### PR TITLE
Fix handling of errors in Darwin framework OTA delegate bridge.

### LINKED ISSUE #20653: [OTA Matter.framework] when a user passes in an error handle is gracefully.
#### Problem
Currently when a caller passes an error back when calling the defined callbacks from MTROTAProviderDelegate, the Matter.framework has a no op with the NSError object. 

 #### Proposed Solution
Ideally check if there is an error passed, and check if the status is not success. If there is an NSError from the caller, and no unsuccessful status, update the status accordingly. 

Code Snippet (NSError is not used):
```
void MTROTAProviderDelegateBridge::HandleQueryImage(chip::app::CommandHandler * commandObj,
    const chip::app::ConcreteCommandPath & commandPath,
    const chip::app::Clusters::OtaSoftwareUpdateProvider::Commands::QueryImage::DecodableType & commandData)
{
    // Make sure to hold on to the command handler and command path to be used in the completion block
    __block chip::app::CommandHandler::Handle handle(commandObj);
    __block chip::app::ConcreteCommandPath cachedCommandPath(
        commandPath.mEndpointId, commandPath.mClusterId, commandPath.mCommandId);

    id<MTROTAProviderDelegate> strongDelegate = mDelegate;
    if ([strongDelegate respondsToSelector:@selector(handleQueryImage:completionHandler:)]) {
        if (strongDelegate && mQueue) {
            auto * commandParams = [[MTROtaSoftwareUpdateProviderClusterQueryImageParams alloc] init];
            ConvertToQueryImageParams(commandData, commandParams);

            dispatch_async(mQueue, ^{
                [strongDelegate handleQueryImage:commandParams
                               completionHandler:^(MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams * _Nullable data,
                                   NSError * _Nullable error) {
                                    if (error) {return;}
                                    dispatch_async(chip::DeviceLayer::PlatformMgrImpl().GetWorkQueue(), ^{
                                        chip::app::Clusters::OtaSoftwareUpdateProvider::Commands::QueryImageResponse::Type response;
                                        ConvertFromQueryImageResponseParms(data, response);

                                        chip::app::CommandHandler * handler = handle.Get();
                                        if (handler) {
                                            handler->AddResponse(cachedCommandPath, response);
                                            handle.Release();
                                        }
                                    });
                               }];
            });
        }
    }
}
```

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
This allows the framework consumer to return an error that will be sent as an error status to the OTA provider client.

Fixes https://github.com/project-chip/connectedhomeip/issues/20653

#### Problem
The callbacks have an `NSError *` argument that is not used in a sane way.

#### Change overview
1. Stop passing in a non-nil NSError from darwin-framework-tool.
2. Convert non-nil NSError into an error status response to the server

#### Testing
1. Modified `handleQueryImageForNodeID` in darwin-framework-tool to pass in a non-null error in the "no OTA image" case allocated like so:
    ```
        auto * error = [[NSError alloc] initWithDomain:MTRInteractionErrorDomain
                                                  code:MTRInteractionErrorCodeFailsafeRequired
                                              userInfo:nil];
    ```
2. Ran the ota-requestor app.
3. Ran darwin-framework-tool in interactive mode, commissioned the ota-requestor app as node id `17`, and ran:
    ```
    otasoftwareupdaterequestor announce-ota-provider ${FRAMEWORK_TOOL_NODE_ID} 0xfff1 0 0 17 0
    ```
4. Observed that the ota-requestor app logged:
    ```
    CHIP: [SWU] Received QueryImage failure response: IM Error 0x000005CA: General error: 0xca (FAILSAFE_REQUIRED)
    ```

### CODE REVIEW

File: examples/darwin-framework-tool/commands/provider/OTAProviderDelegate.mm [hunk 1]
```diff
@@ -46,28 +46,19 @@ - (void)handleQueryImageForNodeID:(NSNumber * _Nonnull)nodeID
...
 
     auto hasCandidate = [self SelectOTACandidate:params.vendorId rPID:params.productId rSV:params.softwareVersion];
     if (!hasCandidate) {
         NSLog(@"Unable to select OTA Image.");
         _selectedCandidate.status = @(MTROtaSoftwareUpdateProviderOTAQueryStatusNotAvailable);
-        error = [[NSError alloc]
-            initWithDomain:@"OTAProviderDomain"
-                      code:MTRErrorCodeInvalidState
-                  userInfo:@{ NSLocalizedDescriptionKey : NSLocalizedString(@"Unable to select Candidate.", nil) }];
+        completionHandler(_selectedCandidate, nil);
```
Comment (krypton36) [inline examples/darwin-framework-tool/commands/provider/OTAProviderDelegate.mm:61]: Is there a reason why we are removing these errors?

Comment (bzbarsky-apple) [reply examples/darwin-framework-tool/commands/provider/OTAProviderDelegate.mm:61]: Because the API contract is changing to "if you pass in a non-nil error, it will get turned into an error status sent to the client".

Comment (krypton36) [reply examples/darwin-framework-tool/commands/provider/OTAProviderDelegate.mm:61]: Thank you for the clarification.

**Review by krypton36 — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
accepted for 1.0: platform change

**Comment by bzbarsky-apple** [comment]
Fast-tracking: has platform owner review (though not recognized by pullapprove), and one other company review.
