### PR TITLE
Fix intermittent BLE connection failures

### LINKED ISSUE #23438: [BUG] Commissioning over BLE often fails due to PBKDFResponse timeout
### Reproduction steps

```bash
1. Build nRF Connect Lighting Example
2. Commission it using chip-tool pairing ble-thread command
```

### Bug prevalence

~80% attempts

### GitHub hash of the SDK that was being used

fac7aae4c8d7c1c916d2a6f54fc9be4dc41ea838

### Platform

nrf

### Platform Version(s)

_No response_

### Anything else?

This is probably caused by https://github.com/project-chip/connectedhomeip/pull/23335/files. After increasing `kExpectedLowProcessingTime` to 10 seconds the problem is gone. I am not sure but the timeout may not take into account the time needed to establish a connection over BLE.

### LINKED ISSUE #23477: Unable to flash M5 board -> {ModuleNotFoundError: No module named 'lark'}
### Reproduction steps

```bash
With SHA 706e9bb14f9931b70c0d4f3478a3460f56ebd099

I am unable to flash M5 board, as I am running into -> ModuleNotFoundError: No module named 'lark'

Steps to reproduce:

1. cd connectedhomeip
2. git reset --hard 706e9bb14f9931b70c0d4f3478a3460f56ebd099
3. git clean -Xdf
4. git submodule update --init
5. export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig"
6. source scripts/bootstrap.sh
7. source scripts/activate.sh
8. cd ${HOME}/tools/esp-idf
9. git checkout v4.4
10. git submodule update --init --recursive
11. ./install.sh
12. . ./export.sh
13. cd ~/connectedhomeip/examples/all-clusters-app/esp32
14. idf.py build
```

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

706e9bb14f9931b70c0d4f3478a3460f56ebd099

### Platform

darwin

### Platform Version(s)

_No response_

### Anything else?

Attaching the log;

[M5_error_log.txt](https://github.com/project-chip/connectedhomeip/files/9932185/M5_error_log.txt)

### PR DESCRIPTION
**Pull request by Damian-Nordic**
1. Rename two BTP constants to match `BTP_CONN_RSP_TIMEOUT` and `BTP_ACK_TIMEOUT` from the spec.
2. Move the constants to BleConfig.h
3. Use `BTP_ACK_TIMEOUT` in both secure and unauthenticated session for ACK timeout calculation.

Fixes #23438

### CODE REVIEW

File: src/ble/BleConfig.h [hunk 1]
```diff
@@ -207,6 +197,25 @@
...
 
+
+/**
+ * @def BTP_CONN_RSP_TIMEOUT
+ *
+ * @brief
+ *   Maximum amount of time, in milliseconds, after sending or receiving a BTP Session Handshake
+ *   request to wait for connection establishment.
+ */
+#define BTP_CONN_RSP_TIMEOUT 15000 // 15 seconds
```
Comment (Damian-Nordic) [inline src/ble/BleConfig.h:208]: In case someone wonders why it doesn't match the spec, see https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/5710.

Comment (andy31415) [reply src/ble/BleConfig.h:209]: it would be nice if constant names would use a suffix to indicate unit, like `BTP_CONN_RSP_TIMEOUT_MS` and `BTP_ACK_TIMEOUT_MS`

Comment (tcarmelveilleux) [reply src/ble/BleConfig.h:209]: The 15s was due to PBKDF being done at runtime during processing of PBKDFParamRequest, back before devices stored verifiers. I think the 5 seconds should actually be done in SDK, since we no longer do PBKDF during message processing.

Comment (Damian-Nordic) [reply src/ble/BleConfig.h]: Added units in the constant names.
@tcarmelveilleux I see, thanks for clarification.

**Review by andy31415 — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]

**Comment by Emill** [comment]
`BTP_CONN_RSP_TIMEOUT` in the spec is set to 5 seconds, but here in the sdk `BTP_CONN_RSP_TIMEOUT_MS` is set to 15 seconds. Should the value in the sdk be changed to 5 seconds or should the spec be updated to say 15 seconds?

I also found `BTP_CONN_IDLE_TIMEOUT` in the spec that does not seem to be referenced anywhere. Should it be removed?

**Comment by bzbarsky-apple** [comment]
@Emill The value in the spec seems to be a default if you have no better idea of what to set the value to, not a requirement.

**Comment by Emill** [comment]
I don't know why the column says "Default" rather than something like "Value".

Allowing implementations to choose custom timeouts would break the protocol:

"The timer’s duration timer SHALL be defined as any value less than one-half the acknowledgement timeout interval. This ensures that on a healthy BLE connection, a peer will always receive acknowledgements for sent packets before its acknowledgement-received timer expires."

If the peers select their own ack timeout, it could happen that one-half ack interval of one peer is longer than the full ack interval of the other peer. In that case the connection would be torn down when idling.

Another section also hints that the timeouts on the two devices are "the same":

"When a client sends a handshake request, it SHALL start a timer with a globally-defined duration of BTP_CONN_RSP_TIMEOUT seconds. If this timer expires before the client receives a handshake response from the server, the client SHALL close the BTP session and report an error to the application. Likewise, a server SHALL start a timer with **the same** duration when it receives a handshake request from a client."

**Comment by bzbarsky-apple** [comment]
That seems like a problem that should get fixed in the spec, then...  @robszewczyk
