### PR TITLE
[app] Implement deferred attribute persister

### LINKED ISSUE #23222: [BUG] Level Control Cluster persists all values during move-to-level
### Reproduction steps

```bash
1. Read persistence storage before level-control move-to-level
2. Perform dimming via level-control move-to-level
3. Read persistence storage after level-control move-to-level

All intermediate values are persisted.

This poses 4 problems:
* Flash wear-out and hard to estimate life-time of a device based on this behaviour.
* Timing of level-control due to write and possibly erase of flash (possibly dependent on platform implementation)
* If a device is switched off and turned on, all other devices doing the dimming will likely have reached the final value, while the device being switched off and turned on will be at an intermediate value and not continue dimming to the final value.
* If a device is automatically controlled (e.g. by illuminance measurements) a device will constantly dim and wear out the flash even faster.

Proposal:
Introduce a new ZAP storage option, e.g. NVM deferred, that delays storage of frequently changed values with a certain duration until the value has stabilized.
```

### Bug prevalence

Every time level-control current-level is changed

### GitHub hash of the SDK that was being used

v1.0

### Platform

nrf, other

### Platform Version(s)

NCS2.0.2

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Damian-Nordic**
Fast-changing attributes with NVM storage, such as CurrentLevel of the LevelControl cluster, may result in rapid flash wearout using the default attribute persister which stores all values immediately.
Implement a helper adapter class for the attribute persistence interface to defer writes of selected attributes.

Use the new class in nRF Connect lighting-app for verification.
Fixes #23222.

### CODE REVIEW

File: src/app/DeferredAttributePersistenceProvider.h [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+#include <lib/support/ScopedBuffer.h>
+#include <lib/support/Span.h>
+
+namespace chip {
+namespace app {
+
+class DeferredAttribute
+{
+public:
+    explicit DeferredAttribute(const ConcreteAttributePath & path) : mPath(path) {}
```
Comment (bzbarsky-apple) [inline src/app/DeferredAttributePersistenceProvider.h:28]: I guess this needs to be a concrete path because if we supported some sort of wildcarding here we'd run into issues with how to store the values?

And this can't be constexpr because the ConcreteAttributePath constructor is not constexpr, I guess?  And even if it were, since we store state we couldn't make the `DeferredAttribute` instances const anyway?

File: src/app/DeferredAttributePersistenceProvider.h [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+public:
+    DeferredAttributePersistenceProvider(AttributePersistenceProvider & persister,
+                                         const Span<DeferredAttribute> & deferredAttributes,
+                                         System::Clock::Milliseconds32 writeDelay) :
+        mPersister(persister),
+        mDeferredAttributes(deferredAttributes), mWriteDelay(writeDelay)
+    {}
+
+    CHIP_ERROR WriteValue(const ConcreteAttributePath & path, const EmberAfAttributeMetadata * metadata, const ByteSpan & value);
+    CHIP_ERROR ReadValue(const ConcreteAttributePath & path, const EmberAfAttributeMetadata * metadata, MutableByteSpan & value);
```
Comment (bzbarsky-apple) [inline src/app/DeferredAttributePersistenceProvider.h:61]: These should be marked `override`, right?

File: src/app/server/Server.h [hunk 3]
```diff
@@ -340,6 +340,8 @@ class Server
 
     Credentials::OperationalCertificateStore * GetOpCertStore() { return mOpCertStore; }
 
+    app::DefaultAttributePersistenceProvider & GetAttributePersister() { return mAttributePersister; }
```
Comment (bzbarsky-apple) [inline src/app/server/Server.h:343]: Should this be called `GetDefaultAttributePersister()`, since it does not get the currently-registered one?

File: src/app/DeferredAttributePersistenceProvider.cpp [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+
+CHIP_ERROR DeferredAttributePersistenceProvider::WriteValue(const ConcreteAttributePath & path,
+                                                            const EmberAfAttributeMetadata * metadata, const ByteSpan & value)
+{
+    for (DeferredAttribute & da : mDeferredAttributes)
+    {
+        if (da.Matches(path))
+        {
+            ReturnErrorOnFailure(da.PrepareWrite(mPersister, metadata, value));
+            DeviceLayer::SystemLayer().StartTimer(System::Clock::Milliseconds32(mWriteDelay), Flush, &da);
```
Comment (bzbarsky-apple) [inline src/app/DeferredAttributePersistenceProvider.cpp:55]: So this will have a separate timer running per attribute, right?  Would it make any sense to have a single timer running if any of the attributes are dirty, then when it fires flush them all?  That would allow us to remove the persister member from `DeferredAttribute`, and might put less pressure on the timer pool...

The fact that the delay is global for the persister but the timers are per-deferred-attribute needs to at least be documented, beause it's very non-obvious.

File: src/app/DeferredAttributePersistenceProvider.cpp [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+    }
+
+    memcpy(mValue.Get(), value.data(), value.size());
+    return CHIP_NO_ERROR;
+}
+
+void DeferredAttribute::Flush()
+{
+    VerifyOrReturn(mValue);
+    mPersister->WriteValue(mPath, mMetadata, ByteSpan(mValue.Get(), mValue.AllocatedSize()));
```
Comment (bzbarsky-apple) [inline src/app/DeferredAttributePersistenceProvider.cpp:43]: I'm a little worried about the metadata pointer here.  What happens if the metadata is for a dynamic endpoint that is removed, and has its metadata deallocated, between when the initial write happens and when the timer fires?

It looks like we mostly pass the metadata to WriteValue for symmetry with ReadValue, and in case it's useful to some persistence implementation.  But `DefaultAttributePersistenceProvider::WriteValue` never uses it.  I wonder whether it makes sense to just pass null here, not store the metadata, and document in `DefaultAttributePersistenceProvider::WriteValue` that if it ever starts using the metadata this part will need to change.

File: src/app/DeferredAttributePersistenceProvider.h (hunk 1 above)
Comment (Damian-Nordic) [reply src/app/DeferredAttributePersistenceProvider.h:28]: Yes, initially I had a more complex implementation which allocated write buffer entries dynamically and put them in intrusive list, but later I thought that in typical use cases there should be few attributes with deferred writes, so I thought the flexibility would not justify the increased flash cost. But I guess I'm OK to change it if it comes handy.

`constexpr` doesn't seem to be useful for this class, yeah.

File: src/app/DeferredAttributePersistenceProvider.h (hunk 2 above)
Comment (Damian-Nordic) [reply src/app/DeferredAttributePersistenceProvider.h:61]: Right, good catch.

File: src/app/server/Server.h (hunk 3 above)
Comment (Damian-Nordic) [reply src/app/server/Server.h:343]: Right, done.

File: src/app/DeferredAttributePersistenceProvider.cpp (hunk 5 above)
Comment (Damian-Nordic) [reply src/app/DeferredAttributePersistenceProvider.cpp:43]: Right, I haven't thought about dynamic endpoints. I can follow your suggestion. Alternatively, maybe we could remove metadata argument from `WriteValue` and that way if it ever gets needed, one will be force to fix all implementations?

File: src/app/DeferredAttributePersistenceProvider.cpp (hunk 4 above)
Comment (Damian-Nordic) [reply src/app/DeferredAttributePersistenceProvider.cpp:55]: My goal was to make sure that if someone calls `Move-To-Level` or any other long-running command that changes an attribute, that attribute is persisted only if the command. So each new write restarts the timer. I wasn't sure if it's OK to restart the flush timer for attribute A when changing attribute B. If it is, I can change it. I can also add timeout member to `DeferredAttribute` and have the timer check which attributes can be written at a given time.

File: src/app/DeferredAttributePersistenceProvider.cpp (hunk 5 above)
Comment (bzbarsky-apple) [reply src/app/DeferredAttributePersistenceProvider.cpp:43]: Removing it for now, since we have no obvious use cases, seems ok to me.

File: src/app/DeferredAttributePersistenceProvider.cpp (hunk 4 above)
Comment (bzbarsky-apple) [reply src/app/DeferredAttributePersistenceProvider.cpp:55]: Ah, I see.  Yes, if we're trying to not write until the attribute goes entirely quiescent (compared to our interval), then this setup makes sense.  I thought we were just trying to throttle.

We should probably clearly document in the API that an attribute will not be written out at all if it never stops changing for the timeout duration...

Or if we're OK with the throttling approach we can just avoid resetting the timer if it's already set and then flush all attributes when the timer fires.  I don't have strong views on which is better; I do think we should have the API clearly document what the behavior is.

Comment (Damian-Nordic) [reply src/app/DeferredAttributePersistenceProvider.cpp:55]: OK, I'll think about it over the weekend and decide on the either approach :) Thanks for the feedback.

Comment (Damian-Nordic) [reply src/app/DeferredAttributePersistenceProvider.cpp]: I documented the current behavior, but I also changed the code to use a single timer no matter how many attributes have writes deferred.

**Review by bzbarsky-apple — APPROVED** [review]

File: examples/lighting-app/nrfconnect/main/AppTask.cpp [hunk 6]
```diff
@@ -89,6 +90,12 @@ bool sHaveBLEConnections                 = false;
 
 chip::DeviceLayer::DeviceInfoProviderImpl gExampleDeviceInfoProvider;
 
+DeferredAttribute gCurrentLevelPersister(ConcreteAttributePath(kLightEndpointId, Clusters::LevelControl::Id,
```
Comment (LuDuda) [inline examples/lighting-app/nrfconnect/main/AppTask.cpp:93]: Could we please add some comments, why we use deffered attribute persister and how it works (just 1-2 sentences)? This is great example for end users to take it and use it in their apps.

**Review by LuDuda — APPROVED** [review]
This is great :+1: Thank you.
