### PR TITLE
[mrp] Fix #17471 - send standalone ack before crypto ops in CASE and PASE.

### LINKED ISSUE #17471: MRP failures trying to commission all-clusters-app on m5stack
#### Problem
Steps to reproduce:
1. Check out ToT (or revision 06c6e06db94e9ee4d7112564cca3eeffc7124afa if desired).
2. Compile chip-all-clusters-app for m5stack and flash it.
3. Compile chip-tool (`scripts/examples/gn_build_example.sh examples/chip-tool out/debug/standalone/` or equivalent)
4. Run `chip-tool pairing ble-wifi ${NODE_ID} ${SSID} ${PASSWORD} 20202021 3840

Expected results: no errors.

Actual results: commissioning does succeed, but before it does that the client prints:
```
[1650316259160] [73458:29505188] CHIP: [SC] Sending Sigma3
[1650316259160] [73458:29505188] CHIP: [EM] Piggybacking Ack for MessageCounter:3203922871 on exchange: 40969i
[1650316259160] [73458:29505188] CHIP: [IN] Prepared unauthenticated message 0x7fe1f7814c68 to 0x0000000000000000 (0)  of type 0x32 and protocolId (0, 0) on exchange 40969i with MessageCounter:2794651821.
[1650316259160] [73458:29505188] CHIP: [IN] Sending unauthenticated msg 0x7fe1f7814c68 with MessageCounter:2794651821 to 0x0000000000000000 at monotonic time: 00000000D66B3854 msec
[1650316259160] [73458:29505188] CHIP: [SC] Sent Sigma3 msg
[1650316259465] [73458:29505188] CHIP: [EM] Retransmitting MessageCounter:2794651821 on exchange 40969i Send Cnt 0
[1650316259465] [73458:29505188] CHIP: [IN] Sending unauthenticated msg 0x7fe1f7814c68 with MessageCounter:2794651821 to 0x0000000000000000 at monotonic time: 00000000D66B3985 msec
[1650316259805] [73458:29505189] CHIP: [EM] Retransmitting MessageCounter:2794651821 on exchange 40969i Send Cnt 1
[1650316259805] [73458:29505189] CHIP: [IN] Sending unauthenticated msg 0x7fe1f7814c68 with MessageCounter:2794651821 to 0x0000000000000000 at monotonic time: 00000000D66B3AD9 msec
[1650316260181] [73458:29505188] CHIP: [EM] Retransmitting MessageCounter:2794651821 on exchange 40969i Send Cnt 2
[1650316260181] [73458:29505188] CHIP: [IN] Sending unauthenticated msg 0x7fe1f7814c68 with MessageCounter:2794651821 to 0x0000000000000000 at monotonic time: 00000000D66B3C52 msec
[1650316260762] [73458:29505189] CHIP: [EM] Failed to Send CHIP MessageCounter:2794651821 on exchange 40969i sendCount: 3 max retries: 3
[1650316262426] [73458:29505189] CHIP: [EM] Received message of type 0x40 with protocolId (0, 0) and MessageCounter:3203922872 on exchange 40969i
[1650316262426] [73458:29505189] CHIP: [EM] Found matching exchange: 40969i, Delegate: 0x7fe1f80cb640
[1650316262426] [73458:29505189] CHIP: [EM] CHIP MessageCounter:2794651821 not in RetransTable on exchange 40969i
[1650316262426] [73458:29505189] CHIP: [SC] Success status report received. Session was established
[1650316262426] [73458:29505189] CHIP: [IN] New secure session created for device 0x0000000000000012, LSID:55323 PSID:17828!
[1650316262426] [73458:29505189] CHIP: [CTL] OperationalDeviceProxy[6817EFE2DA1CD08E:0000000000000012]: State change 3 --> 4
[1650316262426] [73458:29505189] CHIP: [CTL] Finished commissioning step 'FindOperational' with error '../../../examples/chip-tool/third_party/connectedhomeip/src/controller/CHIPDeviceController.cpp:1610: Success'
[1650316262426] [73458:29505189] CHIP: [CTL] Going from commissioning step 'FindOperational' with lastErr = '../../../examples/chip-tool/third_party/connectedhomeip/src/controller/CHIPDeviceController.cpp:1610: Success' --> 'SendComplete'
[1650316262426] [73458:29505189] CHIP: [CTL] Performing next commissioning step 'SendComplete' with completion status = '../../../examples/chip-tool/third_party/connectedhomeip/src/controller/CHIPDeviceController.cpp:1610: Success'
[1650316262426] [73458:29505189] CHIP: [DMG] ICR moving to [AddingComm]
[1650316262426] [73458:29505189] CHIP: [DMG] ICR moving to [AddedComma]
[1650316262426] [73458:29505189] CHIP: [IN] Prepared secure message 0x7fe1f7814c68 to 0x0000000000000012 (1)  of type 0x8 and protocolId (0, 1) on exchange 40970i with MessageCounter:14020799.
[1650316262426] [73458:29505189] CHIP: [IN] Sending encrypted msg 0x7fe1f7814c68 with MessageCounter:14020799 to 0x0000000000000012 (1) at monotonic time: 00000000D66B4516 msec
[1650316262426] [73458:29505189] CHIP: [DMG] ICR moving to [CommandSen]
[1650316262426] [73458:29505189] CHIP: [EM] Sending Standalone Ack for MessageCounter:3203922872 on exchange 40969i
[1650316262426] [73458:29505189] CHIP: [IN] Prepared unauthenticated message 0x70000c82b4d0 to 0x0000000000000000 (0)  of type 0x10 and protocolId (0, 0) on exchange 40969i with MessageCounter:2794651822.
[1650316262426] [73458:29505189] CHIP: [IN] Sending unauthenticated msg 0x70000c82b4d0 with MessageCounter:2794651822 to 0x0000000000000000 at monotonic time: 00000000D66B4517 msec
[1650316262426] [73458:29505189] CHIP: [EM] Flushed pending ack for MessageCounter:3203922872 on exchange 40969i
[1650316262466] [73458:29505189] CHIP: [EM] Received message of type 0x10 with protocolId (0, 0) and MessageCounter:3203922873 on exchange 40969i
[1650316262466] [73458:29505189] CHIP: [EM] OnMessageReceived failed, err = ../../../examples/chip-tool/third_party/connectedhomeip/src/messaging/ExchangeMgr.cpp:268: CHIP Error 0x00000070: Unsolicited msg with originator bit clear
[1650316262528] [73458:29505189] CHIP: [EM] Received message of type 0x10 with protocolId (0, 0) and MessageCounter:3203922874 on exchange 40969i
[1650316262528] [73458:29505189] CHIP: [EM] OnMessageReceived failed, err = ../../../examples/chip-tool/third_party/connectedhomeip/src/messaging/ExchangeMgr.cpp:268: CHIP Error 0x00000070: Unsolicited msg with originator bit clear
[1650316262559] [73458:29505189] CHIP: [EM] Received message of type 0x10 with protocolId (0, 0) and MessageCounter:3203922875 on exchange 40969i
[1650316262559] [73458:29505189] CHIP: [EM] OnMessageReceived failed, err = ../../../examples/chip-tool/third_party/connectedhomeip/src/messaging/ExchangeMgr.cpp:268: CHIP Error 0x00000070: Unsolicited msg with originator bit clear
[1650316262636] [73458:29505189] CHIP: [EM] Received message of type 0x9 with protocolId (0, 1) and MessageCounter:13811505 on exchange 40970i
```
and the server prints:
```
I (35990) chip[IN]: Sending unauthenticated msg 0x3ffca544 with MessageCounter:3203922871 to 0x0000000000000000 at monotonic time: 0000000000008961 msec
I (36010) chip[SC]: Sent Sigma2 msg
E (36010) chip[DL]: Long dispatch time: 1649 ms, for event type 3
I (36010) chip[BLE]: Releasing end point's BLE connection back to application.
E (36020) chip[BLE]: HandleChipConnectionReceived failed, err = d
E (36020) chip[BLE]: failed handle new chip BLE connection, status = d
I (36220) chip[EM]: Received message of type 0x32 with protocolId (0, 0) and MessageCounter:2794651821 on exchange 40969r
I (36220) chip[EM]: Received message of type 0x32 with protocolId (0, 0) and MessageCounter:2794651821 on exchange 40969r
I (36220) chip[SC]: Received Sigma3 msg
W (37750) ROUTE_HOOK: Ignore invalid ICMP packet
E (39410) chip[SC]: Unable to save session resumption state: a0
I (39420) chip[IN]: Prepared unauthenticated message 0x3ffca544 to 0x0000000000000000 (0)  of type 0x40 and protocolId (0, 0) on exchange 40969r with MessageCounter:3203922872.
I (39430) chip[IN]: Sending unauthenticated msg 0x3ffca544 with MessageCounter:3203922872 to 0x0000000000000000 at monotonic time: 00000000000096CF msec
I (39440) chip[IN]: CASE Session established. Setting up the secure channel.
I (39460) chip[IN]: CASE secure channel is available now.
I (39460) chip[IN]: CASE Server enabling CASE session setups
E (39460) chip[DL]: Long dispatch time: 3244 ms, for event type 3
I (39470) chip[EM]: Received message of type 0x32 with protocolId (0, 0) and MessageCounter:2794651821 on exchange 40969r
I (39490) chip[IN]: Prepared unauthenticated message 0x3ffe7734 to 0x0000000000000000 (0)  of type 0x10 and protocolId (0, 0) on exchange 40969r with MessageCounter:3203922873.
I (39500) chip[IN]: Sending unauthenticated msg 0x3ffe7734 with MessageCounter:3203922873 to 0x0000000000000000 at monotonic time: 0000000000009717 msec
I (39520) chip[EM]: Received message of type 0x32 with protocolId (0, 0) and MessageCounter:2794651821 on exchange 40969r
I (39530) chip[IN]: Prepared unauthenticated message 0x3ffe7734 to 0x0000000000000000 (0)  of type 0x10 and protocolId (0, 0) on exchange 40969r with MessageCounter:3203922874.
I (39540) chip[IN]: Sending unauthenticated msg 0x3ffe7734 with MessageCounter:3203922874 to 0x0000000000000000 at monotonic time: 0000000000009743 msec
I (39560) chip[EM]: Received message of type 0x32 with protocolId (0, 0) and MessageCounter:2794651821 on exchange 40969r
I (39560) chip[IN]: Prepared unauthenticated message 0x3ffe7734 to 0x0000000000000000 (0)  of type 0x10 and protocolId (0, 0) on exchange 40969r with MessageCounter:3203922875.
I (39590) chip[IN]: Sending unauthenticated msg 0x3ffe7734 with MessageCounter:3203922875 to 0x0000000000000000 at monotonic time: 000000000000976E msec
```

Git bisect says this started with #17003.  @turon 

 #### Proposed Solution
Figure out what's going on and why we are not seeing our acks in a timely manner.

### PR DESCRIPTION
**Pull request by turon**
Fix #17471 

- Added CHIP_DEVICE_CONFIG_SLOW_CRYPTO with default of 1
- Force send a standalone ack response to all CASE and PASE when above flag enabled.
- Adjusted expected # of expected packets in CASE and PASE tests.

#### Problem
CASE and PASE senders are getting excessive retries due to crypto operations delaying acknowledgement.

#### Testing
CI primarily

### CODE REVIEW

File: src/lib/core/CHIPConfig.h [hunk 1]
```diff
@@ -707,6 +707,17 @@
 #define CHIP_CONFIG_MAX_GROUP_CONTROL_PEERS 2
 #endif // CHIP_CONFIG_MAX_GROUP_CONTROL_PEER
 
+/**
+ *  @def CHIP_CONFIG_SLOW_CRYPTO
+ *
+ *  @brief
+ *   When enabled, CASE and PASE setup will proactively send standalone acknowledgements
+ *   prior to engaging in crypto operations.
```
Comment (tcarmelveilleux) [inline src/lib/core/CHIPConfig.h:715]: Add "because their processing delay far exceeds standalone ACK delay. If CASE and PASE succeeds in less than 300ms, set this to 0".

Suggest making this 0 on Linux/Darwin by default to avoid too many needless standalone ACKs from controllers.

File: src/protocols/secure_channel/CASESession.cpp [hunk 2]
```diff
@@ -1642,6 +1642,10 @@ CHIP_ERROR CASESession::OnMessageReceived(ExchangeContext * ec, const PayloadHea
     Protocols::SecureChannel::MsgType msgType = static_cast<Protocols::SecureChannel::MsgType>(payloadHeader.GetMessageType());
     SuccessOrExit(err);
 
+#if CHIP_CONFIG_SLOW_CRYPTO
+    ReturnErrorOnFailure(mExchangeCtxt->SendStandaloneAckMessage());
+#endif // CHIP_CONFIG_SLOW_CRYPTO
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1647]: Please only send on Sigma*, not statusreport

File: src/protocols/secure_channel/PASESession.cpp [hunk 3]
```diff
@@ -803,6 +803,10 @@ CHIP_ERROR PASESession::OnMessageReceived(ExchangeContext * exchange, const Payl
     CHIP_ERROR err = ValidateReceivedMessage(exchange, payloadHeader, msg);
     SuccessOrExit(err);
 
+#if CHIP_CONFIG_SLOW_CRYPTO
+    ReturnErrorOnFailure(mExchangeCtxt->SendStandaloneAckMessage());
+#endif // CHIP_CONFIG_SLOW_CRYPTO
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/PASESession.cpp:808]: Please send only if it's not statusreport

File: src/protocols/secure_channel/CASESession.cpp (hunk 2 above)
Comment (turon) [reply src/protocols/secure_channel/CASESession.cpp]: fixed

File: src/protocols/secure_channel/PASESession.cpp (hunk 3 above)
Comment (turon) [reply src/protocols/secure_channel/PASESession.cpp]: fixed

File: src/protocols/secure_channel/PASESession.cpp [hunk 4]
```diff
@@ -800,10 +800,19 @@ CHIP_ERROR PASESession::OnUnsolicitedMessageReceived(const PayloadHeader & paylo
...
+    CHIP_ERROR err  = ValidateReceivedMessage(exchange, payloadHeader, msg);
+    MsgType msgType = static_cast<MsgType>(payloadHeader.GetMessageType());
     SuccessOrExit(err);
 
-    switch (static_cast<MsgType>(payloadHeader.GetMessageType()))
+#if CHIP_CONFIG_SLOW_CRYPTO
+    if (msgType == MsgType::PBKDFParamRequest || msgType == MsgType::PBKDFParamResponse || msgType == MsgType::PASE_Pake1 ||
+        msgType == MsgType::PASE_Pake2 || msgType == MsgType::PASE_Pake3)
+    {
+        SuccessOrExit(mExchangeCtxt->SendStandaloneAckMessage());
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/PASESession.cpp:811]:
```suggestion
        SuccessOrExit(mExchangeCtxt->FlushAcks());
```

File: src/protocols/secure_channel/CASESession.cpp [hunk 5]
```diff
@@ -1642,6 +1642,15 @@ CHIP_ERROR CASESession::OnMessageReceived(ExchangeContext * ec, const PayloadHea
     Protocols::SecureChannel::MsgType msgType = static_cast<Protocols::SecureChannel::MsgType>(payloadHeader.GetMessageType());
     SuccessOrExit(err);
 
+#if CHIP_CONFIG_SLOW_CRYPTO
+    if (msgType == Protocols::SecureChannel::MsgType::CASE_Sigma1 || msgType == Protocols::SecureChannel::MsgType::CASE_Sigma2 ||
+        msgType == Protocols::SecureChannel::MsgType::CASE_Sigma2Resume ||
+        msgType == Protocols::SecureChannel::MsgType::CASE_Sigma3)
+    {
+        ReturnErrorOnFailure(mExchangeCtxt->SendStandaloneAckMessage());
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:1650]:
```suggestion
        SuccessOrExit(mExchangeCtxt->FlushAcks());
```
The right thing to call is FlushAcks. Because `SendStandaloneAckMessage` will send an ack even if an ack is not pending.

`SendStandaloneAckMessage` shouldn't even be public API... :(

**Review by bzbarsky-apple — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by emargolis — APPROVED** [review]

File: src/lib/core/CHIPConfig.h (hunk 1 above)
Comment (turon) [reply src/lib/core/CHIPConfig.h:715]: Updated config of Linux/Darwin to assume fast crypto on those platforms.
