### PR TITLE
Make ota provider cancel bdx transfer on sigterm provider changes only

### LINKED ISSUE #685: OTA: Provider cannot gracefully cancel a BDX transfer during OTA update
### Summary
During OTA testing, when the Provider is killed mid-BDX transfer, the Requestor gets stuck in the `Downloading` state and cannot start a new download, even if a new Provider is launched. The default Requestor timeout to return to `Idle` is 6 hours (not mandated by the spec).

Currently, there is no way to gracefully cancel a BDX transfer. A graceful cancel would require the Provider to send a `StatusReport` to the Requestor.

**Note:** _“No way to gracefully cancel a BDX transfer”_ = the Requestor cannot automatically stop and return to Idle if the Provider is killed, because a graceful cancel requires the Provider to send a StatusReport, which is not possible once it is gone.

**Proposed solution:**
- Implement Provider-side functionality to send a StatusReport to gracefully cancel the BDX transfer.
- Requestor should immediately return to Idle after receiving the cancel.

**References:**
[DefaultOTARequestorDriver.cpp in SDK](https://github.com/project-chip/connectedhomeip/blob/8c26f1657836732adad8ba4c9a0354ddce9bc2db/src/app/clusters/ota-requestor/DefaultOTARequestorDriver.cpp#L137)

### Reproduce Test
To reproduce the test, please follow the prerequisites and test steps described below.

#### Prerequisite: Build and run Matter Project
```bash
# Setup your Python environment
# Run Bootstrap
source scripts/bootstrap.sh
# Activate
source scripts/activate.sh
# Env
source out/python_env/bin/activate
```

#### Prerequisite: OTA

**Build  Components:**
```bash
# Build OTA Provider
scripts/examples/gn_build_example.sh examples/ota-provider-app/linux out/debug chip_config_network_layer_ble=false

# Build OTA Requestor
scripts/examples/gn_build_example.sh examples/ota-requestor-app/linux out/debug chip_config_network_layer_ble=false

# Build Chip Tool
scripts/examples/gn_build_example.sh examples/chip-tool out/chiptool 'chip_mdns="platform"'
  ```
**Create OTA Images: (these are just a stubs)**
```bash
# Create different firmware versions
echo "v1.0 firmware" > firmware_v1.bin
echo "v2.0 firmware" > firmware_v2.bin

# Generate OTA images
python3 src/app/ota_image_tool.py create -v 0xFFF1 -p 0x8001 -vn 1 -vs "1.0" -da sha256 firmware_v1.bin firmware_v1.ota
python3 src/app/ota_image_tool.py create -v 0xFFF1 -p 0x8001 -vn 2 -vs "2.0" -da sha256 firmware_v2.bin firmware_v2.ota

# Create some dirs for storage to avoid conflicts
mkdir /tmp/chip_tool_requestor
mkdir /tmp/chip_tool_provider 
```
#### Run Test

```bash
# Terminal 1: Start OTA Provider
./out/debug/chip-ota-provider-app --filepath firmware_requestor_v2.ota \
    --discriminator 1111 \
    --passcode 20202021 \
    --secured-device-port 5540

# Terminal 2: Commission the Provider using Node ID 1
./out/chiptool/chip-tool pairing onnetwork 1 20202021

# Terminal 3: Start OTA Requestor (with different KVS and port)
./out/debug/chip-ota-requestor-app --discriminator 1234 --passcode 20202021 --secured-device-port 5541 --autoApplyImage --KVS /tmp/chip_kvs_requestor 

# Terminal 2: Commission requestor
./out/chiptool/chip-tool pairing onnetwork 2 20202021

# Terminal 2: Configure requestor wit the default OTA provider (last 2 digits are requestor node id and endpoint id)
./out/chiptool/chip-tool otasoftwareupdaterequestor write default-otaproviders '[{"fabricIndex": 1, "providerNodeID": 1, "endpoint": 0}]' 2 0

# Terminal 2: Configure OTA Provider ACL (I can decipher that but basically it's needed to allow nodes send cluster commands to OTA Provider)
./out/chiptool/chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": null}, {"fabricIndex": 1, "privilege": 3, "authMode": 2, "subjects": null, "targets": null}]' 1 0

# Terminal 2: Initiate OTA update
./out/chiptool/chip-tool otasoftwareupdaterequestor announce-otaprovider 1 0 0 0 2 0

# Terminal 1: Kill the Provider
Close Provider terminal
```

**Actual Results**
Observe that the Requestor remains stuck in `Downloading` and does not return to `Idle`.

### PR DESCRIPTION
**Pull request by gd-mauri**
### Summary

This PR is focused on giving OTA Provider the ability to gracefully cancel a BDX transfer. 
This way requestor side doesn't get stuck waiting for sender (responder) side on a Software Update session.
Fixes: [#685](https://github.com/project-chip/matter-test-scripts/issues/685)

### Testing
Please see [ISSUE](https://github.com/project-chip/matter-test-scripts/issues/685) `Run Test` section

___

In the following screenshot there are 4 `ota-requestor-app` events marked in yellow:

1. Status Report (`[BDX] BDX StatusReport 5f`) 
2. `DefaultOTARequestor::RecordNewUpdateState()` sets cluster to `kIdle`
3. `DefaultOTARequestorDriver::HandleIdleStateEnter()` gets called
4. SWU starts its periodic query timer to `86400 seconds`

Captura de pantalla 2025-10-07 a la(s) 9 56 07 a  m

### CODE REVIEW

**Review by cecille — APPROVED** [review]

File: examples/ota-provider-app/linux/main.cpp [hunk 1]
```diff
@@ -407,9 +407,31 @@ void ApplicationInit()
...
+    {
+        chip::DeviceLayer::PlatformMgr().ScheduleWork([](intptr_t) {
+            ChipLogDetail(SoftwareUpdate, "Scheduling BdxOtaSender to ABORT TRANSFER");
+
+            gOtaProvider.GetBdxOtaSender()->AbortTransfer();
+        });
+
+        chip::Server::GetInstance().GenerateShutDownEvent();
+
+        chip::DeviceLayer::PlatformMgr().ScheduleWork([](intptr_t) { chip::DeviceLayer::PlatformMgr().StopEventLoopTask(); });
```
Comment (andy31415) [inline examples/ota-provider-app/linux/main.cpp]: Why the split? Schedule work will run async, so this would rely on sequencing. Could we combine the two schedulework?

Comment (gd-mauri) [reply examples/ota-provider-app/linux/main.cpp]: consolidated both calls to schedule work into first one.

**Review by andy31415 — APPROVED** [review]
