### PR TITLE
[Darwin] MTRDevice should retry subscription when getSessionForNode fails

### LINKED ISSUE #23975: [Darwin] Improve MTRDevice logging
### Reproduction steps

```bash
As title says - MTRDevice logging can be improved with more details to help debugging.
```

### Platform

darwin

### Platform Version(s)

1.0

### Type

Platform validated

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### LINKED ISSUE #23978: [Darwin] MTRDevice should retry subscription when getSessionForNode fails
### Reproduction steps

```bash
1. Create MTRDevice and set delegate while being unable to talk to accessory
2. Subscription fails and never retries
```

### Platform

darwin

### Platform Version(s)

1.0

### Type

Platform validated

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jtung-apple**
Fixes #23978 
Also fixes #23975 

Changes details:
* When `getSessionForNode` fails in `MTRDevice _setupSubscription`, instead of only signaling error, also signal reset, which means "the subscription has gone away". And as long as a delegate object exists, that means a subscription is needed, and so a retry would be scheduled with exponential back off.
* Added logging for #23975

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 1]
```diff
@@ -181,7 +194,19 @@ - (void)setDelegate:(id<MTRDeviceDelegate>)delegate queue:(dispatch_queue_t)queu
 
     _weakDelegate = [MTRWeakReference weakReferenceWithObject:delegate];
     _delegateQueue = queue;
-    [self setupSubscription];
+    [self _setupSubscription];
+
+    MTR_LOG_INFO("%@ setDelegate %@", self, delegate);
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:199]: Probably worth logging this outside the lock being held, just to minimize how much we do under the lock.

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 2]
```diff
@@ -223,6 +252,9 @@ - (void)_handleResubscriptionNeeded
 
     _state = MTRDeviceStateUnknown;
 
+    // reset unreported events to avoid sending noncontiguous set of events
+    _unreportedEvents = nil;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:256]: This part does not make sense to me.  Why are we doing that?

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 3]
```diff
@@ -130,12 +130,18 @@ - (id)strongObject
...
 @property (nonatomic, readonly) os_unfair_lock lock; // protects the caches and device state
+@property (nonatomic) chip::FabricIndex fabricIndex;
 @property (nonatomic) MTRWeakReference<id<MTRDeviceDelegate>> * weakDelegate;
 @property (nonatomic) dispatch_queue_t delegateQueue;
 @property (nonatomic) NSArray<NSDictionary<NSString *, id> *> * unreportedEvents;
 
 @property (nonatomic) BOOL subscriptionActive;
 
+#define MTRDEVICE_SUBSCRIPTION_ATTEMPT_MIN_WAIT (1)
+#define MTRDEVICE_SUBSCRIPTION_ATTEMPT_MAX_WAIT (3600)
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:141]: Please document units.

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 4]
```diff
@@ -235,7 +267,38 @@ - (void)_handleResubscriptionNeeded
...
+    self.reattemptingSubscription = YES;
+
+    if (_lastSubscriptionAttemptWait < MTRDEVICE_SUBSCRIPTION_ATTEMPT_MIN_WAIT) {
+        _lastSubscriptionAttemptWait = MTRDEVICE_SUBSCRIPTION_ATTEMPT_MIN_WAIT;
+    } else {
+        _lastSubscriptionAttemptWait *= 2;
+    }
+
+    MTR_LOG_INFO("%@ scheduling to reattempt subscription in %u seconds", self, _lastSubscriptionAttemptWait);
+    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(_lastSubscriptionAttemptWait * NSEC_PER_SEC)), self.queue, ^{
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:293]:
```suggestion
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, static_cast<int64_t>(_lastSubscriptionAttemptWait) * NSEC_PER_SEC), self.queue, ^{
```
seems like the right thing... Otherwise the multiplication can overflow before we ever cast to 64-bit, depending on what the type of NSEC_PER_SEC is.

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 5]
```diff
@@ -235,7 +267,38 @@ - (void)_handleResubscriptionNeeded
 
 - (void)_handleSubscriptionReset
 {
-    // TODO: logic to reattempt subscription with exponential back off
+    os_unfair_lock_lock(&self->_lock);
+    // if there is no delegate then also do not retry
+    id<MTRDeviceDelegate> delegate = _weakDelegate.strongObject;
+    if (!delegate) {
+        MTR_LOG_INFO("%@ no delegate - do not reattempt subscription", self);
+        return;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:275]: This, and other early returns in this function, are leaking the lock locked.

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 6]
```diff
@@ -284,122 +348,125 @@ - (void)_handleEventReport:(NSArray<NSDictionary<NSString *, id> *> *)eventRepor
...
+                                          dispatch_async(self.queue, ^{
+                                              // OnSubscriptionEstablished
+                                              [self _handleSubscriptionEstablished];
+                                          });
+                                      },
+                                      ^(void) {
+                                          MTR_LOG_INFO("%@ got subscription done", self);
+                                          dispatch_async(self.queue, ^{
+                                              // OnDone
+                                              [self _handleSubscriptionReset];
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:446]: Do we really want to schedule a resubscribe in OnDone?  I guess we are relying on the "If this is being triggered from shutdown then invalidate would have been called already and we won't try to resubscribe because we will not have a delegate" bit?

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 2 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:256]: You are right! Deleting this.

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 6 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:448]: OK, sounds good.

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
Fast-tracking platform-specific change with platform owner review.

**Review by andy31415 — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
