### PR TITLE
[Darwin] MTRDevice write should reset expected value on error

### LINKED ISSUE #23620: [Darwin] MTRDevice write should reset expected value on error
### Reproduction steps

```bash
1. Call write API on MTRDevice write
2. Have write return error for any reason
3. See the expected value remain until interval elapses
```

### Platform

darwin

### Platform Version(s)

1.0

### Type

Platform validated

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jtung-apple**
Fixes #23620

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 1]
```diff
@@ -730,16 +733,16 @@ - (void)writeAttributeWithEndpointID:(NSNumber *)endpointID
                               completion:^(NSArray<NSDictionary<NSString *, id> *> * _Nullable values, NSError * _Nullable error) {
                                   MTR_LOG_INFO("%@ completion error %@ endWork", logPrefix, error);
                                   [workItem endWork];
+                                  if (error) {
+                                      [self removeExpectedValuesForAttributePath:attributePath];
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:737]: There's an edge case here where we write value A for a path, then write value B, then the first write fails and the second write succeeds.  Is it worth tracking some sort of "we are responsible for this expected value" state, or should we just not worry about this case?

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 2]
```diff
@@ -1044,6 +1077,29 @@ - (void)setExpectedValues:(NSArray<NSDictionary<NSString *, id> *> *)values expe
...
+    os_unfair_lock_lock(&self->_lock);
+    BOOL shouldReportValue;
+    NSDictionary<NSString *, id> * attributeValueToReport;
+    [self _setExpectedValue:nil
+                 attributePath:attributePath
+                expirationTime:nil
+             shouldReportValue:&shouldReportValue
+        attributeValueToReport:&attributeValueToReport];
+
+    MTR_LOG_INFO("%@ remove expected values for path %@ should report %@", self, attributePath, shouldReportValue ? @"YES" : @"NO");
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:1091]:
```suggestion
    MTR_LOG_INFO("%@ remove expected value for path %@ should report: %@", self, attributePath, shouldReportValue ? @"YES" : @"NO");
```

File: src/darwin/Framework/CHIPTests/MTRDeviceTests.m [hunk 3]
```diff
@@ -1402,6 +1402,45 @@ - (void)test017_TestMTRDeviceBasics
...
+        }
+    };
+
+    NSDictionary * writeValue = [NSDictionary
+        dictionaryWithObjectsAndKeys:@"UnsignedInteger", @"type", [NSNumber numberWithUnsignedInteger:200], @"value", nil];
+    [device writeAttributeWithEndpointID:testEndpointID
+                               clusterID:testClusterID
+                             attributeID:testAttributeID
+                                   value:writeValue
+                   expectedValueInterval:@(20)
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIPTests/MTRDeviceTests.m:1433]: This is 20ms, right?

File: src/darwin/Framework/CHIPTests/MTRDeviceTests.m [hunk 4]
```diff
@@ -1402,6 +1402,45 @@ - (void)test017_TestMTRDeviceBasics
...
+                       timedWriteTimeout:nil];
+
+    // expected value interval is 20 but expect it get reverted immediately as the write fails
+    [self waitForExpectations:@[ expectedValueReportedExpectation, expectedValueRemovedExpectation ] timeout:5 enforceOrder:YES];
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIPTests/MTRDeviceTests.m:1437]: This timeout is 5s.

Should we perhaps be using an expected value interval longer than 5s to really test this?

**Comment by jtung-apple** [comment]
Rebased to current master and addressed review comments with substantial change.

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 1 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm]: The latest change addresses this by associating expected values with an ID, return it, and have removal confirm the ID to remove.

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 2 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm]: Should be fixed as part of the latest changes

File: src/darwin/Framework/CHIPTests/MTRDeviceTests.m [hunk 5]
```diff
@@ -1402,6 +1402,45 @@ - (void)test017_TestMTRDeviceBasics
...
+    NSDictionary * writeValue = [NSDictionary
+        dictionaryWithObjectsAndKeys:@"UnsignedInteger", @"type", [NSNumber numberWithUnsignedInteger:200], @"value", nil];
+    [device writeAttributeWithEndpointID:testEndpointID
+                               clusterID:testClusterID
+                             attributeID:testAttributeID
+                                   value:writeValue
+                   expectedValueInterval:@(20)
+                       timedWriteTimeout:nil];
+
+    // expected value interval is 20 but expect it get reverted immediately as the write fails
```
[the remark this answers is not in the document]
Comment (jtung-apple) [reply src/darwin/Framework/CHIPTests/MTRDeviceTests.m]: Added comment that this should fail because it's writing to a nonexistent attribute.

File: src/darwin/Framework/CHIPTests/MTRDeviceTests.m (hunk 3 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIPTests/MTRDeviceTests.m]: Thank you for catching this. I've changed this to 20000 for 20s.

File: src/darwin/Framework/CHIPTests/MTRDeviceTests.m (hunk 4 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIPTests/MTRDeviceTests.m:1438]: I've changed the expectedValueInterval to 20000 / 20 seconds.

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 6]
```diff
@@ -200,9 +186,11 @@ @interface MTRDevice ()
 // See MTRDeviceResponseHandler definition for value dictionary details.
 @property (nonatomic) NSMutableDictionary<MTRAttributePath *, NSDictionary *> * readCache;
 
-// Expected value cache is attributePath => MTRPair of [NSDate of expiration time, NSDictionary of value]
+// Expected value cache is attributePath => NSArray of [NSDate of expiration time, NSDictionary of value, expected value ID]
+//   - MTRDeviceExpectedValueFieldIndex
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:190]:
```suggestion
//   - See MTRDeviceExpectedValueFieldIndex for the definitions of indices into this array.
```

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 7]
```diff
@@ -200,9 +186,11 @@ @interface MTRDevice ()
...
 // See MTRDeviceResponseHandler definition for value dictionary details.
-@property (nonatomic) NSMutableDictionary<MTRAttributePath *, MTRPair<NSDate *, NSDictionary *> *> * expectedValueCache;
+@property (nonatomic) NSMutableDictionary<MTRAttributePath *, NSArray *> * expectedValueCache;
+@property (nonatomic) uint64_t expectedValueNextID;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:193]: This could really use some documentation....

Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:193]: This could really use some documentation....

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 8]
```diff
@@ -995,47 +999,102 @@ - (NSArray *)_getAttributesToReportWithReportedValues:(NSArray<NSDictionary<NSSt
...
+
+        // No need to report if new and previous expected value are both nil
+    }
+
+    if (expectedAttributeValue) {
+        _expectedValueCache[attributePath] = @[ expirationTime, expectedAttributeValue, @(expectedValueID) ];
+    } else if (previousExpectedValue) {
+        // Remove previous expected value only if it's from the same setExpectedValues operation
+        NSNumber * previousExpectedValueID = previousExpectedValue[MTRDeviceExpectedValueFieldIDIndex];
+        if (previousExpectedValueID.unsignedLongLongValue == expectedValueID) {
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:1046]: If this tests false, shouldn't we reset `*shouldReportValue` to `NO`?   Or check for this condition earlier or something....

As in, perhaps we should check for this condition pretty early on and take an early return if it holds, so that we don't have to worry about it here or in the "figure out value to report" logic above.

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 9]
```diff
@@ -995,47 +999,102 @@ - (NSArray *)_getAttributesToReportWithReportedValues:(NSArray<NSDictionary<NSSt
...
 
     return attributesToReport;
 }
 
 - (void)setExpectedValues:(NSArray<NSDictionary<NSString *, id> *> *)values expectedValueInterval:(NSNumber *)expectedValueInterval
+{
+    [self setExpectedValues:values expectedValueInterval:expectedValueInterval expectedValueID:nil];
+}
+
+// expectedValueID is an out-argument that returns
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:1094]: returns what?

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 8 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:1046]: Hmm you're right. I'll move this logic.

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 9 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm]: Fixed comment in latest commit.

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 8 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm]: Fixed in latest commit.

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
Fast-tracking platform-specific change with platform owner review.
