### PR TITLE
Fix bootstrap if repository path contains symlinks.

### LINKED ISSUE #31851: [Build] [Python] Cannot finish activate.sh
### Reproduction steps

Step-by-step commands as follows.
- `git clone https://github.com/project-chip/connectedhomeip.git`
- `cd connectedhomeip && git checkout 181b0cb`
- `git submodule update --init`
- `source scripts/activate.sh`

Please check attached log for more details about failing of `source scripts/activate.sh`. 
[matter_console.log](https://github.com/project-chip/connectedhomeip/files/14134497/matter_console.log)

### Bug prevalence

Every time

### GitHub hash of the SDK that was being used

181b0cb

### Platform

other

### Platform Version(s)

Ubuntu 22.04.3 LTS

### Type

Platform Issue

### Anything else?

Wipe original hard drive before installing a brand new Ubuntu (22.04.3 LTS).
Follow the build guide to set up a build environment and start a build by referring to the link below.
- https://project-chip.github.io/connectedhomeip-doc/guides/BUILDING.html#build-for-the-host-os-linux-or-macos

Launch `source scripts/activate.sh` and an Assertion failed with related exception or traceback messages come out...
>   Setting up Python environment.....[\]
ERROR at /home/angus/projects/connectedhomeip/third_party/pigweed/repo/pw_build/facade.gni:187:7: Assertion failed.
      assert(_dep_is_in_link_dependencies,
      ^-----
/home/angus/projects/connectedhomeip/third_party/pigweed/repo/pw_log:impl must be listed in the pw_build_LINK_DEPS build arg when the /home/angus/projects/connectedhomeip/third_party/pigweed/repo/pw_log:pw_log facade is in use. Please update your toolchain configuration.
See /home/angus/projects/connectedhomeip/third_party/pigweed/repo/pw_log/BUILD.gn:47:1: whence it was called.
pw_facade("pw_log") {
^--------------------
See /home/angus/projects/connectedhomeip/third_party/pigweed/repo/pw_env_setup/BUILD.gn:50:5: which caused the file to be included.
    "$dir_pw_log:protos.python",
    ^--------------------------
['gn', 'gen', '/home/angus/projects/connectedhomeip/.environment/gn_out', '--args=chip_crypto="boringssl" dir_pigweed="/home/angus/projects/connectedhomeip/third_party/pigweed/repo"']

> Traceback (most recent call last):
  File "/home/angus/projects/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 402, in install_packages
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gn', 'gen', '/home/angus/projects/connectedhomeip/.environment/gn_out', '--args=chip_crypto="boringssl" dir_pigweed="/home/angus/projects/connectedhomeip/third_party/pigweed/repo"']' returned non-zero exit status 1.

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/home/angus/projects/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 995, in <module>
    sys.exit(main())
  File "/home/angus/projects/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 987, in main
    return EnvSetup(**vars(parse())).setup()
  File "/home/angus/projects/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 577, in setup
    result = step(spin)
  File "/home/angus/projects/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 766, in virtualenv
    if not virtualenv_setup.install(
  File "/home/angus/projects/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 443, in install
    install_packages(gn_target)
  File "/home/angus/projects/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 410, in install_packages
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['gn', 'gen', '/home/angus/projects/connectedhomeip/.environment/gn_out', '--args=chip_crypto="boringssl" dir_pigweed="/home/angus/projects/connectedhomeip/third_party/pigweed/repo"']' returned non-zero exit status 1.
... ...

Is there still anything missing in my Python configuration?
Thanks for comments if any.
-Angus

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Pigweed seems to fail with:

    ERROR at /home/angus/projects/connectedhomeip/third_party/pigweed/repo/pw_build/facade.gni:187:7: Assertion failed.
    assert(_dep_is_in_link_dependencies,

when the repo path has symlinks in it and bootstrap is run.

The workaround is to change to the symlink-resolved path temporarily while doing the pigweed parts of bootstrap.sh.

Fixes https://github.com/project-chip/connectedhomeip/issues/31851

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]

**Review by tehampson — APPROVED** [review]

File: scripts/setup/bootstrap.sh [hunk 1]
```diff
@@ -167,8 +167,14 @@ EOF
 # bootstrap or run_in_build_env.sh can be executed in a build env
 _ORIGINAL_PW_ENVIRONMENT_ROOT="$PW_ENVIRONMENT_ROOT"
 
+# pigweed does not seem to handle pwd involving symlinks very well.
```
Comment (ksperling-apple) [inline scripts/setup/bootstrap.sh:170]: What's the actual problem we're fixing here? If Pigweed doesn't tolerate having symlinks anywhere in PWD that sounds like a Pigweed bug.

File: scripts/setup/bootstrap.sh [hunk 2]
```diff
@@ -167,8 +167,14 @@ EOF
...
+current_dir=$(pwd)
+cd $(realpath $current_dir)
+
 _bootstrap_or_activate "$0"
 
+cd $current_dir
```
Comment (ksperling-apple) [inline scripts/setup/bootstrap.sh:176]:
```suggestion
# Workaround for https://github.com/project-chip/connectedhomeip/issues/31851
if hash realpath 2>/dev/null; then
    realpwd="$(realpath "$PWD")"
    if [ "$realpwd" != "$PWD" ]; then
        echo "Warning: $PWD contains symlinks, using $realpwd instead"
        cd "$realpwd"
    fi
fi

_bootstrap_or_activate "$0"
```

If realpath is not available we can just carry on, so we don't have to install extra stuff in CI

Comment (ksperling-apple) [reply scripts/setup/bootstrap.sh:176]: (Ideally the comment should reference the pigweed issue, once one has been filed)

File: scripts/setup/bootstrap.sh (hunk 1 above)
Comment (bzbarsky-apple) [reply scripts/setup/bootstrap.sh:170]: The problem is bootstrap failing.  Yes, it's basically a pigweed bug, but until they fix it this at least makes things work....

File: scripts/setup/bootstrap.sh (hunk 2 above)
Comment (bzbarsky-apple) [reply scripts/setup/bootstrap.sh:176]: Ah, that is a good point.

Comment (bzbarsky-apple) [reply scripts/setup/bootstrap.sh]: Made this change.

**Comment by afonsomagmota** [comment]
Facing this error but can not understand workaround. Can someone support?

**Comment by bzbarsky-apple** [comment]
@afonsomagmota If your repository is in some path that has symlinks in it, resolve the symlinks to the actual location of the directory and `cd` to there before running bootstrap.
