### PR TITLE
[Android] Modify chiptool crash when skipCommissioningComplete flag enabled

### LINKED ISSUE #32686: [Android] - Devices with android 12 and below have problem with mDNS discovery of commissionable devices
### Reproduction steps

General idea is that in our application we want to scan all devices that have commissioning window open and present them to user to choose which one to configure. This works properly with android 13 and 14, but 12 and lower will find just one device.

1. Add two or more devices to apple home pod or google nest hub
2. Put both devices to pairing mode (open commissioning window)
3. Open Chip tool android app on devices with android 12 or lower
4. Go to PROVISION CHIP DEVICE WITH WIFI
5. Open Input device address fragment
6. Click Discover button
7. Keep clicking Discover button

Array of found devices is filled with same device, second device will be found only when first device close its commissioning mode

When I do exact same steps on android 13 and 14, discovery will add same device 2 or 3 times but it will find second device while both device are in commissioning mode

Issue is tested and mdns discovery **is not working properly on** 

- Huawei P smart 2019 (android 12)
- Samsung Tab S3 (android 9)
- Google Nexus (android 8.1)
- I know that those are old device, but we have to provide same experience to our users  

Devices that mdns discovery **is working properly** 

- Xiaomi Tab 5 (android 13)
- Pixel 7 (android 14)
- Samsung A52 (android 14)

Bellow are logs from chiptool android app from Huawei P smart. As attachment  I have added logs from xiaomi tab where everything works properly for comparation purpose.

Command used from ChipDeviceController is _**public void discoverCommissionableNodes()**_ 

```
linker                  com.google.chip.chiptool             W  Warning: "/data/app/com.google.chip.chiptool-tsReVNv1wGGk8EAAdmPEnQ==/base.apk!/lib/arm64-v8a/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
DMG                     com.google.chip.chiptool             D  AccessControl: initializing
CTL                     com.google.chip.chiptool             D  JNI_OnLoad() called
CTL                     com.google.chip.chiptool             D  Loading Java class references.
CTL                     com.google.chip.chiptool             D  Java class references loaded.
DL                      com.google.chip.chiptool             D  AndroidChipPlatform JNI_OnLoad() called
SPT                     com.google.chip.chiptool             E  JavaVM is already set
DL                      com.google.chip.chiptool             D  Loading Java class references.
DL                      com.google.chip.chiptool             D  Java class references loaded.
DL                      com.google.chip.chiptool             D  BleConnectCallbackJNI_OnLoad
DL                      com.google.chip.chiptool             D  Initializing tracing for android
CTL                     com.google.chip.chiptool             D  newDeviceController() called
CTL                     com.google.chip.chiptool             D  Setting attestation nonce to random value
CTL                     com.google.chip.chiptool             D  Setting CSR nonce to random value
CTL                     com.google.chip.chiptool             D  Setting attestation nonce to random value
CTL                     com.google.chip.chiptool             D  Setting CSR nonce to random value
CTL                     com.google.chip.chiptool             D  Setting attestation nonce from parameters
CTL                     com.google.chip.chiptool             D  Setting CSR nonce from parameters
TOO                     com.google.chip.chiptool             D  KVS: Getting key AndroidDeviceControllerKey
CTL                     com.google.chip.chiptool             D  No existing credentials provided: generating ephemeral local NOC chain with OperationalCredentialsIssuer
TOO                     com.google.chip.chiptool             D  KVS: Getting key AndroidCARootCert1
CTL                     com.google.chip.chiptool             D  Generating NOC
IN                      com.google.chip.chiptool             D  UDP::Init bind&listen port=0
IN                      com.google.chip.chiptool             D  UDP::Init bound to port=51573
IN                      com.google.chip.chiptool             D  UDP::Init bind&listen port=0
IN                      com.google.chip.chiptool             D  UDP::Init bound to port=58345
IN                      com.google.chip.chiptool             D  BLEBase::Init - setting/overriding transport
IN                      com.google.chip.chiptool             D  TransportMgr initialized
FP                      com.google.chip.chiptool             D  Initializing FabricTable from persistent storage
TOO                     com.google.chip.chiptool             D  KVS: Getting key g/lkgt
TS                      com.google.chip.chiptool             D  Last Known Good Time: 2023-10-14T01:16:48
TOO                     com.google.chip.chiptool             D  KVS: Getting key g/fidx
TOO                     com.google.chip.chiptool             D  KVS: Getting key f/1/n
TOO                     com.google.chip.chiptool             D  KVS: Getting key f/1/r
TOO                     com.google.chip.chiptool             D  KVS: Getting key f/1/m
FP                      com.google.chip.chiptool             D  Fabric index 0x1 was retrieved from storage. Compressed FabricId 0xAF3109A1C7EEDFAD, FabricId 
TOO                     com.google.chip.chiptool             D  KVS: Getting key g/fs/c
KeyValueStoreManager    com.google.chip.chiptool             D  Key 'g/fs/c' not found in shared preferences
TOO                     com.google.chip.chiptool             D  KVS: Getting key g/gcc
TOO                     com.google.chip.chiptool             D  KVS: Getting key g/gdc
TOO                     com.google.chip.chiptool             D  KVS: Setting key g/gcc
TOO                     com.google.chip.chiptool             D  KVS: Setting key g/gdc
CTL                     com.google.chip.chiptool             D  System State Initialized...
CTL                     com.google.chip.chiptool             D  Intermediate CA is not needed
TOO                     com.google.chip.chiptool             D  KVS: Getting key f/1/r
TOO                     com.google.chip.chiptool             D  KVS: Getting key f/1/r
TOO                     com.google.chip.chiptool             D  KVS: Getting key f/1/n
TOO                     com.google.chip.chiptool             D  KVS: Getting key f/1/r
FP                      com.google.chip.chiptool             D  Validating NOC chain
FP                      com.google.chip.chiptool             D  NOC chain validation successful
FP                      com.google.chip.chiptool             D  Updated fabric at index: 0x1, Node ID: 0x000000000001B669
TS                      com.google.chip.chiptool             D  Last Known Good Time: 2023-10-14T01:16:48
TS                      com.google.chip.chiptool             D  New proposed Last Known Good Time: 2021-06-10T00:00:00
TS                      com.google.chip.chiptool             D  Retaining current Last Known Good Time
TOO                     com.google.chip.chiptool             D  KVS: Getting key g/sri
KeyValueStoreManager    com.google.chip.chiptool             D  Key 'g/sri' not found in shared preferences
TOO                     com.google.chip.chiptool             D  KVS: Setting key g/fs/c
TOO                     com.google.chip.chiptool             D  KVS: Setting key f/1/m
FP                      com.google.chip.chiptool             D  Metadata for Fabric 0x1 persisted to storage.
TOO                     com.google.chip.chiptool             D  KVS: Setting key f/1/n
TOO                     com.google.chip.chiptool             D  KVS: Deleting key f/1/i
TS                      com.google.chip.chiptool             D  Committing Last Known Good Time to storage: 2023-10-14T01:16:48
TOO                     com.google.chip.chiptool             D  KVS: Setting key g/lkgt
TOO                     com.google.chip.chiptool             D  KVS: Deleting key g/fs/c
CTL                     com.google.chip.chiptool             D  Joined the fabric at index 1. Fabric ID is 0x0000000000000001 (Compressed Fabric ID: AF3109A1C7EEDFAD)
CTL                     com.google.chip.chiptool             D  *** Missing DeviceAttestationVerifier configuration at DeviceCommissioner init: using global default, 
CTL                     com.google.chip.chiptool             D  Setting up group data for Fabric Index 1 with Compressed Fabric ID:
SPT                     com.google.chip.chiptool             D  0xaf, 0x31, 0x09, 0xa1, 0xc7, 0xee, 0xdf, 0xad, 
TOO                     com.google.chip.chiptool             D  KVS: Getting key f/1/g
TOO                     com.google.chip.chiptool             D  KVS: Getting key f/1/k/0
TOO                     com.google.chip.chiptool             D  KVS: Setting key f/1/k/0
CTL                     com.google.chip.chiptool             D  IO thread starting
DL                      com.google.chip.chiptool             D  _OnPlatformEvent
CTL                     com.google.chip.chiptool             D  setAttestationTrustStoreDelegate() called
NsdManager...iceBrowser com.google.chip.chiptool             D  Starting service discovering for '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Started service '_matterc._udp'
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,2,1,27 interval=561
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,2,0 interval=722
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service 'E4B0A28D27C4AC9E'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service '493815107D9116E8'
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for 'E4B0A28D27C4AC9E' type '_matterc._udp'
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for '493815107D9116E8' type '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             W  Succeed to stop discovery service '_matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: E4B0A28D27C4AC9E, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: 493815107D9116E8, type: 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: E4B0A28D27C4AC9E, type: 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: 493815107D9116E8, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             W  Failed to resolve service '493815107D9116E8': 3
NsdService...ndResolver com.google.chip.chiptool             I  Resolved service 'E4B0A28D27C4AC9E' to /fdb1:1183:ba60:0:483e:ad25:d55d:2efb, type : ._matterc._udp
DIS                     com.google.chip.chiptool             D   ----- entry [0] : D 2701
DIS                     com.google.chip.chiptool             D   ----- entry [1] : T 0
DIS                     com.google.chip.chiptool             D   ----- entry [2] : CM 2
DIS                     com.google.chip.chiptool             D   ----- entry [3] : PH 36
DIS                     com.google.chip.chiptool             D   ----- entry [4] : PI NULL
DIS                     com.google.chip.chiptool             D   ----- entry [5] : RI 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D   ----- entry [6] : VP 4442+67
DIS                     com.google.chip.chiptool             D   ----- entry [7] : SAI 800
DIS                     com.google.chip.chiptool             D   ----- entry [8] : SII 800
DIS                     com.google.chip.chiptool             D  Discovered node:
DIS                     com.google.chip.chiptool             D  	Hostname: fdb1:1183:ba60:0
DIS                     com.google.chip.chiptool             D  	IP Address #1: fdb1:1183:ba60:0:483e:ad25:d55d:2efb
DIS                     com.google.chip.chiptool             D  	Port: 5540
DIS                     com.google.chip.chiptool             D  	Mrp Interval idle: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Interval active: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Active Threshold: not present
DIS                     com.google.chip.chiptool             D  	TCP Supported: 0
DIS                     com.google.chip.chiptool             D  	ICD: not present
DIS                     com.google.chip.chiptool             D  	Rotating ID: 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D  	Vendor ID: 4442
DIS                     com.google.chip.chiptool             D  	Product ID: 67
DIS                     com.google.chip.chiptool             D  	Long Discriminator: 2701
DIS                     com.google.chip.chiptool             D  	Pairing Hint: 36
DIS                     com.google.chip.chiptool             D  	Instance Name: E4B0A28D27C4AC9E
DIS                     com.google.chip.chiptool             D  	Commissioning Mode: 2
CTL                     com.google.chip.chiptool             E  Unknown filter type; all matches will fail
ViewRootImpl            com.google.chip.chiptool             I  jank_removeInvalidNode jank list is null
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=93
HwWechatOptimizeImpl    com.google.chip.chiptool             D  mIsEffect:false
e.chip.chiptoo          com.google.chip.chiptool             W  Accessing hidden field Landroid/widget/AbsListView;->mIsChildViewEnabled:Z (light greylist, reflection)
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
mali_winsys             com.google.chip.chiptool             D  EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, 
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,2,1,7 interval=239
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,2,0 interval=344
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,1,3,0 interval=1553
InputMethodManager      com.google.chip.chiptool             V  Reporting focus gain, without startInput
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,1,4,0 interval=1812
libEGL                  com.google.chip.chiptool             W  EGLNativeWindowType 0x7390171010 disconnect failed
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=72
AudioManager            com.google.chip.chiptool             V  playSoundEffect   effectType: 0
AudioManager            com.google.chip.chiptool             V  querySoundEffectsEnabled...
NsdManager...iceBrowser com.google.chip.chiptool             D  Starting service discovering for '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Started service '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service 'E4B0A28D27C4AC9E'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service '493815107D9116E8'
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,2,0 interval=335
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for 'E4B0A28D27C4AC9E' type '_matterc._udp'
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for '493815107D9116E8' type '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             W  Succeed to stop discovery service '_matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: E4B0A28D27C4AC9E, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: 493815107D9116E8, type: 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: E4B0A28D27C4AC9E, type: 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: 493815107D9116E8, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             W  Failed to resolve service '493815107D9116E8': 3
NsdService...ndResolver com.google.chip.chiptool             I  Resolved service 'E4B0A28D27C4AC9E' to /fdb1:1183:ba60:0:483e:ad25:d55d:2efb, type : ._matterc._udp
DIS                     com.google.chip.chiptool             D   ----- entry [0] : D 2701
DIS                     com.google.chip.chiptool             D   ----- entry [1] : T 0
DIS                     com.google.chip.chiptool             D   ----- entry [2] : CM 2
DIS                     com.google.chip.chiptool             D   ----- entry [3] : PH 36
DIS                     com.google.chip.chiptool             D   ----- entry [4] : PI NULL
DIS                     com.google.chip.chiptool             D   ----- entry [5] : RI 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D   ----- entry [6] : VP 4442+67
DIS                     com.google.chip.chiptool             D   ----- entry [7] : SAI 800
DIS                     com.google.chip.chiptool             D   ----- entry [8] : SII 800
DIS                     com.google.chip.chiptool             D  Discovered node:
DIS                     com.google.chip.chiptool             D  	Hostname: fdb1:1183:ba60:0
DIS                     com.google.chip.chiptool             D  	IP Address #1: fdb1:1183:ba60:0:483e:ad25:d55d:2efb
DIS                     com.google.chip.chiptool             D  	Port: 5540
DIS                     com.google.chip.chiptool             D  	Mrp Interval idle: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Interval active: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Active Threshold: not present
DIS                     com.google.chip.chiptool             D  	TCP Supported: 0
DIS                     com.google.chip.chiptool             D  	ICD: not present
DIS                     com.google.chip.chiptool             D  	Rotating ID: 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D  	Vendor ID: 4442
DIS                     com.google.chip.chiptool             D  	Product ID: 67
DIS                     com.google.chip.chiptool             D  	Long Discriminator: 2701
DIS                     com.google.chip.chiptool             D  	Pairing Hint: 36
DIS                     com.google.chip.chiptool             D  	Instance Name: E4B0A28D27C4AC9E
DIS                     com.google.chip.chiptool             D  	Commissioning Mode: 2
CTL                     com.google.chip.chiptool             E  Unknown filter type; all matches will fail
ViewRootImpl            com.google.chip.chiptool             I  jank_removeInvalidNode all the node in jank list is out of time
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=114
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
mali_winsys             com.google.chip.chiptool             D  EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, 
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,2,1,7 interval=252
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,2,0 interval=373
e.chip.chiptoo          com.google.chip.chiptool             I  Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, 
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,1,3,0 interval=1837
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,2,2,3 interval=1840
InputMethodManager      com.google.chip.chiptool             V  Reporting focus gain, without startInput
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,1,4,0 interval=2088
libEGL                  com.google.chip.chiptool             W  EGLNativeWindowType 0x7390194010 disconnect failed
TransportR...ortBackend com.google.chip.chiptool             D  Making request to: https://firebaselogging.googleapis.com/v0cc/log/batch?format=json_proto3
NetworkSecurityConfig   com.google.chip.chiptool             D  No Network Security Config specified, using platform default
TransportR...ortBackend com.google.chip.chiptool             I  Status Code: 200
TransportR...ortBackend com.google.chip.chiptool             I  Content-Type: application/json; charset=UTF-8
TransportR...ortBackend com.google.chip.chiptool             I  Content-Encoding: gzip
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=127
AudioManager            com.google.chip.chiptool             V  playSoundEffect   effectType: 0
AudioManager            com.google.chip.chiptool             V  querySoundEffectsEnabled...
NsdManager...iceBrowser com.google.chip.chiptool             D  Starting service discovering for '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Started service '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service 'E4B0A28D27C4AC9E'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service '493815107D9116E8'
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for 'E4B0A28D27C4AC9E' type '_matterc._udp'
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for '493815107D9116E8' type '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             W  Succeed to stop discovery service '_matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: E4B0A28D27C4AC9E, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: 493815107D9116E8, type: 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: E4B0A28D27C4AC9E, type: 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: 493815107D9116E8, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             W  Failed to resolve service '493815107D9116E8': 3
NsdService...ndResolver com.google.chip.chiptool             I  Resolved service 'E4B0A28D27C4AC9E' to /fdb1:1183:ba60:0:483e:ad25:d55d:2efb, type : ._matterc._udp
DIS                     com.google.chip.chiptool             D   ----- entry [0] : D 2701
DIS                     com.google.chip.chiptool             D   ----- entry [1] : T 0
DIS                     com.google.chip.chiptool             D   ----- entry [2] : CM 2
DIS                     com.google.chip.chiptool             D   ----- entry [3] : PH 36
DIS                     com.google.chip.chiptool             D   ----- entry [4] : PI NULL
DIS                     com.google.chip.chiptool             D   ----- entry [5] : RI 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D   ----- entry [6] : VP 4442+67
DIS                     com.google.chip.chiptool             D   ----- entry [7] : SAI 800
DIS                     com.google.chip.chiptool             D   ----- entry [8] : SII 800
DIS                     com.google.chip.chiptool             D  Discovered node:
DIS                     com.google.chip.chiptool             D  	Hostname: fdb1:1183:ba60:0
DIS                     com.google.chip.chiptool             D  	IP Address #1: fdb1:1183:ba60:0:483e:ad25:d55d:2efb
DIS                     com.google.chip.chiptool             D  	Port: 5540
DIS                     com.google.chip.chiptool             D  	Mrp Interval idle: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Interval active: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Active Threshold: not present
DIS                     com.google.chip.chiptool             D  	TCP Supported: 0
DIS                     com.google.chip.chiptool             D  	ICD: not present
DIS                     com.google.chip.chiptool             D  	Rotating ID: 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D  	Vendor ID: 4442
DIS                     com.google.chip.chiptool             D  	Product ID: 67
DIS                     com.google.chip.chiptool             D  	Long Discriminator: 2701
DIS                     com.google.chip.chiptool             D  	Pairing Hint: 36
DIS                     com.google.chip.chiptool             D  	Instance Name: E4B0A28D27C4AC9E
DIS                     com.google.chip.chiptool             D  	Commissioning Mode: 2
CTL                     com.google.chip.chiptool             E  Unknown filter type; all matches will fail
ViewRootImpl            com.google.chip.chiptool             I  jank_removeInvalidNode all the node in jank list is out of time
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=86
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
mali_winsys             com.google.chip.chiptool             D  EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, 
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,2,1,10 interval=273
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,2,0 interval=349
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,2,2,6 interval=605
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,3,0 interval=608
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,1,4,0 interval=1758
InputMethodManager      com.google.chip.chiptool             V  Reporting focus gain, without startInput
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,1,5,0 interval=2016
libEGL                  com.google.chip.chiptool             W  EGLNativeWindowType 0x73901d0010 disconnect failed
AudioManager            com.google.chip.chiptool             V  playSoundEffect   effectType: 0
AudioManager            com.google.chip.chiptool             V  querySoundEffectsEnabled...
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=103
NsdManager...iceBrowser com.google.chip.chiptool             D  Starting service discovering for '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Started service '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service 'E4B0A28D27C4AC9E'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service '493815107D9116E8'
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,2,0 interval=369
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for 'E4B0A28D27C4AC9E' type '_matterc._udp'
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for '493815107D9116E8' type '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             W  Succeed to stop discovery service '_matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: E4B0A28D27C4AC9E, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: 493815107D9116E8, type: 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: E4B0A28D27C4AC9E, type: 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: 493815107D9116E8, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             W  Failed to resolve service '493815107D9116E8': 3
NsdService...ndResolver com.google.chip.chiptool             I  Resolved service 'E4B0A28D27C4AC9E' to /fdb1:1183:ba60:0:483e:ad25:d55d:2efb, type : ._matterc._udp
DIS                     com.google.chip.chiptool             D   ----- entry [0] : D 2701
DIS                     com.google.chip.chiptool             D   ----- entry [1] : T 0
DIS                     com.google.chip.chiptool             D   ----- entry [2] : CM 2
DIS                     com.google.chip.chiptool             D   ----- entry [3] : PH 36
DIS                     com.google.chip.chiptool             D   ----- entry [4] : PI NULL
DIS                     com.google.chip.chiptool             D   ----- entry [5] : RI 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D   ----- entry [6] : VP 4442+67
DIS                     com.google.chip.chiptool             D   ----- entry [7] : SAI 800
DIS                     com.google.chip.chiptool             D   ----- entry [8] : SII 800
DIS                     com.google.chip.chiptool             D  Discovered node:
DIS                     com.google.chip.chiptool             D  	Hostname: fdb1:1183:ba60:0
DIS                     com.google.chip.chiptool             D  	IP Address #1: fdb1:1183:ba60:0:483e:ad25:d55d:2efb
DIS                     com.google.chip.chiptool             D  	Port: 5540
DIS                     com.google.chip.chiptool             D  	Mrp Interval idle: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Interval active: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Active Threshold: not present
DIS                     com.google.chip.chiptool             D  	TCP Supported: 0
DIS                     com.google.chip.chiptool             D  	ICD: not present
DIS                     com.google.chip.chiptool             D  	Rotating ID: 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D  	Vendor ID: 4442
DIS                     com.google.chip.chiptool             D  	Product ID: 67
DIS                     com.google.chip.chiptool             D  	Long Discriminator: 2701
DIS                     com.google.chip.chiptool             D  	Pairing Hint: 36
DIS                     com.google.chip.chiptool             D  	Instance Name: E4B0A28D27C4AC9E
DIS                     com.google.chip.chiptool             D  	Commissioning Mode: 2
CTL                     com.google.chip.chiptool             E  Unknown filter type; all matches will fail
ViewRootImpl            com.google.chip.chiptool             I  jank_removeInvalidNode all the node in jank list is out of time
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=111
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
mali_winsys             com.google.chip.chiptool             D  EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, 
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,2,1,6 interval=323
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,2,0 interval=362
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=110
InputMethodManager      com.google.chip.chiptool             V  Reporting focus gain, without startInput
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,2,0 interval=368
libEGL                  com.google.chip.chiptool             W  EGLNativeWindowType 0x7390296010 disconnect failed
AudioManager            com.google.chip.chiptool             V  playSoundEffect   effectType: 0
AudioManager            com.google.chip.chiptool             V  querySoundEffectsEnabled...
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,1,3,0 interval=1716
NsdManager...iceBrowser com.google.chip.chiptool             D  Starting service discovering for '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Started service '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service 'E4B0A28D27C4AC9E'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service '493815107D9116E8'
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,1,4,0 interval=1966
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for 'E4B0A28D27C4AC9E' type '_matterc._udp'
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for '493815107D9116E8' type '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             W  Succeed to stop discovery service '_matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: E4B0A28D27C4AC9E, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: 493815107D9116E8, type: 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: E4B0A28D27C4AC9E, type: 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: 493815107D9116E8, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             W  Failed to resolve service '493815107D9116E8': 3
NsdService...ndResolver com.google.chip.chiptool             I  Resolved service 'E4B0A28D27C4AC9E' to /fdb1:1183:ba60:0:483e:ad25:d55d:2efb, type : ._matterc._udp
DIS                     com.google.chip.chiptool             D   ----- entry [0] : D 2701
DIS                     com.google.chip.chiptool             D   ----- entry [1] : T 0
DIS                     com.google.chip.chiptool             D   ----- entry [2] : CM 2
DIS                     com.google.chip.chiptool             D   ----- entry [3] : PH 36
DIS                     com.google.chip.chiptool             D   ----- entry [4] : PI NULL
DIS                     com.google.chip.chiptool             D   ----- entry [5] : RI 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D   ----- entry [6] : VP 4442+67
DIS                     com.google.chip.chiptool             D   ----- entry [7] : SAI 800
DIS                     com.google.chip.chiptool             D   ----- entry [8] : SII 800
DIS                     com.google.chip.chiptool             D  Discovered node:
DIS                     com.google.chip.chiptool             D  	Hostname: fdb1:1183:ba60:0
DIS                     com.google.chip.chiptool             D  	IP Address #1: fdb1:1183:ba60:0:483e:ad25:d55d:2efb
DIS                     com.google.chip.chiptool             D  	Port: 5540
DIS                     com.google.chip.chiptool             D  	Mrp Interval idle: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Interval active: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Active Threshold: not present
DIS                     com.google.chip.chiptool             D  	TCP Supported: 0
DIS                     com.google.chip.chiptool             D  	ICD: not present
DIS                     com.google.chip.chiptool             D  	Rotating ID: 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D  	Vendor ID: 4442
DIS                     com.google.chip.chiptool             D  	Product ID: 67
DIS                     com.google.chip.chiptool             D  	Long Discriminator: 2701
DIS                     com.google.chip.chiptool             D  	Pairing Hint: 36
DIS                     com.google.chip.chiptool             D  	Instance Name: E4B0A28D27C4AC9E
DIS                     com.google.chip.chiptool             D  	Commissioning Mode: 2
CTL                     com.google.chip.chiptool             E  Unknown filter type; all matches will fail
ViewRootImpl            com.google.chip.chiptool             I  jank_removeInvalidNode all the node in jank list is out of time
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=140
mali_winsys             com.google.chip.chiptool             D  EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, 
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,2,1,9 interval=254
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,2,0 interval=391
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,1,3,0 interval=1973
InputMethodManager      com.google.chip.chiptool             V  Reporting focus gain, without startInput
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,1,4,0 interval=2223
libEGL                  com.google.chip.chiptool             W  EGLNativeWindowType 0x73901d1010 disconnect failed
AudioManager            com.google.chip.chiptool             V  playSoundEffect   effectType: 0
AudioManager            com.google.chip.chiptool             V  querySoundEffectsEnabled...
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=41
NsdManager...iceBrowser com.google.chip.chiptool             D  Starting service discovering for '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Started service '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service 'E4B0A28D27C4AC9E'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service '493815107D9116E8'
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,2,0 interval=299
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for 'E4B0A28D27C4AC9E' type '_matterc._udp'
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for '493815107D9116E8' type '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             W  Succeed to stop discovery service '_matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: E4B0A28D27C4AC9E, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: 493815107D9116E8, type: 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: E4B0A28D27C4AC9E, type: 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: 493815107D9116E8, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             W  Failed to resolve service '493815107D9116E8': 3
NsdService...ndResolver com.google.chip.chiptool             I  Resolved service 'E4B0A28D27C4AC9E' to /fdb1:1183:ba60:0:483e:ad25:d55d:2efb, type : ._matterc._udp
DIS                     com.google.chip.chiptool             D   ----- entry [0] : D 2701
DIS                     com.google.chip.chiptool             D   ----- entry [1] : T 0
DIS                     com.google.chip.chiptool             D   ----- entry [2] : CM 2
DIS                     com.google.chip.chiptool             D   ----- entry [3] : PH 36
DIS                     com.google.chip.chiptool             D   ----- entry [4] : PI NULL
DIS                     com.google.chip.chiptool             D   ----- entry [5] : RI 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D   ----- entry [6] : VP 4442+67
DIS                     com.google.chip.chiptool             D   ----- entry [7] : SAI 800
DIS                     com.google.chip.chiptool             D   ----- entry [8] : SII 800
DIS                     com.google.chip.chiptool             D  Discovered node:
DIS                     com.google.chip.chiptool             D  	Hostname: fdb1:1183:ba60:0
DIS                     com.google.chip.chiptool             D  	IP Address #1: fdb1:1183:ba60:0:483e:ad25:d55d:2efb
DIS                     com.google.chip.chiptool             D  	Port: 5540
DIS                     com.google.chip.chiptool             D  	Mrp Interval idle: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Interval active: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Active Threshold: not present
DIS                     com.google.chip.chiptool             D  	TCP Supported: 0
DIS                     com.google.chip.chiptool             D  	ICD: not present
DIS                     com.google.chip.chiptool             D  	Rotating ID: 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D  	Vendor ID: 4442
DIS                     com.google.chip.chiptool             D  	Product ID: 67
DIS                     com.google.chip.chiptool             D  	Long Discriminator: 2701
DIS                     com.google.chip.chiptool             D  	Pairing Hint: 36
DIS                     com.google.chip.chiptool             D  	Instance Name: E4B0A28D27C4AC9E
DIS                     com.google.chip.chiptool             D  	Commissioning Mode: 2
CTL                     com.google.chip.chiptool             E  Unknown filter type; all matches will fail
ViewRootImpl            com.google.chip.chiptool             I  jank_removeInvalidNode all the node in jank list is out of time
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=88
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
mali_winsys             com.google.chip.chiptool             D  EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, 
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,2,1,11 interval=292
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,2,0 interval=365
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,1,3,0 interval=1834
InputMethodManager      com.google.chip.chiptool             V  Reporting focus gain, without startInput
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,1,4,0 interval=2099
libEGL                  com.google.chip.chiptool             W  EGLNativeWindowType 0x73902e5010 disconnect failed
AudioManager            com.google.chip.chiptool             V  playSoundEffect   effectType: 0
AudioManager            com.google.chip.chiptool             V  querySoundEffectsEnabled...
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=130
NsdManager...iceBrowser com.google.chip.chiptool             D  Starting service discovering for '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Started service '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service 'E4B0A28D27C4AC9E'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service '493815107D9116E8'
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for 'E4B0A28D27C4AC9E' type '_matterc._udp'
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for '493815107D9116E8' type '_matterc._udp'
<no-tag>                com.google.chip.chiptool             E  [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
NsdManager...iceBrowser com.google.chip.chiptool             W  Succeed to stop discovery service '_matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: E4B0A28D27C4AC9E, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: 493815107D9116E8, type: 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: E4B0A28D27C4AC9E, type: 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: 493815107D9116E8, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             W  Failed to resolve service '493815107D9116E8': 3
NsdService...ndResolver com.google.chip.chiptool             I  Resolved service 'E4B0A28D27C4AC9E' to /fdb1:1183:ba60:0:483e:ad25:d55d:2efb, type : ._matterc._udp
DIS                     com.google.chip.chiptool             D   ----- entry [0] : D 2701
DIS                     com.google.chip.chiptool             D   ----- entry [1] : T 0
DIS                     com.google.chip.chiptool             D   ----- entry [2] : CM 2
DIS                     com.google.chip.chiptool             D   ----- entry [3] : PH 36
DIS                     com.google.chip.chiptool             D   ----- entry [4] : PI NULL
DIS                     com.google.chip.chiptool             D   ----- entry [5] : RI 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D   ----- entry [6] : VP 4442+67
DIS                     com.google.chip.chiptool             D   ----- entry [7] : SAI 800
DIS                     com.google.chip.chiptool             D   ----- entry [8] : SII 800
DIS                     com.google.chip.chiptool             D  Discovered node:
DIS                     com.google.chip.chiptool             D  	Hostname: fdb1:1183:ba60:0
DIS                     com.google.chip.chiptool             D  	IP Address #1: fdb1:1183:ba60:0:483e:ad25:d55d:2efb
DIS                     com.google.chip.chiptool             D  	Port: 5540
DIS                     com.google.chip.chiptool             D  	Mrp Interval idle: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Interval active: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Active Threshold: not present
DIS                     com.google.chip.chiptool             D  	TCP Supported: 0
DIS                     com.google.chip.chiptool             D  	ICD: not present
DIS                     com.google.chip.chiptool             D  	Rotating ID: 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D  	Vendor ID: 4442
DIS                     com.google.chip.chiptool             D  	Product ID: 67
DIS                     com.google.chip.chiptool             D  	Long Discriminator: 2701
DIS                     com.google.chip.chiptool             D  	Pairing Hint: 36
DIS                     com.google.chip.chiptool             D  	Instance Name: E4B0A28D27C4AC9E
DIS                     com.google.chip.chiptool             D  	Commissioning Mode: 2
CTL                     com.google.chip.chiptool             E  Unknown filter type; all matches will fail
ViewRootImpl            com.google.chip.chiptool             I  jank_removeInvalidNode all the node in jank list is out of time
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=133
mali_winsys             com.google.chip.chiptool             D  EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, 
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,2,1,14 interval=288
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,2,0 interval=384
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,1,3,0 interval=1737
InputMethodManager      com.google.chip.chiptool             V  Reporting focus gain, without startInput
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,1,1,4,0 interval=1999
libEGL                  com.google.chip.chiptool             W  EGLNativeWindowType 0x739030a010 disconnect failed
AudioManager            com.google.chip.chiptool             V  playSoundEffect   effectType: 0
AudioManager            com.google.chip.chiptool             V  querySoundEffectsEnabled...
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=103
NsdManager...iceBrowser com.google.chip.chiptool             D  Starting service discovering for '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Started service '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service 'E4B0A28D27C4AC9E'
NsdManager...iceBrowser com.google.chip.chiptool             I  Found service '493815107D9116E8'
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,2,0 interval=368
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for 'E4B0A28D27C4AC9E' type '_matterc._udp'
NsdManager...ceResolver com.google.chip.chiptool             D  resolve: Starting service resolution for '493815107D9116E8' type '_matterc._udp'
NsdManager...iceBrowser com.google.chip.chiptool             W  Succeed to stop discovery service '_matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  Service discovery started. regType: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: E4B0A28D27C4AC9E, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: 493815107D9116E8, type: 
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found service not a target for resolution, ignoring name: E4B0A28D27C4AC9E, type: 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             D  onServiceFound: found target service name: 493815107D9116E8, type: _matterc._udp., host: null, port: 0, 
NsdService...ndResolver com.google.chip.chiptool             I  Discovery stopped: _matterc._udp
NsdService...ndResolver com.google.chip.chiptool             W  Failed to resolve service '493815107D9116E8': 3
NsdService...ndResolver com.google.chip.chiptool             I  Resolved service 'E4B0A28D27C4AC9E' to /fdb1:1183:ba60:0:483e:ad25:d55d:2efb, type : ._matterc._udp
DIS                     com.google.chip.chiptool             D   ----- entry [0] : D 3862
DIS                     com.google.chip.chiptool             D   ----- entry [1] : T 0
DIS                     com.google.chip.chiptool             D   ----- entry [2] : CM 0
DIS                     com.google.chip.chiptool             D   ----- entry [3] : PH 36
DIS                     com.google.chip.chiptool             D   ----- entry [4] : PI NULL
DIS                     com.google.chip.chiptool             D   ----- entry [5] : RI 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D   ----- entry [6] : VP 4442+67
DIS                     com.google.chip.chiptool             D   ----- entry [7] : SAI 800
DIS                     com.google.chip.chiptool             D   ----- entry [8] : SII 800
DIS                     com.google.chip.chiptool             D  Discovered node:
DIS                     com.google.chip.chiptool             D  	Hostname: fdb1:1183:ba60:0
DIS                     com.google.chip.chiptool             D  	IP Address #1: fdb1:1183:ba60:0:483e:ad25:d55d:2efb
DIS                     com.google.chip.chiptool             D  	Port: 5540
DIS                     com.google.chip.chiptool             D  	Mrp Interval idle: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Interval active: 800 ms
DIS                     com.google.chip.chiptool             D  	Mrp Active Threshold: not present
DIS                     com.google.chip.chiptool             D  	TCP Supported: 0
DIS                     com.google.chip.chiptool             D  	ICD: not present
DIS                     com.google.chip.chiptool             D  	Rotating ID: 8800E16EB875959E578B4162C90264EBBE07
DIS                     com.google.chip.chiptool             D  	Vendor ID: 4442
DIS                     com.google.chip.chiptool             D  	Product ID: 67
DIS                     com.google.chip.chiptool             D  	Long Discriminator: 3862
DIS                     com.google.chip.chiptool             D  	Pairing Hint: 36
DIS                     com.google.chip.chiptool             D  	Instance Name: E4B0A28D27C4AC9E
DIS                     com.google.chip.chiptool             D  	Commissioning Mode: 0
CTL                     com.google.chip.chiptool             D  Discovered device does not have an open commissioning window.
ViewRootImpl            com.google.chip.chiptool             I  jank_removeInvalidNode all the node in jank list is out of time
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,1,0 interval=149
mali_winsys             com.google.chip.chiptool             D  EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, 
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,2,1,11 interval=288
OpenGLRenderer          com.google.chip.chiptool             D    HWUI Binary is  enabled
HwAppInnerBoostImpl     com.google.chip.chiptool             D  asyncReportData com.google.chip.chiptool,2,1,2,0 interval=400
ZrHung.AppEyeUiProbe    com.google.chip.chiptool             D  stop checker.
ViewRootIm...lActivity] com.google.chip.chiptool             D  surface should not be released
ViewRootIm...w:88eaddd] com.google.chip.chiptool             D  surface should not be released
libEGL                  com.google.chip.chiptool             W  EGLNativeWindowType 0x73a842b010 disconnect failed
ZrHung.AppEyeUiProbe    com.google.chip.chiptool             D  Current Activity:false
ZrHung.AppEyeUiProbe    com.google.chip.chiptool             D  not watching, wait.
<no-tag>                com.google.chip.chiptool             E  [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
```
[huawei p smart.txt](https://github.com/project-chip/connectedhomeip/files/14721269/huawei.p.smart.txt)
[xiaomi.txt](https://github.com/project-chip/connectedhomeip/files/14721270/xiaomi.txt)

### Platform

android

### Platform Version(s)

v1.2.0.1 

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by joonhaengHeo**
Fix #32686 

When in CleanUp Stage, if CommissioneeDevice exists, it must be freed. However, this process must be final. This issue causes a crash because CommissioningStageComplete is called after Release and mDeviceBeingCommissioned is null.

Crash Point : 
https://github.com/project-chip/connectedhomeip/blob/824ba6dbd9a7e783353f4c714e7ca0ba03615c64/src/controller/CHIPDeviceController.cpp#L1903

### CODE REVIEW

File: src/controller/CHIPDeviceController.cpp [hunk 1]
```diff
@@ -1770,13 +1770,13 @@ void DeviceCommissioner::CleanupCommissioning(DeviceProxy * proxy, NodeId nodeId
...
     if (completionStatus.err == CHIP_NO_ERROR)
     {
+        CommissioningStageComplete(CHIP_NO_ERROR);
         CommissioneeDeviceProxy * commissionee = FindCommissioneeDevice(nodeId);
         if (commissionee != nullptr)
         {
             ReleaseCommissioneeDevice(commissionee);
         }
         // Send the callbacks, we're done.
-        CommissioningStageComplete(CHIP_NO_ERROR);
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1779]: This does not looks right.  `CommissioningStageComplete` should mean we actually completed the step...

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/controller/CHIPDeviceController.cpp (hunk 1 above)
Comment (joonhaengHeo) [reply src/controller/CHIPDeviceController.cpp:1779]: @bzbarsky-apple 
This process is a function that is called only in the CleanUp Stage. Currently, the root cause of this issue is that mDeviceBeingCommissioned, which is used when CommissioningStageComplete is called, is already free. This free is done by ReleaseCommissioneeDevice.

Crash Point : 
https://github.com/project-chip/connectedhomeip/blob/824ba6dbd9a7e783353f4c714e7ca0ba03615c64/src/controller/CHIPDeviceController.cpp#L1903

Free Code :
https://github.com/project-chip/connectedhomeip/blob/824ba6dbd9a7e783353f4c714e7ca0ba03615c64/src/controller/CHIPDeviceController.cpp#L618


I think ReleaseCommissioneeDevice should be done at the end of the whole process. For this reason, the two codes have been changed, and they are implemented exactly the same in the code below, so this change was made. Please check again.

https://github.com/project-chip/connectedhomeip/blob/824ba6dbd9a7e783353f4c714e7ca0ba03615c64/src/controller/CHIPDeviceController.cpp#L1851

**Review by yunhanw-google — APPROVED** [review]

File: src/controller/CHIPDeviceController.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/controller/CHIPDeviceController.cpp:1779]: Hmm.  I agree that if `CommissioningStageComplete` is going to assert `mDeviceBeingCommissioned` then it can't come after `ReleaseCommissioneeDevice`.  

So why is this not crashing on every single commissioning?

Comment (joonhaengHeo) [reply src/controller/CHIPDeviceController.cpp:1779]: @bzbarsky-apple 
If you do not set other optional parameters in the app, two DeviceProxy are created during the commissioning process. One is CommissioneeDeviceProxy and the other is OperationalDeviceProxy.
In the general case, mDeviceBeingCommissioned is set to OperationalDeviceProxy, and it is CommissioneeDeviceProxy that needs to be freed, so it is not set to null in the code below.
https://github.com/project-chip/connectedhomeip/blob/6a7961db7960dec75039047210c87154fa514f22/src/controller/CHIPDeviceController.cpp#L616

However, when an issue occurs, SkipCommissioningComplete is set to true. In this case, because CASE is being skipped, OperationalDeviceProxy is not created and ends by switching to the CleanUp step. For this reason, because it is the same value in the above code, it is set to null, and a crash occurs.

Comment (bzbarsky-apple) [reply src/controller/CHIPDeviceController.cpp:1779]: So hold on a sec.  Are we then leaking the CommissioneeDeviceProxy when commissioning _does_ go through all the way to CommissioningComplete, because we've reset mDeviceBeingCommissioned to be the OperationalDeviceProxy and hence all the stuff we _think_ is cleaning up the CommissioneeDeviceProxy is doing nothing of the sort?

File: src/controller/CHIPDeviceController.cpp [hunk 2]
```diff
@@ -1771,12 +1771,12 @@ void DeviceCommissioner::CleanupCommissioning(DeviceProxy * proxy, NodeId nodeId
     if (completionStatus.err == CHIP_NO_ERROR)
     {
         CommissioneeDeviceProxy * commissionee = FindCommissioneeDevice(nodeId);
+        CommissioningStageComplete(CHIP_NO_ERROR);
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1774]: OK, I see.  So in the "normal" path `commissionee` and `mDeviceBeingCommissioned` are not the same object.

So then this makes some sense, except for the following: when we call `CommissioningStageComplete` that will send client notifications, and those can cause `commissionee` to be destroyed, no?  And then we will be doing use-after-free when we go to release it.

Comment (joonhaengHeo) [reply src/controller/CHIPDeviceController.cpp:1774]: @bzbarsky-apple 
No, there is no such possibility. In the case of the CleanUp stage in CommissioningStageComplete, a code has already been added to skip the release.

https://github.com/project-chip/connectedhomeip/blob/3cb83827fc6d46d66fc34ca0a39b54dff2170c00/src/controller/CHIPDeviceController.cpp#L1932

Comment (bzbarsky-apple) [reply src/controller/CHIPDeviceController.cpp:1774]: Hmm, ok.  In theory, `CommissioningStageComplete` can tear down the controller, but that has other problems too.  Alright, thanks!

Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1774]:
```suggestion
        // CommissioningStageComplete uses mDeviceBeingCommissioned, which can
        // be commissionee if we are cleaning up before we've gone operational.  Normally
        // that would not happen in this non-error case, _except_ if we were told to skip sending
        // CommissioningComplete: in that case we do not have an operational DeviceProxy, so
        // we're using our CommissioneeDeviceProxy to do a successful cleanup.
        //
        // This means we have to call CommissioningStageComplete() before we destroy commissionee.
        //
        // This should be safe, because CommissioningStageComplete() does not call CleanupCommissioning
        // when called in the cleanup stage (which is where we are), and StopPairing does not directly release
        // mDeviceBeingCommissioned.
        CommissioningStageComplete(CHIP_NO_ERROR);
```

Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1774]: That said, now that I wrote that comment... In the case when we _do_ go operational, if the notification from `CommissioningStageComplete` leads to `StopPairing` being called we will in fact have use-after-free.... 

Do things work correctly if we call `FindCommissioneeDevice()` _after_ `CommissioningStageComplete`?  Seems like if it's returning false the thing has already been destroyed, and we don't have to destroy it again.  Is that true?

Comment (joonhaengHeo) [reply src/controller/CHIPDeviceController.cpp:1785]: @bzbarsky-apple 
In what process can use-after-free occur? In the CleanUp process, nothing becomes free when CommissioningStageComplete is called.

Comment (joonhaengHeo) [reply src/controller/CHIPDeviceController.cpp:1785]: In the case of "mDeviceBeingCommissioned != commissionee", I think it only frees the DeviceProxy already in use in PASE and is unrelated to the OperationalDeviceProxy that is running. I think this case is unrelated to the current issue.

Comment (bzbarsky-apple) [reply src/controller/CHIPDeviceController.cpp:1785]: My point is that in that situation, `commissionee` in this code gets destroyed.  Then this code tries to use it.

**Comment by joonhaengHeo** [comment]
I know this needs to be addressed, but I'm not sure how to do it. Is there a suitable solution?

File: src/controller/CHIPDeviceController.cpp (hunk 2 above)
Comment (joonhaengHeo) [reply src/controller/CHIPDeviceController.cpp:1785]: I don't know if I understand your opinion well, but I understand from your comment that you are concerned that when stopPairing is called, ReleaseCommissioneeDevice is called and becomes free due to the part I modified.

However, in this case, due to the `if` below, the part I modified is not executed, and it becomes `else if (completionStatus.err == CHIP_ERROR_CANCELLED)`, and I think DisarmFailSafeRequest is called. Is there something I thought wrong?

Comment (bzbarsky-apple) [reply src/controller/CHIPDeviceController.cpp:1785]: No, my concern is this code:
```
        CommissioneeDeviceProxy * commissionee = FindCommissioneeDevice(nodeId);
        CommissioningStageComplete(CHIP_NO_ERROR);  // this calls into stopPairing, so now `commissionee` is a dangling pointer

        if (commissionee != nullptr)
        {
            ReleaseCommissioneeDevice(commissionee);  // This is a use-after-free.
```

Comment (joonhaengHeo) [reply src/controller/CHIPDeviceController.cpp:1844]: I understand. Thanks. I changed code.

Comment (joonhaengHeo) [reply src/controller/CHIPDeviceController.cpp:1844]: @bzbarsky-apple 
What do you think about this code? Of course, it doesn't matter since it's code after Commissioning, but wouldn't it be appropriate to modify it together?

https://github.com/project-chip/connectedhomeip/blob/294dc18fe85182a15ab4d8be2d52f25d756da522/src/controller/CHIPDeviceController.cpp#L1919

Comment (bzbarsky-apple) [reply src/controller/CHIPDeviceController.cpp:1844]: @joonhaengHeo Yes, that code would be safer with the order changed too, good catch!

**Review by bzbarsky-apple — APPROVED** [review]

File: src/controller/CHIPDeviceController.cpp (hunk 2 above)
Comment (joonhaengHeo) [reply src/controller/CHIPDeviceController.cpp:1844]: @bzbarsky-apple 
Modified. Thanks.

**Review by bzbarsky-apple — APPROVED** [review]
