### PR TITLE
[Android] Fix handling manual code in CHIPTool

### LINKED ISSUE #29254: [BUG][ANDROID] crash happens when click submit button in BarcodeFragment
### Reproduction steps

```
1. click PROVISION CHIP DEVICE WITH WI-FI button
2. input manual Code in manualCodeEditText
3. click submit button 
```

I'm trying to commit with manual code.
If you enter the manual code in the manualCodeEditText and press the submit button, the following error will be output. Errors always occur and the same error occurs.

```
2023-09-14 20:52:30.728 14527-14559 EGL_emulation           com.google.chip.chiptool             D  app_time_stats: avg=178.66ms min=1.74ms max=3995.70ms count=26
2023-09-14 20:52:30.762 14527-14527 BarcodeFragment         com.google.chip.chiptool             D  Submit Code:00238352384
2023-09-14 20:52:30.799 14527-14527 BarcodeFragment         com.google.chip.chiptool             E  Unrecognized QR Code
                                                                                                    chip.onboardingpayload.UnrecognizedQrCodeException: Invalid QR code string: Invalid argument
                                                                                                    	at chip.onboardingpayload.QRCodeOnboardingPayloadParser.populatePayload(QRCodeOnboardingPayloadParser.kt:33)
                                                                                                    	at chip.onboardingpayload.OnboardingPayloadParser.fetchPayloadFromQrCode(OnboardingPayloadParser.kt:57)
                                                                                                    	at chip.onboardingpayload.OnboardingPayloadParser.parseQrCode(OnboardingPayloadParser.kt:29)
                                                                                                    	at com.google.chip.chiptool.setuppayloadscanner.BarcodeFragment.handleInputQrCode(BarcodeFragment.kt:184)
                                                                                                    	at com.google.chip.chiptool.setuppayloadscanner.BarcodeFragment.startCamera$lambda$4(BarcodeFragment.kt:144)
                                                                                                    	at com.google.chip.chiptool.setuppayloadscanner.BarcodeFragment.$r8$lambda$PHMLMYvbztzuIAiFA4akk56IY_0(Unknown Source:0)
                                                                                                    	at com.google.chip.chiptool.setuppayloadscanner.BarcodeFragment$$ExternalSyntheticLambda9.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:7441)
                                                                                                    	at android.view.View.performClickInternal(View.java:7418)
                                                                                                    	at android.view.View.access$3700(View.java:835)
                                                                                                    	at android.view.View$PerformClick.run(View.java:28676)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2023-09-14 20:52:30.800 14527-14527 Compatibil...geReporter com.google.chip.chiptool             D  Compat change id reported: 147798919; UID 10150; state: ENABLED
2023-09-14 20:52:30.803 14527-14527 AndroidRuntime          com.google.chip.chiptool             D  Shutting down VM
2023-09-14 20:52:30.805 14527-14527 AndroidRuntime          com.google.chip.chiptool             E  FATAL EXCEPTION: main
                                                                                                    Process: com.google.chip.chiptool, PID: 14527
                                                                                                    kotlin.UninitializedPropertyAccessException: lateinit property payload has not been initialized
                                                                                                    	at com.google.chip.chiptool.setuppayloadscanner.BarcodeFragment.handleInputQrCode(BarcodeFragment.kt:198)
                                                                                                    	at com.google.chip.chiptool.setuppayloadscanner.BarcodeFragment.startCamera$lambda$4(BarcodeFragment.kt:144)
                                                                                                    	at com.google.chip.chiptool.setuppayloadscanner.BarcodeFragment.$r8$lambda$PHMLMYvbztzuIAiFA4akk56IY_0(Unknown Source:0)
                                                                                                    	at com.google.chip.chiptool.setuppayloadscanner.BarcodeFragment$$ExternalSyntheticLambda9.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:7441)
                                                                                                    	at android.view.View.performClickInternal(View.java:7418)
                                                                                                    	at android.view.View.access$3700(View.java:835)
                                                                                                    	at android.view.View$PerformClick.run(View.java:28676)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

2e9c162e8048b839fd9780840b0d1a9d4e541959

### Platform

android

### Platform Version(s)

_No response_

### Anything else?

Code: 00238352384

### PR DESCRIPTION
**Pull request by pachuho**
Fixes #29254

#### Problem

crash happens when click submit button in BarcodeFragment

#### Change summary

Modified the handleInputQrCode called when manualCodeBtn is clicked.
Previously, when OnboardingPayloadException occurred, the parseManualPairingCode was called. But in that commit
The string of the code was identified and processed to call the parseQrCode or parseManualPairingCode.

#### Testing
Tested the fix with the android by following the repro steps in the issue cited above.

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]
Thank you! LGTM

**Comment by andy31415** [comment]
@pachuho could you run kotlin formater on this? The CI presubmit cheker complains that the file is not formatted.

File: examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/setuppayloadscanner/BarcodeFragment.kt [hunk 1]
```diff
@@ -178,24 +178,24 @@ class BarcodeFragment : Fragment() {
     }
   }
 
-  private fun handleInputQrCode(qrCode: String) {
+  private fun handleInputCode(code: String) {
     lateinit var payload: OnboardingPayload
```
Comment (andy31415) [inline examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/setuppayloadscanner/BarcodeFragment.kt:182]: Does payload need to be lateinit anymore? We could inline it on line 184

Comment (pachuho) [reply examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/setuppayloadscanner/BarcodeFragment.kt]: @andy31415  Thank you for a good idea. I removed lateinit because it was not required. 
Additionally, i modified the class to match the kotlin format. Please let me know if you need anything else.

**Comment by andy31415** [comment]
@pachuho your formatter somehow is different. I re-ran `./scripts/helpers/kotlin-format.sh` and merged the change to your branch as a maintainer push.

I believe this should merge now.

**Review by andy31415 — APPROVED** [review]
