### PR TITLE
[Microwave Oven] Fix build error for Microwave Oven APP

### LINKED ISSUE #31525: [BUG] Build error for microwave-oven app
### Reproduction steps

Tried to build the microwave-oven exemple app using the following command:
```
scripts/build/build_examples.py --target linux-x64-microwave-oven-ipv6only build
```

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

a0334268f379bbac96b8bf9161a501f29d0298bb

### Platform

vscode

### Platform Version(s)

_No response_

### Anything else?

Failure logs: [failure.log](https://github.com/project-chip/connectedhomeip/files/13981066/failure.log)

Build was successful when using SHA `9034671cab2891c140fdb32a6863e3429b9fe4d8`.

### PR DESCRIPTION
**Pull request by liangpy4**
Fixes: #31525 

Description:
Add static_cast for unsigned value to avoid complie error(ASR plaform).

### CODE REVIEW

File: src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.cpp [hunk 1]
```diff
@@ -105,15 +105,27 @@ bool Instance::HasFeature(MicrowaveOvenControl::Feature feature) const
...
+bool Instance::CheckSupportedWattLevelsValid() const
 {
     uint8_t wattIndex = 0;
     uint16_t watt     = 0;
     while (mDelegate->GetWattSettingByIndex(wattIndex, watt) == CHIP_NO_ERROR)
     {
         wattIndex++;
     }
-    return wattIndex;
+    return wattIndex > 0 && watt > 0;
```
Comment (bzbarsky-apple) [inline src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.cpp:116]: Why are we now adding the check that `watt > 0`?

File: src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.cpp [hunk 2]
```diff
@@ -313,13 +325,8 @@ void Instance::HandleSetCookingParameters(HandlerContext & ctx, const Commands::
             cookMode.HasValue() || cookTimeSec.HasValue() || wattSettingIndex.HasValue(), status = Status::InvalidCommand;
             ChipLogError(Zcl, "Microwave Oven Control: Failed to set cooking parameters, all command fields are missing "));
 
-        // count of supported watt levels must greater than 0
-        VerifyOrExit(
-            mSupportedWattLevels > 0,
-            ChipLogError(Zcl, "Microwave Oven Control: Failed to set wattSettingIndex, count of supported watt levels is 0"));
-
-        reqWattSettingIndex = wattSettingIndex.ValueOr(mSupportedWattLevels - 1);
```
Comment (bzbarsky-apple) [inline src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.cpp:321]: So in the old code, since we had checked mSupportedWattLevels > 0, this was safe; we just needed to explicitly cast the subtraction result to `uint8_t`, right?

Why are we adding all the other complexity?

File: src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.h [hunk 3]
```diff
@@ -85,8 +83,9 @@ class Instance : public CommandHandlerInterface, public AttributeAccessInterface
     Clusters::OperationalState::Instance & mOpStateInstance;
     Clusters::ModeBase::Instance & mMicrowaveOvenModeInstance;
 
-    uint32_t mCookTimeSec        = kDefaultCookTimeSec;
-    uint8_t mSupportedWattLevels = 0;
+    uint32_t mCookTimeSec                = kDefaultCookTimeSec;
+    uint8_t mSupportedWattLevels         = 0;
```
Comment (bzbarsky-apple) [inline src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.h:87]: Isn't mSupportedWattLevels unused now?  It's certainly not assigned to anymore...

**Review by bzbarsky-apple — COMMENTED** [review]
Please check the codesize and memory results once those are available (we _are_ tracking that for this example app, right?), but at first glance this is adding more code (but maybe not?) and an extra member for not particular benefit....

File: src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.cpp (hunk 2 above)
Comment (liangpy4) [reply src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.cpp:321]: I see, we will change to add the static_cast on `mSupportedWattLevels - 1`

File: src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.cpp [hunk 4]
```diff
@@ -105,15 +105,27 @@ bool Instance::HasFeature(MicrowaveOvenControl::Feature feature) const
...
+    return wattIndex > 0 && watt > 0;
+}
+
+uint8_t Instance::GetMaxSupportedWattLevelsIndex() const
+{
+    uint8_t wattIndex = 0, maxWattIndex = 0;
+    uint16_t watt = 0;
+    while (mDelegate->GetWattSettingByIndex(wattIndex, watt) == CHIP_NO_ERROR)
+    {
+        maxWattIndex = wattIndex;
```
[the remark this answers is not in the document]
Comment (liangpy4) [reply src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.cpp:125]: That will cause the complie error if using substraction on wattIndex(unsigned). But now the fix solution is to add static_cast on `(mSupportedWattLevels - 1)`, this method will not be used.

> ```c++
> return (wattIndex - 1);
> ```

File: src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.cpp (hunk 1 above)
Comment (liangpy4) [reply src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.cpp]: just in case the SDK user set watt number to 0.

**Review by yunhanw-google — APPROVED** [review]

**Review by rbultman — APPROVED** [review]

**Comment by cecille** [comment]
Is the microwave oven app currently compiled in the CI? It seems like this should have been caught automatically. If it's not there, can it be added?

**Comment by rbultman** [comment]
> Is the microwave oven app currently compiled in the CI? It seems like this should have been caught automatically. If it's not there, can it be added?

I'm working on this...

File: src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.cpp [hunk 5]
```diff
@@ -318,8 +318,8 @@ void Instance::HandleSetCookingParameters(HandlerContext & ctx, const Commands::
             mSupportedWattLevels > 0,
             ChipLogError(Zcl, "Microwave Oven Control: Failed to set wattSettingIndex, count of supported watt levels is 0"));
 
-        reqWattSettingIndex = wattSettingIndex.ValueOr(mSupportedWattLevels - 1);
-        VerifyOrExit(reqWattSettingIndex <= (mSupportedWattLevels - 1), status = Status::ConstraintError;
+        reqWattSettingIndex = wattSettingIndex.ValueOr(static_cast<uint8_t>(mSupportedWattLevels - 1));
```
Comment (bzbarsky-apple) [inline src/app/clusters/microwave-oven-control-server/microwave-oven-control-server.cpp:321]: Might have been clearer to do `uint8_t maxWattLevelIndex = static_cast<uint8_t>(mSupportedWattLevels - 1);` and then use that in the checks, but this is fine.

**Review by bzbarsky-apple — APPROVED** [review]
