### PR TITLE
Don't try to establish PASE while we are shutting down.

### LINKED ISSUE #20271: [TC-MF-1.9] Manual code command with the wrong pin code supposed to be failed, it causes a crash on the chip-tool side.
Problem:
If we try the manual code command with the wrong pin code supposed to be failed, it causes a crash on the chip-tool side.

Actual Behavior :
Creating with chip stack locking error.

Expected Behavior:
It should fail with PASE session error message 

App used - lock app
Platform - Chip-tool - RPI-4, 8GB RAM
DUT - EFR32 + WF200 , EFR32 +RS9116
Network - Ble-wifi

Logs
[Device 1 chip-tool logs.txt](https://github.com/project-chip/connectedhomeip/files/9039857/Device.1.chip-tool.logs.txt)
[Device 2 chip-tool logs.txt](https://github.com/project-chip/connectedhomeip/files/9039858/Device.2.chip-tool.logs.txt)
[TC-MF-1.9_1 Device Logs.txt](https://github.com/project-chip/connectedhomeip/files/9039859/TC-MF-1.9_1.Device.Logs.txt)
:

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Shutdown of a DeviceCommissioner needs to suppress the "try the next
discovered thing on error" behavior of SetUpCodePairer.

Fixes https://github.com/project-chip/connectedhomeip/issues/20271

#### Problem
See #20271

#### Change overview
Make sure we don't try to do PASE to the next discovered thing if we're shutting down.

#### Testing
Checked manually that we don't end up in the situation #20271 ran into.

### CODE REVIEW

File: src/controller/SetUpCodePairer.cpp [hunk 1]
```diff
@@ -308,6 +308,11 @@ void SetUpCodePairer::NotifyCommissionableDeviceDiscovered(const Dnssd::Discover
     ConnectToDiscoveredDevice();
 }
 
+void SetUpCodePairer::CommissionerShuttingDown()
+{
+    ResetDiscoveryState();
```
Comment (msandstedt) [inline src/controller/SetUpCodePairer.cpp:313]: I don't think this actually works completely:

```
CHIP_ERROR BLEManagerImpl::CancelConnection()
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
```

Our BLE operations on a lot of platforms aren't very cancelable.  For this to fully work, I think we'd either need those cancelable features in the platform BLE implementations, or we'd need some type of 'join' behavior from the commisisoner where it waits for pending BLE things.

Comment (bzbarsky-apple) [reply src/controller/SetUpCodePairer.cpp:313]: I agree this does not fully work as things stand.  The situation this is trying to resolve is when we have queued-up things discovered via dns-sd that we have not tried yet, so we don't start trying them.

If we have an active BLE discovery process, then as you note we don't have a great way to cancel it on some platforms...  We could try to block shutdown on it, I guess, but it's pretty difficult to do that sanely, espeially since by the time we get to here we're typically already shut down the Matter event loop.

I'd suggest we do followup work here in separate PRs.

Comment (msandstedt) [reply src/controller/SetUpCodePairer.cpp:313]: That makes sense.  If there's any concise way to have an issue filed that covers the 'in-flight' cases this PR doesn't cover, that would be welcome.

**Review by msandstedt — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

File: src/controller/SetUpCodePairer.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/controller/SetUpCodePairer.cpp:313]: Filed https://github.com/project-chip/connectedhomeip/issues/20781 as an attempt at that.
