### PR TITLE
Fixes #31578 Removed provisional features from DEM to align to 1.3 TE2 test plans

### LINKED ISSUE #31578: [CERT-TEST-FAILURE] - TC-DEM-1.1 - Test failed
### Feature Area

Other

### Test Case

TC-DEM-1.1

### Reproduction steps

1. Bring up the DUT with All-clusters-app.
2. Pair the DUT using chip-tool through "Onnetwork" transport.
3. Run the command `./chip-tool deviceenergymanagement read feature-map 1 1`

**Expected Outcome:**

> [1705565302.904580][7054:7056] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0098 Attribute 0x0000_FFFC DataVersion: 1117764527
> [1705565302.904631][7054:7056] CHIP:TOO:   FeatureMap: 31

**Actual Outcome:**

> [1705565302.904580][7054:7056] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0098 Attribute 0x0000_FFFC DataVersion: 1117764527
> [1705565302.904631][7054:7056] CHIP:TOO:   FeatureMap: 127

### Bug prevalence

Whenever I try to read FeatureMap.

### GitHub hash of the SDK that was being used

0ff709f25f6a7af68314c1b0a147a76c30c234f6

### Platform

raspi

### Anything else?

In SPEC, the `ForecastAdjustment(FA)` and `ConstraintBasedAdjustment(CON)` feature is `PROVISIONAL` but in ACA these features are enabled. So FA and CON features has to be disabled in ACA as it is provisional.

**Specification Reference:**
image

### PR DESCRIPTION
**Pull request by jamesharrow**
Fixes #31578 

Removed provisional features from:
- all-clusters-app/device-energy-management-stub.cpp
- energy-management-app/linux/main.cpp
- energy-management-app/esp32/main.cpp

### CODE REVIEW

**Comment by jamesharrow** [comment]
Tested with chip-repl:

│   │   │   <class 'chip.clusters.Objects.DeviceEnergyManagement.Attributes.FeatureMap'>: 31,

File: examples/energy-management-app/esp32/main/main.cpp [hunk 1]
```diff
@@ -154,8 +154,7 @@ CHIP_ERROR DeviceEnergyManagementInit()
         BitMask<DeviceEnergyManagement::Feature, uint32_t>(
             DeviceEnergyManagement::Feature::kPowerAdjustment, DeviceEnergyManagement::Feature::kPowerForecastReporting,
             DeviceEnergyManagement::Feature::kStateForecastReporting, DeviceEnergyManagement::Feature::kStartTimeAdjustment,
-            DeviceEnergyManagement::Feature::kPausable, DeviceEnergyManagement::Feature::kForecastAdjustment,
-            DeviceEnergyManagement::Feature::kConstraintBasedAdjustment));
+            DeviceEnergyManagement::Feature::kPausable));
```
Comment (cecille) [inline examples/energy-management-app/esp32/main/main.cpp:157]: not a blocker, but this couples the endpoint configuration and the example app - ie, if you return here that all the features are supported, then the zap conformance needs to match that. I mean, given that this IS an example app, that seems reasonable, but it might be worthwhile to note that in the readme somewhere (if it's not there already) because there is a tendency for folks to blindly copy the examples. Which, I suppose, is a problem in an of itself. Maybe a cert failure is what you get for blindly copying examples.

**Review by cecille — APPROVED** [review]

File: examples/energy-management-app/esp32/main/main.cpp (hunk 1 above)
Comment (jamesharrow) [reply examples/energy-management-app/esp32/main/main.cpp:157]: I can add a comment here - but these should be greyed out in ZAP as the are implemented in the Read AttributeInterface handler https://github.com/project-chip/connectedhomeip/blob/e5f5d6798ed47706078462f1697c481a8dc60bfa/src/app/clusters/device-energy-management-server/device-energy-management-server.cpp#L97  and not set via ZAP.

This https://github.com/project-chip/connectedhomeip/blob/e5f5d6798ed47706078462f1697c481a8dc60bfa/src/app/zap-templates/zcl/zcl-with-test-extensions.json#L192 should be stopping ZAP from being editable.

**Review by saurabhst — APPROVED** [review]
