### PR TITLE
[Silabs] Adds fix for stalling LwIP SLAAC process

### LINKED ISSUE #26966: [BUG] [EFR32] LwIP stalling after an hour when device is reconnecting to WiFi AP several times
### Steps to reproduce:
  1. Connected the device using `chip-tool pairing ble-wifi` with additional details of SSID PSK PASSCODE DISCRIMINATOR
  2. Reconnect the device using scripted automated runs. Roughly tested with reconnections every 15 seconds/30 seconds.

### Observation:
  1. The device connects back to WiFi AP, LwIP starts the SLAAC-DAD process but stops marking the address as preferred. This is taking around an hour to occur with the above automation.

### Bug prevalence

hourly

### GitHub hash of the SDK that was being used

cfb9994bd2ce10e356f71470c4c8e3b509f70f26

### Platform

efr32

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rosahay-silabs**
Fixes #26966 by explicitly invoking the SLAAC process since LwIP stops invoking it after exactly 79mins.

### CODE REVIEW

**Comment by jmartinez-silabs** [comment]
Why does `LwIP stops invoking it after exactly 79mins `?  If it is always needed should the Lwip process continue to do so?

File: examples/platform/silabs/SiWx917/SiWx917/rsi_if.c [hunk 1]
```diff
@@ -561,6 +562,10 @@ void wfx_rsi_task(void * arg)
                 /* Checks if the assigned IPv6 address is preferred by evaluating
                  * the first block of IPv6 address ( block 0)
                  */
+                if (!hasNotifiedIPV6)
```
Comment (selissia) [inline examples/platform/silabs/SiWx917/SiWx917/rsi_if.c:565]: The comment above should be moved to the if() statement it applies to. Similar change also needed below.

**Review by andy31415 — APPROVED** [review]

**Review by selissia — APPROVED** [review]
