### PR TITLE
Include non-fabric-associated pending roots in the RootCertificates attribute.

### LINKED ISSUE #20791: [TC-CGEN-2.2]--AddTrustedRootCertificate command  Fails to add TrustedRootCertificate
****#### Problem****
add-trusted-root-certificate command is not working, TH sends add-trusted-root-certificate to DUT then if TH read the trsusted root certificate attribute where it should list 2 entries but instead lists 1 entry
 
 ****expected behavior:****-The number of items in the returned list is numTrustedRootsOriginal + 1
  **actual behavior:-**
image

  ***** steps to reproduce:--****
To generate TrustedRootCertificate, need to buld chip-cert in connectedhomeip by giving below mentioned commands
1. gn gen --check out/debug
2. ninja -v -C out/debug chip-cert
Once build completes 
3.  ./chip-cert gen-cert --type r --subject-chip-id CACACACA00000001 --valid-from "2020-10-15 14:23:43" --lifetime 7305 --out-key Chip-Root-Key.pem --out Chip-Root-Cert.pem --out-format x509-pem
4. cat Chip-Root-Key.pem 
FTABAQAkAgE3AyQUABgmBIAigScmBYAlTTo3BiQUABgkBwEkCAEwCUEEcHhi5skO0neoie7A8cAE0AhLfjo1GZJLURJBw/MuMi24aVlrHrtZuwqe3E/wtVUK5kv5jWWTustZ9Jse8ZHyfDcKNQEpARgkAmAwBBRVQgQw34aJK7lbbOiFhZPiQdyq7DAFFFVCBDDfhokruVts6IWFk+JB3KrsGDALQLgPckNnCsuVE/LGmZ5GGWcBnc5+ZNLl91xUR6JFBYBOw6SEyNGUdWFkl1530ov3XhD+lbLcZ3IMgds0rCgaf0QY

-    ./chip-tool generalcommissioning  arm-fail-safe   60 1 1 0

-    ./chip-tool  operationalcredentials add-trusted-root-certificate FTABAQAkAgE3AyQUABgmBIAigScmBYAlTTo3BiQUABgkBwEkCAEwCUEEcHhi5skO0neoie7A8cAE0AhLfjo1GZJLURJBw/MuMi24aVlrHrtZuwqe3E/wtVUK5kv5jWWTustZ9Jse8ZHyfDcKNQEpARgkAmAwBBRVQgQw34aJK7lbbOiFhZPiQdyq7DAFFFVCBDDfhokruVts6IWFk+JB3KrsGDALQLgPckNnCsuVE/LGmZ5GGWcBnc5+ZNLl91xUR6JFBYBOw6SEyNGUdWFkl1530ov3XhD+lbLcZ3IMgds0rCgaf0QY  1  0

-   ./chip-tool  operationalcredentials read  trusted-root-certificates 1 0 

****system configuration****
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : IP and wifi
Commit-ID: 0390a8d33b1d1c709fcc4499eab6e132428ad5e2
Dut application: all-clusters-app

****Test-Plan Reference:-****
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/General_Commissioning.adoc#tc-cgen-2-2-armfailsafe-command-verification-dut-server

**PFA log below:-**
[TC-CGEM-2.2.txt](https://github.com/project-chip/connectedhomeip/files/9120085/TC-CGEM-2.2.txt)

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Fixes https://github.com/project-chip/connectedhomeip/issues/20791

Also moves a function that was supposed to be private from public to private.

### CODE REVIEW

File: src/credentials/FabricTable.cpp [hunk 1]
```diff
@@ -554,6 +554,24 @@ CHIP_ERROR FabricTable::FetchRootCert(FabricIndex fabricIndex, MutableByteSpan &
     return mOpCertStore->GetCertificate(fabricIndex, CertChainElement::kRcac, outCert);
 }
 
+CHIP_ERROR FabricTable::FetchPendingNonFabricAssociatedRootCert(MutableByteSpan & outCert) const
```
Comment (tcarmelveilleux) [inline src/credentials/FabricTable.cpp:557]: Please add a unit test to fabrictable for this method

**Review by tcarmelveilleux — APPROVED** [review]

File: src/credentials/FabricTable.h [hunk 2]
```diff
@@ -948,6 +951,19 @@ class DLL_EXPORT FabricTable
...
+     *
+     * NOTE: This is private for use within the FabricTable itself. All mutations have to go through the
+     *       FabricTable public methods that take a FabricIndex so that there are no mutations about which
+     *       the FabricTable is unaware, since this would break expectations regarding shadow/pending
+     *       entries used during fail-safe.
+     *
+     * @param fabricIndex - fabric index for which to get a mutable FabricInfo entry
+     * @return the FabricInfo entry for the fabricIndex if found, or nullptr if not found
+     */
+    FabricInfo * GetMutableFabricByIndex(FabricIndex fabricIndex);
```
Comment (tcarmelveilleux) [inline src/credentials/FabricTable.h:965]: Thanks!

File: src/credentials/FabricTable.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/credentials/FabricTable.cpp:557]: Good point; I was trying to figure out how to test this in YAML, but unit test is easy.  https://github.com/project-chip/connectedhomeip/pull/21016/commits/dbc9858be719b480895a757d8214a03b56adfb68

**Review by woody-apple — APPROVED** [review]
