### PR TITLE
Fix rendezvous bypass mode

### LINKED ISSUE #6578: Pairing via Bypass (Rendezvous mode) Fails
#### Problem
 * expected behavior: Ability to pair via Bypass method fails using (Tested with commit: ab8122e4e05f9757a9156c4f23f4a27f715a5bf2, Last commit that I tested this functionality and was successful: 92e3683cd0a2772b91c08e0b0109395f94944f1b), I can try to pinpoint the commit that may have introduced this regression a bit later.
 * actual behavior: Failure to pair with the device
 * steps to reproduce: `chip-tool pairing bypass {ip_addr} 11097`, I am attempting to pair a M5Stack running the `all-clusters` example app using the  ab8122e4e05f9757a9156c4f23f4a27f715a5bf2 commit.
 * system configuration: Linux (Ubuntu)
 * Logs:
 
```
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x000000000001b669
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:IN: New pairing for device 0x0000000000bc5c01, key 65535!!
CHIP:BLE: Failed in setting up secure channel: err CHIP Error 4003 (0x00000FA3): Incorrect state
CHIP:TOO: Secure Pairing Failed
CHIP:DL: CHIP task running
CHIP:TOO: Pairing Failure: CHIP Error 4003 (0x00000FA3): Incorrect state
CHIP:CTL: Shutting down the commissioner
CHIP:CTL: Shutting down the controller
CHIP:DL: System Layer shutdown
CHIP:DL: Inet Layer shutdown
CHIP:DL: BLE layer shutdown
```

 #### Proposed Solution

### PR DESCRIPTION
**Pull request by pan-apple**
#### Problem
Rendezvous bypass mode is not working. It's failing in establishing the secure session.

 #### Summary of Changes
Recent controller changes mixed using test secret with non-test pairing. This change makes sure that the test secret is used for establishing the secure session when bypass mode is being used.

Fixes #6578

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by tcarmelveilleux — APPROVED** [review]
Suggest adding handling of better error message for:

```
VerifyOrExit(peerAddress.GetTransportType() == Transport::Type::kUdp, err = CHIP_ERROR_INVALID_ARGUMENT);
```

to make clear that `PairTestDeviceWithoutSecurity` is BLE-only

**Comment by kianooshkarami** [comment]
> Suggest adding handling of better error message for:
> 
> ```
> VerifyOrExit(peerAddress.GetTransportType() == Transport::Type::kUdp, err = CHIP_ERROR_INVALID_ARGUMENT);
> ```
> 
> to make clear that `PairTestDeviceWithoutSecurity` is BLE-only

@tcarmelveilleux I am a bit confused by your comment about `PairTestDeviceWithoutSecurity` being BLE-only, did you mean UDP-Only?

File: src/controller/CHIPDeviceController.cpp [hunk 1]
```diff
@@ -848,7 +848,31 @@ CHIP_ERROR DeviceCommissioner::PairTestDeviceWithoutSecurity(NodeId remoteDevice
 
     device->Serialize(serialized);
 
-    OnSessionEstablished();
+    err = mSessionMgr->NewPairing(Optional<Transport::PeerAddress>::Value(peerAddress), device->GetDeviceId(),
+                                  testSecurePairingSecret, SecureSession::SessionRole::kInitiator, mAdminId, nullptr);
+    if (err != CHIP_NO_ERROR)
+    {
+        ChipLogError(Ble, "Failed in setting up secure channel: err %s", ErrorStr(err));
```
Comment (kianooshkarami) [inline src/controller/CHIPDeviceController.cpp:855]: nit: Does `controller` make a better logging module?

**Review by Damian-Nordic — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by kianooshkarami — APPROVED** [review]
Thanks for fixing this issue
