### PR TITLE
move PrepareListFromTLV into its own file

### LINKED ISSUE #9222: PrepareListFromTLV sometimes generated but not used - can't compile
#### Problem
`PrepareListFromTLV()` is sometimes generated in `CHIPClientCallbacks.cpp` but not used, and this causes compiler errors due to `[-Werror=unused-function`]:

```
../../examples/ota-requestor/linux/third_party/connectedhomeip/zzz_generated/ota-requestor-app/zap-generated/CHIPClientCallbacks.cpp:351:22: error: ‘EmberAfStatus PrepareListFromTLV(chip::TLV::TLVReader*, const uint8_t*&, uint16_t&)’ defined but not used [-Werror=unused-function]
  351 | static EmberAfStatus PrepareListFromTLV(TLV::TLVReader * tlvData, const uint8_t *& message, uint16_t & messageLen)
      |                      ^~~~~~~~~~~~~~~~~~
```

To be more specific: `PrepareListFromTLV()` is always generated for any application with client clusters, but the usage of `PrepareListFromTLV()` is only generated under the following conditions:
```
{{#chip_client_clusters}}
{{#if (chip_server_has_list_attributes)}}
{{#chip_server_cluster_attributes}}
{{#if isList}}
void {{asUpperCamelCase parent.name}}Cluster{{asUpperCamelCase name}}ListAttributeFilter(TLV::TLVReader * tlvData, Callback::Cancelable * onSuccessCallback, Callback::Cancelable * onFailureCallback)
{
    // TODO: Add actual support for array and lists.
    const uint8_t * message = nullptr;
    uint16_t messageLen     = 0;
    EmberAfStatus res = PrepareListFromTLV(tlvData, message, messageLen);
```

So compiling will fail for an application with client clusters, but where the corresponding server cluster does not have list attributes.

 #### Proposed Solution
I proposed an outline for a fix in: https://github.com/project-chip/connectedhomeip/pull/8772. This involves writing a new javascript function `chip_any_server_has_list_attributes` to guard generation of `PrepareListFromTLV()`.

### PR DESCRIPTION
**Pull request by holbrookt**
#### Problem
What is being fixed?  Examples:
* `PrepareListFromTLV()` is always generated in `CHIPClientCallbacks.cpp` but its usage is conditionally generated, which means certain cases can have compiler errors for having an unused function. Moving it to its own file avoids this issue.
* Fixes #9222

This is preventing compilation of the ota-requestor app that is in development.

#### Change overview
- Move `PrepareListFromTLV()` into `prepare-list.h`
- remove generation from `CHIPClientCallbacks-src.zapt` and include `prepare-list.h` instead

#### Testing
Main builds pass, and confirmed special case with unused `PrepareListFromTLV()` now builds successfully.

### CODE REVIEW

**Review by msandstedt — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@bzbarsky-apple ?

File: src/app/util/prepare-list.h [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+ */
+
+#pragma once
+
+#include <app/util/af-enums.h>
+
+#include <core/CHIPTLV.h>
+#include <lib/support/SafeInt.h>
+
+static EmberAfStatus PrepareListFromTLV(chip::TLV::TLVReader * tlvData, const uint8_t *& message, uint16_t & messageLen)
```
Comment (bzbarsky-apple) [inline src/app/util/prepare-list.h:25]: I would expect this to give the same "unused function" errors that we get with the static inside the template now...  Shouldn't we make this non-static and put the implementation into a .cpp file?

**Review by jelderton — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
