### PR TITLE
[tlv] Disable 64-bit lengths. NCC-E003350-GH4

### LINKED ISSUE #19340: TLV Reader improperly processes 64-bit lengths
#### Problem

In `CHIPTLVReader.cpp` in `TLVReader::GetLength()` we see an incorrect cast to a 32-bit value.  The TLV spec does provide for a 64-bit length field for UTF-8 strings and for byte strings, and the code does appear to properly parse out the values; however, the remainder of the TLV parsing code lengths to 32-bit quantities. 

 #### Proposed Solution
For version 1.0, error out on any length that cannot be stored in a 32-bit quantity

### PR DESCRIPTION
**Pull request by turon**
#### Problem
Fix #19340

TLV support for 64-bit lengths is impractical.
Few if any Matter devices will have >4GB buffers to support even one such element.

NCC-E003350-GH4

#### Change overview
Return ERROR_NOT_IMPLEMENTED when provided 64-bit length exceeds max 32-bit length.
This prevents potential buffer overflow attacks.

#### Testing
CI
Need to add or verify existence of test cases for the new behaviors:
- [ ] TLV with 64-bit length <= UINT32_MAX (expect success) -- may exist
- [ ] TLV with 64-bit length > UINT32_MAX (expect error) -- probably need to add

### CODE REVIEW

File: src/lib/core/CHIPTLVReader.cpp [hunk 1]
```diff
@@ -731,10 +731,14 @@ CHIP_ERROR TLVReader::ReadElement()
         break;
     case kTLVFieldSize_8Byte:
         mElemLenOrVal = LittleEndian::Read64(p);
+        VerifyOrExit(!TLVTypeHasLength(elemType) || (mElemLenOrVal <= UINT32_MAX), err = CHIP_ERROR_NOT_IMPLEMENTED);
```
Comment (bzbarsky-apple) [inline src/lib/core/CHIPTLVReader.cpp:734]:
```suggestion
        VerifyOrReturnError(!TLVTypeHasLength(elemType) || (mElemLenOrVal <= UINT32_MAX), CHIP_ERROR_NOT_IMPLEMENTED);
```
and then you don't need to mess with the `exit:` bits...

**Review by bzbarsky-apple — APPROVED** [review]

File: src/lib/core/CHIPTLVReader.cpp (hunk 1 above)
Comment (andy31415) [inline src/lib/core/CHIPTLVReader.cpp:734]: why do we need the exit macro? Could we just "return CHIP_ERROR_NOT_IMPLEMENTED" ?

Comment (turon) [reply src/lib/core/CHIPTLVReader.cpp]: updated

**Review by emargolis — APPROVED** [review]
