### PR TITLE
Catch or release ObjectPool leaks

### LINKED ISSUE #11880: Possible use of destroyed pool objects
#### Problem

Historically, objects allocated from a pool have not been destroyed or flagged when the pool is destroyed. https://github.com/project-chip/connectedhomeip/runs/4228395289 appears be failing due to an object (TCPEndPoint) outliving its pool.

### PR DESCRIPTION
**Pull request by kpschoedel**
#### Problem

`ObjectPool`s are sometimes destroyed while objects
remain live. For `BitMapObjectPool` case, such objects can't
be safely touched. For `HeapObjectPool` such objects can be used
but can't be released.

Some leaks have been fixed (#11983, #12031), but there are still
a few remaining.

Fixes #11880 _Possible use of destroyed pool objects_

#### Change overview

- Prevent future leaks by adding an `ObjectPool` template argument
  specifying what to do if it is destroyed with live objects: abort with
  an error message (the default), release the live objects (which calls
  their destructors), or ignore the condition (transitionally, until all
  leaks are fixed).

- Fix shutdown ordering in `DeviceControllerSystemState`.

- For existing pools in `SessionManager`, `InteractionModelEngine`,
  and `GroupDataProviderImpl`, ignore the condition.

#### Testing

CI; no changes to external functionality.

### CODE REVIEW

File: src/lib/support/Pool.h [hunk 1]
```diff
@@ -166,6 +167,16 @@ struct HeapObjectList : HeapObjectListNode
 
 } // namespace internal
 
+/**
+ * Action taken if objects remain allocated when a pool is destroyed.
+ */
+enum class OnObjectPoolDestruction
+{
+    AutoRelease,                   ///< Release any objects still allocated.
```
Comment (kpschoedel) [inline src/lib/support/Pool.h:175]: I'm of two minds about including this — an ObjectPool user can just call `ReleaseAll()` in their destructor, and without it, we could remove this parameter and unconditionally fail, if/when existing uses are addressed.

**Review by woody-apple — APPROVED** [review]

**Comment by kpschoedel** [comment]
Filed issues for the remaining leaks:

- #12503
- #12504
-  #12505

**Review by andy31415 — APPROVED** [review]

File: src/lib/support/Pool.h (hunk 1 above)
Comment (andy31415) [reply src/lib/support/Pool.h:175]: I think long-term explicit lifetime is easier to understand and enforce. Otherwise everyone will `AutoRelease` because less  code  to  write.

Comment (andy31415) [reply src/lib/support/Pool.h:175]: Then again probably does not need to be done in  this PR (or at all). I  stand by  my checkmark of approval for this.

Comment (kpschoedel) [reply src/lib/support/Pool.h:175]: I will definitely revisit this topic to remove the `IgnoreUnsafeDoNotUseInNewCode` case, and if there are no compelling use cases for `AutoRelease` by then I'll remove that as well.

**Comment by kpschoedel** [comment]
⛔ Do not merge yet — there's a (non-merge) conflict with another PR that landed recently.
