### PR TITLE
[Silabs] Cherry-pick changes to support PSA keys for the SessionKeyStore

### LINKED ISSUE #41105: [Platform] [Silabs] TrustZone breaks so that check-in message cannot be decoded by controller  in v1.4 release branch
### Reproduction steps

Using latest android chip-tool built from master, android chip-tool commission icd example app with latest code from master and 1.4.2 using silabs board successfully and check-in message can be decoded by android chip-tool successfully. Then flash the icd example app built from 1.4 release branch, the check-in message cannot be decrypted.

Bisecting 26 commits across 1.4 release branch and master branch, it seems check-in message all fails to be decoded before https://github.com/project-chip/connectedhomeip/pull/36643/files. After this commit, it works.

Please kindly take a further look for root cause and repair the 1.4 release branch asap.

### Platform

efr32

### Platform Version(s)

1.4

### Type

Hardware validated

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mkardous-silabs**
#### Summary
PR cherry-picks all the necessary changes to support PSA keys for the SessionKeyStore which translates to using PSA keys for the Check-In message.
These changes are necessary due to an interop issue with the android chip-tool crypto engine that could not decrypt the check-in message.
PR is a cherry-pick of multiple PRs except the last commit to fix build issues.

#### Related issues

**Note to reviewers:** The description in the issue does not clearly describe the problem. The tipping point that caused the issue was a PR to support TrustZone, but the issue was not fixed by TrustZone. The required changes span several PRs.

Fixes #41105

#### Testing

1. Built an LongIdleTime ICD
2. Commissioned the devices using the `--icd-registration` flag during commissioning
3. Rebooted the device to validated keys were properly stored and Check-In message could be sucesffuly descryped by the c++ chip-tool and android chip-tool.

#### Readability checklist

The checklist below will help the reviewer finish PR review in time and keep the
code readable:

-   [ ] PR title is
        [descriptive](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html#title-formatting)
-   [ ] Apply the
        [_“When in Rome…”_](https://project-chip.github.io/connectedhomeip-doc/style/CODING_STYLE_GUIDE.html)
        rule (coding style)
-   [ ] PR size is short
-   [ ] Try to avoid "squashing" and "force-update" in commit history
-   [ ] CI time didn't increase

See: [Pull Request Guidelines](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html)

### CODE REVIEW

File: src/platform/silabs/platformAbstraction/WiseMcuSpam.cpp [hunk 1]
```diff
@@ -17,11 +17,13 @@
 
 #include <platform/silabs/platformAbstraction/SilabsPlatform.h>
 #include <sl_si91x_button_pin_config.h>
+#include <sl_si91x_common_flash_intf.h>
 
 #include <FreeRTOS.h>
 #include <task.h>
 
 #include <app/icd/server/ICDServerConfig.h>
+#include <lib/support/CodeUtils.h>
```
Comment (mkardous-silabs) [inline src/platform/silabs/platformAbstraction/WiseMcuSpam.cpp]:
```suggestion
```

**Review by jmartinez-silabs — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]
