### PR TITLE
Fix mdns resolution on darwin

### LINKED ISSUE #7120: resolve command using link local address on Mac
resolve command using link local address on Mac

chip-device-ctrl > resolve 0 12344321
[1622004214972] [0x4b066c] CHIP: [DL] Mdns: OnGetAddrInfo hostname:246F288FD758.local.
[1622004214972] [0x4b066c] CHIP: [DIS] Node ID resolved for 0x0000000000BC5C01
[1622004214974] [0x4b066c] CHIP: [CTL] SyncSetKeyValue on PairedDevicebc5c01
Node address has been updated
Current address: fe80::266f:28ff:fe8f:d758:11097
chip-device-ctrl > zcl OnOff Toggle 12344321 1 0
[1622004231856] [0x4affc6] CHIP: [DMG] ICR moving to [Initialize]
[1622004231858] [0x4affc6] CHIP: [DMG] ICR moving to [AddCommand]
[1622004231858] [0x4affc6] CHIP: [IN] Secure message was encrypted: Msg ID 3
[1622004231858] [0x4affc6] CHIP: [IN] Sending msg from 0x000000000001B669 to 0x0000000000BC5C01 at utc time: 130133227 msec
[1622004231858] [0x4affc6] CHIP: [IN] Sending secure msg on generic transport
[1622004231858] [0x4affc6] CHIP: [IN] Secure msg send status OS Error 2065 (0x00000811): No route to host
[1622004231858] [0x4affc6] CHIP: [-] OS Error 2065 (0x00000811): No route to host at ../../../../../src/app/CommandSender.cpp:75

Screen Shot 2021-05-25 at 10 33 13 PM

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
#### Problem
There were two issues:
1. The address type argument to Resolve() was being ignored.
2. The interface id returned by resolution was not being propagated to the OnNodeIdResolved consumer.

#### Change overview
Propagate through the address type to the point where we can use it, and propagate the interface id out to our consumer.

#### Testing
1. Tested the address type bits by modifying `CHIPDeviceController.cpp` to only request IPv4 addresses, then testing pairing between all-clusters-app on an m5Stack and chip-tool on Mac using:
    ```
    ./out/debug/standalone/chip-tool pairing ble-wifi SSID PASSWD  0 12345678 3840 
    ```
    several times and ensuring that the IPv4 address was resolved up each time (verified via the logging this PR adds).

    Then repeated the same with `CHIPDeviceController.cpp` modified to request only IPv6 addresses and verified that an IPv6 address was resolved each time.

2. Verified that when a link-local IPv6 address is resolved, I can now send commands (e.g. `./out/debug/standalone/chip-tool onoff toggle 1`) to the device instead of getting "No route to host" errors.

This does not completely resolve #7120 (nor does it try to) but it's enough to make pairing a lot more reliable for me...

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

File: src/lib/mdns/Discovery_ImplPlatform.cpp [hunk 1]
```diff
@@ -478,7 +478,12 @@ void DiscoveryImplPlatform::HandleNodeIdResolve(void * context, MdnsService * re
     nodeData.mAddress     = result->mAddress.ValueOr({});
     nodeData.mPort        = result->mPort;
 
-    ChipLogProgress(Discovery, "Node ID resolved for 0x" ChipLogFormatX64, ChipLogValueX64(nodeData.mPeerId.GetNodeId()));
+#if CHIP_PROGRESS_LOGGING
+    char addrBuffer[INET6_ADDRSTRLEN + 1];
```
Comment (cecille) [inline src/lib/mdns/Discovery_ImplPlatform.cpp:482]: Could you change this to kMaxIPAddressStringLength? It will sort itself out for the different platforms that way.

File: src/platform/Darwin/MdnsImpl.cpp [hunk 2]
```diff
@@ -446,8 +448,21 @@ CHIP_ERROR GetAddrInfo(void * context, MdnsResolveCallback callback, uint32_t in
         sdCtx->textEntries.push_back(TextEntry{ strdup(key), reinterpret_cast<const uint8_t *>(strdup(value)), valueLen });
     }
 
-    err = DNSServiceGetAddrInfo(&sdRef, 0 /* flags */, interfaceId, kDNSServiceProtocol_IPv4 | kDNSServiceProtocol_IPv6, hostname,
-                                OnGetAddrInfo, sdCtx);
+    DNSServiceProtocol protocol;
```
Comment (cecille) [inline src/platform/Darwin/MdnsImpl.cpp:451]: Not problem, just a heads up - spec paragraph [4.12] (ICHIP instances
MUST silently ignore any IPv4 addresses) is eventually going to obsolete this. No one is compliant with that yet, and we don't have a date set as far as I know. Just though you might want a heads up because I missed that when it went in.

File: src/lib/mdns/Discovery_ImplPlatform.cpp [hunk 3]
```diff
@@ -478,7 +478,12 @@ void DiscoveryImplPlatform::HandleNodeIdResolve(void * context, MdnsService * re
...
+    nodeData.mAddress.ToString(addrBuffer);
+#endif // CHIP_PROGRESS_LOGGING
```
Comment (andy31415) [inline src/lib/mdns/Discovery_ImplPlatform.cpp:484]: Ifdef extension would make it clearer that addrBuffer definition and usage are one unit.

**Review by andy31415 — APPROVED** [review]

File: src/lib/mdns/Discovery_ImplPlatform.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/lib/mdns/Discovery_ImplPlatform.cpp:482]: Good catch, will do.  Hadn't noticed `kMaxIPAddressStringLength` somehow.

File: src/platform/Darwin/MdnsImpl.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/platform/Darwin/MdnsImpl.cpp:451]: Fwiw, my understanding is that there are open issues around that part of the spec and it might change.  But yes, right now there's a spec/impl mismatch here.  #7374 at least tracks it.

File: src/lib/mdns/Discovery_ImplPlatform.cpp (hunk 3 above)
Comment (bzbarsky-apple) [reply src/lib/mdns/Discovery_ImplPlatform.cpp:484]: I was actually torn on this.  The reason for the decision I made: If the logging level of the actual log statement changes, if it's included in the #if then it might end up not being compiled when it should be.  This way it will be, and build failures would catch the need to change the #if condition.

Thoughts @andy31415 ?

**Comment by woody-apple** [comment]
@msandstedt @jepenven-silabs ? Would love some eyes on this to unblock testing. Thanks!

**Comment by woody-apple** [comment]
@saurabhst ?

**Review by msandstedt — APPROVED** [review]
