### PR TITLE
Trigger StartUp & ShutDown event on all platforms uniformly

### LINKED ISSUE #14617: Startup event is only logged on Linux platform now
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
What is being fixed?  Examples:
* Currently, Startup and ShutDown event are only logged on Linux platform, this is before those event are triggered from the platform layer and only Linux platform has the implementation. Those generic events are not platform specific, we can move the logic to generic platform implementation so that those events are triggered uniformly across platforms. 

* Fixes #14617

#### Change overview
Trigger StartUp & ShutDown event on all platforms uniformly

#### Testing
How was this tested? (at least one bullet point required)
* yufengw@yufengw-SEi:~/connectedhomeip/out/debug/standalone$ ./chip-lighting-app
```
[1643855542.352117][839528:839528] CHIP:ZCL: GeneralDiagnosticsDelegate: OnDeviceRebooted
[1643855542.352125][839528:839528] CHIP:DMG: Endpoint 0, Cluster 0x0000_0033 update version to 965a842d
[1643855542.352138][839528:839528] CHIP:ZCL: PlatformMgrDelegate: OnStartUp
[1643855542.352613][839528:839528] CHIP:EVL: LogEvent event number: 0x00000000000B0000 priority: 2, endpoint id:  0x0 

```
* Shutdown the example app
```
[1643855563.673417][839528:839528] CHIP:ZCL: PlatformMgrDelegate: OnShutDown
[1643855563.673523][839528:839528] CHIP:EVL: LogEvent event number: 0x00000000000B0001 priority: 2, endpoint id:  0x0 cluster id: 0x0000_0028 event id: 0x1 Sys timestamp: 0x00000000373B0AB3
[1643855563.673615][839528:839528] CHIP:DL: Inet Layer shutdown
[1643855563.673643][839528:839528] CHIP:DL: System Layer shutdown
```

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

File: src/include/platform/internal/GenericPlatformManagerImpl.cpp [hunk 1]
```diff
@@ -288,6 +299,27 @@ void GenericPlatformManagerImpl<ImplClass>::HandleMessageLayerActivityChanged(bo
...
 
+template <class ImplClass>
+void GenericPlatformManagerImpl<ImplClass>::HandleDeviceRebooted(intptr_t arg)
+{
+    PlatformManagerDelegate * platformManagerDelegate       = PlatformMgr().GetDelegate();
+    GeneralDiagnosticsDelegate * generalDiagnosticsDelegate = GetDiagnosticDataProvider().GetGeneralDiagnosticsDelegate();
+
+    if (generalDiagnosticsDelegate != nullptr)
+    {
+        generalDiagnosticsDelegate->OnDeviceRebooted();
```
Comment (Damian-Nordic) [inline src/include/platform/internal/GenericPlatformManagerImpl.cpp:310]: Could you also remove this call from `platform/Zephyr/PlatformManagerImpl.cpp`?

**Review by Damian-Nordic — APPROVED** [review]

File: src/include/platform/internal/GenericPlatformManagerImpl.cpp (hunk 1 above)
Comment (yufengwangca) [reply src/include/platform/internal/GenericPlatformManagerImpl.cpp:310]: Acked

**Review by yunhanw-google — APPROVED** [review]
