### PR TITLE
Remove un-named callbacks and raw integers from Darwin framework API.

### LINKED ISSUE #18020: Incorrect data type for subscription function in CHIP.framework.
#### Problem
[ChipDevice.h](https://github.com/project-chip/connectedhomeip/blob/caa1d6baca5c662c65ac156564ff3dca6eea0fb3/src/darwin/Framework/CHIP/CHIPDevice.h#L165)
has the incorrect data type in the function linked. It is currently requiring uint16_t and the others are using NSNumber.
 
 #### Proposed Solution
Update function parameters to accept NSNumber.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Switches to typedefs for all the callbacks and using NSNumber for numbers, except in MTRDeviceController (and the XPC version), which will need some more complicated changes.

Addresses part of https://github.com/project-chip/connectedhomeip/issues/22420

Review notes:

* `MTRClustersObjc_internal.h` was unused, and was not actually being generated, in spite of living in zap-generated.
* The removal of the "this file generated by ZAP" comments is also part of #22420 and is included here on purpose, since I was touching some of those files anyway.

#### Issue Being Resolved
* Fixes #18020 

#### Change overview
See above.

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRThreadOperationalDataset.h [hunk 1]
```diff
@@ -49,9 +49,9 @@ extern size_t const MTRSizeThreadPSKc;
  */
 @property (nonatomic, nullable, copy, readonly) NSData * PSKc;
 /**
- *  The Thread network channel
+ *  The Thread network channel.  Always a 16-bit integer.
```
Comment (vivien-apple) [inline src/darwin/Framework/CHIP/MTRThreadOperationalDataset.h:52]: nit: Does it worth mentioning that it is using an `unsigned` representation ?

File: src/darwin/Framework/CHIP/templates/MTRBaseClusters-src.zapt [hunk 2]
```diff
@@ -25,15 +25,17 @@ using chip::SessionHandle;
...
 {
     if (self = [super initWithQueue:queue]) {
         if (device == nil) {
             return nil;
         }
 
         _device = device;
-        _endpoint = endpoint;
+        {{!TODO consider range-checking the incoming number to make sure it's
+                actually in the uint16_t range}}
```
Comment (vivien-apple) [inline src/darwin/Framework/CHIP/templates/MTRBaseClusters-src.zapt:37]: Not for this patch, but if we start doing more and more `NSNumber` conversion to c-types, I wonder if we should end up doing some helpers that does both the conversion and the range check.

File: src/darwin/Framework/Matter.xcodeproj/xcshareddata/xcschemes/Matter Framework Tests.xcscheme [hunk 3]
```diff
@@ -38,9 +38,6 @@
                ReferencedContainer = "container:Matter.xcodeproj">
             </BuildableReference>
             <SkippedTests>
-               <Test
-                  Identifier = "MTRRemoteDeviceSampleTests">
-               </Test>
```
Comment (vivien-apple) [inline src/darwin/Framework/Matter.xcodeproj/xcshareddata/xcschemes/Matter Framework Tests.xcscheme:43]: I tried to find this test that is supposed to came from https://github.com/project-chip/connectedhomeip/commit/153a564928634654576038839f904983ac600fba and I can't tell if this is an extra line (since the header in `MTRXPCListenerSampleTests` uses `MTRRemoteDeviceSampleTests` as a name :/ ) or a file that has not been committed.

**Review by vivien-apple — APPROVED** [review]

File: src/darwin/Framework/CHIP/MTRThreadOperationalDataset.h (hunk 1 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRThreadOperationalDataset.h:52]: Yes, will do.

File: src/darwin/Framework/CHIP/templates/MTRBaseClusters-src.zapt (hunk 2 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/templates/MTRBaseClusters-src.zapt:37]: Yes, that might be nice once we start doing it.

File: src/darwin/Framework/Matter.xcodeproj/project.pbxproj [hunk 4]
```diff
@@ -97,7 +97,6 @@
 		7596A84F2877E6A9004DAE0E /* MTRCluster_internal.h in Headers */ = {isa = PBXBuildFile; fileRef = 7596A84E2877E6A9004DAE0E /* MTRCluster_internal.h */; };
 		7596A8512878709F004DAE0E /* MTRAsyncCallbackQueueTests.m in Sources */ = {isa = PBXBuildFile; fileRef = 7596A8502878709F004DAE0E /* MTRAsyncCallbackQueueTests.m */; };
 		7596A85528788557004DAE0E /* MTRClusters.mm in Sources */ = {isa = PBXBuildFile; fileRef = 7596A85228788557004DAE0E /* MTRClusters.mm */; };
-		7596A85628788557004DAE0E /* MTRClustersObjc_internal.h in Headers */ = {isa = PBXBuildFile; fileRef = 7596A85328788557004DAE0E /* MTRClustersObjc_internal.h */; };
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/darwin/Framework/Matter.xcodeproj/project.pbxproj:100]: Yep.

File: src/darwin/Framework/Matter.xcodeproj/xcshareddata/xcschemes/Matter Framework Tests.xcscheme (hunk 3 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/Matter.xcodeproj/xcshareddata/xcschemes/Matter Framework Tests.xcscheme:43]: I don't know....  But in either case, this is not needed and it was confusing me when testing things.  ;)

**Comment by bzbarsky-apple** [comment]
Fast tracking platform fix with owner approval.

**Review by andy31415 — APPROVED** [review]
