### PR TITLE
Fixing few issues with BindingManager and issues with how clients used BindingManager

### LINKED ISSUE #21606: Binding manager thinks it can connect to multiple things in parallel, but it can't
#### Problem
`BindingManager::EstablishConnection` does:
```
    mInitParams.mCASESessionManager->FindOrEstablishSession(nodeId, &mOnConnectedCallback, &mOnConnectionFailureCallback);
```

This will move the `mOnConnectedCallback` and `mOnConnectionFailureCallback` callbacks to the callback list of the new session establishment process, if there is no session already.

We call `BindingManager::NotifyBoundClusterChanged` in a loop over bindings in `BindingManager::NotifyBoundClusterChanged`.   This means we will only get notified for the last connection we started, not any of the other ones.

In many cases this might be getting covered up by connection attempts that complete synchronously, because we have pre-warmed CASE sessions...  But it can lead to messages not being sent to some bindings if we have no pre-warmed sessions around.

 #### Proposed Solution
Move the connection callbacks to somewhere that is per-connection-attempt.  Perhaps the pending notification?  Or some other data structure?

### PR DESCRIPTION
**Pull request by tehampson**
#### Problem
* Fixes #21606

#### Change overview
* Fixed
  * Issue where BindingManager::EstablishConnection only called once
  * Prevented used after free
  * Prevented buffer overrun

#### Testing
* CI passes
* Ran the following sequence:
  * Build all clusters app with command `scripts/examples/gn_build_example.sh examples/all-clusters-app/linux out/debug/standalone chip_config_network_layer_ble=false chip_build_libshell=true`
  * `rm -f rm -f kvs1 kvs2 kvs3`
  * `Terminal 1` run `./out/debug/standalone/chip-all-clusters-app --secured-device-port 72564 --KVS kvs1` (port was picked by mashing keys)
  * `Terminal 2` run `./out/debug/standalone/chip-tool pairing onnetwork 1 20202021`
  * `Terminal 3` run `./out/debug/standalone/chip-all-clusters-app --secured-device-port 72574 --KVS kvs2`
  * `Terminal 2` run `./out/debug/standalone/chip-tool pairing onnetwork 2 20202021`
  * `Terminal 4` run `./out/debug/standalone/chip-all-clusters-app --KVS kvs3`
  * `Terminal 2` run `./out/debug/standalone/chip-tool pairing onnetwork 3 20202021`
  * `Terminal 2` run `./out/debug/standalone/chip-tool binding write binding '[{"fabricIndex": 1, "node": 2, "endpoint": 1, "cluster": 6}, {"fabricIndex": 1, "node": 3, "endpoint": 1, "cluster": 6}]' 1 1`
  * Confirm on Terminal 3 and and Terminal 4 that come connection was established to node 1
  * Stop running the all clusters application on Terminal 3 and and Terminal 4
  * `Terminal 1` run `switch on`
    * Wait until you see that the messages were dropped after the max number of re-tries and that the CASESession to node 2 and 3 are now in a defunct state
  * `Terminal 3` run `./out/debug/standalone/chip-all-clusters-app --secured-device-port 72574 --KVS kvs2`
  * `Terminal 4` run `./out/debug/standalone/chip-all-clusters-app --KVS kvs3`
  * `Terminal 1` run `switch on`
  * Confirm on Terminal 3 and and Terminal 4 that come connection was established to node 1 and that it got the notification

### CODE REVIEW

**Review by mrjerryjohns — APPROVED** [review]

**Comment by mrjerryjohns** [comment]
Justification for 1.0 inclusion: Fixes a use-after-free bug with Bindings which can/should crash.

File: src/app/clusters/bindings/BindingManager.cpp [hunk 1]
```diff
@@ -188,9 +188,10 @@ CHIP_ERROR BindingManager::NotifyBoundClusterChanged(EndpointId endpoint, Cluste
         {
             if (iter->type == EMBER_UNICAST_BINDING)
             {
-                mPendingNotificationMap.AddPendingNotification(iter.GetIndex(), bindingContext);
+                error = mPendingNotificationMap.AddPendingNotification(iter.GetIndex(), bindingContext);
```
Comment (tehampson) [inline src/app/clusters/bindings/BindingManager.cpp:191]: Adding comment to prevent this PR from getting auto merged if someone else approves. There is something else that still needs to be fixed

**Review by woody-apple — APPROVED** [review]

File: src/app/clusters/bindings/BindingManager.h [hunk 2]
```diff
@@ -123,22 +121,46 @@ class BindingManager
     static BindingManager & GetInstance() { return sBindingManager; }
 
 private:
-    static BindingManager sBindingManager;
-
-    static void HandleDeviceConnected(void * context, Messaging::ExchangeManager & exchangeMgr, SessionHandle & sessionHandle);
-    void HandleDeviceConnected(Messaging::ExchangeManager & exchangeMgr, SessionHandle & sessionHandle);
+    class ConnectionCallback
```
Comment (tehampson) [inline src/app/clusters/bindings/BindingManager.h:124]: @mrjerryjohns  This is the section that got added after your initial approval, please take a look and resolve if you have no further comments and are okay with the PR going in

File: src/app/clusters/bindings/BindingManager.cpp [hunk 3]
```diff
@@ -101,31 +101,28 @@ CHIP_ERROR BindingManager::EstablishConnection(const ScopedNodeId & nodeId)
     VerifyOrReturnError(mInitParams.mCASESessionManager != nullptr, CHIP_ERROR_INCORRECT_STATE);
 
     mLastSessionEstablishmentError = CHIP_NO_ERROR;
-    mInitParams.mCASESessionManager->FindOrEstablishSession(nodeId, &mOnConnectedCallback, &mOnConnectionFailureCallback);
+    auto * connectionCallback      = Platform::New<ConnectionCallback>(this);
+    mInitParams.mCASESessionManager->FindOrEstablishSession(nodeId, connectionCallback->GetOnDeviceConnected(),
+                                                            connectionCallback->GetOnDeviceConnectionFailure());
     if (mLastSessionEstablishmentError == CHIP_ERROR_NO_MEMORY)
```
Comment (mrjerryjohns) [inline src/app/clusters/bindings/BindingManager.cpp:107]: Does this actually work the way it's intended to? I don't believe `CHIP_ERROR_NO_MEMORY` is actually emitted when there are no more entries in the `mPendingNotificationMap`....

I know it isn't germane to this PR, but if it's a bug, let's file a follow-up.

File: src/app/clusters/bindings/BindingManager.h [hunk 4]
```diff
@@ -123,22 +121,46 @@ class BindingManager
...
+    {
+    public:
+        ConnectionCallback(BindingManager * bindingManager) :
```
Comment (mrjerryjohns) [inline src/app/clusters/bindings/BindingManager.h:127]: This should never be null right? If so, let's make this a reference to make that clearer.

File: src/app/clusters/bindings/BindingManager.h [hunk 5]
```diff
@@ -123,22 +121,46 @@ class BindingManager
...
+            mOnConnectionFailureCallback(HandleDeviceConnectionFailure, this)
+        {}
+
+        Callback::Callback<OnDeviceConnected> * GetOnDeviceConnected() { return &mOnConnectedCallback; }
+        Callback::Callback<OnDeviceConnectionFailure> * GetOnDeviceConnectionFailure() { return &mOnConnectionFailureCallback; }
+
+    private:
+        static void HandleDeviceConnected(void * context, Messaging::ExchangeManager & exchangeMgr, SessionHandle & sessionHandle)
+        {
+            ConnectionCallback * connectionCallback = static_cast<ConnectionCallback *>(context);
```
Comment (mrjerryjohns) [inline src/app/clusters/bindings/BindingManager.h:138]: Suggestion: I tend to follow a practice of naming this `_this` so that it better conveys that we're essentially getting back a pointer to 'ourself'. That then makes the delete later clear as well, that we're actually deleting ourselves from within a static method in the same class...

File: src/app/clusters/bindings/BindingManager.h (hunk 2 above)
Comment (mrjerryjohns) [inline src/app/clusters/bindings/BindingManager.h:124]: Please add a description for this class and why it exists.

File: src/app/clusters/bindings/BindingManager.cpp [hunk 6]
```diff
@@ -149,17 +146,16 @@ void BindingManager::HandleDeviceConnected(Messaging::ExchangeManager & exchange
...
-}
-
 void BindingManager::HandleDeviceConnectionFailure(const ScopedNodeId & peerId, CHIP_ERROR error)
 {
     // Simply release the entry, the connection will be re-established as needed.
     ChipLogError(AppServer, "Failed to establish connection to node 0x" ChipLogFormatX64, ChipLogValueX64(peerId.GetNodeId()));
     mLastSessionEstablishmentError = error;
+    // We don't release the entry when connection fails, because inside
+    // BindingManager::EstablishConnection we may try again the connection. The logic in there
+    // doesn't actually make any sense with how mPendingNotificationMap and
```
Comment (mrjerryjohns) [inline src/app/clusters/bindings/BindingManager.cpp:156]: This next bit of text feels more like rationale we don't really need to be adding to the source file...

File: src/app/clusters/bindings/BindingManager.cpp (hunk 3 above)
Comment (tehampson) [reply src/app/clusters/bindings/BindingManager.cpp:107]: This error would not come from mPendingNotificationMap it would come from CASESessionManager. This is the issues I was trying to communicate in https://github.com/project-chip/connectedhomeip/pull/22133#discussion_r955432949

Regardless this is something incorrect that need to be fixed in a follow up PR and arguably after post 1.0
https://github.com/project-chip/connectedhomeip/issues/22173

**Review by mrjerryjohns — APPROVED** [review]

File: src/app/clusters/bindings/BindingManager.cpp [hunk 7]
```diff
@@ -101,31 +101,28 @@ CHIP_ERROR BindingManager::EstablishConnection(const ScopedNodeId & nodeId)
...
+                                                            connectionCallback->GetOnDeviceConnectionFailure());
     if (mLastSessionEstablishmentError == CHIP_ERROR_NO_MEMORY)
     {
         // Release the least recently used entry
-        // TODO: Some reference counting mechanism shall be added the CASESessionManager
-        // so that other session clients don't get accidentally closed.
         ScopedNodeId peerToRemove;
         if (mPendingNotificationMap.FindLRUConnectPeer(peerToRemove) == CHIP_NO_ERROR)
         {
             mPendingNotificationMap.RemoveAllEntriesForNode(peerToRemove);
```
Comment (bzbarsky-apple) [inline src/app/clusters/bindings/BindingManager.cpp:113]: How does this help, though?  If we got NO_MEMORY that means the SessionSetup pool is full, no?  How else can we end up here?  And messing with our notification map will not help with that, I don't think; we would have to cancel some session setups, which is what this code _used_ to do when it was working with OperationalDeviceProxy.

This part needs some thought as to how exactly it should work.  Is this what #22173 is about?

Comment (tehampson) [reply src/app/clusters/bindings/BindingManager.cpp:113]: You are correct.

When I was trying to get this in I was trying to changes as little as possible while fixing https://github.com/project-chip/connectedhomeip/issues/21606, this has been broken before this PR. Part of my thinking is that this should be thought out a little more and addressed in https://github.com/project-chip/connectedhomeip/issues/22173
