### PR TITLE
Fix corner cases of handling of Common Name fallback encoding

### LINKED ISSUE #28898: [BUG] Fallback encoding for PAI with Mpid: blank appears to pass device attestation
### Reproduction steps

Test vector struct_pai_vidpid_fallback_encoding_09 has a test vector as follows:
    "description": "PAI Test Vector: Fallback VID and PID encoding example from spec: invalid, since substring following Mpid: is not exactly 4 uppercase hexadecimal digits",
    "is_success_case": "true",
    
It's not clear why this is marked as a success case or why this passes device attestation.

Similar problem in struct_pai_vidpid_fallback_encoding_08

    "description": "PAI Test Vector: Fallback VID and PID encoding example from spec: invalid, since substring following Mvid: is not exactly 4 uppercase hexadecimal digits",
    "is_success_case": "false",

The vid versions of these test are (correct) failures.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

c3fb1247cc5fb8736e2ccb8ccdd386f87f26591c

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tcarmelveilleux**
Problem:
- Appearance of an empty `Mpid:`/`Mvid:` without value in a DAC/PAI/PAA DN was deemed OK by previous code, but this caused a critical ambiguity in PAIs which would possibly cause fall-back to non-PID-scoped PAI interpretation.
- Related to https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/7470
- Fixes #28898

This PR:

- Replaces the logic for fallback encoding conversion to take the first legitimate fully matching case for Mvid: and Mpid: and detect errors where either of these is present but without a following Mpid/Mvid.
- Updates unit tests to improve coverage and to properly mark as invalid some cases marked invalid in spec which where deemed valid by prior code by mistake

Testing done:

- Integration tests still pass (related to Commissioner DUT).
- Test vectors updated.
- New unit tests added.

### CODE REVIEW

File: src/crypto/CHIPCryptoPAL.cpp [hunk 1]
```diff
@@ -192,10 +194,111 @@ CHIP_ERROR ConvertIntegerRawToDerInternal(const ByteSpan & raw_integer, MutableB
...
+                if (hex_len == sizeof(hex_buf))
+                {
+                    if (!Encoding::UppercaseHexToUint16(&hex_buf[0], sizeof(hex_buf), out_hex_value))
+                    {
+                        // Invalid hex, we don't have a candidate.
+                        done = true;
+                        break;
+                    }
+
+                    state = State::kFoundHex;
```
Comment (andy31415) [inline src/crypto/CHIPCryptoPAL.cpp:287]: you do not need to actually need this state if you return right away

File: src/crypto/CHIPCryptoPAL.cpp [hunk 2]
```diff
@@ -192,10 +194,111 @@ CHIP_ERROR ConvertIntegerRawToDerInternal(const ByteSpan & raw_integer, MutableB
...
+ * @return CHIP_NO_ERROR on success, CHIP_ERROR_NOT_FOUND if not detected and
+ *         CHIP_ERROR_WRONG_CERT_DN if we saw the prefix but no valid hex string.
+ */
+CHIP_ERROR Find16BitUpperCaseHexAfterPrefix(const ByteSpan & buffer, const char * prefix, uint16_t & out_hex_value)
+{
+    chip::CharSpan prefix_span = chip::CharSpan::fromCharString(prefix);
 
-namespace chip {
-namespace Crypto {
+    enum State : int
```
Comment (andy31415) [inline src/crypto/CHIPCryptoPAL.cpp:211]: nit: int and exact values not actually need it (seems easier to just let the compiler liberty to pick whatever)

File: src/crypto/CHIPCryptoPAL.cpp [hunk 3]
```diff
@@ -192,10 +194,111 @@ CHIP_ERROR ConvertIntegerRawToDerInternal(const ByteSpan & raw_integer, MutableB
...
+        {
+            // We possibly can't match anymore since the prefix would not be there.
+            break;
+        }
+
+        Reader prefix_reader{ reinterpret_cast<const uint8_t *>(prefix_span.data()), prefix_span.size() };
+
+        char current_char = '\0';
+        bool done         = false;
+        while (!done)
```
Comment (andy31415) [inline src/crypto/CHIPCryptoPAL.cpp:240]: The indent of this method seems quite high, consider splitting it into at least 2 since the "try_match_at_given_index" seems to be reasonably indepen=dent from the loop of trying every index possible.

Since these are on spans, would it be worth it to not use readers for most operations? It seems to me like we could `memcmp` on prefixes without having the prefix reader and state machine logic. You seem to need one size + memcmp, then one size + memcpy logic to extract the hex chars.

**Review by andy31415 — APPROVED** [review]

File: src/crypto/CHIPCryptoPAL.cpp (hunk 3 above)
Comment (tcarmelveilleux) [reply src/crypto/CHIPCryptoPAL.cpp:240]: The goal here was to avoid any pointer arithmetic, which is what caused the original code to be harder to understand and which caused us to miss that it didn't correctly match in some cases.

File: src/crypto/CHIPCryptoPAL.cpp (hunk 1 above)
Comment (tcarmelveilleux) [reply src/crypto/CHIPCryptoPAL.cpp:287]: Sure. Added it to make clear what happened. Will remove.

File: src/crypto/CHIPCryptoPAL.cpp (hunk 3 above)
Comment (tcarmelveilleux) [reply src/crypto/CHIPCryptoPAL.cpp:240]: Refactored the whole thing PTAL.

File: src/crypto/CHIPCryptoPAL.cpp (hunk 2 above)
Comment (tcarmelveilleux) [reply src/crypto/CHIPCryptoPAL.cpp:211]: Fixed.

File: src/crypto/CHIPCryptoPAL.cpp [hunk 4]
```diff
@@ -159,10 +162,70 @@ CHIP_ERROR ConvertIntegerRawToDerInternal(const ByteSpan & raw_integer, MutableB
...
+        }
+        else
+        {
+            // Found prefix, skip to possible hex value.
+            found_prefix_at_least_once = true;
+            cursor += prefix_span.size();
+            remaining -= prefix_span.size();
+        }
+
+        if (remaining < HEX_ENCODED_LENGTH(sizeof(uint16_t)))
```
Comment (andy31415) [inline src/crypto/CHIPCryptoPAL.cpp:207]: we seem to use HEX_ENCODED_LENGTH and direct 4 ... should we use the same (e.g. use sizeof(hex_buf))? Why do we copy separately? Is const_cast not safe?

File: src/crypto/CHIPCryptoPAL.cpp [hunk 5]
```diff
@@ -159,10 +162,70 @@ CHIP_ERROR ConvertIntegerRawToDerInternal(const ByteSpan & raw_integer, MutableB
...
+CHIP_ERROR Find16BitUpperCaseHexAfterPrefix(const ByteSpan & buffer, const char * prefix, uint16_t & out_hex_value)
+{
+    chip::CharSpan prefix_span = chip::CharSpan::fromCharString(prefix);
 
-namespace chip {
-namespace Crypto {
+    bool found_prefix_at_least_once = false;
+
+    // Scan string from left to right, to find the desired full matching substring.
+    for (size_t start_idx = 0; start_idx < buffer.size(); start_idx++)
```
Comment (andy31415) [inline src/crypto/CHIPCryptoPAL.cpp:182]: We need prefix_span.size() + HEX_ENCODED_LENGTH(sizeof(uint16_t)), so I wonder if we could make the check and the loop in one and never worry about size checks after that again. Something like:

```cpp
const size_t data_len = prefix_span.size() + HEX_ENCODED_LENGTH(sizeof(uint16_t));

if (buffer.size() < data_len) 
{
  return CHIP_ERROR_NOT_FOUND; // insufficient space
}

for (const uint8_t cursor = buffer.data(); cursor < buffer.data() + buffer.size() - data_len; cursor++) 
{
   if (memcmp(cursor, prefix_span.data(), prefix_span.size()) != 0)
   {
      continue;
   }

   found_prefix_at_least_once = true;

   if (Encoding::UppercaseHexToUint16(
              reinterpret_cast<const char *>(cursor + prefix_span.size()),
              HEX_ENCODED_LENGTH(sizeof(uint16_t)),
              out_hex_value) != 0)
   {
       // Found first full valid match, return success, out_hex_value already updated.
       return CHIP_NO_ERROR;
   }
}
// ...
```

Comment (andy31415) [reply src/crypto/CHIPCryptoPAL.cpp:182]: I also wonder if we should cast the `buffer` to char* to begin with and maybe even use strstr to find prefix occurences.

Comment (andy31415) [reply src/crypto/CHIPCryptoPAL.cpp:182]: I guess buffer can contain null terminators in it so strstr does not work.

Comment (tcarmelveilleux) [reply src/crypto/CHIPCryptoPAL.cpp:182]: Exactly: no strstr allowed.

**Review by andy31415 — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]
