### PR TITLE
Fix Android ContentLauncher and MediaPlayback

### LINKED ISSUE #22710: [1.0] null pointer exception in Android ContentLauncher Search
### Reproduction steps

```bash
1. Run CONTENTLAUNCHER-10.3 against default android tv-app
2. Error results due to null list in search
```

### Bug prevalence

always

### GitHub hash of the SDK that was being used

master

### Platform

android

### Platform Version(s)

_No response_

### Type

Platform Issue

### Anything else?

_No response_

### LINKED ISSUE #22731: [1.0] Android media playback speed is not per spec
### Reproduction steps

```bash
1. Run MEDIAPLAYBACK-6.3 and MEDIAPLAYBACK-6.4 test cases
2. Tests fail due to java exceptions and incorrect playback speed calculations
```

### Bug prevalence

always

### GitHub hash of the SDK that was being used

master

### Platform

android

### Platform Version(s)

_No response_

### Type

Platform Issue

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chrisdecenzo**
#### Issue Being Resolved
* Fixes #22710
* Fixes #22731

#### Change overview
Check for null when iterating through search list arguments
Fix java exception in sampled-position
Fix playback speed calculation

### CODE REVIEW

**Review by nicelyjust — APPROVED** [review]

**Review by lazarkov — APPROVED** [review]

File: examples/tv-app/android/java/src/com/matter/tv/server/tvapp/ContentLaunchManagerStub.java [hunk 1]
```diff
@@ -58,15 +58,21 @@ public ContentLaunchResponse launchContent(
...
-      for (ContentLaunchSearchParameter parameter : entry.parameters) {
-        for (ContentLaunchSearchParameter query : search) {
-          if (query.type == parameter.type && query.data.equals(parameter.data)) {
-            Log.d(TAG, " TEST CASE found match=" + entry.name);
-            found = true;
+    if (entries != null) {
+      for (ContentLaunchEntry entry : entries) {
+        if (entry.parameters != null) {
+          for (ContentLaunchSearchParameter parameter : entry.parameters) {
+            if (search != null) {
```
[the remark this answers is not in the document]
Comment (chrisdecenzo) [reply examples/tv-app/android/java/src/com/matter/tv/server/tvapp/ContentLaunchManagerStub.java]: addressed

File: examples/tv-app/android/java/MediaPlaybackManager.cpp [hunk 2]
```diff
@@ -220,6 +220,38 @@ uint64_t MediaPlaybackManager::HandleMediaRequestGetAttribute(MediaPlaybackReque
...
+
+    ChipLogProgress(Zcl, "Received MediaPlaybackManager::HandleMediaRequestGetLongAttribute:%d", attribute);
+    VerifyOrExit(mMediaPlaybackManagerObject != nullptr, err = CHIP_ERROR_INCORRECT_STATE);
+    VerifyOrExit(mGetAttributeMethod != nullptr, err = CHIP_ERROR_INCORRECT_STATE);
+    VerifyOrExit(env != NULL, err = CHIP_JNI_ERROR_NO_ENV);
+
+    jAttributeValue = env->CallLongMethod(mMediaPlaybackManagerObject, mGetAttributeMethod, static_cast<jint>(attribute));
+    if (env->ExceptionCheck())
+    {
+        ChipLogError(AppServer, "Java exception in MediaPlaybackManager::GetAttribute");
```
Comment (andy31415) [inline examples/tv-app/android/java/MediaPlaybackManager.cpp:238]: should this not set some error in ERR if we get an exception?

It seems without that, in case of exception this returns 0 ... is that intended?

Some doccomment describing what this does and expectation may help

File: examples/tv-app/android/java/MediaPlaybackManager.cpp [hunk 3]
```diff
@@ -220,6 +220,38 @@ uint64_t MediaPlaybackManager::HandleMediaRequestGetAttribute(MediaPlaybackReque
     return ret;
 }
 
+long MediaPlaybackManager::HandleMediaRequestGetLongAttribute(MediaPlaybackRequestAttribute attribute)
```
Comment (andy31415) [inline examples/tv-app/android/java/MediaPlaybackManager.cpp:223]: A doc comment saying `returns 0 on error` may help.

**Review by andy31415 — APPROVED** [review]

File: examples/tv-app/android/java/MediaPlaybackManager.cpp (hunk 3 above)
Comment (chrisdecenzo) [reply examples/tv-app/android/java/MediaPlaybackManager.cpp:223]: I will add this in a subsequent PR, thanks
