### PR TITLE
Set up a network commissioning cluster in linux lock-app.

### LINKED ISSUE #17244: [SQA] Door lock test cases failed due to "Invalid CASE parameter"
Door lock cases were failed due to "Invalid CASE parameter" in few seconds after it has been paired.

During any "read" actions after it has been paired, Chip-Tool log thrown an error "The device does not support GetClock_RealTimeMS() API. This will eventually result in CASE session setup failures."

Following the above error, it has failed with "Invalid CASE parameter" for the further commands from Chip-tool.

Entire log has been attached. It contains few read attribute commands & the failure of the commands at the end of the log.

Error log file :
[DL timeout error log.txt](https://github.com/project-chip/connectedhomeip/files/8463979/DL.timeout.error.log.txt)

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
If we have thread or wifi, use them to set up a network commissioning
cluster.

#### Problem
Linux lock-app does not support any sort of commissioning other than onnetwork.

#### Change overview
Use Thread if compiled with that.  If not, use Wi-Fi if compiled with that.

#### Testing
Going to find someone who can test this on a Raspberry Pi.

### CODE REVIEW

File: examples/lock-app/linux/main.cpp [hunk 1]
```diff
@@ -17,8 +17,47 @@
...
+#include <app/clusters/network-commissioning/network-commissioning.h>
+#include <platform/Linux/NetworkCommissioningDriver.h>
 
-void ApplicationInit() {}
+using namespace chip;
+using namespace chip::app;
+
+namespace {
+#ifdef HAVE_NETWORK_COMMISSIONING_DRIVER
+#undef HAVE_NETWORK_COMMISSIONING_DRIVER
```
Comment (andy31415) [inline examples/lock-app/linux/main.cpp:28]: under what circumstances is this set and what is the difference from code before?

New code sets this define if THREAD or WPA is set, old code just had it from somewhere. Does it make a difference? A comment of why this is undef first may help, specifically static why it was set to start with and why we override.

Comment (andy31415) [reply examples/lock-app/linux/main.cpp:28]: Also do we need to use this `#define`? How about having a `void InitNetwork` that is with a right content including empty if none of thread/wpa are set and have ApplicationInit call it without an ifdef? Less split of ifdefs (and less ifdefs) make code easier to read.

Comment (bzbarsky-apple) [reply examples/lock-app/linux/main.cpp:28]: Old code never had it.  This is just guarding against someone outside this code altogether setting the define...

Would you prefer that we just #error if it's defined by someone outside this file?

Comment (bzbarsky-apple) [reply examples/lock-app/linux/main.cpp:28]: Yeah, I can do that.

Comment (andy31415) [reply examples/lock-app/linux/main.cpp:28]:
```cpp
// We support either thread or wi-fi commissioning, not both.  Prefer thread if
// both are available.

#if !(CHIP_DEVICE_LAYER_TARGET_LINUX && CHIP_DEVICE_CONFIG_ENABLE_THREAD) && !CHIP_DEVICE_CONFIG_ENABLE_WPA

void NetworkInit() {
    ChipLogWarning("No network provisioning support enabled");
}

#else // !(CHIP_DEVICE_LAYER_TARGET_LINUX && CHIP_DEVICE_CONFIG_ENABLE_THREAD) && !CHIP_DEVICE_CONFIG_ENABLE_WPA

#if (CHIP_DEVICE_LAYER_TARGET_LINUX && CHIP_DEVICE_CONFIG_ENABLE_THREAD)
    using NetworkCommissioningDriver = DeviceLayer::NetworkCommissioning::LinuxThreadDriver;
#elif CHIP_DEVICE_CONFIG_ENABLE_WPA
    using NetworkCommissioningDriver = DeviceLayer::NetworkCommissioning::LinuxWiFiDriver;
#else
    #error "No suitable network driver found"
#endif

NetworkCommissioningDriver sNetworkCommissioningDriver;
Clusters::NetworkCommissioning::Instance sNetworkCommissioningInstance(0, &sNetworkCommissioningDriver);

void NetworkInit() {
    sNetworkCommissioningInstance.Init();
}

#endif // !(CHIP_DEVICE_LAYER_TARGET_LINUX && CHIP_DEVICE_CONFIG_ENABLE_THREAD) && !CHIP_DEVICE_CONFIG_ENABLE_WPA

} // anonymous namespace

void ApplicationInit()
{
    NetworkInit();
}
```

maybe something like this. Ideally we would have a NULLDriver for networking but implementing that is probably non-trivial.

Comment (andy31415) [reply examples/lock-app/linux/main.cpp:28]:
```cpp
namespace {

// We support either thread or wi-fi commissioning, not both.  Prefer thread if
// both are available.
#if (CHIP_DEVICE_LAYER_TARGET_LINUX && CHIP_DEVICE_CONFIG_ENABLE_THREAD)
    using NetworkCommissioningDriver = DeviceLayer::NetworkCommissioning::LinuxThreadDriver;
#elif CHIP_DEVICE_CONFIG_ENABLE_WPA
    using NetworkCommissioningDriver = DeviceLayer::NetworkCommissioning::LinuxWiFiDriver;
#else
    using NetworkCommissioningDriver = app::Clusters::NetworkCommissioning::NullNetworkDriver;
#endif

NetworkCommissioningDriver sNetworkCommissioningDriver;
Clusters::NetworkCommissioning::Instance sNetworkCommissioningInstance(0, &sNetworkCommissioningDriver);

} // anonymous namespace

void ApplicationInit()
{
    sNetworkCommissioningInstance.Init();
}

```

assuming we always want some real-looking network driver. Otherwise the more complex code above or some variation like that.

**Review by andy31415 — APPROVED** [review]

**Review by lazarkov — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]
