### PR TITLE
Fix in-place save for DefaultSessionResumptionStorage

### LINKED ISSUE #23044: [BUG] DefaultSessionResumptionStorage::Save does not reuse index locations to save data for the same node
### Reproduction steps

DefaultSessionResumptionStorage::Save does not reuse index locations to save data for the same node.  This has a few consequences:

1. Each subsequent session resumption write for a given node will unnecessarily evict entries for other nodes.
2. Backing storage in the state table won't ever have more than one entry for the given node.  This leaves it out of sync with the index.
3. Most seriously, entries in the link table are leaked at each occurrence.

The leak is specifically here:

https://github.com/project-chip/connectedhomeip/blob/7301ecfeb99f4473502ecb9cee75d68d83daa286/src/protocols/secure_channel/DefaultSessionResumptionStorage.cpp#L62

Note that the fact Delete always returns CHIP_NO_ERROR keeps eviction working.  But the leak remains and is serious.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

fa8db560907713c555b06120658034e8c6ccea1a

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by msandstedt**
Nodes that already exist in the DefaultSessionResumptionStorage index are consuming additional entries in the index on save, and aren't cleaned from the link and state tables first.  This has the following consequences:

1. If session resumption storage is full, this causes unnecessary eviction of records for other nodes.
2. This pulls the index out of sync from the backing state table because duplicate entries in the index for a given node only map to a single node-id-keyed entry in the state table.
3. An entry in the link table is leaked on each occurrence, as the resumption-id-keyed link entry will be orphaned once its associated state table entry is overwritten.

This commit fixes the problem by first deleting the link table entry before saving a record for a node that already exists in the table. Save is also simplified in this case by not rewriting the index, as the node is already in the index.

Fixes #23044

### CODE REVIEW

File: src/protocols/secure_channel/DefaultSessionResumptionStorage.cpp [hunk 1]
```diff
@@ -52,6 +52,35 @@ CHIP_ERROR DefaultSessionResumptionStorage::Save(const ScopedNodeId & node, Cons
...
+            // best effort.  Leaks will occur if an entry in the link table does
+            // not have a corresponding entry in the state table.
+            if (err == CHIP_NO_ERROR)
+            {
+                err = DeleteLink(oldResumptionId);
+            }
+            if (err != CHIP_NO_ERROR)
+            {
+                ChipLogError(SecureChannel,
+                             "Unable to delete session resumption link for node " ChipLogFormatX64 ": %" CHIP_ERROR_FORMAT,
```
Comment (smides-nest) [inline src/protocols/secure_channel/DefaultSessionResumptionStorage.cpp:75]: This will log if `LoadState()` returns an error, as well.

Comment (msandstedt) [reply src/protocols/secure_channel/DefaultSessionResumptionStorage.cpp:75]: That is actually the intent.  We need to load from the state table to retrieve the resumption ID in order to remove the entry from the resumption-id-keyed link table.  The implication of being unable to load state is that the resumption-id-keyed entry in the link table won't be removed (this is the storage leak that was happening 100% of the time before this PR).

With the fix, we expect the leak to occur rarely or never, but if it does (or appears to), we want to log it.

Comment (andy31415) [reply src/protocols/secure_channel/DefaultSessionResumptionStorage.cpp:75]: It would be useful to know which of the two calls failed. Right now we get a similar log for both LoadState failing and DeleteLink failing. If we have 'line numbers enabled' (like linux) then we are ok, but on small devices we may just get an error code and we will not know if line 64 or line 70 failed.

Could we disambiguate that?

Comment (msandstedt) [reply src/protocols/secure_channel/DefaultSessionResumptionStorage.cpp:75]: Ah, right.  I am used to the verbose logging with line numbers being enabled.

Will fix.

Comment (msandstedt) [reply src/protocols/secure_channel/DefaultSessionResumptionStorage.cpp]: Done.

File: src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp [hunk 2]
```diff
@@ -109,6 +189,69 @@ void TestSave(nlTestSuite * inSuite, void * inContext)
...
+    for (auto & vector : vectors)
+    {
+        chip::ScopedNodeId outNode;
+        chip::SessionResumptionStorage::ResumptionIdStorage outResumptionId;
+        chip::Crypto::P256ECDHDerivedSecret outSharedSecret;
+        chip::CATValues outCats;
+
+        // Verify all records for all nodes are gone.
+        NL_TEST_ASSERT(inSuite,
+                       sessionStorage.FindByScopedNodeId(vector.node, outResumptionId, outSharedSecret, outCats) != CHIP_NO_ERROR);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp:249]: WIth the TestPersistentStorageDelegate, we also have `GetNumKeys()` and `DumpKeys()` which can be used to do "before"/"after" delta of numbers of key stored, or dump to look with your eyes. Not saying you need to add this here, but we use it in FabricTable tests to make sure our storage backends don't leak stuff after removals.

**Review by tcarmelveilleux — APPROVED** [review]

File: src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp (hunk 2 above)
Comment (msandstedt) [reply src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp:249]: Yes, I am adding code to check for this right now actually.  I'm just using the approach of using the key literals since these are well known in this case.  But that should be fine here.

Will be up shortly.

Comment (msandstedt) [reply src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp:249]: Done.

**Review by andy31415 — APPROVED** [review]

**Review by wbschiller — APPROVED** [review]
Nice catch!

File: src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp [hunk 3]
```diff
@@ -15,15 +15,17 @@
...
 #include <lib/support/UnitTestRegistration.h>
 #include <nlunit-test.h>
 
-#include <lib/support/TestPersistentStorageDelegate.h>
-
 // DefaultSessionResumptionStorage is a partial implementation.
 // Use SimpleSessionResumptionStorage, which extends it, to test.
 #include <protocols/secure_channel/SimpleSessionResumptionStorage.h>
 
+#define ARRAY_SIZE(_array) ((sizeof(_array) / sizeof(_array[0])))
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp:27]: We already have an ArraySize macro for this, fwiw, in `src/lib/support/CodeUtils.`

File: src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp [hunk 4]
```diff
@@ -81,7 +83,124 @@ void TestSave(nlTestSuite * inSuite, void * inContext)
...
+        // Verify retrieval by node.
+        NL_TEST_ASSERT(inSuite,
+                       sessionStorage.FindByScopedNodeId(vector.node, outResumptionId, outSharedSecret, outCats) == CHIP_NO_ERROR);
+        NL_TEST_ASSERT(inSuite, memcmp(vector.resumptionId.data(), outResumptionId.data(), vector.resumptionId.size()) == 0);
+        NL_TEST_ASSERT(inSuite, memcmp(vector.sharedSecret.ConstBytes(), outSharedSecret, vector.sharedSecret.Length()) == 0);
+        NL_TEST_ASSERT(inSuite, vector.cats.values[0] == outCats.values[0]);
+        NL_TEST_ASSERT(inSuite, vector.cats.values[1] == outCats.values[1]);
+        NL_TEST_ASSERT(inSuite, vector.cats.values[2] == outCats.values[2]);
+
+        // Validate retreiveal by resumption ID.
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp:102]: "retrieval"

File: src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp [hunk 5]
```diff
@@ -81,7 +83,124 @@ void TestSave(nlTestSuite * inSuite, void * inContext)
...
+    sessionStorage.Init(&storage);
+    struct
+    {
+        chip::SessionResumptionStorage::ResumptionIdStorage resumptionId;
+        chip::Crypto::P256ECDHDerivedSecret sharedSecret;
+        chip::ScopedNodeId node;
+        chip::CATValues cats;
+    } vectors[CHIP_CONFIG_CASE_SESSION_RESUME_CACHE_SIZE + 10];
+
+    // Construct only a few unique node identities to simiulate talking to a
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp:126]: "simulate"

File: src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp [hunk 6]
```diff
@@ -81,7 +83,124 @@ void TestSave(nlTestSuite * inSuite, void * inContext)
...
+    for (size_t i = 0; i < ARRAY_SIZE(nodes); ++i)
+    {
+        do
+        {
+            nodes[i] = chip::ScopedNodeId(static_cast<chip::NodeId>(rand()), static_cast<chip::FabricIndex>(i + 1));
+        } while (!nodes[i].IsOperational());
+    }
+
+    // Populate test vectors.
+    for (size_t i = 0; i < ARRAY_SIZE(vectors); ++i)
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp:140]: A lot of these loops that just use `i` to index into `vectors` or `nodes` might have been clearer as ranged for loops....

Comment (msandstedt) [reply src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp:140]: I think in all cases where there are indexed loops, the index variable is being used to populate the test vectors with values that are guaranteed not to collide.  I tried to move to ranged for loops wherever possible.

File: src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp (hunk 3 above)
Comment (msandstedt) [reply src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp:27]: Was not aware.  Can do a fast-follow cleanup PR.

Thank you.

File: src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp (hunk 6 above)
Comment (bzbarsky-apple) [reply src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp:140]: Ah, I missed some `i` on the rhs of things, indeed.

File: src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp (hunk 3 above)
Comment (msandstedt) [reply src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp:27]: PR here: https://github.com/project-chip/connectedhomeip/pull/23110

File: src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp (hunk 5 above)
Comment (msandstedt) [reply src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp:126]: PR here: https://github.com/project-chip/connectedhomeip/pull/23110

File: src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp (hunk 4 above)
Comment (msandstedt) [reply src/protocols/secure_channel/tests/TestDefaultSessionResumptionStorage.cpp:102]: PR here: https://github.com/project-chip/connectedhomeip/pull/23110.
