### PR TITLE
[LevelControl] Level Control Recall null level behavior

### LINKED ISSUE #29033: [BUG] Address review issues on PR 28836
### Reproduction steps

See https://github.com/project-chip/connectedhomeip/pull/28836#pullrequestreview-1607869620 @lpbeliveau-silabs 

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

1ed389725756a7a5e6ce4c2e79e6458c7d89d2f6

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### LINKED ISSUE #29185: [1.2] Recall scene with null level control not aligned with spec
### Reproduction steps

The spec behaviour of how to apply a "Null" level to the level control cluster is undefined.

An issue has been opened here: https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/7536

Our current implementation will result in an error being returned to the user when recalling the scene.

We need to implement this behaviour once it is defined.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

5867ac5a69a2bc93ca1e38b93ab4098d878b1420

### Platform

core

### Platform Version(s)

_No response_

### Type

Spec Compliance Issue

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by lpbeliveau-silabs**
Applies the spec changes from: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/7645
So that the level control cluster will ignore a null value for the current level attribute coming from a recall scene and the status of the command returns success.

Note: we should merge this after the spec PR gets merged.

Fixes: https://github.com/project-chip/connectedhomeip/issues/29033
Fixes: https://github.com/project-chip/connectedhomeip/issues/29185

### CODE REVIEW

File: src/app/clusters/level-control/level-control.cpp [hunk 1]
```diff
@@ -238,18 +238,13 @@ class DefaultLevelControlSceneHandler : public scenes::DefaultSceneHandlerImpl
...
 
-        status = moveToLevelHandler(endpoint, command, level, app::DataModel::MakeNullable(static_cast<uint16_t>(timeMs / 100)),
-                                    chip::Optional<BitMask<OptionsBitmap>>(), chip::Optional<BitMask<OptionsBitmap>>(),
-                                    INVALID_STORED_LEVEL);
-
-        if (status != Status::Success)
-        {
-            return CHIP_ERROR_READ_FAILED;
-        }
+        moveToLevelHandler(endpoint, command, level, app::DataModel::MakeNullable(static_cast<uint16_t>(timeMs / 100)),
```
Comment (bzbarsky-apple) [inline src/app/clusters/level-control/level-control.cpp:245]: But "level" here can't be a null value, right?  It's actually 255 if the value was null?

It would be better if we explicitly didn't try to move to level if it's null instead of relying on moveToLevelHandler doing some sort of check on values that it's never supposed to see.

Comment (LP727) [reply src/app/clusters/level-control/level-control.cpp:245]: Correct, null would be 255, which would end up out of bounds for the moveToLevelHandler.  I'll explicitely ignore it instead.

Comment (lpbeliveau-silabs) [reply src/app/clusters/level-control/level-control.cpp]: Added check for null value.

**Review by mkardous-silabs — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
