### PR TITLE
[Java] Implement the trust store delegate API for customized device attestation

### LINKED ISSUE #24297: [Platform] Implement a DeviceAttestationVerifier in Java to allow user to overwrite the DefaultDACVerifier
### Reproduction steps

Per @tcarmelveilleux
 
See `AndroidDeviceControllerWrapper::AllocateNew` in src/controller/java/AndroidDeviceControllerWrapper.cpp:
```
    // Initialize device attestation verifier
    // TODO: Replace testingRootStore with a AttestationTrustStore that has the necessary official PAA roots available
    const chip::Credentials::AttestationTrustStore * testingRootStore = chip::Credentials::GetTestAttestationTrustStore();
    SetDeviceAttestationVerifier(GetDefaultDACVerifier(testingRootStore));
```

The Device Attestation Verifier is what could be bridged to Java.

Overall, the flow could be something like:

image

```
@startuml

participant "Client" as client 
participant "AndroidChipDeviceController" as wrapper
' from AndroidDeviceControllerWrapper
participant "C++ ChipDeviceController" as DevCtrl
' owned by ChipDeviceController
participant "DeviceCommissioner" as Commissioner
' owned by ChipDeviceController
participant "AutoCommissioner" as AutoCommissioner
' Make your custom one
participant "CustomDeviceAttestationVerifier" as Verifier
participant "DCL Client" as DCL

client -> wrapper: <<new ChipDeviceController>>
client <- wrapper: devCtrl
' The following is new
client -> wrapper: SetDeviceAttestationVerifier\n(CustomDeviceAttestationVerifier)
activate wrapper
client -> wrapper: CommissionDevice(...)
wrapper -> DevCtrl: Commission(...)
DevCtrl -> Commissioner: Commission(...)
Commissioner -> AutoCommissioner: StartCommissioning(...)

... some operations pass ...

AutoCommissioner -> Verifier: VerifyAttestationInformation(..., Callback)
Verifier -> DCL: FetchPAA(PAI.authority, PaaFetchedCallback)
Verifier <-- DCL: PaaFetchedCallback(PAA Cert)
Verifier -> Verifier: Bridge to DefaultDeviceAttestationVerifier impl
Note left of Verifier: An ephemeral truststore can be provided\nto DefaultDeviceAttestationVerifier\nthat now has PAA
Note left of Verifier: DefaultDeviceAttestationVerifier does not\nneed to be used, could be custom Java version
AutoCommissioner <-- Verifier: Callback(result)

... more operations pass ...
Commissioner <-- AutoCommissioner: CommissioningStepFinished(kAttestationVerification)
deactivate wrapper

@enduml
```

The general concept:

1. It should be possible to implement a DeviceAttestationVerifier in Java fully
2. That DeviceAttestationVerifier would then NOT need a truststore directly, unless it called into the C++ DefaultDeviceAttestationVerifier with JNI bridging. This should be optional
3. If we abstract at DeviceAttestationVerifier call, then there is already async implementation from DeviceCommissioner to AutoCommissioner to DeviceAttestationVerifier. You can then take a while to obtain PAA from DCL if needed
4. We have to make sure not to break existing public API, only make it better. Right now, most Java clients just use the default Device Attestation Verifier and likely know what PAAs they want to trust (e.g. their own). If you are a fully general commissioner, you always need more customization anyway. That is why I was suggesting *also bridging* the attestation trust store.

Regarding the CD trust store, there is already a set of Well-known keys. The CdWellKnownKeysTrustStore used by default should be good enough for a while.

Overall, I agree that these Java APIs are cumbersome. However, unless someone is willing to help rewrite them to "flow-through" with a frameworked design that works *for everyone*, we have to keep going incrementally.

### Platform

android

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yufengwangca**
This is the continuation work of https://github.com/project-chip/connectedhomeip/pull/24381

Currently, our Java pairing API always use the examples PAAs list to verify the device, this PR implement a Attestation TrustStore Delegate API which allow the vendor to replace the default trust store with their own PAA list

Fix: https://github.com/project-chip/connectedhomeip/issues/24297

Testing
Used Android chip-tool which implemented this delegate and verified the existing path still works
The CI test will be added later after we complete the kotlin conversion in java-matter-controller

### CODE REVIEW

File: examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/attestation/ExampleAttestationTrustStoreDelegate.kt [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+import chip.devicecontroller.ChipDeviceController
+import java.util.*
+
+class ExampleAttestationTrustStoreDelegate(val chipDeviceController: ChipDeviceController) :
+  AttestationTrustStoreDelegate {
+
+  private val paaCerts = arrayListOf(TEST_PAA_FFF1_Cert, TEST_PAA_NOVID_CERT)
+
+  override fun getProductAttestationAuthorityCert(skid: ByteArray): ByteArray? {
+    for (paaCert in paaCerts) {
```
Comment (g-coppock) [inline examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/attestation/ExampleAttestationTrustStoreDelegate.kt:14]: Suggestion: Use mapping functions here:

```
return paaCerts
  .map { Base64.decode(it, Base64.DEFAULT) }
  .map(chipDeviceController::extractSkidFromPaaCert)
  .firstOrNull { it == skid }
```

**Review by g-coppock — APPROVED** [review]

File: examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/attestation/ExampleAttestationTrustStoreDelegate.kt (hunk 1 above)
Comment (yufengwangca) [reply examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/attestation/ExampleAttestationTrustStoreDelegate.kt:14]: Still try to understand this syntax, it looks to me this return skidFromPaaCert instead of paaCertBytes, no?

Comment (g-coppock) [reply examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/attestation/ExampleAttestationTrustStoreDelegate.kt:14]: You're right, I missed that, instead it would be:

```
return paaCerts
  .map { Base64.decode(it, Base64.DEFAULT) }
  .firstOrNull { cert -> chipDeviceController.extractSkidFromPaaCert(cert) == skid }
```

**Review by andy31415 — APPROVED** [review]
