### PR TITLE
Fix some buffer handling issues in BtpEngine.

### LINKED ISSUE #3922: BLEEndPoint::Receive should probably check that it has data
#### Problem
`BLEEndPoint::Receive` does:
```
    if (mBtpEngine.IsCommandPacket(data))
```
which will examine the first byte of `data`.  But what if `data` has no payload bytes at all?  Seems like we'd be reading random memory.

 #### Proposed Solution
Check that we have a byte to read before reading it.

It looks like this code came in like this from Weave....  @pan-apple @turon

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Two problems:

1. BtpEngine::HandleCharacteristicReceived null-checked the incoming
   buffer _after_ it had already dereferenced it, which is pretty
   pointless.

2. BtpEngine::IsCommandPacket read one byte from the buffer even if
   the buffer was zero-length.

Fixes https://github.com/project-chip/connectedhomeip/issues/3922

#### Problem
See above.

#### Change overview
Make sure we check for null before dereferencing and don't directly poke at Start() without checking length.

#### Testing
Not sure how to exercise the error cases here in our CI.

### CODE REVIEW

File: src/ble/BtpEngine.h [hunk 1]
```diff
@@ -130,10 +130,7 @@ class BtpEngine
     inline SequenceNumber_t SetRxPacketSeq(SequenceNumber_t seq) { return (mRxPacketSeq = seq); }
     inline SequenceNumber_t TxPacketSeq() { return mTxPacketSeq; }
     inline SequenceNumber_t RxPacketSeq() { return mRxPacketSeq; }
-    inline bool IsCommandPacket(const PacketBufferHandle & p)
-    {
-        return BitFlags<HeaderFlags>(*(p->Start())).Has(HeaderFlags::kCommandMessage);
-    }
+    bool IsCommandPacket(const PacketBufferHandle & p);
```
Comment (andy31415) [inline src/ble/BtpEngine.h:133]: can this be static or at least const?

Comment (bzbarsky-apple) [reply src/ble/BtpEngine.h]: Done.

**Review by jelderton — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
