### PR TITLE
Fix attribute reads into a large buffer to not read random memory.

### LINKED ISSUE #4371: Investigate address and memory sanitize errors when building all_clusters_app for linux
#### Problem
 
 Memory sanitize complains about glib, address sanitize gives a potential bug:
 
 ```
==2151032==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55a9bb9e15d6 at pc 0x55a9bae1235f bp 0x7ffcf4e91c10 sp 0x7ffcf4e913d8
READ of size 8 at 0x55a9bb9e15d6 thread T0
    #0 0x55a9bae1235e in __asan_memmove (/usr/local/google/home/andreilitvin/devel/connectedhomeip/examples/all-clusters-app/linux/out/all-clusters-server+0x11135e)
    #1 0x55a9bae6e47f in typeSensitiveMemCopy(unsigned char*, unsigned char*, EmberAfAttributeMetadata*, bool, unsigned short) /usr/local/google/home/andreilitvin/devel/connectedhomeip/examples/all-clusters-app/linux/out/../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:394:13
    #2 0x55a9bae6d785 in emAfReadOrWriteAttribute(EmberAfAttributeSearchRecord*, EmberAfAttributeMetadata**, unsigned char*, unsigned short, bool) /usr/local/google/home/andreilitvin/devel/connectedhomeip/examples/all-clusters-app/linux/out/../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:563:47
    #3 0x55a9bae71517 in emAfReadAttribute(unsigned char, unsigned short, unsigned short, unsigned char, unsigned short, unsigned char*, unsigned short, unsigned char*) /usr/local/google/home/andreilitvin/devel/connectedhomeip/examples/all-clusters-app/linux/out/../third_party/connectedhomeip/src/app/util/attribute-table.cpp:645:31
    #4 0x55a9bae60c71 in emberAfPluginReportingTickEventHandler() /usr/local/google/home/andreilitvin/devel/connectedhomeip/examples/all-clusters-app/linux/out/../third_party/connectedhomeip/src/app/reporting/reporting.cpp:220:18
    #5 0x55a9bae68c9c in EventControlHandler(chip::System::Layer*, void*, int) /usr/local/google/home/andreilitvin/devel/connectedhomeip/examples/all-clusters-app/linux/out/../third_party/connectedhomeip/src/app/util/af-event.cpp:109:17
    #6 0x55a9baeb8377 in chip::System::Timer::HandleComplete() /usr/local/google/home/andreilitvin/devel/connectedhomeip/examples/all-clusters-app/linux/out/../third_party/connectedhomeip/src/system/SystemTimer.cpp:274:9
    #7 0x55a9baeb45f0 in chip::System::Layer::HandleSelectResult(int, fd_set*, fd_set*, fd_set*) /usr/local/google/home/andreilitvin/devel/connectedhomeip/examples/all-clusters-app/linux/out/../third_party/connectedhomeip/src/system/SystemLayer.cpp:698:21
    #8 0x55a9bae97584 in chip::DeviceLayer::Internal::GenericPlatformManagerImpl_POSIX<chip::DeviceLayer::PlatformManagerImpl>::SysProcess() /usr/local/google/home/andreilitvin/devel/connectedhomeip/examples/all-clusters-app/linux/out/../third_party/connectedhomeip/src/include/platform/internal/GenericPlatformManagerImpl_POSIX.cpp:170:21
    #9 0x55a9bae96f65 in chip::DeviceLayer::Internal::GenericPlatformManagerImpl_POSIX<chip::DeviceLayer::PlatformManagerImpl>::_RunEventLoop() /usr/local/google/home/andreilitvin/devel/connectedhomeip/examples/all-clusters-app/linux/out/../third_party/connectedhomeip/src/include/platform/internal/GenericPlatformManagerImpl_POSIX.cpp:194:9
    #10 0x55a9bae3eb57 in chip::DeviceLayer::PlatformManager::RunEventLoop() /usr/local/google/home/andreilitvin/devel/connectedhomeip/examples/all-clusters-app/linux/out/../third_party/connectedhomeip/src/include/platform/PlatformManager.h:204:37
    #11 0x55a9bae3ea9e in main /usr/local/google/home/andreilitvin/devel/connectedhomeip/examples/all-clusters-app/linux/out/../main.cpp:66:38
    #12 0x7f73b6bdad09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #13 0x55a9bad99149 in _start (/usr/local/google/home/andreilitvin/devel/connectedhomeip/examples/all-clusters-app/linux/out/all-clusters-server+0x98149)

0x55a9bb9e15d6 is located 42 bytes to the left of global variable 'singletonAttributeData' defined in '../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:67:9' (0x55a9bb9e1600) of size 6
0x55a9bb9e15d6 is located 0 bytes to the right of global variable 'attributeData' defined in '../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:60:9' (0x55a9bb9e1540) of size 150
SUMMARY: AddressSanitizer: global-buffer-overflow (/usr/local/google/home/andreilitvin/devel/connectedhomeip/examples/all-clusters-app/linux/out/all-clusters-server+0x11135e) in __asan_memmove
Shadow bytes around the buggy address:
  0x0ab5b7734260: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9
  0x0ab5b7734270: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9
  0x0ab5b7734280: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ab5b7734290: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 00 00 00 00
  0x0ab5b77342a0: 00 00 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
=>0x0ab5b77342b0: 00 00 00 00 00 00 00 00 00 00[06]f9 f9 f9 f9 f9
  0x0ab5b77342c0: 06 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
  0x0ab5b77342d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ab5b77342e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f9 f9
  0x0ab5b77342f0: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 02 f9 f9 f9
  0x0ab5b7734300: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9
  ```

 #### Proposed Solution
Determine if this is a real out of bounds and fix.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
When reading an attribute value into a large buffer, we would read the
number of bytes that can fit in the buffer, not the number of bytes
the attribute value actually takes up.  This would cause us to read
whatever memory came after the attribute value.

Also fixes some issues in typeSensitiveMemCopy when trying to
read a string-valued attribute into a buffer that's not even big
enough to fit the length value of the string.

Fixes https://github.com/project-chip/connectedhomeip/issues/4371

 #### Problem
We end up reading out-of-bounds memory when doing attribute reporting.

 #### Summary of Changes
Fix `typeSensitiveMemCopy` to not read memory it should not.

### CODE REVIEW

File: src/app/util/attribute-storage.cpp [hunk 1]
```diff
@@ -365,33 +365,46 @@ static uint8_t * singletonAttributeLocation(EmberAfAttributeMetadata * am)
...
+// See documentation for emAfReadOrWriteAttribute for the semantics of
+// readLength when reading and writing.
 static EmberAfStatus typeSensitiveMemCopy(uint8_t * dest, uint8_t * src, EmberAfAttributeMetadata * am, bool write,
                                           uint16_t readLength)
 {
     EmberAfAttributeType attributeType = am->attributeType;
-    uint16_t size                      = (readLength == 0) ? am->size : readLength;
+    // readLength == 0 for a read indicates that we should just trust that the
+    // caller has enough space for an attribute...
+    bool ignoreReadLength = write || (readLength == 0);
```
Comment (andy31415) [inline src/app/util/attribute-storage.cpp:376]: why is the caller buffer size ignored when write is set?

Generally I have complains about this method to start with: a buffer length that seems to be only relevant on read (called readLengt) but method used on both read and write and a direction parameter when the caller could just have flipped src and destination.

Could we fix up this method and make it somehow easier to use?

Comment (bzbarsky-apple) [reply src/app/util/attribute-storage.cpp:376]: > why is the caller buffer size ignored when write is set?

Apart from that being the documented behavior of `emAfReadOrWriteAttribute` and all callers who set `write` passing 0 for the size?  I'm afraid I don't know why the setup is the way it is; that's a question for @selissia or @tecimovic.

> Could we fix up this method and make it somehow easier to use?

Yes, we could, and I agree we should.  We'd need to audit all consumers to see what they are doing with `readLength`; the comments suggest that there are legacy consumers that pass 0 for reads as well....

I'm happy to do that, but it might be a few days before I can pull enough time off of spec stuff to do it.  I'm happy to land this in the meantime to unblock your ASan changes and do the larger semantic-changing refactoring in a followup, or expand the scope of this PR, as long as you're OK with the corresponding lag.  Please let me know.

Comment (andy31415) [reply src/app/util/attribute-storage.cpp:376]: created #4394 to track improvement in buffer handling within this code.

Is this generated code? if so, how would one go about on changing the code and updating?

**Review by andy31415 — APPROVED** [review]

**Review by rwalker-apple — APPROVED** [review]

**Comment by rwalker-apple** [comment]
@jelderton @saurabhst @hawk248 @BroderickCarlin ?

**Review by saurabhst — APPROVED** [review]

File: src/app/util/attribute-storage.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/util/attribute-storage.cpp:376]: Just to close the loop on this: this is not generated code.
