### PR TITLE
[linux] Fix seg fault error if we do network provisioning twice.

### LINKED ISSUE #4269: The linux device crashed if we do network provisioning twice
#### Problem
The linux device crashed if we do network provisioning twice:
chip::DeviceLayer::ConnectivityMgrImpl().StartWiFiManagement();
(wait)
chip::DeviceLayer::ConnectivityManagerImpl::ProvisionWiFiNetwork(ssid, passwd);
(wait)
chip::DeviceLayer::ConnectivityManagerImpl::ProvisionWiFiNetwork(ssid, passwd);

According to the backtrace, seems we have some kind of double free issue:
```
#0 0x0000fffff7a3000c in g_type_check_instance_is_fundamentally_a () at /lib/aarch64-linux-gnu/libgobject-2.0.so.0
#1 0x0000fffff7a139b8 in g_object_unref () at /lib/aarch64-linux-gnu/libgobject-2.0.so.0
#2 0x0000aaaaaaae46a4 in chip::DeviceLayer::ConnectivityManagerImpl::ProvisionWiFiNetwork(char const*, char const*)
(this=0xaaaaaab919b8 <chip::DeviceLayer::ConnectivityManagerImpl::sInstance>, ssid=0xffffffffe7d0 "Nest-T", key=0xffffffffe7f8 "Nesttesting")
at ../third_party/connectedhomeip/src/platform/Linux/ConnectivityManagerImpl.cpp:849

 #### Proposed Solution
<suggested fix, suggested enhancement>

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
The linux device crashed if we do network provisioning twice:
chip::DeviceLayer::ConnectivityMgrImpl().StartWiFiManagement();
(wait)
chip::DeviceLayer::ConnectivityManagerImpl::ProvisionWiFiNetwork(ssid, passwd);
(wait)
chip::DeviceLayer::ConnectivityManagerImpl::ProvisionWiFiNetwork(ssid, passwd);

According to the backtrace, seems we have some kind of double free issue:

#0 0x0000fffff7a3000c in g_type_check_instance_is_fundamentally_a () at /lib/aarch64-linux-gnu/libgobject-2.0.so.0
#1 0x0000fffff7a139b8 in g_object_unref () at /lib/aarch64-linux-gnu/libgobject-2.0.so.0
#2 0x0000aaaaaaae46a4 in chip::DeviceLayer::ConnectivityManagerImpl::ProvisionWiFiNetwork(char const*, char const*)
(this=0xaaaaaab919b8 <chip::DeviceLayer::ConnectivityManagerImpl::sInstance>, ssid=0xffffffffe7d0 "Nest-T", key=0xffffffffe7f8 "Nesttesting")
at ../third_party/connectedhomeip/src/platform/Linux/ConnectivityManagerImpl.cpp:849

 #### Summary of Changes
Clean up current network if exists before provisioning

 Fixes #4269

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

File: src/platform/Linux/ConnectivityManagerImpl.cpp [hunk 1]
```diff
@@ -842,12 +842,33 @@ CHIP_ERROR ConnectivityManagerImpl::ProvisionWiFiNetwork(const char * ssid, cons
...
     GVariant * args = nullptr;
     GVariantBuilder builder;
+    gboolean result;
 
     // Clean up current network if exists
     if (mWpaSupplicant.networkPath)
     {
-        g_object_unref(mWpaSupplicant.networkPath);
-        mWpaSupplicant.networkPath = nullptr;
+        GError * error = nullptr;
```
Comment (mspang) [inline src/platform/Linux/ConnectivityManagerImpl.cpp:850]: can't you use `err` here?

Comment (yufengwangca) [reply src/platform/Linux/ConnectivityManagerImpl.cpp:850]: if result == true and error is not null (which is highly unlikely), This temporary variable 'error'  needs to be freed after use. So I  prefer not reuse err in the outer space for local error handling.

**Review by mspang — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]
