### PR TITLE
Fixes in tv-casting-app to allow setting custom Setup Passcodes and backgrounding the app on iOS

### LINKED ISSUE #24045: [BUG] iOS tv-casting-app: Unable to use a non-test setup PIN for commissioning
### Reproduction steps

```bash
1. Edit this file to change the passcode to a different one: https://github.com/project-chip/connectedhomeip/blob/master/examples/tv-casting-app/darwin/TvCasting/TvCasting/TvCastingApp.swift#L42
2. Run the iOS tv-casting-app and the linux tv-app (without any changes to the passcode on the tv-app side so it is using the test passcode)
3. iOS tv-casting-app will discover the TV. Select it and go back to the tv-app to issue the CLI command "controller ux ok"

Actual result: Commissioning succeeds
Expected result: Commissioning should fail (due to a passcode mismatch)
```

### Bug prevalence

Everytime with the above steps to repro

### GitHub hash of the SDK that was being used

49654486db9ae006f5c9e2fc89b59c622ad614dd

### Platform

darwin

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sharadb-amazon**
Fixes https://github.com/project-chip/connectedhomeip/issues/24045 and https://github.com/project-chip/connectedhomeip/issues/24048

#### Problem
1. Unable to set a non-test setup PIN in the iOS tv-casting-app.
2. Unable to make the app inactive without errors on waking it up.

#### Change summary
* https://github.com/project-chip/connectedhomeip/pull/24046/commits/5259790c702ef0d8c5424e6bf80043116732c719 - Updated the CommissionableDataProviderImpl in MatterTvCastingBridge to generate the required spake2pVerifier and spake2pSalt if they are not provided directly by the tv-casting-app code.
* https://github.com/project-chip/connectedhomeip/pull/24046/commits/796f3e29f476202c935ca49323af59779d3c31f9 - Added APIs init/stopMatterServer that are to be called by the iOS casting app consuming the MatterTvCastingBridge to cycle through app inactive -> active states without errors. Also, as part of this changed disabled BLE.
* Also, in this PR, we make the getDiscoveredCommissioner API synchronous to avoid issues that can be caused be certain client code implementation (Eg: repeat.. while loop that does not wait for the async API to finish returning)

#### Testing
Tested with the iOS tv-casting-app (by setting a non-test setup PIN in the code and putting screen to sleep/waking it up) and the Linux tv-app.

### CODE REVIEW

**Review by chrisdecenzo — APPROVED** [review]

File: examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm [hunk 1]
```diff
@@ -495,6 +510,79 @@ - (void)shutdownAllSubscriptions:(dispatch_queue_t _Nonnull)clientQueue requestS
     });
 }
 
+- (void)initMatterServer
```
Comment (cliffamzn) [inline examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm:513]: since this is re-connecting to a video player that it was previously connected to, it implies this is intended to be called more than once

I suggest we rename this to startMatterServer or something instead even if we're calling the init function internally

Its kind of weird to call the init function more than once

File: examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm [hunk 2]
```diff
@@ -261,7 +277,7 @@ - (void)getDiscoveredCommissioner:(int)index
 {
     ChipLogProgress(AppServer, "CastingServerBridge().getDiscoveredCommissioner() called");
 
-    dispatch_async(_chipWorkQueue, ^{
+    dispatch_sync(_chipWorkQueue, ^{
```
Comment (cliffamzn) [inline examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm:280]: why do we change some of these to sync calls? Is there something dangerous about using the async?

should we add a comment here so future readers can understand the change?

Comment (sharadb-amazon) [reply examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm:280]: I alluded to the reasons for this in the PR description. The reason I made this API make the response callbacks synchronously is to avoid breaking clients if they write their code like this:
```
var commissioner: DiscoveredNodeData?;
            repeat {
                castingServerBridge.getDiscoveredCommissioner(i, clientQueue: DispatchQueue.main, discoveredCommissionerHandler: { (result: DiscoveredNodeData?) -> () in
                    commissioner = result;
                     // .. do something with commissioner
                    }
                })
                i += 1
            } while(commissioner != nil)
```

While we can require clients to handle async callbacks, it felt unnecessary in the case of this API because the results are immediately available from the cache on the SDK (no network calls are required). If this makes sense, I can add that this API will make callbacks to the client code synchronously in the API docs.

File: examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm (hunk 1 above)
Comment (sharadb-amazon) [reply examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm:513]: Sure, I'll change it to `startMatterServer`

Comment (sharadb-amazon) [reply examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm]: See https://github.com/project-chip/connectedhomeip/pull/24046/commits/1b8dcc16ea1800e40dd7b0d2a82548dfdf731bb1

File: examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm (hunk 2 above)
Comment (sharadb-amazon) [reply examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm:280]: See https://github.com/project-chip/connectedhomeip/pull/24046/commits/1b8dcc16ea1800e40dd7b0d2a82548dfdf731bb1

File: examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm [hunk 3]
```diff
@@ -495,6 +510,79 @@ - (void)shutdownAllSubscriptions:(dispatch_queue_t _Nonnull)clientQueue requestS
...
+        CHIP_ERROR err = chip::Server::GetInstance().Init(*self->_serverInitParams);
+        if (err != CHIP_NO_ERROR) {
+            ChipLogError(AppServer, "chip::Server init failed: %s", ErrorStr(err));
+            return;
+        }
+
+        // Now reconnect to the VideoPlayer the casting app was previously connected to (if any)
+        if (self->_previouslyConnectedVideoPlayer != nil) {
+            ChipLogProgress(
+                AppServer, "CastingServerBridge().initMatterServer() reconnecting to previously connected VideoPlayer...");
```
Comment (cliffamzn) [inline examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm:528]: startMatterServer here

**Review by cliffamzn — APPROVED** [review]

File: examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm (hunk 3 above)
Comment (sharadb-amazon) [reply examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm]: Done. Thanks!

**Review by woody-apple — APPROVED** [review]
