### PR TITLE
Don't pass destination as nullptr to OpenSSL encrypt/decrypt calls

### LINKED ISSUE #10190: CASE resumption fails with openssl due to null pointers being used
#### Problem
<what's wrong or missing, please include any applicable:
 * CASE resumption fails with openssl due to null pointers being used. The failure is in CASESession::GenerateSigmaResumeMIC at calling AES_CCM_encrypt with null pointers.
 >

 #### Proposed Solution
Use non-zero pointers when calling AES_CCM_encrypt or fix the AES_CCM_encrypt implementation for openssl

### PR DESCRIPTION
**Pull request by pan-apple**
#### Problem
Passing `nullptr` as destination pointer to `OpenSSL` crypto API causes failures. 
* Fixes #10190

#### Change overview
The unit tests were allocating destination buffer even though the length was 0, and test vectors had it as nullptr. This prevented the tests from catching the failures.

This PR updates the tests to not allocate destination buffer if the length is 0. That verified that the tests actually fail for the given test vectors.

The OpenSSL PAL is updated to allocate a temporary buffer for the destination if the provided buffer is `nullptr` and the length is 0.

#### Testing
Updated CHIPCryptoPALTest to catch this error condition.

### CODE REVIEW

File: src/crypto/CHIPCryptoPALOpenSSL.cpp [hunk 1]
```diff
@@ -134,16 +135,23 @@ CHIP_ERROR AES_CCM_encrypt(const uint8_t * plaintext, size_t plaintext_length, c
     int result               = 1;
     const EVP_CIPHER * type  = nullptr;
 
-    if (plaintext_length != 0)
-    {
-        VerifyOrExit(plaintext != nullptr, error = CHIP_ERROR_INVALID_ARGUMENT);
-        VerifyOrExit(ciphertext != nullptr, error = CHIP_ERROR_INVALID_ARGUMENT);
-    }
-    else if (plaintext == nullptr)
+    chip::Platform::ScopedMemoryBuffer<uint8_t> ciphertext_buf;
```
Comment (tcarmelveilleux) [inline src/crypto/CHIPCryptoPALOpenSSL.cpp:138]: We should not require heap for these calls at all.

**Review by tcarmelveilleux — CHANGES_REQUESTED** [review]

File: src/crypto/CHIPCryptoPALOpenSSL.cpp [hunk 2]
```diff
@@ -134,16 +135,23 @@ CHIP_ERROR AES_CCM_encrypt(const uint8_t * plaintext, size_t plaintext_length, c
...
+
+    if (plaintext_length == 0)
     {
-        plaintext = Uint8::from_const_char(kEmptyCryptoText);
+        if (plaintext == nullptr)
+        {
+            plaintext = Uint8::from_const_char(kEmptyCryptoText);
+        }
+        if (ciphertext == nullptr)
```
Comment (tcarmelveilleux) [inline src/crypto/CHIPCryptoPALOpenSSL.cpp:146]: ciphertext can never be nullptr if plaintext != nullptr.

**Comment by bluebin14** [comment]
Could use a simple 1 byte static for catching both source and destination null pointers or even better (uint8_t *) 1 to catch any non compliant crypto implementation.

**Review by tcarmelveilleux — APPROVED** [review]

**Review by emargolis — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by bluebin14 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]
