### PR TITLE
Remove unset threadNetwork Scan

### LINKED ISSUE #31703: [BUG][Android] When the device retries the BLE-Thread commisisong, ScanNetworksListener is not called.
### Reproduction steps

1. Set true in AttemptNetworkScanThread.
2. Try commissioning with thread device.
3. ScanNetworksListener callback / set thread credentials
4. After commissioning complete, commissioner try to commission with another device.
5.  Not call ScanNetworksListener.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

cc5ca440bd94971db2f1ed45246d219eb5de096f

### Platform

android

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by joonhaengHeo**
Fix #31703 

The AttemptThreadNetworkScan value is set when the controller is initialized. If this value is set to true, the scan callback must be called, and will be called the first time.

However, if you call the commission API again for commissioning another device, the AttemptThreadNetworkScan value changes to false as the thread credentials are set.

To prevent this, it is necessary to modify the AttemptThreadNetworkScan value so that it does not change even if thread credentials are set.

### CODE REVIEW

**Comment by andy31415** [comment]
Unrelated to this PR, but why is mAttemptThreadNetworkScan an optional? Its only use seems to be a `valueOr(false)` ... so then why not just make it a bool value?

File: src/controller/CommissioningDelegate.h [hunk 1]
```diff
@@ -376,12 +376,9 @@ class CommissioningParameters
         return *this;
     }
 
-    // If a ThreadOperationalDataset is provided, then the ThreadNetworkScan will not be attempted
     CommissioningParameters & SetThreadOperationalDataset(ByteSpan threadOperationalDataset)
     {
-
         mThreadOperationalDataset.SetValue(threadOperationalDataset);
```
Comment (andy31415) [inline src/controller/CommissioningDelegate.h:381]: once you set mThreadOperationalDataset, it looks like mAttemptThreadNetworkScan cannot be changed anymore: SetAttemptThreadNetworkScan has a `if (!mThreadOperationalDataset.HasValue())` (which I find odd ... a setter that refuses to set.

I am not familiar with this code, but could you explain why mAttemptThreadNetworkScan exists? What is its purpuse and how does it achieve it? Maybe @chrisdecenzo too.

Overall this seems to be very suspect code:
  - a `Optional<bool>` that is only ever used as a bool. It should be a bool initialized to false it seems
  - a setter that conditionally does not set, which I would count as a bug unless there is a serious reason for it ... and then the method should not be called `set` or some other workaround should be done

Please try to explain me the logic, since I am surprised I have so much trouble understanding the flow given that this is a simple member variable with maybe 5 usages :(

Comment (andy31415) [reply src/controller/CommissioningDelegate.h:381]: Only java seems to use the `SetAttemptThreadNetworkScan`. Why not drop it entirely then if we always want to scan?

Comment (andy31415) [reply src/controller/CommissioningDelegate.h:381]: Same questions for attempted wifi scans - why optional<bool> and why only java? At least the setter on that one does not have conditionals ...

Comment (andy31415) [reply src/controller/CommissioningDelegate.h:381]: I suggest the following changes:

- [ ] remove conditional from the setters
- [ ] make these variables bool (not optional)
- [ ] remove this line as well as the PR does

Also consider why java needs to alter these but other code does not currently. This should be documented and I saw no clear documentation. Maybe these variables should not exist.

File: src/controller/CommissioningDelegate.h [hunk 2]
```diff
@@ -376,12 +376,9 @@ class CommissioningParameters
...
-        mAttemptThreadNetworkScan = MakeOptional(static_cast<bool>(false));
```
Comment (bzbarsky-apple) [inline src/controller/CommissioningDelegate.h:384]: This seems wrong; if we have thread credentials we shouldn't _also_ do a network scan.

If the issue is that state that is persisted across commissionings is not reset properly when a commissioning ends, then _that_ is what needs to get fixed.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/controller/CommissioningDelegate.h (hunk 2 above)
Comment (joonhaengHeo) [reply src/controller/CommissioningDelegate.h:384]: @bzbarsky-apple 
no. I don't think so.
Since this is something that is explicitly set by the user who actually uses this parameter, I think it would cause more confusion if it was automatically disabled when the dataset is set.

I would agree with you if it were to be disabled due to a change in behavior, but this is a situation where the direct user has explicitly enabled it. For Wi-Fi, no such thing is set up.

File: src/controller/CommissioningDelegate.h (hunk 1 above)
Comment (joonhaengHeo) [reply src/controller/CommissioningDelegate.h:381]: @andy31415 
I agree with you that the part declared as Optional<bool> is strange. However, I don't know the exact reason because I didn't create the initial code.

This code is affected by all commissioners that use src/controller. However, this issue cannot occur except on platforms that use Java.
  - In the case of chip-tool, the program is terminated after commissioning, so set it again.
  - In the case of darwin, only the method set before commissioning is possible.

I don't understand exactly what "remove conditional from the setters" means. Please explain again what it means.

File: src/controller/CommissioningDelegate.h (hunk 2 above)
Comment (yunhanw-google) [reply src/controller/CommissioningDelegate.h:384]: i concur with @bzbarsky-apple ,  if we have thread credentials we shouldn't also do a network scan.

Comment (joonhaengHeo) [reply src/controller/CommissioningDelegate.h:384]: @yunhanw-google 
Enabling network scan is intentional by those using the API. In addition, network credentials can be set not only at the beginning, but also after a network scan, and there is a problem in that network scans cannot be performed again after this. There is no other way, so how can we solve this issue?

I think saving it somewhere else and then recovering it is a more complicated approach.

With scan enabled, I think it's natural to add credentials for thread connection.

Comment (erjiaqing) [reply src/controller/CommissioningDelegate.h:384]: If we think the users should not enable network scan, I would suggest making use of the Optional:

- Not set: Do a scan if no credentials provided
- True: Always scan
- False: Always not to scan.

I think we should also clearify what this function really does, according to its name `CommissioningParameters`, it seems to be a configuration, but if we have a fuse `mAttemptThreadNetworkScan = MakeOptional(static_cast<bool>(false));` then it more like a state?

Comment (joonhaengHeo) [reply src/controller/CommissioningDelegate.h:384]: @bzbarsky-apple 
https://github.com/project-chip/connectedhomeip/commit/5706a210f9220e8761bd5f944678efd0e4fe2c89

Here, is there a reason why the three parameter settings below were deleted?
AttemptThreadNetworkScan
AttemptWiFiNetworkScan
SkipCommissioningComplete

Even if you save the Commissioning Parameter Set in the Upper Layer, it is difficult to process it separately because you deleted some parts.

Comment (bzbarsky-apple) [reply src/controller/CommissioningDelegate.h:384]: > For Wi-Fi, no such thing is set up.

How does the Wi-Fi behavior differ?  I would expect the same behavior there: no scan if we have credentials....  But maybe I'm missing something about how this is supposed to work?

What is the intended behavior of "scan + credentials" and what are the credentials used for in that case?

> Here, is there a reason why the three parameter settings below were deleted?

I don't follow the question.  What was deleted?  If you're asking why we are no longer getting/setting those explicitly, it's because the `mParams = params;` that changeset added handles all that for simple boolean bits.

Comment (joonhaengHeo) [reply src/controller/CommissioningDelegate.h:384]: @bzbarsky-apple 
The problem now is as follows.
- If you add Thread Credentials after ScanNetwork, ScanNetworks will no longer work.
   -> Settings for ScanNetwork are not setting each commissioning, but only once when the DeviceCommissioner object is created.

The reason why I asked why the three parameters above were deleted is because I think there is a need to restore that part in order to manage the Commissioning Parameter separately (params = mParam).

  As you said, Wi-Fi and Thread must be managed the same way. (A decision must be made whether to delete both or add both.)

There are two solutions I thought of.
1. Similar to the PR I currently uploaded, when setting Credentials, disabling ScanNetwork was deleted. (Of course, I know your opinion is No.)

2. Manage the Commissioning Parameters separately and set them in the Commissioning Parameters in AutoCommissioner when commissioning.
  -> In this case, as mentioned above, the code related to the three parameter settings must be restored.

Comment (bzbarsky-apple) [reply src/controller/CommissioningDelegate.h:384]: > Settings for ScanNetwork are not setting each commissioning, but only once when the DeviceCommissioner object is created.

If that is the case, that would be the bug that needs fixing, no?

>  In this case, as mentioned above, the code related to the three parameter settings must be restored.

Which exact code?  Again, those settings are copied from the incoming parameters by the assignment to `mParams`....

Comment (joonhaengHeo) [reply src/controller/CommissioningDelegate.h]: @bzbarsky-apple 
I restored the code and separated the part that sets the Android Commissioning Parameter. Is this the right way to make changes?

File: src/controller/AutoCommissioner.cpp [hunk 3]
```diff
@@ -129,6 +129,26 @@ CHIP_ERROR AutoCommissioner::SetCommissioningParameters(const CommissioningParam
         mParams.ClearExternalBufferDependentValues();
     }
 
+    if (params.GetFailsafeTimerSeconds().HasValue())
+    {
+        mParams.SetFailsafeTimerSeconds(params.GetFailsafeTimerSeconds().Value());
```
Comment (bzbarsky-apple) [inline src/controller/AutoCommissioner.cpp:134]: Why is this needed?  This has _already been done_ on line 125, no?

Comment (joonhaengHeo) [reply src/controller/AutoCommissioner.cpp:134]: You're right. I knew that copying was not possible in the case of Optional. I will delete this code.

File: src/controller/CommissioningDelegate.h (hunk 1 above)
Comment (joonhaengHeo) [reply src/controller/CommissioningDelegate.h]: @andy31415 
The implementation has been modified only for Android Platform. Please review again.

File: src/controller/CommissioningDelegate.h [hunk 4]
```diff
@@ -370,9 +370,12 @@ class CommissioningParameters
         mAttestationNonce.SetValue(attestationNonce);
         return *this;
     }
+
+    // If a WiFiCredentials is provided, then the WiFiNetworkScan will not be attempted
     CommissioningParameters & SetWiFiCredentials(WiFiCredentials wifiCreds)
     {
         mWiFiCreds.SetValue(wifiCreds);
+        mAttemptWiFiNetworkScan = MakeOptional(static_cast<bool>(false));
```
Comment (bzbarsky-apple) [inline src/controller/CommissioningDelegate.h:378]: I know you copied the Thread code, but this seems like a complicated way to do:
```suggestion
        mAttemptWiFiNetworkScan.SetValue(false);
```

**Review by bzbarsky-apple — APPROVED** [review]
Approving the src/controller core bit.  I did not look at the java changes.

**Review by yunhanw-google — APPROVED** [review]
