### PR TITLE
 fix asr platform issue

### LINKED ISSUE #26637: ASR platform manager synchronization seems to be completely broken
See https://github.com/project-chip/connectedhomeip/pull/26361#pullrequestreview-1431308530

@tx2rx @andy31415

### PR DESCRIPTION
**Pull request by tx2rx**
fix #26637 

1,modify PlatformManagerImpl implementation
2,bump third_party/asr/xxx/asr_sdk
3,remove unless code in SystemTimeSupport

### CODE REVIEW

File: src/platform/ASR/PlatformManagerImpl.cpp [hunk 1]
```diff
@@ -299,11 +311,13 @@ void PlatformManagerImpl::SetEventFlags(uint32_t flags)
 
 void PlatformManagerImpl::HandleTimerEvent(void)
 {
+    LockChipStack();
```
Comment (bzbarsky-apple) [inline src/platform/ASR/PlatformManagerImpl.cpp:314]: This is probably not the right locking scope.  Compare the locking scope that the FreeRTOS implementation has....

Comment (tx2rx) [reply src/platform/ASR/PlatformManagerImpl.cpp]: I understand,your purpose is to lock the chip stack when 'Handle Timer and Event', and immediate pop all queue . We changed the '_RunEventLoop' implementation copied from FreeRTOS, that makes the implementation look cleaner. we use lega rtos instead of freertos because that allows for compatibility with more RTOS

File: src/platform/ASR/PlatformManagerImpl.cpp [hunk 2]
```diff
@@ -51,17 +51,12 @@ CHIP_ERROR PlatformManagerImpl::_InitChipStack(void)
     err = Internal::InitLwIPCoreLock();
     SuccessOrExit(err);
 
-    /* Initialize the event flags. */
-    result = lega_rtos_init_event_flags(&mEventFlags);
```
Comment (bzbarsky-apple) [inline src/platform/ASR/PlatformManagerImpl.cpp:55]: These changes to how timers are handled don't obviously seem related to the locking bits, but ok....

File: src/platform/ASR/PlatformManagerImpl.cpp [hunk 3]
```diff
@@ -93,47 +91,86 @@ CHIP_ERROR PlatformManagerImpl::_InitChipStack(void)
 
 void PlatformManagerImpl::_RunEventLoop()
 {
-    kTaskRunningEventFlag = 1;
-
+    mRunningEventActive = true;
```
Comment (bzbarsky-apple) [inline src/platform/ASR/PlatformManagerImpl.cpp:94]: I'm a little confused about this variable:

1. It should be documented in terms of what it means.
2. Why do we hold `mEventMutex` some times, but not others, when accessing this variable?

Comment (tx2rx) [reply src/platform/ASR/PlatformManagerImpl.cpp]: if don't think about the queue and mutex variables, we can remove mRunningEventActive to reduce complexity, after all, they take memory little...

**Review by bzbarsky-apple — APPROVED** [review]
Just to be clear, I was not asking you to remove mEventMutex, just asking that we use it consistently... But I guess not having it at all is consistent.

**Comment by tx2rx** [comment]
@bzbarsky-apple hi, can this be safely merged?

**Comment by bzbarsky-apple** [comment]
@tx2rx PRs generally need two reviews from two different companies.  See the "Pending" pullapprove CI job.

Concretely: _I_ cannot merge this PR until it has another review.

File: src/platform/ASR/ASRConfig.cpp [hunk 4]
```diff
@@ -226,7 +226,7 @@ CHIP_ERROR ASRConfig::ReadFactoryConfigValue(asr_matter_partition_t matter_parti
     ret = asr_factory_config_read(matter_partition, buf, (uint32_t) bufSize, (uint32_t *) &outLen);
 
     if (ret != 0)
-        ChipLogProgress(DeviceLayer, "asr_factory_config_read: %d failed, ret = %d\n", matter_partition, ret);
+        ChipLogProgress(DeviceLayer, "asr_factory_config_read: %d failed, ret = %d\n", matter_partition, (int) ret);
```
Comment (andy31415) [inline src/platform/ASR/ASRConfig.cpp:229]: we generally preffer C++ casts instead of C casts. use `static_cast<int>` instead.

**Review by andy31415 — APPROVED** [review]

**Comment by tx2rx** [comment]
hi @bzbarsky-apple ,we remove some unused implemention in DiagnosticDataProviderImpl, these functions are not implemented yet, and should return failure. 
please review and merge it , thanks a lot!

**Review by bzbarsky-apple — APPROVED** [review]
