### PR TITLE
Fixing size checks in Set/GetRotatingDeviceIdUniqueId and right sizing mRotatingDeviceIdUniqueId

### LINKED ISSUE #24041: [BUG] RotatingDeviceId not generated per custom uniqueId
### Reproduction steps

```bash
1. Run the tv-casting-app and tv-app.
2. tv-casting-app will discover the TV. Select the TV.
3. Compare the uniqueId used to generate the rotatingDeviceId on the tv-casting-app (w/ breakpoints or additional logging)

Actual Result: The uniqueId passed in to the SDK is NOT used to generate the rotatingDeviceId
Expected result: The uniqueId passed in to the SDK should be used to generate the rotatingDeviceId
```

### Bug prevalence

Everytime with the above steps to repro

### GitHub hash of the SDK that was being used

49654486db9ae006f5c9e2fc89b59c622ad614dd

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sharadb-amazon**
Fixes https://github.com/project-chip/connectedhomeip/issues/24041

#### Problem
RotatingDeviceId is not generated per custom uniqueId passed into the SDK. This was because the Get/Set methods on the rotatingDeviceIdUniqueId were asserting that sizeof the uniqueId passed in is equal to kRotatingDeviceIDUniqueIDLength, whereas it can actually be of varying sizes. Additionally, for the tv-casting-app, the default buffer size for the uniqueId was only 16 bytes, but that is just the minimum required length.

#### Change summary
1. Changed the size/length assertions in the Set/GetRotatingDeviceIdUniqueId methods.
2. For the tv-casting-app, overrode / defined CHIP_DEVICE_CONFIG_ROTATING_DEVICE_ID_UNIQUE_ID_LENGTH 64

#### Testing
Tested that the uniqueId passed in to the SDK actually gets used to generate the rotatingDeviceId

### CODE REVIEW

File: examples/tv-casting-app/tv-casting-common/include/CHIPProjectAppConfig.h [hunk 1]
```diff
@@ -55,3 +55,5 @@
 #define CONFIG_BUILD_FOR_HOST_UNIT_TEST 1
 
 #define CHIP_ENABLE_ROTATING_DEVICE_ID 1
+
+#define CHIP_DEVICE_CONFIG_ROTATING_DEVICE_ID_UNIQUE_ID_LENGTH 64
```
Comment (chrisdecenzo) [inline examples/tv-casting-app/tv-casting-common/include/CHIPProjectAppConfig.h:59]: doesn't this need to be defined in the CHIPProjectConfig.h?

**Review by chrisdecenzo — APPROVED** [review]

File: examples/tv-casting-app/tv-casting-common/include/CHIPProjectAppConfig.h (hunk 1 above)
Comment (bzbarsky-apple) [inline examples/tv-casting-app/tv-casting-common/include/CHIPProjectAppConfig.h:59]: Should this have some sort of default defined?  Or is the intent that people using rotating device ids should ensure this is defined or get compile errors?

File: src/include/platform/internal/GenericConfigurationManagerImpl.h [hunk 2]
```diff
@@ -118,7 +118,9 @@ class GenericConfigurationManagerImpl : public ConfigurationManager
 protected:
 #if CHIP_ENABLE_ROTATING_DEVICE_ID && defined(CHIP_DEVICE_CONFIG_ROTATING_DEVICE_ID_UNIQUE_ID)
     chip::LifetimePersistedCounter<uint32_t> mLifetimePersistedCounter;
-    uint8_t mRotatingDeviceIdUniqueId[kRotatingDeviceIDUniqueIDLength] = CHIP_DEVICE_CONFIG_ROTATING_DEVICE_ID_UNIQUE_ID;
+    uint8_t mRotatingDeviceIdUniqueId[CHIP_DEVICE_CONFIG_ROTATING_DEVICE_ID_UNIQUE_ID_LENGTH] =
+        CHIP_DEVICE_CONFIG_ROTATING_DEVICE_ID_UNIQUE_ID;
+    size_t mRotatingDeviceIdUniqueIdLength = kRotatingDeviceIDUniqueIDLength;
```
Comment (bzbarsky-apple) [inline src/include/platform/internal/GenericConfigurationManagerImpl.h:123]: Should't that be the actual size of `CHIP_DEVICE_CONFIG_ROTATING_DEVICE_ID_UNIQUE_ID`?

File: examples/tv-casting-app/tv-casting-common/include/CHIPProjectAppConfig.h (hunk 1 above)
Comment (sharadb-amazon) [reply examples/tv-casting-app/tv-casting-common/include/CHIPProjectAppConfig.h:59]: The default is already defined here: https://github.com/project-chip/connectedhomeip/blob/6ccbb7c4b8e859343d5a7562986f8162971b6b22/src/include/platform/CHIPDeviceConfig.h#L288-L290

File: src/include/platform/internal/GenericConfigurationManagerImpl.h (hunk 2 above)
Comment (sharadb-amazon) [reply src/include/platform/internal/GenericConfigurationManagerImpl.h:123]: That is what the constant `kRotatingDeviceIDUniqueIDLength` is:
https://github.com/project-chip/connectedhomeip/blob/48860e29fca4bef88c433dfa0436334c7870d112/src/include/platform/ConfigurationManager.h#L80

Comment (sharadb-amazon) [reply src/include/platform/internal/GenericConfigurationManagerImpl.h:123]: Reopen this if you meant that setting mRotatingDeviceIdUniqueIdLength to CHIP_DEVICE_CONFIG_ROTATING_DEVICE_ID_UNIQUE_ID_LENGTH is preferable instead of going through kRotatingDeviceIDUniqueIDLength

Comment (bzbarsky-apple) [reply src/include/platform/internal/GenericConfigurationManagerImpl.h:123]: If they're the same thing, this seems fine.  The naming could use some cleanup to make it clear which things are lengths of actual things vs which things are max-lengths, but....

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
