### PR TITLE
Fix session eviction handling of eviction hints.

### LINKED ISSUE #30728: [BUG] Default secure session eviction policy is broken when a new session is established
### Reproduction steps

1. Start in a state where the secure session table is full (with one of the slots being the pre-allocated session that CASEServer will use for new incoming CASE attempts), with only one session per peer in the table.  Ideally all on the same fabric.
2. Have a CASE initiator that does _not_ have any existing sessions in the session table try to establish CASE.
3. The new CASE session is established.
4. We try to allocate a new secure session to listen for more incoming CASE (see step 1).
5. This _evicts the just-established CASE session_.

This happens because CASE passes the just-established ScopedNodeId as an eviction hint to session allocation.  When DefaultEvictionPolicy does its sort it:

1. Prioritizes fabrics with more sessions.  If all the sessions are on the same fabric, this is a no-op.
2. Prioritizes sessions that match the hint's fabric.  Again, if there is only one fabric this is all a no-op.
3. Prioritizes peers that have more sessions to them.  Since by assumption there is one session per peer, this is also a no-op.
4. Prioritizes sessions that match the eviction hint.  This will prioritize the just-established session.

Only after that are things like defunct state and activity time checked.  So you can have lost of defunct sessions to various peers and end up evicting the just-established session.

### Bug prevalence

Every time, given the preconditions

### GitHub hash of the SDK that was being used

b37915807c8bcbdcb1ce08f6ada807fd0f46e2e5

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

In practice we have a nonempty hint in two situations:

1. For a CASE initiator, it's the peer ID we're establishing a session to.  In this case, we can assume that we do not have an existing active session, since CASESessionManager would have just used it.
2. For a CASE responder, it's the peer ID that we just established a new session.  In that case we definitely have an active session _and we do not want to evict it_.

So what I would propose is that we treat a session as not matching the eviction hint if it's (1) active and (2) has mNumMatchingOnPeer == 0 (which means it's the only active session to that peer).

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
When we establish a session as a CASE responder, we try to allocate a new session to listen to session establishments, and use the just-established-session's peer ID as the eviction hint.

If we had a bunch of active sessions on a fabric, all to different nodes, this would cause the just-established session to be evicted, since it matched the hint.

The fix is to only consider sessions for eviction based on the hint if they are either non-active or not unique sessions to the peer (at which point, the just-established session should be last in priority order for eviction).

Fixes https://github.com/project-chip/connectedhomeip/issues/30728

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by tcarmelveilleux — APPROVED** [review]

**Review by tehampson — APPROVED** [review]

File: src/transport/SecureSessionTable.cpp [hunk 1]
```diff
@@ -265,8 +265,31 @@ void SecureSessionTable::DefaultEvictionPolicy(EvictionPolicyContext & evictionC
...
+        //    node we are going to establish CASE to.
+        //
+        // In case 2, we should not end up here if there is an active session to
+        // the peer at all (because that session should have been used instead
+        // of establishing a new one).
+        //
+        // In case 1, we know we have a session matching the hint, but we don't
+        // want to pick that one for eviction, because we just established it.
+        // So we should not consider a session as matching a hint if it's active
+        // and is the only session to our peer.
```
Comment (mrjerryjohns) [inline src/transport/SecureSessionTable.cpp:282]: While this the right framing of the logic, the way it is written below is the invert of that. So perhaps mention that !((IsActive() && session.mNumMatchingOnPeer == 0) is the following using DeMorgan's expansion rule (or something?).

Comment (bzbarsky-apple) [reply src/transport/SecureSessionTable.cpp:282]: Yep, I can add a comment to that effect.

Comment (bzbarsky-apple) [reply src/transport/SecureSessionTable.cpp:282]: https://github.com/project-chip/connectedhomeip/pull/30938 addresses this.
