### PR TITLE
40501: Decouple fixed-label cluster

### LINKED ISSUE #40501: ServerClusterInterface: decouple fixed-label-server cluster

### PR DESCRIPTION
**Pull request by arielsz71**
#### Summary

Implementation for decoupling FixedLabel cluster and make it code driven.

- Class FixedLabelAttrAccess (subclass of AttributeAccessInterface) was replaced by FixedLabelCluster (subclass of DefaultServerCluster)
- Added CodegenIntegration.cpp and maintain an array of cluster instances for the different endpoints.
- Added unit tests for FixedLabelCluster

#### Related issues

Fixes https://github.com/project-chip/connectedhomeip/issues/40501

#### Testing

Tested using chip-all-clusters-app and chip-repl:

chip-repl commands:
await devCtrl.CommissionWithCode("MT:-24J0AFN00KA0648G00", 1)
await devCtrl.ReadAttribute(1, [ Clusters.FixedLabel ])

chip-repl response shows the cluster is returning its attributes successfully and the attributes have the expected values.
This cluster does not support WriteAttribute.

### CODE REVIEW

File: src/app/clusters/fixed-label-server/fixed-label-cluster.cpp [hunk 1]
```diff
@@ -0,0 +1,88 @@
+/*
+ *    Copyright (c) 2025 Project CHIP Authors
```
Comment (andy31415) [inline src/app/clusters/fixed-label-server/fixed-label-cluster.cpp]: you kept a lot of code from the old cluster I presume, so change this to 2021-2025

```suggestion
 *    Copyright (c) 2021-2025 Project CHIP Authors
```

File: src/app/clusters/fixed-label-server/fixed-label-cluster.h [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+public:
+    FixedLabelCluster(EndpointId endpoint);
+
+    // Server cluster implementation
+    DataModel::ActionReturnStatus ReadAttribute(const DataModel::ReadAttributeRequest & request,
+                                                AttributeValueEncoder & encoder) override;
+    CHIP_ERROR Attributes(const ConcreteClusterPath & path, ReadOnlyBufferBuilder<DataModel::AttributeEntry> & builder) override;
+
+protected:
+    CHIP_ERROR ReadLabelList(EndpointId endpoint, AttributeValueEncoder & encoder);
```
Comment (andy31415) [inline src/app/clusters/fixed-label-server/fixed-label-cluster.h]: this does not need to be a member method probably. If you place it static in the cpp file (in an anoynmous namespace) the compiler may be able to optimize it more.

Comment (arielsz71) [reply src/app/clusters/fixed-label-server/fixed-label-cluster.h]: Addressed.

File: src/app/clusters/fixed-label-server/fixed-label-cluster.cpp (hunk 1 above)
Comment (arielsz71) [reply src/app/clusters/fixed-label-server/fixed-label-cluster.cpp]: Addressed.

File: src/app/clusters/fixed-label-server/fixed-label-cluster.cpp [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+        {
+            err = encoder.EncodeEmptyList();
+        }
+    }
+    else
+    {
+        err = encoder.EncodeEmptyList();
+    }
+
+    return err;
```
[the remark this answers is not in the document]
Comment (arielsz71) [reply src/app/clusters/fixed-label-server/fixed-label-cluster.cpp]: Addressed.

File: src/app/clusters/fixed-label-server/CodegenIntegration.cpp [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+    gServers[arrayIndex].Create(endpointId);
+    CHIP_ERROR err = CodegenDataModelProvider::Instance().Registry().Register(gServers[arrayIndex].Registration());
+    if (err != CHIP_NO_ERROR)
+    {
+        ChipLogError(AppServer, "Failed to register FixedLabel cluster on endpoint %u: %" CHIP_ERROR_FORMAT, endpointId,
+                     err.Format());
+    }
+}
+
+void emberAfFixedLabelClusterServerShutdownCallback(EndpointId endpointId)
```
Comment (andy31415) [inline src/app/clusters/fixed-label-server/CodegenIntegration.cpp]: this should be using the Matter call. this is not symmetric: emberAf is the startup, matter is the shutdown :( 

Please debug to make sure these are called (e.g. on chip-all-clusters)

File: src/app/clusters/fixed-label-server/CodegenIntegration.cpp [hunk 5]
```diff
@@ -0,0 +1,94 @@
...
+    CHIP_ERROR err = CodegenDataModelProvider::Instance().Registry().Unregister(&gServers[arrayIndex].Cluster());
+    if (err != CHIP_NO_ERROR)
+    {
+        ChipLogError(AppServer, "Failed to unregister FixedLabel cluster on endpoint %u: %" CHIP_ERROR_FORMAT, endpointId,
+                     err.Format());
+    }
+    gServers[arrayIndex].Destroy();
+}
+
+void MatterFixedLabelClusterServerInitCallback(EndpointId endpointId) {}
```
Comment (andy31415) [inline src/app/clusters/fixed-label-server/CodegenIntegration.cpp]: There is no such call used. Please delete all these fillers and only add them back if they are actually needed (compile failing without)

File: src/app/clusters/fixed-label-server/tests/TestFixedLabelCluster.cpp [hunk 6]
```diff
@@ -0,0 +1,114 @@
...
+        ASSERT_NE(buffer.Alloc(1024).Get(), nullptr);
+
+        AttributeReportIBs::Builder attributeReportIBsBuilder;
+        TLV::TLVWriter reportWriter;
+        reportWriter.Init(buffer.Get(), buffer.AllocatedSize());
+        ASSERT_EQ(attributeReportIBsBuilder.Init(&reportWriter), CHIP_NO_ERROR);
+
+        AttributeValueEncoder encoder(attributeReportIBsBuilder, Access::SubjectDescriptor{}, request.path, 0 /* dataVersion */);
+
+        mStatus = mCluster.ReadAttribute(request, encoder);
```
Comment (tersal) [inline src/app/clusters/fixed-label-server/tests/TestFixedLabelCluster.cpp:81]: It seems that these tests don't validate that the encoded value "returned" by the ReadAttribute call is actually the expected one, right?

Comment (arielsz71) [reply src/app/clusters/fixed-label-server/tests/TestFixedLabelCluster.cpp:81]: Yes, currently the unit tests are just checking that the operation succeeded or failed as expected, the thing with checking the values is that they are determined at runtime via DeviceLayer::GetDeviceInfoProvider() and provider->IterateFixedLabel(endpoint) and I do not know in advance the expected values.

File: src/app/clusters/fixed-label-server/CodegenIntegration.cpp [hunk 7]
```diff
@@ -0,0 +1,88 @@
...
+constexpr size_t kFixedLabelFixedClusterCount = FixedLabel::StaticApplicationConfig::kFixedClusterConfig.size();
+constexpr size_t kFixedLabelMaxClusterCount   = kFixedLabelFixedClusterCount + CHIP_DEVICE_CONFIG_DYNAMIC_ENDPOINT_COUNT;
+
+LazyRegisteredServerCluster<FixedLabelCluster> gServers[kFixedLabelMaxClusterCount];
+
+// Find the 0-based array index corresponding to the given endpoint id.
+// Log an error if not found.
+bool FindEndpointWithLog(EndpointId endpointId, uint16_t & outArrayIndex)
+{
+    uint16_t arrayIndex = emberAfGetClusterServerEndpointIndex(endpointId, FixedLabel::Id, kFixedLabelFixedClusterCount);
```
Comment (andy31415) [inline src/app/clusters/fixed-label-server/CodegenIntegration.cpp]: Please update this to use https://github.com/project-chip/connectedhomeip/blob/master/src/data-model-providers/codegen/ClusterIntegration.h

Comment (arielsz71) [reply src/app/clusters/fixed-label-server/CodegenIntegration.cpp]: Addressed.

**Review by andy31415 — APPROVED** [review]

File: src/app/clusters/fixed-label-server/CodegenIntegration.cpp [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+
+constexpr size_t kFixedLabelFixedClusterCount = FixedLabel::StaticApplicationConfig::kFixedClusterConfig.size();
+constexpr size_t kFixedLabelMaxClusterCount   = kFixedLabelFixedClusterCount + CHIP_DEVICE_CONFIG_DYNAMIC_ENDPOINT_COUNT;
+
+LazyRegisteredServerCluster<FixedLabelCluster> gServers[kFixedLabelMaxClusterCount];
+
+class IntegrationDelegate : public CodegenClusterIntegration::Delegate
+{
+public:
+    ServerClusterRegistration & CreateRegistration(EndpointId endpointId, unsigned emberEndpointIndex,
```
Comment (bzbarsky-apple) [inline src/app/clusters/fixed-label-server/CodegenIntegration.cpp]: Note the naming discussion in https://github.com/project-chip/connectedhomeip/pull/40957, as well as the API changes there.

File: src/app/zap-templates/zcl/zcl-with-test-extensions.json [hunk 9]
```diff
@@ -801,6 +801,7 @@
             "FeatureMap"
         ],
         "Camera AV Settings User Level Management": ["MPTZPosition"],
+        "Fixed Label": ["LabelList", "ClusterRevision", "FeatureMap"],
```
Comment (bzbarsky-apple) [inline src/app/zap-templates/zcl/zcl-with-test-extensions.json:804]:
```suggestion
        "Fixed Label": ["ClusterRevision", "FeatureMap"],
```
would be fine too, since lists are handled automatically.  But either way.  Same for the other json file.

**Review by bzbarsky-apple — APPROVED** [review]
