### PR TITLE
Fabric removal should only sync-deliver events for that fabric.

### LINKED ISSUE #21744: about leave event
No matter how many fabrics the dut joins,dut just report fabricIndex 1 when i call chip::Server::GetInstance().GetFabricTable().DeleteAllFabrics() before factroy reset
 
 * expected behavior
   report all fabric index
 * actual behavior
  report fabric index1
* steps to reproduce
  first : dut commission to TH1 and TH2
  second : TH1 and TH2 subscribe leave event: basic subscribe-event leave 1 60 1 0、basic subscribe-event leave 1 60 2 0 --commissioner-name beta
  third : call chip::Server::GetInstance().GetFabricTable().DeleteAllFabrics() befofe factory reset

I try to understand the code and I can see that the event has been pushed to eventManagerment,but it doesn't work well actually, I don't understand what's going on here

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
We were running into an issue where fabric removal would do sync event
delivery on other fabrics, and then removal of _those_ fabrics could
not deliver events (because there was a Report Data outstanding that
had not gotten a Status Response yet).

The fix is to only sync-deliver events for the fabric about to be
removed when a fabric is removed.

Fixes https://github.com/project-chip/connectedhomeip/issues/21744

#### Problem
See above.

#### Change overview
See above.

#### Testing
Ran the commands from #21744.  Output before this change:
```
(On fabric 1)
[1660064884674] [90390:8953652] CHIP: [TOO] Endpoint: 0 Cluster: 0x0000_0028 Event 0x0000_0002
[1660064884674] [90390:8953652] CHIP: [TOO]   Event number: 65541
[1660064884674] [90390:8953652] CHIP: [TOO]   Priority: Info
[1660064884674] [90390:8953652] CHIP: [TOO]   Timestamp: 126366
[1660064884676] [90390:8953652] CHIP: [TOO]   Leave: {
[1660064884676] [90390:8953652] CHIP: [TOO]     FabricIndex: 1
[1660064884676] [90390:8953652] CHIP: [TOO]    }

(On fabric 2)
[1660064885525] [90390:8955520] CHIP: [TOO] Endpoint: 0 Cluster: 0x0000_0028 Event 0x0000_0002
[1660064885525] [90390:8955520] CHIP: [TOO]   Event number: 65541
[1660064885525] [90390:8955520] CHIP: [TOO]   Priority: Info
[1660064885525] [90390:8955520] CHIP: [TOO]   Timestamp: 126366
[1660064885525] [90390:8955520] CHIP: [TOO]   Leave: {
[1660064885525] [90390:8955520] CHIP: [TOO]     FabricIndex: 1
[1660064885525] [90390:8955520] CHIP: [TOO]    }
```

Output after this change:
```
(On fabric 1)
[1660064884674] [90390:8953652] CHIP: [TOO] Endpoint: 0 Cluster: 0x0000_0028 Event 0x0000_0002
[1660064884674] [90390:8953652] CHIP: [TOO]   Event number: 65541
[1660064884674] [90390:8953652] CHIP: [TOO]   Priority: Info
[1660064884674] [90390:8953652] CHIP: [TOO]   Timestamp: 126366
[1660064884676] [90390:8953652] CHIP: [TOO]   Leave: {
[1660064884676] [90390:8953652] CHIP: [TOO]     FabricIndex: 1
[1660064884676] [90390:8953652] CHIP: [TOO]    }

(On fabric 2)
[1660064885525] [90390:8955520] CHIP: [TOO] Endpoint: 0 Cluster: 0x0000_0028 Event 0x0000_0002
[1660064885525] [90390:8955520] CHIP: [TOO]   Event number: 65541
[1660064885525] [90390:8955520] CHIP: [TOO]   Priority: Info
[1660064885525] [90390:8955520] CHIP: [TOO]   Timestamp: 126366
[1660064885525] [90390:8955520] CHIP: [TOO]   Leave: {
[1660064885525] [90390:8955520] CHIP: [TOO]     FabricIndex: 1
[1660064885525] [90390:8955520] CHIP: [TOO]    }
[1660064885525] [90390:8955520] CHIP: [TOO] Endpoint: 0 Cluster: 0x0000_0028 Event 0x0000_0002
[1660064885525] [90390:8955520] CHIP: [TOO]   Event number: 65542
[1660064885525] [90390:8955520] CHIP: [TOO]   Priority: Info
[1660064885525] [90390:8955520] CHIP: [TOO]   Timestamp: 127194
[1660064885525] [90390:8955520] CHIP: [TOO]   Leave: {
[1660064885525] [90390:8955520] CHIP: [TOO]     FabricIndex: 2
[1660064885525] [90390:8955520] CHIP: [TOO]    }
```

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 1]
```diff
@@ -350,6 +350,7 @@ class OpCredsFabricTableDelegate : public chip::FabricTable::Delegate
     // Gets called when a fabric is about to be deleted
     void FabricWillBeRemoved(const FabricTable & fabricTable, FabricIndex fabricIndex) override
     {
+        ChipLogError(Zcl, "\n\nLeave event for fabric index: %u\n", fabricIndex);
```
Comment (Damian-Nordic) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:353]: Looks like a leftover from debugging session.

**Review by Damian-Nordic — APPROVED** [review]

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:353]: Er, yes, good catch!

**Review by tcarmelveilleux — APPROVED** [review]
