### PR TITLE
Fix type conversion error in BitFlags Clear

### LINKED ISSUE #30679: [Trivial] BitFlags Clear function fails on type conversion
### Type

Other

### Explanation
https://github.com/project-chip/connectedhomeip/actions/runs/7008674355/job/19065470504?pr=30562

```
INFO    ../../examples/all-clusters-app/asr/third_party/connectedhomeip/src/lib/support/BitFlags.h: In instantiation of 'chip::BitFlags<FlagsEnum, StorageType>& chip::BitFlags<FlagsEnum, StorageType>::Clear(const chip::BitFlags<FlagsEnum, StorageType>&) [with FlagsEnum = chip::app::Clusters::BooleanSensorConfiguration::AlarmModeBitmap; StorageType = unsigned char]':
INFO    ../../examples/all-clusters-app/asr/third_party/connectedhomeip/src/app/clusters/boolean-sensor-configuration-server/boolean-sensor-configuration-server.cpp:212:29:   required from here
INFO    ../../examples/all-clusters-app/asr/third_party/connectedhomeip/src/lib/support/BitFlags.h:105:16: error: conversion from 'int' to 'unsigned char' may change value [-Werror=conversion]
INFO      105 |         mValue &= ~other.mValue;
INFO          |         ~~~~~~~^~~~~~~~~~~~~~~~
INFO    cc1plus: error: unrecognized command line option '-Wno-unknown-warning-option' [-Werror]
```

### Platform

all

### Platform Version(s)

8f76c06231aebbf5e5d09a00b7b5887c4a8f5bf6

### Testing

CI tested

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by fessehaeve**
fixes #30679

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

File: src/lib/support/BitFlags.h [hunk 1]
```diff
@@ -102,7 +102,7 @@ class BitFlags
      */
     BitFlags & Clear(const BitFlags & other)
     {
-        mValue &= ~other.mValue;
+        mValue &= static_cast<IntegerType>(~static_cast<IntegerType>(other.mValue));
```
Comment (arkq) [inline src/lib/support/BitFlags.h:105]: Is there a reason why you've used `static_cast` twice?

Comment (Damian-Nordic) [inline src/lib/support/BitFlags.h:105]: Is the inner cast needed? `mValue` is already `IntegerType/StorageType`.

**Review by Damian-Nordic — APPROVED** [review]

File: src/lib/support/BitFlags.h (hunk 1 above)
Comment (fessehaeve) [reply src/lib/support/BitFlags.h:105]: Right, I think only the outer cast is needed. This was not failing on my machine, only on CI and the only way to test for me was by pushing the code. So I went with "better copy a tested code" from the next Clear() on line 114.

Comment (fessehaeve) [reply src/lib/support/BitFlags.h:105]: https://github.com/project-chip/connectedhomeip/pull/30680#discussion_r1407820657

Comment (andy31415) [reply src/lib/support/BitFlags.h:105]: Even something like:

```cpp
void TestClear(nlTestSuite * inSuite, void * inContext)
{
    BitMask<TestEnum> mask1;
    BitMask<TestEnum> mask2;

    mask1.Set(TestEnum::kBit_0);
    mask1.Set(TestEnum::kBits_1_2);
    mask1.Set(TestEnum::kBits_High8);

    mask2.set(TestEnum::kBits_1_2);
    mask1.Clear(mask2);

    NL_TEST_ASSERT(inSuite, mask.Raw() == 0xFF01);
}
```

in TestBitMask seems to trigger the error and could be used as a test.

Comment (fessehaeve) [reply src/lib/support/BitFlags.h:105]: @andy31415 have a look at https://github.com/project-chip/connectedhomeip/pull/30689

Comment (andy31415) [reply src/lib/support/BitFlags.h:105]: That change should be part of this PR - we should commit code with tests together.

Comment (fessehaeve) [reply src/lib/support/BitFlags.h:105]: Ah, ok. Will update it.

**Comment by fessehaeve** [comment]
@andy31415 I've added the test here.

File: src/lib/support/BitFlags.h (hunk 1 above)
Comment (bzbarsky-apple) [inline src/lib/support/BitFlags.h:105]: This is probably not right.  The right thing is:
```
mValue = static_cast<IntegerType>(mValue & ~other.mValue);
```
or so.  Because using `&=` causes the result of the `&` (which may have been promoted to a different type) to be assigned to mValue...

Comment (andy31415) [reply src/lib/support/BitFlags.h:105]: could you provide a test showing this behaviour?

We relied a lot on unit tests to prove that bitflags works for us as expected.

Comment (bzbarsky-apple) [reply src/lib/support/BitFlags.h:105]: It _works_ correctly.  When it compiles.  It fails to compile on some compilers, I expect.  Depending on optimization settings and the like.

Comment (andy31415) [reply src/lib/support/BitFlags.h:105]: Can we have a compile variant test for this? When this was fixed, we added a unit test that validated we compile.
