### PR TITLE
[IM] Make CommandHandler::AddResponseData atomic

### LINKED ISSUE #15685: Fix error-handling around AddResponseData
#### Problem
Right now we have various code that does:
1. Call CommandHandler::AddResponseData
2. If that fails add an error status.

But if AddResponseData failed the TLV is going to be in some broken state, so this error-handling code is just wrong.

 #### Proposed Solution
Move adding on error status into AddResponseData, remove it from all consumers.

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem

Fixes #15685 

CommandHandler::AddResponseData is not atomic, then we cannot encode status since the backed buffer might be corrupted and we are in a wrong state.

#### Change overview
- Adds `ResetResponse`
- Make AddResponseData atomic
- Add AddResponseDataOrFailureStatus

#### Testing
- Adds `TestCommandHandlerCommandEncodeFailure`, and `TestCommandHandlerCommandEncodeExternalFailure`

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]

File: src/app/CommandHandler.cpp [hunk 1]
```diff
@@ -540,6 +540,17 @@ CHIP_ERROR CommandHandler::FinishStatus()
     return CHIP_NO_ERROR;
 }
 
+CHIP_ERROR CommandHandler::ResetResponse()
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.cpp:543]: This does not look right to me.  What if we have multiple command responses we are trying to encode?  This is going to lose the already-encoded ones if a later one fails to encode, no?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/CommandHandler.cpp (hunk 1 above)
Comment (erjiaqing) [reply src/app/CommandHandler.cpp]: We only support one command in a transactions for now, so this won't be an issue.

Changed ResetResponse to RollbackResponse to support multiple commands in the future.

Comment (bzbarsky-apple) [reply src/app/CommandHandler.cpp]: > We only support one command in a transactions for now

That is ... not true.  We absolutely support multiple commands.  See `CommandHandler::ProcessInvokeRequest`:
```
    while (CHIP_NO_ERROR == (err = invokeRequestsReader.Next()))
    {
        CommandDataIB::Parser commandData;
        ReturnErrorOnFailure(commandData.Init(invokeRequestsReader));
...
            ReturnErrorOnFailure(ProcessCommandDataIB(commandData));
```

Comment (mrjerryjohns) [reply src/app/CommandHandler.cpp]: We should nix that bit of logic and align the entirety of the code base against the expectations for 1.0, which is '1 command in a given invoke interaction'.

Comment (erjiaqing) [reply src/app/CommandHandler.cpp]: PR: https://github.com/project-chip/connectedhomeip/pull/16338

The PR above should not conflict with this PR, and I think these two PRs can be merged in parallel.

Comment (erjiaqing) [reply src/app/CommandHandler.cpp]: #16338 is merged so this PR should be ready now.

**Comment by andy31415** [comment]
@bzbarsky-apple - are your comments addressed? The comment history seems to indicate that.

**Comment by bzbarsky-apple** [comment]
> @bzbarsky-apple - are your comments addressed? 

Will review tomorrow.

File: examples/ota-provider-app/ota-provider-common/OTAProviderExample.cpp [hunk 2]
```diff
@@ -282,8 +282,7 @@ CHIP_ERROR OTAProviderExample::SendQueryImageResponse(chip::app::CommandHandler
         response.metadataForRequestor.Emplace(chip::ByteSpan());
     }
 
-    ReturnErrorOnFailure(commandObj->AddResponseData(commandPath, response));
-
+    VerifyOrReturnError(commandObj->AddResponse(commandPath, response) == CHIP_NO_ERROR, EMBER_ZCL_STATUS_FAILURE);
```
Comment (bzbarsky-apple) [inline examples/ota-provider-app/ota-provider-common/OTAProviderExample.cpp:285]: So what happens in practice is that the caller of this method will see the error and try to AddStatus on the commandObj.  Which will presumably just fail again, right?

Would it make sense to just have AddResponse return void to avoid that problem?  If we really feel like we need to expose the fact that AddResponse failed, we should audit all AddResponse callers to make sure they don't try to AddStatus after an AddResponse failure.

A followup for addressing this, by either audit or changing the signature, is best, as long as we make sure it happens... and we would need to very carefully review any future AddResponse code if we keep the current signature.

File: examples/ota-provider-app/ota-provider-common/OTAProviderExample.cpp [hunk 3]
```diff
@@ -390,7 +389,7 @@ EmberAfStatus OTAProviderExample::HandleApplyUpdateRequest(chip::app::CommandHan
     // Reset back to success case for subsequent uses
     mUpdateAction = OTAApplyUpdateAction::kProceed;
 
-    VerifyOrReturnError(commandObj->AddResponseData(commandPath, response) == CHIP_NO_ERROR, EMBER_ZCL_STATUS_FAILURE);
+    VerifyOrReturnError(commandObj->AddResponse(commandPath, response) == CHIP_NO_ERROR, EMBER_ZCL_STATUS_FAILURE);
```
Comment (bzbarsky-apple) [inline examples/ota-provider-app/ota-provider-common/OTAProviderExample.cpp:392]: Again, caller ends up doing AddStatus.

File: src/app/CommandHandler.cpp [hunk 4]
```diff
@@ -550,6 +553,18 @@ CHIP_ERROR CommandHandler::FinishStatus()
     return CHIP_NO_ERROR;
 }
 
+CHIP_ERROR CommandHandler::RollbackResponse()
+{
+    VerifyOrReturnError(mState == State::Idle || mState == State::AddedCommand || mState == State::AddingCommand,
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.cpp:558]: I feel like we should have a new state for "checkpointed our builder, but did not complete PrepareStatus/PrepareCommand" and check for that state, not Idle, here.  Followup is OK for this change.

Comment (bzbarsky-apple) [inline src/app/CommandHandler.cpp:558]: Why would we ever want to support rollback in the AddedCommand state?  I don't think we should....  At that point we have successfully encoded a response, no?

File: src/app/CommandHandler.h [hunk 5]
```diff
@@ -162,6 +162,11 @@ class CommandHandler
     TLV::TLVWriter * GetCommandDataIBTLVWriter();
     FabricIndex GetAccessingFabricIndex() const;
 
+    /**
+     * Rollback the state to before encoding the current ResponseData (before calling PrepareCommand / PrepareStatus)
+     */
+    CHIP_ERROR RollbackResponse();
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.h:168]: Should this really be a public API?  When would this be used in practice as a public API?

File: src/app/CommandHandler.h [hunk 6]
```diff
@@ -175,13 +180,38 @@ class CommandHandler
     template <typename CommandData>
     CHIP_ERROR AddResponseData(const ConcreteCommandPath & aRequestCommandPath, const CommandData & aData)
     {
-        ConcreteCommandPath path = { aRequestCommandPath.mEndpointId, aRequestCommandPath.mClusterId, CommandData::GetCommandId() };
-        ReturnErrorOnFailure(PrepareCommand(path, false));
-        TLV::TLVWriter * writer = GetCommandDataIBTLVWriter();
-        VerifyOrReturnError(writer != nullptr, CHIP_ERROR_INCORRECT_STATE);
-        ReturnErrorOnFailure(DataModel::Encode(*writer, TLV::ContextTag(to_underlying(CommandDataIB::Tag::kData)), aData));
+        // We should not encode anything when we are not in the correct state, the user must be using CommandHandler incorrectly.
+        VerifyOrReturnError(mState == State::Idle, CHIP_ERROR_INCORRECT_STATE);
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.h:184]: This check is just to avoid calling `RollbackResponse` when we're in the wrong state (because TryAddResponseData will fail in non-idle state)?

But why bother?   RollbackResponse will just end up failing in that state, which is fine.  And we should try to minimize the amount of inlined code here; the codesize increase from this PR is quite significant...

File: src/app/CommandHandler.h [hunk 7]
```diff
@@ -175,13 +180,38 @@ class CommandHandler
...
 
-        return FinishCommand(/* aEndDataStruct = */ false);
+        CHIP_ERROR err = TryAddResponseData(aRequestCommandPath, aData);
+        if (err != CHIP_NO_ERROR)
+        {
+            // We have verified the state above, so this call must success since we must be one of the state required by
+            // ResetResponse.
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.h:190]:
```suggestion
            // We have verified the state above, so this call must succeed since we must be in one of the states required by
            // RollbackResponse.
```

File: src/app/CommandHandler.h [hunk 8]
```diff
@@ -175,13 +180,38 @@ class CommandHandler
...
+            RollbackResponse();
+        }
+        return err;
+    }
+
+    /**
+     * API for adding a response, i.e. I will try to encode a data response (response command), if it failed to encode the response
+     * data, it will encode Protocols::InteractionModel::Status::Failure status code instead. The template parameter T is generally
+     * expected to be a ClusterName::Commands::CommandName::Type struct, but any object that can be encoded using the
+     * DataModel::Encode machinery and exposes the right command id will work.
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.h:200]:
```suggestion
     * API for adding a response.  This will try to encode a data response
     * (response command), and if that fails will encode a a
     * Protocols::InteractionModel::Status::Failure status response instead.
     *
     * The template parameter T is generally expected to be a
     * ClusterName::Commands::CommandName::Type struct, but any object that can
     * be encoded using the DataModel::Encode machinery and exposes the right
     * command id will work.
```

File: src/app/CommandHandler.h [hunk 9]
```diff
@@ -270,6 +300,28 @@ class CommandHandler
     CHIP_ERROR AddStatusInternal(const ConcreteCommandPath & aCommandPath, const Protocols::InteractionModel::Status aStatus,
                                  const Optional<ClusterStatus> & aClusterStatus);
 
+    /**
+     * Adds a data response.  The template parameter T is generally
+     * expected to be a ClusterName::Commands::CommandName::Type struct, but any
+     * object that can be encoded using the DataModel::Encode machinery and
+     * exposes the right command id will work.
+     *
+     * @param [in] aRequestCommandPath the concrete path of the command we are
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.h:309]:
```suggestion
     *
     * If this function fails, it may leave our TLV buffer in an inconsistent
     * state.  Callers should snapshot as needed before calling this function,
     * and roll back as needed afterward.
     *
     * @param [in] aRequestCommandPath the concrete path of the command we are
```

File: src/app/CommandHandler.cpp [hunk 10]
```diff
@@ -522,6 +524,7 @@ CHIP_ERROR CommandHandler::FinishCommand(bool aStartDataStruct)
 CHIP_ERROR CommandHandler::PrepareStatus(const ConcreteCommandPath & aCommandPath)
 {
     ReturnErrorOnFailure(AllocateBuffer());
+    mInvokeResponseBuilder.Checkpoint(mBackupWriter);
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.cpp:527]: But nothing in AddStatus rolls back, right?  Why are we checkpointing here?

File: src/app/clusters/general-commissioning-server/general-commissioning-server.cpp [hunk 11]
```diff
@@ -149,12 +149,12 @@ bool emberAfGeneralCommissioningClusterArmFailSafeCallback(app::CommandHandler *
         CheckSuccess(failSafeContext.ArmFailSafe(accessingFabricIndex, System::Clock::Seconds16(commandData.expiryLengthSeconds)),
                      Failure);
         response.errorCode = CommissioningError::kOk;
-        CheckSuccess(commandObj->AddResponseData(commandPath, response), Failure);
+        CheckSuccess(commandObj->AddResponse(commandPath, response), Failure);
```
Comment (bzbarsky-apple) [inline src/app/clusters/general-commissioning-server/general-commissioning-server.cpp:152]: The CheckSuccess stuff here does not make sense, in the same way that the OTA bits that manually send a status on failure don't make sense.  This one, though, we should fix as part of this PR (by just dropping this CheckSuccess stuff), because otherwise the codesize measurements are fairly meaningless.

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp [hunk 12]
```diff
@@ -438,7 +438,7 @@ bool emberAfGroupKeyManagementClusterKeySetReadCallback(
     }
     response.groupKeySet.epochKey2.SetNull();
 
-    CHIP_ERROR err = commandObj->AddResponseData(commandPath, response);
+    CHIP_ERROR err = commandObj->AddResponse(commandPath, response);
     if (CHIP_NO_ERROR != err)
```
Comment (bzbarsky-apple) [inline src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:442]: This is going to add a status again on failure, which again does not make sense.  Please remove the emberAfSendImmediateDefaultResponse call.

File: src/app/clusters/groups-server/groups-server.cpp [hunk 13]
```diff
@@ -148,7 +148,7 @@ bool emberAfGroupsClusterAddGroupCallback(app::CommandHandler * commandObj, cons
 
     response.groupId = commandData.groupId;
     response.status  = GroupAdd(fabricIndex, commandPath.mEndpointId, commandData.groupId, commandData.groupName);
-    err              = commandObj->AddResponseData(commandPath, response);
+    err              = commandObj->AddResponse(commandPath, response);
     if (CHIP_NO_ERROR != err)
```
Comment (bzbarsky-apple) [inline src/app/clusters/groups-server/groups-server.cpp:152]: This is going to try to send a status response on failure.  Please remove the emberAfSendImmediateDefaultResponse call.

File: src/app/clusters/groups-server/groups-server.cpp [hunk 14]
```diff
@@ -185,7 +185,7 @@ bool emberAfGroupsClusterViewGroupCallback(app::CommandHandler * commandObj, con
 exit:
     response.groupId = groupId;
     response.status  = status;
-    err              = commandObj->AddResponseData(commandPath, response);
+    err              = commandObj->AddResponse(commandPath, response);
     if (CHIP_NO_ERROR != err)
```
Comment (bzbarsky-apple) [inline src/app/clusters/groups-server/groups-server.cpp:189]: Please remove the emberAfSendImmediateDefaultResponse call.

File: src/app/clusters/groups-server/groups-server.cpp [hunk 15]
```diff
@@ -289,7 +289,7 @@ bool emberAfGroupsClusterGetGroupMembershipCallback(app::CommandHandler * comman
         iter = provider->IterateEndpoints(fabricIndex);
         VerifyOrExit(nullptr != iter, status = EMBER_ZCL_STATUS_FAILURE);
 
-        err = commandObj->AddResponseData(commandPath, GroupMembershipResponse(commandData, commandPath.mEndpointId, iter));
+        err = commandObj->AddResponse(commandPath, GroupMembershipResponse(commandData, commandPath.mEndpointId, iter));
         iter->Release();
         status = (CHIP_NO_ERROR == err) ? EMBER_ZCL_STATUS_SUCCESS : EMBER_ZCL_STATUS_FAILURE;
```
Comment (bzbarsky-apple) [inline src/app/clusters/groups-server/groups-server.cpp:294]: This is going to try to emberAfSendImmediateDefaultResponse in the exit block.  But we actually do want that for exits from earlier in this function....  Followup for making this codepath sane is fine, or you could make it sane here (e.g. by setting status to success no matter what AddResponse returned, or just logging and returning here instead of falling through to the exit block, or something.

File: src/app/clusters/groups-server/groups-server.cpp [hunk 16]
```diff
@@ -324,7 +324,7 @@ bool emberAfGroupsClusterRemoveGroupCallback(app::CommandHandler * commandObj, c
     response.groupId = commandData.groupId;
     response.status  = GroupRemove(fabricIndex, commandPath.mEndpointId, commandData.groupId);
 
-    err = commandObj->AddResponseData(commandPath, response);
+    err = commandObj->AddResponse(commandPath, response);
     if (CHIP_NO_ERROR != err)
```
Comment (bzbarsky-apple) [inline src/app/clusters/groups-server/groups-server.cpp:328]: Please take out the emberAfSendImmediateDefaultResponse call.

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 17]
```diff
@@ -774,7 +774,7 @@ bool emberAfOperationalCredentialsClusterCertificateChainRequestCallback(
     }
 
     response.certificate = derBufSpan;
-    SuccessOrExit(err = commandObj->AddResponseData(commandPath, response));
+    SuccessOrExit(err = commandObj->AddResponse(commandPath, response));
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:777]: This is going to emberAfSendImmediateDefaultResponse in the exit block...  Again, this is actually needed for the earlier failures in this function, but we should not do it if AddResponse failed.  Followup is OK for addressing this.

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 18]
```diff
@@ -834,7 +834,7 @@ bool emberAfOperationalCredentialsClusterAttestationRequestCallback(app::Command
 
         response.attestationElements = attestationElementsSpan;
         response.signature           = signatureSpan;
-        SuccessOrExit(err = commandObj->AddResponseData(commandPath, response));
+        SuccessOrExit(err = commandObj->AddResponse(commandPath, response));
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:837]: Again, will emberAfSendImmediateDefaultResponse in exit block.  Followup OK.

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 19]
```diff
@@ -922,7 +922,7 @@ bool emberAfOperationalCredentialsClusterCSRRequestCallback(app::CommandHandler
 
         response.NOCSRElements        = nocsrElementsSpan;
         response.attestationSignature = signatureSpan;
-        SuccessOrExit(err = commandObj->AddResponseData(commandPath, response));
+        SuccessOrExit(err = commandObj->AddResponse(commandPath, response));
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:925]: Again, will emberAfSendImmediateDefaultResponse in the exit block.  Followup OK.

File: src/app/clusters/test-cluster-server/test-cluster-server.cpp [hunk 20]
```diff
@@ -750,7 +750,7 @@ static bool SendBooleanResponse(CommandHandler * commandObj, const ConcreteComma
 {
     Commands::BooleanResponse::Type response;
     response.value = value;
-    CHIP_ERROR err = commandObj->AddResponseData(commandPath, response);
+    CHIP_ERROR err = commandObj->AddResponse(commandPath, response);
     if (err != CHIP_NO_ERROR)
     {
         commandObj->AddStatus(commandPath, Protocols::InteractionModel::Status::Failure);
```
Comment (bzbarsky-apple) [inline src/app/clusters/test-cluster-server/test-cluster-server.cpp:756]: This makes no sense now.  Please remove this AddStatus.

File: src/app/clusters/test-cluster-server/test-cluster-server.cpp [hunk 21]
```diff
@@ -923,7 +923,7 @@ bool emberAfTestClusterClusterTestListInt8UReverseRequestCallback(
         Commands::TestListInt8UReverseResponse::Type responseData;
         if (count == 0)
         {
-            SuccessOrExit(commandObj->AddResponseData(commandPath, responseData));
+            SuccessOrExit(commandObj->AddResponse(commandPath, responseData));
```
Comment (bzbarsky-apple) [inline src/app/clusters/test-cluster-server/test-cluster-server.cpp:926]: The exit block here calls emberAfSendImmediateDefaultResponse.  Followup to fix the logic here is fine.

File: src/app/clusters/test-cluster-server/test-cluster-server.cpp [hunk 22]
```diff
@@ -953,7 +953,7 @@ bool emberAfTestClusterClusterTestEnumsRequestCallback(CommandHandler * commandO
     response.arg1 = commandData.arg1;
     response.arg2 = commandData.arg2;
 
-    CHIP_ERROR err = commandObj->AddResponseData(commandPath, response);
+    CHIP_ERROR err = commandObj->AddResponse(commandPath, response);
     if (err != CHIP_NO_ERROR)
     {
         emberAfSendImmediateDefaultResponse(EMBER_ZCL_STATUS_FAILURE);
```
Comment (bzbarsky-apple) [inline src/app/clusters/test-cluster-server/test-cluster-server.cpp:959]: This makes no sense now.  Please remove the emberAfSendImmediateDefaultResponse

File: src/app/clusters/test-cluster-server/test-cluster-server.cpp [hunk 23]
```diff
@@ -979,7 +979,7 @@ bool emberAfTestClusterClusterTestNullableOptionalRequestCallback(
         response.originalValue.Emplace(commandData.arg1.Value());
     }
 
-    CHIP_ERROR err = commandObj->AddResponseData(commandPath, response);
+    CHIP_ERROR err = commandObj->AddResponse(commandPath, response);
     if (err != CHIP_NO_ERROR)
     {
         emberAfSendImmediateDefaultResponse(EMBER_ZCL_STATUS_FAILURE);
```
Comment (bzbarsky-apple) [inline src/app/clusters/test-cluster-server/test-cluster-server.cpp:985]: This makes no sense now. Please remove the emberAfSendImmediateDefaultResponse

File: src/app/clusters/test-cluster-server/test-cluster-server.cpp [hunk 24]
```diff
@@ -1000,7 +1000,7 @@ bool emberAfTestClusterClusterSimpleStructEchoRequestCallback(CommandHandler * c
     response.arg1.g = commandData.arg1.g;
     response.arg1.h = commandData.arg1.h;
 
-    CHIP_ERROR err = commandObj->AddResponseData(commandPath, response);
+    CHIP_ERROR err = commandObj->AddResponse(commandPath, response);
     if (err != CHIP_NO_ERROR)
     {
         emberAfSendImmediateDefaultResponse(EMBER_ZCL_STATUS_FAILURE);
```
Comment (bzbarsky-apple) [inline src/app/clusters/test-cluster-server/test-cluster-server.cpp:1006]: This makes no sense now. Please remove the emberAfSendImmediateDefaultResponse

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/CommandHandler.cpp (hunk 4 above)
Comment (erjiaqing) [reply src/app/CommandHandler.cpp:558]: I think we don;t need such state, but we should change the order of checking and setting states in PrepareStatus

File: src/app/CommandHandler.h (hunk 5 above)
Comment (erjiaqing) [reply src/app/CommandHandler.h:168]: This should be a private API.

File: examples/ota-provider-app/ota-provider-common/OTAProviderExample.cpp (hunk 2 above)
Comment (erjiaqing) [reply examples/ota-provider-app/ota-provider-common/OTAProviderExample.cpp]: Made it a void function now, however, I also replaced return to LogErrorOnFailure since the users are also logging the error codes.

File: examples/ota-provider-app/ota-provider-common/OTAProviderExample.cpp (hunk 3 above)
Comment (erjiaqing) [reply examples/ota-provider-app/ota-provider-common/OTAProviderExample.cpp]: Done

File: src/app/CommandHandler.cpp (hunk 4 above)
Comment (erjiaqing) [reply src/app/CommandHandler.cpp]: Seems so, we don't have to rollback until we want to support multiple commands, but I guess we need to do some large refactor. So removed it.

File: src/app/CommandHandler.h (hunk 6 above)
Comment (erjiaqing) [reply src/app/CommandHandler.h]: Makes sense.

File: src/app/CommandHandler.h (hunk 9 above)
Comment (erjiaqing) [reply src/app/CommandHandler.h:310]: Resolved, but not detected by github.

File: src/app/CommandHandler.cpp (hunk 10 above)
Comment (erjiaqing) [reply src/app/CommandHandler.cpp]: Yes, no need to add a checkpoint here as long as the Rollback is a private function.
I added this to make PrepareStatus and PrepareCommand a bit more consistent.

File: src/app/clusters/general-commissioning-server/general-commissioning-server.cpp (hunk 11 above)
Comment (erjiaqing) [reply src/app/clusters/general-commissioning-server/general-commissioning-server.cpp]: Removed.

File: src/app/clusters/test-cluster-server/test-cluster-server.cpp (hunk 21 above)
Comment (erjiaqing) [reply src/app/clusters/test-cluster-server/test-cluster-server.cpp]: The exit block should not be changed, but SuccessOrExit is not necessary here.

File: src/app/CommandHandler.cpp [hunk 25]
```diff
@@ -550,6 +554,18 @@ CHIP_ERROR CommandHandler::FinishStatus()
     return CHIP_NO_ERROR;
 }
 
+CHIP_ERROR CommandHandler::RollbackResponse()
+{
+    VerifyOrReturnError(mState == State::Idle || mState == State::Preparing || mState == State::AddingCommand,
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.cpp:559]: When would RollbackResponse happen in the Idle state?  I guess if `AllocateBuffer` fails?  But then `mBackupWriter` wouldn't be in a reasonable state anyway, so we shouldn't use it in that case.

File: src/app/CommandHandler.h [hunk 26]
```diff
@@ -175,13 +175,40 @@ class CommandHandler
...
-        ConcreteCommandPath path = { aRequestCommandPath.mEndpointId, aRequestCommandPath.mClusterId, CommandData::GetCommandId() };
-        ReturnErrorOnFailure(PrepareCommand(path, false));
-        TLV::TLVWriter * writer = GetCommandDataIBTLVWriter();
-        VerifyOrReturnError(writer != nullptr, CHIP_ERROR_INCORRECT_STATE);
-        ReturnErrorOnFailure(DataModel::Encode(*writer, TLV::ContextTag(to_underlying(CommandDataIB::Tag::kData)), aData));
+        // TryAddResponseData will ensure we are in the correct state when calling AddResponseData.
+        CHIP_ERROR err = TryAddResponseData(aRequestCommandPath, aData);
+        if (err != CHIP_NO_ERROR)
+        {
+            // We have verified the state above, so this call must succeed since we must be in one of the states required by
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.h:182]: We are no longer verifying the state above.  We just don't care about the failure if we are not in one of those states.

File: src/app/CommandHandler.h [hunk 27]
```diff
@@ -175,13 +175,40 @@ class CommandHandler
...
-        return FinishCommand(/* aEndDataStruct = */ false);
+    /**
+     * API for adding a response.  This will try to encode a data response (response command), and if that fails will encode a a
+     * Protocols::InteractionModel::Status::Failure status response instead.
+     *
+     * The template parameter T is generally expected to be a ClusterName::Commands::CommandName::Type struct, but any object that
+     * can be encoded using the DataModel::Encode machinery and exposes the right command id will work.
+     *
+     * Since the function will call AddStatus when failed to encode the data, it cannot send any response when it failed to encode a
+     * status code since another AddStatus call will also fail. Users can check the log when thry failed to receive a response.
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.h:197]:
```suggestion
     * Since the function will call AddStatus when it fails to encode the data, it cannot send any response when it fails to encode a
     * status code since another AddStatus call will also fail. The error from AddStatus will just be logged.
```

File: src/app/CommandHandler.h [hunk 28]
```diff
@@ -175,13 +175,40 @@ class CommandHandler
...
+     * @param [in] aData the data for the response.
+     */
+    template <typename CommandData>
+    void AddResponse(const ConcreteCommandPath & aRequestCommandPath, const CommandData & aData)
+    {
+        CHIP_ERROR err = CHIP_NO_ERROR;
+        LogErrorOnFailure(err = AddResponseData(aRequestCommandPath, aData));
+        if (err != CHIP_NO_ERROR)
+        {
+            LogErrorOnFailure(AddStatus(aRequestCommandPath, Protocols::InteractionModel::Status::Failure));
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.h:210]: Please don't use `LogErrorOnFailure` in device code: it uses `__FILE__` and will lead to a lot of bloat.  Do this instead:
```suggestion
            err = AddStatus(aRequestCommandPath, Protocols::InteractionModel::Status::Failure);
            if (err != CHIP_NO_ERROR)
            {
                ChipLogError(DataManagement, "Failed to encode status: %" CHIP_ERROR_FORMAT, err.Format());
            }
```
but better yet for bloat reduction would be for that log to be in non-inlined code (e.g. have a void-returning `AddStatusOrLog` function).

File: src/app/clusters/groups-server/groups-server.cpp [hunk 29]
```diff
@@ -284,14 +273,12 @@ bool emberAfGroupsClusterGetGroupMembershipCallback(app::CommandHandler * comman
...
         GroupDataProvider::EndpointIterator * iter = nullptr;
-        CHIP_ERROR err                             = CHIP_NO_ERROR;
 
         iter = provider->IterateEndpoints(fabricIndex);
         VerifyOrExit(nullptr != iter, status = EMBER_ZCL_STATUS_FAILURE);
 
-        err = commandObj->AddResponseData(commandPath, GroupMembershipResponse(commandData, commandPath.mEndpointId, iter));
+        commandObj->AddResponse(commandPath, GroupMembershipResponse(commandData, commandPath.mEndpointId, iter));
         iter->Release();
-        status = (CHIP_NO_ERROR == err) ? EMBER_ZCL_STATUS_SUCCESS : EMBER_ZCL_STATUS_FAILURE;
```
Comment (bzbarsky-apple) [inline src/app/clusters/groups-server/groups-server.cpp:294]: This still needs to set status to EMBER_ZCL_STATUS_SUCCESS, no?

Comment (erjiaqing) [reply src/app/clusters/groups-server/groups-server.cpp:294]: Yes, we should set status here.
