### PR TITLE
[EFR apps] Fix issues building and running apps for a EFRMG21 based board

### LINKED ISSUE #2959: EFR32MG21 MCUs Hardfault after starting FreeRtos Scheduler
#### Problem
Running a EFR app on a EFR32MG21 board hard fault when starting FreeRTOS scheduler. 
Doesn't occure with MG12 familly

 #### Proposed Solution
Must be a configuration issue that varies from EFRMG12 (Cortex-M4) and MG21 (Cortex-M33)

### PR DESCRIPTION
**Pull request by jmartinez-silabs**
#### Problem
MCUs Hardfault after starting FreeRTOS Scheduler
Building for BOARD4180A fails because of undefined clock name 

 #### Summary of Changes
initOtSysEFR Clock tree was set to MG12 architecture. MG21 has different clock system and names
Add a define for the EFR family in use to if def those tree
Fix a freeRTOS hard fault with MG21 family, needs a different prio_group config for cortex-m3

fixes #2959

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

File: examples/platform/efr32/init_otSystem.c [hunk 1]
```diff
@@ -65,26 +65,36 @@ void halInitChipSpecific(void);
...
+    SubPrio = 1;
+#endif
 
     __disable_irq();
 
 #undef FIXED_EXCEPTION
 #define FIXED_EXCEPTION(vectorNumber, functionName, deviceIrqn, deviceIrqHandler)
 #define EXCEPTION(vectorNumber, functionName, deviceIrqn, deviceIrqHandler, priorityLevel, subpriority)                            \
-    NVIC_SetPriority(deviceIrqn, NVIC_EncodePriority(PRIGROUP_POSITION, priorityLevel, subpriority));
+    NVIC_SetPriority(deviceIrqn, NVIC_EncodePriority(PRIGROUP_POSITION - SubPrio, priorityLevel, subpriority));
```
Comment (bzbarsky-apple) [inline examples/platform/efr32/init_otSystem.c:80]: Should we store `PRIGROUP_POSITION - SubPrio` in a variable instead of duplicating it?

File: examples/platform/efr32/init_otSystem.c [hunk 2]
```diff
@@ -65,26 +65,36 @@ void halInitChipSpecific(void);
...
     initLCD();
 #endif
     BSP_Init(BSP_INIT_BCC);
 
+#if defined(EFR32MG12)
     CMU_ClockSelectSet(cmuClock_LFE, cmuSelect_LFRCO);
     CMU_ClockEnable(cmuClock_CORELE, true);
+#elif defined(EFR32MG21)
+    CMU_OscillatorEnable(cmuOsc_LFRCO, true, true);
+#endif /* EFR32 PLATFORM */
```
Comment (bzbarsky-apple) [inline examples/platform/efr32/init_otSystem.c:97]: Should there be an `#else #error` here in case some other platform appears, so they know they need to adjust this code?

File: examples/platform/efr32/init_otSystem.c [hunk 3]
```diff
@@ -102,6 +112,8 @@ void initOtSysEFR(void)
     efr32RadioInit();
     efr32AlarmInit();
     efr32MiscInit();
+#if defined(EFR32MG12)
     efr32RandomInit();
```
Comment (bzbarsky-apple) [inline examples/platform/efr32/init_otSystem.c:116]: Is this function not available on EFR32MG21?   If so, should this perhaps be `#ifndef EFR32MG21`

File: examples/platform/efr32/init_otSystem.c (hunk 2 above)
Comment (jmartinez-silabs) [reply examples/platform/efr32/init_otSystem.c:97]: Sure good idea, Will do

File: examples/platform/efr32/init_otSystem.c (hunk 3 above)
Comment (jmartinez-silabs) [reply examples/platform/efr32/init_otSystem.c:116]: This function doesn't exist for the MG21 it has to do with hardware crypto acceleration inits and the mg21 doesn't have that feature. I will change for ifndef

File: examples/platform/efr32/init_otSystem.c [hunk 4]
```diff
@@ -77,11 +78,12 @@ void initOtSysEFR(void)
 #undef FIXED_EXCEPTION
 #define FIXED_EXCEPTION(vectorNumber, functionName, deviceIrqn, deviceIrqHandler)
 #define EXCEPTION(vectorNumber, functionName, deviceIrqn, deviceIrqHandler, priorityLevel, subpriority)                            \
-    NVIC_SetPriority(deviceIrqn, NVIC_EncodePriority(PRIGROUP_POSITION - SubPrio, priorityLevel, subpriority));
+    PrioGoupPos = PRIGROUP_POSITION - SubPrio;                                                                                     \
```
Comment (bzbarsky-apple) [inline examples/platform/efr32/init_otSystem.c:81]: "PrioGroupPos"?

**Review by bzbarsky-apple — APPROVED** [review]

File: examples/platform/efr32/init_otSystem.c (hunk 4 above)
Comment (jmartinez-silabs) [reply examples/platform/efr32/init_otSystem.c:81]: Priority Group Position ?

**Review by rwalker-apple — APPROVED** [review]

**Review by mspang — APPROVED** [review]
