### PR TITLE
[OTA-R] TC-SU-2.3 OTA-R unable to start new CASE session with OTA-P

### LINKED ISSUE #18484: TC-SU-2.3 OTA-R unable to start new CASE session with OTA-P
#### Problem
An intended fix for timing out a CASE session in SWU was here: https://github.com/project-chip/connectedhomeip/pull/15939
However, it appears the fix is not effective. Even though we see the following in the DUT (OTA-R) logs:

```
I: 1237047 [DMG]Time out! failed to receive invoke command response from Exchange: 4289i
E: 1237048 [SWU]Received QueryImage failure response: 32
E: 1237048 [SWU]CASE session may be invalid, tear down session
```
... subsequent requests to the OTA-P from the OTA-R are still attempting to use the same session ID.

<what's wrong or missing, please include any applicable:
 * expected behavior
If OTA-P is restarted, OTA-R should time out its session and use a new session for subsequent requests.

 * actual behavior
Subsequent requests (even after a timeout) are continuing to attempt to use the same session.

 * steps to reproduce
1. OTA-R makes a request to OTA-P (successful)
2. Restart OTA provider
3. OTA-R makes a request to OTA-P (unsuccessful)
4. OTA-R eventually times out and prints in the log: ` [SWU]CASE session may be invalid, tear down session`
5. OTA-R makes a request to OTA-P (unsuccessful)
6. ...

### PR DESCRIPTION
**Pull request by isiu-apple**
#### Problem

If OTA-P is restarted, OTA-R should time out its session and use a new session for subsequent requests.  OTA-R was still attempting to use the same session ID after timing out with OTA-P (due to OTA-P killed) and therefore subsequent requests to OTA-P when OTA-P is restarted fails.

Fixes: https://github.com/project-chip/connectedhomeip/issues/18484

#### Change overview

Add `OperationalDeviceProxy::Disconnect()` call in `DefaultOTARequestor::DisconnectFromProvider()` to evict the session that we have conclusive evidence for indicating a lack of response from the peer.

#### Testing

1. OTA-R makes a request to OTA-P (successful)
2. Kill OTA provider
3. OTA-R makes a request to OTA-P (unsuccessful)
4. OTA-R eventually times out and prints in the log: [SWU]CASE session may be invalid, tear down session. 
5. Restart OTA provider
7. OTA-R makes a request to OTA-P (successful)

### CODE REVIEW

File: src/app/clusters/ota-requestor/DefaultOTARequestor.cpp [hunk 1]
```diff
@@ -400,7 +400,9 @@ void DefaultOTARequestor::DisconnectFromProvider()
         return;
     }
 
-    mCASESessionManager->ReleaseSession(fabricInfo->GetPeerIdForNode(mProviderLocation.Value().providerNodeID));
+    PeerId peerID = fabricInfo->GetPeerIdForNode(mProviderLocation.Value().providerNodeID);
+    mCASESessionManager->FindExistingSession(peerID)->Disconnect();
+    mCASESessionManager->ReleaseSession(peerID);
```
Comment (mrjerryjohns) [inline src/app/clusters/ota-requestor/DefaultOTARequestor.cpp:405]: So, this fix is fine for now for this PR, but this is not going to play nice with other logic in the system that also interacts with `CASESessionManager` to get an `OperationalDeviceProxy` instance to interact with (e.g Bindings). This is going to cause a use-after-free error, because each entity interacting with `CASESessionManager` assumes they have exclusive ownership, which they don't.

Need to figure out what to do here as a separate issue...

**Review by mrjerryjohns — APPROVED** [review]

File: src/app/clusters/ota-requestor/DefaultOTARequestor.cpp (hunk 1 above)
Comment (mrjerryjohns) [reply src/app/clusters/ota-requestor/DefaultOTARequestor.cpp:405]: Added a [comment](https://github.com/project-chip/connectedhomeip/issues/18609#issuecomment-1132247161) to this issue.

**Review by carol-apple — APPROVED** [review]
