### PR TITLE
[Silabs] [EFR32] Adds translation between spec WiFi Security Types

### LINKED ISSUE #25118: [Platform][Silabs][WIFI] The possible SecurityTypes returned from GetWiFiSecurityType doesn't match the spec.
### Reproduction steps

The Security type from the structure `wfx_wifi_scan_result_t` obtained by the function `wfx_get_ap_info` doesn't match the Matter spec but is assigned as is to the `WiFiNetworkDiagnostics::SecurityTypeEnum`.

```
CHIP_ERROR DiagnosticDataProviderImpl::GetWiFiSecurityType(app::Clusters::WiFiNetworkDiagnostics::SecurityTypeEnum & securityType)
{
    using app::Clusters::WiFiNetworkDiagnostics::SecurityTypeEnum;

    wfx_wifi_scan_result_t ap;
    int32_t err = wfx_get_ap_info(&ap);
    if (err == 0)
    {
        securityType = static_cast<SecurityTypeEnum>(ap.security);
```

The possible values from ap.security are describe by the following enum wfx_sec_t.

```
/* Note that these are same as RSI_security */
typedef enum
{
    WFX_SEC_NONE           = 0,
    WFX_SEC_WPA            = 1,
    WFX_SEC_WPA2           = 2,
    WFX_SEC_WEP            = 3,
    WFX_SEC_WPA_EAP        = 4,
    WFX_SEC_WPA2_EAP       = 5,
    WFX_SEC_WPA_WPA2_MIXED = 6,
    WFX_SEC_WPA_PMK        = 7,
    WFX_SEC_WPA2_PMK       = 8,
    WFX_SEC_WPS_PIN        = 9,
    WFX_SEC_GEN_WPS_PIN    = 10,
    WFX_SEC_PUSH_BTN       = 11,
    WFX_SEC_WPA3           = 11,
} wfx_sec_t;
```

A conversion must be made to respect the possible values of `SecurityTypeEnum`  as described by the spec

image

See "11.14.5.1. SecurityTypeEnum" in the Matter spec for more details.

### Platform

efr32

### Platform Version(s)

_No response_

### Type

Platform validated

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rosahay-silabs**
Fixes #25118 

Encoding the enum provided by driver in scan result callback to CHIP spec based enum, decoding them back to driver based enum on the connect API.

### CODE REVIEW

File: examples/platform/silabs/SiWx917/SiWx917/rsi_if.c [hunk 1]
```diff
@@ -381,21 +380,32 @@ static void wfx_rsi_save_ap_info()
...
+        break;
+    case SME_WEP:
+        wfx_rsi.sec.security = WFX_SEC_WEP;
+        break;
+    case SME_WPA3:
+    case SME_WPA3_TRANSITION:
+        wfx_rsi.sec.security = WFX_SEC_WPA3;
+        break;
+    default:
+        wfx_rsi.sec.security = WFX_SEC_UNSPECIFIED;
```
Comment (mkardous-silabs) [inline examples/platform/silabs/SiWx917/SiWx917/rsi_if.c:408]: It is good form to have a `break` statement even for the default case.

File: examples/platform/silabs/efr32/rs911x/rsi_if.c [hunk 2]
```diff
@@ -450,22 +449,35 @@ static void wfx_rsi_save_ap_info()
...
+        break;
+    case SME_WEP:
+        wfx_rsi.sec.security = WFX_SEC_WEP;
+        break;
+    case SME_WPA3:
+    case SME_WPA3_TRANSITION:
+        wfx_rsi.sec.security = WFX_SEC_WPA3;
+        break;
+    default:
+        wfx_rsi.sec.security = WFX_SEC_UNSPECIFIED;
```
Comment (mkardous-silabs) [inline examples/platform/silabs/efr32/rs911x/rsi_if.c:478]: same comment

**Comment by jmartinez-silabs** [comment]
Wouldn't it have been simpler to just do the conversion in a single location, in the WiFi Diagnostic function
`DiagnosticDataProviderImpl::GetWiFiSecurityType` ?

Converting your `WFX` or `RSI` security enums to the Matter `WiFiNetworkDiagnostics::SecurityTypeEnum` ?

**Review by jmartinez-silabs — COMMENTED** [review]
Wouldn't it be simpler to just do the conversion in a single location, in the WiFi Diagnostic function
DiagnosticDataProviderImpl::GetWiFiSecurityType ?

Converting your WFX or RSI security enums to the Matter WiFiNetworkDiagnostics::SecurityTypeEnum ?

**Comment by rosahay-silabs** [comment]
> Wouldn't it be simpler to just do the conversion in a single location, in the WiFi Diagnostic function DiagnosticDataProviderImpl::GetWiFiSecurityType ?
> 
> Converting your WFX or RSI security enums to the Matter WiFiNetworkDiagnostics::SecurityTypeEnum ?

Yes agreed, but that is something I want to pick up without blocking the spec. We have a task to clean up the code here, including the global variables and functions. Including and not limiting only this, it also includes a proper structure to save AP details which seems to be different for WF200 and RS9116, we can remove quite a few duplicate codes with a clean-up. I will also introduce guard style if statement instead of if-else littered everywhere.

**Comment by rosahay-silabs** [comment]
> Wouldn't it be simpler to just do the conversion in a single location, in the WiFi Diagnostic function DiagnosticDataProviderImpl::GetWiFiSecurityType ?
> 
> Converting your WFX or RSI security enums to the Matter WiFiNetworkDiagnostics::SecurityTypeEnum ?

Yes agreed, but that is something I want to pick up without blocking the spec. We have a task to clean up the code here, including the global variables and functions. Including and not limiting only this, it also includes a proper structure to save AP details which seems to be different for WF200 and RS9116, we can remove quite a few duplicate codes with a clean-up. I will also introduce guard style if statement instead of if-else littered everywhere.

**Comment by jmartinez-silabs** [comment]
ok, I'll approve then so you can continue your clean up

**Review by jmartinez-silabs — APPROVED** [review]

File: examples/platform/silabs/efr32/rs911x/rsi_if.c [hunk 3]
```diff
@@ -435,7 +434,7 @@ void wfx_show_err(char * msg)
  * @return
  *       None
  *******************************************************************************************/
-static void wfx_rsi_save_ap_info()
+static void wfx_rsi_save_ap_info() // transalation
```
Comment (jmeg-sfy) [inline examples/platform/silabs/efr32/rs911x/rsi_if.c:437]:
```suggestion
static void wfx_rsi_save_ap_info() // translation
```

File: examples/platform/silabs/efr32/rs911x/rsi_if.c [hunk 4]
```diff
@@ -450,22 +449,36 @@ static void wfx_rsi_save_ap_info()
...
+        break;
+    case SME_WEP:
+        wfx_rsi.sec.security = WFX_SEC_WEP;
+        break;
+    case SME_WPA3:
+    case SME_WPA3_TRANSITION:
+        wfx_rsi.sec.security = WFX_SEC_WPA3;
+        break;
+    default:
+        wfx_rsi.sec.security = WFX_SEC_UNSPECIFIED;
```
Comment (jmeg-sfy) [inline examples/platform/silabs/efr32/rs911x/rsi_if.c:478]: [SiWx917/rsi_if.c] this is a total duplication of the one from SiWx917 
factorize it !

File: examples/platform/silabs/efr32/rs911x/rsi_if.c [hunk 5]
```diff
@@ -480,13 +493,35 @@ static void wfx_rsi_save_ap_info()
...
+            connect_security_mode = RSI_WPA_WPA2_MIXED;
+            break;
+        case WFX_SEC_WPA3:
+            connect_security_mode = RSI_WPA3;
+            break;
+        case WFX_SEC_NONE:
+            connect_security_mode = RSI_OPEN;
+            break;
+        default:
+            WFX_RSI_LOG("%s: error: unknown security type.");
```
Comment (jmeg-sfy) [inline examples/platform/silabs/efr32/rs911x/rsi_if.c:521]: same pattern same comment ...

**Review by jmeg-sfy — APPROVED** [review]
sound like a bit of factorization improvement is needed 
unless you wish to copy/paste everything again when SiWx918 then SiWx920 comes up....

**Comment by brosahay** [comment]
> sound like a bit of factorization improvement is needed unless you wish to copy/paste everything again when SiWx918 then SiWx920 comes up....

Yes, agreed that we are replicating code for now, and a refactor effort is required. This was done to meet the spec requirement without changing the logic much, the refactor effort will be done in a phased manner since it requires quite a good amount of testing.

File: examples/platform/silabs/efr32/rs911x/rsi_if.c (hunk 4 above)
Comment (rosahay-silabs) [reply examples/platform/silabs/efr32/rs911x/rsi_if.c:478]: It will be taken up as an effort later

File: examples/platform/silabs/efr32/rs911x/rsi_if.c (hunk 5 above)
Comment (rosahay-silabs) [reply examples/platform/silabs/efr32/rs911x/rsi_if.c:521]: It will be taken up as an effort later

File: src/platform/silabs/SiWx917/wifi/wfx_host_events.h [hunk 6]
```diff
@@ -149,28 +148,19 @@ typedef enum
 /* Note that these are same as RSI_security */
```
Comment (bzbarsky-apple) [inline src/platform/silabs/SiWx917/wifi/wfx_host_events.h:148]: Are these in fact still the same as RSI_security?

But also, is there a reason this is not just using the spec-defined enum?

File: src/platform/silabs/efr32/wifi/wfx_host_events.h [hunk 7]
```diff
@@ -274,7 +264,7 @@ typedef enum
 typedef struct wfx_wifi_scan_result
 {
     char ssid[32 + 1];
-    uint8_t security;
+    wfx_sec_t security;
```
Comment (bzbarsky-apple) [inline src/platform/silabs/efr32/wifi/wfx_host_events.h:267]: This does not look right.  For a scan result, the security type is a bitmap, not an enum, in the spec.  See "11.8.5.1. WiFiSecurityBitmap", which is not the same thing as the "11.14.5.1. SecurityTypeEnum" used by network diagnostics. It looks to me like the enums above match the latter, but not the scan result bitmap.

File: src/platform/silabs/SiWx917/wifi/wfx_host_events.h (hunk 6 above)
Comment (rosahay-silabs) [reply src/platform/silabs/SiWx917/wifi/wfx_host_events.h:148]: now, they are not same as `rsi_security`, it was a comment which I plan to clean up during the cleanup activity.

File: src/platform/silabs/efr32/wifi/wfx_host_events.h (hunk 7 above)
Comment (rosahay-silabs) [reply src/platform/silabs/efr32/wifi/wfx_host_events.h:267]: The translation for this is here [src/platform/silabs/NetworkCommissioningWiFiDriver.cpp#L197](https://github.com/project-chip/connectedhomeip/blob/master/src/platform/silabs/NetworkCommissioningWiFiDriver.cpp#L197)

Comment (bzbarsky-apple) [reply src/platform/silabs/efr32/wifi/wfx_host_events.h:267]: I don't see how that can work.  That `ConvertSecuritytype` function expects a _bitmap_ as input (not the bit test it's doing) and converts to a different bitmap.  But `wfx_sec_t` is not a bitmap....
