### PR TITLE
tv-casting-app: Fixes for #24399 and #24400

### LINKED ISSUE #24399: [BUG] iOS tv-casting-app: Connection callback not received on putting screen to sleep and waking it up
### Reproduction steps

1. Run the iOS tv-casting-app
2. Commission it with the Linux tv-app
3. Kill the iOS tv-casting-app and restart it
4. Put the screen to sleep and wake it up
5. Click the button for the Linux tv-app it was previously commissioned with.
6. The iOS tv-casting-app shows that it sent the request to connect via CASE, but does not confirm that the connection was successful (because it did not receive the callback)
7. Navigate back to the previous screen on the iOS tv-casting-app and retry step 6. This time the connection is confirmed (got the callback)

### Bug prevalence

Everytime with the above repro steps

### GitHub hash of the SDK that was being used

dd6ae93542c8155bb3d69d214bc51f528d965a13

### Platform

darwin

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sharadb-amazon**
Fixes https://github.com/project-chip/connectedhomeip/issues/24399 and https://github.com/project-chip/connectedhomeip/issues/24400

#### Change Summary
1. Fix for https://github.com/project-chip/connectedhomeip/issues/24399 - Re-initialized binding handlers in the startMatterServer API to make sure the SDK is set up to make the callback on calls to FindOrEstablishSession the first time.
2. Fix for https://github.com/project-chip/connectedhomeip/issues/24400 - Moved calls to SetRotatingDeviceIdUniqueId to a point before the Matter server is initialized, to ensure we always are using the client's passed in RotatingDeviceIdUniqueId and never a default one.

#### Testing
Tested using the Android/iOS tv-casting-apps running against the Linux tv-app

### CODE REVIEW

**Review by chrisdecenzo — APPROVED** [review]

File: examples/tv-casting-app/android/App/app/src/main/jni/cpp/TvCastingApp-JNI.cpp [hunk 1]
```diff
@@ -52,6 +52,37 @@ void JNI_OnUnload(JavaVM * jvm, void * reserved)
...
+        VerifyOrExit(err == CHIP_NO_ERROR,
+                     ChipLogError(AppServer, "Conversion of AppParameters from jobject to Cpp type failed: %" CHIP_ERROR_FORMAT,
+                                  err.Format()));
+        err = CastingServer::GetInstance()->PreInit(&appParams);
+    }
+    VerifyOrExit(
+        err == CHIP_NO_ERROR,
+        ChipLogError(AppServer, "Call to CastingServer::GetInstance()->PreInit() failed: %" CHIP_ERROR_FORMAT, err.Format()));
+exit:
+    if (err != CHIP_NO_ERROR)
```
Comment (andy31415) [inline examples/tv-casting-app/android/App/app/src/main/jni/cpp/TvCastingApp-JNI.cpp:78]:
```cpp
return (err == CHIP_NO_ERROR);
```

**Review by hawk248 — APPROVED** [review]
