### PR TITLE
chip-repl hits the Code is unsafe/racy assert when BLE commissioning is started

### LINKED ISSUE #26265: [BUG] [PYTHON] BLE Scan crash
### Reproduction steps

Initiate DiscoverySync or DiscoveryAsync will cause entire process to crash with the following message
`[1682519165.322591][1219598:1219598] CHIP:DL: Chip stack locking error at 'src/system/SystemLayerImplSelect.cpp:125'. Code is unsafe/racy`
`[1682519165.322610][1219598:1219598] CHIP:-: chipDie chipDie chipDie`

Issue can be traced to `assertChipStackLockedByCurrentThread();` to the beginning of LayerSelect::StartTimer and LayerSelect::CancelTimer

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

980a1a1

### Platform

python

### Platform Version(s)

_No response_

### Anything else?

Issue can be traced to `assertChipStackLockedByCurrentThread();` to the beginning of LayerSelect::StartTimer and LayerSelect::CancelTimer

### PR DESCRIPTION
**Pull request by tehampson**
Fixes: https://github.com/project-chip/connectedhomeip/issues/26265

PR https://github.com/project-chip/connectedhomeip/pull/26180 added assert on the task ownership of the chip Stack lock on some SystemLayer timer calls.

The Linux ChipDeviceScanner starts a SystemLayer timer on the BLE connection which now asserts.

This pr fix the assert on SystemLayer().StartTimer call by acquiring the chipStack Lock before the call (and releasing it after)

Tested the fix by successfully starting to scan chip-repl

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

File: src/platform/Linux/bluez/ChipDeviceScanner.cpp [hunk 1]
```diff
@@ -79,7 +79,9 @@ ChipDeviceScanner::~ChipDeviceScanner()
     StopScan();
 
     // In case the timeout timer is still active
+    DeviceLayer::PlatformMgr().LockChipStack();
     chip::DeviceLayer::SystemLayer().CancelTimer(TimerExpiredCallback, this);
```
Comment (tehampson) [inline src/platform/Linux/bluez/ChipDeviceScanner.cpp:83]: Blocking comment, there might be one more thing needed here

File: src/platform/Linux/bluez/ChipDeviceScanner.cpp [hunk 2]
```diff
@@ -136,7 +136,9 @@ CHIP_ERROR ChipDeviceScanner::StartScan(System::Clock::Timeout timeout)
         return CHIP_ERROR_INTERNAL;
```
Comment (tehampson) [inline src/platform/Linux/bluez/ChipDeviceScanner.cpp:136]: There is still a problem with how we call CancelTimer for some paths

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
