### PR TITLE
[session][test] Added unit test coverage of OnMessageReceive decrypt path.

### LINKED ISSUE #22735: [test] SessionManager::OnMessageReceived doesn't have formal unit test coverage
### Reproduction steps / Feature

```bash
`SessionManager::OnMessageReceived` doesn't have formal unit test coverage
```

### Platform

core (please add to version below)

### Platform Version(s)

_No response_

### Type

Unit tested

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by turon**
#### Issue Being Resolved
* Fixes #22735

#### Change overview
Adds an extensible unit test framework for `SessionManager::OnMessageReceived`.
Adds an initial test vector for decoding and decryption of a PASE secured unicast message.
This sets up an initial framework for adding more test vectors and session types.
Also fixes a length calculation bug in some uses of `CHIP_CONFIG_TEST_SHARED_SECRET` that results in different operational test keys than intended being used.

### CODE REVIEW

File: src/transport/tests/TestSessionManagerDispatch.cpp [hunk 1]
```diff
@@ -0,0 +1,305 @@
...
+    const char * compressedFabricId;
+
+    const char * mic;
+
+    uint16_t sessionId;
+    NodeId peerNodeId;
+    FabricIndex fabricIndex;
+};
+
+struct MessageTestEntry theMessageTestVector[] = {
```
Comment (tcarmelveilleux) [inline src/transport/tests/TestSessionManagerDispatch.cpp:86]: Can we have more vectors than this and vectors for the behavior of invalid MIC or other negative cases?

**Review by tcarmelveilleux — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]
