### PR TITLE
[Fabric-Admin] Refactor to use API methods instead of PushCommand (3/3)

### LINKED ISSUE #34910: [SVE] Switch from string-based cli API to the SDK API using ReadClients.
### Reproduction steps

Currently, we use the string-based command handling in Fabric-Admin example app, to help integrate to the final product, we need to replace it with API which use read/write clients in the SDK.

For example

https://github.com/project-chip/connectedhomeip/blob/master/examples/fabric-admin/commands/pairing/DeviceSynchronization.cpp#L186

https://github.com/project-chip/connectedhomeip/blob/master/examples/fabric-admin/commands/pairing/DeviceSynchronization.cpp#L155

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

c4cdbf68836a08ea17b14fad98669341a309aa1f

### Platform

raspi

### Platform Version(s)

_No response_

### Type

Test Improvement

### Testing

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yufengwangca**
In the Fabric-Admin example app, we currently use string-based command handling. To better integrate with the final product, we need to replace this with APIs that utilize the SDK's read, write, and invoke clients.

Implement the bridge subscription API.

Fixes https://github.com/project-chip/connectedhomeip/issues/34910

### CODE REVIEW

File: examples/fabric-admin/device_manager/BridgeSubscription.cpp [hunk 1]
```diff
@@ -0,0 +1,153 @@
...
+
+    ReadPrepareParams readParams(sessionHandle);
+
+    readParams.mpAttributePathParamsList    = readPaths;
+    readParams.mAttributePathParamsListSize = 1;
+    readParams.mpEventPathParamsList        = eventPaths;
+    readParams.mEventPathParamsListSize     = 1;
+    readParams.mMinIntervalFloorSeconds     = kSubscribeMinInterval;
+    readParams.mMaxIntervalCeilingSeconds   = kSubscribeMaxInterval;
+
```
Comment (tehampson) [inline examples/fabric-admin/device_manager/BridgeSubscription.cpp:138]: Likely this isn't something that can be done in this PR, but should we filtering the event number only looking for something new. Otherwise you might get old events and start trying to send a CommissionNode (that will fail due to your state machine.

Comment (yufengwangca) [reply examples/fabric-admin/device_manager/BridgeSubscription.cpp:138]: The event contains the RequestId, which SHALL match the RequestId provided to RequestCommissioningApproval and the ClientNodeId shall match the NodeId of the client which sent the RequestCommissioningApproval command. So we should not process out of date event.

File: examples/fabric-admin/device_manager/BridgeSubscription.cpp [hunk 2]
```diff
@@ -0,0 +1,153 @@
...
+}
+
+} // namespace
+
+BridgeSubscription::BridgeSubscription() :
+    mOnDeviceConnectedCallback(OnDeviceConnectedWrapper, this),
+    mOnDeviceConnectionFailureCallback(OnDeviceConnectionFailureWrapper, this)
+{}
+
+CHIP_ERROR BridgeSubscription::StartSubscription(Controller::DeviceController & controller, NodeId nodeId, EndpointId endpointId)
```
[the remark this answers is not in the document]
Comment (yufengwangca) [reply examples/fabric-admin/device_manager/BridgeSubscription.cpp:48]: Acked

File: examples/fabric-admin/device_manager/BridgeSubscription.cpp [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+
+void BridgeSubscription::OnError(CHIP_ERROR error)
+{
+    ChipLogProgress(NotSpecified, "Error on remote fabric sync bridge subscription: %" CHIP_ERROR_FORMAT, error.Format());
+}
+
+void BridgeSubscription::OnDone(ReadClient * apReadClient)
+{
+    mClient.reset();
+    ChipLogProgress(NotSpecified, "The remote fabric sync bridge subscription is terminated");
```
[the remark this answers is not in the document]
Comment (yufengwangca) [reply examples/fabric-admin/device_manager/BridgeSubscription.cpp:113]: this should be done in the upper layer.  https://github.com/project-chip/connectedhomeip/issues/36092

File: examples/fabric-admin/device_manager/BridgeSubscription.cpp [hunk 4]
```diff
@@ -0,0 +1,153 @@
...
+        ChipLogError(NotSpecified, "Response Failure: No Data");
+        return;
+    }
+
+    DeviceMgr().HandleEventData(eventHeader, *data);
+}
+
+void BridgeSubscription::OnReportEnd()
+{
+    // We will call mOnDoneCallback in OnDone.
```
[the remark this answers is not in the document]
Comment (yufengwangca) [reply examples/fabric-admin/device_manager/BridgeSubscription.cpp:102]: Copied from other place, removed

File: examples/fabric-admin/device_manager/BridgeSubscription.cpp (hunk 1 above)
Comment (tehampson) [reply examples/fabric-admin/device_manager/BridgeSubscription.cpp:146]: But there is a chance an old one could match. It is unlikely, but why open ourselves up if we don't need to.

File: examples/fabric-admin/device_manager/BridgeSubscription.cpp [hunk 5]
```diff
@@ -97,20 +102,23 @@ void BridgeSubscription::OnEventData(const app::EventHeader & eventHeader, TLV::
...
-{
-    // We will call mOnDoneCallback in OnDone.
-}
-
 void BridgeSubscription::OnError(CHIP_ERROR error)
 {
     ChipLogProgress(NotSpecified, "Error on remote fabric sync bridge subscription: %" CHIP_ERROR_FORMAT, error.Format());
+
+    // Reset the subscription state to allow retry
+    subscriptionStarted = false;
```
Comment (tehampson) [inline examples/fabric-admin/device_manager/BridgeSubscription.cpp:110]: nit, I think you should wait until OnDone to set this to false

**Review by tehampson — APPROVED** [review]

File: examples/fabric-admin/device_manager/BridgeSubscription.cpp (hunk 5 above)
Comment (yufengwangca) [reply examples/fabric-admin/device_manager/BridgeSubscription.cpp]: We already did, since OnError is always followed by OnDone, so we can remove subscription reset from this method.

File: examples/fabric-admin/device_manager/BridgeSubscription.cpp (hunk 1 above)
Comment (tehampson) [reply examples/fabric-admin/device_manager/BridgeSubscription.cpp:143]: Fair what we create in the admin is random (this is assuming nothing is wrong with random generator, which is a relatively safe assumption). I still wonder why you think processing events that we know might be old even if they fail is a good things and not worth considering.

Please note I am okay with not doing this in this PR or even a follow up. I am just wondering if we have considered it and why we are okay with having it process events that we can potentially know are old and not relevant.

The trade-off of developer time is an acceptable reason to not do it, just I want to make sure we at the very least think about what we are trading off. I appreciate the discussion

Comment (yufengwangca) [reply examples/fabric-admin/device_manager/BridgeSubscription.cpp:143]: I set this event to 'eventPaths[0].mIsUrgentEvent = true;' so that the server won't buffer this event to prevent we retrieve the out of date event.

**Comment by andy31415** [comment]
fast track of 1-week old PR
