### PR TITLE
Use TestEventTriggerDelegate in General Diagnostics Cluster

### LINKED ISSUE #18322: [TC-DGGEN-1.1] General Diagnostics--AttributeList attribute missed to list the Mandatory TestEventTriggersEnabled attribute
**Test-case ID** 
 [TC-DGGEN-1.1] Global attributes with server as DUT

**Problem:-**
As per Test-Plan, AttributeList attribute missed to list the Mandatory TestEventTriggersEnabled attribute

**expected behavior**:- TH should read mandatory attributes (values 0, 1, 8) from DUT
**actual behavior:**- TH missed to read Mandatory TestEventTriggersEnabled(8) attribute from DUT
**steps to reproduce:**-./chip-tool generaldiagnostics read attribute-list 1 0

**system configuration:-**
system configuration
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : IP and Wifi
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/25e241ebcbf11b1f63dbe25546b1f10219866ad0
Dut application: All-Clusters-app

**Chip-tool screenshot:-**
image

**Test-Plan reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/general_diagnostics.adoc#tc-dggen-1-1-global-attributes-with-server-as-dut

**Spec Reference:-**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/DiagnosticsGeneral.adoc

### PR DESCRIPTION
**Pull request by tehampson**
#### Problem
* Fixes #18322 

#### Change overview
* Enable TestEventTriggersEnabled attribute on general diagnostics cluster
* Enable TestEventTrigger command on general diagnostics cluster

#### Testing
* Manually tested on linux host
  * Confirmed attribute is listed in chip-tool
  * Confirmed reading TestEventTriggersEnabled attribute returns expected false
  * Confirmed sending command with 0s EnableKey gives `CONSTRAINT_ERROR`
  * Confirmed sending command with incorrectly sized EnableKey gives `CONSTRAINT_ERROR`

### CODE REVIEW

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 1]
```diff
@@ -15,11 +15,13 @@
  *    limitations under the License.
  */
 
+#include "app/server/Server.h"
 #include <app-common/zap-generated/attributes/Accessors.h>
 #include <app-common/zap-generated/cluster-objects.h>
 #include <app-common/zap-generated/ids/Attributes.h>
 #include <app-common/zap-generated/ids/Clusters.h>
 #include <app/AttributeAccessInterface.h>
+#include <app/CommandHandlerInterface.h>
```
Comment (bzbarsky-apple) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:24]: Why is this being included?  It's not needed....

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 2]
```diff
@@ -290,6 +323,45 @@ GeneralDiagnosticsDelegate gDiagnosticDelegate;
 
 } // anonymous namespace
 
+bool emberAfGeneralDiagnosticsClusterTestEventTriggerCallback(CommandHandler * commandObj, const ConcreteCommandPath & commandPath,
+                                                              const Commands::TestEventTrigger::DecodableType & commandData)
+{
+
+    if (commandData.enableKey.empty() || commandData.enableKey.size() != TestEventTriggerDelegate::kExpectedEnableKeyLength)
```
Comment (bzbarsky-apple) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:330]: Why is the `empty()` test here?

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 3]
```diff
@@ -290,6 +323,45 @@ GeneralDiagnosticsDelegate gDiagnosticDelegate;
...
+    {
+        emberAfSendImmediateDefaultResponse(EMBER_ZCL_STATUS_INVALID_VALUE);
```
Comment (bzbarsky-apple) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:332]: Please don't add new `emberAfSendImmediateDefaultResponse` callers.  Send a response via `commandObj` instead.

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 4]
```diff
@@ -290,6 +323,45 @@ GeneralDiagnosticsDelegate gDiagnosticDelegate;
...
+
+    if (!testEventTrigger->DoesEnableKeyMatch(commandData.enableKey))
+    {
+        emberAfSendImmediateDefaultResponse(EMBER_ZCL_STATUS_UNSUPPORTED_ACCESS);
+        return true;
+    }
+
+    if (CHIP_NO_ERROR != testEventTrigger->HandleEventTrigger(commandData.eventTrigger))
+    {
+        emberAfSendImmediateDefaultResponse(EMBER_ZCL_STATUS_INVALID_COMMAND);
```
Comment (bzbarsky-apple) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:357]: Shouldn't this send the actual error as the response status?

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp (hunk 1 above)
Comment (tehampson) [reply src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp]: Weird, I could have sworn I needed it for `CommandHandler`. But turns out I don't

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 5]
```diff
@@ -38,6 +40,33 @@ using chip::DeviceLayer::GetDiagnosticDataProvider;
 
 namespace {
 
+bool isTestEventTriggerEnabled()
```
Comment (tcarmelveilleux) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:43]: Please use `IsTestEventTriggerEnabled()`

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 6]
```diff
@@ -38,6 +40,33 @@ using chip::DeviceLayer::GetDiagnosticDataProvider;
...
+{
+    auto * testEventTrigger = Server::GetInstance().GetTestEventTriggerDelegate();
+    if (testEventTrigger == nullptr)
+    {
+        return false;
+    }
+    uint8_t zeroByteSpanData[TestEventTriggerDelegate::kExpectedEnableKeyLength] = { 0 };
```
Comment (tcarmelveilleux) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:50]: Suggest rename `kExpectedEnableKeyLength` to `kEnableKeyLength`

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp (hunk 2 above)
Comment (tcarmelveilleux) [reply src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp]: The .size() check is enough

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 7]
```diff
@@ -290,6 +323,51 @@ GeneralDiagnosticsDelegate gDiagnosticDelegate;
...
+    if (IsByteSpanAllZeros(commandData.enableKey))
+    {
+        commandObj->AddStatus(commandPath, Status::ConstraintError);
+        return true;
+    }
+
+    auto * testEventTrigger = Server::GetInstance().GetTestEventTriggerDelegate();
+    if (testEventTrigger == nullptr)
+    {
+        commandObj->AddStatus(commandPath, Status::InvalidCommand);
```
Comment (tcarmelveilleux) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:345]: This is equivalent to the key not matching (it could never match, because we don't even have a handler). This should return `UNSUPPORTED_ACCESS`

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 8]
```diff
@@ -290,6 +323,51 @@ GeneralDiagnosticsDelegate gDiagnosticDelegate;
...
+        return true;
+    }
+
+    if (IsByteSpanAllZeros(commandData.enableKey))
+    {
+        commandObj->AddStatus(commandPath, Status::ConstraintError);
+        return true;
+    }
+
+    auto * testEventTrigger = Server::GetInstance().GetTestEventTriggerDelegate();
```
Comment (tcarmelveilleux) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:342]: Suggest renaming to `triggerDelegate`

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 9]
```diff
@@ -290,6 +323,51 @@ GeneralDiagnosticsDelegate gDiagnosticDelegate;
...
+    }
+
+    Status returnStatus                 = Status::Failure;
+    CHIP_ERROR handleEventTriggerResult = testEventTrigger->HandleEventTrigger(commandData.eventTrigger);
+
+    if (handleEventTriggerResult == CHIP_NO_ERROR)
+    {
+        returnStatus = Status::Success;
+    }
+    else if (handleEventTriggerResult == CHIP_ERROR_INVALID_ARGUMENT)
```
Comment (tcarmelveilleux) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:362]: Suggest having an else that sets to `Failure` rather than relying on falltrhough of default `returnStatus` value

File: examples/all-clusters-app/all-clusters-common/all-clusters-app.zap [hunk 10]
```diff
@@ -3339,7 +3339,16 @@
...
+          "commands": [
+            {
+              "name": "TestEventTrigger",
+              "code": 0,
+              "mfgCode": null,
+              "source": "client",
+              "incoming": 1,
+              "outgoing": 0
+            }
+          ],
```
[the remark this answers is not in the document]
Comment (tehampson) [reply examples/all-clusters-app/all-clusters-common/all-clusters-app.zap:3351]: I will do this one as a follow up since I will likely add something to the python linter

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp]: You need `CommandHandler.h` for that.

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 11]
```diff
@@ -290,6 +323,50 @@ GeneralDiagnosticsDelegate gDiagnosticDelegate;
...
+        commandObj->AddStatus(commandPath, Status::UnsupportedAccess);
+        return true;
+    }
+
+    Status returnStatus                 = Status::Success;
+    CHIP_ERROR handleEventTriggerResult = triggerDelegate->HandleEventTrigger(commandData.eventTrigger);
+
+    if (handleEventTriggerResult == CHIP_NO_ERROR)
+    {
+        returnStatus = Status::Success;
```
Comment (bzbarsky-apple) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:355]: I was thinking something more like an unconditional:
```
  returnStatus = StatusIB(handleEventTriggerResult).mStatus;
```
which lets the callee return whatever status they want...  In particular, that will turn CHIP_NO_ERROR into Status::Success.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by tcarmelveilleux — APPROVED** [review]

File: examples/all-clusters-minimal-app/all-clusters-common/all-clusters-minimal-app.matter [hunk 12]
```diff
@@ -3001,14 +3002,14 @@ server cluster ThreadNetworkDiagnostics = 53 {
...
-  readonly attribute int8u weighting = 10;
-  readonly attribute int8u dataVersion = 11;
-  readonly attribute int8u stableDataVersion = 12;
-  readonly attribute int8u leaderRouterId = 13;
-  readonly attribute SecurityPolicy securityPolicy[] = 59;
-  readonly attribute octet_string<4> channelMask = 60;
-  readonly attribute OperationalDatasetComponents operationalDatasetComponents[] = 61;
+  readonly attribute nullable int32u partitionId = 9;
+  readonly attribute nullable int8u weighting = 10;
+  readonly attribute nullable int8u dataVersion = 11;
```
Comment (tcarmelveilleux) [inline examples/all-clusters-minimal-app/all-clusters-common/all-clusters-minimal-app.matter:3007]: Please regen ZAP.

Also please add `TestEventTrigger` stuff to the all-clusters-minimal-app.matter
