### PR TITLE
Fix integer overflow in ExtractIdFromServiceName.

### LINKED ISSUE #8768: ExtractIdFromInstanceName is can end up with integer overflow
#### Problem
`ExtractIdFromInstanceName` does not have any checks for number of digits it's processing, so can overflow.  As a result, it can have a different idea of what id an instance name maps to than other things do.

 #### Proposed Solution
Add sanity length checks.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
In particular, we enforce that the ids we are trying to extract are
the right length (exactly 16 hex chars each).

#### Problem
ExtractIdFromServiceName can end up with integer overflow if the hex strings involved are longer than 16 digits.

#### Change overview
Check that hex strings are the right length, use existing hex-to-bytes utility instead of having our own private hex-parsing code.

Fixes https://github.com/project-chip/connectedhomeip/issues/8768

#### Testing
Unit tests.

### CODE REVIEW

File: src/lib/mdns/ServiceNaming.cpp [hunk 1]
```diff
@@ -67,43 +48,34 @@ CHIP_ERROR ExtractIdFromInstanceName(const char * name, PeerId * peerId)
...
+    ReturnErrorCodeIf(len < totalLength, CHIP_ERROR_INVALID_ARGUMENT);
+
+    // Check that we have a proper terminator.
+    ReturnErrorCodeIf(name[totalLength] != '\0' && name[totalLength] != '.', CHIP_ERROR_WRONG_NODE_ID);
+
+    // Check what we have a separator where we expect.
+    ReturnErrorCodeIf(name[fabricIdStringLength] != '-', CHIP_ERROR_WRONG_NODE_ID);
+
+    static constexpr size_t bufferSize = max(fabricIdByteLength, nodeIdByteLength);
+    uint8_t buf[bufferSize];
```
Comment (Damian-Nordic) [inline src/lib/mdns/ServiceNaming.cpp:67]:
```suggestion
    uint64_t buf;
```
To make sure that the variable is properly aligned when you access it via `uint64_t` pointer.

**Review by Damian-Nordic — CHANGES_REQUESTED** [review]

File: src/lib/mdns/ServiceNaming.cpp [hunk 2]
```diff
@@ -67,43 +48,34 @@ CHIP_ERROR ExtractIdFromInstanceName(const char * name, PeerId * peerId)
...
+
+    ReturnErrorCodeIf(Encoding::HexToBytes(name, fabricIdStringLength, buf, bufferSize) == 0, CHIP_ERROR_WRONG_NODE_ID);
+    // Buf now stores the fabric id, as big-endian bytes.
+    static_assert(fabricIdByteLength == sizeof(uint64_t), "Casting won't work");
+    peerId->SetFabricId(Encoding::BigEndian::HostSwap64(*reinterpret_cast<uint64_t *>(buf)));
```
Comment (andy31415) [inline src/lib/mdns/ServiceNaming.cpp:72]: raw bytes and casting feels a bit unclean/tricky code. Consider extracting into a separate method.

Comment (tcarmelveilleux) [inline src/lib/mdns/ServiceNaming.cpp:72]: Please let's not hostswap a reinterpret-cast, and rather, let's let's just have a `Reader()` over buf and do Read64.

Now that I look at it, I see we have a couple problems:

1- We only have little-endian reader
2- This is why we use this unfortunate trickery here.

I feel like the "single value deserialize" comes often enough that given a byte span and an output value, we should be able to have utilities like `BigEndianToUint64`, `LittleEndianToUint64`, etc... They could wrap reader under the hood.

Doing any reinterpret cast is hugely dangerous. The point above about the `uint8_t buf[bufferSize];` --> `uint64_t N` is important. On several architectures, re-interpret-casting unaligned memory to a wide scalar (e.g. uint32_t/uint64_t) will lead to a fault.

**Review by tcarmelveilleux — CHANGES_REQUESTED** [review]

**Comment by bzbarsky-apple** [comment]
Good points all.  I should be using `Encoding::BigEndian::Get64`, which does the proper unaligned reads as needed.

File: src/lib/mdns/ServiceNaming.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/lib/mdns/ServiceNaming.cpp]: We already have reader methods for basic "read an int from a buffer"; I had just forgotten about them...  Updated PR uses `BigEndian::Get64`, which does exactly that.  It's not length-safe, so not quite the same as wrapping a `Reader`, but definitely much better than what I used to have.

File: src/lib/mdns/ServiceNaming.cpp [hunk 3]
```diff
@@ -67,43 +48,34 @@ CHIP_ERROR ExtractIdFromInstanceName(const char * name, PeerId * peerId)
...
-    ReturnErrorCodeIf(!deliminatorFound, CHIP_ERROR_WRONG_NODE_ID);
-    ReturnErrorCodeIf(!hasNodePart, CHIP_ERROR_WRONG_NODE_ID);
-    ReturnErrorCodeIf(!hasFabricPart, CHIP_ERROR_WRONG_NODE_ID);
+    // Make sure the string is long enough.
+    static constexpr size_t fabricIdByteLength   = 8;
+    static constexpr size_t fabricIdStringLength = fabricIdByteLength * 2;
+    static constexpr size_t nodeIdByteLength     = 8;
+    static constexpr size_t nodeIdStringLength   = nodeIdByteLength * 2;
+    static constexpr size_t totalLength          = fabricIdStringLength + nodeIdStringLength + 1; // +1 for '-'
+    size_t len                                   = strlen(name);
```
Comment (tcarmelveilleux) [inline src/lib/mdns/ServiceNaming.cpp:57]: Suggest `strnlen(name, totalLength + 1)` and check that `len != totalLength` in the next line

File: src/lib/mdns/ServiceNaming.cpp [hunk 4]
```diff
@@ -67,43 +48,34 @@ CHIP_ERROR ExtractIdFromInstanceName(const char * name, PeerId * peerId)
...
-            hasFabricPart = true;
-            peerId->SetFabricId(peerId->GetFabricId() * 16 + val);
-        }
-    }
-
-    ReturnErrorCodeIf(!deliminatorFound, CHIP_ERROR_WRONG_NODE_ID);
-    ReturnErrorCodeIf(!hasNodePart, CHIP_ERROR_WRONG_NODE_ID);
-    ReturnErrorCodeIf(!hasFabricPart, CHIP_ERROR_WRONG_NODE_ID);
+    // Make sure the string is long enough.
+    static constexpr size_t fabricIdByteLength   = 8;
```
Comment (tcarmelveilleux) [inline src/lib/mdns/ServiceNaming.cpp:52]: Note: once https://github.com/project-chip/connectedhomeip/pull/8776 is merged, `fabricIdByteLength` can be replaced by chip::Crypto::kCompressedFabricIdentifierSize.

**Review by tcarmelveilleux — APPROVED** [review]

**Review by Damian-Nordic — APPROVED** [review]

File: src/lib/mdns/ServiceNaming.cpp (hunk 3 above)
Comment (bzbarsky-apple) [reply src/lib/mdns/ServiceNaming.cpp:57]: Good call on the `strnlen`; I had idly wondered how best to avoid walking the whole string if it happens to be long...

But `len != totalLength` does not work because we _could_ have `len > totalLength` if our instance name is followed by `'.'`.  So going to do this:
```
    // Ensure we have at least totalLength chars.
    size_t len = strnlen(name, totalLength);
    ReturnErrorCodeIf(len < totalLength, CHIP_ERROR_INVALID_ARGUMENT);
```

**Review by emargolis — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@andy31415 @woody-apple @msandstedt @saurabhst Please take a look?

**Review by saurabhst — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
