### PR TITLE
Fix NetworkCommissioning Cluster issues

### LINKED ISSUE #31870: [Bug] [NetworkCommissioning] Empty results of directed ScanNetworks don't return expected `NetworkNotFoundError`
### Feature Area

Other

### Test Case

TC-CNET-4.4

### Reproduction steps

1. Bring up the Device Under Test (DUT) with the all-clusters-app.
2. Pair the DUT using chip-tool through the "ble-wifi" transport.
3. Scan the network to know available networks : ./chip-tool networkcommissioning scan-networks 1 0 --Ssid null --Breadcrumb 1
**Note** : _Select any one SSID as 1ST_ACCESSPOINT_SSID_hex_
4. Scan the selected network : ./chip-tool networkcommissioning scan-networks 1 0 --Ssid hex:<1ST_ACCESSPOINT_SSID_hex> --Breadcrumb 2
5. Turn off the 1ST_ACCESSPOINT_SSID_hex wifi
6. Now scan the selected network to expect the NOT FOUND error
 
 **Test Plan Expected outcome** : 
 
 `_Verify that the DUT sends the ScanNetworkResponse command with the NetworkingStatus field set to NetworkNotFound._`

**Expected outcome:** 
> [1683268296.897526][12131:12134] CHIP:TOO:   NetworkConfigResponse: {
> [1683268296.897745][12131:12134] CHIP:TOO:     networkingStatus: 3
> [1683268296.898546][12131:12134] CHIP:TOO:    }

**Actual outcome:** 

> [1707212325.045487][39892:39895] CHIP:TOO:   ScanNetworksResponse: {
> [1707212325.045576][39892:39895] CHIP:TOO:     networkingStatus: 0
> [1707212325.045644][39892:39895] CHIP:TOO:     wiFiScanResults: 0 entries
> [1707212325.045886][39892:39895] CHIP:TOO:    }

### Bug prevalence

Whenever I do this 

### GitHub hash of the SDK that was being used

f63b505179fd326c2cb5df91eed330ecd71a39b8

### Platform

raspi

**Logs:**
[TC_CNET_4_4(ctrl).txt](https://github.com/project-chip/connectedhomeip/files/14177815/TC_CNET_4_4.ctrl.txt)
[TC_CNET_4_4(dut).txt](https://github.com/project-chip/connectedhomeip/files/14177816/TC_CNET_4_4.dut.txt)

**Test Plan Reference:** https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/network_commissioning.adoc#tc-cnet-4-4-wi-fi-verification-for-scannetworks-command-dut-server

### LINKED ISSUE #32018: [Bug][NetworkCommissioning] All command constraint errors lead to InvalidCommand instead of ConstraintError
- In NetworkCommissioning cluster, code inspection showed that `ConstraintError` is almost never used and most cases return InvalidCommand or Failure instead, which is not DM spec compliant.
- Affects 1.0 through 1.3 up to fix.
- Likely was not caught because of insufficient error coverage in cert test cases.

### LINKED ISSUE #32019: [Bug][NetworkCommissioning] ScanNetworks does not disallow `ssid` field
- In NetworkCommissioning HandleScanNetworks, the `ssid` field being populated is not considered an error, even though conformance indicates `ssid` should ONLY be present if the cluster supports WIFI
- Affects 1.0 through 1.3 up to fix.
- Likely was not caught because of insufficient error coverage in cert test cases.
- Fixing this may break some clients that always populate an empty SSID rather than omitting the field, if there is such a thing...

### LINKED ISSUE #32021: [Bug] [NetworkCommissioning] LastNetworkStatus not set every place it needs to be
- In NetworkCommissioning cluster, SetLastNetworkStatusValue is not set on failure to Scan.
- Spec says:

> [[ref_LastNetworkingStatus]]
=== LastNetworkingStatus Attribute
This attribute SHALL indicate the status of the last attempt either scan or connect to an operational network, using this interface, whether by invocation of the <<ref_ConnectNetwork,ConnectNetwork>> command or by autonomous connection after loss of connectivity or during initial establishment. If no such attempt was made, or no network configurations exist in the <<ref_Networks,Networks>> attribute, then this attribute SHALL be set to null.
>
> This attribute is present to assist with error recovery during Network commissioning and to assist in non-concurrent networking commissioning flows.

- Affects 1.0 through 1.3 up to fix.
- Likely was not caught because of insufficient error coverage in cert test cases.

### LINKED ISSUE #32022: [Bug] [NetworkCommissioning] ScanNetworks incorrectly updates several attributes
- In NetworkCommissioning cluster, ScanNetworks updates multiple internal attribute values, affecting future reads, even though the outcome is not the one expected.
- The following attributes are touched, that shouldn't:
  - LastNetworkID
  - LastConnectErrorValue
  - Some cases of LastNetworkingStatus
- This affects 1.0 through 1.3 up to fix.
- Likely was not caught because of insufficient error coverage in cert test cases.

### LINKED ISSUE #32024: [Bug] [NetworkCommissioning] All non-fixed attributes are not reported on update
It was found that the NetworkCommissioning cluster never reports on changes to any of the read-only attributes, preventing clients from detecting changes.

These are:
- LastNetworkingStatus
- LastNetworkID
- LastConnectErrorValue
- Networks

Affects 1.0 through 1.3 up to fix.
Likely was not caught because of insufficient error coverage in cert test cases.

### PR DESCRIPTION
**Pull request by tcarmelveilleux**
This PR addresses several NetworkCommissioning issues which are all inter-related:

- Attributes are never reported on change.
- ScanNetworks used to modify attributes that should not be modified
- LastNetworkStatus was not set where required
- Thread network scanning did not report error on SSID field provided
- All ConstraintErrors actually were reported as InvalidCommand
- Lacking results of directed scanning did not report NetworkNotFound

All fixed issues:
- Fixes #32024
- Fixes #32022
- Fixes #32021
- Fixes #32019
- Fixes #32018
- Fixes #31870

Testing done:
- TC-CNET-4.4 pass on ESP32 and Linux
- Commissioning works on ESP32 and Linux
- Manual testing of all attribute changes validated with chip-repl
  - Automated test beyond TC-CNET-4.4 coming as a follow-up

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]

File: src/app/clusters/network-commissioning/network-commissioning.h [hunk 1]
```diff
@@ -77,10 +77,11 @@ class Instance : public CommandHandlerInterface,
     static void OnPlatformEventHandler(const DeviceLayer::ChipDeviceEvent * event, intptr_t arg);
     void OnCommissioningComplete();
     void OnFailSafeTimerExpired();
-
 #if !CHIP_DEVICE_CONFIG_SUPPORTS_CONCURRENT_CONNECTION
     void SendNonConcurrentConnectNetworkResponse();
 #endif
+
+    EndpointId mEndpointId;
```
Comment (yunhanw-google) [inline src/app/clusters/network-commissioning/network-commissioning.h:84]: please init it mEndpointId = kInvalidEndpointId?

File: src/app/tests/TestNullable.cpp [hunk 2]
```diff
@@ -0,0 +1,307 @@
...
+
+struct Count
+{
+    Count(int i) : m(i) { ++created; }
+    ~Count() { ++destroyed; }
+
+    Count(const Count & o) : m(o.m) { ++created; }
+    Count & operator=(const Count &) = default;
+
+    Count(Count && o) : m(o.m) { ++created; }
```
Comment (andy31415) [inline src/app/tests/TestNullable.cpp:40]: is this safe? If I move something, I expect its destructor to not be called. Is this intentional that if I do move semantics only created increased but not destroyed?

Comment (andy31415) [inline src/app/tests/TestNullable.cpp:40]: If move semantics I expect destructor not to be called. Is it ok to just increase created and not destructed?

File: examples/energy-management-app/energy-management-common/energy-management-app.zap [hunk 3]
```diff
@@ -1452,6 +1452,22 @@
               "maxInterval": 65534,
               "reportableChange": 0
             },
+            {
+              "name": "SupportedWiFiBands",
```
Comment (jmartinez-silabs) [inline examples/energy-management-app/energy-management-common/energy-management-app.zap:1456]: this will be problematic for thread platform running this app with common zap file

File: src/app/tests/TestNullable.cpp [hunk 4]
```diff
@@ -0,0 +1,307 @@
...
+
+#include <app/data-model/Nullable.h>
+#include <lib/support/Span.h>
+#include <lib/support/UnitTestRegistration.h>
+#include <nlunit-test.h>
+
+using namespace chip;
+using namespace chip::app::DataModel;
+
+struct Count
```
[the remark this answers is not in the document]
Comment (andy31415) [reply src/app/tests/TestNullable.cpp:32]: Please add some documentation on expected behaviuor and use.

File: src/app/tests/TestNullable.cpp [hunk 5]
```diff
@@ -0,0 +1,307 @@
...
+    NL_TEST_DEF("NullableCopy", TestCopy),
+    NL_TEST_DEF("NullableMove", TestMove),
+    NL_TEST_DEF("Nullable SetToMatch operation", TestSetToMatch),
+    NL_TEST_SENTINEL()
+};
+// clang-format on
+
+int TestNullable_Setup(void * inContext)
+{
+    return SUCCESS;
```
Comment (andy31415) [inline src/app/tests/TestNullable.cpp:282]: you can pass in nullptr to the nlTestSuite and not define these if they are a noop

File: src/app/data-model/Nullable.h [hunk 6]
```diff
@@ -80,6 +80,16 @@ struct Nullable : protected Optional<T>
         return true;
     }
 
+    // Set the nullable to the `other` nullable, returning true if something actually changed.
+    // This can be used to determine if changes occurred on assignment, so that reporting can be triggered
+    // only on actual changes.
+    constexpr bool SetToMatch(const Nullable<T> & other)
```
Comment (andy31415) [inline src/app/data-model/Nullable.h:86]: This name feels odd ... are there libraries that use this name for reference? I would have expected `Assign` or `Update` or even just `Set`.

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 7]
```diff
@@ -1020,9 +1097,14 @@ void Instance::OnFinished(Status status, CharSpan debugText, WiFiScanResponseIte
         return;
     }
 
-    mLastNetworkingStatusValue.SetNonNull(status);
-    mLastConnectErrorValue.SetNull();
-    mLastNetworkIDLen = 0;
+    // If drivers are failing to respond NetworkNotFound on empty results, force it for them.
```
Comment (jmartinez-silabs) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:1100]: should we not enforce drivers to do so

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 8]
```diff
@@ -1020,9 +1097,14 @@ void Instance::OnFinished(Status status, CharSpan debugText, WiFiScanResponseIte
...
+    bool resultsMissing = !networks || (networks && (networks->Count() == 0));
```
Comment (andy31415) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:1101]: boolean operators should shortcut. `(networks == nullptr) || (networks->Count() == 0)` should be safe.

**Review by jmartinez-silabs — APPROVED** [review]

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 9]
```diff
@@ -379,34 +430,34 @@ CHIP_ERROR Instance::Write(const ConcreteDataAttributePath & aPath, AttributeVal
...
     {
-        memcpy(mLastNetworkID, aNetworkId.Value().data(), aNetworkId.Value().size());
-        mLastNetworkIDLen = static_cast<uint8_t>(aNetworkId.Value().size());
-    }
-    else
-    {
-        mLastNetworkIDLen = 0;
+        if (aNetworkId.Value().size() > kMaxNetworkIDLen)
+        {
+            ChipLogError(DeviceLayer, "Invalid network ID received when calling OnNetworkingStatusChange");
```
Comment (andy31415) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:437]: maybe say `Overly large` in the message since that seems to be more specific than just "invalid" and may help debugging.

File: src/app/tests/TestNullable.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/tests/TestNullable.cpp:32]: Copied from the Optional test... It had no docs there :(

File: examples/energy-management-app/energy-management-common/energy-management-app.zap (hunk 3 above)
Comment (tcarmelveilleux) [reply examples/energy-management-app/energy-management-common/energy-management-app.zap:1456]: It's not the case right now, and without a good sample that can actually run on Embedded Wi-Fi (which all-clusters is not), I have no way to test.

File: src/app/clusters/network-commissioning/network-commissioning.cpp (hunk 7 above)
Comment (tcarmelveilleux) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:1100]: Too late for that

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 10]
```diff
@@ -1044,21 +1126,25 @@ void Instance::OnFinished(Status status, CharSpan debugText, WiFiScanResponseIte
...
     {
-        Structs::WiFiInterfaceScanResultStruct::Type result;
-        result.security = scanResponse.security;
-        result.ssid     = ByteSpan(scanResponse.ssid, scanResponse.ssidLen);
-        result.bssid    = ByteSpan(scanResponse.bssid, sizeof(scanResponse.bssid));
-        result.channel  = scanResponse.channel;
-        result.wiFiBand = scanResponse.wiFiBand;
-        result.rssi     = scanResponse.rssi;
-        SuccessOrExit(err = DataModel::Encode(*writer, TLV::AnonymousTag(), result));
+        for (; networks != nullptr && networks->Next(scanResponse) && networksEncoded < kMaxNetworksInScanResponse;
```
Comment (andy31415) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:1132]: maybe networks != nullptr could be moved up as it does not need to be checked on every for iteration? 
Trying to make the line shorter as this looks quite complex already ... maybe we should even switch to a while loop.

Comment (tcarmelveilleux) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:1132]: This was the existing code... I can change it yes.

File: src/app/clusters/network-commissioning/network-commissioning.h (hunk 1 above)
Comment (tcarmelveilleux) [reply src/app/clusters/network-commissioning/network-commissioning.h:84]: Done

File: src/app/tests/TestNullable.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/tests/TestNullable.cpp:32]: Will rename

File: src/app/data-model/Nullable.h (hunk 6 above)
Comment (tcarmelveilleux) [reply src/app/data-model/Nullable.h:86]: Renaming to Update

File: src/app/clusters/network-commissioning/network-commissioning.cpp (hunk 8 above)
Comment (tcarmelveilleux) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:1101]: Will do

File: src/app/clusters/network-commissioning/network-commissioning.cpp (hunk 9 above)
Comment (tcarmelveilleux) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:437]: Done

File: src/app/clusters/network-commissioning/network-commissioning.cpp (hunk 10 above)
Comment (tcarmelveilleux) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:1132]: Done

File: src/app/tests/TestNullable.cpp (hunk 2 above)
Comment (tcarmelveilleux) [reply src/app/tests/TestNullable.cpp:40]: This is testing the same as TestOptional. I did not reverse engineer the whole set of tests, just ensured that if Nullable becomes different impl than Optional derived class, we catch behavior regression.

File: src/app/tests/TestNullable.cpp (hunk 5 above)
Comment (tcarmelveilleux) [reply src/app/tests/TestNullable.cpp]: Done

File: src/app/tests/TestNullable.cpp [hunk 11]
```diff
@@ -0,0 +1,303 @@
...
+// semantics applied in cases where destruction is expected.
+struct CtorDtorCounter
+{
+    CtorDtorCounter(int i) : m(i) { ++created; }
+    ~CtorDtorCounter() { ++destroyed; }
+
+    CtorDtorCounter(const CtorDtorCounter & o) : m(o.m) { ++created; }
+    CtorDtorCounter & operator=(const CtorDtorCounter &) = default;
+
+    CtorDtorCounter(CtorDtorCounter && o) : m(o.m) { ++created; }
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/tests/TestNullable.cpp:44]: This is a bug that exists in Optional, and is a bigger issue. Can you please raise an issue and we will address holistically.

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 12]
```diff
@@ -1110,6 +1201,12 @@ void Instance::OnFailSafeTimerExpired()
     ChipLogDetail(Zcl, "Failsafe timeout, tell platform driver to revert network credentials.");
     mpWirelessDriver->RevertConfiguration();
     mAsyncCommandHandle.Release();
+
+    // Reset state on failsafe expiry.
```
Comment (bzbarsky-apple) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:1205]: I don't see a spec basis for this...

Furthermore, if the failsafe was for something totally unrelated to commissioning or networks (e.g. an UpdateNOC), clearing this state doesn't obviously seem like the right thing to do.

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 13]
```diff
@@ -426,16 +477,27 @@ void Instance::HandleScanNetworks(HandlerContext & ctx, const Commands::ScanNetw
...
+        mScanningWasDirected        = !ssid.empty();
         mCurrentOperationBreadcrumb = req.breadcrumb;
         mAsyncCommandHandle         = CommandHandler::Handle(&ctx.mCommandHandler);
         ctx.mCommandHandler.FlushAcksRightAwayOnSlowCommand();
         mpDriver.Get<WiFiDriver *>()->ScanNetworks(ssid, this);
     }
     else if (mFeatureFlags.Has(Feature::kThreadNetworkInterface))
     {
+        // Not allowed to populate SSID for Thread.
+        if (!req.ssid.HasValue())
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:495]: Yes :(

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 14]
```diff
@@ -426,16 +477,27 @@ void Instance::HandleScanNetworks(HandlerContext & ctx, const Commands::ScanNetw
...
+        {
+            ctx.mCommandHandler.AddStatus(ctx.mRequestPath, Protocols::InteractionModel::Status::ConstraintError);
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:497]: Will move to InvalidCommand

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 15]
```diff
@@ -426,16 +477,27 @@ void Instance::HandleScanNetworks(HandlerContext & ctx, const Commands::ScanNetw
         }
         if (ssid.size() > DeviceLayer::Internal::kMaxWiFiSSIDLength)
         {
-            ctx.mCommandHandler.AddStatus(ctx.mRequestPath, Protocols::InteractionModel::Status::InvalidCommand);
+            // This should not happen, it means it's a broken driver.
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:480]: Fixed.

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 16]
```diff
@@ -870,19 +945,23 @@ void Instance::OnResult(Status commissioningError, CharSpan debugText, int32_t i
...
     }
 
-    mLastNetworkIDLen = mConnectingNetworkIDLen;
-    memcpy(mLastNetworkID, mConnectingNetworkID, mLastNetworkIDLen);
-    mLastNetworkingStatusValue.SetNonNull(commissioningError);
+    SetLastNetworkId(ByteSpan{ mConnectingNetworkID, mConnectingNetworkIDLen });
+    SetLastNetworkingStatusValue(MakeNullable(commissioningError));
 
-#if CHIP_DEVICE_CONFIG_SUPPORTS_CONCURRENT_CONNECTION
+#if CONFIG_NETWORK_LAYER_BLE && !CHIP_DEVICE_CONFIG_SUPPORTS_CONCURRENT_CONNECTION
```
Comment (bukepo) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:959]: Why is `CONFIG_NETWORK_LAYER_BLE` added?
