### PR TITLE
[MSan Bugfix] Fix uninitialized epoch start time in GroupcastCluster::SetKeySet

### LINKED ISSUE #71584: [MSAN][Groupcast] use of uninitialized epoch.start_time
### Summary

- `TestGroupcastCluster` Memory Sanitized unit test + `TC_GC_2_*` Cert tests with MSan Sanitized Apps are triggering `use-of-uninitialized-value` error
- this happens after a call to `GroupcastCluster::JoinGroup

- This is part of https://github.com/project-chip/connectedhomeip/issues/71500
### Analysis

- the issue seems that `epoch.start_time` is left uninitialized after `GroupDataProvider::KeySet` `ks` is created within `GroupcastCluster::SetKeySet`
- According to spec, `epoch.start_time` in that path (EpochStartTime0) should be initialised to 1

### MSan Stack Traces
<details> 
<summary>1. Unit Test Log</summary>

```cpp
[ RUN      ] TestGroupcastCluster.TestJoinGroupFailsOnBadAargs
[1776178481.660] [1587007:1587007] [DMG] AccessControl: initializing
[1776178481.660] [1587007:1587007] [FP] Initializing FabricTable from persistent storage
[1776178481.660] [1587007:1587007] [TS] Last Known Good Time: [unknown]
[1776178481.660] [1587007:1587007] [TS] Setting Last Known Good Time to firmware build time 2023-10-14T01:16:48
[1776178481.668] [1587007:1587007] [FP] Validating NOC chain
[1776178481.671] [1587007:1587007] [FP] NOC chain validation successful
[1776178481.671] [1587007:1587007] [FP] Added new fabric at index: 0x1
[1776178481.671] [1587007:1587007] [FP] Assigned compressed fabric ID: 0xEED678CC63B5B728, node ID: 0xDEADBEEF00000002
[1776178481.671] [1587007:1587007] [TS] Last Known Good Time: 2023-10-14T01:16:48
[1776178481.671] [1587007:1587007] [TS] New proposed Last Known Good Time: 2000-01-01T00:00:00
[1776178481.671] [1587007:1587007] [TS] Retaining current Last Known Good Time
[1776178481.671] [1587007:1587007] [FP] Metadata for Fabric 0x1 persisted to storage.
[1776178481.671] [1587007:1587007] [TS] Committing Last Known Good Time to storage: 2023-10-14T01:16:48
[1776178481.672] [1587007:1587007] [DMG] AccessControl: checking f=1 a=c s=0x0000000000000001 t= c=0x0000_0065 e=0 p=a r=i
[1776178481.672] [1587007:1587007] [DMG] AccessControl: allowed (delegate)
==1587007==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5b8c4ac01e8f in chip::Credentials::KeySetData::Serialize(chip::TLV::TLVWriter&) const /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/credentials/GroupDataProviderImpl.cpp:726:45
    #1 0x5b8c4ac00245 in chip::DataAccessor::Save(chip::PersistentStorageDelegate*, chip::Span<unsigned char> const&) const /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/lib/support/PersistentData.h:47:36
    #2 0x5b8c4abf3b8f in chip::PersistableData<128ul>::Save(chip::PersistentStorageDelegate*) /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/lib/support/PersistentData.h:110:81
    #3 0x5b8c4abf3b8f in chip::Credentials::GroupDataProviderImpl::SetKeySet(unsigned char, chip::Span<unsigned char const> const&, chip::Credentials::GroupDataProvider::KeySet const&) /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/credentials/GroupDataProviderImpl.cpp:1693:33
    #4 0x5b8c4aa300ce in chip::app::Clusters::GroupcastCluster::SetKeySet(chip::app::ConcreteCommandPath const&, chip::Access::SubjectDescriptor const&, unsigned short, unsigned short, chip::Optional<chip::Span<unsigned char const>> const&) /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/app/clusters/groupcast/GroupcastCluster.cpp:643:26
    #5 0x5b8c4aa2d683 in chip::app::Clusters::GroupcastCluster::JoinGroup(chip::app::ConcreteCommandPath const&, chip::app::Clusters::Groupcast::Commands::JoinGroup::DecodableType const&, chip::Access::SubjectDescriptor const&) /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/app/clusters/groupcast/GroupcastCluster.cpp:481:19
    #6 0x5b8c4aa2b7a5 in chip::app::Clusters::GroupcastCluster::InvokeCommand(chip::app::DataModel::InvokeRequest const&, chip::TLV::TLVReader&, chip::app::CommandHandler*) /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/app/clusters/groupcast/GroupcastCluster.cpp:128:18
    #7 0x5b8c4aadd3e1 in chip::Testing::ClusterTester::InvokeResult<chip::app::DataModel::NullObjectType> chip::Testing::ClusterTester::Invoke<chip::app::Clusters::Groupcast::Commands::JoinGroup::Type, chip::app::DataModel::NullObjectType>(unsigned int, chip::app::Clusters::Groupcast::Commands::JoinGroup::Type const&) /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/app/server-cluster/testing/ClusterTester.h:339:34
    #8 0x5b8c4aada07c in (anonymous namespace)::TestGroupcastCluster_TestJoinGroupFailsOnBadAargs_Test::PigweedTestBody() /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/app/clusters/groupcast/tests/TestGroupcastCluster.cpp:334:30
    #9 0x5b8c4aab584b in pw::unit_test::internal::Test::PigweedTestRun() /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../third_party/pigweed/repo/pw_unit_test/light_public_overrides/pw_unit_test/framework_backend.h:751:7
    #10 0x5b8c4aab584b in void pw::unit_test::internal::Framework::CreateAndRunTest<(anonymous namespace)::TestGroupcastCluster_TestJoinGroupFailsOnBadAargs_Test>(pw::unit_test::internal::TestInfo const&) /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../third_party/pigweed/repo/pw_unit_test/light_public_overrides/pw_unit_test/framework_backend.h:548:20
    #11 0x5b8c4ab6c88c in pw::unit_test::internal::TestInfo::run() const /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../third_party/pigweed/repo/pw_unit_test/light_public_overrides/pw_unit_test/framework_backend.h:705:22
    #12 0x5b8c4ab6c88c in pw::unit_test::internal::Framework::RunAllTests() /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../third_party/pigweed/repo/pw_unit_test/framework_light.cc:71:13
    #13 0x5b8c4ab2b0b3 in RUN_ALL_TESTS() /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../third_party/pigweed/repo/pw_unit_test/light_public_overrides/pw_unit_test/framework_backend.h:803:54
    #14 0x5b8c4ab2b0b3 in main /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/test_driver/posix/unit_test_main.cpp:227:12
    #15 0x7a9f0562a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #16 0x7a9f0562a28a in __libc_start_main csu/../csu/libc-start.c:360:3
    #17 0x5b8c4a99d024 in _start (/home/connectedhomeip/out/linux-x64-tests-msan-clang/tests/TestGroupcastCluster+0x310024) (BuildId: 1790e9f0f8e7d90cbd6612fc1a9a19eda77f4442)

  Uninitialized value was stored to memory at
    #0 0x5b8c4abf3f1a in chip::Credentials::GroupDataProviderImpl::SetKeySet(unsigned char, chip::Span<unsigned char const> const&, chip::Credentials::GroupDataProvider::KeySet const&) /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/credentials/GroupDataProviderImpl.cpp:1670:43
    #1 0x5b8c4aa300ce in chip::app::Clusters::GroupcastCluster::SetKeySet(chip::app::ConcreteCommandPath const&, chip::Access::SubjectDescriptor const&, unsigned short, unsigned short, chip::Optional<chip::Span<unsigned char const>> const&) /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/app/clusters/groupcast/GroupcastCluster.cpp:643:26
    #2 0x5b8c4aa2d683 in chip::app::Clusters::GroupcastCluster::JoinGroup(chip::app::ConcreteCommandPath const&, chip::app::Clusters::Groupcast::Commands::JoinGroup::DecodableType const&, chip::Access::SubjectDescriptor const&) /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/app/clusters/groupcast/GroupcastCluster.cpp:481:19
    #3 0x5b8c4aa2b7a5 in chip::app::Clusters::GroupcastCluster::InvokeCommand(chip::app::DataModel::InvokeRequest const&, chip::TLV::TLVReader&, chip::app::CommandHandler*) /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/app/clusters/groupcast/GroupcastCluster.cpp:128:18
    #4 0x5b8c4aadd3e1 in chip::Testing::ClusterTester::InvokeResult<chip::app::DataModel::NullObjectType> chip::Testing::ClusterTester::Invoke<chip::app::Clusters::Groupcast::Commands::JoinGroup::Type, chip::app::DataModel::NullObjectType>(unsigned int, chip::app::Clusters::Groupcast::Commands::JoinGroup::Type const&) /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/app/server-cluster/testing/ClusterTester.h:339:34
    #5 0x5b8c4aada07c in (anonymous namespace)::TestGroupcastCluster_TestJoinGroupFailsOnBadAargs_Test::PigweedTestBody() /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/app/clusters/groupcast/tests/TestGroupcastCluster.cpp:334:30
    #6 0x5b8c4aab584b in pw::unit_test::internal::Test::PigweedTestRun() /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../third_party/pigweed/repo/pw_unit_test/light_public_overrides/pw_unit_test/framework_backend.h:751:7
    #7 0x5b8c4aab584b in void pw::unit_test::internal::Framework::CreateAndRunTest<(anonymous namespace)::TestGroupcastCluster_TestJoinGroupFailsOnBadAargs_Test>(pw::unit_test::internal::TestInfo const&) /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../third_party/pigweed/repo/pw_unit_test/light_public_overrides/pw_unit_test/framework_backend.h:548:20
    #8 0x5b8c4ab6c88c in pw::unit_test::internal::TestInfo::run() const /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../third_party/pigweed/repo/pw_unit_test/light_public_overrides/pw_unit_test/framework_backend.h:705:22
    #9 0x5b8c4ab6c88c in pw::unit_test::internal::Framework::RunAllTests() /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../third_party/pigweed/repo/pw_unit_test/framework_light.cc:71:13
    #10 0x5b8c4ab2b0b3 in RUN_ALL_TESTS() /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../third_party/pigweed/repo/pw_unit_test/light_public_overrides/pw_unit_test/framework_backend.h:803:54
    #11 0x5b8c4ab2b0b3 in main /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/test_driver/posix/unit_test_main.cpp:227:12
    #12 0x7a9f0562a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #13 0x7a9f0562a28a in __libc_start_main csu/../csu/libc-start.c:360:3
    #14 0x5b8c4a99d024 in _start (/home/connectedhomeip/out/linux-x64-tests-msan-clang/tests/TestGroupcastCluster+0x310024) (BuildId: 1790e9f0f8e7d90cbd6612fc1a9a19eda77f4442)

  Uninitialized value was created by an allocation of 'ks' in the stack frame
    #0 0x5b8c4aa2fc3a in chip::app::Clusters::GroupcastCluster::SetKeySet(chip::app::ConcreteCommandPath const&, chip::Access::SubjectDescriptor const&, unsigned short, unsigned short, chip::Optional<chip::Span<unsigned char const>> const&) /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/app/clusters/groupcast/GroupcastCluster.cpp:607:5

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/connectedhomeip/out/linux-x64-tests-msan-clang/../../src/credentials/GroupDataProviderImpl.cpp:726:45 in chip::Credentials::KeySetData::Serialize(chip::TLV::TLVWriter&) const
Exiting

```

</details>

<details> 
<summary>2. TC_GC_2_3.py</summary>

```cpp

[2026-04-15 13:12:27.999589][TEST][STDOUT][MatterTest] 04-15 13:12:27.998 INFO ***** Test Step 1d : Join Group G1 generating a new Key with KeySetID K1 using JoinGroup
[2026-04-15 13:12:27.999604][APP ][STDOUT][1776251547.998] [2009880:2009880] [EM] ??1 [E:40902r S:9978 M:85044668] (S) Msg Retransmission to 1:000000000001B669 scheduled for 370ms from now [State:Active II:500 AI:300 AT:4000]
[2026-04-15 13:12:27.999747][TEST][STDOUT][MatterTest] 04-15 13:12:27.998 INFO    ***** Test Step 1d : Join Group G1 generating a new Key with KeySetID K1 using JoinGroup
[2026-04-15 13:12:27.999868][APP ][STDOUT][1776251547.998] [2009880:2009880] [DMG] Registered a ReadHandler that will schedule a report between system Timestamp: 0x0000000007F9B0B6 and system Timestamp 0x0000000007FA25E6.
[2026-04-15 13:12:27.999997][APP ][STDOUT][1776251547.998] [2009880:2009880] [DMG] <RE> OnReportConfirm: NumReports = 0
[2026-04-15 13:12:28.000070][TEST][STDOUT][MatterTest] 04-15 13:12:27.999 INFO <<< [E:40902i S:38809 M:232820437 (Ack:85044668)] (S) Msg TX from 000000000001B669 to 1:0000000012344321 [C347] [UDP:[fe80::1732:2f32:5bb9:2fad%wlp0s20f3]:5540] --- Type 0000:10 (SecureChannel:StandaloneAck) (B:34)
[2026-04-15 13:12:28.000107][APP ][STDOUT][1776251547.998] [2009880:2009880] [DMG] IM RH moving to [CanStartReporting]
[2026-04-15 13:12:28.000194][TEST][STDOUT][MatterTest] 04-15 13:12:27.999 INFO Found an existing secure session to [1:0000000012344321]!
[2026-04-15 13:12:28.000357][APP ][STDOUT][1776251547.999] [2009880:2009880] [EM] >>> [E:40902r S:9978 M:232820437 (Ack:85044668)] (S) Msg RX from 1:000000000001B669 [C347] to 0000000012344321 --- Type 0000:10 (SecureChannel:StandaloneAck) (B:34)
[2026-04-15 13:12:28.000479][TEST][STDOUT][MatterTest] 04-15 13:12:27.999 INFO <<< [E:40903i S:38809 M:232820438] (S) Msg TX from 000000000001B669 to 1:0000000012344321 [C347] [UDP:[fe80::1732:2f32:5bb9:2fad%wlp0s20f3]:5540] --- Type 0001:08 (IM:InvokeCommandRequest) (B:89)
[2026-04-15 13:12:28.000506][APP ][STDOUT][1776251547.999] [2009880:2009880] [EM] Found matching exchange: 40902r, Delegate: (nil)
[2026-04-15 13:12:28.000691][APP ][STDOUT][1776251547.999] [2009880:2009880] [EM] Rxd Ack; Removing MessageCounter:85044668 from Retrans Table on exchange 40902r
[2026-04-15 13:12:28.000704][TEST][STDOUT][MatterTest] 04-15 13:12:27.999 INFO ??1 [E:40903i S:38809 M:232820438] (S) Msg Retransmission to 1:0000000012344321 scheduled for 343ms from now [State:Active II:500 AI:300 AT:4000]
[2026-04-15 13:12:28.000768][APP ][STDOUT][1776251547.999] [2009880:2009880] [EM] >>> [E:40903r S:9978 M:232820438] (S) Msg RX from 1:000000000001B669 [C347] to 0000000012344321 --- Type 0001:08 (IM:InvokeCommandRequest) (B:89)
[2026-04-15 13:12:28.000804][APP ][STDOUT][1776251547.999] [2009880:2009880] [EM] Handling via exchange: 40903r, Delegate: 0x55555bbc1200
[2026-04-15 13:12:28.000844][APP ][STDOUT][1776251547.999] [2009880:2009880] [DMG] Received command for Endpoint=0 Cluster=0x0000_0065 Command=0x0000_0000
[2026-04-15 13:12:28.001505][APP ][STDERR]==2009880==WARNING: MemorySanitizer: use-of-uninitialized-value
[2026-04-15 13:12:28.329906][APP ][STDERR]    #0 0x55555612bd2f in chip::Credentials::KeySetData::Serialize(chip::TLV::TLVWriter&) const /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/credentials/GroupDataProviderImpl.cpp:726:45
[2026-04-15 13:12:28.330043][APP ][STDERR]    #1 0x555555a562e5 in chip::DataAccessor::Save(chip::PersistentStorageDelegate*, chip::Span<unsigned char> const&) const /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/lib/support/PersistentData.h:47:36
[2026-04-15 13:12:28.330144][APP ][STDERR]    #2 0x55555611ddaf in chip::PersistableData<128ul>::Save(chip::PersistentStorageDelegate*) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/lib/support/PersistentData.h:110:81
[2026-04-15 13:12:28.330262][APP ][STDERR]    #3 0x55555611ddaf in chip::Credentials::GroupDataProviderImpl::SetKeySet(unsigned char, chip::Span<unsigned char const> const&, chip::Credentials::GroupDataProvider::KeySet const&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/credentials/GroupDataProviderImpl.cpp:1693:33
[2026-04-15 13:12:28.330395][APP ][STDERR]    #4 0x555556072f6e in chip::app::Clusters::GroupcastCluster::SetKeySet(chip::app::ConcreteCommandPath const&, chip::Access::SubjectDescriptor const&, unsigned short, unsigned short, chip::Optional<chip::Span<unsigned char const>> const&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/clusters/groupcast/GroupcastCluster.cpp:643:26
[2026-04-15 13:12:28.330529][APP ][STDERR]    #5 0x555556070603 in chip::app::Clusters::GroupcastCluster::JoinGroup(chip::app::ConcreteCommandPath const&, chip::app::Clusters::Groupcast::Commands::JoinGroup::DecodableType const&, chip::Access::SubjectDescriptor const&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/clusters/groupcast/GroupcastCluster.cpp:481:19
[2026-04-15 13:12:28.330644][APP ][STDERR]    #6 0x55555606e725 in chip::app::Clusters::GroupcastCluster::InvokeCommand(chip::app::DataModel::InvokeRequest const&, chip::TLV::TLVReader&, chip::app::CommandHandler*) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/clusters/groupcast/GroupcastCluster.cpp:128:18
[2026-04-15 13:12:28.330762][APP ][STDERR]    #7 0x555555a988fa in chip::app::CodegenDataModelProvider::InvokeCommand(chip::app::DataModel::InvokeRequest const&, chip::TLV::TLVReader&, chip::app::CommandHandler*) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/data-model-providers/codegen/CodegenDataModelProvider.cpp:172:25
[2026-04-15 13:12:28.330873][APP ][STDERR]    #8 0x55555635508c in chip::app::InteractionModelEngine::DispatchCommand(chip::app::CommandHandlerImpl&, chip::app::ConcreteCommandPath const&, chip::TLV::TLVReader&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/InteractionModelEngine.cpp:1814:83
[2026-04-15 13:12:28.330965][APP ][STDERR]    #9 0x555555ef7b3d in chip::app::CommandHandlerImpl::ProcessCommandDataIB(chip::app::CommandDataIB::Parser&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/CommandHandlerImpl.cpp:455:21
[2026-04-15 13:12:28.331059][APP ][STDERR]    #10 0x555555ef3faa in chip::app::CommandHandlerImpl::ProcessInvokeRequest(chip::System::PacketBufferHandle&&, bool) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/CommandHandlerImpl.cpp:307:22
[2026-04-15 13:12:28.331173][APP ][STDERR]    #11 0x555555ef3844 in chip::app::CommandHandlerImpl::OnInvokeCommandRequest(chip::app::CommandHandlerExchangeInterface&, chip::System::PacketBufferHandle&&, bool) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/CommandHandlerImpl.cpp:128:21
[2026-04-15 13:12:28.331281][APP ][STDERR]    #12 0x555556368e75 in chip::app::CommandResponseSender::OnInvokeCommandRequest(chip::Messaging::ExchangeContext*, chip::System::PacketBufferHandle&&, bool) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/CommandResponseSender.cpp:217:37
[2026-04-15 13:12:28.331397][APP ][STDERR]    #13 0x5555563479f9 in chip::app::InteractionModelEngine::OnInvokeCommandRequest(chip::Messaging::ExchangeContext*, chip::PayloadHeader const&, chip::System::PacketBufferHandle&&, bool) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/InteractionModelEngine.cpp:618:23
[2026-04-15 13:12:28.331510][APP ][STDERR]    #14 0x55555634ff9a in chip::app::InteractionModelEngine::OnMessageReceived(chip::Messaging::ExchangeContext*, chip::PayloadHeader const&, chip::System::PacketBufferHandle&&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/InteractionModelEngine.cpp:1078:18
[2026-04-15 13:12:28.331634][APP ][STDERR]    #15 0x5555562bdb31 in chip::Messaging::ExchangeContext::HandleMessage(unsigned int, chip::PayloadHeader const&, chip::BitFlags<chip::Messaging::MessageFlagValues, unsigned int>, chip::System::PacketBufferHandle&&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/messaging/ExchangeContext.cpp:617:31
[2026-04-15 13:12:28.331765][APP ][STDERR]    #16 0x5555562c2ca4 in chip::Messaging::ExchangeManager::OnMessageReceived(chip::PacketHeader const&, chip::PayloadHeader const&, chip::SessionHandle const&, chip::SessionMessageDelegate::DuplicateMessage, chip::System::PacketBufferHandle&&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/messaging/ExchangeMgr.cpp:403:19
[2026-04-15 13:12:28.331894][APP ][STDERR]    #17 0x5555562dc689 in chip::SessionManager::SecureUnicastMessageDispatch(chip::PacketHeader const&, chip::Transport::PeerAddress const&, chip::System::PacketBufferHandle&&, chip::Transport::MessageTransportContext*) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/transport/SessionManager.cpp:1024:14
[2026-04-15 13:12:28.332006][APP ][STDERR]    #18 0x5555562d9271 in chip::SessionManager::OnMessageReceived(chip::Transport::PeerAddress const&, chip::System::PacketBufferHandle&&, chip::Transport::MessageTransportContext*) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/transport/SessionManager.cpp:677:13
[2026-04-15 13:12:28.332125][APP ][STDERR]    #19 0x555556326ed4 in chip::Transport::Base::HandleMessageReceived(chip::Transport::PeerAddress const&, chip::System::PacketBufferHandle&&, chip::Transport::MessageTransportContext*) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/transport/raw/Base.h:127:20
[2026-04-15 13:12:28.332230][APP ][STDERR]    #20 0x555556326ed4 in chip::Transport::UDP::OnUdpReceive(chip::Inet::UDPEndPoint*, chip::System::PacketBufferHandle&&, chip::Inet::IPPacketInfo const*) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/transport/raw/UDP.cpp:122:10
[2026-04-15 13:12:28.332331][APP ][STDERR]    #21 0x555556172402 in chip::Inet::UDPEndPointImplSockets::HandlePendingIO(chip::BitFlags<chip::System::SocketEventFlags, unsigned char>) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:687:9
[2026-04-15 13:12:28.332414][APP ][STDERR]    #22 0x555556151d56 in chip::System::LayerImplSelect::HandleEvents() /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/system/SystemLayerImplSelect.cpp:671:21
[2026-04-15 13:12:28.332525][APP ][STDERR]    #23 0x555556183a39 in chip::DeviceLayer::Internal::GenericPlatformManagerImpl_POSIX<chip::DeviceLayer::PlatformManagerImpl>::_RunEventLoop() /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/include/platform/internal/GenericPlatformManagerImpl_POSIX.ipp:226:33
[2026-04-15 13:12:28.332611][APP ][STDERR]    #24 0x555555a7db33 in chip::DeviceLayer::PlatformManager::RunEventLoop() /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/include/platform/PlatformManager.h:408:37
[2026-04-15 13:12:28.332702][APP ][STDERR]    #25 0x555555a7db33 in ChipLinuxAppMainLoop(chip::ServerInitParams&, AppMainLoopImplementation*) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/examples/platform/linux/AppMain.cpp:1112:36
[2026-04-15 13:12:28.332756][APP ][STDERR]    #26 0x5555559a352d in main /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/main.cpp:41:5
[2026-04-15 13:12:28.332788][APP ][STDERR]    #27 0x7ffff7c2a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
[2026-04-15 13:12:28.332814][APP ][STDERR]    #28 0x7ffff7c2a28a in __libc_start_main csu/../csu/libc-start.c:360:3
[2026-04-15 13:12:28.332878][APP ][STDERR]    #29 0x555555919024 in _start (/home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/chip-all-clusters-app+0x3c5024) (BuildId: dbcb1ecc712fefa70855d78c0938415d6f0a1f5e)
[2026-04-15 13:12:28.332883][APP ][STDERR]
[2026-04-15 13:12:28.332900][APP ][STDERR]  Uninitialized value was stored to memory at
[2026-04-15 13:12:28.333016][APP ][STDERR]    #0 0x55555611e13a in chip::Credentials::GroupDataProviderImpl::SetKeySet(unsigned char, chip::Span<unsigned char const> const&, chip::Credentials::GroupDataProvider::KeySet const&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/credentials/GroupDataProviderImpl.cpp:1670:43
[2026-04-15 13:12:28.333153][APP ][STDERR]    #1 0x555556072f6e in chip::app::Clusters::GroupcastCluster::SetKeySet(chip::app::ConcreteCommandPath const&, chip::Access::SubjectDescriptor const&, unsigned short, unsigned short, chip::Optional<chip::Span<unsigned char const>> const&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/clusters/groupcast/GroupcastCluster.cpp:643:26
[2026-04-15 13:12:28.333284][APP ][STDERR]    #2 0x555556070603 in chip::app::Clusters::GroupcastCluster::JoinGroup(chip::app::ConcreteCommandPath const&, chip::app::Clusters::Groupcast::Commands::JoinGroup::DecodableType const&, chip::Access::SubjectDescriptor const&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/clusters/groupcast/GroupcastCluster.cpp:481:19
[2026-04-15 13:12:28.333399][APP ][STDERR]    #3 0x55555606e725 in chip::app::Clusters::GroupcastCluster::InvokeCommand(chip::app::DataModel::InvokeRequest const&, chip::TLV::TLVReader&, chip::app::CommandHandler*) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/clusters/groupcast/GroupcastCluster.cpp:128:18
[2026-04-15 13:12:28.333516][APP ][STDERR]    #4 0x555555a988fa in chip::app::CodegenDataModelProvider::InvokeCommand(chip::app::DataModel::InvokeRequest const&, chip::TLV::TLVReader&, chip::app::CommandHandler*) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/data-model-providers/codegen/CodegenDataModelProvider.cpp:172:25
[2026-04-15 13:12:28.333626][APP ][STDERR]    #5 0x55555635508c in chip::app::InteractionModelEngine::DispatchCommand(chip::app::CommandHandlerImpl&, chip::app::ConcreteCommandPath const&, chip::TLV::TLVReader&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/InteractionModelEngine.cpp:1814:83
[2026-04-15 13:12:28.333719][APP ][STDERR]    #6 0x555555ef7b3d in chip::app::CommandHandlerImpl::ProcessCommandDataIB(chip::app::CommandDataIB::Parser&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/CommandHandlerImpl.cpp:455:21
[2026-04-15 13:12:28.333813][APP ][STDERR]    #7 0x555555ef3faa in chip::app::CommandHandlerImpl::ProcessInvokeRequest(chip::System::PacketBufferHandle&&, bool) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/CommandHandlerImpl.cpp:307:22
[2026-04-15 13:12:28.333921][APP ][STDERR]    #8 0x555555ef3844 in chip::app::CommandHandlerImpl::OnInvokeCommandRequest(chip::app::CommandHandlerExchangeInterface&, chip::System::PacketBufferHandle&&, bool) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/CommandHandlerImpl.cpp:128:21
[2026-04-15 13:12:28.334028][APP ][STDERR]    #9 0x555556368e75 in chip::app::CommandResponseSender::OnInvokeCommandRequest(chip::Messaging::ExchangeContext*, chip::System::PacketBufferHandle&&, bool) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/CommandResponseSender.cpp:217:37
[2026-04-15 13:12:28.334147][APP ][STDERR]    #10 0x5555563479f9 in chip::app::InteractionModelEngine::OnInvokeCommandRequest(chip::Messaging::ExchangeContext*, chip::PayloadHeader const&, chip::System::PacketBufferHandle&&, bool) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/InteractionModelEngine.cpp:618:23
[2026-04-15 13:12:28.334262][APP ][STDERR]    #11 0x55555634ff9a in chip::app::InteractionModelEngine::OnMessageReceived(chip::Messaging::ExchangeContext*, chip::PayloadHeader const&, chip::System::PacketBufferHandle&&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/InteractionModelEngine.cpp:1078:18
[2026-04-15 13:12:28.334386][APP ][STDERR]    #12 0x5555562bdb31 in chip::Messaging::ExchangeContext::HandleMessage(unsigned int, chip::PayloadHeader const&, chip::BitFlags<chip::Messaging::MessageFlagValues, unsigned int>, chip::System::PacketBufferHandle&&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/messaging/ExchangeContext.cpp:617:31
[2026-04-15 13:12:28.334516][APP ][STDERR]    #13 0x5555562c2ca4 in chip::Messaging::ExchangeManager::OnMessageReceived(chip::PacketHeader const&, chip::PayloadHeader const&, chip::SessionHandle const&, chip::SessionMessageDelegate::DuplicateMessage, chip::System::PacketBufferHandle&&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/messaging/ExchangeMgr.cpp:403:19
[2026-04-15 13:12:28.334641][APP ][STDERR]    #14 0x5555562dc689 in chip::SessionManager::SecureUnicastMessageDispatch(chip::PacketHeader const&, chip::Transport::PeerAddress const&, chip::System::PacketBufferHandle&&, chip::Transport::MessageTransportContext*) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/transport/SessionManager.cpp:1024:14
[2026-04-15 13:12:28.334754][APP ][STDERR]    #15 0x5555562d9271 in chip::SessionManager::OnMessageReceived(chip::Transport::PeerAddress const&, chip::System::PacketBufferHandle&&, chip::Transport::MessageTransportContext*) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/transport/SessionManager.cpp:677:13
[2026-04-15 13:12:28.334866][APP ][STDERR]    #16 0x555556326ed4 in chip::Transport::Base::HandleMessageReceived(chip::Transport::PeerAddress const&, chip::System::PacketBufferHandle&&, chip::Transport::MessageTransportContext*) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/transport/raw/Base.h:127:20
[2026-04-15 13:12:28.334969][APP ][STDERR]    #17 0x555556326ed4 in chip::Transport::UDP::OnUdpReceive(chip::Inet::UDPEndPoint*, chip::System::PacketBufferHandle&&, chip::Inet::IPPacketInfo const*) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/transport/raw/UDP.cpp:122:10
[2026-04-15 13:12:28.335072][APP ][STDERR]    #18 0x555556172402 in chip::Inet::UDPEndPointImplSockets::HandlePendingIO(chip::BitFlags<chip::System::SocketEventFlags, unsigned char>) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:687:9
[2026-04-15 13:12:28.335160][APP ][STDERR]    #19 0x555556151d56 in chip::System::LayerImplSelect::HandleEvents() /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/system/SystemLayerImplSelect.cpp:671:21
[2026-04-15 13:12:28.335273][APP ][STDERR]    #20 0x555556183a39 in chip::DeviceLayer::Internal::GenericPlatformManagerImpl_POSIX<chip::DeviceLayer::PlatformManagerImpl>::_RunEventLoop() /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/include/platform/internal/GenericPlatformManagerImpl_POSIX.ipp:226:33
[2026-04-15 13:12:28.335277][APP ][STDERR]
[2026-04-15 13:12:28.335304][APP ][STDERR]  Uninitialized value was created by an allocation of 'ks' in the stack frame
[2026-04-15 13:12:28.335439][APP ][STDERR]    #0 0x555556072ada in chip::app::Clusters::GroupcastCluster::SetKeySet(chip::app::ConcreteCommandPath const&, chip::Access::SubjectDescriptor const&, unsigned short, unsigned short, chip::Optional<chip::Span<unsigned char const>> const&) /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/clusters/groupcast/GroupcastCluster.cpp:607:5
[2026-04-15 13:12:28.335444][APP ][STDERR]
[2026-04-15 13:12:28.335544][APP ][STDERR]SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/connectedhomeip/out/linux-x64-all-clusters-msan-clang/../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/credentials/GroupDataProviderImpl.cpp:726:45 in chip::Credentials::KeySetData::Serialize(chip::TLV::TLVWriter&) const
[2026-04-15 13:12:28.335551][APP ][STDERR]Exiting
[2026-04-15 13:12:28.343915][TEST][STDOUT][MatterTest] 04-15 13:12:28.343 INFO <<1 [E:40903i S:38809 M:232820438] (S) Msg Retransmission to 1:0000000012344321
[2026-04-15 13:12:28.344477][TEST][STDOUT][MatterTest] 04-15 13:12:28.344 INFO ??2 [E:40903i S:38809 M:232820438] (S) Msg Retransmission to 1:0000000012344321 scheduled for 361ms from now [State:Active II:500 AI:300 AT:4000]
[2026-04-15 13:12:28.706348][TEST][STDOUT][MatterTest] 04-15 13:12:28.706 INFO <<2 [E:40903i S:38809 M:232820438] (S) Msg Retransmission to 1:0000000012344321
[2026-04-15 13:12:28.706504][TEST][STDOUT][MatterTest] 04-15 13:12:28.706 INFO ??3 [E:40903i S:38809 M:232820438] (S) Msg Retransmission to 1:0000000012344321 scheduled for 533ms from now [State:Active II:500 AI:300 AT:4000]
[2026-04-15 13:12:29.240565][TEST][STDOUT][MatterTest] 04-15 13:12:29.240 INFO <<3 [E:40903i S:38809 M:232820438] (S) Msg Retransmission to 1:0000000012344321
[2026-04-15 13:12:29.240898][TEST][STDOUT][MatterTest] 04-15 13:12:29.240 INFO ??4 [E:40903i S:38809 M:232820438] (S) Msg Retransmission to 1:0000000012344321 scheduled for 918ms from now [State:Active II:500 AI:300 AT:4000]
[2026-04-15 13:12:30.159592][TEST][STDOUT][MatterTest] 04-15 13:12:30.159 INFO <<4 [E:40903i S:38809 M:232820438] (S) Msg Retransmission to 1:0000000012344321
[2026-04-15 13:12:30.159894][TEST][STDOUT][MatterTest] 04-15 13:12:30.159 INFO ??5 [E:40903i S:38809 M:232820438] (S) Msg Retransmission to 1:0000000012344321 scheduled for 1542ms from now [State:Active II:500 AI:300 AT:4000]
^C2026-04-15 13:12:30 ayapad __main__[2009878] INFO Stopping app restart monitor thread
[2026-04-15 13:12:30.427659][TEST][STDOUT][MatterTest] 04-15 13:12:30.427 INFO [Test] test_TC_GC_2_3 None
[2026-04-15 13:12:30.438101][TEST][STDOUT][MatterTest] 04-15 13:12:30.437 INFO ===== EXECUTION FLAGS SUMMARY BEGIN =====
[2026-04-15 13:12:30.438164][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO Config values:
[2026-04-15 13:12:30.438205][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - admin_vendor_id: 65521
[2026-04-15 13:12:30.438238][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - app_pid: 0
[2026-04-15 13:12:30.438280][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - case_admin_subject: 112233
[2026-04-15 13:12:30.438318][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - commission_only: False
[2026-04-15 13:12:30.438365][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - commissioning_method: 'on-network'
[2026-04-15 13:12:30.438408][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - controller_cat_tags: [65537]
[2026-04-15 13:12:30.438448][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - controller_node_id: 112233
[2026-04-15 13:12:30.438482][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - debug: False
[2026-04-15 13:12:30.438520][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - discriminators: [3840]
[2026-04-15 13:12:30.438561][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - dut_node_ids: [305414945]
[2026-04-15 13:12:30.438594][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - endpoint: 0
[2026-04-15 13:12:30.438629][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - fabric_id: 1
[2026-04-15 13:12:30.438671][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - fail_on_skipped_tests: True
[2026-04-15 13:12:30.438705][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - legacy: False
[2026-04-15 13:12:30.438754][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - logs_path: '/tmp/matter_testing/logs'
[2026-04-15 13:12:30.438800][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - maximize_cert_chains: True
[2026-04-15 13:12:30.438892][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - paa_trust_store_path: '/home/connectedhomeip/credentials/development/paa-root-certs'
[2026-04-15 13:12:30.438945][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - pics: Please request if needed
[2026-04-15 13:12:30.439010][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - restart_flag_file: '/tmp/chip_test_restart_app_77c19648'
[2026-04-15 13:12:30.439053][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - root_of_trust_index: 1
[2026-04-15 13:12:30.439098][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - setup_passcodes: [20202021]
[2026-04-15 13:12:30.439151][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - storage_path: 'admin_storage.json'
[2026-04-15 13:12:30.439178][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO 
[2026-04-15 13:12:30.439185][TEST][STDOUT]
[2026-04-15 13:12:30.439198][TEST][STDOUT]Named args:
[2026-04-15 13:12:30.439262][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - certificate_authority_manager: 'fc8ea97e-38bb-11f1-8f1e-0072eecd9f9c'
[2026-04-15 13:12:30.439320][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - default_controller: 'fc8ea97b-38bb-11f1-8f1e-0072eecd9f9c'
[2026-04-15 13:12:30.439372][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - hooks: 'fc8ea97d-38bb-11f1-8f1e-0072eecd9f9c'
[2026-04-15 13:12:30.439427][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - matter_stack: 'fc8ea97a-38bb-11f1-8f1e-0072eecd9f9c'
[2026-04-15 13:12:30.439485][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO   - matter_test_config: 'fc8ea97c-38bb-11f1-8f1e-0072eecd9f9c'
[2026-04-15 13:12:30.439603][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO ===== PICS_SDK_CI_ONLY is enabled (True) for test 'TC_GC_2_3'.
[2026-04-15 13:12:30.439648][TEST][STDERR]Traceback (most recent call last):
[2026-04-15 13:12:30.439836][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO ===== EXECUTION FLAGS SUMMARY END =====
[2026-04-15 13:12:30.440010][TEST][STDERR]  File "/home/connectedhomeip/src/python_testing/TC_GC_2_3.py", line 222, in <module>
[2026-04-15 13:12:30.440121][TEST][STDERR]    default_matter_test_main()
[2026-04-15 13:12:30.440269][TEST][STDOUT][MatterTest] 04-15 13:12:30.438 INFO Summary for test class TC_GC_2_3: Error 1, Executed 1, Failed 0, Passed 0, Requested 1, Skipped 0
[2026-04-15 13:12:30.440528][TEST][STDOUT][MatterTest] 04-15 13:12:30.439 INFO Summary for test run MatterTest@04-15-2026_13-12-27-326:

```
</details>

### PR DESCRIPTION
**Pull request by Alami-Amine**
#### Summary

- Fixes https://github.com/project-chip/connectedhomeip/issues/71584

- `epoch.start_time` was left uninitialised when `GroupcastCluster::SetKeySet` created a new keyset due to a call of `GroupcastCluster::JoinGroup` with a Key provided.
- in Spec, under Groupcast Cluster (11.27.7.1. JoinGroup Command), `EpochStartTime0` SHALL be initialised to 1 in that case

- Follow-up: make initialisation of GroupDataProvider::KeySet safer

#### Related Issues

- Test Plan PR: https://github.com/CHIP-Specifications/chip-test-plans/pull/6051
- This is part of the effort: https://github.com/project-chip/connectedhomeip/issues/71500
#### Testing
- Added a new Step that validates the  GroupKeySet after JoinGroup command in `TC_GC_2_3.py`
- Added validation of GroupKeySet after JoinGroup command in TestGroupcastCluster

- ran MSAN Unit Tests locally and made sure TestGroupcastCluster is passing
- ran MSAN All Clusters Locally against `TC_GC_2_*.py`

### CODE REVIEW

File: src/app/clusters/groupcast/GroupcastCluster.cpp [hunk 1]
```diff
@@ -632,6 +632,7 @@ Status GroupcastCluster::SetKeySet(const ConcreteCommandPath & path, const chip:
         GroupDataProvider::EpochKey & epoch = ks.epoch_keys[0];
         VerifyOrReturnValue(key.Value().size() == GroupDataProvider::EpochKey::kLengthBytes, Status::ConstraintError);
         memcpy(epoch.key, key.Value().data(), GroupDataProvider::EpochKey::kLengthBytes);
+        epoch.start_time = 1;
```
Comment (Alami-Amine) [inline src/app/clusters/groupcast/GroupcastCluster.cpp:635]: Putting this on hold until SVE

[the remark this answers is not in the document]
Comment (Alami-Amine) [reply src/app/clusters/groupcast/GroupcastCluster.cpp:635]: hallucination alert!

**Review by jmartinez-silabs — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

File: src/python_testing/TC_GC_2_3.py [hunk 2]
```diff
@@ -60,7 +61,8 @@ def steps_TC_GC_2_3(self):
             TestStep("1b", "TH removes any existing group and KeySetID on the DUT"),
             TestStep("1c", "TH subscribes to Membership attribute with min interval 0s and max interval 30s"),
             TestStep("1d", "Join Group G1 generating a new Key with KeySetID K1 using JoinGroup"),
-            TestStep("1e", "Join Group G2 generating a new Key with KeySetID K2 using JoinGroup"),
+            TestStep("1e", "TH reads back KeySetID K1 via GroupKeyManagement KeySetRead and validates the returned GroupKeySetStruct"),
```
Comment (jmartinez-silabs) [inline src/python_testing/TC_GC_2_3.py]: test plan will have to be updated too

File: src/app/clusters/groupcast/GroupcastCluster.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (Alami-Amine) [reply src/app/clusters/groupcast/GroupcastCluster.cpp:635]: Yes this is planned as a follow-up already

File: src/python_testing/TC_GC_2_3.py (hunk 2 above)
Comment (Alami-Amine) [reply src/python_testing/TC_GC_2_3.py]: done here: https://github.com/CHIP-Specifications/chip-test-plans/pull/6051
