### PR TITLE
[NWPROV] Fix spec compliance issues

### LINKED ISSUE #17010: Network Commissioning cluster has many subtle spec deviations due to non-spec XML
#### Problem
Apart from not setting various string max lengths, we have the following deviations from the spec:

* `Security` field of `WiFiInterfaceScanResult` has wrong type.
* `PanId` and `ExtendedAddress` fields of `ThreadInterfaceScanResult` have wrong types.
* `ScanMaxTimeSeconds` and `ConnectMaxTimeSeconds` attributes are not marked optional, even though they would not be present on an "Ethernet" version of the cluster.
* `SSID` field in `ScanNetworks` needs to be nullable and optional.
* `DebugText` field in `ScanNetworksResponse` needs to be optional.
* `DebugText` field in `ConnectNetworkResponse` needs to be optional.

 #### Proposed Solution
Apply attached diff to the XML, then regenerate and fix whatever C++ code needs fixing.
[network-commissioning.txt](https://github.com/project-chip/connectedhomeip/files/8412330/network-commissioning.txt)

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem

Fixes #17010 

Some definitions in network commissioning cluster does not match the spec

#### Change overview
- Update the xml and the code
- Apply some trivial changes to platform code

#### Testing
Build should pass.

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by Damian-Nordic — APPROVED** [review]

**Review by tcarmelveilleux — APPROVED** [review]

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 1]
```diff
@@ -79,6 +79,28 @@ NetworkCommissioning::WiFiBand ToClusterObjectEnum(DeviceLayer::NetworkCommissio
     return static_cast<ClusterObject>(to_underlying(band));
 }
 
+chip::BitFlags<NetworkCommissioning::WiFiSecurity>
+ToClusterObjectBitFlags(const chip::BitFlags<DeviceLayer::NetworkCommissioning::WiFiSecurity> & security)
+{
+    using ClusterObject     = NetworkCommissioning::WiFiSecurity;
+    using PlatformInterface = NetworkCommissioning::WiFiSecurity;
```
Comment (bzbarsky-apple) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:86]: These are the same type, so the asserts below are trivially going to pass.

What I would suggests is that we get rid of `DeviceLayer::NetworkCommissioning::WiFiSecurity` and include `cluster-enums.h` in the relevant places so we can use `Clusters::NetworkCommissioning::WiFiSecurity` directly.

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 2]
```diff
@@ -272,8 +294,19 @@ void Instance::HandleScanNetworks(HandlerContext & ctx, const Commands::ScanNetw
...
+        {
+            ctx.mCommandHandler.AddStatus(ctx.mRequestPath, Protocols::InteractionModel::Status::InvalidCommand);
+            return;
+        }
+        const auto nullableSSID = req.ssid.Value();
+        ByteSpan ssid;
+        if (!nullableSSID.IsNull())
+        {
+            ssid = nullableSSID.Value();
+        }
```
Comment (bzbarsky-apple) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:307]: This should enforce the "1 to 32" length constraint from the spec.

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 3]
```diff
@@ -272,8 +294,19 @@ void Instance::HandleScanNetworks(HandlerContext & ctx, const Commands::ScanNetw
...
         mAsyncCommandHandle = CommandHandler::Handle(&ctx.mCommandHandler);
-        mpDriver.Get<WiFiDriver *>()->ScanNetworks(req.ssid, this);
+        mpDriver.Get<WiFiDriver *>()->ScanNetworks(ssid, this);
```
Comment (bzbarsky-apple) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:309]: Unfortunately, the driver interface is not documented very well, so the implementations of it differ in how they handle the SSID.  For example, `src/platform/Ameba/NetworkCommissioningWiFiDriver.cpp` checks `ssid.data()` to decide whether we're doing a single-ssid scan or general scan, while `src/platform/EFR32/NetworkCommissioningWiFiDriver.cpp` checks `ssid.size()`.  If we checked the size here the difference would at least not be observable, but as it is they would reply differently to the same protocol message.

My recommendation would be to change the driver API to have separate functions for "scan for networks with the given SSID" and "scan for all networks" so the only place where we have to make that decision is here.

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 4]
```diff
@@ -392,28 +425,27 @@ void Instance::OnResult(Status commissioningError, CharSpan errorText, int32_t i
...
     response.networkingStatus = ToClusterObjectEnum(commissioningError);
-    response.debugText        = errorText;
-    response.errorValue       = interfaceStatus;
-    commandHandle->AddResponse(mPath, response);
-
-    mLastNetworkIDLen = mConnectingNetworkIDLen;
-    memcpy(mLastNetworkID, mConnectingNetworkID, mLastNetworkIDLen);
-    mLastNetworkingStatusValue.SetNonNull(ToClusterObjectEnum(commissioningError));
-
+    if (debugText.size() != 0)
```
Comment (bzbarsky-apple) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:428]: Should be using `empty()`, really.

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 5]
```diff
@@ -436,28 +468,33 @@ void Instance::OnFinished(Status status, CharSpan debugText, ThreadScanResponseI
...
 
     SuccessOrExit(err = commandHandle->PrepareCommand(
                       ConcreteCommandPath(mPath.mEndpointId, NetworkCommissioning::Id, Commands::ScanNetworksResponse::Id)));
     VerifyOrExit((writer = commandHandle->GetCommandDataIBTLVWriter()) != nullptr, err = CHIP_ERROR_INCORRECT_STATE);
 
     SuccessOrExit(err = writer->Put(TLV::ContextTag(to_underlying(Commands::ScanNetworksResponse::Fields::kNetworkingStatus)),
                                     ToClusterObjectEnum(status)));
-    SuccessOrExit(err = DataModel::Encode(
-                      *writer, TLV::ContextTag(to_underlying(Commands::ScanNetworksResponse::Fields::kDebugText)), debugText));
+    if (debugText.size() != 0)
```
Comment (bzbarsky-apple) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:479]: `empty()`.

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 6]
```diff
@@ -436,28 +468,33 @@ void Instance::OnFinished(Status status, CharSpan debugText, ThreadScanResponseI
     TLV::TLVType listContainerType;
     ThreadScanResponse scanResponse;
     size_t networksEncoded = 0;
+    uint8_t extendedAddressBuffer[8];
```
Comment (bzbarsky-apple) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:471]: That `8` should be a constant defined somewhere.  I would be very surprised if we do not have a constant for this already.

File: src/app/clusters/network-commissioning/network-commissioning.cpp (hunk 1 above)
Comment (erjiaqing) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:86]: This is discuessed before, and we want to avoid using cluster-enums in platform code.

Comment (bzbarsky-apple) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:86]: cluster-enums was _specifically_ created so it can be used in platform code.  Not to be confused with non-ABI-stable cluster-objects.

Comment (tcarmelveilleux) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:86]: +1 `cluster-enums.h` is usable in platform layer and was introduced to avoid this
