### PR TITLE
[ACE] perform initial ACL checks before existence checks to avoid leaking non-existence (For Writes and Commands)

### LINKED ISSUE #37342: Implement spec requirement of "ACL check before existence check"
This request is to implement https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/9024

This should be done after #37322 merges and we should fix the TODO in `WriteHandler::CheckWriteAllowed`.

The issue is that we the existing ordering allows someone with insufficient rights on a cluster still determine what attributes it supports by seeing a difference between "access denied" and "unsupported attribute".

#35336 tried to address it a long time ago, however it was failing CI and code was restructured significantly since then. We can pick up some bits/ideas from there ... like we need to fix BOTH attributes and commands. However overall I expect we need very different/new code (we do not need to be inside ember/ember-compatibility anymore).

### PR DESCRIPTION
**Pull request by Alami-Amine**
#### Summary
- Perform initial ACL checks before existence checks to determine if the subject **would have had at least some access**, so that we do not **leak** **"non-existence"** if subject doesn't have any access.
- This is only done for Attribute Writes and Command Invocation in this PR.

#### Related issues

- This is based on the Spec changes introduced in https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/11812
- This fixes: https://github.com/project-chip/connectedhomeip/issues/37342

#### Testing

- Added Unit Tests to make sure we get Unsupported Access rather than UnsupportedEndpoint/Cluster/Attribute
- Integration Tests run, and more detailed Integration Tests are upcoming
- manual Testing `Chip-Tool` vs `All-Clusters-App` before and after changes and making sure we always get UnsupportedAccess instead of UnsupportedEndpoint/UnsupportedCluster
```bash
# Restricting Access
./chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects":[112233], "targets": [{ "cluster":31, "endpoint":0, "deviceType":null}]}]' 33 0

# Write Request on an Unsupported Endpoint
./chip-tool thermostatuserinterfaceconfiguration write temperature-display-mode 2 33 8

# Write Request on an Unsupported Cluster (DoorLock is not part of All-clusters-App)
./chip-tool doorlock write open-period 30 33 1

# Command Invoke on an unsupported Endpoint
./chip-tool thermostat setpoint-raise-lower 0 10 33 8
```

### CODE REVIEW

File: src/app/InteractionModelEngine.cpp [hunk 1]
```diff
@@ -1812,18 +1812,19 @@ Protocols::InteractionModel::Status InteractionModelEngine::ValidateCommandCanBe
 
     DataModel::AcceptedCommandEntry acceptedCommandEntry;
 
-    Status status = CheckCommandExistence(request.path, acceptedCommandEntry);
+    Status existenceStatus = CheckCommandExistence(request.path, acceptedCommandEntry);
 
-    if (status != Status::Success)
+    Status accessStatus = CheckCommandAccess(request, acceptedCommandEntry);
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.cpp]: If the thing doesn't exist, then `CheckCommandAccess` is nonsense, because the `acceptedCommandEntry` is nonsense, no?  `acceptedCommandEntry` is an outparam from `CheckCommandExistence` and you can only assume it's set on success.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/InteractionModelEngine.cpp [hunk 2]
```diff
@@ -1796,7 +1796,10 @@ Protocols::InteractionModel::Status InteractionModelEngine::ValidateCommandCanBe
 
     DataModel::AcceptedCommandEntry acceptedCommandEntry;
 
-    Status status = CheckCommandExistence(request.path, acceptedCommandEntry);
+    Status status = CheckCommandAccess(request, Access::Privilege::kOperate);
+    VerifyOrReturnValue(status == Status::Success, status);
```
[the remark this answers is not in the document]
Comment (Alami-Amine) [reply src/app/InteractionModelEngine.cpp:1806]: done

File: src/app/WriteHandler.h [hunk 3]
```diff
@@ -194,6 +194,9 @@ class WriteHandler : public Messaging::ExchangeDelegate
     DataModel::ActionReturnStatus CheckWriteAllowed(const Access::SubjectDescriptor & aSubject,
                                                     const ConcreteAttributePath & aPath);
 
+    // TODO add comment
+    Status CheckWriteAccess(const Access::SubjectDescriptor & aSubject, const ConcreteAttributePath & aPath,
+                            const std::optional<DataModel::AttributeEntry> & attributeEntry);
```
[the remark this answers is not in the document]
Comment (Alami-Amine) [reply src/app/WriteHandler.h]: outdated

File: src/app/InteractionModelEngine.cpp (hunk 1 above)
Comment (Alami-Amine) [reply src/app/InteractionModelEngine.cpp]: Yup the whole approach was changed, resolving comment

**Review by tcarmelveilleux — APPROVED** [review]

File: src/app/InteractionModelEngine.cpp [hunk 4]
```diff
@@ -1796,7 +1796,13 @@ Protocols::InteractionModel::Status InteractionModelEngine::ValidateCommandCanBe
 
     DataModel::AcceptedCommandEntry acceptedCommandEntry;
 
-    Status status = CheckCommandExistence(request.path, acceptedCommandEntry);
+    // Execute the ACL Access Granting Algorithm before existence checks, assuming the required_privilege for the element is
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.cpp:1799]: Technically, this is not implementing what the spec says, because in the non-concrete-path case there should be only one ACL check, but we are going to end up doing two here because the group path case calls this code too.

Now in practice this difference in behavior is not observable _if all commands have at least Operate privilege required_, but it might be worth documenting that this divergence from the plain text of the spec is happening and why it's OK, either here or at the callsite in CommandHandlerImpl in the group case, or both.

File: src/app/InteractionModelEngine.h [hunk 5]
```diff
@@ -630,7 +630,7 @@ class InteractionModelEngine : public Messaging::UnsolicitedMessageHandler,
      * Validates that the command exists and on success returns the data for the command in `entry`.
      */
     Status CheckCommandExistence(const ConcreteCommandPath & aCommandPath, DataModel::AcceptedCommandEntry & entry);
-    Status CheckCommandAccess(const DataModel::InvokeRequest & aRequest, const DataModel::AcceptedCommandEntry & entry);
+    Status CheckCommandAccess(const DataModel::InvokeRequest & aRequest, const Access::Privilege & aRequiredPrivilege);
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.h]: Why not just pass the enum by value?

File: src/app/WriteHandler.cpp [hunk 6]
```diff
@@ -764,14 +764,12 @@ void WriteHandler::MoveToState(const State aTargetState)
...
-    // TODO: ordering is to check writability/existence BEFORE ACL and this seems wrong, however
-    //       existing unit tests (TC_AcessChecker.py) validate that we get UnsupportedWrite instead of UnsupportedAccess
-    //
-    //       This should likely be fixed in spec (probably already fixed by
-    //       https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/9024)
-    //       and tests and implementation
-    //
-    //       Open issue that needs fixing: https://github.com/project-chip/connectedhomeip/issues/33735
+
+    // Execute the ACL Access Granting Algorithm before existence checks, assuming the required_privilege for the element is
```
Comment (bzbarsky-apple) [inline src/app/WriteHandler.cpp:768]: Again, this does not technically match spec for the group case, but the difference should not be observable.  Needs to be documented clearly so people don't get confused.

File: src/app/WriteHandler.h [hunk 7]
```diff
@@ -194,6 +194,12 @@ class WriteHandler : public Messaging::ExchangeDelegate
     DataModel::ActionReturnStatus CheckWriteAllowed(const Access::SubjectDescriptor & aSubject,
                                                     const ConcreteAttributePath & aPath);
 
+    /// Validate that a write on the given path has aRequiredPrivilege.
+    ///
+    /// Returns a success status if the ACL check is successfull, otherwise the relevant status will be returned.
+    Status CheckWriteAccess(const Access::SubjectDescriptor & aSubject, const ConcreteAttributePath & aPath,
+                            const Access::Privilege & aRequiredPrivilege);
```
Comment (bzbarsky-apple) [inline src/app/WriteHandler.h]: Why passing the enum by reference?

File: src/app/tests/TestAclAttribute.cpp
Comment (bzbarsky-apple) [inline src/app/tests/TestAclAttribute.cpp:1]: I did not carefully review this file, or any of the other test bits.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/InteractionModelEngine.h (hunk 5 above)
Comment (Alami-Amine) [reply src/app/InteractionModelEngine.h]: True, done

File: src/app/WriteHandler.h [hunk 8]
```diff
@@ -194,6 +194,12 @@ class WriteHandler : public Messaging::ExchangeDelegate
     DataModel::ActionReturnStatus CheckWriteAllowed(const Access::SubjectDescriptor & aSubject,
                                                     const ConcreteAttributePath & aPath);
 
+    /// Validate that a write on the given path has aRequiredPrivilege.
+    ///
+    /// Returns a success status if the ACL check is successfull, otherwise the relevant status will be returned.
```
[the remark this answers is not in the document]
Comment (Alami-Amine) [reply src/app/WriteHandler.h]: done

File: src/python_testing/TC_AccessChecker.py [hunk 9]
```diff
@@ -300,10 +300,10 @@ async def _run_write_access_test_for_cluster_privilege(self, endpoint_id, cluste
 
             resp = await self.TH2.WriteAttribute(nodeid=self.dut_node_id, attributes=[(endpoint_id, attribute(val))])
             if spec_requires == Clusters.AccessControl.Enums.AccessControlEntryPrivilegeEnum.kUnknownEnumValue:
-                # not writeable - expect an unsupported write response
-                if resp[0].Status != Status.UnsupportedWrite:
+                # not writeable - expect either an unsupported write response or an unsupported access response (since ACL privilege check happens before writable check)
+                if (resp[0].Status != Status.UnsupportedWrite and resp[0].Status != Status.UnsupportedAccess):
```
[the remark this answers is not in the document]
Comment (Alami-Amine) [reply src/python_testing/TC_AccessChecker.py]: done

File: src/app/WriteHandler.h (hunk 7 above)
Comment (Alami-Amine) [reply src/app/WriteHandler.h]: True, done

File: src/app/WriteHandler.cpp (hunk 6 above)
Comment (Alami-Amine) [reply src/app/WriteHandler.cpp:768]: done

File: src/app/InteractionModelEngine.cpp (hunk 4 above)
Comment (Alami-Amine) [reply src/app/InteractionModelEngine.cpp:1799]: done

File: src/app/tests/TestAclAttribute.cpp
Comment (Alami-Amine) [reply src/app/tests/TestAclAttribute.cpp:1]: Noted

File: src/app/InteractionModelEngine.cpp [hunk 10]
```diff
@@ -1812,18 +1812,19 @@ Protocols::InteractionModel::Status InteractionModelEngine::ValidateCommandCanBe
 
     DataModel::AcceptedCommandEntry acceptedCommandEntry;
 
-    Status status = CheckCommandExistence(request.path, acceptedCommandEntry);
+    Status existenceStatus = CheckCommandExistence(request.path, acceptedCommandEntry);
 
-    if (status != Status::Success)
+    Status accessStatus = CheckCommandAccess(request, acceptedCommandEntry);
+    VerifyOrReturnValue(accessStatus == Status::Success, accessStatus);
```
[the remark this answers is not in the document]
Comment (Alami-Amine) [reply src/app/InteractionModelEngine.cpp]: similar comment done
