### PR TITLE
[IM]Fix leaked readClient in onFabricRemoved call

### LINKED ISSUE #36920: [BUG] Heap-Use-After-Free (UAF) in tv-casting-app when deleting a fabric after casting
### Reproduction steps

1. Build the `tv-casting-app` with AddressSanitizer (ASAN) enabled.
2. Open Terminal 1 and start the `tv-casting-app`:
    
    ```bash
    $ ./tv-casting-app
    ```
    
3. Open Terminal 2 and start the `tv-app`:
    
    ```bash
    $ ./tv-app
    ```
    
4. In the `tv-casting-app` shell, send a cast request:
    
    ```bash
    tv-casting-app > cast request 0
    ```
    
5. In the `tv-app` shell, respond with:
    
    ```bash
    tv-app > controller ux ok
    ```
    
6. In the `tv-casting-app`, print the list of fabrics and delete a specific fabric:
    
    ```bash
    tv-casting-app > cast print-fabrics
    tv-casting-app > cast delete-fabric <fabricId>
    ```
    
7. Observe the ASAN output in `tv-casting-app` indicating a heap-use-after-free issue.
[tv-casting-app UAF.txt](https://github.com/user-attachments/files/18207572/tv-casting-app.UAF.txt)

### Summary

A heap-use-after-free (UAF) issue occurs in the `tv-casting-app` when the `delete-fabric` command is executed. After removing a fabric, the system attempts to access a freed `ReadClient` object.

### Analysis and Description

The issue arises from a lifecycle mismatch between fabric cleanup and the `ReadClient` object references. The sequence of events leading to the issue is as follows:

1. Fabric Removal (FabricTable.cpp):
    - The `Delete()` method of `FabricTable` is called, which iterates through its delegates and invokes `OnFabricRemoved()`:
        
        ```cpp
        CHIP_ERROR FabricTable::Delete(FabricIndex fabricIndex)
        {
            if (mDelegateListRoot != nullptr)
            {
                FabricTable::Delegate * delegate = mDelegateListRoot;
                while (delegate)
                {
                    FabricTable::Delegate * nextDelegate = delegate->next;
                    delegate->OnFabricRemoved(*this, fabricIndex);
                    delegate = nextDelegate;
                }
            }
        }
        
        ```
        
2. ReadClient Cleanup (InteractionModelEngine.cpp):
    - The `OnFabricRemoved()` method loops through active `ReadClient` objects and calls `Close()`:
        
        ```cpp
        void InteractionModelEngine::OnFabricRemoved(const FabricTable & fabricTable, FabricIndex fabricIndex)
        {
            for (auto * readClient = mpActiveReadClientList; readClient != nullptr; readClient = readClient->GetNextClient())
            {
                if (readClient->GetFabricIndex() == fabricIndex)
                {
                    readClient->Close(CHIP_ERROR_IM_FABRIC_DELETED, false);
                }
            }
        }
        
        ```
        
3. ReadClient Deallocation (ReadClient.cpp):
    - The `Close()` method triggers the callback `mpCallback.OnDone(this)`, marking the `ReadClient` for destruction:
        
        ```cpp
        void ReadClient::Close(CHIP_ERROR aError, bool allowResubscription)
        {
            ...
            mpCallback.OnDone(this);
        }
        
        ```
        
4. Use of Freed Memory:
    - Despite being destroyed, the `ReadClient` remains in the `mpActiveReadClientList`. Subsequent iterations in `OnFabricRemoved()` access the dangling pointer. Specifically, the `readClient->GetNextClient()` call accesses the `mpNext` pointer of the destroyed `ReadClient` object, leading to a UAF:
        
        ```cpp
        ReadClient * GetNextClient() { return mpNext; }
        ```
        
    - This happens because `GetNextClient()` does not verify the validity of the `mpNext` pointer, which now points to a deallocated memory region.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

04e6a68cf8aa2c2d24dd1decb74d71a6f7a70dfe

### Platform

core

### Platform Version(s)

all versions

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yunhanw-google**
#### Summary

When ReadClient::Close is called from onFabricRemove in InteractionModel Engine, readClient is destoryed and becomes not valid so that readClient->GetNextClient() will be use-after-free.

Fixes https://github.com/project-chip/connectedhomeip/issues/36920

#### Testing
Add unit test to cover this, where we create multiple subscriptions, then we remove fabric,
Without this change, the unit test would fail since the problematic loop code in onFabricRemoved cannot continue and numActiveReadClient cannot decrease to 0 after removing fabric, with this change, the numActiveReadClient can decrease to 0.

### CODE REVIEW

File: src/app/ReadClient.cpp [hunk 1]
```diff
@@ -113,6 +113,9 @@ ReadClient::~ReadClient()
             mpImEngine->RemoveReadClient(this);
         }
     }
+    mpExchangeMgr = nullptr;
+    mpNext        = nullptr;
+    mpImEngine    = nullptr;
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.cpp:118]: Why are we doing that in a destructor?

File: src/app/InteractionModelEngine.h [hunk 2]
```diff
@@ -324,12 +324,18 @@ class InteractionModelEngine : public Messaging::UnsolicitedMessageHandler,
...
      */
     void DecrementNumSubscriptionsToResume();
 #endif // CHIP_CONFIG_PERSIST_SUBSCRIPTIONS
 
 #if CONFIG_BUILD_FOR_HOST_UNIT_TEST
+
+    //
+    // Get fabric table
+    //
+    FabricTable * GetFabricTable() { return mpFabricTable; }
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.h:337]: Why do we need this?  In tests, `MessagingContext` has a `GetFabricTable()` on it, no?

File: src/app/ReadClient.cpp (hunk 1 above)
Comment (yunhanw-google) [reply src/app/ReadClient.cpp]: thanks, just removed these unnecessary changes.

File: src/app/InteractionModelEngine.h (hunk 2 above)
Comment (yunhanw-google) [reply src/app/InteractionModelEngine.h]: just removed, yes MessagingContext has a GetFabricTable(), just update test code to use MessagingContext, thanks

File: src/controller/tests/data_model/TestRead.cpp [hunk 3]
```diff
@@ -4510,6 +4510,63 @@ TEST_F(TestRead, TestReadHandler_TwoParallelReadsSecondTooManyPaths)
...
+    GetIOContext().DriveIOUntil(System::Clock::Seconds16(60), [&]() {
+        return numSuccessCalls == (app::InteractionModelEngine::kReadHandlerPoolSize + 1) &&
+            numSubscriptionEstablishedCalls == (app::InteractionModelEngine::kReadHandlerPoolSize + 1);
+    });
+
+    EXPECT_EQ(numSuccessCalls, (app::InteractionModelEngine::kReadHandlerPoolSize + 1));
+    EXPECT_EQ(numSubscriptionEstablishedCalls, (app::InteractionModelEngine::kReadHandlerPoolSize + 1));
+    EXPECT_EQ(mNumActiveSubscriptions, static_cast<int32_t>(app::InteractionModelEngine::kReadHandlerPoolSize + 1));
+
+    chip::Test::MessagingContext::GetFabricTable().DeleteAllFabrics();
```
Comment (bzbarsky-apple) [inline src/controller/tests/data_model/TestRead.cpp:4560]:
```suggestion
    GetFabricTable().DeleteAllFabrics();
```
This is running against a `TestRead` fixture, no?  And that inherits from `chip::Test::AppContext`, etc.

File: src/controller/tests/data_model/TestRead.cpp [hunk 4]
```diff
@@ -4510,6 +4510,63 @@ TEST_F(TestRead, TestReadHandler_TwoParallelReadsSecondTooManyPaths)
...
+
+    EXPECT_EQ(mNumActiveSubscriptions, 0);
+    size_t numActiveReadClients = app::InteractionModelEngine::GetInstance()->GetNumActiveReadClients();
+    EXPECT_EQ(numActiveReadClients, 0u);
+    EXPECT_EQ(GetExchangeManager().GetNumActiveExchanges(), 0u);
+
+    SetMRPMode(chip::Test::MessagingContext::MRPMode::kDefault);
```
Comment (bzbarsky-apple) [inline src/controller/tests/data_model/TestRead.cpp:4567]: Looks to me like you could remove a bunch of namespacing here too, and a bunch of app:: prefixes above can also go away: this whole file is `using namespace chip::app;`

Comment (yunhanw-google) [reply src/controller/tests/data_model/TestRead.cpp]: done, thanks

File: src/controller/tests/data_model/TestRead.cpp (hunk 3 above)
Comment (yunhanw-google) [reply src/controller/tests/data_model/TestRead.cpp]: yes, agree, thanks

File: src/app/InteractionModelEngine.cpp [hunk 5]
```diff
@@ -1967,12 +1967,18 @@ void InteractionModelEngine::OnFabricRemoved(const FabricTable & fabricTable, Fa
     });
 
 #if CHIP_CONFIG_ENABLE_READ_CLIENT
-    for (auto * readClient = mpActiveReadClientList; readClient != nullptr; readClient = readClient->GetNextClient())
+    for (auto * readClient = mpActiveReadClientList; readClient != nullptr;)
     {
         if (readClient->GetFabricIndex() == fabricIndex)
         {
             ChipLogProgress(InteractionModel, "Fabric removed, deleting obsolete read client with FabricIndex: %u", fabricIndex);
+            auto * nextReadClient = readClient->GetNextClient();
```
Comment (andy31415) [inline src/app/InteractionModelEngine.cpp:1975]: a comment that `Close` may delete the client may be useful here, to explain why we do this.

**Review by andy31415 — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/InteractionModelEngine.cpp (hunk 5 above)
Comment (yunhanw-google) [reply src/app/InteractionModelEngine.cpp:1977]: done, thanks
