### PR TITLE
iOS tv-casting-app: Apply StackLocks and sequence callbacks

### LINKED ISSUE #26816: [BUG] iOS tv-casting-app:
### Reproduction steps

The Matter SDK assumes that the client will take a lock on the SDK prior to interacting with any APIs. There is 1 Android function and several iOS functions that do not take the lock prior to interacting with the SDK APIs.

There are also some functions that invoke the Matter SDK in a way that may result in out-of-order callback invocation (e.g. the conceptual "started" callback may be invoked after the conceptual "ended" callback).

Without the StackLocks we see that the iOS tv-casting-app can crash or show unexpected behaviour when calling the Matter SDK APIs.

### Bug prevalence

Some times

### GitHub hash of the SDK that was being used

6ce2412af122fb20386cf13e967064587751d5d0

### Platform

darwin

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sharadb-amazon**
Fixes https://github.com/project-chip/connectedhomeip/issues/26816

### Problem

The Matter SDK assumes that the client will take a lock on the SDK prior to interacting with any APIs. There is 1 Android function and several iOS functions that do not take the lock prior to interacting with the SDK APIs.

There are also some functions that invoke the Matter SDK in a way that may result in out-of-order callback invocation (e.g. the conceptual "started" callback may be invoked after the conceptual "ended" callback).

### Solution

Create utility functions that help ensure that the Matter SDK is invoked safely and that callbacks are delivered in the correct order.

### Testing

Performed local, manual testing with the 'tv-casting-app' example on iOS against a Raspberry Pi running the 'tv-app'. Ran the certification test in the 'tv-casting-app' on iOS against the same Raspberry Pi.

* * Updating naming and parameter order for new CastingServerBridge APIs
* Refactored the Certification Tests to more fully exercise threading behavior

* * Updating the documentation for modified APIs

### CODE REVIEW

**Review by cliffamzn — APPROVED** [review]

**Review by hawk248 — APPROVED** [review]

**Review by hawk248 — APPROVED** [review]

File: examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm [hunk 1]
```diff
@@ -120,10 +111,166 @@ - (instancetype)init
...
 - (MatterError *)initializeApp:(AppParameters * _Nullable)appParameters
                    clientQueue:(dispatch_queue_t _Nonnull)clientQueue
           initAppStatusHandler:(nullable void (^)(bool))initAppStatusHandler
 {
+    // The Matter SDK is not, generally, internally thread-safe. It relies upon the client to lock
+    // the SDK prior to any interactions after chip::DeviceLayer::PlatformMgr().InitChipStack()
+    //
+    // Note that it is presently safe to do at this point because InitChipStack is called in the
+    // constructor for the CastingServerBridge.
+    chip::DeviceLayer::StackLock lock;
```
Comment (bzbarsky-apple) [inline examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm:273]: StackLock is a no-op on the Darwin platform, no?  @sharadb-amazon

File: examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm [hunk 2]
```diff
@@ -120,10 +111,166 @@ - (instancetype)init
...
+    if (nil != description) {
+        ChipLogProgress(AppServer, "[SYNC] CastingServerBridge %s", [description UTF8String]);
+    }
+    dispatch_async(_chipWorkQueue, ^{
+        // The Matter SDK is not, generally, internally thread-safe. It relies upon the client to lock
+        // the SDK prior to any interactions after chip::DeviceLayer::PlatformMgr().InitChipStack()
+        //
+        // Note that it is presently safe to do at this point because InitChipStack is called in the
+        // constructor for the CastingServerBridge.
+        chip::DeviceLayer::StackLock lock;
```
Comment (bzbarsky-apple) [inline examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm:131]: If StackLock were _not_ a no-op on Darwin, this would deadlock, since you are already on the Matter queue and hence holding the lock if there were one.
