### PR TITLE
[BUG] Linux Test Harness Certification Declaration encoding error

### LINKED ISSUE #26811: [BUG] Linux Test Harness Certification Declaration encoding error
### Reproduction steps

1. Flash RaspberryPi with chip-certification-tool/releases/tag/v2.8.1-official
2. Perform AttestationRequest to the device.
3. Attempt to decode and verify the AttestationResponse.

Expected: No issue
Actual: The Certification Declaration fails ASN1 decoding

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

5a21d17fd2bb0a48f4a356937f4741f6c9dc7975

### Platform

core

### Platform Version(s)

1.0 1.1

### Anything else?

https://github.com/CHIP-Specifications/chip-certification-tool/releases/tag/v2.8.1-official

### PR DESCRIPTION
**Pull request by swan-amazon**
Fixes #26811

During internal QA testing related to commissioning the [chip-certification-tool (TH v 2.8.1 - 1.1 Release Build)](https://github.com/CHIP-Specifications/chip-certification-tool/releases/tag/v2.8.1-official) a failure occurred while attempting to verify the Certification Declaration payload using the latest releases of Bouncy Castle.

> **11.17.5.5. Attestation Information**
>
> The certification_declaration field SHALL be the DER-encoded octet
string representation of a CMS-formatted certification declaration, as described in Section 6.3, “Certification Declaration”.

The [specific exception](https://github.com/bcgit/bc-java/blob/876bd0cf02811282707ddd38e4f0f9212a9f4d1f/core/src/main/java/org/bouncycastle/asn1/ASN1Primitive.java#L46-L49) is thrown while attempting to decode the DER-encoded octet string, due to unexpected bytes remaining after attempting to decode the packet. After extracting the Certification Declaration payload and attempting to perform manual validation using openssl, it was double-confirmed that the payload contained an encoding error.

Finally, the Certification Declaration payload was confirmed to have an extra byte originating from the hardcoded test payload. After the extra byte is removed, the payload decoding is successful.

### CODE REVIEW

**Comment by swan-amazon** [comment]
## Original payload:

```
$ openssl asn1parse -inform DER -in /tmp/certificationDeclaration.bin

    0:d=0  hl=4 l= 535 cons: SEQUENCE
    4:d=1  hl=2 l=   9 prim: OBJECT            :pkcs7-signedData
   15:d=1  hl=4 l= 520 cons: cont [ 0 ]
   19:d=2  hl=4 l= 516 cons: SEQUENCE
   23:d=3  hl=2 l=   1 prim: INTEGER           :03
   26:d=3  hl=2 l=  13 cons: SET
   28:d=4  hl=2 l=  11 cons: SEQUENCE
   30:d=5  hl=2 l=   9 prim: OBJECT            :sha256
   41:d=3  hl=4 l= 368 cons: SEQUENCE
   45:d=4  hl=2 l=   9 prim: OBJECT            :pkcs7-data
   56:d=4  hl=4 l= 353 cons: cont [ 0 ]
   60:d=5  hl=4 l= 349 prim: OCTET STRING      [HEX DUMP]:152400012501F1FF3602050080050180050280050380050480050580050680050780050880050980050A80050B80050C80050D80050E80050F80051080051180051280051380051480051580051680051780051880051980051A80051B80051C80051D80051E80051F80052080052180052280052380052480052580052680052780052880052980052A80052B80052C80052D80052E80052F80053080053180053280053380053480053580053680053780053880053980053A80053B80053C80053D80053E80053F80054080054180054280054380054480054580054680054780054880054980054A80054B80054C80054D80054E80054F80055080055180055280055380055480055580055680055780055880055980055A80055B80055C80055D80055E80055F80056080056180056280056380182403162C0413435341303030303053574330303030302D303024050024060024070124080018
  413:d=3  hl=2 l= 124 cons: SET
  415:d=4  hl=2 l= 122 cons: SEQUENCE
  417:d=5  hl=2 l=   1 prim: INTEGER           :03
  420:d=5  hl=2 l=  20 prim: cont [ 0 ]
  442:d=5  hl=2 l=  11 cons: SEQUENCE
  444:d=6  hl=2 l=   9 prim: OBJECT            :sha256
  455:d=5  hl=2 l=  10 cons: SEQUENCE
  457:d=6  hl=2 l=   8 prim: OBJECT            :ecdsa-with-SHA256
  467:d=5  hl=2 l=  70 prim: OCTET STRING      [HEX DUMP]:304402204A12F8D42F90235C05A77121CBEBAE15D590146558E9C9B47A1A38F7A36A7DC5022020A4742897C30AEDA0A56B36E14EBBC85BBDB74493F993581EB0444ED6CA940B
Error in encoding
8689408832:error:0DFFF07B:asn1 encoding routines:CRYPTO_internal:header too long:/AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/libressl/libressl-3.3/crypto/asn1/asn1_lib.c:152:
```

```
00000000: 3082 0217 0609 2a86 4886 f70d 0107 02a0  0.....*.H.......
00000010: 8202 0830 8202 0402 0103 310d 300b 0609  ...0......1.0...
00000020: 6086 4801 6503 0402 0130 8201 7006 092a  `.H.e....0..p..*
00000030: 8648 86f7 0d01 0701 a082 0161 0482 015d  .H.........a...]
00000040: 1524 0001 2501 f1ff 3602 0500 8005 0180  .$..%...6.......
00000050: 0502 8005 0380 0504 8005 0580 0506 8005  ................
00000060: 0780 0508 8005 0980 050a 8005 0b80 050c  ................
00000070: 8005 0d80 050e 8005 0f80 0510 8005 1180  ................
00000080: 0512 8005 1380 0514 8005 1580 0516 8005  ................
00000090: 1780 0518 8005 1980 051a 8005 1b80 051c  ................
000000a0: 8005 1d80 051e 8005 1f80 0520 8005 2180  ........... ..!.
000000b0: 0522 8005 2380 0524 8005 2580 0526 8005  ."..#..$..%..&..
000000c0: 2780 0528 8005 2980 052a 8005 2b80 052c  '..(..)..*..+..,
000000d0: 8005 2d80 052e 8005 2f80 0530 8005 3180  ..-...../..0..1.
000000e0: 0532 8005 3380 0534 8005 3580 0536 8005  .2..3..4..5..6..
000000f0: 3780 0538 8005 3980 053a 8005 3b80 053c  7..8..9..:..;..<
00000100: 8005 3d80 053e 8005 3f80 0540 8005 4180  ..=..>..?..@..A.
00000110: 0542 8005 4380 0544 8005 4580 0546 8005  .B..C..D..E..F..
00000120: 4780 0548 8005 4980 054a 8005 4b80 054c  G..H..I..J..K..L
00000130: 8005 4d80 054e 8005 4f80 0550 8005 5180  ..M..N..O..P..Q.
00000140: 0552 8005 5380 0554 8005 5580 0556 8005  .R..S..T..U..V..
00000150: 5780 0558 8005 5980 055a 8005 5b80 055c  W..X..Y..Z..[..\
00000160: 8005 5d80 055e 8005 5f80 0560 8005 6180  ..]..^.._..`..a.
00000170: 0562 8005 6380 1824 0316 2c04 1343 5341  .b..c..$..,..CSA
00000180: 3030 3030 3053 5743 3030 3030 302d 3030  00000SWC00000-00
00000190: 2405 0024 0600 2407 0124 0800 1831 7c30  $..$..$..$...1|0
000001a0: 7a02 0103 8014 fe34 3f95 9947 763b 61ee  z......4?..Gv;a.
000001b0: 4539 1313 3849 4fe6 7d8e 300b 0609 6086  E9..8IO.}.0...`.
000001c0: 4801 6503 0402 0130 0a06 082a 8648 ce3d  H.e....0...*.H.=
000001d0: 0403 0204 4630 4402 204a 12f8 d42f 9023  ....F0D. J.../.#
000001e0: 5c05 a771 21cb ebae 15d5 9014 6558 e9c9  \..q!.......eX..
000001f0: b47a 1a38 f7a3 6a7d c502 2020 a474 2897  .z.8..j}..  .t(.
00000200: c30a eda0 a56b 36e1 4ebb c85b bdb7 4493  .....k6.N..[..D.
00000210: f993 581e b044 4ed6 ca94 0b00            ..X..DN.....
```

## Updated payload

After removing the extra byte `0x00`, the payload is then well-formed and can be successfully decoded, as shown below, by first, extract the signed payload from the DER encoded Certification Declaration, then performing TLV decode of the resulting buffer.

```
$ openssl asn1parse -inform DER -in <(head -c 539 /tmp/certificationDeclaration.bin)

    0:d=0  hl=4 l= 535 cons: SEQUENCE
    4:d=1  hl=2 l=   9 prim: OBJECT            :pkcs7-signedData
   15:d=1  hl=4 l= 520 cons: cont [ 0 ]
   19:d=2  hl=4 l= 516 cons: SEQUENCE
   23:d=3  hl=2 l=   1 prim: INTEGER           :03
   26:d=3  hl=2 l=  13 cons: SET
   28:d=4  hl=2 l=  11 cons: SEQUENCE
   30:d=5  hl=2 l=   9 prim: OBJECT            :sha256
   41:d=3  hl=4 l= 368 cons: SEQUENCE
   45:d=4  hl=2 l=   9 prim: OBJECT            :pkcs7-data
   56:d=4  hl=4 l= 353 cons: cont [ 0 ]
   60:d=5  hl=4 l= 349 prim: OCTET STRING      [HEX DUMP]:152400012501F1FF3602050080050180050280050380050480050580050680050780050880050980050A80050B80050C80050D80050E80050F80051080051180051280051380051480051580051680051780051880051980051A80051B80051C80051D80051E80051F80052080052180052280052380052480052580052680052780052880052980052A80052B80052C80052D80052E80052F80053080053180053280053380053480053580053680053780053880053980053A80053B80053C80053D80053E80053F80054080054180054280054380054480054580054680054780054880054980054A80054B80054C80054D80054E80054F80055080055180055280055380055480055580055680055780055880055980055A80055B80055C80055D80055E80055F80056080056180056280056380182403162C0413435341303030303053574330303030302D303024050024060024070124080018
  413:d=3  hl=2 l= 124 cons: SET
  415:d=4  hl=2 l= 122 cons: SEQUENCE
  417:d=5  hl=2 l=   1 prim: INTEGER           :03
  420:d=5  hl=2 l=  20 prim: cont [ 0 ]
  442:d=5  hl=2 l=  11 cons: SEQUENCE
  444:d=6  hl=2 l=   9 prim: OBJECT            :sha256
  455:d=5  hl=2 l=  10 cons: SEQUENCE
  457:d=6  hl=2 l=   8 prim: OBJECT            :ecdsa-with-SHA256
  467:d=5  hl=2 l=  70 prim: OCTET STRING      [HEX DUMP]:304402204A12F8D42F90235C05A77121CBEBAE15D590146558E9C9B47A1A38F7A36A7DC5022020A4742897C30AEDA0A56B36E14EBBC85BBDB74493F993581EB0444ED6CA940B
```

```
tlv -d 152400012501F1FF3602050080050180050280050380050480050580050680050780050880050980050A80050B80050C80050D80050E80050F80051080051180051280051380051480051580051680051780051880051980051A80051B80051C80051D80051E80051F80052080052180052280052380052480052580052680052780052880052980052A80052B80052C80052D80052E80052F80053080053180053280053380053480053580053680053780053880053980053A80053B80053C80053D80053E80053F80054080054180054280054380054480054580054680054780054880054980054A80054B80054C80054D80054E80054F80055080055180055280055380055480055580055680055780055880055980055A80055B80055C80055D80055E80055F80056080056180056280056380182403162C0413435341303030303053574330303030302D303024050024060024070124080018
[
  {
    "type": "struct",
    "value": [
      {
        "tag": 0,
        "type": "uint8",
        "value": 1
      },
      {
        "tag": 1,
        "type": "uint16",
        "value": 65521
      },
      {
        "tag": 2,
        "type": "array",
        "value": [
          {
            "type": "uint16",
            "value": 32768
          },
          {
            "type": "uint16",
            "value": 32769
          },
          {
            "type": "uint16",
            "value": 32770
          },
          {
            "type": "uint16",
            "value": 32771
          },
          {
            "type": "uint16",
            "value": 32772
          },
          {
            "type": "uint16",
            "value": 32773
          },
          {
            "type": "uint16",
            "value": 32774
          },
          {
            "type": "uint16",
            "value": 32775
          },
          {
            "type": "uint16",
            "value": 32776
          },
          {
            "type": "uint16",
            "value": 32777
          },
          {
            "type": "uint16",
            "value": 32778
          },
          {
            "type": "uint16",
            "value": 32779
          },
          {
            "type": "uint16",
            "value": 32780
          },
          {
            "type": "uint16",
            "value": 32781
          },
          {
            "type": "uint16",
            "value": 32782
          },
          {
            "type": "uint16",
            "value": 32783
          },
          {
            "type": "uint16",
            "value": 32784
          },
          {
            "type": "uint16",
            "value": 32785
          },
          {
            "type": "uint16",
            "value": 32786
          },
          {
            "type": "uint16",
            "value": 32787
          },
          {
            "type": "uint16",
            "value": 32788
          },
          {
            "type": "uint16",
            "value": 32789
          },
          {
            "type": "uint16",
            "value": 32790
          },
          {
            "type": "uint16",
            "value": 32791
          },
          {
            "type": "uint16",
            "value": 32792
          },
          {
            "type": "uint16",
            "value": 32793
          },
          {
            "type": "uint16",
            "value": 32794
          },
          {
            "type": "uint16",
            "value": 32795
          },
          {
            "type": "uint16",
            "value": 32796
          },
          {
            "type": "uint16",
            "value": 32797
          },
          {
            "type": "uint16",
            "value": 32798
          },
          {
            "type": "uint16",
            "value": 32799
          },
          {
            "type": "uint16",
            "value": 32800
          },
          {
            "type": "uint16",
            "value": 32801
          },
          {
            "type": "uint16",
            "value": 32802
          },
          {
            "type": "uint16",
            "value": 32803
          },
          {
            "type": "uint16",
            "value": 32804
          },
          {
            "type": "uint16",
            "value": 32805
          },
          {
            "type": "uint16",
            "value": 32806
          },
          {
            "type": "uint16",
            "value": 32807
          },
          {
            "type": "uint16",
            "value": 32808
          },
          {
            "type": "uint16",
            "value": 32809
          },
          {
            "type": "uint16",
            "value": 32810
          },
          {
            "type": "uint16",
            "value": 32811
          },
          {
            "type": "uint16",
            "value": 32812
          },
          {
            "type": "uint16",
            "value": 32813
          },
          {
            "type": "uint16",
            "value": 32814
          },
          {
            "type": "uint16",
            "value": 32815
          },
          {
            "type": "uint16",
            "value": 32816
          },
          {
            "type": "uint16",
            "value": 32817
          },
          {
            "type": "uint16",
            "value": 32818
          },
          {
            "type": "uint16",
            "value": 32819
          },
          {
            "type": "uint16",
            "value": 32820
          },
          {
            "type": "uint16",
            "value": 32821
          },
          {
            "type": "uint16",
            "value": 32822
          },
          {
            "type": "uint16",
            "value": 32823
          },
          {
            "type": "uint16",
            "value": 32824
          },
          {
            "type": "uint16",
            "value": 32825
          },
          {
            "type": "uint16",
            "value": 32826
          },
          {
            "type": "uint16",
            "value": 32827
          },
          {
            "type": "uint16",
            "value": 32828
          },
          {
            "type": "uint16",
            "value": 32829
          },
          {
            "type": "uint16",
            "value": 32830
          },
          {
            "type": "uint16",
            "value": 32831
          },
          {
            "type": "uint16",
            "value": 32832
          },
          {
            "type": "uint16",
            "value": 32833
          },
          {
            "type": "uint16",
            "value": 32834
          },
          {
            "type": "uint16",
            "value": 32835
          },
          {
            "type": "uint16",
            "value": 32836
          },
          {
            "type": "uint16",
            "value": 32837
          },
          {
            "type": "uint16",
            "value": 32838
          },
          {
            "type": "uint16",
            "value": 32839
          },
          {
            "type": "uint16",
            "value": 32840
          },
          {
            "type": "uint16",
            "value": 32841
          },
          {
            "type": "uint16",
            "value": 32842
          },
          {
            "type": "uint16",
            "value": 32843
          },
          {
            "type": "uint16",
            "value": 32844
          },
          {
            "type": "uint16",
            "value": 32845
          },
          {
            "type": "uint16",
            "value": 32846
          },
          {
            "type": "uint16",
            "value": 32847
          },
          {
            "type": "uint16",
            "value": 32848
          },
          {
            "type": "uint16",
            "value": 32849
          },
          {
            "type": "uint16",
            "value": 32850
          },
          {
            "type": "uint16",
            "value": 32851
          },
          {
            "type": "uint16",
            "value": 32852
          },
          {
            "type": "uint16",
            "value": 32853
          },
          {
            "type": "uint16",
            "value": 32854
          },
          {
            "type": "uint16",
            "value": 32855
          },
          {
            "type": "uint16",
            "value": 32856
          },
          {
            "type": "uint16",
            "value": 32857
          },
          {
            "type": "uint16",
            "value": 32858
          },
          {
            "type": "uint16",
            "value": 32859
          },
          {
            "type": "uint16",
            "value": 32860
          },
          {
            "type": "uint16",
            "value": 32861
          },
          {
            "type": "uint16",
            "value": 32862
          },
          {
            "type": "uint16",
            "value": 32863
          },
          {
            "type": "uint16",
            "value": 32864
          },
          {
            "type": "uint16",
            "value": 32865
          },
          {
            "type": "uint16",
            "value": 32866
          },
          {
            "type": "uint16",
            "value": 32867
          }
        ]
      },
      {
        "tag": 3,
        "type": "uint8",
        "value": 22
      },
      {
        "tag": 4,
        "type": "string uint8 len",
        "value": "CSA00000SWC00000-00"
      },
      {
        "tag": 5,
        "type": "uint8",
        "value": 0
      },
      {
        "tag": 6,
        "type": "uint8",
        "value": 0
      },
      {
        "tag": 7,
        "type": "uint8",
        "value": 1
      },
      {
        "tag": 8,
        "type": "uint8",
        "value": 0
      }
    ]
  }
]
```

**Review by bzbarsky-apple — APPROVED** [review]

**Review by yufengwangca — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

File: src/app/tests/suites/credentials/TestHarnessDACProvider.cpp [hunk 1]
```diff
@@ -106,7 +106,7 @@ constexpr const uint8_t kCdForAllExamples[539] = {
     0x98, 0x96, 0xc7, 0xc9, 0xc8, 0x2d, 0x4b, 0xf5, 0x76, 0xd3, 0x8f, 0xbd, 0x36, 0x5b
 };
 #else  /* Fall back to the VID=0xFFF1 CD */
-constexpr const uint8_t kCdForAllExamples[540] = {
+constexpr const uint8_t kCdForAllExamples[539] = {
```
Comment (andy31415) [inline src/app/tests/suites/credentials/TestHarnessDACProvider.cpp:109]: why not just `[]` and let the compiler figure out the size?

Comment (andy31415) [reply src/app/tests/suites/credentials/TestHarnessDACProvider.cpp:109]: Maybe just use [] in the other case as well... this manually setting the size seems to be a footgun.

Comment (andy31415) [inline src/app/tests/suites/credentials/TestHarnessDACProvider.cpp:109]:
```suggestion
constexpr const uint8_t kCdForAllExamples[] = {
```

Comment (swan-amazon) [reply src/app/tests/suites/credentials/TestHarnessDACProvider.cpp]: I was trying to avoid making waves by not proactively doing that, but I definitely agree. I have a new draft that addresses this issue in most places.

File: src/credentials/examples/ExampleDACs.cpp [hunk 2]
```diff
@@ -29,7 +29,7 @@ namespace chip {
 namespace DevelopmentCerts {
 
 #if CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID == 0xFFF1 && CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID == 0x8000
-const uint8_t kDevelopmentDAC_Cert_FFF1_8000[493] = {
+const uint8_t kDevelopmentDAC_Cert_FFF1_8000[] = {
```
Comment (bzbarsky-apple) [inline src/credentials/examples/ExampleDACs.cpp:32]: Like the comment at the top of the file says, this is a generated file.  Please don't change it without changing the generator.

File: src/credentials/examples/ExamplePAI.cpp [hunk 3]
```diff
@@ -29,7 +29,7 @@ namespace chip {
 namespace DevelopmentCerts {
 
 #if CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID == 0xFFF1
-const uint8_t kDevelopmentPAI_Cert_FFF1[463] = {
+const uint8_t kDevelopmentPAI_Cert_FFF1[] = {
```
Comment (bzbarsky-apple) [inline src/credentials/examples/ExamplePAI.cpp:32]: Again, generated file.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/credentials/examples/ExampleDACs.cpp (hunk 2 above)
Comment (swan-amazon) [reply src/credentials/examples/ExampleDACs.cpp]: Reverted the changes to this file...

File: src/credentials/examples/ExamplePAI.cpp (hunk 3 above)
Comment (swan-amazon) [reply src/credentials/examples/ExamplePAI.cpp]: Reverted the changes to this file...

File: examples/android/CHIPTool/app/src/main/cpp/native-lib.cpp [hunk 4]
```diff
@@ -29,8 +29,8 @@
 // is working.
 std::string base38Encode(void)
 {
-    const uint8_t buf[6] = { 0, 1, 2, 3, 4, 5 };
-    size_t size          = 6;
+    const uint8_t buf[] = { 0, 1, 2, 3, 4, 5 };
+    size_t size         = sizeof(buf);
```
Comment (bzbarsky-apple) [inline examples/android/CHIPTool/app/src/main/cpp/native-lib.cpp:33]:
```suggestion
    size_t size         = ArraySize(buf);
```

**Review by bzbarsky-apple — APPROVED** [review]
