### PR TITLE
Fix sending PacketBuffer with "ref count > 1" fails in LwIP

### LINKED ISSUE #4372: Sending PacketBuffer with "ref count > 1" fails in LwIP
#### Problem
Sending a message in a `PacketBuffer` with reference count > 1 causes an assert in LwIP library. 
```
assertion "p->ref == 1" failed: file "../esp-idf/components/lwip/lwip/src/core/ipv4/ip4.c", line 927, function: ip4_output_if_opt_src
```

Similar checks are in IPv6 code as well.

CRMP uses reference count as a mechanism to cache the transmitted packets for future retransmissions. But, given the above checks, it won't work on platforms that are using LwIP.

 #### Proposed Solution
One option is to deep copy the packets to another PacketBuffer before transmission, instead of incrementing the reference count. This does add memory overheads.

Need to further analyze the issue to identify the solution.

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
Sending a message in a PacketBuffer with reference count > 1 causes an assert in LwIP library. CRMP uses reference count as a mechanism to cache the transmitted packets for future re-transmissions. But, given the above checks, it won't work on platforms that are using LwIP.

 #### Summary of Changes
1. Set the flag to indicate the buffer is retained after adding the buffer to the re-transmission table successfully.

2. When retaining a buffer, the caller expects the msg to be unmodified.  LwIP stack will normally prepend the packet
   headers as the packet traverses the UDP/IP/netif layers, which modifies the packet.  We prepend a small pbuf to 
   the beginning of the pbuf chain, s.t. all headers are added to the temporary space, just large enough to hold the
   transport headers.    
   we're actually oversizing the reserved space, the transport header is large enough for the TCP header which is
   larger than the UDP header.

 Fixes #4372

### CODE REVIEW

**Review by msandstedt — APPROVED** [review]

File: src/inet/UDPEndPoint.cpp [hunk 1]
```diff
@@ -543,6 +543,27 @@ INET_ERROR UDPEndPoint::SendMsg(const IPPacketInfo * pktInfo, System::PacketBuff
 
 #if CHIP_SYSTEM_CONFIG_USE_LWIP
 
+    pbuf * msgCopy = NULL;
+
+    if (sendFlags & IPEndPointBasis::kSendFlag_RetainBuffer)
```
Comment (bzbarsky-apple) [inline src/inet/UDPEndPoint.cpp:548]: Could we just check whether we "own" the buffer, and do this "prepend a space for headers" bit if we don't?  Seems like checking the refcount (the same way that the assert that ends up failing does) might do the trick, right?

And then we don't need to pipe this flag through various places, sort out whether it's appropriate for its counterparent to live in PacketHeader, etc.

Does that sound feasible?  Reasonable?

Comment (yufengwangca) [reply src/inet/UDPEndPoint.cpp]: I think this is a good idea, Thanks! 

The spec says the CRMP is only used for UDP packets, I am not aware of any case that a TCP packet need to be retained if it does not use CRMP.

File: src/system/SystemPacketBuffer.h [hunk 2]
```diff
@@ -380,6 +380,7 @@ class DLL_EXPORT PacketBuffer : private pbuf
 #endif
 
     void AddRef();
+    uint16_t GetRef() { return this->ref; }
```
Comment (andy31415) [inline src/system/SystemPacketBuffer.h:383]: nit: should this and below be `GetRefCount()`?

File: src/inet/UDPEndPoint.cpp [hunk 3]
```diff
@@ -635,6 +658,13 @@ INET_ERROR UDPEndPoint::SendMsg(const IPPacketInfo * pktInfo, System::PacketBuff
 
     // Unlock LwIP stack
     UNLOCK_TCPIP_CORE();
+
+    if (msg.GetRef() > 1)
+    {
+        /* Disconnect the temporary head pbuf from the remaining pbufs in chain */
+        msgCopy->next = NULL;
```
Comment (andy31415) [inline src/inet/UDPEndPoint.cpp:665]: It seems not easy to follow that ->next = NULL is sufficient to undo the pbuf_chain call that establishes a chain. Is there a lwip call that would do this undo? `pbuf_dechain` seems to exist but did not look if it is suitable. Naming wise it seems so.

Looking at lwip, I see that `pbuf_chain` will `pbuf_ref` on the tail - so we have an extra reference on the tail that will now not get removed. Is this true or does the sending remove it?

Could you confirm that this works ok? Maybe we could add some debug-mode local checksum validation that proves that the input buffer is not touched in any way.

File: src/inet/UDPEndPoint.cpp [hunk 4]
```diff
@@ -543,6 +543,31 @@ INET_ERROR UDPEndPoint::SendMsg(const IPPacketInfo * pktInfo, System::PacketBuff
...
+            return INET_ERROR_NO_MEMORY;
+        }
+
+        pbuf_chain(msgCopy, System::LwIPPacketBufferView::UnsafeGetLwIPpbuf(msg));
+    }
+    else
+    {
+        msgCopy = System::LwIPPacketBufferView::UnsafeGetLwIPpbuf(msg);
+    }
+
```
Comment (tcarmelveilleux) [inline src/inet/UDPEndPoint.cpp:570]: Overall this whole approach is very complex to follow and error prone, and tries to deal with *internal knowledge* of the IP stack (lwip here)

CRMP should make no attempt to keep the same buffer as that being sent in the retransmit table, or use reference counting, as a first implementation. The simpler and much less complex approach (which doesn't require special processing logic) is to:

1. Make CRMP keep the original copy for retransmit table, rather than increase refcount. Refcount increase are a total optimization with lots of side-effects in how you analyze downstream code.
2. Here, always make a copy, rather than chain. Make a literal, full copy of the chain.

You could do the opposite as well.

This would:

- Reduce special casing
- Create a copy that lives only for a very short period of time, only until the netif is reached, which is actually a synchronous flow for UDP
- Avoid having start tracking the exact chaining/ref count
- Avoid making assumption about the TCP/IP stack below (that its buffer enable and/or require particular reference count semantics and have underlying chaining considerations).

The cost of the copy is minuscule compared to many of the other costs, and *a copy needs to be made in some situations anyway*.

File: src/inet/UDPEndPoint.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/inet/UDPEndPoint.cpp]: > The spec says the CRMP is only used for UDP packets

I'm more thinking what happens if some consumer in general retains a buffer and then tries to send it over TCP.  Any idea what happens if they do?

File: src/system/SystemPacketBuffer.h (hunk 2 above)
Comment (bzbarsky-apple) [inline src/system/SystemPacketBuffer.h:383]: If we do this, I'd really rather expose a boolean "do I have sole ownership?" value than the refcount in general.  The latter is not really the business of anyone outside this class; it has no useful semantic meaning to consumers other than "is it 1?"

File: src/inet/UDPEndPoint.cpp (hunk 4 above)
Comment (kpschoedel) [reply src/inet/UDPEndPoint.cpp:570]: I'm also concerned about exposing the reference count. I'll look deeper, but off the top of my head, what if we provide something like `PacketBufferHandle GetUniqueOwnership(PacketBufferHandle && aPacket)`, which returns the handle itself if ref==1 and a copy if ref>1? Then `UDPEndPoint::SendMsg()` can do this just before calling LwIP, and we don't have to know or expose any internals.

File: src/inet/UDPEndPoint.cpp (hunk 3 above)
Comment (yufengwangca) [reply src/inet/UDPEndPoint.cpp]: Acked, we need to use pbuf_dechain to de-chain the head. The extra reference of the original pbuf is removed after the head is de-chained.

File: src/system/SystemPacketBuffer.h (hunk 2 above)
Comment (yufengwangca) [reply src/system/SystemPacketBuffer.h]: Acked. I use function bool IsRetained() to check is the buffer is solely owned, please let me know if there is a better name.

File: src/inet/UDPEndPoint.cpp (hunk 4 above)
Comment (yufengwangca) [reply src/inet/UDPEndPoint.cpp]: @tcarmelveilleux Currently CRMP logic is implemented within the messaging layer and use the transport layer to uniquely encrypt and send the message. If we keep the original buffer in the re-transmit table, in the following re-transmission,  the original buffer will go through the encryption process again, then it will not be treated as the same packet by the destination.

I have piloted clone and send method In https://github.com/project-chip/connectedhomeip/pull/4927, I found the transport layer does not send the encrypted packet as is, it will re-attach the UDP header at least for each send, even I clone the whole encrypted packet, it will fail in the following re-transmission.

If we want to use copy and send method, the best place is do the copy is within UDPEndPoint::SendMsg(), but we need to update the current PacketBufferHandle CloneData() to support chained buffers.

    /**
     * Creates a copy of the data in this packet.
     *
     * Does NOT support chained buffers.
     *
     *  @param[in]  aAdditionalSize Size of additional application data space after the initial contents.
     *  @param[in]  aReservedSize   Number of octets to reserve for protocol headers.
     *
     * @returns empty handle on allocation failure.
     */
    PacketBufferHandle CloneData(uint16_t aAdditionalSize = 0, uint16_t aReservedSize = PacketBuffer::kDefaultHeaderReserve); 
    
Currently, the PacketBuffer is the wrapper of the head of pbuf, the Lwip does not provide the function to clone the pbuf chain. Since we don't own pbuf.c, implement the chained buffer copy within PacketBuffer will be very tricky.

Comment (yufengwangca) [reply src/inet/UDPEndPoint.cpp]: If we could assume we never use chained pbuf for CHIP message with Lwip stack(Currently YES, but not sure in future), then we can copy the  PacketBufferHandle at UDPEndPoint::SendMsg() and give the copy to Lwip stack to send. 

Confirmed the openweave also get updated to use chained pbuf method and verified in production.

Comment (andy31415) [reply src/inet/UDPEndPoint.cpp]: For a quick fix, we can make CloneData error out if a chain is passed in and have a GH issue to have chain support.

File: src/system/SystemPacketBuffer.h [hunk 5]
```diff
@@ -474,6 +475,14 @@ class DLL_EXPORT PacketBufferHandle
      */
     bool IsNull() const { return mBuffer == nullptr; }
 
+    /**
+     * Test whether the PacketBuffer owned by this PacketBufferHandle has unique ownership.
+     *
+     * @return \c true if the PacketBuffer owned by this PacketBufferHandle is solely owned; return \c false if
```
Comment (andy31415) [inline src/system/SystemPacketBuffer.h:481]: comment seems wrong: this returns true if refcount > 1 (i.e. NOT solely owned) and false otherwise.

How about a name of 'HasSoleOwnership' to make it obvious what the method does without needing to read coments.

That being said, I believe we should take the approoach of cloning instead of adding lwip-specific code that relies on packetbuffer internal reference counts.

File: src/inet/UDPEndPoint.cpp (hunk 4 above)
Comment (kpschoedel) [reply src/inet/UDPEndPoint.cpp]: Do we actually want `CloneData()` to handle chains, or a new `Clone()` that also duplicates ‘reserved’ (non Data) parts? I fear the former would end up biting someone.

Comment (yufengwangca) [reply src/inet/UDPEndPoint.cpp]: I registered https://github.com/project-chip/connectedhomeip/issues/5348 to follow up this, yes, clone a PacketBufferHandle with a chained pbuf will be super tricky from my point of view if we do not own pbuf.c, we need to make a copy of the head as PacketBuffer and rest of element as plain pbuf.

For now, I assume CHIP messages are never chained, CloneData will return failure if it find the buffer is chained.

File: src/system/SystemPacketBuffer.h (hunk 5 above)
Comment (yufengwangca) [reply src/system/SystemPacketBuffer.h:481]: Acked

File: src/inet/UDPEndPoint.cpp [hunk 6]
```diff
@@ -543,6 +543,30 @@ INET_ERROR UDPEndPoint::SendMsg(const IPPacketInfo * pktInfo, System::PacketBuff
...
+    pbuf * pmsg = NULL;
+
+    if (!msg.HasSoleOwnership())
+    {
+        // when retaining a buffer, the caller expects the msg to be unmodified.
+        // LwIP stack will normally prepend the packet headers as the packet traverses
+        // the UDP/IP/netif layers, which normally modifies the packet. We need to clone
+        // msg into a fresh object in this case, and queues that for transmission, leaving
+        // the original msg available after return.
+        msgCopy = msg.CloneData();
```
Comment (andy31415) [inline src/inet/UDPEndPoint.cpp:556]: It does not look like we need msgCopy.

How about:

```cpp
if (!msg.HasSoleOwnership()) {
   // comments...
   msg = msg.CloneData();
}
```

you will not need any other changes.
Also consider doing this for all platforms (not only LWIP) for consistency sake. It has a cost but it seems minimal.

Comment (yufengwangca) [reply src/inet/UDPEndPoint.cpp:556]: It take me some time to understand the ref count with this change.

1. With msgCopy, the ref count is easy to calculate since we didn't touch the original logic.
Suppose we pass a packet which has been retained, msg.ref ==2. and msgCopy.ref =1 
When the function is returned, the ref count of the original packet become 1 since msg is destructed and the ref count of the copied packet become 0 and the copied packet is freed.

2. Without msgCopy, the ref count is calculated as:
Suppose we pass a packet which has been retained, msg.ref ==2. 
After msg = msg.CloneData();
The ref count of the original packet become 1 since msg gave up the ownership and msg take the ownership of copied packet with ref count = 1. 
When the function is returned, the ref count of the original packet is still 1 and the ref count of the copied packet become 0  since msg is destructed. The copied packet is freed.

Am I right?

Comment (andy31415) [reply src/inet/UDPEndPoint.cpp:556]: I believe this is correct. @kpschoedel 

Generally I am assuming that packetbufferhandles have correct/safe reference counting and I am using them as regular values without trying to manually match reference counts. Their functionality should be 'has a reference count while object is alive, drops reference count when object is destructed'

Comment (bzbarsky-apple) [reply src/inet/UDPEndPoint.cpp:556]: Yep, that's how handles work.

The one thing that might be a footgun in that sense is if you do `handle = std::move(handle)`.  That will lead to a dropped ref and a null pointer.  But `handle = handle.CloneData()` should works just fine.

Comment (kpschoedel) [reply src/inet/UDPEndPoint.cpp:556]: Checking for `handle = std::move(handle)` would cost around 100 bytes in the current tree. I think that's acceptable.

Comment (yufengwangca) [reply src/inet/UDPEndPoint.cpp]: Yes, only "msg = msg.CloneData()" could do the trick, "msg = std::move(msg.CloneData())" does not.

Comment (bzbarsky-apple) [reply src/inet/UDPEndPoint.cpp]: `msg = std::move(msg.CloneData())` should be fine as well; it will end up behaving just like `msg = msg.CloneData()` because in both cases the RHS is an rvalue ref.

To be clear, I am not saying we need to check for `handle = std::move(handle)`.  I'm just saying that this is the one "may act like a reference, not a value" edge case.  In practice, no one is doing that, though, and it would be pretty obvious if someone did.

**Review by andy31415 — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
