### PR TITLE
[mdns] fix mDNS type length

### LINKED ISSUE #6773: [tests] unit test "TestMdns" is failing
#### Problem
The unit test `TestMdns` is failing on master branch because avahi service `type` includes
the protocol text. It is introduced by https://github.com/project-chip/connectedhomeip/pull/6626.

 #### Proposed Solution
Use a local buffer for copying the type argument and parsing it into true service type
and protocol fields.

### PR DESCRIPTION
**Pull request by wgtdkp**
#### Problem
The `type` parameter in `MdnsAvahi::HandleBrowse` includes the protocol (`_tcp` or `_udp`) as suffix
but the `MdnsService::mType` fields includes only the service type. The Linux avahi implementation
results in failures in browse and resolve handler.

 #### Summary of Changes
This PR uses a local buffer for copying the `type` argument and parsing it into true service type
and protocol fields.

Fixes #6773

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

File: src/platform/Linux/MdnsImpl.cpp [hunk 1]
```diff
@@ -579,13 +579,16 @@ void MdnsAvahi::HandleBrowse(AvahiServiceBrowser * browser, AvahiIfIndex interfa
         if (strcmp("local", domain) == 0)
         {
             MdnsService service = {};
+            char typeAndProtocol[kMdnsTypeAndProtocolMaxSize + 1];
 
             strncpy(service.mName, name, sizeof(service.mName));
-            strncpy(service.mType, type, sizeof(service.mType));
             service.mName[kMdnsNameMaxSize] = 0;
+            strncpy(typeAndProtocol, type, sizeof(typeAndProtocol));
```
Comment (andy31415) [inline src/platform/Linux/MdnsImpl.cpp:586]: why do we need a separate copy?

The original code is suspect because it uses a local variable probably due to const-correctness. However getting the protocol from type seems totally doable in `const char *`.
