### PR TITLE
[IM]: Fix OnResponseTimeout is never fired when SendMessage fails

### LINKED ISSUE #9093: OnResponseTimeout cannot be fired when SendMessage fails fo send.

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
What is being fixed?  Examples:
* We found OnResponseTimeout was not triggered if SendMessage failed during IM read/write tests.
The reason is the current IM timeout value is set to 12 seconds, but the IM test interval is set to 1 second, the response timeout handler never has an chance to fire in case of SendMessage fails, since the timeout timer is cleared by the next iteration of test.

* Fixes #9093, #7489

#### Change overview
* Allow IM client to set the command timeout value. The IM client can use the current value (kImMessageTimeoutMsec) as the default timeout, in case this value is not overridden.

* Adjust the IM timeout value to a number less than IM test interval.

#### Testing
How was this tested? (at least one bullet point required)
* Do not start ./chip-im-responder on the server side
* ./chip-im-initiator 192.168.86.171 and confirm the response timeout handler are triggered.
```
[1629389848.711849][2051823:2051823] CHIP:DMG: CommandSender:Time out! failed to receive invoke command response from Exchange: 39017

[1629389849.713490][2051823:2051823] CHIP:DMG: CommandSender:Time out! failed to receive invoke command response from Exchange: 39018

[1629389850.713965][2051823:2051823] CHIP:DMG: CommandSender:Time out! failed to receive invoke command response from Exchange: 39019

[1629389852.717663][2051823:2051823] CHIP:DMG: CommandSender:Time out! failed to receive invoke command response from Exchange: 39020

[1629389853.717126][2051823:2051823] CHIP:DMG: ReadClient:Time out! failed to receive report data from Exchange: 39021

[1629389854.718814][2051823:2051823] CHIP:DMG: ReadClient:Time out! failed to receive report data from Exchange: 39022

[1629389855.719741][2051823:2051823] CHIP:DMG: ReadClient:Time out! failed to receive report data from Exchange: 39023

[1629389857.721055][2051823:2051823] CHIP:DMG: WriteClient:Time out! failed to receive write response from Exchange: 39024

[1629389858.721158][2051823:2051823] CHIP:DMG: WriteClient:Time out! failed to receive write response from Exchange: 39025

[1629389859.721473][2051823:2051823] CHIP:DMG: WriteClient:Time out! failed to receive write response from Exchange: 39026
```

### CODE REVIEW

File: src/app/InteractionModelEngine.h [hunk 1]
```diff
@@ -54,7 +54,7 @@ namespace app {
 
 constexpr size_t kMaxSecureSduLengthBytes = 1024;
 /* TODO: https://github.com/project-chip/connectedhomeip/issues/7489 */
-constexpr uint32_t kImMessageTimeoutMsec = 12000;
+constexpr uint32_t kImMessageTimeoutMsec = 1000;
```
Comment (yunhanw-google) [inline src/app/InteractionModelEngine.h:57]: is it too aggressive to set it as 1 seconds?

Comment (yunhanw-google) [reply src/app/InteractionModelEngine.h:57]: see this commit https://github.com/project-chip/connectedhomeip/commit/9d74bd044e0ea84388f48541c437ba562c7b2238

Comment (yufengwangca) [reply src/app/InteractionModelEngine.h:57]: kImMessageTimeoutMsec needs to be less than gMessageIntervalMsec to make sense, otherwise it is always get overwritten and never take effect. 

Maybe we should allow timeout value to be configurable as issue::7489 suggested?

Comment (yunhanw-google) [reply src/app/InteractionModelEngine.h:57]: yep, please make it configurable, thanks

**Comment by andy31415** [comment]
Cirque seems to claim failure

File: src/app/InteractionModelEngine.cpp [hunk 2]
```diff
@@ -314,7 +314,8 @@ CHIP_ERROR InteractionModelEngine::OnMessageReceived(Messaging::ExchangeContext
 
 void InteractionModelEngine::OnResponseTimeout(Messaging::ExchangeContext * ec)
 {
-    ChipLogProgress(DataManagement, "Time out! failed to receive echo response from Exchange: %d", ec->GetExchangeId());
+    ChipLogProgress(DataManagement, "InteractionModelEngine:Time out! failed to receive echo response from Exchange: %d",
```
Comment (woody-apple) [inline src/app/InteractionModelEngine.cpp:317]: Shouldn't we change the log category, rather than editing the string to add more context?

File: src/app/ReadClient.cpp [hunk 3]
```diff
@@ -348,7 +348,7 @@ CHIP_ERROR ReadClient::ProcessReportData(System::PacketBufferHandle && aPayload)
 
 void ReadClient::OnResponseTimeout(Messaging::ExchangeContext * apExchangeContext)
 {
-    ChipLogProgress(DataManagement, "Time out! failed to receive report data from Exchange: %d",
+    ChipLogProgress(DataManagement, "ReadClient:Time out! failed to receive report data from Exchange: %d",
```
Comment (woody-apple) [inline src/app/ReadClient.cpp:351]: Same as above

File: src/app/WriteClient.cpp [hunk 4]
```diff
@@ -328,7 +329,7 @@ CHIP_ERROR WriteClient::OnMessageReceived(Messaging::ExchangeContext * apExchang
 
 void WriteClient::OnResponseTimeout(Messaging::ExchangeContext * apExchangeContext)
 {
-    ChipLogProgress(DataManagement, "Time out! failed to receive write response from Exchange: %d",
+    ChipLogProgress(DataManagement, "WriteClient:Time out! failed to receive write response from Exchange: %d",
```
Comment (woody-apple) [inline src/app/WriteClient.cpp:332]: Same as above

**Review by woody-apple — CHANGES_REQUESTED** [review]

File: src/app/InteractionModelEngine.cpp (hunk 2 above)
Comment (yufengwangca) [reply src/app/InteractionModelEngine.cpp]: Acked.

File: src/app/ReadClient.cpp (hunk 3 above)
Comment (yufengwangca) [reply src/app/ReadClient.cpp]: Mainly to differentiate with InteractionModelEngine log,  no need to change if InteractionModelEngine use different log category.

File: src/app/CommandSender.h [hunk 5]
```diff
@@ -50,9 +50,12 @@ class CommandSender : public Command, public Messaging::ExchangeDelegate
     // handle calling Shutdown on itself once it decides it's done with waiting
     // for a response (i.e. times out or gets a response).
     //
+    // Client can specify the maximum time to wait for response (in milliseconds) via timeout parameter.
+    // Default timeout value will be used otherwise.
+    //
     // If SendCommandRequest is never called, or the call fails, the API
     // consumer is responsible for calling Shutdown on the CommandSender.
-    CHIP_ERROR SendCommandRequest(NodeId aNodeId, FabricIndex aFabricIndex, SessionHandle * secureSession = nullptr);
+    CHIP_ERROR SendCommandRequest(NodeId aNodeId, FabricIndex aFabricIndex, SessionHandle * secureSession, uint32_t timeout = 0);
```
Comment (msandstedt) [inline src/app/CommandSender.h:58]: Instead of defining 0 is a magic value that results in using the default `kImMessageTimeoutMsec`', why not instead just set `kImMessageTimeoutMsec` as the default here?

Comment (yufengwangca) [reply src/app/CommandSender.h]: Acked, the reason I do this trick is there are some conflicts if I include #include <app/InteractionModelEngine.h> directly in those header files use kImMessageTimeoutMsec.

This is resolved by declaring kImMessageTimeoutMsec in InteractionModelDelegate.h which already is the common header files

**Review by woody-apple — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
