### PR TITLE
Establish CASE on re-subscription

### LINKED ISSUE #16202: Figure out interaction timeout behaviors and recovery logic
In steady state, when a given protocol interaction times out (e.g subscription failure), it's not clear exactly who/what handles recovery from such an occurrence, and exactly what that that recovery should entail.

Some key questions surface:

1. How does an application get notified of such a failure? Through individual protocol-specific API surfaces (e.g ReadClient::Callback::OnError for reads, or CommandSender::Callback::OnError for commands, etc)? Or through a singular, common pathway?
2. Who (and this could be multiple) should get notified of such an error?
3. Are there automatic recovery steps that should be taken by the SDK? Or is it the application's responsibility entirely?
4. What would the recovery steps entail?

Most of the questions here are from the perspective of the controller/client.

In discussions with @bzbarsky-apple, here's what we settled on as one possible strategy:

1. Applications shouldn't likely be saddled with needing to aggregate all the various possible error callback sites to handle this. Instead, a single API should likely be added (perhaps even using the `SessionRecoveryDelegate` as the logical home for this).
2. That API should likely get routed to the `CASESessionManager` to appropriate manage subsequent recovery logic.
3. We should commence operational node discovery upon receiving `OnFirstMessageDeliveryFailed`. The results of that should be used to update the target address for a given session.
4. As for the actual recovery, we should implement CASE session resumption, and always do that as the recovery step upon completion of operational node discovery. Resumption is a fairly low-cost operational that doesn't involve heavy crypto, and avoids the penalty of CASE session establishment. The alternatives here are unfortunately quite un-ideal:
    * Attempt to go ahead and re-use the old session for further interactions, and if those fail **again**, THEN, re-establish CASE. This tries to assume that the reason for the interaction timeout earlier was networking related and that the state on the peer hasn't actually changed (i.e it hasn't rebooted). This approach will increase the latency for recovery however.
    * Always reestablish CASE. This is conservative, but it will result in wasteful attempts to reestablish CASE when they are not needed.
5. Add an API called `UpdateSession` in `SessionHolder` that will atomically, swap out an old session with a new one. This will likely be called by `CASESessionManager` upon completion of session resumption and will point to the new CASE session instance. This will automatically update session holders to point to the new session transparently.

One of the key benefactors of 5) above will be the re-subscription logic in `ReadClient` that will continue to work correctly across sessions as they get re-established/resumed.

### PR DESCRIPTION
**Pull request by mrjerryjohns**
This adds support for re-establishing CASE on re-subscription if a `CHIP_ERROR_TIMEOUT` was encountered as a default policy implementation, with the application having the ability to over-ride that if needed.

Fixes #16202 

This works out-of-the-box if you call `SendAutoResubscribeRequest`.

This deletes the function-callback approach in `ReadPrepareParams::mResubscribePolicy` and uses instead the re-named, `ReadClient::Callback::OnResubscriptionNeeded` callback to effect the right re-subscription policy.

That callback now pivots from being just an informational callback to one that places the onus on the application (if it over-rides the default impl) to schedule the ensuing re-subscription by calling back into `ReadClient::ScheduleResubscription`.

Helper methods are provided to help applications pick and select elements of the default re-sub implementation as they desire.

Other notables:
* Fixes missing clean-up of timers on ReadClient destruction initiated by the application.
* Fixes missing error-handling of calls made during re-subscription to ensure they trigger further re-subscription.

#### Testing

1. Added a new `TestSubscribeAttributeTimeout` in `TestRead.cpp` that validates re-subscription sans CASE.
2. Added a new `TestResubscription` in the Python test suite that validates re-subscription with CASE.

### CODE REVIEW

**Comment by mrjerryjohns** [comment]
FYI I did not update `chip-tool` since I didn't know whether you wanted the default behavior there as well, or if you wanted it to be hidden behind an option.

@bzbarsky-apple let me know if you'd like me to update `chip-tool` (which goes through the `SendSubscribeRequestWithoutValidation` API unfortunately, so that makes it a bit more work..)

File: src/app/ReadClient.h [hunk 1]
```diff
@@ -315,6 +332,32 @@ class ReadClient : public Messaging::ExchangeDelegate
...
+    //
+    uint32_t ComputeTimeTillNextSubscription();
+
+    //
+    // Schedules a re-subscription aTimeTillNextResubscriptionMs into the future.
+    //
+    // If restablishCASE is true, operational discovery and CASE will be attempted at that time before
+    // the actual IM interaction is initiated.
+    //
+    CHIP_ERROR ScheduleResubscription(uint32_t aTimeTillNextResubscriptionMs, bool restablishCASE = true);
```
Comment (mrjerryjohns) [inline src/app/ReadClient.h:359]: I realize that this API doesn't actually accept a new SessionHandle as a possible argument in the case where the application undertook the responsibility of setting up the CASE session itself. Will likely amend the API to:

```
CHIP_ERROR ScheduleResubscription(uint32_t aTimeTillNextResubscriptionMs, Optional<SessionHandle> newSessionHandle, bool restablishCASE = true);
```

If `newSessionHandle` is present, that will be used and the value of `restablishCASE` will be ignored. If it isn't present, then restablishCASE will be assessed.
```

File: src/app/ReadClient.h [hunk 2]
```diff
@@ -315,6 +332,32 @@ class ReadClient : public Messaging::ExchangeDelegate
...
+    //      - Calculates the time till next subscription with fibonacci back-off (implemented by ComputeTimeTillNextSubscription()).
+    //      - Schedules the next subscription attempt at the computed interval from the previous step. Operational discovery and
+    //        CASE establishment will be attempted if aTerminationCause was CHIP_ERROR_TIMEOUT. In all other cases, it will attempt
+    //        to re-use a previously established session.
+    //
+    CHIP_ERROR DefaultResubscribePolicy(CHIP_ERROR aTerminationCause);
+
+    //
+    // Computes the time till the next re-subscription with millisecond resolution over
+    // an even increasing window following a fibonacci sequence with the current retry count
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.h:346]:
```suggestion
    // an ever increasing window following a fibonacci sequence with the current retry count
```

File: src/app/ReadClient.h (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/ReadClient.h:359]: See above about how the CASE re-establishment should just happen in the Callback, not here...

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 3]
```diff
@@ -30,6 +30,7 @@
 #include <app/CommandHandler.h>
 #include <app/ConcreteCommandPath.h>
 #include <app/EventLogging.h>
+#include <app/InteractionModelEngine.h>
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:33]: Why?

File: src/app/InteractionModelEngine.cpp [hunk 4]
```diff
@@ -42,13 +42,17 @@ InteractionModelEngine * InteractionModelEngine::GetInstance()
...
+                                        CASESessionManager * apCASESessionMgr)
 {
-    mpExchangeMgr = apExchangeMgr;
-    mpFabricTable = apFabricTable;
+    VerifyOrReturnError(apFabricTable != nullptr, CHIP_ERROR_INVALID_ARGUMENT);
+    VerifyOrReturnError(apExchangeMgr != nullptr, CHIP_ERROR_INVALID_ARGUMENT);
+
+    mpExchangeMgr    = apExchangeMgr;
+    mpFabricTable    = apFabricTable;
+    mpCASESessionMgr = apCASESessionMgr;
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.cpp:53]: Doesn't `Shutdown` need to clear that pointer?

File: src/controller/tests/data_model/TestRead.cpp [hunk 5]
```diff
@@ -1436,6 +1436,12 @@ void TestReadInteraction::TestReadAttributeTimeout(nlTestSuite * apSuite, void *
     NL_TEST_ASSERT(apSuite, ctx.GetExchangeManager().GetNumActiveExchanges() == 0);
 }
 
+#if 0
```
Comment (bzbarsky-apple) [inline src/controller/tests/data_model/TestRead.cpp:1439]: If we were using sufficient callback control over things here, we could have it resub without redoing CASE, no?

File: src/transport/SessionManager.h [hunk 6]
```diff
@@ -126,6 +126,8 @@ class DLL_EXPORT SessionManager : public TransportMgrDelegate, public FabricTabl
     SessionManager();
     ~SessionManager() override;
 
+    FabricTable * GetFabricTable() const { return mFabricTable; }
```
Comment (bzbarsky-apple) [inline src/transport/SessionManager.h:129]: This is a really weird place to expose the fabric table.

**Review by bzbarsky-apple — COMMENTED** [review]
Let's do any chip-tool changes we want to do in a separate PR.

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp (hunk 3 above)
Comment (mrjerryjohns) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:33]: See calls to `InteractionModel::GetInstance()->...` in the file.

File: src/transport/SessionManager.h (hunk 6 above)
Comment (mrjerryjohns) [reply src/transport/SessionManager.h:129]: Didn't see the mFabricTable in the InteractionModelEngine. Will use that.

File: src/controller/tests/data_model/TestRead.cpp (hunk 5 above)
Comment (mrjerryjohns) [reply src/controller/tests/data_model/TestRead.cpp:1439]: We could, but I didn't feel inclined to do surgery on the the APIs in `ReadInteraction.h` to expose that level of control just for the sake of testing.

Comment (mrjerryjohns) [reply src/controller/tests/data_model/TestRead.cpp:1439]: We could do the testing with ReadClient directly...I could add that.

**Review by msandstedt — DISMISSED** [review]
Blocking merge until we have a chance to thoroughly review today.

I'm not implying there are problems in this PR.  There are just some critical interfaces that need to be vetted.

File: src/app/ReadClient.cpp [hunk 7]
```diff
@@ -957,48 +965,99 @@ CHIP_ERROR ReadClient::SendSubscribeRequestImpl(const ReadPrepareParams & aReadP
...
-        ChipLogProgress(DataManagement, "Resubscribe has been stopped");
-        return false;
+        auto * caseSessionManager = InteractionModelEngine::GetInstance()->GetCASESessionManager();
+        VerifyOrDie(caseSessionManager != nullptr);
+
+        auto fabric =
+            InteractionModelEngine::GetInstance()->GetExchangeManager()->GetSessionManager()->GetFabricTable()->FindFabricWithIndex(
+                _this->mPeer.GetFabricIndex());
+        VerifyOrExit(fabric != nullptr, err = CHIP_ERROR_INVALID_FABRIC_INDEX;
+                     ChipLogError(DataManagement, "Underlying fabric has gone away, stopping re-subscriptions!"););
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/app/ReadClient.cpp:1036]: No, I mean that removing the fabric should:
1. Kill off the relevant sessions.
2. And as a result have the client send errors to its consumer as needed and put itself in an OnDone state, with no more resubsribe attempts.

As in, we should not be reaching this code at all if the fabric is gone.

I absolutely agree we should not rely on applications doing anything here; this shoud all be handled in ReadClient.  But it should be handled before we get here.

File: src/app/ReadClient.h [hunk 8]
```diff
@@ -130,14 +132,30 @@ class ReadClient : public Messaging::ExchangeDelegate
...
+         * OnResubscriptionNeeded will be called when a subscription that was started with SendAutoResubscribeRequest has terminated
+         * and re-subscription is needed. The termination cause is provided to help inform subsequent re-subscription logic.
+         *
+         * The base implementation automatically re-subscribes at appropriate intervals taking the termination cause into account
+         * (see ReadClient::DefaultResubscribePolicy for more details). If the default implementation doesn't suffice, the logic of
+         * ReadClient::DefaultResubscribePolicy is broken down into its constituent methods that are publicly available for
+         * applications to call and sequence.
+         *
+         * If the method is over-ridden, it's the application's responsibility to take the appropriate steps needed to eventually
+         * call-back into the ReadClient object to schedule a re-subscription (by invoking ReadClient::ScheduleResubscription).
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/app/ReadClient.h:144]: OK, but what is the answer to my question about "consumers that want to set up CASE themselves"?  What do they need to do in practice, and how does what they need to do interact with Close/~ReadClient?

File: src/app/InteractionModelEngine.cpp (hunk 4 above)
Comment (bzbarsky-apple) [reply src/app/InteractionModelEngine.cpp:53]: I think it would be a good idea; followup is fine if desired.

File: src/app/InteractionModelEngine.h [hunk 9]
```diff
@@ -545,6 +551,8 @@ class InteractionModelEngine : public Messaging::UnsolicitedMessageHandler,
 
     FabricTable * mpFabricTable;
 
+    CASESessionManager * mpCASESessionMgr = nullptr;
```
[the remark this answers is not in the document]
Comment (msandstedt) [reply src/app/InteractionModelEngine.h:554]: Discussed offline.  The solution that the PR allows is to extend `ReadClient` and override `OnResubscriptionNeeded` to create a call-path that doesn't depend on `CASESessionManager` so that a null `CASESessionManager` can be passed at init.

That will work.  I have just requested that the instances of VerifyOrDie(GetCaseSessionManager != nullptr) be replaced with code that propagates the error if possible, as the point here is that `CASESessionManager` isn't _strictly_ required if one is willing to override this feature.

File: src/app/ReadClient.cpp [hunk 10]
```diff
@@ -957,48 +965,99 @@ CHIP_ERROR ReadClient::SendSubscribeRequestImpl(const ReadPrepareParams & aReadP
...
+
+void ReadClient::HandleDeviceConnectionFailure(void * context, PeerId peerId, CHIP_ERROR err)
+{
+    ReadClient * const _this = static_cast<ReadClient *>(context);
+    VerifyOrDie(_this != nullptr);
+
+    ChipLogError(DataManagement, "Failed connecting to device with error '%s'", err.AsString());
+
+    auto * caseSessionManager = InteractionModelEngine::GetInstance()->GetCASESessionManager();
+    VerifyOrDie(caseSessionManager != nullptr);
```
Comment (msandstedt) [inline src/app/ReadClient.cpp:1011]: Discussed offline.  I would request that we instead propagate an error here if we are claiming that it can be legal to pass a null CASESessionManager.

File: src/app/ReadClient.cpp [hunk 11]
```diff
@@ -957,48 +965,99 @@ CHIP_ERROR ReadClient::SendSubscribeRequestImpl(const ReadPrepareParams & aReadP
...
+
+    ChipLogProgress(DataManagement, "OnResubscribeTimerCallback: DoCASE = %d", _this->mDoCaseOnNextResub);
+    _this->mNumRetries++;
+
+    if (_this->mDoCaseOnNextResub)
     {
-        ChipLogProgress(DataManagement, "Resubscribe has been stopped");
-        return false;
+        auto * caseSessionManager = InteractionModelEngine::GetInstance()->GetCASESessionManager();
+        VerifyOrDie(caseSessionManager != nullptr);
```
Comment (msandstedt) [inline src/app/ReadClient.cpp:1030]: Discussed offline.  I would request that we instead propagate an error here if we are claiming that it can be legal to pass a null CASESessionManager.

File: src/app/ReadClient.cpp (hunk 10 above)
Comment (mrjerryjohns) [reply src/app/ReadClient.cpp:1011]: I'll convert the other VerifyOrDie to an error, but this one should likely still be a VerifyOrDie, since to get to this callback, it meant that you had to have had a CASESessionManager housing OperationalDeviceProxy instances.

Comment (msandstedt) [reply src/app/ReadClient.cpp:1011]: I would like to request then that this feature be moved out of the ReadClient base class and into an inherited class.

We already have consensus that ReadClient is one place where re-initiating CASE can occur, but that it's equally reasonable for that to happen in the app.  So let's make the code promise to support that and formalize that promise with this feature in a class extension.  Right now, there is no stability to this promise going forward and it would be non-obvious to future maintainers that ReadClient must support a usage without these calls into CASESessionManager.

I believe this change can be made without significant redesign of this feature.

**Review by msandstedt — DISMISSED** [review]
~~Requesting move of this feature out of the ReadClient base class.~~

See https://github.com/project-chip/connectedhomeip/pull/20080#discussion_r912492863.

File: src/app/ReadClient.cpp (hunk 10 above)
Comment (mrjerryjohns) [reply src/app/ReadClient.cpp:1011]: The existing ReadClient already handles re-subscriptions, so teasing that out into a separate extended class would be taking away a feature that already exists, which I don't think is something we can do.

Given that, it's not trivial nor sensible to split apart the CASE re-establishment logic from the timer management and re-sub scheduling logic that already exists in the client today into a separate extended class. If CASE is requested, the callback fired by the timer has to establish CASE, and not just motor on with the handle present inside the client object, which is why both bits of logic have to be sandwiched together.

> it would be non-obvious to future maintainers that ReadClient must support a usage without these calls into CASESessionManager.

Wouldn't documentation help here? Isn't reading that documentation an expectation of any future maintainer?

I'd view all of this from the lens of actually _fixing_ our current re-sub logic - it's broken because it never actually successfully re-subscribes in the 99% of cases that matter, because it never attempts to re-do CASE. Against that lens, this PR is not a new feature - it's a bug fix :)

Comment (msandstedt) [reply src/app/ReadClient.cpp:1011]: That is a fair assessment.  You're right that resubscription as a feature in the ReadClient isn't new.  It just didn't work.

Based on this then, I would welcome any documentation and test cases that give stability around supporting usage without a CASESessionManager.  It's just very important to us that this be a fully supported usage.

File: src/app/ReadClient.h [hunk 12]
```diff
@@ -315,6 +332,32 @@ class ReadClient : public Messaging::ExchangeDelegate
     // that's the only case when the consumer moved a ReadParams into the client.
     CHIP_ERROR SendAutoResubscribeRequest(ReadPrepareParams && aReadPrepareParams);
 
+    //
+    // This provides a standard re-subscription policy implementation that given a termination cause, does the following:
+    //      - Calculates the time till next subscription with fibonacci back-off (implemented by ComputeTimeTillNextSubscription()).
+    //      - Schedules the next subscription attempt at the computed interval from the previous step. Operational discovery and
+    //        CASE establishment will be attempted if aTerminationCause was CHIP_ERROR_TIMEOUT. In all other cases, it will attempt
+    //        to re-use a previously established session.
+    //
```
Comment (turon) [inline src/app/ReadClient.h:341]: Change comment style to doxygen compliant: `/** ... */`.

File: src/app/ReadClient.h [hunk 13]
```diff
@@ -315,6 +332,32 @@ class ReadClient : public Messaging::ExchangeDelegate
...
+    CHIP_ERROR DefaultResubscribePolicy(CHIP_ERROR aTerminationCause);
+
+    //
+    // Computes the time till the next re-subscription with millisecond resolution over
+    // an even increasing window following a fibonacci sequence with the current retry count
+    // used as input to the fibonacci algorithm.
+    //
+    // CHIP_RESUBSCRIBE_MAX_FIBONACCI_STEP_INDEX is used as the maximum ceiling for that input.
+    //
```
Comment (turon) [inline src/app/ReadClient.h:350]: Change comment style to doxygen compliant: `/** ... */`.

File: src/app/ReadClient.h [hunk 14]
```diff
@@ -315,6 +332,32 @@ class ReadClient : public Messaging::ExchangeDelegate
...
+    uint32_t ComputeTimeTillNextSubscription();
+
+    //
+    // Schedules a re-subscription aTimeTillNextResubscriptionMs into the future.
+    //
+    // If restablishCASE is true, operational discovery and CASE will be attempted at that time before
+    // the actual IM interaction is initiated.
+    //
```
Comment (turon) [inline src/app/ReadClient.h:358]: Change comment style to doxygen compliant: `/** ... */`.

File: src/app/ReadClient.h (hunk 1 above)
Comment (turon) [reply src/app/ReadClient.h:359]: The proposal to pass a `newSessionHandle` here triggered questions for me on the intended API flow for `ReadClient` related to peer binding.  Is this the following correct?

- `ReadClient` tracks subscriptions between a client and exactly one peer (implied by the fact that the class has a singular `mPeer` instance data.)
- The peer that a `ReadClient` object is bound to is set not in the constructor, but when `ReadClient::SendRequest` is called, where the peer info is passed via `ScheduleResubscription.mSessionHolder`.

Given this, shouldn't we strive to focus the external API more on the peer relationship, and setting the peer identity to track, rather than providing a particular active session (that could go away or be replaced) to that peer? 

Perhaps APIs like `SessionManager::FindSecureSessionForNode` could be leveraged to lookup the best known session for the bound peer (and trigger auto-creation if none exist) rather than have the app pass SessionHandles into more and more of the API surface?

**Review by turon — COMMENTED** [review]
:+1: Looks good -- Thanks @mrjerryjohns!

File: src/app/ReadClient.h (hunk 8 above)
[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/app/ReadClient.h:144]: > OK, but what is the answer to my question about "consumers that want to set up CASE themselves"?

Exactly as you mentioned above. I'll document that here.

[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/app/ReadClient.h:144]: >  and how does what they need to do interact with Close/~ReadClient?

If they're managing the timer themselves, there is no interaction, because what I was alluding to above was the need to cancel the CASE session attempt, and to clean-up timers in `Close` or `~ReadHandler` that won't apply here.

File: src/app/ReadClient.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/app/ReadClient.cpp:1036]: I've filed #21084 and added a note in this file.

File: src/app/ReadClient.cpp (hunk 11 above)
Comment (mrjerryjohns) [reply src/app/ReadClient.cpp]: I've since fixed this to return an error.

File: src/app/ReadClient.cpp (hunk 10 above)
Comment (mrjerryjohns) [reply src/app/ReadClient.cpp:966]: Added a test that validates re-subscription without a CASESessionManager (this is in fact that the only thing we can test easily right now without adding a lot of extra test infra).

File: src/app/ReadClient.h (hunk 1 above)
Comment (mrjerryjohns) [reply src/app/ReadClient.h]: > Given this, shouldn't we strive to focus the external API more on the peer relationship, and setting the peer identity to track, rather than providing a particular active session (that could go away or be replaced) to that peer?

All the IM client-side objects only accept `SessionHandle`s today, so we have to keep with that for now for 1.0, since doing anything different is a much bigger change than we can swallow right now.

File: src/controller/tests/data_model/TestRead.cpp (hunk 5 above)
Comment (mrjerryjohns) [reply src/controller/tests/data_model/TestRead.cpp]: I added both a C++ based unit-test that validates non-CASE based re-sub, as well as a Python based re-sub test.

File: src/app/ReadClient.cpp [hunk 15]
```diff
@@ -34,47 +34,10 @@
...
-
-    aNextSubscriptionIntervalMsec = waitTimeInMsec;
-    aShouldResubscribe            = true;
-    ChipLogProgress(DataManagement,
-                    "Computing Resubscribe policy: attempts %" PRIu32 ", max wait time %" PRIu32 " ms, selected wait time %" PRIu32
-                    " ms",
-                    aNumCumulativeRetries, maxWaitTimeInMsec, waitTimeInMsec);
-}
-
 ReadClient::ReadClient(InteractionModelEngine * apImEngine, Messaging::ExchangeManager * apExchangeMgr, Callback & apCallback,
```
[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/app/ReadClient.cpp:37]: It is still effectively a pointer, but one that cannot be null right?

I don't believe there is a real convention in the SDK around naming here, and since this existed before this PR, I'm inclined to keep it in the way it is for now.

File: src/app/ReadClient.cpp [hunk 16]
```diff
@@ -719,10 +730,11 @@ CHIP_ERROR ReadClient::ProcessEventReportIBs(TLV::TLVReader & aEventReportIBsRea
...
 
-            if (mReadPrepareParams.mResubscribePolicy != nullptr)
-            {
-                mReadPrepareParams.mEventNumber.SetValue(header.mEventNumber + 1);
-            }
+            //
+            // Update the event number being tracked in mReadPrepareParams in case
+            // we want to use it for re-subscriptions later.
+            //
+            mReadPrepareParams.mEventNumber.SetValue(header.mEventNumber + 1);
```
[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/app/ReadClient.cpp:701]: This is there from before, so won't update it in this PR for now.

File: src/app/ReadClient.h [hunk 17]
```diff
@@ -131,14 +138,30 @@ class ReadClient : public Messaging::ExchangeDelegate
...
+         *
+         * If the application DOES NOT want re-subscription to happen on a particular invocation of this method, returning anything
+         * other than CHIP_NO_ERROR will terminate the interaction and result in OnError, OnDeallocatePaths and OnDone being called
+         * in that sequence.
+         *
+         * This object MUST continue to exist after this call is completed. The
          * application shall wait until it receives an OnDone call to destroy the object.
          *
          * @param[in] aTerminationCause The cause of failure of the subscription that just terminated.
-         * @param[in] aNextResubscribeIntervalMsec How long we will wait before trying to auto-resubscribe.
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.h:139]: So in the new setup, how does a ReadClient::Callback that does not want to manage its own resubscribe timing get informed about what the selected timing is?  Is it by calling `ComputeTimeTillNextSubscription()`?  Might be worth documenting that.

File: src/app/ReadClient.h [hunk 18]
```diff
@@ -168,7 +191,6 @@ class ReadClient : public Messaging::ExchangeDelegate
          *      - Be called even in error circumstances.
          *      - Only be called after a successful call to SendRequest has been
          *        made, when the read completes or the subscription is shut down.
-         *
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.h:171]: Why this change.  Please put the empty line back....

File: src/app/ReadClient.h [hunk 19]
```diff
@@ -301,21 +323,59 @@ class ReadClient : public Messaging::ExchangeDelegate
...
+     *  Like SendSubscribeRequest, but the ReadClient will automatically attempt to re-establish the subscription if
+     *  we decide that the subscription has dropped.  The exact behavior of the re-establishment can be controlled
+     *  by setting mResubscribePolicy in the ReadPrepareParams.  If not set, a default behavior with exponential backoff will be
+     *  used.
+     *
+     *  The application has to know to
+     *  a) allocate a ReadPrepareParams object that will have fields mpEventPathParamsList and mpAttributePathParamsList and
+     *  mpDataVersionFilterList with lifetimes as long as the ReadClient itself and b) free those up later in the call to
+     *  OnDeallocatePaths. Note: At a given time in the system, you can either have a single subscription with re-sub enabled that
+     *  that has mKeepSubscriptions = false, OR, multiple subs with re-sub enabled with mKeepSubscriptions = true. You shall not
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.h:336]:
```suggestion
     *  has mKeepSubscriptions = false, OR, multiple subs with re-sub enabled with mKeepSubscriptions = true. You shall not
```

File: src/app/ReadClient.h [hunk 20]
```diff
@@ -301,21 +323,59 @@ class ReadClient : public Messaging::ExchangeDelegate
...
+     *     to re-use a previously established session.
+     */
+    CHIP_ERROR DefaultResubscribePolicy(CHIP_ERROR aTerminationCause);
+
+    /**
+     * Computes the time till the next re-subscription with millisecond resolution over
+     * an ever increasing window following a fibonacci sequence with the current retry count
+     * used as input to the fibonacci algorithm.
+     *
+     * CHIP_RESUBSCRIBE_MAX_FIBONACCI_STEP_INDEX is used as the maximum ceiling for that input.
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.h:358]: For what input?

File: src/app/ReadClient.h [hunk 21]
```diff
@@ -301,21 +323,59 @@ class ReadClient : public Messaging::ExchangeDelegate
...
+     *   This provides a standard re-subscription policy implementation that given a termination cause, does the following:
+     *   - Calculates the time till next subscription with fibonacci back-off (implemented by ComputeTimeTillNextSubscription()).
+     *   - Schedules the next subscription attempt at the computed interval from the previous step. Operational discovery and
+     *     CASE establishment will be attempted if aTerminationCause was CHIP_ERROR_TIMEOUT. In all other cases, it will attempt
+     *     to re-use a previously established session.
+     */
+    CHIP_ERROR DefaultResubscribePolicy(CHIP_ERROR aTerminationCause);
+
+    /**
+     * Computes the time till the next re-subscription with millisecond resolution over
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.h:354]:
```suggestion
     * Computes the time, in milliseconds, until the next re-subscription over
```

File: src/app/ReadClient.h [hunk 22]
```diff
@@ -301,21 +323,59 @@ class ReadClient : public Messaging::ExchangeDelegate
...
+     *
+     * CHIP_RESUBSCRIBE_MAX_FIBONACCI_STEP_INDEX is used as the maximum ceiling for that input.
+     *
+     */
+    uint32_t ComputeTimeTillNextSubscription();
+
+    /**
+     * Schedules a re-subscription aTimeTillNextResubscriptionMs into the future.
+     *
+     * If an application wants to setup CASE on their own, they should call ComputeTimeTillNextSubscription() to compute the next
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.h:366]:
```suggestion
     * If an application wants to set up CASE on their own, they should call ComputeTimeTillNextSubscription() to compute the next
```

File: src/app/ReadClient.h [hunk 23]
```diff
@@ -301,21 +323,59 @@ class ReadClient : public Messaging::ExchangeDelegate
...
+     * interval at which they should attempt CASE and attempt CASE at that time. On successful CASE establishment, this method
+     * should be called with the new SessionHandle provided through 'aNewSessionHandle', 'aTimeTillNextResubscriptionMs' set to 0
+     * (i.e re-subscribe immediately) and 'aReestablishCASE' set to false.
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.h:369]: This makes it sounds like passing 0 will try to re-subscribe sync from inside this function, when it's actually going to still do it async, right?  Maybe replace "immediately" with "async, but as soon as possible"?

File: src/app/InteractionModelEngine.h [hunk 24]
```diff
@@ -102,17 +104,28 @@ class InteractionModelEngine : public Messaging::UnsolicitedMessageHandler,
...
-    Messaging::ExchangeManager * GetExchangeManager(void) const { return mpExchangeMgr; };
+    Messaging::ExchangeManager * GetExchangeManager(void) const { return mpExchangeMgr; }
+
+    /**
+     * Returns a pointer to the CASESessionManager. This can return nullptr if one wasn't
+     * provided in the call to Init().
+     */
+    CASESessionManager * GetCASESessionManager() const { return mpCASESessionMgr; }
+
+    FabricTable * GetFabricTable() const { return mpFabricTable; }
```
[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/app/InteractionModelEngine.h:128]: Will remove - it was there originally prior to my PeerId->ScopedNodeId changes, but once that was done, this is not needed anymore.

File: src/app/InteractionModelEngine.h [hunk 25]
```diff
@@ -102,17 +104,28 @@ class InteractionModelEngine : public Messaging::UnsolicitedMessageHandler,
...
+     *  @param[in]    apCASESessionMgr An optional pointer to a CASESessionManager (used for re-subscriptions).
      *
      *  @retval #CHIP_ERROR_INCORRECT_STATE If the state is not equal to
      *          kState_NotInitialized.
      *  @retval #CHIP_NO_ERROR On success.
      *
      */
-    CHIP_ERROR Init(Messaging::ExchangeManager * apExchangeMgr, FabricTable * apFabricTable);
+    CHIP_ERROR Init(Messaging::ExchangeManager * apExchangeMgr, FabricTable * apFabricTable,
+                    CASESessionManager * apCASESessionMgr = nullptr);
```
Comment (msandstedt) [inline src/app/InteractionModelEngine.h:116]: This = nullptr default argument is very much appreciated as an obvious signal, in addition to the docs header, that null is legal.

File: src/app/ReadClient.cpp [hunk 26]
```diff
@@ -531,7 +553,7 @@ CHIP_ERROR ReadClient::ProcessReportData(System::PacketBufferHandle && aPayload)
 exit:
     if (IsSubscriptionType())
     {
-        if (IsAwaitingInitialReport())
+        if (IsAwaitingInitialReport() || IsAwaitingSubscribeResponse())
```
[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/app/ReadClient.cpp:556]: `RefreshLivenessCheckTimer` relies on a valid value for `mMaxInterval` to correctly setup the timers, which means that it should only be run post subscription establishment.

Today, this is calling that function even when we're in the priming phase (i.e in the 2nd-to-Nth report in the priming phase), where `IsAwaitingInitialReport` is no longer true. Consequently, it's actually priming the liveness timer to fire using a mMaxInterval value of 0. We're just lucky that the ACK timeout being tacked on is so large that it never fires during the time that priming is happening.

I'll fix this logic to not be that awkward.

File: src/app/ReadClient.cpp [hunk 27]
```diff
@@ -914,48 +949,92 @@ CHIP_ERROR ReadClient::SendSubscribeRequestImpl(const ReadPrepareParams & aReadP
...
+
+void ReadClient::HandleDeviceConnectionFailure(void * context, const ScopedNodeId & peerId, CHIP_ERROR err)
+{
+    ReadClient * const _this = static_cast<ReadClient *>(context);
+    VerifyOrDie(_this != nullptr);
+
+    ChipLogError(DataManagement, "Failed to establish CASE for re-subscription with error '%" CHIP_ERROR_FORMAT "'", err.Format());
+
+    auto * caseSessionManager = InteractionModelEngine::GetInstance()->GetCASESessionManager();
+    VerifyOrDie(caseSessionManager != nullptr);
```
[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/app/ReadClient.cpp:994]: It was there I think because I was releasing the session there-after. Since I'm no longer doing that, this should be removed as well.

File: src/app/ReadClient.cpp [hunk 28]
```diff
@@ -914,48 +949,92 @@ CHIP_ERROR ReadClient::SendSubscribeRequestImpl(const ReadPrepareParams & aReadP
...
     {
-        ChipLogProgress(DataManagement, "Resubscribe has been stopped");
-        return false;
+        auto * caseSessionManager = InteractionModelEngine::GetInstance()->GetCASESessionManager();
+        VerifyOrExit(caseSessionManager != nullptr, err = CHIP_ERROR_INCORRECT_STATE);
+
+        auto proxy = caseSessionManager->FindExistingSession(_this->mPeer);
+        if (proxy != nullptr)
+        {
+            proxy->Disconnect();
```
[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/app/ReadClient.cpp:1017]: > So the issue here is that just because we timed out in the sense of not getting a report that does not mean that we had an exchange-level timeout and so the session may not be marked defunct, I guess?

That's right.

Now that you've raised attention to it, I'm going to actually fix this logic to directly do this instead:
```
        if (_this->mReadPrepareParams.mSessionHolder) {
            _this->mReadPrepareParams.mSessionHolder.Get().Value()->AsSecureSession()->MarkAsDefunct();
        }
```

That should achieve an identical effect.

Importantly, with @tehampson 's changes coming up, methods like `FindExistingSession` will no longer be there nor make sense.

File: src/app/ReadClient.cpp [hunk 29]
```diff
@@ -914,48 +949,92 @@ CHIP_ERROR ReadClient::SendSubscribeRequestImpl(const ReadPrepareParams & aReadP
...
     {
-        ChipLogError(DataManagement, "Fail to resubscribe with error %" CHIP_ERROR_FORMAT, err.Format());
-        return false;
+        //
+        // Call Close (which should trigger re-subscription again) EXCEPT if we got here because we didn't have a valid fabric,
+        // or an invalid CASESessionManager pointer when mDoCaseOnNextResub was true.
+        //
+        // In that case, don't permit re-subscription to occur.
+        //
+        _this->Close(err, err != CHIP_ERROR_INVALID_FABRIC_INDEX && err != CHIP_ERROR_INCORRECT_STATE);
```
[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/app/ReadClient.cpp:1036]: Yup, will fix. Remains from the pre-ScopedNodeId changes that I didn't get to clean-up.

File: src/app/ReadClient.h (hunk 17 above)
Comment (mrjerryjohns) [reply src/app/ReadClient.h:139]: Isn't this text sufficient?

> If the default implementation doesn't suffice, the logic of ReadClient::DefaultResubscribePolicy is broken down into its constituent methods that are publicly available for applications to call and sequence.

If you go to that method, it has further documentation on the two methods it calls, and so on.

File: src/app/ReadClient.h (hunk 20 above)
Comment (mrjerryjohns) [reply src/app/ReadClient.h:358]: The context for input is provided in the sentence before that?

File: src/app/ReadClient.h (hunk 23 above)
Comment (mrjerryjohns) [reply src/app/ReadClient.h:369]: Sure.

File: src/controller/python/test/test_scripts/base.py [hunk 30]
```diff
@@ -756,6 +756,58 @@ def CompareUnfilteredData(accessingFabric, otherFabric, expectedData):
...
+        ''' This validates the re-subscription logic by triggering a liveness failure caused by the expiration
+            of the underlying CASE session and the resultant failure to receive reports from the server. This should
+            trigger CASE session establishment and subscription restablishment. Both the attempt and successful
+            restablishment of the subscription are validated.
+        '''
+        cv = asyncio.Condition()
+        resubAttempted = False
+        resubSucceeded = True
+
+        async def OnResubscriptionAttempted(transaction, errorEncountered: int, nextResubsribeIntervalMsec: int):
```
Comment (tcarmelveilleux) [inline src/controller/python/test/test_scripts/base.py:769]: nit: `nextResubcribeIntervalMsec`

File: src/app/ReadClient.cpp (hunk 28 above)
[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/app/ReadClient.cpp:1017]: Alas, this won't work until @tehampson 's changes are merged. Because right now, marking a session defunct has no effect on other existing session holders. Today, `OperationalDeviceProxy` instances just linger around, and so calling `FindOrEstablishSession` just returns back the existing object bound to the existing session. And that goes nowhere.

File: src/app/ReadClient.h (hunk 20 above)
Comment (mrjerryjohns) [reply src/app/ReadClient.h]: Updated the sentence.

File: src/app/ReadClient.cpp (hunk 28 above)
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/app/ReadClient.cpp:1038]: Yep, that's right.  Calling Disconnect is the right thing for now.

File: src/app/ReadClient.cpp (hunk 26 above)
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/app/ReadClient.cpp]: Yes, the new thing is much clearer, thank you!

File: src/app/ReadClient.cpp [hunk 31]
```diff
@@ -914,48 +954,108 @@ CHIP_ERROR ReadClient::SendSubscribeRequestImpl(const ReadPrepareParams & aReadP
...
+        // We need to mark our session as defunct explicitly since the assessment of a liveness failure
+        // is usually triggered by the absence of any exchange activity that would have otherwise
+        // automatically marked the session as defunct on a response timeout.
+        //
+        // Doing so will ensure that the subsequent call to FindOrEstablishSession will not bind to
+        // an existing established session but rather trigger establishing a new one.
+        //
+        if (_this->mReadPrepareParams.mSessionHolder)
+        {
+            _this->mReadPrepareParams.mSessionHolder.Get().Value()->AsSecureSession()->MarkAsDefunct();
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.cpp:1027]:
```suggestion
            _this->mReadPrepareParams.mSessionHolder->AsSecureSession()->MarkAsDefunct();
```
does the same thing, but is less noisy.

File: src/app/ReadClient.cpp [hunk 32]
```diff
@@ -914,48 +954,108 @@ CHIP_ERROR ReadClient::SendSubscribeRequestImpl(const ReadPrepareParams & aReadP
...
+    err = _this->SendSubscribeRequest(_this->mReadPrepareParams);
+
+exit:
     if (err != CHIP_NO_ERROR)
     {
-        ChipLogError(DataManagement, "Fail to resubscribe with error %" CHIP_ERROR_FORMAT, err.Format());
-        return false;
+        //
+        // Call Close (which should trigger re-subscription again) EXCEPT if we got here because we didn't have a valid fabric,
+        // or an invalid CASESessionManager pointer when mDoCaseOnNextResub was true.
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.cpp:1053]:
```suggestion
        // Call Close (which should trigger re-subscription again) EXCEPT if we got here because we didn't have a valid
        // CASESessionManager pointer when mDoCaseOnNextResub was true.
```

**Review by bzbarsky-apple — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]

File: src/app/ReadClient.cpp [hunk 33]
```diff
@@ -914,48 +954,108 @@ CHIP_ERROR ReadClient::SendSubscribeRequestImpl(const ReadPrepareParams & aReadP
...
+        //
+        auto proxy = caseSessionManager->FindExistingSession(_this->mPeer);
+        if (proxy != nullptr)
+        {
+            proxy->Disconnect();
+        }
+
+        caseSessionManager->FindOrEstablishSession(_this->mPeer, &_this->mOnConnectedCallback,
+                                                   &_this->mOnConnectionFailureCallback);
+        return;
```
Comment (yunhanw-google) [inline src/app/ReadClient.cpp:1043]: After the existing session is disconnected, we return here, then next time, we would do resubscription?

File: src/app/ReadClient.cpp [hunk 34]
```diff
@@ -914,48 +954,108 @@ CHIP_ERROR ReadClient::SendSubscribeRequestImpl(const ReadPrepareParams & aReadP
...
-    uint32_t intervalMsec        = 0;
-    aNextResubscribeIntervalMsec = 0;
-    if (mReadPrepareParams.mResubscribePolicy == nullptr)
+    ReadClient * const _this = static_cast<ReadClient *>(context);
+    VerifyOrDie(_this != nullptr);
+
+    ChipLogProgress(DataManagement, "HandleDeviceConnected %d\n", device->GetSecureSession().HasValue());
+    _this->mReadPrepareParams.mSessionHolder.Grab(device->GetSecureSession().Value());
+
+    auto err = _this->SendSubscribeRequest(_this->mReadPrepareParams);
```
Comment (yunhanw-google) [inline src/app/ReadClient.cpp:985]: now we would send subscription once the device is connected via HandleDeviceConnected? this callback is called from underneath session?

File: src/app/ReadClient.cpp (hunk 33 above)
Comment (mrjerryjohns) [reply src/app/ReadClient.cpp:1043]: That's right. We return here because we need to wait till the CASE session either establishes and `HandleDeviceConnected` is called, at which point re-subscription is initiated, OR, `HandleDeviceConnectionFailure` and we then re-schedule OnResubscribeTimerCallback and the whole process repeats...

Comment (yunhanw-google) [reply src/app/ReadClient.cpp:1043]: thanks for clarification.

**Review by msandstedt — APPROVED** [review]
