### PR TITLE
Generate Documentation for python API: Fix TOC links

### LINKED ISSUE #39667: ChipDeviceCtrl API documentation - Fix links
The links in the TOC don't work in the compiled documentation:

https://project-chip.github.io/connectedhomeip-doc/testing/ChipDeviceCtrlAPI.html#

### PR DESCRIPTION
**Pull request by juandediosg**
### Summary

This PR fixes broken Table of Contents (TOC) links in the generated `ChipDeviceCtrlAPI.md` file.

### Issue
The generated Markdown documentation (`ChipDeviceCtrlAPI.md`) did not generate functional links in the table of contents (TOC) when generated a HTML via CMake build. This broke internal navigation.

### RCA (Root cause Analysis)
The original pydoc-markdown used the below config, that resulted in TOC links in the Markdown did not have proper ID anchors, causing broken navigation in the generated HTML.
```bash
insert_header_anchors: false
add_full_prefix: false
```

### Solution
Updated the pydoc-markdown configuration to automatically insert proper ID anchors, thus removing the awk command.
```bash
insert_header_anchors: true
add_full_prefix: false
```
Now the TOC entries show as `RegisterOnActiveCallback` instead of `chip.ChipDeviceCtrl.RegisterOnActiveCallback` with the anchor link like below
```bash
* [RegisterOnActiveCallback](#chip.ChipDeviceCtrl.RegisterOnActiveCallback)
```

### Related issues
Fixes https://github.com/project-chip/connectedhomeip/issues/39667
- Documentation for python API [#37751](https://github.com/project-chip/connectedhomeip/issues/37751) 
- Generate ChipDeviceCtrl API doc on build [#34761](https://github.com/project-chip/connectedhomeip/pull/34761)
- Documentation for python API - Docstring Updates [#38200](https://github.com/project-chip/connectedhomeip/pull/38200)
- Generate Documentation for python API - Docstring Updates (Only ChipDeviceCtrl) + CI Integration [#38283](https://github.com/project-chip/connectedhomeip/pull/38283)

### Testing
Run the following commands to generate and verify the documentation:

#### Run locally
- Run the script to generate the documentation:
  ``` bash
  bash docs/testing/GenerateChipDeviceCtrlDoc.sh docs/testing
  ```
- Check that the output file is generated and updated:
  ``` bash
  ls -l docs/testing/ChipDeviceCtrlAPI.md
  ```
- Build the full documentation using Make (as CI does)
  ``` bash
  make -C docs html
  ```
- Check that the output HTML file is generated and updated:
  ``` bash
  ls -l docs/_build/html/testing/ChipDeviceCtrlAPI.html
  ```

#### Run simulating CI
To simulate how the CI pipeline generates and builds documentation, follow the below steps:
- Create the target direcoty:
  ``` bash
  mkdir -p _build/src/testing
  ```
- Run the script to generate the documentation:
This will create `ChipDeviceCtrlAPI.md` inside the `_build/src/testing directory`:
  ``` bash
  bash docs/testing/GenerateChipDeviceCtrlDoc.sh _build/src/testing
  ```
- Build the full documentation using Make (as CI does)
  ``` bash
  make -C docs html
  ```

#### Documentation Generation Validation
Please validate the generated documentation files to ensure they are free of errors and broken references:

- **Markdown file**: Verify the generated `.md` file (e.g., `ChipDeviceCtrlAPI.md`) in `_build/src/testing`  and check
  - Includes valid ID anchor links. 
- **HTML output files**: Check the generated HTML files in `docs/_build/html/testing/` and check:
  - Internal table of contents (TOC) links are working.
  - Anchor navigation jumps to the correct section.
  - No broken references.

### CODE REVIEW

File: docs/testing/GenerateChipDeviceCtrlDoc.sh [hunk 1]
```diff
@@ -30,7 +30,7 @@ pydoc-markdown -I "$PYTHONPATH" --py3 -m chip.ChipDeviceCtrl '{
       descriptive_class_title: false,
       render_toc: true,
       render_toc_title: "ChipDeviceCtrl.py API",
-      insert_header_anchors: false,
+      insert_header_anchors: true,
```
[the remark this answers is not in the document]
Comment (juandediosg) [reply docs/testing/GenerateChipDeviceCtrlDoc.sh:33]: Fixed;  Removed awk; anchors now handled via config (insert_header_anchors=true, add_full_prefix=false)

File: docs/testing/GenerateChipDeviceCtrlDoc.sh [hunk 2]
```diff
@@ -30,9 +30,7 @@ pydoc-markdown -I "$PYTHONPATH" --py3 -m chip.ChipDeviceCtrl '{
...
```
Comment (asirko-soft) [inline docs/testing/GenerateChipDeviceCtrlDoc.sh:33]: Per pydoc-markdown documentation, this is enabled by default https://niklasrosenstein.github.io/pydoc-markdown/api/pydoc_markdown/renderers/markdown/#insert_header_anchors I guess this setting might be removed entirely, except if you want to have it there for clarity?

**Review by asirko-soft — APPROVED** [review]

File: docs/testing/GenerateChipDeviceCtrlDoc.sh (hunk 2 above)
Comment (juandediosg) [reply docs/testing/GenerateChipDeviceCtrlDoc.sh:33]: @asirko-soft Thanks for the feedback! I will keep this setting for clarity and readability in the config, even though it is enabled by default.

**Review by cecille — APPROVED** [review]
