### PR TITLE
Fix empty struct generation

### LINKED ISSUE #3873: af-structs.zapt generates empty structs instead of 'typedef uint8_t'
You should probably not take it on faith.

If you look at it twice you may noticed that there are some empty structs. For example:

With `ZAP` templates:
```
// Struct for Signature
typedef struct _Signature
{
} EmberAfSignature;
```

With `AppBuilder`:
```
// Void typedef for EphemeralData which is empty.
// this will result in all the references to the data being as uint8_t*
typedef uint8_t EphemeralData;
```

It does work because those are not used. I will open an issue for them.

_Originally posted by @vivien-apple in https://github.com/project-chip/connectedhomeip/pull/3826#discussion_r524305610_

### PR DESCRIPTION
**Pull request by jepenven-silabs**
#### Problem
ZAP was generating empty struct instead of defaulting them to `uint8_t` 

 #### Summary of Changes
Check the number of item within the struct before generating a `typedef struct`

Cleanup the code in the template by adding a new helper in `chip-helper.js`

 Fixes #3873

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

File: src/app/zap-templates/helper-chip.js [hunk 1]
```diff
@@ -69,6 +72,35 @@ function isCommandAvailable(clusterSide, incoming, outgoing, source, name) {
...
+ *
+ * @param {*} type : The xml type to be converted
+ */
+function asChipUnderlyingType(label, type) {
+
+  if (zclHelper.isStrEqual(label, "endpoint")) {
+    return 'chip::EndpointId'
+  } else if (zclHelper.isStrEqual(label, "endpointId")) {
+    return 'chip::EndpointId'
+  } else if (zclHelper.isStrEqual(label, "CLUSTER_ID")) {
```
Comment (vivien-apple) [inline src/app/zap-templates/helper-chip.js:89]: `label` -> `type`

File: src/app/zap-templates/helper-chip.js [hunk 2]
```diff
@@ -69,6 +72,35 @@ function isCommandAvailable(clusterSide, incoming, outgoing, source, name) {
...
+    return 'chip::ClusterId'
+  } else if (zclHelper.isStrEqual(label, "ATTRIBUTE_ID")){
```
Comment (vivien-apple) [inline src/app/zap-templates/helper-chip.js:91]: `label` -> `type`

File: src/app/zap-templates/helper-chip.js [hunk 3]
```diff
@@ -69,6 +72,35 @@ function isCommandAvailable(clusterSide, incoming, outgoing, source, name) {
   return false;
 }
 
+/**
+ * Returns CHIP specific type for ZCL framework
+ * This function is flawed since it relies on the
+ * type label for CHIP type conversion. CHIP specific XML should have the
+ * correct type directly embedded inside.
+ *
+ * @param {*} type : The xml type to be converted
```
Comment (vivien-apple) [inline src/app/zap-templates/helper-chip.js:81]: Worth adding a doc comment about the label too

File: src/app/zap-templates/helper-chip.js [hunk 4]
```diff
@@ -69,6 +72,35 @@ function isCommandAvailable(clusterSide, incoming, outgoing, source, name) {
...
+  } else if (zclHelper.isStrEqual(label, "CLUSTER_ID")) {
+    return 'chip::ClusterId'
+  } else if (zclHelper.isStrEqual(label, "ATTRIBUTE_ID")){
+    return 'chip::AttributeId'
+  } else if (zclHelper.isStrEqual(label, "groupId")) {
+    return 'chip::GroupId'
+  } else if (zclHelper.isStrEqual(label, "commandId")) {
+    return 'chip::CommandId'
+  } else {
+    // Might want to use asZclUnderlyingType instead. TBD
```
Comment (vivien-apple) [inline src/app/zap-templates/helper-chip.js:98]: The answer to this is yes at the moment. Can you use that instead ?

**Review by vivien-apple — CHANGES_REQUESTED** [review]

File: src/app/zap-templates/helper-chip.js (hunk 4 above)
Comment (jepenven-silabs) [reply src/app/zap-templates/helper-chip.js:98]: For now I'll stick with the `asUnderlyingType` since the `asUnderlyingZclType` seems to have a problem depending on the context it is used in.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by vivien-apple — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@jepenven-silabs Please resolve the conflicts?

**Comment by jepenven-silabs** [comment]
> @jepenven-silabs Please resolve the conflicts?

Resolved
