### PR TITLE
Fix Ble endpoint pool FULL on macOS controller

### LINKED ISSUE #6863: chip-tool on Mac throws Ble endpoint pool FULL
With ToT (8a51de25248b6ab506d30e89f0f95b216d06729c) code, chip-tool on Mac throws BLE EndPT full error when trying to provision accessory running on raspi

 ./out/host/chip-tool pairing ble-wifi MYSSID MYPASSWD 87564321 20202021 3840
[1621203866816] [0x989948] CHIP: [DL] _Init
[1621203866816] [0x989948] CHIP: [IN] TransportMgr initialized
[1621203866816] [0x989948] CHIP: [DIS] Init admin pairing table with server storage.
[1621203866816] [0x989948] CHIP: [IN] local node id is 0x000000000001b669
[1621203866816] [0x989948] CHIP: [ZCL] Using ZAP configuration...
[1621203866816] [0x989948] CHIP: [ZCL] deactivate report event
[1621203866816] [0x989948] CHIP: [CTL] Getting operational keys
[1621203866816] [0x989948] CHIP: [CTL] Generating operational certificate for the controller
[1621203866817] [0x989948] CHIP: [CTL] Getting root certificate for the controller from the issuer
[1621203866817] [0x989948] CHIP: [CTL] Generating credentials
[1621203866817] [0x989948] CHIP: [CTL] Loaded credentials successfully
[1621203866817] [0x989957] CHIP: [DL] CHIP task running
[1621203866817] [0x989948] CHIP: [DMG] ICR moving to [Initialize]
[1621203866818] [0x989948] CHIP: [BLE] NewConnection
[1621203866821] [0x989948] CHIP: [BLE] Assigned local session key ID 0
[1621203866821] [0x989948] CHIP: [IN] Message appended to BLE send queue
[1621203866821] [0x989948] CHIP: [BLE] Sent PBKDF param request
[1621203866884] [0x989958] CHIP: [BLE] CBManagerState: ON
[1621203870549] [0x989959] CHIP: [BLE] Connecting to device with discriminator: 3840
[1621203873627] [0x989958] CHIP: [IN] BleConnectionComplete: endPoint 0x10ce8a8f0
[1621203873627] [0x989958] CHIP: [BLE] Ble endpoint pool FULL
[1621203873627] [0x989958] CHIP: [IN] Clearing BLE pending packets.
[1621203873627] [0x989958] CHIP: [IN] BleConnection Error: Ble Error 6002 (0x00001772): No more BLE endpoints
[1621203874433] [0x989958] CHIP: [BLE] subscribe complete, ep = 0x10ce8a8f0
[1621203874482] [0x989958] CHIP: [BLE] peripheral chose BTP version 3; central expected between 2 and 3
[1621203874482] [0x989958] CHIP: [BLE] using BTP fragment sizes rx 20 / tx 128.
[1621203874482] [0x989958] CHIP: [BLE] local and remote recv window size = 3
[1621203874482] [0x989958] CHIP: [IN] BLE EndPoint 0x10ce8a8f0 Connection Complete
[1621203896822] [0x989957] CHIP: [TOO] Pairing Failure: CHIP Error 4050 (0x00000FD2): Timeout
[1621203896822] [0x989957] CHIP: [BLE] PASESession timed out while waiting for a response from the peer. Expected message type was 33
[1621203896822] [0x989957] CHIP: [TOO] Secure Pairing Failed
[1621203896822] [0x989948] CHIP: [CTL] Shutting down the commissioner
[1621203896822] [0x989948] CHIP: [CTL] Shutting down the controller
[1621203896823] [0x989957] CHIP: [TOO] Pairing Failure: CHIP Error 4050 (0x00000FD2): Timeout
[1621203896823] [0x989948] CHIP: [DL] System Layer shutdown
[1621203896823] [0x989948] CHIP: [DL] Inet Layer shutdown
[1621203896823] [0x989948] CHIP: [DL] BLE layer shutdown
[1621203896823] [0x989948] CHIP: [IN] Clearing BLE pending packets.
[1621203896823] [0x989948] CHIP: [BLE] Auto-closing end point's BLE connection.
[1621203896836] [0x989948] CHIP: [DMG] ICR moving to [Uninitiali]

### PR DESCRIPTION
**Pull request by krypton36**
#### Problem
What is being fixed?  Examples:
* Fixes #6863 chip-tool on Mac throws Ble endpoint pool FULL

#### Change overview
- Updated the found variable from local to global.
- Prevents multiple calls to the same service.

#### Testing
How was this tested? (at least one bullet point required)
* Tested pairing BLE accessory with chip-device-ctrl 
* BLE accessory that was tested was RasPi (Linux)
* Controller platform was macOS
* macOS is the only platform accepted

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]
A description of "why" a bug occurs would help in the summary. For example "didDiscoverServices is called multiple times, which results in ....".

This would help reviewers understand the change and see if it is appropriate.

**Comment by andy31415** [comment]
@krypton36 pleas sign the CLA and update the summary to describe the problem (i.e. what causes it rather than linking to the bug. The bug just says "error BLE endpoint full" without explaining what causes it to get full)

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]
So I'm trying to understand this change.  It seems like the real thing that's going on here is that `didDiscoverServices`is called multiple times, and while the first call finds a service that matches `_shortServiceUUID` some subsequent call does not and then we (incorrectly?) fail the connnection?

First, is that what is going on here?

Second, what happens ifthe calls to `didDiscoverServices` come in the opposite order?  That would still fail out, right?  Why can that not happen?

In general, some documentation in the commit message about why the previous setup does not work and hence needs to be changed would be very helpful to keep this from regressing.

File: src/platform/Darwin/BleConnectionDelegateImpl.mm [hunk 1]
```diff
@@ -103,6 +104,7 @@ - (id)initWithDiscriminator:(uint16_t)deviceDiscriminator
         _chipWorkQueue = chip::DeviceLayer::PlatformMgrImpl().GetWorkQueue();
         _timer = dispatch_source_create(DISPATCH_SOURCE_TYPE_TIMER, 0, 0, _workQueue);
         _centralManager = [CBCentralManager alloc];
+        _found = false;
```
Comment (cjandhyala) [inline src/platform/Darwin/BleConnectionDelegateImpl.mm:107]: this variable never seem to be used.

File: src/platform/Darwin/BleConnectionDelegateImpl.mm [hunk 2]
```diff
@@ -206,17 +208,15 @@ - (void)peripheral:(CBPeripheral *)peripheral didDiscoverServices:(NSError *)err
         ChipLogError(Ble, "BLE:Error finding Chip Service in the device: [%s]", [error.localizedDescription UTF8String]);
     }
 
-    bool found;
-
     for (CBService * service in peripheral.services) {
-        if ([service.UUID.data isEqualToData:_shortServiceUUID.data]) {
-            found = true;
+        if ([service.UUID.data isEqualToData:_shortServiceUUID.data] && !self.found) {
```
Comment (cjandhyala) [inline src/platform/Darwin/BleConnectionDelegateImpl.mm:212]: Would this "!self.found" allow to provision multiple BLE devices using home app ?

File: src/platform/Darwin/BleConnectionDelegateImpl.mm (hunk 1 above)
Comment (bzbarsky-apple) [reply src/platform/Darwin/BleConnectionDelegateImpl.mm:107]: `_found` is another name for `self.found`, mostly.  So it's used.

**Comment by woody-apple** [comment]
@mspang @saurabhst @msandstedt @Damian-Nordic @jmartinez-silabs @LuDuda

@krypton36 Thank you for your submission, can you please sign the CLA? Thanks!

**Review by jmartinez-silabs — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Comment by yufengwangca** [comment]
I have confirmed I no longer see "BLE endpoint Full" issue with this change.

**Review by bzbarsky-apple — APPROVED** [review]
This is OK as a workaround, but I'd still really like us to figure out a better way to fix this...
