### PR TITLE
Draft: Add configurable ep1 ACLs and bindings

### LINKED ISSUE #23208: [Platform] AutoCommissioner gaps (reset failsafe, retry net config)
### Reproduction steps

1. There is no simple way to reset the failsafe timer during commissioning
- When user input is needed during commissioning (ex: to select a network, to respond to attestation issues), the failsafe timer must be set to a high value.
- During this time, it would be useful to have a command to reset the failsafe timer.
- Prior to CASE (operational discovery), it would be useful to be able to reset the failsafe timer to a smaller value.

2. There is no simple way to retry a different network config when the first attempt fails
- Since its an error, the CHIPDeviceController automatically cleans itself up (cancels commissioning.
- It would be useful to be able to allow the UX to decide whether to cancel commissioning or to retry with different a network config.

### Platform

core (please add to version below)

### Platform Version(s)

master

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chrisdecenzo**
Fixes #23208

After commissioning a casting video client using ContentAppPlatform::ManageClientAccess
1. The set of clusters on ep1 which are allowed via ACL is not configurable
2. The bindings set on the target is not configurable
- all previous bindings are wiped out
- commissioners may want to read the existing bindings and merge with the current set

This PR allows the ContentAppPlatformFactory to set the cluster list on ep1, and pass a binding list to ManageClientAccess.

The linux and android example tv-apps all read the current binding list and perform a merge rather than replacement of bindings.

### CODE REVIEW

File: examples/tv-app/android/java/AppImpl.cpp [hunk 1]
```diff
@@ -403,6 +403,30 @@ Access::Privilege ContentAppFactoryImpl::GetVendorPrivilege(uint16_t vendorId)
...
+constexpr ClusterId kClusterIdMediaPlayback = 0x0506;
+// constexpr ClusterId kClusterIdMediaInput          = 0x0507;
+constexpr ClusterId kClusterIdLowPower        = 0x0508;
+constexpr ClusterId kClusterIdKeypadInput     = 0x0509;
+constexpr ClusterId kClusterIdContentLauncher = 0x050a;
+constexpr ClusterId kClusterIdAudioOutput     = 0x050b;
+// constexpr ClusterId kClusterIdApplicationLauncher = 0x050c;
+// constexpr ClusterId kClusterIdAccountLogin        = 0x050e;
+
+std::list<ClusterId> ContentAppFactoryImpl::GetAllowedClusterListForStaticEndpoint(EndpointId endpointId, uint16_t vendorId)
```
Comment (amitnj) [inline examples/tv-app/android/java/AppImpl.cpp:420]: Any reason not to pass productId as well.

File: examples/tv-app/android/java/AppImpl.cpp [hunk 2]
```diff
@@ -403,6 +403,30 @@ Access::Privilege ContentAppFactoryImpl::GetVendorPrivilege(uint16_t vendorId)
     return Access::Privilege::kOperate;
 }
 
+constexpr ClusterId kClusterIdDescriptor = 0x001d;
+constexpr ClusterId kClusterIdOnOff      = 0x0006;
+constexpr ClusterId kClusterIdWakeOnLAN  = 0x0503;
+// constexpr ClusterId kClusterIdChannel             = 0x0504;
+// constexpr ClusterId kClusterIdTargetNavigator     = 0x0505;
+constexpr ClusterId kClusterIdMediaPlayback = 0x0506;
```
Comment (amitnj) [inline examples/tv-app/android/java/AppImpl.cpp:411]: Would it make sense to initialize using the IDs from the cluster definitions. So like
constexpr ClusterId kClusterIdMediaPlayback = chip::app::Clusters::MediaPlayback::Id;
Or directly use constants defined in cluster-id.h (#include <app-common/zap-generated/cluster-id.h>)
like ZCL_MEDIA_PLAYBACK_CLUSTER_ID?

What I want to avoid is the IDs being defined separately again. Although it is unlikely they will change.

File: examples/tv-app/android/java/AppImpl.cpp (hunk 1 above)
Comment (chrisdecenzo) [reply examples/tv-app/android/java/AppImpl.cpp]: added productId

**Review by amitnj — APPROVED** [review]
Looks good. One thing that can be done at a later point is to create an object for the callbacks and pass the context to that object instead of caching it in the listener object which we create only one instance of.

**Review by hawk248 — APPROVED** [review]

**Review by lazarkov — APPROVED** [review]
Looks good.
