### PR TITLE
[cirque] Create dedicate docker container for cirque tests.

### LINKED ISSUE #3943: Create dedicated dockerfile for cirque on chip
#### Problem
currently chip x cirque docker image is using 
https://github.com/openweave/cirque/blob/master/cirque/resources/Dockerfile.generic_node#L19
which has dependancy on otbt, sometimes otbr docker image is broken, however, it those docker images don't version.

 #### Proposed Solution
create the dedicated maintainable cirque docker image.

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem
Previously, we are using generic-node-image for running tests, this image relies on other repo and not versioned. This will break our build if other repo fails.

 #### Summary of Changes
Create a dedicate docker container for cirque tests, and after the PR is merged, we need to publish the docker image in this PR so we don't need to build it everytime.

 Fixes #3943

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

File: integrations/docker/images/chip-cirque-device-base/Dockerfile [hunk 1]
```diff
@@ -0,0 +1,44 @@
+FROM ubuntu:focal
+
+ARG OT_BR_POSIX_CHECKOUT=master
```
Comment (andy31415) [inline integrations/docker/images/chip-cirque-device-base/Dockerfile:3]: master checkouts mean that every docker build potentially generates a different version.

How about fixing the version to a SHA, so docker builds are reproducible?

File: integrations/docker/images/chip-cirque-device-base/Dockerfile [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+ENV OT_BR_POSIX_CHECKOUT=${OT_BR_POSIX_CHECKOUT}
+
+RUN mkdir /app
+
+WORKDIR /app
+
+RUN apt-get update \
+  && apt-get install --no-install-recommends -y sudo git ca-certificates psmisc dhcpcd5 wpasupplicant wireless-tools \
+  && ln -fs /usr/share/zoneinfo/UTC /etc/localtime \
+  && git clone https://github.com/openthread/ot-br-posix . \
```
Comment (andy31415) [inline integrations/docker/images/chip-cirque-device-base/Dockerfile:17]: I would separate apt-get from the git clone, so that docker layer caching works a bit better (image builds will be faster as we update what openthread we check out)

File: integrations/docker/images/chip-cirque-device-base/Dockerfile (hunk 1 above)
Comment (erjiaqing) [reply integrations/docker/images/chip-cirque-device-base/Dockerfile:3]: The SHA is set by build.sh.

File: integrations/docker/images/chip-cirque-device-base/build.sh [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+SOURCE=${BASH_SOURCE[0]}
+SOURCE_DIR=$(cd "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)
+REPO_DIR="$SOURCE_DIR/../../../../"
+
+# The image build will clone its own ot-br-posix checkout due to limitations of git submodule.
+# Using the same ot-br-posix version as chip
+OT_BR_POSIX=$REPO_DIR/third_party/ot-br-posix/repo
+OT_BR_POSIX_CHECKOUT=$(cd "$OT_BR_POSIX" && git log -n 1 --format='%H')
+
+docker build -t chip-cirque-device-base -f "$SOURCE_DIR"/Dockerfile --build-arg OT_BR_POSIX_CHECKOUT="$OT_BR_POSIX_CHECKOUT" "$SOURCE_DIR"
```
Comment (erjiaqing) [inline integrations/docker/images/chip-cirque-device-base/build.sh:12]: The ot-br-posix checkout is set here when building with build.sh

File: integrations/docker/images/chip-cirque-device-base/Dockerfile (hunk 2 above)
Comment (erjiaqing) [reply integrations/docker/images/chip-cirque-device-base/Dockerfile:17]: I think we should publish the image to docker hub in the future, in that case, we should focus on the image size instead of build time.

Comment (andy31415) [reply integrations/docker/images/chip-cirque-device-base/Dockerfile:17]: I would have thought image size would be the same in both cases. Is that not so?

File: integrations/docker/images/chip-cirque-device-base/build.sh (hunk 3 above)
Comment (andy31415) [reply integrations/docker/images/chip-cirque-device-base/build.sh:12]: does our third_party repo track master or is it fixed to a specific hash?

I see in .gitmodules:

```
[submodule "ot-br-posix"]
        path = third_party/ot-br-posix/repo
        url = https://github.com/openthread/ot-br-posix.git
        branch = master
```

which tells me that I always get the latest master build in third_party. This leads me to believe that if I do 'docker build' today and 'docker build' two weeks from now on the same CHIP sources I may get a different result. This makes tracking down CI failures a lot harder.

Comment (rwalker-apple) [reply integrations/docker/images/chip-cirque-device-base/build.sh:12]: is something that @mspang might have an answer for.  our trees

**Review by rwalker-apple — APPROVED** [review]

File: integrations/docker/images/chip-cirque-device-base/build.sh (hunk 3 above)
Comment (mspang) [reply integrations/docker/images/chip-cirque-device-base/build.sh:12]: We track a specific version. You want this instead:

`git rev-parse :third_party/cirque/repo`

`branch` instructs the update script about what to update to. Ideally we automate this and run it ~daily.

File: integrations/docker/images/chip-cirque-device-base/Dockerfile [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+                          libavahi-client-dev libboost-dev libboost-filesystem-dev libboost-system-dev libjsoncpp-dev \
+                          libnetfilter-queue-dev \
+  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false cmake cpputest doxygen \
+  && mkdir -p /etc/wpa_supplicant \
+  && echo "ctrl_interface=/run/wpa_supplicant" >> /etc/wpa_supplicant/wpa_supplicant.conf \
+  && echo "update_config=1" >> /etc/wpa_supplicant/wpa_supplicant.conf \
+  && rm -rf /var/lib/apt/lists/*
+
+ENTRYPOINT service dbus start && \
+           sleep 1 && \
```
Comment (mspang) [inline integrations/docker/images/chip-cirque-device-base/Dockerfile:41]: Why sleep 1?

File: integrations/docker/images/chip-cirque-device-base/Dockerfile [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+  && ./script/bootstrap \
+  && ./script/setup \
+  && chmod 644 /etc/bind/named.conf.options \
+  && mv ./script /tmp \
+  && mv ./etc /tmp \
+  && find . -delete \
+  && rm -rf /usr/include \
+  && mv /tmp/script . \
+  && mv /tmp/etc . \
+  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false git ca-certificates \
```
Comment (mspang) [inline integrations/docker/images/chip-cirque-device-base/Dockerfile:29]: I'd suggest building in a throwaway container instead of purging. There's no need to come up with a list of what to remove in that case.

File: integrations/docker/images/chip-cirque-device-base/Dockerfile (hunk 2 above)
Comment (yunhanw-google) [reply integrations/docker/images/chip-cirque-device-base/Dockerfile:17]: I think we should use https://github.com/project-chip/connectedhomeip/tree/master/third_party/ot-br-posix so that we can use the commit as third_party has

File: scripts/tests/cirque_tests.sh [hunk 6]
```diff
@@ -72,6 +72,7 @@ function cirquetest_bootstrap() {
     cd "$REPO_DIR"/third_party/cirque/repo
     pip3 install pycodestyle==2.5.0 wheel
     make NO_GRPC=1 install -j
+    "$REPO_DIR"/integrations/docker/images/chip-cirque-device-base/build.sh
     ./dependency_modules.sh
```
Comment (yunhanw-google) [inline scripts/tests/cirque_tests.sh:76]: we need to run dedicated dependency_moduels.sh in chip instead of using reference one from cirque.

File: integrations/docker/images/chip-cirque-device-base/Dockerfile (hunk 5 above)
Comment (erjiaqing) [reply integrations/docker/images/chip-cirque-device-base/Dockerfile:29]: I reviewed the build procedure and needs some time to figure out the otbr-posix build procedure and which package is required if we will using a throwaway container. So I will add a comment and left for follow up.

File: scripts/tests/cirque_tests.sh (hunk 6 above)
Comment (yunhanw-google) [reply scripts/tests/cirque_tests.sh]: per offline chat, song will do it in another pr via using commit id from openthread submodule

File: integrations/docker/images/chip-cirque-device-base/Dockerfile (hunk 4 above)
Comment (yunhanw-google) [reply integrations/docker/images/chip-cirque-device-base/Dockerfile]: i. think it has been resolved.

**Review by yunhanw-google — APPROVED** [review]

**Review by mspang — APPROVED** [review]
