### PR TITLE
Complete TC tests for TLS Certificate Management & fix impl

### LINKED ISSUE #40907: Implement remaining TC tests
https://github.com/project-chip/connectedhomeip/pull/40552 implements the main tests which provide the most coverage; need to finish implementing other tests in test plan

is 2.1 implemented anywhere? Is that YAML?

_Originally posted by @cecille in https://github.com/project-chip/connectedhomeip/pull/40552#discussion_r2334795991_

### PR DESCRIPTION
**Pull request by gmarcosb**
#### Summary

Complete TC tests as per https://github.com/CHIP-Specifications/chip-test-plans/pull/5534

Fix implementation to pass all tests

#### Testing

CI

#### Readability checklist

The checklist below will help the reviewer finish PR review in time and keep the
code readable:

-   [x] PR title is
        [descriptive](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html#title-formatting)
-   [x] Apply the
        [_“When in Rome…”_](https://project-chip.github.io/connectedhomeip-doc/style/CODING_STYLE_GUIDE.html)
        rule (coding style)
-   [ ] PR size is short
-   [ ] Try to avoid "squashing" and "force-update" in commit history
-   [ ] CI time didn't increase

See: [Pull Request Guidelines](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html)

### CODE REVIEW

File: examples/all-clusters-app/all-clusters-common/src/tls-certificate-management-instance.cpp [hunk 1]
```diff
@@ -252,7 +253,7 @@ CHIP_ERROR TlsCertificateManagementCommandDelegate::LookupRootCert(EndpointId ma
                                                                    const ByteSpan & certificate,
                                                                    LoadedRootCertificateCallback loadedCallback) const
 {
-    std::array<uint8_t, chip::Crypto::kSHA1_Hash_Length> fingerprintPayload = { 0 };
+    std::array<uint8_t, Crypto::kSHA1_Hash_Length> fingerprintPayload = { 0 };
     MutableByteSpan calculatedFingerprint(fingerprintPayload);
     ReturnErrorOnFailure(Hash_SHA1(certificate.data(), certificate.size(), fingerprintPayload.data()));
```
Comment (samadDotDev) [inline examples/all-clusters-app/all-clusters-common/src/tls-certificate-management-instance.cpp]: Needs to be SHA256 here too right?

File: examples/all-clusters-app/all-clusters-common/src/tls-certificate-management-instance.cpp [hunk 2]
```diff
@@ -413,13 +420,13 @@ CHIP_ERROR TlsCertificateManagementCommandDelegate::LookupClientCert(EndpointId
                                                                      const ByteSpan & certificate,
                                                                      LoadedClientCertificateCallback loadedCallback) const
 {
-    std::array<uint8_t, chip::Crypto::kSHA1_Hash_Length> fingerprintPayload = { 0 };
+    std::array<uint8_t, Crypto::kSHA1_Hash_Length> fingerprintPayload = { 0 };
     MutableByteSpan calculatedFingerprint(fingerprintPayload);
     ReturnErrorOnFailure(Hash_SHA1(certificate.data(), certificate.size(), fingerprintPayload.data()));
```
Comment (samadDotDev) [inline examples/all-clusters-app/all-clusters-common/src/tls-certificate-management-instance.cpp]: SHA256?

Comment (gmarcosb) [reply examples/all-clusters-app/all-clusters-common/src/tls-certificate-management-instance.cpp]: Thank you! I get why this one wasn't caught, context @ https://github.com/CHIP-Specifications/chip-test-plans/pull/5534#discussion_r2380333857

File: examples/all-clusters-app/all-clusters-common/src/tls-certificate-management-instance.cpp (hunk 1 above)
Comment (gmarcosb) [reply examples/all-clusters-app/all-clusters-common/src/tls-certificate-management-instance.cpp]: Thanks! Strange that this wasn't caught, though.... you'd think one of the test cases would fail. Looking into it

Comment (gmarcosb) [reply examples/all-clusters-app/all-clusters-common/src/tls-certificate-management-instance.cpp]: Looping back, it was failing in the last test run 🤣 2.2 step 7, so we're good

But strangely all tests were passing in my "TC Tests Completed" commit, so now I'm just confused!

File: src/lib/support/CodeUtils.h [hunk 3]
```diff
@@ -275,13 +275,15 @@
  *  @endcode
  *
  *  @param[in]  expr        An expression to be tested.
+ *  @param[in]  ...         Statements to execute before returning. Optional.
  */
-#define ReturnOnFailure(expr)                                                                                                      \
+#define ReturnOnFailure(expr, ...)                                                                                                 \
```
Comment (robszewczyk) [inline src/lib/support/CodeUtils.h:280]: Nice catch!  This brings parallelism to those macros; `ReturnOnFailure` now has the parallel arguments to `VerifyOrReturn`

**Review by robszewczyk — APPROVED** [review]

File: src/lib/support/CodeUtils.h (hunk 3 above)
Comment (gmarcosb) [reply src/lib/support/CodeUtils.h:280]: Thanks! Yeah I went to use it & was like.... woops 😅🤣

**Comment by marktrayer** [comment]
Why are all of the discrete TLS Cert Tests in a single Python Class?  The usual pattern is a class per script that extends MatterBaseTest.  How does this then lend itself to possibly different CI script-args across the tests (maybe not true now, but possible)?  How does this get rendered by the Test Harness?  Does it allow the individual tests to be selected, or are they all executed as a block?

**Comment by gmarcosb** [comment]
This followed the example of `TC_SWTCH.py` & `TCP_Tests`, which do a similar thing - as far as I could tell, most of the logic seems to be around the method names, which include the TC test number in it; it was a little easier to manage sharing of code this way, such as the common setup, instead of splitting it up between files and/or having to setup some shared common base

As for allowing the individual tests to be selected: that's a good question, I don't know the answer; at least for `local.py`, they're executed as a block, because selection is based on the python script name; you're asking for test events I take it? I'm not sure how those are run, but seems like this being python it wouldn't be complicated to select a method name & not run the whole class

**Review by marktrayer — APPROVED** [review]

File: src/app/clusters/tls-certificate-management-server/tls-certificate-management-server.cpp [hunk 4]
```diff
@@ -363,11 +372,22 @@ void TlsCertificateManagementServer::HandleProvisionClientCertificate(HandlerCon
...
                    ctx.mCommandHandler.AddStatus(ctx.mRequestPath, Status::ConstraintError));
+    auto srcIter = req.intermediateCertificates.begin();
+    while (srcIter.Next())
+    {
+        auto & cert = srcIter.GetValue();
+        VerifyOrReturn(cert.size() <= kSpecMaxCertBytes, ctx.mCommandHandler.AddStatus(ctx.mRequestPath, Status::ConstraintError));
+
+        ReturnOnFailure(Crypto::IsCertificateValidAtCurrentTime(cert),
+                        ctx.mCommandHandler.AddStatus(ctx.mRequestPath, Status::DynamicConstraintError));
+    }
```
Comment (bzbarsky-apple) [inline src/app/clusters/tls-certificate-management-server/tls-certificate-management-server.cpp:391]: Where's the TLV validity check for req.intermediateCertificates?  As in, what if one of those list entries fails to decode entirely?  This will silently truncate the list at that point.

Comment (gmarcosb) [reply src/app/clusters/tls-certificate-management-server/tls-certificate-management-server.cpp:391]: Woops, yeah forgot to check for valid tlv decode; will add

Comment (gmarcosb) [reply src/app/clusters/tls-certificate-management-server/tls-certificate-management-server.cpp:391]: Addressed @ https://github.com/project-chip/connectedhomeip/pull/41195 - thanks again for catching this
