### PR TITLE
Fix JNI error in tv-app

### LINKED ISSUE #25330: [BUG] JNI error in example->tv-app->android
### Reproduction steps

1. run the android tv-app(platform-app & content-app) on an android device(1).
2. run the android tv-casting-app on another android device(2).
3. commission the tv-casting-app on the tv-app running on device 1.
4. navigate to "certification test" and click on the "launch" button.

Expected : All the tests should run and print success logs on the client and the corresponding command logs should show up on the server.
Actual : The commands on the endpoint 1 work. But on the first command to endpoint 4(content-app), a JNI error occurs:
"JNI DETECTED ERROR IN APPLICATION: JNI ERROR (app bug): jstring is an invalid local reference: 0x355 (deleted reference at index 26 in a table of size 26)"

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

3b80154

### Platform

android

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by amitnj**
`Fixes #25330`

Change default passcode returned from account login cluster. Move use of JniUtfString in a code block so that ReleaseStringUTFChars does not happen after DeleteLocalRef.

### CODE REVIEW

**Review by chrisdecenzo — APPROVED** [review]

File: examples/tv-app/android/java/ContentAppCommandDelegate.cpp [hunk 1]
```diff
@@ -81,11 +81,13 @@ void ContentAppCommandDelegate::InvokeCommand(CommandHandlerInterface::HandlerCo
             env->ExceptionDescribe();
             env->ExceptionClear();
             FormatResponseData(handlerContext, "{\"value\":{}}");
-            return;
         }
-        JniUtfString respStr(env, resp);
-        ChipLogProgress(Zcl, "ContentAppCommandDelegate::InvokeCommand got response %s", respStr.c_str());
-        FormatResponseData(handlerContext, respStr.c_str());
+        else
```
Comment (andy31415) [inline examples/tv-app/android/java/ContentAppCommandDelegate.cpp:85]: Previous code was not doing DeleteLocalRef in the exception check case, however new  code does. So the change is a bit more than just "place in a codeblock to fix order of releasing things". Is this intended?

File: examples/tv-app/android/java/ContentAppCommandDelegate.cpp [hunk 2]
```diff
@@ -81,11 +81,13 @@ void ContentAppCommandDelegate::InvokeCommand(CommandHandlerInterface::HandlerCo
             env->ExceptionDescribe();
```
Comment (andy31415) [inline examples/tv-app/android/java/ContentAppCommandDelegate.cpp:81]: https://docs.oracle.com/en/java/javase/16/docs/specs/jni/functions.html#exceptiondescribe seems to indicate that "The pending exception is cleared as a side-effect of calling this function" ... do we need to also call ExceptionClear ?

File: examples/tv-app/android/java/ContentAppCommandDelegate.cpp (hunk 1 above)
Comment (amitnj) [reply examples/tv-app/android/java/ContentAppCommandDelegate.cpp:85]: Yes. I did not want to add checks for null. The [DeleteLocalRef](https://docs.oracle.com/javase/10/docs/specs/jni/functions.html#deletelocalref) accepts a null and ignores. So I just made the change to call it irrespective.

**Review by andy31415 — APPROVED** [review]
