### PR TITLE
[Android] Remove Fabric ID negative value check 

### LINKED ISSUE #28696: [BUG] Android matter sdk setFabricId does not accept values which touch twos compliment
### Reproduction steps

Using an example fabric id: `d5f9b903418fda11`, I am unable to set the fabric id on the controller params since it only accepts a "signed" Long as a parameter. This fabric id can be parsed as an unsigned Long but when converting to a Long it becomes a negative value and fails the sdk check:
```
public Builder setFabricId(long fabricId) {
        if (fabricId < 1L) {
            throw new IllegalArgumentException("fabricId must be > 0");
        } else {
            this.fabricId = fabricId;
            return this;
        }
}
```
Repro steps:

1. Try to set a valid fabric id with a value greater than `7FFF_FFFF_FFFF_FFFF` on the controller parameters.

### Bug prevalence

everytime

### GitHub hash of the SDK that was being used

8f66f4215bc0708efc8cc73bda80620e67d8955f

### Platform

android

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by joonhaengHeo**
Fix #28696 

Java long variable range is -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807.
uint64_t variable range is  0 to 18,446,744,073,709,551,615.

It would be best if there was an unsigned type in Java, but since it doesn't exist, you have no choice but to use negative values when using Java in your App.

For this reason, it has been modified to remove negative checks.

### CODE REVIEW

**Comment by yufengwangca** [comment]
our plan is to switch to kotlin to which has corresponding data type for uint64_t

File: src/controller/java/src/chip/devicecontroller/ControllerParams.java [hunk 1]
```diff
@@ -151,9 +151,6 @@ public static class Builder {
     private Builder() {}
 
     public Builder setFabricId(long fabricId) {
-      if (fabricId < 1) {
```
Comment (yufengwangca) [inline src/controller/java/src/chip/devicecontroller/ControllerParams.java:154]: Even long can not express the full range of uint_64, but this check is still valid, right? can fabricId be a negative number?

File: src/controller/java/src/chip/devicecontroller/ControllerParams.java [hunk 2]
```diff
@@ -151,9 +151,6 @@ public static class Builder {
...
-        throw new IllegalArgumentException("fabricId must be > 0");
-      }
       this.fabricId = fabricId;
       return this;
     }
```
Comment (yunhanw-google) [inline src/controller/java/src/chip/devicecontroller/ControllerParams.java:156]: I would prefer creating another function
public Builder setFabricId(BigInteger fabricId) {
  return setFabricId(fabricId. longValue())
}

File: src/controller/java/src/chip/devicecontroller/ControllerParams.java (hunk 1 above)
Comment (joonhaengHeo) [reply src/controller/java/src/chip/devicecontroller/ControllerParams.java:154]: @yufengwangca 
As mentioned above, negative values of long type can be matched from 0x8000000000000000 to 0xFFFFFFFFFFFFFFFF of uint64_t.
In the case of nodeID and fabricID, they are used after being created as ULong type in kotlin and then changed to java long type. (Use toLong()).

e.g., https://github.com/project-chip/connectedhomeip/blob/a40963d7d571c18f4da18205b918e0c1b4e788f5/examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/AddressUpdateFragment.kt#L18

File: src/controller/java/src/chip/devicecontroller/ControllerParams.java (hunk 2 above)
Comment (joonhaengHeo) [reply src/controller/java/src/chip/devicecontroller/ControllerParams.java:156]: @yunhanw-google 
Finally I agree with you. However, since NodeID and FabricID variables are all implemented in long type in the current Java code, shouldn't this code be modified first and then changed overall?

**Comment by joonhaengHeo** [comment]
> our plan is to switch to kotlin to which has corresponding data type for uint64_t

I agree. However, the current issue has been reported, and I have already deleted and used this code due to the same issue.

File: src/controller/java/src/chip/devicecontroller/ControllerParams.java (hunk 2 above)
Comment (yunhanw-google) [reply src/controller/java/src/chip/devicecontroller/ControllerParams.java:156]: Agree. let's remove the restriction first, thanks

**Review by yunhanw-google — APPROVED** [review]

File: src/controller/java/src/chip/devicecontroller/ControllerParams.java (hunk 2 above)
Comment (yunhanw-google) [reply src/controller/java/src/chip/devicecontroller/ControllerParams.java:156]: I think in the follow-up, we just need to setup the convenient setter with BigInteger, so application developer can leverage this setter or implement their conversion code in their side.

Comment (joonhaengHeo) [reply src/controller/java/src/chip/devicecontroller/ControllerParams.java:156]: I understand your comment.

**Review by saurabhst — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]
