### PR TITLE
[Infineon][SVE-2] CYW30739 fix for TC-RR-1.1

### LINKED ISSUE #22546: [Platform][Infineon] CYW30739 failed TC-RR-1.1
### Reproduction steps

```bash
Run TC-RR-1.1
```

### Platform

other

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by hsusid**
#### Problem
Fixes #22546
TC-RR-1.1 failed.

#### Change overview
* Change CHIP_CONFIG_MAX_FABRICS from 5 to 4.
* Optimize KVS key storage size:
  * Only store non-zero bytes of the key to the flash.
  * Decrease the value size field from 4 bytes to 2 bytes.
* Adjust the flash layout for a larger KVS session.
* Change ota-requestor-app to Thread MTD.

#### Testing
1. TC-RR-1.1
1. Build with API audit enabled:
`gn gen out/debug --args="chip_error_logging=true chip_openthread_ftd=false chip_support_enable_storage_api_audit=true"`
API audit passes with the following line:
`ErrM CHIP:ATM: ==== PersistentStorageDelegate API audit: SUCCESS ====`

### CODE REVIEW

**Review by andy31415 — DISMISSED** [review]

**Comment by andy31415** [comment]
Accepted for 1.0: platform fix

File: src/platform/Infineon/CYW30739/CHIPPlatformConfig.h [hunk 1]
```diff
@@ -23,7 +23,7 @@
 
 #pragma once
 
-#define CHIP_CONFIG_MAX_FABRICS 5
+#define CHIP_CONFIG_MAX_FABRICS 4
```
Comment (tcarmelveilleux) [inline src/platform/Infineon/CYW30739/CHIPPlatformConfig.h:26]: Spec minimum to support is 5. You cannot pass cert with 4.

File: src/platform/Infineon/CYW30739/KeyValueStoreManagerImpl.cpp [hunk 2]
```diff
@@ -171,25 +171,27 @@ CHIP_ERROR KeyValueStoreManagerImpl::EraseAll(void)
...
 }
 
-KeyValueStoreManagerImpl::KeyStorage::KeyStorage(const char * key, size_t keyLength) : mValueSize(0)
+KeyValueStoreManagerImpl::KeyStorage::KeyStorage(const char * key) : mValueSize(0)
 {
     memset(mKey, 0, sizeof(mKey));
-    memcpy(mKey, key, keyLength);
+
+    if (key != NULL)
+        strncpy(mKey, key, sizeof(mKey));
```
Comment (tcarmelveilleux) [inline src/platform/Infineon/CYW30739/KeyValueStoreManagerImpl.cpp:179]: This does not guarantee null termination if key `size ==  kKeyLengthMax`. Could this break for you?

File: examples/ota-requestor-app/infineon/cyw30739/args.gni [hunk 3]
```diff
@@ -17,6 +17,6 @@ import("${chip_root}/src/platform/Infineon/CYW30739/args.gni")
 
 cyw30739_sdk_target = get_label_info(":sdk", "label_no_toolchain")
 
-chip_openthread_ftd = true
+chip_openthread_ftd = false
```
Comment (tcarmelveilleux) [inline examples/ota-requestor-app/infineon/cyw30739/args.gni:20]: Curious why by default you are moving from FTD to MTD?

File: src/platform/Infineon/CYW30739/KeyValueStoreManagerImpl.cpp (hunk 2 above)
Comment (hsusid) [reply src/platform/Infineon/CYW30739/KeyValueStoreManagerImpl.cpp:179]: No, we use `strncmp(mKey, key, sizeof(mKey))` to compare the key.
Also, this change can pass the storage API audit, so I think it works well.

File: src/platform/Infineon/CYW30739/CHIPPlatformConfig.h (hunk 1 above)
Comment (hsusid) [reply src/platform/Infineon/CYW30739/CHIPPlatformConfig.h]: I changed it back to 5.

[the remark this answers is not in the document]
Comment (hsusid) [reply src/platform/Infineon/CYW30739/CHIPPlatformConfig.h]: I changed it back to 5.

File: examples/ota-requestor-app/infineon/cyw30739/args.gni (hunk 3 above)
Comment (hsusid) [reply examples/ota-requestor-app/infineon/cyw30739/args.gni:20]: Because the ota-requestor-app won't build unless changing it to MTD.
To support 5 fabrics, our platform needs an additional 16k flash space for the KVS.
But there is no space left in the ota-requestor-app, the only way I can do is to change it to MTD to reduce its code size.

**Review by woody-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by hsusid** [comment]
rebase
