### PR TITLE
Fix CommissioneeDeviceProxy state

### LINKED ISSUE #13431: After EstablishPASEConnection, Commission hangs since CommissioneeDeviceProxy is not in ConnectionState::SecureConnected
#### Problem

When using the `EstablishPASEConnection` API in `CHIPDeviceController` followed by the `Commission` API, commissioning gets stuck, since the `CommissioneeDeviceProxy` never transitions to the connected state. Since the PASE session was successfully established, commissioning should move forward. The hang is encountered in `CHIPDeviceController.cpp`:

```
if (device->IsSecureConnected())
{
    mAutoCommissioner.StartCommissioning(device);
}
else
{
    mRunCommissioningAfterConnection = true;
}
```

As it reaches the else case waiting for a subsequent connection, which never comes (as the connection has already completed).

### PR DESCRIPTION
**Pull request by cecille**
#### Problem
The pairing call was moved to external so the commissionee
device proxy never gets set to connected. LoadSecureSessionParameters
takes care of setting up the pairing in the session manager anyway, so it makes sense to call through the DeviceProxy.
Fixes #13431 

#### Change overview
Added a new function that gets called when the pairing is complete
to set the state and setup the pairing in the session manager.

#### Testing
paseonly then commission in chip-device-ctrl

### CODE REVIEW

File: src/controller/CommissioneeDeviceProxy.cpp [hunk 1]
```diff
@@ -132,6 +132,13 @@ CHIP_ERROR CommissioneeDeviceProxy::UpdateDeviceData(const Transport::PeerAddres
     return CHIP_NO_ERROR;
 }
 
+CHIP_ERROR CommissioneeDeviceProxy::SetConnected()
+{
+    mState = ConnectionState::SecureConnected;
+    bool didLoad;
+    return LoadSecureSessionParametersIfNeeded(didLoad);
```
Comment (tcarmelveilleux) [inline src/controller/CommissioneeDeviceProxy.cpp:139]: Any reason why we ignore the value? If we ignore it, perhaps rename to `didLoadPlaceholder` ?

File: src/controller/CommissioneeDeviceProxy.h [hunk 2]
```diff
@@ -196,6 +196,14 @@ class CommissioneeDeviceProxy : public DeviceProxy, public SessionReleaseDelegat
 
     void SetActive(bool active) { mActive = active; }
 
+    /**
+     * @brief
+     * Should be called when the pairing completes.
```
Comment (tcarmelveilleux) [inline src/controller/CommissioneeDeviceProxy.h:201]: Called by whom? If it's called externally (e.g. no by `onSessionEstablished`), maybe mention it has to be called in a safe context relative to the CHIP stack.

Also suggest saying that the return values map to `LoadSecureSessionParametersIfNeeded`.

File: src/controller/CommissioneeDeviceProxy.cpp [hunk 3]
```diff
@@ -132,6 +132,13 @@ CHIP_ERROR CommissioneeDeviceProxy::UpdateDeviceData(const Transport::PeerAddres
     return CHIP_NO_ERROR;
 }
 
+CHIP_ERROR CommissioneeDeviceProxy::SetConnected()
+{
+    mState = ConnectionState::SecureConnected;
```
Comment (tcarmelveilleux) [inline src/controller/CommissioneeDeviceProxy.cpp:137]: Is it an CHIP_ERROR_INVALID_STATE if it is already set to SecureConnected or it is otherwise not the correct initial state?

**Review by tcarmelveilleux — APPROVED** [review]

**Review by mrjerryjohns — APPROVED** [review]

File: src/controller/CommissioneeDeviceProxy.cpp (hunk 1 above)
Comment (andy31415) [reply src/controller/CommissioneeDeviceProxy.cpp:139]: `_` is sometimes used for unused values (like `_didLoad`) if you find that shorter. 
Would not block the PR on this though - it seems reasonably readable that when becoming connection, we ensure we have parameters but do not care if they were loaded or already available. It is a side-effect of having an 'if' in the method name.

**Review by andy31415 — APPROVED** [review]

File: src/controller/CommissioneeDeviceProxy.cpp (hunk 3 above)
Comment (andy31415) [reply src/controller/CommissioneeDeviceProxy.cpp:137]: Also wondering - what if the loading of parameters fails - is it still ok for mState to have been changed to Connected?
or should we have this set only if parameter load works.

File: src/controller/CommissioneeDeviceProxy.h (hunk 2 above)
Comment (andy31415) [reply src/controller/CommissioneeDeviceProxy.h:201]: Is that not an implementation detail? Maybe we should remove the "should be called" and just state what it does.

Comment (cecille) [reply src/controller/CommissioneeDeviceProxy.h]: Changed to indicate what it does.

File: src/controller/CommissioneeDeviceProxy.cpp (hunk 3 above)
Comment (cecille) [reply src/controller/CommissioneeDeviceProxy.cpp]: added checks for current state and return of the load call.

File: src/controller/CommissioneeDeviceProxy.cpp (hunk 1 above)
Comment (cecille) [reply src/controller/CommissioneeDeviceProxy.cpp]: changed to _didLoad

**Comment by andy31415** [comment]
fast track: small delta, created by domain owner

**Review by bzbarsky-apple — APPROVED** [review]
