### PR TITLE
Fix the issue of unreleased JNI references.

### LINKED ISSUE #23648: [BUG] Memory leak in android because ReleaseStringUTFChars is not called after GetStringUTFChars
### Reproduction steps

```bash
1. Run the tv-app android platform-app and content-app on an android emulator
2. Run the tv-casting-app linux/android and commission it to the tv
3. Make several calls to read attributes.
After a point the platform-app crashes because the process is holding on the JNI references.
```

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

406bdfe

### Platform

android

### PR DESCRIPTION
**Pull request by amitnj**
Fixes #23648 

There were unreleased JNI references that caused the reference table to overflow and caused the crash of the application. Fixed to release/delete references.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]
I believe we may want to eventually have a RAII class that handles java UTF Chars. Looking at existing code, I am not conviged we call ReleaseStringUTFChars at all. I will create a new issue for this.

File: examples/tv-app/android/java/ContentAppAttributeDelegate.cpp [hunk 1]
```diff
@@ -53,11 +54,15 @@ const char * ContentAppAttributeDelegate::Read(const chip::app::ConcreteReadAttr
         ChipLogError(Zcl, "Java exception in ContentAppAttributeDelegate::Read");
         env->ExceptionDescribe();
         env->ExceptionClear();
+        // returning blank string causes the caller to default to output required by the tests
         return "";
     }
     const char * respStr = env->GetStringUTFChars(resp, 0);
+    std::string retStr(respStr);
```
Comment (andy31415) [inline examples/tv-app/android/java/ContentAppAttributeDelegate.cpp:61]: Lets use `chip::JniUtfString` from src/lib/support/JniTypeWrappers.h (assuming that is visible from the build system) or create an equivalent. RAII is much safer than ensuring that releasestring is called.

**Review by sharadb-amazon — APPROVED** [review]

File: examples/tv-app/android/java/ContentAppAttributeDelegate.cpp (hunk 1 above)
Comment (amitnj) [reply examples/tv-app/android/java/ContentAppAttributeDelegate.cpp:61]: @andy31415 Which field are you proposing to use chip::JniUtfString for?
I dont want to leak jni usages beyond a few classes. So the return type should not be chip::JniUtfString. Can you please clarify.

Comment (amitnj) [reply examples/tv-app/android/java/ContentAppAttributeDelegate.cpp:61]: Resolving this for now. Any changes can be done as part of resolving #23658

**Review by chrisdecenzo — APPROVED** [review]
