### PR TITLE
[PSA] bugfix for potential buffer overflow from AES_CCM Encrypt/Decrypt

### LINKED ISSUE #35155: [BUG] [PSA] Output buffer provided to AES_CCM_decrypt might not be wide enough
### Reproduction steps

When using `CHIPCryptoPALPSA`, I encountered a case where the `plaintext` buffer size is not large enough.
When calling `AES_CCM_decrypt` from `HandleSigma3a`, the input and ouput buffer are the same location:
```
SuccessOrExit(err = AES_CCM_decrypt(msg_R3_Encrypted.Get(), msg_r3_encrypted_len, nullptr, 0,
                                            msg_R3_Encrypted.Get() + msg_r3_encrypted_len, CHIP_CRYPTO_AEAD_MIC_LENGTH_BYTES,
                                            sr3k.KeyHandle(), kTBEData3_Nonce, kTBEDataNonceLength, msg_R3_Encrypted.Get()))
```

In my case, `ciphertext_length` is equal to `0x226`, so when calling `psa_aead_update`, the output size is computed with `PSA_AEAD_UPDATE_OUTPUT_SIZE` macro, which rounds up `0x226` to `0x230`.
This is a problem, because the output buffer is the input buffer, so its size is `0x226`.
Here is the context in `psa_aead_update`:
image

There is a risk of buffer overflow.

### Bug prevalence

whenever the input length is not a multiple of a block size

### GitHub hash of the SDK that was being used

ea01e21b18e54f6fedcd8c47b46c183a54ee3aea

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Alami-Amine**
- Fixes #35155

- before this fix, buffer overflow could occur in encryption and decryption operations when the input buffer's size wasn't a multiple of 16 bytes (AES block size). 
- This happened because PSA's `psa_aead_update` API requires output buffers to be block-aligned. So they were rounded up to multiples of 16 bytes in the API Call.

#### Testing
Tested using `scripts/build/build_examples.py --target nrf-native-posix-64-tests build` which uses Crypto PSA on Linux

### CODE REVIEW

File: src/crypto/CHIPCryptoPALPSA.cpp [hunk 1]
```diff
@@ -94,17 +94,42 @@ CHIP_ERROR AES_CCM_encrypt(const uint8_t * plaintext, size_t plaintext_length, c
...
+        status = psa_aead_update(&operation, plaintext, block_aligned_length, ciphertext, block_aligned_length, &out_length);
         VerifyOrReturnError(status == PSA_SUCCESS, CHIP_ERROR_INTERNAL);
 
         ciphertext += out_length;
+    }
+
+    if (partial_block_length > 0)
+    {
+        uint8_t temp_buffer[kBlockSize];
+        size_t rounded_up_length = PSA_AEAD_UPDATE_OUTPUT_SIZE(PSA_KEY_TYPE_AES, algorithm, partial_block_length);
```
Comment (tcarmelveilleux) [inline src/crypto/CHIPCryptoPALPSA.cpp:116]: - Need to check that `rounded_up_length <= sizeof(temp_buffer)`

File: src/crypto/CHIPCryptoPALPSA.cpp [hunk 2]
```diff
@@ -94,17 +94,42 @@ CHIP_ERROR AES_CCM_encrypt(const uint8_t * plaintext, size_t plaintext_length, c
         ChipLogDetail(Crypto, "AES_CCM_encrypt: Using aad == null path");
     }
 
-    if (plaintext_length != 0)
+    // psa_aead_update() requires the usage of the macro PSA_AEAD_UPDATE_OUTPUT_SIZE to determine the output buffer size.
+    // For AES-CCM, PSA_AEAD_UPDATE_OUTPUT_SIZE will round up the size to the next multiple of the block size (16).
+    // If the ciphertext length is not a multiple of the block size, we will encrypt in two steps, first with the
+    // block_aligned_length, and then with a rounded up partial_block_length, where a temporary buffer will be used for the output.
+    constexpr uint8_t kBlockSize = 16;
```
Comment (tcarmelveilleux) [inline src/crypto/CHIPCryptoPALPSA.cpp:101]: This 16 must rather come from a PSA macro, if one is available, such as a macro/constant from PSA_AEAD_UPDATE_OUTPUT_SIZE

File: src/crypto/CHIPCryptoPALPSA.cpp [hunk 3]
```diff
@@ -147,14 +172,38 @@ CHIP_ERROR AES_CCM_decrypt(const uint8_t * ciphertext, size_t ciphertext_length,
         ChipLogDetail(Crypto, "AES_CCM_decrypt: Using aad == null path");
     }
 
-    if (ciphertext_length != 0)
+    // psa_aead_update() requires the usage of the macro PSA_AEAD_UPDATE_OUTPUT_SIZE to determine the output buffer size.
+    // For AES-CCM, PSA_AEAD_UPDATE_OUTPUT_SIZE will round up the size to the next multiple of the block size (16).
+    // If the ciphertext length is not a multiple of the block size, we will decrypt in two steps, first with the
+    // block_aligned_length, and then with a rounded up partial_block_length, where a temporary buffer will be used for the output.
+    constexpr uint8_t kBlockSize = 16;
```
Comment (tcarmelveilleux) [inline src/crypto/CHIPCryptoPALPSA.cpp:179]: Same comments as for encrypt. Please apply same way

File: src/crypto/CHIPCryptoPALPSA.cpp [hunk 4]
```diff
@@ -94,19 +94,53 @@ CHIP_ERROR AES_CCM_encrypt(const uint8_t * plaintext, size_t plaintext_length, c
...
-    if (plaintext_length != 0)
+    // psa_aead_update() requires the usage of the macro PSA_AEAD_UPDATE_OUTPUT_SIZE to determine the output buffer size.
+    // For AES-CCM, PSA_AEAD_UPDATE_OUTPUT_SIZE will round up the size to the next multiple of the block size (16).
+    // If the ciphertext length is not a multiple of the block size, we will encrypt in two steps, first with the
+    // block_aligned_length, and then with a rounded up partial_block_length, where a temporary buffer will be used for the output.
+    constexpr uint8_t kBlockSize = PSA_BLOCK_CIPHER_BLOCK_LENGTH(PSA_KEY_TYPE_AES);
+    size_t block_aligned_length  = (plaintext_length / kBlockSize) * kBlockSize;
+    size_t partial_block_length  = plaintext_length % kBlockSize;
+
+    if (block_aligned_length > 0)
```
Comment (tcarmelveilleux) [inline src/crypto/CHIPCryptoPALPSA.cpp:105]: Approval conditional on new unit tests that cover blocks < block size having been run against PSA.

**Review by tcarmelveilleux — APPROVED** [review]

**Review by axelnxp — APPROVED** [review]
thanks for fixing !

File: src/crypto/CHIPCryptoPALPSA.cpp [hunk 5]
```diff
@@ -94,19 +94,53 @@ CHIP_ERROR AES_CCM_encrypt(const uint8_t * plaintext, size_t plaintext_length, c
         ChipLogDetail(Crypto, "AES_CCM_encrypt: Using aad == null path");
     }
 
-    if (plaintext_length != 0)
+    // psa_aead_update() requires the usage of the macro PSA_AEAD_UPDATE_OUTPUT_SIZE to determine the output buffer size.
+    // For AES-CCM, PSA_AEAD_UPDATE_OUTPUT_SIZE will round up the size to the next multiple of the block size (16).
```
Comment (bzbarsky-apple) [inline src/crypto/CHIPCryptoPALPSA.cpp:98]: Why are we assuming that behavior and depending on implementation details, rather than checking whether PSA_AEAD_UPDATE_OUTPUT_SIZE(plaintext_length) == plaintext_length and if not counting down the length until those _are_ equal?

I guess for the "remaining bytes" bit computing the buffer size would not be constexpr...

At the very least we need to fail out if PSA_AEAD_UPDATE_OUTPUT_SIZE(block_aligned_length) == block_aligned_length, right?

File: src/crypto/CHIPCryptoPALPSA.cpp [hunk 6]
```diff
@@ -94,19 +94,53 @@ CHIP_ERROR AES_CCM_encrypt(const uint8_t * plaintext, size_t plaintext_length, c
...
+        size_t rounded_up_length = PSA_AEAD_UPDATE_OUTPUT_SIZE(PSA_KEY_TYPE_AES, algorithm, partial_block_length);
+
+        VerifyOrReturnError(rounded_up_length <= sizeof(temp_buffer), CHIP_ERROR_BUFFER_TOO_SMALL);
+
+        out_length = 0;
+        status     = psa_aead_update(&operation, plaintext + block_aligned_length, partial_block_length, &temp_buffer[0],
+                                     rounded_up_length, &out_length);
         VerifyOrReturnError(status == PSA_SUCCESS, CHIP_ERROR_INTERNAL);
 
+        memcpy(ciphertext, temp_buffer, partial_block_length);
```
Comment (bzbarsky-apple) [inline src/crypto/CHIPCryptoPALPSA.cpp:125]: Should we sanity-check that partial_block_length == out_length here?

File: src/crypto/CHIPCryptoPALPSA.cpp [hunk 7]
```diff
@@ -94,19 +94,53 @@ CHIP_ERROR AES_CCM_encrypt(const uint8_t * plaintext, size_t plaintext_length, c
...
+
         ciphertext += out_length;
+    }
+
+    if (plaintext_length != 0)
+    {
+        out_length     = 0;
+        tag_out_length = 0;
 
         status = psa_aead_finish(&operation, ciphertext, PSA_AEAD_FINISH_OUTPUT_SIZE(PSA_KEY_TYPE_AES, algorithm), &out_length, tag,
```
Comment (bzbarsky-apple) [inline src/crypto/CHIPCryptoPALPSA.cpp:135]: Does PSA_AEAD_FINISH_OUTPUT_SIZE not have the block-alignment problem?

File: src/crypto/CHIPCryptoPALPSA.cpp [hunk 8]
```diff
@@ -94,19 +94,53 @@ CHIP_ERROR AES_CCM_encrypt(const uint8_t * plaintext, size_t plaintext_length, c
         ChipLogDetail(Crypto, "AES_CCM_encrypt: Using aad == null path");
     }
 
-    if (plaintext_length != 0)
+    // psa_aead_update() requires the usage of the macro PSA_AEAD_UPDATE_OUTPUT_SIZE to determine the output buffer size.
```
Comment (bzbarsky-apple) [inline src/crypto/CHIPCryptoPALPSA.cpp:97]:
```suggestion
    // psa_aead_update() requires use of the macro PSA_AEAD_UPDATE_OUTPUT_SIZE to determine the output buffer size.
```

File: src/crypto/CHIPCryptoPALPSA.cpp [hunk 9]
```diff
@@ -147,20 +181,49 @@ CHIP_ERROR AES_CCM_decrypt(const uint8_t * ciphertext, size_t ciphertext_length,
         ChipLogDetail(Crypto, "AES_CCM_decrypt: Using aad == null path");
     }
 
-    if (ciphertext_length != 0)
+    // psa_aead_update() requires the usage of the macro PSA_AEAD_UPDATE_OUTPUT_SIZE to determine the output buffer size.
```
Comment (bzbarsky-apple) [inline src/crypto/CHIPCryptoPALPSA.cpp:184]:
```suggestion
    // psa_aead_update() requires use of the macro PSA_AEAD_UPDATE_OUTPUT_SIZE to determine the output buffer size.
```

File: src/crypto/CHIPCryptoPALPSA.cpp [hunk 10]
```diff
@@ -147,20 +181,49 @@ CHIP_ERROR AES_CCM_decrypt(const uint8_t * ciphertext, size_t ciphertext_length,
...
+    // For AES-CCM, PSA_AEAD_UPDATE_OUTPUT_SIZE will round up the size to the next multiple of the block size (16).
+    // If the ciphertext length is not a multiple of the block size, we will decrypt in two steps, first with the
+    // block_aligned_length, and then with a rounded up partial_block_length, where a temporary buffer will be used for the output.
+    constexpr uint8_t kBlockSize = PSA_BLOCK_CIPHER_BLOCK_LENGTH(PSA_KEY_TYPE_AES);
+    size_t block_aligned_length  = (ciphertext_length / kBlockSize) * kBlockSize;
```
Comment (bzbarsky-apple) [inline src/crypto/CHIPCryptoPALPSA.cpp:189]: Same comments here as for encrypt.

File: src/crypto/CHIPCryptoPALPSA.cpp [hunk 11]
```diff
@@ -94,19 +94,53 @@ CHIP_ERROR AES_CCM_encrypt(const uint8_t * plaintext, size_t plaintext_length, c
...
+    if (partial_block_length > 0)
     {
-        status = psa_aead_update(&operation, plaintext, plaintext_length, ciphertext,
-                                 PSA_AEAD_UPDATE_OUTPUT_SIZE(PSA_KEY_TYPE_AES, algorithm, plaintext_length), &out_length);
+        uint8_t temp_buffer[kBlockSize];
+        size_t rounded_up_length = PSA_AEAD_UPDATE_OUTPUT_SIZE(PSA_KEY_TYPE_AES, algorithm, partial_block_length);
+
+        VerifyOrReturnError(rounded_up_length <= sizeof(temp_buffer), CHIP_ERROR_BUFFER_TOO_SMALL);
+
+        out_length = 0;
```
[the remark this answers is not in the document]
Comment (Damian-Nordic) [reply src/crypto/CHIPCryptoPALPSA.cpp:120]: discussed f2f that other reviewers requested it.

**Review by Damian-Nordic — APPROVED** [review]

File: src/crypto/CHIPCryptoPALPSA.cpp (hunk 4 above)
Comment (Alami-Amine) [reply src/crypto/CHIPCryptoPALPSA.cpp:105]: Such Tests already exist, more testcases will be added in a future PR.
https://github.com/project-chip/connectedhomeip/blob/dd0ce899dfb6e247d303ec0cfe6cad6965fc056d/src/crypto/tests/AES_CCM_128_test_vectors.h#L49-L59

File: src/crypto/CHIPCryptoPALPSA.cpp (hunk 6 above)
Comment (Alami-Amine) [reply src/crypto/CHIPCryptoPALPSA.cpp:125]: Sure will do

File: src/crypto/CHIPCryptoPALPSA.cpp (hunk 7 above)
Comment (Alami-Amine) [reply src/crypto/CHIPCryptoPALPSA.cpp:135]: for AES-CCM, `psa_aead_finish` will only output the `tag_length` and `tag_out_length`, it should not touch the ciphertext

File: src/crypto/CHIPCryptoPALPSA.cpp (hunk 9 above)
Comment (Alami-Amine) [reply src/crypto/CHIPCryptoPALPSA.cpp:184]: done

File: src/crypto/CHIPCryptoPALPSA.cpp (hunk 5 above)
Comment (Alami-Amine) [reply src/crypto/CHIPCryptoPALPSA.cpp:98]: I agree that it is more future-proof to use your suggestion rather than depending on details of how `PSA_AEAD_UPDATE_OUTPUT_SIZE` works, but I think the current way is more readable, and after all, this is a PSA implementation method for AES-CCM. I will add your suggested sanity check since it will achieve the same objective.

File: src/crypto/CHIPCryptoPALPSA.cpp (hunk 10 above)
Comment (Alami-Amine) [reply src/crypto/CHIPCryptoPALPSA.cpp:194]: done

**Review by bzbarsky-apple — APPROVED** [review]
