### PR TITLE
Respect updated DNS SD broadcast names in TV app

### LINKED ISSUE #25492: [BUG] TV sample app does not receive DNSSD updates
### Reproduction steps

When a device is advertising over dns-sd and the TX bits change (device name) a message is sent out to indicate that the old advertisement should be expired and the new one should be used.

In the current implementation of the casting app, we stop listening to updates after the discoveryDurationSeconds timeout. This causes us to miss messages and Android seems to fall back to the cached value of the DNS advertisement.

We need to change the usage pattern here so that clients stop the discovery manually after it is started and keep it active for the lifetime they need it for.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

6dd52945eb25f8090f19b066605f1c9f6e800da1

### Platform

android

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cliffamzn**
When a device is advertising over dns-sd and the TX bits change (device name) a message is sent out to indicate that the old advertisement should be expired and the new one should be used.

In the current implementation of the casting app, we stop listening to updates after the `discoveryDurationSeconds` timeout. This causes us to miss messages and Android seems to fall back to the cached value of the DNS advertisement.

We need to change the usage pattern here so that clients stop the discovery manually after it is started and keep it active for the lifetime they need it for.

I also updated the test apps to behave a bit nicer with discovered commissioners.

Fixes #25492

### CODE REVIEW

**Review by sharadb-amazon — APPROVED** [review]

File: examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/DiscoveredNodeData.java [hunk 1]
```diff
@@ -216,4 +217,25 @@ public String toString() {
...
+
+  // autogenerated
+  @Override
+  public int hashCode() {
+    int result = Objects.hash(vendorId, productId, commissioningMode, deviceType);
+    result = 31 * result + Arrays.hashCode(rotatingId);
+    return result;
+  }
+
+  // autogenerated
```
Comment (andy31415) [inline examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/DiscoveredNodeData.java:229]: what auto-generates this?

It seems somewhat confusing that hash and equality uses 5 values where as the class itself is a container of 16 elements.

Would it make sense to somehow have a hashable/keyable `getKey` or `getId` or similar that returns a container of the 4 relevant items? Otherwise we should heavily document that these are not really using all data within the object.

**Review by andy31415 — APPROVED** [review]
Checkmark for the purposes of updating a sample app with changes and checkmarks from app owner - I have not deeply checked the logic and without a review for 1 week this probably qualifies for fast track.

Had a comment about oddness of having a hash/equals that only considers partial class data (and I can understand usage in the array adapter ... but it is odd/unexpected that `if (contains) { remove(); } add` is not actually a noop but rather replaces same;fkey data).

leaving up to app maintainer to decide what to do with it, I am giving the checkmark in advance.

File: examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/DiscoveredNodeData.java (hunk 1 above)
Comment (cliffamzn) [reply examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/DiscoveredNodeData.java:229]: This was generated by AndroidStudio - i should have specified that it is auto generated but i stripped out some elements to it. The main reason being i still wanted it to match the "equals" clause even in the cases where those other elements (like display name) didn't match because the point was that it was "effectively equal" - in this case despite the change in elements such as the broadcast name the DiscoveredNode still represented the same object.

**Comment by cliffamzn** [comment]
> Checkmark for the purposes of updating a sample app with changes and checkmarks from app owner - I have not deeply checked the logic and without a review for 1 week this probably qualifies for fast track.
> 
> Had a comment about oddness of having a hash/equals that only considers partial class data (and I can understand usage in the array adapter ... but it is odd/unexpected that `if (contains) { remove(); } add` is not actually a noop but rather replaces same;fkey data).
> 
> leaving up to app maintainer to decide what to do with it, I am giving the checkmark in advance.

Thanks! - To clarify the behavior, it does the contains to check if it is "effectively" equal, but in actual use there are some elements that might change on a new broadcast update (such as the broadcast name), and in those cases i still want the button updated.

File: examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/DiscoveredNodeData.java (hunk 1 above)
Comment (andy31415) [reply examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/DiscoveredNodeData.java:229]: But if anything in a struct is different from another struct, they are not 'equal' right?

Put it in another way: in a unit test, if I validate scanner behavior I should be able to rely on equality for testing and this is incomplete. The "auto-generated" comment is misleading then: this was auto-generated and edited on purpose. this needs at least documentation (and if I would be a maintainer of the app I would request a separate class encapsulating only items I actually care about).

File: examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/TvCastingApp.java [hunk 2]
```diff
@@ -129,22 +136,22 @@ public void discoverVideoPlayerCommissioners(
...
+    if (this.discoveryStarted
+        && nsdManager != null
+        && multicastLock != null
+        && nsdDiscoveryListener != null) {
+      Log.d(TAG, "TvCastingApp stopping Video Player commissioner discovery");
+      nsdManager.stopServiceDiscovery(nsdDiscoveryListener);
+      if (multicastLock.isHeld()) {
+        multicastLock.release();
+      }
+      this.discoveryStarted = false;
```
Comment (cliffamzn) [inline examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/TvCastingApp.java:154]:
```suggestion
      this.discoveryStarted = false;
      }
```

File: examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/DiscoveredNodeData.java (hunk 1 above)
Comment (cliffamzn) [reply examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/DiscoveredNodeData.java]: Thats fair, i changed the implementation to remove it from equals and introduce a new `discoveredNodeHasSameSource` method that takes care of the equality check and makes it more obvious the objects are not exactly equal.
