### PR TITLE
[ota-provider-app] fix location parsing and BDX sender

### LINKED ISSUE #9703: Fix QueryImage param length checking
#### Problem
OTA Provider code currently uses `emberAfStringLength()` to check the length of the `location` parameter to `QueryImage`. However, this does not work because ember is representing `CHAR_STRING` as `uint8_t *`.

This causes handling of QueryImage to fail.

https://github.com/project-chip/connectedhomeip/blob/e71f2d73e35ce8a8bf8a7cf231e2f37dd7be9e5c/src/app/clusters/ota-provider/ota-provider.cpp#L171

 #### Proposed Solution
Temporarily remove this check so that QueryImage can be handled by apps like `ota-provider-app`.

### PR DESCRIPTION
**Pull request by holbrookt**
#### Problem
This PR contains necessary changes for completing an OTA BDX transfer with an ota-requestor-app (which will also require changes submitted in another PR).
* file I/O for BDX sending was erroring out on EOF instead of sending the last block
* code that verified `QueryImage` parameters was using `emberAfStringLength()` which is incompatible with CHIP TLV format
* The BDX `ExchangeContext` was closing after every message send
* Fixes #9703 

#### Change overview
* don't consider EOF as an error condition when reading blocks for BDX transfer
* don't keep calling `gcount()` to get the number of bytes read
* add `kExpectResponse` for all BDX messages except StatusReport in order to keep exchange open
* use `strlen()` to parse location string instead of `emberAfStringLength()`
* fix message for printing location string length

#### Testing
* tested again modified `ota-requestor-app` (PR will be submitted soon)

### CODE REVIEW

File: examples/ota-provider-app/ota-provider-common/BdxOtaSender.cpp [hunk 1]
```diff
@@ -29,6 +30,12 @@ using chip::bdx::StatusCode;
 using chip::bdx::TransferControlFlags;
 using chip::bdx::TransferSession;
 
+bool IsStatusReportMessage(const TransferSession::MessageTypeData & msgTypeData)
```
Comment (bzbarsky-apple) [inline examples/ota-provider-app/ota-provider-common/BdxOtaSender.cpp:33]: Might be cleaner to add a typed `HasMessageType` accessor on `MessageTypeData`, similar to the way `PayloadHeader` works.  That would automatically handle figuring out the protocol id from the message id.

File: src/app/clusters/ota-provider/ota-provider.cpp [hunk 2]
```diff
@@ -168,10 +168,12 @@ bool emberAfOtaSoftwareUpdateProviderClusterQueryImageCallback(EndpointId endpoi
     ChipLogDetail(Zcl, "OTA Provider received QueryImage");
 
     // TODO: (#7112) change location size checking once CHAR_STRING is supported
-    const uint8_t locationLen = emberAfStringLength(location);
+    // The following commented code does not work because location is being treated as uint8_t* and this leads to always sending a
```
Comment (bzbarsky-apple) [inline src/app/clusters/ota-provider/ota-provider.cpp:171]: The code is not commented, that I can see....  Unless you mean that this is the comment or something like that?  In which case probably clearer to say "The code using strlen"... or something?

Comment (holbrookt) [reply src/app/clusters/ota-provider/ota-provider.cpp:171]: this was a mistake, I meant to remove this. Thanks for catching it.

File: examples/ota-provider-app/ota-provider-common/BdxOtaSender.cpp (hunk 1 above)
Comment (holbrookt) [reply examples/ota-provider-app/ota-provider-common/BdxOtaSender.cpp]: I like this suggestion. Added

**Review by yufengwangca — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@saurabhst @Damian-Nordic @LuDuda ?

**Review by saurabhst — APPROVED** [review]
