### PR TITLE
[Infineon] Fix for successorexit return error for PSoC6 platform

### LINKED ISSUE #25537: Infineon platform code has a bunch of broken SuccessOrExit(CHIP_ERROR_INTERNAL)
`SuccessOrExit(CHIP_ERROR_INTERNAL)` will go to exit, but then return whatever that returns.  In most of these functions that's `err`, which is set to `CHIP_NO_ERROR` in this case.

This can lead to returns of CHIP_NO_ERROR while outparams are set to garbage.

@ifyall

### PR DESCRIPTION
**Pull request by praveenCY**
Fixes https://github.com/project-chip/connectedhomeip/issues/25537

Tested Infineon PSoC6 Compile

### CODE REVIEW

File: src/platform/Infineon/PSOC6/ConnectivityManagerImpl.cpp [hunk 1]
```diff
@@ -176,12 +176,13 @@ CHIP_ERROR ConnectivityManagerImpl::_GetAndLogWiFiStatsCounters(void)
...
     cy_wcm_associated_ap_info_t ap_info;
     cy_rslt_t result = CY_RSLT_SUCCESS;
+    CHIP_ERROR err   = CHIP_NO_ERROR;
 
     result = cy_wcm_get_associated_ap_info(&ap_info);
     if (result != CY_RSLT_SUCCESS)
     {
         ChipLogError(DeviceLayer, "cy_wcm_get_associated_ap_info failed: %d", (int) result);
-        SuccessOrExit(CHIP_ERROR_INTERNAL);
+        SuccessOrExit(err = CHIP_ERROR_INTERNAL);
```
Comment (bzbarsky-apple) [inline src/platform/Infineon/PSOC6/ConnectivityManagerImpl.cpp:185]: We should add a lint for `SuccessOrExit(CHIP_ERROR` to `.github/workflows/lint.yml`.  Followup is fine for that.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

File: src/platform/Infineon/PSOC6/ConnectivityManagerImpl.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/platform/Infineon/PSOC6/ConnectivityManagerImpl.cpp:185]: Created https://github.com/project-chip/connectedhomeip/pull/26057
