### PR TITLE
[Android] Fix to avoid NewStringUTF crash

### LINKED ISSUE #25910: [BUG][Android][Plugfest #4] Crash CHIPTool when read invalid String attribute
### Reproduction steps

1. Commissioning device using Android CHIPTool
2. Read attributes string type.
3. Crash when parsing String hex.

08-14 09:30:05.986 F 15822    15927    e.chip.chiptoo:                                                                     java_vm_ext.cc:577] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0 
08-14 09:30:05.986 F 15822    15927    e.chip.chiptoo:                                                                     java_vm_ext.cc:577]     string: tfm_bas� 
08-14 09:30:05.986 F 15822    15927    e.chip.chiptoo:                                                                     java_vm_ext.cc:577]     input: 0x74 0x66 0x6d 0x5f 0x62 0x61 0x73 0xd5 
08-14 09:30:05.986 F 15822    15927    e.chip.chiptoo:                                                                     java_vm_ext.cc:577]     in call to NewStringUTF 

### Bug prevalence

read attribute with specific device.

### GitHub hash of the SDK that was being used

ce0ddc035143117d9193eb5b59647a7dd957aea0

### Platform

android

### Platform Version(s)

master

### Anything else?

During testing in Plugfest 4, while analyzing the issue, the same crash occurs in Android CHIPTool, so an issue is registered.

### PR DESCRIPTION
**Pull request by joonhaengHeo**
Fix #25910 

Crash is occurring when a value is passed instead of an ASCII value.
(Tested values are "0x74, 0x66, 0x6d, 0x5f, 0x62, 0x61, 0x73, 0xd5"). - It is occurring at 0xd5.
To solve this problem, I would like to prevent Crash by changing the method of generating java string.

1. Make new API in JniReference for changing jstring.
2. Using this API in ZAP files.

### CODE REVIEW

File: src/lib/support/JniReferences.h [hunk 1]
```diff
@@ -160,6 +160,11 @@ class JniReferences
         return CreateBoxedObject(boxedTypeClsName, constructorSignature, chip::to_underlying(value), outObj);
     }
 
+    /**
+     * Fix to avoid NewStringUTF crash
```
Comment (andy31415) [inline src/lib/support/JniReferences.h:164]: This comment does not help understand the code. This needs actual documentation.

**Review by andy31415 — CHANGES_REQUESTED** [review]
Please update the summary: why was it crashing, what was changed to fix the crash.

Also update the doccomment in JniReferences.h to explain what the method does (maybe contrasting with NewUTFString)

File: src/controller/java/templates/partials/decode_value.zapt [hunk 2]
```diff
@@ -60,7 +60,7 @@ if ({{source}}.IsNull()) {
         env->SetByteArrayRegion({{target}}ByteArray, 0, static_cast<jsize>({{source}}.size()), reinterpret_cast<const jbyte *>({{source}}.data()));
         {{target}} = {{target}}ByteArray;
       {{else if (isCharString type)}}
-        {{target}} = env->NewStringUTF(std::string({{source}}.data(), {{source}}.size()).c_str());
+        {{target}} = chip::JniReferences::GetInstance().CharToJniString(std::string({{source}}.data(), {{source}}.size()).c_str());
```
Comment (andy31415) [inline src/controller/java/templates/partials/decode_value.zapt:63]: In theory UTF8 should be valid for string, because this is not octet string. Switching this from UTF8 does not seem correct.

Comment (andy31415) [reply src/controller/java/templates/partials/decode_value.zapt:63]:
```
7.18.2.28. Character String
The character string data type is derived from an octet string. The octets SHALL be characters with UTF-8 encoding. An instance of this data type SHALL NOT contain truncated code points.
```

We should report an exception (can we add tests here for fast return?) but not accept JNI strings that are not UTF8.

Comment (joonhaengHeo) [reply src/controller/java/templates/partials/decode_value.zapt:63]: I totally agree with you that it should be valid for a string. However, it is also necessary that a crash should not occur when there is a value that is not vailed. By any chance, is there a better solution? The solution I suggested is handled by UTF-8, but it's a way to change it in a different way so that it doesn't cause a crash.

File: src/lib/support/JniReferences.h (hunk 1 above)
Comment (joonhaengHeo) [reply src/lib/support/JniReferences.h]: Comment edited.
By the way, according to your opinion below, it is more appropriate to handle Error. I will write again after the conversation below is resolved.

File: src/controller/java/templates/partials/decode_value.zapt (hunk 2 above)
Comment (bzbarsky-apple) [reply src/controller/java/templates/partials/decode_value.zapt:63]: Note that `NewStringUTF` does not actually accept standard UTF-8.  If you have a standard UTF-8 encoding of an emoji and you try to `NewStringUTF` with it, I expect it fails.

Comment (andy31415) [reply src/controller/java/templates/partials/decode_value.zapt:63]: Is it the case that NewStringUTF does not accept valid strings (if so that is a bug and we should fix it) or that this is indeed an invalid string (this is my current understanding).

For an invalid string, I expect java to throw an exception on decoding.

File: src/lib/support/JniReferences.cpp [hunk 3]
```diff
@@ -388,4 +388,23 @@ CHIP_ERROR JniReferences::GetObjectField(jobject objectToRead, const char * name
...
+{
+    JNIEnv * env        = GetEnvForCurrentThread();
+    jobject jbyteBuffer = env->NewDirectByteBuffer((void *) value, static_cast<jlong>(strlen(value)));
+
+    jclass charSetClass = env->FindClass("java/nio/charset/Charset");
+    jmethodID charsetForNameMethod =
+        env->GetStaticMethodID(charSetClass, "forName", "(Ljava/lang/String;)Ljava/nio/charset/Charset;");
+    jobject charsetObject = env->CallStaticObjectMethod(charSetClass, charsetForNameMethod, env->NewStringUTF("UTF-8"));
+
+    jmethodID charSetDecodeMethod = env->GetMethodID(charSetClass, "decode", "(Ljava/nio/ByteBuffer;)Ljava/nio/CharBuffer;");
```
Comment (andy31415) [inline src/lib/support/JniReferences.cpp:401]: `decode` says `This method always replaces malformed-input and unmappable-character sequences with this charset's default replacement byte array` ... is this really acceptable instead of failing decode?

File: src/lib/support/JniReferences.h [hunk 4]
```diff
@@ -160,6 +160,12 @@ class JniReferences
         return CreateBoxedObject(boxedTypeClsName, constructorSignature, chip::to_underlying(value), outObj);
     }
 
+    /**
+     * Use instead of 'NewStringUTF' function
+     * Creates a java string type based on char array.
```
Comment (andy31415) [inline src/lib/support/JniReferences.h:165]: Please explain why to use instead of NewStringUTF: what are the differences? 

As far as I can tell, this is using Charset(UTF-8)::decode which is lenient to malformed input and replaces it with the charset default replacement byte array, while NewStringUTF is strict.

Based on this description, we can be string on char strings.

File: src/controller/java/templates/partials/decode_value.zapt (hunk 2 above)
Comment (andy31415) [reply src/controller/java/templates/partials/decode_value.zapt:63]: My expectation:
   - UTF8 validation should be ok. We should replace NewStringUTF with something else if we prove a valid emoji (in UTF-8 encoding) fails to parse. I don't think this should be the case, however java docs mentions `Constructs a new java.lang.String object from an array of characters in modified UTF-8 encoding.` ... what is `modified` ??
    - we should not crash, however throwing an exception should be acceptable. Maybe we need to check `ExceptionOcurred` in our decoders.

@bzbarsky-apple do you have a concrete example with the emoji?

Comment (andy31415) [reply src/controller/java/templates/partials/decode_value.zapt:63]: For what its worth, the string described in this issue does look like invalid UTF-8:

```python
>>> binascii.a2b_hex('74666d5f626173d5').decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 7: unexpected end of data
```

Comment (andy31415) [reply src/controller/java/templates/partials/decode_value.zapt:63]: Maybe it is truncated because d5 is a 2-byte continuation start, so something like `74666d5f626173d5a0` would be valid utf8.

Comment (andy31415) [reply src/controller/java/templates/partials/decode_value.zapt:63]: Regarding "modified" the docs seem to say things that should not affect us:
  - nulls are encoded as 2-bytes (we should not care ...we should not embed nulls)
  - only support 1,2 or 3 byte encoding. I do not believe we have a reason to use 4-byte utf8 in chip

File: src/lib/support/JniReferences.cpp (hunk 3 above)
Comment (joonhaengHeo) [reply src/lib/support/JniReferences.cpp:401]: This code is simply designed to prevent crashes.
It seems that the current discussion is discussing that it is correct to return an error in the case of an invalid string byte.

In this case, it is necessary to add a code that checks whether it can be changed to utf-8 before decoding and transmits it as an error.

File: src/lib/support/JniReferences.h (hunk 4 above)
Comment (joonhaengHeo) [reply src/lib/support/JniReferences.h:165]: Yes, I understand what you mean. This part will be corrected when the final fix point is decided.

Comment (joonhaengHeo) [reply src/lib/support/JniReferences.h:168]: I added some comments.

File: src/controller/java/templates/partials/decode_value.zapt (hunk 2 above)
Comment (joonhaengHeo) [reply src/controller/java/templates/partials/decode_value.zapt]: @andy31415 @bzbarsky-apple 
It has been modified to return as an error when it is not decoded as `UTF-8`.
(In a file created with zap, it will be returned as null.)

File: src/lib/support/JniReferences.cpp (hunk 3 above)
Comment (joonhaengHeo) [reply src/lib/support/JniReferences.cpp]: It has been modified to return as an error when it is not decoded as `UTF-8`.
(In a file created with zap, it will be returned as null.)

File: src/lib/support/JniReferences.h (hunk 4 above)
Comment (joonhaengHeo) [reply src/lib/support/JniReferences.h:168]: comment has been added.

File: src/lib/support/JniReferences.cpp (hunk 3 above)
Comment (joonhaengHeo) [reply src/lib/support/JniReferences.cpp]: In addition, in the decode method of the CharsetDecoder class, an exception occurs when decoding cannot be performed.
Refer https://docs.oracle.com/javase/7/docs/api/java/nio/charset/CharsetDecoder.html#decode(java.nio.ByteBuffer)

File: src/controller/java/templates/partials/decode_value.zapt [hunk 5]
```diff
@@ -60,7 +60,7 @@ if ({{source}}.IsNull()) {
         env->SetByteArrayRegion({{target}}ByteArray, 0, static_cast<jsize>({{source}}.size()), reinterpret_cast<const jbyte *>({{source}}.data()));
         {{target}} = {{target}}ByteArray;
       {{else if (isCharString type)}}
-        {{target}} = env->NewStringUTF(std::string({{source}}.data(), {{source}}.size()).c_str());
+        chip::JniReferences::GetInstance().CharToStringUTF(std::string({{source}}.data(), {{source}}.size()).c_str(), {{target}});
```
Comment (bzbarsky-apple) [inline src/controller/java/templates/partials/decode_value.zapt:63]: Shouldn't this just fail if the data is not valid UTF-8, instead of silently using a different value?

(Related: the code above this in the `isArray` does not fail on decoding errors, instead silently ignoring everything in the list after the decoding error....)

File: src/lib/support/JniReferences.cpp [hunk 6]
```diff
@@ -388,4 +388,31 @@ CHIP_ERROR JniReferences::GetObjectField(jobject objectToRead, const char * name
     return err;
 }
 
+CHIP_ERROR JniReferences::CharToStringUTF(const char * value, jobject &outStr)
```
Comment (bzbarsky-apple) [inline src/lib/support/JniReferences.cpp:391]: Why not just pass in the CharSpan instead of doing the copy into an std::string but then just passing the char *?

File: src/controller/java/templates/partials/decode_value.zapt (hunk 5 above)
Comment (joonhaengHeo) [reply src/controller/java/templates/partials/decode_value.zapt:63]: In the case of String, if UTF-8 decoding fails, nullptr is returned. Is it correct to modify it so that it can return even the errorCode?

Comment (joonhaengHeo) [reply src/controller/java/templates/partials/decode_value.zapt:63]: e.g : 
CHIPAttributeTLVValueDecoder-src.zapt
`{{>decode_value target="value" source="cppValue" cluster=(asUpperCamelCase parent.name) depth=0 errorCode="*aError = " earlyReturn="nullptr"}}`

decode_value.zapt
`{{errorCode}} chip::JniReferences::GetInstance().CharToStringUTF(std::string({{source}}.data(), {{source}}.size()).c_str(), {{target}});`

Comment (bzbarsky-apple) [reply src/controller/java/templates/partials/decode_value.zapt:63]: Something like that would make sense, yes, if that generates the right code.  Followup is fine for doing that as needed...

File: src/lib/support/JniReferences.cpp (hunk 6 above)
Comment (joonhaengHeo) [reply src/lib/support/JniReferences.cpp]: I modified. Thanks.

File: src/controller/java/templates/partials/decode_value.zapt (hunk 5 above)
Comment (joonhaengHeo) [reply src/controller/java/templates/partials/decode_value.zapt]: I modified. Thanks. Please review it.

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by joonhaengHeo** [comment]
@andy31415 
Please review my PR.

File: src/controller/java/zap-generated/CHIPReadCallbacks.cpp [hunk 7]
```diff
@@ -35184,7 +35173,7 @@ void CHIPUnitTestingNullableCharStringAttributeCallback::CallbackFn(void * conte
     }
     else
     {
-        javaValue = env->NewStringUTF(std::string(value.Value().data(), value.Value().size()).c_str());
+        chip::JniReferences::GetInstance().CharToStringUTF(value.Value(), javaValue);
```
Comment (andy31415) [inline src/controller/java/zap-generated/CHIPReadCallbacks.cpp:35176]: Should use the return error.

File: src/controller/java/zap-generated/CHIPReadCallbacks.cpp [hunk 8]
```diff
@@ -4836,7 +4836,7 @@ void CHIPActionsActionListAttributeCallback::CallbackFn(
                                                                        newElement_0_actionIDCtorSignature.c_str(), entry_0.actionID,
                                                                        newElement_0_actionID);
         jobject newElement_0_name;
-        newElement_0_name = env->NewStringUTF(std::string(entry_0.name.data(), entry_0.name.size()).c_str());
+        chip::JniReferences::GetInstance().CharToStringUTF(entry_0.name, newElement_0_name);
```
Comment (andy31415) [inline src/controller/java/zap-generated/CHIPReadCallbacks.cpp:4839]: return value should be used (empty? null?)

File: src/controller/java/zap-generated/CHIPReadCallbacks.cpp (hunk 7 above)
Comment (joonhaengHeo) [reply src/controller/java/zap-generated/CHIPReadCallbacks.cpp]: When doing TLV Decode, I think it is best to implement it in the same way as returning to null if an error occurs.
We added setting null to the outString variable in CharToStringUTF and wrapped it with LogErrorOnFailure to add log when it is an error.
(LogErrorOnFailure is Marco that only outputs Log when Error.)

File: src/controller/java/zap-generated/CHIPInvokeCallbacks.cpp [hunk 9]
```diff
@@ -157,7 +157,7 @@ void CHIPGroupsClusterViewGroupResponseCallback::CallbackFn(
     chip::JniReferences::GetInstance().CreateBoxedObject<uint16_t>(GroupIDClassName.c_str(), GroupIDCtorSignature.c_str(),
                                                                    dataResponse.groupID, GroupID);
     jobject GroupName;
-    GroupName = env->NewStringUTF(std::string(dataResponse.groupName.data(), dataResponse.groupName.size()).c_str());
+    chip::JniReferences::GetInstance().CharToStringUTF(dataResponse.groupName, GroupName);
```
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/controller/java/zap-generated/CHIPInvokeCallbacks.cpp]: Add to set null in CharToStringUTF function.

File: src/controller/java/zap-generated/CHIPReadCallbacks.cpp (hunk 8 above)
Comment (joonhaengHeo) [reply src/controller/java/zap-generated/CHIPReadCallbacks.cpp:4839]: When doing TLV Decode, I think it is best to implement it in the same way as returning to null if an error occurs.
We added setting null to the outString variable in CharToStringUTF and wrapped it with LogErrorOnFailure to add log when it is an error.
(LogErrorOnFailure is Marco that only outputs Log when Error.)

Comment (joonhaengHeo) [reply src/controller/java/zap-generated/CHIPReadCallbacks.cpp:4839]: The code returned to "*aError" was also restored.
(src/controller/java/zap-generated/CHIPAttributeTLVValueDecoder.cpp, src/controller/java/zap-generated/CHIPEventTLVValueDecoder.cpp)

It doesn't use the "*aError" variable in the function.

**Review by andy31415 — APPROVED** [review]
