### PR TITLE
[Tizen] Use Thread implementation of mDNS functions

### LINKED ISSUE #22549: [Platform] Tizen uses non-Thread mDNS functions when Thread is enabled
### Reproduction steps

```bash
1. Modify chip-tool, so it will use mDNS with Thread
2. Run: `chip-tool pairing code-thread 1 1234 0001`
3. Network version of mDNS is used instead of `chip::DeviceLayer::ThreadStackMgr().DnsBrowse()`
```

### Platform

other

### Platform Version(s)

_No response_

### Type

Platform validated

### (Optional) If manually tested please explain why this is only manually tested

Manually tested. Currently there are no runtime automatic tests for Tizen.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by arkq**
#### Issue Being Resolved
* Fixes #22549

#### Change overview
- call dedicated mDNS functions when using Thread

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

File: src/platform/Tizen/ThreadStackManagerImpl.cpp [hunk 1]
```diff
@@ -586,6 +586,17 @@ CHIP_ERROR ThreadStackManagerImpl::_ClearSrpHost(const char * aHostName)
...
 
+CHIP_ERROR ThreadStackManagerImpl::_DnsBrowse(const char * aServiceName, DnsBrowseCallback aCallback, void * aContext)
+{
+    return CHIP_ERROR_NOT_IMPLEMENTED;
+}
+
+CHIP_ERROR ThreadStackManagerImpl::_DnsResolve(const char * aServiceName, const char * aInstanceName, DnsResolveCallback aCallback,
+                                               void * aContext)
+{
+    return CHIP_ERROR_NOT_IMPLEMENTED;
```
Comment (msandstedt) [inline src/platform/Tizen/ThreadStackManagerImpl.cpp:597]: Am I reading correctly that the DNS functions are now directed here?  If so, is it intentional that we would throw `CHIP_ERROR_NOT_IMPLEMENTED`?  Is this then to allow for future, Thread-specific Tizen work in the sdk, or does this allow for some type of different override behavior in code consuming the Tizen platform?

Comment (Arkq) [reply src/platform/Tizen/ThreadStackManagerImpl.cpp:597]: This is a shim for now. Proper Thread DNS implementations for Tizen require changes in Tizen Native API which right now is not available on tizen.org. I thought that such implementation (dummy one) will be better than nothing at all. Right now one will get a proper error message (not implemented) instead of running IP mDNS version of browse and resolve. I will submit for these functions later (remove, browse and resolve; and a fix for register call - right now it does not register TXT records).
