### PR TITLE
Fix BLE advertisement service data format

### LINKED ISSUE #3556: BLE advertisements are inconsistent between spec, commissioner apps, & examples
BLE advertisements are not consistent between iOS, Android, and example apps.

- iOS & ESP32 are serializing discriminator incorrectly
- iOS requires a short length payload (4 bytes for VID/PID omitted)

As of #2954, Android expects the correct format, but that broke discovery of examples still using the wrong format such as ESP32.

https://github.com/project-chip/connectedhomeip/blob/master/src/platform/Darwin/BleConnectionDelegateImpl.mm#L128-L137

https://github.com/project-chip/connectedhomeip/blob/master/src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/bluetooth/BluetoothManager.kt#L54-L57

### PR DESCRIPTION
**Pull request by mspang**
#### Problem

Several components are using an incorrect format for BLE advertisement.

 #### Summary of Changes
 
The correct format is implemented in ChipBLEDeviceIdentificationInfo.
Update the Linux, ESP32, Android, and Darwin ports to support the
correct format during Rendezvous.

Fixes #3556

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

File: src/platform/ESP32/bluedroid/BLEManagerImpl.cpp [hunk 1]
```diff
@@ -655,13 +655,22 @@ CHIP_ERROR BLEManagerImpl::ConfigureAdvertisingData(void)
...
+    err = ConfigurationMgr().GetBLEDeviceIdentificationInfo(deviceIdInfo);
+    if (err != CHIP_NO_ERROR)
+    {
+        ChipLogError(DeviceLayer, "GetBLEDeviceIdentificationInfo(): ", ErrorStr(err));
+        ExitNow();
+    }
+
+    VerifyOrExit(index + sizeof(deviceIdInfo) <= sizeof(advData), err = BLE_ERROR_OUTBOUND_MESSAGE_TOO_BIG);
+    memcpy(&advData[index], &deviceIdInfo, sizeof(deviceIdInfo));
+    index = static_cast<uint8_t>(index + sizeof(deviceIdInfo));
```
Comment (vivien-apple) [inline src/platform/ESP32/bluedroid/BLEManagerImpl.cpp:673]: For the record I have not added VendorId/ProductId on purpose since there was still a debate to include it or not.

Is the debate finally closed ? I've not seen the debate resolution in the spec. At the moment it still says:
```Inclusion of Vendor and Product ID (VID and PID) in advertisements is under debate within the TT.```

Comment (mspang) [reply src/platform/ESP32/bluedroid/BLEManagerImpl.cpp:673]: The implementation should reflect the currently specified payload. It's important converge on a format so that all of the examples can be commissioned.

**Review by gjc13 — APPROVED** [review]

File: src/platform/ESP32/bluedroid/BLEManagerImpl.cpp (hunk 1 above)
Comment (mspang) [reply src/platform/ESP32/bluedroid/BLEManagerImpl.cpp:673]: The answers seems to be that they are in, but optional and should be specified as zero if omitted. The length is fixed.

Comment (smides-nest) [reply src/platform/ESP32/bluedroid/BLEManagerImpl.cpp:673]: > For the record I have not added VendorId/ProductId on purpose since there was still a debate to include it or not.
> 
> Is the debate finally closed ? I've not seen the debate resolution in the spec. At the moment it still says:
> `Inclusion of Vendor and Product ID (VID and PID) in advertisements is under debate within the TT.`

Yes. The debate closed a while back but the spec was written before that decision was reached. There's a PR up for the updated spec [here](https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/326)

Comment (vivien-apple) [reply src/platform/ESP32/bluedroid/BLEManagerImpl.cpp:673]: > The answer seems to be that they are in, but optional and should be specified as zero if omitted. The advertisement length is fixed.

Agreed on `0x0A` instead of `0x06` in this case. And I would be fine if you remove the deprecated case in the Darwin BLE connection code. 

But can we add a build flag in `_GetBLEDeviceIdentificationInfo` that defaults to `false` and that you explicitly need to turn `true` for adding those `productId` and `vendorId` informations to BLE. Otherwise the default will be to include them all the time since `productId` and `vendorId`, even if you don't intend to use them for BLE advertisement, will likely be part of the product by default.

Comment (mspang) [reply src/platform/ESP32/bluedroid/BLEManagerImpl.cpp:673]: > > The answer seems to be that they are in, but optional and should be specified as zero if omitted. The advertisement length is fixed.
> 
> Agreed on `0x0A` instead of `0x06` in this case. And I would be fine if you remove the deprecated case in the Darwin BLE connection code.
> 
> But can we add a build flag in `_GetBLEDeviceIdentificationInfo` that defaults to `false` and that you explicitly need to turn `true` for adding those `productId` and `vendorId` informations to BLE. Otherwise the default will be to include them all the time since `productId` and `vendorId`, even if you don't intend to use them for BLE advertisement, will likely be part of the product by default.

Having that be configurable seems find.

BTW, a bunch of demos are setting these already. The immediate issue is that various commissioner/commissionee pairs **are not compatible**.

This updated PR is totally fine with zero values. I can set the ESP32 values to zero if you want.

**Review by andy31415 — APPROVED** [review]

**Review by vivien-apple — APPROVED** [review]
> > > The answer seems to be that they are in, but optional and should be specified as zero if omitted. The advertisement length is fixed.
> > 
> > 
> > Agreed on `0x0A` instead of `0x06` in this case. And I would be fine if you remove the deprecated case in the Darwin BLE connection code.
> > But can we add a build flag in `_GetBLEDeviceIdentificationInfo` that defaults to `false` and that you explicitly need to turn `true` for adding those `productId` and `vendorId` informations to BLE. Otherwise the default will be to include them all the time since `productId` and `vendorId`, even if you don't intend to use them for BLE advertisement, will likely be part of the product by default.
> 
> Having that be configurable seems fine.

Mind opening a followup to add a build flag that default to false ? r+ with the followup opened.

> 
> BTW, a bunch of demos are setting these already. The immediate issue is that various commissioner/commissionee pairs **are not compatible**.

I did not realised the nrf*/Zephyr platform already does that :(

**Comment by mspang** [comment]
> > > > The answer seems to be that they are in, but optional and should be specified as zero if omitted. The advertisement length is fixed.
> > > 
> > > 
> > > Agreed on `0x0A` instead of `0x06` in this case. And I would be fine if you remove the deprecated case in the Darwin BLE connection code.
> > > But can we add a build flag in `_GetBLEDeviceIdentificationInfo` that defaults to `false` and that you explicitly need to turn `true` for adding those `productId` and `vendorId` informations to BLE. Otherwise the default will be to include them all the time since `productId` and `vendorId`, even if you don't intend to use them for BLE advertisement, will likely be part of the product by default.
> > 
> > 
> > Having that be configurable seems fine.
> 
> Mind opening a followup to add a build flag that default to false ? r+ with the followup opened.
> 
> > BTW, a bunch of demos are setting these already. The immediate issue is that various commissioner/commissionee pairs **are not compatible**.
> 
> I did not realised the nrf*/Zephyr platform already does that :(

Not sure if about defaulting to false. Currently 3 platforms include vid/pid (linux, efr32, nordic) and 1 does not (esp32).

**Review by vidhis88 — APPROVED** [review]

**Review by jelderton — APPROVED** [review]
