### PR TITLE
Fixes: [OPSTATE] specific phase in the list should not null

### LINKED ISSUE #27931: [OPSTATE] specific phase in the list should not null
The cited code is not about PhaseList, though.  It's about a specific phase _in the list_.  Those can never be null.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/26971#discussion_r1260470579_

### PR DESCRIPTION
**Pull request by mideayanghui**
Fixes #27931

### CODE REVIEW

File: src/app/clusters/operational-state-server/operational-state-server.h [hunk 1]
```diff
@@ -262,14 +267,14 @@ class Delegate
     virtual CHIP_ERROR GetOperationalStateAtIndex(size_t index, GenericOperationalState & operationalState) = 0;
 
     /**
-     * Fills in the provided GenericOperationalPhase with the phase at index `index` if there is one,
+     * Fills in the provided MutableCharSpan with the phase at index `index` if there is one,
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-state-server/operational-state-server.h:270]: This needs to document how a callee communicates "PhaseList is null".

Also: is there any use case for "empty but not null" for PhaseList?  Looks like not, but just checking.

Comment (mideayanghui) [reply src/app/clusters/operational-state-server/operational-state-server.h:270]: Optimize some document, please help check if this can match the use case for "empty but not null" for PhaseList

File: src/app/clusters/operational-state-server/operational-state-server.h [hunk 2]
```diff
@@ -269,6 +269,8 @@ class Delegate
     /**
      * Fills in the provided MutableCharSpan with the phase at index `index` if there is one,
      * or returns CHIP_ERROR_NOT_FOUND if the index is out of range for the list of phases.
+     * If fills in the provided MutableCharSpan with the phase at index `0` and returns CHIP_ERROR_NOT_FOUND,
+     * it represents PhaseList attribute is an empty list, the SDK will set PhaseList attribute value to null.
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-state-server/operational-state-server.h:273]: How about:
```suggestion
     *
     * If CHIP_ERROR_NOT_FOUND is returned for index 0, that indicates that the PhaseList attribute is null
     * (there are no phases defined at all).
     *
```
and the same in all the other places where this got copy/pasted.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]

File: src/app/clusters/operational-state-server/operational-state-server.h (hunk 2 above)
Comment (cecille) [reply src/app/clusters/operational-state-server/operational-state-server.h]: This is probably more of a spec question than an SDK question, but why have a nullable list to begin with? Per 17.18.1 

```
Composite data types that have a length (i.e. octet string and list), and derived types that have those as the base type, SHALL NOT differentiate semantically between the null value and the empty (zero length) value. 
```

This seems like extra wrappers for no good reason. Or is this just for backwards compatibility?

Comment (bzbarsky-apple) [reply src/app/clusters/operational-state-server/operational-state-server.h]: The spec could have gone either way here....  There are various opinions about which is better (e.g. null is one less byte on the wire than an empty list is).  But for purposes of the SDK, this is what the spec says, and yes, this has already shipped as nullable, so at this point we can't really change the spec.
