### PR TITLE
Missing information for LastNetworkingStatus attributes for Ethernet

### LINKED ISSUE #37824: [BUG]  Network Commissioning Cluster returns incorrect values for 'LastNetworkingStatus' and 'LastNetworkId' attributes on example apps commissioned over a network
### Reproduction steps

Test TC_CNET_4_3.py fails on example app darwin-arm64-light-no-ble/linux-x64-light-no-ble

Expected result: LastNetworkStatus is success, LastNetworkId is not Null
Actual result: LastNetworkStatus is Null, LastNetworkId is Null

assertion error:
```
Details=Null is not <NetworkCommissioningStatusEnum.kSuccess: 0> Verify that LastNetworkingStatus attribute value is success, Extras=None
```

how to reproduce: 

from branch #37387
```
python3 src/python_testing/TC_CNET_4_3.py --commissioning-method on-network  --qr-code MT:-24J0AFN00KA0648G00 --endpoint 0
```

### Bug prevalence

during manual execution of TC_CNET_4_3.py

### GitHub hash of the SDK that was being used

128e41a99d

### Platform

core, darwin

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tersal**
This is a proposed fix for #37824. Fixes #37824 

The goal is to affect the least amount of code not related to Linux platform and examples for the fix (e.g. avoid modifying specific clusters code), in this case only ConnectivityManager, AppMain and EthernetDriver are modified.

The LastNetworkingStatus is configured immediately after the Ethernet initialization provided that a valid interface name was found. A new method was added to ConnectivityManagerImpl for Linux for this sole purpose and it is only called once after the EthernetNetworkCommissioning instance is initialized.

In order to use the existing mpStatusChangeCallback (used for Thread and WiFi) this callback and the setter were moved out of the conditional compilation to make it available for all (Ethernet, WiFi and Thread).

#### Testing

Tested by hand using chip-repl to verify that the ethernet connection is reported in the attribute LastNetworkID. 

Also tested using the existing CNET test TC_CNET_4_3.py.

### CODE REVIEW

**Review by ratgr — APPROVED** [review]

**Review by jennygaz — APPROVED** [review]

File: examples/platform/linux/AppMain.cpp [hunk 1]
```diff
@@ -276,6 +276,9 @@ void InitNetworkCommissioning()
     {
 #if CHIP_APP_MAIN_HAS_ETHERNET_DRIVER
         sEthernetNetworkCommissioningInstance.Init();
+#if CHIP_DEVICE_LAYER_TARGET_LINUX
```
Comment (cecille) [inline examples/platform/linux/AppMain.cpp:281]: I think this might be redundant - this file is in platfom/linux, so I don't think it gets used anywhere that's not a linux target. If it does, we have weird stuff going on.

**Review by cecille — COMMENTED** [review]
With this change, the CNET-4.3 test should start working in the CI, right? Can you please enable that so we can see the test running?

File: examples/platform/linux/AppMain.cpp (hunk 1 above)
Comment (tersal) [reply examples/platform/linux/AppMain.cpp:281]: I believed the same, however it seems that this is also used for Darwin in some degree. There is actually a couple of compilation "guards" for Darwin in the same file (CHIP_DEVICE_LAYER_TARGET_DARWIN) and got a compilation error in the Darwin CI checks without that CHIP_DEVICE_LAYER_TARGET_LINUX condition.

**Comment by tersal** [comment]
I removed the `TC_CNET_4_3.py` from the list of excluded test in CI and the checks are still passing.

I see the next log in the tests, so I assume this is running?
image

File: examples/platform/linux/AppMain.cpp (hunk 1 above)
Comment (cecille) [reply examples/platform/linux/AppMain.cpp:281]: woah. Okie dokie...let's not shave that particular yak today.

**Review by cecille — APPROVED** [review]

File: src/platform/Linux/ConnectivityManagerImpl.cpp [hunk 2]
```diff
@@ -85,6 +85,19 @@ namespace DeviceLayer {
 
 ConnectivityManagerImpl ConnectivityManagerImpl::sInstance;
 
+void ConnectivityManagerImpl::UpdateEthernetNetworkingStatus()
+{
+    if (mpStatusChangeCallback != nullptr)
+    {
+        if (mEthIfName[0] != '\0')
```
Comment (ksperling-apple) [inline src/platform/Linux/ConnectivityManagerImpl.cpp:92]: This could just use `GetEthernetIfName()` and `CharSpan::fromString` instead of doing strnlen "by hand"

Comment (tersal) [reply src/platform/Linux/ConnectivityManagerImpl.cpp:92]: Just wanted to confirm, do you mean [`fromCharString`](https://github.com/project-chip/connectedhomeip/blob/master/src/lib/support/Span.h#L180)?, I cannot find a `fromString` function directly in Span.h.

If that is the case, I'll probably still have to do some kind of casting since `fromCharString` returns a `CharSpan` (that seems to be `Span<const char>` and the function `OnNetworkingStatusChange` expects a `ByteSpan` (that will end up being `Span<const unsigned char>`).

Comment (andy31415) [reply src/platform/Linux/ConnectivityManagerImpl.cpp:92]: I think this may be a followup - we do not have great conversions for bytestrings for null terminated strings (.... us mixing strings and byte spands does feel odd...)
