### PR TITLE
Import scene cluster

### LINKED ISSUE #2064: Import ../third_party/connectedhomeip/src/app/clusters/scenes
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

Import Scene cluster

 #### Summary of Changes

Make changes to compile and link

fixes #2064

### CODE REVIEW

File: src/app/clusters/scenes/scenes.c [hunk 1]
```diff
@@ -998,8 +998,8 @@ bool emberAfPluginScenesServerParseAddScene(const EmberAfClusterCommand * cmd, u
 
 bool emberAfPluginScenesServerParseViewScene(const EmberAfClusterCommand * cmd, uint16_t groupId, uint8_t sceneId)
 {
-    EmberAfSceneTableEntry entry;
-    EmberAfStatus status = EMBER_ZCL_STATUS_NOT_FOUND;
+    EmberAfSceneTableEntry entry = {};
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes/scenes.c:1001]: Was the lack of an initializer there triggering compiler or static analysis warnings?

**Review by bzbarsky-apple — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

File: src/app/clusters/scenes/scenes.c (hunk 1 above)
Comment (vivien-apple) [reply src/app/clusters/scenes/scenes.c:1001]: Compiler warnings.
