### PR TITLE
[Push AV 1.5.1] Update upload sequence of the record clip files

### LINKED ISSUE #41808: [BUG] Camera Push AV: init segment should be uploaded before media segment
### Reproduction steps

The current camera app is uploading the manifest & segments in the following order (with a possible race seen between first media segment `.m4s` and first manifest `.mpd`):

```
> PUT /<publishing_point_path>/session_1/media/segment_1001.m4s HTTP/2
> PUT /<publishing_point_path>/session_1/media.mpd HTTP/2
> PUT /<publishing_point_path>/session_1/media/media.init HTTP/2
> PUT /<publishing_point_path>/session_1/media/segment_1002.m4s HTTP/2
> PUT /<publishing_point_path>/session_1/media.mpd HTTP/2
> PUT /<publishing_point_path>/session_1/media/segment_1003.m4s HTTP/2
> PUT /<publishing_point_path>/session_1/media.mpd HTTP/2
> PUT /<publishing_point_path>/session_1/media/segment_1004.m4s HTTP/2
> PUT /<publishing_point_path>/session_1/media.mpd HTTP/2
> PUT /<publishing_point_path>/session_1/media/segment_1005.m4s HTTP/2
> PUT /<publishing_point_path>/session_1/media.mpd HTTP/2
> PUT /<publishing_point_path>/session_1/media/segment_1006.m4s HTTP/2
> PUT /<publishing_point_path>/session_1/media.mpd HTTP/2
> PUT /<publishing_point_path>/session_1/media.mpd HTTP/2
```

Per the [DASH spec](https://dashif.org/Ingest/#interface-1-requirements), we should do the following:

1. manifest
2. init media
3. first media segment

and then continue with subsequent media segment uploads and mpd updates. 

This will ensure that if the upload is interrupted especially in the inital period of the recording, then we can atleast play whatever segments that were uploaded. 

The issue can be seen more visibly when recording is interrupted after a few seconds and despite the media segment upload, it is not playable because init is never uploaded: [device.redacted.log](https://github.com/user-attachments/files/23378096/device.redacted.log)

### Bug prevalence

Consistent

### GitHub hash of the SDK that was being used

cfc90c89e6210a26783b94e975abd2b75de5d457

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by raveendra-karu**
#### Summary
This is to modify the upload sequence of the recorded clip files in the camera application in the following order:

1. Manifest file
2. Init media
3. First media segment

ex:  `.mpd ->  .init -> .m4s`

#### Related issues
Fixes #41808
Fixes https://github.com/project-chip/connectedhomeip/issues/41613

#### Testing
```
[1]
# Build and run camera application
./scripts/examples/gn_build_example.sh examples/camera-app/linux out/debug/
sudo rm -rf /tmp/chip_*; ./out/debug/chip-camera-app

# Build python controller and active environment
scripts/build_python.sh -m platform -i out/python_env
source out/python_env/bin/activate

# Run Push AV TC
Example:
python3 src/python_testing/TC_PAVSTI_1_1.py --commissioning-method on-network --qr-code MT:-24J0AFN00KA0648G00 --endpoint 1

[2] Verify the order the clip files in the push av server
```

### CODE REVIEW

File: examples/camera-app/linux/src/pushav-clip-recorder.cpp [hunk 1]
```diff
@@ -902,42 +891,60 @@ void PushAVClipRecorder::FinalizeCurrentClip(int reason)
...
+
+    std::filesystem::path first_segment_path = make_segment_path(1);
+    if (mUploadSegmentID == 1 && !IsFileReadyForUpload(first_segment_path))
     {
-        mUploadMPD                       = true;
-        std::string renamed_segment_path = RenameSegmentFile(segment_path.string());
-        CheckAndUploadFile(renamed_segment_path);
-        mUploadSegmentID++;
-        segment_path = make_segment_path(mUploadSegmentID);
+        return; // Wait for segment_1001.m4s to be created before starting any uploads
```
[the remark this answers is not in the document]
Comment (raveendra-karu) [reply examples/camera-app/linux/src/pushav-clip-recorder.cpp]: done

File: examples/camera-app/linux/src/pushav-clip-recorder.cpp [hunk 2]
```diff
@@ -132,59 +141,41 @@ bool PushAVClipRecorder::EnsureDirectoryExists(const std::string & path)
...
         {
             ChipLogError(Camera, "Path is not a directory: %s, error code: %d (%s)", p.c_str(), ec.value(), ec.message().c_str());
-            return false;
+            return ec;
         }
 
         auto perms = std::filesystem::status(p, ec).permissions();
         if ((perms & std::filesystem::perms::owner_write) == std::filesystem::perms::none)
         {
             ChipLogError(Camera, "Directory is not writable: %s, error code: %d (%s)", p.c_str(), ec.value(), ec.message().c_str());
```
[the remark this answers is not in the document]
Comment (raveendra-karu) [reply examples/camera-app/linux/src/pushav-clip-recorder.cpp]: done

File: examples/camera-app/linux/src/pushav-clip-recorder.cpp [hunk 3]
```diff
@@ -902,42 +891,60 @@ void PushAVClipRecorder::FinalizeCurrentClip(int reason)
...
+        mUploadSegmentID++;
+        mUploadMPD   = true;
+        segment_path = make_segment_path(mUploadSegmentID);
+    }
+    if (IsFileReadyForUpload(mpdPath) && mUploadMPD)
+    {
+        UpdateMPDStartNumber(mpdPath.string());
+        CheckAndUploadFile(mpdPath.string());
+        mUploadMPD = false;
     }
```
[the remark this answers is not in the document]
Comment (raveendra-karu) [reply examples/camera-app/linux/src/pushav-clip-recorder.cpp:987]: done

File: examples/camera-app/linux/src/pushav-clip-recorder.cpp [hunk 4]
```diff
@@ -147,7 +147,7 @@ bool PushAVClipRecorder::EnsureDirectoryExists(const std::string & path)
         auto perms = std::filesystem::status(p, ec).permissions();
         if ((perms & std::filesystem::perms::owner_write) == std::filesystem::perms::none)
         {
-            ChipLogError(Camera, "Directory is not writable: %s, error code: %d (%s)", p.c_str(), ec.value(), ec.message().c_str());
+            ChipLogError(Camera, "Directory is not writable: %s", p.c_str());
```
Comment (vnkavali) [inline examples/camera-app/linux/src/pushav-clip-recorder.cpp]: Is it possible to print perms here?

File: examples/camera-app/linux/src/pushav-clip-recorder.cpp [hunk 5]
```diff
@@ -845,6 +845,30 @@ bool PushAVClipRecorder::IsFileReadyForUpload(const std::filesystem::path & path
     return std::filesystem::exists(path) && !std::filesystem::exists(path.string() + ".tmp");
 }
 
+/**
+ * @brief Uploads the MPD file if it's ready
+ *
+ * @return true if MPD was uploaded or is not ready yet, false on error
+ */
+bool PushAVClipRecorder::UploadMPDIfReady(const std::filesystem::path & mpdPath)
```
Comment (vnkavali) [inline examples/camera-app/linux/src/pushav-clip-recorder.cpp]: I think this is better defined as a lambda function in `FinalizeCurrentClip` rather than a new function

File: examples/camera-app/linux/include/uploader/pushav-uploader.h [hunk 6]
```diff
@@ -65,8 +66,10 @@ class PushAVUploader
     void setCertificateBuffer(const PushAVCertBuffer & certBuffer) { mCertBuffer = certBuffer; }
     void setCertificatePath(const PushAVCertPath & certPath) { mCertPath = certPath; }
 
-    void setMPDPath(const std::pair<std::string, std::string> & path) { mMPDPath = path; }
-    std::pair<std::string, std::string> getMPDPath() const { return mMPDPath; }
+    void UploadFinalMPD(const std::filesystem::path & filename, std::string & url)
```
Comment (yufengwangca) [inline examples/camera-app/linux/include/uploader/pushav-uploader.h]:
```suggestion
    void UploadFinalMPD(const std::filesystem::path & filename, const std::string & url)
```

File: examples/camera-app/linux/include/uploader/pushav-uploader.h [hunk 7]
```diff
@@ -65,8 +66,10 @@ class PushAVUploader
...
+    {
+        UploadData(make_pair(filename.string(), url));
```
Comment (yufengwangca) [inline examples/camera-app/linux/include/uploader/pushav-uploader.h]:
```suggestion
        UploadData(std::make_pair(filename.string(), url));
```

File: examples/camera-app/linux/src/pushav-clip-recorder.cpp [hunk 8]
```diff
@@ -103,25 +103,34 @@ PushAVClipRecorder::~PushAVClipRecorder()
...
 {
     // Base output path
     std::filesystem::path basePath(path);
     std::filesystem::path sessionDir = basePath / ("session_" + std::to_string(mClipInfo.mSessionNumber));
-    std::filesystem::path trackDir   = sessionDir / mClipInfo.mTrackName;
+    mUploadFileBasePath              = sessionDir / mClipInfo.mTrackName;
 
     // Helper lambda to ensure a directory exists and is writable, creating it with mode 0755
-    auto ensure = [&](const std::filesystem::path & p) -> bool {
+    auto ensure = [&](const std::filesystem::path & p) -> std::error_code {
```
Comment (yufengwangca) [inline examples/camera-app/linux/src/pushav-clip-recorder.cpp]: You changed the inner lambda to return std::error_code and then use it in boolean contexts (if (ensure(basePath))). While this works because error_code converts to bool when there's an error, it's surprising and reduces readability.

Also some filesystem calls use the overloads without std::error_code which can throw exceptions on some platforms/permissions. 

Recommendations:
Make the lambda return bool (true on success) and log/return false on failure;

File: examples/camera-app/linux/src/uploader/pushav-uploader.cpp [hunk 9]
```diff
@@ -33,29 +33,12 @@ PushAVUploader::PushAVUploader() : mIsRunning(false) {}
...
-        if (!std::filesystem::remove(uploadJob.first, ec))
-        {
-            ChipLogError(Camera, "Failed to delete file: %s, error: %s", uploadJob.first.c_str(), ec.message().c_str());
-        }
-        else
-        {
-            ChipLogDetail(Camera, "Successfully deleted file: %s", uploadJob.first.c_str());
-        }
     }
 }
```
[the remark this answers is not in the document]
Comment (raveendra-karu) [reply examples/camera-app/linux/src/uploader/pushav-uploader.cpp:62]: No nee to upload the pending requests

File: examples/camera-app/linux/src/pushav-clip-recorder.cpp (hunk 4 above)
Comment (raveendra-karu) [reply examples/camera-app/linux/src/pushav-clip-recorder.cpp]: Done

File: examples/camera-app/linux/include/uploader/pushav-uploader.h (hunk 6 above)
Comment (raveendra-karu) [reply examples/camera-app/linux/include/uploader/pushav-uploader.h]: Done

File: examples/camera-app/linux/src/pushav-clip-recorder.cpp (hunk 8 above)
Comment (raveendra-karu) [reply examples/camera-app/linux/src/pushav-clip-recorder.cpp]: Done

File: examples/camera-app/linux/src/pushav-clip-recorder.cpp (hunk 5 above)
Comment (raveendra-karu) [reply examples/camera-app/linux/src/pushav-clip-recorder.cpp]: Done

File: examples/camera-app/linux/include/uploader/pushav-uploader.h (hunk 7 above)
Comment (raveendra-karu) [reply examples/camera-app/linux/include/uploader/pushav-uploader.h]: Done

**Review by yufengwangca — APPROVED** [review]

File: examples/camera-app/linux/src/uploader/pushav-uploader.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (pidarped) [reply examples/camera-app/linux/src/uploader/pushav-uploader.cpp:62]: Wondering about why there is no need to upload the pending requests. Draining the queue in the destructor seems like a good guardrail to have reliability on the transfer.

File: examples/camera-app/linux/src/pushav-clip-recorder.cpp [hunk 10]
```diff
@@ -896,47 +908,81 @@ void PushAVClipRecorder::FinalizeCurrentClip(ClipFinalizationReason reason)
...
+        oss << "#__" << stream << "__#segment_" << std::setw(4) << std::setfill('0') << number << ".m4s";
+        return mUploadFileBasePath / oss.str();
     };
 
-    std::filesystem::path segment_path = make_segment_path(mUploadSegmentID);
-    while (std::filesystem::exists(segment_path) && !std::filesystem::exists(segment_path.string() + ".tmp"))
+    std::filesystem::path mpdPath = mUploadFileBasePath / "index.mpd";
+
+    // Wait for the first segment (segment_0001.m4s) for any stream to be created before starting any uploads
+    for (size_t i = 0; i < mUploadSegmentID.size(); i++)
```
Comment (vnkavali) [inline examples/camera-app/linux/src/pushav-clip-recorder.cpp]: This for loop doesn't have to run if `firstSegmentReady` is already `true`

File: examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp [hunk 11]
```diff
@@ -503,29 +538,20 @@ void PushAVTransport::SetTransportStatus(TransportStatusEnum status)
         mUploader->setCertificateBuffer(mCertBuffer);
         mUploader->setCertificatePath(mCertPath);
         mUploader->Start();
```
Comment (vnkavali) [inline examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp]: This is now redundant, please remove.

File: src/python_testing/TC_PAVST_2_12.py
Comment (vnkavali) [inline src/python_testing/TC_PAVST_2_12.py:1]:
```diff
-                endpoint=endpoint, cluster=tlscluster, attribute=tlsattr
+                endpoint=endpoint, cluster=tlscluster, attribute=tlsattr.ProvisionedEndpoints
```

Please fix this in `TC_PAVST_2_11.py`

Comment (raveendra-karu) [reply src/python_testing/TC_PAVST_2_12.py:1]: done

File: examples/camera-app/linux/src/pushav-clip-recorder.cpp (hunk 10 above)
Comment (raveendra-karu) [reply examples/camera-app/linux/src/pushav-clip-recorder.cpp]: added check!

File: examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp (hunk 11 above)
Comment (raveendra-karu) [reply examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp]: done

File: examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp [hunk 12]
```diff
@@ -242,13 +242,25 @@ CHIP_ERROR PushAVTransport::ConfigureRecorderSettings(const TransportOptionsStru
...
-    mVideoInfo.mVideoFrameDuration = mVideoInfo.mVideoTimeBase.den / (mVideoInfo.mFrameRate * mVideoInfo.mVideoTimeBase.num);
-    mVideoInfo.mVideoStreamIndex   = -1;
-    mVideoInfo.mBitRate            = videoStreamParams.minBitRate;
+    mVideoInfo.mBitRate   = videoStreamParams.minBitRate;
+    if (mClipInfo.mHasVideo)
+    {
+        if (transportOptions.videoStreams.HasValue())
+        {
+            // Recoder module currently only supports one audio and one video stream
+            mVideoInfo.mVideoStreamName = transportOptions.videoStreams.Value().begin()->videoStreamName.data();
```
Comment (samadDotDev) [inline examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp]: Couple of bugs here:

1. The streams vector needs to be checked for emptiness
2. The stream name is a `CharSpan` which is not null-terminated, so you need to construct string with the type's size.

```suggestion
        if (transportOptions.videoStreams.HasValue() && !transportOptions.videoStreams.Value().empty())
        {
            // Recoder module currently only supports one audio and one video stream
            auto videoStreamName        = transportOptions.videoStreams.Value().begin()->videoStreamName;
            mVideoInfo.mVideoStreamName = std::string(videoStreamName.data(), videoStreamName.size());
```

File: examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp [hunk 13]
```diff
@@ -216,19 +209,26 @@ CHIP_ERROR PushAVTransport::ConfigureRecorderSettings(const TransportOptionsStru
...
-    mAudioInfo.mAudioPts         = 0;
-    mAudioInfo.mAudioDts         = 0;
-    mAudioInfo.mAudioStreamIndex = -1;
+    mAudioInfo.mBitRate = audioStreamParams.bitRate;
+    if (mClipInfo.mHasAudio)
+    {
+        if (transportOptions.audioStreams.HasValue())
+        {
+            // Recoder module currently only supports one audio and one video stream
+            mAudioInfo.mAudioStreamName = transportOptions.audioStreams.Value().begin()->audioStreamName.data();
```
Comment (samadDotDev) [inline examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp]: Similarly for audio streams

```suggestion
        if (transportOptions.audioStreams.HasValue() && !transportOptions.audioStreams.Value().empty())
        {
            // Recoder module currently only supports one audio and one video stream
            auto audioStreamName        = transportOptions.audioStreams.Value().begin()->audioStreamName;
            mAudioInfo.mAudioStreamName = std::string(audioStreamName.data(), audioStreamName.size());
```

Comment (raveendra-karu) [reply examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp]: Done

File: examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp (hunk 12 above)
Comment (raveendra-karu) [reply examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp]: Done

File: examples/camera-app/linux/include/uploader/pushav-uploader.h [hunk 14]
```diff
@@ -78,4 +79,5 @@ class PushAVUploader
     std::atomic<bool> mIsRunning;
     std::thread mUploaderThread;
     std::pair<std::string, std::string> mMPDPath;
+    std::vector<std::string> mStreamIdNameMap;
```
Comment (samadDotDev) [inline examples/camera-app/linux/include/uploader/pushav-uploader.h]: Is the `mMPDPath` used anywhere else? If not, can we remove it?

File: examples/camera-app/linux/src/pushav-clip-recorder.cpp [hunk 15]
```diff
@@ -896,47 +908,84 @@ void PushAVClipRecorder::FinalizeCurrentClip(ClipFinalizationReason reason)
...
 
-    // Handle MPD and init file upload
     if (mUploadMPD)
     {
-        std::filesystem::path mpd_path = basePath;
-        mpd_path += ".mpd";
-        if (std::filesystem::exists(mpd_path) && !std::filesystem::exists(mpd_path.string() + ".tmp"))
+        if (IsFileReadyForUpload(mpdPath))
         {
-            mUploader->setMPDPath(std::make_pair(mpd_path.string(), mClipInfo.mUrl));
```
Comment (samadDotDev) [inline examples/camera-app/linux/src/pushav-clip-recorder.cpp:923]: There's a regression since this removal where the uploader/recorder no longer has the up-to-date URL when it is modified using `ModifyPushTransport`.

File: src/app/clusters/push-av-stream-transport-server/PushAVStreamTransportLogic.cpp [hunk 16]
```diff
@@ -637,12 +637,14 @@ Status PushAvStreamTransportServerLogic::ValidateIncomingTransportOptions(
...
-                             const std::shared_ptr<PushAvStreamTransport::TransportOptionsStorage> transportOptionsPtr)
+std::optional<DataModel::ActionReturnStatus> PushAvStreamTransportServerLogic::ValidateStreamParameters(
+    CommandHandler & handler, const ConcreteCommandPath & commandPath,
+    const PushAvStreamTransport::Structs::TransportOptionsStruct::DecodableType & transportOptions,
+    const std::shared_ptr<PushAvStreamTransport::TransportOptionsStorage> transportOptionsPtr)
 {
 
-    // Check mutual exclusivity and presence of stream fieldsconst PushAvStreamTransport::Structs::TransportOptionsStruct::DecodableType
+    // Check mutual exclusivity and presence of stream fieldsconst
+    // PushAvStreamTransport::Structs::TransportOptionsStruct::DecodableType
```
Comment (vnkavali) [inline src/app/clusters/push-av-stream-transport-server/PushAVStreamTransportLogic.cpp]: Seems like a typo?

Comment (raveendra-karu) [reply src/app/clusters/push-av-stream-transport-server/PushAVStreamTransportLogic.cpp]: done

File: examples/camera-app/linux/include/uploader/pushav-uploader.h (hunk 14 above)
Comment (raveendra-karu) [reply examples/camera-app/linux/include/uploader/pushav-uploader.h]: done

File: examples/camera-app/linux/src/pushav-clip-recorder.cpp (hunk 15 above)
Comment (raveendra-karu) [reply examples/camera-app/linux/src/pushav-clip-recorder.cpp:923]: done

**Review by vnkavali — APPROVED** [review]
