### PR TITLE
Se05x HSM support in thermostat example

### LINKED ISSUE #22905: [NXP SE05x] Add se05x support in thermostat example
### Reproduction steps

```bash
No SE05x (HSM) support files available for thermostat example. Add the missing platform support files.
```

### Platform

NXP SE05x

### Platform Version(s)

N/A

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sujaygkulkarni-nxp**
#### Problem
Se05x HSM support in thermostat example

* Fixes #22905 

#### Change overview
* Added Se05x support in thermostat example
* Also included the device attestation support using se05x HSM 

#### Testing
Tested using the thermostat example and chip tool for connectivity

### CODE REVIEW

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 1]
```diff
@@ -0,0 +1,301 @@
...
+CHIP_ERROR ExampleSe05xDACProviderv2::SignWithDeviceAttestationKey(const ByteSpan & message_to_sign,
+                                                                   MutableByteSpan & out_signature_buffer)
+{
+    CHIP_ERROR err = CHIP_NO_ERROR;
+    VerifyOrReturnError(IsSpanUsable(out_signature_buffer), CHIP_ERROR_INVALID_ARGUMENT);
+    VerifyOrReturnError(IsSpanUsable(message_to_sign), CHIP_ERROR_INVALID_ARGUMENT);
+
+    ChipLogDetail(Crypto, "Sign using DA key from se05x (Using internal sign)");
+
+    MutableByteSpan tlv_buffer = ((MutableByteSpan &) message_to_sign).SubSpan(1); // Exclude the Start container
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:175]: This is not really ok; why is this casting away const?

You can do `SubSpan` on a `ByteSpan` if that's what you want to do, though ideally you would just init your TLVReader with the whole ByteSpan and then verify that it's on a start container, the container is of the right type, etc, instead of just silently skipping the first byte and assuming that this is the right thing.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 2]
```diff
@@ -0,0 +1,301 @@
...
+
+    msg_reader.Init(tlv_buffer);
+    msg_reader.Next();
+
+    /* To be removed. Use common key id to sign message */
+    static bool sign_cert_decl_attest = 1;
+
+    if (sign_cert_decl_attest)
+    {
+        /* Skip certificate declaration tag */
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:188]: This seems to be assuming that `SignWithDeviceAttestationKey` will only be called on messages with a specific TLV structure... Is that assumption documented anywhere in the API?

Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:188]: Shouldn't this check that the current tag is in fact the certification declaration tag?

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 3]
```diff
@@ -0,0 +1,301 @@
...
+
+    ChipLogDetail(Crypto, "Sign using DA key from se05x (Using internal sign)");
+
+    MutableByteSpan tlv_buffer = ((MutableByteSpan &) message_to_sign).SubSpan(1); // Exclude the Start container
+
+    TLV::TLVReader msg_reader;
+    TLV::Tag tagValue;
+
+    msg_reader.Init(tlv_buffer);
+    msg_reader.Next();
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:181]: Shouldn't this be error-checked?

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 4]
```diff
@@ -0,0 +1,301 @@
...
+
+    /* To be removed. Use common key id to sign message */
+    static bool sign_cert_decl_attest = 1;
+
+    if (sign_cert_decl_attest)
+    {
+        /* Skip certificate declaration tag */
+        msg_reader.Next();
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:189]: This and all the other calls on msg_reader can fail depending on what's in the buffer.  They should all be checked.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 5]
```diff
@@ -0,0 +1,301 @@
...
+        VerifyOrReturnError(CHIP_NO_ERROR == se05xSetCertificate(CD_TIME_STAMP_LEN_SE05X_ID, &tmp, 1), CHIP_ERROR_INTERNAL);
+        if (time_stamp.size() > 0)
+        {
+            /* Set time stamp data */
+            VerifyOrReturnError(CHIP_NO_ERROR ==
+                                    se05xSetCertificate(CD_TIME_STAMP_DATA_SE05X_ID, time_stamp.data(), time_stamp.size()),
+                                CHIP_ERROR_INTERNAL);
+        }
+
+        if (message_to_sign.size() >= 16)
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:217]: This doesn't really guarantee that we have not already read to within <16 bytes of the end, right?  Shouldn't this be comparing `message_to_sign.size()` minus the number of bytes the reader has consumed, at least?

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 6]
```diff
@@ -0,0 +1,301 @@
...
+    size_t signature_se05x_len                                       = sizeof(signature_se05x);
+
+    if (sign_cert_decl_attest)
+    {
+        err = se05xPerformInternalSign(CD_DEV_ATTESTATION_KEY_SE05X_ID, signature_se05x, &signature_se05x_len);
+        se05x_delete_key(CD_ATTEST_NONCE_DATA_SE05X_ID);
+        se05x_delete_key(CD_TIME_STAMP_LEN_SE05X_ID);
+        se05x_delete_key(CD_TIME_STAMP_DATA_SE05X_ID);
+        se05x_delete_key(CD_ATTEST_CHALLENGE_SE05X_ID);
+        sign_cert_decl_attest = 0;
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:270]: This seems to be assuming that the calls to this function will come in a certain order in terms of whether we're signing a CSR or the attestation bits.  What guarantees this order?  Note that two CSRRequests can happen in a row....

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 1 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp]: updated the code. Using find utilities to the required TLVs now.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 2 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp]: Checking the certificate declaration tag also now,

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 3 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp]: Added error checks

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 4 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp]: Added error checks

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 5 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp]: updated the condition now

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 6 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:276]: This limitation will be removed in the subsequent PR. (Put a note for the same). After updating our HSM side implementation, the signing will be independent of the calls. 
Also this is not the default se05x DAC provider class. The default (ExampleSe05xDACProvider) will sign the message without paring the TLV data.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 2 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp]: From the spec, I see that DA key is used only for signing these 2 cases. 
6.2.3. Device Attestation Procedure  and 
6.4.6.1. Node Operational Certificate Signing Request (NOCSR) Procedure

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 7]
```diff
@@ -172,49 +173,50 @@ CHIP_ERROR ExampleSe05xDACProviderv2::SignWithDeviceAttestationKey(const ByteSpa
...
+                                    se05xSetCertificate(CD_ATTEST_NONCE_DATA_SE05X_ID, attest_nonce.data(), attest_nonce.size()),
+                                CHIP_ERROR_INTERNAL);
+        }
+
+        ReturnErrorOnFailure(TLV::Utilities::Find(msg_reader, TLV::ContextTag(3), tagReader));
+        uint8_t tslen = tagReader.GetLength();
         /* Set time stamp length */
-        VerifyOrReturnError(CHIP_NO_ERROR == se05xSetCertificate(CD_TIME_STAMP_LEN_SE05X_ID, &tmp, 1), CHIP_ERROR_INTERNAL);
-        if (time_stamp.size() > 0)
+        VerifyOrReturnError(CHIP_NO_ERROR == se05xSetCertificate(CD_TIME_STAMP_LEN_SE05X_ID, &tslen, 1), CHIP_ERROR_INTERNAL);
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:206]: Note that if the TLV is malicious then `tslen` might have an arbitrary value here...  your should really not use it for anything important until the `Get()` for the `ByteSpan` succeeds.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 8]
```diff
@@ -172,49 +173,50 @@ CHIP_ERROR ExampleSe05xDACProviderv2::SignWithDeviceAttestationKey(const ByteSpa
...
+        if (tslen > 0)
         {
+            ByteSpan time_stamp;
+            tagReader.Get(time_stamp);
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:210]: Needs an error check, no?

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 9]
```diff
@@ -172,49 +173,50 @@ CHIP_ERROR ExampleSe05xDACProviderv2::SignWithDeviceAttestationKey(const ByteSpa
...
             /* Set time stamp data */
             VerifyOrReturnError(CHIP_NO_ERROR ==
                                     se05xSetCertificate(CD_TIME_STAMP_DATA_SE05X_ID, time_stamp.data(), time_stamp.size()),
                                 CHIP_ERROR_INTERNAL);
         }
 
-        if (message_to_sign.size() >= 16)
+        if (message_to_sign.size() -
+                (cdlen + attlen + tslen + 9 /* Tag + control byte + len */ + 2 /* start and end containers*/) >=
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:218]: Why wouldn't you just use the tag reader's actual position (after calling `Next()` on it) here instead of trying to recompute it?

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 10]
```diff
@@ -224,31 +226,35 @@ CHIP_ERROR ExampleSe05xDACProviderv2::SignWithDeviceAttestationKey(const ByteSpa
...
-        /* Get nocsr nonce */
-        ByteSpan nocsr_nonce;
-        msg_reader.Get(nocsr_nonce);
-        /* Set nocsr nonce data */
-        VerifyOrReturnError(CHIP_NO_ERROR ==
-                                se05xSetCertificate(NOCSR_CSR_NONCE_DATA_SE05X_ID, nocsr_nonce.data(), nocsr_nonce.size()),
-                            CHIP_ERROR_INTERNAL);
-
-        if (message_to_sign.size() >= 16)
+        VerifyOrReturnError(CHIP_NO_ERROR == se05xSetCertificate(NOCSR_CSR_LEN_SE05X_ID, &csrlen, 1), CHIP_ERROR_INTERNAL);
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:232]: Again, is it ok if csrlen is too large here?  The Get() for the csr_data will error out in that case, so maybe it is.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 11]
```diff
@@ -224,31 +226,35 @@ CHIP_ERROR ExampleSe05xDACProviderv2::SignWithDeviceAttestationKey(const ByteSpa
...
+            /* Get nocsr nonce */
+            ByteSpan nocsr_nonce;
+            ReturnErrorOnFailure(tagReader.Get(nocsr_nonce));
+            /* Set nocsr nonce data */
+            VerifyOrReturnError(CHIP_NO_ERROR ==
+                                    se05xSetCertificate(NOCSR_CSR_NONCE_DATA_SE05X_ID, nocsr_nonce.data(), nocsr_nonce.size()),
+                                CHIP_ERROR_INTERNAL);
+        }
+
+        if (message_to_sign.size() - (csrlen + noncelen + 6 /* Tag + control byte + len */ + 2 /* start and end containers*/) >= 16)
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:257]: Again, better to use the reader's actual position than this guess?

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 7 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:206]: Get() would fail in case the length in TLV is 0. But i would still need the length information to be passed to HSM. So not relying on the status of Get() here. ALso the data created in HSM is transient data. So this should be fine.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 9 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:218]: I see some issues when i use the Next() for parsing the TLV data here. Using Find() utility to get the TLV data. For this I am  recomputing the value data utilized.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 8 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp]: Added error check

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 10 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:236]: Doing this operation now after Get().

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 11 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:253]: I see some issues when i use the Next() for parsing the TLV data here. Using Find() utility to get the TLV data. For this I am recomputing the value data utilized.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 7 above)
Comment (bzbarsky-apple) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:205]: No, my point is that the `tslen` might be large enough it's larger than the TLV buffer, so this call returns a garbage value and then `Get` fails

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 9 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp]: Updated the code to use GetRemainingLength() now.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 7 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp]: Changed the sequence of calls now. Using length after get() is called.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 12]
```diff
@@ -0,0 +1,298 @@
...
+        {
+            ByteSpan time_stamp;
+            ReturnErrorOnFailure(tagReader.Get(time_stamp));
+            /* Set time stamp data */
+            VerifyOrReturnError(CHIP_NO_ERROR ==
+                                    se05xSetCertificate(CD_TIME_STAMP_DATA_SE05X_ID, time_stamp.data(), time_stamp.size()),
+                                CHIP_ERROR_INTERNAL);
+        }
+        /* Set time stamp length */
+        VerifyOrReturnError(CHIP_NO_ERROR == se05xSetCertificate(CD_TIME_STAMP_LEN_SE05X_ID, &tslen, 1), CHIP_ERROR_INTERNAL);
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:212]: Why isn't this using `time_stamp.size()`?  That is, what is the point of `tslen` at all?  It seems like an attractive nuisance, as do most of the `GetLength` calls here.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 13]
```diff
@@ -0,0 +1,298 @@
...
+    else
+    {
+        ReturnErrorOnFailure(TLV::Utilities::Find(msg_reader, TLV::ContextTag(1), tagReader));
+        uint8_t csrlen = tagReader.GetLength();
+        VerifyOrReturnError(csrlen > 0, CHIP_ERROR_INVALID_TLV_TAG);
+        ByteSpan csr_data;
+        /* Get nocsr */
+        ReturnErrorOnFailure(tagReader.Get(csr_data));
+        /* Set nocsr length */
+        VerifyOrReturnError(CHIP_NO_ERROR == se05xSetCertificate(NOCSR_CSR_LEN_SE05X_ID, &csrlen, 1), CHIP_ERROR_INTERNAL);
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:231]: Why not initializing csrlen from `csr_data.size()`?

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 14]
```diff
@@ -0,0 +1,298 @@
...
+    size_t signature_se05x_len                                       = sizeof(signature_se05x);
+
+    if (sign_cert_decl_attest)
+    {
+        err = se05xPerformInternalSign(CD_DEV_ATTESTATION_KEY_SE05X_ID, signature_se05x, &signature_se05x_len);
+        se05x_delete_key(CD_ATTEST_NONCE_DATA_SE05X_ID);
+        se05x_delete_key(CD_TIME_STAMP_LEN_SE05X_ID);
+        se05x_delete_key(CD_TIME_STAMP_DATA_SE05X_ID);
+        se05x_delete_key(CD_ATTEST_CHALLENGE_SE05X_ID);
+        sign_cert_decl_attest = 0;
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:267]: This setup with sign_cert_decl_attest needs to be very clearly documented, especially because it's not spec-compliant....

**Review by bzbarsky-apple — APPROVED** [review]

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 12 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:212]: get() member will return error in case the tag length is 0. So using the GetLength() before get() member is called.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 13 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:231]: get() member will return error in case the tag length is 0. So using the GetLength() before get() member is called.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 12 above)
Comment (bzbarsky-apple) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:212]: Wait, what?  Why would `Get` return an error on 0 length?  It most certainly does not do that...

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 13 above)
Comment (bzbarsky-apple) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:231]: Again, `Get` does not return error on zero length....

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 12 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:212]: I have created the issue to check this as well as other changes you suggested in the previous conversation. (https://github.com/project-chip/connectedhomeip/issues/23064). Will address these in the next PR.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 13 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:231]: I have created the issue to check this as well as other changes you suggested in the previous conversation. (https://github.com/project-chip/connectedhomeip/issues/23064). Will address these in the next PR.
