### PR TITLE
Address API review issues in MTRControllerFactory.

### LINKED ISSUE #22594: [Platform] Apply darwin API review changes to MTRControllerFactory and the factory and controller startup params
### Reproduction steps

MTRControllerFactory, and the startup params files for controllers and controller factories need various fixes based on the API review. This includes documentation, function naming, etc, etc.

Part of https://github.com/project-chip/connectedhomeip/issues/22420

### Platform

darwin

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
* Rename to MTRDeviceControllerFactory.
* Change the startup params startServer to shouldStartServer.
* Change the startup params init signatures to be more aligned.
* Change isRunning to running.
* Rename startup to startControllerFactory and add NSError outparam.
* Rename shutdown to stopControllerFactory
* Rename startControllerOnExistingFabric to createControllerOnExistingFabric and add NSError outparam.
* Rename startControllerOnNewFabric to createControllerOnNewFabric and add NSError outparam.

Addresses part of https://github.com/project-chip/connectedhomeip/issues/22420

#### Issue Being Resolved
* Fixes #22594

#### Change overview
See above.

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRDeviceControllerFactory.h [hunk 1]
```diff
@@ -66,44 +66,47 @@ NS_ASSUME_NONNULL_BEGIN
...
 - (instancetype)initWithStorage:(id<MTRPersistentStorageDelegate>)storageDelegate;
 @end
 
-@interface MTRControllerFactory : NSObject
+@interface MTRDeviceControllerFactory : NSObject
 
-@property (readonly, nonatomic) BOOL isRunning;
-
-- (instancetype)init NS_UNAVAILABLE;
-+ (instancetype)new NS_UNAVAILABLE;
```
Comment (vivien-apple) [inline src/darwin/Framework/CHIP/MTRDeviceControllerFactory.h:80]: I thought that making `init` and `new` unavailable was to make sure folks are using the shared instance ?  Do we really want to not lock it down ?

Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDeviceControllerFactory.h:80]: I just moved those to the end of the interface.

**Review by vivien-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
Fast-tracking platform-specific change with platform owner review.

**Review by andy31415 — APPROVED** [review]
