### PR TITLE
Try multiple transports in SetUpCodePairer.

### LINKED ISSUE #16728: Unable to pair via manual pin code on iOS chip tool - Error Domain=CHIPErrorDomain Code=9 "Transaction timed out." UserInfo={NSLocalizedDescription=Transaction timed out
Unable to pair M5 all clusters app via pin code with iOS chip tool

1. Launch iOS chiptool
2. Enter manual pin code to pair via iOS chip tool 

In step 2:  Seeing timeout failures with pin code: Error Domain=CHIPErrorDomain Code=9 "Transaction timed out." UserInfo={NSLocalizedDescription=Transaction timed out

Only activity seen on the M5 board logs when entering manual pin code  - 3 retries:
I (650936) ROUTE_HOOK: Received RIO
I (650936) ROUTE_HOOK: prefix FDE4:B950:2EE9:: lifetime 1800

With the M5 in the same state, I was able to scan in the QR code and pair the M5 board successfully

Seen: 5 out of 5

<details>
<summary>Logs on chiptool:</summary>

```
CFPrefsSearchListSource<0x283f76200> (Domain: com.apple.keyboard.preferences, Container: (null))
2022-03-28 09:28:36.967776-0700  localhost CHIPTool[608]: (CHIP) [com.zigbee.chip:all] ð¢ [1648484916967] [608:19924] CHIP: [EM] Retransmitting MessageCounter:3977131908 on exchange 22553i Send Cnt 1
2022-03-28 09:28:36.968002-0700  localhost CHIPTool[608]: (CHIP) [com.zigbee.chip:all] ðµ [1648484916967] [608:19924] CHIP: [IN] Sending unauthenticated msg 0x11a04e068 with MessageCounter:3977131908 to 0x0000000000000000 at monotonic time: 0000017FD15B9EE7 msec
2022-03-28 09:28:38.969502-0700  localhost CHIPTool[608]: (CHIP) [com.zigbee.chip:all] ð¢ [1648484918969] [608:19824] CHIP: [EM] Retransmitting MessageCounter:3977131908 on exchange 22553i Send Cnt 2
2022-03-28 09:28:38.969774-0700  localhost CHIPTool[608]: (CHIP) [com.zigbee.chip:all] ðµ [1648484918969] [608:19824] CHIP: [IN] Sending unauthenticated msg 0x11a04e068 with MessageCounter:3977131908 to 0x0000000000000000 at monotonic time: 0000017FD15BA6B9 msec
2022-03-28 09:28:40.971276-0700  localhost CHIPTool[608]: (CHIP) [com.zigbee.chip:all] ð´ [1648484920971] [608:19924] CHIP: [EM] Failed to Send CHIP MessageCounter:3977131908 on exchange 22553i sendCount: 3 max retries: 3
2022-03-28 09:29:14.603417-0700  localhost CHIPTool[608]: (UIKitCore) [com.apple.UIKit:MultitouchAnalytics] Analytics: Reporting foreground time: 60.001 sec
2022-03-28 09:29:14.603731-0700  localhost CHIPTool[608]: (CoreAnalytics) [com.apple.CoreAnalytics.event:send] com.apple.app-profile {"appForegroundActiveDuration":60.001276041666664,"bundleID":"com.chip.CHIPTool-Kean"}
2022-03-28 09:29:16.818913-0700  localhost CHIPTool[608]: (AssistantServices) [com.apple.siri:Client] _AFInternalPreferencesDidChangeCallback Internal Preferences Changed!
2022-03-28 09:29:16.819145-0700  localhost CHIPTool[608]: (AssistantServices) [com.apple.siri:Client] -[AFPreferences _internalPreferencesDidChangeExternally] 0x281f06af0 <AFInstanceContextHost: 0x281348980> (default)
2022-03-28 09:29:19.964836-0700  localhost CHIPTool[608]: (CHIP) [com.zigbee.chip:all] ð´ [1648484959964] [608:19924] CHIP: [SC] PASESession timed out while waiting for a response from the peer. Expected message type was 33
2022-03-28 09:29:19.965100-0700  localhost CHIPTool[608]: (CHIP) DevicePairingDelegate status updated: 1
2022-03-28 09:29:19.965594-0700  localhost CHIPTool[608]: (CHIP) DevicePairingDelegate Pairing complete. Status ../../../../../../../../../../../connectedhomeip/src/protocols/secure_channel/PASESession.cpp:324: CHIP Error 0x00000032: Timeout
2022-03-28 09:29:19.965966-0700  localhost CHIPTool[608]: (CoreFoundation) [com.apple.CFBundle:resources] Resource lookup at CFBundle 0x119e05070 </private/var/containers/Bundle/Application/E0C9D276-266F-430A-BEB2-939ACC8A91CD/CHIPTool.app> (executable, loaded)
	Request       : Localizable type: strings
	Result        : None
2022-03-28 09:29:19.966124-0700  localhost CHIPTool[608]: (CoreFoundation) [com.apple.CFBundle:resources] Resource lookup at CFBundle 0x119e05070 </private/var/containers/Bundle/Application/E0C9D276-266F-430A-BEB2-939ACC8A91CD/CHIPTool.app> (executable, loaded)
	Request       : Localizable type: stringsdict
	Result        : None
2022-03-28 09:29:19.966215-0700  localhost CHIPTool[608]: (CoreFoundation) [com.apple.CFBundle:strings] Hit last resort and creating empty strings table
2022-03-28 09:29:19.966340-0700  localhost CHIPTool[608]: (CoreFoundation) [com.apple.defaults:User Defaults] found no value for key NSShowNonLocalizedStrings in CFPrefsSearchListSource<0x283f50c00> (Domain: com.chip.CHIPTool-Kean, Container: (null))
2022-03-28 09:29:19.966460-0700  localhost CHIPTool[608]: (CoreFoundation) [com.apple.CFBundle:strings] Bundle: CFBundle 0x119e05070 </private/var/containers/Bundle/Application/E0C9D276-266F-430A-BEB2-939ACC8A91CD/CHIPTool.app> (executable, loaded), key: Transaction timed out., value: , table: Localizable, localizationName: (null), result: Transaction timed out.
2022-03-28 09:29:19.966690-0700  localhost CHIPTool[608]: Got pairing error back Error Domain=CHIPErrorDomain Code=9 "Transaction timed out." UserInfo={NSLocalizedDescription=Transaction timed out.}
```

</details>

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
When a device gets removed from a fabric and then factory reset, we
can get into a situation where it's only listening over BLE but there
are stale DNS-SD records for it.  In that case we should try BLE once
we discover that doing PASE over IP does not work.

Fixes https://github.com/project-chip/connectedhomeip/issues/16728

#### Problem
See above.

#### Change overview
See above.

#### Testing
Followed the steps to reproduce from https://github.com/project-chip/connectedhomeip/issues/16728 and verified that once the IP PASE setup times out we connect to the m5stack over BLE and commission it.

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

File: src/controller/SetUpCodePairer.cpp [hunk 1]
```diff
@@ -192,14 +274,46 @@ void SetUpCodePairer::NotifyCommissionableDeviceDiscovered(const Dnssd::Discover
     {
         return;
     }
-    LogErrorOnFailure(StopConnectOverBle());
+
+    ChipLogProgress(Controller, "Discovered device to be commissioned over DNS-SD");
+
+    mWaitingForDiscovery[kIPTransport] = false;
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/controller/SetUpCodePairer.cpp:280]: Good catch.  Also realized we need to set the boolean for BLE to false in `OnDiscoveredDeviceOverBle`.

File: src/controller/CHIPDeviceController.cpp [hunk 2]
```diff
@@ -812,7 +812,27 @@ void DeviceCommissioner::RendezvousCleanup(CHIP_ERROR status)
...
+        return;
+    }
+
+    // Reset mDeviceInPASEEstablishment because PairingFailed checks for that to
+    // send the right notifications.
+    mDeviceInPASEEstablishment = oldDeviceInPASEEstablishment;
+    PairingFailed(err);
+}
+
+void DeviceCommissioner::PairingFailed(CHIP_ERROR err)
```
Comment (tcarmelveilleux) [inline src/controller/CHIPDeviceController.cpp:834]: What is the difference between "Pairing" and "Session Establishment"? This is coupling the SetupCodePairer logic to an extent to the CHIPDeviceController...

There is really non-trivial state logic here.

Comment (bzbarsky-apple) [reply src/controller/CHIPDeviceController.cpp:834]: > What is the difference between "Pairing" and "Session Establishment"?

Fair question.  "Pairing" in this case means "all attempts to establish a session have failed and we have nothing else to try".  I am open to better suggestions.

> This is coupling the SetupCodePairer logic to an extent to the CHIPDeviceController...

They're already coupled pretty tightly...  I agree that ideally they would be decoupled entirely, but that is  much bigger project with a lot of risk of causing unintended problems, so seems like post-1.0 work at this point.

> There is really non-trivial state logic here.

Yes, including before this change...

Comment (tcarmelveilleux) [reply src/controller/CHIPDeviceController.cpp:834]: The coupling is very directional: CHIPDeviceController doesn't rely on SetupCodePairer, really (we use it without SetupCodePairer usage), but the opposite is not true.

Comment (bzbarsky-apple) [reply src/controller/CHIPDeviceController.cpp:834]: That doesn't change here, right?  There are APIs on `CHIPDeviceController` that end up calling into `SetUpCodePairer` and then that calls back into `CHIPDeviceController`.  With this change there can be more round-trips of that, but no fundamental difference.

If the APIs on `CHIPDeviceController` that call into `SetUpCodePairer` are never used, then there should be no difference in behavior, as long as we ensure that `TryNextRendezvousParameters` returns false in that situation.  Which I will make sure happens.

Comment (cecille) [reply src/controller/CHIPDeviceController.cpp:834]: One potentially incorrect case is if (for some strange reason), PairDevice is called with the setup code (BLE and IP). Device is discovered on IP and commissioned. Second PairDevice is called NOT through the setupcode pairer for a device on IP. If the PASE connection on #2 fails, I think TryNextRendezvousParameters will still return true because of the pending BLE from the first PairDevice call. 

That can be fixed, I believe, by calling ResetDiscoveryState when the pase connection is established.

Comment (cecille) [reply src/controller/CHIPDeviceController.cpp:834]: I do share Tennessee's concerns though - the more tightly we could these, the harder it gets to disentangle them at a later date.

**Review by tcarmelveilleux — APPROVED** [review]

File: src/controller/CHIPDeviceController.cpp (hunk 2 above)
Comment (tcarmelveilleux) [reply src/controller/CHIPDeviceController.cpp:834]: Approving assuming a follow-up comes to reduce the risk of SetUpCodePairer complex state hooks interfering with DeviceCommissioner users that don't want to rely on SetupCodePairer for their discovery attempts.
