### PR TITLE
[mdns] fix esp32 mdns publish error with platform implementation

### LINKED ISSUE #5076: esp-idf platform mDNS implementation fails at initialization
As of 27d3ea89f ("Make CHIP devices advertise as operational devices via mDNS (#4132)") we cannot use the esp-idf mDNS implementation.

This should be possible after 2c820d0f6 ("Add platform implementation for Advertiser (#4345)") but this is not working as there is an error at initialization:

```
E (677) chip[DL]: esp mdns internal error: ESP_ERR_INVALID_STATE
E (678) chip[DIS]: mDNS initialization failed with Error 4000172 (0x003D09AC)
E (681) chip[DIS]: Failed to initialize platform mdns: Error 4000172 (0x003D09AC)
I (690) spi_flash: detected chip: gd
```

Repro: Set chip_mdns_advertiser = "platform" and chip_enable_rotating_device_id = false for ESP32 build. Error shows at boot and the device cannot be discovered.

### PR DESCRIPTION
**Pull request by gjc13**
#### Problem
The mdns module cannot be initialized until the ESP32 is connected to
the wifi network.

 #### Summary of Changes

* Fix various build errors and warnings
* Move mdns initialization to `Start()`
* Advertise CHIP services in the server until the advertiser has been
  started

fixes https://github.com/project-chip/connectedhomeip/issues/5076

### CODE REVIEW

File: src/lib/mdns/Advertiser.h [hunk 1]
```diff
@@ -150,7 +150,7 @@ class ServiceAdvertiser
     virtual ~ServiceAdvertiser() {}
 
     /// Starts the advertiser. Items 'Advertised' will become visible.
-    /// May be called before OR after Advertise() calls.
+    /// Must be called before Advertise() calls.
```
Comment (andy31415) [inline src/lib/mdns/Advertiser.h:153]: This conflicts with the implementation in server/Mdns.cpp: there we do a Start followed by Advertise

File: src/lib/mdns/Discovery_ImplPlatform.cpp [hunk 2]
```diff
@@ -129,16 +139,15 @@ CHIP_ERROR DiscoveryImplPlatform::SetupHostname()
 {
     uint8_t mac[6];    // 6 byte wifi mac
     char hostname[13]; // Hostname will be the hex representation of mac.
-    CHIP_ERROR error;
+    CHIP_ERROR error = CHIP_NO_ERROR;
```
Comment (andy31415) [inline src/lib/mdns/Discovery_ImplPlatform.cpp:142]: can we delete this line and `return CHIP_NO_ERROR` as the final return instead?

**Review by andy31415 — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Review by mspang — APPROVED** [review]

File: src/lib/mdns/Discovery_ImplPlatform.cpp [hunk 3]
```diff
@@ -60,17 +61,26 @@ DiscoveryImplPlatform DiscoveryImplPlatform::sManager;
...
     mCommissionInstanceName = GetRandU64();
-    CHIP_ERROR error        = ChipMdnsInit(HandleMdnsInit, HandleMdnsError, this);
+}
+
+CHIP_ERROR DiscoveryImplPlatform::Start(Inet::InetLayer * inetLayer, uint16_t port)
+{
+    CHIP_ERROR error = CHIP_NO_ERROR;
+    if (!mMdnsInitialized)
+    {
+        ChipMdnsInit(HandleMdnsInit, HandleMdnsError, this);
```
Comment (bzbarsky-apple) [inline src/lib/mdns/Discovery_ImplPlatform.cpp:71]: Why are we no longer checking the return value here?

File: src/lib/mdns/Discovery_ImplPlatform.cpp [hunk 4]
```diff
@@ -108,19 +119,18 @@ void DiscoveryImplPlatform::HandleMdnsError(void * context, CHIP_ERROR error)
 }
 
 #if CHIP_ENABLE_ROTATING_DEVICE_ID
-static CHIP_ERROR DiscoveryImplPlatform::GenerateRotatingDeviceId(char rotatingDeviceIdHexBuffer[],
-                                                                  size_t & rotatingDeviceIdHexBufferSize)
+CHIP_ERROR DiscoveryImplPlatform::GenerateRotatingDeviceId(char rotatingDeviceIdHexBuffer[], size_t & rotatingDeviceIdHexBufferSize)
```
Comment (bzbarsky-apple) [inline src/lib/mdns/Discovery_ImplPlatform.cpp:122]: Why this change?

**Review by bzbarsky-apple — DISMISSED** [review]

**Review by kedars — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]
