### PR TITLE
Check if SSID and BSSID properties were fetched

### LINKED ISSUE #22929: [BUG] Linux: _GetBssInfo tries to get properties of not available network
### Reproduction steps

```bash
1. Run lighting app with wifi enabled: ./chip-lighting-app --wifi
2. Commission with chip-tool: pairing ble-wifi ...
3. When networks are scanned there is lots of GLib warnings:
(process:13679): GLib-CRITICAL **: 15:09:11.661: g_variant_get_type: assertion 'value != NULL' failed

(process:13679): GLib-CRITICAL **: 15:09:11.662: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed

(process:13679): GLib-CRITICAL **: 15:09:11.662: g_variant_get_fixed_array: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_ARRAY)' failed

(process:13679): GLib-CRITICAL **: 15:09:11.662: g_variant_get_type: assertion 'value != NULL' failed

(process:13679): GLib-CRITICAL **: 15:09:11.662: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed

(process:13679): GLib-CRITICAL **: 15:09:11.662: g_variant_get_fixed_array: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_ARRAY)' failed
...
```

### Bug prevalence

always

### GitHub hash of the SDK that was being used

f2cd15fd76ccda8aa42abbedbcf971fe0b2da349

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by arkq**
Network scan is performed in the background by wpa_supplicant. When we are trying to get BSS properties, the BSS may be already gone. This patch prevents passing NULL to g_variant_get_fixed_array().

#### Issue Being Resolved
* Fixes #22929 

#### Change overview
- check for nullptr when getting properties

### CODE REVIEW

File: src/platform/Linux/ConnectivityManagerImpl.cpp [hunk 1]
```diff
@@ -1549,6 +1549,13 @@ bool ConnectivityManagerImpl::_GetBssInfo(const gchar * bssPath, NetworkCommissi
     std::unique_ptr<GVariant, GVariantDeleter> ssid(g_dbus_proxy_get_cached_property(G_DBUS_PROXY(bssProxy), "SSID"));
     std::unique_ptr<GVariant, GVariantDeleter> bssid(g_dbus_proxy_get_cached_property(G_DBUS_PROXY(bssProxy), "BSSID"));
 
+    // Network scan is performed in the background, so the BSS
+    // may be gone when we try to get the properties.
+    if (ssid == nullptr || bssid == nullptr)
+    {
+        return false;
```
Comment (andy31415) [inline src/platform/Linux/ConnectivityManagerImpl.cpp:1556]: should we log something if this happens? Although there is no logging on null bss either.

**Review by andy31415 — APPROVED** [review]

File: src/platform/Linux/ConnectivityManagerImpl.cpp (hunk 1 above)
Comment (Arkq) [reply src/platform/Linux/ConnectivityManagerImpl.cpp:1557]: Log message added.

> Although there is no logging on null bss either.

NULL bss would be caused out-of-memory (I think) or some programmer error. The `wpa_fi_w1_wpa_supplicant1_bss_proxy_new_for_bus_sync` only creates and initializes GLib object.
