### PR TITLE
Check WPA supplicant state before saving config

### LINKED ISSUE #22894: [Platform] Calling wpa_fi_w1_wpa_supplicant1_... on nullptr iface
### Reproduction steps

```bash
1. Try to commission Linux lighting app with removed WiFi interface: ./out/linux-x64-light/chip-lighting-app
2. Run network commissioning on other host: chip-tool pairing onnetwork 1 20202021
3. chip-lighting-app output:
...
[1664268290.126647][182494:182494] CHIP:DL: writing settings to file (/tmp/chip_kvs-lH0pGx)
[1664268290.126809][182494:182494] CHIP:DL: renamed tmp file to file (/tmp/chip_kvs)
[1664268290.126826][182494:182494] CHIP:DL: wpa_supplicant: connected to network

(process:182494): GLib-GIO-CRITICAL **: 10:44:50.126: g_dbus_proxy_call_sync_internal: assertion 'G_IS_DBUS_PROXY (proxy)' failed
```

### Platform

other

### Platform Version(s)

f2cd15fd76ccda8aa42abbedbcf971fe0b2da349

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by arkq**
### Issue Being Resolved
* Fixes #22894 

### Change overview
- check if iface is connected before saving config

### Testing

Tested locally with BLE commissionig:

```
./chip-lighting-app
....
CHIP:NP: LinuxWiFiDriver: SSID: MatterWiFi
CHIP:NP: Failed to connect to WiFi network: ../../examples/lighting-app/linux/third_party/connectedhomeip/src/platform/Linux/ConnectivityManagerImpl.cpp:970: CHIP Error 0x00000003: Incorrect state 
CHIP:DMG: Command handler moving to [ Preparing]
...
```

```
./chip-lighting-app --wifi
....
CHIP:NP: LinuxWiFiDriver: SSID: MatterWiFi
CHIP:DL: wpa_supplicant: added network: /fi/w1/wpa_supplicant1/Interfaces/0/Networks/0
CHIP:DMG: Decreasing reference count for CommandHandler, remaining 1
CHIP:DL: wpa_supplicant: failed to save config: GDBus.Error:fi.w1.wpa_supplicant1.UnknownError: Not allowed to update configuration (update_config=0)
CHIP:DL: wpa_supplicant:PropertiesChanged:key:State -> 'scanning'
...
```

### CODE REVIEW

File: src/platform/Linux/ConnectivityManagerImpl.cpp [hunk 1]
```diff
@@ -1223,7 +1223,13 @@ CHIP_ERROR ConnectivityManagerImpl::CommitConfig()
     gboolean result;
     std::unique_ptr<GError, GErrorDeleter> err;
 
-    ChipLogProgress(DeviceLayer, "wpa_supplicant: connected to network");
```
Comment (yufengwangca) [inline src/platform/Linux/ConnectivityManagerImpl.cpp:1226]: we should keep this log to indicate if the network has been connected

Comment (Arkq) [reply src/platform/Linux/ConnectivityManagerImpl.cpp:1226]: I've removed it because I thought that it was a typo. Are you sure that the `CommitConfig` is the right place for such message? Such message is here: https://github.com/project-chip/connectedhomeip/blob/956ead0324558d02fe5d6b55f460678080e00125/src/platform/Linux/ConnectivityManagerImpl.cpp#L1123

Comment (andy31415) [reply src/platform/Linux/ConnectivityManagerImpl.cpp:1226]: Maybe log should say something like "ConnectivityManagerImpl::CommitConfig" since I do not acutally see wpa_supplicant specific things here. We will save config synchronously, so maybe even log "wpa_supplicant: will save config synchronously" or similar.

Comment (Arkq) [reply src/platform/Linux/ConnectivityManagerImpl.cpp:1226]: > since I do not acutally see wpa_supplicant specific things here

Yeap, that was my reasoning behind removing this line. OK, I can replace this message with a more suitable one.

Comment (Arkq) [reply src/platform/Linux/ConnectivityManagerImpl.cpp:1226]: I've added "wpa_supplicant: save config" log message (save config is wpa_supplicant specific).

**Review by andy31415 — APPROVED** [review]

**Review by yufengwangca — APPROVED** [review]

File: src/platform/Linux/ConnectivityManagerImpl.cpp [hunk 2]
```diff
@@ -962,6 +962,7 @@ ConnectivityManagerImpl::ConnectWiFiNetworkAsync(ByteSpan ssid, ByteSpan credent
 
     VerifyOrReturnError(ssid.size() <= kMaxWiFiSSIDLength, CHIP_ERROR_INVALID_ARGUMENT);
     VerifyOrReturnError(credentials.size() <= kMaxWiFiKeyLength, CHIP_ERROR_INVALID_ARGUMENT);
+    VerifyOrReturnError(mWpaSupplicant.iface != nullptr, CHIP_ERROR_INCORRECT_STATE);
```
Comment (bzbarsky-apple) [inline src/platform/Linux/ConnectivityManagerImpl.cpp:965]: Why don't we need to lock `mWpaSupplicantMutex` before doing this check?

File: src/platform/webos/ConnectivityManagerImpl.cpp [hunk 3]
```diff
@@ -935,6 +935,7 @@ ConnectivityManagerImpl::ConnectWiFiNetworkAsync(ByteSpan ssid, ByteSpan credent
 
     VerifyOrReturnError(ssid.size() <= kMaxWiFiSSIDLength, CHIP_ERROR_INVALID_ARGUMENT);
     VerifyOrReturnError(credentials.size() <= kMaxWiFiKeyLength, CHIP_ERROR_INVALID_ARGUMENT);
+    VerifyOrReturnError(mWpaSupplicant.iface != nullptr, CHIP_ERROR_INCORRECT_STATE);
```
Comment (bzbarsky-apple) [inline src/platform/webos/ConnectivityManagerImpl.cpp:938]: Again, why doesn't this require taking the mutex?

Comment (Arkq) [reply src/platform/webos/ConnectivityManagerImpl.cpp:938]: To be honest I'm not sure about the mutex. There are more functions in there where the `mWpaSupplicant.iface` is used without mutex. I can add mutex locks in all that places, run linux test suite and see whether there will ne no deadlocks.

Comment (bzbarsky-apple) [reply src/platform/webos/ConnectivityManagerImpl.cpp:938]: I think we need to figure out what state the mutex is meant to protect and document that, so it's clear when the mutex needs to be locked...

Comment (Arkq) [reply src/platform/webos/ConnectivityManagerImpl.cpp:938]: Currently I'm trying to incorporate Clang Thread Safety Analysis for this. As I long run I think that we might use this tool in all places where locking is used. Unfortunately, this tool does not show double locks in the same thread if e.g. `funcA` locks mutex and `funcB` locks the same mutex, and in the code we've got `funcA` calling `funcB`. But still, I think it might be very useful for locking analysis.

> I think we need to figure out what state the mutex is meant to protect and document that

OK, I'll try to do that. And speaking of documentation, this clang thread-safety extension might be a great tool for documentation as well - all variables which need locking will have to be correctly annotated with corresponding mutex.

File: src/platform/Linux/ConnectivityManagerImpl.cpp (hunk 2 above)
Comment (arkq) [reply src/platform/Linux/ConnectivityManagerImpl.cpp:970]: I've added missing lock.

**Review by andy31415 — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
