### PR TITLE
Remove GroupKeyMap entries for removed KeySet

### LINKED ISSUE #23862: [BUG] Removing a GroupKeySet does not removing the corresponding mapping
### Reproduction steps

```bash
- label: "TH sends KeySetWrite command with TH key"
      cluster: "Group Key Management"
      endpoint: 0
      command: "KeySetWrite"
      arguments:
        values:
            - name: GroupKeySet
              value: {
                        GroupKeySetID: 0x01a3,
                        GroupKeySecurityPolicy: 0,
                        EpochKey0: "0xd0d1d2d3d4d5d6d7d8d9dadbdcdddedf",
                        EpochStartTime0: 2220000,
                        EpochKey1: "0xd1d1d2d3d4d5d6d7d8d9dadbdcdddedf",
                        EpochStartTime1: 2220001,
                        EpochKey2: "0xd2d1d2d3d4d5d6d7d8d9dadbdcdddedf",
                        EpochStartTime2: 2220002,
                     }
    - label: "TH binds GroupId to GroupKeySet"
      cluster: "Group Key Management"
      endpoint: 0
      command: "writeAttribute"
      attribute: "GroupKeyMap"
      arguments:
        value: [
                  {
                    FabricIndex: 1,
                    GroupId: 0x0103,
                    GroupKeySetID: 0x01a3,
                  },
               ]

    - label: "TH removes the GroupKeySet"
      cluster: "Group Key Management"
      endpoint: 0
      command: "KeySetRemove"
      arguments:
        values:
          - name: GroupKeySetID
            value: 0x01a3

    - label: "TH verifies the corresponding GroupKeyMap entry has been removed"
      cluster: "Group Key Management"
      endpoint: 0
      command: "readAttribute"
      attribute: "GroupKeyMap"
      response:
        value: []
```

### Bug prevalence

always

### GitHub hash of the SDK that was being used

0493fc32aef12c254ded406815142835674fadaf (ToT dec 1)

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

SDK problem is in the GroupDataProviderImpl. Will make changes before submitting changes to SC test plans / automation.

### PR DESCRIPTION
**Pull request by cecille**
Per Core spec 11.2.9.4, If there exist any entries for the accessing fabric within the GroupKeyMap attribute that refer to the GroupKeySetID just removed, then these entries SHALL be removed from that list.

Fixes #23862

### CODE REVIEW

File: src/credentials/GroupDataProviderImpl.cpp [hunk 1]
```diff
@@ -495,6 +495,37 @@ struct KeyMapData : public GroupDataProvider::GroupKey, LinkedData
         id = static_cast<uint16_t>(max_id + 1);
         return false;
     }
+
+    // returns index if the find_idx is found, otherwise std::numeric_limits<size_t>::max
```
Comment (bzbarsky-apple) [inline src/credentials/GroupDataProviderImpl.cpp:499]:
```suggestion
    // returns index if the find_id is found, otherwise std::numeric_limits<size_t>::max
```

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
