### PR TITLE
Don't mark session defunct on response timeout if the message was acked.

### LINKED ISSUE #29165: [BUG] Marking sessions defunct on exhange timeout should probably not happen if the message was acked
### Reproduction steps

If we send a message and:

1. We get an MRP ack for it.
2. We do not get an application-level response for it in time

we will go ahead and mark the session as defunct.  But the session seemed to be fine: we got an ack and decrypted it!

So we should probably not mark the session defunct in this situation.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

5ae3c657a8f17582d1af0c8abc9a8642c7185ad2

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
If we got an ack, the session is fine and there is no reason to mark it defunct.

Fixes https://github.com/project-chip/connectedhomeip/issues/29165

### CODE REVIEW

File: src/messaging/ReliableMessageMgr.cpp [hunk 1]
```diff
@@ -154,6 +157,13 @@ void ReliableMessageMgr::ExecuteActions()
 
             // Do not StartTimer, we will schedule the timer at the end of the timer handler.
             mRetransTable.ReleaseObject(entry);
+
+            // That marked the exchange as not having an un-acked message... but
```
Comment (tcarmelveilleux) [inline src/messaging/ReliableMessageMgr.cpp:161]: What is "that" here?

**Review by tcarmelveilleux — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]

File: src/messaging/ReliableMessageMgr.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/messaging/ReliableMessageMgr.cpp:161]: The ReleaseObject call.  I'll make that clearer.

**Review by saurabhst — APPROVED** [review]
