### PR TITLE
Fix CATValues == operator

### LINKED ISSUE #20252: CATValues == operator incorrect
#### Problem

CATValues == operator considers equality by position in the contained values std::array.  However, CATs are not positional.

 #### Proposed Solution

Fix the == operator to consider CATValues equal if both a,b contain the same values in any order.

CC @kghost , @bzbarsky-apple

### PR DESCRIPTION
**Pull request by msandstedt**
#### Problem

CATValues == was using std::array equality, but this considers order of the data, which is not relevant for CATs.

#### Change overview

Fix CATValues equality by sorting entries first before evaluating.  Also add != and < operators for convenience.

Fixes #20252 

#### Testing

Added unit tests for the new and corrected operators.

### CODE REVIEW

File: src/lib/core/tests/TestCATValues.cpp [hunk 1]
```diff
@@ -0,0 +1,176 @@
+/*
+ *
+ *    Copyright (c) 2022 Project CHIP Authors
+ *    Copyright (c) 2013-2017 Nest Labs, Inc.
```
Comment (tcarmelveilleux) [inline src/lib/core/tests/TestCATValues.cpp:4]:
```suggestion
```

File: src/lib/core/tests/TestCATValues.cpp [hunk 2]
```diff
@@ -0,0 +1,176 @@
...
+ *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ *    See the License for the specific language governing permissions and
+ *    limitations under the License.
+ */
+
+/**
+ *    @file
+ *      This file implements unit tests for the CHIP TLV implementation.
+ *
+ */
```
Comment (tcarmelveilleux) [inline src/lib/core/tests/TestCATValues.cpp:24]:
```suggestion
```

File: src/lib/core/tests/TestCATValues.cpp [hunk 3]
```diff
@@ -0,0 +1,176 @@
...
+
+#include <lib/support/UnitTestRegistration.h>
+#include <nlbyteorder.h>
```
Comment (tcarmelveilleux) [inline src/lib/core/tests/TestCATValues.cpp:27]:
```suggestion
```

File: src/lib/core/CASEAuthTag.h [hunk 4]
```diff
@@ -84,6 +87,16 @@ struct CATValues
...
     }
+
+private:
+    static bool Cmp(const CASEAuthTag & a, const CASEAuthTag & b) { return a < b; }
+    void Sort() { Sorting::BubbleSort(this->values.begin(), this->size(), Cmp); }
+    CATValues Sorted() const
+    {
+        auto sorted = *this;
+        sorted.Sort();
+        return sorted;
```
Comment (tcarmelveilleux) [inline src/lib/core/CASEAuthTag.h:98]: How frequently must this be done?

It's not "super" expensive, but it's expensive if we do it all the time.

std::sort() and quicksort() have special casing in most implementations that uses sorting networks for small arrays (e.g. arrays of 3 values), which is very and costs very little since already used in other parts of the system as well (usually)

File: src/lib/core/CASEAuthTag.h [hunk 5]
```diff
@@ -84,6 +87,16 @@ struct CATValues
         }
         return CHIP_NO_ERROR;
     }
+
+private:
+    static bool Cmp(const CASEAuthTag & a, const CASEAuthTag & b) { return a < b; }
+    void Sort() { Sorting::BubbleSort(this->values.begin(), this->size(), Cmp); }
+    CATValues Sorted() const
+    {
+        auto sorted = *this;
```
Comment (tcarmelveilleux) [inline src/lib/core/CASEAuthTag.h:96]: The invariant at line 52/53 is broken by sorting:

```
    // All valid CAT values are always in the beginning of the array followed by kUndefinedCAT values.
    ReturnErrorCodeIf(cat == kUndefinedCAT, false);
```

File: src/lib/core/CASEAuthTag.h (hunk 4 above)
Comment (msandstedt) [reply src/lib/core/CASEAuthTag.h:98]: Yes, normally I would prefer to use std::sort or qsort.  But std::sort() was explicitly rejected in another PR, and I think it was shown in the increases report that it was being used for the first time in many builds when it was considered for introduction.  So bubble sort was added to our libs, and I am using that to avoid any increase in flash.  I won't argue what is optimal.  I am following the result of the prior discussion.

However, for performance, I think the big problem here is that: 1) we need to sort every time we need one of these operators, and 2) we need to push 192 bytes on the stack to do it.  Because we can't sort in place.

I will fix those two problems.  Actually this seems related to your other comment here: https://github.com/project-chip/connectedhomeip/pull/20253#discussion_r912555429

File: src/lib/core/CASEAuthTag.h (hunk 5 above)
Comment (msandstedt) [reply src/lib/core/CASEAuthTag.h:96]: There appears to be nothing at all in this object that enforces this in the first place.

I think I will do a reverse sort in the constructor to make this _actually_ guaranteed.  That should cleanly solve everything at once.

File: src/lib/core/tests/TestCATValues.cpp (hunk 1 above)
Comment (msandstedt) [reply src/lib/core/tests/TestCATValues.cpp]: I wasn't sure if there was some claim about copying the NL boilerplate we have in all the tests.  But I think there is sufficient atribution in the NL headers.

Thanks, applied.

File: src/lib/core/CASEAuthTag.h (hunk 5 above)
Comment (msandstedt) [reply src/lib/core/CASEAuthTag.h:96]: Ah, I see we can't do this because we are transcribing directly to and from certificates and ordering _does_ matter for the signature.  And this is apparently where the promise that kUndefinedCAT will appear at the end of the array is realized.

Also, the code seems to be pretty set on CATValues being an aggregate.

I'll stick to the original approach, but with reverse ordering for the temporary arrays, and audit to see how often we actually use the equality operator.  Hopefully not often.

Comment (msandstedt) [reply src/lib/core/CASEAuthTag.h:96]: > This means that after sorting, iteration may fail and CheckSubjectAgainstCATs may iterate less entries (or none?)

Ah, OK.  So the thing is that the Sorted arrays are only temporary and only used for comparison.  And per the above, we can't sort in place anyway because inside the certificate, order _does_ matter.

For this reason, this approach actually doesn't break anything.  Is there anything beyond making these methods private that I can do to address your concern?

Here is where we are using the comparison:

```
../src/transport/SecureSessionTable.h:114:43: error: no match for ‘operator==’ (operand types are ‘const chip::CATValues’ and ‘const chip::CATValues’)
  114 |                 oldSession->GetPeerCATs() == session->GetPeerCATs())
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~~~~~~~~~~
      |                                        |                         |
      |                                        const chip::CATValues     const chip::CATValues
```

We don't compare these often, but where we do, the comparison is broken as I have claimed.  So a fix is needed.

File: src/lib/core/CASEAuthTag.h [hunk 6]
```diff
@@ -60,7 +60,54 @@ struct CATValues
         return false;
     }
 
-    bool operator==(const CATValues & that) const { return values == that.values; }
+    bool operator==(const CATValues & that) const
+    {
+        // Two sets of CATs confer equal permissions if for each defined value
+        // in one set, a corresponding value exists in the other set.  If this
+        // is true, we consider the sets equal.
```
Comment (msandstedt) [inline src/lib/core/CASEAuthTag.h:67]:
```suggestion
        // Two sets of CATs confer equal permissions if the sets are exactly equal.
        // Ignoring kUndefinedCAT values, evaluate this.
```

**Comment by msandstedt** [comment]
Move to draft.  We have discovered that the ability to populate duplicate CAT RDNs breaks CAT versioning.

Holding off on this until we have clarity in the spec.

File: src/lib/core/CASEAuthTag.h (hunk 5 above)
Comment (msandstedt) [reply src/lib/core/CASEAuthTag.h]: Collaborated on a solution, which is now merged into this branch.

**Review by tcarmelveilleux — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]
