### PR TITLE
Apply ColorTempPhysicalMaxMireds when ColorTemperatureMaximumMireds f…

### LINKED ISSUE #33903: [BUG] Incorrect handling of MoveColorTemperature and StepColorTemperature when ColorTemperatureMaximum is 0
### Reproduction steps

We have found the issue regarding MoveColorTemperature and StepColorTemperature. If the light receives the above command and ColorTemperatureMaximum is 0, the light will not take any action. The light should adjust its color temperature value according to the spec description.
```
ColorTemperatureMinimumMireds Field
If the ColorTemperatureMinimumMireds field is set to 0, ColorTempPhysicalMinMireds SHALL 
be used as the lower bound for the ColorTemperatureMireds attribute.

ColorTemperatureMaximumMireds Field
If the ColorTemperatureMaximum Mireds field is set to 0, ColorTempPhysicalMaxMireds 
SHALL be used as the upper bound for the ColorTemperatureMireds attribute.
```
But the SDK currently does not handle ColorTemperatureMaximum is 0.
https://github.com/project-chip/connectedhomeip/blob/master/src/app/clusters/color-control-server/color-control-server.cpp#L2700
https://github.com/project-chip/connectedhomeip/blob/master/src/app/clusters/color-control-server/color-control-server.cpp#L2811

### Bug prevalence

100%

### GitHub hash of the SDK that was being used

d83caf7fefeaa91ebc549863552050311abe46ae

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jmartinez-silabs**
…ield is 0 for `MoveColorTemperature` and `StepColorTemperature` commands.

Add test steps to TC_CC_6.2 and TC_CC_6.3 to validate the behaviour (tied with test plan pr [4235](https://github.com/CHIP-Specifications/chip-test-plans/pull/4235))

fixes #33903

### CODE REVIEW

**Review by yufengwangca — APPROVED** [review]

File: src/app/clusters/color-control-server/color-control-server.cpp [hunk 1]
```diff
@@ -2697,7 +2697,7 @@ bool ColorControlServer::moveColorTempCommand(app::CommandHandler * commandObj,
     {
         colorTemperatureMinimum = tempPhysicalMin;
     }
-    if (colorTemperatureMaximum > tempPhysicalMax)
+    if ((colorTemperatureMaximum == 0) || (colorTemperatureMaximum > tempPhysicalMax))
```
Comment (bzbarsky-apple) [inline src/app/clusters/color-control-server/color-control-server.cpp:2700]: The cited issue talks about the min temperature too, no?  Why is this PR only changing the maximum?

Comment (jmartinez-silabs) [reply src/app/clusters/color-control-server/color-control-server.cpp:2700]: The min temperature is already covered by the existing if condition  as tempPhysicalMin cannot be lower than 0 anyway
```
if (colorTemperatureMinimum < tempPhysicalMin)
{
        colorTemperatureMinimum = tempPhysicalMin;
}
```

The issue only applied to `colorTemperatureMaximum` since the check was greater than only ence not catching the 0 condition.

Comment (bzbarsky-apple) [reply src/app/clusters/color-control-server/color-control-server.cpp:2700]: It might be worth noting in a code comment that the spec requirement around `colorTemperatureMinimum == 0` is handled by the fact that `tempPhysicalMin >= 0`.

**Review by bzbarsky-apple — APPROVED** [review]
