### PR TITLE
Fix the move-to-level max level value accepted by the command handler

### LINKED ISSUE #17380: Level control min and max level issue
#### Problem
In level-control.cpp, the min and max levels are defined as shown below
`#define LEVEL_CONTROL_LIGHTING_MIN_LEVEL 0x01`
`#define LEVEL_CONTROL_LIGHTING_MAX_LEVEL 0xFE`

However, chip-tool allows level to be 0 and 255
`./chip-tool levelcontrol move-to-level-with-on-off 255 0 1234 1`
`./chip-tool levelcontrol move-to-level-with-on-off 0 0 1234 1`

### PR DESCRIPTION
**Pull request by jmartinez-silabs**
#### Problem
fixes #17380 

#### Change overview
Limit move to level commands to a level value of 254, else error out the command

#### Testing
Build lighting-app on EFR32.
`chip-tool levelcontrol move-to-level 254 100 0xff 0xff 23813 1 ` returns success
`chip-tool levelcontrol move-to-level 254 100 0xff 0xff 23813 1 ` returns `Run command failure: IM Error 0x00000580: General error: 0x80 (INVALID_ACTION)`
`chip-tool levelcontrol move-to-level-with-on-off 254 100 23813 1` returns success
`chip-tool levelcontrol move-to-level-with-on-off 255 100 23813 1` return `Run command failure: IM Error 0x00000580: General error: 0x80 (INVALID_ACTION)`

### CODE REVIEW

File: src/app/clusters/level-control/level-control.cpp [hunk 1]
```diff
@@ -520,6 +520,11 @@ static EmberAfStatus moveToLevelHandler(EndpointId endpoint, CommandId commandId
         return EMBER_ZCL_STATUS_FAILURE;
     }
 
+    if (level > EMBER_AF_PLUGIN_LEVEL_CONTROL_MAXIMUM_LEVEL)
+    {
+        return EMBER_ZCL_STATUS_MALFORMED_COMMAND;
```
Comment (tcarmelveilleux) [inline src/app/clusters/level-control/level-control.cpp:525]: For commands, I think it should be EMBER_ZCL_STATUS_INVALID_COMMAND. `EMBER_ZCL_STATUS_MALFORMED_COMMAND` is INVALID_ACTION in Matter. When data is out of bounds for a field, it would be INVALID_COMMAND I think.

Right now, MALFORMED_COMMAND is used only in LevelControl and Scenes server for commands, and otherwise is used in IM handler for attributes. INVALID_COMMAND/InvalidCommand is used much more places.

Strongly suggest moving this to INVALID_COMMAND and updating usage, since this error is not Matter compliant in the context AFAIK

Comment (jmartinez-silabs) [reply src/app/clusters/level-control/level-control.cpp:525]: Sure I can change it to EMBER_ZCL_STATUS_INVALID_COMMAND.

**Review by andy31415 — APPROVED** [review]

**Review by tcarmelveilleux — APPROVED** [review]

**Review by selissia — APPROVED** [review]
