### PR TITLE
Multiple spec compliance fixes to NOC cluster

### LINKED ISSUE #15311: AddTrustedRootCertificate without AddNOC is broken
#### Problem
AddTrustedRootCertificate sets the new root cert in `gFabricBeingCommissioned`... but then nothing ever happens to get it anywhere else.  This means:

1) If we never make an AddNOC call, the new root cert will never get added to the list in any way.
2) Until we make an AddNOC call the root cert list as viewed by the attribute will not show the new root.  Which also means our MatterReportingAttributeChangeCallback call there is nonsense.

 #### Proposed Solution
Implement something closer to the spec.

### LINKED ISSUE #17209: Add/RemoveTrustedRootCertificate must be updated to match latest spec
#### Problem
The `RemoveTrustedRootCertificate` handler in the SDK does not seem to work at all.

By inspecting the code, we find:

```
// TODO: Implement the logic for RemoveTrustedRootCertificate
    EmberAfStatus status = EMBER_ZCL_STATUS_FAILURE;
    emberAfSendImmediateDefaultResponse(status);
```

 #### Proposed Solution
Fix the logic of RemoveTrustedRootCertificate to follow spec. This is symmetrical to #17208

### PR DESCRIPTION
**Pull request by tcarmelveilleux**
#### Problem  
- A lot of error-handling in NOC cluster is not spec-compliant with too many different situations to list individually.
- The RemoveTrustedRootCertificate command no longer exisets
- There is missing interlock between the fail-safe and AddNOC/UpdateNOC/AddTrustedRootCertificate/CSRRequest

Issue #18633
Fixes #15311
Fixes #17209

#### Change overview
- Add all missing IM-level checks that would lead to
  INVALID_COMMAND error on incorrectly provided inputs
- Normalize logging of errors some more
- Add missing interlocks on fail-safe
- Remove RemoveTrustedRootCertificate command
- Ensure error-handling in AddTrustedRootCertificate
  does not destroy in-progress state on innocuous errors
- Move some IM structural checks before fail-safe checks
  in AddNOC/UpdateNOC

#### Testing
- Unit tests pass
- Cert tests pass
- Added YAML tests for the AddNOC/UpdateNOC/CSRRequest/AddTrustedRootCertificate handling of being called outside fail-safe

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by emargolis — APPROVED** [review]

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 1]
```diff
@@ -991,33 +1031,43 @@ bool emberAfOperationalCredentialsClusterCSRRequestCallback(app::CommandHandler
...
-        SuccessOrExit(err = gFabricBeingCommissioned.SetOperationalKeypair(&keypair));
+        err = gFabricBeingCommissioned.SetOperationalKeypair(&keypair);
+        VerifyOrExit(err == CHIP_NO_ERROR, finalStatus = Status::Failure);
 
         // Generate the actual CSR from the ephemeral key
-        VerifyOrExit(csr.Alloc(csrLength), err = CHIP_ERROR_NO_MEMORY);
+        if (!csr.Alloc(csrLength))
+        {
+            err = CHIP_ERROR_NO_MEMORY;
+            VerifyOrExit(err == CHIP_NO_ERROR, finalStatus = Status::Failure);
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:1041]: Followup: This should be Status::ResourceExhausted.

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 2]
```diff
@@ -890,55 +912,73 @@ bool emberAfOperationalCredentialsClusterAttestationRequestCallback(app::Command
...
     attestationElementsLen = TLV::EstimateStructOverhead(certDeclSpan.size(), attestationNonce.size(), sizeof(uint64_t) * 8);
 
-    VerifyOrExit(attestationElements.Alloc(attestationElementsLen), err = CHIP_ERROR_NO_MEMORY);
-    attestationElementsSpan = MutableByteSpan{ attestationElements.Get(), attestationElementsLen };
-    SuccessOrExit(err = Credentials::ConstructAttestationElements(certDeclSpan, attestationNonce, timestamp, kEmptyFirmwareInfo,
-                                                                  emptyVendorReserved, attestationElementsSpan));
+    if (!attestationElements.Alloc(attestationElementsLen))
+    {
+        err = CHIP_ERROR_NO_MEMORY;
+        VerifyOrExit(err == CHIP_NO_ERROR, finalStatus = Status::Failure);
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:951]: Followup: this should be Status::ResourceExhausted.

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 3]
```diff
@@ -991,33 +1031,43 @@ bool emberAfOperationalCredentialsClusterCSRRequestCallback(app::CommandHandler
...
         nocsrLengthEstimate = TLV::EstimateStructOverhead(csrLength,       // CSR buffer
                                                           CSRNonce.size(), // CSR Nonce
                                                           0u               // no vendor reserved data
         );
 
-        VerifyOrExit(nocsrElements.Alloc(nocsrLengthEstimate), err = CHIP_ERROR_NO_MEMORY);
+        if (!nocsrElements.Alloc(nocsrLengthEstimate))
+        {
+            err = CHIP_ERROR_NO_MEMORY;
+            VerifyOrExit(err == CHIP_NO_ERROR, finalStatus = Status::Failure);
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:1063]: Followup: ResourceExhausted

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 4]
```diff
@@ -1052,51 +1107,57 @@ bool emberAfOperationalCredentialsClusterAddTrustedRootCertificateCallback(
...
-    // TODO: Implement the logic for RemoveTrustedRootCertificate
-    EmberAfStatus status = EMBER_ZCL_STATUS_FAILURE;
-    emberAfSendImmediateDefaultResponse(status);
-
+    // Got here, so we succeeded, mark AddTrustedRootCert has having been invoked.
+    ChipLogProgress(Zcl, "OpCreds: AddTrustedRootCertificate successful.");
+    finalStatus = Status::Success;
+    failSafeContext.SetAddTrustedRootCertInvoked();
     MatterReportingAttributeChangeCallback(commandPath.mEndpointId, OperationalCredentials::Id,
                                            OperationalCredentials::Attributes::TrustedRootCertificates::Id);
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:1151]: Followup issue for a pre-existing problem, please: Since we have not actually added this to the fabric table, this is going to actually send the wrong value to subscribers.  Need to think about how to address that...

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 5]
```diff
@@ -1052,51 +1107,57 @@ bool emberAfOperationalCredentialsClusterAddTrustedRootCertificateCallback(
...
 
+exit:
+    // If failed constraints or internal errors, send a status report instead of the response sent above
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:1154]: There is no "response sent above".  Please fix this comment to reflect the actual code here.  Followup OK for this.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 6]
```diff
@@ -469,7 +470,15 @@ bool emberAfOperationalCredentialsClusterRemoveFabricCallback(app::CommandHandle
     MATTER_TRACE_EVENT_SCOPE("RemoveFabric", "OperationalCredentials");
     auto & fabricBeingRemoved = commandData.fabricIndex;
 
-    ChipLogProgress(Zcl, "OpCreds: Received a RemoveFabric Command");
+    ChipLogProgress(Zcl, "OpCreds: Received a RemoveFabric Command for FabricIndex 0x%x",
+                    static_cast<unsigned>(fabricBeingRemoved));
+
+    if ((fabricBeingRemoved < 1) || (fabricBeingRemoved > 254))
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:476]: Well, the constraint about fabric index values is expressed elsewhere... I will add it to the spec, see https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/5332

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 7]
```diff
@@ -520,29 +532,36 @@ bool emberAfOperationalCredentialsClusterUpdateFabricLabelCallback(app::CommandH
                                                                    const Commands::UpdateFabricLabel::DecodableType & commandData)
 {
     MATTER_TRACE_EVENT_SCOPE("UpdateFabricLabel", "OperationalCredentials");
-    auto & Label        = commandData.label;
+    auto & label        = commandData.label;
     auto ourFabricIndex = commandObj->GetAccessingFabricIndex();
 
     ChipLogProgress(Zcl, "OpCreds: Received an UpdateFabricLabel command");
 
+    if ((label.size() < 1) || (label.size() > 32))
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:540]: Fixed

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 8]
```diff
@@ -779,21 +801,20 @@ bool emberAfOperationalCredentialsClusterUpdateNOCCallback(app::CommandHandler *
...
-
+    VerifyOrExit(NOCValue.size() <= Credentials::kMaxCHIPCertLength, nonDefaultStatus = Status::InvalidCommand);
+    VerifyOrExit(!ICACValue.HasValue() || ICACValue.Value().size() <= Credentials::kMaxCHIPCertLength,
+                 nonDefaultStatus = Status::InvalidCommand);
     VerifyOrExit(failSafeContext.IsFailSafeArmed(commandObj->GetAccessingFabricIndex()),
                  nonDefaultStatus = Status::UnsupportedAccess);
 
     VerifyOrExit(!failSafeContext.NocCommandHasBeenInvoked(), nonDefaultStatus = Status::ConstraintError);
 
+    // Fetch current fabric. If not available, command was invoked over PASE which is not legal
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:814]: Fixed

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 9]
```diff
@@ -654,23 +673,26 @@ bool emberAfOperationalCredentialsClusterAddNOCCallback(app::CommandHandler * co
...
-
-    VerifyOrExit(NOCValue.size() <= 400, nonDefaultStatus = Status::InvalidCommand);
-
-    VerifyOrExit(!ICACValue.HasValue() || ICACValue.Value().size() <= 400, nonDefaultStatus = Status::InvalidCommand);
-
+    VerifyOrExit(NOCValue.size() <= Credentials::kMaxCHIPCertLength, nonDefaultStatus = Status::InvalidCommand);
+    VerifyOrExit(!ICACValue.HasValue() || ICACValue.Value().size() <= Credentials::kMaxCHIPCertLength,
+                 nonDefaultStatus = Status::InvalidCommand);
     VerifyOrExit(ipkValue.size() == Crypto::CHIP_CRYPTO_SYMMETRIC_KEY_LENGTH_BYTES, nonDefaultStatus = Status::InvalidCommand);
+    VerifyOrExit((adminVendorId != VendorId::Common) && (adminVendorId <= static_cast<uint16_t>(VendorId::TestVendor4)),
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:680]: Done

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp (hunk 5 above)
Comment (tcarmelveilleux) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp]: Fixed

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp (hunk 4 above)
Comment (tcarmelveilleux) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:1150]: Will fix later yes

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp]: I agree that it's not clear what a client is to do here in the face of this error...

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp (hunk 4 above)
Comment (bzbarsky-apple) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:1150]: Filed https://github.com/project-chip/connectedhomeip/issues/19066 to track this.
