### PR TITLE
Fix PAA pathlen check to match spec

### LINKED ISSUE #27194: [BUG] MbedTLS implementation cannot load all PAA Certificates
### Reproduction steps

Build `chip-tool` with `mbedtls`

1. `cd example/chip-tool`
2. `gn gen out/build --args='chip_crypto="mbedtls"'`
3. `ninja -C out/build`
4. Go the certificate for subjectId `30:A7:FC:6C:D6:FA:5A:CB:82:7F:77:6E:32:62:07:6B:B8:11:E4:29` ([found here](https://on.dcl.csa-iot.org/dcl/pki/certificates/MDMxGzAZBgNVBAMMElFpYW55YW4gTWF0dGVyIFBBQTEUMBIGCisGAQQBgqJ8AgEMBDEzODc=/30:A7:FC:6C:D6:FA:5A:CB:82:7F:77:6E:32:62:07:6B:B8:11:E4:29)) and save the `pemCert` field to a file (make sure to replace `\n` with newlines).
5. Convert the certificate to `der` format
```
openssl x509 -in <PEM certificate file> -outform DER -out <output file>
```
6. Run `chip-tool` pairing with `--paa-trust-store-path` set to the folder containing the `der` certificate.
```
cd out/build
chip-tool pairing code 12345 1234-567-8901 --paa-trust-store-path <path to certificate folder>
```
7. The output will show the following line:
```
mbedTLS error: ASN1 - ASN1 tag was of an unexpected value
```

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

40fb7c246671e9d37ca8bb2cfbf37f81c1509334

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

It seems to be that the mbedtls implementation in chip expects the `Basic Constraint` extension to have a `pathLen` field to be set, while the matter specification marks this field as optional (see §6.2.2.5 in the v1.1 spec).

The certificate that was used in the reproduction path omits the `pathLen` field, as can be seen when reading the certificate using the following command:
```
openssl x509 -in cert.pem -text
```
```
...
X509v3 Basic Constraints: critical
                CA:TRUE
...
```

Certificates that do have the `pathLen` field set (e.g. [`D8:93:5A:88:DC:52:53:EA:35:4F:CE:D9:03:CE:D2:F6:2A:5C:AA:FF`](https://on.dcl.csa-iot.org/dcl/pki/certificates/MCYxJDAiBgNVBAMMG1dJU2VLZXkgT0lTVEUgTWF0dGVyIFBBQSBHQQ==/D8:93:5A:88:DC:52:53:EA:35:4F:CE:D9:03:CE:D2:F6:2A:5C:AA:FF)) can be used with mbedtls and will not show the ASN1 tag error.

### PR DESCRIPTION
**Pull request by tcarmelveilleux**
Problem:
- Since Matter 1.1, PAAs are allowed to omit the pathlen optional field to basic constraints extension. The code did not do that. See Matter 1.1, section 6.2.2.5.
- Fixes #27194

Changes in this PR:

- Update all CryptoPAL backends to fix the path length checks
- Added unit tests covering valid and invalid basic constraints around path lengths.

Testing done:

- Unit tests pass on both mbedTLS and BoringSSL/OpenSSL CryptoPAL

### CODE REVIEW

**Review by emargolis — APPROVED** [review]

File: src/crypto/CHIPCryptoPALmbedTLS.cpp [hunk 1]
```diff
@@ -1402,8 +1402,8 @@ CHIP_ERROR VerifyAttestationCertificateFormat(const ByteSpan & cert, Attestation
 
                 if (p != seqStart + len)
                 {
+                    // Failure to read will leave pathLen == -1
                     result = mbedtls_asn1_get_int(&p, end, &pathLen);
-                    VerifyOrExit(result == 0, error = CHIP_ERROR_INTERNAL);
```
Comment (bzbarsky-apple) [inline src/crypto/CHIPCryptoPALmbedTLS.cpp:1406]: Is this line being removed the thing that fixes the linked issue?  Because I don't see how the change to treat pathLen == 0 as error would fix it, but maybe I am missing something?

File: src/crypto/CHIPCryptoPALPSA.cpp [hunk 2]
```diff
@@ -1309,8 +1309,11 @@ CHIP_ERROR VerifyAttestationCertificateFormat(const ByteSpan & cert, Attestation
                 result = mbedtls_asn1_get_bool(&p, end, &isCA);
                 VerifyOrExit(result == 0 || result == MBEDTLS_ERR_ASN1_UNEXPECTED_TAG, error = CHIP_ERROR_INTERNAL);
 
-                if (p != seqStart + len)
+                // Missing pathLen optional tag will leave pathLen == -1.
+                bool hasPathLen = (p <= (seqStart + len));
```
Comment (bzbarsky-apple) [inline src/crypto/CHIPCryptoPALPSA.cpp:1313]: So just to make sure I understand....  we `mbedtls_asn1_get_tag`.  This updates `p` to point right after the tag + length, so now it points to the value, ok.  `len` is the length of the value.  I guess this value is the sequence?

We then mbedtls_asn1_get_bool.  This updates `p` to point to after the boolean's tag+value.

NOw we compare `seqStart + len` to `p`.  But what about the size of the encoded sequence length, the size of the boolean, etc? 

I am assuming I am missing something here in terms of how these APIs work.

Comment (tcarmelveilleux) [reply src/crypto/CHIPCryptoPALPSA.cpp:1313]: Yes. These APIs are brutal and very low-level and deal with the pointer. It doesn't help that this is nested parsing of ASN.1 within an octet string. This piece of code here for detecting optional element is still in sequence works only for the particular case of elements within a sequence. I did instrumented tests with a debugger with @emargolis and we validated that we correctly detected the presence/absence of the tag, and the pointers/sizes were sane. I hate this mbedTLS low-level API :(

**Review by bzbarsky-apple — APPROVED** [review]
Yes, now this all makes sense.  :)
