### PR TITLE
[IM] Update GetMinSubscriptionsPerFabric

### LINKED ISSUE #19535: `subscriptionsPerFabric` in basic cluster has incorrect values
#### Problem

Reading out `subscriptionsPerFabric` gives a really large number (which might be accurate on heap-based platforms anyways), but looked suspicious.

Looks like the logic is off in `InteractionModelEngine::GetMinSubscriptionsPerFabric()`:

```
    size_t perFabricSubscriptionCapacity = static_cast<size_t>(readHandlerPoolCapacity - kReservedPathsForReads) / fabricCount;
```

That should be `kReservedHandlersForRead`, not paths.

Also, `GetReadHandlerPoolCapacity` is not quite handling heap-based platforms today, resulting in an advertised number lower than the capability of the platform.

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem

Fixes #19535 

#### Change overview

- Renamed `GetMinSubscriptionsPerFabric` to `GetMinGuaranteedSubscriptionsPerFabric`
- The updated code is a solution that will never be wrong. (Return a constant value)
- Updated     static constexpr size_t kMinSupportedSubscriptionsPerFabric = 3; static constexpr size_t kMinSupportedPathsPerSubscription   = 3; Which should be updated in previous PRs, but I think it is also suitable to include the change in this PR

#### Testing

- Build with `#define CHIP_SYSTEM_CONFIG_POOL_USE_HEAP 1` it returns 65535
- Build with `#define CHIP_SYSTEM_CONFIG_POOL_USE_HEAP 0` it returns 3
- Build without heap, and with `#define CHIP_IM_MAX_NUM_SUBSCRIPTIONS (CHIP_CONFIG_MAX_FABRICS * 5)` it returns 5

### CODE REVIEW

File: src/app/InteractionModelEngine.cpp [hunk 1]
```diff
@@ -1370,19 +1371,14 @@ bool InteractionModelEngine::HasActiveRead()
...
-    if (fabricCount == 0)
-    {
-        return kMinSupportedSubscriptionsPerFabric;
-    }
-
-    size_t perFabricSubscriptionCapacity = readHandlerPoolCapacity / fabricCount;
-
-    return static_cast<uint16_t>(perFabricSubscriptionCapacity);
+#if CHIP_SYSTEM_CONFIG_POOL_USE_HEAP
+    return UINT16_MAX;
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.cpp:1377]: This would then claim that the device guarantees this many subscriptions.  But it may not actually be able to handle this many...

Followup is ok, but we need to figure out something saner here.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/InteractionModelEngine.cpp (hunk 1 above)
Comment (mrjerryjohns) [reply src/app/InteractionModelEngine.cpp:1377]: Sure, but what about be saner?

**Review by mrjerryjohns — APPROVED** [review]

File: src/app/InteractionModelEngine.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/InteractionModelEngine.cpp:1377]: If I had a concrete suggestion I would have made it....  Hence followup.
