### PR TITLE
[OTA] Add support for applying image for Linux/Darwin platform

### LINKED ISSUE #16498: OTA Requestor for Linux/Darwin uses the wrong version for NotifyUpdateApplied
#### Problem
With the merge of https://github.com/project-chip/connectedhomeip/pull/16103, `StoreSoftwareVersion` is used to save the software version to the configuration manager. There are a few problems with this:

1. There is no implementation for `StoreSoftwareVersion` on Linux
2. The OTARequestor class did not explicitly update `mCurrentVersion` after any "apply" for Linux platform

 #### Proposed Solution
Actually "apply" the downloaded image so that `mCurrentVersion` will be correct without additional logic

### PR DESCRIPTION
**Pull request by carol-apple**
#### Problem
OTA Requestor cannot send NotifyUpdateApplied to the provider for Linux/Darwin platform. The reason is because it relies on the version stored in `CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION` to be used when notifying and currently Linux/Darwin does not actually apply the downloaded image.

Fixes: https://github.com/project-chip/connectedhomeip/issues/16498

#### Change overview
- Define `CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION` and `CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING` to be used by Linux/Darwin platforms
- Actually apply the image (using `execv`)
- Implement `IsFirstImageRun` and `ConfirmCurrentImage` for Linux/Darwin so that `NotifyUpdateApplied` will be called on the new image
- Persist new values like current update state and target version to help determine that we are booting into a new image
- Make sure OTARequestor init code does not assume a boot up is always in idle state

#### Testing
- Basic transfer succeeds
- A new Linux image can be booted into after download
- NotifyUpdateApplied is sent to provider

### CODE REVIEW

File: examples/ota-requestor-app/linux/main.cpp [hunk 1]
```diff
@@ -189,5 +189,23 @@ int main(int argc, char * argv[])
...
+    if (gRequestorCore.GetCurrentUpdateState() == OTARequestor::OTAUpdateStateEnum::kApplying)
+    {
+        if (kMaxFilePathSize <= strlen(kImageExecPath))
+        {
+            ChipLogError(SoftwareUpdate, "Buffer too small for the new image file path: %s", kImageExecPath);
+            return -1;
+        }
+
+        char execFilePathBuf[kMaxFilePathSize];
+        strncpy(execFilePathBuf, kImageExecPath, strlen(kImageExecPath));
```
Comment (Damian-Nordic) [inline examples/ota-requestor-app/linux/main.cpp:203]: Why does it need to be copied? Can't `kImageExecPath` be assigned directly?

File: examples/ota-requestor-app/linux/main.cpp [hunk 2]
```diff
@@ -189,5 +189,23 @@ int main(int argc, char * argv[])
...
+        argv[0] = execFilePathBuf;
+        execv(argv[0], argv);
```
Comment (Damian-Nordic) [inline examples/ota-requestor-app/linux/main.cpp:205]: I guess calling this in `Apply()` caused the signal issues you mentioned on slack, right?

File: src/app/clusters/ota-requestor/DefaultOTARequestorStorage.cpp [hunk 3]
```diff
@@ -134,6 +134,40 @@ CHIP_ERROR DefaultOTARequestorStorage::LoadUpdateToken(MutableByteSpan & updateT
...
+    return mPersistentStorage->SyncDeleteKeyValue(DefaultStorageKeyAllocator::OTACurrentUpdateState());
+}
+
+CHIP_ERROR DefaultOTARequestorStorage::StoreTargetVersion(uint32_t targetVersion)
+{
+    return mPersistentStorage->SyncSetKeyValue(DefaultStorageKeyAllocator::OTATargetVersion(), &targetVersion,
+                                               sizeof(targetVersion));
+}
+
+CHIP_ERROR DefaultOTARequestorStorage::LoadTargetVersion(uint32_t & targetVersion)
```
Comment (Damian-Nordic) [inline src/app/clusters/ota-requestor/DefaultOTARequestorStorage.cpp:160]: Is OTA requestor expected to validate if the new images version matches the version that was announced by OTA provider? I wonder if after applying the update it's not too late to validate that which would indicate that the target version doesn't need to be stored in KVS.

File: src/platform/Linux/OTAImageProcessorImpl.cpp [hunk 4]
```diff
@@ -82,6 +84,35 @@ CHIP_ERROR OTAImageProcessorImpl::ProcessBlock(ByteSpan & block)
...
+    }
+
+    uint32_t currentVersion;
+    ReturnErrorOnFailure(DeviceLayer::ConfigurationMgr().GetSoftwareVersion(currentVersion));
+    if (currentVersion != requestor->GetTargetVersion())
+    {
+        return CHIP_ERROR_INCORRECT_STATE;
+    }
+
+    return CHIP_NO_ERROR;
```
Comment (Damian-Nordic) [inline src/platform/Linux/OTAImageProcessorImpl.cpp:113]: I wonder if this function should copy `kImageExecPath` image to the initial image location to approve the update and make further restarts not "rollback" to the old image. But maybe that could be a followup.

File: src/platform/Linux/OTAImageProcessorImpl.cpp [hunk 5]
```diff
@@ -96,6 +127,8 @@ void OTAImageProcessorImpl::HandlePrepareDownload(intptr_t context)
         return;
     }
 
+    unlink(imageProcessor->mImageFile.data());
```
Comment (Damian-Nordic) [inline src/platform/Linux/OTAImageProcessorImpl.cpp:130]: This assumes `mImageFile` is null-terminated which doesn't have to be the case. Maybe switching from `CharSpan` to `const char*` for `mImageFile` would make sense give its use?

File: src/app/clusters/ota-requestor/OTARequestor.cpp [hunk 6]
```diff
@@ -107,12 +107,40 @@ void OTARequestor::InitState(intptr_t context)
...
-    // This results in the initial periodic timer kicking off
-    requestorCore->RecordNewUpdateState(OTAUpdateStateEnum::kIdle, OTAChangeReasonEnum::kSuccess);
+    if (requestorCore->mCurrentUpdateState != OTAUpdateStateEnum::kApplying)
+    {
+        // This results in the initial periodic timer kicking off
+        requestorCore->RecordNewUpdateState(OTAUpdateStateEnum::kIdle, OTAChangeReasonEnum::kSuccess);
+    }
+    else
+    {
+        // This may have been a reboot from applying an image
```
Comment (selissia) [inline src/app/clusters/ota-requestor/OTARequestor.cpp:117]: It would be good to have a comment here that would described how the periodic timer will be kicked off in this logic path

**Review by selissia — APPROVED** [review]

File: examples/ota-requestor-app/linux/main.cpp (hunk 1 above)
Comment (carol-apple) [reply examples/ota-requestor-app/linux/main.cpp:203]: So the issue is that `kImageExecPath` is const and argv[0] takes in `char *`. I guess I can change `kImageExecPath` to non-const to do this assignment directly

File: src/platform/Linux/OTAImageProcessorImpl.cpp [hunk 7]
```diff
@@ -126,18 +157,18 @@ void OTAImageProcessorImpl::HandleFinalize(intptr_t context)
...
-    }
+    VerifyOrReturn(requestor != nullptr);
+
+    // Move the downloaded image to th location where the new image is to be executed from
+    unlink(kImageExecPath);
+    rename(imageProcessor->mImageFile.data(), kImageExecPath);
+    chmod(kImageExecPath, S_IRUSR | S_IWUSR | S_IXUSR | S_IRGRP | S_IXGRP | S_IROTH | S_IXOTH);
+
+    // Shutdown the stack and expect to boot into the new image once shutdown is complete
+    requestor->Shutdown();
```
[the remark this answers is not in the document]
Comment (carol-apple) [reply src/platform/Linux/OTAImageProcessorImpl.cpp:171]: No, at the end of `main`, it does the `execv` which boots into the new image automatically.

File: src/app/clusters/ota-requestor/OTARequestor.cpp [hunk 8]
```diff
@@ -809,6 +876,44 @@ void OTARequestor::StoreCurrentUpdateInfo()
...
+    }
+}
+
+void OTARequestor::Reset()
+{
+    mProviderLocation.ClearValue();
+    mUpdateToken.reduce_size(0);
+    RecordNewUpdateState(OTAUpdateStateEnum::kIdle, OTAChangeReasonEnum::kSuccess);
+    mTargetVersion = 0;
+
```
[the remark this answers is not in the document]
Comment (carol-apple) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:912]: `StoreCurrentUpdateState` will make clear vs store calls depending on the values of each of these member variables.

File: src/app/clusters/ota-requestor/DefaultOTARequestorStorage.cpp (hunk 3 above)
Comment (carol-apple) [reply src/app/clusters/ota-requestor/DefaultOTARequestorStorage.cpp:160]: I thought it might be a good idea for OTARequestor to validate version after first boot into the new image (especially helpful for Linux verification). Specifically for Linux, there wouldn't be an opportunity to validate after "applying" as it implies a reboot immediately after apply.

File: src/platform/Linux/OTAImageProcessorImpl.cpp (hunk 4 above)
Comment (carol-apple) [reply src/platform/Linux/OTAImageProcessorImpl.cpp:113]: So I had thought about some of this. One things is getting the location of the executable wasn't so straight forward (usually folks are probably calling from top-level dir and executable is somewhere under out/ so calling `getcwd` only got you to the top-level location). Figuring this out required more time than I had wanted to spend on this :) 

Also, the rolling back vs not.. if we did copy to the initial image location, that means if you want to run OTA again after terminating the app, you'd have to build a newer version otherwise the next image will never pass Confirm. I couldn't quite decide how we should handle this situation either so just left it as this second location. I can definitely file an issue to track this for later.

File: src/platform/Linux/OTAImageProcessorImpl.cpp (hunk 5 above)
Comment (carol-apple) [reply src/platform/Linux/OTAImageProcessorImpl.cpp:130]: Done

File: src/app/clusters/ota-requestor/OTARequestor.cpp (hunk 6 above)
Comment (carol-apple) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:117]: Done

File: src/platform/Linux/OTAImageProcessorImpl.cpp (hunk 4 above)
Comment (carol-apple) [reply src/platform/Linux/OTAImageProcessorImpl.cpp:113]: One more thought on this is if confirming the new image fails, we might want to consider rolling back to the previous image. I guess this should all be captured by a followup.

Comment (carol-apple) [reply src/platform/Linux/OTAImageProcessorImpl.cpp:113]: Filed https://github.com/project-chip/connectedhomeip/issues/16516

File: src/app/clusters/ota-requestor/OTARequestor.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (hrajendran-samsung) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:913]: Hmmm. Doesn't StoreCurrentUpdateState() simply store the update value in the KVS? I don't see the UpdateState being cleared anywhere.

File: src/app/clusters/ota-requestor/OTARequestor.cpp [hunk 9]
```diff
@@ -788,19 +821,53 @@ CHIP_ERROR OTARequestor::SendNotifyUpdateAppliedRequest(OperationalDeviceProxy &
...
 
-    mProviderLocation.ClearValue(); // Clearing the last used provider location to start afresh on reboot
+    // There is no response for a notify so consider this OTA complete. Clear the provider location and reset any states to indicate
+    // so.
+    Reset();
 
     return cluster.InvokeCommand(args, this, OnNotifyUpdateAppliedResponse, OnNotifyUpdateAppliedFailure);
 }
 
 void OTARequestor::StoreCurrentUpdateInfo()
```
[the remark this answers is not in the document]
Comment (hrajendran-samsung) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:832]: Probably, or reset the system if all else fails?

File: src/app/clusters/ota-requestor/OTARequestor.cpp [hunk 10]
```diff
@@ -107,12 +107,41 @@ void OTARequestor::InitState(intptr_t context)
     OTARequestor * requestorCore = reinterpret_cast<OTARequestor *>(context);
     VerifyOrDie(requestorCore != nullptr);
 
-    // This results in the initial periodic timer kicking off
-    requestorCore->RecordNewUpdateState(OTAUpdateStateEnum::kIdle, OTAChangeReasonEnum::kSuccess);
+    if (requestorCore->mCurrentUpdateState != OTAUpdateStateEnum::kApplying)
```
Comment (Damian-Nordic) [inline src/app/clusters/ota-requestor/OTARequestor.cpp:110]: I think we should add here `|| !IsFirstImageRun`. Otherwise, if a new image crashes and is reverted, we will switch to `kApplying` state, but the driver will never confirm the image.

File: src/platform/Linux/OTAImageProcessorImpl.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (Damian-Nordic) [reply src/platform/Linux/OTAImageProcessorImpl.cpp:171]: oh, right.

File: src/app/clusters/ota-requestor/OTARequestor.h [hunk 11]
```diff
@@ -40,6 +40,8 @@ class OTARequestor : public OTARequestorInterface, public BDXDownloader::StateDe
     OTARequestor() : mOnConnectedCallback(OnConnected, this), mOnConnectionFailureCallback(OnConnectionFailure, this) {}
 
     //////////// OTARequestorInterface Implementation ///////////////
+    void Shutdown(void) override;
```
Comment (Damian-Nordic) [inline src/app/clusters/ota-requestor/OTARequestor.h:43]: This is very much platform-specific, so I have a feeling it shouldn't be part of OTA requestor interface, but I'm not sure how to trigger server shutdown in a better way...

File: src/app/clusters/ota-requestor/OTARequestor.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (carol-apple) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:913]: Sorry, I misread/miswrote in my last comment to you (I was referring to `StoreCurrentUpdateInfo` which does clearing). So I don't see a valid reason for us to ever call `ClearCurrentUpdateState` unless something has gone horribly wrong. Clearing update state is equivalent of saying the state is `kUnknown` which is there to indicate we truly don't know the state (like during first time bootup). After that, we probably should never use that state as we know we'll be in idle.

With that said, I had added the `ClearCurrentUpdateState` to be consistent with all the other storage APIs. There is no need to use it right now so happy to remove it if you feel strongly about it.

File: src/app/clusters/ota-requestor/OTARequestor.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (carol-apple) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:832]: Sounds like maybe we should do a follow up to handle something like this?

File: src/app/clusters/ota-requestor/OTARequestor.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (hrajendran-samsung) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:913]: Got it, I see that the updateState is being changed to Idle- that makes sense.

**Review by harsha-rajendran — APPROVED** [review]

File: src/app/clusters/ota-requestor/OTARequestor.h (hunk 11 above)
Comment (carol-apple) [reply src/app/clusters/ota-requestor/OTARequestor.h:43]: Yeah, I was having a hard time figuring out where best to put this. Perhaps a follow up for post v1 to determine a better way to shutdown the server?

File: src/app/clusters/ota-requestor/OTARequestor.cpp (hunk 10 above)
Comment (carol-apple) [reply src/app/clusters/ota-requestor/OTARequestor.cpp]: `IsFirstImageRun` is in image processor which OTARequestor does not have access to. Instead, I addressed this by modifying `GenericOTARequestorDriver::Init` to prevent problems with the new image from causing  the "stuck in the `kApplying` state" scenario. Specifically, I reset the OTA states either when confirm fails or if this is `!IsFirstImageRun` but we're also not in the idle state.

File: src/app/clusters/ota-requestor/OTARequestor.h (hunk 11 above)
Comment (Damian-Nordic) [reply src/app/clusters/ota-requestor/OTARequestor.h:44]: Yes, I think this should be cleaned up at some point since embedded platforms typically don't need to implement any graceful shutdown involving killing threads etc.

**Review by Damian-Nordic — APPROVED** [review]

File: src/app/clusters/ota-requestor/OTARequestor.cpp (hunk 10 above)
Comment (Damian-Nordic) [reply src/app/clusters/ota-requestor/OTARequestor.cpp]: `OTARequestor` does have access to `OTAImageProcessor`, but I think your solution is cleaner now.
