### PR TITLE
[ICD] refreshKey needs to be set with length

### LINKED ISSUE #35347: [CERT-TEST-FAILURE] [TC-ICDB-1.3] Test failed - DUT Fails to Refresh Entry with New Key - Receives Status 0x87 (CONSTRAINT_ERROR) in Step 2b
### Feature Area

Area:ICDPhase2

### Test Case

TC-ICDB-1.3

### Reproduction steps

At step 2b. According to the test plan, when the DUT receives a Check-In message with a Check-In Counter ICDCounter2 indicating that 2^31 counter values have been used, the DUT should refresh its entry with a new key Key2 via the RegisterClient command to the TH with the following details:
CheckInNodeID: CheckInNodeID
MonitoredSubject: MonitoredSubID
Key: Key2
However, in the current SDK, TH receiving the status 0x87 (CONSTRAINT_ERROR)

Command used to launch the DUT :`./lit-icd-app --enable-key 00112233445566778899AABBCCDDEEFF`
Command used to launch the TH: `./chip-tool pairing onnetwork 1 20202021`
After the successful pairing entered to interactive mode using mentioned command - `./chip-tool interactive start`
step 1 : TH sends {C_REGISTER_CLIENT} command.

CheckInNodeID: CheckInNodeID
MonitoredSubject: MonitoredSubID
Key: Key1
` icdmanagement register-client 112233 1 hex:abcdef1234567890abcdef1234567890 0 1 0
`
> [1725270357.500] [23820:23822] [DMG] Received Command Response Data, Endpoint=0 Cluster=0x0000_0046 Command=0x0000_0001
> [1725270357.501] [23820:23822] [TOO] Endpoint: 0 Cluster: 0x0000_0046 Command 0x0000_0001
> [1725270357.501] [23820:23822] [TOO]   RegisterClientResponse: {
> [1725270357.501] [23820:23822] [TOO]     ICDCounter: 3083289412
> [1725270357.501] [23820:23822] [TOO]    }
> 

`icd wait-for-device 1 30
`[1725270362.672] [23820:23820] [TOO] Command: icd wait-for-device 1 30 
[1725270362.674] [23820:23822] [TOO] Peer is a registered LIT ICD.
[1725270362.674] [23820:23822] [TOO] Please trigger the device active mode.
[1725270368.005] [23820:23822] [EM] >>> [E:31729r S:0 M:254352686] (U) Msg RX from 0:88BEE2F5BF9325A3 [0000] --- Type 0000:50 (SecureChannel:ICD_CheckInMessage) (B:57)
[1725270368.005] [23820:23822] [EM] Handling via exchange: 31729r, Delegate: 0xaaaac19b25d0
[1725270368.006] [23820:23822] [ICD] Check In Message processing complete: start_counter=3083289412 offset=1 nodeid=<000000000000

Step 2a : 
`generaldiagnostics test-event-trigger hex:00112233445566778899AABBCCDDEEFF 0x0046000000000003 1 0
`
> [1725270369.053] [23820:23822] [DMG] 	InteractionModelRevision = 11
> [1725270369.053] [23820:23822] [DMG] },
> [1725270369.053] [23820:23822] [DMG] Received Command Response Status for Endpoint=0 Cluster=0x0000_0033 Command=0x0000_0000 Status=0x0
> [1725270369.053] [23820:23822] [DMG] ICR moving to [AwaitingDe]

**STEP 2b -** waited DUT refresh its entry with a new key Key2 via {C_REGISTER_CLIENT} command to TH: - CheckInNodeID: CheckInNodeID

MonitoredSubject: MonitoredSubID
Key: Key2**
However, in the current SDK, TH receiving the status 0x87 (CONSTRAINT_ERROR)

> [1725270378.016] [23820:23822] [DMG] InvokeResponseMessage =
> [1725270378.016] [23820:23822] [DMG] {
> [1725270378.016] [23820:23822] [DMG] 	suppressResponse = false, 
> [1725270378.016] [23820:23822] [DMG] 	InvokeResponseIBs =
> [1725270378.016] [23820:23822] [DMG] 	[
> [1725270378.017] [23820:23822] [DMG] 		InvokeResponseIB =
> [1725270378.017] [23820:23822] [DMG] 		{
> [1725270378.017] [23820:23822] [DMG] 			CommandStatusIB =
> [1725270378.017] [23820:23822] [DMG] 			{
> [1725270378.017] [23820:23822] [DMG] 				CommandPathIB =
> [1725270378.017] [23820:23822] [DMG] 				{
> [1725270378.017] [23820:23822] [DMG] 					EndpointId = 0x0,
> [1725270378.017] [23820:23822] [DMG] 					ClusterId = 0x46,
> [1725270378.017] [23820:23822] [DMG] 					CommandId = 0x0,
> [1725270378.017] [23820:23822] [DMG] 				},
> [1725270378.017] [23820:23822] [DMG] 				
> [1725270378.017] [23820:23822] [DMG] 				StatusIB =
> [1725270378.017] [23820:23822] [DMG] 				{
> [1725270378.017] [23820:23822] [DMG] 					status = 0x87 (CONSTRAINT_ERROR),
> [1725270378.018] [23820:23822] [DMG] 				},
> [1725270378.018] [23820:23822] [DMG] 				
> [1725270378.018] [23820:23822] [DMG] 			},
> [1725270378.018] [23820:23822] [DMG] 			
> [1725270378.018] [23820:23822] [DMG] 		},
> [1725270378.018] [23820:23822] [DMG] 		
> [1725270378.018] [23820:23822] [DMG] 	],
> [1725270378.018] [23820:23822] [DMG] 	
> [1725270378.018] [23820:23822] [DMG] 	InteractionModelRevision = 11
> [1725270378.018] [23820:23822] [DMG] },
> [1725270378.018] [23820:23822] [DMG] Received Command Response Status for Endpoint=0 Cluster=0x0000_0046 Command=0x0000_0000 Status=0x87
> [1725270378.018] [23820:23822] [ICD] RegisterClient command failed: IM Error 0x00000587: General error: 0x87 (CONSTRAINT_ERROR)
> [1725270378.018] [23820:23822] [ICD] Re-registration with new key failed with error : IM Error 0x00000587: General error: 0x87 (CONSTRAINT_ERROR)

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

708558881bf6e5b0dac3c09489124907927b6cd2

### Platform

raspi

### Anything else?

**Test Plan Reference :** 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/icdbehavior.adoc#tc-icdb-1-3-icd-check-in-protocol-client-response-dut_client

**PFA Logs**
[TC-ICDB-1.3 - LIT-APP.txt](https://github.com/user-attachments/files/16835899/TC-ICDB-1.3.-.LIT-APP.txt)
[TC-ICDB-1.3 validation log.txt](https://github.com/user-attachments/files/16835900/TC-ICDB-1.3.validation.log.txt)

### PR DESCRIPTION
**Pull request by yunhanw-google**
We need setLength after putting data inside SensitiveDataBuffer, otherwise, the key is 0 bytes
verified locally and confirm refreshKey works
fixes https://github.com/project-chip/connectedhomeip/issues/35347

### CODE REVIEW

File: src/app/icd/client/DefaultCheckInDelegate.cpp [hunk 1]
```diff
@@ -41,7 +41,8 @@ void DefaultCheckInDelegate::OnCheckInComplete(const ICDClientInfo & clientInfo)
 
 CHIP_ERROR DefaultCheckInDelegate::GenerateRefreshKey(RefreshKeySender::RefreshKeyBuffer & newKey)
 {
-    return Crypto::DRBG_get_bytes(newKey.Bytes(), newKey.Capacity());
+    ReturnErrorOnFailure(Crypto::DRBG_get_bytes(newKey.Bytes(), newKey.Capacity()));
+    return newKey.SetLength(Crypto::kAES_CCM128_Key_Length);
```
Comment (bzbarsky-apple) [inline src/app/icd/client/DefaultCheckInDelegate.cpp:45]: Why are we putting `newKey.Capacity()` bytes in there but then claiming the length is `Crypto::kAES_CCM128_Key_Length`?

Should be consistent.

Comment (yunhanw-google) [reply src/app/icd/client/DefaultCheckInDelegate.cpp]: done, thanks

**Review by jmartinez-silabs — APPROVED** [review]

File: src/app/icd/client/DefaultCheckInDelegate.cpp (hunk 1 above)
Comment (yunhanw-google) [reply src/app/icd/client/DefaultCheckInDelegate.cpp]: done, thanks

**Review by bzbarsky-apple — APPROVED** [review]

**Review by yufengwangca — APPROVED** [review]
