### PR TITLE
[controller] Add timeout to pairing

### LINKED ISSUE #5607: Add timeout for pairing (key exchange)
#### Problem

Currently, when pairing over IP with a wrong ip address / port, the `chip-tool` will stopped by `Command::WaitForResponse` and `chip-device-ctrl` will hang.

```
± % ./out/debug/standalone/chip-tool pairing softap 12345678 1111 192.168.123.123 123                                                                                                       !10361
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 112233

CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:DL: CHIP task running
CHIP:BLE: Sent PBKDF param request
CHIP:TOO: No response from device
CHIP:CTL: Shutting down the commissioner
CHIP:CTL: Shutting down the controller
CHIP:DL: System Layer shutdown
CHIP:DL: Inet Layer shutdown
CHIP:DL: BLE layer shutdown
```

This is an issue if we want to conduct multiple key exchanges using the same device controller instance, the device controller or PASE/CASE session should take care of this.

 #### Proposed Solution

Add a timeout for pairing on host side.

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem
Currently, when pairing over IP with a wrong ip address / port, chip-device-ctrl will hang.

 #### Summary of Changes

Add a timeout in DeviceCommissioner class.

 #### Test

```
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x000000000001b669
CHIP:DL: CHIP task running
Chip Device Controller Shell

chip-device-ctrl > connect -ip 1.2.3.4 12345678
Device is assigned with nodeid = 72600
CHIP:BLE: Assigned local session key ID 0
CHIP:BLE: Sent PBKDF param request
Failed to establish secure session to device: 4050
CHIP Error 4050 (0x00000FD2): Timeout
chip-device-ctrl > 
```

 Fixes #5607

### CODE REVIEW

File: src/controller/CHIPDeviceController.cpp [hunk 1]
```diff
@@ -70,6 +70,7 @@ using namespace chip::Encoding;
 constexpr const char kPairedDeviceListKeyPrefix[] = "ListPairedDevices";
 constexpr const char kPairedDeviceKeyPrefix[]     = "PairedDevice";
 constexpr const char kNextAvailableKeyID[]        = "StartKeyID";
+constexpr const uint32_t kPairingTimeout          = 30 * kMillisecondPerSecond;
```
Comment (Damian-Nordic) [inline src/controller/CHIPDeviceController.cpp:73]: Why does the pairing hang in your case? Will this be needed after switching to CRMP transport which AFAIK supports timeouts for individual messages? My concern is that 30s may be too little for the scenario where a user must enter network credentials by hand (e.g. in the Android app). Maybe at least the timer could be cancelled at the network provisioning phase?

Comment (erjiaqing) [reply src/controller/CHIPDeviceController.cpp]: Moved it to OnRendezvousStatusUpdate.

**Review by Damian-Nordic — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]
Echoing the comment from @Damian-Nordic, it does seem like this should somehow be formalized.  And a device's CRMP profile would seem to tell us how long is reasonable to wait.  Doesn't this session establishment need to happen every time the controller boots?  I don't believe this is only relevant during commissioning.

I don't know the answers to these questions.  And I agree there needs to be a timeout.  But I think this needs more design / discussion.  When my controller boots, it may attempt to establish sessions with a large number of sleepy devices.  Won't most of these interactions fail?  What should be my controller's behavior for this scenario?

Approving so we have something.  But I'm very interested in everyone's thoughts.

File: src/controller/CHIPDeviceController.cpp [hunk 2]
```diff
@@ -877,5 +883,24 @@ void DeviceCommissioner::ReleaseDevice(Device * device)
     DeviceController::ReleaseDevice(device);
 }
 
+void DeviceCommissioner::OnSessionEstablishmentTimeout()
```
Comment (woody-apple) [inline src/controller/CHIPDeviceController.cpp:886]: We should support timeouts in the Darwin framework too

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
> Echoing the comment from @Damian-Nordic, it does seem like this should somehow be formalized. And a device's CRMP profile would seem to tell us how long is reasonable to wait. Doesn't this session establishment need to happen every time the controller boots? I don't believe this is only relevant during commissioning.
> 
> I don't know the answers to these questions. And I agree there needs to be a timeout. But I think this needs more design / discussion. When my controller boots, it may attempt to establish sessions with a large number of sleepy devices. Won't most of these interactions fail? What should be my controller's behavior for this scenario?
> 
> Approving so we have something. But I'm very interested in everyone's thoughts.

Given this is during the pairing process, I do agree we need a less random number than 30 seconds, but also - given this is an operation which requires user interaction, we do need some user feedback about "This is taking too long", please reboot your accessory and try again, or something to that end. Thoughts?

**Comment by msandstedt** [comment]
> Given this is during the pairing process, I do agree we need a less random number than 30 seconds, but also - given this is an operation which requires user interaction, we do need some user feedback about "This is taking too long", please reboot your accessory and try again, or something to that end. Thoughts?

This I think is part of the source of my confusion.  I thought these code paths were executing any time a controller restarted and attempted to reestablish sessions with devices.  Is that not true?  Does this code only execute when we are commissioning new devices?
