### PR TITLE
Closure App Set-Target ,Step,MoveTo command fixes.

### LINKED ISSUE #40497: [Closure App]:  Position field in OverallTargetState struct gets wrong value after step command
### Type

Position field in OverallTargetState struct gets a wrong value after step command is sent after a start up where the position is not known yet. 

### Explanation

Step 1: Start Closure app and read OverallTargetStat struct. Expected Position=null, Actual Position=null
Step 2: Send a Step command on ClosureDimension
Step 3: Read out OverallTargetState: Expected Position=Null But Position Field gets an unexpected value than null 

### Platform

Linux

### Platform Version(s)

_No response_

### Testing

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sabollim-silabs**
#### Summary
This Jira aims to fix closure app issues

1. Set Target command updated target position in closure control to none -> changed it to null
2. SetOverallState closure cluster function has been updated  validate secured state based on position and latch values and reject if secure state values didnot match the conditions. So we updated the securestate values to reflect the changes of position and latch changes.

Adding SecureState specifications reference

This field SHALL indicate the current secure state of the closure.
A secure state requires the closure to meet all of the following conditions defined by the OverallCurrentState Struct based on feature support:
If the Positioning feature is supported, then the Position field of OverallCurrentState is FullyClosed.
If the MotionLatching feature is supported, then the Latch field of OverallCurrentState is True.

The rules for setting the value of the SecureState field SHALL be:
True if the closure meets the required conditions for a secure state, preventing unauthorized or undetectable access.
False if the closure does not meet these conditions and unauthorized or undetectable access is possible.
null if the closure’s current secure state is unknown.`

#### Related issues

Fixes: #40497 

#### Testing
Manually tested, the above Set-Target command and MoveTO commands manually.
CI runs the test script across the app.

#### Readability checklist

The checklist below will help the reviewer finish PR review in time and keep the
code readable:

-   [x] PR title is
        [descriptive](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html#title-formatting)
-   [x] Apply the
        [_“When in Rome…”_](https://project-chip.github.io/connectedhomeip-doc/style/CODING_STYLE_GUIDE.html)
        rule (coding style)
-   [x] PR size is short
-   [x] Try to avoid "squashing" and "force-update" in commit history
-   [x] CI time didn't increase

See: [Pull Request Guidelines](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html)

### CODE REVIEW

**Review by AliTalebVelux — APPROVED** [review]

**Review by jepenven-silabs — APPROVED** [review]

File: examples/closure-app/silabs/src/ClosureManager.cpp [hunk 1]
```diff
@@ -707,6 +707,18 @@ void ClosureManager::HandleClosureMotionAction()
             // In Real application, this would be replaced with actual unlatch logic.
             ChipLogProgress(AppServer, "Performing latch action");
             mClosureEndpoint1CurrentState.Value().latch.SetValue(DataModel::MakeNullable(true));
+            if (mClosureEndpoint1CurrentState.Value().position.HasValue() &&
+                !mClosureEndpoint1CurrentState.Value().position.Value().IsNull())
+            {
+                if (mClosureEndpoint1CurrentState.Value().position.Value().Value() == CurrentPositionEnum::kFullyClosed)
+                {
+                    mClosureEndpoint1CurrentState.Value().secureState.SetNonNull(true);
```
Comment (mkardous-silabs) [inline examples/closure-app/silabs/src/ClosureManager.cpp:715]: I'm not sure I understand why we are setting this to true - the comment earlier is stating that we are unlatching?

File: examples/closure-app/linux/ClosureManager.cpp [hunk 2]
```diff
@@ -908,6 +912,17 @@ void ClosureManager::HandleClosureMotionAction()
             // In Real application, this would be replaced with actual unlatch logic.
             ChipLogProgress(AppServer, "Performing latch action");
             ep1CurrentState.Value().latch.SetValue(DataModel::MakeNullable(true));
+            if (ep1CurrentState.Value().position.HasValue() && !ep1CurrentState.Value().position.Value().IsNull())
+            {
+                if (ep1CurrentState.Value().position.Value().Value() == CurrentPositionEnum::kFullyClosed)
+                {
+                    ep1CurrentState.Value().secureState.SetNonNull(true);
```
Comment (mkardous-silabs) [inline examples/closure-app/linux/ClosureManager.cpp:919]: same comment

**Comment by mkardous-silabs** [comment]
Having the application managing the secure state seems odd since there it is based on the two states of the device. It seems  to me the cluster / common logic should manage that state when the position or latch states are changed. 

This can be a follow up - it would simplify the requirements around the closre manager implementation.

File: examples/closure-app/silabs/src/ClosureManager.cpp (hunk 1 above)
Comment (sabollim-silabs) [reply examples/closure-app/silabs/src/ClosureManager.cpp:715]: this is a latch action . there is a mistake in comment will correct it.
the chiplogprogress and latch.setvalue(true) both are correct for latching action.

File: examples/closure-app/linux/ClosureManager.cpp (hunk 2 above)
Comment (sabollim-silabs) [reply examples/closure-app/linux/ClosureManager.cpp:919]: this is a latch action . there is a mistake in comment will correct it.
the chiplogprogress and latch.setvalue(true) both are correct for latching action.

File: examples/closure-app/silabs/src/ClosureManager.cpp [hunk 3]
```diff
@@ -707,6 +707,18 @@ void ClosureManager::HandleClosureMotionAction()
             // In Real application, this would be replaced with actual unlatch logic.
```
Comment (sabollim-silabs) [inline examples/closure-app/silabs/src/ClosureManager.cpp]:
```suggestion
            // In Real application, this would be replaced with actual latch logic.
```

File: examples/closure-app/linux/ClosureManager.cpp [hunk 4]
```diff
@@ -908,6 +912,17 @@ void ClosureManager::HandleClosureMotionAction()
             // In Real application, this would be replaced with actual unlatch logic.
```
Comment (sabollim-silabs) [inline examples/closure-app/linux/ClosureManager.cpp]:
```suggestion
            // In Real application, this would be replaced with actual latch logic.
```
