### PR TITLE
Remove recursive mutex & fix unbalanced locking in TestPlatformMgr

### LINKED ISSUE #1584: TestPlatformMgr is flaky on Linux
Looks like another load dependent failure

[ CHIP DeviceLayer time tests ]
CHIP:DL: writing settings to file (/tmp/chip_factory.ini.tmp)
CHIP:DL: renamed tmp file to file (/tmp/chip_factory.ini)
CHIP:DL: writing settings to file (/tmp/chip_config.ini.tmp)
CHIP:DL: renamed tmp file to file (/tmp/chip_config.ini)
CHIP:DL: writing settings to file (/tmp/chip_counters.ini.tmp)
CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[ CHIP DeviceLayer time tests : Test PlatformMgr::Init               ] : PASSED
[ CHIP DeviceLayer time tests : Test PlatformMgr::StartEventLoopTask ] : PASSED
CHIP:DL: CHIP task running
../../src/platform/tests/TestPlatformMgr.cpp:62: assertion failed: "locked"
CHIP:DL: Timer: 2592000000
[ CHIP DeviceLayer time tests : Test PlatformMgr::TryLockChipStack   ] : FAILED
[ CHIP DeviceLayer time tests : Test PlatformMgr::AddEventHandler    ] : PASSED
Failed Tests:   1 / 4

### PR DESCRIPTION
**Pull request by mspang**
We shouldn't use recursive mutexes for synchronization as they greatly
complicate analysis and maintenance.

fixes #1584

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by turon — APPROVED** [review]
LGTM :+1:

File: src/platform/tests/TestPlatformMgr.cpp [hunk 1]
```diff
@@ -59,12 +59,8 @@ static void TestPlatformMgr_StartEventLoopTask(nlTestSuite * inSuite, void * inC
 static void TestPlatformMgr_TryLockChipStack(nlTestSuite * inSuite, void * inContext)
 {
     bool locked = PlatformMgr().TryLockChipStack();
-    NL_TEST_ASSERT(inSuite, locked);
-
-    PlatformMgr().LockChipStack();
-    locked = PlatformMgr().TryLockChipStack();
-    PlatformMgr().UnlockChipStack();
-    NL_TEST_ASSERT(inSuite, locked);
+    if (locked)
```
Comment (andy31415) [inline src/platform/tests/TestPlatformMgr.cpp:62]: should we have a NL_TEST_ASSERT on locked being true ? Previous code was testing things (but double for recursive support). Should we keep at least one?

**Review by andy31415 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

File: src/platform/tests/TestPlatformMgr.cpp (hunk 1 above)
Comment (mspang) [reply src/platform/tests/TestPlatformMgr.cpp:62]: This isn't possible because the lock is contended during this tests (by the events thread). By definition trylock isn't guaranteed to take the lock.

That's the cause of the flake in the bug this is closing.

File: src/include/platform/internal/GenericPlatformManagerImpl_POSIX.ipp [hunk 2]
```diff
@@ -53,13 +53,7 @@ CHIP_ERROR GenericPlatformManagerImpl_POSIX<ImplClass>::_InitChipStack(void)
...
     CHIP_ERROR err = CHIP_NO_ERROR;
 
-#if defined(PTHREAD_RECURSIVE_MUTEX_INITIALIZER)
-    mChipStackLock = PTHREAD_RECURSIVE_MUTEX_INITIALIZER;
-#elif defined(PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP)
-    mChipStackLock = PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP;
-#else
-#error "No defined static initializer for POSIX Threads recursive mutex!"
-#endif // defined(PTHREAD_RECURSIVE_MUTEX_INITIALIZER)
+    mChipStackLock = PTHREAD_MUTEX_INITIALIZER;
```
Comment (gerickson) [inline src/include/platform/internal/GenericPlatformManagerImpl_POSIX.ipp:56]: Did we lose some portability here?
