### PR TITLE
Make AddressResolver not keep duplicate IP addresses in its cache

### LINKED ISSUE #36746: [BUG] Operational discovery fails if highest scored IP address is not reachable
### Reproduction steps

There is a difference in behaviour between commissionable node and operational node discovery.

- Commisionable node discovery will try to send messages over all/multiple discovered addresses if the highest scored address fails
- Operational node discovery will only attempt the highest scored address in some cases, which I believe is a bug.

Commit https://github.com/project-chip/connectedhomeip/commit/b590431f30f2abbff84ad94211c11b049e2bd702 created and implemented the `NodeLookupResults::UpdateResults` function. The problem is that the `results` list can get filled with addresses which are all the same.

This can cause problems. 

- During commissioning the PASE session will be created over an IP address that doesn’t have the highest score. However, when operational discovery takes place to finalise commissioning, it wil fail because it only tries the IP with the highest score again.
- If for whatever reason the highest scored IP doesn’t work, operational discovery will never succeed.

I think the `NodeLookupResults::UpdateResults` function should be updated to also check if the address is already present in the `results` list, and not replace another address if this is the case (even if the score of address in the list is lower).

**Reproduction path:**

- To make it a bit easier to see what is happening you could at `LogDetail()` to `NodeLookupResults::ConsumeResults()` and `NodeLookupResults::UpdateResults()`
- Add `#define CHIP_CONFIG_MDNS_RESOLVE_LOOKUP_RESULTS 5` to `examples/chip-tool/include/CHIPProjectAppConfig.h`
    - Without this, operational discovery doesn’t even attempt multiple addresses, while commisionable node discovery does do this.
- Compile `chip-tool`
- Now starts the tricky path, we need to create a device that creates an mDNS advertisement, but doesn’t respond to udp messages. I’ve used `matter.js` for this, as it exposed the APIs to do this. I’ve attached these scripts.
- Commissionable node (which works as expected):
    - Run as javascript (with matter.js installed):

```javascript
import { Network, VendorId } from '@matter/main';
import { MdnsBroadcaster } from '@matter/main/protocol';

const broadcaster = await MdnsBroadcaster.create(Network.get());

// Pairing code = MT:Y.K90YDA13CJO35X700
await broadcaster.setCommissionMode(5540, 1, {
    discriminator: 1203,
    vendorId: VendorId(65521),
    name: 'Dummy MDNS Commissionable Node',
    deviceType: 0x0001,
    productId: 32768,
});
```
  - Run `chip-tool pairing code 12345 MT:Y.K90YDA13CJO35X700`
      - This obviously fails, because no one is responding. Important is that we see that all advertised addresses are used:
          - `Attempting PASE connection to UDP:[fe80::21c:42ff:fe11:b7fc%enp0s5]:5540`
          - `Attempting PASE connection to UDP:[fd01:54a2:7aa9:9caf:21c:42ff:fe11:b7fc]:5540`
    - [commissionable-node.log](https://github.com/user-attachments/files/18038338/commissionable-node.log)

- Operational node (which can fail):
    - Run as javascript:
```javascript
import { FabricId, FabricIndex, Network, NodeId, Crypto, VendorId } from '@matter/main';
import { Fabric, MdnsBroadcaster } from '@matter/main/protocol';

const broadcaster = await MdnsBroadcaster.create(Network.get());

const compressedFabricId = 0xB4341FFC3A38E11Bn; // Note: replace with the compressed fabric id thats created by chip-tool
const nodeId = NodeId(12345);


const operationalId = Buffer.alloc(8);
operationalId.writeBigUint64BE(compressedFabricId);

await broadcaster.setFabrics(5540, [
    new Fabric({
        fabricIndex: FabricIndex(1),
        fabricId: FabricId(compressedFabricId),
        nodeId,
        rootNodeId: NodeId(1),
        operationalId,
        rootPublicKey: new Uint8Array(),
        keyPair: Crypto.createKeyPair(),
        rootVendorId: VendorId(0x1234),
        rootCert: new Uint8Array(),
        identityProtectionKey: new Uint8Array(),
        operationalIdentityProtectionKey: new Uint8Array(),
        intermediateCACert: undefined,
        operationalCert: new Uint8Array(),
        label: 'testing',
    }),
]);
```
  - Run `chip-tool interactive start` and then `onoff toggle 12345 1`
      - Interactive mode is required, because `chip-tool` will exit after 30s
      - With the added logs, we see that the results table is getting filled with duplicate addresses.
```
[-] NodeLookupResults::UpdateResults ->
[DIS]  #1: UDP:[fe80::21c:42ff:fe11:b7fc%enp0s5]:5540
[DIS]  #2: UDP:[fe80::21c:42ff:fe11:b7fc%enp0s5]:5540
[DIS]  #3: UDP:[fe80::21c:42ff:fe11:b7fc%enp0s5]:5540
[DIS]  #4: UDP:[fd01:54a2:7aa9:9caf:21c:42ff:fe11:b7fc]:5540
[DIS]  #5: UDP:[fd01:54a2:7aa9:9caf:21c:42ff:fe11:b7fc]:5540
```
  - Because (in this case) the highest three addresses are the same, it will try three times to send the messages to this address. While the intended behaviour (I think) is that it should try a different address.
  - [operational-node.log](https://github.com/user-attachments/files/18038333/operational-node.log)

        
        
> That the link-local/highest score address is not reachable should not happen of course. But we don't live in a perfect world 😅 

> I was not able to reproduce this when running `chip-tool` on Mac, only on Ubuntu. So there also seems to be some discovery differences between platforms.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

9b008bc10d48bef1184cf9f0405b12b41af5d328

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by andy31415**
This fixes #36746 by deduplicating IP addresses in AddressResolver results.

### Changes

- do not insert duplicate addresses in the list
- fixed and added unit tests for this
- Attempted to push MDNS result size to 3 however that seems to take too much RAM for various platforms, so new tests are enabled only if mdns result size is 3 or more.

### Testing

Unit tests were updated and added to cover the new code. The unit tests were failing before the code was updated. CI will also validate general functionality.

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

File: src/lib/address_resolve/tests/TestAddressResolve_DefaultImpl.cpp [hunk 1]
```diff
@@ -18,24 +18,52 @@
...
+
 namespace {
 
 using chip::Dnssd::IPAddressSorter::IpScore;
 using chip::Dnssd::IPAddressSorter::ScoreIpAddress;
 
 constexpr uint8_t kNumberOfAvailableSlots = CHIP_CONFIG_MDNS_RESOLVE_LOOKUP_RESULTS;
 
-Transport::PeerAddress GetAddressWithLowScore(uint16_t port = CHIP_PORT, Inet::InterfaceId interfaceId = Inet::InterfaceId::Null())
+Transport::PeerAddress GetAddressWithLowScore(uint16_t idx = 4, uint16_t port = CHIP_PORT,
```
Comment (cecille) [inline src/lib/address_resolve/tests/TestAddressResolve_DefaultImpl.cpp:47]: Not sure I care because this is a test, so if the CI is already done and there are no other comments, please ignore. BUT, if you end up needing to do another CI run for some reason, if you could pop in a comment about what idx is here, that would be helpful to understand the test.

**Review by cecille — APPROVED** [review]

File: src/lib/address_resolve/tests/TestAddressResolve_DefaultImpl.cpp (hunk 1 above)
Comment (andy31415) [reply src/lib/address_resolve/tests/TestAddressResolve_DefaultImpl.cpp:55]: Had a fix after all and updated comment.
