### PR TITLE
Fix python Wi-Fi/Thread setup with manual code

### LINKED ISSUE #26907: [python] ChipDeviceController BLE API do not support discovery by short discriminator
When only a manual pairing code is available, only the short discriminator (upper 4 bits of 12-bit discriminator) are available for discovery.

None of the Python API for commissioning over BLE support a version where the short discriminator is given.

Suggest:

- Adapting the ConnectBLE to have some way of expression short discriminator (e.g. by setting high bit of discriminator)
- Adapting CommissionThread/CommissionWifi to have `shortDiscriminator` keyword argument defaulting to None that causes disregarding the long `discriminator` argument, and uses short discriminator instead.

### PR DESCRIPTION
**Pull request by tcarmelveilleux**
- Plumbing was missing to pass down the short discriminator
- Passing `--manual-code 1234-567-8901` which only has short discriminator, would always fail to find device over BLE

Fixes #26907

This PR:

- Adds plumbing to detect short discriminator in Python controller
- Improves code-based setup in CHIPDeviceController to honor the SetupDiscriminator value, including whether short/long.

Testing done:
- Ran `python3 src/python_testing/TC_SC_3_6.py --commissioning-method ble-wifi --wifi-ssid MySsid --wifi-passphrase Secret123 --manual-code 2168-374-4904 --storage-path kvs1`
  - Before fix, discriminator always mismatched.
  - After fix, commissioning succeeds.
- Unit tests and other integration tests still pass

### CODE REVIEW

File: src/protocols/secure_channel/RendezvousParameters.h [hunk 1]
```diff
@@ -59,11 +60,55 @@ class RendezvousParameters
...
+        return mSetupDiscriminator.GetLongValue();
+    }
+
+    SetupDiscriminator GetSetupDiscriminator() const
+    {
+        if (!mHasDiscriminator)
+        {
+            ChipLogError(Discovery,
+                         "Get RendezvousParameters::GetSetupDiscriminator() called without discriminator in params (inconsistent). "
+                         "Returning last!");
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/RendezvousParameters.h:96]: I'm not really sure what this "Returning last" bit means...

File: src/protocols/secure_channel/RendezvousParameters.h [hunk 2]
```diff
@@ -128,9 +173,10 @@ class RendezvousParameters
     }
 
 private:
-    Transport::PeerAddress mPeerAddress;  ///< the peer node address
-    uint32_t mSetupPINCode  = 0;          ///< the target peripheral setup PIN Code
-    uint16_t mDiscriminator = UINT16_MAX; ///< the target peripheral discriminator
+    Transport::PeerAddress mPeerAddress; ///< the peer node address
+    uint32_t mSetupPINCode = 0;          ///< the target peripheral setup PIN Code
+    bool mHasDiscriminator = false;
+    SetupDiscriminator mSetupDiscriminator;
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/RendezvousParameters.h:179]: Any value in using `std::optional<SetupDiscriminator>' here?

File: src/lib/support/SetupDiscriminator.h
Comment (bzbarsky-apple) [inline src/lib/support/SetupDiscriminator.h:1]: Why the changes to this file?  They're sane if we don't care about packing SetupDiscriminator into 16 bits (which maybe we don't)....

If we do make these changes, do we still need the `kLongBits == 12` and whatnot static assert?  It was there to make it safe to store the value in a 12-bit bitfield.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/lib/support/SetupDiscriminator.h
Comment (tcarmelveilleux) [reply src/lib/support/SetupDiscriminator.h:1]: I wanted to avoid yak-shaving the public API backwards compatibility more than I need too

File: src/protocols/secure_channel/RendezvousParameters.h (hunk 1 above)
Comment (tcarmelveilleux) [reply src/protocols/secure_channel/RendezvousParameters.h:96]: Fixed

File: src/protocols/secure_channel/RendezvousParameters.h (hunk 2 above)
Comment (tcarmelveilleux) [reply src/protocols/secure_channel/RendezvousParameters.h:179]: Done

File: src/lib/support/SetupDiscriminator.h
Comment (tcarmelveilleux) [reply src/lib/support/SetupDiscriminator.h:1]: Also, `kLongBits` is used other places.

**Review by yufengwangca — APPROVED** [review]
