### PR TITLE
[OTA-R] Correct the implementation of mProviderRetryCount

### LINKED ISSUE #18824: [OTA-R] mProviderRetryCount is not implemented correctly
#### Problem

So the current code doesn't properly reset `mProviderRetryCount` after a successful download but image is not applied. Given that we now have two retry counters and they are incremented in different locations, we could be incrementing `mProviderRetryCount` even on an invalid session error:

1. Requestor successfully sends QueryImage (CASE established and `mProviderRetryCount` incremented to 1)
2. Provider is restarted
3. Requestor sends QueryImage -> invalid session detected -> CASE torn down
4. `mInvalidSessionRetryCount` incremented to 1 in `HandleIdleStateEnter`
5. `mProviderRetryCount` incremented to 2 in `SendQueryImage`

Given the current example app, after (5), we could get a successful query/download but never applied the image. The next time we attempt to query (and if it were busy), `mProviderRetryCount` already started at 2 instead of 0 and it would at most retry one more time.

 #### Proposed Solution

Increment and reset `mProviderRetryCount` properly to reflect actual provider retry attempts.

### PR DESCRIPTION
**Pull request by isiu-apple**
#### Problem

`mProviderRetryCount` was not implemented correctly.  For example:

So the current code doesn't properly reset `mProviderRetryCount` after a successful download but image is not applied. Given that we now have two retry counters and they are incremented in different locations, we could be incrementing `mProviderRetryCount` even on an invalid session error:

1. Requestor successfully sends QueryImage (CASE established and `mProviderRetryCount` incremented to 1)
2. Provider is restarted
3. Requestor sends QueryImage -> invalid session detected -> CASE torn down
4. `mInvalidSessionRetryCount` incremented to 1 in `HandleIdleStateEnter`
5. `mProviderRetryCount` incremented to 2 in `SendQueryImage`

Given the current example app, after (5), we could get a successful query/download but never applied the image. The next time we attempt to query (and if it were busy), `mProviderRetryCount` already started at 2 instead of 0 and it would at most retry one more time.

Fixes: https://github.com/project-chip/connectedhomeip/issues/18824

#### Change overview

Reset `mProviderRetryCount` to zero when QueryImage download has succeeded.

#### Testing

Ran QueryImage tests and verified that `mProviderRetryCount` is reset to zero upon successful QueryImage download.

### CODE REVIEW

**Review by tcarmelveilleux — APPROVED** [review]

File: src/app/clusters/ota-requestor/DefaultOTARequestorDriver.cpp [hunk 1]
```diff
@@ -224,6 +224,9 @@ CHIP_ERROR DefaultOTARequestorDriver::UpdateNotFound(UpdateNotFoundReason reason
 
 void DefaultOTARequestorDriver::UpdateDownloaded()
 {
+    // Download complete so reset provider retry counter
+    mProviderRetryCount = 0;
```
Comment (carol-apple) [inline src/app/clusters/ota-requestor/DefaultOTARequestorDriver.cpp:228]: I'm wondering if it's cleaner to just reset in `DefaultOTARequestorDriver::HandleIdleStateEnter`? That's where you reset the other retry counter and if we ever enter the Idle state, that means we're definitely done with retrying, e.g. in the case of Busy, the new state is DelayedOnQuery and not idle.

Comment (isiu-apple) [reply src/app/clusters/ota-requestor/DefaultOTARequestorDriver.cpp:228]: Since `mProverRetryCount` is incremented in `DefaultOTARequestorDriver::SendQueryImage()`, I think for parity it is clearer to reset it in `UpdateDownloaded()`.  There could be various reasons why OTA-R enters idle state, such as watchdog timer kicking in due to no progress.

Comment (isiu-apple) [reply src/app/clusters/ota-requestor/DefaultOTARequestorDriver.cpp:228]: @carol-apple, made the changes in `CustomOTARequestorDriver::UpdateDownloaded()` as we discussed.  So now, we reset `mProverRetryCount` in `CustomOTARequestorDriver::UpdateDownloaded()` in the case where we do not apply update. And in the case we do apply update, all member variables will be reset when the image is reloaded anyways.  This is to take care of the case where Apply Update fails and we want to count it against `mProverRetryCount`.

**Review by carol-apple — APPROVED** [review]
