### PR TITLE
Bugfix: Dont read non-existing attributes for lock/unlock commands

### LINKED ISSUE #19316: [Door Lock App] Failure of basic lock/unlock
#### Problem
**Found during smoke testing of SDK Master at Google, Jun 7 2022**

Device EFR32, Controller Linux.

With the default door-lock app example, the "lock" and "unlock" now fail.

Executed from code state:

https://github.com/project-chip/connectedhomeip/blob/ae6e092ff5acfb2faf34e4e9308217870d7954c8/examples/lock-app/lock-common/lock-app.zap#L7847

Command:
```
./out/chip-tool doorlock unlock-door $node_id 1 --timedInteractionTimeoutMs 1000
./out/chip-tool doorlock lock-door $node_id 1 --timedInteractionTimeoutMs 1000
```

Both fail with 
```
[1654591433.194073][33215:33215] CHIP:TOO: Run command failure: IM Error 0x00000501: General error: 0x01 (FAILURE)
```

Execution log on EFR32:
- [Jlinkrttc.log](https://github.com/project-chip/connectedhomeip/files/8862500/Jlinkrttc.log)

Execution log for Lock on Linux:
- [lock.log](https://github.com/project-chip/connectedhomeip/files/8862503/lock.log)

Execution log for Unlock on Linux:
- [unlock.log](https://github.com/project-chip/connectedhomeip/files/8862505/unlock.log)

When looking at the device log:
```
<detail> [EM] Found matching exchange: 16796r, Delegate: 0x2000a8d0
<detail> [EM] Rxd Ack; Removing MessageCounter:117370073 from Retrans Table on exchange 16796r
<detail> [EM] Removed CHIP MessageCounter:117370073 from RetransTable on exchange 16796r
<detail> [DMG] Timed following action arrived at 0x000000000000EE0D: handler 0x2000a8d0 exchange 16796r
<detail> [DMG] Handing timed invoke to IM engine: handler 0x2000a8d0 exchange 16796r
<detail> [DMG] Received command for Endpoint=1 Cluster=0x0000_0101 Command=0x0000_0000
<info  > [ZCL] Received command: LockDoor
<error > [ZCL] Failed to read DoorLock attribute: attribute=0x33, status=0x86
<detail> [DMG] ICR moving to [ Preparing]
```

Seems like there was an internal error to read DoorLock Attribute:

```
template <typename T>
bool DoorLockServer::GetAttribute(chip::EndpointId endpointId, chip::AttributeId attributeId,
                                  EmberAfStatus (*getFn)(chip::EndpointId endpointId, T * value), T & value)
{
    EmberAfStatus status = getFn(endpointId, &value);
    bool success         = (EMBER_ZCL_STATUS_SUCCESS == status);

    if (!success)
    {
        ChipLogError(Zcl, "Failed to read DoorLock attribute: attribute=0x%" PRIx32 ", status=0x%x", attributeId,
                     to_underlying(status));
    }
    return success;
}
```

[Code path](https://github.com/project-chip/connectedhomeip/blame/ae6e092ff5acfb2faf34e4e9308217870d7954c8/src/app/clusters/door-lock-server/door-lock-server.cpp#L3144):

```
    else
    {
        // appclusters.pdf 5.3.4.1:
        // If the RequirePINforRemoteOperation attribute is True then PINCode field SHALL be provided and the door lock SHALL NOT
        // grant access if it is not provided.
        bool requirePin = false;
        VerifyOrExit(GetAttribute(endpoint, Attributes::RequirePINforRemoteOperation::Id,
                                  Attributes::RequirePINforRemoteOperation::Get, requirePin),
                     /* credentialsOk is false here */);
        credentialsOk = !requirePin;
    }
```

Upon inspection, feature is Upon further inspection, the featuremap is 0x0133 - 0b100110011 => bits 0, 1, 4, 5, 8 set, features `PIN | RID |SCH | DPS | USR`.

It looks like the code is checking for `RequirePINforRemoteOperation` but the conformance of this attribute is `COTA & PIN `

A recent change removed the attribute from ZAP due to `COTA` feature not enabled

unnamed

However, the code is still trying to read an attribute that has now disappeared from the attribute store to affect an internal data dependency condition of the cluster.

 #### Proposed Solution

Instead of `VerifyOrExit(GetAttribute(endpoint, Attributes::RequirePINforRemoteOperation::Id, Attributes::RequirePINforRemoteOperation::Get, requirePin)`

there should be code that checks for conformance and if the feature maps doesn't have `COTA & PIN`, or if the `RequirePINforRemoteOperation` is missing, then the code should assume that a PIN required is false and proceed with open.

### PR DESCRIPTION
**Pull request by Morozov-5F**
#### Problem
* Fixes #19316 

#### Change overview
* Don't rely on the `RequirePINforRemoteOperation` attribute when it's not present.
* Update YAML tests to check lock-door and unlock-door commands when PIN is not present.

#### Testing
* Manual testing: try to lock/unlock with and without PIN code, read Lock State attribute
* Ran automated tests: `DL_LockUnlock`, `DL_Schedules`, `DL_UsersAndCredentials`.

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 1]
```diff
@@ -3143,13 +3143,19 @@ bool DoorLockServer::HandleRemoteLockOperation(chip::app::CommandHandler * comma
...
+
+        // appclusters.pdf 5.3.4.1:
+        // If the RequirePINForRemoteOperation attribute is True then PINCode field SHALL be provided and the door lock SHALL NOT
+        // grant access if it is not provided. This attribute exists when COTA and PIN features are both enabled. Otherwise we
+        // assume PIN to be OK.
+        if (SupportsCredentialsOTA(endpoint) && SupportsPIN(endpoint))
+        {
+            auto status = Attributes::RequirePINforRemoteOperation::Get(endpoint, &requirePin);
+            VerifyOrExit(
+                EMBER_ZCL_STATUS_UNSUPPORTED_ATTRIBUTE == status || EMBER_ZCL_STATUS_SUCCESS == status,
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:3156]: But if COTA and PIN are both enabled, shouldn't we fail out if the then-required attribute does not exist?

Also, the attribute is allowed to be present even if those features are disabled, I believe. @CamWms can you confirm?

@Morozov-5F

File: src/app/tests/suites/DL_LockUnlock.yaml [hunk 2]
```diff
@@ -28,6 +28,26 @@ tests:
...
+      command: "UnlockDoor"
+      timedInteractionTimeoutMs: 10000
+
+    - label: "Verify that lock state attribute value is set to Unlocked"
+      command: "readAttribute"
+      attribute: "LockState"
+      response:
+          value: 2
+
+    - label: "Try to unlock the door without a PIN"
```
Comment (bzbarsky-apple) [inline src/app/tests/suites/DL_LockUnlock.yaml:41]: This label is wrong...
