### PR TITLE
Do not start the PASE Session establishement before device scan succeeds

### LINKED ISSUE #23438: [BUG] Commissioning over BLE often fails due to PBKDFResponse timeout
### Reproduction steps

```bash
1. Build nRF Connect Lighting Example
2. Commission it using chip-tool pairing ble-thread command
```

### Bug prevalence

~80% attempts

### GitHub hash of the SDK that was being used

fac7aae4c8d7c1c916d2a6f54fc9be4dc41ea838

### Platform

nrf

### Platform Version(s)

_No response_

### Anything else?

This is probably caused by https://github.com/project-chip/connectedhomeip/pull/23335/files. After increasing `kExpectedLowProcessingTime` to 10 seconds the problem is gone. I am not sure but the timeout may not take into account the time needed to establish a connection over BLE.

### PR DESCRIPTION
**Pull request by vivien-apple**
Fixes #23438

### CODE REVIEW

File: src/controller/CHIPDeviceController.cpp [hunk 1]
```diff
@@ -740,6 +742,32 @@ CHIP_ERROR DeviceCommissioner::EstablishPASEConnection(NodeId remoteDeviceId, Re
...
+    }
+}
+
+void DeviceCommissioner::OnDiscoveredDeviceOverBleError(void * appState, CHIP_ERROR err)
+{
+    auto self   = static_cast<DeviceCommissioner *>(appState);
+    auto device = self->mDeviceInPASEEstablishment;
+    if (nullptr != device)
+    {
+        self->ReleaseCommissioneeDevice(device);
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:767]: Is it worth checking that the device's session is in fact a BLE session?  I'm a little worried about having these un-cancelable async bits, but I guess a lot of commissioning is like that.....

**Review by bzbarsky-apple — APPROVED** [review]

File: src/controller/CHIPDeviceController.cpp [hunk 2]
```diff
@@ -740,6 +742,32 @@ CHIP_ERROR DeviceCommissioner::EstablishPASEConnection(NodeId remoteDeviceId, Re
...
+void DeviceCommissioner::OnDiscoveredDeviceOverBleSuccess(void * appState, BLE_CONNECTION_OBJECT connObj)
+{
+    auto self   = static_cast<DeviceCommissioner *>(appState);
+    auto device = self->mDeviceInPASEEstablishment;
+    if (nullptr != device)
+    {
+        auto remoteId = device->GetDeviceId();
+
+        RendezvousParameters params;
+        params.SetPeerAddress(Transport::PeerAddress::BLE()).SetConnectionObject(connObj);
```
Comment (Damian-Nordic) [inline src/controller/CHIPDeviceController.cpp:754]: It almost works, but you're dropping the pincode which obviously causes SPAKE to fail. I did a quick test and added `.SetSetupPINCode(20202021)` to this line - with that addition it works.

**Review by Damian-Nordic — CHANGES_REQUESTED** [review]

**Review by Damian-Nordic — APPROVED** [review]
