### PR TITLE
[Camera] Fix camera app crashes on unexpected SDPs

### LINKED ISSUE #42247: [BUG] Camera app crashes on unexpected SDPs
### Reproduction steps

While the empty SDP like in the offer command below is unexpected (but possible), this could be used as a vector to crash a device which isn't great. We may need to either filter out unexpected content before attempting to set in the underlying webrtc stack (libdatachannel in this case), or relax the requirements in the library a bit such that it returns an error instead of crashing the app.

```
[1764701877.077] [43078:43078] [EM] >>> [E:44719r S:16233 M:93034702] (S) Msg RX from 5:2373A7EE75052BF6 [8C0C] to B52A8CD8A89A4FF7 --- Type 0001:08 (IM:InvokeCommandRequest) (B:80)
[1764701877.077] [43078:43078] [EM] Handling via exchange: 44719r, Delegate: 0xaaaab4f1e3f8
[1764701877.077] [43078:43078] [DMG] InvokeRequestMessage =
[1764701877.077] [43078:43078] [DMG] {
[1764701877.077] [43078:43078] [DMG] 	suppressResponse = false,
[1764701877.077] [43078:43078] [DMG] 	timedRequest = false,
[1764701877.077] [43078:43078] [DMG] 	InvokeRequests =
[1764701877.077] [43078:43078] [DMG] 	[
[1764701877.077] [43078:43078] [DMG] 		CommandDataIB =
[1764701877.077] [43078:43078] [DMG] 		{
[1764701877.077] [43078:43078] [DMG] 			CommandPathIB =
[1764701877.077] [43078:43078] [DMG] 			{
[1764701877.077] [43078:43078] [DMG] 				EndpointId = 0x1,
[1764701877.077] [43078:43078] [DMG] 				ClusterId = 0x553,
[1764701877.077] [43078:43078] [DMG] 				CommandId = 0x2,
[1764701877.077] [43078:43078] [DMG] 			},
[1764701877.077] [43078:43078] [DMG]
[1764701877.077] [43078:43078] [DMG] 			CommandFields =
[1764701877.077] [43078:43078] [DMG] 			{
[1764701877.077] [43078:43078] [DMG] 				0x0 = NULL
[1764701877.077] [43078:43078] [DMG] 				0x1 = "" (0 chars),
[1764701877.077] [43078:43078] [DMG] 				0x2 = 3 (unsigned),
[1764701877.077] [43078:43078] [DMG] 				0x3 = 0 (unsigned),
[1764701877.077] [43078:43078] [DMG] 				0x4 = 3 (unsigned),
[1764701877.077] [43078:43078] [DMG] 				0x5 = 3 (unsigned),
[1764701877.077] [43078:43078] [DMG] 			},
[1764701877.077] [43078:43078] [DMG] 			Ref = 0x0,
[1764701877.077] [43078:43078] [DMG] 		},
[1764701877.077] [43078:43078] [DMG]
[1764701877.077] [43078:43078] [DMG] 	],
[1764701877.077] [43078:43078] [DMG]
[1764701877.077] [43078:43078] [DMG] 	InteractionModelRevision = 12
[1764701877.077] [43078:43078] [DMG] },
[1764701877.077] [43078:43078] [DMG] AccessControl: checking f=5 a=c s=0x2373A7EE75052BF6 t=0x00000001 c=0x0000_0553 e=1 p=o r=i
[1764701877.077] [43078:43078] [DMG] AccessControl: allowed
[1764701877.077] [43078:43078] [DMG] AccessControl: checking f=5 a=c s=0x2373A7EE75052BF6 t=0x00000001 c=0x0000_0553 e=1 p=o r=i
[1764701877.077] [43078:43078] [DMG] AccessControl: allowed
[1764701877.077] [43078:43078] [DMG] Received command for Endpoint=1 Cluster=0x0000_0553 Command=0x0000_0002
[1764701877.077] [43078:43078] [ZCL] WebRTCTransportProvider: InvokeCommand called with CommandId=0x00000002
[1764701877.077] [43078:43078] [CAM] Video stream ID 3 is valid and allocated
[1764701877.077] [43078:43078] [CAM] Audio stream ID 3 is valid and allocated
[1764701877.077] [43078:43078] [CAM] HandleProvideOffer called
[1764701877.077] [43078:43078] [CAM] WebrtcTransport created
[1764701877.077] [43078:43078] [CAM] ExtractMidFromSdp: empty SDP or media type
[1764701877.078] [43078:43078] [CAM] ExtractMidFromSdp: empty SDP or media type
[1764701877.078] [43078:43078] [CAM] Payload type for codec H264 not found
[1764701877.078] [43078:43078] [CAM] Payload type for codec opus not found
[1764701877.078] [43078:43078] [CAM] Extracted audioMid: , payloadType: 111
[1764701877.078] [43078:43078] [CAM] Extracted videoMid: , payloadType: 96
[1764701877.078] [43078:43078] [CAM] WebrtcTransport moving to [ SendingAnswer ]
libc++abi: terminating due to uncaught exception of type std::invalid_argument: Remote description has no ICE user fragment
```

### Bug prevalence

Consistent

### GitHub hash of the SDK that was being used

766134f3a7461c60cd06da565a2835096b91258d

### Platform

other, raspi

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Summary

We need to validates that an SDP contains the minimum required fields for WebRTC before use.
This required by the underlying WebRTC library. Without this check, the library would throw an exception when trying to set the remote description.

#### Related issues

Fixes: #42247

#### Testing

Validate by CI

#### Readability checklist

The checklist below will help the reviewer finish PR review in time and keep the
code readable:

-   [ ] PR title is
        [descriptive](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html#title-formatting)
-   [ ] Apply the
        [_“When in Rome…”_](https://project-chip.github.io/connectedhomeip-doc/style/CODING_STYLE_GUIDE.html)
        rule (coding style)
-   [ ] PR size is short
-   [ ] Try to avoid "squashing" and "force-update" in commit history
-   [ ] CI time didn't increase

See: [Pull Request Guidelines](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html)

### CODE REVIEW

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp [hunk 1]
```diff
@@ -37,6 +37,63 @@ namespace {
...
+bool ValidateSdpFields(const std::string & sdp)
+{
+    if (sdp.empty())
+    {
+        ChipLogError(Camera, "ValidateSdpFields: SDP is empty");
+        return false;
+    }
+
+    // Check for required SDP fields
+    bool hasMediaLine   = (sdp.find("m=") != std::string::npos);
```
Comment (andy31415) [inline examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp]: This separates out bools from the messages, which seems a bit harder to follow/extend. How about a loop approach like:

```cpp

    struct SdpRequirement
    {
        const char * substring;
        const char * description;
    };

    // Define the list of required substrings and their corresponding descriptions for error logging.
    static const SdpRequirement kRequirements[] = {
        { "m=", "media line" },
        { "a=ice-ufrag:", "ICE user fragment" },
        { "a=ice-pwd:", "ICE password" },
        { "a=fingerprint:", "DTLS fingerprint" },
    };

    for (const auto & req : kRequirements)
    {
        if (sdp.find(req.substring) == std::string::npos)
        {
            ChipLogError(Camera, "ValidateSdpFields: SDP has no %s (%s): %s", req.description, req.substring, sdp.c_str());
            return false;
        }
    }

    return true;
```

Comment (andy31415) [reply examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp]: Generally I wonder even if we need the empty check: empty SDP will obviously fail the checks and as long as we report the string, we will see it is empty.

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp [hunk 2]
```diff
@@ -262,6 +319,12 @@ CHIP_ERROR WebRTCProviderManager::HandleProvideOffer(const ProvideOfferRequestAr
 {
     ChipLogProgress(Camera, "HandleProvideOffer called");
 
+    if (!ValidateSdpFields(args.sdp))
+    {
+        ChipLogError(Camera, "HandleProvideOffer: Invalid SDP offer received");
```
Comment (andy31415) [inline examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp]: we already logged the error in "validate". Maybe we should not log again.

File: src/controller/webrtc/WebRTCClient.cpp [hunk 3]
```diff
@@ -30,6 +30,63 @@ int ExtractDynamicPayloadType(const std::string & sdp, const std::string & type,
...
+bool ValidateSdpFields(const std::string & sdp)
+{
+    if (sdp.empty())
+    {
+        ChipLogError(NotSpecified, "ValidateSdpFields: SDP is empty");
+        return false;
+    }
+
+    // Check for required SDP fields
+    bool hasMediaLine   = (sdp.find("m=") != std::string::npos);
```
Comment (andy31415) [inline src/controller/webrtc/WebRTCClient.cpp]: This seems duplidated - same comments apply and should we not find a way to share this? it could be within some camera clusters or other shared code and not inside clusters.
We could also accept a `const char *` as input and then not worry about std::string usage.

Comment (yufengwangca) [reply src/controller/webrtc/WebRTCClient.cpp]: The matter spec only define the SDP exchange protocol, it does not specify how to validate the SDP content. We have two independent implementation of WebRTCClient, one for camera-app and one for Test Harness, we don't share the code between those two apps, same for other implementations.

**Comment by marktrayer** [comment]
Couldn't we home the new structs and logic in the server cluster, rather than duplicating where it is used?

File: src/controller/webrtc/WebRTCClient.cpp [hunk 4]
```diff
@@ -30,6 +30,56 @@ int ExtractDynamicPayloadType(const std::string & sdp, const std::string & type,
...
+    }
+
+    struct SdpRequirement
+    {
+        const char * substring;
+        const char * description;
+    };
+
+    // Define the list of required substrings and their corresponding descriptions for error logging.
+    static const SdpRequirement kRequirements[] = {
```
Comment (pidarped) [inline src/controller/webrtc/WebRTCClient.cpp:73]: If we want to use this validation function for the minimum viable SDP format before passing it on to the WebRTC stack, maybe we should also include some of the other basic parameters that the SDP structure should have:
version(v=), originator(o=) containing session ids, session name(s=), connection(c=), timing (t=) lines.
Also, the number of m= lines should match between the Offer and Answer I believe.

Comment (yufengwangca) [reply src/controller/webrtc/WebRTCClient.cpp:73]: Updated with the mandatory SDP session-level fields per RFC 8866, Cross-checking across multiple Commands adds complexity because it requires matching each Answer to its corresponding Offer and introduces dependencies between command handlers.

**Review by pidarped — APPROVED** [review]

**Review by joonhaengHeo — APPROVED** [review]
