### PR TITLE
DeviceCommissioner: Track ExtendArmFailSafe conditionally and manage CASE callbacks accurately

### LINKED ISSUE #32521: VerifyOrDie failure at src/controller/CHIPDeviceController.cpp:2519: !mInvokeCancelFn
```
[1709828063158] [6218:42944490] [CTL] Session establishment failed for <0000000000000011, 2>, error: src/app/OperationalSessionSetup.cpp:257: CHIP Error 0x00000032: Timeout.  Next retry expected to get a response to Sigma1 or fail within 10 seconds
[1709828063158] [6218:42944490] [CTL] Arming failsafe (70 seconds)
[1709828063158] [6218:42944490] [SPT] VerifyOrDie failure at src/controller/CHIPDeviceController.cpp:2519: !mInvokeCancelFn
```

Introduced in #32233

### PR DESCRIPTION
**Pull request by ksperling-apple**
Only pass a context into ExtendArmFailSafe callbacks and track them as the
current cancelable invocation when it is actually a part of the sequential
commissioning flow. Treat as "fire and forget" when the method is called by an
external client, or when we're handling CASE retries.

Fixes #32521

Also manage CASE callbacks accurately
- Ensure all callbacks are unregistered once CASE setup is done.
- Cancel CASE setup callbacks on StopPairing.

Add CASEServerBusy fault injection point and handle `--faults` in example apps when building with fault injection.

### CODE REVIEW

File: src/controller/CHIPDeviceController.cpp [hunk 1]
```diff
@@ -1809,56 +1822,43 @@ void DeviceCommissioner::OnDeviceConnectedFn(void * context, Messaging::Exchange
...
     }
-
-    if (commissioner->mDeviceBeingCommissioned == nullptr ||
-        commissioner->mDeviceBeingCommissioned->GetDeviceId() != peerId.GetNodeId())
+    else
     {
-        // Not the device we are trying to commission.
-        return;
-    }
+        // Ensure that commissioning stage advancement is done based on seeing an error.
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1848]:
```suggestion
```

File: src/controller/CHIPDeviceController.cpp [hunk 2]
```diff
@@ -1809,56 +1822,43 @@ void DeviceCommissioner::OnDeviceConnectedFn(void * context, Messaging::Exchange
...
+        // Ensure that commissioning stage advancement is done based on seeing an error.
+        if (error == CHIP_NO_ERROR)
+        {
+            // Ensure that commissioning stage advancement is done based on seeing an error.
+            if (error == CHIP_NO_ERROR)
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1853]: This looks like some weird rebase issue, with doubled code?  But also, if we are in this branch we know error == CHIP_NO_ERROR before we hit any of the doubled code, no?

File: src/controller/CHIPDeviceController.cpp [hunk 3]
```diff
@@ -1809,56 +1822,43 @@ void DeviceCommissioner::OnDeviceConnectedFn(void * context, Messaging::Exchange
...
+            {
+                ChipLogError(Controller, "Device connection failed without a valid error code. Making one up.");
+                error = CHIP_ERROR_INTERNAL;
+            }
 
-    if (commissioner->mCommissioningStage == CommissioningStage::kFindOperational &&
-        commissioner->mCommissioningDelegate != nullptr)
-    {
+            commissioner->CommissioningStageComplete(error);
+            commissioner->CommissioningStageComplete(error);
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1860]: Again, why all the extra copies of this?  Shouldn't be here.

File: src/controller/CHIPDeviceController.cpp [hunk 4]
```diff
@@ -2513,19 +2516,20 @@ CHIP_ERROR
...
-                                             Optional<System::Clock::Timeout> timeout)
+                                             Optional<System::Clock::Timeout> timeout, bool useContext)
 
 {
-    VerifyOrDie(!mInvokeCancelFn); // we don't make parallel calls
+    VerifyOrDie(!(useContext && mInvokeCancelFn)); // we don't make parallel calls that we track with context
 
-    auto onSuccessCb = [context = this, successCb](const app::ConcreteCommandPath & aPath, const app::StatusIB & aStatus,
-                                                   const typename RequestObjectT::ResponseType & responseData) {
+    void * context   = (useContext) ? this : nullptr;
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:2524]: Why the extra parens?

File: src/controller/CHIPDeviceController.cpp [hunk 5]
```diff
@@ -2513,19 +2516,20 @@ CHIP_ERROR
...
+    auto onSuccessCb = [context, successCb](const app::ConcreteCommandPath & aPath, const app::StatusIB & aStatus,
+                                            const typename RequestObjectT::ResponseType & responseData) {
         successCb(context, responseData);
     };
-    auto onFailureCb = [context = this, failureCb](CHIP_ERROR aError) { failureCb(context, aError); };
+    auto onFailureCb = [context, failureCb](CHIP_ERROR aError) { failureCb(context, aError); };
 
     return InvokeCommandRequest(device->GetExchangeManager(), device->GetSecureSession().Value(), endpoint, request, onSuccessCb,
-                                onFailureCb, NullOptional, timeout, &mInvokeCancelFn);
+                                onFailureCb, NullOptional, timeout, (useContext) ? &mInvokeCancelFn : nullptr);
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:2532]: Again, why extra parens?

File: src/controller/CHIPDeviceController.h [hunk 6]
```diff
@@ -957,14 +962,19 @@ class DLL_EXPORT DeviceCommissioner : public DeviceController,
     CommissioneeDeviceProxy * FindCommissioneeDevice(const Transport::PeerAddress & peerAddress);
     void ReleaseCommissioneeDevice(CommissioneeDeviceProxy * device);
 
+    bool ExtendArmFailSafeInternal(DeviceProxy * proxy, CommissioningStage step, uint16_t armFailSafeTimeout,
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.h:965]: This needs some documentation, especially because `useContext` is not very clear.

Perhaps that argument should be called `isSequentialCommissioningStep` or something?

I would also prefer the new argument not be optional, since forgetting it when it should be false can lead to VerifyOrDie failures.  Just require callers to think about what they want to pass.

File: src/darwin/Framework/CHIPTests/MTRPairingTests.m [hunk 7]
```diff
@@ -29,6 +29,7 @@
 // Fixture: chip-all-clusters-app --KVS "$(mktemp -t chip-test-kvs)" --interface-id -1 \
     --dac_provider credentials/development/commissioner_dut/struct_cd_origin_pid_vid_correct/test_case_vector.json \
     --product-id 32768 --discriminator 3839
+// CASE retry code paths can be tested using --faults chip_CASEServerBusy_f1 (or similar)
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIPTests/MTRPairingTests.m:32]: But nothing i doing that right now, right?  This is for local, not CI testing?  Might be good to make this comment a bit less cryptic.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/controller/CHIPDeviceController.cpp (hunk 2 above)
Comment (ksperling-apple) [reply src/controller/CHIPDeviceController.cpp:1853]: Hm yeah the rebase totally messed this one up.

File: src/controller/CHIPDeviceController.cpp (hunk 3 above)
Comment (ksperling-apple) [reply src/controller/CHIPDeviceController.cpp:1860]: Yeah this is all part of the same rebase issue.

File: src/controller/CHIPDeviceController.cpp (hunk 4 above)
Comment (ksperling-apple) [reply src/controller/CHIPDeviceController.cpp:2524]: I think ternary expressions are more readable when the condition is in parentheses.

File: src/darwin/Framework/CHIPTests/MTRPairingTests.m (hunk 7 above)
Comment (ksperling-apple) [reply src/darwin/Framework/CHIPTests/MTRPairingTests.m:32]: Yes at the moment it's just a note for manual testing. Hopefully at some point we can integrate the fault injection cluster to include automated tests for this.

File: src/controller/CHIPDeviceController.cpp [hunk 8]
```diff
@@ -1911,11 +1902,12 @@ void DeviceCommissioner::OnDeviceConnectionRetryFn(void * context, const ScopedN
...
         failsafeTimeout = static_cast<uint16_t>(retryTimeout.count() + kDefaultFailsafeTimeout);
     }
-    // A false return from ExtendArmFailSafe is fine; we don't want to make the
-    // fail-safe shorter here.
-    self->ExtendArmFailSafe(commissioneeDevice, CommissioningStage::kFindOperational, failsafeTimeout,
-                            MakeOptional(kMinimumCommissioningStepTimeout), OnExtendFailsafeForCASERetrySuccess,
-                            OnExtendFailsafeForCASERetryFailure);
+
+    // Treat this command as a fire-and-forget request (useContext = false).
+    // A false return is fine; we don't want to make the fail-safe shorter here.
```
[the remark this answers is not in the document]
Comment (ksperling-apple) [reply src/controller/CHIPDeviceController.cpp:1907]: Ah I missed that comment.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/controller/CHIPDeviceController.cpp [hunk 9]
```diff
@@ -1926,6 +1915,8 @@ void DeviceCommissioner::OnDeviceConnectionRetryFn(void * context, const ScopedN
                  ChipLogValueScopedNodeId(peerId), error.Format(), retryTimeout.count());
 
     auto self = static_cast<DeviceCommissioner *>(context);
+    VerifyOrDie(self->mCommissioningStage == CommissioningStage::kFindOperational);
+    VerifyOrDie(self->mDeviceBeingCommissioned->GetDeviceId() == peerId.GetNodeId());
```
Comment (tcarmelveilleux) [inline src/controller/CHIPDeviceController.cpp:1919]: We are certain this cannot ever be false at runtime, in a recoverable way, right?

File: src/controller/CHIPDeviceController.cpp [hunk 10]
```diff
@@ -2552,19 +2543,22 @@ CHIP_ERROR
...
+    auto onSuccessCb = [context, successCb](const app::ConcreteCommandPath & aPath, const app::StatusIB & aStatus,
+                                            const typename RequestObjectT::ResponseType & responseData) {
         successCb(context, responseData);
     };
-    auto onFailureCb = [context = this, failureCb](CHIP_ERROR aError) { failureCb(context, aError); };
+    auto onFailureCb = [context, failureCb](CHIP_ERROR aError) { failureCb(context, aError); };
 
     return InvokeCommandRequest(device->GetExchangeManager(), device->GetSecureSession().Value(), endpoint, request, onSuccessCb,
-                                onFailureCb, NullOptional, timeout, &mInvokeCancelFn);
+                                onFailureCb, NullOptional, timeout, (!fireAndForget) ? &mInvokeCancelFn : nullptr);
```
Comment (tcarmelveilleux) [inline src/controller/CHIPDeviceController.cpp:2561]: Suggest `(fireAndForget) ? nullptr : &mInvokeCancelFn`

Ternaries with inverse single conditions are more confusing than just reversing the order of the outputs.

File: examples/platform/linux/Options.cpp [hunk 11]
```diff
@@ -94,6 +102,9 @@ enum
 #if CONFIG_BUILD_FOR_HOST_UNIT_TEST
     kDeviceOption_SubscriptionResumptionRetryIntervalSec = 0x1026,
 #endif
+#if CHIP_WITH_NLFAULTINJECTION
+    kDeviceOption_FaultInjection = 0x1027,
```
Comment (tcarmelveilleux) [inline examples/platform/linux/Options.cpp:106]: Would have liked to see an integration test make use of the fault injection just added.

**Review by tcarmelveilleux — APPROVED** [review]

File: examples/platform/linux/Options.cpp (hunk 11 above)
Comment (ksperling-apple) [reply examples/platform/linux/Options.cpp:106]: Added to my TODO list for a follow-up: https://github.com/project-chip/connectedhomeip/issues/32541

File: src/controller/CHIPDeviceController.cpp (hunk 9 above)
Comment (ksperling-apple) [reply src/controller/CHIPDeviceController.cpp:1919]: Yes, we're invalidating the CASE callbacks when we're done with them and on StopPairing now, so there should be no way to get stray callbacks anymore.

File: src/controller/CHIPDeviceController.cpp (hunk 10 above)
Comment (ksperling-apple) [reply src/controller/CHIPDeviceController.cpp:2561]: Will do in a follow-up.
