### PR TITLE
Fix reading attribute activeLocale failure

### LINKED ISSUE #13771: Not able to read the attribute with string type value
#### Problem
 
 I found the default generated attribute get API does not work for the attrbute with type of string, such as:
  
namespace Description {
EmberAfStatus Get(chip::EndpointId endpoint, chip::MutableCharSpan value); // char_string
EmberAfStatus Set(chip::EndpointId endpoint, chip::CharSpan value);

The Set API works well.

 #### Proposed Solution
<suggested fix, suggested enhancement>

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
What is being fixed?  Examples:
* Always fails to read activeLocale in emberAfLocalizationConfigurationClusterServerInitCallback, the reason is we pass a null pointer with a zero-sized buffer to EmberAfStatus status = ActiveLocale::Get(endpoint, activeLocale)
* Fix https://github.com/project-chip/connectedhomeip/issues/13771

#### Change overview
Fix reading attribute activeLocale failure

#### Testing
How was this tested? (at least one bullet point required)
* During bootup, check the log and confirm no error message Failed to read ActiveLocale with error during initialization in the log.

### CODE REVIEW

File: src/app/clusters/localization-configuration-server/localization-configuration-server.cpp [hunk 1]
```diff
@@ -150,7 +152,9 @@ void emberAfLocalizationConfigurationClusterServerInitCallback(EndpointId endpoi
 {
     DeviceLayer::AttributeList<CharSpan, DeviceLayer::kMaxLanguageTags> supportedLocales;
     CharSpan validLocale;
-    MutableCharSpan activeLocale;
+
+    char outBuffer[kMaxActiveLocaleLength] = "";
+    MutableCharSpan activeLocale(outBuffer, kMaxActiveLocaleLength);
```
Comment (bzbarsky-apple) [inline src/app/clusters/localization-configuration-server/localization-configuration-server.cpp:157]:
```suggestion
    char outBuffer[kMaxActiveLocaleLength];
    MutableCharSpan activeLocale(outBuffer);
```

**Review by bzbarsky-apple — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]
