### PR TITLE
[Darwin] Implement multiple read and subscribe

### LINKED ISSUE #25424: How to read multiple attribute in darwin platform
### Reproduction steps

There is no way to read multiple attributes at once from the Darwin platform.

We have confirmed that one attribute can be read using the readAttributeWithEndpointId of MTRBaseDeviceClass, and that endpointId, clusterId, attributeId can be used as null value(nil) parameter to read all attributes. However, it is impossible to deliver in List form like Android.

https://github.com/project-chip/connectedhomeip/blob/1a1d0c3c23d78f8fa72c7ef0d6ad88ff05ef0224/src/controller/java/src/chip/devicecontroller/ChipDeviceController.java#L567

### Bug prevalence

always

### GitHub hash of the SDK that was being used

1a1d0c3c23d78f8fa72c7ef0d6ad88ff05ef0224

### Platform

darwin

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by joonhaengHeo**
Fixes #25424 

1. Implement multiple read attribute or event.
2. Implement multiple subscribe attribute or event.

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 1]
```diff
@@ -229,6 +282,48 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+/**
+ * Reads multiple attributes or events from the device.
+ *
+ * Nil values for endpointID, clusterID, attributeID, eventID indicate wildcards
+ * (e.g. nil attributeID means "read all the attributes from the endpoint(s) and
+ * cluster(s) that match endpointID/clusterID").
+ *
+ * If the list of MTRAttributePath class as input parameters, device will be read multiple attributes.
+ * Similarly,If the list of MTRAttributePath class as input parameters, device will be read multiple events.
+ * (Device can be read both of them.)
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:294]: Perhaps:
```suggestion
 * Lists of attribute and event paths to read can be provided via attributePaths and eventPaths.
```

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 2]
```diff
@@ -833,6 +847,121 @@ void OnDeallocatePaths(chip::app::ReadPrepareParams && aReadPrepareParams) overr
     Platform::UniquePtr<app::ReadClient> mReadClient;
 };
 
+template <typename DecodableValueType> class BufferedMultipleReadClientCallback final : public app::ReadClient::Callback {
```
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:850]: Yes, I'll fix it.

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 3]
```diff
@@ -229,6 +282,48 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
                           completion:(MTRDeviceResponseHandler)completion
     API_AVAILABLE(ios(16.4), macos(13.3), watchos(9.4), tvos(16.4));
 
+/**
+ * Reads multiple attributes or events from the device.
+ *
+ * Nil values for endpointID, clusterID, attributeID, eventID indicate wildcards
+ * (e.g. nil attributeID means "read all the attributes from the endpoint(s) and
+ * cluster(s) that match endpointID/clusterID").
```
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.h:290]: Comment will be fixed.

File: src/darwin/Framework/CHIP/MTRBaseDevice.h (hunk 1 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.h:294]: Comment will be fixed.

[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.h:294]: Comment will be fixed.

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 4]
```diff
@@ -229,6 +282,48 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+ *
+ * If the list of MTRAttributePath class as input parameters, device will be read multiple attributes.
+ * Similarly,If the list of MTRAttributePath class as input parameters, device will be read multiple events.
+ * (Device can be read both of them.)
+ *
+ * The completion will be called with an error if the entire read interaction fails.
+ * Otherwise it will be called with values, which may be empty (e.g. if no paths
+ * matched the wildcard) or may include per-path errors if particular paths
```
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.h:298]: Comment will be fixed.

File: src/darwin/Framework/CHIP/MTRBaseDevice.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.h:294]: 1. I added both empty arrays exception cases.
2. There is no limitation of array length.

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 5]
```diff
@@ -229,6 +282,48 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+- (void)readWithAttributePaths:(NSArray<MTRAttributePath *> * _Nullable)attributePaths
+                    EventPaths:(NSArray<MTREventPath *> * _Nullable)eventPaths
+                        params:(MTRReadParams * _Nullable)params
+                         queue:(dispatch_queue_t)queue
+                    completion:(MTRDeviceResponseHandler)completion;
+
+/**
+ * Subscribes to the specified attributes on the device.
+ *
+ * Nil values for endpointID, clusterID, attributeID, eventID indicate wildcards
```
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.h:310]: Comment will be fixed.

File: src/darwin/Framework/CHIP/MTRBaseDevice.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRBaseDevice.h]: > There is no limitation of array length.

This is clearly false, since at some point things won't fit in a packet...

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 6]
```diff
@@ -1818,6 +2205,15 @@ - (instancetype)initWithPath:(const ConcreteClusterPath &)path
     return self;
 }
 
+- (instancetype)initWithEndpointID:(NSNumber * _Nullable)endpointID clusterID:(NSNumber * _Nullable)clusterID
+{
+    if (self = [super init]) {
+        _endpoint = endpointID;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:2211]: This is broken.  The attribute backed by this ivar is claimed to be non-nullable, but this might be assigning nil to the ivar.

As the comments on these interfaces say, they represent concrete paths, without wildcards.  If you need to represent possibly-wildcard paths, you need a different set of interfaces.  You can't use MTRAttributePath/MTREventPath to represent things with wildcards.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/darwin/Framework/CHIP/MTRBaseDevice.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.h]: I have a concern about this.

If you use wildcard, you can send one value, but you can receive several values.
I wonder if it is right to set a limit for this reason.

Also, if there is a problem, I think this will be enough because an error will be sent to the callback. Do you have any other opinions?

(Keep it unresolved until the end of the conversation. The conversation is over If you think about it, please reserve it.)

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 6 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:2211]: Instead of nil, I will modify it to handle wildcard values by defining them. (It will be corrected at the end of the entire conversation.)
e.g.,`NSNumber * const MTRWildCardAttributeId = kInvalidAttributeId;`

Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:2211]: Please do not use `kInvalidAttributeId` in the API.  The fact that such a thing exists should really not be exposed.  The right representation for wildcards is nil.  You just need a path representation that can represent wildcard paths, instead of repurposing the one we have right now which is explicitly for concrete paths only.

Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:2211]: I understand your comment that you should create an interface separate from MTRAttributePath / MTREventPath. By the way, is there a reason you have to make it separately? Of course, I agree that the current implementation has a problem that wildcards are not processed, but since the properties in MTRAttributePath are the same, I think it's okay to use them together. Also, it is difficult to create another interface name because the meaning of the MTRAttributePath name is not the meaning of the output. Can you recommend another interface name? (Attribute, Event)

File: src/darwin/Framework/CHIP/MTRBaseDevice.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.h]: What sort of limit?
-> I understood you mean you want the implementation to have a length limit.

Have you tested (and in general, where are the unit tests for the new API)? I expect the errors that come back in that situation are pretty inscrutable, so we should document the limitations as well.
-> Internally implemented on the CHIPTool side and tested, but not implemented with UnitTest. I will check this out and add it.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 6 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:2211]: > By the way, is there a reason you have to make it separately?

Well... we can't change `MTRAttributePath`, right?  What other options do you see?

>  Can you recommend another interface name?

MTRAttributeRequestPath, MTREventRequestPath?

File: src/darwin/Framework/CHIP/MTRBaseDevice.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRBaseDevice.h]: >  -> I understood you mean you want the implementation to have a length limit.

The implementation _on the server_ absolutely has a length limit.  What that limit is depends on the device; the only guarantee is that 9 paths must be supported.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 6 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: Thank you about your advice. I modified.

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 7]
```diff
@@ -130,6 +130,37 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
     MTRTransportTypeTCP,
 } API_AVAILABLE(ios(16.4), macos(13.3), watchos(9.4), tvos(16.4));
 
+/**
+ * A path indicating a attribute on a device.
+ * If value is a wildcard, set it to nil.
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:135]:
```suggestion
 * A path indicating an attribute being requested (for read or subscribe).  
 *
 * nil is used to represent wildcards.
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 8]
```diff
@@ -130,6 +130,37 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+ */
+MTR_NEWLY_AVAILABLE;
+@interface MTRAttributeRequestPath : NSObject <NSCopying>
+@property (nonatomic, readonly, copy) NSNumber * _Nullable endpoint;
+@property (nonatomic, readonly, copy) NSNumber * _Nullable cluster;
+@property (nonatomic, readonly, copy) NSNumber * _Nullable attribute;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:141]:
```suggestion
@property (nonatomic, readonly, copy, nullable) NSNumber * endpoint;
@property (nonatomic, readonly, copy, nullable) NSNumber * cluster;
@property (nonatomic, readonly, copy, nullable) NSNumber * attribute;
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 9]
```diff
@@ -130,6 +130,37 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+
++ (MTRAttributeRequestPath *)requestPathWithEndpointID:(NSNumber * _Nullable)endpointID
+                                             clusterID:(NSNumber * _Nullable)clusterID
+                                           attributeID:(NSNumber * _Nullable)attributeID MTR_NEWLY_AVAILABLE;
+@end
+
+/**
+ * A path indicating a event on a device.
+ * If value is a wildcard, set it to nil.
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:150]: * A path indicating an event being requested (for read or subscribe).  
 *
 * nil is used to represent wildcards.

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 10]
```diff
@@ -130,6 +130,37 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+ */
+MTR_NEWLY_AVAILABLE;
+@interface MTREventRequestPath : NSObject <NSCopying>
+@property (nonatomic, readonly, copy) NSNumber * _Nullable endpoint;
+@property (nonatomic, readonly, copy) NSNumber * _Nullable cluster;
+@property (nonatomic, readonly, copy) NSNumber * _Nullable event;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:156]:
```suggestion
@property (nonatomic, readonly, copy, nullable) NSNumber * endpoint;
@property (nonatomic, readonly, copy, nullable) NSNumber * cluster;
@property (nonatomic, readonly, copy, nullable) NSNumber * event;
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 11]
```diff
@@ -229,6 +260,38 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
                           completion:(MTRDeviceResponseHandler)completion
     API_AVAILABLE(ios(16.4), macos(13.3), watchos(9.4), tvos(16.4));
 
+/**
+ * Reads multiple attributes or events from the device.
+ *
+ * Nil value is treated as empty array for attributePaths and eventPaths.
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:266]:
```suggestion
 * Nil is treated as an empty array for attributePaths and eventPaths.
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 12]
```diff
@@ -130,6 +130,37 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
     MTRTransportTypeTCP,
 } API_AVAILABLE(ios(16.4), macos(13.3), watchos(9.4), tvos(16.4));
 
+/**
+ * A path indicating a attribute on a device.
+ * If value is a wildcard, set it to nil.
+ */
+MTR_NEWLY_AVAILABLE;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:137]:
```suggestion
MTR_NEWLY_AVAILABLE
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 13]
```diff
@@ -130,6 +130,37 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
++ (MTRAttributeRequestPath *)requestPathWithEndpointID:(NSNumber * _Nullable)endpointID
+                                             clusterID:(NSNumber * _Nullable)clusterID
+                                           attributeID:(NSNumber * _Nullable)attributeID MTR_NEWLY_AVAILABLE;
+@end
+
+/**
+ * A path indicating a event on a device.
+ * If value is a wildcard, set it to nil.
+ */
+MTR_NEWLY_AVAILABLE;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:152]:
```suggestion
MTR_NEWLY_AVAILABLE
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 14]
```diff
@@ -229,6 +260,38 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
     API_AVAILABLE(ios(16.4), macos(13.3), watchos(9.4), tvos(16.4));
 
+/**
+ * Reads multiple attributes or events from the device.
+ *
+ * Nil value is treated as empty array for attributePaths and eventPaths.
+ *
+ * Lists of attribute and event paths to read can be provided via attributePaths and eventPaths.
+ *
+ * The completion will be called with an error if  the input parameter has a problem(e.g., both attributePaths and eventPaths are
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:270]:
```suggestion
 * The completion will be called with an error if  the input parameters are invalid (e.g., both attributePaths and eventPaths are
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 15]
```diff
@@ -229,6 +260,38 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+ * empty.) or the entire read interaction fails. Otherwise it will be called with values, which may be empty (e.g. if no paths
+ * matched the wildcard) or may include per-path errors if particular paths failed.
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:272]:
```suggestion
 * matched the wildcard paths passed in) or may include per-path errors if particular paths failed.
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 16]
```diff
@@ -229,6 +260,38 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+ */
+- (void)readWithAttributePaths:(NSArray<MTRAttributeRequestPath *> * _Nullable)attributePaths
+                    EventPaths:(NSArray<MTREventRequestPath *> * _Nullable)eventPaths
+                        params:(MTRReadParams * _Nullable)params
+                         queue:(dispatch_queue_t)queue
+                    completion:(MTRDeviceResponseHandler)completion MTR_NEWLY_AVAILABLE;
+/**
+ * Subscribes multiple attributes or events from the device.
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:280]:
```suggestion
 * Subscribes to multiple attribute or event paths.
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 17]
```diff
@@ -229,6 +260,38 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
                           completion:(MTRDeviceResponseHandler)completion
     API_AVAILABLE(ios(16.4), macos(13.3), watchos(9.4), tvos(16.4));
 
+/**
+ * Reads multiple attributes or events from the device.
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:264]:
```suggestion
 * Reads multiple attribute or event paths from the device.
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 18]
```diff
@@ -229,6 +260,38 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+ */
+- (void)readWithAttributePaths:(NSArray<MTRAttributeRequestPath *> * _Nullable)attributePaths
+                    EventPaths:(NSArray<MTREventRequestPath *> * _Nullable)eventPaths
+                        params:(MTRReadParams * _Nullable)params
+                         queue:(dispatch_queue_t)queue
+                    completion:(MTRDeviceResponseHandler)completion MTR_NEWLY_AVAILABLE;
+/**
+ * Subscribes multiple attributes or events from the device.
+ *
+ * Nil value is treated as empty array for attributePaths and eventPaths.
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:282]:
```suggestion
 * Nil is treated as an empty array for attributePaths and eventPaths.
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 19]
```diff
@@ -229,6 +260,38 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+ *
+ * Lists of attribute and event paths to subscribe can be provided via attributePaths and eventPaths.
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:284]:
```suggestion
 * Lists of attribute and event paths to subscribe to can be provided via attributePaths and eventPaths.
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 20]
```diff
@@ -229,6 +260,38 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+ * Nil value is treated as empty array for attributePaths and eventPaths.
+ *
+ * Lists of attribute and event paths to read can be provided via attributePaths and eventPaths.
+ *
+ * The completion will be called with an error if  the input parameter has a problem(e.g., both attributePaths and eventPaths are
+ * empty.) or the entire read interaction fails. Otherwise it will be called with values, which may be empty (e.g. if no paths
+ * matched the wildcard) or may include per-path errors if particular paths failed.
+ */
+- (void)readWithAttributePaths:(NSArray<MTRAttributeRequestPath *> * _Nullable)attributePaths
+                    EventPaths:(NSArray<MTREventRequestPath *> * _Nullable)eventPaths
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:275]:
```suggestion
                    eventPaths:(NSArray<MTREventRequestPath *> * _Nullable)eventPaths
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 21]
```diff
@@ -229,6 +260,38 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+ *
+ * Nil value is treated as empty array for attributePaths and eventPaths.
+ *
+ * Lists of attribute and event paths to read can be provided via attributePaths and eventPaths.
+ *
+ * The completion will be called with an error if  the input parameter has a problem(e.g., both attributePaths and eventPaths are
+ * empty.) or the entire read interaction fails. Otherwise it will be called with values, which may be empty (e.g. if no paths
+ * matched the wildcard) or may include per-path errors if particular paths failed.
+ */
+- (void)readWithAttributePaths:(NSArray<MTRAttributeRequestPath *> * _Nullable)attributePaths
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:274]:
```suggestion
- (void)readAttributePaths:(NSArray<MTRAttributeRequestPath *> * _Nullable)attributePaths
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 22]
```diff
@@ -229,6 +260,38 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+ * Subscribes multiple attributes or events from the device.
+ *
+ * Nil value is treated as empty array for attributePaths and eventPaths.
+ *
+ * Lists of attribute and event paths to subscribe can be provided via attributePaths and eventPaths.
+ *
+ * The reportHandler will be called with an error if the input parameter has a problem(e.g., both attributePaths and eventPaths are
+ * empty.).
+ */
+- (void)subscribeWithAttributePaths:(NSArray<MTRAttributeRequestPath *> * _Nullable)attributePaths
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:289]:
```suggestion
- (void)subscribeToAttributePaths:(NSArray<MTRAttributeRequestPath *> * _Nullable)attributePaths
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 23]
```diff
@@ -229,6 +260,38 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+                         EventPaths:(NSArray<MTREventRequestPath *> * _Nullable)eventPaths
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:290]:
```suggestion
                         eventPaths:(NSArray<MTREventRequestPath *> * _Nullable)eventPaths
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 24]
```diff
@@ -229,6 +260,38 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+                         queue:(dispatch_queue_t)queue
+                    completion:(MTRDeviceResponseHandler)completion MTR_NEWLY_AVAILABLE;
+/**
+ * Subscribes multiple attributes or events from the device.
+ *
+ * Nil value is treated as empty array for attributePaths and eventPaths.
+ *
+ * Lists of attribute and event paths to subscribe can be provided via attributePaths and eventPaths.
+ *
+ * The reportHandler will be called with an error if the input parameter has a problem(e.g., both attributePaths and eventPaths are
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:286]:
```suggestion
 * The reportHandler will be called with an error if the inputs are invalid (e.g., both attributePaths and eventPaths are
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 25]
```diff
@@ -229,6 +260,38 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+ * empty.).
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:287]:
```suggestion
 * empty), or if the subscription fails entirely.
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 26]
```diff
@@ -229,6 +260,38 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+ */
+- (void)subscribeWithAttributePaths:(NSArray<MTRAttributeRequestPath *> * _Nullable)attributePaths
+                         EventPaths:(NSArray<MTREventRequestPath *> * _Nullable)eventPaths
+                             params:(MTRSubscribeParams * _Nullable)params
+                              queue:(dispatch_queue_t)queue
+                      reportHandler:(MTRDeviceResponseHandler)reportHandler
+            subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished MTR_NEWLY_AVAILABLE;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:294]: Should there be a handler here for resubscribe notifications too?

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 27]
```diff
@@ -823,14 +850,15 @@ void OnSubscriptionEstablished(SubscriptionId aSubscriptionId) override
...
     OnErrorCallbackType mOnError;
     OnDoneCallbackType mOnDone;
     OnSubscriptionEstablishedCallbackType mOnSubscriptionEstablished;
     app::BufferedReadCallback mBufferedReadAdapter;
     Platform::UniquePtr<app::ReadClient> mReadClient;
+    std::vector<app::AttributePathParams> mAttributePathParamsList;
+    std::vector<app::EventPathParams> mEventPathParamsList;
 };
 
 - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:864]: Here's what I don't understand.  Why can't this function just create a single `MTRAttributeRequestPath` from its arguments and call the new function we are adding, instead of duplicating all the code?

Same for the existing `readEventsWithEndpointID:...`

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 28]
```diff
@@ -730,19 +744,23 @@ CHIP_ERROR Encode(chip::TLV::TLVWriter & writer, chip::TLV::Tag tag) const
 
 template <typename DecodableValueType> class BufferedReadClientCallback final : public app::ReadClient::Callback {
 public:
-    using OnSuccessCallbackType
-        = std::function<void(const app::ConcreteClusterPath & aPath, const uint32_t aValueId, const DecodableValueType & aData)>;
+    using OnSuccessAttributeCallbackType = std::function<void(
+        const app::ConcreteClusterPath & aPath, const AttributeId aAttributeId, const DecodableValueType & aData)>;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:748]:
```suggestion
        const ConcreteAttributePath & aPath, const DecodableValueType & aData)>;
```
if we're going back to having separate callbacks for events and attributes, we can just use the right type.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 29]
```diff
@@ -730,19 +744,23 @@ CHIP_ERROR Encode(chip::TLV::TLVWriter & writer, chip::TLV::Tag tag) const
...
+    using OnSuccessEventCallbackType
+        = std::function<void(const app::ConcreteClusterPath & aPath, const EventId aEventId, const DecodableValueType & aData)>;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:750]:
```suggestion
        = std::function<void(const ConcreteEventPath & aPath, const DecodableValueType & aData)>;
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 30]
```diff
@@ -768,21 +786,25 @@ void OnAttributeData(
...
+            std::find_if(mAttributePathParamsList.begin(), mAttributePathParamsList.end(),
+                [aPath](app::AttributePathParams & pathParam) -> bool { return pathParam.IsAttributePathSupersetOf(aPath); })
+                != mAttributePathParamsList.end(),
             err = CHIP_ERROR_SCHEMA_MISMATCH);
         VerifyOrExit(apData != nullptr, err = CHIP_ERROR_INVALID_ARGUMENT);
 
         SuccessOrExit(err = app::DataModel::Decode(*apData, value));
 
-        mOnSuccess(aPath, aPath.mAttributeId, value);
+        mOnAttributeSuccess(aPath, aPath.mAttributeId, value);
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:807]:
```suggestion
        mOnAttributeSuccess(aPath, value);
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 31]
```diff
@@ -795,14 +817,19 @@ void OnEventData(const EventHeader & aEventHeader, TLV::TLVReader * apData, cons
...
+                             return pathParam.IsEventPathSupersetOf(aEventHeader.mPath);
+                         })
+                != mEventPathParamsList.end(),
             err = CHIP_ERROR_SCHEMA_MISMATCH);
         VerifyOrExit(apData != nullptr, err = CHIP_ERROR_INVALID_ARGUMENT);
 
         SuccessOrExit(err = app::DataModel::Decode(*apData, value));
 
-        mOnSuccess(aEventHeader.mPath, aEventHeader.mPath.mEventId, value);
+        mOnEventSuccess(aEventHeader.mPath, aEventHeader.mPath.mEventId, value);
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:832]:
```suggestion
        mOnEventSuccess(aEventHeader.mPath, value);
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 32]
```diff
@@ -908,8 +936,162 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+            //
+            // Make sure interactionStatus survives even if this block scope is destroyed.
+            auto interactionStatus = std::make_shared<CHIP_ERROR>(CHIP_NO_ERROR);
+
+            auto resultArray = [[NSMutableArray alloc] init];
+            auto onAttributeSuccessCb = [resultArray](const app::ConcreteClusterPath & clusterPath, const AttributeId aAttributeId,
+                                            const MTRDataValueDictionaryDecodableType & aData) {
+                app::ConcreteAttributePath attribPath(clusterPath.mEndpointId, clusterPath.mClusterId, aAttributeId);
+                [resultArray addObject:@ {
+                    MTRAttributePathKey : [[MTRAttributePath alloc] initWithPath:attribPath],
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:996]:
```suggestion
            auto onAttributeSuccessCb = [resultArray](const ConcreteAttributePath & attributePath,
                                            const MTRDataValueDictionaryDecodableType & aData) {
                [resultArray addObject:@ {
                    MTRAttributePathKey : [[MTRAttributePath alloc] initWithPath:attributePath],
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 33]
```diff
@@ -908,8 +936,162 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                    MTRDataKey : aData.GetDecodedObject()
+                }];
+            };
+
+            auto onEventSuccessCb = [resultArray](const app::ConcreteClusterPath & clusterPath, const EventId aEventId,
+                                        const MTRDataValueDictionaryDecodableType & aData) {
+                app::ConcreteEventPath eventPath(clusterPath.mEndpointId, clusterPath.mClusterId, aEventId);
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1003]:
```suggestion
            auto onEventSuccessCb = [resultArray](const ConcreteEventPath & eventPath,
                                        const MTRDataValueDictionaryDecodableType & aData) {
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 34]
```diff
@@ -908,8 +936,162 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                [resultArray addObject:@ {
+                    MTREventPathKey : [[MTREventPath alloc] initWithPath:eventPath],
+                    MTRDataKey : aData.GetDecodedObject()
+                }];
+            };
+
+            auto onFailureCb = [resultArray, interactionStatus](
+                                   const app::ConcreteClusterPath * clusterPath, const uint32_t aValueId, CHIP_ERROR aError) {
+                if (clusterPath) {
+                    app::ConcreteAttributePath attribPath(clusterPath->mEndpointId, clusterPath->mClusterId, aValueId);
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1013]: How do you know this is the attribute case?  This could be an event.  Seems like we need two different error failure callbacks, like we have two different success callbacks.... Or possibly three: one for path-specific attribute errors, one for path-specific event errors, one for non-path-specific errors.  That way in the non-path-specific case the caller doesn't have to guess whether to call the "event" or "attribute" callback.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 35]
```diff
@@ -908,8 +936,162 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                    // onSuccessCb.
+                    *interactionStatus = aError;
+                }
+            };
+
+            std::vector<app::AttributePathParams> attributePathParamsList;
+            std::vector<app::EventPathParams> eventPathParamsList;
+
+            if (attributePaths != nil) {
+                for (uint8_t i = 0; i < [attributePaths count]; i++) {
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1030]:
```suggestion
                for (MTRAttributeRequestPath * attributePath in attributePaths) {
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 36]
```diff
@@ -908,8 +936,162 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                    chip::EndpointId endpointId = kInvalidEndpointId;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1031]: How about something more like this::

```
AttributePathParams requestPath;
if (attributePath.endpoint != nil) {
  requestPath.endpointId = attributePath.endpoint.unsignedShortValue;
}
if (attributePath.cluster != nil) {
  requestPath.clusterId = static_cast<ClusterId>(attributePath.cluster.unsignedLongValue);
}
if (attributePath.attribute != nil) {
  requestPath.attributeId = static_cast<AttributeId>(attributePath.attribute.unsignedLongValue);
}
attributePathParamsList.push_back(std::move(requestPath));
```
or so.  That way we don't make assumptions about the internal representation of wildcards in AttributePathParams.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 37]
```diff
@@ -908,8 +936,162 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+
+                    if ([attributePaths[i] attribute]) {
+                        attributeId = static_cast<chip::AttributeId>([[attributePaths[i] attribute] unsignedLongValue]);
+                    }
+                    attributePathParamsList.push_back(app::AttributePathParams(endpointId, clusterId, attributeId));
+                }
+            }
+
+            if (eventPaths != nil) {
+                for (uint8_t i = 0; i < [eventPaths count]; i++) {
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1051]: Similar comments here as for attributes.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 38]
```diff
@@ -934,6 +1116,205 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
     std::move(*bridge).DispatchAction(self);
 }
 
+- (void)subscribeWithAttributePaths:(NSArray<MTRAttributeRequestPath *> * _Nullable)attributePaths
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1119]: Again, the existing subscribeToAttributes/Events bits should just call this one.  And this should be placed right next to where the current subscribeToAttributesWithEndpointID implementation is, to make the diff saner to review.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 39]
```diff
@@ -934,6 +1116,205 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+        // We don't support subscriptions over PASE.
+        dispatch_async(queue, ^{
+            reportHandler(nil, [MTRError errorForCHIPErrorCode:CHIP_ERROR_INCORRECT_STATE]);
+        });
+        return;
+    }
+
+    // Copy params before going async.
+    attributePaths = (attributePaths == nil) ? nil : [attributePaths copy];
+    eventPaths = (eventPaths == nil) ? nil : [eventPaths copy];
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1143]: This is not in fact copying them usefully; it's just grabbing references to the same objects in a new array.  This should probably actually create new (mutable) arrays with the right capacity and then fill them with copies.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 40]
```diff
@@ -934,6 +1116,205 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                   }
+
+                   auto onAttributeReportCb
+                       = [queue, reportHandler](const app::ConcreteClusterPath & clusterPath, const AttributeId aAttributeId,
+                             const MTRDataValueDictionaryDecodableType & data) {
+                             id valueObject = data.GetDecodedObject();
+                             app::ConcreteAttributePath pathCopy(clusterPath.mEndpointId, clusterPath.mClusterId, aAttributeId);
+                             dispatch_async(queue, ^{
+                                 reportHandler(@[ @ {
+                                     MTRAttributePathKey : [[MTRAttributePath alloc] initWithPath:pathCopy],
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1166]:
```suggestion
                       = [queue, reportHandler](const ConcreteAttributePath & attributePath,
                             const MTRDataValueDictionaryDecodableType & data) {
                             id valueObject = data.GetDecodedObject();
                             ConcreteAttributePath pathCopy(attributePath);
                             dispatch_async(queue, ^{
                                 reportHandler(@[ @ {
                                     MTRAttributePathKey : [[MTRAttributePath alloc] initWithPath:pathCopy],
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 41]
```diff
@@ -934,6 +1116,205 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                                     MTRDataKey : valueObject
+                                 } ],
+                                     nil);
+                             });
+                         };
+
+                   auto onEventReportCb = [queue, reportHandler](const app::ConcreteClusterPath & clusterPath,
+                                              const EventId aEventId, const MTRDataValueDictionaryDecodableType & data) {
+                       id valueObject = data.GetDecodedObject();
+                       app::ConcreteEventPath pathCopy(clusterPath.mEndpointId, clusterPath.mClusterId, aEventId);
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1176]:
```suggestion
                   auto onEventReportCb = [queue, reportHandler](const ConcreteEventPath & eventPath,
                                               const MTRDataValueDictionaryDecodableType & data) {
                       id valueObject = data.GetDecodedObject();
                       ConcreteEventPath pathCopy(eventPath);
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 42]
```diff
@@ -934,6 +1116,205 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                       dispatch_async(queue, ^{
+                           reportHandler(
+                               @[ @ { MTREventPathKey : [[MTREventPath alloc] initWithPath:pathCopy], MTRDataKey : valueObject } ],
+                               nil);
+                       });
+                   };
+
+                   auto establishedOrFailed = chip::Platform::MakeShared<BOOL>(NO);
+                   auto onFailureCb = [establishedOrFailed, queue, subscriptionEstablished, reportHandler](
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1185]: I know you copied this from the existing subscribeAttributes... code, but if `clusterPath` is not null here, this logic is wrong...  Please add a TODO comment and I will fix that later.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 43]
```diff
@@ -934,6 +1116,205 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                       if (subscriptionEstablished) {
+                           dispatch_async(queue, subscriptionEstablished);
+                       }
+                   };
+
+                   MTRReadClientContainer * container = [[MTRReadClientContainer alloc] init];
+                   container.deviceID = self.nodeID;
+
+                   std::vector<app::AttributePathParams> attributePathParamsList;
+                   std::vector<app::EventPathParams> eventPathParamsList;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1214]:
```suggestion
                   std::vector<AttributePathParams> attributePathParamsList;
                   std::vector<EventPathParams> eventPathParamsList;
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 44]
```diff
@@ -934,6 +1116,205 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+
+                   if (attributePaths != nil) {
+                       for (uint8_t i = 0; i < [attributePaths count]; i++) {
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1217]: See comments in the read version of this code.  Seems like we might want to have some static helper functions for "convert this NSArray<MTRAttributeRequestPath> to std::vector<AttributePathParams>" and similar for the event case...  But see below.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 45]
```diff
@@ -934,6 +1116,205 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                           }
+
+                           if ([attributePaths[i] attribute]) {
+                               attributeId = static_cast<chip::AttributeId>([[attributePaths[i] attribute] unsignedLongValue]);
+                           }
+
+                           attributePathParamsList.push_back(app::AttributePathParams(endpointId, clusterId, attributeId));
+                       }
+                       container.pathParamsSize = attributePathParamsList.size();
+                       container.pathParams = attributePathParamsList.data();
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1237]: This does not make sense.  The container needs to keep the paths alive.  But now it's just pointing into a stack variable.  How is it supposed to keep that alive?

Probably what should happen here is that move to using `new []` and `delete []` to allocate and free these things, with nothrow and null checks and whatnot.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 46]
```diff
@@ -934,6 +1116,205 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                           }
+
+                           if ([eventPaths[i] event]) {
+                               eventId = static_cast<chip::EventId>([[eventPaths[i] event] unsignedLongValue]);
+                           }
+
+                           eventPathParamsList.push_back(app::EventPathParams(endpointId, clusterId, eventId));
+                       }
+                       container.eventPathParamsSize = eventPathParamsList.size();
+                       container.eventPathParams = eventPathParamsList.data();
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1260]: Again, this is going to break.  How was this tested?  There should probably be some unit tests for this as part of this PR....

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 47]
```diff
@@ -934,6 +1116,205 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                   }
+
+                   app::InteractionModelEngine * engine = app::InteractionModelEngine::GetInstance();
+                   CHIP_ERROR err = CHIP_NO_ERROR;
+
+                   chip::app::ReadPrepareParams readParams(session.Value());
+                   [params toReadPrepareParams:readParams];
+                   readParams.mpAttributePathParamsList = container.pathParams;
+                   readParams.mAttributePathParamsListSize = container.pathParamsSize;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1269]: If this is the only use of `pathParamsSize` and `eventPathParamsSize`, why do we need them on the container anyway?  I don't think we need them there...  Again, te comtainer is just there to manage the array lifetime, and for that it does not need to know the size.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 48]
```diff
@@ -934,6 +1116,205 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+
+                   if (err != CHIP_NO_ERROR) {
+                       if (reportHandler) {
+                           dispatch_async(queue, ^{
+                               reportHandler(nil, [MTRError errorForCHIPErrorCode:err]);
+                           });
+                       }
+                       Platform::Delete(readClient);
+                       if (container.pathParams != nullptr) {
+                           Platform::Delete(container.pathParams);
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1301]: This is trying to `free()` a pointer to the stack.  This is really not ok....

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 49]
```diff
@@ -934,6 +1116,205 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                       }
+
+                       if (container.eventPathParams != nullptr) {
+                           Platform::Delete(container.eventPathParams);
+                       }
+                       container.pathParams = nullptr;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1307]: Needs to null out `container.eventPathParams` too.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/darwin/Framework/CHIP/MTRBaseDevice.h (hunk 9 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.h:151]: modified

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 49 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1302]: modified

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 45 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1232]: It's hard to agree with your opinion.
Even if it is passed to the stack, it is changed from SendRequest to TLV Format, so there is no problem even if it is made into a stack.
 
(Of course, free should be deleted below.)

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 46 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1255]: It's hard to agree with your opinion.
Even if it is passed to the stack, it is changed from SendRequest to TLV Format, so there is no problem even if it is made into a stack.
 
(Of course, free should be deleted below.)

Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1255]: I'm sorry. I checked this variable has to make `new` and `delete`.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 45 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1232]: I'm sorry. I checked this variable has to make `new` and `delete`.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 27 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:872]: I fully agree with your opinion.
It was thought to minimize modifications to the existing code. I will edit according to your comments.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 34 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1018]: Oh.... I will be modified.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 48 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: Modified.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 45 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: modified

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 44 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: modified using array memory allocation.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 42 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1174]: I added.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 39 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1133]: I modified.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 38 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: I understand.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 37 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: I modified

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 36 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: I modified in AttributeRequestPath, EventRequestPath.

**Comment by bzbarsky-apple** [comment]
@joonhaengHeo Build is failing.... And this still needs unit tests, right?

**Comment by joonhaengHeo** [comment]
> Build is failing.... And this still needs unit tests, right?

I checked for build errors.
Also, I am considering adding unit tests. 
However, while checking the entire test, a crash occurred in a part unrelated to the modification, so it is being checked.

**Comment by joonhaengHeo** [comment]
@bzbarsky-apple 

During the implementation of the Test Code, I have an inquiry about the code below.
https://github.com/project-chip/connectedhomeip/blob/d85124e4822145f8764328d61970562fb7f4e6f8/src/darwin/Framework/CHIPTests/MTRDeviceTests.m#L1600

The attributes of the Test Case below are set to 0xFFFFFFFF.
If you change the code this time and set it to 0xFFFFFFFF, a fail will occur.
In my opinion, the meaning of this value seems to be Wildcard, so would it be okay to change this part to nil?

File: src/darwin/Framework/CHIP/MTRBaseDevice.h (hunk 26 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.h]: I added.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 47 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: I understand. I removed.

File: src/darwin/Framework/CHIP/MTRBaseDevice.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.h]: I added comment about 9 path. Test Cases is also check 9 paths.

**Comment by joonhaengHeo** [comment]
@bzbarsky-apple 
I think everything has been revised according to your opinion. If there's anything that didn't work out, please let me know again. (There are so many comments that I'm confused.)

**Comment by bzbarsky-apple** [comment]
> The attributes of the Test Case below are set to 0xFFFFFFFF.

Yes, that should be using nil.

> I think everything has been revised according to your opinion.

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 50]
```diff
@@ -229,6 +262,43 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
     API_AVAILABLE(ios(16.4), macos(13.3), watchos(9.4), tvos(16.4));
 
+/**
+ * Reads multiple attribute or event paths from the device.
+ *
+ * Nil is treated as an empty array for attributePaths and eventPaths.
+ *
+ * Lists of attribute and event paths to read can be provided via attributePaths and eventPaths.
+ *
+ * The completion will be called with an error if  the input parameters are invalid (e.g., both attributePaths and eventPaths are
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:272]:
```suggestion
 * The completion will be called with an error if the input parameters are invalid (e.g., both attributePaths and eventPaths are
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 51]
```diff
@@ -229,6 +262,43 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+ * matched the wildcard paths passed in) or may include per-path errors if particular paths failed.
+ *
+ * The length of the path is guaranteed up to 9.
+ */
+- (void)readAttributePaths:(NSArray<MTRAttributeRequestPath *> * _Nullable)attributePaths
+                eventPaths:(NSArray<MTREventRequestPath *> * _Nullable)eventPaths
+                    params:(MTRReadParams * _Nullable)params
+                     queue:(dispatch_queue_t)queue
+                completion:(MTRDeviceResponseHandler)completion MTR_NEWLY_AVAILABLE;
+/**
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:283]:
```suggestion

/**
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.h [hunk 52]
```diff
@@ -229,6 +262,43 @@ typedef NS_ENUM(uint8_t, MTRTransportType) {
...
+ * Subscribes to multiple attribute or event paths.
+ *
+ * Nil is treated as an empty array for attributePaths and eventPaths.
+ *
+ * Lists of attribute and event paths to subscribe to can be provided via attributePaths and eventPaths.
+ *
+ * The reportHandler will be called with an error if the inputs are invalid (e.g., both attributePaths and eventPaths are
+ * empty), or if the subscription fails entirely.
+ *
+ * The length of the Path is guaranteed up to 9.
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.h:293]: No, it's not.  Not for subscriptions.
```suggestion
 * If the sum of the lengths of attributePaths and eventPaths exceeds 3, the subscribe may fail due to the device not supporting that many paths for a subscription.
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 53]
```diff
@@ -147,9 +147,13 @@ static void PurgeReadClientContainers(
                     container.readClientPtr = nullptr;
                 }
                 if (container.pathParams) {
-                    Platform::Delete(container.pathParams);
+                    Platform::MemoryFree(container.pathParams);
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:150]: This assumes that AttributePathParams has a trivial destructor.  We should be static_asserting that, so if the assumption stops being true we can fix this code accordingly.  Something like:
```suggestion
                    static_assert(std::is_trivially_destructible<AttributePathParams>::value, "AttributePathPArams destructors won't get run");
                    Platform::MemoryFree(container.pathParams);
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 54]
```diff
@@ -147,9 +147,13 @@ static void PurgeReadClientContainers(
...
                     container.pathParams = nullptr;
                 }
+                if (container.eventPathParams) {
+                    Platform::MemoryFree(container.eventPathParams);
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:154]: Again, this should be static_asserting that EventPathParams has a trivial destructor.
```suggestion
                    static_assert(std::is_trivially_destructible<EventPathParams>::value, "EventPathParams destructors won't get run");
                    Platform::MemoryFree(container.eventPathParams);
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 55]
```diff
@@ -223,9 +227,13 @@ - (void)onDone
         _readClientPtr = nullptr;
     }
     if (_pathParams) {
-        Platform::Delete(_pathParams);
+        Platform::MemoryFree(_pathParams);
```
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:232]: Added.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 56]
```diff
@@ -236,9 +244,13 @@ - (void)dealloc
...
```
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:250]: Added.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 57]
```diff
@@ -934,6 +1049,195 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
     std::move(*bridge).DispatchAction(self);
 }
 
+- (void)subscribeToAttributePaths:(NSArray<MTRAttributeRequestPath *> * _Nullable)attributePaths
```
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: Moved.

**Review by bzbarsky-apple — COMMENTED** [review]
This is very very close!  Thank you for moving the code (made it _much_ easier to review) and adding the tests!

The only real issue here that still needs to get sorted out is the memory leak on error in the read function.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 58]
```diff
@@ -1207,17 +1382,30 @@ - (void)subscribeToAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                       for (MTRAttributeRequestPath * attribute in attributes) {
+                           [attribute convertToAttributePathParams:container.pathParams[attributePathSize++]];
+                       }
                    }
-                   if (attributeID) {
-                       container.pathParams->mAttributeId = static_cast<chip::AttributeId>([attributeID unsignedLongValue]);
+                   size_t eventPathSize = 0;
+                   if (events != nil) {
+                       container.eventPathParams
+                           = static_cast<EventPathParams *>(Platform::MemoryCalloc([events count], sizeof(EventPathParams)));
```
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1413]: Added.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 59]
```diff
@@ -1207,17 +1382,30 @@ - (void)subscribeToAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
-                   if (endpointID) {
-                       container.pathParams->mEndpointId = static_cast<chip::EndpointId>([endpointID unsignedShortValue]);
-                   }
-                   if (clusterID) {
-                       container.pathParams->mClusterId = static_cast<chip::ClusterId>([clusterID unsignedLongValue]);
+
+                   size_t attributePathSize = 0;
+                   if (attributes != nil) {
+                       container.pathParams = static_cast<AttributePathParams *>(
+                           Platform::MemoryCalloc([attributes count], sizeof(AttributePathParams)));
```
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1397]: Added.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 60]
```diff
@@ -878,38 +979,60 @@ - (void)readAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                }
             }
-            if (attributeID) {
-                attributePath.mAttributeId = static_cast<chip::AttributeId>([attributeID unsignedLongValue]);
+
+            if (events != nil) {
+                size_t count = 0;
+                eventPathParamsList
+                    = static_cast<EventPathParams *>(Platform::MemoryCalloc([events count], sizeof(EventPathParams)));
+                VerifyOrReturnError(eventPathParamsList != nullptr, CHIP_ERROR_NO_MEMORY);
```
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:999]: I tried to consider both unique_ptr and shared_ptr, but the problem of not clearing the memory when subscribing continues to occur.

In my opinion, releasing the container when an error occurs seems to be a more reliable choice.

[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:999]: In the case of the current subscribe function, it is set in the container, so when the container is released, attributePathList and eventPathList are set to be memory free.

[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:999]: Right, subscribe does not have a leak problem.  The only leak problem is here in read.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 61]
```diff
@@ -1207,17 +1382,46 @@ - (void)subscribeToAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
-                   }
-                   if (clusterID) {
-                       container.pathParams->mClusterId = static_cast<chip::ClusterId>([clusterID unsignedLongValue]);
+
+                   size_t attributePathSize = 0;
+                   if (attributes != nil) {
+                       container.pathParams = static_cast<AttributePathParams *>(
+                           Platform::MemoryCalloc([attributes count], sizeof(AttributePathParams)));
+                       if (container.pathParams == nullptr) {
+                           if (reportHandler) {
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1399]: reportHandler can't be nil here, so no need to null-check that.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 62]
```diff
@@ -1207,17 +1382,46 @@ - (void)subscribeToAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
...
+                       }
                    }
-                   if (attributeID) {
-                       container.pathParams->mAttributeId = static_cast<chip::AttributeId>([attributeID unsignedLongValue]);
+                   size_t eventPathSize = 0;
+                   if (events != nil) {
+                       container.eventPathParams
+                           = static_cast<EventPathParams *>(Platform::MemoryCalloc([events count], sizeof(EventPathParams)));
+                       if (container.eventPathParams == nullptr) {
+                           if (reportHandler) {
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1415]: Again, reportHandler cannot be nil.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 61 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: Removed.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 62 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: Removed.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 60 above)
[the remark this answers is not in the document]
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: Added Free attributePathList code in this.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 63]
```diff
@@ -996,7 +996,13 @@ - (void)readAttributePaths:(NSArray<MTRAttributeRequestPath *> * _Nullable)attri
                 size_t count = 0;
                 eventPathParamsList
                     = static_cast<EventPathParams *>(Platform::MemoryCalloc([events count], sizeof(EventPathParams)));
-                VerifyOrReturnError(eventPathParamsList != nullptr, CHIP_ERROR_NO_MEMORY);
+                if (eventPathParamsList == nullptr) {
+                    if (attributePathParamsList != nullptr) {
+                        Platform::MemoryFree(attributePathParamsList);
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1001]: This is not enough.  You have to clean up both lists below if allocating `callback` or `readClient` fails.

That's why I suggested doing something RAII, because that makes it much harder to get things wrong and is a lot more maintainable.

Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: I modified using unique_ptr.
And, I have a question previous implementation.

Is it on purpose that the callback class memory was not erased from the subscription function?

When test005 was executed, it was found that memory delete was not called without onDone of the callback being called. (It is the same implementation even before I modified it.)

While changing to unique_ptr, additional modifications were made so that the callback class object memory was deleted, but if this part was done on purpose, I think it will need to be modified again.

Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: > Is it on purpose that the callback class memory was not erased from the subscription function?

What do you mean?

>  it was found that memory delete was not called without onDone of the callback being called

Well, until onDone is called the callback can be called into, no?  That's why onDone is the thing that deletes the callback...  Deleting it before then is not safe.

@joonhaengHeo I don't understand why we need to store the callback in the `MTRReadClientContainer`.  It should not need to be stored in there, as far as I can tell.  The setup for the callback in the subscribe case is:

1. It's stored in a unique_ptr on the stack.
2. If the subscribe is kicked off successfully, it guarantees that it will call onDone at some point.  So we `release()` the unique_ptr, and then in onDone we delete the callback.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 64]
```diff
@@ -76,12 +76,15 @@
...
 class MTRDataValueDictionaryCallbackBridge;
+template <typename DecodableValueType> class BufferedReadClientCallback;
+class MTRDataValueDictionaryDecodableType;
 
 @interface MTRReadClientContainer : NSObject
 @property (nonatomic, readwrite) app::ReadClient * readClientPtr;
 @property (nonatomic, readwrite) app::AttributePathParams * pathParams;
 @property (nonatomic, readwrite) app::EventPathParams * eventPathParams;
 @property (nonatomic, readwrite) uint64_t deviceID;
+@property (nonatomic, readwrite) BufferedReadClientCallback<MTRDataValueDictionaryDecodableType> * callbackPtr;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:87]: I don't think this should be needed.  See https://github.com/project-chip/connectedhomeip/pull/25840#discussion_r1168981534

Why is it needed?

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 65]
```diff
@@ -748,7 +763,7 @@ CHIP_ERROR Encode(chip::TLV::TLVWriter & writer, chip::TLV::Tag tag) const
     static void OnSuccessFn(void * context, id value) { DispatchSuccess(context, value); }
 };
 
-template <typename DecodableValueType> class BufferedReadClientCallback final : public app::ReadClient::Callback {
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:731]: Why this change?

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 66]
```diff
@@ -765,25 +780,36 @@ CHIP_ERROR Encode(chip::TLV::TLVWriter & writer, chip::TLV::Tag tag) const
...
         , mOnEventSuccess(aOnEventSuccess)
         , mOnError(aOnError)
         , mOnDone(aOnDone)
         , mOnSubscriptionEstablished(aOnSubscriptionEstablished)
         , mOnDeviceResubscriptionScheduled(aOnDeviceResubscriptionScheduled)
         , mBufferedReadAdapter(*this)
     {
+        if (aAttributePathParamsList != nullptr) {
+            mAttributePathParamsList
+                = Platform::MakeMemoryUnique<app::AttributePathParams>(aAttributePathParamsSize, sizeof(AttributePathParams));
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:793]: This is not great, because this allocation can fail...

I think the previous setup, where the callback just held pointers to these things and something else handled the memory management was better than making these copies inside the callback....

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 67]
```diff
@@ -979,32 +1005,25 @@ - (void)readAttributePaths:(NSArray<MTRAttributeRequestPath *> * _Nullable)attri
                 }
             };
 
-            AttributePathParams * attributePathParamsList = nullptr;
-            EventPathParams * eventPathParamsList = nullptr;
+            Platform::MemoryUniquePtr<AttributePathParams> attributePathParamsList = nullptr;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1008]: Now that I am looking at this again... was there a reason we couldn't use the existing `ScopedMemoryBuffer` class here?  It does have a `Release()`, method, so seems like it should be usable here.

So to be precise, here is what I am thinking this should look like:

```
   __block AttributePathParams * attributePathParamsToFree = nullptr;
  ScopedMemoryBuffer<AttributePathParams> attributePathParamsList;
  VerifyOrReturnError(attributePathParamsList.Calloc([attributes count], CHIP_ERROR_NO_MEMORY);
  ...
  // Fill in the values, do the same for the events, kick off the read.  If he read kicks off successfully:
  attributePathParamsToFree = attributePathParamsList.Release();
```

and in `onDone` you free attributePathParamsToFree if it's not null.  No changes needed to the callback compared to what you had before, or to the ReadClientContainer.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 63 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: As long as onDone is guaranteed to be called, there should be no problem.
However, when I tested (test005_subscribe), I found a case where onDone was not called and ended, so I added these modifications.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 64 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:87]: I commented https://github.com/project-chip/connectedhomeip/pull/25840#discussion_r1169329324

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 65 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:731]: In order to add the above "BufferedReadClientCallback" property, the above class definition was additionally required. If final is not removed, a build error occurs.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 67 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1008]: I understand your intention, but it is difficult to implement with your method because the value of "attributePathParamsToFree" is not determined at the time of onDone's lambda definition code.

I'll think about it a bit more and add additional comments.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 66 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:793]: I agree your opinion. I will change this code.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 67 above)
Comment (joonhaengHeo) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: I implemented it using ScopeBuffer.
However, since it is captured using Get() in advance, there is no problem in implementation, but there is a problem that even if it is not null, it cannot guarantee whether it is Free or not.

(I think there is no problem in the code because onDone is not called if an error occurs in the callback or readClient after onDone is declared.)

Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: Oh, right, onDone is a C++ lambda, not an Objective C block...

But yes, what you ended up doing should work, exactly because onDone will not be called unless we succeed at kicking off the read.  Good catch on that.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 63 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: > I found a case where onDone was not called and ended

Was not called in what sense?  Was it not called when the subscription was actually terminated (i.e. when the controller got shut down) @joonhaengHeo ?  Or just not called within the test function, which is expected because the subscription does not terminate there....

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 68]
```diff
@@ -1207,17 +1384,42 @@ - (void)subscribeToAttributesWithEndpointID:(NSNumber * _Nullable)endpointID
                        }
                    };
 
+                   auto onResubscriptionScheduledCb = [resubscriptionScheduled](NSError * error, NSNumber * resubscriptionDelay) {
+                       if (resubscriptionScheduled) {
+                           resubscriptionScheduled(error, resubscriptionDelay);
+                       }
+                   };
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1391]:
```suggestion
                   auto onResubscriptionScheduledCb
                       = [queue, resubscriptionScheduled](NSError * error, NSNumber * resubscriptionDelay) {
                             if (resubscriptionScheduled) {
                                 dispatch_async(queue, ^{
                                     resubscriptionScheduled(error, resubscriptionDelay);
                                 });
                             }
                         };
```

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
Fast-tracking platform-specific change with platform owner review.

**Comment by bzbarsky-apple** [comment]
@joonhaengHeo Thank you for the fix, and your patience!
