### PR TITLE
[Linux] Fix BLE connection removal race between BLE layer and device layer

### LINKED ISSUE #38746: Segmentation fault during BLE unsubscribe after successful commissioning complete.
**Description:** 

When executing the script TC_Pair.py as a part of stress testing, After successful commissioning over BLE-Thread, the 
 python controller encounters a segmentation fault while closing the BLE connection. The `ERROR C2 is NULL in UnsubscribeCharacteristicImpl` is logged just before the crash.

> [MatterTest/ble-thread] 05-01 01:47:14.115 INFO Received Command Response Data, Endpoint=0 Cluster=0x0000_0030 Command=0x0000_0005
[MatterTest/ble-thread] 05-01 01:47:14.115 INFO Received CommissioningComplete response, errorCode=0
[MatterTest/ble-thread] 05-01 01:47:14.116 INFO {
[MatterTest/ble-thread] 05-01 01:47:14.116 INFO 	"label" : "core_commissioning_stage_send_complete",
[MatterTest/ble-thread] 05-01 01:47:14.116 INFO 	"value" : 0
[MatterTest/ble-thread] 05-01 01:47:14.116 INFO }
[MatterTest/ble-thread] 05-01 01:47:14.116 INFO Successfully finished commissioning step 'SendComplete'
[MatterTest/ble-thread] 05-01 01:47:14.117 INFO Commissioning stage next step: 'SendComplete' -> 'Cleanup'
[MatterTest/ble-thread] 05-01 01:47:14.117 INFO {
[MatterTest/ble-thread] 05-01 01:47:14.117 INFO 	"label" : "core_dcm_commission_stage",
[MatterTest/ble-thread] 05-01 01:47:14.117 INFO 	"value" : 39
[MatterTest/ble-thread] 05-01 01:47:14.118 INFO }
[MatterTest/ble-thread] 05-01 01:47:14.118 INFO {
[MatterTest/ble-thread] 05-01 01:47:14.118 INFO 	"label" : "core_commissioning_stage_cleanup",
[MatterTest/ble-thread] 05-01 01:47:14.118 INFO 	"value" : null
[MatterTest/ble-thread] 05-01 01:47:14.118 INFO }
[MatterTest/ble-thread] 05-01 01:47:14.119 INFO Performing next commissioning step 'Cleanup'
[MatterTest/ble-thread] 05-01 01:47:14.119 INFO {
[MatterTest/ble-thread] 05-01 01:47:14.119 INFO 	"label" : "core_commissioning_stage_cleanup",
[MatterTest/ble-thread] 05-01 01:47:14.119 INFO 	"value" : 0
[MatterTest/ble-thread] 05-01 01:47:14.119 INFO }
[MatterTest/ble-thread] 05-01 01:47:14.120 INFO Successfully finished commissioning step 'Cleanup'
[MatterTest/ble-thread] 05-01 01:47:14.120 INFO Closing all BLE connections
[MatterTest/ble-thread] 05-01 01:47:14.120 ERROR C2 is NULL in UnsubscribeCharacteristicImpl
[MatterTest/ble-thread] 05-01 01:47:14.121 INFO Auto-closing end point's BLE connection.
[MatterTest/ble-thread] 05-01 01:47:14.121 INFO Closing BLE GATT connection (con 0x754950029030)
/home/grl/chip_jenkins_workspace/workspace/stress_test_pipeline/60/copied_controller_binaries@tmp/durable-78c9c596/script.sh.copy: line 5: 1708018 Segmentation fault      (core dumped)

GitHub hash of the SDK that were being used are : 09fbc4656cc3880be9b2c69168a9d5776b86a34f

**Test Bed :**
Controller Platform - python controller running on linux machine(amd64) ,
Nordic nRF52840-dk as DUT - all-cluster-app running on Nordic thread device,
Provisioning method - Ble-thread

**Test scenario:**
Pair/Provision the DUT (All-cluster-app running on Nordic) using ble-thread.
Read device information after the device is provisioned
Unpair the DUT (i.e. removing the fabric)
Factory reset the DUT
repeat step1 - 4 for 100 iterations
Script reference: https://github.com/CHIP-Specifications/matter-qa/blob/main/src/matter_qa/scripts/reliability_scripts/TC_Pair.py

**Execution Details:**

In this test-bed 48 iteration were passed and 49 iteration is crashed with this issue:

Passed iteartion log:  [controller_log_iteration_48_2025-05-01_01-46-34.log](https://github.com/user-attachments/files/20034087/controller_log_iteration_48_2025-05-01_01-46-34.log)
Crashed iteration log: [controller_log_iteration_49_2025-05-01_01-47-01.log](https://github.com/user-attachments/files/20034094/controller_log_iteration_49_2025-05-01_01-47-01.log)

### PR DESCRIPTION
**Pull request by arkq**
#### Summary

When device layer receives a signal that BLE has been disconnected it notifies the BLE layer about it and removes the connection object. However, the BLE layer notification is done in async manner, so it might happen that device layer frees the BLE connection object while it is still used by the BLE layer. This can lead to a scenario where BLE layer passes invalid (freed) connection object back to the device layer which results in segmentation fault. To mitigate that we need to make sure that BLE layer cleanup and device layer cleanup are synchronized properly.

#### Changes

- Sync BLE layer and device layer by processing both cleanups on matter event loop
- Remove misleading log message form HandlePlatformSpecificBLEEvent (it receives not only BLE-specific events)

#### Related issues

Fixes https://github.com/project-chip/connectedhomeip/issues/38746

#### Testing

Tested locally to verify that when BLE connection is dropped in the middle of the commissioning process, the `chip::Platform::Delete(conn)` will always happen after the BLE layer clears BLE connection handle `mConnObj = BLE_CONNECTION_UNINITIALIZED`.

### CODE REVIEW

File: src/platform/Linux/bluez/BluezEndpoint.cpp [hunk 1]
```diff
@@ -155,7 +154,6 @@ gboolean BluezEndpoint::BluezCharacteristicAcquireNotify(BluezGattCharacteristic
 #endif // CHIP_ERROR_LOGGING
     BluezConnection * conn       = nullptr;
     bool isAdditionalAdvertising = false;
-    GAutoPtr<GVariant> option_mtu;
```
Comment (cecille) [inline src/platform/Linux/bluez/BluezEndpoint.cpp:158]: was this just unused previously?

**Review by cecille — APPROVED** [review]

File: src/platform/Linux/bluez/BluezEndpoint.cpp (hunk 1 above)
Comment (arkq) [reply src/platform/Linux/bluez/BluezEndpoint.cpp:158]: Yes, this is unused variable. However, it is basically `std::unique_ptr` so there is no warning because destructor is called...

**Review by saurabhst — APPROVED** [review]
