### PR TITLE
[YAML] Issue an error on pairing timeout

### LINKED ISSUE #16017: [TC-MF-1.6] Handle expected error response codes for "PairWithQRCode" in YAML
Need support to handle expected error code when commissioning of DUT is expected to fails in YAML scripts.

Attaching screenshots for reference 
1. Test plan reference
image
image

2. YAML script execution logs
[timeouterror.txt](https://github.com/project-chip/connectedhomeip/files/8215705/timeouterror.txt)
timouterror

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

When a YAML test is trying to pair to a device but can not find any advertisement it just wait until the whole test times out.
This PR update the YAML format to have a common path for "simulated" clusters such as "discovery" and "commissioner" since the "commissioner" simulated cluster is what is used to pair with devices.
Then it also add a timer to `SetUpCodePairer` to cancel everything after a given timeout - where the value of the timeout is the one use for other pairing methods into `CHIPDeviceController`.

Also there are a few more changes to the `zapt` templates than what is needed since this was some code I have to migrate the YAML c++ backend from `Invoke` to `ReadClient/WriteClient/CommandSender`

fix #16017

#### Change overview
 * Update `src/app/tests/suites/commands/discovery` to use a decodable type when it returns a value instead of a custom struct.

 * Update `src/app/tests/suites/commands/commissioner` to use the same `OnResponse` path into YAML generated code.

 * Add a timer to `SetUpCodePairer`

 * Add a test to check if not finding any device triggers an error as expected   

#### Testing
A test has been added to `TestMultiAdmin.yaml`

### CODE REVIEW

File: examples/chip-tool/templates/tests/helper.js [hunk 1]
```diff
@@ -47,8 +47,31 @@ function asPropertyValue(options)
...
+{
+  const options = { 'hash' : { ns : this.cluster } };
+  let type;
+  if ('commandObject' in this) {
+    type = this.commandObject.responseName;
+  } else if ('attributeObject' in this) {
+    type            = this.attributeObject.type;
+    this.isArray    = this.attributeObject.isArray;
+    this.isOptional = this.attributeObject.isOptional;
+    this.isNullable = this.attributeObject.isNullable;
```
Comment (bzbarsky-apple) [inline examples/chip-tool/templates/tests/helper.js:60]: Why are we mutating `this`, esp in an async way?  This is pretty odd...

File: examples/chip-tool/templates/tests/helper.js [hunk 2]
```diff
@@ -47,8 +47,31 @@ function asPropertyValue(options)
   return name;
 }
 
+async function asDecodableType()
+{
+  const options = { 'hash' : { ns : this.cluster } };
+  let type;
```
Comment (bzbarsky-apple) [inline examples/chip-tool/templates/tests/helper.js:53]: We seem to write to `type`, but when do we use it for anything?

File: examples/chip-tool/templates/tests/helper.js [hunk 3]
```diff
@@ -47,8 +47,31 @@ function asPropertyValue(options)
   return name;
 }
 
+async function asDecodableType()
+{
+  const options = { 'hash' : { ns : this.cluster } };
```
Comment (bzbarsky-apple) [inline examples/chip-tool/templates/tests/helper.js:52]: Where is `options` used?

File: examples/chip-tool/templates/tests/partials/test_cluster.zapt [hunk 4]
```diff
@@ -83,25 +83,31 @@ class {{filename}}Suite: public TestCommand
...
-      {{/chip_tests_items}}
+        bool shouldContinue = false;
 
-      VerifyOrReturn(isExpectedDnssdResult, Exit("An unexpected dnssd result has been received"));
-      NextTest();
+        switch (mTestIndex - 1)
+        {
+        {{#chip_tests_items}}
+        {{!
+            This check can be remove once the cluster APIs has been converted from Invoke to
```
Comment (bzbarsky-apple) [inline examples/chip-tool/templates/tests/partials/test_cluster.zapt:94]:
```suggestion
            This check can be removed once the cluster APIs have been converted from Invoke to
```

File: src/app/tests/suites/commands/commissioner/CommissionerCommands.cpp [hunk 5]
```diff
@@ -48,11 +44,40 @@ CHIP_ERROR CommissionerCommands::PairWithManualCode(chip::NodeId nodeId, const c
...
 CHIP_ERROR CommissionerCommands::Unpair(chip::NodeId nodeId)
 {
-    mExpectedStatus = CHIP_NO_ERROR;
-
     return GetCurrentCommissioner().UnpairDevice(nodeId);
 }
 
+chip::app::StatusIB ConvertToStatusIB(CHIP_ERROR err)
+{
+    using namespace chip::Protocols::InteractionModel;
```
Comment (bzbarsky-apple) [inline src/app/tests/suites/commands/commissioner/CommissionerCommands.cpp:52]: Why not throw a `using namespace chip` and `using chip::app::StatusIB` in here and get rid of all the namespace noise in this method?

File: src/controller/CHIPDeviceController.cpp [hunk 6]
```diff
@@ -571,13 +571,16 @@ CHIP_ERROR DeviceCommissioner::PairDevice(NodeId remoteDeviceId, const char * se
...
 }
 
 CHIP_ERROR DeviceCommissioner::PairDevice(NodeId remoteDeviceId, const char * setUpCode)
 {
     MATTER_TRACE_EVENT_SCOPE("PairDevice", "DeviceCommissioner");
-    return mSetUpCodePairer.PairDevice(remoteDeviceId, setUpCode, SetupCodePairerBehaviour::kCommission);
+    ReturnErrorOnFailure(mSetUpCodePairer.PairDevice(remoteDeviceId, setUpCode, SetupCodePairerBehaviour::kCommission));
+
+    return mSystemState->SystemLayer()->StartTimer(chip::System::Clock::Milliseconds32(kSessionEstablishmentTimeout),
+                                                   mSetUpCodePairer.OnSessionEstablishmentTimeoutCallback, &mSetUpCodePairer);
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:583]: 1. Why is this timer started here, and not inside the setup code pairer?
2. Why is this timer happening only in the `kCommission` cases. and not in all the uses of setup code pairer that just establish PASE sessions?
3. What cancels this timer?  If we complete one session establishement, what keeps it from firing in the middle of a second one, if the second one just does a PASE session, not commissioning?
4. Is it really the intent for this timer to interrupt an ongoing PASE connection attempt based on an advertisement we discovered?  Does it actually interrupt that, or leave it to keep establishing but notify that session establishment failed?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: examples/chip-tool/templates/tests/helper.js (hunk 2 above)
Comment (vivien-apple) [reply examples/chip-tool/templates/tests/helper.js:56]: I forgot to push the last line of the method that uses `zapTypeToDecodableClusterObjectType`...

File: examples/chip-tool/templates/tests/helper.js (hunk 3 above)
Comment (vivien-apple) [reply examples/chip-tool/templates/tests/helper.js]: Same answer than the previous comment.

File: src/app/tests/suites/commands/commissioner/CommissionerCommands.cpp (hunk 5 above)
Comment (vivien-apple) [reply src/app/tests/suites/commands/commissioner/CommissionerCommands.cpp:54]: Fixed.

File: examples/chip-tool/templates/tests/helper.js [hunk 7]
```diff
@@ -47,8 +48,36 @@ function asPropertyValue(options)
   return name;
 }
 
+async function asDecodableType()
+{
+  // Copy some properties of the properties needed by zapTypeToDecodableClusterObjectType
```
Comment (bzbarsky-apple) [inline examples/chip-tool/templates/tests/helper.js:53]:
```suggestion
  // Copy some properties needed by zapTypeToDecodableClusterObjectType
```

File: examples/chip-tool/templates/tests/partials/test_cluster.zapt [hunk 8]
```diff
@@ -83,25 +83,31 @@ class {{filename}}Suite: public TestCommand
...
-      {{/chip_tests_items}}
+        bool shouldContinue = false;
 
-      VerifyOrReturn(isExpectedDnssdResult, Exit("An unexpected dnssd result has been received"));
-      NextTest();
+        switch (mTestIndex - 1)
+        {
+        {{#chip_tests_items}}
+        {{!
+            This check can be removes once the cluster APIs have been converted from Invoke to
```
Comment (bzbarsky-apple) [inline examples/chip-tool/templates/tests/partials/test_cluster.zapt:94]:
```suggestion
            This check can be removed once the cluster APIs have been converted from Invoke to
```

File: src/controller/SetUpCodePairer.cpp [hunk 9]
```diff
@@ -45,7 +49,10 @@ CHIP_ERROR SetUpCodePairer::PairDevice(NodeId remoteId, const char * setUpCode,
     mRemoteId     = remoteId;
     mSetUpPINCode = payload.setUpPINCode;
 
-    return Connect(payload);
+    ReturnErrorOnFailure(Connect(payload));
+
+    return mSystemLayer->StartTimer(chip::System::Clock::Milliseconds32(kDeviceDiscoveredTimeout),
```
Comment (bzbarsky-apple) [inline src/controller/SetUpCodePairer.cpp:54]:
```suggestion
    return mSystemLayer->StartTimer(System::Clock::Milliseconds32(kDeviceDiscoveredTimeout),
```

Comment (bzbarsky-apple) [inline src/controller/SetUpCodePairer.cpp:54]: Should include `system/SystemClock.h` in this file.

File: src/controller/SetUpCodePairer.cpp [hunk 10]
```diff
@@ -202,5 +211,14 @@ void SetUpCodePairer::NotifyCommissionableDeviceDiscovered(const Dnssd::Discover
     OnDeviceDiscovered(params);
 }
 
+void SetUpCodePairer::OnDeviceDiscoveredTimeoutCallback(System::Layer * layer, void * context)
+{
+    SetUpCodePairer * pairer = static_cast<SetUpCodePairer *>(context);
```
Comment (bzbarsky-apple) [inline src/controller/SetUpCodePairer.cpp:216]:
```suggestion
    auto * pairer = static_cast<SetUpCodePairer *>(context);
```

**Review by bzbarsky-apple — APPROVED** [review]

File: src/controller/SetUpCodePairer.cpp [hunk 11]
```diff
@@ -29,12 +29,17 @@
 #include <controller/CHIPDeviceController.h>
 #include <lib/dnssd/Resolver.h>
 #include <lib/support/CodeUtils.h>
+#include <system/SystemClock.h>
+
+constexpr uint32_t kDeviceDiscoveredTimeout = 30 * chip::kMillisecondsPerSecond;
```
Comment (tcarmelveilleux) [inline src/controller/SetUpCodePairer.cpp:34]: This policy choice/heuristics now becomes a policy shared by all. What is the justification for this particular non-configurable time-out value?

**Review by woody-apple — APPROVED** [review]

File: src/controller/SetUpCodePairer.cpp (hunk 11 above)
Comment (woody-apple) [reply src/controller/SetUpCodePairer.cpp:34]: @vivien-apple @raju-apple ?

Comment (vivien-apple) [reply src/controller/SetUpCodePairer.cpp]: I have updated the code so there is a `#define` in `ChipConfig.h` instead of an hardcoded value.
