### PR TITLE
Darwin mdns fix

### LINKED ISSUE #11891: DNSServiceGetAddrInfo fails to complete on Big Sur and Monterey
#### Problem
We appear to be calling DNSServiceGetAddrInfo successfully (err = 0), but the OnGetAddrInfo never gets called.

 #### Proposed Solution
Root cause this. No idea how to fix yet.

### PR DESCRIPTION
**Pull request by cecille**
#### Problem
GetAddrInfo hangs if the interface is local only.
Fixes #11891 

#### Change overview
Default to localhost on interface -1.

#### Testing
Tested by Andy - now get address correctly for devices returned on interface -1.

### CODE REVIEW

**Comment by cecille** [comment]
Closed because andy opened one with the updates on already - https://github.com/cecille/connectedhomeip/pull/1

**Comment by cecille** [comment]
Nope, I don't know how to read - Andy's PR is on this branch.

File: src/platform/Darwin/DnssdImpl.cpp [hunk 1]
```diff
@@ -460,13 +460,40 @@ static CHIP_ERROR GetAddrInfo(void * context, DnssdResolveCallback callback, uin
...
+        sockaddr.sin6_len    = sizeof(sockaddr);
+        sockaddr.sin6_family = AF_INET6;
+        sockaddr.sin6_addr   = in6addr_loopback;
+        sockaddr.sin6_port   = htons((unsigned short) port);
+        uint32_t ttl         = 120; // default TTL for records with hostnames is 120 seconds
+        uint32_t interface   = 0;   // Set interface to ANY (0) - network stack can decide how to route this.
+        OnGetAddrInfo(nullptr, 0 /* flags */, interface, kDNSServiceErr_NoError, hostname,
+                      reinterpret_cast<struct sockaddr *>(&sockaddr), ttl, sdCtx);
+
+        // Don't leak memory.
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.cpp:487]: This is still leaking sdCtx itself, right?

It would probably be better to call `MdnsContexts::Delete(sdCtx)` and if that fails because it has a null `context->serviceRef` we should add a check there?

Also, there are other leaks all over this code on failre paths; I'll deal with those....

Comment (cecille) [reply src/platform/Darwin/DnssdImpl.cpp:487]: @harimau-qirex - would you be able to add a delete call in here and ensure it works?

Comment (harimau-qirex) [reply src/platform/Darwin/DnssdImpl.cpp:487]: I've made the change and tested that it works. I'm unsure how to push it directly, so I've created another pull request with the change: cecille#2

**Comment by vivien-apple** [comment]
I'm sort of curious. Does the resolve for interface id `-1` still fails once the memory corruption thing is fixed ?

For some context I'm running `Big Sur` and  applying this patch locally:
```
diff --git a/src/platform/Darwin/DnssdImpl.cpp b/src/platform/Darwin/DnssdImpl.cpp
index 8cb8d609e7..852ac72ae2 100644
--- a/src/platform/Darwin/DnssdImpl.cpp
+++ b/src/platform/Darwin/DnssdImpl.cpp
@@ -524,7 +524,7 @@ CHIP_ERROR ChipDnssdPublishService(const DnssdService * service)
         MdnsContexts::GetInstance().SetHostname(service->mHostName);
     }
     std::string regtype  = GetFullTypeWithSubTypes(service->mType, service->mProtocol, service->mSubTypes, service->mSubTypeSize);
-    uint32_t interfaceId = GetInterfaceId(service->mInterface);
+    uint32_t interfaceId = static_cast<uint32_t>(-1); //GetInterfaceId(service->mInterface);
 
     TXTRecordRef record;
     char buffer[kDnssdTextMaxSize];
```

And then launching the `all-clusters-app`: `./out/debug/standalone/chip-all-clusters-app` then `dns-sd -B _matterc._udp` results into: 
```
Browsing for _matterc._udp
DATE: ---Fri 19 Nov 2021---
17:35:16.524  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
17:35:16.525  Add        2  -1 local.               _matterc._udp.       C478BFCF4596349A
```

Running `./out/debug/standalone/chip-tool pairing onnetwork 0x12345 20202021` results into:
```
[1637339818779] [26712:46895140] CHIP: [IN] UDP::Init bind&listen port=5550
[1637339818779] [26712:46895140] CHIP: [IN] UDP::Init bound to port=5550
[1637339818779] [26712:46895140] CHIP: [IN] UDP::Init bind&listen port=5550
[1637339818779] [26712:46895140] CHIP: [IN] UDP::Init bound to port=5550
[1637339818779] [26712:46895140] CHIP: [IN] TransportMgr initialized
[1637339818779] [26712:46895152] CHIP: [DL] _OnPlatformEvent
[1637339818779] [26712:46895152] CHIP: [DL] Mdns: OnBrowseAdd  name: C478BFCF4596349A, type: _matterc._udp., domain: local., interface: -1
[1637339818780] [26712:46895152] CHIP: [DL] Resolved interface id: 4294967295
[1637339818780] [26712:46895152] CHIP: [DL] Mdns: OnGetAddrInfo hostname:MacBook-Pro.local.
[1637339818780] [26712:46895152] CHIP: [TOO] Discovered Device: ::1:5540
```

**Review by bzbarsky-apple — APPROVED** [review]
Approving if we have verified that this fixes the problem and verified that the problem is still there after the memory fixes.

Thank you!

**Comment by cecille** [comment]
I think the symptoms we are seeing here are slightly different, because the dns-sd command line tool also cannot resolve an address on these computers. I think you may be correct that there is a firewall blocking something to do with bonjour on our network. Not sure how common this will be across companies, but at the very least we know the memory fix alone does not get our devs unblocked.

File: src/platform/Darwin/DnssdImpl.cpp (hunk 1 above)
Comment (cecille) [reply src/platform/Darwin/DnssdImpl.cpp:490]: The PR to this branch is now merged, so I'm going to resolve this comment.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
fast track: platform specific change

**Comment by andy31415** [comment]
fast track: platform specific change

File: src/platform/Darwin/DnssdImpl.cpp [hunk 2]
```diff
@@ -460,13 +463,35 @@ static CHIP_ERROR GetAddrInfo(void * context, DnssdResolveCallback callback, uin
     protocol = kDNSServiceProtocol_IPv6;
 #endif
 
-    err = DNSServiceGetAddrInfo(&sdRef, 0 /* flags */, interfaceId, protocol, hostname, OnGetAddrInfo, sdCtx);
-    VerifyOrReturnError(CheckForSuccess(sdCtx, __func__, err, true), CHIP_ERROR_INTERNAL);
+    if (interfaceId != static_cast<uint32_t>(-1))
```
Comment (msandstedt) [inline src/platform/Darwin/DnssdImpl.cpp:466]: Why not just use the defined kDNSServiceInterfaceIndexLocalOnly?

Comment (msandstedt) [reply src/platform/Darwin/DnssdImpl.cpp:466]: Confirmed this compiles:

```
diff --git a/src/platform/Darwin/DnssdImpl.cpp b/src/platform/Darwin/DnssdImpl.cpp
index ff0f96ffd..f18220cbc 100644
--- a/src/platform/Darwin/DnssdImpl.cpp
+++ b/src/platform/Darwin/DnssdImpl.cpp
@@ -463,7 +463,7 @@ static CHIP_ERROR GetAddrInfo(void * context, DnssdResolveCallback callback, uin
     protocol = kDNSServiceProtocol_IPv6;
 #endif
 
-    if (interfaceId != static_cast<uint32_t>(-1))
+    if (interfaceId != kDNSServiceInterfaceIndexLocalOnly)
     {
         // -1 is the local only interface. If we're not on that interface, we need to get the address for the given hostname.
         err = DNSServiceGetAddrInfo(&sdRef, 0 /* flags */, interfaceId, protocol, hostname, OnGetAddrInfo, sdCtx);

```

Comment (cecille) [reply src/platform/Darwin/DnssdImpl.cpp:466]: If you know what header that's defined in, we can make that change.

Comment (msandstedt) [reply src/platform/Darwin/DnssdImpl.cpp:466]: It's not in our code.  It's in dns_sd.h, which we include from `platform/Darwin/DnssdImpl.h`.

https://opensource.apple.com/source/mDNSResponder/mDNSResponder-544/mDNSShared/dns_sd.h.auto.html

**Review by msandstedt — APPROVED** [review]
