### PR TITLE
Fix timestamps in Diagnostic Logs cluster to follow the spec.

### LINKED ISSUE #24265: Timestamps in Diagnostic Logs cluster do not match spec
Per spec, in RetrieveLogsResponse the UTCTimeStamp should be `epoch-us` (64-bit microseconds) and the TimeSinceBoot should be `systime-us` (64-bit microseconds).

In the SDK right now UTCTimeStamp is an `epoch-s` in the XML, but the actual value the cluster stores in there is a _millisecond_ monotonic timestamp (which is neither seconds, nor an epoch value).

In the SDK right now TimeSinceBoot is an INT32U in the XML.  It's never actually sent on the wire by the current cluster implementation.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
There were a few issues here:

1. We were using a monotonic timestamp, but setting the UTCTimeStamp in the response payload.

2. We were using a millisecond timestamp, whereas the spec has microsecond ones.

Switch to using "time since server init" for the timestamp, put it in the TimeSinceBoot field, and make sure it has the right units.

Also fixes the timestamps to actually be optional, per spec.

Fixes https://github.com/project-chip/connectedhomeip/issues/24265

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

File: src/app/server/Server.h [hunk 1]
```diff
@@ -369,6 +370,8 @@ class Server
 
     void ScheduleFactoryReset();
 
+    System::Clock::Microseconds64 TimeSinceInit() { return System::SystemClock().GetMonotonicMicroseconds64() - mInitTimestamp; }
```
Comment (andy31415) [inline src/app/server/Server.h:373]: supernit: could be const?

**Review by andy31415 — APPROVED** [review]

**Review by jtung-apple — APPROVED** [review]

File: src/app/server/Server.h (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/server/Server.h:373]: Good catch.

Comment (bzbarsky-apple) [reply src/app/server/Server.h]: Done.

**Review by msandstedt — APPROVED** [review]

File: src/app/clusters/diagnostic-logs-server/diagnostic-logs-server.cpp [hunk 2]
```diff
@@ -20,15 +20,20 @@
...
 #include <app/ConcreteCommandPath.h>
 #include <app/clusters/diagnostic-logs-server/diagnostic-logs-server.h>
+#include <app/server/Server.h>
 #include <app/util/af.h>
 #include <lib/support/BytesCircularBuffer.h>
+#include <lib/support/ScopedBuffer.h>
 
 #include <array>
 
+// We store our times as millisecond times, to save space.
```
Comment (jmeg-sfy) [inline src/app/clusters/diagnostic-logs-server/diagnostic-logs-server.cpp:30]: does the specs need to be updated here ; if spec says microsecond that seems overkill ...

**Review by jmeg-sfy — APPROVED** [review]
thanks for this fix

File: src/app/clusters/diagnostic-logs-server/diagnostic-logs-server.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/app/clusters/diagnostic-logs-server/diagnostic-logs-server.cpp:30]: Spec does not have a millisecond time type... It has microseconds and seconds.

Comment (bzbarsky-apple) [reply src/app/clusters/diagnostic-logs-server/diagnostic-logs-server.cpp:30]: And it's probably better to not make random spec changes here at this point.
