### PR TITLE
EVSE add get set clear targets support

### LINKED ISSUE #30997: [1.3] Complete EVSE delegate implementation
### Reproduction steps

This issue is to track the outstanding work in the EVSE Delegate

Implemented in PR: https://github.com/project-chip/connectedhomeip/pull/30999/
- [x] - [x] Add Callback to HW to inform it of MaxCurrentLimit
- [x] Add Callback to HW to inform it of Change in Charging Enabled / Disable state

Implemented in PR: https://github.com/project-chip/connectedhomeip/pull/31200/
- [x] Add PluggedIn / Unplugged Events
- [x] Add EnergyTransferStarted Event
- [x] Add EnergyTransferStopped Event
- [x] Add Session support (Requires EEM cluster integration)
- [x] Add Persisted Storage support for some attributes

- [x] Add Timer expiry checking to automatically stop charging/discharging

Implemented in PR 
https://github.com/project-chip/connectedhomeip/pull/31406

-[x] Update XML for EVSE to support new charging preference structures

To do:
- [ ] Implement Persisting of helper data which allows session duration, session energy charged etc to be computed

- [ ] Add Charging Preferences Support (GetTargets/SetTargets/ClearTargets) (see PR https://github.com/project-chip/connectedhomeip/pull/31407)
- [ ] Add RPC handlers into example energy management app

### Bug prevalence

N/A

### GitHub hash of the SDK that was being used

N/A

### Platform

core

### Platform Version(s)

1.3

### Type

Core SDK Performance Improvement

### Anything else?

This is an issue to track EVSE implementation for 1.3

### LINKED ISSUE #31900: [1.3] Remove EVSE 80A max current limit to align with latest spec
### Reproduction steps

Changes to the EVSE spec in 1.3 have meant the 80A current limit should be removed in the SDK.

### Bug prevalence

N/A

### GitHub hash of the SDK that was being used

83f8665f0177906a66b927b1a24e8ac038861c86

### Platform

core

### Platform Version(s)

N/A

### Type

Spec Compliance Issue

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jamesharrow**
This PR is to add:

- [x] Support for Clear Targets
- [x] Support for Set Targets
- [x] Support for Get Targets
- [x] Persisting the targets
- [x] Added TC_EEVSE_2_3.py (test case for EVSE Preferences)

Also fixes #31900 - remove 80A limit from EVSE SDK code

### CODE REVIEW

**Comment by Rajashreekalmane** [comment]
https://github.com/project-chip/connectedhomeip/issues/31358

**Review by michaelleecowan7 — APPROVED** [review]
Approve, looks good James

**Review by michaelleecowan7 — APPROVED** [review]
Approve, looks good James

File: examples/all-clusters-app/all-clusters-common/src/energy-evse-stub.cpp [hunk 1]
```diff
@@ -23,14 +23,24 @@ using namespace chip::app::Clusters;
 using namespace chip::app::Clusters::EnergyEvse;
 
 static std::unique_ptr<EnergyEvseDelegate> gDelegate;
+static std::unique_ptr<EvseTargetsDelegate> gEvseTargetsDelegate;
 static std::unique_ptr<EnergyEvseManager> gInstance;
 
 void emberAfEnergyEvseClusterInitCallback(chip::EndpointId endpointId)
 {
     VerifyOrDie(endpointId == 1); // this cluster is only enabled for endpoint 1.
```
Comment (cecille) [inline examples/all-clusters-app/all-clusters-common/src/energy-evse-stub.cpp:31]: Why does this only work for ep1? Seems like this will cause problems for people down the line

File: examples/all-clusters-app/nxp/mw320/BUILD.gn [hunk 2]
```diff
@@ -91,6 +91,7 @@ mw320_executable("shell_mw320") {
     "${chip_root}/examples/energy-management-app/energy-management-common/src/ElectricalPowerMeasurementDelegate.cpp",
     "${chip_root}/examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp",
     "${chip_root}/examples/energy-management-app/energy-management-common/src/EnergyEvseManager.cpp",
+    "${chip_root}/examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp",
```
Comment (cecille) [inline examples/all-clusters-app/nxp/mw320/BUILD.gn:94]: For the gn clusters, can this not just be added to the data model gni file that pulls in the server files?

File: examples/energy-management-app/energy-management-common/include/EnergyEvseTargetsStore.h [hunk 3]
```diff
@@ -0,0 +1,135 @@
...
+        kCount = 1,
+        kSize  = 2,
+    };
+
+private:
+    // The array itself has a control byte and an end-of-array marker.
+    static constexpr size_t kArrayOverHead = 2;
+
+    EvseTargetIteratorImpl * mEvseTargetsIterator = nullptr;
+    PersistentStorageDelegate * mpTargetStore     = nullptr;
```
Comment (cecille) [inline examples/energy-management-app/energy-management-common/include/EnergyEvseTargetsStore.h:109]: Suggest looking at the safe persistent storage stuff
 https://github.com/project-chip/connectedhomeip/blob/master/src/app/SafeAttributePersistenceProvider.h

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp [hunk 4]
```diff
@@ -1492,6 +1690,55 @@ CHIP_ERROR GetEpochTS(uint32_t & chipEpoch)
...
+ * @param   unixEpoch (as time_t)
+ *
+ * @return  bitmap value for day of week
+ * Sunday = 0x01, Monday = 0x01 ... Saturday = 0x40 (1<<6)
+ */
+uint8_t GetDayOfWeekUnixEpoch(time_t unixEpoch)
+{
+    // Define a timezone structure and initialize it to the local timezone
+    // This will capture any daylight saving time changes
+    struct tm local_time;
```
Comment (cecille) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp:1709]: This doesn't work across platforms, does it? Does this cluster tie into the time sync cluster? It should be getting local time from there. Many smaller impls won't be carrying their own dst tables.

File: examples/all-clusters-app/all-clusters-common/src/energy-evse-stub.cpp (hunk 1 above)
Comment (jamesharrow) [reply examples/all-clusters-app/all-clusters-common/src/energy-evse-stub.cpp:31]: The cluster does work on any endpoint, but this is in the all-clusters-app so I was following the pattern used in other all-clusters stubs where only EP 1 is used. In Energy-Management-App it is created using code (no ember) and can use any EP.

I can remove it, but the convention from other stubs in all-clusters seem to have this VerifyOrDie

File: examples/all-clusters-app/nxp/mw320/BUILD.gn (hunk 2 above)
Comment (jamesharrow) [reply examples/all-clusters-app/nxp/mw320/BUILD.gn:94]: I didn't put them in there because these sit as 'examples' in the 'delegate' space whereas things in src/app/cluster/server area are already in the data_model.gni file (for the lower level cluster handling of attributes and commands).

File: examples/energy-management-app/energy-management-common/include/EnergyEvseTargetsStore.h (hunk 3 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/include/EnergyEvseTargetsStore.h:109]: I'm already using this for some of the basic attributes, but this data is not stored as an attribute (only accessible as a command Get / Set). Also I don't know if that allows for lists of lists (which is what this needs to have stored).

I wish there was a library that did this, but spoke with others who recommended that it needed to have storage separately implemented so that the storage layer could handle any backwards compatibility changes needed over time. (i.e. independent from the cluster type definitions).

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp (hunk 4 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp:1706]: Agreed - the comment in the function description also says that this would only work on platforms that do this. Again this sits in the examples area (so manufacturers can come up with their own implementations if they wanted to adapt it).

 We deliberately have mandated use of TimeSync (e.g. you could use NTP or a real-time clock or some other way of getting real time) but TimeSync is definitely an option people could use.

**Comment by andy31415** [comment]
@jamesharrow linter says `src/app/clusters/energy-evse-server/energy-evse-server.h:31: #include <vector>` is not allowed. We generally do not use STL items that use heap in embedded parts.

**Comment by jamesharrow** [comment]
> @jamesharrow linter says `src/app/clusters/energy-evse-server/energy-evse-server.h:31: #include <vector>` is not allowed. We generally do not use STL items that use heap in embedded parts.

Understood that - which is why I didn't just turn off the linter. I have based this implementation heavily on the DefaultICDClientStorage.cpp which uses vectors to allow the implementation to save the targets from RAM to Flash, and then dynamically allocate some memory for a short while to allow the GetTargetsResponse to be sent.

Others I have spoken to have said don't use static memory (arrays) - so would welcome some advice how to get this resolved?
Is there another good approach to follow?

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h [hunk 5]
```diff
@@ -139,6 +141,46 @@ class EnergyEvseDelegate : public EnergyEvse::Delegate
...
+
+    EvseTargetsDelegate * GetEvseTargetsDelegate() { return mEvseTargetsDelegate; }
+
+    /**
+     * @brief Delegate should implement a handler to PrepareGetTargets
+     *
+     * This needs to load any stored targets into memory and hold it until the GetTargetsFinished is
+     * called by the cluster server.
+     *
+     * @param  Reference to EvseTargetIterator class that implements the ability
```
Comment (tcarmelveilleux) [inline examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h:158]: It says reference here, but it's a pointer to a pointer in the API. This would benefit from being updated.

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h [hunk 6]
```diff
@@ -139,6 +141,46 @@ class EnergyEvseDelegate : public EnergyEvse::Delegate
...
+     * freed
+     */
+    CHIP_ERROR GetTargetsFinished() override;
+
+    /**
+     * @brief    Called when EVSE cluster receives ClearTargets command
+     */
+    Status ClearTargets() override;
+
+    /* Helper functions for managing targets*/
```
Comment (tcarmelveilleux) [inline examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h:177]: These helpers should probably not be public. Do they need to be?

File: examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp [hunk 7]
```diff
@@ -0,0 +1,415 @@
...
+        EvseTargetsDelegate & dg = *this;
+        mEvseTargetsIterator     = new EvseTargetIteratorImpl(dg);
+    }
+    return mEvseTargetsIterator;
+};
+EvseTargetsDelegate::~EvseTargetsDelegate()
+{
+    if (mEvseTargetsIterator)
+    {
+        delete mEvseTargetsIterator;
```
Comment (jamesharrow) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp:47]: set this to null after

File: src/app/clusters/energy-evse-server/energy-evse-server.h [hunk 8]
```diff
@@ -38,13 +39,31 @@ namespace EnergyEvse {
...
+constexpr uint8_t kEvseTargetsMaxTargetsPerDay  = 10;
+
+struct EvseChargingTarget
+{
+    uint16_t targetTimeMinutesPastMidnight;
+    Optional<chip::Percent> targetSoC;
+    Optional<int64_t> addedEnergy;
+};
+
+class EvseTargetEntry
```
Comment (jamesharrow) [inline src/app/clusters/energy-evse-server/energy-evse-server.h:52]: make struct instead of class

File: src/app/clusters/energy-evse-server/energy-evse-server.h [hunk 9]
```diff
@@ -38,13 +39,31 @@ namespace EnergyEvse {
...
+{
+public:
+    chip::BitMask<TargetDayOfWeekBitmap> dayOfWeekMap;
+    std::vector<EvseChargingTarget> dailyChargingTargets;
```
Comment (jamesharrow) [inline src/app/clusters/energy-evse-server/energy-evse-server.h:56]: change to a span instead, do memory management in the next handler with a span to the size needed.

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp [hunk 10]
```diff
@@ -360,27 +362,84 @@ void Instance::HandleStartDiagnostics(HandlerContext & ctx, const Commands::Star
...
+    while (it->Next(chargingTargetScheduleEntry))
+    {
+        entry.dayOfWeekForSequence = chargingTargetScheduleEntry.dayOfWeekMap;
+
+        uint8_t index = 0;
+        // copy from our vector to a local array of structs which we can reduce to the length required
+        // so we can pass it into our Encode engine
+        for (const EvseChargingTarget & chargingTarget : chargingTargetScheduleEntry.dailyChargingTargets)
+        {
+            array[index].targetTimeMinutesPastMidnight = chargingTarget.targetTimeMinutesPastMidnight;
```
Comment (jamesharrow) [inline src/app/clusters/energy-evse-server/energy-evse-server.cpp:415]: Check that the index can't grow beyond the kEvseTargetsMaxTargetPerDay

File: examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp [hunk 11]
```diff
@@ -0,0 +1,415 @@
...
+    return reader.VerifyEndOfContainer();
+}
+
+CHIP_ERROR EvseTargetsDelegate::SerializeToTlv(TLV::TLVWriter & writer, const std::vector<EvseTargetEntry> & targetEntryVector)
+{
+    TLV::TLVType arrayType;
+    ReturnErrorOnFailure(writer.StartContainer(TLV::AnonymousTag(), TLV::kTLVType_Array, arrayType));
+    for (auto & targetEntry : targetEntryVector)
+    {
+        TLV::TLVType EvseTargetEntryType;
```
Comment (jamesharrow) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp:270]: make lower case type since its a local variable

File: src/lib/support/DefaultStorageKeyAllocator.h [hunk 12]
```diff
@@ -245,6 +245,12 @@ class DefaultStorageKeyAllocator
     // when new fabric is created, this list needs to be updated,
     // when client init DefaultICDClientStorage, this table needs to be loaded.
     static StorageKeyName ICDFabricList() { return StorageKeyName::FromConst("g/icdfl"); }
+
+    // Energy EVSE cluster
+    // Need a key to store the Charging Preference Targets which is a TLV of list of lists
```
Comment (jamesharrow) [inline src/lib/support/DefaultStorageKeyAllocator.h:250]: Needs to be kept somewhere private since its not in sdk area.
Can just use const char.

Comment (jamesharrow) [reply src/lib/support/DefaultStorageKeyAllocator.h:250]: Also need delete all storage when last fabric is deleted as part of factory reset.
Make an API but not until 1.4

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp [hunk 13]
```diff
@@ -360,27 +362,84 @@ void Instance::HandleStartDiagnostics(HandlerContext & ctx, const Commands::Star
...
+            array[index].targetSoC                     = chargingTarget.targetSoC;
+            array[index].addedEnergy                   = chargingTarget.addedEnergy;
+            index++;
+        }
+
+        DataModel::List<Structs::ChargingTargetStruct::Type> mSpan(array);
+        mSpan.reduce_size(index);
```
Comment (bzbarsky-apple) [inline src/app/clusters/energy-evse-server/energy-evse-server.cpp:422]:
```suggestion
        DataModel::List<Structs::ChargingTargetStruct::Type> targetList(array, index);
```

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp [hunk 14]
```diff
@@ -360,27 +362,84 @@ void Instance::HandleStartDiagnostics(HandlerContext & ctx, const Commands::Star
...
+        entry.chargingTargets = mSpan;
+
+        SuccessOrExit(err = DataModel::Encode(*writer, TLV::AnonymousTag(), entry));
+    }
+
+    SuccessOrExit(err = writer->EndContainer(listContainerType));
+    SuccessOrExit(err = commandHandle->FinishCommand());
+exit:
+    // Release iterator and any memory
```
Comment (bzbarsky-apple) [inline src/app/clusters/energy-evse-server/energy-evse-server.cpp:431]: So if something above errors out after PrepareInvokeResponseCommand succeeds but before FinishCommand, doesn't this leave the CommandHandler in a bad state and not properly respond with an error?  This code also does not work with command batching.

The raw APIs are there, but using them correctly is ... not trivial.

I strongly suggest using `TryAddingResponse` to at least not leave things in a broken state, though the "respond with error" part will still be on you.

The other option is to define a class with an `Encode()` method that does the right things to encode what you want encoded and then you can use the `AddResponse()` API on CommandHandler which does all the sanity bits for you.

File: src/app/clusters/energy-evse-server/energy-evse-server.h [hunk 15]
```diff
@@ -38,13 +39,31 @@ namespace EnergyEvse {
 constexpr int64_t kMinimumChargeCurrent         = 0;
 constexpr int64_t kMaximumChargeCurrent         = 80000;
 constexpr uint32_t kMaxRandomizationDelayWindow = 86400;
+constexpr uint8_t kEvseTargetsMaxNumberOfDays   = 7;
+constexpr uint8_t kEvseTargetsMaxTargetsPerDay  = 10;
+
+struct EvseChargingTarget
+{
+    uint16_t targetTimeMinutesPastMidnight;
+    Optional<chip::Percent> targetSoC;
```
Comment (bzbarsky-apple) [inline src/app/clusters/energy-evse-server/energy-evse-server.h:48]: This is inside `namespace chip`, no?  That applies to various places in this header.

File: src/app/clusters/energy-evse-server/energy-evse-server.h [hunk 16]
```diff
@@ -81,6 +100,41 @@ class Delegate
      */
     virtual Protocols::InteractionModel::Status StartDiagnostics() = 0;
 
+    /**
+     * @brief Delegate should implement a handler to SetTargets command.
```
Comment (bzbarsky-apple) [inline src/app/clusters/energy-evse-server/energy-evse-server.h:104]:
```suggestion
     * @brief Delegate should implement a handler for the SetTargets command.
```

File: src/app/clusters/energy-evse-server/energy-evse-server.h [hunk 17]
```diff
@@ -81,6 +100,41 @@ class Delegate
...
+    virtual Protocols::InteractionModel::Status
+    SetTargets(const DataModel::DecodableList<Structs::ChargingTargetScheduleStruct::DecodableType> &) = 0;
+
+    /**
+     * @brief Delegate should implement a handler to PrepareGetTargets
+     *
+     * This needs to load any stored targets into memory and hold it until the GetTargetsFinished is
+     * called by the cluster server.
+     *
+     * @param  Reference to EvseTargetIterator class that implements the ability
```
Comment (bzbarsky-apple) [inline src/app/clusters/energy-evse-server/energy-evse-server.h:117]: Is this an out param?  Should be documented.

File: src/app/clusters/energy-evse-server/energy-evse-server.h [hunk 18]
```diff
@@ -81,6 +100,41 @@ class Delegate
...
+    /**
+     * @brief Delegate should implement a handler to SetTargets command.
+     * It should report Status::Success if successful and may
+     * return other Status codes if it fails
+     */
+    virtual Protocols::InteractionModel::Status
+    SetTargets(const DataModel::DecodableList<Structs::ChargingTargetScheduleStruct::DecodableType> &) = 0;
+
+    /**
+     * @brief Delegate should implement a handler to PrepareGetTargets
```
Comment (bzbarsky-apple) [inline src/app/clusters/energy-evse-server/energy-evse-server.h:112]:
```suggestion
     * @brief Delegate should implement a handler for PrepareGetTargets
```

File: src/app/clusters/energy-evse-server/energy-evse-server.h [hunk 19]
```diff
@@ -81,6 +100,41 @@ class Delegate
...
+     * This needs to load any stored targets into memory and hold it until the GetTargetsFinished is
+     * called by the cluster server.
+     *
+     * @param  Reference to EvseTargetIterator class that implements the ability
+     *         for the cluster server to iterate through the target entries
+     */
+    virtual CHIP_ERROR PrepareGetTargets(EvseTargetIterator ** iterator) = 0;
+
+    /**
+     * @brief Delegate should implement a handler to GetTargetsFinished
```
Comment (bzbarsky-apple) [inline src/app/clusters/energy-evse-server/energy-evse-server.h:123]:
```suggestion
     * @brief Delegate should implement a handler for GetTargetsFinished
```

File: src/app/clusters/energy-evse-server/energy-evse-server.h [hunk 20]
```diff
@@ -81,6 +100,41 @@ class Delegate
...
+     *
+     * This is used by the cluster server to indicate it has finished preparing
+     * the GetTargetsResponse using the iterator and that the memory in the delegate can
+     * freed
+     */
+    virtual CHIP_ERROR GetTargetsFinished() = 0;
+
+    /**
+     * @brief Delegate should implement a handler to ClearTargets command.
```
Comment (bzbarsky-apple) [inline src/app/clusters/energy-evse-server/energy-evse-server.h:132]:
```suggestion
     * @brief Delegate should implement a handler for the ClearTargets command.
```

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp [hunk 21]
```diff
@@ -234,6 +234,201 @@ Status EnergyEvseDelegate::StartDiagnostics()
...
+        auto iterInner   = entry.chargingTargets.begin();
+        uint8_t innerIdx = 0;
+        while (iterInner.Next())
+        {
+            auto & targetStruct          = iterInner.GetValue();
+            uint16_t minutesPastMidnight = targetStruct.targetTimeMinutesPastMidnight;
+            ChipLogProgress(AppServer, "[%d] MinutesPastMidnight : %d", innerIdx,
+                            static_cast<short unsigned int>(minutesPastMidnight));
+
+            if (minutesPastMidnight > 1439)
```
Comment (bzbarsky-apple) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp:299]: Shouldn't all this "required by spec" validation be in the core cluster code, instead of requiring every single app to implement this?

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp [hunk 22]
```diff
@@ -234,6 +234,201 @@ Status EnergyEvseDelegate::StartDiagnostics()
...
+            }
+
+            uint8_t targetSoC;
+            int64_t addedEnergy;
+
+            /* Check that we have at least an AddedEnergy or TargetSoC value */
+            if (!(targetStruct.targetSoC.HasValue()) && !(targetStruct.addedEnergy.HasValue()))
+            {
+                ChipLogError(AppServer, "Must have one of AddedEnergy or TargetSoC");
+                return Status::ConstraintError;
```
Comment (bzbarsky-apple) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp:312]: I think per spec this should be InvalidCommand, no?

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp [hunk 23]
```diff
@@ -234,6 +234,201 @@ Status EnergyEvseDelegate::StartDiagnostics()
...
+            {
+                targetSoC = targetStruct.targetSoC.Value();
+                ChipLogProgress(AppServer, "[%d] TargetSoC           : %d", innerIdx, static_cast<int>(targetSoC));
+
+                if (targetSoC > 100)
+                {
+                    ChipLogError(AppServer, "TargetSoC has invalid value (%d)", static_cast<int>(targetSoC));
+                    return Status::ConstraintError;
+                }
+                /* If SoC feature is not supported check that the value is 100% */
```
Comment (bzbarsky-apple) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp:325]: That's not what the spec says.  The spec says:

1. If SOC is supported, TargetSoC must be present (and then I have no idea what the conformance is for AddedEnergy, given how things are written).
2. If SOC not supported, then exactly one of TargetSoC and AddedEnergy must be present.

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp [hunk 24]
```diff
@@ -234,6 +234,201 @@ Status EnergyEvseDelegate::StartDiagnostics()
...
+                {
+                    ChipLogError(AppServer, "AddedEnergy has invalid value (%ld)", static_cast<signed long int>(addedEnergy));
+                    return Status::ConstraintError;
+                }
+            }
+            innerIdx++;
+        }
+    }
+
+    return Status::Success;
```
Comment (bzbarsky-apple) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp:347]: This is missing checks that the TLV was actually valid, no?  As in, nothing checks for errors on the iterators.

This is the big drawback of passing the raw iterators to application code.  If we moved this validation into the cluster, that would at least be handled consistently there, leaving fewer pitfalls for app authors who may not realize all the checks they need to be doing.

File: examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp [hunk 25]
```diff
@@ -0,0 +1,415 @@
...
+    size_t len = MaxTargetEntryCounterSize();
+    VerifyOrReturnError(CanCastTo<uint16_t>(len), CHIP_ERROR_BUFFER_TOO_SMALL);
+    ReturnErrorCodeIf(!backingBuffer.Calloc(len), CHIP_ERROR_NO_MEMORY);
+    uint16_t length = static_cast<uint16_t>(len);
+
+    CHIP_ERROR err =
+        mpTargetStore->SyncGetKeyValue(DefaultStorageKeyAllocator::EvseTargetEntryCounter().KeyName(), backingBuffer.Get(), length);
+    if (err == CHIP_ERROR_PERSISTED_STORAGE_VALUE_NOT_FOUND)
+    {
+        return CHIP_NO_ERROR;
```
Comment (bzbarsky-apple) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp:101]: But the out params did not get set, did they?  How is this supposed to work?

File: examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp
Comment (bzbarsky-apple) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp:1]: I did not carefully review all the TLV-munging in this file.  I am hoping someone else is doing it, but if not I can try.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/clusters/energy-evse-server/energy-evse-server.h (hunk 15 above)
Comment (PeterC1965) [reply src/app/clusters/energy-evse-server/energy-evse-server.h:48]: Sorry but not sure what is wrong here. Would you like `struct EvseChargingTarget` -> `struct->chip::EvseChargingTarget`?

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp (hunk 13 above)
Comment (PeterC1965) [reply src/app/clusters/energy-evse-server/energy-evse-server.cpp]: Changed as suggested

File: src/app/clusters/energy-evse-server/energy-evse-server.h (hunk 16 above)
Comment (PeterC1965) [reply src/app/clusters/energy-evse-server/energy-evse-server.h]: Done

File: src/app/clusters/energy-evse-server/energy-evse-server.h (hunk 17 above)
Comment (PeterC1965) [reply src/app/clusters/energy-evse-server/energy-evse-server.h]: Done

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp (hunk 22 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp]: Agree/changed

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp (hunk 23 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp]: Agree on 1/changed.

Wrt 2, the intent of the spec is:
- if SOC is supported, the TargetSoC is mandatory, and the AddedEnergy is optional (and the spec should probably be clarified to [SOC],O.a+ to say that)
- if SOC is not supported, one or both of TargetSoc and AddedEnergy must be present.
- And the code has been reworked to reflect this logic.

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp (hunk 24 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp]: I have moved this validation method into the cluster (src/app/clusters/energy-evse-server/energy-evse-server.cpp) and added the TLV checks.

File: examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp (hunk 25 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp:104]: I have set the values of we return here.

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp (hunk 14 above)
Comment (PeterC1965) [reply src/app/clusters/energy-evse-server/energy-evse-server.cpp:539]: I have changed the code so in the error condition the following happens:

`ctx.mCommandHandler.AddStatus(ctx.mRequestPath, StatusIB(err).mStatus);`

Is that ok?

File: src/app/clusters/energy-evse-server/energy-evse-server.h (hunk 15 above)
Comment (bzbarsky-apple) [reply src/app/clusters/energy-evse-server/energy-evse-server.h:48]: I would like `Optional<Percent> targetSoC;`

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp (hunk 14 above)
Comment (PeterC1965) [reply src/app/clusters/energy-evse-server/energy-evse-server.cpp:536]: I have updated from master and had to rework the code as a consequence of https://github.com/project-chip/connectedhomeip/pull/33736 I believe. 

Would it be possible to review the reworked code pls? 

In particular is the 
`    EnergyEvse::Structs::ChargingTargetStruct::Type chargingTargets[kEvseTargetsMaxNumberOfDays][kEvseTargetsMaxTargetsPerDay];
`
acceptable? I have run tests and they passed. I have assumed that 
`    ctx.mCommandHandler.AddResponse(ctx.mRequestPath, response);
`copies the chargingTargets pointed to in the Lists so that when the method returns and `chargingTargets `goes out of scope all is ok?

**Review by bzbarsky-apple — APPROVED** [review]

File: examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp (hunk 7 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp]: Outdated

File: examples/all-clusters-app/all-clusters-common/src/energy-evse-stub.cpp (hunk 1 above)
Comment (jamesharrow) [reply examples/all-clusters-app/all-clusters-common/src/energy-evse-stub.cpp:31]: Marking this as resolved.

File: examples/all-clusters-app/nxp/mw320/BUILD.gn (hunk 2 above)
Comment (jamesharrow) [reply examples/all-clusters-app/nxp/mw320/BUILD.gn:98]: Marking this as resolved now.

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp (hunk 4 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp]: Marking as resolved.

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h [hunk 26]
```diff
@@ -0,0 +1,107 @@
...
+    void AddChargingTarget(EnergyEvse::Structs::ChargingTargetStruct::Type & chargingTarget);
+    void AllocAndCopy();
+    void AllocAndCopy(const DataModel::List<const Structs::ChargingTargetStruct::Type> & chargingTargets);
+    CHIP_ERROR AllocAndCopy(const DataModel::DecodableList<Structs::ChargingTargetStruct::DecodableType> & chargingTargets);
+
+    EnergyEvse::Structs::ChargingTargetStruct::Type * GetChargingTargets() const;
+    uint16_t GetNumChargingTargets() const;
+
+private:
+    EnergyEvse::Structs::ChargingTargetStruct::Type * mpChargingTargets[kEvseTargetsMaxNumberOfDays];
```
Comment (jamesharrow) [inline examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h:98]: It may be clearer to rename mpChargingTargets to mpListOfDays (or something better) so it doesn't look too similar to mChargingTargets below, or make the one below mDailyChargingTargets - it's quite hard to follow.

File: src/python_testing/TC_EEVSE_2_3.py [hunk 27]
```diff
@@ -0,0 +1,402 @@
...
+            "This test case verifies the primary functionality of the Energy EVSE cluster server with the optional ChargingPreferences feature supported."
+
+    def pics_TC_EEVSE_2_3(self):
+        """ This function returns a list of PICS for this test case that must be True for the test to be run"""
+        return ["EEVSE.S", "EEVSE.S.F00"]
+
+    def steps_TC_EEVSE_2_3(self) -> list[TestStep]:
+        steps = [
+            TestStep("1", "Commissioning, already done", is_commissioning=True),
+            TestStep("2", "TH reads TestEventTriggersEnabled attribute from General Diagnostics Cluster. Verify value is 1 (True)"),
```
Comment (jamesharrow) [inline src/python_testing/TC_EEVSE_2_3.py:45]:
```suggestion
            TestStep("2", "TH reads TestEventTriggersEnabled attribute from General Diagnostics Cluster.", "Verify value is 1 (True)"),
```

File: src/python_testing/TC_EEVSE_2_3.py [hunk 28]
```diff
@@ -0,0 +1,402 @@
...
+            TestStep("3", "TH sends TestEventTrigger command to General Diagnostics Cluster on Endpoint 0 with EnableKey field set to PIXIT.EEVSE.TEST_EVENT_TRIGGER_KEY and EventTrigger field set to PIXIT.EEVSE.TEST_EVENT_TRIGGER for Basic Functionality Test Event. Verify Command response is Success"),
```
Comment (jamesharrow) [inline src/python_testing/TC_EEVSE_2_3.py:46]:
```suggestion
            TestStep("3", "TH sends TestEventTrigger command to General Diagnostics Cluster on Endpoint 0 with EnableKey field set to PIXIT.EEVSE.TEST_EVENT_TRIGGER_KEY and EventTrigger field set to PIXIT.EEVSE.TEST_EVENT_TRIGGER for Basic Functionality Test Event.", "Verify Command response is Success"),
```

File: src/python_testing/TC_EEVSE_2_3.py [hunk 29]
```diff
@@ -0,0 +1,402 @@
...
+            TestStep("4", "TH sends TestEventTrigger command to General Diagnostics Cluster on Endpoint 0 with EnableKey field set to PIXIT.EEVSE.TEST_EVENT_TRIGGER_KEY and EventTrigger field set to PIXIT.EEVSE.TEST_EVENT_TRIGGER for EVSE TimeOfUse Mode Test Event. Verify Command response is Success"),
```
Comment (jamesharrow) [inline src/python_testing/TC_EEVSE_2_3.py:47]:
```suggestion
            TestStep("4", "TH sends TestEventTrigger command to General Diagnostics Cluster on Endpoint 0 with EnableKey field set to PIXIT.EEVSE.TEST_EVENT_TRIGGER_KEY and EventTrigger field set to PIXIT.EEVSE.TEST_EVENT_TRIGGER for EVSE TimeOfUse Mode Test Event.", "Verify Command response is Success"),
```

Comment (jamesharrow) [reply src/python_testing/TC_EEVSE_2_3.py:47]: The same change can be made to all of these TestSteps now that there is a 3rd argument which is the test verification step.

It helps make the file easier to read rather than long lines of text. Once the Python formatter has nicely done line wrapping.

File: examples/energy-management-app/energy-management-common/include/EnergyEvseTargetsStore.h (hunk 3 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/include/EnergyEvseTargetsStore.h]: Closing this comment out - this code has been refactored since anyway.

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h (hunk 6 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h:197]: These are called by the src/app/ sdk layer so I think they need to be public.

File: src/python_testing/TC_EEVSE_2_3.py [hunk 30]
```diff
@@ -0,0 +1,445 @@
...
+            TestStep("7", "TH sends GetTargets.",
+                     "Response EEVSE.S.C00.Tx(GetTargetsResponse) sent with no targets defined."),
+            TestStep("8", "TH sends SetTargets with DayOfTheWeekforSequence=0x7F (i.e. having all days set) and a single ChargingTargets={TargetTime=1439, TargetSoC=null, AddedEnergy=25000000}.",
+                     "Verify Command response is Success"),
+            TestStep("8a", "TH reads NextChargeStartTime attribute.",
+                     "Verify value is null."),
+            TestStep("8b", "TH reads NextChargeTargetTime attribute.",
+                     "Verify value is null."),
+            TestStep("8c", "TH reads NextChargeRequiredEnergy attribute.",
+                     "Verify value is AddedEnergy above."),
```
Comment (jamesharrow) [inline src/python_testing/TC_EEVSE_2_3.py:73]: Currently the code below has a TODO which say expect NULL instead of 250000000

File: src/python_testing/TC_EEVSE_2_3.py [hunk 31]
```diff
@@ -0,0 +1,445 @@
...
+        await self.send_set_targets_command(chargingTargetSchedules=targets)
+
+        self.step("8a")
+        await self.check_evse_attribute("NextChargeStartTime", NullValue)
+
+        self.step("8b")
+        await self.check_evse_attribute("NextChargeTargetTime", NullValue)
+
+        self.step("8c")
+        # await self.check_evse_attribute("NextChargeRequiredEnergy", 25000000)
```
Comment (jamesharrow) [inline src/python_testing/TC_EEVSE_2_3.py:244]: This along with the comment above about the test plan https://github.com/CHIP-Specifications/chip-test-plans/pull/4211/files#r1669407282 need to be aligned along with the spec.

File: examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp [hunk 32]
```diff
@@ -676,6 +905,10 @@ bool HandleEnergyEvseTestEventTrigger(uint64_t eventTrigger)
         ChipLogProgress(Support, "[EnergyEVSE-Test-Event] => EV Charge NoDemand");
         SetTestEventTrigger_EVChargeDemandClear();
         break;
+    case EnergyEvseTrigger::kEVTimeOfUseMode:
+        ChipLogProgress(Support, "[EnergyEVSE-Test-Event] => EV TimeOfUse Mode");
```
Comment (jamesharrow) [inline examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp:909]: I think we need to also was to clear this TE trigger.

File: src/app/clusters/energy-evse-server/EnergyEvseTestEventTriggerHandler.h [hunk 33]
```diff
@@ -57,6 +57,8 @@ enum class EnergyEvseTrigger : uint64_t
     kEVChargeDemand = 0x0099000000000004,
     // EV Charge Demand Test Event Clear | Simulate the EV becoming fully charged
     kEVChargeDemandClear = 0x0099000000000005,
+    // EV Charge TimeOfUse Mode | Simulate putting the EVSE into a Mode with the TimeOfUse tag included
+    kEVTimeOfUseMode = 0x0099000000000006,
```
Comment (jamesharrow) [inline src/app/clusters/energy-evse-server/EnergyEvseTestEventTriggerHandler.h:61]: As above perhaps we need a TimeOfUseMode clear trigger which is sent at the end of the test.

File: src/python_testing/TC_EEVSE_2_3.py [hunk 34]
```diff
@@ -0,0 +1,445 @@
...
+                targetTimeMinutesPastMidnight=1140, addedEnergy=25000000),
+            Clusters.EnergyEvse.Structs.ChargingTargetStruct(
+                targetTimeMinutesPastMidnight=1260, addedEnergy=25000000),
+        ]
+
+        targets_step_19 = [Clusters.EnergyEvse.Structs.ChargingTargetScheduleStruct(
+            dayOfWeekForSequence=0x40, chargingTargets=daily_targets_step_19)]
+        await self.send_set_targets_command(chargingTargetSchedules=targets_step_19, expected_status=Status.ResourceExhausted)
+
+        self.step("20")
```
Comment (jamesharrow) [inline src/python_testing/TC_EEVSE_2_3.py:432]: We should add a TestEvent clear for the ToU mode as well.

File: src/python_testing/TC_EEVSE_Utils.py [hunk 35]
```diff
@@ -97,6 +157,9 @@ async def send_test_event_trigger_charge_demand(self):
     async def send_test_event_trigger_charge_demand_clear(self):
         await self.send_test_event_triggers(eventTrigger=0x0099000000000005)
 
+    async def send_test_event_trigger_time_of_use_mode(self):
```
Comment (jamesharrow) [inline src/python_testing/TC_EEVSE_Utils.py:160]: We should add a time_of_use_mode_clear as well

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h (hunk 26 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h:98]: Did both. Renamed mpChargingTargets to mpListOfDays and renamed mChargingTargets to mDailyChargingTargets and renamed a couple of methods accordingly.

File: src/python_testing/TC_EEVSE_2_3.py (hunk 29 above)
Comment (jamesharrow) [reply src/python_testing/TC_EEVSE_2_3.py]: Applied the change now - this can be resolved.

File: src/python_testing/TC_EEVSE_Utils.py (hunk 35 above)
Comment (PeterC1965) [reply src/python_testing/TC_EEVSE_Utils.py:160]: Added but will be fully implemented when issue #34249 is addressed.

File: src/app/clusters/energy-evse-server/EnergyEvseTestEventTriggerHandler.h (hunk 33 above)
Comment (PeterC1965) [reply src/app/clusters/energy-evse-server/EnergyEvseTestEventTriggerHandler.h:61]: Added but will be fully implemented when issue #34249 is addressed.

File: examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp [hunk 36]
```diff
@@ -577,6 +802,10 @@ void SetTestEventTrigger_EVChargeDemandClear()
 
     dg->HwSetState(sEVSETestEventSaveData.mOldHwStatePluggedInDemand);
 }
+void SetTestEventTrigger_EVTimeOfUseMode()
+{
+    // TODO - what to do here?
```
[the remark this answers is not in the document]
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp:807]: Will be fully implemented when issue #34249 is addressed.

File: src/python_testing/TC_EEVSE_2_3.py (hunk 34 above)
Comment (PeterC1965) [reply src/python_testing/TC_EEVSE_2_3.py:432]: Will be implemented when issue https://github.com/project-chip/connectedhomeip/issues/34249 is addressed.

File: examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp:1]: I have added some unit tests to test the TLV specific behaviour - see src/energy/tests. I had to create the src/energy directory so not clear if I created these tests in the correct place?

File: src/python_testing/TC_EEVSE_2_3.py (hunk 30 above)
Comment (PeterC1965) [reply src/python_testing/TC_EEVSE_2_3.py:73]: Updated the test - we expected AddedEnergy to be NULL as EVSE is not enabled

File: src/python_testing/TC_EEVSE_2_3.py (hunk 31 above)
Comment (PeterC1965) [reply src/python_testing/TC_EEVSE_2_3.py]: Done - see above

File: src/lib/support/DefaultStorageKeyAllocator.h (hunk 12 above)
Comment (PeterC1965) [reply src/lib/support/DefaultStorageKeyAllocator.h]: I have fixed the comment above by moving the the EVSE targets key to be a private member of EnergyEvseTargetsStore

File: src/app/clusters/energy-evse-server/energy-evse-server.h (hunk 8 above)
Comment (jamesharrow) [reply src/app/clusters/energy-evse-server/energy-evse-server.h]: Done

File: src/app/clusters/energy-evse-server/energy-evse-server.h (hunk 9 above)
Comment (jamesharrow) [reply src/app/clusters/energy-evse-server/energy-evse-server.h]: No longer done with vectors. Closing this.

File: src/app/clusters/energy-evse-server/energy-evse-server.h (hunk 20 above)
Comment (jamesharrow) [reply src/app/clusters/energy-evse-server/energy-evse-server.h]: Done

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp (hunk 21 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp]: It is in the server class now.

File: examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp:1]: The unit test has been moved to be in the examples area not the sdk area.

File: src/app/clusters/energy-evse-server/energy-evse-server.h (hunk 19 above)
Comment (jamesharrow) [reply src/app/clusters/energy-evse-server/energy-evse-server.h]: Done

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h (hunk 5 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h]: This code has been reworked and this part of the API is obsolete.

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp (hunk 10 above)
Comment (PeterC1965) [reply src/app/clusters/energy-evse-server/energy-evse-server.cpp]: This area has been reworked so this comment is not long applicable.

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h [hunk 37]
```diff
@@ -0,0 +1,107 @@
...
+ *    ChargingTargetsMemMgr::AllocAndCopy(const DataModel::DecodableList<Structs::ChargingTargetStruct::DecodableType> &
+ * chargingTargets)
+ *
+ * Having allocated and copied the chargingTargets accordingly, they can be added to a
+ * DataModel::List<const Structs::ChargingTargetStruct::Type as follows:
+ *
+ * chargingTargetsList = DataModel::List<Structs::ChargingTargetStruct::Type>(ChargingTargetsMemMgr::GetChargingTargets(),
+ * ChargingTargetsMemMgr::GetNumDailyChargingTargets());
+ *
+ * All memory allocated by this object is released When the ChargingTargetsMemMgr destructor is called.
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h:66]: this comment seems like it should be tied to ChargingTargetsMemMgr class instead of to the top of the file.

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h [hunk 38]
```diff
@@ -0,0 +1,107 @@
...
+namespace EnergyEvse {
+
+class ChargingTargetsMemMgr
+{
+public:
+    ChargingTargetsMemMgr();
+    ~ChargingTargetsMemMgr();
+
+    void Reset(uint16_t chargingTargetSchedulesIdx);
+    void AddChargingTarget(EnergyEvse::Structs::ChargingTargetStruct::Type & chargingTarget);
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h:89]: should the argument be const? Or if not const please explain what will be changed in it at return time.

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h [hunk 39]
```diff
@@ -33,6 +34,31 @@ using chip::Protocols::InteractionModel::Status;
  */
 CHIP_ERROR GetEpochTS(uint32_t & chipEpoch);
 
+/**
+ * @brief   Helper function to get current timestamp and work out the day of week based on localtime
+ *
+ * @param   reference to hold the day of week as a bitmap
+ *
+ * Sunday = 0x01, Monday = 0x01 ... Saturday = 0x40 (1<<6)
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h:42]: are there constants for these? Why are we not using a BitMask type with a strongly typed enum in it? That one has RawValue if we need the actual raw bits.

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h [hunk 40]
```diff
@@ -33,6 +34,31 @@ using chip::Protocols::InteractionModel::Status;
...
+ * @brief   Helper function to get current timestamp and work out the day of week
+ *
+ * NOTE that the time_t is converted using localtime to provide the timestamp
+ * in local time. If this is not supported on some platforms an alternative
+ * implementation may be required.
+ *
+ * @param   unixEpoch (as time_t)
+ *
+ * @return  bitmap value for day of week
+ * Sunday = 0x01, Monday = 0x01 ... Saturday = 0x40 (1<<6)
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h:56]: why not a enum with constants?

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h [hunk 41]
```diff
@@ -33,6 +34,31 @@ using chip::Protocols::InteractionModel::Status;
...
+ */
+uint8_t GetDayOfWeekUnixEpoch(time_t unixEpoch);
+
+CHIP_ERROR GetMinutesPastMidnight(uint16_t & minutesPastMidnight);
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h:60]: please add documentation for this: minutes past midnight since when? Is this using the current time?

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h [hunk 42]
```diff
@@ -236,9 +309,9 @@ class EnergyEvseDelegate : public EnergyEvse::Delegate
 
 private:
     /* Constants */
-    static constexpr int kDefaultMinChargeCurrent                     = 6000;                  /* 6A */
-    static constexpr int kDefaultUserMaximumChargeCurrent             = kMaximumChargeCurrent; /* 80A */
-    static constexpr int kDefaultRandomizationDelayWindow             = 600;                   /* 600s */
+    static constexpr int kDefaultMinChargeCurrent                     = 6000;  /* 6A */
+    static constexpr int kDefaultUserMaximumChargeCurrent             = 80000; /* 80A */
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h:313]: constants should have unit of measurement in name. these seem to be `_mA` or `_milliAmp` or something like that.

`kDefaultRandmizationDelayWindow` should have a `Sec` or `Seconds` suffix.

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp [hunk 43]
```diff
@@ -0,0 +1,154 @@
...
+    return mNumDailyChargingTargets;
+}
+
+void ChargingTargetsMemMgr::AllocAndCopy()
+{
+    if (mNumDailyChargingTargets > 0)
+    {
+        // Allocate the memory first and then use placement new to initialise the memory of each element in the array
+        mpListOfDays[mChargingTargetSchedulesIdx] = static_cast<EnergyEvse::Structs::ChargingTargetStruct::Type *>(
+            chip::Platform::MemoryAlloc(sizeof(EnergyEvse::Structs::ChargingTargetStruct::Type) * mNumDailyChargingTargets));
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp:84]: should you check if allocation succeeded/you had sufficient RAM? Or is segfault acceptable?

If we check, maybe AllocAndCopy should return a CHIP_ERROR.

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h [hunk 44]
```diff
@@ -0,0 +1,107 @@
...
+    void AllocAndCopy();
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h:90]: need documentation for these: alloc and copy what? Please document public APIs

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp [hunk 45]
```diff
@@ -0,0 +1,154 @@
...
+{
+    return mNumDailyChargingTargets;
+}
+
+void ChargingTargetsMemMgr::AllocAndCopy()
+{
+    if (mNumDailyChargingTargets > 0)
+    {
+        // Allocate the memory first and then use placement new to initialise the memory of each element in the array
+        mpListOfDays[mChargingTargetSchedulesIdx] = static_cast<EnergyEvse::Structs::ChargingTargetStruct::Type *>(
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp:83]: both here and below: if AllocAndCopy is called several times in a row, mpListOfDays does not seemed cleared. Should we clear it if not null or add an assertion that it is null?

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp [hunk 46]
```diff
@@ -0,0 +1,154 @@
...
+    size_t numDailyChargingTargets = 0;
+    CHIP_ERROR err                 = chargingTargets.ComputeSize(&numDailyChargingTargets);
+    if (err == CHIP_NO_ERROR)
+    {
+        mNumDailyChargingTargets = static_cast<uint16_t>(numDailyChargingTargets);
+
+        if (mNumDailyChargingTargets > 0)
+        {
+            // Allocate the memory first and then use placement new to initialise the memory of each element in the array
+            mpListOfDays[mChargingTargetSchedulesIdx] = static_cast<EnergyEvse::Structs::ChargingTargetStruct::Type *>(
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp:133]: failure to allocate should probably return a CHIP_ERROR_NO_MEMORY

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp [hunk 47]
```diff
@@ -0,0 +1,154 @@
...
+                chip::Platform::MemoryAlloc(sizeof(EnergyEvse::Structs::ChargingTargetStruct::Type) * mNumDailyChargingTargets));
+
+            uint16_t idx = 0;
+            auto it      = chargingTargets.begin();
+            while (it.Next())
+            {
+                auto & chargingTarget = it.GetValue();
+
+                // This will cause the ChargingTargetStruct constructor to be called and this element in the array
+                new (mpListOfDays[mChargingTargetSchedulesIdx] + idx) EnergyEvse::Structs::ChargingTargetStruct::Type();
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp:143]: how do we guarantee that idx does not iterate longer than `mNumDailyChazrgingTargets` and overflows?

File: examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp [hunk 48]
```diff
@@ -104,6 +103,223 @@ CHIP_ERROR EVSEManufacturer::Shutdown()
...
+    VerifyOrReturnError(mn != nullptr, CHIP_ERROR_UNINITIALIZED);
+
+    EnergyEvseDelegate * dg = mn->GetEvseDelegate();
+    VerifyOrReturnError(dg != nullptr, CHIP_ERROR_UNINITIALIZED);
+
+    const DataModel::List<const EnergyEvse::Structs::ChargingTargetScheduleStruct::Type> & chargingTargetSchedules =
+        dg->GetEvseTargetsDelegate()->GetTargets();
+    for (auto & chargingTargetScheduleEntry : chargingTargetSchedules)
+    {
+        if (chargingTargetScheduleEntry.dayOfWeekForSequence.GetField(static_cast<TargetDayOfWeekBitmap>(0x7F)) & dayOfWeekMap)
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp:128]: 0x7F should probably be a named constant.

File: examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp [hunk 49]
```diff
@@ -104,6 +103,223 @@ CHIP_ERROR EVSEManufacturer::Shutdown()
...
+            err = FindNextTarget(dayOfWeekMap, minutesPastMidnightNow_m, targetTimeMinutesPastMidnight_m, targetSoC,
+                                 addedEnergy_mWh, (searchDay != 0));
+            if (err == CHIP_ERROR_NOT_FOUND)
+            {
+                // We didn't find one for today, try tomorrow
+                searchDay++;
+                dayOfWeekMap = (dayOfWeekMap << 1) & 0x7f;
+                if (dayOfWeekMap == 0x00)
+                {
+                    dayOfWeekMap = 0x01; // Must be Saturday and shifted off, so set it to Sunday
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp:240]: need day bitmak constants instead of numeric values.

File: src/app/clusters/energy-evse-server/energy-evse-server.h [hunk 50]
```diff
@@ -81,6 +82,36 @@ class Delegate
...
+     */
+    virtual Protocols::InteractionModel::Status
+    SetTargets(const DataModel::DecodableList<Structs::ChargingTargetScheduleStruct::DecodableType> & chargingTargetSchedules) = 0;
+
+    /**
+     * @brief Delegate should implement a handler for LoadTargets
+     *
+     * This needs to load any stored targets into memory
+     */
+    virtual Protocols::InteractionModel::Status LoadTargets() = 0;
```
Comment (andy31415) [inline src/app/clusters/energy-evse-server/energy-evse-server.h:98]: why are these returning Status instead of CHIP_ERROR?

Comment (bzbarsky-apple) [reply src/app/clusters/energy-evse-server/energy-evse-server.h:98]: One reason to return Status is to emphasize that you have to return a spec-defined status.

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp (hunk 45 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp:83]: ChargingTargetsMemMgr::Reset() must be called when we move from day to day . There is a comment in the header:
`
 * When iterating through the chargingTargetSchedules, an index in this list is kept and the
 * ChargingTargetsMemMgr::Reset must be called so this object knows which day schedule it is tracking.
 * This will free any previous memory allocated for the day schedule in this object.
`
FYI, the only user of ChargingTargetsMemMgr is EvseTargetsDelegate (EnergyEvseTargetsStore.cpp).

Would you like some further documentation locally (maybe even just pointing the reader to the header file?

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h (hunk 37 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h:78]: I have moved the comment as suggested.

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h (hunk 38 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h]: It is now a const....

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h (hunk 41 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h:67]: Documentation added.

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h (hunk 42 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h]: Change made.

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp (hunk 43 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp:87]: A check is now made and CHIP_ERROR returned.

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h (hunk 44 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h]: Documentation added.

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp (hunk 45 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp:86]: I have added a comment stating Reset() must be called and pointing the reader at ChargingTargetsMemMgr.h where more details are provided.

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp [hunk 51]
```diff
@@ -0,0 +1,154 @@
...
+        }
+    }
+}
+
+CHIP_ERROR
+ChargingTargetsMemMgr::AllocAndCopy(const DataModel::DecodableList<Structs::ChargingTargetStruct::DecodableType> & chargingTargets)
+{
+    size_t numDailyChargingTargets = 0;
+    CHIP_ERROR err                 = chargingTargets.ComputeSize(&numDailyChargingTargets);
+    if (err == CHIP_NO_ERROR)
```
[the remark this answers is not in the document]
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp]: Done.

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp (hunk 46 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp]: A check is now made and CHIP_ERROR returned.

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp (hunk 47 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp]: A check is made/error returned if we would exceed the `mNumDailyChargingTargets`.

File: examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp [hunk 52]
```diff
@@ -104,6 +103,223 @@ CHIP_ERROR EVSEManufacturer::Shutdown()
...
+CHIP_ERROR FindNextTarget(const uint8_t dayOfWeekMap, uint16_t minutesPastMidnightNow_m, uint16_t & targetTimeMinutesPastMidnight_m,
+                          DataModel::Nullable<Percent> & targetSoC, DataModel::Nullable<int64_t> & addedEnergy_mWh,
+                          bool bAllowTargetsInPast)
+{
+
+    CHIP_ERROR err = CHIP_NO_ERROR;
+
+    EnergyEvse::Structs::ChargingTargetScheduleStruct::Type entry;
+
+    uint16_t minTimeToTarget_m = 1440; // 24 hours
```
[the remark this answers is not in the document]
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp]: Change made.

File: examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp (hunk 48 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp]: A constant is now used.

File: examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp (hunk 49 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp]: Referenced the chip::app::Clusters::EnergyEvse::TargetDayOfWeekBitmap

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h (hunk 40 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h]: I have changed the comment. This bitmap is effectively that defined by chip::app::Clusters::EnergyEvse::TargetDayOfWeekBitmap. We map from a Unix day (Sunday = 0, Monday =1 ... ) to the equivalent bitmask.
I guess ideally we could have returned a chip::BitMask instead of a uint8_t. However would be acceptable to leave as a uint8_t as it ripples through a couple of layers of functions please?

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h (hunk 39 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h]: I have changed the comment. This bitmap is effectively that defined by chip::app::Clusters::EnergyEvse::TargetDayOfWeekBitmap. We map from a Unix day (Sunday = 0, Monday =1 ... ) to the equivalent bitmask.
I guess ideally we could have returned a chip::BitMask instead of a uint8_t. However would be acceptable to leave as a uint8_t as it ripples through a couple of layers of functions please?

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h [hunk 53]
```diff
@@ -33,6 +34,34 @@ using chip::Protocols::InteractionModel::Status;
  */
 CHIP_ERROR GetEpochTS(uint32_t & chipEpoch);
 
+/**
+ * @brief   Helper function to get current timestamp and work out the day of week based on localtime
+ *
+ * @param   reference to hold the day of week as a bitmap as defined by EnergyEvse::TargetDayOfWeekBitmap
+ */
+CHIP_ERROR GetDayOfWeekNow(uint8_t & dayOfWeekMap);
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h:42]: according to the docs, this should return a `EnergeEvse::TargetOfDayWeekBitmap` instead of a uint8_t

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp (hunk 45 above)
Comment (andy31415) [reply examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp:86]: Please add a VerifyOrDie then if you do not want to clear. People tend to not notice comments and this will be mis-used eventually.

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp [hunk 54]
```diff
@@ -0,0 +1,191 @@
...
+{
+    // NOTE: ChargingTargetsMemMgr::Reset() must be called as specified in the class comments in
+    // ChargingTargetsMemMgr.h before this method can be called.
+
+    size_t numDailyChargingTargets = 0;
+    CHIP_ERROR err                 = chargingTargets.ComputeSize(&numDailyChargingTargets);
+    if (err != CHIP_NO_ERROR)
+    {
+        return err;
+    }
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp:153]:
```suggestion
    ReturnErrorOnFailure(chargingTargets.ComputeSize(&numDailyChargingTargets));
```

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp [hunk 55]
```diff
@@ -0,0 +1,191 @@
...
+    if (mNumDailyChargingTargets > 0)
+    {
+        // Allocate the memory first and then use placement new to initialise the memory of each element in the array
+        mpListOfDays[mChargingTargetSchedulesIdx] = static_cast<EnergyEvse::Structs::ChargingTargetStruct::Type *>(
+            chip::Platform::MemoryAlloc(sizeof(EnergyEvse::Structs::ChargingTargetStruct::Type) * mNumDailyChargingTargets));
+
+        if (mpListOfDays[mChargingTargetSchedulesIdx] == nullptr)
+        {
+            return CHIP_ERROR_NO_MEMORY;
+        }
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp:92]:
```suggestion
        VerifyOrReturnError(mpListOfDays[mChargingTargetSchedulesIdx] != nullptr, CHIP_ERROR_NO_MEMORY);
```

is slightly more idiomatic in chip codebase

File: examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp [hunk 56]
```diff
@@ -104,6 +107,224 @@ CHIP_ERROR EVSEManufacturer::Shutdown()
...
+                    targetTimeMinutesPastMidnight_m = chargingTarget.targetTimeMinutesPastMidnight;
+
+                    if (chargingTarget.targetSoC.HasValue())
+                    {
+                        targetSoC.SetNonNull(chargingTarget.targetSoC.Value());
+                    }
+                    else
+                    {
+                        targetSoC.SetNull();
+                    }
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp:158]:
```suggestion
                    targetSoC = chargingTarget.targetSoC;
```

Is this the same? It looks like if it has a value, you set it to thyat value, otherwise you set it to null.
Same for below.

File: examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp [hunk 57]
```diff
@@ -104,6 +107,224 @@ CHIP_ERROR EVSEManufacturer::Shutdown()
     return CHIP_NO_ERROR;
 }
 
+CHIP_ERROR FindNextTarget(const uint8_t dayOfWeekMap, uint16_t minutesPastMidnightNow_m, uint16_t & targetTimeMinutesPastMidnight_m,
+                          DataModel::Nullable<Percent> & targetSoC, DataModel::Nullable<int64_t> & addedEnergy_mWh,
+                          bool bAllowTargetsInPast)
+{
+
+    CHIP_ERROR err = CHIP_NO_ERROR;
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp:115]: This style of code makes the code hard to follow: the final `return err` depends on the initialization that happens at the start of the function and following to see if anything in the code changes it.

Please remove this declaration and do a explicit `return bFound ? CHIP_NO_ERROR : CHIP_ERROR_NOT_FOUND` or similar.

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h (hunk 39 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h]: GetEpochTS(), GetLocalDayOfWeekFromUnixEpoch(), GetLocalDayOfWeekNow(), GetMinutesPastMidnight() have now been moved into a separate module (examples/energy-management-app/energy-management-common/include/EnergyTimeUtils.h and examples/energy-management-app/energy-management-common/src/EnergyTimeUtils.cpp). The uint8_t bitmask has also been replaced with BitMask<EnergyEvse::TargetDayOfWeekBitmap>

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h (hunk 40 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h]: See above. Now using chip::app::Clusters::EnergyEvse::TargetDayOfWeekBitmap instead of a uint8_t.

File: examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp (hunk 49 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp]: See above. EnergyEvse::TargetDayOfWeekBitmap is being used instead of a uint8_t

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp (hunk 45 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp:86]: I have added `VerifyOrDie `to two of the `AllocAndCopy `method but not the following as it can be called multiple times for the same day
`ChargingTargetsMemMgr::AllocAndCopy(const DataModel::DecodableList<Structs::ChargingTargetStruct::DecodableType> & chargingTargets)
`

File: examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp (hunk 56 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp:159]: targetSoc is of type DataModel::Nullable<Percent>
chargingTarget.targetSoC is of type Optional<chip::Percent>
And there is no assignment operator between these two types.

File: examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp (hunk 57 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp]: Change made.

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h (hunk 53 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h]: This has been changed in the new file EnergyTimeUtils.cpp/h

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h [hunk 58]
```diff
@@ -0,0 +1,160 @@
...
+ */
+
+class ChargingTargetsMemMgr
+{
+public:
+    ChargingTargetsMemMgr();
+    ~ChargingTargetsMemMgr();
+
+    /**
+     * @brief This method sets the index (mChargingTargetSchedulesIdx) to use into mpListOfDays.
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h:89]: all these comments below reference `mpListOfDays`. That is not a public field and is an implementation detail. 

The documentation should describe what the class does, not the implementation. Unure if maybe just saying `list of days` makes sense, however you should never reference private bits in comments  for public API.

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h [hunk 59]
```diff
@@ -0,0 +1,160 @@
...
+     *        ChargingTargetsMemMgr::AddChargingTarget() needs to be called as each individual
+     *        chargingTarget is loaded from persistent data.
+     *
+     * @param chargingTarget  - The chargingTarget to add into mpListOfDays[mChargingTargetSchedulesIdx]
+     */
+    void AddChargingTarget(const EnergyEvse::Structs::ChargingTargetStruct::Type & chargingTarget);
+
+    /**
+     * @brief Called to allocate and copy the chargingTargets in mDailyChargingTargets to
+     *        mpListOfDays[mChargingTargetSchedulesIdx].
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h:114]: reprhrase this as well. mDailyChargingTargets is a private field ... the caller does not know what this is.

The public API should be documented in a way that is understandable for use without referencing/re-stating the private implementation. I still do not know what AllocAndCopy intent is based on this description.

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h [hunk 60]
```diff
@@ -0,0 +1,160 @@
...
+    /**
+     * @brief This method sets the index (mChargingTargetSchedulesIdx) to use into mpListOfDays.
+     *        This index is used in subsequent calls to GetChargingTargets and the AllocAndCopy
+     *        methods below.
+     *
+     *        NOTE: This method MUST be called each time a new day is added to
+     *        DataModel::List<const Structs::ChargingTargetScheduleStruct::Type> chargingTargetSchedules
+     *        before building up the ChargingTargetStruct associated with the mpListOfDays entry.
+     *
+     * @param chargingTargetSchedulesIdx  - The new index to use when accessing mpListOfDays
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h:97]: if this changes internal state for future calls, should this be named differently from `Reset` (it seems to be some `Prepare` or `Start` of sorts).

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h (hunk 59 above)
Comment (andy31415) [reply examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h:114]: what are `the chargingTargets` in the context of this call? I see no parameters here.

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h [hunk 61]
```diff
@@ -0,0 +1,160 @@
...
+     *        mpListOfDays[mChargingTargetSchedulesIdx].
+     *
+     * @param chargingTargets  - The chargingTargets to add into mpListOfDays[mChargingTargetSchedulesIdx]
+     */
+    CHIP_ERROR AllocAndCopy(const DataModel::DecodableList<Structs::ChargingTargetStruct::DecodableType> & chargingTargets);
+
+    /**
+     * @brief Returns the list of chargingTargets into mpListOfDays dependant on mChargingTargetSchedulesIdx.
+     *
+     * @return mpListOfDays[mChargingTargetSchedulesIdx]
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h:139]: how do I set `mChargingTarggetSchedulesIdx` ? Reading through the API, the only method seems `Reset` but that clears the targets so no point in getting them.

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h [hunk 62]
```diff
@@ -216,9 +250,16 @@ class EnergyEvseDelegate : public EnergyEvse::Delegate
 
     /* PREF attributes */
     DataModel::Nullable<uint32_t> GetNextChargeStartTime() override;
+    CHIP_ERROR SetNextChargeStartTime(DataModel::Nullable<uint32_t> newValue);
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h:253]: instead of `newValue` could we name it in some way to specify measurement?

I think this may be `epochSec` for example.

Also below: required energy is `energyMilliWattH`.

TargetSoC seems to be better because type is encoded as perced.

File: examples/energy-management-app/energy-management-common/include/EnergyEvseTargetsStore.h [hunk 63]
```diff
@@ -0,0 +1,122 @@
...
+     */
+    CHIP_ERROR ClearTargets();
+
+    /**
+     * Part of the FabricTable::Delegate interface. Gets called when a fabric is deleted, such as on FabricTable::Delete().
+     **/
+    virtual void OnFabricRemoved(const FabricTable & fabricTable, FabricIndex fabricIndex) override;
+
+private:
+    static uint16_t GetTlvSizeEstimate();
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/EnergyEvseTargetsStore.h:82]: Estimate seems like a `guess` in this context. This need some comment explaining this - is this an upper bound? 

We seem to use this to allocate memory to load things. In that case it does sound like we allocate sufficient size to be able to load anything. Is this correct? Should be this named accordingly (like upper bound/max-size/loading-size or something like that)?

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp (hunk 45 above)
Comment (andy31415) [reply examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp:88]: Don't they leak memory? Will check...

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp [hunk 64]
```diff
@@ -234,6 +230,81 @@ Status EnergyEvseDelegate::StartDiagnostics()
...
+ */
+Status EnergyEvseDelegate::ClearTargets()
+{
+    ChipLogProgress(AppServer, "EnergyEvseDelegate::ClearTargets()");
+
+    Status status = Status::Success;
+    CHIP_ERROR err;
+
+    EvseTargetsDelegate * targets = GetEvseTargetsDelegate();
+    VerifyOrExit(targets != nullptr, status = StatusIB(CHIP_ERROR_UNINITIALIZED).mStatus);
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp:291]: Can we avoid a `goto exit` just for the purpose of a return? That seems to force a large scope increase on err as well for no reason and this combines early return with gotoexit. This should probably be:

```cpp
EvseTargetsDelegate * targets = GetEvseTargetsDelegate();
if (targets == nullptr)
{
    return Status::Failure; /// TODO: is this right? using a CHIP_ERROR just obscures this ...
}

CHIP_ERROR err = targets->ClearTargets();
if (err != CHIP_NO_ERROR)
{
    // Status::Failure loses the original error information, so log it before it is lost.
    ChipLogError(App, "Failed to clear Evse targets: %" CHIP_ERROR_FORMAT, err.Format());
    return Status::Failure;
}

// The Application needs to be told that the Targets have been deleted
// so it can potentially re-optimize the charging start time etc
NotifyApplicationChargingPreferencesChange();
return Status::Success;
```

```

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp [hunk 65]
```diff
@@ -1378,18 +1445,100 @@ DataModel::Nullable<uint32_t> EnergyEvseDelegate::GetNextChargeStartTime()
...
 DataModel::Nullable<uint32_t> EnergyEvseDelegate::GetNextChargeTargetTime()
 {
     return mNextChargeTargetTime;
 }
+CHIP_ERROR EnergyEvseDelegate::SetNextChargeTargetTime(DataModel::Nullable<uint32_t> newValue)
+{
+    DataModel::Nullable<uint32_t> oldValue = mNextChargeTargetTime;
+
+    mNextChargeTargetTime = newValue;
+    if (oldValue != newValue)
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp:1478]: not: could you decrease indent by starting with:

```cpp
if (newValue == mNextChargetTargetTime)
{
    return CHIP_NO_ERROR;
}
```

or:

```cpp
VerifyOrReturnError(newValue != mNextChargeTargetTime, CHIP_NO_ERROR);
```

File: examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp [hunk 66]
```diff
@@ -0,0 +1,478 @@
...
+    uint16_t chargingTargetSchedulesIdx = 0;
+    while ((err = reader.Next(TLV::kTLVType_Structure, TLV::AnonymousTag())) == CHIP_NO_ERROR)
+    {
+        TLV::TLVType evseTargetEntryType;
+
+        ReturnErrorOnFailure(reader.EnterContainer(evseTargetEntryType));
+
+        // DayOfWeek bitmap
+        ReturnErrorOnFailure(reader.Next(TLV::ContextTag(TargetEntryTag::kDayOfWeek)));
+        ReturnErrorOnFailure(reader.Get(mChargingTargetSchedulesArray[chargingTargetSchedulesIdx].dayOfWeekForSequence));
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp:104]: what ensures that `chargingTargetSchedulesIdx < ArraySize(mChargingTargetSchedulesArray)` ?

File: examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp [hunk 67]
```diff
@@ -0,0 +1,478 @@
...
+
+        ChipLogProgress(AppServer, "LoadTargets: DayOfWeekForSequence = 0x%02x",
+                        mChargingTargetSchedulesArray[chargingTargetSchedulesIdx].dayOfWeekForSequence.GetField(
+                            static_cast<TargetDayOfWeekBitmap>(0x7F)));
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp:108]: we should have a constant like `kAllTargetDaysMask` to use this and everywhere else for the GetField mask.

File: examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp [hunk 68]
```diff
@@ -0,0 +1,478 @@
...
+                else
+                {
+                    // Something else unexpected here
+                    return CHIP_ERROR_UNEXPECTED_TLV_ELEMENT;
+                }
+            }
+
+            ReturnErrorOnFailure(reader.ExitContainer(chargingTargetsStructType));
+
+            [[maybe_unused]] int64_t addedEnergy = chargingTarget.addedEnergy.HasValue() ? chargingTarget.addedEnergy.Value() : 0;
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp:163]: use `ValueOr(0)` for better readability here and below.

**Review by andy31415 — APPROVED** [review]
In review for 6 months so adding a "consensus" review. I do not have sufficient background on this to fully review.

The bit that I assume will be fixed before merging is the potential memory leak and fixing up public API documentation to not reference implementation details (i.e. private fields).

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h (hunk 59 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h]: I have reworded the API to avoid implementation details.

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h (hunk 60 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h]: Reset() renamed to PrepareDaySchedule()

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h (hunk 61 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h]: I have reworded the API to avoid implementation details.

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h (hunk 62 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h]: Parameters renamed.

File: examples/energy-management-app/energy-management-common/include/EnergyEvseTargetsStore.h (hunk 63 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/EnergyEvseTargetsStore.h]: GetTlvSizeEstimate renamed to GetTlvSizeUpperBound

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp (hunk 64 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp]: Code restructured as suggested. We still return a Status as this get used in `chip::app::Clusters::EnergyEvse::Instance::HandleClearTargets`

File: examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp (hunk 66 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp:108]: There is now the following check:
`VerifyOrReturnError(chargingTargetSchedulesIdx < kEvseTargetsMaxNumberOfDays, CHIP_ERROR_INCORRECT_STATE);`

File: examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp (hunk 67 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp]: kAllTargetDaysMask is now defined in examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h and used appropriately.

File: examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp (hunk 68 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseTargetsStore.cpp]: Change made.

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp [hunk 69]
```diff
@@ -0,0 +1,179 @@
...
+
+    size_t numDailyChargingTargets = 0;
+    ReturnErrorOnFailure(chargingTargets.ComputeSize(&numDailyChargingTargets));
+
+    mNumDailyChargingTargets = static_cast<uint16_t>(numDailyChargingTargets);
+
+    if (mNumDailyChargingTargets > 0)
+    {
+        // Allocate the memory first and then use placement new to initialise the memory of each element in the array
+        mpListOfDays[mChargingTargetSchedulesIdx] = static_cast<EnergyEvse::Structs::ChargingTargetStruct::Type *>(
```
[the remark this answers is not in the document]
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp:156]: I have added a `VerifyOrDie(mpListOfDays[mChargingTargetSchedulesIdx] == nullptr); `There was a problem in EnergyEvseTargetsStore.cpp that was not calling the now called `PrepareDaySchedule `(previously `Reset`) ,method.

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h [hunk 70]
```diff
@@ -0,0 +1,153 @@
...
+    /**
+     * @brief Called as each individual chargingTarget is loaded from persistent data.
+     *        When loading the Target from persistent storage, it is not known upfront
+     *        how many chargingTargets are associated with this day schedule so
+     *        ChargingTargetsMemMgr::AddChargingTarget() needs to be called as each individual
+     *        chargingTarget is loaded from persistent data.
+     *
+     * @param chargingTarget  - The chargingTarget that will be added into the current day schedule
+     */
+    void AddChargingTarget(const EnergyEvse::Structs::ChargingTargetStruct::Type & chargingTarget);
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h:105]: you have a limit on how large your charging targets are (kEvseTargetsMaxTargetsPerDay it seems). This method returns void so it cannot report a failure. How is failure handled? documentation on the method should explain that.

File: examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp [hunk 71]
```diff
@@ -0,0 +1,189 @@
...
+        mpListOfDays[mChargingTargetSchedulesIdx] = nullptr;
+    }
+}
+
+void ChargingTargetsMemMgr::AddChargingTarget(const EnergyEvse::Structs::ChargingTargetStruct::Type & chargingTarget)
+{
+    if (mNumDailyChargingTargets < kEvseTargetsMaxTargetsPerDay)
+    {
+        mDailyChargingTargets[mNumDailyChargingTargets++] = chargingTarget;
+    }
```
Comment (andy31415) [inline examples/energy-management-app/energy-management-common/src/ChargingTargetsMemMgr.cpp:73]: Log if false. You should not silently fail.

File: examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h (hunk 70 above)
Comment (PeterC1965) [reply examples/energy-management-app/energy-management-common/include/ChargingTargetsMemMgr.h:105]: I have added some documentation.
