### PR TITLE
Load secure session parameters before sending message to the device

### LINKED ISSUE #4544: Receiving first ZCL command from Android CHIP Tool always fails.
#### Problem
When using Android CHIP Tool to control CHIP device running nrfconnect lock-app example there is a problem that sending first ON/OFF/TOGGLE command always results in data model processing failure. Following commands are processed properly and the first command is the only one that fails.

I noticed that source of a problem is Android CHIP Tool app and commit that seems to introduce it is:
https://github.com/project-chip/connectedhomeip/commit/fad6d0538fe1e6f906aa2e984f1fc3d02ecac001

When using Android CHIP Tool in previous revision, everything works fine. Revision of the lock-app firmware doesn't seem to have impact on it.

Below there are logs demonstrating problem. As you can see first message (the bolden one) is dropped due to invalid endpoint ID, which is different every time. Also RX len is bigger (25) than expected (3). There is also second message attached to show the proper message structure.
I: 22929[SVR] Packet received from UDP:2001:db8:2:0:88c5:d4a1:a7a6:5f77:46027: zu bytes
I: 22937[ZCL] APS frame processing success!                                                                                   
**I: 22941[ZCL] RX len 25, ep 13, clus 0x38a9                                                                                   
I: 22945[ZCL]  FC ea seq e8 cmd 9c payload[                                                                                   
I: 22949[ZCL] 0hX0hX0hX0hX0hX0hX0hX0hX0hX0hX0hX0hX0hX0hX0hX0hX0hX0hX0hX0hX0hX0hX                                              I: 22956[ZCL] ]                                                                                                                                                                                                                   
I: 22961[ZCL] Drop cluster 0x38a9 command 0x9c                                                                                
I: 22965[ZCL]  due to invalid endpoint:                                                                                       
I: 22969[ZCL] 0x13                                                                                                            
I: 22970[ZCL] Data model processing failure!**                                                                                  
I: 29304[SVR] Packet received from UDP:2001:db8:2:0:88c5:d4a1:a7a6:5f77:46027: zu bytes                                       
I: 29311[ZCL] APS frame processing success!                                                                                   
I: 29315[ZCL] RX len 3, ep 1, clus 0x 6                                                                                       
I: 29319[ZCL]  FC 1 seq 1 cmd 2 payload[                                                                                      
I: 29323[ZCL] NULL                                                                                                            
I: 29324[ZCL] ]                                                                                                                                                                                                                            I: 29329[ZCL] On/Off set value: 1 2                                                                                           
I: 29332[ZCL] Toggle on/off from 1 to 0                                                                                       
I: Unlock Action has been initiated  

 #### Proposed Solution

### PR DESCRIPTION
**Pull request by pan-apple**
#### Problem
After pairing the device, the first message sent by the controller is corrupted when received by the device. This happen only in certain use cases, where the UDP transport information in not updated in the peer connection table.

 #### Summary of Changes
1. Check peer connection table entry for transport type. If the transport is incorrect, reload the security parameter for the connection.
2. The packet at re-send is corrupted since the original packet got modified (encryption, and header attachment) before the original send failed. So, instead of refcounting the packet for resending, copy the packet data. With the current change, this logic is specifically exercised in scenarios where the OS releases the underlying socket. Otherwise, the original transmissions will not fail. 

 Fixes #4544

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]
Works like a charm! :+1: 
Thank you for cooperation and nailing down the problem :rocket:

**Review by saurabhst — APPROVED** [review]

**Comment by woody-apple** [comment]
@robszewczyk @andy31415 ?

**Review by kkasperczyk-no — APPROVED** [review]

**Review by kkasperczyk-no — APPROVED** [review]
It works for me too, good job, thanks for solving it!

File: src/controller/CHIPDevice.cpp [hunk 1]
```diff
@@ -56,50 +56,77 @@ namespace Controller {
...
-        err = LoadSecureSessionParameters(ResetTransport::kNo);
-        SuccessOrExit(err);
-    }
-    else
+    ReturnErrorOnFailure(LoadSecureSessionParametersIfNeeded(loadedSecureSession));
+
+    if (!loadedSecureSession)
     {
-        // Secure connection already exists
+        // Secure connection already existed
```
Comment (andy31415) [inline src/controller/CHIPDevice.cpp:69]: 'existed' reads odd to me.

**Review by andy31415 — APPROVED** [review]
