### PR TITLE
Spin up commissioners in chip-tool as needed.

### LINKED ISSUE #21828: Using different commissioner name other than beta or gamma in chip-tool interactive mode throws segmentation error
Issue:
While doing provision to RD1, RD2, RD3, RD4 and RD5 on distinct fabrics in RPI platform TC-IDM-7.1 facing following issue
After successful provision of RD4  using "--commissioner-name 4"  If RD4 is try to send any command in interactive mode throws segmentation error
 for example "basic write node-label 1 4 0  --commissioner-name 4" in interactive mode I am getting segmentation fault for commissioner-name other then beta or gamma
image

 * **expected behavior** : We should get the expected outcome as per test-plan
 * **actual behavior** : Segmentation fault
 * **steps to reproduce:-**
For example
 Commission DUT to TH
./chip-tool interactive start
For example below command, but for all the commands getting segmentation fault
basic write node-label 1 4 0  --commissioner-name 4

 **system configuration**
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : IP and wifi
Commit-ID : a1643eee5ef5534d494ae205bb586b4a9cbfee23 
Dut application: all-clusters-app
 
**PFA log below:-**
[TC-IDM-7.1.txt](https://github.com/project-chip/connectedhomeip/files/9308572/TC-IDM-7.1.txt)

**Test-Plan reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#tc-idm-7-1-multi-fabric-subscription-test-cases-dut_server

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
The basic change is that instead of spinning up commissioners during "stack
startup" for the three default identities plus the command's identity (in case
that's not one of the three defaults) we:

1) Spin up the commissioner for the command's identity when we're actually
   running the command (on the Matter event loop).  This allows commands in
   interactive mode to use an identity that is not one of the three default
   identities and fixes https://github.com/project-chip/connectedhomeip/issues/21828

2) Spin up commissioners as needed when they are requested.  This allows YAML
   test steps (which are not distinct commands) to use an identity that is not
   one of the three default identities.

#### Problem
See #21828 

#### Change overview
See above.

#### Testing
Checked the steps from #21828.  CI should check YAML bits.

### CODE REVIEW

File: examples/chip-tool/commands/common/CHIPCommand.cpp [hunk 1]
```diff
@@ -375,6 +380,24 @@ CHIP_ERROR CHIPCommand::InitializeCommissioner(std::string key, chip::FabricId f
...
+        chip::MutableByteSpan compressed_fabric_id_span(compressed_fabric_id);
+        ReturnLogErrorOnFailure(commissioner->GetCompressedFabricIdBytes(compressed_fabric_id_span));
+
+        ReturnLogErrorOnFailure(chip::GroupTesting::InitData(&sGroupDataProvider, fabricIndex, compressed_fabric_id_span));
+
+        // Configure the default IPK for all fabrics used by CHIP-tool. The epoch
+        // key is the same, but the derived keys will be different for each fabric.
+        chip::ByteSpan defaultIpk = chip::GroupTesting::DefaultIpkValue::GetDefaultIpk();
+        ReturnLogErrorOnFailure(
+            chip::Credentials::SetSingleIpkEpochKey(&sGroupDataProvider, fabricIndex, defaultIpk, compressed_fabric_id_span));
```
Comment (msandstedt) [inline examples/chip-tool/commands/common/CHIPCommand.cpp:398]: Just FYI, this interface can actually provide an IPK:

```
typedef void (*OnNOCChainGeneration)(void * context, CHIP_ERROR status, const ByteSpan & noc, const ByteSpan & icac,
                                     const ByteSpan & rcac, Optional<Crypto::AesCcm128KeySpan> ipk, Optional<NodeId> adminSubject);
```

This is where I would have tried to get the ipk.

How does this code here interact with the manual `AddKeySet` command?

Comment (msandstedt) [reply examples/chip-tool/commands/common/CHIPCommand.cpp:398]: Looking above, what's here appears to be functionally equivalent to what we had before.  So these are just questions, not an action for the PR.

**Review by msandstedt — APPROVED** [review]

File: examples/chip-tool/commands/common/CHIPCommand.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply examples/chip-tool/commands/common/CHIPCommand.cpp:398]: Fwiw, I just moved this code; it's not new and not being changed.

Past that, this code doesn't really get a NOC chain generation callback, as far as I can tell.

> How does this code here interact with the manual AddKeySet command?

That one probably allows overriding the IPK if used with keyset id 0.

File: examples/chip-tool/commands/common/CHIPCommand.cpp [hunk 2]
```diff
@@ -183,6 +150,40 @@ void CHIPCommand::MaybeTearDownStack()
...
+    }
+    else
+    {
+        fabricId = strtoull(identity.c_str(), nullptr, 0);
+        if (fabricId < kIdentityOtherFabricId)
+        {
+            ChipLogError(chipTool, "Invalid identity: %s", identity.c_str());
+            return CHIP_ERROR_INVALID_ARGUMENT;
+        }
+    }
```
Comment (tcarmelveilleux) [inline examples/chip-tool/commands/common/CHIPCommand.cpp:182]: So how do you create a FabricId 1234 under root of trust (identity) Alpha?

**Review by tcarmelveilleux — APPROVED** [review]

File: examples/chip-tool/commands/common/CHIPCommand.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply examples/chip-tool/commands/common/CHIPCommand.cpp:182]: You don't, either before or after this PR.  This PR is not changing the basic functionality, which is that "identity"means "fabric" in chip-tool.  It does not mean "root of trust".
