### PR TITLE
[server] Moved GetSetupPasscode failure log.

### LINKED ISSUE #22717: [BUG] Confusing error log is printed in case of using default passcode
### Reproduction steps

```bash
1.Use default passcode
2.See the error log:

E: 804 [SVR]GetCommissionableDataProvider()->GetSetupPasscode() failed: a0
I: 813 [SVR]*** Using default EXAMPLE passcode 20202021 ***

This error log may be confusing to user and make him think that something went wrong, while using default passcode for testing purpose is pretty usual thing.
```

### Bug prevalence

Every time if default passcode is used

### GitHub hash of the SDK that was being used

989ad8ec4d8004065c6c7cb090de23484f12b54f

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kkasperczyk-no**
#### Issue Being Resolved
* Fixes #22717

#### Change overview
Moved error log to be printed only if there is no default passcode to be used.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

File: src/app/server/OnboardingCodesUtil.cpp [hunk 1]
```diff
@@ -105,12 +105,12 @@ CHIP_ERROR GetPayloadContents(chip::PayloadContents & aPayload, chip::Rendezvous
     err = GetCommissionableDataProvider()->GetSetupPasscode(aPayload.setUpPINCode);
     if (err != CHIP_NO_ERROR)
     {
-        ChipLogError(AppServer, "GetCommissionableDataProvider()->GetSetupPasscode() failed: %" CHIP_ERROR_FORMAT, err.Format());
 #if defined(CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE) && CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE
         ChipLogProgress(AppServer, "*** Using default EXAMPLE passcode %u ***",
                         static_cast<unsigned>(CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE));
         aPayload.setUpPINCode = CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE;
 #else
+        ChipLogError(AppServer, "GetCommissionableDataProvider()->GetSetupPasscode() failed: %" CHIP_ERROR_FORMAT, err.Format());
```
Comment (bzbarsky-apple) [inline src/app/server/OnboardingCodesUtil.cpp:113]: I thought the point was that the default thing was a temporary workaround and we need to stop relying on it?

Comment (kkasperczyk-no) [reply src/app/server/OnboardingCodesUtil.cpp:113]: I think at some point we should do that, but currently we've got the whole group of test values https://github.com/project-chip/connectedhomeip/blob/master/src/include/platform/CHIPDeviceConfig.h#L886 that are used in the code without throwing an error, so I wanted to remove this discrepancy. To be honest I don't know whether all platforms are ready for removing test values or not.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]
