### PR TITLE
[dnssd] Fixed OT DNS API usage for Thread platform

### LINKED ISSUE #26101: Thread implementation of ChipDnssdResolve does not follow the DNS-SD spec, breaks with some DNS servers
It looks like the implementation of `ChipDnssdResolve` in `src/platform/OpenThread/DnssdImpl.cpp` ends up calling `otDnsClientResolveService`, which does queries for TXT and SRV records, but not the AAAA record.

DNS servers are allowed to include the AAAA record when an SRV record is queried (see https://datatracker.ietf.org/doc/html/rfc6763#section-12.2) but are not required to, and some (e.g. the Apple one) do not.

Devices are required to not assume the AAAA record will be included, see last paragraph of https://datatracker.ietf.org/doc/html/rfc6763#section-12 which says:

> Clients MUST be capable of functioning correctly with DNS servers (and Multicast DNS Responders) that fail to generate these additional records automatically, by issuing subsequent queries for any further record(s) they require.

But that assumption is _exactly_ what our `ChipDnssdResolve` implementation is making.  And when dealing with a DNS server that does not add the additional records, operational discovery will always fail.

What this means in practice is that OTA for the relevant Thread devices is unreliable at best (for example, it will work if the OTA provider and the node that sends the AnnounceOTAProvider command are the same node, but not otherwise), the sleepy check-in messages people are working on will just flat out not work in networks with a DNS server that does not add the additional records, binding will not work correctly in networks with such a DNS server, etc.

We need to either do the additional AAAA query when `otDnsClientResolveService` does not return an address, or fix `otDnsClientResolveService` to do that itself in addition to the TXT/SRV queries.

### PR DESCRIPTION
**Pull request by kkasperczyk-no**
Introduced several fixes to the Thread platform DNS implementation:
* Added checking if memory allocation for DnsResult was successful and dispatching dedicated methods to inform upper layer in case of memory allocation failure
* Added checking if DNS response for DNS resolve includes AAAA record. In case it doesn't the additional DNS query to obtain IPv6 address will be sent.
* Added checking if DNS response for DNS browse includes SRV, TXT and AAAA records. In case it doesn't the additional DNS queries to obtain SRV + TXT, and AAAA records will be sent.

Fixes: https://github.com/project-chip/connectedhomeip/issues/26101

### CODE REVIEW

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 1]
```diff
@@ -2580,6 +2580,42 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::FromOtDnsRespons
...
+    otDnsClientResolveAddress(ThreadStackMgrImpl().OTInstance(), fullHostName, OnDnsBrowseInvokedAddressResolveResult,
+                              reinterpret_cast<void *>(dnsResult), defaultConfig);
+
+    ThreadStackMgrImpl().UnlockThreadStack();
+}
+
+template <class ImplClass>
+void GenericThreadStackManagerImpl_OpenThread<ImplClass>::DispatchAddressResolve(intptr_t context)
+{
+    DnsResult * dnsResult = reinterpret_cast<DnsResult *>(context);
```
Comment (LuDuda) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2604]: As only the callback function is different, would it make sense to have one common method as you did with `OnDnsAddressResolveResult`?

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 2]
```diff
@@ -2647,32 +2706,57 @@ void GenericThreadStackManagerImpl_OpenThread<ImplClass>::OnDnsBrowseResult(otEr
...
     }
 
 exit:
     // Invoke callback to notify about end-of-browse or failure
     DnsResult * dnsResult = Platform::New<DnsResult>(aContext, error);
-    DeviceLayer::PlatformMgr().ScheduleWork(DispatchBrowseEmpty, reinterpret_cast<intptr_t>(dnsResult));
+
+    if (dnsResult == nullptr)
+    {
+        error = CHIP_ERROR_NO_MEMORY;
```
Comment (LuDuda) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2753]: Is this needed at all?

**Review by LuDuda — COMMENTED** [review]
Thanks! Great work :+1:

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp (hunk 1 above)
Comment (kkasperczyk-no) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2604]: I think I could create a wrapper implementing most of the functionality and taking callback name as an input, but still I guess we would need two different dispatch methods to pass the appropriate callbacks.

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 3]
```diff
@@ -2612,6 +2655,22 @@ void GenericThreadStackManagerImpl_OpenThread<ImplClass>::DispatchBrowse(intptr_
...
+}
+
+template <class ImplClass>
+bool GenericThreadStackManagerImpl_OpenThread<ImplClass>::IsIPv6AddressUnspecified(otIp6Address address)
+{
+    uint8_t emptyArray[OT_IP6_ADDRESS_SIZE];
+
+    memset(emptyArray, 0, sizeof(emptyArray));
+
+    return memcmp(address.mFields.m32, emptyArray, sizeof(emptyArray)) == 0 ? true : false;
```
[the remark this answers is not in the document]
Comment (kkasperczyk-no) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2671]: I wasn't aware that such method exists. Thanks!

**Review by LuDuda — APPROVED** [review]

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 4]
```diff
@@ -2580,6 +2580,36 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::FromOtDnsRespons
...
+
+    ThreadStackMgrImpl().LockThreadStack();
+
+    const otDnsQueryConfig * defaultConfig = otDnsClientGetDefaultConfig(ThreadStackMgrImpl().OTInstance());
+
+    char fullHostName[chip::Dnssd::kHostNameMaxLength + 1 + SrpClient::kDefaultDomainNameSize + 1];
+    snprintf(fullHostName, sizeof(fullHostName), "%s.%s", dnsResult->mMdnsService.mHostName, SrpClient::kDefaultDomainName);
+
+    otDnsClientResolveAddress(ThreadStackMgrImpl().OTInstance(), fullHostName, callback, reinterpret_cast<void *>(dnsResult),
+                              defaultConfig);
```
Comment (abtink) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2596]: This is ok as is, but we can simplify and pass `NULL` as config in `otDnsClientResolveAddress()` (which will then use the default config from `otDnsClientGetDefaultConfig()`).

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 5]
```diff
@@ -2702,11 +2769,51 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::_DnsBrowse(const
...
+                                                                               const otDnsAddressResponse * aResponse,
+                                                                               void * aContext,
+                                                                               AsyncWorkFunct dispatchAddressResolve)
 {
     CHIP_ERROR error;
-    DnsResult * dnsResult = Platform::New<DnsResult>(aContext, MapOpenThreadError(aError));
+    DnsResult * dnsResult = reinterpret_cast<DnsResult *>(aContext);
+    otIp6Address address;
+
+    error = MapOpenThreadError(otDnsAddressResponseGetAddress(aResponse, 0, &address, nullptr));
```
Comment (abtink) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2781]: We may receive multiple addresses in the "Address Resolve" response. In the code here we seem to get and use the first one (index is `0`).

 If we later need to pass all (or select one if there are multiple), we can iterate through the here (keep reading different `index` values until `otDnsAddressResponseGetAddress()` returns `OT_ERROR_NOT_FOUND`.

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 6]
```diff
@@ -2580,6 +2580,36 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::FromOtDnsRespons
...
+    DnsResult * dnsResult = reinterpret_cast<DnsResult *>(context);
+
+    ThreadStackMgrImpl().LockThreadStack();
+
+    const otDnsQueryConfig * defaultConfig = otDnsClientGetDefaultConfig(ThreadStackMgrImpl().OTInstance());
+
+    char fullHostName[chip::Dnssd::kHostNameMaxLength + 1 + SrpClient::kDefaultDomainNameSize + 1];
+    snprintf(fullHostName, sizeof(fullHostName), "%s.%s", dnsResult->mMdnsService.mHostName, SrpClient::kDefaultDomainName);
+
+    otDnsClientResolveAddress(ThreadStackMgrImpl().OTInstance(), fullHostName, callback, reinterpret_cast<void *>(dnsResult),
```
Comment (abtink) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2595]: Should we handle the `error` here?

If `otDnsClientResolveAddress()` returns an error then the passed-in  `callback` will not be invoked (and we may need to free/clear any allocated items, like I guess the `dnsResult`?)

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 7]
```diff
@@ -2647,32 +2690,56 @@ void GenericThreadStackManagerImpl_OpenThread<ImplClass>::OnDnsBrowseResult(otEr
...
-            // list due to large memory size needed to allocate on stack.
-            static_assert(ArraySize(dnsResult->mMdnsService.mName) >= ArraySize(serviceName),
-                          "The target buffer must be big enough");
-            Platform::CopyString(dnsResult->mMdnsService.mName, serviceName);
-            DeviceLayer::PlatformMgr().ScheduleWork(DispatchBrowse, reinterpret_cast<intptr_t>(dnsResult));
+            const otDnsQueryConfig * defaultConfig = otDnsClientGetDefaultConfig(ThreadStackMgrImpl().OTInstance());
+
+            error = MapOpenThreadError(otDnsClientResolveService(ThreadStackMgrImpl().OTInstance(), serviceName, type,
+                                                                 OnDnsBrowseInvokedResolveResult,
+                                                                 reinterpret_cast<void *>(dnsResult), defaultConfig));
```
Comment (abtink) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2709]: Same here. We can pass `NULL` instead of `defaultConfig` which will then use default config.

**Review by abtink — COMMENTED** [review]
Thanks @kkasperczyk-no.
Looks good overall. Couple of suggestions and questions below.

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp (hunk 5 above)
Comment (kkasperczyk-no) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2781]: Yes, I know, however the structure used to represent DNS service in Matter currently includes only one IP address. Based on my local tests it seems the Matter devices also include only one IP address in DNS records, but it's a good point what should happen if there would be more of them. We can still pick only one IP address, but what criteria should we use to select it? @bzbarsky-apple do you have any opinion on that?

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp (hunk 6 above)
Comment (kkasperczyk-no) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp]: Yes, thank you for catching it!. It's fixed.

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 8]
```diff
@@ -2647,32 +2690,56 @@ void GenericThreadStackManagerImpl_OpenThread<ImplClass>::OnDnsBrowseResult(otEr
...
         {
-            // Invoke callback for every service one by one instead of for the whole
-            // list due to large memory size needed to allocate on stack.
-            static_assert(ArraySize(dnsResult->mMdnsService.mName) >= ArraySize(serviceName),
-                          "The target buffer must be big enough");
-            Platform::CopyString(dnsResult->mMdnsService.mName, serviceName);
-            DeviceLayer::PlatformMgr().ScheduleWork(DispatchBrowse, reinterpret_cast<intptr_t>(dnsResult));
+            const otDnsQueryConfig * defaultConfig = otDnsClientGetDefaultConfig(ThreadStackMgrImpl().OTInstance());
+
+            error = MapOpenThreadError(otDnsClientResolveService(ThreadStackMgrImpl().OTInstance(), serviceName, type,
```
[the remark this answers is not in the document]
Comment (kkasperczyk-no) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp]: I believe it's out of date after refactor done in the last commit.

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 9]
```diff
@@ -2647,32 +2690,56 @@ void GenericThreadStackManagerImpl_OpenThread<ImplClass>::OnDnsBrowseResult(otEr
         serviceInfo.mTxtData            = txtBuffer;
         serviceInfo.mTxtDataSize        = sizeof(txtBuffer);
 
-        error = MapOpenThreadError(otDnsBrowseResponseGetServiceInfo(aResponse, serviceName, &serviceInfo));
+        otError err = otDnsBrowseResponseGetServiceInfo(aResponse, serviceName, &serviceInfo);
+        error       = MapOpenThreadError(err);
 
-        VerifyOrExit(error == CHIP_NO_ERROR, );
+        VerifyOrExit(err == OT_ERROR_NOT_FOUND || err == OT_ERROR_NONE, );
```
[the remark this answers is not in the document]
Comment (kkasperczyk-no) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2715]: You are right, the callbacks synchronization is wrong here. I didn't want to implement this behavior in Discovery_ImplPlatform, as the current problem was strictly related to the OpenThread API usage. However now I think that providing proper events and calls synchronization in the Thread platform may be more complicated than I initially thought. And moreover Discovery_ImplPlatform has it already implemented. The only missing thing is checking the content of data passed to the callback. I refactored the code to follow this approach, please re-review it.

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 10]
```diff
@@ -2498,26 +2498,12 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::_SetSrpDnsCallba
...
-        return CHIP_ERROR_INVALID_ARGUMENT;
-    }
-    Platform::CopyString(mdnsService.mHostName, serviceInfo.mHostNameBuffer);
-
-    if (strchr(serviceType, '.') == nullptr)
-        return CHIP_ERROR_INVALID_ARGUMENT;
-
     // Extract from the <type>.<protocol>.<domain-name>. the <type> part.
-    substringSize = strchr(serviceType, '.') - serviceType;
+    size_t substringSize = strchr(serviceType, '.') - serviceType;
```
Comment (Damian-Nordic) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2506]: I know it's the existing code, but this `substringSize` does not seem to be used when copying the string to `mdnsService`, right? Maybe we should file a followup issue to fix this as well?

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 11]
```diff
@@ -2549,37 +2535,100 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::FromOtDnsRespons
...
+
+        // Extract from the <hostname>.<domain-name>. the <hostname> part.
+        substringSize = strchr(serviceInfo.mHostNameBuffer, '.') - serviceInfo.mHostNameBuffer;
+        if (substringSize >= ArraySize(mdnsService.mHostName))
+        {
+            return CHIP_ERROR_INVALID_ARGUMENT;
+        }
+        Platform::CopyString(mdnsService.mHostName, serviceInfo.mHostNameBuffer);
+
+        if (strchr(serviceType, '.') == nullptr)
```
Comment (Damian-Nordic) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2553]: This is unrelated to the host name. It should have been used before line 2506.

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 12]
```diff
@@ -2549,37 +2535,100 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::FromOtDnsRespons
...
     {
-        if (txtEntry.mKey == nullptr || txtEntry.mValue == nullptr)
-            continue;
-
-        serviceTxtEntries.mTxtEntries[entryIndex].mKey      = alloc.Clone(txtEntry.mKey);
-        serviceTxtEntries.mTxtEntries[entryIndex].mData     = alloc.Clone(txtEntry.mValue, txtEntry.mValueLength);
-        serviceTxtEntries.mTxtEntries[entryIndex].mDataSize = txtEntry.mValueLength;
-        entryIndex++;
+        mdnsService.mAddressType = Inet::IPAddressType::kIPv6;
+        mdnsService.mAddress     = chip::Optional<chip::Inet::IPAddress>(ToIPAddress(serviceInfo.mHostAddress));
```
Comment (Damian-Nordic) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2566]:
```suggestion
        mdnsService.mAddress     = MakeOptional(ToIPAddress(serviceInfo.mHostAddress));
```

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp (hunk 5 above)
Comment (bzbarsky-apple) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2787]: @kkasperczyk-no The code that calls into this code expects to get a callback that contains:

1. The context it initially provided.
2. A `Dnssd::DnssdService *`.
3. A `Span<Inet::IPAddress>` of addresses.
4. The success-or-error status.

This code is choosing to keep track of that "list of addresses" in the single address slot of the `DnssdService`, but that's an implementation choice....  That said, refactoring this code to support the full list of addresses, if we want to do that, should be a separate PR.

Note, by the way, that in the "server includes AAAA with the SRV/TXT response" case you will only get a single address, based on what I see from the OpenThread APIs, not all the addresses.  So unless you do an unconditional separate resolve, you will just get whatever single address the DNS server picked there anyway.

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp (hunk 10 above)
Comment (bzbarsky-apple) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2506]: Yes, this seems kind of broken; followup for this, please.  And the part below that's copying into `protocol` seems broken too...

Comment (bzbarsky-apple) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2506]: This lost the check that makes this safe:
```
    if (strchr(serviceType, '.') == nullptr)
        return CHIP_ERROR_INVALID_ARGUMENT;
```
because that looks like it was incorrectly moved to the block below.

Comment (kkasperczyk-no) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:2509]: I pushed another commit fixing the mentioned string copying.

**Review by Damian-Nordic — APPROVED** [review]

**Review by jepenven-silabs — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
Thank you for fixing this!
