### PR TITLE
CASESession: Fix SessionResumption bugs

### LINKED ISSUE #17439: CASESession::EstablishSession does not support session resumption
#### Problem
CASESession::EstablishSession ignores the sessionResumptionStorage argument, thereby disabling session resumption.

 #### Proposed Solution
Do not ignore sessionResumptionStorage argument, e.g. by:
mSessionResumptionStorage = sessionResumptionStorage;

### LINKED ISSUE #17440: CASESession::DeriveSecureSession conflicts with specification
#### Problem
CASESession::DeriveSecureSession conflicts with specification see "Resumption Session Encryption Keys". The msg_salt needs to be constructed differently in case of session resumption.

 #### Proposed Solution
Pseudo code:
if (mState == kSentSigma1Resume || mState == kSentSigma2Resume)
{
    // construct msg_salt from mInitiatorRandom and mResumptionId
}
else
{
    // construct msg_salt from mIPK and mMessageDigest
}

### LINKED ISSUE #17450: CASESession: data needed for resumption key derivation is uninitialized
#### Problem
mInitiatorRandom and mResumptionId are needed to derive resumption keys as per the specification. Yet mInitiatorRandom is left uninitialized in the server and mResumptionId is left uninitialized in the client.

 #### Proposed Solution
1 - in HandleSigma1() after calling ParseSigma1() add:
memcpy(mInitiatorRandom, initiatorRandom.data(), sizeof(mInitiatorRandom));

2 - in HandleSigma2Resume() after getting resumptionId from TLV add:
mResumptionId = resumptionId;

### PR DESCRIPTION
**Pull request by kghost**
#### Problem
* #17439
* #17440
* #17450

#### Change overview
* Removed `mCASESessionEstablished`, this is implied by `mState`
  * Add 2 new states `kFinished` and `kFinishedResumed` for finish state, also distinguish whether it is resumed or not
* In `CASESession::DeriveSecureSession` generate correct keys.

#### Testing
Passed unit-tests

### CODE REVIEW

File: src/protocols/secure_channel/CASESession.cpp [hunk 1]
```diff
@@ -284,30 +279,51 @@ void CASESession::OnResponseTimeout(ExchangeContext * ec)
...
-    (void) kKDFSEInfo;
-    (void) kKDFSEInfoLength;
+    switch (mState)
+    {
+    case State::kFinished: {
+        // Generate Salt for Encryption keys
+        size_t saltlen = sizeof(mIPK) + kSHA256_Hash_Length;
 
-    VerifyOrReturnError(mCASESessionEstablished, CHIP_ERROR_INCORRECT_STATE);
+        chip::Platform::ScopedMemoryBuffer<uint8_t> msg_salt;
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:288]: No need for a scoped memory buffer here. If you make `saltlen` a `constexpr size_t`, you can use a basic stack buffer. It is very small and this avoids one more possible heap buffer needed where stack would easily be OK.

File: src/protocols/secure_channel/CASESession.cpp [hunk 2]
```diff
@@ -1486,16 +1508,27 @@ CHIP_ERROR CASESession::SetEffectiveTime()
...
     }
 
-    mState = kInitialized;
+    switch (mState)
+    {
+    case State::kSentSigma3:
+        mState = State::kFinished;
+        break;
+    case State::kSentSigma2Resume:
+        mState = State::kFinishedResumed;
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1525]: `kFinishedFromResume` may be a better name

File: src/protocols/secure_channel/CASESession.cpp [hunk 3]
```diff
@@ -1486,16 +1508,27 @@ CHIP_ERROR CASESession::SetEffectiveTime()
...
+        break;
+    default:
+        VerifyOrDie(false);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1528]:
```suggestion
        VerifyOrDie(false && "Reached invalid internal state keeping in CASE session");
```

**Review by tcarmelveilleux — APPROVED** [review]

File: src/protocols/secure_channel/CASESession.cpp [hunk 4]
```diff
@@ -284,30 +279,51 @@ void CASESession::OnResponseTimeout(ExchangeContext * ec)
...
+        ReturnErrorOnFailure(session.InitFromSecret(ByteSpan(mSharedSecret, mSharedSecret.Length()),
+                                                    ByteSpan(msg_salt.Get(), saltlen),
+                                                    CryptoContext::SessionInfoType::kSessionEstablishment, mRole));
 
-        VerifyOrReturnError(bbuf.Fit(), CHIP_ERROR_BUFFER_TOO_SMALL);
+        return CHIP_NO_ERROR;
     }
+    case State::kFinishedResumed: {
+        // Generate Salt for Encryption keys
+        size_t saltlen = sizeof(mInitiatorRandom) + mResumeResumptionId.size();
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:306]: Again, can be constexpr and use a stack buffer.

File: src/protocols/secure_channel/CASESession.cpp [hunk 5]
```diff
@@ -284,30 +279,51 @@ void CASESession::OnResponseTimeout(ExchangeContext * ec)
...
+            bbuf.Put(mResumeResumptionId.data(), mResumeResumptionId.size());
+
+            VerifyOrReturnError(bbuf.Fit(), CHIP_ERROR_BUFFER_TOO_SMALL);
+        }
 
-    ReturnErrorOnFailure(session.InitFromSecret(ByteSpan(mSharedSecret, mSharedSecret.Length()), ByteSpan(msg_salt.Get(), saltlen),
-                                                CryptoContext::SessionInfoType::kSessionEstablishment, mRole));
+        ReturnErrorOnFailure(session.InitFromSecret(ByteSpan(mSharedSecret, mSharedSecret.Length()),
+                                                    ByteSpan(msg_salt.Get(), saltlen),
+                                                    CryptoContext::SessionInfoType::kSessionResumption, mRole));
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:320]: It looks like the callee does not handle kSessionResumption per spec.  It uses an "info" value that does not match the spec.  Followup to fix that, please?

File: src/protocols/secure_channel/CASESession.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/protocols/secure_channel/CASESession.cpp:1525]: Or `kFinishedResuming` or `kFinishedViaResume`?

File: src/protocols/secure_channel/CASESession.cpp (hunk 5 above)
Comment (kghost) [reply src/protocols/secure_channel/CASESession.cpp:320]: Fixed in this PR

**Review by bzbarsky-apple — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]
