### PR TITLE
[nrfconnect] Fixed CHIPoBLE advertising when not in pairing mode.

### LINKED ISSUE #7098: [nrfconnect] Don't advertise CHIP bits over BLE if we are not in commissioning mode
#### Problem
After #7081 nrfconnect apps keep advertising over BLE to support DFU.  But we should not advertise _CHIP_ bits over BLE unless we are in commissioning mode.

 #### Proposed Solution
Shut off the CHIP parts of the BLE advertisement when we're not in commissioning mode.

### PR DESCRIPTION
**Pull request by kkasperczyk-no**
#### Problem
Currently for the Device Firmware Upgrade purposes nrfconnect devices may advertise over BLE even with Thread enabled and not in the pairing mode. However they should not advertise CHIPoBLE service, but the one used for DFU (SMP).

#### Change overview
* Added DFUoverSMP module handling performing DFU over BLE using SMP protocol.
* Simplified command used to build the target with DFU support to just one flag called DBUILD_WITH_DFU.
* Refactored BLEManager to register CHIPoBLE GATT service only when CHIPoBLE advertising is working.
* By the way changed lighting-app config to start pairing mode autostart on boot, as it is no longer forbidden by the spec.
* Aligned docs.

Basically after this change the current behavior is as follows:
* When CHIPoBLE advertising is disabled (pairing window off) and DFU is off BLE advertising is disabled.
* When CHIPoBLE advertising is disabled (pairing window off) and DFU is on BLE advertising of SMP service is enabled.
* When BLE advertising of SMP service is enabled and we start pairing mode, the CHIPoBLE advertising is used instead of SMP.
* When BLE advertising of CHIPoBLE advertising is working and we enable DFU, nothing happens, SMP advertising cannot replace CHIPoBLE advertising.
* When DFU is enabled, CHIPoBLE service is advertised and device is commissioned, so Thread is enabled - CHIPoBLE advertising stops and is replaced by SMP advertising.
* When DFU is enabled, CHIPoBLE service is advertised and CHIPoBLE advertising timeout expires - CHIPoBLE advertising stops and is replaced by SMP advertising.

Drawings may help in understanding :smile: 

image

#### Testing
Verified on nrfconnect platform that:

- Advertising behavior is as described above

- Device Firmware Upgrade over BLE using SMP works correctly.

- Commissioning over BLE with Python CHIP controller works correctly.

Fixes: https://github.com/project-chip/connectedhomeip/issues/7098

### CODE REVIEW

**Comment by msandstedt** [comment]
>     * When BLE advertising of CHIPoBLE advertising is working and we enable DFU, nothing happens, SMP advertising cannot replace CHIPoBLE advertising.

Should this somehow be surfaced as an error?

**Review by woody-apple — APPROVED** [review]

**Comment by kkasperczyk-no** [comment]
> > ```
> > * When BLE advertising of CHIPoBLE advertising is working and we enable DFU, nothing happens, SMP advertising cannot replace CHIPoBLE advertising.
> > ```
> 
> Should this somehow be surfaced as an error?

@msandstedt I believe not. What we need to successfully perform DFU over SMP is SMP GATT service registered, so even when advertising only Matter information, we can still connect to the device and discover SMP service properly.

File: examples/lighting-app/nrfconnect/main/AppTask.cpp [hunk 1]
```diff
@@ -426,13 +389,25 @@ void AppTask::StartBLEAdvertisementHandler(AppEvent * aEvent)
...
-    if (event->CHIPoBLEAdvertisingChange.Result == kActivity_Started)
+    if (event->CHIPoBLEAdvertisingChange.Result == kActivity_Stopped)
+    {
+#ifdef CONFIG_CHIP_NFC_COMMISSIONING
+        NFCMgr().StopTagEmulation();
+#endif
+#ifdef CONFIG_MCUMGR_SMP_BT
+        // After CHIPoBLE advertising stop, start advertising SMP in case Thread is enabled or there are no active CHIPoBLE
+        // connections (exclude the case when CHIPoBLE advertising is stopped on the connection time)
+        if (GetDFUOverSMP().IsEnabled() && (ConnectivityMgr().IsThreadProvisioned() || ConnectivityMgr().NumBLEConnections() == 0))
```
Comment (msandstedt) [inline examples/lighting-app/nrfconnect/main/AppTask.cpp:405]: If I understand this and the PR description, I believe `IsThreadProvisioned()` is being used as a proxy to determine  whether the device is commissioned to a Matter fabric.

If so, that seems like a fragile assumption.  This would definitely break if the device is manually joined to a Thread network through the debug console before proceeding to commissioning (which otherwise is a useful thing to do).  

Is there a more formal way for us to determine whether this node is commissioned to one or more fabrics?  That is ultimately the thing we want to branch on, correct?

Comment (kkasperczyk-no) [reply examples/lighting-app/nrfconnect/main/AppTask.cpp:405]: Just to clarify, do you mean the situation that we join the Thread network manually and because of that IsThreadProvisioned() condition is met, even though we are actually not commissioned, so the pairing window will not be open? If yes, I think that's a valid point. Moreover we already use the same check in other places like here: https://github.com/project-chip/connectedhomeip/blob/master/src/app/server/Server.cpp#L522

Do you think that better option would be checking IsFullyProvisioned() condition? Currently with that one TODO: https://github.com/project-chip/connectedhomeip/blob/master/src/include/platform/internal/GenericConfigurationManagerImpl.cpp#L923 it doesn't seem to make much difference ...

Comment (kkasperczyk-no) [reply examples/lighting-app/nrfconnect/main/AppTask.cpp:405]: Going even further I think that currently most platforms doesn't allow to trigger starting BLE advertising basing on the IsThreadProvisioned() condition: https://github.com/project-chip/connectedhomeip/blob/master/examples/lock-app/qpg/src/AppTask.cpp#L342

Comment (msandstedt) [reply examples/lighting-app/nrfconnect/main/AppTask.cpp:405]: > Just to clarify, do you mean the situation that we join the Thread network manually and because of that IsThreadProvisioned() condition is met, even though we are actually not commissioned, so the pairing window will not be open? If yes, I think that's a valid point.

Yes, exactly.

> Do you think that better option would be checking IsFullyProvisioned() condition? Currently with that one TODO: https://github.com/project-chip/connectedhomeip/blob/master/src/include/platform/internal/GenericConfigurationManagerImpl.cpp#L923 it doesn't seem to make much difference ...

I suppose yes.  But `IsFullyProvisioned()` is provided by the configuration manager and may need some work.  It definitely seems odd in the context of multi-admin.  Maybe that's just naming.  Maybe it should be called `IsJoinedToOneOrMoreFabrics()`.  I'm sure code would would need to be tweaked though to make this evaluate correctly in multi-admin scenarios.

> I created an issue to track this one, as I believe that fixing all occurences in the code is a bit out of this PR scope: #8897

Sounds good.  Thank you!

**Review by msandstedt — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
