### PR TITLE
Fix APIs involved in the MTROperationalCredentialsDelegate.

### LINKED ISSUE #23439: Need to rename Darwin AttestationInfo and CSRInfo interfaces
They should be called MTRAttestationInfo and MTRCSRInfo.  That was asked for during review, but apparently the PR author chose to ignore the review comments...

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
* Rename CSRInfo to MTROperationalCSRInfo
* Rename the properties of MTROperationalCSRInfo to match the spec more closely.
* Rename AttestationInfo to MTRAttestationInfo.
* Fix naming of the API on MTRDeviceController to follow conventions better, document the API more clearly, and have it return errors as needed.
* Rename MTRNOCChainIssuer to MTROperationalCertificateIssuer
* Change signature of the one method on MTROperationalCertificateIssuer to have better naming, take a controller, and name the completion block "completion".
* Change the completion signature on MTROperationalCertificateIssuer to allow the external certificate issuer to return an error (e.g. if its device attestation checks failed).
* Don't ask the external issuer for the IPK, since we should already have that anyway (from our controller init).
* Allow the external issuer to return nil for the intermediate certificate, to indicate that there isn't one.
* Make sure that all our access to mOnNOCCompletionCallback happens on the Matter queue, so we don't have thread races on that member.
* Make all the dispatch we do as part of the credential-issuing process async.
* Introduce backwards-compat shims for all the API changes for now.

Fixes https://github.com/project-chip/connectedhomeip/issues/23439

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRAttestationInfo.h [hunk 1]
```diff
@@ -23,6 +23,36 @@ NS_ASSUME_NONNULL_BEGIN
...
+
+@property (nonatomic, copy, readonly) NSData * nonce;
+
+@property (nonatomic, copy, readonly) NSData * elements;
+
+@property (nonatomic, copy, readonly) NSData * elementsSignature;
+
+@property (nonatomic, copy, readonly) NSData * dac;
+
+@property (nonatomic, copy, readonly) NSData * pai;
```
Comment (jtung-apple) [inline src/darwin/Framework/CHIP/MTRAttestationInfo.h:38]: Seeing how we are expanding “NOC”, I’m wondering if we should take this opportunity to also change “dac” and “pai” into longer names?

```suggestion
@property (nonatomic, copy, readonly) NSData * deviceAttestationCert;

@property (nonatomic, copy, readonly) NSData * productAttestationIntermediateCert;
```

Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRAttestationInfo.h]: Done, good catch.

**Review by jtung-apple — APPROVED** [review]

File: src/darwin/Framework/CHIP/MTRCSRInfo.h [hunk 2]
```diff
@@ -20,9 +20,31 @@
...
+ * CSRNonce fields from that structure.
  *
+ * The AttestationSignature from the CSRResponse command is also included.  This
+ * signs a concatenation of csrElements and the attestationChallenge found in
+ * MTRAttestationInfo.
  */
+MTR_NEWLY_AVAILABLE
+@interface MTROperationalCSRInfo : NSObject
+
+@property (nonatomic, copy, readonly) NSData * csr;
```
Comment (ksperling-apple) [inline src/darwin/Framework/CHIP/MTRCSRInfo.h:35]: Should this be `MTRCertificateDERBytes` ? I guess it's not strictly a certificate, but it's DER...

File: src/darwin/Framework/CHIP/MTRCSRInfo.h [hunk 3]
```diff
@@ -20,9 +20,31 @@
...
+@property (nonatomic, copy, readonly) NSData * csrNonce;
+@property (nonatomic, copy, readonly) NSData * csrElements;
```
Comment (ksperling-apple) [inline src/darwin/Framework/CHIP/MTRCSRInfo.h:37]: It would be nice if it was more obvious which is the overall TLV structure... maybe this property could be called `rawTLV` or something along those lines? Also would be nice if we had a generic `MTRTLVBytes` type.

File: src/darwin/Framework/CHIP/MTRDeviceController.h [hunk 4]
```diff
@@ -118,18 +118,33 @@ typedef void (^MTRDeviceConnectionCallback)(MTRBaseDevice * _Nullable device, NS
...
  *
- * @param[in] nocChainIssuer the NOC Chain issuer to use for issuer operational certs
+ * When using an external operational certificate issuer, all device attestation
+ * checks that require some sort of trust anchors are delegated to the external
+ * certificate issuer.  Specifically, the following device attestation checks
+ * are not performed and must be done by the operationalCertificateIssuer:
  *
- * @param[in] queue The queue on which the callbacks will be delivered
+ * (1) Make sure the PAA is valid and approved by CSA.
+ * (2) vid-scoped PAA check: if the PAA is vid scoped, then its vid must match the DAC vid.
```
Comment (ksperling-apple) [inline src/darwin/Framework/CHIP/MTRDeviceController.h:134]: Nit: `VID` should probably be all-caps in text?

File: src/darwin/Framework/CHIP/MTROperationalCertificateIssuer.h [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+ * used.
+ */
+MTR_NEWLY_AVAILABLE
+@interface MTROperationalCertificateInfo : NSObject
+@property (nonatomic, copy) MTRCertificateDERBytes operationalCertificate;
+@property (nonatomic, copy, nullable) MTRCertificateDERBytes intermediateCertificate;
+@property (nonatomic, copy) MTRCertificateDERBytes rootCertificate;
+@property (nonatomic, copy, nullable) NSNumber * adminSubject;
+
++ (instancetype)infoWithOperationalCertificate:(MTRCertificateDERBytes)operationalCertificate
```
Comment (ksperling-apple) [inline src/darwin/Framework/CHIP/MTROperationalCertificateIssuer.h:44]: Is there some particular reason for using a factory method instead of an initializer here?

File: src/darwin/Framework/CHIP/MTRCSRInfo.h (hunk 2 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRCSRInfo.h:35]: For certs the key is to distinguish DER-encoded certs from TLV-encoded certs.  For the CSR, we don't ever have a TLV-encoded CSR floating around so there isn't any confusion....

File: src/darwin/Framework/CHIP/MTRCSRInfo.h (hunk 3 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRCSRInfo.h:37]: MTRTLVBytes makes a lot of sense.  Will add that, and add better docs here, along with possible renaming as needed.

File: src/darwin/Framework/CHIP/MTRDeviceController.h (hunk 4 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDeviceController.h:134]: Makes sense.  I copied this comment from another place and lightly edited, but looks like I should have done a bit more careful editing.

File: src/darwin/Framework/CHIP/MTROperationalCertificateIssuer.h (hunk 5 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTROperationalCertificateIssuer.h:44]: Not really; I wasn't sure which was the more idiomatic thing to do, or both.

Comment (ksperling-apple) [reply src/darwin/Framework/CHIP/MTROperationalCertificateIssuer.h:44]: I think initializer would be the default. I'd generally use a factory method if you might want to return a cached instance, or return an instance of a particular sub-class depending on parameters, that sort of thing.

File: src/darwin/Framework/CHIP/MTROperationalCredentialsDelegate.h [hunk 6]
```diff
@@ -120,22 +120,9 @@ class MTROperationalCredentialsDelegate : public chip::Controller::OperationalCr
...
-     * If ipk and adminSubject are non nil, then they will be used in the AddNOC command sent to the commissionee. If they are not
-     * populated, then the values provided in the MTRDeviceController initialization will be used.
-     */
-    void onNOCChainGenerationComplete(NSData * operationalCertificate, NSData * intermediateCertificate, NSData * rootCertificate,
-        NSData * _Nullable ipk, NSNumber * _Nullable adminSubject, NSError * __autoreleasing * error);
-
-    void setNSError(CHIP_ERROR err, NSError * __autoreleasing * outError);
-
-    CHIP_ERROR CallbackGenerateNOCChain(const chip::ByteSpan & csrElements, const chip::ByteSpan & csrNonce,
+    void ExternalNOCChainGenerated(MTROperationalCertificateInfo * _Nullable info, NSError * _Nullable error);
```
Comment (cliffamzn) [inline src/darwin/Framework/CHIP/MTROperationalCredentialsDelegate.h:123]: addition of documentation of here would be useful

File: src/darwin/Framework/CHIP/MTRDeviceController.mm [hunk 7]
```diff
@@ -548,20 +548,33 @@ - (void)setDeviceControllerDelegate:(id<MTRDeviceControllerDelegate>)delegate qu
     });
 }
 
-- (void)setNocChainIssuer:(id<MTRNOCChainIssuer>)nocChainIssuer queue:(dispatch_queue_t)queue
+- (BOOL)setOperationalCertificateIssuer:(nullable id<MTROperationalCertificateIssuer>)operationalCertificateIssuer
```
Comment (cliffamzn) [inline src/darwin/Framework/CHIP/MTRDeviceController.mm:551]: rather than pass back a bool, can we just pass back the error code?

In this implementation, error is sometimes set and sometimes unset and its an out var, might be just simpler to pass back `CHIP_NO_ERROR` if its a success

File: src/darwin/Framework/CHIP/MTRDeviceController.h [hunk 8]
```diff
@@ -118,18 +118,33 @@ typedef void (^MTRDeviceConnectionCallback)(MTRBaseDevice * _Nullable device, NS
...
+ * (3) cert chain check: verify PAI is signed by PAA, and DAC is signed by PAI.
+ * (4) PAA subject key id extraction: the PAA subject key must match the PAA key referenced in the PAI.
+ * (5) CD signature check: make sure a valid CSA CD key is used to sign the CD.
+ *
+ * @param[in] operationalCertificateIssuer the operationalCertificateIssuer to
+ *            use for issuing operational certs
+ *
+ * @param[in] queue The queue on which the calls into the
+ *                  operationalCertificateIssuer will happen.
  */
```
Comment (cliffamzn) [inline src/darwin/Framework/CHIP/MTRDeviceController.h:144]: missing `out` param here

File: src/darwin/Framework/CHIP/MTRDeviceController.mm [hunk 9]
```diff
@@ -1105,4 +1172,10 @@ - (void)setPairingDelegate:(id<MTRDevicePairingDelegate>)delegate queue:(dispatc
     [self setDeviceControllerDelegate:delegateShim queue:queue];
 }
 
+- (void)setNocChainIssuer:(id<MTRNOCChainIssuer>)nocChainIssuer queue:(dispatch_queue_t)queue
+{
+    [self setOperationalCertificateIssuer:[[MTROperationalCertificateChainIssuerShim alloc] initWithIssuer:nocChainIssuer]
+                                    queue:queue
+                                    error:nil];
```
Comment (cliffamzn) [inline src/darwin/Framework/CHIP/MTRDeviceController.mm:1179]: isn't this dangerous if queue is nil and we try to set an error?

File: src/darwin/Framework/CHIP/MTROperationalCredentialsDelegate.h (hunk 6 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTROperationalCredentialsDelegate.h:123]: Can do.

File: src/darwin/Framework/CHIP/MTRDeviceController.mm (hunk 7 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDeviceController.mm:551]: This is the normal API shape for sync-fallible Darwin APIs: a return type that can be tested as a boolean, and an out param for the error in case the consumer wants it.

File: src/darwin/Framework/CHIP/MTRDeviceController.mm (hunk 9 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDeviceController.mm:1179]: Dangerous in what way?  The API contract is that error outparams are _always_ allowed to be nil; the implementation needs to handle that (and does).

Comment (cliffamzn) [reply src/darwin/Framework/CHIP/MTRDeviceController.mm:1179]: i actually missed the part where you were doing a check for the existence of the error var. My bad, please ignore!

File: src/darwin/Framework/CHIP/MTRCSRInfo.h (hunk 2 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRCSRInfo.h:35]: Added an `MTRCSRDERBytes` typedef.

File: src/darwin/Framework/CHIP/MTRCSRInfo.h (hunk 3 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRCSRInfo.h:37]: Done.

File: src/darwin/Framework/CHIP/MTRDeviceController.h (hunk 4 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDeviceController.h:134]: Done.

File: src/darwin/Framework/CHIP/MTROperationalCertificateIssuer.h (hunk 5 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTROperationalCertificateIssuer.h:44]: Done.

File: src/darwin/Framework/CHIP/MTRDeviceController.h (hunk 8 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDeviceController.h]: This API is gone now.

**Review by cliffamzn — APPROVED** [review]

**Review by ksperling-apple — APPROVED** [review]
