### PR TITLE
Don't touch member variables from async dispatch.

### LINKED ISSUE #21453: SubscriptionCallback::ReportData needs to capture its callbacks in block vars.
#### Problem
SubscriptionCallback::ReportData  (in MTRBaseDevice.mm) does this:
```
    if (mAttributeReportCallback && attributeReports.count) {
        dispatch_async(mQueue, ^{
            mAttributeReportCallback(attributeReports);
```

but by the time the async block runs, `mAttributeReportCallback` can have become null, right?  And in general, this is doing racy access to the callback....

We have crashes on that call to mAttributeReportCallback that I bet are due to this.

 #### Proposed Solution
The callback should be getting captured into a block var, like the attributeReports are.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
We were null-checking members, then calling them from an async block,
by which point they might be null.

Fixes https://github.com/project-chip/connectedhomeip/issues/21453

#### Problem
Crashes.

#### Change overview
See above.

#### Testing
Need to do stress-testing to see how this does on the crash stacks we are seeing...

### CODE REVIEW

**Comment by bzbarsky-apple** [comment]
@jtung-apple Please review next week?

**Review by woody-apple — APPROVED** [review]

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 1]
```diff
@@ -1384,16 +1384,20 @@ - (instancetype)initWithPath:(const ConcreteEventPath &)path
...
         dispatch_async(mQueue, ^{
-            mAttributeReportCallback(attributeReports);
+            attributeCallback(attributeReports);
         });
     }
-    if (mEventReportCallback && eventReports.count) {
+    if (eventCallback != nil && eventReports.count) {
         dispatch_async(mQueue, ^{
-            mEventReportCallback(eventReports);
+            eventCallback(eventReports);
```
Comment (woody-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1400]: I think this should check for eventCallback != nil before calling it in here in the dispatch block.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 2]
```diff
@@ -1384,16 +1384,20 @@ - (instancetype)initWithPath:(const ConcreteEventPath &)path
...
+
     __block NSArray * eventReports = mEventReports;
     mEventReports = nil;
-    if (mAttributeReportCallback && attributeReports.count) {
+    __block auto eventCallback = mEventReportCallback;
+
+    if (attributeCallback != nil && attributeReports.count) {
         dispatch_async(mQueue, ^{
-            mAttributeReportCallback(attributeReports);
+            attributeCallback(attributeReports);
```
Comment (woody-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1395]: I think this should check for attributeCallback != nil before calling it in here in the dispatch block.

**Review by woody-apple — APPROVED** [review]

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 2 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1395]: How would it become nil, if we checked it for non-nil before queueing the block, and it's a block variable?

Comment (mrjerryjohns) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1395]: Can't it not become nil if `ReportError` got called after your block got queued for execution, but before your block gets dispatched?

Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1395]: How?  It's a pointer that was on the stack and then was copied into the block.  `mAttributeReportCallback` can become null, which is precisely the thing we are guarding against by not using it inside the block.  But I don't see how `attributeCallback` can.

Or am I just totally mis-understanding how all this works?
