### PR TITLE
Normalize NOC cluster logs

### LINKED ISSUE #18384: Update some logs from INFO to ERROR since they expose actual issues
#### Problem

Errors such as the following are logged as `INFO`:
```
I (52610) chip[ZCL]: OpCreds: Failed AddNOC request. Status 9
```

 #### Proposed Solution
Since these do expose real issues, they should be logged as `ERROR`.

### PR DESCRIPTION
**Pull request by tcarmelveilleux**
#### Problem
- NOC cluster was using Info/Debug verbosity for errors
- NOC cluster was not logging sufficient info for some errors
- NOC cluster had a variety of asymmetrical log formats related
  to multiple authors.
- NOC cluster was using emberAfPrintln() instead of ChipLog*()

Fixes #18384

#### Change overview
This PR cleans up the logging of NOC cluster and normalizes it

#### Testing
- Unit tests and cert tests pass
- Logging audited on a cert test run for funkiness, none found

### CODE REVIEW

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 1]
```diff
@@ -405,11 +408,11 @@ class OpCredsFabricTableDelegate : public chip::FabricTable::Delegate
...
-        emberAfPrintln(EMBER_AF_PRINT_DEBUG,
-                       "OpCreds: Fabric index 0x%x was retrieved from storage. FabricId 0x" ChipLogFormatX64
-                       ", NodeId 0x" ChipLogFormatX64 ", VendorId 0x%04X",
-                       static_cast<unsigned>(fabric->GetFabricIndex()), ChipLogValueX64(fabric->GetFabricId()),
-                       ChipLogValueX64(fabric->GetPeerId().GetNodeId()), fabric->GetVendorId());
+        ChipLogProgress(Zcl,
+                        "OpCreds: Fabric index 0x%x was retrieved from storage. FabricId 0x" ChipLogFormatX64
+                        ", NodeId 0x" ChipLogFormatX64 ", VendorId 0x%04X",
+                        static_cast<unsigned>(fabric->GetFabricIndex()), ChipLogValueX64(fabric->GetFabricId()),
+                        ChipLogValueX64(fabric->GetPeerId().GetNodeId()), fabric->GetVendorId());
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:415]:
```suggestion
                        ChipLogValueX64(fabric->GetNodeId()), fabric->GetVendorId());
```

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 2]
```diff
@@ -420,11 +423,11 @@ class OpCredsFabricTableDelegate : public chip::FabricTable::Delegate
...
-        emberAfPrintln(EMBER_AF_PRINT_DEBUG,
-                       "OpCreds: Fabric  index 0x%x was persisted to storage. FabricId " ChipLogFormatX64
-                       ", NodeId " ChipLogFormatX64 ", VendorId 0x%04X",
-                       static_cast<unsigned>(fabric->GetFabricIndex()), ChipLogValueX64(fabric->GetFabricId()),
-                       ChipLogValueX64(fabric->GetPeerId().GetNodeId()), fabric->GetVendorId());
+        ChipLogProgress(Zcl,
+                        "OpCreds: Fabric  index 0x%x was persisted to storage. FabricId " ChipLogFormatX64
+                        ", NodeId " ChipLogFormatX64 ", VendorId 0x%04X",
+                        static_cast<unsigned>(fabric->GetFabricIndex()), ChipLogValueX64(fabric->GetFabricId()),
+                        ChipLogValueX64(fabric->GetPeerId().GetNodeId()), fabric->GetVendorId());
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:430]:
```suggestion
                        ChipLogValueX64(fabric->GetNodeId()), fabric->GetVendorId());
```

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 3]
```diff
@@ -973,7 +974,13 @@ bool emberAfOperationalCredentialsClusterCSRRequestCallback(app::CommandHandler
...
         err = gFabricBeingCommissioned.GetOperationalKey()->NewCertificateSigningRequest(csr.Get(), csrLength);
-        emberAfPrintln(EMBER_AF_PRINT_DEBUG, "OpCreds: NewCertificateSigningRequest returned %" CHIP_ERROR_FORMAT, err.Format());
+        if (err != CHIP_NO_ERROR)
+        {
+            ChipLogError(Zcl, "OpCreds: NewCertificateSigningRequest returned %" CHIP_ERROR_FORMAT, err.Format());
+            SuccessOrExit(err);
+        }
+        ChipLogProgress(Zcl, "OpCreds: NewCertificateSigningRequest succeeded");
+
         SuccessOrExit(err);
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:984]:
```suggestion
```
since now we have it inside the `if (err != CHIP_NO_ERROR)` block, right?

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp (hunk 1 above)
Comment (tcarmelveilleux) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp]: Done

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp (hunk 3 above)
Comment (tcarmelveilleux) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp]: Done

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 4]
```diff
@@ -433,8 +436,6 @@ OpCredsFabricTableDelegate gFabricDelegate;
 
 void MatterOperationalCredentialsPluginServerInitCallback(void)
 {
-    emberAfPrintln(EMBER_AF_PRINT_DEBUG, "OpCreds: Initiating OpCreds cluster by writing fabrics list from fabric table.");
-
```
Comment (turon) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:437]: Don't want to keep this log line?  It's being deleted instead of replaced with ChipLog format.

**Review by turon — APPROVED** [review]
