### PR TITLE
Fix CurrentPositionLiftPercent100ths attribute read value mismatch

### LINKED ISSUE #22265: [TC-WNCV-3.1] CurrentPositionLiftPercent100ths attribute read value mismatch error
Summary:
As per testplan of WNCV-3.1 in Step 3b: TH reads CurrentPositionLiftPercent100ths  and the expected outcome value must not be 10000 ( 0x2710 ) but got 10000 when executed.
Steps needs review 3b , 3c, 3d, 3e
Client app: All clusters app
Server app: Chip-tool

Diff link: https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:connectedhomeip:CurrentPositionLiftPercent100ths_Value_Mismatch

Testplan screenshot:
image

Execution logs:
[WNCV_3_1.txt](https://github.com/project-chip/connectedhomeip/files/9454170/WNCV_3_1.txt)

### PR DESCRIPTION
**Pull request by yufengwangca**
* Currently, cert Test_TC_WNCV_3_1 and Test_TC_WNCV_3_2 are failed and temporarily disabled. This is because the current mock implementation of movement is one shot and up to the end straight after 5s, but the test requires the value change gradually when window is opened or closed.

* Current mock implementation of window covering movement is done in WindowCovering cluster Server, this is not right, since the cluster server is used in both example app and product. 

#### Issue Being Resolved
* Fixes #22265, #22287

#### Change overview
* Re-enable Test_TC_WNCV_3_1 and Test_TC_WNCV_3_2 
* Make window covering changes gradually when window is opened or closed
* Move the mock implementation from cluster server to example app

Note: similar implementation for WindowApp will be done in a separate PR

### CODE REVIEW

File: examples/all-clusters-app/linux/WindowCoveringManager.h [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+ *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ *    See the License for the specific language governing permissions and
+ *    limitations under the License.
+ */
+
+#pragma once
+
+#include <app/clusters/window-covering-server/window-covering-server.h>
+
+using WindowCoveringDelegate = chip::app::Clusters::WindowCovering::Delegate;
```
Comment (andy31415) [inline examples/all-clusters-app/linux/WindowCoveringManager.h:22]: using statements in headers will polute global namespace. Please scope them inside the class or fully expand them.

File: src/app/clusters/window-covering-server/window-covering-delegate.h [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+namespace Clusters {
+namespace WindowCovering {
+
+/** @brief
+ *    Defines methods for implementing application-specific logic for the WindowCovering Cluster.
+ */
+class Delegate
+{
+public:
+    virtual CHIP_ERROR HandleLiftMovement() = 0;
```
Comment (andy31415) [inline src/app/clusters/window-covering-server/window-covering-delegate.h:37]: These `Handle` need some documentation: what is one supposed to do when `HandleFOO`? when is that method called and what is the expected operation? What does it mean for them to return errors?

File: src/app/clusters/window-covering-server/window-covering-server.cpp [hunk 3]
```diff
@@ -649,6 +593,21 @@ EmberAfStatus GetMotionLockStatus(chip::EndpointId endpoint)
     return EMBER_ZCL_STATUS_SUCCESS;
 }
 
+void SetDefaultDelegate(EndpointId endpoint, Delegate * delegate)
+{
+    uint16_t ep = emberAfFindClusterServerEndpointIndex(endpoint, Channel::Id);
+
+    // if endpoint is found and is not a dynamic endpoint
+    if (ep != 0xFFFF && ep < EMBER_AF_WINDOW_COVERING_CLUSTER_SERVER_ENDPOINT_COUNT)
```
Comment (andy31415) [inline src/app/clusters/window-covering-server/window-covering-server.cpp:601]: is there a constant name we could define for 0xFFFF? It would be easier to read if it was called something like `kInvalidEndpointId` or similar.

File: src/app/clusters/window-covering-server/window-covering-server.cpp [hunk 4]
```diff
@@ -697,7 +643,26 @@ bool emberAfWindowCoveringClusterUpOrOpenCallback(app::CommandHandler * commandO
     {
         Attributes::TargetPositionTiltPercent100ths::Set(endpoint, WC_PERCENT100THS_MIN_OPEN);
     }
+
+    Delegate * delegate = GetDelegate(endpoint);
+    if (delegate)
+    {
+        if (HasFeature(endpoint, Feature::kPositionAwareLift))
+        {
+            LogErrorOnFailure(delegate->HandleLiftMovement());
```
Comment (andy31415) [inline src/app/clusters/window-covering-server/window-covering-server.cpp:652]: The ember callbacks seem to know if Up/Open or Down/Close is called, yet the handle callbacks only say "movement/tilt".

Why the split? Also why is there an ordering of features: if you only are position aware you get 'Lift' and otherwise if you have tilt you get 'tilt' callback. What if you have both features?

Have we considered passing in arguments into the delegate instead (like up/down constants)? Why would the delegate not have a single callback instead of separate lift/tilt?

File: examples/all-clusters-app/linux/WindowCoveringManager.h (hunk 1 above)
Comment (yufengwangca) [reply examples/all-clusters-app/linux/WindowCoveringManager.h]: Acked

File: src/app/clusters/window-covering-server/window-covering-server.cpp (hunk 4 above)
Comment (yufengwangca) [reply src/app/clusters/window-covering-server/window-covering-server.cpp]: Yes, we can merge these two methods with passing argument.

According to spec, when we adjust the lift position, the tilt position should also be adjusted accordingly if Tilt feature is supported. If we have both features supported, we only need to adjust one type of position, so method HandleMovement should only be called only once.

**Review by andy31415 — APPROVED** [review]

File: src/app/clusters/window-covering-server/window-covering-server.cpp [hunk 5]
```diff
@@ -697,7 +644,26 @@ bool emberAfWindowCoveringClusterUpOrOpenCallback(app::CommandHandler * commandO
...
     }
+
+    Delegate * delegate = GetDelegate(endpoint);
+    if (delegate)
+    {
+        if (HasFeature(endpoint, Feature::kPositionAwareLift))
+        {
+            LogErrorOnFailure(delegate->HandleMovement(WindowCoveringType::Lift));
+        }
+        else if (HasFeature(endpoint, Feature::kPositionAwareTilt))
```
Comment (andy31415) [inline src/app/clusters/window-covering-server/window-covering-server.cpp:655]: why is there an else here?

What if both features exist? Should we not be passing a set of what movement to handle or is the spec saying that only one of lift or tilt features have to exist?

Comment (andy31415) [reply src/app/clusters/window-covering-server/window-covering-server.cpp:655]: Spec seems to say "*At least one of the Lift and Tilt features SHALL be supported." but I cannot find any text that says they are mutually exclusive.

But logically it does seem like they may be exclusive. Maybe just a comment suffices saying that the SDK expects only one of the features being set.

I think we can add the comment as a followup (or change to bit flags)

**Review by andy31415 — APPROVED** [review]

File: src/app/clusters/window-covering-server/window-covering-server.cpp (hunk 5 above)
Comment (jmeg-sfy) [reply src/app/clusters/window-covering-server/window-covering-server.cpp:655]: no there are not exclusive , must have at least one or both but cannot have none

File: examples/all-clusters-app/linux/WindowCoveringManager.cpp [hunk 6]
```diff
@@ -0,0 +1,138 @@
...
+    VerifyOrReturn(manager->mState != OperationalState::Stall);
+
+    uint16_t currentPosition = manager->mCurrentPosition.Value();
+    uint16_t targetPosition  = manager->mTargetPosition.Value();
+
+    ChipLogProgress(NotSpecified, "HandleMovementTimer:currentPosition:%u, targetPosition:%u", currentPosition, targetPosition);
+
+    if (OperationalState::MovingUpOrOpen == manager->mState)
+    {
+        if (currentPosition > targetPosition)
```
Comment (jmeg-sfy) [inline examples/all-clusters-app/linux/WindowCoveringManager.cpp:56]: there is a function to compare already available i would have prefer keeping using it

**Review by jmeg-sfy — COMMENTED** [review]
Thanks for the PR i didn't have time to review it before today

File: src/app/clusters/window-covering-server/window-covering-server.cpp [hunk 7]
```diff
@@ -728,6 +694,24 @@ bool emberAfWindowCoveringClusterDownOrCloseCallback(app::CommandHandler * comma
...
     emberAfSendImmediateDefaultResponse(EMBER_ZCL_STATUS_SUCCESS);
+
+    Delegate * delegate = GetDelegate(endpoint);
+    if (delegate)
+    {
+        if (HasFeature(endpoint, Feature::kPositionAwareLift))
+        {
+            LogErrorOnFailure(delegate->HandleMovement(WindowCoveringType::Lift));
+        }
+        else if (HasFeature(endpoint, Feature::kPositionAwareTilt))
```
Comment (jmeg-sfy) [inline src/app/clusters/window-covering-server/window-covering-server.cpp:705]: This is incorrect we can have both at the same time

File: src/app/clusters/window-covering-server/window-covering-server.cpp (hunk 5 above)
Comment (jmeg-sfy) [reply src/app/clusters/window-covering-server/window-covering-server.cpp:655]: This is incorrect we must have both running at the same time

File: src/app/clusters/window-covering-server/window-covering-server.cpp [hunk 8]
```diff
@@ -658,19 +618,6 @@ EmberAfStatus GetMotionLockStatus(chip::EndpointId endpoint)
...
- *
- * Cluster Init
- *
- * @param endpoint    Endpoint that is being initialized
- */
-void emberAfWindowCoveringClusterInitCallback(chip::EndpointId endpoint)
-{
-    emberAfWindowCoveringClusterPrint("Window Covering Cluster init");
-
-    ConfigStatusUpdateFeatures(endpoint);
```
Comment (jmeg-sfy) [inline src/app/clusters/window-covering-server/window-covering-server.cpp:671]: Where did this go ?

Comment (jmeg-sfy) [inline src/app/clusters/window-covering-server/window-covering-server.cpp:671]: Where did this go ?

**Review by jmeg-sfy — COMMENTED** [review]
There is a mistake to fix

File: src/app/clusters/window-covering-server/window-covering-server.cpp (hunk 7 above)
Comment (yufengwangca) [reply src/app/clusters/window-covering-server/window-covering-server.cpp:705]: Yes, we could have both, but the spec say when we adjust the position for lift we should also adjust the position for tilt accordingly, same to the other way,  so if both of them are supported, we only need to change one of them

File: examples/all-clusters-app/linux/WindowCoveringManager.cpp (hunk 6 above)
Comment (yufengwangca) [reply examples/all-clusters-app/linux/WindowCoveringManager.cpp:56]: ack

File: src/app/clusters/window-covering-server/window-covering-server.cpp (hunk 7 above)
Comment (yufengwangca) [reply src/app/clusters/window-covering-server/window-covering-server.cpp:705]: Ack, UpOrOpen/DownOrClose/StopMotion commands will impact both actuator at the same time, and other commands will only adjust one of them

**Comment by yufengwangca** [comment]
@jmeg-sfy https://github.com/project-chip/connectedhomeip/pull/22733
