### PR TITLE
Replaced the use of std::set with IntrusiveList in ModeBase.

### LINKED ISSUE #28125: [1.2] Remove the use of set in the Mode Base server code
### Reproduction steps

n/a

### Bug prevalence

not a bug

### GitHub hash of the SDK that was being used

3d63a734

### Platform

other

### Platform Version(s)

1.2

### Type

Common Cluster Logic

### Anything else?

The use of `std::set` is not compatible with embedded platforms. This needs to be replaced with an embedded friendly implementation. Consider the SDK`s doubly linked list implementation, `IntrusiveList`.

- Replace the use of `std::set` with `IntrusiveList`.
- Remove the exeption to use `std::set` from `scripts/tools/check_includes_config.py`

### PR DESCRIPTION
**Pull request by hicklin**
Fixes #28125 Replaces the use of `std::set` with `IntrusiveList`.

### CODE REVIEW

File: src/app/clusters/mode-base-server/mode-base-server.cpp [hunk 1]
```diff
@@ -38,6 +38,22 @@ namespace app {
...
+    {
+        gModeBaseAliasesInstances.PushBack(instance);
+    }
+}
+
+void Instance::UnregisterInstance(Instance * instance)
+{
+    if (gModeBaseAliasesInstances.Contains(instance))
+    {
+        gModeBaseAliasesInstances.Remove(instance);
```
Comment (bzbarsky-apple) [inline src/app/clusters/mode-base-server/mode-base-server.cpp:53]: I think Remove() is safe to call even if the instance is not in the list, and that will save the work of checking whether it is....

File: src/app/clusters/mode-base-server/mode-base-server.cpp [hunk 2]
```diff
@@ -476,14 +491,14 @@ Instance::Instance(Delegate * aDelegate, EndpointId aEndpointId, ClusterId aClus
 
 Instance::~Instance()
 {
-    ModeBaseAliasesInstances.erase(this);
+    UnregisterInstance(this);
```
Comment (bzbarsky-apple) [inline src/app/clusters/mode-base-server/mode-base-server.cpp:494]: If the instances are static, and the list itself is static, what guarantees the destructors of the instances will run before the list destructor?  The latter will crash if the list is not empty.. and in fact I think some of the CI failures on this PR are precisely that.

Should we have a Shutdown() on Instance that applications are responsible for calling?

File: src/app/clusters/mode-base-server/mode-base-server.cpp [hunk 3]
```diff
@@ -476,14 +491,14 @@ Instance::Instance(Delegate * aDelegate, EndpointId aEndpointId, ClusterId aClus
...
     chip::app::InteractionModelEngine::GetInstance()->UnregisterCommandHandler(this);
     unregisterAttributeAccessOverride(this);
 }
 
-std::set<Instance *> * GetModeBaseInstances()
+IntrusiveList<Instance> & GetModeBaseInstanceList()
```
Comment (bzbarsky-apple) [inline src/app/clusters/mode-base-server/mode-base-server.cpp:499]: Should this be returning `const IntrusiveList<Instance> &`?  Do we expect consumers to modify the list?  I'd guess no.

File: src/app/clusters/mode-base-server/mode-base-server.h [hunk 4]
```diff
@@ -55,6 +55,18 @@ class Instance : public CommandHandlerInterface, public AttributeAccessInterface
     CHIP_ERROR Read(const ConcreteReadAttributePath & aPath, AttributeValueEncoder & aEncoder) override;
     CHIP_ERROR Write(const ConcreteDataAttributePath & aPath, AttributeValueDecoder & aDecoder) override;
 
+    /**
+     * Register a ModeBase instance.
+     * @param instance The instance to register.
+     */
+    void RegisterInstance(Instance * instance);
```
Comment (bzbarsky-apple) [inline src/app/clusters/mode-base-server/mode-base-server.h:62]: Should this and UnregisterInstance be static methods?  Alternately, should they me member methods but then just use `this` instead of taking the instance as an argument?

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/clusters/mode-base-server/mode-base-server.h (hunk 4 above)
Comment (hicklin) [reply src/app/clusters/mode-base-server/mode-base-server.h:62]: I prefer the latter since these are private functions. Implemented.

File: src/app/clusters/mode-base-server/mode-base-server.cpp (hunk 1 above)
Comment (hicklin) [reply src/app/clusters/mode-base-server/mode-base-server.cpp:53]: OK, I removed the check.

File: src/app/clusters/mode-base-server/mode-base-server.cpp (hunk 3 above)
Comment (hicklin) [reply src/app/clusters/mode-base-server/mode-base-server.cpp:499]: I did try this but for some reason, when the OnOff server tries to do a for loop on the contents of the `IntrusiveList`, the elements it returns are also const and therefore it cannot use the `UpdateXxx` functions, which is required.

File: src/app/clusters/mode-base-server/mode-base-server.cpp (hunk 2 above)
Comment (hicklin) [reply src/app/clusters/mode-base-server/mode-base-server.cpp:494]: Is there an emberAf shutdown callback function where the user can call this shutdown command?

Static objects should be deconstructed in the reverse order that they where constructed so it shouldn't be an issue since the list should be constructed before the Instances. 

The problem is that the instances in the examples are created on the heap. So they are never deconstructed. We need the application to destroy these objects at shutdown.

Comment (bzbarsky-apple) [reply src/app/clusters/mode-base-server/mode-base-server.cpp]: > Is there an emberAf shutdown callback function where the user can call this shutdown command?

Shutdown happens under application control to start with, right?  Apps call Server::Shutdown.  So they could clean up before doing that?  Or we could do it in Server::Shutdown itself, perhaps.

> Static objects should be deconstructed in the reverse order that they where constructed

Yes.

> so it shouldn't be an issue since the list should be constructed before the Instances.

Absolutely nothing guarantees this, right?  The list is in one translation unit.  The instances are in another.  Their static constructors do not have a defined ordering.

File: src/app/clusters/mode-base-server/mode-base-server.cpp (hunk 3 above)
Comment (bzbarsky-apple) [reply src/app/clusters/mode-base-server/mode-base-server.cpp:496]: Please document that.

Containers and const on a container means all the things in it are also const are annoying...

Comment (hicklin) [reply src/app/clusters/mode-base-server/mode-base-server.cpp:496]: I added this comment above the getter `// This does not return a const of gModeBaseAliasesInstances since the caller might need to call the element's UpdateXxx methods.`.

File: src/app/clusters/mode-base-server/mode-base-server.cpp (hunk 2 above)
Comment (hicklin) [reply src/app/clusters/mode-base-server/mode-base-server.cpp]: In the Linux all-clusters-app, I moved the `AppicationExit()` call to the `ChipLinuxAppMainLoop()` so it can be called before `Server::Shutdown()`. This makes more sense as this Init and Exit pair is called in reverse order with all the other init and de-init methods.

The `AppicationExit()` method calls shutdown methods for all the delegates. These destroy the instance then the delegate. The changes are in [this commit](https://github.com/project-chip/connectedhomeip/pull/28163/commits/d9cab5435caa03b833cc02ca9f005006d68f0321).

File: examples/all-clusters-app/all-clusters-common/src/dishwasher-mode.cpp [hunk 5]
```diff
@@ -76,12 +76,23 @@ CHIP_ERROR DishwasherModeDelegate::GetModeTagsByIndex(uint8_t modeIndex, List<Mo
     return CHIP_NO_ERROR;
 }
 
+void DishwasherMode::Shutdown()
+{
+    if (gDishwasherModeInstance != nullptr)
+    {
+        gDishwasherModeInstance->~Instance();
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/all-clusters-common/src/dishwasher-mode.cpp:83]: Please make this symmetric with the allocator.  So:
```suggestion
        delete gDishwasherModeInstance;
        gDishwasherModeInstance = nullptr;
```
This will (1) properly free the memory and (2) be safe if Shutdown is called twice (e.g. after a second failed init or something).  Similar elsewhere.

File: examples/all-clusters-app/linux/main-common.cpp [hunk 6]
```diff
@@ -193,6 +192,13 @@ void ApplicationInit()
 
 void ApplicationExit()
 {
+    // These have been initialised via the emberAfXxxClusterInitCallback methods. We need to destroy them before shutdown.
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/linux/main-common.cpp:195]:
```suggestion
    // These may have been initialised via the emberAfXxxClusterInitCallback methods. We need to destroy them before shutdown.
```

File: examples/platform/linux/AppMain.h [hunk 7]
```diff
@@ -103,3 +103,6 @@ CommissionerDiscoveryController * GetCommissionerDiscoveryController();
 
 // For extra init calls, the function will be called right before running Matter main loop.
 void ApplicationInit();
+
+// For extra teardown calls, the function will be called right after running Matter main loop.
+void ApplicationExit();
```
Comment (bzbarsky-apple) [inline examples/platform/linux/AppMain.h:108]: This should be called ApplicationShutdown, to make it clear that it's a parallel to ApplicationInit.  And document, perhaps, that it will be called before any of the core Matter objects are shut down?

File: src/app/clusters/mode-base-server/mode-base-server.h [hunk 8]
```diff
@@ -229,9 +239,10 @@ class Delegate
 
 // A set of pointers to all initialised ModeBase instances. It provides a way to access all ModeBase derived clusters.
 // todo change once there is a clear public interface for the OnOff cluster data dependencies (#27508)
-static std::set<Instance *> ModeBaseAliasesInstances;
+static IntrusiveList<Instance> gModeBaseAliasesInstances;
 
-std::set<Instance *> * GetModeBaseInstances();
+// This does not return a const of gModeBaseAliasesInstances since the caller might need to call the element's UpdateXxx methods.
```
Comment (bzbarsky-apple) [inline src/app/clusters/mode-base-server/mode-base-server.h:244]:
```suggestion
// This does not return a refernce to const IntrusiveList, because the caller might need
// to change the state of the instances in the list and const IntrusiveList only allows
// access to const Instance.
```

**Review by bzbarsky-apple — APPROVED** [review]

File: examples/all-clusters-app/all-clusters-common/src/dishwasher-mode.cpp (hunk 5 above)
Comment (hicklin) [reply examples/all-clusters-app/all-clusters-common/src/dishwasher-mode.cpp]: Done.

File: examples/platform/linux/AppMain.h (hunk 7 above)
Comment (hicklin) [reply examples/platform/linux/AppMain.h]: Done.

**Review by p0fi — APPROVED** [review]

File: examples/all-clusters-app/all-clusters-common/src/dishwasher-mode.cpp [hunk 9]
```diff
@@ -76,12 +76,24 @@ CHIP_ERROR DishwasherModeDelegate::GetModeTagsByIndex(uint8_t modeIndex, List<Mo
...
+void DishwasherMode::Shutdown()
+{
+    if (gDishwasherModeInstance != nullptr)
+    {
+        delete gDishwasherModeInstance;
+        gDishwasherModeInstance = nullptr;
+    }
+    if (gDishwasherModeDelegate != nullptr)
+    {
+        gDishwasherModeDelegate->~DishwasherModeDelegate();
```
Comment (tcarmelveilleux) [inline examples/all-clusters-app/all-clusters-common/src/dishwasher-mode.cpp:88]: Why is destructor explicitly called here?

Comment (bzbarsky-apple) [reply examples/all-clusters-app/all-clusters-common/src/dishwasher-mode.cpp:88]: @hicklin This is .. strange.  This was one of my review comments, which was not addressed.  See https://github.com/project-chip/connectedhomeip/pull/28163#discussion_r1272573621 the "similar elsewhere" bit!

Comment (hicklin) [reply examples/all-clusters-app/all-clusters-common/src/dishwasher-mode.cpp:88]: Sorry about that. For some reason I didn't clock the delegate and only did this for the instance. I have issued a [bug](https://github.com/project-chip/connectedhomeip/issues/28265) and will be submitting a PR that fixes it soon.

File: src/app/clusters/mode-base-server/mode-base-server.h [hunk 10]
```diff
@@ -229,9 +239,12 @@ class Delegate
 
 // A set of pointers to all initialised ModeBase instances. It provides a way to access all ModeBase derived clusters.
 // todo change once there is a clear public interface for the OnOff cluster data dependencies (#27508)
-static std::set<Instance *> ModeBaseAliasesInstances;
+static IntrusiveList<Instance> gModeBaseAliasesInstances;
 
-std::set<Instance *> * GetModeBaseInstances();
+// This does not return a refernce to const IntrusiveList, because the caller might need
```
[the remark this answers is not in the document]
Comment (hicklin) [reply src/app/clusters/mode-base-server/mode-base-server.h:244]: Thanks. Will be fixed in a new PR.
