### PR TITLE
Fix the ReadClient destructor to call OnDeallocatePaths.

### LINKED ISSUE #21658: Make ReadClient destructor clean up properly.
#### Problem
Just destroying a ReadClient (e.g. from a subscription) does not handle cleaning up properly.  In particular, for a subscription that does resubscribes it does not clean up the paths.

 #### Proposed Solution
Fix things to work correctly.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
This is actually somewhat dangerous, because there is a good chance ~ReadClient
is running from under the destructor of the ReadClient::Callback and we are
invoking a virtual method on the callback.  But this is the only way to ensure
we don't leak.  ReadClient::Callback implementations need to be able to handle
this.

Fixes https://github.com/project-chip/connectedhomeip/issues/21658

#### Problem
We never call OnDeallocatePaths if a ReadClient with auto-resubscribe is destroyed.

#### Change overview
Call it.

#### Testing
```
LSAN_OPTIONS="detect_leaks=1" chip-tool interactive start
```
and at the interactive prompt run:
```
basic subscribe data-model-revision 1 100 17 0 --auto-resubscribe true

quit()
```

Without this PR it shows path leaks.

### CODE REVIEW

File: src/app/ReadClient.cpp [hunk 1]
```diff
@@ -68,20 +68,29 @@ void ReadClient::ClearActiveSubscriptionState()
...
+        mReadPrepareParams.mpEventPathParamsList        = nullptr;
+        mReadPrepareParams.mEventPathParamsListSize     = 0;
+        mReadPrepareParams.mpDataVersionFilterList      = nullptr;
+        mReadPrepareParams.mDataVersionFilterListSize   = 0;
+    }
 }
 
 ReadClient::~ReadClient()
 {
+    Close(CHIP_NO_ERROR, /* allowResubscription = */ false, /* allowOnDone = */ false);
```
Comment (mrjerryjohns) [inline src/app/ReadClient.cpp:91]: Calling `Close` here is a bit odd. If we arrived at the destructor here as a side-effect of a previous `Close`, it's going to call it twice. That isn't in theory, a problem per say, but I tend to think we should avoid such double calls if we can in the design here if possible.

The only thing you really need out of this `Close` is the call to `StopResubscription` really. So, why not move `StopSubscription` exclusively into the destructor, and then avoid this call entirely?

File: src/app/tests/TestReadInteraction.cpp [hunk 2]
```diff
@@ -1748,6 +1748,7 @@ void TestReadInteraction::TestSubscribeWildcard(nlTestSuite * apSuite, void * ap
 
         delegate.mGotReport = false;
 
+        attributePathParams.release();
         err = readClient.SendAutoResubscribeRequest(std::move(readPrepareParams));
```
Comment (mrjerryjohns) [inline src/app/tests/TestReadInteraction.cpp:1752]: Our usual policy has been that until this call succeeds, the onus to free the client object is on the caller. It seems like de-allocation of paths doesn't quite line up that way, and the logic within `SendAutoResubscribeRequest` takes responsibility for calling you to free up the params. I realize this is existing code, but perhaps we line those up?

File: src/app/ReadClient.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/ReadClient.cpp:91]: > The only thing you really need out of this Close is the call to StopResubscription really. So, why not move StopSubscription exclusively into the destructor, and then avoid this call entirely?

I actually went back and forth about this some: if we add more logic to Close() it's easy to forget to do it in the destructor....  But yes, that is a much smaller and simpler change and I can absolutely do that.

File: src/app/tests/TestReadInteraction.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/app/tests/TestReadInteraction.cpp:1752]: The reason it works like it does is that once you call `std::move` on something you're not really supposed to assume things about its state.  Any cleanup should really be done by the callee at that point....

Comment (mrjerryjohns) [reply src/app/tests/TestReadInteraction.cpp:1752]: Why not `std::move` it back if any errors happen within `SendAutoResubscribeRequest`?

Comment (bzbarsky-apple) [reply src/app/tests/TestReadInteraction.cpp:1752]: > Why not std::move it back if any errors happen within SendAutoResubscribeRequest?

We could, but again that's not how APIs that take rvalue references normally work in C++.  Normally if you take an rvalue reference it's on you to clean things up correctly.

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking given this has had enough time for review.

File: src/app/ReadClient.cpp (hunk 1 above)
Comment (mrjerryjohns) [reply src/app/ReadClient.cpp:91]: This was merged without resolving this. Please fix this in a subsequent PR.

Comment (bzbarsky-apple) [reply src/app/ReadClient.cpp:91]: https://github.com/project-chip/connectedhomeip/issues/22352 and https://github.com/project-chip/connectedhomeip/pull/22353
