### PR TITLE
[Darwin] MTRDevice should log better

### LINKED ISSUE #23621: [Darwin] MTRDevice should log better
### Reproduction steps

```bash
For debugging, when MTRDevice filters incoming reports or read callbacks (because values did not change), a log should be generated about it.
```

Edit: on top of the above, also improve overall logging for this class.

### Platform

darwin

### Platform Version(s)

1.0

### Type

Platform validated

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jtung-apple**
Fixes #23621 

This adds some logging, and also fixes a bug when the MTRAsyncCallbackWorkQueue is drained.

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRAsyncCallbackWorkQueue.mm [hunk 1]
```diff
@@ -80,6 +87,8 @@ - (void)invalidate
     _items = nil;
     os_unfair_lock_unlock(&_lock);
 
+    MTR_LOG_INFO(
+        "MTRAsyncCallbackWorkQueue invalidate for context %@items count: %lu", _context, (unsigned long) invalidateItems.count);
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRAsyncCallbackWorkQueue.mm:91]:
```suggestion
        "MTRAsyncCallbackWorkQueue invalidate for context %@ items count: %lu", _context, (unsigned long) invalidateItems.count);
```

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 2]
```diff
@@ -669,23 +690,32 @@ - (NSArray *)_getAttributesToReportWithReportedValues:(NSArray<NSDictionary<NSSt
...
                 if (![self _attributeDataValue:attributeDataValue isEqualToDataValue:expectedValue.second]) {
                     shouldReportAttribute = YES;
                 }
                 _expectedValueCache[attributePath] = nil;
-            }
-
-            // then compare and update read cache
-            if (![self _attributeDataValue:attributeDataValue isEqualToDataValue:_readCache[attributePath]]) {
+                _readCache[attributePath] = attributeDataValue;
+            } else if (![self _attributeDataValue:attributeDataValue isEqualToDataValue:_readCache[attributePath]]) {
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:706]: I'd think we want to update `_readCache` no matter what the state of `_expectedValueCache` was here...

That is, I think the logic should be:

1. Report if we have an expected value and it does not match, or if we have no expected value and the read cache value does not match.
2. Clear out the expected value cache if there is a value there.
3. Update the read cache.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 2 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:706]: Ah, I missed the `_readCache[attributePath] = attributeDataValue;` bit in the `expectedValue` path. So this part is all good.

**Comment by bzbarsky-apple** [comment]
Fast-tracking platform-specific fix with platform owner review.
