### PR TITLE
[Silabs] Refactor Bluetooth implementation to use SLC structure

### LINKED ISSUE #22876: [Silabs] Bluetooth implementation is not inline with latest silabs structure
### Reproduction steps

```bash
No steps to reproduce. This is a refactor to latest structure.
```

### Platform

efr32

### Platform Version(s)

N/A

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mkardous-silabs**
#### Issue Being Resolved
* Fixes #22876 

#### Change overview
- Refactor Bluetooth implementation to use gecko sdk task management.
- Delete all task creation and only implement ble task event processing callback

### CODE REVIEW

File: src/platform/EFR32/EFR32Config.cpp [hunk 1]
```diff
@@ -533,3 +534,90 @@ void EFR32Config::RepackNvm3Flash(void)
 } // namespace Internal
 } // namespace DeviceLayer
 } // namespace chip
+
+extern "C" {
```
Comment (jmartinez-silabs) [inline src/platform/EFR32/EFR32Config.cpp:538]: not sure if this is the right location to have moved those. but other than this it lgtm

**Review by jmartinez-silabs — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
