### PR TITLE
[Darwin] Track last commissioining stage for metrics

### LINKED ISSUE #40009: [Darwin] Setup metrics not tracking last commissioning stage completed
### Reproduction steps

Commission a Matter device and on Darwin platform the commissioning stage completed is always kCleanup and not the last failed or successful one

### Platform

darwin

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by anush-apple**
#### Readability checklist

The checklist below will help the reviewer finish PR review in time and keep the
code readable:

-   [x] PR title is
        [descriptive](https://project-chip.github.io/connectedhomeip-doc/pull_request_guidelines.html#title-formatting)
-   [x] Apply the
        [_“When in Rome…”_](https://project-chip.github.io/connectedhomeip-doc/style/CODING_STYLE_GUIDE.html)
        rule (coding style)
-   [x] PR size is short
-   [x] Try to avoid "squashing" and "force-update" in commit history
-   [ ] CI time didn't increase

See: [Pull Request Guidelines](https://project-chip.github.io/connectedhomeip-doc/pull_request_guidelines.html)

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRMetricsCollector.mm [hunk 1]
```diff
@@ -242,7 +243,13 @@ - (void)handleMetricEvent:(MetricEvent)event
 
     // Add to the collection only if it does not exist as yet or pick latest value for instant event
     if (![_metricsDataCollection valueForKey:metricsKey] || event.type() == MetricEvent::Type::kInstantEvent) {
-        [_metricsDataCollection setValue:data forKey:metricsKey];
+        static const size_t kStagingStringLength(strlen(chip::Tracing::kMetricDeviceCommissionerCommissionStage));
+
+        // If this is the commissioning staging event, skip the cleanup to track the last stage completed in case of error
+        // For all other events, just capture the value
+        if (strncmp(event.key(), chip::Tracing::kMetricDeviceCommissionerCommissionStage, kStagingStringLength) != 0 || event.ValueUInt32() != chip::Controller::CommissioningStage::kCleanup) {
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRMetricsCollector.mm]: This strncmp will test true for any string that starts with kMetricDeviceCommissionerCommissionStage, right?  Is that the intent? 

If that's not the intent, why are we using strncmp here at all?

Comment (anush-apple) [reply src/darwin/Framework/CHIP/MTRMetricsCollector.mm]: Opps, forgot to change that. Will resolve

**Comment by kiel-apple** [comment]
CI didn't pass on first try due to #40132

**Review by bzbarsky-apple — APPROVED** [review]
