### PR TITLE
Door lock fixes for testing

### LINKED ISSUE #16606: Door Lock cluster attributes missing
Summary:
               As per test-plan need to read and write attribute "UserCodeTemporaryDisableTime" "NumberOfHolidaySchedulesSupported" and "RequirePINforRemoteOperation"
showing attribute missing when we executed.

Spec screenshot:
image
image

Execution screenshot and logs:
RewPINRP
[RequirePINforRemoteOperation.txt](https://github.com/project-chip/connectedhomeip/files/8339839/RequirePINforRemoteOperation.txt)

### LINKED ISSUE #16656: [TC-DL-1.13] SetUser Command is showing Failure Response
Configured SetUser Comamnd Argument fields as per testplan but getting Failure response in yaml

TestPlan Screenshot:

Spec Screenshot:

Teststep Screenshot:

[DL-1-13.zip](https://github.com/project-chip/connectedhomeip/files/8348230/DL-1-13.zip)
Error Scrrenshot:

### LINKED ISSUE #16672: [TC-DL-1.8] SetWeekDaySchedule command is giving Failure Response
Configured all the Arguments and values in SetWeekDaySchedule command as per testplan but getting Failure reponse in yaml 

Testplan Screenshot:

Spec Screenshot:

TestStep Screenshot:

Error Screenshot:

[DL-1-8-Execution-logs.zip](https://github.com/project-chip/connectedhomeip/files/8351269/DL-1-8-Execution-logs.zip)

### LINKED ISSUE #16702: "LockDoor" commands showing success response expected Failure response
Summary:
                As per testplan TH sends "LockDoor" Command to the DUT without any argument PINCode ,expected outcome is failure response but when we executed got success response.

Testplan screenshot:
image

Spec screenshot: 
image

Yaml screenshot:
image

Execution screenshot and logs:
image
[PIncode_without_args.txt](https://github.com/project-chip/connectedhomeip/files/8360475/PIncode_without_args.txt)

### LINKED ISSUE #16716: unlockwithTimeout command failing when executed
Summary:
              unlockwithTimeout command showing failure response instead of success response when executed.

Spec screenhot:
image

Execution screenshot and logs: 
image
[unlockwithTimeout_command.txt](https://github.com/project-chip/connectedhomeip/files/8362806/unlockwithTimeout_command.txt)

### LINKED ISSUE #16810: "SetYearDaySchedule" command showing failure response
Summary:
              SetYearDaySchedule command showing failure response when executed but expected outcome is success response.

Spec screenshot:
image

Execution log and screenshot:
image
[SetYearDaySchedule.txt](https://github.com/project-chip/connectedhomeip/files/8376946/SetYearDaySchedule.txt)

### PR DESCRIPTION
**Pull request by krypton36**
#### Problem
* Fixes Door Lock issues for testing.
* Fixes #16606
* Fixes #16810 
* Fixes #16716 
* Fixes #16702 
* Fixes #16672 
* Fixes #16656 

#### Change overview
- Updated Zap files to include the missing clusters and attributes.
- Updated Unlock and Lock behavior to not accept unlocks or locks if pin is not correct. See issue #16702 

#### Testing
- Obtained the YAMLs having issues
- Generated code
- Compiled
- Ran the YAML tests agains the all-clusters-app.

### CODE REVIEW

File: examples/door-lock-app/linux/src/LockEndpoint.cpp [hunk 1]
```diff
@@ -287,19 +287,11 @@ DlStatus LockEndpoint::SetSchedule(uint8_t yearDayIndex, uint16_t userIndex, DlS
...
-    {
-        ChipLogDetail(Zcl, "Door Lock App: door is already locked, ignoring command to set lock state to \"%s\" [endpointId=%d]",
-                      lockStateToString(lockState), mEndpointId);
-        return true;
-    }
-
     if (!pin.HasValue())
     {
-        ChipLogDetail(Zcl, "Door Lock App: PIN code is not specified, setting door lock state to \"%s\" [endpointId=%d]",
+        ChipLogDetail(Zcl, "Door Lock App: PIN code is not specified, not setting door lock state to \"%s\" [endpointId=%d]",
```
Comment (bzbarsky-apple) [inline examples/door-lock-app/linux/src/LockEndpoint.cpp:292]: Why this change?  If a PIN is not specified, then it's not supposed to be checked, but the operation still carried out, no?

Comment (krypton36) [reply examples/door-lock-app/linux/src/LockEndpoint.cpp:292]: Yes, you are correct. If there is no PIN passed, and RequirePINforRemoteOperation is set to true, at the server level, it will return kInvalidCredential, but if RequirePINforRemoteOperation is false and No PIN is provided, then the server calls this function with no PIN. Good catch! Thank you!

**Comment by krypton36** [comment]
@dustin-crossman Can you please take a look at this PR?

**Comment by raju-apple** [comment]
@Morozov-5F @truebiker Can you guys review this PR please ?

**Review by Morozov-5F — APPROVED** [review]
Thanks! Everything looks good, no notes from my side.

**Review by bzbarsky-apple — APPROVED** [review]
