### PR TITLE
[nrfconnect] Fixed window covering bug in updating cluster attributes

### LINKED ISSUE #18371: [SQA]-THREAD ConfigStatus Attribute value is remains same (Unchanged).
**Problem:**
In TC-WNCV-2.3,As per the test plan if the Write command for mode is passed. The  ConfigStatus value has to changed . B ut it remains the same value . 
If the mode value is 2 then the down-or-close command should fail. But it passes in the thread setup after the successful execution  of write command of mode by value 2.

**Expected behavior:**- Failure (0x01)

**Actual behavior:**-  Success (0x00)

**Steps to reproduce**: `./chip-tool windowcovering down-or-close 1 1`

**Platform :** Thread

**Commit-ID:** https://github.com/project-chip/connectedhomeip/commit/11587f5bf0bb9e621edd4c867c0bc942d804d1ce

**Reference:**  [Test-plan](https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/window_covering.adoc)

**Logs:** 

> [1652356270.423328][31321:31326] CHIP:EM: Removed CHIP MessageCounter:10282731 from RetransTable on exchange 46952i
[1652356270.423399][31321:31326] CHIP:DMG: ICR moving to [ResponseRe]
[1652356270.423499][31321:31326] CHIP:DMG: InvokeResponseMessage =
[1652356270.423557][31321:31326] CHIP:DMG: {
[1652356270.423614][31321:31326] CHIP:DMG: 	suppressResponse = false, 
[1652356270.423725][31321:31326] CHIP:DMG: 	InvokeResponseIBs =
[1652356270.423805][31321:31326] CHIP:DMG: 	[
[1652356270.423864][31321:31326] CHIP:DMG: 		InvokeResponseIB =
[1652356270.423948][31321:31326] CHIP:DMG: 		{
[1652356270.424011][31321:31326] CHIP:DMG: 			CommandStatusIB =
[1652356270.424084][31321:31326] CHIP:DMG: 			{
[1652356270.424157][31321:31326] CHIP:DMG: 				CommandPathIB =
[1652356270.424237][31321:31326] CHIP:DMG: 				{
[1652356270.424317][31321:31326] CHIP:DMG: 					EndpointId = 0x1,
[1652356270.424404][31321:31326] CHIP:DMG: 					ClusterId = 0x102,
[1652356270.424487][31321:31326] CHIP:DMG: 					CommandId = 0x1,
[1652356270.424567][31321:31326] CHIP:DMG: 				},
[1652356270.424656][31321:31326] CHIP:DMG: 				
[1652356270.424729][31321:31326] CHIP:DMG: 				StatusIB =
[1652356270.424810][31321:31326] CHIP:DMG: 				{
[1652356270.424890][31321:31326] CHIP:DMG: 					status = 0x00 (SUCCESS),
[1652356270.424962][31321:31326] CHIP:DMG: 				},
[1652356270.425041][31321:31326] CHIP:DMG: 				
[1652356270.425113][31321:31326] CHIP:DMG: 			},
[1652356270.425195][31321:31326] CHIP:DMG: 			
[1652356270.425260][31321:31326] CHIP:DMG: 		},
[1652356270.425342][31321:31326] CHIP:DMG: 		
[1652356270.425401][31321:31326] CHIP:DMG: 	],
[1652356270.425472][31321:31326] CHIP:DMG: 	
[1652356270.425529][31321:31326] CHIP:DMG: 	InteractionModelRevision = 1
[1652356270.425586][31321:31326] CHIP:DMG: },
[1652356270.425721][31321:31326] CHIP:DMG: Received Command Response Status for Endpoint=1 Cluster=0x0000_0102 Command=0x0000_0001 Status=0x0
[1652356270.425816][31321:31326] CHIP:DMG: ICR moving to [AwaitingDe]
[1652356270.425933][31321:31326] CHIP:EM: Sending Standalone Ack for MessageCounter:1523613 on exchange 46952i

### PR DESCRIPTION
**Pull request by kkasperczyk-no**
#### Problem
Nrfconnect window covering example doesn't update window covering cluster attributes properly.

#### Change overview
* Moved PostAttributeChange method from window-covering-server.cpp to header.
* Called PostAttributeChange method in nrfconnect implementation of MatterWindowCoveringClusterServerAttributeChangedCallback
* Changed mode default value from 0x14 to 0.

#### Testing
Reproduced manually tests described in: https://github.com/project-chip/connectedhomeip/issues/18371

Fixes: https://github.com/project-chip/connectedhomeip/issues/18371

### CODE REVIEW

**Review by jmeg-sfy — APPROVED** [review]
LGTM

**Review by Damian-Nordic — APPROVED** [review]

**Comment by markaj-nordic** [comment]
Please hold on with the merge, we need to retest.

**Review by markaj-nordic — APPROVED** [review]

File: src/app/clusters/window-covering-server/window-covering-server.h [hunk 1]
```diff
@@ -139,6 +139,14 @@ void TiltPositionSet(chip::EndpointId endpoint, NPercent100ths position);
 
 EmberAfStatus GetMotionLockStatus(chip::EndpointId endpoint);
 
+/**
+ * @brief PostAttributeChange is called when an Attribute is modified
+ *
+ * @param[in] endpoint
+ * @param[in] attributeId
+ */
+void PostAttributeChange(chip::EndpointId endpoint, chip::AttributeId attributeId);
```
Comment (bzbarsky-apple) [inline src/app/clusters/window-covering-server/window-covering-server.h:148]: I guess, but why is the _app_ implementing the _cluster_ attribute-changed callback, not the _app_ attribute-changed callback, necessitating this call from the app back into the cluster to notify it about the fact that the attribute change it should have known about anyway has happened?

At the very least, this interaction, which is not how other clusters work, needs to be very clearly documented here.  Because nothing in the docs there says "the app must call this function"....

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/clusters/window-covering-server/window-covering-server.h (hunk 1 above)
Comment (kkasperczyk-no) [reply src/app/clusters/window-covering-server/window-covering-server.h:148]: Yeah, I agree and honestly I was also concerned about that, when analyzing the bug root cause. However it was more about fixing the certification fault from my side and I didn't want to modify the cluster code that I don't fully understand much. @jmeg-sfy could we consider changing the cluster behavior in some followup PR?

**Comment by bzbarsky-apple** [comment]
@kkasperczyk-no I was not asking you to modify the cluster code.  But I _was_ asking for decent API docs on the API being added to the cluster, and that did not happen.....

**Comment by kkasperczyk-no** [comment]
> @kkasperczyk-no I was not asking you to modify the cluster code. But I _was_ asking for decent API docs on the API being added to the cluster, and that did not happen.....

@bzbarsky-apple sorry about that, I forgot to do the change after answering on your comment. Pushed followup PR: https://github.com/project-chip/connectedhomeip/pull/18840

File: src/app/clusters/window-covering-server/window-covering-server.h (hunk 1 above)
Comment (jmeg-sfy) [reply src/app/clusters/window-covering-server/window-covering-server.h:148]: Yeah this should be changed in the future. This post Attribute change function is originally there to detect internal/external writes on target position attributes.
it is weak because the implementation of all clusters is different than the original one on EFR32.
We should try to converge to a common a codebase abstracted from the platform rather than forking.
I would support any PR going into this way. I don't know the implementation of NRF well need to look at it.
