### PR TITLE
[TCR] Extended Announcement additions

### LINKED ISSUE #31565: [1.3] [TCR] Implement Extended Announcement for enhanced setup success reliability of device discovery
### Reproduction steps

Originally logged in spec as https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/7632

Updated based on https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/7825

### Bug prevalence

20% of setup attempts

### GitHub hash of the SDK that was being used

na

### Platform

efr32

### Platform Version(s)

_No response_

### Type

Spec Compliance Issue

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ghost**
Hello,

This PR brings changes to support what was discussed/agreed as spec changes and merged based on [#7825](https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/7825) regarding Extended Announcement.

This PR shows an example implementation for the Silabs platform. But the changes are generic and can be opted-into by any platform.
Platforms that do not require this functionality do not require any changes based on this PR.

For platforms that want to opt in, an example CHIPProjectConfig.h might look like this:

`// current configuration option, extend the original basic window opened by the server`
`#define CHIP_DEVICE_CONFIG_DISCOVERY_TIMEOUT_SECS (60 * 60 * 48)`

`// new configuration option to opt-in into Extended Announcement `
`#define CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING 1`

`// if required platforms can override the default configuration`
`#define CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_CHANGE_TIME_MS (15 * 60 * 1000)`

1. In terms of testing, this was developed and tested using Nanoleaf's proprietary HW which is directly based off of the Silabs platform together with both Apple and Google ecosystems (1 BR + 1 mobile device with their respective OSes each).
3. Both ecosystems successfully paired with the DUT during the new extended adv. period. 
4. Because of the VID/PID elision a user either needs to scan a QR code or otherwise provide it manually (same as the regular pairing flow), during commissioning both ecosystems correctly identified the DUT, showing the correct information to the user.

The problem this PR aims to solve is poor user setup experience (as defined in the spec change discussion) because the device cannot be found by a controller for a wide array of reasons (from time based to actual spurious failures especially based on the environment).

Fixes #31565

### CODE REVIEW

File: src/platform/silabs/BLEManagerImpl.h [hunk 1]
```diff
@@ -208,6 +208,11 @@ class BLEManagerImpl final : public BLEManager, private BleLayer, private BlePla
     static void DriveBLEState(intptr_t arg);
     static void BleAdvTimeoutHandler(TimerHandle_t xTimer);
     uint8_t GetTimerHandle(uint8_t connectionHandle, bool allocate);
+
+#if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
+    uint16_t Internal_Slow_Advertising_MIN = CHIP_DEVICE_CONFIG_BLE_SLOW_ADVERTISING_INTERVAL_MIN;
+    uint16_t Internal_Slow_Advertising_MAX = CHIP_DEVICE_CONFIG_BLE_SLOW_ADVERTISING_INTERVAL_MAX;
+#endif
```
Comment (tcarmelveilleux) [inline src/platform/silabs/BLEManagerImpl.h:215]: This does not need to be in the header. Recommend only having this in the impl file (e.g. BLEManagerImpl)

File: src/include/platform/CHIPDeviceConfig.h [hunk 2]
```diff
@@ -617,6 +617,22 @@
...
+
+#if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
+
+#ifndef CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_CHANGE_TIME
+#define CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_CHANGE_TIME (15 * 60 * 1000)
+#endif
+
+#ifndef CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL
+#define CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL 1920
+#endif
```
Comment (tcarmelveilleux) [inline src/include/platform/CHIPDeviceConfig.h:632]: Please document all of these constants

File: src/platform/silabs/efr32/BLEManagerImpl.cpp [hunk 3]
```diff
@@ -458,6 +458,18 @@ CHIP_ERROR BLEManagerImpl::ConfigureAdvertisingData(void)
     advData[index++] = CHIP_ADV_DATA_TYPE_SERVICE_DATA;                                         // AD type : Service Data
     advData[index++] = ShortUUID_CHIPoBLEService[0];                                            // AD value
     advData[index++] = ShortUUID_CHIPoBLEService[1];
+
+#if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
+    // check for extended advertisment interval
```
Comment (tcarmelveilleux) [inline src/platform/silabs/efr32/BLEManagerImpl.cpp:463]:
```suggestion
    // Check for extended advertisement interval and redact VID/PID if past the initial period.
```

File: src/platform/silabs/efr32/BLEManagerImpl.cpp [hunk 4]
```diff
@@ -458,6 +458,18 @@ CHIP_ERROR BLEManagerImpl::ConfigureAdvertisingData(void)
...
+    if (BLEMgrImpl().Internal_Slow_Advertising_MIN == CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL)
+    {
+        mDeviceIdInfo.SetVendorId(0x0000);
+        mDeviceIdInfo.SetProductId(0x0000);
+        mDeviceIdInfo.SetAdditionalDataFlag(true);
```
Comment (tcarmelveilleux) [inline src/platform/silabs/efr32/BLEManagerImpl.cpp:468]: Why is the AdditionalDataFlag set?

File: src/platform/silabs/efr32/BLEManagerImpl.cpp [hunk 5]
```diff
@@ -953,8 +970,26 @@ void BLEManagerImpl::BleAdvTimeoutHandler(TimerHandle_t xTimer)
...
+#endif
+        BLEMgr().SetAdvertisingMode(BLEAdvertisingMode::kSlowAdvertising);
+#if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
+        BLEMgrImpl().StartBleAdvTimeoutTimer(CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_CHANGE_TIME);
+#endif
+    }
+#if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
+    else
+    {
+        ChipLogDetail(DeviceLayer, "bleAdv Timeout : Start extended advertisment");
```
Comment (tcarmelveilleux) [inline src/platform/silabs/efr32/BLEManagerImpl.cpp:986]:
```suggestion
        ChipLogDetail(DeviceLayer, "bleAdv Timeout : Start extended advertisement");
```

File: src/platform/silabs/efr32/BLEManagerImpl.cpp [hunk 6]
```diff
@@ -554,8 +566,13 @@ CHIP_ERROR BLEManagerImpl::StartAdvertising(void)
     }
     else
     {
+#if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
+        interval_min = BLEMgrImpl().Internal_Slow_Advertising_MIN;
+        interval_max = BLEMgrImpl().Internal_Slow_Advertising_MAX;
```
Comment (tcarmelveilleux) [inline src/platform/silabs/efr32/BLEManagerImpl.cpp:571]: You can use the actual constants here. There is no need to access members that are only relevant to the implementation and come from a global config header.

**Review by tcarmelveilleux — COMMENTED** [review]
Please indicate in the PR description how this was tested and which issue it resolves.

File: src/platform/silabs/efr32/BLEManagerImpl.cpp (hunk 4 above)
Comment (cnanoleaf) [reply src/platform/silabs/efr32/BLEManagerImpl.cpp:468]: For no reason apparently, I was confused regarding the spec requirement. You are right, not needed will remove.

File: src/app/server/CommissioningWindowManager.h [hunk 7]
```diff
@@ -59,8 +59,13 @@ class CommissioningWindowManager : public Messaging::UnsolicitedMessageHandler,
 
     static constexpr System::Clock::Seconds16 MaxCommissioningTimeout()
     {
+#if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
+        // per new spec change/extension - Extended Announcement Duration up to 48h
```
Comment (mkardous-silabs) [inline src/app/server/CommissioningWindowManager.h:63]:
```suggestion
        // per spec - Extended Announcement Duration up to 48h
```

Comment (cnanoleaf) [reply src/app/server/CommissioningWindowManager.h:63]: @mkardous-silabs  I got the actual proper info from the new spec now: 
`// Specification section 2.3.1 - Extended Announcement Duration up to 48h`

File: src/include/platform/CHIPDeviceConfig.h (hunk 2 above)
Comment (andy31415) [reply src/include/platform/CHIPDeviceConfig.h:632]: what is this interval measured in? please add suffix.

File: src/platform/silabs/BLEManagerImpl.h (hunk 1 above)
Comment (andy31415) [reply src/platform/silabs/BLEManagerImpl.h:215]: member variable names use `mCamelCase`. Please do not use SnakeCase and use `Min/Max` without uppercasing them.

Comment (cnanoleaf) [reply src/platform/silabs/BLEManagerImpl.h:215]: @andy31415 Noted for next time, for this one I will step away from the member to using the constants directly as requested above.

File: src/include/platform/CHIPDeviceConfig.h (hunk 2 above)
Comment (cnanoleaf) [reply src/include/platform/CHIPDeviceConfig.h:632]: @andy31415  Added to the comments documentation same as all the others. Again, I would be happy to change the define as well but then we should probably adjust all of them in that file, at least the BLE ones for consistency, not to confuse new users.

File: src/platform/silabs/efr32/BLEManagerImpl.cpp [hunk 8]
```diff
@@ -460,12 +460,11 @@ CHIP_ERROR BLEManagerImpl::ConfigureAdvertisingData(void)
     advData[index++] = ShortUUID_CHIPoBLEService[1];
 
 #if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
-    // check for extended advertisment interval
-    if (BLEMgrImpl().Internal_Slow_Advertising_MIN == CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL)
+    // Check for extended advertisement interval and redact VID/PID if past the initial period.
+    if (mFlags.Has(Flags::kExtAdvertisingEnabled)) {
```
Comment (jmartinez-silabs) [inline src/platform/silabs/efr32/BLEManagerImpl.cpp]: double bracket here is cause the large restyle shift

File: src/include/platform/CHIPDeviceConfig.h [hunk 9]
```diff
@@ -617,18 +617,56 @@
 #define CHIP_DEVICE_CONFIG_BLE_ADVERTISING_INTERVAL_CHANGE_TIME 30000
 #endif
 
+/**
+ * CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
+ *
+ * Optional configuration to enable Extended Announcement Duration up to 48h
+ * Should be used together with extending CHIP_DEVICE_CONFIG_DISCOVERY_TIMEOUT_SECS past 15 minutes
+ * Disabled by default
```
Comment (tcarmelveilleux) [inline src/include/platform/CHIPDeviceConfig.h:625]:
```suggestion
 * Optional configuration to enable Extended Announcement Duration up to 48h.
 * Should be used together with extending CHIP_DEVICE_CONFIG_DISCOVERY_TIMEOUT_SECS past 15 minutes.
 * Disabled by default.
```

File: src/include/platform/CHIPDeviceConfig.h [hunk 10]
```diff
@@ -617,18 +617,56 @@
...
 
 #if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
 
+/**
+ * CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_CHANGE_TIME
+ *
+ * The amount of time in miliseconds after which BLE advertisement should be switched from the slow
+ * advertising to the extended advertising, counting from the moment of advertisement commencement.
+ *
+ *  Defaults to 15 minutes measured in ms.
```
Comment (tcarmelveilleux) [inline src/include/platform/CHIPDeviceConfig.h:640]: Please measure in seconds everywhere or milliseconds everywhere.

File: src/include/platform/CHIPDeviceConfig.h [hunk 11]
```diff
@@ -617,18 +617,56 @@
...
+ *
+ * The interval (in units of 0.625ms) at which the device will send BLE advertisements while
+ * in extended advertising mode. The maximum interval should be greater and not equal to the
+ * CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_MIN.
+ *
+ * Defaults to 1936 (1210 ms).
+ */
+#ifndef CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_MAX
+#define CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_MAX 1936
 #endif
```
Comment (tcarmelveilleux) [inline src/include/platform/CHIPDeviceConfig.h:671]: Suggest a static_assert that the number of seconds/millis (whatever the end result is) of total advertisement for both initial and extended, does not cross 48h total.

File: src/app/server/CommissioningWindowManager.h [hunk 12]
```diff
@@ -60,7 +60,7 @@ class CommissioningWindowManager : public Messaging::UnsolicitedMessageHandler,
     static constexpr System::Clock::Seconds16 MaxCommissioningTimeout()
     {
 #if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
-        // per new spec change/extension - Extended Announcement Duration up to 48h
+        // Specification section 2.3.1 - Extended Announcement Duration up to 48h
         return System::Clock::Seconds16(60 * 60 * 48);
```
[the remark this answers is not in the document]
Comment (cnanoleaf) [reply src/app/server/CommissioningWindowManager.h:64]: Yes, I thought about that as well. So, would you like a define for the value on both branches? 
I was a little surprised to see it was missing a define to being with (even if its just a constant value from the spec).

File: src/include/platform/CHIPDeviceConfig.h (hunk 10 above)
Comment (cnanoleaf) [reply src/include/platform/CHIPDeviceConfig.h:640]: Its all measured in ms, the minutes where just documentation. I will adjust it to the ms value for consistency.

File: src/include/platform/CHIPDeviceConfig.h (hunk 11 above)
Comment (cnanoleaf) [reply src/include/platform/CHIPDeviceConfig.h:671]: Sure.

File: src/platform/silabs/efr32/BLEManagerImpl.cpp [hunk 13]
```diff
@@ -554,8 +564,16 @@ CHIP_ERROR BLEManagerImpl::StartAdvertising(void)
     }
     else
     {
-        interval_min = CHIP_DEVICE_CONFIG_BLE_SLOW_ADVERTISING_INTERVAL_MIN;
-        interval_max = CHIP_DEVICE_CONFIG_BLE_SLOW_ADVERTISING_INTERVAL_MAX;
+        if (!(mFlags.Has(Flags::kExtAdvertisingEnabled))) {
```
Comment (mkardous-silabs) [inline src/platform/silabs/efr32/BLEManagerImpl.cpp]: If we remove the else we should also remove the if imo

File: src/include/platform/CHIPDeviceConfig.h [hunk 14]
```diff
@@ -617,6 +617,22 @@
...
 
+#ifndef CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
+#define CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING 0
+#endif
+
+#if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
+
+#ifndef CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_CHANGE_TIME
+#define CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_CHANGE_TIME (15 * 60 * 1000)
```
[the remark this answers is not in the document]
Comment (andy31415) [reply src/include/platform/CHIPDeviceConfig.h:643]: Lets make new code better regardless of what old code does. I am not asking to fix the old code (although that would be great) however I am asking for new code to be updated.

File: src/platform/silabs/efr32/BLEManagerImpl.cpp [hunk 15]
```diff
@@ -458,6 +458,17 @@ CHIP_ERROR BLEManagerImpl::ConfigureAdvertisingData(void)
     advData[index++] = CHIP_ADV_DATA_TYPE_SERVICE_DATA;                                         // AD type : Service Data
     advData[index++] = ShortUUID_CHIPoBLEService[0];                                            // AD value
     advData[index++] = ShortUUID_CHIPoBLEService[1];
+
+#if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
+    // Check for extended advertisement interval and redact VID/PID if past the initial period.
+    if (mFlags.Has(Flags::kExtAdvertisingEnabled))
+    {
+        mDeviceIdInfo.SetVendorId(0x0000);
+        mDeviceIdInfo.SetProductId(0x0000);
```
Comment (andy31415) [inline src/platform/silabs/efr32/BLEManagerImpl.cpp:467]: maybe just `0` is clearer than the 0x0000 as it is shorter and looks more like a `clear`

File: src/platform/silabs/efr32/BLEManagerImpl.cpp [hunk 16]
```diff
@@ -554,8 +565,18 @@ CHIP_ERROR BLEManagerImpl::StartAdvertising(void)
     }
     else
     {
-        interval_min = CHIP_DEVICE_CONFIG_BLE_SLOW_ADVERTISING_INTERVAL_MIN;
-        interval_max = CHIP_DEVICE_CONFIG_BLE_SLOW_ADVERTISING_INTERVAL_MAX;
+        if (!(mFlags.Has(Flags::kExtAdvertisingEnabled)))
```
Comment (andy31415) [inline src/platform/silabs/efr32/BLEManagerImpl.cpp:568]:
```suggestion
        if (!mFlags.Has(Flags::kExtAdvertisingEnabled))
```

File: src/platform/silabs/efr32/BLEManagerImpl.cpp [hunk 17]
```diff
@@ -950,11 +968,23 @@ uint8_t BLEManagerImpl::GetTimerHandle(uint8_t connectionHandle, bool allocate)
 
 void BLEManagerImpl::BleAdvTimeoutHandler(TimerHandle_t xTimer)
 {
-    if (BLEMgrImpl().mFlags.Has(Flags::kFastAdvertisingEnabled))
-    {
+    if (BLEMgrImpl().mFlags.Has(Flags::kFastAdvertisingEnabled)) {
         ChipLogDetail(DeviceLayer, "bleAdv Timeout : Start slow advertissment");
+        BLEMgrImpl().mFlags.Set(Flags::kAdvertising);
```
[the remark this answers is not in the document]
Comment (cnanoleaf) [reply src/platform/silabs/efr32/BLEManagerImpl.cpp:977]: That is a very good question. Not all platforms use the same priority model as your examples, and depending on that this might be necessary, since SetAdvertisingMode triggers delayed execution of the StartAdvertising. 

If we are already advertising it does not matter and it covers a wider range of cases.

File: src/platform/silabs/efr32/BLEManagerImpl.cpp [hunk 18]
```diff
@@ -950,11 +968,23 @@ uint8_t BLEManagerImpl::GetTimerHandle(uint8_t connectionHandle, bool allocate)
...
+        BLEMgrImpl().mFlags.Clear(Flags::kExtAdvertisingEnabled);
+        BLEMgrImpl().StartBleAdvTimeoutTimer(CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_CHANGE_TIME);
+#endif
+    }
+#if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
+    else {
+        ChipLogDetail(DeviceLayer, "bleAdv Timeout : Start extended advertisment");
+        BLEMgrImpl().mFlags.Set(Flags::kAdvertising);
+        BLEMgrImpl().mFlags.Set(Flags::kExtAdvertisingEnabled);
         BLEMgr().SetAdvertisingMode(BLEAdvertisingMode::kSlowAdvertising);
```
[the remark this answers is not in the document]
Comment (cnanoleaf) [reply src/platform/silabs/efr32/BLEManagerImpl.cpp:990]: Same response as the reply above.

File: src/platform/silabs/efr32/BLEManagerImpl.cpp [hunk 19]
```diff
@@ -950,11 +968,23 @@ uint8_t BLEManagerImpl::GetTimerHandle(uint8_t connectionHandle, bool allocate)
...
+        BLEMgr().SetAdvertisingMode(BLEAdvertisingMode::kSlowAdvertising);
+#if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
+        BLEMgrImpl().mFlags.Clear(Flags::kExtAdvertisingEnabled);
+        BLEMgrImpl().StartBleAdvTimeoutTimer(CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_CHANGE_TIME);
+#endif
+    }
+#if CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING
+    else {
+        ChipLogDetail(DeviceLayer, "bleAdv Timeout : Start extended advertisment");
+        BLEMgrImpl().mFlags.Set(Flags::kAdvertising);
```
[the remark this answers is not in the document]
Comment (cnanoleaf) [reply src/platform/silabs/efr32/BLEManagerImpl.cpp:988]: If you are referring to the `BLEMgrImpl().mFlags.Set(Flags::kAdvertising);`, yes, answered above.

File: src/platform/silabs/efr32/BLEManagerImpl.cpp (hunk 13 above)
Comment (cnanoleaf) [reply src/platform/silabs/efr32/BLEManagerImpl.cpp]: Sure, I did not want to add another, but yes its nicer.

File: src/include/platform/CHIPDeviceConfig.h [hunk 20]
```diff
@@ -617,6 +617,60 @@
...
+ */
+#ifndef CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_CHANGE_TIME
+#define CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_CHANGE_TIME (15 * 60 * 1000)
+#endif
+
+/**
+ * CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_MIN
+ *
+ * The minimum interval (in units of 0.625ms) at which the device will send BLE advertisements while
+ * in extended advertising mode. The minimum interval should be smaller and not equal to the
```
[the remark this answers is not in the document]
Comment (cnanoleaf) [reply src/include/platform/CHIPDeviceConfig.h:650]: We could but in that case I would adjust the previous case for the slow that is also missing it and has the wrong wording on it as a copy/paste issue. I was trying to touch less, but sure.

[the remark this answers is not in the document]
Comment (cnanoleaf) [reply src/include/platform/CHIPDeviceConfig.h:650]: @mkardous-silabs Spec says SHALL and ideally equal. I believe older versions of the GSDK (and some other SDKs) might have have an issue with both equal.

I will adjust the wording to SHALL and keep the interval as low as possible by default, from my trial runs 10 ms seems to do the trick.

File: src/include/platform/CHIPDeviceConfig.h [hunk 21]
```diff
@@ -617,6 +617,60 @@
...
+ */
+#ifndef CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_MIN
+#define CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_MIN 1920
+#endif
+
+/**
+ * CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_MAX
+ *
+ * The interval (in units of 0.625ms) at which the device will send BLE advertisements while
+ * in extended advertising mode. The maximum interval should be greater and not equal to the
```
[the remark this answers is not in the document]
Comment (cnanoleaf) [reply src/include/platform/CHIPDeviceConfig.h:663]: Answered above.

**Comment by ndyck14** [comment]
This resolves #31565

File: src/include/platform/CHIPDeviceConfig.h (hunk 20 above)
[the remark this answers is not in the document]
Comment (cnanoleaf) [reply src/include/platform/CHIPDeviceConfig.h:650]: As the spec is clear, I am going to enforce the min and add a static assert for the max.

File: src/include/platform/CHIPDeviceConfig.h (hunk 11 above)
Comment (cnanoleaf) [reply src/include/platform/CHIPDeviceConfig.h:671]: But this would be above. This `CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_MAX` is just how fast the adv. is sent out, as in the period for the radio stack.

File: src/app/server/CommissioningWindowManager.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (cnanoleaf) [reply src/app/server/CommissioningWindowManager.h:64]: Looking again at this. Just to make sure, those values are just spec enforcement. The actual size of the window is configurable already with `CHIP_DEVICE_CONFIG_DISCOVERY_TIMEOUT_SECS`, setting that to 48 h means the window will close at 48h taking the BLE with it (Server takes care of that when closing the window).

The rest is just BLE tracking on the platform to switch the period/frequency of the adv. at their respective time points.

**Review by jmartinez-silabs — APPROVED** [review]

**Review by mkardous-silabs — APPROVED** [review]

File: src/app/server/CommissioningWindowManager.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/server/CommissioningWindowManager.h:64]: Please add a static assert to ensure that it is never > 48 when we add CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_CHANGE_TIME_MS

**Review by tcarmelveilleux — APPROVED** [review]

File: src/app/server/CommissioningWindowManager.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (cnanoleaf) [reply src/app/server/CommissioningWindowManager.h:64]: Sure.
I think I get what you mean now, its basically that a platform would configure the window to 48 and go rogue a bit after that up to `CHIP_DEVICE_CONFIG_BLE_EXT_ADVERTISING_INTERVAL_CHANGE_TIME_MS` when its timer would actually expire.

I am adding the assert on that branch.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@cnanoleaf - You do not need to keep updating to master since that resets the CI pipline. Please let it finish as-is.
