### PR TITLE
Fix unbounded stack in emberAfPrintBuffer()

### LINKED ISSUE #3662: Unbounded stack in emberAfPrintBuffer()
#### Problem

emberAfPrintBuffer() allocates stack space based on an argument, with no upper bound. This could lead to stack exhaustion on small devices.

 #### Proposed Solution

Since this is used for logging, to dump data in hexadecimal, it may be sufficient to break a long argument into multiple lines.

### PR DESCRIPTION
**Pull request by kpschoedel**
#### Problem

`emberAfPrintBuffer()` allocates stack space based on an argument, with
no upper bound. This could lead to stack exhaustion on small devices.

#### Summary of Changes

Print long buffers in multiple segments.

Fixes #3662 - Unbounded stack in emberAfPrintBuffer()

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

File: src/app/util/ember-print.cpp [hunk 1]
```diff
@@ -48,35 +49,38 @@ void emberAfPrintln(int category, const char * format, ...)
     }
 }
 
-// TODO: issue #3662 - Unbounded stack in emberAfPrintBuffer()
-#pragma GCC diagnostic push
-#pragma GCC diagnostic ignored "-Wstack-usage="
-
 void emberAfPrintBuffer(int category, const uint8_t * buffer, uint16_t length, bool withSpace)
```
Comment (andy31415) [inline src/app/util/ember-print.cpp:52]: Is there a way we could unit test this? Maybe add a TODO PR (I think I wanted to do app/util unit tests before and failed, so it does not seem fair to ask you do do it as part of this PR).

**Review by andy31415 — APPROVED** [review]

File: src/app/util/ember-print.cpp (hunk 1 above)
Comment (kpschoedel) [reply src/app/util/ember-print.cpp:55]: Added TODO. I did verify the change out-of-tree with a `#define emberAfPrint(c,...) printf(__VA_ARGS__)`.

**Review by woody-apple — APPROVED** [review]
