### PR TITLE
Fix various issues with TCP connections

### LINKED ISSUE #30670: The TCP Connection State objects need to be converted to a reference-counted object
### Reproduction steps

This is an improvement task.
Currently, the Active TCP connection objects in TCP.h are not implemented as a subclass of the ReferenceCounted. It should be converted to that to enable automatic reference counting.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

503cbc5f2

### Platform

core

### Platform Version(s)

_No response_

### Type

Core SDK Memory Issue

### Anything else?

_No response_

### LINKED ISSUE #39690: [BUG] local.py tests running against boringssl fail for LARGE_PAYLOAD
### Reproduction steps

Running:
```
source ./scripts/bootstrap.sh
./scripts/tests/local.py build
./scripts/tests/local.py python-tests --test-filter TestCheckCommandFlags.py --keep-going
```

Get:

```
No memory at src/app/OperationalSessionSetup.cpp:254
```

The issue seems to be that [local.py uses `variants = ["no-ble", "clang", "boringssl"]`](https://github.com/project-chip/connectedhomeip/blob/31c8966f7903aacfeddb4d563a2336f30d16903e/scripts/tests/local.py#L76), and `boringssl` seems to be the underlying cause

### Bug prevalence

Workaround available by not using boringssl, but happens 100% with boringssl

### GitHub hash of the SDK that was being used

f3fc26aa7cecead92ddebac6230f8e0cca93515b

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by gmarcosb**
#### Summary

Previously, `TCPBase::TCPConnect` & `TCPBase::HandleIncomingConnection` would pre-allocate a TCP connection, which `Session::mTCPConnection` would hold onto.

Because said TCP connection ends up being shared between the insecure connection & secure connection & `CASESesssion`, the only safe way to properly release this TCP connection when a session is closed is via reference-counting.

`TCPBase::SendMessage` would also allocate a TCP connection if there was no previous call to `TCPBase::TCPConnect`, and [said connection would be leaked, with no straightforward way to clean-up](https://github.com/project-chip/connectedhomeip/blob/f3fbd606da8194ecc7e9d8451b4cc21d11356f36/src/transport/raw/TCP.cpp#L298).

This PR makes it so that all connections must be explicitly initiated & owned via `ActiveTCPConnectionHolder`, which will decrement the reference on dtor.

Lastly, this PR fixes multiple connections to same peer (e.g. 2 controllers for 2 fabrics), which previously would fail CASE due to 2 TCP connections being created but messages being sent through the first connection found with `FindActiveConnection`.

#### Related issues

Fixes https://github.com/project-chip/connectedhomeip/issues/39690, which was caused by TCP connections being allocated & never freed

#### Testing

Existing tests run in CI now properly check for ownership

### CODE REVIEW

File: src/transport/raw/ActiveTCPConnectionState.h [hunk 1]
```diff
@@ -46,38 +49,32 @@ enum class TCPState
 };
 
 struct AppTCPConnectionCallbackCtxt;
+
+// Templatized to force inlining
+template <typename State>
+class ActiveTCPConnectionStateDeleter
```
Comment (pidarped) [inline src/transport/raw/ActiveTCPConnectionState.h:59]: Is this templatization and inlining necessary? Wouldn't this also increase code-size at call-sites?

File: src/transport/raw/ActiveTCPConnectionState.h [hunk 2]
```diff
@@ -103,14 +100,90 @@ struct ActiveTCPConnectionState
...
+
+    // For printing
+    inline operator const void *() const { return mReleasable; }
 };
 
+inline bool ActiveTCPConnectionState::operator==(const ActiveTCPConnectionHolder & other) const
+{
+    return this == other.mReleasable;
+}
+inline bool ActiveTCPConnectionState::operator!=(const ActiveTCPConnectionHolder & other) const
```
Comment (pidarped) [inline src/transport/raw/ActiveTCPConnectionState.h:189]: Any particular reason we omitted the `==` and `!=` operator overloads between 2 ActiveTCPConnectionState objects?

File: src/transport/raw/TCP.cpp [hunk 3]
```diff
@@ -216,56 +257,55 @@ CHIP_ERROR TCPBase::SendMessage(const Transport::PeerAddress & address, System::
...
 
-    endPoint->mAppState         = reinterpret_cast<void *>(this);
-    endPoint->OnConnectComplete = HandleTCPEndPointConnectComplete;
-    endPoint->SetConnectTimeout(mConnectTimeout);
+    InitEndpoint(endPoint);
 
-    activeConnection = AllocateConnection();
-    VerifyOrReturnError(activeConnection != nullptr, CHIP_ERROR_NO_MEMORY);
-    activeConnection->Init(endPoint, addr);
+    ActiveTCPConnectionHolder activeConnection = AllocateConnection(endPoint, addr);
```
Comment (pidarped) [inline src/transport/raw/TCP.cpp]: AllocateConnection actually returns a pointer to ActiveTCPConnectionState. For clarity, should activeConnection be  typed as such?

File: src/transport/raw/TCP.h [hunk 4]
```diff
@@ -221,29 +214,30 @@ class DLL_EXPORT TCPBase : public Base
      * Allocate an unused connection from the pool
      *
      */
```
Comment (pidarped) [inline src/transport/raw/TCP.h:212]: The documentation probably needs an update to indicate that this also does initialization after allocation.

File: src/transport/raw/TCP.cpp [hunk 5]
```diff
@@ -127,21 +145,33 @@ void TCPBase::Close()
...
+        {
+            ActiveTCPConnectionHolder releaseUnclaimed(&mActiveConnections[i]);
+        }
+    }
     return nullptr;
 }
 
 // Find an ActiveTCPConnectionState corresponding to a peer address
-ActiveTCPConnectionState * TCPBase::FindActiveConnection(const PeerAddress & address)
+ActiveTCPConnectionHolder TCPBase::FindInUseConnection(const PeerAddress & address)
```
Comment (pidarped) [inline src/transport/raw/TCP.cpp:177]: Why was the FindActiveConnection renamed to FindInUseConnection? FindActiveConnection seeks a connection that is in Connected state.

File: src/transport/raw/TCP.cpp [hunk 6]
```diff
@@ -150,17 +180,28 @@ ActiveTCPConnectionState * TCPBase::FindActiveConnection(const PeerAddress & add
...
-        uint16_t port;
-        mActiveConnections[i].mEndPoint->GetPeerInfo(&addr, &port);
 
-        if ((addr == address.GetIPAddress()) && (port == address.GetPort()))
+        if (conn.mPeerAddr == address)
         {
-            return &mActiveConnections[i];
+            Inet::IPAddress addr;
+            uint16_t port;
+            if (conn.IsConnected() && conn.mEndPoint->GetPeerInfo(&addr, &port) != CHIP_NO_ERROR)
```
Comment (pidarped) [inline src/transport/raw/TCP.cpp:196]: The IsConnected() call should indicate if the connection is active. Why do we need to call GetPeerInfo()? 
Note that a call to GetPeerInfo() can potentially fail if the network is in a transient bad state. Reseting it could create unnecessary churn.

File: src/transport/raw/TCP.cpp [hunk 7]
```diff
@@ -150,17 +180,28 @@ ActiveTCPConnectionState * TCPBase::FindActiveConnection(const PeerAddress & add
...
+            {
+                // Failure to get peer information means the connection is bad, re-establish connection
+                CHIP_ERROR err = TryResetConnection(conn);
+                if (err != CHIP_NO_ERROR)
+                {
+                    CloseConnectionInternal(conn, err, SuppressCallback::No);
```
Comment (pidarped) [inline src/transport/raw/TCP.cpp:202]: What would the application do when it receives a callback from this function?

File: src/transport/raw/TCP.cpp [hunk 8]
```diff
@@ -216,56 +257,55 @@ CHIP_ERROR TCPBase::SendMessage(const Transport::PeerAddress & address, System::
     uint8_t * output = msgBuf->Start();
     LittleEndian::Write32(output, static_cast<uint32_t>(msgBuf->DataLength() - kPacketSizeBytes));
 
-    // Reuse existing connection if one exists, otherwise a new one
-    // will be established
-    ActiveTCPConnectionState * connection = FindActiveConnection(address);
-
-    if (connection != nullptr)
+    // Must find a previously-established connection with an owning reference
+    auto connection = FindInUseConnection(address);
```
Comment (pidarped) [inline src/transport/raw/TCP.cpp:271]: Shouldn't this be a call to FindActiveConnection() and if the returned connection is Null then skip the SendMessage and call SendAfterConnect() with the Null connectionholder object?

File: src/transport/raw/TCP.cpp [hunk 9]
```diff
@@ -291,15 +331,8 @@ CHIP_ERROR TCPBase::SendAfterConnect(const PeerAddress & addr, System::PacketBuf
         return CHIP_NO_ERROR;
     }
 
-    // Ensures sufficient active connections size exist
-    VerifyOrReturnError(mUsedEndPointCount < mActiveConnectionsSize, CHIP_ERROR_NO_MEMORY);
-
-    Transport::ActiveTCPConnectionState * peerConnState = nullptr;
-    ReturnErrorOnFailure(StartConnect(addr, nullptr, &peerConnState));
```
Comment (pidarped) [inline src/transport/raw/TCP.cpp:298]: Is this not establishing a connection for sending the message? Is the passed in ActiveConnectionHolder expected to hold an active connection?

File: src/transport/raw/TCP.cpp [hunk 10]
```diff
@@ -127,21 +145,33 @@ void TCPBase::Close()
     mState = TCPState::kNotReady;
 }
 
-ActiveTCPConnectionState * TCPBase::AllocateConnection()
+ActiveTCPConnectionState * TCPBase::AllocateConnection(Inet::TCPEndPoint * endpoint, const PeerAddress & address)
```
Comment (pidarped) [inline src/transport/raw/TCP.cpp:148]: Maybe rename this function AllocateAndInitConnection(..) since now this does the Init() inside.

File: src/transport/raw/TCP.cpp [hunk 11]
```diff
@@ -127,21 +145,33 @@ void TCPBase::Close()
...
 {
-    for (size_t i = 0; i < mActiveConnectionsSize; i++)
+    for (int reclaim = 0; reclaim < 1; reclaim++)
```
Comment (pidarped) [inline src/transport/raw/TCP.cpp]: Why is this necessary?

File: src/transport/raw/TCP.cpp [hunk 12]
```diff
@@ -127,21 +145,33 @@ void TCPBase::Close()
...
+                ActiveTCPConnectionState * activeConnection = &mActiveConnections[i];
+                VerifyOrDie(activeConnection->GetReferenceCount() == 0);
+                // Update state for the active connection
+                activeConnection->Init(endpoint, address, [this](auto & conn) { TCPDisconnect(conn, true); });
+                return activeConnection;
+            }
         }
-    }
 
+        // Verify that previously-unclaimed connections are released
```
Comment (pidarped) [inline src/transport/raw/TCP.cpp]: Why is this releasing all connections here?

File: src/transport/raw/TCP.cpp [hunk 13]
```diff
@@ -384,71 +416,64 @@ CHIP_ERROR TCPBase::ProcessSingleMessage(const PeerAddress & peerAddress, Active
...
+    connection.mConnectionState = TCPState::kClosed;
+
+    if (suppressCallback == SuppressCallback::No)
+    {
+        if (prevState == TCPState::kConnecting)
         {
-            connection->mEndPoint->Close();
+            ActiveTCPConnectionHolder holder(&connection);
+            // Call upper layer connection attempt complete handler
+            HandleConnectionAttemptComplete(holder, err);
```
Comment (pidarped) [inline src/transport/raw/TCP.cpp:507]: Why this asymmetry in the 2 callbacks where _HandleConnectionAttemptComplete_ takes the holder while _HandleConnectionClosed_ takes the connection?

File: src/transport/raw/TCP.cpp [hunk 14]
```diff
@@ -384,71 +416,64 @@ CHIP_ERROR TCPBase::ProcessSingleMessage(const PeerAddress & peerAddress, Active
...
     HandleMessageReceived(peerAddress, std::move(message), &msgContext);
     return CHIP_NO_ERROR;
 }
 
-void TCPBase::CloseConnectionInternal(ActiveTCPConnectionState * connection, CHIP_ERROR err, SuppressCallback suppressCallback)
+void TCPBase::CloseConnectionInternal(ActiveTCPConnectionState & connection, CHIP_ERROR err, SuppressCallback suppressCallback)
 {
-    TCPState prevState;
-
-    if (connection == nullptr)
```
Comment (pidarped) [inline src/transport/raw/TCP.cpp:401]: Why not 
`if (connection.IsNull())
{
    return;
}` ?

File: src/transport/raw/ActiveTCPConnectionState.h (hunk 1 above)
Comment (gmarcosb) [reply src/transport/raw/ActiveTCPConnectionState.h:59]: This calls a single method, entry::mReleaseConnection, and the call site is not going to be increased vs calling the single method of `ActiveTCPConnectionStateDeleter`

Significant savings from being able to inline & effectively not have `ActiveTCPConnectionStateDeleter` in compiled code

File: src/transport/raw/ActiveTCPConnectionState.h (hunk 2 above)
Comment (gmarcosb) [reply src/transport/raw/ActiveTCPConnectionState.h:189]: That would just fall through to a pointer comparison, which would be valid & have this behavior; the reason we need one for `ActiveTCPConnectionHolder` is because it holds a pointer, and we want to compare the pointers it holds rather than the holder

File: src/transport/raw/TCP.cpp (hunk 3 above)
Comment (gmarcosb) [reply src/transport/raw/TCP.cpp]: We want to take ownership of the connection, thus `ActiveTCPConnectionHolder` - ideally `AllocateConnection` would give us a `ActiveTCPConnectionHolder`, but there are some complexities with incoming connections: we don't have an owner until `TCPBase::ProcessSingleMessage`, and so we must keep the `ActiveTCPConnectionState` "dangling" after `HandleIncomingConnection` until we have a session which can take ownership of the connection

File: src/transport/raw/TCP.cpp (hunk 5 above)
Comment (gmarcosb) [reply src/transport/raw/TCP.cpp:177]: Because we should also be finding a connection that is in Connecting state

The previous code would create a new connection if it found one that was Connecting instead of re-using it, which is wrong behavior.

The new code expects an existing connection, whether it's connecting or connected; if it's connected, it sends the message; if it's connecting, it queues

File: src/transport/raw/TCP.cpp (hunk 6 above)
Comment (gmarcosb) [reply src/transport/raw/TCP.cpp:196]: `GetPeerInfo()` will check if the connection is still valid; if the peer has reset the connection, `GetPeerInfo` will return an error, which means all future attempts to send packets using said connection will fail

In that case, we re-connect here

The old code was inadvertently/accidentally doing this: it wasn't checking the error code for `GetPeerInfo`, but it was comparing against uninitialized memory (addr & port would be uninitialized if `GetPeerInfo` returned an error), and would thus create a new connection most of the time - trouble is,it would leave the old invalid connection dangling

File: src/transport/raw/TCP.cpp (hunk 7 above)
Comment (gmarcosb) [reply src/transport/raw/TCP.cpp:202]: The same it would do if the connection was explicitly closed; this basically means: "the peer of the connection you have a handle to, is no longer there, the connection is bad & closed; handle accordingly"

File: src/transport/raw/TCP.cpp (hunk 12 above)
Comment (gmarcosb) [reply src/transport/raw/TCP.cpp]: It's only releasing unclaimed connections ("previously-unclaimed")

`ActiveTCPConnectionHolder releaseUnclaimed(&mActiveConnections[i]);` increments/decrements the refcount

For any claimed connections (i.e. refcount > 0, e.g. a `Session` holding onto it), the connection will be fine

For any unclaimed connection (i.e. something which came through `HandleIncomingConnection` without a follow-on `ProcessSingleMessage`), those will have a ref-count of 0 & this will disconnect them

File: src/transport/raw/TCP.cpp (hunk 8 above)
Comment (gmarcosb) [reply src/transport/raw/TCP.cpp:271]: `TCPBase::SendMessage` must be called by someone who owns a TCP connection

Previously, this would create a connection that was unowned & thus could not be collected, i.e. would take up a `mActiveConnections` with no one having a reference to the resulting `ActiveTCPConnectionState`

Also, previously if the connection was `Connecting`, this would create a new connection instead of using the one already connecting

The updated code requires that before we send a message through TCP, the caller must have a reference to the underlying TCP connection either through `TCPBase::TCPConnect` or `TCPBase::ProcessSingleMessage`, so that they can properly release it

File: src/transport/raw/TCP.cpp (hunk 9 above)
Comment (gmarcosb) [reply src/transport/raw/TCP.cpp:298]: No, it is sending a message through a previously-established connection, see comment above - the issue with the code here previously is that we had a dangling `ActiveTCPConnectionState`

File: src/transport/raw/TCP.cpp (hunk 14 above)
Comment (gmarcosb) [reply src/transport/raw/TCP.cpp:401]: `ActiveTCPConnectionState` cannot be null; `CloseConnectionInternal` is guaranteed to be called with a valid active connection

File: src/transport/raw/TCP.cpp (hunk 13 above)
Comment (gmarcosb) [reply src/transport/raw/TCP.cpp:507]: `HandleConnectionAttemptComplete` expects that the receiver will take ownership of the connection - we wrap it in `ActiveTCPConnectionHolder` so that we pre-increment the counter

If the recipient does not take ownership if the connection, we immediately close it

`HandleConnectionClosed`, on the other hand, we don't expect the recipient to take ownership - the connection is already closed, ownership (to later close the connection) is unnecessary

File: src/transport/raw/TCP.h (hunk 4 above)
Comment (gmarcosb) [reply src/transport/raw/TCP.h:212]: Thanks, updated

File: src/transport/raw/TCP.cpp (hunk 10 above)
Comment (gmarcosb) [reply src/transport/raw/TCP.cpp:148]: I'm going to leave it as-is because when we move this to use a Pool, we will just be calling the ctor & we won't need `Init` anymore

File: src/transport/raw/TCP.cpp (hunk 11 above)
Comment (gmarcosb) [reply src/transport/raw/TCP.cpp]: Added a doc

File: src/transport/raw/TCP.cpp [hunk 15]
```diff
@@ -127,21 +145,36 @@ void TCPBase::Close()
...
 }
 
-ActiveTCPConnectionState * TCPBase::AllocateConnection()
+ActiveTCPConnectionState * TCPBase::AllocateConnection(Inet::TCPEndPoint * endpoint, const PeerAddress & address)
 {
-    for (size_t i = 0; i < mActiveConnectionsSize; i++)
+    // If a peer initiates a connection through HandleIncomingConnection but the connection is never claimed
+    // in ProcessSingleMessage, we'll be left with a dangling ActiveTCPConnectionState which can be
+    // reclaimed.  Don't try to reclaim these connections unless we're out of space
+    for (int reclaim = 0; reclaim < 1; reclaim++)
```
[the remark this answers is not in the document]
Comment (gmarcosb) [reply src/transport/raw/TCP.cpp]: Good catch, thanks! Fixed

File: src/transport/raw/tests/TestTCP.cpp [hunk 16]
```diff
@@ -205,10 +231,93 @@ class MockTransportMgrDelegate : public chip::TransportMgrDelegate
...
+            [&](const uint8_t * message, size_t length, int count, ActiveTCPConnectionHolder & conn, void * data) -> CHIP_ERROR {
+                if (memcmp(message, PAYLOAD, length) == 0)
+                {
+                    firstMessageReceived = true;
+
+                    chip::System::PacketBufferHandle firstResponse;
+                    ReturnErrorOnFailure(BufferWithHeader(kMessageCounter + 2, firstResponse, PAYLOAD_RESPONSE));
+
+                    // First message, respond with first response
+                    ReturnErrorOnFailure(tcp.SendMessage(conn, std::move(firstResponse)));
```
Comment (gmarcosb) [inline src/transport/raw/tests/TestTCP.cpp:252]: So, in the test we use this `SendMessage` overload which allows us to pass in a respective connection; but `SessionManager` can't use this, as it's not exposed by `mTransportMgr`

The reason we need it here is because this is a loop-back, and if we didn't specify the connection, we would use the wrong one

Do we care about and want to support the loopback scenario in `SessionManager`?

File: src/protocols/secure_channel/CASESession.h [hunk 17]
```diff
@@ -542,19 +542,17 @@ class DLL_EXPORT CASESession : public Messaging::UnsolicitedMessageHandler,
...
 
 #if INET_CONFIG_ENABLE_TCP_ENDPOINT
-    static void HandleConnectionAttemptComplete(Transport::ActiveTCPConnectionState * conn, CHIP_ERROR conErr);
-    static void HandleConnectionClosed(Transport::ActiveTCPConnectionState * conn, CHIP_ERROR conErr);
+    void HandleConnectionAttemptComplete(Transport::ActiveTCPConnectionHolder & conn, CHIP_ERROR conErr) override;
+    void HandleConnectionClosed(const Transport::ActiveTCPConnectionState & conn, CHIP_ERROR conErr) override;
 
-    // Context to pass down when connecting to peer
-    Transport::AppTCPConnectionCallbackCtxt mTCPConnCbCtxt;
     // Pointer to the underlying TCP connection state. Returned by the
```
Comment (pidarped) [inline src/protocols/secure_channel/CASESession.h]:
```suggestion
    // Reference holder to the underlying TCP connection state. Returned by the
```

File: src/protocols/secure_channel/CASESession.cpp [hunk 18]
```diff
@@ -683,64 +667,42 @@ CHIP_ERROR CASESession::RecoverInitiatorIpk()
...
-    VerifyOrDie(conn->mAppState != nullptr);
+    VerifyOrReturn(conn == mPeerConnState);
 
     char peerAddrBuf[chip::Transport::PeerAddress::kMaxToStringSize];
     conn->mPeerAddr.ToString(peerAddrBuf);
 
-    CASESession * caseSession = reinterpret_cast<CASESession *>(conn->mAppState->appContext);
-    VerifyOrReturn(caseSession != nullptr);
+    auto ConnectionCleanup = [](CASESession * s) {
+        s->mExchangeCtxt.Value()->GetSessionHandle()->AsUnauthenticatedSession()->ReleaseTCPConnection();
```
Comment (pidarped) [inline src/protocols/secure_channel/CASESession.cpp:678]: Recommend adding some documentation here for clarification on the cleanup:
1. The unauthenticated session for the initial message exchange that holds a reference to the connection.
2. The resultant secure session that was established that also holds a reference to the connection.
3. Finally calling Clear() on the CASESession object to release the member reference mPeerConnectionState.

File: src/protocols/secure_channel/CASESession.cpp [hunk 19]
```diff
@@ -683,64 +667,42 @@ CHIP_ERROR CASESession::RecoverInitiatorIpk()
...
+        s->mSecureSessionHolder.Get().Value()->AsSecureSession()->ReleaseTCPConnection();
+        s->Clear();
+    };
+    std::unique_ptr<CASESession, decltype(ConnectionCleanup)> connectionHolder(this, ConnectionCleanup);
```
Comment (pidarped) [inline src/protocols/secure_channel/CASESession.cpp:682]: Some documentation on the lifetime of the local connectionHolder object is necessary, I think. What is its purpose? When it goes out of scope after exiting this function, the custom deleter would be invoked that would perform all the releases. 
How does that impact the underlying connection and mPeerConnState? The following SetTCPConnection(conn) calls would be incrementing the reference counts.

File: src/protocols/secure_channel/CASESession.cpp [hunk 20]
```diff
@@ -683,64 +667,42 @@ CHIP_ERROR CASESession::RecoverInitiatorIpk()
...
 
     // Associate the connection with the current secure session that is being
     // set up.
-    caseSession->mSecureSessionHolder.Get().Value()->AsSecureSession()->SetTCPConnection(conn);
+    mSecureSessionHolder.Get().Value()->AsSecureSession()->SetTCPConnection(conn);
 
     // Send Sigma1 after connection is established for sessions over TCP
-    err = caseSession->SendSigma1();
-    SuccessOrExit(err);
+    LogAndReturnOnFailure(SendSigma1(), SecureChannel, "Sigma1 failed to peer %s", peerAddrBuf);
```
Comment (pidarped) [inline src/protocols/secure_channel/CASESession.cpp:698]: In this model, if there are errors on the SendSigma1(), returning causes the connectionHolder to go out of scope and its deleter is called, right? What happens to the ref count on the TCPConnection objects in that scenario?

File: src/protocols/secure_channel/CASESession.cpp [hunk 21]
```diff
@@ -683,64 +667,42 @@ CHIP_ERROR CASESession::RecoverInitiatorIpk()
...
-        // not holding on to a stale ActiveTCPConnectionState. We call
-        // TCPDisconnect() here explicitly in order to abort the connection
-        // even after it establishes successfully, but SendSigma1() fails for
-        // some reason.
-        caseSession->mSessionManager->TCPDisconnect(conn, /* shouldAbort = */ true);
-        caseSession->mPeerConnState = nullptr;
-
-        caseSession->Clear();
-    }
+    connectionHolder.release();
```
Comment (pidarped) [inline src/protocols/secure_channel/CASESession.cpp:700]: Is this release() the counterpart to the refcount increment during construction? If so, please add a document line atop.

File: src/protocols/secure_channel/CASESession.cpp (hunk 18 above)
Comment (gmarcosb) [reply src/protocols/secure_channel/CASESession.cpp:678]: We're just undoing what we do in this method, documenting that seems like too much

On line 691 & 694, we set these values; if anything goes wrong, we have to cleanup or we leave a dangling reference

This is just regular RAII, localized to this method - I copied the `std::unique_ptr` pattern from TCP.cpp

File: src/protocols/secure_channel/CASESession.cpp (hunk 19 above)
Comment (gmarcosb) [reply src/protocols/secure_channel/CASESession.cpp:682]: This is just good 'ol RAII - I copied the `std::unique_ptr` pattern from TCP.cpp

We set all these values here: `AsUnauthenticatedSession()->SetTCPConnection(conn)` on line 691, `AsSecureSession()->SetTCPConnection(conn)` on line 695; if anything goes wrong in this method, we must undo

File: src/protocols/secure_channel/CASESession.cpp (hunk 20 above)
Comment (gmarcosb) [reply src/protocols/secure_channel/CASESession.cpp:698]: Exactly, and in turn we release the reference to the TCP connection so it can be cleaned up, because this session not being properly established -> we should not hold on to the TCP connection

The old code should've done this, too, it just didn't cleanup after itself & left a dangling TCP connection if sigma1 failed

File: src/protocols/secure_channel/CASESession.cpp (hunk 21 above)
Comment (gmarcosb) [reply src/protocols/secure_channel/CASESession.cpp:700]: This is so the cleanup doesn't run, i.e. RAII is automatically runs (releasing pointers & cleaning up) if anything goes wrong; if we get to this line, everything was successful & we bail on the clean-up

This is the pattern used in TCP.cpp, I just copied it, not sure if there's another well-known RAII mechanism in CHIP

**Review by robszewczyk — APPROVED** [review]

File: src/transport/SessionManager.cpp [hunk 22]
```diff
@@ -743,32 +728,6 @@ CHIP_ERROR SessionManager::TCPConnect(const PeerAddress & peerAddress, Transport
...
-void SessionManager::TCPDisconnect(Transport::ActiveTCPConnectionState * conn, bool shouldAbort)
-{
-    if (mTransportMgr != nullptr && conn != nullptr)
-    {
-        char peerAddrBuf[chip::Transport::PeerAddress::kMaxToStringSize];
-        conn->mPeerAddr.ToString(peerAddrBuf);
-        ChipLogProgress(Inet, "Disconnecting TCP connection from peer at %s.", peerAddrBuf);
-        mTransportMgr->TCPDisconnect(conn, shouldAbort);
-
-        MarkSecureSessionOverTCPForEviction(conn, CHIP_NO_ERROR);
```
Comment (pidarped) [inline src/transport/SessionManager.cpp:769]: Earlier, explicitly calling this TCPDisconnect(conn, ..) also marked the session for eviction. By using the automatic release and invocation of the TCPDisconnect at the transport level is, potentially, missing the marking of the corresponding session for eviction, leaving an active session without any underlying connection.
We would need a way for the TCPDisconnect(..) to signal the SessionManager to mark the session as such.

**Review by pidarped — APPROVED** [review]

File: src/transport/SessionManager.cpp (hunk 22 above)
Comment (gmarcosb) [reply src/transport/SessionManager.cpp:769]: We really should never have been explicitly closing the TCP connection - as we share the connection, no single user should be able to force it closed

If the session is closed organically, say the network dies, then we will continue to have the close callback which automatically marks all sessions for eviction (`HandleConnectionClosed`)

The one exception to this is testing - the easiest way to test that sessions were properly evicted is by forcing the connection closed, which is the reason `TCP_Tests.py` was failing; I added a `ForceDisconnect` to allow us to test for this case, but it really should never be used in production

File: src/transport/raw/tests/TestTCP.cpp (hunk 16 above)
Comment (gmarcosb) [reply src/transport/raw/tests/TestTCP.cpp:252]: Resolving this with https://github.com/project-chip/connectedhomeip/issues/40901 - we can decide whether we want to implement there

**Review by marktrayer — APPROVED** [review]

**Comment by gmarcosb** [comment]
Followup @ https://github.com/project-chip/connectedhomeip/pull/40904 for anyone wanting to do a more thorough review

File: src/lib/support/CodeUtils.h [hunk 23]
```diff
@@ -209,6 +209,58 @@
...
+ *
+ *  Example usage:
+ *
+ *  @code
+ *    LogAndReturnErrorOnFailure(channel->SendMsg(msg), Module, "Failure message: %s", param);
+ *  @endcode
+ *
+ *  @param[in]  expr        A scalar expression to be evaluated against CHIP_NO_ERROR.
+ */
+#define LogAndReturnErrorOnFailure(expr, MOD, MSG, ...)                                                                            \
```
Comment (bzbarsky-apple) [inline src/lib/support/CodeUtils.h:253]: I wonder whether we can convert ReturnLogErrorOnFailure callsites (or even its definition?) to use this.  Not sure it's worth it.

That said, I think emphasizing the return part is fairly important, so maybe this should have been named ReturnAndLogErrorOnFailure?

File: src/messaging/ExchangeDelegate.h [hunk 24]
```diff
@@ -135,6 +135,11 @@ class DLL_EXPORT ExchangeDelegate
     virtual void OnExchangeClosing(ExchangeContext * ec) {}
 
     virtual ExchangeMessageDispatch & GetMessageDispatch() { return ApplicationExchangeDispatch::Instance(); }
+
+#if INET_CONFIG_ENABLE_TCP_ENDPOINT
+    virtual void HandleConnectionAttemptComplete(Transport::ActiveTCPConnectionHolder & conn, CHIP_ERROR conErr){};
+    virtual void HandleConnectionClosed(const Transport::ActiveTCPConnectionState & conn, CHIP_ERROR conErr){};
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeDelegate.h:141]: I do wonder whether it's worth having "TCP" explicitly in the names of the functions here, or whether just having it in the arg types is enough....

Note that having conditional bits like this in a delegate API can lead to interesting problems if somehow compilation of various modules gets out of sync in terms of whether INET_CONFIG_ENABLE_TCP_ENDPOINT is enabled.  But I don't see an obvious way around that here.

File: src/messaging/ExchangeDelegate.h [hunk 25]
```diff
@@ -135,6 +135,11 @@ class DLL_EXPORT ExchangeDelegate
     virtual void OnExchangeClosing(ExchangeContext * ec) {}
 
     virtual ExchangeMessageDispatch & GetMessageDispatch() { return ApplicationExchangeDispatch::Instance(); }
+
+#if INET_CONFIG_ENABLE_TCP_ENDPOINT
+    virtual void HandleConnectionAttemptComplete(Transport::ActiveTCPConnectionHolder & conn, CHIP_ERROR conErr){};
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeDelegate.h:140]: I'm a little suprised the holder here is not const...

File: src/messaging/ExchangeMgr.cpp [hunk 26]
```diff
@@ -453,16 +453,32 @@ void ExchangeManager::CloseAllContextsForDelegate(const ExchangeDelegate * deleg
...
     });
 }
+
+bool ExchangeManager::OnTCPConnectionAttemptComplete(Transport::ActiveTCPConnectionHolder & conn, CHIP_ERROR conErr)
+{
+    bool foundHandler = false;
+    mContextPool.ForEachActiveObject([&](auto * ec) {
+        if (ec->HasSessionHandle())
+        {
+            ec->OnConnectionAttemptComplete(conn, conErr);
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeMgr.cpp:474]: So this can call OnConnectionAttemptComplete on different exchanges with `conn` in different states, because it's not const, right?

File: src/protocols/secure_channel/CASESession.cpp [hunk 27]
```diff
@@ -683,64 +667,42 @@ CHIP_ERROR CASESession::RecoverInitiatorIpk()
...
-    // before calling this callback.
-    VerifyOrDie(conn->mAppState != nullptr);
+    VerifyOrReturn(conn == mPeerConnState);
 
     char peerAddrBuf[chip::Transport::PeerAddress::kMaxToStringSize];
     conn->mPeerAddr.ToString(peerAddrBuf);
 
-    CASESession * caseSession = reinterpret_cast<CASESession *>(conn->mAppState->appContext);
-    VerifyOrReturn(caseSession != nullptr);
+    auto ConnectionCleanup = [](CASESession * s) {
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:677]: I think usually we would use `connectionCleanup` for the instance and starting with a capital letter for a type.

File: src/protocols/secure_channel/CASESession.cpp (hunk 21 above)
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:700]: So naming-wise: connectionHolder is not really holding a connection.  It's conceptually holding an instance of connnection auto-cleanup, and releasing it means not doing the cleanup, right?  

Might be better named connectionAutoCleanup.

File: src/transport/Session.h [hunk 28]
```diff
@@ -300,10 +300,10 @@ class Session
 #if INET_CONFIG_ENABLE_TCP_ENDPOINT
     // This API is used to associate the connection with the session when the
     // latter is about to be marked active. It is also used to reset the
-    // connection to a nullptr when the connection is lost and the session
-    // is marked as Defunct.
-    ActiveTCPConnectionState * GetTCPConnection() const { return mTCPConnection; }
-    void SetTCPConnection(ActiveTCPConnectionState * conn) { mTCPConnection = conn; }
+    // connection when the connection is lost and the session is marked as Defunct.
+    inline const ActiveTCPConnectionHolder & GetTCPConnection() const { return const_cast<Session *>(this)->mTCPConnection; }
```
Comment (bzbarsky-apple) [inline src/transport/Session.h:304]: Why do you need the const_cast here?  You're returning a const ref....

File: src/transport/SessionConnectionDelegate.h [hunk 29]
```diff
@@ -35,12 +40,23 @@ class DLL_EXPORT SessionConnectionDelegate
...
      * @param session       The handle to the secure session
      * @param conErr        The connection error code
      */
-    virtual void OnTCPConnectionClosed(const SessionHandle & session, CHIP_ERROR conErr) = 0;
+    virtual void OnTCPConnectionClosed(const Transport::ActiveTCPConnectionState & conn, const SessionHandle & session,
+                                       CHIP_ERROR conErr) = 0;
+
+    /**
+     * @brief
+     *   Called when the underlying TCP connection attempt for the session is complete. Returns true if handled.
```
Comment (bzbarsky-apple) [inline src/transport/SessionConnectionDelegate.h:54]: What does "handled" mean?  What needs to be handled?  If I were implementing this API, I would have no idea whether to return true or false.

File: src/transport/SessionManager.cpp [hunk 30]
```diff
@@ -668,68 +668,53 @@ void SessionManager::OnMessageReceived(const PeerAddress & peerAddress, System::
...
-    Transport::AppTCPConnectionCallbackCtxt * appTCPConnCbCtxt = conn->mAppState;
-    VerifyOrReturn(appTCPConnCbCtxt != nullptr);
-
-    if (appTCPConnCbCtxt->connClosedCb != nullptr)
+    Transport::AppTCPConnectionCallbackCtxt * appTCPConnCbCtxt = conn.mAppState;
+    if (appTCPConnCbCtxt != nullptr && appTCPConnCbCtxt->connClosedCb != nullptr)
     {
         appTCPConnCbCtxt->connClosedCb(conn, conErr);
     }
+    MarkSecureSessionOverTCPForEviction(conn, conErr);
```
Comment (bzbarsky-apple) [inline src/transport/SessionManager.cpp:713]: Why the ordering change here?  If the order is important, please document why it has to be this order.

File: src/transport/SessionManager.cpp [hunk 31]
```diff
@@ -842,16 +801,17 @@ void SessionManager::UnauthenticatedMessageDispatch(const PacketHeader & partial
...
+        if (sessionConn.IsNull())
         {
             unsecuredSession->SetTCPConnection(ctxt->conn);
         }
         else
         {
             if (sessionConn != ctxt->conn)
             {
-                ChipLogError(Inet, "Data received over wrong connection %p. Dropping it!", ctxt->conn);
+                ChipLogError(Inet, "Unauthenticated data received over %p for wrong connection %p. Dropping it!",
```
Comment (bzbarsky-apple) [inline src/transport/SessionManager.cpp:813]: This new log line is not making sense to me.  The message was received over ctxt->conn, no?  sessionConn is where we were _expecting_ to get data for this session... and didn't.

Should be something more like `Unauthenticated data received over TCP connection %p instead of %p` and reverse the order of the arguments being passed for those `%p`?

File: src/transport/SessionManager.cpp [hunk 32]
```diff
@@ -930,16 +890,17 @@ void SessionManager::SecureUnicastMessageDispatch(const PacketHeader & partialPa
...
+        if (sessionConn.IsNull())
         {
             secureSession->SetTCPConnection(ctxt->conn);
         }
         else
         {
             if (sessionConn != ctxt->conn)
             {
-                ChipLogError(Inet, "Data received over wrong connection %p. Dropping it!", ctxt->conn);
+                ChipLogError(Inet, "Unicast data received over %p for wrong connection %p. Dropping it!",
```
Comment (bzbarsky-apple) [inline src/transport/SessionManager.cpp:902]: See above.

File: src/transport/SessionManager.cpp [hunk 33]
```diff
@@ -1349,12 +1310,9 @@ void SessionManager::MarkSecureSessionOverTCPForEviction(Transport::ActiveTCPCon
             // closure.
             if (mConnDelegate != nullptr)
             {
-                mConnDelegate->OnTCPConnectionClosed(handle, conErr);
+                mConnDelegate->OnTCPConnectionClosed(conn, handle, conErr);
             }
 
-            // Dis-associate the connection from session by setting it to a
-            // nullptr.
-            session->SetTCPConnection(nullptr);
```
Comment (bzbarsky-apple) [inline src/transport/SessionManager.cpp:1357]: So this is now supposed to be handled by mConnDelegate?

File: src/transport/TransportMgrBase.cpp [hunk 34]
```diff
@@ -99,58 +89,33 @@ void TransportMgrBase::HandleMessageReceived(const Transport::PeerAddress & peer
...
-        Transport::TCPBase * tcp = reinterpret_cast<Transport::TCPBase *>(conn->mEndPoint->mAppState);
-
-        // Close connection here since no upper layer is interested in the
-        // connection.
-        if (tcp)
-        {
-            tcp->TCPDisconnect(conn, /* shouldAbort = */ true);
-        }
+        // Close connection here since no upper layer is interested in the connection.
+        Transport::ActiveTCPConnectionHolder releaseConnection(&conn);
```
Comment (bzbarsky-apple) [inline src/transport/TransportMgrBase.cpp:101]: It's really not obvious why this ends up closing the connection.  ActiveTCPConnectionHolder retains in its constructor... so is this relying on `conn` having a zero refcount before this line and then this going out of scope destroying it?  It seems weird to destroy something the caller is clearly referencing.  Would it not be better if this ActiveTCPConnectionHolder were in the caller, and then if no one takes a holder to the connection it would go away once that holder goes out of scope?

File: src/transport/raw/TCP.cpp [hunk 35]
```diff
@@ -127,21 +145,36 @@ void TCPBase::Close()
...
+                activeConnection->Init(endpoint, address, [this](auto & conn) { TCPDisconnect(conn, true); });
+                return activeConnection;
+            }
         }
-    }
 
+        // Out of space; reclaim connections that were never claimed by ProcessSingleMessage
+        for (size_t i = 0; i < mActiveConnectionsSize; i++)
+        {
+            ActiveTCPConnectionHolder releaseUnclaimed(&mActiveConnections[i]);
```
Comment (bzbarsky-apple) [inline src/transport/raw/TCP.cpp:170]: So this will reclaim things that currently have a 0 refcount, basically?  Might be worth documenting that.

File: src/protocols/secure_channel/CASESession.cpp (hunk 20 above)
Comment (samadDotDev) [inline src/protocols/secure_channel/CASESession.cpp:698]: I have called this out in the follow up PR so I'll just leave this here for reference: I think we might need to propagate the error in case of these failures which was missed previously as well but the refactor of cleanup into a closure makes it tricky to time the cleanup before error propagation: https://github.com/project-chip/connectedhomeip/pull/40904#discussion_r2337896088

File: src/transport/SessionManager.cpp (hunk 30 above)
Comment (gmarcosb) [reply src/transport/SessionManager.cpp:713]: Ordering not important - I originally deleted the top blurb, then echo tests were failing, and I added it back in 😅

Didn't realize I added it in wrong order, apologies

File: src/transport/SessionManager.cpp (hunk 31 above)
Comment (gmarcosb) [reply src/transport/SessionManager.cpp:813]: Sorry I just tweaked the message so it's not the same as the other (same log text used twice in this file) & based it on the method name, `UnauthenticatedMessageDispatch` - this was just so that during debugging it would be clear where this is being logged 😅

File: src/transport/SessionManager.cpp (hunk 32 above)
Comment (gmarcosb) [reply src/transport/SessionManager.cpp:902]: Similar thing, error log was duplicated in 2 places & I simply went by the method name where we were logging this, `SecureUnicastMessageDispatch`, so that it'd be easier to find culprit logging line in code

File: src/transport/SessionManager.cpp (hunk 31 above)
Comment (bzbarsky-apple) [reply src/transport/SessionManager.cpp:813]: My point is that the new text does not make sense.

File: src/transport/SessionManager.cpp (hunk 32 above)
Comment (bzbarsky-apple) [reply src/transport/SessionManager.cpp:902]: Same thing: the issue is that the new message is misleading in a way the old one was not.

File: src/lib/support/CodeUtils.h (hunk 23 above)
Comment (gmarcosb) [reply src/lib/support/CodeUtils.h:253]: Was thinking about order of operations, but agreed on emphasizing the return

As for converting `ReturnLogErrorOnFailure`... continued @ https://github.com/project-chip/connectedhomeip/pull/40904/files#r2402876980

File: src/messaging/ExchangeDelegate.h (hunk 24 above)
Comment (gmarcosb) [reply src/messaging/ExchangeDelegate.h:141]: I like to err on the side of smaller method names if the context is already captured elsewhere, e.g. params, as it is here

As for out-of-sync for TCP, agreed, but is the pattern followed throughout for TCP, e.g. `DnssdServer` - in the case where TCP is half-enabled, i.e. in some modules but not in others, I think it's going to get ugly with crashes & there's no getting around that

File: src/messaging/ExchangeDelegate.h (hunk 25 above)
Comment (gmarcosb) [reply src/messaging/ExchangeDelegate.h:140]: Yeah I kinda went back-and-forth on whether or not to make it const 😅 It got kinda ugly because we then allow copying from a const to a non-const, i.e. a const handle no longer implies a const connection, yay const-correctness

Updating these to const in follow-up

File: src/messaging/ExchangeMgr.cpp (hunk 26 above)
Comment (gmarcosb) [reply src/messaging/ExchangeMgr.cpp:474]: Yeah good point, cleaner with a const - at the start I was trying to preserve the idea of "const Holder == const TCP connection", but that went out the door & this ended up being more like a const pointer with no ability to have pointer to a const

File: src/transport/raw/TCP.cpp (hunk 35 above)
Comment (gmarcosb) [reply src/transport/raw/TCP.cpp:170]: Expanded on comment in line 167 in follow-up

File: src/transport/TransportMgrBase.cpp (hunk 34 above)
Comment (gmarcosb) [reply src/transport/TransportMgrBase.cpp:101]: Resolved @ https://github.com/project-chip/connectedhomeip/pull/40904/files#r2402926106

File: src/transport/SessionManager.cpp (hunk 33 above)
Comment (gmarcosb) [reply src/transport/SessionManager.cpp:1357]: No, by `MarkForEviction` below - i.e. when session is actually collected when refCount == 0, it'll clear out its tcp connection decrementing the ref

File: src/transport/SessionManager.cpp (hunk 31 above)
Comment (gmarcosb) [reply src/transport/SessionManager.cpp:813]: Ah got it, fixed in follow-up

File: src/transport/SessionManager.cpp (hunk 32 above)
Comment (gmarcosb) [reply src/transport/SessionManager.cpp:902]: Fixed in follow-up

File: src/transport/SessionConnectionDelegate.h (hunk 29 above)
Comment (gmarcosb) [reply src/transport/SessionConnectionDelegate.h:54]: Updated text in follow-up

File: src/transport/Session.h (hunk 28 above)
Comment (gmarcosb) [reply src/transport/Session.h:304]: Fixed in follow-up

File: src/protocols/secure_channel/CASESession.cpp (hunk 21 above)
Comment (gmarcosb) [reply src/protocols/secure_channel/CASESession.cpp:700]: Addressed in follow-up

File: src/protocols/secure_channel/CASESession.cpp (hunk 27 above)
Comment (gmarcosb) [reply src/protocols/secure_channel/CASESession.cpp:677]: This is no longer necessary in follow-up with `ScopeExit`
