### PR TITLE
[Infineon]Update button init sequence before wifi commissioning

### LINKED ISSUE #29611: [BUG] [1.1] [Infineon] [PSoC6] cannot finish commissioning
### Reproduction steps

PSoC6 cannot finish commissioning.
It stacked in WiFi setting process on commissioning.

When PSoC6 got this situation, it cannot be Factory Reset.
WiFi process blocked.

```bash
./chip-tool pairing ble-wifi 1234 $SSID $PASSWORD 20202021 3840
```

[infineon-lighting-app-20231004.txt](https://github.com/project-chip/connectedhomeip/files/12826817/infineon-lighting-app-20231004.txt)

> CHIP:DL: WiFi station mode change: Disabled -> Enabled
> CHIP:DMG: Decreasing reference count for CommandHandler, remaining 1
> CHIP:DL: Starting P6 WiFi layer
> CHIP:DL: EnableStationMode
> CHIP:DL: WiFi station state change: NotConnected -> Connecting
> CHIP:DL: Attempting to connect WiFi station interface
> CHIP:DL: Connecting to AP : [WIFIAP_SSID] 
> 
> CHIP:DL: Write received for CHIPoBLE RX characteristic con:8000 handle:000c len2
> CHIP:DL: CHIPoBLE unsubscribe received
> CHIP:DL: BLE GATT connection closed (con 32768, reason 19)

[chip-tool-20231004.txt](https://github.com/project-chip/connectedhomeip/files/12826816/chip-tool-20231004.txt)

> [1696563218.555536][150802:150802] CHIP:CTL: Shutting down the commissioner
> [1696563218.555556][150802:150802] CHIP:CTL: Shutting down the controller
> [1696563218.555561][150802:150802] CHIP:CTL: Shutting down the System State, this will teardown the CHIP Stack
> [1696563218.555649][150802:150802] CHIP:DMG: All ReadHandler-s are clean, clear GlobalDirtySet
> [1696563218.555688][150802:150802] CHIP:FP: Shutting down FabricTable
> [1696563218.555691][150802:150802] CHIP:TS: Pending Last Known Good Time: 2023-10-06T09:30:35
> [1696563218.555705][150802:150802] CHIP:TS: Previous Last Known Good Time: 2023-10-06T09:30:35
> [1696563218.555711][150802:150802] CHIP:TS: Reverted Last Known Good Time to previous value
> [1696563218.555955][150802:150802] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-zeQqRA)
> [1696563218.556216][150802:150802] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
> [1696563218.556233][150802:150802] CHIP:DL: NVS set: chip-counters/total-operational-hours = 0 (0x0)
> [1696563218.556237][150802:150802] CHIP:DL: Inet Layer shutdown
> [1696563218.556240][150802:150802] CHIP:DL: BLE shutdown
> [1696563218.556558][150802:150802] CHIP:DL: System Layer shutdown
> [1696563218.556879][150802:150802] CHIP:TOO: Run command failure: src/app/CommandSender.cpp:271: CHIP Error 0x00000032: Timeout

### Bug prevalence

always

### GitHub hash of the SDK that was being used

commit 8f66f4215bc0708efc8cc73bda80620e67d8955f (HEAD, tag: v1.1.0.1)

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by praveenCY**
Fixes https://github.com/project-chip/connectedhomeip/issues/29611

- Support button init before wifi commissioning sequence in-order to do factory reset during error scenarios.
- call starttimer using schedulelamba as it was causing chipDie during wifi connect retry sequences (if wifi password is wrong)

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

File: src/platform/Infineon/PSOC6/ConnectivityManagerImpl.cpp [hunk 1]
```diff
@@ -446,10 +446,18 @@ void ConnectivityManagerImpl::DriveAPState()
...
                 // arm a timer to fire at that time.
                 System::Clock::Timeout apTimeout = (mLastAPDemandTime + mWiFiAPIdleTimeout) - now;
-                err                              = DeviceLayer::SystemLayer().StartTimer(apTimeout, DriveAPState, nullptr);
-                SuccessOrExit(err);
                 ChipLogProgress(DeviceLayer, "Next WiFi AP timeout in %" PRIu32 " ms",
                                 System::Clock::Milliseconds32(apTimeout).count());
+                SystemLayer().ScheduleLambda([apTimeout, this] {
+                    CHIP_ERROR ret = CHIP_NO_ERROR;
+                    ret            = DeviceLayer::SystemLayer().StartTimer(apTimeout, DriveAPState, this);
+                    SuccessOrExit(ret);
```
Comment (arkq) [inline src/platform/Infineon/PSOC6/ConnectivityManagerImpl.cpp:454]: This `SuccessOrExit` is redundant here if you are checking `if (ret != CHIP_NO_ERROR)` 2 lines below. For readability maybe it's better to use:
```c++
VerifyOrReturn(ret != CHIP_NO_ERROR, ChipLogError(NotSpecified, "StartTimer failed %s: ", chip::ErrorStr(ret)));
```

The same thing with lambda below.

**Review by arkq — APPROVED** [review]

File: src/platform/Infineon/PSOC6/ConnectivityManagerImpl.cpp (hunk 1 above)
Comment (praveenCY) [reply src/platform/Infineon/PSOC6/ConnectivityManagerImpl.cpp]: @arkq  : thanks for the review. I have updated the code.

**Comment by praveenCY** [comment]
@woody-apple  @bzbarsky-apple  : Can you please review and merge ?
