### PR TITLE
[OpenThread] Revert configuration on boot with fail-safe armed

### LINKED ISSUE #21543: [Thread] OpenThread configuration is not reverted on reboot when fail-safe is armed.
#### Problem
Previously, the network commissioning driver's `RevertConfiguration` method was automatically called after a reboot with the fail-safe armed.
After https://github.com/project-chip/connectedhomeip/pull/20010/, the fail-safe cleanup on boot is only done when the fail-safe marker has been saved into KVS, which happens at the beginning of `CommissioningComplete` command handler.

 #### Proposed Solution
Call `RevertConfiguration` on boot manually in the generic Thread driver.

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
After recent changes related to the fail-safe commit marker persistence RevertConfiguration() is no longer called by the common code when the device reboots with the fail-safe armed.
Due to the nature of OpenThread API, all network credential changes are persistent, so an explicit revert is needed in such a case.

#### Change overview
Add explicit revert on the driver initialization.
By the way, remove the workaround for KVS not being able to store empty values as the scenario has already been verified by the storage audit.
Fixes #21543

#### Testing
Verified certain fail-safe scenarios on nRF Connect Lock:
- commissioning using a wrong Thread dataset + waiting for the fail-safe timeout => removed the dataset
- commissioning using a wrong Thread dataset + reboot => removed the dataset
- changing the Thread dataset to invalid one + waiting for the fail-safe timeout => restored the previous dataset
- changing the Thread dataset to invalid one + reboot => restored the previous dataset

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by tcarmelveilleux — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]

File: src/platform/OpenThread/GenericNetworkCommissioningThreadDriver.cpp [hunk 1]
```diff
@@ -86,23 +84,15 @@ CHIP_ERROR GenericThreadDriver::RevertConfiguration()
...
-    if (dataset.data_equal(ByteSpan(kEmptyDataset)))
-    {
-        dataset = {};
-    }
+    // Always remove the backup, regardless if it can be successfully restored.
+    KeyValueStoreMgr().Delete(key.FailSafeNetworkConfig());
+    ReturnErrorOnFailure(error);
 
-    ReturnErrorOnFailure(mStagingNetwork.Init(dataset));
+    ReturnErrorOnFailure(mStagingNetwork.Init(ByteSpan(datasetBytes, datasetLength)));
```
Comment (bzbarsky-apple) [inline src/platform/OpenThread/GenericNetworkCommissioningThreadDriver.cpp:92]: If we reboot again between the delete and the `mStagingNetwork.Init` call, won't that lose our fail-safe recovery.

It seems to me like the delete should still be the last thing here, but should be done even if the previous steps failed, as long as we _tried_ those steps.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/platform/OpenThread/GenericNetworkCommissioningThreadDriver.cpp (hunk 1 above)
Comment (Damian-Nordic) [reply src/platform/OpenThread/GenericNetworkCommissioningThreadDriver.cpp]: Good point. Reworked according to your suggestion.
