### PR TITLE
Fix initialization of device instance info providers on POSIX.

### LINKED ISSUE #21139: `all-clusters-app` not correctly taking `--vendor-id` input into QR code generation
#### Problem
When running `./out/all-clusters-app/chip-all-clusters-app --vendor-id 6524` the `chip-all-clusters-app` does not change the value of the `--vendor-id` from the default `65521` to `6524 ` when displaying the QR/ Manual codes for pairing the sample accessory. Additionally, after the device is paired, the `--vendor-id` is still not reflected in `./darwin-framework-tool basic read vendor-id 1 0`

 #### Proposed Solution
Have all-clusters-app take the input given in the `--vendor-id` argument and use it in the app.

#### Logs
```
[1658520516.778673][2328:2328] CHIP:DL: NVS set: chip-factory/vendor-id = 6524 (0x197C)
[1658520516.778746][2328:2328] CHIP:DL: Device Configuration:
[1658520516.778827][2328:2328] CHIP:DL:   Serial Number: TEST_SN
[1658520516.778891][2328:2328] CHIP:DL:   Vendor Id: 65521 (0xFFF1)
[1658520516.778944][2328:2328] CHIP:DL:   Product Id: 32769 (0x8001)
[1658520516.779153][2328:2328] CHIP:DL:   Hardware Version: 0
[1658520516.779229][2328:2328] CHIP:DL:   Setup Pin Code (0 for UNKNOWN/ERROR): 20202021
[1658520516.779273][2328:2328] CHIP:DL:   Setup Discriminator (0xFFFF for UNKNOWN/ERROR): 3840 (0xF00)
[1658520516.779392][2328:2328] CHIP:DL:   Manufacturing Date: (not set)
[1658520516.779447][2328:2328] CHIP:DL:   Device Type: 65535 (0xFFFF)
[1658520516.779528][2328:2328] CHIP:-: ==== Onboarding payload for Standard Commissioning Flow ====
[1658520516.779598][2328:2328] CHIP:SVR: SetupQRCode: [MT:-24J0AFN00KA0648G00]
[1658520516.779651][2328:2328] CHIP:SVR: Copy/paste the below URL in a browser to see the QR Code:
[1658520516.779695][2328:2328] CHIP:SVR: https://project-chip.github.io/connectedhomeip/qrcode.html?data=MT%3A-24J0AFN00KA0648G00
[1658520516.779752][2328:2328] CHIP:SVR: Manual pairing code: [34970112332]
[1658520516.779798][2328:2328] CHIP:-: ==== Onboarding payload for Custom Commissioning Flows ====
[1658520516.779857][2328:2328] CHIP:SVR: SetupQRCode: [MT:-24J029Q00KA0648G00]
[1658520516.779910][2328:2328] CHIP:SVR: Copy/paste the below URL in a browser to see the QR Code:
[1658520516.779954][2328:2328] CHIP:SVR: https://project-chip.github.io/connectedhomeip/qrcode.html?data=MT%3A-24J029Q00KA0648G00
[1658520516.780011][2328:2328] CHIP:SVR: Manual pairing code: [749701123365521327694]
```
Using **SetupQRCode: [MT:-24J0AFN00KA0648G00]** from log above: 
```
$ ./chip-tool payload parse-setup-payload MT:-24J0AFN00KA0648G00
[1658533677613] [20597:5106998] CHIP: [SPL] Parsing base38Representation: MT:-24J0AFN00KA0648G00
[1658533677614] [20597:5106998] CHIP: [SPL] Version:       0
[1658533677614] [20597:5106998] CHIP: [SPL] VendorID:      65521
[1658533677614] [20597:5106998] CHIP: [SPL] ProductID:     32769
[1658533677614] [20597:5106998] CHIP: [SPL] Custom flow:   0    (STANDARD)
[1658533677614] [20597:5106998] CHIP: [SPL] Capabilities:  0x04 (On IP network)
[1658533677614] [20597:5106998] CHIP: [SPL] Discriminator: 3840
[1658533677614] [20597:5106998] CHIP: [SPL] Passcode:      20202021
```
[all-clusters-app Invalid Vendor-ID Logs.txt](https://github.com/project-chip/connectedhomeip/files/9172721/all-clusters-app.Invalid.Vendor-ID.Logs.txt)

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
GenericConfigurationManagerImpl::Init sets up a generic device
instance info provider, which was overriding the platform-specific
ones that were being set in various places.

Fixes https://github.com/project-chip/connectedhomeip/issues/21139

#### Problem
We're ending up with the wrong device instance info provider.

#### Change overview
Fix that.

#### Testing
Made sure that on Darwin the `--vendor-id` and `--product-id` args for the example apps work again.

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

File: src/platform/Linux/PlatformManagerImpl.cpp [hunk 1]
```diff
@@ -175,12 +175,15 @@ CHIP_ERROR PlatformManagerImpl::_InitChipStack()
...
     // Initialize the configuration system.
     ReturnErrorOnFailure(Internal::PosixConfig::Init());
-    SetDeviceInstanceInfoProvider(&DeviceInstanceInfoProviderMgrImpl());
 
     // Call _InitChipStack() on the generic implementation base class
     // to finish the initialization process.
     ReturnErrorOnFailure(Internal::GenericPlatformManagerImpl_POSIX<PlatformManagerImpl>::_InitChipStack());
 
+    // Now set up our device instance info provider.  We couldn't do that
+    // earlier, because the generic implementation sets a generic one.
```
Comment (tcarmelveilleux) [inline src/platform/Linux/PlatformManagerImpl.cpp:184]: The problem is the "generic implementation" setting a "generic one" (which cannot properly be right). We should move the device instance info provider to the Server and have a getter for it.

Comment (bzbarsky-apple) [reply src/platform/Linux/PlatformManagerImpl.cpp:184]: I absolutely agree.  I'm just trying to unblock https://github.com/project-chip/connectedhomeip/issues/21139 without rewriting the whole thing in the process because I don't have time for that right this second and because I am not quite sure what shape the rewrite would have....

Comment (bzbarsky-apple) [reply src/platform/Linux/PlatformManagerImpl.cpp:184]: Ideally, this stuff would not use configuration manager at all, by the way.

**Review by woody-apple — APPROVED** [review]
