### PR TITLE
[Tizen] Fix ipv6 link local interface issue

### LINKED ISSUE #22889: [Platform] CASE session with ipv6 does not work
### Reproduction steps

```bash
commissioning does not work during CASE session with ipv6.
```

### Platform

other

### Platform Version(s)

_No response_

### Type

Unit tested

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by wootak-jung**
#### Issue Being Resolved
* Fixes #22889 

#### Change overview
Adds ipv6 link local interface

Signed-off-by: kibak.yoon <kibak.yoon@samsung.com>
Signed-off-by: Wootak Jung <wootak.jung@samsung.com>

### CODE REVIEW

**Review by arkq — APPROVED** [review]

File: src/platform/Tizen/DnssdImpl.cpp [hunk 1]
```diff
@@ -352,6 +354,14 @@ void OnResolve(dnssd_error_e result, dnssd_service_h service, void * data)
 
     dnssdService.mPort = static_cast<uint16_t>(port);
 
+    ret = dnssd_service_get_interface(service, &interface);
+    VerifyOrExit(ret == DNSSD_ERROR_NONE, ChipLogError(DeviceLayer, "dnssd_service_get_interface() failed. ret: %d", ret));
+
+    err = chip::Inet::InterfaceId::InterfaceNameToId(interface, dnssdService.mInterface);
+    VerifyOrExit(
+        err == CHIP_NO_ERROR,
+        ChipLogError(DeviceLayer, "chip::Inet::InterfaceId::InterfaceNameToId() failed. ret: %" CHIP_ERROR_FORMAT, err.Format()));
```
Comment (msandstedt) [inline src/platform/Tizen/DnssdImpl.cpp:363]: This path is passing `ret`==`DNSSD_ERROR_NONE` to `rCtx->mCallback(rCtx->mCbContext, nullptr, chip::Span<chip::Inet::IPAddress>(), GetChipError(ret));` at the `exit:` label.

Comment (Arkq) [reply src/platform/Tizen/DnssdImpl.cpp:363]: Good catch! I've missed that...

Comment (wootak-jung) [reply src/platform/Tizen/DnssdImpl.cpp:363]: Thank you for your detail review! I updated it.

**Review by msandstedt — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
