### PR TITLE
[Android-DD-3.14] Add QR / Manual invaild value check

### LINKED ISSUE #22553: [BUG] Update invalid QR code check for android
### Reproduction steps

```bash
This is a manual bug creation for #22357

Android does not implement SetupPayload validation.
```

### Bug prevalence

Testing DD-3-14 on Android

### GitHub hash of the SDK that was being used

N/A

### Platform

android

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by joonhaengHeo**
#### Problem
What is being fixed?  Examples:
* In Android Platform, DD-3.14 test case is failed.
* In Android can't check SetupPayload value check.

#### Change overview
Add SetupPayload check routine.

Fixes #22553

#### Testing
How was this tested? (at least one bullet point required)
* Run DD-3.14 Test Case.
* Commissioning Test, Read basic cluster attribute.

### CODE REVIEW

File: src/setup_payload/java/SetupPayloadParser-JNI.cpp [hunk 1]
```diff
@@ -40,7 +40,7 @@ jint JNI_OnLoad(JavaVM * jvm, void * reserved)
     return JNI_VERSION_1_6;
 }
 
-JNI_METHOD(jobject, fetchPayloadFromQrCode)(JNIEnv * env, jobject self, jstring qrCodeObj)
+JNI_METHOD(jobject, fetchPayloadFromQrCode)(JNIEnv * env, jobject self, jstring qrCodeObj, jboolean isAllowInvalidPayload)
```
Comment (andy31415) [inline src/setup_payload/java/SetupPayloadParser-JNI.cpp:43]: isAllowInvalidPayload is a strange name. `acceptInvalidPayloads` or `allowInvalidPayload` or similar sounds better.

What does it mean to allow an invalid payload?

please ad some documentation for this method.

Comment (andy31415) [reply src/setup_payload/java/SetupPayloadParser-JNI.cpp:43]: or maybe `validatePayload`

**Comment by andy31415** [comment]
Accepted for 1.0: platform specific change (android/java)

File: src/setup_payload/java/SetupPayloadParser-JNI.cpp (hunk 1 above)
Comment (joonhaengHeo) [reply src/setup_payload/java/SetupPayloadParser-JNI.cpp]: I changed to allowInvalidPayload and adding some comments.

File: src/setup_payload/java/src/chip/setuppayload/SetupPayloadParser.java [hunk 2]
```diff
@@ -4,14 +4,37 @@
...
+  public SetupPayload parseQrCode(String qrCodeString)
+      throws UnrecognizedQrCodeException, SetupPayloadException {
+    return fetchPayloadFromQrCode(qrCodeString, false);
+  }
+
+  /**
+   * Returns {@link SetupPayload} parsed from the QR code string.
+   *
+   * @param qrCodeString the QRCode for commissioning device.
+   * @param allowInvalidPayload Allow invalid payload components.
```
Comment (andy31415) [inline src/setup_payload/java/src/chip/setuppayload/SetupPayloadParser.java:16]: Please provide examples. It is obvious that 'allowInvalidPayload' 'allows invalid payloads'.
The documentation should explain non-obvious things. like what is an invalid payload? why would one allow it? What is the return value if the payload is invalid but allowed? are any payloads allowed when this is true?

Comment (joonhaengHeo) [reply src/setup_payload/java/src/chip/setuppayload/SetupPayloadParser.java]: Added additional description.
This value is added for the same purpose as chiptool's "--allow-invalid-payload" option. In the case of the Android platform, since commissioning is performed after parsing the pairing code, both cases are considered necessary. (I think it is necessary for the user to only parse the QR Code / Manual Pairing Code.)

File: src/setup_payload/java/src/chip/setuppayload/SetupPayloadParser.java [hunk 3]
```diff
@@ -4,14 +4,39 @@
...
+      throws UnrecognizedQrCodeException, SetupPayloadException {
+    return fetchPayloadFromQrCode(qrCodeString, false);
+  }
+
+  /**
+   * Returns {@link SetupPayload} parsed from the QR code string.
+   *
+   * @param qrCodeString the QRCode for commissioning device.
+   * @param allowInvalidPayload Allow invalid payload components. If this value is true, payload
+   *     element validation is not checked. (See detail 5.1.3 in Matter Spec.)
```
Comment (andy31415) [inline src/setup_payload/java/src/chip/setuppayload/SetupPayloadParser.java:17]: Please don't force me to just read the 5.1.3. Documentation that just says "read another documentation" is not friendly.

It is ok to point to it for full reference, but give me a TLDR variant here. Like packed binary structure should contain things like version,vendor and product id. This will not validate it.

Even after reading 5.1.3 I still do not know what `parseQrCode` will do with an invalid payload:
  - if the payload is invalid, what gets put in SetupPayload? Empty? Just accepting invalid values?
  - what is the element validation? Version? Range for vendor/product? Others?
  - will this even accept overly short payloads? what if a payload is 8 bits - 3 are for version 5 for vendor (?) ... is that even valid? what gets placed into vendor?
  
  Generally for me a "allow invalid data" with a returned parsed content sounds very vague and unclear. Unless SetupPayload does not contain the Onbarding payload bits.
  
  Please explain in the documentation.

**Review by andy31415 — CHANGES_REQUESTED** [review]
Changes requested: I keep asking for usable developer documentations on methods, get only quick passes. 

Keeping this as "changes requested" until we have reasonable developer-friendly description of the API. This is required because a "allow invalid data" together with  a "this is the parsed form of the data" is very unusual - how can one parse and make sense of invalid data.

it is doable, but really needs documentation.

**Comment by joonhaengHeo** [comment]
@andy31415 
I'm confused as to whether I need to write additional information because this API is unlikely to be used for what you requested, or if I need two APIs but need a detailed explanation. Please let me know you mean list all invalid cases and  explain what value is returned in invalid case.

File: src/setup_payload/java/src/chip/setuppayload/SetupPayloadParser.java (hunk 3 above)
Comment (joonhaengHeo) [reply src/setup_payload/java/src/chip/setuppayload/SetupPayloadParser.java]: 1. Added a phrase that an exception is throwing when an invalid element is included.
2. Content about invalid element cannot be written here, so it has been added to SetupPayload.java. And, added a phrase to refer to SetupPayload in the API document.

File: src/setup_payload/java/src/chip/setuppayload/SetupPayloadParser.java [hunk 4]
```diff
@@ -3,15 +3,50 @@
...
+    return fetchPayloadFromManualEntryCode(entryCodeString, false);
+  }
+
+  /**
+   * Returns {@link SetupPayload} parsed from the manual entry code string.
+   *
+   * @param entryCodeString the manual Pairing Code for commissioning device.
+   * @param allowInvalidPayload Allow invalid payload components. If this value is true, payload
+   *     element validation is not checked. Refer to {@link SetupPayload} for the description of the
+   *     invalid element.
```
Comment (andy31415) [inline src/setup_payload/java/src/chip/setuppayload/SetupPayloadParser.java:45]: Consider saying that the payload must still parse correctly, but this skips validation of the content past parsing (i.e. it does not validate ranges for individual elements).

**Review by andy31415 — APPROVED** [review]

File: src/setup_payload/java/src/chip/setuppayload/SetupPayloadParser.java (hunk 4 above)
Comment (joonhaengHeo) [reply src/setup_payload/java/src/chip/setuppayload/SetupPayloadParser.java:49]: I checked. Add your comment in this code.
