### PR TITLE
Fix tv-casting-app implementation of commissioner discovery/resolution

### LINKED ISSUE #23786: [BUG] tv-casting-app: Unable to resolve in case of multiple on-network commissioners
### Reproduction steps

```bash
1. Advertise two commissioners on the network over DNS-SD, using two instances of the tv-app or mock them using the dns-sd utility on mac:
>dns-sd -R DD200C20D25AE5F7 _matterd._udp,_V123,_T35 . 33333 VP=123+456 DT=35 DN="Living Room TV"
>dns-sd -R ED200C20D25AE5F7 _matterd._udp,_V123,_T35 . 33333 VP=123+456 DT=35 DN="Family Room TV"

2. Open the Android tv-casting-app which auto-triggers commissioner discovery.

3. Cannot resolve either commissioner, although it does find both on the network.

See logs below:

11-22 22:47:47.203 D/NsdDiscoveryListener( 1552): Service discovery success. name: 0FD017BAB3ACDAAE, type: _matterd._udp., host: null, port: 0, network: 101, txtRecord: 
11-22 22:47:47.203 D/NsdManagerResolverAvailState( 1552): Found NsdManager Resolver free, using it and marking it as busy
11-22 22:47:47.204 D/NsdDiscoveryListener( 1552): Service discovery success. name: E27BFA1C915810BA, type: _matterd._udp., host: null, port: 0, network: 101, txtRecord: 
11-22 22:47:47.204 D/NsdManagerResolverAvailState( 1552): Found NsdManager Resolver busy, waiting
```

### Bug prevalence

Everytime with the above steps to repro

### GitHub hash of the SDK that was being used

8f1136db1dfcf6387c2b796e8c7d20330ded77e3

### Platform

android

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sharadb-amazon**
Fixes #23786

#### Problem
The tv-casting-app's implementation of the commissioner discovery / resolution gets deadlocked when more than 1 commissioner video players are on the network.

#### Change summary
In this change, we run the resolution (and do the preceeding locking) in a separate thread rather than the one the NsdManager is calling back on, onServiceFound.

Also, in this PR, a small bug fix (typo) where the darwin MatterTvCastingBridge.Framework was checking for mSetupDiscriminator instead of mSpake2pIterationCount in the implementation of GetSpake2pIterationCount

#### Testing
Verified the fix using the sample tv-casting-app running discovery against 2 commissioners being advertised on network.

### CODE REVIEW

File: examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/NsdDiscoveryListener.java [hunk 1]
```diff
@@ -58,24 +59,33 @@ public void onDiscoveryStarted(String regType) {
...
-              deviceTypeFilter,
-              preCommissionedVideoPlayers,
-              successCallback,
-              failureCallback,
-              nsdManagerResolverAvailState,
-              1));
-    } else {
-      Log.d(TAG, "Ignoring discovered service: " + service.toString());
-    }
+    Executors.newSingleThreadExecutor()
```
Comment (chrisdecenzo) [inline examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/NsdDiscoveryListener.java:62]: is it efficient to create a new Executor each time rather than running this in an executor belonging to the class or instance?

File: examples/tv-casting-app/darwin/TvCasting/TvCasting/TvCastingApp.swift [hunk 2]
```diff
@@ -38,6 +38,12 @@ struct TvCastingApp: App {
                         }
                         appParameters.rotatingDeviceIdUniqueId = Data(rotatingDeviceIdUniqueId)
                         
+                        let onboardingParameters: OnboardingPayload = OnboardingPayload()
+                        onboardingParameters.setupPasscode = 20202021
```
Comment (chrisdecenzo) [inline examples/tv-casting-app/darwin/TvCasting/TvCasting/TvCastingApp.swift:42]: are these defaults?

**Review by chrisdecenzo — APPROVED** [review]

File: examples/tv-casting-app/darwin/TvCasting/TvCasting/TvCastingApp.swift (hunk 2 above)
Comment (sharadb-amazon) [reply examples/tv-casting-app/darwin/TvCasting/TvCasting/TvCastingApp.swift:42]: Yes. And this is example code in the iOS tv-casting-app, not part of the casting framework.

File: examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/NsdDiscoveryListener.java (hunk 1 above)
Comment (sharadb-amazon) [reply examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/NsdDiscoveryListener.java]: Makes sense. Done!

**Review by hawk248 — APPROVED** [review]

**Review by yufengwangca — APPROVED** [review]
