### PR TITLE
Fix handling of path-specific errors in MTRBaseDevice subscribe code.

### LINKED ISSUE #26076: Fix onFailureCb in MTRBaseDevice's subscribeToAttributePaths
See TODO comment being added in https://github.com/project-chip/connectedhomeip/pull/25840: paths-specific failures are not handled correctly

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
1) Improve documentation for subcribeTo* functions on MTRBaseDevice. 
2) Fix the implementation to not call the subscriptionEstablished handler when the subscription actually errors out before the subscribe is complete.
3) Fix the error handling in the implementation to report path-specific errors using the same mechanism as MTRDevice.

Fixes https://github.com/project-chip/connectedhomeip/issues/26076

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 1]
```diff
@@ -1356,29 +1356,36 @@ - (void)subscribeToAttributePaths:(NSArray<MTRAttributeRequestPath *> * _Nullabl
...
                            dispatch_async(queue, ^{
-                               reportHandler(nil, [MTRError errorForCHIPErrorCode:error]);
+                               reportHandler(@[ @ {
+                                   MTRAttributePathKey : [[MTREventPath alloc] initWithPath:pathCopy],
+                                   MTRErrorKey : [MTRError errorForCHIPErrorCode:error]
+                               } ],
+                                   nil);
                            });
+                       } else {
+                           if (reportHandler) {
```
Comment (ksperling-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:1380]: Looks like you're no longer checking whether `reportHandler` is non-null elsewhere, so can this check be removed too?

**Review by ksperling-apple — APPROVED** [review]

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 1 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:1380]: Good catch.  That argument is nonnull, so we shouldn't be checking it...

**Comment by bzbarsky-apple** [comment]
Fast-tracking platform-specific change with platform owner review.
