### PR TITLE
[Scenes] Missing Tests Cases

### LINKED ISSUE #30696: TestSceneTable relies on emberAfContainsServerFromIndex being mocked inconsistently
TestSceneTable currently relies on `emberAfContainsServerFromIndex` returning true for all cluster ids.

The test should be updated to actually mock a Scene cluster on the relevant endpoints (either in the default mock configuration or by creating a dedicated configuration for this test).

### LINKED ISSUE #33821: [CERT-TEST-FAILURE] - TC-S-2.2- Test failed
### Feature Area

Area:Scenes

### Test Case

TC-S-2.2

### Reproduction steps

1. Execute the below mentioned command to put DUT into a commissionable state : `./chip-all-clusters-app`
2. Once DUT reach the commission able state sent below mentioned command on TH. : .`/chip-tool pairing onnetwork 1 20202021`
3. Once after successful pairing provide the below commands:

**Precondition Steps for adding a Group:**
`./chip-tool groupkeymanagement key-set-write '{"groupKeySetID": "0x01a1","groupKeySecurityPolicy": 0, "epochKey0":"a0a1a2a3a4a5a6a7a8a9aaabacadaeaf","epochStartTime0": 1110000,"epochKey1":"b0b1b2b3b4b5b6b7b8b9babbbcbdbebf", "epochStartTime1": 1110001,"epochKey2":"c0c1c2c3c4c5c6c7c8c9cacbcccdcecf", "epochStartTime2": 1110002 }' 1 0`

> [1718021039.147785][36873:36875] CHIP:DMG: 				StatusIB =
> [1718021039.147861][36873:36875] CHIP:DMG: 				{
> [1718021039.147938][36873:36875] CHIP:DMG: 					status = 0x00 (SUCCESS),
> [1718021039.148015][36873:36875] CHIP:DMG: 				},

`./chip-tool groupkeymanagement write group-key-map '[{"groupId": "0x0001", "groupKeySetID": "0x01a1", "fabricIndex": 1}]' 1 0 `

> [1718021089.747735][36877:36879] CHIP:DMG: 			StatusIB =
> [1718021089.747812][36877:36879] CHIP:DMG: 			{
> [1718021089.747912][36877:36879] CHIP:DMG: 				status = 0x00 (SUCCESS),
> [1718021089.747981][36877:36879] CHIP:DMG: 			},

`./chip-tool groups add-group 0x0001 Gp1 1 1`

> [1718021104.970199][36883:36885] CHIP:DMG: Received Command Response Data, Endpoint=1 Cluster=0x0000_0004 Command=0x0000_0000
> [1718021104.970377][36883:36885] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0004 Command 0x0000_0000
> [1718021104.970667][36883:36885] CHIP:TOO:   AddGroupResponse: {
> [1718021104.970734][36883:36885] CHIP:TOO:     status: 0
> [1718021104.970846][36883:36885] CHIP:TOO:     groupID: 1
> [1718021104.970948][36883:36885] CHIP:TOO:    }

**Send AddScene command to DUT with invalid ExtensionField (Invalid attribute ID for given cluster).
Here AttributeID 0x4011 is Invalid ID from Color Control Cluster**

**Actual Outcome:**

`./chip-tool scenesmanagement add-scene 0x0001 0x01 1000 "scene name" '[{"clusterID": "0x0300", "attributeValueList":[{"attributeID": "0x4011", "attributeValue": "0x01"}]}]' 1 1`

> [1718021138.581350][36889:36891] CHIP:DMG: Received Command Response Data, Endpoint=1 Cluster=0x0000_0062 Command=0x0000_0000
> [1718021138.581539][36889:36891] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0062 Command 0x0000_0000
> [1718021138.581880][36889:36891] CHIP:TOO:   AddSceneResponse: {
> [1718021138.582027][36889:36891] CHIP:TOO:     status: 0
> [1718021138.582090][36889:36891] CHIP:TOO:     groupID: 1
> [1718021138.582200][36889:36891] CHIP:TOO:     sceneID: 1
> [1718021138.582252][36889:36891] CHIP:TOO:    }

**Expected Outcome:**

`./chip-tool scenesmanagement add-scene 0x0001 0x01 1000 "scene name" '[{"clusterID": "0x0300", "attributeValueList":[{"attributeID": "0x4011", "attributeValue": "0x01"}]}]' 1 1`

> [1718021138.581350][36889:36891] CHIP:DMG: Received Command Response Data, Endpoint=1 Cluster=0x0000_0062 Command=0x0000_0000
> [1718021138.581539][36889:36891] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0062 Command 0x0000_0000
> [1718021138.581880][36889:36891] CHIP:TOO:   AddSceneResponse: {
> [1718021138.582027][36889:36891] CHIP:TOO:     status: 133
> [1718021138.582090][36889:36891] CHIP:TOO:     groupID: 1
> [1718021138.582200][36889:36891] CHIP:TOO:     sceneID: 1
> [1718021138.582252][36889:36891] CHIP:TOO:    }

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

c15826050e744034ec9c90cf810fb2b34bb46c54

### Platform

raspi

### Anything else?

As per the specification, In Add Scene Command If the ExtensionFieldSetStructs list is formatted invalid according to the ExtensionFieldSetStruct structure definition, then the status SHALL be INVALID_COMMAND in the AddSceneResponse,
But in current SDK the Status Response is **"SUCCESS"**

image

**Step that require review:**
Test step 8f 

**Reference log:**
[TC-S-2.2(DUT).txt](https://github.com/user-attachments/files/15766156/TC-S-2.2.DUT.txt)
[TC-S-2.2(CNTRL).txt](https://github.com/user-attachments/files/15766157/TC-S-2.2.CNTRL.txt)

**Spec References:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/Scenes.adoc#926-effect-on-receipt

**Test Plan References:**
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/scenes.adoc#tc-s-2-2-primary-functionality-with-dut_server

### PR DESCRIPTION
**Pull request by lpbeliveau-silabs**
Implemented missing yaml tests cases for points 1 to 3 of https://github.com/CHIP-Specifications/chip-test-plans/issues/4060 and server checks in code to verify validity of ExtensionFieldSets attributes.

Fixes: https://github.com/CHIP-Specifications/chip-test-plans/issues/4060

Also added a MockNodeConfig for Scenes, 
Fixes: https://github.com/project-chip/connectedhomeip/issues/30696

Added test to check for failure on wrong attribute id value,
fixes: https://github.com/project-chip/connectedhomeip/issues/33821

Fixes: https://github.com/CHIP-Specifications/chip-test-plans/issues/4060

### CODE REVIEW

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 1]
```diff
@@ -20,6 +20,27 @@
...
+
+/// ValideAttribute
+/// @brief  Validate the attribute exists for a given cluster
+/// @param[in] clusterID  Cluster ID
+/// @param[in] attID      Attribute ID
+/// @return CHIP_ERROR_UNSUPPORTED_CHIP_FEATURE if the attribute does not exist for a given cluster or is not scenable
+// TODO: Assess if we also want to throw an error if the attribute value is out of range
+// TODO: Add check for "S" quality to determine if the attribute is scenable once suported :
+// https://github.com/project-chip/connectedhomeip/issues/24177
+CHIP_ERROR ValideAttribute(EndpointId endpoint, ClusterId cluster, AttributeId attributeId)
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:33]:
```suggestion
CHIP_ERROR ValidateAttributePath(EndpointId endpoint, ClusterId cluster, AttributeId attributeId)
```

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 2]
```diff
@@ -20,6 +20,27 @@
...
+{
+    uint16_t attIndex = emberAfGetServerAttributeIndexByAttributeId(endpoint, cluster, attributeId);
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:35]: Please use `emberAfContainsAttribute`, which is the better "public" API here.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 1 above)
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:33]: Note that this will return error for global list attributes.  That's probably OK, since those are not scenable anyway....

Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp]: I'll add a note there just in case we someday want to make global attributes scenable.

**Comment by andy31415** [comment]
PR #32632: Size comparison from b6f8e4f5161618497de9e10ccda438b326aeedb2 to afd568c83eadc30713b281c0c6533a92e52d8f9c


<details>
<summary>Increases (20 builds for cc13x4_26x4, cyw30739, efr32, esp32, linux, nrfconnect, psoc6, stm32, telink)</summary>


| platform    | target                                | config                   | section       |   b6f8e4f5 |   afd568c8 |   change |   % change |
|:------------|:--------------------------------------|:-------------------------|:--------------|-----------:|-----------:|---------:|-----------:|
| cc13x4_26x4 | lighting-app                          | LP_EM_CC1354P10_6        | (read only)   |     774060 |     774140 |       80 |        0.0 |
|             |                                       |                          | .text         |     691976 |     692056 |       80 |        0.0 |
| cyw30739    | light                                 | cyw930739m2evb_01        | (read/write)  |     569195 |     569275 |       80 |        0.0 |
|             |                                       |                          | .app_xip_area |     458949 |     459029 |       80 |        0.0 |
| efr32       | lighting-app                          | BRD4161A+rs9116          | (read/write)  |     933136 |     933232 |       96 |        0.0 |
|             |                                       |                          | .text         |     733756 |     733852 |       96 |        0.0 |
|             |                                       | BRD4187C                 | (read/write)  |    1110416 |    1110472 |       56 |        0.0 |
|             |                                       |                          | .text         |     911804 |     911860 |       56 |        0.0 |
| esp32       | all-clusters-app                      | c3devkit                 | (read only)   |    1211614 |    1211738 |      124 |        0.0 |
|             |                                       |                          | .flash.text   |    1211614 |    1211738 |      124 |        0.0 |
|             |                                       | m5stack                  | (read only)   |    1253855 |    1253927 |       72 |        0.0 |
|             |                                       |                          | .flash.text   |    1247691 |    1247763 |       72 |        0.0 |
| linux       | all-clusters-app                      | debug                    | (read only)   |    5927209 |    5927977 |      768 |        0.0 |
|             |                                       |                          | .text         |    5144483 |    5145251 |      768 |        0.0 |
|             | all-clusters-minimal-app              | debug                    | (read only)   |    5208057 |    5208809 |      752 |        0.0 |
|             |                                       |                          | .text         |    4684963 |    4685715 |      752 |        0.0 |
|             | shell                                 | debug                    | (read only)   |    2895217 |    2895969 |      752 |        0.0 |
|             |                                       |                          | .text         |    2536594 |    2537346 |      752 |        0.0 |
|             | lighting-app                          | debug+rpc+ui             | (read only)   |    5525969 |    5526737 |      768 |        0.0 |
|             |                                       |                          | .text         |    4925363 |    4926131 |      768 |        0.0 |
| nrfconnect  | all-clusters-app                      | nrf52840dk_nrf52840      | (read/write)  |    1062496 |    1062576 |       80 |        0.0 |
|             |                                       |                          | text          |     779604 |     779680 |       76 |        0.0 |
|             | all-clusters-minimal-app              | nrf52840dk_nrf52840      | (read/write)  |    1010072 |    1010152 |       80 |        0.0 |
|             |                                       |                          | text          |     740940 |     741016 |       76 |        0.0 |
|             | all-clusters-app                      | nrf7002dk_nrf5340_cpuapp | (read/write)  |    1223936 |    1224016 |       80 |        0.0 |
|             |                                       |                          | text          |     795600 |     795676 |       76 |        0.0 |
| psoc6       | all-clusters                          | cy8ckit_062s2_43012      | (read/write)  |    1796860 |    1796956 |       96 |        0.0 |
|             |                                       |                          | .text         |    1589572 |    1589668 |       96 |        0.0 |
|             | all-clusters-minimal                  | cy8ckit_062s2_43012      | (read/write)  |    1718908 |    1719020 |      112 |        0.0 |
|             |                                       |                          | .text         |    1514764 |    1514876 |      112 |        0.0 |
|             | light                                 | cy8ckit_062s2_43012      | (read/write)  |    1638012 |    1638124 |      112 |        0.0 |
|             |                                       |                          | .text         |    1440596 |    1440708 |      112 |        0.0 |
| stm32       | light                                 | STM32WB5MM-DK            | (read/write)  |     601241 |     601321 |       80 |        0.0 |
|             |                                       |                          | .text         |     382800 |     382880 |       80 |        0.0 |
| telink      | all-clusters-app                      | tlsr9518adk80d           | (read/write)  |    1092872 |    1093000 |      128 |        0.0 |
|             |                                       |                          | text          |     793934 |     794058 |      124 |        0.0 |
|             | lighting-app-ota-rpc-factory-data-4mb | tlsr9518adk80d           | (read/write)  |    1074228 |    1074356 |      128 |        0.0 |
|             |                                       |                          | text          |     778116 |     778240 |      124 |        0.0 |
|             | all-clusters-minimal-app              | tlsr9528a                | (read/write)  |    1050344 |    1050464 |      120 |        0.0 |
|             |                                       |                          | text          |     765256 |     765380 |      124 |        0.0 |
</details>

<details>
<summary>Decreases (1 build for efr32)</summary>


| platform   | target     | config   | section      |   b6f8e4f5 |   afd568c8 |   change |   % change |
|:-----------|:-----------|:---------|:-------------|-----------:|-----------:|---------:|-----------:|
| efr32      | window-app | BRD4187C | (read/write) |    1157136 |    1157128 |       -8 |       -0.0 |
|            |            |          | .text        |     986364 |     986356 |       -8 |       -0.0 |
</details>

<details>
<summary>Full report (72 builds for bl602, bl702, bl702l, cc13x4_26x4, cc32xx, cyw30739, efr32, esp32, k32w, linux, mbed, nrfconnect, psoc6, qpg, stm32, telink)</summary>


| platform    | target                                  | config                   | section       |   b6f8e4f5 |   afd568c8 |   change |   % change |
|:------------|:----------------------------------------|:-------------------------|:--------------|-----------:|-----------:|---------:|-----------:|
| bl602       | lighting-app                            | bl602                    | (read/write)  |    1437770 |    1437770 |        0 |        0.0 |
|             |                                         |                          | .bss          |      85352 |      85352 |        0 |        0.0 |
|             |                                         |                          | .data         |       9496 |       9496 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     158432 |     158432 |        0 |        0.0 |
|             |                                         |                          | .text         |    1103848 |    1103848 |        0 |        0.0 |
|             |                                         | bl602+mfd                | (read/write)  |    1452194 |    1452194 |        0 |        0.0 |
|             |                                         |                          | .bss          |      85512 |      85512 |        0 |        0.0 |
|             |                                         |                          | .data         |       9472 |       9472 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     157392 |     157392 |        0 |        0.0 |
|             |                                         |                          | .text         |    1119166 |    1119166 |        0 |        0.0 |
|             |                                         | bl602+rpc                | (read/write)  |    1485418 |    1485418 |        0 |        0.0 |
|             |                                         |                          | .bss          |      93384 |      93384 |        0 |        0.0 |
|             |                                         |                          | .data         |       9872 |       9872 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     166000 |     166000 |        0 |        0.0 |
|             |                                         |                          | .text         |    1135494 |    1135494 |        0 |        0.0 |
| bl702       | lighting-app                            | bl702                    | (read only)   |       3478 |       3478 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1202215 |    1202215 |        0 |        0.0 |
|             |                                         |                          | .bss          |      11133 |      11133 |        0 |        0.0 |
|             |                                         |                          | .data         |       3680 |       3680 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     107784 |     107784 |        0 |        0.0 |
|             |                                         |                          | .text         |     972748 |     972748 |        0 |        0.0 |
|             |                                         | bl702+mfd                | (read only)   |       3478 |       3478 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1213271 |    1213271 |        0 |        0.0 |
|             |                                         |                          | .bss          |      11309 |      11309 |        0 |        0.0 |
|             |                                         |                          | .data         |       3656 |       3656 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     106724 |     106724 |        0 |        0.0 |
|             |                                         |                          | .text         |     984758 |     984758 |        0 |        0.0 |
|             |                                         | bl702+rpc                | (read only)   |       3478 |       3478 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1293963 |    1293963 |        0 |        0.0 |
|             |                                         |                          | .bss          |      19613 |      19613 |        0 |        0.0 |
|             |                                         |                          | .data         |       4216 |       4216 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     123156 |     123156 |        0 |        0.0 |
|             |                                         |                          | .text         |    1047712 |    1047712 |        0 |        0.0 |
|             |                                         | bl706-eth                | (read/write)  |    1019929 |    1019929 |        0 |        0.0 |
|             |                                         |                          | .bss          |      23708 |      23708 |        0 |        0.0 |
|             |                                         |                          | .data         |       3256 |       3256 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     101116 |     101116 |        0 |        0.0 |
|             |                                         |                          | .text         |     763876 |     763876 |        0 |        0.0 |
|             |                                         | bl706-wifi               | (read/write)  |    1254514 |    1254514 |        0 |        0.0 |
|             |                                         |                          | .bss          |      10577 |      10577 |        0 |        0.0 |
|             |                                         |                          | .data         |       3688 |       3688 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     122116 |     122116 |        0 |        0.0 |
|             |                                         |                          | .text         |     995722 |     995722 |        0 |        0.0 |
| bl702l      | lighting-app                            | bl702l                   | (read only)   |        512 |        512 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1171792 |    1171792 |        0 |        0.0 |
|             |                                         |                          | .bss          |      16328 |      16328 |        0 |        0.0 |
|             |                                         |                          | .data         |       5040 |       5040 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     101788 |     101788 |        0 |        0.0 |
|             |                                         |                          | .text         |     965846 |     965846 |        0 |        0.0 |
|             |                                         | bl702l+mfd               | (read only)   |        512 |        512 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1182940 |    1182940 |        0 |        0.0 |
|             |                                         |                          | .bss          |      16504 |      16504 |        0 |        0.0 |
|             |                                         |                          | .data         |       5024 |       5024 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     100728 |     100728 |        0 |        0.0 |
|             |                                         |                          | .text         |     977912 |     977912 |        0 |        0.0 |
| cc13x4_26x4 | lighting-app                            | LP_EM_CC1354P10_6        | (read only)   |     774060 |     774140 |       80 |        0.0 |
|             |                                         |                          | (read/write)  |     168624 |     168624 |        0 |        0.0 |
|             |                                         |                          | .bss          |      90628 |      90628 |        0 |        0.0 |
|             |                                         |                          | .data         |       3560 |       3560 |        0 |        0.0 |
|             |                                         |                          | .rodata       |      81820 |      81820 |        0 |        0.0 |
|             |                                         |                          | .text         |     691976 |     692056 |       80 |        0.0 |
|             | lock-ftd                                | LP_EM_CC1354P10_6        | (read only)   |     790484 |     790484 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     178872 |     178872 |        0 |        0.0 |
|             |                                         |                          | .bss          |     100876 |     100876 |        0 |        0.0 |
|             |                                         |                          | .data         |       3560 |       3560 |        0 |        0.0 |
|             |                                         |                          | .rodata       |      76004 |      76004 |        0 |        0.0 |
|             |                                         |                          | .text         |     714216 |     714216 |        0 |        0.0 |
|             | lock-mtd                                | LP_EM_CC1354P10_6        | (read only)   |     779124 |     779124 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     173312 |     173312 |        0 |        0.0 |
|             |                                         |                          | .bss          |      95316 |      95316 |        0 |        0.0 |
|             |                                         |                          | .data         |       3560 |       3560 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     102756 |     102756 |        0 |        0.0 |
|             |                                         |                          | .text         |     676104 |     676104 |        0 |        0.0 |
|             | pump-app                                | LP_EM_CC1354P10_6        | (read only)   |     731396 |     731396 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     167592 |     167592 |        0 |        0.0 |
|             |                                         |                          | .bss          |      89360 |      89360 |        0 |        0.0 |
|             |                                         |                          | .data         |       3552 |       3552 |        0 |        0.0 |
|             |                                         |                          | .rodata       |      77484 |      77484 |        0 |        0.0 |
|             |                                         |                          | .text         |     653648 |     653648 |        0 |        0.0 |
|             | pump-controller-app                     | LP_EM_CC1354P10_6        | (read only)   |     716916 |     716916 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     167800 |     167800 |        0 |        0.0 |
|             |                                         |                          | .bss          |      89584 |      89584 |        0 |        0.0 |
|             |                                         |                          | .data         |       3544 |       3544 |        0 |        0.0 |
|             |                                         |                          | .rodata       |      73260 |      73260 |        0 |        0.0 |
|             |                                         |                          | .text         |     643392 |     643392 |        0 |        0.0 |
| cc32xx      | air-purifier                            | CC3235SF_LAUNCHXL        | (read only)   |     583402 |     583402 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     207992 |     207992 |        0 |        0.0 |
|             |                                         |                          | .bss          |     201228 |     201228 |        0 |        0.0 |
|             |                                         |                          | .data         |       1640 |       1640 |        0 |        0.0 |
|             |                                         |                          | .rodata       |      86610 |      86610 |        0 |        0.0 |
|             |                                         |                          | .text         |     494668 |     494668 |        0 |        0.0 |
|             | lock                                    | CC3235SF_LAUNCHXL        | (read only)   |     628674 |     628674 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     208336 |     208336 |        0 |        0.0 |
|             |                                         |                          | .bss          |     201720 |     201720 |        0 |        0.0 |
|             |                                         |                          | .data         |       1496 |       1496 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     107066 |     107066 |        0 |        0.0 |
|             |                                         |                          | .text         |     519484 |     519484 |        0 |        0.0 |
| cyw30739    | light                                   | cyw930739m2evb_01        | (read/write)  |     569195 |     569275 |       80 |        0.0 |
|             |                                         |                          | .app_xip_area |     458949 |     459029 |       80 |        0.0 |
|             |                                         |                          | .bss          |      65080 |      65080 |        0 |        0.0 |
|             |                                         |                          | .data         |        744 |        744 |        0 |        0.0 |
|             |                                         |                          | .rodata       |          0 |          0 |        0 |        0.0 |
|             |                                         |                          | .text         |        112 |        112 |        0 |        0.0 |
|             | lock                                    | cyw930739m2evb_01        | (read/write)  |     551867 |     551867 |        0 |        0.0 |
|             |                                         |                          | .app_xip_area |     436861 |     436861 |        0 |        0.0 |
|             |                                         |                          | .bss          |      69832 |      69832 |        0 |        0.0 |
|             |                                         |                          | .data         |        752 |        752 |        0 |        0.0 |
|             |                                         |                          | .rodata       |          0 |          0 |        0 |        0.0 |
|             |                                         |                          | .text         |        112 |        112 |        0 |        0.0 |
|             | ota-requestor                           | cyw930739m2evb_01        | (read/write)  |     571995 |     571995 |        0 |        0.0 |
|             |                                         |                          | .app_xip_area |     463253 |     463253 |        0 |        0.0 |
|             |                                         |                          | .bss          |      63616 |      63616 |        0 |        0.0 |
|             |                                         |                          | .data         |        704 |        704 |        0 |        0.0 |
|             |                                         |                          | .rodata       |          0 |          0 |        0 |        0.0 |
|             |                                         |                          | .text         |        112 |        112 |        0 |        0.0 |
|             | switch                                  | cyw930739m2evb_01        | (read/write)  |     564931 |     564931 |        0 |        0.0 |
|             |                                         |                          | .app_xip_area |     452909 |     452909 |        0 |        0.0 |
|             |                                         |                          | .bss          |      66816 |      66816 |        0 |        0.0 |
|             |                                         |                          | .data         |        784 |        784 |        0 |        0.0 |
|             |                                         |                          | .rodata       |          0 |          0 |        0 |        0.0 |
|             |                                         |                          | .text         |        112 |        112 |        0 |        0.0 |
| efr32       | lighting-app                            | BRD4161A+rs9116          | (read/write)  |     933136 |     933232 |       96 |        0.0 |
|             |                                         |                          | .bss          |     197960 |     197960 |        0 |        0.0 |
|             |                                         |                          | .data         |       1396 |       1396 |        0 |        0.0 |
|             |                                         |                          | .text         |     733756 |     733852 |       96 |        0.0 |
|             | lock-app                                | BRD4161A+wf200           | (read/write)  |    1122828 |    1122828 |        0 |        0.0 |
|             |                                         |                          | .bss          |     186788 |     186788 |        0 |        0.0 |
|             |                                         |                          | .data         |       2800 |       2800 |        0 |        0.0 |
|             |                                         |                          | .text         |     933220 |     933220 |        0 |        0.0 |
|             | lighting-app                            | BRD4187C                 | (read/write)  |    1110416 |    1110472 |       56 |        0.0 |
|             |                                         |                          | .bss          |     195176 |     195176 |        0 |        0.0 |
|             |                                         |                          | .data         |       3416 |       3416 |        0 |        0.0 |
|             |                                         |                          | .text         |     911804 |     911860 |       56 |        0.0 |
|             | window-app                              | BRD4187C                 | (read/write)  |    1157136 |    1157128 |       -8 |       -0.0 |
|             |                                         |                          | .bss          |     167424 |     167424 |        0 |        0.0 |
|             |                                         |                          | .data         |       3328 |       3328 |        0 |        0.0 |
|             |                                         |                          | .text         |     986364 |     986356 |       -8 |       -0.0 |
| esp32       | all-clusters-app                        | c3devkit                 | (read only)   |    1211614 |    1211738 |      124 |        0.0 |
|             |                                         |                          | (read/write)  |    1749744 |    1749744 |        0 |        0.0 |
|             |                                         |                          | .dram0.bss    |      74320 |      74320 |        0 |        0.0 |
|             |                                         |                          | .dram0.data   |      13620 |      13620 |        0 |        0.0 |
|             |                                         |                          | .flash.rodata |     252272 |     252272 |        0 |        0.0 |
|             |                                         |                          | .flash.text   |    1211614 |    1211738 |      124 |        0.0 |
|             |                                         |                          | .iram0.text   |      75530 |      75530 |        0 |        0.0 |
|             |                                         | m5stack                  | (read only)   |    1253855 |    1253927 |       72 |        0.0 |
|             |                                         |                          | (read/write)  |     536336 |     536336 |        0 |        0.0 |
|             |                                         |                          | .dram0.bss    |      81256 |      81256 |        0 |        0.0 |
|             |                                         |                          | .dram0.data   |      35164 |      35164 |        0 |        0.0 |
|             |                                         |                          | .flash.rodata |     283996 |     283996 |        0 |        0.0 |
|             |                                         |                          | .flash.text   |    1247691 |    1247763 |       72 |        0.0 |
|             |                                         |                          | .iram0.text   |     125403 |     125403 |        0 |        0.0 |
| k32w        | contact                                 | k32w0+release            | (read only)   |     604912 |     604912 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |      79460 |      79460 |        0 |        0.0 |
|             |                                         |                          | .bss          |      67300 |      67300 |        0 |        0.0 |
|             |                                         |                          | .data         |       2176 |       2176 |        0 |        0.0 |
|             |                                         |                          | .text         |     604376 |     604376 |        0 |        0.0 |
|             | light                                   | k32w0+release            | (read only)   |     606896 |     606896 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |      79320 |      79320 |        0 |        0.0 |
|             |                                         |                          | .bss          |      67156 |      67156 |        0 |        0.0 |
|             |                                         |                          | .data         |       2180 |       2180 |        0 |        0.0 |
|             |                                         |                          | .text         |     606360 |     606360 |        0 |        0.0 |
|             | contact                                 | k32w1+release            | (read only)   |       1024 |       1024 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     699776 |     699776 |        0 |        0.0 |
|             |                                         |                          | .bss          |      71148 |      71148 |        0 |        0.0 |
|             |                                         |                          | .data         |       2848 |       2848 |        0 |        0.0 |
|             |                                         |                          | .text         |     586400 |     586400 |        0 |        0.0 |
|             | light                                   | k32w1+release            | (read only)   |       1024 |       1024 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     791196 |     791196 |        0 |        0.0 |
|             |                                         |                          | .bss          |      80628 |      80628 |        0 |        0.0 |
|             |                                         |                          | .data         |       2048 |       2048 |        0 |        0.0 |
|             |                                         |                          | .text         |     669160 |     669160 |        0 |        0.0 |
| linux       | chip-tool-ipv6only                      | arm64                    | (read only)   |   11366292 |   11366292 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     587872 |     587872 |        0 |        0.0 |
|             |                                         |                          | .bss          |     103512 |     103512 |        0 |        0.0 |
|             |                                         |                          | .data         |       4496 |       4496 |        0 |        0.0 |
|             |                                         |                          | .data.rel.ro  |     454592 |     454592 |        0 |        0.0 |
|             |                                         |                          | .dynamic      |        512 |        512 |        0 |        0.0 |
|             |                                         |                          | .got          |      16944 |      16944 |        0 |        0.0 |
|             |                                         |                          | .init         |         24 |         24 |        0 |        0.0 |
|             |                                         |                          | .init_array   |        256 |        256 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     354596 |     354596 |        0 |        0.0 |
|             |                                         |                          | .text         |   10133384 |   10133384 |        0 |        0.0 |
|             | thermostat-no-ble                       | arm64                    | (read only)   |    4417492 |    4417492 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     245432 |     245432 |        0 |        0.0 |
|             |                                         |                          | .bss          |     121832 |     121832 |        0 |        0.0 |
|             |                                         |                          | .data         |       3376 |       3376 |        0 |        0.0 |
|             |                                         |                          | .data.rel.ro  |     103624 |     103624 |        0 |        0.0 |
|             |                                         |                          | .dynamic      |        512 |        512 |        0 |        0.0 |
|             |                                         |                          | .got          |       8616 |       8616 |        0 |        0.0 |
|             |                                         |                          | .init         |         24 |         24 |        0 |        0.0 |
|             |                                         |                          | .init_array   |        424 |        424 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     159436 |     159436 |        0 |        0.0 |
|             |                                         |                          | .text         |    3923416 |    3923416 |        0 |        0.0 |
|             | air-purifier-app                        | debug                    | (read only)   |    2621093 |    2621093 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     128968 |     128968 |        0 |        0.0 |
|             |                                         |                          | .bss          |      46544 |      46544 |        0 |        0.0 |
|             |                                         |                          | .data         |       2240 |       2240 |        0 |        0.0 |
|             |                                         |                          | .data.rel.ro  |      74248 |      74248 |        0 |        0.0 |
|             |                                         |                          | .dynamic      |        608 |        608 |        0 |        0.0 |
|             |                                         |                          | .got          |       4544 |       4544 |        0 |        0.0 |
|             |                                         |                          | .init         |         27 |         27 |        0 |        0.0 |
|             |                                         |                          | .init_array   |        752 |        752 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     184624 |     184624 |        0 |        0.0 |
|             |                                         |                          | .text         |    2258981 |    2258981 |        0 |        0.0 |
|             | all-clusters-app                        | debug                    | (read only)   |    5927209 |    5927977 |      768 |        0.0 |
|             |                                         |                          | (read/write)  |     480440 |     480440 |        0 |        0.0 |
|             |                                         |                          | .bss          |     134848 |     134848 |        0 |        0.0 |
|             |                                         |                          | .data         |       4528 |       4528 |        0 |        0.0 |
|             |                                         |                          | .data.rel.ro  |     333640 |     333640 |        0 |        0.0 |
|             |                                         |                          | .dynamic      |        624 |        624 |        0 |        0.0 |
|             |                                         |                          | .got          |       5360 |       5360 |        0 |        0.0 |
|             |                                         |                          | .init         |         27 |         27 |        0 |        0.0 |
|             |                                         |                          | .init_array   |       1392 |       1392 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     349328 |     349328 |        0 |        0.0 |
|             |                                         |                          | .text         |    5144483 |    5145251 |      768 |        0.0 |
|             | all-clusters-minimal-app                | debug                    | (read only)   |    5208057 |    5208809 |      752 |        0.0 |
|             |                                         |                          | (read/write)  |     236392 |     236392 |        0 |        0.0 |
|             |                                         |                          | .bss          |     127680 |     127680 |        0 |        0.0 |
|             |                                         |                          | .data         |       4432 |       4432 |        0 |        0.0 |
|             |                                         |                          | .data.rel.ro  |      97208 |      97208 |        0 |        0.0 |
|             |                                         |                          | .dynamic      |        624 |        624 |        0 |        0.0 |
|             |                                         |                          | .got          |       5280 |       5280 |        0 |        0.0 |
|             |                                         |                          | .init         |         27 |         27 |        0 |        0.0 |
|             |                                         |                          | .init_array   |       1120 |       1120 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     288362 |     288362 |        0 |        0.0 |
|             |                                         |                          | .text         |    4684963 |    4685715 |      752 |        0.0 |
|             | bridge-app                              | debug                    | (read only)   |    4602457 |    4602457 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     217240 |     217240 |        0 |        0.0 |
|             |                                         |                          | .bss          |     118176 |     118176 |        0 |        0.0 |
|             |                                         |                          | .data         |       6208 |       6208 |        0 |        0.0 |
|             |                                         |                          | .data.rel.ro  |      86144 |      86144 |        0 |        0.0 |
|             |                                         |                          | .dynamic      |        624 |        624 |        0 |        0.0 |
|             |                                         |                          | .got          |       5248 |       5248 |        0 |        0.0 |
|             |                                         |                          | .init         |         27 |         27 |        0 |        0.0 |
|             |                                         |                          | .init_array   |        816 |        816 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     228970 |     228970 |        0 |        0.0 |
|             |                                         |                          | .text         |    4153171 |    4153171 |        0 |        0.0 |
|             | chip-tool                               | debug                    | (read only)   |   12044449 |   12044449 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     521520 |     521520 |        0 |        0.0 |
|             |                                         |                          | .bss          |      94424 |      94424 |        0 |        0.0 |
|             |                                         |                          | .data         |       5122 |       5122 |        0 |        0.0 |
|             |                                         |                          | .data.rel.ro  |     414744 |     414744 |        0 |        0.0 |
|             |                                         |                          | .dynamic      |        624 |        624 |        0 |        0.0 |
|             |                                         |                          | .got          |       5768 |       5768 |        0 |        0.0 |
|             |                                         |                          | .init         |         27 |         27 |        0 |        0.0 |
|             |                                         |                          | .init_array   |        784 |        784 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     448665 |     448665 |        0 |        0.0 |
|             |                                         |                          | .text         |   10889987 |   10889987 |        0 |        0.0 |
|             | lock-app                                | debug                    | (read only)   |    4669817 |    4669817 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     204824 |     204824 |        0 |        0.0 |
|             |                                         |                          | .bss          |     113600 |     113600 |        0 |        0.0 |
|             |                                         |                          | .data         |       4128 |       4128 |        0 |        0.0 |
|             |                                         |                          | .data.rel.ro  |      80392 |      80392 |        0 |        0.0 |
|             |                                         |                          | .dynamic      |        624 |        624 |        0 |        0.0 |
|             |                                         |                          | .got          |       5200 |       5200 |        0 |        0.0 |
|             |                                         |                          | .init         |         27 |         27 |        0 |        0.0 |
|             |                                         |                          | .init_array   |        848 |        848 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     254890 |     254890 |        0 |        0.0 |
|             |                                         |                          | .text         |    4203251 |    4203251 |        0 |        0.0 |
|             | ota-provider-app                        | debug                    | (read only)   |    4298145 |    4298145 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     193296 |     193296 |        0 |        0.0 |
|             |                                         |                          | .bss          |     113280 |     113280 |        0 |        0.0 |
|             |                                         |                          | .data         |       4336 |       4336 |        0 |        0.0 |
|             |                                         |                          | .data.rel.ro  |      69776 |      69776 |        0 |        0.0 |
|             |                                         |                          | .dynamic      |        624 |        624 |        0 |        0.0 |
|             |                                         |                          | .got          |       4536 |       4536 |        0 |        0.0 |
|             |                                         |                          | .init         |         27 |         27 |        0 |        0.0 |
|             |                                         |                          | .init_array   |        712 |        712 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     207946 |     207946 |        0 |        0.0 |
|             |                                         |                          | .text         |    3897203 |    3897203 |        0 |        0.0 |
|             | ota-requestor-app                       | debug                    | (read only)   |    4427617 |    4427617 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     197728 |     197728 |        0 |        0.0 |
|             |                                         |                          | .bss          |     114208 |     114208 |        0 |        0.0 |
|             |                                         |                          | .data         |       4736 |       4736 |        0 |        0.0 |
|             |                                         |                          | .data.rel.ro  |      72896 |      72896 |        0 |        0.0 |
|             |                                         |                          | .dynamic      |        624 |        624 |        0 |        0.0 |
|             |                                         |                          | .got          |       4472 |       4472 |        0 |        0.0 |
|             |                                         |                          | .init         |         27 |         27 |        0 |        0.0 |
|             |                                         |                          | .init_array   |        760 |        760 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     214090 |     214090 |        0 |        0.0 |
|             |                                         |                          | .text         |    4015987 |    4015987 |        0 |        0.0 |
|             | shell                                   | debug                    | (read only)   |    2895217 |    2895969 |      752 |        0.0 |
|             |                                         |                          | (read/write)  |     156360 |     156360 |        0 |        0.0 |
|             |                                         |                          | .bss          |      62736 |      62736 |        0 |        0.0 |
|             |                                         |                          | .data         |       1392 |       1392 |        0 |        0.0 |
|             |                                         |                          | .data.rel.ro  |      86464 |      86464 |        0 |        0.0 |
|             |                                         |                          | .dynamic      |        592 |        592 |        0 |        0.0 |
|             |                                         |                          | .got          |       4072 |       4072 |        0 |        0.0 |
|             |                                         |                          | .init         |         27 |         27 |        0 |        0.0 |
|             |                                         |                          | .init_array   |       1072 |       1072 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     185280 |     185280 |        0 |        0.0 |
|             |                                         |                          | .text         |    2536594 |    2537346 |      752 |        0.0 |
|             | tv-app                                  | debug                    | (read only)   |    5716937 |    5716937 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     352592 |     352592 |        0 |        0.0 |
|             |                                         |                          | .bss          |     244368 |     244368 |        0 |        0.0 |
|             |                                         |                          | .data         |       6528 |       6528 |        0 |        0.0 |
|             |                                         |                          | .data.rel.ro  |      94424 |      94424 |        0 |        0.0 |
|             |                                         |                          | .dynamic      |        624 |        624 |        0 |        0.0 |
|             |                                         |                          | .got          |       5496 |       5496 |        0 |        0.0 |
|             |                                         |                          | .init         |         27 |         27 |        0 |        0.0 |
|             |                                         |                          | .init_array   |       1144 |       1144 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     290058 |     290058 |        0 |        0.0 |
|             |                                         |                          | .text         |    5184771 |    5184771 |        0 |        0.0 |
|             | tv-casting-app                          | debug                    | (read only)   |    9869185 |    9869185 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     340304 |     340304 |        0 |        0.0 |
|             |                                         |                          | .bss          |     156272 |     156272 |        0 |        0.0 |
|             |                                         |                          | .data         |       2976 |       2976 |        0 |        0.0 |
|             |                                         |                          | .data.rel.ro  |     174176 |     174176 |        0 |        0.0 |
|             |                                         |                          | .dynamic      |        624 |        624 |        0 |        0.0 |
|             |                                         |                          | .got          |       5072 |       5072 |        0 |        0.0 |
|             |                                         |                          | .init         |         27 |         27 |        0 |        0.0 |
|             |                                         |                          | .init_array   |       1176 |       1176 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     382616 |     382616 |        0 |        0.0 |
|             |                                         |                          | .text         |    9020803 |    9020803 |        0 |        0.0 |
|             | lighting-app                            | debug+rpc+ui             | (read only)   |    5525969 |    5526737 |      768 |        0.0 |
|             |                                         |                          | (read/write)  |     226032 |     226032 |        0 |        0.0 |
|             |                                         |                          | .bss          |     119144 |     119144 |        0 |        0.0 |
|             |                                         |                          | .data         |       4832 |       4832 |        0 |        0.0 |
|             |                                         |                          | .data.rel.ro  |      94544 |      94544 |        0 |        0.0 |
|             |                                         |                          | .dynamic      |        672 |        672 |        0 |        0.0 |
|             |                                         |                          | .got          |       5888 |       5888 |        0 |        0.0 |
|             |                                         |                          | .init         |         27 |         27 |        0 |        0.0 |
|             |                                         |                          | .init_array   |        928 |        928 |        0 |        0.0 |
|             |                                         |                          | .rodata       |     353908 |     353908 |        0 |        0.0 |
|             |                                         |                          | .text         |    4925363 |    4926131 |      768 |        0.0 |
| mbed        | lock-app-release                        | cy8cproto_062_4343w      | (read only)   |       6224 |       6224 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    2532376 |    2532376 |        0 |        0.0 |
|             |                                         |                          | .bss          |     220472 |     220472 |        0 |        0.0 |
|             |                                         |                          | .data         |       5200 |       5200 |        0 |        0.0 |
|             |                                         |                          | .text         |    1495060 |    1495060 |        0 |        0.0 |
| nrfconnect  | all-clusters-app                        | nrf52840dk_nrf52840      | (read only)   |          4 |          4 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1062496 |    1062576 |       80 |        0.0 |
|             |                                         |                          | bss           |     133111 |     133111 |        0 |        0.0 |
|             |                                         |                          | rodata        |     102584 |     102584 |        0 |        0.0 |
|             |                                         |                          | text          |     779604 |     779680 |       76 |        0.0 |
|             | all-clusters-minimal-app                | nrf52840dk_nrf52840      | (read only)   |          4 |          4 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1010072 |    1010152 |       80 |        0.0 |
|             |                                         |                          | bss           |     131969 |     131969 |        0 |        0.0 |
|             |                                         |                          | rodata        |      89848 |      89848 |        0 |        0.0 |
|             |                                         |                          | text          |     740940 |     741016 |       76 |        0.0 |
|             | all-clusters-app                        | nrf7002dk_nrf5340_cpuapp | (read only)   |          4 |          4 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1223936 |    1224016 |       80 |        0.0 |
|             |                                         |                          | bss           |     127147 |     127147 |        0 |        0.0 |
|             |                                         |                          | rodata        |     151172 |     151172 |        0 |        0.0 |
|             |                                         |                          | text          |     795600 |     795676 |       76 |        0.0 |
| psoc6       | all-clusters                            | cy8ckit_062s2_43012      | (read only)   |     834440 |     834440 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1796860 |    1796956 |       96 |        0.0 |
|             |                                         |                          | .bss          |     196236 |     196236 |        0 |        0.0 |
|             |                                         |                          | .data         |       2664 |       2664 |        0 |        0.0 |
|             |                                         |                          | .text         |    1589572 |    1589668 |       96 |        0.0 |
|             | all-clusters-minimal                    | cy8ckit_062s2_43012      | (read only)   |     837584 |     837584 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1718908 |    1719020 |      112 |        0.0 |
|             |                                         |                          | .bss          |     193116 |     193116 |        0 |        0.0 |
|             |                                         |                          | .data         |       2640 |       2640 |        0 |        0.0 |
|             |                                         |                          | .text         |    1514764 |    1514876 |      112 |        0.0 |
|             | light                                   | cy8ckit_062s2_43012      | (read only)   |     844312 |     844312 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1638012 |    1638124 |      112 |        0.0 |
|             |                                         |                          | .bss          |     186580 |     186580 |        0 |        0.0 |
|             |                                         |                          | .data         |       2448 |       2448 |        0 |        0.0 |
|             |                                         |                          | .text         |    1440596 |    1440708 |      112 |        0.0 |
|             | lock                                    | cy8ckit_062s2_43012      | (read only)   |     817160 |     817160 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1667660 |    1667660 |        0 |        0.0 |
|             |                                         |                          | .bss          |     213740 |     213740 |        0 |        0.0 |
|             |                                         |                          | .data         |       2440 |       2440 |        0 |        0.0 |
|             |                                         |                          | .text         |    1443092 |    1443092 |        0 |        0.0 |
| qpg         | lighting-app                            | qpg6105+debug            | (read/write)  |    1130052 |    1130052 |        0 |        0.0 |
|             |                                         |                          | .bss          |     102480 |     102480 |        0 |        0.0 |
|             |                                         |                          | .data         |        824 |        824 |        0 |        0.0 |
|             |                                         |                          | .text         |     642432 |     642432 |        0 |        0.0 |
|             | lock-app                                | qpg6105+debug            | (read/write)  |    1090012 |    1090012 |        0 |        0.0 |
|             |                                         |                          | .bss          |      97224 |      97224 |        0 |        0.0 |
|             |                                         |                          | .data         |        844 |        844 |        0 |        0.0 |
|             |                                         |                          | .text         |     602396 |     602396 |        0 |        0.0 |
| stm32       | light                                   | STM32WB5MM-DK            | (read/write)  |     601241 |     601321 |       80 |        0.0 |
|             |                                         |                          | .bss          |     128344 |     128344 |        0 |        0.0 |
|             |                                         |                          | .data         |        668 |        668 |        0 |        0.0 |
|             |                                         |                          | .rodata       |      79700 |      79700 |        0 |        0.0 |
|             |                                         |                          | .text         |     382800 |     382880 |       80 |        0.0 |
| telink      | window-covering                         | tlsr9258a                | (read only)   |      51584 |      51584 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     835696 |     835696 |        0 |        0.0 |
|             |                                         |                          | bss           |      68104 |      68104 |        0 |        0.0 |
|             |                                         |                          | text          |     627192 |     627192 |        0 |        0.0 |
|             | pump-app                                | tlsr9258a_retention      | (read only)   |      51774 |      51774 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     828382 |     828382 |        0 |        0.0 |
|             |                                         |                          | bss           |      49840 |      49840 |        0 |        0.0 |
|             |                                         |                          | text          |     621574 |     621574 |        0 |        0.0 |
|             | all-clusters-app                        | tlsr9518adk80d           | (read only)   |      29042 |      29042 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1092872 |    1093000 |      128 |        0.0 |
|             |                                         |                          | bss           |     101804 |     101804 |        0 |        0.0 |
|             |                                         |                          | text          |     793934 |     794058 |      124 |        0.0 |
|             | bridge-app                              | tlsr9518adk80d           | (read only)   |      29042 |      29042 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     911056 |     911056 |        0 |        0.0 |
|             |                                         |                          | bss           |      93140 |      93140 |        0 |        0.0 |
|             |                                         |                          | text          |     652732 |     652732 |        0 |        0.0 |
|             | lighting-app-ota-rpc-factory-data-4mb   | tlsr9518adk80d           | (read only)   |      29122 |      29122 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1074228 |    1074356 |      128 |        0.0 |
|             |                                         |                          | bss           |     100220 |     100220 |        0 |        0.0 |
|             |                                         |                          | text          |     778116 |     778240 |      124 |        0.0 |
|             | ota-requestor-app                       | tlsr9518adk80d           | (read only)   |      29042 |      29042 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     930028 |     930028 |        0 |        0.0 |
|             |                                         |                          | bss           |      92720 |      92720 |        0 |        0.0 |
|             |                                         |                          | text          |     671810 |     671810 |        0 |        0.0 |
|             | pump-controller-app                     | tlsr9518adk80d           | (read only)   |      31872 |      31872 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     791956 |     791956 |        0 |        0.0 |
|             |                                         |                          | bss           |      56040 |      56040 |        0 |        0.0 |
|             |                                         |                          | text          |     592250 |     592250 |        0 |        0.0 |
|             | shell                                   | tlsr9518adk80d           | (read only)   |      29042 |      29042 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     677312 |     677312 |        0 |        0.0 |
|             |                                         |                          | bss           |      73672 |      73672 |        0 |        0.0 |
|             |                                         |                          | text          |     462570 |     462570 |        0 |        0.0 |
|             | temperature-measurement-app-mars-ota    | tlsr9518adk80d           | (read only)   |      32220 |      32220 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     851917 |     851917 |        0 |        0.0 |
|             |                                         |                          | bss           |      59516 |      59516 |        0 |        0.0 |
|             |                                         |                          | text          |     636960 |     636960 |        0 |        0.0 |
|             | thermostat                              | tlsr9518adk80d           | (read only)   |      31872 |      31872 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     817604 |     817604 |        0 |        0.0 |
|             |                                         |                          | bss           |      56328 |      56328 |        0 |        0.0 |
|             |                                         |                          | text          |     611934 |     611934 |        0 |        0.0 |
|             | all-clusters-minimal-app                | tlsr9528a                | (read only)   |      47960 |      47960 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |    1050344 |    1050464 |      120 |        0.0 |
|             |                                         |                          | bss           |     110108 |     110108 |        0 |        0.0 |
|             |                                         |                          | text          |     765256 |     765380 |      124 |        0.0 |
|             | light-switch-app-ota-shell-factory-data | tlsr9528a                | (read only)   |      51584 |      51584 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     931368 |     931368 |        0 |        0.0 |
|             |                                         |                          | bss           |      77732 |      77732 |        0 |        0.0 |
|             |                                         |                          | text          |     698660 |     698660 |        0 |        0.0 |
|             | lock-app-dfu                            | tlsr9528a                | (read only)   |      51584 |      51584 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     903760 |     903760 |        0 |        0.0 |
|             |                                         |                          | bss           |      69196 |      69196 |        0 |        0.0 |
|             |                                         |                          | text          |     653924 |     653924 |        0 |        0.0 |
|             | air-quality-sensor-app                  | tlsr9528a_retention      | (read only)   |      51774 |      51774 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     824026 |     824026 |        0 |        0.0 |
|             |                                         |                          | bss           |      49684 |      49684 |        0 |        0.0 |
|             |                                         |                          | text          |     616822 |     616822 |        0 |        0.0 |
|             | contact-sensor-app                      | tlsr9528a_retention      | (read only)   |      51774 |      51774 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     825650 |     825650 |        0 |        0.0 |
|             |                                         |                          | bss           |      49732 |      49732 |        0 |        0.0 |
|             |                                         |                          | text          |     618512 |     618512 |        0 |        0.0 |
|             | smoke_co_alarm-app                      | tlsr9528a_retention      | (read only)   |      51774 |      51774 |        0 |        0.0 |
|             |                                         |                          | (read/write)  |     833186 |     833186 |        0 |        0.0 |
|             |                                         |                          | bss           |      51364 |      51364 |        0 |        0.0 |
|             |                                         |                          | text          |     624882 |     624882 |        0 |        0.0 |

</details>

**Review by jmartinez-silabs — APPROVED** [review]

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 3]
```diff
@@ -20,6 +20,29 @@
...
 namespace scenes {
 
+namespace {
+
+/// ValideAttribute
+/// @brief  Validate the attribute exists for a given cluster
+/// @param[in] clusterID  Cluster ID
+/// @param[in] attID      Attribute ID
+/// @return CHIP_ERROR_UNSUPPORTED_CHIP_FEATURE if the attribute does not exist for a given cluster or is not scenable
+/// @note This will allways fail for global list attributes. If we do want to make them scenable someday, we will need to
```
Comment (cecille) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:30]: I don't see how those would ever be scenable, so that's probably not a concern. However, if the client passes in the attribute ID for a global attribute, will this function correctly fail?

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 4]
```diff
@@ -20,6 +20,29 @@
...
+///       use a different validation method.
+// TODO: Assess if we also want to throw an error if the attribute value is out of range
```
Comment (cecille) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:32]: Possibly also if the type is incorrect.

File: src/app/tests/suites/certification/Test_TC_S_2_2.yaml [hunk 5]
```diff
@@ -431,6 +431,21 @@ tests:
               - name: "SceneID"
                 value: 0x01
 
+    - label:
+          "Step 4e: TH sends a RecallScene command to DUT with the GroupID field
+          set to GI (Where GI is a group currently absent from the group table)
+          and the SceneID field set to 0x01."
+      PICS: S.S.C05.Rsp
```
Comment (cecille) [inline src/app/tests/suites/certification/Test_TC_S_2_2.yaml:438]: total nit, but this command is mandatory, so it is probably better to just omit the PICS here - that way you know the step is going to be run on all devices regardless of whether or not the pics is set correctly. The pics file for the CI in particular tends to be improperly defined and is easy to break by accident.

File: src/app/tests/suites/certification/Test_TC_S_2_2.yaml [hunk 6]
```diff
@@ -773,6 +788,150 @@ tests:
               - name: "SceneID"
                 value: 0x01
 
+    - label:
+          "Step 8f: TH sends a AddScene command to DUT with the GroupID field
+          set to G1, the SceneID field set to 0x01, the TransitionTime field set
+          to 1000 (1s) and extension field sets holding an invalid
+          ExtensionField (Invalid attribute ID for given cluster). This should
+          fail and return a status of 0x85 (INVALID_COMMAND)."
+      PICS: S.S.C00.Rsp && PICS_SDK_CI_ONLY
```
Comment (cecille) [inline src/app/tests/suites/certification/Test_TC_S_2_2.yaml:797]: Why does this not work for real devices? Is this because the user needs to send in a scenable attribute ID that doesn't exist? For yaml, you should be able to pass this in as a config variable. If you opted to do this in python, you could just find one by looking through the attribute lists for the various endpoints.

Same for the other mandatory commands below.

File: src/app/tests/suites/certification/Test_TC_S_2_3.yaml [hunk 7]
```diff
@@ -705,6 +705,81 @@ tests:
...
+          values:
+              - name: "GroupID"
+                value: G1
+              - name: "SceneID"
+                value: 0x03
+
+    - label:
+          "Step 6g: TH sends a ViewScene command to DUT with the GroupID field
+          set to G1 and the SceneID field set to 0x03."
+      PICS: S.S.C01.Rsp && PICS_SDK_CI_ONLY
```
Comment (cecille) [inline src/app/tests/suites/certification/Test_TC_S_2_3.yaml:724]: Why is this CI only?

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 4 above)
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:32]: Yes, but that should be checked by the "S" quality since a scenable attribute must be one of the accepted types.

File: src/app/tests/suites/certification/Test_TC_S_2_2.yaml (hunk 6 above)
Comment (lpbeliveau-silabs) [reply src/app/tests/suites/certification/Test_TC_S_2_2.yaml:797]: Because for this command to pass, the OnOff cluster must be supported, otherwise the Scenes cluster would just skip the cluster and store the scene, thus not generating an error.

So this AddScene command must hold the extension field set of a cluster supported on the DUT. 

Same for the other commands

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 8]
```diff
@@ -20,6 +20,29 @@
...
+// TODO: Add check for "S" quality to determine if the attribute is scenable once suported :
+// https://github.com/project-chip/connectedhomeip/issues/24177
+CHIP_ERROR ValidateAttributePath(EndpointId endpoint, ClusterId cluster, AttributeId attributeId)
+{
+    bool attIndex = emberAfContainsAttribute(endpoint, cluster, attributeId);
+    if (!attIndex)
+    {
+        return CHIP_ERROR_UNSUPPORTED_CHIP_FEATURE;
```
[the remark this answers is not in the document]
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp]: Added CHIP_ERROR_UNSUPPORTED_ATTRIBUTE to CHIPError.h

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 4 above)
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp]: The defined behavior in the spec is to cap the value at the maximal range accepted for the specific attribute in the event that a value greater than the expected one is stored. 

I added a check on the value, that way there will be a cap if a uint64 is passed to a uint8 attribute, however the check on maximal allowed value is more tedious as it is a per cluster / per attribute check.

Attributes in our data model do not currently have a "max" or "min" attribute that I know of

Comment (cecille) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp]: Oh, interesting. so you can use a different type than the attribute and that's fine?

Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp]: At least from the Scene Table's perspective, and our TLV Encoder already reduce the save size depending on the value, so as long as it's an integer it is okay.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 9]
```diff
@@ -16,10 +16,60 @@
...
+
+/// CapAttributeID
+/// Cap the attribute value based on the attribute type size
+/// @param[in] aVPair   AttributeValuePairType
+/// @param[in] metadata  EmberAfAttributeMetadata
+///
+void CapAttributeID(AttributeValuePairType & aVPair, const EmberAfAttributeMetadata * metadata)
+{
+    // Calculate the maximum value that can be represented with the given number of bytes
+    uint64_t maxValue = (1ULL << (metadata->size * 8)) - 1;
```
Comment (andy31415) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:37]: should we consider unsigned types? That starts being difficult.

What sizes do we have for arrays or strings ? do we assume this is never called for such a thing (makes sense, however maybe we should check)

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 10]
```diff
@@ -16,10 +16,60 @@
...
+// https://github.com/project-chip/connectedhomeip/issues/24177
+CHIP_ERROR ValidateAttributePath(EndpointId endpoint, ClusterId cluster, AttributeValuePairType & aVPair)
+{
+    bool attIndex = emberAfContainsAttribute(endpoint, cluster, aVPair.attributeID);
+    if (!attIndex)
+    {
+        return CHIP_ERROR_UNSUPPORTED_ATTRIBUTE;
+    }
+
+    EmberAfAttributeMetadata metadata = *emberAfLocateAttributeMetadata(endpoint, cluster, aVPair.attributeID);
```
Comment (andy31415) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:64]: would it make sense to call this and check for nullptr instead of doing `contains` followed by a locate?

File: src/app/tests/TestSceneTable.cpp [hunk 11]
```diff
@@ -152,6 +156,43 @@ static uint32_t OO_buffer_serialized_length = 0;
 static uint32_t LC_buffer_serialized_length = 0;
 static uint32_t CC_buffer_serialized_length = 0;
 
+// clang-format off
+static const MockNodeConfig SceneMockNodeConfig({
+    MockEndpointConfig(kTestEndpoint1, {
+        MockClusterConfig(kScenesClusterId, {}),
+        MockClusterConfig(kOnOffClusterId, {
+            kOnOffAttId
```
Comment (andy31415) [inline src/app/tests/TestSceneTable.cpp:164]: could we use actual attribute IDs? Like `chip::app::Clusters::OnOff::Attributes::OnOff::Id` ? maybe with a `using` clause to make these shorter?

Or are we intentionally using mock values (in which case maybe we should use MockAttributeId)

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 9 above)
Comment (andy31415) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:37]: also BOOLEAN will have size 1, however cap is probably 1.

File: src/app/util/mock/MockNodeConfigImpl.h [hunk 12]
```diff
@@ -0,0 +1,25 @@
...
+ *    See the License for the specific language governing permissions and
+ *    limitations under the License.
+ */
+
+#pragma once
+
+#include <app/util/mock/MockNodeConfig.h>
+
+const chip::Test::MockNodeConfig & GetMockNodeConfig();
+
```
Comment (andy31415) [inline src/app/util/mock/MockNodeConfigImpl.h:24]: Reset should go in here as well if we have one, but since we use a pointer now, we should probably just state we allow nullptr and remove the reset implementation.

Since we pass a pointer, lifetime is not as clear. I would suggest a RAII object that sets a config in a constructor and resets it back in a destructor, so that we can explicitly set the lifetime of config.

File: src/app/util/mock/Functions.h [hunk 13]
```diff
@@ -47,9 +47,6 @@ void ResetVersion();
 /// be returned by emberAfDataVersionStorage
 DataVersion GetVersion();
 
-/// Configures the singular global mock attribute storage to use the specified configuration.
-void SetMockNodeConfig(const MockNodeConfig & config);
-
 /// Resets the mock attribute storage to the default configuration.
 void ResetMockNodeConfig();
```
Comment (andy31415) [inline src/app/util/mock/Functions.h:51]: Reset was also deleted.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 9 above)
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:37]: The only acceptable types are signed and unsigned integers from  8bits to 64bits. I am not sure how we could consider signed types here.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 14]
```diff
@@ -16,10 +16,138 @@
...
+    return (type == ZCL_INT8U_ATTRIBUTE_TYPE || type == ZCL_INT16U_ATTRIBUTE_TYPE || type == ZCL_INT32U_ATTRIBUTE_TYPE ||
+            type == ZCL_INT64U_ATTRIBUTE_TYPE || type == ZCL_INT8S_ATTRIBUTE_TYPE || type == ZCL_INT16S_ATTRIBUTE_TYPE ||
+            type == ZCL_INT32S_ATTRIBUTE_TYPE || type == ZCL_INT64S_ATTRIBUTE_TYPE);
+}
+
+/// IsSignedAttribute
+/// @brief Compare the attribute type to the signed attribute types in ZCL and return true if it is signed.
+/// @param attributeType metadata's attribute type
+/// @return
+bool IsSignedAttribute(EmberAfAttributeType attributeType)
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:44]: This is re-inventing emberAfIsTypeSigned.  Which I know, is not really exposed as API right now, but if we need it, we should expose it, no?  Possibly with a better name like IsSignedIntegerAttribute.  Or even an IsSignedIntegerAttribute() member function on EmberAfAttributeMetadata.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 15]
```diff
@@ -16,10 +16,138 @@
...
+{
+    if (len <= 2)
+    {
+        return static_cast<uint64_t>(defaultValue.defaultValue);
+    }
+    else
+    {
+        uint64_t result     = 0;
+        const uint8_t * val = defaultValue.ptrToDefaultValue;
+        for (size_t i = 0; i < len; i++)
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:65]: I would think this should be using `NumericAttributeTraits` instead of re-inventing that logic, no?

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 16]
```diff
@@ -16,10 +16,138 @@
...
+    {
+        maxValue = (1ULL << ((emberAfAttributeSize(metadata) * 8) - 1)) - 1;
+    }
+    else
+    {
+        maxValue = (1ULL << (emberAfAttributeSize(metadata) * 8)) - 1;
+    }
+
+    // Check metadata for min and max values
+    if ((metadata->mask & ATTRIBUTE_MASK_MIN_MAX) && metadata->defaultValue.ptrToMinMaxValue)
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:95]: Please add an accessor to the metadata struct instead of raw mask checks.

Also, under what conditions would the mask flag be set but ptrToMinMaxValue be null?

File: src/app/tests/suites/certification/Test_TC_S_2_2.yaml (hunk 6 above)
Comment (lpbeliveau-silabs) [reply src/app/tests/suites/certification/Test_TC_S_2_2.yaml:796]: Currently the clusters with scenes attributes are:
ColorControl
DoorLock
LevelControl
ModeBase
ModeSelect
OnOff
Thermostat
WindowCovering

Having a scenes cluster without any of those would be okay, meaning the device could still store scenes with their names transition time, groupid and sceneid. their extensionfield sets would be empty, which would mean the scenes would not take any actions when being recalled

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 17]
```diff
@@ -16,10 +16,156 @@
...
 namespace chip {
 namespace scenes {
 
+namespace {
+
+using ConcreteAttributePath  = app::ConcreteAttributePath;
+using AttributeValuePairType = app::Clusters::ScenesManagement::Structs::AttributeValuePair::Type;
+
+/// ConvertByteArrayToUInt64
+/// @brief Helper function to convert a byte array to a uint64_t value
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:30]:
```suggestion
/// @brief Helper function to convert a byte array to a value of the given type.
```

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 18]
```diff
@@ -16,10 +16,156 @@
...
+/// @param EmberAfDefaultAttributeValue & defaultValue
+/// @param len Length of the byte array
+/// @return uint64_t or int64_t Value
+/// @note The attribute table supports 8 bytes only for unsigned integers, 4 bytes is the maximum for signed integers
+template <typename Type>
+Type ConvertByteArrayToType(const EmberAfDefaultAttributeValue & defaultValue, uint16_t len)
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:36]: I'm not sure this really makes sense as a signature.  Is the "len" not derivable from the "type"?

It feels like if do things this way then the "type" involved should be whatever the template parameter would be for NumericAttributeTraits (more on this below) and the return type of this function would be `NumericAttributeTraits<Type>:WorkingType` or so.

And the "len" is then presumably the same as `sizeof(NumericAttributeTraits<Type>::StorageType)` and if it's not we better have some documentation explaining why.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 19]
```diff
@@ -16,10 +16,156 @@
...
 
 namespace chip {
 namespace scenes {
 
+namespace {
+
+using ConcreteAttributePath  = app::ConcreteAttributePath;
+using AttributeValuePairType = app::Clusters::ScenesManagement::Structs::AttributeValuePair::Type;
+
+/// ConvertByteArrayToUInt64
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:29]: That is not what this function does.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 20]
```diff
@@ -16,10 +16,156 @@
...
+/// @brief Helper function to convert a byte array to a uint64_t value
+/// @param EmberAfDefaultAttributeValue & defaultValue
+/// @param len Length of the byte array
+/// @return uint64_t or int64_t Value
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:33]: That's not what this function returns.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 21]
```diff
@@ -16,10 +16,156 @@
...
+/// @note The attribute table supports 8 bytes only for unsigned integers, 4 bytes is the maximum for signed integers
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:34]: Really?  I am sure we have signed 64-bit things, in general....

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 18 above)
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:36]: This is more of a ConvertDefaultValueToWorkingValue or something, in the nomenclature of NumericAttributeTraits.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 22]
```diff
@@ -16,10 +16,156 @@
...
+        const EmberAfAttributeMinMaxValue * minMaxValue = metadata->defaultValue.ptrToMinMaxValue;
+        Type minVal = ConvertByteArrayToType<Type>(minMaxValue->minValue, emberAfAttributeSize(metadata));
+        Type maxVal = ConvertByteArrayToType<Type>(minMaxValue->maxValue, emberAfAttributeSize(metadata));
+
+        // Cap based on minimum value
+        if (minVal > static_cast<Type>(aVPair.attributeValue))
+        {
+            uint64_t sValue = 0;
+            memcpy(&sValue, &minVal, sizeof(Type));
+            aVPair.attributeValue = app::NumericAttributeTraits<uint64_t>::StorageToWorking(sValue);
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:84]: This does not make sense to me.  Let's say Type is uint8_t and we are on a big-endian system.  What happens here?

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 23]
```diff
@@ -16,10 +16,156 @@
...
+
+        // Adjust maxValue if greater than the meta data's max value
+        if (maxVal < maxValue)
+        {
+            maxValue = maxVal;
+        }
+    }
+
+    // Cap based on maximum value
+    if (metadata->IsSignedIntegerAttribute())
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:97]: Don't we already know this information based on Type, at compile time?  This feels pretty strange to me...

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 24]
```diff
@@ -16,10 +16,156 @@
...
+        if (static_cast<int64_t>(aVPair.attributeValue) > static_cast<int64_t>(maxValue))
+        {
+            uint64_t sValue = 0;
+            memcpy(&sValue, &maxValue, sizeof(Type));
+            aVPair.attributeValue = app::NumericAttributeTraits<uint64_t>::StorageToWorking(sValue);
+        }
+    }
+    else
+    {
+        if (static_cast<uint64_t>(aVPair.attributeValue) > static_cast<uint64_t>(maxValue))
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:108]: Isn't `aVPair.attributeValue` already a `uint64_t`?  And why do we need to cast maxValue to anything?

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 25]
```diff
@@ -16,10 +16,156 @@
...
+    }
+
+    // Cap based on maximum value
+    if (metadata->IsSignedIntegerAttribute())
+    {
+        if (static_cast<int64_t>(aVPair.attributeValue) > static_cast<int64_t>(maxValue))
+        {
+            uint64_t sValue = 0;
+            memcpy(&sValue, &maxValue, sizeof(Type));
+            aVPair.attributeValue = app::NumericAttributeTraits<uint64_t>::StorageToWorking(sValue);
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:103]: Again, this does not make sense to me....

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 26]
```diff
@@ -16,10 +16,156 @@
...
+    case ZCL_INT8U_ATTRIBUTE_TYPE:
+        CapAttributeID<uint8_t>(aVPair, metadata);
+        break;
+    case ZCL_INT16U_ATTRIBUTE_TYPE:
+        CapAttributeID<uint16_t>(aVPair, metadata);
+        break;
+    case ZCL_INT32U_ATTRIBUTE_TYPE:
+        CapAttributeID<uint32_t>(aVPair, metadata);
+        break;
+    case ZCL_INT64U_ATTRIBUTE_TYPE:
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:146]: What happened to 24, 40, 48, 56?  We absolutely have int24* attributes around in standardized clusters.  Incidentally, that's why `NumericAttributeTraits` comes in handy; together with `OddSizedInteger` it helps you handle all that stuff sanely (e.g. `NumericAttributeTraits<OddSizedInteger<3, true>>::StorageToWorking` will convert from a 3-byte buffer to a 32-bit unsigned integer that you can then actually work with....

Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:146]: So the Scenes Spec doesn't allow those types but does say in the event we would ever add a "Scene" quality attribute with an odd sized integer, we should convert it to one of the types in this case.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 24 above)
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:108]: The casting is to ensure that they are both compared as uint64_t, I could have swore the type promotion didn't work as expected in a previous test but it seems I was wrong. We do need to cast maxValue for compare to silence warnings on different type comparison though.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 23 above)
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:97]: This is because we keep the value in it's type's size inside of attributeValue,
Eg -1 for an int16_t would be stored as FFFF'0000'0000'0000 instead of FFFF'FFFF'FFFF'FFFF,
So we need to cast it as a uint64_t for the comparison only.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 18 above)
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp]: Agreed, sizeof, is cleaner to use here

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 21 above)
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp]: Either way, removed the note from the comment.

File: src/app/tests/TestSceneTable.cpp [hunk 27]
```diff
@@ -681,6 +722,77 @@ void TestHandlerFunctions(nlTestSuite * aSuite, void * aContext)
...
+                   CHIP_NO_ERROR == sHandler.Deserialize(kTestEndpoint1, kOnOffClusterId, buff_span, extensionFieldValueCapOut));
+
+    // Verify that the output value is capped
+    NL_TEST_ASSERT(aSuite, extensionFieldValueCapOut.attributeValueList[0].attributeValue == 0x007FFFFF);
+
+    // Clear buffer
+    memset(buffer, 0, buff_span.size());
+
+    // Test Serialize Add of an attribute value that is smaller than the mock attribute min (-2)
+    OOPairs[0].attributeValue = 0xFFFFFFFF'FFFFFFFE;
```
Comment (bzbarsky-apple) [inline src/app/tests/TestSceneTable.cpp:764]: So I am confused.  I thought we were representing -2 as `0xFE` for a one-byte signed thing.  IS this one not one-byte?

File: src/app/tests/suites/certification/Test_TC_S_2_2.yaml [hunk 28]
```diff
@@ -773,6 +787,150 @@ tests:
...
+                value: 1000
+              - name: "SceneName"
+                value: "Scene1"
+              - name: "ExtensionFieldSets"
+                value:
+                    [
+                        {
+                            ClusterID: 0x0006,
+                            AttributeValueList:
+                                [{ AttributeID: 0xFFFF, AttributeValue: 0x01 }],
```
Comment (bzbarsky-apple) [inline src/app/tests/suites/certification/Test_TC_S_2_2.yaml:814]: The spec does not have `AttributeValue`.  What am I missing?

Or rather, it talks about AttributeValue in various places, but  AttributeValuePairStruct does not have an AttributeValue field.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 29]
```diff
@@ -16,10 +16,186 @@
...
+    if (metadata->IsSignedIntegerAttribute())
+    {
+        if (static_cast<int64_t>(aVPair.attributeValue) > static_cast<int64_t>(maxValue))
+        {
+            aVPair.attributeValue = static_cast<std::make_unsigned_t<WorkingType>>(maxValue);
+        }
+    }
+    else
+    {
+        if (aVPair.attributeValue > static_cast<uint64_t>(maxValue))
```
[the remark this answers is not in the document]
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:111]: To silence compiler warnings `comparison of integers of different signs:` that appear without this cast. Since the compiler doesn't understand `metadata->IsSignedIntegerAttribute()`, it assumes we could end up on this path for a signed integer and throws warning if we don't cast here.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 30]
```diff
@@ -16,10 +16,186 @@
...
+        {
+            aVPair.attributeValue = static_cast<std::make_unsigned_t<WorkingType>>(maxValue);
```
[the remark this answers is not in the document]
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:113]: Right, the double casting is not necessary, but we still need to silence the same warning as above.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 29 above)
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:111]: Then this could use a comment.  Though we could also use an `if constexpr` test on the signedness of WorkingType instead of doing the dynamic check, and then this would not be a problem....  And presumably a VerifyOrDie that the signedness of the metadata matches the signedness of WorkingType.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 30 above)
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:113]: See https://github.com/project-chip/connectedhomeip/pull/32632#discussion_r1580230198

File: src/app/tests/TestSceneTable.cpp (hunk 27 above)
Comment (lpbeliveau-silabs) [reply src/app/tests/TestSceneTable.cpp:764]: So the hypothetical attribute for this test is:
```
EmberAfAttributeMetadata mockmetadata = { .defaultValue  = EmberAfDefaultOrMinMaxAttributeValue(&minMaxValue),
                                          .attributeId   = 0,
                                          .size          = sizeof(int32_t),
                                          .attributeType = ZCL_INT24S_ATTRIBUTE_TYPE,
                                          .mask          = ATTRIBUTE_MASK_MIN_MAX }; // namespace
```
But we are simulating that -2 arrived on the wire in the for of an int64_t and it would be capped to the minimal value in the working type, hence giving -1 in a uint32_t.

As you have noted above, this convoluted example does not test every possible solution, and the spec is not exactly clear as to what the outcome should even be for that specific case, so more metadata and test will be added.

File: src/app/tests/suites/certification/Test_TC_S_2_2.yaml (hunk 28 above)
Comment (lpbeliveau-silabs) [reply src/app/tests/suites/certification/Test_TC_S_2_2.yaml:814]: I will open another PR to address that before we merge this one as we need a spec clarification.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 31]
```diff
@@ -16,10 +16,186 @@
...
+
+        // Cap based on minimum value
+        if (minVal > static_cast<WorkingType>(aVPair.attributeValue))
+        {
+            aVPair.attributeValue = static_cast<std::make_unsigned_t<WorkingType>>(minVal);
+            // We assume the max is >= min therefore we can return
+            return;
+        }
+
+        // Adjust maxValue if greater than the meta data's max value
```
[the remark this answers is not in the document]
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:100]: Only for the signed ones right? Since unsigned type min is always zero

[the remark this answers is not in the document]
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:103]: Either way, for now we treat overflowing the attribute type as greater than max since we cannot know the position of the sign bit (Nor the actual signedness that was received).

File: src/app/tests/suites/certification/Test_TC_S_2_2.yaml (hunk 28 above)
Comment (lpbeliveau-silabs) [reply src/app/tests/suites/certification/Test_TC_S_2_2.yaml:814]: Keeping this open as we should not merge this before:
A: Closing the Spec PR
B: Refactoring AttributeValue to the spec description.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 32]
```diff
@@ -16,10 +16,224 @@
...
+
+/// ConvertDefaultValueToWorkingValue
+/// @brief Helper function to convert a byte array to a value of the given type.
+/// @param EmberAfDefaultAttributeValue & defaultValue
+/// @return Value converted to the given working type
+template <typename Type>
+typename app::NumericAttributeTraits<Type>::WorkingType
+ConvertDefaultValueToWorkingValue(const EmberAfDefaultAttributeValue & defaultValue)
+{
+    if (sizeof(typename app::NumericAttributeTraits<Type>::WorkingType) <= 2)
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:40]:
```suggestion
    if constexpr (sizeof(typename app::NumericAttributeTraits<Type>::WorkingType) <= 2)
```

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 33]
```diff
@@ -16,10 +16,224 @@
...
+        return static_cast<typename app::NumericAttributeTraits<Type>::WorkingType>(defaultValue.defaultValue);
+    }
+
+    typename app::NumericAttributeTraits<Type>::StorageType sValue;
+    memcpy(&sValue, defaultValue.ptrToDefaultValue, sizeof(sValue));
+    return app::NumericAttributeTraits<Type>::StorageToWorking(sValue);
+}
+
+/// IsOnlyOneValuePopulated
+/// @brief Helper function to verify if only one value is populated in a given AttributeValuePairType
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:51]:
```suggestion
/// @brief Helper function to verify that exactly one value is populated in a given AttributeValuePairType
```

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 34]
```diff
@@ -16,10 +16,224 @@
...
+/// @param AttributeValuePairType & type AttributeValuePairType to verify
+/// @return bool true if only one value is populated, false otherwise
+bool IsOnlyOneValuePopulated(const AttributeValuePairType & type)
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:54]:
```suggestion
bool IsExactlyOneValuePopulated(const AttributeValuePairType & type)
```
since this checks that it's not _fewer_ than 1 as well.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 35]
```diff
@@ -16,10 +16,224 @@
...
+void CapAttributeID(typename app::NumericAttributeTraits<Type>::WorkingType & Value, const EmberAfAttributeMetadata * metadata)
+{
+    using IntType     = app::NumericAttributeTraits<Type>;
+    using WorkingType = typename IntType::WorkingType;
+
+    WorkingType maxValue;
+    WorkingType minValue;
+    uint16_t bitWidth = static_cast<uint16_t>(emberAfAttributeSize(metadata) * 8);
+
+    // Min/Max Value capps for the OddSize integers
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:92]:
```suggestion
    // Min/Max Value caps for the OddSize integers
```

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 36]
```diff
@@ -16,10 +16,224 @@
...
+    if (metadata->IsSignedIntegerAttribute())
+    {
+        // We use emberAfAttributeSize for cases like INT24S, INT40S, INT48S, INT56S where numeric_limits<WorkingType>::max()
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:95]: Followup: NumericAttributeTraits should just have max/min on it?

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 37]
```diff
@@ -16,10 +16,224 @@
...
+        // wouldn't work
+        maxValue = static_cast<WorkingType>((1ULL << (bitWidth - 1)) - 1);
+        minValue = static_cast<WorkingType>(-(1ULL << (bitWidth - 1)));
+    }
+    else
+    {
+        // We use emberAfAttributeSize for cases like INT24U, INT40U, INT48U, INT56U where numeric_limits<WorkingType>::max()
+        // wouldn't work
+        if (ZCL_INT64U_ATTRIBUTE_TYPE == metadata->attributeType)
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:104]: This is going to fail badly for attributes with types like ZCL_BITMAP64_ATTRIBUTE_TYPE, ZCL_NODE_ID_ATTRIBUTE_TYPE, etc, etc.

Followup: we need to not be doing any of this stuff with metadata.  We already know the type: it's Type.  The min/max should just come from that.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 38]
```diff
@@ -16,10 +16,224 @@
...
+}
+
+/// CapAttributeID
+/// Cap the attribute value based on the attribute's min and max if they are defined,
+/// or based on the attribute's size if they are not.
+/// @param[in] aVPair   AttributeValuePairType
+/// @param[in] metadata  EmberAfAttributeMetadata
+///
+template <typename Type>
+void CapAttributeID(typename app::NumericAttributeTraits<Type>::WorkingType & Value, const EmberAfAttributeMetadata * metadata)
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:83]:
```suggestion
void CapAttributeValue(typename app::NumericAttributeTraits<Type>::WorkingType & value, const EmberAfAttributeMetadata * metadata)
```

We are not capping the _ID_.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 39]
```diff
@@ -16,10 +16,224 @@
...
+        {
+            maxValue = static_cast<WorkingType>((1ULL << bitWidth) - 1);
+        }
+        minValue = static_cast<WorkingType>(0);
+    }
+
+    // Ensure that the metadata's signedness matches the working type's signedness
+    VerifyOrDie(metadata->IsSignedIntegerAttribute() == std::is_signed<WorkingType>::value);
+
+    if (metadata->IsBoolean())
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:118]: This would be handled correctly by the right min/max on NumericAttributeTraits<bool>, per the above followups.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 40]
```diff
@@ -16,10 +16,224 @@
...
+
+    if (nullptr == metadata)
+    {
+        return CHIP_IM_GLOBAL_STATUS(UnsupportedAttribute);
+    }
+
+    // There should never be more than one populated value in an ExtensionFieldSet
+    VerifyOrReturnError(IsOnlyOneValuePopulated(aVPair), CHIP_ERROR_INVALID_ARGUMENT);
+
+    switch (metadata->attributeType)
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:164]: Should this be using `AttributeBaseType(metadata->attributeType)`?  Followup fine for this, but I think it should.  And then we can have fewer cases below; right now we are including some "integer like" types in the cases but not others, which is very odd.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 41]
```diff
@@ -16,10 +16,224 @@
...
+    case ZCL_INT24U_ATTRIBUTE_TYPE:
+        VerifyOrReturnError(aVPair.valueUnsigned32.HasValue(), CHIP_ERROR_INVALID_ARGUMENT);
+        CapAttributeID<OddSizedInteger<3, false>>(aVPair.valueUnsigned32.Value(), metadata);
+        break;
+    case ZCL_BITMAP32_ATTRIBUTE_TYPE:
+    case ZCL_INT32U_ATTRIBUTE_TYPE:
+        VerifyOrReturnError(aVPair.valueUnsigned32.HasValue(), CHIP_ERROR_INVALID_ARGUMENT);
+        CapAttributeID<uint32_t>(aVPair.valueUnsigned32.Value(), metadata);
+        break;
+    case ZCL_INT48U_ATTRIBUTE_TYPE:
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:188]: What happened to ZCL_INT40U_ATTRIBUTE_TYPE?

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 42]
```diff
@@ -16,10 +16,224 @@
...
+        break;
+    case ZCL_INT24S_ATTRIBUTE_TYPE:
+        VerifyOrReturnError(aVPair.valueSigned32.HasValue(), CHIP_ERROR_INVALID_ARGUMENT);
+        CapAttributeID<OddSizedInteger<3, true>>(aVPair.valueSigned32.Value(), metadata);
+        break;
+    case ZCL_INT32S_ATTRIBUTE_TYPE:
+        VerifyOrReturnError(aVPair.valueSigned32.HasValue(), CHIP_ERROR_INVALID_ARGUMENT);
+        CapAttributeID<int32_t>(aVPair.valueSigned32.Value(), metadata);
+        break;
+    case ZCL_INT48S_ATTRIBUTE_TYPE:
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:217]: Where is ZCL_INT40S_ATTRIBUTE_TYPE?

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 43]
```diff
@@ -58,7 +272,9 @@ DefaultSceneHandlerImpl::SerializeAdd(EndpointId endpoint, const ExtensionFieldS
     auto pair_iterator = extensionFieldSet.attributeValueList.begin();
     while (pair_iterator.Next())
     {
-        aVPairs[pairCount] = pair_iterator.GetValue();
+        AttributeValuePairType currentPair = pair_iterator.GetValue();
+        ReturnErrorOnFailure(ValidateAttributePath(endpoint, extensionFieldSet.clusterID, currentPair));
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:276]: So that will clamp to range, but for a nullable attribute, isn't it supposed to turn out-of-range to null instead of clamping?  Where is that implemented?  Or is that not relevant here?

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 36 above)
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:96]: Created issue here:
https://github.com/project-chip/connectedhomeip/issues/35328

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 37 above)
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:105]: Added check on AttributeBaseType for now.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp [hunk 44]
```diff
@@ -130,13 +134,20 @@ void CapAttributeID(typename app::NumericAttributeTraits<Type>::WorkingType & Va
         maxValue                                        = ConvertDefaultValueToWorkingValue<Type>(minMaxValue->maxValue);
     }
 
-    if (minValue > Value)
+    if (metadata->IsNullable() && (minValue > value || maxValue < value))
+    {
+        // If the attribute is nullable, the value can be set to NULL
```
Comment (bzbarsky-apple) [inline src/app/clusters/scenes-server/SceneHandlerImpl.cpp:139]: But if the value is nullable your min/max above are wrong...

File: src/app/tests/TestSceneTable.cpp [hunk 45]
```diff
@@ -1046,7 +1065,7 @@ TEST_F(TestSceneTable, TestHandlerFunctions)
         MockCCPairs[5].attributeID = MockAttributeId(kEnhancedColorMode);
         MockCCPairs[5].valueSigned8.SetValue(static_cast<int8_t>(-2)); // will cap to -1
         MockCCPairs[6].attributeID = MockAttributeId(kColorLoopActiveId);
-        MockCCPairs[6].valueSigned16.SetValue(static_cast<int16_t>(0x7FFF)); // will cap to 0x7FFE in int16
+        MockCCPairs[6].valueSigned16.SetValue(static_cast<int16_t>(0x7FFE)); // will cap to 0x7FFD in int16
```
Comment (bzbarsky-apple) [inline src/app/tests/TestSceneTable.cpp:1068]: I don't get any of this.  What's capping to 0x7FFD?  The max int16 value is 0x7FFF.

File: src/app/tests/TestSceneTable.cpp [hunk 46]
```diff
@@ -1223,6 +1247,47 @@ TEST_F(TestSceneTable, TestHandlerFunctions)
...
+        EXPECT_EQ(pair.valueSigned64.Value(), MockFKPairs[1].valueSigned64.Value());
+
+        // Verify that we cap the value to the mock attribute size when serializing
+        EXPECT_EQ(CHIP_NO_ERROR, mpSceneHandler->SerializeAdd(kTestEndpoint4, extensionFieldValueCapIn, buff_span));
+        EXPECT_EQ(CHIP_NO_ERROR,
+                  mpSceneHandler->Deserialize(kTestEndpoint4, MockClusterId(kFakeClusterId), buff_span, extensionFieldValueCapOut));
+
+        // Verify that the output value is capped to uint40 max value
+        uint64_t uint40Max = static_cast<uint64_t>(0x000000FFFFFFFFFF);
+        EXPECT_EQ(uint40Max, static_cast<uint64_t>(extensionFieldValueCapOut.attributeValueList[0].valueUnsigned64.Value()));
```
Comment (bzbarsky-apple) [inline src/app/tests/TestSceneTable.cpp:1282]: Why is there a static_cast here?

File: src/app/tests/TestSceneTable.cpp [hunk 47]
```diff
@@ -1223,6 +1247,47 @@ TEST_F(TestSceneTable, TestHandlerFunctions)
...
+
+        // Verify that the output value is not capped
```
Comment (bzbarsky-apple) [inline src/app/tests/TestSceneTable.cpp:1284]: That's ... not what the code ends up testing?

Comment (lpbeliveau-silabs) [reply src/app/tests/TestSceneTable.cpp:1284]: bad copy paste

File: src/app/tests/TestSceneTable.cpp (hunk 45 above)
Comment (lpbeliveau-silabs) [reply src/app/tests/TestSceneTable.cpp:1068]: The maximum is forced in the mock attribute declaration. The goal was to test a value cap to max when the input value is above the limit but lower than a NULL representation. The cap is declared by `minMaxValue16S` above.

File: src/app/clusters/scenes-server/SceneHandlerImpl.cpp (hunk 44 above)
Comment (lpbeliveau-silabs) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:139]: True but since without a specific metadata min/max, the max for a uint and min for an int will be UINTMAX - 1 and INTMIN + 1, doesn't that end up being the same?
Say for uint8, with a max of 0xFE, the only value above max will already be considered NULL so no changes will be required.
Same for int8 where -128 would be considered a NULL value without needing to enter this if condition.

Comment (bzbarsky-apple) [reply src/app/clusters/scenes-server/SceneHandlerImpl.cpp:139]: Yes, you are right.  Maybe just add a comment for now that if the value is outside the nullable range but inside the non-nullable range then it's already set to null so no need to do anything?

File: src/app/tests/TestSceneTable.cpp [hunk 48]
```diff
@@ -1065,7 +1065,8 @@ TEST_F(TestSceneTable, TestHandlerFunctions)
         MockCCPairs[5].attributeID = MockAttributeId(kEnhancedColorMode);
         MockCCPairs[5].valueSigned8.SetValue(static_cast<int8_t>(-2)); // will cap to -1
         MockCCPairs[6].attributeID = MockAttributeId(kColorLoopActiveId);
-        MockCCPairs[6].valueSigned16.SetValue(static_cast<int16_t>(0x7FFE)); // will cap to 0x7FFD in int16
+        MockCCPairs[6].valueSigned16.SetValue(
+            static_cast<int16_t>(0x7FFE)); // will cap to 0x7FFD in int16 du to declared maximum in the attribute's mock metadata
```
Comment (bzbarsky-apple) [inline src/app/tests/TestSceneTable.cpp:1069]:
```suggestion
            static_cast<int16_t>(0x7FFE)); // will cap to 0x7FFD in int16 due to declared maximum in the attribute's mock metadata
```

**Review by bzbarsky-apple — APPROVED** [review]
