### PR TITLE
Fix clang-tidy error in PersistedCounter.h

### LINKED ISSUE #37854: [Tooling] clang-tidy error - returning without writing to variable
### Reproduction steps / Feature

clang-tidy claims that we're returning without writing to `aStartValue`:

```
/Users/runner/work/connectedhomeip/connectedhomeip/out/default/../../src/app/server/Server.cpp:287:11: note: Calling 'PersistedCounter::Init'
  287 |     err = sGlobalEventIdCounter.Init(mDeviceStorage, DefaultStorageKeyAllocator::IMEventNumber(),
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  288 |                                      CHIP_DEVICE_CONFIG_EVENT_ID_COUNTER_EPOCH);
      |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/lib/support/PersistedCounter.h:82:29: note: Assuming the condition is true
   82 |         VerifyOrReturnError(aStorage != nullptr, CHIP_ERROR_INVALID_ARGUMENT);
      |                             ^
../../src/lib/support/PersistedCounter.h:82:9: note: Taking false branch
   82 |         VerifyOrReturnError(aStorage != nullptr, CHIP_ERROR_INVALID_ARGUMENT);
      |         ^
../../src/lib/support/PersistedCounter.h:82:9: note: Loop condition is false.  Exiting loop
   82 |         VerifyOrReturnError(aStorage != nullptr, CHIP_ERROR_INVALID_ARGUMENT);
      |         ^
../../src/lib/support/PersistedCounter.h:83:9: note: Taking false branch
   83 |         VerifyOrReturnError(aKey.IsInitialized(), CHIP_ERROR_INVALID_ARGUMENT);
      |         ^
../../src/lib/support/PersistedCounter.h:83:9: note: Loop condition is false.  Exiting loop
   83 |         VerifyOrReturnError(aKey.IsInitialized(), CHIP_ERROR_INVALID_ARGUMENT);
      |         ^
../../src/lib/support/PersistedCounter.h:84:29: note: 'aEpoch' is > 0
   84 |         VerifyOrReturnError(aEpoch > 0, CHIP_ERROR_INVALID_INTEGER_VALUE);
      |                             ^
../../src/lib/support/PersistedCounter.h:84:9: note: Taking false branch
   84 |         VerifyOrReturnError(aEpoch > 0, CHIP_ERROR_INVALID_INTEGER_VALUE);
      |         ^
../../src/lib/support/PersistedCounter.h:84:9: note: Loop condition is false.  Exiting loop
   84 |         VerifyOrReturnError(aEpoch > 0, CHIP_ERROR_INVALID_INTEGER_VALUE);
      |         ^
../../src/lib/support/PersistedCounter.h:90:9: note: 'startValue' declared without an initial value
   90 |         T startValue;
      |         ^~~~~~~~~~~~
../../src/lib/support/PersistedCounter.h:93:30: note: Calling 'PersistedCounter::ReadStartValue'
   93 |         ReturnErrorOnFailure(ReadStartValue(startValue));
      |                              ^
../../src/lib/support/PersistedCounter.h:232:9: note: Loop condition is false.  Exiting loop
  232 |         VerifyOrReturnError(mKey.IsInitialized(), CHIP_ERROR_INCORRECT_STATE);
      |         ^
../../src/lib/support/PersistedCounter.h:235:9: note: Taking false branch
  235 |         if (err == CHIP_ERROR_PERSISTED_STORAGE_VALUE_NOT_FOUND)
      |         ^
../../src/lib/support/PersistedCounter.h:245:13: note: Taking true branch
  245 |             ReturnErrorOnFailure(err);
      |             ^
../../src/lib/support/PersistedCounter.h:245:13: note: Returning without writing to 'aStartValue'
  245 |             ReturnErrorOnFailure(err);
      |             ^
../../src/lib/support/PersistedCounter.h:93:30: note: Returning from 'PersistedCounter::ReadStartValue'
   93 |         ReturnErrorOnFailure(ReadStartValue(startValue));
      |                              ^
../../src/lib/support/PersistedCounter.h:93:9: note: Taking false branch
   93 |         ReturnErrorOnFailure(ReadStartValue(startValue));
      |         ^
../../src/lib/support/PersistedCounter.h:93:9: note: Loop condition is false.  Exiting loop
   93 |         ReturnErrorOnFailure(ReadStartValue(startValue));
      |         ^
../../src/lib/support/PersistedCounter.h:108:78: note: The left operand of '+' is a garbage value
  108 |         ReturnErrorOnFailure(PersistNextEpochStart(static_cast<T>(startValue + aEpoch)));
      |                                                                              ^
```

### Platform

darwin

### Platform Version(s)

_No response_

### Type

CI tested

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

Failed job: https://github.com/project-chip/connectedhomeip/actions/runs/13631159299/job/38107715575?pr=37807

### PR DESCRIPTION
**Pull request by adigie**
Assign 0 to suppress the warning. In case of error, the value wont't be used anyway.

Fixes #37854.

#### Testing
Tested by CI

https://github.com/project-chip/connectedhomeip/actions/runs/13675355334/job/38234550494?pr=37855
```
2025-03-03T22:53:03.4922710Z INFO    Will tidy /Users/runner/work/connectedhomeip/connectedhomeip/src/app/server/Server.cpp
2025-03-03T22:53:14.1556740Z INFO    Successfully processed 1 path(s)
```

### CODE REVIEW

File: src/lib/support/PersistedCounter.h [hunk 1]
```diff
@@ -240,6 +240,11 @@ class PersistedCounter : public MonotonicallyIncreasingCounter<T>
         }
         else
         {
+            // clang-tidy claims that we're returning without writing to 'aStartValue',
+            // assign 0 to supppress the warning. In case of error, the value wont't be
+            // used anyway.
+            aStartValue = 0;
```
Comment (andy31415) [inline src/lib/support/PersistedCounter.h:246]: setting it here feels odd ... why not at the top then?

Comment (adigie) [reply src/lib/support/PersistedCounter.h]: Moved to the top.

**Review by ArekBalysNordic — APPROVED** [review]

File: src/app/server/Server.cpp [hunk 2]
```diff
@@ -104,7 +104,7 @@ static app::CircularEventBuffer sLoggingBuffer[CHIP_NUM_EVENT_LOGGING_BUFFERS];
 
 CHIP_ERROR Server::Init(const ServerInitParams & initParams)
 {
-    ChipLogProgress(AppServer, "Server initializing...");
+    ChipLogProgress(AppServer, "Server initializing....");
```
Comment (Damian-Nordic) [inline src/app/server/Server.cpp:107]: Hmm. Why this change?

Comment (adigie) [reply src/app/server/Server.cpp:107]: Just to trigger `clang-tidy`, I will drop the commit before merging.

**Review by Damian-Nordic — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
