### PR TITLE
[chip-cert] Added Print Certification Declaration (CD) Command to the Tool

### LINKED ISSUE #22604: [1.0] Need Command To Print Certification Declaration (CD) Content
### Reproduction steps

```bash
This command is needed for testing and development purposes.
```

### Bug prevalence

100% of the time

### GitHub hash of the SDK that was being used

8626d3919ac7480798c613af825543f4c9c2e4a6

### Platform

core

### Platform Version(s)

_No response_

### Type

Test Improvement

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by emargolis**
#### Issue Being Resolved
#22604

#### Change overview
New `print-cd` command is added to the `chip-cert` tool.

Examples how this new command can be used:
`./out/debug/standalone/chip-cert print-cd credentials/development/commissioner_dut/struct_cd_pid_array_count100_valid/cd.der`

`./out/debug/standalone/chip-cert print-cd credentials/development/commissioner_dut/struct_cd_authorized_paa_list_count10_valid/cd.der`

`./out/debug/standalone/chip-cert print-cd 3081f506092a864886f70d010702a081e73081e4020103310d300b0609608648016503040201305006092a864886f70d010701a0430441152400012501f2ff360205018005028018250334122c04135a494732303134325a423333303030322d3234240500240600250794262408002509f1ff250a008018317e307c020103801462fa823359acfaa9963e1cfa140addf504f37160300b0609608648016503040201300a06082a8648ce3d04030204483046022100926296f7578158be7c459388336ca7383766c9eedd9855cbda6f4cf6bdf43211022100e0dbf4a2bcec4ea274baf0dea208b3365c6ed544086d101afdaf079a2c23e0de`

### CODE REVIEW

File: src/lib/core/CHIPTLVDebug.cpp [hunk 1]
```diff
@@ -147,7 +147,10 @@ static void DumpHandler(DumpWriter aWriter, const char * aIndent, const TLVReade
         case kTLVType_ByteString:
             err = temp.GetDataPtr(strbuf);
             VerifyOrExit(err == CHIP_NO_ERROR, aWriter("Error in kTLVType_ByteString"));
-            aWriter("%p\n", strbuf);
+            for (uint32_t i = 0; i < len; i++)
```
Comment (emargolis) [inline src/lib/core/CHIPTLVDebug.cpp:150]: @mrjerryjohns PTAL if these changes in the `CHIPTLVDebug.cpp` are valid.

Comment (andy31415) [reply src/lib/core/CHIPTLVDebug.cpp:150]: Can we have a unit test for these things?

File: src/lib/core/CHIPTLVDebug.cpp [hunk 2]
```diff
@@ -147,7 +147,10 @@ static void DumpHandler(DumpWriter aWriter, const char * aIndent, const TLVReade
...
+            {
+                aWriter("%02X", strbuf[i]);
```
Comment (mrjerryjohns) [inline src/lib/core/CHIPTLVDebug.cpp:152]:
```suggestion
                aWriter("0x%02X ", strbuf[i]);
```

Comment (mrjerryjohns) [reply src/lib/core/CHIPTLVDebug.cpp:152]: This makes it more obvious it is not decimal, and prevents confusion around endian-ness.

File: src/tools/chip-cert/Cmd_PrintCD.cpp [hunk 3]
```diff
@@ -0,0 +1,277 @@
...
+    }
+
+    return kCDFormat_Unknown;
+}
+
+bool ReadCD(const char * fileNameOrStr, MutableByteSpan cd)
+{
+    CDFormat cdFmt = kCDFormat_Unknown;
+    uint32_t cdLen = 0;
+    std::unique_ptr<uint8_t[]> cdBuf;
```
Comment (tcarmelveilleux) [inline src/tools/chip-cert/Cmd_PrintCD.cpp:165]: A better object here is `std::vector`

File: src/tools/chip-cert/Cmd_PrintCD.cpp [hunk 4]
```diff
@@ -0,0 +1,277 @@
...
+        VerifyOrReturnError(ReadFileIntoMem(fileNameOrStr, cdBuf.get(), cdLen), false);
+
+        cdFmt = DetectCDFormat(cdBuf.get(), cdLen);
+        if (cdFmt == kCDFormat_Unknown)
+        {
+            fprintf(stderr, "Unrecognized CD Format in File: %s\n", fileNameOrStr);
+            return false;
+        }
+    }
+    // Otherwise, treat fileNameOrStr as a pointer to the certificate string
```
Comment (tcarmelveilleux) [inline src/tools/chip-cert/Cmd_PrintCD.cpp:183]: What does "certificate string" mean? Does it mean hex? If so, please say "as hex"

File: src/tools/chip-cert/Cmd_PrintCD.cpp [hunk 5]
```diff
@@ -0,0 +1,277 @@
...
+    return true;
+}
+
+void ENFORCE_FORMAT(1, 2) SimpleDumpWriter(const char * aFormat, ...)
+{
+    va_list args;
+
+    va_start(args, aFormat);
+
+    vprintf(aFormat, args);
```
Comment (tcarmelveilleux) [inline src/tools/chip-cert/Cmd_PrintCD.cpp:225]: This only works on stdout, not to an output file.

Suggest have a `gDumpWriteOutputFile` in anonymous namespace and using `vfprintf`

File: src/tools/chip-cert/Cmd_PrintCD.cpp [hunk 6]
```diff
@@ -0,0 +1,277 @@
...
+    uint32_t signerKeyIdHexLen = 0;
+
+    VerifyOrReturnError(!cd.empty(), false);
+    VerifyOrReturnError(OpenFile(fileName, file, true), false);
+    VerifyOrReturnError(CMS_ExtractKeyId(cd, signerKeyId) == CHIP_NO_ERROR, false);
+    VerifyOrReturnError(CMS_ExtractCDContent(cd, cdContent) == CHIP_NO_ERROR, false);
+
+    signerKeyIdHexLen = 2 * static_cast<uint32_t>(signerKeyId.size()) + 1;
+    signerKeyIdHex    = std::unique_ptr<char[]>(new char[signerKeyIdHexLen]);
+    VerifyOrReturnError(BytesToHex(signerKeyId.data(), signerKeyId.size(), signerKeyIdHex.get(), signerKeyIdHexLen,
```
Comment (tcarmelveilleux) [inline src/tools/chip-cert/Cmd_PrintCD.cpp:246]: `BytesToUppercaseHexString` avoids needing the HexFlags and is clearer up-front.

File: src/lib/core/CHIPTLVDebug.cpp (hunk 1 above)
Comment (tcarmelveilleux) [reply src/lib/core/CHIPTLVDebug.cpp:150]: +1 to unit test

Comment (emargolis) [reply src/lib/core/CHIPTLVDebug.cpp:149]: Added unit test CheckOctetStringPrettyPrinter()

File: src/lib/core/CHIPTLVDebug.cpp (hunk 2 above)
Comment (emargolis) [reply src/lib/core/CHIPTLVDebug.cpp:151]: Adopted format proposed by @tcarmelveilleux : "hex:"

File: src/tools/chip-cert/Cmd_PrintCD.cpp (hunk 4 above)
Comment (emargolis) [reply src/tools/chip-cert/Cmd_PrintCD.cpp]: updated this comment. The command line input string can be of hex or base64 format

File: src/tools/chip-cert/Cmd_PrintCD.cpp (hunk 5 above)
Comment (emargolis) [reply src/tools/chip-cert/Cmd_PrintCD.cpp]: Added `gOutFile` variable and using `vfprintf` as suggested

File: src/tools/chip-cert/Cmd_PrintCD.cpp (hunk 6 above)
Comment (emargolis) [reply src/tools/chip-cert/Cmd_PrintCD.cpp]: updated

File: src/lib/core/CHIPTLVDebug.cpp [hunk 7]
```diff
@@ -68,13 +68,11 @@ static void DumpHandler(DumpWriter aWriter, const char * aIndent, const TLVReade
     temp.Init(aReader);
     tagControl = static_cast<TLVTagControl>(temp.GetControlByte() & kTLVTagControlMask);
 
-    aWriter("%zd ", aDepth);
+    aWriter("0x%02X, ", temp.GetLengthRead());
```
Comment (emargolis) [inline src/lib/core/CHIPTLVDebug.cpp:71]: Note for reviewers (@tcarmelveilleux  @mrjerryjohns ). 

The outputs below are for the following command:
```
./out/debug/standalone/chip-cert print-cd credentials/development/commissioner_dut/struct_cd_authorized_paa_list_count10_valid/cd.der
```

The printing format prior to my changes in this file were:
```
0 0x7ffd0af72841, tag[Anonymous]: 0xffffffff, type: Structure (0x15), container: 
1     0x7ffd0af72844, tag[Context Specific]: 0x0, type: Signed Fixed Point (0x00), value: 1
1     0x7ffd0af72848, tag[Context Specific]: 0x1, type: Unsigned Fixed Point (0x04), value: 65521
1     0x7ffd0af7284a, tag[Context Specific]: 0x2, type: Array (0x16), container: 
2         0x7ffd0af7284d, tag[Anonymous]: 0xffffffff, type: Unsigned Fixed Point (0x04), value: 32768
1     0x7ffd0af72852, tag[Context Specific]: 0x3, type: Unsigned Fixed Point (0x04), value: 4660
1     0x7ffd0af72855, tag[Context Specific]: 0x4, type: UTF-8 String (0x0c), length: 19, value: "ZIG20141ZB330001-24"
1     0x7ffd0af7286b, tag[Context Specific]: 0x5, type: Unsigned Fixed Point (0x04), value: 0
1     0x7ffd0af7286e, tag[Context Specific]: 0x6, type: Unsigned Fixed Point (0x04), value: 0
1     0x7ffd0af72872, tag[Context Specific]: 0x7, type: Unsigned Fixed Point (0x04), value: 39030
1     0x7ffd0af72875, tag[Context Specific]: 0x8, type: Unsigned Fixed Point (0x04), value: 0
1     0x7ffd0af72877, tag[Context Specific]: 0xb, type: Array (0x16), container: 
2         0x7ffd0af72879, tag[Anonymous]: 0xffffffff, type: Data (0x10), length: 20, value: 0x7ffd0af72879

2         0x7ffd0af7288f, tag[Anonymous]: 0xffffffff, type: Data (0x10), length: 20, value: 0x7ffd0af7288f

2         0x7ffd0af728a5, tag[Anonymous]: 0xffffffff, type: Data (0x10), length: 20, value: 0x7ffd0af728a5

2         0x7ffd0af728bb, tag[Anonymous]: 0xffffffff, type: Data (0x10), length: 20, value: 0x7ffd0af728bb

2         0x7ffd0af728d1, tag[Anonymous]: 0xffffffff, type: Data (0x10), length: 20, value: 0x7ffd0af728d1

2         0x7ffd0af728e7, tag[Anonymous]: 0xffffffff, type: Data (0x10), length: 20, value: 0x7ffd0af728e7

2         0x7ffd0af728fd, tag[Anonymous]: 0xffffffff, type: Data (0x10), length: 20, value: 0x7ffd0af728fd

2         0x7ffd0af72913, tag[Anonymous]: 0xffffffff, type: Data (0x10), length: 20, value: 0x7ffd0af72913

2         0x7ffd0af72929, tag[Anonymous]: 0xffffffff, type: Data (0x10), length: 20, value: 0x7ffd0af72929

2         0x7ffd0af7293f, tag[Anonymous]: 0xffffffff, type: Data (0x10), length: 20, value: 0x7ffd0af7293f
```

The printing format after my updates in this file is:
```
0x01, tag[Anonymous]: 0xffffffff, type: Structure (0x15), container: 
0x04,     tag[Context Specific]: 0x0, type: Signed Fixed Point (0x00), value: 1
0x08,     tag[Context Specific]: 0x1, type: Unsigned Fixed Point (0x04), value: 65521
0x0A,     tag[Context Specific]: 0x2, type: Array (0x16), container: 
0x0D,         tag[Anonymous]: 0xffffffff, type: Unsigned Fixed Point (0x04), value: 32768
0x12,     tag[Context Specific]: 0x3, type: Unsigned Fixed Point (0x04), value: 4660
0x15,     tag[Context Specific]: 0x4, type: UTF-8 String (0x0c), length: 19, value: "ZIG20141ZB330001-24"
0x2B,     tag[Context Specific]: 0x5, type: Unsigned Fixed Point (0x04), value: 0
0x2E,     tag[Context Specific]: 0x6, type: Unsigned Fixed Point (0x04), value: 0
0x32,     tag[Context Specific]: 0x7, type: Unsigned Fixed Point (0x04), value: 39030
0x35,     tag[Context Specific]: 0x8, type: Unsigned Fixed Point (0x04), value: 0
0x37,     tag[Context Specific]: 0xb, type: Array (0x16), container: 
0x39,         tag[Anonymous]: 0xffffffff, type: Octet String (0x10), length: 20, value: hex:6AFD22771F511FECBF1641976710DCDC31A1717E
0x4F,         tag[Anonymous]: 0xffffffff, type: Octet String (0x10), length: 20, value: hex:F4BBCABBC5016577AA8B44FFB90FCCA140FE6620
0x65,         tag[Anonymous]: 0xffffffff, type: Octet String (0x10), length: 20, value: hex:F4BB35BBC5016577AA8B44FFB90FCCA140FE6620
0x7B,         tag[Anonymous]: 0xffffffff, type: Octet String (0x10), length: 20, value: hex:F4BB3544C5016577AA8B44FFB90FCCA140FE6620
0x91,         tag[Anonymous]: 0xffffffff, type: Octet String (0x10), length: 20, value: hex:F4BB35443A016577AA8B44FFB90FCCA140FE6620
0xA7,         tag[Anonymous]: 0xffffffff, type: Octet String (0x10), length: 20, value: hex:F4BB35443AFE6577AA8B44FFB90FCCA140FE6620
0xBD,         tag[Anonymous]: 0xffffffff, type: Octet String (0x10), length: 20, value: hex:F4BB35443AFE9A77AA8B44FFB90FCCA140FE6620
0xD3,         tag[Anonymous]: 0xffffffff, type: Octet String (0x10), length: 20, value: hex:F4BB35443AFE9A88AA8B44FFB90FCCA140FE6620
0xE9,         tag[Anonymous]: 0xffffffff, type: Octet String (0x10), length: 20, value: hex:F4BB35443AFE9A88558B44FFB90FCCA140FE6620
0xFF,         tag[Anonymous]: 0xffffffff, type: Octet String (0x10), length: 20, value: hex:F4BB35443AFE9A88557444FFB90FCCA140FE6620
```

File: src/tools/chip-cert/Cmd_PrintCD.cpp (hunk 3 above)
Comment (emargolis) [reply src/tools/chip-cert/Cmd_PrintCD.cpp:166]: Good Point! I'll do that change as a followup as it requires changes in other places in this tool.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
accepted for master: tooling update.
