### PR TITLE
Fix loading of CD signing certs in chip-tool.

### LINKED ISSUE #32337: [BUG] [1.2.0.1] chiptool fails to load somes CD certificates
### Reproduction steps

1. Download the matter-stack (connectedhomeip) using v1.2.0.1 tag
2. Build chiptool

At this point:
1. Do a random command with `--cd-trust-store-path` to check that when you use the path `credentials/development/cd-certs` it's okay:
```
./chip-tool pairing unpair 1 --cd-trust-store-path "/path_to/connectedhomeip-v1.2.0.1/credentials/development/cd-certs"
```
2. Create a temporary directory and copy (only) the `CSA_Matter_CD_Signing_Key_*.cert.der` files to this directory:
```
rm -rf /tmp/tmp-cd && mkdir /tmp/tmp-cd
cp credentials/development/cd-certs/CSA_Matter_CD_Signing_Key_00*.der /tmp/tmp-cd/
```
3. Run chip-tool again using this new directory:
```
./chip-tool pairing unpair 1 --cd-trust-store-path "/tmp/tmp-cd"
```

At this point you will get this message:

```
CHIP:TOO: Warning: no CD signing certs found in path: /tmp/tmp-cd, only defaults will be used
```

The warning appear because only `Chip-Test-CD-Cert.der` and `CSA_Matter_Certificate_and_Testing_Root.cert.der` are successfully parsed using `chip::Credentials::LoadAllX509DerCerts(cdTrustStorePath)`. The certificates `CSA_Matter_CD_Signing_Key_*.cert.der` are not recognised.

The problem is that in `VerifyAttestationCertificateFormat()`, the function `X509_get_pathlen(x509Cert)` returns 0.

I don't know if it's normal or not, it's not really clear to me. 

Attached you will find the CD certificates that we get from DCL that are also not "recognised":

[certs.zip](https://github.com/project-chip/connectedhomeip/files/14418159/certs.zip)

### Bug prevalence

100%

### GitHub hash of the SDK that was being used

181b0cb14ff007ec912f2ba6627e05dfb066c008

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
We were calling a function that tried to validate that the certs are valid PAA certs, which is very much not required for CD signing certs.

Fixes https://github.com/project-chip/connectedhomeip/issues/32337

### CODE REVIEW

File: src/credentials/attestation_verifier/FileAttestationTrustStore.h [hunk 1]
```diff
@@ -25,17 +25,29 @@
 namespace chip {
 namespace Credentials {
 
+enum class CertificateValidationMode
+{
+    // Validate that the certificate is a valid PAA certificate.
+    kPAA,
```
Comment (cecille) [inline src/credentials/attestation_verifier/FileAttestationTrustStore.h:31]: I believe the function handles all three in the chain - can this be kAttestation or something similar?

**Review by cecille — APPROVED** [review]

File: src/credentials/attestation_verifier/FileAttestationTrustStore.h (hunk 1 above)
Comment (cecille) [reply src/credentials/attestation_verifier/FileAttestationTrustStore.h:31]: Nope,  I'm wrong, ignore that. Closing.

Comment (bzbarsky-apple) [reply src/credentials/attestation_verifier/FileAttestationTrustStore.h:31]: > I believe the function handles all three in the chain

I don't think it does.  It explicitly calls:
```
VerifyAttestationCertificateFormat(certSpan, Crypto::AttestationCertType::kPAA)
```

**Review by tcarmelveilleux — APPROVED** [review]

**Review by ReneJosefsen — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]
