### PR TITLE
Fix escaping in Linux app storage

### LINKED ISSUE #20188: Ensure Linux examples platform storage backend succeeds Storage audit
#### Problem
PR #20134 and #20164 together introduced a storage API compliance audit.

This audit must be run and pass on Linux and succeed against PersistentStorageDelegate used by all-clusters-app (KVS file based)

To run the audit for anything using Server, build your target with `chip_support_enable_storage_api_audit=true` added to your GN args and then run your binary in a debugger. The default audit is added to Server::Init() and will cause an assert with logs on failure.

Audit passes once you see the following string in your logs

- `==== PersistentStorageDelegate API audit: SUCCESS ====`

On failure, informative assertion failures are logged to assist in debugging.

 #### Proposed Solution

- Build with audit enabled
- Run and comment on passing along with the SHA of the commit where it was run. Provide a logs capture of your run.
- If you find failures, please document them in comments on the issue to help SDK team audit the types of failures/assumptions made.
- Close the issue once you pass

### PR DESCRIPTION
**Pull request by tcarmelveilleux**
#### Problem

- Linux apps (like all-clusters-app) use a different storage backend
  than chip-tool, but the backend eventually goes to the same INI
  format.
- The Linux app did not properly manage keys with `=` and `\n` in the
  key, when attempting reload of value.

Fixes #20188

#### Change overview

- Adds the same escaping to Linux apps as for chip-tool
- Adds unescaping
- Adds unit tests for escaping and unescaping
- Adds debug dumping of all keys to chip-tool storage init

#### Testing

- Added unit tests pass
- Existing unit tests pass
- Cert tests pass
- Manual validation of restart with colliding keys in INI backend
  no longer shows collision after change

### CODE REVIEW

**Review by jmartinez-silabs — APPROVED** [review]

File: src/lib/support/tests/TestIniEscaping.cpp [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+
+    NL_TEST_ASSERT(inSuite, UnescapeKey(EscapeKey("\x01\x02\x03\x04\x05\x06\x07")) == "\x01\x02\x03\x04\x05\x06\x07");
+    NL_TEST_ASSERT(inSuite, UnescapeKey(EscapeKey("\x08\x09\x0a\x0b\x0c\x0d\x0e")) == "\x08\x09\x0a\x0b\x0c\x0d\x0e");
+    NL_TEST_ASSERT(inSuite, UnescapeKey(EscapeKey("\x0f\x10\x11\x12\x13\x14\x15")) == "\x0f\x10\x11\x12\x13\x14\x15");
+    NL_TEST_ASSERT(inSuite, UnescapeKey(EscapeKey("\x16\x17\x18\x19\x1a\x1b\x1c")) == "\x16\x17\x18\x19\x1a\x1b\x1c");
+    NL_TEST_ASSERT(inSuite, UnescapeKey(EscapeKey("\x1d\x1e\x1f \x7f=\\")) == "\x1d\x1e\x1f \x7f=\\");
+    NL_TEST_ASSERT(inSuite, UnescapeKey(EscapeKey("\x81\x82\xff")) == "\x81\x82\xff");
+
+    // Make sure entire range is escapable
+    for (int c = -128; c <= 127; c++)
```
Comment (tehampson) [inline src/lib/support/tests/TestIniEscaping.cpp:91]: I spent about a min thinking this through. You accomplish the same thing and make it easier for someone else later if you use uint16_t going from 0 to <= 255

File: src/lib/support/tests/TestIniEscaping.cpp [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+{
+    const char * input;
+    const char * expectedOutput;
+};
+
+void TestEscaping(nlTestSuite * inSuite, void * inContext)
+{
+    NL_TEST_ASSERT(inSuite, EscapeKey("") == "");
+    NL_TEST_ASSERT(inSuite, EscapeKey("abcd1234,!") == "abcd1234,!");
+    NL_TEST_ASSERT(inSuite, EscapeKey("ab\ncd =12\\34\x7f") == "ab\\x0acd\\x20\\x3d12\\x5c34\\x7f");
```
Comment (tehampson) [inline src/lib/support/tests/TestIniEscaping.cpp:38]: Should the expected string be `ab\\x0acd\\x20\\x3d12\\x5c\\x5c34\\x5c7f`

File: examples/chip-tool/config/PersistentStorage.h [hunk 3]
```diff
@@ -34,6 +34,8 @@ class PersistentStorage : public chip::PersistentStorageDelegate
     CHIP_ERROR SyncDeleteKeyValue(const char * key) override;
     bool SyncDoesKeyExist(const char * key) override;
 
+    void DumpKeys() const;
```
[the remark this answers is not in the document]
Comment (tehampson) [reply examples/chip-tool/config/PersistentStorage.h:37]: I couldn't remove this comment during review for some reason, so marking as resolved since after I made it I figured it didn't actually apply

[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply examples/chip-tool/config/PersistentStorage.h:37]: There is a comment about usage in `PersistentStorage.cpp::Init()`. It's there to keep.

File: src/lib/support/tests/TestIniEscaping.cpp (hunk 2 above)
Comment (tcarmelveilleux) [reply src/lib/support/tests/TestIniEscaping.cpp:38]: No, because the inner `\\` between 12 and 34 is 1 character

File: src/lib/support/tests/TestIniEscaping.cpp (hunk 1 above)
Comment (tcarmelveilleux) [reply src/lib/support/tests/TestIniEscaping.cpp]: One is more accurate than the other, but I will change to 0..255

**Review by tehampson — APPROVED** [review]
