### PR TITLE
Fix isEqual and hash on various path classes to do the right thing.

### LINKED ISSUE #30969: [Darwin] MTRCommandPath and MTREventPath should override the isEqual and hash
### Reproduction steps

Check the implementation of command and event path in MTRBaseDevice.mm
```
@implementation MTRCommandPath
@end
```

Not overwriting the isEqual method results in two different commands in a cluster (different command IDs) to pass the equity checks since we end up using MTRBaseClusterPath:

```
- (BOOL)isEqual:(id)object
{
    if (![object isKindOfClass:[self class]]) {
        return NO;
    }
    return [self isEqualToClusterPath:object];
}

```

### Platform

darwin

### Platform Version(s)

_No response_

### Type

Platform validated

### (Optional) If manually tested please explain why this is only manually tested

@implementation MTRCommandPath
- (instancetype)initWithPath:(const ConcreteCommandPath &)path
{
    if (self = [super initWithPath:path]) {
        _command = @(path.mCommandId);
    }
    return self;
}

+ (MTRCommandPath *)commandPathWithEndpointID:(NSNumber *)endpointID clusterID:(NSNumber *)clusterID commandID:(NSNumber *)commandID
{
    ConcreteCommandPath path(static_cast<chip::EndpointId>([endpointID unsignedShortValue]),
        static_cast<chip::ClusterId>([clusterID unsignedLongValue]), static_cast<chip::CommandId>([commandID unsignedLongValue]));

    return [[MTRCommandPath alloc] initWithPath:path];
}

- (id)copyWithZone:(NSZone *)zone
{
    return [MTRCommandPath commandPathWithEndpointID:self.endpoint clusterID:self.cluster commandID:_command];
}
@end

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Some of them were falling through to the MTRClusterPath implementations, leading to different paths testing equal.

Fixes https://github.com/project-chip/connectedhomeip/issues/30969

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]

File: src/darwin/Framework/CHIPTests/MTRDeviceTests.m [hunk 1]
```diff
@@ -2805,6 +2805,91 @@ - (void)test900_SubscribeAllAttributes
...
+
+    // Mix
+    XCTAssertFalse([commandPath1 isEqual:eventPath1]);
+    XCTAssertFalse([eventPath1 isEqual:commandPath1]);
+
+    XCTAssertFalse([commandPath1 isEqual:attributePath1]);
+    XCTAssertFalse([attributePath1 isEqual:commandPath1]);
+
+    XCTAssertFalse([attributePath1 isEqual:eventPath1]);
+    XCTAssertFalse([eventPath1 isEqual:attributePath1]);
```
Comment (ksperling-apple) [inline src/darwin/Framework/CHIPTests/MTRDeviceTests.m:2890]:
```suggestion
    XCTAssertFalse([eventPath1 isEqual:attributePath1]);
    XCTAssertFalse([clusterPath1 isEqual:attributePath1]);
    XCTAssertFalse([clusterPath1 isEqual: eventPath1]);
```

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm [hunk 2]
```diff
@@ -2497,6 +2497,24 @@ ConcreteEventPath path(static_cast<chip::EndpointId>([endpointID unsignedShortVa
...
 }
 
+- (BOOL)isEqualToEventPath:(MTREventPath *)eventPath
+{
+    return [self isEqualToClusterPath:eventPath] && [_event isEqualToNumber:eventPath.event];
+}
+
+- (BOOL)isEqual:(id)object
+{
+    if (![object isKindOfClass:[self class]]) {
```
Comment (ksperling-apple) [inline src/darwin/Framework/CHIP/MTRBaseDevice.mm:2507]: The basic bug is that `MTRClusterPath` should be checking for `[object class] == [self class]`, not `isKindOfClass:` since instances of different sub-classes should never be equal. The sub-class implementations can then be `return [super isEqual:obejct] && /* test the sub-class-specific fields */`.

As this is written, an `[aClusterPath isEqual:someEventPath]` will still incorrectly compare only the cluster path parts.

**Comment by ksperling-apple** [comment]
It would also be nice to move each of these classes into their own file, or at least 1 file for MTRClusterPath and it's sub-classes.

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 2 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm:2507]: I guess that depends on the expected semantics of isEqual.  If someone hands me an `MTRClusterPath*` that happens to be an event path under the hood, and I do `[myClusterPath isEqual:givenClusterPath]`, should it test equal?

But I guess in that situation we'd want the same answer as `[givenClusterPath isEqual:myClusterPath]`, which presumably should be false?

File: src/darwin/Framework/CHIPTests/MTRDeviceTests.m (hunk 1 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIPTests/MTRDeviceTests.m:2890]: Applied.

**Comment by bzbarsky-apple** [comment]
> It would also be nice to move each of these classes into their own file, or at least 1 file for MTRClusterPath and it's sub-classes.

Will do as a followup: https://github.com/project-chip/connectedhomeip/issues/31247

File: src/darwin/Framework/CHIP/MTRBaseDevice.mm (hunk 2 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRBaseDevice.mm]: Fixed.

**Review by jtung-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
Fast-tracking platform-specific fix with platform owner review.
