### PR TITLE
Resolve race condition before UserPrompt in simulated tests.

### LINKED ISSUE #25382: [BUG] Chip-App fails to execute Test case TC-PRS-3.1
### Reproduction steps

1. Open Terminal 1 and run 'rm -rf /tmp/chip_*;./chip-app1 --trace_file "/logs/trace_log_2023-02-28_19.47.05_0xb14e1214ed9efe87_SIMULATED_APP_TEST_PAIRING.log" --trace_decode 1`
2. Open Terminal 2 and run `rm -rf /tmp/chip*;./chip-tool pairing code 305414945 MT:-24J0AFN00KA0648G00`
3. Ctrl+C on Terminal 1.
4. In Terminal 1, run `./chip-app1 --command Test_TC_PRS_3_1_Simulated --secured-device-port 5540 --trace_file "/logs/trace_log_2023-02-28_19.47.14_0xb14e1214ed9efe87_SIMULATED_APP_TEST_Test_TC_PRS_3_1_Simulated.log" --trace_decode 1`
5. In Terminal 2, run the below commands:
 ./chip-tool pressuremeasurement read measured-value 305414945 0
 ./chip-tool pressuremeasurement read min-measured-value 305414945 0
 ./chip-tool pressuremeasurement read max-measured-value 305414945 0
 ./chip-tool pressuremeasurement read tolerance 305414945 0
 ./chip-tool pressuremeasurement read scaled-value 305414945 0
 ./chip-tool pressuremeasurement read min-scaled-value 305414945 0
 ./chip-tool pressuremeasurement read max-scaled-value 305414945 0
 ./chip-tool pressuremeasurement read scaled-tolerance 305414945 0
 ./chip-tool pressuremeasurement read scale 305414945 0
5. Observe in Terminal 1 that `chip-app` seem to skip step "read scale" and move to next step to prompt user. Chip-app does not seem to respond to the request from the controller.
6. Observe in Terminal 2 that `chip-tool` fails. 

Logs of test step to read scale attribute are attached from `chip-app` and `controller`

### Bug prevalence

100%

### GitHub hash of the SDK that was being used

b89e83be43dde7a79d90823f4bc1279eb53f76de

### Platform

raspi

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by krypton36**
- Fixes #25382  
- Updated the next test to be executed as scheduled work so it does not block the read/write/command to complete when a user prompt is executed on the following step.

Tests:
- Validated that the issue filed no longer occurs.
- Validated that all steps are completed in the test.
- Validated that user prompt is still accepted and continue after typing it in.

### CODE REVIEW

File: examples/placeholder/linux/include/TestCommand.h [hunk 1]
```diff
@@ -129,7 +129,7 @@ class TestCommand : public TestRunner,
     {
         if (commandPath == mCommandPath)
         {
-            NextTest();
+            chip::DeviceLayer::PlatformMgr().ScheduleWork(ScheduleNextTest, reinterpret_cast<intptr_t>(this));
```
Comment (bzbarsky-apple) [inline examples/placeholder/linux/include/TestCommand.h:132]: This seems ok, but shouldn't the `RemoveEventHandler` bit move from ScheduleNextTest into the OnPlatformEvent case where we get the kCommissioningComplete event?

Also, should we be setting isRunning to false somewhere given that ScheduleNextTest sets it to true?  Not sure what the meaning of the member is...

Comment (krypton36) [reply examples/placeholder/linux/include/TestCommand.h:132]: It is only set to false when waiting for commissioning, so setting this to True is a no-op since it should already be True in the other scenarios. I also noticed `RemoveEventHandler`, I thought it was a no-op if the event didn't exist so I didn't plan to move, but it makes more sense to move it.

Comment (krypton36) [reply examples/placeholder/linux/include/TestCommand.h:132]: Ok, moved it.

Comment (krypton36) [reply examples/placeholder/linux/include/TestCommand.h:132]: Re-tested and the issue remains resolved.

File: examples/placeholder/linux/include/TestCommand.h [hunk 2]
```diff
@@ -123,13 +122,14 @@ class TestCommand : public TestRunner,
             chip::DeviceLayer::PlatformMgr().ScheduleWork(ScheduleNextTest, arg);
             break;
         }
+        chip::DeviceLayer::PlatformMgr().RemoveEventHandler(OnPlatformEvent, arg);
```
Comment (bzbarsky-apple) [inline examples/placeholder/linux/include/TestCommand.h:125]: This needs to be in the case where we get the event we are waiting for, not out here where other events will trigger it....

Comment (krypton36) [reply examples/placeholder/linux/include/TestCommand.h:125]: I was think about this incorrectly. That makes sense! Iff we receive the event we are expecting only then remove the event handler.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by yufengwangca — APPROVED** [review]
