### PR TITLE
[OPSTATE] fix :optimize event api

### LINKED ISSUE #28127: [1.2] Address review comments from PR 27990
### Reproduction steps

https://github.com/project-chip/connectedhomeip/pull/27990 was merged before reviews were submitted (but while it was being reviewed).  This is an issue to track addressing the review comments in https://github.com/project-chip/connectedhomeip/pull/27990#pullrequestreview-1539765953

@mideayanghui 

### Bug prevalence

N/A

### GitHub hash of the SDK that was being used

5cd5320

### Platform

core

### Platform Version(s)

_No response_

### Type

Common Cluster Logic

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mideayanghui**
fixes: https://github.com/project-chip/connectedhomeip/issues/28127

### CODE REVIEW

File: src/app/clusters/operational-state-server/operational-state-server.h [hunk 1]
```diff
@@ -27,6 +27,55 @@ namespace app {
...
 
+/**
+ * A class which represents the operational error event of an Operational State cluster derivation instance.
+ */
+class GenericErrorEvent : private app::Clusters::OperationalState::Events::OperationalError::Type
+{
+    using super = app::Clusters::OperationalState::Events::OperationalError::Type;
+
+public:
+    GenericErrorEvent(ClusterId aClusterId, const Structs::ErrorStateStruct::Type & aError) : mClusterId(aClusterId)
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-state-server/operational-state-server.h:38]: This is actually a bit dangerous: if the ErrorStateStruct::Type goes out of scope before the GenericErrorEvent does, we will possibly end up with dangling pointers.

It would be safer to keep taking the ErrorStateStruct as an argument to OnOperationalErrorDetected and using the cluster id of the instance to construct the GenericErrorEvent from the struct and ensure that it does not live too long.  In particular, this event definition could move into operational-state-server.cpp, so it's not exposed.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
