### PR TITLE
[ICD] Reset mNeedIcdRegistration to false when starting the commision flow

### LINKED ISSUE #33517: [BUG] chip-tool commissioning ICD device then commissioning non-ICD device will fail
### Reproduction steps

1.run chip-tool under interactive mode
2.pair a ICD device -> OK
3.then pair a non-ICD device -> FAIL

### Bug prevalence

always

### GitHub hash of the SDK that was being used

matter 1.3

### Platform

core

### Platform Version(s)

all platform that implement commissioner

### Anything else?

From my anaysis, the root cause is no chance to set mNeedIcdRegistration to false (controller/AutoCommissioner.cpp)
When commissioning a ICD device, because ICD cluster exists, mNeedIcdRegistration will be set to true. Following a non-ICD device, mNeedIcdRegistration is still true, then commissioner will go to ICD registration stage. But the regisitration will fail for status UNSUPPORTED_CLUSTER.

One changes to fix maybe:

```
--- a/src/controller/AutoCommissioner.cpp
+++ b/src/controller/AutoCommissioner.cpp
@@ -752,6 +752,7 @@ CHIP_ERROR AutoCommissioner::CommissioningStepFinished(CHIP_ERROR err, Commissio
 
             if (mParams.GetICDRegistrationStrategy() != ICDRegistrationStrategy::kIgnore)
             {
+                mNeedIcdRegistration = false;
                 if (mDeviceCommissioningInfo.icd.isLIT && mDeviceCommissioningInfo.icd.checkInProtocolSupport)
                 {
                     mNeedIcdRegistration = true;
```

### PR DESCRIPTION
**Pull request by yunhanw-google**
When commissioning a LIT device,  mNeedIcdRegistration will be set to true. Following a non-LIT device, mNeedIcdRegistration is still true, then commissioner will continue with LIT registration.
We should reset the mNeedIcdRegistration to false before check whether the device is LIT or not.

### CODE REVIEW

File: src/controller/AutoCommissioner.cpp [hunk 1]
```diff
@@ -760,6 +760,7 @@ CHIP_ERROR AutoCommissioner::CommissioningStepFinished(CHIP_ERROR err, Commissio
                 }
             }
 
+            mNeedIcdRegistration = false;
```
Comment (bzbarsky-apple) [inline src/controller/AutoCommissioner.cpp:763]: This is probably OK, but conceptually it would make more sense to either store this in mParams or reset it in `AutoCommissioner::SetCommissioningParameters` like we do other things we get from the device (e.g. the failsafe timer above).

**Review by bzbarsky-apple — APPROVED** [review]

File: src/controller/AutoCommissioner.cpp (hunk 1 above)
Comment (yunhanw-google) [reply src/controller/AutoCommissioner.cpp]: yes, it make sense, move it inside AutoCommissioner::SetCommissioningParameters

**Review by yufengwangca — APPROVED** [review]
