### PR TITLE
Make sure we expire pending sessions that we never make active.

### LINKED ISSUE #17167: [TC-MF-1.11]  After 11th attempt of invalid passcode chip-tool is  not showing any error logs
**Issue** : 
According to test-plan [TC-MF-1.11] step 3, until 20 unsuccessful invalid pass code attempts the chip-tool should throw PASE session failure, and then for  21st attempt should throw a message that can’t begin "PASE (failure at PBKDFRequest, not obtaining a PBKDFResponse)", but here after 11  unsuccessful attempts chip-tool is not showing any error logs.

**Expected behaviour** : Untill 21st attempt chip-tool should throw pase session failure error 

**Actual behaviour** : Affter 11th attempt chip-tool doesn't throw pase session failure error

**Spec Reference** : https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/AdminCommissioningCluster.adoc#ref_OCW

**Test-plan reference** : https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/multiplefabrics.adoc#tc-mf-1-9-device-exit-commissioning-mode-after-20-failed-commission-attempts-ecm-dut-commissionee

**Test platform** : 
             Chip-tool - RPI
             DUT - RPI/MAC

**Steps to reproduce** : 

1. DUT side : 

- sudo rm -rf /tmp/chip_*
- sudo ./chip-all-clusters-app --wifi (Discriminator - 3841, Passcode - 20202021)

2. TH side : 

- ./chip-tool pairing ble-wifi 1 zigbeehome matter123 20202021 3841(on TH1)
- ./chip-tool pairing open-commissioning-window 1 1 100 1000 3841/./chip-tool administratorcommissioning open-basic-commissioning-window 500 1 0 --timedInteractionTimeoutMs 1000 (on TH1)
- ./chip-tool pairing manualcode 2 35484132896 / ./chip-tool pairing onnetwork 2 20202019(wrong manual code)(on TH2)
- Above command should be given 20 times
- But when we pass 11th time of above command chip-tool is not showing error logs 
- ./chip-tool pairing manualcode 2 34970112332 / ./chip-tool pairing onnetwork 2 20202021(correct manual code)(on TH2)

             
PFA logs : 
[TC_MF_1.11_cntrl02.txt](https://github.com/project-chip/connectedhomeip/files/8442375/TC_MF_1.11_cntrl02.txt)

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
When we started allocating secure sessions at the start of the
CASE/PASE handshake, not at the end, we ended up in a situation where
if the session handshake fails the pending session still sticks around
and never gets cleaned up.  Eventually the secure session pool fills
up, and we are unable to create any new sessions.

The fix is to make PairingSession clean things up properly.

Fixes https://github.com/project-chip/connectedhomeip/issues/17167

#### Problem
See above.

#### Change overview
See above.

#### Testing
Followed the steps in #17167 and was able to go for 20 PASE attempts before the server closed the commisssioning window.

### CODE REVIEW

**Review by msandstedt — APPROVED** [review]

File: src/transport/SessionManager.h [hunk 1]
```diff
@@ -237,9 +237,8 @@ class DLL_EXPORT SessionManager : public TransportMgrDelegate
     // is returned. Otherwise, an Optional<SessionHandle> with no value set is returned.
     //
     //
-    Optional<SessionHandle>
-    FindSecureSessionForNode(ScopedNodeId peerNodeId,
-                             Transport::SecureSession::Type type = Transport::SecureSession::Type::kUndefined);
+    Optional<SessionHandle> FindSecureSessionForNode(ScopedNodeId peerNodeId,
```
Comment (mrjerryjohns) [inline src/transport/SessionManager.h:240]: The description of this function should be updated to indicate that `kUndefined` is to no longer be passed in.

File: src/transport/PairingSession.cpp [hunk 2]
```diff
@@ -99,4 +100,22 @@ CHIP_ERROR PairingSession::DecodeMRPParametersIfPresent(TLV::Tag expectedTag, TL
     return tlvReader.ExitContainer(containerType);
 }
 
+void PairingSession::Clear()
+{
+    if (mSessionManager != nullptr)
+    {
+        auto handle = GetSecureSessionHandle();
```
Comment (mrjerryjohns) [inline src/transport/PairingSession.cpp:107]: This doesn't look to be defined anywhere?

File: src/transport/PairingSession.cpp [hunk 3]
```diff
@@ -99,4 +100,22 @@ CHIP_ERROR PairingSession::DecodeMRPParametersIfPresent(TLV::Tag expectedTag, TL
...
+        if (handle.HasValue() && !handle.Value()->AsSecureSession()->IsActiveSession())
+        {
+            // Make sure to clean up our pending session, since we're the only
+            // ones who have access to it do do so.
+            mSessionManager->ExpirePairing(handle.Value());
+        }
+    }
+
+    mPeerSessionId.ClearValue();
+    mSecureSessionHolder.Release();
```
Comment (mrjerryjohns) [inline src/transport/PairingSession.cpp:117]: This doesn't quite feel right. In general, should we not be releasing holders first _before_ we expire pairings? Otherwise `Release` is going to attempt to remove itself as a holder and access the underlying session that was just expired earlier?

Comment (mrjerryjohns) [reply src/transport/PairingSession.cpp:117]: Or is it that the act of calling `ExpirePairing` will invoke the destructor for `SecureSession`, which in turn will call `NotifySessionReleased`, which in turn calls `OnSessionReleased`, resulting in the underlying session here being actually released before we even get here?

Either way, comments would be good here.

File: src/transport/SessionManager.h (hunk 1 above)
Comment (bzbarsky-apple) [reply src/transport/SessionManager.h:240]: Good catch, done.

File: src/transport/PairingSession.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/transport/PairingSession.cpp:107]: Merge conflict...  Fixing.

File: src/transport/PairingSession.cpp (hunk 3 above)
Comment (mrjerryjohns) [reply src/transport/PairingSession.cpp:117]: Sigh. We honestly need more documentation elsewhere too, since these long-chain behaviors-on-destruction and the effects they have across the system are just not obvious to most layman readers, let alone someone like me who has been wading in this for some time and still take time to deduce some of these call paths.

**Review by mrjerryjohns — APPROVED** [review]
