### PR TITLE
Fix the identify timer logic on the esp32 all-clusters-app

### LINKED ISSUE #3165: M5Stack Identify Cluster command never stops
#### Problem
Running the Identify Cluster Command on the M5Stack via the CHIP Tool CLI never seems to stop identifying. 

```
./out/debug/standalone/chip-tool identify 192.168.x.xx 11095 1 5
```

 #### Proposed Solution
Find and fix this regression

### PR DESCRIPTION
**Pull request by sagar-apple**
#### Problem
The Identify command, once started, never stops. 

 #### Summary of Changes
This is happening because the Identify Cluster restarts the identify command every second. 
i.e if asked to identify for 2 seconds, the Identify cluster issues 3 identify commands for 2,1 and, 0 seconds respectively and because the currently implementation of the timer handler decrements the counter _before_ checking its value, when the timer is started for 0 seconds, it overflows and misses the check to stop the timer. Because of this, the LED never stops blinking.

Fixed it by decrementing the counter after its value has been checked. 

When we have proper Identify cluster callbacks via zap this code will change. 

 Fixes #3165

### CODE REVIEW

File: examples/all-clusters-app/esp32/main/DeviceCallbacks.cpp [hunk 1]
```diff
@@ -150,7 +149,7 @@ void DeviceCallbacks::OnIdentifyPostAttributeChangeCallback(EndpointId endpointI
 
     statusLED1.Blink(kIdentifyTimerDelayMS * 2);
 
-    // timerCount represents the number of callback execution before the we stopped the timer.
+    // timerCount represents the number of callback execution before we stop the timer.
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/esp32/main/DeviceCallbacks.cpp:152]:
```suggestion
    // timerCount represents the number of callback executions before we stop the timer.
```

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by rwalker-apple — APPROVED** [review]

**Comment by sagar-apple** [comment]
requesting a review @saurabhst @hawk248 @BroderickCarlin @jelderton.

**Review by saurabhst — APPROVED** [review]
