### PR TITLE
Fix crashes when DeviceCommissioner is shut down.

### LINKED ISSUE #22243: Crash if CHIPDeviceController shuts down in the middle of commissioning
#### Problem
Observing a crash (for SHA aca4b94f9220f2dd23c44da5dbfcdf8f212f5e4d, from an automated reporting system) with this stack:
```
0   chip::Controller::DeviceCommissioner::CommissioningStageComplete(chip::ChipError, chip::Controller::CommissioningDelegate::CommissioningReport) + 108 (src/controller/CHIPDeviceController.cpp:1551)
1   chip::Controller::OnBasicFailure(void*, chip::ChipError) + 168 (src/controller/CHIPDeviceController.cpp:1448)
2   chip::Controller::OnBasicFailure(void*, chip::ChipError) + 168 (src/controller/CHIPDeviceController.cpp:1448)
3   std::__1::__function::__func(chip::app::Clusters::GeneralCommissioning::Commands::CommissioningComplete::Type const&, void*, void (*)(void*, chip::app::Clusters::GeneralCommissioning::Commands::CommissioningComplete::Type::ResponseType const&), void (*)(void*, chip::ChipError), chip::Optional const&)::'lambda'(chip::ChipError), std::__1::allocator(chip::app::Clusters::GeneralCommissioning::Commands::CommissioningComplete::Type const&, void*, void (*)(void*, chip::app::Clusters::GeneralCommissioning::Commands::CommissioningComplete::Type::ResponseType const&), void (*)(void*, chip::ChipError), chip::Optional const&)::'lambda'(chip::ChipError)>, void (chip::ChipError)>::operator()(chip::ChipError&&) + 44 (/Library/Caches/com.apple.xbs/Sources/118c449b-1c17-401c-a939-b9e5d9c7e3f0/CHIPFramework-66/connectedhomeip/src/controller/CHIPCluster.h:83)
4   chip::Controller::TypedCommandCallback::OnError(chip::app::CommandSender const*, chip::ChipError) + 96 (/Volumes/BuildRootMonorailEnigma/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.1.Internal.sdk/usr/include/c++/v1/__functional/function.h:505)
5   chip::app::CommandSender::OnResponseTimeout(chip::Messaging::ExchangeContext*) + 232 (src/app/CommandSender.cpp:216)
6   chip::Messaging::ExchangeContext::NotifyResponseTimeout(bool) + 284 (src/messaging/ExchangeContext.cpp:481)
7   chip::Messaging::ExchangeContext::OnSessionReleased() + 148 (src/messaging/ExchangeContext.cpp:408)
8   chip::SessionHolderWithDelegate::SessionReleased() + 80 (src/transport/SessionHolder.h:98)
9   chip::Transport::Session::NotifySessionReleased() + 128 (src/transport/Session.h:124)
10  chip::Transport::SecureSession::MarkForEviction() + 276 (src/transport/SecureSession.cpp:149)
11  auto chip::SessionManager::ExpireAllSessionsForFabric(unsigned char)::$_2::operator()(chip::Transport::SecureSession*) const + 72 (src/transport/SessionManager.cpp:370)
12  chip::internal::LambdaProxy::Call(void*, void*) + 36 (src/lib/support/Pool.h:126)
13  chip::internal::HeapObjectList::ForEachNode(void*, chip::Loop (*)(void*, void*)) + 132 (src/lib/support/Pool.cpp:126)
14  chip::Loop chip::HeapObjectPool::ForEachActiveObject(chip::SessionManager::ExpireAllSessionsForFabric(unsigned char)::$_2&&) + 92 (src/lib/support/Pool.h:401)
15  chip::Loop chip::Transport::SecureSessionTable::ForEachSession(chip::SessionManager::ExpireAllSessionsForFabric(unsigned char)::$_2&&) + 56 (src/transport/SecureSessionTable.h:84)
16  chip::SessionManager::ExpireAllSessionsForFabric(unsigned char) + 100 (src/transport/SessionManager.cpp:367)
17  chip::Controller::DeviceController::Shutdown() + 160 (src/controller/CHIPDeviceController.cpp:304)
18  chip::Controller::DeviceCommissioner::Shutdown() + 256 (src/controller/CHIPDeviceController.cpp:495)
```

The crashing line (`src/controller/CHIPDeviceController.cpp:1551` on that SHA) is:
```
    NodeId nodeId            = mDeviceBeingCommissioned->GetDeviceId();
```
and the crashing address seems to be `0x18 == 24`, which is consistent with reading `mNodeId` member of the `mPeerId` member of `CommissioneeDeviceProxy` if the `CommissioneeDeviceProxy *` is null on a system where the three vtable pointers are 8 bytes each.  Though I am not sure how we managed to do the virtual function call if this is really a null-deref.

Also, if this is a null-deref I am not sure _why_ `mDeviceBeingCommissioned` is null here; I would have expected a garbage value pointing into the pool that `DeviceCommissioner::Shutdown` shut down....

On tip the code flow around these bits seems about the same.

`DeviceCommissioner::Shutdown` does have a TODO comment about "If we have a commissioning step in progress, is there a way to cancel that callback?" and we are _somewhat_ doing that here, by tearing down the secure session, but much later in shutdown than would perhaps be ideal. 

 #### Proposed Solution
We should probably do a few things:
1. `DeviceCommissioner::Shutdown` should check for `mDeviceBeingCommissioned` being non-null, and if so `ReleaseCommissioneeDevice(mDeviceBeingCommissioned)` before it tears down the commissionee device pool.
2. `DeviceCommissioner::CommissioningStageComplete` should null-check `mDeviceBeingCommissioned` before using it.
3. Ideally we would also fix the above TODO, but that might need to be a separate work item.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
There are two fixes here:

1) Ensure that DeviceCommissioner::Shutdown properly cleans up
   mDeviceBeingCommissioned so we don't end up with it being a dangling pointer.

2) Ensure that DeviceCommissioner::CommissioningStageComplete doesn't try to
   derefence a null mDeviceBeingCommissioned (which indicates something has
   already stopped the commissioning process).

Fixes https://github.com/project-chip/connectedhomeip/issues/22243

#### Problem
See #22243 for crash analysis.

#### Change overview
See above.

#### Testing
CI should generally test this on happy paths.  Trying to figure out how to write a test that would exercise the "shut down in the middle of commissioning" codepath.

### CODE REVIEW

**Review by msandstedt — APPROVED** [review]

File: src/controller/CHIPDeviceController.cpp [hunk 1]
```diff
@@ -489,6 +489,17 @@ void DeviceCommissioner::Shutdown()
     }
 #endif // CHIP_DEVICE_CONFIG_ENABLE_COMMISSIONER_DISCOVERY
 
+    // If we have a commissionee device for the device being commissioned,
+    // release it now, before we release our whole commissionee pool.
+    if (mDeviceBeingCommissioned != nullptr)
+    {
+        auto * commissionee = FindCommissioneeDevice(mDeviceBeingCommissioned->GetDeviceId());
```
Comment (Damian-Nordic) [inline src/controller/CHIPDeviceController.cpp:496]: Is this step needed because the commissionee device proxy may not be allocated from the common pool? If that's possible, shouldn't the code for releasing `mDeviceInPASEEstablishment` also check that? And if that's not possible, wouldn't `ReleaseCommissioneeDevice(mDeviceBeingCommissioned)` be enough? Or even `mDeviceBeingCommissioned = nullptr` after `mCommissioneeDevicePool.ReleaseAll()`?

Comment (bzbarsky-apple) [reply src/controller/CHIPDeviceController.cpp:496]: > Is this step needed because the commissionee device proxy may not be allocated from the common pool?

`mDeviceBeingCommissioned` might be an operational device, not a commissionee device, if we got to the "send CommissioningComplete" part of commissioning.  That's why it's a `DeviceProxy *`, not `CommmissioneeDeviceProxy *`.

> wouldn't ReleaseCommissioneeDevice(mDeviceBeingCommissioned)

Wouldn't compile; wrong type.

> Or even mDeviceBeingCommissioned = nullptr after mCommissioneeDevicePool.ReleaseAll()

Again, `mDeviceBeingCommissioned` might not be a `CommmissioneeDeviceProxy`.

Comment (Damian-Nordic) [reply src/controller/CHIPDeviceController.cpp:496]: Oh, ok. Wasn't aware it can be operational device, too. Thanks!

**Review by Damian-Nordic — APPROVED** [review]
