### PR TITLE
Stop calling OnPairingComplete on CASE session establishment.

### LINKED ISSUE #18230: Pairing Delegates get repeated calls to OnPairingComplete
#### Problem
Setup: Once a device is commissioned and a CASE session is established. 
If first message for a command fails to deliver, the CHIPDeviceController calls, `updateDevice` which then goes and calls `OnPairingComplete` even though we are not currently commissioning.

See CHIPDeviceController.cpp
```
void DeviceController::OnFirstMessageDeliveryFailed(const SessionHandle & session)
...
    err = UpdateDevice(secureSession->GetPeerNodeId());
```

 #### Proposed Solution
We need to define what `OnPairingComplete` actually means. My understanding is that it means PASE is established. In which case, it has no meaning once Commissioning is complete and shouldn't keep getting triggered.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
OnPairingComplete is documented as indicating the end of PASE
establishment, but our implementation calls it for _some_ CASE
sessions as well: only the ones we kick off from UpdateDevice.

This is unexpected by API consumers, and we should not be doing it.

Fixes https://github.com/project-chip/connectedhomeip/issues/18230

#### Problem
See above.

#### Change overview
See above.

#### Testing
Should be covered by existing tests.

### CODE REVIEW

File: src/controller/CHIPDeviceController.cpp [hunk 1]
```diff
@@ -1510,32 +1510,25 @@ void DeviceCommissioner::OnDeviceConnectedFn(void * context, OperationalDevicePr
...
-        if (commissioner->mDeviceBeingCommissioned != nullptr &&
-            commissioner->mDeviceBeingCommissioned->GetDeviceId() == device->GetDeviceId() &&
-            commissioner->mCommissioningDelegate != nullptr)
-        {
-            CommissioningDelegate::CommissioningReport report;
-            report.Set<OperationalNodeFoundData>(OperationalNodeFoundData(device));
-            commissioner->CommissioningStageComplete(CHIP_NO_ERROR, report);
-        }
+        // This call is definitely not us finding our commissionee device.
+        // This is presumably us trying to re-establish CASE on MRP failure.
```
Comment (mrjerryjohns) [inline src/controller/CHIPDeviceController.cpp:1516]: Or session eviction? Might be good to add this text in there now, even if it's not quite relevant just yet.

**Review by mrjerryjohns — APPROVED** [review]

File: src/controller/CHIPDeviceController.cpp [hunk 2]
```diff
@@ -1562,10 +1555,6 @@ void DeviceCommissioner::OnDeviceConnectionFailureFn(void * context, PeerId peer
     {
         commissioner->CommissioningStageComplete(error);
     }
-    else
```
Comment (kghost) [inline src/controller/CHIPDeviceController.cpp:1565]: I can't comment previous lines. In line 1550, there is a check of `commissioner->mPairingDelegate != nullptr`, since the field is no longer being used in this function, are we going to remove that check ?

**Review by kghost — APPROVED** [review]

File: src/controller/CHIPDeviceController.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/controller/CHIPDeviceController.cpp:1516]: Session eviction would not end up reaching this code, I don't think....

File: src/controller/CHIPDeviceController.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/controller/CHIPDeviceController.cpp:1565]: Oh, good catch!  That check was wrong in fact, because it skipped the the `ReleaseSession` cleanup!

**Review by sagar-apple — APPROVED** [review]
