### PR TITLE
import zcl reporting

### LINKED ISSUE #2066: Import ../third_party/connectedhomeip/src/app/reporting
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

### PR DESCRIPTION
**Pull request by bhaskar-apple**
#### Problem
import zcl reporting

 #### Summary of Changes
Get it to compile and link. Suppress some warnings

fixes #2066

### CODE REVIEW

File: examples/wifi-echo/server/esp32/main/gen/endpoint_config.h [hunk 1]
```diff
@@ -554,11 +554,11 @@
 // Generated reporting configuration defaults
 #define EMBER_AF_GENERATED_REPORTING_CONFIG_DEFAULTS                                                                               \
     {                                                                                                                              \
-        { EMBER_ZCL_REPORTING_DIRECTION_REPORTED, 1, 0x0006, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 1, 65534, 0 },                   \
-            { EMBER_ZCL_REPORTING_DIRECTION_REPORTED, 1, 0x0008, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 1, 65534, 0 },               \
-            { EMBER_ZCL_REPORTING_DIRECTION_REPORTED, 1, 0x0101, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 1, 65534, 0 },               \
-            { EMBER_ZCL_REPORTING_DIRECTION_REPORTED, 1, 0x0300, 0x0003, CLUSTER_MASK_SERVER, 0x0000, 1, 65534, 0 },               \
-            { EMBER_ZCL_REPORTING_DIRECTION_REPORTED, 1, 0x0300, 0x0004, CLUSTER_MASK_SERVER, 0x0000, 1, 65534, 0 },               \
+        { EMBER_ZCL_REPORTING_DIRECTION_REPORTED, 1, 0x0006, 0x0000, CLUSTER_MASK_SERVER, 0x0000, { { 1, 65534, 0 } } },           \
```
Comment (bhaskar-apple) [inline examples/wifi-echo/server/esp32/main/gen/endpoint_config.h:557]: Needed to add braces to avoid initialization errors.

File: src/app/reporting/reporting-default-configuration.c [hunk 2]
```diff
@@ -62,6 +65,28 @@ void emberAfPluginReportingLoadReportingConfigDefaults(void)
...
+ * configuration values from user if there is no default value available within
+ * af generated default reporting configuration tabel. The application need to
+ * write to the minInterval, maxInterval and reportable change in the passed
+ * IO pointer in the arguement while handleing this callback, then application
+ * shall return true if it has provided the default values or else false for
+ * reporting plugin to further handleing.
+ *
+ * @param entry   Ver.: always
+ */
+bool emberAfPluginReportingGetDefaultReportingConfigCallback(EmberAfPluginReportingEntry * entry)
```
Comment (bhaskar-apple) [inline src/app/reporting/reporting-default-configuration.c:80]: Ported from Silabs SDK

File: src/app/reporting/reporting.c [hunk 3]
```diff
@@ -67,6 +68,24 @@ EmberEventControl emberAfPluginReportingTickEventControl;
...
+ * application can use this callback for scheduling readings or measurements
+ * based on the minimum and maximum reporting interval for the entry. The
+ * application should return EMBER_ZCL_STATUS_SUCCESS if it can support the
+ * configuration or an error status otherwise. Note: attribute reporting is
+ * required for many clusters and attributes, so rejecting a reporting
+ * configuration may violate ZigBee specifications.
+ *
+ * @param entry   Ver.: always
+ */
+EmberAfStatus emberAfPluginReportingConfiguredCallback(const EmberAfPluginReportingEntry * entry)
```
Comment (bhaskar-apple) [inline src/app/reporting/reporting.c:84]: Ported from Silabs SDK

File: src/app/reporting/reporting.c [hunk 4]
```diff
@@ -138,8 +157,11 @@ void emberAfPluginReportingInitCallback(void)
     {
         EmberAfPluginReportingEntry entry;
         emAfPluginReportingGetEntry(i, &entry);
+#pragma GCC diagnostic push
```
Comment (bhaskar-apple) [inline src/app/reporting/reporting.c:160]: Need to add these to avoid uninitialized and maybe-initialized warnings being treated as errors.

File: src/app/util/af-types.h [hunk 5]
```diff
@@ -1977,7 +1977,15 @@ typedef struct
 #define EMBER_AF_PERMIT_JOIN_FOREVER 0xFF
 #define EMBER_AF_PERMIT_JOIN_MAX_TIMEOUT 0xFE
 
+#define MAX_INT32U_VALUE (0xFFFFFFFFUL)
```
Comment (bhaskar-apple) [inline src/app/util/af-types.h:1980]: Ported from Silabs SDK

File: src/app/util/util.c [hunk 6]
```diff
@@ -1416,3 +1416,13 @@ EmberStatus emberAfDeactivateServerTick(uint8_t endpoint, EmberAfClusterId clust
 {
     return EMBER_SUCCESS; // Stub for now.
 }
+
```
Comment (bhaskar-apple) [inline src/app/util/util.c:1419]: Stub implementation tracked here
Implement stubs in zcl reporting cluster #2470

**Review by mspang — APPROVED** [review]

File: src/app/util/types_stub.h [hunk 7]
```diff
@@ -1934,4 +1934,39 @@ typedef struct
...
+ * @note To better understand the parameters of this macro, refer to the
+ *           example of token usage above.
+ *
+ * @param data   A pointer to where the token data should be placed.
+ *
+ * @param token  The token name used in <code>DEFINE_*_TOKEN</code>,
+ *               prepended with <code>TOKEN_</code>.
+ * @param index  The index to access in the indexed token.
+ */
+#define halCommonGetIndexedToken(data, token, index)
```
Comment (rwalker-apple) [inline src/app/util/types_stub.h:1951]: these have to plumb to persistent storage or be replaced by CHIP config code?

**Review by rwalker-apple — APPROVED** [review]
nice work

**Comment by bhaskar-apple** [comment]
@andy31415 @BroderickCarlin @hawk248 @saurabhst - review please

File: src/app/reporting/reporting-default-configuration.c (hunk 2 above)
Comment (bzbarsky-apple) [reply src/app/reporting/reporting-default-configuration.c:80]: This info should probably be in the commit message.

File: src/app/reporting/reporting.c (hunk 3 above)
Comment (bzbarsky-apple) [reply src/app/reporting/reporting.c:84]: Again, should say that in the commit message.

Please have on of the silabs folks sign off on these bits license-wise?

File: src/app/reporting/reporting.c (hunk 4 above)
Comment (bzbarsky-apple) [reply src/app/reporting/reporting.c:160]: That's annoying.  I wish compilers understood the "out param here!" pattern this is using...

I guess we could initialize the struct with `{}` if we really care; might be less noisy than having to do this all over the place  Followup for that, maybe?

File: src/app/reporting/reporting.c [hunk 8]
```diff
@@ -179,9 +206,9 @@ void emberAfPluginReportingTickEventHandler(void)
         {
             continue;
         }
-
```
Comment (bzbarsky-apple) [inline src/app/reporting/reporting.c:182]: Why this line removal?

File: src/app/reporting/reporting.c [hunk 9]
```diff
@@ -199,26 +226,31 @@ void emberAfPluginReportingTickEventHandler(void)
...
         {
+#pragma GCC diagnostic pop
             if (appResponseLength + reportSize > smallestPayloadMaxLength)
             {
                 emberAfReportingPrintln("Reporting Entry Full - creating new report");
             }
             conditionallySendReport(apsFrame->sourceEndpoint, apsFrame->clusterId);
             apsFrame = NULL;
         }
-
```
Comment (bzbarsky-apple) [inline src/app/reporting/reporting.c:217]: And this one?

File: src/app/util/types_stub.h (hunk 7 above)
Comment (bzbarsky-apple) [reply src/app/util/types_stub.h:1951]: Definitely want an issue tracking implementing this (and the "set" version) for real and link to it here.

**Review by bzbarsky-apple — COMMENTED** [review]
I'm a little confused by how this links, given that `emberAfSendCommandUnicastToBindingsWithCallback` and `emberAfSendCommandUnicastToBindings` are commented out, afaict...

**Comment by bzbarsky-apple** [comment]
I guess it links because `emberAfPluginReportingTickEventHandler` is dead code as far as the linker goes.  Looks like the only place it's used is `af-gen-event.h` putting it into `EMBER_AF_GENERATED_EVENTS` which is then used by `af-event.c`, and we're not importing any of that at all at the moment.  

That's probably OK for the moment, but once we hook this up we'll need to do a bunch more work to make the actual sending function properly, talk to the bindings, etc.  Of course those are also the pieces the DM folks want to change, which is why I'm not suggesting we try to deal with it now.

File: src/app/reporting/reporting.c (hunk 3 above)
Comment (bhaskar-apple) [reply src/app/reporting/reporting.c:84]: @wehale @selissia - is it ok to port this from the Silabs SDK?

File: src/app/util/types_stub.h (hunk 7 above)
Comment (bhaskar-apple) [reply src/app/util/types_stub.h:1951]: https://github.com/project-chip/connectedhomeip/issues/2470
Using this one for this as well.

File: src/app/reporting/reporting.c (hunk 4 above)
Comment (bhaskar-apple) [reply src/app/reporting/reporting.c:160]: Sure will do a follow up

File: src/app/reporting/reporting.c (hunk 9 above)
Comment (bhaskar-apple) [reply src/app/reporting/reporting.c]: Inadvertently got taken out. Fixed

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@saurabhst @jelderton @hawk248 Could you take a look please?

File: src/app/reporting/reporting.c [hunk 10]
```diff
@@ -67,6 +69,24 @@ EmberEventControl emberAfPluginReportingTickEventControl;
...
+/** @brief Configured
+ *
+ * This callback is called by the Reporting plugin whenever a reporting entry
+ * is configured, including when entries are deleted or updated. The
+ * application can use this callback for scheduling readings or measurements
+ * based on the minimum and maximum reporting interval for the entry. The
+ * application should return EMBER_ZCL_STATUS_SUCCESS if it can support the
+ * configuration or an error status otherwise. Note: attribute reporting is
+ * required for many clusters and attributes, so rejecting a reporting
+ * configuration may violate ZigBee specifications.
```
Comment (BroderickCarlin) [inline src/app/reporting/reporting.c:81]: Just a thought, but do we want to scrub mentions of `Zigbee` from added code/comments or do we view this as more throw away code until we get the CHIP data/device model in place?

**Review by BroderickCarlin — APPROVED** [review]

File: src/app/reporting/reporting.c (hunk 10 above)
Comment (bhaskar-apple) [reply src/app/reporting/reporting.c:81]: We have references to Zigbee either as Zigbee or ZCL already in the data model layer. My take is to do a scrub off this later in a separate pass.
