### PR TITLE
[Android] Save Wifi credentials to CHIP device

### LINKED ISSUE #2715: Rendezvous over BLE in android app not working
**Problem**
Android App is not doing pairing over BLE for esp32 target.
It is supposed to be working as [this ](https://github.com/project-chip/connectedhomeip/projects/20) project is closed.

@vidhis88 can you give more information on this?

**Proposed Solution**
Add new PR to add this feature in android app.

### PR DESCRIPTION
**Pull request by vidhis88**
#### Problem
Android CHIP Tool app does not have a way to send Wi-Fi network credentials to CHIP device.

 #### Summary of Changes
1. Implement DevicePairingDelegate for Android in the JNI layer.
2. Send Wi-Fi credentials to CHIP device in the OnNetworkCredentialsRequestedCallback.

The lower level C++ changes are patched in from @andy31415's PR #3543.

 Fixes #2715

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

File: src/controller/java/AndroidDeviceControllerWrapper.h [hunk 1]
```diff
@@ -23,43 +23,66 @@
...
-#include "AndroidDevicePairingDelegate.h"
-
 /**
  * This class contains all relevant information for the JNI view of CHIPDeviceController
  * to handle all controller-related processing.
  *
  * Generally it contains the DeviceController class itself, plus any related delegates/callbacks.
  */
-class AndroidDeviceControllerWrapper
+class AndroidDeviceControllerWrapper : chip::DeviceController::DevicePairingDelegate
```
Comment (mspang) [inline src/controller/java/AndroidDeviceControllerWrapper.h:32]: Can we use public inheritance here?

Comment (vidhis88) [reply src/controller/java/AndroidDeviceControllerWrapper.h]: Done.

**Review by mspang — APPROVED** [review]

**Comment by vidhis88** [comment]
@rwalker-apple @saurabhst @hawk248 @BroderickCarlin @chrisdecenzo @jelderton @bzbarsky-apple

**Review by bzbarsky-apple — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]
