### PR TITLE
Fix 12692: Chiptool cannot commission tv-app on same machine

### LINKED ISSUE #12692: Chiptool cannot commission tv-app on same machine
#### Problem
 * I should be able to commission the tv-app using the chiptool running on same linux host
 * currently this has broken (broke on 11/30)

 #### Proposed Solution
* Problem is that both tv-app and chip-tool are configured to listen on the same default commissioner port (5542)
* Solution is to modify tv-app configuration to not use the default commissioner port

### PR DESCRIPTION
**Pull request by chrisdecenzo**
#### Problem
* Fixes #12692: Chiptool cannot commission tv-app on same machine

#### Change overview
* Problem is that both tv-app and chip-tool are configured to listen on the same default commissioner port (5542)
* Solution is to modify tv-app configuration to not use the default commissioner port

#### Testing
* Commission tv-app from chiptool running on same host:

./out/host/chip-tv-app --secured-device-port 5640
./out/host/chip-tool pairing onnetwork-long 1234 20202021 3840

### CODE REVIEW

**Review by lazarkov — APPROVED** [review]

File: examples/platform/linux/AppMain.cpp [hunk 1]
```diff
@@ -222,8 +222,8 @@ CHIP_ERROR InitCommissioner()
     ReturnErrorOnFailure(gFabricStorage.Initialize(&gServerStorage));
 
     factoryParams.fabricStorage = &gFabricStorage;
-    // use a different listen port for the commissioner.
-    factoryParams.listenPort              = LinuxDeviceOptions::GetInstance().securedCommissionerPort;
+    // use a different listen port for the commissioner than the default used by chip-tool.
+    factoryParams.listenPort              = LinuxDeviceOptions::GetInstance().securedCommissionerPort + 10;
```
Comment (bzbarsky-apple) [inline examples/platform/linux/AppMain.cpp:226]: Why are we listening on a hardcoded port here to start with?  Can we not use an ephemeral port?

**Review by yunhanw-google — APPROVED** [review]

File: examples/platform/linux/AppMain.cpp (hunk 1 above)
Comment (chrisdecenzo) [reply examples/platform/linux/AppMain.cpp:226]: linuxDeviceOptions can be overridden from the command line so the port choice is already change-able

**Review by woody-apple — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

File: examples/platform/linux/AppMain.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply examples/platform/linux/AppMain.cpp:226]: Yes, but why are we not using an ephemeral port when no command-line option is provided?  @andy31415 @chrisdecenzo
