### PR TITLE
Fix too large buffer size in VerifyStatusReport()

### LINKED ISSUE #4748: TestBdxTransferSession tries to read out of packetbuffer bounds
#### Problem
In `TestBdxTransferSession.cpp`, `VerifyStatusReport` does:
```
    Encoding::LittleEndian::Reader reader(msg->Start() + headerSize, msg->DataLength());
```
This is starting reading `headerSize` bytes into the data, but still claiming the full data length is available to be read, which seems wrong.

 #### Proposed Solution
Consume `headerSize` bytes first, then just pass `Start()` as the first arg.  Or subtract `headerSize` from the data length if we don't want to change the packet buffer state.  Or something.

@holbrookt

### PR DESCRIPTION
**Pull request by holbrookt**
#### Problem
In `TestBdxTransferSession.cpp`, `VerifyStatusReport()`, a `Reader` object was being initialized with a length that exceeded the bounds of the PacketBuffer to read.

 #### Summary of Changes
Subtract `headerSize` from the length parameter so that the Reader cannot read data beyond the bounds of the PacketBuffer

 Fixes #4748

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Comment by mspang** [comment]
@kpschoedel 

Can we do something like

Reader reader(msg)
reader.Skip(headerSize) ?

**Comment by kpschoedel** [comment]
> reader.Skip(headerSize) ?

BufferReader doesn't have `Skip()`, but it probably should.

**Comment by tcarmelveilleux** [comment]
> > reader.Skip(headerSize) ?
> 
> BufferReader doesn't have `Skip()`, but it probably should.

I strongly feel like adding `Skip()` is a root-cause fix that could avoid the risky size-arithmetic that is being introduced as part of the fix.

**Comment by holbrookt** [comment]
> > > reader.Skip(headerSize) ?
> > 
> > 
> > BufferReader doesn't have `Skip()`, but it probably should.
> 
> I strongly feel like adding `Skip()`/`Reset()` is a root-cause fix that could avoid the risky size-arithmetic that is being introduced as part of the fix.

I'm happy to add this as part of this PR

**Comment by mspang** [comment]
> > > > reader.Skip(headerSize) ?
> > > 
> > > 
> > > BufferReader doesn't have `Skip()`, but it probably should.
> > 
> > 
> > I strongly feel like adding `Skip()`/`Reset()` is a root-cause fix that could avoid the risky size-arithmetic that is being introduced as part of the fix.
> 
> I'm happy to add this as part of this PR

Yes, please.

File: src/protocols/bdx/tests/TestBdxTransferSession.cpp [hunk 1]
```diff
@@ -129,8 +129,13 @@ void VerifyStatusReport(nlTestSuite * inSuite, void * inContext, const System::P
     NL_TEST_ASSERT(inSuite, err == CHIP_NO_ERROR);
     NL_TEST_ASSERT(inSuite, payloadHeader.GetProtocolID() == Protocols::kProtocol_Protocol_Common);
     NL_TEST_ASSERT(inSuite, payloadHeader.GetMessageType() == static_cast<uint8_t>(Protocols::Common::MsgType::StatusReport));
+    if (headerSize > msg->DataLength())
```
Comment (bzbarsky-apple) [inline src/protocols/bdx/tests/TestBdxTransferSession.cpp:132]: In theory, this should have caused `err` to be an error....  I'm OK with keeping it, or ok with a comment saying we can assume `headerSize` is small enough because `err == CHIP_NO_ERROR` here.

Certainly non-test code makes that assumption.

File: src/protocols/bdx/tests/TestBdxTransferSession.cpp [hunk 2]
```diff
@@ -129,8 +129,13 @@ void VerifyStatusReport(nlTestSuite * inSuite, void * inContext, const System::P
...
+    {
+        NL_TEST_ASSERT(inSuite, false);
+        return;
+    }
 
-    Encoding::LittleEndian::Reader reader(msg->Start() + headerSize, msg->DataLength());
+    Encoding::LittleEndian::Reader reader(msg->Start() + headerSize, static_cast<uint16_t>(msg->DataLength() - headerSize));
```
Comment (bzbarsky-apple) [inline src/protocols/bdx/tests/TestBdxTransferSession.cpp:138]: Probably OK if we need to not change the state of `msg`.  Otherwise we could `msg->Consume(headerSize)` or something and then ditch the arithmetic.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
