### PR TITLE
Efr32 lock app

### LINKED ISSUE #1955: EFR32 Lock-app example doesn't build for mcu family MG21
#### Problem
The lock-app example doesn't compile when specifying a EFR32 board of the MG21 family. ex.: make BOARD=BRD4180A
The example seem to have been generated for specific device (from the MG12 family) with simplicity studio.

Some configuration specifics to some board might be wrong even for the MG12 family even if the build complete succesfully because the file currently used have been generated for one specific board.

 #### Proposed Solution
Makefile should use the correct files from the Gecko SDK depending of the board specified int the make command (make BOARD=<BRDXXXXX>

### PR DESCRIPTION
**Pull request by jmartinez-silabs**
#### Problem
Fix issues where the wrong GSDK board specific files were used. 
Project built with a board of MG21 family now succesfully builds. 
Correct peripheral configuration and initialization is used based on the Board name provided at the make command make BOARD=<BRDXXXXX>

 #### Summary of Changes
Add new platform subdirectory for MCU family MG12 and MG21 and for each proposed board in those family
Add a board_id define in the makefile to match board capability in the code
Add files for the mbedtls crypto on  MG21 family

fixes #1955

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@jmartinez-silabs Thanks for the submission! Can you restyle this please?

**Comment by woody-apple** [comment]
@jelderton @andy31415 ?

File: examples/lock-app/efr32/include/hal-config-app-common.h [hunk 1]
```diff
@@ -1,37 +1,22 @@
...
- *
- * The licensor of this software is Silicon Laboratories Inc. Your use of this
- * software is governed by the terms of Silicon Labs Master Software License
- * Agreement (MSLA) available at
- * www.silabs.com/about-us/legal/master-software-license-agreement. This
- * software is distributed to you in Source Code format and is governed by the
- * sections of the MSLA applicable to Source Code.
- *
- ******************************************************************************/
+/***************************************************************************/ /**
```
Comment (jelderton) [inline examples/lock-app/efr32/include/hal-config-app-common.h:1]: will this get cleaned from the style-bot?  Not sure why all of these are jacked

**Review by jelderton — APPROVED** [review]
