### PR TITLE
[ICD][Android] Add ICD storage API, UI

### LINKED ISSUE #31151: [ICD] Need to ICD Client Storage, Management UI in Android Chip-tool
### Reproduction steps

In Chip-tool, It is already implemented ICD Client Storage and Management Command.
Implementation is required to perform the same test in Android Chip-tool.

Related #30863, #29783

### Bug prevalence

always

### GitHub hash of the SDK that was being used

b22a39645b72b26621467dd161209fc08c83fad6

### Platform

android

### Platform Version(s)

_No response_

### Type

Platform Issue

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by joonhaengHeo**
Fix #31151 

Add to check ICD storage, view menu. in Android Chiptool and Java controller.

### CODE REVIEW

File: src/controller/java/src/chip/devicecontroller/ICDClientInfo.java [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+ *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ *   See the License for the specific language governing permissions and
+ *   limitations under the License.
+ *
+ */
+package chip.devicecontroller;
+
+/** Class for holding ICD Client information. */
+public class ICDClientInfo {
+  private final long nodeId;
```
Comment (yunhanw-google) [inline src/controller/java/src/chip/devicecontroller/ICDClientInfo.java:22]: naming: peerNodeId?
nodeId is scoped with fabric
so you may create a new class which is equivalent with ScopedNodeId ?

File: src/controller/java/AndroidDeviceControllerWrapper.cpp [hunk 2]
```diff
@@ -889,10 +910,36 @@ void AndroidDeviceControllerWrapper::OnICDRegistrationInfoRequired()
...
     chip::DeviceLayer::StackUnlock unlock;
+
+    CHIP_ERROR err = CHIP_NO_ERROR;
+    chip::app::ICDClientInfo clientInfo;
+    clientInfo.peer_node         = ScopedNodeId(icdNodeId, Controller()->GetFabricIndex());
+    clientInfo.monitored_subject = mAutoCommissioner.GetCommissioningParameters().GetICDMonitoredSubject().Value();
+    clientInfo.start_icd_counter = icdCounter;
+
+    err = mICDClientStorage.SetKey(clientInfo, mAutoCommissioner.GetCommissioningParameters().GetICDSymmetricKey().Value());
+    if (err == CHIP_NO_ERROR)
```
Comment (yunhanw-google) [inline src/controller/java/AndroidDeviceControllerWrapper.cpp:921]: if failed, print error, then early return? currently you are calling onICDRegistrationComplete even thought it fails.

File: src/controller/java/AndroidDeviceControllerWrapper.cpp [hunk 3]
```diff
@@ -637,6 +648,16 @@ void AndroidDeviceControllerWrapper::OnPairingDeleted(CHIP_ERROR error)
 void AndroidDeviceControllerWrapper::OnCommissioningComplete(NodeId deviceId, CHIP_ERROR error)
 {
     chip::DeviceLayer::StackUnlock unlock;
+
+    if (error != CHIP_NO_ERROR && mDeviceIsICD)
+    {
+        CHIP_ERROR deleteEntryError = mICDClientStorage.DeleteEntry(ScopedNodeId(deviceId, Controller()->GetFabricIndex()));
+        if (deleteEntryError != CHIP_NO_ERROR)
+        {
+            ChipLogError(chipTool, "Failed to delete ICD entry: %s", ErrorStr(error));
```
Comment (yunhanw-google) [inline src/controller/java/AndroidDeviceControllerWrapper.cpp:657]: err.Format()?

File: src/controller/java/AndroidDeviceControllerWrapper.cpp [hunk 4]
```diff
@@ -889,10 +910,36 @@ void AndroidDeviceControllerWrapper::OnICDRegistrationInfoRequired()
...
+        err = mICDClientStorage.StoreEntry(clientInfo);
+    }
+
+    if (err == CHIP_NO_ERROR)
+    {
+        ChipLogProgress(Controller, "Saved ICD Symmetric key for " ChipLogFormatX64, ChipLogValueX64(icdNodeId));
+    }
+    else
+    {
+        mICDClientStorage.RemoveKey(clientInfo);
```
Comment (yunhanw-google) [inline src/controller/java/AndroidDeviceControllerWrapper.cpp:932]: if failed, print error, then early return? currently you are calling onICDRegistrationComplete even thought it fails.

File: src/controller/java/AndroidDeviceControllerWrapper.h [hunk 5]
```diff
@@ -217,6 +220,8 @@ class AndroidDeviceControllerWrapper : public chip::Controller::DevicePairingDel
     // TODO: This may need to be injected as a SessionKeystore*
     chip::Crypto::RawKeySessionKeystore mSessionKeystore;
 
+    chip::app::DefaultICDClientStorage mICDClientStorage;
```
Comment (yunhanw-google) [inline src/controller/java/AndroidDeviceControllerWrapper.h:223]: if we reboot android chip-tool, can it be persistent?

Comment (joonhaengHeo) [reply src/controller/java/AndroidDeviceControllerWrapper.h:223]: Yes. 
In each case, I confirmed that it was saved and loaded.
  - Java controller: File
  - Android: Shared Preference.

File: src/controller/java/src/chip/devicecontroller/ICDClientInfo.java (hunk 1 above)
Comment (joonhaengHeo) [reply src/controller/java/src/chip/devicecontroller/ICDClientInfo.java:22]: The name was changed to peerNodeId. And, in the case of ChipDeviceController, since an object is created for each Fabric, I don't think it needs to be configured with ScopedNodeId. Do you have any other opinions?

File: src/controller/java/AndroidDeviceControllerWrapper.cpp (hunk 3 above)
Comment (joonhaengHeo) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:657]: Changed. Thanks.

File: src/controller/java/AndroidDeviceControllerWrapper.cpp (hunk 4 above)
Comment (joonhaengHeo) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:932]: The current DevicePairingDelegate implementation does not consider stopping it. Even in other error cases, the error code is transmitted only to the upper layer.

File: src/controller/java/AndroidDeviceControllerWrapper.cpp (hunk 2 above)
Comment (joonhaengHeo) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:921]: The current DevicePairingDelegate implementation does not consider stopping it. Even in other error cases, the error code is transmitted only to the upper layer.

Comment (yunhanw-google) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:921]: if fails, why we continue? maybe it is existing bug?

File: src/controller/java/AndroidDeviceControllerWrapper.cpp [hunk 6]
```diff
@@ -889,10 +910,36 @@ void AndroidDeviceControllerWrapper::OnICDRegistrationInfoRequired()
 void AndroidDeviceControllerWrapper::OnICDRegistrationComplete(chip::NodeId icdNodeId, uint32_t icdCounter)
 {
     chip::DeviceLayer::StackUnlock unlock;
+
```
Comment (yunhanw-google) [inline src/controller/java/AndroidDeviceControllerWrapper.cpp:913]: I think we can create one ICDRegistrationInfo struct, and put it as a member in AndroidDeviceControllerWrapper, and store clientInfo there.
When generating the symmetric key, we could also store that key in ICDRegistrationInfo, 
When commissioning completes, we may apply them in ICD storage and always notify upper application with these info.
Note: for android-chip-tool, we may or may not apply ICD storage and further check-in message, therefore we may introduce the boolean variable to enable/disable the storage?

Comment (joonhaengHeo) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:913]: When ICDRegistrationComplete was added to the current structure, passing symmetricKey was added. However, if commissioning fails, this key value is invalid, so erasing it should be considered when implementing the upper layer. And, I think it is appropriate to generate keys randomly. If it is based upon FabricID / nodeID, there is a risk that the key value can be guessed.

File: src/controller/java/AndroidDeviceControllerWrapper.cpp (hunk 2 above)
Comment (joonhaengHeo) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:923]: When a failure occurs, commissioning cannot be stopped, so there is concern as to whether it is appropriate to return simply by failing to save. Wouldn't it be more appropriate for a callback function to be called from the Upper Layer when only saving fails?

File: examples/kotlin-matter-controller/java/src/com/matter/controller/commands/pairing/PairingCommand.kt [hunk 7]
```diff
@@ -177,10 +177,10 @@ abstract class PairingCommand(
     logger.log(Level.INFO, "onICDRegistrationInfoRequired")
   }
 
-  override fun onICDRegistrationComplete(icdNodeId: Long, icdCounter: Long) {
+  override fun onICDRegistrationComplete(icdNodeId: Long, icdCounter: Long, symmetricKey: ByteArray) {
```
Comment (yunhanw-google) [inline examples/kotlin-matter-controller/java/src/com/matter/controller/commands/pairing/PairingCommand.kt:180]: should we also pass user_active_mode_trigger_hint and instruction and monitor subject via this callback? 
maybe we create a class to cover these meta data in case we change it in the future?

File: src/controller/java/AndroidDeviceControllerWrapper.cpp (hunk 6 above)
Comment (yunhanw-google) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:913]: Let's follow-up the unique symmetric key discussion in the follow-up

File: src/controller/java/AndroidDeviceControllerWrapper.cpp (hunk 4 above)
Comment (yunhanw-google) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:934]: ack

File: src/controller/java/AndroidDeviceControllerWrapper.cpp (hunk 2 above)
Comment (yunhanw-google) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:923]: ack

File: src/controller/java/AndroidDeviceControllerWrapper.cpp (hunk 6 above)
Comment (yunhanw-google) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:913]: I think we can mimic 
https://github.com/project-chip/connectedhomeip/blob/371756bb6ad0a2fe12464ef50f64629f2313b250/examples/chip-tool/commands/pairing/PairingCommand.cpp#L390 to remove the bad key and icd metadata when commmisioning complete in this wrapper file.

otherwises, you have to figure out how to implement this removal mechanism via java/kotlin API to this c++ wrapper?

File: src/controller/java/AndroidDeviceControllerWrapper.cpp (hunk 4 above)
Comment (joonhaengHeo) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:934]: I will add errorCode in this input parameter.

File: examples/kotlin-matter-controller/java/src/com/matter/controller/commands/pairing/PairingCommand.kt (hunk 7 above)
Comment (joonhaengHeo) [reply examples/kotlin-matter-controller/java/src/com/matter/controller/commands/pairing/PairingCommand.kt]: I modified to class parameter.

File: src/controller/java/AndroidDeviceControllerWrapper.cpp (hunk 6 above)
Comment (joonhaengHeo) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:913]: I already implemented using below code.
https://github.com/project-chip/connectedhomeip/pull/31193/files#diff-22864825009a652ecbadf8006425b968ec54dbbafd6f39c720a0c84f58c089f3R652

Comment (yunhanw-google) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:913]: thanks

File: src/controller/java/AndroidDeviceControllerWrapper.h (hunk 5 above)
Comment (yunhanw-google) [reply src/controller/java/AndroidDeviceControllerWrapper.h:223]: thanks

File: examples/kotlin-matter-controller/java/src/com/matter/controller/commands/pairing/PairingCommand.kt (hunk 7 above)
Comment (yunhanw-google) [reply examples/kotlin-matter-controller/java/src/com/matter/controller/commands/pairing/PairingCommand.kt]: Followup: please rename ICDDeviceInfo to ICDRegistrationInfo, and put nodeId, counter, monitor subject inside

File: src/controller/java/src/chip/devicecontroller/ICDClientInfo.java (hunk 1 above)
Comment (yunhanw-google) [reply src/controller/java/src/chip/devicecontroller/ICDClientInfo.java]: i see, thanks for clarification.

File: src/controller/java/CHIPDeviceController-JNI.cpp [hunk 8]
```diff
@@ -2151,6 +2142,73 @@ JNI_METHOD(jobject, computePaseVerifier)
...
+    err = JniReferences::GetInstance().CreateArrayList(jInfo);
+    VerifyOrReturnValue(err == CHIP_NO_ERROR, nullptr,
+                        ChipLogError(Controller, "CreateArrayList failed!: %" CHIP_ERROR_FORMAT, err.Format()));
+
+    auto iter = wrapper->getICDClientStorage()->IterateICDClientInfo();
+
+    jmethodID constructor;
+    jclass infoClass;
+
+    err = JniReferences::GetInstance().GetClassRef(env, "chip/devicecontroller/ICDClientInfo", infoClass);
```
Comment (yunhanw-google) [inline src/controller/java/CHIPDeviceController-JNI.cpp:2169]: please kindly stop using GetClassRef and s JniClass icdClientInfoClass pattern.
please use GetLocalClassRef.
Although this  getICDClientInfo is called from java/kotlin layer and JVM do manage the local reference recycling, I prefer we explicitly call  JniLocalReferenceManager manager(env) in this beginning of the function.

File: src/controller/java/AndroidDeviceControllerWrapper.cpp (hunk 4 above)
Comment (yunhanw-google) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:934]: then we just need to inject error inside onICDRegistrationComplete if any for this function. thanks

Comment (joonhaengHeo) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp:934]: I already added in onICDRegistrationComplete.
https://github.com/project-chip/connectedhomeip/pull/31193/files#diff-9e353b12e06979cac624339aaf9d8b9c7da07cd4ebe98157dee888cdd297002cR1625

File: examples/kotlin-matter-controller/java/src/com/matter/controller/commands/pairing/PairingCommand.kt (hunk 7 above)
Comment (joonhaengHeo) [reply examples/kotlin-matter-controller/java/src/com/matter/controller/commands/pairing/PairingCommand.kt]: The reason for creating a separate class is because there is a need to later pass UserActiveModeTriggerHint and UserActiveModeTriggerInstruction to the Upper Layer. Of course, according to your opinion, icdCounter, icdNodeId, and MonitoredSubject should also be included, but I think it is inappropriate to include UserActiveModeTriggerHint and UserActiveModeTriggerInstruction in ICDRegistrationInfo.

(Other parameters except symmetric key will be implemented after this PR is merged.)

File: src/controller/java/CHIPDeviceController-JNI.cpp (hunk 8 above)
Comment (joonhaengHeo) [reply src/controller/java/CHIPDeviceController-JNI.cpp:2169]: I modified.

File: examples/kotlin-matter-controller/java/src/com/matter/controller/commands/pairing/PairingCommand.kt (hunk 7 above)
Comment (yunhanw-google) [reply examples/kotlin-matter-controller/java/src/com/matter/controller/commands/pairing/PairingCommand.kt]: agree, thanks

File: src/controller/java/CHIPDeviceController-JNI.cpp (hunk 8 above)
Comment (yunhanw-google) [reply src/controller/java/CHIPDeviceController-JNI.cpp]: thanks

File: src/controller/java/CHIPDeviceController-JNI.cpp [hunk 9]
```diff
@@ -2152,6 +2143,73 @@ JNI_METHOD(jobject, computePaseVerifier)
...
+
+    jobject jInfo = nullptr;
+    chip::app::ICDClientInfo info;
+    chip::FabricIndex fabricIndex = static_cast<chip::FabricIndex>(jFabricIndex);
+
+    ChipLogProgress(Controller, "getICDClientInfo(%u) called", fabricIndex);
+    AndroidDeviceControllerWrapper * wrapper = AndroidDeviceControllerWrapper::FromJNIHandle(handle);
+    VerifyOrReturnValue(wrapper != nullptr, nullptr, ChipLogError(Controller, "wrapper is null"));
+
+    err = JniReferences::GetInstance().CreateArrayList(jInfo);
```
Comment (yunhanw-google) [inline src/controller/java/CHIPDeviceController-JNI.cpp:2160]: could you move JniLocalReferenceManager manager(env); before CreateArrayList? for example, line 2151, so that manager could release the objects created from CreateArrayList as well, thanks

**Review by yunhanw-google — APPROVED** [review]

File: src/controller/java/AndroidDeviceControllerWrapper.cpp [hunk 10]
```diff
@@ -889,14 +910,59 @@ void AndroidDeviceControllerWrapper::OnICDRegistrationInfoRequired()
...
     JNIEnv * env = JniReferences::GetInstance().GetEnvForCurrentThread();
     jmethodID onICDRegistrationCompleteMethod;
-    CHIP_ERROR err = JniReferences::GetInstance().FindMethod(env, mJavaObjectRef, "onICDRegistrationComplete", "(JJ)V",
-                                                             &onICDRegistrationCompleteMethod);
+    jclass icdDeviceInfoClass         = nullptr;
+    jmethodID icdDeviceInfoStructCtor = nullptr;
+    jobject icdDeviceInfoObj          = nullptr;
+    jbyteArray jSymmetricKey          = nullptr;
+    err                               = JniReferences::GetInstance().FindMethod(env, mJavaObjectRef, "onICDRegistrationComplete",
```
Comment (yunhanw-google) [inline src/controller/java/AndroidDeviceControllerWrapper.cpp:947]: this err would override "err = mICDClientStorage.StoreEntry(clientInfo);", maybe we should use different variable called CHIP_ERROR methodErr here?

File: src/controller/java/CHIPDeviceController-JNI.cpp (hunk 9 above)
Comment (joonhaengHeo) [reply src/controller/java/CHIPDeviceController-JNI.cpp:2160]: After moving it above CreateArrayList, I get a "use of deleted local reference 0x71" Crash.

File: src/controller/java/AndroidDeviceControllerWrapper.cpp (hunk 10 above)
Comment (joonhaengHeo) [reply src/controller/java/AndroidDeviceControllerWrapper.cpp]: Changed.

**Review by jmartinez-silabs — APPROVED** [review]

File: src/controller/java/AndroidDeviceControllerWrapper.cpp [hunk 11]
```diff
@@ -889,14 +910,61 @@ void AndroidDeviceControllerWrapper::OnICDRegistrationInfoRequired()
...
+    jmethodID icdDeviceInfoStructCtor = nullptr;
+    jobject icdDeviceInfoObj          = nullptr;
+    jbyteArray jSymmetricKey          = nullptr;
+    CHIP_ERROR methodErr =
+        JniReferences::GetInstance().FindMethod(env, mJavaObjectRef, "onICDRegistrationComplete",
+                                                "(IJJLchip/devicecontroller/ICDDeviceInfo;)V", &onICDRegistrationCompleteMethod);
+    VerifyOrReturn(methodErr == CHIP_NO_ERROR,
+                   ChipLogError(Controller, "Error finding Java method: %" CHIP_ERROR_FORMAT, methodErr.Format()));
+
+    methodErr = chip::JniReferences::GetInstance().GetClassRef(env, "chip/devicecontroller/ICDDeviceInfo", icdDeviceInfoClass);
```
Comment (yunhanw-google) [inline src/controller/java/AndroidDeviceControllerWrapper.cpp:953]: Please use GetLocalClassRef here to prevent reference leak.
