### PR TITLE
Remove the kDNSServiceFlagsTimeout flag when calling DNSServiceGetAdd…

### LINKED ISSUE #33051: [Darwin] Figure out a better setup to have longer-running DNS resolves instead of doing them as-needed
### Reproduction steps

Right now the basic process for operational resolve on Darwin looks like this:

1. We start with the operational instance name.
2. We do a `DNSServiceResolve` to get the hostname and TXT records.
3. We do a bunch of `DNSServiceGetAddrInfo` (one per interface id we got results on), asking the for IPs for that hostname.
4. Once we get results back from `DNSServiceGetAddrInfo` we pass that info up to the caller.

Importantly: when we do `DNSServiceGetAddrInfo` we pass the `kDNSServiceFlagsTimeout` flag, so if we get nothing quickly we fail out and stop trying, even though our caller is willing to wait for 45 seconds for answers.

We should consider a few changes here:

1. Removing the `kDNSServiceFlagsTimeout` flag. This would be especially helpful with https://github.com/project-chip/connectedhomeip/issues/32512 also resolved, so we can stream the results back as they come in.
2. Generally having a longer-running `DNSServiceGetAddrInfo` for nodes we "care about" instead of kicking off things "when we need the info", so that we don't keep starting/stopping the DNS lookups.

### Platform

darwin

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nivi-apple**
…rInfo

- We should not be terminating the queries if we do not get anything back quickly The queries should be running until we get something back

Fixes: #33051

### CODE REVIEW

File: src/platform/Darwin/DnssdImpl.cpp [hunk 1]
```diff
@@ -43,7 +43,7 @@ constexpr uint16_t kSRPTimeoutInMsec = 250;
 
 constexpr DNSServiceFlags kRegisterFlags        = kDNSServiceFlagsNoAutoRename;
 constexpr DNSServiceFlags kBrowseFlags          = kDNSServiceFlagsShareConnection;
```
Comment (nivi-apple) [inline src/platform/Darwin/DnssdImpl.cpp:45]: Do we need these constants kBrowseFlags, kGetAddrInfoFlags? could just use the kDNSServiceFlagsShareConnection in the api calls? we might want to keep them for future use cases where we might add to the flags

Comment (ksperling-apple) [reply src/platform/Darwin/DnssdImpl.cpp:45]: I agree, I feel like seeing the flags inline at the call site would be more helpful than having these constants.

Comment (kiel-apple) [reply src/platform/Darwin/DnssdImpl.cpp:45]: It looks like `kRegisterFlags` is the only one of these constants that ends up being used more than once, and it's reused within a single function.

A middle ground would be to scope these constants to the functions where they are used rather than putting them in global scope, and that seems like the right solution for `kRegisterFlags` - the others are probably more clear with the flags inline.

Comment (nivi-apple) [reply src/platform/Darwin/DnssdImpl.cpp:45]: I would also add the flag for register and reconfirm records as well in the call site itself to be consistent since it doesn't have multiple flags there. If folks disagree I will revert that

**Review by kiel-apple — APPROVED** [review]

File: src/platform/Darwin/DnssdImpl.cpp [hunk 2]
```diff
@@ -179,10 +173,11 @@ CHIP_ERROR Register(void * context, DnssdPublishCallback callback, uint32_t inte
     ChipLogProgress(Discovery, "Registering service %s on host %s with port %u and type: %s on interface id: %" PRIu32,
                     StringOrNullMarker(name), StringOrNullMarker(hostname), port, StringOrNullMarker(type), interfaceId);
 
+    DNSServiceFlags registerFlags = kDNSServiceFlagsNoAutoRename;
```
Comment (kiel-apple) [inline src/platform/Darwin/DnssdImpl.cpp:176]: this can be `const` here to avoid changes within scope

**Review by kiel-apple — APPROVED** [review]

File: src/platform/Darwin/DnssdImpl.cpp [hunk 3]
```diff
@@ -179,10 +173,11 @@ CHIP_ERROR Register(void * context, DnssdPublishCallback callback, uint32_t inte
     ChipLogProgress(Discovery, "Registering service %s on host %s with port %u and type: %s on interface id: %" PRIu32,
                     StringOrNullMarker(name), StringOrNullMarker(hostname), port, StringOrNullMarker(type), interfaceId);
 
-    RegisterContext * sdCtx = nullptr;
+    const DNSServiceFlags registerFlags = kDNSServiceFlagsNoAutoRename;
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.cpp:176]: Why not constexpr?

**Review by bzbarsky-apple — APPROVED** [review]

File: src/platform/Darwin/DnssdImpl.cpp (hunk 3 above)
Comment (nivi-apple) [reply src/platform/Darwin/DnssdImpl.cpp]: done.

**Review by andy31415 — APPROVED** [review]
