### PR TITLE
[EFR32] Fix Storage audit - Allow storing null pointer of size 0

### LINKED ISSUE #20284: Ensure EFR32 platform succeeds Storage audit
#### Problem
PR https://github.com/project-chip/connectedhomeip/pull/20134 and https://github.com/project-chip/connectedhomeip/pull/20164 together introduced a storage API compliance audit.

This audit must be run and pass on nRF Connect and succeed against PersistentStorageDelegate used by lock-app (KVS file based)

To run the audit for anything using Server, build your target with chip_support_enable_storage_api_audit=true added to your GN args and then run your binary in a debugger. The default audit is added to Server::Init() and will cause an assert with logs on failure.

Audit passes once you see the following string in your logs

==== PersistentStorageDelegate API audit: SUCCESS ====
On failure, informative assertion failures are logged to assist in debugging.

 #### Proposed Solution
On failure, informative assertion failures are logged to assist in debugging.

Proposed Solution
Build with audit enabled
Run and comment on passing along with the SHA of the commit where it was run. Provide a logs capture of your run.
If you find failures, please document them in comments on the issue to help SDK team audit the types of failures/assumptions made.
Close the issue once you pass

### PR DESCRIPTION
**Pull request by jmartinez-silabs**
#### Problem
Fixes #20284

#### Change overview
Change platform implementation to allow the storage and reading of a Nullpointer if the given size is also 0.

#### Testing
Build with audit enable
`./scripts/examples/gn_efr32_example.sh examples/lighting-app/efr32/ out/lighting_app BRD4164A chip_support_enable_storage_api_audit=true`

Audit success if printed.
```
<info  > [SVR] Server initializing...
<error > [ATM] ==== PersistentStorageDelegate API audit: SUCCESS ====
```

### CODE REVIEW

File: src/platform/EFR32/EFR32Config.cpp [hunk 1]
```diff
@@ -336,33 +335,23 @@ CHIP_ERROR EFR32Config::WriteConfigValueStr(Key key, const char * str, size_t st
...
 
 CHIP_ERROR EFR32Config::WriteConfigValueBin(Key key, const uint8_t * data, size_t dataLen)
 {
-    CHIP_ERROR err;
+    CHIP_ERROR err = CHIP_ERROR_INVALID_ARGUMENT;
 
     VerifyOrExit(ValidConfigKey(key), err = CHIP_DEVICE_ERROR_CONFIG_NOT_FOUND); // Verify key id.
 
-    if (data != NULL)
+    // Only write NULL pointer if the given size is 0
```
Comment (tcarmelveilleux) [inline src/platform/EFR32/EFR32Config.cpp:349]:
```suggestion
    // Only allow NULL pointer if the given size is 0, since in that case, nothing is read at the pointer
```

File: src/platform/EFR32/KeyValueStoreManagerImpl.cpp [hunk 2]
```diff
@@ -146,7 +144,6 @@ CHIP_ERROR KeyValueStoreManagerImpl::_Get(const char * key, void * value, size_t
 CHIP_ERROR KeyValueStoreManagerImpl::_Put(const char * key, const void * value, size_t value_size)
 {
     VerifyOrReturnError(key != nullptr, CHIP_ERROR_INVALID_ARGUMENT);
-    VerifyOrReturnError(value != nullptr, CHIP_ERROR_INVALID_ARGUMENT);
```
Comment (tcarmelveilleux) [inline src/platform/EFR32/KeyValueStoreManagerImpl.cpp:149]: Value can only be nullptr if value_size is 0

**Review by tcarmelveilleux — APPROVED** [review]

File: src/platform/EFR32/KeyValueStoreManagerImpl.cpp (hunk 2 above)
Comment (jmartinez-silabs) [reply src/platform/EFR32/KeyValueStoreManagerImpl.cpp:149]: _Put then calls EFR32Config::WriteConfigValueBin which does the correct check :)

File: src/platform/EFR32/EFR32Config.cpp (hunk 1 above)
Comment (jmartinez-silabs) [reply src/platform/EFR32/EFR32Config.cpp]: done

**Review by jmeg-sfy — APPROVED** [review]

**Review by jepenven-silabs — APPROVED** [review]

**Review by rcasallas-silabs — APPROVED** [review]
