### PR TITLE
Fix liveness timer not firing for subscriptions

### LINKED ISSUE #21546: Subscriptions are not terminated on the client when the maxInterval expires
#### Problem
This got broken by #20080.

In `RefreshLivenessCheckTimer` we used to do:
```
System::Clock::Timeout timeout = System::Clock::Seconds16(mMaxInterval) + mExchange->GetSessionHandle()->GetAckTimeout();
```
but this got changed to:
```
        VerifyOrReturnError(mReadPrepareParams.mSessionHolder, CHIP_ERROR_INCORRECT_STATE);
        timeout = System::Clock::Seconds16(mMaxInterval) + mReadPrepareParams.mSessionHolder->GetAckTimeout();
```
When not doing resubscription, `mReadPrepareParams` doesn't contain anything, so that `VerifyOrReturnError` always fails.  But nothing ever checks the return value of `RefreshLivenessCheckTimer`, so we proceed with things.  The timer is not scheduled, and if we never hear back from the other side we don't treat that as a subscription failure.

 #### Proposed Solution
1. Add tests that would have caught this problem.  It's fairly surprising that we don't have any.
2. Figure out whether callers should be checking the return value of `RefreshLivenessCheckTimer`.  If not, it should return void.
3. Decide whether lack of a session here should lead to an immediate `Close` call, just like failure to schedule a timer does.
4. Figure out where the session should be coming from here:
    * Possibly we should go back to using the exchange (since all the _non-test_ calls to this function do in fact have an exchange), and if we need `OverrideLivenessTimeout` to work we can fall back to the read prepare params if there is no exchange.
    * As above, but change `OverrideLivenessTimeout` to just take a session as argument.
    * Another option would be to always store the session in `mReadPrepareParams`, even when we're not doing auto-resubscription.  But then we'd also want to update it any time we get a message, because the incoming message _may not be on the session we sent the original subscribe on_.  In fact, that session could be long-gone even as we're getting messages from the server on a different session, so getting a session from `mReadPrepareParams` is just not at all reliable.

@mrjerryjohns @yunhanw-google

### PR DESCRIPTION
**Pull request by mrjerryjohns**
Fixes #21546 

On subscriptions created with `ReadClient::SendRequest`,`ReadClient::RefreshLivenessCheckTimer` was erroring out due to the incorrect assumption that `mReadPrepareParams.mSessionHolder` would be
tracking a valid session, which it isn't in the re-sub disabled case.

Fixes:
- Have `mReadPrepareParams.mSessionHolder` always track the latest valid  session in all subscription related cases.
- Fix `RefreshLivenessCheckTimer` to be the type of function that just returns an error and let callers deal with calling `Close()`. Fix up callers to handle the error returned appropriately.
- Update the `MessagingContext` helper to use a much lower idle/active retrans timeout values for the test sessions to facilitate faster tests. This should provide benefits across the board (e.g `TestWriteChunking` drops for 19s to 5s!). By doing altering it at this level, various tests that accelerated failure discovery by altering the liveness timeouts can go to a more representative model of failure injection by doing stuff like dropping packets (like a real network would) to simulate certain classes of failures instead, while still ensuring the tests run reasonably fast in CI.

Tests:
- Added a new `TestSubscribeAttributeTimeout` test that checks for subscriptions timing out due to a liveness failure. Ensured that it failed prior to the change, and passes after.

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]

File: src/app/tests/TestReadInteraction.cpp [hunk 1]
```diff
@@ -2738,20 +2742,15 @@ void TestReadInteraction::TestReadClientReceiveInvalidMessage(nlTestSuite * apSu
...
         ctx.GetLoopback().mNumMessagesToAllowBeforeDropping = 0;
         ctx.GetLoopback().mDroppedMessageCount              = 0;
         readClient.OnMessageReceived(readClient.mExchange.Get(), payloadHeader, std::move(msgBuf));
         ctx.DrainAndServiceIO();
 
-        // TODO: Need to validate what status is being sent to the ReadHandler
-        // The ReadHandler closed its exchange when it sent the Report Data (which we dropped).
-        // Since we synthesized the StatusResponse to the ReadClient, instead of sending it from the ReadHandler,
-        // the only messages here are the ReadClient's StatusResponse to the unexpected message and an MRP ack.
-        NL_TEST_ASSERT(apSuite, ctx.GetLoopback().mSentMessageCount == 2);
```
Comment (bzbarsky-apple) [inline src/app/tests/TestReadInteraction.cpp:2754]: This change is not OK.  After this change, this test no longer checks for the thing it's supposed to be checking for (that the ReadClient sends a Status Response) at all...

Similar for a lot of these other changes.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]
Er, I meant to request changes...

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@mrjerryjohns can you rebase this?
