### PR TITLE
[ReportScheduler] Fixed chunked reporting for Synchronized Report Scheduler

### LINKED ISSUE #30518: [BUG] Subscription resumption at reboot hangs when Subscription Synchronization is enabled
### Reproduction steps

1. Commission a device with subscription sync and persistant subscription enabled
2. Run the chip-tool in interactive mode (Version must include https://github.com/project-chip/connectedhomeip/pull/30457)
3. Establish a subscription to the end device `any subscribe-by-id 0xFFFFFFFF 0xFFFFFFFF 0 60 <node-id> 0xFFFF`
4. Power cycle the end device

When the end device power cycles, it will try to restablish the subscription but will hang after the first report is full. This only happens when chucking is required. If the chip-tool subscribe to a single attribute, re-establishement succeeds. 

### Bug prevalence

Every power cycle with a big subscription

### GitHub hash of the SDK that was being used

bb2d05e6b3

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by lpbeliveau-silabs**
Fix bug where chunked report would not be properly handled by synchronised report scheduler and added a version of TestReadInteraction unit test that would perform all the read interaction tests while using the synchronized report scheduler. 

The Report Synchronisation logic has also been changed so it gets rescheduled if a timer somehow fired too early for its handler's min interval.

Fixes: https://github.com/project-chip/connectedhomeip/issues/30518

### CODE REVIEW

File: src/app/reporting/SynchronizedReportSchedulerImpl.cpp [hunk 1]
```diff
@@ -180,25 +180,49 @@ CHIP_ERROR SynchronizedReportSchedulerImpl::CalculateNextReportTimeout(Timeout &
...
+    mNodesPool.ForEachActiveObject([now, &firedEarly](ReadHandlerNode * node) {
         if (node->GetMinTimestamp() <= now)
         {
             node->SetCanBeSynced(true);
         }
 
         if (node->IsReportableNow(now))
         {
+            // We assume we fired the timer early if no handler is reportable at the moment
+            firedEarly = false;
```
Comment (mkardous-silabs) [inline src/app/reporting/SynchronizedReportSchedulerImpl.cpp:195]: Odd comment since firedEarly = false?

**Review by mkardous-silabs — APPROVED** [review]

File: src/app/reporting/SynchronizedReportSchedulerImpl.cpp [hunk 2]
```diff
@@ -180,25 +180,49 @@ CHIP_ERROR SynchronizedReportSchedulerImpl::CalculateNextReportTimeout(Timeout &
...
+        ReadHandlerNode * firstNode = nullptr;
+
+        // If we fired the timer early, we need to restart the timer
+        mNodesPool.ForEachActiveObject([&firstNode](ReadHandlerNode * node) {
+            firstNode = node;
+            return Loop::Break;
+        });
+
+        bool firstNodeFound = (nullptr != firstNode);
+        VerifyOrReturn(firstNodeFound);
```
Comment (jmartinez-silabs) [inline src/app/reporting/SynchronizedReportSchedulerImpl.cpp:216]:
```suggestion
        VerifyOrReturn(firstNode); // Verify we have a valid node
```

File: src/app/reporting/SynchronizedReportSchedulerImpl.cpp (hunk 1 above)
Comment (lpbeliveau-silabs) [reply src/app/reporting/SynchronizedReportSchedulerImpl.cpp]: Clarified commend.

File: src/app/reporting/SynchronizedReportSchedulerImpl.cpp [hunk 3]
```diff
@@ -180,25 +180,49 @@ CHIP_ERROR SynchronizedReportSchedulerImpl::CalculateNextReportTimeout(Timeout &
...
+        // If we fired the timer early, we need to restart the timer
+        mNodesPool.ForEachActiveObject([&firstNode](ReadHandlerNode * node) {
+            firstNode = node;
+            return Loop::Break;
+        });
+
+        VerifyOrReturn(firstNode); // Verify we have a valid node
+
+        Timeout timeout = Milliseconds32(0);
+        ReturnOnFailure(CalculateNextReportTimeout(timeout, firstNode, now));
```
Comment (andy31415) [inline src/app/reporting/SynchronizedReportSchedulerImpl.cpp:219]: Could you add a comment of why the first node in the list is the correct/sufficient node to base time calculations on?

Reading the code without having too much background, I am wondering why calculateNextReportTimeout is based on the first node instead of being some "min" of all nodes.


Looking through the code, it seems the node is only used for ` VerifyOrReturnError(nullptr != FindReadHandlerNode(aNode->GetReadHandler()), CHIP_ERROR_INVALID_ARGUMENT)` ... which I do not understand. Why do we check for a read handler if aNode is not used at all after that?

Comment (andy31415) [reply src/app/reporting/SynchronizedReportSchedulerImpl.cpp:219]: Looking at this: could you add comments specifically for what arguments in `ScheduleReport` actually do and mean? at least usage of `node` is unclear ot me

Comment (lpbeliveau-silabs) [reply src/app/reporting/SynchronizedReportSchedulerImpl.cpp:219]: The reason is that CalculateNextReportTimeout will iterate through all active nodes so it doesn't matter which one is passed, as long as it is a node for an existing readHandler.

The reason we do this check is that if for a reason the readHandler of a node just got freed and we start looping through all nodes, at some point IsReadHandlerReportable(node->GetReadHandler()) will be called, which yields:
IsReadHandlerReportable(null), null->ShouldStartReporting() -> crash. 

Now that being said, it is probably better to do null checks in all ReadHandler dependant functions of the Scheduler so I will do that instead.

Comment (lpbeliveau-silabs) [reply src/app/reporting/SynchronizedReportSchedulerImpl.cpp]: Updated, no more using the first node nor checking an unused variable.

**Review by woody-apple — APPROVED** [review]
