### PR TITLE
[Camera] Call RemoveSession method from Matter context

### LINKED ISSUE #41538: [BUG] Camera app crash on webrtc session end
### Reproduction steps

- Establish a webrtc connection in normal flow:
  - Client/Controller -> Server/Device: SDP offer
  - Client <- Server: SDP answer
  - Client <-> Server: ICE exchange
- End the webrtc connection:
  - Client -> Server: End

```
[1760975189.896] [3371847:3372183] [CAM] [PeerConnection State: Closed]
[1760975189.896] [3371847:3372183] [CAM] Connection state changed for sessionID: 0
[1760975189.896] [3371847:3372183] [CAM] Connection state changed for session 0: disconnected
[1760975189.896] [3371847:3372183] [CAM] Peer connection closed for session 0, cleaning up resources
[1760975189.896] [3371847:3372183] [CAM] UnregisterWebrtcTransport called for sessionId: 0
[1760975189.896] [3371847:3372183] [CAM] Deregistering transport from buffer 0x7723c80053d0
[1760975189.896] [3371847:3372183] [CAM] Sink deregistered for transport.
[1760975189.896] [3371847:3372183] [CAM] Successfully unregistered transport for sessionId: 0
[1760975189.896] [3371847:3372183] [DL] Chip stack locking error at 'src/app/reporting/reporting.cpp:32'. Code is unsafe/racy
[1760975189.896] [3371847:3372183] [-] chipDie chipDie chipDie
```

### Bug prevalence

Consistent

### GitHub hash of the SDK that was being used

76c9ca20daa1f95f10285e8feb8c8468936ff7b3

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

Full device side logs: [device.log](https://github.com/user-attachments/files/23004514/device.log)

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Summary

The crash is happening because MatterReportingAttributeChangeCallback is being called from a WebRTC worker thread (the libdatachannel "RTC worker" thread) without holding the Matter stack lock. This violates Matter's threading requirements.

Looking at the stack trace:

WebRTC connection closes on an RTC worker thread

1. Callback chain leads to WebRTCProviderManager::OnConnectionStateChanged
2. Which calls RemoveSession
3. Which calls MatterReportingAttributeChangeCallback without the Matter lock

The RemoveSession method needs to ensure it's called on the Matter thread with the stack lock held. 

#### Related issues

Fixes: #41538

#### Testing

Establish a webrtc connection in normal flow:

- Client/Controller -> Server/Device: SDP offer
- Client <- Server: SDP answer
- Client <-> Server: ICE exchange

End the webrtc connection:

- Client -> Server: End

#### Readability checklist

The checklist below will help the reviewer finish PR review in time and keep the
code readable:

-   [ ] PR title is
        [descriptive](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html#title-formatting)
-   [ ] Apply the
        [_“When in Rome…”_](https://project-chip.github.io/connectedhomeip-doc/style/CODING_STYLE_GUIDE.html)
        rule (coding style)
-   [ ] PR size is short
-   [ ] Try to avoid "squashing" and "force-update" in commit history
-   [ ] CI time didn't increase

See: [Pull Request Guidelines](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html)

### CODE REVIEW

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp [hunk 1]
```diff
@@ -887,42 +887,45 @@ void WebRTCProviderManager::OnConnectionStateChanged(bool connected, const uint1
...
-        {
-
-            ChipLogProgress(Camera,
-                            "Transport not found for session %u during disconnect; session may have already been cleaned up",
-                            sessionId);
-            return;
-        }
+        // Schedule cleanup on Matter thread to ensure proper locking when calling RemoveSession
+        DeviceLayer::SystemLayer().ScheduleLambda([this, sessionId]() {
+            WebrtcTransport * transport = GetTransport(sessionId);
```
Comment (bzbarsky-apple) [inline examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp:894]: What guarantees that `this` has not been destroyed at this point?

**Review by bzbarsky-apple — COMMENTED** [review]
Thank you for adding the cluster asserts!

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp (hunk 1 above)
Comment (yufengwangca) [reply examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp:894]: WebRTCProviderManager is a member variable of CameraDevice
CameraDevice itself is a global variable
This means it has static storage duration - it lives for the entire lifetime of the program

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp [hunk 2]
```diff
@@ -887,42 +887,45 @@ void WebRTCProviderManager::OnConnectionStateChanged(bool connected, const uint1
...
-        // Remove from current sessions list in the WebRTC Transport Provider
-        if (mWebRTCTransportProvider != nullptr)
-        {
-            mWebRTCTransportProvider->RemoveSession(sessionId);
-        }
+            // Remove from current sessions list in the WebRTC Transport Provider
+            // This MUST be called on the Matter thread with the stack lock held
+            if (mWebRTCTransportProvider != nullptr)
+            {
+                mWebRTCTransportProvider->RemoveSession(sessionId);
```
Comment (pidarped) [inline examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp:923]: RemoveSession() is the one that needs to run on the Matter thread, right? Are we bundling the entire clean-up logic in the lambda to keep the execution together(which also may not be guaranteed to happen)?

Comment (yufengwangca) [reply examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp:923]: I am also debating if only offload mWebRTCTransportProvider->RemoveSession(sessionId); to Matter thread

If we do that, then the whole cleanup is not automatic, the app first clean up, then the server do the cleanup, will there be any race condition?

Comment (marktrayer) [reply examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp:923]: Before I saw the PR I was assuming that it would just scheduleLamda for the RemoveSession.  But it may be cleaner treating the whole cleanup as atomic, and we're also calling down into the SDK in ReleaseAudioVideoStreams, which is safe for now, but may not be depending on how that code evolves.

Comment (pidarped) [reply examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp:923]: Yes. It seems it is best to keep all of it in the lambda. Although, that in itself does not guarantee atomicity.

**Review by pidarped — APPROVED** [review]

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp:894]: That's worth a comment.

Comment (yufengwangca) [reply examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp:894]: acked

**Review by bzbarsky-apple — APPROVED** [review]

**Review by marktrayer — APPROVED** [review]
