### PR TITLE
Final PacketBufferHandle cleanup.

### LINKED ISSUE #2707: Figure out a way to express PacketBuffer ownership in the type system
#### Problem
If a function takes a `PacketBuffer *`, it's not obvious from the function signature whether it's expected to free the buffer or not.  We can document the semantics, but that still leaves a lot of room for error, and for the function failing to actually implement the semantics properly.

 #### Proposed Solution
Express "this function will free the buffer" in the type system.   It seems to me that we want to be able to express the following concepts:

1. A function is handed "ownership" of a `PacketBuffer` and is expected to free it.
2. We are now handing "ownership" of our `PacketBuffer` to someone else and should not reference it anymore.
3. We are now incrementing the refcount on a `PacketBuffer`, after which we will hand over one of the references to someone else and be responsible for releasing the other ourselves.

We could perhaps use `std::shared_ptr` for this, with `std::move` at the ownership transfers.  Functions expecting ownership would take `shared_ptr<PacketBuffer>&&`.  It's not completely ideal because nothing prevents use of a "moved out of" `shared_ptr` from being accessed, but at least it would be a null deref, not a UAF.

We could also just pass something like `shared_ptr` by value, if we think our refcounting is cheap enough.

Ideally, of course, we would have some sort of clonable `PacketBuffer` handle so we can model the increment explicitly as a clone and we'd have lifetimes a la Rust so when you hand the handle to someone the compiler won't let you touch it again.  Sadly, I don't see a way to do that in C++; you can always mess with something like a `unique_ptr` you called `release` on... 

@sagar-apple @pan-apple @andy31415 @gerickson @turon @rwalker-apple any thoughts or suggestions?

### PR DESCRIPTION
**Pull request by kpschoedel**
#### Problem

Code should use `PacketBufferHandle` rather than `PacketBuffer *`.
A few references and transitional interfaces remain.

#### Summary of Changes

- Promote `Release_ForNow()` to `UnsafeRelease()`. It's impractical
  to remove entirely since it's used conjunction with platform event
  queues.
- Replace `GetLwIPpbuf()` with `LwIPPacketBufferView::UnsafeGetLwIPpbuf()`,
  restricted to specific friend classes.
- Privatize `AddRef()` and raw `SetDataLength()`.
- Remove `AddToEnd_ForNow()`.
- Remove various `using PacketBuffer` declarations.
- Remove obsolete comments about `PacketBuffer *` ownership, and
  rephrase comments mentioning the `PacketBuffer` class by name.

Fixes #2707 - Figure out a way to express PacketBuffer ownership in the type system

### CODE REVIEW

File: src/system/SystemPacketBuffer.h [hunk 1]
```diff
@@ -592,9 +575,25 @@ class DLL_EXPORT PacketBufferHandle
...
+    /**
+     * Export a raw PacketBuffer pointer.
+     *
+     * @brief The PacketBufferHandle's ownership is transferred to the caller.
+     *
+     * @note This should only be used in low-level code, e.g. to export buffers from LwIP or a similar stack.
+     *       The ref-qualifier `&&` requires the caller to use `std::move` to emphasize that ownership is
+     *       moved out of this handle.
+     */
+    CHECK_RETURN_VALUE PacketBuffer * UnsafeRelease() &&
```
Comment (kpschoedel) [inline src/system/SystemPacketBuffer.h:590]: This is currently only used to reference a PacketBuffer in events. In the case of `CHIPoBLEWriteReceived` it's as a `PacketBuffer*`, but in `ChipSystemLayerEvent` it's as a `uintptr_t`. An option would be to only Release as an opaque `uintptr_t` to discourage any use of packet buffers through a `PacketBuffer*`; it might then also be possible to make `PacketBuffer` itself a private type inside `PacketBufferHandle`.

File: src/system/SystemPacketBuffer.h [hunk 2]
```diff
@@ -592,9 +575,25 @@ class DLL_EXPORT PacketBufferHandle
      *
      * @note This should be used ONLY by low-level code interfacing with LwIP.
      */
-    struct pbuf * GetLwIPpbuf() { return static_cast<struct pbuf *>(mBuffer); }
+    struct pbuf * UnsafeGetLwIPpbuf() { return static_cast<struct pbuf *>(mBuffer); }
```
Comment (rwalker-apple) [inline src/system/SystemPacketBuffer.h:578]: can we protect this method and make a list of friend classes allowed to call it?  is that worth the work?

**Review by rwalker-apple — APPROVED** [review]
nice work

File: src/system/SystemPacketBuffer.h (hunk 2 above)
Comment (kpschoedel) [reply src/system/SystemPacketBuffer.h:578]: Yes, the only uses are in Inet:…EndPoint, so that shouldn't be difficult. (The same isn't true of UnsafeRelease(), unfortunately, since it's mostly used under src/platform/, so hiding it would be a problem for out-of-tree platforms.)

Comment (kpschoedel) [reply src/system/SystemPacketBuffer.h]: Done with a task-specific subclass to set a pattern for disjoint exposures. No increase in code size.

**Comment by kpschoedel** [comment]
Looks like some new raw `PacketBuffer` just got committed :-(

File: src/inet/RawEndPoint.cpp [hunk 3]
```diff
@@ -624,20 +622,20 @@ INET_ERROR RawEndPoint::SendMsg(const IPPacketInfo * pktInfo, chip::System::Pack
...
 
-        lwipErr = raw_sendto(mRaw, msg.GetLwIPpbuf(), &ipAddr);
+        lwipErr = raw_sendto(mRaw, System::LwIPPacketBufferView::UnsafeGetLwIPpbuf(msg), &ipAddr);
 #else // LWIP_VERSION_MAJOR <= 1 && LWIP_VERSION_MINOR < 5
         if (PCB_ISIPV6(mRaw))
         {
             ip6_addr_t ipv6Addr = addr.ToIPv6();
 
-            lwipErr = raw_sendto_ip6(mRaw, msg.GetLwIPpbuf(), &ipv6Addr);
+            lwipErr = raw_sendto_ip6(mRaw, msg.UnsafeGetLwIPpbuf(), &ipv6Addr);
```
Comment (bzbarsky-apple) [inline src/inet/RawEndPoint.cpp:631]: Needs to use `LwIPPacketBufferView`

File: src/inet/RawEndPoint.cpp [hunk 4]
```diff
@@ -624,20 +622,20 @@ INET_ERROR RawEndPoint::SendMsg(const IPPacketInfo * pktInfo, chip::System::Pack
...
         }
 #if INET_CONFIG_ENABLE_IPV4
         else
         {
             ip4_addr_t ipv4Addr = addr.ToIPv4();
 
-            lwipErr = raw_sendto(mRaw, msg.GetLwIPpbuf(), &ipv4Addr);
+            lwipErr = raw_sendto(mRaw, msg.UnsafeGetLwIPpbuf(), &ipv4Addr);
```
Comment (bzbarsky-apple) [inline src/inet/RawEndPoint.cpp:638]: Needs to use `LwIPPacketBufferView`

File: src/inet/UDPEndPoint.cpp [hunk 5]
```diff
@@ -600,9 +598,9 @@ INET_ERROR UDPEndPoint::SendMsg(const IPPacketInfo * pktInfo, System::PacketBuff
             }
 
             if (intfId != INET_NULL_INTERFACEID)
-                lwipErr = udp_sendto_if_ip6(mUDP, msg.GetLwIPpbuf(), &lwipDestAddr, destPort, intfId);
+                lwipErr = udp_sendto_if_ip6(mUDP, msg.UnsafeGetLwIPpbuf(), &lwipDestAddr, destPort, intfId);
```
Comment (bzbarsky-apple) [inline src/inet/UDPEndPoint.cpp:601]: Needs to use `LwIPPacketBufferView`

File: src/inet/UDPEndPoint.cpp [hunk 6]
```diff
@@ -600,9 +598,9 @@ INET_ERROR UDPEndPoint::SendMsg(const IPPacketInfo * pktInfo, System::PacketBuff
...
             else
-                lwipErr = udp_sendto_ip6(mUDP, msg.GetLwIPpbuf(), &lwipDestAddr, destPort);
+                lwipErr = udp_sendto_ip6(mUDP, msg.UnsafeGetLwIPpbuf(), &lwipDestAddr, destPort);
```
Comment (bzbarsky-apple) [inline src/inet/UDPEndPoint.cpp:603]: Needs to use `LwIPPacketBufferView`

File: src/inet/UDPEndPoint.cpp [hunk 7]
```diff
@@ -619,9 +617,9 @@ INET_ERROR UDPEndPoint::SendMsg(const IPPacketInfo * pktInfo, System::PacketBuff
             }
 
             if (intfId != INET_NULL_INTERFACEID)
-                lwipErr = udp_sendto_if(mUDP, msg.GetLwIPpbuf(), &lwipDestAddr, destPort, intfId);
+                lwipErr = udp_sendto_if(mUDP, msg.UnsafeGetLwIPpbuf(), &lwipDestAddr, destPort, intfId);
```
Comment (bzbarsky-apple) [inline src/inet/UDPEndPoint.cpp:620]: Needs to use `LwIPPacketBufferView`

File: src/inet/UDPEndPoint.cpp [hunk 8]
```diff
@@ -619,9 +617,9 @@ INET_ERROR UDPEndPoint::SendMsg(const IPPacketInfo * pktInfo, System::PacketBuff
...
             else
-                lwipErr = udp_sendto(mUDP, msg.GetLwIPpbuf(), &lwipDestAddr, destPort);
+                lwipErr = udp_sendto(mUDP, msg.UnsafeGetLwIPpbuf(), &lwipDestAddr, destPort);
```
Comment (bzbarsky-apple) [inline src/inet/UDPEndPoint.cpp:622]: Needs to use `LwIPPacketBufferView`

**Review by bzbarsky-apple — APPROVED** [review]
Nicely done!

File: src/inet/UDPEndPoint.cpp (hunk 8 above)
Comment (kpschoedel) [reply src/inet/UDPEndPoint.cpp]: Done and thanks for catching that. Looks like I rushed that change and stopped when the active builds worked.

**Comment by kpschoedel** [comment]
@andy31415 @saurabhst @BroderickCarlin @hawk248 @jelderton ? Need a couple more partner reviews.

**Review by mspang — APPROVED** [review]

**Review by jelderton — APPROVED** [review]
