### PR TITLE
Typo/Comments Cleanup for  IM writeClient and writeHandler

### LINKED ISSUE #7795: Review comments for WriteClient/Handler PR
#### Problem
Various issues in #7730 that were not caught in review:
* [x] Docs for `InteractionModelDelegate::WriteResponsStatus` have "an Write Response" instead of "a Write Response"
* [x] `aCommandIndex` argument name for `InteractionModelDelegate::WriteResponseStatus` makes no sense.
* [x] `aCommandIndex` argument for `InteractionModelDelegate::WriteResponseStatus` is not documented; I have no idea what I'd do with it as an API consumer.
* [x] Documentation for `InteractionModelDelegate::WriteResponseProcessed` says "already" which sounds like "it's been done once, so there's nothing we need to do", and I am pretty sure that is not the intent of this callback.
* [x] Documentation for `InteractionModelDelegate::WriteResponseProtocolError` has "an Write Response"
* [x] Documetation for `InteractionModelDelegate::WriteResponseError` talks about `aCWRiteClient`, whatever that is.
* [ ]  InteractionModelEngine::OnWriteRequest aborts exchange contexts if a handler cannot be found. An abort will fail to send an MRP ack; this does not seem like the right behavior.  Tracked in #7968
* [x] Documentation for `InteractionModelEngine::NewWriteClient` says "use to send do a write".  "send", or "do", not both, please.
* [x] Documentation for `InteractionModelEngine::NewWriteClient` says consumer is responsible for calling `Shutdown`, but `WriteClient::OnMessageReceived` shuts itself down.  This seems like copy/paste from `ReadClient`, which does _NOT_ call `Shutdown` itself, ever.
* [x] Documentation for `InteractionModelEngine::NewWriteClient` says `CHIP_ERROR_INCORRECT_STATE` is returned when no write client is available, but the implementation returns `CHIP_ERROR_NO_MEMORY`.
* [x] Comments inside `WriteClient::ClearExistingExchangeContext` talk about "one Echo exchange", which makes no sense.
* [ ] There are `Abort`s of exchange contexts in various places in the PR. There probably should not be any at all. I suspect that little to no testing was done of how all these Aborts interact with the intended MRP semantics in various error conditions, and am quite sure they interact badly.  Tracked in #7969
* [x] In `WriteClient::SendWriteRequest` there's a "TODO: temprary create ..." comment which is clearly copy/pasted from somewhere, complete with multiple grammar issues.
* [x] `WriteClient::SendWriteRequest` sets `kNoAutoRequestAck`  for some reason.  It should not be doing that. (Fixed in #7991)
* [ ] The test in `TestWriteInteraction` calls private `ProcessWriteResponseMessage` instead of calling the public `OnMessageReceived` API.  As a result we are not properly testing the lifetime handling.
* [ ] WriteClient::ProcessAttributeStatusElement reads node ids from the attribute path TLV. This doesn't make sense to me: For a WriteResponse message the node for all paths should be clear from the packet headers and should not be present in the TLV at all. If it is thus present in the spec, that's a bug in the spec that should be filed and we should implement the sane thing.  Tracked in #7971
* [ ] WriteHandler::ProcessAttributeDataList likewise reads node ids from the TLV. This does not make sense: writes are always targeted at the message recipient node (and the node id may not even be known, if the write is issued to a group).  Tracked in #7972
* [x] Why is `WriteClient::FinalizeMessage` public API?  It shouldn't be; it's an internal helper method.
* [x] The API contract for `WriteClient` is not documented.  Is the intent that you call allocate one, then call `PrepareAttribute` followed by `FinishAttribute` for every attribute you want to read (why the separate `FinishAttribute`; that's not documented), then call `SendWriteRequest`?  Or something else?  Needs to be documented clearly.
* [ ] I assume the lack of group/wildcard writes is intentional for now. That's fine, but there should be a TODO comment indicating that it still needs to happen, no?  Tracked in #7973
* [ ] There's a WriteClient::GetAttributeDataElementTLVWriter API that is not very user-friendly. We should have a followup to figure out how to do this better, at least in common cases. We might need to fall back to exposing a TLVWriter for very complicated write requests, but a typical consumer writing something simple should not have to deal with a TLVWriter at all.  Tracked in #7974
* [x] `WriteHandler::OnWriteRequest` API documentation talks about shutdown being called "including if OnWriteHandler returns an error."  What is "OnWriteHandler" here?  Does it mean "OnWriteRequest"?
* [ ] Why is `WriteHandler::SendWriteResponse` (the one-arg version) public API?  If it needs to be public, why is it not documented?
* [x] Our general convention now seems to be to pass packetbuffers by rvalue reference, but a lot of this new code is passing them by value.  Is that intentional?

 #### Proposed Solution
Address the above issues.

@yunhanw-google @andy31415 @woody-apple

### PR DESCRIPTION
**Pull request by yunhanw-google**
#### Problem
* Fix https://github.com/project-chip/connectedhomeip/issues/7795

#### Change overview
Cleanup Typo and imrpove comments for IM write client and write Handler

#### Testing
The existing test cover this.

### CODE REVIEW

File: src/app/WriteClient.cpp [hunk 1]
```diff
@@ -270,7 +270,7 @@ CHIP_ERROR WriteClient::SendWriteRequest(NodeId aNodeId, Transport::AdminId aAdm
 
     err = mpExchangeCtx->SendMessage(
         Protocols::InteractionModel::MsgType::WriteRequest, std::move(packet),
-        Messaging::SendFlags(Messaging::SendMessageFlags::kExpectResponse).Set(Messaging::SendMessageFlags::kNoAutoRequestAck));
+        Messaging::SendFlags(Messaging::SendMessageFlags::kExpectResponse));
```
Comment (woody-apple) [inline src/app/WriteClient.cpp:273]: This doesn't appear to be a typo? What bug is fixed here, what new test was added or modified to confirm this behavior?

**Review by woody-apple — DISMISSED** [review]

File: src/app/WriteClient.cpp [hunk 2]
```diff
@@ -255,7 +255,7 @@ CHIP_ERROR WriteClient::SendWriteRequest(NodeId aNodeId, Transport::AdminId aAdm
     ClearExistingExchangeContext();
 
     // Create a new exchange context.
-    // TODO: temprary create a SecureSessionHandle from node id, will be fix in PR 3602
+    // TODO: we temprarily create a SecureSessionHandle from node id, this will be fixed in PR 3602
```
Comment (woody-apple) [inline src/app/WriteClient.cpp:258]: Typo here

File: src/app/WriteHandler.cpp [hunk 3]
```diff
@@ -63,7 +63,7 @@ void WriteHandler::ClearExistingExchangeContext()
     }
 }
 
-CHIP_ERROR WriteHandler::OnWriteRequest(Messaging::ExchangeContext * apExchangeContext, System::PacketBufferHandle aPayload)
+CHIP_ERROR WriteHandler::OnWriteRequest(Messaging::ExchangeContext * apExchangeContext, System::PacketBufferHandle && aPayload)
```
Comment (woody-apple) [inline src/app/WriteHandler.cpp:66]: This appears to be not a typo fix, but a logic change?

File: src/app/WriteHandler.h [hunk 4]
```diff
@@ -69,9 +69,7 @@ class WriteHandler
      *  @retval #Others If fails to process read request
      *  @retval #CHIP_NO_ERROR On success.
      */
-    CHIP_ERROR OnWriteRequest(Messaging::ExchangeContext * apExchangeContext, System::PacketBufferHandle aPayload);
-
-    CHIP_ERROR SendWriteResponse(System::PacketBufferHandle aPayload);
+    CHIP_ERROR OnWriteRequest(Messaging::ExchangeContext * apExchangeContext, System::PacketBufferHandle && aPayload);
```
Comment (woody-apple) [inline src/app/WriteHandler.h:72]: Appears to be a logic change in here?

Comment (yunhanw-google) [reply src/app/WriteHandler.h:72]: Our general convention now seems to be to pass packetbuffers by rvalue reference, I intend to use rvalue, but i make a typo here which use copy constructor, functionality is same, copy constructor make additional memory copy. Here I correct it to use rvalue referance.

File: src/app/WriteHandler.cpp (hunk 3 above)
Comment (yunhanw-google) [reply src/app/WriteHandler.cpp:66]: Our general convention now seems to be to pass packetbuffers by rvalue reference, I intend to use rvalue, but i make a typo here which use copy constructor, functionality is same, copy constructor make additional memory copy. Here I correct it to use rvalue reference.

File: src/app/WriteClient.cpp (hunk 1 above)
Comment (yunhanw-google) [reply src/app/WriteClient.cpp:273]: This is MRP kNoAutoRequestAck flag, basically it means disable MRP here, we previously disable MRP in Command/Read for stability reason, I think song and Boris re-enable MRP for Command/Read, it doesn't impact the happy test behavior. I intend to enable MRP for write, but somehow I forget to remove this kNoAutoRequestAck.
This is similar to what we have done for Command/Read, I have validated it manually and locally to check if MRP is enabled.

File: src/app/WriteClient.cpp (hunk 2 above)
Comment (yunhanw-google) [reply src/app/WriteClient.cpp]: Done, thanks

File: src/app/WriteClient.cpp (hunk 1 above)
Comment (yunhanw-google) [reply src/app/WriteClient.cpp]: this has been handled by https://github.com/project-chip/connectedhomeip/pull/7991, removed this from this pr

File: src/app/WriteClient.h [hunk 5]
```diff
@@ -39,6 +39,8 @@ namespace app {
 /**
  *  @brief The read client represents the initiator side of a Write Interaction, and is responsible
  *  for generating one Write Request for a particular set of attributes, and handling the Write response.
+ *  Consumer can allocate one write client, then call PrepareAttribute followed by FinishAttribute for every attribute
+ *  it want to insert in write request, then call SendWriteRequest
```
Comment (bzbarsky-apple) [inline src/app/WriteClient.h:43]:
```suggestion
 *  it wants to insert in write request, then call SendWriteRequest
```

But actually, the consumer will need to insert the values too, no?

File: src/app/WriteClient.h [hunk 6]
```diff
@@ -51,15 +53,11 @@ class WriteClient : public Messaging::ExchangeDelegate
...
-    /**
-     *  Send a Write Request.  There can be one Write Request outstanding on a given WriteClient.
-     *  If SendWriteRequest returns success, no more Write Requests can be sent on this WriteClient
-     *  until the corresponding InteractionModelDelegate::WriteResponseProcessed or InteractionModelDelegate::WriteResponseError
-     *  call happens with guarantee.
+     *  Once SendWriteRequest returns successfully, the WriteClient will
+     *  handle calling Shutdown on itself once it decides it's done with waiting
+     *  for a response (i.e. times out or gets a response).
+     *  If SendWriteRequest is never called, or the call fails, the API
+     *  consumer is responsible for calling Shutdown on the CommandSender.
```
Comment (bzbarsky-apple) [inline src/app/WriteClient.h:60]:
```suggestion
     *  consumer is responsible for calling Shutdown on the WriteClient.
```

File: src/app/WriteHandler.h [hunk 7]
```diff
@@ -69,9 +69,7 @@ class WriteHandler
      *  @retval #Others If fails to process read request
      *  @retval #CHIP_NO_ERROR On success.
      */
-    CHIP_ERROR OnWriteRequest(Messaging::ExchangeContext * apExchangeContext, System::PacketBufferHandle aPayload);
-
-    CHIP_ERROR SendWriteResponse(System::PacketBufferHandle aPayload);
```
Comment (bzbarsky-apple) [inline src/app/WriteHandler.h:74]: This is removed from the header, but it's still being used in various places and it's still implemented.  What is going on here?

Comment (yunhanw-google) [reply src/app/WriteHandler.h:74]: we are using CHIP_ERROR WriteHandler::SendWriteResponse() instead of SendWriteResponse(System::PacketBufferHandle aPayload);

**Review by bzbarsky-apple — APPROVED** [review]
Approved with the two comment fixes.

File: src/app/WriteClient.h (hunk 5 above)
Comment (yunhanw-google) [reply src/app/WriteClient.h]: Done, update with comments, yes, insert the value in write request.

File: src/app/WriteClient.h (hunk 6 above)
Comment (yunhanw-google) [reply src/app/WriteClient.h]: Done, thanks

**Review by jmartinez-silabs — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Review by chrisdecenzo — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]
