### PR TITLE
Reset the wrong code retry attempts if a valid credential is presented

### LINKED ISSUE #23782: Door lock WrongCodeEntryLimit should have the counter reset on correct PIN entry
See https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/5735

### PR DESCRIPTION
**Pull request by nivi-apple**
- Provide a ResetWrongCodeEntryAttempts for apps to use to reset the wrong entry attempts

- Update DL_LockUnlock.yaml to test resetting the wrong code retry attempts

Fixes #23782

### CODE REVIEW

File: src/app/clusters/door-lock-server/door-lock-server.h [hunk 1]
```diff
@@ -180,6 +180,17 @@ class DoorLockServer
         return GetFeatures(endpointId).Has(DoorLockFeature::kUser) && SupportsAnyCredential(endpointId);
     }
 
+    inline void ResetWrongCodeEntryAttempts(chip::EndpointId endpointId)
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.h:183]: Needs documentation.  And why is the implementation inline?

File: src/app/clusters/door-lock-server/door-lock-server.h [hunk 2]
```diff
@@ -121,7 +121,7 @@ class DoorLockServer
     bool SetOneTouchLocking(chip::EndpointId endpointId, bool isEnabled);
     bool SetPrivacyModeButton(chip::EndpointId endpointId, bool isEnabled);
 
-    bool TrackWrongCodeEntry(chip::EndpointId endpointId);
+    bool HandleWrongCodeEntry(chip::EndpointId endpointId);
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.h:124]: Needs documentation (the API docs should be here, not next to the impl).

Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.h:124]: Should there be followup issues to update the example apps to call this?

File: src/app/clusters/door-lock-server/door-lock-server.h (hunk 1 above)
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.h:183]: Is this public API that consumers are expected to call?  I would have expected this to be called from SendLockOperationEvent as needed, so that consumers don't have to do that manually....

File: src/app/tests/suites/DL_LockUnlock.yaml [hunk 3]
```diff
@@ -270,7 +269,70 @@ tests:
...
+    # Engage lockout by trying invalid PIN again 3 times after the reset.
+    # The retry count should have reset to 0 to allow us 3 retry attempts again
+
+    - label: "Read the lockout timeout"
+      command: "readAttribute"
+      attribute: "UserCodeTemporaryDisableTime"
+      response:
+          value: 10
+
+    - label:
```
Comment (bzbarsky-apple) [inline src/app/tests/suites/DL_LockUnlock.yaml:309]: How do we know that the lockout counter was reset?  If it didn't get reset, we would enter lockout now, and our next two attempts would end up in failure, which is all this test is testing for, no?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/clusters/door-lock-server/door-lock-server.h (hunk 1 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.h:183]: Yes thats the intention. For the pinpad use case for e.g. the app doesn't send us the wrong entry info. so the app has to track the wrong code and call the HandleWrongCodeEntry or ResetWrongCodeEntryAttempts if  a correct pincode is entered. This was my understanding when talking to Joshua. I will cover this in the issue to track usage. Please let me know if we need to discuss this further

File: src/app/tests/suites/DL_LockUnlock.yaml (hunk 3 above)
Comment (nivi-apple) [reply src/app/tests/suites/DL_LockUnlock.yaml:309]: Yes thats true. since it was reset it takes 3 retries to engage lockout not 2. Please let me know if there's a better way to do this :)

File: src/app/clusters/door-lock-server/door-lock-server.h (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/clusters/door-lock-server/door-lock-server.h:183]: My point is: the app needs to be calling SendLockOperationEvent anyway, unless it manually sends those events.  So what I would propose is:

1. SendLockOperationEvent handles this automatically.
2. We have a public API for this too.
3. We clearly document that you either send events yourself and call the reset API, or that you just call SendLockOperationEvent and it handles things.

File: src/app/tests/suites/DL_LockUnlock.yaml (hunk 3 above)
Comment (bzbarsky-apple) [reply src/app/tests/suites/DL_LockUnlock.yaml:309]: The way to do this is to do two wrong things, then a right thing, then two more wrong things, and then the right thing again and test that the second right thing (after 4 previous wrong things, but with a right thing in the middle) works.

File: src/app/clusters/door-lock-server/door-lock-server.h (hunk 2 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.h:124]: yes agreed. will file one to track.

File: src/app/clusters/door-lock-server/door-lock-server.h (hunk 1 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.h:183]: gotcha. I added a reset in SetLockState https://github.com/project-chip/connectedhomeip/pull/25536/commits/f41610c4fcce7ebeac8d3ef32404ca9a5d34ae35#diff-ba4731e35f6cf29195b5ca8a6c50f6ed2b1730e9c492ae6453d02ac34e9f0f74R129. Are you saying that apps will call SendLockOperationEvent and not call setLockState. If thats true, I will add the reset code there as well. Please lmk. Will add documentation.

Comment (bzbarsky-apple) [reply src/app/clusters/door-lock-server/door-lock-server.h:183]: > my point is: the app needs to be calling SendLockOperationEvent anyway

I meant SetLockState, not SendLockOperationEvent....

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 4]
```diff
@@ -125,6 +125,9 @@ bool DoorLockServer::SetLockState(chip::EndpointId endpointId, DlLockState newLo
     // Schedule auto-relocking
     if (success && LockOperationTypeEnum::kUnlock == opType)
     {
+        // Reset code wrong entry attempts (in case there were any incorrect wrong code retries prior) since unlock was a success.
+        ResetWrongCodeEntryAttempts(endpointId);
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:129]: Shouldn't we only do that in cases when credentials were involved?  If this was an unlock without credentials presented, it shouldn't reset the wrong-credential attempt counter....

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 5]
```diff
@@ -181,7 +184,13 @@ bool DoorLockServer::SetPrivacyModeButton(chip::EndpointId endpointId, bool isEn
     return SetAttribute(endpointId, Attributes::EnablePrivacyModeButton::Id, Attributes::EnablePrivacyModeButton::Set, isEnabled);
 }
 
-bool DoorLockServer::TrackWrongCodeEntry(chip::EndpointId endpointId)
+/**
+ * @brief Handles a wrong code entry attempt. If the number of wrong entry attempts exceeds the max limit, engage lockout.
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:188]: Again, these comments should be in the header, not here.

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 6]
```diff
@@ -3352,7 +3361,13 @@ bool DoorLockServer::HandleRemoteLockOperation(chip::app::CommandHandler * comma
...
     if (!success && reason == OperationErrorEnum::kInvalidCredential)
     {
-        TrackWrongCodeEntry(endpoint);
+        HandleWrongCodeEntry(endpoint);
+    }
+
+    // Reset the wrong code retry attempts if a valid credential is presented
+    if (success && pinCode.HasValue())
+    {
+        ResetWrongCodeEntryAttempts(endpoint);
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:3370]: So we do this unconditionally here, but only for unlock operations in SetLockState.  Why the inconsistency?

Also, worth documenting here that we need to do this because the relevant code in SetLockState will not be reached for a kRemote operation source.

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 4 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:129]: agreed. I missed that. i have to check if credential is pincode and hasValue here too.

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 5 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:188]: haven't addressed this yet :) will do

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 6 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:3370]: i should check for unlock here. Will add that

File: src/app/tests/suites/DL_LockUnlock.yaml (hunk 3 above)
Comment (nivi-apple) [reply src/app/tests/suites/DL_LockUnlock.yaml:309]: makes sense. I think I was trying to go with - try 2 wrong times, then 1 right (wrong count should be 2). will my fix is now 0. Try 2nd set of 3 wrong times. lockout happens. try 1 right time and see failure. but i guess this doesn't confirm if the 2nd or 3rd wrong time in the 2nd set caused it. will fix.

File: src/app/clusters/door-lock-server/door-lock-server.h (hunk 1 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.h]: done

File: src/app/clusters/door-lock-server/door-lock-server.h (hunk 2 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.h:133]: done

File: src/app/clusters/door-lock-server/door-lock-server.h (hunk 1 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.h]: done

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 4 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp]: just checking if credential is not null and not empty as dicussed. done

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 5 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp]: done

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 6 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:3379]: should reset on both Lock/unlock

File: src/app/clusters/door-lock-server/door-lock-server.h (hunk 2 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.h:133]: https://github.com/project-chip/connectedhomeip/issues/25599

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 7]
```diff
@@ -3352,7 +3370,13 @@ bool DoorLockServer::HandleRemoteLockOperation(chip::app::CommandHandler * comma
 exit:
     if (!success && reason == OperationErrorEnum::kInvalidCredential)
     {
-        TrackWrongCodeEntry(endpoint);
+        HandleWrongCodeEntry(endpoint);
+    }
+
+    // Reset the wrong code retry attempts if a valid credential is presented during lock/unlock
+    if ((opType == LockOperationTypeEnum::kUnlock || opType == LockOperationTypeEnum::kLock) && success && pinCode.HasValue())
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:3377]:
```suggestion
    if (success && pinCode.HasValue())
```
The opType here is always either Lock or Unlock.

File: src/app/clusters/door-lock-server/door-lock-server.h [hunk 8]
```diff
@@ -121,7 +121,16 @@ class DoorLockServer
     bool SetOneTouchLocking(chip::EndpointId endpointId, bool isEnabled);
     bool SetPrivacyModeButton(chip::EndpointId endpointId, bool isEnabled);
 
-    bool TrackWrongCodeEntry(chip::EndpointId endpointId);
+    /**
+     * @brief Handles a wrong code entry attempt for the endpoint. If the number of wrong entry attempts exceeds the max limit,
+     *        engage lockout. Otherwise increment the number of incorrect attempts by 1. This is handled automatically for
+     *        remote operations - lock and unlock . Any app that uses SetLockState or sends lock/unlock events via
+     * SendLockOperationEvent has to handle tracking of wrong retry attempts and needs to call this API to update the wrong entry
+     * attempt count or engage lockoutif retry limit is exceeded.
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.h:129]:
```suggestion
     *        remote operations - lock and unlock.  Applications are responsible for calling it for non-remote incorrect credential presentation attempts.
```

File: src/app/clusters/door-lock-server/door-lock-server.h [hunk 9]
```diff
@@ -183,6 +192,16 @@ class DoorLockServer
     bool OnFabricRemoved(chip::EndpointId endpointId, chip::FabricIndex fabricIndex);
 
     static void DoorLockOnAutoRelockCallback(chip::System::Layer *, void * callbackContext);
+    /**
+     * @brief Resets the wrong code entry attempts to 0 for the endpoint. This API is called from HandleRemoteLockOperation
+     *        to reset the count if we have an lock/unlock remote operation with valid credential automatically. An app that
+     *        calls SetLockState also will have this done automatically on successful unlock operation using valid credential.
+     *        Any app that sends unlock events via SendLockOperationEvent has to handle resetting the wrong retry count by
+     *        calling this API.
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.h:200]:
```suggestion
     * @brief Resets the wrong code entry attempts to 0 for the endpoint. This is done automatically when a
     *        remote lock operation with credentials succeeds, or when SetLockState is called with a non-empty credentials list.
     *        Applications that call the two-argument version of SetLockState and handle sending the relevant operation events
     *        themselves or via SendLockOperationEvent are responsible for calling this API when a valid credential is presented.
```

File: src/app/tests/suites/DL_LockUnlock.yaml [hunk 10]
```diff
@@ -270,6 +270,94 @@ tests:
...
+                value: "123456"
+
+    - label: "Verify that lock state attribute value is set to Unlocked"
+      command: "readAttribute"
+      attribute: "LockState"
+      response:
+          value: 2
+
+    - label: "Try to unlock the door with invalid PIN for the first time"
+      command: "UnlockDoor"
```
Comment (bzbarsky-apple) [inline src/app/tests/suites/DL_LockUnlock.yaml:288]: Don't we need to re-lock it first, before trying to unlock more?

File: src/app/tests/suites/DL_LockUnlock.yaml [hunk 11]
```diff
@@ -270,6 +270,94 @@ tests:
...
+              - name: "PINCode"
+                value: "123456"
+
+    - label: "Verify that lock state attribute value is set to Unlocked"
+      command: "readAttribute"
+      attribute: "LockState"
+      response:
+          value: 2
+
+    - label: "Lock the door back prior to next tests"
```
Comment (bzbarsky-apple) [inline src/app/tests/suites/DL_LockUnlock.yaml:321]: So we need a copy of this bit and the following LockState check above.

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 7 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:3377]: There are 2 other codes in the enum (not valid op types though). chances are it won't be called for those but to be safe

File: src/app/tests/suites/DL_LockUnlock.yaml (hunk 10 above)
Comment (nivi-apple) [reply src/app/tests/suites/DL_LockUnlock.yaml:288]: yes we should. my bad

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 7 above)
Comment (bzbarsky-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp]: See the VerifyOrDie at the very top of the function.  And if _that_ ever changes, then the function needs to be read very carefully to make sure it's ok with the new optypes, top to bottom, not just this part.

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 12]
```diff
@@ -122,8 +122,8 @@ bool DoorLockServer::SetLockState(chip::EndpointId endpointId, DlLockState newLo
     SendLockOperationEvent(endpointId, opType, opSource, OperationErrorEnum::kUnspecified, userIndex, Nullable<chip::FabricIndex>(),
                            Nullable<chip::NodeId>(), credentials, success);
 
-    // Reset code wrong entry attempts (in case there were any incorrect wrong code retries prior) since lock/unlock was a success
-    // and a valid credential was presented
+    // Reset wrong entry attempts (in case there were any incorrect wrong credentials presented before) if lock/unlock was a success
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:125]:
```suggestion
    // Reset wrong entry attempts (in case there were any incorrect credentials presented before) if lock/unlock was a success
```

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 7 above)
Comment (nivi-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp]: i missed that. let me check

**Review by bzbarsky-apple — APPROVED** [review]

**Review by yufengwangca — APPROVED** [review]
