### PR TITLE
Fix: Bridge Action cluster NodeLabel attribute shows Success

### LINKED ISSUE #23509: Bridge Action cluster NodeLabel attribute showing UnsupportedWrite response instead Success
### Reproduction steps

```bash
Pair DUT and TH
Run test TC-BRBINFO-2.1 againt Bridge-app
in step 18: TH writes "newnode" to NodeLabel attribute, as per spec it is write supported but when executed got UNSUPPORTEDWRITE response instead Success.

Client : Bridge-app
server : Chip-tool
```

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

0c0092309188bcc5718aeb4b0f8f68eb468688ce

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

Diff link: https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:connectedhomeip:NodeLabel_UnsupportedWrite_Error
Testplan screenshot: 
image

Execution logs:
image
[exe_log.txt](https://github.com/project-chip/connectedhomeip/files/9941044/exe_log.txt)

### PR DESCRIPTION
**Pull request by r-recchia**
This PR fixes [#23509](https://github.com/project-chip/connectedhomeip/issues/23509)

### Updates

Updates `examples/bridge-app/linux/main.cpp`. Adds `HandleWriteBridgedDeviceBasicAttribute` function in order to handle `NodeLabel` writing. Also makes the attribute `NodeLabel` writable.

### Testing

- Build chip tool (terminal 1):
  ``` bash
  ./scripts/build/build_examples.py --target darwin-arm64-chip-tool build
  ```

- Build bridge app (terminal 1):
  ``` bash
  ./scripts/build/build_examples.py --target darwin-arm64-bridge build
  ```

- Remove commissioning data (terminal 1):

  ``` bash
  rm /tmp/chip_*
  ```

- Run bridge app (terminal 1):

  ``` bash
  ./out/darwin-arm64-bridge/chip-bridge-app
  ```

- Commission (terminal 2):

  ``` bash
  ./out/darwin-arm64-chip-tool/chip-tool pairing onnetwork 1 20202021 
  ```

- Read (terminal 2):

  ``` bash
  ./out/darwin-arm64-chip-tool/chip-tool bridgeddevicebasicinformation read node-label 1 3
  ```

  image

- Write (terminal 2):

  ``` bash
  ./out/darwin-arm64-chip-tool/chip-tool bridgeddevicebasicinformation write node-label '"newnode"' 1 3
  ```

  image

- Read (terminal 2):

  ``` bash
  ./out/darwin-arm64-chip-tool/chip-tool bridgeddevicebasicinformation read node-label 1 3
  ```

  image

### CODE REVIEW

File: examples/bridge-app/linux/main.cpp [hunk 1]
```diff
@@ -564,6 +565,33 @@ Protocols::InteractionModel::Status HandleWriteOnOffAttribute(DeviceOnOff * dev,
...
+
+        HandleDeviceStatusChanged(dev, Device::kChanged_Name);
+    }
+    else
+    {
+        return Protocols::InteractionModel::Status::Failure;
+    }
+
+    return Protocols::InteractionModel::Status::Success;
+}
```
[the remark this answers is not in the document]
Comment (r-recchia) [reply examples/bridge-app/linux/main.cpp]: Done!

File: examples/bridge-app/linux/main.cpp [hunk 2]
```diff
@@ -711,6 +738,10 @@ Protocols::InteractionModel::Status emberAfExternalAttributeWriteCallback(Endpoi
         {
             ret = HandleWriteOnOffAttribute(static_cast<DeviceOnOff *>(dev), attributeMetadata->attributeId, buffer);
         }
+        else if ((dev->IsReachable()) && (clusterId == BridgedDeviceBasicInformation::Id))
+        {
+            ret = HandleWriteBridgedDeviceBasicAttribute(static_cast<Device *>(dev), attributeMetadata->attributeId, buffer);
```
Comment (gd-mauri) [inline examples/bridge-app/linux/main.cpp]: no need for casting, since `dev` is already a Dev * 

```suggestion
            ret = HandleWriteBridgedDeviceBasicAttribute(dev, attributeMetadata->attributeId, buffer);
```

File: examples/bridge-app/linux/main.cpp [hunk 3]
```diff
@@ -564,6 +566,31 @@ Protocols::InteractionModel::Status HandleWriteOnOffAttribute(DeviceOnOff * dev,
...
+        return Protocols::InteractionModel::Status::Failure;
+    }
+
+    const uint8_t len = emberAfStringLength(buffer);
+    if (len > kNodeLabelSize)
+    {
+        return Protocols::InteractionModel::Status::InvalidValue;
+    }
+
+    std::string label(reinterpret_cast<const char *>(buffer + 1), len);
```
Comment (gd-mauri) [inline examples/bridge-app/linux/main.cpp]: [buffer + 1, buffer + 1 + len] will run out of band...

you maybe meant:

```
    std::string label(reinterpret_cast<const char *>(buffer), len);
```

Comment (gd-mauri) [reply examples/bridge-app/linux/main.cpp]: ember handles this... disregard comment

File: examples/bridge-app/linux/main.cpp (hunk 2 above)
Comment (r-recchia) [reply examples/bridge-app/linux/main.cpp]: Done

File: examples/bridge-app/linux/main.cpp [hunk 4]
```diff
@@ -564,6 +566,29 @@ Protocols::InteractionModel::Status HandleWriteOnOffAttribute(DeviceOnOff * dev,
...
 }
 
+Protocols::InteractionModel::Status HandleWriteBridgedDeviceBasicAttribute(Device * dev, chip::AttributeId attributeId,
+                                                                           uint8_t * buffer)
+{
+    ChipLogProgress(DeviceLayer, "HandleWriteBridgedDeviceBasicAttribute: attrId=%d", attributeId);
+
+    if (attributeId != chip::app::Clusters::BridgedDeviceBasicInformation::Attributes::NodeLabel::Id)
+    {
+        return Protocols::InteractionModel::Status::Failure;
```
Comment (andy31415) [inline examples/bridge-app/linux/main.cpp]: UnsupportedWrite seems to be the spec requirement for handling attributes that are not writable

File: examples/bridge-app/linux/main.cpp [hunk 5]
```diff
@@ -564,6 +566,29 @@ Protocols::InteractionModel::Status HandleWriteOnOffAttribute(DeviceOnOff * dev,
...
+    }
+
+    const uint8_t len = emberAfStringLength(buffer);
+    if (len > kNodeLabelSize)
+    {
+        return Protocols::InteractionModel::Status::InvalidValue;
```
Comment (andy31415) [inline examples/bridge-app/linux/main.cpp]: Is `ConstraintError` more correct here?

File: examples/bridge-app/linux/main.cpp [hunk 6]
```diff
@@ -564,6 +566,29 @@ Protocols::InteractionModel::Status HandleWriteOnOffAttribute(DeviceOnOff * dev,
...
+    }
+
+    dev->SetName(std::string{ reinterpret_cast<const char *>(buffer + 1), len }.c_str());
```
Comment (andy31415) [inline examples/bridge-app/linux/main.cpp]: emberAfStringLength or better use https://github.com/project-chip/connectedhomeip/blob/master/src/app/persistence/PascalString.h#L185

File: examples/bridge-app/linux/main.cpp (hunk 4 above)
Comment (r-recchia) [reply examples/bridge-app/linux/main.cpp]: Done!

File: examples/bridge-app/linux/main.cpp (hunk 5 above)
Comment (r-recchia) [reply examples/bridge-app/linux/main.cpp]: You are right, done!

File: examples/bridge-app/linux/main.cpp (hunk 6 above)
Comment (r-recchia) [reply examples/bridge-app/linux/main.cpp]: Updated to:

``` c++
    chip::Span<char> full(reinterpret_cast<char *>(buffer), static_cast<size_t>(len) + 1);
    ShortPascalString pascal(full);
    auto content = pascal.Content();
    dev->SetName(content.data());
```

File: examples/bridge-app/linux/main.cpp [hunk 7]
```diff
@@ -564,6 +569,34 @@ Protocols::InteractionModel::Status HandleWriteOnOffAttribute(DeviceOnOff * dev,
     return Protocols::InteractionModel::Status::Success;
 }
 
+Protocols::InteractionModel::Status HandleWriteBridgedDeviceBasicAttribute(Device * dev, chip::AttributeId attributeId,
```
Comment (bzbarsky-apple) [inline examples/bridge-app/linux/main.cpp]:
```suggestion
Protocols::InteractionModel::Status HandleWriteBridgedDeviceBasicAttribute(Device * dev, AttributeId attributeId,
```

File: examples/bridge-app/linux/main.cpp [hunk 8]
```diff
@@ -564,6 +569,34 @@ Protocols::InteractionModel::Status HandleWriteOnOffAttribute(DeviceOnOff * dev,
...
+                                                                           uint8_t * buffer)
+{
+    ChipLogProgress(DeviceLayer, "HandleWriteBridgedDeviceBasicAttribute: attrId=%d", attributeId);
```
Comment (bzbarsky-apple) [inline examples/bridge-app/linux/main.cpp]: This will not work right on a 32-bit system.  Please log the MEI as a MEI.

File: examples/bridge-app/linux/main.cpp [hunk 9]
```diff
@@ -564,6 +569,34 @@ Protocols::InteractionModel::Status HandleWriteOnOffAttribute(DeviceOnOff * dev,
...
+
+    if (attributeId != chip::app::Clusters::BridgedDeviceBasicInformation::Attributes::NodeLabel::Id)
```
Comment (bzbarsky-apple) [inline examples/bridge-app/linux/main.cpp]:
```suggestion
    if (attributeId != BridgedDeviceBasicInformation::Attributes::NodeLabel::Id)
```

File: examples/bridge-app/linux/main.cpp [hunk 10]
```diff
@@ -564,6 +569,34 @@ Protocols::InteractionModel::Status HandleWriteOnOffAttribute(DeviceOnOff * dev,
...
+    }
+
+    const uint8_t len = emberAfStringLength(buffer);
+
+    if (len > kNodeLabelSize)
+    {
+        return Protocols::InteractionModel::Status::ConstraintError;
+    }
+
+    chip::Span<char> full(reinterpret_cast<char *>(buffer), static_cast<size_t>(len) + 1);
```
Comment (bzbarsky-apple) [inline examples/bridge-app/linux/main.cpp]: Is here a reason this is reinventing `CharSpan::fromZclString`?

File: examples/bridge-app/linux/main.cpp [hunk 11]
```diff
@@ -564,6 +569,34 @@ Protocols::InteractionModel::Status HandleWriteOnOffAttribute(DeviceOnOff * dev,
...
+    ShortPascalString pascal(full);
+    auto content = pascal.Content();
+
+    dev->SetName(content.data());
```
Comment (bzbarsky-apple) [inline examples/bridge-app/linux/main.cpp]: Wait, what?  Where is the null-termination coming from?  SetName() should be taking a CharSpan.

I have to ask: was this tested at all?  Why are there no tests for this in the PR?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: examples/bridge-app/linux/main.cpp (hunk 11 above)
Comment (andy31415) [reply examples/bridge-app/linux/main.cpp]: data is not the right thing here ... content is a span not a null terminated string. SetName should take a charspan or you should use something that guarantees null termination (e.g. stringbuilder will as long as you check that it did Fit() ). This mix of c_str and char_span in apis makes things harder.

File: examples/bridge-app/linux/main.cpp (hunk 8 above)
Comment (r-recchia) [reply examples/bridge-app/linux/main.cpp]: Done!

File: examples/bridge-app/linux/main.cpp (hunk 10 above)
Comment (r-recchia) [reply examples/bridge-app/linux/main.cpp]: Changed to:
  ``` C++
  CharSpan nameSpan = CharSpan::fromZclString(buffer);
  ```

File: examples/bridge-app/linux/main.cpp (hunk 11 above)
Comment (r-recchia) [reply examples/bridge-app/linux/main.cpp]: Updated to:

``` c++
    std::string name(nameSpan.data(), nameSpan.size());    
    dev->SetName(name.c_str());
```

File: examples/bridge-app/linux/main.cpp [hunk 12]
```diff
@@ -26,15 +26,18 @@
 #include <app/AttributeAccessInterfaceRegistry.h>
 #include <app/ConcreteAttributePath.h>
 #include <app/EventLogging.h>
+#include <app/persistence/String.h>
```
Comment (andy31415) [inline examples/bridge-app/linux/main.cpp]: Are you using this anymore?

File: examples/bridge-app/linux/main.cpp [hunk 13]
```diff
@@ -564,6 +569,31 @@ Protocols::InteractionModel::Status HandleWriteOnOffAttribute(DeviceOnOff * dev,
...
+Protocols::InteractionModel::Status HandleWriteBridgedDeviceBasicAttribute(Device * dev, AttributeId attributeId, uint8_t * buffer)
+{
+    ChipLogProgress(DeviceLayer, "HandleWriteBridgedDeviceBasicAttribute: attrId=" ChipLogFormatMEI, ChipLogValueMEI(attributeId));
+
+    if (attributeId != BridgedDeviceBasicInformation::Attributes::NodeLabel::Id)
+    {
+        return Protocols::InteractionModel::Status::UnsupportedWrite;
+    }
+
+    const uint8_t len = emberAfStringLength(buffer);
```
Comment (andy31415) [inline examples/bridge-app/linux/main.cpp]: how about doing fromZclString and then checking nameSpan.size for the constraint error?

File: examples/bridge-app/linux/main.cpp (hunk 12 above)
Comment (r-recchia) [reply examples/bridge-app/linux/main.cpp]: Done! Removed unused imports

File: examples/bridge-app/linux/main.cpp (hunk 13 above)
Comment (r-recchia) [reply examples/bridge-app/linux/main.cpp]: Done! Not using `emberAfStringLength()` for `CONSTRAINT` validation. Using `CharSpan.size()` instead

File: src/app/tests/suites/certification/Test_TC_BRBINFO_2_1.yaml [hunk 14]
```diff
@@ -160,7 +160,6 @@ tests:
               type: char_string
               maxLength: 32
 
-    #Issue https://github.com/project-chip/connectedhomeip/issues/23509
```
Comment (andy31415) [inline src/app/tests/suites/certification/Test_TC_BRBINFO_2_1.yaml:163]: was the comment here because this was a manual validation (since I see 'verification' steps)?

Can we automate it now? Or should we create an issue to automate it?

**Review by andy31415 — APPROVED** [review]

File: src/app/tests/suites/certification/Test_TC_BRBINFO_2_1.yaml (hunk 14 above)
Comment (r-recchia) [reply src/app/tests/suites/certification/Test_TC_BRBINFO_2_1.yaml:163]: Test_TC_BRBINFO_2_1 automated

**Review by bzbarsky-apple — APPROVED** [review]
