### PR TITLE
[OTA Requestor] Implement the CancelImageUpdate() OTARequestor API

### LINKED ISSUE #13393: Most versions of OTAImageProcessorImpl::SetBlock are broken
#### Problem
The K32W, Linux, and EFR32 implementations of `OTAImageProcessorImpl::SetBlock` all have the same problem, due to being copy/pasted from each other.  If the blocks coming in are different sizes (which is very much allowed in bdx), then any block that's larger than the smallest preceding block will fail.

Specifically, `CopySpanToMutableSpan`, which is used in the function does the following:
1) Ensures that the source span fits inside the target span.
2) Copies the data.
3) Sets the size of the target span to the size of the source span.

Step 3 is key.  It means that `mBlock` will be the size of the smallest block seen so far.

The implementation on ESP32 does not have this problem, though it will do too much releasing/allocating because it does not keep track of the actual available space in mBlock, just of the space used by the last block copied into it.

 #### Proposed Solution
Ideally, stop having multiple copies of this (clearly hard to get right) code.  Have one copy, that we make correct and everyone uses.

Failing that, at least copy/paste the non-buggy version.

### PR DESCRIPTION
**Pull request by selissia**
#### Problem
Need an OTARequestor API to cancel image update

#### Change overview
Implement the CancelImageUpdate() OTARequestor API. Also add the UpdateCancelled API to OTARequestorDriver.

Also add comments and a check to highlight the fact the mProviderNodeId, mProviderFabricIndex and mProviderEndpointId OTARequestor member variables only apply to the image update currently in progress. 

Also fix https://github.com/project-chip/connectedhomeip/issues/13393 for Linux (change in `src/platform/Linux/OTAImageProcessorImpl.cpp`)

#### Testing
Tested with a custom-coded Linux chip-ota-requestor-app to invoke CancelImageUpdate() at various stages of the image udate flow (idle, download in progress).

### CODE REVIEW

File: src/app/clusters/ota-requestor/OTARequestor.h [hunk 1]
```diff
@@ -114,13 +114,9 @@ class OTARequestor : public OTARequestorInterface, public BDXDownloader::StateDe
...
-    // Application directs the Requestor to abort the download in progress. All the Requestor state (such
-    // as the QueryImageResponse content) is preserved
-    void AbortImageUpdate();
-
-    // Application directs the Requestor to abort the download in progress. All the Requestor state is
-    // cleared, UploadState is reset to Idle
-    void AbortAndResetState();
+    // Application directs the Requestor to cancel image update in progress. All the Requestor state is
+    // cleared, UpdateState is reset to Idle
+    void CancelImageUpdate();
```
Comment (carol-apple) [inline src/app/clusters/ota-requestor/OTARequestor.h:119]: This API should be in OTARequestorInterface.h as well

File: src/app/clusters/ota-requestor/OTARequestor.cpp [hunk 2]
```diff
@@ -270,6 +271,20 @@ void OTARequestor::ConnectToProvider(OnConnectedAction onConnectedAction)
                    ChipLogError(SoftwareUpdate, "Cannot establish connection to provider: %" CHIP_ERROR_FORMAT, err.Format()));
 }
 
+// Application directs the Requestor to cancel image update in progress. All the Requestor state is
```
Comment (carol-apple) [inline src/app/clusters/ota-requestor/OTARequestor.cpp:274]: nit: Probably no need to repeat the same comment as what's already in the header?

File: src/app/clusters/ota-requestor/OTARequestor.cpp [hunk 3]
```diff
@@ -270,6 +271,20 @@ void OTARequestor::ConnectToProvider(OnConnectedAction onConnectedAction)
...
+void OTARequestor::CancelImageUpdate()
+{
+    mBdxDownloader->EndDownload(CHIP_ERROR_CONNECTION_ABORTED);
+
+    // All Provider info should be invalidated
+    mProviderNodeId      = kUndefinedNodeId;
+    mProviderFabricIndex = kUndefinedFabricIndex;
+    mProviderEndpointId  = kRootEndpointId;
+
+    RecordNewUpdateState(OTAUpdateStateEnum::kIdle, OTAChangeReasonEnum::kUnknown);
```
Comment (carol-apple) [inline src/app/clusters/ota-requestor/OTARequestor.cpp:285]: Should we actually call `RecordErrorUpdateState` so that `HandleError` can be called on the driver?

File: src/app/clusters/ota-requestor/OTARequestor.h (hunk 1 above)
Comment (selissia) [reply src/app/clusters/ota-requestor/OTARequestor.h:119]: Fixed

File: src/app/clusters/ota-requestor/OTARequestor.cpp (hunk 3 above)
Comment (selissia) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:285]: I don't know. Are we in an error situation here? The application decides to cancel the image update process, the core OTA logic successfully stops the download and resets all the state. I don't necessarily see that any of this constitutes an error and requires error handling from the platform.

File: src/app/clusters/ota-requestor/OTARequestor.cpp (hunk 2 above)
Comment (selissia) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:274]: I actually have the opposite view on this: I find it inconvenient that people don't comment function definitions. When looking through the code and trying to understand what a function does one has to stop and chase the function declaration -- potentially through multiple header files and complicated chains of inheritance.

Comment (carol-apple) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:274]: I find it extra maintenance. If the comment changes in one spot, you need to remember to change it in the other place. Many times, only one has been done so you end up with out of sync comments. Nonetheless, this was a nit.

File: src/app/clusters/ota-requestor/OTARequestor.cpp (hunk 3 above)
Comment (carol-apple) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:285]: This more or less relates to the topic we had yesterday on periodic query. If we were to cancel, the entire process ends with this function. If we were to call `HandleError` (that function is currently empty), perhaps we could handle a restart of query after X time if we were to pass in the right `UpdateFailureState` here. Thoughts?

File: src/app/clusters/ota-requestor/OTARequestor.h [hunk 4]
```diff
@@ -269,9 +265,9 @@ class OTARequestor : public OTARequestorInterface, public BDXDownloader::StateDe
     static void OnNotifyUpdateAppliedFailure(void * context, EmberAfStatus);
 
     OTARequestorDriver * mOtaRequestorDriver  = nullptr;
-    NodeId mProviderNodeId                    = kUndefinedNodeId;
-    FabricIndex mProviderFabricIndex          = kUndefinedFabricIndex;
-    EndpointId mProviderEndpointId            = kRootEndpointId;
+    NodeId mProviderNodeId                    = kUndefinedNodeId;      // Only valid for the current update in progress
```
Comment (carol-apple) [inline src/app/clusters/ota-requestor/OTARequestor.h:268]: I'm actually unclear on what this comment is meant to tell me. It's not like we regularly update these values so it should be valid literally forever unless some code explicitly sets it to undefined again, no?

File: src/app/clusters/ota-requestor/OTARequestor.cpp (hunk 3 above)
Comment (selissia) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:285]: Yes, we may decide to pass some sort of notification to the driver but it would have to be something tailored to this particular situation -- "Cancel Retries" or something like that, not a general error event.

File: src/app/clusters/ota-requestor/OTARequestor.h (hunk 4 above)
Comment (selissia) [reply src/app/clusters/ota-requestor/OTARequestor.h:268]: The code added in this PR explicitly sets it to undefined. And I think that we should update these values regularly: every time DefaultProvider changes or AnnounceOTAProvider is received.

File: src/app/clusters/ota-requestor/OTARequestor.cpp (hunk 2 above)
Comment (selissia) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:274]: Yes, producing readable code requires extra effort.

File: src/app/clusters/ota-requestor/OTARequestor.cpp (hunk 3 above)
Comment (carol-apple) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:285]: Could you add the API to the driver? Don't necessarily have to implement it.

File: src/app/clusters/ota-requestor/OTARequestor.h (hunk 4 above)
Comment (carol-apple) [reply src/app/clusters/ota-requestor/OTARequestor.h:268]: Right... but the point is, once they have been set (either via DefaultOTAProviders change or AnnounceOTAProviders), then these contain "valid" values unless they provider node is no longer on the fabric.

File: src/app/clusters/ota-requestor/OTARequestor.cpp (hunk 3 above)
Comment (selissia) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:285]: Done

File: src/app/clusters/ota-requestor/OTARequestor.h (hunk 4 above)
Comment (selissia) [reply src/app/clusters/ota-requestor/OTARequestor.h:268]: Here valid is supposed to mean "valid as the provider we are currently communicating with". If we get a fresh AnnounceOtaProvider then the mProviderNodeId gets overwritten, the old one is no longer valid. Same for CancelImageUpdate().

**Review by carol-apple — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]
