### PR TITLE
Shut down subscription clients when DeviceController shuts down.

### LINKED ISSUE #22319: DeviceController shutdown should ShutdownSubscription on still-registered subscriptions.
#### Problem
During stack shutdown, if there are subscription ReadClients that are not waiting from a message from the server, or are but use auto-resubscribe, those ReadClients will not end up erroring out.  That means the consumer will not be notified and will not know to destroy them, and if they are destroyed later they will crash as described in https://github.com/project-chip/connectedhomeip/issues/20085

 #### Proposed Solution
Since we know the ReadClients won't receive any more messages from the server (because we are removing them from the InteractionModelEngine list and because their resubscribe timers will never fire, since we are shutting down), we should just ShutdownSubscription on all of them.  That will give API consumers a sane chance to clean them up.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Other clients get shut down due to their sessions going away, but subscription
clients can be in a state where they are not waiting on a response, and those
should get shut down too.

Also:

1) Fixes ReadClient::Close to release its exchange, so shutting down a
subscription while it's waiting for a response from the server actually shuts it
down, instead of delivering OnDone and then getting a message on the exchange
and possibly sending more notifications after OnDone.

2) Fixes potential use-after-free in the ShutdownSubscriptions functions.

Fixes https://github.com/project-chip/connectedhomeip/issues/22319

#### Problem
Crashes possible due to subscription clients outliving shutdown.

#### Change overview
Make sure we call OnDone on all relevant subscriptions when shutting down a DeviceController.

#### Testing
Verified that if I create a subscription in chip-tool or darwin-framework-tool and then shut down the relevant controller I see `~ReadClient` getting called.

### CODE REVIEW

**Review by jmartinez-silabs — APPROVED** [review]

**Review by tcarmelveilleux — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
And just to address https://github.com/project-chip/connectedhomeip/issues/20085#issuecomment-1170555208 :

If we're shutting down the DeviceController for a fabric, nixing all the sessions for that fabric, etc, not calling Close on the subscription clients is a bit odd.  It also leads to races: clients waiting on the server will get closed (because their session goes away), but clients not thus waiting would just stick around...

**Comment by bzbarsky-apple** [comment]
The Darwin CI failure here is real, though the problem pre-existing: we used to leak the ReadClient and the callback waiting on it.  Now we're freeing the ReadClient, but not the callback (because we are using the ReadInteraction SubscribeAttribute API, which never calls OnDone on us, and hence we never know whether we can free the callback bits.

LSAN used to not detect the leak because we leaked objects that referred to each other, and LSAN does not detect that.  But now we free one of them, not the other, and the leak gets noticed.

**Comment by bzbarsky-apple** [comment]
Filed https://github.com/project-chip/connectedhomeip/issues/22333 on the leak issue.  Will just add a suppression for now, since it's not being made worse by this PR.

**Review by yunhanw-google — APPROVED** [review]

File: src/app/InteractionModelEngine.cpp [hunk 1]
```diff
@@ -253,24 +258,50 @@ CHIP_ERROR InteractionModelEngine::ShutdownSubscription(const ScopedNodeId & aPe
...
+    // ReadClients in the list.
+    for (auto * readClient = mpActiveReadClientList; readClient != nullptr;)
     {
+        // Grab the next client now, because we might be about to delete readClient.
+        auto * nextClient = readClient->GetNextClient();
         if (readClient->IsSubscriptionType())
         {
             readClient->Close(CHIP_NO_ERROR);
         }
+        readClient = nextClient;
```
Comment (vivien-apple) [inline src/app/InteractionModelEngine.cpp:304]: What about having a single method with `chip::Optional` parameters for the `FabricIndex` and the `NodeId` ?
That would avoid having to duplicate the loops/comments. I'm thinking of something like:

```
void InteractionModelEngine::ShutdownSubscriptions(Optional<FabricIndex> fabricIndex = Optional<FabricIndex>::Missing(), Optional<NodeId> nodeId = Optional<NodeId>::Missing())
{
    // This is assuming that ReadClient::Close will not affect any other
     // ReadClients in the list.
     for (auto * readClient = mpActiveReadClientList; readClient != nullptr;)
     {
         // Grab the next client now, because we might be about to delete readClient.
         auto * nextClient = readClient->GetNextClient();
         if (readClient->IsSubscriptionType())
         {
             bool validFabric = !fabricIndex.HasValue() || (fabricIndex.Value) == readClient->GetFabricIndex());
             bool validNodeId = !nodeId.HasValue() || (nodeId.Value() == readClient->GetNodeId());
             if (validFabric && validNodeId)
             {
                 readClient->Close(CHIP_NO_ERROR);
             }
         }
         readClient = nextClient;
     }
}

void InteractionModelEngine::ShutdownAllSubscriptions()
{
     ShutdowSubscriptions();
}

void InteractionModelEngine::ShutdownSubscriptions(FabricIndex aFabricIndex)
{
    ShutdowSubscriptions(MakeOptional(aFabricIndex));
}

void InteractionModelEngine::ShutdownSubscriptions(FabricIndex aFabricIndex, NodeId aPeerNodeId)
{
    ShutdowSubscriptions(MakeOptional(aFabricIndex), MakeOptional(nodeId));
}
```

**Review by vivien-apple — APPROVED** [review]

**Comment by andy31415** [comment]
V1 accepted: fixes potential crash.

File: src/app/InteractionModelEngine.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/InteractionModelEngine.cpp:291]: Good idea, done.
