### PR TITLE
Android: Synchronizing on the use of NsdManager.resolveService()

### LINKED ISSUE #23514: [BUG] Android: NsdManager resolver calls back with FAILURE_ALREADY_ACTIVE
### Reproduction steps

```bash
1. Commission the Android tv-casting-app
2. Kill the app and restart
3. Commissioner discovery fails with the error FAILURE_ALREADY_ACTIVE
```

### Bug prevalence

3 out of 5 times with the above steps

### GitHub hash of the SDK that was being used

351876075cd34841a5b7d628df5fb9b42003b5f2

### Platform

android

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sharadb-amazon**
Fixes https://github.com/project-chip/connectedhomeip/issues/23514

#### Problem
The Android NsdManager seems capable of only resolving one service at a time. If it is called to resolve a service while it already is busy with a previous request, it calls back the second caller's ResolveListener with a [FAILURE_ALREADY_ACTIVE](https://developer.android.com/reference/android/net/nsd/NsdManager#FAILURE_ALREADY_ACTIVE) error. 

This leads to issues with running discovery and resolution from any app code if Matter SDK's NsdManagerServiceResolver.java is running service resolution in parallel. For example, Commissioner discovery/resolution may fail if Operational discovery/resolution is already in progress - as manifested in the Android tv-casting-app bug cited above. Further more, this may lead to issues with _any_ usage of NsdManager's resolveService API for any use case (Matter related _or otherwise_)

#### Change summary
This change adds a NsdManagerResolverAvailState to the Matter NsdManagerServiceResolver and allows setting it optionally via an overloaded constructor. If an app provides this NsdManagerResolverAvailState object, it can use it to synchronize with the Matter NsdManagerServiceResolver on the usage of NsdManager's resolveService API. This helps avoid failing with the [FAILURE_ALREADY_ACTIVE](https://developer.android.com/reference/android/net/nsd/NsdManager#FAILURE_ALREADY_ACTIVE) error when using the NsdManager (in Matter SDK and/or app side code)

#### Testing
Tested the fix with the android tv-casting-app by following the repro steps in the issue cited above.

### CODE REVIEW

**Review by chrisdecenzo — APPROVED** [review]

File: src/platform/android/java/chip/platform/NsdManagerServiceResolver.java [hunk 1]
```diff
@@ -223,4 +255,47 @@ public void removeServices() {
...
+
+    private Lock lock = new ReentrantLock();
+    private Condition condition = lock.newCondition();
+    private boolean busy = false;
+
+    /**
+     * Waits if the NsdManager is already busy with resolving a service. Otherwise, it marks it as
+     * busy and returns
+     */
+    public void markBusyIfFreeOrWait() {
```
Comment (andy31415) [inline src/platform/android/java/chip/platform/NsdManagerServiceResolver.java:277]: nit: method names with `or` are generally harder to reason about because they include separate action paths. How about naming this something singular, like `acquireBusy` or `lockBusy` or similar?

File: src/platform/android/java/chip/platform/NsdManagerServiceResolver.java [hunk 2]
```diff
@@ -223,4 +255,47 @@ public void removeServices() {
...
+      }
+      lock.unlock();
+    }
+
+    /** Signals the NsdManager resolver as free */
+    public void signalFree() {
+      lock.lock();
+      Log.d(TAG, "Signaling NsdManager Resolver as free");
+      busy = false;
+      condition.signalAll();
```
Comment (andy31415) [inline src/platform/android/java/chip/platform/NsdManagerServiceResolver.java:297]: would `signal` be sufficient here? Why the All?

File: src/platform/android/java/chip/platform/NsdManagerServiceResolver.java [hunk 3]
```diff
@@ -37,15 +40,27 @@ public class NsdManagerServiceResolver implements ServiceResolver {
   private Handler mainThreadHandler;
   private List<NsdManager.RegistrationListener> registrationListeners = new ArrayList<>();
   private final CopyOnWriteArrayList<String> mMFServiceName = new CopyOnWriteArrayList<>();
+  private final NsdManagerResolverAvailState nsdManagerResolverAvailState;
```
Comment (andy31415) [inline src/platform/android/java/chip/platform/NsdManagerServiceResolver.java:43]: We have a constructor that can set this to null. Can we tag this as nullable?

File: src/platform/android/java/chip/platform/NsdManagerServiceResolver.java (hunk 1 above)
Comment (sharadb-amazon) [reply src/platform/android/java/chip/platform/NsdManagerServiceResolver.java]: Done. Called it acquireResolver()

File: src/platform/android/java/chip/platform/NsdManagerServiceResolver.java (hunk 2 above)
Comment (sharadb-amazon) [reply src/platform/android/java/chip/platform/NsdManagerServiceResolver.java]: signal is indeed more appropriate here. Changed.

File: src/platform/android/java/chip/platform/NsdManagerServiceResolver.java (hunk 3 above)
Comment (sharadb-amazon) [reply src/platform/android/java/chip/platform/NsdManagerServiceResolver.java]: Done.

**Review by andy31415 — APPROVED** [review]

**Comment by zhenqinrui** [comment]
Excuse? I have a question, wheath it should new NsdManagerResolverAvailState? I havent' found the new NsdManagerResolverAvailState, how can i do ?
