### PR TITLE
Simplify/fix handling of fabric-scoped command payloads.

### LINKED ISSUE #39001: AccessingFabricIndex should be available for all commands
### Reproduction steps

Currently it seems that there are conditions (`!mGoneAsync`) for [the context fabric ID to be available while handling a command](https://github.com/project-chip/connectedhomeip/blob/9b54b6708dee9d4d74839173ec824d78f460fd6c/src/app/CommandHandlerImpl.cpp#L762)

This causes problems with fabric-scoped structures, where we need to always know the fabric ID so that it can be propagated to the fabric-scoped structure.

What is the context here? Shouldn't there always be a way to find out what the fabric id is for a command being handled?

### Bug prevalence

Unsure

### GitHub hash of the SDK that was being used

head

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
* Remove DataModel::Encode/Decode overloads that were slight footguns.
* Fix CommandSender::AddRequestData to not look like it has a usable fabric index.  It doesn't.
* Fix WrappedStructEncoder be explicit about what it's encoding when dealing with fabric-scoped struct fields of commands.
* Fix command payload codegen to just have Encode() methods, including for response commands, but take a FabricIndex argument for response commands that is then used for encoding the fabric-scoped structs appropriately (i.e. skipping fabric-sensitive fields as needed).
* Fix a few new uses of if_is_fabric_scoped_struct to pass in the cluster name.
* Make TestCommandInteraction.cpp not executable again, since it doesn't need to be.

#### Testing

Existing unit tests continue to work.

### CODE REVIEW

File: src/app/CommandHandlerImpl.cpp [hunk 1]
```diff
@@ -135,16 +135,26 @@ CHIP_ERROR CommandHandlerImpl::TryAddResponseData(const ConcreteCommandPath & aR
...
+    //
+    // Note that just calling GetAccessingFabricIndex() here is not OK, because
+    // we may have gone async already and our exchange/session may be gone, so
+    // that would crash.  Which is one of the reasons GetAccessingFabricIndex()
+    // is not allowed to be called once we have gone async.
+    FabricIndex accessingFabricIndex;
+    if (context && context->HasSessionHandle()) {
+        accessingFabricIndex = context->GetSessionHandle()->GetFabricIndex();
+    } else {
+        accessingFabricIndex = kUndefinedFabricIndex;
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/app/CommandHandlerImpl.cpp:156]: There's a comment a few lines above.

File: src/app/CommandSender.cpp [hunk 2]
```diff
@@ -563,15 +563,7 @@ CHIP_ERROR CommandSender::AddRequestData(const CommandPathParams & aCommandPath,
     ReturnErrorOnFailure(PrepareCommand(aCommandPath, prepareCommandParams));
     TLV::TLVWriter * writer = GetCommandDataIBTLVWriter();
     VerifyOrReturnError(writer != nullptr, CHIP_ERROR_INCORRECT_STATE);
-    if (mExchangeCtx.Get() && mExchangeCtx.Get()->HasSessionHandle())
```
Comment (gmarcosb) [inline src/app/CommandSender.cpp:566]: This is ok to not include a fabric index? i.e. what's CommandSender used for vs CommandHandlerImpl?

**Review by gmarcosb — APPROVED** [review]
Thanks for helping with this!

File: src/app/CommandSender.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/app/CommandSender.cpp:566]: CommandSender is used for client-to-server (request) commands, which per spec are required to not include a fabric index right?

CommandHandlerImpl is used for server-to-client (response) commands.

Comment (gmarcosb) [reply src/app/CommandSender.cpp:566]: Oh sweet jesus why are they both under `app`? 😬🤦‍♂️

I had thought client-to-server generally went under controller?

Does it make sense to add a note to `CommandSender` that it's intended for request commands, whereas `CommandHandler` for response?

(Feel free to resolve this either way, will defer to you)

**Review by andy31415 — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

File: src/app/CommandSender.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/app/CommandSender.cpp:566]: Yeah, better docs would be good.  And apps can send commands (e.g. a light switch!)

**Review by pidarped — APPROVED** [review]
