### PR TITLE
Fix ExchangeContext leaks

### LINKED ISSUE #21544: ExchangeHolder leaks exchanges on send failure followed by session expiration
#### Problem
Consider the following sequence of events:

1. An exchange is created for a session.
2. The exchange is stored in an ExchangeHolder.
3. A message is sent on the exchange.  The send fails (which means the exchange does not close).
4. Caller does not close the exchange, because it's relying on the ExchangeHolder to do that.
5. The session is evicted.  This lands in `ExchangeContext::OnSessionReleased` which sees that we're not in `IsResponseExpected()` state and hence that it's our consumer's responsibility to close us.  So it does not call `Abort` or `Close`.
6. The exchange calls `DoClose` to do its session-eviction cleanup, which calls `OnExchangeClosing` on the holder.
7. The holder sees that neither `IsResponseExpected()` nor `IsSendExpected()` is true and just forgets its pointer to the exchange.
8. ~ExchangeHolder is called, does nothing because it's not holding anything.

As a result nothing ever drops the ref to the exchange.

This is trivially reproducible on Mac with:
```
chip-tool onoff toggle 0xffffffffffff4141 1454
````
(a group command) which has code like this:
```
        chip::app::CommandSender commandSender(mCallback, exchangeManager);
        ReturnErrorOnFailure(commandSender.AddRequestDataNoTimedCheck(commandPath, value, chip::NullOptional));

        chip::Transport::OutgoingGroupSession session(groupId, fabricIndex);
        return commandSender.SendGroupCommandRequest(chip::SessionHandle(session));
```
Note that the `session` destructor happens before the `commandSender` destructore, hence step 5 above happening before step 8.  But in general the above ordering could happen for various reasons.

 #### Proposed Solution
We need to decide whether `OnExchangeClosing` means (1) "Close or Abort has been called, and the ref that was holding has been dropped" (which is what SessionHolder seems to be assuming) or whether it means (2) "we have set our kFlagClosed and there is no more communication on this exchange" (which is what is actually implemented).

Based on a quick grep, not much implements `OnExchangeClosing`:
* `DefaultOTARequestor.h` seems to expect meaning (1) of the callback.  In particular, all it does is drop the reference, which would be the wrong thing to do for the other meaning.
* `ExchangeHolder`, as discussed above, expects meaning (1).
* `TimedHandler` kind of expects meaning (2), but in practice since it's always a responder it never ends up in a state where it's got an exchange that is not processing an incoming messagne and not waiting for a response.  So it never ends up in the codepath above, where we end up in `DoClose` without dropping a ref.

But an issue there is that `DoClose` will drop the reference to the delegate, so _won't_ be able to notify it about the exchange closing in the future....

### LINKED ISSUE #21632: Address possible mis-behavior due to pointer-to-exchange members being null when they did not use to be
#### Problem
After #21081 and #20237 the semantics of the exchange context member of various interaction model objects changed in a subtle but important way.

Before that change, the member could only become null in the following cases:
* We tried to send a message, it failed, we close the exchange and null it out.
* We tried to send the last message in the transaction, it succeeded, the exchange self-closed and we nulled it out.
* We were waiting for a response, it timed out (possibly due to the session going away), the exchange self-closed and we nulled it out.
* We decided we were done (e.g. due to error of some sort) and closed the exchange.

Importantly: while we are processing an incoming message, the member could not become null until we tried to send a response.  That means any logic that used the member could rely on it being there while processing an incoming message.

After #21081 and #20237 that changes: now if the session goes away (as one possible trigger for the behavior) the member becomes null immediately.  This means that any methods/getters that use the exchange context can start mis-behaving while we are trying to process an incoming message, including things like not being able to determine the accessing fabric (or it changing in mid-processing!).  At least the following things might be affected:

* CommandHandler::ProcessGroupCommandDataIB
* CommandHandler::GetAccessingFabricIndex
* CommandHandler::GetSubjectDescriptor
* Various places in WriteHandler where I think depending on how the stack reacts to a write the mExchangeCtx could end up null where it couldn't have before.

 #### Proposed Solution
 We need to think a little bit about whether this is a problem in practice or not.  Maybe something guarantees that the session can't be evicted while we are processing an incoming message on it, but I don't see obvious such guarantees.

Maybe an attempt to close an exchange while it's processing an incoming message (including due to session eviction) should simply set a flag (which would prevent any more sending of non-ack messages; need to think about what happens here if the closure is due to session going away) and do the actual closing + notification of the delegate once we unwind the stack?  But note that some of the state we are interested in from exchanges actually comes from the session, so it might have mis-behaved before anyway if the session went away but the exchange remained non-null...

Another option would be for the IM objects to snapshot anything they need from the exchange except message-sending services before they start calling out to consumers for an incoming message.  But that would require those objects to get bigger, which might be an issue.

Any other bright ideas @mrjerryjohns?

### PR DESCRIPTION
**Pull request by mrjerryjohns**
This makes some key fixes to the management of the `ExchangeContext`, specifically around how the `WillSendMessage` flag is set/cleared, as well as dealing with clean-up of the exchange in `OnSessionReleased()`. It also fixes some key bugs in ExchangeHolder around failure to release the ref on the exchange in certain scenarios as outlined in bugs #21544 and #21632.

Notably, the following fixes have been made to `ExchangeContext`:
- Setting the `WillSendMessage` flag immediately in `SendMessage` and only clearing the WillSendMessage flag on actually having successfully sent a message in `SendMessage`. Otherwise, the holder is not able to infer that the ownership still resides with it on a `SendMessage` failure.

- Not clearing the `WillSendMessage` flag in OnSessionReleased. This ensures the holder again can infer that it still has the ref and needs to give it up when `OnExchangeClosing` is called there-after.

- Avoiding a double call of `DoClose` by checking if it is already closed.

- Cleaning up `OnSessionReleased` logic to now correctly call `Abort()` in
  both the case where we're waiting for a response AND we're in the
  middle of received message dispatch (i.e we're in the middle of
  `OnMessageReceived`). This is a pre-existing bug where the closure of the exchange resulted in a leak due to `MessageHandled()` not quite cleaning up the EC later when the call unwinds.

Tests:

`TestExchangeHolder` has been buffed up to now exhaustively test permutations of send failure, session closure (both before and after message transmission) and calling WillSendMessage at all points along a
3 message transmission.

### CODE REVIEW

File: src/messaging/ExchangeContext.cpp [hunk 1]
```diff
@@ -336,7 +364,6 @@ ExchangeContext::ExchangeContext(ExchangeManager * em, uint16_t ExchangeId, cons
 ExchangeContext::~ExchangeContext()
 {
     VerifyOrDie(mExchangeMgr != nullptr && GetReferenceCount() == 0);
-    VerifyOrDie(!IsAckPending());
```
Comment (mrjerryjohns) [inline src/messaging/ExchangeContext.cpp:339]: I had to remove this to get the test to pass. I'm not sure why this is here @bzbarsky-apple ?

File: src/app/tests/TestCommandInteraction.cpp [hunk 2]
```diff
@@ -496,10 +496,15 @@ void TestCommandInteraction::TestCommandHandlerWithWrongState(nlTestSuite * apSu
...
-    commandHandler.mExchangeCtx.Grab(ctx.NewExchangeToAlice(&delegate));
+
+    auto exchange = ctx.NewExchangeToAlice(&delegate, false);
+    commandHandler.mExchangeCtx.Grab(exchange);
+
     err = commandHandler.SendCommandResponse();
 
     NL_TEST_ASSERT(apSuite, err == CHIP_ERROR_INCORRECT_STATE);
+
+    exchange->Close();
```
Comment (bzbarsky-apple) [inline src/app/tests/TestCommandInteraction.cpp:507]: This `Close` call is needed because this is not an initiator exchange so does not start with `WillSendMessage` when it's created?  If so, please document that here so people don't copy the patter in places where it is not appropriate.

File: src/app/tests/TestCommandInteraction.cpp [hunk 3]
```diff
@@ -580,6 +588,8 @@ void TestCommandInteraction::ValidateCommandHandlerWithSendCommand(nlTestSuite *
     err = invokeResponseMessageParser.CheckSchemaValidity();
     NL_TEST_ASSERT(apSuite, err == CHIP_NO_ERROR);
 #endif
+
+    exchange->Close();
```
Comment (bzbarsky-apple) [inline src/app/tests/TestCommandInteraction.cpp:592]: Again, please document.  And same in other places where we are doing this.

File: src/app/tests/TestCommandInteraction.cpp [hunk 4]
```diff
@@ -1295,8 +1317,7 @@ void TestCommandInteraction::TestCommandHandlerReleaseWithExchangeClosed(nlTestS
     // Verify that async command handle has been allocated
     NL_TEST_ASSERT(apSuite, asyncCommandHandle.Get() != nullptr);
 
-    // Close the exchange associated with the handle and verify the handle can be gracefully released
-    asyncCommandHandle.Get()->mExchangeCtx->Close();
+    // Close the handle and ensure it's handled correctly.
```
Comment (bzbarsky-apple) [inline src/app/tests/TestCommandInteraction.cpp:1320]: But that's not what this test was testing.  This test was testing that if something else closes the exchange (e.g. session release?) the async handle going off the stack doesn't misbehave.  It should keep testing that...  What it's testing after this change is not at all the same thing.

This is a must-fix.

File: src/messaging/ExchangeContext.cpp [hunk 5]
```diff
@@ -54,6 +54,8 @@ using namespace chip::Encoding;
 using namespace chip::Inet;
 using namespace chip::System;
 
+#define CHIP_EXCHANGE_CONTEXT_DETAIL_LOGGING 1
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeContext.cpp:57]: Is this meant to be checked in?

File: src/messaging/ExchangeContext.cpp [hunk 6]
```diff
@@ -139,12 +141,15 @@ CHIP_ERROR ExchangeContext::SendMessage(Protocols::Id protocolId, uint8_t msgTyp
...
+    // point below, the exchange is still in a mode of being ready to send a message again, as well as being setup
+    // correctly for delegates to know that they still need to release the ref on this exchange.
+    //
     if (!isStandaloneAck)
     {
-        // If we were waiting for a message send, this is it.  Standalone acks
-        // are not application-level sends, which is why we don't allow those to
-        // clear the WillSendMessage flag.
-        mFlags.Clear(Flags::kFlagWillSendMessage);
+        mFlags.Set(Flags::kFlagWillSendMessage);
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeContext.cpp:152]: Hmm.  So if I am responding to an incoming message and I try to send and fail, now it's my responsibility to explicitly close the exchange?  That's a change from the setup we had before (where the exchange would close unless there was a WillSend or a successful send), and I'm worried about it leaking for anyone who is not using SessionHolder.

Why do we need to do this, exactly?  So consumers don't have to think about whether they are responding to an incoming message or not when they get a failed send?

This needs an audit of existing SendMessage callers to make sure they are either using ExchangeHandle or following the new rules.  That is a must-fix.

File: src/messaging/ExchangeContext.cpp [hunk 7]
```diff
@@ -208,19 +213,37 @@ CHIP_ERROR ExchangeContext::SendMessage(Protocols::Id protocolId, uint8_t msgTyp
             return CHIP_ERROR_MISSING_SECURE_SESSION;
         }
 
+        CHIP_ERROR err;
+
+#if CONFIG_BUILD_FOR_HOST_UNIT_TEST
         // Create a new scope for `err`, to avoid shadowing warning previous `err`.
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeContext.cpp:219]: This comment does not make sense.  There is no scope.

File: src/messaging/ExchangeContext.cpp (hunk 1 above)
Comment (bzbarsky-apple) [inline src/messaging/ExchangeContext.cpp:339]: Why is this being removed?  We should not be ending up in a state where on destruction there is a pending ack; that means someone failed to flush acks correctly...

This is a must-fix.

File: src/messaging/ExchangeDelegate.h [hunk 8]
```diff
@@ -61,13 +61,13 @@ class ExchangeContext;
  *        on the exchange, then the exchange remains with you, and it's your responsibility to either send a message on it,
  *        or Close/Abort if you no longer wish to have the exchange around.
  *
- *     6. If you get a call to OnExchangeClosing, you should give up your reference to the exchange
- *        by 'nulling' out your reference to the exchange. The exchange will be automatically closed by the ExchangeMgr.
+ *     6. If you get a call to OnExchangeClosing, you should null out your reference to the exchange UNLESS you still
+ *        ownership of the exchange (i.e due to a prior call to WillSendMessage). In that case, you should call Abort/Close
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeDelegate.h:65]:
```suggestion
 *        hold ownership of the exchange (i.e due to a prior call to WillSendMessage). In that case, you should call Abort/Close
```

File: src/messaging/ExchangeDelegate.h [hunk 9]
```diff
@@ -61,13 +61,13 @@ class ExchangeContext;
...
+ *        whenever you're done with using the exchange. Those calls can be made synchronously within the OnExchangeClosing
+ *        callback.
  *
- *     6. If you get a call to OnResponseTimeout, you should give up your reference to the exchange
- *        by 'nulling' out your reference to the exchange UNLESS you intend to do further work on the exchange. If so,
- *        rules 2, 3 and 5 apply. Otherwise, the exchange will be automatically closed by the ExchangeMgr. Note that
- *        if the cause of the call is the release of the underlying session, attempts to send a message will result in failure.
+ *     6. If you get a call to OnResponseTimeout, you should null out your reference to the exchange since the exchange layer
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeDelegate.h:69]:
```suggestion
 *     7. If you get a call to OnResponseTimeout, you should null out your reference to the exchange since the exchange layer
```

File: src/messaging/ExchangeDelegate.h [hunk 10]
```diff
@@ -61,13 +61,13 @@ class ExchangeContext;
  *        on the exchange, then the exchange remains with you, and it's your responsibility to either send a message on it,
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeDelegate.h:61]: I think item 4 needs to change to "No message send attempts happened" or something, because of the behavior change in SendMessage where it sends the will-send flag...  It's very unclear whether "no messages were sent on that exchange" refers to SendMessage calls or actual messages going out.  Need to figure out how to document the behavior here clearly.

This is a must-fix.

File: src/messaging/ExchangeHolder.h [hunk 11]
```diff
@@ -33,12 +35,30 @@ namespace Messaging {
...
- *   (see AbortIfNeeded()).
+ *   An equivalent but simplified version of the rules around exchange management as specified in
+ *   ExchangeDelegate.h are provided here for consumers:
+ *
+ *   1. When an exchange is allocated, the holder takes over ownership of the exchange when Grab() is invoked.
+ *      Until a message is sent successfully, the holder will automatically manage the exchange until its
+ *      destructor or Release() is invoked.
+ *
+ *   2. If you send a message successfully that doesn't require a response, invoking Get() on the holder there-after will return
+ * nullptr.
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeHolder.h:46]:
```suggestion
 *   2. If you send a message successfully that doesn't require a response, invoking Get() on the holder there-after will return
 *      nullptr.
```

File: src/messaging/ExchangeHolder.h [hunk 12]
```diff
@@ -33,12 +35,30 @@ namespace Messaging {
...
+ *
+ *   3. If you send a message successfully that does require a response, invoking Get() on the holder will return a valid
+ *      pointer until the response is received.
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeHolder.h:49]: Or the the response times out, no?

File: src/messaging/ExchangeHolder.h [hunk 13]
```diff
@@ -33,12 +35,30 @@ namespace Messaging {
...
- *   This is a delegate forwarder - consumers can still register to be an ExchangeDelegate
- *   and get notified of all relevant happenings on that delegate interface.
+ *   5. If you invoke WillSendMessage() on the exchange in your implementation of OnMessageReceived indicating a desire to send a
+ * message later on the exchange, invoking Get() on the holder will return a valid exchange until SendMessage() on the exchange is
+ * called, at which point, rules 2 and 3 apply.
+ *
+ *   6. This is a delegate forwarder -  consumers can still register to be an ExchangeDelegate
+ *      and get notified of all relevant happenings on that delegate interface.
+ *
+ *   7. At no point shall you call Abort/Close/Release/Retain on the exchange tracked by the holder.
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeHolder.h:61]: This is why the unit tests that do just that should have comments.  ;)

File: src/messaging/ExchangeHolder.h [hunk 14]
```diff
@@ -20,6 +20,8 @@
 #include <lib/support/IntrusiveList.h>
 #include <messaging/ExchangeContext.h>
 
+#define CHIP_EXCHANGE_HOLDER_DETAIL_LOGGING 1
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeHolder.h:23]: Should this be enabled by default?

File: src/messaging/ExchangeMgr.h [hunk 15]
```diff
@@ -87,16 +87,17 @@ class DLL_EXPORT ExchangeManager : public SessionMessageDelegate
...
-     *  @param[in]    session    The identifier of the secure session (possibly
-     *                           the empty session for a non-secure exchange)
-     *                           for which the ExchangeContext is being set up.
+     *  @param[in]    session       The identifier of the secure session (possibly
+     *                              the empty session for a non-secure exchange)
+     *                              for which the ExchangeContext is being set up.
      *
-     *  @param[in]    delegate   A pointer to ExchangeDelegate.
+     *  @param[in]    delegate      A pointer to ExchangeDelegate.
+     *  @param[in]    isInitiator   Set to true if the exchange is created on the initiator.
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeMgr.h:95]: Maybe document that this should generally be true except for unit tests?

Or maybe we should have a unit-test-only thing for creating responder exchanges...

**Review by bzbarsky-apple — APPROVED** [review]
I did not have time to carefully review TestExchangeHolder.  Please make sure someone else does?

Approving so this is not blocked, but please make sure there "must-fix" items (the ones that have that phrase in the review comments) get fixed.

File: src/messaging/ExchangeContext.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/messaging/ExchangeContext.cpp:339]: If this assert is failing then ***someone did not close the exchange properly and it leaked***.  Probably because of the rules change for failing SendMessage under OnMessageReceived.

We have no other checks for exchanges leaking, if I recall correctly; the exchange manager does not assert that none leaked.  So if this is failing after this PR, then this PR introduced a leak.

Comment (bzbarsky-apple) [reply src/messaging/ExchangeContext.cpp:339]: See also https://github.com/project-chip/connectedhomeip/pull/21846#discussion_r944548034

File: src/app/tests/TestCommandInteraction.cpp (hunk 2 above)
Comment (mrjerryjohns) [reply src/app/tests/TestCommandInteraction.cpp:507]: That's right. Will add comments.

File: src/app/tests/TestCommandInteraction.cpp (hunk 4 above)
Comment (mrjerryjohns) [reply src/app/tests/TestCommandInteraction.cpp:1320]: Will fix.

File: src/messaging/ExchangeContext.cpp (hunk 5 above)
Comment (mrjerryjohns) [reply src/messaging/ExchangeContext.cpp:57]: I just placed it here for now so that I can debug any test failures that happen in CI. Once they all pass, I'll be removing this.

File: src/messaging/ExchangeContext.cpp (hunk 6 above)
Comment (mrjerryjohns) [reply src/messaging/ExchangeContext.cpp:152]: Wasn't the contract always that if `SendMessage` fails, that the caller has the responsibility of releasing the ref on the exchange? (i.e point # 2 in the rules section):

> If you send a message successfully that doesn't require a response, the ownership transfers to the ExchangeMgr, and it will close the exchange for you automatically.

Comment (mrjerryjohns) [reply src/messaging/ExchangeContext.cpp:152]: Will audit.

File: src/messaging/ExchangeContext.cpp (hunk 1 above)
Comment (mrjerryjohns) [reply src/messaging/ExchangeContext.cpp:339]: How exactly does it leak? Can you shed more details?

File: src/controller/python/test/test_scripts/base.py [hunk 16]
```diff
@@ -53,6 +53,7 @@
 
 def TestFail(message, doCrash=False):
     logger.fatal("Testfail: {}".format(message))
+    doCrash = False
```
Comment (andy31415) [inline src/controller/python/test/test_scripts/base.py:56]: Why is the input argument chanted? What is the purpose of such an argument if it is set to false anyway?

File: src/messaging/ExchangeContext.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/messaging/ExchangeContext.cpp:339]: > How exactly does it leak? Can you shed more details?

I'd have to debug to tell exactly what is leaking and how, but the upshot is that we are destroying an exchange (probably by destroying the pool it was allocated from) without having actually closed it (and therefore destroyed it via the normal "refcount goes to 0" codepath).

File: src/messaging/ExchangeContext.cpp (hunk 6 above)
Comment (bzbarsky-apple) [reply src/messaging/ExchangeContext.cpp:152]: > Wasn't the contract always that if SendMessage fails, that the caller has the responsibility of releasing the ref on the exchange? 

No, that was only if SendMessage fails when sending a message outside of incoming message processing.

File: src/messaging/ExchangeContext.cpp (hunk 1 above)
Comment (mrjerryjohns) [reply src/messaging/ExchangeContext.cpp:339]: So, the sequence of events in the unit-test that necessitated this was as follows:

1. Responder receives a message on an exchange.
2. Responder attempts to send a message on the exchange. We artificially inject an error that results in `SendMessage` failing.
3. That eventually results in the `ExchangeHolder` aborting the EC (since a failure to send means it is responsible to abort the EC). That results in a call to `DoClose`, which calls `FlushAcks`. That _also_ fails since we still have the 'inject failure' enabled on the EC. That prevents us from getting to `ExchangeMessageDispatch::SendMessage`, which is what would have cleared that ACK bit by calling `TakePendingPeerAckMessageCounter`.
4. The EC's destructor is called eventually, and VerifyOrDie triggers.

File: src/messaging/ExchangeContext.cpp (hunk 6 above)
Comment (mrjerryjohns) [reply src/messaging/ExchangeContext.cpp:152]: So, here's the coarse results of my audit of all callers to `SendMessage`:

1. `BdxOtaSender::HandleTransferSessionOutput`. This is not called from within `OnMessageReceived` processing, and is scheduled instead on a timer. The `TransferFacilitator` always calls `WillSendMessage` in its `OnMessageReceived` callback, further bolstering this. So this is not affected by this logic.
2. `BdxDownloader::HandleBdxEvent` calls `BDXDownloader::MessagingDelegate::SendMessage`, which the default impl of in `DefaultOTARequestor`, calls `ExchangeContext::SendMessage` and on error, will call `Close` on the EC. `HandleBdxEvent` is called from `PollTransferSession`, which is called from `OnMessageReceived`. Which means that this logic is actually already faulty relative to the existing assumptions...
3. `CASESession` and `PASESession` both adhere correctly to the existing assumptions. So that would need to get changed, assuming we follow through with the rules change.
4. IM logic use ExchangeHolders, so they're covered.

Comment (mrjerryjohns) [reply src/messaging/ExchangeContext.cpp:152]: Modulo the bugs that exist above, I'm fine removing this to return it back to the contract you've specified. That I think is the safest for now...

File: src/controller/python/test/test_scripts/base.py (hunk 16 above)
Comment (mrjerryjohns) [reply src/controller/python/test/test_scripts/base.py:56]: Hang over from running some tests. Will revert.

File: src/messaging/ExchangeDelegate.h (hunk 10 above)
Comment (mrjerryjohns) [reply src/messaging/ExchangeDelegate.h:61]: So, I've decided to revert the setting of the WillSendMessage flag early on in SendMessage. That hopefully makes this text relevant/correct again?

File: src/messaging/ExchangeContext.cpp (hunk 1 above)
Comment (mrjerryjohns) [reply src/messaging/ExchangeContext.cpp:339]: Causing a session to be released before calling `SendMessage` has the same resultant effect btw.

File: src/messaging/ExchangeContext.cpp (hunk 6 above)
Comment (mrjerryjohns) [reply src/messaging/ExchangeContext.cpp:152]: Removed this bit of logic.

File: src/messaging/ExchangeContext.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/messaging/ExchangeContext.cpp:339]: > Causing a session to be released before calling SendMessage has the same resultant effect btw.

Hmm.  Maybe we should clear the "ack pending" state if we try to send an ack and fail....  Because at that point we won't be able to send it sanely.

File: src/messaging/ExchangeContext.cpp (hunk 6 above)
Comment (bzbarsky-apple) [reply src/messaging/ExchangeContext.cpp]: > Which means that this logic is actually already faulty relative to the existing assumptions...

To be clear, calling Close there is safe, just not necessary.

File: src/app/tests/TestCommandInteraction.cpp [hunk 17]
```diff
@@ -496,10 +499,20 @@ void TestCommandInteraction::TestCommandHandlerWithWrongState(nlTestSuite * apSu
...
+    auto exchange = ctx.NewExchangeToAlice(&delegate, false);
+    commandHandler.mExchangeCtx.Grab(exchange);
+
     err = commandHandler.SendCommandResponse();
 
     NL_TEST_ASSERT(apSuite, err == CHIP_ERROR_INCORRECT_STATE);
+
+    //
+    // Ordinarily, the ExchangeContext will close itself upon sending the final message / error'ing out on a responder exchange
+    // when unwinding back from an OnMessageReceived callback. Since that isn't the case in this artificial setup here, we need
```
Comment (bzbarsky-apple) [inline src/app/tests/TestCommandInteraction.cpp:512]:
```suggestion
    // when unwinding back from an OnMessageReceived callback. Since that isn't the case in this artificial setup here (where we created a responder exchange that's not responding to anything), we need
```
and similar in other places in this file?

File: src/messaging/ExchangeDelegate.h (hunk 10 above)
Comment (bzbarsky-apple) [reply src/messaging/ExchangeDelegate.h:61]: Yes, that looks good.

File: src/messaging/ExchangeHolder.h [hunk 18]
```diff
@@ -33,12 +33,30 @@ namespace Messaging {
...
+ *
+ *   3. If you send a message successfully that does require a response, invoking Get() on the holder will return a valid
+ *      pointer until the response is received or times out.
+ *
+ *   4. On reception of a message on an exchange, if you return from OnMessageReceived() and no messages were sent on that exchange,
+ *      invoking Get() on the holder will return a nullptr.
+ *
+ *   5. If you invoke WillSendMessage() on the exchange in your implementation of OnMessageReceived indicating a desire to send a
+ * message later on the exchange, invoking Get() on the holder will return a valid exchange until SendMessage() on the exchange is
+ * called, at which point, rules 2 and 3 apply.
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeHolder.h:54]: Please fix the indent here to line up with the "If" after "5."

**Review by bzbarsky-apple — APPROVED** [review]

File: src/messaging/ExchangeContext.cpp (hunk 1 above)
Comment (mrjerryjohns) [reply src/messaging/ExchangeContext.cpp:339]: Since the crux of what this was checking was that `DoClose` got called before we got here, checking for the presence of the Closed flag is a more direct, clearer, and more encompassing check.

@bzbarsky-apple was good with this suggestion, so closing comment.

**Review by yunhanw-google — APPROVED** [review]
