### PR TITLE
[linux] Fire InternetConnectivityChange event when we get an IP address on wlan netif.

### LINKED ISSUE #3634: IP address not assigned on Wlan0 interface on raspi
IP address not assigned on Wlan0 interface on raspi after wifi is provisioned.

### LINKED ISSUE #4937: raspi :does not send IP address after connected to WiFi network in rendezvous session
Raspi hung up in network provisioning. Per spec, once the device provisioned with network credentials ,device BLE GAP connection should be terminated. 

chip-device-ctrl >  connect -ble 3840 12345678
CHIP: [BLE] NewConnection
CHIP: [BLE] CBManagerState: ON
CHIP: [BLE] Connecting to device with discriminator: 3840
CHIP: [BLE] Warning: OnBleConnectionComplete is called multiple times for the same peripheral.
CHIP: [BLE] subscribe complete, ep = 0x111e7a878
CHIP: [BLE] peripheral chose BTP version 3; central expected between 2 and 3
CHIP: [BLE] using BTP fragment sizes rx 20 / tx 128.
CHIP: [BLE] local and remote recv window size = 3
CHIP: [BLE] Sent PBKDF param request
CHIP: [BLE] Received pairing message from 12344321
CHIP: [BLE] Received pairing message for 112233
CHIP: [BLE] Received PBKDF param response
CHIP: [BLE] Sent spake2p msg1
CHIP: [BLE] Received pairing message from 12344321
CHIP: [BLE] Received pairing message for 112233
CHIP: [BLE] Received spake2p msg2
CHIP: [BLE] Sent spake2p msg3
CHIP: [IN] New pairing for device 12344321, key 0!!
CHIP: [CTL] Remote device completed SPAKE2+ handshake

CHIP: [NP] Sending Network Creds. Delegate 0x7f9ee101ea18

CHIP: [IN] Secure message was encrypted: Msg ID 0
CHIP: [IN] Sending msg from 112233 to 12344321
CHIP: [IN] Sending secure msg on connection specific transport
CHIP: [IN] Secure msg send status 0

--------------Device Side log--------------

CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Received rendezvous message for 12344321
CHIP:BLE: Received rendezvous message from 112233
CHIP:NP: Received kWiFiAssociationRequest.

CHIP:NP: LinuxNetworkProvisioningDelegate: SSID: Bewareofpython
CHIP:DL: wpa_supplicant: added network: SSID: Bewareofpython: /fi/w1/wpa_supplicant1/Interfaces/0/Networks/0
CHIP:DL: wpa_supplicant: connected to network: SSID: Bewareofpython
CHIP:DL: wpa_supplicant: failed to save config: GDBus.Error:fi.w1.wpa_supplicant1.UnknownError: Not allowed to update configuration (update_config=0)
CHIP:SVR: Device was assigned network credentials
CHIP:SVR: Device completed Rendezvous process
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70
CHIP:BLE: Indication confirmation, 0xffffa4023f70
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffa4023f70

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem
raspi :does not send IP address after connected to WiFi network in rendezvous session

 #### Summary of Changes
Create a thread and listen to netlink, Fire InternetConnectivityChange event when we get an IP address on wlan netif.

This feature is not required when we have mdns finished.

The method for calling dhclient is quite hacky, however, I don't have much idea about this, maybe we can call network manager which will take care of all of this on linux in the future.

 Fixes #4937
Fixes #3634

### CODE REVIEW

File: src/platform/Linux/PlatformManagerImpl.h [hunk 1]
```diff
@@ -67,6 +67,10 @@ class PlatformManagerImpl final : public PlatformManager, public Internal::Gener
 
     static PlatformManagerImpl sInstance;
 
+    // The temporary hack for getting IP address change on linux for network provisioning in the rendezvous session.
+    // This should be removed or find a better place once we deperate the rendezvous session.
```
Comment (bzbarsky-apple) [inline src/platform/Linux/PlatformManagerImpl.h:71]:
```suggestion
    // This should be removed or find a better place once we deprecate the rendezvous session.
```

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by erjiaqing** [comment]
@bzbarsky-apple Just added a call of dhclient after we connected to wifi, the solution of calling "system" is quite hacky, however, I don't have better ideas.
I guess we may need to switch to network manager on linux to avoid these matters (getting ips, calling dhclient, etc).

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
Generally I find the 'internet connectivity change' dodgy: when debugging ESP32 I found that it checked for ipv6 'internet connectivity' for example by filtering out link-local addresses.

However for provisioning purposes, link-local is fine. 

I added another 'ip address assigned' notification for that case. We may want to eventually standardise on that ... or repurpose "internet connectivity" to note that we do not really need real internet and it equates to having a LAN IP address.

**Review by jelderton — APPROVED** [review]
