### PR TITLE
Do not reset state if query image is not available (either not availa…

### LINKED ISSUE #25067: Do not reset OTA provider state if query image returns not available
Currently we reset state if a query image returns not available or the delegate returns busy or if protocol is not supported. This is incorrect behavior that we need to fix

### PR DESCRIPTION
**Pull request by nivi-apple**
…ble, or protocol not supported or if delegate returns busy)

Fixes #25067

### CODE REVIEW

**Review by carol-apple — APPROVED** [review]

File: src/protocols/bdx/TransferFacilitator.cpp [hunk 1]
```diff
@@ -102,6 +102,7 @@ CHIP_ERROR Responder::PrepareForTransfer(System::Layer * layer, TransferRole rol
 
     mPollFreq    = pollFreq;
     mSystemLayer = layer;
+    ChipLogProgress(BDX, "%s: Start polling for messages", __FUNCTION__);
```
Comment (bzbarsky-apple) [inline src/protocols/bdx/TransferFacilitator.cpp:105]: Please do not use __FUNCTION__ in device code.  It leads to very bloaty code.

But also, shouldn't this log line be down where the StartTimer call is?  Because if `WaitForTransfer` errors out, we are not in fact polling....

File: src/protocols/bdx/TransferFacilitator.cpp [hunk 2]
```diff
@@ -113,6 +114,7 @@ CHIP_ERROR Responder::PrepareForTransfer(System::Layer * layer, TransferRole rol
 void Responder::ResetTransfer()
 {
     mTransfer.Reset();
+    ChipLogProgress(BDX, "%s: Start polling for messages", __FUNCTION__);
```
Comment (bzbarsky-apple) [inline src/protocols/bdx/TransferFacilitator.cpp:117]: Stop, not start?

File: src/darwin/Framework/CHIP/MTROTAProviderDelegateBridge.mm [hunk 3]
```diff
@@ -132,6 +132,11 @@ void SetDelegate(id<MTROTAProviderDelegate> delegate, dispatch_queue_t delegateN
     void ResetState()
     {
         assertChipStackLockedByCurrentThread();
+        if (mNodeId.HasValue()) {
+            ChipLogProgress(Controller, "Resetting state for OTA Provider for node id %llu", mNodeId.Value());
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTROTAProviderDelegateBridge.mm:136]: This should log the fabric index too, probably.  And maybe:
```suggestion
            ChipLogProgress(Controller, "Resetting state for OTA Provider; no longer providing an update for node id %llu", mNodeId.Value());
```
or something?

File: src/protocols/bdx/TransferFacilitator.cpp (hunk 2 above)
Comment (nivi-apple) [reply src/protocols/bdx/TransferFacilitator.cpp:117]: ah :(

Comment (nivi-apple) [reply src/protocols/bdx/TransferFacilitator.cpp]: done

File: src/protocols/bdx/TransferFacilitator.cpp (hunk 1 above)
Comment (nivi-apple) [reply src/protocols/bdx/TransferFacilitator.cpp]: done.

File: src/darwin/Framework/CHIP/MTROTAProviderDelegateBridge.mm [hunk 4]
```diff
@@ -132,6 +132,13 @@ void SetDelegate(id<MTROTAProviderDelegate> delegate, dispatch_queue_t delegateN
     void ResetState()
     {
         assertChipStackLockedByCurrentThread();
+        if (mNodeId.HasValue() && mFabricIndex.HasValue()) {
+            ChipLogProgress(Controller,
+                "Resetting state for OTA Provider; no longer providing an update for node id %llu fabric index %llu",
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTROTAProviderDelegateBridge.mm:137]:
```suggestion
                "Resetting state for OTA Provider; no longer providing an update for node id %llu fabric index %u",
```

**Review by bzbarsky-apple — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

File: src/darwin/Framework/CHIP/MTROTAProviderDelegateBridge.mm [hunk 5]
```diff
@@ -132,6 +132,13 @@ void SetDelegate(id<MTROTAProviderDelegate> delegate, dispatch_queue_t delegateN
     void ResetState()
     {
         assertChipStackLockedByCurrentThread();
+        if (mNodeId.HasValue() && mFabricIndex.HasValue()) {
+            ChipLogProgress(Controller,
+                "Resetting state for OTA Provider; no longer providing an update for node id 0x" ChipLogFormatX64 "fabric index %u",
```
Comment (carol-apple) [inline src/darwin/Framework/CHIP/MTROTAProviderDelegateBridge.mm:137]:
```suggestion
                "Resetting state for OTA Provider; no longer providing an update for node id 0x" ChipLogFormatX64 ", fabric index %u",
```

**Review by Damian-Nordic — APPROVED** [review]
