### PR TITLE
Fix secure channel after removing node IDs from rendezvous

### LINKED ISSUE #5016: Device can't decrypt CHIP messages sent over UDP after merging #4945
#### Problem
After merging #4945, CHIP Python Controller is able to pair an accessory device successfully, but then the accessory is unable to decrypt ZCL messages. I use nRF Connect lock as the accessory, but the problem may be more generic.

Controller logs:
```
# Pairing
chip-device-ctrl > set-pairing-thread-credential 15 0x1234 00112233445566778899aabbccddeeff
Thread credential set
chip-device-ctrl > connect -ble 3840 12345678 12344321

CHIP:IN: New pairing for device 12344321, key 0!!
CHIP:CTL: Sender key: 13FBAE958E52E133BBE8DE0AC7B30CE9
CHIP:CTL: Receiver key: 38EEB0AF391397EB122F770C6E0B7C9A
CHIP:CTL: Remote device completed SPAKE2+ handshake
...
# Sending ZCL command:
chip-device-ctrl > zcl OnOff Off 12344321 1 1
CHIP:ZCL: Successfully encoded 11 bytes
CHIP:IN: Connection from 'UNDEFINED' expired
CHIP:CTL: OnConnectionExpired: Failed to process received message: err 4051
CHIP:IN: New pairing for device 12344321, key 0!!
CHIP:CTL: Sender key: 13FBAE958E52E133BBE8DE0AC7B30CE9
CHIP:CTL: Receiver key: 38EEB0AF391397EB122F770C6E0B7C9A
CHIP:CTL: Encrypt: D584B99681D1D50822227D2F987A3FB2B9893F46
CHIP:CTL:   AAD: 21230000000069B6010000000000015CBC00000000000000
CHIP:CTL:   KEY: 13FBAE958E52E133BBE8DE0AC7B30CE9
CHIP:CTL:   TAG: 2CD2BCB012D804360E1F5B7701C99CC4
CHIP:CTL:    IV: 69B601000000000000000000
```

Device:
```
# Pairing
E: 12751 [BLE]Missing node id in rendezvous parameters. Node ID is required until opcerts are implemented
D: 12760 [IN]New pairing for device lu, key 0!!
I: 12765 [CTL]Sender key: 38EEB0AF391397EB122F770C6E0B7C9A
I: 12770 [CTL]Receiver key: 13FBAE958E52E133BBE8DE0AC7B30CE9

# ZCL command received
I: 29109 [CTL]Decrypt:
I: 29111 [CTL]  AAD: 21230000000069B6010000000000015CBC00000000000000
I: 29118 [CTL]  KEY: 2C9F77161970145E3F2FDF88925B0238
I: 29122 [CTL]  TAG: 2CD2BCB012D804360E1F5B7701C99CC4
I: 29127 [CTL]   IV: 69B601000000000000000000
E: 29131 [CR]mbedTLS error: -15:
```

 #### Proposed Solution
Find the root cause, fix.

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
After merging #4945, CHIP Python Controller is able to pair an accessory device successfully, but then the accessory is unable to decrypt ZCL messages. The reason is that the PR dropped usage of node IDs (in PASE session) which are necessary to identify a correct encryption key.

 #### Summary of Changes
When nodeIDs are missing in CHIP messages use correct defaults to store encryption keys exchanged during the rendezvous session.

 Fixes #5016

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

File: src/transport/RendezvousSession.cpp [hunk 1]
```diff
@@ -179,7 +179,9 @@ void RendezvousSession::OnSessionEstablished()
     {
         ChipLogError(Ble, "Missing node id in rendezvous parameters. Node ID is required until opcerts are implemented");
     }
-    mPairingSession.PeerConnection().SetPeerNodeId(mParams.GetRemoteNodeId().ValueOr(kUndefinedNodeId));
+
+    const auto defaultPeerNodeId = mParams.IsController() ? kTestDeviceNodeId : kTestControllerNodeId;
```
Comment (andy31415) [inline src/transport/RendezvousSession.cpp:183]: This seems to hardcode node ids.
Is there some other workaround here - this is very odd.

**Review by andy31415 — APPROVED** [review]
Approving because we likely need a fix for TE1.

However also for TE1, we probably expect devices to not use hardcoded nonde ids.
The removal of nodeids was intended exactly to highlight these kind of dependencies and adding them back seems problematic.

File: src/transport/RendezvousSession.cpp (hunk 1 above)
Comment (andy31415) [reply src/transport/RendezvousSession.cpp:183]: I believe I had to preserve the peer node id during message sending on rendezous so I would expect the remote node id to be available during communication.

Could we use that instead of having this IsController?

in any case this requires a large 'TODO: this needs replacement' if it actually goes in.

Comment (Damian-Nordic) [reply src/transport/RendezvousSession.cpp:183]: @andy31415 Did you intentionally remove "source node id" from messages sent by the commissioner? If so, there's currently no other way to initialize it properly other than hard coding. Once we have CASE sessions implemented, we may no longer need to know for which node ID a given encryption key was added, but now we do need this information.

Comment (Damian-Nordic) [reply src/transport/RendezvousSession.cpp:183]: Actually, I can see that you moved setting source Node ID to `RendezvousSession`, so in theory `PASESession` could set `mConnectionState.SetPeerNodeId` on receipt of the session establishment message...

**Review by jelderton — APPROVED** [review]

**Comment by mspang** [comment]
> Approving because we likely need a fix for TE1.
> 
> However also for TE1, we probably expect devices to not use hardcoded nonde ids.
> The removal of nodeids was intended exactly to highlight these kind of dependencies and adding them back seems problematic.

So what's your plan then? I thought your change wasn't meant to be a functional change, but now it turns out it did.

Are we backsliding here? Perhaps we should back out that change.

**Comment by pan-apple** [comment]
I tried the same use case with iOS CHIPTool, and it works fine. I understand that the behavior over PASE is not per spec (i.e. using/assigning the NodeIDs). Since the current change is temporary to support TE1, maybe we can mimic in Python control what iOS CHIPTool is doing as a stop gap solution.

File: src/transport/RendezvousSession.cpp (hunk 1 above)
Comment (msandstedt) [reply src/transport/RendezvousSession.cpp:183]: I thought the whole point of removing the source IDs from the PASE code paths is that in PASE world, node IDs are not authenticated, and so much less meaningful.  Wouldn't the 'correct' thing to do here be to store the session encryption keys in the session object itself and pass this around?

It seems wrong to index the keys on Node ID when anybody can claim any Node ID during PASE.  The only thing that is authenticated is that a peer, whomever they are, at the end of some known channel (BLE, peer/peer IP tuple or whatever), are in possession of a shared secret.  Using the session object would seem to key to this more directly and could avoid some odd DOS situations (or worse) where another party also claims during PASE to have the same node ID.

Comment (Damian-Nordic) [reply src/transport/RendezvousSession.cpp:183]: You may be right, however if you look into the current implementation of `SecureSessionMgr::OnMessageReceived` you will see that the key used for decryption of the message is selected based on the source node ID from that message. So until we don't align this part with the spec we must ensure that the `nodeID -> connection state/encryption key` mapping is correctly initialized and that is not the case. I'm OK either with merging my quick fix or reverting the changes which break the previous behavior and working out a better solution, but the point is that the issue is blocking some devs and test autiomation engineers, so we should somehow address it quickly :)

Comment (msandstedt) [reply src/transport/RendezvousSession.cpp:183]: Reverting the other PR seems like a move in the wrong direction.

Thanks for the explanation. Looks good to me.

**Review by msandstedt — APPROVED** [review]

**Comment by andy31415** [comment]
> I tried the same use case with iOS CHIPTool, and it works fine. I understand that the behavior over PASE is not per spec (i.e. using/assigning the NodeIDs). Since the current change is temporary to support TE1, maybe we can mimic in Python control what iOS CHIPTool is doing as a stop gap solution.

Indeed, I think I matched some C++ code since I needed chip-tool to work, however I may not have used python. I believe this requires some secondary passes or we wait until we have proper pase/case and then nodeid should be set at the proper time (i.e at opcreds setup time)

**Comment by andy31415** [comment]
> > Approving because we likely need a fix for TE1.
> > However also for TE1, we probably expect devices to not use hardcoded nonde ids.
> > The removal of nodeids was intended exactly to highlight these kind of dependencies and adding them back seems problematic.
> 
> So what's your plan then? I thought your change wasn't meant to be a functional change, but now it turns out it did.
> 
> Are we backsliding here? Perhaps we should back out that change.

Agree, it was not meant to break things (but it did ... unfortunately I only tested command line chip tool).
I specifically kept some pieces of code with nodeid with 'TODO' in place to change it once appropriate and assumed I highlighted all awkward cases. Apparently this PR shows that we had one extra place that needs to be awkward, which is unfortunate.
