### PR TITLE
Remove duplicate logic to cleanup FailSafeContext

### LINKED ISSUE #16814: We should have the event posting and SetFailSafeBusy all be inside the fail-safe
#### Problem
[src/include/platform/internal/GenericConfigurationManagerImpl.ipp](https://github.com/project-chip/connectedhomeip/pull/16497/files/026092850b6409d7a3b6be154d5c2a015dc649c7#diff-35014e72042d8bbaac1bb351f830d93f364c7e10bf505418460f382a014ce36f)
        err = PlatformMgr().PostEvent(&event);
        SuccessOrExit(err);

        DeviceControlServer::DeviceControlSvr().GetFailSafeContext().SetFailSafeBusy(true);
 
Member
@[bzbarsky-apple](https://github.com/bzbarsky-apple) bzbarsky-apple [2 hours ago](https://github.com/project-chip/connectedhomeip/pull/16497#discussion_r838084627)
As a followup: We should still have the event posting and SetFailSafeBusy all be inside the fail-safe, so we don't duplicate this logic.

 #### Proposed Solution
<suggested fix, suggested enhancement>

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
What is being fixed?  Examples:
* We should have the event posting and SetFailSafeBusy all be inside the fail-safe, so that we don't have duplicated logic to do the FailSafeContext cleanup.

* Fixes #16814

#### Change overview
Have the event posting and SetFailSafeBusy all be inside the fail-safe,

#### Testing
How was this tested? (at least one bullet point required)
* No logic change, merging duplicated logic to function ScheduleFailSafeCleanup()

### CODE REVIEW

**Review by msandstedt — APPROVED** [review]

File: src/include/platform/FailSafeContext.h [hunk 1]
```diff
@@ -44,6 +44,13 @@ class FailSafeContext
     CHIP_ERROR SetAddNocCommandInvoked(FabricIndex nocFabricIndex);
     CHIP_ERROR SetUpdateNocCommandInvoked(FabricIndex nocFabricIndex);
 
+    /**
+     * @brief
+     *   Schedules a work to cleanup the FailSafe Context asynchronously after various cleanup work
```
Comment (bzbarsky-apple) [inline src/include/platform/FailSafeContext.h:49]:
```suggestion
     *   Schedules a call to cleanup the FailSafe Context asynchronously after various cleanup work
```

File: src/platform/FailSafeContext.cpp [hunk 2]
```diff
@@ -76,8 +76,12 @@ void FailSafeContext::FailSafeTimerExpired()
         ChipLogError(DeviceLayer, "Failed to post fail-safe timer expired: %" CHIP_ERROR_FORMAT, status.Format());
     }
 
-    mFailSafeBusy = true;
+    ScheduleFailSafeCleanup();
```
Comment (bzbarsky-apple) [inline src/platform/FailSafeContext.cpp:79]: Here's the question.  Why can't the PostEvent be inside that function too?

That is, make the function take the fabric index and the two booleans as arguments, call it here with our members, call it in configuration manager with the deserialized state, have the function set mFailSafeArmed/mAddNocCommandHasBeenInvoked/mUpdateNocCommandHasBeenInvoked to false, set mFailSafeBusy to true, post the event, schedule the HandleDisarmFailSafe.

Comment (yufengwangca) [reply src/platform/FailSafeContext.cpp]: Acked

**Review by tcarmelveilleux — APPROVED** [review]
