### PR TITLE
Fix crashes when closing all exchanges for fabric.

### LINKED ISSUE #19747: Use-after-free when aborting already-closed exchange
#### Problem
I tried using the code added in #19328 in RemoveFabric, and ran into crashes in the following scenario:

1. There is an exchange on the server that has been closed but is still waiting for an ack.  It's held alive by a single reference from the retransmission table.
2. A new command comes in that calls into the `AbortExchangesForFabricExceptOne` API from #19328 (in my case RemoveFabric).

`AbortExchangesForFabricExceptOne` ends up looping through all live exchanges, and the exchange waiting for an ack is live.  It calls `Abort()` on the exchanges.  `Abort()` does the following, in order:

1. Notifiies the delegate.
2. Flushes acks.
3. Removes the exchange from the retrans table.
4. Tries to cancel the response timer, which uses members of the exchange.
5. Calls `Release()`.

In this case, after step 3 our object is dead because the last ref got dropped, and at step 4 we crash.  But even if we held an extra ref on the stack to keep it alive through step 4, the unbalanced `Release()` in step 5 would mean we end up refcounting a dead object at some point.

 #### Proposed Solution
I think we need to do something smarter than calling `Abort` on all existing exchanges for the fabric, in terms of managing the exchange refcounts.  In particular, I would propose we do the following:

1. For exchanges that are not on the one session we are keeping around, do nothing, because marking those sessions for removal will deal with the exchanges on them correctly already.
2. For exchanges that _are_ on the session we are keeping around, ideally call SessionReleased on their SessionHolder if we can manage it, to mimic what would happen if the session were actually getting released. If we can't manage that, call `OnSessionReleased` on the exchange itself, which I think might be good enough: it might retain the reference to the session if it does not die (because the app is holding on to it), but future OnSessionReleased calls on it would be no-ops because it won't be in the retrans table anymore.  In particular, `OnSessionReleased` already handles the various refcounting scenarios correctly.

Another possibility is that instead of having an API on the exchange manager here we have an API on secure session which is basically "notify all holders except this given one that you are going away", plus an API on exchange that:
1. Nukes all sessions except the exchange's session for the exchange's fabric, using the session manager API from #19328.
2. Calls the session API to notify all holders except the exchange's holder.
3. Flags the exchange itself to mark the session for removal when the exchange is destroyed.

@kghost @mrjerryjohns I actually kind of like that last idea...  It funnels as much as possible through existing, tested, code paths in terms of the exchange-termination behavior.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Our "close all exchanges except this special one for this fabric" API
messes up exchange refcounting, leading to use-after-free.

The fix is to reuse, as much as possible, the normal "session is going
away" flow to notify exchanges, and other session consumers, that the
sessions are in fact going away.

Fixes https://github.com/project-chip/connectedhomeip/issues/19747

#### Problem
See #19747.

#### Change overview
See above: we make this special operation look as much as possible like all the relevant sessions being marked for removal in the normal way.

#### Testing
Tests added that test various scenarios. Without this PR (using the old exchange manager API) those tests fail with all sorts of use-after-free issues.

### CODE REVIEW

File: src/messaging/ExchangeContext.cpp [hunk 1]
```diff
@@ -326,7 +326,13 @@ ExchangeContext::~ExchangeContext()
     VerifyOrDie(!IsAckPending());
 
     if (ReleaseSessionOnDestruction() && mSession)
-        mSession->AsSecureSession()->MarkForRemoval();
+    {
+        // Move the session out of the older for the removal, so it doesn't try
+        // to notify us in our destructor.
+        const auto & session = mSession.Get();
```
Comment (kghost) [inline src/messaging/ExchangeContext.cpp:332]:
```suggestion
        const Optional<SessionHandle> session = mSession.Get();
```

Get returns a temporary variable, I'm not confident that it is lives long enough. We should use a value to hold it.

File: src/messaging/ExchangeContext.cpp [hunk 2]
```diff
@@ -573,5 +579,19 @@ ExchangeMessageDispatch & ExchangeContext::GetMessageDispatch(bool isEphemeralEx
     return ApplicationExchangeDispatch::Instance();
 }
 
+void ExchangeContext::AbortAllOtherCommunicationOnFabric()
+{
+    if (!mSession || !mSession->IsSecureSession())
+    {
+        return;
+    }
```
Comment (kghost) [inline src/messaging/ExchangeContext.cpp:587]:
```suggestion
    VerifyOrDie(mSession && mSession->IsSecureSession());
```

Can it die here ?

If this check fails, it probably doesn't work as caller expects.

Comment (bzbarsky-apple) [reply src/messaging/ExchangeContext.cpp:587]: I agree it probably does not work as caller expects, but I am also a little leery of dying in public APIs.  We _could_ add error logging, though; might be a good idea.

File: src/transport/SecureSession.h [hunk 3]
```diff
@@ -170,8 +170,12 @@ class SecureSession : public Session, public ReferenceCounted<SecureSession, Sec
      */
     void MarkAsDefunct();
 
-    // Used to prevent any new exchange created on the session while the existing exchanges finish their work.
-    void MarkInactive();
+    // Used to make the session look like it's being released, while allowing
+    // the passed-in holder (which must be holding this session) to continue
+    // holding it for now until it completes the work it's going.  This API also
```
Comment (msandstedt) [inline src/transport/SecureSession.h:175]:
```suggestion
    // holding it for now until it completes the work it's doing.  This API also
```

Comment (bzbarsky-apple) [reply src/transport/SecureSession.h]: Good catch, fixed.

File: src/messaging/ExchangeMgr.cpp [hunk 4]
```diff
@@ -236,7 +236,14 @@ void ExchangeManager::OnMessageReceived(const PacketHeader & packetHeader, const
                         packetHeader.GetDestinationGroupId().Value());
     }
 
-    // Do not handle unsolicited messages on a inactive session.
+    // Do not handle messages that don't match an existing exchange on a
+    // inactive session, since we should not be creating new exchanges there.
```
Comment (msandstedt) [inline src/messaging/ExchangeMgr.cpp:240]:
```suggestion
    // Do not handle messages that don't match an existing exchange on an
    // inactive session, since we should not be creating new exchanges there.
```

File: src/transport/SecureSession.cpp [hunk 5]
```diff
@@ -144,12 +151,18 @@ void SecureSession::MarkInactive()
     case State::kDefunct:
         FALLTHROUGH;
     case State::kActive:
+        // Make sure we don't notify "deferred" that we're being removed.  This
+        // ensures that "deferred" is in fact in our holder list.
+        RemoveHolder(deferred);
```
Comment (msandstedt) [inline src/transport/SecureSession.cpp:156]: What happens if we pass a random holder that wasn't in our list (i.e. not pointing to this at all) in the first place?

File: src/transport/SecureSession.h [hunk 6]
```diff
@@ -170,8 +171,12 @@ class SecureSession : public Session, public ReferenceCounted<SecureSession, Sec
      */
     void MarkAsDefunct();
 
-    // Used to prevent any new exchange created on the session while the existing exchanges finish their work.
-    void MarkInactive();
+    // Used to make the session look like it's being released, while allowing
+    // the passed-in holder (which must be holding this session) to continue
```
Comment (msandstedt) [inline src/transport/SecureSession.h:175]: > (which must be holding this session)

Is it possible to have logic that enforces this?

File: src/messaging/ExchangeMgr.cpp (hunk 4 above)
Comment (bzbarsky-apple) [reply src/messaging/ExchangeMgr.cpp:240]: Done.

File: src/transport/SecureSession.cpp (hunk 5 above)
Comment (bzbarsky-apple) [reply src/transport/SecureSession.cpp:156]: Then this will crash.  Since the only callsite for this should be the exchange context, that should not be an issue in practice....

File: src/transport/SecureSession.h (hunk 6 above)
Comment (bzbarsky-apple) [reply src/transport/SecureSession.h:175]: We crash if that's not the case.

**Review by msandstedt — APPROVED** [review]

File: src/messaging/ExchangeContext.cpp [hunk 7]
```diff
@@ -573,5 +579,20 @@ ExchangeMessageDispatch & ExchangeContext::GetMessageDispatch(bool isEphemeralEx
     return ApplicationExchangeDispatch::Instance();
 }
 
+void ExchangeContext::AbortAllOtherCommunicationOnFabric()
```
[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/messaging/ExchangeContext.cpp:582]: ExchangeMgr would be a better bet honestly barring the above suggestion.

File: src/transport/SecureSession.cpp [hunk 8]
```diff
@@ -144,12 +151,18 @@ void SecureSession::MarkInactive()
...
         // By setting this state, IsActiveSession() will return false, which prevents creating new exchanges.
-        mState = State::kInactive;
+        MoveToState(State::kInactive);
+        NotifySessionReleased();
```
Comment (mrjerryjohns) [inline src/transport/SecureSession.cpp:159]: Why is this necessary? When a session is marked for release, it's not strictly necessary that you detach all existing holders right? That can happen later when the session _actually_ gets marked for eviction no?

As long as we prevent new exchanges from being created on the in-active session, that's what matters I'd think...

File: src/transport/SessionManager.cpp [hunk 9]
```diff
@@ -532,7 +532,7 @@ void SessionManager::SecureUnicastMessageDispatch(const PacketHeader & packetHea
 
     Transport::SecureSession * secureSession = session.Value()->AsSecureSession();
 
-    if (!secureSession->IsDefunct() && !secureSession->IsActiveSession())
+    if (!secureSession->IsDefunct() && !secureSession->IsActiveSession() && !secureSession->IsInactive())
```
Comment (mrjerryjohns) [inline src/transport/SessionManager.cpp:535]: Perhaps a comment should be added here explaining why we're letting inactive sessions to still be processed, because to a layman reader, doing this doesn't make a ton of sense no?

File: src/messaging/ExchangeContext.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/messaging/ExchangeContext.cpp:582]: So the reason this is on the ExchangeContext is because that's the entity that has the one special SessionHolder that we want to exempt from eviction....

[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/messaging/ExchangeContext.cpp:582]: See [this](https://github.com/project-chip/connectedhomeip/pull/19780#discussion_r902976774) comment.

File: src/transport/SecureSession.cpp (hunk 8 above)
Comment (bzbarsky-apple) [reply src/transport/SecureSession.cpp:159]: We need to detach all existing exchanges (except our special one) that happen to be using this session already.

We can either do that via notifying them the session is gone, or by telling the exchanges something directly.  This does the former, because that's a tested codepath that we use elsewhere anyway.  We could do that latter, but it means more codepaths to maintain, test, and reason about...

Comment (bzbarsky-apple) [reply src/transport/SecureSession.cpp:159]: Yes, per spec those exchanges need to die immediately.  e.g. if we're in the middle of a chunked read, it needs to stop delivering data, no?

**Review by woody-apple — APPROVED** [review]

File: src/transport/SecureSession.cpp (hunk 8 above)
Comment (mrjerryjohns) [reply src/transport/SecureSession.cpp:159]: Does the spec actually say exchanges need to die immediately?

> > All internal data reflecting the prior operational identifier of the Node within the Fabric SHALL be revoked and removed, to an outcome equivalent to the disappearance of the prior Node, except for the ongoing CASE session context, which SHALL temporarily remain valid until the NOCResponse has been successfully delivered or until the next transport-layer error, so that the response can be received by the Administrator invoking the command.

I guess it kinda does...

File: src/messaging/ExchangeContext.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/messaging/ExchangeContext.cpp:582]: > that's the entity that has the one special SessionHolder that we want to exempt from eviction....

Can't you not extract the `mSession` from that through a getter and implement all of this same bits of logic in `ExchangeManager`?

[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/messaging/ExchangeContext.cpp:582]: We _could_ extract it through a getter.  Then we'd need to keep the public setter for the "tear down the session when this exchange goes away" bit (which becomes non-public in this PR).

I can go either way, but I was trying to minimize the number of footgun APIs.  At least this one I am adding corresponds to a clear spec-defined operation...

**Review by mrjerryjohns — APPROVED** [review]

File: src/messaging/ExchangeContext.cpp [hunk 10]
```diff
@@ -573,5 +575,31 @@ ExchangeMessageDispatch & ExchangeContext::GetMessageDispatch(bool isEphemeralEx
...
+{
+    if (!mSession || !mSession->IsSecureSession())
+    {
+        ChipLogError(ExchangeManager, "AbortAllOtherCommunicationOnFabric called when we don't have a PASE/CASE session");
+        return;
+    }
+
+    // Save our session so it does not actually go away.
+    Optional<SessionHandle> session = mSession.Get();
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/messaging/ExchangeContext.cpp:587]: It can't, because we can't get our hands on a vanilla handle: it has no copy constructor.  `Get()` returns an `Optional` and we are moving out of it here, but if we tried to get the handle itself this would not compile.

[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/messaging/ExchangeContext.cpp:587]: Let's just keep it as is to get the PR in.

**Review by msandstedt — APPROVED** [review]
