### PR TITLE
[ESP32] Fix incorrect RTC log format in SystemTimeSupport

### LINKED ISSUE #1269: TimeSynchronizationCluster: Wrong epoch time conversion ? (CON-1539)
**Describe the bug**
When we set the UTC time of a node running on esp32, the time being set seems to be wrong (or wrongly displayed).

For example:

```
I (2248785) chip[TS]: Last Known Good Time: 2025-02-05T17:51:33
I (2248788) chip[TS]: New proposed Last Known Good Time: 2025-02-05T17:51:33
I (2248796) chip[TS]: Updating Last Known Good Time to 2025-02-05T17:51:33
I (2248804) chip[DL]: Real time clock set to 1738777893 (0125/01/05 17:51:33 UTC)
```

The problem is on this line:

```
I (2248804) chip[DL]: Real time clock set to 1738777893 (0125/01/05 17:51:33 UTC)
```

**Environment**
FireBeetle 2 ESP32-C6

**Any additional details**
1. Use any simple example and enable `CONFIG_ENABLE_SNTP_TIME_SYNC`
2. Configure the example to implement the TimeSynchronization cluster:

```
// Time sync
#include <app/clusters/time-synchronization-server/time-synchronization-server.h>
#include <app/clusters/time-synchronization-server/DefaultTimeSyncDelegate.h>
#include <app-common/zap-generated/callback.h>

void main(void)
{
....
    endpoint_t *root_node_ep = endpoint::get_first(node);
    ABORT_APP_ON_FAILURE(root_node_ep != nullptr, ESP_LOGE(TAG, "Failed to find root node endpoint"));

    cluster::time_synchronization::config_t time_sync_cfg;
    static chip::app::Clusters::TimeSynchronization::DefaultTimeSyncDelegate time_sync_delegate;
    time_sync_cfg.delegate = &time_sync_delegate;
    cluster_t *time_sync_cluster = cluster::time_synchronization::create(root_node_ep, &time_sync_cfg, CLUSTER_FLAG_SERVER);
    ABORT_APP_ON_FAILURE(time_sync_cluster != nullptr, ESP_LOGE(TAG, "Failed to create time_sync_cluster"));

    cluster::time_synchronization::feature::time_zone::config_t tz_cfg;
    cluster::time_synchronization::feature::time_zone::add(time_sync_cluster, &tz_cfg);
...
}
```
3. Commission the device using chiptool
4. Send a command "SetUTCTime" to the device:
```
# WARNING: The UTC time is passed as microseconds, but it must be the difference between NOW and 1st January 2000
# Be carefull here, it's not unix timestamp
chip-tool timesynchronization set-utctime 792093093930488 4 1 0
```

Here a simple tool to get the compatible epoch time:

```
#!/bin/bash

now=$(date +%s%6N)
epoch_2000=$(date -d "2000-01-01 00:00:00" +%s%6N)
diff=$((now - epoch_2000))
echo "$diff"
```

It's possible that the problem is due to a wrong conversion: Matter specifications says, they use epoch us based on 2000-01-01, (it's not unix timestamp)

Currently I don't know where the problem is (stack: platform code for esp32, esp-matter ?)

### PR DESCRIPTION
**Pull request by pimpalemahesh**
#### Problem  
Fixes espressif/esp-matter#1269  

The `tm_year` and `tm_mon` values were being logged incorrectly, resulting in an invalid date format.  

#### Changes  
- Used strftime() for formatting utc time.

#### Testing  
- Verified the fix by setting the RTC time using the Time Synchronization cluster through `chip-tool` and checking the log output.  
- Logs now correctly reflect the expected timestamp format.

### CODE REVIEW

**Review by dhrishi — APPROVED** [review]

File: src/platform/ESP32/SystemTimeSupport.cpp [hunk 1]
```diff
@@ -95,8 +95,8 @@ CHIP_ERROR ClockImpl::SetClock_RealTime(Microseconds64 aNewCurTime)
         struct tm calendar;
         localtime_r(&timep, &calendar);
         ChipLogProgress(DeviceLayer, "Real time clock set to %lld (%04d/%02d/%02d %02d:%02d:%02d UTC)",
-                        static_cast<long long>(tv.tv_sec), calendar.tm_year, calendar.tm_mon, calendar.tm_mday, calendar.tm_hour,
-                        calendar.tm_min, calendar.tm_sec);
+                        static_cast<long long>(tv.tv_sec), calendar.tm_year + 1900, calendar.tm_mon + 1, calendar.tm_mday,
```
Comment (wqx6) [inline src/platform/ESP32/SystemTimeSupport.cpp:98]: Could we use `strftime()` here to format the `calendar`?

**Review by wqx6 — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
