### PR TITLE
Import identify, barrier and scene-client clusters

### LINKED ISSUE #2051: Import ../third_party/connectedhomeip/src/app/clusters/barrier-control-server
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

### LINKED ISSUE #2059: Import ../third_party/connectedhomeip/src/app/clusters/identify
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

### LINKED ISSUE #2065: Import ../third_party/connectedhomeip/src/app/clusters/scenes-client
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

### PR DESCRIPTION
**Pull request by bhaskar-apple**
#### Problem
Import identify, barrier and scene-client clusters

 #### Summary of Changes
Uncomment relevant parts of component.mk and fix up code as needed to get it to compile & link.

fixes #2065, #2059, #2051

### CODE REVIEW

File: examples/wifi-echo/server/esp32/main/gen/clusters-callback-stubs.c [hunk 1]
```diff
@@ -722,20 +745,20 @@ bool emberAfIasZoneClusterZoneStatusChangeNotificationCallback(uint16_t zoneStat
  *
  * @param identifyTime   Ver.: always
  */
-bool emberAfIdentifyClusterIdentifyCallback(uint16_t identifyTime)
-{
-    return false;
-}
+// bool emberAfIdentifyClusterIdentifyCallback(uint16_t identifyTime)
```
Comment (rwalker-apple) [inline examples/wifi-echo/server/esp32/main/gen/clusters-callback-stubs.c:748]: please just delete these.  they were placed in this file by me to enable a "plugin-oriented" gen/ directory to be able to link with no plugins in the build

Comment (rwalker-apple) [reply examples/wifi-echo/server/esp32/main/gen/clusters-callback-stubs.c:748]: in fact this whole file should end up empty and should be deleted after we've finished the port

File: src/app/clusters/barrier-control-server/barrier-control-server-cli.c [hunk 2]
```diff
@@ -37,6 +37,7 @@
  *******************************************************************************
  ******************************************************************************/
 
+#if 0
```
Comment (rwalker-apple) [inline src/app/clusters/barrier-control-server/barrier-control-server-cli.c:40]: better to remove this file than to comment it out.  we can resurrect it trivially when needed

File: src/app/clusters/barrier-control-server/barrier-control-server.c [hunk 3]
```diff
@@ -41,8 +41,14 @@
 #include "barrier-control-server.h"
 #include "af.h"
 
+#include <assert.h>
+
+#ifndef MILLISECOND_TICKS_PER_DECISECOND
+#define MILLISECOND_TICKS_PER_DECISECOND 1000
```
Comment (rwalker-apple) [inline src/app/clusters/barrier-control-server/barrier-control-server.c:47]: @bzbarsky-apple had a better plan for this than redefinition in every source file

File: src/app/clusters/identify/identify-cli.c [hunk 4]
```diff
@@ -44,7 +44,8 @@
 // * Copyright 2012 by Ember Corporation. All rights reserved.              *80*
 // *******************************************************************
 
-#include "app/framework/include/af.h"
+#if 0
```
Comment (rwalker-apple) [inline src/app/clusters/identify/identify-cli.c:47]: again, I think: just delete this file

File: src/app/clusters/scenes-client/scenes-client.c [hunk 5]
```diff
@@ -39,7 +39,7 @@
  ******************************************************************************/
 
 #include "scenes-client.h"
-#include "../../include/af.h"
+#include "af.h"
```
Comment (rwalker-apple) [inline src/app/clusters/scenes-client/scenes-client.c:42]: I think we should be using the chip include path for these, since they're compiled by applications against the CHIP tree.

recommend
```
#include <app/util/af.h>
```

File: src/app/util/util.c [hunk 6]
```diff
@@ -1400,3 +1400,19 @@ uint8_t emberAfMake8bitEncodedChanPg(uint8_t page, uint8_t channel)
         return channel | ENCODED_8BIT_CHANPG_PAGE_MASK_PAGE_0;
     }
 }
+
+EmberStatus emberAfScheduleServerTick(uint8_t endpoint, EmberAfClusterId clusterId, uint32_t delayMs)
```
Comment (rwalker-apple) [inline src/app/util/util.c:1404]: excellent

**Review by mspang — APPROVED** [review]

File: examples/wifi-echo/server/esp32/main/gen/clusters-callback-stubs.c (hunk 1 above)
Comment (bzbarsky-apple) [inline examples/wifi-echo/server/esp32/main/gen/clusters-callback-stubs.c:748]: Again, would prefer `#if 0`.

File: examples/wifi-echo/server/esp32/main/gen/clusters-callback-stubs.c [hunk 7]
```diff
@@ -722,20 +745,20 @@ bool emberAfIasZoneClusterZoneStatusChangeNotificationCallback(uint16_t zoneStat
...
 /** @brief Identify Cluster Identify Query
  *
  *
  *
  */
-bool emberAfIdentifyClusterIdentifyQueryCallback(void)
-{
-    return false;
-}
+// bool emberAfIdentifyClusterIdentifyQueryCallback(void)
```
Comment (bzbarsky-apple) [inline examples/wifi-echo/server/esp32/main/gen/clusters-callback-stubs.c:758]: `#if 0`

File: examples/wifi-echo/server/esp32/main/gen/clusters-callback-stubs.c [hunk 8]
```diff
@@ -1030,11 +1053,11 @@ EmberAfStatus emberAfIasZoneClusterServerPreAttributeChangedCallback(uint8_t end
 {
     return EMBER_ZCL_STATUS_SUCCESS;
 }
-void emberAfIdentifyClusterServerAttributeChangedCallback(uint8_t endpoint, EmberAfAttributeId attributeId) {}
-void emberAfIdentifyClusterServerInitCallback(uint8_t endpoint) {}
+// void emberAfIdentifyClusterServerAttributeChangedCallback(uint8_t endpoint, EmberAfAttributeId attributeId) {}
+// void emberAfIdentifyClusterServerInitCallback(uint8_t endpoint) {}
```
Comment (bzbarsky-apple) [inline examples/wifi-echo/server/esp32/main/gen/clusters-callback-stubs.c:1057]: `#if 0`

File: examples/wifi-echo/server/esp32/main/gen/clusters-callback-stubs.c [hunk 9]
```diff
@@ -1030,11 +1053,11 @@ EmberAfStatus emberAfIasZoneClusterServerPreAttributeChangedCallback(uint8_t end
...
 
 void emberAfLevelControlClusterServerInitCallback(uint8_t endpoint) {}
-void emberAfPluginBarrierControlServerInitCallback(void) {}
+// void emberAfPluginBarrierControlServerInitCallback(void) {}
```
Comment (bzbarsky-apple) [inline examples/wifi-echo/server/esp32/main/gen/clusters-callback-stubs.c:1060]: `#if 0`

File: src/app/clusters/barrier-control-server/barrier-control-server-cli.c (hunk 2 above)
Comment (bzbarsky-apple) [inline src/app/clusters/barrier-control-server/barrier-control-server-cli.c:40]: This is because we don't actually want to build this file, right?  At the very least we should document that.  Better yet would be to actually not build this file.  I thought @rwalker-apple had some plan for that; worth checking.

File: src/app/clusters/barrier-control-server/barrier-control-server-test.c [hunk 10]
```diff
@@ -37,6 +37,7 @@
  *******************************************************************************
  ******************************************************************************/
 
+#if 0
```
Comment (bzbarsky-apple) [inline src/app/clusters/barrier-control-server/barrier-control-server-test.c:40]: Again, minimally need to document, better yet to explicitly not build.

File: src/app/clusters/barrier-control-server/barrier-control-server.c (hunk 3 above)
Comment (bzbarsky-apple) [inline src/app/clusters/barrier-control-server/barrier-control-server.c:47]: I would think this should be `100`.

But even better would be to just put:
```
#define MILLISECOND_TICKS_PER_DECISECOND (MILLISECOND_TICKS_PER_SECOND / 10)
```
in a header that gets included from all the things we care about (e.g. `types_stub.h` for the moment?).  And probably put the definition of `MILLISECOND_TICKS_PER_SECOND` in the same header.

That said, as a followup we should investigate all the uses of this define and see whether they make sense in a world in which non-HAL code doesn't know about ticks at all.   Please file a followup issue on that?

File: src/app/clusters/barrier-control-server/barrier-control-server.c [hunk 11]
```diff
@@ -41,8 +41,14 @@
...
+#endif
+
 // We need this for initializating default reporting configurations.
-#include "app/framework/plugin/reporting/reporting.h"
+//#include "app/framework/plugin/reporting/reporting.h"
```
Comment (bzbarsky-apple) [inline src/app/clusters/barrier-control-server/barrier-control-server.c:51]: Seems better to do `#include <app/reporting/reporting.h>` instead.

File: src/app/clusters/identify/identify-cli.c (hunk 4 above)
Comment (bzbarsky-apple) [inline src/app/clusters/identify/identify-cli.c:47]: Again, comment or figure out a way to not build the file?

File: src/app/util/config.h [hunk 12]
```diff
@@ -300,4 +300,5 @@
 #define EMBER_AF_CUSTOM_NETWORK_INIT_OPTIONS (EMBER_NETWORK_INIT_PARENT_INFO_IN_TOKEN | Z3_NETWORK_INIT_BEHAVIOR)
 #endif // EMBER_AF_CUSTOM_NETWORK_INIT_OPTIONS
 
+#define MILLISECOND_TICKS_PER_SECOND 1000
```
Comment (bzbarsky-apple) [inline src/app/util/config.h:303]: Not sure whether this should go here or in `types_stub.h`.  And we should have an issue tracking auditing consumers of this one too.

File: src/app/util/util.c [hunk 13]
```diff
@@ -1400,3 +1400,19 @@ uint8_t emberAfMake8bitEncodedChanPg(uint8_t page, uint8_t channel)
...
+{
+    return EMBER_SUCCESS; // Stub for now.
```
Comment (bzbarsky-apple) [inline src/app/util/util.c:1406]: Please file issues to un-stub and link to them here and in the other stubs?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: examples/wifi-echo/server/esp32/main/gen/clusters-callback-stubs.c [hunk 14]
```diff
@@ -33,27 +33,50 @@ bool emberAfIdentifyClusterIdentifyQueryResponseCallback(uint16_t timeout)
...
- * @param percentOpen   Ver.: always
+ * @param endpoint Endpoint id
  */
-bool emberAfBarrierControlClusterBarrierControlGoToPercentCallback(uint8_t percentOpen)
+bool emberAfPluginIdentifyStopFeedbackCallback(uint8_t endpoint)
 {
     return false;
 }
 
+// /** @brief Barrier Control Cluster Barrier Control Stop
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply examples/wifi-echo/server/esp32/main/gen/clusters-callback-stubs.c:59]: Looks like @rwalker-apple above prefers removal.  ;)

**Comment by rwalker-apple** [comment]
note that both if 0 and commenting out code are against coding guidelines (the only real guidelines we have)

File: src/app/util/util.c (hunk 13 above)
Comment (rwalker-apple) [reply src/app/util/util.c:1406]: this is covered by an issue already assigned to me

File: src/app/util/config.h (hunk 12 above)
Comment (bhaskar-apple) [reply src/app/util/config.h:303]: Moved to `types_stub.h`

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bhaskar-apple** [comment]
@hawk248 @BroderickCarlin review please.

File: examples/wifi-echo/server/esp32/main/component.mk [hunk 15]
```diff
@@ -38,7 +40,6 @@ COMPONENT_SRCDIRS :=                                                      \
 
 #  ../third_party/connectedhomeip/src/app/clusters/identify               \
```
Comment (bzbarsky-apple) [inline examples/wifi-echo/server/esp32/main/component.mk:41]: This line should go away

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@saurabhst @andy31415 @jelderton pinging some more potential reviewers.

**Review by saurabhst — APPROVED** [review]
