### PR TITLE
tv-casting-app: On kBindingsChangedViaCluster, connect to VideoPlayer if already commissioned with it

### LINKED ISSUE #24267: [BUG] tv-casting-app does not connect to tv-app on recommissioning
### Reproduction steps

Test with the Android tv-casting-app and the Linux tv-app. 

Note: The Android tv-casting-app has behaviour to skip the UDC flow if the app is already commissioned with the selected TV. Make a temporary code change in the DiscoveredNodeData.java class in the `isPreCommissioned` method  to `return false` instead of `return connectableVideoPlayer != null` This is done so that we can simulate cases where the post-commissioning flow may have failed which would require the app to go through commissioning again.

1. Commission the Android tv-casting-app with the tv-app.
2. Kill and restart both the Android tv-casting-app and the tv-app.
3. Run through the commissioning flow

Actual result: The tv-casting-app fails to proceed to the Cluster selection screen and never connects to the Linux tv-app it had previously commissioned with.
Expected result: The tv-casting-app finds that it is already commissioned with the selected tv-app and establishes a CASE session with it.

### Bug prevalence

Everytime I do this with the above steps to repro

### GitHub hash of the SDK that was being used

19c8ea42b4f4af2669643b758caa4cf412cfee69

### Platform

android, other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sharadb-amazon**
Fixes https://github.com/project-chip/connectedhomeip/issues/24267

### Change summary
1. Added a flag udcInProgress to CastingServer to track if UDC is in progress
2. On kBindingsChangedViaCluster, if we find UDC is in progress, we select the video player (find its nodeId and fabricIndex) from the cache which matches the one we were trying to commission with now (based on IP addresses and device names)
3. Then we connect to the video player found above and call the commissioningCompleteCallback.

### Testing
Tested with the Android tv-casting-app and the Linux tv-app as per the instructions in https://github.com/project-chip/connectedhomeip/issues/24267

### CODE REVIEW

File: examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp [hunk 1]
```diff
@@ -320,24 +321,81 @@ CastingServer::ContentLauncherLaunchURL(TargetEndpointInfo * endpoint, const cha
...
+            ChipLogProgress(AppServer,
+                            "CastingServer::DeviceEventCallback UDC is in progress while handling kBindingsChangedViaCluster");
+            CastingServer::GetInstance()->udcInProgress = false;
+            if (CastingServer::GetInstance()->mTargetVideoPlayerNumIPs > 0)
+            {
+                TargetVideoPlayerInfo * connectableVideoPlayerList =
+                    CastingServer::GetInstance()->ReadCachedTargetVideoPlayerInfos();
+                if (connectableVideoPlayerList == nullptr || !connectableVideoPlayerList[0].IsInitialized())
+                {
+                    ChipLogProgress(AppServer, "No cached video players found");
```
Comment (chrisdecenzo) [inline examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp:348]: should we be exiting here? Seems like 2 lines later a connectableVideoPlayerList nullptr would cause a crash

File: examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp [hunk 2]
```diff
@@ -320,24 +321,81 @@ CastingServer::ContentLauncherLaunchURL(TargetEndpointInfo * endpoint, const cha
...
+            ChipLogProgress(AppServer,
+                            "CastingServer::DeviceEventCallback already connected to video player, reading server clusters");
             CastingServer::GetInstance()->ReadServerClustersForNode(
                 CastingServer::GetInstance()->GetActiveTargetVideoPlayer()->GetNodeId());
         }
+        else if (CastingServer::GetInstance()->udcInProgress)
+        {
+            ChipLogProgress(AppServer,
+                            "CastingServer::DeviceEventCallback UDC is in progress while handling kBindingsChangedViaCluster");
+            CastingServer::GetInstance()->udcInProgress = false;
```
Comment (chrisdecenzo) [inline examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp:341]: is this the only place where udcInProgress gets set back to false? Does this code path get hit during a regular commissioning flow?

File: examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp [hunk 3]
```diff
@@ -320,24 +321,81 @@ CastingServer::ContentLauncherLaunchURL(TargetEndpointInfo * endpoint, const cha
...
+                                                               CastingServer::GetInstance()->mTargetVideoPlayerNumIPs,
+                                                               CastingServer::GetInstance()->mTargetVideoPlayerIpAddress))
+                    {
+                        ChipLogProgress(AppServer,
+                                        "CastingServer::DeviceEventCallback found the video player to initialize/connect to");
+                        targetPeerNodeId     = connectableVideoPlayerList[i].GetNodeId();
+                        targetFabricIndex    = connectableVideoPlayerList[i].GetFabricIndex();
+                        runPostCommissioning = true;
+                    }
+                }
```
Comment (chrisdecenzo) [inline examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp:363]: maybe log a message if we didn't find a matching connectableVideoPlayer - this would be helpful for debugging I think

**Review by chrisdecenzo — APPROVED** [review]

File: examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp (hunk 1 above)
Comment (sharadb-amazon) [reply examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp]: Done. Added return statement. Also upgraded this to a ChipLogError.

File: examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp (hunk 2 above)
Comment (sharadb-amazon) [reply examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp:341]: It gets set to false here and at line 377 - essentially anytime we want to mark the end of the user directed commissioning flow. 
While line 377 will execute during a regular commissioning flow where the app just commissioned with a new commissioner, line 341 executes when the app begins user directed commissioning but the commissioner had previously commissioned the app.

File: examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp (hunk 3 above)
Comment (sharadb-amazon) [reply examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp:365]: Done. Logging an error message, calling back the client with an error and returning early.

File: examples/tv-casting-app/tv-casting-common/include/CastingServer.h [hunk 4]
```diff
@@ -415,7 +415,8 @@ class CastingServer
     void ReadServerClusters(chip::EndpointId endpointId);
 
     PersistenceManager mPersistenceManager;
-    bool mInited = false;
+    bool mInited       = false;
+    bool udcInProgress = false;
```
Comment (bzbarsky-apple) [inline examples/tv-casting-app/tv-casting-common/include/CastingServer.h:419]:
```suggestion
    bool mUdcInProgress = false;
```

**Review by bzbarsky-apple — APPROVED** [review]

File: examples/tv-casting-app/tv-casting-common/include/CastingServer.h (hunk 4 above)
Comment (sharadb-amazon) [reply examples/tv-casting-app/tv-casting-common/include/CastingServer.h]: Done
