### PR TITLE
change for on off transitiontime feature

### LINKED ISSUE #22750: [BUG]
### Reproduction steps

```bash
1.Testing OnOffTransitionTime feature, when receiving off command(OnOffTransitionTime is non-zero), the previous order: onoff attribute change to off, then execute move-to-level,
The phenomenon of light is off immediately, no fade out.
2.The correct order should be : when receiving off command ,if defined EMBER_AF_PLUGIN_LEVEL_CONTROL, should execute move-to-level-with-on-off, adjust level first, when the level move to min-level, change the onoff attribute to off, if not define on-level, set current level to stored level.
```

### Bug prevalence

When ever I do this

### GitHub hash of the SDK that was being used

7a06f13a6a8d04c26c3fe748afe95e780f76c689

### Platform

esp32

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Jerry-ESP**
#### Problem
Fixes #22750 
Fixed the OnOffTransition feature when receiving an off command and OnOffTransitionTime is non-zero.
Testing OnOffTransitionTime feature, when receiving off command, the previous order: onoff attribute change to off, then execute move-to-level,  
The phenomenon of light is off immediately, no fade out.
The correct order should be : when receiving off command ,if defined  EMBER_AF_PLUGIN_LEVEL_CONTROL,  should execute move-to-level-with-on-off, adjust level first, when the level move to min-level, change the onoff attribute to off, if not define on-level, set current level to stored level.

#### Change overview
1. In on-off-server.cpp file, in the setOnOffValue() function, add a #else condition after the macro EMBER_AF_PLUGIN_LEVEL_CONTROL when set off.
2. In level-control.cpp file, at the emberAfOnOffClusterLevelControlEffectCallback() function, change the MoveToLevel::Id to MoveToLevelWithOnOff::Id to set on-off attribute after level adjustment when execute off effect.
3. In the emberAfLevelControlClusterServerTickCallback(), replace the setOnOffValue() with the OnOff::Attributes::OnOff::Set() function to avoid calling the setOnOffValue() in on-off-server.cpp
4. In the emberAfLevelControlClusterServerTickCallback(), add the storedLevel condition when deal with the level control with on off commands.

#### Testing
test using esp32 lighting-app example 
1. write a non-zero value to the OnOffTransitionTime attribute
2. send on/off command to the lighting-app, the light can fade in and out normally depend on the above time.

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

File: src/app/clusters/level-control/level-control.cpp [hunk 1]
```diff
@@ -246,24 +246,27 @@ void emberAfLevelControlClusterServerTickCallback(EndpointId endpoint)
         if (state->commandId == Commands::MoveToLevelWithOnOff::Id || state->commandId == Commands::MoveWithOnOff::Id ||
             state->commandId == Commands::StepWithOnOff::Id)
         {
-            setOnOffValue(endpoint, (currentLevel != state->minLevel));
+            status = OnOff::Attributes::OnOff::Set(endpoint, currentLevel != state->minLevel);
```
Comment (bzbarsky-apple) [inline src/app/clusters/level-control/level-control.cpp:249]: > Testing OnOffTransitionTime feature, when receiving off command, the previous order: onoff attribute change to off, then execute move-to-level,

@jmartinez-silabs @Rob-Houtepen-Signify could you please check this behavior (and this PR, which is aiming to change it) against the spec?

Comment (jmartinez-silabs) [reply src/app/clusters/level-control/level-control.cpp:249]: You are breaking functionalities and also removing a lot of checks and validation by replacing this function call and forcing the onoff attribute to false. This is not the right way to go.

`setOnOffValue` checks if the on-off cluster is on the same endpoint if so it will call `EmberAfStatus OnOffServer::setOnOffValue` which will validate values and the feature map. it then does the behaviour for the OnTime attribute, the level transitions, links with mode Select and scenes.

Comment (jmartinez-silabs) [reply src/app/clusters/level-control/level-control.cpp:249]: I believe your premise is wrong for the whole logic that you are trying to do. The OnOff attribute state should be turned off when receiving the off command and the level transition started. It is up to the application in my opinion to not physically turn off the light until the desired transition time is done.

I cannot find explicitly in the spec that for OnOffTransition, or Off transition that the OnOff State must be changed after the transition time.

In the spec, the on-off command just specifies that On Off state should be changed directly to false.

The OffWithEffect Command is clearer on that topic as it says 
```
7.4.3. Effect on Receipt
On receipt of the OffWithEffect command, the server SHALL check the value of the GlobalSceneControl attribute.

If the GlobalSceneControl attribute is equal to TRUE, the server SHALL store its settings in its global scene then set the GlobalSceneControl attribute to FALSE, then set the OnOff attribute to FALSE and if the OnTime attribute is supported set the OnTime attribute to 0.

If the GlobalSceneControl attribute is equal to FALSE, the server SHALL only set the OnOff attribute to FALSE.
```
This is a good example of how the effect is dealt with in the app code. The OnOff attribute is changed directly but the app needs to trigger the effect before physically closing the Light.

I'll let Rob chime about the spec.

**Review by jmartinez-silabs — CHANGES_REQUESTED** [review]

File: src/app/clusters/level-control/level-control.cpp (hunk 1 above)
Comment (Rob-Houtepen-Signify) [reply src/app/clusters/level-control/level-control.cpp:249]: These attributes are a nightmare! Including the OnLevel attribute. I have no practical experience with them as they are not mandatory for lights. Which device type uses these? Can we not remove these attributes from the SDK?

Comment (chshu) [reply src/app/clusters/level-control/level-control.cpp:249]: @jmartinez-silabs @Rob-Houtepen-Signify  What's your suggestion on the next step?

OnOffTransitionTime is an optional attribute defined in Level Control cluster, and might be enabled by some lighting customers, some description from Clusters Spec:
```
1.6.5.9. OnOffTransitionTime Attribute

The OnOffTransitionTime attribute represents the time taken to move to or from the target level when On or Off commands are received by an On/Off cluster on the same endpoint.
```
The behavior is clear, and the current SDK already implemented most of the OnOffTransitionTime feature, including the fade in/out logic, this PR aims to trigger the Off state change after the fade out is done, then the whole feature works as expected.

**Review by chshu — APPROVED** [review]

File: src/app/clusters/level-control/level-control.cpp (hunk 1 above)
Comment (jmartinez-silabs) [reply src/app/clusters/level-control/level-control.cpp]: Again, the section of the spec you show is clear on the transition of the level yes. But it doesn't say anything about when the on off attributes changes.

The command received is off. In the spec, the command OnOff says to set the attribute state to off on the command reception. Nothing is said about changing the attribute state after transition time is complete.

Did you test other use cases of the on off and level cluster with your changes?

Is the onLevel (when null or non-null) behaviour still functional for on and off?

File: src/app/clusters/on-off-server/on-off-server.cpp [hunk 2]
```diff
@@ -210,15 +210,19 @@ EmberAfStatus OnOffServer::setOnOffValue(chip::EndpointId endpoint, uint8_t comm
...
-            return status;
+#endif
+            // write the new on/off value
+            status = Attributes::OnOff::Set(endpoint, newValue);
+            if (status != EMBER_ZCL_STATUS_SUCCESS)
+            {
+                emberAfOnOffClusterPrintln("ERR: writing on/off %x", status);
+                return status;
+            }
+#ifdef EMBER_AF_PLUGIN_LEVEL_CONTROL
```
Comment (jmartinez-silabs) [inline src/app/clusters/on-off-server/on-off-server.cpp:223]: I am also not a fan of the use of those ember_af_plugin defines. I know there is still multiple of those throughout the code but they come from zigbee

We now have means check the metadat of the cluster and use the featuremap to determine if a feature should be used or not.

@bzbarsky-apple what do you think? I'll differ to your call on this

Comment (bzbarsky-apple) [reply src/app/clusters/on-off-server/on-off-server.cpp:223]: I think the issue is that this code is calling functions that may not even exist if the level control thing is not compiled in....

But past that, doing feature checks seems fine if there is a feature bit for this.

File: src/app/clusters/level-control/level-control.cpp (hunk 1 above)
Comment (Jerry-ESP) [reply src/app/clusters/level-control/level-control.cpp]: Yes, I had tested most of the on/off and levelcontrol cluster commands, my changes has no extra impact. And the onLevel behaviour still functional for on and off.

**Comment by chshu** [comment]
@jmartinez-silabs We are on the same page that the OnOffTransitionTime feature is defined clearly in Spec, but doesn't specific what should be done in SDK, and what else in application code.

Given the current SDK already implemented the OnOffTransitionTime feature, and handle the fade in/out logic for application. It's hard for application code to distinguish the off command callback is `normal Off` or `start of OffTransition time`. We should simplify the application code in such case.

Thoughts?

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
The "Darwin" test that fails does the following:

1. Subscribe to the "OnOff" attribute with minInterval set to 2 seconds.
1. Send an "off" command.
3. Wait at most 3 seconds after the "off" command responds with success for the attribute change report to appear.

That 3 second timeout is getting hit.

As far as I can tell, OnOffTransitionTime is 0 in this case, so there is no a priori reason that this timeout should be getting hit in this situation.

I also tried to change the 3-second wait to 15 seconds, and the test failed in exactly the same way.  So at first glance there is a real bug here and either the onoff state is never changing to "off" or the subscription reports are not being sent correctly when it does.
