### PR TITLE
[Darwin] Fix OTAProviderDelegate init after all controllers has been turned off and a new controller is started

### LINKED ISSUE #21306: Fix OTA delegate bridge init on Darwin
#### Problem
See https://github.com/project-chip/connectedhomeip/pull/21224#pullrequestreview-1053229275

 #### Proposed Solution
Move the init to the right place, and add tests.

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

Fix #21306

#### Change overview
* Update `MTROTAProviderDelegateBridge::Init` so it returns an error if init fails
* Shuffle the code so `MTROTAProviderDelegateBridge::Init` happens when the system state has been initialised with proper values
* Add a test to make sure a new controller can be created after a proper cleanup of the system state

#### Testing
`xcodebuild test -target "Matter" -scheme "Matter Framework Tests" -sdk macosx -only-testing:MatterTests/MTRControllerTests/testControllerWithOTAProviderDelegate`

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRControllerFactory.mm [hunk 1]
```diff
@@ -387,6 +389,15 @@ - (MTRDeviceController * _Nullable)startControllerOnExistingFabric:(MTRDeviceCon
         return nil;
     }
 
+    if (_otaProviderDelegateBridge) {
+        BOOL ok = [self maybeInitializeOTAProvider:_otaProviderDelegateBridge];
+        if (ok == NO) {
+            MTR_LOG_ERROR("Failed to init provider delegate bridge");
+            [self controllerShuttingDown:controller];
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRControllerFactory.mm:396]: No, at this point the controller has started up, so we need to actually call `shutdown` on it so it will shut itself down properly.  `controllerShuttingDown` will only do part of that work.
```suggestion
            [controller shutdown];
```

File: src/darwin/Framework/CHIP/MTRControllerFactory.mm [hunk 2]
```diff
@@ -447,6 +458,15 @@ - (MTRDeviceController * _Nullable)startControllerOnNewFabric:(MTRDeviceControll
...
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRControllerFactory.mm:465]:
```suggestion
            [controller shutdown];
```

File: src/darwin/Framework/CHIP/MTRControllerFactory.mm [hunk 3]
```diff
@@ -516,6 +531,24 @@ - (BOOL)findMatchingFabric:(FabricTable &)fabricTable
     return YES;
 }
 
+// Initialize the MTROTAProviderDelegateBridge if it has not been initialized already
+//
+// Returns NO on failure, YES on success.
+// If the provider has been initialized already, it is not considered as a failure.
+//
+- (BOOL)maybeInitializeOTAProvider:(MTROTAProviderDelegateBridge * _Nonnull)otaProviderDelegateBridge
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRControllerFactory.mm:539]: Optional, but worth thinking about: we could probably simplify the callsites and reduce code duplication by changing this function to take the controller that was just started as an argument and having it return a nullable controller.  Then the callsites could just do:
```
    return [self maybeInitializeOTAProvider:controller];
```
or so.  On failure this function would return nil after shutting down the controller.

Note that the provider is a member var, so we don't need to pass it in as an argument...

I'm also ok with leaving things as they are here if you prefer that.

File: src/darwin/Framework/CHIPTests/MTRControllerTests.m [hunk 4]
```diff
@@ -158,6 +159,62 @@ - (void)testControllerMultipleShutdown
...
+    XCTAssertNotNil(params2);
+
+    params2.vendorId = @(kTestVendorId);
+
+    MTRDeviceController * controller3 = [factory startControllerOnNewFabric:params2];
+    XCTAssertTrue([controller3 isRunning]);
+    [controller3 shutdown];
+
+    // Stop the factory, start it up again and create a controller to ensure that no dead state from the previous
+    // ota provider delegate are staying around.
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIPTests/MTRControllerTests.m:203]:
```suggestion
    // ota provider delegate is staying around.
```

File: src/darwin/Framework/CHIPTests/MTRControllerTests.m [hunk 5]
```diff
@@ -158,6 +159,62 @@ - (void)testControllerMultipleShutdown
     XCTAssertFalse([factory isRunning]);
 }
 
+- (void)testControllerWithOTAProviderDelegate
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIPTests/MTRControllerTests.m:162]: I assume this test fails without the code changes?

**Review by bzbarsky-apple — APPROVED** [review]

File: src/darwin/Framework/CHIP/MTRControllerFactory.mm (hunk 3 above)
Comment (vivien-apple) [reply src/darwin/Framework/CHIP/MTRControllerFactory.mm]: I end up using `return [self maybeInitializeOTAProvider:controller];`

File: src/darwin/Framework/CHIP/MTRControllerFactory.mm [hunk 6]
```diff
@@ -516,6 +513,27 @@ - (BOOL)findMatchingFabric:(FabricTable &)fabricTable
     return YES;
 }
 
+// Initialize the MTROTAProviderDelegateBridge if it has not been initialized already
+//
+// Returns NO on failure, YES on success.
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRControllerFactory.mm:518]:
```suggestion
// Returns nil on failure, the input controller on success.
```

File: src/darwin/Framework/CHIP/MTRControllerFactory.mm [hunk 7]
```diff
@@ -516,6 +513,27 @@ - (BOOL)findMatchingFabric:(FabricTable &)fabricTable
...
+//
+- (MTRDeviceController * _Nullable)maybeInitializeOTAProvider:(MTRDeviceController * _Nonnull)controller
+{
+    VerifyOrReturnValue(_otaProviderDelegateBridge != nil, controller);
+    VerifyOrReturnValue([_controllers count] == 1, controller);
+
+    auto systemState = _controllerFactory->GetSystemState();
+    CHIP_ERROR err = _otaProviderDelegateBridge->Init(systemState->SystemLayer(), systemState->ExchangeMgr());
+    if (CHIP_NO_ERROR != err) {
+        MTR_LOG_ERROR("Failed to init provider delegate bridge");
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRControllerFactory.mm:529]:
```suggestion
        MTR_LOG_ERROR("Failed to init provider delegate bridge: %" CHIP_ERROR_FORMAT, err.Format());
```

File: src/darwin/Framework/CHIPTests/MTRControllerTests.m (hunk 5 above)
Comment (vivien-apple) [reply src/darwin/Framework/CHIPTests/MTRControllerTests.m:162]: Yes and no, in the sense that it was silently failing.

Initially `MTROTAProviderDelegateBridge` init method was not returning a `CHIP_ERROR` and while the bdx sender checks for a non-null system layer and a non null exchange manager it was not bubbling up to the controller factory.

But bubbling up the error and checking it was making the test fail without moving the `MTROTAProviderDelegateBridge::Init` call site.
