### PR TITLE
[Android] Fix memory leakage in AndroidLogDownloadFromNode Class

### LINKED ISSUE #36734: Java test `Run Pairing Onnetwork and get diagnostic log Test`  is flaky
After #36591 we seem to have frequent errors in diagnostics log test. One such instance reports:

```
2024-12-05T05:59:48.0688225Z [2024-12-05 05:59:48.068222][[32mAPP [0m][[33mSTDOUT[0m][18779:18779] CHIP:EM: ExchangeContext: 48186i delegate=null
2024-12-05T05:59:48.0689511Z [2024-12-05 05:59:48.068228][[32mAPP [0m][[33mSTDOUT[0m][18779:18779] CHIP:SPT: VerifyOrDie failure at src/lib/support/Pool.h:405: Allocated() == 0
```

I believe it may be some race issue here where we stop the application before some pool (unclear which pool) frees its objects.

### PR DESCRIPTION
**Pull request by joonhaengHeo**
Fix #36734 

There are two issues here, 
1. memory was not deleted after finishing AndroidLogDownloadFromNode, in this PR, we add the logic to release memory.
2. There was a part where all-cluster-app was terminated quickly while the script was running, and memory was not freed. To prevent this, I added TimeUnit.SECONDS.sleep(WAIT_FOR_TERMINATE) in PairOnNetworkLongDownloadLogCommand.kt

### Testing
Reenabling the disabled java bdx testing in CI, we have run 5 times in CI, and looks good so far.

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]

File: src/controller/java/AndroidLogDownloadFromNode.cpp [hunk 1]
```diff
@@ -217,22 +217,27 @@ void AndroidLogDownloadFromNode::FinishLogDownloadFromNode(CHIP_ERROR err)
...
-    VerifyOrReturn(jniErr == CHIP_NO_ERROR, ChipLogError(Controller, "Could not find onError method"));
+        env->CallVoidMethod(mJavaCallback.ObjectRef(), onErrorMethod, static_cast<jint>(mController->GetFabricIndex()),
+                            static_cast<jlong>(mRemoteNodeId), static_cast<jlong>(err.AsInteger()));
+    }
 
-    env->CallVoidMethod(mJavaCallback.ObjectRef(), onErrorMethod, static_cast<jint>(mController->GetFabricIndex()),
-                        static_cast<jlong>(mRemoteNodeId), static_cast<jlong>(err.AsInteger()));
+exit:
+    // Finish this function, this object will be deleted.
+    delete this;
```
Comment (yunhanw-google) [inline src/controller/java/AndroidLogDownloadFromNode.cpp:240]: this is not correct, this function is inside callback, you cannot delete this, you should pass context object(AndroidLogDownloadFromNode) from the  callback inside FinishLogDownloadFromNode, then delete in the end.

**Review by yunhanw-google — CHANGES_REQUESTED** [review]

**Review by andy31415 — CHANGES_REQUESTED** [review]
@joonhaengHeo this also needs a `Testing` section in the summary to explain how this was tested.

Since this did not update any unit tests, the testing is `manual` so we need to meet a higher bar (make it less convenient for most PRs to just be manually tested because it is easier) so we need a more detailed description on how the manual tests were done as well as a justification why automated testing of the newly added code is impossible.

**Comment by joonhaengHeo** [comment]
@andy31415 
The automated test is running in the Java Script below.
(The test will be performed using the same API as Android.)
https://github.com/project-chip/connectedhomeip/pull/36742/files#diff-6c2ab70cb562cdd0d56b9443a6986a6f0b1916176bea3e252ee2afff81b8bf68R262

Is there any additional test that is needed?

File: src/controller/java/AndroidLogDownloadFromNode.cpp (hunk 1 above)
Comment (joonhaengHeo) [reply src/controller/java/AndroidLogDownloadFromNode.cpp]: Modified. 
And. The code where Memory Leakage occurred was confirmed to be not Java, but all-cluster-app. However, I checked that there was a part where all-cluster-app was terminated quickly while the script was running, and memory was not freed. To prevent this, I added sleep in the java controller as follows.
https://github.com/project-chip/connectedhomeip/pull/36742/files#diff-bd1929217ea9054b007b99dc0e924dfec04dfbb662e4d00e8c98c9b03fea8901R89

**Review by yunhanw-google — APPROVED** [review]

**Comment by yunhanw-google** [comment]
src/controller/java/AndroidLogDownloadFromNode.cpp:216:    VerifyOrExit(env != nullptr, CHIP_ERROR_INCORRECT_STATE);, please fix that, thanks

**Comment by andy31415** [comment]
> @andy31415 The automated test is running in the Java Script below. (The test will be performed using the same API as Android.) https://github.com/project-chip/connectedhomeip/pull/36742/files#diff-6c2ab70cb562cdd0d56b9443a6986a6f0b1916176bea3e252ee2afff81b8bf68R262
> 
> Is there any additional test that is needed?

@joonhaengHeo this should be written in the `Summary` section (something like re-enabled disabled test, which covers this bit)

**Review by andy31415 — APPROVED** [review]
