### PR TITLE
address media test case issues

### LINKED ISSUE #17845: [TV-APP] Not able to terminate the DUT.
#### Problem
"We launched the DUT and commissioned with TH and later if I wants to terminate the DUT to 
relaunch again I am facing this issue.
image

 * steps to reproduce:-./chip-tv-app

 * system configuration
 system configuration:-
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/3a7f03a0a1c58c4f6cf69ea7e6b808feff3b6636
Dut: TV-app

### LINKED ISSUE #17896: [TC-MC-10.5]Content Launcher Cluster--Results are not matching with the Test-Plan.
#### Problem

**Test-Step-1 and 2**
As per Test-plan, When "TH sends a LaunchURL command to the DUT with a known good content URL string" DUT should responds with "success respond (value 0) and launch the content at the given URL". But currently DUT fails to display the content.

 * expected behavior--Success response and launch the content at given URL
 * actual behavior:-Success response

 * steps to reproduce:-
1. ./chip-tool contentlauncher launch-url "exampleUrl"   '{"providerName":  "exampleName", "background": { "imageUrl": "exampleUrl", "color": "blue", "size" : {"width": 1.0, "height": 1.0,  "metric": 0} }}' 1 1
2. sudo ./chip-tool contentlauncher launch-url "https://csa-iot.org/"   '{"providerName":  "exampleName", "background": { "imageUrl": "exampleUrl", "color": "blue", "size" : {"width": 1.0, "height": 1.0,  "metric": 0} }}' 1 1

**Test-Step 4**
As per Test-Plan, When TH sends a LaunchURL command to the DUT with a known unreachable content URL string. The DUT should respond with a URL_NOT_AVAILABLE response (value 1) but Currently DUT responds with succes(value 0)

 expected behavior--URL_NOT_AVAILABLE response (value 1)
actual behavior:-Success response

 steps to reproduce:-
 sudo ./chip-tool contentlauncher launch-url "https://badurl"   '{"providerName":  "exampleName", "background": { "imageUrl": "exampleUrl", "color": "blue", "size" : {"width": 1.0, "height": 1.0,  "metric": 0} }}' 1 1

**Test-Step-5**
As per Test-Plan, "TH sends a LaunchURL command to the DUT with a known un-authorized content URL string" for this The DUT should respond with a AUTH_FAILED response (value 2).

steps to reproduce:-
sudo ./chip-tool contentlauncher launch-url "https://csa-iot.org/badauth"   '{"providerName":  "exampleName", "background": { "imageUrl": "exampleUrl", "color": "blue", "size" : {"width": 1.0, "height": 1.0,  "metric": 0} }}' 1 1

expected behavior--AUTH_FAILED response (value 2)
actual behavior:-Success response

**system configuration:-**
Chip-Tool: RPI
DUT: RPI
Platform : IP
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/99988e5ae1a2271e4eec9e0c296a3fd58358238d
Dut: TV-app

**Test-Plan Reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#tc-mc-10-5-launch-url-verification-dut-as-server

**PFA log:-**
[[TC-MC-10.5].txt](https://github.com/project-chip/connectedhomeip/files/8590095/TC-MC-10.5.txt)

### LINKED ISSUE #17900: [TC-MC-3.8] and [TC-MC-3.9]--DUT  Fails to stop and hide a running application on the application Basic cluster of the Endpoint
**#### Problem**
As per the Test-Plan, When TH sends a StopApp and HideApp command to DUT to stop or hide a running application, Dut should responds with "Status Attribute is updated to STOPPED(value 0) or ACTIVE_HIDDEN on the application Basic cluster of the Endpoint corresponding to stopped or hidden application.
 
* expected behavior:-Requested application is hidden and Status Attribute is updated to ACTIVE_HIDDEN or STOPPED
 * actual behavior:-APP_NOT_AVAILABLE(value 1)

**system configuration:-**
Chip-Tool: RPI
DUT: RPI
Platform : IP
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/99988e5ae1a2271e4eec9e0c296a3fd58358238d
Dut: TV-app

**Test-Plan reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#tc-mc-3-8-stop-application-verification

**PFA log:-**
[[TC-MC-3.6 and 3.7].txt](https://github.com/project-chip/connectedhomeip/files/8590507/TC-MC-3.6.and.3.7.txt)

### LINKED ISSUE #17902: [TC-MC-3.7]Application Launcher Cluster-LaunchApp command fails to launch specified application.
#### Problem
As per Test-Plan, when TH sends a LaunchApp command to DUT to launch and bring an application to the foreground, Dut should responds with successful (value 0) but currently DUT responds with APP_NOT_AVAILABLE(value 1)

 * expected behavior:- successful (value 0) response and  Status Attribute is updated to ACTIVE_VISIBLE_FOCUS
                                    on the application Basic cluster of the Endpoint 
 * actual behavior:APP_NOT_AVAILABLE(value 1)
 
* steps to reproduce:-sudo ./chip-tool applicationlauncher launch-app '{"catalogVendorId": 5, "applicationId": "exampleString" }' 1 1

system configuration:-
Chip-Tool: RPI
DUT: RPI
Platform : IP
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/99988e5ae1a2271e4eec9e0c296a3fd58358238d
Dut: TV-app

Test-Plan reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#tc-mc-3-7-launch-application-verification

PFA log:-
[[TC-MC-3.7].txt](https://github.com/project-chip/connectedhomeip/files/8590621/TC-MC-3.7.txt)

### LINKED ISSUE #18160: Media test cases - casting fails when video player first commissioned
#### Problem
 * For commissionable TV, I should be able to first commission it using chip-tool and then cast to it using tv-casting-app
 * Currently, this only works after restarting tv-app after commissioning and before casting

 #### Proposed Solution
* Problem is that Server and Commissioner are using different FabricTable objects and so the Commissioner does not know that the Server has added a fabric and as a result there is a conflict. Solution is to add an option to pass the Server's FabricTable to the Commissioner.

### LINKED ISSUE #18216: tv-app ACL persistence regressions
#### Problem
 * ACLs created for tv-casting-app should persist across tv-app restarts. This worked but was broken by a recent refactoring of ACLs

 #### Proposed Solution
* Migrate to the the ACL Entry create method

### PR DESCRIPTION
**Pull request by chrisdecenzo**
#### Problem
What is being fixed?  Examples:
* Fix https://github.com/project-chip/connectedhomeip/issues/17900
* Fix https://github.com/project-chip/connectedhomeip/issues/18160
* Fix https://github.com/project-chip/connectedhomeip/issues/17896
* Fix https://github.com/project-chip/connectedhomeip/issues/17902
* Fix https://github.com/project-chip/connectedhomeip/issues/17845
* Fix https://github.com/project-chip/connectedhomeip/issues/18216

#### Change overview
* 17900: Make dummy app platform recognize the dummy "exampleid" used in the test script.
* 18160: Pass the Server's FabricTable to the Commissioner. Give linux tv-info a dedicated file for storage and default port that does not conflict with tv-casting-app.
* 17896: Make dummy content launcher return correct error codes for bad url and auth failed.
* 17902: Make dummy app platform recognize the dummy "exampleString" used in the test script.
* 17845: Disable SignalHandlers when shell is enabled
* 18216: Migrate to the new ACL Create Entry method

#### Testing
* Tested using chip-tool, tv-app and tv-casting-app on linux

### CODE REVIEW

File: examples/platform/linux/AppMain.cpp [hunk 1]
```diff
@@ -109,6 +109,7 @@ void EventHandler(const DeviceLayer::ChipDeviceEvent * event, intptr_t arg)
     }
 }
 
+#if !defined(ENABLE_CHIP_SHELL)
```
Comment (bzbarsky-apple) [inline examples/platform/linux/AppMain.cpp:112]: Should probably document why this is code is disabled if ENABLE_CHIP_SHELL.

File: src/controller/CHIPDeviceControllerFactory.cpp [hunk 2]
```diff
@@ -147,7 +147,8 @@ CHIP_ERROR DeviceControllerFactory::InitSystemState(FactoryInitParams params)
 #endif
                                                             ));
 
-    stateParams.fabricTable                                   = chip::Platform::New<FabricTable>();
+    stateParams.fabricTable = (params.fabricTable == nullptr) ? chip::Platform::New<FabricTable>() : params.fabricTable;
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceControllerFactory.cpp:150]: This is not OK, for a few reasons:

1) This will end up calling `Init` on the table below, but in this case it's already initialized, no?
2) `DeviceControllerSystemState::Shutdown` will `Platform::Delete` the fabric table, but it's not allocated via `Platform::*` APIs, possibly leading to memory corruption.  And definitely calling the object's destructor while `Server` is still referencing it... 

There are pre-existing issues here about a second session manager and second InteractionModelEngine Init, by the way, which make me wonder how any of this works at all.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

**Review by lazarkov — APPROVED** [review]

**Review by Byungjoo-Lee — APPROVED** [review]

File: src/controller/CHIPDeviceControllerFactory.cpp (hunk 2 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceControllerFactory.cpp]: ok, I found a different approach and so removed this change, thanks

File: examples/platform/linux/AppMain.cpp (hunk 1 above)
Comment (chrisdecenzo) [reply examples/platform/linux/AppMain.cpp:114]: added comment

File: examples/platform/linux/CommissionerMain.cpp [hunk 3]
```diff
@@ -187,6 +188,12 @@ CHIP_ERROR InitCommissioner(uint16_t commissionerPort, uint16_t udcListenPort)
     gCommissionerDiscoveryController.SetUserDirectedCommissioningServer(gCommissioner.GetUserDirectedCommissioningServer());
     gCommissionerDiscoveryController.SetCommissionerCallback(&gCommissionerCallback);
 
+    // re-init server's fabric table since the CommissionerDiscoveryController will add its fabric if not already there.
```
Comment (bzbarsky-apple) [inline examples/platform/linux/CommissionerMain.cpp:191]: This part is not very clear: is CommissionerDiscoveryController adding the fabric to the _storage_ such that we now need to re-read the storage?  Or is it adding it to the table and we want to ignore that addition?

In general, though, the fabric table doesn't claim that you can call Init on it more than once, so doing that is very odd.    In particular doing this will in-place overwrite data structures that various code (include gCommissioner above) has pointers to, as far as I can tell.

File: src/credentials/FabricTable.h [hunk 4]
```diff
@@ -368,11 +383,18 @@ class DLL_EXPORT FabricTable
      */
     CHIP_ERROR AddNewFabric(FabricInfo & fabric, FabricIndex * assignedIndex);
 
+    /**
+     * Obtain a pointer to the FabricInfo. Note that its possible for fabrics to be added
+     * and removed, and for the FabricTable to be re-inited from storage. As a result
+     * clients should use FindFabric when a FabricInfo is needed and avoid holding a
+     * reference since the underlying Fabric may change.
```
Comment (bzbarsky-apple) [inline src/credentials/FabricTable.h:390]: This is not viable.  Consumers hold pointers to FabricInfo* all over.

Fabric removal notifies so they can update.  Fabric addition does not invalidate existing pointers.

File: src/credentials/FabricTable.cpp [hunk 5]
```diff
@@ -785,17 +800,21 @@ FabricIndex NextFabricIndex(FabricIndex index)
 
 void FabricTable::UpdateNextAvailableFabricIndex()
 {
+    ChipLogProgress(Discovery, "   ------   FabricTable::UpdateNextAvailableFabricIndex()");
```
Comment (bzbarsky-apple) [inline src/credentials/FabricTable.cpp:803]: Why are these "Discovery" logs?

File: examples/platform/linux/CommissionerMain.cpp [hunk 6]
```diff
@@ -187,6 +188,13 @@ CHIP_ERROR InitCommissioner(uint16_t commissionerPort, uint16_t udcListenPort)
     gCommissionerDiscoveryController.SetUserDirectedCommissioningServer(gCommissioner.GetUserDirectedCommissioningServer());
     gCommissionerDiscoveryController.SetCommissionerCallback(&gCommissionerCallback);
 
+    // re-init server's fabric table since DeviceControllerFactory::InitSystemState will add
+    // its Fabric if it is not already there.
+    ReturnErrorOnFailure(Server::GetInstance().GetFabricTable().ReInitFromStorage());
```
Comment (bzbarsky-apple) [inline examples/platform/linux/CommissionerMain.cpp:193]: Right on line 172 of this file is a violation of the new API documentation: `gCommissioner` has a `FabricInfo *` member.

File: src/credentials/FabricTable.cpp [hunk 7]
```diff
@@ -719,6 +719,7 @@ CHIP_ERROR FabricTable::Init(PersistentStorageDelegate * storage)
     VerifyOrReturnError(storage != nullptr, CHIP_ERROR_INVALID_ARGUMENT);
 
     mStorage = storage;
+
```
Comment (bzbarsky-apple) [inline src/credentials/FabricTable.cpp:722]: Please undo this stray change.

File: src/credentials/FabricTable.h [hunk 8]
```diff
@@ -128,12 +128,27 @@ class DLL_EXPORT FabricInfo
     // TODO - Update these APIs to take ownership of the buffer, instead of copying
```
Comment (bzbarsky-apple) [inline src/credentials/FabricTable.h:128]: A bunch of stray changes here too.

File: src/controller/CHIPDeviceControllerFactory.cpp [hunk 9]
```diff
@@ -147,31 +147,36 @@ CHIP_ERROR DeviceControllerFactory::InitSystemState(FactoryInitParams params)
...
     stateParams.exchangeMgr                                   = chip::Platform::New<Messaging::ExchangeManager>();
     stateParams.messageCounterManager                         = chip::Platform::New<secure_channel::MessageCounterManager>();
     stateParams.groupDataProvider                             = params.groupDataProvider;
 
-    ReturnErrorOnFailure(stateParams.fabricTable->Init(params.fabricIndependentStorage));
+    // if no fabricTable was provided, create one and track it in stateParams for cleanup
+    FabricTable * fabricTable = params.fabricTable;
+    if (fabricTable == nullptr)
+    {
+        stateParams.fabricTable = fabricTable = chip::Platform::New<FabricTable>();
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceControllerFactory.cpp:161]: OK, but if `fabricTable` is not null, then `stateParam.fabricTable` ends up null, and then the `DeviceControllerSystemState` will return null from `Fabrics`, which will probably cause crashes somewhere around `DeviceController::ProcessControllerNOCChain`.

The thing we probably want to do is:
1. Set the fabric table on the system state.
2. Tell the system state to not delete the table.
3. Store the table in a member of ours, so if we go through the no-args InitSystemState later (e.g. if we shut down the last controller and then try to start a new one) we can set it up on the system state properly...

File: examples/platform/linux/CommissionerMain.cpp (hunk 3 above)
Comment (chrisdecenzo) [reply examples/platform/linux/CommissionerMain.cpp]: added comment explaining rationale, since removed line

File: src/credentials/FabricTable.h (hunk 4 above)
Comment (chrisdecenzo) [reply src/credentials/FabricTable.h]: reverted this approach

File: src/credentials/FabricTable.cpp (hunk 5 above)
Comment (chrisdecenzo) [reply src/credentials/FabricTable.cpp]: this was accidentally left in, fixed

File: examples/platform/linux/CommissionerMain.cpp (hunk 6 above)
Comment (chrisdecenzo) [reply examples/platform/linux/CommissionerMain.cpp]: reverted this approach

File: src/credentials/FabricTable.cpp (hunk 7 above)
Comment (chrisdecenzo) [reply src/credentials/FabricTable.cpp]: reverted

File: src/credentials/FabricTable.h (hunk 8 above)
Comment (chrisdecenzo) [reply src/credentials/FabricTable.h]: fixed

File: src/controller/CHIPDeviceControllerSystemState.h [hunk 10]
```diff
@@ -179,6 +180,11 @@ class DeviceControllerSystemState
     CASEClientPool * mCASEClientPool                               = nullptr;
     Credentials::GroupDataProvider * mGroupDataProvider            = nullptr;
 
+    // if tempFabricTable is not null, it was created during
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceControllerSystemState.h:183]:
```suggestion
    // If mTempFabricTable is not null, it was created during
```

File: src/controller/CHIPDeviceControllerFactory.cpp [hunk 11]
```diff
@@ -147,15 +147,21 @@ CHIP_ERROR DeviceControllerFactory::InitSystemState(FactoryInitParams params)
...
     SimpleSessionResumptionStorage * sessionResumptionStorage = chip::Platform::New<SimpleSessionResumptionStorage>();
     stateParams.sessionResumptionStorage                      = sessionResumptionStorage;
     stateParams.exchangeMgr                                   = chip::Platform::New<Messaging::ExchangeManager>();
     stateParams.messageCounterManager                         = chip::Platform::New<secure_channel::MessageCounterManager>();
     stateParams.groupDataProvider                             = params.groupDataProvider;
 
-    ReturnErrorOnFailure(stateParams.fabricTable->Init(params.fabricIndependentStorage));
+    // if no fabricTable was provided, create one and track it in stateParams for cleanup
+    FabricTable * tempFabricTable = nullptr;
+    stateParams.fabricTable       = params.fabricTable;
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceControllerFactory.cpp:159]: OK.  This is still going to be broken if the controller is shut down and then restarted (at that point it will create a new, "temp" fabric table), but at least there are no memory errors anymore and fixing that can be done in a followup, I guess...

**Review by bzbarsky-apple — APPROVED** [review]

File: src/controller/CHIPDeviceControllerFactory.cpp (hunk 11 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceControllerFactory.cpp:159]: it will require the factory to be restarted in order to restart the controller

Comment (bzbarsky-apple) [reply src/controller/CHIPDeviceControllerFactory.cpp:159]: The point is, we support restarting controllers without restarting the factory, but if someone tries to do that it will be broken.  At the very least that limitation should be documented in the API....
