### PR TITLE
[Push AV] Fix issue in Motion Zone based clip recording

### LINKED ISSUE #41800: [BUG] Camera crash on re-activated video recording
### Reproduction steps

I was able to produce this using:

1. Allocate transport
2. Set transport status to Active
3. Manually trigger transport
4. Set transport status to Inactive, interrupting the upload
5. Modify transport (update the URL)
6. Set transport status to Active
7. Manually trigger transport

```
[1762363646.565] [1060399:1060418] [CAM] Found I-frame at PTS: 0
[h264 @ 0x77287c25ccc0] decoding for stream 0 failed
[dash @ 0x77287c001f00] No bit rate set for stream 0
[dash @ 0x77287c001f00] Opening '/tmp/session_2/media/media.init' for writing
[dash @ 0x77287c001f00] Opening '/tmp/session_2/media/segment_0001.m4s.tmp' for writing
[1762363646.567] [1060399:1060418] [CAM] Found I-frame at PTS: 900000
[1762363648.501] [1060399:1060403] [CAM] Found I-frame at PTS: 1800000
[1762363650.505] [1060399:1060403] [CAM] Found I-frame at PTS: 2700000
[1762363652.513] [1060399:1060403] [CAM] Found I-frame at PTS: 3600000
[1762363654.521] [1060399:1060403] [CAM] Found I-frame at PTS: 4500000
[dash @ 0x77287c001f00] Opening '/tmp/session_2/media.mpd.tmp' for writing
[dash @ 0x77287c001f00] Opening '/tmp/session_2/media/segment_0002.m4s.tmp' for writing
[1762363654.522] [1060399:1077643] [CAM] Renamed segment /tmp/session_2/media/segment_0001.m4s to /tmp/session_2/media/segment_1001.m4s
[1762363654.522] [1060399:1077643] [CAM] Recorder:File upload ready [/tmp/session_2/media/segment_1001.m4s] to [https://<redacted-host>/matter/clips/6b54b093-0fe0-4872-95eb-d19ce31d95d7/]
[1762363654.522] [1060399:1077643] [CAM] Added file name /tmp/session_2/media/segment_1001.m4s to queue
chip-camera-app: pthread_mutex_lock.c:438: __pthread_mutex_lock_full: Assertion `e != ESRCH || !robust' failed.
```

Full logs: [device.redacted.log](https://github.com/user-attachments/files/23373813/device.redacted.log)

Also seeing a slightly different signature in some cases when that subsequent manual trigger actually works but then stopping it (by setting transport status to inactive) panics:

```
[1762370454.492] [1110862:1110862] [DMG] Received command for Endpoint=1 Cluster=0x0000_0555 Command=0x0000_0004
[1762370454.492] [1110862:1110862] [CAM] PushAVTransport transport status change requested to inactive
[1762370454.492] [1110862:1110862] [CAM] PushAVClipRecorder destructor called for sessionID: 2 Track name: media
[1762370454.492] [1110862:1110862] [CAM] PushAVClipRecorder::Stop - Scheduling async cluster server API call for connection 1
[1762370454.492] [1110862:1110862] [CAM] Setting Clip Recorder to Status 0
[1762370454.492] [1110862:1110862] [CAM] Recording stopped for sessionID: 2 Track name: media
[1762370454.492] [1110862:1114285] [CAM] Async thread: Calling NotifyTransportStopped for connection 1
[1762370454.492] [1110862:1114270] [CAM] Recorder thread received stop signal for sessionID: 2 Track name: media
[dash @ 0x7eddf825d600] Opening '/tmp/session_2/media.mpd.tmp' for writing
[1762370454.492] [1110862:1114270] [CAM] Renamed segment /tmp/session_2/media/segment_0001.m4s to /tmp/session_2/media/segment_1001.m4s
[1762370454.492] [1110862:1114270] [CAM] Recorder:File upload ready [/tmp/session_2/media/segment_1001.m4s] to [https://louvrea-mtls-useast2.api.stacceptance.com/matter/clips/7e95d363-a946-441d-9d2c-1cf3ef1db140/]
[1762370454.493] [1110862:1114270] [CAM] Added file name /tmp/session_2/media/segment_1001.m4s to queue
chip-camera-app: tpp.c:83: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.
```

### Bug prevalence

Frequently occuring with different signatures when playing around with manual trigger and transport status (toggling between active/inactive)

### GitHub hash of the SDK that was being used

cfc90c89e6210a26783b94e975abd2b75de5d457

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by raveendra-karu**
#### Summary
Follow issues are addressed in this PR:

1. Camera app crash on a reactivated transport
2. Clip record doesn't start when the transport becomes active, after motion zone trigger occurs
```
Example:
(Motion Trigger Type) Transport Status Active (t = -1) -> Motion event trigger (duration 20 sec) t=0 -> Transport Inactive at t = 5 sec -> Transport Active at t = 10 -> For second time when status change to active, clip recording not started.
```
3. Ignore blind period for Manual trigger type

#### Related issues

Fixes #41800

#### Testing

```
#Build and run camera application
./scripts/examples/gn_build_example.sh examples/camera-app/linux out/debug/
sudo rm -rf /tmp/chip_*; ./out/debu/chip-camera-app

#Build python controller and active environment
scripts/build_python.sh -m platform -i out/python_env
source out/python_env/bin/activate
```

### CODE REVIEW

File: examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp [hunk 1]
```diff
@@ -308,14 +311,14 @@ bool PushAVTransport::HandleTriggerDetected()
     int64_t elapsed = 0;
     auto now        = std::chrono::steady_clock::now();
 
-    if (mTransportTriggerType != TransportTriggerTypeEnum::kCommand && InBlindPeriod(mBlindStartTime, mClipInfo.mBlindDurationS))
+    if (!mRecordingTriggerByManual && mIsZoneBasedTrigger && mTransportTriggerType != TransportTriggerTypeEnum::kCommand && InBlindPeriod(mBlindStartTime, mClipInfo.mBlindDurationS))
```
[the remark this answers is not in the document]
Comment (raveendra-karu) [reply examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp]: Done

File: examples/camera-app/linux/include/pushav-clip-recorder.h [hunk 2]
```diff
@@ -76,23 +76,23 @@ class PushAVClipRecorder
...
+        uint16_t mChunkDurationMs;                             ///< Chunk duration  milliseconds
+        uint16_t mSegmentDurationMs;                           ///< Segment duration in milliseconds
+        uint16_t mBlindDurationS;                              ///< Duration without recording after motion stop
+        uint16_t mPreRollLengthMs;                             ///< Pre-roll length in milliseconds
+        uint16_t mElapsedTimeS;                                ///< Elapsed time since recording start in seconds
+        std::string mOutputPath;                               ///< Base output directory path
+        std::string mTrackName;                                ///< Track name for segmented files
+        std::string mUrl;                                      ///< URL for uploading clips;
+        int mTriggerType;                                      ///< Recording trigger type
+        std::chrono::steady_clock::time_point activationTimeS; ///< Time when the recording started
```
Comment (samadDotDev) [inline examples/camera-app/linux/include/pushav-clip-recorder.h]: This is already well-defined type for "instants" of time, and shouldn't be accompanied by units. Infact, it doesn't store the value in seconds at all
```suggestion
        std::chrono::steady_clock::time_point activationTime; ///< Time when the recording started
```

We should only need `Ms` or `S` units for other raw data types (like uint16 and such) that you already have.

File: examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp [hunk 3]
```diff
@@ -351,14 +354,17 @@ bool PushAVTransport::HandleTriggerDetected()
             mStreaming                             = true;
         }
     }
-    mBlindStartTime = mRecorder->mClipInfo.activationTime + std::chrono::seconds(mRecorder->mClipInfo.mInitialDurationS);
+    mBlindStartTime = mRecorder->mClipInfo.activationTimeS + std::chrono::seconds(mRecorder->mClipInfo.mInitialDurationS) +
+        std::chrono::seconds((mRecorder->mClipInfo.mPreRollLengthMs / 1000));
```
Comment (samadDotDev) [inline examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp]:
```suggestion
        std::chrono::seconds(mRecorder->mClipInfo.mPreRollLengthMs / 1000);
```

File: examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp [hunk 4]
```diff
@@ -531,9 +572,15 @@ void PushAVTransport::SetTransportStatus(TransportStatusEnum status)
         mStreaming    = false; // Stop streaming
         mCanSendVideo = false;
         mCanSendAudio = false;
+        // Clear activationTime for manual triggers when setting status to inactive
+        if (mActivationTimeSetByManualTrigger)
+        {
+            mClipInfo.activationTimeS         = std::chrono::steady_clock::time_point();
+            mActivationTimeSetByManualTrigger = false;
+            ChipLogProgress(Camera, "PushAVTransport, cleared activationTimeS for manual trigger");
```
Comment (samadDotDev) [inline examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp]: This is more of a detail/debug/trace level log
```suggestion
            ChipLogDetail(Camera, "PushAVTransport, cleared activationTime for manual trigger");
```

**Review by samadDotDev — APPROVED** [review]

File: examples/camera-app/linux/include/pushav-clip-recorder.h (hunk 2 above)
Comment (raveendra-karu) [reply examples/camera-app/linux/include/pushav-clip-recorder.h]: Noted, updated changes.

File: examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp (hunk 3 above)
Comment (raveendra-karu) [reply examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp]: Done

File: examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp (hunk 4 above)
Comment (raveendra-karu) [reply examples/camera-app/linux/src/pushav-transport/pushav-transport.cpp]: Done

**Review by marktrayer — APPROVED** [review]

**Review by chulspro — APPROVED** [review]

**Review by pidarped — APPROVED** [review]
