### PR TITLE
Properly manage operational key lifecycle for fail-safe

### LINKED ISSUE #16443: Revert the state of operational key pair, NOC and ICAC on fail-safe expiration
#### Problem
<what's wrong or missing, please include any applicable:
If an UpdateNOC command had been successfully invoked, revert the state of operational key pair, NOC and ICAC for that Fabric to the state prior to the Fail-Safe timer being armed, for the Fabric Index that was the subject of the UpdateNOC command.

    if (event->CommissioningComplete.UpdateNocCommandHasBeenInvoked)
    {
        // TODO: Revert the state of operational key pair, NOC and ICAC
    }

 #### Proposed Solution
<suggested fix, suggested enhancement>

### LINKED ISSUE #19072: Implement the `IsForUpdateNOC` field to CSR request
#### Problem
IsForUpdateNOC field added to CSRRequest in https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/5343 must be implemented, and the associated error handling.

 #### Proposed Solution
<suggested fix, suggested enhancement>

### PR DESCRIPTION
**Pull request by tcarmelveilleux**
#### Problem
- Fail-safe did not properly manage the roll-back of operational keys
- Operational key storage being centralized by value in FabricTable
  prevented ability to back keys by hardware/OS and allow the rollback
  of keys on failsafe expiry
- CASE code was using "raw" FabricInfo * which could go stale on UpdateNOC
  or after fail-safe expiry.

Fixes #19072
Issue #18633
Fixes #16443

#### Change overview
- Adds an OperationalKeystore interface
- Make the FabricTable use the OperationalKeystore for when
  a commissionable node (with Opcreds cluster) is being commissioned
- Retain legacy controller behavior that allows injection of operational
  keys
- Simplifies the fail-safe handling lifecycle
- Add logging to fail-safe handling
- Add logging to general commissioning cluster
- Make CASE use ScopedNodeId everywhere
- Implement IsForUpdateNOC in fail-safe and opcreds cluster

#### Testing
- Unit tests still pass
- Cert tests still pass
- Added unit tests for the OperationalKeystore

### CODE REVIEW

File: src/credentials/FabricTable.cpp [hunk 1]
```diff
@@ -658,6 +627,27 @@ CHIP_ERROR FabricInfo::SetFabricInfo(FabricInfo & newFabric, Credentials::Certif
...
+    // NOTE: this requres ENABLE_HSM_CASE_OPS_KEY is not defined
+    P256SerializedKeypair opKeysSerialized;
+    memcpy(static_cast<uint8_t *>(opKeysSerialized), nocKey.data(), nocKey.size());
+    ReturnErrorOnFailure(opKeysSerialized.SetLength(nocKey.size()));
+
+    P256Keypair opKey;
+    ReturnErrorOnFailure(opKey.Deserialize(opKeysSerialized));
+    ReturnErrorOnFailure(SetOperationalKeypair(&opKey));
+
+    // NOTE: mVendorId and mFabricLabel are not initialize, because they are not used in tests.
```
Comment (msandstedt) [inline src/credentials/FabricTable.cpp:647]:
```suggestion
    // NOTE: mVendorId and mFabricLabel are not initialized because they are not used in tests.
```

File: src/credentials/FabricTable.h [hunk 2]
```diff
@@ -509,6 +554,15 @@ class DLL_EXPORT FabricTable
     // it can go and is full.
     Optional<FabricIndex> mNextAvailableFabricIndex;
     uint8_t mFabricCount = 0;
+
+    // If true, we are in the process of a fail-safe and there was at least one
+    // operation that cause partial data in the fabric table.
```
Comment (msandstedt) [inline src/credentials/FabricTable.h:559]:
```suggestion
    // If true, we are in the process of a fail-safe and there was at least one
    // operation that caused partial data in the fabric table.
```

File: src/credentials/FabricTable.h [hunk 3]
```diff
@@ -509,6 +554,15 @@ class DLL_EXPORT FabricTable
...
+    bool mIsPendingFabricDataPresent = false;
+
+    // When mIsPendingFabricDataPresent is true, this holds the index of the fabric
+    // for which is there is currently pending data.
```
Comment (msandstedt) [inline src/credentials/FabricTable.h:563]:
```suggestion
    // When mIsPendingFabricDataPresent is true, this holds the index of the fabric
    // for which there is currently pending data.
```

File: src/crypto/OperationalKeystore.h [hunk 4]
```diff
@@ -0,0 +1,139 @@
...
+     *                                         or if fabricIndex is an invalid value.
+     * @retval CHIP_ERROR_NOT_IMPLEMENTED if only `SignWithOpKeypair` is supported
+     * @retval other CHIP_ERROR value on internal crypto engine errors
+     */
+    virtual CHIP_ERROR NewOpKeypairForFabric(FabricIndex fabricIndex, MutableByteSpan & outCertificateSigningRequest) = 0;
+
+    /**
+     * @brief Temporarily activates the operational keypair last generated with `NewOpKeypairForFabric`, so
+     *        that `SignWithOpKeypair` starts using it, but only it matches public key associated
+     *        with the last NewOpKeypairForFabric.
```
Comment (msandstedt) [inline src/crypto/OperationalKeystore.h:52]:
```suggestion
     *        that `SignWithOpKeypair` starts using it, but only if it matches public key associated
     *        with the last NewOpKeypairForFabric.
```

File: src/lib/support/logging/CHIPLogging.cpp [hunk 5]
```diff
@@ -100,8 +100,8 @@ const char ModuleNames[] = "-\0\0" // None
                            "SD\0"  // ServiceDirectory
                            "SP\0"  // ServiceProvisioning
                            "SWU"   // SoftwareUpdate
-                           "TP\0"  // TokenPairing
-                           "TS\0"  // TimeService
+                           "FS\0"  // FailSafe
+                           "TS\0"  // TimeServices
```
Comment (msandstedt) [inline src/lib/support/logging/CHIPLogging.cpp:104]: I had changed this comment from TimeServices to TimeService to match `kLogModule_TimeService`.  I don't have an opinion on which is better, but changing this comment is a smaller delta.

```suggestion
                           "TS\0"  // TimeService
```

File: src/app/clusters/general-commissioning-server/general-commissioning-server.cpp [hunk 6]
```diff
@@ -231,16 +237,34 @@ bool emberAfGeneralCommissioningClusterCommissioningCompleteCallback(
             !failSafe.MatchesFabricIndex(commandObj->GetAccessingFabricIndex()))
         {
             response.errorCode = CommissioningError::kInvalidAuthentication;
+            ChipLogError(FailSafe, "GeneralCommissioning: Got commissioning complete in invalid security context");
         }
         else
         {
+            if (failSafe.NocCommandHasBeenInvoked())
+            {
+                CHIP_ERROR err = fabricTable.CommitPendingFabricData();
```
Comment (msandstedt) [inline src/app/clusters/general-commissioning-server/general-commissioning-server.cpp:246]: Do we have a sequencing problem with this commit happening here, but other things being committed or reverted in src/app/clusters/operational-credentials-server/operational-credentials-server.cpp after the event loop comes around the horn?  This doesn't seem right to me.  Shouldn't this all happen in one place?

Comment (tcarmelveilleux) [reply src/app/clusters/general-commissioning-server/general-commissioning-server.cpp:246]: Where do you suggest it would happen. I want it to happen during the same event loop pass as the CommissioningComplete. I think it's safer like that, I can't see a different way off the top of my head that has zero races with the event loop since we are not doing any introspection of pending events.

File: src/app/server/Server.cpp [hunk 7]
```diff
@@ -297,6 +301,41 @@ CHIP_ERROR Server::Init(const ServerInitParams & initParams)
     return err;
 }
 
+CHIP_ERROR Server::InitFailSafe()
```
Comment (tehampson) [inline src/app/server/Server.cpp:304]: nit, is there any point to this returning `CHIP_ERROR` instead of void? Right now it looks like you always return `CHIP_NO_ERROR`

Comment (tcarmelveilleux) [reply src/app/server/Server.cpp:304]: Good catch

File: src/platform/FailSafeContext.cpp [hunk 8]
```diff
@@ -37,36 +37,32 @@ constexpr TLV::Tag kUpdateNocCommandTag = TLV::ContextTag(2);
...
-    }
+    FailSafeContext * failSafeContext = reinterpret_cast<FailSafeContext *>(arg);
+    failSafeContext->DisarmFailSafe();
 }
 
 void FailSafeContext::FailSafeTimerExpired()
 {
+    if (!IsFailSafeArmed())
+    {
+        // In case this was a pending timer event in event loop, and we had
```
Comment (bzbarsky-apple) [inline src/platform/FailSafeContext.cpp:54]: `FailSafeContext::DisarmFailSafe` cancels the timer. I guess the point is that if we're in the middle of timer processing the CancelTimer might actually not do anything because the timer has already "fired" but just not called its callback yet?  It's really not clear from the CancelTimer API documentation that this is possible failure mode.  As a follow-up, please update the docs there?  And we need to audit all our CancelTimer uses.  :(

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 9]
```diff
@@ -345,13 +348,9 @@ void FailSafeCleanup(const chip::DeviceLayer::ChipDeviceEvent * event)
 
 void CommissioningComplete(const chip::DeviceLayer::ChipDeviceEvent * event)
 {
+    // THIS IS DEFERRED. The let the General Commissioning server actually
+    // commit he fabric table much before this deferred event loop event occurs.
```
Comment (msandstedt) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:352]:
```suggestion
    // THIS IS DEFERRED. The General Commissioning server actually
    // commits the fabric table much before this deferred event loop event occurs.
```

File: src/platform/FailSafeContext.cpp [hunk 10]
```diff
@@ -37,36 +37,32 @@ constexpr TLV::Tag kUpdateNocCommandTag = TLV::ContextTag(2);
...
+        // done CommissioningComplete or manual disarm.
+        return;
+    }
+
+    ChipLogProgress(FailSafe, "Fail-safe timer expired");
+    DeviceLayer::SystemLayer().CancelTimer(HandleArmFailSafeTimer, this);
```
Comment (bzbarsky-apple) [inline src/platform/FailSafeContext.cpp:60]: I don't understand this CancelTimer call.  The timer just fired.... why do we need to cancel it again?

**Review by msandstedt — APPROVED** [review]

File: src/platform/FailSafeContext.cpp [hunk 11]
```diff
@@ -37,36 +37,32 @@ constexpr TLV::Tag kUpdateNocCommandTag = TLV::ContextTag(2);
...
     ScheduleFailSafeCleanup(mFabricIndex, mAddNocCommandHasBeenInvoked, mUpdateNocCommandHasBeenInvoked);
 }
 
 void FailSafeContext::ScheduleFailSafeCleanup(FabricIndex fabricIndex, bool addNocCommandInvoked, bool updateNocCommandInvoked)
 {
-    ResetState();
```
Comment (bzbarsky-apple) [inline src/platform/FailSafeContext.cpp:68]: Why is this being removed?  That will make it look like a fail-safe is still armed, when it's critically important at this point that it _not_ look like it's armed.

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp (hunk 9 above)
Comment (tcarmelveilleux) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp]: Fixed

File: src/crypto/tests/BUILD.gn [hunk 12]
```diff
@@ -59,5 +61,6 @@ chip_test_suite("tests") {
     "${nlunit_test_root}:nlunit-test",
   ]
 
+  #tests = [ "CHIPCryptoPALTest", "TestPersistentStorageOpKeyStore" ]
```
Comment (tehampson) [inline src/crypto/tests/BUILD.gn:64]: nit, I am guessing you want clean this up?

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 13]
```diff
@@ -1044,68 +1091,70 @@ bool emberAfOperationalCredentialsClusterCSRRequestCallback(app::CommandHandler
...
+
+        Optional<FabricIndex> fabricIndexForCsr;
+        if (isForUpdateNoc)
+        {
+            fabricIndexForCsr.SetValue(commandObj->GetAccessingFabricIndex());
+        }
+
+        err = fabricTable.AllocatePendingOperationalKey(fabricIndexForCsr, csrSpan);
+
+        if (csrSpan.size() > Crypto::kMAX_CSR_Length)
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:1139]: Correct

File: src/protocols/secure_channel/tests/TestCASESession.cpp [hunk 14]
```diff
@@ -160,14 +202,19 @@ CHIP_ERROR InitCredentialSets()
...
     ReturnErrorOnFailure(opKeysSerialized.SetLength(sTestCert_Node01_01_PublicKey_Len + sTestCert_Node01_01_PrivateKey_Len));
 
-    ReturnErrorOnFailure(opKey.Deserialize(opKeysSerialized));
-    ReturnErrorOnFailure(deviceFabric.SetOperationalKeypair(&opKey));
+    ReturnErrorOnFailure(deviceOpKey->Deserialize(opKeysSerialized));
+
+    gDeviceOperationalKeystore.Init(1, std::move(deviceOpKey));
+    ReturnErrorOnFailure(gDeviceFabrics.Init(&gDeviceStorageDelegate, &gDeviceOperationalKeystore));
+
+    // ReturnErrorOnFailure(deviceFabric.SetOperationalKeypair(&opKey));
```
Comment (tehampson) [inline src/protocols/secure_channel/tests/TestCASESession.cpp:217]: nit, I am guessing you can remove this now?

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 15]
```diff
@@ -870,9 +900,26 @@ bool emberAfOperationalCredentialsClusterUpdateNOCCallback(app::CommandHandler *
         VerifyOrExit(err == CHIP_NO_ERROR, nocResponse = ConvertToNOCResponseStatus(err));
     }
 
-    err = Server::GetInstance().GetFabricTable().UpdateFabric(fabricIndex, gFabricBeingCommissioned);
+    // TODO(#18633): Stop committing fabric table right away, only do it on commissioning complete
+    err = fabricTable.UpdateFabric(fabricIndex, gFabricBeingCommissioned);
     VerifyOrExit(err == CHIP_NO_ERROR, nocResponse = ConvertToNOCResponseStatus(err));
 
+    // Activate the operational key previously generated
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:903]: My follow-up will rewrite the code to deal with certificates, so I will factor it out then.

File: src/app/server/Server.cpp [hunk 16]
```diff
@@ -155,6 +157,8 @@ CHIP_ERROR Server::Init(const ServerInitParams & initParams)
         deviceInfoprovider->SetStorageDelegate(mDeviceStorage);
     }
 
+    InitFailSafe();
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/server/Server.cpp:160]: Just moved it down and also documented

File: src/crypto/PersistentStorageOperationalKeystore.cpp [hunk 17]
```diff
@@ -0,0 +1,303 @@
...
+
+    ReturnErrorOnFailure(writer.Put(kOpKeyVersionTag, kOpKeyVersion));
+
+    // P256SerializedKeypair has RAII secret clearing
+    Crypto::P256SerializedKeypair serializedOpKey;
+    ReturnErrorOnFailure(keypair->Serialize(serializedOpKey));
+
+    ReturnErrorOnFailure(writer.Put(kOpKeyDataTag, ByteSpan(serializedOpKey.Bytes(), serializedOpKey.Length())));
+
+    // We are done with the serialized key, it is in the TLV now, let's clean this temp buffer ASAP.
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/crypto/PersistentStorageOperationalKeystore.cpp:77]: Good catch, fixed

File: src/credentials/FabricTable.cpp [hunk 18]
```diff
@@ -518,6 +491,24 @@ FabricInfo * FabricTable::FindFabricWithIndex(FabricIndex fabricIndex)
     return nullptr;
 }
 
+const FabricInfo * FabricTable::FindFabricWithIndex(FabricIndex fabricIndex) const
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/credentials/FabricTable.cpp:494]: It is worse... It's a bit annoying but I'm trying to see if a follow-up can remove the non-const getter altogether

File: src/credentials/FabricTable.cpp [hunk 19]
```diff
@@ -583,65 +574,35 @@ CHIP_ERROR FabricTable::LoadFromStorage(FabricInfo * fabric)
...
-    VerifyOrReturnError(operationalKey->Pubkey().Length() == pubkey.Length(), CHIP_ERROR_INVALID_PUBLIC_KEY);
-    VerifyOrReturnError(memcmp(operationalKey->Pubkey().ConstBytes(), pubkey.Bytes(), pubkey.Length()) == 0,
-                        CHIP_ERROR_INVALID_PUBLIC_KEY);
-
-    if (mFabricId != kUndefinedFabricId)
+    if (operationalKey != nullptr)
     {
-        VerifyOrReturnError(mFabricId == fabricId, CHIP_ERROR_UNSUPPORTED_CERT_FORMAT);
-    }
+        // Verify that public key in NOC matches public key generated provided by controller init.
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/credentials/FabricTable.cpp:589]: Fixed

File: src/credentials/FabricTable.cpp [hunk 20]
```diff
@@ -583,65 +574,35 @@ CHIP_ERROR FabricTable::LoadFromStorage(FabricInfo * fabric)
...
+        }
+        else if (operationalKey != nullptr)
+        {
+            ReturnErrorOnFailure(SetOperationalKeypair(operationalKey));
+        }
+        else
+        {
+            return CHIP_ERROR_INCORRECT_STATE;
+        }
     }
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/credentials/FabricTable.cpp:606]: Done

File: src/credentials/FabricTable.cpp [hunk 21]
```diff
@@ -909,6 +899,17 @@ CHIP_ERROR FabricTable::Init(PersistentStorageDelegate * storage)
     return CHIP_NO_ERROR;
 }
 
+CHIP_ERROR FabricTable::Init(PersistentStorageDelegate * storage, OperationalKeystore * operationalKeystore)
+{
+    if (operationalKeystore == nullptr)
+    {
+        ChipLogError(FabricProvisioning,
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/credentials/FabricTable.cpp:906]: Just removed the warning

File: src/credentials/FabricTable.cpp [hunk 22]
```diff
@@ -1124,40 +1140,122 @@ CHIP_ERROR FabricTable::ReadFabricInfo(TLV::ContiguousBufferTLVReader & reader)
...
 
-    P256Keypair opKey;
-    ReturnErrorOnFailure(opKey.Deserialize(opKeysSerialized));
-    ReturnErrorOnFailure(SetOperationalKeypair(&opKey));
+    if (fabricIndex.HasValue())
+    {
+        // Fabric udpate case (e.g. UpdateNOC): we already know the fabric index
+        mFabricIndexWithPendingState = fabricIndex.Value();
+    }
+    else if ((mFabricCount < kMaxValidFabricIndex) && mNextAvailableFabricIndex.HasValue())
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/credentials/FabricTable.cpp:1191]: Removed the mFabricCount check

File: src/credentials/FabricTable.h [hunk 23]
```diff
@@ -186,6 +187,12 @@ class DLL_EXPORT FabricInfo
                                         Credentials::ValidationContext & context, PeerId & nocPeerId, FabricId & fabricId,
                                         Crypto::P256PublicKey & nocPubkey);
 
+    // Validate an NOC chain at time of adding/updating a fabric (uses VerifyCredentials with additional checks)
+    static CHIP_ERROR ValidateIncomingNOCChain(const ByteSpan & noc, const ByteSpan & icac, const ByteSpan & rcac,
+                                               FabricId existingFabricId, Credentials::CertificateValidityPolicy * policy,
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/credentials/FabricTable.h:192]: Documented

File: src/credentials/FabricTable.h [hunk 24]
```diff
@@ -465,6 +486,23 @@ class DLL_EXPORT FabricTable
     ConstFabricIterator begin() const { return cbegin(); }
     ConstFabricIterator end() const { return cend(); }
 
+    CHIP_ERROR SignWithOpKeypair(FabricIndex fabricIndex, ByteSpan message, Crypto::P256ECDSASignature & outSignature) const;
+
+    CHIP_ERROR AllocatePendingOperationalKey(Optional<FabricIndex> fabricIndex, MutableByteSpan & outputCsr);
+    CHIP_ERROR ActivatePendingOperationalKey(const Crypto::P256PublicKey & nocSubjectPublicKey);
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/credentials/FabricTable.h:492]: Done

File: src/crypto/CHIPCryptoPAL.h [hunk 25]
```diff
@@ -187,6 +187,31 @@ void ClearSecretData(uint8_t (&buf)[N])
...
+    const uint8_t * A = (const uint8_t *) a;
+    const uint8_t * B = (const uint8_t *) b;
+    uint8_t diff      = 0;
+
+    for (size_t i = 0; i < n; i++)
+    {
+        diff |= (A[i] ^ B[i]);
+    }
+
+    return (diff == 0);
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/crypto/CHIPCryptoPAL.h:212]: Let me fix

File: src/crypto/OperationalKeystore.h [hunk 26]
```diff
@@ -0,0 +1,152 @@
...
+
+namespace chip {
+namespace Crypto {
+
+class OperationalKeystore
+{
+public:
+    virtual ~OperationalKeystore() {}
+
+    // ==== Commissionable-only API (although can be used by controllers) ====
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/crypto/OperationalKeystore.h:16]: Done

File: src/crypto/OperationalKeystore.h [hunk 27]
```diff
@@ -0,0 +1,152 @@
...
+     *        NOT ACTIVE (i.e after `NewOpKeypairForFabric` but before
+     *        `ActivateOpKeypairForFabric`).
+     */
+    virtual bool HasPendingOpKeypair() const = 0;
+
+    /**
+     * @brief Returns whether a usable operational key exists for the given fabric.
+     *
+     * Returns true even if the key is not persisted, such as if `ActivateOpKeypairForFabric`
+     * had been successfully called for a given fabric.
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/crypto/OperationalKeystore.h:31]: Fixed

File: src/crypto/OperationalKeystore.h [hunk 28]
```diff
@@ -0,0 +1,152 @@
...
+     * @return true if there an active operational keypair for the given FabricIndex, false otherwise.
+     */
+    virtual bool HasOpKeypairForFabric(FabricIndex fabricIndex) const = 0;
+
+    /**
+     * @brief This initializes a new keypair for the given fabric and generates a CSR for it,
+     *        so that it can be passed in a CSRResponse.
+     *
+     * The keypair is temporary and becomes usable for `SignWithOpKeypair` only after either
+     * `ActivateOpKeypairForFabric` or `CommitOpKeypairForFabric is called. It is destroyed if
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/crypto/OperationalKeystore.h:43]: Yes, commit cannot be skipped. Fixed

File: src/crypto/PersistentStorageOperationalKeystore.cpp [hunk 29]
```diff
@@ -0,0 +1,303 @@
...
+ *           APIs use stack buffers and do not sanitize! This implementation is for example purposes
+ *           only of the API and it is recommended to avoid directly accessing raw private key bits
+ *           in storage.
+ */
+CHIP_ERROR SignWithStoredOpKey(FabricIndex fabricIndex, PersistentStorageDelegate * storage, const ByteSpan & message,
+                               P256ECDSASignature & outSignature)
+{
+    VerifyOrReturnError(IsValidFabricIndex(fabricIndex) && (storage != nullptr), CHIP_ERROR_INVALID_ARGUMENT);
+
+    // Use RAII scoping for the transient keypair, to make sure it doesn't get leaked on any error paths.
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/crypto/PersistentStorageOperationalKeystore.cpp:100]: Documented.

File: src/crypto/PersistentStorageOperationalKeystore.cpp [hunk 30]
```diff
@@ -0,0 +1,303 @@
...
+    auto transientOperationalKeypair = Platform::MakeUnique<P256Keypair>();
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/crypto/PersistentStorageOperationalKeystore.cpp:101]: The whole point for HSM is that they would implement a Keystore and that abstracts the whole deal 100%

File: src/crypto/PersistentStorageOperationalKeystore.cpp [hunk 31]
```diff
@@ -0,0 +1,303 @@
...
+}
+
+CHIP_ERROR PersistentStorageOperationalKeystore::NewOpKeypairForFabric(FabricIndex fabricIndex,
+                                                                       MutableByteSpan & outCertificateSigningRequest)
+{
+    VerifyOrReturnError(mStorage != nullptr, CHIP_ERROR_INCORRECT_STATE);
+    VerifyOrReturnError(IsValidFabricIndex(fabricIndex), CHIP_ERROR_INVALID_FABRIC_INDEX);
+    VerifyOrReturnError(outCertificateSigningRequest.size() >= Crypto::kMAX_CSR_Length, CHIP_ERROR_BUFFER_TOO_SMALL);
+
+    // Replace previous pending keypair, if any was previously allocated
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/crypto/PersistentStorageOperationalKeystore.cpp:203]: Good catch. Added a unit test line to verify

File: src/crypto/PersistentStorageOperationalKeystore.cpp [hunk 32]
```diff
@@ -0,0 +1,303 @@
...
+    mPendingFabricIndex = kUndefinedFabricIndex;
+
+    mPendingKeypair = Platform::New<Crypto::P256Keypair>();
+    VerifyOrReturnError(mPendingKeypair != nullptr, CHIP_ERROR_NO_MEMORY);
+
+    mPendingKeypair->Initialize();
+    size_t csrLength = outCertificateSigningRequest.size();
+    CHIP_ERROR err   = mPendingKeypair->NewCertificateSigningRequest(outCertificateSigningRequest.data(), csrLength);
+
+    // No need to free the mPendingKeypair on failure, it may be OK and other paths will clean it.
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/crypto/PersistentStorageOperationalKeystore.cpp:216]: Fixed

File: src/crypto/PersistentStorageOperationalKeystore.cpp [hunk 33]
```diff
@@ -0,0 +1,303 @@
...
+                                                                       MutableByteSpan & outCertificateSigningRequest)
+{
+    VerifyOrReturnError(mStorage != nullptr, CHIP_ERROR_INCORRECT_STATE);
+    VerifyOrReturnError(IsValidFabricIndex(fabricIndex), CHIP_ERROR_INVALID_FABRIC_INDEX);
+    VerifyOrReturnError(outCertificateSigningRequest.size() >= Crypto::kMAX_CSR_Length, CHIP_ERROR_BUFFER_TOO_SMALL);
+
+    // Replace previous pending keypair, if any was previously allocated
+    ResetPendingKey();
+
+    // Until ActivateOpKeypairForFabric, the new key is just pending in memory.
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/crypto/PersistentStorageOperationalKeystore.cpp:206]: It's actually not needed. Removed

File: src/crypto/tests/BUILD.gn (hunk 12 above)
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/crypto/tests/BUILD.gn:64]: Fixed, was debugging issues with unit test builds related to this legacy unit test (the only one left of this shape)

File: src/crypto/tests/TestPersistentStorageOpKeyStore.cpp [hunk 34]
```diff
@@ -0,0 +1,216 @@
...
+    err     = opKeystore.NewOpKeypairForFabric(kFabricIndex, csrSpan);
+    NL_TEST_ASSERT(inSuite, err == CHIP_NO_ERROR);
+    NL_TEST_ASSERT(inSuite, opKeystore.HasPendingOpKeypair() == true);
+
+    P256PublicKey csrPublicKey2;
+    err = VerifyCertificateSigningRequest(csrSpan.data(), csrSpan.size(), csrPublicKey2);
+    NL_TEST_ASSERT(inSuite, err == CHIP_NO_ERROR);
+    NL_TEST_ASSERT(inSuite, !csrPublicKey1.Matches(csrPublicKey2));
+
+    // Fail to generate CSR for invalid fabrics
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/crypto/tests/TestPersistentStorageOpKeyStore.cpp:77]: Done

File: src/include/platform/FailSafeContext.h [hunk 35]
```diff
@@ -94,6 +99,7 @@ class FailSafeContext
     bool mAddNocCommandHasBeenInvoked      = false;
     bool mUpdateNocCommandHasBeenInvoked   = false;
     bool mAddTrustedRootCertHasBeenInvoked = false;
+    bool mIsCsrRequestForUpdateNoc         = false;
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/include/platform/FailSafeContext.h:102]: Done

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp]: Removed

File: src/platform/FailSafeContext.cpp (hunk 8 above)
Comment (tcarmelveilleux) [reply src/platform/FailSafeContext.cpp:54]: Documented

File: src/platform/FailSafeContext.cpp (hunk 10 above)
Comment (tcarmelveilleux) [reply src/platform/FailSafeContext.cpp:60]: Fixed

File: src/platform/FailSafeContext.cpp (hunk 11 above)
Comment (tcarmelveilleux) [reply src/platform/FailSafeContext.cpp:68]: That's why there is the "busy" flag below.

 The ResetState is done by     `PlatformMgr().ScheduleWork(HandleDisarmFailSafe, reinterpret_cast<intptr_t>(this));` --> HandleDisarmFailSafe --> DisarmFailSafe via the event loop.

I hate this and we should fix it... But not this PR

Comment (bzbarsky-apple) [reply src/platform/FailSafeContext.cpp:68]: The busy flag is fine, but the point of this ResetState was to clear the "armed" state.  We want `IsFailSafeArmed()` to test false starting at this point.  That's why the ResetState was there.

That means either setting `mFailSafeArmed` to false or having `IsFailSafeArmed()` test the busy flag or something....

Comment (tcarmelveilleux) [reply src/platform/FailSafeContext.cpp:68]: Fixed

File: src/crypto/tests/TestPersistentStorageOpKeyStore.cpp [hunk 36]
```diff
@@ -0,0 +1,216 @@
...
+{
+    TestPersistentStorageDelegate storageDelegate;
+    PersistentStorageOperationalKeystore opKeystore;
+
+    FabricIndex kFabricIndex    = 111;
+    FabricIndex kBadFabricIndex = kFabricIndex + 10;
+
+    // Failure before Init
+    P256PublicKey placeHolderPublicKey;
+    CHIP_ERROR err = opKeystore.ActivateOpKeypairForFabric(kFabricIndex, placeHolderPublicKey);
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/crypto/tests/TestPersistentStorageOpKeyStore.cpp:45]: Done

File: src/platform/FailSafeContext.cpp (hunk 11 above)
Comment (tcarmelveilleux) [reply src/platform/FailSafeContext.cpp:68]: Fixed and added a bit of docs. The solution is to not post anything to even loop anymore...

**Review by tehampson — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

File: src/credentials/FabricTable.cpp [hunk 37]
```diff
@@ -802,8 +802,13 @@ CHIP_ERROR FabricTable::Delete(FabricIndex fabricIndex)
         // chose to return.
         return CHIP_ERROR_NOT_FOUND;
     }
+
+    // TODO: The error chain below can cause partial state storage. We must refactor.
     ReturnErrorOnFailure(err);
-    ReturnErrorOnFailure(opKeyErr);
+    if (opKeyErr != CHIP_ERROR_INVALID_FABRIC_INDEX)
```
Comment (bzbarsky-apple) [inline src/credentials/FabricTable.cpp:808]: Please document that for fail-safe expiration this is an expected condition, because we may already have done `RevertPendingFabricData` in that case.

File: src/crypto/tests/TestPersistentStorageOpKeyStore.cpp [hunk 38]
```diff
@@ -0,0 +1,237 @@
...
+
+    // Committing with mismatching fabric fails, leaves pending
+    err = opKeystore.CommitOpKeypairForFabric(kBadFabricIndex);
+    NL_TEST_ASSERT(inSuite, err == CHIP_ERROR_INVALID_FABRIC_INDEX);
+    NL_TEST_ASSERT(inSuite, storageDelegate.GetNumKeys() == 0);
+    NL_TEST_ASSERT(inSuite, opKeystore.HasPendingOpKeypair() == true);
+    NL_TEST_ASSERT(inSuite, opKeystore.HasOpKeypairForFabric(kFabricIndex) == true);
+
+    // Committing key resets pending state and adds storage
+    DefaultStorageKeyAllocator keyAllocator;
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/crypto/tests/TestPersistentStorageOpKeyStore.cpp:169]: The keyallocator is what determines the correct values of storage keys for different purposes in common code

File: src/credentials/FabricTable.cpp (hunk 37 above)
Comment (tcarmelveilleux) [reply src/credentials/FabricTable.cpp:808]: Done

File: src/credentials/FabricTable.h [hunk 39]
```diff
@@ -186,6 +187,15 @@ class DLL_EXPORT FabricInfo
                                         Credentials::ValidationContext & context, PeerId & nocPeerId, FabricId & fabricId,
                                         Crypto::P256PublicKey & nocPubkey);
 
+    // Validate an NOC chain at time of adding/updating a fabric (uses VerifyCredentials with additional checks).
+    // The `existingFabricId` is passed for UpdateNOC, and must match the Fabric, to make sure that we are
+    // not trying to change FabricID with UpdateNOC. If set to kUndefinedFabricIndex, we are doing an add and
```
Comment (bzbarsky-apple) [inline src/credentials/FabricTable.h:192]:
```suggestion
    // not trying to change FabricID with UpdateNOC. If set to kUndefinedFabricId, we are doing an add and
```

File: src/credentials/FabricTable.h [hunk 40]
```diff
@@ -465,6 +489,86 @@ class DLL_EXPORT FabricTable
...
+    CHIP_ERROR SignWithOpKeypair(FabricIndex fabricIndex, ByteSpan message, Crypto::P256ECDSASignature & outSignature) const;
+
+    /**
+     * This initializes a new keypair for the given fabric and generates a CSR for it,
+     * so that it can be passed in a CSRResponse.
+     *
+     * The keypair is temporary and becomes usable for `SignWithOpKeypair` only after either
+     * `ActivatePendingOperationalKey` is called. It is destroyed if
+     * `RevertPendingFabricData` is called before `CommitPendingFabricData`.
+     *  If a pending keypair already existed, it is replaced by this call.
```
Comment (bzbarsky-apple) [inline src/credentials/FabricTable.h:517]:
```suggestion
     *  If a pending keypair for the desired fabricIndex already existed, it is replaced by this call.
```

File: src/crypto/OperationalKeystore.h [hunk 41]
```diff
@@ -0,0 +1,157 @@
...
+     * @brief Permanently remove the keypair associated with a fabric
+     *
+     * This is to be used for fail-safe handling and RemoveFabric.  Removes both the
+     * pending operational keypair for the fabricIndex (if any) and the committed one (if any).
+     *
+     * @param fabricIndex - FabricIndex for which to remove the keypair
+     *
+     * @retval CHIP_NO_ERROR on success
+     * @retval CHIP_ERROR_INCORRECT_STATE if the key store is not properly initialized.
+     * @retval CHIP_ERROR_INVALID_FABRIC_INDEX if there is no pending operational keypair for `fabricIndex`
```
Comment (bzbarsky-apple) [inline src/crypto/OperationalKeystore.h:115]:
```suggestion
     * @retval CHIP_ERROR_INVALID_FABRIC_INDEX if there is no operational keypair for `fabricIndex`
```

**Review by bzbarsky-apple — APPROVED** [review]
