### PR TITLE
Use GetConnectedDevice in TestCommand to wait for CASE session

### LINKED ISSUE #7860: chip-tool tests TestCluster is broken after "Enable CASE session establishment (#7666)"
#### Problem

chip-tool tests TestClusters is broken:

Initial pairing:
```
[1624494664.846274][1749867] CHIP:IN: TransportMgr initialized
[1624494664.846299][1749867] CHIP:DIS: Init admin pairing table with server storage
[1624494664.846399][1749867] CHIP:IN: Loading certs from KVS
[1624494664.846409][1749867] CHIP:IN: local node id is 0x000000000001B669
[1624494664.847036][1749867] CHIP:DL: MDNS failed to join multicast group on enx00e04c002cc7 for address type IPv4: Inet Error 1016 (0x000003F8): Address not found
[1624494664.847073][1749867] CHIP:ZCL: Using ZAP configuration...
[1624494664.847098][1749867] CHIP:ZCL: deactivate report event
[1624494664.847105][1749867] CHIP:CTL: Getting operational keys
[1624494664.847109][1749867] CHIP:CTL: Generating credentials
[1624494664.847223][1749867] CHIP:CTL: Loaded credentials successfully
[1624494664.847320][1749875] CHIP:DL: CHIP task running
[1624494664.847375][1749867] CHIP:SC: Assigned local session key ID 25
[1624494664.847438][1749867] CHIP:IN: Message appended to BLE send queue
[1624494664.847444][1749867] CHIP:SC: Sent PBKDF param request
[1624494664.847903][1749876] CHIP:DL: TRACE: Bluez mainloop starting Thread
[1624494664.848022][1749871] CHIP:DL: TRACE: Bus acquired for name C-b36b
[1624494664.851782][1749875] CHIP:DL: PlatformBlueZInit init success
[1624494664.853991][1749871] CHIP:BLE: BLE removing known devices.
[1624494664.854010][1749871] CHIP:BLE: BLE initiating scan.
[1624494664.989681][1749871] CHIP:BLE: New device scanned: 67:E9:7E:06:AF:6B
[1624494664.989705][1749871] CHIP:BLE: Device discriminator match. Attempting to connect.
[1624494664.993670][1749871] CHIP:BLE: Scan complete notification without an active scan.
[1624494665.156233][1749871] CHIP:DL: ConnectDevice complete
[1624494666.137502][1749871] CHIP:DL: Char1 /org/bluez/hci0/dev_67_E9_7E_06_AF_6B/service0006
[1624494666.137527][1749871] CHIP:DL: Char1 /org/bluez/hci0/dev_67_E9_7E_06_AF_6B/service000a
[1624494666.137535][1749871] CHIP:DL: Char1 /org/bluez/hci0/dev_67_E9_7E_06_AF_6B/service0006
[1624494666.137540][1749871] CHIP:DL: Char1 /org/bluez/hci0/dev_67_E9_7E_06_AF_6B/service000a
[1624494666.137547][1749871] CHIP:DL: Char1 /org/bluez/hci0/dev_67_E9_7E_06_AF_6B/service0006
[1624494666.137552][1749871] CHIP:DL: Char1 /org/bluez/hci0/dev_67_E9_7E_06_AF_6B/service000a
[1624494666.137562][1749871] CHIP:DL: Char1 /org/bluez/hci0/dev_67_E9_7E_06_AF_6B/service000a
[1624494666.137567][1749871] CHIP:DL: Char1 /org/bluez/hci0/dev_67_E9_7E_06_AF_6B/service000a
[1624494666.137576][1749871] CHIP:DL: Char1 /org/bluez/hci0/dev_67_E9_7E_06_AF_6B/service000a
[1624494666.137581][1749871] CHIP:DL: Char1 /org/bluez/hci0/dev_67_E9_7E_06_AF_6B/service000a
[1624494666.137588][1749871] CHIP:DL: Char1 /org/bluez/hci0/dev_67_E9_7E_06_AF_6B/service000a
[1624494666.137593][1749871] CHIP:DL: Char1 /org/bluez/hci0/dev_67_E9_7E_06_AF_6B/service000a
[1624494666.137601][1749871] CHIP:DL: New BLE connection 0x7f4a000324c0, device 67:E9:7E:06:AF:6B, path /org/bluez/hci0/dev_67_E9_7E_06_AF_6B
[1624494666.137665][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16385
[1624494666.137687][1749875] CHIP:IN: BleConnectionComplete: endPoint 0x5598d75208e0
[1624494666.520203][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494666.617871][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16388
[1624494666.617891][1749875] CHIP:BLE: subscribe complete, ep = 0x5598d75208e0
[1624494666.618372][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494666.618435][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494666.618460][1749875] CHIP:BLE: peripheral chose BTP version 3; central expected between 2 and 3
[1624494666.618471][1749875] CHIP:BLE: using BTP fragment sizes rx 20 / tx 128.
[1624494666.618480][1749875] CHIP:BLE: local and remote recv window size = 3
[1624494666.618541][1749875] CHIP:IN: BLE EndPoint 0x5598d75208e0 Connection Complete
[1624494666.715024][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494667.252066][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494667.252167][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494667.300451][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494667.300516][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494667.397588][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494667.398522][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494667.398582][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494667.398970][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494667.399041][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494667.495051][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494667.495907][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494667.495969][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494667.496008][1749875] CHIP:EM: Received message of type 33 and protocolId 0 on exchange 39017
[1624494667.496024][1749875] CHIP:SC: Received PBKDF param response
[1624494667.497168][1749875] CHIP:SC: Sent spake2p msg1
[1624494667.592513][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494667.593384][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494667.593450][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494670.176517][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494670.469445][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494670.469536][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494670.469928][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494670.469992][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494670.566389][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494670.567210][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494670.567292][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494670.567973][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494670.568032][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494670.663884][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494670.664703][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494670.664768][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494670.665437][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494670.665504][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494670.761373][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494670.762350][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494670.762430][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494670.762465][1749875] CHIP:EM: Received message of type 35 and protocolId 0 on exchange 39017
[1624494670.762479][1749875] CHIP:SC: Received spake2p msg2
[1624494670.762485][1749875] CHIP:SC: Peer assigned session key ID 0
[1624494670.763555][1749875] CHIP:SC: Sent spake2p msg3
[1624494670.763585][1749875] CHIP:IN: New pairing for device 0x0000000000bc5c01, key 0!!
[1624494670.763617][1749875] CHIP:CTL: Remote device completed SPAKE2+ handshake
[1624494670.763624][1749875] CHIP:CTL: Sending root certificate to the device
[1624494670.763651][1749875] CHIP:DMG: ICR moving to [Initialize]
[1624494670.763663][1749875] CHIP:DMG: ICR moving to [AddCommand]
[1624494670.763709][1749875] CHIP:IN: Secure message was encrypted: Msg ID 0
[1624494670.763723][1749875] CHIP:IN: Encrypted message 0x7f4a0a7fb1c8 from 0x000000000001B669 to 0x0000000000BC5C01 of type 8 and protocolId 5 on exchange 39018.
[1624494670.763732][1749875] CHIP:IN: Sending msg 0x7f4a0a7fb1c8 to 0x0000000000BC5C01 at utc time: 212122817 msec
[1624494670.763738][1749875] CHIP:IN: Sending secure msg on generic transport
[1624494670.763745][1749875] CHIP:IN: Secure msg send status No Error
[1624494670.763751][1749875] CHIP:DMG: ICR moving to [   Sending]
[1624494670.763757][1749875] CHIP:CTL: Sent root certificate to the device
[1624494670.858907][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494670.859544][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494670.859650][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494671.005162][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494671.151452][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494671.590699][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494671.590796][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494671.687686][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494673.102108][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494673.102189][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494673.198939][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494673.199722][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494673.199798][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494673.200510][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494673.200571][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494673.296411][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494673.297197][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494673.297260][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494673.297832][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494673.297884][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494673.297929][1749875] CHIP:IN: Secure transport received message destined to fabric 0, node 0x000000000001B669. Key ID 25
[1624494673.297971][1749875] CHIP:EM: Received message of type 9 and protocolId 5 on exchange 39018
[1624494673.297991][1749875] CHIP:DMG: InvokeCommand =
[1624494673.297997][1749875] CHIP:DMG: {
[1624494673.298001][1749875] CHIP:DMG: 	CommandList =
[1624494673.298006][1749875] CHIP:DMG: 	[
[1624494673.298010][1749875] CHIP:DMG: 		CommandDataElement =
[1624494673.298015][1749875] CHIP:DMG: 		{
[1624494673.298019][1749875] CHIP:DMG: 			CommandPath =
[1624494673.298023][1749875] CHIP:DMG: 			{
[1624494673.298028][1749875] CHIP:DMG: 				EndpointId = 0x0,
[1624494673.298032][1749875] CHIP:DMG: 				ClusterId = 0x3e,
[1624494673.298037][1749875] CHIP:DMG: 				CommandId = 0xa1,
[1624494673.298040][1749875] CHIP:DMG: 			},
[1624494673.298046][1749875] CHIP:DMG: 			
[1624494673.298050][1749875] CHIP:DMG: 			StatusElement =
[1624494673.298054][1749875] CHIP:DMG: 			{
[1624494673.298059][1749875] CHIP:DMG: 				GeneralCode = 0x0,
[1624494673.298063][1749875] CHIP:DMG: 				ProtocolId = 0x5,
[1624494673.298067][1749875] CHIP:DMG: 				protocolCode = 0x0,
[1624494673.298071][1749875] CHIP:DMG: 			},
[1624494673.298075][1749875] CHIP:DMG: 			
[1624494673.298079][1749875] CHIP:DMG: 		},
[1624494673.298085][1749875] CHIP:DMG: 		
[1624494673.298089][1749875] CHIP:DMG: 	],
[1624494673.298094][1749875] CHIP:DMG: 	
[1624494673.298098][1749875] CHIP:DMG: }
[1624494673.298108][1749875] CHIP:ZCL: DefaultResponse:
[1624494673.298112][1749875] CHIP:ZCL:   Transaction: 0x5598d751ed58
[1624494673.298116][1749875] CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
[1624494673.298121][1749875] CHIP:CTL: Device confirmed that it has received the root certificate
[1624494673.298126][1749875] CHIP:CTL: Sending OpCSR request to 0x7ffec1541f70 device
[1624494673.298174][1749875] CHIP:DMG: ICR moving to [Initialize]
[1624494673.298183][1749875] CHIP:DMG: ICR moving to [AddCommand]
[1624494673.298207][1749875] CHIP:IN: Secure message was encrypted: Msg ID 1
[1624494673.298217][1749875] CHIP:IN: Encrypted message 0x7f4a0a7faed8 from 0x000000000001B669 to 0x0000000000BC5C01 of type 8 and protocolId 5 on exchange 39019.
[1624494673.298224][1749875] CHIP:IN: Sending msg 0x7f4a0a7faed8 to 0x0000000000BC5C01 at utc time: 212125352 msec
[1624494673.298228][1749875] CHIP:IN: Sending secure msg on generic transport
[1624494673.298234][1749875] CHIP:IN: Secure msg send status No Error
[1624494673.298239][1749875] CHIP:DMG: ICR moving to [   Sending]
[1624494673.298242][1749875] CHIP:CTL: Sent OpCSR request, waiting for the CSR
[1624494673.298250][1749875] CHIP:DMG: ICR moving to [Uninitiali]
[1624494673.393979][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494673.540123][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494673.541037][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494673.541103][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494674.906000][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494674.906072][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.002576][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494675.003527][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.003594][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.004253][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.004322][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.099908][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494675.100877][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.100945][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.101571][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.101636][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.197657][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494675.198423][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.198482][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.199071][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.199130][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.295164][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494675.295965][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.296038][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.296605][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.296677][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.392697][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494675.393504][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.393568][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.394012][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.394073][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.490151][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494675.490994][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.491080][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.491733][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.491813][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.587536][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494675.588449][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.588552][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.589203][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.589265][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.685054][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494675.686033][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.686110][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.686688][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.686766][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.782583][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494675.783361][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.783443][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.784047][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494675.784104][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494675.784162][1749875] CHIP:IN: Secure transport received message destined to fabric 0, node 0x000000000001B669. Key ID 25
[1624494675.784214][1749875] CHIP:EM: Received message of type 9 and protocolId 5 on exchange 39019
[1624494675.784243][1749875] CHIP:DMG: InvokeCommand =
[1624494675.784254][1749875] CHIP:DMG: {
[1624494675.784263][1749875] CHIP:DMG: 	CommandList =
[1624494675.784272][1749875] CHIP:DMG: 	[
[1624494675.784281][1749875] CHIP:DMG: 		CommandDataElement =
[1624494675.784289][1749875] CHIP:DMG: 		{
[1624494675.784297][1749875] CHIP:DMG: 			CommandPath =
[1624494675.784307][1749875] CHIP:DMG: 			{
[1624494675.784317][1749875] CHIP:DMG: 				EndpointId = 0x0,
[1624494675.784327][1749875] CHIP:DMG: 				ClusterId = 0x3e,
[1624494675.784336][1749875] CHIP:DMG: 				CommandId = 0x5,
[1624494675.784344][1749875] CHIP:DMG: 			},
[1624494675.784355][1749875] CHIP:DMG: 			
[1624494675.784362][1749875] CHIP:DMG: 			CommandData = 
[1624494675.784372][1749875] CHIP:DMG: 			{
[1624494675.784381][1749875] CHIP:DMG: 				0x0 = [
[1624494675.784411][1749875] CHIP:DMG: 					0x30, 0x81, 0xca, 0x30, 0x70, 0x2, 0x1, 0x0, 0x30, 0xe, 0x31, 0xc, 0x30, 0xa, 0x6, 0x3, 0x55, 0x4, 0xa, 0xc, 0x3, 0x43, 0x53, 0x52, 0x30, 0x59, 0x30, 0x13, 0x6, 0x7, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x2, 0x1, 0x6, 0x8, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x3,
[1624494675.784423][1749875] CHIP:DMG: 			]
[1624494675.784432][1749875] CHIP:DMG: 				0x1 = [
[1624494675.784451][1749875] CHIP:DMG: 					0x42, 0x40, 0x30, 0x12, 0x5a, 0xeb, 0xb0, 0xeb, 0xcf, 0xce, 0x3, 0x3, 0xf9, 0xce, 0x34, 0x2a, 0xfa, 0xd1, 0xfc, 0xb1, 0x38, 0x92, 0x5e, 0x6a, 0xb6, 0x2f, 0x72, 0xd4, 0xa8, 0xf5, 0x9a, 0x1d, 
[1624494675.784460][1749875] CHIP:DMG: 			]
[1624494675.784469][1749875] CHIP:DMG: 				0x2 = [
[1624494675.784478][1749875] CHIP:DMG: 					
[1624494675.784486][1749875] CHIP:DMG: 			]
[1624494675.784495][1749875] CHIP:DMG: 				0x3 = [
[1624494675.784502][1749875] CHIP:DMG: 					
[1624494675.784509][1749875] CHIP:DMG: 			]
[1624494675.784517][1749875] CHIP:DMG: 				0x4 = [
[1624494675.784524][1749875] CHIP:DMG: 					
[1624494675.784533][1749875] CHIP:DMG: 			]
[1624494675.784541][1749875] CHIP:DMG: 				0x5 = [
[1624494675.784549][1749875] CHIP:DMG: 					
[1624494675.784557][1749875] CHIP:DMG: 			]
[1624494675.784567][1749875] CHIP:DMG: 			},
[1624494675.784575][1749875] CHIP:DMG: 		},
[1624494675.784588][1749875] CHIP:DMG: 		
[1624494675.784595][1749875] CHIP:DMG: 	],
[1624494675.784609][1749875] CHIP:DMG: 	
[1624494675.784617][1749875] CHIP:DMG: }
[1624494675.784641][1749875] CHIP:ZCL: Received Cluster Command: Cluster=3e Command=5 Endpoint=0
[1624494675.784657][1749875] CHIP:ZCL: OpCSRResponse:
[1624494675.784666][1749875] CHIP:ZCL:   CSR: 205
[1624494675.784674][1749875] CHIP:ZCL:   CSRNonce: 32
[1624494675.784681][1749875] CHIP:ZCL:   VendorReserved1: 0
[1624494675.784689][1749875] CHIP:ZCL:   VendorReserved2: 0
[1624494675.784696][1749875] CHIP:ZCL:   VendorReserved3: 0
[1624494675.784703][1749875] CHIP:ZCL:   Signature: 0
[1624494675.784712][1749875] CHIP:CTL: Received certificate signing request from the device
[1624494675.784727][1749875] CHIP:CTL: Generating operational certificate for device 0000000000BC5C01
[1624494675.785546][1749875] CHIP:CTL: Getting intermediate CA certificate from the issuer
[1624494675.785564][1749875] CHIP:CTL: GetIntermediateCACertificate returned 4190
[1624494675.785569][1749875] CHIP:CTL: Intermediate CA is not needed
[1624494675.785610][1749875] CHIP:CTL: Sending operational certificate to the device
[1624494675.785630][1749875] CHIP:DMG: ICR moving to [Initialize]
[1624494675.785643][1749875] CHIP:DMG: ICR moving to [AddCommand]
[1624494675.785688][1749875] CHIP:IN: Secure message was encrypted: Msg ID 2
[1624494675.785708][1749875] CHIP:IN: Encrypted message 0x7f4a0a7fab88 from 0x000000000001B669 to 0x0000000000BC5C01 of type 8 and protocolId 5 on exchange 39020.
[1624494675.785722][1749875] CHIP:IN: Sending msg 0x7f4a0a7fab88 to 0x0000000000BC5C01 at utc time: 212127839 msec
[1624494675.785730][1749875] CHIP:IN: Sending secure msg on generic transport
[1624494675.785740][1749875] CHIP:IN: Secure msg send status No Error
[1624494675.785748][1749875] CHIP:DMG: ICR moving to [   Sending]
[1624494675.785756][1749875] CHIP:CTL: Sent operational certificate to the device
[1624494675.785778][1749875] CHIP:DMG: ICR moving to [Uninitiali]
[1624494675.880349][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494676.026511][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494676.027248][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494676.027329][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494676.172727][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494676.318905][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494676.319701][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494676.319799][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494676.563374][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494676.563463][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494676.660011][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494676.661034][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494676.661102][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494676.661729][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494676.661787][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494676.757667][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494676.758474][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494676.758522][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494676.758931][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494676.758994][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494676.759058][1749875] CHIP:IN: Secure transport received message destined to fabric 0, node 0x000000000001B669. Key ID 25
[1624494676.759101][1749875] CHIP:EM: Received message of type 9 and protocolId 5 on exchange 39020
[1624494676.759121][1749875] CHIP:DMG: InvokeCommand =
[1624494676.759130][1749875] CHIP:DMG: {
[1624494676.759137][1749875] CHIP:DMG: 	CommandList =
[1624494676.759144][1749875] CHIP:DMG: 	[
[1624494676.759149][1749875] CHIP:DMG: 		CommandDataElement =
[1624494676.759156][1749875] CHIP:DMG: 		{
[1624494676.759162][1749875] CHIP:DMG: 			CommandPath =
[1624494676.759168][1749875] CHIP:DMG: 			{
[1624494676.759175][1749875] CHIP:DMG: 				EndpointId = 0x0,
[1624494676.759182][1749875] CHIP:DMG: 				ClusterId = 0x3e,
[1624494676.759188][1749875] CHIP:DMG: 				CommandId = 0x6,
[1624494676.759196][1749875] CHIP:DMG: 			},
[1624494676.759208][1749875] CHIP:DMG: 			
[1624494676.759233][1749875] CHIP:DMG: 			StatusElement =
[1624494676.759244][1749875] CHIP:DMG: 			{
[1624494676.759254][1749875] CHIP:DMG: 				GeneralCode = 0x0,
[1624494676.759264][1749875] CHIP:DMG: 				ProtocolId = 0x5,
[1624494676.759273][1749875] CHIP:DMG: 				protocolCode = 0x0,
[1624494676.759282][1749875] CHIP:DMG: 			},
[1624494676.759292][1749875] CHIP:DMG: 			
[1624494676.759298][1749875] CHIP:DMG: 		},
[1624494676.759310][1749875] CHIP:DMG: 		
[1624494676.759317][1749875] CHIP:DMG: 	],
[1624494676.759326][1749875] CHIP:DMG: 	
[1624494676.759335][1749875] CHIP:DMG: }
[1624494676.759353][1749875] CHIP:ZCL: DefaultResponse:
[1624494676.759362][1749875] CHIP:ZCL:   Transaction: 0x5598d751ed58
[1624494676.759370][1749875] CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
[1624494676.759379][1749875] CHIP:CTL: Device confirmed that it has received the operational certificate
[1624494676.759388][1749875] CHIP:CTL: Operational credentials provisioned on device 0x7ffec1541f70
[1624494676.760188][1749875] CHIP:TOO: Secure Pairing Success
[1624494676.760786][1749875] CHIP:TOO: Pairing Success
[1624494676.760845][1749875] CHIP:DMG: ICR moving to [Initialize]
[1624494676.760865][1749875] CHIP:DMG: ICR moving to [AddCommand]
[1624494676.760881][1749875] CHIP:IN: Connection from 'BLE' expired
[1624494676.760894][1749875] CHIP:CTL: OnConnectionExpired was called for unknown device, ignoring it.
[1624494676.760906][1749875] CHIP:IN: New pairing for device 0x0000000000bc5c01, key 0!!
[1624494676.761002][1749875] CHIP:IN: Secure message was encrypted: Msg ID 4
[1624494676.761017][1749875] CHIP:IN: Encrypted message 0x7f4a0a7fae28 from 0x000000000001B669 to 0x0000000000BC5C01 of type 8 and protocolId 5 on exchange 39021.
[1624494676.761028][1749875] CHIP:IN: Sending msg 0x7f4a0a7fae28 to 0x0000000000BC5C01 at utc time: 212128815 msec
[1624494676.761038][1749875] CHIP:IN: Sending secure msg on generic transport
[1624494676.761047][1749875] CHIP:IN: Secure msg send status No Error
[1624494676.761053][1749875] CHIP:DMG: ICR moving to [   Sending]
[1624494676.761071][1749875] CHIP:DMG: ICR moving to [Uninitiali]
[1624494676.855271][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494677.001451][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494677.002199][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494677.002274][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494677.099467][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494677.099545][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494677.196510][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494677.197237][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494677.197309][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494677.197869][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494677.197940][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494677.293891][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494677.294753][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494677.294824][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494677.295283][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494677.295352][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494677.295426][1749875] CHIP:IN: Secure transport received message destined to fabric 0, node 0x000000000001B669. Key ID 25
[1624494677.295479][1749875] CHIP:EM: Received message of type 9 and protocolId 5 on exchange 39021
[1624494677.295509][1749875] CHIP:DMG: InvokeCommand =
[1624494677.295525][1749875] CHIP:DMG: {
[1624494677.295535][1749875] CHIP:DMG: 	CommandList =
[1624494677.295545][1749875] CHIP:DMG: 	[
[1624494677.295554][1749875] CHIP:DMG: 		CommandDataElement =
[1624494677.295564][1749875] CHIP:DMG: 		{
[1624494677.295573][1749875] CHIP:DMG: 			CommandPath =
[1624494677.295584][1749875] CHIP:DMG: 			{
[1624494677.295594][1749875] CHIP:DMG: 				EndpointId = 0x0,
[1624494677.295604][1749875] CHIP:DMG: 				ClusterId = 0x31,
[1624494677.295613][1749875] CHIP:DMG: 				CommandId = 0x2,
[1624494677.295621][1749875] CHIP:DMG: 			},
[1624494677.295629][1749875] CHIP:DMG: 			
[1624494677.295635][1749875] CHIP:DMG: 			StatusElement =
[1624494677.295641][1749875] CHIP:DMG: 			{
[1624494677.295647][1749875] CHIP:DMG: 				GeneralCode = 0x0,
[1624494677.295653][1749875] CHIP:DMG: 				ProtocolId = 0x5,
[1624494677.295659][1749875] CHIP:DMG: 				protocolCode = 0x0,
[1624494677.295665][1749875] CHIP:DMG: 			},
[1624494677.295671][1749875] CHIP:DMG: 			
[1624494677.295677][1749875] CHIP:DMG: 		},
[1624494677.295685][1749875] CHIP:DMG: 		
[1624494677.295690][1749875] CHIP:DMG: 	],
[1624494677.295698][1749875] CHIP:DMG: 	
[1624494677.295704][1749875] CHIP:DMG: }
[1624494677.295718][1749875] CHIP:ZCL: DefaultResponse:
[1624494677.295724][1749875] CHIP:ZCL:   Transaction: 0x5598d751ee68
[1624494677.295729][1749875] CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
[1624494677.295737][1749875] CHIP:TOO: AddNetworkResponse
[1624494677.295750][1749875] CHIP:DMG: ICR moving to [Initialize]
[1624494677.295777][1749875] CHIP:DMG: ICR moving to [AddCommand]
[1624494677.295812][1749875] CHIP:IN: Secure message was encrypted: Msg ID 5
[1624494677.295824][1749875] CHIP:IN: Encrypted message 0x7f4a0a7faee8 from 0x000000000001B669 to 0x0000000000BC5C01 of type 8 and protocolId 5 on exchange 39022.
[1624494677.295833][1749875] CHIP:IN: Sending msg 0x7f4a0a7faee8 to 0x0000000000BC5C01 at utc time: 212129350 msec
[1624494677.295839][1749875] CHIP:IN: Sending secure msg on generic transport
[1624494677.295846][1749875] CHIP:IN: Secure msg send status No Error
[1624494677.295852][1749875] CHIP:DMG: ICR moving to [   Sending]
[1624494677.295862][1749875] CHIP:DMG: ICR moving to [Uninitiali]
[1624494677.391474][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494677.488792][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494677.489616][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494677.489698][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494677.733250][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494677.733332][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494677.878958][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494677.879698][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494677.879769][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494677.880279][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494677.880327][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494678.073973][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494678.074874][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494678.074937][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494678.075280][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494678.075352][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494678.075407][1749875] CHIP:IN: Secure transport received message destined to fabric 0, node 0x000000000001B669. Key ID 25
[1624494678.075444][1749875] CHIP:EM: Received message of type 9 and protocolId 5 on exchange 39022
[1624494678.075463][1749875] CHIP:DMG: InvokeCommand =
[1624494678.075470][1749875] CHIP:DMG: {
[1624494678.075476][1749875] CHIP:DMG: 	CommandList =
[1624494678.075482][1749875] CHIP:DMG: 	[
[1624494678.075487][1749875] CHIP:DMG: 		CommandDataElement =
[1624494678.075493][1749875] CHIP:DMG: 		{
[1624494678.075498][1749875] CHIP:DMG: 			CommandPath =
[1624494678.075504][1749875] CHIP:DMG: 			{
[1624494678.075511][1749875] CHIP:DMG: 				EndpointId = 0x0,
[1624494678.075520][1749875] CHIP:DMG: 				ClusterId = 0x31,
[1624494678.075529][1749875] CHIP:DMG: 				CommandId = 0xc,
[1624494678.075536][1749875] CHIP:DMG: 			},
[1624494678.075546][1749875] CHIP:DMG: 			
[1624494678.075554][1749875] CHIP:DMG: 			StatusElement =
[1624494678.075562][1749875] CHIP:DMG: 			{
[1624494678.075571][1749875] CHIP:DMG: 				GeneralCode = 0x0,
[1624494678.075579][1749875] CHIP:DMG: 				ProtocolId = 0x5,
[1624494678.075588][1749875] CHIP:DMG: 				protocolCode = 0x0,
[1624494678.075595][1749875] CHIP:DMG: 			},
[1624494678.075604][1749875] CHIP:DMG: 			
[1624494678.075612][1749875] CHIP:DMG: 		},
[1624494678.075623][1749875] CHIP:DMG: 		
[1624494678.075630][1749875] CHIP:DMG: 	],
[1624494678.075637][1749875] CHIP:DMG: 	
[1624494678.075642][1749875] CHIP:DMG: }
[1624494678.075655][1749875] CHIP:ZCL: DefaultResponse:
[1624494678.075660][1749875] CHIP:ZCL:   Transaction: 0x5598d751ed58
[1624494678.075665][1749875] CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
[1624494678.075672][1749875] CHIP:TOO: EnableNetworkResponse
[1624494678.075677][1749875] CHIP:TOO: Mdns: Updating NodeId: bc5c01 FabricId: 1b669 ...
[1624494678.075818][1749875] CHIP:DIS: mDNS broadcast success
[1624494678.075917][1749875] CHIP:DIS: mDNS broadcast success
[1624494678.075989][1749875] CHIP:DIS: mDNS broadcast success
[1624494678.076037][1749875] CHIP:DIS: mDNS broadcast success
[1624494678.076086][1749875] CHIP:DIS: mDNS broadcast success
[1624494678.076106][1749875] CHIP:DMG: ICR moving to [Uninitiali]
[1624494678.220229][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1624494680.658294][1749871] CHIP:DL: Indication received, conn = 0x7f4a000324c0
[1624494680.658385][1749875] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1624494683.058003][1749875] CHIP:TOO: OnAddressUpdateComplete: No Error
[1624494683.058024][1749875] CHIP:CTL: OperationalDiscoveryComplete for device ID 12344321
[1624494683.058031][1749875] CHIP:CTL: Enabling CASE session establishment for the device
[1624494683.058321][1749875] CHIP:IN: Connection from 'UDP:10.1.0.113:11097' expired
[1624494683.059230][1749875] CHIP:SC: Sent SigmaR1 msg
[1624494683.059299][1749875] CHIP:TOO: OnAddressUpdateComplete: CHIP Error 4003 (0x00000FA3): Incorrect state
[1624494683.059316][1749875] CHIP:CTL: OperationalDiscoveryComplete for device ID 12344321
[1624494683.059322][1749875] CHIP:CTL: Operational certificates already provisioned for this device
[1624494683.059333][1749867] CHIP:TOO: Run command failure: CHIP Error 4172 (0x0000104C): Internal error
[1624494683.060057][1749867] CHIP:CTL: Shutting down the commissioner
[1624494683.060070][1749867] CHIP:CTL: Shutting down the controller
[1624494683.060074][1749867] CHIP:DL: Inet Layer shutdown
[1624494683.060095][1749874] CHIP:IN: Async DNS worker thread woke up.
[1624494683.060111][1749874] CHIP:IN: Async DNS worker thread exiting.
[1624494683.060113][1749873] CHIP:IN: Async DNS worker thread woke up.
[1624494683.060121][1749873] CHIP:IN: Async DNS worker thread exiting.
[1624494683.060230][1749867] CHIP:DL: BLE layer shutdown
[1624494683.060247][1749867] CHIP:IN: Clearing BLE pending packets.
[1624494683.060278][1749867] CHIP:BLE: Auto-closing end point's BLE connection.
[1624494683.060286][1749867] CHIP:DL: Closing BLE GATT connection (con 0x7f4a000324c0)
[1624494683.060299][1749867] CHIP:DL: System Layer shutdown
[1624494683.060390][1749871] CHIP:DL: BluezDisconnect peer=67:E9:7E:06:AF:6B
```

Run tests:
```
./chip-tool tests TestCluster
[1624494697.331748][1750248] CHIP:IN: TransportMgr initialized
[1624494697.331768][1750248] CHIP:DIS: Init admin pairing table with server storage
[1624494697.331869][1750248] CHIP:IN: Loading certs from KVS
[1624494697.331881][1750248] CHIP:IN: local node id is 0x000000000001B669
[1624494697.332509][1750248] CHIP:DL: MDNS failed to join multicast group on enx00e04c002cc7 for address type IPv4: Inet Error 1016 (0x000003F8): Address not found
[1624494697.332545][1750248] CHIP:ZCL: Using ZAP configuration...
[1624494697.332565][1750248] CHIP:ZCL: deactivate report event
[1624494697.332571][1750248] CHIP:CTL: Getting operational keys
[1624494697.332573][1750248] CHIP:CTL: Generating credentials
[1624494697.332663][1750248] CHIP:CTL: Loaded credentials successfully
[1624494697.332752][1750256] CHIP:DL: CHIP task running
[1624494697.332791][1750248] CHIP:TOO: Test Cluster - Send Test Command: Sending command...
[1624494697.332806][1750248] CHIP:DMG: ICR moving to [Initialize]
[1624494697.332810][1750248] CHIP:DMG: ICR moving to [AddCommand]
[1624494697.333051][1750248] CHIP:SC: Sent SigmaR1 msg
[1624494697.333071][1750248] CHIP:-: CHIP Error 4072 (0x00000FE8): Not connected at ../../src/app/CommandSender.cpp:75
[1624494697.333074][1750248] CHIP:DMG: ICR moving to [Uninitiali]
[1624494697.333078][1750248] CHIP:TOO: TestCluster: CHIP Error 4072 (0x00000FE8): Not connected
[1624494697.333085][1750248] CHIP:TOO: Run command failure: CHIP Error 4072 (0x00000FE8): Not connected
[1624494697.333216][1750248] CHIP:CTL: Shutting down the commissioner
[1624494697.333223][1750248] CHIP:CTL: Shutting down the controller
[1624494697.333225][1750248] CHIP:DL: Inet Layer shutdown
[1624494697.333254][1750255] CHIP:IN: Async DNS worker thread woke up.
[1624494697.333277][1750255] CHIP:IN: Async DNS worker thread exiting.
[1624494697.333293][1750254] CHIP:IN: Async DNS worker thread woke up.
[1624494697.333314][1750254] CHIP:IN: Async DNS worker thread exiting.
[1624494697.333511][1750248] CHIP:DL: BLE layer shutdown
[1624494697.333518][1750248] CHIP:DL: System Layer shutdown
```

@pan-apple @vivien-apple

### PR DESCRIPTION
**Pull request by pan-apple**
#### Problem
Fixes #7860 chip-tool tests TestCluster is broken after "Enable CASE session establishment

#### Change overview
Use `GetConnectedDevice()` API to get a callback on CASE session establishment, for test commands.

#### Testing
Ran the tests using `chip-tool tests TestCluster`
Note: need this PR to fix some packet buffer and memory leaks. https://github.com/project-chip/connectedhomeip/pull/7852
Without #7852, the device may reboot after a few CASE session establishments due to memory allocation failures.

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

File: examples/chip-tool/commands/tests/TestCommand.cpp [hunk 1]
```diff
@@ -24,9 +24,21 @@ CHIP_ERROR TestCommand::Run()
...
+    err = ctx->commissioner->GetConnectedDevice(ctx->remoteId, &mOnDeviceConnectedCallback, &mOnDeviceConnectionFailureCallback);
     ReturnErrorOnFailure(err);
 
-    NextTest();
     return CHIP_NO_ERROR;
 }
+
+void TestCommand::OnDeviceConnectedFn(void * context, chip::Controller::Device * device)
+{
+    TestCommand * command = reinterpret_cast<TestCommand *>(context);
```
Comment (bzbarsky-apple) [inline examples/chip-tool/commands/tests/TestCommand.cpp:35]:
```suggestion
    auto * command = static_cast<TestCommand *>(context);
```

File: examples/chip-tool/commands/tests/TestCommand.cpp [hunk 2]
```diff
@@ -24,9 +24,21 @@ CHIP_ERROR TestCommand::Run()
...
+    VerifyOrReturn(command != nullptr, ChipLogError(chipTool, "Device connected, but cannot run the test, as the context is null"));
+    command->mDevice = device;
+    command->NextTest();
+}
+
+void TestCommand::OnDeviceConnectionFailureFn(void * context, NodeId deviceId, CHIP_ERROR error)
+{
+    ChipLogError(chipTool, "Failed in connecting to the device %" PRIu64 ". Error %d", deviceId, error);
+}
```
Comment (bzbarsky-apple) [inline examples/chip-tool/commands/tests/TestCommand.cpp:44]: Doesn't this need to `command->SetCommandExitStatus(error);` so the test will actually terminate instead of waiting to time out?

**Review by msandstedt — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by mspang — APPROVED** [review]
