### PR TITLE
[ICD-server] Replace the event/queue based logic with a notifier

### LINKED ISSUE #29450: [BUG] [ICD] Failed to switch to Idle mode if the device fails to post `kChipMsgRxEventHandled` event
### Reproduction steps

We will post a event `kChipMsgSentEvent` when an exchange context sends a message that expects response. This event will increase the `expectedMsgCount` in `ICDEventManager` by one. And another event `kChipMsgRxEventHandled` will be post when the device receives a response or the ResponseTimer is triggered. This event will decrease the `expectedMsgCount` in `ICDEventManager` by one.

If the `kChipMsgSentEvent` event is post but the device fails to post `kChipMsgRxEventHandled` event. The  `expectedMsgCount` in `ICDEventManager` will never be decreased to 0 and the device will never switch to Idle mode if we don't reboot the device.

### Bug prevalence

Sometimes

### GitHub hash of the SDK that was being used

6bb0b716bc19c0e52d25a1812bc729ca202123b5

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jmartinez-silabs**
fixes #29450

- Replace the ICDEventManager and its event queue logic with the ICDNotifier (Subject/observer pattern). This removes the risk of the event queue being full and failing to post events which can get the ICD stuck in active mode.
- Rework the messaging Keep active requirements. Now it is purely tied to Open ExchangeContexts.
- Messages sent and received now trigger a "NetworkActivity" which kicks an active Threshold
- Tweak some ICDManager logic to account for SIT with active interval and active threshold of 0 ms allowing cleaner transitions for those settings.

### CODE REVIEW

File: src/app/icd/ICDManager.cpp [hunk 1]
```diff
@@ -233,5 +259,69 @@ void ICDManager::OnTransitionToIdle(System::Layer * aLayer, void * appState)
     pIcdManager->mStateObserver->OnTransitionToIdle();
 }
 
+bool ICDManager::EnsureChipStackLock()
+{
```
Comment (jtung-apple) [inline src/app/icd/ICDManager.cpp:263]: Should `#if CHIP_STACK_LOCK_TRACKING_ENABLED` be used here?

Comment (jmartinez-silabs) [reply src/app/icd/ICDManager.cpp:263]: True, I will add it

**Review by mkardous-silabs — APPROVED** [review]

File: examples/platform/silabs/BaseApplication.cpp [hunk 2]
```diff
@@ -505,13 +506,9 @@ void BaseApplication::ButtonHandler(AppEvent * aEvent)
...
                 SILABS_LOG("Network is already provisioned, Ble advertissement not enabled");
-                DeviceLayer::ChipDeviceEvent event;
-                event.Type     = DeviceLayer::DeviceEventType::kAppWakeUpEvent;
-                CHIP_ERROR err = DeviceLayer::PlatformMgr().PostEvent(&event);
-                if (err != CHIP_NO_ERROR)
-                {
-                    ChipLogError(AppServer, "Failed to post App wake up Event event %" CHIP_ERROR_FORMAT, err.Format());
-                }
+#if CHIP_CONFIG_ENABLE_ICD_SERVER
+                GetICDNotifier()->NetworkActivity();
```
[the remark this answers is not in the document]
Comment (jmartinez-silabs) [reply examples/platform/silabs/BaseApplication.cpp:510]: This will become something else when it is well defined in the spec. similar to the `StayActiveRequest Command` Currently it only triggers 1 active Threshold so it is the same functionality than NetWorkActivity

File: src/app/icd/BUILD.gn [hunk 3]
```diff
@@ -16,11 +16,20 @@ import("//build_overrides/chip.gni")
...
+config("notifier-config") {
+  defines =
+      [ "ICD_MAX_NOTIFICATION_SUBSCRIBERS=${icd_max_notification_subscribers}" ]
+}
 
 source_set("observer-srcs") {
   sources = [ "ICDStateObserver.h" ]
 }
 
+source_set("notifier-srcs") {
```
Comment (andy31415) [inline src/app/icd/BUILD.gn:28]: nit: I believe the `-srcs` suffix here should not be needed - generally these targets types are transparent (static_libs or source_sets) and we do not use this pattern anywhere else.

File: src/app/icd/BUILD.gn [hunk 4]
```diff
@@ -16,11 +16,20 @@ import("//build_overrides/chip.gni")
 import("icd.gni")
 
 # ICD Server sources and configurations
+config("notifier-config") {
+  defines =
+      [ "ICD_MAX_NOTIFICATION_SUBSCRIBERS=${icd_max_notification_subscribers}" ]
```
Comment (andy31415) [inline src/app/icd/BUILD.gn:21]: This adds a command-line define for compilers. This is inconvenient when integrating into 3rd party build systems that are not gn-based. It would be prefferable to use a buildconfig_header.

File: src/app/icd/ICDManager.cpp [hunk 5]
```diff
@@ -40,6 +40,16 @@ using namespace chip::app;
 using namespace chip::app::Clusters;
 using namespace chip::app::Clusters::IcdManagement;
 
+uint8_t ICDManager::OpenExchangeContextCount = 0;
+static_assert(UINT8_MAX >= CHIP_CONFIG_MAX_EXCHANGE_CONTEXTS,
+              "ICDManager::OpenExchangeContextCount cannot hold count for the max exchange count");
+
+ICDNotifier * GetICDNotifier()
```
Comment (andy31415) [inline src/app/icd/ICDManager.cpp:47]: Should this be in a separate cpp file for ICDNotifier instead of ICDManager? that way maybe we can make ICDNotifier not be all methods inline and we can put them in the cpp file as well.

File: src/app/icd/ICDManager.cpp [hunk 6]
```diff
@@ -228,5 +254,74 @@ void ICDManager::OnTransitionToIdle(System::Layer * aLayer, void * appState)
     pIcdManager->mStateObserver->OnTransitionToIdle();
 }
 
+bool ICDManager::EnsureChipStackLock()
```
Comment (andy31415) [inline src/app/icd/ICDManager.cpp:257]: please make this some form of RAII object - tracing that lock and unlock are paired is hard otherwise.

I would also generally prefer us NOT needing to do this: it is very convenient to just say "lock if needed" however that convenence means that code paths will not be as carefully reviewed and we would not know if a lock is needed or not. Also note that darwin does NOT support stack locking at all. even if we do not expect ICD production devices to run on mac, test programs should be runnable.

@bzbarsky-apple for apple opinion

File: src/app/icd/ICDManager.cpp [hunk 7]
```diff
@@ -228,5 +254,74 @@ void ICDManager::OnTransitionToIdle(System::Layer * aLayer, void * appState)
...
+    }
+    return requireLock;
+}
+
+/* ICDNotify observer functions. */
+void ICDManager::KeepActiveRequest(KeepActiveFlags request, bool set)
+{
+    bool requiresUnlock = this->EnsureChipStackLock();
+
+    if (request == KeepActiveFlags::kExchangeContextOpen)
```
Comment (andy31415) [inline src/app/icd/ICDManager.cpp:278]: nesting here feels too deep because of lack of lock RAII (or lock being needed in general). After RAII/nolock switch, please make this early-return as needed.

File: src/app/icd/ICDManager.cpp [hunk 8]
```diff
@@ -228,5 +254,74 @@ void ICDManager::OnTransitionToIdle(System::Layer * aLayer, void * appState)
...
+                ChipLogError(DeviceLayer, "The ICD Manager did not account for ExchangeContext closure");
+            }
+
+            if (this->OpenExchangeContextCount == 0)
+            {
+                this->SetKeepActiveModeRequirements(request, set);
+            }
+        }
+    }
+    else /* kCommissioningWindowOpen, kFailSafeArmed */
```
Comment (andy31415) [inline src/app/icd/ICDManager.cpp:304]: the comment should provably say `!KeepActiveFlags::kExchangeContextOpen` since that is the actual branch meaning. We could give commissioningwindowopen and failsafearmed as examples after that.

File: src/app/icd/ICDNotifier.h [hunk 9]
```diff
@@ -0,0 +1,106 @@
...
+    enum class KeepActiveFlags : uint8_t
+    {
+        kCommissioningWindowOpen = 0x01,
+        kFailSafeArmed           = 0x02,
+        kExchangeContextOpen     = 0x03,
+    };
+
+    virtual ~ICDNotify() {}
+    virtual void NotifyNetworkActivity()                              = 0;
+    virtual void KeepActiveRequest(KeepActiveFlags request, bool set) = 0;
```
Comment (andy31415) [inline src/app/icd/ICDNotifier.h:44]: Please add some documentation here - what is KeepActiveRequest supposed to do?

I was trying to review the code and understanding it, and without ICD background I could not actually figure it out.

File: src/app/icd/ICDManager.cpp [hunk 10]
```diff
@@ -228,5 +254,74 @@ void ICDManager::OnTransitionToIdle(System::Layer * aLayer, void * appState)
...
+    bool requiresUnlock = this->EnsureChipStackLock();
+
+    if (request == KeepActiveFlags::kExchangeContextOpen)
+    {
+        // There can be multiple open exchange context at the same time.
+        // Keep track of the requests count.
+        if (set)
+        {
+            this->OpenExchangeContextCount++;
+            this->SetKeepActiveModeRequirements(request, set);
```
Comment (andy31415) [inline src/app/icd/ICDManager.cpp:285]: since we know set is true here, would it be more readable to place ` true /* set */` here  and maybe `false /* set */` below?

File: src/app/icd/ICDNotifier.h [hunk 11]
```diff
@@ -0,0 +1,106 @@
...
+};
+
+class ICDNotifier
+{
+public:
+    ICDNotifier() { memset(subscribers, 0, sizeof(subscribers)); }
+    ~ICDNotifier() { memset(subscribers, 0, sizeof(subscribers)); }
+
+    void Subscribe(ICDNotify * subscriber)
```
Comment (andy31415) [inline src/app/icd/ICDNotifier.h:53]: Should these return CHIP_ERROR, e.g. if there is no space in subscribers to return a out_of_space/resources errors?

File: src/app/icd/ICDNotifier.h [hunk 12]
```diff
@@ -0,0 +1,106 @@
...
+        {
+            if (sub == subscriber)
+            {
+                sub = nullptr;
+                break;
+            }
+        }
+    }
+
+    void NetworkActivity() const
```
Comment (andy31415) [inline src/app/icd/ICDNotifier.h:77]: consider these to be named `BroadcastNetworkActivityNotification` / `BroadcastActiveRequestNotification` to make it clear what they do

File: src/app/icd/ICDNotifier.h [hunk 13]
```diff
@@ -0,0 +1,106 @@
...
+
+    virtual ~ICDNotify() {}
+    virtual void NotifyNetworkActivity()                              = 0;
+    virtual void KeepActiveRequest(KeepActiveFlags request, bool set) = 0;
+};
+
+class ICDNotifier
+{
+public:
+    ICDNotifier() { memset(subscribers, 0, sizeof(subscribers)); }
```
Comment (andy31415) [inline src/app/icd/ICDNotifier.h:50]: maybe ` = {}` where subscribers is declared is clearer for 0-initalization. Consider using std::fill in the destructor.

File: src/app/icd/ICDManager.h [hunk 14]
```diff
@@ -83,6 +80,18 @@ class ICDManager
      */
     static void OnTransitionToIdle(System::Layer * aLayer, void * appState);
 
+    /**
+     * @brief This function locks the ChipStack if the current thread didn't already do so.
+     *
+     *  Use case: Requests or notifications from the ICDNotifier can occur from a thread owning the lock already
```
Comment (andy31415) [inline src/app/icd/ICDManager.h:86]: Generally I would let the caller have a `DoFoo` and `DoFooLocked` or `DoFooAsync` to specifify if we are whithin the chip stack or not. To get into the chip stack, I believe we generally schedule a work to be performed on the chip event loop.

File: src/app/tests/TestICDManager.cpp [hunk 15]
```diff
@@ -136,45 +137,45 @@ class TestICDManager
         TestContext * ctx = static_cast<TestContext *>(aContext);
 
         // Setting a requirement will transition the ICD to active mode.
-        ctx->mICDManager.SetKeepActiveModeRequirements(ICDManager::KeepActiveFlags::kCommissioningWindowOpen, true);
+        GetICDNotifier()->ActiveRequest(ICDNotify::KeepActiveFlags::kCommissioningWindowOpen, true);
```
Comment (andy31415) [inline src/app/tests/TestICDManager.cpp:140]: How deep do true/false booeans go through the stack? I find their usage as arguments in multi-argument methods usually harder to follow/extend. For clarity, did we consider having pairs of start/stop or enter/leave or similar? I would read code like `ICDNotifier::GetInstance()->EnterActive(ICDNotify::KeepActiveFlags::kCommissioningWindowOpen)` and `ICDNotifier::GetInstance()->ExitActive(ICDNotify::KeepActiveFlags::kCommissioningWindowOpen)`

Comment (jmartinez-silabs) [reply src/app/tests/TestICDManager.cpp:140]: The boolean goes 1 level deep, but I like the idea of an enter and exit function

File: src/app/icd/ICDNotifier.h (hunk 11 above)
Comment (jmartinez-silabs) [reply src/app/icd/ICDNotifier.h:53]: Yes, it should, adding it!

File: examples/platform/silabs/BaseApplication.cpp (hunk 2 above)
Comment (bzbarsky-apple) [inline examples/platform/silabs/BaseApplication.cpp:510]: This one is strange. This isn't actually network activity...

File: src/app/FailSafeContext.cpp [hunk 16]
```diff
@@ -55,14 +56,7 @@ void FailSafeContext::SetFailSafeArmed(bool armed)
...
     {
-        DeviceLayer::ChipDeviceEvent event;
-        event.Type                = DeviceLayer::DeviceEventType::kFailSafeStateChanged;
-        event.FailSafeState.armed = armed;
-        CHIP_ERROR err            = DeviceLayer::PlatformMgr().PostEvent(&event);
-        if (err != CHIP_NO_ERROR)
-        {
-            ChipLogError(AppServer, "Failed to post kFailSafeStateChanged event %" CHIP_ERROR_FORMAT, err.Format());
-        }
+        chip::app::GetICDNotifier()->ActiveRequest(app::ICDNotify::KeepActiveFlags::kFailSafeArmed, armed);
```
Comment (bzbarsky-apple) [inline src/app/FailSafeContext.cpp:59]:
```suggestion
        GetICDNotifier()->ActiveRequest(ICDNotify::KeepActiveFlags::kFailSafeArmed, armed);
```

File: src/app/icd/ICDManager.cpp [hunk 17]
```diff
@@ -122,9 +134,14 @@ void ICDManager::UpdateOperationState(OperationalState state)
 
     if (state == OperationalState::IdleMode)
     {
-        mOperationalState         = OperationalState::IdleMode;
-        uint32_t idleModeInterval = IcdManagementServer::GetInstance().GetIdleModeIntervalSec();
-        DeviceLayer::SystemLayer().StartTimer(System::Clock::Seconds32(idleModeInterval), OnIdleModeDone, this);
+        mOperationalState = OperationalState::IdleMode;
+
+        // When the active mode interval is 0, we stay in idleMode until a notification brings the icd in active mode
```
Comment (bzbarsky-apple) [inline src/app/icd/ICDManager.cpp:139]:
```suggestion
        // When the active mode interval is 0, we stay in idleMode until a notification brings the icd into active mode
```

File: src/app/icd/ICDManager.cpp [hunk 18]
```diff
@@ -228,5 +254,74 @@ void ICDManager::OnTransitionToIdle(System::Layer * aLayer, void * appState)
...
+    // TODO implement platform agnostic lock creation/mechanism that can be used for ICD without locking the chip stack
+    bool requireLock = false;
+
+#if CHIP_STACK_LOCK_TRACKING_ENABLED
+    requireLock = !DeviceLayer::PlatformMgr().IsChipStackLockedByCurrentThread();
+#endif
+
+    if (requireLock)
+    {
+        DeviceLayer::PlatformMgr().LockChipStack();
```
Comment (bzbarsky-apple) [inline src/app/icd/ICDManager.cpp:268]: Yeah, this is a really weird pattern.  We're basically re-implementing a re-entrant lock here, which is usually hard to reason about.

What should be going on instead is that we should require the lock be held for all our public APIs, and leave synchronization to the consumer.  Who should know which thread context they are running on and hence how to call the API.

File: src/app/icd/ICDManager.cpp [hunk 19]
```diff
@@ -228,5 +254,74 @@ void ICDManager::OnTransitionToIdle(System::Layer * aLayer, void * appState)
...
+}
+
+/* ICDNotify observer functions. */
+void ICDManager::KeepActiveRequest(KeepActiveFlags request, bool set)
+{
+    bool requiresUnlock = this->EnsureChipStackLock();
+
+    if (request == KeepActiveFlags::kExchangeContextOpen)
+    {
+        // There can be multiple open exchange context at the same time.
```
Comment (bzbarsky-apple) [inline src/app/icd/ICDManager.cpp:280]:
```suggestion
        // There can be multiple open exchange contexts at the same time.
```

File: src/app/icd/ICDNotifier.h [hunk 20]
```diff
@@ -0,0 +1,106 @@
...
+#ifndef ICD_MAX_NOTIFICATION_SUBSCRIBERS
+#define ICD_MAX_NOTIFICATION_SUBSCRIBERS 1
+#endif
+
+class ICDNotify;
+
+namespace chip {
+namespace app {
+
+class ICDNotify
```
Comment (bzbarsky-apple) [inline src/app/icd/ICDNotifier.h:32]:
```suggestion
class ICDListener
```
or so?

File: src/messaging/ExchangeContext.cpp [hunk 21]
```diff
@@ -201,16 +198,9 @@ CHIP_ERROR ExchangeContext::SendMessage(Protocols::Id protocolId, uint8_t msgTyp
...
-            event.Type                       = DeviceLayer::DeviceEventType::kChipMsgSentEvent;
-            event.MessageSent.ExpectResponse = currentMessageExpectResponse;
-            CHIP_ERROR status                = DeviceLayer::PlatformMgr().PostEvent(&event);
-            if (status != CHIP_NO_ERROR)
-            {
-                ChipLogError(DeviceLayer, "Failed to post Message sent event %" CHIP_ERROR_FORMAT, status.Format());
-            }
-#endif // CONFIG_DEVICE_LAYER
+#if CHIP_CONFIG_ENABLE_ICD_SERVER
+            chip::app::GetICDNotifier()->NetworkActivity();
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeContext.cpp:202]:
```suggestion
            app::GetICDNotifier()->NetworkActivity();
```

File: src/messaging/ExchangeContext.cpp [hunk 22]
```diff
@@ -608,17 +582,10 @@ CHIP_ERROR ExchangeContext::HandleMessage(uint32_t messageCounter, const Payload
...
-    event.RxEventContext.clearsExpectedResponse = IsResponseExpected();
-    CHIP_ERROR status                           = DeviceLayer::PlatformMgr().PostEvent(&event);
-    if (status != CHIP_NO_ERROR)
-    {
-        ChipLogError(DeviceLayer, "Failed to post Message received event %" CHIP_ERROR_FORMAT, status.Format());
-    }
-#endif // CONFIG_DEVICE_LAYER && CHIP_CONFIG_ENABLE_ICD_SERVER
+#if CHIP_CONFIG_ENABLE_ICD_SERVER
+    // message received
+    chip::app::GetICDNotifier()->NetworkActivity();
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeContext.cpp:587]:
```suggestion
    app::GetICDNotifier()->NetworkActivity();
```

File: src/messaging/ReliableMessageMgr.cpp [hunk 23]
```diff
@@ -326,19 +327,9 @@ CHIP_ERROR ReliableMessageMgr::SendFromRetransTable(RetransTableEntry * entry)
...
-        event.Type                       = DeviceLayer::DeviceEventType::kChipMsgSentEvent;
-        event.MessageSent.ExpectResponse = false;
-        CHIP_ERROR status                = DeviceLayer::PlatformMgr().PostEvent(&event);
-        if (status != CHIP_NO_ERROR)
-        {
-            ChipLogError(DeviceLayer, "Failed to post retransmit message sent event %" CHIP_ERROR_FORMAT, status.Format());
-        }
-#endif // CONFIG_DEVICE_LAYER
+#if CHIP_CONFIG_ENABLE_ICD_SERVER
+        chip::app::GetICDNotifier()->NetworkActivity();
```
Comment (bzbarsky-apple) [inline src/messaging/ReliableMessageMgr.cpp:331]:
```suggestion
        app::GetICDNotifier()->NetworkActivity();
```

File: examples/platform/silabs/BaseApplication.cpp (hunk 2 above)
Comment (jmartinez-silabs) [reply examples/platform/silabs/BaseApplication.cpp:510]: It is temporary right now to add User action triggers to wakeup the device. I am adding a comment to mention this. There will be a better option soon.

File: src/app/icd/BUILD.gn (hunk 4 above)
Comment (jmartinez-silabs) [reply src/app/icd/BUILD.gn]: moved it to the `app_buildconfig` buildconfig_header

File: src/app/icd/ICDManager.cpp (hunk 6 above)
Comment (jmartinez-silabs) [reply src/app/icd/ICDManager.cpp]: remove this internal lock mechanism from the ICDManager. the ICDNotifier is expected to be used from the chipT ask context

File: src/app/icd/ICDManager.cpp (hunk 18 above)
Comment (jmartinez-silabs) [reply src/app/icd/ICDManager.cpp]: Left the responsibility to the icdNotifier user to ensure that its calls are done from the chip task context or with the lock held

File: src/app/icd/ICDNotifier.h (hunk 20 above)
Comment (jmartinez-silabs) [reply src/app/icd/ICDNotifier.h]: opted for ICDSubscriber.

File: examples/platform/silabs/BaseApplication.cpp [hunk 24]
```diff
@@ -505,13 +506,12 @@ void BaseApplication::ButtonHandler(AppEvent * aEvent)
...
                 SILABS_LOG("Network is already provisioned, Ble advertissement not enabled");
-                DeviceLayer::ChipDeviceEvent event;
-                event.Type     = DeviceLayer::DeviceEventType::kAppWakeUpEvent;
-                CHIP_ERROR err = DeviceLayer::PlatformMgr().PostEvent(&event);
-                if (err != CHIP_NO_ERROR)
-                {
-                    ChipLogError(AppServer, "Failed to post App wake up Event event %" CHIP_ERROR_FORMAT, err.Format());
-                }
+#if CHIP_CONFIG_ENABLE_ICD_SERVER
+                // Temporarly used to cause a user trigger and ICD Active Mode Interval/Threshold
```
Comment (bzbarsky-apple) [inline examples/platform/silabs/BaseApplication.cpp:510]:
```suggestion
                // Temporarily claim network activity, until we implement a "user trigger" reason for ICD wakeups.
```

File: src/app/icd/ICDNotifier.h [hunk 25]
```diff
@@ -0,0 +1,97 @@
...
+ *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ *    See the License for the specific language governing permissions and
+ *    limitations under the License.
+ */
+#pragma once
+
+#include <app/AppConfig.h>
+#include <lib/core/CHIPError.h>
+
+class ICDSubscriber;
```
Comment (bzbarsky-apple) [inline src/app/icd/ICDNotifier.h:22]: I think the problem with "Subscriber" is that it's too easy to get confused with Matter subscriptions, esp because of how ICD-related those are.

If ICDListener is not ok, how about ICDActivityObserver?

**Review by bzbarsky-apple — APPROVED** [review]
