### PR TITLE
Use struct mallinfo when __GLIBC__ is defined

### LINKED ISSUE #9906: Linux build fails with musl libc because struct mallinfo is not available
Linux build fails with musl libc

At

https://github.com/project-chip/connectedhomeip/blob/bc4d7114c60d40d517bdd9da7d2f51c00e2a70ee/src/platform/Linux/PlatformManagerImpl.cpp#L154

with

```log
../../third_party/connectedhomeip/src/platform/Linux/PlatformManagerImpl.cpp:154:34: error: invalid use of incomplete type 'mallinfo'
    struct mallinfo mallocInfo = mallinfo();
                                 ^~~~~~~~~~
../../third_party/connectedhomeip/src/platform/Linux/PlatformManagerImpl.cpp:154:12: note: forward declaration of 'mallinfo'
    struct mallinfo mallocInfo = mallinfo();
           ^
```

Possible solution: Add build arg to bypass usage of mallinfo.

### PR DESCRIPTION
**Pull request by tewarid**
#### Problem
What is being fixed?  Examples:
* Fixes #9906 Linux build fails with musl libc because struct mallinfo is not available.

#### Change overview
Struct mallinfo is not available with musl libc. Work around the issue
by building source code that uses mallinfo only when __GLIBC__ is
defined.

#### Testing
Manual testing using yocto linux toolchain.

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

File: src/platform/Linux/DiagnosticDataProviderImpl.cpp [hunk 1]
```diff
@@ -218,28 +218,33 @@ DiagnosticDataProviderImpl & DiagnosticDataProviderImpl::GetDefaultInstance()
 
 CHIP_ERROR DiagnosticDataProviderImpl::GetCurrentHeapFree(uint64_t & currentHeapFree)
 {
+#ifdef __GLIBC__
     struct mallinfo mallocInfo = mallinfo();
 
     // Get the current amount of heap memory, in bytes, that are not being utilized
     // by the current running program.
     currentHeapFree = mallocInfo.fordblks;
```
Comment (andy31415) [inline src/platform/Linux/DiagnosticDataProviderImpl.cpp:226]: should there not be an else value that does something?

Like return CHIP_ERROR_NOT_IMPLEMENTED or at least setting the current free to some know value.

Comment (tewarid) [reply src/platform/Linux/DiagnosticDataProviderImpl.cpp:226]: sure - will change to something like...

```cpp
#ifndef __GLIBC__
    return CHIP_ERROR_NOT_IMPLEMENTED;
#else
...
#endif
```

**Review by andy31415 — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
