### PR TITLE
Fix PersistentStorageDelegate APIs to be consistent about error reporting

### LINKED ISSUE #15671: Unify error code for Persistent Storage Delegate
#### Problem
When a value is not found two possible error code can be returned depending on implementation type : 
`CHIP_ERROR_PERSISTED_STORAGE_VALUE_NOT_FOUND` and `CHIP_ERROR_KEY_NOT_FOUND`

 #### Proposed Solution
Unify the API so that the same error code is return regardless of implementation.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Fixes https://github.com/project-chip/connectedhomeip/issues/15671

#### Problem
Storage delegate has unclear API contract, implementation violate parts of it anyway.

#### Change overview
Define contract more clearly, fix violations.

#### Testing
Should not affect existing code.  Should allow new code being added to not have to check for multiple possible error returns for the same situation.

### CODE REVIEW

File: src/protocols/secure_channel/tests/TestCASESession.cpp [hunk 1]
```diff
@@ -316,7 +321,7 @@ class TestCASESessionPersistentStorageDelegate : public PersistentStorageDelegat
                 keysize[i] = static_cast<uint16_t>(strlen(key));
                 keysize[i]++;
                 keys[i] = reinterpret_cast<char *>(chip::Platform::MemoryAlloc(keysize[i]));
-                strcpy(keys[i], key);
+                memcpy(keys[i], key, keysize[i]);
```
Comment (jepenven-silabs) [inline src/protocols/secure_channel/tests/TestCASESession.cpp:324]: Keysize would be a character shorter in that case since strlen doesn't count the null character. I suggest keeping strcpy or increasing the keysize by 1 to keep a valid string.

Comment (jepenven-silabs) [reply src/protocols/secure_channel/tests/TestCASESession.cpp:324]: nevermind, didn't see the `keysize[i]++;`

**Review by jepenven-silabs — APPROVED** [review]

File: src/protocols/secure_channel/tests/TestCASESession.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/protocols/secure_channel/tests/TestCASESession.cpp:324]: > Keysize would be a character shorter in that case since strlen doesn't count the null character.

Yes, "keys[i]" does not include the null char.

>  I suggest keeping strcpy 

It's misleading, because it actually runs out of buffer and just does not put in the null... So the behavior with memcpy is the same, but clearer in terms of what's going on.

**Review by woody-apple — APPROVED** [review]
