### PR TITLE
Fix post-review comments on Q quality utils from #34266

### LINKED ISSUE #34334: Resolve post-review minor comments on Q quality building block (#34266)
@bzbarsky-apple raised some minor comments post-submit on https://github.com/project-chip/connectedhomeip/pull/34266#pullrequestreview-2173994817.

These should be resolved.

### PR DESCRIPTION
**Pull request by tcarmelveilleux**
- PR #34266 had post review comments See: https://github.com/project-chip/connectedhomeip/pull/34266#pullrequestreview-2173994817
- Fix 0->0 case
- Introduce `Timestamp` more places where it makes sense
- Simplify some code lines

Fixes #34334

Testing done:

- Added unit test for 0->0
- Tests still pass

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

File: src/app/cluster-building-blocks/QuieterReporting.h [hunk 1]
```diff
@@ -172,13 +172,13 @@ class QuieterReportingAttribute
...
      */
-    AttributeDirtyState SetValue(const chip::app::DataModel::Nullable<T> & newValue, Timestamp now,
-                                 SufficientChangePredicate changedPredicate)
+    AttributeDirtyState SetValue(const DataModel::Nullable<T> & newValue, Timestamp now, SufficientChangePredicate changedPredicate)
     {
-        bool isChangeOfNull       = newValue.IsNull() ^ mValue.IsNull();
-        bool areBothValuesNonNull = !newValue.IsNull() && !mValue.IsNull();
+        bool isChangeOfNull         = newValue.IsNull() != mValue.IsNull();
+        bool areBothValuesNonNull   = !newValue.IsNull() && !mValue.IsNull();
+        bool areBothValuesDifferent = areBothValuesNonNull && (newValue.Value() != mValue.Value());
```
Comment (bzbarsky-apple) [inline src/app/cluster-building-blocks/QuieterReporting.h:179]: Hmm.  I guess we don't want to just early-return if `newValue == mValue` because we want to always give `changedPredicate` a shot at marking dirty even if the value has not changed?

I think that's worth documenting here so that someone doesn't "optimize" away that capability.  We should also clearly document that change predicates need to be aware of the fact that they might be called even if the value is not actually changing.

That said, it seems odd to me to allow this.  Why would we ever want to mark things dirty if they are not actually changing?  It might help to include some of those use-cases as examples in the API documentation for change predicates or something....

Comment (tcarmelveilleux) [reply src/app/cluster-building-blocks/QuieterReporting.h:179]: It's basically not to lose parity with MatterReportingAttributeChangeCallback() having been called unconditionally.

Comment (tcarmelveilleux) [reply src/app/cluster-building-blocks/QuieterReporting.h:171]: Fixed

**Review by bzbarsky-apple — APPROVED** [review]
