### PR TITLE
Quick-fix running out of CASE sessions

### LINKED ISSUE #17698: Timeout error occured occasionally in the chip-tool in all apps
**Problem**
Timeout error occured occasionally during the executing of test cases on raspi and thread platform . 

**Apps used**- All Apps

**Commit ID** -077e44eadf46f349916b3f4f358da6126be2ed48

**platform:** - Raspi,Thread

**Branch** - Master branch

**Error:**

**DUT-** [1650885627.816408][11255:11255] CHIP:EM: OnMessageReceived failed, err = ../../third_party/connectedhomeip/src/transport/PairingSession.cpp:29: CHIP Error 0x0000000B: No memory

**CTRL-** [1650885657.611084][9442:9442] CHIP:DL: System Layer shutdown
[1650885657.611268][9442:9442] CHIP:TOO: Run command failure: ../../commands/common/CHIPCommand.cpp:392: CHIP Error 0x00000032: Timeout

**Actual logs :**

[new_log_dut.txt](https://github.com/project-chip/connectedhomeip/files/8556459/new_log_dut.txt)
[ctrl_log.txt](https://github.com/project-chip/connectedhomeip/files/8556462/ctrl_log.txt)

**Steps to reproduce:**
1. Pairing of DUT and controller
2. Executing test cases in controller

### PR DESCRIPTION
**Pull request by tcarmelveilleux**
#### Problem
- From #17422 onwards, "previous" CASE sessions were not expired
  in terms of the session cache if sessions were constantly
  re-established.
- A root cause solution will be to solve #17568, but in the meantime,
  cert testing started failing after N (where N is session manager
  pool size) runs.

Fixes #17698

#### Change overview
This PR cleans-up the previous sessions from same node (duplicate sessions
that should not happen). This is a bit unclean but will do to unblock
testing since it was good enough before, and the better method is not
yet implemented.

This PR also adds logging when this happens.

#### Testing

- Unit tests pass
- Cert tests pass
- Manual run of N > 16
  `for i in {1..18}; do ./out/debug/standalone/chip-tool basic read vendor-name 115566 0 ; done`
  does not fail as before.

### CODE REVIEW

File: src/transport/PairingSession.cpp [hunk 1]
```diff
@@ -34,16 +34,25 @@ CHIP_ERROR PairingSession::AllocateSecureSession(SessionManager & sessionManager
 
 CHIP_ERROR PairingSession::ActivateSecureSession(const Transport::PeerAddress & peerAddress)
 {
-    Transport::SecureSession * secureSession = mSecureSessionHolder->AsSecureSession();
+    // TODO(17568): Replace with proper expiry logic. This current method makes sure there
+    // are not multiple sessions established, until eventual exhaustion of the resources
+    // for CASE sessions. Current method is quick fix for #17698, cannot remain.
+    mSessionManager->ExpireAllPairingsForPeerExceptPending(GetPeer());
```
Comment (bzbarsky-apple) [inline src/transport/PairingSession.cpp:40]: This seems fine if it can't accidentally expire PASE sessions....

**Review by bzbarsky-apple — APPROVED** [review]

File: src/transport/PairingSession.cpp (hunk 1 above)
Comment (tcarmelveilleux) [reply src/transport/PairingSession.cpp:40]: It cannot, since it would only expire another PASE session "with the same peer"  that is still active. For PASE, I guess this enforces a single PASE session (which is already a constraint)

**Review by andy31415 — APPROVED** [review]

**Review by kghost — COMMENTED** [review]
There should a temporary solution before #17568 being fixed

**Review by kghost — APPROVED** [review]
This should be a temporary solution before #17568 being fixed

**Review by jmartinez-silabs — APPROVED** [review]
