### PR TITLE
Fix KeySetRemove to fail on key set index 0

### LINKED ISSUE #28518: [BUG] KeySetRemove Command returns SUCCESS status code when GroupKeySetID 0 is being removed
### Reproduction steps

**spec reference: 1**1.2.7.4. KeySetRemove Command
This command SHALL fail with an INVALID_COMMAND status code back to the initiator if the
GroupKeySetID being removed is 0, which is the Key Set associated with the Identity Protection Key
(IPK).

When key-set-remove command is issued with 0x0 ID we should expect INVALID_COMMAND as status code but we see SUCCESS as the status code
This issue was found during covering additional negative scenarios for TC-GRPKEY-2.2 

Reference log:
[GRPKEY2.2GroupKeySetID0Error.txt](https://github.com/project-chip/connectedhomeip/files/12258277/GRPKEY2.2GroupKeySetID0Error.txt)

### Bug prevalence

NA

### GitHub hash of the SDK that was being used

NA

### Platform

other

### Platform Version(s)

NA

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tcarmelveilleux**
Problem:

- Removing KeySet index 0 is not allowed by spec, but SDK allowed it.
- Fixes #28518

This PR:

- Adds the check and tests against removing fabric index zero
- Improves error reporting for several errors in the cluster

Testing:

- Added unit tests and integration tests for additions

### CODE REVIEW

File: src/app/CommandHandler.cpp [hunk 1]
```diff
@@ -470,8 +470,7 @@ CHIP_ERROR CommandHandler::AddStatus(const ConcreteCommandPath & aCommandPath, c
     return AddStatusInternal(aCommandPath, StatusIB(aStatus));
 }
 
-CHIP_ERROR CommandHandler::AddStatusAndLogIfFailure(const ConcreteCommandPath & aCommandPath, const Status aStatus,
-                                                    const char * aMessage)
+void CommandHandler::AddStatusAndLogIfFailure(const ConcreteCommandPath & aCommandPath, const Status aStatus, const char * aMessage)
```
Comment (andy31415) [inline src/app/CommandHandler.cpp:473]: if void, the "And log if failure" in the name seems not needed. We do not name all our functions that log something with "and log if failure".

Consider renaming to just AddStatus as I imagine void functions would log if things don't go their way.

Comment (tcarmelveilleux) [reply src/app/CommandHandler.cpp:473]: Yeah :(

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp [hunk 2]
```diff
@@ -405,6 +405,43 @@ constexpr uint16_t GroupKeyManagementAttributeAccess::kClusterRevision;
 
 GroupKeyManagementAttributeAccess gAttribute;
 
+bool ValidateAndGetProviderAndFabric(chip::app::CommandHandler * commandObj, const chip::app::ConcreteCommandPath & commandPath,
+                                     Credentials::GroupDataProvider ** outGroupDataProvider, const FabricInfo ** outFabricInfo)
+{
+    VerifyOrDie((outGroupDataProvider != nullptr) && (outFabricInfo != nullptr));
+
+    // Else if the command in the path is fabric-scoped and there is no accessing fabric,
+    // a CommandStatusIB SHALL be generated with the UNSUPPORTED_ACCESS Status Code.
```
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp]: Just was refactoring all the existing code, but I had forgotten about that pre-check path. Thanks for calling it out, I removed the duplication.

[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp]: Just was refactoring all the existing code, but I had forgotten about that pre-check path. Thanks for calling it out, I removed the duplication.

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp [hunk 3]
```diff
@@ -401,7 +401,32 @@ ValidateKeySetWriteArguments(const chip::app::Clusters::GroupKeyManagement::Comm
     return Status::Success;
 }
 
-constexpr uint16_t GroupKeyManagementAttributeAccess::kClusterRevision;
+bool ValidateAndGetProviderAndFabric(chip::app::CommandHandler * commandObj, const chip::app::ConcreteCommandPath & commandPath,
```
Comment (andy31415) [inline src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:404]: remove `validateand`. Maybe GetValidProviderAndFabric and even that seems a bit inconvenient because of the and.

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp [hunk 4]
```diff
@@ -401,7 +401,32 @@ ValidateKeySetWriteArguments(const chip::app::Clusters::GroupKeyManagement::Comm
...
+                                     Credentials::GroupDataProvider ** outGroupDataProvider, const FabricInfo ** outFabricInfo)
+{
+    VerifyOrDie((outGroupDataProvider != nullptr) && (outFabricInfo != nullptr));
```
Comment (andy31415) [inline src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:407]: should we validate commandObj as well since we are using it below? Or would we segfault anyway if null?

Comment (andy31415) [reply src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:407]: Maybe we should just return false on invalid arguments instead of die.

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp [hunk 5]
```diff
@@ -401,7 +401,32 @@ ValidateKeySetWriteArguments(const chip::app::Clusters::GroupKeyManagement::Comm
...
+
+    if (nullptr == provider)
+    {
+        commandObj->AddStatusAndLogIfFailure(commandPath, Status::Failure, "Internal consistency error on provider!");
+        return false;
+    }
+
+    if (nullptr == fabric)
+    {
+        commandObj->AddStatusAndLogIfFailure(commandPath, Status::Failure, "Internal consistency error on access fabric!");
```
Comment (andy31415) [inline src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:421]: Should the caller not set status (since it is the same every time) and this should just log? That way you do not need to pass in the path anymore, making the method smaller.

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp [hunk 6]
```diff
@@ -592,30 +616,41 @@ bool emberAfGroupKeyManagementClusterKeySetRemoveCallback(
...
     }
 
-    // Send response
-    CHIP_ERROR send_err = commandObj->AddStatus(commandPath, status);
-    if (CHIP_NO_ERROR != send_err)
+    if (commandData.groupKeySetID == GroupDataProvider::kIdentityProtectionKeySetId)
+    {
+        // SPEC: This command SHALL fail with an INVALID_COMMAND status code back to the initiator if the GroupKeySetID being
+        // removed is 0, which is the Key Set associated with the Identity Protection Key (IPK).
+        commandObj->AddStatusAndLogIfFailure(commandPath, Status::InvalidCommand,
```
Comment (andy31415) [inline src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:633]: Why are we using this method everywhere instead of having separate log and add status. We know this is a failure, so it seems less cognitive load to not read the "and" as "always happens" by splitting this into a lot and a AddStatus without a log.

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp [hunk 7]
```diff
@@ -592,30 +616,41 @@ bool emberAfGroupKeyManagementClusterKeySetRemoveCallback(
...
+
+    Status status = Status::Success;
+    if (CHIP_ERROR_KEY_NOT_FOUND == err)
+    {
+        status = Status::NotFound;
+    }
+    else if (CHIP_NO_ERROR != err)
     {
-        ChipLogDetail(Zcl, "GroupKeyManagementCluster: KeySetRemove failed: %" CHIP_ERROR_FORMAT, send_err.Format());
+        status = Status::Failure;
```
Comment (andy31415) [inline src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:649]: This logging of status here uses the CHIP_ERROR which is more detailed (in some platforms it even has the line/file where it happend). It seems better to have logs inside here rather than use the logiffailure

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp (hunk 3 above)
Comment (pidarped) [reply src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:404]: Yes. Too many Ands in the function name. I would suggest just GetProviderAndFabric(). Getting valid ones should be implied and checks done internally.

**Review by pidarped — APPROVED** [review]

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp (hunk 3 above)
Comment (andy31415) [reply src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp]: Updated the code.

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp (hunk 4 above)
Comment (andy31415) [reply src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:408]: Added VerifyOrDie for commandObj as well.

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp (hunk 7 above)
Comment (andy31415) [reply src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:660]: Updated logging to support a CHIP_ERROR as well to not lose a format.

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp [hunk 8]
```diff
@@ -443,8 +473,9 @@ bool emberAfGroupKeyManagementClusterKeySetWriteCallback(
         // supported by the server, because it is ... a new value unrecognized
         // by a legacy server, then the server SHALL generate a general
         // constraint error
-        commandObj->AddStatusAndLogIfFailure(commandPath, Status::ConstraintError,
+        chip::app::CommandHandler::LogStatus(commandPath, Status::ConstraintError,
```
Comment (bzbarsky-apple) [inline src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:476]: The whole point of AddStatusAndLogIfFailure, as far as I can tell, was to make it really easy for people to log the thing they are responding with.  The new setup requires repeating the same status twice, can lead to them diverging, etc.  Please leave AddStatusAndLogIfFailure bits as they were.

**Review by bzbarsky-apple — DISMISSED** [review]

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp (hunk 8 above)
Comment (andy31415) [reply src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:476]: I made the change intentional: a method with `And` in the name is a code smell and it should not have existed in the first place. This method encouraged awkward code:
  - calling this method with a failing status just for the log sideffect, when there is little benefit over clear addstatus and logging
  - logging with Status code using this method instead of the underlying CHIP_ERROR (and thus losing the extra info that is contained in CHIP_ERROR).
  
  I added an equivalent `Log` to be explicit and do one thing only.

Comment (bzbarsky-apple) [reply src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:476]: I know what you did but given that you are taking @tcarmelveilleux's PR and explicitly removing a thing he added in a previous PR, the whole thing is very odd.

What I would suggest is that we fix the actual bug in this PR, and move any refactoring of the AddStatus bits to separate PRs that can be reviewed separately (and can wait for @tcarmelveilleux to get back from vacation, whereas this one we need to fix so we stop failing tests).

Comment (andy31415) [reply src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:476]: Ok, reverted that change, will do any updates in a separate PR.

File: src/app/CommandHandler.cpp [hunk 9]
```diff
@@ -482,7 +484,7 @@ CHIP_ERROR CommandHandler::AddStatusAndLogIfFailure(const ConcreteCommandPath &
                      ChipLogValueIMStatus(aStatus), aMessage);
     }
 
-    return AddStatus(aCommandPath, aStatus);
+    LogErrorOnFailure(AddStatus(aCommandPath, aStatus));
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.cpp:487]: I expect this is why you are getting noticeable flash increases on all platforms.  I would strongly suggest leaving this LogErrorOnFailure (which has the issues described in https://github.com/project-chip/connectedhomeip/issues/28532) to a separate PR.

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp [hunk 10]
```diff
@@ -420,12 +447,13 @@ bool emberAfGroupKeyManagementClusterKeySetWriteCallback(
     chip::app::CommandHandler * commandObj, const chip::app::ConcreteCommandPath & commandPath,
     const chip::app::Clusters::GroupKeyManagement::Commands::KeySetWrite::DecodableType & commandData)
 {
-    auto provider = GetGroupDataProvider();
-    auto fabric   = Server::GetInstance().GetFabricTable().FindFabricWithIndex(commandObj->GetAccessingFabricIndex());
+    Credentials::GroupDataProvider * provider = nullptr;
+    const FabricInfo * fabric                 = nullptr;
 
-    if (nullptr == provider || nullptr == fabric)
+    // Flight-check fabric scoping.
```
Comment (bzbarsky-apple) [inline src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:453]:
```suggestion
```
This is not checking fabric scoping...

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp [hunk 11]
```diff
@@ -516,32 +544,30 @@ bool emberAfGroupKeyManagementClusterKeySetWriteCallback(
...
     chip::app::CommandHandler * commandObj, const chip::app::ConcreteCommandPath & commandPath,
     const chip::app::Clusters::GroupKeyManagement::Commands::KeySetRead::DecodableType & commandData)
 {
-    auto fabric     = commandObj->GetAccessingFabricIndex();
-    auto * provider = GetGroupDataProvider();
+    Credentials::GroupDataProvider * provider = nullptr;
+    const FabricInfo * fabric                 = nullptr;
 
-    if (nullptr == provider)
+    // Flight-check fabric scoping.
```
Comment (bzbarsky-apple) [inline src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:558]:
```suggestion
```

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp [hunk 12]
```diff
@@ -592,30 +618,41 @@ bool emberAfGroupKeyManagementClusterKeySetRemoveCallback(
...
 
 {
-    auto fabric     = commandObj->GetAccessingFabricIndex();
-    auto * provider = GetGroupDataProvider();
-    Status status   = Status::Failure;
+    Credentials::GroupDataProvider * provider = nullptr;
+    const FabricInfo * fabric                 = nullptr;
 
-    if (nullptr != provider)
+    // Flight-check fabric scoping.
```
Comment (bzbarsky-apple) [inline src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:624]:
```suggestion
```

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp [hunk 13]
```diff
@@ -654,19 +691,21 @@ bool emberAfGroupKeyManagementClusterKeySetReadAllIndicesCallback(
     chip::app::CommandHandler * commandObj, const chip::app::ConcreteCommandPath & commandPath,
     const chip::app::Clusters::GroupKeyManagement::Commands::KeySetReadAllIndices::DecodableType & commandData)
 {
-    auto fabric     = commandObj->GetAccessingFabricIndex();
-    auto * provider = GetGroupDataProvider();
+    Credentials::GroupDataProvider * provider = nullptr;
+    const FabricInfo * fabric                 = nullptr;
 
-    if (nullptr == provider)
+    // Flight-check fabric scoping.
```
Comment (bzbarsky-apple) [inline src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:697]:
```suggestion
```

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/CommandHandler.cpp (hunk 9 above)
Comment (andy31415) [reply src/app/CommandHandler.cpp:487]: I added separate logging as it seems that this method is actually indended to not lose error statuses since it returns void.

Made a custom text to actually have full data, even though this will probably still have some slight size increase (I assume not too bad as this method is not inlined).

Comment (bzbarsky-apple) [reply src/app/CommandHandler.cpp:487]: > I added separate logging as it seems that this method is actually indended to not lose error statuses

This method is based on the reality that AddStatus in fact never fails....
