### PR TITLE
Issue #40008: deconstrain RVC example's `GoHome` handler to fix TC-RVCOPSTATE-2.5

### LINKED ISSUE #40008: [BUG] RVC Example App requires idling before `GoHome` command
### Reproduction steps

I don't think this idling is required by the specification - other changes, like changing cleaning modes, must happen from an Idle state, but `GoHome` is on OperationalState and should be possible to command from the cleaning state as done in `TC-RVCOPSTATE-2.5`.  I don't see anything in the [GoHome Command spec](https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/OperationalState_RVC.adoc#51-gohome-command) that should constrain seeking the charger when cleaning.

### Bug prevalence

every time

### GitHub hash of the SDK that was being used

784e0e3f6182b2db7b0852eaddc30959e3e60b0d

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

see #40002 where an additional "change mode" command is performed prior to issuing `GoHome` to work around this issue to pass CI with the example app.  That command wasn't necessary on the retail RVCs I tested.

### PR DESCRIPTION
**Pull request by kiel-apple**
TODO
- [x] update state diagram to reflect that Paused and Running can also `GoHome`
- [x] ensure no regressions in other RVC test cases (CI)

#### Summary

- `GoHome` was rejecting non-Stopped opstate requests to GoHome.  I don't see any [spec text](https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/OperationalState_RVC.adoc#51-gohome-command) supporting that constraint.
- Update GoHome handler to also update RVC Run Mode to Idle.  It doesn't have to be set to Idle immediately to meet [spec](https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/OperationalState_RVC.adoc#51-gohome-command), but doing so immediately avoids the need to maintain more global state.

#### Related issues

Fixes #40008

#### Testing

Manual testing: 

1. `scripts/examples/gn_build_example.sh examples/rvc-app/linux examples/rvc-app/linux/out/rvc-app`
1. `rm /tmp/chip*; ./examples/rvc-app/linux/out/rvc-app/chip-rvc-app --app-pipe /tmp/rvc_fifo`
1. in parallel, `python3 src/python_testing/TC_RVCOPSTATE_2_5.py --commissioning-method on-network --passcode 20202021 --discriminator 3840 --storage-path ~/.chip_admin_storage.json --bypass-attestation-verifier --endpoint 1 --PICS examples/rvc-app/rvc-common/pics/rvc-app-pics-values --int-arg runmode_cleanmode:1 --app-pipe /tmp/rvc_fifo`

Also pending CI run of all RVC tests.

#### Readability checklist

The checklist below will help the reviewer finish PR review in time and keep the
code readable:

-   [x] PR title is
        [descriptive](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html#title-formatting)
-   [x] Apply the
        [_“When in Rome…”_](https://project-chip.github.io/connectedhomeip-doc/style/CODING_STYLE_GUIDE.html)
        rule (coding style)
-   [x] PR size is short
-   [x] Try to avoid "squashing" and "force-update" in commit history
-   [ ] CI time didn't increase

### CODE REVIEW

File: examples/rvc-app/rvc-common/src/rvc-device.cpp [hunk 1]
```diff
@@ -142,13 +142,21 @@ void RvcDevice::HandleOpStateGoHomeCallback(Clusters::OperationalState::GenericO
 {
     switch (mOperationalStateInstance.GetCurrentOperationalState())
     {
-    case to_underlying(OperationalState::OperationalStateEnum::kStopped): {
-        if (mRunModeInstance.GetCurrentMode() != RvcRunMode::ModeIdle)
+    case to_underlying(OperationalState::OperationalStateEnum::kStopped):
+    case to_underlying(OperationalState::OperationalStateEnum::kPaused):
+    case to_underlying(OperationalState::OperationalStateEnum::kRunning): {
```
[the remark this answers is not in the document]
Comment (kiel-apple) [reply examples/rvc-app/rvc-common/src/rvc-device.cpp:147]: I also like that, but apparently Restyled doesn't.

File: src/python_testing/TC_RVCOPSTATE_2_5.py [hunk 2]
```diff
@@ -235,9 +235,6 @@ async def test_TC_RVCOPSTATE_2_5(self):
             # TH sends GoHome command to the DUT
             self.step("8")
 
-            # TODO:  add this idle mode set to test plan, as RVC must be idle for GoHome to be performed successfully
-            await self.send_change_to_mode_with_check(idle_mode, RvcStatusEnum.Success)
-
             await self.send_go_home_cmd_with_check(Clusters.OperationalState.Enums.ErrorStateEnum.kNoError)
             await self.read_operational_state_with_check(Clusters.RvcOperationalState.Enums.OperationalStateEnum.kSeekingCharger)
```
[the remark this answers is not in the document]
Comment (kiel-apple) [reply src/python_testing/TC_RVCOPSTATE_2_5.py:239]: ... thanks.

File: examples/rvc-app/RVC_app_state_diagram.png
Comment (andy31415) [inline examples/rvc-app/RVC_app_state_diagram.png:1]: The diagram resolution changed and text seems smaller now. COuld we re-generate at the previous resolution?

Comment (andy31415) [reply examples/rvc-app/RVC_app_state_diagram.png:1]: Maybe mis-read ... if the newer one is the bigger one, I like that better.

Comment (andy31415) [reply examples/rvc-app/RVC_app_state_diagram.png:1]: It does make it very hard to compare...

Comment (kiel-apple) [reply examples/rvc-app/RVC_app_state_diagram.png:1]: yep, made the diagram 200% since it was a bit blurry at the original resolution.  it does indeed make it tough to compare :(

**Review by plauric — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
