### PR TITLE
Fix ResolverProxy use-after-free in HandleNodeBrowse

### LINKED ISSUE #13289: HandleNodeBrowse ResolverDelegateProxy use-after-free
#### Problem

Observed when debugging #13227:

```
static void HandleNodeBrowse(void * context, DnssdService * services, size_t servicesSize, CHIP_ERROR error)
{
    ResolverDelegateProxy * proxy = static_cast<ResolverDelegateProxy *>(context);
    proxy->Release();

    for (size_t i = 0; i < servicesSize; ++i)
    {
        proxy->Retain();
        // For some platforms browsed services are already resolved, so verify if resolve is really needed or call resolve callback
        if (!services[i].mAddress.HasValue())
        {
            ChipDnssdResolve(&services[i], services[i].mInterface, HandleNodeResolve, context);
        }
        else
        {
            HandleNodeResolve(context, &services[i], error);
        }
    }
}
```

If coming into this method, reference count is 1, this immediately decrements to 0. Then we increment back to 1, which is use-after-free.

 #### Proposed Solution

Move Release call to the end of the method, after potential object use and Retain calls.

### PR DESCRIPTION
**Pull request by msandstedt**
#### Problem

HandleNodeBrowse decrements the ResolverProxy reference count, which will cause the object to be destructed if the counter reaches 0.  But then it increments the counter and accesses the object, which can be a use-after-free.

Fixes #13289

#### Change overview

This fixes the problem by ordering Release to occur after Retain. This also adds an abort to ReferenceCounted::Retain to check for cases like this when kInitRefCount is non-zero.  For objects that are initialized with a non-zero reference count, we don't ever expect to call Retain when the count has already decremented to 0 because this indicates the object has been deleted.

#### Testing

Tested locally with a modified chip-tool that dynamically creates and initializes ResolverProxy objects for resolve calls, and calls their Shutdown method from within the OnNodeDiscoveryComplete callback.  This reliably caused segfault without the fix and did not after.  Additional instrumentation was added to log reference counts during testing and it was verified that these were now as expected.

The abort that has been added for ReferenceCounted::Retain should also provide significant coverage.

### CODE REVIEW

File: src/lib/dnssd/Discovery_ImplPlatform.cpp [hunk 1]
```diff
@@ -129,7 +129,6 @@ static void HandleNodeIdResolve(void * context, DnssdService * result, CHIP_ERRO
 static void HandleNodeBrowse(void * context, DnssdService * services, size_t servicesSize, CHIP_ERROR error)
 {
     ResolverDelegateProxy * proxy = static_cast<ResolverDelegateProxy *>(context);
-    proxy->Release();
 
     for (size_t i = 0; i < servicesSize; ++i)
     {
```
Comment (mdamle) [inline src/lib/dnssd/Discovery_ImplPlatform.cpp:134]: Retain() can be called servicesSize number of times on the proxy object. Do we need to call Release() same number of times as well?

Comment (msandstedt) [reply src/lib/dnssd/Discovery_ImplPlatform.cpp:134]: This Release is not paired with those Retains.  We can and will enter this scope with a reference count of 1.  So for each of the Retains in the loop, there must be an additional Release in the call chain from within the loop.  The release happens in [HandleNodeResolve](https://github.com/project-chip/connectedhomeip/blob/c50811c1d355261664150550310a2596c970117b/src/lib/dnssd/Discovery_ImplPlatform.cpp#L45).

CC @vivien-apple

**Review by andy31415 — APPROVED** [review]

File: src/lib/core/ReferenceCounted.h [hunk 2]
```diff
@@ -51,6 +51,10 @@ class ReferenceCounted
     /** Adds one to the usage count of this class */
     Subclass * Retain()
     {
+        if (kInitRefCount && mRefCount == 0)
```
Comment (wbschiller) [inline src/lib/core/ReferenceCounted.h:54]: Consider using a compile time static_assert to check that `kInitRefCount` is not 0, if that is appropriate for this template.

**Review by wbschiller — APPROVED** [review]
Looks correct to me.

File: src/lib/core/ReferenceCounted.h (hunk 2 above)
Comment (msandstedt) [reply src/lib/core/ReferenceCounted.h:54]: Unfortunately, this code purposefully instantiates the template with  kInitRefCount=0: https://github.com/project-chip/connectedhomeip/blob/4b9ead687c2b3eed1e430c1314b3a16bde211fc8/src/transport/UnauthenticatedSessionTable.h#L48

This new check has to ignore usages where that's the case.

**Review by saurabhst — APPROVED** [review]
