### PR TITLE
[IM] Record LastReportTick and DirtyTick in ReadHandler

### LINKED ISSUE #15975: Wildcard Reporting with iOS chiptool fails -M5 temp updates do not reflect in chiptool
#### Problem
Since switching to wildcard reporting for Chiptool, changing temp values on M5 board do not reflect in iOS chiptool

SHA: 2822511e632bd2ae8a2e5a853a114a9bac1cebe5

1. Pair M5 board using iOS chiptool2. 
2. Verify able to toggle light
3. Go to Temp sensor option, enable reporting Min: 1s, Max: 2s, Delta: 1C
4. Change temp on M5 board -> verify iOS chiptool updates

In step 4, Temp values do not update. See a bunch of errors reading values on M5 log

I (150619) all-clusters-app: Display awake but will switch off automatically in 30 seconds
I (150619) DeviceWithDisplay: editing attribute as integer: 34 (+)
E (150629) chip[DMG]: Endpoint 1, Cluster 0x0000_0402 update version to 771a7db8
I (150629) app-devicecallbacks: PostAttributeChangeCallback - Cluster ID: '0x0402', EndPoint ID: '0x01', Attribute ID: '0x0000'
I (150649) app-devicecallbacks: Unhandled cluster ID: 1026
I (150659) app-devicecallbacks: Current free heap: 62824

E (150839) chip[IN]: Received a duplicate message with MessageCounter:16124935 on exchange 50158r
E (150839) chip[EM]: Received message of type 0x1 with protocolId (0, 1) and MessageCounter:16124935 on exchange 50158r
E (150859) chip[EM]: Found matching exchange: 50158r, Delegate: 0x3ffce1d8
E (150869) chip[EM]: Forcing tx of solitary ack for duplicate MessageCounter:16124935 on exchange 50158r
E (150869) chip[EM]: Sending Standalone Ack for MessageCounter:16124935 on exchange 50158r
E (150879) chip[IN]: Prepared secure message 0x3ffe7764 to 0xB2E6D3E8F9A5EAEC (1)  of type 0x10 and protocolId (0, 0) on exchange 50158r with MessageCounter:3760406.
E (150899) chip[IN]: Sending encryp
[reporting-fails-chiptool-logs.txt](https://github.com/project-chip/connectedhomeip/files/8208989/reporting-fails-chiptool-logs.txt)
[reporting-fails-M5logs.txt](https://github.com/project-chip/connectedhomeip/files/8208991/reporting-fails-M5logs.txt)
M5 ted msg 0x3ffe7764 with MessageCounter:3760406 to 0xB2E6D3E8F9A5EAEC (1) at monotonic time: 150059 msec
I (150949) all-clusters-app: Display awake but will switch off automatically in 30 seconds
I (150949) DeviceWithDisplay: editing attribute as integer: 35 (+)
E (150959) chip[DMG]: Endpoint 1, Cluster 0x0000_0402 update version to 771a7db9
I (150959) app-devicecallbacks: PostAttributeChangeCallback - Cluster ID: '0x0402', EndPoint ID: '0x01', Attribute ID: '0x0000'
I (150979) app-devicecallbacks: Unhandled cluster ID: 1026
I (150989) app-devicecallbacks: Current free heap: 62812

E (150989) chip[EM]: Retransmitting MessageCounter:3760404 on exchange 50158r Send Cnt 0
E (150999) chip[IN]: Sending encrypted msg 0x3ffca04c with MessageCounter:3760404 to 0xB2E6D3E8F9A5EAEC (1) at monotonic time: 150163 msec
E (151139) chip[IN]: Received a duplicate message with MessageCounter:16124935 on exchange 50158r
E (151149) chip[EM]: Received message of type 0x1 with protocolId (0, 1) and MessageCounter:16124935 on exchange 50158r
E (151159) chip[EM]: Found matching exchange: 50158r, Delegate: 0x3ffce1d8
E (151169) chip[EM]: Forcing tx of solitary ack for duplicate MessageCounter:16124935 on exchange 50158r
E (151169) chip[EM]: Sending Standalone Ack for MessageCounter:16124935 on exchange 50158r
E (151179) chip[IN]: Prepared secure message 0x3ffe7764 to 0xB2E6D3E8F9A5EAEC (1)  of type 0x10 and protocolId (0, 0) on exchange 50158r with MessageCounter:3760407.
E (151199) chip[IN]: Sending encrypted msg 0x3ffe7764 with MessageCounter:3760407 to 0xB2E6D3E8F9A5EAEC (1) at monotonic time: 150359 msec
E (152999) chip[EM]: Retransmitting MessageCounter:3760404 on exchange 50158r Send Cnt 1
E (152999) chip[IN]: Sending encrypted msg 0x3ffca04c with MessageCounter:3760404 to 0xB2E6D3E8F9A5EAEC (1) at monotonic time: 152164 msec
I (153089) ROUTE_HOOK: Received RIO
I (153089) ROUTE_HOOK: prefix FDB7:92FF:3249:: lifetime 1800

E (153189) chip[EM]: Received message of type 0x1 with protocolId (0, 1) and MessageCounter:16124936 on exchange 50158r
E (153189) chip[EM]: Found matching exchange: 50158r, Delegate: 0x3ffce1d8
E (153209) chip[EM]: Rxd Ack; Removing MessageCounter:3760404 from Retrans Table on exchange 50158r
E (153219) chip[EM]: Removed CHIP MessageCounter:3760404 from RetransTable on exchange 50158r
E (153219) chip[DMG]: StatusResponseMessage =
E (153229) chip[DMG]: {
E (153229) chip[DMG]: 	Status = 0x0,
E (153229) chip[DMG]: 	InteractionModelRevision = 1
E (153239) chip[DMG]: }
E (153239) chip[IM]: Received status response, status is 0
E (153249) chip[DMG]: <RE> OnReportConfirm: NumReports = 0
E (153259) chip[DMG]: IM RH moving to [GeneratingReports]
E (153259) chip[DMG]: <RE:Run> Cluster 3, Attribute 0 is dirty
E (153269) chip[DMG]: Reading attribute: Cluster=0x0000_0003 Endpoint=0 AttributeId=0x0000_0000 (expanded=1)
E (153279) chip[DMG]: AccessControl: checking f=1 a=c s=0xB2E6D3E8F9A5EAEC t= c=0x0000_0003 e=0 p=v
E (153289) chip[DMG]: <RE:Run> Cluster 3, Attribute 1 is dirty
E (153299) chip[DMG]: Reading attribute: Cluster=0x0000_0003 Endpoint=0 AttributeId=0x0000_0001 (expanded=1)
E (153309) chip[DMG]: AccessControl: checking f=1 a=c s=0xB2E6D3E8F9A5EAEC t= c=0x0000_0003 e=0 p=v
E (153309) chip[DMG]: <RE:Run> Cluster 3, Attribute fffd is dirty
E (153319) chip[DMG]: Reading attribute: Cluster=0x0000_0003 Endpoint=0 AttributeId=0x0000_FFFD (expanded=1)
E (153339) chip[DMG]: AccessControl: checking f=1 a=c s=0xB2E6D3E8F9A5EAEC t= c=0x0000_0003 e=0 p=v
E (153349) chip[DMG]: <RE:Run> Cluster 3, Attribute fff8 is dirty
E (153349) chip[DMG]: Reading attribute: Cluster=0x0000_0003 Endpoint=0 AttributeId=0x0000_FFF8 (expanded=1)
E (153359) chip[DMG]: AccessControl: checking f=1 a=c s=0xB2E6D3E8F9A5EAEC t= c=0x0000_0003 e=0 p=v
E (153369) chip[DMG]: <RE:Run> Cluster 3, Attribute fff9 is dirty
E (153379) chip[DMG]: Reading attribute: Cluster=0x0000_0003 Endpoint=0 AttributeId=0x0000_FFF9 (expanded=1)
E (153389) chip[DMG]: AccessControl: checking f=1 a=c s=0xB2E6D3E8F9A5EAEC t= c=0x0000_0003 e=0 p=v
E (153399) chip[DMG]: <RE:Run> Cluster 3, Attribute fffb is dirty

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem

Fixes #15975

During priming report, the report might be large, and if there are any attributes changed during the report, we will do a full regeneration, makes the report unable to finish.

#### Change overview
- Only regenerate the attributes under the current generating cluster (and only when needed)
- For any other attribute change, we record a timestamp, and report it the next time we are generating the reports.

#### Testing
- Updates existing tests for SetDirty and Regeneration

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@erjiaqing Can you please explain:

1) What the timer bits are doing and why they are needed?
2) Why do we need to reset back to the beginning of the cluster and not just to the beginning of the attribute we are actually chunking?
3) Why do we not need to do anything for non-wildcard reads?  Those can be in the middle of a chunk as well when a write happens.

File: src/app/ReadHandler.h [hunk 1]
```diff
@@ -267,8 +265,10 @@ class ReadHandler : public Messaging::ExchangeDelegate
     // waiting for the min reporting interval to elapse.  If we have to send a
     // report immediately due to an urgent event being queued,
     // UnblockUrgentEventDelivery can be used to force mHoldReport to false.
-    bool mHoldReport         = false;
-    bool mDirty              = false;
+    bool mHoldReport = false;
+    // The timestamp when this read handler was marked as a dirty read handler.
+    uint64_t mDirtyTick      = 0;
+    bool mOverrideDirty      = false;
```
Comment (bzbarsky-apple) [inline src/app/ReadHandler.h:271]: The interactions between these various members need to be documented.

File: src/app/ReadHandler.h [hunk 2]
```diff
@@ -280,7 +280,13 @@ class ReadHandler : public Messaging::ExchangeDelegate
     // are waiting for the max reporting interval to elaps.  When mHoldSync
     // becomes false, we are allowed to send an empty report to keep the
     // subscription alive on the client.
-    bool mHoldSync                   = false;
+    bool mHoldSync = false;
+    // For subscriptions, we record the timestamp when we started to generate the last report.
+    // The mCurrentReportTick records the timestamp for the current report, which won;t be used for checking if this
+    // ReadHandler is dirty.
+    // mLastReportTick will be set to mCurrentReportTick after we sent the last chunk of the current report.
+    uint64_t mLastReportTick         = 0;
```
Comment (bzbarsky-apple) [inline src/app/ReadHandler.h:288]: Is there a clear description somewhere in one spot of the intended logic of the dirty-marking and how it's expected to work?  I would really like to make sure (1) the behavior being aimed for makes sense and (2) the code actually impements that behavior.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

**Comment by mrjerryjohns** [comment]
On the whole, having a difficult time figuring out all the logic bits fit together. Please write up how all the bits for dirty handling work together with Report generation.

**Comment by mrjerryjohns** [comment]
So on the whole, the changes here are quite complicated with respect to dirty computation and report generation, especially since they have complex inter-twined side-effects both in time (due to the use of timestamps) and in space (in terms of where the iterator is relative to the beginning/end of the chunked report train).

Here's my understanding of it - @erjiaqing please check if this aligns with your thinking and if so, please put this somewhere in the code:

At a high level, there are two key concepts in play for report generation - request path expansion (i.e expansion of the requested paths in the read/subscribe), and the use of dirtiness to act as a masked modifier over the set of request expanded paths to create the modified path set.

During priming, only the former is in play. The changes in this PR make it such that instead of coarsely resetting the iterator back to the beginning of that request expanded path set, it just resets it back to the 'beginning' of the cluster IF we happen to modify an attribute that lies within that cluster instance. This is markedly better than just blindly resetting back to the beginning of the request expanded set. It's **not** better than a more aggressive version that only resets it back to the beginning of the attribute IF we happened to have been modifying that attribute. However, this aggressive version would have meant that a receiver CAN get a view of the data of the cluster that isn't actually 'legal' (i.e a snapshot that is one of any number of snapshots of that cluster now, or in the past). This can happen if the attribute that got marked dirty was already processed earlier, but now, the receiver doesn't get sent that attribute and sees a slightly different view of that cluster.

So this is great. But what happens if we modified an attribute in a different cluster that we had already generated reports for already during priming?

That's where the second phase kicks in - during priming, we don't check the dirty set at all. However, once priming is done, the dirty set is processed. And at that time, we'll process the set of dirty items in the global dirty set (for items that were marked dirty after we had already iterated over them during priming) and generate reports for those.

The timestamp fixes actually aren't necessary to address the problems in the original issue - we could have just put in the less aggressive iterator reset to the head of the cluster.

The timestamp fixes just make it such that we don't over eagerly bundle in dirty items in steady state reporting by resetting the iterator back to the beginning and generating a whole new train of reports again anytime something becomes dirty.

I'll note however that there is a bug in the code (see the PR for more details).

File: src/app/ReadHandler.cpp [hunk 3]
```diff
@@ -226,6 +225,12 @@ CHIP_ERROR ReadHandler::SendReportData(System::PacketBufferHandle && aPayload, b
     }
 
     VerifyOrReturnLogError(mpExchangeCtx != nullptr, CHIP_ERROR_INCORRECT_STATE);
+    // If mIsChunkedReport is not set, then we are generating our first report chunk, record the current tick for checking dirty
+    // read handlers.
+    if (!mIsChunkedReport)
```
Comment (mrjerryjohns) [inline src/app/ReadHandler.cpp:230]: See my comment later on about how this isn't a very easy to understand way of formulating "is this the first report in a chunked series?".

File: src/app/ReadHandler.h (hunk 2 above)
Comment (mrjerryjohns) [inline src/app/ReadHandler.h:288]: The description isn't quite accurate - this tracks the timestamp of the first report in a train of reports that had last been sent to the client. This is updated at the end of a given report train.

As such, it should not be called `mLastReportTick` but rather, `mPreviousReportsBeginTime`.

File: src/app/ReadHandler.h [hunk 4]
```diff
@@ -280,7 +280,13 @@ class ReadHandler : public Messaging::ExchangeDelegate
...
+    uint64_t mCurrentReportTick      = 0;
```
Comment (mrjerryjohns) [inline src/app/ReadHandler.h:289]: This is more aptly the beginning time of the current series of reports, i.e `mCurrentReportsBeginTime`.

File: src/app/ReadHandler.cpp [hunk 5]
```diff
@@ -742,5 +748,34 @@ CHIP_ERROR ReadHandler::RefreshSubscribeSyncTimer()
...
+{
+    ConcreteAttributePath path;
+    mDirtyTick     = InteractionModelEngine::GetInstance()->GetReportingEngine().GetDirtyTick();
+    mOverrideDirty = true;
+
+    // We won't reset the path iterator for every SetDirty call to reduce the number of full report data.
+    // The iterator will be reset after finished each report session.
+    if (apAttributeChanged == nullptr ||
+        (mAttributePathExpandIterator.Get(path) && path.mEndpointId == apAttributeChanged->mEndpointId &&
+         path.mClusterId == apAttributeChanged->mClusterId) ||
```
Comment (mrjerryjohns) [inline src/app/ReadHandler.cpp:768]: There is a bug here - while this logic works great for Reads, in the case of steady-state report generation that utilizes the global dirty set to further mask the request expanded path set, you need to actually reset the iterator all the way back to the beginning. Without that, you'll actually miss gather attributes who are considered newer than the last report time of the read handler, but we'll never actually iterate over them since our iterator has already gone past those.

**Review by mrjerryjohns — CHANGES_REQUESTED** [review]
Need some key fixes.

File: src/app/ReadHandler.cpp [hunk 6]
```diff
@@ -252,6 +257,7 @@ CHIP_ERROR ReadHandler::SendReportData(System::PacketBufferHandle && aPayload, b
     }
     if (!aMoreChunks)
     {
+        mLastReportTick = mCurrentReportTick;
```
Comment (mrjerryjohns) [inline src/app/ReadHandler.cpp:260]: This should actually be snapping to the timestamp of the CURRENT report, not the first report in the CURRENT reporting series/train.

**Comment by erjiaqing** [comment]
> @erjiaqing Can you please explain:
> 
> 1. What the timer bits are doing and why they are needed?

The PR actually contains two parts, one is to adapt a less aggressive resetting strategy, however, we need to find another way to indicate whether the read handler is dirty, since the attribute changed might be happening after it is reported but before the end of chunking data. Then a single "mDirty" is not enough, we need to have a more precise timestamp to indicate if it is really reported.

> 2. Why do we need to reset back to the beginning of the cluster and not just to the beginning of the attribute we are actually chunking?

Resetting the encoder state is OK for me, with the possibility of a invalid cluster data (the users may see the , I'm not sure if this is acceptable.

> 3. Why do we not need to do anything for non-wildcard reads?  Those can be in the middle of a chunk as well when a write happens.

We have two state regarding the reporting process, the encoder state and the iterator state, since the iterator don't know the actual type of the attribute.
The encoder state is reset in ReadHandler::SetDirty()

Jerry's understanding matches my idea.

> The timestamp fixes actually aren't necessary to address the problems in the original issue - we could have just put in the less aggressive iterator reset to the head of the cluster.

No, it won't, if we adapt a less aggressive approach, the attribute change would be ignored since we will clear the dirty flag after sending the last chunk, then the global dirty set will be cleared since all ReadHandlers are clean. So we must have something else to indicate whether we have reported all we want.

File: src/app/ReadHandler.cpp (hunk 5 above)
Comment (erjiaqing) [reply src/app/ReadHandler.cpp:768]: With the help of the timestamp, I think they should be included in the next report message, that why ReadHandler.cpp:260 should be the timestamp of the start of the report series.

In this case, any attribute change after the start of the current report will be included in the next report.

Consider this case: we have finished the priming report, then we added a new endpoint -- this will result in a large number of chunks, and another attribute keeps changing, then we should not use a aggressive reset strategy here too.

File: src/app/ReadHandler.cpp [hunk 7]
```diff
@@ -742,5 +748,34 @@ CHIP_ERROR ReadHandler::RefreshSubscribeSyncTimer()
...
+
+void ReadHandler::SetDirty(const ClusterInfo * apAttributeChanged)
+{
+    ConcreteAttributePath path;
+    mDirtyTick     = InteractionModelEngine::GetInstance()->GetReportingEngine().GetDirtyTick();
+    mOverrideDirty = true;
+
+    // We won't reset the path iterator for every SetDirty call to reduce the number of full report data.
+    // The iterator will be reset after finished each report session.
+    if (apAttributeChanged == nullptr ||
```
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/app/ReadHandler.cpp]: No, since the ony user of the ReadHandler::SetDirty is ReportingEnging, changed the signature to `const ClusterInfo &` istead.

File: src/app/ReadHandler.cpp (hunk 5 above)
Comment (mrjerryjohns) [reply src/app/ReadHandler.cpp]: > In this case, any attribute change after the start of the current report will be included in the next report.

I don't think this is optimal. Those attributes **have** to be bundled into some report, so it's better to do that in the current report if one is already in flight. Otherwise, you may have to either wait for minimum reporting interval to generate that report, as well as potentially making that report in-efficient (you may have had space in the current reporting series to stuff that in).

File: src/app/tests/TestReadInteraction.cpp [hunk 8]
```diff
@@ -1319,10 +1319,11 @@ void TestReadInteraction::TestSetDirtyBetweenChunks(nlTestSuite * apSuite, void
 
         ctx.DrainAndServiceIO();
 
-        // We should receive another 2 * (6 + 1) = 14 attribute reports since the underlying path iterator should be reset.
+        // We should receive another (6 + 1) = 7 attribute reports since the underlying path iterator should be reset to the
+        // beginning of the cluster it is current iterating.
         ChipLogError(DataManagement, "OLD: %d\n", currentAttributeResponsesWhenSetDirty);
         ChipLogError(DataManagement, "NEW: %d\n", delegate.mNumAttributeResponse);
-        NL_TEST_ASSERT(apSuite, delegate.mNumAttributeResponse == currentAttributeResponsesWhenSetDirty + 14);
+        NL_TEST_ASSERT(apSuite, delegate.mNumAttributeResponse == currentAttributeResponsesWhenSetDirty + 7);
```
Comment (mrjerryjohns) [inline src/app/tests/TestReadInteraction.cpp:1326]: Can we restructure these tests to:

```
Mark Dirty (Item1, Item2, Item ...)
Generate Report Series()
Mark Dirty (Item4)
Validate Receiver (Item1, Item2, Item 3)
Generate Report Series()
Validate Receiver (Item4)
```

or something like this. This kind of macro-style, programming-instruction approach makes it easier to validate these various corner cases.

Right now, this logic is going based purely on counts, which is not at all accurate, and very brittle.

Comment (mrjerryjohns) [reply src/app/tests/TestReadInteraction.cpp:1326]: I'd like to see tests for the following (A, B, C = Clusters, 1, 2, 3 = Attribute IDs):

Basic:
1. Mark A1, A2, A3 dirty and deliver A1, A2, A3 in a single report.
2. "" + Mark A1, A2 again dirty, and validate we get A1, A2.

Advanced:
3. Mark A1 A2 A3 dirty, and deliver A1, A2 in a single chunked report. Validate we got A1, A2. Mark A2 dirty again, and generate another chunked report with A2 in it, and validate we get the newer A2, A3.
4. Mark A2 A2 A3 dirty, and deliver A1, A2 in one chunked report. Mark A1 dirty again. Validate we get A3 in the next chunked report, and then a new report chunks with A1 in it.
5. Any other tests you can think of.

To do the above, you'll need to be able to artificially limit the number of attributes that can be packed in a report in the reporting engine during test, as well as being able to tag the report chunking series (i.e exchanges) by assigning a number during OnReportBegin on the client.

File: src/app/ReadHandler.cpp (hunk 5 above)
Comment (mrjerryjohns) [reply src/app/ReadHandler.cpp]: I've come around to agreeing with @erjiaqing , that over-eagerly bundling dirty attributes in the current reporting series will cause issues with high rate of change attributes.

**Comment by mrjerryjohns** [comment]
The logic looks fine, but I think we need specific tests to validate the behaviors here (see testing suggestions).

File: src/app/ReadHandler.h (hunk 1 above)
Comment (erjiaqing) [reply src/app/ReadHandler.h]: Added comment

File: src/app/ReadHandler.h (hunk 2 above)
Comment (erjiaqing) [reply src/app/ReadHandler.h]: Explained in PR and comment

File: src/app/tests/TestReadInteraction.cpp (hunk 8 above)
Comment (erjiaqing) [reply src/app/tests/TestReadInteraction.cpp:1326]: Infact this is not what this test meant for, I have added another test in `controller/tests/TestReadChunking.cpp` and it should covered these.

**Comment by erjiaqing** [comment]
@mrjerryjohns @bzbarsky-apple 
The comments should be resolved and the tests should be updated (and covered) please take a look, thanks.

File: src/controller/tests/TestReadChunking.cpp [hunk 9]
```diff
@@ -509,13 +621,240 @@ void TestCommandInteraction::TestDynamicEndpoint(nlTestSuite * apSuite, void * a
...
+        app::AttributePathParams attributePath;
+        app::ReadPrepareParams readParams(sessionHandle);
+
+        readParams.mpAttributePathParamsList    = &attributePath;
+        readParams.mAttributePathParamsListSize = 1;
+        readParams.mMinIntervalFloorSeconds     = 0;
+        readParams.mMaxIntervalCeilingSeconds   = 2;
+
+        //// TEST 1 -- Read using wildcard paths
+        {
```
Comment (mrjerryjohns) [inline src/controller/tests/TestReadChunking.cpp:667]: The way these tests are designed makes it quite a bit difficult to decipher what's happening.

I'd very much have liked to see some kind of 'instruction list' like construct, similar to what I had done for `TestBufferedReadCallback.cpp`:

```
enum Attribute {
    kAttributeA,
    kAttributeB,
    kAttributeC
};

struct AttributeVersion {
     Attribute attribute;
     uint16_t version;
};

struct SingleExecutionRound {
    std::vector<Attribute> DirtyInstructions;
    std::vector<AttributeVersion> ReceivedAttributes;
};


ExecuteTest(std::vector<SingleExecutionRound> executionList);
```


Mark A, B dirty, and in the received report, we see A1, B1:
```
ExecuteTest({
                           { {AttributeA, AttributeB},  { {AttributeA, 1}, {AttributeB, 1} } },
                       });
```
Mark A, B, C dirty, and we deliver A, B in the first chunked report, and C later. This test requires artificially limiting the # of attributes that can be sent to 2 in a report:

LimitReportToAttributes(2);
ExecuteTest({
                           { {AttributeA, AttributeB, AttributeC},  { {AttributeA, 1}, {AttributeB, 1} } },
                          {  { },                                                         { {AttributeC, 1} }
                       });
```

etc...

Comment (mrjerryjohns) [reply src/controller/tests/TestReadChunking.cpp:667]: Each execution round is a single execution of the engine + receive processing. You can continue to use the 'mark the dirty items in the `OnAttributeData` trick you've employed above.

Comment (erjiaqing) [reply src/controller/tests/TestReadChunking.cpp:769]: Thanks for advice, infact, wrapping all the works into one function makes the code a bit messy since there are things should be checked in different forms.

Finally ended up with a extra struct, and some template functions / structs / variables to make the code clearer.

File: src/controller/tests/TestReadChunking.cpp [hunk 10]
```diff
@@ -509,13 +622,260 @@ void TestCommandInteraction::TestDynamicEndpoint(nlTestSuite * apSuite, void * a
...
+
+            ChipLogProgress(DataManagement, "Case 1-2: Set dirty during chunked report by wildcard path.");
+            readCallback.mActionOn[AttrOnEp5<Attr2>] = WriteAttrOnEndpoint5<Attr3, 3>;
+            DoTest(&readCallback,
+                   { .chunksize = 2,
+                     .preworks = { WriteAttrOnEndpoint5<Attr1, 2>, WriteAttrOnEndpoint5<Attr2, 2>, WriteAttrOnEndpoint5<Attr3, 2> },
+                     .expectedValues                = { { AttrOnEp5<Attr1>, 2 }, { AttrOnEp5<Attr2>, 2 }, { AttrOnEp5<Attr3>, 3 } },
+                     .attributesWithSameDataVersion = { { AttrOnEp5<Attr1>, AttrOnEp5<Attr2>, AttrOnEp5<Attr3> } } });
+
+            ChipLogProgress(DataManagement, "Case 1-3: Set dirty during chunked report by wildcard path -- new dirty attribute.");
```
Comment (mrjerryjohns) [inline src/controller/tests/TestReadChunking.cpp:798]: I'm not sure what the case numbering scheme here is, since the top number "1" is never changed at all.

I'd rather sub-steps as part of the same logical test be sub-numbered, so the above cases become "1-1, 1-2, 2-1, 3-1, 4-1".

File: src/controller/tests/TestReadChunking.cpp [hunk 11]
```diff
@@ -509,13 +622,260 @@ void TestCommandInteraction::TestDynamicEndpoint(nlTestSuite * apSuite, void * a
...
+
+            // When the report engine starts to report attributes in endpoint 5, mark cluster 1 as dirty.
+            // The report engine should NOT include it in initial report to reduce traffic.
+            // We are expected to miss attributes on kTestEndpointId during initial reports.
+            ChipLogProgress(DataManagement, "Case 1-1: Set dirty during priming report.");
+            readCallback.mActionOn[AttrOnEp5<Attr1>] = TouchAttrOnEndpoint1<Attr1>;
+            DriveIOUntilSubscriptionEstablished(&readCallback);
+            CheckValues(&readCallback, { { AttrOnEp1<Attr1>, 1 } });
+
+            ChipLogProgress(DataManagement, "Case 1-1: Check for attributes missed last report.");
```
Comment (mrjerryjohns) [inline src/controller/tests/TestReadChunking.cpp:787]: Repeating a case number is not necessary - a clearer way is described below.

File: src/controller/tests/TestReadChunking.cpp [hunk 12]
```diff
@@ -509,13 +622,260 @@ void TestCommandInteraction::TestDynamicEndpoint(nlTestSuite * apSuite, void * a
...
+
+            app::ReadClient readClient(engine, &ctx.GetExchangeManager(), readCallback.mBufferedCallback,
+                                       app::ReadClient::InteractionType::Subscribe);
+
+            NL_TEST_ASSERT(apSuite, readClient.SendRequest(readParams) == CHIP_NO_ERROR);
+
+            // When the report engine starts to report attributes in endpoint 5, mark cluster 1 as dirty.
+            // The report engine should NOT include it in initial report to reduce traffic.
+            // We are expected to miss attributes on kTestEndpointId during initial reports.
+            ChipLogProgress(DataManagement, "Case 1-1: Set dirty during priming report.");
```
Comment (mrjerryjohns) [inline src/controller/tests/TestReadChunking.cpp:782]: Can we use curly braces to nest the various test depths?

```
//
// Case 1: Describe the entire test here first.
//
{
     //
     // Case 1-1: Describe test sub-step here.
     //
      {
          ...
      }
}
```

File: src/controller/tests/TestReadChunking.cpp [hunk 13]
```diff
@@ -509,13 +622,260 @@ void TestCommandInteraction::TestDynamicEndpoint(nlTestSuite * apSuite, void * a
...
+            readCallback.mActionOn[AttrOnEp5<Attr2>] = WriteAttrOnEndpoint5<Attr3, 3>;
+            DoTest(&readCallback,
+                   { .chunksize = 2,
+                     .preworks = { WriteAttrOnEndpoint5<Attr1, 2>, WriteAttrOnEndpoint5<Attr2, 2>, WriteAttrOnEndpoint5<Attr3, 2> },
+                     .expectedValues                = { { AttrOnEp5<Attr1>, 2 }, { AttrOnEp5<Attr2>, 2 }, { AttrOnEp5<Attr3>, 3 } },
+                     .attributesWithSameDataVersion = { { AttrOnEp5<Attr1>, AttrOnEp5<Attr2>, AttrOnEp5<Attr3> } } });
+
+            ChipLogProgress(DataManagement, "Case 1-3: Set dirty during chunked report by wildcard path -- new dirty attribute.");
+
+            readCallback.mActionOn[AttrOnEp5<Attr2>] = WriteAttrOnEndpoint5<Attr3, 4>;
```
Comment (mrjerryjohns) [inline src/controller/tests/TestReadChunking.cpp:800]: It'd be a lot easier to read if we made this WriteAttr<AttrOnEp5<Attr3, 4>>. That re-uses the same nomenclature for validation.

File: src/controller/tests/TestReadChunking.cpp [hunk 14]
```diff
@@ -509,13 +622,260 @@ void TestCommandInteraction::TestDynamicEndpoint(nlTestSuite * apSuite, void * a
...
+    Attr3 = 3,
+};
+
+using AttributeWithValue = std::pair<AttributeIdWithEndpointId, uint8_t>;
+using AttributesList     = std::vector<AttributeIdWithEndpointId>;
+
+struct Instruction
+{
+    uint32_t chunksize;
+    std::vector<std::function<void()>> preworks;
```
Comment (mrjerryjohns) [inline src/controller/tests/TestReadChunking.cpp:670]: Please add a lot more comments about exactly what each of these fields mean.

**Review by mrjerryjohns — APPROVED** [review]

File: src/controller/tests/TestReadChunking.cpp (hunk 11 above)
Comment (erjiaqing) [reply src/controller/tests/TestReadChunking.cpp]: I think the case number in the log are important, they can help us locate the failed test from the log.

File: src/app/reporting/Engine.h [hunk 15]
```diff
@@ -120,6 +122,8 @@ class Engine
 
     uint32_t GetNumReportsInFlight() const { return mNumReportsInFlight; }
 
+    uint64_t GetDirtyTick() const { return mDirtyTick; }
```
Comment (bzbarsky-apple) [inline src/app/reporting/Engine.h:125]: `GetDirtySetGeneration`

File: src/app/reporting/Engine.h [hunk 16]
```diff
@@ -175,6 +179,8 @@ class Engine
      */
     bool MergeOverlappedAttributePath(AttributePathParams & aAttributePath);
 
+    inline void BumpDirtyTick() { mDirtyTick++; }
```
Comment (bzbarsky-apple) [inline src/app/reporting/Engine.h:182]:
```suggestion
    inline void BumpDirtySetGeneration() { mDirtySetGeneration++; }
```

File: src/app/reporting/Engine.h [hunk 17]
```diff
@@ -203,10 +209,21 @@ class Engine
...
-    ObjectPool<AttributePathParams, CHIP_IM_SERVER_MAX_NUM_DIRTY_SET> mGlobalDirtySet;
+    ObjectPool<AttributePathParamsWithTimestamp, CHIP_IM_SERVER_MAX_NUM_DIRTY_SET> mGlobalDirtySet;
+
+    /**
+     * A ticker for recording when an attribute is makred as dirty. Acts as a monotonic timestamp for attributes.
+     * ReadHandlers can save the tick value when it is generating reports, then we can tell if an attribute is not reported by
+     * checking this timestamp.
+     *
+     * mDirtyTick will increase by one when SetDirty is called.
+     * Count it from 1, so 0 will be used to indicate "the read handler has never been reported"
```
Comment (bzbarsky-apple) [inline src/app/reporting/Engine.h:220]:
```suggestion
     * A generation counter for the dirty attrbute set.
     *
     * ReadHandlers can save the tick value when generating reports.
     * 
     * Then we can tell whether they might have missed reporting an attribute by
     * comparing its generation counter to the saved one.
     *
     * mDirtySetGeneration will increase by one when SetDirty is called.
     *
     * Count it from 1, so 0 can be used in ReadHandler to indicate "the read handler has never
     * completed a report".
```

File: src/app/reporting/Engine.h [hunk 18]
```diff
@@ -203,10 +209,21 @@ class Engine
...
+     */
+    uint64_t mDirtyTick = 1;
```
Comment (bzbarsky-apple) [inline src/app/reporting/Engine.h:222]:
```suggestion
    uint64_t mDirtySetGeneration = 1;
```

File: src/app/tests/TestReadInteraction.cpp [hunk 19]
```diff
@@ -1319,10 +1319,11 @@ void TestReadInteraction::TestSetDirtyBetweenChunks(nlTestSuite * apSuite, void
 
         ctx.DrainAndServiceIO();
 
-        // We should receive another 2 * (6 + 1) = 14 attribute reports since the underlying path iterator should be reset.
+        // We should receive another (6 + 1) = 7 attribute reports since the underlying path iterator should be reset to the
+        // beginning of the cluster it is current iterating.
```
Comment (bzbarsky-apple) [inline src/app/tests/TestReadInteraction.cpp:1323]:
```suggestion
        // beginning of the cluster it is currently iterating.
```

**Review by bzbarsky-apple — COMMENTED** [review]
There are some naming and comment fixes, but generally this looks quite good, thank you!

I did not review the TestReadChunking changes carefully...

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking given this has had > 3 days for review.

File: src/app/ReadHandler.h [hunk 20]
```diff
@@ -283,7 +284,40 @@ class ReadHandler : public Messaging::ExchangeDelegate
...
+
+    // The timestamp when this read handler was marked as a dirty read handler.
+    // In SetDirty(), we reset the iterator to the beginning of the current cluster instead of the beginning of the whole report, we
+    // might miss the change and regard this ReadHandler as a clean ReadHandler by mistake. So we record the time when this
+    // ReadHandler was marked as a dirty ReadHandler, and another time when the Readhandler reports attribute change, then we can
+    // tell if the ReadHandler is clean by checking these timestamps. The timestamp is represented by a counter which will increment
+    // by 1 every time an attribute is marked dirty by the reporting engine.
+    uint64_t mDirtyTick = 0;
+    // Emitting new events won't notify the report enging except for the urgent events, we use a OverrideDirty flag to indicate this
+    // state that we have something to report for this ReadHandler.
```
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/app/ReadHandler.h:297]: Yes, we don't need to set mForceDirty flag in the SetDirty() function, since the dirty generations stuff already marked the read handler dirty.

File: src/app/AttributePathExpandIterator.cpp [hunk 21]
```diff
@@ -140,6 +140,25 @@ void AttributePathExpandIterator::PrepareAttributeIndexRange(const AttributePath
     }
 }
 
+void AttributePathExpandIterator::ResetCurrentCluster()
+{
+    // If this is a null iterator, or the attribute id of current cluster info is not a wildcard attribute id, then this function
+    // will do nothing, since we won't be expanding the wildcard attribute ids under a cluster. Back to the beginning of reporting
```
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/app/AttributePathExpandIterator.cpp]: This is added to ReadHandler, in the SetDirty bits.

File: src/app/AttributePathExpandIterator.cpp [hunk 22]
```diff
@@ -140,6 +140,25 @@ void AttributePathExpandIterator::PrepareAttributeIndexRange(const AttributePath
...
+    // current cluster.
```
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/app/AttributePathExpandIterator.cpp]: Yes, this sentense should be removed.

File: src/app/AttributePathParams.h [hunk 23]
```diff
@@ -86,5 +86,16 @@ struct AttributePathParams
     EndpointId mEndpointId   = kInvalidEndpointId;  // uint16
     ListIndex mListIndex     = kInvalidListIndex;   // uint16
 };
+
+struct AttributePathParamsWithTimestamp : public AttributePathParams
```
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/app/AttributePathParams.h]: Moved to Engine.cpp

File: src/app/AttributePathParams.h [hunk 24]
```diff
@@ -86,5 +86,16 @@ struct AttributePathParams
...
+{
+    AttributePathParamsWithTimestamp() {}
+    AttributePathParamsWithTimestamp(const AttributePathParams aPath) : AttributePathParams(aPath) {}
+    AttributePathParamsWithTimestamp(const AttributePathParams aPath, uint64_t aTickTouched) :
+        AttributePathParams(aPath), mTickTouched(aTickTouched)
+    {}
```
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/app/AttributePathParams.h]: Removed

File: src/app/AttributePathParams.h [hunk 25]
```diff
@@ -86,5 +86,16 @@ struct AttributePathParams
...
+    uint64_t mTickTouched = 0;
```
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/app/AttributePathParams.h]: Yes, they are not really a timestamp. Generation is a better word than timestamp and tick.

File: src/app/ReadHandler.h [hunk 26]
```diff
@@ -131,9 +131,10 @@ class ReadHandler : public Messaging::ExchangeDelegate
      */
     bool IsFromSubscriber(Messaging::ExchangeContext & apExchangeContext) const;
 
-    bool IsReportable() const { return mState == HandlerState::GeneratingReports && !mHoldReport && (mDirty || !mHoldSync); }
+    bool IsReportable() const { return mState == HandlerState::GeneratingReports && !mHoldReport && (IsDirty() || !mHoldSync); }
     bool IsGeneratingReports() const { return mState == HandlerState::GeneratingReports; }
     bool IsAwaitingReportResponse() const { return mState == HandlerState::AwaitingReportResponse; }
+    void ResetPathIterator();
```
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/app/ReadHandler.h:139]: Added
