### PR TITLE
Fix 17211: TV Casting does not work on Mac 

### LINKED ISSUE #17211: TV Casting does not work on Mac
#### Problem
 * should be able to compile and run tv-app and tv-casting-app on Mac
 * instead, commissioning fails due to a variety of issues

 #### Proposed Solution
Fix issues on Mac

### PR DESCRIPTION
**Pull request by chrisdecenzo**
#### Problem
* Fix #17211 

#### Change overview
* Fix MDns instance filter
* Update tv-casting-app to not use same files for storage (fixes "[SC] Failed to obtain IPK for initiating" error message)
* Fix commissioning when BLE disabled
* Add proper shell to casting app, with commands to discover and to request commissioning
* Fix re-use of discovery controller

#### Testing
* run tv-app and tv-casting-app from the same Mac

### CODE REVIEW

File: src/app/server/CommissioningWindowManager.cpp [hunk 1]
```diff
@@ -318,10 +318,12 @@ CHIP_ERROR CommissioningWindowManager::StartAdvertisement()
     }
 #endif
 
+#if CONFIG_NETWORK_LAYER_BLE
```
[the remark this answers is not in the document]
Comment (chrisdecenzo) [reply src/app/server/CommissioningWindowManager.cpp:321]: This was part of the reason that casting wasn't working on Mac - when BLE is disabled, these routines are still getting called (and returning errors)

**Review by sharadb-amazon — APPROVED** [review]

File: examples/tv-casting-app/linux/main.cpp [hunk 2]
```diff
@@ -166,6 +194,7 @@ void PrepareForCommissioning(const Dnssd::DiscoveredNodeData * selectedCommissio
  * Accepts user input of selected commissioner and calls PrepareForCommissioning with
  * the selected commissioner
  */
+/*
```
Comment (andy31415) [inline examples/tv-casting-app/linux/main.cpp:197]: Commented out code should generally be just removed (git history would preseve it if really needed)

File: examples/tv-casting-app/linux/main.cpp [hunk 3]
```diff
@@ -218,6 +241,32 @@ void InitCommissioningFlow(intptr_t commandArg)
     }
 }
 
+CHIP_ERROR DiscoverCommissioners()
+{
+    // Send discover commissioners request
+    ReturnErrorOnFailure(gCommissionableNodeController.DiscoverCommissioners(gDiscoveryFilter));
+
+    // Give commissioners some time to respond and then ScheduleWork to initiate commissioning
+    DeviceLayer::SystemLayer().StartTimer(
```
Comment (andy31415) [inline examples/tv-casting-app/linux/main.cpp:250]: I believe startTimer returns a CHIP_ERROR, so this should be the final return and not ignored.

File: examples/tv-casting-app/linux/main.cpp [hunk 4]
```diff
@@ -218,6 +241,32 @@ void InitCommissioningFlow(intptr_t commandArg)
...
+    return CHIP_NO_ERROR;
+}
+
+CHIP_ERROR RequestCommissioning(int index)
+{
+    const Dnssd::DiscoveredNodeData * selectedCommissioner =
+        gCommissionableNodeController.GetDiscoveredCommissioner(index);
+    if (selectedCommissioner == nullptr)
+    {
+        ChipLogError(AppServer, "No such commissioner!");
```
Comment (andy31415) [inline examples/tv-casting-app/linux/main.cpp:263]: I would add details if we log: `ChipLogError(AppServer, "No commisionier with index %d exists", index);`

File: examples/tv-casting-app/linux/main.cpp [hunk 5]
```diff
@@ -492,10 +543,43 @@ void ReadServerClustersForNode(NodeId nodeId)
...
+    if (err != CHIP_NO_ERROR)
+    {
+        ChipLogError(AppServer, "Associate() failed: %" CHIP_ERROR_FORMAT, err.Format());
+        return err;
+    }
+    LaunchURL::Type request;
+    request.contentURL          = chip::CharSpan::fromCharString(contentUrl);
+    request.displayString       = Optional<CharSpan>(chip::CharSpan::fromCharString(contentDisplayStr));
+    request.brandingInformation = Optional<chip::app::Clusters::ContentLauncher::Structs::BrandingInformation::Type>(
+            chip::app::Clusters::ContentLauncher::Structs::BrandingInformation::Type());
```
Comment (bzbarsky-apple) [inline examples/tv-casting-app/linux/main.cpp:578]:
```suggestion
    request.brandingInformation = MakeOptional(
            chip::app::Clusters::ContentLauncher::Structs::BrandingInformation::Type());
```
Or could just not set it at all, since "optional without value" is the default anyway....

File: src/platform/Darwin/DnssdImpl.cpp [hunk 6]
```diff
@@ -383,9 +383,19 @@ CHIP_ERROR Browse(void * context, DnssdBrowseCallback callback, uint32_t interfa
...
     if (position != std::string::npos)
     {
-        regtype = regtype.substr(position + subtypeDelimiter.size()) + "," + regtype.substr(0, position);
+        if (regtype.rfind("_", position) == 0)
+        {
+            regtype = regtype.substr(position + subtypeDelimiter.size()) + "," + regtype.substr(0, position);
+        }
+        else
+        {
+            // if it doesn't start with "_" then don't include the instance name
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.cpp:395]: This needs a much clearer explanation of why (the current comment just describes "what", which is already clear from the code... though even on the "what" the code does not seem to match the comment).  What cases is this trying to handle and why is this the right way to handle them?

File: src/platform/Darwin/DnssdImpl.cpp [hunk 7]
```diff
@@ -383,9 +383,19 @@ CHIP_ERROR Browse(void * context, DnssdBrowseCallback callback, uint32_t interfa
     std::string regtype(type);
     std::string subtypeDelimiter = "._sub.";
     size_t position              = regtype.find(subtypeDelimiter);
+    // if we have more in the string (a subtype) then append it to the end
```
[the remark this answers is not in the document]
Comment (chrisdecenzo) [reply src/platform/Darwin/DnssdImpl.cpp:386]: Updated the comment to be more clear, with examples

File: examples/tv-casting-app/linux/main.cpp (hunk 2 above)
Comment (chrisdecenzo) [reply examples/tv-casting-app/linux/main.cpp]: Removed

File: examples/tv-casting-app/linux/main.cpp (hunk 4 above)
Comment (chrisdecenzo) [reply examples/tv-casting-app/linux/main.cpp]: Done

File: examples/tv-casting-app/linux/CastingShellCommands.cpp [hunk 8]
```diff
@@ -0,0 +1,116 @@
...
+
+static CHIP_ERROR CastingHandler(int argc, char ** argv)
+{
+    CHIP_ERROR error = CHIP_NO_ERROR;
+
+    if (argc == 0 || strcmp(argv[0], "help") == 0)
+    {
+        return PrintAllCommands();
+    }
+    else if (strcmp(argv[0], "discover") == 0)
```
[the remark this answers is not in the document]
Comment (chrisdecenzo) [reply examples/tv-casting-app/linux/CastingShellCommands.cpp:59]: This is a convention in these shell commands but I will fix if CI complains

File: examples/tv-casting-app/linux/main.cpp (hunk 5 above)
Comment (chrisdecenzo) [reply examples/tv-casting-app/linux/main.cpp]: done

File: src/platform/Darwin/DnssdImpl.cpp (hunk 6 above)
Comment (chrisdecenzo) [reply src/platform/Darwin/DnssdImpl.cpp]: Updated the comment with more explanation and examples

File: examples/tv-casting-app/linux/main.cpp (hunk 3 above)
Comment (chrisdecenzo) [reply examples/tv-casting-app/linux/main.cpp]: Fixed

File: examples/tv-casting-app/linux/CastingShellCommands.cpp [hunk 9]
```diff
@@ -0,0 +1,125 @@
...
+    {
+        ChipLogProgress(DeviceLayer, "discover");
+
+        return error = DiscoverCommissioners();
```
Comment (andy31415) [inline examples/tv-casting-app/linux/CastingShellCommands.cpp:63]: all these `return error = ....` should be replaced with `return ....`.
Then remove the error variable.

File: examples/tv-casting-app/linux/CastingShellCommands.cpp [hunk 10]
```diff
@@ -0,0 +1,125 @@
...
+        chip::Inet::IPAddress commissioner;
+        chip::Inet::IPAddress::FromString(argv[1], commissioner);
+        uint16_t port = (uint16_t) strtol(argv[2], &eptr, 10);
+        return SendUDC(chip::Transport::PeerAddress::UDP(commissioner, port));
+    }
+    else
+    {
+        return CHIP_ERROR_INVALID_ARGUMENT;
+    }
+    return error;
```
Comment (andy31415) [inline examples/tv-casting-app/linux/CastingShellCommands.cpp:111]: return error is redundant. Please follow https://clang.llvm.org/extra/clang-tidy/checks/readability-else-after-return.html

File: examples/tv-casting-app/linux/CastingShellCommands.cpp [hunk 11]
```diff
@@ -0,0 +1,125 @@
...
+}
+
+void RegisterCastingCommands()
+{
+
+    static const shell_command_t sDeviceComand = { &CastingHandler, "cast", "Casting commands. Usage: cast [command_name]" };
+
+    // Register the root `device` command with the top-level shell.
+    Engine::Root().RegisterCommands(&sDeviceComand, 1);
+    return;
```
Comment (andy31415) [inline examples/tv-casting-app/linux/CastingShellCommands.cpp:121]: please remove redundant return

Comment (chrisdecenzo) [reply examples/tv-casting-app/linux/CastingShellCommands.cpp]: done

File: examples/tv-casting-app/linux/CastingShellCommands.cpp (hunk 10 above)
Comment (chrisdecenzo) [reply examples/tv-casting-app/linux/CastingShellCommands.cpp]: done

File: examples/tv-casting-app/linux/CastingShellCommands.cpp (hunk 9 above)
Comment (chrisdecenzo) [reply examples/tv-casting-app/linux/CastingShellCommands.cpp]: done

**Review by andy31415 — APPROVED** [review]

File: examples/tv-casting-app/linux/main.cpp [hunk 12]
```diff
@@ -156,31 +177,26 @@ void PrepareForCommissioning(const Dnssd::DiscoveredNodeData * selectedCommissio
     if (selectedCommissioner != nullptr)
     {
         // Send User Directed commissioning request
-        ReturnOnFailure(Server::GetInstance().SendUserDirectedCommissioningRequest(chip::Transport::PeerAddress::UDP(
-            selectedCommissioner->ipAddress[0], selectedCommissioner->port, selectedCommissioner->interfaceId)));
+        // Wait 1 second to allow our commissionee DNS records to publish (needed on Mac)
+        int32_t expiration = 1;
+        DeviceLayer::SystemLayer().StartTimer(System::Clock::Seconds32(expiration),
```
Comment (andy31415) [inline examples/tv-casting-app/linux/main.cpp:182]: is it ok to ignore any CHIP_ERROR returned here?

Comment (chrisdecenzo) [reply examples/tv-casting-app/linux/main.cpp]: addressed

File: src/platform/Darwin/DnssdImpl.cpp [hunk 13]
```diff
@@ -383,9 +383,29 @@ CHIP_ERROR Browse(void * context, DnssdBrowseCallback callback, uint32_t interfa
...
     if (position != std::string::npos)
     {
-        regtype = regtype.substr(position + subtypeDelimiter.size()) + "," + regtype.substr(0, position);
+        // DNSServiceBrowse allows searching by type, and by subtype (PTR records).
+        //  (ex. _matterc._udp.local. or _CM._sub._matterc._udp.local.)
+        //
+        // It does not include support for searching by instance name (SRV records).
+        //  (ex. DD200C20D25AE5F7._matterc._udp.local.)
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.cpp:393]: But in that string, there is no "._sub.", so we won't even be in this branch.  Why is that string relevant to this code?

Comment (chrisdecenzo) [reply src/platform/Darwin/DnssdImpl.cpp]: looking deeper into this code, it turns out that the instance name filter was not being handled correctly by the resolver since it was being treated as a subtype which it is not. When we know the instance, we just need to perform a resolve and not a browse.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by lazarkov — APPROVED** [review]

File: examples/tv-casting-app/linux/main.cpp [hunk 14]
```diff
@@ -158,31 +179,25 @@ void PrepareForCommissioning(const Dnssd::DiscoveredNodeData * selectedCommissio
     if (selectedCommissioner != nullptr)
     {
         // Send User Directed commissioning request
-        ReturnOnFailure(Server::GetInstance().SendUserDirectedCommissioningRequest(chip::Transport::PeerAddress::UDP(
-            selectedCommissioner->ipAddress[0], selectedCommissioner->port, selectedCommissioner->interfaceId)));
+        // Wait 1 second to allow our commissionee DNS records to publish (needed on Mac)
```
Comment (andy31415) [inline examples/tv-casting-app/linux/main.cpp:182]: Sleep is generally discouraged as a method of synchronization.

Comment (chrisdecenzo) [reply examples/tv-casting-app/linux/main.cpp:182]: I will address this in https://github.com/project-chip/connectedhomeip/issues/17299
