### PR TITLE
Ensure that we send MRP acks to incoming messages as needed.

### LINKED ISSUE #10515: Acks to unencrypted messages broken after exchange closure
#### Problem
Consider the case of an unencrypted message coming in after the exchange it was targeting has been closed (e.g. it's a duplicate of the last message in a handshake, because the other side never got our ack).

We land in `ExchangeManager::OnMessageReceived` and don't match any existing exchanges.  We create a new exchange to handle the standalone ack.  We do this check:
```
        if (ec->IsEncryptionRequired() != packetHeader.GetFlags().Has(Header::FlagValues::kEncryptedMessage))
            ChipLogError(ExchangeManager, "OnMessageReceived failed, err = %s", ErrorStr(CHIP_ERROR_INVALID_MESSAGE_TYPE));
            ec->Close();
            return;
```
and the condition tests true, because the standalone ack exchange has no delegate, hence uses the `mDefaultExchangeDispatch` of the exchange manager, which is an `ApplicationExchangeDispatch`, which requires encryption.

So we never send the ack.

 #### Proposed Solution
Fix things so we send acks properly.

@pan-apple @kghost

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
There were two ways we could fail to send an ack to an incoming reliable message:

1) If we found no matching handler, and hence created an ephemeral exchange to
handle the message, but the message was unencrypted.  In this case our ephemeral
exchange would return true for IsEncryptionRequired(), because it would default
to an ApplicationExchangeDispatch, and we would never call into
ExchangeContext::HandleMessage.

2) If ExchangeMessageDispatch::MessagePermitted returned false for the message.
In particular, for an ApplicationExchangeDispatch, this would happen for all the
handshake messages except StatusReport.

The fix for issue 1 is to ensure we always call into HandleMEssage if we manage
to allocate an exchange.  If there is an encryption mismatch, which only matters
when the exchange is non-ephemeral, we close the exchange first to prevent event
delivery to the delegate.

The fix for issue 2 is to move the MRP processing out of ExchangeMessageDispatch
and into ExchangeContext, and to move the MessagePermitted check so the only
thing it prevents is delivery of the message to the delegate, not any other
processing by the exchange.

Fixes https://github.com/project-chip/connectedhomeip/issues/10515

#### Problem
See above.

#### Change overview
See above.

#### Testing
Introduced a 10-second sleep in CASE StatusReport processing, which without these changes caused acks to the resent Sigma3 or Sigma2Resume message to be dropped.  Verified that with these changes those acks are sent correctly.  That exercises problem 1.  

In addition to the above, added StatusReport to the list of disallowed messages in `ApplicationExchangeDispatch::MessagePermitted` and verified that without the changes to fix problem 2 above acks failed to be sent, but with the changes in this PR acks were sent correctly.

### CODE REVIEW

File: src/messaging/ExchangeMgr.cpp [hunk 1]
```diff
@@ -310,11 +310,23 @@ void ExchangeManager::OnMessageReceived(const PacketHeader & packetHeader, const
...
+            // We want to still to do MRP processing for this message, but we do
+            // not want to deliver it to the application.  Just close the
+            // exchange (which will notify the delegate, null it out, etc), then
+            // go ahead and call HandleMessage() on it to do the MRP
+            // processing.null out the delegate on the exchange, pretend to
+            // matchingUMH that exchange creation failed, so it cleans up the
+            // delegate, then tell the exchagne to handle the message.
+            ChipLogProgress(ExchangeManager, "OnMessageReceived encryption mismatch");
             ec->Close();
-            return;
```
Comment (kghost) [inline src/messaging/ExchangeMgr.cpp:317]: I'd say no to this. `HandleMessage` on a closed exchange, it just too tricky, to hard too follow.

The UMH logic is twisted with StandaloneAck for unmatching packet, I'd prefer writing 2 separate functions, to handle them separately.

**Review by woody-apple — APPROVED** [review]

File: src/messaging/ExchangeMgr.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/messaging/ExchangeMgr.cpp:317]: > I'd say no to this. HandleMessage on a closed exchange, it just too tricky, to hard too follow.

It better not be!  It happens all the time.  I send a message and close the exchange, the other side sends a message in response, it gets dispatched to that exchange.

**Review by kghost — APPROVED** [review]

File: src/messaging/ExchangeMgr.cpp (hunk 1 above)
Comment (kghost) [reply src/messaging/ExchangeMgr.cpp:317]: This should be addressed separately.
