### PR TITLE
Don't use LwIP defines if CHIP_SYSTEM_CONFIG_USE_LWIP is not set.

### LINKED ISSUE #29211: [BUG] LWIP_PBUF_FROM_CUSTOM_POOLS and PBUF_POOL_SIZE don't seem to be set up in a reasonable way
### Reproduction steps

LWIP_PBUF_FROM_CUSTOM_POOLS and PBUF_POOL_SIZE are used by some of our config headers (as in, its _value_ is used in `ReliableMessageProtocolConfig.h`), but where are they supposed to be defined by consumers?  Some things seem to have them in `lwipopts.h`, but our config headers  don't include `lwipopts.h`, right?

How is this supposed to work?

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

b02c9842e3dedc8f81f16760da5c322affdf27ee

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Fixes https://github.com/project-chip/connectedhomeip/issues/29211

### CODE REVIEW

File: src/messaging/ReliableMessageProtocolConfig.h [hunk 1]
```diff
@@ -122,15 +123,23 @@ namespace chip {
  *
  */
 #ifndef CHIP_CONFIG_RMP_RETRANS_TABLE_SIZE
-#if LWIP_PBUF_FROM_CUSTOM_POOLS
-#define CHIP_CONFIG_RMP_RETRANS_TABLE_SIZE CHIP_CONFIG_MAX_EXCHANGE_CONTEXTS
-#elif PBUF_POOL_SIZE
+#if CHIP_SYSTEM_CONFIG_USE_LWIP
+
```
Comment (rojer) [inline src/messaging/ReliableMessageProtocolConfig.h:127]: suggest `#include "lwip/opt.h"` here to ensure `PBUF_POOL_SIZE` is defined.

Comment (bzbarsky-apple) [reply src/messaging/ReliableMessageProtocolConfig.h:127]: Aha!  I was wondering where this sort of thing was supposed to come from.

Thank you.

**Review by saurabhst — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by pidarped — APPROVED** [review]
