### PR TITLE
Don't automatically close exchanges if the underlying connection closes.

### LINKED ISSUE #7012: ExchangeManager::OnConnectionExpired is incorrectly closing exchanges, can cause lost messages or crashes
STEPS TO REPRODUCE:
1. Compile all-clusters-app for m5stack with pairing mode set to BLE
2. Run it on the m5stack
3. On desktop (Mac in my case) run `./gn_build.sh`
4. Run `./out/debug/standalone/chip-tool pairing ble-wifi x y 112233 12345678 3840`

where "x" and "y" can be replaced with the WiFi SSID and password as desired.

EXPECTED RESULTS: M5Stack joins the wifi network

ACTUAL RESULTS: M5Stack gets the SSID and password, but never gets an EnableNetwork command.

@pan-apple and I dug through what happens on the chip-tool side, and it looks like the following, starting at the first place where something weird starts to happen:

1. We send the AddRootCert command on exchange N.  Exchange context N has a refcount of 1 at this point.
2. The response to AddRootCert comes back.
3. `ExchangeContext::HandleResponse` takes a ref, refcount is 2.
4. The actual response handling calls `Close` because we got a response, refcount is 1
5. Response handling calls into the app logic, which decides pairing is done and we need to reload some CHIPDevice info now.
6. We end up in `SecureSessionMgr::NewPairing` which calls `MarkConnectionsExpired`.
7. That lands in `ExchangeManager::OnConnectionExpired` which calls `Close` on all the exchange contexts for the session.  Refcount goes to 0 and exchange context N is destroyed.
8. We unwind back to more app logic, which decides to send the AddNetwork command.
9. The command sender asks for a new exchange context, gets exchange context N (because it's available!), refcount is now 1
10. The command gets sent.
11. Stack unwinds all the way back to `ExchangeContext::HandleResponse`, which drops the ref it took.  Refcount goes to 0, exchange context N is destroyed.
12. Eventually the server responds to the AddNetwork command, but the exchange is gone, so we treat it as an unsolicited non-initiator message and drop it.
13. We time out the commissioning process and never send EnableNetwork.

A note: If at step 9 we had gotten a _different_ exchange context then instead of step 11 destroying an exchange context that should not be destroyed it would have called Release() on a 0-refcount context and hit the `abort()` there.

 #### Proposed Solution
Stop calling `Close` on random exchange contexts that we don't understand the lifetime of.  That will lead to use-after-free, as here.  If the teardown had happened when someone had allocated an exchange but not yet called SendMessage, they would have ended up calling SendMessage on a deleted exchange....  Maybe that case would have been helped by a delegate being notified the exchange is closing (though I am doubtful), but note in the above steps we are closing an already-closed exchange, so even that does not help.

@kghost @andreilitvin

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Someone might still have a reference to those exchanges, and we will
end up with an unbalanced release.  Instead just notify our consumer
in the specific case when we are waiting for a response so it knows
the response will never come (and presumably closes the exchange as
needed).

#### Problem
Fixes https://github.com/project-chip/connectedhomeip/issues/7012

#### Change overview
Instead of hard-closing exchanges on connection close, just notify the ones that are waiting for a response that it won't be coming.

#### Testing
* There are automated tests for some basic behavior included in this PR.
* I manually tested that applying this on top of #7041 allows me to successfully complete ble-wifi pairing with the C++ chip-tool.

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

File: src/messaging/ExchangeMgr.h [hunk 1]
```diff
@@ -249,9 +249,13 @@ class DLL_EXPORT ExchangeManager : public SecureSessionMgrDelegate, public Trans
                            SecureSessionMgr * msgLayer) override;
 
     void OnNewConnection(SecureSessionHandle session, SecureSessionMgr * mgr) override;
+#if CHIP_CONFIG_TEST
+public: // Allow OnConnectionExpired to be called directly from tests.
+#endif  // CHIP_CONFIG_TEST
     void OnConnectionExpired(SecureSessionHandle session, SecureSessionMgr * mgr) override;
 
     // TransportMgrDelegate interface for rendezvous sessions
+private:
```
Comment (yufengwangca) [inline src/messaging/ExchangeMgr.h:258]: We can save 'private' if we move OnMessageReceived before  OnConnectionExpired

File: src/messaging/ExchangeContext.cpp [hunk 2]
```diff
@@ -300,6 +300,21 @@ bool ExchangeContext::MatchExchange(SecureSessionHandle session, const PacketHea
...
+        // Nothing to do in this case
+        return;
+    }
+
+    // If we're waiting on a response, we now know it's never going to show up
+    // and we should notify our delegate accordingly.
+    CancelResponseTimer();
+    SetResponseExpected(false);
+    NotifyResponseTimeout();
+}
```
Comment (yufengwangca) [inline src/messaging/ExchangeContext.cpp:316]: ExchangeContext is created with a valid SecureSession, is mSecureSession still valid after the associated connection get closed?

**Review by Damian-Nordic — APPROVED** [review]

File: src/messaging/ExchangeContext.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/messaging/ExchangeContext.cpp:316]: That is a good question.  None of that stuff is documented, so I don't know.  @pan-apple ?

File: src/messaging/ExchangeMgr.h (hunk 1 above)
Comment (bzbarsky-apple) [reply src/messaging/ExchangeMgr.h:258]: We can, but then we run the danger of someone adding something that ends up public in tests if they just put it at te end of the file.  So this is safer, imo.

File: src/messaging/ExchangeContext.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/messaging/ExchangeContext.cpp:316]: Per discussion with @pan-apple we should reset `mSecureSession` here so no more messages can be sent on this exchange.

File: src/messaging/ExchangeContext.cpp [hunk 3]
```diff
@@ -300,6 +300,27 @@ bool ExchangeContext::MatchExchange(SecureSessionHandle session, const PacketHea
         && (payloadHeader.IsInitiator() != IsInitiator());
 }
 
+void ExchangeContext::OnConnectionExpired()
+{
+    // Reset our mSecureSession to a default-initialized (hence not matching any
+    // connection state) value, because it's still referencing the now-expired
+    // connection.  This will mean that no more messages can be sent via this
+    // exchange, which seems fine given the semantics of connection expiration.
+    mSecureSession = SecureSessionHandle();
```
Comment (yufengwangca) [inline src/messaging/ExchangeContext.cpp:309]: After we reset the SessionHandle, this exchange can not be used to send any message.

Let's go back the the original issue.

After we send AddRootCert command and receive the response to AddRootCert, the connection is closed. 
Now we don't close the exchange, but reset the SessionHandle of the exchange.

On which exchange we send AddNetwork Command? My understand is we should continue to use the same exchange to send this command and close the exchange when we reach the end of conversation  (Received the response of AddNetwork Command)

Comment (bzbarsky-apple) [reply src/messaging/ExchangeContext.cpp:309]: > On which exchange we send AddNetwork Command?

A different one.  Each new Invoke is a new exchange in the spec.

**Review by yufengwangca — APPROVED** [review]

**Review by mspang — APPROVED** [review]
