### PR TITLE
Non concurrent mode now sends connect network response as per spec

### LINKED ISSUE #31660: [1.3] Implement Non-Concurrent Spec Change #8728 in SDK
### Reproduction steps

Run in non-concurrent mode.
The ConnectNetworkResponse(Success) is not sent as required by the https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/8728 spec change.
https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/8728

Non-concurrent mode in lighting app requires examples/lighting-app/linux/include/CHIPProjectAppConfig.h to be modified as follows.
#define CHIP_DEVICE_CONFIG_SUPPORTS_CONCURRENT_CONNECTION 0

### Bug prevalence

Every time.

### GitHub hash of the SDK that was being used

88c0d58faa

### Platform

raspi

### Platform Version(s)

Head of SDK

### Type

Spec Compliance Issue

### Anything else?

https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/8728

### PR DESCRIPTION
**Pull request by simonhmorris1**
Fixes #31660, Implement Non-Concurrent Spec Change #8728 in the SDK.

This change now sends the ConnectNetworkResponse(Success) on the commissioning channel before closing it and enabling the operation channel as required by the https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/8728 spec change.

This changes the commissioner and Linux Raspberry Pi lighting app commissionee. The Non-concurrent mode in lighting app requires examples/lighting-app/linux/include/CHIPProjectAppConfig.h to be modified as follows to disable concurrent connection mode. `#define CHIP_DEVICE_CONFIG_SUPPORTS_CONCURRENT_CONNECTION 0`

This has been tested with the `CHIP_DEVICE_CONFIG_SUPPORTS_CONCURRENT_CONNECTION` set to zero and one, the passing test logs are attached.

[chip_output_concurrent_mode.txt](https://github.com/project-chip/connectedhomeip/files/14082223/chip_output_concurrent_mode.txt)
[light-app-concurrent.txt](https://github.com/project-chip/connectedhomeip/files/14082224/light-app-concurrent.txt)
[light-app-non-concurrent.txt](https://github.com/project-chip/connectedhomeip/files/14082225/light-app-non-concurrent.txt)
[chip_output_non-concurrent_mode.txt](https://github.com/project-chip/connectedhomeip/files/14082227/chip_output_non-concurrent_mode.txt)

### CODE REVIEW

File: src/platform/Linux/BLEManagerImpl.cpp [hunk 1]
```diff
@@ -215,12 +219,29 @@ void BLEManagerImpl::_OnPlatformEvent(const ChipDeviceEvent * event)
...
+                                PacketBufferHandle::Adopt(event->CHIPoBLEWriteReceived.Data));
+        }
         break;
 
     case DeviceEventType::kCHIPoBLEIndicateConfirm:
         HandleIndicationConfirmation(event->CHIPoBLEIndicateConfirm.ConId, &CHIP_BLE_SVC_ID, &ChipUUID_CHIPoBLEChar_TX);
+#if !CHIP_DEVICE_CONFIG_SUPPORTS_CONCURRENT_CONNECTION
+        if (GetBleTerminating())
+        {
+            ChipLogProgress(DeviceLayer, "Non-concurrent mode BLE packet acknowledged. Sending CloseAllBLEConnections");
```
Comment (Damian-Nordic) [inline src/platform/Linux/BLEManagerImpl.cpp:241]: Isn't this assuming that one indication will be enough to transfer the entire ConnectNetworkResponse (no fragmentation)? Maybe this should rather be triggered somehow from inside `BLEEndpoint` code that checks if `(mBtpEngine.TxState() == BtpEngine::kState_Complete)`.

File: src/ble/BleLayer.cpp [hunk 2]
```diff
@@ -789,6 +790,18 @@ void BleLayer::OnConnectionError(void * appState, CHIP_ERROR err)
     layer->mBleTransport->OnBleConnectionError(err);
 }
 
+// BLE Flag to wait for packet transmission confirmation
+static bool BleTerminating = false;
```
Comment (Damian-Nordic) [inline src/ble/BleLayer.cpp:794]: Why using a global if `BleLayer` is a class that can have regular members? Also, how about a name such as `mTerminateOnPacketTxComplete` or something that better describes the behavior?

File: src/platform/Linux/BLEManagerImpl.cpp (hunk 1 above)
Comment (simonhmorris1) [reply src/platform/Linux/BLEManagerImpl.cpp]: Updated to use BTP.

File: src/ble/BleLayer.cpp (hunk 2 above)
Comment (simonhmorris1) [reply src/ble/BleLayer.cpp]: Changed to use regular member.

**Comment by adabreuti** [comment]
@simonhmorris1 Great catch and change, one note is that these changes aren't currently functional for a for a Thread based platform implementation, as there is no Thread based event to call HandleConcurrentConnectNetwork().
https://github.com/simonhmorris1/connectedhomeip/blob/master/src/app/clusters/network-commissioning/network-commissioning.cpp#L1066

 I'm wondering if it would be useful for other vendors if we added an additional API to the DeviceControlServer for Thread that would simply post a kThreadDeviceAvailable event for vendors to implement in their respective BLEManager's since this is currently in a shared file.

This would allow for non-concurrent operation on Thread following a similar path as to what you have implemented for Wi-Fi.
https://github.com/simonhmorris1/connectedhomeip/blob/master/src/platform/DeviceControlServer.cpp#L83

Let me know your thoughts.

**Comment by simonhmorris1** [comment]
> @simonhmorris1 Great catch and change, one note is that these changes aren't currently functional for a for a Thread based platform implementation, as there is no Thread based event to call HandleConcurrentConnectNetwork(). https://github.com/simonhmorris1/connectedhomeip/blob/master/src/app/clusters/network-commissioning/network-commissioning.cpp#L1066
> 
> I'm wondering if it would be useful for other vendors if we added an additional API to the DeviceControlServer for Thread that would simply post a kThreadDeviceAvailable event for vendors to implement in their respective BLEManager's since this is currently in a shared file.
> 
> This would allow for non-concurrent operation on Thread following a similar path as to what you have implemented for Wi-Fi. https://github.com/simonhmorris1/connectedhomeip/blob/master/src/platform/DeviceControlServer.cpp#L83
> 
> Let me know your thoughts.



> @simonhmorris1 Great catch and change, one note is that these changes aren't currently functional for a for a Thread based platform implementation, as there is no Thread based event to call HandleConcurrentConnectNetwork(). https://github.com/simonhmorris1/connectedhomeip/blob/master/src/app/clusters/network-commissioning/network-commissioning.cpp#L1066
> 
> I'm wondering if it would be useful for other vendors if we added an additional API to the DeviceControlServer for Thread that would simply post a kThreadDeviceAvailable event for vendors to implement in their respective BLEManager's since this is currently in a shared file.
> 
> This would allow for non-concurrent operation on Thread following a similar path as to what you have implemented for Wi-Fi. https://github.com/simonhmorris1/connectedhomeip/blob/master/src/platform/DeviceControlServer.cpp#L83
> 
> Let me know your thoughts.

Yep I'll take a look at making that change.

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 3]
```diff
@@ -135,6 +135,24 @@ void Instance::Shutdown()
     mpBaseDriver->Shutdown();
 }
 
+#if !CHIP_DEVICE_CONFIG_SUPPORTS_CONCURRENT_CONNECTION
```
Comment (bzbarsky-apple) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:138]: Is CHIP_DEVICE_CONFIG_SUPPORTS_CONCURRENT_CONNECTION defined for devices that don't do BLE at all?  I guess probably....

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 4]
```diff
@@ -135,6 +135,24 @@ void Instance::Shutdown()
...
+void Instance::SendNonConcurrentConnectNetworkResponse()
+{
+    auto commandHandleRef = std::move(mAsyncCommandHandle);
+    auto commandHandle    = commandHandleRef.Get();
+    if (commandHandle == nullptr)
+    {
+        return;
+    }
+
+    chip::DeviceLayer::ConnectivityMgr().GetBleLayer()->mTerminateOnPacketTxComplete = true;
```
Comment (bzbarsky-apple) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:148]:
```suggestion
    DeviceLayer::ConnectivityMgr().GetBleLayer()->mTerminateOnPacketTxComplete = true;
```
This is all inside `namespace chip`.

Comment (bzbarsky-apple) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:148]: Please include the right headers for these bits.

File: src/controller/CHIPDeviceController.cpp [hunk 5]
```diff
@@ -3062,28 +3041,9 @@ void DeviceCommissioner::PerformCommissioningStep(DeviceProxy * proxy, Commissio
...
-            err = SendCommand(proxy, request, NonConcurrentNetworkResponse, NonConcurrentTimeout, endpoint, NullOptional);
-            if (err == CHIP_NO_ERROR)
-            {
-                // As there will be no ConnectNetworkResponse, it is an implicit kSuccess so a default report is fine
-                CommissioningDelegate::CommissioningReport report;
-                CommissioningStageComplete(CHIP_NO_ERROR, report);
-                return;
-            }
-        }
+                        params.GetSupportsConcurrentConnection().Value());
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:3045]: So now we are reading the "supports concurrent connection" bit just so we can log it here?

File: src/platform/Linux/BLEManagerImpl.cpp
Comment (bzbarsky-apple) [inline src/platform/Linux/BLEManagerImpl.cpp:1]: Other platforms need similar fixes, right?  Presumably tracked in some set of issues?

File: src/app/clusters/network-commissioning/network-commissioning.cpp (hunk 3 above)
Comment (simonhmorris1) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:138]: Yes, the default is is defined in src/include/platform/CHIPDeviceConfig.h

File: src/ble/BleApplicationDelegate.h [hunk 6]
```diff
@@ -42,6 +42,10 @@ class DLL_EXPORT BleApplicationDelegate
     // The application can use this callback to e.g. close the underlying BLE connection if it is no longer needed,
     // decrement the connection's refcount if it has one, or perform any other sort of cleanup as desired.
     virtual void NotifyChipConnectionClosed(BLE_CONNECTION_OBJECT connObj) = 0;
+
+    // Called to determine whether the BLE connection should be closed when in Non-concurrent mode if sending
+    // ConnectNetworkResponse. The BTP will be in kState_Complete o all fragments have been sent.
```
[the remark this answers is not in the document]
Comment (simonhmorris1) [reply src/ble/BleApplicationDelegate.h]: Done.

File: src/ble/BleLayer.h [hunk 7]
```diff
@@ -233,6 +233,9 @@ class DLL_EXPORT BleLayer
     void * mAppState                 = nullptr;
     BleLayerDelegate * mBleTransport = nullptr;
 
+    // Set in Non-concurrent mode when the ConnectNetworkResponse has been requested
+    bool mTerminateOnPacketTxComplete = false;
```
[the remark this answers is not in the document]
Comment (simonhmorris1) [reply src/ble/BleLayer.h]: Now use mState instead of mTerminateOnPacketTxComplete.

**Review by swan-amazon — APPROVED** [review]

File: src/app/clusters/network-commissioning/network-commissioning.cpp (hunk 4 above)
Comment (simonhmorris1) [reply src/app/clusters/network-commissioning/network-commissioning.cpp]: Done.

Comment (simonhmorris1) [reply src/app/clusters/network-commissioning/network-commissioning.cpp]: Added `#include <platform/ConnectivityManager.h>`

File: src/controller/CHIPDeviceController.cpp (hunk 5 above)
Comment (simonhmorris1) [reply src/controller/CHIPDeviceController.cpp:3045]: Yes, with the change to always send ConnectNetworkResponse(Success) on BLE prior to closing the commissioning channel and starting the operational channel. However I can see additional optimisation that could be done by the controller if knowing that this is a non-concurrent device.

File: src/platform/Linux/BLEManagerImpl.cpp
Comment (simonhmorris1) [reply src/platform/Linux/BLEManagerImpl.cpp:1]: If other platforms want to support Non-Concurrent mode then yes similar changes would be needed, however they would only use non-concurrent mode if the platform does not support concurrent mode. I have used the Raspberry Pi as the example as that is used in QA and certification testing, so it can now do either. I don't think any tickets need raising on the other platforms as they all support concurrent mode. New platforms that do not support Concurrent mode will need these changes.

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 8]
```diff
@@ -135,6 +136,24 @@ void Instance::Shutdown()
...
+void Instance::SendNonConcurrentConnectNetworkResponse()
+{
+    auto commandHandleRef = std::move(mAsyncCommandHandle);
+    auto commandHandle    = commandHandleRef.Get();
+    if (commandHandle == nullptr)
+    {
+        return;
+    }
+
+    DeviceLayer::ConnectivityMgr().GetBleLayer()->mState = Ble::BleLayer::kState_Disconnecting;
```
Comment (tcarmelveilleux) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:149]: Why are we directly touching BLE here? We should NOT be touching internal state of BLE layer from this place, and at the very least, if done, it should not be via member fields.

Comment (tcarmelveilleux) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:149]: This needs to be conditional on CONFIG_NETWORK_LAYER_BLE

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 9]
```diff
@@ -177,12 +196,7 @@ void Instance::InvokeCommand(HandlerContext & ctxt)
 
     case Commands::ConnectNetwork::Id: {
         VerifyOrReturn(mFeatureFlags.Has(Feature::kWiFiNetworkInterface) || mFeatureFlags.Has(Feature::kThreadNetworkInterface));
-#if CONFIG_NETWORK_LAYER_BLE && !CHIP_DEVICE_CONFIG_SUPPORTS_CONCURRENT_CONNECTION
-        // If commissionee does not support Concurrent Connections, request the BLE to be stopped.
-        // Start the ConnectNetwork, but this will not complete until the BLE is off.
-        ChipLogProgress(NetworkProvisioning, "Closing BLE connections due to non-concurrent mode");
-        DeviceLayer::DeviceControlServer::DeviceControlSvr().PostCloseAllBLEConnectionsToOperationalNetworkEvent();
```
Comment (tcarmelveilleux) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:184]: Can this leave some existing devices in a bad state?

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 10]
```diff
@@ -826,13 +844,19 @@ void Instance::HandleQueryIdentity(HandlerContext & ctx, const Commands::QueryId
 void Instance::OnResult(Status commissioningError, CharSpan debugText, int32_t interfaceStatus)
 {
     auto commandHandleRef = std::move(mAsyncCommandHandle);
-    auto commandHandle    = commandHandleRef.Get();
+
+    // In Non-concurrent mode the commandHandle will be null here, the ConnectNetworkResponse
+    // has already been sent and the BLE will have been stopped, however the other functionality
+    // is still required
+#if CHIP_DEVICE_CONFIG_SUPPORTS_CONCURRENT_CONNECTION
+    auto commandHandle = commandHandleRef.Get();
```
Comment (tcarmelveilleux) [inline src/app/clusters/network-commissioning/network-commissioning.cpp:852]: What happens to the lifecycle of the commandHandleRef in this case?

File: src/app/clusters/network-commissioning/network-commissioning.h [hunk 11]
```diff
@@ -48,6 +48,10 @@ class Instance : public CommandHandlerInterface,
     CHIP_ERROR Init();
     void Shutdown();
 
+#if !CHIP_DEVICE_CONFIG_SUPPORTS_CONCURRENT_CONNECTION
+    void SendNonConcurrentConnectNetworkResponse();
```
Comment (tcarmelveilleux) [inline src/app/clusters/network-commissioning/network-commissioning.h:52]: Why is this public?

File: src/app/server/CommissioningWindowManager.cpp [hunk 12]
```diff
@@ -89,8 +89,8 @@ void CommissioningWindowManager::OnPlatformEvent(const DeviceLayer::ChipDeviceEv
 #if CONFIG_NETWORK_LAYER_BLE
     else if (event->Type == DeviceLayer::DeviceEventType::kCloseAllBleConnections)
     {
-        ChipLogProgress(AppServer, "Received kCloseAllBleConnections");
-        mServer->GetBleLayerObject()->CloseAllBleConnections();
+        ChipLogProgress(AppServer, "Received kCloseAllBleConnections:%d", event->Type);
```
Comment (tcarmelveilleux) [inline src/app/server/CommissioningWindowManager.cpp:92]: Please `static_cast<int>(event->Type)`

File: src/app/server/CommissioningWindowManager.cpp [hunk 13]
```diff
@@ -89,8 +89,8 @@ void CommissioningWindowManager::OnPlatformEvent(const DeviceLayer::ChipDeviceEv
...
+        mServer->GetBleLayerObject()->Shutdown();
```
Comment (tcarmelveilleux) [inline src/app/server/CommissioningWindowManager.cpp:93]: Shutdown != to CloseAllBleConnections. How widely was this change tested? It impacts all BLE users.

File: src/include/platform/CHIPDeviceEvent.h [hunk 14]
```diff
@@ -171,7 +171,7 @@ enum PublicEventTypes
      * When supportsConcurrentConnection = False, the ConnectNetwork command cannot start until
      * the BLE device is closed and the WiFi device has been started.
      */
-    kWiFiDeviceAvailable,
+    kOperationalNetworkStarted,
```
Comment (tcarmelveilleux) [inline src/include/platform/CHIPDeviceEvent.h:174]: This is a change of public API. Changing this may break platforms. This was the wrong name, but the old name must be maintained, and kWiFiDeviceAvailable should just steer to the same place as kOperationalNetworkStarted.

File: src/platform/Linux/BLEManagerImpl.cpp [hunk 15]
```diff
@@ -222,8 +226,18 @@ void BLEManagerImpl::_OnPlatformEvent(const ChipDeviceEvent * event)
...
-        HandleWriteReceived(event->CHIPoBLEWriteReceived.ConId, &CHIP_BLE_SVC_ID, &ChipUUID_CHIPoBLEChar_RX,
-                            PacketBufferHandle::Adopt(event->CHIPoBLEWriteReceived.Data));
+#if !CHIP_DEVICE_CONFIG_SUPPORTS_CONCURRENT_CONNECTION
+        // If BLE is being stopped, ignore any write messages
+        if (mState != kState_Initialized)
+        {
+            ChipLogProgress(DeviceLayer, "Non-concurrent mode BLE stopped, BLE write ignored");
+        }
+        else
+#endif
```
Comment (tcarmelveilleux) [inline src/platform/Linux/BLEManagerImpl.cpp:236]: It's really not clear why this is being done. Please document more detauks about how we could get here. Why is it specific to non-concurrent? This seems like always an error that could be an early return that is not conditional to the `#if !CHIP_DEVICE_CONFIG_SUPPORTS_CONCURRENT_CONNECTION`

**Review by tcarmelveilleux — CHANGES_REQUESTED** [review]
- [ ] Return all existing public API and layer new features in addition to old names, even if they go to the same place
- [ ] Refactor direct access to `DeviceLayer::ConnectivityMgr().GetBleLayer()->mState`
- [ ] This seems risky/brittle given the breadth of changes. Please add an integration test that does not rely on multiple manual tests people have to keep running to prove the functioning of this feature.
- [ ] Make BLEManagerImpl.cpp error handling non-build-conditional wherever they apply uniformly
- [ ] Justify the move to `mServer->GetBleLayerObject()->Shutdown();` and how it is possible to guarantee that after a mid-commissioning failure, the window could still be open for the remainder of the time, to allow more BLE connections to support finishing the commissioning without reboot of the device.

File: src/app/clusters/network-commissioning/network-commissioning.cpp (hunk 3 above)
Comment (bzbarsky-apple) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:139]: No, what I meant is: is it going to be true for non-BLE devices?  But I am guessing yes.

**Review by bzbarsky-apple — APPROVED** [review]
Approving, assuming @tcarmelveilleux's issues are addressed.

File: src/app/clusters/network-commissioning/network-commissioning.cpp (hunk 8 above)
Comment (simonhmorris1) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:150]: Done

File: src/app/clusters/network-commissioning/network-commissioning.cpp (hunk 9 above)
Comment (simonhmorris1) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:184]: I do not think so, the CloseAllBleConnections is now done on the confirmation that the BTP packet containing the ConnectNetworkResponse(Success) has been sent.

File: src/app/clusters/network-commissioning/network-commissioning.cpp (hunk 10 above)
Comment (simonhmorris1) [reply src/app/clusters/network-commissioning/network-commissioning.cpp:854]: The commandHandleRef is completed when the NetworkConnectResponse(Success) is sent in SendNonConcurrentConnectNetworkResponse() prior to getting here.

File: src/app/clusters/network-commissioning/network-commissioning.cpp [hunk 16]
```diff
@@ -826,13 +844,19 @@ void Instance::HandleQueryIdentity(HandlerContext & ctx, const Commands::QueryId
...
     if (commandHandle == nullptr)
     {
         // When the platform shutted down, interaction model engine will invalidate all commandHandle to avoid dangling references.
         // We may receive the callback after it and should make it noop.
         return;
     }
+#endif
```
[the remark this answers is not in the document]
Comment (simonhmorris1) [reply src/app/clusters/network-commissioning/network-commissioning.cpp]: Done

File: src/app/clusters/network-commissioning/network-commissioning.h (hunk 11 above)
Comment (simonhmorris1) [reply src/app/clusters/network-commissioning/network-commissioning.h]: Moved

File: src/app/server/CommissioningWindowManager.cpp (hunk 12 above)
Comment (simonhmorris1) [reply src/app/server/CommissioningWindowManager.cpp]: Done

File: src/app/server/CommissioningWindowManager.cpp (hunk 13 above)
Comment (simonhmorris1) [reply src/app/server/CommissioningWindowManager.cpp:93]: As we are in Non-concurrent mode, the BLE must be stopped for all BLE users. The BLE will be either powered off or just the use of the RF disabled. as we are commissioning I am not aware of any other BLE users at this time.

File: src/include/platform/CHIPDeviceEvent.h (hunk 14 above)
Comment (simonhmorris1) [reply src/include/platform/CHIPDeviceEvent.h:175]: Done, however as this was only added a few weeks ago after the 1.2 release, I do not think it has been used by anyone, so we may not need to do it.

File: src/include/platform/DeviceControlServer.h [hunk 17]
```diff
@@ -37,7 +37,7 @@ class DeviceControlServer final
     CHIP_ERROR SetRegulatoryConfig(uint8_t location, const CharSpan & countryCode);
     CHIP_ERROR PostConnectedToOperationalNetworkEvent(ByteSpan networkID);
     CHIP_ERROR PostCloseAllBLEConnectionsToOperationalNetworkEvent();
-    CHIP_ERROR PostWiFiDeviceAvailableNetworkEvent();
+    CHIP_ERROR PostOperationalNetworkStartedEvent();
```
[the remark this answers is not in the document]
Comment (simonhmorris1) [reply src/include/platform/DeviceControlServer.h:41]: Done, however I do not think this has been used by anyone, see other comment.

File: src/platform/Linux/BLEManagerImpl.cpp (hunk 15 above)
Comment (simonhmorris1) [reply src/platform/Linux/BLEManagerImpl.cpp]: BlueZ sends another message after the BLE has been stopped which was causing the Wi-Fi to be disconnected and reestablished slowing down commissioning. This is a good point, I have modified the system so that BlueZ is disconnected at the same time of the underlying BLE, negating the need for this. So removed.

**Comment by simonhmorris1** [comment]
> * [ ]  Return all existing public API and layer new features in addition to old names, even if they go to the same place
**Done**
> * [ ]  Refactor direct access to `DeviceLayer::ConnectivityMgr().GetBleLayer()->mState`
**Thinking on this one**
> * [ ]  This seems risky/brittle given the breadth of changes. Please add an integration test that does not rely on multiple manual tests people have to keep running to prove the functioning of this feature.
**Please could you point me at instructions of how to add/write integration tests. Could this be done under a different ticket?**
> * [ ]  Make BLEManagerImpl.cpp error handling non-build-conditional wherever they apply uniformly
**Done**
> * [ ]  Justify the move to `mServer->GetBleLayerObject()->Shutdown();` and how it is possible to guarantee that after a mid-commissioning failure, the window could still be open for the remainder of the time, to allow more BLE connections to support finishing the commissioning without reboot of the device.
**See comment about Shutdown in code review also,** 
In non-concurrent mode, the BLE could be powered off, to allow the WiFi to start, think of a scenario of a cut down BLE/Wi-Fi IoT chip in use with limited RAM so only one can be used at a time. Dealing with this is implementation dependent. The code here is a RPi example to ensure the spec signalling is in place. Getting BlueZ working well for production would require more work.

File: src/app/clusters/network-commissioning/network-commissioning.cpp (hunk 8 above)
Comment (simonhmorris1) [reply src/app/clusters/network-commissioning/network-commissioning.cpp]: I looked at sending an event to the Commissioning Manager which would call the BLE, but that has race conditions. The disconnecting state needs setting prior to the sending of the BTP packet containing the ConnectNetworkResponse(Success) but the event is queued at the same time AddResponse() is called. Which means there is the potential that the BTP packet completes prior to the event being handled. Therefore I have created a function which is now called to set the mState within the BLE layer rather than directly accessing the member field.

**Review by tcarmelveilleux — APPROVED** [review]

**Review by swan-amazon — APPROVED** [review]
