### PR TITLE
Fix for Bug #36731.

### LINKED ISSUE #36731: [BUG] Heap-Use-After-Free in TCPBase::CloseActiveConnections During Shutdown
### Reproduction steps

0. Build `chip-all-clusters-app` with AddressSanitizer (ASAN) enabled.
1. Open Terminal 1 and start the `chip-all-clusters-app`:
    
    ```bash
    $ ./chip-all-clusters-app
    ```
    
2. Open Terminal 2 and run the following commands in `chip-tool`:
    
    ```bash
    $ ./chip-tool interactive start
    $ pairing onnetwork-long 1 20202021 3840
    $ basicinformation read vendor-name 1 0 --allow-large-payload 1
    ```
    
3. After the TCP session is established, terminate `chip-all-clusters-app` in Terminal 1 with `Ctrl+C`.
4. Observe the ASAN output of chip-all-clusters-app indicating a heap-use-after-free issue.
[ASAN Log.txt](https://github.com/user-attachments/files/18017742/ASAN.Log.txt)

### Summary

A **heap-use-after-free (UAF)** issue occurs during the cleanup phase in the Matter protocol's TCP transport layer. When a `TCPEndPoint` object is deallocated, its reference remains in the `ActiveTCPConnectionState` object. This dangling pointer leads to undefined behavior when the TCP connection termination logic accesses the invalid memory.

### Analysis and Description

The root cause of this issue lies in the mismatch between the lifecycle management of `TCPEndPoint` objects and their references in `ActiveTCPConnectionState`. The following sequence of events explains the issue:

1. **Allocation and Initialization**:
    - A `TCPEndPoint` object is created and assigned to the `mEndPoint` member of an `ActiveTCPConnectionState` object during the TCP connection establishment process.
2. **Deallocation**:
    - During shutdown, the `HeapObjectPool` destructor deallocates all `TCPEndPoint` objects via `ReleaseAll()`. However, the `ActiveTCPConnectionState` objects retain dangling pointers to these deallocated `TCPEndPoint` objects.
    
    ```cpp
    HeapObjectPool::~HeapObjectPool()
    {
        ReleaseAll();
    }
    
    void ReleaseAll()
    {
        mObjects.ForEachNode(this, ReleaseObject);
    }
    
    ```
    
3. **Access to Freed Memory**:
    - When `TCPBase::CloseActiveConnections()` is called, it iterates over the `ActiveTCPConnectionState` array. The `mEndPoint` pointer in these objects is used to call the `Close()` method, resulting in a UAF error.
    
    ```cpp
    void TCPBase::CloseActiveConnections()
    {
        for (size_t i = 0; i < mActiveConnectionsSize; ++i)
        {
            ActiveTCPConnectionState * connection = &mActiveConnections[i];
            if (connection->InUse()) // mEndPoint is dangling
            {
                CloseConnectionInternal(connection, CHIP_NO_ERROR, SuppressCallback::kNo);
            }
        }
    }
    
    ```
    
4. **ASAN Error**:
    - The error occurs in the `TCPEndPoint::Close()` method when the code tries to clear the receive queue (`mRcvQueue`), as shown in the ASAN log:
    
    ```cpp
    void TCPEndPoint::Close()
    {
        mRcvQueue = nullptr; // Accesses freed memory
    }
    
    ```
    

### Proposed Solution

The following solutions are proposed to address this issue:

1. **Synchronize Lifecycles**:
    - Ensure that `TCPEndPoint` objects are not deallocated while `ActiveTCPConnectionState` references them.
2. **Use Smart Pointers**:
    - Replace raw pointers with smart pointers (e.g., `std::shared_ptr`) in `ActiveTCPConnectionState`. This would allow the object to manage the lifetime of the `TCPEndPoint` safely:
    
    ```cpp
    std::shared_ptr<Inet::TCPEndPoint> mEndPoint;
    ```
    
3. **Refactor Object Management**:
    - Decouple the lifecycle of `ActiveTCPConnectionState` from `TCPEndPoint` objects. Use proxy objects or implement weak references to manage the dependency.

By addressing this issue, the framework can prevent undefined behavior and potential security vulnerabilities. The proposed solutions not only resolve the immediate problem but also enhance the robustness and maintainability of the code.

If further information is needed, please do not hesitate to reach out.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

ffbc362200b60380114a3e136a44343c0de5e64d

### Platform

core

### Platform Version(s)

all versions with TCP support

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pidarped**
Add CloseActiveConnections() call in TCPBase::Close(), which is called as part of Server::Shutdown().
Active connections should be closed as part of Server shutdown. This allows the TCPConnectionState to also close the associated TCPEndpoint object as part of this shutdown flow.

Previously, the CloseActiveConnections() call was present in the TCPBase destructor alone.

Fixes https://github.com/project-chip/connectedhomeip/issues/36731

### CODE REVIEW

File: src/transport/raw/TCP.cpp [hunk 1]
```diff
@@ -125,6 +125,9 @@ void TCPBase::Close()
         mListenSocket->Free();
         mListenSocket = nullptr;
     }
+
+    CloseActiveConnections();
```
Comment (bzbarsky-apple) [inline src/transport/raw/TCP.cpp:129]: Seems like the destructor should call Close() instead of us copy/pasting everything between them?

**Review by bzbarsky-apple — APPROVED** [review]

**Review by yufengwangca — APPROVED** [review]
