### PR TITLE
DoorLock: Fix incorrect CredentialIndex on LockOperation events initated remotely (#24985)

### LINKED ISSUE #24985: [BUG] Doorlock: CredentialIndex in LockOperationEvent is incorrect for Remote operation
### Reproduction steps

1. Create 1 user with credential UserIndex == 44, and CredentialIndex == 55:
      chip-tool doorlock set-user 0 44 "Test45" 445 null 0 0 1 1 --timedInteractionTimeoutMs 1000
      chip-tool doorlock set-credential 0 '{ "credentialType" : 1 , "credentialIndex" : 55 }' 4455 44 null null 1 1 --timedInteractionTimeoutMs 1000

2. Operate lock via unlock-door command:
     chip-tool doorlock unlock-door 1 1 --PinCode 4455 --timedInteractionTimeoutMs 1000

3. Read LockOperation event:
     chip-tool doorlock read-event lock-operation 1 1

4. Note that 'CredentialIndex' in event is incorrect (reads as '44' but should be '55'):
```
[1676055173.372648][293882:293887] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0101 Event 0x0000_0002
[1676055173.372704][293882:293887] CHIP:TOO:   Event number: 1179651
[1676055173.372742][293882:293887] CHIP:TOO:   Priority: Critical
[1676055173.372784][293882:293887] CHIP:TOO:   Timestamp: 16537
[1676055173.372863][293882:293887] CHIP:TOO:   LockOperation: {
[1676055173.372922][293882:293887] CHIP:TOO:     LockOperationType: 1
[1676055173.372974][293882:293887] CHIP:TOO:     OperationSource: 7
[1676055173.373030][293882:293887] CHIP:TOO:     UserIndex: 44
[1676055173.373076][293882:293887] CHIP:TOO:     FabricIndex: 1
[1676055173.373127][293882:293887] CHIP:TOO:     SourceNode: 112233
[1676055173.373183][293882:293887] CHIP:TOO:     Credentials: 1 entries
[1676055173.373283][293882:293887] CHIP:TOO:       [1]: {
[1676055173.373339][293882:293887] CHIP:TOO:         CredentialType: 1
[1676055173.373391][293882:293887] CHIP:TOO:         CredentialIndex: 44
[1676055173.373440][293882:293887] CHIP:TOO:        }
[1676055173.373493][293882:293887] CHIP:TOO:    }
```

### Bug prevalence

Consistent

### GitHub hash of the SDK that was being used

5ad70f62394b1b52123014eb7ad0c389aa63652c

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jrhees-cae**
LockOperation events produced in response to a Lock or Unlock operation initiated via Matter (Remote) include the incorrect credentialIndex in the events.

Fixes #24985

### CODE REVIEW

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 1]
```diff
@@ -1743,7 +1743,7 @@ bool DoorLockServer::findUserIndexByCredential(chip::EndpointId endpointId, Cred
             if (credentialInfo.credentialData.data_equal(credentialData))
             {
                 userIndex       = i;
-                credentialIndex = i;
+                credentialIndex = credential.CredentialIndex;
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:1746]: Nice catch, but can we please add a YAML test for this?

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 1 above)
Comment (jrhees-cae) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:1746]: YAML test has been updated.

**Review by yufengwangca — APPROVED** [review]

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:1746]: No, it hasn't.  What was updated was:

1. One of the certification tests.  Those should not get updated without corresponding test plan changes.
2. Not one of the tests that actually runs anything automated.  What should have been done is either updating src/app/tests/suites/DL_UsersAndCredentials.yaml or adding a new test.

Comment (bzbarsky-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:1746]: Filed https://github.com/project-chip/connectedhomeip/issues/24992 to track this....
