### PR TITLE
Make platform PlatformManager::PostEvent() return status

### LINKED ISSUE #9543: PacketBuffer leak
#### Problem

In `IPEndPointBasis::PostPacketBufferEvent()` for LwIP we have:
```
const CHIP_ERROR error = aLayer->PostEvent(aTarget, aEventType, (uintptr_t) System::LwIPPacketBufferView::UnsafeGetLwIPpbuf(aBuffer));
if (error == CHIP_NO_ERROR)
{
    // If PostEvent() succeeded, it has ownership of the buffer, so we need to release it (without freeing it).
    static_cast<void>(std::move(aBuffer).UnsafeRelease());
}
```

However, `PostEvent()` does:
```
PlatformMgr().PostEvent(&event);
return CHIP_NO_ERROR;
```
because platform `_PostEvent()` returns `void`.

So, if the platform actually fails to deliver the event, that is not reported, and the packet buffer leaks. 

#### Proposed Solution

Return and propagate status from platform  `_PostEvent()`.

### PR DESCRIPTION
**Pull request by kpschoedel**
#### Problem

`void PlatformManager::PostEvent()` can fail on some platforms, but does
not report this to callers.

In the #9543 case, an intermediate layer unconditionally returned
`CHIP_NO_ERROR`, and `Inet` code assumed it could actually test whether
`PostEvent()` succeeded.

Fixes #9543 _PacketBuffer leak_

#### Change overview

Made `PlatformManager::PostEvent()` return `CHIP_ERROR`.
Marked it `[[nodiscard]]` to catch all uses, and made callers
propagate or at least log any error.

#### Testing

CI.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

File: src/include/platform/internal/GenericConfigurationManagerImpl.cpp [hunk 1]
```diff
@@ -794,7 +794,7 @@ CHIP_ERROR GenericConfigurationManagerImpl<ImplClass>::_ClearServiceProvisioning
         ChipDeviceEvent event;
         event.Type                                   = DeviceEventType::kAccountPairingChange;
         event.AccountPairingChange.IsPairedToAccount = false;
-        PlatformMgr().PostEvent(&event);
+        ReturnErrorOnFailure(PlatformMgr().PostEvent(&event));
```
Comment (bzbarsky-apple) [inline src/include/platform/internal/GenericConfigurationManagerImpl.cpp:797]: If we take this early return, we have done the `ClearConfigValue` calls above but not the `mFlags.Clear` calls below.  Is that an OK state to be in?  Or do we make assumptions based on `mFlags` about the config value bits?

At the very least could use documentation.  Same for the other early return here.

File: src/platform/DeviceControlServer.cpp [hunk 2]
```diff
@@ -68,7 +72,7 @@ CHIP_ERROR DeviceControlServer::CommissioningComplete()
     ChipDeviceEvent event;
     event.Type                         = DeviceEventType::kCommissioningComplete;
     event.CommissioningComplete.status = CHIP_NO_ERROR;
-    PlatformMgr().PostEvent(&event);
+    ReturnErrorOnFailure(PlatformMgr().PostEvent(&event));
     return CHIP_NO_ERROR;
```
Comment (bzbarsky-apple) [inline src/platform/DeviceControlServer.cpp:76]:
```suggestion
    return PlatformMgr().PostEvent(&event);
```

File: src/platform/ESP32/ConnectivityManagerImpl.cpp [hunk 3]
```diff
@@ -667,7 +667,7 @@ void ConnectivityManagerImpl::OnStationConnected()
     ChipDeviceEvent event;
     event.Type                          = DeviceEventType::kWiFiConnectivityChange;
     event.WiFiConnectivityChange.Result = kConnectivity_Established;
-    PlatformMgr().PostEvent(&event);
+    PlatformMgr().PostEventLoggingErrors(&event);
 
     UpdateInternetConnectivityState();
```
Comment (bzbarsky-apple) [inline src/platform/ESP32/ConnectivityManagerImpl.cpp:672]: Should this update happen even if the notification could not be posted?  Maybe file a followup to sort this out?  Similar for other things in this file.  I guess the existing error-handling here is pretty questionable....

File: src/platform/Linux/ConnectivityManagerImpl.cpp [hunk 4]
```diff
@@ -941,7 +941,7 @@ CHIP_ERROR ConnectivityManagerImpl::ProvisionWiFiNetwork(const char * ssid, cons
                         ChipLogDetail(DeviceLayer, "Got IP address on interface: %s IP: %s", ifName,
                                       event.InternetConnectivityChange.address);
 
-                        PlatformMgr().PostEvent(&event);
+                        ReturnErrorOnFailure(PlatformMgr().PostEvent(&event));
```
Comment (bzbarsky-apple) [inline src/platform/Linux/ConnectivityManagerImpl.cpp:944]: This is a slightly odd thing to do in a function with an `exit:` cleanup block.  I guess we know `err` is null here?  Still seems a bit odd.

In particular, it's not clear to me why skipping the dhclient bits if this PostEvent fails is better than just setting `ret` to a failure here and moving forward.....  especially given the comment after those dhclient bits, which claims this function should returns succcess even if some bits inside it fail.

File: src/platform/Linux/ThreadStackManagerImpl.cpp [hunk 5]
```diff
@@ -212,7 +220,7 @@ CHIP_ERROR ThreadStackManagerImpl::_SetThreadProvision(ByteSpan netInfo)
     ChipDeviceEvent event;
     event.Type                                           = DeviceEventType::kServiceProvisioningChange;
     event.ServiceProvisioningChange.IsServiceProvisioned = true;
-    PlatformMgr().PostEvent(&event);
+    ReturnErrorOnFailure(PlatformMgr().PostEvent(&event));
 
     return CHIP_NO_ERROR;
```
Comment (bzbarsky-apple) [inline src/platform/Linux/ThreadStackManagerImpl.cpp:225]:
```suggestion
    return PlatformMgr().PostEvent(&event);
```

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 6]
```diff
@@ -245,7 +249,7 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::_SetThreadProvis
     ChipDeviceEvent event;
     event.Type                                           = DeviceEventType::kServiceProvisioningChange;
     event.ServiceProvisioningChange.IsServiceProvisioned = true;
-    PlatformMgr().PostEvent(&event);
+    ReturnErrorOnFailure(PlatformMgr().PostEvent(&event));
 
     return MapOpenThreadError(otErr);
```
Comment (bzbarsky-apple) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:254]: If otErr is a failure _and_ we fail to post the event (which seems like an odd thing to be doing if otErr is a failure!), which error should we return?

My gut feeling is that we should only try to post the event if otErr is success.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/include/platform/internal/GenericConfigurationManagerImpl.cpp (hunk 1 above)
Comment (kpschoedel) [reply src/include/platform/internal/GenericConfigurationManagerImpl.cpp:797]: Will change to continue and return an error at the end, and add to the existing TODO comment.

File: src/platform/DeviceControlServer.cpp (hunk 2 above)
Comment (kpschoedel) [reply src/platform/DeviceControlServer.cpp:76]: Will do.

File: src/include/platform/PlatformManager.h [hunk 7]
```diff
@@ -354,9 +355,19 @@ inline void PlatformManager::UnlockChipStack()
...
 }
 
-inline void PlatformManager::PostEvent(const ChipDeviceEvent * event)
+inline CHIP_ERROR PlatformManager::PostEvent(const ChipDeviceEvent * event)
 {
-    static_cast<ImplClass *>(this)->_PostEvent(event);
+    return static_cast<ImplClass *>(this)->_PostEvent(event);
+}
+
+inline CHIP_ERROR PlatformManager::PostEventLoggingErrors(const ChipDeviceEvent * event)
```
Comment (mrjerryjohns) [inline src/include/platform/PlatformManager.h:363]: Why have two versions of this call, when the logging of the error could just be wrapped in a define? Do you really mean to have callers decide between the two? Think it would be more natural to just have logging of this be controlled through a global define.

File: src/include/platform/PlatformManager.h [hunk 8]
```diff
@@ -354,9 +355,19 @@ inline void PlatformManager::UnlockChipStack()
     static_cast<ImplClass *>(this)->_UnlockChipStack();
 }
 
-inline void PlatformManager::PostEvent(const ChipDeviceEvent * event)
+inline CHIP_ERROR PlatformManager::PostEvent(const ChipDeviceEvent * event)
```
Comment (mrjerryjohns) [inline src/include/platform/PlatformManager.h:358]: I'd consider the inability to post an event a fairly egregious fault in the system, since there is very little recovery you can do from that situation that doesn't break functionality that was dependent on posting this. Historically on embedded platforms, we'd assert() in that situation so that it's more immediately discoverable and actionable, so that we can actually perhaps alter the size of the event queue, or debug why it become full.

Just emitting a log line feels like it doesn't raise attention enough to this issue.

Comment (kpschoedel) [reply src/include/platform/PlatformManager.h:358]: > I'd consider the inability to post an event a fairly egregious fault in the system, since there is very little recovery you can do from that situation that doesn't break functionality that was dependent on posting this.

That's often true, but the case from #9543 is one where it really is good to accept  event-posting failure. Otherwise it becomes trivial to knock out a device with a UDP flood, _or_ there needs to be some other mechanism to prevent that (e.g. have fewer packet buffers than event slots, which practically speaking integrators will not get consistently right).

> Historically on embedded platforms, we'd assert() in that situation so that it's more immediately discoverable and actionable, so that we can actually perhaps alter the size of the event queue, or debug why it become full.

It's always been possible for platforms' `_PostEvent()` to abort on failure — but none of them do, which suggests that leaving it entirely up to platform implementors doesn't work.

> Just emitting a log line feels like it doesn't raise attention enough to this issue.

How about `PostEventOrDie` instead of `PostEventLoggingErrors`?

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@kpschoedel ?

**Comment by andy31415** [comment]
> @kpschoedel ?

Kevin is OOO for another 2 weeks. @mrjerryjohns - should your comments be addressed by code changes in this PR or are you ok to merge and change as a followup to expedite changes going in?

**Review by mrjerryjohns — APPROVED** [review]
With the latest changes to now clearly provide a method that dies if it fails, vs a method that doesn't, Kevin's addressed my concerns.
