### PR TITLE
submodule: bump third_party/openthread/repo from `130afd9` to `f4c2233`

### LINKED ISSUE #7742: OTBR cannot parse large SRP update due to fragmentation
**Describe the bug**
SRP server on the OTBR fails to parse an SRP update that is too large to fit in a single IPv6 packet. In such a case the datagram is fragmented and the SRP server tries to process the first fragment alone which results in the following error:
```
May 23 11:49:09 b22caefa12ee otbr-agent[210]: 01:54:23.728 [W] SrpServer-----: Failed to process Service Discovery instructions: Parse
May 23 11:49:09 b22caefa12ee otbr-agent[210]: 01:54:23.728 [W] SrpServer-----: Failed to process DNS Update section: Parse
```
I checked that the failing line of code is:
```c
SuccessOrExit(error = aMessage.Read(signatureOffset, signature));
```
Root cause: `signatureOffset` is greater than the payload length.

I'm filing an issue here instead of in the OTBR repo as I'm not sure if an SRP client should create such big updates at all or maybe they should be split into smaller ones.

**To Reproduce**

1. Run OTBR (OTBR SHA: bb3c1e) and form a network.
2. Build OpenThread CLI for nRF 52840 DK (OpenThread SHA: 130afd9) with `OPENTHREAD_CONFIG_SRP_CLIENT_BUFFERS_MAX_SERVICES` changed to 6.
3. Run the following commands on the CLI:
```
ifconfig up
dataset set active <otbr-dataset>
thread start
srp client autostart enable
srp client service add 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde _matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6 12345 0 0 364b45593d7478743174787431747874317478743174787431747874317478743174787431747874317478743174787431747874317478
srp client service add 1123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde _matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6 12345 0 0 364b45593d7478743274787432747874327478743274787432747874327478743274787432747874327478743274787432747874327478
srp client service add 2123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde _matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6 12345 0 0 364b45593d7478743374787433747874337478743374787433747874337478743374787433747874337478743374787433747874337478
srp client service add 3123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde _matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6 12345 0 0 364b45593d7478743474787434747874347478743474787434747874347478743474787434747874347478743474787434747874347478
srp client host name hosthosthosthosthosthosthosthosthosthosthosthosthosthosthosthos
srp client host address fd11:22:0:0:a295:b6e6:a120:c3c
```
4. Observe that the services are never registered:
```
$ srp client service
instance:"3123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde", name:"_matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6", state:Adding, port:12345, priority:0, weight:0
instance:"2123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde", name:"_matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6", state:Adding, port:12345, priority:0, weight:0
instance:"1123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde", name:"_matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6", state:Adding, port:12345, priority:0, weight:0
instance:"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde", name:"_matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6", state:Adding, port:12345, priority:0, weight:0
```

**Expected behavior**
Successful registration of the services.

**Console/log output**
Already provided above.

**Additional context**
Building OTBR with `OT_IP6_FRAGM` enabled solves the issue, because then the fragmented datagram is reassembled on the OTBR side.

### PR DESCRIPTION
**Pull request by jwhui**
#### Problem
* Fixes https://github.com/openthread/openthread/issues/7742

#### Change overview
* Update openthread hash to include recent fixes
* https://github.com/openthread/openthread/pull/7776
* Using `mPendingTimestamp` as the active timestamp is a bug that is also fixed by this PR.

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by mspang — APPROVED** [review]

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 1]
```diff
@@ -1492,8 +1492,13 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::_WriteThreadNetw
...
             otError otErr = otDatasetGetActive(mOTInst, &activeDataset);
             VerifyOrExit(otErr == OT_ERROR_NONE, err = MapOpenThreadError(otErr));
-            uint64_t activeTimestamp = activeDataset.mPendingTimestamp;
-            err                      = encoder.Encode(activeTimestamp);
+#if OPENTHERAD_API_VERSION >= 219
+            uint64_t activeTimestamp = (activeDataset.mActiveTimestamp.mSeconds << 16) |
+                (activeDataset.mActiveTimestamp.mTicks << 1) | activeDataset.mActiveTimestamp.mAuthoritative;
+#else
+            uint64_t activeTimestamp = activeDataset.mActiveTimestamp;
+#endif
```
Comment (msandstedt) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:1500]: Given that we have openthread as a submodule in the tree, do we need this backward compatibility?  I'm not finding other examples of #ifdef on the openthread API version in the tree.

Comment (jwhui) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:1500]: I was thinking the same, but it appears there are other pinned versions of OpenThread around. Specifically, I ran into this build failure on TELINK: https://github.com/project-chip/connectedhomeip/runs/7045847972?check_suite_focus=true

Comment (jwhui) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:1500]: Other examples of `OPENTHEAD_API_VERSION`:
```bash
$ git grep OPENTHREAD_API_VERSION
examples/common/pigweed/rpc_services/OtCli.h:static_assert(OPENTHREAD_API_VERSION >= 85, "Invalid Open Thread version");
examples/shell/shell_common/cmd_otcli.cpp:#if OPENTHREAD_API_VERSION >= 85
examples/shell/shell_common/cmd_otcli.cpp:#if OPENTHREAD_API_VERSION >= 85
examples/shell/shell_common/cmd_otcli.cpp:#if OPENTHREAD_API_VERSION >= 85
examples/shell/shell_common/cmd_otcli.cpp:#if OPENTHREAD_API_VERSION >= 85
examples/shell/shell_common/cmd_otcli.cpp:#endif // OPENTHREAD_API_VERSION >= 85
src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:static_assert(OPENTHREAD_API_VERSION >= 156, "SRP Client requires a more recent OpenThread version");
src/platform/OpenThread/OpenThreadUtils.cpp:#if OPENTHREAD_API_VERSION >= 126
src/platform/OpenThread/OpenThreadUtils.cpp:#if OPENTHREAD_API_VERSION >= 126
```

Comment (saurabhst) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:1500]: How is the API version mapped to Thread spec say 1.1 /1.2 /1.3 and so on

Comment (jwhui) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:1500]: OpenThread API version and Thread Protocol version are independent. The former tracks changes in OpenThread API, the latter tracks changes in Thread network protocol.

Comment (mspang) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:1500]: Yeah... openthread comes from platforms in some cases and upgrading it all at the same time would require a lot more coordination (not to mention delay the fix waiting for the update to roll up the dependency tree).

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 2]
```diff
@@ -1492,8 +1492,13 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::_WriteThreadNetw
             otOperationalDataset activeDataset;
             otError otErr = otDatasetGetActive(mOTInst, &activeDataset);
             VerifyOrExit(otErr == OT_ERROR_NONE, err = MapOpenThreadError(otErr));
-            uint64_t activeTimestamp = activeDataset.mPendingTimestamp;
-            err                      = encoder.Encode(activeTimestamp);
+#if OPENTHREAD_API_VERSION >= 219
+            uint64_t activeTimestamp = (activeDataset.mActiveTimestamp.mSeconds << 16) |
+                (activeDataset.mActiveTimestamp.mTicks << 1) | activeDataset.mActiveTimestamp.mAuthoritative;
```
Comment (bzbarsky-apple) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:1497]: Why?  The spec is not super-clear on what this attribute means, probably because it assumes the old API surface, but why would we be including mAuthoritative in there?

Comment (jwhui) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:1497]: Thread 1.1.1 Section 8.10.1.13 states:

> A 1-bit flag that indicates the time was obtained from an authoritative source: either NTP (Network Time Protocol), GPS (Global Positioning System), cell network, or other method. Note that the U bit is the least significant bit when the entire timestamp is represented as a single 64-bit number.

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 3]
```diff
@@ -1492,8 +1492,13 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::_WriteThreadNetw
             otOperationalDataset activeDataset;
             otError otErr = otDatasetGetActive(mOTInst, &activeDataset);
             VerifyOrExit(otErr == OT_ERROR_NONE, err = MapOpenThreadError(otErr));
-            uint64_t activeTimestamp = activeDataset.mPendingTimestamp;
```
Comment (jwhui) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:1495]: Using the `mPendingTimestamp` as the active timestamp is a bug.

**Review by bzbarsky-apple — APPROVED** [review]
