### PR TITLE
[Camera] Support camera session re-establishment without peforming reset

### LINKED ISSUE #40212: [BUG] Running multiple WebRTC TCs from TH UI together, results in camera-app crash
### Reproduction steps

This needs to be fixed because in cases where users runs multiple TCs from TH UI, a crash can occur in camera app. 

In TH version TH Version v2.14-beta1+fall2025, when we run multiple WEBRTC_1_X together, camera app crashes.

Simple way to reproduce in CLI.

```sh
# camera app
rm -rf /tmp/chip_*
./chip-camera-app

#camera controller
./chip-camera-controller
pairing onnetwork 1 20202021
webrtc connect 1 1
cameraavstreammanagement audio-stream-allocate 3 0 8 48000 20000 24 1 1
webrtc provide-offer 3 --audio-stream-id 1
webrtctransportprovider end-session 1 1 1 1  #End Session 
webrtc connect 1 1 # Start session restablishment
cameraavstreammanagement audio-stream-allocate 3 0 8 48000 20000 24 1 1
webrtc provide-offer 3 --audio-stream-id 1 #Crash in camera app
```

Crash bt
```
(gdb) bt
#0  0x00005555555cfd63 in chip::app::Clusters::WebRTCTransportProvider::WebRTCProviderManager::HandleProvideOffer (this=0x555555c90998 <gCameraDevice+216>, args=..., outSession=...)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp:229
#1  0x0000555555676e3f in chip::app::Clusters::WebRTCTransportProvider::WebRTCTransportProviderServer::HandleProvideOffer (this=0x555555fcc7a0, ctx=..., req=...)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/app/clusters/webrtc-transport-provider-server/webrtc-transport-provider-server.cpp:590
#2  0x0000555555677b86 in operator()<chip::app::Clusters::WebRTCTransportProvider::Commands::ProvideOffer::DecodableType> (__closure=0x7fffffffca58, subCtx=..., req=...)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/app/clusters/webrtc-transport-provider-server/webrtc-transport-provider-server.cpp:127
#3  0x0000555555677cf9 in chip::app::CommandHandlerInterface::HandleCommand<chip::app::Clusters::WebRTCTransportProvider::Commands::ProvideOffer::DecodableType, chip::app::Clusters::WebRTCTransportProvider::WebRTCTransportProviderServer::InvokeCommand(chip::app::CommandHandlerInterface::HandlerContext&)::<lambda(chip::app::CommandHandlerInterface::HandlerContext&, const auto:9&)> >(chip::app::CommandHandlerInterface::HandlerContext &, struct {...}) (this=0x555555fcc7b8, handlerContext=..., func=...)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/app/CommandHandlerInterface.h:265
#4  0x0000555555674d09 in chip::app::Clusters::WebRTCTransportProvider::WebRTCTransportProviderServer::InvokeCommand (this=0x555555fcc7a0, ctx=...)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/app/clusters/webrtc-transport-provider-server/webrtc-transport-provider-server.cpp:126
#5  0x00005555555f171c in chip::app::CodegenDataModelProvider::InvokeCommand
    (this=0x555555c8f100 <chip::app::CodegenDataModelProvider::Instance()::gCodegenModel>, request=..., input_arguments=..., handler=0x555555ed2970)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/data-model-providers/codegen/CodegenDataModelProvider.cpp:186
#6  0x0000555555992847 in chip::app::InteractionModelEngine::DispatchCommand (this=0x555555ca8e20 <chip::app::sInteractionModelEngine>, apCommandObj=..., aCommandPath=..., apPayload=...)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/app/InteractionModelEngine.cpp:1783
#7  0x00005555559cf773 in chip::app::CommandResponseSender::DispatchCommand (this=0x555555ed2940, apCommandObj=..., aCommandPath=..., apPayload=...)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/app/CommandResponseSender.cpp:132
#8  0x0000555555842f2b in chip::app::CommandHandlerImpl::ProcessCommandDataIB (this=0x555555ed2970, aCommandElement=...)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/app/CommandHandlerImpl.cpp:456
#9  0x00005555558422de in chip::app::CommandHandlerImpl::ProcessInvokeRequest (this=0x555555ed2970, payload=..., isTimedInvoke=false)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/app/CommandHandlerImpl.cpp:306
#10 0x0000555555840fbf in chip::app::CommandHandlerImpl::OnInvokeCommandRequest (this=0x555555ed2970, commandResponder=..., payload=..., isTimedInvoke=false)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/app/CommandHandlerImpl.cpp:127
#11 0x00005555559cfc3c in chip::app::CommandResponseSender::OnInvokeCommandRequest (this=0x555555ed2940, ec=0x5555560bc0f0, payload=..., isTimedInvoke=false)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/app/CommandResponseSender.cpp:217
#12 0x000055555598e454 in chip::app::InteractionModelEngine::OnInvokeCommandRequest
    (this=0x555555ca8e20 <chip::app::sInteractionModelEngine>, apExchangeContext=0x5555560bc0f0, aPayloadHeader=..., aPayload=..., aIsTimedInvoke=false)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/app/InteractionModelEngine.cpp:607
#13 0x000055555599075b in chip::app::InteractionModelEngine::OnMessageReceived
    (this=0x555555ca8e20 <chip::app::sInteractionModelEngine>, apExchangeContext=0x5555560bc0f0, aPayloadHeader=..., aPayload=...)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/app/InteractionModelEngine.cpp:1066
#14 0x00005555558a7fe9 in chip::Messaging::ExchangeContext::HandleMessage (this=0x5555560bc0f0, messageCounter=65314366, payloadHeader=..., msgFlags=..., msgBuf=...)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/messaging/ExchangeContext.cpp:617
#15 0x00005555558ab278 in chip::Messaging::ExchangeManager::OnMessageReceived
    (this=0x555555ca9ef8 <chip::Server::sServer+2168>, packetHeader=..., payloadHeader=..., session=..., isDuplicate=chip::SessionMessageDelegate::DuplicateMessage::No, msgBuf=...)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/messaging/ExchangeMgr.cpp:390
#16 0x00005555559404f4 in chip::SessionManager::SecureUnicastMessageDispatch
    (this=0x555555ca99b0 <chip::Server::sServer+816>, partialPacketHeader=..., peerAddress=..., msg=..., ctxt=0x7fffffffd878)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/transport/SessionManager.cpp:1026
#17 0x000055555593e552 in chip::SessionManager::OnMessageReceived (this=0x555555ca99b0 <chip::Server::sServer+816>, peerAddress=..., msg=..., ctxt=0x7fffffffd878)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/transport/SessionManager.cpp:652
#18 0x0000555555944c65 in chip::TransportMgrBase::HandleMessageReceived (this=0x555555ca9688 <chip::Server::sServer+8>, peerAddress=..., msg=..., ctxt=0x7fffffffd878)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/transport/TransportMgrBase.cpp:91
#19 0x0000555555a4f2b1 in chip::Transport::Base::HandleMessageReceived (this=0x555555ca96e0 <chip::Server::sServer+96>, source=..., buffer=..., ctxt=0x7fffffffd878)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/transport/raw/Base.h:137
#20 0x0000555555a51741 in chip::Transport::TCPBase::ProcessSingleMessage
    (this=0x555555ca96e0 <chip::Server::sServer+96>, peerAddress=..., state=0x555555ca9728 <chip::Server::sServer+168>, messageSize=678)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/transport/raw/TCP.cpp:393
#21 0x0000555555a51468 in chip::Transport::TCPBase::ProcessReceivedBuffer (this=0x555555ca96e0 <chip::Server::sServer+96>, endPoint=0x555555f975b0, peerAddress=..., buffer=...)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/transport/raw/TCP.cpp:354
#22 0x0000555555a51a8c in chip::Transport::TCPBase::HandleTCPEndPointDataReceived (endPoint=0x555555f975b0, buffer=...)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/transport/raw/TCP.cpp:454
#23 0x0000555555a60d13 in chip::Inet::TCPEndPoint::DriveReceiving (this=0x555555f975b0) at ../../examples/camera-app/linux/third_party/connectedhomeip/src/inet/TCPEndPoint.cpp:337
#24 0x00005555559e04fd in chip::Inet::TCPEndPointImplSockets::ReceiveData (this=0x555555f975b0)
--Type <RET> for more, q to quit, c to continue without paging--
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/inet/TCPEndPointImplSockets.cpp:973
#25 0x00005555559dff7d in chip::Inet::TCPEndPointImplSockets::HandlePendingIO (this=0x555555f975b0, events=...)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/inet/TCPEndPointImplSockets.cpp:835
#26 0x00005555559dfd74 in chip::Inet::TCPEndPointImplSockets::HandlePendingIO (events=..., data=93825002993072)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/inet/TCPEndPointImplSockets.cpp:777
#27 0x00005555559e6a67 in chip::System::LayerImplSelect::HandleEvents (this=0x555555ca4220 <chip::DeviceLayer::SystemLayerImpl()::gSystemLayerImpl>)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/system/SystemLayerImplSelect.cpp:618
#28 0x00005555558d4d40 in chip::DeviceLayer::Internal::GenericPlatformManagerImpl_POSIX<chip::DeviceLayer::PlatformManagerImpl>::_RunEventLoop
    (this=0x555555ca4e30 <chip::DeviceLayer::PlatformManagerImpl::sInstance+16>)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/include/platform/internal/GenericPlatformManagerImpl_POSIX.ipp:226
#29 0x0000555555685440 in chip::DeviceLayer::PlatformManager::RunEventLoop (this=0x555555ca4e20 <chip::DeviceLayer::PlatformManagerImpl::sInstance>)
    at ../../examples/camera-app/linux/third_party/connectedhomeip/src/include/platform/PlatformManager.h:409
#30 0x000055555568a25a in ChipLinuxAppMainLoop (impl=0x0) at ../../examples/camera-app/linux/third_party/connectedhomeip/examples/platform/linux/AppMain.cpp:1023
#31 0x00005555555ec53a in main (argc=1, argv=0x7fffffffe1c8) at ../../examples/camera-app/linux/main.cpp:57
(gdb)
```

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

9cc87022a97af43d1145d2a0469e2ce8e4452cd6

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chulspro**
This PR,
* Fixed https://github.com/project-chip/connectedhomeip/issues/40212
* Supports for multiple session re-establishment without necessary to reset camera-app
* Fixes stability issues when runing multiple WEBRTC_1_X tests together in TH
### Testing
Running multiple TC_WEBRTC_1_X tests together from Test Harness.

### CODE REVIEW

File: examples/camera-app/linux/src/webrtc-libdatachannel.cpp [hunk 1]
```diff
@@ -108,10 +108,14 @@ class LibDataChannelTrack : public WebRTCTrack
...
     {
-        if (mTrack)
+        if (mTrack && mTrack->isOpen())
         {
             mTrack->send(reinterpret_cast<const std::byte *>(data), size);
         }
+        else
+        {
+            ChipLogError(Camera, "Track is closed");
+        }
```
[the remark this answers is not in the document]
Comment (chulspro) [reply examples/camera-app/linux/src/webrtc-libdatachannel.cpp:118]: Already logging `ChipLogError`

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp [hunk 2]
```diff
@@ -340,6 +352,7 @@ CHIP_ERROR WebRTCProviderManager::HandleEndSession(uint16_t sessionId, WebRTCEnd
         mOriginatingEndpointId = 0;
         mPeerId                = ScopedNodeId();
         mLocalSdp.clear();
+        mLocalCandidates.clear();
```
[the remark this answers is not in the document]
Comment (chulspro) [reply examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp:355]: Not explicitly required as we already do `mPeerConnection->Close()`

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp [hunk 3]
```diff
@@ -166,6 +172,12 @@ CHIP_ERROR WebRTCProviderManager::HandleProvideOffer(const ProvideOfferRequestAr
 {
     ChipLogProgress(Camera, "HandleProvideOffer called");
```
Comment (yufengwangca) [inline examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp:174]: do we need those improvements in HandleProvideOffer?

**Review by yufengwangca — APPROVED** [review]

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp [hunk 4]
```diff
@@ -68,6 +69,11 @@ void WebRTCProviderManager::SetMediaController(MediaController * mediaController
 CHIP_ERROR WebRTCProviderManager::HandleSolicitOffer(const OfferRequestArgs & args, WebRTCSessionStruct & outSession,
                                                      bool & outDeferredOffer)
 {
+    if (!mPeerConnection)
```
Comment (marktrayer) [inline examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp]: It's a style thing, but I believe the preference is to explicitly check that it or is not null.
So this becomes:
if (mPeerConnection == nullptr)
{
  Init();
}

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp [hunk 5]
```diff
@@ -166,6 +172,12 @@ CHIP_ERROR WebRTCProviderManager::HandleProvideOffer(const ProvideOfferRequestAr
 {
     ChipLogProgress(Camera, "HandleProvideOffer called");
 
+    if (!mPeerConnection)
```
Comment (marktrayer) [inline examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp]: Same comment as earlier

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp (hunk 4 above)
Comment (chulspro) [reply examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp]: Thank you for your review. Applied it

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp (hunk 5 above)
Comment (chulspro) [reply examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp]: Thank you for your review. Applied it

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp (hunk 3 above)
Comment (chulspro) [reply examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp:174]: Yes, since ProvideOffer / SolicitOffer will be the first command here after any previous EndSession.

**Review by marktrayer — APPROVED** [review]
