### PR TITLE
GroupKeyManagement: Wrong error code returned from key set remove.

### LINKED ISSUE #28748: [CERT-TEST-FAILURE] KeySetRemove for non existing GroupKeySetID should return NOT_FOUND status
### Feature Area
Group Key Management Cluster

### Test Case

TC-GRPKEY-2.2

### Reproduction steps

In the test case execution the last step mentions
Note :0x01b does not exist in the GroupKeyMap attribute
./chip-tool groupkeymanagement key-set-remove "0x01b" 1 0
We are seeing FAILURE as response instead of NOT_FOUND

Spec Reference :
11.2.7.4. KeySetRemove Command
This command SHALL send a SUCCESS status code back to the initiator on success, or NOT_FOUND
if the GroupKeySetID requested did not exist.

Supporting Log:
************************************************************************************************************************
[1692346956.320095][35688:35691] CHIP:DMG: InvokeResponseMessage =
[1692346956.320102][35688:35691] CHIP:DMG: {
[1692346956.320108][35688:35691] CHIP:DMG:         suppressResponse = false, 
[1692346956.320119][35688:35691] CHIP:DMG:         InvokeResponseIBs =
[1692346956.320139][35688:35691] CHIP:DMG:         [
[1692346956.320147][35688:35691] CHIP:DMG:                 InvokeResponseIB =
[1692346956.320162][35688:35691] CHIP:DMG:                 {
[1692346956.320170][35688:35691] CHIP:DMG:                         CommandStatusIB =
[1692346956.320181][35688:35691] CHIP:DMG:                         {
[1692346956.320197][35688:35691] CHIP:DMG:                                 CommandPathIB =
[1692346956.320207][35688:35691] CHIP:DMG:                                 {
[1692346956.320219][35688:35691] CHIP:DMG:                                         EndpointId = 0x0,
[1692346956.320231][35688:35691] CHIP:DMG:                                         ClusterId = 0x3f,
[1692346956.320243][35688:35691] CHIP:DMG:                                         CommandId = 0x3,
[1692346956.320253][35688:35691] CHIP:DMG:                                 },
[1692346956.320268][35688:35691] CHIP:DMG:                                 
**[1692346956.320276][35688:35691] CHIP:DMG:                                 StatusIB =
[1692346956.320289][35688:35691] CHIP:DMG:                                 {
[1692346956.320298][35688:35691] CHIP:DMG:                                         status = 0x01 (FAILURE),
[1692346956.320303][35688:35691] CHIP:DMG:                                 },
[1692346956.320318][35688:35691] CHIP:DMG:                                 
[1692346956.320325][35688:35691] CHIP:DMG:                         },
[1692346956.320333][35688:35691] CHIP:DMG:                         
[1692346956.320337][35688:35691] CHIP:DMG:                 },
[1692346956.320346][35688:35691] CHIP:DMG:**                 
[1692346956.320352][35688:35691] CHIP:DMG:         ],
[1692346956.320360][35688:35691] CHIP:DMG:         
[1692346956.320366][35688:35691] CHIP:DMG:         InteractionModelRevision = 10
[1692346956.320371][35688:35691] CHIP:DMG: },

*****************************************************************************************************************

### Bug prevalence

during manual execution of TC-GRPKEY-2.2

### GitHub hash of the SDK that was being used

a40963d7d571c18f4da18205b918e0c1b4e788f5 

### Platform

other

### Anything else?

NA

### PR DESCRIPTION
**Pull request by cecille**
Fixes: #28748

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

File: src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp [hunk 1]
```diff
@@ -639,7 +639,7 @@ bool emberAfGroupKeyManagementClusterKeySetRemoveCallback(
     CHIP_ERROR err          = provider->RemoveKeySet(fabricIndex, commandData.groupKeySetID);
 
     Status status = Status::Success;
-    if (CHIP_ERROR_KEY_NOT_FOUND == err)
+    if (CHIP_ERROR_NOT_FOUND == err)
```
Comment (tcarmelveilleux) [inline src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:642]: It appears that maybe the issue is that some GroupDataProvider API calls reutrn CHIP_ERROR_NOT_FOUND and others CHIP_ERROR_KEY_NOT_FOUND.

Comment (cecille) [reply src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.cpp:642]: ah. OK, I'll check both on the other side

**Review by tcarmelveilleux — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by cliffamzn — APPROVED** [review]
