### PR TITLE
[Silabs]Add fallback test value for mandatory attributes VendorName and Produ…

### LINKED ISSUE #26267: [Platform] EFR32 SDK lighting example couldn't get valid reply to reading `VendorName` from `BasicInformationCluster`
### Reproduction steps

I used RPCs since I am not setup to commission device onto thread network. But based on debugging I am pretty sure this would happen with chip-tool as well.

Reproduce:
* Issues RPC `rpcs.chip.rpc.Attributes.Read(endpoint=0, cluster=40, attribute_id=1, pw_rpc_timeout_s=1)`
* Get `(Status.INTERNAL, chip.rpc.AttributeData())`

What is happening is that `EFR32DeviceDataProvider::GetVendorName` is called, but `SilabsConfig::ReadConfigValueStr(SilabsConfig::kConfigKey_VendorName` fails, I am guessing because the vendor ID (also productID) are not programmed into the nvm3. Not sure if this is all the time or just for SDK examples because the ID is a null string somewhere.

### Platform

efr32

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jmartinez-silabs**
…ctName

fixes #26267

also update the `sl_matter_version_str` prefix to v1.1

### CODE REVIEW

File: examples/platform/silabs/SilabsDeviceDataProvider.cpp [hunk 1]
```diff
@@ -313,7 +313,16 @@ CHIP_ERROR SilabsDeviceDataProvider::GetSetupPayload(MutableCharSpan & payloadBu
 CHIP_ERROR SilabsDeviceDataProvider::GetVendorName(char * buf, size_t bufSize)
 {
     size_t vendorNameLen = 0; // without counting null-terminator
-    return SilabsConfig::ReadConfigValueStr(SilabsConfig::kConfigKey_VendorName, buf, bufSize, vendorNameLen);
+    CHIP_ERROR err       = SilabsConfig::ReadConfigValueStr(SilabsConfig::kConfigKey_VendorName, buf, bufSize, vendorNameLen);
+#if defined(CHIP_DEVICE_CONFIG_TEST_VENDOR_NAME)
+    if (err == CHIP_DEVICE_ERROR_CONFIG_NOT_FOUND)
+    {
+        VerifyOrReturnError(buf != nullptr, CHIP_ERROR_NO_MEMORY);
+        memcpy(buf, CHIP_DEVICE_CONFIG_TEST_VENDOR_NAME, bufSize);
```
Comment (bzbarsky-apple) [inline examples/platform/silabs/SilabsDeviceDataProvider.cpp:321]: What guarantees that `CHIP_DEVICE_CONFIG_TEST_VENDOR_NAME` is at least `bufSize` bytes?

File: examples/platform/silabs/SilabsDeviceDataProvider.cpp [hunk 2]
```diff
@@ -339,7 +348,16 @@ CHIP_ERROR SilabsDeviceDataProvider::GetVendorId(uint16_t & vendorId)
 CHIP_ERROR SilabsDeviceDataProvider::GetProductName(char * buf, size_t bufSize)
 {
     size_t productNameLen = 0; // without counting null-terminator
-    return SilabsConfig::ReadConfigValueStr(SilabsConfig::kConfigKey_ProductName, buf, bufSize, productNameLen);
+    CHIP_ERROR err        = SilabsConfig::ReadConfigValueStr(SilabsConfig::kConfigKey_ProductName, buf, bufSize, productNameLen);
+#if defined(CHIP_DEVICE_CONFIG_TEST_PRODUCT_NAME)
+    if (err == CHIP_DEVICE_ERROR_CONFIG_NOT_FOUND)
+    {
+        VerifyOrReturnError(buf != nullptr, CHIP_ERROR_NO_MEMORY);
+        memcpy(buf, CHIP_DEVICE_CONFIG_TEST_PRODUCT_NAME, bufSize);
```
Comment (bzbarsky-apple) [inline examples/platform/silabs/SilabsDeviceDataProvider.cpp:356]: Again, what guarantees `CHIP_DEVICE_CONFIG_TEST_PRODUCT_NAME` is at least `bufSize` bytes?

File: src/platform/silabs/CHIPDevicePlatformConfig.h [hunk 3]
```diff
@@ -61,6 +61,28 @@
 #define CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION SL_HARDWARE_VERSION
 #endif
 
+/**
+ *  Allow for some test/fall-back values to be used
+ * Production builds shall set to 0 or remove this option
+ */
+#ifndef CHIP_DEVICE_CONFIG_ENABLE_TEST_SETUP_PARAMS
+#define CHIP_DEVICE_CONFIG_ENABLE_TEST_SETUP_PARAMS 1
```
Comment (bzbarsky-apple) [inline src/platform/silabs/CHIPDevicePlatformConfig.h:69]: This really should not be true by default for the platform, ideally... but I guess other platforms are doing it.  :(

Comment (jmartinez-silabs) [reply src/platform/silabs/CHIPDevicePlatformConfig.h:69]: This options is mostly for devs and daily development and testing. 

Yes, product wouldn't want to use that but there are a few config that they would probably want to change.

The config could be set the 0 by default but then daily devs will need to enable it constantly or just provision the device..  I can't think of a great solution to please both situations

File: examples/platform/silabs/SilabsDeviceDataProvider.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply examples/platform/silabs/SilabsDeviceDataProvider.cpp:321]: > There might be some garbage after the null terminated character. 

Let me make it clearer.

Say CHIP_DEVICE_CONFIG_TEST_VENDOR_NAME points to a string of 4 chars.  That means that the 5 bytes pointed to (including the null terminator) are what need to get copied.

Caller passes in a large buffer, with bufSize set to 1000.  We're going to try to copy 1000 bytes when we only have 5 to work with, and either copy random memory (now it's a security bug!) or crash due to a segmentation violation.

Of course in the other direction if CHIP_DEVICE_CONFIG_TEST_VENDOR_NAME is longer than bufSize you are going to _write_ to memory you don't own (again a security bug).

> Or memcpy of the smallest size between the string to be copied bufSize.

What you should do is use `Platform::CopyString` if you're OK with just truncating when CHIP_DEVICE_CONFIG_TEST_VENDOR_NAME is longer than bufSize can hold, or doing more checks otherwise.

Comment (jmartinez-silabs) [reply examples/platform/silabs/SilabsDeviceDataProvider.cpp]: Thank you for the details,

I replaced the `memcpy` with `CopyString` which use `strncpy`. I also decided not to truncate in case the bufsize is too small, so I added a check for that to error out on those cases instead.

File: src/platform/silabs/CHIPDevicePlatformConfig.h (hunk 3 above)
Comment (jmartinez-silabs) [reply src/platform/silabs/CHIPDevicePlatformConfig.h:69]: I'll keep it like that, for now, has the common `src/include/platform/CHIPDeviceConfig.h` already use that define for PASE test configs/fallbacks

File: examples/platform/silabs/SilabsDeviceDataProvider.cpp [hunk 4]
```diff
@@ -389,7 +391,7 @@ CHIP_ERROR SilabsDeviceDataProvider::GetHardwareVersionString(char * buf, size_t
     if (err == CHIP_DEVICE_ERROR_CONFIG_NOT_FOUND)
     {
         VerifyOrReturnError(buf != nullptr, CHIP_ERROR_NO_MEMORY);
-        memcpy(buf, CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION_STRING, bufSize);
+        Platform::CopyString(buf, bufSize, CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION_STRING);
```
Comment (bzbarsky-apple) [inline examples/platform/silabs/SilabsDeviceDataProvider.cpp:397]: Should probably have a strlen check here too.

**Review by bzbarsky-apple — APPROVED** [review]

File: examples/platform/silabs/SilabsDeviceDataProvider.cpp (hunk 4 above)
Comment (jmartinez-silabs) [reply examples/platform/silabs/SilabsDeviceDataProvider.cpp:397]: Yes, I forgot that one I must have pushed the commit while you were re-reviewing. It is there now.

**Review by tehampson — APPROVED** [review]
