### PR TITLE
app: Fix undef error for CHIP_CONFIG_ENABLE_READ_CLIENT

### LINKED ISSUE #29213: [BUG] Configuration for CHIP_CONFIG_ENABLE_READ_CLIENT looks broken
### Reproduction steps

Compiling with `-Wundef` added in `build/config/compiler/BUILD.gn` in the `strict_warnings` section leads to a bunch of failures because things check `CHIP_CONFIG_ENABLE_READ_CLIENT` without it actually being defined.

This seems very broken: why are the relevant files being compiled in an environment where that variable is not set to either 1 or 0?  In particular, that means the compilation for those is broken if read client _is_ enabled.

Looks like this was caused by https://github.com/project-chip/connectedhomeip/pull/28149.  For 1.2 we need to either fix this or back out that PR @wqx6 @andy31415 @woody-apple 

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

b02c9842e3dedc8f81f16760da5c322affdf27ee

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by wqx6**
We were checking CHIP_CONFIG_ENABLE_READ_CLIENT without including the config header that defines it.

Fixes #29213

### CODE REVIEW

File: src/app/AttributePathParams.h [hunk 1]
```diff
@@ -18,6 +18,7 @@
 
 #pragma once
 
+#include <app/AppBuildConfig.h>
```
Comment (bzbarsky-apple) [inline src/app/AttributePathParams.h:21]: But there are other files that check CHIP_CONFIG_ENABLE_READ_CLIENT but don't include this header, no?

Comment (wqx6) [reply src/app/AttributePathParams.h:21]: I have added the following code in the files that uses `CHIP_CONFIG_ENABLE_READ_CLIENT`
```
#if !undefined(CHIP_CONFIG_ENABLE_READ_CLIENT)
#error "CHIP_CONFIG_ENABLE_READ_CLIENT undefined"
#endif
```
Only this file reports this error.

Comment (wqx6) [reply src/app/AttributePathParams.h:21]: Looks like other files includes some headers that include `app/AppBuildConfig.h`.

Comment (bzbarsky-apple) [reply src/app/AttributePathParams.h:21]: > Looks like other files includes some headers that include app/AppBuildConfig.h.

That's not reliable.  Those headers can change.  If those files depend on `AppBuildConfig.h`, those files should include it directly.

Comment (wqx6) [reply src/app/AttributePathParams.h:21]: Added this header for all the other files

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
