### PR TITLE
Fix crashes when last controller is shut down while a PASE session is outstanding.

### LINKED ISSUE #16440: Fix CommissioneeDeviceProxy destructor to close session.
#### Problem
CommissioneeDeviceProxy doesn't clean up the session, so we will still get callbacks after the proxy is destroyed.

 #### Proposed Solution
remove session in destructor.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Commissioner shutdown shuts down the CASE sessions associated with the
commissioner, but not the PASE sessions.  Those sessions then get shut down
much later in shutdown, at which point various objects that are needed to
handle the shutdown are no longer present.

The fix is to shut down PASE sessions when we destroy CommissioneeDeviceProxy
objects, and ensure that we always destroy CommissioneeDeviceProxy via
ReleaseCommissioneeDevice, so we don't end up with dangling pointers to the
objects.

Fixes https://github.com/project-chip/connectedhomeip/issues/16440

Should vastly improve, if not completely fix,
https://github.com/project-chip/connectedhomeip/issues/20880 which is a very common crash we are seeing.

#### Problem
Crashes during shutdown of the Matter stack.

#### Change overview
Clean up PASE sessions earlier in shutdown.

#### Testing
Should pass existing tests.

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]

**Comment by andy31415** [comment]
Acceptable for 1.0: fixing a crash

**Review by woody-apple — APPROVED** [review]

File: src/controller/CHIPDeviceController.cpp [hunk 1]
```diff
@@ -559,6 +551,11 @@ void DeviceCommissioner::ReleaseCommissioneeDevice(CommissioneeDeviceProxy * dev
     {
         mDeviceBeingCommissioned = nullptr;
     }
+
+    // Release the commissionee device after we have nulled out our pointers,
+    // because that can call back in to us with error notifications as the
+    // session is released.
+    mCommissioneeDevicePool.ReleaseObject(device);
```
Comment (amitnj) [inline src/controller/CHIPDeviceController.cpp:558]: @bzbarsky-apple Looks like there are two calls now to ReleaseObject from the device pool. I am getting an error when I tried to use commissioning through the tv-casting-app. Is it expected to have two calls to ReleaseObject?

Comment (bzbarsky-apple) [reply src/controller/CHIPDeviceController.cpp:558]: This got fixed in #22403.
