### PR TITLE
[Telink] Redefined ping timeout for WebSocketServer

### LINKED ISSUE #29951: [CERT-TEST-FAILURE] Test_TC_OO_2_3 failure (websockets.exceptions.ConnectionClosedError)
### Feature Area

Other

### Test Case

TC_OO_2_3

### Reproduction steps

Running the Test_TC_OO_2_3 on Telink LightingApp (Thread-commissioned) with
```
scripts/tests/yaml/chiptool.py tests Test_TC_OO_2_3 --nodeId $LIGHTING_NODE_ID
```
The **step 131** interrupts with an error, dropping websocket connection:
`websockets.exceptions.ConnectionClosedError: no close frame received or sent`
By default on the **previous step 130** the wait interval is set to 40sec. I've tried decreasing timeout 40->20sec and it finished like normally would. Also tried doing that in differrent setup and Thread network, identical behavior.
Logs are in attached file.

Also tried playing with `_KEEP_ALIVE_TIMEOUT_IN_SECONDS` value in `scripts/py_matter_yamltests/matter_yamltests/websocket_runner.py` , didn't help much

**Could you confirm the issue must be on my side or is it a common and known thing to other platforms as well?**

[Test_TC_OO_2_3.log](https://github.com/project-chip/connectedhomeip/files/13116936/Test_TC_OO_2_3.log)

### Bug prevalence

Each time I do this

### GitHub hash of the SDK that was being used

433e6769389c5e127e8d88418d1dae3150e39534

### Platform

python, other

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by interfer**
As Test_TC_OO_2_3 has been failing on Telink platform because of WS closing on server side, added redefinition of `secs_since_valid_ping` and `secs_since_valid_hangup` so the connection would not be closed during the test.

**Fixes [#29951](https://github.com/project-chip/connectedhomeip/issues/29951)**

Tested on Telink Lighting-App Thread commissioned, as described in issue mentioned above

### CODE REVIEW

**Review by arkq — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

File: examples/common/websocket-server/WebSocketServer.cpp [hunk 1]
```diff
@@ -166,10 +166,15 @@ CHIP_ERROR WebSocketServer::Run(chip::Optional<uint16_t> port, WebSocketServerDe
...
-    info.pt_serv_buf_size = kMaxMessageBufferLen;
-    info.protocols        = protocols;
+    info.port                         = port.ValueOr(kDefaultWebSocketServerPort);
+    info.iface                        = nullptr;
+    info.pt_serv_buf_size             = kMaxMessageBufferLen;
+    info.protocols                    = protocols;
+    static const lws_retry_bo_t retry = {
+        .secs_since_valid_ping   = 400,
+        .secs_since_valid_hangup = 400,
+    };
```
Comment (bzbarsky-apple) [inline examples/common/websocket-server/WebSocketServer.cpp:176]: This is not initializing all the struct members.  What values do the other members end up with, and why are those values OK?

Comment (arkq) [reply examples/common/websocket-server/WebSocketServer.cpp:176]: > This is not initializing all the struct members

It does initialize them implicitly to zero - the `retry` has static storage duration.

Comment (interfer) [reply examples/common/websocket-server/WebSocketServer.cpp:176]: @bzbarsky-apple @arkq 
Thanks for your interest!

> What values do the other members end up with, and why are those values OK?

Eventually it will look like this:
```
[D] retry_ms_table_count=4
[D] conceal_count=4
[D] secs_since_valid_ping=400
[D] secs_since_valid_hangup=400
[D] jitter_percent=20
```

I didn't make initialization of other struct members because it would be useless as in [libwebsockets/repo/lib/core/context.c#L1138](https://github.com/warmcat/libwebsockets/blob/288f36fc8178e2664614b78322d2d05a70b9ac0a/lib/core/context.c#L1138) those values are set from `default_retry` structure thus cannot be redefined as `secs_since_valid_ping` and `secs_since_valid_hangup`. 
I've even tested that manually, they don't change in runtime anywhere. 
I don't think we need to redefine all the variables in the `lws_retry_bo_t` as default are OK. We regularly run certification tests on the development board and they all pass now, no issues regarding websocket or any others.

BUT if we want to do that, then _maybe_ not the `lws_create_context` should be used in `connectedhomeip/examples/common/websocket-server/WebSocketServer.cpp` but `lws_client_connect_via_info` from `connectedhomeip/third_party/libwebsockets/repo/lib/core-net/client/connect.c`. 
 
Static initialization was taken as a referrence from repo's examples like this one in [libwebsockets/repo/minimal-examples-lowlevel/ws-client/minimal-ws-client/minimal-ws-client.c](https://github.com/warmcat/libwebsockets/blob/288f36fc8178e2664614b78322d2d05a70b9ac0a/minimal-examples-lowlevel/ws-client/minimal-ws-client/minimal-ws-client.c#L39)

Please, let me know if I should make any changes considering all above and thanks for your time!

Comment (bzbarsky-apple) [reply examples/common/websocket-server/WebSocketServer.cpp:176]: @interfer Ah, I see.  Ok, perfect, that's what I needed to know.

**Comment by wilbur-se** [comment]
From my test, the socket will be closed by server after 400s idle. Maybe we need set “secs_since_valid_hangup” larger than ”secs_since_valid_ping“。

**Comment by bzbarsky-apple** [comment]
@wilbur-se If you make that change, does that solve your issue? If so, please create a PR?

**Comment by wilbur-se** [comment]
@bzbarsky-apple Sure, just create one #33158
