### PR TITLE
Fix MRP baseTimeout calculation for LIT

### LINKED ISSUE #35354: [BUG] CASE timeout is to long on LIT ICD
### Reproduction steps

After sending/receiving a Sigma1 (but no follow up). a CASE Session is opened but no timeout is ever triggered. This leads to an error when trying to etablish a new CASE Sesssion;
 [SC] Received error (protocol code 4) during pairing process: src/protocols/secure_channel/CASESession.cpp:2144: CHIP Error 0x000000DB: The Resource is busy and cannot process the request
It also prevents an ICD to leave active mode, draining the battery (https://github.com/project-chip/connectedhomeip/issues/35355).

I reproduced the issue with the LIT-ICD App on the Silabs EFR32 Platform, compiled with the Following Parameters: --icd --low-power enable_openthread_cli=false chip_enable_ota_requestor=true chip_persist_subscriptions=false
I also enabled the openthread log, so I can see poll atempts to check the interval.

- Flash the software, commission the device
- Trigger a CASE Session from Chiptool, but exit Chiptool directly after sending the Sigma1
- Watch the Logs of the Device. It will never timeout the case session
- Wait some time (at least the expected case timeout)
- Start Chiptool again, Trigger a CASE Session again
- Observer the "Resource is busy" Error message in Chiptool and the device log.

The Issue can also be observed in the reverse way, if the DUT triggered the CASE Session, but I did not manage to do that with an unmodified example.

### Bug prevalence

Everytime I ran the listed steps.

### GitHub hash of the SDK that was being used

0e3434a0665ab908e27bef9a84d4429ab8f9d93a

### Platform

efr32

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yunhanw-google**
Currently MRP baseTimeout calculation may be fine for SIT, but it is problematic for LIT ICD where Idle internal could be very large, and mrp timeout could be very large, which prevent devices going into sleep node.

Actually, we need to handle two scenarios: the controller sending an initial message to a LIT, and the controller sending a subsequent message. 

This PR matched the logic from GetRetransmissionTimeout with ReliableMessageMgr::CalculateNextRetransTime which always treats things as "active" for non-initial messages on the exchange.

Fixes: https://github.com/project-chip/connectedhomeip/issues/35354

#### Testing
Working on manually triggering and testing this case locally with manufactuers

### CODE REVIEW

File: src/messaging/ReliableMessageProtocolConfig.cpp [hunk 1]
```diff
@@ -135,7 +135,7 @@ System::Clock::Timeout GetRetransmissionTimeout(System::Clock::Timeout activeInt
     System::Clock::Timestamp timeout(0);
     for (uint8_t i = 0; i < CHIP_CONFIG_RMP_DEFAULT_MAX_RETRANS + 1; i++)
     {
-        auto baseInterval = ((timeSinceLastActivity + timeout) < activityThreshold) ? activeInterval : idleInterval;
```
Comment (Damian-Nordic) [inline src/messaging/ReliableMessageProtocolConfig.cpp:138]: You shouldn't remove the usage of idle interval for SIT or non-ICD devices. This exception should be for LIT only where the idle interval can be very long.

**Review by Damian-Nordic — CHANGES_REQUESTED** [review]

File: src/messaging/ReliableMessageProtocolConfig.cpp (hunk 1 above)
Comment (yunhanw-google) [reply src/messaging/ReliableMessageProtocolConfig.cpp:138]: I agree, I think it would be to use min(activeInterval, idleInterval) here for both client and server regarding mrp configuration.

For SIT/non-ICD, SAI would be larger than SII, then it would go with SII when it reaches to idle status.

For LIT, SAI would be less than SII, then it would go with SAI when it reaches to idle status.

Comment (Damian-Nordic) [reply src/messaging/ReliableMessageProtocolConfig.cpp:138]: I don't think SAI is usually larger than SII for SIT/non-ICD. In fact, default SAI is 300ms while SII is 500. For SIT it's also common to use a sub-second fast-polling interval and a couple of seconds slow-polling interval. Unfortunately, it seems that we need some sort of flag passed from outside to indicate that the receiver is LIT. Alternatively, we could detect that by checking if SII > 15s?

File: src/messaging/ReliableMessageProtocolConfig.cpp [hunk 2]
```diff
@@ -135,7 +135,8 @@ System::Clock::Timeout GetRetransmissionTimeout(System::Clock::Timeout activeInt
...
+        auto baseInterval =
+            ((timeSinceLastActivity + timeout) < activityThreshold) ? activeInterval : min(activeInterval, idleInterval);
```
Comment (bzbarsky-apple) [inline src/messaging/ReliableMessageProtocolConfig.cpp:139]: This is a clear spec violation.

File: src/transport/SecureSession.h [hunk 3]
```diff
@@ -265,7 +265,8 @@ class SecureSession : public Session, public ReferenceCounted<SecureSession, Sec
 
     System::Clock::Timestamp GetMRPBaseTimeout() const override
     {
-        return IsPeerActive() ? GetRemoteMRPConfig().mActiveRetransTimeout : GetRemoteMRPConfig().mIdleRetransTimeout;
+        return IsPeerActive() ? GetRemoteMRPConfig().mActiveRetransTimeout
+                              : min(GetRemoteMRPConfig().mActiveRetransTimeout, GetRemoteMRPConfig().mIdleRetransTimeout);
```
Comment (bzbarsky-apple) [inline src/transport/SecureSession.h:269]: This is also a spec violation.

File: src/transport/UnauthenticatedSessionTable.h [hunk 4]
```diff
@@ -155,7 +155,8 @@ class UnauthenticatedSession : public Session, public ReferenceCounted<Unauthent
 
     System::Clock::Timestamp GetMRPBaseTimeout() const override
     {
-        return IsPeerActive() ? GetRemoteMRPConfig().mActiveRetransTimeout : GetRemoteMRPConfig().mIdleRetransTimeout;
+        return IsPeerActive() ? GetRemoteMRPConfig().mActiveRetransTimeout
+                              : min(GetRemoteMRPConfig().mActiveRetransTimeout, GetRemoteMRPConfig().mIdleRetransTimeout);
```
Comment (bzbarsky-apple) [inline src/transport/UnauthenticatedSessionTable.h:159]: As is this.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]
The right fix for https://github.com/project-chip/connectedhomeip/issues/35354 is to fix the issue pointed out in https://github.com/project-chip/connectedhomeip/issues/35354#issuecomment-2342005193

File: src/messaging/ReliableMessageProtocolConfig.cpp (hunk 1 above)
Comment (yunhanw-google) [reply src/messaging/ReliableMessageProtocolConfig.cpp:138]: Yes, considering dynamic ICD feature, it would be hard to feature flag to setup MRP timeout here.

I would prefer checking if SII > 15 s, I just update the code to reflect, thanks

File: src/messaging/ReliableMessageProtocolConfig.cpp (hunk 2 above)
Comment (yunhanw-google) [reply src/messaging/ReliableMessageProtocolConfig.cpp]: I just follow @damian's suggestion, and use 15 seconds to determine whether device is in LIT mode, then if
yes, set the timeout base as SAI when timeSinceLastActivity + timeout) >= activityThreshold and it is LIT

Comment (bzbarsky-apple) [reply src/messaging/ReliableMessageProtocolConfig.cpp]: > I just follow @damian's suggestion in this pr

Again: it's as spec violation.

> For the original https://github.com/project-chip/connectedhomeip/issues/35354#issuecomment-2342005193, i don't think that is enough

So:

1. The changes proposed in this bug are not enough to fix the fact that the timeout calculations are just wrong.
2. I don't understand your example of "if client send out the first case message in the end of active window".  The issue with timeouts we are seeing is that a server sending a Sigma2 waits long enough that a client sending it a message and using its SII would time out MRP before it times out waiting for the Sigma2 response.  But of course no client is going to use SII in that calculation of actual MRP bits, since it's an active exchange.  So properly using SAI in that situation will in fact fix https://github.com/project-chip/connectedhomeip/issues/35354.

> but session layer may not be able to know whether it is the first message..

Of course, which is why the information about whether things should be force-considered not idle needs to be passed in to the session from the API consumer, which _does_ have this information about the state of the exchange.

Comment (yunhanw-google) [reply src/messaging/ReliableMessageProtocolConfig.cpp]: Thanks for comments. I agree. 

I have matched the logic from GetRetransmissionTimeout the logic with ReliableMessageMgr::CalculateNextRetransTime which always treats things as "active" for non-initial messages on the exchange. 

i have plumber the isPeerActive boolean from application to session layer. The client, like commissioner/controller, would always use SAI for calculation via setting isPeerActive as true.

File: src/app/CommandSender.cpp [hunk 5]
```diff
@@ -125,7 +125,8 @@ CHIP_ERROR CommandSender::SendCommandRequestInternal(const SessionHandle & sessi
     mExchangeCtx.Grab(exchange);
     VerifyOrReturnError(!mExchangeCtx->IsGroupExchangeContext(), CHIP_ERROR_INVALID_MESSAGE_TYPE);
 
-    mExchangeCtx->SetResponseTimeout(timeout.ValueOr(session->ComputeRoundTripTimeout(app::kExpectedIMProcessingTime)));
+    mExchangeCtx->SetResponseTimeout(timeout.ValueOr(
+        session->ComputeRoundTripTimeout(app::kExpectedIMProcessingTime, mExchangeCtx.Get()->HasReceivedAtLeastOneMessage())));
```
Comment (bzbarsky-apple) [inline src/app/CommandSender.cpp:129]: Won't `mExchangeCtx.Get()->HasReceivedAtLeastOneMessage()` always be false here?  I don't get this logic.

File: src/transport/Session.h [hunk 6]
```diff
@@ -254,7 +254,7 @@ class Session
     // GetAckTimeout is the estimate for how long it could take for the other
     // side to receive our message (accounting for our MRP retransmits if it
     // gets lost) and send a response.
-    virtual System::Clock::Milliseconds32 GetAckTimeout() const = 0;
+    virtual System::Clock::Milliseconds32 GetAckTimeout(bool isPeerActive) const = 0;
```
Comment (bzbarsky-apple) [inline src/transport/Session.h:257]: What does this boolean really mean?  Is it a "we know the peer is active via some information not available to the session"?  Or is it a "the MRP machinery on our side will assume the peer is active regardless of what the session state is"?

I suspect it's the latter of those two, but please double-check.  The naming, documentation (which needs to exist) and actual setting of this parameter need to match the intended meaning.

File: src/transport/Session.h [hunk 7]
```diff
@@ -265,15 +265,16 @@ class Session
     // System::SystemClock().GetMonotonicTimestamp() (to indicate "peer is
     // responding to a message it just received") and System::Clock::kZero (to
     // indicate "peer is reaching out to us, not in response to anything").
-    virtual System::Clock::Milliseconds32 GetMessageReceiptTimeout(System::Clock::Timestamp ourLastActivity) const = 0;
+    virtual System::Clock::Milliseconds32 GetMessageReceiptTimeout(System::Clock::Timestamp ourLastActivity,
+                                                                   bool isPeerActive) const = 0;
```
Comment (bzbarsky-apple) [inline src/transport/Session.h:269]: This part makes no sense to me.  Whether the _peer_ is active or not has nothing to do with how long it will keep retrying to get a message to _us_.  What matter is whether the peer thinks _we_ are active.

In practice we need to carefully look at the callsites of this function.  I suspect in all of them the peer would be assuming we are active because it's responding to our message, but that needs to be verified carefully.

File: src/transport/Session.h [hunk 8]
```diff
@@ -265,15 +265,16 @@ class Session
...
 
     const ReliableMessageProtocolConfig & GetRemoteMRPConfig() const { return GetRemoteSessionParameters().GetMRPConfig(); }
 
     // Returns a suggested timeout value based on the round-trip time it takes for the peer at the other end of the session to
     // receive a message, process it and send it back. This is computed based on the session type, the type of transport, sleepy
     // characteristics of the target and a caller-provided value for the time it takes to process a message at the upper layer on
     // the target For group sessions, this function will always return 0.
-    System::Clock::Timeout ComputeRoundTripTimeout(System::Clock::Timeout upperlayerProcessingTimeout);
+    System::Clock::Timeout ComputeRoundTripTimeout(System::Clock::Timeout upperlayerProcessingTimeout, bool isPeerActive);
```
Comment (bzbarsky-apple) [inline src/transport/Session.h:277]: Again, what does this boolean actually mean?

File: src/messaging/ReliableMessageProtocolConfig.cpp [hunk 9]
```diff
@@ -126,7 +126,8 @@ Optional<ReliableMessageProtocolConfig> GetLocalMRPConfig()
 }
 
 System::Clock::Timeout GetRetransmissionTimeout(System::Clock::Timeout activeInterval, System::Clock::Timeout idleInterval,
-                                                System::Clock::Timeout lastActivityTime, System::Clock::Timeout activityThreshold)
+                                                System::Clock::Timeout lastActivityTime, System::Clock::Timeout activityThreshold,
+                                                bool isPeerActive)
```
Comment (bzbarsky-apple) [inline src/messaging/ReliableMessageProtocolConfig.cpp:130]: So... maybe if we want to match `ReliableMessageMgr::CalculateNextRetransTime` we should just explicitly have a isResponseMessage boolean argument here?  That would make it _very_ clear what is actually going on and how to go about deciding what to pass in.

File: src/protocols/secure_channel/CASESession.h [hunk 10]
```diff
@@ -157,13 +157,16 @@ class DLL_EXPORT CASESession : public Messaging::UnsolicitedMessageHandler,
 
     FabricIndex GetFabricIndex() const { return mFabricIndex; }
 
+    bool IsPeerActive() { return mExchangeCtxt.HasValue() && mExchangeCtxt.Value()->HasReceivedAtLeastOneMessage(); };
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.h:160]: Should not be needed.

File: src/protocols/secure_channel/CASESession.h [hunk 11]
```diff
@@ -157,13 +157,16 @@ class DLL_EXPORT CASESession : public Messaging::UnsolicitedMessageHandler,
...
     // Compute our Sigma1 response timeout.  This can give consumers an idea of
     // how long it will take to detect that our Sigma1 did not get through.
-    static System::Clock::Timeout ComputeSigma1ResponseTimeout(const ReliableMessageProtocolConfig & remoteMrpConfig);
+    static System::Clock::Timeout ComputeSigma1ResponseTimeout(const ReliableMessageProtocolConfig & remoteMrpConfig,
+                                                               bool isPeerActive);
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.h:164]: For a _Sigma1_, again if we are trying to match CalculateNextRetransTime(), the peer is never "known active", right?  Because it's the first message on the exchange.

File: src/protocols/secure_channel/CASESession.h [hunk 12]
```diff
@@ -157,13 +157,16 @@ class DLL_EXPORT CASESession : public Messaging::UnsolicitedMessageHandler,
...
 
     // Compute our Sigma2 response timeout.  This can give consumers an idea of
     // how long it will take to detect that our Sigma1 did not get through.
-    static System::Clock::Timeout ComputeSigma2ResponseTimeout(const ReliableMessageProtocolConfig & remoteMrpConfig);
+    static System::Clock::Timeout ComputeSigma2ResponseTimeout(const ReliableMessageProtocolConfig & remoteMrpConfig,
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.h:168]: Sigma2 is always a response.  So in this case the peer is always known "active".

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/messaging/ReliableMessageProtocolConfig.cpp (hunk 2 above)
Comment (yunhanw-google) [reply src/messaging/ReliableMessageProtocolConfig.cpp]: updated, thanks

File: src/transport/SecureSession.h (hunk 3 above)
Comment (yunhanw-google) [reply src/transport/SecureSession.h]: reverted, thanks

File: src/transport/UnauthenticatedSessionTable.h (hunk 4 above)
Comment (yunhanw-google) [reply src/transport/UnauthenticatedSessionTable.h]: reverted, thanks

File: src/protocols/secure_channel/CASESession.h (hunk 12 above)
Comment (yunhanw-google) [reply src/protocols/secure_channel/CASESession.h]: i agree, updated, thanks

File: src/protocols/secure_channel/CASESession.h (hunk 11 above)
Comment (yunhanw-google) [reply src/protocols/secure_channel/CASESession.h]: i agree, updated, thanks

File: src/messaging/ReliableMessageProtocolConfig.cpp (hunk 9 above)
Comment (yunhanw-google) [reply src/messaging/ReliableMessageProtocolConfig.cpp]: I am now using isInitial boolean, which should be similar to !isResponseMessage, thanks

File: src/transport/Session.h (hunk 7 above)
Comment (yunhanw-google) [reply src/transport/Session.h]: I agree, yes, after checking all calls, i think all of them the peer would be assuming we are active. updated, thanks

File: src/transport/Session.h (hunk 6 above)
Comment (yunhanw-google) [reply src/transport/Session.h]: yes, the latter should be right after checking around the code. updated. thanks

File: src/app/CommandSender.cpp (hunk 5 above)
Comment (yunhanw-google) [reply src/app/CommandSender.cpp]: removed. thanks

File: src/transport/Session.h (hunk 8 above)
Comment (yunhanw-google) [reply src/transport/Session.h]: removed, thanks

File: src/transport/Session.h [hunk 13]
```diff
@@ -265,7 +265,9 @@ class Session
     // System::SystemClock().GetMonotonicTimestamp() (to indicate "peer is
     // responding to a message it just received") and System::Clock::kZero (to
     // indicate "peer is reaching out to us, not in response to anything").
-    virtual System::Clock::Milliseconds32 GetMessageReceiptTimeout(System::Clock::Timestamp ourLastActivity) const = 0;
+    // isInitial indicates whether the other side treats us as initial message.
+    virtual System::Clock::Milliseconds32 GetMessageReceiptTimeout(System::Clock::Timestamp ourLastActivity,
+                                                                   bool isInitial) const = 0;
```
[the remark this answers is not in the document]
Comment (yunhanw-google) [reply src/transport/Session.h:270]: I agree, thanks, updated

File: src/protocols/secure_channel/CASESession.cpp [hunk 14]
```diff
@@ -2622,23 +2622,26 @@ System::Clock::Timeout ComputeRoundTripTimeout(ExchangeContext::Timeout serverPr
                                     // Assume peer is idle, as a worst-case assumption (probably true for
                                     // Sigma1, since that will be our initial message on the session, but less
                                     // so for Sigma2).
-                                    System::Clock::kZero, remoteMrpConfig.mActiveThresholdTime) +
+                                    System::Clock::kZero, remoteMrpConfig.mActiveThresholdTime, isFirstMessageOnExchange) +
         serverProcessingTime +
         GetRetransmissionTimeout(localMRPConfig.mActiveRetransTimeout, localMRPConfig.mIdleRetransTimeout,
                                  // Peer will assume we are active, since it's
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:2628]: I can't suggest on the whole comment here, since it includes removals, but this comment should say:
```
    // Peer will be responding to our message, so isFirstMessageOnExchange should be false
    // and the timestamp does not matter.
```

or something along those lines.

File: src/protocols/secure_channel/CASESession.cpp [hunk 15]
```diff
@@ -2622,23 +2622,26 @@ System::Clock::Timeout ComputeRoundTripTimeout(ExchangeContext::Timeout serverPr
...
+                                 System::SystemClock().GetMonotonicTimestamp(), localMRPConfig.mActiveThresholdTime,
+                                 false /*isFirstMessageOnExchange*/);
 }
 } // anonymous namespace
 
 System::Clock::Timeout CASESession::ComputeSigma1ResponseTimeout(const ReliableMessageProtocolConfig & remoteMrpConfig)
 {
-    return ComputeRoundTripTimeout(kExpectedSigma1ProcessingTime, remoteMrpConfig);
+    // Assume it is the initial message on the session, and treat peer as idle for Sigma1
+    return ComputeRoundTripTimeout(kExpectedSigma1ProcessingTime, remoteMrpConfig, false /*isFirstMessageOnExchange*/);
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:2638]:
```suggestion
    // Sigma1 is the first message on the exchange.
    return ComputeRoundTripTimeout(kExpectedSigma1ProcessingTime, remoteMrpConfig, true /*isFirstMessageOnExchange*/);
```

File: src/protocols/secure_channel/CASESession.cpp [hunk 16]
```diff
@@ -2622,23 +2622,26 @@ System::Clock::Timeout ComputeRoundTripTimeout(ExchangeContext::Timeout serverPr
...
 }
 
 System::Clock::Timeout CASESession::ComputeSigma2ResponseTimeout(const ReliableMessageProtocolConfig & remoteMrpConfig)
 {
-    return ComputeRoundTripTimeout(kExpectedHighProcessingTime, remoteMrpConfig);
+    // Assume it is the response message on the session, and treat peer as active for Sigma2
+    return ComputeRoundTripTimeout(kExpectedHighProcessingTime, remoteMrpConfig, true /*isFirstMessageOnExchange*/);
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:2644]:
```suggestion
    // Sigma2 is never the first message on the exchange.
    return ComputeRoundTripTimeout(kExpectedHighProcessingTime, remoteMrpConfig, false /*isFirstMessageOnExchange*/);
```

File: src/transport/SecureSession.h [hunk 17]
```diff
@@ -194,7 +195,8 @@ class SecureSession : public Session, public ReferenceCounted<SecureSession, Sec
             const auto & defaultMRRPConfig   = GetDefaultMRPConfig();
             const auto & localMRPConfig      = maybeLocalMRPConfig.ValueOr(defaultMRRPConfig);
             return GetRetransmissionTimeout(localMRPConfig.mActiveRetransTimeout, localMRPConfig.mIdleRetransTimeout,
-                                            ourLastActivity, localMRPConfig.mActiveThresholdTime);
+                                            ourLastActivity, localMRPConfig.mActiveThresholdTime,
+                                            ourLastActivity == System::Clock::kZero /*isFirstMessageOnExchange*/);
```
Comment (bzbarsky-apple) [inline src/transport/SecureSession.h:199]:
```suggestion
                                            false /*isFirstMessageOnExchange*/);
```
`GetMessageReceiptTimeout` is always asking how long the _response_ will take, so it's never the first message on an exchange, no?

File: src/transport/Session.cpp [hunk 18]
```diff
@@ -71,9 +71,10 @@ System::Clock::Timeout Session::ComputeRoundTripTimeout(System::Clock::Timeout u
         return System::Clock::kZero;
     }
 
-    // Treat us as active for purposes of GetMessageReceiptTimeout(), since the
-    // other side would be responding to our message.
-    return GetAckTimeout() + upperlayerProcessingTimeout + GetMessageReceiptTimeout(System::SystemClock().GetMonotonicTimestamp());
+    // Treat us as active for purposes of GetMessageReceiptTimeout(), pass false into GetAckTimeout to
+    // indicate we are processing non-initial message since the other side would be responding to our message.
```
Comment (bzbarsky-apple) [inline src/transport/Session.cpp:75]: No, the "responding to our message" is the `GetMessageReceiptTimeout()` bit, and it passes false already.  But GetAckTimeout.... we don't know what to pass it, because it depends on whether this ComputeRoundTripTimeout() call is for an initial message or not.  As in, this function needs a isFirstMessageOnExchange argument, just like the copy of this function in CASESession.cpp needed one.

File: src/transport/Session.h [hunk 19]
```diff
@@ -254,7 +254,8 @@ class Session
     // GetAckTimeout is the estimate for how long it could take for the other
     // side to receive our message (accounting for our MRP retransmits if it
     // gets lost) and send a response.
-    virtual System::Clock::Milliseconds32 GetAckTimeout() const = 0;
+    // This need to know whether we are talking about an initial message we send or not via isFirstMessageOnExchange
```
Comment (bzbarsky-apple) [inline src/transport/Session.h:257]:
```suggestion
    //
    // The MRP retransmit delay computation depends on whether this is the first message on the exchange.
```

File: src/transport/UnauthenticatedSessionTable.h [hunk 20]
```diff
@@ -120,7 +121,8 @@ class UnauthenticatedSession : public Session, public ReferenceCounted<Unauthent
             const auto & defaultMRRPConfig   = GetDefaultMRPConfig();
             const auto & localMRPConfig      = maybeLocalMRPConfig.ValueOr(defaultMRRPConfig);
             return GetRetransmissionTimeout(localMRPConfig.mActiveRetransTimeout, localMRPConfig.mIdleRetransTimeout,
-                                            ourLastActivity, localMRPConfig.mActiveThresholdTime);
+                                            ourLastActivity, localMRPConfig.mActiveThresholdTime,
+                                            ourLastActivity == System::Clock::kZero /*isFirstMessageOnExchange*/);
```
Comment (bzbarsky-apple) [inline src/transport/UnauthenticatedSessionTable.h:125]:
```suggestion
                                            false /*isFirstMessageOnExchange*/);
```

File: src/protocols/secure_channel/CASESession.cpp (hunk 14 above)
Comment (yunhanw-google) [reply src/protocols/secure_channel/CASESession.cpp:2628]: updated, thanks

File: src/protocols/secure_channel/CASESession.cpp (hunk 16 above)
Comment (yunhanw-google) [reply src/protocols/secure_channel/CASESession.cpp]: updated, thanks

File: src/transport/Session.cpp (hunk 18 above)
Comment (yunhanw-google) [reply src/transport/Session.cpp:75]: audited and update all ComputeRoundTripTimeout caller, thanks

File: src/messaging/ExchangeContext.h [hunk 21]
```diff
@@ -177,7 +177,6 @@ class DLL_EXPORT ExchangeContext : public ReliableMessageContext,
 
     // Applies a suggested response timeout value based on the session type and the given upper layer processing time for
     // the next message to the exchange. The exchange context must have a valid session when calling this function.
-    //
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeContext.h:180]: Why this change?  Please don't make this change.

File: src/protocols/secure_channel/CASESession.cpp [hunk 22]
```diff
@@ -546,6 +546,7 @@ CHIP_ERROR CASESession::EstablishSession(SessionManager & sessionManager, Fabric
     mSessionResumptionStorage = sessionResumptionStorage;
     mLocalMRPConfig           = MakeOptional(mrpLocalConfig.ValueOr(GetDefaultMRPConfig()));
 
+    // Sigma1 is the first message on the exchange.
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:549]:
```suggestion
```

**Review by bzbarsky-apple — APPROVED** [review]

File: src/messaging/ExchangeContext.h (hunk 21 above)
Comment (yunhanw-google) [reply src/messaging/ExchangeContext.h]: done, thanks

File: src/transport/SecureSession.h [hunk 23]
```diff
@@ -194,7 +195,8 @@ class SecureSession : public Session, public ReferenceCounted<SecureSession, Sec
             const auto & defaultMRRPConfig   = GetDefaultMRPConfig();
             const auto & localMRPConfig      = maybeLocalMRPConfig.ValueOr(defaultMRRPConfig);
             return GetRetransmissionTimeout(localMRPConfig.mActiveRetransTimeout, localMRPConfig.mIdleRetransTimeout,
-                                            ourLastActivity, localMRPConfig.mActiveThresholdTime);
+                                            ourLastActivity, localMRPConfig.mActiveThresholdTime,
+                                            false /*isFirstMessageOnExchange*/);
```
Comment (Damian-Nordic) [inline src/transport/SecureSession.h:199]: Shouldn't this also be taken as a parameter? This is used by `ReadClient` to calculate the timeout for receiving ReportData and each ReportData comes on a new exchange, so in such a case this parameter should be `true`, right?

Comment (yunhanw-google) [reply src/transport/SecureSession.h:199]: see this comment from boris, 
https://github.com/project-chip/connectedhomeip/pull/37696#discussion_r1984363287

where "GetMessageReceiptTimeout is always asking how long the response will take, so it's never the first message on an exchange."
See comment here. https://github.com/project-chip/connectedhomeip/blob/714907ec5b146dbf48373b72a32fd838e26402a5/src/app/ReadClient.cpp#L991

https://github.com/project-chip/connectedhomeip/blob/714907ec5b146dbf48373b72a32fd838e26402a5/src/transport/Session.cpp#L76

Comment (Damian-Nordic) [reply src/transport/SecureSession.h:199]: But notice that if you pass `false` here then passing `kZero` in `ReadCient` does nothing, so this comment ("Peer will assume we are idle (hence we pass kZero to GetMessageReceiptTimeout())") becomes irrelevant. That is, we will always calculate the receipt time as if the peer thought we were active.

Comment (yunhanw-google) [reply src/transport/SecureSession.h:199]: yes, it is, I would prefer follow-up comment improvement on this part, thanks

Comment (bzbarsky-apple) [reply src/transport/SecureSession.h:199]: Hmm.  So the API documentation for GetMessageReceiptTimeout says:

```
    // GetReceiptTimeout is the estimate for how long it could take for us to
    // receive a message after the other side sends it, accounting for the MRP
    // retransmits the other side might do if the message gets lost.
```

which I thought would mean it's always a response but of course @Damian-Nordic is right and ReadClient is using it for the initial message from the other side.  So this PR can't go in as-is, because it would in fact mis-compute things there and then subscriptions would not work right.

Maybe the right thing is for GetMessageReceiptTimeout to lose the timestamp bit entirely, because the only values we pass are zero to indicate "initial message" and "now" to indicate "a response", and instead have an actual `isFirstMessageOnExchange` boolean arg on GetMessageReceiptTimeout?  This would be false in ReadClient, true in the one other caller in Session.cpp...  I guess `GetRetransmissionTimeout` still takes a "last activity" thing, but that could be computed in the implementation of GetMessageReceiptTimeout: zero if isFirstMessageOnExchange, now otherwise?

Comment (bzbarsky-apple) [reply src/transport/SecureSession.h:199]: Alternately, we could in fact add a boolean arg to GetMessageReceiptTimeout and just pass it through, after fixing the two callsites, and then do a followup to figure out whether we can fix GetRetransmissionTimeout to not require the activity time or something...

Comment (yunhanw-google) [reply src/transport/SecureSession.h:199]: updated to add a boolean arg to GetMessageReceiptTimeout,  I think we need set isFirstMessageOnExchange as **true** in readClient, set isFirstMessageOnExchange as **false** in one 

> instead have an actual isFirstMessageOnExchange boolean arg on GetMessageReceiptTimeout? This would be **false** in ReadClient, **true** in the one other caller in Session.cpp

**Review by Damian-Nordic — APPROVED** [review]

File: src/transport/SecureSession.h (hunk 23 above)
Comment (Damian-Nordic) [reply src/transport/SecureSession.h]: Thanks for fixing this. I agree with Boris that perhaps the timestamp argument in GetMessageReceiptTimeout is not really needed anymore, but it can be removed in a followup as well.

Comment (bzbarsky-apple) [reply src/transport/SecureSession.h]: > I think we need set isFirstMessageOnExchange as true in readClient, set isFirstMessageOnExchange as false in session side

Yes, sorry, I had it backwards above......

File: src/transport/Session.cpp [hunk 24]
```diff
@@ -71,10 +71,10 @@ System::Clock::Timeout Session::ComputeRoundTripTimeout(System::Clock::Timeout u
         return System::Clock::kZero;
     }
 
-    // Treat us as active for purposes of GetMessageReceiptTimeout(), pass false into GetAckTimeout to
+    // Treat us as active for purposes of GetMessageReceiptTimeout(), pass false into GetAckTimeout and GetMessageReceiptTimeout to
     // indicate we are processing non-initial message since the other side would be responding to our message.
     return GetAckTimeout(false /*isFirstMessageOnExchange*/) + upperlayerProcessingTimeout +
```
Comment (bzbarsky-apple) [inline src/transport/Session.cpp:76]: So hold on.  Now that I am re-reading this... (and I am sorry we keep going back and forth):

1. GetAckTimeout is how long we expect the message from us to them to take, right?
2. GetMessageReceiptTimeout is how long we expect the message from them to us to take.

For the second one, isFirstMessageOnExchange should definitely be false, since it's responding to our message.

But for the first (GetAckTimeout....  isFirstMessageOnExchange needs to be set based on whether we are computing the roundtrip bits for the first message on the exchange or not, no?

I thought this had gotten fixed in https://github.com/project-chip/connectedhomeip/pull/37696#discussion_r1985465438 so what exactly is going on here?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/transport/Session.cpp (hunk 24 above)
Comment (bzbarsky-apple) [reply src/transport/Session.cpp:76]: > [force-pushed](https://github.com/project-chip/connectedhomeip/compare/c3a4999a123991f547e8bd9bfa08817fc0d833c5..e3fad9b13b5c62f0fa73b014341f2b1810d932a7) the feature/case_lit_timeout branch from [c3a4999](https://github.com/project-chip/connectedhomeip/commit/c3a4999a123991f547e8bd9bfa08817fc0d833c5) to [e3fad9b](https://github.com/project-chip/connectedhomeip/commit/e3fad9b13b5c62f0fa73b014341f2b1810d932a7)

This is where the broken came in.  See https://github.com/project-chip/connectedhomeip/blob/c3a4999/src/transport/Session.h#L279-L280 which has the right signature, but then it went away.

Comment (yunhanw-google) [reply src/transport/Session.cpp:76]: i use vscode github UI to checkout the multiple PRs, somehow it create a new branch automatically with same PRs during PR switches..and lose the right change sets....

working on the right branch

Comment (yunhanw-google) [reply src/transport/Session.cpp]: I locate the right branch, and compared it against the last comments you make when you mark the previous approval, and add the latest change that fix GetMessageReceiptTimeou

**Review by bzbarsky-apple — APPROVED** [review]
