### PR TITLE
Bridge-app: Add actions delegate in the Bridge app

### LINKED ISSUE #36938: [All-Bridge-App] Add support of Actions cluster for asr, telink, esp32 apps
### Reproduction steps

With #35568, the Actions cluster support has been removed from some platforms. When the PR gets merged, raise a follow-up to add support for the Actions in asr, telink, esp32 bridge app.

### Platform

other

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jadhavrohit924**
#### Problem

- Fixes: https://github.com/project-chip/connectedhomeip/issues/36938

#### Testing

- Tested read attribute and invoke commands on bridge-app for esp32.
- Relying on CI to build for other platforms.

### CODE REVIEW

**Review by s07641069 — APPROVED** [review]

File: examples/bridge-app/asr/src/AppTask.cpp [hunk 1]
```diff
@@ -62,6 +66,20 @@ void NetWorkCommissioningInstInit()
     emberAfEndpointEnableDisable(kNetworkCommissioningEndpointSecondary, false);
 }
 
+void emberAfActionsClusterInitCallback(EndpointId endpoint)
+{
+    VerifyOrReturn(endpoint == 1,
+                   ChipLogError(Zcl, "Actions cluster delegate is not implemented for endpoint with id %d.", endpoint));
+    VerifyOrReturn(emberAfContainsServer(endpoint, app::Clusters::Actions::Id) == true,
+                   ChipLogError(Zcl, "Endpoint %d does not support Actions cluster.", endpoint));
```
Comment (shubhamdp) [inline examples/bridge-app/asr/src/AppTask.cpp:74]:
```suggestion
                   ChipLogError(Zcl, "Endpoint %u does not support Actions cluster.", endpoint));
```

File: examples/bridge-app/bridge-common/include/bridged-actions-stub.h [hunk 2]
```diff
@@ -0,0 +1,80 @@
+/*
+ *
+ *    Copyright (c) 2024 Project CHIP Authors
```
Comment (shubhamdp) [inline examples/bridge-app/bridge-common/include/bridged-actions-stub.h:3]:
```suggestion
 *    Copyright (c) 2025 Project CHIP Authors
```

File: examples/bridge-app/bridge-common/src/bridged-actions-stub.cpp [hunk 3]
```diff
@@ -0,0 +1,131 @@
+/*
+ *
+ *    Copyright (c) 2024 Project CHIP Authors
```
Comment (shubhamdp) [inline examples/bridge-app/bridge-common/src/bridged-actions-stub.cpp:3]:
```suggestion
 *    Copyright (c) 2025 Project CHIP Authors
```

File: examples/bridge-app/esp32/main/main.cpp [hunk 4]
```diff
@@ -395,6 +399,20 @@ static void InitServer(intptr_t context)
                       Span<DataVersion>(gLight2DataVersions), 1);
 }
 
+void emberAfActionsClusterInitCallback(EndpointId endpoint)
+{
+    VerifyOrReturn(endpoint == 1,
+                   ChipLogError(Zcl, "Actions cluster delegate is not implemented for endpoint with id %d.", endpoint));
+    VerifyOrReturn(emberAfContainsServer(endpoint, app::Clusters::Actions::Id) == true,
+                   ChipLogError(Zcl, "Endpoint %d does not support Actions cluster.", endpoint));
```
Comment (shubhamdp) [inline examples/bridge-app/esp32/main/main.cpp:407]:
```suggestion
                   ChipLogError(Zcl, "Endpoint %u does not support Actions cluster.", endpoint));
```

File: examples/bridge-app/telink/src/AppTask.cpp [hunk 5]
```diff
@@ -23,15 +23,33 @@
...
+std::unique_ptr<chip::app::Clusters::Actions::ActionsDelegateImpl> sActionsDelegateImpl;
+std::unique_ptr<chip::app::Clusters::Actions::ActionsServer> sActionsServer;
 } // namespace
 
+void emberAfActionsClusterInitCallback(chip::EndpointId endpoint)
+{
+    VerifyOrReturn(endpoint == 1,
+                   ChipLogError(Zcl, "Actions cluster delegate is not implemented for endpoint with id %d.", endpoint));
+    VerifyOrReturn(emberAfContainsServer(endpoint, chip::app::Clusters::Actions::Id) == true,
+                   ChipLogError(Zcl, "Endpoint %d does not support Actions cluster.", endpoint));
```
Comment (shubhamdp) [inline examples/bridge-app/telink/src/AppTask.cpp:44]:
```suggestion
                   ChipLogError(Zcl, "Endpoint %u does not support Actions cluster.", endpoint));
```

**Review by shubhamdp — APPROVED** [review]

**Review by s07641069 — APPROVED** [review]

File: examples/bridge-app/bridge-common/include/bridged-actions-stub.h [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+private:
+    std::vector<ActionStructStorage> kActionList = {
+        ActionStructStorage(0, CharSpan::fromCharString("TurnOnLight"), ActionTypeEnum::kScene, 0, 0, ActionStateEnum::kInactive),
+        ActionStructStorage(1, CharSpan::fromCharString("TurnOffLight"), ActionTypeEnum::kScene, 1, 0, ActionStateEnum::kInactive),
+        ActionStructStorage(2, CharSpan::fromCharString("ToggleLight"), ActionTypeEnum::kScene, 2, 0, ActionStateEnum::kInactive)
+    };
+
+    std::vector<EndpointId> firstEpList  = { 0 };
+    std::vector<EndpointId> secondEpList = { 0, 1 };
+    std::vector<EndpointId> thirdEpList  = { 1, 2, 3 };
```
[the remark this answers is not in the document]
Comment (jadhavrohit924) [reply examples/bridge-app/bridge-common/include/bridged-actions-stub.h]: Removed EP0.

**Review by tcarmelveilleux — APPROVED** [review]
