### PR TITLE
[Darwin] Issue 26012 - MTRDevice should stream subscription reports

### LINKED ISSUE #26012: [Darwin] Subscription reports should be streamed rather than wait for OnReportEnd
### Reproduction steps

Currently both MTRDevice and MTRBaseDevice subscriptions report at OnReportEnd time. Given SubscriptionCallback is using Buffered callback, all OnXData calls should be complete and reportable.

We should stream the reports for more responsive subscriptions.

### Platform

darwin

### Platform Version(s)

1.0

### Type

Platform validated

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jtung-apple**
Fixes #26012 

This PR makes the MTRDevice.mm's SubscriptionCallback reports attributes immediately without waiting for OnReportEnd.

This does mean that the `MTRDeviceDelegate` will be getting individual callbacks for each attribute and event, and so I have filed a separate issue for optimizing that part: https://github.com/project-chip/connectedhomeip/issues/29357

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRDevice.mm
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:1]: So with this change, MTRDevice just does not use `mAttributeReports` and `mEventReports` at all, right?

What I am wondering is this: can we not get the coalescing we want without any core ReadClient changes per https://github.com/project-chip/connectedhomeip/issues/29357 by:

1. Whenever we get a report, queue something _on the Matter queue_ (to avoid races) to report things.
2. When that thing runs, if the arrays are nonempty replace them with empty arrays (not nil, because more reports will be coming in, since we have not hit the `ReportData` call from `OnReportEnd` or `OnError`) and report the currently batched up values.

Since the reporting is async, it automatically coalesces across all the reports in a single packet.

Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:1]: > So with this change, MTRDevice just does not use mAttributeReports and mEventReports at all, right?
Yup.

And on your suggestion of queuing a "report if exists" on the Matter queue:

While it works functionally for layering purpose, it still incurs a per-attribute/event cost of queuing a block and the dispatch system running it, which could be up to hundreds of times for priming report per device. That said, these blocks are not jumping queues and has a chance of very quickly getting executed on-thread without much perf degradation.

Having a concrete batch boundary callback per #29357 would make this signal explicit.

In any case, there is also the possibility that not batching at all works well enough, and we won't need either of these optimizations.

Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:1]: > it still incurs a per-attribute/event cost of queuing a block and the dispatch system running it,

No, it's per-packet cost, in the sense that we can track when the block is queued and not queue another one, right?

So effectively you have your own packet start state (block has not been queued) and packet end state (block runs).

We _can_ add more logic to ReadClient and ReadCallback, but that affects constrained-memory devices too, some of which have to deal with reads, so I would really rather not do that if we can avoid it....

Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:1]: Hmm I see, you mean queue something OnReportBegin, and then this something would report interim data, allocate the arrays, and then queue itself again. And to break cycle it'll just exit without queuing if both arrays are nil.

Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:1]: Made a version that queues the interim report block if it hasn't been queued yet, and added block cancellation when OnReportEnd and in destructor, to prevent useless or dangerous invocations.

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 1]
```diff
@@ -429,6 +433,15 @@ - (void)_handleReportEnd
 {
     os_unfair_lock_lock(&self->_lock);
     _estimatedStartTimeFromGeneralDiagnosticsUpTime = nil;
+// For unit testing only
+#ifdef DEBUG
+    id delegate = _weakDelegate.strongObject;
+    if (delegate && [delegate respondsToSelector:@selector(unitTestReportEndForDevice:)]) {
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:439]: I would be much happier if we did the respondsToSelector check inside the async block, because calling out into arbitrary code with our lock held seems scary.

I know this is debug-only, etc, but still.

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 2]
```diff
@@ -187,6 +187,10 @@ @interface MTRDevice ()
 
 @end
 
+@protocol MTRDeviceUnitTestDelegate <MTRDeviceDelegate>
+- (void)unitTestReportEndForDevice:(MTRDevice *)device;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:191]: I assume this protocol declaration is needed just so `@selector(unitTestReportEndForDevice:)` doesn't error out?  Might be worth documenting that.

File: src/darwin/Framework/CHIPTests/MTRDeviceTests.m [hunk 3]
```diff
@@ -1457,6 +1465,8 @@ - (void)test017_TestMTRDeviceBasics
                 XCTAssertNotNil(eventDict[MTREventTimestampDateKey]);
             }
         }
+    };
+    delegate.onReportEnd = ^() {
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIPTests/MTRDeviceTests.m:1469]: Hmm.  Pre-existing, but I think at the end of this test when we are doing `[self waitForExpectations:@[ resubscriptionExpectation ] timeout:60];` (around line 1601 after this PR) we should in fact be waiting until report end, not just reachability, I think.  Followup to fix that, please?

**Review by bzbarsky-apple — APPROVED** [review]

File: src/darwin/Framework/CHIPTests/MTRDeviceTests.m (hunk 3 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIPTests/MTRDeviceTests.m:1469]: Filed https://github.com/project-chip/connectedhomeip/issues/29365

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 1 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:439]: This code is doing:
1. A pre-flight check that the delegate responds to the unit test callback
2. Schedule a block on a different queue.

And so the arbitrary unit test code won't be run while holding the MTRDevice lock.

This is actually really clean and not problematic.

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 2 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:193]: Done.

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 1 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:442]: I see what you mean. I've made the change.

**Comment by bzbarsky-apple** [comment]
Fast-tracking platform-specific change with platform owner review.
