### PR TITLE
Don't expire failsafe when commissioning window closes

### LINKED ISSUE #19678: Closing the commissioning window should not expire fail-safe
#### Problem
With Max Cumulative Fail safe timer created we now should no longer expire the failsafe timer when the commission window closes either due to open window timeout or RevokeCommissioning command

### PR DESCRIPTION
**Pull request by tehampson**
#### Problem
*Fixes https://github.com/project-chip/connectedhomeip/issues/19678

#### Change overview
No longer expire the failsafe timer when the commission window closes either due to open window timeout or RevokeCommissioning command

#### Testing
* Github CI
* Did the following process:
  * Terminal 1:
    * `chip-tool pairing onnetwork 1 20202021`
    * `chip-tool pairing open-commissioning-window 1 0 200 1000 3840`
  * Terminal 2:
    * `chip-tool interactive start`
      * `pairing code-paseonly 17 749701123365521327694`
  * Terminal 1:
    * `chip-tool administratorcommissioning revoke-commissioning 1 0 --timedInteractionTimeoutMs 1000`
  * Terminal 2 (in interactive shell):
      * `generalcommissioning arm-fail-safe 60 0 17 0`
      * Confirmed command goes through, previously on the `revoke-commissioning` fail-safe would trigger and this command would never send

### CODE REVIEW

File: src/app/server/CommissioningWindowManager.cpp [hunk 1]
```diff
@@ -274,7 +277,7 @@ CHIP_ERROR CommissioningWindowManager::OpenBasicCommissioningWindow(Seconds16 co
     CHIP_ERROR err = OpenCommissioningWindow(commissioningTimeout);
     if (err != CHIP_NO_ERROR)
     {
-        Cleanup();
+        Cleanup(/* expireFailSafeTimer */ true);
```
Comment (bzbarsky-apple) [inline src/app/server/CommissioningWindowManager.cpp:280]: Again, I don't think that there's going to be a fail-safe armed at this point.  The OpenBasicCommissioningWindow command cannot be issued while a fail-safe is live, and opening a window at boot time or whatnot would not have a live fail-safe.

File: src/app/server/CommissioningWindowManager.cpp [hunk 2]
```diff
@@ -305,7 +308,7 @@ CHIP_ERROR CommissioningWindowManager::OpenEnhancedCommissioningWindow(Seconds16
...
```
Comment (bzbarsky-apple) [inline src/app/server/CommissioningWindowManager.cpp:311]: Likewise, I don't think a fail-safe can be armed here.

**Review by bzbarsky-apple — APPROVED** [review]
I think the `ExpireFailSafeIfArmed()` call in Cleanup() can just go away altogether, based on these callsites...

File: src/app/server/CommissioningWindowManager.cpp (hunk 2 above)
Comment (tehampson) [reply src/app/server/CommissioningWindowManager.cpp]: All the times I set it to true here I just figured it would be safe to disable since we only do it if fail-safe is enabled. But you've made a very compelling argument that these should all be false so we can entirely remove if from the Cleanup(). I also made Cleanup() private now since we have only used it internally

**Review by bzbarsky-apple — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Comment by tehampson** [comment]
I was wondering if anyone had a recommendation on how to use chip-tool to test this PR

I tried to do something with chip-repl today and that didn't work out. I tried messing around with chip-tool and hitting issue with revoking-commissioning. I was thinking something along the lines of (not even sure if step 2 is doing what I think it is doing):

1. Terminal 1:
  * `chip-tool pairing onnetwork 1 20202021`
  * `chip-tool pairing open-commissioning-window 1 0 200 1000 3840`

2. Terminal 2:
  * `chip-tool interactive start`
    * `pairing code-paseonly 17 749701123365521327694`

3. Terminal 1:
  * `chip-tool administratorcommissioning revoke-commissioning 1 0`

But the revoke command is failing here

**Comment by bzbarsky-apple** [comment]
>    pairing code-paseonly 17 749701123365521327694

You probably want to throw `--commissioner-name beta` on there.

>   chip-tool administratorcommissioning revoke-commissioning 1 0

This needs a `--timedInteractionTimeoutMs` argument to not error out.
