### PR TITLE
Modifying ReplacementProductListManager to be generic

### LINKED ISSUE #28148: [1.2] ReplacemenProductListManager is assuming static memory allocation
### Reproduction steps

The API looks like this:
```
    virtual CHIP_ERROR Next(Attributes::ReplacementProductStruct::Type & item) = 0;
```

But that struct has a CharSpan inside, and how does the callee know when it's safe to free the memory the CharSpan is pointing to?  It doesn't.

We need to stop using "static stick it all in memory" implementations to back our delegate APIs, unless we really expect all applications to do it that way....

@cliffamzn @tcarmelveilleux @chrisdecenzo 

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

d2d4701

### Platform

core

### Platform Version(s)

_No response_

### Type

Common Cluster Logic

### Anything else?

@cliffamzn I suggest doing one of two things.  Either have separate getters for the separate parts of the struct, or have a struct type that _includes storage_ so that you can put one on the stack and the callee can copy the data into it.  The latter is what I had been suggesting you do on Slack, if you recall: inherit from one of the generated structs, pull in any method definitions, adapt your subclass for your needs...

### PR DESCRIPTION
**Pull request by cliffamzn**
Addressing feedback from PR #28095 and also addressing #28148

Tested to ensure functionality still works as expected using the all-clusters-app as well as the resource-monitoring-app

### CODE REVIEW

**Review by chrisdecenzo — APPROVED** [review]

File: src/app/clusters/resource-monitoring-server/replacement-product-list-manager.h [hunk 1]
```diff
@@ -39,10 +39,7 @@ class ReplacementProductListManager
 
     void Reset() { mIndex = 0; }
 
-    // Returns total size of Replacement Products List.
-    virtual uint8_t Size() = 0;
-
-    virtual CHIP_ERROR Next(Attributes::ReplacementProductStruct::Type & item) = 0;
+    virtual CHIP_ERROR Next(Attributes::GenericReplacementProductStruct::GenericType & item) = 0;
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/replacement-product-list-manager.h:42]: This needs to:

1. Document how the callee indicates "end of list" properly.
2. Document what the memory ownership contract is around the outparam.

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h [hunk 2]
```diff
@@ -141,37 +141,39 @@ struct TypeInfo
 };
 } // namespace LastChangedTime
 
-namespace ReplacementProductStruct {
+namespace GenericReplacementProductStruct {
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:144]: Do we even need this deep namespace nesting?  Seems like we could just define a GenericReplacementProductStruct as a struct right in the ResourceMonitoring namespace....

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h [hunk 3]
```diff
@@ -141,37 +141,39 @@ struct TypeInfo
...
 enum class Fields : uint8_t
 {
     kProductIdentifierType  = 0,
     kProductIdentifierValue = 1,
 };
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:149]: I suspect these are not needed at all; see below.

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h [hunk 4]
```diff
@@ -141,37 +141,39 @@ struct TypeInfo
...
 
-struct Type
+class GenericType : protected app::Clusters::HepaFilterMonitoring::Structs::ReplacementProductStruct::Type
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:151]:
```suggestion
// A struct used during reads of the ReplacementProductList to store a single list instance we request
// from the application.
// 
// Inherit from an auto-generated struct to pick up the implementation bits, but make
// it private inheritance so people can't accidentally use this struct where the other
// is expected.
class GenericType : private HepaFilterMonitoring::Structs::ReplacementProductStruct::Type
```

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h [hunk 5]
```diff
@@ -141,37 +141,39 @@ struct TypeInfo
...
 {
-public:
-    ProductIdentifierTypeEnum productIdentifierType = static_cast<ProductIdentifierTypeEnum>(0);
+private:
+    ResourceMonitoring::ProductIdentifierTypeEnum productIdentifierType;
     chip::CharSpan productIdentifierValue;
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:155]: Why are these members needed?  The super-class has them already.....

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h [hunk 6]
```diff
@@ -141,37 +141,39 @@ struct TypeInfo
...
 
-    CHIP_ERROR Decode(TLV::TLVReader & reader);
-
+public:
+    GenericType() {}
+    GenericType(ResourceMonitoring::ProductIdentifierTypeEnum aProductIdentifierType, chip::CharSpan aProductIdentifierValue)
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:159]: Is this used?

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h [hunk 7]
```diff
@@ -141,37 +141,39 @@ struct TypeInfo
...
+    {
+        productIdentifierType  = aProductIdentifierType;
+        productIdentifierValue = aProductIdentifierValue;
+    }
+    virtual ~GenericType()                = default;
     static constexpr bool kIsFabricScoped = false;
-
     CHIP_ERROR Encode(TLV::TLVWriter & writer, TLV::Tag tag) const;
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:166]: Why is this not just:
```suggestion
    using HepaFilterMonitoring::Structs::ReplacementProductStruct::Type::Encode;
```
instead of reimplementing things?

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h [hunk 8]
```diff
@@ -141,37 +141,39 @@ struct TypeInfo
...
 };
-
-using DecodableType = Type;
-
-} // namespace ReplacementProductStruct
+} // namespace GenericReplacementProductStruct
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:168]: This struct needs to have a buffer for the character data the CharSpan is pointed too.  It should probably have setters for the type and value; type assigns to the type member, value (a fallible setter!) copies the data into the internal buffer and points the charspan to that buffer.

In particular, this PR in its current form does _not_ address https://github.com/project-chip/connectedhomeip/issues/28148.

I would strongly urge you to exercise this logic by having this attribute return _not_ static data in some cases.  And add tests!

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h [hunk 9]
```diff
@@ -141,37 +141,39 @@ struct TypeInfo
...
 
 namespace ReplacementProductList {
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:170]: I suspect this whole namespace is entirely unneeded.

File: src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp [hunk 10]
```diff
@@ -197,6 +197,12 @@ Status Instance::OnResetCondition()
         }
     }
 
+    ReplacementProductListManager * productListManagerInstance = Instance::GetReplacementProductListManagerInstance();
+    if (nullptr != productListManagerInstance)
+    {
+        productListManagerInstance->Reset();
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp:203]: Why?  This Reset means "we will now be starting at the beginning of the list".... but it's only relevant for reads of the attribute.  Why are we doing it here.

File: src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp [hunk 11]
```diff
@@ -244,8 +250,8 @@ CHIP_ERROR Instance::EnumerateAcceptedCommands(const ConcreteClusterPath & clust
 
 CHIP_ERROR Instance::ReadReplacableProductList(AttributeValueEncoder & aEncoder)
 {
-    CHIP_ERROR err;
-    if (Instance::HasFeature(ResourceMonitoring::Feature::kReplacementProductList))
+    CHIP_ERROR err = CHIP_NO_ERROR;
+    if (HasFeature(ResourceMonitoring::Feature::kReplacementProductList))
     {
         ReplacementProductListManager * productListManagerInstance = Instance::GetReplacementProductListManagerInstance();
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp:256]:
```suggestion
        ReplacementProductListManager * productListManagerInstance = GetReplacementProductListManagerInstance();
```

File: src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp [hunk 12]
```diff
@@ -257,15 +263,17 @@ CHIP_ERROR Instance::ReadReplacableProductList(AttributeValueEncoder & aEncoder)
         productListManagerInstance->Reset();
 
         err = aEncoder.EncodeList([&](const auto & encoder) -> CHIP_ERROR {
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp:265]:
```suggestion
        err = aEncoder.EncodeList([productListManagerInstance](const auto & encoder) -> CHIP_ERROR {
```

File: src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp [hunk 13]
```diff
@@ -257,15 +263,17 @@ CHIP_ERROR Instance::ReadReplacableProductList(AttributeValueEncoder & aEncoder)
...
-            Attributes::ReplacementProductStruct::Type replacementProductStruct;
-            while (productListManagerInstance->Next(replacementProductStruct) == CHIP_NO_ERROR)
+            Attributes::GenericReplacementProductStruct::GenericType replacementProductStruct;
+            CHIP_ERROR iteratorError = CHIP_NO_ERROR;
+            while (CHIP_NO_ERROR == iteratorError)
             {
                 ReturnErrorOnFailure(encoder.Encode(replacementProductStruct));
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp:270]: Has this been tested?  This does not look like it does the right thing.  Please test this code.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h (hunk 6 above)
Comment (cliffamzn) [reply src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:161]: This is used in the examples

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h (hunk 8 above)
Comment (cliffamzn) [reply src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h]: Modified this and also added a test for it

File: src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp (hunk 13 above)
Comment (cliffamzn) [reply src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp:265]: Tested manually, had missed the bug. Added a test for this as well

File: src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp (hunk 10 above)
Comment (cliffamzn) [reply src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp]: Removed

File: src/app/clusters/resource-monitoring-server/replacement-product-list-manager.h [hunk 14]
```diff
@@ -34,15 +34,24 @@ namespace ResourceMonitoring {
 class ReplacementProductListManager
 {
 public:
+    static constexpr size_t kReplacementProductListMaxSize = 5u;
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/replacement-product-list-manager.h:37]: Please document that this is the max length defined in the spec.

File: src/app/clusters/resource-monitoring-server/replacement-product-list-manager.h [hunk 15]
```diff
@@ -34,15 +34,24 @@ namespace ResourceMonitoring {
...
     virtual ~ReplacementProductListManager() = default;
 
     void Reset() { mIndex = 0; }
 
-    // Returns total size of Replacement Products List.
-    virtual uint8_t Size() = 0;
-
-    virtual CHIP_ERROR Next(Attributes::ReplacementProductStruct::Type & item) = 0;
+    /**
+     * Iterates through the entries in the ReplacementProductListManager. Each call to this function move the list pointer to the
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/replacement-product-list-manager.h:45]: No, each call _copies the next item into the outparam_.  There are no pointers moving here.

File: src/app/clusters/resource-monitoring-server/replacement-product-list-manager.h [hunk 16]
```diff
@@ -34,15 +34,24 @@ namespace ResourceMonitoring {
...
+     * next element. Calls to this function will return CHIP_NO_ERROR if there are still valid elements in the list. The function
+     * will return CHIP_ERROR_PROVIDER_LIST_EXHAUSTED if the end of the list has been reached.
+     *
+     * @param[out] item An out parameter that is populated with the address of the item in the list. Will be empty if there are no
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/replacement-product-list-manager.h:49]: No, it's not populated with the address of anything....

File: src/app/clusters/resource-monitoring-server/replacement-product-list-manager.h [hunk 17]
```diff
@@ -34,15 +34,24 @@ namespace ResourceMonitoring {
...
+     * remaining items in the list. In normal circumstances this parameter should never be modified.
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/replacement-product-list-manager.h:50]: I don't understand what "should never be modified" means.  The whole point is the callee needs to modify it.

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h [hunk 18]
```diff
@@ -29,7 +29,9 @@ namespace app {
 namespace Clusters {
 namespace ResourceMonitoring {
 
-static constexpr std::array<ClusterId, 2> AliasedClusters = { HepaFilterMonitoring::Id, ActivatedCarbonFilterMonitoring::Id };
+// max of 20 characters + 1 for null terminator
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:32]: Why is there a null terminator involved?  There should be no null terminators involved.

Please document that the 20 comes from the constraint on ProductIdentifierValue in the spec.

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h [hunk 19]
```diff
@@ -141,37 +143,72 @@ struct TypeInfo
...
 
-namespace ReplacementProductStruct {
-enum class Fields : uint8_t
+// A struct used during reads of the ReplacementProductList to store a single list instance we request
+// from the application.
+//
+// Inherit from an auto-generated struct to pick up the implementation bits, but make
+// it private inheritance so people can't accidentally use this struct where the other
+// is expected.
+struct GenericType : private HepaFilterMonitoring::Structs::ReplacementProductStruct::Type
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:152]: `Attributes::GenericType` is a very odd place to put this.

How about putting it under `Clusters::ResourceMonitoring` and calling it `ReplacementProductStruct`?  That would have the virtue of matching the spec.

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h [hunk 20]
```diff
@@ -141,37 +143,72 @@ struct TypeInfo
...
+    }
+
+    using HepaFilterMonitoring::Structs::ReplacementProductStruct::Type::Encode;
+
+    /**
+     * Sets the product identifier type.
+     *
+     * @param aProductIdentifierType The product identifier type.
+     */
+    void setProductIdentifierType(ResourceMonitoring::ProductIdentifierTypeEnum aProductIdentifierType)
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:174]:
```suggestion
    void SetProductIdentifierType(ResourceMonitoring::ProductIdentifierTypeEnum aProductIdentifierType)
```
and similar for other functions.

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h [hunk 21]
```diff
@@ -141,37 +143,72 @@ struct TypeInfo
...
+    {
+        productIdentifierType = static_cast<HepaFilterMonitoring::ProductIdentifierTypeEnum>(aProductIdentifierType);
+    }
+
+    /**
+     * Sets the product identifier value.
+     * This implementation will copy the argument to the local implementation.
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:181]:
```suggestion
     * This implementation will copy the argument into this struct's buffer.
```

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h [hunk 22]
```diff
@@ -141,37 +143,72 @@ struct TypeInfo
...
+     *
+     * @param aProductIdentifierValue The value of the product identifier to set.
+     * @return CHIP_ERROR_INVALID_ARGUMENT when aProductIdentifierValue is invalid, CHIP_NO_ERROR otherwise.
+     */
+    CHIP_ERROR setProductIdentifierValue(chip::CharSpan aProductIdentifierValue)
+    {
+        VerifyOrReturnError(IsSpanUsable(aProductIdentifierValue), CHIP_ERROR_INVALID_ARGUMENT);
+
+        if (aProductIdentifierValue.size() > sizeof(productIdentifierValueBuffer))
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:190]: This should also return CHIP_ERROR_INVALID_ARGUMENT instead of silently truncating.

File: src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h [hunk 23]
```diff
@@ -141,37 +143,72 @@ struct TypeInfo
...
+    }
 };
 
-using DecodableType = Type;
-
-} // namespace ReplacementProductStruct
-
 namespace ReplacementProductList {
 static constexpr AttributeId Id = 0x00000005;
 struct TypeInfo
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-cluster-objects.h:207]: I am very certain you do not need this TypeInfo thing at all, actually.  It's only used on the client side.

File: examples/resource-monitoring-app/resource-monitoring-common/src/instances/HepafilterMonitoring.cpp [hunk 24]
```diff
@@ -31,29 +31,28 @@
...
-    { .productIdentifierType  = ResourceMonitoring::ProductIdentifierTypeEnum::kEan,
-      .productIdentifierValue = CharSpan::fromCharString("4444455555666") },
-    { .productIdentifierType  = ResourceMonitoring::ProductIdentifierTypeEnum::kGtin14,
-      .productIdentifierValue = CharSpan::fromCharString("gtin14xhepaxxx") },
-    { .productIdentifierType  = ResourceMonitoring::ProductIdentifierTypeEnum::kOem,
-      .productIdentifierValue = CharSpan::fromCharString("oem20xhepaxxxxxxxxxx") },
-};
-StaticReplacementProductListManager sHepaFilterReplacementProductListManager(&sHepaFilterReplacementProductsList[0],
-                                                                             ArraySize(sHepaFilterReplacementProductsList));
+DynamicReplacementProductListManager mHepaFilterReplacementProductListManager;
```
Comment (bzbarsky-apple) [inline examples/resource-monitoring-app/resource-monitoring-common/src/instances/HepafilterMonitoring.cpp:37]: Why "m" prefix?  This is not an instance member....

File: examples/resource-monitoring-app/resource-monitoring-common/src/ReplacementProductListManager.cpp [hunk 25]
```diff
@@ -25,7 +26,19 @@
 using namespace chip::app::Clusters;
 using namespace chip::app::Clusters::ResourceMonitoring;
 
-CHIP_ERROR StaticReplacementProductListManager::Next(Attributes::ReplacementProductStruct::Type & item)
+CHIP_ERROR StaticReplacementProductListManager::Next(Attributes::GenericType & item)
+{
+    if (mIndex < mReplacementProductListSize)
+    {
+        item = mReplacementProductsList[mIndex];
```
Comment (bzbarsky-apple) [inline examples/resource-monitoring-app/resource-monitoring-common/src/ReplacementProductListManager.cpp:33]: This actually does not do the right thing, and the only reason it works is because this is returning pointers into infinite-lifetime data.  Please think through where the pointers in `item` end up pointing after this assignment.

The key thing that the "dynamic" case should test is not the "we dynamically built the infinite-lifetime list situation" but the "we read this from flash when asked" situation.  That is, a stack buffer for the string, that then gets filled with the string read from somewhere else, and then we want to hand it out to the caller.

File: examples/resource-monitoring-app/resource-monitoring-common/include/DynamicReplacementProductListManager.h [hunk 26]
```diff
@@ -0,0 +1,63 @@
...
+/**
+ * This implementation allows for items to be added dynamically.
+ */
+
+class DynamicReplacementProductListManager : public ReplacementProductListManager
+{
+public:
+    CHIP_ERROR Next(Attributes::GenericType & item) override;
+
+    CHIP_ERROR addItemToList(ResourceMonitoring::ProductIdentifierTypeEnum aProductIdentifierType,
```
Comment (bzbarsky-apple) [inline examples/resource-monitoring-app/resource-monitoring-common/include/DynamicReplacementProductListManager.h:39]:
```suggestion
    CHIP_ERROR AddItemToList(ResourceMonitoring::ProductIdentifierTypeEnum aProductIdentifierType,
```

File: src/app/clusters/resource-monitoring-server/replacement-product-list-manager.h (hunk 17 above)
Comment (cliffamzn) [reply src/app/clusters/resource-monitoring-server/replacement-product-list-manager.h:50]: I'll remove this statement, in general i don't expect this would be modified at all, i would expect that the device implementing this cluster would have a static list of these replacement products that doesn't change. I don't think there's really a use case where this changes dynamically that we've identified.

File: src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp [hunk 27]
```diff
@@ -300,7 +300,7 @@ CHIP_ERROR Instance::Read(const ConcreteReadAttributePath & aPath, AttributeValu
         ReturnErrorOnFailure(aEncoder.Encode(mLastChangedTime));
         break;
     }
-    case Attributes::ReplacementProductList::Id: {
+    case HepaFilterMonitoring::Attributes::ReplacementProductList::TypeInfo::GetAttributeId(): {
```
Comment (bzbarsky-apple) [inline src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp:303]: This is worth a comment explaining why the HepaFilterMonitoring bit is being used.  Or you could leave the definition of `Attributes::ReplacementProductList::Id` around.....

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp (hunk 27 above)
Comment (cliffamzn) [reply src/app/clusters/resource-monitoring-server/resource-monitoring-server.cpp]: Decided to leave the definition around, makes the code easier to read since all the other attributes are listed there as well
