### PR TITLE
Clear exchange context when subscription liveness timeout

### LINKED ISSUE #10047: [TE6] Subscriptions: Crash/Abort when Subscription is terminated (or when Liveness Times out)
#### Problem
When a subscription is considered terminated after the schedule report exceeds the Maximum Interval Ceiling, the Callback that is fired (`OnLivenessTimeoutCallback`) results in a crash/abort. To reproduce this issue, establish a Subscription with a Node, and turn off the Node (Publisher) to stop the Node(Publisher) from reporting which should result in the Liveness Time to trigger once it exceeds the Maximum Interval Ceiling. 

`ReadClient::OnLivenessTimeoutCallback()` will attempt to propagate the timeout to the delegate (IM Engine) which results in an Abort when attempting to get the Secure Session of the ReadClient's Exchange Context in the following function that Gets Call Through (`OnLivenessTimeoutCallback` -> `ReadClient::ShutdownInternal()` -> `mpDelegate->ReadError()` which is the following method

```
CHIP_ERROR DeviceControllerInteractionModelDelegate::ReadError(const app::ReadClient * apReadClient, CHIP_ERROR aError)
{
    app::ClusterInfo path;
    path.mNodeId = apReadClient->GetExchangeContext()->GetSecureSession().GetPeerNodeId();
    IMReadReportAttributesResponseCallback(apReadClient, path, nullptr, Protocols::InteractionModel::Status::Failure);
    return CHIP_NO_ERROR;
}
```

I think the underlying problem is that Read Client is persisting the Exchange Context `mExchangeCtx` for the Report Exchanges initiated by the Publisher for the schedule reports, these Exchanges will be destructed once the Report is acknowledged by the Node. The current crash is one symptom of the underlying issue.

The issue is observed with the `test_event_6` branch (SHA: `005ce592e74e6194ecc19fd4da08cd403b3be05d`)

 #### Proposed Solution

### PR DESCRIPTION
**Pull request by yunhanw-google**
#### Problem
* Fixes #10047 

#### Change overview
-- After sending out status report for unsolicited report
during post-subscription, clear out exchange context. Also Clear out
exchange context when liveness timeout happens.
-- Introduce GetPeerNodeId for read client and remove unsafe
GetExchangeContext for read client.

#### Testing
Manually kick out the server, and trigger the subscription client liveness timeout call, and read peer node id.

### CODE REVIEW

**Review by jmartinez-silabs — APPROVED** [review]

File: src/app/util/im-client-callbacks.cpp [hunk 1]
```diff
@@ -437,8 +437,8 @@ bool IMSubscribeResponseCallback(const chip::app::ReadClient * apSubscribeClient
     CHIP_ERROR err                           = CHIP_NO_ERROR;
     Callback::Cancelable * onSuccessCallback = nullptr;
     Callback::Cancelable * onFailureCallback = nullptr;
-    err = gCallbacks.GetResponseCallback(apSubscribeClient->GetExchangeContext()->GetSecureSession().GetPeerNodeId(),
-                                         sequenceNumber, &onSuccessCallback, &onFailureCallback);
+    err =
+        gCallbacks.GetResponseCallback(apSubscribeClient->GetPeerNodeId(), sequenceNumber, &onSuccessCallback, &onFailureCallback);
```
Comment (mrjerryjohns) [inline src/app/util/im-client-callbacks.cpp:441]: This is insufficient to identify a peer, since fabric information is needed as well. Since this PR isn't altering the GetResponseCallback API, I think it needs a follow-up.

File: src/app/ReadClient.cpp [hunk 2]
```diff
@@ -327,6 +331,7 @@ CHIP_ERROR ReadClient::OnUnsolicitedReportData(Messaging::ExchangeContext * apEx
 {
     mpExchangeCtx  = apExchangeContext;
     CHIP_ERROR err = ProcessReportData(std::move(aPayload));
+    mpExchangeCtx  = nullptr;
```
Comment (mrjerryjohns) [inline src/app/ReadClient.cpp:334]: @bzbarsky-apple If I understand correctly, `ProcessReportData` will trigger the transmission of a StatusResponse, which is the final message in this exchange, resulting in the closure of the exchange automatically.

So this setting of the `mpExchangeCtx` to nullptr is purely for cleanliness, and serves no functional value right?

**Review by mrjerryjohns — APPROVED** [review]

**Comment by mrjerryjohns** [comment]
Can you please add a unit-test that would have caught this failure? (i.e it should have crashed before)

File: src/app/util/im-client-callbacks.cpp (hunk 1 above)
Comment (msandstedt) [reply src/app/util/im-client-callbacks.cpp:441]: I have seen this exact code path happily cross its wires across fabrics and route callbacks to the wrong context.

Indeed, this is a really big security problem.

**Review by msandstedt — APPROVED** [review]
Approve.

I would also echo though the point that we need followup to fix callback routing on node ID.  This is a major security hole.

**Comment by yunhanw-google** [comment]
> Can you please add a unit-test that would have caught this failure? (i.e it should have crashed before)
https://github.com/project-chip/connectedhomeip/issues/10073, need to think about how to do this.

File: src/app/ReadClient.cpp (hunk 2 above)
Comment (yunhanw-google) [reply src/app/ReadClient.cpp:334]: https://github.com/project-chip/connectedhomeip/issues/10074

**Comment by kianooshkarami** [comment]
@yunhanw-google Can we cherry-pick this change into `test_event_6`?

**Comment by andy31415** [comment]
Confirmed with Chaitanya and cherry-picked this one. Manually resolved a small merge conflict.
