### PR TITLE
[android] fixes the library copying issue

### LINKED ISSUE #2529: Unable to build Android CHIP Tool
I am trying to build the CHIP Tool for Android. I followed all the README steps (https://github.com/project-chip/connectedhomeip/blob/master/src/android/CHIPTool/README.md) and I was able to generate and copy in the right locations the SetupPayloadParser.jar/libSetupPayloadParser.so files.

When I try to build the Project in Android Studio I get an undefined reference to "devicecontroller" (see the image below). I noticed that the corresponding .h/.a files were located under src/controller but it's unclear to me how to link these .h/.a files to the project. Could you please help? 

chip-tool

@randyrossi

### PR DESCRIPTION
**Pull request by wgtdkp**
#### Problem
The script of copying the OT Commissioner libraries was changed unintentionally, resulting in a bug that not all libraries are copied into target directory.

 #### Summary of Changes
This PR changes to build OT Commissioner as static libraries rather than shared libraries, so we need to copy only a single shared library at the end.

fixes https://github.com/project-chip/connectedhomeip/issues/2529.

### CODE REVIEW

**Review by andy31415 — COMMENTED** [review]
Restyler does this and I believe it will fight you.

you may need to add this file as an exclude pattern into
`.restyled.yaml`

**Comment by andy31415** [comment]
> Restyler does this and I believe it will fight you.
> 
> you may need to add this file as an exclude pattern into
> `.restyled.yaml`

Alternatively we could just use find directly without a for loop (maybe -type f and -exec args to do the copy) or switch the script to python.

File: third_party/ot-commissioner/build-android-libs.sh [hunk 1]
```diff
@@ -39,10 +39,14 @@ find ./io/openthread/commissioner -name "*.class" | xargs jar cvf ../../../libs/
 cd ../../../
 
 ## Copy shared native libraries
-for lib in "$(find ./build -name "*.so")"; do
+<<<<<<< Updated upstream
```
Comment (bzbarsky-apple) [inline third_party/ot-commissioner/build-android-libs.sh:42]: These conflict markers presumably should not be here...

Also, the commit messages for these commits really need to be better, please.

**Review by bzbarsky-apple — DISMISSED** [review]

**Comment by wgtdkp** [comment]
> > Restyler does this and I believe it will fight you.
> > you may need to add this file as an exclude pattern into
> > `.restyled.yaml`
> 
> Alternatively we could just use find directly without a for loop (maybe -type f and -exec args to do the copy) or switch the script to python.

@andy31415 Thanks for suggestions! I worked out a solution that we can build OT Commissioner as static libraries and have the JNI library links against those static libraries.

File: third_party/ot-commissioner/build-android-libs.sh (hunk 1 above)
Comment (wgtdkp) [reply third_party/ot-commissioner/build-android-libs.sh]: @bzbarsky-apple Sorry for unintentional commits, reverted.

**Review by andy31415 — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
I would still really prefer it if the commit messages described what the commits are doing, instead of that information being captured only in the PR description in GitHub...

**Review by mspang — APPROVED** [review]

**Review by rwalker-apple — APPROVED** [review]

**Comment by rwalker-apple** [comment]
@saurabhst @jelderton @hawk248 ?

**Review by saurabhst — APPROVED** [review]

**Comment by rwalker-apple** [comment]
@bzbarsky-apple can you provide specific instructions for the changes you want or release the review if you're satisfied with the changes made thus far?

**Comment by bzbarsky-apple** [comment]
Some plausible options:

1. A single commit squashing all three of these, with this commit message:
> Build OT Commissioner as static libraries rather than shared libraries" as the commit message.
>
> This way we need to copy only a single shared library at the end.
2. Keep the three commits, but change the commit messages to:
a. "Copy all the OT Commissioner libraries correctly"
b. The one I suggest for the squashed commit above.
c. "correct library name" (as now)

That said, if we're planning to squash anyway, the first of those three will make no sense in the final result, nor will the third...  Hence my preference is for just squashing to start with.
