### PR TITLE
Fix Cirque random crash issue in CI

### LINKED ISSUE #5686: RendezvousSession in DeviceController is used after free
#### Problem

In

https://github.com/project-chip/connectedhomeip/blob/3edc0a1f2ada15dace4d432f6697c8bd97798d18/src/controller/CHIPDeviceController.cpp#L758-L782

`RendezvousCleanup` is called, however, this function is a callback of RendezvousSession.

This caused Cirque tests crashed recently.

 #### Proposed Solution
<suggested fix, suggested enhancement>

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem

The Cirque CI is not stable, it randomly fails due to the following crash

Traceback (most recent call last):
  File "/home/runner/work/connectedhomeip/connectedhomeip/src/test_driver/linux-cirque/helper/CHIPTestBase.py", line 62, in run_test
    self.test_routine()
  File "/home/runner/work/connectedhomeip/connectedhomeip/src/test_driver/linux-cirque/test-on-off-cluster.py", line 66, in test_routine
    self.run_data_model_test()
  File "/home/runner/work/connectedhomeip/connectedhomeip/src/test_driver/linux-cirque/test-on-off-cluster.py", line 91, in run_data_model_test
    self.assertEqual(
  File "/home/runner/work/connectedhomeip/connectedhomeip/src/test_driver/linux-cirque/helper/CHIPTestBase.py", line 222, in assertEqual
    raise AssertionError
AssertionError
2021-04-05 03:50:45,661 [CHIPOnOffTest] INFO destroying home: a322a5ee-12b0-4792-ac98-0d78d83c65c2
Cleanup Flask

It looks OnRendezvousComplete is called after RendezvousCleanup is called.

 #### Summary of Changes
Clean up the RendezvousSession during UnpairDevice.

 Fixes #5686

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]

File: src/controller/CHIPDeviceController.cpp [hunk 1]
```diff
@@ -723,6 +723,8 @@ CHIP_ERROR DeviceCommissioner::UnpairDevice(NodeId remoteDeviceId)
 {
     // TODO: Send unpairing message to the remote device.
 
+    FreeRendezvousSession();
```
Comment (mspang) [inline src/controller/CHIPDeviceController.cpp:726]: Need to check `remoteDeviceId`?

Comment (yufengwangca) [reply src/controller/CHIPDeviceController.cpp:726]: You means this check "VerifyOrReturnError(device->GetDeviceId() == remoteDeviceId, CHIP_ERROR_INVALID_DEVICE_DESCRIPTOR);"

I think this check might not apply to UnpairDevice since it might call on the device which is not currently being paired.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
Marking as hotfix - we had red cirque for the last day on cirque. Trying to figure out if this was the cause, otherwise we can revert the IM PR that started failing.

File: src/controller/CHIPDeviceController.cpp (hunk 1 above)
Comment (mspang) [reply src/controller/CHIPDeviceController.cpp:726]: Right, why would unpairing a different device free the rendezvous session?

Comment (yufengwangca) [reply src/controller/CHIPDeviceController.cpp:726]: That make sense, I will take a look
