### PR TITLE
[ON-OFF] Increase the size of  the onoff cluster's eventControl array to handl…

### LINKED ISSUE #26205: [1.0] [TC-OO-2-3] Failed to send OnWithTimedOff Command to dynamic endpoint, return error "Unsupported Endpoint"
### Reproduction steps

We have a Bridge device，its zap config as follow:
Endpoint 0: RootNode
Endpoint 1: Aggregator
Endpoint 2: Disabled last fixed endpoint，which is used as a placeholder for all of the supported cluster so that zap will generated the requisite code

Steps to trigger this bug:
Step1: Register bridge device to non-matter side
Step2: Commissioning bridge device to matter fabric
Step3: Register a non-matter device to non-matter side
Step4: After step3, we turn this non-matter device to a dynamic endpoint, and endpoint id is 3.
Step5: Then send command "./chip-tool onoff on-with-timed-off 1 300 300 1 3" to this dynamic endpoint.
Step6: we got an error "unsupported endpoint"

And we look into the "src/app/cluster/on-off-server.cpp" and found command "OnWithTimedOff" will check whether the EventControl is nullptr, but "eventControls[EMBER_AF_ON_OFF_CLUSTER_SRVER_ENDPOINT_COUNT]" in "src/app/cluster/on-off-server/on-off-server.h" shows that it seems only has effect on fixed endpoint.   

### Bug prevalence

always

### GitHub hash of the SDK that was being used

4744889

### Platform

ameba

### Platform Version(s)

_No response_

### Type

Common Cluster Logic

### Anything else?

$ ./chip-tool onoff on-with-timed-off 1 300 300 1 3
[1682302961.608545][61116:61116] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_kvs
[1682302961.614116][61116:61116] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_factory.ini
[1682302961.614423][61116:61116] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_config.ini
[1682302961.614554][61116:61116] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_counters.ini
[1682302961.614873][61116:61116] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-lAI0zQ)
[1682302961.615498][61116:61116] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1682302961.615556][61116:61116] CHIP:DL: NVS set: chip-counters/reboot-count = 2 (0x2)
[1682302961.616373][61116:61116] CHIP:DL: Got Ethernet interface: eth0
[1682302961.616955][61116:61116] CHIP:DL: Found the primary Ethernet interface:eth0
[1682302961.617522][61116:61116] CHIP:DL: Got WiFi interface: wlan0
[1682302961.617589][61116:61116] CHIP:DL: Failed to reset WiFi statistic counts
[1682302961.617643][61116:61116] CHIP:IN: UDP::Init bind&listen port=0
[1682302961.617750][61116:61116] CHIP:IN: UDP::Init bound to port=51571
[1682302961.617771][61116:61116] CHIP:IN: BLEBase::Init - setting/overriding transport
[1682302961.617789][61116:61116] CHIP:IN: TransportMgr initialized
[1682302961.617822][61116:61116] CHIP:FP: Initializing FabricTable from persistent storage
[1682302961.617962][61116:61116] CHIP:TS: Last Known Good Time: 2022-10-21T23:13:11
[1682302961.619406][61116:61116] CHIP:FP: Fabric index 0x1 was retrieved from storage. Compressed FabricId 0x8FECD154B02E71F6, FabricId 0x0000000000000001, NodeId 0x000000000001B669, VendorId 0xFFF1
[1682302961.621569][61116:61116] CHIP:ZCL: Using ZAP configuration...
[1682302961.625441][61116:61116] CHIP:DL: Avahi client registered
[1682302961.626610][61116:61116] CHIP:CTL: System State Initialized...
[1682302961.626722][61116:61116] CHIP:CTL: Stopping commissioning discovery over DNS-SD
[1682302961.626764][61116:61116] CHIP:CTL: Setting attestation nonce to random value
[1682302961.626800][61116:61116] CHIP:CTL: Setting CSR nonce to random value
[1682302961.627085][61116:61121] CHIP:DL: CHIP task running
[1682302961.627391][61116:61121] CHIP:DL: HandlePlatformSpecificBLEEvent 32784
[1682302961.627466][61116:61121] CHIP:CTL: Stopping commissioning discovery over DNS-SD
[1682302961.627501][61116:61121] CHIP:CTL: Setting attestation nonce to random value
[1682302961.627678][61116:61121] CHIP:CTL: Setting CSR nonce to random value
[1682302961.628812][61116:61121] CHIP:CTL: Generating NOC
[1682302961.629955][61116:61121] CHIP:FP: Validating NOC chain
[1682302961.632036][61116:61121] CHIP:FP: NOC chain validation successful
[1682302961.632214][61116:61121] CHIP:FP: Updated fabric at index: 0x1, Node ID: 0x000000000001B669
[1682302961.632249][61116:61121] CHIP:TS: Last Known Good Time: 2022-10-21T23:13:11
[1682302961.632273][61116:61121] CHIP:TS: New proposed Last Known Good Time: 2021-01-01T00:00:00
[1682302961.632296][61116:61121] CHIP:TS: Retaining current Last Known Good Time
[1682302961.639743][61116:61121] CHIP:FP: Metadata for Fabric 0x1 persisted to storage.
[1682302961.641749][61116:61121] CHIP:TS: Committing Last Known Good Time to storage: 2022-10-21T23:13:11
[1682302961.644204][61116:61121] CHIP:CTL: Joined the fabric at index 1. Compressed fabric ID is: 0x0000000000000000
[1682302961.653335][61116:61121] CHIP:TOO: Sending command to node 0x1
[1682302961.653387][61116:61121] CHIP:CSM: FindOrEstablishSession: PeerId = [1:0000000000000001]
[1682302961.653411][61116:61121] CHIP:CSM: FindOrEstablishSession: No existing OperationalSessionSetup instance found
[1682302961.653448][61116:61121] CHIP:CTL: OperationalSessionSetup[1:0000000000000001]: State change 1 --> 2
[1682302961.653479][61116:61121] CHIP:DIS: Resolving 8FECD154B02E71F6:0000000000000001 ...
[1682302961.655214][61116:61121] CHIP:DL: Avahi resolve found
[1682302961.655287][61116:61121] CHIP:DIS: Node ID resolved for 8FECD154B02E71F6:0000000000000001
[1682302961.655310][61116:61121] CHIP:DIS:      Hostname: 00E04CB72300
[1682302961.655336][61116:61121] CHIP:DIS:      IP Address #1: fe80::2e0:4cff:feb7:2300
[1682302961.655358][61116:61121] CHIP:DIS:      Port: 5540
[1682302961.655379][61116:61121] CHIP:DIS:      Mrp Interval idle: 5000 ms
[1682302961.655399][61116:61121] CHIP:DIS:      Mrp Interval active: 300 ms
[1682302961.655420][61116:61121] CHIP:DIS:      TCP Supported: 1
[1682302961.655555][61116:61121] CHIP:DIS: UDP:[fe80::2e0:4cff:feb7:2300%eth0]:5540: new best score: 3
[1682302961.655601][61116:61121] CHIP:DIS: Checking node lookup status after 2 ms
[1682302961.655620][61116:61121] CHIP:DIS: Keeping DNSSD lookup active
[1682302961.854046][61116:61121] CHIP:DIS: Checking node lookup status after 200 ms
[1682302961.854362][61116:61121] CHIP:DIS: OperationalSessionSetup[1:0000000000000001]: Updating device address to UDP:[fe80::2e0:4cff:feb7:2300%eth0]:5540 while in state 2
[1682302961.854431][61116:61121] CHIP:CTL: OperationalSessionSetup[1:0000000000000001]: State change 2 --> 3
[1682302961.854646][61116:61121] CHIP:IN: SecureSession[0xffff8c00a0a0]: Allocated Type:2 LSID:26145
[1682302961.854735][61116:61121] CHIP:SC: Initiating session on local FabricIndex 1 from 0x000000000001B669 -> 0x0000000000000001
[1682302961.856408][61116:61121] CHIP:SC: Including MRP parameters
[1682302961.856799][61116:61121] CHIP:IN: Prepared unauthenticated message 0xffff8c007028 to 0x0000000000000000 (0)  of type 0x30 and protocolId (0, 0) on exchange 36124i with MessageCounter:242630426.
[1682302961.856905][61116:61121] CHIP:IN: Sending unauthenticated msg 0xffff8c007028 with MessageCounter:242630426 to 0x0000000000000000 at monotonic time: 0000000042AC0910 msec
[1682302961.857216][61116:61121] CHIP:SC: Sent Sigma1 msg
[1682302961.857287][61116:61121] CHIP:CTL: OperationalSessionSetup[1:0000000000000001]: State change 3 --> 4
[1682302961.922975][61116:61121] CHIP:EM: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:263731168 on exchange 36124i
[1682302961.923075][61116:61121] CHIP:EM: Found matching exchange: 36124i, Delegate: 0xffff8c00b138
[1682302961.923158][61116:61121] CHIP:EM: Rxd Ack; Removing MessageCounter:242630426 from Retrans Table on exchange 36124i
[1682302961.923216][61116:61121] CHIP:EM: Removed CHIP MessageCounter:242630426 from RetransTable on exchange 36124i
[1682302962.512764][61116:61121] CHIP:EM: Received message of type 0x31 with protocolId (0, 0) and MessageCounter:263731169 on exchange 36124i
[1682302962.512843][61116:61121] CHIP:EM: Found matching exchange: 36124i, Delegate: 0xffff8c00b138
[1682302962.512888][61116:61121] CHIP:EM: CHIP MessageCounter:242630426 not in RetransTable on exchange 36124i
[1682302962.512953][61116:61121] CHIP:SC: Received Sigma2 msg
[1682302962.513007][61116:61121] CHIP:SC: Peer assigned session session ID 10598
[1682302962.519785][61116:61121] CHIP:SC: Found MRP parameters in the message
[1682302962.519868][61116:61121] CHIP:SC: Sending Sigma3
[1682302962.520634][61116:61121] CHIP:EM: Piggybacking Ack for MessageCounter:263731169 on exchange: 36124i
[1682302962.520718][61116:61121] CHIP:IN: Prepared unauthenticated message 0xffff8c007728 to 0x0000000000000000 (0)  of type 0x32 and protocolId (0, 0) on exchange 36124i with MessageCounter:242630427.
[1682302962.520777][61116:61121] CHIP:IN: Sending unauthenticated msg 0xffff8c007728 with MessageCounter:242630427 to 0x0000000000000000 at monotonic time: 0000000042AC0BA8 msec
[1682302962.520998][61116:61121] CHIP:SC: Sent Sigma3 msg
[1682302962.584161][61116:61121] CHIP:EM: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:263731170 on exchange 36124i
[1682302962.584228][61116:61121] CHIP:EM: Found matching exchange: 36124i, Delegate: 0xffff8c00b138
[1682302962.584288][61116:61121] CHIP:EM: Rxd Ack; Removing MessageCounter:242630427 from Retrans Table on exchange 36124i
[1682302962.584331][61116:61121] CHIP:EM: Removed CHIP MessageCounter:242630427 from RetransTable on exchange 36124i
[1682302963.905678][61116:61121] CHIP:EM: Received message of type 0x40 with protocolId (0, 0) and MessageCounter:263731171 on exchange 36124i
[1682302963.905782][61116:61121] CHIP:EM: Found matching exchange: 36124i, Delegate: 0xffff8c00b138
[1682302963.905846][61116:61121] CHIP:EM: CHIP MessageCounter:242630427 not in RetransTable on exchange 36124i
[1682302963.905939][61116:61121] CHIP:SC: Success status report received. Session was established
[1682302963.912589][61116:61121] CHIP:SC: SecureSession[0xffff8c00a0a0]: Moving from state 'kEstablishing' --> 'kActive'
[1682302963.912666][61116:61121] CHIP:IN: SecureSession[0xffff8c00a0a0]: Activated - Type:2 LSID:26145
[1682302963.912707][61116:61121] CHIP:IN: New secure session activated for device <0000000000000001, 1>, LSID:26145 PSID:10598!
[1682302963.912756][61116:61121] CHIP:CTL: OperationalSessionSetup[1:0000000000000001]: State change 4 --> 5
[1682302963.912843][61116:61121] CHIP:TOO: Sending cluster (0x00000006) command (0x00000042) on endpoint 3
[1682302963.912935][61116:61121] CHIP:DMG: ICR moving to [AddingComm]
[1682302963.912990][61116:61121] CHIP:DMG: ICR moving to [AddedComma]
[1682302963.913325][61116:61121] CHIP:IN: Prepared secure message 0xffff8c00d208 to 0x0000000000000001 (1)  of type 0x8 and protocolId (0, 1) on exchange 36125i with MessageCounter:149376042.
[1682302963.913409][61116:61121] CHIP:IN: Sending encrypted msg 0xffff8c00d208 with MessageCounter:149376042 to 0x0000000000000001 (1) at monotonic time: 0000000042AC1118 msec
[1682302963.913663][61116:61121] CHIP:DMG: ICR moving to [CommandSen]
[1682302963.913750][61116:61121] CHIP:EM: Sending Standalone Ack for MessageCounter:263731171 on exchange 36124i
[1682302963.913818][61116:61121] CHIP:IN: Prepared unauthenticated message 0xffffa14ed968 to 0x0000000000000000 (0)  of type 0x10 and protocolId (0, 0) on exchange 36124i with MessageCounter:242630428.
[1682302963.913879][61116:61121] CHIP:IN: Sending unauthenticated msg 0xffffa14ed968 with MessageCounter:242630428 to 0x0000000000000000 at monotonic time: 0000000042AC1119 msec
[1682302963.914017][61116:61121] CHIP:EM: Flushed pending ack for MessageCounter:263731171 on exchange 36124i
[1682302964.067799][61116:61121] CHIP:EM: Received message of type 0x9 with protocolId (0, 1) and MessageCounter:153876781 on exchange 36125i
[1682302964.067899][61116:61121] CHIP:EM: Found matching exchange: 36125i, Delegate: 0xffff8c009908
[1682302964.067981][61116:61121] CHIP:EM: Rxd Ack; Removing MessageCounter:149376042 from Retrans Table on exchange 36125i
[1682302964.068040][61116:61121] CHIP:EM: Removed CHIP MessageCounter:149376042 from RetransTable on exchange 36125i
[1682302964.068117][61116:61121] CHIP:DMG: ICR moving to [ResponseRe]
[1682302964.068225][61116:61121] CHIP:DMG: InvokeResponseMessage =
[1682302964.068285][61116:61121] CHIP:DMG: {
[1682302964.068342][61116:61121] CHIP:DMG:      suppressResponse = false,
[1682302964.068403][61116:61121] CHIP:DMG:      InvokeResponseIBs =
[1682302964.068524][61116:61121] CHIP:DMG:      [
[1682302964.068589][61116:61121] CHIP:DMG:              InvokeResponseIB =
[1682302964.068670][61116:61121] CHIP:DMG:              {
[1682302964.068735][61116:61121] CHIP:DMG:                      CommandStatusIB =
[1682302964.068815][61116:61121] CHIP:DMG:                      {
[1682302964.068883][61116:61121] CHIP:DMG:                              CommandPathIB =
[1682302964.068961][61116:61121] CHIP:DMG:                              {
[1682302964.069040][61116:61121] CHIP:DMG:                                      EndpointId = 0x3,
[1682302964.069125][61116:61121] CHIP:DMG:                                      ClusterId = 0x6,
[1682302964.069205][61116:61121] CHIP:DMG:                                      CommandId = 0x42,
[1682302964.069282][61116:61121] CHIP:DMG:                              },
[1682302964.069370][61116:61121] CHIP:DMG:
[1682302964.069441][61116:61121] CHIP:DMG:                              StatusIB =
[1682302964.069519][61116:61121] CHIP:DMG:                              {
[1682302964.069598][61116:61121] CHIP:DMG:                                      status = 0x7f (UNSUPPORTED_ENDPOINT),
[1682302964.069677][61116:61121] CHIP:DMG:                              },
[1682302964.069750][61116:61121] CHIP:DMG:
[1682302964.069817][61116:61121] CHIP:DMG:                      },
[1682302964.069896][61116:61121] CHIP:DMG:
[1682302964.069958][61116:61121] CHIP:DMG:              },
[1682302964.070032][61116:61121] CHIP:DMG:
[1682302964.070089][61116:61121] CHIP:DMG:      ],
[1682302964.070162][61116:61121] CHIP:DMG:
[1682302964.070219][61116:61121] CHIP:DMG:      InteractionModelRevision = 1
[1682302964.070277][61116:61121] CHIP:DMG: },
[1682302964.070410][61116:61121] CHIP:DMG: Received Command Response Status for Endpoint=3 Cluster=0x0000_0006 Command=0x0000_0042 Status=0x7f
[1682302964.070484][61116:61121] CHIP:TOO: Error: IM Error 0x0000057F: General error: 0x7f (UNSUPPORTED_ENDPOINT)
[1682302964.070569][61116:61121] CHIP:DMG: ICR moving to [AwaitingDe]
[1682302964.070681][61116:61121] CHIP:EM: Sending Standalone Ack for MessageCounter:153876781 on exchange 36125i
[1682302964.070852][61116:61121] CHIP:IN: Prepared secure message 0xffffa14ed978 to 0x0000000000000001 (1)  of type 0x10 and protocolId (0, 0) on exchange 36125i with MessageCounter:149376043.
[1682302964.070946][61116:61121] CHIP:IN: Sending encrypted msg 0xffffa14ed978 with MessageCounter:149376043 to 0x0000000000000001 (1) at monotonic time: 0000000042AC11B6 msec
[1682302964.071169][61116:61121] CHIP:EM: Flushed pending ack for MessageCounter:153876781 on exchange 36125i
[1682302964.071539][61116:61116] CHIP:CTL: Shutting down the commissioner
[1682302964.071613][61116:61116] CHIP:CTL: Stopping commissioning discovery over DNS-SD
[1682302964.071674][61116:61116] CHIP:CTL: Shutting down the controller
[1682302964.071726][61116:61116] CHIP:IN: Expiring all sessions for fabric 0x1!!
[1682302964.071777][61116:61116] CHIP:IN: SecureSession[0xffff8c00a0a0]: MarkForEviction Type:2 LSID:26145
[1682302964.071830][61116:61116] CHIP:SC: SecureSession[0xffff8c00a0a0]: Moving from state 'kActive' --> 'kPendingEviction'
[1682302964.071883][61116:61116] CHIP:IN: SecureSession[0xffff8c00a0a0]: Released - Type:2 LSID:26145
[1682302964.071942][61116:61116] CHIP:FP: Forgetting fabric 0x1
[1682302964.072012][61116:61116] CHIP:TS: Pending Last Known Good Time: 2022-10-21T23:13:11
[1682302964.072292][61116:61116] CHIP:TS: Previous Last Known Good Time: 2022-10-21T23:13:11
[1682302964.072354][61116:61116] CHIP:TS: Reverted Last Known Good Time to previous value
[1682302964.072441][61116:61116] CHIP:CTL: Shutting down the commissioner
[1682302964.072540][61116:61116] CHIP:CTL: Stopping commissioning discovery over DNS-SD
[1682302964.072595][61116:61116] CHIP:CTL: Shutting down the controller
[1682302964.072645][61116:61116] CHIP:CTL: Shutting down the System State, this will teardown the CHIP Stack
[1682302964.074636][61116:61116] CHIP:DMG: IM WH moving to [Uninitialized]
[1682302964.074716][61116:61116] CHIP:DMG: IM WH moving to [Uninitialized]
[1682302964.074765][61116:61116] CHIP:DMG: IM WH moving to [Uninitialized]
[1682302964.074814][61116:61116] CHIP:DMG: IM WH moving to [Uninitialized]
[1682302964.074869][61116:61116] CHIP:DMG: All ReadHandler-s are clean, clear GlobalDirtySet
[1682302964.075040][61116:61116] CHIP:BLE: BleConnectionDelegate::CancelConnection is not implemented.
[1682302964.075511][61116:61116] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-hwr1qG)
[1682302964.076907][61116:61116] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1682302964.077052][61116:61116] CHIP:DL: NVS set: chip-counters/total-operational-hours = 0 (0x0)
[1682302964.077113][61116:61116] CHIP:DL: Inet Layer shutdown
[1682302964.077164][61116:61116] CHIP:DL: BLE shutdown
[1682302964.077216][61116:61116] CHIP:DL: System Layer shutdown
[1682302964.077471][61116:61116] CHIP:TOO: Run command failure: IM Error 0x0000057F: General error: 0x7f (UNSUPPORTED_ENDPOINT)

### PR DESCRIPTION
**Pull request by jmartinez-silabs**
…e the max dynamic endpoint count.

fixes #26205

### CODE REVIEW

File: src/app/clusters/on-off-server/on-off-server.cpp [hunk 1]
```diff
@@ -48,7 +48,9 @@ using chip::Protocols::InteractionModel::Status;
 static OnOffEffect * firstEffect = nullptr;
 OnOffServer OnOffServer::instance;
 
-static EmberEventControl gEventControls[EMBER_AF_ON_OFF_CLUSTER_SERVER_ENDPOINT_COUNT];
+static constexpr size_t kOnOffMaxEnpointCount =
+    EMBER_AF_ON_OFF_CLUSTER_SERVER_ENDPOINT_COUNT + CHIP_DEVICE_CONFIG_DYNAMIC_ENDPOINT_COUNT;
+static EmberEventControl gEventControls[kOnOffMaxEnpointCount];
```
Comment (bzbarsky-apple) [inline src/app/clusters/on-off-server/on-off-server.cpp:53]: This is not enough on its own.

The array is indexed into using `emberAfFindClusterServerEndpointIndex`.  But that function is only safe to use for static endpoints.  For dynamic endpoints it can at runtime change what value it returns for the same exact endpoint.

See also the description of this same problem in https://github.com/project-chip/connectedhomeip/issues/25984#issue-1655772149

We should probably have a helper function for this "find the index into the array for both static and dynamic endpoints" operation....

And we ideally should have tests for this.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/clusters/on-off-server/on-off-server.cpp (hunk 1 above)
Comment (jmartinez-silabs) [reply src/app/clusters/on-off-server/on-off-server.cpp:53]: Ok I didn't realize that emberAfFindClusterServerEndpointIndex was not properly working for dynamic endpoints. 

Why don't we set dynamic clusters to always be set at the end of the static indexes?
let's say I have `EMBER_AF_ON_OFF_CLUSTER_SERVER_ENDPOINT_COUNT` static on-off cluster defined. Then, a dynamic cluster added will always be set to an index > than  `(EMBER_AF_ON_OFF_CLUSTER_SERVER_ENDPOINT_COUNT-1)`

Comment (jmartinez-silabs) [reply src/app/clusters/on-off-server/on-off-server.cpp:53]: if I look at the implementation of `emberAfGetDynamicIndexFromEndpoint` and `emberAfSetDynamicEndpoint`it seems to be implemented as I mention. What am I missing? why does the index of a dynamic endpoint change at runtime?

Comment (bzbarsky-apple) [reply src/app/clusters/on-off-server/on-off-server.cpp:53]: @jmartinez-silabs `emberAfFindClusterServerEndpointIndex` is the index of the endpoint in the list of endpoints that implement the given cluster, and with dynamic endpoints that list can have things added/removed in the middle as dynamic endpoints are added/removed.

Let's say you have a device with one static endpoint, with endpoint id 1, that implements On/Off and allows two dynamic endpoints, and the following sequence of actions happens:

1. A dynamic endpoint with endpoint id 2 is defined at dynamic index 0 that implements On/Off.
2. A dynamic endpoint with endpoint id 3 is defined at dynamic index 1 that implements On/Off.

At this point:

* `emberAfFindClusterServerEndpointIndex(1, OnOff::Id) == 0`
* `emberAfFindClusterServerEndpointIndex(2, OnOff::Id) == 1`
* `emberAfFindClusterServerEndpointIndex(3, OnOff::Id) == 2`

Now endpoint 2 is removed via `emberAfClearDynamicEndpoint(0)` (e.g. because we are a bridge and the device we are bridging is permanently disconnected from the bridge.  Now what we have is:

* `emberAfFindClusterServerEndpointIndex(1, OnOff::Id) == 0`
* `emberAfFindClusterServerEndpointIndex(3, OnOff::Id) == 1`

Now we start bridging a new thing, endpoint 4 is added at dynamic index 0, and we end up with:

* `emberAfFindClusterServerEndpointIndex(1, OnOff::Id) == 0`
* `emberAfFindClusterServerEndpointIndex(4, OnOff::Id) == 1`
* `emberAfFindClusterServerEndpointIndex(3, OnOff::Id) == 2`

Comment (jmartinez-silabs) [reply src/app/clusters/on-off-server/on-off-server.cpp:53]: Do you agree that when we remove the dynamic endpoint 2, we should not re-index the existing dynamic endpoints. In my opinion, we should leave index 1 empty and the 2nd dynamic endpoint(3) keeps his initial his index (2 in the case above). 

This way you would always be sure that for a given existing dynamic endpoint you always get the same index. 

I am not sure how we can identify a dynamic ep with his index with what is currently implemented

Comment (bzbarsky-apple) [reply src/app/clusters/on-off-server/on-off-server.cpp:53]: > Do you agree that when we remove the dynamic endpoint 2, we should not re-index the existing dynamic endpoints.

"re-index" in what sense?  Their _endpoint index_ does not change. But the value returned by `emberAfFindClusterServerEndpointIndex` changes, as things stand.

We could change what `emberAfFindClusterServerEndpointIndex` does, of course.  What is the exact proposal for what it should do?

> I am not sure how we can identify a dynamic ep with his index with what is currently implemented

You can identify dynamic endpoints by:

1. `emberAfIndexFromEndpoint(endpoint_id)` is not `kEmberInvalidEndpointIndex`
2. `emberAfIndexFromEndpoint(endpoint_id) >= emberAfFixedEndpointCount()`

Comment (jmartinez-silabs) [reply src/app/clusters/on-off-server/on-off-server.cpp:53]: I added a new function that returns the index of the ClusterServer endpoint as it is indexed in `emAfEndpoints`.

This index is always valid for static and dynamic endpoints and will correspond to the event control array on the on-off server implementation.

This new function can be used in multiple cluster server implementations and fix the issue with dynamic endpoint indexing when using `emberAfFindClusterServerEndpointIndex`.

Once this is merged, I'll replace the function calls in the other cluster that use a similar implementation than OnOff cluster

File: src/app/util/af.h [hunk 2]
```diff
@@ -184,6 +184,42 @@ uint16_t emberAfIndexFromEndpointIncludingDisabledEndpoints(chip::EndpointId end
...
 uint16_t emberAfFindClusterServerEndpointIndex(chip::EndpointId endpoint, chip::ClusterId clusterId);
 
+/**
+ * Returns the index of the given endpoint, in the list of all defined endpoints,
+ * that support the given cluster.
+ *
+ * Returns kEmberInvalidEndpointIndex if the given endpoint does not support the
+ * given cluster or if the given endpoint is disabled.
+ *
+ * Contrary to emberAfFindClusterServerEndpointIndex, this function always return the same index
```
Comment (bzbarsky-apple) [inline src/app/util/af.h:194]:
```suggestion
 * Unlike emberAfFindClusterServerEndpointIndex, this function always return the same index
```

File: src/app/util/attribute-storage.cpp [hunk 3]
```diff
@@ -878,6 +878,23 @@ static uint16_t findIndexFromEndpoint(EndpointId endpoint, bool ignoreDisabledEn
     return kEmberInvalidEndpointIndex;
 }
 
+uint16_t emberAfGetClusterServerEndpointIndex(EndpointId endpoint, ClusterId cluster)
```
Comment (bzbarsky-apple) [inline src/app/util/attribute-storage.cpp:881]: Given the behavior of this function, the way on-off-server is using it is wrong and will lead to out-of-bounds access on the array.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/util/attribute-storage.cpp (hunk 3 above)
Comment (bzbarsky-apple) [reply src/app/util/attribute-storage.cpp:881]: Again, what I think we want here, given how the array in on-off-server is set up, is a function that:

1) For static endpoins returns what emberAfFindClusterServerEndpointIndex returns.
2) For dynamic endpoints returns the index of the endpoint minus FIXED_ENDPOINT_COUNT plus the number of fixed endpoints that implement the given cluster.

or something like that.  Please check carefully.

This code _really_ needs tests.

Comment (jmartinez-silabs) [reply src/app/util/attribute-storage.cpp:881]: Argh I confused `EMBER_AF_ON_OFF_CLUSTER_SERVER_ENDPOINT_COUNT`  with `FIXED_ENPOINT_COUNT` to be the same.   :Facepalm: 

Alright I'll fix that tomorrow.

For a unit test, I agree but I don't have a simple way to do it without re-implemeting the app-util mock, and I don't currently have the time to do that part.

I am willing to do with but it will have to wait a bit

Comment (bzbarsky-apple) [reply src/app/util/attribute-storage.cpp:881]: Yeah, I'm not going to block this PR on the test bit; just saying that it would be really good to have them in general....

Comment (jmartinez-silabs) [reply src/app/util/attribute-storage.cpp]: Updated the function to act as you described, Sorry for my confusion and mistake yesterday. 

I'll now plan time to unit test that code in the incoming days

File: src/app/util/af.h [hunk 4]
```diff
@@ -184,6 +184,46 @@ uint16_t emberAfIndexFromEndpointIncludingDisabledEndpoints(chip::EndpointId end
  */
 uint16_t emberAfFindClusterServerEndpointIndex(chip::EndpointId endpoint, chip::ClusterId clusterId);
 
+/**
+ *  @brief Returns an index of the given endpoint the given cluster server
```
Comment (bzbarsky-apple) [inline src/app/util/af.h:188]:
```suggestion
 *  @brief Returns the index of the given endpoint in the list of all endpoints that might support the given cluster server.
```

File: src/app/util/af.h [hunk 5]
```diff
@@ -184,6 +184,46 @@ uint16_t emberAfIndexFromEndpointIncludingDisabledEndpoints(chip::EndpointId end
...
+ *
+ * Returns kEmberInvalidEndpointIndex if the given endpoint does not support the
+ * given cluster or if the given endpoint is disabled.
+ *
+ * Unlike emberAfFindClusterServerEndpointIndex, this function always returns the same index
+ * for a given endpointId instance, static or dynamic.
```
Comment (bzbarsky-apple) [inline src/app/util/af.h:194]:
```suggestion
 * Unlike emberAfFindClusterServerEndpointIndex, this function always returns the same index
 * for a given endpointId instance, fixed or dynamic, if it does not return kEmberInvalidEndpointIndex.
```

Because an endpoint can _absolutely_ go from returning `kEmberInvalidEndpointIndex` to returning some valid index or the other way.

Also, later on we call the fixed endpoints "fixed", not static.

File: src/app/util/af.h [hunk 6]
```diff
@@ -184,6 +184,46 @@ uint16_t emberAfIndexFromEndpointIncludingDisabledEndpoints(chip::EndpointId end
...
+ *
+ * The return index is determined by the location of the endpoint in
+ * emAfEndpoints database but is adjusted to the given Cluster server implementation scope
```
Comment (bzbarsky-apple) [inline src/app/util/af.h:197]: I don't know what this comment is supposed to say.  Maybe better would be:
```suggestion
 * The return index is identical to emberAfFindClusterServerEndpointIndex for fixed endpoints,
 * but for dynamic endpoints the indexing assumes that any dynamic endpoint could start supporting
 * the given server cluster.
```
or something like that.

File: src/app/util/af.h [hunk 7]
```diff
@@ -184,6 +184,46 @@ uint16_t emberAfIndexFromEndpointIncludingDisabledEndpoints(chip::EndpointId end
...
+ * For example, if a device has 4 fixed endpoints (ids 0-3) and 2 dynamic
+ * endpoints, and cluster X is supported on endpoints 1 and 3, then
+ * fixedClusterServerEndpointCount should be 2 and
+ *
+ * 1) emberAfGetClusterServerEndpointIndex(0, X) returns kEmberInvalidEndpointIndex
+ * 2) emberAfGetClusterServerEndpointIndex(1, X) returns 0
+ * 3) emberAfGetClusterServerEndpointIndex(2, X) returns kEmberInvalidEndpointIndex
+ * 4) emberAfGetClusterServerEndpointIndex(3, X) returns 1
+
+ * The Dynamic endpoints are placed after the fixed ones
```
Comment (bzbarsky-apple) [inline src/app/util/af.h:208]:
```suggestion
 * The Dynamic endpoints are placed after the fixed ones;
```

File: src/app/util/af.h [hunk 8]
```diff
@@ -184,6 +184,46 @@ uint16_t emberAfIndexFromEndpointIncludingDisabledEndpoints(chip::EndpointId end
...
+ * then emberAfGetClusterServerEndpointIndex(7, X) returns 3 (fixedClusterServerEndpointCount{2} + DynamicEndpointIndex {1}).
+ *
+ * If now a second dynamic endpoint, also supporting cluster X, is defined to dynamic index 0
+ * with endpoint id 9  (via emberAfSetDynamicEndpoint(0, 9, ...)),
+ * emberAfGetClusterServerEndpointIndex(9, X) returns 2. (fixedClusterServerEndpointCount{2} + DynamicEndpointIndex {0}).
+ * and emberAfGetClusterServerEndpointIndex(7, X) still returns 3
+ *
+ * @param endpoint Endpoint number
+ * @param cluster Id the of the Cluster server you are interrested on
+ * @param fixedClusterServerEndpointCount The amount of Fixed endpoints containing this cluster server
```
Comment (bzbarsky-apple) [inline src/app/util/af.h:222]:
```suggestion
 * @param fixedClusterServerEndpointCount The number of fixed endpoints containing this cluster server.  Typically one of the  EMBER_AF_*_CLUSTER_SERVER_ENDPOINT_COUNT constants.
```

File: src/app/util/attribute-storage.cpp [hunk 9]
```diff
@@ -878,6 +878,51 @@ static uint16_t findIndexFromEndpoint(EndpointId endpoint, bool ignoreDisabledEn
     return kEmberInvalidEndpointIndex;
 }
 
+uint16_t emberAfGetClusterServerEndpointIndex(EndpointId endpoint, ClusterId cluster, uint16_t fixedClusterServerEndpointCount)
+{
+    uint16_t epIndex = findIndexFromEndpoint(endpoint, true /*ignoreDisabledEndpoints*/);
+
+    // Endpoint must be configured and enabled
+    if (epIndex != kEmberInvalidEndpointIndex)
```
Comment (bzbarsky-apple) [inline src/app/util/attribute-storage.cpp:886]: Why not just early-return if `epIndex == kEmberInvalidEndpointIndex` and outdent?

File: src/app/util/attribute-storage.cpp [hunk 10]
```diff
@@ -878,6 +878,51 @@ static uint16_t findIndexFromEndpoint(EndpointId endpoint, bool ignoreDisabledEn
...
+    {
+        if (emberAfFindClusterInType(emAfEndpoints[epIndex].endpointType, cluster, CLUSTER_MASK_SERVER) == nullptr)
+        {
+            // The provided endpoint do not contain the given cluster server.
```
Comment (bzbarsky-apple) [inline src/app/util/attribute-storage.cpp:890]:
```suggestion
            // The provided endpoint does not contain the given cluster server.
```

File: src/app/util/attribute-storage.cpp [hunk 11]
```diff
@@ -878,6 +878,51 @@ static uint16_t findIndexFromEndpoint(EndpointId endpoint, bool ignoreDisabledEn
...
+            return kEmberInvalidEndpointIndex;
+        }
+
+        if (epIndex < FIXED_ENDPOINT_COUNT)
+        {
+            // This endpoint is a fixed one.
```
Comment (bzbarsky-apple) [inline src/app/util/attribute-storage.cpp:896]: Isn't this just reimplementing `emberAfFindClusterServerEndpointIndex`?  Why not just call that?

File: src/app/util/attribute-storage.cpp [hunk 12]
```diff
@@ -878,6 +878,51 @@ static uint16_t findIndexFromEndpoint(EndpointId endpoint, bool ignoreDisabledEn
...
+            }
+
+            // If this asserts, The provided fixedClusterServerEndpointCount doesn't match the app data model"
+            VerifyOrDie(ajustedEndpointIndex < fixedClusterServerEndpointCount);
+            epIndex = ajustedEndpointIndex;
+        }
+        else
+        {
+            // This is a Dynamic endpoint
+            // ajust index after the fixedClusterServerEndpointCount index
```
Comment (bzbarsky-apple) [inline src/app/util/attribute-storage.cpp:918]:
```suggestion
            // This is a dynamic endpoint.
            // It's index is just its index in the dynamic endpoint list, offset by fixedClusterServerEndpointCount.
```

File: src/app/util/attribute-storage.cpp [hunk 13]
```diff
@@ -878,6 +878,51 @@ static uint16_t findIndexFromEndpoint(EndpointId endpoint, bool ignoreDisabledEn
     return kEmberInvalidEndpointIndex;
 }
 
+uint16_t emberAfGetClusterServerEndpointIndex(EndpointId endpoint, ClusterId cluster, uint16_t fixedClusterServerEndpointCount)
+{
+    uint16_t epIndex = findIndexFromEndpoint(endpoint, true /*ignoreDisabledEndpoints*/);
```
Comment (bzbarsky-apple) [inline src/app/util/attribute-storage.cpp:883]: We should probably either fail out or die if fixedClusterServerEndpointCount > FIXED_ENDPOINT_COUNT.

File: src/app/util/attribute-storage.cpp (hunk 9 above)
Comment (jmartinez-silabs) [reply src/app/util/attribute-storage.cpp:886]: Either way, there is the same amount of conditions and no added code or additional call if `epIndex == kEmberInvalidEndpointIndex`

Just a preference I guess, I can do it as you suggest. It doesn't bother me

File: src/app/util/attribute-storage.cpp (hunk 13 above)
Comment (jmartinez-silabs) [reply src/app/util/attribute-storage.cpp:883]: Agreed, adding it

File: src/app/util/attribute-storage.cpp (hunk 11 above)
Comment (bzbarsky-apple) [reply src/app/util/attribute-storage.cpp]: While true, this approach duplicates various fragile code.

Perhaps as a followup (or here, if you prefer) we should factor out the for loop inside `findClusterEndpointIndex` so that it can be used from both there and here?

Comment (jmartinez-silabs) [reply src/app/util/attribute-storage.cpp]: I can do that. I just wonder once this is merged and tested with a unit test. Is there still a use case for emberAfFindClusterServerEndpointIndex ?

Comment (bzbarsky-apple) [reply src/app/util/attribute-storage.cpp]: That's a good question.  There are a bunch of consumers, but I suspect they should all be using the new function...  So maybe the right answer is we update them all to do that and remove `emberAfFindClusterServerEndpointIndex`?

Comment (jmartinez-silabs) [reply src/app/util/attribute-storage.cpp]: Yes, I think that's a plan. In a second PR, I'll review all the other use of `emberAfFindClusterServerEndpointIndex` and replace it with `emberAfGetClusterServerEndpointIndex`

File: src/app/util/attribute-storage.cpp [hunk 14]
```diff
@@ -878,6 +878,54 @@ static uint16_t findIndexFromEndpoint(EndpointId endpoint, bool ignoreDisabledEn
...
+    {
+        // The provided endpoint does not contain the given cluster server.
+        return kEmberInvalidEndpointIndex;
+    }
+
+    if (epIndex < FIXED_ENDPOINT_COUNT)
+    {
+        // This endpoint is a fixed one.
+        // ajust the return index to be in the scope of the ClusterServer[0 to fixedClusterServerEndpointCount]
+        // in chronological order of appearance of the cluster server in the endpoint database
```
Comment (bzbarsky-apple) [inline src/app/util/attribute-storage.cpp:902]:
```suggestion
        // Return the index of this endpoint in the list of fixed endpoints that support the given cluster.
```

File: src/app/util/attribute-storage.cpp [hunk 15]
```diff
@@ -878,6 +878,54 @@ static uint16_t findIndexFromEndpoint(EndpointId endpoint, bool ignoreDisabledEn
...
+        uint16_t ajustedEndpointIndex = 0;
```
Comment (bzbarsky-apple) [inline src/app/util/attribute-storage.cpp:903]:
```suggestion
        uint16_t adjustedEndpointIndex = 0;
```

File: src/app/util/attribute-storage.cpp [hunk 16]
```diff
@@ -878,6 +878,54 @@ static uint16_t findIndexFromEndpoint(EndpointId endpoint, bool ignoreDisabledEn
...
+        for (uint16_t i = 0; i < epIndex; i++)
+        {
+            // increase ajustedEndpointIndex for every endpoint containing the cluster server
```
Comment (bzbarsky-apple) [inline src/app/util/attribute-storage.cpp:906]:
```suggestion
            // Increase adjustedEndpointIndex for every endpoint containing the cluster server
```

File: src/app/util/attribute-storage.cpp [hunk 17]
```diff
@@ -878,6 +878,54 @@ static uint16_t findIndexFromEndpoint(EndpointId endpoint, bool ignoreDisabledEn
...
+            // before our endpoint of interest
+            if (emAfEndpoints[i].endpoint != kInvalidEndpointId &&
+                (emberAfFindClusterInType(emAfEndpoints[i].endpointType, cluster, CLUSTER_MASK_SERVER) != nullptr))
+            {
+                ajustedEndpointIndex++;
```
Comment (bzbarsky-apple) [inline src/app/util/attribute-storage.cpp:911]:
```suggestion
                adjustedEndpointIndex++;
```

File: src/app/util/attribute-storage.cpp [hunk 18]
```diff
@@ -878,6 +878,54 @@ static uint16_t findIndexFromEndpoint(EndpointId endpoint, bool ignoreDisabledEn
...
+            }
+        }
+
+        // If this asserts, The provided fixedClusterServerEndpointCount doesn't match the app data model"
```
Comment (bzbarsky-apple) [inline src/app/util/attribute-storage.cpp:915]:
```suggestion
        // If this asserts, the provided fixedClusterServerEndpointCount doesn't match the app data model.
```

File: src/app/util/attribute-storage.cpp [hunk 19]
```diff
@@ -878,6 +878,54 @@ static uint16_t findIndexFromEndpoint(EndpointId endpoint, bool ignoreDisabledEn
...
+        VerifyOrDie(ajustedEndpointIndex < fixedClusterServerEndpointCount);
+        epIndex = ajustedEndpointIndex;
```
Comment (bzbarsky-apple) [inline src/app/util/attribute-storage.cpp:917]:
```suggestion
        VerifyOrDie(adjustedEndpointIndex < fixedClusterServerEndpointCount);
        epIndex = adjustedEndpointIndex;
```

File: src/app/util/attribute-storage.cpp [hunk 20]
```diff
@@ -878,6 +878,54 @@ static uint16_t findIndexFromEndpoint(EndpointId endpoint, bool ignoreDisabledEn
...
+    }
+    else
+    {
+        // This is a dynamic endpoint.
+        // It's index is just its index in the dynamic endpoint list, offset by fixedClusterServerEndpointCount.
```
Comment (bzbarsky-apple) [inline src/app/util/attribute-storage.cpp:922]:
```suggestion
        // Its index is just its index in the dynamic endpoint list, offset by fixedClusterServerEndpointCount.
```

**Review by bzbarsky-apple — APPROVED** [review]
If we're keeping that loop, this looks good, with these bits fixed up.

**Review by tehampson — APPROVED** [review]
