### PR TITLE
Align Generic Diagnostics cluster with the latest spec

### LINKED ISSUE #10379: Broken API for Diagnostics cluster.
#### Problem
* Currently, Getter methods for some WiFi Diagnostic clusters attributes return 0 on failure. However, specs demand NULL value.
Spec -
`A value of NULL SHALL indicates that the interface is not currently configured or operational.`

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
What is being fixed?  Examples:
* Currently, Getter methods for some Generic Diagnostic clusters attributes return 0 on failure. However, specs demand NULL value.
* Fixes #10379 

#### Change overview
Align Generic Diagnostics cluster with the latest spec

#### Testing
How was this tested? (at least one bullet point required)
yufengw@yufengw-SEi:~/connectedhomeip/out/debug/standalone$ ./chip-tool generaldiagnostics read network-interfaces 
.......
[1644212595.921311][1076884:1076889] CHIP:DMG: ReportDataMessage =
[1644212595.921331][1076884:1076889] CHIP:DMG: {
[1644212595.921334][1076884:1076889] CHIP:DMG: 	AttributeReportIBs =
[1644212595.921362][1076884:1076889] CHIP:DMG: 	[
[1644212595.921365][1076884:1076889] CHIP:DMG: 		AttributeReportIB =
[1644212595.921371][1076884:1076889] CHIP:DMG: 		{
[1644212595.921375][1076884:1076889] CHIP:DMG: 			AttributeDataIB =
[1644212595.921379][1076884:1076889] CHIP:DMG: 			{
[1644212595.921384][1076884:1076889] CHIP:DMG: 				DataVersion = 0xbc938d6c,
[1644212595.921388][1076884:1076889] CHIP:DMG: 				AttributePathIB =
[1644212595.921392][1076884:1076889] CHIP:DMG: 				{
[1644212595.921397][1076884:1076889] CHIP:DMG: 					Endpoint = 0x0,
[1644212595.921401][1076884:1076889] CHIP:DMG: 					Cluster = 0x33,
[1644212595.921407][1076884:1076889] CHIP:DMG: 					Attribute = 0x0000_0000,
[1644212595.921411][1076884:1076889] CHIP:DMG: 				}
[1644212595.921416][1076884:1076889] CHIP:DMG: 					
[1644212595.921420][1076884:1076889] CHIP:DMG: 					Data = [
[1644212595.921425][1076884:1076889] CHIP:DMG: 						
[1644212595.921430][1076884:1076889] CHIP:DMG: 					],
[1644212595.921435][1076884:1076889] CHIP:DMG: 			},
[1644212595.921440][1076884:1076889] CHIP:DMG: 			
[1644212595.921444][1076884:1076889] CHIP:DMG: 		},
[1644212595.921451][1076884:1076889] CHIP:DMG: 		
[1644212595.921455][1076884:1076889] CHIP:DMG: 		AttributeReportIB =
[1644212595.921461][1076884:1076889] CHIP:DMG: 		{
[1644212595.921465][1076884:1076889] CHIP:DMG: 			AttributeDataIB =
[1644212595.921469][1076884:1076889] CHIP:DMG: 			{
[1644212595.921473][1076884:1076889] CHIP:DMG: 				DataVersion = 0xbc938d6c,
[1644212595.921477][1076884:1076889] CHIP:DMG: 				AttributePathIB =
[1644212595.921482][1076884:1076889] CHIP:DMG: 				{
[1644212595.921486][1076884:1076889] CHIP:DMG: 					Endpoint = 0x0,
[1644212595.921490][1076884:1076889] CHIP:DMG: 					Cluster = 0x33,
[1644212595.921495][1076884:1076889] CHIP:DMG: 					Attribute = 0x0000_0000,
[1644212595.921499][1076884:1076889] CHIP:DMG: 					ListIndex = Null,
[1644212595.921503][1076884:1076889] CHIP:DMG: 				}
[1644212595.921508][1076884:1076889] CHIP:DMG: 					
[1644212595.921512][1076884:1076889] CHIP:DMG: 					Data = 
[1644212595.921516][1076884:1076889] CHIP:DMG: 					{
[1644212595.921521][1076884:1076889] CHIP:DMG: 						0x0 = "veth7f4ceb2", 
[1644212595.921527][1076884:1076889] CHIP:DMG: 						0x1 = true, 
[1644212595.921532][1076884:1076889] CHIP:DMG: 						0x2 = false, 
[1644212595.921538][1076884:1076889] CHIP:DMG: 						0x3 = false, 
[1644212595.921543][1076884:1076889] CHIP:DMG: 						0x4 = [
[1644212595.921548][1076884:1076889] CHIP:DMG: 							0x1e, 0x98, 0xe8, 0x85, 0x8e, 0xcb, 
[1644212595.921553][1076884:1076889] CHIP:DMG: 						]
[1644212595.921559][1076884:1076889] CHIP:DMG: 						0x5 = 0, 
[1644212595.921564][1076884:1076889] CHIP:DMG: 					},
[1644212595.921568][1076884:1076889] CHIP:DMG: 			},
[1644212595.921574][1076884:1076889] CHIP:DMG: 			
[1644212595.921578][1076884:1076889] CHIP:DMG: 		},
[1644212595.921586][1076884:1076889] CHIP:DMG: 		
[1644212595.921590][1076884:1076889] CHIP:DMG: 		AttributeReportIB =
[1644212595.921596][1076884:1076889] CHIP:DMG: 		{
[1644212595.921600][1076884:1076889] CHIP:DMG: 			AttributeDataIB =
[1644212595.921603][1076884:1076889] CHIP:DMG: 			{
[1644212595.921608][1076884:1076889] CHIP:DMG: 				DataVersion = 0xbc938d6c,
[1644212595.921612][1076884:1076889] CHIP:DMG: 				AttributePathIB =
[1644212595.921616][1076884:1076889] CHIP:DMG: 				{
[1644212595.921621][1076884:1076889] CHIP:DMG: 					Endpoint = 0x0,
[1644212595.921628][1076884:1076889] CHIP:DMG: 					Cluster = 0x33,
[1644212595.921634][1076884:1076889] CHIP:DMG: 					Attribute = 0x0000_0000,
[1644212595.921640][1076884:1076889] CHIP:DMG: 					ListIndex = Null,
[1644212595.921645][1076884:1076889] CHIP:DMG: 				}
[1644212595.921652][1076884:1076889] CHIP:DMG: 					
[1644212595.921656][1076884:1076889] CHIP:DMG: 					Data = 
[1644212595.921661][1076884:1076889] CHIP:DMG: 					{
[1644212595.921667][1076884:1076889] CHIP:DMG: 						0x0 = "br-b26b7ebdfefb", 
[1644212595.921673][1076884:1076889] CHIP:DMG: 						0x1 = true, 
[1644212595.921680][1076884:1076889] CHIP:DMG: 						0x2 = false, 
[1644212595.921686][1076884:1076889] CHIP:DMG: 						0x3 = false, 
[1644212595.921692][1076884:1076889] CHIP:DMG: 						0x4 = [
[1644212595.921699][1076884:1076889] CHIP:DMG: 							0x2, 0x42, 0xd8, 0x1b, 0x21, 0xa1, 
[1644212595.921707][1076884:1076889] CHIP:DMG: 						]
[1644212595.921713][1076884:1076889] CHIP:DMG: 						0x5 = 0, 
[1644212595.921719][1076884:1076889] CHIP:DMG: 					},
[1644212595.921723][1076884:1076889] CHIP:DMG: 			},
[1644212595.921731][1076884:1076889] CHIP:DMG: 			
[1644212595.921734][1076884:1076889] CHIP:DMG: 		},
[1644212595.921745][1076884:1076889] CHIP:DMG: 		
[1644212595.921748][1076884:1076889] CHIP:DMG: 		AttributeReportIB =
[1644212595.921755][1076884:1076889] CHIP:DMG: 		{
[1644212595.921759][1076884:1076889] CHIP:DMG: 			AttributeDataIB =
[1644212595.921763][1076884:1076889] CHIP:DMG: 			{
[1644212595.921767][1076884:1076889] CHIP:DMG: 				DataVersion = 0xbc938d6c,
[1644212595.921771][1076884:1076889] CHIP:DMG: 				AttributePathIB =
[1644212595.921775][1076884:1076889] CHIP:DMG: 				{
[1644212595.921779][1076884:1076889] CHIP:DMG: 					Endpoint = 0x0,
[1644212595.921784][1076884:1076889] CHIP:DMG: 					Cluster = 0x33,
[1644212595.921790][1076884:1076889] CHIP:DMG: 					Attribute = 0x0000_0000,
[1644212595.921796][1076884:1076889] CHIP:DMG: 					ListIndex = Null,
[1644212595.921802][1076884:1076889] CHIP:DMG: 				}
[1644212595.921809][1076884:1076889] CHIP:DMG: 					
[1644212595.921814][1076884:1076889] CHIP:DMG: 					Data = 
[1644212595.921819][1076884:1076889] CHIP:DMG: 					{
[1644212595.921826][1076884:1076889] CHIP:DMG: 						0x0 = "br-ceecb05e7171", 
[1644212595.921832][1076884:1076889] CHIP:DMG: 						0x1 = false, 
[1644212595.921839][1076884:1076889] CHIP:DMG: 						0x2 = false, 
[1644212595.921846][1076884:1076889] CHIP:DMG: 						0x3 = false, 
[1644212595.921852][1076884:1076889] CHIP:DMG: 						0x4 = [
[1644212595.921860][1076884:1076889] CHIP:DMG: 							0x2, 0x42, 0x92, 0x67, 0x66, 0xa2, 
[1644212595.921866][1076884:1076889] CHIP:DMG: 						]
[1644212595.921873][1076884:1076889] CHIP:DMG: 						0x5 = 0, 
[1644212595.921878][1076884:1076889] CHIP:DMG: 					},
[1644212595.921881][1076884:1076889] CHIP:DMG: 			},
[1644212595.921888][1076884:1076889] CHIP:DMG: 			
[1644212595.921892][1076884:1076889] CHIP:DMG: 		},
[1644212595.921901][1076884:1076889] CHIP:DMG: 		
[1644212595.921905][1076884:1076889] CHIP:DMG: 		AttributeReportIB =
[1644212595.921911][1076884:1076889] CHIP:DMG: 		{
[1644212595.921915][1076884:1076889] CHIP:DMG: 			AttributeDataIB =
[1644212595.921919][1076884:1076889] CHIP:DMG: 			{
[1644212595.921923][1076884:1076889] CHIP:DMG: 				DataVersion = 0xbc938d6c,
[1644212595.921927][1076884:1076889] CHIP:DMG: 				AttributePathIB =
[1644212595.921931][1076884:1076889] CHIP:DMG: 				{
[1644212595.921935][1076884:1076889] CHIP:DMG: 					Endpoint = 0x0,
[1644212595.921941][1076884:1076889] CHIP:DMG: 					Cluster = 0x33,
[1644212595.921947][1076884:1076889] CHIP:DMG: 					Attribute = 0x0000_0000,
[1644212595.921952][1076884:1076889] CHIP:DMG: 					ListIndex = Null,
[1644212595.921958][1076884:1076889] CHIP:DMG: 				}
[1644212595.921965][1076884:1076889] CHIP:DMG: 					
[1644212595.921971][1076884:1076889] CHIP:DMG: 					Data = 
[1644212595.921977][1076884:1076889] CHIP:DMG: 					{
[1644212595.921984][1076884:1076889] CHIP:DMG: 						0x0 = "br-cdaf00c2e801", 
[1644212595.921991][1076884:1076889] CHIP:DMG: 						0x1 = false, 
[1644212595.921997][1076884:1076889] CHIP:DMG: 						0x2 = false, 
[1644212595.922004][1076884:1076889] CHIP:DMG: 						0x3 = false, 
[1644212595.922010][1076884:1076889] CHIP:DMG: 						0x4 = [
[1644212595.922016][1076884:1076889] CHIP:DMG: 							0x2, 0x42, 0xbc, 0xbe, 0xe1, 0x42, 
[1644212595.922023][1076884:1076889] CHIP:DMG: 						]
[1644212595.922028][1076884:1076889] CHIP:DMG: 						0x5 = 0, 
[1644212595.922033][1076884:1076889] CHIP:DMG: 					},
[1644212595.922039][1076884:1076889] CHIP:DMG: 			},
[1644212595.922047][1076884:1076889] CHIP:DMG: 			
[1644212595.922050][1076884:1076889] CHIP:DMG: 		},
[1644212595.922061][1076884:1076889] CHIP:DMG: 		
[1644212595.922065][1076884:1076889] CHIP:DMG: 		AttributeReportIB =
[1644212595.922073][1076884:1076889] CHIP:DMG: 		{
[1644212595.922077][1076884:1076889] CHIP:DMG: 			AttributeDataIB =
[1644212595.922082][1076884:1076889] CHIP:DMG: 			{
[1644212595.922088][1076884:1076889] CHIP:DMG: 				DataVersion = 0xbc938d6c,
[1644212595.922093][1076884:1076889] CHIP:DMG: 				AttributePathIB =
[1644212595.922098][1076884:1076889] CHIP:DMG: 				{
[1644212595.922103][1076884:1076889] CHIP:DMG: 					Endpoint = 0x0,
[1644212595.922108][1076884:1076889] CHIP:DMG: 					Cluster = 0x33,
[1644212595.922113][1076884:1076889] CHIP:DMG: 					Attribute = 0x0000_0000,
[1644212595.922118][1076884:1076889] CHIP:DMG: 					ListIndex = Null,
[1644212595.922123][1076884:1076889] CHIP:DMG: 				}
[1644212595.922128][1076884:1076889] CHIP:DMG: 					
[1644212595.922133][1076884:1076889] CHIP:DMG: 					Data = 
[1644212595.922139][1076884:1076889] CHIP:DMG: 					{
[1644212595.922146][1076884:1076889] CHIP:DMG: 						0x0 = "br-b0e20b6dfc46", 
[1644212595.922153][1076884:1076889] CHIP:DMG: 						0x1 = false, 
[1644212595.922159][1076884:1076889] CHIP:DMG: 						0x2 = false, 
[1644212595.922166][1076884:1076889] CHIP:DMG: 						0x3 = false, 
[1644212595.922172][1076884:1076889] CHIP:DMG: 						0x4 = [
[1644212595.922179][1076884:1076889] CHIP:DMG: 							0x2, 0x42, 0x47, 0x9a, 0x3c, 0x37, 
[1644212595.922186][1076884:1076889] CHIP:DMG: 						]
[1644212595.922192][1076884:1076889] CHIP:DMG: 						0x5 = 0, 
[1644212595.922200][1076884:1076889] CHIP:DMG: 					},
[1644212595.922206][1076884:1076889] CHIP:DMG: 			},
[1644212595.922214][1076884:1076889] CHIP:DMG: 			
[1644212595.922219][1076884:1076889] CHIP:DMG: 		},
[1644212595.922230][1076884:1076889] CHIP:DMG: 		
[1644212595.922233][1076884:1076889] CHIP:DMG: 		AttributeReportIB =
[1644212595.922241][1076884:1076889] CHIP:DMG: 		{
[1644212595.922245][1076884:1076889] CHIP:DMG: 			AttributeDataIB =
[1644212595.922249][1076884:1076889] CHIP:DMG: 			{
[1644212595.922254][1076884:1076889] CHIP:DMG: 				DataVersion = 0xbc938d6c,
[1644212595.922258][1076884:1076889] CHIP:DMG: 				AttributePathIB =
[1644212595.922264][1076884:1076889] CHIP:DMG: 				{
[1644212595.922270][1076884:1076889] CHIP:DMG: 					Endpoint = 0x0,
[1644212595.922276][1076884:1076889] CHIP:DMG: 					Cluster = 0x33,
[1644212595.922282][1076884:1076889] CHIP:DMG: 					Attribute = 0x0000_0000,
[1644212595.922286][1076884:1076889] CHIP:DMG: 					ListIndex = Null,
[1644212595.922290][1076884:1076889] CHIP:DMG: 				}
[1644212595.922295][1076884:1076889] CHIP:DMG: 					
[1644212595.922300][1076884:1076889] CHIP:DMG: 					Data = 
[1644212595.922306][1076884:1076889] CHIP:DMG: 					{
[1644212595.922313][1076884:1076889] CHIP:DMG: 						0x0 = "br-594fe2e87af5", 
[1644212595.922319][1076884:1076889] CHIP:DMG: 						0x1 = false, 
[1644212595.922326][1076884:1076889] CHIP:DMG: 						0x2 = false, 
[1644212595.922332][1076884:1076889] CHIP:DMG: 						0x3 = false, 
[1644212595.922337][1076884:1076889] CHIP:DMG: 						0x4 = [
[1644212595.922343][1076884:1076889] CHIP:DMG: 							0x2, 0x42, 0x2f, 0xa3, 0xe4, 0x72, 
[1644212595.922350][1076884:1076889] CHIP:DMG: 						]
[1644212595.922356][1076884:1076889] CHIP:DMG: 						0x5 = 0, 
[1644212595.922362][1076884:1076889] CHIP:DMG: 					},
[1644212595.922368][1076884:1076889] CHIP:DMG: 			},
[1644212595.922376][1076884:1076889] CHIP:DMG: 			
[1644212595.922380][1076884:1076889] CHIP:DMG: 		},
[1644212595.922390][1076884:1076889] CHIP:DMG: 		
[1644212595.922394][1076884:1076889] CHIP:DMG: 		AttributeReportIB =
[1644212595.922402][1076884:1076889] CHIP:DMG: 		{
[1644212595.922406][1076884:1076889] CHIP:DMG: 			AttributeDataIB =
[1644212595.922411][1076884:1076889] CHIP:DMG: 			{
[1644212595.922416][1076884:1076889] CHIP:DMG: 				DataVersion = 0xbc938d6c,
[1644212595.922421][1076884:1076889] CHIP:DMG: 				AttributePathIB =
[1644212595.922426][1076884:1076889] CHIP:DMG: 				{
[1644212595.922430][1076884:1076889] CHIP:DMG: 					Endpoint = 0x0,
[1644212595.922435][1076884:1076889] CHIP:DMG: 					Cluster = 0x33,
[1644212595.922439][1076884:1076889] CHIP:DMG: 					Attribute = 0x0000_0000,
[1644212595.922443][1076884:1076889] CHIP:DMG: 					ListIndex = Null,
[1644212595.922447][1076884:1076889] CHIP:DMG: 				}
[1644212595.922452][1076884:1076889] CHIP:DMG: 					
[1644212595.922455][1076884:1076889] CHIP:DMG: 					Data = 
[1644212595.922461][1076884:1076889] CHIP:DMG: 					{
[1644212595.922468][1076884:1076889] CHIP:DMG: 						0x0 = "br-4a6a83ee8f18", 
[1644212595.922474][1076884:1076889] CHIP:DMG: 						0x1 = false, 
[1644212595.922480][1076884:1076889] CHIP:DMG: 						0x2 = false, 
[1644212595.922487][1076884:1076889] CHIP:DMG: 						0x3 = false, 
[1644212595.922493][1076884:1076889] CHIP:DMG: 						0x4 = [
[1644212595.922499][1076884:1076889] CHIP:DMG: 							0x2, 0x42, 0xae, 0xae, 0x86, 0x7b, 
[1644212595.922506][1076884:1076889] CHIP:DMG: 						]
[1644212595.922513][1076884:1076889] CHIP:DMG: 						0x5 = 0, 
[1644212595.922519][1076884:1076889] CHIP:DMG: 					},
[1644212595.922524][1076884:1076889] CHIP:DMG: 			},
[1644212595.922531][1076884:1076889] CHIP:DMG: 			
[1644212595.922535][1076884:1076889] CHIP:DMG: 		},
[1644212595.922544][1076884:1076889] CHIP:DMG: 		
[1644212595.922548][1076884:1076889] CHIP:DMG: 		AttributeReportIB =
[1644212595.922556][1076884:1076889] CHIP:DMG: 		{
[1644212595.922560][1076884:1076889] CHIP:DMG: 			AttributeDataIB =
[1644212595.922564][1076884:1076889] CHIP:DMG: 			{
[1644212595.922569][1076884:1076889] CHIP:DMG: 				DataVersion = 0xbc938d6c,
[1644212595.922573][1076884:1076889] CHIP:DMG: 				AttributePathIB =
[1644212595.922578][1076884:1076889] CHIP:DMG: 				{
[1644212595.922583][1076884:1076889] CHIP:DMG: 					Endpoint = 0x0,
[1644212595.922590][1076884:1076889] CHIP:DMG: 					Cluster = 0x33,
[1644212595.922596][1076884:1076889] CHIP:DMG: 					Attribute = 0x0000_0000,
[1644212595.922602][1076884:1076889] CHIP:DMG: 					ListIndex = Null,
[1644212595.922608][1076884:1076889] CHIP:DMG: 				}
[1644212595.922613][1076884:1076889] CHIP:DMG: 					
[1644212595.922617][1076884:1076889] CHIP:DMG: 					Data = 
[1644212595.922624][1076884:1076889] CHIP:DMG: 					{
[1644212595.922629][1076884:1076889] CHIP:DMG: 						0x0 = "br-3aa0866d12a7", 
[1644212595.922635][1076884:1076889] CHIP:DMG: 						0x1 = false, 
[1644212595.922641][1076884:1076889] CHIP:DMG: 						0x2 = false, 
[1644212595.922648][1076884:1076889] CHIP:DMG: 						0x3 = false, 
[1644212595.922655][1076884:1076889] CHIP:DMG: 						0x4 = [
[1644212595.922661][1076884:1076889] CHIP:DMG: 							0x2, 0x42, 0x2f, 0x1a, 0x3c, 0x73, 
[1644212595.922667][1076884:1076889] CHIP:DMG: 						]
[1644212595.922674][1076884:1076889] CHIP:DMG: 						0x5 = 0, 
[1644212595.922679][1076884:1076889] CHIP:DMG: 					},
[1644212595.922685][1076884:1076889] CHIP:DMG: 			},
[1644212595.922692][1076884:1076889] CHIP:DMG: 			
[1644212595.922696][1076884:1076889] CHIP:DMG: 		},
[1644212595.922706][1076884:1076889] CHIP:DMG: 		
[1644212595.922710][1076884:1076889] CHIP:DMG: 		AttributeReportIB =
[1644212595.922717][1076884:1076889] CHIP:DMG: 		{
[1644212595.922721][1076884:1076889] CHIP:DMG: 			AttributeDataIB =
[1644212595.922725][1076884:1076889] CHIP:DMG: 			{
[1644212595.922729][1076884:1076889] CHIP:DMG: 				DataVersion = 0xbc938d6c,
[1644212595.922734][1076884:1076889] CHIP:DMG: 				AttributePathIB =
[1644212595.922739][1076884:1076889] CHIP:DMG: 				{
[1644212595.922744][1076884:1076889] CHIP:DMG: 					Endpoint = 0x0,
[1644212595.922749][1076884:1076889] CHIP:DMG: 					Cluster = 0x33,
[1644212595.922756][1076884:1076889] CHIP:DMG: 					Attribute = 0x0000_0000,
[1644212595.922762][1076884:1076889] CHIP:DMG: 					ListIndex = Null,
[1644212595.922768][1076884:1076889] CHIP:DMG: 				}
[1644212595.922774][1076884:1076889] CHIP:DMG: 					
[1644212595.922780][1076884:1076889] CHIP:DMG: 					Data = 
[1644212595.922786][1076884:1076889] CHIP:DMG: 					{
[1644212595.922791][1076884:1076889] CHIP:DMG: 						0x0 = "docker0", 
[1644212595.922797][1076884:1076889] CHIP:DMG: 						0x1 = false, 
[1644212595.922804][1076884:1076889] CHIP:DMG: 						0x2 = false, 
[1644212595.922811][1076884:1076889] CHIP:DMG: 						0x3 = false, 
[1644212595.922818][1076884:1076889] CHIP:DMG: 						0x4 = [
[1644212595.922848][1076884:1076889] CHIP:DMG: 							0x2, 0x42, 0x53, 0x6e, 0x2a, 0x80, 
[1644212595.922854][1076884:1076889] CHIP:DMG: 						]
[1644212595.922861][1076884:1076889] CHIP:DMG: 						0x5 = 0, 
[1644212595.922867][1076884:1076889] CHIP:DMG: 					},
[1644212595.922872][1076884:1076889] CHIP:DMG: 			},
[1644212595.922879][1076884:1076889] CHIP:DMG: 			
[1644212595.922884][1076884:1076889] CHIP:DMG: 		},
[1644212595.922895][1076884:1076889] CHIP:DMG: 		
[1644212595.922899][1076884:1076889] CHIP:DMG: 		AttributeReportIB =
[1644212595.922907][1076884:1076889] CHIP:DMG: 		{
[1644212595.922910][1076884:1076889] CHIP:DMG: 			AttributeDataIB =
[1644212595.922915][1076884:1076889] CHIP:DMG: 			{
[1644212595.922919][1076884:1076889] CHIP:DMG: 				DataVersion = 0xbc938d6c,
[1644212595.922923][1076884:1076889] CHIP:DMG: 				AttributePathIB =
[1644212595.922927][1076884:1076889] CHIP:DMG: 				{
[1644212595.922931][1076884:1076889] CHIP:DMG: 					Endpoint = 0x0,
[1644212595.922935][1076884:1076889] CHIP:DMG: 					Cluster = 0x33,
[1644212595.922940][1076884:1076889] CHIP:DMG: 					Attribute = 0x0000_0000,
[1644212595.922945][1076884:1076889] CHIP:DMG: 					ListIndex = Null,
[1644212595.922952][1076884:1076889] CHIP:DMG: 				}
[1644212595.922958][1076884:1076889] CHIP:DMG: 					
[1644212595.922963][1076884:1076889] CHIP:DMG: 					Data = 
[1644212595.922969][1076884:1076889] CHIP:DMG: 					{
[1644212595.922976][1076884:1076889] CHIP:DMG: 						0x0 = "wlp3s0", 
[1644212595.922981][1076884:1076889] CHIP:DMG: 						0x1 = true, 
[1644212595.922988][1076884:1076889] CHIP:DMG: 						0x2 = false, 
[1644212595.922994][1076884:1076889] CHIP:DMG: 						0x3 = false, 
[1644212595.923000][1076884:1076889] CHIP:DMG: 						0x4 = [
[1644212595.923008][1076884:1076889] CHIP:DMG: 							0xb0, 0xa4, 0x60, 0xe, 0xcf, 0xae, 
[1644212595.923018][1076884:1076889] CHIP:DMG: 						]
[1644212595.923024][1076884:1076889] CHIP:DMG: 						0x5 = 1, 
[1644212595.923030][1076884:1076889] CHIP:DMG: 					},
[1644212595.923036][1076884:1076889] CHIP:DMG: 			},
[1644212595.923043][1076884:1076889] CHIP:DMG: 			
[1644212595.923047][1076884:1076889] CHIP:DMG: 		},
[1644212595.923058][1076884:1076889] CHIP:DMG: 		
[1644212595.923062][1076884:1076889] CHIP:DMG: 		AttributeReportIB =
[1644212595.923070][1076884:1076889] CHIP:DMG: 		{
[1644212595.923074][1076884:1076889] CHIP:DMG: 			AttributeDataIB =
[1644212595.923078][1076884:1076889] CHIP:DMG: 			{
[1644212595.923082][1076884:1076889] CHIP:DMG: 				DataVersion = 0xbc938d6c,
[1644212595.923085][1076884:1076889] CHIP:DMG: 				AttributePathIB =
[1644212595.923090][1076884:1076889] CHIP:DMG: 				{
[1644212595.923094][1076884:1076889] CHIP:DMG: 					Endpoint = 0x0,
[1644212595.923098][1076884:1076889] CHIP:DMG: 					Cluster = 0x33,
[1644212595.923104][1076884:1076889] CHIP:DMG: 					Attribute = 0x0000_0000,
[1644212595.923109][1076884:1076889] CHIP:DMG: 					ListIndex = Null,
[1644212595.923133][1076884:1076889] CHIP:DMG: 				}
[1644212595.923142][1076884:1076889] CHIP:DMG: 					
[1644212595.923148][1076884:1076889] CHIP:DMG: 					Data = 
[1644212595.923156][1076884:1076889] CHIP:DMG: 					{
[1644212595.923163][1076884:1076889] CHIP:DMG: 						0x0 = "enp1s0", 
[1644212595.923170][1076884:1076889] CHIP:DMG: 						0x1 = false, 
[1644212595.923178][1076884:1076889] CHIP:DMG: 						0x2 = false, 
[1644212595.923186][1076884:1076889] CHIP:DMG: 						0x3 = false, 
[1644212595.923194][1076884:1076889] CHIP:DMG: 						0x4 = [
[1644212595.923203][1076884:1076889] CHIP:DMG: 							0x5c, 0x85, 0x7e, 0x48, 0x5e, 0xac, 
[1644212595.923211][1076884:1076889] CHIP:DMG: 						]
[1644212595.923219][1076884:1076889] CHIP:DMG: 						0x5 = 2, 
[1644212595.923227][1076884:1076889] CHIP:DMG: 					},
[1644212595.923234][1076884:1076889] CHIP:DMG: 			},
[1644212595.923243][1076884:1076889] CHIP:DMG: 			
[1644212595.923247][1076884:1076889] CHIP:DMG: 		},
[1644212595.923259][1076884:1076889] CHIP:DMG: 		
[1644212595.923263][1076884:1076889] CHIP:DMG: 		AttributeReportIB =
[1644212595.923271][1076884:1076889] CHIP:DMG: 		{
[1644212595.923276][1076884:1076889] CHIP:DMG: 			AttributeDataIB =
[1644212595.923281][1076884:1076889] CHIP:DMG: 			{
[1644212595.923287][1076884:1076889] CHIP:DMG: 				DataVersion = 0xbc938d6c,
[1644212595.923293][1076884:1076889] CHIP:DMG: 				AttributePathIB =
[1644212595.923298][1076884:1076889] CHIP:DMG: 				{
[1644212595.923304][1076884:1076889] CHIP:DMG: 					Endpoint = 0x0,
[1644212595.923309][1076884:1076889] CHIP:DMG: 					Cluster = 0x33,
[1644212595.923316][1076884:1076889] CHIP:DMG: 					Attribute = 0x0000_0000,
[1644212595.923324][1076884:1076889] CHIP:DMG: 					ListIndex = Null,
[1644212595.923331][1076884:1076889] CHIP:DMG: 				}
[1644212595.923339][1076884:1076889] CHIP:DMG: 					
[1644212595.923346][1076884:1076889] CHIP:DMG: 					Data = 
[1644212595.923352][1076884:1076889] CHIP:DMG: 					{
[1644212595.923358][1076884:1076889] CHIP:DMG: 						0x0 = "lo", 
[1644212595.923366][1076884:1076889] CHIP:DMG: 						0x1 = true, 
[1644212595.923374][1076884:1076889] CHIP:DMG: 						0x2 = false, 
[1644212595.923382][1076884:1076889] CHIP:DMG: 						0x3 = false, 
[1644212595.923390][1076884:1076889] CHIP:DMG: 						0x4 = [
[1644212595.923399][1076884:1076889] CHIP:DMG: 							0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 
[1644212595.923408][1076884:1076889] CHIP:DMG: 						]
[1644212595.923417][1076884:1076889] CHIP:DMG: 						0x5 = 0, 
[1644212595.923426][1076884:1076889] CHIP:DMG: 					},
[1644212595.923431][1076884:1076889] CHIP:DMG: 			},
[1644212595.923439][1076884:1076889] CHIP:DMG: 			
[1644212595.923444][1076884:1076889] CHIP:DMG: 		},
[1644212595.923451][1076884:1076889] CHIP:DMG: 		
[1644212595.923456][1076884:1076889] CHIP:DMG: 	],
[1644212595.923496][1076884:1076889] CHIP:DMG: 	
[1644212595.923501][1076884:1076889] CHIP:DMG: 	SuppressResponse = true, 
[1644212595.923505][1076884:1076889] CHIP:DMG: 	InteractionModelRevision = 1
[1644212595.923510][1076884:1076889] CHIP:DMG: }
[1644212595.923978][1076884:1076889] CHIP:TOO: Endpoint: 0 Cluster: 0x0000_0033 Attribute 0x0000_0000
[1644212595.924028][1076884:1076889] CHIP:TOO:   NetworkInterfaces: 12 entries
[1644212595.924058][1076884:1076889] CHIP:TOO:     [1]: {
[1644212595.924064][1076884:1076889] CHIP:TOO:       Name: veth7f4ceb2
[1644212595.924070][1076884:1076889] CHIP:TOO:       FabricConnected: TRUE
[1644212595.924082][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv4: FALSE
[1644212595.924087][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv6: FALSE
[1644212595.924092][1076884:1076889] CHIP:TOO:       HardwareAddress: 1E98E8858ECB
[1644212595.924097][1076884:1076889] CHIP:TOO:       Type: 0
[1644212595.924102][1076884:1076889] CHIP:TOO:      }
[1644212595.924111][1076884:1076889] CHIP:TOO:     [2]: {
[1644212595.924115][1076884:1076889] CHIP:TOO:       Name: br-b26b7ebdfefb
[1644212595.924119][1076884:1076889] CHIP:TOO:       FabricConnected: TRUE
[1644212595.924124][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv4: FALSE
[1644212595.924128][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv6: FALSE
[1644212595.924133][1076884:1076889] CHIP:TOO:       HardwareAddress: 0242D81B21A1
[1644212595.924137][1076884:1076889] CHIP:TOO:       Type: 0
[1644212595.924142][1076884:1076889] CHIP:TOO:      }
[1644212595.924149][1076884:1076889] CHIP:TOO:     [3]: {
[1644212595.924153][1076884:1076889] CHIP:TOO:       Name: br-ceecb05e7171
[1644212595.924175][1076884:1076889] CHIP:TOO:       FabricConnected: FALSE
[1644212595.924178][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv4: FALSE
[1644212595.924181][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv6: FALSE
[1644212595.924185][1076884:1076889] CHIP:TOO:       HardwareAddress: 0242926766A2
[1644212595.924188][1076884:1076889] CHIP:TOO:       Type: 0
[1644212595.924192][1076884:1076889] CHIP:TOO:      }
[1644212595.924197][1076884:1076889] CHIP:TOO:     [4]: {
[1644212595.924201][1076884:1076889] CHIP:TOO:       Name: br-cdaf00c2e801
[1644212595.924204][1076884:1076889] CHIP:TOO:       FabricConnected: FALSE
[1644212595.924208][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv4: FALSE
[1644212595.924211][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv6: FALSE
[1644212595.924215][1076884:1076889] CHIP:TOO:       HardwareAddress: 0242BCBEE142
[1644212595.924218][1076884:1076889] CHIP:TOO:       Type: 0
[1644212595.924221][1076884:1076889] CHIP:TOO:      }
[1644212595.924227][1076884:1076889] CHIP:TOO:     [5]: {
[1644212595.924230][1076884:1076889] CHIP:TOO:       Name: br-b0e20b6dfc46
[1644212595.924234][1076884:1076889] CHIP:TOO:       FabricConnected: FALSE
[1644212595.924237][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv4: FALSE
[1644212595.924240][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv6: FALSE
[1644212595.924245][1076884:1076889] CHIP:TOO:       HardwareAddress: 0242479A3C37
[1644212595.924250][1076884:1076889] CHIP:TOO:       Type: 0
[1644212595.924254][1076884:1076889] CHIP:TOO:      }
[1644212595.924262][1076884:1076889] CHIP:TOO:     [6]: {
[1644212595.924265][1076884:1076889] CHIP:TOO:       Name: br-594fe2e87af5
[1644212595.924270][1076884:1076889] CHIP:TOO:       FabricConnected: FALSE
[1644212595.924274][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv4: FALSE
[1644212595.924278][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv6: FALSE
[1644212595.924282][1076884:1076889] CHIP:TOO:       HardwareAddress: 02422FA3E472
[1644212595.924287][1076884:1076889] CHIP:TOO:       Type: 0
[1644212595.924291][1076884:1076889] CHIP:TOO:      }
[1644212595.924298][1076884:1076889] CHIP:TOO:     [7]: {
[1644212595.924302][1076884:1076889] CHIP:TOO:       Name: br-4a6a83ee8f18
[1644212595.924306][1076884:1076889] CHIP:TOO:       FabricConnected: FALSE
[1644212595.924310][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv4: FALSE
[1644212595.924314][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv6: FALSE
[1644212595.924319][1076884:1076889] CHIP:TOO:       HardwareAddress: 0242AEAE867B
[1644212595.924323][1076884:1076889] CHIP:TOO:       Type: 0
[1644212595.924328][1076884:1076889] CHIP:TOO:      }
[1644212595.924335][1076884:1076889] CHIP:TOO:     [8]: {
[1644212595.924339][1076884:1076889] CHIP:TOO:       Name: br-3aa0866d12a7
[1644212595.924343][1076884:1076889] CHIP:TOO:       FabricConnected: FALSE
[1644212595.924347][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv4: FALSE
[1644212595.924351][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv6: FALSE
[1644212595.924355][1076884:1076889] CHIP:TOO:       HardwareAddress: 02422F1A3C73
[1644212595.924360][1076884:1076889] CHIP:TOO:       Type: 0
[1644212595.924364][1076884:1076889] CHIP:TOO:      }
[1644212595.924371][1076884:1076889] CHIP:TOO:     [9]: {
[1644212595.924375][1076884:1076889] CHIP:TOO:       Name: docker0
[1644212595.924379][1076884:1076889] CHIP:TOO:       FabricConnected: FALSE
[1644212595.924383][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv4: FALSE
[1644212595.924387][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv6: FALSE
[1644212595.924391][1076884:1076889] CHIP:TOO:       HardwareAddress: 0242536E2A80
[1644212595.924395][1076884:1076889] CHIP:TOO:       Type: 0
[1644212595.924399][1076884:1076889] CHIP:TOO:      }
[1644212595.924406][1076884:1076889] CHIP:TOO:     [10]: {
[1644212595.924410][1076884:1076889] CHIP:TOO:       Name: wlp3s0
[1644212595.924414][1076884:1076889] CHIP:TOO:       FabricConnected: TRUE
[1644212595.924419][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv4: FALSE
[1644212595.924423][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv6: FALSE
[1644212595.924428][1076884:1076889] CHIP:TOO:       HardwareAddress: B0A4600ECFAE
[1644212595.924432][1076884:1076889] CHIP:TOO:       Type: 1
[1644212595.924436][1076884:1076889] CHIP:TOO:      }
[1644212595.924444][1076884:1076889] CHIP:TOO:     [11]: {
[1644212595.924448][1076884:1076889] CHIP:TOO:       Name: enp1s0
[1644212595.924452][1076884:1076889] CHIP:TOO:       FabricConnected: FALSE
[1644212595.924456][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv4: FALSE
[1644212595.924460][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv6: FALSE
[1644212595.924465][1076884:1076889] CHIP:TOO:       HardwareAddress: 5C857E485EAC
[1644212595.924470][1076884:1076889] CHIP:TOO:       Type: 2
[1644212595.924474][1076884:1076889] CHIP:TOO:      }
[1644212595.924481][1076884:1076889] CHIP:TOO:     [12]: {
[1644212595.924485][1076884:1076889] CHIP:TOO:       Name: lo
[1644212595.924489][1076884:1076889] CHIP:TOO:       FabricConnected: TRUE
[1644212595.924493][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv4: FALSE
[1644212595.924497][1076884:1076889] CHIP:TOO:       OffPremiseServicesReachableIPv6: FALSE
[1644212595.924501][1076884:1076889] CHIP:TOO:       HardwareAddress: 000000000000
[1644212595.924505][1076884:1076889] CHIP:TOO:       Type: 0
[1644212595.924509][1076884:1076889] CHIP:TOO:      }

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

File: src/platform/Ameba/DiagnosticDataProviderImpl.cpp [hunk 1]
```diff
@@ -143,8 +143,8 @@ CHIP_ERROR DiagnosticDataProviderImpl::GetNetworkInterfaces(NetworkInterface **
                 ifp->type = EMBER_ZCL_INTERFACE_TYPE_ETHERNET;
             else
                 ifp->type = EMBER_ZCL_INTERFACE_TYPE_WI_FI;
-            ifp->offPremiseServicesReachableIPv4 = false;
-            ifp->offPremiseServicesReachableIPv6 = false;
+            ifp->offPremiseServicesReachableIPv4.SetNonNull(false);
+            ifp->offPremiseServicesReachableIPv6.SetNonNull(false);
```
Comment (bzbarsky-apple) [inline src/platform/Ameba/DiagnosticDataProviderImpl.cpp:147]: This is wrong, per spec.  Filed https://github.com/project-chip/connectedhomeip/issues/14936

Comment (yufengwangca) [reply src/platform/Ameba/DiagnosticDataProviderImpl.cpp:147]: https://github.com/project-chip/connectedhomeip/pull/15008
