### PR TITLE
[Darwin] MTRDevice shouldn't persist data version if report gets interrupted

### LINKED ISSUE #37364: [Darwin] MTRDevice attribute cache handling of DataVersion does not handle subscription interruption well
### Reproduction steps

Two issues:

1. We "commit" the new DataVersion to the in-memory store immediately, not at end of report, so if that store is used for a resubscribe (e.g. after a suspend/resume), we may have the "new" DataVersion but still "old" data for some attributes.
2. We are setting up the "cluster data to persist" as we go; on subscription interrupt we should probably clear it out so it does not get persisted by accident in a partially-received state.

### Platform

darwin

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jtung-apple**
Fixes #37364

See the issue for details. Also, this change also ensures that if persistence timer hits and MTRDevice is receiving a report, that persistence is postponed.

#### Testing

Adding unit test to test for when a report is interrupted.

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRDevice_Concrete.mm [hunk 1]
```diff
@@ -3922,7 +3952,7 @@ - (void)_noteDataVersion:(NSNumber *)dataVersion forClusterPath:(MTRClusterPath
         clusterData = [[MTRDeviceClusterData alloc] initWithDataVersion:dataVersion attributes:nil];
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice_Concrete.mm:3952]: This needs to set the pending data version, not the current one, right?

File: src/darwin/Framework/CHIP/MTRDeviceClusterData.h [hunk 2]
```diff
@@ -26,6 +26,7 @@ NS_ASSUME_NONNULL_BEGIN
 MTR_TESTABLE
 @interface MTRDeviceClusterData : NSObject <NSSecureCoding, NSCopying>
 @property (nonatomic, nullable) NSNumber * dataVersion;
+@property (nonatomic, nullable) NSNumber * pendingDataVersion; // for holding new data version during a report
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDeviceClusterData.h:29]: Should document here, or in the impl, or both, that this is not encoded/decoded?

File: src/darwin/Framework/CHIP/MTRDevice_Concrete.mm (hunk 1 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice_Concrete.mm]: Thanks for catching this, which is actually the common case for very first report. I've made the change

File: src/darwin/Framework/CHIP/MTRDeviceClusterData.h (hunk 2 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDeviceClusterData.h]: Added light documentation in comment.

**Review by bzbarsky-apple — APPROVED** [review]
