### PR TITLE
Only do address updates for CASE delivery failures.

### LINKED ISSUE #22326: Stop trying to update addresses for non-CASE sessions
#### Problem
We try to update the address for non-CASE sessions (because the checks for "is this session that failed to deliver a message a CASE session?" got lost during the CASE refactors).  This at best leads to spurious error logs and at worst leads to extra dns-sd traffic that actually makes the delivery problems worse.

 #### Proposed Solution
Add back the "is this CASE?" checks.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
When the handling of "failed to send message, so update the IP for this peer"
moved out of DeviceCommissioner, we stopped checking whether the session is a
CASE session.  Go back to checking that again.

Fixes https://github.com/project-chip/connectedhomeip/issues/22326

#### Problem
See #22326.

#### Change overview
Check that we're dealing with a CASE session before we try to find a new IP for it.

#### Testing
Tried doing a CASE handshake with a device that was not responding; observed that we don't try to re-resolve for the failed-delivery handshake messages (which are happening on an unauthenticated session, not a CASE session).

### CODE REVIEW

**Review by jmartinez-silabs — APPROVED** [review]

File: src/messaging/ReliableMessageMgr.cpp [hunk 1]
```diff
@@ -320,7 +320,8 @@ CHIP_ERROR ReliableMessageMgr::SendFromRetransTable(RetransTableEntry * entry)
         if (exchangeMgr)
         {
             // After the first failure notify session manager to refresh device data
-            if (entry->sendCount == 1 && mSessionUpdateDelegate != nullptr)
+            if (entry->sendCount == 1 && mSessionUpdateDelegate != nullptr && entry->ec->GetSessionHandle()->IsSecureSession() &&
+                entry->ec->GetSessionHandle()->AsSecureSession()->IsCASESession())
```
Comment (tcarmelveilleux) [inline src/messaging/ReliableMessageMgr.cpp:324]: Why not also PASE sessions over IP? Why just CASE?

**Review by tcarmelveilleux — APPROVED** [review]

File: src/messaging/ReliableMessageMgr.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/messaging/ReliableMessageMgr.cpp:324]: Because the information we pass in (the "peer id") can't be used to do commissionable discovery to obtain a new IP for a PASE session.  It can only be used for operational discovery.

File: src/app/OperationalSessionSetup.cpp [hunk 2]
```diff
@@ -411,7 +411,7 @@ void OperationalSessionSetup::PerformAddressUpdate()
     CHIP_ERROR err = LookupPeerAddress();
     if (err != CHIP_NO_ERROR)
     {
-        ChipLogError(Controller, "PerformAddressUpdate could not perform lookup");
+        ChipLogError(Controller, "PerformAddressUpdate could not perform lookup: %" CHIP_ERROR_FORMAT, err.Format());
```
Comment (Damian-Nordic) [inline src/app/OperationalSessionSetup.cpp:414]: Collission with https://github.com/project-chip/connectedhomeip/pull/22335

**Review by Damian-Nordic — APPROVED** [review]

File: src/app/OperationalSessionSetup.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/app/OperationalSessionSetup.cpp]: Aligned with the wording in that PR, so things will merge cleanly in either direction.

**Comment by andy31415** [comment]
Marking accepted for 1.0: judgement call as this being a small but significant value change.
