### PR TITLE
[ESP32] Set credential type and index to passed-in credentials

### LINKED ISSUE #25083: esp32 lock-app does something weird with credentials in BoltLockManager::SetUser
It's overriding the type and index of the passed-in credentials with other values, which looks wrong to me. At the very least it needs a comment explaining why it's doing that and why that's not a spec violation.

@shubhamdp @dhrishi

### PR DESCRIPTION
**Pull request by jadhavrohit924**
Problem:

Fixes #25083.

Changes:

Set credential type and index to passed-in credentials.

Testing:

Tested by setting user credentials.

### CODE REVIEW

File: examples/platform/esp32/lock/BoltLockManager.cpp [hunk 1]
```diff
@@ -431,11 +431,8 @@ bool BoltLockManager::SetUser(chip::EndpointId endpointId, uint16_t userIndex, c
     for (size_t i = 0; i < totalCredentials; ++i)
     {
         mCredentials[userIndex][i] = credentials[i];
-        // TODO: Why are we modifying the passed-in credentials?
-        // https://github.com/project-chip/connectedhomeip/issues/25083
-        // For now, preserve pre-existing behavior, which set credentialType to 1.
-        mCredentials[userIndex][i].credentialType  = CredentialTypeEnum::kPin;
-        mCredentials[userIndex][i].credentialIndex = i + 1;
+        mCredentials[userIndex][i].credentialType  = credentials[i].credentialType;
+        mCredentials[userIndex][i].credentialIndex = credentials[i].credentialIndex;
```
Comment (bzbarsky-apple) [inline examples/platform/esp32/lock/BoltLockManager.cpp:435]: Why are these two lines needed?

Comment (jadhavrohit924) [reply examples/platform/esp32/lock/BoltLockManager.cpp]: Used memcpy instead.

Comment (yufengwangca) [reply examples/platform/esp32/lock/BoltLockManager.cpp]: memcpy only reset the first totalCredentials credentials, do we need to clear mCredentials before the memcpy?

File: examples/platform/esp32/lock/BoltLockManager.cpp [hunk 2]
```diff
@@ -428,15 +428,7 @@ bool BoltLockManager::SetUser(chip::EndpointId endpointId, uint16_t userIndex, c
...
-    for (size_t i = 0; i < totalCredentials; ++i)
-    {
-        mCredentials[userIndex][i] = credentials[i];
-        // TODO: Why are we modifying the passed-in credentials?
-        // https://github.com/project-chip/connectedhomeip/issues/25083
-        // For now, preserve pre-existing behavior, which set credentialType to 1.
-        mCredentials[userIndex][i].credentialType  = CredentialTypeEnum::kPin;
-        mCredentials[userIndex][i].credentialIndex = i + 1;
-    }
+    memcpy(mCredentials, credentials, totalCredentials * sizeof(CredentialStruct));
```
Comment (bzbarsky-apple) [inline examples/platform/esp32/lock/BoltLockManager.cpp:431]: Can you explain to me, in detail, why this memcpy is the right thing to do?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: examples/platform/esp32/lock/BoltLockManager.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply examples/platform/esp32/lock/BoltLockManager.cpp]: This part is not an issue, because the the actual thing we store is a Span with the provided length, so we don't look outside of that length.

File: examples/platform/esp32/lock/BoltLockManager.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply examples/platform/esp32/lock/BoltLockManager.cpp]: memcpy is fine for copying credentials _if you are copying to the right memory_. Which the above code was not.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by dhrishi — APPROVED** [review]

**Review by dhrishi — APPROVED** [review]
