### PR TITLE
Import door lock cluster

### LINKED ISSUE #2054: Import ../third_party/connectedhomeip/src/app/clusters/door-lock-server
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

### PR DESCRIPTION
**Pull request by shana-apple**
Uncomment door lock cluster and get it compiling

fixes #2054

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

File: src/app/clusters/door-lock-server/door-lock-server-logging.c [hunk 1]
```diff
@@ -66,7 +67,8 @@ static bool loggingIsEnabled(void)
 bool emberAfPluginDoorLockServerAddLogEntry(EmberAfDoorLockEventType eventType, EmberAfDoorLockEventSource source, uint8_t eventId,
                                             uint16_t userId, uint8_t pinLength, uint8_t * pin)
 {
-    if (!loggingIsEnabled() || ENTRY_ID_TO_INDEX(nextEntryId) >= COUNTOF(entries))
+    if (!loggingIsEnabled() ||
+        ENTRY_ID_TO_INDEX(nextEntryId) >= (sizeof(entries) / sizeof((entries)[0]))) /* COUNTOF(entries) #2499 */
```
Comment (rwalker-apple) [inline src/app/clusters/door-lock-server/door-lock-server-logging.c:71]: please use ArraySize from CodeUtils.h

File: src/app/clusters/door-lock-server/door-lock-server-logging.c [hunk 2]
```diff
@@ -82,7 +84,7 @@ bool emberAfPluginDoorLockServerAddLogEntry(EmberAfDoorLockEventType eventType,
     uint8_t moveLength =
         (pinLength > EMBER_AF_PLUGIN_DOOR_LOCK_SERVER_MAX_PIN_LENGTH ? EMBER_AF_PLUGIN_DOOR_LOCK_SERVER_MAX_PIN_LENGTH : pinLength);
     nextEntry->pin[0] = moveLength;
-    MEMMOVE(nextEntry->pin + 1, pin, moveLength);
+    memmove(nextEntry->pin + 1, pin, moveLength); /*MEMMOVE #2500*/
```
Comment (rwalker-apple) [inline src/app/clusters/door-lock-server/door-lock-server-logging.c:87]: I've closed these issues, you can remove the comments.

**Review by rwalker-apple — CHANGES_REQUESTED** [review]
just a couple small things

**Review by mspang — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

File: src/app/clusters/door-lock-server/door-lock-server-schedule.c [hunk 3]
```diff
@@ -156,7 +156,7 @@ bool emberAfDoorLockClusterSetWeekdayScheduleCallback(uint8_t scheduleId, uint16
     if (rfProgrammingEventMask & BIT(0))
     {
         emberAfFillCommandDoorLockClusterProgrammingEventNotification(0x01, 0x00, userId, &userPin, 0x00, 0x00, 0x00, &userPin);
-        SEND_COMMAND_UNICAST_TO_BINDINGS();
+        // SEND_COMMAND_UNICAST_TO_BINDINGS();
```
Comment (vivien-apple) [inline src/app/clusters/door-lock-server/door-lock-server-schedule.c:159]: If the cli API is removed can't we simply remove those calls and remove the declaration at https://github.com/project-chip/connectedhomeip/blob/74798d4d23b1ca50177b5802fd0e3cb13b0d1a92/src/app/util/af.h#L1382 ?

File: src/app/clusters/door-lock-server/door-lock-server-user.c [hunk 4]
```diff
@@ -609,7 +612,9 @@ static void startLockout()
     uint8_t lockoutTimeS = getUserCodeTemporaryDisableTime();
     if (lockoutTimeS != 0)
     {
-        emberEventControlSetDelayMS(emberAfPluginDoorLockServerLockoutEventControl, lockoutTimeS * MILLISECOND_TICKS_PER_SECOND);
+        /*emberEventControlSetDelayMS(emberAfPluginDoorLockServerLockoutEventControl, lockoutTimeS * MILLISECOND_TICKS_PER_SECOND);
+         * Replace silab emberEventControlSet (DelayMS/Inactive...) methods with equivalent #2503
+         */
```
Comment (vivien-apple) [inline src/app/clusters/door-lock-server/door-lock-server-user.c:617]: Can we uncomment that ?

File: src/app/clusters/door-lock-server/door-lock-server-schedule.c (hunk 3 above)
Comment (bzbarsky-apple) [reply src/app/clusters/door-lock-server/door-lock-server-schedule.c:159]: @vivien-apple I don't follow. What does the cli API have to do with this?  `emberAfDoorLockClusterSetWeekdayScheduleCallback` is called by command dispatch when the "Set Week Day Schedule" command (ZCL v8 section 7.3.2.15.13) is received.  And the "RF Programming Event" bits are part of the ZCL spec too, as far as I can tell

Comment (vivien-apple) [reply src/app/clusters/door-lock-server/door-lock-server-schedule.c:159]: My bad. I have misread the documentation... replacing ``` client command API```by ```CLI API```in my head.

File: src/app/clusters/door-lock-server/door-lock-server-user.c (hunk 4 above)
Comment (rwalker-apple) [reply src/app/clusters/door-lock-server/door-lock-server-user.c:617]: yes, should be able to uncomment these now

File: src/app/clusters/door-lock-server/door-lock-server-logging.c (hunk 1 above)
Comment (shana-apple) [reply src/app/clusters/door-lock-server/door-lock-server-logging.c:71]: CodeUtils.h is C++ while door lock is C

**Review by rwalker-apple — APPROVED** [review]

File: src/app/clusters/door-lock-server/door-lock-server-user.c [hunk 5]
```diff
@@ -638,7 +639,9 @@ static EmberAfStatus applyCode(uint8_t * code, uint8_t codeLength, EmberAfPlugin
 
 void emberAfPluginDoorLockServerLockoutEventHandler(void)
 {
-    emberEventControlSetInactive(emberAfPluginDoorLockServerLockoutEventControl);
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server-user.c:641]: This can just stay now, right?

File: src/app/clusters/door-lock-server/door-lock-server-user.c [hunk 6]
```diff
@@ -674,7 +677,9 @@ static void scheduleAutoRelock(uint32_t autoRelockTimeS)
 
     if (autoRelockTimeS == 0)
     {
-        emberEventControlSetInactive(emberAfPluginDoorLockServerRelockEventControl);
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server-user.c:677]: And this?

File: src/app/clusters/door-lock-server/door-lock-server-user.c [hunk 7]
```diff
@@ -685,7 +690,9 @@ static void scheduleAutoRelock(uint32_t autoRelockTimeS)
 
 void emberAfPluginDoorLockServerRelockEventHandler(void)
 {
-    emberEventControlSetInactive(emberAfPluginDoorLockServerRelockEventControl);
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server-user.c:688]: And this?

**Comment by woody-apple** [comment]
@shana-apple lots of conflicts to fix here :)

File: src/app/clusters/door-lock-server/door-lock-server-user.c (hunk 5 above)
Comment (shana-apple) [reply src/app/clusters/door-lock-server/door-lock-server-user.c:641]: why it still does not exist

File: examples/lighting-app/efr32/src/gen/callback-stub.c [hunk 8]
```diff
@@ -1997,6 +1997,19 @@ bool emberAfReadReportingConfigurationCommandCallback(const EmberAfClusterComman
     return false;
 }
 
+/** @brief Activate Door Lock Callback
```
Comment (bzbarsky-apple) [inline examples/lighting-app/efr32/src/gen/callback-stub.c:2000]: I wouldn't expect this function to be needed here.... Is it needed? Same for the callback.h in this dir.

File: examples/lighting-app/lighting-common/gen/callback-stub.c [hunk 9]
```diff
@@ -1997,6 +1997,19 @@ bool emberAfReadReportingConfigurationCommandCallback(const EmberAfClusterComman
     return false;
 }
 
+/** @brief Activate Door Lock Callback
```
Comment (bzbarsky-apple) [inline examples/lighting-app/lighting-common/gen/callback-stub.c:2000]: Again, is this needed?  This app will not be implementing door lock....

File: examples/lock-app/nrfconnect/main/gen/callback-stub.c [hunk 10]
```diff
@@ -0,0 +1,2490 @@
+/**
```
Comment (bzbarsky-apple) [inline examples/lock-app/nrfconnect/main/gen/callback-stub.c:1]: This file should not exist at all.  In fact, this directory doesn't exist and shouldn't exist.  This looks like a merge problem to me.

File: examples/wifi-echo/server/esp32/main/component.mk [hunk 11]
```diff
@@ -36,7 +36,7 @@ COMPONENT_SRCDIRS :=                                                      \
   ../third_party/connectedhomeip/src/app/clusters/scenes                 \
  ../third_party/connectedhomeip/src/app/clusters/basic                  \
   ../third_party/connectedhomeip/src/app/reporting                       \
-#  ../third_party/connectedhomeip/src/app/clusters/door-lock-server       \
+ ../third_party/connectedhomeip/src/app/clusters/door-lock-server       \
```
Comment (bzbarsky-apple) [inline examples/wifi-echo/server/esp32/main/component.mk:39]: Please fix the whitespace here?

File: gn_build.sh [hunk 12]
```diff
@@ -1,126 +0,0 @@
-#!/usr/bin/env bash
```
Comment (bzbarsky-apple) [inline gn_build.sh:1]: Why is this being deleted?

File: src/app/clusters/door-lock-server/door-lock-server-user.c [hunk 13]
```diff
@@ -265,10 +267,10 @@ bool emberAfDoorLockClusterSetPinCallback(uint16_t userId, uint8_t userStatus, u
                                (uint8_t *) &rfProgrammingEventMask, sizeof(rfProgrammingEventMask));
     if ((rfProgrammingEventMask & BIT(2)) && !status && (pin != NULL))
     {
-        emberAfFillCommandDoorLockClusterProgrammingEventNotification(EMBER_ZCL_DOOR_LOCK_EVENT_SOURCE_RF,
-                                                                      EMBER_ZCL_DOOR_LOCK_PROGRAMMING_EVENT_CODE_PIN_ADDED, userId,
-                                                                      pin, userType, userStatus, emberAfGetCurrentTime(), pin);
-        SEND_COMMAND_UNICAST_TO_BINDINGS();
+        emberAfFillCommandDoorLockClusterProgrammingEventNotification(
+            EMBER_ZCL_DOOR_LOCK_EVENT_SOURCE_RF, EMBER_ZCL_DOOR_LOCK_PROGRAMMING_EVENT_CODE_PIN_ADDED, userId, pin, userType,
+            userStatus, 0, pin); /*emberAfGetCurrentTime() #2507*/
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server-user.c:272]: The comment should be right after the `0`; otherwise it's not clear what it refers to.

File: src/app/clusters/door-lock-server/door-lock-server-user.c [hunk 14]
```diff
@@ -566,9 +568,9 @@ bool emberAfDoorLockClusterUnlockDoorCallback(uint8_t * pin)
     if (doorUnlocked && (rfOperationEventMask & BIT(2)) && (pin != NULL))
     {
         emberAfFillCommandDoorLockClusterOperationEventNotification(EMBER_ZCL_DOOR_LOCK_EVENT_SOURCE_RF,
-                                                                    EMBER_ZCL_DOOR_LOCK_OPERATION_EVENT_CODE_UNLOCK, userId, pin,
-                                                                    emberAfGetCurrentTime(), pin);
-        SEND_COMMAND_UNICAST_TO_BINDINGS();
+                                                                    EMBER_ZCL_DOOR_LOCK_OPERATION_EVENT_CODE_UNLOCK, userId, pin, 0,
+                                                                    pin); /*emberAfGetCurrentTime() #2507 */
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server-user.c:572]: Again, comment should be right after `0`.

**Review by bzbarsky-apple — DISMISSED** [review]

**Review by andy31415 — APPROVED** [review]
