### PR TITLE
Fix bug with ReportingEngine not being run with short/0 min-reporting intervals

### LINKED ISSUE #16653: min report interval 0 subscription doesn't flush final CurrentLevel after On/Off command
#### Problem

Setting the minimal report interval to zero so that updates arrive in the minimal possible time can cause dirty attributes to not be flushed out (as in the case of the level control cluster and the On and Off commands)

```
In [1]: node = 0x3e8

In [2]: sub = await devCtrl.ReadAttribute(node, [Clusters.OnOff.Attributes.OnOff, Clusters.LevelControl.Attributes.CurrentLevel], reportInterval=(0, 120))
2022-03-24 22:26:55 yuif chip.SC[372750] ERROR The device does not support GetClock_RealTimeMS() API. This will eventually result in CASE session setup failures.

In [3]: await devCtrl.SendCommand(node, 1, Clusters.OnOff.Commands.On())

Attribute Changed:
{
│   'Endpoint': 1,
│   'Attribute': <class 'chip.clusters.Objects.LevelControl.Attributes.CurrentLevel'>,
│   'Value': 1
}
Attribute Changed:
{
│   'Endpoint': 1,
│   'Attribute': <class 'chip.clusters.Objects.OnOff.Attributes.OnOff'>,
│   'Value': True
}
```

Issuing a read seems to force the subscription to flush:

```
In [4]: _ = await devCtrl.ReadAttribute(node, [Clusters.OnOff.Attributes.OnOff, Clusters.LevelControl.Attributes.CurrentLevel])
Attribute Changed:
{
│   'Endpoint': 1,
│   'Attribute': <class 'chip.clusters.Objects.LevelControl.Attributes.CurrentLevel'>,
│   'Value': 254
}
```

@mrjerryjohns @erjiaqing

### PR DESCRIPTION
**Pull request by mrjerryjohns**
#### Problem

Fixes #16653. 

We weren't seeing some attribute changes make their way to a client through a report on a subscription. This only happens when two things happen at the same time:

1. When two attributes change in quick succession, with the second attribute changing in subsequent execution context than the first (as is the case when you issue the Off() command to the OnOff cluster, where the state of the on-off cluster changes to off, but the level cluster only changes to 254 in a subsequent execution context).

2. A subscription was setup with a min interval that is 0, and a max-interval that is much higher.

This results in the first attribute change being 'picked up' and a report being generated. At the same time, `ReadHandler::RefreshSubscribeSyncTimer` is called to arm the hold-off timer for min-interval report hold off. That fires fairly immediately after transmission of the first report, which triggers the reporting engine to run. However, we have yet to receive the status response yet, which means no further reports can actually get generated.

When the status response is eventually received, the actual bug is that we're not properly triggering the reporting engine **again** to run. This would correctly handled all cases of generating reports on handlers that were not in hold off anymore.

#### Fix

Run the reporting engine on receipt of a status response.

#### Tests

Added a Python test to validate the failing scenario in the issue.

I couldn't add a YAML test since it doesn't look like the right plumbing is there to make a test like this happen.

### CODE REVIEW

File: src/app/ReadHandler.cpp [hunk 1]
```diff
@@ -184,6 +184,13 @@ CHIP_ERROR ReadHandler::OnStatusResponse(Messaging::ExchangeContext * apExchange
                 MoveToState(HandlerState::GeneratingReports);
                 mpExchangeCtx = nullptr;
             }
+
+            //
+            // Schedule execution of the ReportingEngine to drive further report generation activity if needed
+            // on this and other subscription that have already full-filled their minimum reporting hold-off requirements
+            // (i.e OnUnblockHoldReportCallback was already called before we got this status response).
```
Comment (bzbarsky-apple) [inline src/app/ReadHandler.cpp:191]: So I'm trying to understand the sequence of events here, from the original issue description:

1. We send the report for the first attribute.
2. While we are waiting for a status response our hold-off timer fires.
3. We call ScheduleRun() on the reporting engine, right?
4. I guess IsReportable() returns false because we are not in the GeneratingReports state but rather in the AwaitingReportResponse state?

If so, it seems like that's the part we should document.  Something like:
```suggestion
            // It's possible that the reporting engine skipped over us because we reported
            // false from IsReportable due to not being in the GeneratingReports state.  If so,
            // we may now have become reportable and should notify the reporting engine so
            // it runs and checks whether we are in fact reportable.
```
But also, why don't we do this inside `MoveToState`, when moving to the GeneratingReports state (and maybe if IsReportable now tests true, but either way)?  Then we can remove a whole bunch of ScheduleRun calls that are scattered all over this code after `MoveToState(HandlerState::GeneratingReports);` and the scheduling will be centralized in the one place where we know we might now be reportable so it's worth trying to report us.

**Review by andy31415 — APPROVED** [review]

File: src/app/ReadHandler.cpp (hunk 1 above)
Comment (mrjerryjohns) [reply src/app/ReadHandler.cpp:191]: Yes, your description is correct. I'll update the documentation to include your snippet.

I could certainly add that to `MoveToState`, but some of the other ones are still needed (e.g `OnUnblockHoldReportCallback`).

File: src/app/ReadHandler.cpp [hunk 2]
```diff
@@ -597,11 +596,25 @@ const char * ReadHandler::GetStateStr() const
...
+    }
+
     if (IsAwaitingReportResponse() && aTargetState != HandlerState::AwaitingReportResponse)
     {
         InteractionModelEngine::GetInstance()->GetReportingEngine().OnReportConfirm();
     }
 
+    //
+    // If we just unblocked sending reports, let's go ahead and schedule the reporting
+    // engine to run to run to kick that off.
```
Comment (bzbarsky-apple) [inline src/app/ReadHandler.cpp:611]:
```suggestion
    // engine to run to kick that off.
```

File: src/app/ReadHandler.h [hunk 3]
```diff
@@ -280,8 +280,8 @@ class ReadHandler : public Messaging::ExchangeDelegate
     enum class HandlerState
     {
         Idle,                   ///< The handler has been initialized and is ready
-        GeneratingReports,      ///< The handler has received either a Read or Subscribe request and is the process of generating a
-                                ///< report.
+        GeneratingReports,      ///< The handler has is now capable of generating reports and may generate one immediately
+                                ///< or later when other criteria is satifified (e.g hold-off for min reporting interval).
```
Comment (bzbarsky-apple) [inline src/app/ReadHandler.h:284]:
```suggestion
                                ///< or later when other criteria are satisfied (e.g hold-off for min reporting interval).
```

**Review by bzbarsky-apple — APPROVED** [review]
