### PR TITLE
Fix crash on fail-safe timeout due to closed exchange

### LINKED ISSUE #21586: [crash] Crash on fail-safe timeout
#### Problem
Was testing the commissioning using incorrect network credentials and the following crash happened during the fail-safe timeout:
```
#0  _exit (status=<optimized out>) at /home/damian/src/ncs/zephyr/lib/libc/newlib/libc-hooks.c:281
#1  0x000be9da in abort ()
#2  0x000aaf98 in chipAbort () at ../../../../../../src/lib/support/CodeUtils.h:506
#3  chip::Messaging::ExchangeHolder::operator-> (this=<optimized out>, this=<optimized out>) at ../../../../../../src/messaging/ExchangeHolder.h:111
#4  0x000623b2 in chip::app::CommandHandler::DecrementHoldOff (this=0x2000d0cc <chip::app::sInteractionModelEngine+52>) at ../../../../../../src/app/CommandHandler.cpp:189
#5  chip::app::CommandHandler::DecrementHoldOff (this=0x2000d0cc <chip::app::sInteractionModelEngine+52>) at ../../../../../../src/app/CommandHandler.cpp:179
#6  0x000ab3ea in chip::app::CommandHandler::Handle::Release (this=0x200127bc <chip::DeviceLayer::Internal::(anonymous namespace)::sThreadNetworkCommissioningInstance+68>)
    at ../../../../../../src/app/CommandHandler.cpp:585
#7  chip::app::CommandHandler::Handle::Release (this=0x200127bc <chip::DeviceLayer::Internal::(anonymous namespace)::sThreadNetworkCommissioningInstance+68>)
    at ../../../../../../src/app/CommandHandler.cpp:579
#8  0x000b4f0a in chip::DeviceLayer::Internal::GenericPlatformManagerImpl<chip::DeviceLayer::PlatformManagerImpl>::DispatchEventToApplication (
    this=this@entry=0x20010878 <chip::DeviceLayer::PlatformManagerImpl::sInstance+8>, event=event@entry=0x2002b778 <chip::DeviceLayer::sChipThreadStack+8184>)
    at ../../../../../../src/include/platform/internal/GenericPlatformManagerImpl.ipp:298
#9  0x0006db40 in chip::DeviceLayer::Internal::GenericPlatformManagerImpl<chip::DeviceLayer::PlatformManagerImpl>::_DispatchEvent (
    this=this@entry=0x20010878 <chip::DeviceLayer::PlatformManagerImpl::sInstance+8>, event=event@entry=0x2002b778 <chip::DeviceLayer::sChipThreadStack+8184>)
    at ../../../../../../src/include/platform/internal/GenericPlatformManagerImpl.ipp:263
#10 0x000b4f86 in chip::DeviceLayer::PlatformManager::DispatchEvent (event=0x2002b778 <chip::DeviceLayer::sChipThreadStack+8184>, 
    this=0x20010870 <chip::DeviceLayer::PlatformManagerImpl::sInstance>) at ../../../../../../src/include/platform/PlatformManager.h:437
```

100% reproducible on a494b1c396d1c97d912ccdc707774c4cc27a6125 - `VerifyOrDie(mpExchangeCtx != nullptr)` assertion fails.
Tested on nRF Connect Lock example, but looks like a generic problem.

 #### Proposed Solution
N/A

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
When CommandHandler is released it dereferences an exchange holder to figure out if the status response can be sent.
The exchange holder, however, can be nulled-out at this point.

#### Change overview
Add a null check. 
Fixes #21586

#### Testing
Added a unit test that reproduces the crash scenario.

### CODE REVIEW

File: src/app/CommandHandler.cpp [hunk 1]
```diff
@@ -186,7 +186,7 @@ void CommandHandler::DecrementHoldOff()
         return;
     }
 
-    if (!mExchangeCtx->IsGroupExchangeContext() && !mSentStatusResponse)
+    if (mExchangeCtx.Get() != nullptr && !mExchangeCtx->IsGroupExchangeContext() && !mSentStatusResponse)
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.cpp:189]:
```suggestion
    if (mExchangeCtx && !mExchangeCtx->IsGroupExchangeContext() && !mSentStatusResponse)
```
Might also be worth logging something here if `!mExchangeCtx`....

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/CommandHandler.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/CommandHandler.cpp:189]: Auditing this code, I think we also need null-checks in:
* `CommandHandler::ProcessGroupCommandDataIB`
* `CommandHandler::GetAccessingFabricIndex`, perhaps.  This one is a problem.  We used to guarantee that during processing of the incoming message `mExchangeCtx` could not go null, but now with `ExchangeHolder` it can if a command does something to evict the exchange's session, for example.  @mrjerryjohns

Comment (Damian-Nordic) [reply src/app/CommandHandler.cpp]: Added a log on empty exchange.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/CommandHandler.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/CommandHandler.cpp]: I spun off https://github.com/project-chip/connectedhomeip/issues/21632 on the further possible changes needed here.

**Review by tcarmelveilleux — APPROVED** [review]

**Review by mrjerryjohns — APPROVED** [review]
