### PR TITLE
[Closure] Fix attribute updates in closure app when the required features are not supported.

### LINKED ISSUE #40753: [Closure app] -  UNLATCH_ACTION always triggered regardless of latch feature is supported or not
### Type

Other

### Explanation

The following action is triggered "UNLATCH_ACTION" from the InitiateAction() function in ClosureManager. This action should not be triggered when the Latch feature is not supported.

### Platform

all

### Platform Version(s)

_No response_

### Testing

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by arun-silabs**
#### Summary
In the Closure app, certain attributes were being updated without verifying whether the corresponding feature set was supported. For example, latch actions were executed without checking if the MotionLatching feature was enabled. 
This PR introduces feature-gating logic to ensure that attribute initialization and latch-related operations are only performed when the relevant features are supported.

#### Related issues
N/A

#### Testing
- Built the Closure app with only the Positioning and Speed features enabled. Verified that the initial state is correctly set without causing a crash.

- Confirmed that latch updates via the move-to command behave as expected when the MotionLatching feature is disabled.

Commission the DUT to raspberry-pi

./chip-tool closurecontrol read overall-current-state 1 1
Output: 
{
  Position : 0,
  Speed : 0,
  Secure State : TRUE
}

./chip-tool closurecontrol move-to 111 1 --Position 1 --Latch 1 --Speed 3
Output : Status : Success

/chip-tool closurecontrol read overall-current-state 1 1
Output: 
{
  Position : 1,
  Speed : 3,
  Secure State : TRUE
}

#### Readability checklist

The checklist below will help the reviewer finish PR review in time and keep the
code readable:

-   [x] PR title is
        [descriptive](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html#title-formatting)
-   [x] Apply the
        [_“When in Rome…”_](https://project-chip.github.io/connectedhomeip-doc/style/CODING_STYLE_GUIDE.html)
        rule (coding style)
-   [ ] PR size is short
-   [x] Try to avoid "squashing" and "force-update" in commit history
-   [x] CI time didn't increase

### CODE REVIEW

**Review by sabollim-silabs — APPROVED** [review]

File: examples/closure-app/silabs/src/ClosureManager.cpp [hunk 1]
```diff
@@ -136,51 +136,83 @@ void ClosureManager::Init()
...
-        .Set(ClosureControl::LatchControlModesBitmap::kRemoteUnlatching);
-    ReturnErrorOnFailure(closureControlEndpoint.GetLogic().SetLatchControlModes(latchControlModes));
+
+    if (conformance.HasFeature(ClosureControl::Feature::kPositioning) && !conformance.HasFeature(ClosureControl::Feature::kInstantaneous))
+    {
+        ReturnErrorOnFailure(closureControlEndpoint.GetLogic().SetCountdownTimeFromDelegate(NullNullable));
+    }
+    ReturnErrorOnFailure(closureControlEndpoint.GetLogic().SetMainState(MainStateEnum::kStopped));
+    
+    if(conformance.HasFeature(ClosureControl::Feature::kMotionLatching))
```
[the remark this answers is not in the document]
Comment (arun-silabs) [reply examples/closure-app/silabs/src/ClosureManager.cpp]: fixed with restyler

**Review by AliTalebVelux — APPROVED** [review]

**Review by AliTalebVelux — APPROVED** [review]

**Comment by sabollim-silabs** [comment]
Feature gating refactoring need to taken up in closure manager. raised issue for same https://github.com/project-chip/connectedhomeip/issues/40856

File: examples/closure-app/linux/ClosureManager.cpp [hunk 2]
```diff
@@ -138,51 +138,97 @@ void ClosureManager::Shutdown()
...
+            .min = static_cast<int16_t>(0), .max = static_cast<int16_t>(10000) }));
+    }
+    if (conformance.HasFeature(ClosureDimension::Feature::kRotation))
+    {
+        ReturnErrorOnFailure(closurePanelEndpoint.GetLogic().SetOverflow(OverflowEnum::kTopInside));
+    }
+    if (conformance.HasFeature(ClosureDimension::Feature::kLimitation))
+    {
+        ClosureDimension::Structs::RangePercent100thsStruct::Type limitRange{ .min = static_cast<Percent100ths>(0),
+                                                                              .max = static_cast<Percent100ths>(10000) };
```
Comment (jepenven-silabs) [inline examples/closure-app/linux/ClosureManager.cpp:222]: Magic numbers, don't we have a define for it ? or at least a comment with a spec reference...

**Review by jepenven-silabs — APPROVED** [review]

File: examples/closure-app/linux/ClosureManager.cpp (hunk 2 above)
Comment (sabollim-silabs) [reply examples/closure-app/linux/ClosureManager.cpp:222]: These numbers are not part of the modified code. will add the spec reference

**Review by sabollim-silabs — APPROVED** [review]
