### PR TITLE
Make the comma split work in zsh

### LINKED ISSUE #27338: [BUG] Bootstrap script fails to run in zsh
### Reproduction steps

1. Open zsh shell.
2. After executing `. ./scripts/bootstrap.sh`, return `_install_additional_pip_requirements:read:19: bad option: -a`.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

9a5b9097245526267909ffbfc7e2f60a3c9b452a

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by andy31415**
Fixes #27338

### CODE REVIEW

File: scripts/setup/bootstrap.sh [hunk 1]
```diff
@@ -33,7 +33,11 @@ _install_additional_pip_requirements() {
     done
 
     if ! [ -z "$_SETUP_PLATFORM" ]; then
-        IFS="," read -r -a _PLATFORMS <<<"$_SETUP_PLATFORM"
+        if [ -n "$ZSH_VERSION" ]; then
+           IFS="," read -r -A _PLATFORMS <<<"$_SETUP_PLATFORM"
```
Comment (bzbarsky-apple) [inline scripts/setup/bootstrap.sh]: I wonder whether doing:
```
   if [ -n "$ZSH_VERSION" ]; then
       array_arg="-A"
   else
       array_arg="-a"
   fi
   IFS="," read -r $array_arg _PLATFORMS <<<"$_SETUP_PLATFORM"
```
is more or less readable/maintainable...

**Review by bzbarsky-apple — APPROVED** [review]
