### PR TITLE
Fix incorrectly reported NoReponse when single batch command sent to …

### LINKED ISSUE #32360: OnNoResponse is always called using extendable invoke against the old device that don't support batch
when CommandRef is not in CommandResponseIB and total command in this transaction = 1 and onResponse is received, you may suppress onNoResponse

### PR DESCRIPTION
**Pull request by tehampson**
When new CommandSender APIs is used to send a single invoke request where `CommandRef` was provided in the request to a legacy device, CommandSender would incorrectly call the NoResposeCallback.

This occurs because legacy device is allowed to drop CommandRef (as it doesn't even know to look for CommandRef, nor does it know what it means).

Fix by assuming if getting a response to a single request, we assume the response matches the single pending tracked command.

fixes: https://github.com/project-chip/connectedhomeip/issues/32360

### CODE REVIEW

**Review by tcarmelveilleux — APPROVED** [review]

File: src/app/CommandSender.cpp [hunk 1]
```diff
@@ -441,6 +441,14 @@ CHIP_ERROR CommandSender::ProcessInvokeResponseIB(InvokeResponseIB::Parser & aIn
             }
         }
 
+        if (!commandRef.HasValue() && !commandRefRequired && mpPendingResponseTracker != nullptr && mpPendingResponseTracker->Count() == 1)
```
Comment (tcarmelveilleux) [inline src/app/CommandSender.cpp:444]: Please add a test to cover detecting a regression of this PR's fix.

**Review by yunhanw-google — APPROVED** [review]

File: src/app/CommandSender.cpp (hunk 1 above)
Comment (tehampson) [reply src/app/CommandSender.cpp:444]: Test has been added

**Review by woody-apple — APPROVED** [review]
