### PR TITLE
Disable the second network commissioning endpoint for ESP32 all-clusters-app

### LINKED ISSUE #15359: Enumeration test - Unable to read device list of endpoint 65534 - Error Domain=MatterInteractionErrorDomain Code=195 "The cluster indicated is not supported" UserInfo={NSLocalizedDescription=The cluster indicated is not supported}
#### Problem

Enumeration test - Unable to read device list of endpoint 65534 - Error Domain=MatterInteractionErrorDomain Code=195 "The cluster indicated is not supported" UserInfo={NSLocalizedDescription=The cluster indicated is not supported}

SHA: 149c271f497b4493dbc009aed8f616922fc9b5fe

Steps to reproduce
 
1. Pair M5 with chip tool and toggle light works fine. 
2. Perform enumeration test
3. Observe chip tool logs, we are able to read server list from endpoints 1 and 2 fine. 
4. But we see error such as below for reading device list on endpoint 65534

2022-02-18 11:38:47.878938-0800  localhost CHIPTool[12034]: UpdatingUIResult: Unable to read device list for Endpoint:65534 Error: Error Domain=MatterInteractionErrorDomain Code=195 "The cluster indicated is not supported" UserInfo={NSLocalizedDescription=The cluster indicated is not supported}

[Unable-to-read-device-list-for-ep-65534-Chiptool.txt](https://github.com/project-chip/connectedhomeip/files/8099948/Unable-to-read-device-list-for-ep-65534-Chiptool.txt)
[Unable-to-read-device-list-for-ep-65534-M5-logs.txt](https://github.com/project-chip/connectedhomeip/files/8099949/Unable-to-read-device-list-for-ep-65534-M5-logs.txt)

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
We don't use that endpoint, and should not be enabling it.

#### Problem
Extra endpoint visible.

#### Change overview
Disable it on esp32.

#### Testing
Checked that it not longer shows up in Descriptor.

### CODE REVIEW

File: examples/all-clusters-app/esp32/main/main.cpp [hunk 1]
```diff
@@ -628,13 +628,18 @@ class AppCallbacks : public AppDelegate
...
+
 } // namespace
 
 static void InitServer(intptr_t context)
 {
     // Init ZCL Data Model and CHIP App Server
     chip::Server::GetInstance().Init(&sCallbacks);
 
+    // We only have network commissioning on endpoint 0.
+    emberAfEndpointEnableDisable(kNetworkCommissioningEndpointSecondary, false);
```
Comment (sagar-apple) [inline examples/all-clusters-app/esp32/main/main.cpp:641]: Is this being done in this particular "flavor" of the all-clusters-app because the zap config is shared between all the "flavors"?

i.e there might be devices running this application that might have other network commissioning cluster instances?

**Review by sagar-apple — APPROVED** [review]

File: examples/all-clusters-app/esp32/main/main.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply examples/all-clusters-app/esp32/main/main.cpp:641]: Yes, exactly.  The Linux versions supports both WiFi and Thread in some configurations.

**Review by andy31415 — APPROVED** [review]
