### PR TITLE
On kBindingsChangedViaCluster during UDC, pick target video player's nodeID from BindingTable

### LINKED ISSUE #24267: [BUG] tv-casting-app does not connect to tv-app on recommissioning
### Reproduction steps

Test with the Android tv-casting-app and the Linux tv-app. 

Note: The Android tv-casting-app has behaviour to skip the UDC flow if the app is already commissioned with the selected TV. Make a temporary code change in the DiscoveredNodeData.java class in the `isPreCommissioned` method  to `return false` instead of `return connectableVideoPlayer != null` This is done so that we can simulate cases where the post-commissioning flow may have failed which would require the app to go through commissioning again.

1. Commission the Android tv-casting-app with the tv-app.
2. Kill and restart both the Android tv-casting-app and the tv-app.
3. Run through the commissioning flow

Actual result: The tv-casting-app fails to proceed to the Cluster selection screen and never connects to the Linux tv-app it had previously commissioned with.
Expected result: The tv-casting-app finds that it is already commissioned with the selected tv-app and establishes a CASE session with it.

### Bug prevalence

Everytime I do this with the above steps to repro

### GitHub hash of the SDK that was being used

19c8ea42b4f4af2669643b758caa4cf412cfee69

### Platform

android, other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sharadb-amazon**
Fixes https://github.com/project-chip/connectedhomeip/issues/24267

### Change summary
1. Added a new BindingsChanged event in CHIPDeviceEvent.h which includes the accessing fabricIndex.
2. Passed the accessing fabricIndex in the BindingsChanged event in bindings.cpp: NotifyBindingsChanged call
3. On kBindingsChangedViaCluster, if we find UDC is in progress, we select the video player (find its nodeId and fabricIndex) from the BindingTable by matching it against the accessing fabricIndex found in the BindingsChanged event.

### Testing
Tested with the Android tv-casting-app and the Linux tv-app as per the instructions in https://github.com/project-chip/connectedhomeip/issues/24267

### CODE REVIEW

File: src/app/clusters/bindings/bindings.cpp [hunk 1]
```diff
@@ -52,7 +52,7 @@ class BindingTableAccess : public AttributeAccessInterface
     CHIP_ERROR ReadBindingTable(EndpointId endpoint, AttributeValueEncoder & encoder);
     CHIP_ERROR WriteBindingTable(const ConcreteDataAttributePath & path, AttributeValueDecoder & decoder);
 
-    CHIP_ERROR NotifyBindingsChanged();
+    CHIP_ERROR NotifyBindingsChanged(FabricIndex accessingFabricIndex = 0);
```
Comment (chrisdecenzo) [inline src/app/clusters/bindings/bindings.cpp:55]: is there a need to have a default? seems like this might allow a caller to forget to set it - in which case some sort of "unknown fabric index" value would be better. I suggest not having a default unless you absolutely need it

**Review by chrisdecenzo — APPROVED** [review]

File: src/app/clusters/bindings/bindings.cpp (hunk 1 above)
Comment (sharadb-amazon) [reply src/app/clusters/bindings/bindings.cpp]: Somewhat recently this PR: https://github.com/sharadb-amazon/connectedhomeip/commit/3c0c8753a4d660507f822ec5e28dae3a1e4b8875#diff-cff38b6dd18f2dee82a0430ab4d8d1199a330559936fb17e1be1bc8dc4131c54 added a OnListWriteEnd function. I think we should be ok passing in a 0 for a fabricIndex when that function calls NotifyBindingsChanged, which is why I had added the default value. If passing 0 makes sense (let me know if it doesn't), I have changed to code, so there are no defaults now, but we explicitly pass 0 in the implementation of OnListWriteEnd.

Comment (ReneJosefsen) [reply src/app/clusters/bindings/bindings.cpp]: OnListWriteEnd was added to avoid that the previous implementation sent out an event when the list was cleared and one when the "new" binding list was written again. 

The notify function call inside `if (!path.IsListOperation())` should not happen and it is unclear if this situation is even possible: https://github.com/project-chip/connectedhomeip/issues/24377

My assumption for this to work we would want to return the correct accessingFabricIndex in OnListWriteEnd and not just 0?

Comment (sharadb-amazon) [reply src/app/clusters/bindings/bindings.cpp]: @ReneJosefsen - Thanks, you're right, I'll need to return a valid accessingFabricIndex in OnListWriteEnd. 

If you are familiar with this version of the BindingTableAccess class and how the state of its objects are handled, can you tell me if that can be done by capturing the accessingFabricIndex in WriteBindingTable as a new data member (say mAccessingFabricIndex) of the BindingTableAccess object, and then passing the value of that data member in OnListWriteEnd?

Comment (sharadb-amazon) [reply src/app/clusters/bindings/bindings.cpp]: Diff updated.

**Review by hawk248 — APPROVED** [review]
