### PR TITLE
[NXP] Initial enablement of NXP Matter over WiFi with Zephyr 

### LINKED ISSUE #25808: [BUG] Deprecation For CPLUSPLUS And LIB_CPLUSPLUS For Zephyr
### Reproduction steps

proj.conf:
```
CONFIG_CHIP=y
```

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

974f6206119e7436a9ae6262ca6f6035aeeeb149

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

Zephyr: Master - f19e6d481164420ed758f5c07d879aa75da93eed

CPLUSPLUS:
```
[DEPRECATED] Select CPP instead.

Symbols currently y-selecting this symbol:
  - CHIP
```
LIB_CPLUSPLUS:
```
[DEPRECATED]
Select REQUIRES_FULL_LIBCPP or specify the C++ standard library
implementation to use from LIBCPP_IMPLEMENTATION.
Symbols currently y-implying this symbol:
  - CHIP
```

EDIT0: As an aside (probably), maybe that's why I get the red squiggles in my conf in vscode using the kconfig extension for `CONFIG_CHIP=y` even though it says it's because `Unknown symbol CONFIG_CHIP`.
It configures fine (other than the deprecation), but maybe it's a red-herring and it's because of the deprecation issue that the extension considers it `unknown`.

### PR DESCRIPTION
**Pull request by axelnxp**
This PR aims to upstream initial enablement of NXP Matter over Wi-Fi with Zephyr.

ec6c4b461f7987af52fc28281ab81ba73e1dbec7 also fixes #25808

### CODE REVIEW

File: src/platform/nxp/zephyr/wifi/ConnectivityManagerImplWiFi.cpp [hunk 1]
```diff
@@ -0,0 +1,178 @@
+/*
```
Comment (Damian-Nordic) [inline src/platform/nxp/zephyr/wifi/ConnectivityManagerImplWiFi.cpp:1]: This `wifi` implementation looks almost identical to nRF Connect's implementation. Do you think it could be unified by moving it (or a part of that) to `src/platform/Zephyr/wifi` and building in both platforms? We initially put it in `src/platform/nrfconnect` as we used proprietary Wi-Fi APIs back then but now that we switched to Zephyr's net management APIs, it could probably be unified. That way we may help each other in the future when bugs are found in the shared code.

Comment (axelnxp) [reply src/platform/nxp/zephyr/wifi/ConnectivityManagerImplWiFi.cpp:1]: Hi Damian, I agree, this is also the purpose of this PR, to see if we can put even more modules in common for zephyr platforms.
We already made a few fixes, after running internal certification tests, thus the minor differences.

If that makes sense to you, I can do the change in another PR, I'd prefer to not stack changes in this PR as it's already kinda heavy to review.

File: src/platform/nxp/zephyr/BLEManagerImpl.h [hunk 2]
```diff
@@ -0,0 +1,26 @@
+/*
+ *
+ *    Copyright (c) 2023 Project CHIP Authors
```
[the remark this answers is not in the document]
Comment (axelnxp) [reply src/platform/nxp/zephyr/BLEManagerImpl.h:3]: do you mean it should state 2024 ?

File: src/platform/nxp/zephyr/wifi/ConnectivityManagerImplWiFi.cpp (hunk 1 above)
Comment (Damian-Nordic) [reply src/platform/nxp/zephyr/wifi/ConnectivityManagerImplWiFi.cpp:1]: Yes, works for me. You can probably file an issue for that so it's not forgotten.

File: src/platform/nxp/zephyr/BLEManagerImpl.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (Damian-Nordic) [reply src/platform/nxp/zephyr/BLEManagerImpl.h:3]: Yes, we generally care about the year the code is contributed, so 2024 would be fine.

File: src/platform/nxp/zephyr/wifi/ConnectivityManagerImplWiFi.cpp (hunk 1 above)
Comment (axelnxp) [reply src/platform/nxp/zephyr/wifi/ConnectivityManagerImplWiFi.cpp:1]: Done: https://github.com/project-chip/connectedhomeip/issues/31651

File: src/platform/nxp/zephyr/BLEManagerImpl.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (axelnxp) [reply src/platform/nxp/zephyr/BLEManagerImpl.h:3]: ok got it, will update.

**Review by Damian-Nordic — APPROVED** [review]

**Comment by axelnxp** [comment]
Should I rebase this branch on top of master ?
Any idea why `Tests / REPL Tests ` is failing ? I don't think this is related to this PR.

**Review by woody-apple — APPROVED** [review]

File: src/platform/nxp/zephyr/wifi/ConnectivityManagerImplWiFi.cpp (hunk 1 above)
Comment (LuDuda) [reply src/platform/nxp/zephyr/wifi/ConnectivityManagerImplWiFi.cpp:1]: Thanks @axelnxp, looking forward for PR. What about the features defined in chip-module/KConfig or KConfig.features? Originally these KConfig options were created for nRF Connect platform, now they are copied to another file almost without modifications. I wonder if we could move them to common generic Zephyr port as well and simplify maintenance in the future?

Comment (Damian-Nordic) [reply src/platform/nxp/zephyr/wifi/ConnectivityManagerImplWiFi.cpp:1]: chip-module/Kconfig is already unified (config/zephyr/Kconfig). Only platform-specific Kconfig are separated.

**Review by yunhanw-google — APPROVED** [review]

**Comment by axelnxp** [comment]
Anyone can provide guidance about `Darwin / Build Darwin` check ? I'm not sure how it can be related to these changes.
It seems unstable, was pass on previous push.
@Damian-Nordic @woody-apple @yunhanw-google

**Comment by yunhanw-google** [comment]
Darwin CI is a little bit flaky, usually retry can help, just merge your PR, thanks

**Comment by axelnxp** [comment]
> Darwin CI is a little bit flaky, usually retry can help, just merge your PR, thanks

Thanks @yunhanw-google 
Is it possible to rerun a failing check instead of rerunning the whole list ?
