### PR TITLE
[Infineon] Fix KVS not clean config value for CYW30739

### LINKED ISSUE #22610: [Platform] [Infineon] KVS not clean config value for CYW30739
### Reproduction steps

```bash
1. Delete a zero-size value.
```

### Platform

other

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AlvinHsiao**
#### Problem
Fixes #22610

#### Change overview
* Check value size before cleaning config value.

### CODE REVIEW

File: src/platform/Infineon/CYW30739/KeyValueStoreManagerImpl.cpp [hunk 1]
```diff
@@ -149,8 +149,11 @@ CHIP_ERROR KeyValueStoreManagerImpl::_Delete(const char * key)
     err = CYW30739Config::ClearConfigValue(entry->GetKeyConfigKey());
     VerifyOrExit(ChipError::IsSuccess(err), err = CHIP_ERROR_PERSISTED_STORAGE_VALUE_NOT_FOUND);
 
-    err = CYW30739Config::ClearConfigValue(entry->GetValueConfigKey());
-    VerifyOrExit(ChipError::IsSuccess(err), err = CHIP_ERROR_PERSISTED_STORAGE_VALUE_NOT_FOUND);
+    if (entry->GetValueSize() != 0)
+    {
+        err = CYW30739Config::ClearConfigValue(entry->GetValueConfigKey());
+        VerifyOrExit(ChipError::IsSuccess(err), err = CHIP_ERROR_PERSISTED_STORAGE_VALUE_NOT_FOUND);
+    }
```
Comment (tcarmelveilleux) [inline src/platform/Infineon/CYW30739/KeyValueStoreManagerImpl.cpp:156]: This will leave the key as present if the size is zero. How does this fix "network information does not restore back"? I think the fix likely needs to be in the NetworkCommissioning::WifiDriver instance for your platforn

Comment (hsusid) [reply src/platform/Infineon/CYW30739/KeyValueStoreManagerImpl.cpp:156]: The subject of this PR contains misleading descriptions. It's a general KVS implementation fix.
When writing a zero-size value, CYW30739 only writes the key of the value to the flash because the lower layer APIs of CYW30739 doesn't support writing a zero-size value.
``` c
CHIP_ERROR KeyValueStoreManagerImpl::_Put(const char * key, const void * value, size_t value_size)
{
    ...
    if (value_size != 0)
    {
        SuccessOrExit(err = CYW30739Config::WriteConfigValueBin(entry->GetValueConfigKey(), value, value_size));
    }
    ...
}
```
CYW30739 only has to erase the key of a zero-size value from the flash rather than erase both the key and the value from the flash.
When the original codes tried to delete a non-existed value from the flash, the lower layer API would return an error and bypass the following codes. This is the bug we are trying to fix.

**Review by Damian-Nordic — APPROVED** [review]

**Comment by andy31415** [comment]
Accepted for 1.0: platform specific change.

@AlvinHsiao - please link an issue (edit the summary and say something like `fixes #...` or `closes #...` (text has to match, except case)

File: src/platform/Infineon/CYW30739/KeyValueStoreManagerImpl.cpp (hunk 1 above)
Comment (andy31415) [reply src/platform/Infineon/CYW30739/KeyValueStoreManagerImpl.cpp:156]: This description should be in the issue linked to this PR.

**Comment by AlvinHsiao** [comment]
@andy31415 
Added the issue link https://github.com/project-chip/connectedhomeip/issues/22610.

**Review by bzbarsky-apple — APPROVED** [review]
