### PR TITLE
Fix retrieval of attestation challenge in Java

### LINKED ISSUE #17351: GetAttestationChallenge is a public API and doesn't make sense
#### Problem
GetAttestationChallenge ended up as a public API. BUT, it really is just a convenience for the commissioner to get the attestation challenge of the device CURRENTLY being commissioned because the proxy isn't provided. Previously, this (accidentally IMO) fell back to the most recently PASE'd proxy, but as we moved towards less statefulness, this function got left behind.

 #### Proposed Solution
Add optional var to the API to allow a proxy to be provided, THEN fall back to the current commissioning device.
CHIP_ERROR GetAttestationChallenge(ByteSpan & attestationChallenge, const DeviceProxy* proxy = nullptr)

### PR DESCRIPTION
**Pull request by g-coppock**
When not using the auto-commissioning flow, the mDeviceBeingCommissioned
proxy is no longer assigned, so the default behavior of retrieving the
attestation challenge fails.

Since at the time of use we already have a reference to the correct
DeviceProxy, added an overload to pass the proxy along to retrieve the
challenge.

### CODE REVIEW

File: src/controller/CHIPDeviceController.h [hunk 1]
```diff
@@ -476,6 +476,17 @@ class DLL_EXPORT DeviceCommissioner : public DeviceController,
...
+    /**
+     * @brief
+     *   This function returns the attestation challenge for the secure session of the device being commissioned.
+     *
+     * @param[out] attestationChallenge The output for the attestationChallenge
+     * @param[in] proxy The DeviceProxy whose secure session should be used to derive the challenge
+     *
+     * @return CHIP_ERROR               CHIP_NO_ERROR on success, or CHIP_ERROR_INVALID_ARGUMENT if no secure session is active
+     */
+    CHIP_ERROR GetAttestationChallenge(DeviceProxy * proxy, ByteSpan & attestationChallenge);
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.h:488]: This API shouldn't be on device commissioner, since it does not use any device commissioner state.  It should just be on DeviceProxy.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/controller/CHIPDeviceController.h (hunk 1 above)
Comment (g-coppock) [reply src/controller/CHIPDeviceController.h]: You're right, that's much cleaner. Updated, and removed the existing GetAttestationChallenge from CHIPDeviceController as well.

File: src/app/DeviceProxy.h [hunk 2]
```diff
@@ -59,6 +59,25 @@ class DLL_EXPORT DeviceProxy
...
+     * @brief
+     *   This function returns the attestation challenge for the secure session.
+     *
+     * @param[out] attestationChallenge The output for the attestationChallenge
+     *
+     * @return CHIP_ERROR               CHIP_NO_ERROR on success, or CHIP_ERROR_INVALID_ARGUMENT if no secure session is active
+     */
+    virtual CHIP_ERROR GetAttestationChallenge(ByteSpan & attestationChallenge)
+    {
+        Optional<SessionHandle> secureSessionHandle;
```
Comment (bzbarsky-apple) [inline src/app/DeviceProxy.h:72]: Might be better to put the implementation in the .cpp...

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

File: src/app/DeviceProxy.h (hunk 2 above)
Comment (andy31415) [reply src/app/DeviceProxy.h:72]: Seems no updates in a while on this PR. Assuming this can be done as a followup.

Comment (bzbarsky-apple) [reply src/app/DeviceProxy.h:72]: @andy31415 Is there an issue tracking tahg followup assigned to this PR's author?

I am fine with followups, but I want them to actually happen, and except for a few people our track record at them is very poor.

Comment (g-coppock) [reply src/app/DeviceProxy.h:72]: Followup is here: https://github.com/project-chip/connectedhomeip/pull/19058
