### PR TITLE
[EVSE] add evse cluster and examples energy management app

### LINKED ISSUE #30580: Create initial EVSE XML for SDK
For SDK code freeze we need to have EVSE cluster implemented.
This is a small PR to allow people just to review the XML and check chip-tool compiles.

### LINKED ISSUE #30665: [1.3] Updates needed on EVSE XML & Device Energy Management - to use new types, and clean up other comments with optional XML.
### Reproduction steps

EVSE XML follow up issues based on PR: #30581 

- Please ensure a follow-up issue is filed to add the energy-mWh, amperage-mA, etc types to the XML definitions.
- For what it's worth, "max" is ignored here for readonly attributes, and the "is nullable and of type epoch_s" defines that max anyway. It doesn't hurt things, other than visual noise, but is not needed either. Spec does not have it (because it's part of the type already).
-This is the default; does not need to be explicitly listed, but ok to do it:
-     <access op="invoke" privilege="operate"/> - 
-  There is no "side" for events, right? All events are server-side....
-     <event code="0x0000" name="EVConnected" priority="info" side="server" apiMaturity="provisional">

### Bug prevalence

N/A

### GitHub hash of the SDK that was being used

Will need to be fixed in 1.3

### Platform

core

### Platform Version(s)

N/A

### Type

Spec Compliance Issue

### Anything else?

_No response_

### LINKED ISSUE #30727: Add EVSE to examples/energy-management-app
We need an example app for energy-management, which will include EVSE, DEM, Electrical Power Measurement, Electrical Energy Measurement.

This task is just to add the EVSE cluster.

See also [Add DEM (Device Energy Management) to examples/energy-management-app#30726](https://github.com/project-chip/connectedhomeip/issues/30726)

### LINKED ISSUE #30805: [EVSE] SessionID null value XML change
Implement the changes to make Session attributes Nullable by updating XML.
Also change TargetTime -> TargetTimeMinutesPastMidnght

### PR DESCRIPTION
**Pull request by jamesharrow**
Fixes #30727 
- https://github.com/project-chip/connectedhomeip/issues/30727

Fixes #30665 
- https://github.com/project-chip/connectedhomeip/issues/30665

Fixed #30805 
- https://github.com/project-chip/connectedhomeip/issues/30805

This is an omnibus PR which should be reviewed after #30857 

Adds EVSE SDK and all-clusters-app. 
It includes the new Energy-Management-App example

- Note updates EVSE XML to support energy types (energy_mwh - still all lowercase)
- Adds energy-evse-server.cpp/,h into SDK
- Adds all-clusters-app and stub functions

NOTE: the Energy EVSE XML makes SessionID nullable and changes TargetTime (as per spec https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/8631)

### CODE REVIEW

File: examples/all-clusters-app/all-clusters-common/src/EnergyEvseManager.cpp [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    GetInstance()->Instance::Init();
+    return CHIP_NO_ERROR;
+}
+
+void EnergyEvseManager::Shutdown()
+{
+    GetInstance()->Instance::Shutdown();
+}
+
+void MatterEnergyEvsePluginServerInitCallback() {}
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/all-clusters-common/src/EnergyEvseManager.cpp:36]: This is supposed to be in the cluster impl or `src/app/util/util.cpp`, not in the app.  This is an SDK hook, not public app API.

File: examples/all-clusters-app/all-clusters-common/include/EnergyEvseDelegateImpl.h [hunk 2]
```diff
@@ -0,0 +1,193 @@
...
+    Status StartDiagnostics() override;
+
+    // -----------------------------------------------------------------
+    // Internal API to allow an EVSE to change its internal state etc
+    // TODO Status hwRegisterEvseHardwareCallback(Callback);
+    Status hwSetMaxHardwareCurrentLimit(int64_t currentmA);
+    Status hwSetCircuitCapacity(int64_t currentmA);
+    Status hwSetCableAssemblyLimit(int64_t currentmA);
+    Status hwSetState(StateEnum state);
+    Status hwSetFault(FaultStateEnum fault);
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/all-clusters-common/include/EnergyEvseDelegateImpl.h:76]: We generally use InitialCaps naming for methods....

File: src/app/clusters/energy-evse-server/energy-evse-server.h
Comment (bzbarsky-apple) [inline src/app/clusters/energy-evse-server/energy-evse-server.h:1]: For review sanity, I strongly suggest having separate PRs for:

1. Add the core SDK bits.
2. Add the example app bits.

File: examples/all-clusters-app/all-clusters-common/src/EnergyEvseManager.cpp (hunk 1 above)
Comment (jamesharrow) [reply examples/all-clusters-app/all-clusters-common/src/EnergyEvseManager.cpp:36]: Ah ok - I copied from bridged-actions-stub.cpp. 
Looks like I randomly picked the wrong example!

File: examples/all-clusters-app/all-clusters-common/include/EnergyEvseDelegateImpl.h (hunk 2 above)
Comment (jamesharrow) [reply examples/all-clusters-app/all-clusters-common/include/EnergyEvseDelegateImpl.h]: Fixed

File: src/app/clusters/energy-evse-server/energy-evse-server.h
Comment (jamesharrow) [reply src/app/clusters/energy-evse-server/energy-evse-server.h:1]: Will do - but needed to check that the whole thing will merge and pass all tests (currently doesn't) - this PR is still in draft.
I'll try to split this into 2 so it is easier to merge.

File: examples/all-clusters-app/all-clusters-common/src/EnergyEvseManager.cpp (hunk 1 above)
Comment (jamesharrow) [reply examples/all-clusters-app/all-clusters-common/src/EnergyEvseManager.cpp]: Changed.

File: src/app/clusters/energy-evse-server/energy-evse-server.h
Comment (jamesharrow) [reply src/app/clusters/energy-evse-server/energy-evse-server.h:1]: Ok - so this PR #30793 is clean I think.
But per your request I took this PR and deleted a few files and created #30857 which is just the SDK and all-clusters-app.

Comment (bzbarsky-apple) [reply src/app/clusters/energy-evse-server/energy-evse-server.h:1]: Thank you!

File: examples/all-clusters-app/all-clusters-common/src/EnergyEvseManager.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply examples/all-clusters-app/all-clusters-common/src/EnergyEvseManager.cpp]: @jamesharrow Yeah, the fact that some of our examples do things wrong is ... don't get me started.  :(

File: examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+using namespace chip::app;
+using namespace chip::app::Clusters;
+using namespace chip::app::Clusters::EnergyEvse;
+
+CHIP_ERROR EVSEManufacturer::Init(EnergyEvseManager * aInstance)
+{
+    /* Manufacturers should modify this to do any custom initialisation */
+
+    /* Register callbacks */
+    EnergyEvseDelegate * dg = aInstance->GetDelegate();
```
Comment (PSONALl) [inline examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp:31]: we should check here if instance is null and return error if it is

Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/src/EVSEManufacturerImpl.cpp:31]: Ok - will add.

File: examples/energy-management-app/linux/main.cpp [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+    }
+    else
+    {
+        ChipLogError(AppServer, "EVSE Instance or Delegate already exist.")
+    }
+
+    if (gEvseManufacturer == nullptr)
+    {
+        gEvseManufacturer = new EVSEManufacturer();
+        gEvseManufacturer->Init(gInstance);
```
Comment (PSONALl) [inline examples/energy-management-app/linux/main.cpp:70]: If EVSE manufacturer initialisation fails then we should delete EVSE instance

Comment (jamesharrow) [reply examples/energy-management-app/linux/main.cpp]: Good spot - re-written the function to handle potential failures in malloc and init() calls.

File: examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h
Comment (jamesharrow) [inline examples/energy-management-app/energy-management-common/include/EnergyEvseDelegateImpl.h:1]: This file _should_ be identical to the one in all-clusters-app/all-clusters-common

File: examples/energy-management-app/energy-management-common/include/EnergyEvseManager.h
Comment (jamesharrow) [inline examples/energy-management-app/energy-management-common/include/EnergyEvseManager.h:1]: This file _should_ be identical to the one in all-clusters-app/all-clusters-common

File: examples/energy-management-app/energy-management-common/include/EnergyManagementManager.h
Comment (jamesharrow) [inline examples/energy-management-app/energy-management-common/include/EnergyManagementManager.h:1]: This file is a placeholder for when we add Device Energy Management cluster here.

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp
Comment (jamesharrow) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp:1]: This file _should_ be identical to the one in all-clusters-app/all-clusters-common

File: examples/energy-management-app/energy-management-common/src/EnergyEvseManager.cpp
Comment (jamesharrow) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseManager.cpp:1]: This file _should_ be identical to the one in all-clusters-app/all-clusters-common

File: examples/energy-management-app/energy-management-common/src/EnergyManagementManager.cpp
Comment (jamesharrow) [inline examples/energy-management-app/energy-management-common/src/EnergyManagementManager.cpp:1]: This is a placeholder for when we add Device Energy Management

File: examples/energy-management-app/linux/BUILD.gn [hunk 5]
```diff
@@ -0,0 +1,125 @@
...
+
+import("//build_overrides/chip.gni")
+
+import("${chip_root}/build/chip/tools.gni")
+import("${chip_root}/src/app/common_flags.gni")
+import("${chip_root}/third_party/imgui/imgui.gni")
+
+assert(chip_build_tools)
+
+import("${chip_root}/examples/common/pigweed/pigweed_rpcs.gni")
```
Comment (jamesharrow) [inline examples/energy-management-app/linux/BUILD.gn:23]: We will add Pigweed RPCs in a future commit - but not added them yet in this PR to help keep the PR small

File: examples/energy-management-app/linux/include/CHIPProjectAppConfig.h [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+
+// Bulbs do not typically use this - enabled so we can use shell to discover commissioners
+#define CHIP_DEVICE_CONFIG_ENABLE_COMMISSIONER_DISCOVERY_CLIENT 1
+
+#define CHIP_DEVICE_CONFIG_ENABLE_EXTENDED_DISCOVERY 1
+
+#define CHIP_DEVICE_CONFIG_ENABLE_COMMISSIONABLE_DEVICE_TYPE 1
+
+// TODO We don’t have one yet - but we’d need to change this
+#define CHIP_DEVICE_CONFIG_DEVICE_TYPE 257 // 0x0101 = 257 = Dimmable Bulb
```
Comment (jamesharrow) [inline examples/energy-management-app/linux/include/CHIPProjectAppConfig.h:43]: Who assigns these device type numbers?

Comment (bzbarsky-apple) [inline examples/energy-management-app/linux/include/CHIPProjectAppConfig.h:43]: These should be a device type id from the spec, no?  Should match the device selected in ZAP.

File: examples/energy-management-app/linux/main.cpp [hunk 7]
```diff
@@ -0,0 +1,144 @@
...
+        return;
+    }
+
+    /* Now create EVSEManufacturer*/
+    gEvseManufacturer = new EVSEManufacturer();
+    if (gEvseManufacturer == nullptr)
+    {
+        ChipLogError(AppServer, "Failed to allocate memory for EvseManufacturer");
+        delete gInstance;
+        delete gDelegate;
```
Comment (bzbarsky-apple) [inline examples/energy-management-app/linux/main.cpp:95]: All this cleanup might have benefited from some `std::auto_ptr` on the stack and releasing into the global pointer at the end... but this is fine.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by dhrishi — APPROVED** [review]

**Comment by dhrishi** [comment]
Approving it as per the review from Sonali

File: examples/energy-management-app/linux/main.cpp (hunk 7 above)
Comment (jamesharrow) [reply examples/energy-management-app/linux/main.cpp:95]: Noted.

File: examples/energy-management-app/energy-management-common/energy-management-app.matter [hunk 8]
```diff
@@ -0,0 +1,1419 @@
...
+    callback attribute supportedLocales;
+    callback attribute generatedCommandList;
+    callback attribute acceptedCommandList;
+    callback attribute eventList;
+    callback attribute attributeList;
+    ram      attribute featureMap default = 0;
+    ram      attribute clusterRevision default = 1;
+  }
+
+  server cluster TimeFormatLocalization {
```
[the remark this answers is not in the document]
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-management-app.matter]: Removed and regen'd

File: examples/energy-management-app/energy-management-common/energy-management-app.matter [hunk 9]
```diff
@@ -0,0 +1,1419 @@
...
+    handle command KeySetWrite;
+    handle command KeySetRead;
+    handle command KeySetReadResponse;
+    handle command KeySetRemove;
+    handle command KeySetReadAllIndices;
+    handle command KeySetReadAllIndicesResponse;
+  }
+}
+endpoint 1 {
+  device type ma_lightsensor = 262, version 1;
```
[the remark this answers is not in the document]
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-management-app.matter:1263]: Had to choose something since device type ID is still to be implemented.
Filed follow up issue [#31061](https://github.com/project-chip/connectedhomeip/issues/31061)

File: examples/energy-management-app/linux/include/CHIPProjectAppConfig.h (hunk 6 above)
Comment (jamesharrow) [reply examples/energy-management-app/linux/include/CHIPProjectAppConfig.h:43]: I've raised a follow up - [#31061](https://github.com/project-chip/connectedhomeip/issues/31061)
