### PR TITLE
Fix chip-tool threading asserts if an interactive command times out.

### LINKED ISSUE #27535: [Build] Darwin tsan failure in chip-tool
### Build issue(s)

https://github.com/project-chip/connectedhomeip/actions/runs/5401576138/jobs/9811580025

```
ERROR   14:34:35.573 - APP  OUT  : [1687962875573] [27599:293692] [DIS] Mdns: OnRegisterRecord flags: 1
ERROR   14:34:35.573 - APP  OUT  : [1687962875573] [27599:293692] [DIS] Mdns: OnRegisterRecord flags: 0
ERROR   14:34:35.573 - APP  OUT  : [1687962875573] [27599:293692] [DIS] Mdns: OnRegisterRecord flags: 1
ERROR   14:34:35.573 - APP  OUT  : [1687962875573] [27599:293692] [DIS] Mdns: OnRegisterRecord flags: 0
ERROR   14:34:48.676 - TEST ERR  : ==================
ERROR   14:34:48.676 - TEST ERR  : WARNING: ThreadSanitizer: data race (pid=27621)
ERROR   14:34:48.676 - TEST ERR  :   Write of size 1 at 0x7b5c00000510 by main thread:
ERROR   14:34:48.676 - TEST ERR  :     #0 chip::Optional<unsigned long long>::ClearValue() <null>:246088793 (chip-tool:x86_64+0x1001b419f) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.677 - TEST ERR  :     #1 void (anonymous namespace)::ResetOptionalArg<unsigned long long>(Argument const&) <null>:246088793 (chip-tool:x86_64+0x1011e1ab7) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.677 - TEST ERR  :     #2 Command::ResetArguments() <null>:246088793 (chip-tool:x86_64+0x1011e03e8) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.677 - TEST ERR  :     #3 CHIPCommand::Shutdown() <null>:246088793 (chip-tool:x86_64+0x1001871c5) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.677 - TEST ERR  :     #4 CHIPCommand::Run() <null>:246088793 (chip-tool:x86_64+0x1011cc4a7) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.677 - TEST ERR  :     #5 Command::RunAsInteractive(chip::Optional<char*> const&) <null>:246088793 (chip-tool:x86_64+0x1012050fd) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.677 - TEST ERR  :     #6 Commands::RunCommand(int, char**, bool, chip::Optional<char*> const&) <null>:246088793 (chip-tool:x86_64+0x101202fe4) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.677 - TEST ERR  :     #7 Commands::RunInteractive(char const*, chip::Optional<char*> const&) <null>:246088793 (chip-tool:x86_64+0x10120373a) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.677 - TEST ERR  :     #8 InteractiveCommand::ParseCommand(char*, int*) <null>:246088793 (chip-tool:x86_64+0x10122f353) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.677 - TEST ERR  :     #9 InteractiveServerCommand::OnWebSocketMessageReceived(char*) <null>:246088793 (chip-tool:x86_64+0x10122efb9) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.677 - TEST ERR  :     #10 non-virtual thunk to InteractiveServerCommand::OnWebSocketMessageReceived(char*) <null>:246088793 (chip-tool:x86_64+0x10122f82c) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.677 - TEST ERR  :     #11 WebSocketServer::OnWebSocketMessageReceived(char*) <null>:246088793 (chip-tool:x86_64+0x1016435c0) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.677 - TEST ERR  :     #12 (anonymous namespace)::OnWebSocketCallback(lws*, lws_callback_reasons, void*, void*, unsigned long) <null>:246088793 (chip-tool:x86_64+0x10164316b) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #13 user_callback_handle_rxflow <null>:246088793 (chip-tool:x86_64+0x10108c71f) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #14 lws_ws_frame_rest_is_payload <null>:246088793 (chip-tool:x86_64+0x1010b38a0) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #15 lws_parse_ws <null>:246088793 (chip-tool:x86_64+0x1010b2d01) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #16 lws_read_h1 <null>:246088793 (chip-tool:x86_64+0x10109b25f) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #17 rops_handle_POLLIN_ws <null>:246088793 (chip-tool:x86_64+0x1010afd71) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #18 lws_service_fd_tsi <null>:246088793 (chip-tool:x86_64+0x101085455) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #19 _lws_plat_service_forced_tsi <null>:246088793 (chip-tool:x86_64+0x1010b5d8a) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #20 _lws_plat_service_tsi <null>:246088793 (chip-tool:x86_64+0x1010b64fb) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #21 lws_plat_service <null>:246088793 (chip-tool:x86_64+0x1010b65e3) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #22 lws_service <null>:246088793 (chip-tool:x86_64+0x10108573e) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #23 WebSocketServer::Run(chip::Optional<unsigned short>, WebSocketServerDelegate*) <null>:246088793 (chip-tool:x86_64+0x101642c3d) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #24 InteractiveServerCommand::RunCommand() <null>:246088793 (chip-tool:x86_64+0x10122ec58) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #25 CHIPCommand::StartWaiting(std::__2::chrono::duration<unsigned int, std::__2::ratio<1l, 1000l> >) <null>:246088793 (chip-tool:x86_64+0x1011cc773) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #26 CHIPCommand::Run() <null>:246088793 (chip-tool:x86_64+0x1011cc458) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.678 - TEST ERR  :     #27 Commands::RunCommand(int, char**, bool, chip::Optional<char*> const&) <null>:246088793 (chip-tool:x86_64+0x101203261) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.679 - TEST ERR  :     #28 Commands::Run(int, char**) <null>:246088793 (chip-tool:x86_64+0x101201a1f) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.679 - TEST ERR  :     #29 main <null>:246088793 (chip-tool:x86_64+0x100181336) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.679 - TEST ERR  : 
ERROR   14:34:48.679 - TEST ERR  :   Previous read of size 1 at 0x7b5c00000510 by thread T1:
ERROR   14:34:48.679 - TEST ERR  :     #0 chip::Optional<unsigned long long>::HasValue() const <null>:246088793 (chip-tool:x86_64+0x1001fa109) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.679 - TEST ERR  :     #1 CHIPCommand::GetIdentityNodeId(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >, unsigned long long*) <null>:246088793 (chip-tool:x86_64+0x1011cbfac) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.679 - TEST ERR  :     #2 CHIPCommand::GetCommissioner(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >) <null>:246088793 (chip-tool:x86_64+0x1011ce146) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.679 - TEST ERR  :     #3 CHIPCommand::CurrentCommissioner() <null>:246088793 (chip-tool:x86_64+0x1011cdefa) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.679 - TEST ERR  :     #4 WaitForCommissioneeCommand::RunCommand() <null>:246088793 (chip-tool:x86_64+0x101211a41) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.679 - TEST ERR  :     #5 CHIPCommand::RunQueuedCommand(long) <null>:246088793 (chip-tool:x86_64+0x1011cf604) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.679 - TEST ERR  :     #6 chip::DeviceLayer::Internal::GenericPlatformManagerImpl<chip::DeviceLayer::PlatformManagerImpl>::_DispatchEvent(chip::DeviceLayer::ChipDeviceEvent const*) <null>:246088793 (chip-tool:x86_64+0x101431e62) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.679 - TEST ERR  :     #7 chip::DeviceLayer::PlatformManager::DispatchEvent(chip::DeviceLayer::ChipDeviceEvent const*) <null>:246088793 (chip-tool:x86_64+0x101432ae9) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.679 - TEST ERR  :     #8 invocation function for block in chip::DeviceLayer::PlatformManagerImpl::_PostEvent(chip::DeviceLayer::ChipDeviceEvent const*) <null>:246088793 (chip-tool:x86_64+0x101432a86) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.680 - TEST ERR  :     #9 __tsan::invoke_and_release_block(void*) <null>:246088793 (libclang_rt.tsan_osx_dynamic.dylib:x86_64+0x7d1db) (BuildId: 4c4c44ce55553144a15e063c7d8e617d2400000010000000000a0a0000010c00)
ERROR   14:34:48.680 - TEST ERR  :     #10 _dispatch_client_callout <null>:246088793 (libdispatch.dylib:x86_64+0x3316) (BuildId: 1a04b38076e43e4bb0fc9837533d021d32000000200000000100000000060c00)
ERROR   14:34:48.680 - TEST ERR  : 
ERROR   14:34:48.680 - TEST ERR  :   Location is heap block of size 832 at 0x7b5c00000380 allocated by main thread:
ERROR   14:34:48.680 - TEST ERR  :     #0 operator new(unsigned long) <null>:246088793 (libclang_rt.tsan_osx_dynamic.dylib:x86_64+0x80d3d) (BuildId: 4c4c44ce55553144a15e063c7d8e617d2400000010000000000a0a0000010c00)
ERROR   14:34:48.680 - TEST ERR  :     #1 std::__2::unique_ptr<Command, std::__2::default_delete<Command> > make_unique<WaitForCommissioneeCommand, CredentialIssuerCommands*&>(CredentialIssuerCommands*&) <null>:246088793 (chip-tool:x86_64+0x100050106) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.680 - TEST ERR  :     #2 registerCommandsDelay(Commands&, CredentialIssuerCommands*) <null>:246088793 (chip-tool:x86_64+0x10004ff8c) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.680 - TEST ERR  :     #3 main <null>:246088793 (chip-tool:x86_64+0x10018126d) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00)
ERROR   14:34:48.680 - TEST ERR  : 
ERROR   14:34:48.681 - TEST ERR  :   Thread T1 (tid=293070, running) is a GCD worker thread
ERROR   14:34:48.681 - TEST ERR  : 
ERROR   14:34:48.681 - TEST ERR  : SUMMARY: ThreadSanitizer: data race (chip-tool:x86_64+0x1001b419f) (BuildId: 4c4c44f655553144a16f6698152c453332000000200000000100000000000b00) in chip::Optional<unsigned long long>::ClearValue()+0x3f
ERROR   14:34:48.681 - TEST ERR  : ==================
ERROR   14:34:48.685 - TEST ERR  : Traceback (most recent call last):
ERROR   14:34:48.685 - TEST ERR  :   File "/Users/runner/work/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 968, in transfer_data
ERROR   14:34:48.699 - TEST ERR  :     message = await self.read_message()
ERROR   14:34:48.699 - TEST ERR  :   File "/Users/runner/work/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1038, in read_message
ERROR   14:34:48.699 - TEST ERR  :     frame = await self.read_data_frame(max_size=self.max_size)
ERROR   14:34:48.699 - TEST ERR  :   File "/Users/runner/work/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1113, in read_data_frame
ERROR   14:34:48.699 - TEST ERR  :     frame = await self.read_frame(max_size)
ERROR   14:34:48.699 - TEST ERR  :   File "/Users/runner/work/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1170, in read_frame
ERROR   14:34:48.699 - TEST ERR  :     frame = await Frame.read(
ERROR   14:34:48.700 - TEST ERR  :   File "/Users/runner/work/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/websockets/legacy/framing.py", line 69, in read
ERROR   14:34:48.701 - TEST ERR  :     data = await reader(2)
ERROR   14:34:48.701 - TEST ERR  :   File "/Users/runner/work/connectedhomeip/connectedhomeip/.environment/cipd/packages/python/lib/python3.9/asyncio/streams.py", line 723, in readexactly
ERROR   14:34:48.702 - TEST ERR  :     await self._wait_for_data('readexactly')
ERROR   14:34:48.702 - TEST ERR  :   File "/Users/runner/work/connectedhomeip/connectedhomeip/.environment/cipd/packages/python/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
ERROR   14:34:48.703 - TEST ERR  :     await self._waiter
ERROR   14:34:48.703 - TEST ERR  :   File "/Users/runner/work/connectedhomeip/connectedhomeip/.environment/cipd/packages/python/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
ERROR   14:34:48.705 - TEST ERR  :     data = self._sock.recv(self.max_size)
```

### Platform

_No response_

### Anything else?

_No response_

### LINKED ISSUE #29275: [CERT-TEST-FAILURE] Chip-tool crashes in interactive mode
### Feature Area

Other

### Test Case

Chip-tool Interactive Mode

### Reproduction steps

ToT (d4cbdbcd7c412e1f181675c4853060afcb7f31b0), 
1. build chip-tool using `./scripts/examples/gn_build_example.sh examples/chip-tool out/chip-tool 'chip_mdns="platform" chip_inet_config_enable_ipv4=false'`
2. build all cluster app (ACA) using` ./scripts/examples/gn_build_example.sh examples/all-clusters-app/linux examples/all-clusters-app/linux/out/all-cluster-app chip_inet_config_enable_ipv4=false chip_enable_icd_server=true `
3. Launch ACA using `./examples/all-clusters-app/linux/out/all-cluster-app/chip-all-clusters-app --KVS ~/storge.json`
4. launch ./out/chip-tool/chip-tool interactive start
5. provision using chip-tool using , `./out/chip-tool/chip-tool pairing code 50 MT:-24J042C00KA0648G00`
6. Read attribute like , `basicinformation read vendor-name 50 0`
7. kill and restart the ACA , using same cmd in step3
8. repeat step6, chip-tool crashes after MRP retries, log below

>>> basicinformation read vendor-name 50 0
[1694736729225] [39906:71817125] [TOO] Command: basicinformation read vendor-name 50 0 
[1694736729226] [39906:71817127] [TOO] Sending command to node 0x32
[1694736729227] [39906:71817127] [CSM] FindOrEstablishSession: PeerId = [1:0000000000000032]
[1694736729227] [39906:71817127] [CSM] FindOrEstablishSession: No existing OperationalSessionSetup instance found
[1694736729227] [39906:71817127] [DIS] Found an existing secure session to [1:0000000000000032]!
[1694736729227] [39906:71817127] [DIS] OperationalSessionSetup[1:0000000000000032]: State change 1 --> 5
[1694736729227] [39906:71817127] [TOO] Sending ReadAttribute to:
[1694736729227] [39906:71817127] [TOO] 	cluster 0x0000_0028, attribute: 0x0000_0001, endpoint 0
[1694736729227] [39906:71817127] [DMG] SendReadRequest ReadClient[0x128804bb0]: Sending Read Request
[1694736729227] [39906:71817127] [EM] <<< [E:59723i S:45800 M:116333174] (S) Msg TX to 1:0000000000000032 [E009] --- Type 0001:02 (IM:ReadRequest)
[1694736729227] [39906:71817127] [IN] (S) Sending msg 116333174 on secure session with LSID: 45800
[1694736729228] [39906:71817127] [DMG] MoveToState ReadClient[0x128804bb0]: Moving to [AwaitingIn]
[1694736735322] [39906:71817127] [EM] Retransmitting MessageCounter:116333174 on exchange 59723i Send Cnt 1
[1694736735323] [39906:71817127] [IN] (S) Sending msg 116333174 on secure session with LSID: 45800
[1694736741317] [39906:71818695] [EM] Retransmitting MessageCounter:116333174 on exchange 59723i Send Cnt 2
[1694736741318] [39906:71818695] [IN] (S) Sending msg 116333174 on secure session with LSID: 45800
[1694736752199] [39906:71818917] [EM] Retransmitting MessageCounter:116333174 on exchange 59723i Send Cnt 3
[1694736752200] [39906:71818917] [IN] (S) Sending msg 116333174 on secure session with LSID: 45800
[1694736769466] [39906:71819421] [EM] Retransmitting MessageCounter:116333174 on exchange 59723i Send Cnt 4
[1694736769466] [39906:71819421] [IN] (S) Sending msg 116333174 on secure session with LSID: 45800
[1694736789226] [39906:71817125] [DL] Chip stack locking error at 'src/system/SystemLayerImplSelect.cpp:260'. Code is unsafe/racy
[1694736789226] [39906:71817125] [-] chipDie chipDie chipDie
zsh: abort      ./out/chip-tool/chip-tool interactive start

### Bug prevalence

every time

### GitHub hash of the SDK that was being used

d4cbdbcd7c412e1f181675c4853060afcb7f31b0

### Platform

darwin

### Anything else?

Same issue happens on linux as well.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Since the Matter event loop is still running in interacive mode, we need to do the command cleanup on that event loop.

* Fixes https://github.com/project-chip/connectedhomeip/issues/29275
* Fixes https://github.com/project-chip/connectedhomeip/issues/27535

### CODE REVIEW

**Review by vivien-apple — APPROVED** [review]

File: examples/chip-tool/commands/common/CHIPCommand.cpp [hunk 1]
```diff
@@ -504,6 +505,63 @@ void CHIPCommand::RunQueuedCommand(intptr_t commandArg)
...
+            std::lock_guard<std::mutex> lk(cvWaitingForResponseMutex);
+            mWaitingForResponse = false;
+        }
+        return err;
+    }
+
+    auto waitingUntil = std::chrono::system_clock::now() + std::chrono::duration_cast<std::chrono::seconds>(timeout);
+    {
+        std::unique_lock<std::mutex> lk(cvWaitingForResponseMutex);
+        if (!cvWaitingForResponse.wait_until(lk, waitingUntil, [this]() { return !this->mWaitingForResponse; }))
```
Comment (andy31415) [inline examples/chip-tool/commands/common/CHIPCommand.cpp:552]: seems like this is:

```cpp
timeout = !cvWaitingForResponse.wait_until(
    lk, waitingUntil, 
    [this]() { return !this->mWaitingForResponse; });
```

**Review by andy31415 — APPROVED** [review]

File: examples/chip-tool/commands/common/CHIPCommand.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply examples/chip-tool/commands/common/CHIPCommand.cpp]: Good catch, done.
