### PR TITLE
Fixes: #31672 avoids a deliberate crash on targets which don't suppor…

### LINKED ISSUE #31672: M5 board keeps resetting itself after pairing to Home app and the accessory goes to No Response state
### Reproduction steps

With the latest SHA, M5 board keeps resetting itself after pairing to Home app and the accessory goes to No Response state

SHA: 7f5e208f78847466816cd0544617ab077d3d0bb5

1. cd ~/connectedhomeip
2. git reset --hard 7f5e208f78847466816cd0544617ab077d3d0bb5
3. source scripts/bootstrap.sh
4. source scripts/activate.sh
5. cd ~/tools/esp-idf 
6. git checkout v5.1
7. ./install.sh
8. . ./export.sh
9. cd ~/connectedhomeip/examples/all-clusters-app/esp32
10. export ZAP_INSTALL_PATH=~/Downloads/zap-mac/
11. idf.py build
12. idf.py menuconfig -> select M5 from Demo
13. idf.py -D 'SDKCONFIG_DEFAULTS=sdkconfig_m5stack.defaults' erase-flash build flash monitor
14. Launch HomeApp
15. Pair M5 board with HomeApp

Results:
Soon after pairing, M5 board keeps resetting itself and the accessory goes to No Response state

### Bug prevalence

all the time

### GitHub hash of the SDK that was being used

7f5e208f78847466816cd0544617ab077d3d0bb5

### Platform

darwin

### Platform Version(s)

_No response_

### Type

Core SDK Crash

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jamesharrow**
Fixes: #31672 
 - #31672 

This was caused by a VerifyOrDie() when the platform System::SystemClock().GetClock_RealTimeMS(cTMs) returns CHIP_ERROR_UNSUPPORTED_CHIP_FEATURE.

- [x] Removed the VerifyOrDie and made it fail more gracefully

Note platforms not supporting realtime clock cannot support EVSE cluster.

### CODE REVIEW

File: examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp [hunk 1]
```diff
@@ -1474,7 +1474,11 @@ CHIP_ERROR GetEpochTS(uint32_t & chipEpoch)
      * This should not be certifiable since getting time is a Mandatory
      * feature of EVSE Cluster
      */
-    VerifyOrDie(err != CHIP_ERROR_UNSUPPORTED_CHIP_FEATURE);
+    if (err == CHIP_ERROR_UNSUPPORTED_CHIP_FEATURE)
```
Comment (tehampson) [inline examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp:1477]: Should the comment above be changed, or moved to a more appropriate location? How are you making sure that at cert the device fails?

Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/src/EnergyEvseDelegateImpl.cpp:1477]: The TC_EEVSE_2_2 performs lots of checks on the fact that Session events should be generated when an EV is plugged in or unplugged. So the fact that this causes an early exit from the code which calls GetEpochTS() will mean that the certification test will fail.

As for moving the comments somewhere else - I'm not sure if there is a better place than here.

I may be tempted if anything to beef up the error message printed out so it is clear to manufacturers they need to fix this.

This function is only called within the EVSE code base.

**Review by simonhmorris1 — APPROVED** [review]

**Review by tcarmelveilleux — APPROVED** [review]

**Review by tehampson — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]
