### PR TITLE
[Android] Fix crash when read/subscribe attribute API

### LINKED ISSUE #22890: [1.0] [Android] Crash when deviceController subscribeToPath
### Reproduction steps

```bash
1. Connect the device in Android ChipTool app.
2. Then Click WILDCARD.
3. Input Endpoint:1, Cluster ID: 6, Attribute Id: 0.
4. Click SUBSCRIBE. App will crash.
```

### Bug prevalence

Every time.

### GitHub hash of the SDK that was being used

4f7669b052b16bd054227376e1bbadac85419793

### Platform

android

### Platform Version(s)

_No response_

### Type

Platform Issue

### Anything else?

Code:
```
 deviceController.subscribeToPath(subscriptionEstablishedCallback,
                                       resubscriptionAttemptCallback,
                                       reportCallback,
                                       ChipClient.getConnectedDevicePointer(requireContext(),
                                       addressUpdateFragment.deviceId),
                                       listOf(attributePath),
                                       null,
                                       minInterval,
                                       maxInterval,
                                       keepSubscriptions,
                                       isFabricFiltered)
```
Logs:
[matterlog.txt](https://github.com/project-chip/connectedhomeip/files/9651220/matterlog.txt)

### PR DESCRIPTION
**Pull request by joonhaengHeo**
Issue Being Resolved

> Fixes https://github.com/project-chip/connectedhomeip/issues/22890
> And, Read attribute button is almost same issue. 

Change overview
>  Both EventPath and AttributePath must be non-null to avoid crashing.
> Therefore, it has been modified to treat as an error only when both are null.
(Also, the Test App UI has been modified.)

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

File: src/controller/java/CHIPDeviceController-JNI.cpp [hunk 1]
```diff
@@ -1149,6 +1149,8 @@ JNI_METHOD(void, read)
     err = ParseEventPathList(eventPathList, eventPathParamsList);
     VerifyOrReturn(err == CHIP_NO_ERROR, ChipLogError(Controller, "Error parsing Java event paths: %s", ErrorStr(err)));
 
+    VerifyOrReturn(attributePathParamsList.size() != 0 || eventPathParamsList.size() != 0,
```
Comment (yufengwangca) [inline src/controller/java/CHIPDeviceController-JNI.cpp:1152]: Your PR description say "Both EventPath and AttributePath must be non-null to avoid crashing." It is not aligned with the check here, should it be

`VerifyOrReturn(attributePathParamsList.size() != 0 && eventPathParamsList.size() != 0,`

Comment (joonhaengHeo) [reply src/controller/java/CHIPDeviceController-JNI.cpp:1152]: Currently, a crash does not occur only when both variables are not null. However, only one variable of Attribute and Event is set in the Test App, and the remaining values are set to null. If the size of one variable is not 0, it should be treated as vailed because it should also be processed.

**Review by yufengwangca — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]
LGTM, thanks
