### PR TITLE
event: Exclude the unsupported event paths if receiving an event read request with a wildcard event path

### LINKED ISSUE #41056: [BUG] Incorrect behavior when reading a wildcard event that only includes unsupported events
### Reproduction steps

Test with the example using other data model provider which doesn't support the optional events `ConnectionStatus` and `NetworkFaultChange` in `ThreadNetworkDiagnostics` cluster:
Read a wildcard event path that only includes the above unsupported events, the chip-tool report a timeout error instead of an empty report.

### Bug prevalence

Whenever I do it

### GitHub hash of the SDK that was being used

098e831ede197a7c94a023a521bcbfbd907ec01a

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by wqx6**
#### Summary

This PR fixes the incorrect behavior for example using other data model provider.
Exclude the unsupported event paths if receiving an event read request with a wildcard event path

#### Related issues

Fixes #41056

#### Testing

Test with an example that uses other data model provider which doesn't support the optional events in ThreadNetworkDiagnostics cluster.

- Read event with a wildcard path that only includes the unsupported event, the chip-tool gets an empty report.

### CODE REVIEW

**Review by andy31415 — CHANGES_REQUESTED** [review]
Added some comments in the reported bug. For the PR could you explain how we know about "event not supported"? Over time we established that knowing what events are supported or not is really difficult, so ember by default just says "if I do not know, assume the default kView" (which is also done to save flash since this is a common default).

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp [hunk 1]
```diff
@@ -252,9 +252,19 @@ CHIP_ERROR CodegenDataModelProvider::EventInfo(const ConcreteEventPath & path, D
     {
         return cluster->EventInfo(path, eventInfo);
     }
-
-    eventInfo.readPrivilege = RequiredPrivilege::ForReadEvent(path);
-    return CHIP_NO_ERROR;
+    const EmberAfCluster * cluster = emberAfFindServerCluster(path.mEndpointId, path.mClusterId);
```
Comment (andy31415) [inline src/data-model-providers/codegen/CodegenDataModelProvider.cpp]: Why do we need this check? I imagine:

- if doing wildcard expansion, then the path will be valid already
- if not doing wildcard expansion, the caller can validate the path if needed

File: src/app/EventManagement.cpp [hunk 2]
```diff
@@ -553,7 +553,13 @@ CHIP_ERROR EventManagement::CheckEventContext(EventLoadOutContext * eventLoadOut
     ReturnErrorOnFailure(ret);
 
     DataModel::EventEntry eventInfo;
-    ReturnErrorOnFailure(InteractionModelEngine::GetInstance()->GetDataModelProvider()->EventInfo(path, eventInfo));
+    if (InteractionModelEngine::GetInstance()->GetDataModelProvider()->EventInfo(path, eventInfo) != CHIP_NO_ERROR)
+    {
+        // If we cannot get event info here, the interested path should be a wildcard path but the data model doesn't
+        // support the event, return CHIP_ERROR_UNEXPECTED_EVENT here so the event path will be excluded in the generated
+        // event report.
+        return CHIP_ERROR_UNEXPECTED_EVENT;
```
Comment (andy31415) [inline src/app/EventManagement.cpp]: This change looks correct, but then this method is crazy: it seems to either return UNEXPECTED_EVENT or NO_ERROR and nothing else ... that is a footgun (which we clealy triggered before) ... lets make it return a bool then if it is just a yes/no.

Comment (andy31415) [reply src/app/EventManagement.cpp]: I looked at its documentation and it *wrongly* claims it can return CHIP_EVENT_ID_FOUND and CHIP_ERROR_ACCESS_DENIED (with a todo to use an enum).

I would suggest to switch it to a non-chip-error enum or bool now.

Comment (wqx6) [reply src/app/EventManagement.cpp]: Changed the return value to bool.

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp (hunk 1 above)
Comment (wqx6) [reply src/data-model-providers/codegen/CodegenDataModelProvider.cpp]: This function will not accept a wildcard event path as the input path is a concrete path.

And for the concrete event path, the codegen data model might not support that event.

In zap code, there are event lists in the generated cluster structures https://github.com/project-chip/connectedhomeip/blob/master/scripts/tools/zap/tests/outputs/all-clusters-app/app-templates/endpoint_config.h#L3607-L3608, if the event is not supported, the list will not include the event id of that event.

So I add this check in EventInfo function.

File: src/app/EventManagement.cpp (hunk 2 above)
Comment (wqx6) [reply src/app/EventManagement.cpp:561]: And I also removed the Access check as it has been done in the report engine.

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/data-model-providers/codegen/CodegenDataModelProvider.cpp]: > In zap code, there are event lists in the generated cluster structures

That data is generally wrong.  We don't do anything with it right now, because of that, and if we start it's likely to break existing applications.

What we should probably do is stop generating that stuff (because it's just wasted codesize) and fix the ZAP UI to not even try to expose whether events are supported.

If an event is being generated, it's supported.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]
See https://github.com/project-chip/connectedhomeip/pull/41057#discussion_r2369841623

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp (hunk 1 above)
Comment (wqx6) [reply src/data-model-providers/codegen/CodegenDataModelProvider.cpp]: Thanks for the explanation, reverted this change now and only keep the changes in EventManagement

File: src/app/EventManagement.cpp [hunk 3]
```diff
@@ -522,38 +522,45 @@ CHIP_ERROR EventManagement::CopyEvent(const TLVReader & aReader, TLVWriter & aWr
     return CHIP_NO_ERROR;
 }
 
-CHIP_ERROR EventManagement::CheckEventContext(EventLoadOutContext * eventLoadOutContext,
-                                              const EventManagement::EventEnvelopeContext & event)
+bool EventManagement::CheckEventContext(EventLoadOutContext * eventLoadOutContext,
```
Comment (andy31415) [inline src/app/EventManagement.cpp]: `Check` seems vague in the name ... check for what?  Based on the documentation, this may be named `IncludeEventInReport` ... or any other name that makes sense as reading it as a bool. 

Could we rename it?

File: src/app/EventManagement.cpp [hunk 4]
```diff
@@ -602,25 +609,17 @@ CHIP_ERROR EventManagement::EventIterator(const TLVReader & aReader, size_t aDep
...
-    if (err == CHIP_NO_ERROR)
-    {
-        err = CHIP_EVENT_ID_FOUND;
-    }
-    else if (err == CHIP_ERROR_UNEXPECTED_EVENT)
-    {
-        err = CHIP_NO_ERROR;
-    }
-
+    encodeEvent = CheckEventContext(apEventLoadOutContext, *event);
```
Comment (andy31415) [inline src/app/EventManagement.cpp]: should we change the return below to `return CHIP_NO_ERROR` ? it amounts to the same because we `ReturnErrorOnFailure` above ... maybe that makes it clear that if we get here we are succeeding.

**Review by andy31415 — APPROVED** [review]

File: src/app/EventManagement.cpp (hunk 3 above)
Comment (bzbarsky-apple) [reply src/app/EventManagement.cpp]: I would love it if we gave this thing a sane name.... That might also lead us to the understanding that it should be multiple functions, depending on what happens when we try to name it.

But that might want to be a separate PR.

File: src/app/EventManagement.cpp [hunk 5]
```diff
@@ -522,38 +522,45 @@ CHIP_ERROR EventManagement::CopyEvent(const TLVReader & aReader, TLVWriter & aWr
...
+    {
+        return false;
+    }
 
     DataModel::EventEntry eventInfo;
-    ReturnErrorOnFailure(InteractionModelEngine::GetInstance()->GetDataModelProvider()->EventInfo(path, eventInfo));
+    if (InteractionModelEngine::GetInstance()->GetDataModelProvider()->EventInfo(path, eventInfo) != CHIP_NO_ERROR)
+    {
+        // If we cannot get event info here, the interested path should be a wildcard path but the data model does't
+        // support the event, return false here so the event path will be excluded in the generated event report.
```
Comment (bzbarsky-apple) [inline src/app/EventManagement.cpp]: So just to make sure: this is an event that:

1.  Our data model claims we don't support.
2. We actually generated an instance of.

I have to ask: why do we even have this event in our buffer?   It's taking up space, possibly evicting other events, but we will never actually deliver it to anyone, right?

As in, should an existence/support check perhaps be where events are placed in the buffer?

That does still leave the question of what to do if that check passed but this one fails.  That could in fact happen if the endpoint the event was for has gone away, right?  Though ideally in that situation we would remove those stray events for the now-gone endpoint from the buffer (another followup may be needed here).

But for now we're basically preserving behavior here, ok.

File: src/app/EventManagement.h [hunk 6]
```diff
@@ -511,9 +511,11 @@ class EventManagement : public DataModel::EventsGenerator
      *
      * The function is used to scan through the event log to find events matching the spec in the supplied context.
      * Particularly, it would check against mStartingEventNumber, and skip fetched event.
+     *
+     * If the fetched event log is not going to be filtered, the encodeEvent will be true.
```
Comment (bzbarsky-apple) [inline src/app/EventManagement.h]:
```suggestion
     * On success, if the event represented by the EventEnvelopeContext should be encoded, encodeEvent will be set to true.
```

File: src/app/EventManagement.h [hunk 7]
```diff
@@ -542,15 +544,10 @@ class EventManagement : public DataModel::EventsGenerator
     /**
      * @brief Check whether the event instance represented by the EventEnvelopeContext should be included in the report.
      *
-     * @retval CHIP_ERROR_UNEXPECTED_EVENT This path should be excluded in the generated event report.
-     * @retval CHIP_EVENT_ID_FOUND This path should be included in the generated event report.
```
Comment (bzbarsky-apple) [inline src/app/EventManagement.h:546]: Followup: can we remove CHIP_EVENT_ID_FOUND?

File: src/app/EventManagement.h [hunk 8]
```diff
@@ -542,15 +544,10 @@ class EventManagement : public DataModel::EventsGenerator
...
-     * @retval CHIP_ERROR_ACCESS_DENIED This path should be included in the generated event report, but the client does not have
-     * .       enough privilege to access it.
-     *
-     * TODO: Consider using CHIP_NO_ERROR, CHIP_ERROR_SKIP_EVENT, CHIP_ERROR_ACCESS_DENINED or some enum to represent the checking
-     * result.
+     * @retval false This path should be excluded in the generated event report.
+     * @retval true This path should be included in the generated event report.
```
Comment (bzbarsky-apple) [inline src/app/EventManagement.h]: Which "this path"?  This is not just a path check, though it does some path checking as well.  This is a check of some combination of the EventEnvelopeContext and the EventLoadOutContext (with the actual "event" apparently represented by a mix of the two, and the accessing fabric information represented in the EventLoadOutContext)?

I'm sorry, because I know you did not create these rather messed-up types, so it's not your fault, but for now we should at least have the comments match reality.

File: src/app/EventManagement.cpp (hunk 3 above)
Comment (wqx6) [reply src/app/EventManagement.cpp]: Changed the name.

File: src/app/EventManagement.cpp (hunk 4 above)
Comment (wqx6) [reply src/app/EventManagement.cpp]: Done

File: src/app/EventManagement.cpp (hunk 5 above)
Comment (wqx6) [reply src/app/EventManagement.cpp]: This issue is not for the code-gen data model provider, since our code-gen data model provider support all the events. It occurs on a data model provider that doesn't support some optional events. If a client reads a wildcard event path that includes the unsupported events, the read will fail, instead of not including the unsupported events in the report.

File: src/app/EventManagement.h (hunk 6 above)
Comment (wqx6) [reply src/app/EventManagement.h]: Done

File: src/app/EventManagement.h (hunk 7 above)
Comment (wqx6) [reply src/app/EventManagement.h:546]: Yes, create #41163.

File: src/app/EventManagement.h (hunk 8 above)
Comment (wqx6) [reply src/app/EventManagement.h]: Changed it to `this event instance`

File: src/app/EventManagement.cpp (hunk 5 above)
Comment (bzbarsky-apple) [reply src/app/EventManagement.cpp]: OK, but how did an unsupported event get generated at all?

As I see it, we have the following:

1. Event generation should not allow generating events which we can never put on the wire.  Followup is probably OK, as long as it happens.
2. If we do have such an event (e.g. it got generated and then the endpoint went away), then for now the changes in this PR are fine, but as a followup we should perhaps have such events go away (similar to how `EventManagement::FabricRemoved` works).

Comment (wqx6) [reply src/app/EventManagement.cpp]: Could we add check in LogEvent() so that we will not generate events for the invalid event path?

Add a TODO comment to remove the events with invalid paths.

Comment (bzbarsky-apple) [reply src/app/EventManagement.cpp]: > Could we add check in LogEvent() so that we will not generate events for the invalid event path?

Yes, that is what I am saying we should do.  Again, followup is ok, but needs to be tracked.

Comment (wqx6) [reply src/app/EventManagement.cpp]: https://github.com/project-chip/connectedhomeip/issues/41448

File: src/app/EventManagement.cpp [hunk 9]
```diff
@@ -522,38 +522,48 @@ CHIP_ERROR EventManagement::CopyEvent(const TLVReader & aReader, TLVWriter & aWr
...
 
     DataModel::EventEntry eventInfo;
-    ReturnErrorOnFailure(InteractionModelEngine::GetInstance()->GetDataModelProvider()->EventInfo(path, eventInfo));
+    if (InteractionModelEngine::GetInstance()->GetDataModelProvider()->EventInfo(path, eventInfo) != CHIP_NO_ERROR)
+    {
+        // If we cannot get event info here, the interested path should be a wildcard path but the data model does't support the
+        // event (eg. The endpoint is removed), return false here so the event path will be excluded in the generated event report.
+        // TODO: We should not record the event in the log buffer when the event is not supported by the data model
+        // TODO: We should remove the event from the log buffer when the event path is no longer valid (eg. when the endpoint of the
+        // event path is removed).
```
Comment (bzbarsky-apple) [inline src/app/EventManagement.cpp]:
```suggestion
        // If we cannot get event info here, that means the data model doesn't support the
        // event (eg. the endpoint is removed).  Return false, because we can't even perform ACL checks here,
        // since we don't know what permissions to check for.  This is not an error condition
        // (other than omitting the event), because the only way we can end up in this situation
        // is with a wildcard event path.
        //
        // TODO: We should not record the event in the log buffer when the event is not supported by the data model
        // TODO: We should remove the event from the log buffer when the event path is no longer valid (eg. when the endpoint of the
        // event path is removed).
```

File: src/app/EventManagement.cpp [hunk 10]
```diff
@@ -522,38 +522,48 @@ CHIP_ERROR EventManagement::CopyEvent(const TLVReader & aReader, TLVWriter & aWr
...
+    }
 
     DataModel::EventEntry eventInfo;
-    ReturnErrorOnFailure(InteractionModelEngine::GetInstance()->GetDataModelProvider()->EventInfo(path, eventInfo));
+    if (InteractionModelEngine::GetInstance()->GetDataModelProvider()->EventInfo(path, eventInfo) != CHIP_NO_ERROR)
+    {
+        // If we cannot get event info here, the interested path should be a wildcard path but the data model does't support the
+        // event (eg. The endpoint is removed), return false here so the event path will be excluded in the generated event report.
+        // TODO: We should not record the event in the log buffer when the event is not supported by the data model
+        // TODO: We should remove the event from the log buffer when the event path is no longer valid (eg. when the endpoint of the
```
Comment (bzbarsky-apple) [inline src/app/EventManagement.cpp]: The TODO comments should mention the issues tracking those TODOs.

File: src/app/EventManagement.cpp [hunk 11]
```diff
@@ -563,17 +573,17 @@ CHIP_ERROR EventManagement::CheckEventContext(EventLoadOutContext * eventLoadOut
         Access::GetAccessControl().Check(eventLoadOutContext->mSubjectDescriptor, requestPath, eventInfo.readPrivilege);
     if (accessControlError != CHIP_NO_ERROR)
     {
-        VerifyOrReturnError((accessControlError == CHIP_ERROR_ACCESS_DENIED) ||
-                                (accessControlError == CHIP_ERROR_ACCESS_RESTRICTED_BY_ARL),
-                            accessControlError);
-        ret = CHIP_ERROR_UNEXPECTED_EVENT;
+        // If we don't have the access for the event, the interested path should be a wildcard path. Return false so that
+        // the event path will be excluded in the generated event report.
```
Comment (bzbarsky-apple) [inline src/app/EventManagement.cpp]:
```suggestion
        // If we don't have the access for the event, the only way we could have gotten here
        // is due to a wildcard event path that includes the event.  Return false so that
        // the event will be excluded in the generated event report.
```

What we are including/excluding here are events, not event paths.  Different events for the same path might end up with different return values from this function, in general.

File: src/app/EventManagement.cpp [hunk 12]
```diff
@@ -563,17 +573,17 @@ CHIP_ERROR EventManagement::CheckEventContext(EventLoadOutContext * eventLoadOut
...
+        return false;
     }
 
-    return ret;
+    // If all the checks pass, the event path will be included in the generated event report.
```
Comment (bzbarsky-apple) [inline src/app/EventManagement.cpp]:
```suggestion
    // If all the checks pass, the event will be included in the generated event report.
```

**Review by bzbarsky-apple — APPROVED** [review]
