### PR TITLE
WindowCovering: Add operational-status + YAML tests

### LINKED ISSUE #14392: [TC-WNCV-3.1 3.2] Yaml file need update for Command & Report Verification with server as DUT
#### Problem
<what's wrong or missing, please include any applicable:
 * Missing Report check of Operational status
 * Need Conditional testing from FeatureMap
 * Test Plan has been updated and the current are not conformant
 >

### PR DESCRIPTION
**Pull request by jmeg-sfy**
#### Problem
What is being fixed?  Examples:
* Operational status was not implemented in the example
* Update and Complete tests  WNCV 3.1, 3.2, 3.3 for the test harness

#### Change overview
What's in this PR
* Modification of all-cluster to include a simple delayed callback to simulate a move
* Some factorization and fixes in the EFR32 to add operational status
* Usage of a dedicated callback for attributes modification
* Update the feature maps to allows Tilt + Lift as position aware

#### Testing
How was this tested? (at least one bullet point required)
* Commission and Tested on Thread EFR32 demo
* CI pass on Linux + Darwin
* chip-tool is updated following the test plan

close https://github.com/project-chip/connectedhomeip/issues/14392

### CODE REVIEW

**Review by jmartinez-silabs — APPROVED** [review]

File: examples/all-clusters-app/linux/main-common.cpp [hunk 1]
```diff
@@ -116,3 +117,16 @@ void emberAfLowPowerClusterInitCallback(EndpointId endpoint)
...
     chip::app::Clusters::LowPower::SetDefaultDelegate(endpoint, &lowPowerManager);
 }
+
+void MatterPostAttributeChangeCallback(const chip::app::ConcreteAttributePath & attributePath, uint8_t mask, uint8_t type,
+                                       uint16_t size, uint8_t * value)
+{
+    switch (attributePath.mClusterId)
+    {
+    case chip::app::Clusters::WindowCovering::Id:
+        MatterWindowCoveringClusterServerAttributeChangedCallback(attributePath);
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/linux/main-common.cpp:127]: I assume this behavior is not Linux-specific, right?

The way this should work, and I know it's non-obvious, is that in `src/app/zap-templates/templates/app/helper.js` the cluster name gets added to the `endpointClusterWithAttributeChanged` array.  That will codegen the right bits that `MatterWindowCoveringClusterServerAttributeChangedCallback` will be automatically called by the SDK, instead of the application having to do it.  Then the application's `MatterPostAttributeChangeCallback` is just used for the state the application wants to maintain.

File: examples/window-app/common/src/WindowApp.cpp [hunk 2]
```diff
@@ -296,33 +293,54 @@ void WindowApp::DispatchEvent(const WindowApp::Event & event)
...
+    {
+        emberAfWindowCoveringClusterPrint("Ep[%u] not supported AttributeId=%u\n", endpoint, (unsigned int) attribute);
+        return;
+    }
 
+    switch (attribute)
+    {
+    /* For a device supporting Position Awareness : Changing the Target triggers motions on the real or simulated device */
+    case Attributes::TargetPositionLiftPercent100ths::Id:
+        cover->LiftGoToTarget();
```
Comment (bzbarsky-apple) [inline examples/window-app/common/src/WindowApp.cpp:318]: As a followup: this seems like it should be shared cluster logic, not per-app logic...  That is, the cluster should notice the attribute change and trigger an app callback of some sort, instead of every app having to know how attributes map into behavior.

File: examples/window-app/common/src/ZclCallbacks.cpp [hunk 3]
```diff
@@ -39,83 +40,22 @@ using namespace ::chip::app::Clusters::WindowCovering;
 void MatterPostAttributeChangeCallback(const app::ConcreteAttributePath & attributePath, uint8_t mask, uint8_t type, uint16_t size,
                                        uint8_t * value)
 {
-    if (attributePath.mClusterId == app::Clusters::Identify::Id)
+    switch (attributePath.mClusterId)
     {
+    case Id:
+        MatterWindowCoveringClusterServerAttributeChangedCallback(attributePath);
```
Comment (bzbarsky-apple) [inline examples/window-app/common/src/ZclCallbacks.cpp:46]: Again, the cluster should just register for these notifications directly, instead of relying on the app to notify it.

File: examples/window-app/common/src/ZclCallbacks.cpp [hunk 4]
```diff
@@ -39,83 +40,22 @@ using namespace ::chip::app::Clusters::WindowCovering;
...
 }
 
-/**
- * @brief  Cluster StopMotion Command callback (from client)
- */
-bool emberAfWindowCoveringClusterStopMotionCallback(chip::app::CommandHandler * commandObj,
-                                                    const chip::app::ConcreteCommandPath & commandPath,
-                                                    const Commands::StopMotion::DecodableType & commandData)
+/* Forwards all attributes changes */
+void MatterWindowCoveringClusterServerAttributeChangedCallback(const app::ConcreteAttributePath & attributePath)
```
Comment (bzbarsky-apple) [inline examples/window-app/common/src/ZclCallbacks.cpp:58]: This should be implemented in the cluster itself, no?

But if all it's doing is running app logic (for now), this should presumably just happen in the app post-attribute-changed callback.

File: src/app/clusters/window-covering-server/window-covering-server.cpp [hunk 5]
```diff
@@ -649,4 +764,16 @@ bool emberAfWindowCoveringClusterGoToTiltPercentageCallback(app::CommandHandler
     return true;
 }
 
+/**
+ * @brief Cluster Attribute Changed Callback
+ */
+void __attribute__((weak))
```
Comment (bzbarsky-apple) [inline src/app/clusters/window-covering-server/window-covering-server.cpp:770]: Why weak?  This is where spec-defined cluster logic should go.  App logic goes in the app post-attr-change notification, which is called separately.  There's no reason for an app to override this callback....

File: src/app/clusters/window-covering-server/window-covering-server.h [hunk 6]
```diff
@@ -146,6 +148,8 @@ uint16_t TiltToPercent100ths(chip::EndpointId endpoint, uint16_t tilt);
 uint16_t Percent100thsToTilt(chip::EndpointId endpoint, uint16_t percent100ths);
 void TiltPositionSet(chip::EndpointId endpoint, uint16_t percent100ths);
 
+void PostAttributeChange(chip::EndpointId endpoint, chip::AttributeId attributeId);
```
Comment (bzbarsky-apple) [inline src/app/clusters/window-covering-server/window-covering-server.h:151]: This is not public API, right?  Why is it in the header?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: examples/all-clusters-app/linux/main-common.cpp (hunk 1 above)
Comment (jmeg-sfy) [reply examples/all-clusters-app/linux/main-common.cpp:127]: I was wondering that indeed this is not cluster specific and this why i have added a weak reference you pointed later
Ok gonna have look for an update thk

File: examples/window-app/common/src/WindowApp.cpp (hunk 2 above)
Comment (jmeg-sfy) [reply examples/window-app/common/src/WindowApp.cpp:318]: indeed we need to have single implementation as a follow up
but due to amount of diff and time constraint my goal is to implement all the missing test in the TH

File: src/app/clusters/window-covering-server/window-covering-server.cpp (hunk 5 above)
Comment (jmeg-sfy) [reply src/app/clusters/window-covering-server/window-covering-server.cpp:770]: Yes indeed, but right now we got two separated logic. The one in all-cluster-app  and the one in Window-app used on EFR32. My goal is to merge everything into a single app but due to time constraints and amount of diff that would do i propose to do that later in next PR. Here is to implement the missing tests.
If you look at stop-motion before this was using weak and now removed. Right there is one PostAttributeChange in window-covering-server.cpp and another in ZclCallbacks.cpp

File: examples/window-app/common/src/ZclCallbacks.cpp (hunk 4 above)
Comment (jmeg-sfy) [reply examples/window-app/common/src/ZclCallbacks.cpp:55]: The post-attribute callback is forwarding everything in the queue for the EFR32 app demo . The other does simple fake motion with a timer to implement the Test . Further goals is to create a linux app and passing the test for TH in it rather than all-cluster-app

File: examples/all-clusters-app/linux/main-common.cpp (hunk 1 above)
Comment (jmeg-sfy) [reply examples/all-clusters-app/linux/main-common.cpp]: Removed following your advice

**Comment by jmeg-sfy** [comment]
@bzbarsky-apple did some modifs and comments

File: examples/window-app/common/src/ZclCallbacks.cpp [hunk 7]
```diff
@@ -39,83 +40,19 @@ using namespace ::chip::app::Clusters::WindowCovering;
...
```
Comment (bzbarsky-apple) [inline examples/window-app/common/src/ZclCallbacks.cpp:55]: I guess we can do this for now, but really this should be using the _app_ post-attribute-change callback, to trigger app logic, instead of overriding the cluster one.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by ReneJosefsen — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking, given this is adding tests.

**Comment by woody-apple** [comment]
@jmeg-sfy Please rebase and regen zap
