### PR TITLE
Stop using ResolverProxy for resolving node lookups

### LINKED ISSUE #28694: [BUG]  Memory Leak in ResolverProxy
### Reproduction steps

I just finished triaging a memory leak in `ResolverProxy`.

This memory allocation is getting leaked ([Source code link](https://github.com/project-chip/connectedhomeip/blob/3c3e5f52ddb7b73bee4ca3c0d9f4584ddd98dced/src/lib/dnssd/ResolverProxy.h#L89)): 

```c++
    CHIP_ERROR Init(Inet::EndPointManager<Inet::UDPEndPoint> * udpEndPoint = nullptr) override
    {
        ReturnErrorOnFailure(chip::Dnssd::Resolver::Instance().Init(udpEndPoint));
        VerifyOrReturnError(mDelegate == nullptr, CHIP_ERROR_INCORRECT_STATE);
-->     mDelegate = chip::Platform::New<ResolverDelegateProxy>();   <-- // Allocated and never freed.

...
```

This was the call stack of the leaked allocation:

```c++
src/lib/support/CHIPMem-Malloc.cpp: chip::Platform::MemoryAlloc()
src/lib/support/CHIPMem.h: chip::Platform::New<>()
src/lib/dnssd/ResolverProxy.h: chip::Dnssd::ResolverProxy::Init()
src/lib/dnssd/Discovery_ImplPlatform.cpp: chip::Dnssd::DiscoveryImplPlatform::HandleDnssdInit()
src/platform/google/dnssd_manager.cc: chip::Dnssd::ChipDnssdInit()
src/lib/dnssd/Discovery_ImplPlatform.cpp: chip::Dnssd::DiscoveryImplPlatform::InitImpl()
src/lib/dnssd/Discovery_ImplPlatform.h: chip::Dnssd::DiscoveryImplPlatform::Init()
src/lib/dnssd/Discovery_ImplPlatform.h: chip::Dnssd::DiscoveryImplPlatform::Init()
src/controller/CHIPDeviceControllerFactory.cpp: chip::Controller::DeviceControllerFactory::InitSystemState()
src/controller/CHIPDeviceControllerFactory.cpp: chip::Controller::DeviceControllerFactory::Init()
```

Although everything shuts down properly, This call to `mDelegate->Release()` in `ResolverProxy::Shutdown` is not freeing mDelegate as expected, as its ref count is still greater than 1 ([Source code link](https://github.com/project-chip/connectedhomeip/blob/3c3e5f52ddb7b73bee4ca3c0d9f4584ddd98dced/src/lib/dnssd/ResolverProxy.h#L150)):

```c++
    void Shutdown() override
    {
        VerifyOrReturn(mDelegate != nullptr);
        mDelegate->SetOperationalDelegate(nullptr);
        mDelegate->SetCommissioningDelegate(nullptr);
-->     mDelegate->Release(); <-- // Does not free mDelegate (ref count is > 1)
        mDelegate = nullptr;
    }
```

The reason is that `ResolverProxy::ResolveNodeId` obtained an additional ref to it here, and never released it ([Source code link](https://github.com/project-chip/connectedhomeip/blob/3c3e5f52ddb7b73bee4ca3c0d9f4584ddd98dced/src/lib/dnssd/Discovery_ImplPlatform.cpp#L701)):

```c++
CHIP_ERROR ResolverProxy::ResolveNodeId(const PeerId & peerId)
{
    VerifyOrReturnError(mDelegate != nullptr, CHIP_ERROR_INCORRECT_STATE);


    ChipLogProgress(Discovery, "Resolving " ChipLogFormatX64 ":" ChipLogFormatX64 " ...",
                    ChipLogValueX64(peerId.GetCompressedFabricId()), ChipLogValueX64(peerId.GetNodeId()));


    DnssdService service;


    ReturnErrorOnFailure(MakeInstanceName(service.mName, sizeof(service.mName), peerId));
    Platform::CopyString(service.mType, kOperationalServiceName);
    service.mProtocol    = DnssdServiceProtocol::kDnssdProtocolTcp;
    service.mAddressType = Inet::IPAddressType::kAny;


--> mDelegate->Retain(); <-- // Increases the ref-count of mDelegate.


    CHIP_ERROR err = ChipDnssdResolve(&service, Inet::InterfaceId::Null(), HandleNodeIdResolve, mDelegate);
    if (err != CHIP_NO_ERROR)
    {
        mDelegate->Release();
    }
    return err;
}

```

In my specific use-case, it was expected to be released when `ResolverProxy::NodeIdResolutionNoLongerNeeded` is called, but it's clearly not ([Source code link](https://github.com/project-chip/connectedhomeip/blob/3c3e5f52ddb7b73bee4ca3c0d9f4584ddd98dced/src/lib/dnssd/Discovery_ImplPlatform.cpp#L711)):

```c++
void ResolverProxy::NodeIdResolutionNoLongerNeeded(const PeerId & peerId)
{
    char name[Common::kInstanceNameMaxLength + 1];
    ReturnOnFailure(MakeInstanceName(name, sizeof(name), peerId));


    ChipDnssdResolveNoLongerNeeded(name);
}
```

Actually, `DiscoveryImplPlatform` doesn't even propagate the call to `DiscoveryImplPlatform::NodeIdResolutionNoLongerNeeded` to the `ResolverProxy`, which I think it should be, and surrounding functions do this ([Source code link](https://github.com/project-chip/connectedhomeip/blob/3c3e5f52ddb7b73bee4ca3c0d9f4584ddd98dced/src/lib/dnssd/Discovery_ImplPlatform.cpp#L640)).

```c++
CHIP_ERROR DiscoveryImplPlatform::ResolveNodeId(const PeerId & peerId)
{
    ReturnErrorOnFailure(InitImpl());
--> return mResolverProxy.ResolveNodeId(peerId);  <-- // Calls ResolverProxy.
}


void DiscoveryImplPlatform::NodeIdResolutionNoLongerNeeded(const PeerId & peerId)
{
    char name[Common::kInstanceNameMaxLength + 1];
    ReturnOnFailure(MakeInstanceName(name, sizeof(name), peerId));


-->  ChipDnssdResolveNoLongerNeeded(name);  <-- // Does NOT call ResolverProxy.
}


CHIP_ERROR DiscoveryImplPlatform::DiscoverCommissionableNodes(DiscoveryFilter filter)
{
    ReturnErrorOnFailure(InitImpl());
--> return mResolverProxy.DiscoverCommissionableNodes(filter);  <-- // Calls ResolverProxy.
}
```

### Thoughts on a fix

We need to call `ResolverProxy::NodeIdResolutionNoLongerNeeded` from `DiscoveryImplPlatform::NodeIdResolutionNoLongerNeeded`, and `ResolverProxy::NodeIdResolutionNoLongerNeeded` should be calling `mDelegate->Release()` if the specified PeerId is holding a ref.

We'll need a set of PeerIds to keep track of how many times we've retained `mDelegate`, since we don't want to decrease the ref-count if someone calls `ResolverProxy::NodeIdResolutionNoLongerNeeded` with a PeerId that doesn't have an active reference to `mDelegate`.  That risks prematurely freeing `mDelegate` which would lead to a crash.

### Other concerns

It looks like there are a few other calls to `mDelegate->Retain()` in `Discovery_ImplPlatform.cpp` as well, and I don't see many calls to `mDelegate->Release()` so there may be other execution flows that leak the delegate as well.

### Bug prevalence

Whenever the AddressResolve logic is used, and we no longer need to resolve a node.

### GitHub hash of the SDK that was being used

af6cb3a6d7d4cd9a4eb38ec49687260bc5ec96e7

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

Although the hash I reported isn't the latest, I inspected the top-of-tree code, and the issue still exists.  All my permalinks are from the top of tree source.

### PR DESCRIPTION
**Pull request by andy31415**
Fixes #28694 (memory leak because stopping resolution was not implemented).

We currently use AddressResolve to handle node resolution, so a separate singleton resolver proxy should not be needed for handling node resolution.

Actual changes:
  - remove implementation for ResolverProxy::ResolveNodeId
  - replace with inline code for PlatformDnsSd for resolverproxy. Made PlatformDnsSd maintain its own delegate for operational node discovery
  - Updated Avahi linux implementation to support "StopResolution" by kepping track of active resolutions and being able to free up memory outside avahi callbacks
  - Changed shell `Dns.cpp` to use AddressResolver interface instead of ResolverProxy for operational discovery.

## Tested

```
./out/linux-x64-address-resolve-tool-platform-mdns-asan/address-resolve-tool node 1 2
```

validated that node resolution still works when node is advertised (CI should also validate that) and that there are no memory leaks if we stop a resolution that does not find anything (i.e. cancel works and memory is freed up).

## TODO notes

- we may in general want to clean up ResolverProxy usage, especially since it now claims to implement an entire Resolver interface when in fact it does not implement operational node resolution. Maybe interfaces should be split

### CODE REVIEW

**Comment by andy31415** [comment]
@joonhaengHeo this updates Avahi implementation for linux to actually be able to stop browse. This makes it so that test apps that stop will clean up memory for browse. I see webos has a copy of this code, however I did not touch it (unsure what if anything is different in it).

File: src/lib/dnssd/Discovery_ImplPlatform.cpp [hunk 1]
```diff
@@ -633,15 +631,27 @@ bool DiscoveryImplPlatform::IsInitialized()
 
 CHIP_ERROR DiscoveryImplPlatform::ResolveNodeId(const PeerId & peerId)
 {
-    ReturnErrorOnFailure(InitImpl());
-    return mResolverProxy.ResolveNodeId(peerId);
+    // Resolve requests can only be issued once DNSSD is initialized and there is
+    // no caching currently
+    VerifyOrReturnError(mState == State::kInitialized, CHIP_ERROR_INCORRECT_STATE);
+
```
Comment (bzbarsky-apple) [inline src/lib/dnssd/Discovery_ImplPlatform.cpp:637]: We used to error out in the `mOperationalDelegate == nullptr` case (CHIP_ERROR_INCORRECT_STATE).  Should we keep doing that?

File: src/lib/dnssd/ResolverProxy.h [hunk 2]
```diff
@@ -151,13 +151,16 @@ class ResolverProxy : public Resolver
...
     CHIP_ERROR ReconfirmRecord(const char * hostname, Inet::IPAddress address, Inet::InterfaceId interfaceId) override;
 
+    // TODO: ResolverProxy should not be used anymore to implement operational node resolution
+    //       This method still here because Resolver interface requires it
+    CHIP_ERROR ResolveNodeId(const PeerId & peerId) override { return CHIP_ERROR_NOT_IMPLEMENTED; }
+    void NodeIdResolutionNoLongerNeeded(const PeerId & peerId) override {}
+
 private:
     ResolverDelegateProxy * mDelegate                            = nullptr;
     OperationalResolveDelegate * mPreInitOperationalDelegate     = nullptr;
```
Comment (bzbarsky-apple) [inline src/lib/dnssd/ResolverProxy.h:166]: As a followup:

1. We can remove ResolverProxy::SetOperationalDelegate, right?
2. We can remove mPreInitOperationalDelegate.
3. We can remove SetOperationalDelegate from ResolverDelegateProxy.

There might be more cleanups hiding in here too.

**Review by bzbarsky-apple — COMMENTED** [review]
I guess the big question is whether we are OK breaking the `src/lib/shell/commands/Dns.cpp` bit.  Does nothing use that?  Is there something tracking either removing it or fixing it to work?

File: src/lib/dnssd/Discovery_ImplPlatform.cpp (hunk 1 above)
Comment (andy31415) [reply src/lib/dnssd/Discovery_ImplPlatform.cpp:637]: I was thinking no as the delegate is now a global, so callers can/should override them. In practice the operational delegate should always be the global `AddressResolve` instance and should never change.

**Comment by andy31415** [comment]
> I guess the big question is whether we are OK breaking the `src/lib/shell/commands/Dns.cpp` bit. Does nothing use that? Is there something tracking either removing it or fixing it to work?

Pinged @kkasperczyk-no as the original author. I am unsure, but at least tracking does make sense: we should update/fix that file or delete if unused.

**Comment by Damian-Nordic** [comment]
> Pinged @kkasperczyk-no as the original author. I am unsure, but at least tracking does make sense: we should update/fix that file or delete if unused.

We use these shell commands in our internal tests on hardware. Maybe the command should use AddressResolve instead, since this is currently the "public" API for node address resolution?

**Comment by kkasperczyk-no** [comment]
> > Pinged @kkasperczyk-no as the original author. I am unsure, but at least tracking does make sense: we should update/fix that file or delete if unused.
> 
> We use these shell commands in our internal tests on hardware. Maybe the command should use AddressResolve instead, since this is currently the "public" API for node address resolution?

I think that we do not use it anymore in our tests. Nevertheless I can recall it was recommended to use this commands during Matter 1.0 certification tests. I don't remember what test cases they were, however the commands were used to verify that the device is able to properly resolve Matter DNS services. It was also very useful tool for troubleshooting of the problems with DNS and SRP compatibility between OpenThread and other implementations we had in the past.

All in all this is quite useful, but only a debug utility and probably it is currently not used very often. If it would be possible to align it to use the new API, it would be great, but otherwise we should think what brings more value to the project, as I would not like to block potentially good changes to the API.

**Comment by andy31415** [comment]
> I guess the big question is whether we are OK breaking the `src/lib/shell/commands/Dns.cpp` bit. Does nothing use that? Is there something tracking either removing it or fixing it to work?

Replaced that with AddressResolver, resolution should now be possible with Dns.cpp commands.

Difference is that AddressResolver will only return one address instead of many, however that is likely sufficient for debug purposes and checking that dnssd works.

**Comment by andy31415** [comment]
> > Pinged @kkasperczyk-no as the original author. I am unsure, but at least tracking does make sense: we should update/fix that file or delete if unused.
> 
> We use these shell commands in our internal tests on hardware. Maybe the command should use AddressResolve instead, since this is currently the "public" API for node address resolution?

Updated to use AddressResolve.

File: src/lib/shell/commands/Dns.cpp [hunk 3]
```diff
@@ -39,40 +40,38 @@ Shell::Engine sShellDnsBrowseSubcommands;
...
-        if (retryInterval.HasValue())
-            streamer_printf(streamer_get(), "   MRP retry interval (active): %" PRIu32 "ms\r\n", retryInterval.Value());
-
-        streamer_printf(streamer_get(), "   Supports TCP: %s\r\n", nodeData.resolutionData.supportsTcp ? "yes" : "no");
+                        ChipLogValueX64(peerId.GetCompressedFabricId()), ChipLogValueX64(peerId.GetNodeId()));
+
+        char addr_string[Transport::PeerAddress::kMaxToStringSize];
+        result.address.ToString(addr_string);
+
+        streamer_printf(streamer_get(), "Resolve completed: %s\r\n", addr_string);
```
Comment (bzbarsky-apple) [inline src/lib/shell/commands/Dns.cpp:56]: You should be able to log all the addresses (and in fact all the ports, etc, depending on what responses look like) if this code also does:
```
AddressResolve::Resolver::Instance().TryNextResult(Handle());
```
or so after logging this response.  At least for the backends that usefully provide more than one address.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/platform/Linux/DnssdImpl.h [hunk 4]
```diff
@@ -145,12 +148,28 @@ class MdnsAvahi
         AvahiProtocol mTransport;
         AvahiProtocol mAddressType;
         std::string mFullType;
-        uint8_t mAttempts = 0;
+        uint8_t mAttempts                = 0;
+        AvahiServiceResolver * mResolver = nullptr;
+
+        ~ResolveContext()
+        {
+            if (mResolver != nullptr)
```
Comment (yunhanw-google) [inline src/platform/Linux/DnssdImpl.h:156]: after calling avahi_service_resolver_free(mResolver); it is good to set mResolver as nullptr as well

File: src/platform/Linux/DnssdImpl.cpp [hunk 5]
```diff
@@ -988,7 +1047,10 @@ CHIP_ERROR ChipDnssdResolve(DnssdService * browseResult, chip::Inet::InterfaceId
                                             browseResult->mAddressType, Inet::IPAddressType::kAny, interface, callback, context);
 }
 
-void ChipDnssdResolveNoLongerNeeded(const char * instanceName) {}
+void ChipDnssdResolveNoLongerNeeded(const char * instanceName)
+{
+    MdnsAvahi::GetInstance().StopResolve(instanceName);
```
Comment (yunhanw-google) [inline src/platform/Linux/DnssdImpl.cpp:1052]: StopResolve can handle nullptr?

**Review by yunhanw-google — APPROVED** [review]

File: src/platform/Linux/DnssdImpl.h (hunk 4 above)
Comment (andy31415) [reply src/platform/Linux/DnssdImpl.h:156]: Updated, although still unsure because this is in the destructor, so anything accessing it would be accessing invalid memory right away. I guess this would more easily catch invalid access with segfaults.

File: src/platform/Linux/DnssdImpl.cpp (hunk 5 above)
Comment (andy31415) [reply src/platform/Linux/DnssdImpl.cpp:1052]: I see no evidence that ChipDnssdResolveNoLongerNeeded is supposed to allow nullptr.
