### PR TITLE
dac revocation: Default implementation to check if DAC chain is revoked

### LINKED ISSUE #33124: Implement default version of CheckForRevokedDACChain
### Reproduction steps

Implement default version of CheckForRevokedDACChain

### Bug prevalence

NA

### GitHub hash of the SDK that was being used

11838c6616a08cc527771748a884bef809ff0920

### Platform

other

### Platform Version(s)

_No response_

### Type

Common Cluster Logic

### Anything else?

_No response_

### LINKED ISSUE #33652: dac revocation - Unit tests to for default implementation of CheckForRevokedDACChain()
Need some unit test along with #33651

### PR DESCRIPTION
**Pull request by shubhamdp**
Fixes #33124
Fixes #33652

#### Change overview
- Impl for parsing revocation set generated using `credentials/generate-revocation-set.py` using jsoncpp.
- Impl for parsing AKID, serial number, issuer name from cert in hex string, and base64 format
- Added an option to chip-tool to take json file as an input revoked set

#### Testing
- Verified commissioning with lighting-app with/without `--dac-revocation-set-path` option.
- When using `--dac-revocation-set-path`, verified with revoked as well as not revoked test dataset.
- Added unit tests

### CODE REVIEW

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 1]
```diff
@@ -26,10 +26,16 @@
...
 #include <lib/core/Global.h>
+#include <lib/support/Base64.h>
+#include <lib/support/BytesToHex.h>
 #include <lib/support/CodeUtils.h>
 #include <lib/support/ScopedBuffer.h>
 #include <lib/support/Span.h>
 
+#include <fstream>
+#include <json/json.h>
+#include <string.h>
```
Comment (tcarmelveilleux) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:37]: Use `#include <string>` for STL.

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 2]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
...
+
+    if (!parsingSuccessful)
+    {
+        return false;
+    }
+
+    for (const auto & revokedSet : jsonData)
+    {
+        if (strncmp(revokedSet["issuer_name"].asCString(), issuerNameBase64Str.data(), issuerNameBase64Str.size()) == 0 &&
+            strncmp(revokedSet["issuer_subject_key_id"].asCString(), akidHexStr.data(), akidHexStr.size()) == 0)
```
Comment (tcarmelveilleux) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:655]: Don't use strncmp to do these checks. Construct std::string from .data()/.size()

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 3]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
...
+    uint8_t serialNumberBuf[kMaxCertificateSerialNumberLength] = { 0 };
+    MutableByteSpan serialNumber(serialNumberBuf);
+
+    CHIP_ERROR err = ExtractSerialNumberFromX509Cert(certDer, serialNumber);
+    VerifyOrReturnError(err == CHIP_NO_ERROR, err);
+    VerifyOrReturnError(outSerialNumberHexStr.size() > serialNumber.size() * 2, CHIP_ERROR_BUFFER_TOO_SMALL);
+
+    Encoding::HexFlags flags = Encoding::HexFlags::kUppercaseAndNullTerminate;
+    err = BytesToHex(serialNumber.data(), serialNumber.size(), outSerialNumberHexStr.data(), outSerialNumberHexStr.size(), flags);
+    VerifyOrReturnError(err == CHIP_NO_ERROR, err);
```
Comment (tcarmelveilleux) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:697]: Extract hex-ification to a helper, with ByteSpan input and returning an optional<std::string>

**Review by tcarmelveilleux — CHANGES_REQUESTED** [review]
- [ ] Need to introduce an interface for revocation checking and injection of implementation.
- [ ] Need to avoid JSON and files being added at all to common code outside client-provided implementation.
- [ ] Need `CheckForRevokedDACChain` to be able to push exact errors
- [ ] Need unit tests for the additions

File: examples/chip-tool/commands/common/CredentialIssuerCommands.h [hunk 4]
```diff
@@ -62,6 +62,15 @@ class CredentialIssuerCommands
     virtual CHIP_ERROR SetupDeviceAttestation(chip::Controller::SetupParams & setupParams,
                                               const chip::Credentials::AttestationTrustStore * trustStore) = 0;
 
+    /**
+     * @brief
+     *   This function is used to set the path to Device Attestation revocation set JSON file.
+     *
+     * @param[in] path Path to the JSON file containing list of revoked DACs or PAIs.
```
Comment (bzbarsky-apple) [inline examples/chip-tool/commands/common/CredentialIssuerCommands.h:69]: Apparently passing null is allowed?  This needs to be documented, along with what the semantics of passing null are.

File: examples/chip-tool/commands/common/CredentialIssuerCommands.h [hunk 5]
```diff
@@ -62,6 +62,15 @@ class CredentialIssuerCommands
...
+     *                 It can be generated using credentials/generate-revocation-set.py script
+     */
+    virtual void SetupDeviceAttestationRevocationSetPath(const char * path) = 0;
```
Comment (bzbarsky-apple) [inline examples/chip-tool/commands/common/CredentialIssuerCommands.h:72]:
```suggestion
    virtual void SetDeviceAttestationRevocationSetPath(const char * path) = 0;
```

File: examples/chip-tool/commands/example/ExampleCredentialIssuerCommands.h [hunk 6]
```diff
@@ -44,6 +44,17 @@ class ExampleCredentialIssuerCommands : public CredentialIssuerCommands
 
         return CHIP_NO_ERROR;
     }
+
+    void SetupDeviceAttestationRevocationSetPath(const char * path) override
+    {
+        if (path)
+        {
+            // As we know that we are using DefaultDACVerifier, we can downcast from
```
Comment (bzbarsky-apple) [inline examples/chip-tool/commands/example/ExampleCredentialIssuerCommands.h:52]: If we know that, why is `mDacVerifier` not just of type `DefaultDACVerifier`?  Either it can be (and then this cast is not needed), or it can't be, and then this cast is not valid.  I think it's the latter, since nothing says `GetDefaultDACVerifier` in fact returns an instance of `DefaultDACVerifier` right now, and its implementation could easily change to return something else in some cases.

Either way, there should be no cast here.

File: examples/chip-tool/commands/example/ExampleCredentialIssuerCommands.h [hunk 7]
```diff
@@ -44,6 +44,17 @@ class ExampleCredentialIssuerCommands : public CredentialIssuerCommands
 
         return CHIP_NO_ERROR;
     }
+
+    void SetupDeviceAttestationRevocationSetPath(const char * path) override
+    {
+        if (path)
```
Comment (bzbarsky-apple) [inline examples/chip-tool/commands/example/ExampleCredentialIssuerCommands.h:50]: OK, so if path is null then we keep using whatever the previous path used to be?  Again, this all needs to be clearly documented in the API, and then we can have a discussion about what the right behavior is.

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 8]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
...
+//    "type": "revocation_set",
+//    "issuer_subject_key_id": "63540E47F64B1C38D13884A462D16C195D8FFB3C",
+//    "issuer_name": "MD0xJTAjBgNVBAMMHE1hdHRlciBEZXYgUEFJIDB4RkZGMSBubyBQSUQxFDASBgorBgEEAYKifAIBDARGRkYx",
+//    "revoked_serial_numbers": [
+//      "69CDF10DE9E54ED1"
+//    ]
+//  }
+// ]
+//
+bool DefaultDACVerifier::IsEntryExistsInRevocationSet(const CharSpan & akidHexStr, const CharSpan & issuerNameBase64Str,
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:628]:
```suggestion
bool DefaultDACVerifier::IsEntryInRevocationSet(const CharSpan & akidHexStr, const CharSpan & issuerNameBase64Str,
```

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 9]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
...
+    std::string errs;
+
+    bool parsingSuccessful = Json::parseFromStream(readerBuilder, file, &jsonData, &errs);
+
+    // Close the file as it's no longer needed
+    file.close();
+
+    if (!parsingSuccessful)
+    {
+        return false;
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:649]: Please log the errors; otherwise this is a completely inscrutable failure.

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:655]: 💯 

The checks you have here are:

> does `revokedSet["issuer_name"]` start with `issuerNameBase64Str`?

This is not the right check, and we should have tests that would have caught this bug, please.

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 10]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
...
+    }
+
+    for (const auto & revokedSet : jsonData)
+    {
+        if (strncmp(revokedSet["issuer_name"].asCString(), issuerNameBase64Str.data(), issuerNameBase64Str.size()) == 0 &&
+            strncmp(revokedSet["issuer_subject_key_id"].asCString(), akidHexStr.data(), akidHexStr.size()) == 0)
+        {
+            for (const auto & revokedSerialNumber : revokedSet["revoked_serial_numbers"])
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:657]: Consider reversing the sense of the issuer name/subject checks, doing `continue` if either of those does not match, and outdenting.

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 11]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
...
+    return false;
+}
+
+CHIP_ERROR DefaultDACVerifier::GetAKIDHexStr(const ByteSpan & certDer, MutableCharSpan & outAKIDHexStr)
+{
+    uint8_t akidBuf[kAuthorityKeyIdentifierLength];
+    MutableByteSpan akid(akidBuf);
+
+    CHIP_ERROR err = ExtractAKIDFromX509Cert(certDer, akid);
+    VerifyOrReturnError(err == CHIP_NO_ERROR, err);
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:675]:
```suggestion
    ReturnErrorOnFailure(err);
```

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 12]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
...
+    VerifyOrReturnError(outAKIDHexStr.size() > akid.size() * 2, CHIP_ERROR_BUFFER_TOO_SMALL);
+
+    Encoding::HexFlags flags = Encoding::HexFlags::kUppercaseAndNullTerminate;
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:678]: Why are we null-terminating?  We shouldn't need to null-terminate if we are writing into a span, which knows its own length.  And then we can make the length check `>=`, not `>`.

That said, doesn't `BytesToHex` do its own size check?  Why are we doing a separate one?

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 13]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
...
+    err                      = BytesToHex(akid.data(), akid.size(), outAKIDHexStr.data(), outAKIDHexStr.size(), flags);
+    VerifyOrReturnError(err == CHIP_NO_ERROR, err);
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:680]:
```suggestion
    ReturnErrorOnFailure(err);
```

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 14]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
...
+
+    outAKIDHexStr.reduce_size(strlen(outAKIDHexStr.data()));
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:682]: This makes no sense, but does explain why we were null-terminating...

The size must be `akid.size() * 2`, no?

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 15]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
...
+    return CHIP_NO_ERROR;
+}
+
+CHIP_ERROR DefaultDACVerifier::GetSerialNumberHexStr(const ByteSpan & certDer, MutableCharSpan & outSerialNumberHexStr)
+{
+    uint8_t serialNumberBuf[kMaxCertificateSerialNumberLength] = { 0 };
+    MutableByteSpan serialNumber(serialNumberBuf);
+
+    CHIP_ERROR err = ExtractSerialNumberFromX509Cert(certDer, serialNumber);
+    VerifyOrReturnError(err == CHIP_NO_ERROR, err);
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:692]: A bunch of the GetAKIDHexStr comments apply here.

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 16]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
...
+    return CHIP_NO_ERROR;
+}
+
+CHIP_ERROR DefaultDACVerifier::GetIssuerNameBase64Str(const ByteSpan & certDer, MutableCharSpan & outIssuerNameBase64String)
+{
+    uint8_t issuerBuf[kMaxCertificateDistinguishedNameLength] = { 0 };
+    MutableByteSpan issuer(issuerBuf);
+
+    CHIP_ERROR err = ExtractIssuerFromX509Cert(certDer, issuer);
+    VerifyOrReturnError(CHIP_NO_ERROR == err, err);
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:709]: See comments above.

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 17]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
...
+    VerifyOrReturnError(outIssuerNameBase64String.size() > BASE64_ENCODED_LEN(issuer.size()), CHIP_ERROR_BUFFER_TOO_SMALL);
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:710]: Why is this a `>`, not a `>=` check?  I would expect passing a buffer of size `BASE64_ENCODED_LEN(dataToEncode)` to work....

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 18]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
...
+    char issuerNameBuffer[maxIssuerBase64Len]                                = { 0 };
+    char serialNumberHexStrBuffer[2 * kMaxCertificateSerialNumberLength + 1] = { 0 };
+    char akidHexStrBuffer[2 * kAuthorityKeyIdentifierLength + 1]             = { 0 };
+
+    MutableCharSpan issuerName(issuerNameBuffer);
+    MutableCharSpan serialNumber(serialNumberHexStrBuffer);
+    MutableCharSpan akid(akidHexStrBuffer);
+
+    CHIP_ERROR err = GetIssuerNameBase64Str(certDer, issuerName);
+    VerifyOrReturnValue(err == CHIP_NO_ERROR, false);
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:730]: ReturnErrorOnFailure various places here.

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 19]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
...
-    // TODO(#33124): Implement default version of CheckForRevokedDACChain
+    if (mDeviceAttestationRevocationSetPath != nullptr)
+    {
+        if (IsCertificateRevoked(info.dacDerBuffer))
+        {
+            attestationError = AttestationVerificationResult::kDacRevoked;
+        }
+        if (IsCertificateRevoked(info.paiDerBuffer))
+        {
+            attestationError = AttestationVerificationResult::kPaiRevoked;
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:754]: So if both are revoked we consider the PAI being revoked more important than the DAC being revoked, in terms of the errors that get reported?

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp [hunk 20]
```diff
@@ -607,12 +613,147 @@ CHIP_ERROR DefaultDACVerifier::VerifyNodeOperationalCSRInformation(const ByteSpa
     return CHIP_NO_ERROR;
 }
 
+// This method parses the below JSON Scheme
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp:616]: So right now, you can provide a trust store to a DefaultDACVerifier and it will work with that via API, agnostic to how the data is actually stored or gotten.

We should probably do something similar here; there are existing deployments of DefaultDACVerifier that cannot in fact create a file on disk to point it to, so that detail should be hidden behind an API boundary, with some TestSomething class that implements the relevant API and has the JSON thing as an implementation.

The API to that thing should ideally be async, just like the API to the DefaultDACVerifier itself.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp (hunk 19 above)
Comment (shubhamdp) [reply src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp]: Added another error code `kPaiAndDacRevoked` and using that one.

**Comment by shubhamdp** [comment]
@tcarmelveilleux I have address the comments, PTAL for more details below

> * [x]  Need to introduce an interface for revocation checking and injection of implementation.

Added the `DeviceAttestationRevocationDelegate` and methods to inject the implementation into DeviceAttestationVerifier.
> * [x]  Need to avoid JSON and files being added at all to common code outside client-provided implementation.

Not using JSON impl in the DefaultDeviceAttestionVerifier and added TestDACRevocationDelegateImpl.
> * [x]  Need `CheckForRevokedDACChain` to be able to push exact errors

Added another error code if PAI and DAC both are revoked.
> * [x]  Need unit tests for the additions

Added unit tests

**Comment by shubhamdp** [comment]
@bzbarsky-apple I've address the review-comments PTAL!

File: examples/chip-tool/commands/common/CredentialIssuerCommands.h [hunk 21]
```diff
@@ -62,6 +62,17 @@ class CredentialIssuerCommands
     virtual CHIP_ERROR SetupDeviceAttestation(chip::Controller::SetupParams & setupParams,
                                               const chip::Credentials::AttestationTrustStore * trustStore) = 0;
 
+    /**
+     * @brief
+     *   This function is used to set the path to Device Attestation revocation set JSON file.
```
Comment (bzbarsky-apple) [inline examples/chip-tool/commands/common/CredentialIssuerCommands.h:67]:
```suggestion
     *   This function is used to set the path to the Device Attestation revocation set JSON file.
```

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.h [hunk 22]
```diff
@@ -79,6 +79,8 @@ enum class AttestationVerificationResult : uint16_t
 
     kInternalError = 900,
 
+    kPaiAndDacRevoked = 1000,
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DeviceAttestationVerifier.h:82]: I'd expect this to be up near the other Pai/Dac bits, with a similar value.  Not sure whether to put it with the kDac or kPai constants; which of those is the more immediate problem if both are revoked?

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.h [hunk 23]
```diff
@@ -409,13 +413,39 @@ class DeviceAttestationVerifier
...
+
 protected:
     CHIP_ERROR ValidateAttestationSignature(const Crypto::P256PublicKey & pubkey, const ByteSpan & attestationElements,
                                             const ByteSpan & attestationChallenge, const Crypto::P256ECDSASignature & signature);
 
     // Default to support the "development" test key for legacy purposes (since the DefaultDACVerifier)
     // always supported development keys.
     bool mEnableCdTestKeySupport = true;
+
+    DeviceAttestationRevocationDelegate * mRevocationDelegate = nullptr;
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DeviceAttestationVerifier.h:426]: Why is this on the interface here?  Shouldn't it be on whatever class uses DeviceAttestationRevocationDelegate to implement CheckForRevokedDACChain?

I guess the issue is that some consumer (e.g. chip-tool?) just does GetDefaultDACVerifier() and then wants to set this delegate on it. But this part doesn't make sense for other verifier impls....

What should probably happen is that `GetDefaultDACVerifier` grows either an optional argument or a two-argument overload or something.

Comment (shubhamdp) [reply src/credentials/attestation_verifier/DeviceAttestationVerifier.h]: Even I didn't want it here, but wasn't sure where to put it. Thanks for the suggestion. Moved to `DefaultDACVerifier`. and adjusted the bits in chip-tool to set it up accordingly. PTAL

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.h (hunk 22 above)
Comment (shubhamdp) [reply src/credentials/attestation_verifier/DeviceAttestationVerifier.h]: Moved closer to 'kPai` bits, as the name starts with 'kPai` and  revoked PAI is a bigger concern, revoked DAC.

File: examples/chip-tool/commands/common/CHIPCommand.cpp [hunk 24]
```diff
@@ -450,7 +453,14 @@ CHIP_ERROR CHIPCommand::InitializeCommissioner(CommissionerIdentity & identity,
     std::unique_ptr<ChipDeviceCommissioner> commissioner = std::make_unique<ChipDeviceCommissioner>();
     chip::Controller::SetupParams commissionerParams;
 
-    ReturnLogErrorOnFailure(mCredIssuerCmds->SetupDeviceAttestation(commissionerParams, sTrustStore));
+    if (mDacRevocationSetPath.HasValue())
+    {
+        static chip::Credentials::TestDACRevocationDelegateImpl testDacRevocationDelegate;
```
Comment (bzbarsky-apple) [inline examples/chip-tool/commands/common/CHIPCommand.cpp:458]: So in interactive mode, if `mDacRevocationSetPath` has no value this will just keep using the revocation set from last time?  Trying to understand the intended behavior here.

Comment (shubhamdp) [reply examples/chip-tool/commands/common/CHIPCommand.cpp]: Yes that is the intended behaviour here, keeping it similar to trust store path. Also, factored out this code into similar method as trust store path.

should we honour the argument provided in interactive mode? If yes, I'll do it in follow up.

Comment (bzbarsky-apple) [reply examples/chip-tool/commands/common/CHIPCommand.cpp]: This is quite different from the trust store path behavior.  The behavior for trust store path is:

1. The first time a command is executed in interactive mode with a trust store path argument, create a FileAttestationTrustStore for that path.
2. Any time after that a command is executed with a trust store path argument, use that FileAttestationTrustStore (with the old path, ignoring the new value).
3. Any command executed without a trust store path argument uses `Credentials::GetTestAttestationTrustStore()`. 
4. Some complications around the env var bits, but let's ignore those.

The behavior that is being implemented here, on the other hand is:

1. The first time a command is executed in interactive mode with a trust store path argument, create a TestDACRevocationDelegateImpl for that path.
2. Any time after that a command is executed, use that same TestDACRevocationDelegateImpl no matter what the revocation path for the command was or whether one was present.

Neither behavior is terribly sane, honestly, but they are also different and I am not sure whether the behavior differences are intentional or not.

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.h [hunk 25]
```diff
@@ -47,6 +47,7 @@ enum class AttestationVerificationResult : uint16_t
     kPaiVendorIdMismatch  = 205,
     kPaiAuthorityNotFound = 206,
     kPaiMissing           = 207,
+    kPaiAndDacRevoked     = 208,
```
Comment (tcarmelveilleux) [inline src/credentials/attestation_verifier/DeviceAttestationVerifier.h:50]: Have a different code for PAI revoked, and DAC revoked, in the correct ranges (200 for PAI, 300 for DAC)

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.h [hunk 26]
```diff
@@ -259,6 +260,8 @@ class ArrayAttestationTrustStore : public AttestationTrustStore
     const size_t mNumCerts;
 };
 
+class DeviceAttestationRevocationDelegate;
```
Comment (tcarmelveilleux) [inline src/credentials/attestation_verifier/DeviceAttestationVerifier.h:263]: This would not be needed if DeviceAttestationRevocationDelegate was a subclass of DeviceAttestationVerifier

File: src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp [hunk 27]
```diff
@@ -0,0 +1,204 @@
...
+    mDeviceAttestationRevocationSetPath = path;
+    return CHIP_NO_ERROR;
+}
+
+// This method parses the below JSON Scheme
+// [
+//  {
+//    "type": "revocation_set",
+//    "issuer_subject_key_id": "63540E47F64B1C38D13884A462D16C195D8FFB3C",
+//    "issuer_name": "MD0xJTAjBgNVBAMMHE1hdHRlciBEZXYgUEFJIDB4RkZGMSBubyBQSUQxFDASBgorBgEEAYKifAIBDARGRkYx",
```
Comment (tcarmelveilleux) [inline src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp:55]: What constitutes the issuer name? Which bytes?

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.h (hunk 25 above)
Comment (bzbarsky-apple) [reply src/credentials/attestation_verifier/DeviceAttestationVerifier.h:50]: Those already exist.  This is the code for "they are both revoked".

File: examples/chip-tool/commands/common/CHIPCommand.cpp (hunk 24 above)
Comment (shubhamdp) [reply examples/chip-tool/commands/common/CHIPCommand.cpp]: Thanks for the explanation. Yes, they are not exactly similar. May be once we have default revocation set built up, I can align the behaviour to attestation trust store. I have added the comment in the code, about how it behaves. Also raised #34434

File: examples/chip-tool/commands/common/CHIPCommand.h [hunk 28]
```diff
@@ -222,11 +224,16 @@ class CHIPCommand : public Command
...
     chip::Optional<bool> mUseMaxSizedCerts;
     chip::Optional<bool> mOnlyAllowTrustedCdKeys;
+    chip::Optional<char *> mDacRevocationSetPath;
 
     // Cached trust store so commands other than the original startup command
     // can spin up commissioners as needed.
     static const chip::Credentials::AttestationTrustStore * sTrustStore;
 
+    // Cached DAC revocation delegate, this can be set using "--dac-revocation-set-path" argument
+    // Once set this will be used by all commands.
```
Comment (bzbarsky-apple) [inline examples/chip-tool/commands/common/CHIPCommand.h:234]: This information should be in the AddArgument help message, no?  People should not have to read the source to find out how arguments behave.

**Review by bzbarsky-apple — APPROVED** [review]

File: examples/chip-tool/commands/common/CHIPCommand.h (hunk 28 above)
Comment (shubhamdp) [reply examples/chip-tool/commands/common/CHIPCommand.h:236]: Added it to the argument help!

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.h (hunk 26 above)
Comment (shubhamdp) [reply src/credentials/attestation_verifier/DeviceAttestationVerifier.h]: Logged an issue to make it a subclass, will do it in follow-up https://github.com/project-chip/connectedhomeip/issues/34495

**Comment by dhrishi** [comment]
@tcarmelveilleux @andy31415 Can you please review and approve this if it looks okay? We are hoping that this gets merged before the 1.4.TE2 deadline

File: src/credentials/BUILD.gn [hunk 29]
```diff
@@ -157,6 +158,8 @@ static_library("default_attestation_verifier") {
     "attestation_verifier/DefaultDeviceAttestationVerifier.cpp",
     "attestation_verifier/DefaultDeviceAttestationVerifier.h",
     "attestation_verifier/DeviceAttestationDelegate.h",
+    "attestation_verifier/TestDACRevocationDelegateImpl.cpp",
+    "attestation_verifier/TestDACRevocationDelegateImpl.h",
```
Comment (tcarmelveilleux) [inline src/credentials/BUILD.gn:162]: Remove these files from here. and the `jsoncpp_root` dependency in default_attestation_verifier

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.h [hunk 30]
```diff
@@ -57,7 +57,11 @@ class CsaCdKeysTrustStore : public WellKnownKeysTrustStore
 class DefaultDACVerifier : public DeviceAttestationVerifier
 {
 public:
-    DefaultDACVerifier(const AttestationTrustStore * paaRootStore) : mAttestationTrustStore(paaRootStore) {}
+    DefaultDACVerifier(const AttestationTrustStore * paaRootStore,
+                       DeviceAttestationRevocationDelegate * revocationDelegate = nullptr) :
```
Comment (tcarmelveilleux) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.h:61]: Instead of having a default parameter, just add a second constructor with both arguments. This will keep backwards compatibility.

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.h [hunk 31]
```diff
@@ -84,6 +88,7 @@ class DefaultDACVerifier : public DeviceAttestationVerifier
 
     CsaCdKeysTrustStore mCdKeysTrustStore;
     const AttestationTrustStore * mAttestationTrustStore;
+    DeviceAttestationRevocationDelegate * mRevocationDelegate = nullptr;
```
Comment (tcarmelveilleux) [inline src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.h:91]: Suggest having a setter for the revocation delegate.

File: src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp [hunk 32]
```diff
@@ -0,0 +1,205 @@
...
+CHIP_ERROR TestDACRevocationDelegateImpl::GetIssuerNameBase64Str(const ByteSpan & certDer,
+                                                                 MutableCharSpan & outIssuerNameBase64String)
+{
+    uint8_t issuerBuf[kMaxCertificateDistinguishedNameLength] = { 0 };
+    MutableByteSpan issuer(issuerBuf);
+
+    ReturnErrorOnFailure(ExtractIssuerFromX509Cert(certDer, issuer));
+    VerifyOrReturnError(outIssuerNameBase64String.size() >= BASE64_ENCODED_LEN(issuer.size()), CHIP_ERROR_BUFFER_TOO_SMALL);
+
+    uint32_t encodedLen = Base64Encode32(issuer.data(), static_cast<uint32_t>(issuer.size()), outIssuerNameBase64String.data());
```
Comment (tcarmelveilleux) [inline src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp:142]: This can be simply `Base64Encode`.  I don't know what the `32` suffix is about.

File: src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp [hunk 33]
```diff
@@ -0,0 +1,205 @@
...
+    MutableCharSpan akid(akidHexStrBuffer);
+
+    VerifyOrReturnValue(CHIP_NO_ERROR == GetIssuerNameBase64Str(certDer, issuerName), false);
+    ChipLogDetail(NotSpecified, "Issuer: %.*s", static_cast<int>(issuerName.size()), issuerName.data());
+
+    VerifyOrReturnValue(CHIP_NO_ERROR == GetSerialNumberHexStr(certDer, serialNumber), false);
+    ChipLogDetail(NotSpecified, "Serial Number: %.*s", static_cast<int>(serialNumber.size()), serialNumber.data());
+
+    VerifyOrReturnValue(CHIP_NO_ERROR == GetAKIDHexStr(certDer, akid), false);
+    ChipLogDetail(NotSpecified, "AKID: %.*s", static_cast<int>(akid.size()), akid.data());
```
Comment (tcarmelveilleux) [inline src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp:166]: Add a TODO (and create associated issue) to cross-validate the CRLSignerCertificate and CRLSignerDelegator per spec:

```
. If a matching `RevocationSet` is found, determined if `serialNumber` is a member of the set.
    .. If the entity type whose revocation status is being verified is a PAI, then the subject PAI's issuer (a PAA) SHALL fulfill one of the following two cases, otherwise return immediately:
      ... The Subject and Subject Key of the PAI certificate's issuer matches exactly the CRLSignerCertificate's subject (i.e. the CRLSignerCertificate is a PAA).
      ... The Subject and Subject Key of the PAI certificate's issuer matches exactly the PAA which is the issuer of the CRLSignerCertificate (i.e. the CRLSignerCertificate is a CRL signer delegated by a PAA).
    .. If the entity type whose revocation status is being verified is a DAC, then:
      ... If the `CRLSignerDelegator` is present, then the subject DAC's issuer (a PAI) SHALL match the `CRLSignerDelegator` in both Subject Key and Subject, otherwise return immediately.
      ... If the `CRLSignerDelegator` is absent, then the subject DAC's issuer (a PAI) SHALL match the `CRLSignerCertificate` in both Subject Key and Subject, otherwise return immediately.
```

Those checks are not currently do, and MUST be done later once this is supported in revocation set construction.

File: src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp [hunk 34]
```diff
@@ -0,0 +1,205 @@
...
+    return IsEntryInRevocationSet(akid, issuerName, serialNumber);
+}
+
+void TestDACRevocationDelegateImpl::CheckForRevokedDACChain(
+    const DeviceAttestationVerifier::AttestationInfo & info,
+    Callback::Callback<DeviceAttestationVerifier::OnAttestationInformationVerification> * onCompletion)
+{
+    AttestationVerificationResult attestationError = AttestationVerificationResult::kSuccess;
+
+    if (mDeviceAttestationRevocationSetPath != nullptr)
```
Comment (tcarmelveilleux) [inline src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp:177]: Suggest an early exit with call of the callback if `mDeviceAttestationRevocationSetPath == nullptr`, to de-nest this next part.

File: src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp [hunk 35]
```diff
@@ -0,0 +1,205 @@
...
+    {
+        ChipLogDetail(NotSpecified, "Checking for revoked DAC in %s", mDeviceAttestationRevocationSetPath);
```
Comment (tcarmelveilleux) [inline src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp:179]: Suggeste using std::string for the mDeviceAttestationRevocationSetPath

File: src/credentials/tests/TestDeviceAttestationCredentials.cpp
Comment (tcarmelveilleux) [inline src/credentials/tests/TestDeviceAttestationCredentials.cpp:1]: The test needs to now have a dependency on `:test_dac_revocation_delegate` target.

File: examples/chip-tool/commands/common/CredentialIssuerCommands.h [hunk 36]
```diff
@@ -57,10 +57,14 @@ class CredentialIssuerCommands
...
      *
+     * @param[in] revocationDelegate A pointer to the Device Attestation Revocation Delegate for checking revoked DACs and PAIs.
+     *                               Default is nullptr.
+     *
      * @return CHIP_ERROR CHIP_NO_ERROR on success, or corresponding error code.
      */
-    virtual CHIP_ERROR SetupDeviceAttestation(chip::Controller::SetupParams & setupParams,
-                                              const chip::Credentials::AttestationTrustStore * trustStore) = 0;
+    virtual CHIP_ERROR
+    SetupDeviceAttestation(chip::Controller::SetupParams & setupParams, const chip::Credentials::AttestationTrustStore * trustStore,
```
Comment (tcarmelveilleux) [inline examples/chip-tool/commands/common/CredentialIssuerCommands.h:66]: Please do not use default params for this, just require the value to always be passed.

**Review by tcarmelveilleux — APPROVED** [review]

File: examples/chip-tool/commands/common/CredentialIssuerCommands.h (hunk 36 above)
Comment (shubhamdp) [reply examples/chip-tool/commands/common/CredentialIssuerCommands.h]: not using the default value.

File: src/credentials/BUILD.gn (hunk 29 above)
Comment (shubhamdp) [reply src/credentials/BUILD.gn]: Thanks for pointing it out, removed. Thats why tests were passing!

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.h (hunk 30 above)
Comment (shubhamdp) [reply src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.h]: Added one more constructor.

File: src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.h (hunk 31 above)
Comment (shubhamdp) [reply src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.h:96]: Added the setter API

File: src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp [hunk 37]
```diff
@@ -0,0 +1,205 @@
...
+CHIP_ERROR BytesToHexStr(const ByteSpan & bytes, MutableCharSpan & outHexStr)
+{
+    Encoding::HexFlags flags = Encoding::HexFlags::kUppercase;
+    ReturnErrorOnFailure(BytesToHex(bytes.data(), bytes.size(), outHexStr.data(), outHexStr.size(), flags));
+    outHexStr.reduce_size(2 * bytes.size());
+    return CHIP_NO_ERROR;
+}
+} // anonymous namespace
+
+CHIP_ERROR TestDACRevocationDelegateImpl::SetDeviceAttestationRevocationSetPath(const char * path)
```
[the remark this answers is not in the document]
Comment (shubhamdp) [reply src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp]: Using `std::string_view` for this.

File: src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp (hunk 32 above)
Comment (shubhamdp) [reply src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp]: 32 suffix returns the 32 bit value. `Base64Encode` returns 16 bit value. Using `Base64Encode`.

File: src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp (hunk 33 above)
Comment (shubhamdp) [reply src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp:172]: Added a TODO and an issue: #34587

File: src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp (hunk 34 above)
Comment (shubhamdp) [reply src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp]: Since we have to make a call at the end with attestation result, that why it was like this. Inverted the check and returning early.

File: src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp (hunk 35 above)
Comment (shubhamdp) [reply src/credentials/attestation_verifier/TestDACRevocationDelegateImpl.cpp]: Using earlier suggestion, `std::string_view`

File: src/credentials/tests/TestDeviceAttestationCredentials.cpp
Comment (shubhamdp) [reply src/credentials/tests/TestDeviceAttestationCredentials.cpp:1]: Added!

File: src/credentials/tests/TestDeviceAttestationCredentials.cpp [hunk 38]
```diff
@@ -413,3 +416,158 @@ TEST_F(TestDeviceAttestationCredentials, TestAttestationTrustStore)
...
 }
+
+static void WriteTestRevokedData(const char * jsonData, const char * fileName)
+{
+    // write data to /tmp/sample_revoked_set.json using fstream APIs
+    std::ofstream file;
+    file.open(fileName, std::ofstream::out | std::ofstream::trunc);
+    file << jsonData;
+    file.close();
+}
```
[the remark this answers is not in the document]
Comment (shubhamdp) [reply src/credentials/tests/TestDeviceAttestationCredentials.cpp]: Added TODO for now, will fix in follow-up #34588

**Comment by tcarmelveilleux** [comment]
Broke python tests on HEAD
