### PR TITLE
Stop assuming that we can do a localhost write within 0.5s in Darwin test.

### LINKED ISSUE #39114: [Darwin] Random failure in MTRDeviceTests test017_TestMTRDeviceBasics
### Reproduction steps

https://github.com/project-chip/connectedhomeip/actions/runs/15169428894/job/42660643465

```
2025-05-21T20:42:21.4967550Z /Users/runner/work/connectedhomeip/connectedhomeip/src/darwin/Framework/CHIPTests/MTRDeviceTests.m:1637: error: -[MTRDeviceTests test017_TestMTRDeviceBasics] : Failed due to expectation fulfilled in incorrect order: requires 'Expected value reported', actually fulfilled 'waiting for a value for an attribute that does not exist should time out'.
```

### Platform

darwin

### Platform Version(s)

_No response_

### Type

CI tested

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
The tests lose timeslice for longer than that sometimes.

Fixes https://github.com/project-chip/connectedhomeip/issues/39114

#### Testing

Test changes only.

### CODE REVIEW

**Review by tcarmelveilleux — APPROVED** [review]

File: src/darwin/Framework/CHIPTests/MTRDeviceTests.m [hunk 1]
```diff
@@ -1647,7 +1647,11 @@ - (void)test017_TestMTRDeviceBasics
 
     // expected value interval is 20s but expect it get reverted immediately as the write fails because it's writing to a
     // nonexistent attribute
-    [self waitForExpectations:@[ expectedValueReportedExpectation, expectedValueRemovedExpectation, nonexistentAttributeValueWaitExpectation ] timeout:5 enforceOrder:YES];
+    [self waitForExpectations:@[ expectedValueReportedExpectation, expectedValueRemovedExpectation ] timeout:5 enforceOrder:YES];
+
+    // Don't enforce order between the attribute value waiter and the expected value expectations
+    // the expected values are driven off an async process that // can race the waiter.
```
Comment (kiel-apple) [inline src/darwin/Framework/CHIPTests/MTRDeviceTests.m:1653]:
```suggestion
    // the expected values are driven off an async process that 
    // can race the waiter.
```

**Review by kiel-apple — APPROVED** [review]
