### PR TITLE
Fix timer cancellation to be reliable in LayerImplSelect.

### LINKED ISSUE #19387: Canceling timers does not work reliably in the LayerImplSelect implementation
#### Problem
When we process timers, we grab a batch out of the list before we start calling them, and now the timers in that batch cannot be canceled.  This can lead to use-after-free.

 #### Proposed Solution
Either stop doing the batch thing and process timers one by one (maybe with a cap on how far down the list we go), or make the batch a member so that canceling can remove from the batch too.  Discussion on Slack tended toward the former solution.

We should also consider making sure that the Select and FreeRTOS implementations are the same, so our CI tells us something about the FreeRTOS case.

@kpschoedel

### LINKED ISSUE #22160: DMalloc detection of free space overwrite during TestRead
#### Problem
 
 Two instances for this at least:
 
 https://github.com/project-chip/connectedhomeip/runs/8005304886?check_suite_focus=true 
 https://github.com/project-chip/connectedhomeip/runs/7984389882?check_suite_focus=true 
 
 Log says:
 
 ```
 ...
 [1661296765.557679][75818:75818] CHIP:EM: Retransmitting MessageCounter:128264913 on exchange 47182i Send Cnt 1
[1661296765.561911][75818:75818] CHIP:IN: Sending encrypted msg 0x7fc57a2058d0 with MessageCounter:128264913 to 0x0000000011223344 (2) at monotonic time: 000000000019EB6C msec
 [1661296765.570471][75818:75818] CHIP:DMG: Unblock report hold after min 57311 seconds
debug-malloc library: dumping program, fatal error
   Error: free space has been overwritten (err 67)
Aborted (core dumped)
INF Test 1/1: [FAIL] TestRead
```

I am unclear where `57311` seconds come from (seems like an abnormally large seconds count) however timestamps do not seem to point at a large thread block either. Unfortunately TestRead in general is very slow to run and with a lot of logs, making it hard to debug.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
To minimize risk, the changes here keep the "grab all the timers we
should fire, then fire them" setup instead of switching to the "fire
the timers one at a time" approach LayerImplFreeRTOS uses.

The fix consists of the following parts:

1) Store the list of timers to fire in a member, so we can cancel things from
   that list as needed.
2) To avoid canceling things scheduled by ScheduleWork, remove the CancelTimer
   call in ScheduleWork.  This does mean we now allow multiple timers for the
   same callback+appState in the timer list, if they were created by
   ScheduleWork, but that should be OK, since the only reason that pair needs to
   be unique is to allow cancellation and we never want to cancel the things
   ScheduleWork schedules.  As a followup we should stop using the timer list
   for ScheduleWork altogether and use ScheduleLambda like LayerImplFreeRTOS
   does, but that involves fixing the unit tests that call ScheduleWork without
   actually running the platfor manager event loop and expect it to work
   somehow.

TestRead was failing the sanity assert for not losing track of timers
to fire, because it was spinning a nested event loop.  The changes to
that test stop it from doing that.

Fixes https://github.com/project-chip/connectedhomeip/issues/19387
Fixes https://github.com/project-chip/connectedhomeip/issues/22160

#### Problem
Timer cancellation sometimes fails, leading to crashes.

#### Change overview
Fix timer cancellation to be reliable.

#### Testing
New unit tests added for canceling timers and ScheduleWork not canceling a previous ScheduleWork.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
Accepted on master: high value change, fixing potentially use after free (classes do not expect a timer to be fired after explicitly calling CancelTimer on it)

**Comment by bzbarsky-apple** [comment]
>  As a followup we should stop using the timer list for ScheduleWork altogether and use ScheduleLambda like LayerImplFreeRTOS does

https://github.com/project-chip/connectedhomeip/issues/22377

File: src/controller/tests/data_model/TestRead.cpp [hunk 1]
```diff
@@ -2522,40 +2530,50 @@ void TestReadInteraction::SubscribeThenReadHelper(nlTestSuite * apSuite, TestCon
...
     NL_TEST_ASSERT(apSuite, numSuccessCalls == aSubscribeCount);
     NL_TEST_ASSERT(apSuite, numSubscriptionEstablishedCalls == aSubscribeCount);
+    NL_TEST_ASSERT(apSuite, numReadSuccessCalls == aReadCount);
+    NL_TEST_ASSERT(apSuite, numReadFailureCalls == 0);
 }
 
-void TestReadInteraction::MultipleReadHelper(nlTestSuite * apSuite, TestContext & aCtx, size_t aReadCount)
+// The guts of MultipleReadHelper which take references to the success/failure
+// counts to modify and assume the consumer will be spinning the event loop.
+void TestReadInteraction::MultipleReadHelperGuts(nlTestSuite * apSuite, TestContext & aCtx, size_t aReadCount,
```
Comment (tcarmelveilleux) [inline src/controller/tests/data_model/TestRead.cpp:2539]: HelperCommon/HelperInternal are a more usual name than the biological innards reference :)

File: src/system/SystemLayerImplSelect.h [hunk 2]
```diff
@@ -101,6 +101,9 @@ class LayerImplSelect : public LayerSocketsLoop
 
     TimerPool<TimerList::Node> mTimerPool;
     TimerList mTimerList;
+    // List of expired times being processed right now.  Stored in a member so
```
Comment (tcarmelveilleux) [inline src/system/SystemLayerImplSelect.h:104]:
```suggestion
    // List of expired timers being processed right now.  Stored in a member so
```

File: src/system/SystemLayerImplSelect.cpp [hunk 3]
```diff
@@ -170,6 +170,10 @@ void LayerImplSelect::CancelTimer(TimerCompleteCallback onComplete, void * appSt
     VerifyOrReturn(mLayerState.IsInitialized());
 
     TimerList::Node * timer = mTimerList.Remove(onComplete, appState);
+    if (timer == nullptr)
```
Comment (tcarmelveilleux) [inline src/system/SystemLayerImplSelect.cpp:173]: Please document this very very subtle nullptr check here that removes from a different pool. Arguably it's one of the biggest parts of this PR

**Review by tcarmelveilleux — APPROVED** [review]

File: src/controller/tests/data_model/TestRead.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/controller/tests/data_model/TestRead.cpp:2539]: Will do HelperInternal.

File: src/system/SystemLayerImplSelect.cpp (hunk 3 above)
Comment (bzbarsky-apple) [reply src/system/SystemLayerImplSelect.cpp:173]: Will do.

**Review by tcarmelveilleux — APPROVED** [review]

**Comment by msandstedt** [comment]
> To minimize risk, the changes here keep the "grab all the timers we
should fire, then fire them" setup instead of switching to the "fire
the timers one at a time" approach LayerImplFreeRTOS uses.

How do we reckon this is less risky?  The "grab all the timers we should fire, then fire them" was too clever by half and caused the problem in the first place.  Isn't simple, but definitely correct, what we want for a scheduler?

**Comment by bzbarsky-apple** [comment]
> How do we reckon this is less risky? 

Just in terms of the differences in behavior from what we have been testing so far....

>  Isn't simple, but definitely correct, what we want for a scheduler?

Yes, it is.  But to get to "correct" we would need to fix https://github.com/project-chip/connectedhomeip/issues/22377 somehow and stop using timers for ScheduleWork and them we might have a chance of "correct"....

The real question here is not "what is correct?" but "what can we get done in the next < 2 work weeks?"

**Comment by bzbarsky-apple** [comment]
It looks like something is going wrong with testSystemLayer on ESP32. Looking into that.

**Comment by msandstedt** [comment]
> > How do we reckon this is less risky?
> 
> Just in terms of the differences in behavior from what we have been testing so far....
> 
> > Isn't simple, but definitely correct, what we want for a scheduler?
> 
> Yes, it is. But to get to "correct" we would need to fix #22377 somehow and stop using timers for ScheduleWork and them we might have a chance of "correct"....
> 
> The real question here is not "what is correct?" but "what can we get done in the next < 2 work weeks?"

OK, fair enough.
