### PR TITLE
[ESP32] Fixed crash on commissioning into a second fabric

### LINKED ISSUE #17056: m5stack panics when trying to commission it into a second fabric
#### Problem
<details>
<summary>I am getting an assertion failure and panic with this stack:</summary>

```
I (87207) chip[SVR]: Commissioning completed successfully
I (87217) chip[DIS]: Updating services using commissioning mode 0
I (87227) chip[DIS]: CHIP minimal mDNS started advertising.
I (87247) chip[DIS]: Advertise operational node 53ECC075F13C7B50-00000000000000AA
I (87247) chip[DIS]: CHIP minimal mDNS configured as 'Operational device'.
I (87267) chip[DIS]: mDNS service published: _matter._tcp
I (87267) chip[DIS]: Advertise operational node 62FE85D752FAB7CF-0000000000000003
I (87277) chip[DIS]: CHIP minimal mDNS configured as 'Operational device'.
I (87287) chip[DIS]: mDNS service published: _matter._tcp
I (87297) app-devicecallbacks: Commissioning complete

assert failed: spinlock_acquire spinlock.h:123 ((result == SPINLOCK_FREE) == (lock->count == 0))


Backtrace:0x40081e2a:0x3ffe73300x400923ad:0x3ffe7350 0x40098bc1:0x3ffe7370 0x40095809:0x3ffe7490 0x4009330d:0x3ffe74b0 0x40093474:0x3ffe74f0 0x40108acd:0x3ffe7510 0x401020bc:0x3ffe7530 0x401020d3:0x3ffe7550 0x40101dc3:0x3ffe7570 0x4010174f:0x3ffe7590 0x400ee852:0x3ffe75b0 0x401c3187:0x3ffe75d0 0x401c54f5:0x3ffe75f0 0x40136ded:0x3ffe7610 0x401370a2:0x3ffe7630 0x401370c9:0x3ffe76a0 0x40095635:0x3ffe76c0 
0x40081e2a: panic_abort at /Users/bzbarsky/tools/esp-idf/components/esp_system/panic.c:402

0x400923ad: esp_system_abort at /Users/bzbarsky/tools/esp-idf/components/esp_system/esp_system.c:121

0x40098bc1: __assert_func at /Users/bzbarsky/tools/esp-idf/components/newlib/assert.c:85

0x40095809: spinlock_acquire at /Users/bzbarsky/tools/esp-idf/components/esp_hw_support/include/soc/spinlock.h:123
 (inlined by) xPortEnterCriticalTimeout at /Users/bzbarsky/tools/esp-idf/components/freertos/port/xtensa/port.c:288

0x4009330d: vPortEnterCritical at /Users/bzbarsky/tools/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578
 (inlined by) xQueueSemaphoreTake at /Users/bzbarsky/tools/esp-idf/components/freertos/queue.c:1563

0x40093474: xQueueTakeMutexRecursive at /Users/bzbarsky/tools/esp-idf/components/freertos/queue.c:731

0x40108acd: npl_freertos_mutex_pend at /Users/bzbarsky/tools/esp-idf/components/bt/host/nimble/nimble/porting/npl/freertos/src/npl_os_freertos.c:194

0x401020bc: ble_npl_mutex_pend at /Users/bzbarsky/tools/esp-idf/components/bt/host/nimble/nimble/porting/npl/freertos/include/nimble/nimble_npl_os.h:176
 (inlined by) ble_hs_lock_nested at /Users/bzbarsky/tools/esp-idf/components/bt/host/nimble/nimble/nimble/host/src/ble_hs.c:165

0x401020d3: ble_hs_lock at /Users/bzbarsky/tools/esp-idf/components/bt/host/nimble/nimble/nimble/host/src/ble_hs.c:210

0x40101dc3: ble_hs_stop at /Users/bzbarsky/tools/esp-idf/components/bt/host/nimble/nimble/nimble/host/src/ble_hs_stop.c:225

0x4010174f: nimble_port_stop at /Users/bzbarsky/tools/esp-idf/components/bt/host/nimble/nimble/porting/nimble/src/nimble_port.c:107

0x400ee852: DeviceCallbacks::DeviceEventCallback(chip::DeviceLayer::ChipDeviceEvent const*, int) at /Users/bzbarsky/connectedhomeip/examples/all-clusters-app/esp32/main/DeviceCallbacks.cpp:123 (discriminator 8)

0x401c3187: chip::DeviceManager::CHIPDeviceManager::CommonDeviceEventHandler(chip::DeviceLayer::ChipDeviceEvent const*, int) at /Users/bzbarsky/connectedhomeip/examples/all-clusters-app/esp32/main/CHIPDeviceManager.cpp:50

0x401c54f5: chip::DeviceLayer::Internal::GenericPlatformManagerImpl<chip::DeviceLayer::PlatformManagerImpl>::DispatchEventToApplication(chip::DeviceLayer::ChipDeviceEvent const*) at /Users/bzbarsky/connectedhomeip/examples/all-clusters-app/esp32/build/esp-idf/chip/../../../../../../config/esp32/third_party/connectedhomeip/src/include/platform/internal/GenericPlatformManagerImpl.ipp:308 (discriminator 2)

0x40136ded: chip::DeviceLayer::Internal::GenericPlatformManagerImpl<chip::DeviceLayer::PlatformManagerImpl>::_DispatchEvent(chip::DeviceLayer::ChipDeviceEvent const*) at /Users/bzbarsky/connectedhomeip/examples/all-clusters-app/esp32/build/esp-idf/chip/../../../../../../config/esp32/third_party/connectedhomeip/src/include/platform/internal/GenericPlatformManagerImpl.ipp:273

0x401370a2: chip::DeviceLayer::PlatformManager::DispatchEvent(chip::DeviceLayer::ChipDeviceEvent const*) at /Users/bzbarsky/connectedhomeip/examples/all-clusters-app/esp32/build/esp-idf/chip/../../../../../../config/esp32/third_party/connectedhomeip/src/include/platform/PlatformManager.h:442
 (inlined by) chip::DeviceLayer::Internal::GenericPlatformManagerImpl_FreeRTOS<chip::DeviceLayer::PlatformManagerImpl>::_RunEventLoop() at /Users/bzbarsky/connectedhomeip/examples/all-clusters-app/esp32/build/esp-idf/chip/../../../../../../config/esp32/third_party/connectedhomeip/src/include/platform/internal/GenericPlatformManagerImpl_FreeRTOS.ipp:216

0x401370c9: chip::DeviceLayer::PlatformManager::RunEventLoop() at /Users/bzbarsky/connectedhomeip/examples/all-clusters-app/esp32/build/esp-idf/chip/../../../../../../config/esp32/third_party/connectedhomeip/src/include/platform/PlatformManager.h:365
 (inlined by) chip::DeviceLayer::Internal::GenericPlatformManagerImpl_FreeRTOS<chip::DeviceLayer::PlatformManagerImpl>::EventLoopTaskMain(void*) at /Users/bzbarsky/connectedhomeip/examples/all-clusters-app/esp32/build/esp-idf/chip/../../../../../../config/esp32/third_party/connectedhomeip/src/include/platform/internal/GenericPlatformManagerImpl_FreeRTOS.ipp:241

0x40095635: vPortTaskWrapper at /Users/bzbarsky/tools/esp-idf/components/freertos/port/xtensa/port.c:131
```

</details>

when I do the following steps:
1. Flash Matter rev 7ab6653ec47bf0e45ec4307b43f5189cc326cca9 on an m5stack.
2. Install iOS CHIPTool from that same rev on two different iPhones.
3. Scan the QR code for the m5stack on iPhone 1, commission it.
4. Go into the "Enable Pairing" screen on iPhone 1 and tap the "Open Pairing Window" button.
5. On iPhone 2, go into the "QRCode scanner" screen, type the manual code that iPhone 1 showed into the textfield, and tap "Go".

Once the m5stack gets through commissioning it panics.

 #### Proposed Solution
The specific code running here in `examples/all-clusters-app/esp32/main/DeviceCallbacks.cpp` in the `DeviceCallbacks::DeviceEventCallback` function looks like this:
```
    case DeviceEventType::kCommissioningComplete: {
        ESP_LOGI(TAG, "Commissioning complete");
#if CONFIG_BT_NIMBLE_ENABLED && CONFIG_DEINIT_BLE_ON_COMMISSIONING_COMPLETE
        int ret = nimble_port_stop();
        if (ret == 0)
        {
``` 
and the stack passes through that `int ret = nimble_port_stop();` line.

@dhrishi

### PR DESCRIPTION
**Pull request by jadhavrohit924**
#### Problem
* Fix crash on commissioning into a second fabric
* Fixes #17056

#### Change overview
Fix crash on commissioning into a second fabric

#### Testing
Manually tested.

### CODE REVIEW

File: examples/all-clusters-app/esp32/main/DeviceCallbacks.cpp [hunk 1]
```diff
@@ -120,20 +120,30 @@ void DeviceCallbacks::DeviceEventCallback(const ChipDeviceEvent * event, intptr_
     case DeviceEventType::kCommissioningComplete: {
         ESP_LOGI(TAG, "Commissioning complete");
 #if CONFIG_BT_NIMBLE_ENABLED && CONFIG_DEINIT_BLE_ON_COMMISSIONING_COMPLETE
-        int ret = nimble_port_stop();
-        if (ret == 0)
+
+        // ble_hs_is_enabled() returns 1 if ble host is enabled
+
```
Comment (dhrishi) [inline examples/all-clusters-app/esp32/main/DeviceCallbacks.cpp:125]: I don't think this comment is necessary. It is self explanatory.

**Review by dhrishi — APPROVED** [review]

File: examples/all-clusters-app/esp32/main/DeviceCallbacks.cpp (hunk 1 above)
Comment (jadhavrohit924) [reply examples/all-clusters-app/esp32/main/DeviceCallbacks.cpp:125]: Okay, removed

**Review by andy31415 — APPROVED** [review]
