### PR TITLE
Apply API review fixes for MTRReadParams and MTRSubscribeParams.

### LINKED ISSUE #22534: [Platform] Move minInterval/maxInterval into MTRSubscribeParams
### Reproduction steps

These should not be separate arguments. MTRSubscribeParams should require them to be created.

Part of https://github.com/project-chip/connectedhomeip/issues/22420

This probably needs to happen after #22531.

### Platform

darwin

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### LINKED ISSUE #22536: [Platform] Switch MTRSubscribeParams nullable booleans to just BOOL
### Reproduction steps
Instead of "null means default", just pre-init to default and then consumers can set it to whatever as desired.

Probably safe to do in parallel with #22531.

Part of https://github.com/project-chip/connectedhomeip/issues/22420

### Platform

darwin

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
* Move minInterval and maxInterval into MTRSubscribeParams.

* Make the booleans in MTRSubsribeParams and MTRReadParams just BOOL (inited to the default) instead of "NSNumber with nil meaning default".

Addresses part of https://github.com/project-chip/connectedhomeip/issues/22420

#### Issue Being Resolved
* Fixes #22536
* Fixes #22534

#### Change overview
See above.

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRDeviceOverXPC.h [hunk 1]
```diff
@@ -25,11 +25,6 @@ NS_ASSUME_NONNULL_BEGIN
 
 - (instancetype)init NS_UNAVAILABLE;
 + (instancetype)new NS_UNAVAILABLE;
-- (void)subscribeWithQueue:(dispatch_queue_t)queue
-                minInterval:(NSNumber *)minInterval
-                maxInterval:(NSNumber *)maxInterval
-              reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
-    subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablishedHandler NS_UNAVAILABLE;
```
Comment (vivien-apple) [inline src/darwin/Framework/CHIP/MTRDeviceOverXPC.h:32]: So this one is a leftover from https://github.com/project-chip/connectedhomeip/commit/153a564928634654576038839f904983ac600fba and the signature is unused now ?

**Review by vivien-apple — APPROVED** [review]

File: src/darwin/Framework/CHIP/MTRDeviceOverXPC.h (hunk 1 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDeviceOverXPC.h:32]: Yes, since then subscription was implemented for remoted devices.

**Comment by bzbarsky-apple** [comment]
Fast-tracking platform-specific fix with platform owner review.
