### PR TITLE
[SE05x] Logic to track signature calls for attestation is removed

### LINKED ISSUE #23064: [NXP SE05x] Remove the logic to track signature calls for attestation
### Reproduction steps

```bash
1. Code inspection of examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp file.
static variable 'sign_cert_decl_attest' is used for tracking signature calls for nocsr and certificate declaration.
Todo - Change the implementation to remove this tracking logic 

2. Use size() operator to get the length in tlv parsing
```

### Platform

other

### Platform Version(s)

N/A

### Type

Platform validated

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sujaygkulkarni-nxp**
Problem
Remove the logic to track signature calls for attestation
Fixed #23064

Change overview
* Logic to track signature calls for attestation is removed. DA example provider is made more generic
* Se05x middleware commit id is updated (contains support for updated provision examples and additional functionality of se05x)

Testing
Tested using the thermostat example and chip tool for connectivity

### CODE REVIEW

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 1]
```diff
@@ -178,108 +180,77 @@ CHIP_ERROR ExampleSe05xDACProviderv2::SignWithDeviceAttestationKey(const ByteSpa
...
-        }
-        /* Set time stamp length */
-        VerifyOrReturnError(CHIP_NO_ERROR == se05xSetCertificate(CD_TIME_STAMP_LEN_SE05X_ID, &tslen, 1), CHIP_ERROR_INTERNAL);
+    tempBuf[0] = (uint8_t) TLV::TLVElementType::Structure;
+    VerifyOrReturnError(CHIP_NO_ERROR == se05xSetCertificate(START_CONTAINER_SE05X_ID, tempBuf, 1), CHIP_ERROR_INTERNAL);
 
-        if ((tagReader.GetRemainingLength() + 1 /* End container */) >= 16)
+    for (int i = 1; i <= 3; i++)
+    {
+        if (TLV::Utilities::Find(msg_reader, TLV::ContextTag(i), tagReader) == CHIP_NO_ERROR)
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:194]: And if it's not CHIP_NO_ERROR, this might silently be ignoring broken TLV and proceeding to sign something anyway.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 1 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp]: Updated the code to handle the tlv errors.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 2]
```diff
@@ -178,108 +182,78 @@ CHIP_ERROR ExampleSe05xDACProviderv2::SignWithDeviceAttestationKey(const ByteSpa
...
-                                se05xSetCertificate(CD_ATTEST_NONCE_DATA_SE05X_ID, attest_nonce.data(), attest_nonce.size()),
-                            CHIP_ERROR_INTERNAL);
-
-        ReturnErrorOnFailure(TLV::Utilities::Find(msg_reader, TLV::ContextTag(3), tagReader));
-        uint8_t tslen = tagReader.GetLength();
-        if (tslen > 0)
+        CHIP_ERROR tlverr = CHIP_NO_ERROR;
+        tlverr = TLV::Utilities::Find(msg_reader, TLV::ContextTag(i), tagReader);
+        if (tlverr == CHIP_ERROR_TLV_TAG_NOT_FOUND){
+            continue;
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:200]: Is it really OK if tags 1 and 2 are not found?

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 3]
```diff
@@ -178,108 +182,78 @@ CHIP_ERROR ExampleSe05xDACProviderv2::SignWithDeviceAttestationKey(const ByteSpa
...
+        }
+        SuccessOrExit(tlverr);
+
+        taglen     = tagReader.GetLength();
+        tempBuf[0] = tagReader.GetControlByte();
+        ;
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:206]: Why this lone semicolon?

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 4]
```diff
@@ -178,108 +182,78 @@ CHIP_ERROR ExampleSe05xDACProviderv2::SignWithDeviceAttestationKey(const ByteSpa
...
+        tempBuf[1] = i;
+        SuccessOrExit(se05xSetCertificate(TAG1_ID + (3 * (i - 1)), tempBuf, 2));
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:208]: Where is this `3 * (i - 1)` bit coming from?  Should at least be documented, if not given a nice macro or function.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 2 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:207]: It is not. Updated the code to make sure only TAG3 is optional now.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 3 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp]: Removed.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp (hunk 4 above)
Comment (sujaygkulkarni-nxp) [reply examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp]: Updated the function with the comments on this logic.

File: examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp [hunk 5]
```diff
@@ -178,108 +189,82 @@ CHIP_ERROR ExampleSe05xDACProviderv2::SignWithDeviceAttestationKey(const ByteSpa
...
-            VerifyOrReturnError(CHIP_NO_ERROR ==
-                                    se05xSetCertificate(CD_TIME_STAMP_DATA_SE05X_ID, time_stamp.data(), time_stamp.size()),
-                                CHIP_ERROR_INTERNAL);
+            continue;
         }
-        /* Set time stamp length */
-        VerifyOrReturnError(CHIP_NO_ERROR == se05xSetCertificate(CD_TIME_STAMP_LEN_SE05X_ID, &tslen, 1), CHIP_ERROR_INTERNAL);
+        SuccessOrExit(tlverr);
+
+        // Transisnet binary object ids starting from location 0x7D300005 (TAG1_ID) to 0x7D30000D (TAG3_VALUE_ID)
```
Comment (bzbarsky-apple) [inline examples/platform/nxp/se05x/DeviceAttestationSe05xCredsExample_v2.cpp:211]:
```suggestion
        // Transient binary object ids starting from location 0x7D300005 (TAG1_ID) to 0x7D30000D (TAG3_VALUE_ID)
```

**Review by bzbarsky-apple — APPROVED** [review]
