### PR TITLE
[E2E][JF] Fix AddNOC() during JCM

### LINKED ISSUE #39442: [E2E][JF] Issue a NOC with Administrator CAT/use the correct CaseAdminSubject during JCM
Spec, JCM chapter: 

- "during the AddNOC step, Ecosystem B Administrator SHALL receive a NOC with Administrator CAT inside Fabric A. The version of the Administrator CAT SHALL be the one indicated by the corresponding entry of the GroupList attribute hold by the Joint Fabric Datastore of Fabric B."
- "during the AddNOC step, the CaseAdminSubject field SHALL contain an Anchor CAT that grants
Administer privileges only to Ecosystem A Anchor Administrator over Ecosystem B
Administrator in Fabric A. The version of the Anchor CAT SHALL be the one indicated by the
corresponding entry of the GroupList attribute hold by the Joint Fabric Datastore of Fabric B"

### PR DESCRIPTION
**Pull request by doru91**
#### Summary

Spec, JCM chapter:

- during the AddNOC step, Ecosystem B Administrator SHALL receive a NOC with Administrator CAT inside Fabric A. The version of the Administrator CAT SHALL be the one indicated by the corresponding entry of the GroupList attribute hold by the Joint Fabric Datastore of Fabric B
- during the AddNOC step, the CaseAdminSubject field SHALL contain an Anchor CAT that grants Administer privileges only to Ecosystem A Anchor Administrator over Ecosystem B Administrator in Fabric A. The version of the Anchor CAT SHALL be the one indicated by the corresponding entry of the GroupList attribute hold by the Joint Fabric Datastore of Fabric B

#### Related issues

Fix https://github.com/project-chip/connectedhomeip/issues/39442
Depends on https://github.com/project-chip/connectedhomeip/issues/39443

#### Testing

- For setting up the two Ecosystem followed the exact same steps from https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/joint_fabric_guide.md
- On Ecosystem B, used jf-control-app for opening a commissioning window in jf-admin-app (pairing open-commissioning-window 11 1 400 1000 1261)
- On Ecosystem A, used jf-control-app for commissioning jf-admin-app@EcosystemB (pairing onnetwork 15 passcode --execute-jcm true)
- on jf-control-app@B used a non-filtered fabric read for reading the NOC from Fabric Index = 2 (operationalcredentials read nocs 11 0 --fabric-filtered false) then used chip-cert to parse the NOC bytes and checked that it contains the Administrator CAT

### CODE REVIEW

**Comment by gmarcosb** [comment]
Is it possible to setup a CI/automated test to make sure this actually fixes the problem & there's no regressions in the future?

**Review by gmarcosb — APPROVED** [review]
Is it possible to setup a CI/automated test to make sure this actually fixes the problem & there's no regressions in the future?

File: examples/jf-control-app/commands/pairing/PairingCommand.cpp [hunk 1]
```diff
@@ -40,9 +40,18 @@ using namespace ::chip::Controller;
 CHIP_ERROR PairingCommand::RunCommand()
```
Comment (tcarmelveilleux) [inline examples/jf-control-app/commands/pairing/PairingCommand.cpp:40]: Please add an integration test to verify this. We cannot rely on manual testing for such procedures.

File: examples/jf-control-app/commands/pairing/PairingCommand.cpp [hunk 2]
```diff
@@ -40,9 +40,18 @@ using namespace ::chip::Controller;
...
 {
     CurrentCommissioner().RegisterPairingDelegate(this);
+    /* TODO: if JFA is onboarded get the administrator CAT initial version from JF_DS@GroupList (through RPC)
```
Comment (tcarmelveilleux) [inline examples/jf-control-app/commands/pairing/PairingCommand.cpp:43]: What is "JF_DS@GroupList" ?

Comment (doru91) [reply examples/jf-control-app/commands/pairing/PairingCommand.cpp:43]: Joint Fabric Datastore, GroupList attribute: https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/JointFabricDatastoreCluster.adoc?plain=1#L629

**Review by robertfarnum — APPROVED** [review]
Approved conditionally upon the following:

1) Re-address integration tests concerns once the OJCW command is available  https://github.com/project-chip/connectedhomeip/pull/39637 
2) Handle TODOs in PR: https://github.com/project-chip/connectedhomeip/issues/39443, realized the TODOs are dependent on the implementation of some new DS attributes (which will require additional work - https://github.com/project-chip/connectedhomeip/issues/38949)

**Review by vijs — APPROVED** [review]

File: examples/jf-control-app/commands/pairing/PairingCommand.cpp (hunk 1 above)
Comment (doru91) [reply examples/jf-control-app/commands/pairing/PairingCommand.cpp:40]: @paulux15 will submit an integration test shortly.
