### PR TITLE
Fail A record parsing if IPV4 is disabled in CHIP

### LINKED ISSUE #16837: Operational Discovery failed if  a node advertise A and AAAA records in the same time. Incorrect node address discovering.
#### Node address can't be discovered correctly if node publish both A and AAAA records. Commissioner build with disabled IPv4.
In case if commissioner build with enabled  IPv4 discovering works well.
 * expected behavior: A record should be ignored if IPv4 disabled
 * actual behavior: A record used to discover node address.
 * steps to reproduce: Pair a commissionee which advertise  both A and AAAA records and  chip-tool with disabled IPv4
 * most interesting part of a log:
 ``` 
[1648655043.939507][3664708:3664713] CHIP:TOO: Secure Pairing Success
[1648655043.939656][3664708:3664713] CHIP:DIS: Attempt to mDNS broadcast failed:  ../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1648655043.939694][3664708:3664713] CHIP:DMG: ICR moving to [AwaitingDe]
[1648655043.939711][3664708:3664713] CHIP:EM: Sending Standalone Ack for MessageCounter:3596501 on exchange 12808i
[1648655043.939789][3664708:3664713] CHIP:IN: Prepared secure message 0x7fb32e7fb070 to 0x0000000000000001 (1)  of type 0x10 and protocolId (0, 0) on exchange 12808i with MessageCounter:6735112.
[1648655043.939810][3664708:3664713] CHIP:IN: Sending encrypted msg 0x7fb32e7fb070 with MessageCounter:6735112 to 0x0000000000000001 (1) at monotonic time: 66917013 msec
[1648655043.939850][3664708:3664713] CHIP:EM: Flushed pending ack for MessageCounter:3596501 on exchange 12808i
[1648655043.940454][3664708:3664713] CHIP:DIS: Node ID resolved for 0x0000000000000001
[1648655043.940466][3664708:3664713] CHIP:DIS:     Addr 0: [::ffff:192.168.88.11]:5540
[1648655043.940477][3664708:3664713] CHIP:DIS:     Addr 1: [fe80::217:88ff:feb0:ba3]:5540
[1648655043.940488][3664708:3664713] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000000001
[1648655043.940879][3664708:3664713] CHIP:IN: Generating DestinationID. Fabric ID 0x0000000000000001, Dest node ID 0x0000000000000001, Random data
...
[1648655043.941312][3664708:3664713] CHIP:CTL: Device connection failed. Error ../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1648655043.941327][3664708:3664713] CHIP:CTL: Failed to perform commissioning step 17
[1648655043.941338][3664708:3664713] CHIP:CTL: Rendezvous cleanup
[1648655043.941350][3664708:3664713] CHIP:TOO: Device commissioning Failure: ../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1648655043.941384][3664708:3664713] CHIP:CTL: Address resolved for node: 0x0000000000000001
[1648655043.941397][3664708:3664713] CHIP:CTL: OnNodeIdResolved was called for a device with no active sessions, ignoring it.
[1648655043.941514][3664708:3664708] CHIP:-: ../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable at ../examples/chip-tool/commands/common/CHIPCommand.cpp:62
[1648655043.941546][3664708:3664708] CHIP:TOO: Run command failure: ../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
```
[failed_discovery.log](https://github.com/project-chip/connectedhomeip/files/8382302/failed_discovery.log)

 #### Proposed Solution
Type A records should ignore if commissioner doesn't support IPv4.
Below you can see a simple fix for this issue.

``` diff
--- a/src/lib/dnssd/Resolver_ImplMinimalMdns.cpp
+++ b/src/lib/dnssd/Resolver_ImplMinimalMdns.cpp
@@ -275,6 +275,7 @@ void PacketDataReporter::OnResource(ResourceType type, const ResourceData & data
         }
         break;
     case QType::A: {
+#if INET_CONFIG_ENABLE_IPV4
         Inet::IPAddress addr;
         if (!ParseARecord(data.GetData(), &addr))
         {
@@ -292,6 +293,7 @@ void PacketDataReporter::OnResource(ResourceType type, const ResourceData & data
                 OnDiscoveredNodeIPAddress(addr);
             }
         }
+#endif
         break;
     }
     case QType::AAAA: {
```

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem

MinMDNS blindly parses A records even though code relies that IPV4 disabled means no IPV4 addresses anywhere.

#### Change overview
Refuse to parse A records if no IPV4 support.

Fixes #16837

#### Testing
Compile and unit test updated.

### CODE REVIEW

**Review by cecille — APPROVED** [review]

File: src/lib/dnssd/minimal_mdns/RecordData.cpp [hunk 1]
```diff
@@ -101,6 +102,10 @@ bool ParseARecord(const BytesRange & data, chip::Inet::IPAddress * addr)
     addr->Addr[3] = htonl(chip::Encoding::BigEndian::Get32(data.Start()));
 
     return true;
+#else
+    // IPV4 support is disabled: IPAddress should never get IPv4 values.
+    return false;
```
Comment (mrjerryjohns) [inline src/lib/dnssd/minimal_mdns/RecordData.cpp:107]: Shouldn't this policy-level enforcement happen at a higher layer? Seems like we should be minimizing policy-logic application at this layer since it requires coordinated changes to a fairly broad range of platform impls, when doing so at a higher level would provide more flexibility in how easily we can make such decisions.

I'd think the mDNS impls here should just be responsible for returning to you the set of service records they discovered, and leave it to impls of `CommissioningResolveDelegate::OnNodeDiscovered` to actually prune out the IPv4 records as needed. 

Thoughts?

Comment (mrjerryjohns) [reply src/lib/dnssd/minimal_mdns/RecordData.cpp:107]: The broader theme for me is to endeavor to keep our expectations of the mDNS logic layers minimal if we can, and keep the corresponding impls as simple and light-weight as possible.

Comment (andy31415) [reply src/lib/dnssd/minimal_mdns/RecordData.cpp:107]: I am trying to enforce the invariant of `IPAddress is always a valid IP address` which seems to be the intent as when IPV4 is not enabled, we have:

```
enum class IPAddressType : uint8_t
{
    kUnknown = 0, ///< Not used.
#if INET_CONFIG_ENABLE_IPV4
    kIPv4 = 1, ///< Internet protocol version 4.
#endif         // INET_CONFIG_ENABLE_IPV4
    kIPv6 = 2, ///< Internet protocol version 6.
    kAny  = 3  ///< The unspecified internet address (independent of protocol version).
};
```

The issue here is that `parsing` was done outside the IPAddress class and is reaching into the IP address internals.

Comment (andy31415) [reply src/lib/dnssd/minimal_mdns/RecordData.cpp:107]: Bug is that ParseARecord claims to parse a valid IPAddress, but since our Type() does not support IPv4, we claim a totally invalid IPv6 instead:

```
IPAddressType IPAddress::Type() const
{
    if (Addr[0] == 0 && Addr[1] == 0 && Addr[2] == 0 && Addr[3] == 0)
        return IPAddressType::kAny;
#if INET_CONFIG_ENABLE_IPV4
    if (Addr[0] == 0 && Addr[1] == 0 && Addr[2] == htonl(0xFFFF))
        return IPAddressType::kIPv4;
#endif // INET_CONFIG_ENABLE_IPV4
    return IPAddressType::kIPv6;
}
```

**Review by bzbarsky-apple — APPROVED** [review]

File: src/lib/dnssd/minimal_mdns/RecordData.cpp (hunk 1 above)
Comment (andy31415) [reply src/lib/dnssd/minimal_mdns/RecordData.cpp:107]: Resolving after offline chat - we can update and have more consistency as a followup.
