### PR TITLE
Fix lighting-app build error for nrf52840dongle

### LINKED ISSUE #13129: Lighting-app stopped building for nRF52840-dongle
Lighting app stopped building on the nRF52840-dongle 2 days ago.  Timing correlates with the nRF Connect SDK 1.8 SDK merge (https://github.com/project-chip/connectedhomeip/pull/13031).

Build environment is a github action worker run nightly.  Issue occurs at this step in the guide using the docker instructions: https://github.com/project-chip/connectedhomeip/tree/master/examples/lighting-app/nrfconnect#building
```
west build -b nrf52840dongle_nrf52840
```

It appears some kconfig keys may have changed from the error.

**Error message:**
```console
...
Parsing /var/ncs/zephyr/Kconfig
/var/chip/examples/lighting-app/nrfconnect/boards/nrf52840dongle_nrf52840.conf:22: warning: attempt to assign the value 'y' to the undefined symbol USB
Loaded configuration '/var/ncs/zephyr/boards/arm/nrf52840dongle_nrf52840/nrf52840dongle_nrf52840_defconfig'

/var/chip/examples/lighting-app/nrfconnect/boards/nrf52840dongle_nrf52840.conf:23: warning: attempt to assign the value 'y' to the undefined symbol USB_UART_CONSOLE

/var/chip/examples/lighting-app/nrfconnect/boards/nrf52840dongle_nrf52840.conf:26: warning: attempt to assign the value '"CDC_ACM_0"' to the undefined symbol UART_SHELL_ON_DEV_NAME

error: Aborting due to Kconfig warnings

Merged configuration '/var/chip/config/nrfconnect/app/sample-defaults.conf'
Merged configuration '/var/chip/examples/lighting-app/nrfconnect/prj.conf'
Merged configuration '/var/chip/examples/lighting-app/nrfconnect/boards/nrf52840dongle_nrf52840.conf'
CMake Error at /var/ncs/zephyr/cmake/kconfig.cmake:270 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  /var/ncs/zephyr/cmake/app/boilerplate.cmake:546 (include)
  /var/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:24 (include)
  /var/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:35 (include_boilerplate)
  CMakeLists.txt:52 (find_package)


-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake -DWEST_PYTHON=/usr/bin/python3 -B/var/chip/examples/lighting-app/nrfconnect/build -S/var/chip/examples/lighting-app/nrfconnect -GNinja -DBOARD=nrf52840dongle_nrf52840
```

### PR DESCRIPTION
**Pull request by lmpprk**
#### Problem
What is being fixed? 
* Fix #13129, detailed below:

The nrf light example app gets error when building for `nrf52840dongle_nrf52840` with following unrecognized symbols in kconfig

> `CONFIG_USB` -> [replaced](https://docs.zephyrproject.org/latest/releases/release-notes-2.7.html#usb) by `CONFIG_USB_DEVICE_DRIVER ` in 2.7
>`CONFIG_UART_SHELL_ON_DEV_NAME` -> [removed](https://docs.zephyrproject.org/latest/releases/release-notes-2.7.html?highlight=config_uart_shell_on_dev_name#changes-in-this-release) in 2.7 in favor of chosen node `zephyr,shell-uart`
> `CONFIG_USB_UART_CONSOLE` -> [removed](https://docs.zephyrproject.org/latest/releases/release-notes-3.0.html?highlight=config_usb_uart_console#changes-in-this-release) in 3.0 draft

#### Change overview
- Replaced `CONFIG_USB` with `CONFIG_USB_DEVICE_STACK`
- Removed `CONFIG_USB_UART_CONSOLE`
- Added boards nrf52840dongle_nrf52840 overlay config to replace `CONFIG_UART_SHELL_ON_DEV_NAME="CDC_ACM_0"`
- Added `Build example nRF Connect SDK Lighting App on nRF52840 Dongle` in the nrfconnect example workflow
- Updated nrfconnect example script to load the board overlays if the `boards/$BOARD.conf` file exists for the example

#### Testing
How was this tested? (at least one bullet point required)
* `west build -b nrf52840dongle_nrf52840` built successfully
* Built output hex file loaded onto the dongle, USB device shows up, shell and console work correctly
* Workflow passed: https://github.com/lmpprk/connectedhomeip/actions/runs/1636443089

### CODE REVIEW

**Comment by lmpprk** [comment]
Restyled is [blocking](https://restyled.io/gh/project-chip/repos/connectedhomeip/jobs/1394929) review due to workflow permission, not sure what I need to do, would still appreciate if this one gets looked at.

**Comment by caubut-charter** [comment]
@lmpprk, try these changes: https://github.com/project-chip/connectedhomeip/commit/aa5b8436f1f9194441b682eed8247b38857e0726.

Line 44 replaces the tab with 4 spaces.  Line 47 double quotes `$OVERLAY_CONF_FLAG`.

The script is trying to force push the workflow file which is blocked here: https://github.com/project-chip/connectedhomeip/blob/d4d57f607f5cc67f349e8aa97a4443e5743595f7/.restyled.yaml#L43

If the fixes I linked are applied, I don't think restyle will find any changes and will therefore not try and push anything.

These changes were found by running the scripts locally that were found to modify the source in https://restyled.io/gh/project-chip/repos/connectedhomeip/jobs/1394929.  The flags used were extracted from https://github.com/lmpprk/connectedhomeip/blob/nrf-dongle/.restyled.yaml.

```console
docker run --rm -it -v $PWD/scripts/examples/nrfconnect_example.sh:/tmp/nrfconnect_example.sh restyled/restyler-shellharden:v4.1.1-2 shellharden --transform /tmp/nrfconnect_example.sh > /tmp/nrfconnect_example.sh
vimdiff scripts/examples/nrfconnect_example.sh /tmp/nrfconnect_example.sh

docker run --rm -it -v $PWD/scripts/examples/nrfconnect_example.sh:/tmp/nrfconnect_example.sh restyled/restyler-shellharden:v4.1.1-2 /tmp/nrfconnect_example.sh > /tmp/nrfconnect_example.sh
vimdiff scripts/examples/nrfconnect_example.sh /tmp/nrfconnect_example.sh
```

**Comment by lmpprk** [comment]
> 
> Line 44 replaces the tab with 4 spaces. Line 47 double quotes `$OVERLAY_CONF_FLAG`.
> 
> Restyled is trying to force push the workflow file since it is part of the commit but is blocked here:
> 
> https://github.com/project-chip/connectedhomeip/blob/d4d57f607f5cc67f349e8aa97a4443e5743595f7/.restyled.yaml#L43
> 
> If the fixes I linked are applied, I don't think restyled will find any changes and will therefore not try and push anything.
> ...

@caubut-charter Thank you very much, it worked!

File: scripts/examples/nrfconnect_example.sh [hunk 1]
```diff
@@ -39,4 +39,9 @@ source "../scripts/activate.sh"
 export GNUARMEMB_TOOLCHAIN_PATH="$PW_PIGWEED_CIPD_INSTALL_DIR"
 env
 
-west build -b "$BOARD" -d "$APP/nrfconnect/build/$BOARD" "$APP/nrfconnect" -- "$@"
+OVERLAY_CONF_FLAGS=()
```
Comment (andy31415) [inline scripts/examples/nrfconnect_example.sh:42]: please update build_examples.py with similar options.

I just tried:

```
./scripts/build/build_examples.py --target-glob 'nrf*52840*light' build
```

and it seemed to compile fine (it created `nrf-nrf52840-light`). Is the dongle different (assuming one is DK and one is not)? Could we add dongle support to build_examples?

Comment (caubut-charter) [reply scripts/examples/nrfconnect_example.sh:42]: Dongle uses the same chipset but lacks some of the auxiliary hardware of the devkit (DK).  It is different enough that it requires different configuration parameters for building.  Would be a good idea to add since the example has been broken for 3 weeks now (since https://github.com/project-chip/connectedhomeip/pull/13031).

Comment (lmpprk) [reply scripts/examples/nrfconnect_example.sh:42]: Thanks for the review! I added the change to build_examples.py to support the dongle. The script didn't attempt to build for the dongle at all so it never failed.

I verified the firmware built from 

```
./scripts/build/build_examples.py --target-glob 'nrf*52840*light' build
```

on a nrf52840dongle.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@lmpprk - changes to build_examples.py require unit test changes.

Also consider marking some items noglob to avoid exponential explosion of build targets when building with "*".

File: scripts/build/builders/nrf.py [hunk 2]
```diff
@@ -138,17 +141,22 @@ def generate(self):
...
+            if os.path.exists(os.path.join(
+                    self.root, self.app.AppPath(), "nrfconnect/boards/"+self.board.GnArgName()+".conf")):
+                boardconfig = "-DOVERLAY_CONFIG=boards/"+self.board.GnArgName()+".conf"
+            else:
+                boardconfig = ""
             cmd = '''
 source "$ZEPHYR_BASE/zephyr-env.sh";
 export GNUARMEMB_TOOLCHAIN_PATH="$PW_PIGWEED_CIPD_INSTALL_DIR";
-west build --cmake-only -d {outdir} -b {board} {sourcedir}{rpcs}
+west build --cmake-only -d {outdir} -b {board} {sourcedir} -- {boardoverlay} {rpcs}
```
Comment (andy31415) [inline scripts/build/builders/nrf.py:152]: previously `--` was not needed. if boardoverlay is empty, this will result in an extra `" --  "` entry which looks ugly.

How about making the overlay config be  " -- ... " or "" (i.e. include spaces) and have the string be `... {sourcedir}{boardoverlay}{rpcs}` ? Previous code seems to do that to avoid extra spacing.

Comment (lmpprk) [reply scripts/build/builders/nrf.py:152]: hmm I'm surprised how the previous code could work. I tried

```
./scripts/build/build_examples.py --target-glob 'nrf*53*light-rpc' build
```

but it got this:
```
Exception: Command ['bash', '-c', 'source "$ZEPHYR_BASE/zephyr-env.sh";\nexport GNUARMEMB_TOOLCHAIN_PATH="$PW_PIGWEED_CIPD_INSTALL_DIR";\nwest build --cmake-only -d /home/lmpprk/connectedhomeip/out/nrf-nrf5340dk-light-rpc -b nrf5340dk_nrf5340_cpuapp /home/lmpprk/connect
homeip/examples/lighting-app/nrfconnect-DOVERLAY_CONFIG=rpc.overlay'] failed: 1
```

I think the " --" has to be left out of the two overlay arg variables, otherwise in case `boardoverlay` is empty and `rpcs` is not, there would be no "--" that can pass the rpc overlay flag.

How about updating to this:
```
west build --cmake-only -d {outdir} -b {board} {sourcedir} --{boardoverlay}{rpcs}
boardconfig = " -DOVERLAY_CONFIG=boards/"+self.board.GnArgName()+".conf"
rpcs=" -DOVERLAY_CONFIG=rpc.overlay"
```

**Comment by lmpprk** [comment]
> @lmpprk - changes to build_examples.py require unit test changes.
> 
> Also consider marking some items noglob to avoid exponential explosion of build targets when building with "*".

Actually I think the dongle is only supposed to work with the light example, I'll update the target to only yield it for the lighting app. Thanks for pointing this out!

Also sorry for the newbie question: any pointer for the instructions on updating the tests? Thanks!

**Comment by lmpprk** [comment]
Committed the updated testdata.

File: scripts/build/builders/nrf.py (hunk 2 above)
Comment (lmpprk) [reply scripts/build/builders/nrf.py]: pushed a commit with the code update

**Comment by andy31415** [comment]
> > @lmpprk - changes to build_examples.py require unit test changes.
> > Also consider marking some items noglob to avoid exponential explosion of build targets when building with "*".
> 
> Actually I think the dongle is only supposed to work with the light example, I'll update the target to only yield it for the lighting app. Thanks for pointing this out!
> 
> Also sorry for the newbie question: any pointer for the instructions on updating the tests? Thanks!

For tests, run them and replace with the generated files. I do something like:

```
gn gen aabb
cd aabb
ninja -t targets | grep script | grep test # Because I always forget what target to run
ninja scripts/build:build_examples.tests
```

This will tell you what is different and you can copy the expected files into `../scripts/build/testdata`

File: scripts/build/testdata/build_all_except_host.txt [hunk 3]
```diff
@@ -551,67 +551,72 @@ cmake -S {root}/examples/shell/mbed -B {out}/mbed-CY8CPROTO_062_4343W-shell-rele
 # Generating nrf-native-posix-64-tests
 bash -c 'source "$ZEPHYR_BASE/zephyr-env.sh";
 export GNUARMEMB_TOOLCHAIN_PATH="$PW_PIGWEED_CIPD_INSTALL_DIR";
-west build --cmake-only -d {out}/nrf-native-posix-64-tests -b native_posix_64 {root}/src/test_driver/nrfconnect'
+west build --cmake-only -d {out}/nrf-native-posix-64-tests -b native_posix_64 {root}/src/test_driver/nrfconnect --'
```
Comment (andy31415) [inline scripts/build/testdata/build_all_except_host.txt:554]: the -- seems useless here. Can you modify the script to not have unneeded arguments?

Comment (lmpprk) [reply scripts/build/testdata/build_all_except_host.txt]: Updated. Also noticed that the test data I previously sent in were bad, regenerated now.

File: scripts/examples/nrfconnect_example.sh [hunk 4]
```diff
@@ -39,4 +39,9 @@ source "../scripts/activate.sh"
...
+if [[ -f "$APP/nrfconnect/boards/$BOARD.conf" ]]; then
+    OVERLAY_CONF_FLAGS+=(-DOVERLAY_CONFIG=boards/"$BOARD".conf)
```
Comment (Damian-Nordic) [inline scripts/examples/nrfconnect_example.sh:44]: This shouldn't be needed. `lighting-app/nrfconnect/CMakeLists.txt` contains the following:
```
 if (EXISTS boards/${BOARD}.conf)
   list(APPEND CONF_FILE boards/${BOARD}.conf)
 endif()
```
The problem is that it expects that the build is triggered from the project's directory. You can just fix it with:
```
if (EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/boards/${BOARD}.conf)
```
and then the build scripts won't need to be updated.

**Review by Damian-Nordic — CHANGES_REQUESTED** [review]
Thanks for the fix! Just have one comment on including the board overlays.

File: scripts/examples/nrfconnect_example.sh (hunk 4 above)
Comment (lmpprk) [reply scripts/examples/nrfconnect_example.sh]: Thanks for the comment, that's a much better fix! I was hoping not to have to do the ugly handling in the scripts. I have updated all the nrfconnect examples' CMakeList.txt to have this fix. The shell app and the pigweed-app examples' CMakeList.txt didn't have this block at all so I added it.

Comment (Damian-Nordic) [reply scripts/examples/nrfconnect_example.sh]: Thank you :)

**Review by Damian-Nordic — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
