### PR TITLE
Fix various miscellaneous Darwin API issues.

### LINKED ISSUE #22531: [Platform] Miscellaneous Darwin framework API fixes
### Reproduction steps

* Rename readAttributeWithEndpointID to readAttributePathWithEndpointID
* Document readAttributePathWithEndpointID
* Rename subscribeAttributeWithEndpointID to subscribeAttributePathWithEndpointID
* Document subscribeAttributePathWithEndpointID
* Switch various things from "strong" to "copy" for paths, reports, etc.
* Remove redundant "nonnull" declarations on properties.
* Create typedefs for the NSData representations of certificates, for readability
* Replace "(nullable X *)" with "(X * _Nullable)" in various places.
* Fix various documentation.
* Rename "failSafeExpiryTimeoutSecs" to "failSafeExpiryTimeout".

Needs to happen after both #22528 and #22529 have been fixed.

Part of https://github.com/project-chip/connectedhomeip/issues/22420

### Platform

darwin

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
* Rename readAttributeWithEndpointID to readAttributePathWithEndpointID
* Document readAttributePathWithEndpointID
* Rename subscribeAttributeWithEndpointID to subscribeAttributePathWithEndpointID
* Document subscribeAttributePathWithEndpointID
* Switch various things from "strong" to "copy" for paths, reports, etc.
* Remove redundant "nonnull" declarations on properties.
* Create typedefs for the NSData representations of certificates, for readability
* Replace "(nullable X *)" with "(X * _Nullable)" in various places.
* Fix various documentation.
* Rename "failSafeExpiryTimeoutSecs" to "failSafeExpiryTimeout".

Addresses part of https://github.com/project-chip/connectedhomeip/issues/22420

#### Issue Being Resolved
* Fixes #22531

#### Change overview
See above.

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRCertificates.h [hunk 1]
```diff
@@ -85,13 +88,13 @@ NS_ASSUME_NONNULL_BEGIN
...
  * error.
  */
-+ (nullable NSData *)generateOperationalCertificate:(id<MTRKeypair>)signingKeypair
-                                 signingCertificate:(NSData *)signingCertificate
-                               operationalPublicKey:(SecKeyRef)operationalPublicKey
-                                           fabricID:(NSNumber *)fabricID
-                                             nodeID:(NSNumber *)nodeID
-                              caseAuthenticatedTags:(NSArray<NSNumber *> * _Nullable)caseAuthenticatedTags
-                                              error:(NSError * __autoreleasing _Nullable * _Nullable)error;
++ (NSData * _Nullable)createOperationalCertificate:(id<MTRKeypair>)signingKeypair
```
Comment (vivien-apple) [inline src/darwin/Framework/CHIP/MTRCertificates.h:91]: nit: `MTRCertificateDERBytes` ?

File: src/darwin/Framework/CHIP/MTRCertificates.h [hunk 2]
```diff
@@ -85,13 +88,13 @@ NS_ASSUME_NONNULL_BEGIN
...
+                                signingCertificate:(NSData *)signingCertificate
```
Comment (vivien-apple) [inline src/darwin/Framework/CHIP/MTRCertificates.h:92]: nit: `MTRCertificateDERBytes` ?

File: src/darwin/Framework/CHIP/MTRCommissioningParameters.h [hunk 3]
```diff
@@ -22,40 +22,55 @@ NS_ASSUME_NONNULL_BEGIN
...
 /**
- * The class definition for the CHIPCommissioningParameters
- *
+ * Information that can be provided to commissionWithNodeID to commision devices.
  */
 @interface MTRCommissioningParameters : NSObject
 
 /**
- *  The CSRNonce
+ * The nonce to use when requesting a CSR for the node's operatonal
```
Comment (vivien-apple) [inline src/darwin/Framework/CHIP/MTRCommissioningParameters.h:30]: nit: `operatonal` -> `operational`

File: src/darwin/Framework/CHIP/MTRDeviceControllerStartupParams.mm [hunk 4]
```diff
@@ -49,8 +49,8 @@ - (instancetype)initWithSigningKeypair:(id<MTRKeypair>)nocSigner fabricID:(NSNum
 }
 
 - (instancetype)initWithOperationalKeypair:(id<MTRKeypair>)operationalKeypair
-                    operationalCertificate:(NSData *)operationalCertificate
-                   intermediateCertificate:(nullable NSData *)intermediateCertificate
+                    operationalCertificate:(MTRCertificateDERBytes *)operationalCertificate
+                   intermediateCertificate:(MTRCertificateDERBytes * _Nullable)intermediateCertificate
                            rootCertificate:(NSData *)rootCertificate
```
Comment (vivien-apple) [inline src/darwin/Framework/CHIP/MTRDeviceControllerStartupParams.mm:54]: nit: `NSData` -> `MTRCertificateDERBytes`

**Review by vivien-apple — APPROVED** [review]

File: src/darwin/Framework/CHIP/MTRCertificates.h (hunk 2 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRCertificates.h:92]: Good catch, done.

File: src/darwin/Framework/CHIP/MTRCommissioningParameters.h (hunk 3 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRCommissioningParameters.h:30]: Nice catch!

File: src/darwin/Framework/CHIP/MTRDeviceControllerStartupParams.mm (hunk 4 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDeviceControllerStartupParams.mm:54]: Done.

**Comment by bzbarsky-apple** [comment]
Fast-tracking platform specific change with platform owner review.
