### PR TITLE
Don't Clear mSecureSessionType on PairingSession::Clear()

### LINKED ISSUE #13711: PairingSession::GetSessionType returns incorrect result
#### Problem
During commissioning, by the time SessionManager::NewPairing (in SessionManager.cpp)
calls PairingSession::GetSessionType to pass it into SecureSessionTable::CreateNewSecureSession,
the value is not set.

You can see this by logging the value and the PairingSession pointer at that location, it's 0 (undefined), not 1 (PASE) or 2 (CASE).

You can add more logging of that value and this pointer in places (e.g. PairingSession::SetSecureSessionType, called by PASESession constructor) to see it was set.

Adding logging of that value and this pointer in PairingSession::Clear reveals it is cleared multiple times between being set and being read, so this is probably why it's not returning the correct result when finally used.

 #### Proposed Solution
Need to determine what the value is used for, whether it matters that it becomes unset, why Clear is called so frequently, etc.

### PR DESCRIPTION
**Pull request by emargolis**
#### Problem
#13711 

#### Change overview
There is no need to clear the session type because it doesn't change.

I believe the more appropriate fix will be implemented with #9059. The Clear() method is not needed and a new session instance should be allocated and the old one released when required. 

#### Testing
existing tests

### CODE REVIEW

File: src/transport/PairingSession.h [hunk 1]
```diff
@@ -177,10 +177,9 @@ class DLL_EXPORT PairingSession
     // TODO: remove Clear, we should create a new instance instead reset the old instance.
     void Clear()
     {
-        mSecureSessionType = Transport::SecureSession::Type::kUndefined;
-        mPeerNodeId        = kUndefinedNodeId;
-        mPeerCATs          = kUndefinedCATs;
-        mPeerAddress       = Transport::PeerAddress::Uninitialized();
+        mPeerNodeId  = kUndefinedNodeId;
```
Comment (mlepage-google) [inline src/transport/PairingSession.h:180]:
```suggestion
        // NOTE: no need to clear mSecureSessionType as it cannot change.
        mPeerNodeId  = kUndefinedNodeId;
```

Comment (mlepage-google) [reply src/transport/PairingSession.h:180]: Might even be better, to make mSecureSessionType const, initialize it from an arg to the constructor, and have derived classes call base class constructor with proper arg. Then it always reflects actual object and can't be altered.

**Review by mlepage-google — APPROVED** [review]
I do think this change should fix the issue, but please see the comment for a suggested tweak.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/transport/PairingSession.h (hunk 1 above)
Comment (emargolis) [reply src/transport/PairingSession.h:180]: Updated. Made mSecureSessionType const.

File: src/transport/PairingSession.h [hunk 2]
```diff
@@ -104,7 +104,7 @@ class DLL_EXPORT PairingSession
                                           TLV::TLVWriter & tlvWriter);
 
 protected:
-    void SetSecureSessionType(Transport::SecureSession::Type secureSessionType) { mSecureSessionType = secureSessionType; }
+    // void SetSecureSessionType(Transport::SecureSession::Type secureSessionType) { mSecureSessionType = secureSessionType; }
```
Comment (andy31415) [inline src/transport/PairingSession.h:107]: could we delete commented-out code instead of keeping it?

it seems we can then also remove the "protected:" line and have a smaller file vertically.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
fast track: small delta, several checkmars, PR has been up for sufficient time for cross timezone review.

File: src/transport/PairingSession.h (hunk 2 above)
Comment (emargolis) [reply src/transport/PairingSession.h]: removed this line
