### PR TITLE
[Credentials] Fix memory exposure

### LINKED ISSUE #22054: Memory revelation in KeySetData serialization
#### Problem
- Dynamic runtime analysis at Google found that random data from memory was stored in persistent storage in unused key slots, possibly revealing memory at the time of storage, and also storing garbage data.

Stack frame
```
#0 0x7f47f5827cd4 in chip::Credentials::KeySetData::Serialize(chip::TLV::TLVWriter&) const [src/credentials/GroupDataProviderImpl.cpp:785]
#1 0x7f47f581ea0b in Save [src/credentials/GroupDataProviderImpl.cpp:60]
#2 0x7f47f581ea0b in chip::Credentials::GroupDataProviderImpl::SetKeySet(unsigned char, chip::Span<unsigned char const> const&, chip::Credentials::GroupDataProvider::KeySet const&) [src/credentials/GroupDataProviderImpl.cpp:1615] 
#3 0x7f47fd9d8301 in chip::Credentials::SetSingleIpkEpochKey(chip::Credentials::GroupDataProvider*, unsigned char, chip::Span<unsigned char const> const&, chip::Span<unsigned char const> const&) [src/credentials/GroupDataProvider.h:395]..... 
```

 #### Proposed Solution
- Use default values in the slots beyond the last one used by a real key
- Cannot avoid writing entries without breaking already commissioned devices storage format. Therefore blank entries must be written to remain compatible.

### PR DESCRIPTION
**Pull request by jepenven-silabs**
#### Issue Being Resolved
* Fixes #22054

#### Change overview
Overwrite unused keys with null value when saving keys.
Update Unit test.

### CODE REVIEW

File: src/credentials/GroupDataProviderImpl.cpp [hunk 1]
```diff
@@ -770,13 +770,28 @@ struct KeySetData : PersistentData<kPersistentBufferMax>
...
+                memset(encryptionKey, 0, Crypto::CHIP_CRYPTO_SYMMETRIC_KEY_LENGTH_BYTES);
                 ReturnErrorOnFailure(writer.StartContainer(TLV::AnonymousTag(), TLV::kTLVType_Structure, item));
-                ReturnErrorOnFailure(writer.Put(TagStartTime(), static_cast<uint64_t>(key.start_time)));
-                ReturnErrorOnFailure(writer.Put(TagKeyHash(), key.hash));
+
+                if (keyCount++ < keys_count)
+                {
+                    startTime = key.start_time;
+                    hash      = key.hash;
+                    memcpy(encryptionKey, key.encryption_key, Crypto::CHIP_CRYPTO_SYMMETRIC_KEY_LENGTH_BYTES);
```
Comment (bzbarsky-apple) [inline src/credentials/GroupDataProviderImpl.cpp:788]:
```suggestion
                    memcpy(encryptionKey, key.encryption_key, sizeof(encryptionKey));
```

File: src/credentials/GroupDataProviderImpl.cpp [hunk 2]
```diff
@@ -770,13 +770,28 @@ struct KeySetData : PersistentData<kPersistentBufferMax>
...
             ReturnErrorOnFailure(writer.StartContainer(TagGroupCredentials(), TLV::kTLVType_Array, array));
+            uint8_t keyCount   = 0;
+            uint64_t startTime = 0;
+            uint16_t hash      = 0;
+            uint8_t encryptionKey[Crypto::CHIP_CRYPTO_SYMMETRIC_KEY_LENGTH_BYTES];
             for (auto & key : operational_keys)
             {
+                startTime = 0;
+                hash      = 0;
+                memset(encryptionKey, 0, Crypto::CHIP_CRYPTO_SYMMETRIC_KEY_LENGTH_BYTES);
```
Comment (bzbarsky-apple) [inline src/credentials/GroupDataProviderImpl.cpp:781]:
```suggestion
                memset(encryptionKey, 0, sizeof(encryptionKey));
```

File: src/credentials/GroupDataProviderImpl.cpp [hunk 3]
```diff
@@ -770,13 +770,28 @@ struct KeySetData : PersistentData<kPersistentBufferMax>
...
+                {
+                    startTime = key.start_time;
+                    hash      = key.hash;
+                    memcpy(encryptionKey, key.encryption_key, Crypto::CHIP_CRYPTO_SYMMETRIC_KEY_LENGTH_BYTES);
+                }
+                ReturnErrorOnFailure(writer.Put(TagStartTime(), static_cast<uint64_t>(startTime)));
+                ReturnErrorOnFailure(writer.Put(TagKeyHash(), hash));
                 ReturnErrorOnFailure(
-                    writer.Put(TagKeyValue(), ByteSpan(key.encryption_key, Crypto::CHIP_CRYPTO_SYMMETRIC_KEY_LENGTH_BYTES)));
+                    writer.Put(TagKeyValue(), ByteSpan(encryptionKey, Crypto::CHIP_CRYPTO_SYMMETRIC_KEY_LENGTH_BYTES)));
```
Comment (bzbarsky-apple) [inline src/credentials/GroupDataProviderImpl.cpp:793]:
```suggestion
                    writer.Put(TagKeyValue(), ByteSpan(encryptionKey)));
```

**Review by bzbarsky-apple — APPROVED** [review]

**Review by robszewczyk — APPROVED** [review]
