### PR TITLE
Simplfy the implementation of Mode Select Cluster

### LINKED ISSUE #11162: Mode Select Cluster implementation is using the heap
#### Problem
Mode Select Cluster implementation is using the heap. This does not work on some platforms. 

 #### Proposed Solution
Get rid of the std::map used in StaticSupportedModeOptionsManager. 
Declare all the options statically.

### LINKED ISSUE #11163: Mode Select Cluster Implementation has too many unnecessary abstraction
#### Problem
The current implementation of Mode Select Cluster has some problems:
* Over-designed interfaces and iterators that have a lot of virtuals on them, that are not necessary. This results in 24K increase in flash alone, without any of the application bits at all involved here. That is concerning.
* Went through a lot of work to design a SupportedModesManager interface, yet the cluster impl only permits a specific concrete realization of that interface, which defeats the point of that interface.

 #### Proposed Solution
This can be done much simpler: creation of a fairly simple 'data provider' interface that hides away the actual list of modes, as well as the methods to interact with that data feels like the appropriate solution here. This would hide away the storage specifics of that data (letting the application decide it), making it more flexible, as well as reducing the complexity of the overall solution.

A suggested provider interface (that would be registered with the cluster impl) could look like this:
```
class ModeDataProvider {
public:
    class ModeChangeListener {
    public:
        enum ModeOperation {
            kModeAdded = 0,
            kModeDeleted = 1,
            kModeModified = 2
        };

        virtual void OnModeChange(uint16_t modeIndex, ModeOperation modeOperation) = 0;
    };

    virtual CHIP_ERROR GetNumSupportedModes() = 0;

    virtual CHIP_ERROR GetMode(uint16_t modeIndex, Structs::ModeOptionsStruct::Type &mode, EndpointId &associatedEndpointId) = 0;
    virtual CHIP_ERROR SetMode(uint16_t modeIndex, Structs::ModeOptionStruct::Type &mode) = 0;

    virtual CHIP_ERROR RegisterModeChangeListener(ModeChangeListener *modeChangeListener) = 0;
};
```
This approximates very closely existing provider interfaces (like GroupDataProvider).

### PR DESCRIPTION
**Pull request by du48s03**
#### Problem
What is being fixed?  Examples:
* Simplify the over-complicated implementation of Mode Select Cluster
* Fixes #11163 
* Fixes #11162 

#### Change overview
Removed the usage of std::map
Removed the abstract ModeOptionIterator and its implementation
Removed the abstract ModeOptionIteratorFactory and its implementation
Move the implementation of StaticSupportedModeOptionsManager to /example folders, as it contains app-specific logic. 
Added the concrete class ModeOptionsProvider

#### Testing
How was this tested? (at least one bullet point required)
* If manually tested, what platforms controller and device platforms were manually tested, and how?
Manually tested on MacOs with chip-tool

### CODE REVIEW

File: src/app/clusters/mode-select-server/static-supported-modes-manager.cpp [hunk 1]
```diff
@@ -23,35 +23,42 @@ Structs::ModeOptionStruct::Type buildModeOptionStruct(const char * label, uint8_
...
-    { 1, StaticSupportedModesManager::coffeeOptionsSpan }
-};
+// TODO: Configure your options for each endpoint
+storage_value_type StaticSupportedModesManager::coffeeOptions[] = { buildModeOptionStruct("Black", 0, 0),
+                                                                    buildModeOptionStruct("Cappuccino", 4, 0),
+                                                                    buildModeOptionStruct("Espresso", 7, 0) };
+const StaticSupportedModesManager::EndpointSpanPair
+    StaticSupportedModesManager::supportedOptionsByEndpoints[ENDPOINTS_WITH_MODES] = {
+        EndpointSpanPair(1, Span<storage_value_type>(StaticSupportedModesManager::coffeeOptions)) // Options for Endpoint 1
+    };
```
Comment (tcarmelveilleux) [inline src/app/clusters/mode-select-server/static-supported-modes-manager.cpp:33]: Why are these fixed examples in core SDK code (e.g. `src/app`) rather than  in `examples/`

File: src/app/clusters/mode-select-server/static-supported-modes-manager.h [hunk 2]
```diff
@@ -24,6 +24,10 @@
 #include <map>
 #include <vector>
 
+#ifndef ENDPOINTS_WITH_MODES
+#define ENDPOINTS_WITH_MODES 1
+#endif
```
Comment (tcarmelveilleux) [inline src/app/clusters/mode-select-server/static-supported-modes-manager.h:29]: What is this for? It should be clear why this is here

File: src/app/clusters/mode-select-server/static-supported-modes-manager.h [hunk 3]
```diff
@@ -24,6 +24,10 @@
 #include <map>
 #include <vector>
```
Comment (tcarmelveilleux) [inline src/app/clusters/mode-select-server/static-supported-modes-manager.h:25]: These are no longer used. I don't see `std::` usage anymore...

File: src/app/clusters/mode-select-server/static-supported-modes-manager.h [hunk 4]
```diff
@@ -36,97 +40,33 @@ namespace ModeSelect {
...
-            _begin(Iterator(aSupportedOptions.data())), _end(Iterator(aSupportedOptions.data() + aSupportedOptions.size()))
+        EndpointSpanPair(const EndpointId aEndpointId, const Span<storage_value_type> && aSpan) :
+            mEndpointId(aEndpointId), mSpan(aSpan)
         {}
-        ~IteratorFactory() = default;
+    };
 
-        const Iterator * begin() const override { return &_begin; }
-        const Iterator * end() const override { return &_end; }
+    static storage_value_type coffeeOptions[];
```
Comment (tcarmelveilleux) [inline src/app/clusters/mode-select-server/static-supported-modes-manager.h:55]: This really seems like a concrete detail that should be part of a unit test only

File: src/app/clusters/mode-select-server/static-supported-modes-manager.h [hunk 5]
```diff
@@ -24,6 +24,10 @@
 #include <map>
 #include <vector>
 
+#ifndef ENDPOINTS_WITH_MODES
+#define ENDPOINTS_WITH_MODES 1
```
Comment (bzbarsky-apple) [inline src/app/clusters/mode-select-server/static-supported-modes-manager.h:28]: Why is this not using the existing define, for static endpoints?  And for dynamic ones this would not work.

File: examples/all-clusters-app/esp32/main/static-supported-modes-manager.cpp [hunk 6]
```diff
@@ -0,0 +1,75 @@
+//
```
Comment (jmartinez-silabs) [inline examples/all-clusters-app/esp32/main/static-supported-modes-manager.cpp:1]: Fix this header with the copyright like for other files

File: examples/all-clusters-app/linux/include/static-supported-modes-manager.cpp [hunk 7]
```diff
@@ -0,0 +1,75 @@
+//
```
Comment (jmartinez-silabs) [inline examples/all-clusters-app/linux/include/static-supported-modes-manager.cpp:1]: Fix this header with the copyright like for other files

File: examples/all-clusters-app/ameba/main/static-supported-modes-manager.cpp [hunk 8]
```diff
@@ -0,0 +1,75 @@
+//
```
Comment (jmartinez-silabs) [inline examples/all-clusters-app/ameba/main/static-supported-modes-manager.cpp:1]: Fix this header with the copyright like for other files

File: examples/all-clusters-app/ameba/main/include/static-supported-modes-manager.h [hunk 9]
```diff
@@ -0,0 +1,73 @@
+/*
```
Comment (jmartinez-silabs) [inline examples/all-clusters-app/ameba/main/include/static-supported-modes-manager.h:1]: All those static-supported-modes-manager.h/cpp seem copied and pasted for each platform. Why not have one static-supported-modes-manager.h/cpp in the common folder

File: examples/all-clusters-app/ameba/main/static-supported-modes-manager.cpp [hunk 10]
```diff
@@ -0,0 +1,75 @@
...
+// Created by Ding, Li-an on 10/21/21.
+//
```
Comment (du48s03) [inline examples/all-clusters-app/ameba/main/static-supported-modes-manager.cpp:3]:
```suggestion
```

File: examples/all-clusters-app/esp32/main/static-supported-modes-manager.cpp [hunk 11]
```diff
@@ -0,0 +1,75 @@
...
+// Created by Ding, Li-an on 10/21/21.
+//
```
Comment (du48s03) [inline examples/all-clusters-app/esp32/main/static-supported-modes-manager.cpp:3]:
```suggestion
```

File: examples/all-clusters-app/linux/include/static-supported-modes-manager.cpp [hunk 12]
```diff
@@ -0,0 +1,75 @@
...
+// Created by Ding, Li-an on 10/21/21.
+//
```
Comment (du48s03) [inline examples/all-clusters-app/linux/include/static-supported-modes-manager.cpp:3]:
```suggestion
```

File: examples/all-clusters-app/mbed/main/static-supported-modes-manager.cpp [hunk 13]
```diff
@@ -0,0 +1,75 @@
+//
+// Created by Ding, Li-an on 10/21/21.
+//
```
Comment (du48s03) [inline examples/all-clusters-app/mbed/main/static-supported-modes-manager.cpp:3]:
```suggestion
```

File: examples/all-clusters-app/p6/src/static-supported-modes-manager.cpp [hunk 14]
```diff
@@ -0,0 +1,75 @@
+//
+// Created by Ding, Li-an on 10/21/21.
+//
```
Comment (du48s03) [inline examples/all-clusters-app/p6/src/static-supported-modes-manager.cpp:3]:
```suggestion
```

File: examples/all-clusters-app/ameba/main/include/static-supported-modes-manager.h (hunk 9 above)
Comment (du48s03) [reply examples/all-clusters-app/ameba/main/include/static-supported-modes-manager.h:1]: I'm not sure why, but there are already shared code that are not put in the all-clusters-common folder, For example, the definition of `bool lowPowerClusterSleep()` can be found in every platform, even though they are the same. I guess the reason is to allow different platform to provide different definitions, based on their different limitations.

Comment (jmartinez-silabs) [reply examples/all-clusters-app/ameba/main/include/static-supported-modes-manager.h:1]: I guess we could add a layer for specific platform implementation. I will approve it but let see what other reviewers think of it

**Review by jmartinez-silabs — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@saurabhst @msandstedt @andy31415 ?

File: examples/all-clusters-app/ameba/main/include/static-supported-modes-manager.h (hunk 9 above)
Comment (bzbarsky-apple) [inline examples/all-clusters-app/ameba/main/include/static-supported-modes-manager.h:1]: If all the instances of all-clusters-app use the same exact code, could we have just one copy of it in `examples/all-clusters-app/all-clusters-common/src` instead of one copy per platform?  I can understand not wanting to put this into `src/app/clusters`, because this is very app-specific code, but it's not specific to the (app, platform) pair...

I see @jmartinez-silabs asked this question too...  the answer is that people didn't do the work to do things right, preferrring to copy/paste instead.  Let's not keep doing that, please, if it can be avoided.

File: examples/all-clusters-app/ameba/main/static-supported-modes-manager.cpp [hunk 15]
```diff
@@ -0,0 +1,72 @@
...
+        EndpointSpanPair(1, Span<storage_value_type>(StaticSupportedModesManager::coffeeOptions)) // Options for Endpoint 1
+    };
+
+const StaticSupportedModesManager StaticSupportedModesManager::instance = StaticSupportedModesManager();
+
+const SupportedModesManager::ModeOptionsProvider StaticSupportedModesManager::getModeOptionsProvider(EndpointId endpointId) const
+{
+    for (size_t i = 0; i < EMBER_AF_MODE_SELECT_CLUSTER_SERVER_ENDPOINT_COUNT; ++i)
+    {
+        const EndpointSpanPair & endpointSpanPair = supportedOptionsByEndpoints[i];
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/ameba/main/static-supported-modes-manager.cpp:36]:
```suggestion
    for (auto & endpointSpanPair : supportedOptionsByEndpoints)
```

**Review by bzbarsky-apple — DISMISSED** [review]

File: examples/all-clusters-app/linux/BUILD.gn [hunk 16]
```diff
@@ -15,6 +15,28 @@
 import("//build_overrides/build.gni")
 import("//build_overrides/chip.gni")
 
+static_library("static-supported-modes-manager") {
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/linux/BUILD.gn:18]: Why this separate library instad of just adding this to the sources for `executable("chip-all-clusters-app")`?

File: examples/all-clusters-app/p6/BUILD.gn [hunk 17]
```diff
@@ -54,6 +54,30 @@ p6_sdk_sources("all_clusters_app_sdk_sources") {
   public_configs = [ "${chip_root}/third_party/p6:p6_sdk_config" ]
 }
 
+static_library("static-supported-modes-manager") {
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/p6/BUILD.gn:57]: Again, why the separate library instead of adding to sources for `p6_executable("clusters_app")`?

**Comment by woody-apple** [comment]
Fast tracking as this has had > 3 days to review, and comments are addressed
