### PR TITLE
Delete persisted subscriptions that are in subscription resumption state when a subscribeRequest command comes in with keepSubscription flag set to false from the same subscriber

### LINKED ISSUE #37739: [BUG] Persisted subscription in subscription resumption mode are not removed when a new subscription with keepSubscriptions=false comes in
The specification is stating:

Image

This means that active (existing) subscriptions needs to be terminated when keepSubscriptions flag is set to FALSE → This is implemented and works as expected. (see below code snippet of OnReadInitialRequest function of src/app/InteractionModelEngine.cpp). It checks the flag keepExistingSubscriptions and it will iterate over the active readHandlers, if it finds an active subscription, it will close and release the subscription and corresponding readHandler. This frees the resource for a new subscription being set up.

>         if (!keepExistingSubscriptions)
>         {
>             //
>             // Walk through all existing subscriptions and shut down those whose subscriber matches
>             // that which just came in.
>             //
>             mReadHandlers.ForEachActiveObject([apExchangeContext](ReadHandler * handler) {
>                 if (handler->IsFromSubscriber(*apExchangeContext))
>                 {
>                     ChipLogProgress(InteractionModel,
>                                     "Deleting previous active subscription from NodeId: " ChipLogFormatX64 ", FabricIndex: %u",
>                                     ChipLogValueX64(apExchangeContext->GetSessionHandle()->AsSecureSession()->GetPeerNodeId()),
>                                     apExchangeContext->GetSessionHandle()->GetFabricIndex());
>                     handler->Close();
>                 }
> 
>                 return Loop::Continue;
>             });
>       }

But the specification is also mentioning it shall terminate any **pending** subscriptions. A subscription that is in a subscription resumption state can be seen as a pending subscription.
→ This implementation is missing in the Matter SDK. The persisted subscription will be kept in subscription resumption state and the stack keeps trying to resume this subscription, although the controller requested to terminate it (keepSubscription flag is set to false). So this subscription needs to be removed as well.

### Reproduction steps
Performed the test with QPG light switch device (enabled persisted subscriptions and subcription resumption timeout)

1. Commission the device with chiptool and setup a subscription on switch events. (keepSubscription = false, is-urgent=true)
2. Check that the reports are coming in as expected when the switch device is triggered
3. Move the switch device out-or-range
4. Trigger the switch, so the report can't be sent out after retries, and the subscription goes into subscription resumption mode
5. Bring the device back in range while the subscription resumption is still ongoing.
6. Setup a subscription again with keepSubscriptions = False
7. Check that the reports are coming in as expected when the switch device is triggered (with the new subscription)
8. After some time, the subscription resumption timer will be fired and it will try to resume the old subscription although, keepSubscription was set to false.

Solution should be that when the keepSubscription flag is set to false, the subscription resumption shall be terminated and the relevant persisted subscription shall be removed from persisted storage.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

master

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

Linked Issue Report: https://github.com/project-chip/connectedhomeip/issues/36081

### PR DESCRIPTION
**Pull request by dvdm-qorvo**
Fixes https://github.com/project-chip/connectedhomeip/issues/37739

The Matter specification is saying:
"If KeepSubscriptions is FALSE, all existing or pending subscriptions on the publisher for this subscriber SHALL be terminated."

Currently only active readHandlers and corresponding persisted subscription were removed. The subscriptions that were persisted and in subscription resumption mode, were kept in persistent storage, keeping the subscription resumption mechanism active, so pending subscriptions were not terminated. This fixes, when a subscribeRequest come in with keepSubscriptions flag set to false, these persisted non-active subscriptions can be deleted as well and the subscription resumption mechanism can be stopped if no other subscription were resuming.

#### Testing
Verified with QPG switch device based on the instructions listed in https://github.com/project-chip/connectedhomeip/issues/37739

### CODE REVIEW

File: src/app/InteractionModelEngine.cpp [hunk 1]
```diff
@@ -723,14 +723,46 @@ Protocols::InteractionModel::Status InteractionModelEngine::OnReadInitialRequest
...
+            {
+                SubscriptionResumptionStorage::SubscriptionInfo subscriptionInfo;
+                auto * iterator = mpSubscriptionResumptionStorage->IterateSubscriptions();
+
+                while (iterator->Next(subscriptionInfo))
+                {
+                    if (subscriptionInfo.mNodeId == apExchangeContext->GetSessionHandle()->AsSecureSession()->GetPeerNodeId() &&
+                        subscriptionInfo.mFabricIndex == apExchangeContext->GetSessionHandle()->GetFabricIndex())
+                    {
+                        ChipLogProgress(InteractionModel,
```
Comment (jtung-apple) [inline src/app/InteractionModelEngine.cpp:746]: I suggest also log the SubscriptionId on this line.

**Review by jtung-apple — APPROVED** [review]

File: src/app/InteractionModelEngine.cpp [hunk 2]
```diff
@@ -723,14 +723,47 @@ Protocols::InteractionModel::Status InteractionModelEngine::OnReadInitialRequest
...
+                                        ChipLogValueX64(subscriptionInfo.mNodeId), subscriptionInfo.mFabricIndex,
+                                        subscriptionInfo.mSubscriptionId);
+                        mpSubscriptionResumptionStorage->Delete(subscriptionInfo.mNodeId, subscriptionInfo.mFabricIndex,
+                                                                subscriptionInfo.mSubscriptionId);
+                    }
+                }
+                iterator->Release();
+
+                // If we have no subscriptions to resume, we can cancel the Timer, to make sure it is cleared in the case,
+                // we deleted a subscription in resumption mode.
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.cpp:758]:
```suggestion
                // If we have no subscriptions to resume, we can cancel the timer, which might be armed
                // if one of the subscriptions we deleted was about to be resumed.
```

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/InteractionModelEngine.cpp [hunk 3]
```diff
@@ -723,14 +723,47 @@ Protocols::InteractionModel::Status InteractionModelEngine::OnReadInitialRequest
...
+                if (!HasSubscriptionsToResume())
+                {
+                    mpExchangeMgr->GetSessionManager()->SystemLayer()->CancelTimer(ResumeSubscriptionsTimerCallback, this);
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.cpp:761]: Should this reset the counter like https://github.com/project-chip/connectedhomeip/pull/37740/files does?

Comment (dvdm-qorvo) [reply src/app/InteractionModelEngine.cpp:761]: This is done 2 lines below. mNumSubscriptionResumptionRetries is set to 0

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
It is a bit annoying that we are not able to unit test this ... we are adding tests that are only verifiable manually and in probably somewhat more complex conditions. Without unit tests we cannot ensure that things do not regress back after some other changes.
