### PR TITLE
[Darwin]Fix: enable controller to skip complete step

### LINKED ISSUE #26239: [1.0] MTRCommissioningParameters for darwin could not skip step sendComplete
### Reproduction steps

For darwin there is no way to skip  step sendComplete

During commissioning process, as the [Matter 1.0 Core Specification](https://csa-iot.org/developer-resource/specifications-download-request/), the implementation should provide a way for commissioner to skip step sendComplete.

It says in chapter5.5 Commissioning Flows
> While the Administrator of steps 13-15 will, in many situations, be the Commissioner Node itself, it
MAY be a different Node that was configured by the Commissioner to have Administer privilege
against the Commissionee’s General Commissioning Cluster. This is to support flexibility in finalizing the Commissioning. From a Commissionee’s perspective, all Nodes with Administer privilege in
the Commissionee’s ACL are equivalent once the Node has a Node Operational Certificate and associated Node Operational Identifier on the Fabric into which it was just commissioned.

In project connectedhomeip/src/darwin/Framework/CHIP the implementation of MTRDeviceController 

```
- (BOOL)commissionNodeWithID:(NSNumber *)nodeID
         commissioningParams:(MTRCommissioningParameters *)commissioningParams
                       error:(NSError * __autoreleasing *)error;
```
There is no code to set `chip::Controller::CommissioningParameters params` `SetSkipCommissioningComplete`

we try to add a property for `MTRCommissioningParameters` and set skip sendComplete in

```
- (BOOL)commissionNodeWithID:(NSNumber *)nodeID
         commissioningParams:(MTRCommissioningParameters *)commissioningParams
                       error:(NSError * __autoreleasing *)error
{
     ...
        if (commissioningParams.skipCommissioningComplete) {
            NSLog(@"Matter step====set skipCommissioningComplete");
            params.SetSkipCommissioningComplete(commissioningParams.skipCommissioningComplete.boolValue);
        }
       ...
}
```
Could you please provide a skip function just like this or any other way you prefer?

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

9c0ca13 - Fix Linux standalone job. (#23897)

### Platform

darwin

### Platform Version(s)

iOS 16.2

### Type

Platform Issue

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by robinmo**
Fix #26239

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRCommissioningParameters.h [hunk 1]
```diff
@@ -80,6 +80,12 @@ NS_ASSUME_NONNULL_BEGIN
  */
 @property (nonatomic, copy, nullable) NSNumber * failSafeTimeout API_AVAILABLE(ios(16.4), macos(13.3), watchos(9.4), tvos(16.4));
 
+/**
+ * Only perform the PASE steps of commissioning.
+ * Commissioning will be completed by another admin on the network.
+ */
+@property (nonatomic, copy, nullable) NSNumber * skipCommissioningComplete;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRCommissioningParameters.h:87]: What does `nil` mean here?  Why is this nullable?  That is, why is this not just of type BOOL, defaulting to NO?

Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRCommissioningParameters.h:87]: This needs an MTR_NEWLY_AVAILABLE annotation at the end:
```suggestion
@property (nonatomic, copy, nullable) NSNumber * skipCommissioningComplete MTR_NEWLY_AVAILABLE;
```

**Review by Damian-Nordic — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@robinmo Looks like a random failure on a timing-dependent test... retriggered it.
