### PR TITLE
Mark CASE sessions as defunct when we don't get expected responses/acks.

### LINKED ISSUE #20814: Automatically mark sessions as defunct on transport/timeout failures
#### Problem

When we encounter an ACK timeout, or an app-level timeout, we don't do anything to the underlying session. Session consumers continue to putter on with a potentially broken session without a more explicit app involvement to do something different.

#### Proposal

1. Mark things defunct from inside MRP bits if the exchange is not waiting on an app-level reply.
2. Mark things defunct on app-level timeout if we were waiting on an app-level reply.

While the ideal reality would be to always mark a session defunct on any MRP timeouts, the current reality is that commands/writes that take a long time due to app-level work holding up the main CHIP execution context means that ACKs don't come back in time, resulting in an assessment of MRP failure even though the other side did receive the message.

We have logic to pre-emptively fire off a single ACK on receipt of such long-running commands, but it's still risky since the loss of that single ACK would now render the session defunct (vs doing so on not receiving ACKs on any of the re-transmissions).

So the above strategy is perhaps the best balanced approach for now.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
#### Problem
We never mark CASE sessions as defunct unless an application manually calls Disconnect.

#### Change overview
1. Fix session holder notification to handle session holders removing themselves when notified.
2. Make OperationalDeviceProxy::OnSessionHang disconnect, so we both mark the session as defunct and put the proxy into a state where it will try to create a new session instead of reusing this one.
3. Adjust the rules for calling OnSessionHang a bit to avoid slightly delayed acks followed by an app-level response causing a disconnect.

#### Testing
1. Commission server as node id 17.
2. `chip-tool interactive start`
3. `basic read data-model-revision 17 0`
4.  Restart the server.
5. `basic read data-model-revision 17 0`
6. `basic read data-model-revision 17 0`

Step 5 timed out.  Step 6 worked.  Without this PR, step 6 also times out.

### CODE REVIEW

File: src/app/OperationalDeviceProxy.cpp [hunk 1]
```diff
@@ -354,7 +354,7 @@ void OperationalDeviceProxy::OnFirstMessageDeliveryFailed()
 
 void OperationalDeviceProxy::OnSessionHang()
 {
-    // TODO: establish a new session
+    Disconnect();
```
Comment (mrjerryjohns) [inline src/app/OperationalDeviceProxy.cpp:357]: I thought based on our discussions, that we were going to mark the session as defunct straight from within `ExchangeContext::NotifyResponseTimeout` and from `ReliableMessageMgr`, in addition to calling `OnSessionHang`.

With the changes that @tehampson is doing, `OperationalDeviceProxy` is pivoting to only being resident while a session is being established, and so this is effectively going to be a no-op pretty much 99% of the time.

**Review by mrjerryjohns — CHANGES_REQUESTED** [review]
Change is not quite in the right place.

File: src/app/OperationalDeviceProxy.cpp (hunk 1 above)
Comment (mrjerryjohns) [reply src/app/OperationalDeviceProxy.cpp:357]: Importantly, the marking of a session as defunct should not only happen on the controller side - it should apply equally to sessions used by server objects (like `ReadHandler` for example too, when it generates a report, that should fail because the session is now defunct).

Comment (bzbarsky-apple) [reply src/app/OperationalDeviceProxy.cpp:357]: We would need to do both, then, until @tehampson's changes happen, because just marking the session defunct does not help if we have an operational device proxy still hanging around that references it that we hand out to people.

I can certainly do that.

**Review by mrjerryjohns — APPROVED** [review]
Thanks for the fix-ups. Any ideas on how we could make an automated test here?

**Comment by mrjerryjohns** [comment]
If you could add the ability to disable 'message reception' at the message layer, we could in theory, craft-up a fairly simple test in Python:

1. Disable message reception.
2. Send a command. It should time out
3. Enable message reception.
4. Send the command again. That should re-setup CASE, and the command should succeed.

**Comment by mrjerryjohns** [comment]
Once #20531 merges, the actual timeout shouldn't take too long if we can adjust it down. This should make the above test possible to implement.

Follow-up fine.

**Comment by bzbarsky-apple** [comment]
> I hadn't had any yet.

Added a test now.

**Review by krypton36 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]
