### PR TITLE
Move IM standalone test run on a single event loop

### LINKED ISSUE #7939: Move IM standalone test run inside chip thread.
#### Problem
we see race happens in IM test, since shutdown happens after OnWriteResponse mpDelegate->WriteResponseProcessed(this); inside WriteResponseProcessed, https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/integration/chip_im_initiator.cpp#L291 has been called to unblock the next test run, but shutdown has not yet run.

in cirque test, we are seeing the flaky for IM test
Send write request message to Node: 12344321
[1624643323.443755][157] CHIP:DMG: WriteClient moving to [AddAttribu]
[1624643323.443785][157] CHIP:IN: Secure message was encrypted: Msg ID 17
[1624643323.443793][157] CHIP:IN: Encrypted message 0x7fffffffe2c0 from 0x000000000001B669 to 0x0000000000BC5C01 of type 6 and protocolId 5 on exchange 39025.
[1624643323.443798][157] CHIP:IN: Sending msg 0x7fffffffe2c0 to 0x0000000000BC5C01 at utc time: 1160308 msec
[1624643323.443801][157] CHIP:IN: Sending secure msg on generic transport
[1624643323.443822][157] CHIP:IN: Secure msg send status No Error
[1624643323.443831][157] CHIP:DMG: WriteClient moving to [AwaitingRe]
[1624643323.644432][167] CHIP:IN: Secure transport received message destined to fabric 0, node 0x000000000001B669. Key ID 0
[1624643323.644475][167] CHIP:EM: Received message of type 7 and protocolId 5 on exchange 39025
[1624643323.644488][167] CHIP:EM: Sending Standalone Ack for MsgId:00000009
[1624643323.644495][167] CHIP:IN: Secure message was encrypted: Msg ID 18
[1624643323.644498][167] CHIP:IN: Encrypted message 0x7fffe2ffd330 from 0x000000000001B669 to 0x0000000000BC5C01 of type 16 and protocolId 0 on exchange 39025.
[1624643323.644502][167] CHIP:IN: Sending msg 0x7fffe2ffd330 to 0x0000000000BC5C01 at utc time: 1160509 msec
[1624643323.644504][167] CHIP:IN: Sending secure msg on generic transport
[1624643323.644526][167] CHIP:IN: Secure msg send status No Error
[1624643323.644534][167] CHIP:EM: Flushed pending ack for MsgId:00000009
[1624643323.644541][167] CHIP:DMG: WriteResponse =
[1624643323.644544][167] CHIP:DMG: {
[1624643323.644546][167] CHIP:DMG: 	AttributeStatusList =
[1624643323.644548][167] CHIP:DMG: 	[
[1624643323.644551][167] CHIP:DMG: 		AttributeStatusElement =
[1624643323.644553][167] CHIP:DMG: 		{
[1624643323.644555][167] CHIP:DMG: 			AttributePath =
[1624643323.644558][167] CHIP:DMG: 			{
[1624643323.644560][167] CHIP:DMG: 				FieldTag = 0x4,
[1624643323.644562][167] CHIP:DMG: 				NodeId = 0x1,
[1624643323.644565][167] CHIP:DMG: 				ClusterId = 0x3,
[1624643323.644567][167] CHIP:DMG: 				EndpointId = 0x2,
[1624643323.644569][167] CHIP:DMG: 			}
[1624643323.644572][167] CHIP:DMG: 				
[1624643323.644574][167] CHIP:DMG: 			StatusElement =
[1624643323.644576][167] CHIP:DMG: 			{
[1624643323.644578][167] CHIP:DMG: 				GeneralCode = 0x0,
[1624643323.644580][167] CHIP:DMG: 				ProtocolId = 0x0,
[1624643323.644583][167] CHIP:DMG: 				protocolCode = 0x0,
[1624643323.644584][167] CHIP:DMG: 			},
[1624643323.644587][167] CHIP:DMG: 			
[1624643323.644589][167] CHIP:DMG: 		},
[1624643323.644592][167] CHIP:DMG: 		
[1624643323.644594][167] CHIP:DMG: 	],
[1624643323.644597][167] CHIP:DMG: 	
[1624643323.644599][167] CHIP:DMG: }
Write Response: 2/2(100.00%) time=0.201ms
ChipCommandSender failed: CHIP Error 4011 (0x00000FAB): No memory
[1624643323.645142][167] CHIP:DMG: WriteClient moving to [Uninitiali]
[1624643323.645142][167] CHIP:DMG: WriteClient moving to [Uninitiali]
[Thread 0x7fffedffd700 (LWP 165) exited]
[Thread 0x7fffe2ffe700 (LWP 167) exited]
[Thread 0x7fffe3fff700 (LWP 166) exited]
[Thread 0x7fffeeffe700 (LWP 164) exited]
[Thread 0x7fffeffff700 (LWP 163) exited]
[Thread 0x7ffff5f24700 (LWP 162) exited]
[Thread 0x7ffff6f25700 (LWP 161) exited]
[Inferior 1 (process 157) exited with code 01]
No stack.
(gdb) quit

Proposed solution:
Move IM standalone test run in single thread with chip

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
What is being fixed?  Examples:
* This PR is to fix the remaining race issues happens in IM test by running everything within a single event loop.
* Currently, Platform Layer provides both API RunEventLoop to run Matter on the app main thread and StartEventLoopTask/StopEventLoopTask to run Matter on a separate thread.  For internal testing, we plan to make all test apps single threaded to prevent any race issue occurs.

* Fixes #7939 

#### Change overview
Move IM standalone test run on a single event loop

#### Testing
How was this tested? (at least one bullet point required)
Setting up cirque environment
git submodule update --init
./scripts/tests/cirque_tests.sh bootstrap

Run IM test for 10 times and confirmed no race issue occurs
./scripts/tests/cirque_tests.sh run_test InteractionModelTest

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]
thanks

File: src/app/tests/integration/chip_im_initiator.cpp [hunk 1]
```diff
@@ -293,8 +293,143 @@ void HandleWriteComplete()
...
+    if (gCommandRespCount < kMaxCommandMessageCount)
+    {
+        chip::app::CommandSender * commandSender;
+        err = chip::app::InteractionModelEngine::GetInstance()->NewCommandSender(&commandSender);
+        SuccessOrExit(err);
+
+        err = SendCommandRequest(commandSender);
+        SuccessOrExit(err);
+
+        err = chip::DeviceLayer::SystemLayer.StartTimer(gMessageIntervalSeconds * 1000, CommandRequestTimerHandler, NULL);
```
Comment (bzbarsky-apple) [inline src/app/tests/integration/chip_im_initiator.cpp:325]: So in this new setup each test will definitely run for `gMessageIntervalSeconds` instead of completing when the response is received, right?  Is that intended?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/tests/integration/chip_im_initiator.cpp [hunk 2]
```diff
@@ -293,8 +293,143 @@ void HandleWriteComplete()
 
     printf("Write Response: %" PRIu64 "/%" PRIu64 "(%.2f%%) time=%.3fms\n", gWriteRespCount, gWriteCount,
            static_cast<double>(gWriteRespCount) * 100 / gWriteCount, static_cast<double>(transitTime) / 1000);
+}
+
+void Shutdown()
+{
+    chip::app::InteractionModelEngine::GetInstance()->Shutdown();
+    ShutdownChip();
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/app/tests/integration/chip_im_initiator.cpp:301]: It looks like #8100 had similar problems, in addition to possibly calling `StopEventLoopTask` when there is no event loop running, which is also not ok.

File: src/app/tests/integration/chip_im_initiator.cpp [hunk 3]
```diff
@@ -293,8 +293,143 @@ void HandleWriteComplete()
...
+    {
+        err = chip::DeviceLayer::SystemLayer.StartTimer(gMessageIntervalSeconds * 1000, WriteRequestTimerHandler, NULL);
+        SuccessOrExit(err);
+    }
 
-    gCond.notify_one();
+exit:
+    if (err != CHIP_NO_ERROR)
+    {
+        printf("Failed to handle bad command request: %s\n", chip::ErrorStr(err));
```
[the remark this answers is not in the document]
Comment (yufengwangca) [reply src/app/tests/integration/chip_im_initiator.cpp]: Updated the error message

File: src/app/tests/integration/chip_im_initiator.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (yufengwangca) [reply src/app/tests/integration/chip_im_initiator.cpp]: I updated the logic to only call StopEventLoopTask to trigger RunEventLoop to exit after all work item processing is stopped. And do platform shutdown only after the RunEventLoop returns.

File: src/app/tests/integration/chip_im_initiator.cpp (hunk 1 above)
Comment (yufengwangca) [reply src/app/tests/integration/chip_im_initiator.cpp:320]: Yes, it is intended. We always start new test after interval gMessageIntervalSeconds

Comment (bzbarsky-apple) [reply src/app/tests/integration/chip_im_initiator.cpp:320]: Alright.  Seems like it will make the test run much slower, but maybe that's ok....

File: src/app/tests/integration/chip_im_responder.cpp [hunk 4]
```diff
@@ -208,6 +208,7 @@ int main(int argc, char * argv[])
 
     chip::app::InteractionModelEngine::GetInstance()->Shutdown();
 
+    chip::DeviceLayer::PlatformMgr().StopEventLoopTask();
```
Comment (bzbarsky-apple) [inline src/app/tests/integration/chip_im_responder.cpp:211]: This does not make sense to me.  This is after `RunEventLoop` has returned, so what does it even mean to call this function here?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/tests/integration/chip_im_responder.cpp (hunk 4 above)
Comment (yufengwangca) [reply src/app/tests/integration/chip_im_responder.cpp]: Acked, we don't need to explicitly stop event loop after RunEventLoop returned

**Review by bzbarsky-apple — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
