### PR TITLE
[Simulated Test] Simulated node does not have a chance to send the in…

### LINKED ISSUE #23104: YAML last step of any simulated test case seem to get skipped
### Reproduction steps

1. Simulated test
2. Pair DUT to TH
3. Saw a strange issue where the last step of any simulated test case seem to get skipped, I even duplicated the last test step in one of the script and it gets executed only once.

Added diff link:
https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:connectedhomeip:Simulated_Last_Step_Error

### Bug prevalence

Eveytime

### GitHub hash of the SDK that was being used

7b284c027bd5499ca3c5be00d51f83715e8969d6

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

YAML file:
[Test_TC_ACT_3_1_Simulated.zip](https://github.com/project-chip/connectedhomeip/files/9754791/Test_TC_ACT_3_1_Simulated.zip)

Execution logs:
[ACT_3_1_DUT.zip](https://github.com/project-chip/connectedhomeip/files/9754776/ACT_3_1_DUT.zip)
In line no: 1529  ./out/debug/standalone/chip-tool bridgedactions read setup-url 0x654321 0

### PR DESCRIPTION
**Pull request by vivien-apple**
…teraction response for the last step on success

#### Problem

Fix #23104

The last step of the test are not really skipped, but the runner does not have a chance to send the interaction response.
This PR does an async exit so the interaction response can be sent properly.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

File: examples/placeholder/linux/include/TestCommand.h [hunk 1]
```diff
@@ -87,7 +87,21 @@ class TestCommand : public TestRunner,
...
+        {
+            chip::DeviceLayer::PlatformMgr().ScheduleWork(ScheduleExit, reinterpret_cast<intptr_t>(this));
+        }
+        else
+        {
+            SetCommandExitStatus(err);
+        }
+    }
+
+    static void ScheduleExit(intptr_t context)
```
Comment (bzbarsky-apple) [inline examples/placeholder/linux/include/TestCommand.h:101]:
```suggestion
    static void AsyncExit(intptr_t context)
```

**Review by bzbarsky-apple — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]
