### PR TITLE
chef: Use -u flag to force linking non-weak functions for esp32 example

### LINKED ISSUE #33165: [BUG] Weak functions are linked when building "chef" app
### Reproduction steps

This seems to be a similar issue of  [31439](https://github.com/project-chip/connectedhomeip/issues/31439)

1. Follow the instructions to build Chef airqualitysensor

```
$ source ~/tools/esp-idf/export.sh 

$ cd connectedhomeip/

$ source scripts/activate.sh 

$ cd examples/chef/

# Add config.yaml as below
$  cat config.yaml
esp32:
  IDF_PATH: /home/erwinpan/tools/esp-idf
  TTY: /dev/ttyUSB0


$ ./chef.py -zbr -d rootnode_airqualitysensor_e63187f6c9 -t esp32
```

2. After build done, check the function `emberAfExternalAttributeReadCallback` and `emberAfExternalAttributeWriteCallback` are based on `generic-callback-stubs.cpp`
```
examples/chef$ grep emberAfExternal esp32/build/chip-shell.map 
 .text._Z36emberAfExternalAttributeReadCallbacktmPK24EmberAfAttributeMetadataPht
                0x00000000401c706c                _Z36emberAfExternalAttributeReadCallbacktmPK24EmberAfAttributeMetadataPht
 .text._Z37emberAfExternalAttributeWriteCallbacktmPK24EmberAfAttributeMetadataPh
                0x00000000401c7074                _Z37emberAfExternalAttributeWriteCallbacktmPK24EmberAfAttributeMetadataPh
_Z36emberAfExternalAttributeReadCallbacktmPK24EmberAfAttributeMetadataPht esp-idf/main/libmain.a(generic-callback-stubs.cpp.obj)
_Z37emberAfExternalAttributeWriteCallbacktmPK24EmberAfAttributeMetadataPh esp-idf/main/libmain.a(generic-callback-stubs.cpp.obj)
```

3. And they are defined as `weak` functions in [src/app/util/generic-callback-stubs.cpp](https://github.com/project-chip/connectedhomeip/blob/22188b60f18b4834cf0f3c13926c35b7b6cf0bfe/src/app/util/generic-callback-stubs.cpp#L39)
```
chip::Protocols::InteractionModel::Status __attribute__((weak))
emberAfExternalAttributeWriteCallback(EndpointId endpoint, ClusterId clusterId, const EmberAfAttributeMetadata * attributeMetadata,
                                      uint8_t * buffer)
{
    return chip::Protocols::InteractionModel::Status::Failure;
}
...
chip::Protocols::InteractionModel::Status __attribute__((weak))
emberAfExternalAttributeReadCallback(EndpointId endpoint, ClusterId clusterId, const EmberAfAttributeMetadata * attributeMetadata,
                                     uint8_t * buffer, uint16_t maxReadLength)
```

4. Actually the both two function are defined in [examples/chef/common/stubs.cpp](https://github.com/project-chip/connectedhomeip/blob/22188b60f18b4834cf0f3c13926c35b7b6cf0bfe/examples/chef/common/stubs.cpp#L28] which is supposed to overwrite the `weak` functions when linking objects.
```
Protocols::InteractionModel::Status emberAfExternalAttributeReadCallback(EndpointId endpoint, ClusterId clusterId,
                                                                         const EmberAfAttributeMetadata * attributeMetadata,
                                                                         uint8_t * buffer, uint16_t maxReadLength)
...
Protocols::InteractionModel::Status emberAfExternalAttributeWriteCallback(EndpointId endpoint, ClusterId clusterId,
                                                                          const EmberAfAttributeMetadata * attributeMetadata,
                                                                          uint8_t * buffer)
```

5. And confirm that all other functions in the "examples/chef/common/stubs.cpp" were built and linked in the final executable
```
examples/chef$ grep stub.cpp esp32/build/chip-shell.map
esp-idf/main/libmain.a(callback-stub.cpp.obj)
 .text          0x0000000000000000        0x0 esp-idf/main/libmain.a(callback-stub.cpp.obj)
 .data          0x0000000000000000        0x0 esp-idf/main/libmain.a(callback-stub.cpp.obj)
...
_Z52emberAfOtaSoftwareUpdateRequestorClusterInitCallbackt esp-idf/main/libmain.a(callback-stub.cpp.obj)
_Z53emberAfRelativeHumidityMeasurementClusterInitCallbackt esp-idf/main/libmain.a(callback-stub.cpp.obj)
```

Only ESP32 has this issue. I follow the same steps and confirm Linux doesn't have this issue.

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

22188b6

### Platform

esp32

### Platform Version(s)

_No response_

### Anything else?

This seems to be a similar issue of  [31439](https://github.com/project-chip/connectedhomeip/issues/31439)

### PR DESCRIPTION
**Pull request by wqx6**
Add a function and use -u flag to force linking the chef stubs.cpp file to ensure the non-weak functions be linked.

Fixes #33165

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

File: examples/chef/common/stubs.cpp [hunk 1]
```diff
@@ -235,3 +235,7 @@ void emberAfWakeOnLanClusterInitCallback(EndpointId endpoint)
     WakeOnLan::SetDefaultDelegate(endpoint, &wakeOnLanManager);
 }
 #endif
+
+// No-op function, used to force linking this file,
+// instead of the weak functions from other files
+extern "C" void chef_include_stubs_impl(void) {}
```
Comment (erwinpan1) [inline examples/chef/common/stubs.cpp:241]: Is this only available to ESP32?

File: examples/chef/esp32/main/CMakeLists.txt [hunk 2]
```diff
@@ -121,6 +121,9 @@ idf_component_register(PRIV_INCLUDE_DIRS
                       PRIV_REQUIRES chip nvs_flash bt console mbedtls QRCode tft screen-framework spidriver
                       SRC_DIRS ${SRC_DIRS_LIST})
 
+# Forces the linker to include common/stubs.cpp
+target_link_libraries(${COMPONENT_LIB} INTERFACE "-u chef_include_stubs_impl")
```
Comment (erwinpan1) [inline examples/chef/esp32/main/CMakeLists.txt:125]: The Linker already links common/stubs.cpp.  However, the `emberAfExternalAttributeReadCallback` `emberAfExternalAttributeWriteCallback` aren't linked. Can this force the 2 functions to be linked?

Comment (wqx6) [reply examples/chef/esp32/main/CMakeLists.txt:125]: The common/stubs.cpp is linked by `-u` flag, so all the non-weak functions in that file will override the weak definitions We don't need to force the 2 functions to be linked.

File: examples/chef/common/stubs.cpp (hunk 1 above)
Comment (wqx6) [reply examples/chef/common/stubs.cpp:241]: Yes, if other platforms have the same issues they can also use this functions

**Review by erwinpan1 — APPROVED** [review]
LGTM. Thanks !!
