### PR TITLE
TestCluster: Add attribute resets during Test cmd.

### LINKED ISSUE #13434: Cluster test failure on test 174 on M5
#### Problem
Test cluster test 174 fails.
'''
[1641873493.836219][3628224:3628229] CHIP:TOO:  ***** Test Step 174 : Read list of structs containing nullables and optionals

[1641873493.836270][3628224:3628229] CHIP:DMG: SendReadRequest ReadClient[0x7f5310001290]: Sending Read Request
[1641873493.836332][3628224:3628229] CHIP:IN: Prepared secure message 0x5611f71ba488 to 0x00000000000004D2 (1)  of type 0x2 and protocolId (0, 1) on exchange 32309i with MessageCounter:1844988.
[1641873493.836362][3628224:3628229] CHIP:IN: Sending encrypted msg 0x5611f71ba488 with MessageCounter:1844988 to 0x00000000000004D2 (1) at monotonic time: 943923701 msec
[1641873493.836507][3628224:3628229] CHIP:DMG: MoveToState ReadClient[0x7f5310001290]: Moving to [AwaitingIn]
[1641873493.836551][3628224:3628229] CHIP:DMG: ICR moving to [AwaitingDe]
[1641873493.836568][3628224:3628229] CHIP:EM: Sending Standalone Ack for MessageCounter:6727973 on exchange 32308i
[1641873493.836602][3628224:3628229] CHIP:IN: Prepared secure message 0x7f531a7fabf8 to 0x00000000000004D2 (1)  of type 0x10 and protocolId (0, 0) on exchange 32308i with MessageCounter:1844989.
[1641873493.836626][3628224:3628229] CHIP:IN: Sending encrypted msg 0x7f531a7fabf8 with MessageCounter:1844989 to 0x00000000000004D2 (1) at monotonic time: 943923701 msec
[1641873493.836685][3628224:3628229] CHIP:EM: Flushed pending ack for MessageCounter:6727973 on exchange 32308i
[1641873494.046282][3628224:3628229] CHIP:EM: Received message of type 0x5 with protocolId (0, 1) and MessageCounter:6727974 on exchange 32309i
[1641873494.046331][3628224:3628229] CHIP:EM: Found matching exchange: 32309i, Delegate: 0x7f5310001290
[1641873494.046378][3628224:3628229] CHIP:EM: Rxd Ack; Removing MessageCounter:1844988 from Retrans Table on exchange 32309i
[1641873494.046397][3628224:3628229] CHIP:EM: Removed CHIP MessageCounter:1844988 from RetransTable on exchange 32309i
[1641873494.046465][3628224:3628229] CHIP:DMG: ReportDataMessage =
[1641873494.046485][3628224:3628229] CHIP:DMG: {
[1641873494.046499][3628224:3628229] CHIP:DMG: 	AttributeReportIBs =
[1641873494.046523][3628224:3628229] CHIP:DMG: 	[
[1641873494.046541][3628224:3628229] CHIP:DMG: 		AttributeReportIB =
[1641873494.046566][3628224:3628229] CHIP:DMG: 		{
[1641873494.046582][3628224:3628229] CHIP:DMG: 			AttributeDataIB =
[1641873494.046602][3628224:3628229] CHIP:DMG: 			{
[1641873494.046621][3628224:3628229] CHIP:DMG: 				DataVersion = 0x0,
[1641873494.046641][3628224:3628229] CHIP:DMG: 				AttributePathIB =
[1641873494.046662][3628224:3628229] CHIP:DMG: 				{
[1641873494.046682][3628224:3628229] CHIP:DMG: 					Endpoint = 0x1,
[1641873494.046701][3628224:3628229] CHIP:DMG: 					Cluster = 0x50f,
[1641873494.046726][3628224:3628229] CHIP:DMG: 					Attribute = 0x0000_0023,
[1641873494.046741][3628224:3628229] CHIP:DMG: 				}
[1641873494.046760][3628224:3628229] CHIP:DMG: 					
[1641873494.046778][3628224:3628229] CHIP:DMG: 					Data = [
[1641873494.046797][3628224:3628229] CHIP:DMG: 						
[1641873494.046816][3628224:3628229] CHIP:DMG: 					],
[1641873494.046835][3628224:3628229] CHIP:DMG: 			},
[1641873494.046860][3628224:3628229] CHIP:DMG: 			
[1641873494.046875][3628224:3628229] CHIP:DMG: 		},
[1641873494.046908][3628224:3628229] CHIP:DMG: 		
[1641873494.046923][3628224:3628229] CHIP:DMG: 		AttributeReportIB =
[1641873494.046950][3628224:3628229] CHIP:DMG: 		{
[1641873494.046966][3628224:3628229] CHIP:DMG: 			AttributeDataIB =
[1641873494.046989][3628224:3628229] CHIP:DMG: 			{
[1641873494.047008][3628224:3628229] CHIP:DMG: 				DataVersion = 0x0,
[1641873494.047027][3628224:3628229] CHIP:DMG: 				AttributePathIB =
[1641873494.047046][3628224:3628229] CHIP:DMG: 				{
[1641873494.047066][3628224:3628229] CHIP:DMG: 					Endpoint = 0x1,
[1641873494.047086][3628224:3628229] CHIP:DMG: 					Cluster = 0x50f,
[1641873494.047105][3628224:3628229] CHIP:DMG: 					Attribute = 0x0000_0023,
[1641873494.047124][3628224:3628229] CHIP:DMG: 					ListIndex = Null,
[1641873494.047142][3628224:3628229] CHIP:DMG: 				}
[1641873494.047164][3628224:3628229] CHIP:DMG: 					
[1641873494.047182][3628224:3628229] CHIP:DMG: 					Data = 
[1641873494.047202][3628224:3628229] CHIP:DMG: 					{
[1641873494.047223][3628224:3628229] CHIP:DMG: 						0x1 = NULL
[1641873494.047250][3628224:3628229] CHIP:DMG: 						0x4 = NULL
[1641873494.047270][3628224:3628229] CHIP:DMG: 						0x7 = NULL
[1641873494.047291][3628224:3628229] CHIP:DMG: 						0xa = [
[1641873494.047318][3628224:3628229] CHIP:DMG: 							1, 2, 
[1641873494.047338][3628224:3628229] CHIP:DMG: 						],
[1641873494.047357][3628224:3628229] CHIP:DMG: 					},
[1641873494.047375][3628224:3628229] CHIP:DMG: 			},
[1641873494.047403][3628224:3628229] CHIP:DMG: 			
[1641873494.047420][3628224:3628229] CHIP:DMG: 		},
[1641873494.047454][3628224:3628229] CHIP:DMG: 		
[1641873494.047469][3628224:3628229] CHIP:DMG: 	],
[1641873494.047502][3628224:3628229] CHIP:DMG: 	
[1641873494.047519][3628224:3628229] CHIP:DMG: 	SuppressResponse = true, 
[1641873494.047535][3628224:3628229] CHIP:DMG: }
[1641873494.047802][3628224:3628229] CHIP:TOO:  ***** Test Failure: listNullablesAndOptionalsStruct[0].nullableList expected to be null but isn't

[1641873494.047866][3628224:3628229] CHIP:EM: Sending Standalone Ack for MessageCounter:6727974 on exchange 32309i
[1641873494.047906][3628224:3628229] CHIP:IN: Prepared secure message 0x7f531a7fabf8 to 0x00000000000004D2 (1)  of type 0x10 and protocolId (0, 0) on exchange 32309i with MessageCounter:1844990.
[1641873494.047932][3628224:3628229] CHIP:IN: Sending encrypted msg 0x7f531a7fabf8 with MessageCounter:1844990 to 0x00000000000004D2 (1) at monotonic time: 943923912 msec
[1641873494.048056][3628224:3628229] CHIP:EM: Flushed pending ack for MessageCounter:6727974 on exchange 32309i
[1641873494.048260][3628224:3628224] CHIP:-: ../../commands/tests/TestCommand.cpp:85: CHIP Error 0x000000AC: Internal error at ../../commands/common/CHIPCommand.cpp:59
[1641873494.048302][3628224:3628224] CHIP:TOO: Run command failure: ../../commands/tests/TestCommand.cpp:85: CHIP Error 0x000000AC: Internal error
[1641873494.051230][3628224:3628224] CHIP:SPT: VerifyOrDie failure at ../../third_party/connectedhomeip/src/inet/InetLayer.h:121: sEndPointPool.Allocated() == 0
'''

 #### Proposed Solution
fix.

### LINKED ISSUE #13435: Test cluster test 353 fails on M5
#### Problem
[1641873968.083197][3638784:3638790] CHIP:TOO:  ***** Test Step 353 : Read attribute NULLABLE_CHAR_STRING Default Value

[1641873968.083244][3638784:3638790] CHIP:DMG: SendReadRequest ReadClient[0x7f7d38002780]: Sending Read Request
[1641873968.083308][3638784:3638790] CHIP:IN: Prepared secure message 0x55d22d4e9488 to 0x00000000000004D2 (1)  of type 0x2 and protocolId (0, 1) on exchange 41751i with MessageCounter:11491482.
[1641873968.083338][3638784:3638790] CHIP:IN: Sending encrypted msg 0x55d22d4e9488 with MessageCounter:11491482 to 0x00000000000004D2 (1) at monotonic time: 944397948 msec
[1641873968.083466][3638784:3638790] CHIP:DMG: MoveToState ReadClient[0x7f7d38002780]: Moving to [AwaitingIn]
[1641873968.083517][3638784:3638790] CHIP:EM: Sending Standalone Ack for MessageCounter:7377265 on exchange 41750i
[1641873968.083553][3638784:3638790] CHIP:IN: Prepared secure message 0x7f7d3fffdbf8 to 0x00000000000004D2 (1)  of type 0x10 and protocolId (0, 0) on exchange 41750i with MessageCounter:11491483.
[1641873968.083578][3638784:3638790] CHIP:IN: Sending encrypted msg 0x7f7d3fffdbf8 with MessageCounter:11491483 to 0x00000000000004D2 (1) at monotonic time: 944397948 msec
[1641873968.083636][3638784:3638790] CHIP:EM: Flushed pending ack for MessageCounter:7377265 on exchange 41750i
[1641873968.235106][3638784:3638790] CHIP:EM: Received message of type 0x5 with protocolId (0, 1) and MessageCounter:7377266 on exchange 41751i
[1641873968.235149][3638784:3638790] CHIP:EM: Found matching exchange: 41751i, Delegate: 0x7f7d38002780
[1641873968.235216][3638784:3638790] CHIP:EM: Rxd Ack; Removing MessageCounter:11491482 from Retrans Table on exchange 41751i
[1641873968.235234][3638784:3638790] CHIP:EM: Removed CHIP MessageCounter:11491482 from RetransTable on exchange 41751i
[1641873968.235298][3638784:3638790] CHIP:DMG: ReportDataMessage =
[1641873968.235318][3638784:3638790] CHIP:DMG: {
[1641873968.235331][3638784:3638790] CHIP:DMG: 	AttributeReportIBs =
[1641873968.235356][3638784:3638790] CHIP:DMG: 	[
[1641873968.235386][3638784:3638790] CHIP:DMG: 		AttributeReportIB =
[1641873968.235419][3638784:3638790] CHIP:DMG: 		{
[1641873968.235443][3638784:3638790] CHIP:DMG: 			AttributeDataIB =
[1641873968.235465][3638784:3638790] CHIP:DMG: 			{
[1641873968.235494][3638784:3638790] CHIP:DMG: 				DataVersion = 0x0,
[1641873968.235519][3638784:3638790] CHIP:DMG: 				AttributePathIB =
[1641873968.235536][3638784:3638790] CHIP:DMG: 				{
[1641873968.235553][3638784:3638790] CHIP:DMG: 					Endpoint = 0x1,
[1641873968.235584][3638784:3638790] CHIP:DMG: 					Cluster = 0x50f,
[1641873968.235606][3638784:3638790] CHIP:DMG: 					Attribute = 0x0000_801E,
[1641873968.235626][3638784:3638790] CHIP:DMG: 				}
[1641873968.235648][3638784:3638790] CHIP:DMG: 					
[1641873968.235670][3638784:3638790] CHIP:DMG: 					Data = "☉T☉", 
[1641873968.235688][3638784:3638790] CHIP:DMG: 			},
[1641873968.235712][3638784:3638790] CHIP:DMG: 			
[1641873968.235728][3638784:3638790] CHIP:DMG: 		},
[1641873968.235752][3638784:3638790] CHIP:DMG: 		
[1641873968.235767][3638784:3638790] CHIP:DMG: 	],
[1641873968.235791][3638784:3638790] CHIP:DMG: 	
[1641873968.235807][3638784:3638790] CHIP:DMG: 	SuppressResponse = true, 
[1641873968.235826][3638784:3638790] CHIP:DMG: }
[1641873968.235948][3638784:3638790] CHIP:TOO:  ***** Test Failure: nullableCharString.Value() value mismatch, expected '' but got '☉T☉'

 #### Proposed Solution
<suggested fix, suggested enhancement>

### PR DESCRIPTION
**Pull request by cecille**
#### Problem
The test assumes that we start with the default values, which means
the test will fail the second time around. This fixes that.
Fixes #13434
Fixes #13435

#### Change overview
Adds an attribute reset to the Test command that is run at the start of the test.

#### Testing
Ran TestCluster tests using chip-tool 2x on linux and M5.

### CODE REVIEW

**Review by mspang — APPROVED** [review]

**Review by tcarmelveilleux — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]

File: src/app/clusters/test-cluster-server/test-cluster-server.cpp [hunk 1]
```diff
@@ -411,6 +411,43 @@ CHIP_ERROR TestAttrAccess::WriteStructAttribute(AttributeValueDecoder & aDecoder
...
+        gListUint8Data[i] = 0;
+        gListOctetStringData[i].SetLength(0);
+        gListOperationalCert[i].SetLength(0);
+        listStructOctetStringData[i].fabricIndex     = 0;
+        listStructOctetStringData[i].operationalCert = ByteSpan();
+        gSimpleEnums[i]                              = SimpleEnum::kUnspecified;
+    }
+    gSimpleEnumCount = 0;
+
+    gStructAttributeValue.a = 0;
```
Comment (mrjerryjohns) [inline src/app/clusters/test-cluster-server/test-cluster-server.cpp:427]: Argh...we shouldn't need to do this given support for initialization to defaults went in recently, but for some reason, some of the structs got missed in that I think.

@bzbarsky-apple FYI

**Review by mrjerryjohns — APPROVED** [review]

File: src/app/clusters/test-cluster-server/test-cluster-server.cpp (hunk 1 above)
Comment (mrjerryjohns) [reply src/app/clusters/test-cluster-server/test-cluster-server.cpp:427]: i.e the ideal prescription here would be to just do:

```
gStructAttributeValue = Structs::SimpleStruct::Type()
```

Comment (andy31415) [reply src/app/clusters/test-cluster-server/test-cluster-server.cpp:427]: I think this would be handled by a separate PR from Boris. Lets not hold up this PR on a dependency.

**Comment by andy31415** [comment]
fast track: small delta, test code, lots of checkmarks, sufficient time for cross  timezone review passed.
