### PR TITLE
tv-casting-app: Handle uncaught exceptions before JNI crashes app and make iOS discoverCommissioners API callback based

### LINKED ISSUE #24895: [BUG] android/tv-casting-app: Unhandled exceptions in client code lead to app crash
### Reproduction steps

If one of the handlers in the tv-casting app for android, throws an exception that it does not handle, it leads to the exception being passed to JNI which crashes the application. This can be tested y temporarily adding a throw new RuntimeException(dummy exc) call in one of the handlers.

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

eaa747668f9fda13e443dfac54b00fd185c9b685

### Platform

android

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sharadb-amazon**
Fixes https://github.com/project-chip/connectedhomeip/issues/24895 and https://github.com/project-chip/connectedhomeip/issues/24894

### Problems fixed
1. If one of the handlers in the tv-casting app for android, throws an exception that it does not handle, it leads to the exception being passed to JNI which crashes the application. This can be tested y temporarily adding a throw new RuntimeException(dummy exc) call in one of the handlers.
2. In the darwin tv-casting-app, the discoverCommissioners API call must be followed by a getDiscoveredCommissioners call after a certain period of time. This is not ideal because the wait time is non-deterministic and leads to the implementation of polling behaviour on the client side. Change the API to be callback based so that the client is called whenever a new commissioner is discovered.

### Testing
Tested with the android and iOS tv-casting-apps

### CODE REVIEW

File: examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/SuccessCallback.java [hunk 1]
```diff
@@ -17,6 +17,18 @@
...
+
+public abstract class SuccessCallback<R> {
+  private static final String TAG = SuccessCallback.class.getSimpleName();
+
+  public abstract void handle(R response);
+
+  public void handleInternal(R response) {
+    try {
+      handle(response);
+    } catch (Exception e) {
```
Comment (chrisdecenzo) [inline examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/SuccessCallback.java:30]: if the purpose is avoiding a crash, then should this be catching Throwable rather than Exception?

**Review by chrisdecenzo — APPROVED** [review]

File: examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/SuccessCallback.java (hunk 1 above)
Comment (sharadb-amazon) [reply examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/SuccessCallback.java]: Done

**Review by andy31415 — APPROVED** [review]
