### PR TITLE
EVSE Delegate callbacks to user application

### LINKED ISSUE #30997: [1.3] Complete EVSE delegate implementation
### Reproduction steps

This issue is to track the outstanding work in the EVSE Delegate

Implemented in PR: https://github.com/project-chip/connectedhomeip/pull/30999/
- [x] - [x] Add Callback to HW to inform it of MaxCurrentLimit
- [x] Add Callback to HW to inform it of Change in Charging Enabled / Disable state

Implemented in PR: https://github.com/project-chip/connectedhomeip/pull/31200/
- [x] Add PluggedIn / Unplugged Events
- [x] Add EnergyTransferStarted Event
- [x] Add EnergyTransferStopped Event
- [x] Add Session support (Requires EEM cluster integration)
- [x] Add Persisted Storage support for some attributes

- [x] Add Timer expiry checking to automatically stop charging/discharging

Implemented in PR 
https://github.com/project-chip/connectedhomeip/pull/31406

-[x] Update XML for EVSE to support new charging preference structures

To do:
- [ ] Implement Persisting of helper data which allows session duration, session energy charged etc to be computed

- [ ] Add Charging Preferences Support (GetTargets/SetTargets/ClearTargets) (see PR https://github.com/project-chip/connectedhomeip/pull/31407)
- [ ] Add RPC handlers into example energy management app

### Bug prevalence

N/A

### GitHub hash of the SDK that was being used

N/A

### Platform

core

### Platform Version(s)

1.3

### Type

Core SDK Performance Improvement

### Anything else?

This is an issue to track EVSE implementation for 1.3

### PR DESCRIPTION
**Pull request by jamesharrow**
Relates to #30997 - but does not fix all issues.
Raising this PR to make a small change easier to review.

- [x] Add Callback to HW to inform it of MaxCurrentLimit
- [x] Add Callback to HW to inform it of Change in Charging Enabled / Disable state

Also changed all-clusters-app & energy-management-app ZAP file to enable EVSE commands and added config-data.yaml to avoid emberAf...Command linker errors.
Sync'd files in all-clusters-app and energy-management-app where appropriate.

NOT DONE YET:
- [ ] Add PluggedIn / Unplugged Events
- [ ] Add EnergyTransferStarted Event
- [ ] Add EnergyTransferStopped Event
- [ ] Add Session support (Requires EEM cluster integration)
- [ ] Add Persisted Storage support for some attributes
- [ ] Add Timer expiry checking to automatically stop charging/discharging
- [ ] Add Charging Preferences Support (GetTargets/SetTargets/ClearTargets)

### CODE REVIEW

File: examples/all-clusters-app/all-clusters-common/include/EVSECallbacks.h [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+#pragma once
+
+namespace chip {
+namespace app {
+namespace Clusters {
+
+using namespace chip::app::Clusters::EnergyEvse;
+
+/* This callbacks mechanism is intended to allow different delegates to callback
+ * and inform the manufacturer that something has changed.
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/all-clusters-common/include/EVSECallbacks.h:28]:
```suggestion
/* This callbacks mechanism is intended to allow different delegates to
 * dispatch notifications that something has changed.
```

File: examples/all-clusters-app/all-clusters-common/src/EnergyEvseDelegateImpl.cpp [hunk 2]
```diff
@@ -199,25 +204,42 @@ Status EnergyEvseDelegate::StartDiagnostics()
     /* For EVSE manufacturers to customize */
     ChipLogProgress(AppServer, "EnergyEvseDelegate::StartDiagnostics()");
 
-    /* update SupplyState */
+    /* update SupplyState to indicate in Diagnostics mode */
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/all-clusters-common/src/EnergyEvseDelegateImpl.cpp:207]:
```suggestion
    /* update SupplyState to indicate we are now in Diagnostics mode */
```

File: examples/all-clusters-app/all-clusters-common/include/EnergyEvseDelegateImpl.h [hunk 3]
```diff
@@ -70,7 +71,7 @@ class EnergyEvseDelegate : public EnergyEvse::Delegate
 
     // -----------------------------------------------------------------
     // Internal API to allow an EVSE to change its internal state etc
-    // TODO Status HwRegisterEvseHardwareCallback(Callback);
+    Status HwRegisterEvseCallbackHandler(EVSECallbackFunc handler, intptr_t arg);
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/all-clusters-common/include/EnergyEvseDelegateImpl.h:74]: This needs to document the "you can only register one handler" limitation.

File: examples/energy-management-app/energy-management-common/energy-management-app.matter [hunk 4]
```diff
@@ -1328,15 +1328,6 @@ endpoint 1 {
...
     ram      attribute clusterRevision default = 2;
-
-    handle command GetTargetsResponse;
-    handle command Disable;
-    handle command EnableCharging;
-    handle command EnableDischarging;
-    handle command StartDiagnostics;
-    handle command SetTargets;
-    handle command GetTargets;
-    handle command ClearTargets;
```
Comment (bzbarsky-apple) [inline examples/energy-management-app/energy-management-common/energy-management-app.matter:1339]: Why are all of these being disabled?  This does not seem to be related to adding callbacks...

File: examples/energy-management-app/energy-management-common/include/EVSECallbacks.h [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+
+#pragma once
+
+namespace chip {
+namespace app {
+namespace Clusters {
+
+using namespace chip::app::Clusters::EnergyEvse;
+
+/* This callbacks mechanism is intended to allow different delegates to callback
```
Comment (bzbarsky-apple) [inline examples/energy-management-app/energy-management-common/include/EVSECallbacks.h:27]: Same comments as for all-clusters app.

File: examples/energy-management-app/energy-management-common/energy-management-app.matter (hunk 4 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-management-app.matter:1339]: For some reason a previous commit must have enabled commands in ZAP which meant that the linker was looking for emberAf...Command handlers which aren't required due to the direct handling of commands in the sdk.
Not entirely sure why this wasn't picked up before by other checkers on previous build runs.

File: examples/energy-management-app/energy-management-common/include/EVSECallbacks.h (hunk 5 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/include/EVSECallbacks.h:27]: I think I will try to remove one set of these files and change the BUILD.gn in all-clusters to reference one set of files in energy-management-common. But will do that in a future PR.

File: examples/energy-management-app/energy-management-common/energy-management-app.matter (hunk 4 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-management-app.matter:1339]: Alternatively I can leave them enabled and add empty emberAfXyzCommand handlers? Since it is confusing for people who expect to be able to turn on/off commands in ZAP? Either way probably needs to be better documented on the mechanism to instantiate command handling with this cluster.

File: examples/all-clusters-app/all-clusters-common/include/EnergyEvseDelegateImpl.h (hunk 3 above)
Comment (jamesharrow) [reply examples/all-clusters-app/all-clusters-common/include/EnergyEvseDelegateImpl.h:74]: This is sort of documented in the .cpp but added something in the .h too.

File: examples/all-clusters-app/all-clusters-common/include/EVSECallbacks.h [hunk 6]
```diff
@@ -0,0 +1,82 @@
...
+     * DeviceEnergyManagement has changed
+     */
+    DeviceEnergyManagementChanged,
+};
+
+struct EVSECbInfo
+{
+    EVSECallbackType type;
+
+    union
```
[the remark this answers is not in the document]
Comment (jamesharrow) [reply examples/all-clusters-app/all-clusters-common/include/EVSECallbacks.h:57]: Added.

File: examples/energy-management-app/energy-management-common/energy-management-app.matter (hunk 4 above)
Comment (bzbarsky-apple) [reply examples/energy-management-app/energy-management-common/energy-management-app.matter:1339]: If all the commands are handled entirely in the SDK via CommandHandlerInterface, what you want is:

1. Turn them on in ZAP, so the ZAP config matches reality.  Otherwise you get ZAP complaining about your feature map not matching your enabled command set, etc.
2. Add your cluster to `CommandHandlerInterfaceOnlyClusters` in `src/app/common/templates/config-data.yaml`.

Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-management-app.matter:1339]: ah - didn't know about that!

Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-management-app.matter]: Ok - done this change to config-data.yaml and re-enabled commands in ZAP both in energy-management and all-clusters. Then regen_all.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]
