### PR TITLE
Fix issues 20991 and 20930

### LINKED ISSUE #20991: [TC-DRLK-2.9] Door-lock Get Credential Command is returning INVALID_COMMAND .
**1.Problem**- In TC-DRLK-2.9, In Get Credential Command the value for credentialIndex in the range of  11 to 65534 is returning INVALID_COMMAND instead of NULL values.
 
 When the credentialIndex value is in the range of 1 to 10 is returning the NULL value even it is not set but if the value is between 11 to 65534 it is returning as INVALID_COMMAND instead of NULL value.

 **2. steps to reproduce**
 
> ./chip-tool doorlock clear-credential  '{ "credentialType" : 1 , "credentialIndex" : 65534 }'  1 1 --timedInteractionTimeoutMs 1000
> 
> ./chip-tool doorlock get-credential-status '{ "credentialType" : 1 , "credentialIndex" : 65534 }'  1 1 --timedInteractionTimeoutMs 1000
> 
> [1654698175.244136][5478:5483] CHIP:DMG:                                        status = 0x85 (INVALID_COMMAND),

**3.Test Environment**
App Used - lock app
Platform - Chip-tool - RPI-4, 8GB RAM
DUT - RPI-4, 8GB RAM
Network - Ethernet
commit id - 742b80e93346926435743976271ebf1362a3a85c

**4.logs**
[get credential cmd logs.txt](https://github.com/project-chip/connectedhomeip/files/9149010/get.credential.cmd.logs.txt)

### PR DESCRIPTION
**Pull request by mykrupp**
#### Problem
https://github.com/project-chip/connectedhomeip/issues/20991 https://github.com/project-chip/connectedhomeip/issues/20930

#### Change overview

- Fix issue where get credential status command  returns INVALID_COMMAND when it's supposed to send a response with null values.

- Fix issue where set credential command returns userIndex as null instead of the actual user index.

#### Testing
EFR32 platform, manual testing. Hoping to get this run against a test harness as soon as possible.

### CODE REVIEW

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 1]
```diff
@@ -553,15 +553,15 @@ void DoorLockServer::setCredentialCommandHandler(
         emberAfDoorLockClusterPrintln("[SetCredential] Credential index is out of range [endpointId=%d,credentialType=%u"
                                       ",credentialIndex=%d]",
                                       commandPath.mEndpointId, to_underlying(credentialType), credentialIndex);
-        sendSetCredentialResponse(commandObj, commandPath, DlStatus::kInvalidField, 0, nextAvailableCredentialSlot);
+        sendSetCredentialResponse(commandObj, commandPath, DlStatus::kInvalidField, userIndex.Value(), nextAvailableCredentialSlot);
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:556]: I might be missing something, but:

1.  Won't this crash if `userIndex` is null (i.e. this is an Add)?
2. If `userIndex` is not null (i.e. this is a Modify), then per spec it should be null in the response, so we should not pass its value here.

Same for a bunch of the rest of these.

Am I missing something?

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 2]
```diff
@@ -628,7 +629,7 @@ void DoorLockServer::setCredentialCommandHandler(
 
         status = createCredential(commandPath.mEndpointId, fabricIdx, sourceNodeId, credentialIndex, credentialType,
                                   existingCredential, credentialData, userIndex, userStatus, userType, createdUserIndex);
-        sendSetCredentialResponse(commandObj, commandPath, status, createdUserIndex, nextAvailableCredentialSlot);
+        sendSetCredentialResponse(commandObj, commandPath, status, userIndex.Value(), nextAvailableCredentialSlot);
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:632]: And _here_ is the one place we should return a nonzero user-index, and it should be the _output from the add_, not the input.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 1 above)
Comment (mykrupp) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:556]: I think you may have "userIndex" and and "createdUserIndex" conflated. 

The reason for issue 20930 is because 0 is hardcoded as userIndex for all these calls to sendSetCredentialResponse.

The 0 you are thinking of, which indicates to add a user is the createdUserIndex. Poor name in my opinion. You can see in createCredential, it has both a "userIndex" and a "createdUserIndex". User index indicates where in an array the user should be, and createdUserIndex indicates the operation.

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 2 above)
Comment (mykrupp) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:632]: 4.41.2. UserIndex
The user index that was created with the new credential. This SHALL be null if OperationType was Modify; otherwise, this SHALL NOT be null and SHALL provide the UserIndex created.

I see what you are saying. From reading the spec, it seems that on line 632, we should send the actual userIndex (the one used as an array index) because of 4.41.2

But I guess 4.41.2 indicates that this should be null for the modify response. So might need to change line 644?

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 1 above)
Comment (mykrupp) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:556]: I agree with #2. Good catch, modify should have null in the response. But I think the rest should be passed the actual userIndex. That seems to be causing issue 20930

Comment (bzbarsky-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:556]: As far as I can tell from the spec the way this command works is:

1. For a Modify, there is an incoming userIndex.  In this case the result must not have a userIndex.
2. For an Add, there may or may not be an incoming userIndex, depending on whether we are adding a credential to an existing user or adding a credential along with a user.  The spec is extremely unclear about what happens in this case; see https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/5507

Given the endemic lack of responses on the spec bits, let's just implement something sane here and be done with it and the spec can follow.  I'd propose we do the following:

* For any failure, the user index in the response should be null.
* For a Modify, user index in response should be null.
* For an add to an existing user, the user index in the response should be null.
* For an add that creates a new user, the response should indicate the user index of the newly created user.

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:632]: We need to change 644, and all places where we are sending an error.  

The only places we should have a nonzero user index is on line 632.   And there we should only have a nonzero value if we actually created a user.  And when we create a user, I would expect `createdUserIndex` to be the index we created it at....

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:556]: > User index indicates where in an array the user should be, and createdUserIndex indicates the operation.

No, createdUserIndex does not indicate the operation.  It's an outparam that gets set to the index where the user is actually created.

Comment (mykrupp) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:556]: Oh I see. I misinterpreted createdUserIndex. operationType determines the operation.

Comment (mykrupp) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:556]: I agree with your approach. I didn't consider the case of adding a credential along with a user. With manual testing, I usually test creating a user, then adding a credential to it afterwards.

What I am implementing:
- All failures result as null for userIndex
- For modify, userIndex responds as null
- **Clear user returns userIndex** let me know what you think of this one. Seems sane to me.

The last 2 bullets should be taken care of by changing line 632 to 
        sendSetCredentialResponse(commandObj, commandPath, status, userIndex.Value(), nextAvailableCredentialSlot);

Comment (bzbarsky-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp]: > Clear credential returns userIndex let me know what you think of this one. Seems sane to me.

You mean the "Clear Credential" command?  That returns a status response....

Or do you mean something else?

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 3]
```diff
@@ -660,7 +661,7 @@ void DoorLockServer::setCredentialCommandHandler(
     case DlDataOperationType::kClear:
     default:
         // appclusters, 5.2.4.40: set credential command supports only Add and Modify operational type.
-        sendSetCredentialResponse(commandObj, commandPath, DlStatus::kInvalidField, 0, nextAvailableCredentialSlot);
+        sendSetCredentialResponse(commandObj, commandPath, DlStatus::kInvalidField, userIndex.Value(), nextAvailableCredentialSlot);
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:664]: This doesn't make sense.  We're sending an error response here...

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 4]
```diff
@@ -628,7 +628,8 @@ void DoorLockServer::setCredentialCommandHandler(
 
         status = createCredential(commandPath.mEndpointId, fabricIdx, sourceNodeId, credentialIndex, credentialType,
                                   existingCredential, credentialData, userIndex, userStatus, userType, createdUserIndex);
-        sendSetCredentialResponse(commandObj, commandPath, status, createdUserIndex, nextAvailableCredentialSlot);
+
+        sendSetCredentialResponse(commandObj, commandPath, status, userIndex.Value(), nextAvailableCredentialSlot);
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:632]: This should be sending `createdUserIndex` like it used to, no?

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 5]
```diff
@@ -718,6 +715,16 @@ void DoorLockServer::getCredentialStatusCommandHandler(chip::app::CommandHandler
         }
     }
 
+    sendGetCredentialStatusResponse(commandObj, commandPath, credentialType, credentialIndex, userIndexWithCredential,
+                                    credentialInfo, credentialExists);
+}
+
+void DoorLockServer::sendGetCredentialStatusResponse(chip::app::CommandHandler * commandObj,
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:722]:
```suggestion
void DoorLockServer::sendGetCredentialResponse(chip::app::CommandHandler * commandObj,
```

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 3 above)
Comment (mykrupp) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:664]: Oh. It was not clear to me that is an error response. Just reread the comment. I will put this one back as 0.

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 5 above)
Comment (mykrupp) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:722]: Adding this one.

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 4 above)
Comment (mykrupp) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:632]: You're right, it does make mores sense to use the out param here.

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 1 above)
Comment (mykrupp) [reply src/app/clusters/door-lock-server/door-lock-server.cpp]: Sorry what I meant here is that clear credential should return a **credential** index in the status response rather than null. 

Based on your comment, I see now that clear credential is supposed to be an error.

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 3 above)
Comment (bzbarsky-apple) [reply src/app/clusters/door-lock-server/door-lock-server.cpp]: > It was not clear to me that is an error response.

See the status: `DlStatus::kInvalidField`

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@mykrupp Now the `DL_UsersAndCredentials` test is failing, presumably because it's wrong....

**Comment by mykrupp** [comment]
I tracked down the test that's failing. It's expecting that the reading of a "ProgrammingPin" credential fails.

    - label: "Reading PIN credential with index 0 fails"
      command: "GetCredentialStatus"
      arguments:
          values:
              - name: "credential"
                value: { CredentialType: 1, CredentialIndex: 0 }
      response:
          error: INVALID_COMMAND
          
I don't see this implemented in getCredentialStatusCommandHandler. @Morozov-5F what is going on here?

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 6]
```diff
@@ -680,17 +681,13 @@ void DoorLockServer::getCredentialStatusCommandHandler(chip::app::CommandHandler
...
     uint16_t maxNumberOfCredentials = 0;
+    EmberAfPluginDoorLockCredentialInfo credentialInfo;
     if (!credentialIndexValid(commandPath.mEndpointId, credentialType, credentialIndex, maxNumberOfCredentials))
     {
-        emberAfDoorLockClusterPrintln("[GetCredentialStatus] Credential index is out of range "
-                                      "[endpointId=%d,credentialType=%u,credentialIndex=%d,maxNumberOfCredentials=%d]",
-                                      commandPath.mEndpointId, to_underlying(credentialType), credentialIndex,
-                                      maxNumberOfCredentials);
-        emberAfSendImmediateDefaultResponse(EMBER_ZCL_STATUS_INVALID_COMMAND);
+        sendGetCredentialResponse(commandObj, commandPath, credentialType, credentialIndex, 0, credentialInfo, false);
```
Comment (selissia) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:687]: Should credentialInfo be initialized by this point?

**Review by selissia — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
> I guess it shouldn't be expecting INVALID_COMMAND

Right, in the new setup wouldn't this respond with a success, with a "Get Credential Status Response" that has `CredentialExists` set to `false`?

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 6 above)
Comment (mykrupp) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:687]: Currently credential info is initialized by emberAfPluginDoorLockGetCredential with a valid index. 

Now that we want to return a failure response instead of INVALID_COMMAND, maybe we should look at initializing credentialInfo with some default values so it can be safely passed from function to function

Comment (Morozov-5F) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:687]: Maybe the easier change would be to change the `credentialInfo`'s parameter type in `sendGetCredentialResponse` to `Optional<EmberAfPluginDoorLockCredentialInfo>`? Or maybe to just `EmberAfPluginDoorLockCredentialInfo *` and pass a `nullptr` in case we don't have any info?

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 7]
```diff
@@ -718,6 +715,15 @@ void DoorLockServer::getCredentialStatusCommandHandler(chip::app::CommandHandler
...
     }
 
+    sendGetCredentialResponse(commandObj, commandPath, credentialType, credentialIndex, userIndexWithCredential, credentialInfo,
+                              credentialExists);
+}
+
+void DoorLockServer::sendGetCredentialResponse(chip::app::CommandHandler * commandObj,
+                                               const chip::app::ConcreteCommandPath & commandPath, DlCredentialType credentialType,
+                                               uint16_t credentialIndex, uint16_t userIndexWithCredential,
+                                               EmberAfPluginDoorLockCredentialInfo credentialInfo, bool credentialExists)
```
Comment (Morozov-5F) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:725]: Please take a look at my comment above about making this parameter either `Optional` or a regular pointer. I think we need to do that anyway as copying the whole structure is a bit expensive.

**Review by Morozov-5F — APPROVED** [review]
Looks great, thank you! I've added just a couple of thoughts that might help.

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 7 above)
Comment (mykrupp) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:725]: That's a good point. I think a pointer would work well here. Sending a null for the error cases i.e. when credentialIndex is invalid sounds good to me. I'll look into the implications of making it optional as well. I'll update this, thank you.

Comment (mykrupp) [reply src/app/clusters/door-lock-server/door-lock-server.cpp]: I changed the function signature to take a pointer, and am now passing null in the error case.

File: src/app/tests/suites/tests.js [hunk 8]
```diff
@@ -838,8 +838,7 @@ function getTests() {
         "TestArmFailSafe",
         "TestFanControl",
         "TestAccessControlConstraints",
-        "TestLevelControlWithOnOffDependency",
-        "TestCommissioningWindow",
```
Comment (bzbarsky-apple) [inline src/app/tests/suites/tests.js:842]: Why are you removing TestCommissioningWindow?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/tests/suites/tests.js [hunk 9]
```diff
@@ -846,7 +846,7 @@ function getTests() {
         "TestFanControl",
         "TestAccessControlConstraints",
         "TestLevelControlWithOnOffDependency",
-        "TestCommissioningWindow",
+        "TestCommissioningWindow"
```
Comment (bzbarsky-apple) [inline src/app/tests/suites/tests.js:849]:
```suggestion
        "TestCommissioningWindow",
```

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking, given comments are resolved, and we need to either approve, or deny this tonight.

File: src/app/tests/suites/tests.js [hunk 10]
```diff
@@ -864,15 +864,15 @@ function getTests() {
     ];
 
     const DoorLock = [
-        "DL_UsersAndCredentials",
+        //"DL_UsersAndCredentials", TODO: This test is not aligned with spec
```
Comment (woody-apple) [inline src/app/tests/suites/tests.js:867]: Filing an issue for this

File: src/app/tests/suites/tests.js [hunk 11]
```diff
@@ -864,15 +864,15 @@ function getTests() {
...
         "DL_LockUnlock",
         "DL_Schedules",
         "Test_TC_DRLK_2_2",
         "Test_TC_DRLK_2_3",
         "Test_TC_DRLK_2_4",
         "Test_TC_DRLK_2_5",
         "Test_TC_DRLK_2_7",
-        "Test_TC_DRLK_2_9",
+        //"Test_TC_DRLK_2_9", TODO: This test is not aligned with spec
```
Comment (woody-apple) [inline src/app/tests/suites/tests.js:875]: Filing an issue for this

**Review by woody-apple — APPROVED** [review]

File: src/app/tests/suites/tests.js (hunk 11 above)
Comment (bzbarsky-apple) [inline src/app/tests/suites/tests.js:875]: Please make sure there is a follow-up to align this YAML with the test plan, at least, and re-enable it here.

**Review by bzbarsky-apple — APPROVED** [review]
