### PR TITLE
[example] Add rendezvous session to nrf apps

### LINKED ISSUE #2902: Rendezvous over BLE is not working in ESP32 wifi-echo example
#### Problem
`RendezvousDeviceDelegate` is failing to initialize in ESP32 example app. The error is coming from `BLE::Init()` call. I added some debug logs and this is where it's failing

```
BLE Init: has descriminator 0, conn obj 0
BLE transport init returned 4000047
E (1281) rendezvous-devicedelegate: RendezvousDeviceDelegate Init failure: Error 4000047 (0x003D092F)
```

```
CHIP_ERROR BLE::Init(RendezvousSessionDelegate * delegate, const RendezvousParameters & params)
{
    CHIP_ERROR err      = CHIP_NO_ERROR;
    BleLayer * bleLayer = params.GetBleLayer();

    VerifyOrExit(mState == State::kNotReady, err = CHIP_ERROR_INCORRECT_STATE);
    VerifyOrExit(bleLayer, err = CHIP_ERROR_INCORRECT_STATE);

    mDelegate = delegate;

    mBleLayer                           = bleLayer;
    mBleLayer->mAppState                = reinterpret_cast<void *>(this);
    mBleLayer->OnChipBleConnectReceived = OnNewConnection;

    printf("BLE Init: has descriminator %d, conn obj %d\n", params.HasDiscriminator(), params.HasConnectionObject());
    if (params.HasDiscriminator())
    {
        err = DelegateConnection(params.GetDiscriminator());
        printf("DelegateConnection ret %d\n", err);
    }
    else if (params.HasConnectionObject())
    {
        err = InitInternal(params.GetConnectionObject());
        printf("InitInternal ret %d\n", err);
    }
    else
    {
        err = CHIP_ERROR_INVALID_ARGUMENT;
    }
```

So, params doesn't have discriminator and connection object. If I change the last else condition to return `CHIP_NO_ERROR`, the Rendezvous flow starts working. But, that doesn't seem like the correct solution.

 #### Proposed Solution
Analyze and fix the issue.

### PR DESCRIPTION
**Pull request by gjc13**
#### Problem
The BLE connection handler in nrf apps are not using the SPAKE secure session. 

 #### Summary of Changes

- Add secure session handler to the nrf app.
- Modify the initialization flow of `RendezvousSession` to reduce the use of heap.

Also fixes https://github.com/project-chip/connectedhomeip/issues/2902

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Review by rwalker-apple — APPROVED** [review]

**Comment by rwalker-apple** [comment]
rebased

**Comment by rwalker-apple** [comment]
@gjc13 builds failing...

**Review by rwalker-apple — CHANGES_REQUESTED** [review]
please address build issues

**Comment by erjiaqing** [comment]
We need to bypass the pairing procedure, or datamodel messages cannot be accpeted.

**Comment by gjc13** [comment]
> We need to bypass the pairing procedure, or datamodel messages cannot be accpeted.

The datamodel message handling part remains the same using the test key. You can manually set the Thread network use the OpenThread cli to by pass the network provisioning.

**Comment by rwalker-apple** [comment]
@gjc13 I think this may need a rebase to address the Cirque failures.  I rebased for you, but I think you may have overwritten that.

**Comment by rwalker-apple** [comment]
> @gjc13 I think this may need a rebase to address the Cirque failures. I rebased for you, but I think you may have overwritten that.

nevermind, looks like another Cirque issue.  @erjiaqing @yunhanw-google can you guys have a look?

**Comment by gjc13** [comment]
> > @gjc13 I think this may need a rebase to address the Cirque failures. I rebased for you, but I think you may have overwritten that.
> 
> nevermind, looks like another issue. @erjiaqing @yunhanw-google can you guys have a look to verify it's not Cirque just in case?

I've identified the issue and just added a bypass for the secure session.

**Review by rwalker-apple — APPROVED** [review]

File: examples/common/chip-app-server/RendezvousServer.cpp [hunk 1]
```diff
@@ -0,0 +1,101 @@
+#include "RendezvousServer.h"
```
Comment (rwalker-apple) [inline examples/common/chip-app-server/RendezvousServer.cpp:1]: why isn't this code finding its way into a CHIP library?

File: src/test_driver/linux-cirque/OnOffClusterTest.sh [hunk 2]
```diff
@@ -39,7 +39,7 @@ function build_chip_lighting() {
     source "$REPO_DIR/scripts/activate.sh" >/dev/null
     set -x
     cd "$chip_light_dir"
-    gn gen out/debug >/dev/null
+    gn gen out/debug --args='bypass_rendezvous=true' >/dev/null
```
Comment (rwalker-apple) [inline src/test_driver/linux-cirque/OnOffClusterTest.sh:42]: this looks like one of the few places RendezvousServer is being exercised by CI.  if it's turned off here, where is it being tested?

**Comment by rwalker-apple** [comment]
> > > @gjc13 I think this may need a rebase to address the Cirque failures. I rebased for you, but I think you may have overwritten that.
> > 
> > 
> > nevermind, looks like another issue. @erjiaqing @yunhanw-google can you guys have a look to verify it's not Cirque just in case?
> 
> I've identified the issue and just added a bypass for the secure session.

awesome, but have you just disabled any testing of the code you've added?

File: examples/common/chip-app-server/RendezvousServer.cpp (hunk 1 above)
Comment (gjc13) [reply examples/common/chip-app-server/RendezvousServer.cpp:1]: Currently wifi and Thread are sending their network credentials in different format. Wifi is `$ssid:$psk` in text format while Thread the network dataset in binary format.

I believe neither will be the final design for network provisioning and the D&S guys are working on the final network provision profile so we may keep those code here until that general network provision profile is implemented.

File: src/test_driver/linux-cirque/OnOffClusterTest.sh (hunk 2 above)
Comment (gjc13) [reply src/test_driver/linux-cirque/OnOffClusterTest.sh:42]: The RendezvousServer has never been tested. In the cirque tests we always manually set the Thread network. Moreover the rendezvous code can only work on BLE before and after the PR so it cannot be tested in the simulation CI which now only supports IP network.

**Comment by pan-apple** [comment]
LGTM
CC: @vivien-apple

File: src/transport/RendezvousSession.cpp [hunk 3]
```diff
@@ -29,10 +29,11 @@ static const char * kSpake2pKeyExchangeSalt        = "SPAKE2P Key Exchange Salt"
 
 namespace chip {
 
-CHIP_ERROR RendezvousSession::Init()
+CHIP_ERROR RendezvousSession::Init(const RendezvousParameters & params)
 {
     CHIP_ERROR err = CHIP_NO_ERROR;
 
+    mParams = params;
```
Comment (vivien-apple) [inline src/transport/RendezvousSession.cpp:36]: Before the SetupPINCode was enforced by making sure the constructor receive something. Can we add a VerifyOrExit check with a HasSetupPINCode method in the RendezvousParameters ?
Also we can probably check that the value is not 0 since this one means the accessory is already paired.

**Review by vivien-apple — APPROVED** [review]

File: src/transport/RendezvousSession.cpp (hunk 3 above)
Comment (gjc13) [reply src/transport/RendezvousSession.cpp:36]: Oh I don't know pincode 0 means already paired, thanks for pointing out.

File: src/test_driver/linux-cirque/OnOffClusterTest.sh (hunk 2 above)
Comment (andy31415) [reply src/test_driver/linux-cirque/OnOffClusterTest.sh:42]: Should we add a GH issue to track this? Or is this nothing that can be done (i.e. CI simulation simply cannot do BLE?)

if there is nothing to be done, some documentation would be nice, maybe where the flag is defined.

File: examples/common/chip-app-server/Server.cpp [hunk 4]
```diff
@@ -195,21 +108,28 @@ void InitServer()
 {
     CHIP_ERROR err = CHIP_NO_ERROR;
     Optional<Transport::PeerAddress> peer(Transport::Type::kUndefined);
+#ifndef BYPASS_RENDEZVOUS
```
Comment (andy31415) [inline examples/common/chip-app-server/Server.cpp:111]: Could we place this together with the code below (eventually within {} if the sucessorexit forces parameter declaration)?

it would make it easier to read if code is localized. We can also split it into a separate function.
It looks like pinCode is also only needed for rendezvous.

File: src/test_driver/linux-cirque/OnOffClusterTest.sh (hunk 2 above)
Comment (rwalker-apple) [reply src/test_driver/linux-cirque/OnOffClusterTest.sh:42]: @gjc13 perhaps instead of a compile-time flag, you can do a runtime check.  I.e. if the Thread network has already been set, there is no need for the Rendezvous server to be exercised this way?

Comment (gjc13) [reply src/test_driver/linux-cirque/OnOffClusterTest.sh:42]: In fact we cannot since in the cirque test we still set the Thread network after the server process is launched.

File: examples/common/chip-app-server/RendezvousServer.cpp [hunk 5]
```diff
@@ -0,0 +1,101 @@
...
+}
+
+void RendezvousServer::OnRendezvousConnectionClosed()
+{
+    ChipLogProgress(AppServer, "OnRendezvousConnectionClosed");
+}
+
+void RendezvousServer::OnRendezvousMessageReceived(PacketBuffer * buffer)
+{
+#if CHIP_ENABLE_OPENTHREAD
```
Comment (bukepo) [inline examples/common/chip-app-server/RendezvousServer.cpp:37]: better to implement a simple Thread operational dataset encoder instead.

File: examples/common/chip-app-server/RendezvousServer.cpp (hunk 1 above)
Comment (bukepo) [inline examples/common/chip-app-server/RendezvousServer.cpp:1]: Missing license header.

**Review by bukepo — APPROVED** [review]

File: examples/common/chip-app-server/RendezvousServer.cpp (hunk 1 above)
Comment (andy31415) [reply examples/common/chip-app-server/RendezvousServer.cpp:18]: I would suggest to add a GH issue and a todo here to remind us to merge the formats.

**Review by andy31415 — APPROVED** [review]
