### PR TITLE
[Fixed] OTAServerDelegate class for vendor logic

### LINKED ISSUE #2862: Implement OTA Software Update cluster (Server side)
#### Problem
The CHIP spec defines an OTA software update cluster but the SDK currently does not implement said cluster's server side logic

 #### Proposed Solution
Implement the CHIP OTA software update cluster's server side logic

### PR DESCRIPTION
**Pull request by holbrookt**
This is a resubmit of #6476 with fixes for the breakages that lead to #7534

#### Problem
Need a way to separate common code from application/vendor specific code for OTA Server Cluster, which doesn't require the developer to fork the repo.

#### Change overview
* define OTAServerDelegate class for implementing vendor OTA Server logic
* add some common logic for OTA Server Cluster commands
* add OTA Server Cluster to all-clusters-app and chip-tool
* fix AnnounceOTAServer command direction (OTA Client client node -> OTA Client server node)
* fixed logging symbols that lead to #7534 
* Fixes #2862 - Implement OTA Software Update cluster (Server side)

#### Testing
Ran `chip-tool` and `all-clusters-app` on Linux machine, confirmed that I can send `query-image` `apply-update-request` and `notify-update-applied`. The response to `apply-update-request` and `notify-update-applied` is `EMBER_ZCL_STATUS_UNSUP_COMMAND` as expected, because there is no OTAServerDelegate implemented yet. The response to `query-image` is a TLV parse failure because `CHAR_STRING` is not supported yet

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@holbrookt  - needs merge due to generated code

**Review by jmartinez-silabs — APPROVED** [review]

File: src/app/clusters/ota-server/ota-server.cpp [hunk 1]
```diff
@@ -82,5 +160,47 @@ bool emberAfOtaSoftwareUpdateServerClusterQueryImageCallback(
...
+                                        locationSpan, clientCanConsent, metadataForServer);
+    if (status != EMBER_ZCL_STATUS_SUCCESS)
+    {
+        emberAfSendImmediateDefaultResponse(status);
+    }
+
+    return true;
+}
+
+void chip::app::clusters::OTAServer::SetDelegate(chip::EndpointId endpointId, OTAServerDelegate * delegate)
```
Comment (mspang) [inline src/app/clusters/ota-server/ota-server.cpp:199]: Why are doing "using namespace chip::app::clusters" only to have to spell out the entire thing here?

Can't we put the entire file content within that namespace?

**Review by mspang — APPROVED** [review]

**Review by mspang — CHANGES_REQUESTED** [review]
Please fix the namespacing.

**Comment by holbrookt** [comment]
> Please fix the namespacing.

fixed in latest commits.

File: src/app/clusters/ota-server/ota-server.cpp (hunk 1 above)
Comment (holbrookt) [reply src/app/clusters/ota-server/ota-server.cpp]: The entire file should not be in that namespace because the `emberAf...` functions are defined in the global namespace.

But I did remove the unnecessary scopes here

**Review by mspang — APPROVED** [review]
