### PR TITLE
[build] fix linux build without OpenThread

### LINKED ISSUE #3184: Linux build broken with chip_enable_openthread=false
#### Problem
Linux target does not build successfully with chip_enable_openthread=false.

Reproducer as follows:

```
$ uname -a
Linux ubuntu 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ git clone https://github.com/project-chip/connectedhomeip
$ cd connectedhomeip
$ git checkout 41feafa5ae3aad1f6aa006f8cb65b445ff21702b
$ gn gen out --args='chip_enable_openthread=false'
$ ninja -C out
../src/platform/Linux/ThreadStackManagerImpl.h:26:10: fatal error: dbus/client/thread_api_dbus.hpp: No such file or directory
   26 | #include "dbus/client/thread_api_dbus.hpp"
```

### PR DESCRIPTION
**Pull request by gjc13**
#### Problem

The linux build fails with `chip_enable_openthread=false`.

 #### Summary of Changes

- Add `CHIP_DEVICE_CONFIG_ENABLE_THREAD` into the generated header.
- Remove unused headers in CHIPoBLE test.

 Fixes https://github.com/project-chip/connectedhomeip/issues/3184

### CODE REVIEW

**Review by bukepo — APPROVED** [review]
LGTM:+1:

**Review by mspang — APPROVED** [review]

File: src/platform/tests/TestCHIPoBLEStackMgr.cpp [hunk 1]
```diff
@@ -17,25 +17,13 @@
 
 #include "platform/internal/CHIPDeviceLayerInternal.h"
```
Comment (mspang) [inline src/platform/tests/TestCHIPoBLEStackMgr.cpp:18]: It seems this didn't work. I think Linux/CHIPDevicePlatformConfig.h needs this stanza

```
#if CHIP_ENABLE_OPENTHREAD
#define CHIP_DEVICE_CONFIG_ENABLE_THREAD 1
#endif
```

and remove the change to `BUILD.gn`

**Review by rwalker-apple — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]
