### PR TITLE
Test Event Trigger implementation for General Diagnostics Cluster

### LINKED ISSUE #18322: [TC-DGGEN-1.1] General Diagnostics--AttributeList attribute missed to list the Mandatory TestEventTriggersEnabled attribute
**Test-case ID** 
 [TC-DGGEN-1.1] Global attributes with server as DUT

**Problem:-**
As per Test-Plan, AttributeList attribute missed to list the Mandatory TestEventTriggersEnabled attribute

**expected behavior**:- TH should read mandatory attributes (values 0, 1, 8) from DUT
**actual behavior:**- TH missed to read Mandatory TestEventTriggersEnabled(8) attribute from DUT
**steps to reproduce:**-./chip-tool generaldiagnostics read attribute-list 1 0

**system configuration:-**
system configuration
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : IP and Wifi
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/25e241ebcbf11b1f63dbe25546b1f10219866ad0
Dut application: All-Clusters-app

**Chip-tool screenshot:-**
image

**Test-Plan reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/general_diagnostics.adoc#tc-dggen-1-1-global-attributes-with-server-as-dut

**Spec Reference:-**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/DiagnosticsGeneral.adoc

### PR DESCRIPTION
**Pull request by tehampson**
#### Problem
* Partially fixes #18322

#### Change overview
* Interface for TestEventTriggerDelegate

#### Testing
Untested since it is an interface header file that is added

### CODE REVIEW

File: src/controller/TestEventTriggerDelegate.h [hunk 1]
```diff
@@ -0,0 +1,69 @@
+/*
```
Comment (tehampson) [inline src/controller/TestEventTriggerDelegate.h:1]: I don't really know the best spot for this right now. I didn't think `src/platform` was any better, but based on other files it did seem like a slightly better place potentially. The only thing I think maybe be slightly better than this location is somewhere in `src/app/`. But I don't see a precedent that is a good example to follow

File: src/controller/TestEventTriggerDelegate.h [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+     *
+     * @param[out] enableKey Buffer to put the test enable key into
+     *
+     * @return CHIP_ERROR_BUFFER_TOO_SMALL the provided MutableByteSpan is not big enough.
+     */
+    virtual CHIP_ERROR GetEnableKey(MutableByteSpan enableKey) = 0;
+
+    /**
+     * Expectation is that the caller has already validated the test enable key before calling this.
+     * Configures the test event trigger based on `eventTrigger` provided.
```
Comment (tcarmelveilleux) [inline src/controller/TestEventTriggerDelegate.h:41]: Configure is not quite it. It should be `HandleTestEventTrigger`

File: src/controller/TestEventTriggerDelegate.h [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+#if 0
+// This is a lighter weight interface from General Diagnostics Cluster perspective placing all the burden on each
+// implementation to perform required validation.
+class TestEventTriggerDelegate
+{
+public:
+    virtual CHIP_ERROR ConfigureTestEventTrigger(const ByteSpan testEventKey, uint64_t eventTrigger) = 0;
+    virtual size_t ConfiguredEventTriggerCount() = 0;
+};
+#endif
```
Comment (tcarmelveilleux) [inline src/controller/TestEventTriggerDelegate.h:66]: Not sure what this is for here

Comment (tehampson) [reply src/controller/TestEventTriggerDelegate.h:66]: This comes from my design doc based mentality. This is more just showing work for this initial review of "Alternative solutions considered", that is expected to be removed if you are okay with the first approach.

It is removed in the next push

File: src/controller/TestEventTriggerDelegate.h [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+public:
+    /**
+     * This API can be used to retrieve the test enable key. The enable key is copied into `buffer`
+     * if the size is large enough.
+     *
+     * @param[out] enableKey Buffer to put the test enable key into
+     *
+     * @return CHIP_ERROR_BUFFER_TOO_SMALL the provided MutableByteSpan is not big enough.
+     */
+    virtual CHIP_ERROR GetEnableKey(MutableByteSpan enableKey) = 0;
```
[the remark this answers is not in the document]
Comment (tehampson) [reply src/controller/TestEventTriggerDelegate.h]: Sounds good. Slight change making this return a bool instead

File: src/app/TestEventTriggerDelegate.h [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+#include <stddef.h>
+#include <stdint.h>
+
+namespace chip {
+
+class TestEventTriggerDelegate
+{
+public:
+    /**
+     * Checks to see if `enableKey` provided matches value choosen by by the manufacturer.
```
Comment (bzbarsky-apple) [inline src/app/TestEventTriggerDelegate.h:30]:
```suggestion
     * Checks to see if `enableKey` provided matches value chosen by the manufacturer.
```

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/TestEventTriggerDelegate.h [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+     * @param[in] eventTrigger Event trigger to handle.
+     *
+     * @return CHIP_ERROR_INVALID_ARGUMENT when eventTrigger is not a valid test event trigger.
+     */
+    virtual CHIP_ERROR HandleEventTrigger(uint64_t eventTrigger) = 0;
+
+    /**
+     * Get the count of all configured test event triggers.
+     */
+    virtual size_t ConfiguredEventTriggerCount() const = 0;
```
Comment (tcarmelveilleux) [inline src/app/TestEventTriggerDelegate.h:49]: Let's remove this API since it is not required by any callers.

**Review by tcarmelveilleux — APPROVED** [review]

File: src/app/TestEventTriggerDelegate.h [hunk 7]
```diff
@@ -0,0 +1,52 @@
+/*
+ *    Copyright (c) 2022 Project CHIP Authors
+ *
```
Comment (andy31415) [inline src/app/TestEventTriggerDelegate.h:3]: supernit: standard license text has a ` *    All rights reserved.` right under copyright.

Mentioning it because I saw a recent PR adding it ...
