### PR TITLE
Fix the status codes returned from failed Read interactions.

### LINKED ISSUE #18343: Lack of available read handlers for a read should respond with BUSY, not RESOURCE_EXHAUSTED
#### Problem
If I do a read and get back RESOURCE_EXHAUSTED, there is no way to tell whether that's because there was another read in progress (in which case I should just retry) or whether it's because my read attempt used too many paths, filters, etc (in which case I need to change what sort of request I am sending).

 #### Proposed Solution
Use BUSY to indicate "no available read clients right now", not RESOURCE_EXHAUSTED.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Fixes https://github.com/project-chip/connectedhomeip/issues/18343

#### Problem
Status responses not following the spec.

#### Change overview
Fix to follow spec.  Need to check path counts first, because an error there should take precedence over lack of read handlers (which is transient).

#### Testing
Unit tests added to exercise the various cases.

### CODE REVIEW

**Review by tcarmelveilleux — APPROVED** [review]

File: src/app/InteractionModelEngine.cpp [hunk 1]
```diff
@@ -759,6 +759,15 @@ bool InteractionModelEngine::CanEstablishReadTransaction(const ReadHandler * apR
     size_t activeReadHandlersOnCurrentFabric = 0;
 
     // It is safe to use & here since this function will be called on current stack.
+    if (apReadHandler->GetAttributePathCount() > kReservedPathsPerReadRequest ||
+        apReadHandler->GetEventPathCount() > kReservedPathsPerReadRequest ||
+        apReadHandler->GetDataVersionFilterCount() > kReservedPathsPerReadRequest)
+    {
+        // Doesn't matter how many other reads are in progress; we are not
```
Comment (mrjerryjohns) [inline src/app/InteractionModelEngine.cpp:766]: So, this doesn't quite align with what the spec is saying:

_"If there are not enough resources to support the number of paths in the action and the number of paths in the action exceeds the number of paths that is guaranteed to be supported for a Read Interaction"_

That first bit is not being up-held here with this logic.

It's important we not alter the interpretation of the minima into a maxima at all times - that pivot'ed interpretation should only apply when we have insufficient resources to serve such a request.

Comment (bzbarsky-apple) [reply src/app/InteractionModelEngine.cpp:766]: > That first bit is not being up-held here with this logic.

I am not changing the behavior of how many paths we allow.  Right now our behavior is to only allow the spec-defined minimum, so if you send any more paths than that the read is rejected.  That's true both with my change and without it.  The only thing my change does is change which status code is reported.

Now I agree that we should allow more paths if more paths are available, especially if we don't have the maximum number of fabrics commissioned.  But that's out of scope for this PR, which is just making sure that clients can tell when they need to retry vs when retrying the same thing would be pointless...

**Review by jmartinez-silabs — APPROVED** [review]

File: src/app/InteractionModelEngine.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/InteractionModelEngine.cpp:766]: Filed https://github.com/project-chip/connectedhomeip/issues/18610 to track this.
