### PR TITLE
Fix bug in SubscribeEvent function that results in compilation failure

### LINKED ISSUE #22467: [BUG] bug in the SubscribeEvent function in CHIPCluster.h
### Reproduction steps

```bash
Reproduction steps
1. Compile matter SDK while trying to call subscribevent function

There is a bug in the SubscribeEvent function in CHIPCluster.h: https://github.com/project-chip/connectedhomeip/blob/342ba68745610b4bee23112ac56e0681d3e72067/src/controller/CHIPCluster.h#L348
While trying to use this function I get the following compilation error:
vendor/csa-iot/connectedhomeip/src/controller/CHIPCluster.h:384:16: error: no matching function for call to 'SubscribeEvent'
        return Controller::SubscribeEvent<DecodableType>(&mExchangeManager, mSession.Get().Value(), mEndpoint, onReportCb,
By changing this line of code https://github.com/project-chip/connectedhomeip/blob/342ba68745610b4bee23112ac56e0681d3e72067/src/controller/CHIPCluster.h#L369
to
auto onSubscriptionEstablishedCb = [context, subscriptionEstablishedCb](const app::ReadClient & readClient)
compilation is successful
```

### Bug prevalence

everytime

### GitHub hash of the SDK that was being used

b4505ac2a724d057791c38821b560180bc21a8ef

### Platform

ameba, android, cc13x2_cc26x2, darwin, efr32, esp32, freeRTOS, IMX8, k32w, nrf, python, raspi, vscode, windows

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by spalas1996**
#### Problem
Fix bug in SubscribeEvent function.

Fixes #22467

#### Change overview
Fix bug in SubscribeEvent function that results in compilation failure
There is a bug in the SubscribeEvent function in CHIPCluster.h: https://github.com/project-chip/connectedhomeip/blob/342ba68745610b4bee23112ac56e0681d3e72067/src/controller/CHIPCluster.h#L348
While trying to use this function I get the following compilation error:
vendor/csa-iot/connectedhomeip/src/controller/CHIPCluster.h:384:16: error: no matching function for call to 'SubscribeEvent'
        return Controller::SubscribeEvent<DecodableType>(&mExchangeManager, mSession.Get().Value(), mEndpoint, onReportCb,

By changing this line of code https://github.com/project-chip/connectedhomeip/blob/342ba68745610b4bee23112ac56e0681d3e72067/src/controller/CHIPCluster.h#L369
to
auto onSubscriptionEstablishedCb = [context, subscriptionEstablishedCb](const app::ReadClient & readClient)
compilation is successful

#### Testing
How was this tested? (at least one bullet point required)
* If no testing is required, why not? Not tested since this function is not currently used by any example. Compilation was successful with local setup that uses this function.

### CODE REVIEW

File: src/controller/CHIPCluster.h [hunk 1]
```diff
@@ -366,7 +366,7 @@ class DLL_EXPORT ClusterBase
             }
         };
 
-        auto onSubscriptionEstablishedCb = [context, subscriptionEstablishedCb]() {
+        auto onSubscriptionEstablishedCb = [context, subscriptionEstablishedCb](const app::ReadClient & readClient) {
```
Comment (tcarmelveilleux) [inline src/controller/CHIPCluster.h:369]: The readClient is unused in the scope. This should not fail to compile

**Review by andy31415 — CHANGES_REQUESTED** [review]
Please document what compile error you get and how to reproduce.

CI seems to compile this just fine for many platforms.

File: src/controller/CHIPCluster.h (hunk 1 above)
Comment (andy31415) [reply src/controller/CHIPCluster.h:369]: Maybe Controller::SubscribeAttribute requires a specific type of callback even if unused?

Either way, I would want to see the compiler error this gets. I don't see any compiler errors in CI.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/controller/CHIPCluster.h (hunk 1 above)
Comment (bzbarsky-apple) [reply src/controller/CHIPCluster.h:369]: > Maybe Controller::SubscribeAttribute requires a specific type of callback even if unused?

The callback function signature has to be right, yes.  The function will be called with certain arguments; whether it uses those arguments is not something the caller has a way to know.

>  I don't see any compiler errors in CI.

That's because this is (1) a template and (2) not called by anything in CI, so not instantiated, so there are no "does it compile?" checks, since those generally would depend on the types the template is instantiated with.

**Comment by spalas1996** [comment]
> Please document what compile error you get and how to reproduce.
> 
> CI seems to compile this just fine for many platforms.

I have updated the description. Please let me know if you have any more questions. Basically when I try to call subscribevent function and compile for amazon echo, compilation fails.

**Review by tcarmelveilleux — APPROVED** [review]

**Comment by spalas1996** [comment]
Hello @andy31415 , I have made the requested changes. Please advise on where exactly I should add the issue link https://github.com/project-chip/connectedhomeip/issues/22467 because CI seems to be failing on parsing the issue link

**Comment by bzbarsky-apple** [comment]
@spalas1996 You need "Fixes #NNNN" in that exact form in the PR description... I added that here.

**Comment by spalas1996** [comment]
> @spalas1996 You need "Fixes #NNNN" in that exact form in the PR description... I added that here.

Thanks @bzbarsky-apple

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
Accepted for v1: compile error fix.
