### PR TITLE
Fix the dnssd code that browses on both the local and srp domains

### LINKED ISSUE #32668: Fix outstanding comments for https://github.com/project-chip/connectedhomeip/pull/32631

### PR DESCRIPTION
**Pull request by nivi-apple**
- Fixes the UAF issue with the timer

- Resolves critical comments from PR #32631

Fixes: #32668

### CODE REVIEW

File: src/platform/Darwin/DnssdContexts.cpp [hunk 1]
```diff
@@ -458,27 +458,35 @@ ResolveContext::ResolveContext(void * cbContext, DnssdResolveCallback cb, chip::
...
-    protocol        = GetProtocol(cbAddressType);
-    instanceName    = instanceNameToResolve;
-    consumerCounter = std::move(consumerCounterToUse);
+    type               = ContextType::Resolve;
+    context            = cbContext;
+    callback           = cb;
+    protocol           = GetProtocol(cbAddressType);
+    instanceName       = instanceNameToResolve;
+    consumerCounter    = std::move(consumerCounterToUse);
+    hasSrpTimerStarted = false;
```
Comment (ksperling-apple) [inline src/platform/Darwin/DnssdContexts.cpp:467]: Nit: This is not needed since you've already got it initialized to false in the header.

**Review by ksperling-apple — APPROVED** [review]

File: src/platform/Darwin/DnssdContexts.cpp (hunk 1 above)
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdContexts.cpp:467]: Why is this not default-initialized in the class decl, so you don't have to do it in both constructors?

I know other members were doing things this way; that's not a reason to copy the bad pattern.

File: src/platform/Darwin/DnssdImpl.cpp [hunk 2]
```diff
@@ -144,59 +148,57 @@ std::string GetDomainFromHostName(const char * hostnameWithDomain)
...
 }
 
+/**
+ * @brief Cancels the timer that was started to wait for the resolution on the kSrpDot domain to happen.
+ *
+ * @param[in] ResolveContext The resolve context.
+ */
+void CancelSrpTimer(ResolveContext * ctx)
+{
+    DeviceLayer::SystemLayer().CancelTimer(SrpTimerExpiredCallback, reinterpret_cast<void *>(ctx));
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.cpp:195]: Why do you need the cast here?  Just passing `ctx` as the second arg should work.  Same in StartTimer....

File: src/platform/Darwin/DnssdImpl.cpp [hunk 3]
```diff
@@ -307,25 +309,37 @@ static void OnGetAddrInfo(DNSServiceRef sdRef, DNSServiceFlags flags, uint32_t i
     {
         VerifyOrReturn(sdCtx->HasAddress(), sdCtx->Finalize(kDNSServiceErr_BadState));
 
-        if (domainName.compare(kOpenThreadDot) == 0)
+        if (domainName.compare(kSrpDot) == 0)
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.cpp:312]: I think this is broken.  You can get multiple SRP results, then a non-SRP result with !kDNSServiceFlagsMoreComing, and this code will end up sitting and waiting for 250ms when it shouldn't.  I think there's some confusion here about what kDNSServiceFlagsMoreComing means.  Which is understandable, because it can be confusing.  If set, all it means is "something on this same connection has more data to deliver right now".  In our case, it could be either of the two resolves, any of the GetAddrInfo those kicked off, etc.  In particular, it does not mean "no more data coming for the args that got passed here"; it means "no more stuff I know about right this second for anything that is using this connection".

File: src/platform/Darwin/DnssdImpl.cpp [hunk 4]
```diff
@@ -307,25 +309,37 @@ static void OnGetAddrInfo(DNSServiceRef sdRef, DNSServiceFlags flags, uint32_t i
...
-            if (!sdCtx->hasOpenThreadTimerStarted)
+            if (!sdCtx->hasSrpTimerStarted)
             {
-                // Schedule a timer to allow the resolve on OpenThread domain to complete.
-                StartOpenThreadTimer(kOpenThreadTimeoutInMsec, sdCtx);
-                sdCtx->hasOpenThreadTimerStarted = true;
+                // Schedule a timer to allow the resolve on Srp domain to complete.
+                CHIP_ERROR error = StartSrpTimer(kSrpTimeoutInMsec, sdCtx);
+
+                // If the timer fails to start, finalize the context and return.
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.cpp:336]: This comment should explain _why_, not _what_.  The "what" (finalize and return) is obvious from the code below.  The question is: why is that the right thing to do?  (It is, but the comment should explain why.)

File: src/platform/Darwin/DnssdContexts.cpp [hunk 5]
```diff
@@ -560,52 +568,60 @@ void ResolveContext::DispatchSuccess()
...
+        if (key.first == interfaceIndex)
+        {
+            auto & interface = interfaces[key];
+            auto & ips       = interface.addresses;
 
-    ChipLogProgress(Discovery, "Mdns: Resolve success on interface %" PRIu32, interfaceIndex);
+            // Some interface may not have any ips, just ignore them.
+            if (ips.size() == 0)
+            {
+                return false;
```
[the remark this answers is not in the document]
Comment (nivi-apple) [reply src/platform/Darwin/DnssdContexts.cpp:591]: I didn't modify this code. :) but yes I see we need to continue to the other interfaces

File: src/platform/Darwin/DnssdImpl.cpp (hunk 4 above)
Comment (nivi-apple) [reply src/platform/Darwin/DnssdImpl.cpp:336]: will do.

File: src/platform/Darwin/DnssdContexts.cpp [hunk 6]
```diff
@@ -548,7 +555,8 @@ void ResolveContext::DispatchSuccess()
 
     for (auto & interface : interfaces)
     {
-        if (TryReportingResultsForInterfaceIndex(interface.first.first, interface.first.second))
+        auto interfaceId = interface.first.first;
+        if (TryReportingResultsForInterfaceIndex(interfaceId))
```
[the remark this answers is not in the document]
Comment (nivi-apple) [reply src/platform/Darwin/DnssdContexts.cpp:559]: The reason I couldn't add the domain here is because there are hardcoded interfaces to prioritize that do not have a domain and I have no idea what domains to use here. we need to discuss this more for me to fix this properly.

File: src/platform/Darwin/DnssdContexts.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/platform/Darwin/DnssdContexts.cpp:591]: > I didn't modify this code.

You changed the context around it, though.  Before, when there was only map entry the code was dealing with, return was correct. Now that it's trying to work with multiple map entries, returning is not correct.

So not modifying this code _is the bug_.

File: src/platform/Darwin/DnssdContexts.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/platform/Darwin/DnssdContexts.cpp:559]: My point is that the "prioritize" bits indeed can only pass in the interface id (and then walk through all the matches and call the two-arg version for each one), but the bit here should pass in both pieces.

File: src/platform/Darwin/DnssdContexts.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/platform/Darwin/DnssdContexts.cpp:467]: > i already have it defaulting to false in the class decl.

Then we shouldn't touch it in the constructor.

File: src/platform/Darwin/DnssdContexts.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (nivi-apple) [reply src/platform/Darwin/DnssdContexts.cpp:591]: yup. got that after i closley inspected the changes. it is a bug and i fixed it locally.
