### PR TITLE
Bugfix/spake2p calc tt value fix

### LINKED ISSUE #4360: Calculation of TT does not take into account the len(Context).
#### Problem
The calculation of TT in TestSPAKE2P_RFC does not take len(Context) into account.
The specification requires the len(Context) to be taken into the hash input.

 #### Proposed Solution
First put in the length of the context (in a 8-byte field) as done in SPAKE2+ protocol.

### PR DESCRIPTION
**Pull request by sujaygkulkarni-nxp**
Problem
In spake2p protocol calculation of TT does not take into account the length of context

Summary of Changes
Added context length in calculation of TT

Fixes #4360

### CODE REVIEW

**Comment by andy31415** [comment]
@sujaygkulkarni-nxp please sign the CLA for this to go to review.

**Review by rwalker-apple — COMMENTED** [review]
please re-request review once either @pan-apple or @balducci-apple have signed off

**Comment by balducci-apple** [comment]
Likely what we should do is:

1. Modify `Spake2p::Init` such that it accepts a `const uint8_t *context` and `size_t context_len`.
2. Modify `Spake2p:: InitImpl` to always start a new Hash_SHA256_stream context (and it does when the current context parameter is NULL).
3. Modify `Spake2p:: InitImpl` to `InternalHash` the input `(context, context_len)` parameters.

This will prevent mis-use by not requiring callers the need to call `InternalHash` themselves.

**Review by balducci-apple — CHANGES_REQUESTED** [review]
Likely what we should do is:

1. Modify `Spake2p::Init` such that it accepts a `const uint8_t *context` and `size_t context_len`.
2. Modify `Spake2p:: InitImpl` to always start a new Hash_SHA256_stream context (and it does when the current context parameter is NULL).
3. Modify `Spake2p:: InitImpl` to `InternalHash` the input `(context, context_len)` parameters.

This will prevent mis-use by not requiring callers the need to call `InternalHash` themselves.

**Comment by woody-apple** [comment]
ping @sujaygkulkarni-nxp , any update on this pending PR?

**Comment by sujaygkulkarni-nxp** [comment]
> ping @sujaygkulkarni-nxp , any update on this pending PR?

Hello. I see the similar changes required in transport layer also (SecurePairingSession.cpp). Will include the fix in this pull request.

**Comment by woody-apple** [comment]
@balducci-apple ?

File: src/crypto/CHIPCryptoPAL.h [hunk 1]
```diff
@@ -691,6 +692,12 @@ class Spake2p
     void * order;
     void * tempbn;
 
+    /*
+     *  Context = "SPAKE2+ Commissioning" || PBKDFParamRequest || PBKDFParamResponse
```
Comment (balducci-apple) [inline src/crypto/CHIPCryptoPAL.h:696]: Context is now Hash("CHIP PAKE V1 Commissioning" || PBKDFParamRequest || PBKDFParamResponse). Since the Spake2+ impl ingests the context during initialization, why do we need this buffer here ? Shouldn't this be attached to the SecurePairingSession ?

File: src/transport/SecurePairingSession.cpp [hunk 2]
```diff
@@ -179,12 +178,6 @@ CHIP_ERROR SecurePairingSession::Init(Optional<NodeId> myNodeId, uint16_t myKeyI
 
     VerifyOrExit(delegate != nullptr, err = CHIP_ERROR_INVALID_ARGUMENT);
 
-    err = mCommissioningHash.Begin();
```
Comment (balducci-apple) [inline src/transport/SecurePairingSession.cpp:182]: Context is now Hash("CHIP PAKE V1 Commissioning" || PBKDFParamRequest || PBKDFParamResponse). We'll still need this hash so we don't need to save PBKDFParamRequest and PBKDFParamResponse in memory while building a secure session.

File: src/transport/SecurePairingSession.cpp [hunk 3]
```diff
@@ -361,8 +358,8 @@ CHIP_ERROR SecurePairingSession::HandlePBKDFParamRequest(const PacketHeader & he
     ChipLogDetail(Ble, "Received PBKDF param request");
 
     // Update commissioning hash with the received pbkdf2 param request
-    err = mCommissioningHash.AddData(req, reqlen);
```
Comment (balducci-apple) [inline src/transport/SecurePairingSession.cpp:364]: We should keep this behaviour (hashing in the PBKDFParamRequest).

File: src/transport/SecurePairingSession.cpp [hunk 4]
```diff
@@ -413,8 +410,8 @@ CHIP_ERROR SecurePairingSession::SendPBKDFParamResponse()
     resp->SetDataLength(u16len);
 
     // Update commissioning hash with the pbkdf2 param response that's being sent.
-    err = mCommissioningHash.AddData(resp->Start(), resp->DataLength());
```
Comment (balducci-apple) [inline src/transport/SecurePairingSession.cpp:416]: We should keep this behaviour (hashing the PBKDFParamResponse)

File: src/transport/SecurePairingSession.cpp [hunk 5]
```diff
@@ -464,8 +461,8 @@ CHIP_ERROR SecurePairingSession::HandlePBKDFParamResponse(const PacketHeader & h
         VerifyOrExit(CanCastTo<uint32_t>(iterCount), err = CHIP_ERROR_INVALID_MESSAGE_LENGTH);
 
         // Update commissioning hash with the received pbkdf2 param response
-        err = mCommissioningHash.AddData(resp, resplen);
```
Comment (balducci-apple) [inline src/transport/SecurePairingSession.cpp:467]: We should keep this behaviour (hashing the PBKDFParamResponse)

File: src/transport/SecurePairingSession.cpp [hunk 6]
```diff
@@ -328,8 +325,8 @@ CHIP_ERROR SecurePairingSession::SendPBKDFParamRequest()
     req->SetDataLength(kPBKDFParamRandomNumberSize);
 
     // Update commissioning hash with the pbkdf2 param request that's being sent.
-    err = mCommissioningHash.AddData(req->Start(), req->DataLength());
```
Comment (balducci-apple) [inline src/transport/SecurePairingSession.cpp:331]: We should keep this behaviour (hashing in the PBKDFParamRequest).

File: src/transport/SecurePairingSession.cpp [hunk 7]
```diff
@@ -205,7 +198,11 @@ CHIP_ERROR SecurePairingSession::SetupSpake2p(uint32_t pbkdf2IterCount, const ui
                         sizeof(mWS), &mWS[0][0]);
     SuccessOrExit(err);
 
-    err = mSpake2p.Init(&mCommissioningHash);
+    // Form the context to be used. Context = "SPAKE2+ Commissioning" || PBKDFParamRequest || PBKDFParamResponse
+    memcpy((mSpake2p.spake_context + mSpake2p.spake_context_len), kSpake2pContext, strlen(kSpake2pContext));
+    mSpake2p.spake_context_len += strlen(kSpake2pContext);
+
+    err = mSpake2p.Init(mSpake2p.spake_context, mSpake2p.spake_context_len);
```
Comment (balducci-apple) [inline src/transport/SecurePairingSession.cpp:205]: We should keep `mCommissioningHash` and `Init` with the output digest.

**Review by balducci-apple — CHANGES_REQUESTED** [review]
Context is now Hash("CHIP PAKE V1 Commissioning" || PBKDFParamRequest || PBKDFParamResponse). Therefore we should still utilize the `mCommissioningHash` so we don't need to save these messages to memory.

File: src/transport/SecurePairingSession.cpp (hunk 3 above)
Comment (sujaygkulkarni-nxp) [reply src/transport/SecurePairingSession.cpp:364]: Instead of passing the context in chunks, it would be better to pass complete context to crypto layer. Anyway we need a place holder to keep track of the length of the context ("CHIP PAKE V1 Commissioning" || PBKDFParamRequest || PBKDFParamResponse).

File: src/crypto/CHIPCryptoPAL.h (hunk 1 above)
Comment (sujaygkulkarni-nxp) [reply src/crypto/CHIPCryptoPAL.h:696]: Agree. Buffer can be moved to SecurePairingSession.

File: src/transport/SecurePairingSession.cpp (hunk 3 above)
Comment (sujaygkulkarni-nxp) [reply src/transport/SecurePairingSession.cpp]: If the crypto operations are offloaded to HSM, it would be convenient if the context is passed as a whole.

File: src/crypto/CHIPCryptoPAL.h (hunk 1 above)
Comment (sujaygkulkarni-nxp) [reply src/crypto/CHIPCryptoPAL.h]: moved buffer to PASESession

File: src/transport/SecurePairingSession.cpp (hunk 3 above)
Comment (balducci-apple) [reply src/transport/SecurePairingSession.cpp]: I'm not suggesting we pass in the context in chunks. The context **is** the **hash** of the constant string "CHIP PAKE V1 Commissioning", the PBKDFParamRequest, and the PBKDFParamResponse. We implicitly know the length because we know the hash function that is used. 

**Previously Spake2+ was calculating this:** 

```
TranscriptHash = SHA256("Const String" || PBKDFParamRequest || PBKDFParamResponse || 
                        0x0000000000000000 || 0x0000000000000000 || 
                        len(M) || M || len(N) || N || 
                        len(X) || X || len(Y) || Y || 
                        len(Z) || Z || len(V) || V || len(w0) w0)
```

**What we would be calculating with this path:**

```
TranscriptHash = SHA256(len("Const String" || PBKDFParamRequest || PBKDFParamResponse) || 
                        "Const String" || PBKDFParamRequest || PBKDFParamResponse ||
                        0x0000000000000000 || 0x0000000000000000 || 
                        len(M) || M || len(N) || N || 
                        len(X) || X || len(Y) || Y || 
                        len(Z) || Z || len(V) || V || len(w0) w0)
```

**What we should be calculating:**

```
TranscriptHash = SHA256(SHA256_Output_Length || 
                        SHA256("Const String" || PBKDFParamRequest || PBKDFParamResponse) ||
                        0x0000000000000000 || 0x0000000000000000 || 
                        len(M) || M || len(N) || N || 
                        len(X) || X || len(Y) || Y || 
                        len(Z) || Z || len(V) || V || len(w0) w0)
```


This method of hashing these values is convenient as devices don't need to store the full-length message in memory. This will be especially important if we increase the number of pre-session messages or increase their size.

**Comment by balducci-apple** [comment]
**Previously Spake2+ was calculating this:** 

```
TranscriptHash = SHA256("Const String" || PBKDFParamRequest || PBKDFParamResponse || 
                        0x0000000000000000 || 0x0000000000000000 || 
                        len(M) || M || len(N) || N || 
                        len(X) || X || len(Y) || Y || 
                        len(Z) || Z || len(V) || V || len(w0) w0)
```

**What we would be calculating with this path:**

```
TranscriptHash = SHA256(len("Const String" || PBKDFParamRequest || PBKDFParamResponse) || 
                        "Const String" || PBKDFParamRequest || PBKDFParamResponse ||
                        0x0000000000000000 || 0x0000000000000000 || 
                        len(M) || M || len(N) || N || 
                        len(X) || X || len(Y) || Y || 
                        len(Z) || Z || len(V) || V || len(w0) w0)
```

**What we should be calculating:**

```
TranscriptHash = SHA256(SHA256_Output_Length || 
                        SHA256("Const String" || PBKDFParamRequest || PBKDFParamResponse) ||
                        0x0000000000000000 || 0x0000000000000000 || 
                        len(M) || M || len(N) || N || 
                        len(X) || X || len(Y) || Y || 
                        len(Z) || Z || len(V) || V || len(w0) w0)
```

**Comment by sujaygkulkarni-nxp** [comment]
> **Previously Spake2+ was calculating this:**
> 
> ```
> TranscriptHash = SHA256("Const String" || PBKDFParamRequest || PBKDFParamResponse || 
>                         0x0000000000000000 || 0x0000000000000000 || 
>                         len(M) || M || len(N) || N || 
>                         len(X) || X || len(Y) || Y || 
>                         len(Z) || Z || len(V) || V || len(w0) w0)
> ```
> 
> **What we would be calculating with this path:**
> 
> ```
> TranscriptHash = SHA256(len("Const String" || PBKDFParamRequest || PBKDFParamResponse) || 
>                         "Const String" || PBKDFParamRequest || PBKDFParamResponse ||
>                         0x0000000000000000 || 0x0000000000000000 || 
>                         len(M) || M || len(N) || N || 
>                         len(X) || X || len(Y) || Y || 
>                         len(Z) || Z || len(V) || V || len(w0) w0)
> ```
> 
> **What we should be calculating:**
> 
> ```
> TranscriptHash = SHA256(SHA256_Output_Length || 
>                         SHA256("Const String" || PBKDFParamRequest || PBKDFParamResponse) ||
>                         0x0000000000000000 || 0x0000000000000000 || 
>                         len(M) || M || len(N) || N || 
>                         len(X) || X || len(Y) || Y || 
>                         len(Z) || Z || len(V) || V || len(w0) w0)
> ```

**Comment by sujaygkulkarni** [comment]
context calculation updated as SHA256("Const String" || PBKDFParamRequest || PBKDFParamResponse)

**Review by balducci-apple — APPROVED** [review]
Looks good to me !

**Review by mspang — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@jelderton @saurabhst ?

**Review by saurabhst — APPROVED** [review]
