### PR TITLE
Fix invoke double call by modifying IME

### LINKED ISSUE #37257: Ensure no double-work on ::Invoke processing in validating paths
See conversation in https://github.com/project-chip/connectedhomeip/pull/37207#discussion_r1931526570_ for reference

In general we currently have IME check that a command path is valid and then calling ::Invoke checks that the command path is valid again. This seems redundant and we can save a bit of resources (both code size and processing time) if we do not get IME to double-check paths and lets the provider handle things.

### PR DESCRIPTION
**Pull request by jennygaz**
#### Summary

* Reorder command validation so we authorize first, then reuse the single `AcceptedCommandEntry` lookup for flag checks, keeping behavior fail-closed while documenting the equivalence to the spec’s flow.
* Simplify the invoke dispatch commentary to describe the new process and how it removed the double call to invoke
* Clarify the validation control flow by making the command-existence result explicit and const-qualified.

#### Related issues

Fixes #37257 

#### Testing

Passed unit tests locally and in the CI/CD, only Lint was giving me a hard time

#### Readability checklist

The checklist below will help the reviewer finish PR review in time and keep the
code readable:

-   [x] PR title is
        [descriptive](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html#title-formatting)
-   [x] Apply the
        [_“When in Rome…”_](https://project-chip.github.io/connectedhomeip-doc/style/CODING_STYLE_GUIDE.html)
        rule (coding style)
-   [x] PR size is short
-   [x] Try to avoid "squashing" and "force-update" in commit history
-   [x] CI time didn't increase

See: [Pull Request Guidelines](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html)

### CODE REVIEW

File: src/app/InteractionModelEngine.cpp [hunk 1]
```diff
@@ -1796,27 +1796,24 @@ Protocols::InteractionModel::Status InteractionModelEngine::ValidateCommandCanBe
...
-    // SPEC-DIVERGENCE: For non-concrete paths (Group Commands), the spec mandates only one ACL check AFTER the existence check.
-    // However, because this code is also used in the group path case, we end up performing an ADDITIONAL ACL check before the
-    // existence check. In practice, this divergence is not observable if all commands require at least Operate privilege.
-    Status status = CheckCommandAccess(request, Access::Privilege::kOperate);
-    VerifyOrReturnValue(status == Status::Success, status);
+    Status existenceStatus = CheckCommandExistence(request.path, acceptedCommandEntry);
 
-    status = CheckCommandExistence(request.path, acceptedCommandEntry);
+    // Default to Operate when the command metadata is unknown so we can fail closed while still avoiding
+    // leaking information about whether the path actually exists. When the metadata lookup succeeds we
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.cpp]: This should document that while it's not implementing the logic in the spec as written, it's equivalent as long as all commands require at least Operate privilege.  And that if that were ever not the case, the spec's logic would be broken.

File: src/data-model-providers/codegen/CodegenDataModelProvider.h [hunk 2]
```diff
@@ -127,6 +175,13 @@ class CodegenDataModelProvider : public DataModel::Provider
 
     SingleEndpointServerClusterRegistry mRegistry;
 
+    std::optional<ResolvedCommandTarget> mLastResolvedCommand;
```
Comment (bzbarsky-apple) [inline src/data-model-providers/codegen/CodegenDataModelProvider.h]: This cache seems completely unrelated to the IME changes....  Which one of these is this PR after and why?

In particular: there is nonzero codesize cost here.  What problem is it solving that makes it worth it?

Comment (jennygaz) [reply src/data-model-providers/codegen/CodegenDataModelProvider.h]: This is done so that Codegen doesn't call twice when looking for a command path and then using it, since that was what happening because there was no way in IME to call for a command path without verifying its existence.

Comment (bzbarsky-apple) [reply src/data-model-providers/codegen/CodegenDataModelProvider.h]: So that codegen (you mean CodegenDataModelProvider, I assume?) doesn't call _what_ twice?  And why is whatever it is bad to call twice?

Comment (jennygaz) [reply src/data-model-providers/codegen/CodegenDataModelProvider.h]: It was calling the command path validation twice through the `Invoke` method, and the issue mentioned there were possible code savings by removing the double call.

File: src/app/InteractionModelEngine.cpp (hunk 1 above)
Comment (jennygaz) [reply src/app/InteractionModelEngine.cpp]: Should be documented by now

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp [hunk 3]
```diff
@@ -178,6 +205,7 @@ std::optional<DataModel::ActionReturnStatus> CodegenDataModelProvider::InvokeCom
 
     if (handler_interface)
     {
+        RememberResolvedCommand(handler_interface, clusterPath);
         CommandHandlerInterface::HandlerContext context(*handler, request.path, input_arguments);
         handler_interface->InvokeCommand(context);
```
[the remark this answers is not in the document]
Comment (jennygaz) [reply src/data-model-providers/codegen/CodegenDataModelProvider.cpp:182]: According to the flow of the code, this will not happen and adding a guard would not work.

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp [hunk 4]
```diff
@@ -168,8 +168,35 @@ std::optional<DataModel::ActionReturnStatus> CodegenDataModelProvider::InvokeCom
...
+
+        case ResolvedCommandTarget::HandlerType::kCommandHandlerInterface: {
+            CommandHandlerInterface::HandlerContext context(*handler, request.path, input_arguments);
+            cached->handler.commandHandler->InvokeCommand(context);
+
+            if (context.mCommandHandled)
+            {
+                return std::nullopt;
+            }
+            break;
```
[the remark this answers is not in the document]
Comment (jennygaz) [reply src/data-model-providers/codegen/CodegenDataModelProvider.cpp]: It is intended to proceed because there's a way to handle such a case afterwards. By doing an early return here, it could introduce a memory issue or even a segmentation fault (I already tested it).

File: src/app/InteractionModelEngine.cpp [hunk 5]
```diff
@@ -185,6 +185,18 @@ InteractionModelEngine::InteractionModelEngine() : mReportingEngine(this) {}
...
+    //   1. `CheckCommandExistence` asks the active data-model provider for an `AcceptedCommandEntry`.  `CodegenDataModelProvider`
+    //   caches the most recent lookup and returns the same entry that `InvokeCommand` will later reuse for dispatch.  This avoids
+    //   duplicate registry/metadata traversals and keeps privilege data consistent.
+    //   2. `CheckCommandAccess` enforces ACL/privilege requirements derived from that entry.  By relying on the provider’s metadata
+    //   we ensure the privilege used here matches what the generated handler expects.
+    //   3. `CheckCommandFlags` validates timed / fabric-scoped / payload-size constraints that were also computed by the provider
+    //   so any change to generated metadata automatically applies to both validation and dispatch.
+    //
+    // Should any other code want to modify the command validation policy, it must do so via the provider or these helper functions
+    // so that pre-dispatch validation and the eventual dispatch path remain in lock-step.
```
[the remark this answers is not in the document]
Comment (jennygaz) [reply src/app/InteractionModelEngine.cpp]: Should be resolved in the latest commit.

File: src/app/InteractionModelEngine.cpp [hunk 6]
```diff
@@ -1793,30 +1793,44 @@ void InteractionModelEngine::DispatchCommand(CommandHandlerImpl & apCommandObj,
 
 Protocols::InteractionModel::Status InteractionModelEngine::ValidateCommandCanBeDispatched(const DataModel::InvokeRequest & request)
 {
+    // Spec §9.6.2 says we should return UnsupportedCommand as soon as the path is unknown. We check
+    // privilege first instead. This is equivalent to the spec as long as every command requires at
+    // least Operate privilege (the default we apply when metadata is missing). Should a command ever
```
Comment (andy31415) [inline src/app/InteractionModelEngine.cpp]: Is this new or was this existing? if we validate if command exists, could we pre-check with "view" (i.e. lowest) permission possible for existence check?

File: src/app/InteractionModelEngine.cpp [hunk 7]
```diff
@@ -1793,30 +1793,44 @@ void InteractionModelEngine::DispatchCommand(CommandHandlerImpl & apCommandObj,
...
+    // demand less than Operate, the spec’s algorithm would also need to change to stay consistent.
+
+    // Validation happens before we decode or dispatch command payloads. The flow intentionally mirrors the logic used by the
+    // generated data-model provider so that we only ever resolve command metadata once:
```
Comment (andy31415) [inline src/app/InteractionModelEngine.cpp]: I am unsure if IME comments should mention codegen data model provider ... it should explain what it does and why, but not couple it with specific implementations unless there is some strong reason for it (e.g. mentioning that some paths can be optimized)

File: src/app/InteractionModelEngine.cpp [hunk 8]
```diff
@@ -1793,30 +1793,44 @@ void InteractionModelEngine::DispatchCommand(CommandHandlerImpl & apCommandObj,
...
+    //   1. `CheckCommandExistence` asks the active data-model provider for an `AcceptedCommandEntry`.  `CodegenDataModelProvider`
```
Comment (andy31415) [inline src/app/InteractionModelEngine.cpp]: This comment is coupling CodegenDataModelProvider ... we should not do that. The caching is an implementation detail of the codegendatamodelprovider.

If we need changes in codegen, we can describe the caching there.

File: src/app/InteractionModelEngine.cpp [hunk 9]
```diff
@@ -1793,30 +1793,44 @@ void InteractionModelEngine::DispatchCommand(CommandHandlerImpl & apCommandObj,
...
 
-    // Execute the ACL Access Granting Algorithm before existence checks, assuming the required_privilege for the element is
-    // Operate, to determine if the subject would have had at least some access against the concrete path. This is done so we don't
-    // leak information if we do fail existence checks.
-    // SPEC-DIVERGENCE: For non-concrete paths (Group Commands), the spec mandates only one ACL check AFTER the existence check.
-    // However, because this code is also used in the group path case, we end up performing an ADDITIONAL ACL check before the
-    // existence check. In practice, this divergence is not observable if all commands require at least Operate privilege.
-    Status status = CheckCommandAccess(request, Access::Privilege::kOperate);
-    VerifyOrReturnValue(status == Status::Success, status);
+    Status existenceStatus = CheckCommandExistence(request.path, acceptedCommandEntry);
```
Comment (andy31415) [inline src/app/InteractionModelEngine.cpp]: maybe if we do a bool, it is clearer:

```suggestion
    const bool commandExists = (CheckCommandExistence(request.path, acceptedCommandEntry) == Status::Success);
```

Comment (andy31415) [reply src/app/InteractionModelEngine.cpp]: ah, I see we need the status later ok. Ok, then maybe:


```suggestion
    const Status existenceStatus = CheckCommandExistence(request.path, acceptedCommandEntry);
    const bool commandExists = (existenceStatus == Status::Success);
```

File: src/data-model-providers/codegen/CodegenDataModelProvider.h [hunk 10]
```diff
@@ -113,6 +117,50 @@ class CodegenDataModelProvider : public DataModel::Provider
         ClusterReference(const ConcreteClusterPath p, const EmberAfCluster * c) : path(p), cluster(c) {}
     };
 
+    struct ResolvedCommandTarget
```
Comment (andy31415) [inline src/data-model-providers/codegen/CodegenDataModelProvider.h]: The changes in this PR seems to be 360+ bytes of flash and quite a bit of code to save a lookup during command handling.

I was hoping the "avoid double call" would somehow be smaller and easier to  maintain. Unless we see that command dispatch timing is a problem, I would maybe rather lean towards not having this and either trying for a simpler change or give up on the change alltogether and commenting on the issue that "trying to optimize for performance costs a lot in maintainability/flash" and not fixing it after all.

File: src/app/InteractionModelEngine.cpp [hunk 11]
```diff
@@ -1793,30 +1793,44 @@ void InteractionModelEngine::DispatchCommand(CommandHandlerImpl & apCommandObj,
...
 
-    status = CheckCommandExistence(request.path, acceptedCommandEntry);
+    // Default to Operate when the command metadata is unknown so we can fail closed while still avoiding
+    // leaking information about whether the path actually exists. When the metadata lookup succeeds we
+    // enforce the precise privilege declared for the command.
+    Access::Privilege privilegeToCheck =
```
Comment (andy31415) [inline src/app/InteractionModelEngine.cpp]: What if we optimize for happy path to only have one call and get the unhappy path to potentially do multiple calls?

The way I understand the checks today is:
  - we check if command is accessible at all (and error out if it is not)
  - find the command
  - check access with the real privilege

which means 2xaccess check and one find if we are successful.

How about if we change to:
  - find the command
  - if not found, check access and return access error or find error
  - if found, check access with real privilege

This moves the happy path check to find + check access (because not-found is the error case).

This should minimize code delta and solves most of "do not call the API twice".

Comment (jennygaz) [reply src/app/InteractionModelEngine.cpp]: I removed the caching process and implemented a different flow now, so it should be better for now. Regarding byte size, I think it improved in some but might need to check more thoroughly. Let me know if the current changes are better or there could still be some gains to achieve

File: src/data-model-providers/codegen/CodegenDataModelProvider.h (hunk 2 above)
Comment (bzbarsky-apple) [reply src/data-model-providers/codegen/CodegenDataModelProvider.h]: >  and the issue mentioned there were possible code savings by removing the double call.

By removing the double call, sure.  But if you add a bunch of extra logic, that is not going to lead to code savings.  And in particular, this PR is significantly _increasing_ flash use for various platforms, no?

File: src/app/InteractionModelEngine.cpp [hunk 12]
```diff
@@ -1793,30 +1793,31 @@ void InteractionModelEngine::DispatchCommand(CommandHandlerImpl & apCommandObj,
 
 Protocols::InteractionModel::Status InteractionModelEngine::ValidateCommandCanBeDispatched(const DataModel::InvokeRequest & request)
 {
+    // Spec §9.6.2 says we should return UnsupportedCommand as soon as the path is unknown. We check
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.cpp]: Um... spec section 9.6.2 is the "Revision History" section of the Binding cluster.

What spec section is this actually talking about?  It's hard to evaluate the claims here (which look odd; "path is unknown" is not a spec concept, so I don't know what _that_ means either) without knowing what we think we are talking about.

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp [hunk 13]
```diff
@@ -164,6 +163,16 @@ CHIP_ERROR CodegenDataModelProvider::Startup(DataModel::InteractionModelContext
     });
 }
 
+// Validation happens before we decode or dispatch command payloads. The flow intentionally mirrors the logic used by the
+// generated data-model provider so that dispatch observes the same metadata that validation relied on:
```
Comment (bzbarsky-apple) [inline src/data-model-providers/codegen/CodegenDataModelProvider.cpp]: What is "the generated data-model provider"?

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp [hunk 14]
```diff
@@ -164,6 +163,16 @@ CHIP_ERROR CodegenDataModelProvider::Startup(DataModel::InteractionModelContext
...
+//   1. `CheckCommandExistence` asks the active data-model provider for an `AcceptedCommandEntry`, guaranteeing dispatch sees the
+//      same command metadata.
+//   2. `CheckCommandAccess` enforces ACL/privilege requirements for the command path after existence is confirmed.
+//   3. `CheckCommandFlags` validates timed / fabric-scoped / payload-size constraints that were also computed by the provider,
+//      so any change to generated metadata automatically applies to both validation and dispatch.
+//
+// Should any other code want to modify the command validation policy, it must do so via the provider or these helper functions
+// so that pre-dispatch validation and the eventual dispatch path remain in lock-step.
```
Comment (bzbarsky-apple) [inline src/data-model-providers/codegen/CodegenDataModelProvider.cpp]: I don't understand this comment.  By the time we land in this code, we have already done the following validations:

1.  The command exists
2. ACLs allow dispatch
3. Various other required IM checks, which are not spelled out in the API docs.

What needs to be kept in lock-step with wha?  This code is not repeating those validations....

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

**Review by bzbarsky-apple — COMMENTED** [review]
Also, the PR description seems to have not much to do with what the PR is actually doing now.

File: src/data-model-providers/codegen/CodegenDataModelProvider.h (hunk 2 above)
Comment (jennygaz) [reply src/data-model-providers/codegen/CodegenDataModelProvider.h]: I simplified the code afterwards, it should be better now and not increase the flash use as much, in a previous state it did increase it a lot.

File: src/app/InteractionModelEngine.cpp (hunk 12 above)
Comment (jennygaz) [reply src/app/InteractionModelEngine.cpp]: I got confused on my end, so I reworded the comments to better reflect the usage, what is going on, and avoid coupling unintentionally through comments.

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp (hunk 13 above)
Comment (jennygaz) [reply src/data-model-providers/codegen/CodegenDataModelProvider.cpp]: I replace this mention with a shorter note that indicates how validation uses the same metadata that is exposed by the provider, which should be clearer but let me know if it's not to fix it

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp (hunk 14 above)
Comment (jennygaz) [reply src/data-model-providers/codegen/CodegenDataModelProvider.cpp]: Yes, I didn't update the comment after making some changes which made the comment obsolete. I think it should be better now

File: src/app/InteractionModelEngine.cpp [hunk 15]
```diff
@@ -1793,30 +1793,34 @@ void InteractionModelEngine::DispatchCommand(CommandHandlerImpl & apCommandObj,
 
 Protocols::InteractionModel::Status InteractionModelEngine::ValidateCommandCanBeDispatched(const DataModel::InvokeRequest & request)
 {
+    // The specification describes a validate-then-authorize flow that first resolves command metadata
+    // (which implicitly checks existence) and then enforces the privilege declared for that command.
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.cpp]: This doesn't correctly describe what the spec says, and makes it sound like the spec "reveals whether a command exists", when it does not.

And importantly: what the spec says is somewhat different for the group vs non-group case, but this code is called for both cases.

If we're going to have comments here, they really need to be accurate.

If we want a comment here, I suggest having a comment that:

1. Describes the spec's checks for the non-group case (which this comment does not do correctly).
2. Describes the spec's checks for the group case.
3. Describes the checks we will do below.
4. Explains whey they are observably equivalent to (1) as long as all commands require at least Operate, and to (2) (because for (2) nothing can be observed anyway other than whether the command executes).

But I am not sure we need a comment here, especially because comments below, next to the relevant code, cover the same ground.

File: src/app/InteractionModelEngine.cpp [hunk 16]
```diff
@@ -1793,30 +1793,34 @@ void InteractionModelEngine::DispatchCommand(CommandHandlerImpl & apCommandObj,
...
+    // We reverse those steps: authorization happens first so we never reveal whether a command exists
+    // to a caller lacking sufficient privilege. This produces the same result as the spec today because
+    // all Matter commands require at least Operate privilege and we fall back to Operate when metadata
+    // is unavailable; if a command ever shipped with a lower privilege requirement we would need to
+    // revisit this ordering.
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.cpp]: Again: it's important that if a command ever had a lower privilege requirement, the current logic in the spec would be wrong.  But again, I don't think we need this comment at all.

File: src/app/InteractionModelEngine.cpp [hunk 17]
```diff
@@ -1793,30 +1793,34 @@ void InteractionModelEngine::DispatchCommand(CommandHandlerImpl & apCommandObj,
...
-    // existence check. In practice, this divergence is not observable if all commands require at least Operate privilege.
-    Status status = CheckCommandAccess(request, Access::Privilege::kOperate);
-    VerifyOrReturnValue(status == Status::Success, status);
+    const Status existenceStatus = CheckCommandExistence(request.path, acceptedCommandEntry);
+    const bool commandExists     = (existenceStatus == Status::Success);
 
-    status = CheckCommandExistence(request.path, acceptedCommandEntry);
+    // Default to Operate when the command metadata is unknown so we can fail closed while still avoiding
+    // leaking information about whether the path actually exists. When the metadata lookup succeeds we
+    // enforce the precise privilege declared for the command.
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.cpp]:
```suggestion
    // If the command exists, then the spec defines either doing a check for Operate access
    // followed by a check for the actual access level of the command (in the concrete path case)
    // or just doing a check for the actual access level of the command (in the non-concrete path case).
    // Since all commands require at least Operate access in the spec (and the spec algorithm would be
    // wrong if they did not), this is equivalent to doing a single check for the actual access level of the command.
    //
    // If the command does not exist, but we still got here, we must be in the concrete path case, and the spec
    // then defines a single check for the Operate access level, whose failure must take precedence over the
    // existence check in terms of what is communicated back to the client.
    //
    // The code below implements equivalent logic:
    // * If the command exists, the only possible failure is due to insufficient access, and it's
    //   enough to check the actual access level of the command.
    // * If the command does not exist, a check for Operate is done, and if that fails the corresponding
    //   status is returned.  If it succeeds, then the "no such command" status is returned.
```

Comment (bzbarsky-apple) [reply src/app/InteractionModelEngine.cpp]: Note: with the comment in this form, I don't think the comment at the top of the function is needed at all....

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp [hunk 18]
```diff
@@ -164,6 +163,9 @@ CHIP_ERROR CodegenDataModelProvider::Startup(DataModel::InteractionModelContext
     });
 }
 
+// Command validation queries this provider for metadata before InvokeCommand runs, so the dispatch sequence below relies on the
+// same catalog of clusters and handlers that validation already approved.  That keeps the privilege and flag checks performed by
+// `ValidateCommandCanBeDispatched` in sync with the handler that ultimately processes the request.
```
Comment (bzbarsky-apple) [inline src/data-model-providers/codegen/CodegenDataModelProvider.cpp]: I don't understand what this comment is trying to say and why it's specific to CodegenDataModelProvider.

As in: why is this comment here?

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp [hunk 19]
```diff
@@ -176,7 +178,7 @@ std::optional<DataModel::ActionReturnStatus> CodegenDataModelProvider::InvokeCom
     CommandHandlerInterface * handler_interface =
         CommandHandlerInterfaceRegistry::Instance().GetCommandHandler(request.path.mEndpointId, request.path.mClusterId);
 
-    if (handler_interface)
+    if (handler_interface != nullptr)
```
Comment (bzbarsky-apple) [inline src/data-model-providers/codegen/CodegenDataModelProvider.cpp]: Why this random change?

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp [hunk 20]
```diff
@@ -188,7 +190,7 @@ std::optional<DataModel::ActionReturnStatus> CodegenDataModelProvider::InvokeCom
         }
     }
 
-    // Ember always sets the return in the handler
+    // Let the generated dispatcher handle any remaining paths; it sets the status on our behalf.
```
Comment (bzbarsky-apple) [inline src/data-model-providers/codegen/CodegenDataModelProvider.cpp]: No, this is not correct.  The old comment could perhaps be clearer, but the key is that DispatchSingleClusterCommand will always place responses in the handler, so we must return std::nullopt from this method to follow the DataModelProvider::InvokeCommand API contract.

The new comment completely misses this key point.

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp [hunk 21]
```diff
@@ -453,11 +455,13 @@ CHIP_ERROR CodegenDataModelProvider::AcceptedCommands(const ConcreteClusterPath
     if (interface != nullptr)
     {
         CHIP_ERROR err = interface->RetrieveAcceptedCommands(path, builder);
-        // If retrieving the accepted commands returns CHIP_ERROR_NOT_IMPLEMENTED then continue with normal procesing.
+        // If retrieving the accepted commands returns CHIP_ERROR_NOT_IMPLEMENTED then continue with normal processing.
         // Otherwise we finished.
-        VerifyOrReturnError(err == CHIP_ERROR_NOT_IMPLEMENTED, err);
+        if (err != CHIP_ERROR_NOT_IMPLEMENTED)
```
Comment (bzbarsky-apple) [inline src/data-model-providers/codegen/CodegenDataModelProvider.cpp]: Why this change?  But OK, I guess.

File: src/data-model-providers/codegen/CodegenDataModelProvider.cpp [hunk 22]
```diff
@@ -190,7 +187,7 @@ std::optional<DataModel::ActionReturnStatus> CodegenDataModelProvider::InvokeCom
         }
     }
 
-    // Let the generated dispatcher handle any remaining paths; it sets the status on our behalf.
+    // Ember always sets the return in the handler, where std::nullopt must be returned to follow the InvokeCommand API contract
```
Comment (bzbarsky-apple) [inline src/data-model-providers/codegen/CodegenDataModelProvider.cpp]:
```suggestion
    // Ember always returns responses via the handler, so std::nullopt must be returned here to follow the InvokeCommand API contract
```

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
