### PR TITLE
Ensure that a PASE session doesn't outlive the fail-safe (and vice versa).

### LINKED ISSUE #16839: Need to implement handling of CloseSession status messages
#### Problem
The spec defines, in "4.10.1.4. CloseSession", a secure channel status code that forces closing of the secure session it's delivered on.  This is not implemented, but error recovery during commissioning critically depends on this.

 #### Proposed Solution
What I think we need to do is:
1. Sort out the actual semantics; see https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/5071 and https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/5072.
2. For now, assume that we just need to handle CloseSession in unsolicited status messages, which we can do somewhat easily via an unsolicited message handler.
3. <s>Make sure that as we're closing the session we at least get the MRP ack off first, so the other side doesn't keep retrying.  This might already work, possibly; we will need to check.</s> Edit: no MRP involved with CloseSession.
4. Ensure that when a PASE session is closed via CloseSession any associated fail-safe context is expired (and does its roll-backs as needed).
5. Ensure that when a PASE session is closed via CloseSession the commissioning window manager is notified so it can go back to listening for PASE session establishment if the commissioning window is still open.

@cecille @tcarmelveilleux @lochan-apple @msandstedt

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Per spec, when a fail-safe expires step 1 is:

> Terminate any open PASE secure session by clearing any associated Secure
> Session Context at the Server.

We were not doing that.

Similarly, per spec if a PASE session is terminated by CloseSession, it should
expire the pending fail-safe, if any.  We weren't doing that either.

#### Problem
See above.

#### Change overview
Expire the fail-safe when the PASE session is closed, and close the PASE session when the fail-safe expires.

#### Testing
1. Compile and run all-clusters-app on Mac.
2. Compile chip-tool.
3. `chip-tool interactive start`
4. Issue the following commands:
    ```
    pairing code-paseonly 17 749701123365521327694
    generalcommissioning arm-fail-safe 0 0 17 0
    onoff toggle 17 1
    ```

Before these changes, the toggle command was received by the server and the response was received by chip-tool.

After these changes, the toggle command gets dropped with:
```
[1655317670249] [9204:12201281] CHIP: [IN] Data received on an unknown session (LSID=48053). Dropping it!
```

Testing the other direction will happen once I fix #16839 and can test CloseSession.

### CODE REVIEW

File: src/app/server/CommissioningWindowManager.cpp [hunk 1]
```diff
@@ -98,11 +103,7 @@ void CommissioningWindowManager::ResetState()
 void CommissioningWindowManager::Cleanup()
 {
     StopAdvertisement(/* aShuttingDown = */ false);
-    DeviceLayer::FailSafeContext & failSafeContext = DeviceLayer::DeviceControlServer::DeviceControlSvr().GetFailSafeContext();
-    if (failSafeContext.IsFailSafeArmed())
-    {
-        failSafeContext.ForceFailSafeTimerExpiry();
-    }
+    ExpireFailSafeIfArmed();
```
Comment (tcarmelveilleux) [inline src/app/server/CommissioningWindowManager.cpp:106]: This does not belong in the CommissioningWindowManager, per spec. We already have to clean that up with the cumulative fail-safe. Since https://github.com/project-chip/connectedhomeip/pull/19582 is merged, we should take this ExpireFailSafeIfArmed out

Comment (bzbarsky-apple) [reply src/app/server/CommissioningWindowManager.cpp:106]: I would rather have that behavior change as a separate PR that we can audit carefully (including checking all the reasons Cleanup is called).  For this PR I just kept existing behavior here.

**Review by mrjerryjohns — APPROVED** [review]

File: src/app/server/CommissioningWindowManager.cpp [hunk 2]
```diff
@@ -164,20 +165,31 @@ void CommissioningWindowManager::OnSessionEstablished(const SessionHandle & sess
...
     }
     else
     {
-        CHIP_ERROR err = failSafeContext.ArmFailSafe(kUndefinedFabricId, System::Clock::Seconds16(60));
+        err = failSafeContext.ArmFailSafe(kUndefinedFabricId, System::Clock::Seconds16(60));
         if (err != CHIP_NO_ERROR)
         {
             ChipLogError(AppServer, "Error arming failsafe on PASE session establishment completion");
+            // Don't allow a PASE session to hang around without a fail-safe.
+            session->AsSecureSession()->MarkForRemoval();
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/app/server/CommissioningWindowManager.cpp:180]: That's a really good question.  I guess we could do that, yes.  You're right that it might be a little cleaner.

**Review by tcarmelveilleux — APPROVED** [review]

**Review by krypton36 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]
