### PR TITLE
CASE spec refresh

### LINKED ISSUE #5934: CASE handshake implementation looks nothing like the spec
#### Problem
#5442 implemented CASE, but it looks very little like the CASE in the spec in terms of what's going in to the messages and how.

 #### Proposed Solution
Implement what the spec says.

### LINKED ISSUE #8207: CASE session fails when commissioning second device in a row
#### Problem
When commissioning the accessory device for the first time CASE session is established fine, however after factory resetting the device and commissioning it once again with different node ID it fails on the controller side due to no memory error. The condition that fails is located in the following line: https://github.com/project-chip/connectedhomeip/blob/master/src/credentials/CHIPCert.cpp#L244

Steps to reproduce:
1. Commission the accessory with Python CHIP controller and some node ID (e.g. 1):

```
connect -ble 3840 20202021 1
zcl NetworkCommissioning AddThreadNetwork 1 0 0 operationalDataset=hex:000300000f02081111111122222222051000112233445566778899aabbccddeeff01021234 breadcrumb=0 timeoutMs=1000
zcl NetworkCommissioning EnableNetwork 1 0 0 networkID=hex:1111111122222222 breadcrumb=0 timeoutMs=1000
close-ble
```

2. Resolve IP address with `resolve 5544332211 1` - it will succeed.
3. Factory reset the device.
4. Commission the accessory once again with different node ID (e.g. 2):

```
connect -ble 3840 20202021 2
zcl NetworkCommissioning AddThreadNetwork 2 0 0 operationalDataset=hex:000300000f02081111111122222222051000112233445566778899aabbccddeeff01021234 breadcrumb=0 timeoutMs=1000
zcl NetworkCommissioning EnableNetwork 2 0 0 networkID=hex:1111111122222222 breadcrumb=0 timeoutMs=1000
close-ble
```

5. Resolve IP address with `resolve 5544332211 2` again - it will fail.

Logs on the accessory side:
```
'I: 72134 [IN]CASE Server received SigmaR1 message. Starting handshake. EC 0x20003898\r\n'
'D: 72144 [SC]Waiting for SigmaR1 msg\r\n'
'D: 72148 [SC]Received SigmaR1 msg\r\n'
'D: 72151 [SC]Peer assigned session key ID 12\r\n'
'D: 72209 [SC]Sent SigmaR2 msg\r\n'
'I: 72310 [EM]Received message of type 63 and protocolId 0 on exchange 56472\r\n'
'E: 72317 [SC]Received error (255) during CASE pairing process\r\n'
'I: 72324 [IN]CASE Session establishment failed: CHIP Error 4084 (0x00000FF4): Invalid CASE parameter\r\n'
```

Logs on the controller side:
```
[1625463797.529033][459:658] CHIP:DIS: Node ID resolved for 0x0000000000000009 to [fd11:22::7cf8:11af:95ed:a205]:11097
[1625463797.529059][459:658] CHIP:CTL: SyncSetKeyValue on PairedDevice9
Node address has been updated
[1625463797.529367][459:658] CHIP:CTL: OperationalDiscoveryComplete for device ID 9
[1625463797.529378][459:658] CHIP:CTL: Enabling CASE session establishment for the device
[1625463797.529391][459:658] CHIP:CTL: SyncSetKeyValue on PairedDevice9
[1625463797.529395][459:658] CHIP:IN: Marking old secure session for device 0x0000000000000009 as expired
[1625463797.529409][459:658] CHIP:CTL: SyncSetKeyValue on PairedDevice9
[1625463797.529415][459:658] CHIP:CTL: SyncSetKeyValue on StartKeyID
[1625463797.529698][459:658] CHIP:SC: Sent SigmaR1 msg
[1625463797.747842][459:658] CHIP:EM: Received message of type 49 and protocolId 0 on exchange 56458
[1625463797.747889][459:658] CHIP:EM: Rxd Ack; Removing MsgId:00000000 from Retrans Table
[1625463797.747901][459:658] CHIP:EM: Removed CHIP MsgId:00000000 from RetransTable
[1625463797.747929][459:658] CHIP:SC: Received SigmaR2 msg
[1625463797.747939][459:658] CHIP:SC: Peer assigned session key ID 1
[1625463797.748543][459:658] CHIP:EM: Piggybacking Ack for MsgId:00000000 with msg
[1625463797.748686][459:658] CHIP:CTL: Device connection failed. Error CHIP Error 4011 (0x00000FAB): No memory
Failed to commission: 4011
```

It seems that root cause of a problem is that CHIP Device Controller stores only one instance of certificates here: https://github.com/project-chip/connectedhomeip/blob/master/src/controller/CHIPDeviceController.h#L341. Maximal capacity is 3, so it can store root cert, ICA and NOC. First two of them are loaded on the controller init and third one during CASE session with accessory. After first CASE session array is full and on the new CASE session with another device there is not space for another NOC.

 #### Proposed Solution
Store here: https://github.com/project-chip/connectedhomeip/blob/master/src/controller/CHIPDeviceController.h#L341 an array of objects with size equal to the number of paired devices instead of single object?

### PR DESCRIPTION
**Pull request by jpk233**
#### Problem
* CASE does not currently follow the current spec with message handling.

* Fixes #5934 (along with the previously submitted CASE TLV changes)
* Fixes #8207

#### Change overview
* Added TrustedRootId parameter to CASESession’s EstablishSession method

* Added new methods to Find and Generate Destination IDs (New CASE Spec updates)

* Updated some CASESession method’s parameters that were using raw input buffers with ByteSpan and MutableByteSpan objects

* Updated CASESession Nonce and Info vectors (new CASE Spec updates)

* Updated SigmaR1 message construction method to generate DestinationID instead of sending all TrustedRootIDs available.

* Minor comment updates to match CASE Spec’s steps

* Added new method to OperationalCredentialSet to retrieve RootCertificate indexed by TrustedRootId

* CASESession Tests: Updated NodeID parameter to match Node ID of the corresponding Test Vector Certificate

#### Testing
* Tested using CASE Session Unit Tests

### CODE REVIEW

File: src/channel/Channel.h [hunk 1]
```diff
@@ -107,6 +107,13 @@ class ChannelBuilder
         return *this;
     }
 
+    Credentials::CertificateKeyId & GetTrustedRootId() const { return *mCaseParameters.mTrustedRootId; }
+    ChannelBuilder & SetTrustedRootId(Credentials::CertificateKeyId * trustedRootId)
+    {
+        mCaseParameters.mTrustedRootId = trustedRootId;
+        return *this;
+    }
+
```
Comment (tcarmelveilleux) [inline src/channel/Channel.h:116]: TrustedRootIdentifier is no longer present in CASE section of spec. See: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/3390

File: src/protocols/secure_channel/CASESession.cpp [hunk 2]
```diff
@@ -335,54 +348,51 @@ CHIP_ERROR CASESession::DeriveSecureSession(SecureSession & session, SecureSessi
...
+    uint8_t destinationIdentifier[kMAX_Hash_Length]      = { 0 };
 
     // Step 1
-    // Fill in the random value
+    ReturnErrorOnFailure(mEphemeralKey.Initialize());
+
+    // Step 2
+    {
+        MutableByteSpan ipkSpan(mIPK, sizeof(mIPK));
+        ReturnErrorOnFailure(ComputeIPK(mConnectionState.GetLocalKeyID(), ipkSpan));
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:366]: What is ComputeIPK? The IPK is supposed to be stored.

File: src/protocols/secure_channel/CASESession.cpp [hunk 3]
```diff
@@ -335,54 +348,51 @@ CHIP_ERROR CASESession::DeriveSecureSession(SecureSession & session, SecureSessi
...
+    }
+
+    // Step 3
     ReturnErrorOnFailure(DRBG_get_bytes(initiatorRandom, kSigmaParamRandomNumberSize));
 
-    // Step 4
-    ReturnErrorOnFailure(mEphemeralKey.Initialize());
+    // Step 6
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:372]: These step numbers are confusing: step 6 is before `Step 5 (6)`. Would it be possible instead to describe, rather than number, the steps?

File: src/protocols/secure_channel/CASESession.cpp [hunk 4]
```diff
@@ -423,31 +434,44 @@ CHIP_ERROR CASESession::HandleSigmaR1(System::PacketBufferHandle & msg)
...
     SuccessOrExit(err);
 
-    err = tlvReader.FindElementWithTag(CASETLVTag::kNumberofTrustedRootIDs, suppTlvReader);
+    ChipLogDetail(SecureChannel, "Peer assigned session key ID %d", encryptionKeyId);
+    mConnectionState.SetPeerKeyID(encryptionKeyId);
+
+    {
+        MutableByteSpan ipkSpan(mIPK, sizeof(mIPK));
+        SuccessOrExit(err = ComputeIPK(mConnectionState.GetPeerKeyID(), ipkSpan));
+    }
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:455]: There must be a "match loop" that includes trying every IPK still valid for the given fabric (there may be more than one). We do not have that yet (Group Key Management Cluster) to spec in here, so I suggest adding a TODO to iterate over all candidate IPKs for each fabric.

File: src/protocols/secure_channel/CASESession.cpp [hunk 5]
```diff
@@ -875,25 +905,26 @@ CHIP_ERROR CASESession::SendSigmaR3()
...
-                                 mOpCredSet->GetDevOpCredLen(mTrustedRootId));
-        SuccessOrExit(err);
-        err = tlvWriter.PutBytes(CASETLVTag::kSignature, sigmaR3Signature, static_cast<uint32_t>(sigmaR3Signature.Length()));
-        SuccessOrExit(err);
-        err = tlvWriter.EndContainer(outerContainerType);
-        SuccessOrExit(err);
-        err = tlvWriter.Finalize();
-        SuccessOrExit(err);
+        SuccessOrExit(err = tlvWriter.StartContainer(TLV::AnonymousTag, TLV::kTLVType_Structure, outerContainerType));
+        SuccessOrExit(err = tlvWriter.PutBytes(CASETLVTag::kNOC, mOpCredSet->GetDevOpCred(mTrustedRootId),
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:909]: Is GetDevOpCred already a cert array? I think @bzbarsky-apple was talking about maybe splitting the NOC+ICAC cert arrays into separate fields everywhere to simplify things. No need to do in this PR, but something where a conversation could be had.

File: src/protocols/secure_channel/CASESession.cpp [hunk 6]
```diff
@@ -1109,23 +1144,59 @@ void CASESession::SendErrorMsg(SigmaErrorType errorCode)
...
+    Encoding::LittleEndian::BufferWriter bbuf(destinationMessage->Start(), destinationMessageLen);
+
+    bbuf.Put(random.data(), random.size());
+    bbuf.Put(rootCertificate->mPublicKey.data(), rootCertificate->mPublicKey.size());
+    bbuf.Put64(fabricId);
+    bbuf.Put64(nodeId);
+
+    VerifyOrReturnError(bbuf.Fit(), CHIP_ERROR_NO_MEMORY);
+
+    ReturnErrorOnFailure(mHKDF.HKDF_SHA256(destinationMessage->Start(), destinationMessageLen, 0, 0, mIPK, sizeof(mIPK),
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1170]: There is one choice of IPK for outgoing destination ID (the current one chosen by initator), but this method will eventually need to be called several times, one for each IPK in force (where there could be rotation at play) at the receiver.

Strongly suggest making this "compute-only" method stateless, by:

1- Adding a FabricID argument
2- Adding an IPK argument

Then the `GenerateDestinationID` could also be validated by unit test against the canonical test vector in Matter spec.

File: src/protocols/secure_channel/CASESession.cpp [hunk 7]
```diff
@@ -1109,23 +1144,59 @@ void CASESession::SendErrorMsg(SigmaErrorType errorCode)
...
+CHIP_ERROR CASESession::GenerateDestinationID(const ByteSpan & random, const Credentials::CertificateKeyId * trustedRootId,
+                                              NodeId nodeId, MutableByteSpan & destinationId)
 {
-    CertificateKeyId trustedRoot;
-    System::PacketBufferTLVReader suppTlvReader;
-    uint8_t trustedRootId[kTrustedRootIdSize];
+    HKDF_sha_crypto mHKDF;
+    // TODO: read fabricId
+    uint64_t fabricId              = 0;
+    uint16_t destinationMessageLen = kSigmaParamRandomNumberSize + kP256_PublicKey_Length + sizeof(fabricId) + sizeof(nodeId);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1153]: The message is not based on underlying types, but rather on wire data. Suggest using `sizeof(uint64_t)` for FabricID NodeId, especially since if NodeId type changes over time to possibly be wider, the value here will break.

File: src/protocols/secure_channel/CASESession.cpp (hunk 6 above)
Comment (tcarmelveilleux) [reply src/protocols/secure_channel/CASESession.cpp:1170]: The function used here is an HKDF, rather than the specified HMAC. They are very closely related, but not the same.

The algorithm used here mixes and matches fields in a way that does not match spec. See https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/crypto_primitives/case_destination_id_test_vector.py for pseudo-code of a destination ID.

Your version should yield the *exact same* output for the same inputs. It will not.

I implemented your version quickly in the test vector (see attached) and given the same inputs, it does not match the output of HMAC-SHA256 due to how the data is preprocessed for HKDF purposes.

This means that the destination ID computation is not to-spec.

Suggested fix:

1- Create a unit test case that matches the destination ID test vector from spec
2- Add CHIP_Crypto_HMAC to CryptoPAL (not yet implemented, but easy to implement and verify). The semantics are expressed in chapter 3 of the spec
3- Update the logic here to use CHIP_Crypto_HMAC.

I can assist, as I wrote the test vectors in the spec and designed the destinationId method.

**Review by tcarmelveilleux — CHANGES_REQUESTED** [review]
Crypto algorithm used for destinationId in CASE does not match spec.

File: src/protocols/secure_channel/CASESession.cpp (hunk 6 above)
Comment (tcarmelveilleux) [reply src/protocols/secure_channel/CASESession.cpp:1170]: I started the implementation of CHIP_Crypto_HMAC in CHIPCryptoPAL

File: src/channel/Channel.h (hunk 1 above)
Comment (jpk233) [reply src/channel/Channel.h]: Updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 2 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 3 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Changed the comments to a description rather than step numbers.

File: src/protocols/secure_channel/CASESession.cpp (hunk 5 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp:844]: Agreed, could be something to look into for the future.

File: src/protocols/secure_channel/CASESession.cpp (hunk 6 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated to use HMAC.

File: src/protocols/secure_channel/CASESession.cpp (hunk 4 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 7 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated to use the existing FabricId and NodeId types instead (which are uint64_t), rather than hardcode it here.

File: src/protocols/secure_channel/CASESession.cpp [hunk 8]
```diff
@@ -575,19 +550,18 @@ CHIP_ERROR CASESession::SendSigmaR2()
         SuccessOrExit(err = tlvWriter.Finalize());
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:550]:
```suggestion
        SuccessOrExit(err = tlvWriter.Finalize());
        msg_r2_signed_enc_len = static_cast<uint16_t>(tlvWriter.GetLengthWritten());
```

File: src/protocols/secure_channel/CASESession.cpp [hunk 9]
```diff
@@ -881,25 +840,26 @@ CHIP_ERROR CASESession::SendSigmaR3()
...
-        SuccessOrExit(err);
-        err = tlvWriter.Finalize();
-        SuccessOrExit(err);
+        SuccessOrExit(err = tlvWriter.StartContainer(TLV::AnonymousTag, TLV::kTLVType_Structure, outerContainerType));
+        SuccessOrExit(err = tlvWriter.PutBytes(CASETLVTag::kNOC, mOpCredSet->GetDevOpCred(mTrustedRootId),
+                                               mOpCredSet->GetDevOpCredLen(mTrustedRootId)));
+        SuccessOrExit(
+            err = tlvWriter.PutBytes(CASETLVTag::kSignature, sigmaR3Signature, static_cast<uint32_t>(sigmaR3Signature.Length())));
+        SuccessOrExit(err = tlvWriter.EndContainer(outerContainerType));
+        SuccessOrExit(err = tlvWriter.Finalize());
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:849]:
```suggestion
        SuccessOrExit(err = tlvWriter.Finalize());
        msg_r3_encrypted_len = static_cast<uint16_t>(tlvWriter.GetLengthWritten());
```

File: src/controller/CHIPDevice.h [hunk 10]
```diff
@@ -473,6 +475,7 @@ class DLL_EXPORT Device : public Messaging::ExchangeDelegate, public SessionEsta
     CASESession mCASESession;
 
     Credentials::OperationalCredentialSet * mCredentials = nullptr;
+    uint8_t * mCredentialsIndex                          = nullptr;
```
Comment (tcarmelveilleux) [inline src/controller/CHIPDevice.h:478]: If it's an index, why is it a uint8_t pointer?

File: src/protocols/secure_channel/CASESession.h [hunk 11]
```diff
@@ -105,6 +104,7 @@ class DLL_EXPORT CASESession : public Messaging::ExchangeDelegate, public Pairin
      * @param peerAddress                   Address of peer with which to establish a session.
      * @param operationalCredentialSet      CHIP Certificate Set used to store the chain root of trust an validate peer node
      *                                      certificates
+     * @param opCredSetIndex                Index value used to choose the chain root of trust for establisbing a session
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.h:107]: The comment here doesn't really express how to determine this index.

File: src/transport/AdminPairingTable.cpp [hunk 12]
```diff
@@ -374,6 +374,7 @@ CHIP_ERROR AdminPairingInfo::GetCredentials(OperationalCredentialSet & credentia
 
     credentials.Release();
     ReturnErrorOnFailure(credentials.Init(&certificates, 1));
+    credentialsIndex = static_cast<uint8_t>(credentials.GetCertCount() - 1U);
```
Comment (tcarmelveilleux) [inline src/transport/AdminPairingTable.cpp:377]: Why is this a `uint8_t` rather than a size_t ? What if we have a device part of a large number of fabrics, and the number of credentials is > 255?

File: src/protocols/secure_channel/tests/TestCASESession.cpp [hunk 13]
```diff
@@ -67,6 +67,11 @@ P256SerializedKeypair accessoryOpKeysSerialized;
 
 P256Keypair commissionerOpKeys;
 P256Keypair accessoryOpKeys;
+
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/tests/TestCASESession.cpp:70]: Overall comment on TestCASESession.cpp:

Either:
- We need the DestinationId computation to be part of CHIPCryptoPAL.cpp/.h and test it in there
- We add a test case to TestCASESession.cpp to at least cover the spec test vector of destinationID computation.

File: src/protocols/secure_channel/CASESession.cpp [hunk 14]
```diff
@@ -43,17 +44,14 @@ using namespace Crypto;
...
+constexpr uint8_t kKDFSR2Info[]   = { 0x53, 0x69, 0x67, 0x6d, 0x61, 0x32 };
+constexpr uint8_t kKDFSR3Info[]   = { 0x53, 0x69, 0x67, 0x6d, 0x61, 0x33 };
 constexpr size_t kKDFInfoLength   = sizeof(kKDFSR2Info);
 constexpr uint8_t kKDFSEInfo[]    = { 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x73 };
 constexpr size_t kKDFSEInfoLength = sizeof(kKDFSEInfo);
 
-constexpr uint8_t kIVSR2[] = { 0x4e, 0x43, 0x41, 0x53, 0x45, 0x5f, 0x53, 0x69, 0x67, 0x6d, 0x61, 0x52, 0x32 };
-constexpr uint8_t kIVSR3[] = { 0x4e, 0x43, 0x41, 0x53, 0x45, 0x5f, 0x53, 0x69, 0x67, 0x6d, 0x61, 0x52, 0x33 };
+constexpr uint8_t kIVSR2[] = { 0x4e, 0x43, 0x41, 0x53, 0x45, 0x5f, 0x53, 0x69, 0x67, 0x6d, 0x61, 0x32, 0x4e };
+constexpr uint8_t kIVSR3[] = { 0x4e, 0x43, 0x41, 0x53, 0x45, 0x5f, 0x53, 0x69, 0x67, 0x6d, 0x61, 0x33, 0x4e };
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:54]: These are called TBEData2_Nonce and TBEData3_Nonce respectively in spec. Suggest renaming these constants to match spec and add the equivalent string as a comment above (e.g. `/* "NCASE_Sigma2N" */`)

File: src/protocols/secure_channel/CASESession.cpp [hunk 15]
```diff
@@ -91,26 +89,15 @@ enum CASETLVTag : uint8_t
...
-    kEncryptedData = 9,
-    /*! \brief Tag 10. The packet contains an AEAD Tag. */
-    kTag = 10,
-    // TODO: Remove tag 11
-    /*! \brief Tag 11. The packet contains the total number of Trusted Root IDs. */
-    kNumberofTrustedRootIDs = 11,
+    /*! \brief Tag 8. The packet contains an Encrypted data blob. */
+    kEncryptedData = 8,
+    /*! \brief Tag 9. The packet contains an AEAD Tag. */
+    kTag = 9,
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:95]: This entire enum "shifted" from original meaning to being TLV tags. The Tag IDs are actually in the spec. These tag IDs are all not to-spec:

```
[[ref_Sigma2]]
====== Generate and Send Sigma2

If <<ref_VALIDATE_S1, validation>> is successful, the responder encodes and sends a `Sigma2` message.

[[ref_sigma-2-struct]]
[subs="+macros"]
----
sigma-2-tbsdata => STRUCTURE [ tag-order ]
{
  responderNOC       [1] : OCTET STRING,
  responderEphPubKey [2] : <<ref_ec-pub-key, ec-pub-key>>,
  initiatorEphPubKey [3] : <<ref_ec-pub-key, ec-pub-key>>,
}

sigma-2-tbedata => STRUCTURE [ tag-order ]
{
  responderNOC [1] : OCTET STRING,
  signature    [2] : <<ref_ec-signature, ec-signature>>,
}

sigma-2-struct => STRUCTURE [ tag-order ]
{
  responderRandom    [1] : OCTET STRING [ length 32 ],
  responderSessionId [2] : UNSIGNED INTEGER [ range 16bits ],
  responderEphPubKey [3] : <<ref_ec-pub-key, ec-pub-key>>,
  encrypted2         [4] : OCTET STRING,
}
```

^^^ Tag IDs are contextual to a structure.

File: src/protocols/secure_channel/CASESession.cpp [hunk 16]
```diff
@@ -282,6 +265,8 @@ CHIP_ERROR CASESession::EstablishSession(const Transport::PeerAddress peerAddres
     mExchangeCtxt->SetResponseTimeout(kSigma_Response_Timeout);
     mConnectionState.SetPeerAddress(peerAddress);
     mConnectionState.SetPeerNodeId(peerNodeId);
+    // TODO: implement API for this in OperationalCredentialSet
+    mTrustedRootId = operationalCredentialSet->GetOpCredSet()[opCredSetIndex].GetCertSet()[0].mAuthKeyId;
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:269]: This indexing is unsafe. There must be bound checks to ensure the indices are correct. Perhaps step 1 is to implement the API needed in OperationalCredentialSet, and then be able to rely on it.

File: src/protocols/secure_channel/CASESession.cpp [hunk 17]
```diff
@@ -335,57 +320,50 @@ CHIP_ERROR CASESession::DeriveSecureSession(SecureSession & session, SecureSessi
...
-                              mOpCredSet->GetCertCount() * kTrustedRootIdSize + kP256_PublicKey_Length + sizeof(uint64_t) * 4);
+    uint16_t data_len = static_cast<uint16_t>(kSigmaParamRandomNumberSize + sizeof(uint16_t) + kMAX_Hash_Length +
+                                              kP256_PublicKey_Length + sizeof(uint64_t) * 4);
 
     System::PacketBufferTLVWriter tlvWriter;
     System::PacketBufferHandle msg_R1;
     TLV::TLVType outerContainerType                      = TLV::kTLVType_NotSpecified;
     uint8_t initiatorRandom[kSigmaParamRandomNumberSize] = { 0 };
+    uint8_t destinationIdentifier[kMAX_Hash_Length]      = { 0 };
+    // TODO: Parameterize fabricId instead of hardcoding it to 0
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:331]: This is important, because we have to make sure both sides share correct fabric ID, rather than assume it. This has to be validated during CASE when processing R2/R3

File: src/protocols/secure_channel/CASESession.cpp [hunk 18]
```diff
@@ -413,7 +391,8 @@ CHIP_ERROR CASESession::HandleSigmaR1(System::PacketBufferHandle & msg)
     TLV::TLVType containerType = TLV::kTLVType_Structure;
 
     uint16_t encryptionKeyId = 0;
-    uint32_t n_trusted_roots;
+    uint8_t destinationIdentifier[kMAX_Hash_Length];
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:394]: For this to be future-safe, we need to use `kSHA256_Hash_Length` rather than kMAX_Hash_Length everywhere, since destinationId is organized based on SHA256

File: src/protocols/secure_channel/CASESession.cpp [hunk 19]
```diff
@@ -1115,50 +1073,85 @@ void CASESession::SendErrorMsg(SigmaErrorType errorCode)
...
-CHIP_ERROR CASESession::FindValidTrustedRoot(const System::PacketBufferTLVReader & tlvReader, uint32_t nTrustedRoots)
+CHIP_ERROR CASESession::GenerateDestinationID(const ByteSpan & random, const Credentials::CertificateKeyId * trustedRootId,
+                                              NodeId nodeId, FabricId fabricId, MutableByteSpan & destinationId)
 {
-    CertificateKeyId trustedRoot;
-    System::PacketBufferTLVReader suppTlvReader;
-    uint8_t trustedRootId[kTrustedRootIdSize];
+    HMAC_sha hmac;
+    uint16_t destinationMessageLen = kSigmaParamRandomNumberSize + kP256_PublicKey_Length + sizeof(FabricId) + sizeof(NodeId);
+    System::PacketBufferHandle destinationMessage = System::PacketBufferHandle::New(destinationMessageLen);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1081]: This should not use packet buffers as memory. Use a `ScopedBuffer` instead if heap is needed.

Overall, the size here could be made a constant expression, and the buffer could be done cheaper by using a stack buffer. The length will be 32 + 65 + 8 + 8 = 113 bytes, which is not crazy. It's possibly less stack then the entire alloc chain below.


```
constexpr size_t destinationMessageLen = kSigmaParamRandomNumberSize + kP256_PublicKey_Length + sizeof(FabricId) + sizeof(NodeId);

uint8_t bbuf[destinationMessageLen];
```

File: src/protocols/secure_channel/CASESession.cpp [hunk 20]
```diff
@@ -1115,50 +1073,85 @@ void CASESession::SendErrorMsg(SigmaErrorType errorCode)
...
+    const ChipCertificateData * rootCertificate   = mOpCredSet->GetRootCertificate(*trustedRootId);
+    VerifyOrReturnError(!destinationMessage.IsNull(), CHIP_ERROR_NO_MEMORY);
+    VerifyOrReturnError(rootCertificate != nullptr, CHIP_ERROR_CERT_NOT_FOUND);
+    VerifyOrReturnError(!rootCertificate->mPublicKey.empty(), CHIP_ERROR_INTERNAL);
+    VerifyOrReturnError(rootCertificate->mPublicKey.size() == kP256_PublicKey_Length, CHIP_ERROR_INTERNAL);
+
+    Encoding::LittleEndian::BufferWriter bbuf(destinationMessage->Start(), destinationMessageLen);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1088]: This actually needs to be `Encoding::BigEndian`

File: src/protocols/secure_channel/CASESession.cpp [hunk 21]
```diff
@@ -1170,13 +1163,13 @@ CHIP_ERROR CASESession::ConstructSaltSigmaR2(const ByteSpan & rand, const P256Pu
     return CHIP_NO_ERROR;
 }
 
-CHIP_ERROR CASESession::ConstructSaltSigmaR3(const uint8_t * ipk, size_t ipkLen, MutableByteSpan & salt)
+CHIP_ERROR CASESession::ConstructSaltSigmaR3(const ByteSpan & ipk, MutableByteSpan & salt)
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1166]: Thanks for updating a lot of these to use ByteSpan

File: src/protocols/secure_channel/CASESession.cpp (hunk 9 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp:825]: Updated.

File: src/transport/AdminPairingTable.cpp (hunk 12 above)
Comment (jpk233) [reply src/transport/AdminPairingTable.cpp:377]: We're using uint8_t because the return type of the GetCertCount method from OperationalCredentialSet Class is uint8_t.
I agree with your suggestion, but could we address that in a separate PR since the OperationalCredentialSet will need a complete refactor to replace all uint8_t refs to size_t?

File: src/controller/CHIPDevice.h (hunk 10 above)
Comment (jpk233) [reply src/controller/CHIPDevice.h:480]: Because all other members of the ControllerDeviceInitParams struct are pointers. I did it like this to follow the convention.
Also, I think it makes sense to rely on the true credentialsIndex variable which is present in DeviceController class

File: src/protocols/secure_channel/CASESession.cpp (hunk 15 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Thanks, updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 18 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 17 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/protocols/secure_channel/tests/TestCASESession.cpp (hunk 13 above)
Comment (jpk233) [reply src/protocols/secure_channel/tests/TestCASESession.cpp:70]: Added GenerateDestinationID test.

File: src/protocols/secure_channel/CASESession.cpp (hunk 14 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 16 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 19 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 21 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp:1140]: No problem, needed to be done anyway.

File: src/channel/Channel.h [hunk 22]
```diff
@@ -83,6 +83,13 @@ class ChannelBuilder
     }
     NodeId GetPeerNodeId() const { return mPeerNodeId; }
 
+    ChannelBuilder & SetPeerFabricId(FabricId peerFabricId)
```
Comment (msandstedt) [inline src/channel/Channel.h:86]: It does not make sense to me that we would have a `mPeerFabricId`, and particularly not a public setter.  Isn't the source of truth for this the fabric ID in `mOperationalCredentialSet[mOperationalCredentialSetIndex]`?  Why duplicate this information?  That seems like a good way to get into an inconsistent state.

File: src/controller/CHIPDevice.h (hunk 10 above)
Comment (msandstedt) [reply src/controller/CHIPDevice.h:481]: It is entirely possible to use the Device object outside of the `chip::Device::DeviceController`.  Or stated another way, it's possible (and currently necessary in some cases) to roll your own controller.  Dependencies like this on the `chip::Device::DeviceController` object are going to create problems.

I think this also shows a larger problem with the `OperationalCredentialSet` object, which can only hold `kOperationalCredentialsMax` credentials.  Why?  This is only the spec-candidate minimum.  If I want to hold 1000 sets of credentials and I can fit these in memory, I should be able to.

I think we need an object that holds only a single set of credentials and that's what this  object, the channel, should reference.  It's impossible for a channel to use multiple credentials simultaneously, so why does it need a handle to more than one?

File: src/transport/AdminPairingTable.cpp (hunk 12 above)
Comment (msandstedt) [reply src/transport/AdminPairingTable.cpp:377]: Also mentioned this above.  I think the idea of `OperationalCredentialSet` is really the problem.  Why do we have an object with a fixed space for `kOperationalCredentialsMax`?  What is the utility of bundling these all together like that?  An object like this can't possibly fulfill all use cases.  The only limitation for the number of supported fabrics should be memory size.

File: src/controller/CHIPDevice.h (hunk 10 above)
Comment (jpk233) [reply src/controller/CHIPDevice.h:481]: I agree with this, but I think it should be addressed in a separate PR because the OperationalCredentialSet requires a complete refactor.

File: src/protocols/secure_channel/CASESession.h (hunk 11 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.h]: Updated.

File: src/channel/Channel.h (hunk 22 above)
Comment (jpk233) [reply src/channel/Channel.h]: Updated.

File: src/transport/AdminPairingTable.cpp (hunk 12 above)
Comment (jpk233) [reply src/transport/AdminPairingTable.cpp:377]: As mentioned above, I think it should be addressed in a separate PR because the OperationalCredentialSet requires a complete refactor.

File: src/controller/CHIPDevice.h (hunk 10 above)
Comment (tcarmelveilleux) [reply src/controller/CHIPDevice.h:477]: Could you please open an issue related to the follow-up and add its number to the TODOs you had to address later?

File: src/credentials/CHIPCert.cpp [hunk 23]
```diff
@@ -318,6 +318,17 @@ CHIP_ERROR ChipCertificateSet::LoadCerts(TLVReader & reader, BitFlags<CertDecode
     return err;
 }
 
+CHIP_ERROR ChipCertificateSet::ReleaseLastCert()
+{
+    const ChipCertificateData * lastCert = GetLastCert();
+    VerifyOrReturnError(lastCert != nullptr, CHIP_ERROR_INTERNAL);
+
+    lastCert->~ChipCertificateData();
```
Comment (tcarmelveilleux) [inline src/credentials/CHIPCert.cpp:326]: This is very odd: a const pointer, but were we call what is ostensibly a mutating destructor. Is there a cleaner way to do this, or a new public method that can be added to ChipCertificateData? Does this leak anything?

File: src/credentials/CHIPCert.cpp [hunk 24]
```diff
@@ -753,6 +764,29 @@ CHIP_ERROR ChipDN::GetCertChipId(uint64_t & chipId) const
...
+    uint8_t rdnCount = RDNCount();
+
+    fabricId = 0;
+
+    for (uint8_t i = 0; i < rdnCount; i++)
+    {
+        switch (rdn[i].mAttrOID)
+        {
+        case kOID_AttributeType_ChipFabricId:
+            VerifyOrReturnError(fabricId == 0, CHIP_ERROR_WRONG_CERT_TYPE);
```
Comment (tcarmelveilleux) [inline src/credentials/CHIPCert.cpp:778]: Why this condition? How could it occur?

File: src/credentials/CHIPCert.h [hunk 25]
```diff
@@ -467,6 +476,11 @@ class DLL_EXPORT ChipCertificateSet
      **/
     CHIP_ERROR LoadCerts(chip::TLV::TLVReader & reader, BitFlags<CertDecodeFlags> decodeFlags);
 
+    /**
+     * @brief Release last certificate data in the set.
```
Comment (tcarmelveilleux) [inline src/credentials/CHIPCert.h:480]: The name already says this. Why is this useful? Is there a possibility of composing other existing methods to do the same without a new method?

File: src/credentials/CHIPOperationalCredentials.cpp [hunk 26]
```diff
@@ -364,5 +364,24 @@ P256Keypair * OperationalCredentialSet::GetNodeKeypairAt(const CertificateKeyId
     return nullptr;
 }
 
+const ChipCertificateData * OperationalCredentialSet::GetRootCertificate(const CertificateKeyId & trustedRootId) const
+{
+    for (uint8_t i = 0; i < mOpCredCount; i++)
```
Comment (tcarmelveilleux) [inline src/credentials/CHIPOperationalCredentials.cpp:369]: Please change any indexing using uint8_t to size_t. This is, as @msandstedt pointed-out, an artificial limitation on maximum number of certs available in these primitive building block classes.

File: src/protocols/secure_channel/tests/TestCASESession.cpp [hunk 27]
```diff
@@ -435,6 +453,56 @@ void CASE_SecurePairingSerializeTest(nlTestSuite * inSuite, void * inContext)
     chip::Platform::Delete(testPairingSession2);
 }
 
+void CASE_DestinationIDGenerationTest(nlTestSuite * inSuite, void * inContext)
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/tests/TestCASESession.cpp:456]: This does not test the version present in the spec. How was this test case generated? Why not test against the test vectors from the spec?

File: src/protocols/secure_channel/tests/TestCASESession.cpp [hunk 28]
```diff
@@ -435,6 +453,56 @@ void CASE_SecurePairingSerializeTest(nlTestSuite * inSuite, void * inContext)
...
+                   ctx.GetExchangeManager().RegisterUnsolicitedMessageHandlerForType(
+                       Protocols::SecureChannel::MsgType::CASE_SigmaR1, &pairingAccessory) == CHIP_NO_ERROR);
+
+    NL_TEST_ASSERT(inSuite,
+                   pairingAccessory.ListenForSessionEstablishment(&accessoryDevOpCred, 0, &delegateAccessory) == CHIP_NO_ERROR);
+
+    NL_TEST_ASSERT(inSuite,
+                   pairingCommissioner.EstablishSession(Transport::PeerAddress(Transport::Type::kBle), &commissionerDevOpCred,
+                                                        commissionerCredentialsIndex, Node01_01, 0, context,
+                                                        &delegate) == CHIP_NO_ERROR);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/tests/TestCASESession.cpp:494]: None of these steps should be necessary. GenerateDestinationID() should be stateless and just take as arguments the necessary parameters, so that it's easier to test without dependencies to otehr data sources in setup. Destination IDs is a hash of a few values.

File: src/protocols/secure_channel/CASEServer.cpp [hunk 29]
```diff
@@ -73,7 +73,8 @@ CHIP_ERROR CASEServer::InitCASEHandshake(Messaging::ExchangeContext * ec)
     }
     ReturnErrorCodeIf(admin == nullptr, CHIP_ERROR_INVALID_ARGUMENT);
 
-    ReturnErrorOnFailure(admin->GetCredentials(mCredentials, mCertificates, mRootKeyId));
+    uint8_t credentialsIndex;
+    ReturnErrorOnFailure(admin->GetCredentials(mCredentials, mCertificates, mRootKeyId, credentialsIndex));
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASEServer.cpp:77]: If this returns on failure, the `mAdmins->LoadFromStorage(mAdminId)` causes memory to remain cached and not released. How is it cleaned-up?

File: src/protocols/secure_channel/CASESession.cpp [hunk 30]
```diff
@@ -44,21 +45,22 @@ using namespace Crypto;
...
 constexpr size_t kKDFSEInfoLength = sizeof(kKDFSEInfo);
 
-constexpr uint8_t kIVSR2[] = { 0x4e, 0x43, 0x41, 0x53, 0x45, 0x5f, 0x53, 0x69, 0x67, 0x6d, 0x61, 0x52, 0x32 };
-constexpr uint8_t kIVSR3[] = { 0x4e, 0x43, 0x41, 0x53, 0x45, 0x5f, 0x53, 0x69, 0x67, 0x6d, 0x61, 0x52, 0x33 };
-constexpr size_t kIVLength = sizeof(kIVSR2);
+constexpr uint8_t kTBEData2_Nonce[] =
+    /* "NCASE_Sigma2N" */ { 0x4e, 0x43, 0x41, 0x53, 0x45, 0x5f, 0x53, 0x69, 0x67, 0x6d, 0x61, 0x32, 0x4e };
+constexpr uint8_t kTBEData3_Nonce[] =
+    /* "NCASE_Sigma3N" */ { 0x4e, 0x43, 0x41, 0x53, 0x45, 0x5f, 0x53, 0x69, 0x67, 0x6d, 0x61, 0x33, 0x4e };
+constexpr size_t kTBEDataNonceLength = sizeof(kTBEData2_Nonce);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:58]:
```suggestion
constexpr size_t kTBEDataNonceLength = sizeof(kTBEData2_Nonce);
static_assert(sizeof(kTBEData2_Nonce) == sizeof(kTBEData3_Nonce),"TBEData2_Nonce and TBEData3_Nonce must be same size");
```

File: src/protocols/secure_channel/CASESession.cpp [hunk 31]
```diff
@@ -339,57 +300,54 @@ CHIP_ERROR CASESession::DeriveSecureSession(SecureSession & session, SecureSessi
 
 CHIP_ERROR CASESession::SendSigmaR1()
 {
-    uint16_t data_len =
-        static_cast<uint16_t>(kSigmaParamRandomNumberSize + sizeof(uint16_t) + sizeof(uint16_t) +
-                              mOpCredSet->GetCertCount() * kTrustedRootIdSize + kP256_PublicKey_Length + sizeof(uint64_t) * 4);
+    uint16_t data_len = static_cast<uint16_t>(kSigmaParamRandomNumberSize + sizeof(uint16_t) + kSHA256_Hash_Length +
+                                              kP256_PublicKey_Length + sizeof(uint64_t) * 4);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:304]: It would be good to have an "estimate struct overhead" method that takes data sizes and "number of fields overall" and does the heuristic above, so that the heuristic of "sizeof(uint64_t)-ish per TLV field should do" is clearer.

File: src/protocols/secure_channel/CASESession.cpp [hunk 32]
```diff
@@ -339,57 +300,54 @@ CHIP_ERROR CASESession::DeriveSecureSession(SecureSession & session, SecureSessi
...
-            ReturnErrorOnFailure(tlvWriter.PutBytes(CASETLVTag::kTrustedRootID, trustedRootId.data(), trustedRootId.size()));
-        }
+        ChipCertificateData nodeOperationalCertificate;
+        FabricId fabricId;
+        MutableByteSpan destinationIdSpan(destinationIdentifier, sizeof(destinationIdentifier));
+
+        ReturnErrorOnFailure(DecodeChipCert(mOpCredSet->GetDevOpCred(mTrustedRootId), mOpCredSet->GetDevOpCredLen(mTrustedRootId),
+                                            nodeOperationalCertificate));
+        ReturnErrorOnFailure(nodeOperationalCertificate.mSubjectDN.GetCertFabricId(fabricId));
+        ReturnErrorOnFailure(GenerateDestinationID(ByteSpan(initiatorRandom, sizeof(initiatorRandom)), &mTrustedRootId,
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:339]: GenerateDestinationID should take-in the IPK and public key of the root cert, rather than directly access the certs. Makes it more testable and less stateful.

File: src/protocols/secure_channel/CASESession.cpp [hunk 33]
```diff
@@ -430,38 +389,42 @@ CHIP_ERROR CASESession::HandleSigmaR1(System::PacketBufferHandle & msg)
     err = tlvReader.EnterContainer(containerType);
     SuccessOrExit(err);
 
-    err = tlvReader.FindElementWithTag(CASETLVTag::kSessionID, suppTlvReader);
+    err = tlvReader.FindElementWithTag(TLV::ContextTag(1), suppTlvReader);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:392]: The spec expect tag-order. This reads in any order. There should be a utility method to "ensure at least N context tags in order starting at tag M", as a pre-validation of schema. Then `FindElementWithTag` is fine once that is validated.

File: src/protocols/secure_channel/CASESession.cpp [hunk 34]
```diff
@@ -430,38 +389,42 @@ CHIP_ERROR CASESession::HandleSigmaR1(System::PacketBufferHandle & msg)
...
+    SuccessOrExit(err);
+    VerifyOrExit(kSigmaParamRandomNumberSize == suppTlvReader.GetLength(), err = CHIP_ERROR_INVALID_TLV_ELEMENT);
+    VerifyOrExit(suppTlvReader.GetType() == TLV::kTLVType_ByteString, err = CHIP_ERROR_WRONG_TLV_TYPE);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:395]: Isn't this condition handled by error return of GetBytes() below?

File: src/protocols/secure_channel/CASESession.cpp [hunk 35]
```diff
@@ -430,38 +389,42 @@ CHIP_ERROR CASESession::HandleSigmaR1(System::PacketBufferHandle & msg)
...
+    err = suppTlvReader.GetBytes(initiatorRandom, sizeof(initiatorRandom));
+    SuccessOrExit(err);
+
+    err = tlvReader.FindElementWithTag(TLV::ContextTag(2), suppTlvReader);
     SuccessOrExit(err);
     err = suppTlvReader.Get(encryptionKeyId);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:401]: Please rename `encryptionKeyId` to `initiatorSessionId`

File: src/protocols/secure_channel/CASESession.cpp [hunk 36]
```diff
@@ -339,57 +300,54 @@ CHIP_ERROR CASESession::DeriveSecureSession(SecureSession & session, SecureSessi
...
-    ReturnErrorOnFailure(tlvWriter.PutBytes(CASETLVTag::kInitiatorEphPubKey, mEphemeralKey.Pubkey(),
-                                            static_cast<uint32_t>(mEphemeralKey.Pubkey().Length())));
+    ReturnErrorOnFailure(tlvWriter.PutBytes(TLV::ContextTag(3), destinationIdentifier, sizeof(destinationIdentifier)));
 
+    ReturnErrorOnFailure(
+        tlvWriter.PutBytes(TLV::ContextTag(4), mEphemeralKey.Pubkey(), static_cast<uint32_t>(mEphemeralKey.Pubkey().Length())));
     ReturnErrorOnFailure(tlvWriter.EndContainer(outerContainerType));
     ReturnErrorOnFailure(tlvWriter.Finalize(&msg_R1));
 
     ReturnErrorOnFailure(mCommissioningHash.AddData(msg_R1->Start(), msg_R1->DataLength()));
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:349]: @balducci-apple We are computing transcript on pre-header payloads here and not including the headers, and at receiver, just on the payload as well. Please provide a link to spec issue where we clarify which is which.

For now, I consider this "to-spec", as written, but the intent is clearly not respected fully since parts of the message (headers) are not under transcript.

File: src/protocols/secure_channel/CASESession.cpp [hunk 37]
```diff
@@ -498,114 +461,103 @@ CHIP_ERROR CASESession::SendSigmaR2()
...
 
-    // Step 1
     // Fill in the random value
     err = DRBG_get_bytes(msg_rand.Get(), kSigmaParamRandomNumberSize);
     SuccessOrExit(err);
 
-    // Step 3
-    // hardcoded to use a p256keypair
+    // Generate an ephemeral keypair
 #ifdef ENABLE_HSM_CASE_EPHERMAL_KEY
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:469]: There is a typo on this define.

File: src/protocols/secure_channel/CASESession.cpp [hunk 38]
```diff
@@ -498,114 +461,103 @@ CHIP_ERROR CASESession::SendSigmaR2()
...
     {
         TLV::TLVWriter tlvWriter;
         TLV::TLVType outerContainerType = TLV::kTLVType_NotSpecified;
 
         tlvWriter.Init(msg_R2_Signed.Get(), msg_r2_signed_len);
         SuccessOrExit(err = tlvWriter.StartContainer(TLV::AnonymousTag, TLV::kTLVType_Structure, outerContainerType));
-        SuccessOrExit(err = tlvWriter.PutBytes(CASETLVTag::kResponderEphPubKey, mEphemeralKey.Pubkey(),
-                                               static_cast<uint32_t>(mEphemeralKey.Pubkey().Length())));
-        SuccessOrExit(err = tlvWriter.PutBytes(CASETLVTag::kNOC, mOpCredSet->GetDevOpCred(mTrustedRootId),
+        SuccessOrExit(err = tlvWriter.PutBytes(TLV::ContextTag(1), mOpCredSet->GetDevOpCred(mTrustedRootId),
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:502]: The spec calls for a `chip-certificate-array` format. When reading all the docs for `GetDevOpCred` and associated values, it's not clear at all that the format is chip-certificate-array. Is it the case?

File: src/protocols/secure_channel/CASEServer.cpp (hunk 29 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASEServer.cpp:77]: It should be handled by DeviceController::Shutdown() method

File: src/credentials/CHIPCert.cpp (hunk 24 above)
Comment (jpk233) [reply src/credentials/CHIPCert.cpp:778]: This method will retrieve the Certificate Fabric ID. At the same time, that condition will check if there is only one FabricId present in the Certificate. If there's two or more, then the method will fail.

File: src/protocols/secure_channel/CASESession.cpp [hunk 39]
```diff
@@ -1119,50 +1057,82 @@ void CASESession::SendErrorMsg(SigmaErrorType errorCode)
...
 {
     uint8_t md[kSHA256_Hash_Length];
     memset(salt.data(), 0, salt.size());
     Encoding::LittleEndian::BufferWriter bbuf(salt.data(), salt.size());
 
-    bbuf.Put(ipk, ipkLen);
+    bbuf.Put(ipk.data(), ipk.size());
     bbuf.Put(rand.data(), kSigmaParamRandomNumberSize);
     bbuf.Put(pubkey, pubkey.Length());
     ReturnErrorOnFailure(mCommissioningHash.Finish(md));
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1138]: The Finish() followed by Begin() on mCommissioningHash means that we are losing the "total" transcript. The transcript was meant to be only Msg1:

image

The full transcript hash is required to generate the session key, but it will be lost from this new Begin().

See:
image


@balducci-apple Could you please take a peek at transcript computation overall in this branch?

File: src/protocols/secure_channel/CASESession.cpp [hunk 40]
```diff
@@ -1119,50 +1057,82 @@ void CASESession::SendErrorMsg(SigmaErrorType errorCode)
...
     }
+
     VerifyOrReturnError(!mTrustedRootId.empty(), CHIP_ERROR_CERT_NOT_TRUSTED);
 
     return CHIP_NO_ERROR;
 }
 
-CHIP_ERROR CASESession::ConstructSaltSigmaR2(const ByteSpan & rand, const P256PublicKey & pubkey, const uint8_t * ipk,
-                                             size_t ipkLen, MutableByteSpan & salt)
+CHIP_ERROR CASESession::ConstructSaltSigmaR2(const ByteSpan & rand, const Crypto::P256PublicKey & pubkey, const ByteSpan & ipk,
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1128]: Not an applicable diff line, but there are a not of CHIP_ERROR_NO_MEMORY errors for `writer.Fit()` failing that should be CHIP_ERROR_BUFFER_TOO_SMALL

File: src/protocols/secure_channel/CASESession.cpp [hunk 41]
```diff
@@ -498,114 +461,103 @@ CHIP_ERROR CASESession::SendSigmaR2()
...
         MutableByteSpan saltSpan(msg_salt.Get(), saltlen);
-        err = ConstructSaltSigmaR2(ByteSpan(msg_rand.Get(), kSigmaParamRandomNumberSize), mEphemeralKey.Pubkey(), mIPK,
-                                   sizeof(mIPK), saltSpan);
+        err = ConstructSaltSigmaR2(ByteSpan(msg_rand.Get(), kSigmaParamRandomNumberSize), mEphemeralKey.Pubkey(),
+                                   ByteSpan(mIPK, sizeof(mIPK)), saltSpan);
         SuccessOrExit(err);
     }
 
     err = mHKDF.HKDF_SHA256(mSharedSecret, mSharedSecret.Length(), msg_salt.Get(), saltlen, kKDFSR2Info, kKDFInfoLength, sr2k,
                             kAEADKeySize);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:487]: `kAEADKeySize` should be deleted from this file and every mention of it should be the canonical `CHIP_CRYPTO_SYMMETRIC_KEY_LENGTH_BITS` (which I now realize is missing from CHIPCryptoPAL.h :( 

This could be left as a TODO where kAEADKeySize is defined.

File: src/protocols/secure_channel/CASESession.cpp [hunk 42]
```diff
@@ -498,114 +461,103 @@ CHIP_ERROR CASESession::SendSigmaR2()
...
 
         tlvWriter.Init(std::move(msg_R2));
         SuccessOrExit(err = tlvWriter.StartContainer(TLV::AnonymousTag, TLV::kTLVType_Structure, outerContainerType));
-        SuccessOrExit(err = tlvWriter.PutBytes(CASETLVTag::kRandom, msg_rand.Get(), kSigmaParamRandomNumberSize));
-        SuccessOrExit(err = tlvWriter.Put(CASETLVTag::kSessionID, mConnectionState.GetLocalKeyID(), true));
-        SuccessOrExit(err = tlvWriter.PutBytes(CASETLVTag::kTrustedRootID, mTrustedRootId.data(),
-                                               static_cast<uint32_t>(mTrustedRootId.size())));
-        SuccessOrExit(err = tlvWriter.PutBytes(CASETLVTag::kResponderEphPubKey, mEphemeralKey.Pubkey(),
+        SuccessOrExit(err = tlvWriter.PutBytes(TLV::ContextTag(1), msg_rand.Get(), kSigmaParamRandomNumberSize));
+        SuccessOrExit(err = tlvWriter.Put(TLV::ContextTag(2), mConnectionState.GetLocalKeyID(), true));
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:556]: `GetLocalKeyID()` should be called `GetLocalSessionID`

File: src/protocols/secure_channel/CASESession.cpp [hunk 43]
```diff
@@ -498,114 +461,103 @@ CHIP_ERROR CASESession::SendSigmaR2()
...
+        SuccessOrExit(err = tlvWriter.PutBytes(TLV::ContextTag(3), mEphemeralKey.Pubkey(),
                                                static_cast<uint32_t>(mEphemeralKey.Pubkey().Length())));
-        SuccessOrExit(err = tlvWriter.PutBytes(CASETLVTag::kEncryptedData, msg_R2_Encrypted.Get(), msg_r2_signed_enc_len));
-        SuccessOrExit(err = tlvWriter.PutBytes(CASETLVTag::kTag, tag, sizeof(tag)));
+        SuccessOrExit(err = tlvWriter.PutBytes(TLV::ContextTag(4), msg_R2_Encrypted.Get(), msg_r2_signed_enc_len));
+        SuccessOrExit(err = tlvWriter.PutBytes(TLV::ContextTag(5), tag, sizeof(tag)));
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:560]: Tag 5 does not exist. The "tag" (i.e. message tag from  from `AES_CCM_encrypt` must be concatenated to the encrypted data.

The crypto primitive in spec:
```
byte[lengthInBytes(P) + CHIP_CRYPTO_AEAD_MIC_LENGTH_BYTES]
CHIP_Crypto_AEAD_GenerateEncrypt(
     SymmetricKey K,
     byte[lengthInBytes(P)] P,
     byte[] A,
     byte[CHIP_CRYPTO_AEAD_NONCE_LENGTH_BYTES] N)
```

The buffer for msg_R2_Encrypted  should have been allocated with at least kAEADKeySize extra, and then pointed the tag buffer to `msg_R2_Encrypted.Get() + msg_r2_signed_enc_len` so that the tag is emitted at the end, rather than in a separate buffer.

File: src/protocols/secure_channel/CASESession.cpp [hunk 44]
```diff
@@ -732,24 +679,24 @@ CHIP_ERROR CASESession::HandleSigmaR2(System::PacketBufferHandle & msg)
...
+    err = tlvReader.FindElementWithTag(TLV::ContextTag(4), suppTlvReader);
     SuccessOrExit(err);
     VerifyOrExit(suppTlvReader.GetType() == TLV::kTLVType_ByteString, err = CHIP_ERROR_WRONG_TLV_TYPE);
     VerifyOrExit(msg_R2_Encrypted.Alloc(suppTlvReader.GetLength()), err = CHIP_ERROR_NO_MEMORY);
     msg_r2_encrypted_len = static_cast<uint16_t>(suppTlvReader.GetLength());
     err                  = suppTlvReader.GetBytes(msg_R2_Encrypted.Get(), msg_r2_encrypted_len);
     SuccessOrExit(err);
 
-    err = tlvReader.FindElementWithTag(CASETLVTag::kTag, suppTlvReader);
+    err = tlvReader.FindElementWithTag(TLV::ContextTag(5), suppTlvReader);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:691]: MIC tag should be extracted from the last kAEADKeySize bytes of ContextTag 4

File: src/protocols/secure_channel/CASESession.cpp [hunk 45]
```diff
@@ -916,9 +856,9 @@ CHIP_ERROR CASESession::SendSigmaR3()
         tlvWriter.Init(std::move(msg_R3));
         err = tlvWriter.StartContainer(TLV::AnonymousTag, TLV::kTLVType_Structure, outerContainerType);
         SuccessOrExit(err);
-        err = tlvWriter.PutBytes(CASETLVTag::kEncryptedData, msg_R3_Encrypted.Get(), msg_r3_encrypted_len);
+        err = tlvWriter.PutBytes(TLV::ContextTag(1), msg_R3_Encrypted.Get(), msg_r3_encrypted_len);
         SuccessOrExit(err);
-        err = tlvWriter.PutBytes(CASETLVTag::kTag, tag, sizeof(tag));
+        err = tlvWriter.PutBytes(TLV::ContextTag(2), tag, sizeof(tag));
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:861]: Tag should be part of ContextTag 1

File: src/protocols/secure_channel/CASESession.cpp [hunk 46]
```diff
@@ -1045,36 +982,37 @@ CHIP_ERROR CASESession::HandleSigmaR3(System::PacketBufferHandle & msg)
...
-    err = decryptedDataTlvReader.FindElementWithTag(CASETLVTag::kNOC, suppTlvReader);
+    err = decryptedDataTlvReader.FindElementWithTag(TLV::ContextTag(1), suppTlvReader);
     SuccessOrExit(err);
     VerifyOrExit(suppTlvReader.GetType() == TLV::kTLVType_ByteString, err = CHIP_ERROR_WRONG_TLV_TYPE);
     responderOpCertLen = static_cast<uint16_t>(suppTlvReader.GetLength());
     err                = suppTlvReader.GetBytes(responderOpCert, responderOpCertLen);
     SuccessOrExit(err);
 
-    // Step 3
+    // Step 5
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:992]: This is steps 5/6 together I think:

image

File: src/protocols/secure_channel/CASESession.cpp [hunk 47]
```diff
@@ -1045,36 +982,37 @@ CHIP_ERROR CASESession::HandleSigmaR3(System::PacketBufferHandle & msg)
...
 
-    err = ConstructTBS3Data(responderOpCert, responderOpCertLen, msg_R3_Signed.Get(), msg_r3_signed_len);
+    err = ConstructTBS3Data(ByteSpan(responderOpCert, responderOpCertLen), msg_R3_Signed.Get(), msg_r3_signed_len);
     SuccessOrExit(err);
 
-    err = decryptedDataTlvReader.FindElementWithTag(CASETLVTag::kSignature, suppTlvReader);
+    err = decryptedDataTlvReader.FindElementWithTag(TLV::ContextTag(2), suppTlvReader);
     SuccessOrExit(err);
     VerifyOrExit(suppTlvReader.GetType() == TLV::kTLVType_ByteString, err = CHIP_ERROR_WRONG_TLV_TYPE);
     VerifyOrExit(sigmaR3SignedData.Capacity() >= suppTlvReader.GetLength(), err = CHIP_ERROR_INVALID_TLV_ELEMENT);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1010]: A better name for sigmaR3SignedData is `TBSData3Signature`. Tag 2 contains a signature, not "signed" data.

File: src/protocols/secure_channel/CASESession.cpp [hunk 48]
```diff
@@ -1119,50 +1057,82 @@ void CASESession::SendErrorMsg(SigmaErrorType errorCode)
                    ChipLogError(SecureChannel, "Failed to send error message"));
 }
 
-CHIP_ERROR CASESession::FindValidTrustedRoot(const System::PacketBufferTLVReader & tlvReader, uint32_t nTrustedRoots)
+CHIP_ERROR CASESession::GenerateDestinationID(const ByteSpan & random, const Credentials::CertificateKeyId * trustedRootId,
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1060]: Suggest making this take in just the raw public key of the trusted root, rather than needing to get access to state (`mOpCredSet`) from within the primitive. That would make testing easier.

File: src/protocols/secure_channel/CASESession.cpp [hunk 49]
```diff
@@ -1119,50 +1057,82 @@ void CASESession::SendErrorMsg(SigmaErrorType errorCode)
...
-    trustedRoot = CertificateKeyId(trustedRootId);
+    bbuf.Put(random.data(), random.size());
+    bbuf.Put(rootCertificate->mPublicKey.data(), rootCertificate->mPublicKey.size());
+    bbuf.Put64(fabricId);
+    bbuf.Put64(nodeId);
+
+    VerifyOrReturnError(bbuf.Fit(), CHIP_ERROR_NO_MEMORY);
 
-    for (uint32_t i = 0; i < nTrustedRoots; ++i)
+    // retrieve Fabric IPK
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1079]: IPK should be passed as an argument. The loop in `FindDestinationIdCandidate()` forgets to iterate over all IPKs. At least if the list of IPKs, instead of coming from a crypto store API, came from a local list in  `FindDestinationIdCandidate()`, with a TODO to actually populate w/ each IPK for the given fabric, it would allow moving to "fully correct" impl with just changing how that IPK list is obtained, rather than chaning this method structurally.

File: src/protocols/secure_channel/CASESession.cpp [hunk 50]
```diff
@@ -1174,13 +1144,13 @@ CHIP_ERROR CASESession::ConstructSaltSigmaR2(const ByteSpan & rand, const P256Pu
...
 
-CHIP_ERROR CASESession::ConstructSaltSigmaR3(const uint8_t * ipk, size_t ipkLen, MutableByteSpan & salt)
+CHIP_ERROR CASESession::ConstructSaltSigmaR3(const ByteSpan & ipk, MutableByteSpan & salt)
 {
     uint8_t md[kSHA256_Hash_Length];
     memset(salt.data(), 0, salt.size());
     Encoding::LittleEndian::BufferWriter bbuf(salt.data(), salt.size());
 
-    bbuf.Put(ipk, ipkLen);
+    bbuf.Put(ipk.data(), ipk.size());
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1153]: The hash should not be finished here either. I will update the SHA256 stream impl to enable "incremental digest".

**Review by tcarmelveilleux — CHANGES_REQUESTED** [review]
Found several inconsistencies from spec remaining. Can approve once current set of comments are resolved and a delta is available for re-review.

File: src/protocols/secure_channel/CASESession.cpp (hunk 38 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp:509]: All certificates are stored in chip format inside OperationalCredentialSet class.

File: src/protocols/secure_channel/CASESession.cpp (hunk 50 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp:1107]: Updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 49 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 48 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 47 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 46 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 45 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/controller/CHIPDevice.h (hunk 10 above)
Comment (jpk233) [reply src/controller/CHIPDevice.h]: Will do this.

File: src/protocols/secure_channel/CASESession.cpp (hunk 38 above)
Comment (tcarmelveilleux) [reply src/protocols/secure_channel/CASESession.cpp:509]: Yes, they are stored as CHIP format, but what is the format output by `mOpCredSet->GetDevOpCred(mTrustedRootId)` ?

File: src/protocols/secure_channel/CASESession.cpp (hunk 50 above)
Comment (tcarmelveilleux) [reply src/protocols/secure_channel/CASESession.cpp:1107]: Removing the Begin() does not solve the problem. It's the usage of Finish() that is the problem, based on the overall transcript

File: src/protocols/secure_channel/CASESession.cpp [hunk 51]
```diff
@@ -1119,79 +1012,108 @@ void CASESession::SendErrorMsg(SigmaErrorType errorCode)
...
+        VerifyOrReturnError(rootCertificate->mPublicKey.size() == kP256_PublicKey_Length, CHIP_ERROR_INTERNAL);
+
+        for (size_t j = 0; j < ipkListEntries; ++j)
         {
-            if (!mTrustedRootId.empty())
+            MutableByteSpan candidateSpan(candidate, sizeof(candidate));
+            ReturnErrorOnFailure(
+                GenerateDestinationID(initiatorRandom, rootCertificate->mPublicKey, nodeId, fabricId, ipkList[j], candidateSpan));
+
+            if (memcmp(destinationId.data(), candidate, destinationId.size()) == 0)
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1068]: You can use:
`if (destinationId.data_equal(candidate))` for these memcmp checks

File: src/protocols/secure_channel/CASESession.cpp [hunk 52]
```diff
@@ -982,104 +900,79 @@ CHIP_ERROR CASESession::HandleSigmaR3(System::PacketBufferHandle & msg)
...
-    err = mCommissioningHash.AddData(buf, bufLen);
-    SuccessOrExit(err);
+    SuccessOrExit(err = mCommissioningHash.AddData(buf, bufLen));
 
-    // Step 2
-    err = AES_CCM_decrypt(msg_R3_Encrypted.Get(), msg_r3_encrypted_len, nullptr, 0, tag, kTAGSize, sr3k, kAEADKeySize, kIVSR3,
-                          kIVLength, msg_R3_Encrypted.Get());
-    SuccessOrExit(err);
+    // Step 2 - Decrypt data blob
+    SuccessOrExit(err = AES_CCM_decrypt(msg_R3_Encrypted.Get(), msg_r3_encrypted_len - kTAGSize, nullptr, 0,
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:938]: Need to precheck that `msg_r3_encrypted_len > kTAGSize`, same for R2

Comment (tcarmelveilleux) [reply src/protocols/secure_channel/CASESession.cpp:938]: Also, the multiple indices could be resolved with adding a helper variable:

```
size_t msg_r3_encrypted_len_with_tag = 0;
size_t msg_r3_encrypted_len = 0;
......
msg_r3_encrypted_len_with_tag = tlvReader.GetLength();
VerifyOrExit(msg_r3_encrypted_len_with_tag > kTAGSize, CHIP_ERROR_INVALID_TLV_ELEMENT);
msg_r3_encrypted_len = msg_r3_encrypted_len_with_tag - kTAGSize;
...

SuccessOrExit(err = AES_CCM_decrypt(msg_R3_Encrypted.Get(), msg_r3_encrypted_len, nullptr, 0,
    msg_R3_Encrypted.Get() + msg_r3_encrypted_len, kTAGSize, sr3k, kAEADKeySize,
    kTBEData3_Nonce, kTBEDataNonceLength, msg_R3_Encrypted.Get()));
....
```

File: src/credentials/CHIPCert.cpp (hunk 24 above)
Comment (tcarmelveilleux) [reply src/credentials/CHIPCert.cpp:771]:
```suggestion
            // Ensure only one FabricID RDN present, since start value is 0, which is reserved and never seen.     
            VerifyOrReturnError(fabricId == 0, CHIP_ERROR_WRONG_CERT_TYPE);
```

File: src/protocols/secure_channel/CASEServer.cpp (hunk 29 above)
Comment (tcarmelveilleux) [reply src/protocols/secure_channel/CASEServer.cpp:77]: The credentials are only ever needed during session establishment. They should be loaded at time of use in a scope context, such that they are immediately released when no longer needed. Sigma1 and Sigma 3 require access (Sigma1 only to the root public key of current target fabric), so does Sigma2, on the way back. There is no need at all to maintain the credentials in memory forever outside of CASE, therefore `DeviceController::Shutdown()` is too late to release.

File: src/protocols/secure_channel/CASESession.cpp (hunk 50 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp:1118]: Updated to use GetDigest instead.

File: src/protocols/secure_channel/CASESession.cpp (hunk 51 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 52 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/protocols/secure_channel/CASESession.cpp (hunk 51 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated.

File: src/credentials/CHIPCert.cpp (hunk 24 above)
Comment (tcarmelveilleux) [reply src/credentials/CHIPCert.cpp:771]: You resolved the comment without applying the suggestion of adding the comment.

File: src/credentials/CHIPOperationalCredentials.cpp (hunk 26 above)
Comment (tcarmelveilleux) [reply src/credentials/CHIPOperationalCredentials.cpp:369]: The loop indexing can be changed today to size_t for `i` and `j`, even if the field doesn't change, because size_t is a wider type

File: src/protocols/secure_channel/CASEServer.cpp (hunk 29 above)
Comment (tcarmelveilleux) [reply src/protocols/secure_channel/CASEServer.cpp:77]: This comment was not addressed with a response.

File: src/protocols/secure_channel/CASESession.cpp [hunk 53]
```diff
@@ -44,21 +45,31 @@ using namespace Crypto;
...
 constexpr size_t kTAGSize = 16;
 
+constexpr size_t kDestinationMessageLen = kSigmaParamRandomNumberSize + kP256_PublicKey_Length + sizeof(FabricId) + sizeof(NodeId);
+
+// TODO: Remove this list. Replace it with an actual method to retrieve an IPK list (e.g. from a Crypto Store API)
+static uint8_t sIPKList[][kIPKSize] = {
+    { 0 }, /* Corresponds to the FabricID for the Commissioning Example. All zeros. */
+    { 0x1D, 0x1D, 0x1D, 0x1D, 0x1D, 0x1D, 0x1D, 0x1D, 0x1D, 0x1D, 0x1D, 0x1D, 0x1D, 0x1D, 0x1D,
+      0x1D }, /* Corresponds to the FabricID for the Node01_01 Test Vector */
+};
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:71]: Here we are coupling the test data with the implementation. It shows that the implementation has insufficient abstraction to be unit tested without completely changing the impl.

If `CaseSession` had basic protected API to get IPK length get access IPKs, at least in short term, then the test could override it and have this test value in its list. Please add a basic abstraction to access the IPK, even if temporary and living in this class, so that testing does not rely baking in this list.

File: src/protocols/secure_channel/CASESession.cpp [hunk 54]
```diff
@@ -339,57 +309,62 @@ CHIP_ERROR CASESession::DeriveSecureSession(SecureSession & session, SecureSessi
...
+        FabricId fabricId;
+        MutableByteSpan destinationIdSpan(destinationIdentifier, sizeof(destinationIdentifier));
+
+        ReturnErrorOnFailure(DecodeChipCert(mOpCredSet->GetDevOpCred(mTrustedRootId), mOpCredSet->GetDevOpCredLen(mTrustedRootId),
+                                            nodeOperationalCertificate));
+        ReturnErrorOnFailure(nodeOperationalCertificate.mSubjectDN.GetCertFabricId(fabricId));
+        // retrieve Fabric IPK
+        MutableByteSpan ipkSpan(mIPK, sizeof(mIPK));
+        ReturnErrorOnFailure(RetrieveIPK(fabricId, ipkSpan));
+        ReturnErrorOnFailure(GenerateDestinationID(ByteSpan(initiatorRandom, sizeof(initiatorRandom)), rootCertificate->mPublicKey,
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:355]: There exists a span constructor over static arrays, such that:

```
uint8_t initiatorRandom[kSigmaParamRandomNumberSize] = { 0 };

// The following two are equivalent:
ByteSpan span1(initiatorRandom);
ByteSpan span2(&initiatorRandom[0], sizeof(initiatorRandom));
```

Suggest using that version for arguments that are backed by arrays

File: src/protocols/secure_channel/CASESession.cpp (hunk 38 above)
Comment (tcarmelveilleux) [reply src/protocols/secure_channel/CASESession.cpp:509]: This comment was resolved before without an answer.

File: src/protocols/secure_channel/CASESession.cpp [hunk 55]
```diff
@@ -1121,81 +1022,110 @@ void CASESession::SendErrorMsg(SigmaErrorType errorCode)
...
+}
 
-    trustedRoot = CertificateKeyId(trustedRootId);
+CHIP_ERROR CASESession::FindDestinationIdCandidate(const ByteSpan & destinationId, const ByteSpan & initiatorRandom,
+                                                   const ByteSpan * ipkList, size_t ipkListEntries)
+{
+    uint8_t nCertificateSets = mOpCredSet->GetCertCount();
 
-    for (uint32_t i = 0; i < nTrustedRoots; ++i)
+    for (uint8_t i = 0; i < nCertificateSets; ++i)
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1051]: Suggest `size_t` and replace `i` with `certChainIdx` or such.

File: src/protocols/secure_channel/CASESession.cpp [hunk 56]
```diff
@@ -1121,81 +1022,110 @@ void CASESession::SendErrorMsg(SigmaErrorType errorCode)
...
-        VerifyOrReturnError(kTrustedRootIdSize == suppTlvReader.GetLength(), CHIP_ERROR_INVALID_TLV_ELEMENT);
-        VerifyOrReturnError(suppTlvReader.GetType() == TLV::kTLVType_ByteString, CHIP_ERROR_WRONG_TLV_TYPE);
-        ReturnErrorOnFailure(suppTlvReader.GetBytes(trustedRootId, kTrustedRootIdSize));
+        const ChipCertificateData * rootCertificate = mOpCredSet->GetRootCertificate(trustedRootId);
+        VerifyOrReturnError(rootCertificate != nullptr, CHIP_ERROR_CERT_NOT_FOUND);
+        VerifyOrReturnError(!rootCertificate->mPublicKey.empty(), CHIP_ERROR_INTERNAL);
+        VerifyOrReturnError(rootCertificate->mPublicKey.size() == kP256_PublicKey_Length, CHIP_ERROR_INTERNAL);
 
-        if (mOpCredSet->IsTrustedRootIn(trustedRoot))
+        for (size_t j = 0; j < ipkListEntries; ++j)
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:1072]: Suggest `j` --> `ipkIdx`

File: src/protocols/secure_channel/CASESession.cpp [hunk 57]
```diff
@@ -328,7 +298,7 @@ CHIP_ERROR CASESession::DeriveSecureSession(SecureSession & session, SecureSessi
         // TODO: Add IPK to Salt
         bbuf.Put(mMessageDigest, sizeof(mMessageDigest));
 
-        VerifyOrReturnError(bbuf.Fit(), CHIP_ERROR_NO_MEMORY);
+        VerifyOrReturnError(bbuf.Fit(), CHIP_ERROR_BUFFER_TOO_SMALL);
     }
 
     ReturnErrorOnFailure(session.InitFromSecret(ByteSpan(mSharedSecret, mSharedSecret.Length()), ByteSpan(msg_salt.Get(), saltlen),
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:304]: IPK used needs to be accounted-for in salt for spec compliance. See:

image

Also, I'm concerned that since digest is finished() in SigmaR3, that receiving more messages out of order may mess-up order. Strongly recommend finishing digest in here just above the `bbuf.Put()`.

**Review by tcarmelveilleux — CHANGES_REQUESTED** [review]
Very few remaining comments:

- [x] Need to account for IPK in salt in DeriveSecureSession
- [x] Abstract access from IPK some more (see the comments)
- [x] Address review comments open that were closed without change or answer.

File: src/credentials/CHIPOperationalCredentials.cpp (hunk 26 above)
Comment (jpk233) [reply src/credentials/CHIPOperationalCredentials.cpp:369]: Updated to use size_t and new var names

File: src/protocols/secure_channel/CASEServer.cpp (hunk 29 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASEServer.cpp:77]: The credentials are released right after a successful or unsuccessful CASE Session Establishment. See CASEServer::Cleanup method. There is also issue #8342 to update this method in a future PR.

File: src/protocols/secure_channel/CASESession.cpp (hunk 38 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp:509]: They are split into separate certificates before loading them onto the OperationalCredentialSet class. This is performed by the ExtractCertsFromCertArray method present in CHIPCertFromX509.cpp, which also verifies for kTLVType_Array

File: src/protocols/secure_channel/CASESession.cpp (hunk 56 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated

File: src/protocols/secure_channel/CASESession.cpp (hunk 55 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated

File: src/protocols/secure_channel/CASESession.cpp (hunk 54 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated

File: src/protocols/secure_channel/CASESession.cpp (hunk 53 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp:71]: Agreed, working on this.

File: src/protocols/secure_channel/CASESession.cpp (hunk 57 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: Updated

File: src/credentials/CHIPCert.cpp (hunk 24 above)
Comment (jpk233) [reply src/credentials/CHIPCert.cpp:772]: Good catch, missed this. Included now.

File: src/protocols/secure_channel/CASESession.cpp (hunk 53 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp]: This has been updated now.

**Review by tcarmelveilleux — APPROVED** [review]

File: src/credentials/CHIPCert.h [hunk 58]
```diff
@@ -252,6 +252,15 @@ class ChipDN
      **/
     CHIP_ERROR GetCertChipId(uint64_t & certId) const;
 
+    /**
+     * @brief Retrieve the Fabric ID of a CHIP certificate.
+     *
+     * @param certId  A reference to the certificate Fabric ID value.
+     *
+     * @return Returns a CHIP_ERROR on error, CHIP_NO_ERROR otherwise
```
Comment (andy31415) [inline src/credentials/CHIPCert.h:260]: Could you rephrase the comment to focus on non-obvious bits? e.g. any CHIP_ERROR return obviously means 'CHIP_NO_ERROR on success, some error otherwise' and `GetCertFabricId` obviously means 'get the fabric ID from the certitifcate'.

File: src/protocols/secure_channel/CASESession.cpp [hunk 59]
```diff
@@ -283,6 +249,8 @@ CHIP_ERROR CASESession::EstablishSession(const Transport::PeerAddress peerAddres
     mExchangeCtxt->SetResponseTimeout(kSigma_Response_Timeout);
     mConnectionState.SetPeerAddress(peerAddress);
     mConnectionState.SetPeerNodeId(peerNodeId);
+    mTrustedRootId = operationalCredentialSet->GetTrustedRootId(opCredSetIndex);
```
Comment (andy31415) [inline src/protocols/secure_channel/CASESession.cpp:252]: the only use of opCredSetIndex seems to be to `GetTrustedRootId`. Why do we pass the index instead of the trusted root Id itself?

File: src/protocols/secure_channel/CASESession.cpp [hunk 60]
```diff
@@ -262,8 +227,9 @@ CASESession::ListenForSessionEstablishment(OperationalCredentialSet * operationa
 }
 
 CHIP_ERROR CASESession::EstablishSession(const Transport::PeerAddress peerAddress,
-                                         OperationalCredentialSet * operationalCredentialSet, NodeId peerNodeId, uint16_t myKeyId,
-                                         ExchangeContext * exchangeCtxt, SessionEstablishmentDelegate * delegate)
+                                         OperationalCredentialSet * operationalCredentialSet, uint8_t opCredSetIndex,
+                                         NodeId peerNodeId, uint16_t myKeyId, ExchangeContext * exchangeCtxt,
+                                         SessionEstablishmentDelegate * delegate)
 {
     CHIP_ERROR err = CHIP_NO_ERROR;
```
Comment (andy31415) [inline src/protocols/secure_channel/CASESession.cpp:235]: this method seems to mix Return and Exit.  Should the return on exchangeCtxt be an exit so that the code does 'Clear" ?

**Review by msandstedt — APPROVED** [review]

File: src/controller/CHIPDevice.h [hunk 61]
```diff
@@ -82,6 +82,7 @@ struct ControllerDeviceInitParams
     Inet::InetLayer * inetLayer                         = nullptr;
     PersistentStorageDelegate * storageDelegate         = nullptr;
     Credentials::OperationalCredentialSet * credentials = nullptr;
+    uint8_t * credentialsIndex                          = nullptr;
```
Comment (andy31415) [inline src/controller/CHIPDevice.h:85]: why is this a pointer?

I would expect 'init params' to be input parameters for object initialization. Seeing a pointer inidicates to me either having this 'maybe not set (null)' in which case an 'optional' seems better or maybe because it is an output parameter, in which case I would prefer to place this separately to distinguish input vs output parameters

File: src/transport/FabricTable.cpp [hunk 62]
```diff
@@ -374,6 +374,7 @@ CHIP_ERROR FabricInfo::GetCredentials(OperationalCredentialSet & credentials, Ch
 
     credentials.Release();
     ReturnErrorOnFailure(credentials.Init(&certificates, 1));
+    credentialsIndex = static_cast<uint8_t>(credentials.GetCertCount() - 1U);
```
Comment (andy31415) [inline src/transport/FabricTable.cpp:377]: `credentials` seems to have sufficient information to have the 'credentialsIndex' value. Why does this method need to return it? Why don't callers of this `GetCredetials` method do the  GetCertCount() call instead?

File: src/transport/FabricTable.h [hunk 63]
```diff
@@ -123,7 +123,7 @@ class DLL_EXPORT FabricInfo
     }
 
     CHIP_ERROR GetCredentials(Credentials::OperationalCredentialSet & credentials, Credentials::ChipCertificateSet & certSet,
-                              Credentials::CertificateKeyId & rootKeyId);
+                              Credentials::CertificateKeyId & rootKeyId, uint8_t & credentialsIndex);
```
Comment (andy31415) [inline src/transport/FabricTable.h:126]: Please add documentation for these: what does the credentialsIndex returned by this method mean?

In a previous comment I was wondering if this could be removed because if this just means "index of last valid credential in the credential set" then it seems redundant information.

File: src/credentials/CHIPCert.cpp [hunk 64]
```diff
@@ -746,6 +757,30 @@ CHIP_ERROR ChipDN::GetCertChipId(uint64_t & chipId) const
...
+
+            fabricId = rdn[i].mChipVal;
+            break;
+        default:
+            break;
+        }
+    }
+
+    return CHIP_NO_ERROR;
```
Comment (andy31415) [inline src/credentials/CHIPCert.cpp:781]: if none of the OIDs are `kOID_AttributeType_ChipFabricId` is a fabricId of 0 a correct return value? if so please document it here, otherwise please return an error if no fabric ID can be found.

Above you seem to rely that `fabricId 0` is invalid.

File: src/credentials/CHIPCert.cpp [hunk 65]
```diff
@@ -746,6 +757,30 @@ CHIP_ERROR ChipDN::GetCertChipId(uint64_t & chipId) const
...
+
+    for (uint8_t i = 0; i < rdnCount; i++)
+    {
+        switch (rdn[i].mAttrOID)
+        {
+        case kOID_AttributeType_ChipFabricId:
+            // Ensure only one FabricID RDN present, since start value is 0, which is reserved and never seen.
+            VerifyOrReturnError(fabricId == 0, CHIP_ERROR_WRONG_CERT_TYPE);
+
+            fabricId = rdn[i].mChipVal;
```
Comment (andy31415) [inline src/credentials/CHIPCert.cpp:774]: should we return error if mChipVal is 0 here?

File: src/protocols/secure_channel/CASESession.cpp (hunk 59 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp:252]: This is because the TrustedRootId was removed from the spec. So, we should remove it from the public methods and use an index instead.

File: src/protocols/secure_channel/CASESession.cpp (hunk 60 above)
Comment (jpk233) [reply src/protocols/secure_channel/CASESession.cpp:235]: No, because when returning on exchangeCtxt the class wouldn't have been initialized yet.

File: src/transport/FabricTable.cpp (hunk 62 above)
Comment (jpk233) [reply src/transport/FabricTable.cpp:377]: Right now, 'credentialsIndex' is indeed the index of the last valid credential in the credential set. This, however, may not be true in the future, since we may need to have multiple loaded credentials in the set. The 'credentialsIndex'  will then be used by the caller to index the retrieved credentials, which could have been cached previously, or loaded when calling GetCredentials method. Plus, this will serve as a replacement to the rootKeyId parameter, which will be eliminated.

File: src/controller/CHIPDevice.h (hunk 61 above)
Comment (jpk233) [reply src/controller/CHIPDevice.h]: Updated.

File: src/credentials/CHIPCert.h (hunk 58 above)
Comment (jpk233) [reply src/credentials/CHIPCert.h]: Updated.

File: src/transport/FabricTable.h (hunk 63 above)
Comment (jpk233) [reply src/transport/FabricTable.h:137]: Updated.

File: src/credentials/CHIPCert.cpp (hunk 64 above)
Comment (jpk233) [reply src/credentials/CHIPCert.cpp:780]: Updated to return an error if no fabric ID is found.

**Review by hawk248 — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]
