### PR TITLE
Generate test DAC/PAI bits for vendor ids 0xFFF2 and 0xFFF3, not just 0xFFF1

### LINKED ISSUE #25504: [Feature] We'll need a way to programmatically/dynamically generate certs for various VID/PID (VendorID/ ProductID) for extended testing with ota-requester app.
### Feature description

...
SHA: df4ad9521b1dac98d7965f455fec74ffa270429c

We'll need a way to programmatically/dynamically generate certs for various VID/PID (VendorID/ ProductID) for extended testing with ota-requester app. 

We're getting the vid/pid from the certificate now. The test certificate used is hardcoded to have a VendorID of 0xFFF1. 

So if we try to change the value at below location to 0xFFF0 (#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID 0xFFF0) for testing this would still use the hardcoded value of 0xFFF1 on the compiled certificate on the ota-requester app hence we get unexpected results on the testing. 

https://github.com/project-chip/connectedhomeip/blob/a7cc2cf3ca94693e0ba08578cc1365d4848890dd/src/include/platform/CHIPDeviceConfig.h#L200 

[ota-requester-hard-coded-VID-0xFFF1.txt](https://github.com/project-chip/connectedhomeip/files/10904132/ota-requester-hard-coded-VID-0xFFF1.txt)

### Platform

darwin

### Platform Version(s)

13.2

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
REVIEW NOTES:
1) All the new bits under Credentials/development/attestation/ were generated by running src/tools/chip-cert/dacs.py after making the changes to it that this PR makes.
2) Existing der/pem files under Credentials/development/attestation/ were just renamed to the new names the script expects, to minimize changes to the ExampleDACs/ExamplePAI files.
3) The manual changes are to `src/app/tests/suites/credentials/TestHarnessDACProvider.cpp`, `src/credentials/examples/DeviceAttestationCredsExample.cpp`, and `src/tools/chip-cert/dacs.py`.  Everything else is then generated by running `dacs.py`.

The test CDs for VIDs 0xFFF2 and 0xFFF3 were generated by:
    
1) Modifying src/tools/chip-cert/Cmd_GenCD.cpp to use kDataFormat_Hex, not kDataFormat_Raw.
2) Running
    ```
    chip-cert gen-cd -f 1 -V FFF2 -d 0016 -c "CSA00000SWC00000-00" -l 0 -i 0 -n 1 -t 0 -p 8000 -p 8001 -p 8002 -p 8003 -p 8004 -p 8005 -p 8006 -p 8007 -p 8008 -p 8009 -p 800A -p 800B -p 800C -p 800D -p 800E -p 800F -p 8010 -p 8011 -p 8012 -p 8013 -p 8014 -p 8015 -p 8016 -p 8017 -p 8018 -p 8019 -p 801A -p 801B -p 801C -p 801D -p 801E -p 801F -p 8020 -p 8021 -p 8022 -p 8023 -p 8024 -p 8025 -p 8026 -p 8027 -p 8028 -p 8029 -p 802A -p 802B -p 802C -p 802D -p 802E -p 802F -p 8030 -p 8031 -p 8032 -p 8033 -p 8034 -p 8035 -p 8036 -p 8037 -p 8038 -p 8039 -p 803A -p 803B -p 803C -p 803D -p 803E -p 803F -p 8040 -p 8041 -p 8042 -p 8043 -p 8044 -p 8045 -p 8046 -p 8047 -p 8048 -p 8049 -p 804A -p 804B -p 804C -p 804D -p 804E -p 804F -p 8050 -p 8051 -p 8052 -p 8053 -p 8054 -p 8055 -p 8056 -p 8057 -p 8058 -p 8059 -p 805A -p 805B -p 805C -p 805D -p 805E -p 805F -p 8060 -p 8061 -p 8062 -p 8063 --key ./credentials/test/certification-declaration/Chip-Test-CD-Signing-Key.pem --cert ./credentials/test/certification-declaration/Chip-Test-CD-Signing-Cert.pem --out somefile
    ```
   and the same with -V FFF3 to generate the certification declaration.
3) Opening up that file in a text editor and:
   a) Lower-casing the text.
   b) Doing a regexp replace of "(..)" with "0x\1, ".

Fixes https://github.com/project-chip/connectedhomeip/issues/25504

### CODE REVIEW

File: src/credentials/examples/DeviceAttestationCredsExample.cpp [hunk 1]
```diff
@@ -79,6 +80,68 @@ CHIP_ERROR ExampleDACProvider::GetCertificationDeclaration(MutableByteSpan & out
...
+        0x13, 0x43, 0x53, 0x41, 0x30, 0x30, 0x30, 0x30, 0x30, 0x53, 0x57, 0x43, 0x30, 0x30, 0x30, 0x30, 0x30, 0x2d, 0x30, 0x30,
+        0x24, 0x05, 0x00, 0x24, 0x06, 0x00, 0x24, 0x07, 0x01, 0x24, 0x08, 0x00, 0x18, 0x31, 0x7c, 0x30, 0x7a, 0x02, 0x01, 0x03,
+        0x80, 0x14, 0x62, 0xfa, 0x82, 0x33, 0x59, 0xac, 0xfa, 0xa9, 0x96, 0x3e, 0x1c, 0xfa, 0x14, 0x0a, 0xdd, 0xf5, 0x04, 0xf3,
+        0x71, 0x60, 0x30, 0x0b, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x02, 0x01, 0x30, 0x0a, 0x06, 0x08, 0x2a,
+        0x86, 0x48, 0xce, 0x3d, 0x04, 0x03, 0x02, 0x04, 0x46, 0x30, 0x44, 0x02, 0x20, 0x1e, 0x14, 0xa8, 0xc6, 0x95, 0x1d, 0x50,
+        0x87, 0x94, 0x2f, 0x58, 0x69, 0x38, 0x8a, 0xdc, 0x49, 0x50, 0x40, 0x63, 0x5d, 0xdf, 0xc7, 0x93, 0x8b, 0xf0, 0x8a, 0x49,
+        0xce, 0x8f, 0xe2, 0xf0, 0x28, 0x02, 0x20, 0x50, 0x90, 0x96, 0x20, 0x3f, 0xab, 0xe2, 0x19, 0xf8, 0xec, 0xf0, 0xe6, 0x9b,
+        0xa7, 0x51, 0x79, 0x9c, 0x02, 0x98, 0x96, 0xc7, 0xc9, 0xc8, 0x2d, 0x4b, 0xf5, 0x76, 0xd3, 0x8f, 0xbd, 0x36, 0x5b
+    };
+#else  /* Fall back to the VID=0xFFF1 CD */
```
Comment (cecille) [inline src/credentials/examples/DeviceAttestationCredsExample.cpp:144]: Suggestion (and I'm sorry for scope-creeping this here), but should this maybe error out here? If the vendor ID doesn't match the config, commissioning should also fail and that might be good to know at compile time.

**Review by cecille — APPROVED** [review]
Feel free to ignore my suggestion if it's going to be annoying to change. This looks fine. Thanks.

File: src/credentials/examples/DeviceAttestationCredsExample.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/credentials/examples/DeviceAttestationCredsExample.cpp:144]: I considered erroring out, but I expect that would break devices that:

1. Set a different CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID
2. Implement a different DAC provider that does the right thing for their vendor id, but still end up compiling this bit because it's always compiled as part of the core `src/credentials` code.

Comment (cecille) [reply src/credentials/examples/DeviceAttestationCredsExample.cpp:144]: kk, sounds reasonable. This matches the current behaviour anyway, so I'm good with this as-is.

**Review by yufengwangca — APPROVED** [review]

**Review by emargolis — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]
