### PR TITLE
Address API review issues in MTRDeviceController.

### LINKED ISSUE #22533: [Platform] Apply darwin API review changes to MTRDeviceController
### Reproduction steps

MTRDeviceController and MTRDeviceControllerOverXPC need various fixes based on the API review.  This includes documentation, function naming, etc, etc.

Part of https://github.com/project-chip/connectedhomeip/issues/22420

This probably needs to happen after #22531

### Platform

darwin

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
* Make MTRBaseDevice creation synchronous.  This requires updates to MTRBaseDeviceOverXPC to do the possible async getting of the controller id it needs during its async operations, not when getting the device object.
* Rename "pairDevice" to "setupCommissioningSessionWithPayload", fix its signature, improve documentation.
* Rename "commissionDevice" to "commissionNodeWithID".
* Rename "stopDevicePairing" to "cancelCommissioningForNodeID" and document.
* Rename "getDeviceBeingCommissioned" to "getDeviceBeingCommissionedWithNodeID".
* Various documentation improvements.
* Add a way to generate a QR code from an MTRSetupPayload to allow correct recovery of long discriminators in setupCommissioningSessionWithPayload.

Addresses part of https://github.com/project-chip/connectedhomeip/issues/22420

#### Issue Being Resolved
* Fixes #22533

#### Change overview
See above.

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRDeviceController.h [hunk 1]
```diff
@@ -39,61 +41,60 @@ typedef void (^MTRDeviceConnectionCallback)(MTRBaseDevice * _Nullable device, NS
...
+ * can be used to get an MTRBaseDevice and discover what sort of network
+ * credentials the device might need, and commissionNodeWithID can be used to
+ * commission the device.
  */
-- (BOOL)pairDevice:(uint64_t)deviceID
-           address:(NSString *)address
-              port:(uint16_t)port
-      setupPINCode:(uint32_t)setupPINCode
-             error:(NSError * __autoreleasing *)error;
+- (void)setupCommissioningSessionWithPayload:(MTRSetupPayload *)payload
```
Comment (tcarmelveilleux) [inline src/darwin/Framework/CHIP/MTRDeviceController.h:71]: This change would benefit greatly the overall CHIPDeviceController API

Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDeviceController.h:71]: Yes, that is the idea.  :)

Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDeviceController.h]: Filed https://github.com/project-chip/connectedhomeip/issues/22603

File: src/darwin/Framework/CHIP/MTRDeviceOverXPC.m [hunk 2]
```diff
@@ -28,18 +29,21 @@
...
 
 @implementation MTRDeviceOverXPC
 
-- (instancetype)initWithController:(id<NSCopying>)controller
-                          deviceID:(NSNumber *)deviceID
-                     xpcConnection:(MTRDeviceControllerXPCConnection *)xpcConnection
+- (instancetype)initWithControllerID:(id<NSCopying> _Nullable)controllerID
+                          controller:(MTRDeviceControllerOverXPC *)controller
+                            deviceID:(NSNumber *)deviceID
+                       xpcConnection:(MTRDeviceControllerXPCConnection *)xpcConnection
```
Comment (vivien-apple) [inline src/darwin/Framework/CHIP/MTRDeviceOverXPC.m:44]: The fact that both `controllerID` and `controller` needs to be passed in is very confusing IMHO. Especially given that the underlying code is calling method ending with "Controller" but use "controllerId" as an argument (`subscribeWithController`, `readAttributeWithController`, * ...)

Just curious why, can't we just pass the `MTRDeviceControllerOverXPC` and check the `controllerID` property directly (as exposed by `MTRDeviceControllerOverXPC_Internal.h`)

File: examples/darwin-framework-tool/main.mm [hunk 3]
```diff
@@ -30,13 +30,15 @@
...
+        Commands commands;
+        registerCommandsPairing(commands);
+        registerCommandsInteractive(commands);
+        registerCommandsPayload(commands);
+        registerClusterOtaSoftwareUpdateProviderInteractive(commands);
+        registerCommandsStorage(commands);
+        registerCommandsTests(commands);
+        registerClusters(commands);
+        return commands.Run(argc, (char **) argv);
+    }
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply examples/darwin-framework-tool/main.mm:43]: Yes, in https://github.com/project-chip/connectedhomeip/pull/22606.  It's needed to avoid leaks in both PRs, from different API changes.  I wanted to get the CI running in parallel and they should merge cleanly.

File: src/darwin/Framework/CHIP/MTRDeviceController_Internal.h [hunk 4]
```diff
@@ -96,6 +96,15 @@ NS_ASSUME_NONNULL_BEGIN
...
 
+/**
+ * Notification that the MTRDeviceControllerFactory has finished shutting down
+ * this controller and will not be touching it anymore.  This is guaranteed to
+ * be called after initWithFactory succeeds.
+ *
+ * Only MTRDeviceControllerFactory should be calling this.
+ */
+- (void)deinitFromFactory;
+
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDeviceController_Internal.h:107]: Yes, it's needed to fix leaks in both PRs.  ;)

File: src/darwin/Framework/CHIPTests/MTRXPCListenerSampleTests.m [hunk 5]
```diff
@@ -537,13 +527,6 @@ - (void)waitForCommissionee
                    NSLog(@"Listener is not active");
                    return nil;
                }];
-    [remoteController getBaseDevice:kDeviceId
-                              queue:queue
-                         completion:^(MTRBaseDevice * _Nullable device, NSError * _Nullable error) {
-                             mConnectedDevice = device;
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIPTests/MTRXPCListenerSampleTests.m:543]: Good catch.  This test is not run in CI, so it's possible this just broke it.  I'll run locally and make sure it works.

File: examples/darwin-framework-tool/commands/pairing/PairingCommandBridge.mm [hunk 6]
```diff
@@ -83,75 +80,53 @@
...
-    [commissioner pairDevice:mNodeId onboardingPayload:payload error:error];
-}
-
-void PairingCommandBridge::PairWithIPAddress(NSError * __autoreleasing * error)
-{
+    NSString * onboardingPayload = [NSString stringWithUTF8String:mOnboardingPayload];
     SetUpPairingDelegate();
+    auto * payload = [MTRSetupPayload setupPayloadWithOnboardingPayload:onboardingPayload error:error];
+    if (payload == nil) {
+        return;
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply examples/darwin-framework-tool/commands/pairing/PairingCommandBridge.mm:94]: I can do that.

File: examples/darwin-framework-tool/commands/tests/TestCommandBridge.h [hunk 7]
```diff
@@ -156,27 +156,19 @@ class TestCommandBridge : public CHIPCommandBridge,
...
-                           if (error != nil) {
-                               SetCommandExitStatus(error);
-                               return;
-                           }
-
-                           mConnectedDevices[identity] = device;
-                           NextTest();
-                       }];
+        mConnectedDevices[identity] = [MTRBaseDevice deviceWithNodeID:@(value.nodeId) controller:controller];
+        NextTest();
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply examples/darwin-framework-tool/commands/tests/TestCommandBridge.h:171]: I can do that, yes.

File: src/darwin/Framework/CHIP/MTRDeviceOverXPC.m (hunk 2 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDeviceOverXPC.m:44]: I guess we could, sure.  So here "controller" would mean the actual MTRDeviceControllerOverXPC and in other places it would mean the controller id.  Maybe I should call this one `initWithControllerOverXPC` or something to make them look different?

Comment (vivien-apple) [reply src/darwin/Framework/CHIP/MTRDeviceOverXPC.m:44]: `initWithControllerOverXPC` looks good to me!

Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDeviceOverXPC.m:44]: Done.

File: examples/darwin-framework-tool/commands/pairing/PairingCommandBridge.mm (hunk 6 above)
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply examples/darwin-framework-tool/commands/pairing/PairingCommandBridge.mm:94]: Actually, these work fine: they have an error outparam, and it it gets set non-nil we use it to `SetCommandExitStatus`.

**Review by vivien-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
Fast-tracking platform-specific fix reviewed by platform owner.
