### PR TITLE
Fix ACL constraint error (return constraint error instead of failure when the ACL entry is invalid)

### LINKED ISSUE #20672: [TC-ACL-2.4] Test Case need to be revisited.
**Test Case ID**
TC-ACL-2.4
**Describe Issue**
Step 29: expected outcome is constraint error but result is failure.
Reason:  Authmode is PASE RESERVED FOR FUTURE ,.
The subjects list SHALL NOT be empty if the entry’s
AuthMode is PASE.
Step 31: expected outcome is constraint error but result is failure .
reason:     field combination invalid that means Administer privilege with group authmode.
Step 32:      expected outcome is constraint error but result is failure.
Reason:  in the privilege field  tried with 6,7 ,8,9 values but failure.
Step 33: expected outcome is constraint error but result is failure. In the Authmode field tried the
values 4,5,6,7,8 values but result is failure.
Step 34:  expected outcome is constraint error but result is failure. Invalid subject element is found.
Step 35: expected outcome is constraint error but result is failure. Invalid subject element is found.
Step 36: expected outcome is constraint error but result is failure.
Step 37:"expected outcome is constraint error but result is success:
tried  with privilege 5 and authmode 2 then also getting failure instead of constraint error.
"
Step 38:   expected outcome is constraint error but result is failure.
Reason: Target elements invalid (no field is present)
Step 42:  expected outcome is constraint error but result is failure.
Reason: Target element Invalid( both endpoint and deviceTypes are present).
**Steps that require review:**
Step 29,31,32,33,34,35,36,37,38,42
Specification References:
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/ACL-Cluster.adoc#attributes
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/ACL-Cluster.adoc#6-error-handling

Test Plan Reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/AccessControl.adoc#tc-acl-2-4-acl-attribute

### LINKED ISSUE #20794: [TC-ACL-2.4]: Test case ,Step 32: Expected output is constraint error , But the actual result is Failure
Test Case ID
TC-ACL-2.4
Describe Issue:
Step 32 :expected outcome is constraint error but result is Failure.
Command to Verify: ./chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": null}, {"fabricIndex": 1, "privilege": 6, "authMode": 2, "subjects": null, "targets":null}]' 1 0
Specification References:
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/ACL-Cluster.adoc#error-handling
Test Plan Reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/AccessControl.adoc#tc-acl-2-4-acl-attribute

### LINKED ISSUE #20796: [TC-ACL-2.4]: Test case ,Step 35: Expected output is constraint error , But the actual result is Failure
Test Case ID
TC-ACL-2.4
Describe Issue:
Step 35 :expected outcome is constraint error but result is Failure.
Command to Verify: ./chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": null}, {"fabricIndex": 1, "privilege": 3, "authMode": 2, "subjects": [18446744073709551615], "targets":null}]' 1 0
-For the above command , as per spec, SDK should return Constraint error.

Test Plan Reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/AccessControl.adoc#tc-acl-2-4-acl-attribute

### LINKED ISSUE #20797: [TC-ACL-2.4]: Test case ,Step 36: Expected output is constraint error , But the actual result is success
Test Case ID
TC-ACL-2.4
Describe Issue:
Step 36 :expected outcome is constraint error but result is Success.
Command to Verify:  ./chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": null}, {"fabricIndex": 1, "privilege": 3, "authMode": 2, "subjects": [42949672930000000], "targets": null}]' 1 0
Test Plan Reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/AccessControl.adoc#tc-acl-2-4-acl-attribute

### LINKED ISSUE #20798: [TC-ACL-2.4]: Test case ,Step 37: Expected output is constraint error , But the actual result is Failure
Test Case ID
TC-ACL-2.4
Describe Issue:
Step 37 :expected outcome is constraint error but result is failure
Command to Verify: ./chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": null}, {"fabricIndex": 1, "privilege": 3, "authMode": 2, "subjects": [18446744073709486080], "targets":null}]' 1 0 

Test Plan Reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/AccessControl.adoc#tc-acl-2-4-acl-attribute

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
`FAILURE` reported instead of `CONSTRAINT_ERROR`

Fixes #20672
Fixes #20794 
Fixes #20796
Fixes #20797 (NOTE: uses 0xFFFF_FFFD_0000_0000 and NOT the original test value as that seemed odd)
Fixes #20798

#### Change overview
Fix return code
Add unit tests for automation

I could *NOT* add tests for the 64bit invalid subjects due to zap limitation (was later explained that I need to use quotes). In the mean time, the tests not covered were broken out in separate bugs that will be fixed separately.

#### Testing
Automated testing (yay!)

### CODE REVIEW

**Comment by andy31415** [comment]
Some tests still fail: when testing, I had not rebuild chip-tool. Will update the PR for tests to pass as needed.

**Review by bzbarsky-apple — COMMENTED** [review]
> I could NOT add tests for the 64bit invalid subjects due to zap limitation.

Should work fine.  Have to put 64-bit literals in quotes (as a string) instead of just listing them as bareword numbers.

**Comment by andy31415** [comment]
@aswathygrl created issues for items that could not be covered by this PR:

https://github.com/project-chip/connectedhomeip/issues/20794
https://github.com/project-chip/connectedhomeip/issues/20796
https://github.com/project-chip/connectedhomeip/issues/20797
https://github.com/project-chip/connectedhomeip/issues/20798

**Comment by andy31415** [comment]
> > I could NOT add tests for the 64bit invalid subjects due to zap limitation.
> 
> Should work fine. Have to put 64-bit literals in quotes (as a string) instead of just listing them as bareword numbers.

I will fix those as part of the breakout bugs.
I both had problems with creating the test - this should be fixed by the quotes as you mentioned, but also in some tests my ACL was simply accepted, so unsure if this is a problem or the fact that I just run "Step 37" without previous steps is an issue.

File: src/access/examples/ExampleAccessControlDelegate.cpp [hunk 1]
```diff
@@ -125,7 +126,7 @@ class SubjectStorage
             mNode = node;
             return CHIP_NO_ERROR;
         }
-        return CHIP_ERROR_INVALID_ARGUMENT;
+        return CHIP_IM_GLOBAL_STATUS(ConstraintError);
```
Comment (tcarmelveilleux) [inline src/access/examples/ExampleAccessControlDelegate.cpp:129]: In this module, it's all business logic. We should not have IM inside of logic that can be managed internally.

This is where conversion of "failure on delegate with INVALID_ARGUMENT" means constraint error in the cluster. Otherwise we are layer crossing. Cluster layer is cluster layer. This is internal to the IM business logic in a sense

File: src/access/BUILD.gn [hunk 2]
```diff
@@ -36,5 +36,6 @@ static_library("access") {
     "${chip_root}/src/lib/core",
     "${chip_root}/src/lib/support",
     "${chip_root}/src/platform",
+    "${chip_root}/src/protocols:im_status",  # For protocol error codes
```
Comment (tcarmelveilleux) [inline src/access/BUILD.gn:39]: AccessControl module is internal business logic. It should not depend on src/protocols

File: src/protocols/BUILD.gn [hunk 3]
```diff
@@ -21,8 +21,6 @@ static_library("protocols") {
     "echo/Echo.h",
     "echo/EchoClient.cpp",
     "echo/EchoServer.cpp",
```
Comment (tcarmelveilleux) [inline src/protocols/BUILD.gn:23]: Drive-by: we should take this out for now... Do we still use this? It's not spec compliant. This should only appear in examples/

Comment (andy31415) [reply src/protocols/BUILD.gn:23]: Probably separate PR. I had the same thought.

File: src/access/BUILD.gn (hunk 2 above)
Comment (andy31415) [reply src/access/BUILD.gn]: Updated logic. Hopefully cleaner now.

**Review by tcarmelveilleux — APPROVED** [review]

**Review by mrjerryjohns — APPROVED** [review]

File: src/app/tests/suites/TestAccessControlConstraints.yaml [hunk 4]
```diff
@@ -0,0 +1,313 @@
...
+                      Privilege: 5, # Administer
+                      AuthMode: 2, # CASE
+                      Subjects: [112233],
+                      Targets: null,
+                  },
+                  {
+                      FabricIndex: 1,
+                      Privilege: 3, # Operate
+                      AuthMode: 2, # CASE
+                      Subjects: ["18446744073709551615"],
```
Comment (bzbarsky-apple) [inline src/app/tests/suites/TestAccessControlConstraints.yaml:254]: You could probably have `"0xFFFFFFFFFFFFFFFF"` here, by the way.  But either way.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/clusters/access-control-server/access-control-server.cpp [hunk 5]
```diff
@@ -415,6 +428,47 @@ void AccessControlAttribute::OnEntryChanged(const SubjectDescriptor * subjectDes
     ChipLogError(DataManagement, "AccessControlCluster: event failed %" CHIP_ERROR_FORMAT, err.Format());
 }
 
+CHIP_ERROR ChipErrorToImErrorMap(CHIP_ERROR err)
```
[the remark this answers is not in the document]
Comment (andy31415) [reply src/app/clusters/access-control-server/access-control-server.cpp:431]: The intent would be to generally move this logic to a central place. Separate PR(s) though.
