### PR TITLE
Fix reading ExtendedAddress from otbr-agent

### LINKED ISSUE #39722: [BUG] [Linux] [Thread] advertised dns-sd hostname wrong with ot-br-posix
### Reproduction steps

The ThreadStackManagerImpl from the Linux platform currently attempts to read the ExtendedAddress property over d-bus from ot-br-posix using generated code that uses a caching proxy (GDBusProxy).  This proxy does not read or cache properties that are marked "org.freedesktop.DBus.Property.EmitsChangedSignal = false", which is how ExtendedAddress is defined. 

The end-result is that ThreadStackManagerImpl::_GetPrimary802154MACAddress always returns zeros.

Instead of using the generated proxy's openthread_io_openthread_border_router_get_extended_address function, it should invoke the Get method for this attribute and cache it manually.

Example erroneous output (note 0000000000000000.local):

[1750947235.348] [620813:620813] [DL] Using Thread extended MAC for hostname.
[1750947235.348] [620813:620813] [DIS] Advertise commission parameter vendorID=65521 productID=32769 discriminator=3840/15 cm=1 cp=0
[1750947235.348] [620813:620813] [DIS] Responding with _matterc._udp.local
[1750947235.348] [620813:620813] [DIS] Responding with 52A63BCD348800B8._matterc._udp.local
[1750947235.348] [620813:620813] [DIS] Responding with 0000000000000000.local

### Bug prevalence

Always when using OpenThread on the Linux platform

### GitHub hash of the SDK that was being used

f56e79621f8b070d8e0ec3ce0431b2ff7887dfbe

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tleacmcsa**
#### Summary

The property is defined to not emit signals on changes, which means the generated caching proxy will never have a value. Instead, we must directly read the value with the Get function and cache it ourselves.

#### Related issues

Fixes: #39722

#### Testing

Build and run examples/lighting-app/linux example with the --thread option and with otbr-agent running.

Before the fix, output contains (note 0000000000000000.local):

[1750947235.348] [620813:620813] [DL] Using Thread extended MAC for hostname.
[1750947235.348] [620813:620813] [DIS] Advertise commission parameter vendorID=65521 productID=32769 discriminator=3840/15 cm=1 cp=0
[1750947235.348] [620813:620813] [DIS] Responding with _matterc._udp.local
[1750947235.348] [620813:620813] [DIS] Responding with 52A63BCD348800B8._matterc._udp.local
[1750947235.348] [620813:620813] [DIS] Responding with 0000000000000000.local

After the fix, output contains:

[1750949673.937] [490770:490770] [DL] Using Thread extended MAC for hostname.
[1750949673.937] [490770:490770] [DIS] Advertise commission parameter vendorID=65521 productID=32769 discriminator=3840/15 cm=1 cp=0
[1750949673.937] [490770:490770] [DIS] Responding with _matterc._udp.local
[1750949673.937] [490770:490770] [DIS] Responding with 43DA52909547070B._matterc._udp.local
[1750949673.937] [490770:490770] [DIS] Responding with 6A58CF8656C9F369.local

and

"ot-ctl extaddr" in the above example test returns:
6a58cf8656c9f369
Done

### CODE REVIEW

File: src/platform/Linux/ThreadStackManagerImpl.cpp [hunk 1]
```diff
@@ -545,15 +545,65 @@
...
+                mExtendedAddress[sizeof(mExtendedAddress) - i - 1] = (address_value & UINT8_MAX);
+                address_value >>= CHAR_BIT;
+            }
+        }
+        else
+        {
+            ChipLogError(DeviceLayer, "ERROR: Property 'ExtendedAddress' returned unexpected type: %s",
+                    g_variant_get_type_string(value.get()));
+        }
+     }
```
[the remark this answers is not in the document]
Comment (tleacmcsa) [reply src/platform/Linux/ThreadStackManagerImpl.cpp]: comment already says it does not change.

File: src/platform/Linux/ThreadStackManagerImpl.cpp [hunk 2]
```diff
@@ -545,15 +545,65 @@
...
-    VerifyOrReturnError(mProxy, CHIP_ERROR_INCORRECT_STATE);
-    guint64 extAddr = openthread_border_router_get_extended_address(mProxy.get());
+     VerifyOrReturnError(mProxy, CHIP_ERROR_INCORRECT_STATE);
+
+    // The ExtendedAddress d-bus property from otbr-agent is defined to not emit changed signals.
+    // This means the generated api, which uses a caching proxy underneath, will not obtain a value
+    // and will always return NULL. In order to retrieve the value in this case, we must directly
+    // call the Get function to get it, then we manually cache locally since it does not change.
+    if (std::all_of(mExtendedAddress, mExtendedAddress + sizeof(mExtendedAddress),
+                     [](uint8_t v) { return v == 0; }))
```
[the remark this answers is not in the document]
Comment (tleacmcsa) [reply src/platform/Linux/ThreadStackManagerImpl.cpp]: external system warrants retries.  this is an infrequently called function as well.

File: src/platform/Linux/ThreadStackManagerImpl.cpp [hunk 3]
```diff
@@ -545,15 +545,65 @@ CHIP_ERROR ThreadStackManagerImpl::_GetAndLogThreadTopologyFull()
...
+            {
+                mExtendedAddress[sizeof(mExtendedAddress) - i - 1] = (address_value & UINT8_MAX);
+                address_value >>= CHAR_BIT;
+            }
+        }
+        else
+        {
+            ChipLogError(DeviceLayer, "ERROR: Property 'ExtendedAddress' returned unexpected type: %s",
+                    g_variant_get_type_string(value.get()));
+        }
```
[the remark this answers is not in the document]
Comment (tleacmcsa) [reply src/platform/Linux/ThreadStackManagerImpl.cpp]: Thanks, gemini!

File: src/platform/Linux/ThreadStackManagerImpl.cpp [hunk 4]
```diff
@@ -546,14 +546,64 @@ CHIP_ERROR ThreadStackManagerImpl::_GetAndLogThreadTopologyFull()
...
+    if (std::all_of(mExtendedAddress, mExtendedAddress + sizeof(mExtendedAddress), [](uint8_t v) { return v == 0; }))
     {
-        buf[sizeof(uint64_t) - i - 1] = (extAddr & UINT8_MAX);
-        extAddr >>= CHAR_BIT;
+        GAutoPtr<GError> err;
+        GAutoPtr<GVariant> response(g_dbus_proxy_call_sync(G_DBUS_PROXY(mProxy.get()), "org.freedesktop.DBus.Properties.Get",
+                                                           g_variant_new("(ss)", "io.openthread.BorderRouter", "ExtendedAddress"),
+                                                           G_DBUS_CALL_FLAGS_NONE, -1, nullptr, &err.GetReceiver()));
+
+        if (err)
```
Comment (jmartinez-silabs) [inline src/platform/Linux/ThreadStackManagerImpl.cpp]: The use of
VerifyOrReturnError(err, CHIP_ERROR_INTERNAL, DeviceLayer, "openthread: failed to read ExtendedAddress property: %s", err->message);
 
can improve readability here and for the others check

**Review by jmartinez-silabs — APPROVED** [review]

File: src/platform/Linux/ThreadStackManagerImpl.cpp (hunk 4 above)
Comment (tleacmcsa) [reply src/platform/Linux/ThreadStackManagerImpl.cpp]: Good idea, thanks.  Done.

**Review by arkq — APPROVED** [review]

File: src/platform/Linux/ThreadStackManagerImpl.cpp [hunk 5]
```diff
@@ -546,14 +546,47 @@ CHIP_ERROR ThreadStackManagerImpl::_GetAndLogThreadTopologyFull()
 CHIP_ERROR ThreadStackManagerImpl::_GetPrimary802154MACAddress(uint8_t * buf)
 {
     VerifyOrReturnError(mProxy, CHIP_ERROR_INCORRECT_STATE);
-    guint64 extAddr = openthread_border_router_get_extended_address(mProxy.get());
```
Comment (arkq) [inline src/platform/Linux/ThreadStackManagerImpl.cpp:549]: Please also remove the `<property name="ExtendedAddress" type="t" access="read">` from the `src/platform/Linux/dbus/openthread/DBusOpenthread.xml` if `openthread_border_router_get_extended_address` can not be used for obtaining the value.

Also, what with other properties annotated with  `EmitsChangedSignal=false`? Can we rely on getters for these properties, e.g.: https://github.com/project-chip/connectedhomeip/blob/master/src/platform/Linux/ThreadStackManagerImpl.cpp#L185 ?

Comment (tleacmcsa) [reply src/platform/Linux/ThreadStackManagerImpl.cpp:549]: I removed the 3 problematic properties.  They werent being used anyway.

Comment (tleacmcsa) [reply src/platform/Linux/ThreadStackManagerImpl.cpp:549]: correction: they werent being read.  they were being written to, which is fine with the caching proxy, so I left them in but marked them write only so the read/getter isnt generated.
