### PR TITLE
Fix handling of deadband in themostat constraint enforcement.

### LINKED ISSUE #19551: Thermostat cluster only considers deadband if OCC feature is enabled
This was discovered by @mkleszcz-no in #19468, but filing as a separate issue to make the problem very clear.  https://github.com/project-chip/connectedhomeip/issues/19468#issuecomment-1153695041 has very nice steps to reproduce the problem.

#### Problem
In thermostat-server.cpp in `MatterThermostatClusterServerPreAttributeChangedCallback` we have:
```
    int16_t DeadBandTemp                     = 0;
    int8_t DeadBand                          = 0;
...
    if (OurFeatureMap & 1 << 2)

        if (AutoSupported)
        {
            if (MinSetpointDeadBand::Get(endpoint, &DeadBand) != EMBER_ZCL_STATUS_SUCCESS)
            {
                DeadBand = kDefaultDeadBand;
            }
            DeadBandTemp = static_cast<int16_t>(DeadBand * 10);
        }
```
which means that deadband is ignored if bit 2 (OCC) is not set in the feature map.

This does not match either `emberAfThermostatClusterSetpointRaiseLowerCallback` or the spec; we should be considering deadband any time we support AUTO, I would think.

@chrisbeach59 Is this purposeful or just a merge conflict?

 #### Proposed Solution
Remove that `if (OurFeatureMap & 1 << 2)` line.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
The deadband support was incorrectly conditioned on the OCC bit
(feature bit 2), and we were never setting OccupancySupported to
true. Our test apps don't set the OCC bit, so this last was not
getting caught.

Fixes https://github.com/project-chip/connectedhomeip/issues/19551

#### Problem
See above.

#### Change overview
Set OccupancySupported in the body of the if for bit 2, and move the deadband bits out of that body.

#### Testing
The Thermostat YAMLs will presumably test this once those get fixed.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by chrisbeach59 — APPROVED** [review]

File: src/app/clusters/thermostat-server/thermostat-server.cpp [hunk 1]
```diff
@@ -127,15 +127,16 @@ MatterThermostatClusterServerPreAttributeChangedCallback(const app::ConcreteAttr
         CoolSupported = true;
 
     if (OurFeatureMap & 1 << 2)
+        OccupancySupported = true
```
Comment (bzbarsky-apple) [inline src/app/clusters/thermostat-server/thermostat-server.cpp:130]:
```suggestion
        OccupancySupported = true;
```

**Review by woody-apple — APPROVED** [review]
