### PR TITLE
Stop using a fixed salt when opening commissioning windows.

### LINKED ISSUE #10586: Salt used for commissioning window should be randomly generated
#### Problem

`PASESession.cpp` defines a hardcoded salt value (`"SPAKE2P Key Salt"`) which is used in relation to opening a commissioning window, in `CommissioningWindowManager.cpp`, `CHIPDevice.cpp`, and `CHIPDeviceController.cpp`. 

 #### Proposed Solution

Per 11.19.7.1. OpenCommissioningWindow (OCW) Command and 3.9. Password-Based Key Derivation Function (PBKDF), this salt should be derived from a random number source, and be between 16 and 32 bytes.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Fixes https://github.com/project-chip/connectedhomeip/issues/10586

#### Problem
We're using a hardcoded salt value, which is not the right thing.

#### Change overview
Add a way for consumers to pass in a salt (if they want to reuse a single onboarding payload for multiple devices) or have it be randomly generated.

#### Testing
Verified that `chip-tool pairing open-commissioning-window` works and I can then commission into a different fabric using the resulting onboarding payload.

### CODE REVIEW

File: src/controller/CommissioningWindowOpener.cpp [hunk 1]
```diff
@@ -72,6 +80,19 @@ CHIP_ERROR CommissioningWindowOpener::OpenCommissioningWindow(NodeId deviceId, S
...
 
+    if (salt.HasValue())
+    {
+        memcpy(mPBKDFSaltBuffer, salt.Value().data(), salt.Value().size());
+        mPBKDFSalt = ByteSpan(mPBKDFSaltBuffer, salt.Value().size());
+    }
+    else
+    {
+        // What size should we use?
+        constexpr size_t saltLength = (kSpake2p_Min_PBKDF_Salt_Length + kSpake2p_Max_PBKDF_Salt_Length) / 2;
```
Comment (tcarmelveilleux) [inline src/controller/CommissioningWindowOpener.cpp:91]: Use max length

Comment (bzbarsky-apple) [reply src/controller/CommissioningWindowOpener.cpp]: Done.

**Review by tcarmelveilleux — APPROVED** [review]

File: src/controller/CommissioningWindowOpener.cpp [hunk 2]
```diff
@@ -55,11 +55,19 @@ CHIP_ERROR CommissioningWindowOpener::OpenBasicCommissioningWindow(NodeId device
...
                                                               Callback::Callback<OnOpenCommissioningWindow> * callback,
                                                               SetupPayload & payload, bool readVIDPIDAttributes)
 {
     VerifyOrReturnError(mNextStep == Step::kAcceptCommissioningStart, CHIP_ERROR_INCORRECT_STATE);
 
+    VerifyOrReturnError(kSpake2p_Min_PBKDF_Iterations <= iteration && iteration <= kSpake2p_Max_PBKDF_Iterations,
+                        CHIP_ERROR_INVALID_ARGUMENT);
+    VerifyOrReturnError(
+        !salt.HasValue() ||
+            (salt.Value().size() >= kSpake2p_Max_PBKDF_Salt_Length && salt.Value().size() <= kSpake2p_Max_PBKDF_Salt_Length),
```
Comment (Damian-Nordic) [inline src/controller/CommissioningWindowOpener.cpp:68]:
```suggestion
            (salt.Value().size() >= kSpake2p_Min_PBKDF_Salt_Length && salt.Value().size() <= kSpake2p_Max_PBKDF_Salt_Length),
```

**Review by Damian-Nordic — CHANGES_REQUESTED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by Damian-Nordic — APPROVED** [review]
