### PR TITLE
[IM] Fix EnsureResourceForSubscription

### LINKED ISSUE #18380: Bugs in resource enforcement for reads/subscribes
#### Problem
As far as I can tell, we don't properly reserve one read handler _per fabric_.  What we do is:

If a subscribe comes in, and the number of read handlers (so active reads/subscribes) allocated is more than (total available - number of fabrics) we start evicting existing subscriptions.  As a simple example, if MAX_FABRICS were 2 and we supported 3 subscriptions + 1 read per fabric, we would have a cap of 6 subscriptions in `EnsureResourceForSubscription`.  If we have 2 subscriptions on fabric 1, 2 subscriptions on fabric 2, and 2 reads in progress, an attempt to establish a new subscription will evict one of the existing ones.

Worse yet, if we have 3 subscriptions on fabric 1, 2 subscriptions on fabric 2, and 2 reads in progress (total of 7), an attempt to establish a new subscription on fabric 2 will evict _both_ existing subscriptions even though we could have just established our new subscription without evicting anything.

That also means that this block of code in `InteractionModelEngine::OnReadInitialRequest`:
```
    // Reserve the last ReadHandler for ReadInteraction
    if (aInteractionType == ReadHandler::InteractionType::Subscribe && ((handlerPoolCapacity - GetNumActiveReadHandlers()) == 1) &&
        !HasActiveRead())
    {
        ChipLogDetail(InteractionModel, "Reserve the last ReadHandler for IM read Interaction");
        aStatus = Protocols::InteractionModel::Status::ResourceExhausted;
        return CHIP_NO_ERROR;
    }
```
is dead code, because after we finish `EnsureResourceForSubscription` we will always have MAX_FABRICS available read handlers, as far as I can tell.

 #### Proposed Solution
1. Fix logic in `EnsureResourceForSubscription`.  Probably remove the code in `OnReadInitialRequest`, because `EnsureResourceForSubscription` should handle that.  
2. Add tests that would catch this, if we can.  Would involve chunked reads that are still in progress when a subscription request comes in; should be doable with wildcard reads, perhaps.

@erjiaqing @mrjerryjohns

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem
`EnsureResourceForSubscription` should only count the resources used by subscriptions, however, it is counting read and subscriptions previously.

Fixes #18380 

#### Change overview

Only count the resources used by subscriptions in EnsureResourceForSubscription.

#### Testing

- Made a "infinity read" transaction when testing the logic of evicting subscriptions.
- The test will fail if the change in src/app/InteractionModelEngine.cpp is reverted.

### CODE REVIEW

File: src/app/InteractionModelEngine.cpp [hunk 1]
```diff
@@ -688,10 +706,8 @@ bool InteractionModelEngine::EnsureResourceForSubscription(FabricIndex aFabricIn
     }
 
     const auto evictAndUpdateResourceUsage = [&](FabricIndex fabricIndex, bool forceEvict) {
-        bool ret           = TrimFabric(fabricIndex, forceEvict);
-        usedAttributePaths = mAttributePathPool.Allocated();
-        usedEventPaths     = mEventPathPool.Allocated();
-        usedReadHandlers   = mReadHandlers.Allocated();
+        bool ret = TrimFabric(fabricIndex, forceEvict);
+        countResourceUsage();
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.cpp:710]: This looks great, but do we still need the "Reserve the last ReadHandler for ReadInteraction" bits in `InteractionModelEngine::OnReadInitialRequest`?  It seems to me that this function ensures that subscriptions never use up more than (total read handlers - MAX_FABRICS), so that block of code is redundant (and not really right, since it's not reserving one per fabric anyway).  Or am I missing something?

File: src/controller/tests/data_model/TestRead.cpp [hunk 2]
```diff
@@ -1582,6 +1631,7 @@ void EstablishSubscriptions(nlTestSuite * apSuite, SessionHandle sessionHandle,
 
 void TestReadInteraction::TestReadHandler_KillOverQuotaSubscriptions(nlTestSuite * apSuite, void * apContext)
 {
+    // Note: We cannot use ctx.DrainAndServiceIO() since the infinity read will make DrainAndServiceIO never returns.
```
Comment (bzbarsky-apple) [inline src/controller/tests/data_model/TestRead.cpp:1634]:
```suggestion
    // Note: We cannot use ctx.DrainAndServiceIO() since the infinity read will make DrainAndServiceIO never return.
```

File: src/controller/tests/data_model/TestRead.cpp [hunk 3]
```diff
@@ -1592,21 +1642,46 @@ void TestReadInteraction::TestReadHandler_KillOverQuotaSubscriptions(nlTestSuite
 
     app::InteractionModelEngine::GetInstance()->RegisterReadHandlerAppCallback(&gTestReadInteraction);
 
+    // Here, we setup two background infinity read requests to simulate parallen Read + Subscriptions.
```
Comment (bzbarsky-apple) [inline src/controller/tests/data_model/TestRead.cpp:1645]:
```suggestion
    // Here, we set up two background infinity read requests to simulate parallel Read + Subscriptions.
```

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/InteractionModelEngine.cpp (hunk 1 above)
Comment (erjiaqing) [reply src/app/InteractionModelEngine.cpp:701]: We no longer need that check, and I should remove it in previous subscription quota PR.

Removed that check.

File: src/controller/tests/data_model/TestRead.cpp [hunk 4]
```diff
@@ -1635,11 +1654,16 @@ void TestReadInteraction::TestReadHandler_KillOverQuotaSubscriptions(nlTestSuite
...
+            apSuite, ctx.GetSessionBobToAlice(), 1, app::InteractionModelEngine::kMinSupportedPathsPerSubscription,
+            app::AttributePathParams(kTestEndpointId, TestCluster::Id, TestCluster::Attributes::Int16u::Id),
+            app::ReadClient::InteractionType::Subscribe, &readCallback, readClients);
 
         readCallback.ClearCounters();
-        ctx.DrainAndServiceIO();
+        ctx.GetIOContext().DriveIOUntil(System::Clock::Seconds16(5), [&]() {
+            return readCallback.mOnSubscriptionEstablishedCount == 1 &&
+                readCallback.mAttributeCount == app::InteractionModelEngine::kMinSupportedPathsPerSubscription;
+        });
```
[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/controller/tests/data_model/TestRead.cpp:1666]: Specifically in this scenario, we should be validating that the subscriptions that remain are those that had compliant path counts. This ensures we kicked out the sub that was not compliant.

File: src/controller/tests/data_model/TestRead.cpp [hunk 5]
```diff
@@ -1655,15 +1679,17 @@ void TestReadInteraction::TestReadHandler_KillOverQuotaSubscriptions(nlTestSuite
     }
     readCallback.ClearCounters();
 
-    ctx.DrainAndServiceIO();
-    // Ensure the global dirty set is cleared.
-    NL_TEST_ASSERT(apSuite, app::InteractionModelEngine::GetInstance()->GetReportingEngine().GetGlobalDirtySetSize() == 0);
+    ctx.GetIOContext().DriveIOUntil(System::Clock::Seconds16(60), [&]() {
```
Comment (mrjerryjohns) [inline src/controller/tests/data_model/TestRead.cpp:1682]: What's the purpose of this block of code? Why are we waiting to get all the attributes across all the subs?

File: src/controller/tests/data_model/TestRead.cpp [hunk 6]
```diff
@@ -1672,12 +1698,19 @@ void TestReadInteraction::TestReadHandler_KillOverQuotaSubscriptions(nlTestSuite
 
     // The following check will trigger the logic in im to kill the read handlers that use more paths than the limit per fabric.
     {
-        EstablishSubscriptions(apSuite, ctx.GetSessionAliceToBob(),
-                               app::InteractionModelEngine::kMinSupportedSubscriptionsPerFabric,
-                               app::InteractionModelEngine::kMinSupportedPathsPerSubscription, &readCallbackFabric2, readClients);
-
-        ctx.GetIOContext().DriveIOUntil(System::Clock::Seconds16(60),
-                                        [&]() { return readCallbackFabric2.mOnSubscriptionEstablishedCount == 1; });
+        EstablishReadOrSubscriptions(
```
Comment (mrjerryjohns) [inline src/controller/tests/data_model/TestRead.cpp:1701]: There is very little comments in this test to provide a way for readers to understand what's happening. It's taking me a while to look at the code to figure out the rationale, would be so much better if we could have good comments. 

This test has to read like a story so that readers understand the flow of how the test is progresing.

You should provide a statement about the current resource situation, what you're going to do, and what the result should look like. 

("we currently have X subscriptions established from Fabric A, and we're going to now add Y subscriptions from Fabric B. This should kick out Z subscriptions from Fabric A, etc.").

File: src/controller/tests/data_model/TestRead.cpp [hunk 7]
```diff
@@ -1672,12 +1698,19 @@ void TestReadInteraction::TestReadHandler_KillOverQuotaSubscriptions(nlTestSuite
...
+            app::InteractionModelEngine::kMinSupportedPathsPerSubscription,
+            app::AttributePathParams(kTestEndpointId, TestCluster::Id, TestCluster::Attributes::Int16u::Id),
+            app::ReadClient::InteractionType::Subscribe, &readCallbackFabric2, readClients);
+
+        ctx.GetIOContext().DriveIOUntil(System::Clock::Seconds16(5), [&]() {
+            return readCallbackFabric2.mOnSubscriptionEstablishedCount ==
+                app::InteractionModelEngine::kMinSupportedSubscriptionsPerFabric &&
+                readCallbackFabric2.mAttributeCount ==
+                app::InteractionModelEngine::kMinSupportedPathsPerSubscription *
+                    app::InteractionModelEngine::kMinSupportedSubscriptionsPerFabric;
```
Comment (mrjerryjohns) [inline src/controller/tests/data_model/TestRead.cpp:1712]: Shouldn't we be validating the # of subscriptions established on fabric A on the server vs. fabric B?

**Review by yunhanw-google — APPROVED** [review]

File: src/controller/tests/data_model/TestRead.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/controller/tests/data_model/TestRead.cpp:1677]: The block below is validating this -- we should evict the correct subscriptions, and to prove it, we should receive correct number of reports.

Added comments on the validating logic below.

File: src/controller/tests/data_model/TestRead.cpp [hunk 8]
```diff
@@ -1623,10 +1640,12 @@ void TestReadInteraction::TestReadHandler_KillOverQuotaSubscriptions(nlTestSuite
     {
         TestReadCallback callback;
         std::vector<std::unique_ptr<app::ReadClient>> outReadClient;
-        EstablishSubscriptions(apSuite, ctx.GetSessionBobToAlice(), 1,
-                               app::InteractionModelEngine::kMinSupportedPathsPerSubscription + 1, &callback, outReadClient);
+        EstablishReadOrSubscriptions(
```
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/controller/tests/data_model/TestRead.cpp:1653]: Splitted this into two parts.

Adds `Since ... if it exceeds minimas` before `SetForceHandlerQuota`

And the case description right before the case.

File: src/controller/tests/data_model/TestRead.cpp [hunk 9]
```diff
@@ -1592,21 +1584,46 @@ void TestReadInteraction::TestReadHandler_KillOverQuotaSubscriptions(nlTestSuite
...
+                                 app::ReadClient::InteractionType::Read, &infinityReadCallback, readClients);
+    ctx.GetIOContext().DriveIOUntil(System::Clock::Seconds16(5), [&]() {
+        return app::InteractionModelEngine::GetInstance()->GetNumActiveReadHandlers(app::ReadHandler::InteractionType::Read) == 2;
+    });
+    // Ensure our read transactions are established.
+    NL_TEST_ASSERT(apSuite,
+                   app::InteractionModelEngine::GetInstance()->GetNumActiveReadHandlers(app::ReadHandler::InteractionType::Read) ==
+                       2);
+
     // Intentially establish subscriptions using exceeded resources.
```
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/controller/tests/data_model/TestRead.cpp:1608]: No, this not for testing heap based allocations, this is to simplify the validating (to ensure we have evicted correct subscriptions) work later.

Added a comment for this.

File: src/controller/tests/data_model/TestRead.cpp (hunk 7 above)
Comment (erjiaqing) [reply src/controller/tests/data_model/TestRead.cpp:1727]: This is what we validate later.

File: src/controller/tests/data_model/TestRead.cpp (hunk 5 above)
Comment (erjiaqing) [reply src/controller/tests/data_model/TestRead.cpp]: To validating we have evicted the correct subscription.

Added a comment for this.

File: src/controller/tests/data_model/TestRead.cpp [hunk 10]
```diff
@@ -2082,21 +2074,52 @@ void TestReadInteraction::TestReadHandler_KillOverQuotaSubscriptions(nlTestSuite
...
     app::InteractionModelEngine::GetInstance()->SetForceHandlerQuota(false);
-    EstablishSubscriptions(apSuite, ctx.GetSessionBobToAlice(), 1,
-                           app::InteractionModelEngine::kMinSupportedPathsPerSubscription + 1, &readCallback, readClients);
-    EstablishSubscriptions(apSuite, ctx.GetSessionBobToAlice(), kExpectedParallelSubs,
-                           app::InteractionModelEngine::kMinSupportedPathsPerSubscription, &readCallback, readClients);
+    // We established kExpectedParallelSubs + 1 subsctions, with (kExpectedParallelSubs + 1) * kMinSupportedPathsPerSubscription + 1
+    // interested paths. This exceeds the limit we set below, and the subscription with kMinSupportedPathsPerSubscription + 1
+    // interested path will be evicted firstly.
+    // We intentially use exceeded resource here to make testing "used exactly all resources" easier.
```
Comment (mrjerryjohns) [inline src/controller/tests/data_model/TestRead.cpp:2103]:
```suggestion
    //
    // We establish 1 subscription that exceeds the minimum supported paths (but is still established since the 
    // target has sufficient resources), and kExpectedParallelSubs subscriptions that conform to the minimum
    // supported paths. This sets the stage to make it possible to test eviction of subscriptions that are in violation
    // of the minimum later below.
    //
```

**Review by mrjerryjohns — APPROVED** [review]
Few small comments remain, but LGTM otherwise.

File: src/controller/tests/data_model/TestRead.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/controller/tests/data_model/TestRead.cpp:2168]: This is a bit tricky, there is _exactly_ one subscription uses exceeded resources, and we can use up _exactly_ all resources only if we evicted that subscription.

File: src/controller/tests/data_model/TestRead.cpp [hunk 11]
```diff
@@ -1635,11 +1654,16 @@ void TestReadInteraction::TestReadHandler_KillOverQuotaSubscriptions(nlTestSuite
...
-                               app::InteractionModelEngine::kMinSupportedPathsPerSubscription, &readCallback, readClients);
+        EstablishReadOrSubscriptions(
+            apSuite, ctx.GetSessionBobToAlice(), 1, app::InteractionModelEngine::kMinSupportedPathsPerSubscription,
+            app::AttributePathParams(kTestEndpointId, TestCluster::Id, TestCluster::Attributes::Int16u::Id),
+            app::ReadClient::InteractionType::Subscribe, &readCallback, readClients);
 
         readCallback.ClearCounters();
-        ctx.DrainAndServiceIO();
+        ctx.GetIOContext().DriveIOUntil(System::Clock::Seconds16(5), [&]() {
+            return readCallback.mOnSubscriptionEstablishedCount == 1 &&
```
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/controller/tests/data_model/TestRead.cpp:2204]: This is not for validating, the actual validating is the code below.
