### PR TITLE
Make AddStatus generally VerifyOrDie and have centralized logging

### LINKED ISSUE #28630: [BUG] AddStatus error code is often ignored
### Reproduction steps

Examples from `rg -- '->AddStatus'`:

```
...
examples/ota-provider-app/ota-provider-common/OTAProviderExample.cpp:                commandObj->AddStatus(commandPath, Status::Failure);
examples/ota-provider-app/ota-provider-common/OTAProviderExample.cpp:    commandObj->AddStatus(commandPath, Status::Success);
src/controller/tests/data_model/TestCommands.cpp:            apCommandObj->AddStatusAndLogIfFailure(aCommandPath, Protocols::InteractionModel::Status::Failure,
src/controller/tests/data_model/TestCommands.cpp:            apCommandObj->AddStatus(aCommandPath, Protocols::InteractionModel::Status::Success);
src/controller/tests/data_model/TestCommands.cpp:                apCommandObj->AddStatusAndLogIfFailure(aCommandPath, Protocols::InteractionModel::Status::Succes
...
src/app/clusters/channel-server/channel-server.cpp:        command->AddStatus(commandPath, Status::Failure);
src/app/clusters/channel-server/channel-server.cpp:    command->AddStatus(commandPath, status);
src/app/clusters/channel-server/channel-server.cpp:    command->AddStatus(commandPath, status);
src/app/clusters/identify-server/identify-server.cpp:    commandObj->AddStatus(commandPath,
src/app/clusters/identify-server/identify-server.cpp:    commandObj->AddStatus(commandPath, Status::Success);
...
```

A large percentage of AddStatus commands are never actually checked for return codes.

This has two sideffects:
  - errors are never seen in logs
  - we have no sane way to handle AddStatus failures (would we return success without an error code?)

We likely would want to VerifyOrDie unless we are able to handle the error in some way.
Also need to review usage of `AddStatusAndLogIfFailure` since that both logs failure statuses (seems to be the intended functionality) but also adds a log of failed statuses (VerifyOrDie seems more correct though as we cannot really handle the failure).

### PR DESCRIPTION
**Pull request by andy31415**
- Make AddStatus have integrated logging on failure and VerifyOrDie on failure
- Add `FailableAddStatus` when we think we can handle or forward the underlying CHIP_ERROR

Fixes #28630

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]

File: src/app/CommandHandler.cpp [hunk 1]
```diff
@@ -468,31 +468,21 @@ CHIP_ERROR CommandHandler::AddStatusInternal(const ConcreteCommandPath & aComman
     return FinishStatus();
 }
 
-CHIP_ERROR CommandHandler::AddStatus(const ConcreteCommandPath & aCommandPath, const Status aStatus)
+CHIP_ERROR CommandHandler::FailableAddStatus(const CommandPathStatus & status, const char * context, LogOption logging_option)
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.cpp:471]:
```suggestion
CHIP_ERROR CommandHandler::FallibleAddStatus(const CommandPathStatus & status, const char * context, LogOption logging_option)
```

File: src/app/CommandHandler.cpp [hunk 2]
```diff
@@ -468,31 +468,21 @@ CHIP_ERROR CommandHandler::AddStatusInternal(const ConcreteCommandPath & aComman
...
     {
-        ChipLogError(DataManagement,
-                     "Failed to handle on Endpoint=%u Cluster=" ChipLogFormatMEI " Command=" ChipLogFormatMEI
-                     " with " ChipLogFormatIMStatus ": %s",
-                     aCommandPath.mEndpointId, ChipLogValueMEI(aCommandPath.mClusterId), ChipLogValueMEI(aCommandPath.mCommandId),
-                     ChipLogValueIMStatus(aStatus), aMessage);
+    case LogOption::kFailures:
+        status.LogIfFailure(context);
+        break;
+    case LogOption::kAll:
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.cpp:478]: Why do we have the kAll option?  It's not used anywhere, but the way this is structured it requires the code to exist to support it....

File: src/app/CommandHandler.cpp [hunk 3]
```diff
@@ -468,31 +468,21 @@ CHIP_ERROR CommandHandler::AddStatusInternal(const ConcreteCommandPath & aComman
...
+        status.LogStatus(context);
+        break;
+    case LogOption::kNone:
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.cpp:481]: Similarly, where would kNone be used?  We should just log here, period, if we're going to do this....

File: src/app/CommandHandler.h [hunk 4]
```diff
@@ -170,13 +178,38 @@ class CommandHandler : public Messaging::ExchangeDelegate
...
+    inline void AddStatus(const CommandPathStatus & status, const char * context = nullptr,
+                          LogOption logging_option = LogOption::kFailures)
+    {
+        VerifyOrDie(FailableAddStatus(status, context, logging_option) == CHIP_NO_ERROR);
+    }
+
+    inline CHIP_ERROR FailableAddStatus(const ConcreteCommandPath & aCommandPath, const Protocols::InteractionModel::Status aStatus,
+                                        const char * context = nullptr, LogOption logging_option = LogOption::kFailures)
+    {
+        return FailableAddStatus(CommandPathStatus(aCommandPath, aStatus), context, logging_option);
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.h:204]: So... what is the benefit of the CommandPathStatus here, over just passing through the path and status?  

It seems like extra complexity and a bit of extra overhead (to copy various bits around), but for not much reason....  especially if we remove the support for "log all" and "log none".

File: src/app/CommandResponseHelper.h [hunk 5]
```diff
@@ -53,7 +53,7 @@ class CommandResponseHelper
 
     CHIP_ERROR Failure(Protocols::InteractionModel::Status aStatus)
     {
-        CHIP_ERROR err = mCommandHandler->AddStatus(mCommandPath, aStatus);
+        CHIP_ERROR err = mCommandHandler->FailableAddStatus(mCommandPath, aStatus);
```
Comment (bzbarsky-apple) [inline src/app/CommandResponseHelper.h:56]: This is fake error handling. What the caller of this will do if mSentResponse is false is ... AddStatus.

So we should just AddStatus here and set mSentResponse to true unconditionally....

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 6]
```diff
@@ -3327,7 +3327,7 @@ CHIP_ERROR DoorLockServer::sendClusterResponse(chip::app::CommandHandler * comma
     }
     else
     {
-        err = commandObj->AddStatus(commandPath, ToInteractionModelStatus(status));
+        err = commandObj->FailableAddStatus(commandPath, ToInteractionModelStatus(status));
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:3330]: More fake error handling: nothing ever checks the return value of sendClusterResponse....

File: src/app/tests/TestCommandInteraction.cpp [hunk 7]
```diff
@@ -1095,8 +1095,8 @@ void TestCommandInteraction::TestCommandHandlerCommandEncodeExternalFailure(nlTe
 
     err = commandHandler.AddResponseData(ConcreteCommandPath(path.mEndpointId, path.mClusterId, path.mCommandId), BadFields());
     NL_TEST_ASSERT(apSuite, err != CHIP_NO_ERROR);
-    err = commandHandler.AddStatus(ConcreteCommandPath(path.mEndpointId, path.mClusterId, path.mCommandId),
-                                   Protocols::InteractionModel::Status::Failure);
+    err = commandHandler.FailableAddStatus(ConcreteCommandPath(path.mEndpointId, path.mClusterId, path.mCommandId),
+                                           Protocols::InteractionModel::Status::Failure);
     NL_TEST_ASSERT(apSuite, err == CHIP_NO_ERROR);
```
Comment (bzbarsky-apple) [inline src/app/tests/TestCommandInteraction.cpp:1100]: This could just as easily call the infallible version and let the test crash on fail.

File: src/controller/tests/data_model/TestCommands.cpp [hunk 8]
```diff
@@ -116,27 +115,32 @@ void DispatchSingleClusterCommand(const ConcreteCommandPath & aCommandPath, chip
         }
         else if (responseDirective == kSendMultipleSuccessStatusCodes)
         {
+            apCommandObj->AddStatus(aCommandPath, Protocols::InteractionModel::Status::Success,
+                                    "No error but testing status success case");
+
             // TODO: Right now all but the first AddStatus call fail, so this
             // test is not really testing what it should.
-            for (size_t i = 0; i < 4; ++i)
+            for (size_t i = 0; i < 3; ++i)
```
Comment (bzbarsky-apple) [inline src/controller/tests/data_model/TestCommands.cpp:123]: Why the bounds change?

File: src/controller/tests/data_model/TestCommands.cpp [hunk 9]
```diff
@@ -116,27 +115,32 @@ void DispatchSingleClusterCommand(const ConcreteCommandPath & aCommandPath, chip
...
             apCommandObj->AddStatus(aCommandPath, Protocols::InteractionModel::Status::Failure);
         }
         else if (responseDirective == kSendMultipleErrors)
         {
+            apCommandObj->AddStatus(aCommandPath, Protocols::InteractionModel::Status::Failure);
+
             // TODO: Right now all but the first AddStatus call fail, so this
             // test is not really testing what it should.
-            for (size_t i = 0; i < 4; ++i)
+            for (size_t i = 0; i < 3; ++i)
```
Comment (bzbarsky-apple) [inline src/controller/tests/data_model/TestCommands.cpp:141]: Why the bounds change?

File: src/controller/tests/data_model/TestCommands.cpp [hunk 10]
```diff
@@ -116,27 +115,32 @@ void DispatchSingleClusterCommand(const ConcreteCommandPath & aCommandPath, chip
...
-            apCommandObj->AddStatus(aCommandPath, Protocols::InteractionModel::Status::Failure);
+            (void) apCommandObj->FailableAddStatus(aCommandPath, Protocols::InteractionModel::Status::Failure);
         }
         else if (responseDirective == kSendError)
         {
             apCommandObj->AddStatus(aCommandPath, Protocols::InteractionModel::Status::Failure);
         }
         else if (responseDirective == kSendMultipleErrors)
         {
+            apCommandObj->AddStatus(aCommandPath, Protocols::InteractionModel::Status::Failure);
```
Comment (bzbarsky-apple) [inline src/controller/tests/data_model/TestCommands.cpp:137]: This is going to make the test fail, since right now it expects a success status because of the todo.

But more generally: I wonder whether we need a public FallibleAddStatus at all, or whether we should just fix this test to test what it's _actually_ testing and leave the todo comments about how it should test something else.  And if FallibleAddStatus is internal-only, it could return Status, since that's what all its consumers want, and we could save a bit of codesize....

File: src/controller/tests/data_model/TestCommands.cpp (hunk 8 above)
Comment (andy31415) [reply src/controller/tests/data_model/TestCommands.cpp:123]: Tried to make the code equivalent. Realistically it does not matter ...

File: src/app/CommandHandler.cpp (hunk 3 above)
Comment (andy31415) [reply src/app/CommandHandler.cpp]: I thought we would use different logging options, but aggree applying some "you ain't gonna need it" is good here.

File: src/app/CommandResponseHelper.h (hunk 5 above)
Comment (andy31415) [reply src/app/CommandResponseHelper.h]: I think I should only do so if we make Failure return void. since currently we claim this is a Fallible path since we return chip error, doing the falllible bit seems to apply.

I also think you are correct that these should just be void, however I would rather do that as a separate PR.

Comment (bzbarsky-apple) [reply src/app/CommandResponseHelper.h]: Mostly if we don't use FallibleAddStatus here we can fix its signature to make sense for the CommandHandler-internal uses...  But yes, followup is fine for this.

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 6 above)
Comment (andy31415) [reply src/app/clusters/door-lock-server/door-lock-server.cpp]: Updated this to return void.

File: src/controller/tests/data_model/TestCommands.cpp (hunk 10 above)
Comment (andy31415) [reply src/controller/tests/data_model/TestCommands.cpp:137]: I believe this does no changes from the previous state: we used to have 4 failures and a success.
I kept the same thing, but kept the first failure state as unconditional (because it does not fail) and set all the other ones to accept errors (since this is what they did).

I don't think this test actually validates what it thinks it does (we even have a comment about that) however that is not something that I changed.

Comment (bzbarsky-apple) [reply src/controller/tests/data_model/TestCommands.cpp:137]: This test definitely does not validate what it thinks it does, we agree on that.

I see now, you moved the first loop iteration out.  OK, that makes sense, and I was just misreading things....

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
Note: this is being reverted in https://github.com/project-chip/connectedhomeip/pull/28661 due to the OpenIOT perma-fail after this PR merged.  Which is odd, because that job passed in the PR itself, but it's consistently failing _everywhere_ after the merge.
