### PR TITLE
[fix] optimize tag list api in descriptor cluster

### LINKED ISSUE #28894: Address review comments on PR 28753
### Reproduction steps

@mideayanghui please see https://github.com/project-chip/connectedhomeip/pull/28753#pullrequestreview-1595950457

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

cac5620a1d60040170a7c6cea84c4a28536cef9a

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mideayanghui**
fixes: https://github.com/project-chip/connectedhomeip/issues/28894

### CODE REVIEW

File: src/app/clusters/descriptor/descriptor.cpp [hunk 1]
```diff
@@ -64,20 +63,20 @@ CHIP_ERROR DescriptorAttrAccess::ReadFeatureMap(EndpointId endpoint, AttributeVa
     size_t index = 0;
     BitFlags<Feature> featureFlags;
 
-    if (GetTagListFromEndpointAtIndex(endpoint, index, tag) == CHIP_NO_ERROR)
+    if (GetSematicTagForEndpointAtIndex(endpoint, index, tag) == CHIP_NO_ERROR)
```
Comment (bzbarsky-apple) [inline src/app/clusters/descriptor/descriptor.cpp:66]:
```suggestion
    if (GetSemanticTagForEndpointAtIndex(endpoint, index, tag) == CHIP_NO_ERROR)
```

**Review by bzbarsky-apple — APPROVED** [review]

**Review by rbultman — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
