### PR TITLE
Fix possible exchange leak in session establishment

### LINKED ISSUE #13422: exchange leak in DeviceCommissioner::EstablishPASEConnection
#### Problem

At this rev:

```
commit b53521c4ee34cc9d53d7524d446ccd9be0af3fa0 (origin/master, origin/HEAD)
Author: Michael Sandstedt <michael.sandstedt@smartthings.com>
Date:   Fri Jan 7 17:49:40 2022 -0600

    Cleanup CASESession and PASESession lifetime (#13357)
```

In this code:

```
    exchangeCtxt = mSystemState->ExchangeMgr()->NewContext(session.Value(), &device->GetPairing());
    VerifyOrExit(exchangeCtxt != nullptr, err = CHIP_ERROR_INTERNAL);

    err = mIDAllocator.Allocate(keyID);
    SuccessOrExit(err);

    // TODO - Remove use of SetActive/IsActive from CommissioneeDeviceProxy
    device->SetActive(true);

    err = device->GetPairing().Pair(params.GetPeerAddress(), params.GetSetupPINCode(), keyID,
                                    Optional<ReliableMessageProtocolConfig>::Value(mMRPConfig), exchangeCtxt, this);
```

This was identified here: https://github.com/project-chip/connectedhomeip/pull/13294#discussion_r780844434

`device->GetPairing().Pair()` will free the exchange on error, but only if it is called.  If `mIDAllocator.Allocate(keyID);` fails, this code leaks the exchange.

A similar leak for CASE likely exists in OperationalDeviceProxy or CASESessionManager.

 #### Proposed Solution

This would cause this code not to leak:

```
diff --git a/src/controller/CHIPDeviceController.cpp b/src/controller/CHIPDeviceController.cpp
index a5d3e36e4..ce183bdfc 100644
--- a/src/controller/CHIPDeviceController.cpp
+++ b/src/controller/CHIPDeviceController.cpp
@@ -832,8 +832,6 @@ CHIP_ERROR DeviceCommissioner::EstablishPASEConnection(NodeId remoteDeviceId, Re
     session = mSystemState->SessionMgr()->CreateUnauthenticatedSession(params.GetPeerAddress(), device->GetMRPConfig());
     VerifyOrExit(session.HasValue(), err = CHIP_ERROR_NO_MEMORY);
 
-    exchangeCtxt = mSystemState->ExchangeMgr()->NewContext(session.Value(), &device->GetPairing());
-    VerifyOrExit(exchangeCtxt != nullptr, err = CHIP_ERROR_INTERNAL);
 
     err = mIDAllocator.Allocate(keyID);
     SuccessOrExit(err);
@@ -841,6 +839,15 @@ CHIP_ERROR DeviceCommissioner::EstablishPASEConnection(NodeId remoteDeviceId, Re
     // TODO - Remove use of SetActive/IsActive from CommissioneeDeviceProxy
     device->SetActive(true);
 
+    // Allocate the exchange immediately before calling PASESession::Pair.
+    //
+    // PASESession::Pair takes ownership of the exchange and will free it on
+    // error, but can only do this if it is actually called.  Allocating the
+    // exchange context right before calling Pair ensures that if allocation
+    // succeeds, PASESession has taken ownership.
+    exchangeCtxt = mSystemState->ExchangeMgr()->NewContext(session.Value(), &device->GetPairing());
+    VerifyOrExit(exchangeCtxt != nullptr, err = CHIP_ERROR_INTERNAL);
+
     err = device->GetPairing().Pair(params.GetPeerAddress(), params.GetSetupPINCode(), keyID,
                                     Optional<ReliableMessageProtocolConfig>::Value(mMRPConfig), exchangeCtxt, this);
     SuccessOrExit(err);
```

Perhaps better though would be for PASESession just to allocate its own exchange context.

### PR DESCRIPTION
**Pull request by msandstedt**
#### Problem

The CASESession and PASESession objects take ownership of their exchange contexts once passed, and will free and / or close them as appropriate.  However, for this object lifecycle management to occur, exchange contexts must be passed to these objects in the first place.
    
The current session establishment calls do not do this if early-out failures occur between allocation of the exchange contexts and calls to the session establishment methods.

#### Change overview
   
This commit fixes this problem by allocating exchanges immediately before the calls to the session establishment methods.  This removes the possibility of early-out failures causing leaks.

Fixes #13422

#### Testing

Manual testing shows that session establishment is working as before.  CI will show the same.

Unfortunately, triggering the failure path requires additional code modification, and unit testing would not currently be feasible.

A better solution would be for the CASESession and PASESession to allocate their own sessions.  However, this fix is smaller and the possible leaks it fixes are very plainly obvious in the code.

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

File: src/app/CASEClient.cpp [hunk 1]
```diff
@@ -35,12 +35,18 @@ CHIP_ERROR CASEClient::EstablishSession(PeerId peer, const Transport::PeerAddres
     Optional<SessionHandle> session = mInitParams.sessionManager->CreateUnauthenticatedSession(peerAddress, mrpConfig);
     VerifyOrReturnError(session.HasValue(), CHIP_ERROR_NO_MEMORY);
 
-    Messaging::ExchangeContext * exchange = mInitParams.exchangeMgr->NewContext(session.Value(), &mCASESession);
-    VerifyOrReturnError(exchange != nullptr, CHIP_ERROR_INTERNAL);
-
     uint16_t keyID = 0;
     ReturnErrorOnFailure(mInitParams.idAllocator->Allocate(keyID));
 
+    // Allocate the exchange immediately before calling PASESession::Pair.
```
Comment (tcarmelveilleux) [inline src/app/CASEClient.cpp:41]: This comment is stale/unapplicable

**Review by tcarmelveilleux — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]
