### PR TITLE
Unit localization cluster constraints

### LINKED ISSUE #20879: [TC-LUNIT-3.1]When TH writes TemperatureUnit attribute value more than 2, DUT responds as success instead CONSTRAINT_ERROR.
**Test Case ID**
[TC-LUNIT-3.1] Read and Write Unit Localization Cluster Attributes [{DUT_Server}]

**Describe the issue:-**
As per test-plan test step 8 is expecting to write 5 to TemperatureUnit attribute  from TH to DUT,  DUT should responds with constraint error But currently it is responding as success.

 **expected behavior**:-CONSTRAINT_ERROR(0x87)
 * **actual behavior**:-Success(0x00)
 * **steps to reproduce**:-./chip-tool unitlocalization write temperature-unit 5 1 0
 * **system configuration**
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : IP and wifi
Commit-ID:0390a8d33b1d1c709fcc4499eab6e132428ad5e2
Dut application: all-clusters-app

**Test-plan Reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/unitlocalization.adoc#tc-lunit-3-1-read-and-write-unit-localization-cluster-attributes-dut_server

**Spec Reference:-**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/LocalizationUnit.adoc#data-types

**PFA logs:-**
[[TC-LUNIT-3.1].txt](https://github.com/project-chip/connectedhomeip/files/9134257/TC-LUNIT-3.1.txt)

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem

Unit localization cluster does not validate the temperature unit.
Fixes #20879 

#### Change overview
- set min/max values for the unit localization
- add unit tests

#### Testing
CI should run tests. Also ran locally:

```
./scripts/tests/run_test_suite.py --target Test_TC_LUNIT_3_1 --chip-tool ./out/linux-x64-chip-tool/chip-tool run --all-clusters-app ./out/linux-x64-all-clusters/chip-all-clusters-app --tv-app none --lock-app none --ota-provider-app none --ota-requestor-app none
```

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

File: src/app/clusters/unit-localization/unit-localization.cpp [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+#include <app/util/attribute-metadata.h>
+#include <protocols/interaction_model/StatusCode.h>
+
+using namespace chip;
+using namespace chip::app::Clusters::UnitLocalization;
+
+using chip::app::ConcreteAttributePath;
+using Status = Protocols::InteractionModel::Status;
+
+Status MatterUnitLocalizationClusterServerPreAttributeChangedCallback(const ConcreteAttributePath & attributePath,
```
Comment (mrjerryjohns) [inline src/app/clusters/unit-localization/unit-localization.cpp:29]: Isn't this supposed to return an `EmberAfStatus`?

Comment (mrjerryjohns) [reply src/app/clusters/unit-localization/unit-localization.cpp:29]: Hmm, it looks like everyone does this, and I think this is only working because `ToInteractionModelStatus(EmberAfStatus code)` is just blindly casting it over...

Sigh.

File: src/app/clusters/unit-localization/unit-localization.cpp [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+                                                                      uint8_t * value)
+{
+    Protocols::InteractionModel::Status res;
+
+    switch (attributePath.mAttributeId)
+    {
+    case Attributes::TemperatureUnit::Id:
+        // value is based of an enum_8
+        if ((*value != to_underlying(TempUnit::kFahrenheit)) && (*value != to_underlying(TempUnit::kCelsius)) &&
+            (*value != to_underlying(TempUnit::kKelvin)))
```
Comment (bzbarsky-apple) [inline src/app/clusters/unit-localization/unit-localization.cpp:40]: Given these values are contiguous, why not just set the maxvalue in the XML and have the IM pick that up automatically instead of implementing a manual check?

**Review by bzbarsky-apple — DISMISSED** [review]

File: src/app/clusters/unit-localization/unit-localization.cpp (hunk 2 above)
Comment (andy31415) [reply src/app/clusters/unit-localization/unit-localization.cpp]: Done. Did not realize that was an option for enums.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by turon — APPROVED** [review]
