### PR TITLE
Fix support for 0-length hex-encoded octet strings in chip-tool.

### LINKED ISSUE #24054: [BUG] chip-tool cannot write empty octstr to any attribute
### Reproduction steps

```bash
###Problem

Currently it is not possible to use chip-tool to write empty octstr to any attribute. The closest thing is:

./chip-tool any write-by-id 0x130AFC01 0x130A0001 '""' 1 1

but that writes charstr instead.

###Suggestion

Add support for writing empty octstr.
```

### Bug prevalence

always

### GitHub hash of the SDK that was being used

latest

### Platform

darwin, raspi

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Without this fix, these commands all fail to parse:

  chip-tool unittesting write struct-attr '{"a": 1, "b": true, "c": 0, "d":"", "e": "abc", "f": 0, "g": 0, "h": 0}' 17 1
  chip-tool unittesting write struct-attr '{"a": 1, "b": true, "c": 0, "d":"hex:", "e": "abc", "f": 0, "g": 0, "h": 0}' 17 1
  chip-tool unittesting write octet-string "hex:" 17 1
  chip-tool unittesting write-by-id 0 "hex:" 17 1

and with this fix they parse and send correct payloads.

Fixes https://github.com/project-chip/connectedhomeip/issues/24054

### CODE REVIEW

**Review by jmeg-sfy — APPROVED** [review]

File: examples/chip-tool/commands/clusters/ComplexArgument.h [hunk 1]
```diff
@@ -210,18 +211,21 @@ class ComplexArgumentParser
...
 
-            if (size % 2 != 0)
+            CHIP_ERROR err = HexToBytes(
+                chip::CharSpan(str.c_str(), size),
+                [&buffer](size_t allocSize) {
+                    buffer = static_cast<uint8_t *>(chip::Platform::MemoryCalloc(allocSize, sizeof(uint8_t)));
+                    return buffer;
+                },
+                &size);
+            if (err != CHIP_NO_ERROR)
```
Comment (jmeg-sfy) [inline examples/chip-tool/commands/clusters/ComplexArgument.h:221]:
```suggestion
                &size);
       
            if (err != CHIP_NO_ERROR)
```

**Review by tehampson — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

File: examples/chip-tool/commands/common/HexConversion.h [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+    if (hex.size() % 2 != 0)
+    {
+        ChipLogError(chipTool, "Error while encoding '%.*s' as an octet string: Odd number of characters.",
+                     static_cast<int>(hex.size()), hex.data());
+        return CHIP_ERROR_INVALID_STRING_LENGTH;
+    }
+
+    const size_t bufferSize = hex.size() / 2;
+    uint8_t * buffer        = bufferAllocator(bufferSize);
+    if (buffer == nullptr)
```
Comment (arkq) [inline examples/chip-tool/commands/common/HexConversion.h:50]: When using POSIX `malloc()`/`calloc()` function with 0 length we might get NULL instead of zero-length memory chunk (`chip::Platform::MemoryCalloc` uses POSIX `calloc()`). So, passing zero-length span might fail here, where in fact no buffer is needed, because no decoding will take place. Also, why bufferAllocator functor? Isn't it easier to pass preallocated buffer here? The ratio between bytes and hex-string is always 1:2, so buffer can be preallocated beforehand.

Comment (bzbarsky-apple) [reply examples/chip-tool/commands/common/HexConversion.h:50]: Good catch on malloc(0) being allowed to return null.  Will fix.

> Isn't it easier to pass preallocated buffer here?

That requires all callsites to duplicate the length-check and error-handling for incorrect length.

Comment (bzbarsky-apple) [reply examples/chip-tool/commands/common/HexConversion.h]: https://github.com/project-chip/connectedhomeip/pull/24097/commits/90aa96f5c918ed8b2adc8d8bce0ff96958021b47 should fix the `malloc(0)`/`calloc(0)` bits.

**Review by msandstedt — APPROVED** [review]
