### PR TITLE
[Android] Add Service Type Protocol setting in dnssd

### LINKED ISSUE #23605: [BUG] Android DNS-SD service type is wrong when discover commissionable nodes
### Reproduction steps

```bash
1.Open ChipTool app on Samsung S9.
2.Click "PROVISION CHIP DEVICE WITH WIFI".
3.CLICK "INPUT DEVICE ADDRESS".
4.CLICK "DISCOVER".
```

### Bug prevalence

It happend every time on my Samsung S9. But the other's phone works will.

### GitHub hash of the SDK that was being used

87bee4de25886ba00f1a177cd0f8791a48528a1f

### Platform

android

### Platform Version(s)

Samsung S9, Android 10.

### Anything else?

When I click "DISCOVER" button, it will call `deviceController.discoverCommissionableNodes() `method. The logs show the discovered service type is "_matterc._udp". But when resolve service, the service type changed to be "_matterc._tcp". I think may be it a mistake.
```
17:43:06.159 NsdManager...iceBrowser  I  Started service '_matterc._udp'
17:43:06.161 NsdManager...iceBrowser  I  Found service '3982D7E59084DCC3'
17:43:11.172 NsdManager...ceResolver  D  resolve: Starting service resolution for '3982D7E59084DCC3' type '_matterc._tcp'
17:43:11.176 NsdManager...iceBrowser  W  Succeed to stop discovery service '_matterc._udp
17:43:41.206 NsdManager...ceResolver  D  resolve: Timing out
```

### PR DESCRIPTION
**Pull request by joonhaengHeo**
Fixes #23605.

Added Service Type Protocol setting in DNSSD because it was missing in Android Platform.
 -> Add Service Type and Protocol setting.

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

File: src/platform/android/DnssdImpl.cpp [hunk 1]
```diff
@@ -316,7 +316,18 @@ void HandleResolve(jstring instanceName, jstring serviceType, jstring hostName,
     DnssdService service = {};
     CopyString(service.mName, jniInstanceName.c_str());
     CopyString(service.mHostName, jnihostName.c_str());
-    CopyString(service.mType, jniServiceType.c_str());
+
+    std::string serviceTypeStr(jniServiceType.c_str());
+
+    size_t index = serviceTypeStr.find(".");
```
Comment (andy31415) [inline src/platform/android/DnssdImpl.cpp:322]: This code seems to be present in 2 separate places and looks identical. Lets place it in a stand alone function, like `CHIP_ERROR extractProtocol(const char *serviceType, DnssdServiceProtocol &out_protocol)`.

Comment (joonhaengHeo) [reply src/platform/android/DnssdImpl.cpp]: Thanks for your review my code. I modify to add function on your comment.

File: src/platform/android/DnssdImpl.cpp [hunk 2]
```diff
@@ -183,6 +183,20 @@ CHIP_ERROR ChipDnssdStopBrowse(intptr_t browseIdentifier)
...
 }
 
+CHIP_ERROR extractProtocol(const char * serviceType, char * outServiceName, DnssdServiceProtocol & outProtocol)
+{
+    std::string serviceTypeStr(serviceType);
+    size_t index = serviceTypeStr.find(".");
+
+    ReturnErrorCodeIf(index == std::string::npos, CHIP_ERROR_INVALID_ARGUMENT);
+
+    CopyString(outServiceName, index + 1, serviceType);
```
Comment (andy31415) [inline src/platform/android/DnssdImpl.cpp:193]: outServiceName needs to be sized - either use a span or add a length argument to ensure we do not overflow.

You should not pass index+1 here but rather `outServiceNameLength`

File: src/platform/android/DnssdImpl.cpp [hunk 3]
```diff
@@ -183,6 +183,20 @@ CHIP_ERROR ChipDnssdStopBrowse(intptr_t browseIdentifier)
...
+    outProtocol = (serviceTypeStr.substr(index + 1).compare(kOperationalProtocol) == 0) ? DnssdServiceProtocol::kDnssdProtocolTcp
+                                                                                        : DnssdServiceProtocol::kDnssdProtocolUdp;
```
Comment (tcarmelveilleux) [inline src/platform/android/DnssdImpl.cpp:195]: Why is there a desire to extract teh TCP versus UDP?

_matter._tcp is a for protocol than can run over UDP, and in the future, also TCP. Same for _matterc._udp. The `._udp`/`._tcp` are not fundamental. Therefor is there a reason why mProtocol is used/added?

The API allows it, but what is the end-usage of it? In other words, why this cahnge now? If it steers to TCP/UDP usage elsewhere, there will be different problems.

Comment (joonhaengHeo) [reply src/platform/android/DnssdImpl.cpp:195]: This code shows '.' The purpose is to change the following "_tcp" String to DnssdServiceProtocol::kDnssdProtocolTcp, and to replace the "_udp" String to DnssdServiceProtocol::kDnssdProtocolUdp.

Example : 
1. If "_matter._tcp" value is entered in Java Layer, "_matter" is stored in mType variable and DnssdServiceProtocol::kDnssdProtocolTcp value is stored in mProtocol variable.
2. If "_matterc._udp" value is entered in Java Layer, "_matterc" is stored in mType variable and DnssdServiceProtocol::kDnssdProtocolUdp value is stored in mProtocol variable.

kOperationalProtocol has "_tcp" value stored.

Please check if the part you gave us your opinion is about the possibility that other values other than "_tcp" and "_udp" will be delivered.

File: src/platform/android/DnssdImpl.cpp (hunk 2 above)
Comment (joonhaengHeo) [reply src/platform/android/DnssdImpl.cpp]: Thanks your kindly reviewing. I added.

File: src/platform/android/DnssdImpl.cpp (hunk 3 above)
Comment (tcarmelveilleux) [reply src/platform/android/DnssdImpl.cpp:200]: The question is about "why is this needed now". I am trying to understand if the fact that this feature was not implemented broke anything, because it should not have broken anything.

File: src/platform/android/DnssdImpl.cpp [hunk 4]
```diff
@@ -183,6 +183,25 @@ CHIP_ERROR ChipDnssdStopBrowse(intptr_t browseIdentifier)
...
+template <size_t N>
+CHIP_ERROR extractProtocol(const char * serviceType, char (&outServiceName)[N], DnssdServiceProtocol & outProtocol)
+{
+    std::string serviceTypeStr(serviceType);
+    size_t index = serviceTypeStr.find(".");
+
+    ReturnErrorCodeIf(index == std::string::npos, CHIP_ERROR_INVALID_ARGUMENT);
+    ReturnErrorCodeIf(index + 1 > N, CHIP_ERROR_INVALID_ARGUMENT);
+
+    memcpy(outServiceName, serviceType, index);
```
Comment (andy31415) [inline src/platform/android/DnssdImpl.cpp:195]: why do we need to return the string actually?

if we return DnssdServiceProtocol it is trivial to have:

```cpp
const char *ProtocolString(DnssdServiceProtocol p) {
  if (p == DnssdServiceProtocol::kDnssdProtocolTcp) {
     return "_tcp";
  }
  VerifyOrDie(p == DnssdServiceProtocol::kDnssdProtocolUdp);
  return "_udp";
}
```

we seem to otherwise return the same thing in two separate ways, making more complex methods.


Also agree with the point below from @tcarmelveilleux : why does code care about protocol? I thought DNSSD strings are just opaque for our purposes for this browsing prupose.

File: src/platform/android/DnssdImpl.cpp (hunk 3 above)
Comment (joonhaengHeo) [reply src/platform/android/DnssdImpl.cpp:200]: I'm sorry. I didn't understand you correctly.

I'm going to give you my opinion on that

1. For Linux chip-tool, a similar code has already been added below.
https://github.com/project-chip/connectedhomeip/blob/733afaabd512cbf396d3edf09805d1054a6ec5f8/src/platform/Linux/DnssdImpl.cpp#L631

2. I don't know the exact reproduction path, but in order to clarify this part, I changed the code to the following location and tested it to see if it worked. (Initial value specified in Tcp)
https://github.com/project-chip/connectedhomeip/blob/733afaabd512cbf396d3edf09805d1054a6ec5f8/src/lib/dnssd/platform/Dnssd.h#L69

-> DnssdServiceProtocol mProtocol = DnssdServiceProtocol::DnssdServiceProtocol::kDnssdProtocolTcp;

Judging from this, it can be seen that there is a possibility of an issue, not just reproduced. I think it will be initialized to zero due to the code below, but I think this code should be added because there is a history of issues.

https://github.com/project-chip/connectedhomeip/blob/733afaabd512cbf396d3edf09805d1054a6ec5f8/src/platform/android/DnssdImpl.cpp#L316

Therefore, I think you should set the mProtocol variable to clarify this part.

File: src/platform/android/DnssdImpl.cpp (hunk 4 above)
Comment (joonhaengHeo) [reply src/platform/android/DnssdImpl.cpp:195]: 1. I modified the code by referring to your additional comment and the Linux platform code below. Please check.
https://github.com/project-chip/connectedhomeip/blob/733afaabd512cbf396d3edf09805d1054a6ec5f8/src/platform/Linux/DnssdImpl.cpp#L569

2. As I explained above, the value is not set only for Android Platform. Therefore, I think there is a problem with not knowing which value will be set.

**Review by andy31415 — APPROVED** [review]
