### PR TITLE
Fix subscription liveness check

### LINKED ISSUE #11565: For IM report, don't spam more frequently than min interval, but if min interval passed send immediately
#### Problem
From spec, Each Report transaction SHALL NOT be initiated by the publisher until the minimum interval has expired since the last Report transaction in the subscription.

Attribute changes SHALL be delivered as soon as possible, taking into account the minimum interval.

Current server code send report every min interval, need to do the below way, 
 don't spam more frequently than min interval, but if min interval passed send immediately

### PR DESCRIPTION
**Pull request by yunhanw-google**
#### Problem
What is being fixed?  Examples:
-- Send sync report with max interval, after min interval passed, send report immediately if there is any attribute change.
-- Add additional margin for MRP upon max interval when doing liveness check
-- Fix bug:Report Engine would set handler dirty only when its subscribed path interested with dirty path, and fix UpdateReadHandlerDirty's dirty cleanup.
-- Call ScheduleRun() here since we may have accumulated dirty items in the global dirty set that need to get flushed now that the hold off(min interval has passed) has elapsed where handler has been set dirty.
--When the max-interval has elapsed, to definitely send out a report even if there is no actual data to be sent.

#### Change overview
See above

#### Testing
Existing test cover for happy path, manual test for negative cases, for manual test, I use im mock initiator and im mock responder which can communicate over crmp, and after subscription is estabalished, I tear down responder, then check the print out in initiator and see if the actual timeout call can be triggered after max(5s) + margin(19seconds)

### CODE REVIEW

File: src/app/ReadClient.cpp [hunk 1]
```diff
@@ -520,6 +520,15 @@ CHIP_ERROR ReadClient::ProcessAttributeReportIBs(TLV::TLVReader & aAttributeRepo
 CHIP_ERROR ReadClient::RefreshLivenessCheckTimer()
 {
     CancelLivenessCheckTimer();
+    uint64_t timeoutMsec = mMaxIntervalCeilingSeconds;
+    uint64_t marginSec   = 0;
+    if (mpExchangeCtx != nullptr && mpExchangeCtx->IsUDPTransport())
+    {
+        marginSec = (CHIP_CONFIG_RMP_DEFAULT_MAX_RETRANS + 1) * mpExchangeCtx->GetIdleRetransmitTimeoutTick();
```
Comment (msandstedt) [inline src/app/ReadClient.cpp:527]: TCP isn't instant though.  RTO * retries can be hundreds of seconds if a link exhibits a high round-trip time.  Even a single lost packet could lead to a breakage for TCP here, whereas this code might accommodate such a thing for UDP.

I don't see that it makes sense to branch like this PR attempts to.  In this context, the only thing that is special about UDP+MRP as compared to TCP is that we have immediate access to retry parameters with MRP, whereas these are likely obfuscated for TCP.  But they still absolutely exist.

File: src/app/ReadHandler.cpp [hunk 2]
```diff
@@ -579,21 +579,35 @@ CHIP_ERROR ReadHandler::ProcessSubscribeRequest(System::PacketBufferHandle && aP
...
         OnRefreshSubscribeTimerSyncCallback, this);
     mHoldReport = true;
-    return InteractionModelEngine::GetInstance()->GetExchangeManager()->GetSessionManager()->SystemLayer()->StartTimer(
-        System::Clock::Seconds16(mMinIntervalFloorSeconds), OnRefreshSubscribeTimerSyncCallback, this);
+    ReturnErrorOnFailure(
+        InteractionModelEngine::GetInstance()->GetExchangeManager()->GetSessionManager()->SystemLayer()->StartTimer(
+            System::Clock::Seconds16(mMinIntervalFloorSeconds), OnUnblockHoldReportCallback, this));
+    ReturnErrorOnFailure(
+        InteractionModelEngine::GetInstance()->GetExchangeManager()->GetSessionManager()->SystemLayer()->StartTimer(
+            System::Clock::Seconds16(mMaxIntervalCeilingSeconds), OnRefreshSubscribeTimerSyncCallback, this));
```
Comment (bzbarsky-apple) [inline src/app/ReadHandler.cpp:609]: So this is going to wait for max-interval before sending heartbeat?  That seems like it would _very_ easily manage to miss its time window from the other side's point of view and lose the subscription....

File: src/app/ReadClient.cpp [hunk 3]
```diff
@@ -520,6 +520,15 @@ CHIP_ERROR ReadClient::ProcessAttributeReportIBs(TLV::TLVReader & aAttributeRepo
 CHIP_ERROR ReadClient::RefreshLivenessCheckTimer()
 {
     CancelLivenessCheckTimer();
+    uint64_t timeoutMsec = mMaxIntervalCeilingSeconds;
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.cpp:523]: Quite apart from how this is or should be computed ... this variable is not used for anything, right?  How was this tested?

Also, there is some interesting unit confusion going on here with seconds vs msec?

File: src/app/ReadClient.cpp [hunk 4]
```diff
@@ -520,6 +520,15 @@ CHIP_ERROR ReadClient::ProcessAttributeReportIBs(TLV::TLVReader & aAttributeRepo
...
+    uint64_t marginSec   = 0;
+    if (mpExchangeCtx != nullptr && mpExchangeCtx->IsUDPTransport())
+    {
+        marginSec = (CHIP_CONFIG_RMP_DEFAULT_MAX_RETRANS + 1) * mpExchangeCtx->GetIdleRetransmitTimeoutTick();
+    }
+
+    timeoutMsec = timeoutMsec + marginSec * 1000 /* MILLISECOND_PER_SECOND 1000*/;
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.cpp:530]: I suspect using the System::Clock types here would avoid the need for magic constants and get us stronger typing and mixup-avoidance in the process.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/ReadHandler.cpp [hunk 5]
```diff
@@ -579,21 +579,35 @@ CHIP_ERROR ReadHandler::ProcessSubscribeRequest(System::PacketBufferHandle && aP
     return CHIP_NO_ERROR;
 }
 
+void ReadHandler::OnUnblockHoldReportCallback(System::Layer * apSystemLayer, void * apAppState)
+{
+    VerifyOrReturn(apAppState != nullptr);
+    ReadHandler * readHandler = static_cast<ReadHandler *>(apAppState);
+    ChipLogProgress(DataManagement, "Unblock report hold after min %d seconds", readHandler->mMinIntervalFloorSeconds);
+    readHandler->mHoldReport = false;
```
Comment (mrjerryjohns) [inline src/app/ReadHandler.cpp:587]: We do need to call ScheduleRun() here since we may have accumulated dirty items in the global dirty set that need to get flushed now that the hold off has elapsed.

Comment (mrjerryjohns) [reply src/app/ReadHandler.cpp:587]: We need a distinction between:
1. When the min-interval has elapsed, to _only_ send out a report if there is actual data to be sent (modulo other criteria that may need to be satisfied, e.g batching parameters for events)
2. When the max-interval has elapsed, to _definitely_ send out a report _even if_ there is no actual data to be sent.

This distinction I don't think is present today.

File: src/app/ReadHandler.cpp [hunk 6]
```diff
@@ -579,21 +579,35 @@ CHIP_ERROR ReadHandler::ProcessSubscribeRequest(System::PacketBufferHandle && aP
...
+    ChipLogProgress(DataManagement, "ReadHandler::Refresh Subscribe Sync Timer with %d seconds", mMaxIntervalCeilingSeconds);
+    InteractionModelEngine::GetInstance()->GetExchangeManager()->GetSessionManager()->SystemLayer()->CancelTimer(
+        OnUnblockHoldReportCallback, this);
     InteractionModelEngine::GetInstance()->GetExchangeManager()->GetSessionManager()->SystemLayer()->CancelTimer(
         OnRefreshSubscribeTimerSyncCallback, this);
     mHoldReport = true;
-    return InteractionModelEngine::GetInstance()->GetExchangeManager()->GetSessionManager()->SystemLayer()->StartTimer(
-        System::Clock::Seconds16(mMinIntervalFloorSeconds), OnRefreshSubscribeTimerSyncCallback, this);
+    ReturnErrorOnFailure(
+        InteractionModelEngine::GetInstance()->GetExchangeManager()->GetSessionManager()->SystemLayer()->StartTimer(
```
Comment (mrjerryjohns) [inline src/app/ReadHandler.cpp:605]: Since this requires 2 timers per subscription and is impacted by the availability of timers in the system, on LWIP platforms, we should add some checks that `CHIP_SYSTEM_CONFIG_NUM_TIMERS` is at least sized to cover the minimum number of subscriptions * 2.

Side-note: Can we actually reduce the utilization down to 1? We can schedule the timer in two phases - one for min, and then 1 for remaining duration till max.

**Review by mrjerryjohns — CHANGES_REQUESTED** [review]

File: src/app/ReadHandler.cpp (hunk 5 above)
Comment (yunhanw-google) [reply src/app/ReadHandler.cpp:598]: Just updated this. thanks

File: src/app/ReadClient.cpp [hunk 7]
```diff
@@ -520,6 +520,15 @@ CHIP_ERROR ReadClient::ProcessAttributeReportIBs(TLV::TLVReader & aAttributeRepo
...
+
     ChipLogProgress(DataManagement, "Refresh LivenessCheckTime with %d seconds", mMaxIntervalCeilingSeconds);
     CHIP_ERROR err = InteractionModelEngine::GetInstance()->GetExchangeManager()->GetSessionManager()->SystemLayer()->StartTimer(
         System::Clock::Seconds16(mMaxIntervalCeilingSeconds), OnLivenessTimeoutCallback, this);
```
[the remark this answers is not in the document]
Comment (yunhanw-google) [reply src/app/ReadClient.cpp]: yep, thanks for catching this up, fixed.

File: src/app/ReadHandler.cpp (hunk 6 above)
Comment (yunhanw-google) [reply src/app/ReadHandler.cpp:620]: yes, true

Comment (yunhanw-google) [reply src/app/ReadHandler.cpp:620]: updated to schedule timer in two phases. thanks

File: src/app/ReadClient.cpp (hunk 4 above)
Comment (yunhanw-google) [reply src/app/ReadClient.cpp]: Done, thanks

File: src/app/ReadClient.cpp (hunk 3 above)
Comment (yunhanw-google) [reply src/app/ReadClient.cpp]: improved it by System::Clock , thanks

File: src/app/ReadHandler.cpp (hunk 2 above)
Comment (yunhanw-google) [reply src/app/ReadHandler.cpp]: should we add some margin value for BLE as well when run IM over BLE

Comment (bzbarsky-apple) [reply src/app/ReadHandler.cpp]: @mrjerryjohns This expectation should be spelled out in the spec, no?

Comment (bzbarsky-apple) [reply src/app/ReadHandler.cpp]: @yunhanw-google Over BLE, subscriptions should never happen, I would think.  So I would not worry about BLE.

(In fact, it might be a good idea to have the spec be clear about subscriptions not happening over BLE...)

File: src/app/ReadClient.cpp [hunk 8]
```diff
@@ -541,9 +541,18 @@ CHIP_ERROR ReadClient::ProcessEventReportIBs(TLV::TLVReader & aEventReportIBsRea
 CHIP_ERROR ReadClient::RefreshLivenessCheckTimer()
 {
     CancelLivenessCheckTimer();
+    System::Clock::Timeout timeout =
+        std::chrono::duration_cast<std::chrono::milliseconds>(System::Clock::Seconds16(mMaxIntervalCeilingSeconds));
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.cpp:545]:
```suggestion
    System::Clock::Timeout timeout = System::Clock::Seconds16(mMaxIntervalCeilingSeconds);
```
You need to cast explicitly if losing precision, but this is not losing precision.  The types involved know how to convert the thing on the right (known to be in seconds) to the thing on the left (known to be in milliseconds).

File: src/app/ReadClient.cpp [hunk 9]
```diff
@@ -541,9 +541,18 @@ CHIP_ERROR ReadClient::ProcessEventReportIBs(TLV::TLVReader & aEventReportIBsRea
...
+    if (mpExchangeCtx != nullptr && mpExchangeCtx->IsUDPTransport())
+    {
+        System::Clock::Timeout margin = System::Clock::Milliseconds32((CHIP_CONFIG_RMP_DEFAULT_MAX_RETRANS + 1) *
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.cpp:548]:
```suggestion
        auto margin = System::Clock::Milliseconds32((CHIP_CONFIG_RMP_DEFAULT_MAX_RETRANS + 1) *
```
since it's not really a Timeout, right?  It's really a Milliseconds32.

File: src/app/ReadClient.cpp [hunk 10]
```diff
@@ -541,9 +541,18 @@ CHIP_ERROR ReadClient::ProcessEventReportIBs(TLV::TLVReader & aEventReportIBsRea
...
+                                                                      mpExchangeCtx->GetIdleRetransmitTimeoutTick());
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.cpp:549]: `mpExchangeCtx->GetIdleRetransmitTimeoutTick()` does not return a number of milliseconds.  It returns a number of ticks.  Ticks are not one millisecond.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/reporting/Engine.cpp [hunk 11]
```diff
@@ -439,7 +439,15 @@ CHIP_ERROR Engine::SetDirty(ClusterInfo & aClusterInfo)
         // chunk for read interactions.
         if (handler.IsGeneratingReports() || handler.IsAwaitingReportResponse())
         {
-            handler.SetDirty();
+            for (auto clusterInfo = handler.GetAttributeClusterInfolist(); clusterInfo != nullptr;
+                 clusterInfo      = clusterInfo->mpNext)
+            {
+                if (aClusterInfo.IsAttributePathSupersetOf(*clusterInfo) || clusterInfo->IsAttributePathSupersetOf(aClusterInfo))
```
Comment (erjiaqing) [inline src/app/reporting/Engine.cpp:445]: What if we 
Subscribe Wildcard Endpoint, Cluster X

And SetDirty with
Endpoint Y, Wildcard Cluster

This may happen when a new dynamic endpoint was added to the server

File: src/app/ReadHandler.cpp (hunk 2 above)
Comment (yunhanw-google) [reply src/app/ReadHandler.cpp]: yes, agree, thanks

Comment (yunhanw-google) [reply src/app/ReadHandler.cpp]: https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/4689

File: src/app/reporting/Engine.cpp (hunk 11 above)
Comment (yunhanw-google) [reply src/app/reporting/Engine.cpp:445]: yep, need extend supersetof function to overlapped for clusterInfoA and clusterInfoB, and need to get the overlapped part, and send report with overlapped part, perhaps in

Comment (yunhanw-google) [reply src/app/reporting/Engine.cpp:445]: https://github.com/project-chip/connectedhomeip/issues/11960

File: src/app/ReadClient.cpp (hunk 10 above)
Comment (yunhanw-google) [reply src/app/ReadClient.cpp:548]: yep, looks like mpExchangeCtx->GetIdleRetransmitTimeoutTick() >> CHIP_CONFIG_RMP_TIMER_DEFAULT_PERIOD_SHIFT which can return a number of msec

File: src/app/ReadClient.cpp [hunk 12]
```diff
@@ -541,9 +541,18 @@ CHIP_ERROR ReadClient::ProcessEventReportIBs(TLV::TLVReader & aEventReportIBsRea
 CHIP_ERROR ReadClient::RefreshLivenessCheckTimer()
 {
     CancelLivenessCheckTimer();
+    System::Clock::Timeout timeout = System::Clock::Seconds16(mMaxIntervalCeilingSeconds);
+    if (mpExchangeCtx != nullptr && mpExchangeCtx->IsUDPTransport())
+    {
+        auto margin = System::Clock::Milliseconds32(
+            (CHIP_CONFIG_RMP_DEFAULT_MAX_RETRANS + 1) *
+            (mpExchangeCtx->GetIdleRetransmitTimeoutTick() >> CHIP_CONFIG_RMP_TIMER_DEFAULT_PERIOD_SHIFT));
```
Comment (bzbarsky-apple) [inline src/app/ReadClient.cpp:549]: This does not look right.  Was this tested?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/ReadClient.cpp (hunk 1 above)
Comment (yunhanw-google) [reply src/app/ReadClient.cpp]: https://github.com/project-chip/connectedhomeip/issues/12009, I also don't have good idea to get quick calculation for tcp margin, just create the ticket for follow-up. Temporarily I would use the 30s for margin for tcp

Comment (msandstedt) [reply src/app/ReadClient.cpp]: @mrjerryjohns , 

The simplest thing would be to decouple from the exact nature of the underlying transport's reliability features.  We could instead say: transport attempts to be reliable.  Therefore, we should allow 1 strike before assuming the subscription is dead.  So given mMaxIntervalCeilingSeconds, fail at 2x mMaxIntervalCeilingSeconds.

As an aside, this PR's computation for maximum idle-state MRP timeout is not spec compliant.

**Review by msandstedt — APPROVED** [review]

File: src/app/ReadClient.cpp [hunk 13]
```diff
@@ -540,10 +540,27 @@ CHIP_ERROR ReadClient::ProcessEventReportIBs(TLV::TLVReader & aEventReportIBsRea
...
-    ChipLogProgress(DataManagement, "Refresh LivenessCheckTime with %d seconds", mMaxIntervalCeilingSeconds);
-    CHIP_ERROR err = InteractionModelEngine::GetInstance()->GetExchangeManager()->GetSessionManager()->SystemLayer()->StartTimer(
-        System::Clock::Seconds16(mMaxIntervalCeilingSeconds), OnLivenessTimeoutCallback, this);
+    VerifyOrReturnError(mpExchangeCtx != nullptr, err = CHIP_ERROR_INCORRECT_STATE);
+    System::Clock::Timeout timeout = System::Clock::Seconds16(mMaxIntervalCeilingSeconds);
+    if (mpExchangeCtx->IsUDPTransport())
+    {
+        auto margin = System::Clock::Milliseconds32(
+            (CHIP_CONFIG_RMP_DEFAULT_MAX_RETRANS + 1) *
+            (mpExchangeCtx->GetIdleRetransmitTimeoutTick() << CHIP_CONFIG_RMP_TIMER_DEFAULT_PERIOD_SHIFT));
```
Comment (mrjerryjohns) [inline src/app/ReadClient.cpp:551]: This logic should not be happening here at this layer - instead, we should be exposing a function on the exchange context that returns some/all of this information:

```
System::Clock::Milliseconds32 ExchangeContext::GetAckTimeout()
```

or something like that (@bzbarsky-apple might have better suggestions here).

File: src/app/ReadHandler.cpp (hunk 5 above)
Comment (mrjerryjohns) [reply src/app/ReadHandler.cpp:598]: I'm still not quite getting how the logic changes you've done achieve the distinction between the two cases I've outlined above. Can you please explain?

File: src/app/ReadClient.cpp (hunk 13 above)
Comment (mrjerryjohns) [inline src/app/ReadClient.cpp:551]: How exactly was this tested manually? Can you please describe the specific tests you did?

Comment (yunhanw-google) [reply src/app/ReadClient.cpp:551]: agree, just create ExchangeContext::GetAckTimeout, thanks

Comment (yunhanw-google) [reply src/app/ReadClient.cpp:551]: I use im mock initiator and im mock responder, and after subscription is estabalished, I tear down responder, then check the print out in initiator and see if the actual timeout call can be triggered after max(5s) + margin(19seconds)

Comment (yunhanw-google) [reply src/app/ReadClient.cpp:551]: [1637379765276] [44720:9993776] CHIP: [EM] Handling via exchange: 21819r, Delegate: 0x0x107376830
[1637379765276] [44720:9993776] CHIP: [DMG] ReportDataMessage =
[1637379765276] [44720:9993776] CHIP: [DMG] {
[1637379765276] [44720:9993776] CHIP: [DMG] 	SubscriptionId = 0x72bde65c628c1f48,
[1637379765276] [44720:9993776] CHIP: [DMG] }
[1637379765276] [44720:9993776] CHIP: [DMG] **Refresh LivenessCheckTime with 24968 milliseconds**
[1637379765276] [44720:9993776] CHIP: [EM] Piggybacking Ack for MessageCounter:18 on exchange: 21819r
[1637379765276] [44720:9993776] CHIP: [IN] Prepared encrypted message 0x107375658 to 0x0000000000BC5C01 of type 0x1 and protocolId (0, 1) on exchange 21819r with MessageCounter:25.
[1637379765276] [44720:9993776] CHIP: [IN] Sending encrypted msg 0x107375658 with MessageCounter:25 to 0x0000000000BC5C01 at monotonic time: 977658146 msec
[1637379765277] [44720:9993775] CHIP: [EM] Received message of type 0x10 with protocolId (0, 0) and MessageCounter:19 on exchange 21819r
[1637379765277] [44720:9993775] CHIP: [EM] Rxd Ack; Removing MessageCounter:25 from Retrans Table on exchange 21819r
[1637379765277] [44720:9993775] CHIP: [EM] Removed CHIP MessageCounter:25 from RetransTable on exchange 21819r
[1637379790244] [44720:9993776] CHIP: [DMG] Subscription Liveness timeout with peer node 0xbc5c01, shutting down 
ReadError with err ../../src/app/ReadClient.cpp:580: CHIP Error 0x00000032: Timeout[1637379790245] [44720:9993776] CHIP: [DMG] Client[0] moving to [UNINIT]

File: src/messaging/ExchangeContext.h [hunk 14]
```diff
@@ -166,6 +166,12 @@ class DLL_EXPORT ExchangeContext : public ReliableMessageContext, public Referen
 
     void SetResponseTimeout(Timeout timeout);
 
+    System::Clock::Milliseconds32 GetAckTimeout();
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeContext.h:169]: Please document that this is the amount of time we expect to pass before the exchange gives up waiting for an ack and times out.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/ReadHandler.cpp (hunk 5 above)
Comment (yunhanw-google) [reply src/app/ReadHandler.cpp:598]: in OnUnblockHoldReportCallback which is triggered when min-interval is elapsed, I check if current read handler is dirty, then decide if engine send the report out. in OnRefreshSubscribeTimerSyncCallback which is triggerred when max interval is elapsed, report engine would run.
i have updated the setDirty in engine.cpp which would mark read handler as dirty when there is intersected value between subscribed path and marked dirty-path

Comment (mrjerryjohns) [reply src/app/ReadHandler.cpp:598]: > OnRefreshSubscribeTimerSyncCallback which is triggerred when max interval is elapsed, report engine would run

How do you ensure that even if there is no dirtiness, that an empty report will be sent at the max interval?

**Review by jmeg-sfy — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by mrjerryjohns — APPROVED** [review]

File: src/messaging/ExchangeContext.h (hunk 14 above)
Comment (yunhanw-google) [reply src/messaging/ExchangeContext.h:172]: Done, thanks

File: src/app/ReadClient.cpp (hunk 1 above)
Comment (yunhanw-google) [reply src/app/ReadClient.cpp]: move the discussion to 12009 for the follow-up
