### PR TITLE
[example] Fix CommandList for GeneralCommissioning cluster on all-clusters-app

### LINKED ISSUE #17547: [SQA] Thread-Missing command in Generated-command-list for (TC-GC-1.1)
**Problem:**
In (TC-GC-1.1) GeneratedCommandList - 3 (SetRegulatoryConfigResponse) is missing, But it is found in AcceptedCommandList .

So the command **3** (SetRegulatoryConfigResponse) should be removed from the AcceptedCommandList and add that in the GeneratedCommandList.

**Platform:** Thread

**CommitID** used: https://github.com/project-chip/connectedhomeip/commit/20e1a4a705770d5222a8ebf04e12ab2ce0304df6

**For AcceptedCommandList:**

**Expected behavior:** AcceptedCommandList: 3 entries
[1650453685.373070][5559:5564] CHIP:TOO:     [1]: 0
[1650453685.373135][5559:5564] CHIP:TOO:     [2]: 2
[1650453685.373257][5559:5564] CHIP:TOO:     [4]: 4

**Actual behavior:** AcceptedCommandList: 4 entries
[1650453685.373070][5559:5564] CHIP:TOO:     [1]: 0
[1650453685.373135][5559:5564] CHIP:TOO:     [2]: 2
[1650453685.373197][5559:5564] CHIP:TOO:     [3]: 3
[1650453685.373257][5559:5564] CHIP:TOO:     [4]: 4

**Steps to reproduce:**  `./chip-tool generalcommissioning read accepted-command-list 82 0`

**For GeneratedCommandList :**

**Expected behavior:** GeneratedCommandList: 3 entries
[1650453690.789862][5566:5571] CHIP:TOO:     [1]: 1
[1650453685.373197][5559:5564] CHIP:TOO:     [3]: 3
[1650453690.789926][5566:5571] CHIP:TOO:     [2]: 5

**Actual behavior:** GeneratedCommandList: 2 entries
[1650453690.789862][5566:5571] CHIP:TOO:     [1]: 1
[1650453690.789926][5566:5571] CHIP:TOO:     [2]: 5

**Steps to reproduce:** `./chip-tool generalcommissioning read generated-command-list 82 0`

**Reference:** [Spec](https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/GeneralCommissioningCluster.adoc), [Test-plan](https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/General_Commissioning.adoc).

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem
Fixes #17547 Thread-Missing command in Generated-command-list for

#### Change overview

Per spec

**7.13.3.1. AcceptedCommandList**

...

For each client request command in this list that mandates a response from the server, the response command SHALL be in the GeneratedCommandList.

**7.13.3.2. GeneratedCommandList**

...

For each command in this list that is a response to a client command request, the request command SHALL be in the AcceptedCommandList.

So instead of using "incoming_client", "outgoing_server" masks, this PR directly uses the set of response commands from  of the commands with "incoming_server" mask.

Also, this PR adds an "index" to the list header to help verify the generated code manually `(index=x)` shoud match `ZAP_GENERATED_COMMANDS_INDEX( 48 )`

This PR depends on https://github.com/project-chip/zap/pull/480, DO NOT MERGE BEFORE IT.

#### Testing

```
In [4]: await devCtrl.ReadAttribute(nodeid=111111, attributes=[(0, Clusters.GeneralCommissioning)])
{
│   0: {
│   │   <class 'chip.clusters.Objects.GeneralCommissioning'>: {
...
│   │   │   <class 'chip.clusters.Objects.GeneralCommissioning.Attributes.GeneratedCommandList'>: [
│   │   │   │   1,
│   │   │   │   3,
│   │   │   │   5
│   │   │   ],
│   │   │   <class 'chip.clusters.Objects.GeneralCommissioning.Attributes.AcceptedCommandList'>: [
│   │   │   │   0,
│   │   │   │   2,
│   │   │   │   4
│   │   │   ],
...
│   │   }
│   }
}
```

### CODE REVIEW

File: src/app/zap-templates/templates/app/helper.js [hunk 1]
```diff
@@ -195,29 +195,40 @@ function chip_endpoint_generated_functions()
 function chip_endpoint_generated_commands_list(options)
 {
   let ret = [];
+  let index = 0;
```
Comment (erjiaqing) [inline src/app/zap-templates/templates/app/helper.js:198]: Note: This PR depends on https://github.com/project-chip/zap/pull/480, this comment will block the PR from merging accidentally.

File: src/app/zap-templates/templates/app/helper.js [hunk 2]
```diff
@@ -194,30 +194,41 @@ function chip_endpoint_generated_functions()
...
     let generatedCommands = [];
 
     c.commands.forEach((cmd) => {
       if (cmd.mask.includes('incoming_server')) {
         acceptedCommands.push(`${cmd.commandId} /* ${cmd.name} */`);
-      }
-      if (cmd.mask.includes('incoming_client')) {
-        generatedCommands.push(`${cmd.commandId} /* ${cmd.name} */`);
+        console.log(cmd);
+        if (cmd.responseName) {
```
Comment (bzbarsky-apple) [inline src/app/zap-templates/templates/app/helper.js:207]: This seems reasonable, but what was going wrong before?  Why was `SetRegulatoryConfigResponse` running into problems, while `ArmFailSafeResponse` (which looks to be configured identically) was not?  Is it because `SetRegulatoryConfigResponse` is (incorrectly) marked optional in the XML?

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/zap-templates/templates/app/helper.js [hunk 3]
```diff
@@ -194,30 +194,41 @@ function chip_endpoint_generated_functions()
...
     let acceptedCommands  = [];
     let generatedCommands = [];
 
     c.commands.forEach((cmd) => {
       if (cmd.mask.includes('incoming_server')) {
         acceptedCommands.push(`${cmd.commandId} /* ${cmd.name} */`);
-      }
-      if (cmd.mask.includes('incoming_client')) {
-        generatedCommands.push(`${cmd.commandId} /* ${cmd.name} */`);
+        console.log(cmd);
```
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/app/zap-templates/templates/app/helper.js]: Yes, this log is added by mistake, and is removed now.

File: src/app/zap-templates/templates/app/helper.js (hunk 2 above)
Comment (erjiaqing) [reply src/app/zap-templates/templates/app/helper.js:206]: There are some issues in ZAP the zap files.

We have four flags for a command -- (incoming outgoing) x (server client)

However, in Matter, all commands from server to client are response to another from client to server (as indicated by the spec 7.13.3)

Thus some clusters in the ZAP file are mistakenly marked as "client" when they should be server, in this case, some commands have wrong flag -- both as incoming and outgoing commands.

By using the same algorithm as described in spec, we should have a more consistent result.

Comment (erjiaqing) [reply src/app/zap-templates/templates/app/helper.js:206]: Filed https://github.com/project-chip/zap/issues/481 to ZAP

File: src/app/zap-templates/templates/app/helper.js (hunk 1 above)
Comment (andy31415) [reply src/app/zap-templates/templates/app/helper.js:145]: Zap synced in #18134

**Review by jmartinez-silabs — APPROVED** [review]

**Review by tcarmelveilleux — APPROVED** [review]
