### PR TITLE
[Linux] Fix device name for Linux contact sensor

### LINKED ISSUE #25514: [Linux] Wrong device name for Linux contact sensor
### Reproduction steps

Wrong device name for Linux contact sensor published by @andy31415 in PR#25161
Check [CHIPProjectAppConfig.h](https://github.com/project-chip/connectedhomeip/commits/master/examples/contact-sensor-app/linux/include/CHIPProjectAppConfig.h) file
`#define CHIP_DEVICE_CONFIG_DEVICE_NAME "Test Bulb"`

### Platform

other

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by lboue**
Fixed #25514 (device name for Linux contact sensor published by @andy31415 in PR#25161)

### CODE REVIEW

File: examples/contact-sensor-app/linux/include/CHIPProjectAppConfig.h [hunk 1]
```diff
@@ -36,4 +36,4 @@
 
 #define CHIP_DEVICE_ENABLE_PORT_PARAMS 1
 
-#define CHIP_DEVICE_CONFIG_DEVICE_NAME "Test Bulb"
+#define CHIP_DEVICE_CONFIG_DEVICE_NAME "Contact sensor"
```
Comment (arkq) [inline examples/contact-sensor-app/linux/include/CHIPProjectAppConfig.h:39]: In other places in the code I can see device names in title case, i.e. "Contact Sensor"

**Review by arkq — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by cliffamzn — APPROVED** [review]

File: examples/contact-sensor-app/linux/include/CHIPProjectAppConfig.h (hunk 1 above)
Comment (andy31415) [reply examples/contact-sensor-app/linux/include/CHIPProjectAppConfig.h:39]: I believe this is better than before even if case does not matter. We can fix consistency separately.
