### PR TITLE
On mode overwrite

### LINKED ISSUE #16469: Implement StartUpMode and OnMode behavior for ModeSelect Cluster
#### Problem
expected behavior: When OnMode is in affect, it must override the behavior of StartUpMode, as per [spec](https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/ModeSelect.adoc#onmode-with-power-up)

actual behavior: StartUpMode is always in affect

 #### Proposed Solution
Add implementation in src/app/clusters/mode-select-server/mode-select-server.cpp

### LINKED ISSUE #16954: Every alternate execution of Toggle on endpoint2 throws an error 0x86
SHA: f7339952cb05918cb811ced511cd6ff909646425

On CHIPTool app, when trying to test On Off cluster;
On/Off/Toggle on endpoint2 throws an error 0x86 on endpoint 2

Steps to reproduce;

1. Pair M5 board with CHIPTool app
2. Select Light On/Off cluster
3. Update #of light endpoints: 2
4. On Light (endpoint 2) -> First Click on Toggle -> works fine (Toggle command success)
5. On Light (endpoint 2) -> Second Click on Toggle -> fails (An error occurred 0x86)

### PR DESCRIPTION
**Pull request by du48s03**
#### Problem
What is being fixed?  Examples:
* Fix #16469 
* Fix #16954 

#### Change overview
* Implement the logic so that when On/Off cluster's StartUpOnOff determines that the device will be set to "ON" when starting up, OnMode instead of StartUpMode will determine the CurrentMode value. 
* Add verification when OnMode will be changed.  
* Fix the bug where turning on an endpoint without ModeSelect cluster will cause an error, if at least one other endpoint contains the ModeSelectCluster. 

#### Testing
How was this tested? (at least one bullet point required)
* Unit test was added to ensure that the OnMode cannot be changed to unsupported values.

### CODE REVIEW

File: src/app/clusters/mode-select-server/mode-select-server.cpp [hunk 1]
```diff
@@ -134,6 +135,29 @@ void emberAfModeSelectClusterServerInitCallback(EndpointId endpointId)
             // Initialise currentMode to 0
             uint8_t currentMode = 0;
             status              = Attributes::CurrentMode::Get(endpointId, &currentMode);
+#ifdef EMBER_AF_PLUGIN_ON_OFF
+            // OnMode with Power Up
+            // If the On/Off feature is supported and the On/Off cluster attribute StartUpOnOff is present, with a
+            // value of On (turn on at power up), then the CurrentMode attribute SHALL be set to the OnMode attribute
+            // value when the server is supplied with power, except if the OnMode attribute is null.
+            if (emberAfContainsServer(endpointId, OnOff::Id) &&
+                emberAfContainsAttribute(endpointId, OnOff::Id, OnOff::Attributes::OnOff::Id, true) &&
```
Comment (bzbarsky-apple) [inline src/app/clusters/mode-select-server/mode-select-server.cpp:144]: Could you please file a followup to get rid of the pointless last argument of emberAfContainsAttribute?

Comment (bzbarsky-apple) [inline src/app/clusters/mode-select-server/mode-select-server.cpp:144]: Should this really be checking for the OnOff attribute?  Or StartUpOnOff?

File: src/app/clusters/mode-select-server/mode-select-server.cpp [hunk 2]
```diff
@@ -134,6 +135,29 @@ void emberAfModeSelectClusterServerInitCallback(EndpointId endpointId)
             // Initialise currentMode to 0
             uint8_t currentMode = 0;
             status              = Attributes::CurrentMode::Get(endpointId, &currentMode);
+#ifdef EMBER_AF_PLUGIN_ON_OFF
+            // OnMode with Power Up
+            // If the On/Off feature is supported and the On/Off cluster attribute StartUpOnOff is present, with a
```
Comment (bzbarsky-apple) [inline src/app/clusters/mode-select-server/mode-select-server.cpp:140]: The spec, btw, does not say anything about "StartUpOnOff" here.  It just says "and the On/Off cluster attribute is present".  Spec issue needed?

File: src/app/clusters/mode-select-server/mode-select-server.cpp [hunk 3]
```diff
@@ -211,6 +238,10 @@ InteractionModel::Status MatterModeSelectClusterServerPreAttributeChangedCallbac
  */
 static InteractionModel::Status verifyModeValue(const EndpointId endpointId, const uint8_t newMode)
 {
+    if (newMode == 0xFF) // This indicates that the new mode is null.
```
Comment (bzbarsky-apple) [inline src/app/clusters/mode-select-server/mode-select-server.cpp:241]: Please use `NumericAttributeTraits` here instead of hardcoding this.  In particular, `NumericAttributeTraits<uint8_t>::IsNullValue(newMode)`

File: src/app/tests/suites/TestModeSelectCluster.yaml [hunk 4]
```diff
@@ -112,6 +112,14 @@ tests:
       response:
           value: currentModeBeforeToggle
 
+    - label: "Change to Unsupported OnMode"
```
Comment (bzbarsky-apple) [inline src/app/tests/suites/TestModeSelectCluster.yaml:115]: This test doesn't seem to actually exercise what this PR is implementing.  Can we please exercise it?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/app/clusters/mode-select-server/mode-select-server.cpp (hunk 2 above)
Comment (du48s03) [reply src/app/clusters/mode-select-server/mode-select-server.cpp:140]: The Spec has a reference pointing "On/Off cluster attribute" to the StartUpOnOff section. This is not possible with code comment.

Comment (bzbarsky-apple) [reply src/app/clusters/mode-select-server/mode-select-server.cpp:140]: My point is the spec should explicitly say "StartUpOnOff" because there are versions of the spec where links don't work (e.g. hard-copy).

File: src/app/tests/suites/TestModeSelectCluster.yaml (hunk 4 above)
Comment (du48s03) [reply src/app/tests/suites/TestModeSelectCluster.yaml:115]: Will do

File: src/app/clusters/mode-select-server/mode-select-server.cpp (hunk 2 above)
Comment (du48s03) [reply src/app/clusters/mode-select-server/mode-select-server.cpp:141]: pull request created: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/5064/files

File: examples/all-clusters-app/all-clusters-common/all-clusters-app.zap [hunk 5]
```diff
@@ -8023,10 +8023,10 @@
               "mfgCode": null,
               "side": "server",
               "included": 1,
-              "storageOption": "RAM",
+              "storageOption": "NVM",
               "singleton": 0,
               "bounded": 0,
-              "defaultValue": "0xFF",
+              "defaultValue": null,
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/all-clusters-common/all-clusters-app.zap:8029]: Unfortunately, ZAP does not actually support having `null` here so far.  It leads to the default ending up as 0, not null.. Please leave the 0xFF for now until they fix that.

**Review by bzbarsky-apple — APPROVED** [review]

File: examples/all-clusters-app/all-clusters-common/all-clusters-app.zap (hunk 5 above)
Comment (du48s03) [reply examples/all-clusters-app/all-clusters-common/all-clusters-app.zap]: StartUpOnOff is an enum whose value can only be 0, 1, or 2. I can no longer set this to 0xFF. I'll change this to 0x1.

Comment (bzbarsky-apple) [reply examples/all-clusters-app/all-clusters-common/all-clusters-app.zap]: > I can no longer set this to 0xFF

Can no longer in that ZAP won't let you?

@tecimovic @wehale Could we please get this nullability stuff sorted out?  We could get by for a bit with the workaround of setting the right bit patter, but if ZAP won't let us do that _and_ mishandles its own nullability UI we have a serious problem.

@du48s03 in the meantime, how do you feel about hand-editing the .zap file to put the right value there?  :(

Comment (bzbarsky-apple) [reply examples/all-clusters-app/all-clusters-common/all-clusters-app.zap]: Thank you!  The ZAP end is fixed now, and once https://github.com/project-chip/connectedhomeip/pull/16894 merges we won't have to do this manual thing....

**Review by woody-apple — APPROVED** [review]
Fast tracking given this has had enough > 3 days for review.
