### PR TITLE
Mark MCSP responses as NOT_IMPLEMENTED

### LINKED ISSUE #11689: Add MCSP to GroupMessageDispatch
#### Problem
Message Counter Sync is not handle in GroupMessageDispatch.

 #### Proposed Solution
Implement it.

### LINKED ISSUE #13668: Crash doing message counter sync
#### Problem
Finally got fuzzing stood up, ran the fuzzer, got:
```
=34895== ERROR: libFuzzer: deadly signal
    #0 0x10e7fff95 in __sanitizer_print_stack_trace+0x35 (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x53f95)
    #1 0x10dac5798 in fuzzer::PrintStackTrace() FuzzerUtil.cpp:210
    #2 0x10daa9473 in fuzzer::Fuzzer::CrashCallback() FuzzerLoop.cpp:233
    #3 0x7fff6838d5fc in _sigtramp+0x1c (libsystem_platform.dylib:x86_64+0x35fc)
    #4 0x10dcfb15f  (<unknown module>)
    #5 0x7fff68263807 in abort+0x77 (libsystem_c.dylib:x86_64+0x7f807)
    #6 0x10d53a419 in chip::Transport::Session::AsSecureSession() Session.cpp:27
    #7 0x10da32851 in chip::secure_channel::MessageCounterManager::SendMsgCounterSyncResp(chip::Messaging::ExchangeContext*, chip::FixedSpan<unsigned char const, 8ul>) MessageCounterManager.cpp:236
    #8 0x10da30a87 in chip::secure_channel::MessageCounterManager::HandleMsgCounterSyncReq(chip::Messaging::ExchangeContext*, chip::System::PacketBufferHandle&&) MessageCounterManager.cpp:261
    #9 0x10da30610 in chip::secure_channel::MessageCounterManager::OnMessageReceived(chip::Messaging::ExchangeContext*, chip::PayloadHeader const&, chip::System::PacketBufferHandle&&) MessageCounterManager.cpp:96
    #10 0x10d4e83e2 in chip::Messaging::ExchangeContext::HandleMessage(unsigned int, chip::PayloadHeader const&, chip::Transport::PeerAddress const&, chip::BitFlags<chip::Messaging::MessageFlagValues, unsigned int>, chip::System::PacketBufferHandle&&) ExchangeContext.cpp:461
    #11 0x10d4f0b22 in chip::Messaging::ExchangeManager::OnMessageReceived(chip::PacketHeader const&, chip::PayloadHeader const&, chip::SessionHandle const&, chip::Transport::PeerAddress const&, chip::SessionMessageDelegate::DuplicateMessage, chip::System::PacketBufferHandle&&) ExchangeMgr.cpp:305
    #12 0x10d545516 in chip::SessionManager::SecureGroupMessageDispatch(chip::PacketHeader const&, chip::Transport::PeerAddress const&, chip::System::PacketBufferHandle&&) SessionManager.cpp:612
    #13 0x10d544984 in chip::SessionManager::OnMessageReceived(chip::Transport::PeerAddress const&, chip::System::PacketBufferHandle&&) SessionManager.cpp:375
    #14 0x10cfb9ac7 in LLVMFuzzerTestOneInput main.cpp:147
    #15 0x10daaa8c3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) FuzzerLoop.cpp:611
    #16 0x10daaa0da in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) FuzzerLoop.cpp:514
    #17 0x10daab589 in fuzzer::Fuzzer::MutateAndTestOne() FuzzerLoop.cpp:757
    #18 0x10daabfb5 in fuzzer::Fuzzer::Loop(std::__2::vector<fuzzer::SizedFile, std::__2::allocator<fuzzer::SizedFile> >&) FuzzerLoop.cpp:895
    #19 0x10da9adea in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) FuzzerDriver.cpp:912
    #20 0x10dac6252 in main FuzzerMain.cpp:20
    #21 0x7fff68194cc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 3 ChangeBinInt-ChangeByte-PersAutoDict- DE: "\007\000\000\000\000\000\000\000"-; base unit: fa91c7912f718cfd3f1e59b25dea323175b722f3
0xe,0x0,0xf1,0xb1,0xf1,0xf1,0xf1,0xf1,0xed,0x73,0x7,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xc1,0x0,0x0,0x0,0x0,0x0,0x5c,0xf3,0x25,0x0,0x0,0x0,0x0,0x0,
\016\000\361\261\361\361\361\361\355s\007\000\000\000\000\000\000\000\301\000\000\000\000\000\\\363%\000\000\000\000\000
artifact_prefix='./'; Test unit written to ./crash-c9fd2434ccf4a33a7f49765dcc519e1fd529a8e5
Base64: DgDxsfHx8fHtcwcAAAAAAAAAwQAAAAAAXPMlAAAAAAA=
```

 #### Proposed Solution
Investigate why receiving the given payload:
```
0xe,0x0,0xf1,0xb1,0xf1,0xf1,0xf1,0xf1,0xed,0x73,0x7,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xc1,0x0,0x0,0x0,0x0,0x0,0x5c,0xf3,0x25,0x0,0x0,0x0,0x0,0x0,
```
as a message leads to the above attempt to treat a non-CASE session as a SecureSession.

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
Potential crash in `AsSecureSession` call.

#### Change overview
Mark MCSP as not implemented. When implementing it should use Group sessions instead of secure sessions.

Fixes #13668

#### Testing
- flashed and commissioned a devkit-c-all-clusters (to ensure this code is not used during regular secure seession support)
- checked out ae05dfc82 and applied these patches on top, no crash

### CODE REVIEW

File: src/protocols/secure_channel/MessageCounterManager.cpp [hunk 1]
```diff
@@ -225,6 +225,9 @@ CHIP_ERROR MessageCounterManager::SendMsgCounterSyncResp(Messaging::ExchangeCont
 
     VerifyOrDie(exchangeContext->HasSessionHandle());
 
+    VerifyOrReturnError(exchangeContext->GetSessionHandle()->GetSessionType() == Session::SessionType::kSecure,
+                        CHIP_ERROR_INVALID_ARGUMENT);
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/MessageCounterManager.cpp:229]: But an MCSP request in fact uses a group session per spec, so this check would always fail for a valid MCSP request....

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

**Comment by bzbarsky-apple** [comment]
> however the change seems trivial enough and can be validated by CI.

We don't have any CI coverage for this code.

**Comment by andy31415** [comment]
> > however the change seems trivial enough and can be validated by CI.
> 
> We don't have any CI coverage for this code.

I guess it does not make it worse then (and validates compilation)? I did a CP on the old code and it seemed to avoid the crash - which is expected because it validates that the cast is ok.

File: src/protocols/secure_channel/MessageCounterManager.cpp (hunk 1 above)
Comment (andy31415) [reply src/protocols/secure_channel/MessageCounterManager.cpp:229]: MCSP is not currently implemented for groups - otherwise this function would work.

From the group messaging discussions, it seems MCSP missing is a known issue and only trust-first is to be enabled.

This check is correct given existing code: this code can only work if the session is secure, based on the cast a few lines below.

Comment (msandstedt) [reply src/protocols/secure_channel/MessageCounterManager.cpp:229]: 4.9.2.5. Message Counter Synchronization Session Context actually has additional metadata.  So yes we will use the operational group key hash as group ID.  But I would think that were this to be implemented, we would want and need to be seeing a completely distinct MCSP session type here.

Comment (andy31415) [reply src/protocols/secure_channel/MessageCounterManager.cpp]: Updated content and added a comment. It seems we want to implement MCSP and existing "counters for secure sessions" should not be a thing (secure sessions should create their own counters).

**Review by bzbarsky-apple — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking given this is removing code.
