### PR TITLE
[nrfconnect] fix the crash during CASE session resumption

### LINKED ISSUE #22621: [Platform] nrfconnect: crash happens during CASE resumption
### Reproduction steps

```bash
1.Commission light switch device
2.Commission light bulb device
3.Bind the light bulb to the light switch with `chip-tool`
4.Toggle light bulb remotely from light switch
5.Light switch is toggled properly
6.Reset light switch device
7.Attempt to toggle light bulb from light switch again
8.Application crashes with Zephyr hard fault during session resumption.
```

### Platform

nrf connect

### Platform Version(s)

_No response_

### Type

Platform validated

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by markaj-nordic**
#### Issue Being Resolved
* Fixes #22621

#### Change overview
Do not use DeviceProxy pointer in application callback (BindingHandler),
as this object instantiated as temporary object in the caller's code.

This is only application/platform related change.

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

File: examples/light-switch-app/nrfconnect/main/BindingHandler.cpp [hunk 1]
```diff
@@ -35,18 +35,13 @@ void BindingHandler::Init()
...
     CHIP_ERROR error;
 
     if (aError == CHIP_ERROR_TIMEOUT && !BindingHandler::GetInstance().mCaseSessionRecovered)
     {
         LOG_INF("Response timeout for invoked command, trying to recover CASE session.");
-        if (!aDevice)
-            return;
-
-        // Release current CASE session.
-        aDevice->Disconnect();
```
Comment (tehampson) [inline examples/light-switch-app/nrfconnect/main/BindingHandler.cpp:49]: Sorry about this crash.

But just wondering what will be marking the session as defunct now before the "Establish new CASE session and retrasmit command that was not applied" below, or do you know that it already has happened and this was just redundant?

Comment (tehampson) [reply examples/light-switch-app/nrfconnect/main/BindingHandler.cpp:49]: Also please feel free to mark this as resolved and merge because a use after free if a lot worse then removing this here. I just wanted to make sure we didn't remove this without making sure that the session is properly marked as defunct

**Review by woody-apple — APPROVED** [review]

File: examples/light-switch-app/nrfconnect/main/BindingHandler.cpp (hunk 1 above)
Comment (markaj-nordic) [reply examples/light-switch-app/nrfconnect/main/BindingHandler.cpp:49]: @tehampson sorry for the late response, maybe the followup PR will be needed. Let's discuss this f2f.
