### PR TITLE
[Groups] Enable GroupTable attribute reporting

### LINKED ISSUE #29773: [1.2]
### Reproduction steps

Set up a wildcard subscribe to a node.  Add a group to the node. Note that adding a group alters GroupKeyManagement Attribute 1 -- GroupTable. Observe that no report was generated on the wildcard subscribe even though the attribute on the GroupKeyManagement cluster changed.

Because there is no reporting event on GroupKeyManagement attribute 1 it is not possible to monitor editing of groups.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

fc2d829858c3f1597d8e5b7d8873d042fa584e04

### Platform

core

### Platform Version(s)

_No response_

### Type

Common Cluster Logic

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by lpbeliveau-silabs**
Added reporting attribute change callback in the group server where actions are modifying the group table

Fixes https://github.com/project-chip/connectedhomeip/issues/29773

### CODE REVIEW

File: src/app/clusters/groups-server/groups-server.cpp [hunk 1]
```diff
@@ -90,6 +91,7 @@ static Status GroupAdd(FabricIndex fabricIndex, EndpointId endpointId, GroupId g
     }
     if (CHIP_NO_ERROR == err)
     {
+        MatterReportingAttributeChangeCallback(0, GroupKeyManagement::Id, GroupKeyManagement::Attributes::GroupTable::Id);
```
Comment (jmartinez-silabs) [inline src/app/clusters/groups-server/groups-server.cpp:94]: suggesting the use of a constexpr for the endpoint value

**Review by jmartinez-silabs — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
Ideally, we would have some tests here.  This should be testable in YAML....
