### PR TITLE
ESP32: Disable unnecessary reconnection for ConnectNetwork command

### LINKED ISSUE #23250: [ESP32] Unnecessary reconnection for connetnetwork command
### Reproduction steps

1. Commissioning the ESP32.
2. Send arm-fail-safe command to ESP32.
```
./chip-tool generalcommissioning arm-fail-safe 900 1 1 0
```
3. Send connect-network command with the networkID which the ESP32 has connected.
```
./out/chip-tool networkcommissioning connect-network NetworkID 1 0
```
The device will disconnect the WiFi and reconnect it. But this step is unnecessary we can send the success response immediately.

### Platform

esp32

### Platform Version(s)

_No response_

### Type

Platform validated

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by wqx6**
Fixes #23250

### CODE REVIEW

File: src/platform/ESP32/NetworkCommissioningDriver.cpp [hunk 1]
```diff
@@ -203,21 +222,34 @@ void ESPWiFiDriver::OnConnectWiFiNetworkFailed(chip::System::Layer * aLayer, voi
...
 
     VerifyOrExit(NetworkMatch(mStagingNetwork, networkId), networkingStatus = Status::kNetworkIDNotFound);
     VerifyOrExit(mpConnectCallback == nullptr, networkingStatus = Status::kUnknownError);
     ChipLogProgress(NetworkProvisioning, "ESP NetworkCommissioningDelegate: SSID: %.*s", static_cast<int>(networkId.size()),
                     networkId.data());
-
+    if (CHIP_NO_ERROR == GetConfiguredNetwork(configuredNetwork))
+    {
+        if (configuredNetwork.networkIDLen == mStagingNetwork.ssidLen &&
+            memcmp(configuredNetwork.networkID, mStagingNetwork.ssid, mStagingNetwork.ssidLen) == 0)
```
Comment (shubhamdp) [inline src/platform/ESP32/NetworkCommissioningDriver.cpp:237]: Instead of rewriting you can use [`NetworkMatch()`](https://github.com/project-chip/connectedhomeip/blob/master/src/platform/ESP32/NetworkCommissioningDriver.cpp#L89-L92) API, it basically does the same thing.

**Review by shubhamdp — APPROVED** [review]

File: src/platform/ESP32/NetworkCommissioningDriver.cpp (hunk 1 above)
Comment (wqx6) [reply src/platform/ESP32/NetworkCommissioningDriver.cpp]: Done

**Review by andy31415 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

File: src/platform/ESP32/NetworkCommissioningDriver.cpp [hunk 2]
```diff
@@ -38,6 +38,25 @@ constexpr char kWiFiCredentialsKeyName[] = "wifi-pass";
 static uint8_t WiFiSSIDStr[DeviceLayer::Internal::kMaxWiFiSSIDLength];
 } // namespace
 
+CHIP_ERROR GetConfiguredNetwork(Network & network)
+{
+    wifi_ap_record_t ap_info;
+    esp_err_t err;
+    err = esp_wifi_sta_get_ap_info(&ap_info);
```
Comment (bzbarsky-apple) [inline src/platform/ESP32/NetworkCommissioningDriver.cpp:45]: Does this fail if the network is not actually joined?  @wqx6

Comment (wqx6) [reply src/platform/ESP32/NetworkCommissioningDriver.cpp:45]: Yes, this function will return ESP_ERR_WIFI_CONN when the station interface is not initialized and ESP_ERR_WIFI_NOT_CONNECT when the station is in disconnect status.
