### PR TITLE
[Darwin] MTRDeviceTests test017 - fix resubscription expectation

### LINKED ISSUE #29365: [Darwin] MTRDeviceTests 17 should make use of the ReportEnd testing facility throughout
Filed per Boris's comment at https://github.com/project-chip/connectedhomeip/pull/29358#discussion_r1332424987

### PR DESCRIPTION
**Pull request by jtung-apple**
Fixes #29365 

This PR makes MTRDeviceTests `test017_TestMTRDeviceBasics` test use the `-unitTestReportEndForDevice:` callback.

I also fixed some warnings that was causing local unit test compilation to fail.

### CODE REVIEW

File: src/app/InteractionModelEngine.h [hunk 1]
```diff
@@ -679,7 +679,7 @@ CHIP_ERROR ReadSingleClusterData(const Access::SubjectDescriptor & aSubjectDescr
 /**
  *  Check whether concrete attribute path is an "existent attribute path" in spec terms.
  *  @param[in]    aPath                 The concrete path of the data being read.
- *  @retval  boolean
+ *  @retval  boolean   true if the concrete attribute path indicates a single existing instance on the node
```
Comment (bzbarsky-apple) [inline src/app/InteractionModelEngine.h:682]:
```suggestion
 *  @retval  boolean   true if the concrete attribute path indicates an attribute that exists on the node.
```

File: src/darwin/Framework/CHIPTests/TestHelpers/MTRTestKeys.m [hunk 2]
```diff
@@ -57,7 +57,7 @@ - (instancetype)init
     CFErrorRef error = NULL;
     const NSDictionary * keygenParams = @{
         (__bridge NSString *) kSecAttrKeyClass : (__bridge NSString *) kSecAttrKeyClassPrivate,
-        (__bridge NSString *) kSecAttrKeyType : (__bridge NSNumber *) kSecAttrKeyTypeECSECPrimeRandom,
+        (__bridge NSString *) kSecAttrKeyType : (__bridge NSString *) kSecAttrKeyTypeECSECPrimeRandom,
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIPTests/TestHelpers/MTRTestKeys.m:60]: Fun catch here!

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
