### PR TITLE
[IM] Merge paths when global dirty set is exhausted

### LINKED ISSUE #16273: `SetDirty` called more than `CHIP_IM_SERVER_MAX_NUM_DIRTY_SET` times will result in data being lost...
#### Problem

If we call `SetDirty` more than `CHIP_IM_SERVER_MAX_NUM_DIRTY_SET` times synchronously in a given execution context, the remaining calls will fail without any real recovery strategy. This will result in those items not being marked dirty and failing to be delivered to clients, resulting in clients seeing a different view of data than what is on the server.

 #### Proposed Solution

The crappiest answer here is to tear down all subscriptions since we can no longer guarantee coherency. We really should endeavor to do better than this.

Possible alternatives include some kind of coalescing/compaction of the dirty list that progressively lowers the precision of the path set to just free up a single slot:

1. Do a sweep over the dirty set to see if we can find attributes that are part of the same cluster + endpoint, and if so, merge them together to a single path that points to the cluster/endpoint.
2. If 1) doesn't yield a slot, then do a sweep over attributes on clusters that are part of the same endpoint, and if so, merge them together to a single path that points to the endpoint.
3. If 2) doesn't yield a slot, then replace all paths with a single path that is wildcard endpoint and cluster.

The algorithm above should exit the moment it manages to free up a single slot.

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem

Fixes #16273 

#### Change overview

Implement the following functions and related unit tests

```
void MergeDirtyPathsUnderSameCluster();
void MergeDirtyPathsUnderSameEndpoint();
```

Actual algorithm implemented in this PR:

1. sweep the existing path to merge the attributes under the same cluster
2. If 1 failed to yield a new slot, merge the existing attributes under the same endpoint
3. If 2 failed to yield a new slot, replace the dirty set by wildcard endpoint.

Check if the new path can be merged into the existing paths after merging the existing paths.

#### Testing

- Added new unit tests.

### CODE REVIEW

File: src/app/reporting/Engine.cpp [hunk 1]
```diff
@@ -658,6 +658,116 @@ bool Engine::MergeOverlappedAttributePath(const AttributePathParams & aAttribute
...
+            // generation to 0 and then clear it later.
+            innerPath->mGeneration = 0;
+            return Loop::Continue;
+        });
+        return Loop::Continue;
+    });
+    return ClearTombPaths();
+}
+
+CHIP_ERROR Engine::InsertPathToDirtySet(const AttributePathParams & aAttributePath)
```
Comment (bzbarsky-apple) [inline src/app/reporting/Engine.cpp:743]:
```suggestion
CHIP_ERROR Engine::InsertPathIntoDirtySet(const AttributePathParams & aAttributePath)
```

File: src/app/reporting/Engine.h [hunk 2]
```diff
@@ -188,6 +188,31 @@ class Engine
      */
     bool MergeOverlappedAttributePath(const AttributePathParams & aAttributePath);
 
+    /**
+     * If we are running out of ObjectPool for the global dirty set, we will try to merge the existing items by clusters.
+     *
+     * Returns if we have released any paths.
```
Comment (bzbarsky-apple) [inline src/app/reporting/Engine.h:194]:
```suggestion
     * Returns whether we have released any paths.
```

File: src/app/reporting/Engine.h [hunk 3]
```diff
@@ -188,6 +188,31 @@ class Engine
...
+     */
+    bool MergeDirtyPathsUnderSameCluster();
+
+    /**
+     * If we are running out of ObjectPool for the global dirty set and we cannot find a slot after merging the existing items by
+     * clusters, we will try to merge the existing items by endpoints.
+     *
+     * Returns if we have released any paths.
```
Comment (bzbarsky-apple) [inline src/app/reporting/Engine.h:202]:
```suggestion
     * Returns whether we have released any paths.
```

File: src/app/reporting/Engine.h [hunk 4]
```diff
@@ -188,6 +188,31 @@ class Engine
...
+     */
+    bool MergeDirtyPathsUnderSameEndpoint();
+
+    /**
+     * During the iterating of the paths, releasing the object in the inner loop will cause undefined behavior of the ObjectPool, so
+     * we replace the items to be cleared by a tomb first, then clear all the tombs after the iteration.
+     *
+     * Returns if we have released any paths.
```
Comment (bzbarsky-apple) [inline src/app/reporting/Engine.h:210]:
```suggestion
     * Returns whether we have released any paths.
```

File: src/app/tests/TestReportingEngine.cpp [hunk 5]
```diff
@@ -53,6 +53,54 @@ class TestReportingEngine
 public:
     static void TestBuildAndSendSingleReportData(nlTestSuite * apSuite, void * apContext);
     static void TestMergeOverlappedAttributePath(nlTestSuite * apSuite, void * apContext);
+    static void TestMergeAttributePathWhenDirtySetPoolExhausted(nlTestSuite * apSuite, void * apContext);
+
+private:
+    static bool InsertToDirtySet(const AttributePathParams & aPath);
```
Comment (bzbarsky-apple) [inline src/app/tests/TestReportingEngine.cpp:59]:
```suggestion
    static bool InsertIntoDirtySet(const AttributePathParams & aPath);
```

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/reporting/Engine.cpp [hunk 6]
```diff
@@ -658,6 +658,116 @@ bool Engine::MergeOverlappedAttributePath(const AttributePathParams & aAttribute
...
+        }
+        return Loop::Continue;
+    });
+    return pathReleased;
+}
+
+bool Engine::MergeDirtyPathsUnderSameCluster()
+{
+    mGlobalDirtySet.ForEachActiveObject([&](auto * outerPath) {
+        if (outerPath->HasWildcardEndpointId() || outerPath->HasWildcardClusterId() || outerPath->mGeneration == 0)
```
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/app/reporting/Engine.cpp:678]: Yes, the check for endpoint is redundant, however, based on spec 7.9 and 7.10, a cluster on an endpoint should be independent with the (same) cluster on another endpoint. Thus it is unlikely to have paths like E*/Cx in global dirty set although it might be wildly used in read requests.

File: src/app/reporting/Engine.cpp [hunk 7]
```diff
@@ -658,6 +658,116 @@ bool Engine::MergeOverlappedAttributePath(const AttributePathParams & aAttribute
...
+            {
+                return Loop::Continue;
+            }
+            if (innerPath->mGeneration > outerPath->mGeneration)
+            {
+                outerPath->mGeneration = innerPath->mGeneration;
+            }
+            outerPath->SetWildcardAttributeId();
+
+            // The object pool does not allow us to release objects in a nested iteration, mark the path as a tomb by setting its
```
[the remark this answers is not in the document]
Comment (erjiaqing) [reply src/app/reporting/Engine.cpp:699]: In `Loop StaticAllocatorBitmap::ForEachActiveObjectInner(void * context, Lambda lambda)`, the bitmap used in the inner loop is not expected to be up to date.

[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/app/reporting/Engine.cpp:699]: We should very clearly document this: the only release that's valid during iteration of a pool is release of the object that was passed to the callback....

**Review by yunhanw-google — APPROVED** [review]

File: src/app/reporting/Engine.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/app/reporting/Engine.cpp:699]: Created https://github.com/project-chip/connectedhomeip/pull/17921 to improve the documentation.

File: src/app/tests/TestReportingEngine.cpp [hunk 8]
```diff
@@ -176,6 +225,100 @@ void TestReportingEngine::TestMergeOverlappedAttributePath(nlTestSuite * apSuite
...
+    *path             = aPath;
+    path->mGeneration = InteractionModelEngine::GetInstance()->GetReportingEngine().GetDirtySetGeneration();
+    return true;
+}
+
+void TestReportingEngine::TestMergeAttributePathWhenDirtySetPoolExhausted(nlTestSuite * apSuite, void * apContext)
+{
+    TestContext & ctx = *static_cast<TestContext *>(apContext);
+    CHIP_ERROR err    = CHIP_NO_ERROR;
+    err               = InteractionModelEngine::GetInstance()->Init(&ctx.GetExchangeManager());
```
Comment (mlepage-google) [inline src/app/tests/TestReportingEngine.cpp:241]: I believe this function requires another argument. It doesn't build for me after syncing this commit.

**Comment by CodeChronos928** [comment]
I'm seeing build errors in src:tests after this change on x86-64:

```
../src/app/tests/TestReportingEngine.cpp: In static member function ‘static void chip::app::reporting::TestReportingEngine::TestMergeAttributePathWhenDirtySetPoolExhausted(nlTestSuite*, void*)’:
../src/app/tests/TestReportingEngine.cpp:241:68: error: no matching function for call to ‘chip::app::InteractionModelEngine::Init(chip::Messaging::ExchangeManager*)’
  241 |     err               = InteractionModelEngine::GetInstance()->Init(&ctx.GetExchangeManager());
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/app/tests/TestReportingEngine.cpp:26:
../src/app/InteractionModelEngine.h:110:16: note: candidate: ‘CHIP_ERROR chip::app::InteractionModelEngine::Init(chip::Messaging::ExchangeManager*, chip::FabricTable*)’
  110 |     CHIP_ERROR Init(Messaging::ExchangeManager * apExchangeMgr, FabricTable * apFabricTable);
      |                ^~~~
../src/app/InteractionModelEngine.h:110:16: note:   candidate expects 2 arguments, 1 provided
```

File: src/app/tests/TestReportingEngine.cpp (hunk 8 above)
Comment (CodeChronos928) [reply src/app/tests/TestReportingEngine.cpp:241]: Same  here.  Posted build errors below.

**Comment by bzbarsky-apple** [comment]
Looks like there was also a merge problem with the lint for PR*16.  See https://github.com/project-chip/connectedhomeip/runs/6235990998?check_suite_focus=true for a failure from that....
