### PR TITLE
Disable testing code which force custom commission

### LINKED ISSUE #22475: [BUG]  Linux Platform sample codes commission flow overridden by redundant & extra hard-coded `Customized` commissioning flow
### Reproduction steps

* In current https://github.com/project-chip/connectedhomeip/blob/master/examples/platform/linux/AppMain.cpp#L210 , it hard-codes and overrides with extra commissioning flow.

* Since the `PrintOnboardingCodes` function is called twice, the log will also print QR code URL twice: the 1st is *Standard* commissioning flow and the other is *Custom* commissioning flow. This is very confusing.

   ...
    {
        ChipLogProgress(NotSpecified, "==== Onboarding payload for Standard Commissioning Flow ====");
        PrintOnboardingCodes(LinuxDeviceOptions::GetInstance().payload);
    }

    {
        // For testing of manual pairing code with custom commissioning flow
        ChipLogProgress(NotSpecified, "==== Onboarding payload for Custom Commissioning Flows ====");
        err = GetPayloadContents(LinuxDeviceOptions::GetInstance().payload, rendezvousFlags);
        SuccessOrExit(err);

        LinuxDeviceOptions::GetInstance().payload.commissioningFlow = chip::CommissioningFlow::kCustom;

        PrintOnboardingCodes(LinuxDeviceOptions::GetInstance().payload);
    }

```


### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

754a208

### Platform

raspi, other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by erwinpan1**
#### Problem
Regular commission should go through Standard Commission Flow.
However the Custom Commission flow (for testing only) is enabled,
and override the Standard Commission flow

Fixes #22475 

#### Change overview
Disable the Custom Commission flow for testing only

#### Testing
How was this tested? (at least one bullet point required)
* Build `examples/all-cluster-minimal-app` and verify commissioning with `examples/chip-tool`

### CODE REVIEW

File: examples/platform/linux/AppMain.cpp [hunk 1]
```diff
@@ -201,6 +201,7 @@ int ChipLinuxAppInit(int argc, char * const argv[], OptionSet * customOptions)
         PrintOnboardingCodes(LinuxDeviceOptions::GetInstance().payload);
     }
 
+#if 0
```
Comment (andy31415) [inline examples/platform/linux/AppMain.cpp:204]: How about making this a command-line argument?

My thinking is: either this is useful code, so we should have it as an argument option, or it is obsolete code, in which case we should delete it rather than effectively commenting it out. `#if 0` comments it out.

Comment (erwinpan1) [reply examples/platform/linux/AppMain.cpp:204]: I personally think it's obsolete because it obviously duplicates calling `PrintOnboardingCodes` function just few lines above. I think we can actually remove this.

Comment (erwinpan1) [reply examples/platform/linux/AppMain.cpp:204]: BTW, the "Custom Commission Flow" is an advanced usage because it would be hooked with the info in DCL. So I don't think this will be commonly used. The codes remaining to be here are just for reference. Actually it can be removed.

Here's few extract from spec `5.1.4. Manual Pairing Code`
```
...  For this case, a commissioner SHOULD use Vendor ID and Product ID to lookup the 
CommissioningCustomFlow field in the Distributed Compliance Ledger (DCL) to determine 
which of these values applies for this Vendor ID and Product ID combination. ...
```

Comment (andy31415) [reply examples/platform/linux/AppMain.cpp:204]: Lets delete the code then. It can be resurrected from git history if really needed.

**Review by andy31415 — APPROVED** [review]

File: examples/platform/linux/AppMain.cpp (hunk 1 above)
Comment (erwinpan1) [reply examples/platform/linux/AppMain.cpp]: Hi Andy, the code is removed as next commit https://github.com/project-chip/connectedhomeip/pull/22409/commits/ab16c74dbcff5ac397f587c61386586fa500595c.
Thanks for the comment.

**Review by bzbarsky-apple — APPROVED** [review]
Approving, but this is going to break various QA/smoketest flows, I expect....

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
> Approving, but this is going to break various QA/smoketest flows, I expect....

If things are actually using this, maybe adding it back as an argument would be the correct thing to do.
None of our CI uses it though it seems.

**Comment by bzbarsky-apple** [comment]
Yes, it's used by manual smoketests to test "commission with long pairing code"...

**Comment by andy31415** [comment]
The origial testing code was added in #15506

**Comment by bzbarsky-apple** [comment]
> The origial testing code was added in https://github.com/project-chip/connectedhomeip/pull/15506

That PR moved the code around.  It did not add it.

**Comment by erwinpan1** [comment]
> > The origial testing code was added in #15506
> 
> That PR moved the code around. It did not add it.

Do you think the current fix makes sense? If yes, can you help to approve?

**Review by msandstedt — APPROVED** [review]
