### PR TITLE
[Fabric-Sync] Allow RPC ports customization in example apps

### LINKED ISSUE #35178: [BUG] Need to add support in fabric-admin and fabric-bridge to customize RPC ports
### Reproduction steps

We need to add support in fabric-admin and fabric-bridge to customize RPC ports so that we can run two sets of fabric-admin+fabric-bridge on the same host. 

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

c4cdbf68836a08ea17b14fad98669341a309aa1f

### Platform

raspi

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by arkq**
### Problem

It's not possible to run more than one set of fabric-admin+fabric-bridge on a single host.

### Changes

- optionally get RPC server ports from program arguments

### Testing

Tested locally while working on TC-MCORE-FS-1.3 update.

### CODE REVIEW

File: examples/fabric-bridge-app/linux/main.cpp [hunk 1]
```diff
@@ -59,8 +61,48 @@ constexpr uint16_t kPollIntervalMs = 100;
 constexpr uint16_t kRetryIntervalS = 3;
 #endif
 
+uint16_t gFabricAdminServerPort = 33001;
+uint16_t gLocalServerPort       = 33002;
+
 BridgedDeviceBasicInformationImpl gBridgedDeviceBasicInformationAttributes;
 
+constexpr uint16_t kOptionFabricAdminServerPortNumber = 0xFF01;
+constexpr uint16_t kOptionLocalServerPortNumber       = 0xFF02;
```
Comment (tehampson) [inline examples/fabric-bridge-app/linux/main.cpp:70]: Why is htis 0xFF01 and 0xFF02 and not 33001 and 33002

File: examples/fabric-bridge-app/linux/main.cpp [hunk 2]
```diff
@@ -59,8 +61,48 @@ constexpr uint16_t kPollIntervalMs = 100;
...
+
+ArgParser::OptionDef sProgramCustomOptionDefs[] = {
+    { "fabric-admin-server-port", ArgParser::kArgumentRequired, kOptionFabricAdminServerPortNumber },
```
Comment (tehampson) [inline examples/fabric-bridge-app/linux/main.cpp:73]: If the argument is required do we need to define a default? or is there a why for this to remain optional?

Comment (tehampson) [reply examples/fabric-bridge-app/linux/main.cpp:73]: Is this just saying that if optionals are provided we need to provide both?

File: examples/fabric-bridge-app/linux/main.cpp (hunk 1 above)
Comment (tehampson) [reply examples/fabric-bridge-app/linux/main.cpp:70]: Is this an argument identifier and not Port number?

File: examples/fabric-bridge-app/linux/main.cpp (hunk 2 above)
Comment (arkq) [reply examples/fabric-bridge-app/linux/main.cpp:73]: This tells the parser that the argument for the option is required, i.e.:  `--option REQUIRED_ARGUMENT`

File: examples/fabric-admin/commands/interactive/InteractiveCommands.h [hunk 3]
```diff
@@ -55,14 +55,26 @@ class InteractiveStartCommand : public InteractiveCommand
     InteractiveStartCommand(Commands * commandsHandler, CredentialIssuerCommands * credsIssuerConfig) :
         InteractiveCommand("start", commandsHandler, "Start an interactive shell that can then run other commands.",
                            credsIssuerConfig)
-    {}
+    {
+#if defined(PW_RPC_ENABLED)
+        AddArgument("fabric-bridge-server-port", 0, UINT16_MAX, &mFabricBridgeServerPort,
+                    "The fabric-bridge RPC port number to connect to (default: 33002).");
+        AddArgument("local-server-port", 0, UINT16_MAX, &mLocalServerPort,
```
Comment (yufengwangca) [inline examples/fabric-admin/commands/interactive/InteractiveCommands.h:62]: Use constant instead of hard coded number 
constexpr uint16_t kFabricBridgeServerPort = 33002;
constexpr uint16_t kFabricLocalServerPort = 33001;

File: examples/fabric-admin/commands/interactive/InteractiveCommands.h [hunk 4]
```diff
@@ -55,14 +55,26 @@ class InteractiveStartCommand : public InteractiveCommand
...
 
     /////////// CHIPCommand Interface /////////
     CHIP_ERROR RunCommand() override;
 
 private:
     char * GetCommand(char * command);
     std::string GetHistoryFilePath() const;
+
+#if defined(PW_RPC_ENABLED)
+    chip::Optional<uint16_t> mFabricBridgeServerPort{ 33002 };
```
Comment (yufengwangca) [inline examples/fabric-admin/commands/interactive/InteractiveCommands.h:75]: Same as above

File: examples/fabric-admin/rpc/RpcClient.h [hunk 5]
```diff
@@ -22,17 +22,19 @@
...
-constexpr uint16_t kFabricBridgeServerPort = 33002;
-
 /**
- * @brief Initializes the RPC client with the specified server port.
+ * @brief Sets the RPC server port to which the RPC client will connect.
  *
- * This function sets the RPC server port and starts packet processing for the RPC client.
+ * @param port The port number.
+ */
+void SetRpcClientPort(uint16_t port);
```
Comment (yufengwangca) [inline examples/fabric-admin/rpc/RpcClient.h:30]: SetRpcClientPort is confusing, since we don't have client port in RPC, we are setting the remote RPC server port to connect here

**Comment by yufengwangca** [comment]
I have a general question, you customize the local and remote RPC ports from the interactive start command instead of program start args we general did in other examples. But the Start command always get called when the example starts with the default values, how you set those numbers? Via the CLI later?

File: examples/fabric-bridge-app/linux/RpcClient.cpp [hunk 6]
```diff
@@ -107,9 +107,13 @@ void RpcCompletedWithEmptyResponse(const pw_protobuf_Empty & response, pw::Statu
 
 } // namespace
 
-CHIP_ERROR InitRpcClient(uint16_t rpcServerPort)
+void SetRpcClientPort(uint16_t port)
```
Comment (yufengwangca) [inline examples/fabric-bridge-app/linux/RpcClient.cpp:110]: There is no Client Port concept in RPC, we need to rename it to SetRpcRemoteServerPort

**Comment by arkq** [comment]
> But the Start command always get called when the example starts with the default values, how you set those numbers? Via the CLI later?

This PR moves the RPC server/client initialization to the `interactive start` command. It's not possible to set these values after interactive session starts because by that time the RPC connection is already established.

File: examples/fabric-admin/commands/interactive/InteractiveCommands.h (hunk 3 above)
Comment (arkq) [reply examples/fabric-admin/commands/interactive/InteractiveCommands.h]: Done

**Review by yufengwangca — APPROVED** [review]

File: examples/fabric-bridge-app/linux/main.cpp [hunk 7]
```diff
@@ -59,8 +61,48 @@ constexpr uint16_t kPollIntervalMs = 100;
...
+    { "local-server-port", ArgParser::kArgumentRequired, kOptionLocalServerPortNumber },
+    {},
+};
+
+const char sProgramCustomOptionHelp[] = "  --fabric-admin-server-port <port>\n"
```
Comment (saurabhst) [inline examples/fabric-bridge-app/linux/main.cpp:78]: Should the README document updated with these new command args ?

**Review by saurabhst — APPROVED** [review]

File: examples/fabric-bridge-app/linux/main.cpp (hunk 7 above)
Comment (arkq) [reply examples/fabric-bridge-app/linux/main.cpp:78]: Maybe as a followup. README does not cover all the options available for fabric-bridge anyway.
