### PR TITLE
[OTA] Tear down CASE session during a timeout error

### LINKED ISSUE #15599: Failed to restart OTA Transfer after aborting midway
#### Problem
Steps
1. Initiate OTA Transfer using Linux apps.
2. Kill Provider App to abort transfer midway.
3. Relaunch Provider App and initiate another Query to restart OTA Transfer.

Seeing error messages on Provider side when sending new Query
[1645751391688] [1109:20414715] CHIP: [IN] Data received on an unknown session (LSID=1). Dropping it!
[1645751396689] [1109:20414715] CHIP: [IN] Data received on an unknown session (LSID=1). Dropping it!
[1645751398689] [1109:20414680] CHIP: [IN] Data received on an unknown session (LSID=1). Dropping it!
[1645751400689] [1109:20414680] CHIP: [IN] Data received on an unknown session (LSID=1). Dropping it!

 #### Proposed Solution
Restarting OTA Transfer should work.

[ota-p.txt](https://github.com/project-chip/connectedhomeip/files/8143445/ota-p.txt)
[ota-r.txt](https://github.com/project-chip/connectedhomeip/files/8143446/ota-r.txt)

### PR DESCRIPTION
**Pull request by carol-apple**
#### Problem
Once the Requestor establishes a CASE session with the Provider, it just assumes that session is good forever. Upon receiving a timeout error from the provider, nothing is being done to rectify this scenario.

Fixes: https://github.com/project-chip/connectedhomeip/issues/15599

#### Change overview
- When a timeout error is received from CASE session establishment attempt, tear down the session
- Make sure the OperationalDeviceProxy also marks the session as expired

#### Testing
- Verify that a successful OTA transfer occurs using Linux requestor/provider apps
- Terminate the ota-provider-app and relaunch
- Make another attempt at QueryImage (either via announce-ota-provider command or the periodic query timer expiring)
- Verify that error received and tear down occurs
- Make another attempt at QueryImage (either via announce-ota-provider command or the periodic query timer expiring)
- Verify that this time, CASE session is established and OTA transfer occurs successfully

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

File: src/app/OperationalDeviceProxyPool.h [hunk 1]
```diff
@@ -61,7 +61,11 @@ class OperationalDeviceProxyPool : public OperationalDeviceProxyPoolDelegate
         return mDevicePool.CreateObject(params, peerId, nodeResolutionData);
     }
 
-    void Release(OperationalDeviceProxy * device) override { mDevicePool.ReleaseObject(device); }
+    void Release(OperationalDeviceProxy * device) override
+    {
+        device->Disconnect();
```
Comment (bzbarsky-apple) [inline src/app/OperationalDeviceProxyPool.h:66]: So one issue with doing this is that if a binding is removed we will destroy the CASE session even if it's also being used by a subscription or something like that....

(That said, I am not sure those would ever end up reusing the same CASE session given the way things are set up right now...)

We really need to get our lifetime stories for this stuff in order.  :(

This is _probably_ OK, but I'd give it like a 40% chance that it will break something.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/OperationalDeviceProxyPool.h (hunk 1 above)
Comment (carol-apple) [reply src/app/OperationalDeviceProxyPool.h]: For the time being, not explicitly calling this Disconnect since it seems `ExpireAllPairings` is called upon every new CASE session establishment. See https://github.com/project-chip/connectedhomeip/issues/15986.

File: src/app/clusters/ota-requestor/OTARequestor.cpp [hunk 2]
```diff
@@ -184,7 +184,14 @@ void OTARequestor::OnQueryImageFailure(void * context, CHIP_ERROR error)
     OTARequestor * requestorCore = static_cast<OTARequestor *>(context);
     VerifyOrDie(requestorCore != nullptr);
 
-    ChipLogDetail(SoftwareUpdate, "QueryImage failure response %" CHIP_ERROR_FORMAT, error.Format());
+    ChipLogError(SoftwareUpdate, "Received QueryImage failure response: %" CHIP_ERROR_FORMAT, error.Format());
+
+    if (error == CHIP_ERROR_TIMEOUT)
```
Comment (hrajendran-samsung) [inline src/app/clusters/ota-requestor/OTARequestor.cpp:189]: Would we have to cleanup the CASE session in case of any other errors?

Comment (carol-apple) [reply src/app/clusters/ota-requestor/OTARequestor.cpp:189]: If the errors are not related to CASE, then probably no. This tear down and reestablishment is expensive so would like to avoid unless absolutely necessary.

**Review by harsha-rajendran — APPROVED** [review]

**Review by selissia — APPROVED** [review]
