### PR TITLE
Fix crash caused by uninitialized variable

### LINKED ISSUE #7188: chip-device-ctrl always crashes in DeviceController::Shutdown()
#### Problem
chip-device-ctrl always crashes when the exit command is issued, with segmentation fault on the following place in src/controller/CHIPDeviceController .cpp DeviceController::Shutdown()

chip::Platform::Delete(mDefaultIMDelegate);

At that point mDefaultIMDelegate is a random uninitialized pointer.

 #### Proposed Solution
Ensure that mDefaultIMDelegate pointer is properly initialized e.g. in CHIPDeviceController.h

DeviceControllerInteractionModelDelegate * mDefaultIMDelegate = nullptr;

Might want to check the other uninitialized members too.

### Crash log

Process 51626 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x0000000107440670 _ChipDeviceCtrl.so`void chip::Platform::Delete<chip::Controller::DeviceControllerInteractionModelDelegate>(p=0x5303a1037c027c01) at CHIPMem.h:162:9
   159 	template <typename T>
   160 	inline void Delete(T * p)
   161 	{
-> 162 	    p->~T();
   163 	    MemoryFree(p);
   164 	}
   165 	
Target 0: (python3) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0x0000000107440670 _ChipDeviceCtrl.so`void chip::Platform::Delete<chip::Controller::DeviceControllerInteractionModelDelegate>(p=0x5303a1037c027c01) at CHIPMem.h:162:9
    frame #1: 0x0000000107440516 _ChipDeviceCtrl.so`chip::Controller::DeviceController::Shutdown(this=0x0000000102c93000) at CHIPDeviceController.cpp:365:9

### PR DESCRIPTION
**Pull request by bluebin14**
#### Problem
What is being fixed?
* Fix crash in DeviceController::Shutdown()
* Fixes #7188 chip-device-ctrl always crashes in DeviceController::Shutdown()

#### Change overview
This PR fixes crash caused by uninitialized member variable. The crash happened in DeviceController::Shutdown().

#### Testing
How was this tested? (at least one bullet point required)
* launch chip-device-ctrl
* commission accessory e.g. connect -ble 3840 12345678 12344321
* optionally enter any other commands
* issue exit command

Result without the fix: crash with segmentation fault on the following place in src/controller/CHIPDeviceController .cpp DeviceController::Shutdown()

chip::Platform::Delete(mDefaultIMDelegate);

Result with the fix: application tears down correctly and exits.

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by erjiaqing — APPROVED** [review]
Thanks.

**Review by saurabhst — APPROVED** [review]

File: src/controller/CHIPDeviceController.h [hunk 1]
```diff
@@ -277,7 +277,7 @@ class DLL_EXPORT DeviceController : public Messaging::ExchangeDelegate,
     Messaging::ExchangeManager * mExchangeMgr;
     secure_channel::MessageCounterManager * mMessageCounterManager;
     PersistentStorageDelegate * mStorageDelegate;
-    DeviceControllerInteractionModelDelegate * mDefaultIMDelegate;
+    DeviceControllerInteractionModelDelegate * mDefaultIMDelegate = nullptr;
```
Comment (andy31415) [inline src/controller/CHIPDeviceController.h:280]: If we make this change, we should probably initialize all the above to nullptr. Setting to nullptr only the ones that seem to case a crash seems a bit too picky.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@bluebin14 - could you try making a change and re-updating this PR? Restyler seems stuck.

maybe the change could be to add more nullptr initializations as in my comment.

File: src/controller/CHIPDeviceController.h (hunk 1 above)
Comment (bluebin14) [reply src/controller/CHIPDeviceController.h:280]: added a change that initializes all member variables to null, hopefully that also fixes the stuck restyler.

**Review by jmartinez-silabs — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@bluebin14 Needs rebase to tip to fix the Darwin failure...
