### PR TITLE
Fix wildcard path setDirty merge

### LINKED ISSUE #16734: Fix the potential wildcard dirty path issue in MergeOverlappedAttributePath
#### Problem
When we extend setDirty with wildcard support, we have not yet updated MergeOverlappedAttributePath, Concretely, let's say path is (wildcard endpoint, cluster 6, wildcard attribute) and aAttributePath is (wildcard endpoint, wildcard cluster, wildcard attribute), we would update the path with aAttributePath.

 #### Proposed Solution
 update MergeOverlappedAttributePath with wildcard handling

### PR DESCRIPTION
**Pull request by yunhanw-google**
#### Problem
What is being fixed?  Examples:
* Fixes #16734 
#### Change overview
update MergeOverlappedAttributePath with wildcard handling and update the existing test to cover the wildcard situations.

#### Testing
Update the testing to cover the wildcard situation.

### CODE REVIEW

File: src/app/reporting/Engine.cpp [hunk 1]
```diff
@@ -643,7 +643,13 @@ bool Engine::MergeOverlappedAttributePath(AttributePathParams & aAttributePath)
         }
         if (aAttributePath.IsAttributePathSupersetOf(*path))
         {
+            // TODO: the wildcard input path may be superset of next paths in globalDirtySet, it is fine at this moment, since
+            // when building report, it would use the first path of globalDirySet to compare against interested paths read clients
```
Comment (bzbarsky-apple) [inline src/app/reporting/Engine.cpp:647]:
```suggestion
            // when building report, it would use the first path of globalDirtySet to compare against interested paths read clients
```

File: src/app/reporting/Engine.cpp [hunk 2]
```diff
@@ -643,7 +643,13 @@ bool Engine::MergeOverlappedAttributePath(AttributePathParams & aAttributePath)
...
+            // wants.
```
Comment (bzbarsky-apple) [inline src/app/reporting/Engine.cpp:648]:
```suggestion
            // want.
```

**Review by bzbarsky-apple — APPROVED** [review]

**Review by yufengwangca — APPROVED** [review]
