### PR TITLE
CASE: Handle failure if unable to schedule handle/send sigma3c

### LINKED ISSUE #26737: [BUG] CASE session establishment is disabled after ScheduleWork fails in WorkHandler
### Reproduction steps

The CASE session establishment is disabled after the `ScheduleWork` fails in `WorkHandler` and the device doesn't send the status report for sigma3. Then the device can never be reachable over CASE any more. Related to #26280.

The log:
[esp32_logs.txt](https://github.com/project-chip/connectedhomeip/files/11540658/esp32_USB5_logs.txt)

### Bug prevalence

Sometimes

### GitHub hash of the SDK that was being used

8f66f4215bc0708efc8cc73bda80620e67d8955f

### Platform

esp32

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shubhamdp**
#### Problem
Sending and Handling Sigma3 is an async process and divided into three parts, Sigma3a, Sigma3b, and Sigma3c.
Sigma3a schedules Sigma3b, and Sigma3b is suppose to schedule the Sigma3c.

If We fail to schedule Sigma3c then, we are in the state where the only option to recover is reboot. Problem is more described in https://github.com/project-chip/connectedhomeip/pull/25695#discussion_r1178391687 and logs in #26737 has hit this problem. 

Fixes #26737 and completes below item from #26280
> Improve handling if scheduling work fails.
https://github.com/project-chip/connectedhomeip/pull/25695#discussion_r1178391687

#### Change Overview
Implemented the suggestion provided by Marc here: https://github.com/project-chip/connectedhomeip/issues/26280#issuecomment-1595268002

- We are no longer unregistering the unsolicit message hander for sigma1. Based on handshake state and failure to schedule work, decide what to do:
    1. If in middle of handshake but it's zombie, tear down the handshake.
    2. If still in middle of handshake, return without responding.
    3. Otherwise, just do a new handshake.

- Added APIs in helper to check if it fails to schedule after work callback and to re run it from foreground thread.
- Added wrapper around the APIs for HandleSigma3 and SendSigma3 cases.

#### Tests
1. Built chip-tool and lighting-app/esp32, tested commissioning and onoff toggle.
2. Also to test specific scenario, I'have commented below line and verified that case server enables with this fix.
https://github.com/project-chip/connectedhomeip/blob/643f7aaeef020d00892ecb9631adc03e2504dacd/src/protocols/secure_channel/CASESession.cpp#L230

#### Follow ups to do
1. Send Busy response when we are in the middle of handshake and receives sigma1
2. Check if `RegisterUnsolicitedMessageHandlerForType()` can be moved out from `PrepareForSessionEstablishment()`, this gets called every time after case is established/failed.
3. Call `IsSendSigma3PermanentlyBlockedOnBackgroundWork()` and `UnblockSendSigma3FromForegroundWork()` from CASEClient.

https://github.com/project-chip/connectedhomeip/issues/27474 and https://github.com/project-chip/connectedhomeip/issues/27473

### CODE REVIEW

File: src/protocols/secure_channel/CASESession.cpp [hunk 1]
```diff
@@ -224,12 +233,29 @@ class CASESession::WorkHelper
         bool cancel = false;
         // Execute callback in background thread; data must be OK with this
         helper->mStatus = helper->mWorkCallback(helper->mData, cancel);
+
+        // Check the status and call OnWorkFailedCallback
+        if (helper->mStatus != CHIP_NO_ERROR)
+        {
+            if (auto * session = helper->mSession.load())
+            {
+                (session->*(helper->mOnWorkFailedCallback))(helper->mStatus);
```
Comment (tcarmelveilleux) [inline src/protocols/secure_channel/CASESession.cpp:242]: Please introduce helper variables to improve legibility of this incantation if possible

File: src/protocols/secure_channel/CASESession.h [hunk 2]
```diff
@@ -245,6 +245,9 @@ class DLL_EXPORT CASESession : public Messaging::UnsolicitedMessageHandler,
     static CHIP_ERROR HandleSigma3b(HandleSigma3Data & data, bool & cancel);
     CHIP_ERROR HandleSigma3c(HandleSigma3Data & data, CHIP_ERROR status);
 
+    // This will be called when Handle/Send Sigma3b returns error or we fail to schedule Handle/Send Sigma3c
+    void OnSigma3_AsyncFailure(CHIP_ERROR status);
```
Comment (mlepage-google) [inline src/protocols/secure_channel/CASESession.h:249]: This file/class currently isn't using the "on" naming style for callbacks, in the names of functions, or in the names of the callbacks in WorkHelper. Also, it's not currently using underscores. I suggest following the naming conventions in this file and class. E.g. just `Sigma3AsyncFailure` or similar.

File: src/protocols/secure_channel/CASESession.cpp [hunk 3]
```diff
@@ -151,19 +151,26 @@ class CASESession::WorkHelper
     // The `status` value is the result of the work callback (called beforehand).
     typedef CHIP_ERROR (CASESession::*AfterWorkCallback)(DATA & data, CHIP_ERROR status);
 
+    // This callback will be called if WorkCallback returns error code other than CHIP_NO_ERROR,
```
Comment (mlepage-google) [inline src/protocols/secure_channel/CASESession.cpp:154]: I think it's fine to have a callback for if/when the scheduling fails, but it shouldn't occur if the work is scheduled but itself returns a (work-specific) error code that isn't OK. Those errors from work are normally (when scheduling works) ferried back to the CASESession object via the 'C' part of the work, and handled there. Arguably this callback should just be for if scheduling back to the fg thread fails.

File: src/protocols/secure_channel/CASESession.cpp [hunk 4]
```diff
@@ -224,12 +233,29 @@ class CASESession::WorkHelper
...
         // Hold strong ptr while work is outstanding
         helper->mStrongPtr.swap(strongPtr);
         auto status = DeviceLayer::PlatformMgr().ScheduleWork(AfterWorkHandler, reinterpret_cast<intptr_t>(helper));
+
         if (status != CHIP_NO_ERROR)
         {
+            // Scheduling AfterWorkHandler failed, lets call OnWorkFailedCallback
+            if (auto * session = helper->mSession.load())
+            {
+                (session->*(helper->mOnWorkFailedCallback))(helper->mStatus);
```
Comment (mlepage-google) [inline src/protocols/secure_channel/CASESession.cpp:257]: How do we know it is safe to call the callback on the session object from a background thread? If WorkHelper requires the error handling callback to be safe to call from background thread (like WorkCallback), then it needs to be document that requirement (like WorkCallback).

File: src/protocols/secure_channel/CASESession.cpp [hunk 5]
```diff
@@ -224,12 +233,29 @@ class CASESession::WorkHelper
         bool cancel = false;
         // Execute callback in background thread; data must be OK with this
         helper->mStatus = helper->mWorkCallback(helper->mData, cancel);
+
+        // Check the status and call OnWorkFailedCallback
```
Comment (mlepage-google) [inline src/protocols/secure_channel/CASESession.cpp:237]: As noted above, I don't think we should call the callback in the case of normal failure of the work. That failure is reported back to the caller (session object) through normal operation of the WorkHelper, when scheduling works, and the caller has to handle cleanup there anyways.

File: src/protocols/secure_channel/CASESession.cpp [hunk 6]
```diff
@@ -224,12 +233,29 @@ class CASESession::WorkHelper
...
+        if (helper->mStatus != CHIP_NO_ERROR)
+        {
+            if (auto * session = helper->mSession.load())
+            {
+                (session->*(helper->mOnWorkFailedCallback))(helper->mStatus);
+            }
+            return;
+        }
+
         VerifyOrReturn(!cancel && !helper->IsCancelled());
```
Comment (mlepage-google) [inline src/protocols/secure_channel/CASESession.cpp:247]: The order of the new code and this line means that if an error is return during normal background work, and also the background work (or foreground) requests cancellation, we treat that as error instead of cancellation. I'd prefer cancellation to have precedence. (But as noted, I'd prefer normal work errors to not use this special scheduling failure callback.)

File: src/protocols/secure_channel/CASESession.cpp [hunk 7]
```diff
@@ -1516,6 +1546,13 @@ CHIP_ERROR CASESession::SendSigma3c(SendSigma3Data & data, CHIP_ERROR status)
     return err;
 }
 
+void CASESession::OnSigma3_AsyncFailure(CHIP_ERROR status)
+{
+    SendStatusReport(mExchangeCtxt, kProtocolCodeInvalidParam);
```
Comment (mlepage-google) [inline src/protocols/secure_channel/CASESession.cpp:1551]: How can all this occur on the background thread, possibly while the foreground thread is also potentially operating on the same CASESession object?

Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:1551]: This is not OK, and will fail threasafety asserts.  You _have_ to deal with exchanges on the Matter thread, or at least while holding the locks.... and note that not all platforms allow you to have locks.

This part needs some careful thought.

What we probably need is some guarantee that a platform allows _at least one_ of locking the Matter stack and infallible dispatch to the Matter queue, auditing of our platforms to that effect, and documentation in platform manager to that effect.  And then here, since we know the dispatch failed (and we would need to restrict to that case!), we can take the relevant locks, etc.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/protocols/secure_channel/CASESession.cpp (hunk 7 above)
Comment (shubhamdp) [reply src/protocols/secure_channel/CASESession.cpp:1551]: Sorry for the confusion. I mistakenly assumed that `ScheduleWork` and `ScheduleBackgroundWork` are basically same, but it appears that they operate differently and may not work here. I'll check what can be done. Thank you for bringing this to my attention.

File: src/protocols/secure_channel/CASESession.cpp (hunk 3 above)
Comment (shubhamdp) [reply src/protocols/secure_channel/CASESession.cpp]: Sure, thanks for the clarification, will change accordingly.

File: src/protocols/secure_channel/CASESession.cpp (hunk 5 above)
Comment (shubhamdp) [reply src/protocols/secure_channel/CASESession.cpp]: reverted this change!

File: src/protocols/secure_channel/CASESession.cpp (hunk 6 above)
Comment (shubhamdp) [reply src/protocols/secure_channel/CASESession.cpp]: As I removed the above checks, this comment is not valid anymore.

File: src/protocols/secure_channel/CASESession.h (hunk 2 above)
Comment (shubhamdp) [reply src/protocols/secure_channel/CASESession.h]: I got motivated from HandleSigma2_and_SendSigma3 and I had a gut feeling to not use that convention, changing as per your suggestion.

File: src/protocols/secure_channel/CASESession.cpp (hunk 4 above)
Comment (shubhamdp) [reply src/protocols/secure_channel/CASESession.cpp]: Added a comment, PTAL!

File: src/protocols/secure_channel/CASESession.cpp [hunk 8]
```diff
@@ -228,8 +239,16 @@ class CASESession::WorkHelper
         // Hold strong ptr while work is outstanding
         helper->mStrongPtr.swap(strongPtr);
         auto status = DeviceLayer::PlatformMgr().ScheduleWork(AfterWorkHandler, reinterpret_cast<intptr_t>(helper));
```
Comment (shubhamdp) [inline src/protocols/secure_channel/CASESession.cpp:241]: How about `VerifyOrDie()`? Device is anyway is bricked and need reboot, we do an intentional one. @bzbarsky-apple @mlepage-google @tcarmelveilleux

Comment (bzbarsky-apple) [reply src/protocols/secure_channel/CASESession.cpp:241]: Device is not "bricked"; it just can't have new CASE sessions established for it.

What do you think of my suggestion above of requiring at least one of locking the Matter stack and infallible dispatch to the Matter queue whenever this background crypto stuff is enabled?

Or even just requiring locks to work whenever background crypto is enabled?

**Comment by shubhamdp** [comment]
@bzbarsky-apple @mlepage-google @tcarmelveilleux I have resolved all the threads as I have implemented the suggestion from Marc (https://github.com/project-chip/connectedhomeip/issues/26280#issuecomment-1595268002) and they are outdated at the moment. Requesting re-review.

File: src/protocols/secure_channel/CASEServer.cpp [hunk 9]
```diff
@@ -73,6 +73,20 @@ CHIP_ERROR CASEServer::OnUnsolicitedMessageReceived(const PayloadHeader & payloa
 CHIP_ERROR CASEServer::OnMessageReceived(Messaging::ExchangeContext * ec, const PayloadHeader & payloadHeader,
                                          System::PacketBufferHandle && payload)
 {
+    if (mDoingCASEHandshake)
+    {
+        if (GetSession().IsHandleSigma3PermanentlyBlockedOnBackgroundWork())
```
[the remark this answers is not in the document]
Comment (mlepage-google) [reply src/protocols/secure_channel/CASEServer.cpp:78]: As a bonus, this should make it easier to handle both Send and Handle scheduling failures, which is probably a good idea.

File: src/protocols/secure_channel/CASESession.cpp [hunk 10]
```diff
@@ -203,6 +203,27 @@ class CASESession::WorkHelper
 
     bool IsCancelled() const { return mSession.load() == nullptr; }
 
+    // This API returns true when background thread fails to schedule the AfterWorkCallback
+    bool SchedulingAfterWorkCallbackFailed() { return mScheduleAfterWorkFailed.load(); }
```
[the remark this answers is not in the document]
Comment (mlepage-google) [reply src/protocols/secure_channel/CASESession.cpp:207]: Or `CannotScheduleAfterWorkCallback`

File: src/protocols/secure_channel/CASESession.cpp [hunk 11]
```diff
@@ -203,6 +203,27 @@ class CASESession::WorkHelper
...
+
+    // This API runs the AfterWorkCallback. This is supposed to be called from foreground thread
+    // and only call if SchedulingAfterWorkCallbackFailed() returns false.
+    CHIP_ERROR RunAfterWorkCallback()
+    {
+        // Ensure that this function is being called from main Matter thread
+        assertChipStackLockedByCurrentThread();
```
[the remark this answers is not in the document]
Comment (mlepage-google) [reply src/protocols/secure_channel/CASESession.cpp:214]: Actually regarding `IsCancelled` there's two kinds of cancel: 1) the kind called from the main thread, which tries to avoid scheduling part C and aborting, and 2) the kind from the work function itself, which also tries to avoid scheduling part C. In the former case, presumably the main thread has already handled what it needs to, and in the latter case, it's already not scheduling part C, so failure to do so isn't relevant. So I don't think we need to do anything for cancel, we just need to ensure the main thread is cleaning up and doing any responses (if it desires) in all cases.

File: src/protocols/secure_channel/CASEServer.cpp [hunk 12]
```diff
@@ -84,10 +98,13 @@ CHIP_ERROR CASEServer::OnMessageReceived(Messaging::ExchangeContext * ec, const
...
 
+    mDoingCASEHandshake = true;
+
     // TODO - Enable multiple concurrent CASE session establishment
     // https://github.com/project-chip/connectedhomeip/issues/8342
-    ChipLogProgress(Inet, "CASE Server disabling CASE session setups");
-    mExchangeManager->UnregisterUnsolicitedMessageHandlerForType(Protocols::SecureChannel::MsgType::CASE_Sigma1);
+
+    // Earlier we used to unregister the unsolicit message handler for Sigma1 messages.
+    // Now, we keep it registered and perform the appropriate action in above block
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASEServer.cpp:107]: There's no reason to have this comment here.  Just remove it, please.

File: src/protocols/secure_channel/CASEServer.cpp [hunk 13]
```diff
@@ -73,6 +73,20 @@ CHIP_ERROR CASEServer::OnUnsolicitedMessageReceived(const PayloadHeader & payloa
...
+    if (mDoingCASEHandshake)
+    {
+        if (GetSession().IsHandleSigma3PermanentlyBlockedOnBackgroundWork())
+        {
+            ChipLogError(Inet, "CASE session helper failed to schedule HandleSigma3c, executing HandleSigma3c");
+            GetSession().UnblockHandleSigma3FromForegroundWork();
+        }
+        else
+        {
+            ChipLogError(Inet, "CASE session is in establishing state, returning without responding");
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASEServer.cpp:85]: Please add a comment pointing to https://github.com/project-chip/connectedhomeip/issues/27473

**Review by bzbarsky-apple — APPROVED** [review]
Looks good to me, after @mlepage-google's comments are addressed!

File: src/protocols/secure_channel/CASESession.cpp [hunk 14]
```diff
@@ -203,6 +206,23 @@ class CASESession::WorkHelper
...
+    CHIP_ERROR DoAfterWork()
+    {
+        // Ensure that this function is being called from main Matter thread
+        assertChipStackLockedByCurrentThread();
+
+        VerifyOrReturnError(mSession && mAfterWorkCallback, CHIP_ERROR_INCORRECT_STATE);
+
+        auto * helper   = this;
+        helper->mStatus = (helper->mSession->*(helper->mAfterWorkCallback))(helper->mData, helper->mStatus);
+        return helper->mStatus;
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:223]: This part is suspect, since calling mAfterWorkCallback can delete "this", hence delete `helper`, because we are not holding a strong ref to it or anything like that.  Why is this not just:
```suggestion
        return (mSession->*mAfterWorkCallback)(mData, mStatus);
```
That said, why do we care about the status of the after-work callback?  I would have expect this function to return void, just like AfterWorkHandler...  

In fact, I'm not quite sure why we don't:

1. Make AfterWorkHandler assert assertChipStackLockedByCurrentThread.
2. Have this function assert (not verify-or-return-error, VerifyOrDie)  mScheduleAfterWorkFailed.
3. Have this function call `AfterWorkHandler(reinterpret_cast<intptr_t>(this))` (or have both call a shared thing of some sort?) just so we have fewer repetitions of this code.

File: src/protocols/secure_channel/CASESession.cpp [hunk 15]
```diff
@@ -226,6 +246,11 @@ class CASESession::WorkHelper
         auto status = DeviceLayer::PlatformMgr().ScheduleWork(AfterWorkHandler, reinterpret_cast<intptr_t>(helper));
         if (status != CHIP_NO_ERROR)
         {
+            // We failed to schedule after work callback, so setting mScheduleAfterWorkFailed flag to true
+            // This can be checked from foreground thread and after work callback can be retried
+            ChipLogError(SecureChannel, "Failed to Schedule the AfterWorkCallback on foreground thread");
+            helper->mScheduleAfterWorkFailed.store(true);
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:252]: This also needs to set `helper->mStatus = status`, so the after-work callback is called with failure, no?

File: src/protocols/secure_channel/CASESession.cpp [hunk 16]
```diff
@@ -2179,4 +2208,33 @@ System::Clock::Timeout CASESession::ComputeSigma2ResponseTimeout(const ReliableM
         kExpectedHighProcessingTime;
 }
 
+bool CASESession::InvokeBackgroundWorkWatchdog()
+{
+    bool status = false;
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:2213]: This should probably be called "wasBlocked" or "wasStuck" or something.

File: src/protocols/secure_channel/CASESession.cpp [hunk 17]
```diff
@@ -2179,4 +2208,33 @@ System::Clock::Timeout CASESession::ComputeSigma2ResponseTimeout(const ReliableM
...
+
+    if (mSendSigma3Helper && mSendSigma3Helper->UnableToScheduleAfterWorkCallback())
+    {
+        ChipLogError(SecureChannel, "SendSigma3Helper was unable to schedule the AfterWorkCallback");
+        if (mSendSigma3Helper->DoAfterWork() != CHIP_NO_ERROR)
+        {
+            SendStatusReport(mExchangeCtxt, kProtocolCodeInvalidParam);
+            mState = State::kInitialized;
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:2221]: Should not be needed; the after-work callback should be handling all this.

Again, the DoAfterWork thing should just return void.

File: src/protocols/secure_channel/CASESession.h [hunk 18]
```diff
@@ -207,6 +205,15 @@ class DLL_EXPORT CASESession : public Messaging::UnsolicitedMessageHandler,
         kHandleSigma3Pending = 9,
     };
 
+    State GetState() { return mState; }
+
+    // Checks if any of the work helper is unable to schedule the after work callback
+    // If they are stuck, runs the after work callback from the foreground thread.
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.h:211]:
```suggestion
    // Returns true if the CASE session handshake was stuck due to failing to schedule work on the Matter thread.
    // If this function returns true, the CASE session has been reset and is ready for a new session establishment.
```

Comment (shubhamdp) [reply src/protocols/secure_channel/CASESession.h]: Incorporated this locally along with other changes!

File: src/protocols/secure_channel/CASESession.cpp (hunk 16 above)
Comment (shubhamdp) [reply src/protocols/secure_channel/CASESession.cpp]: renamed to `wasBlocked`

File: src/protocols/secure_channel/CASESession.cpp (hunk 15 above)
Comment (shubhamdp) [reply src/protocols/secure_channel/CASESession.cpp:246]: Yep, catching the status now.

File: src/protocols/secure_channel/CASESession.cpp (hunk 14 above)
Comment (shubhamdp) [reply src/protocols/secure_channel/CASESession.cpp]: As suggested, `DoAfterWork` now calls `AfterWorkHandler` and added assert checks as per suggestion. PTAL!

File: src/protocols/secure_channel/CASESession.cpp [hunk 19]
```diff
@@ -2179,4 +2206,25 @@ System::Clock::Timeout CASESession::ComputeSigma2ResponseTimeout(const ReliableM
         kExpectedHighProcessingTime;
 }
 
+bool CASESession::InvokeBackgroundWorkWatchdog()
+{
+    bool wasBlocked = false;
```
Comment (mlepage-google) [inline src/protocols/secure_channel/CASESession.cpp:2211]:
```suggestion
    bool watchdogFired = false;
```

File: src/protocols/secure_channel/CASEServer.cpp [hunk 20]
```diff
@@ -73,6 +73,19 @@ CHIP_ERROR CASEServer::OnUnsolicitedMessageReceived(const PayloadHeader & payloa
...
+    {
+        // We are in the middle of CASE handshake
+
+        // Check if we are stuck on background thread, if yes, unblock it, and continue
+        if (GetSession().InvokeBackgroundWorkWatchdog() == false)
+        {
+            // TODO: Send Busy response, #27473
+            ChipLogError(Inet, "CASE session is in establishing state, returning without responding");
+            return CHIP_NO_ERROR;
+        }
```
Comment (mlepage-google) [inline src/protocols/secure_channel/CASEServer.cpp:86]:
```suggestion
        // Invoke watchdog to fix any stuck handshakes
        bool watchdogFired = GetSession().InvokeBackgroundWorkWatchdog();
        if (!watchdogFired)
        {
            // Handshake wasn't stuck, let it continue its work
            // TODO: Send Busy response, #27473
            ChipLogError(Inet, "CASE session is in establishing state, returning without responding");
            return CHIP_NO_ERROR;
        }
```

Comment (mlepage-google) [reply src/protocols/secure_channel/CASEServer.cpp:86]: Hoping to make the logic/comment here clearer.

File: src/protocols/secure_channel/CASESession.cpp (hunk 19 above)
Comment (mlepage-google) [reply src/protocols/secure_channel/CASESession.cpp]: Suggested naming.

**Review by mlepage-google — APPROVED** [review]
Couple more naming/comment suggestions.

File: src/protocols/secure_channel/CASESession.cpp [hunk 21]
```diff
@@ -226,6 +240,12 @@ class CASESession::WorkHelper
         auto status = DeviceLayer::PlatformMgr().ScheduleWork(AfterWorkHandler, reinterpret_cast<intptr_t>(helper));
         if (status != CHIP_NO_ERROR)
         {
+            // We failed to schedule after work callback, so setting mScheduleAfterWorkFailed flag to true
+            // This can be checked from foreground thread and after work callback can be retried
+            ChipLogError(SecureChannel, "Failed to Schedule the AfterWorkCallback on foreground thread");
+            helper->mScheduleAfterWorkFailed.store(true);
+            helper->mStatus = status;
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:247]: This line needs to be before we set mScheduleAfterWorkFailed.  We're on a background thread here, and once we set mScheduleAfterWorkFailed to true we can get our DoAfterWork called on the other thread.  If that happens before mStatus gets set, that would be bad.  So need to set mStatus first, then do the synchronization point on the atomic boolean.

File: src/protocols/secure_channel/CASESession.cpp [hunk 22]
```diff
@@ -226,6 +240,12 @@ class CASESession::WorkHelper
...
+
             // Release strong ptr since scheduling failed
             helper->mStrongPtr.reset();
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:250]: Please double-check me carefully on this @shubhamdp and @mlepage-google: now that we have this watchdog mechanism, we should NOT reset helper->mStrongPtr here.

Here's why: let's say we reset it (and to be safe we reset it before our mScheduleAfterWorkFailed synchronization point).  At that point the only reference to us is the one the session is holding.  When we now call the after-work handler it will call into the session, and the session has to be careful to not drop its ref before it's done using the data (which is owned by this object).  Right now that happens to be true, but it's very fragile.

The reason we had this reset bit was to avoid leaking due to this ref that would never go away, but now we _do_ have a mechanism for it to go away in the form of the watchdog, right?

**Review by bzbarsky-apple — APPROVED** [review]
Approving, but note the comments.

File: src/protocols/secure_channel/CASESession.cpp (hunk 21 above)
Comment (shubhamdp) [reply src/protocols/secure_channel/CASESession.cpp]: Thanks for pointing out and explanation, moved above.

File: src/protocols/secure_channel/CASESession.cpp (hunk 22 above)
Comment (mlepage-google) [reply src/protocols/secure_channel/CASESession.cpp:250]: I think it's fine to reset the helper's strong ptr to itself here. From its perspective, it's done. The session does still hold a strong ptr to the helper, and yes it has to properly manage that as it does anything with the helper.

If the CASESession were destroyed (object deleted), the helper would still need to be deleted.

At the same time, we can't put ownership solely in the CASESession, because it can't clean up if a scheduled function is waiting to run.

Comment (bzbarsky-apple) [reply src/protocols/secure_channel/CASESession.cpp:250]: > and yes it has to properly manage that as it does anything with the helper

Well, SendSigma3c does not manage it properly in that case....  we should just do a followup to:
1. Document the expectations on CASESession clearly for these ownership bits.
2. Ensure that those expectations are followed.

Comment (shubhamdp) [reply src/protocols/secure_channel/CASESession.cpp:250]: I have filed https://github.com/project-chip/connectedhomeip/issues/27541 for tracking this.

Comment (dhrishi) [reply src/protocols/secure_channel/CASESession.cpp:250]: Can we resolve the conversation as the follow-up issue is filed? @bzbarsky-apple @mlepage-google

Comment (shubhamdp) [reply src/protocols/secure_channel/CASESession.cpp:250]: Resolving this thread!
