### PR TITLE
[ble] Fixed controller not being able to commission device after first attempt failure

### LINKED ISSUE #13286: Controller is not able to commission the device after first attempt failure.
#### Problem
Sometimes it happens that if in specific moment of device commissioning over Bluetooth LE the connection will be closed (e.g. by turning off HCI adapter to simulate hardware problems) the controller is not able to commission the device on the second attempt due to incorrect state. To trigger a fault behavior it has to happen after `BleConnectionComplete`. Turning off adapter earlier doesn't result in any problems.

Here is the testing procedure with Python CHIP controller:
1. Connect to the device over BLE, during the connection turn off HCI adapter and wait for PASE timeout

> chip-device-ctrl > connect -ble 3840 20202021 1
Device is assigned with nodeid = 1
[1640858187.953930][169046:169055] CHIP:SC: Assigned local session key ID 3
[1640858187.953960][169046:169055] CHIP:SC: Including MRP parameters in PBKDF param request
[1640858187.953985][169046:169055] CHIP:IN: Prepared plaintext message 0x7f8215bdb930 to 0x0000000000000000 (0)  of type 0x20 and protocolId (0, 0) on exchange 1582i with MessageCounter:3677862499.
[1640858187.954001][169046:169055] CHIP:IN: Sending plaintext msg 0x7f8215bdb930 with MessageCounter:3677862499 to 0x0000000000000000 at monotonic time: 12450857 msec
[1640858187.954024][169046:169055] CHIP:IN: Message appended to BLE send queue
[1640858187.954036][169046:169055] CHIP:SC: Sent PBKDF param request
[1640858187.954044][169046:169055] CHIP:CTL: SyncSetKeyValue on StartKeyID
[1640858187.954050][169046:169055] CHIP:CTL: Network commissioning parameters are required for BLE auto commissioning.
CHIP Error 0x0000002F: Invalid argument
[1640858187.965744][169046:169053] CHIP:BLE: BLE removing known devices.
[1640858187.970559][169046:169053] CHIP:BLE: BLE initiating scan.
[1640858188.116159][169046:169053] CHIP:BLE: Device 00:A0:50:89:78:D8 does not look like a CHIP device.
[1640858188.194762][169046:169053] CHIP:BLE: New device scanned: EA:EB:96:08:40:63
[1640858188.194807][169046:169053] CHIP:BLE: Device discriminator match. Attempting to connect.
[1640858188.202435][169046:169053] CHIP:BLE: Scan complete notification without an active scan.
[1640858189.553443][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553456][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553474][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0001
[1640858189.553476][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553478][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0001
[1640858189.553480][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553483][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0001
[1640858189.553485][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553491][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0001
[1640858189.553495][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553499][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0001
[1640858189.553502][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553504][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0001
[1640858189.553507][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553515][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0001
[1640858189.553517][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553521][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0001
[1640858189.553523][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553527][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0001
[1640858189.553529][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553532][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553535][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553538][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553540][169046:169053] CHIP:DL: Char1 /org/bluez/hci0/dev_EA_EB_96_08_40_63/service0010
[1640858189.553546][169046:169053] CHIP:DL: New BLE connection 0x7f820c06efe0, device EA:EB:96:08:40:63, path /org/bluez/hci0/dev_EA_EB_96_08_40_63
[1640858189.553595][169046:169055] CHIP:DL: HandlePlatformSpecificBLEEvent 16385
[1640858189.553611][169046:169055] CHIP:IN: BleConnectionComplete: endPoint 0x7f82182f1960
[1640858190.272740][169046:169053] CHIP:DL: Bluez disconnected
[1640858190.272791][169046:169053] CHIP:DL: Bluez notify CHIPoBluez connection disconnected
**[1640858190.273056][169046:169055] CHIP:IN: Failed to establish BLE connection: ../../../../../src/platform/Linux/BLEManagerImpl.cpp:546: Ble Error 0x0000040C: Remote device closed BLE connection**
[1640858190.273067][169046:169055] CHIP:IN: Clearing BLE pending packets.
[1640858190.273094][169046:169055] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1640858190.273126][169046:169055] CHIP:BLE: no endpoint for BLE sent data ack
**[1640858973.283250][183884:183890] CHIP:SC: PASESession timed out while waiting for a response from the peer. Expected message type was 33**
[1640858973.283313][183884:183890] CHIP:CTL: RendezvousCleanup
[1640858973.283360][183884:183890] CHIP:CTL: SyncSetKeyValue on StartKeyID
Failed to establish secure session to device: 50

2. Turn on HCI adapter back and try to connect again:

> chip-device-ctrl > connect -ble 3840 20202021 1
Device is assigned with nodeid = 1
[1640858481.638231][173015:173021] CHIP:SC: Assigned local session key ID 2
[1640858481.638340][173015:173021] CHIP:SC: Including MRP parameters in PBKDF param request
[1640858481.638438][173015:173021] CHIP:IN: Prepared plaintext message 0x7f17f37fc930 to 0x0000000000000000 (0)  of type 0x20 and protocolId (0, 0) on exchange 53915i with MessageCounter:4053720663.
[1640858481.638505][173015:173021] CHIP:IN: Sending plaintext msg 0x7f17f37fc930 with MessageCounter:4053720663 to 0x0000000000000000 at monotonic time: 12744541 msec
**CHIP Error 0x00000003: Incorrect state**
[1640858481.658111][173015:173019] CHIP:BLE: BLE removing known devices.
[1640858481.666520][173015:173019] CHIP:BLE: BLE initiating scan.
[1640858482.111953][173015:173019] CHIP:BLE: Device 00:A0:50:89:78:D8 does not look like a CHIP device.
[1640858482.178057][173015:173019] CHIP:BLE: New device scanned: D8:8C:80:45:96:46
[1640858482.178101][173015:173019] CHIP:BLE: Device discriminator match. Attempting to connect.
[1640858482.203648][173015:173019] CHIP:BLE: Scan complete notification without an active scan.
[1640858482.537096][173015:173019] CHIP:DL: ConnectDeviceDone
[1640858482.537158][173015:173019] CHIP:DL: ConnectDevice complete
[1640858482.867439][173015:173019] CHIP:DL: Char1 /org/bluez/hci0/dev_D8_8C_80_45_96_46/service0010
[1640858482.867455][173015:173019] CHIP:DL: Char1 /org/bluez/hci0/dev_D8_8C_80_45_96_46/service0010
[1640858482.867462][173015:173019] CHIP:DL: Char1 /org/bluez/hci0/dev_D8_8C_80_45_96_46/service0010
[1640858482.867466][173015:173019] CHIP:DL: Char1 /org/bluez/hci0/dev_D8_8C_80_45_96_46/service0010
[1640858482.867475][173015:173019] CHIP:DL: Char1 /org/bluez/hci0/dev_D8_8C_80_45_96_46/service0001
[1640858482.867478][173015:173019] CHIP:DL: Char1 /org/bluez/hci0/dev_D8_8C_80_45_96_46/service0010
[1640858482.867483][173015:173019] CHIP:DL: Char1 /org/bluez/hci0/dev_D8_8C_80_45_96_46/service0001
[1640858482.867486][173015:173019] CHIP:DL: Char1 /org/bluez/hci0/dev_D8_8C_80_45_96_46/service0010
[1640858482.867490][173015:173019] CHIP:DL: Char1 /org/bluez/hci0/dev_D8_8C_80_45_96_46/service0001
[1640858482.867496][173015:173019] CHIP:DL: Char1 /org/bluez/hci0/dev_D8_8C_80_45_96_46/service0010
[1640858482.867510][173015:173019] CHIP:DL: Char1 /org/bluez/hci0/dev_D8_8C_80_45_96_46/service0010
[1640858482.867515][173015:173019] CHIP:DL: Char1 /org/bluez/hci0/dev_D8_8C_80_45_96_46/service0010
[1640858482.867524][173015:173019] CHIP:DL: New BLE connection 0x7f17e8046da0, device D8:8C:80:45:96:46, path /org/bluez/hci0/dev_D8_8C_80_45_96_46
[1640858482.867622][173015:173021] CHIP:DL: HandlePlatformSpecificBLEEvent 16385
[1640858482.867640][173015:173021] CHIP:IN: BleConnectionComplete: endPoint 0x7f17fa424960
[1640858483.300957][173015:173021] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1640858483.392387][173015:173021] CHIP:DL: HandlePlatformSpecificBLEEvent 16388
[1640858483.392452][173015:173021] CHIP:BLE: subscribe complete, ep = 0x7f17fa424960
[1640858483.393212][173015:173019] CHIP:DL: Indication received, conn = 0x7f17e8046da0
[1640858483.393352][173015:173021] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1640858483.393398][173015:173021] CHIP:BLE: peripheral chose BTP version 4; central expected between 4 and 4
[1640858483.393436][173015:173021] CHIP:BLE: using BTP fragment sizes rx 244 / tx 244.
[1640858483.393449][173015:173021] CHIP:BLE: local and remote recv window size = 5
[1640858483.393500][173015:173021] CHIP:IN: BLE EndPoint 0x7f17fa424960 Connection Complete
[1640858485.955707][173015:173021] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1640858488.431745][173015:173019] CHIP:DL: Indication received, conn = 0x7f17e8046da0
[1640858488.431938][173015:173021] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1640858490.965941][173015:173021] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1640858493.472460][173015:173019] CHIP:DL: Indication received, conn = 0x7f17e8046da0
[1640858493.472666][173015:173021] CHIP:DL: HandlePlatformSpecificBLEEvent 16389

The incorrect state error is a result of setting BLE `kConnected` state: https://github.com/project-chip/connectedhomeip/blob/master/src/transport/raw/BLE.cpp#L161 and not cleaning it back if the BLE connection will fail: https://github.com/project-chip/connectedhomeip/blob/master/src/transport/raw/BLE.cpp#L165.

On the next try application will fall here assuming it is connected to some device: https://github.com/project-chip/connectedhomeip/blob/master/src/transport/raw/BLE.cpp#L95 and then fail with incorrect state.

Moreover the early fail results in cancelling PASE timeout timer, so it will not come to clean initialized rendezvous data.

3. Close BLE and try to connect again:

> chip-device-ctrl > connect -ble 3840 20202021 1
Device is assigned with nodeid = 1
**CHIP Error 0x00000003: Incorrect state**

And that fails because of not cleaned rendezvous data verified in this check: https://github.com/project-chip/connectedhomeip/blob/master/src/controller/CHIPDeviceController.cpp#L785

 #### Proposed Solution
To be able to perform many commissioning attempts both BLE and rendezvous data need to be reset to the initial state after every failure. For rendezvous data PASE timeout timer takes care of that and in the BLE case those are some error callbacks. Bring BLE state to the `kInitialized` state after connection failure and make sure that rendezvous data are cleared after each PASE session establishment failure.

### PR DESCRIPTION
**Pull request by kkasperczyk-no**
#### Problem
Sometimes it happens that if in specific moment of device commissioning over Bluetooth LE the connection will be closed
(e.g. by turning off HCI adapter to simulate hardware problems) the controller is not able to commission the device on the second attempt due to incorrect state. See https://github.com/project-chip/connectedhomeip/issues/13286 for more details.

#### Change overview
* Added setting BLE state to kInitialized if BLE connection establishment failed.
* Added cleaning rendezvous data if some PASE establisment error appeared.

#### Testing
Verified with Python CHIP controller and nrfconnect lock-app example that it is possible to attempt several commissioning attempts after breaking BLE connection during communication by turning off Bluetooth HCI adapter.

Fixes: https://github.com/project-chip/connectedhomeip/issues/13286

### CODE REVIEW

**Review by msandstedt — APPROVED** [review]

File: src/transport/raw/BLE.cpp [hunk 1]
```diff
@@ -163,6 +163,8 @@ void BLEBase::OnEndPointConnectComplete(BLEEndPoint * endPoint, CHIP_ERROR err)
     if (err != CHIP_NO_ERROR)
     {
         ChipLogError(Inet, "Failed to establish BLE connection: %s", ErrorStr(err));
+        mState       = State::kInitialized;
```
Comment (hrajendran-samsung) [inline src/transport/raw/BLE.cpp:166]: Minor- It might be more prudent instead to simply call OnEndPointConnectionClosed() instead of lines 166-168. Should reduce duplicity.
```suggestion
        OnEndPointConnectionClosed();
```

File: src/transport/raw/BLE.cpp [hunk 2]
```diff
@@ -163,6 +163,8 @@ void BLEBase::OnEndPointConnectComplete(BLEEndPoint * endPoint, CHIP_ERROR err)
...
+        mBleEndPoint = nullptr;
         ClearPendingPackets();
```
Comment (hrajendran-samsung) [inline src/transport/raw/BLE.cpp:168]: Minor- It might be more prudent instead to simply call OnEndPointConnectionClosed() instead of lines 166-168. Should reduce duplicity.
```suggestion
        OnEndPointConnectionClosed();
```

Comment (hrajendran-samsung) [inline src/transport/raw/BLE.cpp:168]: Minor- It might be more prudent instead to simply call OnEndPointConnectionClosed() instead of lines 166-168. Should reduce duplicity.
```suggestion
        OnEndPointConnectionClosed();
```

**Review by jmartinez-silabs — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]

**Review by Damian-Nordic — APPROVED** [review]
