### PR TITLE
Fix CASE Churn caused by subscriptions on tv

### LINKED ISSUE #23618: [BUG] CASE Session churn on tv-app subscriptions
### Reproduction steps

```bash
1. Start linux tv-app
2. Start linux tv-casting-app
3. Commission tv-casting-app from tv-app
4. tv-casting-app subscriptions will case CASE session to get re-established every ReportData interval
...

Issue 1:
The subscription's ReportData was being sent on the ExchangeMgr tied to the static instance of the InteractionModel. Since tv-app is both a server and a controller, it has 2 ExchangeMgr's and so the one tied to the InterctionModel will not always be correct.

Issue 2:
When the tv-casting-app creates more than one subscription, the second one was killing the first since the KeepSubscriptions param on the subscription creation command was taking its default value of false.
```

### Bug prevalence

always

### GitHub hash of the SDK that was being used

master

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chrisdecenzo**
Fixes #23618 : CASE session churn observed when tv-casting-app creates subscriptions on tv-app.

1. The subscription's ReportData was being sent on the ExchangeMgr tied to the static instance of the InteractionModel. Since tv-app is both a server and a controller, it has 2 ExchangeMgr's and so the one tied to the InterctionModel will not always be correct. 

The fix here is to grab a reference to the ExchangeMgr used to create the subscription's ReadHandler and use that one to send the ReportData

2. When the tv-casting-app creates more than one subscription, the second one was killing the first since the KeepSubscriptions param on the subscription creation command was taking its default value of false.

The fix here is to set this optional param to true.

### CODE REVIEW

**Review by sharadb-amazon — APPROVED** [review]

File: src/app/ReadHandler.cpp [hunk 1]
```diff
@@ -46,6 +46,7 @@ ReadHandler::ReadHandler(ManagementCallback & apCallback, Messaging::ExchangeCon
     VerifyOrDie(apExchangeContext != nullptr);
 
     mExchangeCtx.Grab(apExchangeContext);
+    mExchangeMgr = apExchangeContext->GetExchangeMgr();
```
Comment (bzbarsky-apple) [inline src/app/ReadHandler.cpp:49]: Apart from the extra memory use imposed on all consumers to handle this weird case when someone created multiple meant-to-be-singleton exchange managers... what keeps this pointer from dangling?  Getting things off the IM engine is safe, because the IM engine shuts down all ReadHandlers if it shuts down (though I suspect we can still end up with message dispatch from the "wrong" exchange manager to the IM engine after the latter is shut down).  But if we have some random other exchange manager, it could go away and this code would never know, then we get use-after-free.

**Review by bzbarsky-apple — DISMISSED** [review]

File: examples/tv-casting-app/tv-casting-common/include/MediaSubscriptionBase.h [hunk 2]
```diff
@@ -39,6 +39,6 @@ class MediaSubscriptionBase : public MediaBase
                                  mTvEndpoint);
 
         return cluster.template SubscribeAttribute<TypeInfo>(context, successFn, failureFn, minInterval, maxInterval,
-                                                             onSubscriptionEstablished);
+                                                             onSubscriptionEstablished, nullptr, true, true);
```
[the remark this answers is not in the document]
Comment (chrisdecenzo) [reply examples/tv-casting-app/tv-casting-common/include/MediaSubscriptionBase.h]: added comments

File: src/app/ReadHandler.cpp [hunk 3]
```diff
@@ -46,6 +46,11 @@ ReadHandler::ReadHandler(ManagementCallback & apCallback, Messaging::ExchangeCon
     VerifyOrDie(apExchangeContext != nullptr);
 
     mExchangeCtx.Grab(apExchangeContext);
+#if CHIP_DEVICE_CONFIG_ENABLE_BOTH_COMMISSIONER_AND_COMMISSIONEE
```
Comment (bzbarsky-apple) [inline src/app/ReadHandler.cpp:49]: Ideally this would use a different define, which makes it clear that this is temporary and not a permanent feature of the "commissioner and commissioneee" configuration.

Comment (chrisdecenzo) [reply src/app/ReadHandler.cpp:49]: the underlying issue is also cited in the comment

Comment (bzbarsky-apple) [reply src/app/ReadHandler.cpp:49]: Just to repeat: please make this a separate config value, one which makes it clear that the behavior being opted in to may have security implications.

Comment (bzbarsky-apple) [reply src/app/ReadHandler.cpp:49]: @chrisdecenzo And concretely, how about `CHIP_CONFIG_UNSAFE_SUBSCRIPTION_EXCHANGE_MANAGER_USE` for the define?

**Review by andy31415 — APPROVED** [review]

**Review by mrjerryjohns — CHANGES_REQUESTED** [review]
Our stack is not at all built to deal with multiple instances of canonical singletons like ExchangeMgr, and a patch like this gives the semblance of fixing the problem, when in fact, the problem is much deeper.

ReadHandler adopting the ExchangeMgr alone is insufficient, since there are plenty of complex interactions that go through InteractionModelEngine and the ReportingEngine that results in them accessing again the ExchangeMgr instance behind the InteractionModelEngine.

The correct fix is one of two possibilities:
1. Fix the stack to do away with the singleton nature of these entities, and permit true multi-instancing of the core state of the stack (not at all trivial).
2. Live with the current constraints, and to achieve dual server/client modality, you _dont need_ to instantiate multiple instances of these singletons. That is the approach most people have adopted (including us at Google).

**Review by mrjerryjohns — APPROVED** [review]
Approving to unblock Chris in the short term, since he's committing to working on exploring a fix that involves running commissioner/server using a single instance of the singletons.

**Review by lazarkov — APPROVED** [review]
