### PR TITLE
Do a mDNS advertisement on minmdns server startup

### LINKED ISSUE #4853: mDNS appears broken on ESP32 after #4132
#### Problem

I'm not seeing any mDNS advertisements after #4132

Repro:

Run `dns-sd -B _chip._tcp`
Provision ESP32

Expected output:

mDNS "Add" reported once ESP32 joins network

Actual output:

Nothing

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
Devices should advertise that they exist at boot time, so that passive listeners can see such devices. 

This is especially useful on commisioning devices (new devices appear) as well as in case IP address changes.

 #### Summary of Changes

- IPv4 listen on all inteerfaces (instead of NULL interface id)
- at ::Start, do a mdns advertise of all PTR entries (which will recursively send SRV and A/AAAA records)

 Note that this is not fully RFC compliant (RFC requires a re-advertisement after 10s). It just makes things more functional.

Fixes #4853

### CODE REVIEW

File: src/lib/mdns/Advertiser_ImplMinimalMdns.cpp [hunk 1]
```diff
@@ -569,6 +584,114 @@ FullQName AdvertiserMinMdns::GetCommisioningTextEntries(const CommissionAdvertis
...
+    {
+        return false;
+    }
+
+    if (!current.SupportsMulticast())
+    {
+        return false;
+    }
+
+    char name[64];
```
Comment (msandstedt) [inline src/lib/mdns/Advertiser_ImplMinimalMdns.cpp:599]: Can we perhaps size this intelligently to `IF_NAMESIZE`?  It seems like that would be preferable to hard-coding a constant that will either be needlessly large, or unexpectedly fail at runtime on some exotic target.

Comment (msandstedt) [reply src/lib/mdns/Advertiser_ImplMinimalMdns.cpp:599]: It looks like in Zephyr this can be up to `Z_DEVICE_MAX_NAME_LEN` characters.  To avoid use of this inline constant (which I still advocate we avoid), some sort of platform-mapped macro might be needed.

**Review by msandstedt — APPROVED** [review]

**Comment by andy31415** [comment]
@woody-apple @mspang @jelderton @saurabhst @hawk248 ?

**Review by woody-apple — APPROVED** [review]
Looks great, thank you!

File: src/lib/mdns/Advertiser_ImplMinimalMdns.cpp [hunk 2]
```diff
@@ -209,6 +212,15 @@ class AdvertiserMinMdns : public ServiceAdvertiser,
     /// allocated memory.
     void Clear();
 
+    /// Advertise availabe records configured within the server
```
Comment (bzbarsky-apple) [inline src/lib/mdns/Advertiser_ImplMinimalMdns.cpp:215]:
```suggestion
    /// Advertise available records configured within the server
```

File: src/lib/mdns/Advertiser_ImplMinimalMdns.cpp [hunk 3]
```diff
@@ -569,6 +584,114 @@ FullQName AdvertiserMinMdns::GetCommisioningTextEntries(const CommissionAdvertis
...
+    {
+        ChipLogError(Discovery, "Failed to get interface name - will not advertise on this interface");
+        return false;
+    }
+
+    if (strncmp(name, "lo", 2) == 0)
+    {
+        // Skip advertisement on what looks like a local loopback interface
+        return false;
+    }
```
Comment (bzbarsky-apple) [inline src/lib/mdns/Advertiser_ImplMinimalMdns.cpp:610]: We have this logic duplicated in a few places.  I know these are different iterator classes, but it might be worth having a template function to coalesce the logic even if it won't actually share the code in practice...

File: src/lib/mdns/Advertiser_ImplMinimalMdns.cpp [hunk 4]
```diff
@@ -569,6 +584,114 @@ FullQName AdvertiserMinMdns::GetCommisioningTextEntries(const CommissionAdvertis
...
+
+        packetInfo.Clear();
+        packetInfo.SrcAddress = interfaceAddress.GetAddress();
+        if (interfaceAddress.GetAddress().IsIPv4())
+        {
+            chip::Inet::IPAddress::FromString("224.0.0.251", packetInfo.DestAddress);
+        }
+        else
+        {
+            chip::Inet::IPAddress::FromString("FF02::FB", packetInfo.DestAddress);
```
Comment (bzbarsky-apple) [inline src/lib/mdns/Advertiser_ImplMinimalMdns.cpp:673]: Worth adding a comment that this is the mDNS multicast address.  Or defining some constants, like `kMdnsPort`, for these strings.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/lib/mdns/Advertiser_ImplMinimalMdns.cpp (hunk 3 above)
Comment (andy31415) [reply src/lib/mdns/Advertiser_ImplMinimalMdns.cpp]: Deduplicated within this file only for now - hard to use templates because even thoug the methods are identical (is up, isMulticast, getinterfacename) the iterator types are different.

Comment (bzbarsky-apple) [reply src/lib/mdns/Advertiser_ImplMinimalMdns.cpp]: Right, I just meant within this file...

File: src/lib/mdns/Advertiser_ImplMinimalMdns.cpp (hunk 4 above)
Comment (andy31415) [reply src/lib/mdns/Advertiser_ImplMinimalMdns.cpp]: Removed some duplication for this and comment on the class hopefully works.

File: src/lib/mdns/minimal/Server.h [hunk 5]
```diff
@@ -28,6 +28,20 @@
...
+    chip::Inet::IPAddress ipv6;
+    chip::Inet::IPAddress ipv4;
+
+    BroadcastIpAddresses()
+    {
+        chip::Inet::IPAddress::FromString("FF02::FB", ipv6);
+        chip::Inet::IPAddress::FromString("224.0.0.251", ipv4);
+    }
+};
+extern const BroadcastIpAddresses kBroadcastIpAddresses;
```
Comment (mspang) [inline src/lib/mdns/minimal/Server.h:43]: Please don't do this. BroadcastIpAddresses() isn't constexpr, this is going to generate a static initializer that parses a string which will run in the initial thread before anything else happens in the program. It's a source of performance problems, and also defeats feature toggles in the sense that we'll be forced to spend runtime initializing parts of CHIP at runtime by merely linking the code into the program.

File: src/lib/mdns/minimal/responders/QueryResponder.h [hunk 6]
```diff
@@ -266,6 +266,10 @@ class QueryResponderBase : public Responder // "_services._dns-sd._udp.local"
     /// Flag any additional responses required for the given iterator
     void MarkAdditionalRepliesFor(QueryResponderIterator it);
 
+    /// Resets the internal broadcast throttle setting to allow re-broadcasting
+    /// of all packets without a timedelay.
+    void ClearBroadcastTrottle();
```
Comment (mspang) [inline src/lib/mdns/minimal/responders/QueryResponder.h:271]: typo: Trottle -> Throttle

File: src/lib/mdns/minimal/QueryReplyFilter.h [hunk 7]
```diff
@@ -59,9 +57,41 @@ class QueryReplyFilter : public ReplyFilter
...
+    QueryReplyFilter & SetSendingAdditionalItems(bool additional)
+    {
+        mSendingAdditionalItems = additional;
+        return *this;
+    }
+
 private:
+    bool AcceptableQueryType(QType qType)
+    {
+        if (mSendingAdditionalItems && mQueryData.IsBootAdvertising())
```
Comment (mspang) [inline src/lib/mdns/minimal/QueryReplyFilter.h:69]: Is this check needed (isn't the 2nd condition true already?)

File: src/lib/mdns/minimal/QueryReplyFilter.h [hunk 8]
```diff
@@ -59,9 +57,41 @@ class QueryReplyFilter : public ReplyFilter
...
+    }
+
+    bool AcceptableQueryClass(QClass qClass)
+    {
+        return ((mQueryData.GetClass() == QClass::ANY) || (mQueryData.GetClass() == qClass));
+    }
+
+    bool AcceptablePath(FullQName qname)
+    {
+        if (mIgnoreNameMatch || mQueryData.IsBootAdvertising())
```
Comment (mspang) [inline src/lib/mdns/minimal/QueryReplyFilter.h:84]: Why do we need IsBootAdvertising instead of just using IgnoreNameMatch ?

File: src/lib/mdns/Advertiser_ImplMinimalMdns.cpp [hunk 9]
```diff
@@ -86,35 +86,58 @@ void LogQuery(const QueryData & data)
...
+        return false; // not a usable interface
+    }
+    char name[chip::Inet::InterfaceIterator::kMaxIfNameLength];
+    if (iterator.GetInterfaceName(name, sizeof(name)) != CHIP_NO_ERROR)
+    {
+        ChipLogError(Discovery, "Failed to get interface name.");
+        return false;
+    }
+
+    if (strncmp(name, "lo", 2) == 0)
```
Comment (mspang) [inline src/lib/mdns/Advertiser_ImplMinimalMdns.cpp:105]: Not a new issue, but doesn't seem right that if I rename my interface to "lollipop" it will be skipped.

Probably the name is the wrong thing to look at altogether, and we should just inspect the address.

File: src/lib/mdns/minimal/QueryReplyFilter.h (hunk 7 above)
Comment (andy31415) [reply src/lib/mdns/minimal/QueryReplyFilter.h:69]: IsBootAdvertising is only set during initial boot, not during normal query replies, where as 'sending additional items'  is set for any reply processing. I believe they are both needed.

**Review by mspang — APPROVED** [review]

File: src/lib/mdns/minimal/QueryReplyFilter.h (hunk 8 above)
Comment (andy31415) [reply src/lib/mdns/minimal/QueryReplyFilter.h:84]: It seemed to make the intent cleaner by having behaviour depend on query.

The boot-time broadcaster builds a fake query (so that the sender sends replies to such a query) however it does not have access to the underlying filtering used by the mDNS sender.

Alternative would be to propagate flags into the mdns sending and that seeemed to be a bit uglier.

File: src/lib/mdns/Advertiser_ImplMinimalMdns.cpp (hunk 9 above)
Comment (andy31415) [reply src/lib/mdns/Advertiser_ImplMinimalMdns.cpp:105]: I could find no better way.

For devices this may not be an issue (since they control their wifi name and it is likely LWIP anyway). Would people rename interfaces on android/iOS?

Added a TODO to auto-create an issue.

Comment (mspang) [reply src/lib/mdns/Advertiser_ImplMinimalMdns.cpp:113]: Can't you just get the address and see if it's ::1 or inside 127.0.0.0/8 ?

Comment (andy31415) [reply src/lib/mdns/Advertiser_ImplMinimalMdns.cpp:113]: InterfaceIterator does not provide the address only InterfaceAddressIterator does. 

Absolutely possible to use AddressIterator instead and do some dedup, but I find it more bothersome than what I would be generally add as a 'fix if you are already touching this'.

Comment (andy31415) [reply src/lib/mdns/Advertiser_ImplMinimalMdns.cpp:113]: Real fix would probably to fix the interface iterator to be able to return an address iterator for that specified interface. Having 2 types of iterators that both iterate over all interfaces is strange.
