### PR TITLE
DNS-SD: Implement browse retries for avahi

### LINKED ISSUE #28718: [BUG] Avahi browse doesn't appear to be doing anything for MOST of the timeout period
### Reproduction steps

See https://github.com/CHIP-Specifications/chip-test-scripts/issues/596

### Bug prevalence

happens mostly on thread, think we can repro by starting discovery before the device comes up

### GitHub hash of the SDK that was being used

https://github.com/CHIP-Specifications/chip-test-scripts/issues/596

### Platform

other

### Platform Version(s)

All avahi

### Anything else?

Need to make sure we conform to the retry specifications in the mdns rfc to avoid flooding the network.

### PR DESCRIPTION
**Pull request by cecille**
The current avahi implementation uses a one-shot browse that completes
in approximately one second. This is insufficient for thread devices
that need time to propagage SRP messages through the BR. The majority
of the dnssd timeout is unused. This implements a browse retry with
backoff and also implements the StopBrowse function.

Test: chip-tool pairing started before app, now works. StopBrowse
      is checked in the TestDnssd platform tests.

Fixes: https://github.com/project-chip/connectedhomeip/issues/28718

### CODE REVIEW

File: src/platform/Linux/DnssdImpl.cpp [hunk 1]
```diff
@@ -662,6 +685,26 @@ void CopyTypeWithoutProtocol(char (&dest)[N], const char * typeAndProtocol)
     }
 }
 
+void MdnsAvahi::BrowseRetryCallback(chip::System::Layer * aLayer, void * appState)
+{
+    BrowseContext * context = static_cast<BrowseContext *>(appState);
+    // Don't schedule anything new if we've stopped.
+    if (context->mStopped.load())
+    {
+        return;
```
Comment (andy31415) [inline src/platform/Linux/DnssdImpl.cpp:694]: How is `context` deleted if a browser is not created (since it seems to me like AVAHI_BROWSER_ALL_FOR_NOW handler is the one that deletes the context)

maybe we should have:

```cpp
AvahiServiceBrowser * newBrowser = nullptr;
if (!context->mStopped.load())
{
   newBrowser = avahi_service_browser_new(  /* */ );
}

if (newBrowser == nullptr)
{
   // ...
}
```

Comment (cecille) [reply src/platform/Linux/DnssdImpl.cpp:695]: Added a fix and some comments. Cancelling the timer was also an issue.

**Review by andy31415 — APPROVED** [review]
