### PR TITLE
Fix Session ID Allocation

### LINKED ISSUE #7835: - Update SessionID allocator to use freed session IDs
https://github.com/project-chip/connectedhomeip/blob/6c1f43ac3b90ea014fd499e0817ae3be34025a7e/src/protocols/secure_channel/SessionIDAllocator.cpp#L29-L39

---

###### This issue was generated by [todo](https://todo.jasonet.co) based on a `TODO` comment in 6c1f43ac3b90ea014fd499e0817ae3be34025a7e when #7666 was merged. cc @pan-apple.

### PR DESCRIPTION
**Pull request by msandstedt**
Secure session ID allocation currently suffers the following problems:

* fragmentation has worst case behavior where there may be as few as
  2 outstanding sessions, but the allocator will become full
* there is no formal coupling to the session manager object, but
  yet there can only be one allocator per session manager; the
  current solution is for the allocator to share static state
* IDs are proposed *to* the session manager, which means the session
  manager can only prevent collisions by failing on session creation
  or by evicting sessions; it currently does the latter
* session ID allocation is manual, so leaks are likely

This commit solves these problems by moving ID allocation into the
session manager and by leveraging the session table itself as the
source of truth for available IDs.  Whereas the old flow was:

* allocate session ID
* initiate PASE or CASE
* (on success) allocate session table entry

The new flow is:

* allocate session table entry with non-colliding ID
* initiate PASE or CASE
* activate the session in the table

Allocation uses a next-session-ID clue, which is 1 more than the most
recent allocation, and also searches the session table to make sure
a non-colliding value is returned.  Allocation time complexity is
O(kMaxSessionCount^2/64) in the current implementation.

Lifecycle of the pending session table entries also leverages the
SessionHolder object to alleviate our need to manually free resources.

Fixes: #7835, #12821

Testing:

* Added an allocation test to TestSessionManager
* All other code paths are heavily integrated into existing tests
* All existing unit tests pass

### CODE REVIEW

File: src/protocols/secure_channel/CASESession.cpp [hunk 1]
```diff
@@ -187,18 +187,18 @@ CHIP_ERROR CASESession::FromCachable(const CASESessionCachable & cachableSession
     return CHIP_NO_ERROR;
 }
 
-CHIP_ERROR CASESession::Init(uint16_t localSessionId, SessionEstablishmentDelegate * delegate)
+CHIP_ERROR CASESession::Init(SessionHolder & secureSessionHolder, SessionEstablishmentDelegate * delegate)
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:190]: Should this take `SessionHolder &&`?  Conceptually the consumer is handing over ownership of the session to this class, right?

File: src/protocols/secure_channel/CASESession.cpp [hunk 2]
```diff
@@ -208,11 +208,12 @@ CHIP_ERROR CASESession::Init(uint16_t localSessionId, SessionEstablishmentDelega
 }
 
 CHIP_ERROR
-CASESession::ListenForSessionEstablishment(uint16_t localSessionId, FabricTable * fabrics, SessionEstablishmentDelegate * delegate,
+CASESession::ListenForSessionEstablishment(SessionHolder & secureSessionHolder, FabricTable * fabrics,
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:211]: Again, should probably be `SessionHolder &&`.

File: src/protocols/secure_channel/CASESession.cpp [hunk 3]
```diff
@@ -225,7 +226,7 @@ CASESession::ListenForSessionEstablishment(uint16_t localSessionId, FabricTable
 }
 
 CHIP_ERROR CASESession::EstablishSession(const Transport::PeerAddress peerAddress, FabricInfo * fabric, NodeId peerNodeId,
-                                         uint16_t localSessionId, ExchangeContext * exchangeCtxt,
+                                         SessionHolder & secureSessionHolder, ExchangeContext * exchangeCtxt,
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/CASESession.cpp:229]: `SessionHolder &&`

File: src/protocols/secure_channel/PASESession.cpp [hunk 4]
```diff
@@ -117,75 +117,10 @@ void PASESession::DiscardExchange()
...
-    memcpy(mKe, serializable.mKe, mKeLen);
-
-    SetLocalSessionId(serializable.mLocalSessionId);
-    SetPeerSessionId(serializable.mPeerSessionId);
-
-    return CHIP_NO_ERROR;
-}
-
-CHIP_ERROR PASESession::Init(uint16_t mySessionId, uint32_t setupCode, SessionEstablishmentDelegate * delegate)
+CHIP_ERROR PASESession::Init(SessionHolder & secureSessionHolder, uint32_t setupCode, SessionEstablishmentDelegate * delegate)
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/PASESession.cpp:120]: Similar to CASESession: should be using rvalues where semantically we're taking ownership of the session holder, various places in this file.

File: src/transport/PairingSession.h [hunk 5]
```diff
@@ -50,11 +50,18 @@ class DLL_EXPORT PairingSession
...
 
-    // TODO: the local key id should be allocateed at start
-    // mLocalSessionId should be const and assigned at the construction, such that GetLocalSessionId will always return a valid key
-    // id , and SetLocalSessionId is not necessary.
-    uint16_t GetLocalSessionId() const { return mLocalSessionId; }
-    bool IsValidLocalSessionId() const { return mLocalSessionId != kInvalidKeyId; }
+    Optional<uint16_t> GetLocalSessionId() const
+    {
+        Optional<uint16_t> localSessionId;
+        VerifyOrExit(mSecureSessionHolder, localSessionId = Optional<uint16_t>::Missing());
```
Comment (bzbarsky-apple) [inline src/transport/PairingSession.h:56]:
```suggestion
        VerifyOrExit(mSecureSessionHolder, localSessionId = NullOptional);
```
is shorter...  but also, it's set to that already, by the Optional constructor.  Either way, though.

File: src/transport/PairingSession.h [hunk 6]
```diff
@@ -50,11 +50,18 @@ class DLL_EXPORT PairingSession
...
+        VerifyOrExit(mSecureSessionHolder->GetSessionType() == Transport::Session::SessionType::kSecure,
+                     localSessionId = Optional<uint16_t>::Missing());
+        localSessionId.SetValue(mSecureSessionHolder->AsSecureSession()->GetLocalSessionId());
+    exit:
+        return localSessionId;
+    }
+
+    SessionHolder & GetSecureSessionHolder() { return mSecureSessionHolder; }
```
Comment (bzbarsky-apple) [inline src/transport/PairingSession.h:64]:
```suggestion
    const SessionHolder & GetSecureSessionHolder() const { return mSecureSessionHolder; }
```

File: src/transport/PairingSession.h [hunk 7]
```diff
@@ -97,7 +104,7 @@ class DLL_EXPORT PairingSession
     void SetPeerNodeId(NodeId peerNodeId) { mPeerNodeId = peerNodeId; }
     void SetPeerCATs(CATValues peerCATs) { mPeerCATs = peerCATs; }
     void SetPeerSessionId(uint16_t id) { mPeerSessionId.SetValue(id); }
-    void SetLocalSessionId(uint16_t id) { mLocalSessionId = id; }
+    void SetSecureSessionHolder(SessionHolder & holder) { mSecureSessionHolder = holder; }
```
Comment (bzbarsky-apple) [inline src/transport/PairingSession.h:107]: Again, should this be taking an rvalue and named something like `TakeSecureSession` or something?

File: src/transport/SecureSession.h [hunk 8]
```diff
@@ -71,6 +79,32 @@ class SecureSession : public Session
     {
         SetFabricIndex(fabric);
     }
+
+    /**
+     * @brief
+     *   Construct a secure session to associate with a pending secure
+     *   session establishment attempt.  A pending secure session object
+     *   receives a session ID, but no other state.
```
Comment (bzbarsky-apple) [inline src/transport/SecureSession.h:87]:
```suggestion
     *   receives a local session ID, but no other state.
```

File: src/transport/SecureSessionTable.h [hunk 9]
```diff
@@ -69,6 +67,50 @@ class SecureSessionTable
...
 
+    /**
+     * Allocates a new secure session out of the internal resource pool with the
+     * specified session ID.  The returned secure session will not become active
+     * until the call to SecureSession::Activate.
+     *
+     * @returns allocated session on success, else failure
+     */
+    CHECK_RETURN_VALUE
+    Optional<SessionHandle> CreateNewSecureSession(uint16_t localSessionId)
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.h:78]: Is this generally meant for tests?  If so, worth documenting that.

File: src/transport/SecureSessionTable.h [hunk 10]
```diff
@@ -69,6 +67,50 @@ class SecureSessionTable
...
+        rv = MakeOptional<SessionHandle>(*allocated);
+    exit:
+        return rv;
+    }
+
+    /**
+     * Allocates a new secure session out of the internal resource pool with a
+     * non-colliding session ID and increments mNextSessionId to give a clue to
+     * the allocator for the next allocation.  The secure session session will
+     * become active unitl the call to SecureSession::Activate.
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.h:94]:
```suggestion
     * not become active until the call to SecureSession::Activate.
```

File: src/transport/SessionHolder.h [hunk 11]
```diff
@@ -68,6 +68,8 @@ class SessionHolderWithDelegate : public SessionHolder
 {
 public:
     SessionHolderWithDelegate(SessionReleaseDelegate & delegate) : mDelegate(delegate) {}
+    SessionHolderWithDelegate(SessionHolder holder, SessionReleaseDelegate & delegate) : SessionHolder(holder), mDelegate(delegate)
```
Comment (bzbarsky-apple) [inline src/transport/SessionHolder.h:71]: Should this pass by value or by rvalue reference, for the holder param?

File: src/transport/SessionManager.h [hunk 12]
```diff
@@ -168,6 +168,21 @@ class DLL_EXPORT SessionManager : public TransportMgrDelegate
...
+     *   Allocate a secure session and non-colliding session ID in the secure
+     *   session table.
+     */
+    SessionHolder AllocateSession();
+
+    /**
+     * @brief
+     *   Allocate a secure session in the secure session table at the specified
+     *   session ID.  If the session ID collides with an existing session, evict
+     *   it.
```
Comment (bzbarsky-apple) [inline src/transport/SessionManager.h:182]: Again, if this is mostly meant for tests we should document that.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/protocols/secure_channel/CASESession.cpp (hunk 1 above)
Comment (msandstedt) [reply src/protocols/secure_channel/CASESession.cpp:190]: SessionHolder is more like a shared pointer, and the copy and move constructors enforce this.  Everybody who has a reference is an owner, and the code respects that.  The session object can also reach into all holders and release their session reference, so retaining a reference can't break things.

However, in this case, I can't think of a reason a caller would need to retain a reference.  I'll give this a shot.

File: src/transport/SecureSessionTable.h (hunk 9 above)
Comment (msandstedt) [reply src/transport/SecureSessionTable.h:78]: Yes it is.  Thanks for the careful read.  I will add comments.

File: src/transport/SessionManager.h (hunk 12 above)
Comment (msandstedt) [reply src/transport/SessionManager.h]: Done.

File: src/transport/SecureSessionTable.h (hunk 9 above)
Comment (msandstedt) [reply src/transport/SecureSessionTable.h:83]: Done.

File: src/controller/CHIPDeviceController.cpp [hunk 13]
```diff
@@ -677,8 +675,8 @@ CHIP_ERROR DeviceCommissioner::EstablishPASEConnection(NodeId remoteDeviceId, Re
     session = mSystemState->SessionMgr()->CreateUnauthenticatedSession(params.GetPeerAddress(), device->GetMRPConfig());
     VerifyOrExit(session.HasValue(), err = CHIP_ERROR_NO_MEMORY);
 
-    err = mSystemState->SessionIDAlloc()->Allocate(keyID);
-    SuccessOrExit(err);
+    secureSessionHolder = mSystemState->SessionMgr()->AllocateSession();
+    VerifyOrExit(secureSessionHolder, err = CHIP_ERROR_NO_MEMORY);
```
Comment (mrjerryjohns) [inline src/controller/CHIPDeviceController.cpp:679]: Seems like this existing split where the device controller allocates the session, then passes that into `Pair` is a bit un-necessary. We should just do the allocation closer to the logic that actually owns/makes use of that session.

File: src/protocols/secure_channel/CASESession.cpp (hunk 1 above)
Comment (mrjerryjohns) [reply src/protocols/secure_channel/CASESession.cpp:190]: Why even have this model of allocating the session in one place, and then transferring ownership? Why wouldn't we just have `CASESession` allocate the session, instead of having someone else do it?

That would mean exchange allocation would also have to shift into this (which I think is the right pattern, since CASESession effectively manages the state machine and message processing for the CASE protocol, so it should be the one to allocate the EC).

File: src/transport/PairingSession.h [hunk 14]
```diff
@@ -170,18 +177,15 @@ class DLL_EXPORT PairingSession
...
 private:
     const Transport::SecureSession::Type mSecureSessionType;
     NodeId mPeerNodeId = kUndefinedNodeId;
     CATValues mPeerCATs;
 
-    // TODO: the local key id should be allocateed at start
-    // then we can remove kInvalidKeyId
-    static constexpr uint16_t kInvalidKeyId = UINT16_MAX;
-    uint16_t mLocalSessionId                = kInvalidKeyId;
+    SessionHolder mSecureSessionHolder;
```
Comment (mrjerryjohns) [inline src/transport/PairingSession.h:188]: This is just awesome. We now have shifted away from just dangerously holding onto a naked SessionID without a shared ownership model, to one where we now have a legit 'handle' to the session.

**Review by mrjerryjohns — COMMENTED** [review]
All the whole, a really great PR, thank you for clean-ing this up! The ownership model is much better with the fact that you're allocating a session now from SessionManager, and not just a SessionID.

File: src/protocols/secure_channel/CASESession.cpp (hunk 1 above)
Comment (msandstedt) [reply src/protocols/secure_channel/CASESession.cpp:190]: That is even better.  Will do.

Comment (msandstedt) [reply src/protocols/secure_channel/CASESession.cpp]: Done.

File: src/protocols/secure_channel/PASESession.cpp (hunk 4 above)
Comment (msandstedt) [reply src/protocols/secure_channel/PASESession.cpp]: As suggested by @mrjerryjohns , PASESession and CASESession are now doing the allocation themselves, so this doesn't need to be passed in the first place.

File: src/protocols/secure_channel/CASESession.cpp (hunk 3 above)
Comment (msandstedt) [reply src/protocols/secure_channel/CASESession.cpp]: As suggested by @mrjerryjohns , PASESession and CASESession are now doing the allocation themselves, so this doesn't need to be passed in the first place.

File: src/protocols/secure_channel/CASESession.cpp (hunk 2 above)
Comment (msandstedt) [reply src/protocols/secure_channel/CASESession.cpp]: Also superseded.

File: src/controller/CHIPDeviceController.cpp (hunk 13 above)
Comment (msandstedt) [reply src/controller/CHIPDeviceController.cpp]: I absolutely agree and have pushed an update that does this.

File: src/transport/SessionManager.cpp [hunk 15]
```diff
@@ -372,27 +374,49 @@ void SessionManager::ExpireAllPairingsForFabric(FabricIndex fabric)
...
+    }
+    SessionHolder holder;
+    Optional<SessionHandle> session = mSecureSessions.CreateNewSecureSession(sessionId);
+    VerifyOrExit(session.HasValue(), holder = holder);
+    holder.Grab(session.Value());
+exit:
+    return holder;
+}
+
 CHIP_ERROR SessionManager::NewPairing(SessionHolder & sessionHolder, const Optional<Transport::PeerAddress> & peerAddr,
```
Comment (kghost) [inline src/transport/SessionManager.cpp:404]: With the `SessionHolder` retrievable from pairing session, I suggest removing `sessionHolder` argument here, The caller can get it via `pairing->GetSecureSessionHolder()`

**Review by kghost — COMMENTED** [review]
Pretty solid change for session ID allocation implementation.

While reading the code, I feel there are a few improvements we can do in the future:

1. `PairingSession` as a base class for PASE and CASE pairing, almost provides nothing in common for these 2 cases. We can leave `PairingSession` an almost empty virtual interface and push its fields down into `PASESessoin` and `CASESession` classes.
2. Every API of `PairingSession` takes an argument of `SessionManager`, since it is highly coupled with the SessionManager, we can add a ref to SessionManager into its member.

File: src/transport/SessionHolder.h (hunk 11 above)
Comment (msandstedt) [reply src/transport/SessionHolder.h]: Done.

File: src/transport/PairingSession.h [hunk 16]
```diff
@@ -50,11 +50,18 @@ class DLL_EXPORT PairingSession
...
+        Optional<uint16_t> localSessionId;
+        VerifyOrExit(mSecureSessionHolder, localSessionId = NullOptional);
+        VerifyOrExit(mSecureSessionHolder->GetSessionType() == Transport::Session::SessionType::kSecure,
+                     localSessionId = Optional<uint16_t>::Missing());
+        localSessionId.SetValue(mSecureSessionHolder->AsSecureSession()->GetLocalSessionId());
+    exit:
+        return localSessionId;
+    }
+
+    const SessionHolder & GetSecureSessionHolder() const { return mSecureSessionHolder; }
```
Comment (kghost) [inline src/transport/PairingSession.h:64]: I don't think we should expose the internal SessionHolder here. We should return a `SessionHandle` instead.

```
    SessionHandle GetSecureSession() const { return mSecureSessionHolder.Get(); }
```

File: src/transport/SessionManager.cpp (hunk 15 above)
Comment (msandstedt) [reply src/transport/SessionManager.cpp:404]: Would you be OK if I left it as is?  NewPairing was the one interface that survived this refactor.  While you're right that this is sort of redundant, it doesn't hurt anything.  And this delta is already pretty large.

File: src/transport/PairingSession.h (hunk 16 above)
Comment (msandstedt) [reply src/transport/PairingSession.h:64]: Would I still store mSecureSessionHolder internally though?

Comment (msandstedt) [reply src/transport/PairingSession.h:64]: Ah, I am re-reading your comment.  I think I understand now.

File: src/transport/SessionManager.cpp (hunk 15 above)
Comment (kghost) [reply src/transport/SessionManager.cpp:404]: No problem, we can do it later

File: src/transport/PairingSession.h (hunk 16 above)
Comment (msandstedt) [reply src/transport/PairingSession.h]: @kghost , 

I've pushed up the changes.  Let me know if they are satisfactory.

**Review by mrjerryjohns — APPROVED** [review]
