### PR TITLE
Generate lock operation events after lock state has changed

### LINKED ISSUE #26925: [BUG] Door lock server is sending LockOperation events before lock operations are complete
### Reproduction steps

The current implementation of the door lock server is immediately sending out LockOperation events on remote operations (`DoorLockServer::HandleRemoteLockOperation(...)`) before the actual lock action has been completed.

In theory it might be possible to execute the lock operation blocking within `opHandler(...)` but that will block other things as well.

Due to this it is currently impossible to implement the changes necessary for https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6199 as defined there:

> [...] it SHALL generate a LockOperation event with LockOperationType set to Unlatch **when the unlatched state is reached** and a LockOperation event with LockOperationType set to Unlock **when the lock successfully completes** [...]

### Bug prevalence

On every remote lock operation

### GitHub hash of the SDK that was being used

3fdc99cebd11175608ee8691dc443d4bf5871a2e

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mmarc**
Fixes #26925

`fabricIdx` and `nodeId` are now passed to the LockEndpoint so that they can be then later forwarded again back to the `door-lock-server` when updating the lock state.
So now with remote operations (same as with other operations before) the `LockOperationEvent` is generated together with the change of the lock state.
Only exception is if an error occurs (credential/pin error) before the execution. That error will be returned directly to the `HandleRemoteLockOperation` and stored immediately.

### CODE REVIEW

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 1]
```diff
@@ -3428,7 +3435,7 @@ bool DoorLockServer::HandleRemoteLockOperation(chip::app::CommandHandler * comma
     }
 
     // credentials check succeeded, try to lock/unlock door
-    success = opHandler(endpoint, pinCode, reason);
+    success = opHandler(commandObj, endpoint, pinCode, reason);
```
Comment (jrhees-cae) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:3438]: What is the scope of `commandObj`? Here a pointer to commandObj is being passed (and subsequently is passed to the application). BUT, if the application defers the callback to setLockState(...commandObj...) and said callback is made asynchronously later in time, will the pointer to commandObj still be valid? If not, I would suggest perhaps passing the FabricIndex and NodeId values themselves (since this is all that is being used from commandObj anyway).

File: examples/lock-app/lock-common/src/LockEndpoint.cpp [hunk 2]
```diff
@@ -22,25 +22,28 @@
 using chip::to_underlying;
 using chip::app::DataModel::MakeNullable;
 
-bool LockEndpoint::Lock(const Optional<chip::ByteSpan> & pin, OperationErrorEnum & err, OperationSourceEnum opSource)
+bool LockEndpoint::Lock(const chip::app::CommandHandler * commandObj, const Optional<chip::ByteSpan> & pin,
+                        OperationErrorEnum & err, OperationSourceEnum opSource)
 {
-    return setLockState(DlLockState::kLocked, pin, err, opSource);
+    return setLockState(commandObj, DlLockState::kLocked, pin, err, opSource);
```
[the remark this answers is not in the document]
Comment (jrhees-cae) [reply examples/lock-app/lock-common/src/LockEndpoint.cpp:28]: @bzbarsky-apple Is Handle needed here? What needs to be kept alive during the async operation? If, when the lock (app) finishes its operation,, it can generate the async LockOperation event as long as it knows the nodeId and FabricId...?

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 1 above)
Comment (mmarc) [reply src/app/clusters/door-lock-server/door-lock-server.cpp]: Changed it to pass `fabricIdx` and `nodeId` directly.

File: examples/lock-app/lock-common/src/LockEndpoint.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (mmarc) [reply examples/lock-app/lock-common/src/LockEndpoint.cpp]: `fabricIdx` and `nodeId` are now passed instead of `commandObj` and example has been adapted to go async.

File: examples/lock-app/lock-common/src/LockEndpoint.cpp [hunk 3]
```diff
@@ -475,15 +506,57 @@ bool LockEndpoint::setLockState(const Nullable<chip::FabricIndex> & fabricIdx, c
...
+    currentAction.endpointId      = mEndpointId;
+    currentAction.lockState       = lockState;
+    currentAction.opSource        = opSource;
+    currentAction.userIndex       = MakeNullable(static_cast<uint16_t>(userIndex + 1));
+    currentAction.credentialIndex = static_cast<uint16_t>(credentialIndex);
+    currentAction.fabricIdx       = fabricIdx;
+    currentAction.nodeId          = nodeId;
+
+    // simulate 3s lock movement duration
+    chip::DeviceLayer::SystemLayer().StartTimer(chip::System::Clock::Seconds16(3), OnLockActionCompleteCallback, nullptr);
```
Comment (jrhees-cae) [inline examples/lock-app/lock-common/src/LockEndpoint.cpp:524]: We may want to consider a value lower than 3 seconds since these delays add up in CI backend testing.

File: examples/lock-app/lock-common/src/LockEndpoint.cpp [hunk 4]
```diff
@@ -18,10 +18,27 @@
...
+    OperationSourceEnum opSource;
+    Nullable<uint16_t> userIndex;
+    uint16_t credentialIndex;
+    Nullable<List<const LockOpCredentials>> credentials;
+    Nullable<chip::FabricIndex> fabricIdx;
+    Nullable<chip::NodeId> nodeId;
+    bool moving = false;
+};
+
+LockActionData currentAction;
```
Comment (jrhees-cae) [inline examples/lock-app/lock-common/src/LockEndpoint.cpp:40]: `currentAction` is global here; while this might be suitable for an example, it creates the risk that a second lock/unlock command which arrives while the first async command is ongoing will trash this struct.

Comment (mmarc) [reply examples/lock-app/lock-common/src/LockEndpoint.cpp:40]: That's why I've added the `moving` and reject the new command.
I didn't want to make the example too complex.

File: examples/lock-app/lock-common/src/LockEndpoint.cpp (hunk 3 above)
Comment (mmarc) [reply examples/lock-app/lock-common/src/LockEndpoint.cpp:524]: I've adapted the tests accordingly.
But I can reduce the delay as well @bzbarsky-apple ?

File: src/app/clusters/door-lock-server/door-lock-server.cpp [hunk 5]
```diff
@@ -3428,7 +3426,8 @@ bool DoorLockServer::HandleRemoteLockOperation(chip::app::CommandHandler * comma
     }
 
     // credentials check succeeded, try to lock/unlock door
-    success = opHandler(endpoint, pinCode, reason);
+    success = opHandler(endpoint, Nullable<chip::FabricIndex>(getFabricIndex(commandObj)),
+                        Nullable<chip::NodeId>(getNodeId(commandObj)), pinCode, reason);
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.cpp:3430]:
```suggestion
    success = opHandler(endpoint, MakeNullable(getFabricIndex(commandObj)),
                        MakeNullable(getNodeId(commandObj)), pinCode, reason);
```

File: src/app/clusters/door-lock-server/door-lock-server.h [hunk 6]
```diff
@@ -59,7 +59,8 @@ using chip::app::DataModel::NullNullable;
 using CredentialStruct  = chip::app::Clusters::DoorLock::Structs::CredentialStruct::Type;
 using LockOpCredentials = CredentialStruct;
 
-typedef bool (*RemoteLockOpHandler)(chip::EndpointId endpointId, const Optional<chip::ByteSpan> & pinCode,
+typedef bool (*RemoteLockOpHandler)(chip::EndpointId endpointId, const Nullable<chip::FabricIndex> & fabricIdx,
+                                    const Nullable<chip::NodeId> & nodeId, const Optional<chip::ByteSpan> & pinCode,
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.h:63]: Please document that fabricIdx and nodeId represent the client that is operating on us.

File: src/app/clusters/door-lock-server/door-lock-server.h [hunk 7]
```diff
@@ -95,12 +96,16 @@ class DoorLockServer
      * @param endpointId ID of the endpoint to the lock state
      * @param newLockState new lock state
      * @param opSource source of the operation (will be used in the event).
+     * @param fabricIdx fabric index
+     * @param nodeId node id
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.h:100]: Again, better to more clearly document which fabric and node these are: those that are responsible for operating the lock.

And maybe we should test that those are only non-null for the "remote" optype?  Or at least document here that they must be provided for that optype.

File: src/app/clusters/door-lock-server/door-lock-server.h [hunk 8]
```diff
@@ -899,39 +904,48 @@ emberAfPluginDoorLockOnUnhandledAttributeChange(chip::EndpointId EndpointId, con
  * @brief User handler for LockDoor command (server)
  *
  * @param   endpointId      endpoint for which LockDoor command is called
+ * @param   fabricIdx       fabric index
+ * @param   nodeId          node id
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.h:908]: Similar comments as above about documentation.

File: src/app/clusters/door-lock-server/door-lock-server.h [hunk 9]
```diff
@@ -899,39 +904,48 @@ emberAfPluginDoorLockOnUnhandledAttributeChange(chip::EndpointId EndpointId, con
...
+bool emberAfPluginDoorLockOnDoorUnlockCommand(chip::EndpointId endpointId, const Nullable<chip::FabricIndex> & fabricIdx,
+                                              const Nullable<chip::NodeId> & nodeId, const Optional<chip::ByteSpan> & pinCode,
                                               OperationErrorEnum & err);
 
 /**
  * @brief User handler for UnboltDoor command (server)
  *
  * @param   endpointId      endpoint for which UnboltDoor command is called
+ * @param   fabricIdx       fabric index
+ * @param   nodeId          node id
```
Comment (bzbarsky-apple) [inline src/app/clusters/door-lock-server/door-lock-server.h:940]: Similar comments.

File: src/app/tests/suites/DL_LockUnlock.yaml [hunk 10]
```diff
@@ -18,7 +18,7 @@ config:
     nodeId: 0x12344321
     cluster: "Door Lock"
     endpoint: 1
-    timeout: 25
+    timeout: 100
```
Comment (bzbarsky-apple) [inline src/app/tests/suites/DL_LockUnlock.yaml:21]: Right, so ideally we would not need this, if we can have a shorter timer in the implementation....

File: src/app/tests/suites/DL_LockUnlock.yaml [hunk 11]
```diff
@@ -33,6 +33,14 @@ tests:
       command: "UnlockDoor"
       timedInteractionTimeoutMs: 10000
 
+    - label: "Wait for lock action to complete"
```
Comment (bzbarsky-apple) [inline src/app/tests/suites/DL_LockUnlock.yaml:36]: Followup (separate PR): Instead of doing waits then reads, we should just subscribe and wait for reports.

File: src/app/tests/suites/certification/Test_TC_DRLK_2_1.yaml [hunk 12]
```diff
@@ -63,6 +63,14 @@ tests:
       command: "LockDoor"
       timedInteractionTimeoutMs: 1000
 
+    - label: "Wait for lock action to complete"
```
Comment (bzbarsky-apple) [inline src/app/tests/suites/certification/Test_TC_DRLK_2_1.yaml:66]: These are certification tests. We can't just change them like this without updating the test plan, right?

That said, they are broken as written, looks like, and would fail with real locks.  What I would suggest is disabling them in CI for now and filing a test plan issue to get them fixed....  Or just fixing the test plan.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/tests/suites/certification/Test_TC_DRLK_2_1.yaml (hunk 12 above)
Comment (bzbarsky-apple) [reply src/app/tests/suites/certification/Test_TC_DRLK_2_1.yaml:66]: Also, if we switch to 0 delay it's possible that the tests will pass in CI for now... and then we just need to get the test plan fixed in general.

File: src/app/tests/suites/DL_LockUnlock.yaml (hunk 11 above)
Comment (jrhees-cae) [reply src/app/tests/suites/DL_LockUnlock.yaml:36]: I went down this rabbit-hole a while back. Waiting for reports had issues in Yaml (maybe they're fixed now) -- if any other activity came in while waiting for the report, the test runner would get messed up, so there were always race conditions.

File: examples/lock-app/lock-common/src/LockEndpoint.cpp (hunk 3 above)
Comment (mmarc) [reply examples/lock-app/lock-common/src/LockEndpoint.cpp]: Changed to 0s

File: examples/lock-app/lock-common/src/LockEndpoint.cpp [hunk 13]
```diff
@@ -18,29 +18,49 @@
...
```
[the remark this answers is not in the document]
Comment (mmarc) [reply examples/lock-app/lock-common/src/LockEndpoint.cpp]: done

File: examples/lock-app/lock-common/src/LockEndpoint.cpp [hunk 14]
```diff
@@ -18,29 +18,49 @@
...
-bool LockEndpoint::Lock(const Optional<chip::ByteSpan> & pin, OperationErrorEnum & err, OperationSourceEnum opSource)
+struct LockActionData
 {
-    return setLockState(DlLockState::kLocked, pin, err, opSource);
+    chip::EndpointId endpointId;
+    DlLockState lockState;
+    OperationSourceEnum opSource;
+    Nullable<uint16_t> userIndex;
+    uint16_t credentialIndex;
+    Nullable<List<const LockOpCredentials>> credentials;
```
[the remark this answers is not in the document]
Comment (mmarc) [reply examples/lock-app/lock-common/src/LockEndpoint.cpp:34]: Correct, fixed

File: examples/lock-app/lock-common/src/LockEndpoint.cpp [hunk 15]
```diff
@@ -470,15 +506,57 @@ bool LockEndpoint::setLockState(DlLockState lockState, const Optional<chip::Byte
...
+
+    // simulate 3s lock movement duration
+    chip::DeviceLayer::SystemLayer().StartTimer(chip::System::Clock::Seconds16(3), OnLockActionCompleteCallback, nullptr);
 
     return true;
 }
 
+void LockEndpoint::OnLockActionCompleteCallback(chip::System::Layer *, void * callbackContext)
+{
+    if (currentAction.userIndex == NullNullable)
```
[the remark this answers is not in the document]
Comment (mmarc) [reply examples/lock-app/lock-common/src/LockEndpoint.cpp]: done

File: src/app/clusters/door-lock-server/door-lock-server.cpp (hunk 5 above)
Comment (mmarc) [reply src/app/clusters/door-lock-server/door-lock-server.cpp:3430]: done

File: examples/lock-app/lock-common/src/LockEndpoint.cpp [hunk 16]
```diff
@@ -406,13 +427,28 @@ bool LockEndpoint::setLockState(DlLockState lockState, const Optional<chip::Byte
             ChipLogProgress(Zcl, "Door Lock App: setting door lock state to \"%s\" [endpointId=%d]", lockStateToString(lockState),
                             mEndpointId);
 
-            DoorLockServer::Instance().SetLockState(mEndpointId, lockState);
+            if (currentAction.moving == true)
+            {
+                return false;
```
[the remark this answers is not in the document]
Comment (mmarc) [reply examples/lock-app/lock-common/src/LockEndpoint.cpp:432]: done

File: src/app/clusters/door-lock-server/door-lock-server.h (hunk 7 above)
Comment (mmarc) [reply src/app/clusters/door-lock-server/door-lock-server.h]: added error log for that case now

**Review by bzbarsky-apple — APPROVED** [review]

**Review by jrhees-cae — APPROVED** [review]

File: examples/lock-app/lock-common/src/LockEndpoint.cpp [hunk 17]
```diff
@@ -18,29 +18,48 @@
...
+static LockActionData gCurrentAction;
+
+bool LockEndpoint::Lock(const Nullable<chip::FabricIndex> & fabricIdx, const Nullable<chip::NodeId> & nodeId,
+                        const Optional<chip::ByteSpan> & pin, OperationErrorEnum & err, OperationSourceEnum opSource)
+{
+    return setLockState(fabricIdx, nodeId, DlLockState::kLocked, pin, err, opSource);
 }
 
-bool LockEndpoint::Unlock(const Optional<chip::ByteSpan> & pin, OperationErrorEnum & err, OperationSourceEnum opSource)
+bool LockEndpoint::Unlock(const Nullable<chip::FabricIndex> & fabricIdx, const Nullable<chip::NodeId> & nodeId,
```
Comment (cecille) [inline examples/lock-app/lock-common/src/LockEndpoint.cpp:47]: Possibly a silly question (not my normal area), but what would a null fabricIdx mean here? Unlock over PASE? Is that allowed?

Comment (jrhees-cae) [reply examples/lock-app/lock-common/src/LockEndpoint.cpp:47]: On a real lock, a null fabric index could occur when the action source is not via Matter (for example, locking via thumb turn)

Comment (cecille) [reply examples/lock-app/lock-common/src/LockEndpoint.cpp:47]: AH. Cool thanks.

**Review by cecille — APPROVED** [review]
