### PR TITLE
Resolve operator ambiguities and improve compiler compatibility

### LINKED ISSUE #40781: [Build] Compiling with C++20 results in build failure
### Build issue(s)

**Build Issue(s)**

The project fails to compile with a C++20-compliant compiler. The failure occurs due to the following issues:

Ambiguity in resolving the operator== call between ConcreteAttributePath and ConcreteDataAttributePath.
1. `ChunkedWriteCallback::IsAppendingToLastItem` (ChunkedWriteCallback.cpp)
2. `IsSameAttribute` (WriteHandler.cpp)
 
Compound assignment to volatile.
1. `diff |= x ^ y;` (CHIPCryptoPALPSA.cpp)

Resolving these issues is straightforward and results in a successful build.
```
diff --git src/app/ChunkedWriteCallback.cpp src/app/ChunkedWriteCallback.cpp
index eccd2b6049..6ec1d07b6f 100644
--- src/app/ChunkedWriteCallback.cpp
+++ src/app/ChunkedWriteCallback.cpp
@@ -81,7 +81,7 @@ bool ChunkedWriteCallback::IsAppendingToLastItem(const ConcreteDataAttributePath
     {
         return false;
     }
-    if (!mProcessingAttributePath.HasValue() || !(mProcessingAttributePath.Value() == aPath))
+    if (!mProcessingAttributePath.HasValue() || !(mProcessingAttributePath.Value() == static_cast<ConcreteAttributePath>(aPath)))
     {
         return false;
     }
diff --git src/app/WriteHandler.cpp src/app/WriteHandler.cpp
index fbcab6bcbe..38bb834df9 100644
--- src/app/WriteHandler.cpp
+++ src/app/WriteHandler.cpp
@@ -323,7 +323,7 @@ namespace {
 // To reduce the various use of previousProcessed.HasValue() && previousProcessed.Value() == nextAttribute to save code size.
 bool IsSameAttribute(const Optional<ConcreteAttributePath> & previousProcessed, const ConcreteDataAttributePath & nextAttribute)
 {
-    return previousProcessed.HasValue() && previousProcessed.Value() == nextAttribute;
+    return previousProcessed.HasValue() && previousProcessed.Value() == static_cast<ConcreteAttributePath>(nextAttribute);
 }
 
 bool ShouldReportListWriteEnd(const Optional<ConcreteAttributePath> & previousProcessed, bool previousProcessedAttributeIsList,
diff --git src/crypto/CHIPCryptoPALPSA.cpp src/crypto/CHIPCryptoPALPSA.cpp
index 2f410a29de..ea66e023d3 100644
--- src/crypto/CHIPCryptoPALPSA.cpp
+++ src/crypto/CHIPCryptoPALPSA.cpp
@@ -777,7 +777,7 @@ int mbedtls_ct_memcmp_copy(const void * a, const void * b, size_t n)
          * This avoids IAR compiler warning:
          * 'the order of volatile accesses is undefined ..' */
         unsigned char x = A[i], y = B[i];
-        diff |= x ^ y;
+        diff = diff | (x ^ y);
     }
 
     return ((int) diff);
```

### Platform

nrf connect, all

### Anything else?

I only tested nrf connect but I think it is safe to assume all platforms are affected. I was not able to identify any similar instances to the above that may cause build failures in other projects.

### PR DESCRIPTION
**Pull request by pcaddict**
#### Summary

This change enables the use of C++20 compatible toolchains by resolving the following issues:

1. Resolves an ambiguous comparison between `ConcreteAttributePath and ConcreteDataAttributePath`.
	 - The expression `(ConcreteAttributePath) == (ConcreteDataAttributePath)` became ambiguous because the C++20 standard changed the rules for overload resolution for symmetric operators. The compiler finds a "normal" and "reversed" candidate and declares the comparison ambiguous.
2. Replaces compound assignment: In `CHIPCryptoPALPSA.cpp`, it refactors a compound assignment (|=) to its explicit form (= ... |) to prevent potential compiler warnings related to compound assignment to volatile.
3. Update CMake to enable correct C++ standard (Optional/WIP): Modify `enable-gnu-std.cmake` to conditionally select between gnu++17 and gnu++20. This change is needed to fully allow compilation with C++20 because `enable-gnu-std.cmake` unconditionally sets `-std=gnu++17`, potentially overriding the developer-configured C++ standard and results in build errors.
	- **This change will require further discussion. Local testing has begun.**
#### Related issues
Fixes: [Issue 40781](https://github.com/project-chip/connectedhomeip/issues/40781)

#### Testing
CI
 
#### Readability checklist

The checklist below will help the reviewer finish PR review in time and keep the
code readable:

-   [ ] PR title is
        [descriptive](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html#title-formatting)
-   [ ] Apply the
        [_“When in Rome…”_](https://project-chip.github.io/connectedhomeip-doc/style/CODING_STYLE_GUIDE.html)
        rule (coding style)
-   [ ] PR size is short
-   [ ] Try to avoid "squashing" and "force-update" in commit history
-   [ ] CI time didn't increase

### CODE REVIEW

File: src/app/ChunkedWriteCallback.cpp [hunk 1]
```diff
@@ -81,7 +81,7 @@ bool ChunkedWriteCallback::IsAppendingToLastItem(const ConcreteDataAttributePath
     {
         return false;
     }
-    if (!mProcessingAttributePath.HasValue() || !(mProcessingAttributePath.Value() == aPath))
+    if (!mProcessingAttributePath.HasValue() || !(mProcessingAttributePath.Value() == static_cast<ConcreteAttributePath>(aPath)))
```
Comment (soares-sergio) [inline src/app/ChunkedWriteCallback.cpp]: This seems like an easy mistake to make...

I wonder if we can add/overload something to the class itself to prevent making this mistake again?

Comment (pcaddict) [reply src/app/ChunkedWriteCallback.cpp]: I've dug a little deeper and believe the solution can be improved, but I am not sure how widespread the ramifications are in terms of how this might apply elsewhere, if it matters.

A better solution may be to make the constructor for `ConcreteDataAttributePath` explicit. This prevents the implicit casts and removes the need for the explicit casts added in my PR. On the other hand, there are two other places that will then need explicit casts to resolve situations where implicit casts were used in function calls.

For now I will leave the new diff in this comment for discussion. I am unsure what the correct path forward is in pushing these changes, or even if this is the desired solution but I think it is worth consideration. 

```diff
diff --git a/src/app/ChunkedWriteCallback.cpp b/src/app/ChunkedWriteCallback.cpp
index 6ec1d07..bae45ba 100644
--- a/src/app/ChunkedWriteCallback.cpp
+++ b/src/app/ChunkedWriteCallback.cpp
@@ -40,7 +40,7 @@ void ChunkedWriteCallback::OnResponse(const WriteClient * apWriteClient, const C
         }
 
         // This is a response to another attribute write. Report the final result of last attribute write.
-        callback->OnResponse(apWriteClient, mProcessingAttributePath.Value(), mAttributeStatus);
+        callback->OnResponse(apWriteClient, static_cast<ConcreteDataAttributePath>(mProcessingAttributePath.Value()), mAttributeStatus);
     }
 
     // This is the first report for a new attribute.  We assume it will never be a list item operation.
@@ -66,7 +66,7 @@ void ChunkedWriteCallback::OnDone(WriteClient * apWriteClient)
         // We have a cached status that has yet to be reported to the application so report it now.
         // If we failed to receive the response, or we received a malformed response, OnResponse won't be called,
         // mProcessingAttributePath will be Missing() in this case.
-        callback->OnResponse(apWriteClient, mProcessingAttributePath.Value(), mAttributeStatus);
+        callback->OnResponse(apWriteClient, static_cast<ConcreteDataAttributePath>(mProcessingAttributePath.Value()), mAttributeStatus);
     }
 
     mProcessingAttributePath = NullOptional;
@@ -81,7 +81,7 @@ bool ChunkedWriteCallback::IsAppendingToLastItem(const ConcreteDataAttributePath
     {
         return false;
     }
-    if (!mProcessingAttributePath.HasValue() || !(mProcessingAttributePath.Value() == static_cast<ConcreteAttributePath>(aPath)))
+    if (!mProcessingAttributePath.HasValue() || !(mProcessingAttributePath.Value() == aPath))
     {
         return false;
     }
diff --git a/src/app/ConcreteAttributePath.h b/src/app/ConcreteAttributePath.h
index 99afb46..48bb1f9 100644
--- a/src/app/ConcreteAttributePath.h
+++ b/src/app/ConcreteAttributePath.h
@@ -113,7 +113,7 @@ struct ConcreteDataAttributePath : public ConcreteAttributePath
 
     ConcreteDataAttributePath() {}
 
-    ConcreteDataAttributePath(const ConcreteAttributePath & path) : ConcreteAttributePath(path) {}
+    explicit ConcreteDataAttributePath(const ConcreteAttributePath & path) : ConcreteAttributePath(path) {}
 
     ConcreteDataAttributePath(EndpointId aEndpointId, ClusterId aClusterId, AttributeId aAttributeId) :
         ConcreteAttributePath(aEndpointId, aClusterId, aAttributeId)
diff --git a/src/app/WriteHandler.cpp b/src/app/WriteHandler.cpp
index 7fa782c..8566d24 100644
--- a/src/app/WriteHandler.cpp
+++ b/src/app/WriteHandler.cpp
@@ -324,7 +324,7 @@ namespace {
 // To reduce the various use of previousProcessed.HasValue() && previousProcessed.Value() == nextAttribute to save code size.
 bool IsSameAttribute(const Optional<ConcreteAttributePath> & previousProcessed, const ConcreteDataAttributePath & nextAttribute)
 {
-    return previousProcessed.HasValue() && previousProcessed.Value() == static_cast<ConcreteAttributePath>(nextAttribute);
+    return previousProcessed.HasValue() && previousProcessed.Value() == nextAttribute;
 }
 
 bool ShouldReportListWriteEnd(const Optional<ConcreteAttributePath> & previousProcessed, bool previousProcessedAttributeIsList,
```

File: src/app/ChunkedWriteCallback.cpp [hunk 2]
```diff
@@ -40,7 +40,7 @@ void ChunkedWriteCallback::OnResponse(const WriteClient * apWriteClient, const C
         }
 
         // This is a response to another attribute write. Report the final result of last attribute write.
-        callback->OnResponse(apWriteClient, mProcessingAttributePath.Value(), mAttributeStatus);
+        callback->OnResponse(apWriteClient, static_cast<ConcreteDataAttributePath>(mProcessingAttributePath.Value()), mAttributeStatus);
```
Comment (bzbarsky-apple) [inline src/app/ChunkedWriteCallback.cpp]: Why is this change needed?  The PR description is talking about `operator==`, but there is no `==` involved here.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

**Comment by pcaddict** [comment]
@soares-sergio @bzbarsky-apple Do you have any other concerns with this PR that need to be addressed?

**Comment by bzbarsky-apple** [comment]
Well, answering my question above would be good.  The code changes do not match the PR description.

But also, CI clearly fails, because there are various other places that were using implicit construction of `ConcreteDataAttributePath` from `ConcreteAttributePath`.

It seems like the real issue is that `ConcreteAttributePath(stuff) == ConcreteDataAttributePath(stuff)` is ambiguous because... what?  The compiler can't decide whether to invoke `ConcreteAttributePath::operator==` or whether to implicitly construct a `ConcreteDataAttributePath` from the left hand side and invoke `ConcreteDataAttributePath::operator==`?

My understanding is that there's a difference in C++20 vs C++17 here: in C++17 when doing "x == y", in addition to looking for `operator==(decltype(x), decltype(y))` the compiler has to look for `operator==(decltype(y), decltype(x))`.  In particular, the comparison at question is not flagged as ambiguous by clang with `-std=c++17` but is flagged as ambiguous by clang with `-std=c++20`.  Does that match your observations @pcaddict ?

If so, then I think the right solution may well be to just define:
```
    bool operator==(const ConcreteAttributePath & other) const {
        return ConcreteAttributePath::operator==(other);
    }
```
on `ConcreteDataAttributePath` to preserve the current behavior: when comparing a `ConcreteAttributePath` and a `ConcreteDataAttributePath` for equality, `ConcreteAttributePath::operator==` is invoked and only the non-list parts of the paths are compared.  I believe, based on my local testing, that this should address the C++20 compatibility issue.

Either way, whatever solution we select, the PR description needs to clearly describe what's actually changing.

**Comment by pcaddict** [comment]
Sorry @bzbarsky-apple, looking back at my response to your question I realize that I was not clearly explaining the relation of my proposed changes to `operator==`. Your explanation and understanding of the issue match my observations and does a far better job of explaining the issue than I did.

> It seems like the real issue is that `ConcreteAttributePath(stuff) == ConcreteDataAttributePath(stuff)` is ambiguous because... what? The compiler can't decide whether to invoke `ConcreteAttributePath::operator==` or whether to implicitly construct a `ConcreteDataAttributePath` from the left hand side and invoke `ConcreteDataAttributePath::operator==`?
>
> My understanding is that there's a difference in C++20 vs C++17 here: in C++17 when doing "x == y", in addition to looking for `operator==(decltype(x), decltype(y))` the compiler has to look for `operator==(decltype(y), decltype(x))`. In particular, the comparison at question is not flagged as ambiguous by clang with `-std=c++17` but is flagged as ambiguous by clang with `-std=c++20`.

To add a little more context, the ambiguity arises because the compiler can find two valid ways to perform the comparison:

1. Invoke `ConcreteAttributePath::operator==`: The compiler can use the base class's `operator==`. To do this, it performs a standard "upcast" on the `ConcreteDataAttributePath` object, converting it to a `ConcreteAttributePath`.

2. Invoke `ConcreteDataAttributePath::operator==`: The compiler can also "reverse" the comparison and use the derived class's `operator==`. To do this, it must convert the `ConcreteAttributePath` object on the left into a `ConcreteDataAttributePath` by using its implicit constructor.

The rules for resolving this conflict changed between C++17 and C++20:

*   In C++17: The compiler ranked the two options. It considered the standard upcast (Option 1) to be "better" than the user-defined conversion via a constructor (Option 2), so it unambiguously chose Option 1.
*   In C++20: The rules were tightened. For symmetric operators, if the compiler finds both a "normal" candidate and a "reversed" candidate, it no longer tries to rank them and declares the call ambiguous.
***
My approach with the `explicit` constructor was chosen (admittedly I did not think of your approach) because it addresses the cause of the ambiguity, implicit base to derived conversion, and requires any conversion to be explicit and deliberate. As this solution has evolved it has become clear that the complete solution is more involved than what I've initially submitted.

Your solution is advantageous because it does not introduce the explicit casting required by my solution. I don't think the deliberate casting my solution requires is bad, but it is "different" compared to existing code.

Would we need to include a comment with your solution to document why we are delegating the comparison to the parent class? For example:
```
Explicitly delegate to parent to resolve C++20 ambiguity. This intentionally compares only the
non-list portions of the path, which is the desired behavior for this comparison.
```
***
At this point, I need a little guidance on how to proceed. The next steps as I see it are:
1. Update PR description to more extensively explain the problem.
2. Choose a solution and make required changes.
    a. If alternate solution is selected to what has already been partially implemented, how should the current changes be rolled back?

Thanks again @bzbarsky-apple for the input and assistance. I apologize for needing some hand-holding on this, I'm clearly out of my depth and this has been a learning experience.

**Comment by pcaddict** [comment]
I am thinking a second PR might be required to resolve point 3 in my summary above. This PR resolves compilation issues that arose due to changes in the C++ standard, eliminating compilation errors when a project elects to use C++20. Further work is required to fully enable C++20 support since any platforms that make use of `enable-std-gnu.cmake` force the use of `-std=gnu++17`, ignoring the standard set by the developer.

**Review by bzbarsky-apple — APPROVED** [review]
My apologies for the lag @pcaddict .  I have been having a having a hard time keeping track of Github notifications, unfortunately.

**Comment by bzbarsky-apple** [comment]
> Would we need to include a comment with your solution to document why we are delegating the comparison to the parent class?

That's not a bad idea, @pcaddict...  I figured we should get the fix in, so this is not stuck anymore, but if you have time to put up a documentation PR here, that would be great.  Chances are, given time of year, that won't merge until January, though.
