### PR TITLE
Fix decoding random encrypted bytes as packet header

### LINKED ISSUE #5903: Code landed in PR 5848 is decoding random encrypted bytes as packet headers
#### Problem
I was reading over https://github.com/project-chip/connectedhomeip/pull/5848 and the code just makes no sense to me.

1. `SecureSessionMgr::OnMessageReceived` as called from lower layers has the packet buffer pointing to the start of the encrypted payload, I would think, since the `PacketHeader` has been parsed out already.  That's consistent with the behavior of `SecureMessageCodec::Decode` as called from that function.
2. When we detect a group message with unsynced message counter, we call `QueueReceivedMessageAndSync` and hand over the packetbuffer.  We do not adjust its start position to point to the packet header (either manually or by re-encoding the packet header into it).
3. In `MessageCounterSyncMgr::ProcessPendingGroupMsgs` we then decode a `PacketHeader` from whatever the buffer's start position happens to be.  Which, recall, is the start of the encrypted payload.  This is the part that makes no sense to me.
4. We then pass that packet header, and the buffer (still pointing to the encrypted payload) into `HandleGroupMessageReceived`.  

Of course the message counter sync tests don't test that we can add a message to the receive table, then actually process it from there, so this does not get caught.

 #### Proposed Solution
1. Add tests that will demonstrate the code is broken as it stands.
2. When we go to queue the message, we should `EncodeBeforedata` the `PacketHeader` into the buffer.  This is safer than trying to manually adjust the position of the buffer to point to the data already in it, I would expect.
3. When we go to dequeue the message, we should `DecodeAndConsume` the `PacketHeader` from the buffer instead of the manual thing with `->Start()` that the code does right now.

@yufengwangca could you please take a look?

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
#5848 introduced regression:

1. SecureSessionMgr::OnMessageReceived as called from lower layers has the packet buffer pointing to the start of the encrypted payload, since the PacketHeader has been parsed out already.

2. When we detect a group message with unsynced message counter, we call QueueReceivedMessageAndSync and hand over the packetbuffer. We do not adjust its start position to point to the packet header (either manually or by re-encoding the packet header into it).

3. In MessageCounterSyncMgr::ProcessPendingGroupMsgs we then decode a PacketHeader from whatever the buffer's start position happens to be. Which, recall, is the start of the encrypted payload. 

4. We then pass that packet header, and the buffer (still pointing to the encrypted payload) into HandleGroupMessageReceived. 

 #### Summary of Changes
1. Add unit test that will demonstrate the code is broken as it stands.
2. When we go to queue the message, we should EncodeBeforedata the PacketHeader into the buffer. .
3. When we go to dequeue the message, we should DecodeAndConsume the PacketHeader from the buffer instead of the manual thing with ->Start() that the code does right now.

 Fixes #5903

### CODE REVIEW

File: src/messaging/MessageCounterSync.cpp [hunk 1]
```diff
@@ -198,10 +198,10 @@ void MessageCounterSyncMgr::ProcessPendingGroupMsgs(NodeId peerNodeId)
...
         {
             PacketHeader packetHeader;
-            uint16_t headerSize = 0;
 
-            if (packetHeader.Decode((entry.msgBuf)->Start(), (entry.msgBuf)->DataLength(), &headerSize) != CHIP_NO_ERROR)
+            if (packetHeader.DecodeAndConsume(entry.msgBuf) != CHIP_NO_ERROR)
             {
+                ChipLogError(ExchangeManager, "ProcessPendingGroupMsgs::Failed to decode PacketHeader");
                 break;
             }
```
Comment (bzbarsky-apple) [inline src/messaging/MessageCounterSync.cpp:207]: So if this packet header does not match the incoming nodeid, don't we need to re-encode it into the buffer?

I had forgotten that the decoding here was conditional.  We might want to decode without consuming, and then on match consume the headerSize number of bytes or something...

Please add a test that would catch this?  ;)

File: src/transport/SecureSessionMgr.cpp [hunk 2]
```diff
@@ -371,6 +371,10 @@ void SecureSessionMgr::OnMessageReceived(const PacketHeader & packetHeader, cons
         // Queue the message as needed for sync with destination node.
         if (mCB != nullptr)
         {
+            // We should encode the packetHeader into the buffer before storing the buffer into the queue.
+            // The encoded packetHeader needs to be peeled off during re-processing after the peer message
+            // couter is synced.
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionMgr.cpp:376]:
```suggestion
            // counter is synced.
```

File: src/messaging/MessageCounterSync.cpp [hunk 3]
```diff
@@ -198,10 +198,10 @@ void MessageCounterSyncMgr::ProcessPendingGroupMsgs(NodeId peerNodeId)
         if (!entry.msgBuf.IsNull())
         {
             PacketHeader packetHeader;
-            uint16_t headerSize = 0;
 
-            if (packetHeader.Decode((entry.msgBuf)->Start(), (entry.msgBuf)->DataLength(), &headerSize) != CHIP_NO_ERROR)
```
Comment (bzbarsky-apple) [inline src/messaging/MessageCounterSync.cpp:203]: Looks like the tests don't actually check that this part is done right.  I tried undoing this change, and tests passed...  Followup is probably ok for adding a test here, but we should make sure we add it.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/messaging/MessageCounterSync.cpp (hunk 3 above)
Comment (yufengwangca) [reply src/messaging/MessageCounterSync.cpp:203]: To unit test this part, I need to make ProcessPendingGroupMsgs public, since our test framework only unit test public member function right now, but I don't think we should modify our code just for testing, any good idea?

Comment (bzbarsky-apple) [reply src/messaging/MessageCounterSync.cpp:203]: No good ideas yet.  Hence followup.

**Review by bzbarsky-apple — APPROVED** [review]
Thank you for the quick turnaround!

**Review by saurabhst — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]
