### PR TITLE
Fix handling command handler status for group messages

### LINKED ISSUE #30472: [BUG] The command handler state tracking does not work properly for the groupcast messages.
### Reproduction steps

The `DispatchCommand` is called the same way for both groupcast and unicast scenarios: `mpCallback->DispatchCommand(*this, concretePath, dataReader);` and it doesn't pass the information about the originator of this call. It results in attempts of updating the status (with `AddStatus` method) for the invoking response purposes.

For the groupcast scenario updating status does not make sense, as response will not be sent anyway and additionally it leads to the application being killed if more than one endpoint existing on a single Matter node was added to the same group.
In such case receiving the groupcast command invokes the status update, which works well for the first endpoint from a list, but it fails for the following ones on a following check: `VerifyOrDie(FallibleAddStatus(aCommandPath, aStatus, context) == CHIP_NO_ERROR);`

This issue affects all devices that would like to configure single group on more than one endpoint within the single Matter node and also bridge devices that may represent several different bridged devices belonging to a single group.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

Tested with 181b0cb14ff007ec912f2ba6627e05dfb066c008, but it applies to master as well.

### Platform

core

### Platform Version(s)

All

### Anything else?

The potential solution could be adding `isGroupcastInvoked`-like boolean flag to the `DispatchCommand` method, forward it up to the `AddStatus` call and then conditionally return without updating the status in case of groupcast scenario.

### PR DESCRIPTION
**Pull request by kkasperczyk-no**
The command handler status is added for the response purposes even in case of invoking commands targeted to the group. In case of using more than one endpoint on a single Matter node that was added to the same group, it leads to the application crash. The direct reason is a state check, that succeeds only for the first endpoint and fails for the subsequent calls.

Added a new state flag, which informs if the command that is currently handled origins from groupcast communication or not. In case of targeting the group, application returns prematurely and do not try to add status.

Fixes: #30472

### CODE REVIEW

**Review by markaj-nordic — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by kkasperczyk-no** [comment]
Changing to draft, as I want to prevent mergify from merging it before getting reviews from people involved in slack discussion. Btw. is there a more convenient way to do that? :smile:

**Comment by tehampson** [comment]
> Changing to draft, as I want to prevent mergify from merging it before getting reviews from people involved in a slack discussion. Btw. is there a more convenient way to do that? 😄

Future reference you can also add a comment to the change saying that it is blocking comment for reason x,y,z and that you will resolve to allow merging once condition is satisfied. At least I prefer that method personally over draft PR

**Review by tehampson — APPROVED** [review]

File: src/app/CommandHandler.h [hunk 1]
```diff
@@ -416,7 +426,8 @@ class CommandHandler : public Messaging::ExchangeDelegate
 
     bool mSentStatusResponse = false;
 
-    State mState = State::Idle;
+    State mState       = State::Idle;
+    bool mGroupRequest = false;
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.h:430]: This makes CommandHandler bigger, due to padding, when we didn't have to do that (could have added it _after_ the TLV writer bits, next to the other two booleans).

This also does not handle commands that try to send a data response correctly, right?  Is there a plan for an actual correct fix for this?

Comment (kkasperczyk-no) [reply src/app/CommandHandler.h:430]: > This makes CommandHandler bigger, due to padding, when we didn't have to do that (could have added it after the TLV writer bits, next to the other two booleans).

Right, I haven't noticed it. 

> This also does not handle commands that try to send a data response correctly, right? Is there a plan for an actual correct fix for this?

Why? I don't think I understand this part. The flag is set `true` for all group messages that do not require sending response and it is set to `false` for non-group messages that should send a data response. What should be the actual correct fix?

Comment (bzbarsky-apple) [reply src/app/CommandHandler.h:430]: The flag is _set_ fine, but it's only _checked_ in AddStatus.  There are other methods that add data responses where it's not checked....

Comment (kkasperczyk-no) [reply src/app/CommandHandler.h:430]: As we discussed offline, VerifyOrDie check in `AddStatus` was the only reason of observed failures. The responses prepared for other types of messages like data reponses will be dropped from the queue anyway.
