### PR TITLE
[Android] Support General value TLV parsing

### LINKED ISSUE #30564: [BUG] Android java lib not decoding custom attribute correctly
### Reproduction steps

Here it is in the report: @yunhanw-google 
image
Here it is in the Kotlin report variable:
image

JSON and TLV both have the 2, but valueObject is null, it should be 2.

Example of correctly decoded standard attribute:
image

### Bug prevalence

always

### GitHub hash of the SDK that was being used

181b0cb14ff007ec912f2ba6627e05dfb066c008

### Platform

android

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by joonhaengHeo**
Fix #30564 

Even if the result of DecodeAttributeValue is a null value, TLV parsing is possible for Integer, Float, Boolean, String, and byteArray.

### CODE REVIEW

File: src/controller/java/AndroidCallbacks.cpp [hunk 1]
```diff
@@ -907,6 +915,77 @@ void InvokeCallback::ReportError(const char * message, ChipError::StorageType er
...
+    CHIP_ERROR err   = CHIP_NO_ERROR;
+    jobject retValue = nullptr;
+
+    TLV::TLVReader readerForJavaObject;
+    readerForJavaObject.Init(*apData);
+
+    switch (readerForJavaObject.GetType())
+    {
+    case TLV::kTLVType_SignedInteger: {
+        int64_t signedValue;
```
Comment (yunhanw-google) [inline src/controller/java/AndroidCallbacks.cpp:929]: please set the initial value. thanks

File: src/controller/java/AndroidCallbacks.cpp [hunk 2]
```diff
@@ -907,6 +915,77 @@ void InvokeCallback::ReportError(const char * message, ChipError::StorageType er
...
+        VerifyOrReturnValue(readerForJavaObject.Get(signedValue) == CHIP_NO_ERROR, nullptr,
+                            ChipLogProgress(Controller, "Get TLV Value fail!"));
+        err = JniReferences::GetInstance().CreateBoxedObject<jlong>("java/lang/Long", "(J)V", static_cast<jlong>(signedValue),
+                                                                    retValue);
+        VerifyOrReturnValue(err == CHIP_NO_ERROR, nullptr, ChipLogProgress(Controller, "Create Boxed Object fail!"));
+        return retValue;
+    }
+    case TLV::kTLVType_UnsignedInteger: {
+        uint64_t unsignedValue;
```
Comment (yunhanw-google) [inline src/controller/java/AndroidCallbacks.cpp:938]: please set the initial value. thanks

**Review by yufengwangca — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]

File: src/controller/java/AndroidCallbacks.cpp [hunk 3]
```diff
@@ -907,6 +915,77 @@ void InvokeCallback::ReportError(const char * message, ChipError::StorageType er
...
+        std::unique_ptr<uint8_t[]> buffer = std::unique_ptr<uint8_t[]>(new uint8_t[bufferLen + 1]);
+        err                               = readerForJavaObject.GetBytes(buffer.get(), bufferLen + 1);
+        VerifyOrReturnValue(err == CHIP_NO_ERROR, nullptr, ChipLogProgress(Controller, "Get TLV Value fail!"));
+
+        jbyteArray valueByteArray = env->NewByteArray(static_cast<jsize>(bufferLen));
+        env->SetByteArrayRegion(valueByteArray, 0, static_cast<jsize>(bufferLen), reinterpret_cast<const jbyte *>(buffer.get()));
+
+        return static_cast<jobject>(valueByteArray);
+    }
+    default:
```
Comment (yunhanw-google) [inline src/controller/java/AndroidCallbacks.cpp:984]: should we handle struct and array?, and dump it into json?

Comment (andy31415) [reply src/controller/java/AndroidCallbacks.cpp:984]: It seems we return pure objects here ... it sounds like list/array should be a list as well. Unsure about structures though.

File: src/controller/java/AndroidCallbacks.cpp (hunk 1 above)
Comment (joonhaengHeo) [reply src/controller/java/AndroidCallbacks.cpp:929]: Modified. Thanks.

File: src/controller/java/AndroidCallbacks.cpp (hunk 2 above)
Comment (joonhaengHeo) [reply src/controller/java/AndroidCallbacks.cpp:938]: Modified. Thanks.

File: src/controller/java/AndroidCallbacks.cpp (hunk 3 above)
Comment (joonhaengHeo) [reply src/controller/java/AndroidCallbacks.cpp:984]: @yunhanw-google 
The purpose of this modification is to transmit at least some values of the Custom Attribute through TLV Parsing. As andy31415 commented, it may be possible to implement an Array/List with a simple value, but I think it will be difficult to implement anything else.

Comment (yunhanw-google) [reply src/controller/java/AndroidCallbacks.cpp:1020]: thanks!
