### PR TITLE
Do not disable BLE if a fabric has not been provisioned on the device

### LINKED ISSUE #9832: provisioning over BLE on raspi is broken as BLE advertisement disabled
With ToT (fb53b776694a5910a8e0f36fa810d75c02d877be) Provisioning over BLE on raspi is broken.  From the control log statement "Network already provisioned. Disabling BLE advertisement" , it looks like the BLE advertisement is disabled, hence the controller couldn't provision the device.  Steps to reproduce

1. Build controlee
a) scripts/examples/gn_build_example.sh examples/all-clusters-app/linux/ out/all-clusters-app
b) sudo rm /tmp/chip_*
c) Launch app with sudo ./out/all-clusters-app/chip-all-clusters-app --wifi
2. Build Controller 
a)  ./scripts/build_python.sh --clusters_for_ip_commissioning true --chip_detail_logging true --chip_mdns platform
b) launch controller  $ chip-device-ctrl -n 9999
c) connect -ble 3840 20202021 12344321

Here is controller log
~~~~~~~~~~~~~~~~~~

chip-device-ctrl > connect -ble 3840 20202021 12344321
Device is assigned with nodeid = 12344321
[1632163222.726891][163780:163788] CHIP:SC: Assigned local session key ID 1
[1632163222.727097][163780:163788] CHIP:IN: Build plaintext message 0xffff76f7b1c0 to 0x0000000000000000 of type 32 and protocolId 0 on exchange 31631 with MessageCounter 320294574.
[1632163222.727174][163780:163788] CHIP:IN: Sending plaintext msg 0xffff76f7b1c0 to 0x0000000000000000 at utc time: 869656582 msec
[1632163222.727219][163780:163788] CHIP:IN: Sending msg on generic transport
[1632163222.727265][163780:163788] CHIP:IN: Message appended to BLE send queue
[1632163222.727307][163780:163788] CHIP:SC: Sent PBKDF param request
[1632163222.727372][163780:163788] CHIP:CTL: SyncSetKeyValue on StartKeyID
[1632163222.727850][163780:163824] CHIP:DL: TRACE: Bluez mainloop starting Thread
[1632163222.728089][163780:163784] CHIP:DL: TRACE: Bus acquired for name C-7fc4
[1632163222.738952][163780:163788] CHIP:DL: PlatformBlueZInit init success
[1632163222.745181][163780:163784] CHIP:BLE: BLE removing known devices.
[1632163222.746934][163780:163784] CHIP:BLE: BLE initiating scan.
[1632163223.177155][163780:163784] CHIP:BLE: Device 5F:A2:16:89:D2:E8 does not look like a CHIP device.
[1632163223.209088][163780:163784] CHIP:BLE: Device 53:64:48:90:DB:92 does not look like a CHIP device.
[1632163223.224314][163780:163784] CHIP:BLE: Device 69:47:EA:D2:58:EF does not look like a CHIP device.
[1632163223.230465][163780:163784] CHIP:BLE: Device 7A:7D:36:5E:5A:EF does not look like a CHIP device.
[1632163223.286877][163780:163784] CHIP:BLE: Device 4C:CB:C8:FA:57:F7 does not look like a CHIP device.
[1632163223.293974][163780:163784] CHIP:BLE: Device 54:6E:31:CA:1F:B3 does not look like a CHIP device.
[1632163223.295279][163780:163784] CHIP:BLE: Device 49:42:C3:E9:98:A9 does not look like a CHIP device.
[1632163223.301933][163780:163784] CHIP:BLE: Device 4E:8E:29:C7:A4:05 does not look like a CHIP device.
[1632163223.326934][163780:163784] CHIP:BLE: Device 7C:3B:21:6B:08:D7 does not look like a CHIP device.
[1632163223.388569][163780:163784] CHIP:BLE: Device 35:54:B9:7D:5A:DB does not look like a CHIP device.
[1632163223.529109][163780:163784] CHIP:BLE: Device 2F:D8:51:76:4F:D1 does not look like a CHIP device.
[1632163223.849086][163780:163784] CHIP:BLE: Device 54:6E:31:CA:1F:B3 does not look like a CHIP device.
[1632163224.388422][163780:163784] CHIP:BLE: Device E4:20:74:8E:20:C3 does not look like a CHIP device.
[1632163224.517046][163780:163784] CHIP:BLE: Device FF:8E:7E:77:29:34 does not look like a CHIP device.
[1632163232.750974][163780:163784] CHIP:IN: Clearing BLE pending packets.
[1632163232.751679][163780:163784] CHIP:IN: BleConnection Error: ../../src/platform/Linux/BLEManagerImpl.cpp:821: CHIP Error 0x00000032: Timeout
[1632163252.729005][163780:163788] CHIP:CTL: SyncSetKeyValue on StartKeyID
Failed to establish secure session to device: 50
[1632163252.729402][163780:163788] CHIP:SC: PASESession timed out while waiting for a response from the peer. Expected message type was 33
CHIP Error 0x00000032: Timeout
[1632163252.729482][163780:163788] CHIP:CTL: SyncSetKeyValue on StartKeyID
Failed to establish secure session to device: 50

Raspi Device Log
~~~~~~~~~~~~~~
$ sudo ./out/all-clusters-app/chip-all-clusters-app --wifi
[1632163075.935912][6080:6080] CHIP:DL: writing settings to file (/tmp/chip_factory.ini-KzmwtY)
[1632163075.936115][6080:6080] CHIP:DL: renamed tmp file to file (/tmp/chip_factory.ini)
[1632163075.936321][6080:6080] CHIP:DL: writing settings to file (/tmp/chip_config.ini-4Bq0fY)
[1632163075.936434][6080:6080] CHIP:DL: renamed tmp file to file (/tmp/chip_config.ini)
[1632163075.936577][6080:6080] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-36s6UW)
[1632163075.936682][6080:6080] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1632163075.936884][6080:6080] CHIP:DL: Device Configuration:
[1632163075.936913][6080:6080] CHIP:DL:   Serial Number: TEST_SN
[1632163075.936933][6080:6080] CHIP:DL:   Vendor Id: 9050 (0x235A)
[1632163075.936953][6080:6080] CHIP:DL:   Product Id: 65279 (0xFEFF)
[1632163075.936974][6080:6080] CHIP:DL:   Product Revision: 0
[1632163075.936995][6080:6080] CHIP:DL:   Setup Pin Code: 20202021
[1632163075.937016][6080:6080] CHIP:DL:   Setup Discriminator: 3840 (0xF00)
[1632163075.937038][6080:6080] CHIP:DL:   Manufacturing Date: (not set)
[1632163075.937056][6080:6080] CHIP:DL:   Device Type: 65535 (0xFFFF)
[1632163075.937109][6080:6080] CHIP:SVR: SetupQRCode: [MT:YNJV7VSC00KA0648G00]
[1632163075.937134][6080:6080] CHIP:SVR: Copy/paste the below URL in a browser to see the QR Code:
[1632163075.937192][6080:6080] CHIP:SVR: https://dhrishi.github.io/connectedhomeip/qrcode.html?data=MT%3AYNJV7VSC00KA0648G00
[1632163075.937226][6080:6080] CHIP:SVR: Manual pairing code: [34970112332]
[1632163075.940998][6080:6083] CHIP:DL: wpa_supplicant: connected to wpa_supplicant proxy
[1632163075.942306][6080:6083] CHIP:DL: wpa_supplicant: WiFi interface: /fi/w1/wpa_supplicant1/Interfaces/0
[1632163075.950897][6080:6083] CHIP:DL: wpa_supplicant: connected to wpa_supplicant interface proxy
[1632163076.037878][6080:6080] CHIP:ZCL: Using ZAP configuration...
[1632163076.038812][6080:6080] CHIP:ZCL: deactivate report event
[1632163076.038881][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.038936][6080:6080] CHIP:ZCL: 0xaaaad21ad378ep 1 clus 101 attr  3 not supported
[1632163076.038987][6080:6080] CHIP:ZCL: Failed to write DoorState attribute: 0x86
[1632163076.039036][6080:6080] CHIP:ZCL: 0xaaaad21ad378ep 1 clus 101 attr 21 not supported
[1632163076.039084][6080:6080] CHIP:ZCL: Failed to write Language attribute: 0x86
[1632163076.039332][6080:6080] CHIP:ZCL: OpCreds: Initiating OpCreds cluster by writing fabrics list from fabric table.
[1632163076.039385][6080:6080] CHIP:DIS: Set the fabric pairing table delegate
[1632163076.039431][6080:6080] CHIP:ZCL: OpCreds: Call to writeFabricsIntoFabricsListAttribute
[1632163076.039481][6080:6080] CHIP:ZCL: OpCreds: Stored 0 fabrics in fabrics list attribute.
[1632163076.039537][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.039591][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.039651][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.039703][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.039756][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.039809][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.039863][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.039933][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.039989][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.040040][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.040102][6080:6080] CHIP:ZCL: Start identify callback on endpoint 1 time 0
[1632163076.040151][6080:6080] CHIP:ZCL: Stop identify callback on endpoint 1
[1632163076.040202][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.040255][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.040306][6080:6080] CHIP:ZCL: Window Covering Cluster init
[1632163076.040353][6080:6080] CHIP:ZCL: Initialize PCC Server Cluster [EP:1]
[1632163076.040423][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.040477][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.040533][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.040589][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.040642][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.040693][6080:6080] CHIP:ZCL: WARNING: ATTRIBUTES ARE NOT BEING STORED IN FLASH! 
[1632163076.040739][6080:6080] CHIP:ZCL: DEVICE WILL NOT FUNCTION PROPERLY AFTER REBOOTING!!
[1632163076.040791][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.040844][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.040895][6080:6080] CHIP:ZCL: Failed to send IAS Zone update. Err 0x70
[1632163076.040953][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.041004][6080:6080] CHIP:DMG: AttributePath is not interested
[1632163076.041441][6080:6080] CHIP:DL: writing settings to file (/tmp/chip_kvs-2xrAjY)
[1632163076.041779][6080:6080] CHIP:DL: renamed tmp file to file (/tmp/chip_kvs)
[1632163076.041971][6080:6080] CHIP:DIS: Init fabric pairing table with server storage
1632163076.042035][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042101][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042162][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042220][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042277][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042334][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042391][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042448][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042505][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042562][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042619][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042675][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042733][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042790][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042846][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042904][6080:6080] CHIP:SVR: Retrieved value from server storage.
[1632163076.042971][6080:6080] CHIP:IN: UDP::Init bind&listen port=5540
[1632163076.043180][6080:6080] CHIP:IN: UDP::Init bound to port=5540
[1632163076.043242][6080:6080] CHIP:IN: UDP::Init bind&listen port=5540
[1632163076.043418][6080:6080] CHIP:IN: UDP::Init bound to port=5540
[1632163076.043474][6080:6080] CHIP:IN: TransportMgr initialized
[1632163076.043730][6080:6080] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-vhgMlV)
[1632163076.044613][6080:6080] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1632163076.044709][6080:6080] CHIP:DL: NVS set: chip-counters/GlobalMCTR = 1000 (0x3E8)
[1632163076.044986][6080:6080] CHIP:SVR: Network already provisioned. Disabling BLE advertisement
[1632163076.045065][6080:6080] CHIP:DIS: Mdns StartServer mode=0
[1632163076.048754][6080:6080] CHIP:DL: MDNS failed to join multicast group on wlan0 for address type IPv4: ../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/inet/IPEndPointBasis.cpp:259: Inet Error 0x00000110: Address not found
[1632163076.051492][6080:6080] CHIP:DIS: CHIP minimal mDNS started advertising.
[1632163076.051844][6080:6080] CHIP:DIS: Replying to DNS-SD service listing request
[1632163076.051871][6080:6080] CHIP:DIS: Replying to DNS-SD service listing request
[1632163076.051891][6080:6080] CHIP:DIS: Replying to DNS-SD service listing request

[1632163076.053385][6080:6080] CHIP:DIS: Failed to find a valid admin pairing. Node ID unknown
[1632163076.053404][6080:6080] CHIP:DIS: Start dns-sd server - no current nodeId
[1632163076.053708][6080:6080] CHIP:DIS: Using wifi MAC for hostname
[1632163076.053794][6080:6080] CHIP:DIS: Advertise commission parameter vendorID=9050 productID=65279 discriminator=3840/00
[1632163076.053868][6080:6080] CHIP:DIS: CHIP minimal mDNS configured as 'Commissionable node device'.
[1632163076.053891][6080:6080] CHIP:DIS: Scheduling Discovery timeout in secs=900
[1632163076.053924][6080:6080] CHIP:IN: CASE Server enabling CASE session setups
[1632163076.053949][6080:6080] CHIP:SVR: Server Listening...
[1632163076.054233][6080:6086] CHIP:DL: TRACE: Bluez mainloop starting Thread
[1632163076.054351][6080:6083] CHIP:DL: TRACE: Bus acquired for name MATTER-3840
[1632163076.054570][6080:6083] CHIP:DL: CREATE service object at /chipoble/17c0/service
[1632163076.055321][6080:6083] CHIP:DL: Create characteristic object at /chipoble/17c0/service/c1
[1632163076.055856][6080:6083] CHIP:DL: Create characteristic object at /chipoble/17c0/service/c2
[1632163076.056202][6080:6083] CHIP:DL: CHIP BTP C1 /chipoble/17c0/service
[1632163076.056231][6080:6083] CHIP:DL: CHIP BTP C2 /chipoble/17c0/service
[1632163076.056250][6080:6083] CHIP:DL: CHIP_ENABLE_ADDITIONAL_DATA_ADVERTISING is TRUE
[1632163076.056271][6080:6083] CHIP:DL: Create characteristic object at /chipoble/17c0/service/c3
[1632163076.056732][6080:6083] CHIP:DL: CHIP BTP C3 /chipoble/17c0/service
[1632163076.063417][6080:6080] CHIP:DL: PlatformBlueZInit init success
[1632163076.069533][6080:6083] CHIP:DL: BluezPeripheralRegisterAppDone done
[1632163076.069601][6080:6080] CHIP:DL: HandlePlatformSpecificBLEEvent 16392
[1632163154.229765][6080:6080] CHIP:DIS: Replying to DNS-SD service listing request
[1632163154.229858][6080:6080] CHIP:DIS: Replying to DNS-SD service listing request
[1632163154.229910][6080:6080] CHIP:DIS: Replying to DNS-SD service listing request
[1632163154.229964][6080:6080] CHIP:DIS: Replying to DNS-SD service listing request
[1632163154.230017][6080:6080] CHIP:DIS: Replying to DNS-SD service listing request
[1632163154.230067][6080:6080] CHIP:DIS: Replying to DNS-SD service listing request
[1632163154.230173][6080:6080] CHIP:DIS: Replying to DNS-SD service listing request
[1632163154.230233][6080:6080] CHIP:DIS: Broadcasting mDns reply
[1632163154.465062][6080:6080] CHIP:DIS: Broadcasting mDns reply

### PR DESCRIPTION
**Pull request by pan-apple**
#### Problem
* Fixes #9832 

#### Change overview
Server application was checking the network status to determine if the the device is already provisioned. This code was added long ago, and worked since fabric commissioning was not supported then.

This change uses fabric table to determine if the device is currently commissioned, instead of checking for network status.

#### Testing
Tested BLE commissioning process on m5stack (by configuring it with WiFi credentials through menuconfig) and chip-tool.

### CODE REVIEW

**Review by msandstedt — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

File: src/app/server/Server.cpp [hunk 1]
```diff
@@ -135,10 +135,10 @@ CHIP_ERROR Server::Init(AppDelegate * delegate, uint16_t secureServicePort, uint
         ChipLogProgress(AppServer, "Rendezvous and secure pairing skipped");
         SuccessOrExit(err = AddTestCommissioning());
     }
-    else if (DeviceLayer::ConnectivityMgr().IsWiFiStationProvisioned() || DeviceLayer::ConnectivityMgr().IsThreadProvisioned())
+    else if (GetFabricTable().FabricCount() != 0)
     {
-        // If the network is already provisioned, proactively disable BLE advertisement.
-        ChipLogProgress(AppServer, "Network already provisioned. Disabling BLE advertisement");
+        // The device is already commissioned, proactively disable BLE advertisement.
+        ChipLogProgress(AppServer, "Fabric already provisioned. Disabling BLE advertisement");
```
Comment (bzbarsky-apple) [inline src/app/server/Server.cpp:141]:
```suggestion
        ChipLogProgress(AppServer, "Fabric already commissioned. Disabling BLE advertisement");
```

**Review by bzbarsky-apple — APPROVED** [review]
