### PR TITLE
Fix generation and parsing of Manual Setup Codes to match specification

### LINKED ISSUE #5328: Generated setup code that is 21 bytes long formatted incorrectly
Per the spec, 21 bytes setup code should have 1st digit b.w. 4 and 7 if VID and PID are present, Ref attached spec
The current generated setup code seem to have 1st digit as 0 even if the VID and PID are present. 

Also we need to make sure chip-tool is able to parse the new setup code. 
Ex: $ sudo out/host/chip-tool payload parse-setup-payload 039506169709050652794
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:SPL: Parsing decimalRepresentation: 039506169709050652794
CHIP:SPL: RequiresCustomFlow: 1
CHIP:SPL: VendorID: 9050
CHIP:SPL: Version: 0
CHIP:SPL: ProductID: 65279
CHIP:SPL: Discriminator: 0
CHIP:SPL: SetUpPINCode: 12345678
CHIP:SPL: RendezvousInformation: 0

Table 34. Encoding Method with Vendor and Product ID’s included (VID_PID_Present == 1)
Screen Shot 2021-03-11 at 12 30 02 PM

### PR DESCRIPTION
**Pull request by jrhees-cae**
Fixes #5328

Generation and Parsing of Manual Setup Codes was incorrect.

Per specification, the Manual setup code is formatted as follows:

The binary data is encoded to a decimal string split into 5 chunks:
     <1-digit/3-bits><5 digits/16-bits><4-digits/13-bits><5-digits/16-bits><5-digits/16-bits>:

- <1 digit> Represents:
    - <bits 1..0> Discriminator <bits 11.10>
    - <bit 2> VID/PID present flag
- <5 digits> Represents:
    - <bits 13..0> PIN Code <bits 13..0>
    - <bits 15..14> Discriminator <bits 9..8>
- <4 digits> Represents:
    - <bits 12..0> PIN Code <bits 26..14>
- <5 digits> Vendor ID
- <5 digits> Product ID

Updated Manual Code Generator
Updated Manual Code Parser
Updated Test Vectors

### CODE REVIEW

**Comment by jrhees-cae** [comment]
@woody-apple Please add Shana as a reviewer. Thx

**Comment by shana-apple** [comment]
Looks good, thanks for fixing up/adding unit tests as well

**Review by shana-apple — APPROVED** [review]

File: src/setup_payload/ManualSetupPayloadGenerator.cpp [hunk 1]
```diff
@@ -31,17 +31,60 @@
...
-    constexpr int pinCodeOffset       = discriminatorOffset + kManualSetupDiscriminatorFieldLengthInBits;
-    uint32_t result                   = payload.requiresCustomFlow ? 1 : 0;
+    /* <1 digit> Represents:
+     *     - <bits 1..0> Discriminator <bits 11.10>
+     *     - <bit 2> VID/PID present flag
+     */
 
-    static_assert(kManualSetupDiscriminatorFieldBitMask <= UINT32_MAX >> discriminatorOffset, "Discriminator won't fit");
-    result |= static_cast<uint32_t>((payload.discriminator & kManualSetupDiscriminatorFieldBitMask) << discriminatorOffset);
+    constexpr int discriminatorShift     = (kPayloadDiscriminatorFieldLengthInBits - kManualSetupDiscriminatorFieldLengthInBits +
```
Comment (andy31415) [inline src/setup_payload/ManualSetupPayloadGenerator.cpp:41]: nit: since these are constants, we could name these `kDiscriminatorShift` and `kDiscriminatorMask`

**Review by andy31415 — APPROVED** [review]

**Comment by markus-becker-tridonic-com** [comment]
label TE1 missing.

File: src/setup_payload/SetupPayload.h [hunk 2]
```diff
@@ -40,16 +40,31 @@ const int kCustomFlowRequiredFieldLengthInBits       = 1;
 const int kRendezvousInfoFieldLengthInBits           = 8;
 const int kPayloadDiscriminatorFieldLengthInBits     = 12;
 const int kManualSetupDiscriminatorFieldLengthInBits = 4;
-const int kManualSetupDiscriminatorFieldBitMask      = (1 << kManualSetupDiscriminatorFieldLengthInBits) - 1;
-const int kSetupPINCodeFieldLengthInBits             = 27;
-const int kPaddingFieldLengthInBits                  = 5;
+const int kManualSetupDiscriminatorShiftInBits =
+    (kPayloadDiscriminatorFieldLengthInBits - kManualSetupDiscriminatorFieldLengthInBits);
+const int kManualSetupDiscriminatorFieldBitMask       = ((1 << kManualSetupDiscriminatorFieldLengthInBits) - 1);
```
Comment (Damian-Nordic) [inline src/setup_payload/SetupPayload.h:45]: It's unused, right?

File: src/setup_payload/ManualSetupPayloadGenerator.cpp [hunk 3]
```diff
@@ -31,17 +31,60 @@
...
+                                        kManualSetupChunk1DiscriminatorMsbitsLength);
```
Comment (Damian-Nordic) [inline src/setup_payload/ManualSetupPayloadGenerator.cpp:42]: It doesn't matter since `kManualSetupChunk1DiscriminatorMsbitsLength` == `kManualSetupChunk2DiscriminatorLsbitsLength`, but I guess the formula should contain `kManualSetupChunk2DiscriminatorLsbitsLength` instead of `kManualSetupChunk1DiscriminatorMsbitsLength`, right? Or just do `discriminatorShift = kPayloadDiscriminatorFieldLengthInBits - kManualSetupChunk1DiscriminatorMsbitsLength`.

File: src/setup_payload/ManualSetupPayloadGenerator.cpp (hunk 1 above)
Comment (jrhees-cae) [reply src/setup_payload/ManualSetupPayloadGenerator.cpp:41]: Removed unused constants

File: src/setup_payload/SetupPayload.h (hunk 2 above)
Comment (jrhees-cae) [reply src/setup_payload/SetupPayload.h:45]: Removed unused constants

File: src/setup_payload/ManualSetupPayloadGenerator.cpp (hunk 3 above)
Comment (jrhees-cae) [reply src/setup_payload/ManualSetupPayloadGenerator.cpp:42]: Good catch. I like the simpler equation. Changed

**Review by Damian-Nordic — APPROVED** [review]

**Comment by jrhees-cae** [comment]
@vivien-apple @kkasperczyk-no I need someone to merge this PR. It is unassigned and I am not authorized to merge. Thx!

**Comment by kkasperczyk-no** [comment]
@jrhees-cae I see that CI is failing for QEMU / ESP32, so you have to fix this before your PR will be merged. If you don't see an obvious reason for that happening I recommend force push to trigger jobs re-run.

**Comment by jrhees-cae** [comment]
@kkasperczyk-no Looks like the ESP32 has passed this time

**Comment by kkasperczyk-no** [comment]
@Damian-Nordic @LuDuda could some of you merge that one? I'm also not authorized to do this.

**Review by jmartinez-silabs — APPROVED** [review]
