### PR TITLE
Unblock TLS cert rotation on max client usage

### LINKED ISSUE #42107: [BUG] TLS cert rotation is blocked when max client certs are in use
### Reproduction steps

Per the spec, this check should have been made only on the NULL CCDID cases (i.e. when a new client cert is being added), but it happens to occur for all cases in the SDK, essentially blocking update/rotation of existing client certs once the max (for adds) is reached: https://github.com/project-chip/connectedhomeip/blob/6a5cff3bb16871ff8af7d3bd2af11be439544785/src/app/clusters/tls-certificate-management-server/tls-certificate-management-server.cpp#L365

Image

### Bug prevalence

Consistent

### GitHub hash of the SDK that was being used

682ef15ccc73b0a646073f324f6dca2b31a73c4b

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by samadDotDev**
#### Summary

Per the spec, this check should only be made on the NULL CCDID cases (i.e. when a new client cert is being added). Previously, it occured for all cases, essentially blocking update/rotation of existing client certs once the max (for adds) is reached.

[image](https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/tls/TLSCertificateManagement.adoc#683-effect-on-receipt)

#### Related issues

Fixes https://github.com/project-chip/connectedhomeip/issues/42107

#### Testing

Manually tested with the controller (updating client cert after exhausting the slots)

### CODE REVIEW

**Review by vnkavali — APPROVED** [review]

**Review by marktrayer — APPROVED** [review]

File: src/app/clusters/tls-certificate-management-server/tls-certificate-management-server.cpp [hunk 1]
```diff
@@ -359,11 +359,16 @@ void TlsCertificateManagementServer::HandleGenerateClientCsr(HandlerContext & ct
...
 
     auto fabric = ctx.mCommandHandler.GetAccessingFabricIndex();
-    uint8_t numClientCerts;
-    VerifyOrReturn(mCertificateTable.GetClientCertificateCount(fabric, numClientCerts) == CHIP_NO_ERROR,
-                   ctx.mCommandHandler.AddStatus(ctx.mRequestPath, Status::Failure));
-    VerifyOrReturn(numClientCerts < mMaxClientCertificates,
-                   ctx.mCommandHandler.AddStatus(ctx.mRequestPath, Status::ResourceExhausted));
+
+    // If no CCDID is specified, ensure we have capacity for a new client certificate.
+    if (req.ccdid.IsNull())
```
Comment (yufengwangca) [inline src/app/clusters/tls-certificate-management-server/tls-certificate-management-server.cpp:364]: Per spec, we have other actions need to take if CCDID is NULL, not just return the proper status, are those actions get handled somewhere else?

Comment (samadDotDev) [reply src/app/clusters/tls-certificate-management-server/tls-certificate-management-server.cpp:364]: Yes those are occuring in the delegate `mDelegate.GenerateClientCsr`. The PR is just fixing the first check that needs to occur when CCD ID is null (highlighted as red in the screenshot posted in the description).

Edit: some checks are missing within the delegate as Pradip pointed out later, tracking separate issue https://github.com/project-chip/connectedhomeip/issues/42296 for that.

File: src/app/clusters/tls-certificate-management-server/tls-certificate-management-server.cpp [hunk 2]
```diff
@@ -359,11 +359,16 @@ void TlsCertificateManagementServer::HandleGenerateClientCsr(HandlerContext & ct
...
+    {
+        uint8_t numClientCerts;
+        VerifyOrReturn(mCertificateTable.GetClientCertificateCount(fabric, numClientCerts) == CHIP_NO_ERROR,
+                       ctx.mCommandHandler.AddStatus(ctx.mRequestPath, Status::Failure));
+        VerifyOrReturn(numClientCerts < mMaxClientCertificates,
+                       ctx.mCommandHandler.AddStatus(ctx.mRequestPath, Status::ResourceExhausted));
+    }
 
     auto status = mDelegate.GenerateClientCsr(ctx.mRequestPath.mEndpointId, fabric, req, [&](auto & response) -> Status {
```
Comment (pidarped) [inline src/app/clusters/tls-certificate-management-server/tls-certificate-management-server.cpp:373]: Unless I am missing something, it seems the delegate function is not returning the required status codes defined in the Spec.viz., NotFound in the not-null case, DynamicConstraintError in the null case, etc. 
Not directly related to the issue this PR addresses though.
https://github.com/project-chip/connectedhomeip/blob/master/examples/all-clusters-app/all-clusters-common/src/tls-certificate-management-instance.cpp#L298.

Comment (samadDotDev) [reply src/app/clusters/tls-certificate-management-server/tls-certificate-management-server.cpp:373]: For the null case, I could not find the `DynamicContraintError` (or the key collission check for that error), so I'll defer to @gmarcosb if he is aware of the context.

For the non-null case, I think the `NotFound` is returned from `PrepareClientCertificate` (in `CHIP_ERROR_NOT_FOUND` if you follow that lookup trail), but it's getting reduced/generalized to `Status::Failure` in the delegate function so that's something which certainly needs to be fixed. 

As it is unrelated to the issue/fix in this PR, I can create a separate issue for these bits.

Comment (samadDotDev) [reply src/app/clusters/tls-certificate-management-server/tls-certificate-management-server.cpp:373]: Created https://github.com/project-chip/connectedhomeip/issues/42296 to track those as separate issues.

Comment (pidarped) [reply src/app/clusters/tls-certificate-management-server/tls-certificate-management-server.cpp:373]: Yes, exactly. That's what I observed that the errors from that function were converted into a Status::Failure. 
Thanks for creating the issue.

**Review by pidarped — APPROVED** [review]

**Comment by samadDotDev** [comment]
This has been cherry-picked onto 1.5 branch by @yufengwangca as part of code-driven CP in https://github.com/project-chip/connectedhomeip/pull/42740. Removing the `1.5.1-required` label.
