### PR TITLE
[nrfconnect] Added handling Identify TriggerEffect command

### LINKED ISSUE #19419: Pre SVE Testing: TC-I-3.2 step 4 giving 0x85 error for all-clusters-app on nrfconnect
As per step 4 of TC-I-3.2, DUT sends a TriggerEffect command to the Test Harness, with any supported EffectIdentifier argument and EffectVariant set to 0 .

Sent the chip tool command - ./chip-tool identify trigger-effect 0 0 1 1 

Response shows 0x85 error:
[1654816055916] [2257:2570756] CHIP: [DMG] ICR moving to [ResponseRe]
[1654816055916] [2257:2570756] CHIP: [DMG] InvokeResponseMessage =
[1654816055916] [2257:2570756] CHIP: [DMG] {
[1654816055916] [2257:2570756] CHIP: [DMG] 	suppressResponse = false, 
[1654816055916] [2257:2570756] CHIP: [DMG] 	InvokeResponseIBs =
[1654816055916] [2257:2570756] CHIP: [DMG] 	[
[1654816055916] [2257:2570756] CHIP: [DMG] 		InvokeResponseIB =
[1654816055916] [2257:2570756] CHIP: [DMG] 		{
[1654816055916] [2257:2570756] CHIP: [DMG] 			CommandStatusIB =
[1654816055916] [2257:2570756] CHIP: [DMG] 			{
[1654816055916] [2257:2570756] CHIP: [DMG] 				CommandPathIB =
[1654816055916] [2257:2570756] CHIP: [DMG] 				{
[1654816055916] [2257:2570756] CHIP: [DMG] 					EndpointId = 0x1,
[1654816055916] [2257:2570756] CHIP: [DMG] 					ClusterId = 0x3,
[1654816055916] [2257:2570756] CHIP: [DMG] 					CommandId = 0x40,
[1654816055916] [2257:2570756] CHIP: [DMG] 				},
[1654816055916] [2257:2570756] CHIP: [DMG] 				
[1654816055916] [2257:2570756] CHIP: [DMG] 				StatusIB =
[1654816055916] [2257:2570756] CHIP: [DMG] 				{
[1654816055916] [2257:2570756] CHIP: [DMG] 					status = 0x85 (INVALID_COMMAND),
[1654816055916] [2257:2570756] CHIP: [DMG] 				},
[1654816055916] [2257:2570756] CHIP: [DMG] 				
[1654816055916] [2257:2570756] CHIP: [DMG] 			},
[1654816055916] [2257:2570756] CHIP: [DMG] 			
[1654816055916] [2257:2570756] CHIP: [DMG] 		},
[1654816055916] [2257:2570756] CHIP: [DMG] 		
[1654816055916] [2257:2570756] CHIP: [DMG] 	],
[1654816055916] [2257:2570756] CHIP: [DMG] 	
[1654816055916] [2257:2570756] CHIP: [DMG] 	InteractionModelRevision = 1
[1654816055916] [2257:2570756] CHIP: [DMG] },
[1654816055916] [2257:2570756] CHIP: [DMG] Received Command Response Status for Endpoint=1 Cluster=0x0000_0003 Command=0x0000_0040 Status=0x85
[1654816055916] [2257:2570756] CHIP: [TOO] Error: IM Error 0x00000585: General error: 0x85 (INVALID_COMMAND)
[1654816055916] [2257:2570756] CHIP: [DMG] ICR moving to [AwaitingDe]
[1654816055916] [2257:2570756] CHIP: [EM] Sending Standalone Ack for MessageCounter:46388802 on exchange 4805i
[1654816055916] [2257:2570756] CHIP: [IN] Prepared secure message 0x7000075064f0 to 0x0000000000000001 (1)  of type 0x10 and protocolId (0, 0) on exchange 4805i with MessageCounter:40490913.
[1654816055916] [2257:2570756] CHIP: [IN] Sending encrypted msg 0x7000075064f0 with MessageCounter:40490913 to 0x0000000000000001 (1) at monotonic time: 000000000EE7B721 msec
[1654816055916] [2257:2570756] CHIP: [EM] Flushed pending ack for MessageCounter:46388802 on exchange 4805i
[1654816055916] [2257:2570751] CHIP: [CTL] Shutting down the commissioner
[1654816055916] [2257:2570751] CHIP: [CTL] Shutting down the controller
[1654816055916] [2257:2570751] CHIP: [CTL] Shutting down the commissioner
[1654816055916] [2257:2570751] CHIP: [CTL] Shutting down the controller
[1654816055916] [2257:2570751] CHIP: [IN] Expiring all connections for fabric 1!!
[1654816055916] [2257:2570751] CHIP: [IN] SecureSession[0x7f8561810280]: MarkForRemoval Type:2 LSID:22200
[1654816055916] [2257:2570751] CHIP: [IN] SecureSession[0x7f8561810280]: Released - Type:2 LSID:22200
[1654816055916] [2257:2570751] CHIP: [CTL] Shutting down the commissioner
[1654816055916] [2257:2570751] CHIP: [CTL] Shutting down the controller
[1654816055916] [2257:2570751] CHIP: [IN] Expiring all connections for fabric 2!!
[1654816055916] [2257:2570751] CHIP: [CTL] Shutting down the commissioner
[1654816055916] [2257:2570751] CHIP: [CTL] Shutting down the controller
[1654816055916] [2257:2570751] CHIP: [IN] Expiring all connections for fabric 3!!
[1654816055916] [2257:2570751] CHIP: [CTL] Shutting down the System State, this will teardown the CHIP Stack
[1654816055916] [2257:2570751] CHIP: [DMG] IM WH moving to [Uninitialized]
[1654816055916] [2257:2570751] CHIP: [DMG] IM WH moving to [Uninitialized]
[1654816055916] [2257:2570751] CHIP: [DMG] IM WH moving to [Uninitialized]
[1654816055916] [2257:2570751] CHIP: [DMG] IM WH moving to [Uninitialized]
[1654816055916] [2257:2570751] CHIP: [DMG] All ReadHandler-s are clean, clear GlobalDirtySet
[1654816055916] [2257:2570751] CHIP: [BLE] CancelConnection
[1654816055916] [2257:2570751] CHIP: [DL] Inet Layer shutdown
[1654816055916] [2257:2570751] CHIP: [DL] BLE shutdown
[1654816055916] [2257:2570751] CHIP: [DL] System Layer shutdown
[1654816055916] [2257:2570751] CHIP: [TOO] Run command failure: IM Error 0x00000585: General error: 0x85 (INVALID_COMMAND)

### PR DESCRIPTION
**Pull request by kkasperczyk-no**
#### Problem
All-clusters-app for nrfconnect doesn't support handling TriggerEffect command, despite it is enabled in the .zap
configuration.

#### Change overview
Added method that handles TriggerEffect callback.

#### Testing
Tested manually following the procedure from: https://github.com/project-chip/connectedhomeip/issues/19419.

Fixes: https://github.com/project-chip/connectedhomeip/issues/19419

### CODE REVIEW

File: examples/all-clusters-minimal-app/nrfconnect/main/AppTask.cpp [hunk 1]
```diff
@@ -53,10 +54,48 @@ using namespace ::chip::DeviceLayer;
...
 
+namespace {
+
 static LEDWidget sStatusLED;
 static UnusedLedsWrapper<3> sUnusedLeds{ { DK_LED2, DK_LED3, DK_LED4 } };
 static k_timer sFunctionTimer;
 
+constexpr EndpointId kIdentifyEndpointId = 1;
+
+void OnIdentifyTriggerEffect(Identify * identify)
```
Comment (Damian-Nordic) [inline examples/all-clusters-minimal-app/nrfconnect/main/AppTask.cpp:65]: Isn't all-clusters-minimal-app supposed to have all optional features disabled? If so, TriggerEffect should be disabled in ZAP file, right?

Comment (kkasperczyk-no) [reply examples/all-clusters-minimal-app/nrfconnect/main/AppTask.cpp:65]: Right, it is disabled. I added it here without checking. I will remove it for all-clusters-minimal-app.

**Review by Damian-Nordic — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
