### PR TITLE
[PASESession] TLV Reading Fixes

### LINKED ISSUE #30476: `CASESession.cpp` and `PASESession.cpp` should be using named tag
This came up during PR review [here](https://github.com/project-chip/connectedhomeip/pull/30405#discussion_r1393159270). 

All TLV tags used in this file are using numbers instead of some sort of named tag making it more readable
Example:
```
 ReturnErrorOnFailure(EncodeSessionParameters(TLV::ContextTag(5), mLocalMRPConfig, tlvWriterMsg2));
```

Reason for not cleaning up in PR issue brought up: 
* This has always been there and is an easy cleanup on it own.
* PR is already large and requires approvals. No sense adding burden to reviewers to clean up something not introduced in this PR

### LINKED ISSUE #36959: TLV Reading of Containers often missed a call to ExitContainer
- many instances of Parsing TLV Encodings with Containers, a call to `ExitContainer()` is omitted at the end of Reading that container, this is mostly observed for Top-Level containers at the moment.
- The API contract of `TLVReader::EnterContainer()` clearly indicates that this is needed.
- In addition, not calling `TLVReader::ExitContainer()` has a side-effect of ALLOWING the successful parsing of a received TLV (container) that is not properly terminated (one that did not call EndContainer())  which should  not be allowed.

- Example: (ExitContainerwas completely missed at the end ) : https://github.com/project-chip/connectedhomeip/blob/dedef1fce2c6926a9e82e49531000d31baae1c6f/src/protocols/secure_channel/CASESession.cpp#L1415-L1443
- This was observed in :
  - [x] CASESession.cpp
  - [ ] PASESession.cpp
  - [x] PairingSession.cpp ( A corner case only)

### PR DESCRIPTION
**Pull request by Alami-Amine**
1. Fixes #36959 : Making sure received encoded messages are properly terminated.

2. Adding Sanity Checks that the read TLV data has the expected number of bytes:

3. Adding symbolic TLV Tags 
#### Testing

- Unit Tests with ASAN
- FuzzTests using pw_fuzzer

### CODE REVIEW

File: src/protocols/secure_channel/PASESession.cpp [hunk 1]
```diff
@@ -48,6 +48,56 @@
...
+};
+
+enum class PBKDFParamResponseTags : uint8_t
+{
+    kInitiatorRandom        = 1,
+    kResponderRandom        = 2,
+    kResponderSessionId     = 3,
+    kPbkdfParameters        = 4,
+    kResponderSessionParams = 5,
+
```
Comment (yunhanw-google) [inline src/protocols/secure_channel/PASESession.cpp:69]: remove this extra line, thanks

**Review by yunhanw-google — APPROVED** [review]

File: src/protocols/secure_channel/PASESession.cpp (hunk 1 above)
Comment (Alami-Amine) [reply src/protocols/secure_channel/PASESession.cpp]: done

Comment (Alami-Amine) [reply src/protocols/secure_channel/PASESession.cpp]: done

File: src/protocols/secure_channel/PASESession.cpp [hunk 2]
```diff
@@ -350,33 +401,42 @@ CHIP_ERROR PASESession::HandlePBKDFParamRequest(System::PacketBufferHandle && ms
...
+                                                             tlvReader, mRemoteSessionParams));
         mExchangeCtxt.Value()->GetSessionHandle()->AsUnauthenticatedSession()->SetRemoteSessionParameters(
             GetRemoteSessionParameters());
+
+        err = tlvReader.Next();
     }
 
+    // Future-proofing: CHIP_NO_ERROR will be returned by Next() if we have additional non-parsed TLV Elements, which could
+    // happen in the future if additional elements are added to the specification.
+    VerifyOrExit(err == CHIP_END_OF_TLV || err == CHIP_NO_ERROR, );
```
Comment (tehampson) [inline src/protocols/secure_channel/PASESession.cpp:434]: nit,
```suggestion
    VerifyOrExit(err == CHIP_END_OF_TLV || err == CHIP_NO_ERROR);
```

File: src/protocols/secure_channel/PASESession.cpp [hunk 3]
```diff
@@ -471,59 +533,72 @@ CHIP_ERROR PASESession::HandlePBKDFParamResponse(System::PacketBufferHandle && m
...
+        err = tlvReader.Next();
+        if (err == CHIP_NO_ERROR && tlvReader.GetTag() == AsTlvContextTag(PBKDFParamResponseTags::kResponderSessionParams))
         {
-            SuccessOrExit(err = DecodeSessionParametersIfPresent(TLV::ContextTag(5), tlvReader, mRemoteSessionParams));
+            SuccessOrExit(err = DecodeSessionParametersIfPresent(AsTlvContextTag(PBKDFParamResponseTags::kResponderSessionParams),
+                                                                 tlvReader, mRemoteSessionParams));
             mExchangeCtxt.Value()->GetSessionHandle()->AsUnauthenticatedSession()->SetRemoteSessionParameters(
                 GetRemoteSessionParameters());
+
+            err = tlvReader.Next();
```
Comment (andy31415) [inline src/protocols/secure_channel/PASESession.cpp:562]: The next requirement decouples the error set where we have:
   - set it on line 554 OR
   - set it on line 562 if we have a kResponderSessionParams OR 
   - set it on line 584 OR
   - set it on line 592 if we have a kResponderSessionParams 
Then check it on line 597

This feels hard to follow. Could we centralize the kResponderSessionParams handling? Could we extract it to a method that reads and rolls back if it cannot find it or have some other organization so that code always reads like `err = SomeNext(); VerifyOr... (err == ...)` ?

File: src/protocols/secure_channel/PASESession.cpp [hunk 4]
```diff
@@ -471,59 +533,72 @@ CHIP_ERROR PASESession::HandlePBKDFParamResponse(System::PacketBufferHandle && m
...
         }
     }
+    // Future-proofing: CHIP_NO_ERROR will be returned by Next() if we have additional non-parsed TLV Elements, which could
+    // happen in the future if additional elements are added to the specification.
+    VerifyOrExit(err == CHIP_END_OF_TLV || err == CHIP_NO_ERROR, );
+
+    // Exit Container will fail (return CHIP_END_OF_TLV) if the received encoded message is not properly terminated with an
```
Comment (andy31415) [inline src/protocols/secure_channel/PASESession.cpp:599]: What is the purpose of this comment in helping me read the code? It is true that ExitContainer returns a CHIP_ERROR so can fail. Why does this comment explicitly call out the CHIP_END_OF_TLV error and when it occurs?

Same comment for the copies of this below/throughout.

File: src/protocols/secure_channel/PASESession.cpp [hunk 5]
```diff
@@ -48,6 +48,55 @@
...
+    kCb = 2,
+};
+enum class Pake3Tags : uint8_t
+{
+    kCa = 1,
+};
+
+// Utility to extract the underlying value of TLV Tag enum classes, used in TLV encoding and parsing.
+template <typename Enum>
+constexpr chip::TLV::Tag AsTlvContextTag(Enum e)
```
Comment (tehampson) [inline src/protocols/secure_channel/PASESession.cpp:94]: The linux chip-all-clusters app flash increased by 958 bytes, do we know why? Most of the changes you've made seems like it should barely change.

Personally I have always had trouble fully understanding `constexpr` functions so **I could be very wrong here**: I think a constexpr function will only evaluate at compile time if the arguments themselves are also constexpr. I think there are some circumstances where they can still be evaluated at runtime. Is it possible that the enums result in this actually being determined as runtime instead of compile time?

Not a super pressing concern from me this is more just me asking out of curiosity and trying to learn

File: src/protocols/secure_channel/PASESession.cpp (hunk 4 above)
Comment (Alami-Amine) [reply src/protocols/secure_channel/PASESession.cpp:599]: Just to clarify the importance of ExitContainer()? that having it serves as a check for a missing EndOfContainer terminator in the received message. should i reword it or remove it?

Comment (Alami-Amine) [reply src/protocols/secure_channel/PASESession.cpp:599]: is this better?

```suggestion
    // ExitContainer() acts as a safeguard to ensure that the received encoded message
    // is properly terminated with an EndOfContainer TLV element. If the terminator is missing, CHIP_END_OF_TLV is returned.
```

File: src/protocols/secure_channel/PASESession.cpp (hunk 5 above)
Comment (Alami-Amine) [reply src/protocols/secure_channel/PASESession.cpp:94]: - That is worrying if it's true, can we trust the values from the bloat checker though?

- I am not sure about the possibility for `constexpr` function to get evaluated at run-time, however I tried static_assert the following and it compiled, I guess that confirms that its evaluating at compile-time?
```cpp
    static_assert(AsTlvContextTag(PBKDFParamRequestTags::kPasscodeId) == chip::TLV::ContextTag(3), "error");
```
- any ideas for what to check?

File: src/protocols/secure_channel/PASESession.cpp (hunk 2 above)
Comment (Alami-Amine) [reply src/protocols/secure_channel/PASESession.cpp]: VerifyOrExit requires two arguments, which is why I added the comma,
As discussed privately, this was chosen `VerifyOrExit(err == CHIP_END_OF_TLV || err == CHIP_NO_ERROR, /* No Action */);`

File: src/protocols/secure_channel/PASESession.cpp (hunk 5 above)
Comment (tehampson) [reply src/protocols/secure_channel/PASESession.cpp:94]: I might be wrong, but I think bloat checker compares your branch to tip of tree on master. So it is possible for it to not be accurate. Again don't quote me on that but just something I have had a suspicion about but never spent time validating.

Locally I have compared before and after my changes using
`scripts/tools/memory/report_summary.py --by=region --config-file=scripts/tools/memory/platform/linux.cfg ./out/linux-x64-all-clusters-no-ble-clang/chip-all-clusters-app`

Comment (Alami-Amine) [reply src/protocols/secure_channel/PASESession.cpp:94]: using the script you mentioned:
before --> FLASH      5976427
after   --> FLASH      5976723

the diff is 296, a third of what was reported !(tested using `linux-x64-all-clusters` )

File: src/protocols/secure_channel/PASESession.cpp (hunk 3 above)
Comment (Alami-Amine) [reply src/protocols/secure_channel/PASESession.cpp]: I extracted it to a method `:ReadSessionParamsIfPresent` and made sure a VerifyOr is there after each call of it.

**Review by tehampson — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

File: src/protocols/secure_channel/PASESession.cpp (hunk 4 above)
Comment (Alami-Amine) [reply src/protocols/secure_channel/PASESession.cpp]: Following discussion, the following comment was chosen
```cpp
    // ExitContainer() acts as a safeguard to ensure that the received encoded message is properly terminated with an EndOfContainer
    // TLV element. It is called as an extra validation step to enforce input data structure integrity. Without it, the message may
    // still parse correctly, but malformed or incomplete data might go undetected.
    // ExitContainer() will return CHIP_END_OF_TLV if the EndOfContainer TLV element terminator is missing.
```

**Review by andy31415 — APPROVED** [review]
