### PR TITLE
clear dstoffset when DSTOffsetRequired is true

### LINKED ISSUE #28637: [BUG] TIMESYNC - DSTOffset is not cleared and No DSTEmpty event is generated if TimeZoneDatabase is set to None
### Reproduction steps

1. Configure DUT to have TimeZoneDatabase == TimeZoneDatabaseEnum:None
2. Write TimeZone attribute
3. Write  DSTOffset attribute
4. Write TimeZone attribute with different values from step 2
5. Read DSTOffset attribute (should be empty list)

According to the spec: 
"If the node supports a time zone database and it has information available for the time zone that will be applied, it MAY set its DSTOffset attribute list, otherwise the DSTOffset attribute list SHALL be set to an empty list. A DSTTableEmpty event SHALL be generated if the DSTOffset attribute list is empty. A DSTStatus event SHALL be generated if the node was previously applying a DST offset.

It appears that the check has the wrong logic here: https://github.com/project-chip/connectedhomeip/blob/7353fd6cab156b2f5cf5ca432f005cf33312a1fe/src/app/clusters/time-synchronization-server/time-synchronization-server.cpp#L918C27-L918C27

### Bug prevalence

Consistent (if DUT has TimeZoneDatabase set to None)

### GitHub hash of the SDK that was being used

main

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by fessehaeve**
Fixes https://github.com/project-chip/connectedhomeip/issues/28637

### CODE REVIEW

**Review by jrhees-cae — APPROVED** [review]

File: src/app/clusters/time-synchronization-server/time-synchronization-server.cpp [hunk 1]
```diff
@@ -925,19 +925,24 @@ bool emberAfTimeSynchronizationClusterSetTimeZoneCallback(
...
     else
     {
         response.DSTOffsetRequired = true;
     }
+
+    if (response.DSTOffsetRequired)
+    {
+        TimeState dstState = TimeSynchronizationServer::Instance().UpdateDSTOffsetState();
+        TimeSynchronizationServer::Instance().ClearDSTOffset();
+        if (dstState == TimeState::kActive || dstState == TimeState::kChanged)
```
Comment (cecille) [inline src/app/clusters/time-synchronization-server/time-synchronization-server.cpp:940]: I don't totally understand the enum here - it seems like a mix of states and transitions (active is a state, changed is a transition, but it's not clear from what to what). In what cases would you get back changed vs. active?

Will this also clear the dst offsets if you set the time zone to the same thing it was before?

Comment (fessehaeve) [reply src/app/clusters/time-synchronization-server/time-synchronization-server.cpp:940]: Setting to the same time zone is allowed and considered as new setting - which means dst offset will be cleared.

```
    kInvalid = 0, // No valid offset available
    kActive  = 1, // An offset is currently being used
    kChanged = 2, // An offset expired or changed to a new value
    kStopped = 3, // Permanent item in use
```

kChanged is there (as a state) because we can only tell it changed when some interaction happens, rather than a timer based change. In the latter case we would not have kChanged in there since at the time of an interaction we would already have the correct state.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/clusters/time-synchronization-server/time-synchronization-server.cpp [hunk 2]
```diff
@@ -925,19 +925,24 @@ bool emberAfTimeSynchronizationClusterSetTimeZoneCallback(
...
-            if (dstState == TimeState::kActive || dstState == TimeState::kChanged)
-            {
-                emitDSTStatusEvent(commandPath.mEndpointId, false);
-            }
             response.DSTOffsetRequired = true;
         }
     }
     else
     {
         response.DSTOffsetRequired = true;
```
Comment (bzbarsky-apple) [inline src/app/clusters/time-synchronization-server/time-synchronization-server.cpp:933]: This codepath needs to be exercised in a test....

File: src/app/clusters/time-synchronization-server/time-synchronization-server.cpp (hunk 1 above)
Comment (cecille) [reply src/app/clusters/time-synchronization-server/time-synchronization-server.cpp:940]: What happens if it was inactive before and it's inactive now?

File: src/app/clusters/time-synchronization-server/time-synchronization-server.cpp (hunk 2 above)
Comment (cecille) [reply src/app/clusters/time-synchronization-server/time-synchronization-server.cpp:933]: If you mean the DSTOffsetRequired, it's tested in cert tests. If you mean the status event cert test timesync 2.11 should hit this path IIUC the states - it checks for dst status events as the dst goes on and off. To be fair, it's failing currently, but the test exists.

File: src/app/clusters/time-synchronization-server/time-synchronization-server.cpp (hunk 1 above)
Comment (fessehaeve) [reply src/app/clusters/time-synchronization-server/time-synchronization-server.cpp:940]: Nothing should happen in that case - kInvalid. My main goal was to trace changes and to decide whether there is a valid time zone or offset at a given time.

**Review by cecille — APPROVED** [review]

**Comment by cecille** [comment]
Going to update branch to get rid of the iotSDK requirement (it's been turned off).

File: src/app/clusters/time-synchronization-server/time-synchronization-server.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/app/clusters/time-synchronization-server/time-synchronization-server.cpp:933]: @cecille @fessehaeve I mean that we have a code change here, which is fixing an issue, but there are no test changes.  That means this code is not being exercised in (automated) tests.

It's possible there are manual cert tests for this, but ideally we would have automated tests here...

Comment (cecille) [reply src/app/clusters/time-synchronization-server/time-synchronization-server.cpp:933]: The gap is not the test, it's the example apps. Static zap means we're not covering all cases in CI. Moving to dynamic app testing would be lovely but is a SDK wide problem
