### PR TITLE
fix BLE commissioning on commissionable Matter TVs

### LINKED ISSUE #15012: Chip-tool can't provision chip-tv using ble
#### Problem
 * expected behavior
 -> chip-tool can provision chip-tv-app using ble

 * actual behavior
 ->  chip-tool can't provision chip-tv-app using ble

 * steps to reproduce
 1. lunch example tv-app

 2. using provisioning command 
 sudo ./chip-tool pairing ble-wifi 1 chip-wifi qwerasdf 65956980 2000

 * system configuration
-> using recently source, commit-id is 87d1d3e5bd09423f6012add27ccf6bd76cfdb063

 * screenshots, images, logs, etc.
[chip-tv-app-ble-provisioning-error.txt](https://github.com/project-chip/connectedhomeip/files/8038024/chip-tv-app-ble-provisioning-error.txt)
[chip-tool.txt](https://github.com/project-chip/connectedhomeip/files/8038027/chip-tool.txt)

 #### Proposed Solution
Because chip-tv-app supports commissioners and commissioners, transport managers are initialized three times during the initialization process. 
During initialization process, UMH Pool also changes state then chip-tv-app can't be provisioning by chip-tool using BLE.
In additionally if disable CHIP_DEVICE_CONFIG_ENABLE_COMMISSIONER_DISCOVERY(DISABLE Commissioner in tv-app), It is working well using ble.

### PR DESCRIPTION
**Pull request by chrisdecenzo**
#### Problem
What is being fixed?  Examples:
* Fixes #15012: CHIP-TOOL can't provision CHIP-TV using BLE

#### Change overview
By default, when there is more than one BleBase transport, the second to initialize overrides the global BleLayer transport with itself. This fix adds Ble transport initialization parameters so that this override behavior can be managed, and the default behavior is to only set the global BleLayer transport if it is not already set.

#### Testing
* Tested by commissioning the tv-app using BLE

### CODE REVIEW

File: src/transport/raw/BLE.h [hunk 1]
```diff
@@ -91,6 +122,20 @@ class DLL_EXPORT BLEBase : public Base, public Ble::BleLayerDelegate
...
+     *
+     * This is relevant when there is more than one TransportMgr,
+     * for example, when a device is both a commissioner (has a CHIPDeviceController)
+     * and a commissionee (has a Server) since each TransportMgr will set
+     * the global BleLayer transport to point to itself.
+     *
+     * In this scenario, the device will need the ability to toggle between a
+     * BleLayer transport for commissioner functionality and one for commissionee functionality.
+     */
+    void SetBleLayerTransportToSelf() { mBleLayer->mBleTransport = this; }
```
Comment (andy31415) [inline src/transport/raw/BLE.h:136]: This method is never called, nor is the method below.

Comment (chrisdecenzo) [reply src/transport/raw/BLE.h:136]: Added calls from CHIPDeviceController when commissioning over BLE

File: src/controller/CHIPDeviceController.h [hunk 2]
```diff
@@ -587,6 +587,15 @@ class DLL_EXPORT DeviceCommissioner : public DeviceController,
                                CommissioningDelegate::CommissioningReport report = CommissioningDelegate::CommissioningReport());
 
 #if CONFIG_NETWORK_LAYER_BLE
+#if CHIP_DEVICE_CONFIG_ENABLE_BOTH_COMMISSIONER_AND_COMMISSIONEE
+    /**
+     * @brief
+     *   Prior to commissioning, the Controller should make sure the BleLayer transport
+     *   is set to the Commissioner transport and not the Server transport.
+     */
+    void PrepareBleTransport();
```
Comment (andy31415) [inline src/controller/CHIPDeviceController.h:596]: Based on the description, the name "Prepare" is too generic. This ensures that controller ble transport is set to the commissioner transport. Lets use a name that makes this clear, like `ConnectBleTransportToSelf` or `RedirectBleLayerToCommissioner` or something similar.

**Review by andy31415 — APPROVED** [review]

**Review by lazarkov — APPROVED** [review]

**Review by Byungjoo-Lee — APPROVED** [review]
Verified BLE commissioning

File: src/controller/CHIPDeviceController.h (hunk 2 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.h]: fixed name

**Review by andy31415 — CHANGES_REQUESTED** [review]
Needs a cleaner way of getting to the BLE layer. Using GetImplAtIndex does not seem right.

**Review by andy31415 — APPROVED** [review]
Switching to approve as an unblocking for TV.

From a separate chat with @chrisdecenzo , the situation we have is:
  - ControllerFactory creates a transportmgr shared by all controllers
  - Server creates a transport for server stuff
  
These two conflict and generally the BLE on the server is only needed for commissioning and before commissioning, the controller side would not be functional. There should be a way for either sharing the same trasnport (so BLE does not conflict) or sequencing initializations (do server first, once commissioned, start the controller side).

This needs revision and Chris agreed to take a look at it while working on "make TVs run without comissioness" with a rough estimate of before 8 weeks (i.e. should happen reasonably soon).

**Comment by chrisdecenzo** [comment]
Created issue https://github.com/project-chip/connectedhomeip/issues/15732 to remove this workaround for manually changing the BleLayer transport from CHIPDeviceControlleer (see issue for proposed solution).

**Review by woody-apple — APPROVED** [review]

File: src/controller/CHIPDeviceController.cpp [hunk 3]
```diff
@@ -1320,11 +1320,13 @@ CHIP_ERROR DeviceCommissioner::OnOperationalCredentialsProvisioningCompletion(Co
...
-    // static_assert(__i < tuple_size<tuple<>>::value,
-    // Transport::BLEBase transport = mSystemState->TransportMgr()->GetTransport().template GetImplAtIndex<2>();
-    Transport::BLEBase transport = mSystemState->TransportMgr()->GetTransport().GetImplAtIndex<2>();
+#if INET_CONFIG_ENABLE_IPV4
+    static const size_t kBleTupleIndex = 2;
+#else  // INET_CONFIG_ENABLE_IPV4
+    static const size_t kBleTupleIndex = 1;
+#endif // INET_CONFIG_ENABLE_IPV4
+
+    Transport::BLEBase & transport = mSystemState->TransportMgr()->GetTransport().GetImplAtIndex<kBleTupleIndex>();
```
[the remark this answers is not in the document]
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp]: updated the approach
