### PR TITLE
[Darwin] MTRDeviceTestDelegate properties should be atomic

### LINKED ISSUE #39292: [Darwin] ThreadSanitizer failure in test048_MTRDeviceResubscribeOnSubscriptionPool
### Reproduction steps

https://github.com/project-chip/connectedhomeip/actions/runs/15336175175/job/43155220947

```
2025-05-30T01:21:48.2591020Z WARNING: ThreadSanitizer: data race (pid=37382)
2025-05-30T01:21:48.2591520Z   Read of size 8 at 0x7b0c00108b90 by thread T20:
2025-05-30T01:21:48.2592600Z     #0 __64-[MTRDeviceTests test048_MTRDeviceResubscribeOnSubscriptionPool]_block_invoke_4 <null> (MatterTests:x86_64+0x5eccc9)
2025-05-30T01:21:48.2593730Z     #1 -[MTRDeviceTestDelegate unitTestSubscriptionPoolWorkComplete:] <null> (MatterTests:x86_64+0x405ff1)
2025-05-30T01:21:48.2595090Z     #2 __69-[MTRDevice_Concrete _clearSubscriptionPoolWorkWithProvidedDelegate:]_block_invoke <null> (Matter:x86_64+0x1a3f098)
2025-05-30T01:21:48.2595920Z     #3 __47-[MTRDeviceDelegateInfo callDelegateWithBlock:]_block_invoke <null> (Matter:x86_64+0x1aaf229)
2025-05-30T01:21:48.2596650Z     #4 __tsan::invoke_and_release_block(void*) <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x7f72b)
2025-05-30T01:21:48.2597120Z     #5 _dispatch_client_callout <null> (libdispatch.dylib:x86_64+0x3032)
2025-05-30T01:21:48.2597950Z 
2025-05-30T01:21:48.2598400Z   Previous write of size 8 at 0x7b0c00108b90 by main thread:
2025-05-30T01:21:48.2598800Z     #0 __copy_helper_block_e8_32s <null> (MatterTests:x86_64+0x784e)
2025-05-30T01:21:48.2599860Z     #1 _call_copy_helpers_excp <null> (libsystem_blocks.dylib:x86_64+0x16fb)
2025-05-30T01:21:48.2600820Z     #2 -[MTRDeviceTests test048_MTRDeviceResubscribeOnSubscriptionPool] <null> (MatterTests:x86_64+0x5eca38)
2025-05-30T01:21:48.2601150Z     #3 __invoking___ <null> (CoreFoundation:x86_64h+0x60bab)
2025-05-30T01:21:48.2601170Z 
2025-05-30T01:21:48.2601670Z   Location is heap block of size 40 at 0x7b0c00108b70 allocated by main thread:
2025-05-30T01:21:48.2602320Z     #0 malloc <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x560ec)
2025-05-30T01:21:48.2603310Z     #1 _Block_copy <null> (libsystem_blocks.dylib:x86_64+0x123e)
2025-05-30T01:21:48.2607980Z     #2 -[MTRDeviceTests test048_MTRDeviceResubscribeOnSubscriptionPool] <null> (MatterTests:x86_64+0x5eca38)
2025-05-30T01:21:48.2608430Z     #3 __invoking___ <null> (CoreFoundation:x86_64h+0x60bab)
2025-05-30T01:21:48.2608450Z 
2025-05-30T01:21:48.2608700Z   Thread T20 (tid=119979, running) is a GCD worker thread
```

I _think_ this might be the read and write of `delegate.onSubscriptionPoolWorkComplete`?  I wonder whether we should make all these properties on the delegate atomic...

### Platform

darwin

### Platform Version(s)

_No response_

### Type

CI tested

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jtung-apple**
#### Summary

There seems to be some race as Boris noted in #39292 , and this is an attempt to fix it so that CI tests don't fail when there's no actual problem.

#### Related issues

Fixes #39292

#### Testing

I will run this a a few times and see that CI doesn't fail again in the same `test048_MTRDeviceResubscribeOnSubscriptionPool` test.

### CODE REVIEW

File: src/darwin/Framework/CHIPTests/TestHelpers/MTRDeviceTestDelegate.h [hunk 1]
```diff
@@ -23,31 +23,31 @@ typedef void (^MTRDeviceTestDelegateDataHandler)(NSArray<NSDictionary<NSString *
...
+@property (atomic, nullable) dispatch_block_t onSubscriptionReset;
+@property (atomic, nullable) NSNumber * subscriptionMaxIntervalOverride;
+@property (atomic, nullable) MTRDeviceTestDelegateHandler onUTCTimeSet;
+@property (atomic) BOOL forceTimeUpdateShortDelayToZero;
+@property (atomic) BOOL forceTimeSynchronizationLossDetectionCadenceToZero;
 @end
 
 @interface MTRDeviceTestDelegateWithSubscriptionSetupOverride : MTRDeviceTestDelegate
-@property (nonatomic) BOOL skipSetupSubscription;
+@property (atomic) BOOL skipSetupSubscription;
```
Comment (jtung-apple) [inline src/darwin/Framework/CHIPTests/TestHelpers/MTRDeviceTestDelegate.h:50]: Adding a conversation to prevent auto merge. I will resolve this conversation when there's been a few CI runs without hitting the `test048_MTRDeviceResubscribeOnSubscriptionPool` race.

**Review by woody-apple — APPROVED** [review]
