### PR TITLE
Fix Descriptor cluster when linking statically.

### LINKED ISSUE #11344: Descriptor cluster broken on esp32 (and probably other platforms that use static linking)
#### Problem
Descriptor cluster is broken on esp32, because we never call the `MatterDescriptorPluginServerInitCallback` function it defines there.  As a result, it never registers its attribute access interface, and then nothing works right.

This happens because a weak symbol for that function is provided via PluginApplicationCallbacks.h.  But this is the _only_ function that `descriptor.cpp` provides, so the static linker never even pulls in that file: it's not needed to satisfy the link-time dependencies.

Other clusters, which expose things like callback functions for cluster commands, work ok, but descriptor has no cluster commands.

 #### Proposed Solution
Not sure. Can we just drop the weak symbols from `PluginApplicationCallbacks.h`?

@vivien-apple @dhrishi

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Specific changes:

1) Stop using weak symbols for cluster init callbacks.  The way things
   are, if a cluster has no commands its file might not get linked at
   all (because the weak symbols satisfy the linker), and hence its
   init callback would never be called.  This was hitting the
   Descriptor cluster.

2) Add a bunch of no-op cluster init callbacks so we can link successfully.
    Add some files to the all-clusters-app link that were missing.

Fixes https://github.com/project-chip/connectedhomeip/issues/11344

#### Problem
See #11344.

#### Change overview
See above.

#### Testing
* Verified that manual attempts to read Descriptor from all-clusters-app running on m5stack work.

Note: This PR used to have changes to `src/app/chip_data_model.gni` to use `static_library` instead of `source_set`, but that fails to link `ibCHIPAppServer.so` on Android...

### CODE REVIEW

**Review by msandstedt — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

File: src/app/util/util.cpp [hunk 1]
```diff
@@ -289,6 +289,27 @@ void emberAfTick(void)
 #endif
 }
 
+// Cluster init functions that don't have a cluster implementation to define
+// them in.
+void MatterBooleanStatePluginServerInitCallback() {}
```
Comment (andy31415) [inline src/app/util/util.cpp:294]: complaining about 'util' naming of this file here ... these InitCallbacks seem to have little relationship with  other things inside this file but `util` name is  a grab bag for 'anything fits'.

Could we maybe create a separate `callback-stubs.cpp` file?

Comment (bzbarsky-apple) [reply src/app/util/util.cpp:294]: We could, but then we would need to add it to the build system in a bunch of places, which I was sort of trying to avoid.

Also, we already have a generated `callback-stub.cpp` file, which would make adding another "stubs" file a little odd too .... but that's generated per-app, so adding these there is not great either.

Comment (bzbarsky-apple) [reply src/app/util/util.cpp:294]: Oh, and I put them in this file because the callsite for them is in this file, in the function immediately above where I added them.

Comment (andy31415) [reply src/app/util/util.cpp:294]: ok. things to improve later.

**Review by andy31415 — APPROVED** [review]
