### PR TITLE
[Darwin] Crash when resolving node's IPs if it's discovered on more t…

### LINKED ISSUE #17288: Crash when resolving node's IPs if it's discovered on more than one interface
#### Problem
Steps to reproduce:
1. Check out SHA 2e33dec44d21de6eccdc7d9f96f61552cb1c0f77 or anything else that has the fix for #17246 in it.
2. Compile `chip-tool` and `chip-all-clusters-app`:
    ```
   scripts/examples/gn_build_example.sh examples/all-clusters-app/linux out/debug/standalone chip_config_network_layer_ble=false
    scripts/examples/gn_build_example.sh examples/chip-tool out/debug/standalone/
    ```
3. `rm /tm/chip*`
4. Run `./out/debug/standalone/chip-all-clusters-app`
5. Run `./out/debug/standalone/chip-tool pairing onnetwork 17 20202021`

Expected results: Commissioning is fine.
Actual results: chip-tool crashes.

The problem is that we are ending up resolving the operational node on multiple interfaces (in my case loopback and my wifi interfaces) and after the change in #17246 we end up calling back into `HandleNodeIdResolve` multiple times.  But the first time we call it we do `proxy->Release()` and after that `proxy` can be a dead object, and the second time we call into that code we try to make a virtual call on it, jump into lala-land (well, in my case can't even read the vtable) and crash.

 #### Proposed Solution
Sort out what the actual invariants are supposed to be here and make sure they are not violated.  

I assume CI does not hit this because we advertise loopback-only in CI.

@vivien-apple @Damian-Nordic @andreilitvin

### PR DESCRIPTION
**Pull request by vivien-apple**
…han one interface

#### Problem

Since https://github.com/project-chip/connectedhomeip/pull/17246 Darwin is crashing if there are multiple interfaces broadcasting over mdns when resolving the ip.

fix #17288

#### Change overview
 * share the connection so `kDNSServiceFlagsMoreComing` is shared across the possible various calls of `DNSServiceGetAddrInfo`.

#### Testing
`chip-tool` does not crash anymore.

### CODE REVIEW

File: src/platform/Darwin/DnssdImpl.cpp [hunk 1]
```diff
@@ -435,15 +452,15 @@ static void OnGetAddrInfo(DNSServiceRef sdRef, DNSServiceFlags flags, uint32_t i
 
     // TODO: Does it really make sense to pass in the status from our last "get the IP address" operation?
     sdCtx->callback(sdCtx->context, &service, Span<Inet::IPAddress>(sdCtx->addresses.data(), sdCtx->addresses.size()), status);
-    MdnsContexts::GetInstance().Remove(sdCtx);
+    MdnsContexts::GetInstance().Removes(ContextType::GetAddrInfo);
+    MdnsContexts::GetInstance().Removes(ContextType::GetAddrInfoConnection);
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.cpp:456]: So if we start a lookup, then start another lookup (which shares the connection, right?), how does this removal of the context work?  When does it happen, in the lifetimes of the two lookups?

@vivien-apple

**Review by lazarkov — APPROVED** [review]

File: src/platform/Darwin/DnssdImpl.cpp (hunk 1 above)
Comment (vivien-apple) [reply src/platform/Darwin/DnssdImpl.cpp]: Ok. I did change the code - it ends up beeing a bigger change that what I was expecting.

Now the code is creating a "shared" connection on a per-resolve basis. I have also updated the code that close the context to make it clearer what is the lifetime of contexts in general. This is the "GenericContext::Finalise" method.

File: src/platform/Darwin/DnssdContexts.cpp [hunk 2]
```diff
@@ -0,0 +1,426 @@
...
+CHIP_ERROR ResolveContext::OnNewLocalOnlyAddress()
+{
+    sockaddr_in6 sockaddr;
+    memset(&sockaddr, 0, sizeof(sockaddr));
+    sockaddr.sin6_len    = sizeof(sockaddr);
+    sockaddr.sin6_family = AF_INET6;
+    sockaddr.sin6_addr   = in6addr_loopback;
+    sockaddr.sin6_port   = htons((unsigned short) services[kDNSServiceInterfaceIndexLocalOnly].mPort);
+
+    return OnNewAddress(kDNSServiceInterfaceIndexLocalOnly, reinterpret_cast<struct sockaddr *>(&sockaddr));
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdContexts.cpp:369]: This used to use "any" for the interface with a comment about how we leave the routing to the network stack...  Is the change to local-only here purposeful?

File: src/platform/Darwin/DnssdContexts.cpp [hunk 3]
```diff
@@ -0,0 +1,426 @@
...
+                                    uint16_t txtLen, const unsigned char * txtRecord)
+{
+    ChipLogDetail(DeviceLayer, "Mdns : %s hostname:%s fullname:%s interface: %" PRIu32, __func__, hostnameWithDomain, fullname,
+                  interfaceId);
+
+    DnssdService service = {};
+    service.mPort        = ntohs(port);
+    service.mInterface   = Inet::InterfaceId(interfaceId);
+
+    auto hostname = GetHostNameWithoutDomain(hostnameWithDomain);
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdContexts.cpp:395]: Please document why we are doing this?  The old code didn't seem to strip off the domain, afaict...

File: src/platform/Darwin/DnssdContexts.cpp [hunk 4]
```diff
@@ -0,0 +1,426 @@
...
+    for (auto & service : services)
+    {
+        size_t count = service.second.mTextEntrySize;
+        for (size_t i = 0; i < count; i++)
+        {
+            const auto & textEntry = service.second.mTextEntries[i];
+            free(const_cast<char *>(textEntry.mKey));
+            free(const_cast<uint8_t *>(textEntry.mData));
+        }
+        Platform::MemoryFree(const_cast<TextEntry *>(service.second.mTextEntries));
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdContexts.cpp:421]: The allocator mixing here is a bit weird, but it matches the allocation sites, so ok....

File: src/platform/Darwin/DnssdImpl.cpp [hunk 5]
```diff
@@ -53,7 +56,20 @@ std::string GetFullType(const char * type, DnssdServiceProtocol protocol)
     std::ostringstream typeBuilder;
     typeBuilder << type;
     typeBuilder << (protocol == DnssdServiceProtocol::kDnssdProtocolUdp ? kProtocolUdp : kProtocolTcp);
-    return typeBuilder.str();
+
+    auto fullType                = typeBuilder.str();
+    std::string subtypeDelimiter = "._sub.";
+    size_t position              = fullType.find(subtypeDelimiter);
+    if (position != std::string::npos)
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.cpp:63]: So did `OnBrowseRemove` use to do the wrong thing in its type compare?  And did `Resolve` just use to work because there were never subtypes involved there?  It seems like this is effectively changing both of those callsites....

File: src/platform/Darwin/DnssdImpl.cpp [hunk 6]
```diff
@@ -69,259 +85,125 @@ std::string GetFullTypeWithSubTypes(const char * type, DnssdServiceProtocol prot
...
                        const char * domain, void * context)
 {
-    RegisterContext * sdCtx = reinterpret_cast<RegisterContext *>(context);
-    VerifyOrReturn(CheckForSuccess(sdCtx, __func__, err));
-
     ChipLogDetail(DeviceLayer, "Mdns: %s name: %s, type: %s, domain: %s, flags: %d", __func__, name, type, domain, flags);
 
-    sdCtx->callback(sdCtx->context, type, CHIP_NO_ERROR);
+    auto sdCtx = reinterpret_cast<RegisterContext *>(context);
+    sdCtx->Finalize(err);
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.cpp:170]: So just trying to trace the lifetimes:
1. If `sdCtx` is not in `MdnsContexts::GetInstance` this will delete it.
2. If it _is_ in `MdnsContexts` and this is a failure, it will call the callback and remove it, which calls `MdnsContexts::Delete` and hence deletes the object.
3. If `sdCtx` is in `MdnsContexts` and this is a success, we will call the callback and do nothing else; no removing.  Is that expected?

File: src/platform/Darwin/DnssdImpl.cpp [hunk 7]
```diff
@@ -69,259 +85,125 @@ std::string GetFullTypeWithSubTypes(const char * type, DnssdServiceProtocol prot
...
+    VerifyOrReturnError(nullptr != sdCtx, CHIP_ERROR_NO_MEMORY);
 
-    err = DNSServiceSetDispatchQueue(sdRef, chip::DeviceLayer::PlatformMgrImpl().GetWorkQueue());
-    VerifyOrReturnError(CheckForSuccess(sdCtx, __func__, err, true), CHIP_ERROR_INTERNAL);
+    DNSServiceRef sdRef;
+    auto err = DNSServiceRegister(&sdRef, kRegisterFlags, interfaceId, name, type, kLocalDot, nullptr, ntohs(port), record.size(),
+                                  record.data(), OnRegister, sdCtx);
+    VerifyOrReturnError(kDNSServiceErr_NoError == err, sdCtx->Finalize(err));
 
     return MdnsContexts::GetInstance().Add(sdCtx, sdRef);
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.cpp:195]: So if `Add` fails we will _not_ call the callback, looks like?  But on failures above from DNSServiceRegister we will both call the callback _and_ return an error?  Is the caller expecting that behavior?  I would have expected one of error return or call to callback with error, not both....  I'm worried about callers ending up with double-deletes and the like if we do both.

File: src/platform/Darwin/DnssdImpl.cpp [hunk 8]
```diff
@@ -340,221 +222,129 @@ void OnBrowseAdd(BrowseContext * context, const char * name, const char * type,
...
-    err   = DNSServiceBrowse(&sdRef, 0 /* flags */, interfaceId, regtype.c_str(), kLocalDot, OnBrowse, sdCtx);
-    VerifyOrReturnError(CheckForSuccess(sdCtx, __func__, err), CHIP_ERROR_INTERNAL);
-
-    err = DNSServiceSetDispatchQueue(sdRef, chip::DeviceLayer::PlatformMgrImpl().GetWorkQueue());
-    VerifyOrReturnError(CheckForSuccess(sdCtx, __func__, err, true), CHIP_ERROR_INTERNAL);
+    DNSServiceRef sdRef;
+    auto err = DNSServiceBrowse(&sdRef, kBrowseFlags, interfaceId, type, kLocalDot, OnBrowse, sdCtx);
+    VerifyOrReturnError(kDNSServiceErr_NoError == err, sdCtx->Finalize(err));
 
     return MdnsContexts::GetInstance().Add(sdCtx, sdRef);
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.cpp:265]: Again, the error handling here seems pretty weird....

File: src/platform/Darwin/DnssdImpl.cpp [hunk 9]
```diff
@@ -340,221 +222,129 @@ void OnBrowseAdd(BrowseContext * context, const char * name, const char * type,
...
+    VerifyOrReturnError(kDNSServiceErr_NoError == err, sdCtx->Finalize(err));
 
-    err = DNSServiceSetDispatchQueue(sdRef, chip::DeviceLayer::PlatformMgrImpl().GetWorkQueue());
-    VerifyOrReturnError(CheckForSuccess(sdCtx, __func__, err, true), CHIP_ERROR_INTERNAL);
+    auto sdRefCopy = sdCtx->serviceRef; // Mandatory copy because of kDNSServiceFlagsShareConnection
+    err            = DNSServiceResolve(&sdRefCopy, kResolveFlags, interfaceId, name, type, kLocalDot, OnResolve, sdCtx);
+    VerifyOrReturnError(kDNSServiceErr_NoError == err, sdCtx->Finalize(err));
 
-    return MdnsContexts::GetInstance().Add(sdCtx, sdRef);
+    return MdnsContexts::GetInstance().Add(sdCtx, sdCtx->serviceRef);
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.cpp:343]: Again, not sure about the error-handling here....

File: src/platform/Darwin/DnssdImpl.cpp (hunk 7 above)
Comment (vivien-apple) [reply src/platform/Darwin/DnssdImpl.cpp:195]: None of those cases will call the callback, because "sdCtx" is not "yet" into the list of contexts known by `MdnsContexts::GetInstance`.

Only once "MdnsContexts::GetInstance().Add" has been executed successfully, "Finalize" will start to call the callback.

The previous "CheckForSuccess" method uses to allow the caller to specify if the callback needs to be called but if you look at the current code in master - it is not used in a consistent way - this is why I change the code to makes it implicit / automatically managed".

File: src/platform/Darwin/DnssdImpl.cpp (hunk 8 above)
Comment (vivien-apple) [reply src/platform/Darwin/DnssdImpl.cpp:265]: See https://github.com/project-chip/connectedhomeip/pull/17333#discussion_r852773943

File: src/platform/Darwin/DnssdImpl.cpp (hunk 9 above)
Comment (vivien-apple) [reply src/platform/Darwin/DnssdImpl.cpp:343]: See https://github.com/project-chip/connectedhomeip/pull/17333#discussion_r852773943

File: src/platform/Darwin/DnssdImpl.cpp (hunk 6 above)
Comment (vivien-apple) [reply src/platform/Darwin/DnssdImpl.cpp:170]: 1. Correct
2. Correct
3. This is correct for the "Register" type but for "Resolve" and "Browse" the callback also remove it. This is because in the case of "Register" we want to keep the context alive until "ChipDnssdRemoveServices" is called.

File: src/platform/Darwin/DnssdImpl.cpp (hunk 5 above)
Comment (vivien-apple) [reply src/platform/Darwin/DnssdImpl.cpp]: I agree that the original intention is unclear here. Initially the issue is that the "type" passed in as a parameter to `ChipDnssdBrowse" is formatted in a way that does not fit the expected format under darwin. 
It should not affects results retrieved into `OnBrowseRemove`.
And for the `Resolve` it does not matter because we used to not use subtypes.

To make that clearer I have added an other method called "GetFullTypeWithSubTypes" (same name as the one used for "Register") and I have used it in the "Browse" case, while "Resolve" uses "GetFullType".

File: src/platform/Darwin/DnssdImpl.h [hunk 10]
```diff
@@ -33,29 +32,70 @@ enum class ContextType
...
+
+    CHIP_ERROR Add(GenericContext * context, DNSServiceRef sdRef);
+    CHIP_ERROR Remove(GenericContext * context);
+    CHIP_ERROR RemoveAllOfType(ContextType type);
+    CHIP_ERROR Has(GenericContext * context);
+
+    /**
+     * @brief
+     *   Returns a pointer to a context that has previously been registered
+     *   with a given type.
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.h:66]:
```suggestion
     *   Returns a pointer to a RegisterContext that has previously been registered
     *   with a given type.
```
And maybe we should actually have the outparam be `RegisterContext **`?

File: src/platform/Darwin/DnssdContexts.cpp [hunk 11]
```diff
@@ -0,0 +1,408 @@
...
+        {
+            continue;
+        }
+
+        // Use the first IP we got for the DnssdService.
+        service.second.mAddress.SetValue(ips.front());
+        ips.erase(ips.begin());
+        callback(context, &service.second, Span<Inet::IPAddress>(ips.data(), ips.size()), CHIP_NO_ERROR);
+        MdnsContexts::GetInstance().Remove(this);
+        return;
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdContexts.cpp:323]: I think this might be clearer as a `break` from the loop and a `MdnsContexts::GetInstance().Remove(this);` outside the loop, to make it very clear that we always `Remove()`.

File: src/platform/Darwin/DnssdImpl.cpp (hunk 7 above)
Comment (bzbarsky-apple) [reply src/platform/Darwin/DnssdImpl.cpp:201]: Ah, I had missed that subtlety around Finalize.  OK, thanks!

**Review by bzbarsky-apple — APPROVED** [review]

File: src/platform/Darwin/DnssdContexts.cpp (hunk 3 above)
Comment (vivien-apple) [reply src/platform/Darwin/DnssdContexts.cpp:377]: The old code was wrong basically. If you look at https://github.com/project-chip/connectedhomeip/blob/master/src/lib/dnssd/platform/Dnssd.h#L67 you can see that the size of the field is `kHostNameMaxLength + 1` where `kHostNameMaxLength` is https://github.com/project-chip/connectedhomeip/blob/c2b6479b7aa27517f36b97173efc3e318f0937a9/src/lib/dnssd/Constants.h#L32

So the field is sized to contains a 12 bytes Mac address or an extended address of 16 bytes. But with the current code some parts of the domain where stored. For example on my machine something like "010203040506.loc" was saved when the full name was ""010203040506.local.".

File: src/platform/Darwin/DnssdContexts.cpp (hunk 2 above)
Comment (vivien-apple) [reply src/platform/Darwin/DnssdContexts.cpp:352]: That was on purpose but maybe this is opening the risk to regress https://github.com/project-chip/connectedhomeip/pull/11992 
I have updated the code to use `0` just in case.

**Comment by vivien-apple** [comment]
I really don't understand why this PR fails CI with - I also can't reproduce locally :/ 
```[327/334] touch mac_x64_gcc/obj/scripts/idl/idl.tests.stamp
[3483](https://github.com/project-chip/connectedhomeip/runs/6094985957?check_suite_focus=true#step:11:3483)
Error: The action has timed out.```

File: src/platform/Darwin/DnssdImpl.cpp [hunk 12]
```diff
@@ -340,221 +228,130 @@ void OnBrowseAdd(BrowseContext * context, const char * name, const char * type,
...
-    }
-    else if (addressType == chip::Inet::IPAddressType::kIPv6)
-    {
-        protocol = kDNSServiceProtocol_IPv6;
-    }
-    else
-    {
-        protocol = kDNSServiceProtocol_IPv4 | kDNSServiceProtocol_IPv6;
+        auto interfaceId = service.first;
+        auto hostname    = GetHostNameWithDomain(service.second.mHostName);
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.cpp:301]: Unit tests for dnssd are timing out because `service.second.mHostName` is not long enough to hold the hostname we try to use, and when we copy the hostname into it we just silently truncate.

We should consider erroring out loudly at that point, logging the actual input into `DNSServiceGetAddrInfo` we use here, and figure out how to either fix the hostname we use or stop using the DnssdService to store it for now...

File: src/platform/Darwin/DnssdContexts.cpp [hunk 13]
```diff
@@ -0,0 +1,426 @@
...
+    }
+
+    // The hostname parameter contains the hostname followed by the domain. But the mHostName field is sized
+    // to contain either a 12 bytes mac address or an extended address of at most 16 bytes, not the domain name.
+    auto hostname = GetHostNameWithoutDomain(hostnameWithDomain);
+    Platform::CopyString(service.mHostName, hostname.c_str());
+    Platform::CopyString(service.mName, fullname);
+
+    // If for some reason the hostname can not fit into the hostname field (e.g it is not a mac address) then
+    // DNSServiceGetAddrInfo will never returns anything. So instead, copy the name as the FQDN and use it for
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdContexts.cpp:395]:
```suggestion
    // DNSServiceGetAddrInfo will never return anything. So instead, copy the name as the FQDN and use it for
```

File: src/platform/Darwin/DnssdImpl.h [hunk 14]
```diff
@@ -66,83 +108,35 @@ struct BrowseContext : public GenericContext
...
-
-    CHIP_ERROR Add(GenericContext * context, DNSServiceRef sdRef);
-    CHIP_ERROR Remove(GenericContext * context);
-    CHIP_ERROR Removes(ContextType type);
-    CHIP_ERROR Get(ContextType type, GenericContext ** context);
-    CHIP_ERROR GetRegisterType(const char * type, GenericContext ** context);
+    std::map<uint32_t, DnssdService> services;
+    std::map<uint32_t, std::vector<Inet::IPAddress>> addresses;
+    DNSServiceProtocol protocol;
+    char fullyQualifiedDomainName[256] = {};
```
Comment (bzbarsky-apple) [inline src/platform/Darwin/DnssdImpl.h:124]: Why not just make this an `std::string` instead of a fixed-size buffer?

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

File: src/platform/Darwin/DnssdImpl.cpp (hunk 12 above)
Comment (vivien-apple) [reply src/platform/Darwin/DnssdImpl.cpp]: I have introduce a `InterfaceInfo` class that holds the hostname, the service and the resolved ids.
