### PR TITLE
[Darwin] MTRDevice writes and commands should be serialized along with reads

### LINKED ISSUE #23066: [Darwin] MTRDevice writes and commands should be serialized along with reads
### Reproduction steps

```bash
With the MTRDevice set of APIs, with regard to reading/writing a value to an attribute, we can imagine a scenario:
1. Assume old value is X
2. Write A - fires async write A
3. Read - synchronous and immediately returns A, and fires async real read
4. Async read wins, returns old value X, expected value cache obliterated and we report to client old value X again
5. Async write eventually done
6. Subscription report gets received from device and value A is reported to client
```

### Platform

darwin

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

There does not currently exist unit tests for this.

### Anything else?

Given an attribute that the user is interacting with actively, although the eventual value would be correct, the users could potentially see values jumping around incorrectly during change.

The fix here would be to also serialize writes and commands along with reads.

### PR DESCRIPTION
**Pull request by jtung-apple**
Fixes #23066 

This change makes writes and commands in the MTRDevice set of APIs perform on the same serial queue as read, to avoid the scenario described in #23066 .

### CODE REVIEW

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 1]
```diff
@@ -422,20 +420,24 @@ - (void)writeAttributeWithEndpointID:(NSNumber *)endpointID
...
-                   timedWriteTimeout:timeout
-                               queue:self.queue
-                          completion:^(NSArray<NSDictionary<NSString *, id> *> * _Nullable values, NSError * _Nullable error) {
-                              if (values) {
-                                  [self _handleAttributeReport:values];
-                              }
-                          }];
+    MTRAsyncCallbackQueueWorkItem * workItem = [[MTRAsyncCallbackQueueWorkItem alloc] initWithQueue:_queue];
+    MTRAsyncCallbackReadyHandler readyHandler = ^(MTRDevice * device, NSUInteger retryCount) {
+        MTRBaseDevice * baseDevice = [self newBaseDevice];
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:425]: This is going to need to be merged on top of https://github.com/project-chip/connectedhomeip/pull/23155 ...

Probably simplest is to re-add `newBaseDevice` in this PR or something, and just put it in the same place where it used to be, so when we try to re-land the API change PRs the conflicts are minimal.  But the selector on the baseDevice call will also need updating, unless we re-land some of the API bits first.

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 2]
```diff
@@ -422,20 +420,24 @@ - (void)writeAttributeWithEndpointID:(NSNumber *)endpointID
...
+        [baseDevice
+            writeAttributeWithEndpointID:endpointID
+                               clusterID:clusterID
+                             attributeID:attributeID
+                                   value:value
+                       timedWriteTimeout:timeout
+                                   queue:self.queue
+                              completion:^(NSArray<NSDictionary<NSString *, id> *> * _Nullable values, NSError * _Nullable error) {
+                                  if (values) {
+                                      [self _handleAttributeReport:values];
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:435]: Pre-existing, but this seems strange now that I look at it.  The only reason `values` would be nonempty here is if there was a path-specific error on the write, which is being communicated in `values`.  But then treating that as an attribute _report_ is a bit odd...  Need to figure out how the error reporting here should actually work.

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 3]
```diff
@@ -422,20 +420,24 @@ - (void)writeAttributeWithEndpointID:(NSNumber *)endpointID
...
+                                  }
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:436]: Don't we need to `endWork` somewhere here?

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 4]
```diff
@@ -450,28 +452,34 @@ - (void)invokeCommandWithEndpointID:(NSNumber *)endpointID
                           clusterID:(NSNumber *)clusterID
                           commandID:(NSNumber *)commandID
                       commandFields:(id)commandFields
-                     expectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedValues
+                     expectedValues:(NSArray<NSDictionary<NSString *, id> *> * _Nullable)expectedValues
               expectedValueInterval:(NSNumber *)expectedValueInterval
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:456]: `expectedValueInterval` is also nullable, right?

What should happen if one of `expectedValues` and `expectedValueInterval` is nil and the other is not?  I'd assume they should either both be nil or both not be nil, and we should error out in the other cases...  But either way we should document the behavior in the header.

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 5]
```diff
@@ -450,28 +452,34 @@ - (void)invokeCommandWithEndpointID:(NSNumber *)endpointID
...
+        [baseDevice
+            invokeCommandWithEndpointID:endpointID
+                              clusterID:clusterID
+                              commandID:commandID
+                          commandFields:commandFields
+                     timedInvokeTimeout:timeout
+                                  queue:self.queue
+                             completion:^(NSArray<NSDictionary<NSString *, id> *> * _Nullable values, NSError * _Nullable error) {
+                                 dispatch_async(queue, ^{
+                                     completion(values, error);
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:473]: Again, I would expect a `endWork` somewhere here....

File: src/darwin/Framework/CHIP/templates/MTRClusters-src.zapt [hunk 6]
```diff
@@ -55,54 +56,59 @@ using chip::SessionHandle;
...
+            {{/chip_cluster_command_arguments}}
+
+            auto successFn = Callback<{{>callbackName}}CallbackType>::FromCancelable(success);
+            auto failureFn = Callback<DefaultFailureCallbackType>::FromCancelable(failure);
+            chip::Controller::{{asUpperCamelCase parent.name}}Cluster cppCluster(exchangeManager, session, self->_endpoint);
+            return cppCluster.InvokeCommand(request, successFn->mContext, successFn->mCall, failureFn->mCall, timedInvokeTimeoutMs);
+      });
+    };
+    workItem.readyHandler = readyHandler;
+    [self.device.asyncCallbackWorkQueue enqueueWorkItem:workItem];
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/templates/MTRClusters-src.zapt:111]: Again, should there be `endWork` bits somewhere here?

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 3 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:436]: Yes indeed. I found this issue during more testing (but if these are called last I didn't see the problem - I should have figured). Will make the right changes and re-test.

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 4 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:459]: Yes indeed. I was copying over the _Nullable from the header for expectedValues and missed this. I'll add it.

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 2 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:437]: Filed #23285 to investigate

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 1 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:427]: Done

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 7]
```diff
@@ -452,28 +455,35 @@ - (void)invokeCommandWithEndpointID:(NSNumber *)endpointID
                           clusterID:(NSNumber *)clusterID
                           commandID:(NSNumber *)commandID
                       commandFields:(id)commandFields
-                     expectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedValues
-              expectedValueInterval:(NSNumber *)expectedValueInterval
+                     expectedValues:(NSArray<NSDictionary<NSString *, id> *> * _Nullable)expectedValues
+              expectedValueInterval:(NSNumber * _Nullable)expectedValueInterval
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:459]: We still need to document the behavior if one of these is nil and the other is not.  Followup for that, please.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/darwin/Framework/CHIP/MTRDevice.mm [hunk 8]
```diff
@@ -452,28 +469,45 @@ - (void)invokeCommandWithEndpointID:(NSNumber *)endpointID
...
+                                     completion(values, error);
+                                 });
+                                 [workItem endWork];
+                             }];
+    };
+    workItem.readyHandler = readyHandler;
+    [_asyncCallbackWorkQueue enqueueWorkItem:workItem];
+
+    if (expectedValues) {
+        [self setExpectedValues:expectedValues expectedValueInterval:expectedValueInterval];
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.mm:509]: So if we get here with `expectedValues` not nil but `expectedValueInterval` nil, what happens?  `setExpectedValues` seems to expect a non-nil interval, at first glance....

File: src/darwin/Framework/CHIP/templates/MTRClusters-src.zapt [hunk 9]
```diff
@@ -52,56 +53,71 @@ using chip::SessionHandle;
...
-        {{#chip_cluster_command_arguments}}
-          {{#first}}
-            {{#unless (commandHasRequiredField parent)}}
-            if (params != nil) {
-            {{/unless}}
-          {{/first}}
-          {{>encode_value target=(concat "request." (asLowerCamelCase label)) source=(concat "params." (asStructPropertyName label)) cluster=parent.parent.name errorCode="return CHIP_ERROR_INVALID_ARGUMENT;" depth=0}}
-          {{#last}}
-            {{#unless (commandHasRequiredField parent)}}
+    NSNumber *timedInvokeTimeoutMsParam = params.timedInvokeTimeoutMs;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/templates/MTRClusters-src.zapt:56]: What will this return if `params` is nil?

File: src/darwin/Framework/CHIP/templates/MTRClusters-src.zapt [hunk 10]
```diff
@@ -52,56 +53,71 @@ using chip::SessionHandle;
...
+            auto successFn = Callback<{{>callbackName}}CallbackType>::FromCancelable(success);
+            auto failureFn = Callback<DefaultFailureCallbackType>::FromCancelable(failure);
+            chip::Controller::{{asUpperCamelCase parent.name}}Cluster cppCluster(exchangeManager, session, self->_endpoint);
+            return cppCluster.InvokeCommand(request, successFn->mContext, successFn->mCall, failureFn->mCall, timedInvokeTimeoutMs);
+      });
+    };
+    workItem.readyHandler = readyHandler;
+    [self.device.asyncCallbackWorkQueue enqueueWorkItem:workItem];
+
+    if ([expectedValueIntervalMs compare:@(0)] == NSOrderedAscending) {
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/templates/MTRClusters-src.zapt:113]: What happens here when `expectedValueIntervalMs` is nil?

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 8 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:509]: That would be an API usage error. I will add a change to nil expectedValues and log.

I'm also wondering if the API should respond more drastically like throw an exception? In this case I feel it may be fine because nothing operational would be broken - just that the attribute report will come a little later, in the usual case.

File: src/darwin/Framework/CHIP/templates/MTRClusters-src.zapt (hunk 9 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/templates/MTRClusters-src.zapt:56]: Objc is convenient in that there's default value for nil. In this case timedInvokeTimeoutMsParam will be set to nil, which is correct.

File: src/darwin/Framework/CHIP/templates/MTRClusters-src.zapt (hunk 10 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/templates/MTRClusters-src.zapt:113]: Mmm this part was not written as I did in MTRDevice.mm - thanks for catching this. I'll fix this to be the same.

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 8 above)
Comment (bzbarsky-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:509]: > That would be an API usage error.

OK.  We should document that constraint in the API docs (they don't have it right now) and document what the behavior is if it's violated...

> I'm also wondering if the API should respond more drastically like throw an exception?

I would be fine with that.  We just need to make sure we don't crash in our own code here.

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 7 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:473]: Okay I think the latest header doc might do it.

File: src/darwin/Framework/CHIP/templates/MTRClusters-src.zapt (hunk 10 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/templates/MTRClusters-src.zapt]: Logic was changed in a previous commit along with MTRDevice.mm side.

File: src/darwin/Framework/CHIP/MTRDevice.mm (hunk 8 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDevice.mm:507]: I'm keeping the logic to ignore the values if either argument is nil or <= 0, since the behavior will be "works eventually".

File: src/darwin/Framework/CHIP/MTRDevice.h [hunk 11]
```diff
@@ -117,13 +118,17 @@ typedef NS_ENUM(NSUInteger, MTRDeviceState) {
  * @param expectedValues  array of dictionaries containing the expected values in the same format as
  *                       attribute read completion handler. Requires MTRAttributePathKey values.
  *                       See MTRDeviceResponseHandler definition for dictionary details.
+ *                       The expectedValues and expectedValueInterval arguments need to be both
+ *                       nil or both specified within the expected range, or will be both ignored.
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.h:122]:
```suggestion
 *                       nil or both non-nil, or both will be both ignored.
```

File: src/darwin/Framework/CHIP/MTRDevice.h [hunk 12]
```diff
@@ -117,13 +118,17 @@ typedef NS_ENUM(NSUInteger, MTRDeviceState) {
...
+ *
  * TODO: document better the expectedValues is how this command is expected to change attributes when read, and that the next
  * readAttribute will get these values
  *
  * @param expectedValueInterval  maximum interval in milliseconds during which reads of the attribute will return the value being
- * written. This value will be clamped to timeout
+ * written. This value must be within [1, UINT32_MAX], and will be clamped to this range.
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDevice.h:128]: So what will _actually_ happen here is that values <= 0 cause the expectedValue bits to be ignored, while values > UINT32_MAX are clamped.  So neither this comment nor the one above about "or both specified within the expected range, or will be both ignored" is right.  How about:
```suggestion
 * written. If the value is less than 1, both this value and expectedValues will be ignored.
            If this value is greater than UINT32_MAX, it will be clamped to UINT32_MAX.
```

**Review by bzbarsky-apple — APPROVED** [review]
