### PR TITLE
Fix wildcard subscriptions on all endpoints being rejected with "invalid action"

### LINKED ISSUE #39013: [BUG] [TC-IDM-6.2] Getting INVALID_ACTION response while subscribing the event with all events from all clusters on all endpoints on a specific node
### Reproduction steps

1. Bring up the DUT with All-Clusters-app.
2. Pair the DUT using chip-tool through "Onnetwork" transport.
3. command to enter interactive mode:  `./chip-tool interactive start `                 
4. Run the command `any subscribe-event-by-id 0xFFFFFFFF 0xFFFFFFFF 100 1000 1 0xFFFF`
5. **Test plan test step 6:** TH sends Subscribe Request Message to DUT with EventRequests set to all events from all clusters on all endpoints on a specific node that is, [Node = Specific, Endpoint = Wildcard, Cluster = Wildcard, Event = Wildcard].

**Expected outcome:**

**Verify TH receives Report Data Message with SubscriptionId which uniquely identifies this subscription on the publisher and data for events in Subscribe Request Message.**

> [1657456221.167627][11635:11640] CHIP:DMG: ReportDataMessage =
> [1657456221.167698][11635:11640] CHIP:DMG: {
> [1657456221.167760][11635:11640] CHIP:DMG:      SubscriptionId = 0xbcc84d35,
> [1657456221.167857][11635:11640] CHIP:DMG:      EventReportIBs =
> [1657456221.167944][11635:11640] CHIP:DMG:      [
> [1657456221.168006][11635:11640] CHIP:DMG:              EventReportIB =
> [1657456221.168123][11635:11640] CHIP:DMG:              {
> [1657456221.168221][11635:11640] CHIP:DMG:                      EventDataIB =
> [1657456221.168333][11635:11640] CHIP:DMG:                      {
> [1657456221.168437][11635:11640] CHIP:DMG:                              EventPath =
> [1657456221.168549][11635:11640] CHIP:DMG:                              {
> [1657456221.168764][11635:11640] CHIP:DMG:                                      Endpoint = 0x0,
> [1657456221.168885][11635:11640] CHIP:DMG:                                      Cluster = 0x28,
> [1657456221.169002][11635:11640] CHIP:DMG:                                      Event = 0x0,
> [1657456221.169111][11635:11640] CHIP:DMG:                              },
> [1657456221.169225][11635:11640] CHIP:DMG:
> [1657456221.169335][11635:11640] CHIP:DMG:                              EventNumber = 0x0,
> [1657456221.169448][11635:11640] CHIP:DMG:                              PriorityLevel = 0x2,
> [1657456221.169560][11635:11640] CHIP:DMG:                              SystemTimestamp = 0x5b7a5f,
> [1657456221.169668][11635:11640] CHIP:DMG:                              EventData =
> [1657456221.169780][11635:11640] CHIP:DMG:                              {
> [1657456221.169894][11635:11640] CHIP:DMG:                                      0x0 = 1,
> [1657456221.170008][11635:11640] CHIP:DMG:                              },
> [1657456221.170115][11635:11640] CHIP:DMG:                      },
> [1657456221.170231][11635:11640] CHIP:DMG:
> [1657456221.170323][11635:11640] CHIP:DMG:              },
> [1657456221.170426][11635:11640] CHIP:DMG:
> [1657456221.170456][11635:11640] CHIP:DMG:              EventReportIB =
> [1657456221.170560][11635:11640] CHIP:DMG:              {
> [1657456221.170598][11635:11640] CHIP:DMG:                      EventDataIB =
> [1657456221.170634][11635:11640] CHIP:DMG:                      {
> [1657456221.170669][11635:11640] CHIP:DMG:                              EventPath =
> [1657456221.170707][11635:11640] CHIP:DMG:                              {
> [1657456221.170745][11635:11640] CHIP:DMG:                                      Endpoint = 0x0,
> [1657456221.170786][11635:11640] CHIP:DMG:                                      Cluster = 0x1f,
> [1657456221.170826][11635:11640] CHIP:DMG:                                      Event = 0x0,
> [1657456221.170860][11635:11640] CHIP:DMG:                              },
> [1657456221.170898][11635:11640] CHIP:DMG:
> [1657456221.170934][11635:11640] CHIP:DMG:                              EventNumber = 0x1,
> [1657456221.170973][11635:11640] CHIP:DMG:                              PriorityLevel = 0x1,
> [1657456221.171010][11635:11640] CHIP:DMG:                              DeltaSystemTimestamp = 0xe03,
> [1657456221.171049][11635:11640] CHIP:DMG:                              EventData =
> [1657456221.171083][11635:11640] CHIP:DMG:                              {
> [1657456221.171123][11635:11640] CHIP:DMG:                                      0x1 = NULL
> [1657456221.171160][11635:11640] CHIP:DMG:                                      0x2 = 0,
> [1657456221.171201][11635:11640] CHIP:DMG:                                      0x3 = 1,
> [1657456221.171238][11635:11640] CHIP:DMG:                                      0x4 =
> [1657456221.171277][11635:11640] CHIP:DMG:                                      {
> [1657456221.171318][11635:11640] CHIP:DMG:                                              0x1 = 5,
> [1657456221.171362][11635:11640] CHIP:DMG:                                              0x2 = 2,
> [1657456221.171422][11635:11640] CHIP:DMG:                                              0x3 = [
> [1657456221.171466][11635:11640] CHIP:DMG:                                                              112233,
> [1657456221.171517][11635:11640] CHIP:DMG:                                              ],
> [1657456221.171563][11635:11640] CHIP:DMG:                                              0x4 = NULL
> [1657456221.171608][11635:11640] CHIP:DMG:                                              0xfe = 1,
> [1657456221.171650][11635:11640] CHIP:DMG:                                      },
> [1657456221.171694][11635:11640] CHIP:DMG:                                      0xfe = 1,
> [1657456221.171733][11635:11640] CHIP:DMG:                              },
> [1657456221.171767][11635:11640] CHIP:DMG:                      },
> [1657456221.171814][11635:11640] CHIP:DMG:
> [1657456221.171847][11635:11640] CHIP:DMG:              },
> [1657456221.171895][11635:11640] CHIP:DMG:
> [1657456221.171923][11635:11640] CHIP:DMG:              EventReportIB =
> [1657456221.171960][11635:11640] CHIP:DMG:              {
> [1657456221.171990][11635:11640] CHIP:DMG:                      EventDataIB =
> [1657456221.172029][11635:11640] CHIP:DMG:                      {
> [1657456221.172066][11635:11640] CHIP:DMG:                              EventPath =
> [1657456221.172106][11635:11640] CHIP:DMG:                              {
> [1657456221.172144][11635:11640] CHIP:DMG:                                      Endpoint = 0x1,
> [1657456221.172188][11635:11640] CHIP:DMG:                                      Cluster = 0x3b,
> [1657456221.172230][11635:11640] CHIP:DMG:                                      Event = 0x3,
> [1657456221.172268][11635:11640] CHIP:DMG:                              },
> [1657456221.172306][11635:11640] CHIP:DMG:
> [1657456221.172341][11635:11640] CHIP:DMG:                              EventNumber = 0x2,
> [1657456221.172380][11635:11640] CHIP:DMG:                              PriorityLevel = 0x1,
> [1657456221.172420][11635:11640] CHIP:DMG:                              DeltaSystemTimestamp = 0xd2846,
> [1657456221.172454][11635:11640] CHIP:DMG:                              EventData =
> [1657456221.172491][11635:11640] CHIP:DMG:                              {
> [1657456221.172533][11635:11640] CHIP:DMG:                                      0x0 = 10,
> [1657456221.172576][11635:11640] CHIP:DMG:                              },
> [1657456221.172611][11635:11640] CHIP:DMG:                      },
> [1657456221.172650][11635:11640] CHIP:DMG:
> [1657456221.172681][11635:11640] CHIP:DMG:              },
> [1657456221.172724][11635:11640] CHIP:DMG:
> [1657456221.172752][11635:11640] CHIP:DMG:              EventReportIB =
> [1657456221.172792][11635:11640] CHIP:DMG:              {
> [1657456221.172822][11635:11640] CHIP:DMG:                      EventDataIB =
> [1657456221.172856][11635:11640] CHIP:DMG:                      {
> [1657456221.172893][11635:11640] CHIP:DMG:                              EventPath =
> [1657456221.172931][11635:11640] CHIP:DMG:                              {
> [1657456221.172972][11635:11640] CHIP:DMG:                                      Endpoint = 0x1,
> [1657456221.173012][11635:11640] CHIP:DMG:                                      Cluster = 0x3b,
> [1657456221.173055][11635:11640] CHIP:DMG:                                      Event = 0x3,
> [1657456221.173092][11635:11640] CHIP:DMG:                              },
> [1657456221.173131][11635:11640] CHIP:DMG:
> [1657456221.173166][11635:11640] CHIP:DMG:                              EventNumber = 0x3,
> [1657456221.173204][11635:11640] CHIP:DMG:                              PriorityLevel = 0x1,
> [1657456221.173242][11635:11640] CHIP:DMG:                              DeltaSystemTimestamp = 0x479ad,
> [1657456221.173281][11635:11640] CHIP:DMG:                              EventData =
> [1657456221.173320][11635:11640] CHIP:DMG:                              {
> [1657456221.173360][11635:11640] CHIP:DMG:                                      0x0 = 10,
> [1657456221.173403][11635:11640] CHIP:DMG:                              },
> [1657456221.173438][11635:11640] CHIP:DMG:                      },
> [1657456221.173477][11635:11640] CHIP:DMG:
> [1657456221.173508][11635:11640] CHIP:DMG:              },
> [1657456221.173551][11635:11640] CHIP:DMG:
> [1657456221.173579][11635:11640] CHIP:DMG:              EventReportIB =
> [1657456221.173616][11635:11640] CHIP:DMG:              {
> [1657456221.173646][11635:11640] CHIP:DMG:                      EventDataIB =
> [1657456221.173680][11635:11640] CHIP:DMG:                      {
> [1657456221.173715][11635:11640] CHIP:DMG:                              EventPath =
> [1657456221.173753][11635:11640] CHIP:DMG:                              {
> [1657456221.173791][11635:11640] CHIP:DMG:                                      Endpoint = 0x1,
> [1657456221.173835][11635:11640] CHIP:DMG:                                      Cluster = 0x3b,
> [1657456221.173873][11635:11640] CHIP:DMG:                                      Event = 0x3,
> [1657456221.173911][11635:11640] CHIP:DMG:                              },
> [1657456221.173950][11635:11640] CHIP:DMG:
> [1657456221.173985][11635:11640] CHIP:DMG:                              EventNumber = 0xc,
> [1657456221.174023][11635:11640] CHIP:DMG:                              PriorityLevel = 0x1,
> [1657456221.174064][11635:11640] CHIP:DMG:                              DeltaSystemTimestamp = 0x616ab1,
> [1657456221.174101][11635:11640] CHIP:DMG:                              EventData =
> [1657456221.174138][11635:11640] CHIP:DMG:                              {
> [1657456221.174177][11635:11640] CHIP:DMG:                                      0x0 = 10,
> [1657456221.174216][11635:11640] CHIP:DMG:                              },
> [1657456221.174254][11635:11640] CHIP:DMG:                      },
> [1657456221.174293][11635:11640] CHIP:DMG:
> [1657456221.174324][11635:11640] CHIP:DMG:              },
> [1657456221.174366][11635:11640] CHIP:DMG:
> [1657456221.174394][11635:11640] CHIP:DMG:              EventReportIB =
> [1657456221.174432][11635:11640] CHIP:DMG:              {
> [1657456221.174462][11635:11640] CHIP:DMG:                      EventDataIB =
> [1657456221.174496][11635:11640] CHIP:DMG:                      {
> [1657456221.174533][11635:11640] CHIP:DMG:                              EventPath =
> [1657456221.174573][11635:11640] CHIP:DMG:                              {
> [1657456221.174615][11635:11640] CHIP:DMG:                                      Endpoint = 0x1,
> [1657456221.174658][11635:11640] CHIP:DMG:                                      Cluster = 0x3b,
> [1657456221.174697][11635:11640] CHIP:DMG:                                      Event = 0x3,
> [1657456221.174735][11635:11640] CHIP:DMG:                              },
> [1657456221.174773][11635:11640] CHIP:DMG:
> [1657456221.174808][11635:11640] CHIP:DMG:                              EventNumber = 0xd,
> [1657456221.174846][11635:11640] CHIP:DMG:                              PriorityLevel = 0x1,
> [1657456221.174887][11635:11640] CHIP:DMG:                              DeltaSystemTimestamp = 0xe1d,
> [1657456221.174926][11635:11640] CHIP:DMG:                              EventData =
> [1657456221.174963][11635:11640] CHIP:DMG:                              {
> [1657456221.175002][11635:11640] CHIP:DMG:                                      0x0 = 10,
> [1657456221.175041][11635:11640] CHIP:DMG:                              },
> [1657456221.175077][11635:11640] CHIP:DMG:                      },
> [1657456221.175115][11635:11640] CHIP:DMG:
> [1657456221.175146][11635:11640] CHIP:DMG:              },
> [1657456221.175184][11635:11640] CHIP:DMG:
> [1657456221.175211][11635:11640] CHIP:DMG:      ],
> [1657456221.175279][11635:11640] CHIP:DMG:
> [1657456221.175307][11635:11640] CHIP:DMG:      InteractionModelRevision = 1
> [1657456221.175335][11635:11640] CHIP:DMG: }
> [1657456221.175544][11635:11640] CHIP:TOO: Endpoint: 0 Cluster: 0x0000_0028 Event 0x0000_0000
> [1657456221.175574][11635:11640] CHIP:TOO:       Event number: 0
> [1657456221.175600][11635:11640] CHIP:TOO:       Priority: Critical
> [1657456221.175626][11635:11640] CHIP:TOO:       Timestamp: 5995103
> [1657456221.175665][11635:11640] CHIP:TOO:   StartUp: {
> [1657456221.175697][11635:11640] CHIP:TOO:     SoftwareVersion: 1
> [1657456221.175723][11635:11640] CHIP:TOO:    }
> [1657456221.175846][11635:11640] CHIP:TOO: Endpoint: 0 Cluster: 0x0000_001F Event 0x0000_0000
> [1657456221.175873][11635:11640] CHIP:TOO:       Event number: 1
> [1657456221.175899][11635:11640] CHIP:TOO:       Priority: Info
> [1657456221.175924][11635:11640] CHIP:TOO:       Timestamp: 5998690
> [1657456221.175980][11635:11640] CHIP:TOO:   AccessControlEntryChanged: {
> [1657456221.176010][11635:11640] CHIP:TOO:     AdminNodeID: null
> [1657456221.176038][11635:11640] CHIP:TOO:     AdminPasscodeID: 0
> [1657456221.176066][11635:11640] CHIP:TOO:     ChangeType: 1
> [1657456221.176092][11635:11640] CHIP:TOO:     LatestValue: {
> [1657456221.176119][11635:11640] CHIP:TOO:       Privilege: 5
> [1657456221.176145][11635:11640] CHIP:TOO:       AuthMode: 2
> [1657456221.176177][11635:11640] CHIP:TOO:       Subjects: 1 entries
> [1657456221.176210][11635:11640] CHIP:TOO:         [1]: 112233
> [1657456221.176240][11635:11640] CHIP:TOO:       Targets: null
> [1657456221.176267][11635:11640] CHIP:TOO:       FabricIndex: 1
> [1657456221.176292][11635:11640] CHIP:TOO:      }
> [1657456221.176318][11635:11640] CHIP:TOO:     AdminFabricIndex: 1
> [1657456221.176344][11635:11640] CHIP:TOO:    }
> [1657456221.176448][11635:11640] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_003B Event 0x0000_0003
> [1657456221.176475][11635:11640] CHIP:TOO:       Event number: 2
> [1657456221.176501][11635:11640] CHIP:TOO:       Priority: Info
> [1657456221.176526][11635:11640] CHIP:TOO:       Timestamp: 6860968
> [1657456221.176587][11635:11640] CHIP:TOO:   ShortRelease: {
> [1657456221.176617][11635:11640] CHIP:TOO:     PreviousPosition: 10
> [1657456221.176643][11635:11640] CHIP:TOO:    }
> [1657456221.176740][11635:11640] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_003B Event 0x0000_0003
> [1657456221.176767][11635:11640] CHIP:TOO:       Event number: 3
> [1657456221.176792][11635:11640] CHIP:TOO:       Priority: Info
> [1657456221.176817][11635:11640] CHIP:TOO:       Timestamp: 7154261
> [1657456221.176848][11635:11640] CHIP:TOO:   ShortRelease: {
> [1657456221.176876][11635:11640] CHIP:TOO:     PreviousPosition: 10
> [1657456221.176902][11635:11640] CHIP:TOO:    }
> [1657456221.176998][11635:11640] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_003B Event 0x0000_0003
> [1657456221.177025][11635:11640] CHIP:TOO:       Event number: 12
> [1657456221.177051][11635:11640] CHIP:TOO:       Priority: Info
> [1657456221.177076][11635:11640] CHIP:TOO:       Timestamp: 13538566
> [1657456221.177107][11635:11640] CHIP:TOO:   ShortRelease: {
> [1657456221.177134][11635:11640] CHIP:TOO:     PreviousPosition: 10
> [1657456221.177160][11635:11640] CHIP:TOO:    }
> [1657456221.177257][11635:11640] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_003B Event 0x0000_0003
> [1657456221.177284][11635:11640] CHIP:TOO:       Event number: 13
> [1657456221.177310][11635:11640] CHIP:TOO:       Priority: Info
> [1657456221.177335][11635:11640] CHIP:TOO:       Timestamp: 13542179
> [1657456221.177366][11635:11640] CHIP:TOO:   ShortRelease: {
> [1657456221.177393][11635:11640] CHIP:TOO:     PreviousPosition: 10
> [1657456221.177418][11635:11640] CHIP:TOO:    }
> [1657456221.177534][11635:11640] CHIP:DMG: MoveToState ReadClient[0xffff94008c70]: Moving to [AwaitingSu]
> 

**Current DUT response:**

> [1747371581.149] [5296:5302] [DMG] StatusResponseMessage =
> [1747371581.149] [5296:5302] [DMG] {
> [1747371581.149] [5296:5302] [DMG] 	Status = 0x80 (INVALID_ACTION),
> [1747371581.149] [5296:5302] [DMG] 	InteractionModelRevision = 12
> [1747371581.149] [5296:5302] [DMG] }

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

a12250a4e4ffce5be5f809479fbe8d85e5acd230

### Platform

raspi

### Platform Version(s)

_No response_

### Anything else?

**Here is the failure log files:**

1. Chip-tool log file: [IDM-6.2(Failure).txt](https://github.com/user-attachments/files/20238489/IDM-6.2.Failure.txt)
2. DUT log file: [IDM-6.2(DUT_failure).txt](https://github.com/user-attachments/files/20238498/IDM-6.2.DUT_failure.txt)

### PR DESCRIPTION
**Pull request by andy31415**
Instead of using the concrete `aEndpoint` value, code was using the wildcard endpoint from the path to call into the datamodel provider and datamodel provider will return empty list on invalid endpoint IDs.

This fixes #39013

#### Testing

Manual test as in the bug:

```
# app side:
rm -rf /tmp/chip_*; ./out/linux-x64-all-clusters-clang/chip-all-clusters-app

# chip-tool:
./out/linux-x64-chip-tool-clang//chip-tool pairing onnetwork 1 20202021
./out/linux-x64-chip-tool-clang//chip-tool interactive start 

    any subscribe-event-by-id 0xFFFFFFFF 0xFFFFFFFF 100 1000 1 0xFFFF
```

Before the change I got invalid action, after the change the operation succeeds.

Added integration test in TC_BasicDeviceComposition (we really need to catch this in cert as wildcard subscribe is VERY common). Tested locally with:

```sh
# app
rm -rf /tmp/chip_*; ./out/linux-x64-all-clusters-clang/chip-all-clusters-app --discriminator 1234

# test
python3 src/python_testing/TC_DeviceBasicComposition.py --commissioning-method on-network --manual-code 10054912339 --PICS src/app/tests/suites/certification/ci-pics-values
```

Before I get fail with:

image

And after it passes

```
...
INFO:chip.native.DL:System Layer shutdown
INFO:root:Final result: PASS !
```

### CODE REVIEW

**Review by soares-sergio — APPROVED** [review]

File: src/app/InteractionModelEngine.cpp [hunk 1]
```diff
@@ -93,10 +93,10 @@ bool MayHaveAccessibleEventPathForEndpoint(DataModel::Provider * aProvider, Endp
                                                                aSubjectDescriptor);
     }
 
-    for (auto & cluster : aProvider->ServerClustersIgnoreError(aEventPath.mEndpointId))
+    for (auto & cluster : aProvider->ServerClustersIgnoreError(aEndpoint))
     {
-        if (MayHaveAccessibleEventPathForEndpointAndCluster(ConcreteClusterPath(aEventPath.mEndpointId, cluster.clusterId),
-                                                            aEventPath, aSubjectDescriptor))
+        if (MayHaveAccessibleEventPathForEndpointAndCluster(ConcreteClusterPath(aEndpoint, cluster.clusterId), aEventPath,
```
Comment (andy31415) [inline src/app/InteractionModelEngine.cpp:98]: Pending comment here: I plan to add a test for this (automated) so this does not regress and we catch devices at cert time.

Comment (andy31415) [reply src/app/InteractionModelEngine.cpp:98]: Integration test added.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by cecille — APPROVED** [review]

File: src/python_testing/TC_DeviceBasicComposition.py [hunk 2]
```diff
@@ -674,6 +674,25 @@ class RequiredMandatoryAttribute:
             self.fail_current_test(
                 "At least one cluster has failed the range and support checks for its listed attributes, commands or features")
 
+        # Wildcard reads of events: event list MUST NOT be empty since at least a boot event should be registered.
+        self.print_step(12, "Validate that event wildcard subscription works")
```
Comment (tcarmelveilleux) [inline src/python_testing/TC_DeviceBasicComposition.py:678]:
```suggestion
        self.print_step(12, "Validate that event wildcard subscription works does not fail to initialize.")
```

**Review by tcarmelveilleux — APPROVED** [review]

File: src/python_testing/TC_DeviceBasicComposition.py [hunk 3]
```diff
@@ -674,6 +674,25 @@ class RequiredMandatoryAttribute:
...
+        except Exception as e:
+            self.record_error(self.get_test_name(),
+                              problem=f"Failed to wildcard subscribe events(*): {e}", location=UnknownProblemLocation())
+
+        if subscription is None:
+            self.fail_current_test()
+            return
+
+        if len(subscription.GetEvents()) == 0:
+            self.fail_current_test('Wildcard event subscription returned no events')
```
[the remark this answers is not in the document]
Comment (andy31415) [reply src/python_testing/TC_DeviceBasicComposition.py:694]: Why a warning? It seems like we can test that events actually work and we claim "event list is never empty since we start off with a boot event".

File: src/python_testing/TC_DeviceBasicComposition.py (hunk 2 above)
Comment (andy31415) [reply src/python_testing/TC_DeviceBasicComposition.py:678]: The test is intended to test for a subset of events working, rather than just saying "assert not throws".

File: src/python_testing/TC_DeviceBasicComposition.py [hunk 4]
```diff
@@ -674,6 +674,25 @@ class RequiredMandatoryAttribute:
             self.fail_current_test(
                 "At least one cluster has failed the range and support checks for its listed attributes, commands or features")
 
+        # Wildcard reads of events: event list MUST NOT be empty since at least a boot event should be registered.
+        self.print_step(12, "Validate that event wildcard subscription works")
+        subscription = None
+        try:
+            subscription = await self.default_controller.ReadEvent(nodeid=self.dut_node_id,
+                                                                   events=[('*')],
+                                                                   fabricFiltered=True,
```
[the remark this answers is not in the document]
Comment (andy31415) [reply src/python_testing/TC_DeviceBasicComposition.py:683]: That is a good point about long term running. Will update in this PR
