### PR TITLE
[3/3] Spec-compliant CASE eviction policy algorithm

### LINKED ISSUE #17568: Add session eviction logic to CASE session management
As part of the tenets outlined in #17298, support needs to be added to the management of sessions in the `SecureSessionTable` to properly do the following

1. Instead of `CreateNewSecureSession` failing if there are no slots available, it should evict the oldest session in the table with the following sorting criteria:
     i. A primary sort of all sessions based on time at which the session was established.
     ii. A secondary sort of the resultant set based on fabrics that over their specified minimas for active CASE sessions.
     iii. A tertiary sort of the resultant set based on nodes that have more than 1 active session to them.

The candidate at the top of the sorted list should be selected.

2. Remove the `ExpireInactiveSessions` and associated logic. Sessions should not expire on a timer.
3. `FindSecureSessionForNode` should return the most recent session established to a given peer.

### PR DESCRIPTION
**Pull request by mrjerryjohns**
#### Problem

Fixes #17568 

This implements a spec-compliant CASE eviction policy algorithm that attempts to achieve the following sort key order:

* **Key1**:  Sessions on fabrics that have more sessions in the table are placed ahead of sessions on fabrics
       with lesser sessions.
* **Key2**:  Sessions that match the eviction hint's fabric are placed ahead of those that don't.
* **Key3:**  Peers with more sessions are placed ahead of those with less.
* **Key4:**  Sessions whose target peer's ScopedNodeId matches the eviction hint are placed ahead of those who don't. 
* **Key5:**  Sessions that are in defunct state are placed ahead of those in the active state, ahead of any other state.
* **Key6:**  Sessions that have a less recent activity time are placed ahead of those with a more recent activity time. 

Key1 and Key2 are what guarantee spec-defined minima / fabric regardless of session establishment activity on other fabrics.

More detailed rationale can be found in the comments for `SecureSessionTable::DefaultEvictionPolicy`

Other fixes:
* Shifts from a heap-allocated `SortableSession` list to a stack-allocated one based on discussions previously.

#### Testing

* Adds a new `TestSecureSessionTable` test that validates the various different eviction scenarios that require the different sorting criteria above.
* Adds Python end-to-end tests that validate that over-active session establishment on one fabric does not affect session establishment on another.

### CODE REVIEW

File: src/transport/SecureSessionTable.cpp [hunk 1]
```diff
@@ -183,6 +220,100 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+                        }
+                    }
+                }
+            }
+        }
+
+        return false;
+    });
+
+#if 0
```
Comment (mrjerryjohns) [inline src/transport/SecureSessionTable.cpp:313]: Which do folks prefer?

File: src/transport/SecureSessionTable.cpp [hunk 2]
```diff
@@ -66,12 +66,18 @@ Optional<SessionHandle> SecureSessionTable::CreateNewSecureSession(SecureSession
     auto sessionId = FindUnusedSessionId();
     VerifyOrReturnValue(sessionId.HasValue(), Optional<SessionHandle>::Missing());
 
+#if CONFIG_BUILD_FOR_HOST_UNIT_TEST
+    uint32_t maxSessionTableSize = mMaxSessionTableSize;
```
Comment (andy31415) [inline src/transport/SecureSessionTable.cpp:70]: constexpr and name `kMaxSessionTableSize`

Comment (andy31415) [reply src/transport/SecureSessionTable.cpp:70]: should this be global (e.g. inside `namespace {}`) ? It seems reused in several places

File: src/transport/SecureSessionTable.cpp [hunk 3]
```diff
@@ -99,32 +105,59 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
     // without affecting the sessions in the table itself.
     //
-    Platform::ScopedMemoryBufferWithSize<SortableSession> sortableSessions;
-    sortableSessions.Calloc(mEntries.Allocated());
-    if (!sortableSessions)
-    {
-        VerifyOrDieWithMsg(false, SecureChannel, "We couldn't allocate a session!");
-        return nullptr;
-    }
+    SortableSession sortableSessions[CHIP_CONFIG_SECURE_SESSION_POOL_SIZE];
```
Comment (andy31415) [inline src/transport/SecureSessionTable.cpp:124]: How big is this array? I imagine previous logic allocated on the heap to avoid too much stack usage.

File: src/transport/SecureSessionTable.cpp [hunk 4]
```diff
@@ -183,6 +220,100 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
 
 void SecureSessionTable::DefaultEvictionPolicy(EvictionPolicyContext & evictionContext)
 {
+    evictionContext.Sort([&evictionContext](const SortableSession & a, const SortableSession & b) {
+        //
+        // Sorting on Key1
```
Comment (andy31415) [inline src/transport/SecureSessionTable.cpp:225]: expand comment as after we merge the PR, "Key1" is not as well defined. 
The text of "Sessions on fabrics with more sessoions are more likely to get evicted" seems useful instead of Key1.

File: src/transport/SecureSessionTable.cpp [hunk 5]
```diff
@@ -183,6 +220,100 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+
+        if (a.mNumMatchingOnFabric == b.mNumMatchingOnFabric)
+        {
+            int ScoreA = a.mSession->GetPeer().GetFabricIndex() == evictionContext.GetSessionEvictionHint().GetFabricIndex();
+            int ScoreB = b.mSession->GetPeer().GetFabricIndex() == evictionContext.GetSessionEvictionHint().GetFabricIndex();
+
+            //
+            // Sorting on Key2
+            //
+            if (ScoreA > ScoreB)
```
Comment (andy31415) [inline src/transport/SecureSessionTable.cpp:240]: same here. Do:

```cpp
if (scoreA != scoreB) {
   return scoreA > scoreB;
}
```

File: src/transport/SecureSessionTable.cpp [hunk 6]
```diff
@@ -183,6 +220,100 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+        // Sorting on Key1
+        //
+        if (a.mNumMatchingOnFabric > b.mNumMatchingOnFabric)
+        {
+            return true;
+        }
+
+        if (a.mNumMatchingOnFabric == b.mNumMatchingOnFabric)
+        {
+            int ScoreA = a.mSession->GetPeer().GetFabricIndex() == evictionContext.GetSessionEvictionHint().GetFabricIndex();
```
Comment (andy31415) [inline src/transport/SecureSessionTable.cpp:234]: start variable names with lowercase. mauybe cnst as well.

Why is this an int when the comparison is an equality. Naming of 'score' seems odd.

```cpp
const bool isEvictionHintA = ....;
const bool isEvictionHintB = ....;

if (isEvictionHintA != isEvictionHintB) {
   return isEvictionHintA;
}

File: src/transport/SecureSessionTable.cpp [hunk 7]
```diff
@@ -183,6 +220,100 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+            //
+            if (ScoreA > ScoreB)
+            {
+                return true;
+            }
+
+            if (ScoreA == ScoreB)
+            {
+                //
+                // Sorting on Key3
```
Comment (andy31415) [inline src/transport/SecureSessionTable.cpp:248]: expand comment, simplify logic and indent using `if (.. != ..) {return ...}`

File: src/transport/SecureSessionTable.cpp [hunk 8]
```diff
@@ -183,6 +220,100 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+                //
+                if (a.mNumMatchingOnPeer > b.mNumMatchingOnPeer)
+                {
+                    return true;
+                }
+
+                if (a.mNumMatchingOnPeer == b.mNumMatchingOnPeer)
+                {
+                    int ScoreA1 = a.mSession->GetPeer() == evictionContext.GetSessionEvictionHint();
```
Comment (andy31415) [inline src/transport/SecureSessionTable.cpp:257]: these are not ints, make them bool, simplify logic, update comment

File: src/transport/SecureSessionTable.cpp [hunk 9]
```diff
@@ -183,6 +220,100 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+                    if (ScoreA1 > ScoreB1)
+                    {
+                        return true;
+                    }
+
+                    if (ScoreA1 == ScoreB1)
+                    {
+                        int aStateScore = 0, bStateScore = 0;
+
+                        auto assignStateScore = [](auto & score, const auto & session) {
```
Comment (andy31415) [inline src/transport/SecureSessionTable.cpp:272]: please extract as a static method. Maybe use an enum backed by int to make things readable like kDefunct, kActive, ...

File: src/transport/SecureSessionTable.cpp (hunk 1 above)
Comment (andy31415) [reply src/transport/SecureSessionTable.cpp:313]: Previous one, however needs indent/logic updates as I commented.
Multiple sorts feels slow/wasteful.

Also wondering if we just need "top" do we actually need a sort? Finding "min/max" is generally a faster operation than a sort (linear vs n lgn at best, plus more moving things overhead).

**Review by woody-apple — APPROVED** [review]

File: src/transport/SecureSessionTable.cpp (hunk 1 above)
Comment (andy31415) [reply src/transport/SecureSessionTable.cpp:313]: Saw the comment regarding "cannot realy evict, must move to the next".
Do we expect in the future to be able to just min/max evict? if so, should there be a TODO and comment explaining why we sort instead of "select the session to evict" ?

File: src/transport/SecureSessionTable.cpp (hunk 4 above)
Comment (mrjerryjohns) [reply src/transport/SecureSessionTable.cpp:225]: Definitions of what each keyN does is already specified in the description of this function, so duplicating it here would seem redundant.

File: src/transport/SecureSessionTable.h [hunk 10]
```diff
@@ -230,6 +252,12 @@ class SecureSessionTable
 
     bool mRunningEvictionLogic = false;
     ObjectPool<SecureSession, CHIP_CONFIG_SECURE_SESSION_POOL_SIZE> mEntries;
+
+#if CONFIG_BUILD_FOR_HOST_UNIT_TEST
+    uint32_t mMaxSessionTableSize = CHIP_CONFIG_SECURE_SESSION_POOL_SIZE;
+    void SetMaxSessionTableSize(uint32_t size) { mMaxSessionTableSize = size; }
```
Comment (msandstedt) [inline src/transport/SecureSessionTable.h:258]:
```suggestion
    size_t mMaxSessionTableSize = CHIP_CONFIG_SECURE_SESSION_POOL_SIZE;
    void SetMaxSessionTableSize(size_t size) { mMaxSessionTableSize = size; }
```

File: src/transport/SecureSessionTable.cpp [hunk 11]
```diff
@@ -66,12 +66,18 @@ Optional<SessionHandle> SecureSessionTable::CreateNewSecureSession(SecureSession
     auto sessionId = FindUnusedSessionId();
     VerifyOrReturnValue(sessionId.HasValue(), Optional<SessionHandle>::Missing());
 
+#if CONFIG_BUILD_FOR_HOST_UNIT_TEST
+    uint32_t maxSessionTableSize = mMaxSessionTableSize;
+#else
+    uint32_t maxSessionTableSize = CHIP_CONFIG_SECURE_SESSION_POOL_SIZE;
```
Comment (msandstedt) [inline src/transport/SecureSessionTable.cpp:72]:
```suggestion
    size_t maxSessionTableSize = mMaxSessionTableSize;
#else
    size_t maxSessionTableSize = CHIP_CONFIG_SECURE_SESSION_POOL_SIZE;
```

File: src/transport/SecureSessionTable.cpp [hunk 12]
```diff
@@ -99,32 +105,59 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
 
     auto cleanup = MakeDefer([this]() { mRunningEvictionLogic = false; });
 
+#if CONFIG_BUILD_FOR_HOST_UNIT_TEST
+    uint32_t maxSessionTableSize = mMaxSessionTableSize;
+#else
+    uint32_t maxSessionTableSize = CHIP_CONFIG_SECURE_SESSION_POOL_SIZE;
```
Comment (msandstedt) [inline src/transport/SecureSessionTable.cpp:111]:
```suggestion
    size_t maxSessionTableSize = mMaxSessionTableSize;
#else
    size_t maxSessionTableSize = CHIP_CONFIG_SECURE_SESSION_POOL_SIZE;
```

File: src/transport/SecureSessionTable.cpp (hunk 3 above)
Comment (tehampson) [reply src/transport/SecureSessionTable.cpp:124]: Maybe add a comment here so someone else reading code directly understand reason why this is on the stack?

File: src/transport/tests/TestSecureSessionTable.cpp [hunk 13]
```diff
@@ -0,0 +1,424 @@
...
+        _this->CreateSessionTable(sessionParamList);
+        _this->AllocateSession(ScopedNodeId(2, kFabric1), sessionParamList, 3);
+    }
+
+    //
+    // This validates evicting an over-minima fabric from the session table where there
+    // are sessions from two fabrics, Fabric1 and Fabric2.
+    //
+    // Fabric1 has 2 sessions, and Fabric2 has 3 sessions. Fabric2 will be selected since
+    // it has more sessions than Fabric2.
```
Comment (tehampson) [inline src/transport/tests/TestSecureSessionTable.cpp:233]:
```suggestion
    // it has more sessions than Fabric1.
```

File: src/transport/tests/TestSecureSessionTable.cpp [hunk 14]
```diff
@@ -0,0 +1,424 @@
...
+
+        _this->CreateSessionTable(sessionParamList);
+        _this->AllocateSession(ScopedNodeId(2, kFabric1), sessionParamList, 3);
+    }
+
+    //
+    // This validates evicting an over-minima fabric from the session table where there
+    // are sessions from two fabrics, Fabric1 and Fabric2.
+    //
+    // Fabric1 has 2 sessions, and Fabric2 has 3 sessions. Fabric2 will be selected since
```
Comment (tehampson) [inline src/transport/tests/TestSecureSessionTable.cpp:232]:
```suggestion
    // Fabric1 has 2 sessions, and Fabric2 has 4 sessions. Fabric2 will be selected since
```

File: src/transport/SecureSessionTable.cpp (hunk 1 above)
Comment (mrjerryjohns) [reply src/transport/SecureSessionTable.cpp:313]: There are comments already about the speculative nature of eviction (i.e marking for eviction doesn't guarantee it frees up a slot), but it doesn't quite tie it to the need for sorting. So I can definitely add a comment there.

In the future, if we do ever get around to making `SessionHolder` a true weak ref (see #19495), then yes, we can always **guarantee** that the session we select will always be evictable, because we'd select sessions that have no strong-refs attached to them.

For now, that isn't possible. However, I think this raises a separate, interesting possibility - in the majority of cases, it is likely that the session selected for eviction will actually be evicted (i.e it shouldn't have strong refs attached to it), so just selecting the most likely candidate using an O(n) traversal, will suffice for most of those cases. In the cases where it doesn't, it starts to de-generate, but that shouldn't happen all that often.

For the purposes of getting this PR in, I'll add the comment, and file an issue exploring the O(n) linear min/max possibility.

File: src/transport/SecureSessionTable.cpp (hunk 2 above)
Comment (mrjerryjohns) [reply src/transport/SecureSessionTable.cpp:70]: Will make it constexpr.

It can't be global because it relies on the private member value inside the `SecureSessionTable` instance no?

File: src/transport/SecureSessionTable.cpp (hunk 3 above)
Comment (mrjerryjohns) [reply src/transport/SecureSessionTable.cpp:124]: Good point. Will add that extra comment with information.

File: src/transport/SecureSessionTable.cpp [hunk 15]
```diff
@@ -183,6 +220,100 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
 
 void SecureSessionTable::DefaultEvictionPolicy(EvictionPolicyContext & evictionContext)
 {
+    evictionContext.Sort([&evictionContext](const SortableSession & a, const SortableSession & b) {
+        //
+        // Sorting on Key1
+        //
+        if (a.mNumMatchingOnFabric > b.mNumMatchingOnFabric)
```
[the remark this answers is not in the document]
Comment (mrjerryjohns) [reply src/transport/SecureSessionTable.cpp:227]: Not sure how this removes indent logic, but I can buy the slight simplification. Will change.

File: src/transport/SecureSessionTable.cpp (hunk 9 above)
Comment (mrjerryjohns) [reply src/transport/SecureSessionTable.cpp:272]: How exactly would you envision the enum helping here?

File: src/transport/tests/TestSecureSessionTable.cpp (hunk 14 above)
Comment (mrjerryjohns) [reply src/transport/tests/TestSecureSessionTable.cpp:232]: Damn, you actually read the tests! Thanks for catching this.

File: src/controller/python/test/test_scripts/base.py [hunk 16]
```diff
@@ -380,15 +380,94 @@ async def TestCaseEviction(self, nodeid: int):
         # This tests establishing a subscription on a given CASE session, then mark it defunct (to simulate
         # encountering a transport timeout on the session).
```
Comment (bzbarsky-apple) [inline src/controller/python/test/test_scripts/base.py:381]:
```suggestion
        # This tests establishes a subscription on a given CASE session, then marks it defunct (to simulate
        # encountering a transport timeout on the session).
```

File: src/transport/SecureSessionTable.cpp [hunk 17]
```diff
@@ -99,32 +105,78 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
-        return nullptr;
-    }
+    // The size of this shouldn't place significant demands on the stack - each item is
+    // 8 bytes in size (on a 32-bit platform), and 16 bytes in size (on a 64-bit platform,
+    // including padding). A minimal, spec compliant value for CHIP_CONFIG_SECURE_SESSION_POOL_SIZE
+    // is:
+    //
+    // (3 sessions / fabric * 5 fabrics + 1 reserved for CASE + 1 reserved for PASE) = 17 sessions.
+    //
+    // Total size of this stack variable = 17 * 8 = 136bytes (32-bit platform), 272 bytes (64-bit platform).
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.cpp:131]: That's the minimal size.  The actual size can be much larger, but I think the key is that this is under the control of the device definition.....  And that even if CHIP_CONFIG_SECURE_SESSION_POOL_SIZE is quite large (e.g. 1000) this is 16KB or so, which is not so bad on the sort of setup that would have that sort of pool size.

File: src/transport/SecureSessionTable.cpp [hunk 18]
```diff
@@ -99,32 +105,78 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
 
     auto cleanup = MakeDefer([this]() { mRunningEvictionLogic = false; });
 
+#if CONFIG_BUILD_FOR_HOST_UNIT_TEST
+    const size_t kMaxSessionTableSize = mMaxSessionTableSize;
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.cpp:109]: Feels like this should be factored out into a method, since we have it in multiple places.

File: src/transport/SecureSessionTable.cpp [hunk 19]
```diff
@@ -99,32 +105,78 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+    // match its fabric, as well as the number of other sessions that match its peer.
+    //
+    // This will be used by the session eviction algorithm later.
+    //
+    ForEachSession([&index, &sortableSessions, this](auto session) {
+        sortableSessions[index].mSession             = session;
+        sortableSessions[index].mNumMatchingOnFabric = 0;
+        sortableSessions[index].mNumMatchingOnPeer   = 0;
+
+        ForEachSession([session, index, &sortableSessions](auto otherSession) {
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.cpp:158]: I wonder how this performs if `CHIP_CONFIG_SECURE_SESSION_POOL_SIZE` is 1000 or so....

File: src/transport/SecureSessionTable.cpp [hunk 20]
```diff
@@ -99,32 +105,78 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+
+    unsigned int index = 0;
+
+    //
+    // Compute two key stats for each session - the number of other sessions that
+    // match its fabric, as well as the number of other sessions that match its peer.
+    //
+    // This will be used by the session eviction algorithm later.
+    //
+    ForEachSession([&index, &sortableSessions, this](auto session) {
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.cpp:153]:
```suggestion
    ForEachSession([&index, &sortableSessions, this](auto * session) {
```
To make it clear we are getting pointers, for purposes of the `!=` compare below.

File: src/transport/SecureSessionTable.cpp (hunk 19 above)
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.cpp:158]:
```suggestion
        ForEachSession([session, index, &sortableSessions](auto * otherSession) {
```

File: src/transport/SecureSessionTable.cpp [hunk 21]
```diff
@@ -134,15 +186,19 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.cpp:186]: Should numSessions be const?

File: src/transport/SecureSessionTable.cpp [hunk 22]
```diff
@@ -183,6 +239,109 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+    evictionContext.Sort([&evictionContext](const SortableSession & a, const SortableSession & b) {
+        //
+        // Sorting on Key1
+        //
+        if (a.mNumMatchingOnFabric != b.mNumMatchingOnFabric)
+        {
+            return a.mNumMatchingOnFabric > b.mNumMatchingOnFabric;
+        }
+
+        if (a.mNumMatchingOnFabric == b.mNumMatchingOnFabric)
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.cpp:258]: Has to be true, no?  If they were not equal we aready returned.  So can remove this test and outdent...

File: src/transport/SecureSessionTable.cpp [hunk 23]
```diff
@@ -183,6 +239,109 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+
+            //
+            // Sorting on Key2
+            //
+            if (doesAMatchSessionHintFabric != doesBMatchSessionHintFabric)
+            {
+                return doesAMatchSessionHintFabric > doesBMatchSessionHintFabric;
+            }
+
+            if (doesAMatchSessionHintFabric == doesBMatchSessionHintFabric)
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.cpp:273]: Again, at this point this has to test true, so we can remove check and outdent.

File: src/transport/SecureSessionTable.cpp [hunk 24]
```diff
@@ -183,6 +239,109 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+            {
+                //
+                // Sorting on Key3
+                //
+                if (a.mNumMatchingOnPeer != b.mNumMatchingOnPeer)
+                {
+                    return a.mNumMatchingOnPeer > b.mNumMatchingOnPeer;
+                }
+
+                if (a.mNumMatchingOnPeer == b.mNumMatchingOnPeer)
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.cpp:283]: Same comment here.

File: src/transport/SecureSessionTable.cpp [hunk 25]
```diff
@@ -183,6 +239,109 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+
+                    //
+                    // Sorting on Key4
+                    //
+                    if (doesAMatchSessionHint != doesBMatchSessionHint)
+                    {
+                        return doesAMatchSessionHint > doesBMatchSessionHint;
+                    }
+
+                    if (doesAMatchSessionHint == doesBMatchSessionHint)
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.cpp:296]: Remove and outdent.

File: src/transport/SecureSessionTable.cpp [hunk 26]
```diff
@@ -183,6 +239,109 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+
+                        //
+                        // Sorting on Key5
+                        //
+                        if (aStateScore != bStateScore)
+                        {
+                            return (aStateScore > bStateScore);
+                        }
+
+                        if (aStateScore == bStateScore)
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.cpp:326]: Remove and outdent.

File: src/transport/SecureSessionTable.cpp [hunk 27]
```diff
@@ -183,6 +239,109 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+                            // Sorting on Key6
+                            //
+                            return (a->GetLastActivityTime() < b->GetLastActivityTime());
+                        }
+                    }
+                }
+            }
+        }
+
+        return false;
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.cpp:338]: This will be unreachable once all the outdents are done, which is good.  ;)

File: src/transport/SecureSessionTable.cpp [hunk 28]
```diff
@@ -183,6 +239,109 @@ SecureSession * SecureSessionTable::EvictAndAllocate(uint16_t localSessionId, Se
...
+    });
+
+#if 0
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.cpp:341]: I really prefer the single sort on multiple keys to multiple sorts.  Just remove this part.  Especially because that way we don't rely on sort stability, which makes it easier to change sort algorithms later if we want to.

File: src/transport/SecureSessionTable.h [hunk 29]
```diff
@@ -142,9 +142,13 @@ class SecureSessionTable
         }
 
         const Transport::SecureSession * operator->() const { return mSession; }
+        auto GetNumMatchingOnFabric() { return mNumMatchingOnFabric; }
+        auto GetNumMatchingOnPeer() { return mNumMatchingOnPeer; }
 
     private:
         SecureSession * mSession;
+        uint16_t mNumMatchingOnFabric;
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.h:150]: We need to static_assert that the pool size is not large enough to allow these to overflow.

File: src/transport/SecureSessionTable.h [hunk 30]
```diff
@@ -192,14 +196,32 @@ class SecureSessionTable
...
      *
-     *  - Sessions are sorted with their state as the primary sort key and activity time as the secondary
-     *    sort key.
-     *  - The primary sort key places defunct sessions ahead of active ones, ahead of anything else.
-     *  - The secondary sort key places older sessions ahead of newer sessions. This ensures
-     *    we're prioritizing reaping less active sessions over more recently active sessions (activity
-     *    in either TX or RX).
+     *  - Key1:  Sessions on fabrics that have more sessions in the table are placed ahead of sessions on fabrics
+     *           with lesser sessions. We conclusively know that if a particular fabric has more sessions in the table
+     *           than another, that that fabric is definitely over minimas (assuming a minimially sized session table
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.h:204]:
```suggestion
     *           than another, then that fabric is definitely over minimas (assuming a minimally sized session table
```

File: src/transport/SecureSessionTable.h [hunk 31]
```diff
@@ -192,14 +196,32 @@ class SecureSessionTable
...
+     *           conformant to spec minimas).
+     *
+     *    Key2:  Sessions that match the eviction hint's fabric are placed ahead of those that don't. This ensures that
+     *           if Key1 is even (i.e two fabrics are tied in count), that you attempt to select sessions that match
+     *           the eviction hint's fabric to ensure we evict sessions within the fabric that a new session might be about
+     *           to be created within. This is essential to preventing cross-fabric denial of service possibilities.
+     *
+     *    Key3:  Sessions with a higher mNumMatchingOnPeer are placed ahead of those with less. This ensures
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.h:212]:
```suggestion
     *    Key3:  Sessions with a higher mNumMatchingOnPeer are placed ahead of those with a lower one. This ensures
```

File: src/transport/SecureSessionTable.h [hunk 32]
```diff
@@ -192,14 +196,32 @@ class SecureSessionTable
...
+     *           we pick sessions that have a higher number of duplicated sessions to a peer over those with less since
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.h:213]:
```suggestion
     *           we pick sessions that have a higher number of duplicated sessions to a peer over those with lower since
```

**Review by bzbarsky-apple — APPROVED** [review]

File: src/transport/SecureSessionTable.cpp (hunk 17 above)
Comment (mrjerryjohns) [reply src/transport/SecureSessionTable.cpp:131]: Sure, I can add some text to that effect.

File: src/transport/SecureSessionTable.cpp (hunk 19 above)
Comment (mrjerryjohns) [reply src/transport/SecureSessionTable.cpp:158]: Not great, but short of doing a full-on sort & tally, I don't see how you can actually meaningfully improve on the n^2'ness of this....

Ideas welcome.

File: src/transport/SecureSessionTable.cpp (hunk 28 above)
Comment (mrjerryjohns) [reply src/transport/SecureSessionTable.cpp:341]: I had kept it in to poll folks as to which they preferred. Andrei preferred the single sort too (as do I), so will remove it.

File: src/transport/SecureSessionTable.cpp (hunk 27 above)
Comment (mrjerryjohns) [reply src/transport/SecureSessionTable.cpp:338]: That'll likely fix the broken Ameba C++ impl triggered compile error as well...!

File: src/transport/SecureSessionTable.h [hunk 33]
```diff
@@ -142,9 +142,19 @@ class SecureSessionTable
...
+        auto GetNumMatchingOnFabric() { return mNumMatchingOnFabric; }
+        auto GetNumMatchingOnPeer() { return mNumMatchingOnPeer; }
 
     private:
         SecureSession * mSession;
+        uint16_t mNumMatchingOnFabric;
+        uint16_t mNumMatchingOnPeer;
+
+        static_assert(CHIP_CONFIG_SECURE_SESSION_POOL_SIZE <= std::numeric_limits<decltype(mNumMatchingOnFabric)>::max(),
+                      "CHIP_CONFIG_SECURE_SESSION_POOL_SIZE must set to be less than or equal to 65535!");
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.h:154]:
```suggestion
                      "mNumMatchingOnFabric must be able to count up to CHIP_CONFIG_SECURE_SESSION_POOL_SIZE!");
```

File: src/transport/SecureSessionTable.h [hunk 34]
```diff
@@ -142,9 +142,19 @@ class SecureSessionTable
...
+        static_assert(CHIP_CONFIG_SECURE_SESSION_POOL_SIZE <= std::numeric_limits<decltype(mNumMatchingOnPeer)>::max(),
+                      "CHIP_CONFIG_SECURE_SESSION_POOL_SIZE must set to be less than or equal to 65535!");
```
Comment (bzbarsky-apple) [inline src/transport/SecureSessionTable.h:156]:
```suggestion
                      "mNumMatchingOnPeer must be able to count up to CHIP_CONFIG_SECURE_SESSION_POOL_SIZE!");
```

**Review by bzbarsky-apple — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]
