### PR TITLE
Enforce interface match for unauthenticated session, temporary fix #11120

### LINKED ISSUE #11120: Message is sent to the wrong interface
## Problem

My testing box have 2 different active network interfaces:

> 4: wlp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether d4:d2:52:79:9a:c8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.90.187/24 brd 192.168.90.255 scope global dynamic noprefixroute wlp2s0
       valid_lft 35978sec preferred_lft 35978sec
6: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:76:c8:60:61 brd ff:ff:ff:ff:ff:ff
    inet 192.168.9.1/24 brd 192.168.9.255 scope global docker0
       valid_lft forever preferred_lft forever

The controller sends a message to **192.168.9.1**, on the device side the message is received from **192.168.90.187**. So the message is sent via the wrong socket.

Expected packet: 192.168.9.1:5541 -> 192.168.9.1:5540
Actual packet: 192.168.90.187:5541 -> 192.168.9.1:5540

 we should response the message via the same interface where the message is received.

### Scenario

This is triggered by `scripts/tests/test_suites.sh`

1. Run ./out/debug/standalone/chip-all-clusters-app
1. Run ./out/debug/chip-tool pairing qrcode ...
1. Run ./out/debug/chip-tool test ...

#### During pairing phrase

Here is where the problem begins, in the following logs, the controller send a packet to **192.168.9.1**, this address is discovered by mDNS, but the packet is sent via the wrong interface.

Controller side

> [1635412318.928113][1128053:1128078] CHIP:DIS: Attempt to mDNS broadcast failed:  ../../src/inet/IPEndPointBasis.cpp:687: OS Error 0x02000065: Network is unreachable
[1635412318.928148][1128053:1128078] CHIP:DMG: ICR moving to [AwaitingDe]
[1635412318.928159][1128053:1128078] CHIP:EM: Sending Standalone Ack for MessageCounter:6 on exchange 48303i
[1635412318.928194][1128053:1128078] CHIP:IN: Prepared encrypted message 0x7fc110ada978 to 0x0000000012344321 of type 0x10 and protocolId (0, 0) on exchange 48303i with MessageCounter:11.
[1635412318.928202][1128053:1128078] CHIP:IN: Sending encrypted msg 0x7fc110ada978 with MessageCounter:11 to 0x0000000012344321 at monotonic time: 1337236480 msec
[1635412318.928208][1128053:1128078] CHIP:IN: Sending msg to address UDP:fdb9:e90f:246d:53e2:6a9c:214:9625:d001:5540
[1635412318.928249][1128053:1128078] CHIP:EM: Flushed pending ack for MessageCounter:6 on exchange 48303i
[1635412318.928254][1128053:1128078] CHIP:EM: ec-- id: 48303i
[1635412318.928326][1128053:1128078] CHIP:DIS: Node ID resolved for 0x0000000012344321 to [192.168.9.1]:5540
[1635412318.928354][1128053:1128078] CHIP:IN: Marking old secure session for device 0x0000000012344321 as expired
[1635412318.928360][1128053:1128078] CHIP:CTL: OnConnectionExpired was called for unknown device, ignoring it.
[1635412318.928365][1128053:1128078] CHIP:IN: New secure session created for device 0x0000000012344321, key 1!!
[1635412318.928601][1128053:1128078] CHIP:TOO: OnAddressUpdateComplete: 12344321: ../../src/controller/CHIPDevice.cpp:443: Success
[1635412318.928607][1128053:1128078] CHIP:CTL: OperationalDiscoveryComplete for device ID 305414945
[1635412318.928611][1128053:1128078] CHIP:CTL: Enabling CASE session establishment for the device
[1635412318.928713][1128053:1128078] CHIP:IN: Marking old secure session for device 0x0000000012344321 as expired
[1635412318.928992][1128053:1128078] CHIP:IN: Creating UnauthenticatedSession with PeerAddress UDP:192.168.9.1:5540
[1635412318.929016][1128053:1128078] CHIP:EM: ec++ id: 48304i with delegate @0x7fc11b8e0160
[1635412318.929182][1128053:1128078] CHIP:IN: Prepared plaintext message 0x559821b33010 to 0x0000000000000000 of type 0x30 and protocolId (0, 0) on exchange 48304i with MessageCounter:1568095081.
[1635412318.929197][1128053:1128078] CHIP:IN: Sending plaintext msg 0x559821b33010 with MessageCounter:1568095081 to 0x0000000000000000 at monotonic time: 1337236481 msec
[1635412318.929205][1128053:1128078] CHIP:IN: Sending msg to address UDP:192.168.9.1:5540
[1635412318.929252][1128053:1128078] CHIP:SC: Sent Sigma1 msg
[1635412318.929299][1128053:1128078] CHIP:DIS: Discovered node without a pending query
[1635412318.929309][1128053:1128078] CHIP:DIS: Node ID resolved for 0x0000000012344321 to [192.168.9.1]:5540

Device side:

> [1635412318.929268][1128023:1128023] CHIP:IN: Received msg from address UDP:192.168.90.187:5541
[1635412318.929283][1128023:1128023] CHIP:IN: Creating UnauthenticatedSession with PeerAddress UDP:192.168.90.187:5541
[1635412318.929304][1128023:1128023] CHIP:EM: Received message of type 0x30 with protocolId (0, 0) and MessageCounter:1568095081 on exchange 48304r
[1635412318.929339][1128023:1128023] CHIP:EM: ec++ id: 48304r with delegate @0x555c50c309a8
[1635412318.929346][1128023:1128023] CHIP:EM: Handling via exchange: 48304r, Delegate: 0x0x555c50c309a8
[1635412318.929357][1128023:1128023] CHIP:IN: CASE Server received Sigma1 message. Starting handshake. EC 0x555c50c30fb0
[1635412318.929364][1128023:1128023] CHIP:IN: Marking old secure session for device 0x0000000000000000 as expired
[1635412318.929373][1128023:1128023] CHIP:DIS: CASE handshake initiated, closing all BLE Connections
[1635412318.929380][1128023:1128023] CHIP:SC: Waiting for Sigma1 msg
[1635412318.929385][1128023:1128023] CHIP:IN: CASE Server disabling CASE session setups
[1635412318.929392][1128023:1128023] CHIP:SC: Received Sigma1 msg
[1635412318.929405][1128023:1128023] CHIP:SC: Peer assigned session key ID 2
[1635412318.929414][1128023:1128023] CHIP:DIS: Fabric (1) loaded from storage. Calling OnFabricRetrievedFromStorage
[1635412318.929420][1128023:1128023] CHIP:ZCL: OpCreds: Fabric 0x1 was retrieved from storage. FabricId 0x0000000000000000, NodeId 0x0000000012344321, VendorId 0x000A
[1635412318.929426][1128023:1128023] CHIP:ZCL: OpCreds: Call to writeFabricsIntoFabricsListAttribute
[1635412318.929460][1128023:1128023] CHIP:ZCL: OpCreds: Writing fabric into attribute store at index 0: fabricId 0x0000000000000000, nodeId 0x0000000012344321 vendorId 0x000A
[1635412318.929473][1128023:1128023] CHIP:ZCL: OpCreds: Stored 1 fabrics in fabrics list attribute.

#### During test phrase

Controller sends message:

> [1635412319.074908][1128079:1128093] CHIP:IN: Creating UnauthenticatedSession with PeerAddress UDP:192.168.90.187:5540
[1635412319.074938][1128079:1128093] CHIP:EM: ec++ id: 13075i with delegate @0x7f7da4560160
[1635412319.075071][1128079:1128093] CHIP:IN: Prepared plaintext message 0x55bdb50c3720 to 0x0000000000000000 of type 0x30 and protocolId (0, 0) on exchange 13075i with MessageCounter:2354484034.
[1635412319.075085][1128079:1128093] CHIP:IN: Sending plaintext msg 0x55bdb50c3720 with MessageCounter:2354484034 to 0x0000000000000000 at monotonic time: 1337236627 msec
[1635412319.075090][1128079:1128093] CHIP:IN: Sending msg to address UDP:192.168.90.187:5540
[1635412319.075136][1128079:1128093] CHIP:SC: Sent Sigma1 msg

Device receives message and sends reply

> [1635412319.075169][1128023:1128023] CHIP:IN: Received msg from address UDP:192.168.90.187:5541
[1635412319.075191][1128023:1128023] CHIP:EM: Received message of type 0x30 with protocolId (0, 0) and MessageCounter:2354484034 on exchange 13075r
[1635412319.075199][1128023:1128023] CHIP:EM: ec++ id: 13075r with delegate @0x555c50c309a8
[1635412319.075204][1128023:1128023] CHIP:EM: Handling via exchange: 13075r, Delegate: 0x0x555c50c309a8
[1635412319.075213][1128023:1128023] CHIP:IN: CASE Server received Sigma1 message. Starting handshake. EC 0x555c50c30fb0
[1635412319.075217][1128023:1128023] CHIP:DIS: CASE handshake initiated, closing all BLE Connections
[1635412319.075224][1128023:1128023] CHIP:SC: Waiting for Sigma1 msg
[1635412319.075228][1128023:1128023] CHIP:IN: CASE Server disabling CASE session setups
[1635412319.075232][1128023:1128023] CHIP:SC: Received Sigma1 msg
[1635412319.075244][1128023:1128023] CHIP:SC: Peer assigned session key ID 4
[1635412319.075249][1128023:1128023] CHIP:DIS: Fabric (1) loaded from storage. Calling OnFabricRetrievedFromStorage
[1635412319.075253][1128023:1128023] CHIP:ZCL: OpCreds: Fabric 0x1 was retrieved from storage. FabricId 0x0000000000000000, NodeId 0x0000000012344321, VendorId 0x000A
[1635412319.075258][1128023:1128023] CHIP:ZCL: OpCreds: Call to writeFabricsIntoFabricsListAttribute
[1635412319.075292][1128023:1128023] CHIP:ZCL: OpCreds: Writing fabric into attribute store at index 0: fabricId 0x0000000000000000, nodeId 0x0000000012344321 vendorId 0x000A
[1635412319.075304][1128023:1128023] CHIP:ZCL: OpCreds: Stored 1 fabrics in fabrics list attribute.
[1635412319.075339][1128023:1128023] CHIP:DIS: Fabric (1) loaded from storage. Calling OnFabricRetrievedFromStorage
[1635412319.075346][1128023:1128023] CHIP:ZCL: OpCreds: Fabric 0x1 was retrieved from storage. FabricId 0x0000000000000000, NodeId 0x0000000012344321, VendorId 0x000A
[1635412319.075352][1128023:1128023] CHIP:ZCL: OpCreds: Call to writeFabricsIntoFabricsListAttribute
[1635412319.075372][1128023:1128023] CHIP:ZCL: OpCreds: Writing fabric into attribute store at index 0: fabricId 0x0000000000000000, nodeId 0x0000000012344321 vendorId 0x000A
[1635412319.075381][1128023:1128023] CHIP:ZCL: OpCreds: Stored 1 fabrics in fabrics list attribute.
[1635412319.075681][1128023:1128023] CHIP:EM: Piggybacking Ack for MessageCounter:2354484034 on exchange: 13075r
[1635412319.075692][1128023:1128023] CHIP:IN: Prepared plaintext message 0x555c50c30ea8 to 0x0000000000000000 of type 0x31 and protocolId (0, 0) on exchange 13075r with MessageCounter:1414302350.
[1635412319.075699][1128023:1128023] CHIP:IN: Sending plaintext msg 0x555c50c30ea8 with MessageCounter:1414302350 to 0x0000000000000000 at monotonic time: 1337236627 msec
[1635412319.075705][1128023:1128023] CHIP:IN: Sending msg to address UDP:192.168.90.187:5541
[1635412319.075749][1128023:1128023] CHIP:SC: Sent Sigma2 msg

Controller receives message:

> [1635412319.075767][1128079:1128093] CHIP:IN: Received msg from address UDP:192.168.9.1:5540
[1635412319.075780][1128079:1128093] CHIP:IN: Creating UnauthenticatedSession with PeerAddress UDP:192.168.9.1:5540
[1635412319.075794][1128079:1128093] CHIP:EM: Received message of type 0x31 with protocolId (0, 0) and MessageCounter:1414302350 on exchange 13075i

Due to that the message is on a different UnauthenticatedSession, it is unable to match the session with the original exchange, so it is unable to handle the message.

## Proposed Solution
* Ensure interface id is set properly to device address when discovered by mDNS.
* `UDP::SendMessage` should honor interface in `PeerAddress`.

### PR DESCRIPTION
**Pull request by kghost**
#### Problem
#11120 

#### Change overview
Ensure that interface should match when matching unauthenticated session, if the interface is not null

#### Testing
Verified by unit-tests
Verified by scripts/tests/test_suites.sh

Haven't observed error in #11120, but have observed several mDNS discovery timeout error. It is probably unrelated to this PR.

```
[1635792380.261110][1098785:1098785] CHIP:DL: MDNS failed to join multicast group on enp0s31f6 for address type IPv4: ../../src/inet/UDPEndPoint.cpp:1453: Inet Error 0x00000110: Address not found
[1635792380.261804][1098785:1098785] CHIP:ZCL: Using ZAP configuration...
[1635792380.262466][1098785:1098785] CHIP:DIS: Verifying the received credentials
[1635792380.263859][1098785:1098785] CHIP:IN: Generating compressed fabric ID using uncompressed fabric ID 0x0000000000000000 and root pubkey
[1635792380.263889][1098785:1098785] CHIP:IN: 0x04, 0x31, 0xcd, 0x87, 0xde, 0xa9, 0xa8, 0x69, 
[1635792380.263907][1098785:1098785] CHIP:IN: 0x15, 0xe0, 0xf2, 0x6d, 0x39, 0x28, 0x02, 0x4e, 
[1635792380.263924][1098785:1098785] CHIP:IN: 0x77, 0x94, 0xd1, 0x77, 0x02, 0x3f, 0x22, 0xd6, 
[1635792380.263944][1098785:1098785] CHIP:IN: 0x78, 0xcd, 0x85, 0x90, 0x4c, 0x97, 0x2e, 0x28, 
[1635792380.263963][1098785:1098785] CHIP:IN: 0x59, 0x32, 0x1a, 0x05, 0x2a, 0xeb, 0x08, 0x2f, 
[1635792380.263983][1098785:1098785] CHIP:IN: 0xd3, 0x9c, 0x72, 0xa6, 0x2f, 0xe1, 0x9a, 0x70, 
[1635792380.264001][1098785:1098785] CHIP:IN: 0x39, 0xf5, 0xec, 0x10, 0xd5, 0x12, 0xcf, 0x77, 
[1635792380.264020][1098785:1098785] CHIP:IN: 0xe7, 0x44, 0x2b, 0xbe, 0x8a, 0x46, 0xcd, 0x9f, 
[1635792380.264036][1098785:1098785] CHIP:IN: 0xac, 
[1635792380.264101][1098785:1098785] CHIP:IN: Generated compressed fabric ID
[1635792380.264121][1098785:1098785] CHIP:IN: 0xee, 0x03, 0xe1, 0xb6, 0x06, 0x26, 0xb1, 0x06, 
[1635792380.264146][1098785:1098785] CHIP:DIS: Added new fabric at index: 1, Initialized: 1
[1635792380.264164][1098785:1098785] CHIP:DIS: Assigned compressed fabric ID: 0xEE03E1B60626B106, node ID: 0x000000000001B669
[1635792380.264183][1098785:1098785] CHIP:CTL: Joined the fabric at index 1. Compressed fabric ID is: 0xEE03E1B60626B106
[1635792380.264406][1098785:1098799] CHIP:DL: CHIP task running
[1635792380.264609][1098785:1098799] CHIP:DIS: Attempt to mDNS broadcast failed:  ../../src/inet/UDPEndPoint.cpp:1085: OS Error 0x02000065: Network is unreachable
        [1635792384.922267][1098752:1098752] CHIP:DIS: Broadcasting mDns reply for query from 192.168.90.193
        [1635792390.042901][1098752:1098752] CHIP:DIS: Broadcasting mDns reply for query from 192.168.90.193
[1635792500.264921][1098785:1098785] CHIP:-: ../../examples/chip-tool/commands/common/CHIPCommand.cpp:125: CHIP Error 0x00000032: Timeout at ../../examples/chip-tool/commands/common/CHIPCommand.cpp:84
[1635792500.265029][1098785:1098785] CHIP:TOO: Run command failure: ../../examples/chip-tool/commands/common/CHIPCommand.cpp:125: CHIP Error 0x00000032: Timeout
[1635792500.320322][1098785:1098785] CHIP:CTL: Shutting down the System State, this will teardown the CHIP Stack
[1635792500.320444][1098785:1098785] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-orqMga)
[1635792500.320660][1098785:1098785] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1635792500.320679][1098785:1098785] CHIP:DL: NVS set: chip-counters/total-operational-hours = 0 (0x0)
[1635792500.320696][1098785:1098785] CHIP:DL: Inet Layer shutdown
[1635792500.320756][1098785:1098785] CHIP:DL: BLE layer shutdown
[1635792500.320767][1098785:1098785] CHIP:DL: System Layer shutdown
```

### CODE REVIEW

**Review by msandstedt — APPROVED** [review]

File: src/transport/UnauthenticatedSessionTable.h [hunk 1]
```diff
@@ -175,6 +175,21 @@ class UnauthenticatedSessionTable
...
+    // Enforce interface match if not null
+    static bool MatchInterface(Inet::InterfaceId i1, Inet::InterfaceId i2)
+    {
+        if (i1.IsPresent() && i2.IsPresent())
+        {
+            return i1 == i2;
+        }
+        else
+        {
+            // One of the interface is null
```
Comment (bzbarsky-apple) [inline src/transport/UnauthenticatedSessionTable.h:188]:
```suggestion
            // One of the interfaces is null.
```

**Review by bzbarsky-apple — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by jmeg-sfy — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
TE6 cherrypicks are closed, however I cherrypicked into TE6 LTS branch
