### PR TITLE
Move registering signal handlers out of SDK

### LINKED ISSUE #38944: [BUG] Linux platform code registers signal handlers for SIGINT
### Reproduction steps

https://github.com/project-chip/connectedhomeip/blob/d6b2cee14153c289c5089af8ea95d56e55a2e079/src/platform/Linux/ConnectivityManagerImpl.cpp#L154-L158

Signal handler (if needed) should be installed by the application which uses SDK, not the other way.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

d6b2cee14153c289c5089af8ea95d56e55a2e079

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by crlonxp**
#### Testing

* Environment:
    AP: Asus RT-N66U, running at chnl#1
    ctrl: Rpi + NetGear, Inc. A6210
    dut#1: rpi + Linksys AE6000
    dut#2: imx93+iw612
* commands:
    [commissionee]
        $ ./chip-all-clusters-app --wifi --wifipaf freq_list=2412
    [commissioner]
        $ ./chip-tool pairing code-wifi 1 n_m_2g nxp12345 MT:-24J0M3810KA0648G00 --freq 2412
        or
        $ ./chip-tool pairing wifipaf-wifi 1 n_m_2g nxp12345 20202021 3840 --freq 2412

*  Press ctrl+c before really pairing with the device and make sure the publish and subscription can be canceled
*  Press ctrl+c to stop the pairing in interactive mode

Fixes #38944

### CODE REVIEW

File: examples/chip-tool/commands/pairing/PairingCommand.cpp [hunk 1]
```diff
@@ -63,6 +82,11 @@ CHIP_ERROR PairingCommand::RunInternal(NodeId remoteId)
 {
     CHIP_ERROR err = CHIP_NO_ERROR;
 
+#if CHIP_DEVICE_LAYER_TARGET_LINUX && CHIP_DEVICE_CONFIG_ENABLE_WIFIPAF
+    struct sigaction sa = {};
```
Comment (andy31415) [inline examples/chip-tool/commands/pairing/PairingCommand.cpp:86]: how about having this in the chip-tool main? That would make it clear what happens when the user stops things.

How does interact with https://github.com/project-chip/connectedhomeip/blob/master/examples/platform/linux/AppMain.cpp#L841? Is chip-tool using a different main? Or is this overriding that one (it should not I believe).

Comment (crlonxp) [reply examples/chip-tool/commands/pairing/PairingCommand.cpp:86]: AppMain.cpp is not used in chip-tool.

**Review by andy31415 — APPROVED** [review]

File: src/controller/SetUpCodePairer.cpp [hunk 2]
```diff
@@ -400,6 +404,10 @@ void SetUpCodePairer::OnWifiPAFDiscoveryError(CHIP_ERROR err)
 {
     ChipLogError(Controller, "Commissioning discovery over WiFiPAF failed: %" CHIP_ERROR_FORMAT, err.Format());
     mWaitingForDiscovery[kWiFiPAFTransport] = false;
+    if (mPairingDelegate != nullptr)
+    {
+        mPairingDelegate->OnPairingComplete(err);
```
Comment (bzbarsky-apple) [inline src/controller/SetUpCodePairer.cpp:409]: This is wrong.  Why is pairing complete just because PAF failed somehow?  The device might not even be advertising over PAF and will be commissioned over some other channel.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: examples/chip-tool/commands/pairing/PairingCommand.cpp [hunk 3]
```diff
@@ -242,6 +242,7 @@ CHIP_ERROR PairingCommand::PairWithCode(NodeId remoteId)
     }
 
     ReturnErrorOnFailure(MaybeDisplayTermsAndConditions(commissioningParams));
+    CurrentCommissioner().RegisterPairingDelegate(this);
```
Comment (bzbarsky-apple) [inline examples/chip-tool/commands/pairing/PairingCommand.cpp:245]: Why?  If we are here, we got called from RunInternal, which got called from `PairingCommand::RunCommand` which already did this.

Comment (andy31415) [inline examples/chip-tool/commands/pairing/PairingCommand.cpp:245]: This also seems unrelated with "move signal handling out of SDK".

Why these changes? Can it be a separate PR? Or explain the changes in the summary.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/controller/SetUpCodePairer.cpp (hunk 2 above)
Comment (andy31415) [reply src/controller/SetUpCodePairer.cpp:409]: In hindsight this was indeed unrelated to "move signal handling out of the SDK"....

Could we have either separate PRs for separate work or explain in the summary why changing one thing had sideffects.

File: src/platform/Linux/ConnectivityManagerImpl.h [hunk 4]
```diff
@@ -260,7 +260,6 @@ class ConnectivityManagerImpl final : public ConnectivityManager,
 #if CHIP_DEVICE_CONFIG_ENABLE_WIFIPAF
     OnConnectionCompleteFunct mOnPafSubscribeComplete;
     OnConnectionErrorFunct mOnPafSubscribeError;
-    WiFiPAF::WiFiPAFLayer * pmWiFiPAF;
```
Comment (andy31415) [inline src/platform/Linux/ConnectivityManagerImpl.h:263]: how is this related to "move signal handlers out of the SDK" ?

File: examples/chip-tool/main.cpp [hunk 5]
```diff
@@ -33,11 +33,42 @@
...
+    });
+}
+#endif
+
 // ================================================================================
 // Main Code
 // ================================================================================
 int main(int argc, char * argv[])
 {
+#if CHIP_DEVICE_LAYER_TARGET_LINUX && CHIP_DEVICE_CONFIG_ENABLE_WIFIPAF
```
[the remark this answers is not in the document]
Comment (crlonxp) [reply examples/chip-tool/main.cpp:64]: It's because I only have tested it on the Linux platform. And PAF is supported on Linux for now.

File: examples/chip-tool/commands/pairing/PairingCommand.cpp (hunk 3 above)
Comment (crlonxp) [reply examples/chip-tool/commands/pairing/PairingCommand.cpp:245]: I found the mPairingDelegate won't be set without this that PairingCommand::OnPairingComplete() won't be called

Comment (crlonxp) [reply examples/chip-tool/commands/pairing/PairingCommand.cpp:245]: It's a problem I found while moving signal handler out that PairingCommand::OnPairingComplete() won't be called if stopping it unexpectedly.

**Review by xiaolonghca — APPROVED** [review]

File: examples/chip-tool/commands/pairing/PairingCommand.cpp (hunk 3 above)
Comment (bzbarsky-apple) [reply examples/chip-tool/commands/pairing/PairingCommand.cpp]: How, exactly?  Again, our caller does this, right?

But again: nothing to do with signal handlers.

File: examples/chip-tool/main.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply examples/chip-tool/main.cpp:64]: Well, shouldn't this just be conditioned on CHIP_DEVICE_CONFIG_ENABLE_WIFIPAF and if someone turns that on for something that's not Linux that will do the right thing, then (as in, enable this code, which they presumably need)?

File: examples/chip-tool/main.cpp [hunk 6]
```diff
@@ -33,11 +33,42 @@
...
 #include <zap-generated/cluster/Commands.h>
 
+#include "platform/PlatformManager.h"
+
+#if CHIP_DEVICE_CONFIG_ENABLE_WIFIPAF
+using namespace chip::WiFiPAF;
+#endif
+
+#if CHIP_DEVICE_LAYER_TARGET_LINUX && CHIP_DEVICE_CONFIG_ENABLE_WIFIPAF
+static void StopSignalHandler(int signum)
```
Comment (bzbarsky-apple) [inline examples/chip-tool/main.cpp:43]: So a larger question:  Shouldn't this just happen via the normal shutdown codepath, instead of directly off the signal handler?  As in, is the issue just that chip-tool does not do a "clean shutdown" on Ctrl-C?  But then how is the "just run to completion" handled?

Basically: I don't understand why we are doing this signal handler at all, and only doing it for chip-tool, not server apps.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: examples/chip-tool/main.cpp (hunk 6 above)
Comment (crlonxp) [reply examples/chip-tool/main.cpp:43]: There is no issue in the normal execution path that CHIPCommand::MaybeTearDownStack() is called to shutdown the commissioner properly. The PAF shutdown function is invoked as part of the process.

However, a problem arises when the user terminate the chip-tool application abnormally using ctrl+c. Since no signal handling function is hooked, the program exits immediately and the shutdown function is not called.

The other apps (like all-clusters-app on Linux), the signal handling function is implemented in example/linux/AppMain.cpp. But it's no included in chip-tool project

File: examples/chip-tool/main.cpp [hunk 7]
```diff
@@ -33,13 +33,28 @@
 
 #include <zap-generated/cluster/Commands.h>
 
+static Commands commands;
+
+#if CHIP_DEVICE_LAYER_TARGET_LINUX
```
Comment (bzbarsky-apple) [inline examples/chip-tool/main.cpp:38]: Again, why is this Linux-only?

File: examples/chip-tool/commands/common/Commands.h [hunk 8]
```diff
@@ -44,8 +44,10 @@ class Commands
     }
     int Run(int argc, char ** argv);
     int RunInteractive(const char * command, const chip::Optional<char *> & storageDirectory, bool advertiseOperational);
+    void SetCommandExitStatus(CHIP_ERROR status);
 
 private:
+    Command * mActiveCommand = nullptr;
```
Comment (bzbarsky-apple) [inline examples/chip-tool/commands/common/Commands.h:50]: How does this handle interactive mode, where you have the overall "interactive start" command _and_ can have another command running under it?

Looks to me like this will cancel the "inner" command but then not actually quit interactive mode.  Is that the desired behavior?  If so, it might be best to document it.

File: examples/chip-tool/commands/common/Commands.cpp [hunk 9]
```diff
@@ -328,9 +329,18 @@ CHIP_ERROR Commands::RunCommand(int argc, char ** argv, bool interactive,
...
 
+    mActiveCommand = command;
     return command->Run();
 }
 
+void Commands::SetCommandExitStatus(CHIP_ERROR status)
+{
+    if (mActiveCommand != nullptr)
+    {
+        return mActiveCommand->SetCommandExitStatus(status);
```
Comment (bzbarsky-apple) [inline examples/chip-tool/commands/common/Commands.cpp:340]: It's really not clear to me that this handles our two event loop models correctly.  `#if !CONFIG_USE_SEPARATE_EVENTLOOP` then this is safe to call, presumably... though nothing guarantees our signal handler is in fact called on the Matter (main) thread, really.

But if we have a separate event loop, then the command exit status should only be touched on the Matter queue, right?  And that's running on some non-main thread.

File: examples/chip-tool/commands/pairing/PairingCommand.cpp [hunk 10]
```diff
@@ -59,6 +59,18 @@ CHIP_ERROR PairingCommand::RunCommand()
...
 }
 
+void PairingCommand::CancelCommand(CHIP_ERROR status)
+{
+    ChipLogProgress(chipTool, "Cancel pairing: %s", chip::ErrorStr(status));
+#if CHIP_DEVICE_CONFIG_ENABLE_WIFIPAF
+    if ((mPairingMode == PairingMode::WiFiPAF) || (mPairingMode == PairingMode::Code))
+    {
+        ChipLogProgress(chipTool, "Cancel pairing, node: %lu", mNodeId);
+        chip::WiFiPAF::WiFiPAFLayer::GetWiFiPAFLayer().CancelSession(mNodeId, chip::WiFiPAF::kWiFiPafRole_Subscriber);
```
Comment (bzbarsky-apple) [inline examples/chip-tool/commands/pairing/PairingCommand.cpp:69]: Why are we touching PAF stuff manually here?  Shouldn't this just happen during normal stack shutdown if we just go ahead and shut down the stack cleanly?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: examples/chip-tool/main.cpp (hunk 7 above)
Comment (crlonxp) [reply examples/chip-tool/main.cpp:38]: I will remove the limitation

File: examples/chip-tool/commands/common/Commands.h (hunk 8 above)
Comment (crlonxp) [reply examples/chip-tool/commands/common/Commands.h:50]: The current implementation is to exit the app directly. (No signal handler is hooked) But I think it seems more reasonable just to revoke the inner running command. For example, if the parameters are incorrect, user can just revoke this command and re-issue it again, instead of leaving the app and drop everything. User can have another ctrl+c to close the app.

File: examples/chip-tool/commands/common/Commands.cpp (hunk 9 above)
Comment (crlonxp) [reply examples/chip-tool/commands/common/Commands.cpp:340]: If the purpose is to revoke the inner command, is it still a problem? Or could you let me know what problem may it be? StartWaiting() and StopWaiting() have 2 implementations with/without CONFIG_USE_SEPARATE_EVENTLOOP that it seems can handle it, isn't it correct?

File: examples/chip-tool/commands/pairing/PairingCommand.cpp (hunk 10 above)
Comment (crlonxp) [reply examples/chip-tool/commands/pairing/PairingCommand.cpp:69]: If we did not shutdown stack, we need to cancel the subscription we did in the previous pairing command.

File: examples/chip-tool/commands/common/Commands.h (hunk 8 above)
Comment (bzbarsky-apple) [reply examples/chip-tool/commands/common/Commands.h:51]: "another ctrl+c to close the app" won't work, since mActiveCommand will be wrong at that point, no?

File: examples/chip-tool/commands/common/Commands.cpp (hunk 9 above)
Comment (bzbarsky-apple) [reply examples/chip-tool/commands/common/Commands.cpp:340]: This is a problem independent of what the desired behavior is.   You need to do SetCommandExitStatus on the thread it expects to happen on, if you want to avoid having thread races....

File: examples/chip-tool/commands/pairing/PairingCommand.cpp (hunk 10 above)
Comment (bzbarsky-apple) [reply examples/chip-tool/commands/pairing/PairingCommand.cpp:69]: How does this work for "normal" pairing when pairing is stopped without shutting down the stack? 

It feels like we are adding a chip-tool specific fix for what is a core problem here...

Comment (crlonxp) [reply examples/chip-tool/commands/pairing/PairingCommand.cpp:69]: In the normal condition, commissionee will shutdown the PAF session while the commissioning is completed. Then if the session has started and no traffic for a long time, the commissioner will also shutdown the PAF session.
I will add to cancel the command after it's done to be more explicitly.

File: examples/chip-tool/commands/common/Commands.h (hunk 8 above)
Comment (crlonxp) [reply examples/chip-tool/commands/common/Commands.h:51]: "another ctrl+c" will break the readline() in InteractiveStartCommand::GetCommand(). Even the signal handling function has been registered, it won't be called and the program will exit directly

File: examples/chip-tool/commands/pairing/PairingCommand.cpp (hunk 10 above)
Comment (bzbarsky-apple) [reply examples/chip-tool/commands/pairing/PairingCommand.cpp:69]: chip-tool is the commissioner, not the commissionee.  So in the "normal condition", what cancels the PAF stuff on the commissioner side if commissioning is interrupted?

File: examples/chip-tool/commands/common/Commands.cpp (hunk 9 above)
Comment (crlonxp) [reply examples/chip-tool/commands/common/Commands.cpp:340]: If the expect behavior is to cancel the running command, could you let me know what function can I reference to add SetCommandExitStatus() on other threads like you mentioned? 
Take the pairing command as the example. If issuing "pairing ble-wifi" and wait until time-out, PairingCommand::OnPairingComplete() is called with Timeout. It is also just to call SetCommandExitStatus(err); Won't it have the thread racing problem? Do I miss anything?

File: examples/chip-tool/commands/pairing/PairingCommand.cpp (hunk 10 above)
Comment (crlonxp) [reply examples/chip-tool/commands/pairing/PairingCommand.cpp:69]: There is a time-out if the traffic stops too long that it will cancel the PAF. I added to cancel PAF once it's completed yesterday in the PR.

File: examples/chip-tool/commands/common/Commands.cpp (hunk 9 above)
Comment (bzbarsky-apple) [reply examples/chip-tool/commands/common/Commands.cpp:340]: SetCommandExitStatus is called on the thread where the command is running, no?  For PairingCommand::OnPairingComplete, for example, that's on whatever thread the Matter event queue is running on.  It changes the status and then calls CHIPCommand::StopWaiting, which handles the thread synchronization with other threads.  But first it sets the exit status, and that part should only be touched on the thread where the command lives.

File: examples/chip-tool/commands/pairing/PairingCommand.cpp (hunk 10 above)
Comment (bzbarsky-apple) [reply examples/chip-tool/commands/pairing/PairingCommand.cpp:69]: I guess I am basically being confused about why the commissioner in chip-tool needs special logic here that is different from "normal" commissioners.  It feels like we are trying to special-case chip-tool somehow when the right fix should be somewhere deeper....

Comment (crlonxp) [reply examples/chip-tool/commands/pairing/PairingCommand.cpp:69]: I will add an API, similar with CloseBleConnection() in DeviceCommissioner and move the code there.

**Review by bzbarsky-apple — APPROVED** [review]
