### PR TITLE
Thread Diagnostic cluster - Encode structs and list attributes and fix issues

### LINKED ISSUE #10109: ThreadNetworkDiagnostics - ResetCounts
#### Problem
the ResetCounts (ThreadNetworkDiagnostics) command should only reset the OverrunCount.
Matter Specification: 11.13.6.1. ResetCounts

https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/DiagnosticsThread.adoc#16-commands

This means that the current implementation resets too many counters.
It seems that it's intentional behavior, not just the issue just in the command section in the spec, for example, each attribute has a clear description when it has to be reset.

https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/DiagnosticsThread.adoc#rxerrinvalidscraddrcount-attribute

### LINKED ISSUE #12099: [TC-DIAG-TH_NW-1.2] Attributes [DUT Server] - channel ID returned a uInt8 (not uInt16) in lighting-examples nxp/k32w/k32w
#### Problem
When testing in Test Event 7, it was observed that the type reported by the DUT was not matching the expected type:
 * expected behaviour:
   ` ./chip-tool threadnetworkdiagnostics read channel 1 0 `
    should return Int16u type
 * actual behavior
    returns Int8u type

```
[1637583226.266983][5283:5288] CHIP:DMG: ReportData =
[1637583226.267048][5283:5288] CHIP:DMG: {
[1637583226.267104][5283:5288] CHIP:DMG: 	AttributeDataList =
[1637583226.267170][5283:5288] CHIP:DMG: 	[
[1637583226.267232][5283:5288] CHIP:DMG: 		AttributeDataElement =
[1637583226.267301][5283:5288] CHIP:DMG: 		{
[1637583226.267366][5283:5288] CHIP:DMG: 			AttributePath =
[1637583226.267438][5283:5288] CHIP:DMG: 			{
[1637583226.267523][5283:5288] CHIP:DMG: 				NodeId = 0x1,
[1637583226.267601][5283:5288] CHIP:DMG: 				EndpointId = 0x0,
[1637583226.267679][5283:5288] CHIP:DMG: 				ClusterId = 0x35,
[1637583226.267756][5283:5288] CHIP:DMG: 				FieldTag = 0x0000_0000,
[1637583226.267820][5283:5288] CHIP:DMG: 			}
[1637583226.267889][5283:5288] CHIP:DMG: 				
[1637583226.267955][5283:5288] CHIP:DMG: 			Data = 15, 
[1637583226.268020][5283:5288] CHIP:DMG: 			DataElementVersion = 0x0,
[1637583226.268080][5283:5288] CHIP:DMG: 		},
[1637583226.268146][5283:5288] CHIP:DMG: 		
[1637583226.268197][5283:5288] CHIP:DMG: 	],
[1637583226.268261][5283:5288] CHIP:DMG: 	
[1637583226.268307][5283:5288] CHIP:DMG: }
[1637583226.268462][5283:5288] CHIP:ZCL: ReadAttributesResponse:
[1637583226.268510][5283:5288] CHIP:ZCL:   ClusterId: 0x0000_0035
[1637583226.268560][5283:5288] CHIP:ZCL:   attributeId: 0x0000_0000
[1637583226.268607][5283:5288] CHIP:ZCL:   status: Success                (0x0000)
[1637583226.268650][5283:5288] CHIP:ZCL:   attribute TLV Type: 0x04
[1637583226.268695][5283:5288] CHIP:TOO: Int8u attribute Response: 15
```

Unclear if the test spec and spec are correct or if it is an underlying issue in the cluster definition in zapt.
in ./zzz_generated/app-common/cluster-objects.h line 8168 (on test_event_7.lts branch):

Master: https://github.com/project-chip/connectedhomeip/blob/a3b642aa7e61e34dfc7408a4e9c17523d239afd9/zzz_generated/app-common/app-common/zap-generated/cluster-objects.h#L9957

struct TypeInfo
{
    using Type          = uint8_t;
    using DecodableType = uint8_t;

    static constexpr ClusterId GetClusterId() { return Clusters::ThreadNetworkDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::Channel::Id; }
};
} // namespace Channel

 #### Proposed Solution
- Check the zap definition is correct (int16 or int8?)
- regenerate auto-gen code.

### PR DESCRIPTION
**Pull request by jmartinez-silabs**
#### Problem
Attributes with struct or lists types were not encoded and would return errors or empty list
Fixes #10109 - ResetCounts should only reset OverrunCount
Fixes #12099 - channel ID returned a uInt8 (not uInt16)
RoutingRole attribute returned values didn't match the matter spec

#### Change overview
- Encode the missing attributes that are lists or struct types ( NeighborTable, RouteTable, SecurityPolicy, OperationalDatasetComponent and ActiveNetworkFaults)
- Tally Overruns when sendPacket fails due to lack of memory space.
- ResetCounts command now only resets OverrunCount as specified in the matter spec. ** I still wonder why would we not also reset MAC, MLE and ERR counters **
- Routing Role Attribute in matter does not map exactly what Role is returned my Thread. Validate the details and assign the right value.
- Channel attribute type is a uin16_t not uint8_t. Fix that in the xml.

#### Testing
- Build and run lighting-app on EFR32 thread device
- Use chip-tool to commission device and validate each attributes that changed
- Validate the output comparing with the ot-cli values
 
./chip-tool threadnetworkdiagnostics read channel 1245 0
./chip-tool threadnetworkdiagnostics read neighbor-table-list 1245 0
./chip-tool threadnetworkdiagnostics read routing-role 1245 0
./chip-tool threadnetworkdiagnostics read security-policy 1245 0
./chip-tool threadnetworkdiagnostics read operational-dataset-components 1245 0
./chip-tool threadnetworkdiagnostics read active-network-faults-list 1245 0

### CODE REVIEW

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 1]
```diff
@@ -793,10 +793,12 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::_GetExternalIPv6
 template <class ImplClass>
 void GenericThreadStackManagerImpl_OpenThread<ImplClass>::_ResetThreadNetworkDiagnosticsCounts(void)
 {
+    // Based on the spec, only OverrunCount should be resetted.
+    mOverrunCount = 0;
     // Reset MAC counters
-    otLinkResetCounters(mOTInst);
-    otThreadResetMleCounters(mOTInst);
-    otThreadResetIp6Counters(mOTInst);
+    // otLinkResetCounters(mOTInst);
```
Comment (Damian-Nordic) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:799]: Remove commented code?

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 2]
```diff
@@ -1221,16 +1314,24 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::_WriteThreadNetw
...
-        //     otOperationalDataset activeDataset;
-        //     otError otErr = otDatasetGetActive(mOTInst, &activeDataset);
-        //     VerifyOrExit(otErr == OT_ERROR_NONE, err = MapOpenThreadError(otErr));
-        //     activeDataset.mSecurityPolicy
-        // }
+        if (otDatasetIsCommissioned(mOTInst))
+        {
+            otOperationalDataset activeDataset;
+            otError otErr = otDatasetGetActive(mOTInst, &activeDataset);
+            VerifyOrExit(otErr == OT_ERROR_NONE, err = MapOpenThreadError(otErr));
```
Comment (Damian-Nordic) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:1323]: In some places you use `VerifyOrExit` macro and in others - `ReturnErrorOnFailure`. Is that intentional?

**Review by Damian-Nordic — APPROVED** [review]

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp (hunk 1 above)
Comment (jmartinez-silabs) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:799]: Sure will do

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp (hunk 2 above)
Comment (jmartinez-silabs) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:1323]: Yes it was intentional, VerifyOrExit is used in the "general" function as it knows the exit: label. However in the lambda function given to EncodeList it doesn't, I still stop and return the error if there is one in it.

**Review by rcasallas-silabs — APPROVED** [review]

**Review by jepenven-silabs — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 3]
```diff
@@ -1258,27 +1355,46 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::_WriteThreadNetw
...
-        err = CHIP_ERROR_NOT_IMPLEMENTED;
+        err = CHIP_ERROR_INCORRECT_STATE;
+        if (otDatasetIsCommissioned(mOTInst))
+        {
+            otOperationalDataset activeDataset;
+            otError otErr = otDatasetGetActive(mOTInst, &activeDataset);
+            VerifyOrExit(otErr == OT_ERROR_NONE, err = MapOpenThreadError(otErr));
+            ThreadNetworkDiagnostics::Structs::OperationalDatasetComponents::Type OpDatasetComponents;
+
+            OpDatasetComponents.activeTimestampPresent  = activeDataset.mComponents.mIsActiveTimestampPresent;
```
Comment (jmeg-sfy) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:1366]: can't we have an easier way to do this field copy ? OpDatasetComponents  = mComponents

Comment (jmartinez-silabs) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:1366]: Structure do not allign. For example, bit assigned to a boolean variable(8bit). Can't do as you suggest

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 4]
```diff
@@ -861,41 +895,96 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::_WriteThreadNetw
...
+            return chipErr;
+
+#else // OPENTHREAD_MTD
+            otError otErr = otThreadGetParentInfo(mOTInst, &routerInfo);
+            ReturnErrorOnFailure(MapOpenThreadError(otErr));
+
+            ThreadNetworkDiagnostics::Structs::RouteTable::Type routeTable;
+
+            routeTable.extAddress      = Encoding::BigEndian::Get64(routerInfo.mExtAddress.m8);
+            routeTable.rloc16          = routerInfo.mRloc16;
```
Comment (jmeg-sfy) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:974]: same pattern as 20 lines over...

**Review by jmeg-sfy — APPROVED** [review]

**Comment by jmeg-sfy** [comment]
Thanks for the fix !

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp (hunk 3 above)
Comment (jmeg-sfy) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:1366]: Well understood it was just a nit !

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp (hunk 4 above)
Comment (jmartinez-silabs) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:974]: This part of the code is #if def to use one api for FTD and another for MTD. In the end we fill the same info to the matter structure in the first case for all router on the seen on the networkd, and on the second case only for the parent node. Not not reapeat the assignment twice I would have to use a more intrincate #ifdef pattern to ignore the for loop for the seconde case. I opted to just repeat the pattern as it is more readable and, based on the define, only one path is built so it has no code size impact.


Also Thread structure and the matter structure don't allign memory wise so I have to assign each variables manually.

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp [hunk 5]
```diff
@@ -826,8 +824,44 @@ CHIP_ERROR GenericThreadStackManagerImpl_OpenThread<ImplClass>::_WriteThreadNetw
...
+        }
+        else if (otRole == OT_DEVICE_ROLE_LEADER)
+        {
+            routingRole = EMBER_ZCL_ROUTING_ROLE_LEADER;
+        }
+        else if (otRole == OT_DEVICE_ROLE_CHILD)
+        {
+            otLinkModeConfig linkMode = otThreadGetLinkMode(mOTInst);
+
+            if (linkMode.mNetworkData)
```
Comment (LuDuda) [inline src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:850]: This is not correct since Network Data bit only indicates that device requires the Full Network Data.

You can use `otThreadIsRouterEligible` API to check if the device is Router Eligible (REED) and if not, then use `mRxOnWhenIdle` bit.

**Review by LuDuda — CHANGES_REQUESTED** [review]

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp (hunk 5 above)
Comment (jmartinez-silabs) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:850]: But only the REED requires Full network Data. Else you are already a Router or a Leader.
So if your roule is Child and mNetworkData=1 you are a REED

```
Full Thread Device (FTD) Router
otDeviceRole=OT_DEVICE_ROLE_ROUTER
mRxOnWhenIdle=1
mDeviceType=1
mNetworkData=1

Full Thread Device (FTD) REED
otDeviceRole=OT_DEVICE_ROLE_CHILD
mRxOnWhenIdle=1
mDeviceType=1
mNetworkData=1

Full Thread End Device (FED)
otDeviceRole=OT_DEVICE_ROLE_CHILD
mRxOnWhenIdle=1
mDeviceType=1
mNetworkData=0

Minimal Thread End Device:
otDeviceRole=OT_DEVICE_ROLE_CHILD
mRxOnWhenIdle=1
mDeviceType=0
mNetworkData=0

Sleepy End Device:
otDeviceRole=OT_DEVICE_ROLE_CHILD
mRxOnWhenIdle=0
mDeviceType=0
mNetworkData=0
```

Comment (LuDuda) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp:850]: It is true that REED must set this flag to '1', but regular FED, MED or even SED can also set it to 1 in practice, so this bit does not indicate if you are a REED or not.

**Review by LuDuda — APPROVED** [review]
Thank you for doing this! Looks great :+1:

File: src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp (hunk 5 above)
Comment (jmartinez-silabs) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp]: `otThreadIsRouterEligible` isn't available on MTD devices. It is causing a build failure on those.

Comment (jmartinez-silabs) [reply src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp]: Ok re-arranged the logic to take that into consideration.
So The device can only be a REED if `linkMode.mRxOnWhenIdle` is true, `CHIP_DEVICE_CONFIG_THREAD_FTD` is set  and the device is `otThreadIsRouterEligible`

This is correct from both the issue you raised and MTD not having that API. MTD can't be REED anyway.
