### PR TITLE
[Linux] Mark GLib source as removed when exiting callback

### LINKED ISSUE #22840: [Platform][Linux] g_source_remove() is used on already removed source ID
### Reproduction steps

```bash
1. Start `chip-lighting-app --ble-device 0` on one device
2. Run `chip-tool pairing ble-wifi 0x01 WIFI PASSW 20202021 3840` on other device which does not support all required BLE features (on lighting-app device, in Wireshark `bthci_evt.le_features` is all zero)
3. lighting-app will print:


[1663922441.124142][1652598:1652616] CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
[1663922441.124182][1652598:1652616] CHIP:DL: FAIL: short read in BluezCharacteristicWriteFD (0)     <- source callback will return FALSE
[1663922441.222954][1652598:1652616] CHIP:DL: CHIPoBLE subscribe received
[1663922441.223036][1652598:1652598] CHIP:BLE: no endpoint for sub recvd
[1663922441.223061][1652598:1652598] CHIP:DL: HandlePlatformSpecificBLEEvent 32775
[1663922441.223076][1652598:1652598] CHIP:DL: Receive kCHIPoBLEConnectionEstablished
[1663922458.174623][1652598:1652616] CHIP:DL: Bluez disconnected
[1663922458.174675][1652598:1652616] CHIP:DL: Bluez notify CHIPoBluez connection disconnected

(process:1652598): GLib-CRITICAL **: 10:40:58.174: Source ID 40 was not found when attempting to remove it       <- calling g_source_remove() on removed source
```
```


### Platform

other

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

No automatic test case for such scenario.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by arkq**
#### Issue Being Resolved
* Fixes #22840

#### Change overview
* Mark GLib source as removed when exiting callback function with FALSE.

### CODE REVIEW

File: src/platform/Linux/bluez/Helper.cpp [hunk 1]
```diff
@@ -377,8 +377,7 @@ static gboolean BluezCharacteristicWriteFD(GIOChannel * aChannel, GIOCondition a
     bool isSuccess = false;
 
     BluezConnection * conn = static_cast<BluezConnection *>(apEndpoint);
-
-    VerifyOrExit(conn != nullptr, ChipLogError(DeviceLayer, "No CHIP Bluez connection in %s", __func__));
+    VerifyOrReturnError(conn != nullptr, (ChipLogError(DeviceLayer, "No CHIP Bluez connection in %s", __func__), FALSE));
```
Comment (andy31415) [inline src/platform/Linux/bluez/Helper.cpp:380]: I believe we should not be combining `verifyOrExit` with `VerifyOrReturn` macros.

The idea behind the `goto exit` patten is to ensure that there is a single exit point for things. If we use both macros, that assumption does not hold and is difficuld to keep reasoning about as time goes on. Even though current code is correct, it starts becomming harder to maintain.

I would keep the old code and maybe:

```cpp
if (!isSuccess && (conn != nullptr)) {
   // ... explain ...
   conn->mC1Channel.mWatch = 0;
}
return isSuccess;
```

File: src/platform/Linux/bluez/Helper.cpp [hunk 2]
```diff
@@ -401,7 +400,17 @@ static gboolean BluezCharacteristicWriteFD(GIOChannel * aChannel, GIOCondition a
...
 
 exit:
-    return isSuccess ? TRUE : FALSE;
+    if (!isSuccess)
+    {
+        // Returning FALSE from the source callback removes the source object
+        // from the context. In order not to trigger GLib critical warning when
+        // manually removing the source in BluezOTConnectionDestroy() mark it
+        // as no longer active.
+        conn->mC1Channel.mWatch = 0;
```
Comment (andy31415) [inline src/platform/Linux/bluez/Helper.cpp:409]: Is there some documentation of what mC1Channel/mWatch is? 
Why is setting this mWatch value to 0 a valid way of 'mark it no longer active'?

Comment (andy31415) [reply src/platform/Linux/bluez/Helper.cpp:409]: I see mC1Channel.mWatch being a `conn->mC1Channel.mWatch    = g_io_add_watch(channel,....)`

I am not familiar with watches and documentation seems kind of sparse, but it looks like the logic is described as you add a watch which increases a channel reference count and then you can use g_io_channel_unref to decrease it (is this true?). If so, just setting mWatch to 0 seems to leak things right? or is this an initialization error?

I think this probably needs a bit more explaining. Maybe we just need initializers in struct IOChannel ... mpChannel should start as nullptr and mWatch should start with 0.

Comment (Arkq) [reply src/platform/Linux/bluez/Helper.cpp:409]: > I am not familiar with watches and documentation seems kind of sparse

Yes, documentation lacks a lot of things regarding proper handing of watches and callback functions. But it works that way that the `g_io_add_watch()` creates source watch and registers it within the main context, then it returns unique ID greater than zero (see documentation for `g_source_attach`). And here we've got a hard-to-maintain behavior when the callback function returns FALSE. In that case source removes itself from the context (see doc for `GSourceFunc`), so it's not valid any more to call `g_source_remove()`. 

> add a watch which increases a channel reference count and then you can use g_io_channel_unref to decrease it (is this true?)

The issue is not with `g_io_create_watch()` (this one increments ref count of channel) but with `g_source_attach()` (this one returns ID) and `g_source_set_callback()`.

Maybe it will be easier to maintain this whole thing if we will use `g_io_create_watch()` and `g_source_attach()` directly (without using `g_io_add_watch()` wrapper). I will have to check that, but as far as I remember there is always the same issue with callback unregistering itself. Here the situation is easier because the `g_source_remove` is called from main context as well, but in other circumstances we would need mutex to guard `mC1Channel.mWatch`.

File: src/platform/Linux/bluez/Helper.cpp (hunk 1 above)
Comment (Arkq) [reply src/platform/Linux/bluez/Helper.cpp:380]: I was not sure which approach would be better. But I agree with you that maybe single return point is better in that case.

File: src/platform/Linux/bluez/Helper.cpp (hunk 2 above)
Comment (Arkq) [reply src/platform/Linux/bluez/Helper.cpp:410]: I think that setting source ID tag to zero inside the callback is correct. Event the GLib documentation has got an example exactly like that: https://www.freedesktop.org/software/gstreamer-sdk/data/docs/latest/glib/glib-The-Main-Event-Loop.html#g-source-is-destroyed The only difference is that here we are calling callback and g_source_remove within the same GLib thread - so there is no need for mutex.

Comment (andy31415) [reply src/platform/Linux/bluez/Helper.cpp:410]: The example you posted seems to be an example for 'this will fail, do this instead'.

Comment (andy31415) [reply src/platform/Linux/bluez/Helper.cpp:410]: Would a:

```
if (g_source_is_destroyed(g_main_current_source())) {
  return;
}
```

as in the example fix things or does that not work?

File: src/platform/Linux/bluez/Helper.cpp [hunk 3]
```diff
@@ -417,6 +426,8 @@ static void Bluez_gatt_characteristic1_complete_acquire_write_with_fd(GDBusMetho
 
 static gboolean bluezCharacteristicDestroyFD(GIOChannel * aChannel, GIOCondition aCond, gpointer apClosure)
 {
+    BluezConnection * conn  = static_cast<BluezConnection *>(apClosure);
+    conn->mC2Channel.mWatch = 0;
```
Comment (andy31415) [inline src/platform/Linux/bluez/Helper.cpp:430]: Looks like a similar comment is useful here: why are we setting mWatch to 0?

**Review by andy31415 — APPROVED** [review]
Adding checkmark, but please add some TODO at least to also investigate behavior if we need to set mWatch = 0. I am very unclear what "add watch" actually does and it feels somehow like a handle that we can leak/lose here.

File: src/platform/Linux/bluez/Helper.cpp (hunk 2 above)
Comment (Arkq) [reply src/platform/Linux/bluez/Helper.cpp:410]: Maybe you are right that such approach will be better (to add `g_source_is_destroyed(g_main_current_source()` to the callback as well). However, this example is for multi-threaded GTK case. In such case it might happen that someone will destry the widget (`SomeWidget *self`) by calling `some_widget_finalize()` on one thread and in the same time the callback will be called on some other thread - "This will fail in a multi-threaded application if the **widget is destroyed** before the idle handler fires". But this PR is for some other thing - when the `g_source_remove()` is called on already destroyed source. In that case we still need to know whether the source tag ID is valid or not. I think that this example is somehow misleading, because in the "fixed" version the callback always returns `FALSE` (which equals to `G_SOURCE_REMOVE`), however, in the callback there is no `self->idle_id = 0;`, which IMHO should still be there.

File: src/platform/Linux/bluez/Helper.cpp (hunk 3 above)
Comment (Arkq) [reply src/platform/Linux/bluez/Helper.cpp:432]: Added the same commend as for `conn->mC1Channel.mWatch = 0`.
