### PR TITLE
Fix SoftwareFault and GeneralFault events are missed randomly

### LINKED ISSUE #19242: Refactor new diagnostic APIs from Server into  cluster server
#### Problem
 We need to remove new diagnostic APIs(general, software) from Server, this is not where they belong, they belong in the cluster server

 #### Proposed Solution
<suggested fix, suggested enhancement>

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
What is being fixed?  Examples:
* The SoftwareFault and GeneralFault events were not able to get generated sometimes,  the root cause is we we use different signals to indicate those events occur in Linux simulation,  and we register the signal handler both at app layer and platform layer. We need to consolidate those signal handlers into one place to avoid conflict.

Fixes https://github.com/project-chip/connectedhomeip/issues/19242

#### Change overview
Move SoftwareFault and GeneralFault signal handler from platform layer to app layer

Please note, this PR only contains the changes for general and software diagnostic clusters. 

1. For using pipe instead of signals to trigger those faults (https://github.com/project-chip/connectedhomeip/issues/19114)
2. For switch cluster event refactor (https://github.com/project-chip/connectedhomeip/issues/19007)

#### Testing
How was this tested? (at least one bullet point required)
* 1. Start the chip-all-clusters-app example app
`yufengwang@yufengwang:~/connectedhomeip/out/debug/standalone$ ./chip-all-clusters-app `

* 2. Send the signal to the example app
```
yufengwang@yufengwang:~$ ps -A | grep chip
1563025 pts/4    00:00:00 chip-all-cluste
yufengwang@yufengwang:~$ 
yufengwang@yufengwang:~$ kill -SIGUSR1 1563025
```
 
* 3. Confrim the related event are generated from the example app event
```
......
[1654104193.959661][1563025:1563025] CHIP:ZCL: SoftwareDiagnosticsDelegate: OnSoftwareFaultDetected
[1654104193.959715][1563025:1563025] CHIP:EVL: LogEvent event number: 0x0000000000000002 priority: 1, endpoint id:  0x0 cluster id: 0x0000_0034 event id: 0x0 Sys timestamp: 0x000000002870BDB7

```

### CODE REVIEW

File: src/app/server/Server.cpp [hunk 1]
```diff
@@ -333,6 +333,26 @@ void Server::DispatchShutDownAndStopEventLoop()
     PlatformMgr().ScheduleWork(StopEventLoop);
 }
 
+void Server::DispatchSoftwareFaultEvent(uint32_t eventId)
```
Comment (bzbarsky-apple) [inline src/app/server/Server.cpp:336]: Why does this make sense as a general API on Server?

File: src/app/server/Server.cpp [hunk 2]
```diff
@@ -333,6 +333,26 @@ void Server::DispatchShutDownAndStopEventLoop()
...
+{
+    PlatformMgr().ScheduleWork(
+        [](intptr_t context) {
+            uint32_t event = static_cast<uint32_t>(context);
+            PlatformMgr().HandleSoftwareFault(event);
+        },
+        static_cast<intptr_t>(eventId));
+}
+
+void Server::DispatchGeneralFaultEvent(uint32_t eventId)
```
Comment (bzbarsky-apple) [inline src/app/server/Server.cpp:346]: Likewise, why does this make sense as a general API on Server?

File: src/app/server/Server.h [hunk 3]
```diff
@@ -254,6 +254,16 @@ class Server
      */
     void DispatchShutDownAndStopEventLoop();
 
+    /**
+     * This function generate the SoftwareFault Event when a software fault takes place on the Node.
+     */
+    void DispatchSoftwareFaultEvent(uint32_t eventId);
```
Comment (bzbarsky-apple) [inline src/app/server/Server.h:260]: What is "eventId" here?

File: src/app/server/Server.h [hunk 4]
```diff
@@ -254,6 +254,16 @@ class Server
...
+
+    /**
+     * This function generate the GeneralFault Event when a general fault takes place on the Node.
+     */
+    void DispatchGeneralFaultEvent(uint32_t eventId);
```
Comment (bzbarsky-apple) [inline src/app/server/Server.h:265]: What is eventId?

File: src/include/platform/internal/GenericPlatformManagerImpl.h [hunk 5]
```diff
@@ -57,6 +57,8 @@ class GenericPlatformManagerImpl
     void _RemoveEventHandler(PlatformManager::EventHandlerFunct handler, intptr_t arg);
     void _HandleServerStarted();
     void _HandleServerShuttingDown();
+    void _HandleSoftwareFault(uint32_t eventId);
```
Comment (bzbarsky-apple) [inline src/include/platform/internal/GenericPlatformManagerImpl.h:60]: Why do we need this API on platform manager?

If we're just trying to queue IM events, shouldn't we have public APIs for that that applications can use without having to go through Server _and_ platform manager?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: examples/platform/linux/AppMain.cpp [hunk 6]
```diff
@@ -128,30 +128,46 @@ void OnSignalHandler(int signum)
...
+        Server::GetInstance().DispatchSoftwareFaultEvent(SoftwareDiagnostics::Events::SoftwareFault::Id);
+        break;
+    case SIGUSR2:
+        Server::GetInstance().DispatchGeneralFaultEvent(GeneralDiagnostics::Events::HardwareFaultChange::Id);
+        break;
+    case SIGHUP:
+        Server::GetInstance().DispatchGeneralFaultEvent(GeneralDiagnostics::Events::RadioFaultChange::Id);
+        break;
+    case SIGTTIN:
+        Server::GetInstance().DispatchGeneralFaultEvent(GeneralDiagnostics::Events::NetworkFaultChange::Id);
```
Comment (tcarmelveilleux) [inline examples/platform/linux/AppMain.cpp:163]: Please move all fault handling event management *away from signals* and add APIs to Software/General Diagnostics cluster server to trigger logging of said events. We could use a named pipe on Linux to allow receiving single-byte requests for fault events.

**Review by tcarmelveilleux — CHANGES_REQUESTED** [review]
- [ ] Remove new APIs from `Server`, this is not where they belong, they belong in the cluster server
- [ ] Stop using signals for those faults, altogether, and move to a different notification means, like a pipe

File: src/app/server/Server.cpp (hunk 1 above)
Comment (yufengwangca) [reply src/app/server/Server.cpp:336]: Just to align with existing implementation such as void DispatchShutDownAndStopEventLoop(), we can move these APIs to cluster server if it make more sense.

File: src/include/platform/internal/GenericPlatformManagerImpl.h (hunk 5 above)
Comment (yufengwangca) [reply src/include/platform/internal/GenericPlatformManagerImpl.h:60]: That is the legacy design and we can move everything to related cluster server

File: examples/platform/linux/AppMain.cpp (hunk 6 above)
Comment (yufengwangca) [reply examples/platform/linux/AppMain.cpp:163]: I will proceed to refactor to implement the event handling APIs in cluster server in this PR. https://github.com/project-chip/connectedhomeip/issues/19114 is created to use pipe instead of signal to trigger the event, need to sync with CSG to update the test plans

File: src/app/server/Server.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply src/app/server/Server.cpp:336]: These APIs shouldn't really exist.  We should have event dispatch APIs, but not these random "happens to call into some random platform manager special case we added for a particular event" APIs....

File: src/app/server/Server.h (hunk 3 above)
Comment (bzbarsky-apple) [reply src/app/server/Server.h:260]: My point is that this needs to be documented.  Is this an EventId?  Or an actual uint32_t?  If the latter, how does it get interpreted?

File: examples/platform/linux/AppMain.cpp [hunk 7]
```diff
@@ -165,6 +181,11 @@ void SetupSignalHandlers()
     signal(SIGTERM, OnSignalHandler);
     signal(SIGIO, OnSignalHandler);
     signal(SIGINT, OnSignalHandler);
+
+    signal(SIGUSR1, OnSignalHandler);
+    signal(SIGUSR2, OnSignalHandler);
+    signal(SIGHUP, OnSignalHandler);
+    signal(SIGTTIN, OnSignalHandler);
```
Comment (msandstedt) [inline examples/platform/linux/AppMain.cpp:188]: Thanks for moving this out of the platform layer and into the app.

It was very unkind for the sdk to be using signals in the platform layer, as that's not really an acceptable thing for the sdk to do when it is being linked to an existing application as a library.

File: src/app/server/Server.h (hunk 3 above)
Comment (yufengwangca) [reply src/app/server/Server.h]: moved to cluster server

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 8]
```diff
@@ -202,126 +211,138 @@ CHIP_ERROR GeneralDiagosticsAttrAccess::Read(const ConcreteReadAttributePath & a
...
     {
-        ChipLogDetail(Zcl, "GeneralDiagnosticsDelegate: OnHardwareFaultsDetected");
+        // If General Diagnostics cluster is implemented on this endpoint
+        MatterReportingAttributeChangeCallback(endpointId, GeneralDiagnostics::Id,
+                                               GeneralDiagnostics::Attributes::ActiveHardwareFaults::Id);
+
+        // Record HardwareFault event
+        EventNumber eventNumber;
+        DataModel::List<const HardwareFaultType> currentList =
+            DataModel::List<const HardwareFaultType>(reinterpret_cast<const HardwareFaultType *>(current.data()), current.size());
```
Comment (bzbarsky-apple) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:278]:
```suggestion
        DataModel::List<const HardwareFaultType> currentList(reinterpret_cast<const HardwareFaultType *>(current.data()), current.size());
```
Or use `auto`.  Yes, I know this was pre-existing....

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 9]
```diff
@@ -202,126 +211,138 @@ CHIP_ERROR GeneralDiagosticsAttrAccess::Read(const ConcreteReadAttributePath & a
...
+        DataModel::List<const HardwareFaultType> previousList =
+            DataModel::List<const HardwareFaultType>(reinterpret_cast<const HardwareFaultType *>(previous.data()), previous.size());
```
Comment (bzbarsky-apple) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:280]:
```suggestion
        DataModel::List<const HardwareFaultType> previousList(reinterpret_cast<const HardwareFaultType *>(previous.data()), previous.size());
```

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 10]
```diff
@@ -202,126 +211,138 @@ CHIP_ERROR GeneralDiagosticsAttrAccess::Read(const ConcreteReadAttributePath & a
...
     {
-        ChipLogDetail(Zcl, "GeneralDiagnosticsDelegate: OnRadioFaultsDetected");
+        // If General Diagnostics cluster is implemented on this endpoint
+        MatterReportingAttributeChangeCallback(endpointId, GeneralDiagnostics::Id,
+                                               GeneralDiagnostics::Attributes::ActiveRadioFaults::Id);
 
-        for (auto endpointId : EnabledEndpointsWithServerCluster(GeneralDiagnostics::Id))
+        // Record RadioFault event
+        EventNumber eventNumber;
+        DataModel::List<const RadioFaultType> currentList =
```
Comment (bzbarsky-apple) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:303]: Again, please remove the verbose type duplication here.

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.h [hunk 11]
```diff
@@ -0,0 +1,74 @@
...
+     *   Called after the current device is rebooted.
+     */
+    void OnDeviceReboot(BootReasonType bootReason);
+
+    /**
+     * @brief
+     *   Called when the Node detects a hardware fault has been raised.
+     */
+    void OnHardwareFaultsDetect(DeviceLayer::GeneralFaults<DeviceLayer::kMaxHardwareFaults> & previous,
+                                DeviceLayer::GeneralFaults<DeviceLayer::kMaxHardwareFaults> & current);
```
Comment (bzbarsky-apple) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.h:51]: Why are these non-const references?  Same for the other APIs here.

File: src/app/clusters/software-diagnostics-server/software-diagnostics-server.h [hunk 12]
```diff
@@ -0,0 +1,52 @@
...
+class Server
+{
+public:
+    static Server & Instance();
+
+    /**
+     * @brief
+     *   Called when a software fault that has taken place on the Node.
+     */
+    void OnSoftwareFaultDetect(chip::app::Clusters::SoftwareDiagnostics::Structs::SoftwareFaultStruct::Type & softwareFault);
```
Comment (bzbarsky-apple) [inline src/app/clusters/software-diagnostics-server/software-diagnostics-server.h:43]: Why is this a non-const reference?

**Review by bzbarsky-apple — APPROVED** [review]

File: examples/all-clusters-app/linux/main-common.cpp [hunk 13]
```diff
@@ -41,6 +44,200 @@ using namespace chip::DeviceLayer;
...
+void HandleSoftwareFaultEvent(intptr_t arg)
+{
+    if (!EnabledWithServerCluster(Clusters::SoftwareDiagnostics::Id))
+        return;
+
+    Clusters::SoftwareDiagnostics::Structs::SoftwareFaultStruct::Type softwareFault;
+    char threadName[kMaxThreadNameLength + 1];
+
+    softwareFault.id = static_cast<uint64_t>(gettid());
+    Platform::CopyString(threadName, kMaxThreadNameLength + 1, std::to_string(softwareFault.id).c_str());
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/linux/main-common.cpp:73]:
```suggestion
    Platform::CopyString(threadName, std::to_string(softwareFault.id).c_str());
```

File: examples/all-clusters-app/linux/main-common.cpp [hunk 14]
```diff
@@ -41,6 +44,200 @@ using namespace chip::DeviceLayer;
...
+
+    softwareFault.name           = CharSpan::fromCharString(threadName);
+    softwareFault.faultRecording = ByteSpan(Uint8::from_const_char(threadName), strlen(threadName));
```
Comment (bzbarsky-apple) [inline examples/all-clusters-app/linux/main-common.cpp:76]: Again, the problem is that this going to make people think the faultRecording needs to match the name...

File: examples/all-clusters-app/linux/main-common.cpp [hunk 15]
```diff
@@ -41,6 +44,203 @@ using namespace chip::DeviceLayer;
...
+{
+    // sigaction is not used here because Tsan interceptors seems to
+    // never dispatch the signals on darwin.
+    signal(SIGALRM, OnRebootSignalHandler);
+    signal(SIGVTALRM, OnRebootSignalHandler);
+    signal(SIGILL, OnRebootSignalHandler);
+    signal(SIGTRAP, OnRebootSignalHandler);
+    signal(SIGTERM, OnRebootSignalHandler);
+    signal(SIGIO, OnRebootSignalHandler);
+    signal(SIGINT, OnRebootSignalHandler);
```
Comment (tcarmelveilleux) [inline examples/all-clusters-app/linux/main-common.cpp:236]: Please do not override SIGINT

File: examples/all-clusters-app/linux/main-common.cpp [hunk 16]
```diff
@@ -41,6 +44,203 @@ using namespace chip::DeviceLayer;
 
 namespace {
 static LowPowerManager lowPowerManager;
+
+bool EnabledWithServerCluster(ClusterId clusterId)
```
[the remark this answers is not in the document]
Comment (yufengwangca) [reply examples/all-clusters-app/linux/main-common.cpp:48]: We shall not log the event if the cluster is not enabled on any endpoint.

File: examples/all-clusters-app/linux/main-common.cpp (hunk 15 above)
Comment (yufengwangca) [reply examples/all-clusters-app/linux/main-common.cpp:236]: replace with SIGSTP temperately, and this whole mechanism will be replaced by pipe

File: examples/all-clusters-app/linux/main-common.cpp (hunk 16 above)
[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply examples/all-clusters-app/linux/main-common.cpp:48]: `IsClusterPresentOnAnyEndpoint(ClusterId clusterId)` is a better name. Can do in follow-up

**Review by tcarmelveilleux — APPROVED** [review]

File: examples/all-clusters-app/linux/main-common.cpp (hunk 16 above)
[the remark this answers is not in the document]
Comment (yufengwangca) [reply examples/all-clusters-app/linux/main-common.cpp]: changed to IsClusterPresentOnAnyEndpoint
