### PR TITLE
[BL602] Fix sve2 problems

### LINKED ISSUE #22616: [Platform] BL602 fixes networkcommission and network diagnosis info.
### Reproduction steps

```bash
1.test case:TC-CNET-4.1
```

### Platform

other

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jczhang777**
#### Issue Being Resolved
* Increase pbuf num
* fix memory leak
* reduce app task stack size
* Fix Diagnostic info
* Fxi wifi for update network
* Update readme

fixes #22616

#### Change overview
* Increase pbuf num, fix memory leak, reduce app task stack size, fix Diagnostic info, fix wifi for update network, update readme.

### CODE REVIEW

**Comment by andy31415** [comment]
@jczhang777  please add and link an issue for this. The template explicitly asks for a text of the form `fixes #.....` to link the issue (other text can be used - see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) however an issue is currently mandatory for PRs in ToT

File: src/platform/bouffalolab/BL602/DiagnosticDataProviderImpl.cpp [hunk 1]
```diff
@@ -163,11 +163,33 @@ CHIP_ERROR DiagnosticDataProviderImpl::GetBootReason(BootReasonType & bootReason
...
+    {
+        return 0;
+    }
+
+    int addr_count = 0;
+    for (int i = 0; i < LWIP_IPV6_NUM_ADDRESSES; i++)
+    {
+        if (!ip_addr_cmp(&netif->ip6_addr[i], IP6_ADDR_ANY))
+        {
+            memcpy(&if_ip6[addr_count++], &netif->ip6_addr[i], sizeof(ip6_addr_t));
```
Comment (andy31415) [inline src/platform/bouffalolab/BL602/DiagnosticDataProviderImpl.cpp:178]: how do you ensure that if_ip6 has sufficient space for addr_count ?

I think the size of input arrays should be passed in to methods. Currently nothing seems to guarantee that kMaxIPv6AddrCount >= LWIP_IPV6_NUM_ADDRESSES

File: src/platform/bouffalolab/BL602/DiagnosticDataProviderImpl.cpp [hunk 2]
```diff
@@ -163,11 +163,33 @@ CHIP_ERROR DiagnosticDataProviderImpl::GetBootReason(BootReasonType & bootReason
...
+}
+
 CHIP_ERROR DiagnosticDataProviderImpl::GetNetworkInterfaces(NetworkInterface ** netifpp)
 {
     NetworkInterface * ifp = new NetworkInterface();
     struct netif * netif;
     uint8_t mac_addr[6];
+    uint32_t ip, gw, mask;
+    ip6_addr_t ip6_addr[kMaxIPv6AddrCount];
+    uint8_t ipv6_addr_count = 0;
```
Comment (andy31415) [inline src/platform/bouffalolab/BL602/DiagnosticDataProviderImpl.cpp:192]: this is C++ - you can declare variables where they are used instead of at the top of the function, to make code easier to read.

File: src/platform/bouffalolab/BL602/DiagnosticDataProviderImpl.cpp [hunk 3]
```diff
@@ -179,10 +201,24 @@ CHIP_ERROR DiagnosticDataProviderImpl::GetNetworkInterfaces(NetworkInterface **
         ifp->type                                          = EMBER_ZCL_INTERFACE_TYPE_WI_FI;
         ifp->offPremiseServicesReachableIPv4.SetNull();
         ifp->offPremiseServicesReachableIPv6.SetNull();
-        bl_efuse_read_mac(mac_addr);
-        memcpy(ifp->MacAddress, mac_addr, sizeof(mac_addr));
+        bl_efuse_read_mac(ifp->MacAddress);
+        ifp->hardwareAddress = ByteSpan(ifp->MacAddress, 6);
+
+        wifi_mgmr_sta_ip_get(&ip, &gw, &mask);
```
Comment (andy31415) [inline src/platform/bouffalolab/BL602/DiagnosticDataProviderImpl.cpp:207]: do these methods never fail? Like is there always an ip/gw/mask?

File: src/platform/bouffalolab/BL602/NetworkCommissioningDriver.cpp [hunk 4]
```diff
@@ -157,12 +165,18 @@ CHIP_ERROR BLWiFiDriver::ConnectWiFiNetwork(const char * ssid, uint8_t ssidLen,
 
     char wifi_ssid[64] = { 0 };
     char passwd[64]    = { 0 };
+
     // Set the wifi configuration
+    wifi_mgmr_sta_disconnect();
+    vTaskDelay(500);
```
Comment (andy31415) [inline src/platform/bouffalolab/BL602/NetworkCommissioningDriver.cpp:171]: 500 ticks here is a bit unclear  since it depends on portTICK_PERIOD_MS.
Could you add an explicit in-ms delay instead of something that varies based on OS tick rate?

Why is 500 a correct value to use?

File: src/platform/bouffalolab/BL602/NetworkCommissioningDriver.cpp [hunk 5]
```diff
@@ -157,12 +165,18 @@ CHIP_ERROR BLWiFiDriver::ConnectWiFiNetwork(const char * ssid, uint8_t ssidLen,
...
+    wifi_mgmr_sta_disable(NULL);
+    vTaskDelay(500);
+
     memcpy(wifi_ssid, ssid, ssidLen);
     memcpy(passwd, key, keyLen);
     wifi_interface_t wifi_interface;
     wifi_interface = wifi_mgmr_sta_enable();
-    wifi_mgmr_sta_connect(wifi_interface, ssid, passwd, NULL, NULL, 0, 0);
+    wifi_mgmr_sta_connect(wifi_interface, wifi_ssid, passwd, NULL, NULL, 0, 0);
```
Comment (andy31415) [inline src/platform/bouffalolab/BL602/NetworkCommissioningDriver.cpp:179]: Do these methods return an error code we could check and log on failures?

**Comment by andy31415** [comment]
accepted for 1.0: platform fixes

File: src/platform/bouffalolab/BL602/NetworkCommissioningDriver.cpp (hunk 5 above)
Comment (andy31415) [reply src/platform/bouffalolab/BL602/NetworkCommissioningDriver.cpp:187]: These were marked resolved ... what was the resolution? I see no deltas.

An answer like "this never fails" or implementation change would make sense.

File: src/platform/bouffalolab/BL602/DiagnosticDataProviderImpl.cpp (hunk 1 above)
Comment (andy31415) [reply src/platform/bouffalolab/BL602/DiagnosticDataProviderImpl.cpp:178]: what guarantees that `if_ip6` has at least min(kMaxIPv6AddrCount, LWIP_IPV6_NUM_ADDRESSES) elements? 

The size of if_ip6 should be passed in to this method as an argument, not assumed.

File: src/platform/bouffalolab/BL602/NetworkCommissioningDriver.cpp (hunk 4 above)
Comment (andy31415) [reply src/platform/bouffalolab/BL602/NetworkCommissioningDriver.cpp]: How was this resolved?

**Review by andy31415 — CHANGES_REQUESTED** [review]
Changes requested: comments were marked `resolved` without any resolution it seems.

File: src/platform/bouffalolab/BL602/NetworkCommissioningDriver.cpp (hunk 4 above)
Comment (andy31415) [reply src/platform/bouffalolab/BL602/NetworkCommissioningDriver.cpp]: Was looking at an old version - this was indeed updated.

File: src/platform/bouffalolab/BL602/NetworkCommissioningDriver.cpp [hunk 6]
```diff
@@ -157,12 +167,24 @@ CHIP_ERROR BLWiFiDriver::ConnectWiFiNetwork(const char * ssid, uint8_t ssidLen,
...
+
+    wifi_mgmr_sta_disconnect();
+    vTaskDelay(WIFI_STA_DISCONNECT_DELAY);
+
+    wifi_mgmr_sta_disable(NULL);
+    wifi_mgmr_state_get(&state);
+    while (state != WIFI_STATE_IDLE)
+    {
+        wifi_mgmr_state_get(&state);
+        vTaskDelay(100);
```
Comment (andy31415) [inline src/platform/bouffalolab/BL602/NetworkCommissioningDriver.cpp:180]: what is the 100 here? why is it ok to use ticks which depend on tick rate instead of computing a standard time. At least a comment of why we do not care is appropriate.

**Comment by andy31415** [comment]
@jczhang777 if you mark comments resolved, please do a code change (which would make it obvious why resolved) or add a comment reply saying why no change is needed. I do not have API documentation for the SDK calls you use and you are the expert in the platform, so I am providing suggestions but if you say `not needed because...` that is ok.

Want to make sure things were considered.

**Comment by andy31415** [comment]
I am force-merging this due to 1.0 branch: this PR makes things better, it just seems to be missing some error condition handling and some slight style issues and inconsistencies. These can be made in a followup by the platform owner. As this is not core SDK, I will not block PR on them.

**Comment by andy31415** [comment]
@jczhang777 - followup for more fixes would be appreciated/recommented.
