### PR TITLE
[example] Linux Example App - Light

### LINKED ISSUE #1761: [Linux Platform Example] Virtual Devices - Light
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem
Currently, there is a chip-server in chip-tool acts as a lighting app for testing use comes with the initial PR with cirque tests, which is a bit hack, and unclean. Also we need a Lighting app for linux as a example, it is clear that merge the two app into one will be better.

#### Summary of Changes
1. Move old chip-server in chip-tools to lighting-app/linux
2. Refine chip-tools and update cirque test

#### Note
1. After #2367 is merged, there will be another PR (or rebase this one if not merged) to reduce the dublicate code between multiple platforms.

issue #2302
fix #1761

### CODE REVIEW

**Review by bukepo — APPROVED** [review]
LGTM:+1:

File: examples/chip-tool/main.cpp [hunk 1]
```diff
@@ -450,19 +460,13 @@ void DoOnOff(DeviceController::ChipDeviceController * controller, Command comman
...
-    auto start = std::chrono::system_clock::now();
-    while (waitingForResponse &&
-           std::chrono::duration_cast<std::chrono::minutes>(std::chrono::system_clock::now() - start) < kWaitingForResponseTimeout)
-    {
-        // Just poll for the response.
-        sleep(1);
-    }
 
-    if (waitingForResponse)
+    std::unique_lock<std::mutex> lk(cvWaitingForResponseMutex);
```
Comment (rwalker-apple) [inline examples/chip-tool/main.cpp:464]: @bzbarsky-apple will you have a look here?

File: examples/lighting-app/linux/BUILD.gn [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+    "${chip_root}/src/app/util/util.c",
+    "gen/call-command-handler.c",
+    "gen/callback-stub.c",
+    "gen/znet-bookkeeping.c",
+    "main.cpp",
+  ]
+
+  include_dirs = [
+    ".",
+    "${chip_root}/src/app/util",
```
Comment (rwalker-apple) [inline examples/lighting-app/linux/BUILD.gn:42]: would prefer that we used `#include <app/util/XXX.h` in source files and and have `-I${chip_root}/src` if possible.  if there's an issue with a file in `gen/` that makes this pattern untenable, lemme know

File: examples/chip-tool/main.cpp [hunk 3]
```diff
@@ -53,33 +55,37 @@
 using namespace ::chip;
 using namespace ::chip::Inet;
 
+namespace {
```
Comment (rwalker-apple) [inline examples/chip-tool/main.cpp:58]: thank you

**Comment by rwalker-apple** [comment]
> #### Problem
> #### Summary of Changes
> 1. Move old chip-server in chip-tools to lighting-app/linux
> 2. Refine chip-tools and update cirque test
> 
> issue #2302
> fix #1761


@erjiaqing can you please phrase a problem for this PR?

File: examples/chip-tool/main.cpp [hunk 4]
```diff
@@ -148,10 +154,11 @@ static void HandleDataModelMessage(System::PacketBuffer * buffer)
     System::PacketBuffer::Free(buffer);
 }
 
-static void OnMessage(DeviceController::ChipDeviceController * deviceController, void * appReqState, System::PacketBuffer * buffer)
+void OnMessage(DeviceController::ChipDeviceController * deviceController, void * appReqState, System::PacketBuffer * buffer)
 {
     size_t data_len    = buffer->DataLength();
     waitingForResponse = false;
```
Comment (mspang) [inline examples/chip-tool/main.cpp:160]: The thread must hold cvWaitingForResponseMutex for this store (and can remove the std::atomic since it won't be helpful here).

**Review by mspang — CHANGES_REQUESTED** [review]

File: examples/chip-tool/main.cpp [hunk 5]
```diff
@@ -183,9 +190,12 @@ static void OnError(DeviceController::ChipDeviceController * deviceController, v
                     const IPPacketInfo * pi)
 {
     waitingForResponse = false;
```
Comment (mspang) [inline examples/chip-tool/main.cpp:192]: Also need to hold the mutex during this store.

File: examples/chip-tool/main.cpp (hunk 1 above)
Comment (bzbarsky-apple) [reply examples/chip-tool/main.cpp:464]: This part looks fine to me, given that we set `waitingForResponse` to true before we call `SendMessage`, so even a sync callback under there will do the right thing.

File: examples/lighting-app/linux/BUILD.gn (hunk 2 above)
Comment (bzbarsky-apple) [reply examples/lighting-app/linux/BUILD.gn:42]: There are a bunch of includes in gen files of `af.h`, `af-types.h`, `util.h`.  More importantly, there are includes like that in the non-gen files too.  We could fix that by adding `${chip_root}/src` to the include path for all the apps involved, then changing the non-gen files, then changing the various gen files in the apps, then removing `${chip_root}/src/app/util` from the include paths...

I would argue for not trying to do that as part of this PR and doing a followup instead.

File: examples/chip-tool/main.cpp (hunk 4 above)
Comment (erjiaqing) [reply examples/chip-tool/main.cpp]: Done

**Review by mspang — APPROVED** [review]

**Review by rwalker-apple — APPROVED** [review]

**Comment by rwalker-apple** [comment]
@saurabhst @hawk248 @jelderton ?

File: examples/chip-tool/main.cpp [hunk 6]
```diff
@@ -156,9 +157,12 @@ void HandleDataModelMessage(System::PacketBuffer * buffer)
...
 void OnMessage(DeviceController::ChipDeviceController * deviceController, void * appReqState, System::PacketBuffer * buffer)
 {
-    size_t data_len    = buffer->DataLength();
-    waitingForResponse = false;
-    cvWaitingForResponse.notify_all();
+    size_t data_len = buffer->DataLength();
+    {
+        std::lock_guard<std::mutex> lk(cvWaitingForResponseMutex);
+        waitingForResponse = false;
+        cvWaitingForResponse.notify_all();
```
Comment (bzbarsky-apple) [inline examples/chip-tool/main.cpp:164]: This needs to happen after the `lock_guard` goes out of scope and the lock is unlocked, since whoever wakes up will try to acquire the lock.

File: examples/chip-tool/main.cpp [hunk 7]
```diff
@@ -189,8 +193,11 @@ void OnMessage(DeviceController::ChipDeviceController * deviceController, void *
 static void OnError(DeviceController::ChipDeviceController * deviceController, void * appReqState, CHIP_ERROR error,
                     const IPPacketInfo * pi)
 {
-    waitingForResponse = false;
-    cvWaitingForResponse.notify_all();
+    {
+        std::lock_guard<std::mutex> lk(cvWaitingForResponseMutex);
+        waitingForResponse = false;
+        cvWaitingForResponse.notify_all();
```
Comment (bzbarsky-apple) [inline examples/chip-tool/main.cpp:199]: Again, the `notify_all` needs to be outside the `lock_guard` scope.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by mspang** [comment]
@saurabhst

**Review by saurabhst — APPROVED** [review]

**Comment by rwalker-apple** [comment]
@erjiaqing need conflicts addressed
