### PR TITLE
[Android] Fix CHIPTool cluster cmds fail or app crashes (Issue #15637).

### LINKED ISSUE #15637: [ Android App] Cluster Interaction Tool commands and Sensor Cluster commands fails or app crashes (exits).
Problem
Following commands fail or app crashes (exits) -

Cluster Interaction Tool commands -

- Color Control (Write Attribute) [ app crashes and exits ]
- Level Control (Read and Write Attribute) [ app crashes and exits ]
- OTA provider/OTA requestor [ app crashes and exits ]

Sensor Clusters commands -
- Read Pressure : returns fail

Expected behavior

- Cluster Interaction Tool commands and Sensor Cluster commands should pass. app should not crash and exit out.

Actual behavior

- Cluster Interaction Tool commands and Sensor Cluster commands fails or app crashes (exits).

Steps to reproduce

- Compile and flash app onto device
- Commission device using Android chip tool app using Commission with Wifi
- Run command (for eg. Read/Write Level Control commands)
- Run Cluster Interaction Tool Commands (mentioned above which are failing)

System configuration

- CHIP commit id: https://github.com/project-chip/connectedhomeip/commit/4668421c09d8d985de8be1bcaea535b431cd4118
- App: all_clusters_app
- Device: esp32devkit-c
- Android App: App built on the above mentioned CHIP commit id.

Device (esp32-devkitc) Logs:

[android_app_device_esp32devkitc_logs.pdf](https://github.com/project-chip/connectedhomeip/files/8159491/android_app_device_esp32devkitc_logs.pdf)

### PR DESCRIPTION
**Pull request by Litome**
#### Problem
* Fixes #15637 Android CHIPTool app fails or crashes when calling cluster cmds.

#### Change overview
* Ignore `offset_bytes >= decodedLength` check if `offset_bytes` is zero.
* Skip verification of `address != nullptr` and `port != 0` when "PROVISIONING CHIP DEVICE WITH WI-FI" as the verification gets called multiple times during provisioning. 

#### Testing
How was this tested? (at least one bullet point required)
* Tested on Pixel phone provisioning an ESP32 device.
* Tested to reproduce the crashes / fail provisioning first.
* Then applied changes and tested that:
* provisioning succeeded, 
* device as commissioned with WiFi details 
* "LIGHT ON/OFF & LEVEL CLUSTER" part of the Android app was able to turn the ESP32 light ON, OFF, TOGGLE and READ
* "SENSOR CLUSTERS" part of the Android app was able to read the temperature from the ESP32

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]
Fast tracking platform changes.

File: src/platform/android/DnssdImpl.cpp [hunk 1]
```diff
@@ -223,7 +223,7 @@ void HandleResolve(jstring instanceName, jstring serviceType, jstring address, j
         callback(reinterpret_cast<void *>(contextHandle), service, Span<Inet::IPAddress>(), error);
     };
 
-    VerifyOrReturn(address != nullptr && port != 0, dispatch(CHIP_ERROR_UNKNOWN_RESOURCE_ID));
+//     VerifyOrReturn(address != nullptr && port != 0, dispatch(CHIP_ERROR_UNKNOWN_RESOURCE_ID));
```
Comment (Damian-Nordic) [inline src/platform/android/DnssdImpl.cpp:226]: What's wrong with validating address and port? In which circumstances can they be 0s?

Comment (Litome) [reply src/platform/android/DnssdImpl.cpp]: I don't understand the lower layers enough but when I tried to "PROVISION CHIP DEVICE WITH WIFI" or "LIGHT ON/OFF & LEVEL CLUSTER" the code gets to that verify and exits printing this out twice in log cat:
`2022-03-03 16:05:14.326 16902-17436/com.google.chip.chiptool E/CTL: Error resolving node id: ConnectedHomeIP/src/platform/android/DnssdImpl.cpp:259: CHIP Error 0x000000A6: Unknown resource ID`

Without the verification, the android app works and I can provision the ESP32, turn the lights On and Off, read the status of the ESP32's light and its temperature.

I've done some improvement in commit https://github.com/project-chip/connectedhomeip/pull/15919/commits/668bb4657723a0fab45c1a59f5d65309812bf0ae this time keeping the verification but fixing the expression as the `VerifyOrReturn ` will act on the parameters "if expression evaluates to false". 
I thought the old `address != nullptr && port != 0` and new `!(address == nullptr || port == 0)` expression should evaluate the same but clearly they don't as it works with the new but not the old one.

File: .github/.wordlist.txt [hunk 2]
```diff
@@ -1373,3 +1373,19 @@ zephyrproject
 Zigbee
 zigbeealliance
 zigbeethread
+libshell
+TestGroupDemoConfig
```
Comment (andy31415) [inline .github/.wordlist.txt:1377]: please alphasort. Use something like `sort -f | unique -i`

File: .github/workflows/examples-efr32.yaml [hunk 3]
```diff
@@ -94,12 +94,13 @@ jobs:
                     'import("//with_pw_rpc.gni")'
                   .environment/pigweed-venv/bin/python3 scripts/tools/memory/gh_sizes.py efr32 BRD4161A+rpc lighting-app \
                     out/lighting_app_debug_rpc/BRD4161A/chip-efr32-lighting-example.out /tmp/bloat_reports/
-            - name: Build example EFR32+WF200 WiFi Lock app for BRD4161A
-              timeout-minutes: 10
-              run: |
-                  scripts/examples/gn_efr32_example.sh examples/lock-app/efr32/ out/lock_app_wifi_wf200 BRD4161A --wifi wf200
-                  .environment/pigweed-venv/bin/python3 scripts/tools/memory/gh_sizes.py efr32 BRD4161A+wf200 lock-app \
-                    out/lock_app_wifi_wf200/BRD4161A/chip-efr32-lock-example.out /tmp/bloat_reports/
+            # Disabled until Flash usage is reduced
```
Comment (andy31415) [inline .github/workflows/examples-efr32.yaml:97]: This change does not seem related to android tool changes

**Review by andy31415 — CHANGES_REQUESTED** [review]
This PR looks like it contains changes from several other PRs and probably has more deltas than the 'fix cmd fail and app crashes' as the title describes.

I am unable to find what actual deltas exist: this is 91K added lines and 1.3K deleted lines and cannot be code reviewed.

Please update the patch.

**Comment by Litome** [comment]
> This PR looks like it contains changes from several other PRs and probably has more deltas than the 'fix cmd fail and app crashes' as the title describes.
> 
> I am unable to find what actual deltas exist: this is 91K added lines and 1.3K deleted lines and cannot be code reviewed.
> 
> Please update the patch.

Yes, I followed the guideline to contribute which included "rebase to master if it has changed since your changes" which is where all the extra came from. My change only affects 2 files. I'll see if I can update my PR it so it only shows my changes. If not, maybe reject this PR and I'll create a new one with just my changes?

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
Needs restyle. @Litome please pick up the restyler changes from #15956 or run `./scripts/helpers/restyle-diff.sh` to auto restyle.

**Comment by andy31415** [comment]
> Should be fixed now. The "Files changed" tab shows only 2 files and they just have my changes. Sorry about that, it's my first time contributing a PR.

Thanks! Added the checkmark, needs restyle update before merge.

File: src/platform/android/DnssdImpl.cpp [hunk 4]
```diff
@@ -223,7 +223,7 @@ void HandleResolve(jstring instanceName, jstring serviceType, jstring address, j
         callback(reinterpret_cast<void *>(contextHandle), service, Span<Inet::IPAddress>(), error);
     };
 
-    VerifyOrReturn(address != nullptr && port != 0, dispatch(CHIP_ERROR_UNKNOWN_RESOURCE_ID));
+    VerifyOrReturn(!(address == nullptr || port == 0), dispatch(CHIP_ERROR_UNKNOWN_RESOURCE_ID));
```
Comment (bzbarsky-apple) [inline src/platform/android/DnssdImpl.cpp:226]: This change really does not make sense to me.  Could you please try logging the values of the following expressions:
* `address != nullptr`
* `address == nullptr`
* `port != 0`
* `port == 0`
 and reporting what you see?

Comment (Litome) [reply src/platform/android/DnssdImpl.cpp]: Yes, this time it logged the same, as expected so I reverted this change. It made no sense but it was working with my update and not with the original expression previously. Maybe my other change fixed both or some other change fixed this getting null address and 0 port occasionally...

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@Litome The CLA machinery is not happy because the address in the commits does not match your github info, as far as I can tell.  Sorry about the legal hurdles...

**Comment by Litome** [comment]
> @Litome The CLA machinery is not happy because the address in the commits does not match your github info, as far as I can tell. Sorry about the legal hurdles...

@[bzbarsky-apple](https://github.com/bzbarsky-apple) I really don't know how to get past this. I've changed my GitHub settings so that my "Primary email address" is the same as my .gitconfig settings so it matches my commits and re-accepted / signed the CLA agreement but nothing seems to work. Any idea how to smooth this administrative hurdle?

**Comment by bzbarsky-apple** [comment]
@woody-apple See the CLA question above?
