### PR TITLE
Crypto: Fix node id in IV

### LINKED ISSUE #15317: [security] GetIV must generate nonce using source id from session context
#### Problem
`CryptoContext::GetIV`generates the NONCE, but is always filling the source node id field from the message header:

```
bbuf.Put64(header.GetSourceNodeId().ValueOr(0));
```
This generally results in the value of `0` for all CASE and PASE sessions which omit source id in the header.  The specification states the source node id is to be pulled from the session context when omitted in the message header.

 #### Proposed Solution
Pull the source id from the session context for unicast sessions.

### PR DESCRIPTION
**Pull request by kghost**
#### Problem
Fixes #15317

#### Change overview
Compute correct IV for secure packets.

#### Testing
WIP

### CODE REVIEW

File: src/transport/CryptoContext.cpp [hunk 1]
```diff
@@ -131,16 +130,13 @@ CHIP_ERROR CryptoContext::InitFromKeyPair(const Crypto::P256Keypair & local_keyp
     return InitFromSecret(ByteSpan(secret, secret.Length()), salt, infoType, role);
 }
 
-CHIP_ERROR CryptoContext::GetIV(const PacketHeader & header, uint8_t * iv, size_t len)
+CHIP_ERROR CryptoContext::BuildIV(IVView iv, uint8_t securityFlags, uint32_t messageCounter, NodeId nodeId)
```
Comment (tcarmelveilleux) [inline src/transport/CryptoContext.cpp:133]: IV is the wrong name in the API altogether. The spec calls it Nonce, and the AES-CCM mode of operation described in NIST SP 800-38A also uses "N" and "nonce". "IV" should have never been used as terminology. I suggest that if this code is touched, we make sure to refactor to use proper terminology.

File: src/transport/CryptoContext.cpp [hunk 2]
```diff
@@ -161,7 +157,7 @@ CHIP_ERROR CryptoContext::GetAdditionalAuthData(const PacketHeader & header, uin
     return CHIP_NO_ERROR;
 }
 
-CHIP_ERROR CryptoContext::Encrypt(const uint8_t * input, size_t input_length, uint8_t * output, PacketHeader & header,
+CHIP_ERROR CryptoContext::Encrypt(const uint8_t * input, size_t input_length, uint8_t * output, ConstIVView iv, PacketHeader & header,
```
[the remark this answers is not in the document]
Comment (kghost) [reply src/transport/CryptoContext.cpp:160]: Do you mean adding a flag indicate that the source is set in the packet header but should be omitted when sending the packet ?

I'm not sure it is a good idea.

File: src/transport/CryptoContext.cpp (hunk 1 above)
Comment (kghost) [reply src/transport/CryptoContext.cpp:133]: Address separately #16216

Will rename IV in this PR soon.

**Comment by turon** [comment]
I don't see handling for CASE sessions which needs to pull the SourceNodeID out of the SessionInfo.  Am I missing something?  I'd suggest both PASE and CASE handling use this approach of pulling the SourceNodeID out of the Session in a consistent way.  Only group communication should pull the SourceNodeID out of the message header.

File: src/protocols/secure_channel/tests/TestPASESession.cpp [hunk 3]
```diff
@@ -416,7 +416,9 @@ void SecurePairingSerializeTest(nlTestSuite * inSuite, void * inContext)
 
         NL_TEST_ASSERT(inSuite, err == CHIP_NO_ERROR);
 
-        err = session1.Encrypt(plain_text, sizeof(plain_text), encrypted, header, mac);
+        CryptoContext::IVStorage iv;
+        CryptoContext::BuildIV(iv, header.GetSecurityFlags(), header.GetMessageCounter(), header.GetSourceNodeId().ValueOr(0));
```
[the remark this answers is not in the document]
Comment (turon) [reply src/protocols/secure_channel/tests/TestPASESession.cpp:420]: The issue is the Nonce always requires SourceNodeId, but that field isn't always in the header -- sometimes it is gleaned from the Session info, and we don't want to have to pass a Session object to Encrypt.

[the remark this answers is not in the document]
Comment (tcarmelveilleux) [reply src/protocols/secure_channel/tests/TestPASESession.cpp]: Suggest passing a `NodeId nodeIdForNonce` if it's always required for Encrypt/Decrypt

File: src/protocols/secure_channel/tests/TestPASESession.cpp [hunk 4]
```diff
@@ -416,7 +416,9 @@ void SecurePairingSerializeTest(nlTestSuite * inSuite, void * inContext)
 
         NL_TEST_ASSERT(inSuite, err == CHIP_NO_ERROR);
 
-        err = session1.Encrypt(plain_text, sizeof(plain_text), encrypted, header, mac);
+        CryptoContext::NonceStorage nonce;
+        CryptoContext::BuildNonce(nonce, header.GetSecurityFlags(), header.GetMessageCounter(), 0ull /* node id */);
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/tests/TestPASESession.cpp:420]: Please use `kUndefinedNodeId` as needed if that's what's really meant here.

File: src/protocols/secure_channel/tests/TestPASESession.cpp [hunk 5]
```diff
@@ -426,7 +428,9 @@ void SecurePairingSerializeTest(nlTestSuite * inSuite, void * inContext)
                        testPairingSession2->DeriveSecureSession(session2, CryptoContext::SessionRole::kResponder) == CHIP_NO_ERROR);
 
         uint8_t decrypted[64];
-        NL_TEST_ASSERT(inSuite, session2.Decrypt(encrypted, sizeof(plain_text), decrypted, header, mac) == CHIP_NO_ERROR);
+        CryptoContext::NonceStorage nonce;
+        CryptoContext::BuildNonce(nonce, header.GetSecurityFlags(), header.GetMessageCounter(), 0ull /* node id */);
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/tests/TestPASESession.cpp:432]: Again, `kUndefinedNodeId`

**Review by bzbarsky-apple — APPROVED** [review]

File: src/credentials/FabricTable.cpp [hunk 6]
```diff
@@ -618,15 +618,15 @@ CHIP_ERROR FabricTable::LoadFromStorage(FabricInfo * fabric)
...
-    {
-        ChipLogProgress(Discovery, "Fabric (%d) loaded from storage. Calling OnFabricRetrievedFromStorage",
-                        fabric->GetFabricIndex());
-        delegate->OnFabricRetrievedFromStorage(fabric);
-        delegate = delegate->mNext;
+        FabricTableDelegate * delegate = mDelegate;
+        while (delegate)
+        {
+            ChipLogProgress(Discovery, "Fabric (%d) loaded from storage. Calling OnFabricRetrievedFromStorage",
+                            fabric->GetFabricIndex());
```
Comment (tcarmelveilleux) [inline src/credentials/FabricTable.cpp:626]:
```suggestion
            ChipLogProgress(Discovery, "Fabric (%d) loaded from storage", fabric->GetFabricIndex());
```

File: src/transport/SessionManager.cpp [hunk 7]
```diff
@@ -197,7 +200,18 @@ CHIP_ERROR SessionManager::PrepareMessage(const SessionHandle & sessionHandle, P
...
+        CryptoContext::NonceStorage nonce;
+        if (session->GetSecureSessionType() == SecureSession::Type::kCASE)
+        {
+            FabricInfo * fabric = mFabricTable->FindFabricWithIndex(session->GetFabricIndex());
+            VerifyOrDie(fabric != nullptr);
+            CryptoContext::BuildNonce(nonce, packetHeader.GetSecurityFlags(), messageCounter, fabric->GetNodeId());
+        }
+        else
+        {
+            CryptoContext::BuildNonce(nonce, packetHeader.GetSecurityFlags(), messageCounter, kUndefinedNodeId);
```
Comment (tcarmelveilleux) [inline src/transport/SessionManager.cpp:212]:
```suggestion
            // CASE Sessions use the undefined node ID of all zeroes, since there is no node ID to use
            // and the key is short-lived and always different for each PASE session.
            CryptoContext::BuildNonce(nonce, packetHeader.GetSecurityFlags(), messageCounter, kUndefinedNodeId);
```

File: src/transport/SessionManager.cpp [hunk 8]
```diff
@@ -563,7 +577,11 @@ void SessionManager::SecureUnicastMessageDispatch(const PacketHeader & packetHea
 
     Transport::SecureSession * secureSession = session.Value()->AsSecureSession();
     // Decrypt and verify the message before message counter verification or any further processing.
-    if (SecureMessageCodec::Decrypt(secureSession->GetCryptoContext(), payloadHeader, packetHeader, msg) != CHIP_NO_ERROR)
+    CryptoContext::NonceStorage nonce;
+    CryptoContext::BuildNonce(nonce, packetHeader.GetSecurityFlags(), packetHeader.GetMessageCounter(),
```
Comment (tcarmelveilleux) [inline src/transport/SessionManager.cpp:581]:
```suggestion
    // PASE Sessions use the undefined node ID of all zeroes, since there is no node ID to use
    // and the key is short-lived and always different for each PASE session.
    CryptoContext::BuildNonce(nonce, packetHeader.GetSecurityFlags(), packetHeader.GetMessageCounter(),
```

**Review by tcarmelveilleux — APPROVED** [review]
