### PR TITLE
port SiLabs level-control over to CHIP

### LINKED ISSUE #2060: Import ../third_party/connectedhomeip/src/app/clusters/level-control
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

### PR DESCRIPTION
**Pull request by rwalker-apple**
#### Problem
 level-control cluster server isn't compiling in CHIP

 #### Summary of Changes
 make it compile and run, depends on #2038

fixes #2060

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Comment by rwalker-apple** [comment]
@bzbarsky-apple this is ready to rip

File: src/app/clusters/level-control/level-control.cpp [hunk 1]
```diff
@@ -483,11 +485,11 @@ static void moveToLevelHandler(uint8_t commandId, uint8_t level, uint16_t transi
 
     // Move To Level commands cause the device to move from its current level to
     // the specified level at the specified rate.
-    if (MAX_LEVEL < level)
+    if (MAX_LEVEL <= level)
```
Comment (bzbarsky-apple) [inline src/app/clusters/level-control/level-control.cpp:488]: Why this change and the one for the "min" case?  The net effect seems to be the same as the previous code...

File: src/app/clusters/level-control/level-control.cpp [hunk 2]
```diff
@@ -595,7 +597,7 @@ static void moveHandler(uint8_t commandId, uint8_t moveMode, uint8_t rate, uint8
         goto send_default_response;
     }
 
-    if (!shouldExecuteIfOff(endpoint, commandId, optionMask, optionOverride))
+    if (rate == 0 || !shouldExecuteIfOff(endpoint, commandId, optionMask, optionOverride))
```
Comment (bzbarsky-apple) [inline src/app/clusters/level-control/level-control.cpp:600]: So this just treats Move commands with a rate of 0 as no-ops?

This is not defined in the ZCL spec.  Could you get an issue filed to make sure this is defined in the CHIP data model?

File: src/app/clusters/level-control/level-control.cpp [hunk 3]
```diff
@@ -650,16 +652,34 @@ static void moveHandler(uint8_t commandId, uint8_t moveMode, uint8_t rate, uint8
         }
     }
 
-    // If the Rate field is 0xFF, the device should move as fast as it is able.
-    // Otherwise, the rate is in units per second.
+    // If the Rate field is 0xFF, the device should move at the default move rate, if available,
+    // Otherwise, move as fast as possible
```
Comment (bzbarsky-apple) [inline src/app/clusters/level-control/level-control.cpp:656]: This is a little confusing until one goes and reads the spec, since it's not clear whether "Otherwise" refers to availability of default move rate or to the value of the Rate field.  Maybe s/Otherwise/If there is no default move rate defined/ or so?

File: src/app/clusters/level-control/level-control.cpp [hunk 4]
```diff
@@ -650,16 +652,34 @@ static void moveHandler(uint8_t commandId, uint8_t moveMode, uint8_t rate, uint8
...
+        status = emberAfReadServerAttribute(endpoint, ZCL_LEVEL_CONTROL_CLUSTER_ID, ZCL_DEFAULT_MOVE_RATE_ATTRIBUTE_ID,
+                                            (uint8_t *) &defaultMoveRate, sizeof(defaultMoveRate));
+        if (status != EMBER_ZCL_STATUS_SUCCESS)
+        {
+            emberAfLevelControlClusterPrintln("ERR: reading default move rate %x", status);
+            state->eventDurationMs = FASTEST_TRANSITION_TIME_MS;
+        }
+        else
+        {
+            // nonsensical case, means "don't move", so we're done
```
Comment (bzbarsky-apple) [inline src/app/clusters/level-control/level-control.cpp:669]: Again, this should be defined in the CHIP data model....  Can probably be part of the issue I asked for above.

File: src/app/clusters/level-control/level-control.cpp [hunk 5]
```diff
@@ -650,16 +652,34 @@ static void moveHandler(uint8_t commandId, uint8_t moveMode, uint8_t rate, uint8
...
-    // If the Rate field is 0xFF, the device should move as fast as it is able.
-    // Otherwise, the rate is in units per second.
+    // If the Rate field is 0xFF, the device should move at the default move rate, if available,
+    // Otherwise, move as fast as possible
     if (rate == 0xFF)
     {
-        state->eventDurationMs = FASTEST_TRANSITION_TIME_MS;
+        uint16_t defaultMoveRate;
+        status = emberAfReadServerAttribute(endpoint, ZCL_LEVEL_CONTROL_CLUSTER_ID, ZCL_DEFAULT_MOVE_RATE_ATTRIBUTE_ID,
+                                            (uint8_t *) &defaultMoveRate, sizeof(defaultMoveRate));
```
Comment (bzbarsky-apple) [inline src/app/clusters/level-control/level-control.cpp:661]: I know the best we can do right now, but can you file a followup to have some file somewhere (maybe generated?) that templates on the cluster/attr id pair and exposes the right type and size to use for that attribute?  Or some other mechanism whereby we don't have to ensure manually that the types and sizes we use for attributes stay in sync with the attribute definitions...

File: src/app/util/util.c [hunk 6]
```diff
@@ -1400,3 +1400,19 @@ uint8_t emberAfMake8bitEncodedChanPg(uint8_t page, uint8_t channel)
         return channel | ENCODED_8BIT_CHANPG_PAGE_MASK_PAGE_0;
     }
 }
+
+EmberStatus emberAfScheduleServerTick(uint8_t endpoint, EmberAfClusterId clusterId, uint32_t delayMs)
+{
+    return EMBER_SUCCESS; // Stub for now.
```
Comment (bzbarsky-apple) [inline src/app/util/util.c:1406]: Please put a link to the issue tracking this here, and in the other tick stubs.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/util/util.c (hunk 6 above)
Comment (rwalker-apple) [reply src/app/util/util.c:1406]: this is my very next PR
