### PR TITLE
[EEVSE] Add TC_EEVSE_2_8 [Plug and Charge] feature support

### LINKED ISSUE #30993: [1.3] Potential improvement to HwSetVehicleID API in EVSE cluster delegate
### Reproduction steps

As part of PR review https://github.com/project-chip/connectedhomeip/pull/30857

Comment from @bzbarsky-apple 

> 
> So just to be clear: now we have fixed our delegate to in fact keep the vehicle ID in memory.... Sort of. It's relying on the fact that the caller of this API never wants the vehicle id for any long-term purpose, so the fact that it will later get deleted (if that setter in the delegate implementation gets called) is not a problem.
> 
> If we leave things like this, the precise expectations around lifetime need to be documented.
> 
> I don't want to block on this, but as followup consider an API shape more like this:
> 
> virtual CHIP_ERROR GetVehicleID(DataModel::Nullable<MutableCharSpan> & value) = 0;
> which has the following invariants:
> 
> The caller passes in a Nullable which has a value, and whose value points to a MutableCharSpan with some backing buffer big enough to hold a vehicle id. The caller in our case can just put all this stuff on the stack.
> The callee either does value.ClearValue() if null is meant to be returned or copies the vehicle id into the provided buffer. This allows the callee to store its vehicle IDs anywhere it wants to: RAM, NVM, etc, and makes use-after-free across this API impossible.
> 
> 
> 

### Bug prevalence

N/A

### GitHub hash of the SDK that was being used

N/A

### Platform

core

### Platform Version(s)

N/A

### Type

Core SDK Interopability Issue

### Anything else?

Lower priority issue - most EVSE's in Matter 1.3 won't support this feature (Plug & Charge) anyway.

### PR DESCRIPTION
**Pull request by jamesharrow**
#### Summary

 - [x] Fixes #30993 by adding a new HwGetVehicleID and removes use of new/delete (by holding a static buffer in delegate)
 - [x] Add new TC_EEVSE_2_8.py which is a candidate for next release
[This PR is based on https://github.com/project-chip/connectedhomeip/pull/39565 - once merged this PR is smaller]

#### Related issues

     Fixes: #30993

#### Testing

    added Python test: TC_EEVSE_2_8.py
    manually tested some of the new APIs by adding in calls (removed from checked-in code):

e.g. in EVSEManufacturerImpl.cpp in the Init() function:
```
    dg->HwSetVehicleID(CharSpan::fromCharString("TEST_"));

    char vehicleIdBuffer[64];
    MutableCharSpan mutableSpan(vehicleIdBuffer, sizeof(vehicleIdBuffer));
    DataModel::Nullable<MutableCharSpan> outVehicleId = MakeNullable(mutableSpan);

    ChipLogProgress(AppServer, "Check vehicleId is Null: %d", outVehicleId.IsNull());

    CHIP_ERROR err = dg->HwGetVehicleID(outVehicleId);
    ChipLogProgress(AppServer, "Check vehicleId is Null: %d", outVehicleId.IsNull());
    ChipLogProgress(AppServer, "vehicleId value: %s", vehicleIdBuffer);

    dg->HwSetVehicleID(CharSpan::fromCharString(""));
    err = dg->HwGetVehicleID(outVehicleId);
    ChipLogProgress(AppServer, "Check vehicleId is Null: %d", outVehicleId.IsNull());
```

which results in the output:
```
[1750441330.905] [2075708:2075708] [SVR] VehicleID updated TEST_
[1750441330.905] [2075708:2075708] [DMG] Endpoint 1, Cluster 0x0000_0099 update version to 4ceca765
[1750441330.905] [2075708:2075708] [SVR] Check vehicleId is Null: 0
[1750441330.905] [2075708:2075708] [SVR] Check vehicleId is Null: 0
[1750441330.905] [2075708:2075708] [SVR] vehicleId value: TEST_
[1750441330.905] [2075708:2075708] [SVR] VehicleID cleared
[1750441330.905] [2075708:2075708] [DMG] Endpoint 1, Cluster 0x0000_0099 update version to 4ceca766
[1750441330.905] [2075708:2075708] [SVR] Check vehicleId is Null: 1
```

#### Readability checklist

The checklist below will help the reviewer finish PR review in time and keep the
code readable:

-   [x] PR title is
        [descriptive](https://project-chip.github.io/connectedhomeip-doc/pull_request_guidelines.html#title-formatting)
-   [x] Apply the
        [_“When in Rome…”_](https://project-chip.github.io/connectedhomeip-doc/style/CODING_STYLE_GUIDE.html)
        rule (coding style)
-   [x] PR size is short
-   [x] Try to avoid "squashing" and "force-update" in commit history
-   [x] CI time didn't increase

See: [Pull Request Guidelines](https://project-chip.github.io/connectedhomeip-doc/pull_request_guidelines.html)

### CODE REVIEW

File: examples/energy-management-app/energy-management-common/energy-evse/src/EVSEManufacturerImpl.cpp [hunk 1]
```diff
@@ -190,6 +195,140 @@ CHIP_ERROR FindNextTarget(const BitMask<EnergyEvse::TargetDayOfWeekBitmap> dayOf
...
+    if (power_W == 0)
+    {
+        ChipLogError(AppServer, "EVSE Error: MaxCurrent = 0Amp - Can't schedule charging");
+        startTime_epoch_s.SetNull();
+        return CHIP_ERROR_INTERNAL;
+    }
+
+    // Time to charge(seconds) = (3600 * Energy(mWh) / Power(W)) / 1000
+    // to avoid using floats we multiply by 36 and then divide by 10 (instead of x3600 and dividing by 1000)
+    chargingDuration_s = static_cast<uint32_t>(((requiredEnergy_mWh / power_W) * 36) / 10);
```
[the remark this answers is not in the document]
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-evse/src/EVSEManufacturerImpl.cpp]: Although not relevant to this PR (it was based on another branch PR) applied the suggestions.

File: examples/energy-management-app/energy-management-common/energy-evse/src/EVSEManufacturerImpl.cpp [hunk 2]
```diff
@@ -46,6 +46,8 @@ using namespace chip::app::Clusters::PowerSource::Attributes;
 
 using Protocols::InteractionModel::Status;
 
+constexpr int64_t kMaxRequiredEnergy_mWh = 1000000000; // 1000 MWh
```
[the remark this answers is not in the document]
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-evse/src/EVSEManufacturerImpl.cpp]: Although not relevant to this PR (it was based on another branch PR) applied the suggestions.

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp [hunk 3]
```diff
@@ -420,16 +420,10 @@ Status Instance::ValidateTargets(
                 return Status::ConstraintError;
             }
 
-            // If SocReporting is supported, targetSoc must have a value in the range [0, 100]
+            // If SocReporting is supported, targetSoc can have a value in the range [0, 100] (if present)
```
Comment (bzbarsky-apple) [inline src/app/clusters/energy-evse-server/energy-evse-server.cpp]: Per spec, TargetSoC is required if the SoCReporting feature is supported, no?

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp [hunk 4]
```diff
@@ -420,16 +420,10 @@ Status Instance::ValidateTargets(
...
             if (HasFeature(Feature::kSoCReporting))
             {
-                if (!targetStruct.targetSoC.HasValue())
-                {
-                    ChipLogError(AppServer, "kSoCReporting is supported but TargetSoC does not have a value");
-                    return Status::Failure;
```
Comment (bzbarsky-apple) [inline src/app/clusters/energy-evse-server/energy-evse-server.cpp]: Should probably have been InvalidCommand per spec....

**Review by bzbarsky-apple — DISMISSED** [review]

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp (hunk 3 above)
Comment (jamesharrow) [reply src/app/clusters/energy-evse-server/energy-evse-server.cpp]: Ah true - the issue I faced was that TC_EEVSE_2.3 started to fail once the SOC feature was enabled because the client was sending a target without SOC. So the issue is that the client test case is broken based on Matter 1.3/1.4 which is where EEVSE_2.3 was originally written. I think we will need to revisit the test script or decide if a client is allowed to omit the target SoC (spec doesn't allow it as written).

BTW this PR is still in draft because I was waiting for 2nd review on PR https://github.com/project-chip/connectedhomeip/pull/39565 [the hope was that would merge and this PR on TC 2.8 - PNC feature would be much smaller!].

Comment (jamesharrow) [reply src/app/clusters/energy-evse-server/energy-evse-server.cpp]: I'll probably back out this SDK change and change the EEVSE 2.3 test script / test plan...

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp (hunk 4 above)
Comment (jamesharrow) [reply src/app/clusters/energy-evse-server/energy-evse-server.cpp]: I was looking in the spec and it doesn't really say anything about it in section https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/EnergyEVSE.adoc#952-effect-on-receipt - but agree that InvalidCommand seems more logical than Failure. 

Assume it is okay to make this change now... maybe we should tweak the spec to be explicit?

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp (hunk 3 above)
Comment (jamesharrow) [reply src/app/clusters/energy-evse-server/energy-evse-server.cpp]: Backed out this change now... will work out how to adapt the test script.

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp (hunk 4 above)
Comment (jamesharrow) [reply src/app/clusters/energy-evse-server/energy-evse-server.cpp]: Made the change as suggested.

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp (hunk 3 above)
Comment (jamesharrow) [reply src/app/clusters/energy-evse-server/energy-evse-server.cpp]: TC_EEVSE_2.3 has been reworked to skip a few steps and use TargetSoC=100 in some steps.
Test Plan PR: https://github.com/CHIP-Specifications/chip-test-plans/pull/5235

Comment (jamesharrow) [reply src/app/clusters/energy-evse-server/energy-evse-server.cpp]: Resolved and approved in PR #39565

File: src/app/clusters/energy-evse-server/energy-evse-server.cpp (hunk 4 above)
Comment (jamesharrow) [reply src/app/clusters/energy-evse-server/energy-evse-server.cpp]: resolved in other PR #39565

File: examples/energy-management-app/energy-management-common/energy-evse/include/EnergyEvseDelegateImpl.h [hunk 5]
```diff
@@ -228,6 +228,7 @@ class EnergyEvseDelegate : public EnergyEvse::Delegate
     Status HwSetFault(FaultStateEnum fault);
     Status HwSetRFID(ByteSpan uid);
     Status HwSetVehicleID(const CharSpan & vehID);
+    CHIP_ERROR HwGetVehicleID(DataModel::Nullable<MutableCharSpan> & outValue);
```
Comment (soares-sergio) [inline examples/energy-management-app/energy-management-common/energy-evse/include/EnergyEvseDelegateImpl.h:231]: Could you double check the return types  in all of these functions?
There's a mix of `CHIP_ERROR` and `chip::Protocols::InteractionModel::Status`. It's fine to do in a follow up as it's not an issue introduced by this PR.

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp [hunk 6]
```diff
@@ -581,37 +581,60 @@ Status EnergyEvseDelegate::HwSetRFID(ByteSpan uid)
...
-        delete[] destinationBuffer;
-        return Status::Failure;
+        return Status::Success;
     }
 
-    if (!mVehicleID.IsNull())
+    if (newValue.size() > kMaxVehicleIDBufSize)
     {
-        delete[] mVehicleID.Value().data();
+        ChipLogError(AppServer, "HwSetVehicleID - input too long");
```
Comment (soares-sergio) [inline examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp]:
```suggestion
        ChipLogError(AppServer, "HwSetVehicleID - input too long. Max size = %d", kMaxVehicleIDBufSize);
```

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp [hunk 7]
```diff
@@ -581,37 +581,60 @@ Status EnergyEvseDelegate::HwSetRFID(ByteSpan uid)
...
+ */
+CHIP_ERROR EnergyEvseDelegate::HwGetVehicleID(DataModel::Nullable<MutableCharSpan> & outValue)
+{
+    if (mVehicleID.IsNull())
+    {
+        outValue.SetNull();
+        return CHIP_NO_ERROR;
+    }
+
+    MutableCharSpan & buffer = outValue.Value();
```
Comment (soares-sergio) [inline examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp]:
```suggestion
```

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp [hunk 8]
```diff
@@ -581,37 +581,60 @@ Status EnergyEvseDelegate::HwSetRFID(ByteSpan uid)
...
+    if (buffer.size() < mVehicleID.Value().size())
```
Comment (soares-sergio) [inline examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp]:
```suggestion
    if (outValue.Value().size() < mVehicleID.Value().size())
```

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp [hunk 9]
```diff
@@ -581,37 +581,60 @@ Status EnergyEvseDelegate::HwSetRFID(ByteSpan uid)
...
+    {
+        return CHIP_ERROR_BUFFER_TOO_SMALL;
+    }
+
+    memcpy(buffer.data(), mVehicleID.Value().data(), mVehicleID.Value().size());
```
Comment (soares-sergio) [inline examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp]:
```suggestion
    memcpy(outValue.Value().data(), mVehicleID.Value().data(), mVehicleID.Value().size());
```

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp [hunk 10]
```diff
@@ -581,37 +581,60 @@ Status EnergyEvseDelegate::HwSetRFID(ByteSpan uid)
...
+    buffer.reduce_size(mVehicleID.Value().size());
```
Comment (soares-sergio) [inline examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp]:
```suggestion
    outValue.Value().reduce_size(mVehicleID.Value().size());
```

File: src/python_testing/TC_EEVSE_2_8.py [hunk 11]
```diff
@@ -0,0 +1,104 @@
...
+        self.step("3")
+        value = await self.read_evse_attribute_expect_success(attribute="VehicleID")
+        asserts.assert_is_instance(value, (Nullable, str), "VehicleID must be null or a string")
+
+        self.step("4")
+        await self.send_test_event_trigger_evse_set_vehicleid()
+
+        self.step("5")
+        value = await self.read_evse_attribute_expect_success(attribute="VehicleID")
+        asserts.assert_is_instance(value, str, "VehicleID must be a string")
```
Comment (soares-sergio) [inline src/python_testing/TC_EEVSE_2_8.py:100]: Don't you need to check the content of the attribute you just set on the previous step?
Or is this done in a different test?

Otherwise returning any garbage string would pass?

**Review by soares-sergio — APPROVED** [review]
Made some minor  comments, feel free to resolve and merge once addressed. Thanks

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseEventTriggers.cpp [hunk 12]
```diff
@@ -162,7 +162,12 @@ void SetTestEventTrigger_EVSESetSoCClear()
 }
 void SetTestEventTrigger_EVSESetVehicleID()
 {
-    // TODO
+    constexpr char newVehicleID[] = "Test-Vehicle-ID-012345789-ABCDEF";
+
+    CharSpan vehicleIdSpan(newVehicleID, strlen(newVehicleID));
```
Comment (bzbarsky-apple) [inline examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseEventTriggers.cpp]: Could use `"Test-Vehicle-ID-012345789-ABCDEF"_span` to make all this much simpler.

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp (hunk 9 above)
Comment (bzbarsky-apple) [inline examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp]: Is there a reason we're reinventing CopyCharSpanToMutableCharSpan?

File: src/python_testing/TC_EEVSE_2_8.py
Comment (bzbarsky-apple) [inline src/python_testing/TC_EEVSE_2_8.py:1]: I did not review this file.

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseEventTriggers.cpp (hunk 12 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseEventTriggers.cpp]: Changed

File: src/python_testing/TC_EEVSE_2_8.py (hunk 11 above)
Comment (jamesharrow) [reply src/python_testing/TC_EEVSE_2_8.py:100]: There is no defined format in the spec - it is just a string - so that's all we can do

File: examples/energy-management-app/energy-management-common/energy-evse/include/EnergyEvseDelegateImpl.h (hunk 5 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-evse/include/EnergyEvseDelegateImpl.h:231]: Ok will look to do a follow up - arguably they should all be CHIP_ERROR, but would need to look at why the original choice of using Status was chosen on some of them.

Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-evse/include/EnergyEvseDelegateImpl.h:231]: Raised https://github.com/project-chip/connectedhomeip/issues/39863 to track

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp (hunk 7 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp]: Reworked so this code no-longer used.

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp (hunk 8 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp]: Reworked so this code no-longer used.

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp (hunk 9 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp]: Reworked so this code no-longer used.

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp (hunk 10 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp]: Reworked so this code no-longer used.

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp (hunk 9 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp]: Reverted back to using CopyCharSpanToMutableCharSpan

File: src/python_testing/TC_EEVSE_2_8.py (hunk 11 above)
Comment (soares-sergio) [reply src/python_testing/TC_EEVSE_2_8.py:100]: Could it be that the spec test plan is not correct/incomplete? Or is this a common pattern?

In my mind, it makes no sense to write a string in the previous step, then in the next step, read it back and "only check the type" not the actual value? But I might be I'm missing something as I'm not super familiar with these test plans specs.

Comment (jamesharrow) [reply src/python_testing/TC_EEVSE_2_8.py:100]: The problem is that this is just an opaque string - We can check it isn't too long I suppose (it has a max length 32)

Comment (jamesharrow) [reply src/python_testing/TC_EEVSE_2_8.py:100]: Updated to add a string len test (will update the test plan in another PR)

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp [hunk 13]
```diff
@@ -581,37 +571,51 @@ Status EnergyEvseDelegate::HwSetRFID(ByteSpan uid)
...
 Status EnergyEvseDelegate::HwSetVehicleID(const CharSpan & newValue)
 {
-    // TODO this code to be refactored - See Issue #30993
-    if (!mVehicleID.IsNull() && newValue.data_equal(mVehicleID.Value()))
+    // If the input is empty, treat it as a request to clear the vehicle ID
+    if (newValue.empty())
     {
+        mVehicleID.SetNull();
+        ChipLogDetail(AppServer, "VehicleID cleared");
+        MatterReportingAttributeChangeCallback(mEndpointId, EnergyEvse::Id, VehicleID::Id);
```
Comment (bzbarsky-apple) [inline examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp]: Should this dirty-marking not be skipped if the value was already null?

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
Note: I did not review the Python bits.

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp (hunk 13 above)
Comment (jamesharrow) [reply examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp]: Good point - reordered some of the if statements to avoid that scenario

File: examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp [hunk 14]
```diff
@@ -591,6 +583,15 @@ Status EnergyEvseDelegate::HwSetVehicleID(const CharSpan & newValue)
         return Status::Failure;
     }
 
+    // If the input is empty, treat it as a request to clear the vehicle ID
+    if (newValue.empty())
+    {
+        mVehicleID.SetNull();
+        ChipLogDetail(AppServer, "VehicleID cleared");
+        MatterReportingAttributeChangeCallback(mEndpointId, EnergyEvse::Id, VehicleID::Id);
```
Comment (bzbarsky-apple) [inline examples/energy-management-app/energy-management-common/energy-evse/src/EnergyEvseDelegateImpl.cpp:591]: This didn't address my review comment.

If mVehicleID is null on entry into this function and newValue is empty, the value will not change but the attribute will be marked dirty.
