### PR TITLE
[WebRTC] Parse and set ICE servers to PeerConnection

### LINKED ISSUE #41656: [BUG] ICE servers are not used in camera-app
### Reproduction steps

The ICE servers in `HandleProvideOffer` are not being used at all (they are essentially sent and dropped [here](https://github.com/project-chip/connectedhomeip/blob/9b7095bdc66dbd4055f08efce648d524e1b4626d/examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp#L254)).

This can also be seen here when constructing the libdatachannel's peerconnection, as it only takes the ice servers at ctor, and this is currently being initialized with none (there's a commented line of a STUN server, but not the actual servers provided by the controller for the peer connection): https://github.com/project-chip/connectedhomeip/blob/9b7095bdc66dbd4055f08efce648d524e1b4626d/examples/camera-app/linux/src/webrtc-libdatachannel.cpp#L287

### Bug prevalence

Consistent

### GitHub hash of the SDK that was being used

63d896f1aa7ce3c12c44dc882ced61b4eaeb64eb

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Summary

WebRTC peers behind NATs or firewalls often cannot establish direct connections. ICE servers (STUN/TURN) help discover public IP addresses and relay traffic when direct connectivity fails. The Matter WebRTC Transport Provider cluster allows clients to specify ICE servers in the SolicitOffer and ProvideOffer commands.

This change adds support for configuring ICE (Interactive Connectivity Establishment) servers in the WebRTC transport layer, enabling NAT traversal for camera streaming sessions.   

#### Related issues

Fixes: #41656

#### Testing

Validate by CI

#### Readability checklist

The checklist below will help the reviewer finish PR review in time and keep the
code readable:

-   [ ] PR title is
        [descriptive](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html#title-formatting)
-   [ ] Apply the
        [_“When in Rome…”_](https://project-chip.github.io/connectedhomeip-doc/style/CODING_STYLE_GUIDE.html)
        rule (coding style)
-   [ ] PR size is short
-   [ ] Try to avoid "squashing" and "force-update" in commit history
-   [ ] CI time didn't increase

See: [Pull Request Guidelines](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html)

### CODE REVIEW

File: examples/camera-app/linux/include/webrtc-transport.h [hunk 1]
```diff
@@ -145,6 +148,7 @@ class WebrtcTransport : public Transport
     RequestArgs mRequestArgs;
     OnTransportLocalDescriptionCallback mOnLocalDescription = nullptr;
     OnTransportConnectionStateCallback mOnConnectionState   = nullptr;
+    std::vector<ICEServerInfo> mIceServers;
```
Comment (pidarped) [inline examples/camera-app/linux/include/webrtc-transport.h]: nit: Recommend mICEServers.

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp [hunk 2]
```diff
@@ -101,6 +101,40 @@ bool ValidateSdpFields(const std::string & sdp)
...
+{
+    std::vector<ICEServerInfo> iceServers;
+    for (const auto & server : matterIceServers)
+    {
+        ICEServerInfo info;
+        auto urlsIter = server.URLs.begin();
+        while (urlsIter.Next())
+        {
+            info.urls.emplace_back(urlsIter.GetValue().data(), urlsIter.GetValue().size());
+        }
```
Comment (pidarped) [inline examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp:123]: Need an error check on urlsIter.GetStatus()? That, actually, might mean changing the function signature slightly.

File: examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp [hunk 3]
```diff
@@ -207,6 +241,11 @@ CHIP_ERROR WebRTCProviderManager::HandleSolicitOffer(const OfferRequestArgs & ar
         ChipLogProgress(Camera, "SFrame encryption enabled for session %u", args.sessionId);
     }
 
+    if (args.iceServers.HasValue())
```
Comment (pidarped) [inline examples/camera-app/linux/src/clusters/webrtc-provider/webrtc-provider-manager.cpp:247]: Worth adding a log that if the commands do not contain the ICE servers then the ICE negotiation would be limited to host candidates.

**Review by pidarped — APPROVED** [review]

**Review by joonhaengHeo — APPROVED** [review]
