### PR TITLE
[Silabs] Consolidated Identify callback implementation to common file

### LINKED ISSUE #26797: [BUG] Identify cluster effect identifier and effect variant are NOT the same thing - used in multiple example apps
### Reproduction steps

All the below mentioned example codes do casting from effect variant to effect identifier, which are not the same thing.

`sIdentifyEffect = static_cast<EmberAfIdentifyEffectIdentifier>(identify->mEffectVariant);`

```
examples/chef/efr32/src/AppTask.cpp
examples/light-switch-app/silabs/efr32/src/AppTask.cpp
examples/lighting-app/qpg/src/AppTask.cpp
examples/lighting-app/silabs/efr32/src/AppTask.cpp
examples/lock-app/qpg/src/AppTask.cpp
examples/lock-app/silabs/efr32/src/AppTask.cpp
examples/thermostat/silabs/efr32/src/AppTask.cpp
examples/window-app/common/src/WindowApp.cpp
```

### Bug prevalence

always

### GitHub hash of the SDK that was being used

e022057aea58fee7f855d8994c7f971c5ac2c875

### Platform

efr32, other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jmartinez-silabs**
fixes #26797 -> Invalid cast removed, support the `EffectIdentifierEnum::kChannelChange`. For the Effect Variant, currently, only `EffectVariantEnum::kDefault` exist; Add a condition and a print in case new `EffectVariantEnum` values are eventually added

Other changes:
- Bringing all the duplicated identify implementation in each Silabs app to be handled by the common baseApplication.cpp.
- Clean up the led patterns implementation
- Add a few ifdef in case identify cluster is not enabled or in case the Silabs board used doesn't have a status led.

_* I removed the Invalid cast for the qpg platform also._

Can be reviewed by commit
- Commit 1 is the base of the changes and fixes.
- Commit 2 Cleans up the same duplication for other Silabs apps
- Commit 3 remove invalid cast for qpg

### CODE REVIEW

File: examples/lighting-app/qpg/src/AppTask.cpp [hunk 1]
```diff
@@ -108,18 +108,17 @@ void OnTriggerIdentifyEffect(Identify * identify)
 {
     sIdentifyEffect = identify->mCurrentEffectIdentifier;
 
-    if (identify->mCurrentEffectIdentifier == Clusters::Identify::EffectIdentifierEnum::kChannelChange)
+    if (identify->mEffectVariant != Clusters::Identify::EffectVariantEnum::kDefault)
```
Comment (jepenven-silabs) [inline examples/lighting-app/qpg/src/AppTask.cpp:111]: This is QPG platform.... is this changes really necessary ?

File: examples/lock-app/qpg/src/AppTask.cpp [hunk 2]
```diff
@@ -105,18 +105,17 @@ void OnTriggerIdentifyEffect(Identify * identify)
 {
     sIdentifyEffect = identify->mCurrentEffectIdentifier;
 
-    if (identify->mCurrentEffectIdentifier == Clusters::Identify::EffectIdentifierEnum::kChannelChange)
+    if (identify->mEffectVariant != Clusters::Identify::EffectVariantEnum::kDefault)
```
Comment (jepenven-silabs) [inline examples/lock-app/qpg/src/AppTask.cpp:108]: Again QPG

File: examples/platform/silabs/efr32/BaseApplication.cpp [hunk 3]
```diff
@@ -299,6 +299,87 @@ void BaseApplication::FunctionEventHandler(AppEvent * aEvent)
     }
 }
 
+bool BaseApplication::ActivateStatusLedPatterns()
+{
+    bool isPatternSet = false;
+#if defined(ENABLE_WSTK_LEDS) && defined(SL_CATALOG_SIMPLE_LED_LED1_PRESENT)
```
Comment (jepenven-silabs) [inline examples/platform/silabs/efr32/BaseApplication.cpp:305]: This define should be removed. You can also leave it you want but it will be remove upon merging the BaseApplication.

File: examples/platform/silabs/efr32/BaseApplication.cpp [hunk 4]
```diff
@@ -323,6 +404,7 @@ void BaseApplication::LightEventHandler()
     }
 #endif // CHIP_DEVICE_CONFIG_ENABLE_SED
 
+#if defined(ENABLE_WSTK_LEDS) && defined(SL_CATALOG_SIMPLE_LED_LED1_PRESENT)
```
Comment (jepenven-silabs) [inline examples/platform/silabs/efr32/BaseApplication.cpp:407]: Same comment as above

**Review by jepenven-silabs — APPROVED** [review]

File: examples/lighting-app/qpg/src/AppTask.cpp (hunk 1 above)
Comment (jmartinez-silabs) [reply examples/lighting-app/qpg/src/AppTask.cpp:111]: they copied the wrongful cast from my mistake, so I changed that for them too. It doesn't affect much else

File: examples/platform/silabs/efr32/BaseApplication.cpp (hunk 3 above)
Comment (jmartinez-silabs) [reply examples/platform/silabs/efr32/BaseApplication.cpp:305]: Currently, LEDWidget sStatusLED; is encapsulated in the same ifdef and so are the includes for the LedWidget and `sl_simple_led_instances`
I'll leave it here. When it isn't needed anymore we can quickly Find and delete all the ENABLE_WSTK_LEDS ifdefs

File: examples/platform/silabs/efr32/BaseApplication.cpp (hunk 4 above)
Comment (jmartinez-silabs) [reply examples/platform/silabs/efr32/BaseApplication.cpp:407]: Same reply as my previous one.

File: examples/lock-app/qpg/src/AppTask.cpp (hunk 2 above)
Comment (jmartinez-silabs) [reply examples/lock-app/qpg/src/AppTask.cpp:108]: it won't cause them any harm and it was a quick change

File: examples/window-app/common/src/WindowApp.cpp [hunk 5]
```diff
@@ -40,20 +40,17 @@ void OnTriggerEffect(Identify * identify)
...
 
-    ChipLogProgress(Zcl, "IDENTFY  OnTriggerEffect");
-
-    if (identify->mCurrentEffectIdentifier == Clusters::Identify::EffectIdentifierEnum::kChannelChange)
+    if (identify->mEffectVariant != Clusters::Identify::EffectVariantEnum::kDefault)
     {
-        ChipLogProgress(Zcl, "IDENTIFY_EFFECT_IDENTIFIER_CHANNEL_CHANGE - Not supported, use effect varriant %d",
-                        to_underlying(identify->mEffectVariant));
-        sIdentifyEffect = static_cast<Clusters::Identify::EffectIdentifierEnum>(identify->mEffectVariant);
+        ChipLogDetail(AppServer, "Identify Effect Variant unsupported. Using default");
```
Comment (jmeg-sfy) [inline examples/window-app/common/src/WindowApp.cpp:45]: Cannot we handle this particular use case within its own callback ?

File: examples/platform/silabs/efr32/BaseApplication.cpp [hunk 6]
```diff
@@ -517,6 +543,75 @@ void BaseApplication::StopStatusLEDTimer()
...
+void BaseApplication::OnTriggerIdentifyEffectCompleted(chip::System::Layer * systemLayer, void * appState)
+{
+    ChipLogProgress(Zcl, "Trigger Identify Complete");
+    sIdentifyEffect = Clusters::Identify::EffectIdentifierEnum::kStopEffect;
+
+#if CHIP_DEVICE_CONFIG_ENABLE_SED == 1
+    StopStatusLEDTimer();
+#endif
+}
+
```
Comment (jmeg-sfy) [inline examples/platform/silabs/efr32/BaseApplication.cpp:574]: the variant part ?

File: examples/window-app/common/src/WindowApp.cpp (hunk 5 above)
Comment (jmartinez-silabs) [reply examples/window-app/common/src/WindowApp.cpp:45]: I don't understand what do you mean. Which callback? The effect variant is part of the the trigger effects command. It triggers the same callback. Currently in the spec there is only. 1 possible effect variant; default.  This is check is only a mean to present a handling of the effect variant and at least a notification if additional effect variant are added

File: examples/platform/silabs/efr32/BaseApplication.cpp (hunk 6 above)
Comment (jmartinez-silabs) [reply examples/platform/silabs/efr32/BaseApplication.cpp:574]: The only variant that exist currently is default. Which is the normal effect done here

**Review by bzbarsky-apple — APPROVED** [review]
