### PR TITLE
Fix the extended discovery time limit to actually be obeyed properly.

### LINKED ISSUE #16522: Extended discovery timeout is extended on each `DnssdServer::StartServer`
#### Problem
Extended discovery timeout is reset every time `DnssdServer::StartServer` is called (that is, whenever published DNS-SD services may need to be refreshed) while the timeout should only be scheduled when the extended discovery starts.

 #### Proposed Solution
1. Start the extended discovery timeout in `DnssdServer::StartServer` only if it's not yet started.
2. Cancel the extended discovery timeout when `DnssdServer::StartServer` is called and the commissioning window is open.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Fixes https://github.com/project-chip/connectedhomeip/issues/16522

Tested that if CHIP_DEVICE_CONFIG_EXTENDED_DISCOVERY_TIMEOUT_SECS is set to
CHIP_DEVICE_CONFIG_DISCOVERY_NO_TIMEOUT then we advertise extended discovery
in all the conditions where we are not advertising commissionable discovery.

If CHIP_DEVICE_CONFIG_EXTENDED_DISCOVERY_TIMEOUT_SECS is set to another value, verified that:

1. We do not start advertising extended discovery on startup.
2. If we start advertising commissionable discovery on startup, then after the
   commissioning window closes (whether due to being commissioned or timing out)
   we we start advertising extended discovery until that times out.
3. If we open a new commissioning window and then RevokeCommissioning, we start
   advertising extended discovery until it times out.
4. If we open a new commissioning window and then commission the device, we
   start advertising extended discovery until it times out.
5. If in a state with two fabrics commissioned we remove a fabric we do _not_
   start advertising extended discovery (unlike before this change).
6. If in a state with two fabrics commissioned and extended discovery
   advertising ongoing we remove one of the fabrics, we keep advertising
   extended discovery until it times out.

#### Problem
See https://github.com/project-chip/connectedhomeip/issues/16522

#### Change overview
Keep better track of when we actually need to start extended discovery and when we need to reset its timer; don't reset the timer if we're not starting a new extended discovery period.

#### Testing
For all tests I used all-clusters-app compiled with extended discovery enabled.  I modified it to allow smaller commissioning window timeouts than 3 minutes to speed up testing.

For item 1: Start commissioned all-clusters app and verify that it only advertises operational.

for item 2: Start uncommissioned all-clusters-app, verify (via `dns-sd`) that it advertises commissionable until the commissioning window closes, then advertises extended discovery until that timeout expires.

For item 3: Start commissioned all-clusters-app, use `chip-tool pairing open-commissioning-window` and `chip-tool administratorcommissioning revoke-commissioning`.

For item 4: Start commissioned all-clusters-app, use `chip-tool pairing open-commissioning-window` to open a BCM window and `chip-tool pairing code --commissioner-name beta` to pair with the original manual code.

For item 5: Starting after item 4, wait until the extended discovery times out, then do a `remove-fabric` command via chip-tool.

For item 6: Repeat item 4 and 5, but do the remove before the extended discovery has timed out.

### CODE REVIEW

File: src/app/server/Dnssd.cpp [hunk 1]
```diff
@@ -412,13 +370,27 @@ void DnssdServer::StartServer(Dnssd::CommissioningMode mode)
 #if CHIP_DEVICE_CONFIG_ENABLE_EXTENDED_DISCOVERY
     else if (GetExtendedDiscoveryTimeoutSecs() != CHIP_DEVICE_CONFIG_DISCOVERY_DISABLED)
     {
-        err = AdvertiseCommissionableNode(mode);
-        if (err != CHIP_NO_ERROR)
+        bool alwaysAdvertiseExtended = (GetExtendedDiscoveryTimeoutSecs() == CHIP_DEVICE_CONFIG_DISCOVERY_NO_TIMEOUT);
+        // We do extended discovery advertising in three cases:
+        // 1) We don't have a timeout for extended discovery.
+        // 2) We are transitioning out of commissioning mode (basic or enhanced)
+        //    and should thherefore start extended discovery.
```
Comment (chrisdecenzo) [inline src/app/server/Dnssd.cpp:377]:
```suggestion
        //    and should therefore start extended discovery.
```

**Review by chrisdecenzo — APPROVED** [review]

File: src/app/server/Dnssd.cpp [hunk 2]
```diff
@@ -412,13 +370,27 @@ void DnssdServer::StartServer(Dnssd::CommissioningMode mode)
 #if CHIP_DEVICE_CONFIG_ENABLE_EXTENDED_DISCOVERY
     else if (GetExtendedDiscoveryTimeoutSecs() != CHIP_DEVICE_CONFIG_DISCOVERY_DISABLED)
     {
-        err = AdvertiseCommissionableNode(mode);
-        if (err != CHIP_NO_ERROR)
+        bool alwaysAdvertiseExtended = (GetExtendedDiscoveryTimeoutSecs() == CHIP_DEVICE_CONFIG_DISCOVERY_NO_TIMEOUT);
+        // We do extended discovery advertising in three cases:
+        // 1) We don't have a timeout for extended discovery.
+        // 2) We are transitioning out of commissioning mode (basic or enhanced)
```
Comment (Damian-Nordic) [inline src/app/server/Dnssd.cpp:376]: Are you sure we shouldn't start the extended discovery when the device starts with the commissioning mode off? I thought Pairing Hint could include instructions on how to put the device in the commissioning mode so from that perspective it would be useful to have a way to start the advertising with CM=0.

Comment (bzbarsky-apple) [reply src/app/server/Dnssd.cpp:376]: @Damian-Nordic I asked @chrisdecenzo that question and this implements what I believe he explained as the goal.

That said, I can see the argument for doing extended discovery if we have no fabrics commissioned and are just starting up.  I can modify this PR to make that work.  Or do you think we should also advertise extended discovery on startup even if there are fabrics commissioned?

Comment (Damian-Nordic) [reply src/app/server/Dnssd.cpp:376]: Yeah, based on the description of **CommissioningModeInitialStepsHint** I do think we should advertise extended discovery on startup:
> This field SHALL identify a hint for the steps that MAY be used to put a device that has not yet been
commissioned into commissioning mode.
> (...)
> Devices that implement Extended Discovery SHALL reflect this value in the Pairing Hint field of Commissionable Node Discovery when they have not yet been commissioned.

Would you agree?

**Review by tcarmelveilleux — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

File: src/app/server/Dnssd.cpp (hunk 2 above)
Comment (chrisdecenzo) [reply src/app/server/Dnssd.cpp:376]: @Damian-Nordic raises a good point I had not considered

Comment (bzbarsky-apple) [reply src/app/server/Dnssd.cpp:376]: Yep, done.
