### PR TITLE
Issue 22318 - commissioner attestation delegate should be able to override success

### LINKED ISSUE #22423: [1.0] Commissioner attestation delegate should be able to override success
### Reproduction steps

```bash
The SDK currently allows an attestation delegate to override an attestation failure in response to user preference. The attestation delegate should also be able to override attestation success, in case application logic decides to stop commissioning a device.
```

### Bug prevalence

N/A 

### GitHub hash of the SDK that was being used

0f0e1e9b869719c06a9d3e10c1fa1ee1e9cb4759

### Platform

darwin, core

### Platform Version(s)

_No response_

### Type

Platform Issue

### why is this important
This is required for third party developers on iOS to verify device attestation.

### what is the sideffect if we decide to not accept this change into 1.0 branch or if we fail to finish its development?
Once commissioning starts, third party developers would not be able to reject attestation results, even if they have more verification information

### PR DESCRIPTION
**Pull request by jtung-apple**
#### Problem
Copying problem description from issue #22318:

The SDK currently allows an attestation delegate to override an attestation failure in response to user preference. The attestation delegate should also be able to override attestation success, in case application logic decides to stop commissioning a device.

For example, if the application keeps a more up-to-date revocation list, it can use that information to reject commissioning particular devices.

For this to work, the completion callback for the delegate should include DAC/PAI/CD for the device.

Edit for justification:
* why is this important
This is required for third party developers on iOS to verify device attestation.

* what is the sideffect if we decide to not accept this change into 1.0 branch or if we fail to finish its development?
Once commissioning starts, third party developers would not be able to reject attestation results, even if they have more verification information

/Edit

 #### Change overview
* Have `DeviceAttestationDelegate` add an optional override to use the new flow
* Add a new `AttestationDeviceInfo` object to hold a copy of the device information
* Have `DeviceCommissioner` check if the delegate uses the new flow, and always pass the device information
* Darwin: add an optional attestation completion callback for the objc delegate protocol

#### Testing
* Used darwin-framework-tool and verified the existing path still works
* Used chip-tool and verified existing path still works
* Tested locally with modified darwin-framework-tool that implements the new delegate callback

### CODE REVIEW

File: src/controller/CHIPDeviceController.cpp [hunk 1]
```diff
@@ -1040,15 +1041,22 @@ void DeviceCommissioner::OnDeviceAttestationInformationVerification(void * conte
     }
     else
     {
-        ChipLogProgress(Controller, "Successfully validated 'Attestation Information' command received from the device.");
-        commissioner->CommissioningStageComplete(CHIP_NO_ERROR);
+        if (deviceAttestationDelegate && deviceAttestationDelegate->ShouldWaitAfterDeviceAttestation())
```
Comment (anush-apple) [inline src/controller/CHIPDeviceController.cpp:1044]: This should probably a parameter on the commissioning delegate instead since it avoids anyone to have to implement the new virtual method and thereby go to existing behavior with no changes, unless the client wants to change it by setting the params

File: src/controller/CHIPDeviceController.cpp [hunk 2]
```diff
@@ -1083,13 +1092,29 @@ void DeviceCommissioner::OnFailedToExtendedArmFailSafeFailedDeviceAttestation(vo
...
 {
     mAttestationResult = result;
 
     auto & params                                                      = mDefaultCommissioner->GetCommissioningParameters();
     Credentials::DeviceAttestationDelegate * deviceAttestationDelegate = params.GetDeviceAttestationDelegate();
-    auto expiryLengthSeconds                                           = deviceAttestationDelegate->FailSafeExpiryTimeoutSecs();
+
+    if (deviceAttestationDelegate->ShouldWaitAfterDeviceAttestation())
+    {
+        mAttestationDeviceInfo = chip::Platform::New<Credentials::DeviceAttestationVerifier::AttestationDeviceInfo>(info);
```
Comment (anush-apple) [inline src/controller/CHIPDeviceController.cpp:1114]: clear before assigning?

File: src/controller/CommissioningDelegate.h [hunk 3]
```diff
@@ -414,6 +414,7 @@ class CommissioningParameters
     CompletionStatus completionStatus;
     Credentials::DeviceAttestationDelegate * mDeviceAttestationDelegate =
         nullptr; // Delegate to handle device attestation failures during commissioning
+    Optional<bool> mShouldWaitPostDeviceAttestation;
```
Comment (anush-apple) [inline src/controller/CommissioningDelegate.h:417]: Expose methods to set and get these?

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp [hunk 4]
```diff
@@ -111,5 +113,42 @@ void SetDeviceAttestationVerifier(DeviceAttestationVerifier * verifier)
     gDacVerifier = verifier;
 }
 
+ByteSpan DupByteSpanHelper(const ByteSpan & span_to_dup)
```
Comment (anush-apple) [inline src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp:116]: static inline?

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp [hunk 5]
```diff
@@ -111,5 +113,42 @@ void SetDeviceAttestationVerifier(DeviceAttestationVerifier * verifier)
...
+{
+    uint8_t * bytes = (uint8_t *) chip::Platform::MemoryAlloc(span_to_dup.size());
+    memcpy(bytes, span_to_dup.data(), span_to_dup.size());
+    return ByteSpan(bytes, span_to_dup.size());
+}
+
+DeviceAttestationVerifier::AttestationDeviceInfo::AttestationDeviceInfo(const AttestationInfo & attestationInfo) :
+    mPaiDerBuffer(DupByteSpanHelper(attestationInfo.paiDerBuffer)), mDacDerBuffer(DupByteSpanHelper(attestationInfo.dacDerBuffer))
+{
+    mAttestationElementsBufferCopy = chip::Platform::MemoryAlloc(attestationInfo.attestationElementsBuffer.size());
```
Comment (anush-apple) [inline src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp:126]: Seems like we don't really need to save this if the CD is the only thing we need to get of this? Perhaps just allocate space for the extracted CD?

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.h [hunk 6]
```diff
@@ -222,6 +220,25 @@ class DeviceAttestationVerifier
...
+    {
+    public:
+        AttestationDeviceInfo(const AttestationInfo & attestationInfo);
+        AttestationDeviceInfo(const ByteSpan & attestationElementsBuffer, const ByteSpan paiDerBuffer, const ByteSpan dacDerBuffer);
+
+        ~AttestationDeviceInfo();
+
+        ByteSpan mPaiDerBuffer;       // Buffer containing the PAI certificate from device in DER format.
+        ByteSpan mDacDerBuffer;       // Buffer containing the DAC certificate from device in DER format.
+        Optional<ByteSpan> mCdBuffer; // Buffer containing the certificate declaration from device.
```
Comment (anush-apple) [inline src/credentials/attestation_verifier/DeviceAttestationVerifier.h:234]: Seems like you don't want to provide direct access since these can be modified. Make these private and have inline getters?

File: src/darwin/CHIPTool/CHIPTool.xcodeproj/project.pbxproj [hunk 7]
```diff
@@ -565,7 +565,6 @@
 			buildSettings = {
 				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
 				CODE_SIGN_ENTITLEMENTS = CHIPTool/CHIPTool.entitlements;
-				CODE_SIGN_IDENTITY = "Apple Development";
```
Comment (anush-apple) [inline src/darwin/CHIPTool/CHIPTool.xcodeproj/project.pbxproj:568]: Revert file?

File: src/darwin/Framework/CHIP/MTRDeviceAttestationDelegate_Internal.h [hunk 8]
```diff
@@ -0,0 +1,33 @@
...
+NS_ASSUME_NONNULL_BEGIN
+
+@interface MTRDeviceAttestationDeviceInfo ()
+- (instancetype)initWithDACCertificate:(NSData *)dacCertificate
+                     dacPAICertificate:(NSData *)dacPAICertificate
+                certificateDeclaration:(NSData *)certificateDeclaration;
+
+//@property (nonatomic, readonly) NSData * dacCertificate;
+//@property (nonatomic, readonly) NSData * dacPAICertificate;
+//@property (nonatomic, readonly) NSData * certificateDeclaration;
```
Comment (anush-apple) [inline src/darwin/Framework/CHIP/MTRDeviceAttestationDelegate_Internal.h:29]: Delete?

File: src/darwin/CHIPTool/CHIPTool.xcodeproj/project.pbxproj (hunk 7 above)
Comment (jtung-apple) [reply src/darwin/CHIPTool/CHIPTool.xcodeproj/project.pbxproj:568]: Yeah this was accidental removal. I'll revert the file.

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp (hunk 5 above)
Comment (jtung-apple) [reply src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp:126]: Okay can certainly do that instead.

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.h (hunk 6 above)
Comment (jtung-apple) [reply src/credentials/attestation_verifier/DeviceAttestationVerifier.h:234]: @anush-apple How do you think that should look like?

File: src/controller/CHIPDeviceController.cpp (hunk 1 above)
Comment (jtung-apple) [reply src/controller/CHIPDeviceController.cpp:1044]: The virtual method has a default implementation that returns false, which makes this part use the existing behavior with no changes. Only delegate with new flow needs to override to return true.

Or am I misunderstanding what you mean here?

File: src/controller/CommissioningDelegate.h (hunk 3 above)
Comment (jtung-apple) [reply src/controller/CommissioningDelegate.h:417]: I actually meant to remove this entirely, because the ShouldWaitPostDeviceAttestation question is answered by the delegate object.

File: src/credentials/attestation_verifier/DeviceAttestationDelegate.h [hunk 9]
```diff
@@ -48,14 +48,29 @@ class DeviceAttestationDelegate
...
+    virtual void OnDeviceAttestationCompleted(Controller::DeviceCommissioner * deviceCommissioner, DeviceProxy * device,
+                                              const DeviceAttestationVerifier::AttestationDeviceInfo & info,
+                                              AttestationVerificationResult attestationResult) = 0;
+
+    /**
+     * @brief
+     *   Override this method to return whether the attestation delegate wants the commissioner to wait for a
+     *   ContinueCommissioningAfterDeviceAttestation call in the case attestationResult is successful.
+     */
+    virtual bool ShouldWaitAfterDeviceAttestation() { return false; };
```
Comment (anush-apple) [inline src/credentials/attestation_verifier/DeviceAttestationDelegate.h:73]:
```suggestion
    virtual bool ShouldWaitAfterDeviceAttestation() { return false; }
```

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.h (hunk 6 above)
Comment (anush-apple) [reply src/credentials/attestation_verifier/DeviceAttestationVerifier.h:234]: Make them private and then have:

ByteSpan paiDerBuffer() const  { return mPaiDerBuffer; }

File: src/darwin/Framework/CHIP/MTRDeviceAttestationDelegate.h [hunk 10]
```diff
@@ -21,12 +21,36 @@ NS_ASSUME_NONNULL_BEGIN
 
 @class MTRDeviceController;
 
+@interface MTRDeviceAttestationDeviceInfo : NSObject
+@property (nonatomic, readonly) NSData * dacCertificate;
+@property (nonatomic, readonly) NSData * dacPAICertificate;
+@property (nonatomic, readonly) NSData * certificateDeclaration;
```
Comment (anush-apple) [inline src/darwin/Framework/CHIP/MTRDeviceAttestationDelegate.h:27]: nullable?

File: src/darwin/Framework/CHIP/MTRDeviceAttestationDelegateBridge.mm [hunk 11]
```diff
@@ -17,17 +17,39 @@
...
+                                                            certificateDeclaration:cdData];
+                NSError * error = (attestationResult == chip::Credentials::AttestationVerificationResult::kSuccess)
+                    ? nil
+                    : [MTRError errorForCHIPErrorCode:CHIP_ERROR_INTEGRITY_CHECK_FAILED];
+                [strongDelegate deviceAttestation:mDeviceController
+                               completedForDevice:device
+                            attestationDeviceInfo:deviceInfo
+                                            error:error];
+            }
+        } else if ([strongDelegate respondsToSelector:@selector(deviceAttestation:failedForDevice:error:)]) {
```
Comment (anush-apple) [inline src/darwin/Framework/CHIP/MTRDeviceAttestationDelegateBridge.mm:52]: Check for attestationResult has to be failed before failed delegate is called

File: src/darwin/Framework/CHIP/MTRDeviceAttestationDelegate_Internal.h [hunk 12]
```diff
@@ -0,0 +1,28 @@
...
+ *    See the License for the specific language governing permissions and
+ *    limitations under the License.
+ */
+
+#import <MTRDeviceAttestationDelegate.h>
+
+NS_ASSUME_NONNULL_BEGIN
+
+@interface MTRDeviceAttestationDeviceInfo ()
+- (instancetype)initWithDACCertificate:(NSData *)dacCertificate
```
Comment (anush-apple) [inline src/darwin/Framework/CHIP/MTRDeviceAttestationDelegate_Internal.h:23]: init is unavailable ?

**Comment by andy31415** [comment]
@jtung-apple - this is a core code change. Please help me triage it for 1.0 acceptance by providing 1.0 justification:

- why is this important
- what is the sideffect if we decide to not accept this change into 1.0 branch or if we fail to finish its development?

**Comment by andy31415** [comment]
@jtung-apple - regarding `Used darwin-framework-tool to see that the existing path still works` - how about chip-tool?

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp [hunk 13]
```diff
@@ -111,5 +113,40 @@ void SetDeviceAttestationVerifier(DeviceAttestationVerifier * verifier)
     gDacVerifier = verifier;
 }
 
+static inline ByteSpan DupByteSpanHelper(const ByteSpan & span_to_dup)
+{
+    uint8_t * bytes = (uint8_t *) chip::Platform::MemoryAlloc(span_to_dup.size());
```
Comment (tcarmelveilleux) [inline src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp:118]: This is risky of a memory allocation scheme. Suggest more explicitly maintaining copies

File: src/controller/CHIPDeviceController.cpp [hunk 14]
```diff
@@ -1083,13 +1092,30 @@ void DeviceCommissioner::OnFailedToExtendedArmFailSafeFailedDeviceAttestation(vo
...
     mAttestationResult = result;
 
     auto & params                                                      = mDefaultCommissioner->GetCommissioningParameters();
     Credentials::DeviceAttestationDelegate * deviceAttestationDelegate = params.GetDeviceAttestationDelegate();
-    auto expiryLengthSeconds                                           = deviceAttestationDelegate->FailSafeExpiryTimeoutSecs();
+
+    if (deviceAttestationDelegate->ShouldWaitAfterDeviceAttestation())
+    {
+        ClearAttestationDeviceInfo();
+        mAttestationDeviceInfo = chip::Platform::New<Credentials::DeviceAttestationVerifier::AttestationDeviceInfo>(info);
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1115]: Might make sense to make `mAttestationDeviceInfo` a `Platform::UniquePtr` and use `Platform::MakeUnique` here...

File: src/credentials/attestation_verifier/DeviceAttestationDelegate.h [hunk 15]
```diff
@@ -48,14 +48,29 @@ class DeviceAttestationDelegate
     /**
      * @brief
      *   This method is invoked when device attestation fails for a device that is being commissioned. The client
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DeviceAttestationDelegate.h:50]: It can also be called on success now, no?  This should probably describe the actual semantics of when this is called (e.g. I don't obviously see it being called on attestation success if ShouldWaitAfterDeviceAttestation is false).

File: src/credentials/attestation_verifier/DeviceAttestationDelegate.h [hunk 16]
```diff
@@ -48,14 +48,29 @@ class DeviceAttestationDelegate
...
+     *
+     *   If ShouldWaitAfterDeviceAttestation returns false, then in the case attestationResult is successful, the
+     *   commissioner would finish commissioning the device after OnDeviceAttestationCompleted returns.
+     *
+     *   If ShouldWaitAfterDeviceAttestation returns true, then the commissioner will always wait for a
+     *   ContinueCommissioningAfterDeviceAttestation call after calling OnDeviceAttestationCompleted.
      *
      *   @param deviceCommissioner The commissioner object that is commissioning the device
      *   @param device The proxy represent the device being commissioned
+     *   @param info The structure holding device infor for additional verification by the application
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DeviceAttestationDelegate.h:61]:
```suggestion
     *   @param info The structure holding device info for additional verification by the application
```

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.h [hunk 17]
```diff
@@ -222,6 +220,23 @@ class DeviceAttestationVerifier
...
+    // Copies the bytes passed to it, and holds the PAI, DAC, and CD for additional verification step
+    class AttestationDeviceInfo
+    {
+    public:
+        AttestationDeviceInfo(const AttestationInfo & attestationInfo);
+        AttestationDeviceInfo(const ByteSpan & attestationElementsBuffer, const ByteSpan paiDerBuffer, const ByteSpan dacDerBuffer);
+
+        ~AttestationDeviceInfo();
+
+        ByteSpan mPaiDerBuffer;       // Buffer containing the PAI certificate from device in DER format.
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DeviceAttestationVerifier.h:232]: `ScopedMemoryBufferWithSize` might be somewhat safer here...

And if we need to add easy conversions from `ScopedMemoryBufferWithSize` to `Span`, we can do that too...

File: src/darwin/Framework/CHIP/MTRDeviceAttestationDelegate.h [hunk 18]
```diff
@@ -21,12 +21,36 @@ NS_ASSUME_NONNULL_BEGIN
...
  * The protocol definition for the MTRDeviceAttestationDelegate
  *
  * All delegate methods will be called on the callers queue.
  */
 @protocol MTRDeviceAttestationDelegate <NSObject>
+@optional
+/**
+ * Notify the delegate when device attestation completed with device info for additional verification. If
+ * this callback is implemented, continueCommissioningDevice on MTRDeviceController is expected
+ * to be called if commisioning should continue.
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDeviceAttestationDelegate.h:40]: Should probably document how this interacts with the failedForDevice: signature.  What will happen is this one will be called if implemented, right?  Otherwise the other will be, but only if attestation failed?

File: src/darwin/Framework/CHIP/MTRDeviceAttestationDelegateBridge.mm [hunk 19]
```diff
@@ -17,17 +17,39 @@
...
 
         mResult = attestationResult;
 
         id<MTRDeviceAttestationDelegate> strongDelegate = mDeviceAttestationDelegate;
-        if ([strongDelegate respondsToSelector:@selector(deviceAttestation:failedForDevice:error:)]) {
+        if ([strongDelegate respondsToSelector:@selector(deviceAttestation:completedForDevice:attestationDeviceInfo:error:)]) {
+            MTRDeviceController * strongController = mDeviceController;
+            if (strongController) {
+                NSData * dacData = [NSData dataWithBytes:info.mDacDerBuffer.data() length:info.mDacDerBuffer.size()];
+                NSData * paiData = [NSData dataWithBytes:info.mPaiDerBuffer.data() length:info.mPaiDerBuffer.size()];
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDeviceAttestationDelegateBridge.mm:36]: Please use our existing `AsData()` helper.

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp (hunk 13 above)
Comment (jtung-apple) [reply src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp:118]: Could you elaborate how you want the copies explicitly maintained?

File: src/credentials/attestation_verifier/DeviceAttestationDelegate.h (hunk 15 above)
Comment (jtung-apple) [reply src/credentials/attestation_verifier/DeviceAttestationDelegate.h:50]: I think perhaps my documentation is not clear enough. The original point of the attestation delegate is to handle the fail case, and override it with a call to Continue...

The new use case is to also call OnDeviceAttestationCompleted on success, if ShouldWaitAfterDeviceAttestation returns true.

File: src/darwin/Framework/CHIP/MTRDeviceAttestationDelegate.h (hunk 18 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDeviceAttestationDelegate.h:40]: I can document this more clearly - only one of these should be implemented, as only one will be called.

I would actually like to entirely remove the failed callback at least for Darwin, and always call the completed callback.

**Comment by jtung-apple** [comment]
> @jtung-apple - regarding `Used darwin-framework-tool to see that the existing path still works` - how about chip-tool?

@andy31415 I've also verified that chip-tool continues to commission correctly.

File: src/controller/CHIPDeviceController.cpp (hunk 1 above)
Comment (jtung-apple) [reply src/controller/CHIPDeviceController.cpp:1041]: This was resolved offline - the ShouldWaitAfterDeviceAttestation() mechanism keeps existing logic intact.

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.h (hunk 17 above)
Comment (jtung-apple) [reply src/credentials/attestation_verifier/DeviceAttestationVerifier.h]: Done

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp (hunk 13 above)
Comment (jtung-apple) [reply src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp]: This has been replaced with Boris's suggestion of using ScopedMemoryBufferWithSize and UniquePtr.

File: src/credentials/attestation_verifier/DeviceAttestationDelegate.h (hunk 16 above)
Comment (jtung-apple) [reply src/credentials/attestation_verifier/DeviceAttestationDelegate.h]: Corrected as part of a commit

**Comment by jtung-apple** [comment]
> @jtung-apple - this is a core code change. Please help me triage it for 1.0 acceptance by providing 1.0 justification:
> 
> * why is this important
> * what is the sideffect if we decide to not accept this change into 1.0 branch or if we fail to finish its development?

@andy31415

**Comment by jtung-apple** [comment]
> @jtung-apple - this is a core code change. Please help me triage it for 1.0 acceptance by providing 1.0 justification:
> 
> * why is this important
> * what is the sideffect if we decide to not accept this change into 1.0 branch or if we fail to finish its development?

@andy31415 
* why is this important
  This is required for third party developers on iOS to verify device attestation.

* what is the sideffect if we decide to not accept this change into 1.0 branch or if we fail to finish its development?
  Once commissioning starts, third party developers would not be able to reject attestation results, even if they have more verification information

File: src/darwin/Framework/CHIP/MTRDeviceAttestationDelegate.h (hunk 18 above)
Comment (jtung-apple) [reply src/darwin/Framework/CHIP/MTRDeviceAttestationDelegate.h:52]: I've documented this better. Please have a look!

**Comment by jtung-apple** [comment]
@andy31415 For bookkeeping - I've filed new Issue #22423 with template and copied justification over and linked to this PR.

File: src/controller/CHIPDeviceController.cpp [hunk 20]
```diff
@@ -1058,8 +1066,9 @@ void DeviceCommissioner::OnArmFailSafeExtendedForFailedDeviceAttestation(
     if (deviceAttestationDelegate)
     {
         ChipLogProgress(Controller, "Device attestation failed, delegating error handling to client");
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1068]: This log message should probably be adjusted.

File: src/controller/CHIPDeviceController.cpp [hunk 21]
```diff
@@ -1080,13 +1089,20 @@ void DeviceCommissioner::OnFailedToExtendedArmFailSafeFailedDeviceAttestation(vo
...
 {
     mAttestationResult = result;
 
     auto & params                                                      = mDefaultCommissioner->GetCommissioningParameters();
     Credentials::DeviceAttestationDelegate * deviceAttestationDelegate = params.GetDeviceAttestationDelegate();
-    auto expiryLengthSeconds                                           = deviceAttestationDelegate->FailSafeExpiryTimeoutSecs();
+
+    if (deviceAttestationDelegate->ShouldWaitAfterDeviceAttestation())
+    {
+        mAttestationDeviceInfo = Platform::MakeUnique<Credentials::DeviceAttestationVerifier::AttestationDeviceInfo>(info);
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1102]: Shouldn't this be unconditional?  We pass `*mAttestationDeviceInfo` unconditionally in `OnArmFailSafeExtendedForDeviceAttestation`.

File: src/controller/CHIPDeviceController.h [hunk 22]
```diff
@@ -715,7 +714,9 @@ class DLL_EXPORT DeviceCommissioner : public DeviceController,
     /* Callback when the previously sent CSR request results in failure */
     static void OnCSRFailureResponse(void * context, CHIP_ERROR error);
 
-    void ExtendArmFailSafeForFailedDeviceAttestation(Credentials::AttestationVerificationResult result);
+    void ClearAttestationDeviceInfo();
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.h:717]: This function doesn't seem to actually exist.

File: src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp [hunk 23]
```diff
@@ -111,5 +113,30 @@ void SetDeviceAttestationVerifier(DeviceAttestationVerifier * verifier)
     gDacVerifier = verifier;
 }
 
+static inline Platform::ScopedMemoryBufferWithSize<uint8_t> CopyByteSpanHelper(const ByteSpan & span_to_copy)
+{
+    Platform::ScopedMemoryBufferWithSize<uint8_t> bufferCopy;
+    bufferCopy.Alloc(span_to_copy.size());
+    memcpy(bufferCopy.Get(), span_to_copy.data(), span_to_copy.size());
```
Comment (bzbarsky-apple) [inline src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp:120]:
```suggestion
    if (bufferCopy.Alloc(span_to_copy.size()))
    {
        memcpy(bufferCopy.Get(), span_to_copy.data(), span_to_copy.size());
    }
```
And as a follow-up (separate PR) we should think about how to handle allocation failure here....

File: src/darwin/Framework/CHIP/MTRDeviceAttestationDelegateBridge.h [hunk 24]
```diff
@@ -53,6 +57,7 @@ class MTRDeviceAttestationDelegateBridge : public chip::Credentials::DeviceAttes
     id<MTRDeviceAttestationDelegate> mDeviceAttestationDelegate;
     dispatch_queue_t mQueue;
     chip::Optional<uint16_t> mExpiryTimeoutSecs;
+    bool mShouldWaitAfterDeviceAttestation;
```
Comment (bzbarsky-apple) [inline src/darwin/Framework/CHIP/MTRDeviceAttestationDelegateBridge.h:60]:
```suggestion
    const bool mShouldWaitAfterDeviceAttestation;
```

File: src/controller/CHIPDeviceController.h (hunk 22 above)
Comment (jtung-apple) [reply src/controller/CHIPDeviceController.h:717]: The implementation was removed when we changed to UniquePtr. I'll also remove this declaration.

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@jtung-apple thanks for the new issue template, approving.
