### PR TITLE
Fix bridge-app init

### LINKED ISSUE #15134: Commissioning over BLE and IP are failing on Bridge-app.
#### Problem
Pairing  DUT with chip-tool is failing on Bridge-app (CommitID - 6380d38f44c46f9e8f684024bf99c6a203622455) on Master Branch .
For both BLE and IP commissioning I am gacing this issue itself.
Screenshot of the issue:
image

Log:
[Bridge_app_failing.txt](https://github.com/project-chip/connectedhomeip/files/8059495/Bridge_app_failing.txt)

### PR DESCRIPTION
**Pull request by tcarmelveilleux**
#### Problem
- Bridge app did not have proper CommissionableDataProvider
  init and nobody caught it until some testing weeks later.

Fixes #15134

#### Change overview
- This PR adds the necessary init calls and also refactors
  elements of the bridge app structure to prevent this from
  happening again.

#### Testing
- All unit tests pass
- Cert tests pass
- chip-bridge-app works and is commissionablen by chip-tool and chip-repl

### CODE REVIEW

File: examples/platform/linux/CommissionableInit.cpp [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+#include <platform/TestOnlyCommissionableDataProvider.h>
+
+#include "CommissionableInit.h"
+
+namespace chip {
+namespace examples {
+
+using namespace chip::DeviceLayer;
+
+CHIP_ERROR InitCommissionableDataProvider(LinuxCommissionableDataProvider & provider, LinuxDeviceOptions & options)
```
Comment (tcarmelveilleux) [inline examples/platform/linux/CommissionableInit.cpp:31]: This entire file is just moved code from `platform/linux/AppMain.cpp`

**Review by andy31415 — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
