### PR TITLE
SoftwareDiagnostics::Watermark support based on implementation flags

### LINKED ISSUE #19160: [pre-sve] DGSW-2.3 Reset Watermarks failed
#### Problem
all cluster app
nrf52840
revision: 425f1fb916ca154deeb75cd82cd5196778aba152

Since the device has a feature map set to 1 (means support Watermarks), the device should support current-heap-high-watermark attribute and reset-watermarks command.
The above command on all cluster app fail.

```
[1654259355.980153][76571:76576] CHIP:DMG: ICR moving to [ResponseRe]
[1654259355.980167][76571:76576] CHIP:DMG: InvokeResponseMessage =
[1654259355.980171][76571:76576] CHIP:DMG: {
[1654259355.980175][76571:76576] CHIP:DMG: 	suppressResponse = false, 
[1654259355.980179][76571:76576] CHIP:DMG: 	InvokeResponseIBs =
[1654259355.980186][76571:76576] CHIP:DMG: 	[
[1654259355.980189][76571:76576] CHIP:DMG: 		InvokeResponseIB =
[1654259355.980196][76571:76576] CHIP:DMG: 		{
[1654259355.980200][76571:76576] CHIP:DMG: 			CommandStatusIB =
[1654259355.980205][76571:76576] CHIP:DMG: 			{
[1654259355.980208][76571:76576] CHIP:DMG: 				CommandPathIB =
[1654259355.980215][76571:76576] CHIP:DMG: 				{
[1654259355.980220][76571:76576] CHIP:DMG: 					EndpointId = 0x0,
[1654259355.980227][76571:76576] CHIP:DMG: 					ClusterId = 0x34,
[1654259355.980231][76571:76576] CHIP:DMG: 					CommandId = 0x0,
[1654259355.980235][76571:76576] CHIP:DMG: 				},
[1654259355.980240][76571:76576] CHIP:DMG: 				
[1654259355.980246][76571:76576] CHIP:DMG: 				StatusIB =
[1654259355.980250][76571:76576] CHIP:DMG: 				{
[1654259355.980254][76571:76576] CHIP:DMG: 					status = 0x01 (FAILURE),
[1654259355.980258][76571:76576] CHIP:DMG: 				},
[1654259355.980262][76571:76576] CHIP:DMG: 				
[1654259355.980266][76571:76576] CHIP:DMG: 			},
[1654259355.980271][76571:76576] CHIP:DMG: 			
[1654259355.980274][76571:76576] CHIP:DMG: 		},
[1654259355.980281][76571:76576] CHIP:DMG: 		
[1654259355.980286][76571:76576] CHIP:DMG: 	],
[1654259355.980292][76571:76576] CHIP:DMG: 	
[1654259355.980295][76571:76576] CHIP:DMG: 	InteractionModelRevision = 1
```

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
Not all platforms support ResetWatermark, but we always claim they do.

#### Change overview
- add the featuremap for software diagnostics as a codegen item
- make the diagnostics impl class return a `watermark supported` bool, override it to true for efr32, linux and darwin
- make the impl of the cluster set the feature flags based on the `supported` flag

Fixes #19160 

#### Testing
Flashed NRF all clusters app, observed feature map  0.
Flashed EFR32 light app, observed feature map 1 (and reset-watermarks returns success).

Script used:

```sh
#!/usr/bin/env bash

set -ex

function finish {
  echo "STATUS: $?"
}

trap finish EXIT

export NODEID=$RANDOM

export THREAD_CRED=hex:ADD_YOUR_CREDENTIALS_HERE
export CHIP_TOOL="$HOME/devel/connectedhomeip/out/linux-x64-chip-tool/chip-tool"

log_file="run_log_$(date +'%Y-%m-%d_%H-%M-%S').txt"
rm -f /tmp/chip_*

echo "NODE ID USED: $NODEID" | tee $log_file

echo "=============================================================" >>$log_file
echo $CHIP_TOOL pairing ble-thread $NODEID $THREAD_CRED 20202021 3840 | tee -a $log_file
$CHIP_TOOL pairing ble-thread $NODEID $THREAD_CRED 20202021 3840 >>$log_file 2>&1

echo "=============================================================" >>$log_file
echo $CHIP_TOOL softwarediagnostics read feature-map $NODEID 0 | tee -a $log_file
$CHIP_TOOL softwarediagnostics read feature-map $NODEID 0  2>&1 | tee -a $log_file | grep 'FeatureMap:'

echo "=============================================================" >>$log_file
echo $CHIP_TOOL softwarediagnostics read current-heap-high-watermark $NODEID 0 | tee -a $log_file
$CHIP_TOOL softwarediagnostics read current-heap-high-watermark $NODEID 0  2>&1 | tee -a $log_file | grep 'CurrentHeapHighWatermark:'

echo "=============================================================" >>$log_file
echo $CHIP_TOOL softwarediagnostics reset-watermarks $NODEID 0 | tee -a $log_file
$CHIP_TOOL softwarediagnostics reset-watermarks $NODEID 0  2>&1 | tee -a $log_file | grep -A 3 'StatusIB'
```

### CODE REVIEW

File: src/app/clusters/software-diagnostics-server/software-diagnostics-server.cpp [hunk 1]
```diff
@@ -63,22 +63,27 @@ CHIP_ERROR SoftwareDiagosticsAttrAccess::Read(const ConcreteReadAttributePath &
...
         return ReadThreadMetrics(aEncoder);
+    case Clusters::Globals::Attributes::FeatureMap::Id: {
+        BitFlags<SoftwareDiagnosticsFeature> features;
+
+        if (DeviceLayer::GetDiagnosticDataProvider().SupportsWatermarks())
+        {
+            features.Set(SoftwareDiagnosticsFeature::kWaterMarks);
+        }
+
+        return aEncoder.Encode(features);
```
Comment (bzbarsky-apple) [inline src/app/clusters/software-diagnostics-server/software-diagnostics-server.cpp:82]: Please add this to the `attributeAccessInterfaceAttributes` in `src/app/zap-templates/zcl/zcl.json` (right next to "ThreadMetrics" there), so we can hopefully stop allocating RAM for it.

**Review by bzbarsky-apple — APPROVED** [review]

File: src/app/clusters/software-diagnostics-server/software-diagnostics-server.cpp (hunk 1 above)
Comment (andy31415) [reply src/app/clusters/software-diagnostics-server/software-diagnostics-server.cpp:82]: added featuremap to that list. Ran zap regen though and saw no differences in output.

**Review by mrjerryjohns — APPROVED** [review]
