### PR TITLE
Make FabricIndex be a common thing across all sessions.

### LINKED ISSUE #13396: Use of GetFabricIndex was broken in session handle refactor
#### Problem
#13330 replaced code like this:
```
    return mpExchangeCtx->GetSessionHandle().GetFabricIndex();
```

with code like this:
```
    return mpExchangeCtx->GetSessionHandle()->AsSecureSession()->GetFabricIndex();
```

at a large number of callsites.

Unfortunately, the latter will crash if the session is a group session, whereas the former worked correctly in that case.

 #### Proposed Solution
Fix things so we don't crash if someone groupcasts a command that cares about the fabric index.  In practice this probably means moving mFabricIndex up to `Session`, having it initialized to 0 for `UnauthenticatedSession`, initializing it correctly for group and secure sessions, and implementing `GetFabricIndex` on `Session`.  Or is there a reason that can't happen?

@kghost @andreilitvin @msandstedt

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
Fabric index getting is often required for all session types, including group and secure sessions.
Having separation requires special handling between session types and the existing code of `AsSecureSession()->GetFabricIndex()` would crash for group sessions.

#### Change overview
Move fabric index to common code (Session.h) and use it from Secure and Group session.

fixes #13396

#### Testing
Flashed a devkit-c and commissioned it with chip-tool running the changed code.

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

File: src/app/CommandHandler.cpp [hunk 1]
```diff
@@ -573,7 +573,7 @@ FabricIndex CommandHandler::GetAccessingFabricIndex() const
     }
     else
     {
-        fabric = mpExchangeCtx->GetSessionHandle()->AsSecureSession()->GetFabricIndex();
+        fabric = mpExchangeCtx->GetSessionHandle()->GetFabricIndex();
```
Comment (bzbarsky-apple) [inline src/app/CommandHandler.cpp:576]: Please remove the branching here, since it's not neeed anymore.  This whole function should be:
```
  return mpExchangeCtx->GetSessionHandle()->GetFabricIndex();
```

File: src/app/WriteHandler.cpp [hunk 2]
```diff
@@ -486,7 +486,7 @@ FabricIndex WriteHandler::GetAccessingFabricIndex() const
     }
     else
     {
-        fabric = mpExchangeCtx->GetSessionHandle()->AsSecureSession()->GetFabricIndex();
+        fabric = mpExchangeCtx->GetSessionHandle()->GetFabricIndex();
```
Comment (bzbarsky-apple) [inline src/app/WriteHandler.cpp:489]: Again, please remove the now-unnecessary branching here.  This whole function should be:
```
  return mpExchangeCtx->GetSessionHandle()->GetFabricIndex();
```

File: src/transport/Session.h [hunk 3]
```diff
@@ -33,6 +34,10 @@ class Session
 public:
     virtual ~Session() {}
 
+    static constexpr FabricIndex kInvalidFabricIndex = 0;
```
Comment (bzbarsky-apple) [inline src/transport/Session.h:37]: Please put this in FabricTable.h, with the other fabric index constants.

**Review by bzbarsky-apple — APPROVED** [review]
Thank you for doing this!
