### PR TITLE
Change mrp-parameter-struct to hold 32-bit milliseconds

### LINKED ISSUE #17812: Secure session establishment can fail if local MRP parameters cannot fit within 16 bits
#### Problem

Nodes can exchange MRP parameters during CASE/PASE handshake with the mrp-parameter-struct, which encloses active and idle retry times as 16-bit values.

However, maximum bounds for these are 360,000 milliseconds.  It appears that when populating these, the pairing session code will simply fail.  The implication is that long MRP intervals can likely break PASE and CASE at this location in the code:

https://github.com/project-chip/connectedhomeip/blob/master/src/transport/PairingSession.cpp#L62

 #### Proposed Solution

* consider saturating values for placement in mrp-parameter-struct if local values don't fit
* or consider not sending these if they can't fit - sending is optional
* however, we shouldn't fail secure session establishment as we do now for values that overflow

### PR DESCRIPTION
**Pull request by msandstedt**
#### Problem

Nodes store and advertise MRP parameters as 32-bit values.  However,
the mrp-parameter-struct had been specified to only hold 16-bit values
on the wire.  This would lead to session establishment failures with
nodes attempting to exchange values in excess of 65536 milliseconds,
despite the fact that values up to 360,000 milliseconds are legal.

#### Change overview

This corrects the problem to allow up-to 32-bit values per the spec
change here:

https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/5173

In most cases, peers will be using smaller MRP values and and will
therefore still exchange 1 or 2-byte fields on the wire, making this
change mostly backward compatible.

Fixes #17812

#### Testing

Testing: verification of successful exchange of larger MRP values up
to 360,000 has been added to TestCASESession.cpp.  TestTxtFields.cpp
already has coverage for advertisement of large values.

### CODE REVIEW

File: src/transport/PairingSession.cpp [hunk 1]
```diff
@@ -81,7 +78,7 @@ CHIP_ERROR PairingSession::DecodeMRPParametersIfPresent(TLV::Tag expectedTag, TL
     TLV::TLVType containerType = TLV::kTLVType_Structure;
     ReturnErrorOnFailure(tlvReader.EnterContainer(containerType));
 
-    uint16_t tlvElementValue = 0;
+    uint32_t tlvElementValue = 0;
```
Comment (tcarmelveilleux) [inline src/transport/PairingSession.cpp:81]: This PR is OK, but please check your submodule updates did by mistake. Adding comment here because I can't comment on those lines

**Review by tcarmelveilleux — APPROVED** [review]

File: src/protocols/secure_channel/tests/TestCASESession.cpp [hunk 2]
```diff
@@ -258,6 +258,10 @@ void CASE_SecurePairingHandshakeTestCommon(nlTestSuite * inSuite, void * inConte
     // Test all combinations of invalid parameters
     TestCASESecurePairingDelegate delegateAccessory;
     CASESession pairingAccessory;
+    ReliableMessageProtocolConfig verySleepAccessoryRmpConfig(System::Clock::Milliseconds32(360000),
```
Comment (bzbarsky-apple) [inline src/protocols/secure_channel/tests/TestCASESession.cpp:261]:
```suggestion
    ReliableMessageProtocolConfig verySleepyAccessoryRmpConfig(System::Clock::Milliseconds32(360000),
```

**Review by bzbarsky-apple — APPROVED** [review]

File: src/transport/PairingSession.cpp (hunk 1 above)
Comment (msandstedt) [reply src/transport/PairingSession.cpp:81]: Done.

File: src/protocols/secure_channel/tests/TestCASESession.cpp (hunk 2 above)
Comment (msandstedt) [reply src/protocols/secure_channel/tests/TestCASESession.cpp:261]: Done.
