### PR TITLE
[op-creds] Fix RemoveFabric on Sleepy End Devices

### LINKED ISSUE #15910: TC-MF-1.17 SDK code crashes
#### Problem
During TC-MF-1.17 execution our device crashed. 

[backtrace.txt](https://github.com/project-chip/connectedhomeip/files/8198163/bt.txt)
[log.txt](https://github.com/project-chip/connectedhomeip/files/8198165/log.txt)

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
RemoveFabric command sent for the current fabric crashes on Sleepy End Devices because UpdateSEDPollingMode() method,
used to switch between fast and slow polling mode, references a session object that is released by the command.

#### Change overview
Add a check for the session state.
By the way, remove a debug `printf()`.
Fixes #15910

#### Testing
Sent `RemoveFabric` command with the current fabric as an argument and tested that the application doesn't crash.

### CODE REVIEW

**Review by LuDuda — APPROVED** [review]

**Review by ghost — APPROVED** [review]

File: src/messaging/ExchangeContext.cpp [hunk 1]
```diff
@@ -88,6 +88,7 @@ void ExchangeContext::SetResponseTimeout(Timeout timeout)
 void ExchangeContext::UpdateSEDPollingMode()
 {
     Transport::PeerAddress address;
+    VerifyOrReturn(mSession);
```
Comment (tcarmelveilleux) [inline src/messaging/ExchangeContext.cpp:91]:
```suggestion
    VerifyOrReturn(mSession != nullptr);
```

**Review by tcarmelveilleux — APPROVED** [review]

File: src/messaging/ExchangeContext.cpp (hunk 1 above)
Comment (bzbarsky-apple) [inline src/messaging/ExchangeContext.cpp:91]:
```suggestion
    VerifyOrReturn(HasSessionHandle());
```

Comment (bzbarsky-apple) [reply src/messaging/ExchangeContext.cpp:91]: mSession is not a pointer, though...

**Review by bzbarsky-apple — APPROVED** [review]

File: src/messaging/ExchangeContext.cpp (hunk 1 above)
Comment (bzbarsky-apple) [inline src/messaging/ExchangeContext.cpp:91]: But actually... if we have no session handle, shouldn't we in fact call `UpdateSEDPollingMode(false)`?  Otherwise it seems like we'll be stuck in polling fast-poll mode?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/messaging/ExchangeContext.cpp (hunk 1 above)
Comment (Damian-Nordic) [reply src/messaging/ExchangeContext.cpp:91]: We have a safety mechanism in `~ExchangeContext()` to always release the fast-polling mode request.

Comment (Damian-Nordic) [reply src/messaging/ExchangeContext.cpp]: Ok, I believed that MRP would still continue to work even after the session deletion, but it appears it would not, so there's not point in keeping the fast-polling mode. I added code to release it here.

**Review by bzbarsky-apple — APPROVED** [review]
