### PR TITLE
Fix command timeouts during commissioning.

### LINKED ISSUE #19135: Pairing of M5 board via CHIPTool cli throws Timeout error
With SHA 6c4b54ec544cf748180c1e32a41f6e4b1b34b7fe

M5 board cannot be paired via chiptool cli.

**Steps to reproduce the issue;**

Note: Ensure that M5 board is connected and flashed

1. cd ~/connectedhomeip
2. git reset --hard 6c4b54ec544cf748180c1e32a41f6e4b1b34b7fe
3. source scripts/bootstrap.sh
4. source scripts/activate.sh
5. gn gen out/debug --args='chip_mdns="platform" chip_crypto="mbedtls" chip_inet_config_enable_ipv4=false'
6. ninja -C out/debug
7. sudo ./out/debug/chip-tool pairing ble-wifi 4 "<wifi name>" <password> 20202021 3840 --paa-trust-store-path ./credentials/development/paa-root-certs

**Error:**

[1654206140364] [89910:2429897] CHIP: [EM] OnMessageReceived failed, err = ../../src/messaging/ExchangeMgr.cpp:265: CHIP Error 0x00000070: Unsolicited msg with originator bit clear
[1654206140421] [89910:2429898] CHIP: [EM] Received message of type 0x9 with protocolId (0, 1) and MessageCounter:205648405 on exchange 43505i
[1654206140421] [89910:2429898] CHIP: [EM] Found matching exchange: 43505i, Delegate: 0x7fcd34004250
[1654206140421] [89910:2429898] CHIP: [DMG] ICR moving to [ResponseRe]
[1654206140421] [89910:2429898] CHIP: [DMG] InvokeResponseMessage =
[1654206140421] [89910:2429898] CHIP: [DMG] {
[1654206140421] [89910:2429898] CHIP: [DMG] 	suppressResponse = false, 
[1654206140421] [89910:2429898] CHIP: [DMG] 	InvokeResponseIBs =
[1654206140421] [89910:2429898] CHIP: [DMG] 	[
[1654206140421] [89910:2429898] CHIP: [DMG] 		InvokeResponseIB =
[1654206140421] [89910:2429898] CHIP: [DMG] 		{
[1654206140421] [89910:2429898] CHIP: [DMG] 			CommandDataIB =
[1654206140421] [89910:2429898] CHIP: [DMG] 			{
[1654206140421] [89910:2429898] CHIP: [DMG] 				CommandPathIB =
[1654206140421] [89910:2429898] CHIP: [DMG] 				{
[1654206140421] [89910:2429898] CHIP: [DMG] 					EndpointId = 0x0,
[1654206140421] [89910:2429898] CHIP: [DMG] 					ClusterId = 0x30,
[1654206140421] [89910:2429898] CHIP: [DMG] 					CommandId = 0x1,
[1654206140421] [89910:2429898] CHIP: [DMG] 				},
[1654206140421] [89910:2429898] CHIP: [DMG] 				
[1654206140421] [89910:2429898] CHIP: [DMG] 				CommandFields = 
[1654206140421] [89910:2429898] CHIP: [DMG] 				{
[1654206140421] [89910:2429898] CHIP: [DMG] 					0x0 = 0, 
[1654206140421] [89910:2429898] CHIP: [DMG] 					0x1 = "", 
[1654206140421] [89910:2429898] CHIP: [DMG] 				},
[1654206140421] [89910:2429898] CHIP: [DMG] 			},
[1654206140421] [89910:2429898] CHIP: [DMG] 			
[1654206140421] [89910:2429898] CHIP: [DMG] 		},
[1654206140421] [89910:2429898] CHIP: [DMG] 		
[1654206140421] [89910:2429898] CHIP: [DMG] 	],
[1654206140421] [89910:2429898] CHIP: [DMG] 	
[1654206140421] [89910:2429898] CHIP: [DMG] 	InteractionModelRevision = 1
[1654206140421] [89910:2429898] CHIP: [DMG] },
[1654206140422] [89910:2429898] CHIP: [DMG] Received Command Response Data, Endpoint=0 Cluster=0x0000_0030 Command=0x0000_0001
[1654206140422] [89910:2429898] CHIP: [CTL] Failsafe disarmed
[1654206140422] [89910:2429898] CHIP: [CTL] Successfully finished commissioning step 'Cleanup'
[1654206140422] [89910:2429898] CHIP: [TOO] Device commissioning Failure: ../../src/app/CommandSender.cpp:211: CHIP Error 0x00000032: Timeout
[1654206140422] [89910:2429898] CHIP: [DIS] Closing all BLE connections
[1654206140422] [89910:2429898] CHIP: [IN] Clearing BLE pending packets.
[1654206140422] [89910:2429898] CHIP: [BLE] Auto-closing end point's BLE connection.
[1654206140422] [89910:2429898] CHIP: [DMG] ICR moving to [AwaitingDe]
[1654206140422] [89910:2429893] CHIP: [CTL] Shutting down the commissioner
[1654206140422] [89910:2429893] CHIP: [CTL] Shutting down the controller
[1654206140422] [89910:2429893] CHIP: [CTL] Shutting down the commissioner
[1654206140423] [89910:2429893] CHIP: [CTL] Shutting down the controller
[1654206140423] [89910:2429893] CHIP: [IN] Expiring all connections for fabric 1!!
[1654206140423] [89910:2429893] CHIP: [CTL] Shutting down the commissioner
[1654206140423] [89910:2429893] CHIP: [CTL] Shutting down the controller
[1654206140423] [89910:2429893] CHIP: [IN] Expiring all connections for fabric 2!!
[1654206140423] [89910:2429893] CHIP: [CTL] Shutting down the commissioner
[1654206140423] [89910:2429893] CHIP: [CTL] Shutting down the controller
[1654206140423] [89910:2429893] CHIP: [IN] Expiring all connections for fabric 3!!
[1654206140423] [89910:2429893] CHIP: [CTL] Shutting down the System State, this will teardown the CHIP Stack
[1654206140423] [89910:2429893] CHIP: [DMG] IM WH moving to [Uninitialized]
[1654206140423] [89910:2429893] CHIP: [DMG] IM WH moving to [Uninitialized]
[1654206140423] [89910:2429893] CHIP: [DMG] IM WH moving to [Uninitialized]
[1654206140423] [89910:2429893] CHIP: [DMG] IM WH moving to [Uninitialized]
[1654206140423] [89910:2429893] CHIP: [DMG] All ReadHandler-s are clean, clear GlobalDirtySet
[1654206140423] [89910:2429893] CHIP: [BLE] CancelConnection
[1654206140423] [89910:2429893] CHIP: [DL] Inet Layer shutdown
[1654206140423] [89910:2429893] CHIP: [DL] BLE shutdown
[1654206140423] [89910:2429893] CHIP: [DL] System Layer shutdown
[1654206140423] [89910:2429893] CHIP: [IN] SecureSession Released 0x7fcd32482a80 Type:1 LSID:10578
[1654206140423] [89910:2429893] CHIP: [TOO] Run command failure: ../../src/app/CommandSender.cpp:211: CHIP Error 0x00000032: Timeout

**Attaching the complete log file;**

[M5-cli-error-log.txt](https://github.com/project-chip/connectedhomeip/files/8828094/M5-cli-error-log.txt)

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Several fixes here:

1. AutoCommissioner has a comment about how per spec everything during
   commissioning needs at least a 30s timeout, and it was passing that to
   PerformCommissioningStep, but DeviceCommissioner was ignoring the "timeout"
   parameter for a bunch of the cases, including crucially for AddNOC and
   CSRRequest.  Those can take a while to run, and were hitting the
   now-much-lower default 2s timeout.  The fix here is to stop ignoring the
   passed-in value.

2. The passed-in timeout value computation in AutoCommissioner was not quite
   right.  It was set to max(30s, network-connect-time), but the network connect
   time is the processing time on the server, not the total time including
   transport latency.  Fix the computation of the timeout to:
   a. Take the network connect times for the network enable steps, a "slow
      crypto" time of 15s for the AddNOC and CSRRequest steps, and the default
      IM timeout for all other steps and treat that as the server processing
      time.
   b. Add the transport timeout bits from our device's session to that server
      processing time.
   c. If the result is less than the spec-mandated 30s timeout, use 30s,
      otherwise use the result we computed.

3. Assuming that BLE has 0 transport latency is wrong.  Not clear what the right
   value is, but for now setting it to the same as TCP.

Fixes https://github.com/project-chip/connectedhomeip/issues/19135

#### Problem
See above.

#### Change overview
See above.

#### Testing
Verified via logging that sane timeout values are computed, and checked that BLE commissioning of an M5Stack in fact works now.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

File: src/controller/AutoCommissioner.cpp [hunk 1]
```diff
@@ -288,29 +289,56 @@ CHIP_ERROR AutoCommissioner::StartCommissioning(DeviceCommissioner * commissione
...
 {
-    // Per spec, all commands that are sent with the arm failsafe held need at least a 30s timeout.
-    // Network clusters can indicate the time required to connect, so if we are connecting, use that time as long as it is > 30s.
-    app::Clusters::NetworkCommissioning::Attributes::ConnectMaxTimeSeconds::TypeInfo::DecodableType seconds = 30;
+    // Network clusters can indicate the time required to connect, so if we are
+    // connecting, use that time as our "how long it takes to process server
+    // side" time.  Otherwise pick a time that should be enough for the command
+    // processing: 15s for slow steps the can involve crypto, the default IM
+    // timeout otherwise.
+    // TODO: is this a reasonable estimate for the slow-crypto cases?
```
Comment (tcarmelveilleux) [inline src/controller/AutoCommissioner.cpp:303]: This is overly conservative. I would set it to 5-7

File: src/transport/SecureSession.h [hunk 2]
```diff
@@ -161,6 +161,10 @@ class SecureSession : public Session, public ReferenceCounted<SecureSession, Sec
             return GetMRPConfig().mIdleRetransTimeout * (CHIP_CONFIG_RMP_DEFAULT_MAX_RETRANS + 1);
         case Transport::Type::kTcp:
             return System::Clock::Seconds16(30);
+        case Transport::Type::kBle:
+            // TODO: Figure out what this should be, but zero is not the right
+            // answer.
+            return System::Clock::Seconds16(30);
```
Comment (tcarmelveilleux) [inline src/transport/SecureSession.h:167]: 30 is too long. Please use 5 for now, and it can likely be trimmed down to a bit less even

Comment (andy31415) [reply src/transport/SecureSession.h:167]: What is the sideffect of setting this too high? I imagine we time out slower, however for BLE this is commissioning only, so the difference would be "failed to commission" in 5 seconds vs 30. Would it be acceptable to just make it "very long" just in case?

Comment (bzbarsky-apple) [reply src/transport/SecureSession.h:167]: Alright.  Set to 5, and I'm doing some looking into what a not-just-guessed-at value would be.

File: src/controller/AutoCommissioner.cpp [hunk 3]
```diff
@@ -288,29 +289,56 @@ CHIP_ERROR AutoCommissioner::StartCommissioning(DeviceCommissioner * commissione
...
-Optional<System::Clock::Timeout> AutoCommissioner::GetCommandTimeout(CommissioningStage stage) const
+Optional<System::Clock::Timeout> AutoCommissioner::GetCommandTimeout(DeviceProxy * device, CommissioningStage stage) const
 {
-    // Per spec, all commands that are sent with the arm failsafe held need at least a 30s timeout.
-    // Network clusters can indicate the time required to connect, so if we are connecting, use that time as long as it is > 30s.
-    app::Clusters::NetworkCommissioning::Attributes::ConnectMaxTimeSeconds::TypeInfo::DecodableType seconds = 30;
+    // Network clusters can indicate the time required to connect, so if we are
+    // connecting, use that time as our "how long it takes to process server
+    // side" time.  Otherwise pick a time that should be enough for the command
+    // processing: 7s for slow steps the can involve crypto, the default IM
```
Comment (msandstedt) [inline src/controller/AutoCommissioner.cpp:301]:
```suggestion
    // processing: 7s for slow steps that can involve crypto, the default IM
```

**Review by msandstedt — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

File: src/controller/AutoCommissioner.cpp (hunk 3 above)
Comment (bzbarsky-apple) [reply src/controller/AutoCommissioner.cpp]: Good catch, done.

File: src/transport/SecureSession.h (hunk 2 above)
Comment (bzbarsky-apple) [reply src/transport/SecureSession.h]: @andy31415 The side-effect of setting it too high is mostly that we end up taking longer to detect timeout when a device just doesn't respond to the "join network" command.  I think that's the main place where this value actually ends up mattering in practice.
