### PR TITLE
[Scenes] MaxCapacity fix

### LINKED ISSUE #31955: [1.3] - TC-S-2.6 - Test failed
### Reproduction steps

**1. Commission DUT to TH1**

 Executed the below mentioned command to put DUT into a commissionable state
`./chip-all-clusters-app
`
Once DUT reach the commissionable state sent below mentioned command on Chip-tool.
`./chip-tool pairing onnetwork 1 20202021
`
After the successful commissioning with TH1

**2. Commission DUT to TH2**

`./chip-tool  pairing open-commissioning-window 1 1 400 2000 3841
`
> [1657186324.710951][10820:10825] CHIP:DMG: Received Command Response Status for Endpoint=0 Cluster=0x0000_003C Command=0x0000_0000 Status=0x0
> [1657186324.710980][10820:10825] CHIP:CTL: Successfully opened pairing window On TH(Chiptool)e device
> [1657186324.711048][10820:10825] CHIP:CTL: Manual pairing code: [36253605617]
> [1657186324.711108][10820:10825] CHIP:CTL: SetupQRCode: [MT:-24J0IRV01A7TB7E700]

**Now send the below command for commissioning DUT to TH2 with Manual pairing code generated in TH1 .**

`./chip-tool pairing code 2 36253605617 --commissioner-name beta
`
Verify the commissioning completed with success on TH2(chip-tool) from DUT

> [1657186359.584672][3509:3514] CHIP:CTL: Successfully finished commissioning step 'Cleanup'
> [1657186359.584743][3509:3514] CHIP:TOO: Device commissioning completed with success

**3. Commission DUT to  TH3.**

Open a commissioning window On TH1(Chiptool)using below command 

`./chip-tool  pairing open-commissioning-window 1 1 400 2000 3842
`
> [1701254594.851779][10096:10098] CHIP:DMG: Received Command Response Status for Endpoint=0 Cluster=0x0000_003C Command=0x0000_0000 Status=0x0
> [1701254594.851783][10096:10098] CHIP:CTL: Successfully opened pairing window on the device
> [1701254594.851789][10096:10098] CHIP:CTL: Manual pairing code: [36545248276]
> [1701254594.851795][10096:10098] CHIP:CTL: SetupQRCode: [MT:-24J0Q1212K4.08JP10]

**send the below command for commissionin DUT to TH3 with Manual pairing code generated in TH1 using open commission window**

`./chip-tool pairing code 3 36545248276 --commissioner-name gamma
`
Verify the commissioning completed with success on TH3(chip-tool) from DUT

> [1657186359.584672][3509:3514] CHIP:CTL: Successfully finished commissioning step 'Cleanup'
> [1657186359.584743][3509:3514] CHIP:TOO: Device commissioning completed with success

**After the successful commissioning with TH1, TH2, TH3, Send the below mentioned commands**

1. Please use Interactive mode to Verify the subscription 
  Here the command to enter interactive mode:--   
`./chip-tool interactive start    
`

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

4c4d8bfc90e0c345ad3f0cf61220067ad31b0391

### Platform

raspi

### Platform Version(s)

1.3

### Anything else?

1. As per the specification, the Scene Table capacity for a given fabric SHALL be less than half (rounded down towards 0) of the total Scene Table entries. The total Scene Table capacity for all the fabrics is 16. For each fabric, the maximum capacity is calculated as follows:
[Max Capacity for each fabric = (Scene Table entries -1)/2 = 16-1/2 = 7].

I attempted to add scenes in three different fabrics. Initially, I added scenes to the first and second fabrics until their respective maximum capacities were reached. 

Once the scenes have been added to two different fabrics until their maximum capacities are reached, the remaining capacity of the Scene Table in the third fabric should be 2. However, the current state of the SDK indicates a remaining capacity of 7 for the third fabric. Therefore, the SDK requires updating to reflect the correct remaining capacity according to the specifications
 
2. If a scene cannot be copied due to the lack of Scene Table capacity for the given fabric, the status SHALL be RESOURCE_EXHAUSTED for Copy Scene Command. However, currently, the status is reported as Failure. The SDK needs to be updated accordingly.

3. If a scene cannot be created due to the lack of Scene Table capacity for the given fabric, the status SHALL be RESOURCE_EXHAUSTED for StoreScene command. but currently the status is reported as Failure. The SDK needs to be updated accordingly

**Specification References:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/Scenes.adoc#94-viewscene-command

**Test Plan References:**
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/scenes.adoc

 **Log References:**
[TC-S-2.6(DUT).txt](https://github.com/project-chip/connectedhomeip/files/14179820/TC-S-2.6.DUT.txt)
[TC-S-2.6(TH1).txt](https://github.com/project-chip/connectedhomeip/files/14179822/TC-S-2.6.TH1.txt)
[TC-S-2.6(TH2).txt](https://github.com/project-chip/connectedhomeip/files/14179824/TC-S-2.6.TH2.txt)
[TC-S-2.6(TH3).txt](https://github.com/project-chip/connectedhomeip/files/14179829/TC-S-2.6.TH3.txt)

### PR DESCRIPTION
**Pull request by lpbeliveau-silabs**
Added refresh on read to the FabricSceneInfo capacity 
Patched Resource Exhausted for Copy Scene and Store Scene (proper mapping of CHIP->IMStatus errors is still needed)
Added a MaxCapacity yaml test to confirm everything works as expected.

Fixes: https://github.com/project-chip/connectedhomeip/issues/31955

### CODE REVIEW

**Review by jmartinez-silabs — APPROVED** [review]

File: src/app/clusters/scenes-server/scenes-server.cpp [hunk 1]
```diff
@@ -917,12 +928,10 @@ void ScenesServer::HandleStoreScene(HandlerContext & ctx, const Commands::StoreS
     CHIP_ERROR err = StoreSceneParse(ctx.mCommandHandler.GetAccessingFabricIndex(), ctx.mRequestPath.mEndpointId, req.groupID,
                                      req.sceneID, mGroupProvider);
 
-    if (CHIP_NO_ERROR == err)
-    {
-        ReturnOnFailure(UpdateLastConfiguredBy(ctx, response));
-    }
+    VerifyOrReturn(CHIP_NO_ERROR == AddResponseOnError(ctx, response, err));
```
Comment (andy31415) [inline src/app/clusters/scenes-server/scenes-server.cpp:931]: Given that you use `ReturnOnFailure` below, should this maybe also be `ReturnOnFailure(AddResponseOnError(ctx, response, err));` ?

File: src/app/clusters/scenes-server/scenes-server.cpp [hunk 2]
```diff
@@ -1061,13 +1070,13 @@ void ScenesServer::HandleCopyScene(HandlerContext & ctx, const Commands::CopySce
...
-        // Update SceneInfoStruct Attributes
-        ReturnOnFailure(
-            AddResponseOnError(ctx, response,
-                               UpdateFabricSceneInfo(ctx.mRequestPath.mEndpointId, ctx.mCommandHandler.GetAccessingFabricIndex(),
-                                                     Optional<GroupId>(), Optional<SceneId>(), Optional<bool>())));
+            // Update SceneInfoStruct Attributes after each insert in case we hit max capacity in the middle of the loop
+            ReturnOnFailure(AddResponseOnError(ctx, response,
+                                               UpdateFabricSceneInfo(ctx.mRequestPath.mEndpointId,
+                                                                     ctx.mCommandHandler.GetAccessingFabricIndex(),
+                                                                     Optional<GroupId>(), Optional<SceneId>(), Optional<bool>())));
```
Comment (andy31415) [inline src/app/clusters/scenes-server/scenes-server.cpp:1078]: please add a `/* = name*` for the bool as bools are not obvious what they represent. I can see that the group and scene are missing ... what is the bool?

**Review by andy31415 — APPROVED** [review]
