### PR TITLE
[EFR32] Add support for TestEventTrigger on Silabs

### LINKED ISSUE #27455: [EFR32] Need to add support for TestEventTrigger on Silabs
### Reproduction steps

The TestEventTrigger is not enabled on Silabs platform.

### Platform

efr32

### Platform Version(s)

_No response_

### Type

Platform validated

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ericzijian1994**
Fixes #27455

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

File: examples/platform/silabs/SiWx917/matter_config.cpp [hunk 1]
```diff
@@ -79,6 +82,51 @@ void SilabsMatterConfig::ConnectivityEventCallback(const ChipDeviceEvent * event
...
+        return 10 + hex - 'a';
+    }
+    if ('0' <= hex && hex <= '9')
+    {
+        return hex - '0';
+    }
+    return -1;
+}
+
+static size_t hex_string_to_binary(const char * hex_string, uint8_t * buf, size_t buf_size)
```
Comment (bzbarsky-apple) [inline examples/platform/silabs/SiWx917/matter_config.cpp:107]: This is reinventing code the SDK already has, for what it's worth @ericzijian1994 .  That's bad in an example that you expect applications to follow...

File: examples/platform/silabs/SilabsTestEventTriggerDelegate.h [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+     * @return True or False.
+     */
+    bool DoesEnableKeyMatch(const ByteSpan & enableKey) const override;
+
+    /**
+     * @brief User handler for handling the test event trigger based on `eventTrigger` provided.
+     * @param eventTrigger Event trigger to handle.
+     * @return CHIP_NO_ERROR on success or another CHIP_ERROR on failure.
+     */
+    CHIP_ERROR HandleEventTrigger(uint64_t eventTrigger) override;
```
Comment (bzbarsky-apple) [inline examples/platform/silabs/SilabsTestEventTriggerDelegate.h:42]: This override is not actually implemented.  How is this supposed to work?

File: examples/platform/silabs/efr32/matter_config.cpp [hunk 3]
```diff
@@ -133,6 +135,51 @@ void SilabsMatterConfig::ConnectivityEventCallback(const ChipDeviceEvent * event
...
+        return 10 + hex - 'a';
+    }
+    if ('0' <= hex && hex <= '9')
+    {
+        return hex - '0';
+    }
+    return -1;
+}
+
+static size_t hex_string_to_binary(const char * hex_string, uint8_t * buf, size_t buf_size)
```
Comment (bzbarsky-apple) [inline examples/platform/silabs/efr32/matter_config.cpp:160]: Again, this is code that already exists in the SDK.
