### PR TITLE
Fix TimeSnapshot command and add TC-DGGEN-2.4

### LINKED ISSUE #30096: [1.3 TCR] Implement TimeSnapshot command and associated tests
The TimeSnapshot command was added in 1.3. This needs to be implemented in the SDK.

- [ ] Implement TimeSnapshot
- [ ] Add new tests based on test plan
- [ ] Add new presubmit test

### PR DESCRIPTION
**Pull request by tcarmelveilleux**
- Fix the TimeSnapshot command to actually work properly.
- Add the TC-DGGEN-2.4 test (matching fixes in https://github.com/CHIP-Specifications/chip-test-plans/pull/3759)
- Make TC-DGGEN-2.4 run in CI.

Fixes #30096 
Issue #31177

Testing done:
- Tested against all-clusters-app --> With timesync, TC-DGGEN-2.4 step 3 used instead of step 4
- Tested against lighting-app --> No timesync, TC-DGGEN-2.4 step 4 used instead of step 3

### CODE REVIEW

**Comment by yunhanw-google** [comment]
it seems we also need to update lighting-app for your change?
 gn --root=scripts/build/../.. gen --check --fail-on-unused-args out/debug '--args=target_os="all"chip_build_tests=false chip_enable_wifi=false chip_im_force_fabric_quota_check=true enable_default_builds=false enable_host_gcc_build=true enable_standalone_chip_tool_build=true enable_linux_all_clusters_app_build=true enable_linux_lighting_app_build=true'
Environment looks good, you are ready to go!

Build: GN configure
ERROR at //src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:21:11: Include not allowed.
#include "app/clusters/time-synchronization-server/time-synchronization-server.h"
          ^---------------------------------------------------------------------
It is not in any dependency of
  //examples/lighting-app/lighting-common:lighting-common
The include file is in the target(s):

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 1]
```diff
@@ -385,9 +392,42 @@ bool emberAfGeneralDiagnosticsClusterTestEventTriggerCallback(CommandHandler * c
...
+
+    System::Clock::Microseconds64 posix_time_us{ 0 };
+
+#ifdef TIME_SYNCHRONIZATION_CLUSTER_INCLUDED
+#ifdef ZCL_USING_TIME_SYNCHRONIZATION_CLUSTER_SERVER
+    bool time_is_synced = false;
+    using Clusters::TimeSynchronization::GranularityEnum;
+    GranularityEnum granularity = Clusters::TimeSynchronization::TimeSynchronizationServer::Instance().GetGranularity();
+    time_is_synced              = (granularity == GranularityEnum::kSecondsGranularity) ||
+        (granularity == GranularityEnum::kMillisecondsGranularity) || (granularity == GranularityEnum::kMicrosecondsGranularity);
```
Comment (bzbarsky-apple) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:407]: This might be better as a switch statement, so if a new granularity value is added the compiler will catch the missing case...

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 2]
```diff
@@ -192,7 +197,9 @@ CHIP_ERROR GeneralDiagosticsAttrAccess::Read(const ConcreteReadAttributePath & a
         return ReadIfSupported(&DiagnosticDataProvider::GetRebootCount, aEncoder);
     }
     case UpTime::Id: {
-        return ReadIfSupported(&DiagnosticDataProvider::GetUpTime, aEncoder);
+        System::Clock::Seconds64 system_time_seconds =
```
Comment (bzbarsky-apple) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:200]: This and other places where we duration_cast _might_ be a good use of `auto`.   Hard to say for sure.

File: src/python_testing/TC_DGGEN_2_4.py
Comment (bzbarsky-apple) [inline src/python_testing/TC_DGGEN_2_4.py:1]: I did not carefully review the tests.

File: src/app/chip_data_model.gni [hunk 3]
```diff
@@ -272,8 +272,10 @@ template("chip_data_model") {
           "${_app_root}/clusters/${cluster}/DefaultTimeSyncDelegate.cpp",
           "${_app_root}/clusters/${cluster}/TimeSyncDataProvider.cpp",
         ]
-        defines +=
-            [ "TIME_SYNC_ENABLE_TSC_FEATURE=${time_sync_enable_tsc_feature}" ]
+        defines += [
+          "TIME_SYNC_ENABLE_TSC_FEATURE=${time_sync_enable_tsc_feature}",
+          "TIME_SYNCHRONIZATION_CLUSTER_INCLUDED=1",
```
Comment (cecille) [inline src/app/chip_data_model.gni:277]: I think ZCL_USING_TIME_SYNCHRONIZATION_CLUSTER_SERVER should work here rather than an additional define. It's in gen_config.h, but it's generated at compile, so you won't find it in the repo.

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp [hunk 4]
```diff
@@ -385,9 +392,42 @@ bool emberAfGeneralDiagnosticsClusterTestEventTriggerCallback(CommandHandler * c
...
+
+    Commands::TimeSnapshotResponse::Type response;
+
+    System::Clock::Microseconds64 posix_time_us{ 0 };
+
+#ifdef TIME_SYNCHRONIZATION_CLUSTER_INCLUDED
+#ifdef ZCL_USING_TIME_SYNCHRONIZATION_CLUSTER_SERVER
+    bool time_is_synced = false;
+    using Clusters::TimeSynchronization::GranularityEnum;
+    GranularityEnum granularity = Clusters::TimeSynchronization::TimeSynchronizationServer::Instance().GetGranularity();
```
Comment (cecille) [inline src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:405]: I'm guessing that minutes is omitted here because you don't trust it. If that's true, would you mind just adding a comment to indicate that?

File: src/python_testing/TC_DGGEN_2_4.py [hunk 5]
```diff
@@ -0,0 +1,192 @@
...
+        cluster = Clusters.Objects.TimeSynchronization
+        return await self.read_single_attribute_check_success(endpoint=0, cluster=cluster, attribute=attribute)
+
+    async def set_time_in_timesync(self, current_time: int):
+        endpoint = 0
+        time_cluster = Clusters.Objects.TimeSynchronization
+        code = 0
+
+        try:
+            await self.send_single_cmd(cmd=time_cluster.Commands.SetUTCTime(UTCTime=current_time, granularity=time_cluster.Enums.GranularityEnum.kSecondsGranularity), endpoint=endpoint)
```
Comment (cecille) [inline src/python_testing/TC_DGGEN_2_4.py:46]:
```suggestion
            await self.send_single_cmd(cmd=time_cluster.Commands.SetUTCTime(UTCTime=current_time, granularity=time_cluster.Enums.GranularityEnum.kMillisecondsGranularity), endpoint=endpoint)
```
^ explanation: that's the controller granularity, if you send in seconds, the device might not trust your time.

Comment (cecille) [reply src/python_testing/TC_DGGEN_2_4.py:46]: That's going to need a test plan change too, though.

File: src/python_testing/TC_DGGEN_2_4.py [hunk 6]
```diff
@@ -0,0 +1,192 @@
...
+        has_timesync = (Clusters.TimeSynchronization.id in root_server_list)
+
+        testvar_TimeSyncSupported = False
+
+        if has_timesync:
+            ts_attributes = await self.read_single_attribute(self.default_controller, node_id=self.dut_node_id, endpoint=0, attribute=Clusters.TimeSynchronization.Attributes.AttributeList)
+            has_utc_time = (Clusters.TimeSynchronization.Attributes.UTCTime.attribute_id in ts_attributes)
+
+            if has_utc_time:
+                testvar_TimeSyncSupported = True
```
Comment (cecille) [inline src/python_testing/TC_DGGEN_2_4.py:82]: This matches the test plan, but I'm not sure it's correct there either. If you don't set the time before reading the UTC time attribute, then you're not guaranteed to have a non-null time. Then below, you won't go on to set the time. 

ie, I think step 3a should be moved up to before step 1, with a pre-check for the presence of the cluster.

**Review by cecille — APPROVED** [review]
LGTM once the comments are addressed.

File: src/python_testing/TC_DGGEN_2_4.py (hunk 5 above)
Comment (tcarmelveilleux) [reply src/python_testing/TC_DGGEN_2_4.py:46]: Will follow-up once testplan is fixed.

File: src/python_testing/TC_DGGEN_2_4.py (hunk 6 above)
Comment (tcarmelveilleux) [reply src/python_testing/TC_DGGEN_2_4.py:82]: Will follow-up once testplan is fixed.

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp (hunk 4 above)
Comment (tcarmelveilleux) [reply src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:405]: Done

File: src/app/chip_data_model.gni (hunk 3 above)
Comment (tcarmelveilleux) [reply src/app/chip_data_model.gni:277]: Removed. It was a leftover from a prior attempt.

File: src/python_testing/TC_DGGEN_2_4.py
Comment (tcarmelveilleux) [reply src/python_testing/TC_DGGEN_2_4.py:1]: ACK.

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp (hunk 2 above)
Comment (tcarmelveilleux) [reply src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:200]: Prefer to use the correct unit explicitly rather than auto. If really important will do as a follow-up.

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp (hunk 1 above)
Comment (tcarmelveilleux) [reply src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:407]: Done.

File: src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp (hunk 2 above)
Comment (bzbarsky-apple) [reply src/app/clusters/general-diagnostics-server/general-diagnostics-server.cpp:202]: Like I said: hard to say for sure.  On the one hand, it repeats the type that's right there in the cast.  On the other, it ensures we have the right type.  I'm fine either way here.

**Review by bzbarsky-apple — APPROVED** [review]
