### PR TITLE
Address testing feedback from opcert callbacks, and re-commissioning

### LINKED ISSUE #22419: [1.0] attestation elements and signature are not available during opcert signing
### Reproduction steps

```bash
1.Configure Android ChipDeviceController for opcert signing callback
2.AttestationElements and Signature object are often corrupted since these are not deep copied into the CommissioningParameters object (so the memory is freed after the AttestationValidation step). 
3.The AttestationElements and Signature objects provided to the opcert signing callback are often corrupted
```

### Bug prevalence

Memory corruption if often

### GitHub hash of the SDK that was being used

master

### Platform

android

### Platform Version(s)

_No response_

### Type

Core SDK Memory Issue

### Anything else?

_No response_

### LINKED ISSUE #22421: [1.0] Commissioning an already-on-fabric device fails without useful information for commissioner
### Reproduction steps

```bash
1.Commission device with Admin A
2.Commission device with Admin B
3.Put device into commissioning mode via Admin B, pass resulting setup code to Admin A
4.Admin A does not know that this setup code is for a device it already administers and so attempts commissioning.
5.Commissioning fails at AddNoc step (fabric exists)
6.Admin A can conclude that it already controls this device, but doesn't know which device it is (doesn't know nodeId)

The fix for this should be for the commissioning flow to read existing fabrics during the initial steps so that Admin A can determine the device's nodeId up front and then avoid the AddNoc error.
```

### Bug prevalence

weekly

### GitHub hash of the SDK that was being used

master

### Platform

core

### Platform Version(s)

_No response_

### Type

Core SDK Interopability Issue

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chrisdecenzo**
#### Problem
* Bugs found during testing of new external opcert signing - https://github.com/project-chip/connectedhomeip/issues/22419
* Bug when attempting to commission an already commissioned device - https://github.com/project-chip/connectedhomeip/issues/22421

#### Change overview
* Fix typo on JNI callback lookup
* Persist attestation elements and signature so they are available during opcert signing
* Read fabric list during attribute read step of commissioning and persist the nodeId if the device is already on the commissioners fabric.
* Add code in tv-app and content-app platform to handle the already-on-fabric case
* Fixes #22419
* Fixes #22421

#### Testing
* Tested on Android
* Tested on linux tv-casting-app and tv-app

### CODE REVIEW

**Review by sharadb-amazon — APPROVED** [review]

File: src/controller/AutoCommissioner.cpp [hunk 1]
```diff
@@ -502,9 +502,41 @@ CHIP_ERROR AutoCommissioner::CommissioningStepFinished(CHIP_ERROR err, Commissio
...
+            else
+            {
+                memcpy(mAttestationSignature, report.Get<AttestationResponse>().signature.data(),
+                       report.Get<AttestationResponse>().signature.size());
+                mParams.SetAttestationSignature(
+                    ByteSpan(mAttestationSignature, report.Get<AttestationResponse>().signature.size()));
+            }
+            // ? These don't need to be deep copied to local memory because they are used in this one step then never again.
+            // mParams.SetAttestationElements(report.Get<AttestationResponse>().attestationElements)
+            //     .SetAttestationSignature(report.Get<AttestationResponse>().signature);
```
Comment (tcarmelveilleux) [inline src/controller/AutoCommissioner.cpp:538]: Do you mean to have this remain?

File: src/controller/AutoCommissioner.h [hunk 2]
```diff
@@ -23,6 +23,9 @@
 namespace chip {
 namespace Controller {
 
+constexpr size_t kAttestationElementsLength  = 900;
```
Comment (tcarmelveilleux) [inline src/controller/AutoCommissioner.h:26]: Can you please repace this one with:
```
// As per specifications section 11.22.5.1. Constant RESP_MAX
constexpr size_t kMaxRspLen = 900;
```
^^^ src/app/clusters/operational-credentials-server/operational-credentials-server.cpp

We should move this constant in `src/credentials/DeviceAttestationConstructor.h` most likely, and it would allow reuse here and in op creds cluster and in src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp/DacOnlyPartialAttestationVerifier.cpp

File: src/controller/AutoCommissioner.h [hunk 3]
```diff
@@ -23,6 +23,9 @@
...
+constexpr size_t kAttestationSignatureLength = 64;
```
Comment (tcarmelveilleux) [inline src/controller/AutoCommissioner.h:27]: This is `chip::Crypto::kMax_ECDSA_Signature_Length` from CHIPCryptoPAL.h, please use that instead

File: src/controller/AutoCommissioner.cpp [hunk 4]
```diff
@@ -502,9 +502,41 @@ CHIP_ERROR AutoCommissioner::CommissioningStepFinished(CHIP_ERROR err, Commissio
             SetDAC(report.Get<RequestedCertificate>().certificate);
             break;
         case CommissioningStage::kSendAttestationRequest:
-            // These don't need to be deep copied to local memory because they are used in this one step then never again.
-            mParams.SetAttestationElements(report.Get<AttestationResponse>().attestationElements)
-                .SetAttestationSignature(report.Get<AttestationResponse>().signature);
+            if (report.Get<AttestationResponse>().attestationElements.size() > kAttestationElementsLength)
```
Comment (bzbarsky-apple) [inline src/controller/AutoCommissioner.cpp:505]:
```suggestion
            if (report.Get<AttestationResponse>().attestationElements.size() > sizeof(mAttestationElements))
```
since that's what the code guarded by this `if` really cares about, right?

Comment (bzbarsky-apple) [reply src/controller/AutoCommissioner.cpp:505]: Also, this code would be a _lot_ more readable with something like:
```
auto & elements = report.Get<AttestationResponse>().attestationElements;
```
or so....

File: src/controller/AutoCommissioner.cpp [hunk 5]
```diff
@@ -502,9 +502,41 @@ CHIP_ERROR AutoCommissioner::CommissioningStepFinished(CHIP_ERROR err, Commissio
...
+            }
+            else
+            {
+                memcpy(mAttestationElements, report.Get<AttestationResponse>().attestationElements.data(),
+                       report.Get<AttestationResponse>().attestationElements.size());
+                mParams.SetAttestationElements(
+                    ByteSpan(mAttestationElements, report.Get<AttestationResponse>().attestationElements.size()));
+            }
+
+            if (report.Get<AttestationResponse>().signature.size() > kAttestationSignatureLength)
```
Comment (bzbarsky-apple) [inline src/controller/AutoCommissioner.cpp:520]:
```suggestion
            if (report.Get<AttestationResponse>().signature.size() > sizeof(mAttestationSignature))
```

File: src/controller/AutoCommissioner.cpp [hunk 6]
```diff
@@ -502,9 +502,41 @@ CHIP_ERROR AutoCommissioner::CommissioningStepFinished(CHIP_ERROR err, Commissio
...
             break;
         case CommissioningStage::kSendAttestationRequest:
-            // These don't need to be deep copied to local memory because they are used in this one step then never again.
-            mParams.SetAttestationElements(report.Get<AttestationResponse>().attestationElements)
-                .SetAttestationSignature(report.Get<AttestationResponse>().signature);
+            if (report.Get<AttestationResponse>().attestationElements.size() > kAttestationElementsLength)
+            {
+                ChipLogError(Controller, "AutoCommissioner attestationElements buffer size %d larger than cache size %d",
+                             static_cast<int>(report.Get<AttestationResponse>().attestationElements.size()),
+                             static_cast<int>(kAttestationElementsLength));
```
Comment (bzbarsky-apple) [inline src/controller/AutoCommissioner.cpp:509]: Please use `%u` and cast to `unsigned`, so we don't have unsigned-to-signed casts where we don't need them.

File: src/controller/AutoCommissioner.cpp [hunk 7]
```diff
@@ -502,9 +502,41 @@ CHIP_ERROR AutoCommissioner::CommissioningStepFinished(CHIP_ERROR err, Commissio
...
+                    ByteSpan(mAttestationElements, report.Get<AttestationResponse>().attestationElements.size()));
+            }
+
+            if (report.Get<AttestationResponse>().signature.size() > kAttestationSignatureLength)
+            {
+                ChipLogError(Controller,
+                             "AutoCommissioner attestationSignature buffer size %d larger than "
+                             "cache size %d",
+                             static_cast<int>(report.Get<AttestationResponse>().signature.size()),
+                             static_cast<int>(kAttestationSignatureLength));
```
Comment (bzbarsky-apple) [inline src/controller/AutoCommissioner.cpp:526]: Again, please cast to unsigned and use `%u`.

File: src/controller/AutoCommissioner.cpp [hunk 8]
```diff
@@ -502,9 +502,41 @@ CHIP_ERROR AutoCommissioner::CommissioningStepFinished(CHIP_ERROR err, Commissio
...
+                mParams.SetAttestationSignature(report.Get<AttestationResponse>().signature);
+            }
+            else
+            {
+                memcpy(mAttestationSignature, report.Get<AttestationResponse>().signature.data(),
+                       report.Get<AttestationResponse>().signature.size());
+                mParams.SetAttestationSignature(
+                    ByteSpan(mAttestationSignature, report.Get<AttestationResponse>().signature.size()));
+            }
+            // ? These don't need to be deep copied to local memory because they are used in this one step then never again.
```
Comment (bzbarsky-apple) [inline src/controller/AutoCommissioner.cpp:536]: This comment should go away.

File: src/controller/AutoCommissioner.cpp [hunk 9]
```diff
@@ -502,9 +502,41 @@ CHIP_ERROR AutoCommissioner::CommissioningStepFinished(CHIP_ERROR err, Commissio
...
         case CommissioningStage::kSendAttestationRequest:
-            // These don't need to be deep copied to local memory because they are used in this one step then never again.
-            mParams.SetAttestationElements(report.Get<AttestationResponse>().attestationElements)
-                .SetAttestationSignature(report.Get<AttestationResponse>().signature);
+            if (report.Get<AttestationResponse>().attestationElements.size() > kAttestationElementsLength)
+            {
+                ChipLogError(Controller, "AutoCommissioner attestationElements buffer size %d larger than cache size %d",
+                             static_cast<int>(report.Get<AttestationResponse>().attestationElements.size()),
+                             static_cast<int>(kAttestationElementsLength));
+                mParams.SetAttestationElements(report.Get<AttestationResponse>().attestationElements);
```
Comment (bzbarsky-apple) [inline src/controller/AutoCommissioner.cpp:510]: But in this case we keep using the ByteSpan that points to some temporary memory... how is a consumer expected to know when it's safe to use the span and when it's not?

Seems like we should just error out when the size is not what we expected.....  And something somewhere needs to document how long it's ok to keep using the spans in mParams, though I guess "until the next commissioning starts" might be clear enough.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/controller/AutoCommissioner.cpp (hunk 1 above)
Comment (chrisdecenzo) [reply src/controller/AutoCommissioner.cpp]: I removed this comment and added a warning in CommissioningDelegate.h for the GetAttestationX() methods:

> Warning: data is not deep copied to local memory and can only be read during PerformCommissioningStep.

File: examples/platform/linux/CommissionerMain.cpp [hunk 10]
```diff
@@ -110,14 +113,50 @@ class MyCommissionerCallback : public CommissionerCallback
     }
 };
 
+AutoCommissioner gAutoCommissioner;
+
+class MyCredsIssuer : public ExampleOperationalCredentialsIssuer
```
Comment (tcarmelveilleux) [inline examples/platform/linux/CommissionerMain.cpp:118]: `MyCreds` is not a good name. Please use a better more descriptive name.

File: examples/platform/linux/CommissionerMain.cpp [hunk 11]
```diff
@@ -110,14 +113,50 @@ class MyCommissionerCallback : public CommissionerCallback
...
+{
+    CHIP_ERROR GenerateNOCChain(const ByteSpan & csrElements, const ByteSpan & csrNonce, const ByteSpan & attestationSignature,
+                                const ByteSpan & attestationChallenge, const ByteSpan & DAC, const ByteSpan & PAI,
+                                Callback::Callback<OnNOCChainGeneration> * onCompletion) override
+    {
+        ChipLogError(Controller, "---------------------------MyCredsIssuer ");
+        // add parsing here
```
Comment (tcarmelveilleux) [inline examples/platform/linux/CommissionerMain.cpp:125]: This looks like leftover debug

File: examples/platform/linux/CommissionerMain.cpp [hunk 12]
```diff
@@ -150,6 +190,9 @@ CHIP_ERROR InitCommissioner(uint16_t commissionerPort, uint16_t udcListenPort)
     const Credentials::AttestationTrustStore * testingRootStore = Credentials::GetTestAttestationTrustStore();
     SetDeviceAttestationVerifier(GetDefaultDACVerifier(testingRootStore));
 
+    // Uncomment the following line to perform DAC verification during NOC chain generation
+    // SetDeviceAttestationVerifier(&gPartialDACVerifier);
```
Comment (tcarmelveilleux) [inline examples/platform/linux/CommissionerMain.cpp:194]: This requires forking common code. Could this not be enabled/disabled with a dynamic setter?

File: examples/platform/linux/CommissionerMain.cpp [hunk 13]
```diff
@@ -110,14 +113,50 @@ class MyCommissionerCallback : public CommissionerCallback
...
 CommissionerDiscoveryController gCommissionerDiscoveryController;
 MyCommissionerCallback gCommissionerCallback;
 MyServerStorageDelegate gServerStorage;
-ExampleOperationalCredentialsIssuer gOpCredsIssuer;
+MyCredsIssuer gOpCredsIssuer;
 NodeId gLocalId = kMaxOperationalNodeId;
 Credentials::GroupDataProviderImpl gGroupDataProvider;
-AutoCommissioner gAutoCommissioner;
+Credentials::PartialDACVerifier gPartialDACVerifier;
+FabricId gFabricId = 1;
```
Comment (tcarmelveilleux) [inline examples/platform/linux/CommissionerMain.cpp:159]: This likely does not belong globally. Suggest using a constant

File: src/app/app-platform/ContentAppPlatform.cpp [hunk 14]
```diff
@@ -455,6 +455,61 @@ uint32_t ContentAppPlatform::GetPincodeFromContentApp(uint16_t vendorId, uint16_
     return (uint32_t) strtol(pinString.c_str(), &eptr, 10);
 }
 
+// Returns ACL entry with match subject or CHIP_ERROR_NOT_FOUND if no match is found
+CHIP_ERROR ContentAppPlatform::GetACLEntryIndex(size_t * foundIndex, FabricIndex fabricIndex, NodeId subjectNodeId)
```
Comment (tcarmelveilleux) [inline src/app/app-platform/ContentAppPlatform.cpp:459]: What is this used for?

File: src/app/app-platform/ContentAppPlatform.cpp [hunk 15]
```diff
@@ -482,12 +537,30 @@ CHIP_ERROR ContentAppPlatform::ManageClientAccess(Messaging::ExchangeManager & e
 
     Access::Privilege vendorPrivilege = mContentAppFactory->GetVendorPrivilege(targetVendorId);
 
+    NodeId subjectNodeId    = sessionHandle->GetPeer().GetNodeId();
+    FabricIndex fabricIndex = sessionHandle->GetFabricIndex();
+
+    // first, delete existing ACLs for this nodeId
```
Comment (tcarmelveilleux) [inline src/app/app-platform/ContentAppPlatform.cpp:543]: This runtime mutates the ACL. This seems to fall outside the scope of this PR about "opcert callbacks" and 'recommissioning"

Also, this is a node deciding to grant privileges on its own without an existing admininistrator's knowledge/control. Can you explain how this came to be?

File: src/controller/AutoCommissioner.cpp [hunk 16]
```diff
@@ -502,9 +511,43 @@ CHIP_ERROR AutoCommissioner::CommissioningStepFinished(CHIP_ERROR err, Commissio
             SetDAC(report.Get<RequestedCertificate>().certificate);
             break;
         case CommissioningStage::kSendAttestationRequest:
-            // These don't need to be deep copied to local memory because they are used in this one step then never again.
-            mParams.SetAttestationElements(report.Get<AttestationResponse>().attestationElements)
-                .SetAttestationSignature(report.Get<AttestationResponse>().signature);
+            if (report.Get<AttestationResponse>().attestationElements.size() > kAttestationElementsLength)
+            {
+                ChipLogError(Controller, "AutoCommissioner attestationElements buffer size %d larger than cache size %d",
```
Comment (tcarmelveilleux) [inline src/controller/AutoCommissioner.cpp:516]: Are you using this code to detect something? I think in a working system this should never occur

File: src/controller/AutoCommissioner.cpp [hunk 17]
```diff
@@ -502,9 +511,43 @@ CHIP_ERROR AutoCommissioner::CommissioningStepFinished(CHIP_ERROR err, Commissio
...
+                             static_cast<int>(report.Get<AttestationResponse>().attestationElements.size()),
+                             static_cast<int>(kAttestationElementsLength));
+                mParams.SetAttestationElements(report.Get<AttestationResponse>().attestationElements);
+            }
+            else
+            {
+                memcpy(mAttestationElements, report.Get<AttestationResponse>().attestationElements.data(),
```
Comment (tcarmelveilleux) [inline src/controller/AutoCommissioner.cpp:523]: Why not simply use a vector altogether for the mAttestationElements? It keeps its size and is trivially copyable/assignable

File: src/controller/CHIPDeviceController.cpp [hunk 18]
```diff
@@ -1733,6 +1733,45 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
...
+                    this->mAttributeCache->Get<app::Clusters::OperationalCredentials::Attributes::Fabrics::TypeInfo>(path,
+                                                                                                                     fabrics));
+                auto iter = fabrics.begin();
+                while (iter.Next())
+                {
+                    auto & fabricDescriptor = iter.GetValue();
+                    ChipLogProgress(AppServer,
+                                    "DeviceCommissioner::OnDone - fabric.vendorId=0x%04X fabric.fabricId=0x" ChipLogFormatX64
+                                    " fabric.nodeId=0x" ChipLogFormatX64,
+                                    fabricDescriptor.vendorId, ChipLogValueX64(fabricDescriptor.fabricId),
```
Comment (tcarmelveilleux) [inline src/controller/CHIPDeviceController.cpp:1759]: What is all this code for? It's really not clear what is attempted here, and for what. Also, this expects synchronous-like operation, and in common code.

File: src/controller/CommissioningDelegate.h [hunk 19]
```diff
@@ -177,11 +177,13 @@ class CommissioningParameters
     // Attestation elements from the node. These are obtained from node in response to the AttestationRequest command. In the
     // AutoCommissioner, this is automatically set from the report from the kSendAttestationRequest stage.
     // This must be set before calling PerformCommissioningStep for the kAttestationVerification step.
+    // Warning: data is not deep copied to local memory and can only be read during PerformCommissioningStep.
```
Comment (tcarmelveilleux) [inline src/controller/CommissioningDelegate.h:180]: You are deep copying it now

File: src/controller/java/AndroidOperationalCredentialsIssuer.cpp [hunk 20]
```diff
@@ -219,17 +221,19 @@ CHIP_ERROR AndroidOperationalCredentialsIssuer::CallbackGenerateNOCChain(const B
     JniReferences::GetInstance().N2J_ByteArray(env, attestationChallenge.data(), attestationChallenge.size(),
                                                javaAttestationChallenge);
 
-    const ByteSpan & attestationElements = mAutoCommissioner->GetCommissioningParameters().GetAttestationElements().Value();
+    const ByteSpan & attestationElements = mAutoCommissioner->GetAttestationElements();
     jbyteArray javaAttestationElements;
     JniReferences::GetInstance().N2J_ByteArray(env, attestationElements.data(), attestationElements.size(),
                                                javaAttestationElements);
+    // new log message below
```
Comment (tcarmelveilleux) [inline src/controller/java/AndroidOperationalCredentialsIssuer.cpp:228]: Debug remainders?

File: src/controller/java/AndroidOperationalCredentialsIssuer.cpp [hunk 21]
```diff
@@ -219,17 +221,19 @@ CHIP_ERROR AndroidOperationalCredentialsIssuer::CallbackGenerateNOCChain(const B
...
+    ChipLogError(Controller, "AndroidOpCredsIssuer attestationElements size %d/%d", static_cast<int>(attestationElements.size()),
```
Comment (tcarmelveilleux) [inline src/controller/java/AndroidOperationalCredentialsIssuer.cpp:229]: Please remove this internal debug

File: src/controller/AutoCommissioner.cpp (hunk 9 above)
Comment (chrisdecenzo) [reply src/controller/AutoCommissioner.cpp:519]: I created GetAttestationX() methods to the AutoCommissioner which will always return valid ByteSpans, and these are now called from Android rather than going through the CommissioningParameters object. The CommissioningParameters GetAttestationX() methods are not safe to use after the given step completes. I added a warning to that header file:

>Warning: data is not deep copied to local memory and can only be read during PerformCommissioningStep.

File: src/controller/AutoCommissioner.cpp (hunk 1 above)
Comment (chrisdecenzo) [reply src/controller/AutoCommissioner.cpp]: Removed warning since we are now always deep copying

File: src/controller/AutoCommissioner.h (hunk 2 above)
Comment (chrisdecenzo) [reply src/controller/AutoCommissioner.h]: addressed

File: src/controller/AutoCommissioner.h (hunk 3 above)
Comment (chrisdecenzo) [reply src/controller/AutoCommissioner.h]: addressed

File: src/controller/AutoCommissioner.cpp (hunk 4 above)
Comment (chrisdecenzo) [reply src/controller/AutoCommissioner.cpp]: addressed

File: src/controller/AutoCommissioner.cpp (hunk 5 above)
Comment (chrisdecenzo) [reply src/controller/AutoCommissioner.cpp]: addressed

File: src/controller/AutoCommissioner.cpp (hunk 6 above)
Comment (chrisdecenzo) [reply src/controller/AutoCommissioner.cpp]: addressed

File: src/controller/AutoCommissioner.cpp (hunk 7 above)
Comment (chrisdecenzo) [reply src/controller/AutoCommissioner.cpp]: addressed

File: src/controller/AutoCommissioner.cpp (hunk 8 above)
Comment (chrisdecenzo) [reply src/controller/AutoCommissioner.cpp]: addressed

File: examples/platform/linux/CommissionerMain.cpp (hunk 10 above)
Comment (chrisdecenzo) [reply examples/platform/linux/CommissionerMain.cpp]: updated name

File: examples/platform/linux/CommissionerMain.cpp (hunk 11 above)
Comment (chrisdecenzo) [reply examples/platform/linux/CommissionerMain.cpp]: addressed

File: src/controller/AutoCommissioner.cpp (hunk 16 above)
Comment (chrisdecenzo) [reply src/controller/AutoCommissioner.cpp]: changed code to error out when size is too large

File: src/controller/CHIPDeviceController.cpp (hunk 18 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp]: added comment explaining that this is checking for commissioner fabric already on device, and saving the nodeId

File: src/controller/CommissioningDelegate.h (hunk 19 above)
Comment (chrisdecenzo) [reply src/controller/CommissioningDelegate.h]: removed comment

File: src/controller/java/AndroidOperationalCredentialsIssuer.cpp (hunk 20 above)
Comment (chrisdecenzo) [reply src/controller/java/AndroidOperationalCredentialsIssuer.cpp]: addressed

File: src/controller/java/AndroidOperationalCredentialsIssuer.cpp (hunk 21 above)
Comment (chrisdecenzo) [reply src/controller/java/AndroidOperationalCredentialsIssuer.cpp]: changed to ChipLogProgress

File: src/app/app-platform/ContentAppPlatform.cpp (hunk 14 above)
Comment (chrisdecenzo) [reply src/app/app-platform/ContentAppPlatform.cpp:459]: Used in the next method to find any existing ACL for the given subject. This is the app platform code using for casting and the ACL entries created follow the device library spec (casting video player section).

File: src/app/app-platform/ContentAppPlatform.cpp (hunk 15 above)
Comment (chrisdecenzo) [reply src/app/app-platform/ContentAppPlatform.cpp:543]: This is the app platform code using for casting and the ACL entries created follow the device library spec (casting video player section). The ContentAppPlatform is re-creating the ACL entry for the node after re-commissioning it. This ensures the ACL entry is up-to-date since its possible that new apps have been loaded which grant access to the given nodeId.

File: examples/platform/linux/CommissionerMain.cpp (hunk 12 above)
Comment (chrisdecenzo) [reply examples/platform/linux/CommissionerMain.cpp:193]: I think a lot of the objects in CommissionerMain used for commissioning will need to be overridden by specific implementations. I suggest moving this to a separate "cleanup" issue.

File: examples/platform/linux/CommissionerMain.cpp (hunk 13 above)
Comment (chrisdecenzo) [reply examples/platform/linux/CommissionerMain.cpp:158]: I think a lot of the objects in CommissionerMain used for commissioning will need to be overridden by specific implementations. I suggest moving this to a separate "cleanup" issue.

Comment (tcarmelveilleux) [reply examples/platform/linux/CommissionerMain.cpp:158]: Are you saying this is OK because it's in "CommissionerMain.cpp" which only applies to some odd examples? All other chip examples allow setting fabric ID from command line.

File: src/app/app-platform/ContentAppPlatform.cpp (hunk 15 above)
Comment (tcarmelveilleux) [reply src/app/app-platform/ContentAppPlatform.cpp:543]: This code is very opaque. It may well be spec compliant, but I read the cluster spec and there are many statements like `The method for conveying this information between the Content App and the Casting Video Player is specific to the vendor of the Casting Video Player`. I think it woould help everyone if much more details about the rules applied here were explicitly documented in the code. Otherwise it's very possible that authors other than yourself or close colleagues would be able to maintain this code.

File: src/controller/java/AndroidOperationalCredentialsIssuer.cpp (hunk 21 above)
Comment (tcarmelveilleux) [reply src/controller/java/AndroidOperationalCredentialsIssuer.cpp]: This line should completely be removed, and the comment above as well

File: examples/platform/linux/CommissionerMain.cpp [hunk 22]
```diff
@@ -76,7 +76,7 @@ using namespace chip::app::Clusters;
 using namespace ::chip::Messaging;
 using namespace ::chip::Controller;
 
-class MyServerStorageDelegate : public PersistentStorageDelegate
```
Comment (tcarmelveilleux) [inline examples/platform/linux/CommissionerMain.cpp:76]: Is this customer server storage really needed? It seems to be the same as the code in `src/include/platform/KvsPersistentStorageDelegate.h`

File: examples/platform/linux/CommissionerMain.cpp [hunk 23]
```diff
@@ -105,7 +105,7 @@ class MyServerStorageDelegate : public PersistentStorageDelegate
     }
 };
 
-class MyCommissionerCallback : public CommissionerCallback
```
Comment (tcarmelveilleux) [inline examples/platform/linux/CommissionerMain.cpp:105]: Please comment as to why this "custom" callback set must be implemented. It's to support specific policies that are not the default of the likes of chip-tool. The reasons for this should be made clear

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 24]
```diff
@@ -961,7 +958,8 @@ bool emberAfOperationalCredentialsClusterAttestationRequestCallback(app::Command
     attestationElementsSpan = MutableByteSpan{ attestationElements.Get(), attestationElementsLen };
     err = Credentials::ConstructAttestationElements(certDeclSpan, attestationNonce, timestamp, kEmptyFirmwareInfo,
                                                     emptyVendorReserved, attestationElementsSpan);
-    VerifyOrExit((err == CHIP_NO_ERROR) && (attestationElementsSpan.size() <= kMaxRspLen), finalStatus = Status::Failure);
+    VerifyOrExit((err == CHIP_NO_ERROR) && (attestationElementsSpan.size() <= Credentials::kMaxRspLen),
```
Comment (tcarmelveilleux) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:961]: This is part of the contract of ConstructAttestationElements: it is not supposed to make the span slarger than kMaxRspLen. The check should be in ConstructAttestationElements

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp [hunk 25]
```diff
@@ -1092,7 +1090,8 @@ bool emberAfOperationalCredentialsClusterCSRRequestCallback(app::CommandHandler
 
         err = Credentials::ConstructNOCSRElements(ByteSpan{ csrSpan.data(), csrSpan.size() }, CSRNonce, kNoVendorReserved,
                                                   kNoVendorReserved, kNoVendorReserved, nocsrElementsSpan);
-        VerifyOrExit((err == CHIP_NO_ERROR) && (nocsrElementsSpan.size() <= kMaxRspLen), finalStatus = Status::Failure);
+        VerifyOrExit((err == CHIP_NO_ERROR) && (nocsrElementsSpan.size() <= Credentials::kMaxRspLen),
```
Comment (tcarmelveilleux) [inline src/app/clusters/operational-credentials-server/operational-credentials-server.cpp:1093]: This is part of the contract of ConstructNOCSRElements: it is not supposed to make the span larger than kMaxRspLen. The check should be in ConstructNOCSRElements

File: src/controller/AutoCommissioner.cpp [hunk 26]
```diff
@@ -510,43 +510,33 @@ CHIP_ERROR AutoCommissioner::CommissioningStepFinished(CHIP_ERROR err, Commissio
         case CommissioningStage::kSendDACCertificateRequest:
             SetDAC(report.Get<RequestedCertificate>().certificate);
             break;
-        case CommissioningStage::kSendAttestationRequest:
-            if (report.Get<AttestationResponse>().attestationElements.size() > kAttestationElementsLength)
+        case CommissioningStage::kSendAttestationRequest: {
+            auto & elements  = report.Get<AttestationResponse>().attestationElements;
+            auto & signature = report.Get<AttestationResponse>().signature;
+            if (elements.size() > sizeof(mAttestationElements))
```
Comment (tcarmelveilleux) [inline src/controller/AutoCommissioner.cpp:516]: You cannot compare against a sizeof of a native struct. AttestationElements is TLV.

All of this debug code seems odd. If there is a bug let's fix it. Let's not litter "just in case the APIs don't fulfill the API contract requirements" debug.

How could this happen? Did you observe it happen?

Having a garbage span used-after-free is not going to be fully resolved by this. If the garbage is small enough, then it will get through this.

File: src/controller/CHIPDeviceController.cpp [hunk 27]
```diff
@@ -1734,6 +1734,9 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
         }
     });
 
+    // Try to parse as much as we can here before returning, even if this is an error.
```
Comment (tcarmelveilleux) [inline src/controller/CHIPDeviceController.cpp:1737]: Please parenthesize subexpression:

`return_err = (err == CHIP_NO_ERROR) ? return_err : err

File: src/controller/CHIPDeviceController.cpp [hunk 28]
```diff
@@ -1742,6 +1745,9 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
                 return CHIP_NO_ERROR;
             }
 
+            // this code is checking if the device is already on the commissioner's fabric.
+            // if a matching fabric is found, then remember the nodeId so that the commissioner
+            // can cancel commissioning (before it fails in AddNoc) and know it's nodeId.
```
Comment (tcarmelveilleux) [inline src/controller/CHIPDeviceController.cpp:1750]: Please add an integration test for this. This is a late change to AutoCommissioner logic used by *many* participants. This cannot be changed like this without an integration test validating the behavior. An integration test can be constructed using Python ChipDeviceController and run as part of REPL tests. You would commission a first fabric, then commission a node on same fabric with autocommissioning, and try to see that it doesn't fail.

File: src/controller/java/AndroidOperationalCredentialsIssuer.cpp [hunk 29]
```diff
@@ -225,9 +225,8 @@ CHIP_ERROR AndroidOperationalCredentialsIssuer::CallbackGenerateNOCChain(const B
     jbyteArray javaAttestationElements;
     JniReferences::GetInstance().N2J_ByteArray(env, attestationElements.data(), attestationElements.size(),
                                                javaAttestationElements);
-    // new log message below
-    ChipLogError(Controller, "AndroidOpCredsIssuer attestationElements size %d/%d", static_cast<int>(attestationElements.size()),
-                 static_cast<int>(env->GetArrayLength(javaAttestationElements)));
+    ChipLogProgress(Controller, "AndroidOpCredsIssuer attestationElements size %d/%d", static_cast<int>(attestationElements.size()),
+                    static_cast<int>(env->GetArrayLength(javaAttestationElements)));
```
Comment (tcarmelveilleux) [inline src/controller/java/AndroidOperationalCredentialsIssuer.cpp:229]: Please remove this log. It's a "regular success tracing log". Why is this necessary? The output of this cannot be used. If there is a bug, let's fix the bug.

**Review by tcarmelveilleux — CHANGES_REQUESTED** [review]
- [x] Please add an integration test for new AutoCommissioner code or make the entire feature optional and off-by-default
- [x] Remove needless tracing logs and resolve underlying cause

File: examples/platform/linux/CommissionerMain.cpp (hunk 13 above)
Comment (chrisdecenzo) [reply examples/platform/linux/CommissionerMain.cpp]: added command line option for fabric Id

File: src/app/app-platform/ContentAppPlatform.cpp (hunk 15 above)
Comment (chrisdecenzo) [reply src/app/app-platform/ContentAppPlatform.cpp:545]: added more comments in header file and in the implementation body of what is happening

File: src/controller/java/AndroidOperationalCredentialsIssuer.cpp (hunk 21 above)
Comment (chrisdecenzo) [reply src/controller/java/AndroidOperationalCredentialsIssuer.cpp]: removed

File: examples/platform/linux/CommissionerMain.cpp (hunk 22 above)
Comment (chrisdecenzo) [reply examples/platform/linux/CommissionerMain.cpp]: I will add this to a separate cleanup issue https://github.com/project-chip/connectedhomeip/issues/22459

File: examples/platform/linux/CommissionerMain.cpp (hunk 12 above)
Comment (chrisdecenzo) [reply examples/platform/linux/CommissionerMain.cpp]: https://github.com/project-chip/connectedhomeip/issues/22459

File: examples/platform/linux/CommissionerMain.cpp (hunk 23 above)
Comment (chrisdecenzo) [reply examples/platform/linux/CommissionerMain.cpp]: Added separate issue to make this configurable: https://github.com/project-chip/connectedhomeip/issues/22459

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp (hunk 24 above)
Comment (chrisdecenzo) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp]: moved this check into DeviceAttestationConstructor.cpp

File: src/app/clusters/operational-credentials-server/operational-credentials-server.cpp (hunk 25 above)
Comment (chrisdecenzo) [reply src/app/clusters/operational-credentials-server/operational-credentials-server.cpp]: moved this check into DeviceAttestationConstructor.cpp

File: src/controller/AutoCommissioner.cpp (hunk 26 above)
Comment (chrisdecenzo) [reply src/controller/AutoCommissioner.cpp:516]: we are copying the raw TLV into mAttestationElements so why doesn't the size check make sense?

File: src/controller/java/AndroidOperationalCredentialsIssuer.cpp (hunk 29 above)
Comment (chrisdecenzo) [reply src/controller/java/AndroidOperationalCredentialsIssuer.cpp]: removed

File: src/controller/AutoCommissioner.cpp [hunk 30]
```diff
@@ -494,17 +499,45 @@ CHIP_ERROR AutoCommissioner::CommissioningStepFinished(CHIP_ERROR err, Commissio
...
+                ChipLogError(Controller, "AutoCommissioner attestationElements buffer size %u larger than cache size %u",
+                             static_cast<unsigned>(elements.size()), static_cast<unsigned>(sizeof(mAttestationElements)));
+                return CHIP_ERROR_MESSAGE_TOO_LONG;
+            }
+            memcpy(mAttestationElements, elements.data(), elements.size());
+            mAttestationElementsLen = static_cast<uint16_t>(elements.size());
+            mParams.SetAttestationElements(ByteSpan(mAttestationElements, elements.size()));
+            ChipLogError(Controller, "AutoCommissioner setting attestationElements buffer size %u/%u",
+                         static_cast<unsigned>(elements.size()),
+                         static_cast<unsigned>(mParams.GetAttestationElements().Value().size()));
```
Comment (bzbarsky-apple) [inline src/controller/AutoCommissioner.cpp:527]: This should not be a ChipLogError.  ChipLogDetail is more like it, no?

File: src/controller/AutoCommissioner.h [hunk 31]
```diff
@@ -35,9 +36,14 @@ class AutoCommissioner : public CommissioningDelegate
     void SetOperationalCredentialsDelegate(OperationalCredentialsDelegate * operationalCredentialsDelegate) override;
 
     CHIP_ERROR StartCommissioning(DeviceCommissioner * commissioner, CommissioneeDeviceProxy * proxy) override;
+    void StopCommissioning() { mStopCommissioning = true; };
 
     CHIP_ERROR CommissioningStepFinished(CHIP_ERROR err, CommissioningDelegate::CommissioningReport report) override;
 
+    ByteSpan GetAttestationElements() const { return ByteSpan(mAttestationElements, mAttestationElementsLen); }
+    ByteSpan GetAttestationSignature() const { return ByteSpan(mAttestationSignature, mAttestationSignatureLen); }
+    ByteSpan GetAttestationNonce() const { return ByteSpan(mAttestationNonce, sizeof(mAttestationNonce)); }
```
Comment (bzbarsky-apple) [inline src/controller/AutoCommissioner.h:45]:
```suggestion
    ByteSpan GetAttestationNonce() const { return ByteSpan(mAttestationNonce); }
```

File: src/controller/CHIPDeviceController.cpp [hunk 32]
```diff
@@ -1733,6 +1733,51 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
             return CHIP_NO_ERROR;
         }
     });
+
+    // Try to parse as much as we can here before returning, even if this is an error.
+    return_err = (err == CHIP_NO_ERROR) ? return_err : err;
+
+    err = mAttributeCache->ForEachAttribute(
+        app::Clusters::OperationalCredentials::Id, [this, &info](const app::ConcreteAttributePath & path) {
+            if (path.mAttributeId != app::Clusters::OperationalCredentials::Attributes::Fabrics::Id)
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1742]: This whole file is `using namespace chip::app::Clusters;`, no?
```suggestion
            if (path.mAttributeId != OperationalCredentials::Attributes::Fabrics::Id)
```
I would think.

File: src/controller/CHIPDeviceController.cpp [hunk 33]
```diff
@@ -1733,6 +1733,51 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
...
+            {
+                // Continue on
+                return CHIP_NO_ERROR;
+            }
+
+            // this code is checking if the device is already on the commissioner's fabric.
+            // if a matching fabric is found, then remember the nodeId so that the commissioner
+            // can cancel commissioning (before it fails in AddNoc) and know it's nodeId.
+            switch (path.mAttributeId)
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1751]: Why do we have this switch?  We know we have `OperationalCredentials::Attributes::Fabrics::Id` here, no?

File: src/controller/CHIPDeviceController.cpp [hunk 34]
```diff
@@ -1733,6 +1733,51 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
...
+            {
+            case app::Clusters::OperationalCredentials::Attributes::Fabrics::Id: {
+                app::Clusters::OperationalCredentials::Attributes::Fabrics::TypeInfo::DecodableType fabrics;
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1754]:
```suggestion
                OperationalCredentials::Attributes::Fabrics::TypeInfo::DecodableType fabrics;
```

File: src/controller/CHIPDeviceController.cpp [hunk 35]
```diff
@@ -1733,6 +1733,51 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
...
+                ReturnErrorOnFailure(
+                    this->mAttributeCache->Get<app::Clusters::OperationalCredentials::Attributes::Fabrics::TypeInfo>(path,
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1756]:
```suggestion
                    this->mAttributeCache->Get<OperationalCredentials::Attributes::Fabrics::TypeInfo>(path,
```

File: src/controller/CHIPDeviceController.cpp [hunk 36]
```diff
@@ -1733,6 +1733,51 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
...
+                    auto & fabricDescriptor = iter.GetValue();
+                    ChipLogProgress(AppServer,
+                                    "DeviceCommissioner::OnDone - fabric.vendorId=0x%04X fabric.fabricId=0x" ChipLogFormatX64
+                                    " fabric.nodeId=0x" ChipLogFormatX64,
+                                    fabricDescriptor.vendorId, ChipLogValueX64(fabricDescriptor.fabricId),
+                                    ChipLogValueX64(fabricDescriptor.nodeId));
+                    if (GetFabricId() == fabricDescriptor.fabricId)
+                    {
+                        ChipLogProgress(AppServer, "DeviceCommissioner::OnDone - found a matching fabric");
+                        info.nodeId = fabricDescriptor.nodeId;
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1770]: This does not look right.  This is just checking the integer fabric id and ignoring the scoping root public key, no?

File: src/controller/CHIPDeviceController.cpp [hunk 37]
```diff
@@ -2018,9 +2063,13 @@ void DeviceCommissioner::PerformCommissioningStep(DeviceProxy * proxy, Commissio
         // Read the requested minimum connection times from all network commissioning clusters
         readPaths[7] = app::AttributePathParams(app::Clusters::NetworkCommissioning::Id,
                                                 app::Clusters::NetworkCommissioning::Attributes::ConnectMaxTimeSeconds::Id);
+        // Read the current fabrics
+        readPaths[8] = app::AttributePathParams(app::Clusters::OperationalCredentials::Id,
+                                                app::Clusters::OperationalCredentials::Attributes::Fabrics::Id);
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:2068]: Again, I think all the `app::Clusters` prefixes should be able to go away....

File: src/controller/CHIPDeviceController.cpp [hunk 38]
```diff
@@ -1733,6 +1733,51 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
...
+        app::Clusters::OperationalCredentials::Id, [this, &info](const app::ConcreteAttributePath & path) {
+            if (path.mAttributeId != app::Clusters::OperationalCredentials::Attributes::Fabrics::Id)
+            {
+                // Continue on
+                return CHIP_NO_ERROR;
+            }
+
+            // this code is checking if the device is already on the commissioner's fabric.
+            // if a matching fabric is found, then remember the nodeId so that the commissioner
+            // can cancel commissioning (before it fails in AddNoc) and know it's nodeId.
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1750]:
```suggestion
            // can, if it decides to, cancel commissioning (before it fails in AddNoc) and know the device's nodeId on its fabric.
```

File: src/controller/CHIPDeviceController.cpp [hunk 39]
```diff
@@ -1997,7 +2042,7 @@ void DeviceCommissioner::PerformCommissioningStep(DeviceProxy * proxy, Commissio
         app::InteractionModelEngine * engine = app::InteractionModelEngine::GetInstance();
         app::ReadPrepareParams readParams(proxy->GetSecureSession().Value());
 
-        app::AttributePathParams readPaths[8];
+        app::AttributePathParams readPaths[9];
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:2045]: Please add a comment that this array is not allowed to have more than 9 items, since 9 is what the spec has as a minimum requirement on servers.

File: src/controller/CHIPDeviceController.cpp (hunk 37 above)
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:2068]: Doing this as a required read for all commissioning interactions just to support commissioners that might use this state is not great: this attribute can be quite a lot of data, no?

Why does this need to be done in the common code at all, instead of the commissioners that want this doing the relevant read themselves over PASE before the start the common commissioning process?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]

File: src/controller/CHIPDeviceController.cpp (hunk 36 above)
Comment (tcarmelveilleux) [reply src/controller/CHIPDeviceController.cpp:1770]: Yes, agreed. Discussed it offline with @chrisdecenzo and made that point and gave pointers how to resolve

**Comment by bzbarsky-apple** [comment]
@chrisdecenzo For what it's worth, I think the right approach here at this stage to reduce risk in terms of the DeviceCommissioner changes might be for whatever consumers want the `Fabrics` attribute info to:

1. Use the `EstablishPASEConnection` API on `ChipDeviceController` to establish a PASE session, passing in a device id that will identify the commissioning process and the pairing code involved.
2. In the `OnPairingComplete` callback, if it succeeds, `FindCommissioneeDevice` with the same device id, and use that to send a read for `Fabrics`.
3. Do the sanity check for the fabric already existing.  If it does, and the PASE session should just be closed, call `StopPairing` with the relevant device id.
4. If the fabric does not already exist, call `Commission` on the `DeviceCommissioner` to commission the device.

While it might be good if the SDK provided more built-in support for doing this check, I think it's worth thinking a bit about how exactly that should work in a way that does not hurt the common commissioning case and does not change the default commissioning flow from the one that has been widely tested.  (For example, maybe the Fabrics read should only happen in the actual error case when we get the `FabricConflict` status?)

File: src/controller/CHIPDeviceController.cpp (hunk 28 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp]: Updated to make this functionality runtime enable-able (disabled by default)

File: src/controller/AutoCommissioner.cpp (hunk 30 above)
Comment (chrisdecenzo) [reply src/controller/AutoCommissioner.cpp]: fixed

File: src/controller/AutoCommissioner.h (hunk 31 above)
Comment (chrisdecenzo) [reply src/controller/AutoCommissioner.h]: fixed

File: src/controller/CHIPDeviceController.cpp (hunk 32 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp]: fixed

File: src/controller/CHIPDeviceController.cpp (hunk 33 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp:1746]: removed if, kept as switch to follow pattern used in rest of this method

File: src/controller/CHIPDeviceController.cpp (hunk 34 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp]: fixed

File: src/controller/CHIPDeviceController.cpp (hunk 35 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp]: fixed

File: src/controller/CHIPDeviceController.cpp (hunk 36 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp]: good catch - added code to also check the fabric root public key

File: src/controller/CHIPDeviceController.cpp (hunk 37 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp]: fixed

File: src/controller/CHIPDeviceController.cpp (hunk 38 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp]: included

File: src/controller/CHIPDeviceController.cpp (hunk 39 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp:2054]: added comment

File: src/controller/CHIPDeviceController.cpp (hunk 37 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp]: updated to make this attribute read runtime configurable (disabled by default)

**Comment by chrisdecenzo** [comment]
I created https://github.com/project-chip/connectedhomeip/issues/22525 to track work for making the already-on-fabric check happen by default (with a few suggestions for how best to do it).

**Comment by chrisdecenzo** [comment]
Fixes https://github.com/project-chip/connectedhomeip/issues/22419

**Comment by chrisdecenzo** [comment]
Fixes #22419

File: src/controller/CHIPDeviceController.cpp [hunk 40]
```diff
@@ -1764,10 +1758,24 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
                                     " fabric.nodeId=0x" ChipLogFormatX64,
                                     fabricDescriptor.vendorId, ChipLogValueX64(fabricDescriptor.fabricId),
                                     ChipLogValueX64(fabricDescriptor.nodeId));
+                    // need to add check for root public key
```
Comment (tcarmelveilleux) [inline src/controller/CHIPDeviceController.cpp]: This TODO is done

**Review by tcarmelveilleux — APPROVED** [review]

**Review by hawk248 — APPROVED** [review]

File: src/controller/CHIPDeviceController.cpp [hunk 41]
```diff
@@ -1733,6 +1733,57 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
...
+                        ChipLogError(AppServer, "DeviceCommissioner::OnDone - error reading commissioner root public key");
+                    }
+                    else if (commissionerRootPublicKey.Matches(deviceRootPublicKey))
+                    {
+                        ChipLogProgress(AppServer, "DeviceCommissioner::OnDone - fabric root keys match");
+                        info.nodeId = fabricDescriptor.nodeId;
+                    }
+                }
+            }
+
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1779]: This should document why it's not checking for error on `iter` at this point (which would indicate that we got data where we could not decode the TLV and we don't really know what's going on; presumably that's OK because this is meant to be best-effort?).

File: src/controller/CHIPDeviceController.cpp [hunk 42]
```diff
@@ -1733,6 +1733,57 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
...
+                                "DeviceCommissioner::OnDone - fabric.vendorId=0x%04X fabric.fabricId=0x" ChipLogFormatX64
+                                " fabric.nodeId=0x" ChipLogFormatX64,
+                                fabricDescriptor.vendorId, ChipLogValueX64(fabricDescriptor.fabricId),
+                                ChipLogValueX64(fabricDescriptor.nodeId));
+                // need to add check for root public key
+                if (GetFabricId() == fabricDescriptor.fabricId)
+                {
+                    ChipLogProgress(AppServer, "DeviceCommissioner::OnDone - found a matching fabric id");
+                    chip::ByteSpan rootKeySpan = fabricDescriptor.rootPublicKey;
+                    P256PublicKeySpan rootPubKeySpan(rootKeySpan.data());
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1764]: What happens here if `rootKeySpan.size()` is too small?  Is this not a buffer overrun in that case?  We need to check the sizing here.

File: src/controller/CHIPDeviceController.cpp [hunk 43]
```diff
@@ -1733,6 +1733,57 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
...
+        switch (path.mAttributeId)
+        {
+        case OperationalCredentials::Attributes::Fabrics::Id: {
+            OperationalCredentials::Attributes::Fabrics::TypeInfo::DecodableType fabrics;
+            ReturnErrorOnFailure(this->mAttributeCache->Get<OperationalCredentials::Attributes::Fabrics::TypeInfo>(path, fabrics));
+            auto iter = fabrics.begin();
+            while (iter.Next())
+            {
+                auto & fabricDescriptor = iter.GetValue();
+                ChipLogProgress(AppServer,
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1754]:
```suggestion
                ChipLogProgress(Controller,
```

File: src/controller/CHIPDeviceController.cpp [hunk 44]
```diff
@@ -1733,6 +1733,57 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
...
+                                "DeviceCommissioner::OnDone - fabric.vendorId=0x%04X fabric.fabricId=0x" ChipLogFormatX64
+                                " fabric.nodeId=0x" ChipLogFormatX64,
+                                fabricDescriptor.vendorId, ChipLogValueX64(fabricDescriptor.fabricId),
+                                ChipLogValueX64(fabricDescriptor.nodeId));
+                // need to add check for root public key
+                if (GetFabricId() == fabricDescriptor.fabricId)
+                {
+                    ChipLogProgress(AppServer, "DeviceCommissioner::OnDone - found a matching fabric id");
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1762]:
```suggestion
                    ChipLogProgress(Controller, "DeviceCommissioner::OnDone - found a matching fabric id");
```

File: src/controller/CHIPDeviceController.cpp [hunk 45]
```diff
@@ -1733,6 +1733,57 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
...
+                    chip::ByteSpan rootKeySpan = fabricDescriptor.rootPublicKey;
+                    P256PublicKeySpan rootPubKeySpan(rootKeySpan.data());
+                    Crypto::P256PublicKey deviceRootPublicKey(rootPubKeySpan);
+
+                    Crypto::P256PublicKey commissionerRootPublicKey;
+                    if (CHIP_NO_ERROR != GetRootPublicKey(commissionerRootPublicKey))
+                    {
+                        ChipLogError(AppServer, "DeviceCommissioner::OnDone - error reading commissioner root public key");
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1770]:
```suggestion
                        ChipLogError(Controller, "DeviceCommissioner::OnDone - error reading commissioner root public key");
```

File: src/controller/CHIPDeviceController.cpp [hunk 46]
```diff
@@ -1733,6 +1733,57 @@ void DeviceCommissioner::OnDone(app::ReadClient *)
...
+                    }
+                    else if (commissionerRootPublicKey.Matches(deviceRootPublicKey))
+                    {
+                        ChipLogProgress(AppServer, "DeviceCommissioner::OnDone - fabric root keys match");
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:1774]:
```suggestion
                        ChipLogProgress(Controller, "DeviceCommissioner::OnDone - fabric root keys match");
```

File: src/controller/CHIPDeviceController.cpp [hunk 47]
```diff
@@ -2018,9 +2070,15 @@ void DeviceCommissioner::PerformCommissioningStep(DeviceProxy * proxy, Commissio
...
                                                 app::Clusters::NetworkCommissioning::Attributes::ConnectMaxTimeSeconds::Id);
+        // Read the current fabrics
+        if (params.GetCheckForMatchingFabric().ValueOr(false))
+        {
+            readPaths[8] = app::AttributePathParams(OperationalCredentials::Id, OperationalCredentials::Attributes::Fabrics::Id);
+        }
 
         readParams.mpAttributePathParamsList    = readPaths;
-        readParams.mAttributePathParamsListSize = 8;
+        readParams.mAttributePathParamsListSize = 8 + (params.GetCheckForMatchingFabric().ValueOr(false) ? 1 : 0);
```
Comment (bzbarsky-apple) [inline src/controller/CHIPDeviceController.cpp:2080]: This might be somewhat clearer/safer if we set `readParams.mAttributePathParamsListSize = 8` before we  check `params.GetCheckForMatchingFabric().ValueOr(false)` and then in that block when we seat `readPaths[8]` we also set `readParams.mAttributePathParamsListSize = 9`.  That way we don't have to match up the conditions across different lines, etc.

File: src/controller/CommissioningDelegate.h [hunk 48]
```diff
@@ -417,6 +437,7 @@ class CommissioningParameters
     Optional<bool> mAttemptWiFiNetworkScan;
     Optional<bool> mAttemptThreadNetworkScan; // This automatically gets set to false when a ThreadOperationalDataset is set
     Optional<bool> mSkipCommissioningComplete;
+    Optional<bool> mCheckForMatchingFabric;
```
Comment (bzbarsky-apple) [inline src/controller/CommissioningDelegate.h:440]: Might be worth documenting why this is an `Optional<bool>` instead of just a bool.  For some of the other booleans, there is default auto-guessing behavior based on other information, but for this one the default is just false, right?

File: src/controller/CHIPDeviceController.cpp (hunk 41 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp:1786]: added comment

File: src/controller/CHIPDeviceController.cpp (hunk 40 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp]: removed

File: src/controller/CHIPDeviceController.cpp (hunk 44 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp]: fixed

File: src/controller/CHIPDeviceController.cpp (hunk 45 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp]: fixed

File: src/controller/CHIPDeviceController.cpp (hunk 46 above)
Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp]: fixed

File: src/controller/CommissioningDelegate.h (hunk 48 above)
Comment (chrisdecenzo) [reply src/controller/CommissioningDelegate.h]: checked this to be just a bool

**Review by bzbarsky-apple — APPROVED** [review]

File: src/controller/CHIPDeviceController.cpp [hunk 49]
```diff
@@ -1997,7 +2055,8 @@ void DeviceCommissioner::PerformCommissioningStep(DeviceProxy * proxy, Commissio
         app::InteractionModelEngine * engine = app::InteractionModelEngine::GetInstance();
         app::ReadPrepareParams readParams(proxy->GetSecureSession().Value());
 
-        app::AttributePathParams readPaths[8];
+        // NOTE: this array cannot have more than 9 entries, since 9 is what the spec requires as a minimum on servers
```
Comment (andy31415) [inline src/controller/CHIPDeviceController.cpp:2058]: This seems off: this says the spec requires a minimum but we use 9 as the maximum.

This needs revision.

Comment (chrisdecenzo) [reply src/controller/CHIPDeviceController.cpp:2058]: "client cannot send more than 9 since spec mandates 9 as minimum on the server side"
