### PR TITLE
Make iteration of tracing backends thread-safe using atomics

### LINKED ISSUE #42232: Darwin framework code calls tracing code from non-Matter thread
Example run: https://github.com/project-chip/connectedhomeip/actions/runs/19826470211/job/56803070147

```
2025-12-01 15:19:22.263862+0000 xctest[39122:144067] [Default] <MTRCommissioningOperation: 0x125cff890> attempt to start commissioning with controller <MTRDeviceController_Concrete: 0x108e11080, uuid: 7B02265D-D44A-4C50-B99D-09B31CF8C735, suspended: NO> and parameters <MTRCommissioningParameters: 0x1082fc960, has ssid: 0, has thread dataset: 0>, accepted terms: (null), accepted terms version: (null)> failed: Error Domain=MTRErrorDomain Code=6 "Invalid object state." UserInfo={NSLocalizedDescription=Invalid object state.}
2025-12-01 15:19:22.264071+0000 xctest[39122:143432] [Default] Shutting down the Matter controller factory
2025-12-01 15:19:22.264243+0000 xctest[39122:143432] [Default] Cleaning startup objects in controller factory
2025-12-01 15:19:22.264364+0000 xctest[39122:143432] [Default] Unregistered tracing backend with the registry
2025-12-01 15:19:22.264758+0000 xctest[39122:144067] [Default] Unable to find Begin event corresponding to Metric Event: dwnfw_device_commissioning
Test Case '-[MTRBleTests testShutdownAndBlePowerOffAfterSuccessfulConnect]' passed (0.130 seconds).
../../../../../../../../../../../work/connectedhomeip/connectedhomeip/src/lib/support/IntrusiveList.h:433:34: runtime error: reference binding to null pointer of type 'chip::Tracing::Backend'
```

### PR DESCRIPTION
**Pull request by ksperling-apple**
#### Summary

Use a fixed-sized array of atomic pointers instead of IntrusiveList to manage the list of registered backends. Also update the README to provide some additional clarity around the two levels of tracing APIs.

#### Related Issues

Fixes #42232

#### Testing

Existing TestTracing and TestMetricEvents tests cover backend registration / unregistration.
Added extra checks in to ensure Open / Close is called correctly.

### CODE REVIEW

File: src/tracing/registry.cpp [hunk 1]
```diff
@@ -14,127 +14,157 @@
...
+vacuum:
+    // Replace trailing NullBackend() entries with nullptr,
+    // so iteration can stop as early as possible.
+    for (int i = CHIP_CONFIG_MAX_TRACING_BACKENDS - 1; i >= 0; --i)
+    {
+        auto & slot = gTracingBackends[i];
+        VerifyOrReturn(slot.load() == NullBackend());
+        slot.store(nullptr);
     }
 }
```
[the remark this answers is not in the document]
Comment (ksperling-apple) [reply src/tracing/registry.cpp:119]: Addressed

File: src/tracing/registry.cpp [hunk 2]
```diff
@@ -14,127 +14,158 @@
...
+        }
+    }
+    return;
+vacuum:
+    // Replace trailing NullBackend() entries with nullptr,
+    // so iteration can stop as early as possible.
+    for (int i = CHIP_CONFIG_MAX_TRACING_BACKENDS - 1; i >= 0; --i)
+    {
+        auto & slot = gTracingBackends[i];
+        VerifyOrReturn(slot.load() == NullBackend());
```
[the remark this answers is not in the document]
Comment (ksperling-apple) [reply src/tracing/registry.cpp]: The logic had a bug, but your suggestion is also wrong.

File: src/tracing/registry.cpp [hunk 3]
```diff
@@ -14,127 +14,169 @@
...
+
 namespace {
+// Modifications of the backend array are protected by the Matter stack lock,
+// but iteration can happen from any thread at any time. Slots must be filled
+// from the beginning of the array, so iteration can stop at the first nullptr.
+std::atomic<Backend *> gTracingBackends[CHIP_CONFIG_MAX_TRACING_BACKENDS]{};
+
+// A marker value to represent an empty slot in the backend array.
+// This avoids having to shift backends in the array when unregistering.
+alignas(Backend) constexpr char gNullBackendStorage{ 0 };
```
Comment (andy31415) [inline src/tracing/registry.cpp]: This feels dirty ... so you get a pointer that is actually a totally invalid object ... can we do something else even at the cost of 10s of bytes of flash? How much does a vtable for an empty backend cost?

File: src/tracing/registry.cpp [hunk 4]
```diff
@@ -14,127 +14,169 @@
...
 #include <platform/LockTracker.h>
-#include <tracing/registry.h>
 
-namespace chip {
-namespace Tracing {
+#include <atomic>
+
+namespace chip::Tracing {
+
+#if MATTER_TRACING_ENABLED
```
Comment (andy31415) [inline src/tracing/registry.cpp]: lets use the build system instead. having a `.cpp` file completely adding/removing code via a ifdef seems like a undesireable pattern.

File: src/tracing/registry.cpp [hunk 5]
```diff
@@ -14,127 +14,169 @@
...
+{
+    return reinterpret_cast<Backend *>(const_cast<char *>(&gNullBackendStorage));
+}
+
+template <typename Fn>
+void ForEachBackend(Fn && fn)
+{
+    for (auto & slot : gTracingBackends)
+    {
+        Backend * backend = slot.load();
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/tracing/registry.cpp]: The default is memory_order_seq_cst, which is stronger than release/acquire, so this code is fine.

File: src/tracing/registry.cpp [hunk 6]
```diff
@@ -14,127 +14,169 @@
...
+// so iteration can stop as early as possible.
+void OptimizeBackends()
+{
+    for (int i = CHIP_CONFIG_MAX_TRACING_BACKENDS - 1; i >= 0; --i)
+    {
+        auto & slot    = gTracingBackends[i];
+        auto * backend = slot.load();
+        if (backend == NullBackend())
+        {
+            slot.store(nullptr);
```
[the remark this answers is not in the document]
Comment (bzbarsky-apple) [reply src/tracing/registry.cpp]: > The load() and store() operations need explicit memory ordering

No, they don't; default ordering is "sequential consistency".

File: src/tracing/registry.cpp (hunk 4 above)
Comment (bzbarsky-apple) [reply src/tracing/registry.cpp]: > having a .cpp file completely adding/removing code via a ifdef seems

That's not what's going on here, though?  There's code in the `#else` clause, right?

Though it _is_ what was going on before this PR...

**Review by bzbarsky-apple — APPROVED** [review]

File: src/tracing/registry.cpp (hunk 4 above)
Comment (andy31415) [reply src/tracing/registry.cpp]: well, ok, it uses ifdefs ... what I am suggesting is to have something like `null_registry.cpp` and `indexed_registry.cpp` or some other naming that makes sense and use the build system to define what gets included based on configurations.

ifdefs in cpp files are quickly unmanageable.

Comment (ksperling-apple) [reply src/tracing/registry.cpp]: OK, I'll move this into a `registry_disabled.cpp`

**Review by andy31415 — APPROVED** [review]

File: src/tracing/registry.cpp (hunk 3 above)
Comment (andy31415) [reply src/tracing/registry.cpp]: I also overall wonder: if we have 4 backends, the cost of "loop through all non-null" is probably negligible and the optimization of "stop at the first null" maybe only gains so much. Did we measure if it is worth it to have this extra logic?

File: src/tracing/registry.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (ksperling-apple) [reply src/tracing/registry.cpp]: I've replaced these with explicit release/acquire memory orders now since that's a strong enough guarantee.

File: src/tracing/registry.cpp [hunk 7]
```diff
@@ -14,127 +14,169 @@
...
+// but iteration can happen from any thread at any time. Slots must be filled
+// from the beginning of the array, so iteration can stop at the first nullptr.
+std::atomic<Backend *> gTracingBackends[CHIP_CONFIG_MAX_TRACING_BACKENDS]{};
+
+// A marker value to represent an empty slot in the backend array.
+// This avoids having to shift backends in the array when unregistering.
+alignas(Backend) constexpr char gNullBackendStorage{ 0 };
+Backend * NullBackend()
+{
+    return reinterpret_cast<Backend *>(const_cast<char *>(&gNullBackendStorage));
```
[the remark this answers is not in the document]
Comment (ksperling-apple) [reply src/tracing/registry.cpp]: Changed to avoid the reinterpret_cast

File: src/tracing/registry.cpp (hunk 3 above)
Comment (ksperling-apple) [reply src/tracing/registry.cpp]: I don't actually want to call into the "null" backend since the default `Backend` class has some non-empty implementations, and a check against a known pointer is probably more efficient than a virtual method call. I've changed the table to `void *` so the marker value doesn't need any `reinterpret_cast` gymnastics; there's actually only a single place where we need to downcast to `Backend *`, which is in `ForEachBackend`, so that seems pretty tidy to me now.

File: src/tracing/registry_disabled.cpp [hunk 8]
```diff
@@ -0,0 +1,32 @@
...
+ *    limitations under the License.
+ */
+
+#include <tracing/registry.h>
+
+namespace chip::Tracing {
+
+void Register(Backend & backend)
+{
+    /* no-op if tracing is disabled */
```
Comment (andy31415) [inline src/tracing/registry_disabled.cpp]: should we log something instead? Register that simply does not work sounds off...
