### PR TITLE
Make TestBdxTransferServer::Shutdown() restore the default UnsolicitedMessageHandler

### LINKED ISSUE #41464: [BUG] Error occurs during BDXTransferServer::Shutdown when using the Python controller due to multiple unregisters for UMH
When using the python controller, the following error message occurs during shutdown
`
ERROR:matter.native.-:src/messaging/ExchangeMgr.cpp:192: CHIP Error 0x00000007: No unsolicited message handler at src/protocols/bdx/BdxTransferServer.cpp:55
`

This is happening because the python controller's TestBdxTransferServer overrides the default BdxTransferServer (that which would be used by non-Python implementations), and during initialization it unregisters the unsolicited message handler for SendInit that had been registered by the default BdxTransferServer so that it can register its own protocol-wide handler instead.  However when it tears down it never puts the old handler back in place, so then when the default BdxTransferServer shuts down it tries to unregister its SendInit handler but finds that there is no such handler registered anymore, so it throws an error.

This can be fixed by having the python controller's TestBdxTransferServer::Init store the existing handler before unregistering it, and then during Shutdown re-register the old handler again, thus returning things to how they were before the python controller took over.   Therefore when the default BdxTransferServer does its Shutdown and tries to unregister that handler, it will be there.

The catch here is that the python controller's TestBdxTransferServer::Shutdown **is never actually called**.  This by itself is a problem.  So this must also be fixed in order to fix the above.

I will shortly submit a PR that will implement the above.

### Reproduction steps

To see this error, run any of the python test scripts and look near the end of the controller log.  For example:
`python src/python_testing/TestBdxTransfer.py --discriminator 3456 --passcode 20202021 --commissioning-method on-network`

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

Latest master

### Platform

python

### PR DESCRIPTION
**Pull request by feasel0**
#### Summary

When using the python controller, the following error message occurs during shutdown
ERROR:matter.native.-:src/messaging/ExchangeMgr.cpp:192: CHIP Error 0x00000007: No unsolicited message handler at src/protocols/bdx/BdxTransferServer.cpp:55

This happens because the python controller's TestBdxTransferServer overrides the default BdxTransferServer (that which would be used by non-Python implementations), and during initialization it unregisters the unsolicited message handler for SendInit that had been registered by the default BdxTransferServer so that it can register its own protocol-wide handler instead. However when it tears down it never puts the old handler back in place, so then when the default BdxTransferServer shuts down it tries to unregister its SendInit handler but finds that there is no such handler registered anymore, so it throws an error.

This PR:

- Creates `Bdx.Shutdown()` and calls it from `ChipStack.Shutdown()` (before the call to `pychip_DeviceController_StackShutdown` thus ensuring that the Python controller's BDX server is shut down before the default matter BDX server).
- Creates `pychip_Bdx_Shutdown()`, registers it, and calls it from `Bdx.Shutdown()`.  This method calls `TestBdxTransferServer::Shutdown()`, which previously existed but was never called by anything.
- Adds to `TestBdxTransferServer::Shutdown()` a call to `RegisterUnsolicitedMessageHandlerForType()` which re-registers the default BdxTransferServer that had previously been unregistered by `TestBdxTransferServer::Init()`.
- During `TestBdxTransferServer::Init`, to store the handler that had previously been registered it was necessary to modify `UnregisterUnsolicitedMessageHandlerForType` so that it can return the handler that gets unregistered, which is then stored in a private member variable in TestBdxTransferServer.
- `UnregisterUnsolicitedMessageHandlerForType` takes an additional optional parameter `outHandler` which, if non-null, is assigned the handler that is being unregistered.  If `outHandler`is nullptr or is not provided at all, then it does not do this, so existing code does not have to change.
- Unit tests were updated so that all uses of `UnregisterUnsolicitedMessageHandlerForType` will also check that the handler being unregistered matches the one that was originally registered.

#### Related issues

Fixes: #41464

#### Testing

The python integration tests are sufficient to test this change.  I used `src/python_testing/TestBdxTransfer.py`, but any of them would do.  While the bug had not been causing these tests to fail, it was causing an error message during shutdown.  I've confirmed that this error message is now gone.

The change that was made to `UnregisterUnsolicitedMessageHandlerForType` (adding the optional `outHandler` parameter) is tested by the unit tests `TestExhange.cpp`, `TestExchangeMgr.cpp`, and `TestReliableMessageProtocol.cpp`, all of which use that function.

#### Readability checklist

The checklist below will help the reviewer finish PR review in time and keep the
code readable:

-   [ ] PR title is
        [descriptive](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html#title-formatting)
-   [ ] Apply the
        [_“When in Rome…”_](https://project-chip.github.io/connectedhomeip-doc/style/CODING_STYLE_GUIDE.html)
        rule (coding style)
-   [ ] PR size is short
-   [ ] Try to avoid "squashing" and "force-update" in commit history
-   [ ] CI time didn't increase

See: [Pull Request Guidelines](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html)

### CODE REVIEW

File: src/controller/python/matter/bdx/test-bdx-transfer-server.cpp [hunk 1]
```diff
@@ -44,6 +45,18 @@ void TestBdxTransferServer::Shutdown()
...
+    // Re-register the BdxTransferServer that was registered as part of CHIPDeviceControllerFactory.
+    // Otherwise when BdxTransferServer::Shutdown() attempts to unregister this, it causes an error.
+    // Since there is no direct getter for the current handler in ExchangeManager, we can't save this during
+    // TestBdxTransferServer::Init, so instead we rely on the controller factory system state which owns the default
+    // BDXTransferServer instance.
+    const Controller::DeviceControllerSystemState * systemState =
+        Controller::DeviceControllerFactory::GetInstance().GetSystemState();
+    if (systemState != nullptr && systemState->BDXTransferServer() != nullptr)
+        LogErrorOnFailure(
+            mExchangeManager->RegisterUnsolicitedMessageHandlerForType(MessageType::SendInit, systemState->BDXTransferServer()));
```
[the remark this answers is not in the document]
Comment (feasel0) [reply src/controller/python/matter/bdx/test-bdx-transfer-server.cpp]: Good idea.  Done.

File: src/messaging/ExchangeMgr.cpp [hunk 2]
```diff
@@ -170,18 +171,25 @@ CHIP_ERROR ExchangeManager::RegisterUMH(Protocols::Id protocolId, int16_t msgTyp
...
-CHIP_ERROR ExchangeManager::UnregisterUMH(Protocols::Id protocolId, int16_t msgType)
+CHIP_ERROR ExchangeManager::UnregisterUMH(Protocols::Id protocolId, int16_t msgType,
+                                          Messaging::UnsolicitedMessageHandler ** outHandler)
 {
     for (auto & umh : UMHandlerPool)
     {
         if (umh.IsInUse() && umh.Matches(protocolId, msgType))
         {
+            // Capture the handler before resetting the slot.
+            if (outHandler != nullptr)
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeMgr.cpp:182]: Curlies around if bodies, please.

File: src/messaging/ExchangeMgr.h [hunk 3]
```diff
@@ -168,20 +168,27 @@ class DLL_EXPORT ExchangeManager : public SessionMessageDelegate
      *
      *  @param[in]    msgType       The message type of the corresponding protocol.
      *
+     *  @param[out]   outHandler   If non-null, receives the handler that was removed from the
+     *                             unsolicited message handler pool. If no handler matched, *outHandler
```
Comment (bzbarsky-apple) [inline src/messaging/ExchangeMgr.h]: What pool?   This API does not have a concept of "pool"...

This is just the handler that was unregistered, if any, right?

File: src/messaging/ExchangeMgr.cpp (hunk 2 above)
Comment (feasel0) [reply src/messaging/ExchangeMgr.cpp:182]: Fixed everywhere.

File: src/messaging/ExchangeMgr.h (hunk 3 above)
Comment (feasel0) [reply src/messaging/ExchangeMgr.h]: Yes.  Made this comment better.

**Review by harimau-qirex — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
Marking as approvide since many week old and @harimau-qirex knows BDX quite well.
