### PR TITLE
[OPSTATE] Fix: change in type for OperationalState attribute

### LINKED ISSUE #27580: Align SDK with change in type for OperationalState attribute
Tracking issue for the change in type of the OperationalState attribute to cover needed SDK changes. 
See PR: https://github.com/CHIP-Specifications/chip-test-plans/issues/2963

@mideayanghui

### PR DESCRIPTION
**Pull request by mideayanghui**
Fixes #27580

### CODE REVIEW

File: src/app/clusters/operational-state-server/operational-state-delegate.h [hunk 1]
```diff
@@ -213,10 +213,10 @@ class Delegate
 public:
     /**
      * Get the current operational state.
-     * @param op The GenericOperationalState to fill with the current operational state value.
+     * @param op The uint8_t to fill with the current operational state value.
      * @return void.
      */
-    virtual void GetCurrentOperationalState(GenericOperationalState & op) = 0;
+    virtual void GetCurrentOperationalState(uint8_t & op) = 0;
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-state-server/operational-state-delegate.h:219]:
```suggestion
    virtual uint8_t GetCurrentOperationalState() = 0;
```
And adjust the documentation accordingly.

File: src/app/clusters/operational-state-server/operational-state-delegate.h [hunk 2]
```diff
@@ -258,7 +258,7 @@ class Delegate
      * Set current operational state.
      * @param opState The operational state that should now be the current one.
      */
-    virtual CHIP_ERROR SetOperationalState(const GenericOperationalState & opState) = 0;
+    virtual CHIP_ERROR SetOperationalState(const uint8_t & opState) = 0;
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-state-server/operational-state-delegate.h:261]:
```suggestion
    virtual CHIP_ERROR SetOperationalState(uint8_t opState) = 0;
```

File: src/app/clusters/operational-state-server/operational-state-server.cpp [hunk 3]
```diff
@@ -106,12 +106,12 @@ void OperationalStateServer::HandlePauseState(HandlerContext & ctx, const Comman
     Commands::OperationalCommandResponse::Type response;
     Delegate * delegate = OperationalState::GetOperationalStateDelegate(mEndpointId, mClusterId);
     GenericOperationalError err(to_underlying(ErrorStateEnum::kNoError));
-    GenericOperationalState opState;
+    uint8_t opState;
```
Comment (bzbarsky-apple) [inline src/app/clusters/operational-state-server/operational-state-server.cpp:109]: Should really be declared down where it's first used, so:
```
   uint8_t opState =  delegate->GetCurrentOperationalState();
```
down after we check the delegate is not null.  Similar in other places.

File: src/app/zap-templates/zcl/data-model/chip/operational-state-cluster.xml [hunk 4]
```diff
@@ -63,7 +63,7 @@ limitations under the License.
     <attribute side="server" code="0x0001" define="CURRENT_PHASE"           type="INT8U"                                    min="0x00" max="0x1F"    writable="false" isNullable="true"  optional="false">CurrentPhase</attribute>
     <attribute side="server" code="0x0002" define="COUNTDOWN_TIME"          type="elapsed_s"                                min="0x00" max="259200"  writable="false" isNullable="true"  optional="true">CountdownTime</attribute>
     <attribute side="server" code="0x0003" define="OPERATIONAL_STATE_LIST"  type="ARRAY" entryType="OperationalStateStruct"                          writable="false"                    optional="false">OperationalStateList</attribute>
-    <attribute side="server" code="0x0004" define="OPERATIONAL_STATE"       type="OperationalStateStruct"                                            writable="false"                    optional="false">OperationalState</attribute>
+    <attribute side="server" code="0x0004" define="OPERATIONAL_STATE"       type="ENUM8"                                                             writable="false"                    optional="false">OperationalState</attribute>
```
Comment (bzbarsky-apple) [inline src/app/zap-templates/zcl/data-model/chip/operational-state-cluster.xml:66]:
```suggestion
    <attribute side="server" code="0x0004" define="OPERATIONAL_STATE"       type="OperationalStateEnum"                                                             writable="false"                    optional="false">OperationalState</attribute>
```
In the struct we used ENUM8 to work around some codegen bits, but those bits are not relevant to the attribute, right?

File: src/app/zap-templates/zcl/data-model/chip/operational-state-rvc-cluster.xml [hunk 5]
```diff
@@ -51,7 +51,7 @@ limitations under the License.
     <attribute side="server" code="0x0001" define="CURRENT_PHASE"           type="INT8U"                                    min="0x00" max="0x1F"    writable="false" isNullable="true"  optional="false">CurrentPhase</attribute>
     <attribute side="server" code="0x0002" define="COUNTDOWN_TIME"          type="elapsed_s"                                min="0"    max="259200"  writable="false" isNullable="true"  optional="true">CountdownTime</attribute>
     <attribute side="server" code="0x0003" define="OPERATIONAL_STATE_LIST"  type="ARRAY" entryType="OperationalStateStruct"                          writable="false"                    optional="false">OperationalStateList</attribute>
-    <attribute side="server" code="0x0004" define="OPERATIONAL_STATE"       type="OperationalStateStruct"                                            writable="false"                    optional="false">OperationalState</attribute>
+    <attribute side="server" code="0x0004" define="OPERATIONAL_STATE"       type="ENUM8"                                                             writable="false"                    optional="false">OperationalState</attribute>
```
Comment (bzbarsky-apple) [inline src/app/zap-templates/zcl/data-model/chip/operational-state-rvc-cluster.xml:54]: Here I guess ENUM8 makes sense since it might be the OperationalStateEnum from this cluster of from OperationalState.  But please add a comment in the XML explaining that?  Because once we start generating the XML from the spec (or vice versa), this bit is going to be a problem....

Comment (mideayanghui) [reply src/app/zap-templates/zcl/data-model/chip/operational-state-rvc-cluster.xml:59]: Sure, add a comment.

File: src/app/zap-templates/zcl/data-model/chip/operational-state-rvc-cluster.xml [hunk 6]
```diff
@@ -51,7 +51,12 @@ limitations under the License.
     <attribute side="server" code="0x0001" define="CURRENT_PHASE"           type="INT8U"                                    min="0x00" max="0x1F"    writable="false" isNullable="true"  optional="false">CurrentPhase</attribute>
     <attribute side="server" code="0x0002" define="COUNTDOWN_TIME"          type="elapsed_s"                                min="0"    max="259200"  writable="false" isNullable="true"  optional="true">CountdownTime</attribute>
     <attribute side="server" code="0x0003" define="OPERATIONAL_STATE_LIST"  type="ARRAY" entryType="OperationalStateStruct"                          writable="false"                    optional="false">OperationalStateList</attribute>
-    <attribute side="server" code="0x0004" define="OPERATIONAL_STATE"       type="OperationalStateStruct"                                            writable="false"                    optional="false">OperationalState</attribute>
+
+<!--
+The attribute "OPERATIONAL_STATE" herein is applicable to RVC Operational State only and its values are
+additional to the set of values defined in Operational State. So we define the type of this attribute "ENUM8"
```
Comment (bzbarsky-apple) [inline src/app/zap-templates/zcl/data-model/chip/operational-state-rvc-cluster.xml:57]:
```suggestion
The type of this attribute in the spec is OperationalStateEnum, but the OperationalStateEnum in our XML
excludes the values from the base OperationalState cluster.  Just use ENUM8 for the type, so it allows
both values from this cluster and from the base cluster.
additional to the set of values defined in Operational State. So we define the type of this attribute "ENUM8"
```

**Review by bzbarsky-apple — APPROVED** [review]

**Review by jmeg-sfy — APPROVED** [review]
