### PR TITLE
[examples] Extract common Linux platform app start up code

### LINKED ISSUE #6139: all-clusters-app and tv-app on linux fail to advertise over BLE
Both All cluster app and tv-app fail to advertise over BLE on Raspi running Ubuntu OS with CHIP:DL: FAIL: BLE name is NULL in ConfigureBluezAdv

$ sudo ./out/host/chip-all-clusters-app --wifi
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:ZCL: 0xaaaab6fb8f10ep 1 clus 101 attr  3 not supported
CHIP:ZCL: Failed to write DoorState attribute: 0x86
CHIP:ZCL: 0xaaaab6fb8f10ep 1 clus 101 attr 21 not supported
CHIP:ZCL: Failed to write Language attribute: 0x86
CHIP:ZCL: Start identify callback on endpoint 1 time 0
CHIP:ZCL: Stop identify callback on endpoint 1
CHIP:ZCL: WARNING: ATTRIBUTES ARE NOT BEING STORED IN FLASH!
CHIP:ZCL: DEVICE WILL NOT FUNCTION PROPERLY AFTER REBOOTING!!
CHIP:ZCL: Failed to send IAS Zone update. Err 0x70
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x0000000000bc5c01
CHIP:DL: wpa_supplicant: _IsWiFiStationProvisioned: interface not connected
CHIP:BLE: Assigned local session key ID 0
CHIP:BLE: Waiting for PBKDF param request
CHIP:DIS: Start dns-sd server
CHIP:DIS: CHIP minimal mDNS started advertising.
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:SVR: Server Listening...
CHIP:DIS: Start dns-sd server
CHIP:DIS: CHIP minimal mDNS started advertising.
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DL: FAIL: BLE name is NULL in ConfigureBluezAdv
CHIP:DL: Disabling CHIPoBLE service due to error: CHIP Error 4003 (0x00000FA3): Incorrect state

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem

Different apps for linux platform can share init code.

 #### Summary of Changes

Stare them.

- Note: The app startup code is still app related, so we don't put them under platform layer.

 Fixes #6139

### CODE REVIEW

File: examples/platform/linux/AppMain.cpp [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+void EventHandler(const chip::DeviceLayer::ChipDeviceEvent * event, intptr_t arg)
+{
+    (void) arg;
+    if (event->Type == chip::DeviceLayer::DeviceEventType::kCHIPoBLEConnectionEstablished)
+    {
+        ChipLogProgress(DeviceLayer, "Receive kCHIPoBLEConnectionEstablished");
+    }
+}
+
+CHIP_ERROR PrintQRCodeContent()
```
Comment (Damian-Nordic) [inline examples/platform/linux/AppMain.cpp:33]: Do you think it can be replaced with `ConfigurationMgr().LogDeviceConfig()` + `PrintOnboardingCodes` like the other examples or you need to print it on stderr?

File: examples/platform/linux/AppMain.h [hunk 2]
```diff
@@ -0,0 +1,4 @@
+#pragma once
```
Comment (Damian-Nordic) [inline examples/platform/linux/AppMain.h:1]: Add copyright header?

File: examples/platform/linux/AppMain.cpp (hunk 1 above)
Comment (erjiaqing) [reply examples/platform/linux/AppMain.cpp]: Yes, these code is written before these two functions are added. Removed them and use LogDeviceConfig + PrintOnboardingCodes

File: examples/platform/linux/AppMain.h (hunk 2 above)
Comment (erjiaqing) [reply examples/platform/linux/AppMain.h:19]: Thanks

File: examples/platform/linux/AppMain.cpp [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+    {
+        chip::DeviceLayer::ConnectivityMgrImpl().StartWiFiManagement();
+    }
+#endif // CHIP_DEVICE_CONFIG_ENABLE_WPA
+
+#if CHIP_ENABLE_OPENTHREAD
+    if (LinuxDeviceOptions::GetInstance().mThread)
+    {
+        SuccessOrExit(err = chip::DeviceLayer::ThreadStackMgrImpl().InitThreadStack());
+        std::cerr << "Thread initialized." << std::endl;
```
Comment (msandstedt) [inline examples/platform/linux/AppMain.cpp:93]: Shouldn't we use the CHIP logging subsystem here?

**Review by Damian-Nordic — APPROVED** [review]

File: examples/platform/linux/AppMain.cpp (hunk 3 above)
Comment (erjiaqing) [reply examples/platform/linux/AppMain.cpp]: Yes, however, when taking look at other apps, we use the log api provided by platform directly. And when building real apps, the library other than CHIP may also print their log. Maybe we can provide a log module called "CHIPApp" for apps that want to print the logs of calling CHIP apis, or introduce some logging framework to Linux/Posix so we can avoid the use of writting logs to stderr directly?

**Review by msandstedt — APPROVED** [review]

File: examples/platform/linux/AppMain.cpp (hunk 3 above)
Comment (msandstedt) [reply examples/platform/linux/AppMain.cpp]: I guess you're right.  There are cases to be made on either side.  Yes, you can consider libCHIP one of many libraries, all of which have their own logging.  And I don't think we need a separate App logging interface.  In this context, I suppose calling to the CHIP logger simply gives some useful context and log line prefixes.

As an aside, the Linux platform is logging to stdout, not stderr, which itself seems like a poor practice.

File: examples/platform/linux/BUILD.gn [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+import("//build_overrides/chip.gni")
+
+config("chip_examples_project_linux_platform_main_config") {
+  include_dirs = [ "." ]
+}
+
+source_set("chip_examples_project_linux_platform_main") {
```
Comment (mspang) [inline examples/platform/linux/BUILD.gn:21]: Please use shorter names. "examples", "platform", and "linux" are in the directory name and do not need to be repeated here.

Suggest "main".

File: examples/platform/linux/AppMain.cpp [hunk 5]
```diff
@@ -0,0 +1,113 @@
...
+    err = ParseArguments(argc, argv);
+    SuccessOrExit(err);
+
+    err = chip::DeviceLayer::PlatformMgr().InitChipStack();
+    SuccessOrExit(err);
+
+    ConfigurationMgr().LogDeviceConfig();
+    PrintOnboardingCodes(chip::RendezvousInformationFlag::kBLE);
+
+#if defined(PW_RPC_ENABLED)
```
Comment (mspang) [inline examples/platform/linux/AppMain.cpp:67]: This won't work without relocating the `defines`.

**Review by mspang — CHANGES_REQUESTED** [review]

File: examples/platform/linux/BUILD.gn [hunk 6]
```diff
@@ -14,11 +14,11 @@
 
 import("//build_overrides/chip.gni")
 
-config("chip_examples_project_linux_platform_main_config") {
+config("chip_app_main_config") {
   include_dirs = [ "." ]
```
Comment (mspang) [inline examples/platform/linux/BUILD.gn:18]: Why say `chip` ? Everything in this project is related to CHIP.

Note: Here is where you can say

```
import("${chip_root}/examples/common/pigweed/pigweed_rpcs.gni")

if (chip_enable_pw_rpc) {
  defines = [ "PW_RPC_ENABLED" ]
}
```

Totally fine to share that, as long as the `defines` is set here rather than on the `executable`.

Comment (erjiaqing) [reply examples/platform/linux/BUILD.gn:19]: I'm a bit concerned about that what if someone added `chip_enable_pw_rpc=true` when building apps other than the lightingapp.
I guess other apps also need the pw rpc.

Comment (mspang) [reply examples/platform/linux/BUILD.gn:19]: Either way seems ok.

**Review by mspang — APPROVED** [review]
