### PR TITLE
[cirque]: Fix cirque IM test flaky issue

### LINKED ISSUE #5807: since PR#5720, cirque IM test becomes flaky because of the race condition happens
#### Problem
Since PR5720, we see IM cirque test becomes flaky, from the failure log, we see
Bad log
Command Response: 2/2(100.00%) time=0.000ms

Send invoke command request message to Node: 12344321
CHIP:DMG: ICR moving to [AddCommand]
CHIP:-: CHIP Error 4003 (0x00000FA3): Incorrect state at ../../../../../src/app/Command.cpp:279
CHIP:-: CHIP Error 4003 (0x00000FA3): Incorrect state at ../../../../../src/app/CommandSender.cpp:63
Send command request failed: CHIP Error 4003 (0x00000FA3): Incorrect state
ChipCommandSender failed: CHIP Error 4003 (0x00000FA3): Incorrect state

Good log should be
Command Response: 1/1(100.00%) time=0.001ms
CHIP:DMG: ICR moving to [Initialize]

Send invoke command request message to Node: 12344321
CHIP:DMG: ICR moving to [AddCommand]
CHIP:IN: Secure message was encrypted: Msg ID 2
CHIP:IN: Sending msg from 0x000000000001b669to 0x0000000000bc5c01
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status 0
CHIP:DMG: ICR moving to [   Sending]
CHIP:EM: Rxd Ack; Removing MsgId:00000002 fro

See that Reset is not yet call and IM command state does not go to Initialize state in faliure log, but send command request is issued.
IM cirque test is multiple thread program
SendCommandRequest is in one thread
then IM command response processing is in another thread
in DispatchSingleClusterCommand, gCond.notify_one() is called,
before reset is called, the gCond.wait_for(lock, std::chrono::seconds(gMessageIntervalSeconds)) == std::cv_status::timeout) is unblocked
SendCommandRequest happens before reset

 #### Proposed Solution
Add CommandResponseComplete callback, call it after reset

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
 IM test in cirque is flaky.

From the log, we can see the CommandSender moved to [Initialize] state after the app get notified the response messages is processed. That indicates there is a potential bug in our code. We should not notify the app the response message is processed if IM still have remaining work to do.

Before #5720, we use polling to check the response message before we send the next Command Request, so the delay introduced by polling is long enough to cover this problem.

With #5720, IM initiator call gCond.notify_one() immediately after it receives the delegate callback for response message is processed, if gCond.notify_one() trigger context switch, then IM initiator will send the next Command Request before CommandSender reset its state back to [Initialize]

 #### Summary of Changes
Notify the delegate only when Command/Read responses are fully processed.

 Fixes #5807

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

File: src/app/tests/integration/chip_im_initiator.cpp [hunk 1]
```diff
@@ -264,8 +270,6 @@ void DispatchSingleClusterCommand(chip::ClusterId aClusterId, chip::CommandId aC
 
     printf("Command Response: %" PRIu64 "/%" PRIu64 "(%.2f%%) time=%.3fms\n", gCommandRespCount, gCommandCount,
```
Comment (yunhanw-google) [inline src/app/tests/integration/chip_im_initiator.cpp:265]: Please move this printf to the new callback on response processed

**Review by yunhanw-google — APPROVED** [review]
Overall looks good to me, thanks

File: src/app/tests/integration/chip_im_initiator.cpp (hunk 1 above)
Comment (yunhanw-google) [reply src/app/tests/integration/chip_im_initiator.cpp:265]: Please also update the PR comments to reflect this change, thanks

Comment (yufengwangca) [reply src/app/tests/integration/chip_im_initiator.cpp:265]: That is my initial plan, but after I take another look. I found DispatchSingleClusterCommand is only called when CHIP_END_OF_TLV is received, and CommandResponseProcessed is called as long as the response message is processed, it does not check if the message is the end of TLV or not.

Should we still keep the following logic in DispatchSingleClusterCommand? so that the response is not counted if the message is not the end of TLV.

    gCommandRespCount++;

    printf("Command Response: %" PRIu64 "/%" PRIu64 "(%.2f%%) time=%.3fms\n", gCommandRespCount, gCommandCount,
           static_cast<double>(gCommandRespCount) * 100 / gCommandCount, static_cast<double>(transitTime) / 1000);
}

**Comment by andy31415** [comment]
Marking as hotfix because this fixes cirque flakyness.
