### PR TITLE
[ICD] Added a way of activating the report on active mode from icd.gni

### LINKED ISSUE #29217: [BUG] Need to have an actual way of defining ICD_REPORT_ON_ENTER_ACTIVE_MODE
### Reproduction steps

Try to compile with `-Wundef`.  This breaks on ICD_REPORT_ON_ENTER_ACTIVE_MODE.

We should have a clear way of configuring this, which defaults to "false unless someone explicitly said otherwise".

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

b02c9842e3dedc8f81f16760da5c322affdf27ee

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by lpbeliveau-silabs**
Clarifies how to enable report emission on entering active mode, also addresses: https://github.com/project-chip/connectedhomeip/issues/29217

### CODE REVIEW

File: src/app/icd/ICDManager.cpp [hunk 1]
```diff
@@ -33,6 +33,7 @@
 #define ICD_ENFORCE_SIT_SLOW_POLL_LIMIT 0
 #endif
 
+// This can be enable by adding report_on_active to your build arguments
 #ifndef ICD_REPORT_ON_ENTER_ACTIVE_MODE
 // Enabling this makes the device emit subscription reports when transitioning from idle to active mode.
 #define ICD_REPORT_ON_ENTER_ACTIVE_MODE 0
```
Comment (bzbarsky-apple) [inline src/app/icd/ICDManager.cpp:39]: This doesn't make sense: this define is not used anywhere in this file.... why are we defining it at all?

**Review by jmartinez-silabs — APPROVED** [review]

File: src/app/icd/BUILD.gn [hunk 2]
```diff
@@ -34,6 +34,8 @@ source_set("manager-srcs") {
     ":observer-srcs",
     "${chip_root}/src/credentials:credentials",
   ]
+
+  defines = [ "ICD_REPORT_ON_ENTER_ACTIVE_MODE=${chip_report_on_active_mode}" ]
```
Comment (bzbarsky-apple) [inline src/app/icd/BUILD.gn:38]: But how will this get propagated to ReportSchedulerImpl.cpp, which is where this thing is actually used?

File: src/app/reporting/ReportSchedulerImpl.cpp [hunk 3]
```diff
@@ -18,6 +18,11 @@
 #include <app/InteractionModelEngine.h>
 #include <app/reporting/ReportSchedulerImpl.h>
 
+#ifndef ICD_REPORT_ON_ENTER_ACTIVE_MODE
```
Comment (bzbarsky-apple) [inline src/app/reporting/ReportSchedulerImpl.cpp:21]: This change should not be needed if the build config is actually propagating to here correctly, right?

File: src/app/icd/BUILD.gn (hunk 2 above)
Comment (lpbeliveau-silabs) [reply src/app/icd/BUILD.gn:38]: Since ReportScheduler inherits the ICDObserver, this define should be available for ReportSchedulerImpl no?

File: src/app/reporting/ReportSchedulerImpl.cpp (hunk 3 above)
Comment (lpbeliveau-silabs) [reply src/app/reporting/ReportSchedulerImpl.cpp:21]: right, this isn't needed anymore.

File: src/app/icd/BUILD.gn (hunk 2 above)
Comment (bzbarsky-apple) [reply src/app/icd/BUILD.gn:38]: Nope.  If you look at the actual compiler flags used with this PR, it's not in them.  See https://gn.googlesource.com/gn/+/main/docs/reference.md#var_defines for the rules about how "defines" are determined; if A depends on B, it will pick up defines from the public_configs and all_dependent_configs of B, but not defines set directly on B.

More generally, if `src/app/reporting/ReportSchedulerImpl.cpp` is the only thing using this define, shouldn't this define just be defined in the target that builds that file?

Comment (lpbeliveau-silabs) [reply src/app/icd/BUILD.gn]: Moved into src/app/BUILD.gn

File: scripts/examples/gn_silabs_example.sh [hunk 4]
```diff
@@ -214,6 +214,10 @@ else
             #   optArgs+="openthread_root=\"//third_party/connectedhomeip/third_party/openthread/ot-efr32/openthread\" openthread_efr32_root=\"//third_party/connectedhomeip/third_party/openthread/ot-efr32/src/src\""
             #    shift
             #    ;;
+            --report_on_active)
+                optArgs+="chip_report_on_active_mode=true "
+                shift
+                ;;
```
Comment (mkardous-silabs) [inline scripts/examples/gn_silabs_example.sh:220]: I don't think we need a macro for this argument. This is going to have a default config for our LIT ICD examples.
@jmartinez-silabs agree?

File: src/app/BUILD.gn [hunk 5]
```diff
@@ -59,6 +59,7 @@ buildconfig_header("app_buildconfig") {
     "CHIP_CONFIG_ENABLE_EVENTLIST_ATTRIBUTE=${enable_eventlist_attribute}",
     "CHIP_CONFIG_ENABLE_ICD_SERVER=${chip_enable_icd_server}",
     "CHIP_CONFIG_ENABLE_READ_CLIENT=${chip_enable_read_client}",
+    "ICD_REPORT_ON_ENTER_ACTIVE_MODE=${chip_report_on_active_mode}",
```
Comment (mkardous-silabs) [inline src/app/BUILD.gn:62]: Do we use `ifdef` to check the define or `if`?

Comment (lpbeliveau-silabs) [reply src/app/BUILD.gn:62]: `#if ICD_REPORT_ON_ENTER_ACTIVE_MODE`

File: scripts/examples/gn_silabs_example.sh (hunk 4 above)
Comment (lpbeliveau-silabs) [reply scripts/examples/gn_silabs_example.sh]: removed

Comment (jmartinez-silabs) [reply scripts/examples/gn_silabs_example.sh]: yeah I agree, no macro/preset for 1 arg, and if we want to enable it by default when LIT is supported we can set it in the example gni

File: src/app/BUILD.gn (hunk 5 above)
Comment (bzbarsky-apple) [inline src/app/BUILD.gn:62]: OK, so this adds ICD_REPORT_ON_ENTER_ACTIVE_MODE to AppBuildConfig.h.

But the macro is used in `ReportSchedulerImpl.cpp`, which is not including either AppBuildConfig.h or AppConfig.h.  It should include one of those two, I would think, to pick up the macro.  Right now it _might_ be accidentally picking it up via the headers it does include, but that's really fragile.

Comment (lpbeliveau-silabs) [reply src/app/BUILD.gn:62]: Added explicit include of AppBuildConfig.h

**Review by bzbarsky-apple — APPROVED** [review]
